### ISSUE TITLE
Incorrect URL displayed when scheduling a post

### ISSUE THREAD

**Issue by kb61401** [WordPress/gutenberg#10223] opened 2018-09-27 21:30 UTC
**Describe the bug**
After scheduling a post, I receive a message in the side bar confirming that the post has been schedule and listing what the post address will be. However, the URL displayed for what the post address will be isn't what the actual URL of the post is set up as and instead displays the URL that appears when I am previewing the post in draft mode. Gutenberg version 3.9.0.

**Expected behavior**
I expected the URL displayed in the "The post address will be:" to be the final URL of the post.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Comment by saulirajala** [comment] 2018-10-06 18:47
I can confirm this bug. I tested with Safari 12.0 on MacOS 10.13.6 with fresh WordPress install (runs in docker setup of Gutenberg) and pretty permalinks enabled. Actual post url is: `http://localhost:8888/scheduled-post/`, but Gutenberg shows url `http://localhost:8888/?p=19`

<img width="1420" alt="gutenberg-schedule-wrong-url" src="https://user-images.githubusercontent.com/5536354/46574769-5955f500-c9b1-11e8-90a9-f37cddccb449.png">

**Comment by earnjam** [comment] 2018-11-18 01:29
Confirmed. Pages actually show the future pretty permalink URL, but posts are showing the plain permalink, not the pretty version. So there is an inconsistency there. We should probably at least get that part addressed.

Screenshots from `master`:

![image](https://user-images.githubusercontent.com/4267290/48667539-46e9d380-eaa6-11e8-86b8-5c4937630b68.png)

![image](https://user-images.githubusercontent.com/4267290/48667542-55d08600-eaa6-11e8-9850-3ca5a937b1b1.png)

Technically the URL it will be when actually published isn't in use yet, so it needs to be clear that that URL is the future URL.

**Comment by earnjam** [comment] 2018-11-18 18:31
So after digging a bit, this is because it uses the `title` field from the REST API response. That is generated using `get_permalink()`, which operates differently between pages, custom post types, and other `_builtin` post types (i.e. posts) for posts with a status of `future`.

See: https://core.trac.wordpress.org/changeset/31114

I think the solution here is to use [`getPermalink()`](https://github.com/WordPress/gutenberg/blob/c60894e71602842f98b68801ef00f1118f04a842/packages/editor/src/store/selectors.js#L2095) instead of [`post.link`](https://github.com/WordPress/gutenberg/blob/c60894e71602842f98b68801ef00f1118f04a842/packages/editor/src/components/post-publish-panel/postpublish.js#L82).

**Comment by jorgefilipecosta** [comment] 2019-06-12 10:53
I'm closing the issue as it seems now we don't have the UI that shows the future post address.

**Comment by jorgefilipecosta** [comment] 2019-06-12 10:53
Thank you all for reporting and discussing this issue!

**Closed by jorgefilipecosta** 2019-06-12 10:53 UTC
Labels: [Component] Permalink, [Component] Saving, [Type] Bug

**Comment by earnjam** [comment] 2019-06-12 13:29
> I'm closing the issue as it seems now we don't have the UI that shows the future post address.

Should we though? Should the post publish panel show the future address instead of the current one for scheduled posts?

The old editor showed the future post URL in the permalink space:
![image](https://user-images.githubusercontent.com/4267290/59355058-55266800-8cf4-11e9-95ed-4b0c9d95dd07.png)

We're doing that now, but the post publish panel is a new concept. Should we customize it to display the future URL there instead of the current when it's a scheduled post?
