### ISSUE TITLE
No way to reset custom font size back to default

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38932] opened 2022-02-20 06:34 UTC
### Description

If you set a custom font size, there's no way to reset it back to the default size. Even if you click the _Set custom size_ icon again, to return to the dropdown, it still thinks it's using a custom size and doesn't automatically return to the default size. The only way to get back to the default size is by manually removing the text in the Size input field, or manually reselecting the _Default_ size from the dropdown.

Vid: https://share.getcloudapp.com/P8u64Ez0

The old typography tools had a convenient `Reset` button that allowed you to reset back to the default size. The new UI changes to the Typography tools (and the color tools) have made them considerably worse than what they were previously. You've made changing typography settings harder and more time consuming.

The previous and better typography tools:
![paragraph-block](https://user-images.githubusercontent.com/2078245/154830957-522926bf-b680-4a6d-89eb-c93280b1a051.jpg)

The keyboard delay between typing the text and the numbers appearing in the Input field is also way too slow, as you can also see in the video above.

### Step-by-step reproduction instructions

- Click on a paragraph block
- Click the Set custom size icon
- Enter a custom font size (e.g. 80px)
- See that there's no option to reset the custom size back to the default size
- Click the Set custom size icon again
- See that the control is still using the custom size you entered

### Environment info

WP 5.9
Twenty Twenty One
Firefox 97.0.1
macOS 12.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-02-21 09:54
👋 @maddisondesigns, thanks for creating the issue!

I think the title is a bit misleading as per your own description:

>The only way to get back to the default size is by manually removing the text in the Size input field, or manually reselecting the Default size from the dropdown.

So there are ways to reset to default and most importantly you can reset values through the ToolsPanel UI, which is the direction we want to follow for reseting control values.

https://user-images.githubusercontent.com/16275880/154929830-9c2aa2c7-072b-418f-a656-94a868e79f64.mov

There are discussions about refining the ToolsPanel UX further to make it more clear that it can be used to reset values. Check discussions in this issue: https://github.com/WordPress/gutenberg/issues/38219


>Even if you click the Set custom size icon again, to return to the dropdown, it still thinks it's using a custom size and doesn't automatically return to the default size.

This is expected and the button just switches to another UI and in addition provides useful information about the selected custom input.

**Comment by annezazu** [comment] 2022-02-21 19:08
I'm going to close this issue out as I see it as a duplicate of https://github.com/WordPress/gutenberg/issues/38219 and would love to see the convo continue there.

**Closed as completed by annezazu** 2022-02-21 19:08 UTC
Labels: [Feature] Design Tools
