### ISSUE TITLE
RichText: Difficult to add content on table

### ISSUE THREAD

**Issue by jaydeeprami** [WordPress/gutenberg#15661] opened 2019-05-15 14:47 UTC
**Describe the bug**
It's very difficult to add content on table when have a large content for the left cells.

When we create table (2*2) and then add large content only the left cells and then try to add content on the top of the right cell and it's very difficult as Richtext area only access on middle part.

-  Same problem if Enable/Disable `Fixed width table cells` option

**To reproduce**
1. Go to any Page and add Table block
2. Create 2*2 table block
3. Add large content on the left cell
4. Try to add content on the right cell, Can not click on top part as cursor is not accessible.
5. Tried with Enable/Disable `Fixed width table cells` option

**Expected behavior**
I can access RichText area part entirely

**Screenshots**
![screenshot-appbossnew test-2019 05 15-19-50-39](https://user-images.githubusercontent.com/15060983/57784775-20071400-774e-11e9-9543-2f683d5e3979.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [74.0.3729.131]

**Additional context**
- WordPress 5.2
- Twenty Nineteen (Version: 1.4)

**Comment by talldan** [comment] 2019-07-18 04:01
Thanks for the report @jaydeeprami. I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/14904.

If it's ok I'll close this in favour of that one. I'll add a comment over on that issue mentioning this.

**Closed by talldan** 2019-07-18 04:01 UTC
Labels: [Block] Table
