### ISSUE TITLE
Block Inserter: Manually close the block inserter panel.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#33138] opened 2021-07-01 14:26 UTC
## What problem does this address?

I have come across to support requests.

From Aleksandar (@jashimili)
https://wordpress.org/support/topic/stop-gutenberg-sidebar-disappearing-when-edit-code-in-editor/

"When I click to edit any part of the editor text or code, the gutenberg sidebar disappears, now I know this is new update so it might be normal to work that but it is really annoying that every time I click to write paragraph text, whole page move to the side.
Please take a look at the photos, Is it possible to keep the sidebar sticky all the time."

GregW (@gwmbox)
https://wordpress.org/support/topic/pin-browse-all-blocks-on-left/
In the page/post editor, is there a way to pin the left sidebar column that shows all the blocks available to be pinned there, e.g. when you select the plus icon on the top or the Browse all link as you go to add/edit any block?

## What is your proposed solution?

I have two suggestions.

1. Pin the Block inserter panel so it stays open until the user clicks the pin to close it.

![Pin-Block-Inserter-Panel-to-Stay-Open](https://user-images.githubusercontent.com/5323259/124140231-98450680-da88-11eb-988f-8d10cf2b3596.jpg)

2. The other suggestion is to add a pin Block Inserter panel option into Preferences.

![Preferences-Manually-close-the-Block-Inserter](https://user-images.githubusercontent.com/5323259/124142264-5f0d9600-da8a-11eb-8cd4-aca11cb3c337.jpg)

 
Option 2 could make it so that the user clicks the + sign to open the Block Inserter and the x sign to close it. The interface would be more hidden. As an option under preferences instead of having a pin in the Block Inserter panel to create a sticky.

Associated older and now closed issue:
https://github.com/WordPress/gutenberg/issues/22871

**Comment by javierarce** [comment] 2021-07-01 15:30
I admit that I also find the auto-closing behaviour annoying and would want the left sidebar to act like the right one (or the List View!): staying open until it gets manually closed. 

Comparing the Block inserter and the List View makes me think that part of the problem is how these two sidebars appear on the page. Maybe this has been suggested before, but I think that if we'd like the inserter to autoclose itself (like it does now), this sidebar could float above the content without disrupting the elements of the canvas. Only sidebars that will remain fixed should displace the content. 

That said, I think both of your solutions could work, @paaljoachim, but I feel we could rethink the basic behaviour of this sidebar first.

**Comment by richtabor** [comment] 2021-07-03 00:21
I’m down for consistency. No other sidebars go away, even when you add patterns (with Gutenberg active) I believe. I’m not sure of a UX pattern where you’d want the sidebar to go away - unless you’re adding just one block (which I assume is very infrequently).

**Comment by karmatosed** [comment] 2021-09-10 14:49
I agree with @javierarce and I think that rethinking the behaviour of the sidebar is better than the proposed solutions. Adding a pin seems to add more cognitive load to me at this point. It might work with an iterated experience, but in the context of what we have, I am not convinced. I think we have enough feedback to close this and start thinking about other experiences around this area. Really getting to the root of the experience feels better than patching what seems to be an issue for users.

Note: I am closing to encourage the opening of other ideas, this issue seems to focus on one particular solution so others can open in new issues.

**Closed as completed by karmatosed** 2021-09-10 14:49 UTC
Labels: [Type] Enhancement, [Feature] Inserter, Needs Design Feedback, Needs Design
