### ISSUE TITLE
[Widgets Screen] Drag & dropping legacy text widget sometimes causes breakage

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26236] opened 2020-10-17 03:07 UTC
**Describe the bug**

When dragging & dropping the text legacy widget into a new widget area, the text area disappears. 

**To reproduce**
1. Go to Appearance > Widgets and add at least one text widget with some text. 
2. Install and activate Gutenberg. 
3. Head to Appearance > Widgets
4. Drag the legacy text widget into a new widget area.
5. See that the editor section is gone.

**Expected behavior**

I expect to still be able to still see the editor for the body of the text widget.

**Screenshots**

Here's a 1 min video: https://cloudup.com/cRK4CZJGQn3

Here's what it looks like after dragging and dropping:

<img width="735" alt="Screen Shot 2020-10-16 at 9 07 29 PM" src="https://user-images.githubusercontent.com/26996883/96327082-9c60ef00-0ff3-11eb-8d63-8faf4cb5c06d.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by draganescu** [comment] 2021-02-18 15:12
I can confirm this.

**Comment by noisysocks** [comment] 2021-04-26 06:12
When I test this I'm not able to drag and drop anything into a new widget area.

**Comment by talldan** [comment] 2021-04-27 06:20
I couldn't reproduce the issues mentioned.

When dragging into an empty widget area, I'm seeing that the blue insertion point line doesn't appear. But dropping in the right place (when the cursor has the + symbol) still works.

What's everyone else seeing?

**Comment by noisysocks** [comment] 2021-04-28 01:49
~Aha I see. The problem I noticed is that you cannot seem to drag and drop into an **empty** widget area.~

**Edit:** Sorry, it does work! It's just that without the blue line it's really hard to tell where you need to release the mouse.

**Comment by tellthemachines** [comment] 2021-04-29 03:49
I could repro this up to 10.4.1, but can no longer with 10.5 or with the latest trunk. Let's close it as fixed.

**Closed by tellthemachines** 2021-04-29 03:49 UTC
Labels: [Block] Legacy Widget, [Feature] Drag and Drop, [Feature] Widgets Screen, [Type] Bug
