### ISSUE TITLE
Can not insert patterns inside the Group block

### ISSUE THREAD

**Issue by decodekult** [WordPress/gutenberg#26281] opened 2020-10-19 15:14 UTC
**Describe the bug**
Tryin gto insert a pattern into a Group block does insert it outside of the Group block. The "inline" inserter for the Group blok does not keep the position as the usual native main inserter does.

I have checked this with a couple of plugins that provide nested blog structures and use the `DefaultBlockAppender` component and they all behave the same and show the same problem.

**To reproduce**
1. Add a page and insert a Group block.
2. Click on the inline inserter inside the Group block, likely using this `DefaultBlockAppender` component.
3. Scroll down in the dialog and click on the button to "Browse all". This will open the main inserter in the top left corner of the editor.
4. Select anything to insert, a block or a pattern, and see that it gets inserted above the Group block.
5. Given that there is no other way tos elect patterns to insert (compared to blocks, that can be inserted right from the `DefaultBlockAppender` component), this prevents inserting patterns inside other blocks.

**Expected behavior**
When using the main inserter and the `DefaultBlockAppender` inserter, blocks and patterns should be inserted where they were called.

**Editor version:**
- WordPress version: 5.6-alpha-49152
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin.
- If the Gutenberg plugin is installed, which version is it? 9.1.1

**Desktop:**
 - OS: Windows 10 Home
 - Browser Firefox
 - Version 81.0.2

**Comment by talldan** [comment] 2020-10-20 00:10
This looks like a duplicate of #24403, I'll add a comment there to say the issue also affects patterns.

**Closed by talldan** 2020-10-20 00:10 UTC
