### ISSUE TITLE
Page template changes aren't reflected in preview

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#17727] opened 2019-10-02 19:39 UTC
### Steps to Reproduce

1. Switch to a theme that has page templates (e.g., TwentyTwelve).
1. Assign a template via `Page Attributes > Template`, update the page, and preview. Notice that the previewed page is rendered using the chosen template.
1. Change the page template without updating the page, and preview again. Notice that the previewed page is still rendered using the old template.

**Comment by determin1st** [comment] 2019-10-09 20:36
I'm on WP 5.2, no difference.. Why is this a "bug"? No update == No changes in preview. Logic.

**Comment by jorgefilipecosta** [comment] 2019-10-10 10:54
Hi @iandunn, @determin1st, thank you for your tests and debugging! Unfortunately, I was unable to replicate this issue.
Each time I pressed preview, the page template was updated in the preview as expected.
My tests were done on Gutenberg master.
One important thing to note is that the templates here define the widget areas that appear.
So when I tested at the start, there were no widgets in any area, and it seemed that changing the template did not affect at all. Then I added a different widget on each widget area for testing purposes, and I was able to see differences in each template change.

Would it be possible to check if the widget areas are different between each other and retest the case on Gutenberg master?
Thank you in advance!

**Comment by iandunn** [comment] 2019-10-11 00:12
🤔 

I retested on `master` and got the same results as before, but can't think of why it isn't happening in your tests. 

To demonstrate that it's not a issue w/ missing widgets, this still reproduces it for me:

1. Switch to TwentyTwelve.
1. Add some widgets to `Main Sidebar` if there aren't already.
1. Assign `Default template`, `Update`, and `Preview`. Notice that the sidebar appears.
1. Change the template to `Full width...no sidebar`, click `Preview` (without updating), and the sidebar is still there.
1. Go back and click `Update`, and the preview tab automatically refreshes, and the sidebar is no longer there.

**Comment by aduth** [comment] 2020-03-10 16:26
This may be attributable to the fact that preview autosaves are limited to only saving a few fields, not including page template:

https://developer.wordpress.org/reference/hooks/_wp_post_revision_fields/

>Filters the list of fields saved in post revisions.
>
>Included by default: ‘post_title’, ‘post_content’ and ‘post_excerpt’.

I'm not entirely familiar with the history here, but it's my understanding that it's a longstanding issue.

The reason there may have been different results in testing is that the specific saving behavior varies by post status. Draft posts are saved outright. Only published posts save revisions. Thus, I expect that the issue reported here is specific to previewing changes to already-published posts.

**Comment by jorgefilipecosta** [comment] 2020-03-10 16:30
I did a new set of tests and I'm able to reproduce this issue for published posts on Gutenberg master and WordPress 5.3.2 without Gutenberg.

**Comment by aduth** [comment] 2020-03-10 17:27
Upstream ticket (from 2009): https://core.trac.wordpress.org/ticket/11049

Technically speaking, this would still require changes from Gutenberg end, since we do not currently pass all fields when persisting an autosave:

https://github.com/WordPress/gutenberg/blob/b98465726e14100cd4f176aebe8c9890a1934a9e/packages/core-data/src/actions.js#L317

Possible action items:

- Is there any reason this should be different in its logic, vs. passing all modified properties? Even if core doesn't yet handle them.
- At least, this should respect the `_wp_post_revision_fields` filter, since a plugin or theme could theoretically extend this to include additional fields to autosave.

**Comment by paaljoachim** [comment] 2021-05-06 22:04
Testing with WordPress 5.7. Gutenberg plugin 10.5.4. Twenty Twenty One.

The bug is still there. I tested creating two page templates. Refreshing the page the new page templates showed up. As these do not show up automatically in the Page template selection drop down after having created these. The newest page template was seen on the frontend. Selecting another page template did not show the new but the last created page template. Some kind of automatic updating is needed here.

@youknowriad

**Comment by paaljoachim** [comment] 2021-05-09 07:25
Riad mentioned that this issue would be better to add to Trac. https://github.com/WordPress/gutenberg/issues/31567#issuecomment-834142438
"That's related to a very old behavior for autosaves in Core that is very unlikely to change. It might be better as a trac ticket actually."

**Comment by annezazu** [comment] 2024-08-20 19:37
Closing this out due to current trac issue with the same focus: https://core.trac.wordpress.org/ticket/11049

**Closed by annezazu** 2024-08-20 19:37 UTC
Labels: [Type] Bug, [Feature] Themes
