### ISSUE TITLE
Post preview does not work

### ISSUE THREAD

**Issue by highjewellerydream** [WordPress/gutenberg#9820] opened 2018-09-12 11:51 UTC
**Describe the bug**
Post preview is not generated when clicking on the Preview button.

**Desktop (please complete the following information):**
 - OS: Mac OS X High Sierra 10.13.6
 - Browser Safari
 - Version 11.1.2

**Additional context**
- running on WordPress 4.9.8 (Wordpress.com)

**Comment by designsimply** [comment] 2018-09-12 14:08
I tested Preview using both Gutenberg 3.7 and 3.8.0-rc.1 just now. I tested with Safari 11.1.2 and Firefox 62.0 on macOS 10.13.6 and the Gutenberg demo post in my test. The preview option is working in my test, so it will help to have a bit more information about your situation.

What happens exactly when you click preview? 

Do you see any message or does the button not work at all?

Some people have reported problems in the past with previews if they were using Cloudflare, however, Cloudflare released a fix for an issue which many reported solved the problem. Are you using Cloudflare or anything like it?

**Comment by designsimply** [comment] 2018-09-20 13:18
I am closing this util we can get more information and because there are not any steps to reproduce the problem on other sites.

**Closed by designsimply** 2018-09-20 13:18 UTC
Labels: [Status] Needs More Info
