### ISSUE TITLE
Cannot add a subset of tags to the Query Block query controls if there are over 100 tags

### ISSUE THREAD

**Issue by mwnciau** [WordPress/gutenberg#40474] opened 2022-04-20 12:56 UTC
### Description

Currently, the query controls for the query block will only bring through 100 of each type of taxonomy. See https://github.com/WordPress/gutenberg/blob/4d9af43e91d50853b4da0627863e008ae0b74a5d/packages/block-library/src/query/edit/inspector-controls/taxonomy-controls.js#L41

Once, e.g. you have more than 100 tags, there will be some tags that you are unable to add because they're not on the suggestion list. The query controls won't let you add custom tags that aren't in the suggestions list.

### Step-by-step reproduction instructions

Create over 100 tags for a site. Try to add each tag to a query block controls. You will be unable to add some tags.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-05-05 10:46
Thanks for the issue @mwnciau ! I'll close this as a duplicate of https://github.com/WordPress/gutenberg/issues/33581

**Closed as completed by ntsekouras** 2022-05-05 10:46 UTC
