### ISSUE TITLE
Site Editor: smoother transitions to selected blocks

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29352] opened 2021-02-25 19:20 UTC
One thing that was raised during Site Editor testing was that clicking on a particular block will immediately scroll to that part of the page, which can sometimes be confusing if it's a group block that occupies a bigger chunk of the page.

We can consider adding a smoother transition here, like a bit slower scrolling of the selected section into view.

**Comment by paaljoachim** [comment] 2021-03-08 21:43
Hi @vindl Marko
Can you add an animated gif or a mp4 to show what you mean?

**Comment by vindl** [comment] 2021-03-10 14:25
Hi @paaljoachim,

I think this happens only when the Site Editor loads, while it's still in select mode:

https://user-images.githubusercontent.com/1182160/110643724-b1ae0400-81b4-11eb-9438-587816c962d6.mp4

The same happens when navigating through persistent list view now. Anyway, not that high priority but maybe nice to have. :)

**Comment by paaljoachim** [comment] 2021-03-13 19:43
Thanks Marko!
Going back to your original comment.
Selecting a block further down the page/post in List View should scroll to the block instead of it jumping directly to it.

Current behavior. 

https://user-images.githubusercontent.com/5323259/111042228-9ead6500-843c-11eb-8a73-6d7d8f7c1a98.mp4

Having a smooth scroll feels like a good win to add

**Comment by paaljoachim** [comment] 2022-05-26 22:01
@draganescu @ntsekouras @adamziel  @ZebulanStanphill 

The reason why I am pinging all of you is that I am doing some exploring on clicking an anchor link and noticing how jumps  right away to the place on the page it is in. Can we add a smooth scroll? 

Case:
Clicking somewhere in the List block and having a smoother scroll to the location on the page the item clicked is seen.
Clicking an anchor link and having a smoother scroll as it goes to the area of the page the receiving link it located.

What do you think?

**Comment by draganescu** [comment] 2022-05-27 12:18
> Clicking somewhere in the List block and having a smoother scroll to the location on the page the item clicked is seen.

This can quickly become dizzying if you mis-click three times in the list view. 

Somewhat related experience: in most IDE-s there is the option to sync the file explorer to the currently open file. The sync means that in the file explorer panel you always have the folder nesting expanded and the currently viewed file selected and the view scrolled to there. I always think it's a good idea until I am really into some multiple files madness and the file explorer is always _not_ where I expect it to be.

My two cents: I think that scrolling to location should not be animated when clicking the list view, and that scrolling to location in select mode could have a small ease in.

**Comment by youknowriad** [comment] 2023-02-24 12:42
I'm not reproducing this issue when clicking blocks. Scroll position is preserved. Closing let me know if I missed anything.

**Closed by youknowriad** 2023-02-24 12:42 UTC
Labels: Needs Design Feedback, [Feature] Site Editor
