### ISSUE TITLE
Latest Comments Block HTML validation

### ISSUE THREAD

**Issue by NenadObradovic** [WordPress/gutenberg#8253] opened 2018-07-27 12:23 UTC
Hi guys,

Could you please consider to change article html tag inside this block or to modify it, because article tag require heading element inside them, in otherwise we will get html validation notice? Thanks

> Article lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all articles.

Best regards,
Nenad

**Comment by ashwin-pc** [comment] 2019-04-05 05:27
This is also the case with the comments section of Wordpress. A ticket has been raised on https://core.trac.wordpress.org/ticket/39044. The comment thread there suggests that this has not been changed yet to maintain backward compatibility with themes until its impact with themes can be assessed. Wouldn't the same concern apply here?

**Comment by noisysocks** [comment] 2020-04-30 05:24
The Latest Comments block is matching the markup that Core uses for comments, so closing this as a duplicate of https://core.trac.wordpress.org/ticket/39044. We can re-open this issue if a decision is made in that downstream ticket.

**Closed by noisysocks** 2020-04-30 05:24 UTC
Labels: [Block] Latest Comments, [Feature] Blocks, [Type] Enhancement
