### ISSUE TITLE
Is there a way to remove the .is-style prefix in an element?

### ISSUE THREAD

**Issue by pmqa** [WordPress/gutenberg#17554] opened 2019-09-24 15:15 UTC
I'm using **wp.blocks.registerBlockStyle** to add a style variation to a text element: 

`wp.blocks.registerBlockStyle( 'core/heading', {
		name: 'default',
		label: 'Default',
		isDefault: true,
	} );
`

Is there an option to remove the **.is-style** prefix that appears in this element, in this case **.is-style-default**? 

Maybe we could add a `hasPrefix: false` parameter?

**Comment by swissspidy** [comment] 2019-09-24 19:25
What‘s the use case for that?

The default style doesn‘t add a class name anyway AFAIK.

**Comment by pmqa** [comment] 2019-09-25 08:08
A cleaner style (sass) codebase. Being able to use the same cleaner style classes everywhere: **.page-title** instead of **.is-style-page-title**.

**Comment by jstrangfeld** [comment] 2019-09-30 20:20
This is a duplicate of #11763

**Closed** 2019-10-01 08:34 UTC
Labels: Block API, Needs Technical Feedback, [Component] Style Variations, [Status] Duplicate, [Type] Enhancement
