### ISSUE TITLE
Stuck tooltips

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3481] opened 2017-11-14 16:50 UTC
Happens often that I end up with stuck tooltips in the UI:

![image](https://user-images.githubusercontent.com/548849/32792663-38182280-c964-11e7-9605-6b4479f89b8a.png)

**Comment by aduth** [comment] 2017-11-14 17:18
Needs reliable steps to reproduce. I cannot recreate this issue.

Previous issues with disabled buttons were intended to be addressed in #3177.

**Comment by ephox-mogran** [comment] 2017-11-15 06:01
I can't replicate this sporadically. I'll see if I can get a replication case.

**Comment by ephox-mogran** [comment] 2017-11-15 06:30
I've only seen it happen with `Redo`, so it probably is a race condition somewhere with disabling and mutation observers.

**Comment by ephox-mogran** [comment] 2017-11-15 06:38
I've got `Undo`'s popover sticking as well. Also when disabled.

**Comment by ephox-mogran** [comment] 2017-11-15 06:39
Essentially, before it happens, the button is disabled but if you hover over that disabled button, the tooltip still appears.

**Comment by ephox-mogran** [comment] 2017-11-15 06:46
Still not 100%, but I have it happening regularly now.

**Comment by ephox-mogran** [comment] 2017-11-15 06:52
An interesting part of it is that when you move the cursor over the buttons in the toolbar, the tooltip will only appear if you have previously moved over a non-disabled button. If you have moved over a disabled button, then the tooltip won't appear. I think it is related to that.

**Comment by ephox-mogran** [comment] 2017-11-15 06:57
The best replication case I have is focus the PostTitle, and move the mouse left and right past either end of the header toolbar, stopping at each end. You don't need to click at all. Vary the speed and within a minute, it will probably happen once.

**Comment by aduth** [comment] 2017-11-15 14:33
>The best replication case I have is focus the PostTitle, and move the mouse left and right past either end of the header toolbar, stopping at each end. You don't need to click at all. Vary the speed and within a minute, it will probably happen once.

Nice steps. I was eventually able to reproduce.

It seems that the issue is occurring at this check:

https://github.com/WordPress/gutenberg/blob/3f31557f91b1b65e0258533a2c4126931e4e207c/components/tooltip/index.js#L125-L133

Where in some cases the event target is children of the SVG, in my experience a `path` node which is _not_ disabled. I think it may be a matter of changing this to test `event.currentTarget`, i.e. the node being wrapped (the possibly-disabled button).

**Closed** 2017-11-16 18:43 UTC
Labels: Chrome, [Status] Needs More Info, [Type] Bug
