### ISSUE TITLE
[@wordpress/core-data] getEntityRecords and saveEntityRecord don't sync data correctly

### ISSUE THREAD

**Issue by samueljseay** [WordPress/gutenberg#22127] opened 2020-05-06 06:45 UTC
**Describe the bug**
When using `getEntityRecords` and `saveEntityRecord` within a single component, I expect that when `saveEntityRecord` is called, we will not see another fetch of the data (`getEntityRecords`) until the `saveEntityRecord` data is finished saving.

What I see instead is that on call of `saveEntityRecord` the cache is invalidated too soon and `getEntityRecords` fetches stale data. This causes flickers and the data on screen to be out of date. I have tested this behaviour in `withSelect` and also `useSelect` and it behaves the same way in both.

When debugging I found it hard to always get consistent behaviour which makes me think a race condition exists, but quite frequently I do see that core-data's `saveEntityRecord` triggers 2 `RECEIVE_ITEMS` [actions here](https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/actions.js#L421), the first of which invalidates the cache conditions for `getEntityRecords` [defined here](https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/resolvers.js#L105).

I'm not sure if this is a red herring at this stage, but I couldn't find another reason for the immediate fetch behaviour. 

Additionally this issue seems similar to others I've seen such as https://github.com/WordPress/gutenberg/issues/19132 but this is in the context of core-data so I felt like it should be a unique issue.

**To reproduce**
I have produced a minimal reproduction in a [dummy plugin in a branch here](https://github.com/samueljseay/gutenberg/tree/minimal-repo-data-sync-issue). You should be able to run it as you would normally run gutenberg in development, go to the core data issue plugin and see a list of items, as you check the items they will either flicker back and forth from their checked state or start to get out of sync very quickly. 

The code responsible for the fetch/save functionality [is here ](https://github.com/samueljseay/gutenberg/blob/minimal-repo-data-sync-issue/test-plugins/core-data/js/index.js)

**Expected behavior**
The expected behaviour would be that the checkbox would finish saving completely before the new collection is fetched. This would allow the fetched data to be completely up to date.

**Screenshots**
![reproduce-issue](https://user-images.githubusercontent.com/1281828/81144786-e8c9ec80-8fc8-11ea-9b91-f2d6c8aacebe.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5-alpha-47766 (in development mode) but I've seen it in 5.4 as well.
- "gutenberg plugin"

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser Chrome
 - Version 81.0.4044.129

**Comment by chriskmnds** [comment] 2020-05-08 11:35
This seems related: https://github.com/WordPress/gutenberg/pull/19752 Similar issue with flickering when updating.

**Comment by noisysocks** [comment] 2020-10-13 05:32
It looks like @adamziel ran into this here, so I'm removing Needs Testing: https://github.com/WordPress/gutenberg/pull/25859#issuecomment-707189106

**Comment by adamziel** [comment] 2020-10-19 16:53
This bites us a lot in the widgets editor, let's take a stab at it as soon as possible cc @noisysocks @draganescu @TimothyBJacobs @youknowriad.

**Comment by adamziel** [comment] 2020-11-03 11:45
https://github.com/WordPress/gutenberg/pull/26627 and https://github.com/WordPress/gutenberg/pull/26575 improved the situation here. There is much less flickering, although there is still some of it as seen below:

![core data issue](https://user-images.githubusercontent.com/205419/97978252-988fe380-1dcd-11eb-9d45-cb39d66b21ea.gif)

I think locks would be the ultimate solution here. The downside is that they would add a layer of complexity to an already complex core-data so I'm still trying to come up with some alternatives. But for reference, see the same interaction with https://github.com/WordPress/gutenberg/pull/26389 applied:

![2020-11-03 12-41-39 2020-11-03 12_41_59](https://user-images.githubusercontent.com/205419/97981160-266dcd80-1dd2-11eb-8d52-71be2ef2957c.gif)

cc @youknowriad @samueljseay

**Comment by adamziel** [comment] 2020-11-03 14:50
The flicker on my first gif above is caused by:

1. I save an entity record `book` with `ID = 11` , no resolution is triggered, we’re good, `PUT#1` request is waiting for response.
1. I save an entity record `book` with `ID = 10` , no resolution is triggered, we’re good, `PUT#2` request is waiting for response.
1. The `PUT#1` finishes, invalidates the entity. I have a `useSelect` call that calls `getEntityRecords()` . A `GET` request is issued and awaits response.
1. Now comes the tricky part. Once the `GET` is finished, it will issue `RECEIVE_ITEMS` and update the list of entities, including the ones handled by `PUT#2`.

Different things could happen depending on the resolution order too.

**Comment by adamziel** [comment] 2020-11-10 15:42
Since https://github.com/WordPress/gutenberg/pull/26389 is now merged, I'm closing this one. Feel free to comment or reopen if the fix did not fully help!

**Closed by adamziel** 2020-11-10 15:42 UTC
Labels: [Package] Core data
