### ISSUE TITLE
WP 6.3-beta3 front-page template shows static page on initial loading

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#52388] opened 2023-07-06 17:50 UTC
### Description

As I understand, we have now two options in FSE themes: home.html template and front-page.html. If theme has home.html template, then Settings - reading option is used on front page of site. If front-page, then settings - reading is ignored and only front-page is used

In 6.3 beta, if theme uses front-page.html and if I visit /wp-admin/site-editor.php I see empty screen. And it looks like now it uses settings - reading setup which has no sense, because on Frontend side, front-page template is used.

### Step-by-step reproduction instructions

1. Install any theme which has front-page.html (for example, Greenshift)
2. Set static page in settings - reading
3. Visit /wp-admin/site-editor.php
4. I expect to see front-page template. Instead of this, I see empty screen or screen of static page

### Environment info

- 6.3 beta 3 version of WP

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-07-06 23:11
Nearly positive this is a duplicate of https://github.com/WordPress/gutenberg/pull/52266 on second glance. Can you confirm @wpsoul ?

**Comment by wpsoul** [comment] 2023-07-07 00:01
Not exactly. That ticket describes workflow when Home template is existed (for example in 2023 theme), but my scenario is about Frontpage. If I have next in theme, options in Settings - reading must be ignored and I must have Front Page template when I open site editor. This way it worked in 6.2

![templates 2023-07-07 02-59-02](https://github.com/WordPress/gutenberg/assets/4378263/da4f9bc3-7f3e-4611-b251-b505cdae4198)

**Comment by annezazu** [comment] 2023-07-10 16:48
@ramonjd in case you can take a look!

**Comment by ramonjd** [comment] 2023-07-11 02:52
> Nearly positive this is a duplicate of https://github.com/WordPress/gutenberg/pull/52266 on second glance.

Yeah, despite the very misleading title, that PR was a little different in that it related specifically to the pages list.

I've tested the steps described in this issue on WordPress 6.3-beta3-5619 with both Gutenberg 16.2 activated and deactivated and can reproduce using the Greenshift theme. Checked a few others. Porcupine works. 

Greenshift has a lot of block validation errors:

<img width="1411" alt="Screenshot 2023-07-11 at 12 46 21 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/c78e9a58-3af7-4d0f-85ba-35ad3e3ea4b6">

So when I remove most of those blocks from the front page template, it loads

<img width="1050" alt="Screenshot 2023-07-11 at 12 49 14 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/e3c8a47d-a5c0-419e-95d3-f192098d0eb5">


emptytheme, 2023, 2022 load well. I tested by both:

- Creating a front-page template via the Site Editor template management page, and
- Creating a `front-page.html` in my theme directory

**Comment by wpsoul** [comment] 2023-07-12 01:02
I retested on latest beta build. Error with wrong front page template is gone. I found validation errors, but it looks like bug from core. Custom image size now is rendered also in style tag. I see this bug not only in theme, but in many patterns, for example

![fronts](https://github.com/WordPress/gutenberg/assets/4378263/95e8c032-8764-43bd-aa0c-92aef750ea12)

**Comment by wpsoul** [comment] 2023-07-12 01:08
Found where this block. It's in Woocommerce pattern which is called "Testimonial Single"

**Comment by ramonjd** [comment] 2023-07-12 01:36
Nice sleuthing @wpsoul 

The styles were introduced in https://github.com/WordPress/gutenberg/pull/51545 [here](https://github.com/WordPress/gutenberg/pull/51545/files#diff-a14b61c874095649b236b78413e805b4541277b24eb71ce350a17d9f2b6396b1R568)

I think it should have added a deprecation cc @ajlende 

Here's the template: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/testimonials-single.php

Running this through 6.3 Beta:

Content generated by `save` function:

```html
<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%;width:164px;height:164px" width="164" height="164"/></figure>
```
Content retrieved from post body:

```html
<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%" width="164" height="164"/></figure>
```

**Comment by jordesign** [comment] 2023-07-18 03:38
@ramonjd Just looping back to this one - as notes in #51545 suggest this is a different issue?

**Comment by ramonjd** [comment] 2023-07-18 03:52
Thanks @jordesign 

Confirmed, what I said [above](https://github.com/WordPress/gutenberg/issues/52388#issuecomment-1631721808) was bunk.

Explanation [here](https://github.com/WordPress/gutenberg/pull/51545#discussion_r1263976152): 

> This is part of edit, not save, so it shouldn't affect block deprecations. In a follow-up https://github.com/WordPress/gutenberg/pull/52286, @draganescu added styles to save, but he did add a deprecation for them.

**Comment by draganescu** [comment] 2023-07-19 14:10
@ramonjd is thre anything wrong with https://github.com/WordPress/gutenberg/pull/52286? Once the content is migrated do the errors persist? I did add a deprecation wihich does not include the style. Maybe I forgiot to do something (I am constantly unsure about deprecations).

**Comment by ramonjd** [comment] 2023-07-19 21:30
> @ramonjd is thre anything wrong with https://github.com/WordPress/gutenberg/pull/52286? Once the content is migrated do the errors persist? I did add a deprecation wihich does not include the style. Maybe I forgiot to do something (I am constantly unsure about deprecations


Thanks for the ping! I didn't have time to debug any of the deprecations, so I couldn't tell where it was coming from. I just leapt to a conclusion that the latest `style` additions were related. 

I'll try to test again. Deprecations turn my brain to mashed potato.

**Comment by ramonjd** [comment] 2023-07-21 03:14
@draganescu 

So I think https://github.com/WordPress/gutenberg/pull/52286 did introduce the validation error despite the deprecation.

To test, add a v6 image block to a post via the code editor and save:

```html
<!-- wp:image {"align":"left","width":164,"height":164,"sizeSlug":"large","style":{"border":{"radius":"100%"}},"className":"is-style-rounded"} -->
<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%" width="164" height="164"/></figure>
<!-- /wp:image -->
```

You'll see the deprecation warning.

```
Block validation: Block validation failed for `core/image` ({name: 'core/image', icon: {…}, keywords: Array(3), attributes: {…}, providesContext: {…}, …}).

Content generated by `save` function:

<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%;width:164px;height:164px" width="164" height="164"/></figure>

Content retrieved from post body:

<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%" width="164" height="164"/></figure>
```

Then remove the changes from #52286

```diff
diff --git a/packages/block-library/src/image/save.js b/packages/block-library/src/image/save.js
index 6fa8c6b234..95e8803dd6 100644
--- a/packages/block-library/src/image/save.js
+++ b/packages/block-library/src/image/save.js
@@ -58,8 +58,6 @@ export default function save( { attributes } ) {
 				...borderProps.style,
 				aspectRatio,
 				objectFit: scale,
-				width,
-				height,
 			} }
 			width={ width }
 			height={ height }
```

The warning is gone.

I suspect we need to migrate the markup changes, but it's tricky because the save function doesn't return a valid block, so I couldn't test things out with `migrate/isEligible`. Plus, I'm not sure here, but manipulating `attributes` or `innerBlocks` might not work because:

1. The attributes haven't changed, only the application of them to the `<img />` markup
2. There are no innerBlocks/innerBlockProps

I think we'd also need to add attributes and supports to the v6 deprecation?

I've done a few deprecations in the past but I wouldn't class myself as an expert here. I might ask around.

**Comment by ndiego** [comment] 2023-07-24 20:14
@ramonjd can this be considered complete when https://github.com/WordPress/gutenberg/pull/52822 and https://github.com/WordPress/gutenberg/pull/52853 are backported?

**Comment by ramonjd** [comment] 2023-07-24 23:28
> can this be considered complete when https://github.com/WordPress/gutenberg/pull/52822 and https://github.com/WordPress/gutenberg/pull/52853 are backported?

Thanks for the ping. Yes, that sounds about right. I should have added the backport to RC label to #52822 sooner, but I'll make sure it features in the next round.

**Comment by tellthemachines** [comment] 2023-07-26 01:20
Closing this one because the Image block deprecation fixes were added to core in 6.3 RC2. Thanks everyone!

**Closed as completed by tellthemachines** 2023-07-26 01:20 UTC
Labels: [Type] Bug, [Feature] Site Editor

**Comment by wpsoul** [comment] 2023-07-30 18:41
I return back to my initial bug report. Tried actual 6.3 Nightly and bug is returned back

One more time. If I have FrontPage template in block theme, Site editor must show Front Template on initial loading. Currently, it shows page from Settings - Reading - Homepage which has no sense because this page is not used on frontend side.

**Comment by ramonjd** [comment] 2023-07-31 00:36
>  If I have FrontPage template in block theme, Site editor must show Front Template on initial loading. Currently, it shows page from Settings - Reading - Homepage which has no sense because this page is not used on frontend side.

Could you give details about the front-page template you're using?

I've tested with the most basic set up, by creating a new `front-page.html` with the following content:

```html
<!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">Front page</h1>
<!-- /wp:heading -->
```

And it always overrides the **Settings > Reading** settings in the editor and frontend. So I suspect it might be specific to the front-page template?

**Comment by wpsoul** [comment] 2023-07-31 02:11
> And it always overrides the **Settings > Reading** settings in the editor and frontend. So I suspect it might be specific to the front-page template?

Ok, so, the situation is even worse. If front-page.html uses just static content, it works. But if it uses patterns or template parts, it doesn't work

`<!-- wp:pattern {"slug":"greenshift/footer-default"} /-->`

or

`<!-- wp:template-part {"slug":"header","tagName":"header","className":"site-header"} /-->`

but if I copy content from header template part and insert it directly in front-page.html, then it works

so, wp:pattern and wp:template-part (any of this) will break site editor initial loading. In the same time, if I select Front template in editor, then it works correctly

**Comment by ramonjd** [comment] 2023-07-31 05:30
I wonder if it's related to https://github.com/WordPress/gutenberg/issues/52983

**Comment by wpsoul** [comment] 2023-07-31 09:41
> I wonder if it's related to #52983

No. In my case, template is working if I open it in editor. Problem is only in initial loading which doesn’t show Frontpage if template has pattern

**Comment by wpsoul** [comment] 2023-08-01 18:15
The latest build made everything even worse. Now, it shows Front-page template on initial loading, but you can't edit anything in the content area

**Comment by ramonjd** [comment] 2023-08-02 01:54
Here's what I'm seeing:


https://github.com/WordPress/gutenberg/assets/6458278/82603986-e068-42d9-8df0-b0f48745868d

Is this happening on other themes for you as well?

**Comment by ramonjd** [comment] 2023-08-02 22:13
Oh I think the fix was included in the latest round of cherry picking for 6.3:

- https://github.com/WordPress/gutenberg/pull/53169#issuecomment-1659569158
