### ISSUE TITLE
Blocks with content that exceeds the viewport height causes scroll jump to bottom of block

### ISSUE THREAD

**Issue by covertnine** [WordPress/gutenberg#21158] opened 2020-03-25 23:27 UTC
**Describe the bug**
To replicate the issue, use a block that exceeds the viewport height. Our grid block frequently exceeds the height of the viewport because it contains all site content.

Then, depending on where your scroll point is, if you click inside of a div to select it, the entire scroll bar bounces you down to the bottom of the screen. If you have innerblocks, (with columns for instance) then you will be bounced down further on the page with each selection of the inner block elements, just to select the content item you want to change.

I've recorded a screen share of this, but you can replicate it on your own just as easily in the latest release candidate with a paragraph block. 

https://recordit.co/YnwdZn514v

**To reproduce**
1. Go to the Gutenberg editor and enter a new post or page
2. Input a long paragraph or long column of text that exceeds the viewport height.
3. Click on anywhere in the paragraph block to select it and activate its controls--it will scroll you all the way down to the bottom most edge of the block--very problematic if you use innerblocks and have long content like articles.

**Expected behavior**
When clicking on a div to select it, the controls should show up wherever you've clicked in the active block, without scrolling to the bottom of the screen. Jumping down 9000 pixels twice just so I can select a grid box, an inner container block, and then subsequently a paragraph inside of a column is a terrible user experience.

**Screenshots**
https://recordit.co/YnwdZn514v

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - Browser Chrome
 - Version 80.0 64bit

**Additional context**
- Whatever is included in WordPress Release Candidate 5.4 RC3
- Blocks plugin we're using grids from is on wordpress.org "c9 blocks" with our own minimalist starter theme so its a lot of our own code.

**Comment by talldan** [comment] 2020-03-26 01:03
Thanks for reporting @covertnine, this issue is a duplicate of #20111, so I'll close this in favor of that one.

**Closed by talldan** 2020-03-26 01:03 UTC
Labels: [Status] Duplicate
