### ISSUE TITLE
Undo action doesn't update block selection

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#12002] opened 2018-11-16 20:21 UTC
_Note: this is easier to spot if you don't use "Unified Toolbar" mode, as the block toolbar is positioned on top of the selected block, but the same behavior applies._

Related ~https://github.com/WordPress/gutenberg/pull/11996 (reverted)~ https://github.com/WordPress/gutenberg/pull/12052

**For duplication:**

* Open a post 
* Select a block and duplicate it using the block settings
* Observe how the focus is changed to the new block
* Click the undo button
* Observe how the focus is lost

The expected result is that the focus was returned to the previous block.

![peek 2018-11-16 21-15-duplicate](https://user-images.githubusercontent.com/583546/48645307-99af8680-e9e5-11e8-8707-7318260b0683.gif)

**For deletion:**

* Open a post 
* Select a block and duplicate it using the block settings
* Observe how the focus is changed to the previous block
* Click the undo button
* Observe how the focus is maintained by the previous block

![peek 2018-11-16 21-15-duplicate](https://user-images.githubusercontent.com/583546/48645316-a03dfe00-e9e5-11e8-95f0-aae72f6ae57e.gif)

**Comment by nosolosw** [comment] 2018-11-16 20:36
More context. It looks like the `select( 'core/editor' ).getSelectedBlockClientId()` isn't updated after the undo operation. In the first case (Duplication + Undo) what ends happening is that the selected block no longer exists.

**Comment by iseulde** [comment] 2018-11-17 00:19
Just noting that this has been an issue for a while. We don't save any selection state to in history, neither block selection, nor rich text selection. In fact, rich text selection state is local in the RichText component. This will need some rework... I thought there was an older issue about this.

**Comment by iseulde** [comment] 2018-11-17 00:20
In my opinion, this seems like something that should be looked at soon. At least make an explicit decision whether this should be part of 5.0 or not.

**Comment by mcsf** [comment] 2018-11-21 17:41
I see a PR for this that then got closed, and I see the issue is in the 5.0 milestone. What's the status of this? From here it looks this belongs in post-5.0.

**Comment by nosolosw** [comment] 2018-11-21 17:42
This is what I've considered so far:

1. Clear selection on `UNDO` / `REDO` actions. Discarded as this would cause problems when the user is editing a block.
2. Clear selection on `UNDO` / `REDO` actions _if the block doesn't exist_. This seemed promising. The way we would do this is by catching the `UNDO`/`REDO` actions in the `blockSelection` reducer and do the proper checks. The problem is that we need other state subtrees to check if a block exists in the current post (like the `editor.present` subtree). Normally, a reducer gets this kind of data from the dispatched action, but in this case `UNDO` / `REDO` don't attach any.
3. Could we use effects to dispatch the clear selection action after `UNDO` / `REDO`? No. The component would be updated first, causing this error.
4. Making the `blockSelection` history aware by wrapping it with `withHistory`. The issue with this approach is that selection could contain the same block several times and `UNDO` to get past selections wouldn't ensure the block selected is a valid block, it could be actually the same block that has been deleted. We'd still need the ability to check whether the block still exists in the post (same problem than option 2).

I'm sharing this in the hope I've missed some obvious approach that we can implement easily. cc @WordPress/gutenberg-core for feedback.

**Comment by nosolosw** [comment] 2018-11-21 18:00
@mcsf I was just writing above comment when closing #12133 At the moment I think we should merge https://github.com/WordPress/gutenberg/pull/12052 for 5.0 and revisit this post-5.0.

**Comment by nosolosw** [comment] 2018-11-22 10:47
I actually found a way that fixes the external API (the `getSelectedBlockClientId` selector) https://github.com/WordPress/gutenberg/pull/12214

**Comment by aduth** [comment] 2018-11-26 18:40
Is this closed now by #12214 ?

Tip: You can auto-close issues by pull requests [using specific keywords](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by aduth** [comment] 2018-11-26 20:36
Related: #12327 (accounting for selection in undo history)

**Comment by nosolosw** [comment] 2018-11-26 21:57
> Is this closed now by #12214 ?

Not from my point of view, that's why I haven't marked it as closed. 12214 is only a workaround while this issue is not fixed.

**Comment by nosolosw** [comment] 2018-11-27 10:34
Oh, I see. I assumed we were using this to track the bug, but I've now seen 12327 and it looks more implementation focused than this one. Whatever you feel is useful for not losing sight of the problem would work for me.

**Comment by aduth** [comment] 2019-05-21 19:07
Let's consolidate to #12327. I've back-referenced to this issue and reclassified it as a bug to ensure appropriate urgency.

**Closed by aduth** 2019-05-21 19:07 UTC
Labels: History, [Type] Bug
