### ISSUE TITLE
Query Block: Custom post excerpt "Read More" link shows twice

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#33269] opened 2021-07-07 22:13 UTC
## Description
When I enable the "Post Excerpt Settings: Show link on new line" toggle, I now see the read more text appear twice on the front-end — both inline with the excerpt, and as a new line below.

## Step-by-step reproduction instructions
1. Make some new posts, making sure to add excerpts.
2. On a new page, create a query block. Select the default layout.
3. In the sidebar, toggle "Show link on new line." 
4. Under "Add read more text link" under your post excerpt, add some custom text.
4. Publish your page, and view it.
5. See that your custom text appears twice.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2846578/124835171-e8234200-df4e-11eb-8431-159e17450157.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by annezazu** [comment] 2021-07-08 00:20
Noting that this happens with 5.8 RC2 and GB 11.0 cc @youknowriad

**Comment by ntsekouras** [comment] 2021-07-12 11:32
Thanks for reporting this. I'm closing as duplicate of: https://github.com/WordPress/gutenberg/issues/32473

**Closed as completed by ntsekouras** 2021-07-12 11:32 UTC
Labels: [Type] Bug, [Feature] Themes, [Block] Post Excerpt
