### ISSUE TITLE
Cover media?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2970] opened 2017-10-10 20:29 UTC
Cover image. Is it possible to instead of image having a video from the media library or from youtube?

At the same time. What about clicking the image brings up the media browser? To quickly change the image.

**Comment by youknowriad** [comment] 2017-10-11 08:39
Part of this issue is a duplicate of #2007

**Comment by paaljoachim** [comment] 2017-10-11 08:42
Thanks Riad!

**Comment by karmatosed** [comment] 2017-10-24 17:12
We have a cover video block already being offered. I do not think in this case adding to the cover image block makes sense.

**Closed by karmatosed** 2017-10-24 17:12 UTC
Labels: Blocks, Media
