### ISSUE TITLE
In site title block, background color adding padding in Full Site Editing Editor.

### ISSUE THREAD

**Issue by Smit2808** [WordPress/gutenberg#41535] opened 2022-06-03 10:20 UTC
### Description

In FSE(Full Site Editing) editor side, when we give background color to the site title block. Then it is adding padding: 1.25em 2.375em. I have checked in inspector tools and found out that this CSS is affecting.
```
h1.has-background, h2.has-background, h3.has-background, h4.has-background, h5.has-background, h6.has-background {
    padding: 1.25em 2.375em; 
}
```
And also found out that this CSS is only affecting in editor side only. In front it is working fine.

### Step-by-step reproduction instructions

1. Open FSE.
2. Select the site title block in the nav menu.
3. Add the background color and you can see some padding will be added with background color

### Screenshots, screen recording, code snippet

<img width="1440" alt="Screenshot 2022-06-03 at 3 50 27 PM" src="https://user-images.githubusercontent.com/64188895/171836222-e54114d5-8cf4-4557-93ad-b46518846f4b.png">

### Environment info

wordpress version 6.0
Latest GB version
Browser chrome
Theme Twenty Twenty Two
MAC OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-06-09 07:06
Hi!
I am closing this issue as a duplicate of [#30725 ](https://github.com/WordPress/gutenberg/issues/30725) and  [#36586](https://github.com/WordPress/gutenberg/issues/36586).
I encourage you to continue the discussions in your pull request, or in the open issue.

**Closed as not planned by carolinan** 2022-06-09 07:06 UTC
Labels: [Status] Duplicate
