### ISSUE TITLE
Problem with "Saving Draft" and "Preview"

### ISSUE THREAD

**Issue by rafaelmarchesin** [WordPress/gutenberg#8557] opened 2018-08-05 20:40 UTC
**Describe the bug:**
I'm having two problems using the new editor:
1. Each letter that I type in the editor occurs a Saving Draft and this has left very slow my edition, especially when I need to delete some content using the backspace. Also the message "Updating failed" appears at the top of the editor.
2. Another problem that has occurred is that Preview does not work. I get the message "Please wait ... Generating preview" instead of the preview, but the preview is not loaded.

**Expected behavior**
1. Faster post editing.
2. Correct post preview.

**Comment by youknowriad** [comment] 2018-08-06 09:54
Do you have Cloudflare enabled on your website?

**Comment by rafaelmarchesin** [comment] 2018-08-06 11:37
Yes.

**Comment by youknowriad** [comment] 2018-08-06 11:41
I guess this is probably a duplicate of #8441 There's a workaround (to apply in CloudFlare settings in that issue) I'm going to close this, let's consolidate there. Thanks.

**Closed by youknowriad** 2018-08-06 11:41 UTC
