### ISSUE TITLE
Extensive articles with over 1700 words and various blocks make Gutenberg very slow.

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#10418] opened 2018-10-09 00:37 UTC
**Describe the bug**
If the spotlight mode is activated (or any other mode) and you jump between paragraphs, it always takes a while. This is only a fraction of a second, but depending on your internet connection or whatever, it can interfere with the writing flow.

I don't have the fastest Internet connection, but the problem only occurs in different modes when the article is very extensive. There is always a slight delay, which interrupts the write flow. I think this is especially interesting for countries that don't have such a fast internet connection. But I'm not sure if this is the reason. In any case there is a  little delay.

I would like to add one more thing: if I start a new fresh article, then it is going quite well: http://recordit.co/fn7wBBE5sW

But if the article is very extensive, then it is very slow and it falters without end (1700+ words and many different block variants). The more I write, the slower Gutenberg gets.

![screenshot_1](https://user-images.githubusercontent.com/9355398/47268514-5aab2400-d552-11e8-8f14-e9cd204c8a97.png)

**To Reproduce**
1. Go to 'Post'
2. Click on 'Spotlight Mode'
3. Write paragrafs with over 1700 Words.
4. See error: http://recordit.co/LzOYawwJYI

**Expected behavior**
A faster change within the blocks and a smoother writing flow. This only happens when the article is very extensive.

**Screenshots**
http://recordit.co/LzOYawwJYI

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome 69

**Additional context**
- Gutenberg 4.0

**Comment by blazevivan** [comment] 2018-10-20 10:53
Tested on Win10, Chrome Version 69.0

Couldn't reproduce the issue. This is how it worked in spotlight mode: 

http://cld.wthms.co/wIkk0N

My internet speed is about 15Mb/s

**Comment by SchneiderSam** [comment] 2018-10-21 14:49
@designsimply if you want I can send you access data to the website. Which automatic employee can I contact?

**Comment by SchneiderSam** [comment] 2018-10-21 14:55
I would like to add one more thing: if I start a new fresh article, then it is going quite well: http://recordit.co/fn7wBBE5sW

But if the article is very extensive, then it is very slow and it falters without end (1700+ words and many different block variants).

![screenshot_1](https://user-images.githubusercontent.com/9355398/47268489-07d16c80-d552-11e8-8a40-84ac22bc1a54.png)

**Comment by SchneiderSam** [comment] 2018-10-31 16:37
I want to give you an update with version 4.2 RC 1: it reacts faster, but it still hacks. Please note that I'm talking about an article that has a lot of words:

![wgjre1tnhs](https://user-images.githubusercontent.com/9355398/47803786-89d04b00-dd33-11e8-829e-b8b4591a6d80.gif)

**Comment by aaronjorbin** [comment] 2018-11-05 21:03
This feels like a 5.0 blocker issue that should be looked into.

**Comment by SchneiderSam** [comment] 2018-11-06 16:22
I want to give a small update: the editor is getting faster and faster. I don't know what you're doing, but please keep it up. It's not like the old editor yet. But we are already on the right track.

I took a new test with the newest Version (5.0-beta3-43867)
Please check this: http://recordit.co/5dzd81Pv9r (Please note how the words partially stop and are not displayed. Only after a few seconds.)
And here with an other editor: http://recordit.co/cq6ol15WN2 (which is much faster)

**Comment by aduth** [comment] 2018-11-06 16:44
Previously: #8822
Related (possibly duplicates): #10427 (technical direction)

**Comment by youknowriad** [comment] 2018-11-06 16:44
The most important issues causing performance loss are fixed for me by #10723 and the last remaining one is #10427 which is currently being worked on in #7409 and #11267.

Since I think the remaining point here is tracked in #10427 I'm going to close this as duplicate. Please if you find other things impacting performance, open follow up issues.

**Closed by youknowriad** 2018-11-06 16:44 UTC
Labels: Needs Testing

**Comment by designsimply** [comment] 2018-11-06 17:02
> @designsimply if you want I can send you access data to the website. Which automatic employee can I contact?

Thanks for the offer! But requiring a login to other closed systems for the purpose of testing is not a good solution in general. What would be nice, however, would be an export of the content, or content that is very similar, so I may use it for testing. I noticed the content structure screenshot in your original report says the post you are testing has 235 headings+paragraphs and 308 blocks, so I am interested to know how many other kinds of blocks there are and I am wondering how many (if any) of them are classic blocks. I also noticed the post is in German. If you are able to provide the output of More > Copy All Content either in a pastebin or a gist or somewhere I can access it, I will try using it for testing to see what I can find when testing the PRs referenced in the other replies here—which I think would be good to do.

**Comment by chrisvanpatten** [comment] 2018-11-06 22:38
@SchneiderSam I tried out your content on my personal site which is running 4.2 and didn't experience any major issues. I used Safari 12 on macOS Mojave, with an Intel Core i7 processor.

It only got slightly slow once I had clicked into a bunch of the blocks (which loads up the RichText component) and even then the lag was still pretty minimal, maybe 0.3–0.5 seconds or so.

Did you have any notable errors in your JS console?

**Comment by SchneiderSam** [comment] 2018-11-07 00:19
I don't know much about that, but I'm guessing you mean this:

![screenshot_1](https://user-images.githubusercontent.com/9355398/48102359-f911d780-e22a-11e8-99e2-7020a91a5dab.png)

Notice anything? Well, I'd love to keep testing this, but it's no fun...

**Comment by designsimply** [comment] 2018-11-08 16:46
I tested using the content sample provided (thank you!) and found a couple main things: 1/ typing was indeed laggy (I noticed there were 227 blocks which are mostly headings and paragraphs with some lists and about 5 columns blocks—noting this for reference) and 2/ it takes about 6 or 7 seconds to re-open the post after closing it. (2min) I tested with my site language set to German as well as English.

Because this issue is a duplicate, I will keep an eye on the related PRs (#10723, #10844, #10723, #11287, #11267) and re-test using this content when those are all resolved so we can close the loop here after the performance updates that are in progress become finished. Thank you again for testing and reporting this!

Notes:

> Ahhh. Here's something: http://recordit.co/7RhbEGlCd0
> Or should I set something special on the Chrome Console?

This is good info and I am copying a screenshot from that video for reference because all of those warnings about handlers seem relevant and I don't see those in my own testing:

![screen shot 2018-11-08 at 9 36 20 am](https://user-images.githubusercontent.com/1119271/48213244-a3c4eb80-e33a-11e8-8120-23d4b0ec80a3.png)

Also copying your internet speed screenshot for reference as it's very relevant and making a note for myself do a lot of testing with throttling turned on in browser tools as I go:

![download 4](https://user-images.githubusercontent.com/1119271/48213331-c8b95e80-e33a-11e8-93df-bc182de02add.png)

In comparison, my internet connection is very fast:

![screen shot 2018-11-08 at 9 40 38 am](https://user-images.githubusercontent.com/1119271/48213350-d53db700-e33a-11e8-85dc-c29bc730f0c1.png)

**Comment by SchneiderSam** [comment] 2018-11-08 21:14
@designsimply Thanks for taking the mistake seriously. That gives you a certainty with all the anti-Gutenberg opinions.

**Comment by SchneiderSam** [comment] 2018-11-10 10:10
@designsimply I just want to make a short update to the last Gberg Update 4.3-RC: it's still slow. And this although the related PRs you mentioned should be fixed to 4.2 / 4.3. I think it still hangs somewhere...

**Comment by websupporter** [comment] 2018-11-27 14:40
I tested it today with the content provided by @SchneiderSam and the problem persist for me. I tested it with Firefox in the current RC as well as with the nightly build plugin and wp 4.9.8. I also tested it with Chrome. There it lags a bit as well, but not as bad as with Firefox.

Here is a screencast with my xp: https://www.youtube.com/watch?v=yIV6REWM5tE
