### ISSUE TITLE
Uncaught ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by tatasha2004** [WordPress/gutenberg#44969] opened 2022-10-14 07:53 UTC
### Description

Yoast SEO Free -> Readability section is broken in Gutenberg (trunk)

### Step-by-step reproduction instructions

1. Yoast Free 19.8 + Gutenberg trunk
2. Create a new post
3. Check the readability section

Actual result: Readability metabox is not shown
Console Error:
```
inert-polyfill.min.js?ver=6.0.2:1 Uncaught ReferenceError: Element is not defined
 at inert-polyfill.min.js?ver=6.0.2:1:2399
 at inert-polyfill.min.js?ver=6.0.2:1:107
 at inert-polyfill.min.js?ver=6.0.2:1:129
 at analysis-worker.js?ver=2ae8d0e3f1ba2a5869ab200f3dbae615:1:1092
 at self.onmessage (analysis-worker.js?ver=2ae8d0e3f1ba2a5869ab200f3dbae615:1:1156)
```

### Screenshots, screen recording, code snippet

<img width="1728" alt="Screenshot 2022-10-13 at 15 19 43 (1)" src="https://user-images.githubusercontent.com/30239355/195792518-aaded1a0-d5b4-4fa3-9551-558cda6a7c8f.png">

### Environment info

- WP 6.0.2
- Gutenberg trunk
- Theme TwentyTwentyTwo
- Chrome (MacOS)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment] 2022-10-14 19:37
I can reproduce this issue and confirm the error message! 
It seems to be originating from this file, though, which is not part of the Gutenberg plugin. 
`plugins/wordpress-seo/js/dist/analysis-worker.js?ver=e6a656b3d7af0754331dabe9f8069664`

@tatasha2004 There are two options, where you can connect with the Yoast team

- [Yoast SEO's support forum](https://wordpress.org/support/plugin/wordpress-seo/)
- [Yoast GitHub repo for the SEO plugin](https://github.com/Yoast/wordpress-seo/issues)

I close this for now as this needs to be fixed on the plugin side.

**Closed as completed by bph** 2022-10-14 19:37 UTC

**Comment by tatasha2004** [comment] 2022-10-17 07:29
@bph do you know when the current trunk will be released? I haven't found the release calendar.

Thank you in advance.

**Comment by bph** [comment] 2022-10-18 17:52
Trunk of Gutenberg? @tatasha2004 
The Gutenberg plugin release is every two weeks: 
This week will be 14.4 RC on Wednesday with a stable release next week (Oct 26th).  

An almost daily release of the plugin with the latest merges is available as [Gutenberg Nightly](https://gutenbergtimes.com/need-a-zip-from-master/#nightly) from the Gutenberg Times.

**Comment by tatasha2004** [comment] 2022-10-19 07:36
Thank you @bph.
