### ISSUE TITLE
Add an "approach to data" document

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1324] opened 2017-06-21 01:50 UTC
This should be similar to [the corresponding document for Calypso](https://github.com/Automattic/wp-calypso/blob/6fd6c1b/docs/our-approach-to-data.md#third-era-redux-global-state-tree-december-2015---present) but not as complicated and not yet as fully-formed.

It should explain a bit about what [Redux](http://redux.js.org/) is and how it works within React applications, as well as how network requests fit into this structure (triggered by Redux actions using [`refx`](https://github.com/aduth/refx) and using the [WP REST API Backbone client library](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/)).

**Comment by youknowriad** [comment] 2017-06-21 09:31
related #902

**Comment by aduth** [comment] 2017-06-21 13:24
>related #902 

Maybe even duplicate of?

**Comment by nylen** [comment] 2017-06-21 22:28
Related, but I think doing this and documenting it are separate tasks. #902 also relates more to network actions, but our documentation should cover the structure of the application at a more basic level.

**Comment by mtias** [comment] 2017-11-20 10:59
Going to close this as we'd cover things by documenting the tools (withApiData, etc).

**Closed by mtias** 2017-11-20 10:59 UTC
Labels: Documentation, [Type] Task
