### ISSUE TITLE
Pasting a table that contains `thead` tag leads to column spanning issues

### ISSUE THREAD

**Issue by bperson** [WordPress/gutenberg#7688] opened 2018-07-03 13:27 UTC
**Describe the bug**
Pasting a table that contains `thead` leads to column spanning issues: the first column defined in the `thead` will be spanned across all the columns defined in the `tbody`, any extra column in the `thead` are then appended as if they were "extra" columns. ( see the screenshots below, describing column spanning issues is a pain 😅 )

**To Reproduce**
1. Copy and Paste a table containing a `thead` tag ( for instance from a [GitHub README](https://github.com/apache/parquet-mr/tree/master/parquet-tools) )
2. The `thead` is preserved in the HTML with its children, but it creates layout / column spanning issues

**Expected behavior**
Either filter out the `thead` when copy-pasting
OR
Proper support of `thead` in tables

**Screenshots**
![screen shot 2018-07-03 at 13 16 45](https://user-images.githubusercontent.com/1145270/42222077-a369abac-7ec3-11e8-9cfd-fb9667c42e07.png)
![screen shot 2018-07-03 at 13 17 00](https://user-images.githubusercontent.com/1145270/42222078-a38711b0-7ec3-11e8-9038-cc1496a00354.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser Chrome 
 - Version 67.0.3396.99

**Additional context**
Tried on p2s and on [frontenberg](https://frontenberg.tomjn.com/) so, I'm guessing the latest?
It's potentially a duplicate of #6902

**Comment by designsimply** [comment] 2018-07-05 00:39
Tested and confirmed with WordPress 4.9.6 and Gutenberg 3.1.1 using Safari 11.1.1 on macOS 10.13.5 with the following sample html:

```
<table>
<thead>
<tr>
<th>Acronym</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr>
<td>RC</td>
<td>Row Count</td>
</tr>
<tr>
<td>TS</td>
<td>Total Byte Size</td>
</tr></tbody></table>
```

![screen shot 2018-07-04 at wed jul 4 6 29 26 pm](https://user-images.githubusercontent.com/1119271/42297015-133f25ce-7fb9-11e8-878c-de2ba0f66361.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13878&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Safari 11.1.1 on macOS 10.13.5.</sup>

![screen shot 2018-07-04 at wed jul 4 6 31 37 pm](https://user-images.githubusercontent.com/1119271/42297052-7f512c58-7fb9-11e8-8c42-23cb6cb72772.png)
<sup>Seen at http://alittletestblog.com/2018/07/05/thead-tag-test/ running WordPress 4.9.6 and Gutenberg 3.1.1 using Safari 11.1.1 on macOS 10.13.5.</sup>

I noticed that `<table>` becomes `<table class="wp-block-table">` and removing `class="wp-block-table"` from `<table class="wp-block-table">` on the front end makes the column spanning issue go away.

**Comment by marcusig** [comment] 2018-07-25 08:56
Just noticed the same issue.

The issue is here:

```
.wp-block-table tbody {
    width: 100%;
    display: table;
    min-width: 240px;
}
```
tbody `display` property shouldn't be set to `table`. 

I think the best would be to leave the display property empty, or set it to the default `table-row-group` if really necessary.

**Comment by ianbelanger79** [comment] 2018-08-07 19:14
PR #7899 fixes this issue so I am closing this one

**Closed by ianbelanger79** 2018-08-07 19:14 UTC
Labels: [Component] Raw Handling, [Type] Bug
