### ISSUE TITLE
Resizing the Add block area

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13210] opened 2019-01-05 17:03 UTC
**Is your feature request related to a problem? Please describe.**
There is a limited view of the various blocks after having clicked the Add Block inserter.

![screen shot 2019-01-05 at 17 51 39](https://user-images.githubusercontent.com/5323259/50726874-4a4b2400-1113-11e9-8b94-c58480fbbc46.png)

**Describe the solution you'd like**
It would be good to add a resize handle to see more of the block area.
For instance something using double arrows.

![resize-block-area](https://user-images.githubusercontent.com/5323259/50726881-68b11f80-1113-11e9-8c4c-b033236f3146.jpg)

**Comment by paaljoachim** [comment] 2019-01-18 09:48
Btw one could also add the ability to resize horizontally in addition to vertically. So the user can resize to what works for their work flow.

**Comment by karmatosed** [comment] 2019-04-11 20:30
We discussed this in the design triage meeting this week. In this, I brought up some points wanted to share in this ticket.

- Scrolling really isn't a bad experience compared to unexpected resizing.
- A variable layout can be super disruptive.
- If the issue is with library interactions then looking at that over just resizing would be best.
- Resizing is always a sign of a deeper issue if a user needs.
- I am not convinced it's a wide user need.
There is a balance of 'app' and 'editing' as far as experience goes.
One person's screen also isn't another, so perhaps there's a deeper issue here. I am just not at all convinced a single level resize to avoid a scroll is that.
I personally think it adds a complication to the UI, potential a11y hurdles and a whole host of maybe considerations. I would want to know for sure it's something a lot need.
Resizing a popover is always a bigger consideration than 'just doing'. For example, is it linked to user preference/ cookie/ what state? How do you even find out and revert?

**Comment by paaljoachim** [comment] 2019-04-12 09:49
Thanks for sharing Tammie!

**Comment by karmatosed** [comment] 2019-07-10 17:16
For now, let's as a result of the feedback close this issue. We can always reopen if we need.

**Closed by karmatosed** 2019-07-10 17:16 UTC
Labels: Needs Design Feedback, [Component] Inserter, [Type] Enhancement
