### ISSUE TITLE
Links to the editor don't work for template and template parts revisions in the revisions screen

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#48065] opened 2023-02-14 10:23 UTC
In #45215 the template and template part editors gained a button that links to the revisions screen for the edited template and template part.

The problem is that in the revisions screen there are two links that should link back to the editor which don't work (one with the template name and another one with the text "go to editor").

<img width="1342" alt="Screenshot 2023-02-14 at 12 17 19" src="https://user-images.githubusercontent.com/107534/218706762-393d5642-1ca0-4792-8502-656492a02cdb.png">

In the post editor (block editor) going to the revisions screen will set these links to a shape of:

`/wp-admin/post.php?post=3594&action=edit`

In the template editor going to the revisions screen will set these links to a shape of:

`/wp-admin/revision.php?revision=4068&gutenberg=true`, which is the URI of the revisions screen itself.

This is a blocker for https://core.trac.wordpress.org/ticket/57704
There is a corresponding  core ticket at https://core.trac.wordpress.org/ticket/57709

**Comment by ghost** [comment] 2023-02-14 11:48
@draganescu Sorry, newbie question maybe, but where do I even find the revision screen for template parts? I tried to recreate this issue on my end with both the Gutenberg plugin activated and deactivated, but I can't seem to find the revision screen for templates or template parts.

**Comment by draganescu** [comment] 2023-02-14 14:06
@thomasdevisser

- running trunk
- open a template and do an edit, save
- refresh the page do another edit, save
- refresh the page and open the settings sidebar
- notice the revisions button (should say 2 revisions)
- click it
- you'll end up in the revision screen


https://user-images.githubusercontent.com/107534/218761612-6db1d5fa-301f-4b1b-9713-3caee71d9f13.mp4

**Comment by ghost** [comment] 2023-02-14 14:10
Thank you @draganescu. It looks like the issue is that the entire href is missing on both these anchor tags. That's why you're seeing the URI of the screen you're already on.

<img width="179" alt="Screenshot 2023-02-14 at 3 10 11 PM" src="https://user-images.githubusercontent.com/118618474/218762564-fefa4b30-c2db-414e-901d-f684bbde4c5b.png">

**Comment by ghost** [comment] 2023-02-14 14:21
On further inspection, in core, `get_edit_post_link()` in `wp-admin/revision.php` returns an empty string. I will try to find a fix for this.

**Comment by ghost** [comment] 2023-02-14 14:33
In the `WP_Post_Type` object of templates, it seems the `_edit_link` property is set to an empty string. The reason for this is found in `wp-includes/class-wp-post-type.php`:

```php
// If there's no specified edit link and no UI, remove the edit link.
if ( ! $args['show_ui'] && ! $has_edit_link ) {
	$args['_edit_link'] = '';
}
```

The actual edit URI should be `/wp-admin/site-editor.php?postId=twentytwentythree%2F%2Fcomments&canvas=edit&path=%2Ftemplate-parts%2Fsingle&postType=wp_template_part`.

So to fix this issue we could go in two directions:

- We could add an extra check in `wp-includes/link-template.php`, to see if the post type is `wp_template_part`, and if so, set the correct `_edit_link`. I couldn't find a way to retrieve the values for the `postId` and `path` URL params, but this could solve the issue. I don't know if it's the best solution, though.
`/wp-includes/link-template.php:get_edit_post_link`
```php
if ( $post_type_object->_edit_link ) {
    $link = admin_url( sprintf( $post_type_object->_edit_link . $action, $post->ID ) );
} elseif ( 'wp_template_part' === $post_type_object->name ) {
    $link = '/wp-admin/site-editor.php?postType=wp_template_part&canvas=edit&';
    // postId = twentytwentythree%2F%2Fcomments
    // path = %2Ftemplate-parts%2Fsingle
} else {
    $link = '';
}
```
- We could add the `_edit_link` explicitly during the creation of a new `wp_template_part` post. In this case however, if the link changes, every template post has the link hardcoded as a "custom" edit link so I would suggest the first solution.

This should therefore probably be moved to the [wordpress-develop GitHub](https://github.com/WordPress/wordpress-develop), but I'm not sure as I'm also new here. 🙂

**Comment by draganescu** [comment] 2023-02-15 12:58
@thomasdevisser you are right it would be easier to patch core directly for this and to try a PR in the [wordpress-develop GitHub](https://github.com/WordPress/wordpress-develop).

Also thank you for investigating, yes I as well believe we need to:

- add the `_edit_link` explicitly during the creation of a new `wp_template_part` and `wp_template` CPTs, just like `post` and `page` CPTs have
- update `/wp-includes/link-template.php:get_edit_post_link` to parse the format of `_edit_link` and put in the correct slug, id etc.

**Comment by ramonjd** [comment] 2023-04-13 07:13
I'm looking at [global styles revisions](https://github.com/WordPress/gutenberg/pull/46667#top) and have come across this and the [first revision bug as well](https://github.com/WordPress/gutenberg/issues/49164).

I've been looking at the [suggestion above](https://github.com/WordPress/gutenberg/issues/48065#issuecomment-1431329173) and I've nearly got it working:

- https://github.com/WordPress/wordpress-develop/pull/4326

Just checking if there's been any progress. If not I can carry on 😄 

I also wondered whether it might be a decent fallback to send the edit link in the URL params, given that Gutenberg site-editor.php links could change ?

**Comment by annezazu** [comment] 2023-04-17 18:50
This entirely breaks the experience. Noting this as high priority to fix and adding to the phase 2 board. Can someone indicate whether they will be taking this on to resolve?

**Comment by ramonjd** [comment] 2023-04-18 01:35
Looks like there's an existing fix at https://github.com/WordPress/wordpress-develop/pull/4229

**Comment by dsas** [comment] 2023-05-11 11:21
The existing fix got merged upstream @ramonjd. Given [6.3 won't be released until August](https://make.wordpress.org/core/2023/04/14/wordpress-6-3-planning-proposal-call-for-volunteers/) will GB get patched to fix the broken revisions screen before then?

**Comment by draganescu** [comment] 2023-05-11 12:21
I think it should be yes, but not sure how.

**Comment by annezazu** [comment] 2023-05-11 14:40
@hellofromtonya is this something you can help with?

**Comment by ramonjd** [comment] 2023-05-11 23:32
It should be doable using a combo of `register_post_type_args` and `get_edit_post_link` filters - I can take a crack today if I get time. Will report back if I don't 😄

**Comment by ramonjd** [comment] 2023-05-12 03:03
Backport here:
- https://github.com/WordPress/gutenberg/pull/50563

**Closed as completed** 2023-05-13 01:51 UTC
Labels: [Type] Bug, [Priority] High, [Feature] Template Editing Mode
