### ISSUE TITLE
Buttons Block: Border radius shows the wrong value after refreshing the browser

### ISSUE THREAD

**Issue by bharath** [WordPress/gutenberg#20812] opened 2020-03-11 20:45 UTC
**Describe the bug**
In Buttons block, I drag the Border radius all the way to 50 and see the button rounded. Clicked Update. Then refreshed the browser window. The button is fully rounded but the Border radius shows the wrong value.

**To reproduce**
1. Add button block.
2. Adjust the Border radius all the way to 50.
3. Click Update.
4. Refresh the browser window.
5. Button - Border radius reverts to showing 5. Even though the button visually shows fully rounded as 50.

**Expected behavior**
Border radius setting should show the value set by user even after refreshing the browser window.

**Screenshots**
After setting Border radius and updating the page:
![Screenshot 2020-03-12 at 2 02 16 AM](https://user-images.githubusercontent.com/41569/76461674-5e20a300-6406-11ea-8b4b-e666f1039672.jpg)
After refreshing the browser window:
![Screenshot 2020-03-12 at 2 02 51 AM](https://user-images.githubusercontent.com/41569/76461684-624cc080-6406-11ea-8619-44f67dc12919.jpg)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - 80.0.3987.132

**Additional context**
- Tested with Gutenberg 7.7.0 
- Tested themes:  Twenty Twenty, Twenty Nineteen, Twenty Seventeen and Genesis Sample theme.

**Comment by youknowriad** [comment] 2020-03-12 08:39
I'm not able to reproduce this issue personally. Anything particular about your installation, do you have editor plugins that could affect its behavior?

**Comment by paaljoachim** [comment] 2020-03-12 08:53
I am able to repeat this in Twenty Twenty and in Twenty Nineteen.
Here is a gif from Twenty Nineteen.

![Buttons-Block-Border-Radius-bug](https://user-images.githubusercontent.com/5323259/76504111-5af9d700-6447-11ea-8aa0-2a5fb9d5fa94.gif)

**Comment by youknowriad** [comment] 2020-03-12 09:43
I can reproduce this on my live site but not on Gutenberg master. I guess this was fixed by https://github.com/WordPress/gutenberg/pull/20247

**Closed by youknowriad** 2020-03-12 09:43 UTC
Labels: [Block] Buttons, [Status] Needs More Info

**Comment by paaljoachim** [comment] 2020-03-12 09:44
Does that mean this fix will be included in Gutenberg version 7.8?

**Comment by youknowriad** [comment] 2020-03-12 09:47
yes, or sooner if we decide to do a 7.7.1
