### ISSUE TITLE
Align image left/right - drag handle visibility issues.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11424] opened 2018-11-02 16:34 UTC
**Describe the bug**
Aligning image left the drag handle dissapears

**To Reproduce**
1. Add image to an image block.
2. Align image left. 
3. No drag handle is seen.
4. Align image left or right and drag handles are not seen. Align image center and drag handle are seen.

**Expected behavior**
To see the drag handles on all alignment options left/center/right.

**Screenshots**
![screen shot 2018-11-02 at 17 31 01](https://user-images.githubusercontent.com/5323259/47928060-5fae9280-dec5-11e8-896c-1b88e8920123.png)

![screen shot 2018-11-02 at 17 33 23](https://user-images.githubusercontent.com/5323259/47928083-6d641800-dec5-11e8-809c-21a7655f247e.png)

![screen shot 2018-11-02 at 17 33 50](https://user-images.githubusercontent.com/5323259/47928102-794fda00-dec5-11e8-9a71-0e8bf3784e8a.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser Chrome in Desktop Server
 - Gutenberg version 4.1.1

**Comment by designsimply** [comment] 2018-11-02 22:59
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 that when an image is left-aligned the drag handles appear on the right and bottom and when an image is right-aligned the drag handles appear on the left and bottom and when an image is centered the drag handles appear on the left, right, and bottom. I had assumed this was by design and not a mistake though.

**Comment by paaljoachim** [comment] 2018-11-03 11:16
I looked through this again.
Centering the image the drag handles are easy to discover. As where the mouse needs to be is in the area around the image. 
Aligning an image left or right There is a very limited area for the drag handles to show up on the left. It can easily be missed if one does not move the mouse over to the correct area.

Here is a gif I made to show when the drag handles show up.

![drag-handles](https://user-images.githubusercontent.com/5323259/47951532-2c6e1100-df62-11e8-9e0b-ab2e3e9dc97c.gif)

**Comment by youknowriad** [comment] 2018-11-03 18:15
Movers and drag handle are not visible in floated blocks by design. It's not ideal but there's no better alternative at the moment. I'm inclined to close this issue at the moment.

Not sure if there are plans to revisit this at the moment cc @jasmussen

**Comment by paaljoachim** [comment] 2018-11-04 11:03
At present with the above example alining the image left on top of the paragraph block there is very little room for when the mover and drag handles are seen.

 I would suggest when hovering over a block and the the blue outline is seen that the movers and drag handles also become visible. Showing the outline of a block it to me also feels natural to show what can be directly done with the block.

**Document States** 

 (I will also add a new issue for discussing these things.)

No hovering of block shows how the layout looks. It could also automatically select sidebar document settings or hide the sidebar to fully show the layout as it most natural would be seen on the frontend. 

Clicking the layout outside any block could open the sidebar showing document settings. Clicking the layout outside any block again could hide the sidebar.

Hover a block in the layout shows the blue outline/boundaries of the block and could as well show other things associated with the block that can be manipulated such as movers and drag handles. As well as showing the toolbar belonging to the block.

Clicking into a block shows which actions can be done when interacting with the block.

**Comment by paaljoachim** [comment] 2018-11-04 11:59
Example of showing block outline at current:
<img width="644" alt="screen shot 2018-11-04 at 12 58 28" src="https://user-images.githubusercontent.com/5323259/47963813-56423900-e031-11e8-8d61-70e365cdd459.png">



Suggestion of including mover and drag handles:
<img width="688" alt="screen shot 2018-11-04 at 12 57 25" src="https://user-images.githubusercontent.com/5323259/47963818-6528eb80-e031-11e8-8d29-0f95b6137ba6.png">

**Comment by jasmussen** [comment] 2018-11-05 07:38
> Movers and drag handle are not visible in floated blocks by design. It's not ideal but there's no better alternative at the moment. I'm inclined to close this issue at the moment.

This is correct. As you show yourself in https://github.com/WordPress/gutenberg/issues/11424#issuecomment-435579857, if the movers & drag handle showed up to the left of a left floated block, it would overlap the block beneath it, and I'm concernd that #11468 is too complex of a solution for that problem.

To be clear: **yes, we want movers for left and right aligned content**. But Riad is also correct that they are disabled for now, because it didn't work when we had them there. 

Our current best plan is to show the same layout for a floated block, as we do for blocks on mobile — that is, below the block. But in absence of pull requests making this happen in the next few days, it's likely the movers won't return for floated content until the next WordPress release.

**Comment by paaljoachim** [comment] 2018-11-05 08:53
Ok. I am thinking we will just let another solution show it self over time. Thanks for the comment.

**Comment by designsimply** [comment] 2018-11-05 17:11
Closing for now and noting that #11454 was added to the Ideas project which is a place to add issues for later consideration.

**Closed by designsimply** 2018-11-05 17:11 UTC
Labels: Chrome, [Type] Enhancement
