### ISSUE TITLE
Responsive Cover Image

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#10989] opened 2018-10-24 08:53 UTC
**Describe the bug**
The background image of the cover-image block is always loaded in full width size. Even if the full with size is 4000 px wide and the device is a smartphone.

With WordPress 4.4 the responsive images were introduced to solve this bug with images loaded by the `img` tag. I think there should be a similar solution for the cover image background.

**To Reproduce**
1. Add a cover-image block and choose a large image

**Expected behavior**
There should be a responsive-image behaviour for the cover image background-image

**Desktop:**
 - macOS
 - Browser chome

**Smartphone (please complete the following information):**
 - Device: s7
 - OS: Android
 - Browser chrome

**Comment by antpb** [comment] 2018-10-25 18:20
Duplicate of https://github.com/WordPress/gutenberg/issues/6177 

Closing this to keep the focus there as mentioned in: https://github.com/WordPress/gutenberg/issues/6177#issuecomment-383323785 

:)

**Closed by antpb** 2018-10-25 18:20 UTC
Labels: Blocks, Media, [Type] Bug
