### ISSUE TITLE
template_lock doesn't work inside Columns

### ISSUE THREAD

**Issue by mikedance** [WordPress/gutenberg#10360] opened 2018-10-05 15:36 UTC
**Describe the bug**
When creating a block template for a post type, 'template_lock' => 'all' disables the ability to add, remove, or move blocks. However, if columns exist in the template, blocks within columns can be added, removed, or moved.

**To Reproduce**
1. Create a custom post type with the following arguments:
```
register_post_type( 'thing', array(
	'label' => 'Thing',
	'public' => true,
	'show_in_rest' => true,
	'template' => array(
		array( 'core/columns', array(), array(
			array( 'core/column', array(), array(
				array( 'core/image', array() ),
			) ),
			array( 'core/column', array(), array(
				array( 'core/paragraph', array() ),
			) ),
		) ),
	),
	'template_lock' => 'all'
) );
```
2. Add/delete blocks within either column.

**Expected behavior**
I expect that columns should respect template_lock and not allow adding/removing/moving blocks.

However I can also see the utility being able to have unlocked columns inside locked templates. So I think a better solution, if possible, would be to include the template_lock option as an attribute on columns so that they could be locked or unlocked directly in template args. InnerBlocks can be template-locked, but [columns currently have templateLock={ false } hardcoded](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/column.js).

**Comment by AndreaBarghigiani** [comment] 2018-10-12 11:59
I would like to add to this issue that also when working in JS with the column block I have the same problem. Inside my block I declare a template:

```js 
const TEMPLATE = [
	[
		"core/columns",
		{},
		[
			[
				"core/column",
				{},
				[
					["core/image", { className: "pro-icon" }],
					[
						"core/heading",
						{ placeholder: "Pro Title", className: "pro-title" }
					],
					["core/list", { className: "pro-list" }]
				]
			],
			[
				"core/column",
				{},
				[
					["core/image", { className: "cons-icon" }],
					[
						"core/heading",
						{ placeholder: "Cons Title", className: "cons-title" }
					],
					["core/list", { className: "cons-list" }]
				]
			]
		]
	]
];
```

And then I'll add it to my `edit()` and all is working just fine but the `templateLock` does not get applied:

```js
return (
	<div className={className}>
		<InnerBlocks template={TEMPLATE} templateLock="all" />
	</div>
);
```

I would like to be able to do something like it without dive too deep into React to create new (un-useful) elements.

**Comment by designsimply** [comment] 2018-10-15 22:05
Possibly related: #7693 (the example looks the same, the difference seems to be that 7963 is about inline blocks and 10360 is about inner blocks)

**Comment by youknowriad** [comment] 2019-01-30 10:07
This is a duplicate of #9386

**Closed by youknowriad** 2019-01-30 10:07 UTC
Labels: Needs Technical Feedback, Templates API, [Component] Nested / Inner Blocks
