### ISSUE TITLE
FSE: Previewing in a new tab should reflect template changes even before saving

### ISSUE THREAD

**Issue by edequalsawesome** [WordPress/gutenberg#39172] opened 2022-03-02 20:17 UTC
### Description

On a published post or page, if

* you change the Template in the Page/Post editor right-side panel and click Preview in new tab

or

* you change the Template in the Page/Post editor right-side panel, and then click Edit to end up in the Template Editor, and lastly click Preview in new tab

the change is not reflected.

It only reflects if you preview after you save changes by clicking Update

### Step-by-step reproduction instructions

1. Open a published page from the `Pages > All Pages` area of WP Admin
2. Change the template used for the page from the Templates panel of the sidebar
3. Click `Preview > Preview in New Tab`

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4000628/156442394-59a5f89e-afbf-4926-a3e6-1e08e23efee1.mov

### Environment info

Gutenberg 12.6.1
WordPress 5.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2024-08-20 19:48
Thanks for reporting this. I see this as a duplicate of the following issue: https://github.com/WordPress/gutenberg/issues/28208

I'm going to close this out as a result but, if I'm missing something, please let me know!

**Closed as completed by annezazu** 2024-08-20 19:48 UTC
Labels: [Type] Enhancement, [Feature] Saving, [Feature] Template Editing Mode
