### ISSUE TITLE
Editor cut off midway by other fields

### ISSUE THREAD

**Issue by dynamicdriverepo** [WordPress/gutenberg#14760] opened 2019-04-02 07:39 UTC
**Describe the bug**
So we just updated our blog to Wordpress 5.x with the new editor enabled. When we edit EXISTING POSTS now, the editor is cut off by other fields such as Yoast SEO and other plugin fields. It's not Yoast in particular, but ANY fields added by 3rd party plugins.

**Screenshots**
![bug](https://user-images.githubusercontent.com/3308663/55384507-b5708080-54df-11e9-9140-c7117cbabc7a.jpg)

**Desktop (please complete the following information):**
 - Windows 10
 - Latest Google Chrome

**Comment by youknowriad** [comment] 2019-04-02 07:41
This is a duplicate of #11060 (Please read the thread to understand the problem and the solutions)

**Closed by youknowriad** 2019-04-02 07:41 UTC

**Comment by dynamicdriverepo** [comment] 2019-04-02 08:38
Issue fixed. Turned out to be Sassy Social Sharing plugin being the culprit.
