### ISSUE TITLE
Font weight 700 is not set when bolding text in heading block from toolbar

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#39287] opened 2022-03-08 13:14 UTC
### Description

When I select the heading block in any page or post and add any text inside that heading block. When I select this text and make it **bold** from the toolbar, then the font-weight of that text is being set to 600 instead of 700.

### Step-by-step reproduction instructions

1. Go to the backend of any page and post
2. Now select the heading block of the Gutenberg blocks
3. Now add any text to this heading block
4. Now select this text and make it bold from the toolbar

### Screenshots, screen recording, code snippet

I have added a video link of the font-weight issue in the heading block.

[https://www.loom.com/share/9636a25b3e004069a6d99f118e7a9226](https://www.loom.com/share/9636a25b3e004069a6d99f118e7a9226)

Some screenshots of the font-weight issue in the heading have also been added below.

[https://prnt.sc/O2HPAdbPIS0f](https://prnt.sc/O2HPAdbPIS0f)

[https://prnt.sc/XKBkFjTCtY27](https://prnt.sc/XKBkFjTCtY27)

### Environment info

- WordPress v5.9.1
- Chrome Browser ( Version 99.0.4844.51 )
- Mac OS

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-03-09 12:43
Hi, @aezazs-multidots.

The Bold button on the block toolbar does not mean "`font-weight:bold;` (700)".

It only wraps the selected text with a `strong` tag.

So, what font-weight the `strong` tag is displayed with depends on the browser's default style or the theme's style.

I believe the theme you have activated is Twenty Twenty One, which applies `font-weight:600` to the heading strong tag.

Here is the code:

https://themes.trac.wordpress.org/browser/twentytwentyone/1.5/style.css#L146
https://themes.trac.wordpress.org/browser/twentytwentyone/1.5/style.css#L2301

**Comment by t-hamano** [comment] 2022-04-16 09:14
@aezazs-multidots
I believe this issue is not a bug in WordPress or Gutenberg, so I close the issue.

If you have any questions, please do not hesitate to reopen it 👍

**Closed as completed by t-hamano** 2022-04-16 09:14 UTC
Labels: [Type] Question

**Comment by dossy** [comment] 2025-04-02 04:12
This is a consequence of WordPress defining `strong, b { font-weight: 600; }` in `wp-admin/css/common.css`.

https://github.com/WordPress/gutenberg/issues/30297#issuecomment-2771284137
