### ISSUE TITLE
Some global styles not updating

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#44040] opened 2022-09-09 22:50 UTC
### Description

Some styles are being reverted just after you save the page after setting them. Currently, there's no way to apply some global style for the `heading` and/or `button` elements.

### Step-by-step reproduction instructions

This seems to happen only if either pre-conditions are a true:
- admin on multisite install
- DISALLOW_UNFILTERED_HTML is defined and truthy
- Any role with edit_theme_options but w/o unfiltered_html 

So, to test, make sure any of the pre-conditions above are true (easiest one to test is to set `DISALLOW_UNFILTERED_HTML` to `true` in `wp-config.php`) and:

1. Spin up an instance of wp-env with GB 14.0.2;
1. Use a theme that supports global styles;
5. Go to the **BETA Site editor** (not the regular Gutenburg editor);
6. Go to global styles -> Fonts;
7. Change a `font`, `line-height` or appearance for the header element
8. Notice how it doesn't change
9. Make sure you have a button block in the page. Change the font-size for the button. 
10. Notice how it doesn't get change in the button. Interestingly enough, the other attributes do seem to be applied (appearance, etc) for the button element.

I'm not 100% sure, but It looks like the culprit is that at some point, Gutenberg used to ship with a compat file with mods to support these elements, but at some later point, this compat file was removed. Installing the 14.0.2 on a recent version of WordPress (i.e 6.0.1) won't provide the customized `kses.php` that sets the class to `WP_Theme_Json_Gutenberg`, [as it used to do in v13.6.0](https://github.com/WordPress/gutenberg/blob/v13.6.0/lib/compat/wordpress-5.9/kses.php#L25). Could that be related?

### What you expected to happen

I expected the font to save.

### What actually happened

The font didn't save.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/81248/189459261-d9cca2dc-75c0-4602-98e9-c92c00e5a2d2.mp4

---

https://user-images.githubusercontent.com/81248/189981976-581ebd17-7c14-4b45-9020-0dee8e6cee60.mp4

### Environment info

- WordPress 6.1-alpha-54044
- Gutenberg 14.0.2
- Firefox 105.0b9 (64-bit)
- Ubuntu Linux 18.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-09-12 08:16
Hi!

The settings in the styles sidebar are defaults. If a block has already been edited, the styles do **not** apply to that specific block, unless that block is reset, manually.

If a theme has a template in which the heading has a line height set, then the line height option will not work for that block, because it counts as having been edited.

But add a new heading block, then the line height you set under "Styles > Typography > Heading > Heading level > line height" will be used.

**Comment by fullofcaffeine** [comment] 2022-09-13 18:28
Hi @carolinan, thanks for reaching out!

You're right about this scenario. However, the actual issue I wanted to report is another one that I couldn't reproduce consistently at first, so this feature confused me. I finally managed to reproduce it and updated the issue. It's a different issue and seems related to `kses`. I added another screen-recording to illustrate it.

https://user-images.githubusercontent.com/81248/189981976-581ebd17-7c14-4b45-9020-0dee8e6cee60.mp4

**Comment by t-hamano** [comment] 2022-09-18 14:08
Hi @fullofcaffeine,

I was also able to reproduce the problem, but confirmed that there was a strange warning error about the heading.

![warning](https://user-images.githubusercontent.com/54422211/190911053-e74d4015-f66b-47cf-8fef-8cf92f19547d.png)

Furthermore, after updating to the latest WordPress 6.1, this warning disappeared and the issue didn't reproduce.

I think this problem has been resolved by [Changeset 54105](https://core.trac.wordpress.org/changeset/54105). At least after this alpha version (54105), the problem should not reproduce.

Therefore, I would like to close this issue, but feel free to reopen it if the problem has not been resolved.

**Closed as completed by t-hamano** 2022-09-18 14:08 UTC
Labels: [Type] Regression, Global Styles
