### ISSUE TITLE
Typography > Appearance controls should show available weights only

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#49090] opened 2023-03-15 10:43 UTC
## What problem does this address?

Currently adding Typography > Appearance controls to a block will render the entire range of font weight (100 - 900), plus their italic options: 

<img width="143" alt="Screenshot 2023-03-15 at 11 35 17 AM" src="https://user-images.githubusercontent.com/5375500/225283828-090bec4c-0921-43a3-bf78-dfe3c503995f.png">

Some fonts do not have all of these weights, so unexpected results occur when an Appearance selection is made and the font does not have that weight supplied.

## What is your proposed solution?

Would it be possible or a good idea to limit these options to only the weights that are available? 

I guess an alternative is to disable entirely the Typography > Appearance controls. 

cc @jasmussen @beafialho if you have any thoughts on this, thanks in advance!

**Comment by jasmussen** [comment] 2023-03-15 12:11
We should definitely limit the dropdown to only available weights and styles. The fact that it isn't seems like a bug, unless I'm missing something.

**Comment by cbirdsong** [comment] 2023-03-15 16:27
This problem was touched on ages ago in https://github.com/WordPress/gutenberg/issues/38998, but I never got around to filing it separately. This related issue is also relevant here:
- https://github.com/WordPress/gutenberg/issues/39370

I think this is another good candidate for a set of presets since variable fonts introduce a lot of, uh, potential variation since they go beyond the simple 100-900 scale. However, unlike spacing/font size presets, they would probably need to be constrained by the current font family since that is what would determine if a weight is a valid choice. 

In the meantime, I've been simply disabling the Typography > Appearance panel because I don't want to present nonsensical invalid options to editors, especially ones that result in inline CSS.

**Comment by hanneslsm** [comment] 2023-08-11 02:49
> The fact that it isn't seems like a bug, unless I'm missing something.

Why is this not a bug? For the regular (not variable) fonts, don't we see which weights are enqueued and just only display them?

> I think this is another good candidate for a set of presets since variable fonts introduce a lot of, uh, potential variation

I think we should look at variable fonts separately. They are introducing a lot of other features, not only font-weight.

> In the meantime, I've been simply disabling the Typography > Appearance panel because I don't want to present nonsensical invalid options to editors, especially ones that result in inline CSS.

I don't think this is a good option. I'm using semi-bold weights for example very frequently. I'm not using Extra Bold or Black however (and don't have them enqueued), so only they shouldn't be displayed.

**Comment by jasmussen** [comment] 2023-08-11 07:36
> Why is this not a bug? For the regular (not variable) fonts, don't we see which weights are enqueued and just only display them?

I may have used an odd turn of phrase. I'm suggesting that _it is a bug that we show weights that aren't available in the font_. I _think_ we are in agreement, but let me know if I misunderstood!

Agreed variable width fonts is something we should support, and is separate. They could even have a separate entry in the dropdown which opened a modal, or even a separate dropdown.

**Comment by hanneslsm** [comment] 2023-08-11 08:00
> The fact that it isn't seems like a bug…
>  I'm suggesting that it is a bug that we show weights that aren't available in the font.

Ah, I misunderstood! Yes, we are in agreement :)

**Comment by creativecoder** [comment] 2023-12-21 04:10
This came up with a theme builder I was working with this week. They selected different font weights and there was no visual change because there weren't font faces defined for those weights.

**Comment by colorful-tones** [comment] 2024-01-23 21:58
I'm adding the newly created [Feature] Font Library label, because I believe there are likely considerations that the underlying architecture will need to account for to surface font weights and even distinguishing variable fonts.

**Comment by colorful-tones** [comment] 2024-02-13 16:37
Based on a recent Editor Triage async I'm moving this item to the **Punted to 6.6** column on the [WordPress 6.5 Editor Tasks board](https://github.com/orgs/WordPress/projects/148/views/1).

**Comment by colorful-tones** [comment] 2024-05-22 18:20
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).

**Closed as completed** 2024-07-01 09:47 UTC
Labels: [Type] Bug, [Feature] Blocks, [Status] In Progress, [Feature] Typography, [Feature] Font Library
