### ISSUE TITLE
Image Size: Remember the last size used.

### ISSUE THREAD

**Issue by VyxiFaye** [WordPress/gutenberg#8663] opened 2018-08-07 14:59 UTC
It would be nice in future versions if we had the ability to change the image size default settings. In my case, I like my images large and wouldn't want "Thumbnail" as my default size. Would save me a few clicks on each blog post I do.

I currently have v 3.4.0

![screenshot_20180807-105805_chrome](https://user-images.githubusercontent.com/10146634/43783960-fd658828-9a30-11e8-83ba-88a1bb559194.jpg)

**Comment by youknowriad** [comment] 2018-08-07 15:18
In my case, it's using "Full" by default, I wonder if this is something plugins/themes are customizing in the media library.

**Comment by VyxiFaye** [comment] 2018-08-07 15:28
Interesting. I guess I need to poke around more to see what I can find.

**Comment by designsimply** [comment] 2018-11-27 17:47
Closed #12348 as a duplicate and noting the request to make the "Image Size" setting sticky the same way it currently works in the classic editor.

**Comment by designsimply** [comment] 2018-11-27 17:47
I tested with WordPress 4.9.8, Gutenberg 4.5.1, and the Twenty Seventeen 1.7 theme using Firefox 63.0.3 on macOS 10.13.6 just now and found that images are inserted as "Large" image size by default.

<img width="1280" alt="screen shot 2018-11-27 at 10 42 45 am" src="https://user-images.githubusercontent.com/1119271/49100524-5e0c8c00-f231-11e8-9d66-b4ccf46af525.png">
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=120&action=edit with WordPress 4.9.8, Gutenberg 4.5.1, and the Twenty Seventeen 1.7 theme using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by shuttermuse** [comment] 2019-01-10 19:07
Yes, this would be great if it remembered last settings. The "link to" setting often needs to be set to Media so that lightboxes work, but now you have to remember to do it manually for every image. What a pain!

**Comment by Cliffpro** [comment] 2019-02-04 19:49
So happy to have found this (I thought I was going crazy), but sad to see there's no update to this yet. As we're growing a blogging team at the office, it'd be nice to let them just work on creative and not have to make sure everyone selected the right image size on upload. A minor inconvenience and nothing dire, but would definitely be a nice setting to have!

**Comment by mayhemer** [comment] 2019-03-03 16:55
I **think** the 'large' size default pick is hard coded [here](https://github.com/WordPress/gutenberg/blob/8bd00c40e40f33829f488e17c323067292835024/packages/block-library/src/image/edit.js#L70).

**Comment by gaambo** [comment] 2019-07-03 16:58
> I **think** the 'large' size default pick is hard coded [here](https://github.com/WordPress/gutenberg/blob/8bd00c40e40f33829f488e17c323067292835024/packages/block-library/src/image/edit.js#L70).

Actually, I think it's hardcoded [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js#L68) in the `DEFAULT_SIZE_SLUG` constant. Sadly I don't see a way to change it, but i unset/deleted the large image size and it's selecting `full` for me by default. I guess it's just the first option in the select list and thats why.

**Comment by mbaierl** [comment] 2020-01-30 09:37
Any update on this? Causes a few more clicks for every single image uploaded...

**Comment by feastdesignco** [comment] 2020-02-17 14:55
This needs to be fixed.

Either provide a filter, or add it to "writing" settings page.

Changing the default values in options.php doesn't work either.

**Comment by feastdesignco** [comment] 2020-02-18 09:56
![image](https://user-images.githubusercontent.com/5629719/74724918-13e34200-520b-11ea-953b-207145dacb75.png)

**Comment by talldan** [comment] 2020-02-19 04:09
https://github.com/WordPress/gutenberg/issues/15091 mentions using the `image_default_size` setting. I'm conflicted about whether to close that as a duplicate of this. There seems to be two separate things being discussed:
- Setting a default value
- Making the value 'sticky', i.e. the editor remembering the last option used.

**Comment by feastdesignco** [comment] 2020-02-19 13:02
That depends on how "sticky" is defined and implemented. The original post here doesn't make any mention of sticky and I think it was a mistake for @designsimply  to conflate these two issues.

Similarly, https://github.com/WordPress/gutenberg/issues/8734 is not the same issue either and has mistakenly been tagged as such.

Site-wide settings should be defined via the database (options.php is currently the only method for this). Over-riding those on the post level makes sense. 

As a user, simply changing the image block once for a particular image, doesn't mean I want that to be the new "default". I don't want my post-level edits to change my site-wide settings. I don't think "sticky" makes sense in this case.

The scope of this particular issue is not "sticky" settings or the incorrect display of the image size (https://github.com/WordPress/gutenberg/issues/8734), but simply having the image block respect the user-specified image_default_size setting on first insert.

In a cascading preference when inserting the image block:

1. Use the Wordpress-set DEFAULT_SIZE_SLUG  constant for "large" so that we have a starting point
2. Check for a value in image_default_size (this is default blank on clean installs) and if present, use this value instead

Then rather than use DEFAULT_SIZE_SLUG  in https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js on line 201, 233, use the value from step #2

**Comment by feastdesignco** [comment] 2020-03-14 14:56
Bump. This is an ongoing problem.

![image](https://user-images.githubusercontent.com/5629719/76684385-18b8cd00-65e2-11ea-9907-abf31bbef9e9.png)

You already have a setting in the Wordpress core database for this:
![image](https://user-images.githubusercontent.com/5629719/76684405-3ab24f80-65e2-11ea-96c7-14494421916c.png)

@youknowriad any chance of getting this done?

**Comment by danielbachhuber** [comment] 2020-04-28 19:32
I have this problem too! My expectation is that the `image_default_size` option would be respected if set, given this is what the Classic Editor supports.

**Comment by laurentdebricon** [comment] 2020-06-10 08:24
Who has a solution ?

**Comment by Timoostrich** [comment] 2020-06-15 12:37
I have the same problem. Need to set image_default_size to "full".

**Comment by Emilybkk** [comment] 2020-09-20 22:50
Have the same problem. I also want it to be Align : Center by default.

**Comment by ErnestPH** [comment] 2020-10-30 09:21
Hi! 

> I have the same problem. Need to set image_default_size to "full".

Got a way on how to do this. On Settings >> Media, change the value for large to 0. And it will make the full size the default size automatically :)

**Comment by Mamaduka** [comment] 2021-03-17 08:17
Hi,

I would like to work on this issue and bring `image_default_size` into editor settings.

**Closed** 2021-03-24 03:15 UTC
Labels: [Block] Image, [Feature] Media, [Status] In Progress, [Type] Enhancement

**Comment by Intervik** [comment] 2022-01-31 19:12
Still waiting for a solution on this as well. Gutenberg must deliver a way to set default values. Stop creating new "fancy things" and make current editor UX useful. The Gutenberg developers seems to not working with WordPress clients in real life. Lets make Gutenberg less confusing and easier: one way is to release filters in PHP transported into the js enviroment.

**Comment by feastdesignco** [comment] 2022-04-07 22:55
> 

This has been fixed: https://github.com/FiliagoDev/WordPress/commit/53aff531023b4716746fc2ce0604f52a4f7da1aa
