### ISSUE TITLE
Mobile (Android) - Hitting enter at the end of a heading block does not create a new block

### ISSUE THREAD

**Issue by antonis** [WordPress/gutenberg#29116] opened 2021-02-18 14:29 UTC
## Description
Hitting enter at the end of a heading block does not create a new block

## Step-by-step reproduction instructions

1. Create a new post
2. Add a heading block
3. Write something and hit enter
4. Notice that a second line is created
5. Continue writing
6. Notice that the new line is unformatted 

### Note
* This issue is reproduced only on Pixel 2 and Pixel 3 devices (with Android 11) at this point
* Unsuccessfully tried to reproduce this on Pixel emulators with Android 9,10,11 

## Expected behaviour
Hitting enter at the end of a heading block creates a new paragraph block

## Actual behaviour
Hitting enter at the end of a heading block creates a new line without formatting

## Screenshots or screen recording (optional)

![device-2021-02-18-154728](https://user-images.githubusercontent.com/304044/108370644-8e231980-7205-11eb-861d-7f5ca215785a.gif)

## WordPress information
- WordPress version: 16.6
- Gutenberg version: 1.46.0

## Device information
- Device: Pixel 2 XL
- Operating system: Android 11
- WordPress app version: 16.6

**Comment by jhnstn** [comment] 2021-02-18 18:47
Related issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/3081

**Comment by SiobhyB** [comment] 2021-07-05 09:15
I'm also seeing this behaviour on the very latest beta of the app, 17.7, on a Pixel 5 running Android 11. 

If I carry on typing after pressing enter and then move away from the heading block, the following error pops up:

![wp-1625476328624](https://user-images.githubusercontent.com/2998162/124448102-f9ffbc00-dd79-11eb-9434-1169b76ef25f.png)

**Comment by hypest** [comment] 2022-03-10 16:25
Can't reproduce on my Pixel 2XL Android 11 with gutenberg-mobile trunk (hash [0d32b342](https://github.com/wordpress-mobile/gutenberg-mobile/commit/0d32b34254a1f1e655b08b77aa11c53d8218118f)) that points to Gutenberg trunk at [9973fda](https://github.com/WordPress/gutenberg/tree/9973fdabaa49a0ea46c8c50ff52ca3d1c02c1863)

Closing as fixed but, happy to reopen if the issue still exists, thanks!

**Closed by hypest** 2022-03-10 16:25 UTC
Labels: [Type] Bug, [Priority] High, Mobile App - i.e. Android or iOS
