### ISSUE TITLE
Scripts: Add a description of the `--no-watch` option to the documentation

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#51695] opened 2023-06-20 12:22 UTC
In #44237, the `--no-watch` option was added to the scripts command. However, it is not described in the README, so unless you discover the PR or read the code, you will not know this option exists.

It would be nice to add a description of this option in the [README](https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/README.md) of the package.

It would also be better to update [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/CHANGELOG.md) as well. This PR was merged on February 2 and should be included in the version 25.4.0 section released on February 15.

**Comment by noahbcaldwell** [comment] 2023-06-20 13:37
I would like to be assigned to this issue!

**Comment by t-hamano** [comment] 2023-06-20 13:45
@noahbcaldwell

Thank you for your interest in this issue. You have been assigned 👍

**Comment by Armondal** [comment] 2023-07-28 03:24
As the issue is not solved yet. Can i also be assigned and submit a PR ?

**Comment by t-hamano** [comment] 2023-07-28 12:20
Hi @Armondal,

Thanks for your interest in this issue. It appears that #51707 has already been submitted for this issue, but it has not been merged yet. I would like to check on the status of #51707.

**Comment by t-hamano** [comment] 2023-07-28 12:30
@Armondal 

I would like to assign you to this issue. Closed #51707 will be your reference when you submit your PR.

If a PR is submitted, happy to review it!

**Comment by aurooba** [comment] 2023-08-24 15:15
Looks like this issue has been taken care of and I see a brief description of the `--no-watch` option in the documentation, closing it. Thanks for the addition @Armondal!

**Closed as completed by aurooba** 2023-08-24 15:15 UTC
Labels: [Type] Developer Documentation, Good First Issue, [Tool] WP Scripts
