### ISSUE TITLE
Inline style for add_editor_style( 'style-editor.css' );?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#13008] opened 2018-12-19 10:01 UTC
Can `add_editor_style( 'style-editor.css' );` have inline style added?

The problem is that I want `.wp-block { max-width: 500px; }` for `post` and `.wp-block { max-width: 1000px; }` for `page` but that's currently not doable with just style-editor.css.

There may be other use cases for this as well.

**Comment by designsimply** [comment] 2019-01-31 20:38
Closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/12874 and noting there is a workaround at https://github.com/WordPress/gutenberg/issues/12874#issuecomment-452929053. Sorry for not catching this as a duplicate before!

**Closed by designsimply** 2019-01-31 20:38 UTC
Labels: Custom Editor Styles, Needs Technical Feedback, [Type] Help Request
