### ISSUE TITLE
Reusable Block Do not have any Attributes for inner blocks?

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#24048] opened 2020-07-20 10:14 UTC
**Describe the bug**
If I make any block reusable and try to edit it, it doesn't show any attributes or options in the sidebar panel for that block? Is it a bug? It says no block selected instead, however, the block is selected. 

Now, this is also an issue for custom CSS that is applied to that block as this doesn't apply in the editor if it is saved as a reusable block. 

I've tried it with the latest stable WP 5.4.2 and also by activating the latest Gutenberg Plugin v 8.5.1 and the issue remains as it is.
 
**To reproduce**
1. type a paragraph
2. make it reusable
3. edit it to modify paragraph styling or font-size
4. you won't be able to do it as there are no sidebar options

**Expected behavior**
It should keep the block attributes that are default and also those that are added by 3rd party devs using block filter API.

**Screenshots**
![Image 2020-07-20 at 3 00 31 PM](https://user-images.githubusercontent.com/5817882/87926523-3ec41180-ca9b-11ea-9401-efe50a080382.png)

![Image 2020-07-20 at 3 04 55 PM](https://user-images.githubusercontent.com/5817882/87926539-45528900-ca9b-11ea-8b32-19d4136d8671.png)

![Image 2020-07-20 at 3 06 03 PM](https://user-images.githubusercontent.com/5817882/87926554-4a173d00-ca9b-11ea-8504-4212807b869c.png)

![Image 2020-07-20 at 3 08 02 PM](https://user-images.githubusercontent.com/5817882/87926568-500d1e00-ca9b-11ea-9674-ee945c08908e.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]: **Tried on both.**
- If the Gutenberg plugin is installed, which version is it?  **8.5.1**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Comment by youknowriad** [comment] 2020-07-20 10:24
Duplicate of #18560

**Closed by youknowriad** 2020-07-20 10:24 UTC
