### ISSUE TITLE
Block image is missing some useful settings available in the classic editor

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#4007] opened 2017-12-14 16:48 UTC
The block image is missing the size selection (and other 2 settings for alignement and image link) when you click for adding new image on the modal

![gutenberg - screenshot-192 168 1 10-2017-12-14-16-57-12](https://user-images.githubusercontent.com/4604932/34002777-d80ed940-e0f3-11e7-9677-8655b6a9b4d4.jpg)

This is the modal in the classic editor with the additional settings:

![classic editor - screenshot-192 168 1 10-2017-12-14-17-03-03](https://user-images.githubusercontent.com/4604932/34002685-88de2966-e0f3-11e7-9ad9-f2a214146300.jpg)

The size selection is in the block tab settings but this means that you have to add the image and then click on the tab block and then select the size.

![gutenberg block settings - screenshot-192 168 1 10-2017-12-14-17-07-43](https://user-images.githubusercontent.com/4604932/34002910-34fce5ca-e0f4-11e7-8e65-4d95b7090298.jpg)

And in the block settings tab is also missing the field for adding custom image css class and some other options (this above is the modal when you want to canghe settings on added image):

![classic editor - media windows settings - screenshot-192 168 1 10-2017-12-14-17-09-18](https://user-images.githubusercontent.com/4604932/34003172-e6091528-e0f4-11e7-99ac-5cd9ccd71e3d.jpg)

**Comment by karmatosed** [comment] 2017-12-14 18:37
A little point but you can add a CSS class to each block so that solves the custom class issue. That said, I do think the flow makes sense, you add an image then you add treatment like CSS and alignment. Also then you can visually 'see'. I would argue that the way the existing media input works is not as user friendly.

**Comment by overclokk** [comment] 2017-12-14 19:14
> A little point but you can add a CSS class to each block so that solves the custom class issue.

You can add a custom CSS class only to a block and not to image tag itself

```html
<figure class="wp-block-image custom-css-added-from-block-tab">
    <img src="http://192.168.1.10/italystrap/wp-content/uploads/2013/03/cropped-cropped-image-alignment-1200x4002.jpg" alt="" class="css-class-added-manually" />
</figure>
```

You can add manually on the "Edit as HTML" but the users are not so expert to touch HTML

Also in the classic editor there is a filter that it can be used to add some default CSS class to the field: https://codex.wordpress.org/Plugin_API/Filter_Reference/get_image_tag_class it could be useful to have the same in Gutenberg.

> I do think the flow makes sense, you add an image then you add treatment like CSS and alignment. Also then you can visually 'see'.

Yes, less click, better UX

>  I would argue that the way the existing media input works is not as user friendly.

In the classic editor or in Gutenberg?

**Comment by designsimply** [comment] 2018-07-17 01:06
Tested and confirmed that Attachment Display Settings are no longer present when inserting an image but all are available after the image has been inserted. (screenshots: [classic](https://user-images.githubusercontent.com/1119271/42790763-f4a340ee-8929-11e8-9966-9cf904b7655e.png), [gutenberg](https://user-images.githubusercontent.com/1119271/42790764-f64341c4-8929-11e8-8e89-8fcb2d3a75dc.png))

* Alignment
* Link To
* Size

Also confirmed that the following advanced options are no longer available when selecting edit for a previously inserted image. (screenshots: [classic](https://user-images.githubusercontent.com/1119271/42790828-4cc12692-892a-11e8-8c11-be2b0ec27ec8.png), [gutenberg](https://user-images.githubusercontent.com/1119271/42790966-f082120a-892a-11e8-9658-11119cf4a786.png))

* Image Title Attribute
* ~Image CSS Class~ (now avail. in block settings as Advanced > Additional CSS Class)
* Open link in a new tab
* Link Rel
* Link CSS Class 

<sup>Tested with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by designsimply** [comment] 2018-07-17 01:08
Thank you for reporting this issue! Closing in favor of https://github.com/WordPress/gutenberg/issues/7504 because it has more information about related historical changes in core.

**Closed by designsimply** 2018-07-17 01:08 UTC
Labels: Backwards Compatibility, Blocks, Media, [Type] Enhancement
