### ISSUE TITLE
Page template selector broken in two ways

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#45956] opened 2022-11-22 01:51 UTC
### Description

I use themes which have *not* opted into full-site editing, but have page templates enabled via comments in the theme code:

```
<?php
/*
Template Name: xxx
*/
?>
```

Error 1: When a page is edited, 'Default template' always shows in the sidebar, whichever template the page uses. If you click it, you see a popup with a select box, where the correct page template shows. Changing this dropdown and saving does update the page template, but 'Default template' continues to appear in the sidebar.

Error 2: In the above popup, there is an icon which allows you to create a new template through the Template Editor. This is meant to be an opt-in feature, so should not be displaying, and makes no sense to users when they click it.

### Step-by-step reproduction instructions

1. With a default installation of WordPress, install a theme without full-site-editing enabled, and create a page template with a comment like described above.
2. Create a new page, and attempt to set the page template. See results as described above.

### Environment info

Wordpress 6.1.1, no Gutenberg plugin, numerous custom-build themes

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by petitphp** [comment] 2022-11-22 15:41
This issue could be a duplicate of https://github.com/WordPress/gutenberg/issues/45216

**Comment by ndiego** [comment] 2022-11-29 14:53
@smerriman Thanks for reporting this. Do you happen to have a theme.json file in your theme? I believe the issue you are experiencing is the same one reported in https://github.com/WordPress/gutenberg/issues/45216, but if you have a chance to take a peak at that issue, that would be awesome. Looks like there is some work in progress to address this.

**Comment by Mamaduka** [comment] 2022-12-05 16:37
@smerriman, it looks like you're using `theme.json` with a classic theme. In this case, Block Templates are opt-out; it has been like this since WP 5.8. See #32858.

To disable the feature add `remove_theme_support( 'block-templates' );` to your functions.php

The bug with the `Default template` has been resolved via #46304.

**Closed as completed** 2022-12-22 20:51 UTC
Labels: [Type] Bug, [Feature] Document Settings
