### ISSUE TITLE
The row block needs a special class name ex. ".is-row"

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#39284] opened 2022-03-08 11:29 UTC
## What problem does this address?
I need to remove some top and bottom margins of the **Row** inner blocks that I originally added for the **Group** inner blocks, but I can't because there's no special class name to differentiate them as they both share the same class name. I'm not sure why the **Row** block doesn't have its own class (.wp-block-row), but at least I think it should have a special identifier, like adding ".is-row" class.

## What is your proposed solution?
Add ".is-row" class name to the **Row** block.

**Comment by Mamaduka** [comment] 2022-03-08 11:54
Thanks for contributing, @premitheme.

It looks like a duplicate of #38126, and there's also a PR that will add Row-specific class - #39181.

**Closed as completed by Mamaduka** 2022-03-08 11:54 UTC
Labels: [Status] Duplicate, [Block] Group
