### ISSUE TITLE
Negative value on block's margin settings

### ISSUE THREAD

**Issue by daviedR** [WordPress/gutenberg#38551] opened 2022-02-06 04:34 UTC
## What problem does this address?

Negative value is currently not allowed on block's margin settings. When inputting negative value on the margin input field, it's automatically reverted back to `0`.

## What is your proposed solution?

Allow negative value on block's margin settings, for example `-1rem`, `-10px`, etc.

**Comment by carolinan** [comment] 2022-02-07 09:30
Hi!
I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/32644

**Closed as completed by carolinan** 2022-02-07 09:30 UTC
Labels: [Status] Duplicate
