### ISSUE TITLE
Image block: Resizing jumps oddly

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17174] opened 2019-08-23 20:44 UTC
**Describe the bug**
Resizing an image causes an odd jump once I let go of the resizer. Also the block loses focus after resize too.

**To reproduce**
1. Add an image block.
2. Resizing the image.
3. Observe the quick jump in size from either direction, and also notice that the block no longer has focus.

**Expected behavior**
I expect there not to be a rapid jump when resizing. I also expect to have the block maintain my focus.

**Screenshots** The gif just shows the jump when sizing the image down.

![imagesizing](https://user-images.githubusercontent.com/617986/63622552-e6933f80-c5ab-11e9-9222-fe1a7682d29d.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0.2
 - Gutenberg 6.3

**Comment by senadir** [comment] 2019-08-23 21:16
the lack of focus is reported here https://github.com/WordPress/gutenberg/issues/15420

interestingly, the jump only happen on subsequence resizing, the first time you resize it works fine, after that it breaks. this must have something to do with how we're setting the values after resizing

**Comment by senadir** [comment] 2019-08-23 23:06
somehow I cannot reproduce anymore, not sure why, overall I've got a fix for this problem & the second problem that you mentioned here https://github.com/WordPress/gutenberg/pull/16475#issuecomment-524457509

I will push it so we can test it more

**Closed** 2019-08-25 03:47 UTC
Labels: [Block] Image, [Type] Bug
