### ISSUE TITLE
Upon refresh: "Your site doesn’t include support for the "mynamespace/mycustomblock" block. 

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#13793] opened 2019-02-08 23:18 UTC
**Describe the bug**
When creating a custom block, it works until I refresh the editor page. After refresh, this error appears instead of the block:

`Your site doesn’t include support for the "mynamespace/mycustomblock" block. You can leave this block intact, convert its content to a Custom HTML block, or remove it entirely.`

# Here I am adding my custom block
<img width="733" alt="screen shot 2019-02-08 at 5 55 09 pm" src="https://user-images.githubusercontent.com/1638128/52510694-11e3ad80-2bcb-11e9-9e4d-af77cd59884f.png">

# Here is my block in the editor
<img width="801" alt="screen shot 2019-02-08 at 5 55 20 pm" src="https://user-images.githubusercontent.com/1638128/52510710-1f993300-2bcb-11e9-87fd-ea1c24849b2e.png">

# Here is what shows after I refresh the page
<img width="693" alt="screen shot 2019-02-08 at 5 55 43 pm" src="https://user-images.githubusercontent.com/1638128/52510728-2aec5e80-2bcb-11e9-938b-9378c9e53272.png">

**To Reproduce**
1. Create a custom block by enqueuing it with this code:
```
function my_block_editor_scripts(){

	// Required things to build Gutenberg Blocks
	$required_js_files = array(
		'wp-blocks',
		'wp-i18n',
		'wp-element',
		'wp-editor'
	);

	// Gutenberg Block JSX code
	wp_register_script( 'my-custom-script', add_query_arg( 'my-custom-block-js', true, get_bloginfo( 'url' ) ), $required_js_files, time() );

	register_block_type( 'mynamespace/mycustomblock', array(
	 	'script' => 'my-custom-script',
	) );
}
add_action( 'init', 'my_block_editor_scripts' );

function my_block_javascript() {

	if ( ! isset( $_GET['my-custom-block-js'] ) ) {
		return;
	}

	header('Content-Type: text/javascript'); ?>
	const { __ } = wp.i18n;
	const { registerBlockType } = wp.blocks;

	registerBlockType( 'mynamespace/mycustomblock', {
		title: __( 'My Custom Block' ),
		icon: 'lock',
		category: 'common',

		edit() {

			return ( 'This text is from My Cusom Block'	);

		},
		save() {
			return ( 'This text is from My Cusom Block'	);
		},

	} );<?php

	die();
}
add_action( 'init', 'my_block_javascript' );
```

2. Go to the Gutenberg editor, and add your custom block
<img width="441" alt="screen shot 2019-02-08 at 6 12 13 pm" src="https://user-images.githubusercontent.com/1638128/52511241-14470700-2bcd-11e9-8054-6ea8ad9ff211.png">

3. Save the post, and then refresh the page in your browser.
4. Notice the error that is now showing in place of the custom block: `Your site doesn’t include support for the "mynamespace/mycustomblock" block. You can leave this block intact, convert its content to a Custom HTML block, or remove it entirely.`

**Expected behavior**
I don't know if I have registered the block correctly here. but:

If I've registered the block incorrectly, I expect the block the show the error _all the time_, and it shouldn't work before a page refresh.

If I've registered the block correctly, I expect it to work _all the time_. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.2 (18C54)
 - Browser Chrome 
 - Version Version 72.0.3626.81 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version: 5.0.0

**Comment by HardeepAsrani** [comment] 2019-02-09 00:18
It happens when the float isn't loaded, which I guess is the case when you refresh. You should put your block's JS in a separate JavaScript file instead of wrapping it around in a PHP function. It's just a recipe for disaster if you add your code this way. 😄

**Comment by mintplugins** [comment] 2019-02-09 00:41
@HardeepAsrani It's written this way purely for a reduced-code example. I discovered this while doing it in a separate file. So that isn't the reason.

**Comment by HardeepAsrani** [comment] 2019-02-09 00:43
@mintplugins Haha, then I can't predict. If you can make a github of your code with separate file then I'd love to try and help you out with this. 😄

**Comment by mintplugins** [comment] 2019-02-09 01:22
Sure thing - I'll get that together and paste a link. Thanks for your help

**Comment by mintplugins** [comment] 2019-02-09 03:46
@HardeepAsrani I put together a repo to demonstrate the issue:
https://github.com/mintplugins/sample-gutenberg-block

To update, I've found the issue - or at least a symptom of the issue. I believe the real underlying issue is still an issue with Gutenberg itself. 

I am modifying the script_loader_tag from `text/javascript` to `text/babel` in order to allow JSX to be processed through babel. 

I do that by filtering the tag like this:
```
// This allows us to use JSX by changing it to text/babel
function my_block_editor_modify_jsx_tag( $tag, $handle, $src ) {

	// Convert the custom block file to be recognized as a JSX file
	if ( 'my-custom-script' == $handle ) {
		$tag = str_replace( "<script type='text/javascript'", "<script type='text/babel'", $tag );
	}

	return $tag;
}
add_filter( 'script_loader_tag', 'my_block_editor_modify_jsx_tag', 10, 3 );
```

If I remove that filter, the block still loads properly after a refresh. 

The fact that the block works immediately is what leads me to believe this is a problem with Gutenberg. 

This wasn't an issue until version 4.5 of Gutenberg, when this error message was introduced.

**Comment by mintplugins** [comment] 2019-02-09 04:06
@brandonpayton Do you have any idea why there would be a false positive on my block not existing, simply because the script containing it uses `text/babel` instead of `text/javascript`?

**Comment by HardeepAsrani** [comment] 2019-02-09 06:15
It doesn't happen for me. The block isn't being loaded in the first place. As far as I know, you need to enqueue babel-browser for `text/babel` to work: https://github.com/baixuexiyang/babel-browser

**Comment by mintplugins** [comment] 2019-02-09 14:36
@HardeepAsrani For sure - I had enqueued babel in another location. I have added it to the sample plugin for you now: 

https://github.com/mintplugins/sample-gutenberg-block/blob/master/sample-gutenberg-block.php#L26

The problem I described above still stands. I believe it may be a timing issue with babel transpiling, and gutenberg assuming the block doesn't exist too early.

**Comment by HardeepAsrani** [comment] 2019-02-09 20:59
While I can't tell you what was the issue but it's caused by babel-browser. I compiled the script quickly using http://babeljs.io/repl/ and it changed `text/javascript` from `text/babel` and it worked just fine. I guess compiled code has some inconsistencies or it isn't considered at load? I'm not sure but yea, bable-browser is the culprit.

**Comment by mintplugins** [comment] 2019-02-09 23:03
Yeah that's exactly what I said as well here: 
https://github.com/WordPress/gutenberg/issues/13793#issuecomment-462010233

Thanks for confirming the issue is happening to you too

**Comment by youknowriad** [comment] 2019-02-11 11:19
I'm going to close this issue as not a Gutenberg issue. The problem is that the registration of the block is happening too late when babel-browser is used.

**Closed by youknowriad** 2019-02-11 11:19 UTC

**Comment by mintplugins** [comment] 2019-02-11 13:17
@youknowriad In my opinion what we really have is a fundamentally incorrect way of assuming blocks aren't in existence in Gutenberg. But I can understand how you might not agree.

**Comment by youknowriad** [comment] 2019-02-11 13:21
@mintplugins I agree with you that ultimately, it would be better if the UI is reactive. which means it updates when the block get registered/unregistered but this is a very big refactoring because it means the parsing should be reactive as well. As soon as a block is registered/unregistered, the parsing should be triggered again for the post.

I'm open to this being explored but it's not an immediate focus.
