### ISSUE TITLE
Gallery Block: Drag and Drop Image doesnt work

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#3653] opened 2017-11-25 10:57 UTC
when i move a image with drag and drop to editor then is open a new Image Block.

https://wordpress.slack.com/files/U1E9F2UUF/F85FP7TUM/gallery_dragdrop.mp4

**Comment by mtias** [comment] 2017-11-27 10:46
Closing as duplicate of #3365.

**Closed by mtias** 2017-11-27 10:46 UTC
