### ISSUE TITLE
Experience editing in mobile browser: issues with focus when adding more paragraphs

### ISSUE THREAD

**Issue by jeherve** [WordPress/gutenberg#49857] opened 2023-04-17 08:30 UTC
### Description

Focus isn't moving down the page when you add more blocks that appear downer on the page.

### Step-by-step reproduction instructions

1. Start in a mobile browser. I'm using Safari on iOS 16.3.1.
2. Go to Posts > Add New.
3. Add a first paragraph.
4. Hit return, and add another paragraph.
5. Hit return, and add yet another.
6. At one point, you will hit return, but the focus doesn't move to show you where you are typing (see screencast below)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/426388/232429221-42b577c0-6e9d-44a1-8f01-6ebf1ded2308.mp4

### Environment info

- WordPress 6.2
- No Gutenberg plugin
- Twenty Twenty Three theme (this also happens with other themes, including non block-themes)
- Safari on iOS 16.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeherve** [comment] 2023-04-17 08:30
This was also reported here:
https://fosstodon.org/@kev/110147621066722874

**Comment by ellatrix** [comment] 2023-08-18 13:34
This is a duplicate of #33198 :)

**Closed as completed by ellatrix** 2023-08-18 13:34 UTC
Labels: [Type] Bug, [Focus] Accessibility (a11y), Mobile Web
