### ISSUE TITLE
Dragging between different types of  blocks,  top bar icons are not restored correctly.

### ISSUE THREAD

**Issue by Fujix1** [WordPress/gutenberg#9395] opened 2018-08-28 10:50 UTC
When dragging from a block into another one, icons on the top bar (block type changer, text alignments etc.) disappears. Then dragging back to the original block, those icons are not restored correctly.
To get back them, you have to click on the edge of the block or another block.

![9ee245aaa3d71925c0622cd8b7486bac](https://user-images.githubusercontent.com/13434151/44717959-7fa68c00-aaf9-11e8-8cc1-d9e04b795569.gif)

**To Reproduce**
1.  Select a paragraph and drag to select text.
2.  Keep dragging into a different type of block, for example a heading.
3.  Top bar icons disappears.
4.  Keep dragging back into the original paragraph block.
5.  The icons are missing as long as the caret is inside the block.

**Tested versions**
GT: 3.6.2
Win Chrome: 68.0.3440.106
Win Firefox: 61.0.2

**Comment by arunsathiya** [comment] 2018-08-28 16:36
Noting that I was able to reproduce this as well.

This happens **when the toolbar is not fixed to the top as well**.

![toolbar missing when selection comes back in after going outside of a block](https://user-images.githubusercontent.com/18581859/44737031-82f84280-ab0e-11e8-9a6e-a37fae8daaa2.gif)

## Additional information

The toolbar is nowhere to be seen when one clicks anywhere on the original block. One has to click on a different block to see the toolbar appear on that block, and click again on the original block to see the toolbar appear again.

**Comment by jburciaga0** [comment] 2018-09-27 15:54
One more addition to this thread - I reproduced this as well but I had _deleted_ another block under the block I was trying to edit. I refreshed my browser and the disappearing toolbar issue persisted, see here:

![gutenburg_bug_1](https://user-images.githubusercontent.com/34053009/46158010-d525a400-c231-11e8-954f-32138d1c5e48.gif)

**BUT**

When I switched from Safari to Chrome and clicked to edit the post, it took me to the /wp-admin interface to edit the post and the toolbar stayed as well as the options on the side for the block, much better. See here:

https://d.pr/i/vEAsXf

Safari: Version 12.0 (13606.2.11)
Chrome: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by youknowriad** [comment] 2019-11-19 09:09
That's simple I think. It's because while we're dragging if we restore the selection to a single block, that block is not marked as "selected" in the state so the toolbar doesn't appear until we click it.

**Comment by paaljoachim** [comment] 2021-02-21 00:31
In WordPress 5.7 beta 3 and Gutenberg plugin 10.
Twenty Twenty One.

![Multi-Select](https://user-images.githubusercontent.com/5323259/108611968-5e7e3800-73e4-11eb-88c4-02adc5a2ab24.gif)

I also tested with the top bar icons. It shows the same as the above gif.
I will go ahead and close this issue. If I am mistaken then we can of course reopen.

**Comment by paaljoachim** [comment] 2021-02-21 00:32
In WordPress 5.7 beta 3 and Gutenberg plugin 10.
Twenty Twenty One.

![Multi-Select](https://user-images.githubusercontent.com/5323259/108611968-5e7e3800-73e4-11eb-88c4-02adc5a2ab24.gif)

I also tested with the top bar icons. It shows the same as the above gif.
I will go ahead and close this issue. If I am mistaken then we can of course reopen.

**Closed by paaljoachim** 2021-02-21 00:31 UTC
Labels: [Feature] Block Multi Selection, [Feature] Writing Flow, [Type] Bug
