### ISSUE TITLE
Input field or scroll years to change the publish date.

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#9039] opened 2018-08-15 19:32 UTC
Let say that I have post from 2014 and now I want to update the old post instead of creating new post. With Gutenberg now I have to click though all the months from 2014 to 2018 this is not so friendly. There should be scroll option to choose which years like in this picture. 

![years-choose](https://user-images.githubusercontent.com/13035541/44168785-906c0080-a0fc-11e8-89e2-467f72448f2a.png)

**Comment by designsimply** [comment] 2018-08-15 20:16
Thank you for reporting this and including a screenshot! 

Closing as a duplicate of #7241.

We're consolidating discussion of enhancements to the date picker on #1311.

**Closed by designsimply** 2018-08-15 20:16 UTC
Labels: [Component] Post Settings, [Status] Duplicate, [Type] Enhancement
