### ISSUE TITLE
Vimeo Embed doesn't work as reusable block

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#10072] opened 2018-09-20 14:42 UTC
I created a Vimeo embed block and saved it as a reusable block. After saving it as a reusable block, it would no longer display the video on the front-end. The video was visible in the editor, but only the link was visible on the front-end. It worked fine on the front-end until I made it into a reusable block.

**To Reproduce**
1. Add a Vimeo Embed block with link to a video
2. Save Draft and preview it on the front-end, looks good
3. Add to Reusable Blocks
4. Save Draft and preview it on the front-end, no longer shows the video

**Expected behavior**
The video should still display even after turning it into a reusable block

**Screenshots**
Back-end reusable block
![vimeo-reusable-block-backend](https://user-images.githubusercontent.com/34601694/45825942-6096b680-bcc1-11e8-8401-8719cbba0ee0.PNG)

Front-end reusable block
![vimeo-reusable-block-frontend](https://user-images.githubusercontent.com/34601694/45825969-7906d100-bcc1-11e8-8abb-5f2af41fa9c6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest version

**Additional context**
- Gutenberg 3.9.0-rc2
- WP 4.9.8

**Comment by annestk** [comment] 2018-09-20 15:07
I've also run into the problem where embeds stop displaying properly (only show link) on the front end when they're converted to reusable blocks, but it's not limited to Vimeo. It's also a problem with youtube, instagram, twitter, reddit, imgur and facebook (possibly a general problem?).
I encounter the issue both in 3.8 and 3.9RC2 (Windows 10, Chrome 69, WP 4.9.8)

**Comment by chrisvanpatten** [comment] 2018-09-20 16:29
@ianbelanger79 Would you be able to try #10035? I believe that will solve this.

**Comment by ianbelanger79** [comment] 2018-09-20 20:15
Hi @chrisvanpatten,

I would love to test it, but I am having trouble creating the plugin package for that branch, as soon as I get it worked out I will test it and report back

**Comment by aduth** [comment] 2018-09-21 14:43
Is this duplicate of #9938? cc @notnownikki

**Comment by notnownikki** [comment] 2018-09-21 14:45
Yes, https://github.com/WordPress/gutenberg/pull/10035 is up for review as a fix to saving embeds as reusable blocks and the front end rendering.

**Comment by aduth** [comment] 2018-09-21 14:50
Okay, in that case let's consolidate to track at #9938 as the issue to be closed. Thanks all.

**Closed by aduth** 2018-09-21 14:50 UTC
Labels: Reusable Blocks, [Type] Bug
