### ISSUE TITLE
Cannot open in new window for links and from pictures

### ISSUE THREAD

**Issue by Biobobski** [WordPress/gutenberg#8842] opened 2018-08-10 15:36 UTC
I am trying to add a link, when i click open in window button it just turns the picture below blue and doesn't save the option the only way round it is to move the text below the image, add the option then move back up again.

There is also no option to click a picture and open in a new window

**Comment by abrightclearweb** [comment] 2018-08-10 19:55
I tried adding a link above an image and found it worked sometimes and other times it didn't. Here is a screengrab. First the link button didn't seem to work, then when I tried to click in the URL field, nothing happened. Using Gutenberg 3.5.

![adding a link above an image](https://user-images.githubusercontent.com/7430856/43978442-2e9e5a68-9cdf-11e8-8cd2-0e596f0eeb24.gif)


I also can't see a way to open image links in a new tab.

![linked image - no open in new tab option](https://user-images.githubusercontent.com/7430856/43977509-4fc6ee2e-9cdc-11e8-863f-2795b2fb5c03.png)


Other than this roundabout method:

Add an image in a block and link it.

Switch from the Visual Editor to the Code Editor and manually insert a `target="_blank"` to the` <a>` tag in the image block. 

![image as custom html opening in new tab](https://user-images.githubusercontent.com/7430856/43977528-617c7468-9cdc-11e8-8199-7ea405813ebf.png)

Then switch back to the Visual Editor. You'll see a message **This block has been modified externally**.

Choose Keep as HTML. It mangles the HTML Preview, though the image is the correct size on the front end.

![modified image link preview](https://user-images.githubusercontent.com/7430856/43977577-7fa21038-9cdc-11e8-92f3-dd89717cabd5.png)

**Comment by talldan** [comment] 2018-12-11 08:38
Thanks for reporting this @Biobobski. Both of the issues mention look to now be resolved, so I'll close the issue if that's ok with you.

Here's a gif showing a link being added above an image block and being set to open in a new tab:
![link-above-image](https://user-images.githubusercontent.com/677833/49787647-31449280-fd62-11e8-91d0-adc32f5ca3f3.gif)

Image blocks now also have an Open In New Tab option in the sidebar.

Do let me know if you can still reproduce them and I can look into what the issue is.

**Closed by talldan** 2018-12-11 08:38 UTC
Labels: Blocks, [Type] Bug

**Comment by talldan** [comment] 2018-12-13 00:45
Hi @ashloff - are there any plugins you're using that might be causing this issue? I don't think there are any lightboxes in Gutenberg.

**Comment by ashloff** [comment] 2018-12-13 07:33
That was it @talldan ! I disabled the plugins and found that one of them was causing a lightbox to appear. Thanks.

**Comment by gloofer** [comment] 2019-08-18 16:13
Hi. Not quite sure if this counts as an issue or a request, but I think it is related to this post. When using the block type Gallery in a post I can choose if the full size source image shall be opened if a user click the thumbnail in the gallery. But I want it to open in a new tab or in a new window, not in the same window. I miss something like a check box (open in new tab) in the block admin panel. Or is there already an easy way to do this, that I have missed?
![bild](https://user-images.githubusercontent.com/6996227/63227138-cba78080-c1e3-11e9-9582-0d46be035e9a.png)
