### ISSUE TITLE
Columns Block: Spacing control visible in classic themes in WP 6.3 RC 1, but doesn't work

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#52909] opened 2023-07-24 23:47 UTC
### Description

In the WordPress 6.3 RC 1, the Block Spacing control appears for the Columns block in the editor when using a classic theme, but it doesn't do anything  -- no styles are output when you change its values. 

Since it's the only block with this open when using a classic theme, and that it doesn't work, it seems like it shouldn't be visible after all. 

### Step-by-step reproduction instructions

1. Start on a test site running WP 6.3 RC 1, and using a classic theme like Twenty Twenty One.
2. Create a page, and add the Columns block.
3. Change the horizontal Block Spacing value to either one of the 1-7 values, or a fixed PX value.
4. See the gap doesn't change in the editor, or on the front-end. If you inspect the front-end, the usual styles that would be output to change the gap aren't there. 

### Screenshots, screen recording, code snippet

![columns-block 2023-07-24 16_41_17](https://github.com/WordPress/gutenberg/assets/177561/0837c58a-7927-4d2e-b40e-328cf6e363a9)

### Environment info

I can recreate this with:
- WordPress 6.3 RC 1 and the Twenty Twenty One theme, without Gutenberg.
- WordPress 6.2.2 and the Twenty Twenty One theme, with Gutenberg 16.2.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-07-25 14:30
Thanks for the report.

I was also able to reproduce this problem: _without_ the Gutenberg plugin, there was at least the following difference between WP6.2 and WP6.3 about block supports:

### WordPress 6.2.2

- Group Block: Has padding support
- Columns Block: Has padding support

### WordPress 6.3-RC1

- Group Block: Has padding, margin support
- Columns Block: Has padding, margin, block spacing support

It appears that unintended Dimensions support has been added to the Classic theme. I mark this issue as a problem that should be fixed by WordPress 6.3.

**Comment by tellthemachines** [comment] 2023-07-26 02:03
I can reproduce this in Gutenberg trunk, though the spacing control _seems_ to work in the editor, but doesn't output any value on the front end. 

I'm not entirely sure why the spacing control is visible for Columns as it isn't for other flex layout blocks (e.g. Row). We shouldn't be showing it if it's not supported (though an argument could be made for supporting it in classic themes too).

Edit: Columns has [sides defined](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/columns/block.json#L37) for its block spacing, unlike other blocks with spacing support, so the issue is probably with the presence of this array not being accounted for when determining whether to show the control in the Dimensions panel.

**Closed as completed** 2023-07-27 06:56 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Themes, [Feature] Layout
