### ISSUE TITLE
Site Logo Block: Resets to upload logo after leaving site editor and returning

### ISSUE THREAD

**Issue by geheren** [WordPress/gutenberg#29329] opened 2021-02-25 05:48 UTC
###  Description

After inserting a Site Logo block it reverts back to upload anytime I enter the site editor. However, when I click on it, then the logo appears. 

### Step-by-step reproduction instructions

1. Insert a Site Logo block.
2. Add an image if needed.
3. Update design and go through saving flow. 
4. Go to the homepage (logo is there)
5. Enter site editor, and look at Site Logo block.

### Expected behavior
The Site Logo should just appear

### Actual behavior
The block looks like the logo is missing. Here is a [screen recording](https://michaelgeheren.com/wp-content/uploads/2021/02/Site-Logo-Issue.mov). 

### WordPress information

WordPress version: 5.6.2
Gutenberg version: 10.0.2
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? Yes (TT1 Blocks 0.4.4)

### Device information

Device: Laptop
Operating system: macOS 11.3 Beta
Browser: Safari 14.1 (16611.1.14.1.2)

**Comment by geheren** [comment] 2021-02-25 05:57
Opened as part of [FSE Program Testing Call #2: Build a Homepage with Site Editing Blocks ](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/)

**Comment by ntsekouras** [comment] 2021-02-25 12:56
Hey @geheren - thanks for reporting this! 

I saw your screen recording, but couldn't reproduce this on my end. The Placeholder is shown until the image is fetched, but after that everything seemed okay to me.

**Comment by annezazu** [comment] 2021-03-12 18:59
I just tried to replicate this as well and wasn't able to do so with Gutenberg 10.1.1. I'm going to close this as a result but feel free to re-open if this happens again with future releases!

**Closed by annezazu** 2021-03-12 18:59 UTC
Labels: Needs Testing, [Block] Site Logo
