### ISSUE TITLE
Validation issues with block.json in a few core blocks

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#35902] opened 2021-10-24 14:53 UTC
## What problem does this address?

When adding the schema definition to core blocks in https://github.com/WordPress/gutenberg/pull/35900 it highlighted the following validation errors in a few core blocks.

I'm not sure if the issues are with the schema definition or invalid properties in the block.json each will need to be investigated, adding this ticket so they are not lost.

- [x] Button block - spacing - padding - horizontal - invalid value
- [x] Column block: templateLock - type missing
- [x] Cover block: templateLock - type missing
- [x] File block: viewScript - invalid property
- [x] Group block: templateLock - type missing
- [x] Navigation block: viewScript - invalid property
- [x] Post-Comment-content block - spacing - padding - horizontal - invalid value
- [x] Post-comments-form block - style - invalid type

**Comment by gziolo** [comment] 2021-10-25 08:36
It looks like changes proposed in https://github.com/WordPress/gutenberg/pull/35900 helped to find valid issues. I can confirm that `templateLock` is missing a type. @oandregal, can you help validate the reported violation for the Global Styles related support?

`viewScript` is a new property waiting to be included in WordPress 5.9 and it still needs to be documented. The work on it is being tracked in https://github.com/WordPress/gutenberg/issues/33542. We need to include it in the block schema. It is documented in the REST API endpoint for the block type:
https://github.com/WordPress/wordpress-develop/blob/2238c302f9598b6f8f4ab0c27b175fd9ca7370fd/src/wp-includes/rest-api/endpoints/class-wp-rest-block-types-controller.php#L529-L535
also in the `WP_Block_Type` class:
https://github.com/WordPress/wordpress-develop/blob/2238c302f9598b6f8f4ab0c27b175fd9ca7370fd/src/wp-includes/class-wp-block-type.php#L174-L180

Let me also highlight again my question from https://github.com/WordPress/gutenberg/pull/35843#issuecomment-949365738:

> Out of curiosity, how much work it would be to keep the schema in Gutenberg repository, possibly inside `@wordpress/blocks` package (or we could create another one with schemas to include also `theme.json`) and sync it somehow to another place that we could use instead?
> 
> I love the idea of having a schema that could be used for validation and I'd be in favor of tighter integration into the existing tooling. One immediate idea for a follow-up for this PR would be to run `block.json` validation on scaffolded test block on CI as part of:
>
> https://github.com/WordPress/gutenberg/blob/trunk/bin/test-create-block.sh

Now, that we plan to add schema to all core blocks, we could also create an integration test that would validate all `block.json` files against the schema.

**Comment by gziolo** [comment] 2021-10-25 08:46
@ryanwelcher, this could be also useful to add the `block.json` schema to the blocks present in https://github.com/WordPress/gutenberg-examples.

**Comment by ryanwelcher** [comment] 2021-10-25 12:52
> @ryanwelcher, this could be also useful to add the `block.json` schema to the blocks present in https://github.com/WordPress/gutenberg-examples

The schema property was added with https://github.com/WordPress/gutenberg-examples/pull/167 - thanks @mkaz !

**Comment by mkaz** [comment] 2021-10-25 13:01
@gziolo I like the idea of having it internal to Gutenberg repo.
What do you recommend a "@wordpress/schemas" package?

We would also want to include the theme.json schema. We can mirror any changes to the SchemaStore URL so any old URLs would still work, plus get better exposure if people look there first,. But the master version would live in Gutenberg repo.

Also, in Gutenberg it would get automatic versioning with the tags/branches of each release,
Using a URL like one could validate against whatever version they were targeting:
`https://github.com/WordPress/gutenberg/tree/wp/5.8/packages/schemas/block.json`

**Comment by gziolo** [comment] 2021-10-25 13:32
> @gziolo I like the idea of having it internal to Gutenberg repo. What do you recommend a "@wordpress/schemas" package?

That's one of the options that could help with maintenance. There are also i18n related config files for `block.json` and `theme.json` that we could move there:
https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/i18n-block.json
https://github.com/WordPress/gutenberg/blob/trunk/lib/theme-i18n.json

Unless @mkaz or @ajlende know how to annotate the translatable fields directly in the schema definition 😄

**Comment by ajlende** [comment] 2021-10-25 15:45
We could add custom fields to the schema file to indicate if the field is translatable or not. Some of the schemas in SchemaStore use a custom `markdownDescription` field ([used by VS Code](https://code.visualstudio.com/Docs/languages/json#_use-rich-formatting-in-hovers)) that isn't part of the schema spec, so I'd expect that most validators would just ignore invalid values rather than halting.

**Comment by oandregal** [comment] 2021-10-25 15:48
> Button block - spacing - padding - horizontal - invalid value

Checked this one, which was added at https://github.com/WordPress/gutenberg/pull/33859 and it appears that `horizontal` & `vertical` are proper values. Checked the PR to schemastore and [those values](https://github.com/SchemaStore/schemastore/pull/1879/files#diff-3a1f85d1b8b80851fdf09435549f98726c13cddcad9975da1497b4fc137ff23eR333) are also there. Unfamiliar with the schemastore syntax but probably we'd need to update the schema to allow the existing values (see [comment](https://github.com/SchemaStore/schemastore/pull/1879#r735743752)).

**Comment by oandregal** [comment] 2021-10-25 15:49
> Post-Comment-content block - spacing - padding - horizontal - invalid value

Same as button above.

**Comment by ajlende** [comment] 2021-10-25 16:09
- [x] Button block - spacing - padding - horizontal - invalid value
- [x] Post-Comment-content block - spacing - padding - horizontal - invalid value

Fix in https://github.com/SchemaStore/schemastore/pull/1903

**Comment by ryanwelcher** [comment] 2021-10-25 17:56
I've also got a PR to address some items being moved into `typopgraphy` - SchemaStore/schemastore#1898

**Comment by gziolo** [comment] 2021-11-02 11:44
>  Post-comments-form block - style - invalid type

We need to extend the schema to allow `string` and `string[]` for `style` and `editorStyle`. @aristath is it something we will land in WordPress 5.9 or is it the plugin for the time being?

**Comment by gziolo** [comment] 2021-11-02 11:48
- [x] Column block: templateLock - type missing
- [x] Cover block: templateLock - type missing
- [x] Group block: templateLock - type missing

Fix in https://github.com/WordPress/gutenberg/pull/36140

**Comment by aristath** [comment] 2021-11-02 11:52
> We need to extend the schema to allow `string` and `string[]` for `style` and `editorStyle`. @aristath is it something we will land in WordPress 5.9 or is it the plugin for the time being?

AFAIK this will land in 5.9 👍

**Comment by gziolo** [comment] 2021-11-03 13:14
I opened https://github.com/WordPress/gutenberg/pull/36175 to add `viewScript` in schema and docs to the Gutenberg repo.

**Comment by gziolo** [comment] 2021-11-04 07:21
> I opened #36175 to add `viewScript` in schema and docs to the Gutenberg repo.

I opened a follow-up PR https://github.com/SchemaStore/schemastore/pull/1915.

I will take care of the last item now:
>  Post-comments-form block - style - invalid type.

**Comment by gziolo** [comment] 2021-11-04 15:00
> I will take care of the last item now:
> 
> > Post-comments-form block - style - invalid type.

PR ready to review: https://github.com/WordPress/gutenberg/pull/36218. That is the last task which should conclude this issue 🎉

**Comment by walbo** [comment] 2021-11-05 16:20
> * [x]  Column block: templateLock - type missing
> * [x]  Cover block: templateLock - type missing
> * [x]  Group block: templateLock - type missing
> 
> Fix in #36140

Created an PR (#36264) to fix a regression in that PR.

**Comment by gziolo** [comment] 2021-11-08 09:23
Great catch @walbo. I see that you already relaxed the schema validation in #36267. It looks like we need to allow also an array of strings as the `type` in block attributes. Anyone knows how to code it? 😃

**Comment by walbo** [comment] 2021-11-08 09:25
Yes. I'll create a PR so type can both be a string or an array.

**Comment by gziolo** [comment] 2021-11-08 10:20
We still have some changes to sync with https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/block.json to be able to consider this issue as done.

**Comment by ajlende** [comment] 2021-11-14 16:56
With https://github.com/SchemaStore/schemastore/pull/1930 merged, the SchemaStore file should reference this one. So we don't have to worry about opening a PR for both of them anymore, and I think this can be marked as complete 🙂

**Closed as completed by ajlende** 2021-11-14 16:56 UTC
Labels: Good First Issue, [Type] Code Quality, [Package] Block library

**Comment by gziolo** [comment] 2021-11-15 06:51
@ajlende, thank you so much 🎉
