### ISSUE TITLE
Pasting Text into The Post Title Erases Existing Text

### ISSUE THREAD

**Issue by TheJeffr0** [WordPress/gutenberg#43726] opened 2022-08-30 21:06 UTC
### Description

When copying text and pasting it into the Post Title area, any existing text is erased in favor of the pasted text. I expect the text to be added to what's there, not erased. 

### Step-by-step reproduction instructions

Install and activate the Gutenberg Plugin version 13.9.0
Browse to the Add New Post page and type text into the Title Box
Copy and paste any text into the Title box

### Environment info

WordPress 6.0.2
I'm using FireFox 104.0 on a MacBook Pro
Gutenberg 13.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramseyp** [comment] 2022-08-30 21:22
I'm able to reproduce this: 

WordPress 6.0.2

No plugins active except Gutenberg 13.9.0

Screen recording attached. In this, I created a new post, typed out a title, then pasted some selected text at the cursor. Result was the entire title text was replaced. 

https://user-images.githubusercontent.com/1168839/187545510-0f9eec0f-6c76-4e9e-bd44-9d0bfae64f36.mp4

**Comment by Mamaduka** [comment] 2022-08-31 05:03
Duplicate of #43066. Fixed in #43123, it should ship in Gutenberg 14.0.

**Closed as not planned by Mamaduka** 2022-08-31 05:03 UTC
Labels: [Type] Bug, [Feature] Paste, [Status] Duplicate
