### ISSUE TITLE
Selecting Parent Block Selects Child Block in Firefox

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#42535] opened 2022-07-19 13:10 UTC
### Description

In WordPress 6.0 when using Firefox, there is a bug that makes it very difficult to select parent blocks.

When clicking the parent block (and explicitly outside a child block) the parent block is briefly selected and then the nearest child block is selected.

I have observed this behavior in the Group block, Columns block, and Media & Text block content container (clicking the image works to select the block).

### Step-by-step reproduction instructions

1. Insert a Group block
2. Give it a background color so it has some padding (in most themes, like Twenty Twenty Two)
3. Add a paragraph inside the group block with a few words
4. Click inside the group block but outside the paragraph (in the padding added by the background color)

Expected result: Group block is selected

Actual result: Group block is _briefly_ selected and then the paragraph block is selected instead

### Screenshots, screen recording, code snippet

The basic bug described in the step-by-step instructions:

https://user-images.githubusercontent.com/1238696/179756355-a1574f7d-ef53-4d5f-9d84-bd4c4458660d.mp4

Note the nearest child block selection behavior (selecting even the nearest list-item, not just the nearest list block):

![nearest-child-block-selection-bug](https://user-images.githubusercontent.com/1238696/179757897-3748b961-7fe6-4d01-9fbc-ecf9c37b9f74.gif)

### Environment info

- Windows 10 / Firefox 103
- WordPress 6.0 (and 6.0.1)
- Twenty Twenty Two
- No plugins
- No Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrwweb** [comment] 2022-07-19 13:42
It's a little harder to replicate, but I think I just experienced this in the Buttons block as well (selecting the nearest button). I appreciate the High Priority label and agree. This really degrades the user experience. It's been both annoying and directly led to multiple errors (e.g. applying background to child block rather than expected parent).

**Comment by apmatthews** [comment] 2022-07-22 17:03
I was able to reproduce this on `trunk` on macOS. It appears to only be a problem for blocks that use rich text. If I put a spacer block inside the group instead of a paragraph, the bug does not appear.

Still looking for a root cause, but [this comment](https://github.com/WordPress/gutenberg/blob/dceefb1d4ffaa07f879e6eccfb679fc91d83325c/packages/block-editor/src/components/rich-text/use-firefox-compat.js#L20-L24) sounds like it could be related.

**Comment by apmatthews** [comment] 2022-07-22 21:57
I've traced this back to [this particular invocation of `onSelectionChange`](https://github.com/WordPress/gutenberg/blob/04802c3e1edef60a6df877d1a5006486564f65da/packages/rich-text/src/component/use-input-and-selection.js#L158) that does not execute during the reproduction in Chrome, but does in Firefox. When this function executes, it causes block selection to move back to the paragraph. 

It seems Firefox manages document selection a little differently than Chrome when users click away from a rich text field. After clicking from the paragraph to the group block, Chrome gives the following output from [`document.getSelection()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getSelection):

```js
{
  anchorNode: null
  anchorOffset: 0
  baseNode: null
  baseOffset: 0
  extentNode: null
  extentOffset: 0
  focusNode: null
  focusOffset: 0
  isCollapsed: true
  rangeCount: 0
  type: "None"
}
```

Whereas Firefox gives something like:

```js
{
  anchorNode: #text "Testing the block selection"
  anchorOffset: 0
  caretBidiLevel: 0
  focusNode: #text "Testing the block selection"
  focusOffset: 0
  isCollapsed: true
  rangeCount: 1
  type: "Caret"
}
```

From what I can tell, Chrome is _clearing_ selection whereas Firefox is simply resetting it to the beginning of the paragraph's text node. This difference is what allows Chrome to skip the aforementioned `onSelectionChange` call (because of the null anchorNode and focusNodes).

Notably, the bug does not occur in the following two cases:
1. Put your cursor at the beginning of the text node before clicking to the left or top of the paragraph to select the group block.
2. Put your cursor at the end of the text node and click to the right or bottom of the paragraph to select the group block.

I don't quite understand the full context of [this block](https://github.com/WordPress/gutenberg/blob/04802c3e1edef60a6df877d1a5006486564f65da/packages/rich-text/src/component/use-input-and-selection.js#L138-L175) enough to propose a solution, but hopefully this gives someone else a head start 🙂

**Comment by sunnyt7** [comment] 2022-07-25 19:52
I've been experiencing this as well ever since 6.0 came out. It's quite frustrating, so I'm hoping there will be a fix for it soon.

**Comment by getdave** [comment] 2022-07-27 14:38
~@ellatrix as this is related to RichText are you aware of any recent changes that could have caused this?~

Looks like this occurred with 6.0 so it isn't likely to be recent. 

Nonetheless, we need to look into it.

**Comment by ellatrix** [comment] 2022-07-28 13:25
I am looking into this issue now.

**Comment by ellatrix** [comment] 2022-07-28 13:41
Found the issue. Fixed in my PR https://github.com/WordPress/gutenberg/pull/42777.

**Closed as completed** 2022-07-28 16:59 UTC
Labels: [Type] Bug, [Priority] High, Browser Issues, [Type] Regression, [Package] Rich text
