### ISSUE TITLE
'image_default_size' setting doesn't work on Gutenberg

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#15091] opened 2019-04-21 13:19 UTC
I'm Japanaese, so I'm sorry for my poor English.

The problem is 'image_default_size' setting doesn't work on Gutenberg.

I set ' image_default_size = full ' on /wp-admin/options.php, but the image set large size.

**Comment by aduth** [comment] 2019-04-22 16:58
Related: #6177, #11529

It's possible it may be a duplicate of #11529 ? It does not mention the specific option `image_default_size`, however.

**Comment by talldan** [comment] 2020-02-19 04:09
Also some discussion of this on https://github.com/WordPress/gutenberg/issues/8663

**Comment by henrikwirth** [comment] 2020-03-21 13:30
Is there any update to this? For me this is a big problem. I actually want to remove all default image_sizes and only have `thumbnail` and `full` showing with the default selection of `full`.

From what I see the `large` is hardcoded as a constant here: https://github.com/WordPress/gutenberg/blob/bee1bf91958c71c733be4514b42cfa136243b3eb/packages/block-library/src/image/constants.js#L8

I guess this comment sums up what could/should be done: https://github.com/WordPress/gutenberg/issues/8663#issuecomment-588217060

**Comment by Timoostrich** [comment] 2020-07-22 14:07
I still have this problem, too.

**Comment by laurentdebricon** [comment] 2020-12-07 09:54
i would love this fixed !

**Comment by Mamaduka** [comment] 2021-03-24 03:27
Fixed via #29966.

**Closed by Mamaduka** 2021-03-24 03:27 UTC
Labels: [Feature] Media, [Type] Bug
