### ISSUE TITLE
Documentation has broken links

### ISSUE THREAD

**Issue by jblevins1991** [WordPress/gutenberg#51656] opened 2023-06-19 13:39 UTC
### Description

There are some [README files](https://github.com/WordPress/gutenberg/blob/ce4dd6167517ed52de1a120ee4015942a7f73513/packages/components/src/panel/README.md) that have broken links to documentation. I am not sure where the link with the text of **Panel Anatomy** was suppose to go, but the page is no longer there.

### Step-by-step reproduction instructions

1. Go to [this page](https://github.com/WordPress/gutenberg/blob/ce4dd6167517ed52de1a120ee4015942a7f73513/packages/components/src/panel/README.md)
2. click on the link labeled **Panel Anatomy**
3. observe the page not load

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mburridge** [comment] 2023-08-21 10:40
> click on the link labeled Panel Anatomy

Do you mean the image under the heading 'Anatomy', i.e. `![Panel anatomy](https://make.wordpress.org/design/files/2019/03/panel-anatomy.png)`?

If so that seems to work. Can you provide more info on this issue?

**Comment by skorasaurus** [comment] 2023-12-15 20:06
I feel confident in closing this; in that the broken link was referring to the panel anatomy image which is linked at https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/panel/README.md and displays as intended at https://developer.wordpress.org/block-editor/reference-guides/components/panel/

**Closed as completed by skorasaurus** 2023-12-15 20:06 UTC
Labels: [Type] Developer Documentation
