### ISSUE TITLE
Allow header.php and footer.php fallback if header.html and footer.html parts are not used

### ISSUE THREAD

**Issue by dansdev** [WordPress/gutenberg#56114] opened 2023-11-14 11:41 UTC
This was brought up a few years back and there doesn't seem to be anything in place yet - https://github.com/WordPress/gutenberg/issues/33989

Currently in templates if you have a .php file with a higher specificity than your .html file, the .php file will take priority in rendering. E.g - if you have singular.html in your /block-templates/ dir, and a single.php in your normal directory, the single.php will take priority over the singular.html.

Integrating this same logic for header.php and footer.php files would be amazing!

**Comment by carolinan** [comment] 2024-07-30 09:01
Duplicate of #33989

**Closed as completed by carolinan** 2024-07-30 09:01 UTC
Labels: [Status] Duplicate
