### ISSUE TITLE
Autosaving feature jams-up

### ISSUE THREAD

**Issue by doughatlem** [WordPress/gutenberg#10416] opened 2018-10-08 21:41 UTC
The autosaving feature generally works very well, but apparently can get stuck in a way that is impossible to resolve. Clicking on the button did not take it out of the autosaving loop. I attempted to hit ctrl-v (cmd-v since I am working on a mac) to save what I had done, but that did not work either. 

Autosave works well enough generally that half way through composing my third post (about 2000 words) in Gutenberg, I began just letting it autosave, rarely clicking "save draft" myself. This was a mistake as it meant I lost about 90 minutes of work.

**To [attempt to] Reproduce**
I have tried, but not been able to reproduce the behaviour. I have two sub-steps at #4 that might do it, however, as both things happened or potentially happened when this occurred.
1. Go to 'New Post'
2. Give the post a title and begin typing, including hitting enter for new paragraphs as this seems to trigger the autosaving feature.
3. Watch for autosaving in the upper right panel of the post.
4a. Switch which wi-fi, hotspot, or ethernet connection you are using if possible
4b. Leave the post active, but do other work or leave the computer to go into screensaver or sleep mode for about an hour.
5. Continue with the post, watching for whether autosaving becomes stuck in a loop. 

**Expected behavior**
I expected that, as previously, the post was autosaving every 30 seconds to a minute. If there was any problem, I thought I would lose a sentence or two at most, not several carefully crafted paragraphs. I have generally liked Gutenberg but will go back to the old editor permanently if this should happen again.

**Screenshots**
One attached
![gutenburg bug](https://user-images.githubusercontent.com/43972323/46634837-4ada1b80-cb20-11e8-985a-38e98775c766.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X El Capitan
 - Browser Safari
 - Version 11.1.2

**Comment by ChemicalSailor** [comment] 2018-12-16 12:30
I also had this (or very similar) problem. It presents itself as an infinite loop of autosaving. It occurred for me after clicking the preview button. Each time I clicked the preview button I would get a javascript error in the console, a 403 error when trying to load something to do with a meta box. Sorry I can't be more specific, after I refreshed the editor it works fine.

Safari 12.0.1

**Comment by james-pierce** [comment] 2019-02-12 22:59
I have exactly this problem. Lost so much work due to this!!! Super annoying...

**Comment by frizzant** [comment] 2019-03-15 11:28
I think I got the same issue with gutenberg blocks most likely kind of bricking it. I then can't even open the post anymore, and have to reset it through the database.
I'm not sure what is causing the infinite saving loop. Also the page is basicly unviewable, and will load for 5minutes then show a load of looped weird content (gutenberg block).

I'm working with Timber, WP Gutenberg and ACF beta 3/4.

**Comment by tellthemachines** [comment] 2020-02-06 05:23
Hi @doughatlem, are you still experiencing this issue? We have since made changes to autosaving (https://github.com/WordPress/gutenberg/pull/16490) so hopefully it works better now. If you can still reproduce the issue, please add a note here and we'll try to follow up further! 

When testing, please make sure you have all other plugins disabled, and use a default theme (e.g. Twenty Nineteen or Twenty Twenty), so that we can be sure the issue isn't caused by third party code.

**Comment by noisysocks** [comment] 2020-02-20 06:01
Do you have any meta boxes enabled? If so, https://github.com/WordPress/gutenberg/issues/6966 may be related.

**Comment by youknowriad** [comment] 2020-02-27 15:26
Closing per all the autosave updates. Let's reopen if we have more details to reproduce it.

**Closed by youknowriad** 2020-02-27 15:26 UTC
Labels: Needs Testing
