### ISSUE TITLE
Preview opens and says "generating preview" forever (Cloudflare)

### ISSUE THREAD

**Issue by billhennessy** [WordPress/gutenberg#8441] opened 2018-08-03 13:34 UTC
**Describe the bug**
Preview doesn't work. About:blank page opens and says "generating preview." Forever. 

**To Reproduce**
1. Create a new post or edit an existing post.
2. Click Preview
3. In new tab, about:blank page opens with message "Generating preview."
4. Preview never appears.

**Expected behavior**
Preview appears.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.x
 - Browser Chrome, Safari
 - Version Latest

**Comment by youknowriad** [comment] 2018-08-03 13:59
Do you see any error in the console of Gutenberg when clicking this button?

**Comment by achmedislamic** [comment] 2018-08-03 22:20
[Sorry for my bad english, but I want to support Gutenberg and Wordpress]

It did happen to me too, I can't preview my post. Here is the condition.

**Bug Description**
I can't preview my post (old or new post using Gutenberg). It says "Please wait... Generating Preview". And I wait for so long and the preview won't appear.

**Steps to reproduce**
Simply, create new post or edit existing post with Gutenberg. And try to Preview it using Preview button.

**Expected behaviour**
Just like preview on Classic Editor. I expect to see my post that I create or change and the rest of my site.

**Screenshot**
![gutenberg issue](https://user-images.githubusercontent.com/25688207/43668217-39fdd176-97ae-11e8-9aa0-fa01ce88f71b.jpg)

**My device**
I'm using Windows 10 with April 2018 Update using Google Chrome latest version (V.68)

I'm really excited with Gutenberg. I hope you guys always keep up the spirit to make Gutenberg better than ever :)

**Comment by pratikthink** [comment] 2018-08-03 23:25
also happening with me some time ago
Are you using Cloudflare? I'm quite sure this is happening due to the Cloudflare. Whitelist your IP in Cloudflare Firewall.
also see #2704

**Comment by abwdvm** [comment] 2018-08-04 03:29
This also happened to my install.  It cleared up with the Cloudflare Firewall fix....  if you want to call it a fix.

**Comment by designsimply** [comment] 2018-08-04 07:39
Here is last known workaround from Cloudflare 
copied from https://github.com/WordPress/gutenberg/issues/2704#issuecomment-410090933 for reference:

> Once you have upgraded your account, you would be able to disable the firewall rule by going to your Firewall page >> selecting Web Application Firewall >> under Cloudflare Rule Set >> click on Cloudflare Wordpress >> Select the rule WP0025B >> set to Disable

> The only resolution then, with a free Cloudflare account, is to whitelist all of the IP addresses that will be using the JSON API.

And #2704 also notes that Cloudflare should have an update in place soon.

**Comment by achmedislamic** [comment] 2018-08-04 09:00
Thank you for the answer. Yes, I'm using Cloudflare. I rather to wait Cloudflare team to resolve that issue. I'm just ordinary writer of my blog and don't have experience to messed up my Cloudflare setting :( but I do really love and want Gutenberg to be default editor in the coming future.

I hope I can report any issue when I'm writing :)

**Comment by remaindeer** [comment] 2018-08-04 09:49
I hope this issue can be fixed at Cloudflare. I'm also experiencing the same bug with a free Cloudflare account and Gutenberg installed.

**Comment by swissspidy** [comment] 2018-08-04 10:46
See also #7852, #7561, and #6331, and probably many more.

This can also be caused by something else like another plugin. IIRC I had the same issue when using Polylang.

**Comment by billhennessy** [comment] 2018-08-06 14:05
Thanks! That works. The downside is that I have to repeat the process every time my IP address changes. That adds a lot of overhead to writing.

Thanks,
Bill
---
"There are two kins of people in the world: those who say to God, "thy will be done," and those to whom God says, "alright, then, have it your way." — C. S. Lewis

**Comment by designsimply** [comment] 2018-08-06 21:32
Cloudflare is working on an update and it should be fixed soon. Here is the latest note I could find on that: https://github.com/WordPress/gutenberg/issues/2704#issuecomment-410563259

**Comment by KansasEMS** [comment] 2018-08-08 17:04
I am NOT on Cloudflare and have the same issue.  Created a new post, tried to preview and got: "Please wait... Generating Preview" which does not change.  Post page says "updating failed".  However, if I display all posts, the draft I saved is there.  If I click on preview from the All Posts page, that DOES work.

When I attempt to publish it, I receive the message "publishing failed".  However, when I return to the All Posts page, the post shows as published.

**Comment by youknowriad** [comment] 2018-08-08 17:12
@KansasEMS I suspect you have a PHP error or warning messing up with the return value (JSON) of the API endpoints. You can open the network tab in your browser's console to check the response of the "autosave"/"save" XHR for instance. Hopefully the content of the response will help debug this.

**Comment by KansasEMS** [comment] 2018-08-08 17:32
I didn’t see any errors when I opened the console.  Strangely, once I published using the “classic” editor, I can now preview from within Gutenberg.  Also, even though it SAYS that updating fails, it appears that the update ACTUALLY happens.

James Kennedy
IT Manager
Kansas Board of EMS
900 SW Jackson; Suite 1031
Topeka, KS  66612-1228
Office     785.296.7296
Fax         785.296.6212
Email: James.kennedy@ks.gov<mailto:James.kennedy@ks.gov>

**Comment by youknowriad** [comment] 2018-08-08 17:38
I don't expect errors, but valid XHR response (code 200) with PHP warnings/errors making the JSON in the responses invalid. 

Here's how you see the response in Chrome

<img width="1078" alt="screen shot 2018-08-08 at 18 37 34" src="https://user-images.githubusercontent.com/272444/43854237-35a519a6-9b3a-11e8-906f-902e7ca17967.png">

**Comment by KansasEMS** [comment] 2018-08-08 17:44
I will test again later, when I have more time.

James Kennedy
IT Manager
Kansas Board of EMS
900 SW Jackson; Suite 1031
Topeka, KS  66612-1228
Office     785.296.7296
Fax         785.296.6212
Email: James.kennedy@ks.gov<mailto:James.kennedy@ks.gov>

**Comment by youknowriad** [comment] 2018-08-09 08:39
Ok, it looks like Cloudflare fixed the issue, I'm closing this issue for now. Let's see how it plays. To follow the Cloudflare discussions, this issue #2704 is probably a better one.

**Closed by youknowriad** 2018-08-09 08:39 UTC
Labels: [Status] Needs More Info

**Comment by Niresh12495** [comment] 2018-12-09 06:32
This may help somebody I had the same issue. I was able to fix it,
[Fix wordpress “Updating Failed”](https://www.guest.blog/3417/how-i-fixed-wordpress-updating-failed/)
