### ISSUE TITLE
Navigation block: remove ability in new editable list view flow after deleting a menu to add blocks to deleted menu

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46477] opened 2022-12-12 19:08 UTC
## What problem does this address?

While working on the next call for testing for the FSE Outreach Program, I noticed two problems:
- If I delete a menu, I am still presented with the option to add blocks and am able to do so and save without clarity that it won't actually save anything.
- Similar to this empty state: https://github.com/WordPress/gutenberg/issues/46202 when a menu has been deleted, the empty state is also quite strange to experience: 

https://user-images.githubusercontent.com/26996883/207132423-cc03dce1-a54c-43c2-91a5-2f736b6f9e23.mov

## What is your proposed solution?

Remove the ability to add blocks after a menu has been deleted _and_ improve the empty state for list view post deletion. Perhaps prioritize showing selecting another menu or creating a new one?

**Comment by jasmussen** [comment] 2022-12-13 09:02
Good one. I would think this is a primary opportunity to revisit the in-canvas message, which is both lacking context when part of this flow, but is also unwieldy and causing layout shifts. The canvas really isn't a good place to offer error messages like this. (See also #44778)

So one aspect could be to move this message to the inspector as a first step.

Another angle is: what is the purpose of still referencing a deleted menu? Can the act of deleting a menu also make the navigation block point to the _next_ menu in line? I.e.:

1. Site has "Header navigation 2", "Header navigation 1" menus.
2. User deletes "Header navigation 2". Navigation block now falls back to "Header navigation 1".
3. User deletes "Header navigation" menu. Navigation block now falls back to showing the Page List.

The above flow would eliminate the need to create a menu, when one already exists (which is always given the ultimate page list fallback), and it would eliminate the need for any scary error messages in the canvas or inspector. So that's the main question: can we do this? And if not, why not? It's very possible I'm missing a crucial piece, so I'd be happy to learn.

**Comment by talldan** [comment] 2022-12-13 09:33
> can we do this? And if not, why not? It's very possible I'm missing a crucial piece, so I'd be happy to learn.

I think @draganescu had reservations about doing this, but I think it is possible and probably not too difficult.

**Comment by draganescu** [comment] 2023-01-04 16:22
It is possible and not too difficult, but my main reservation is we need to be careful not to hide an error (if the menu is removed from the DB via API or via the manage menus screen we should not just pretend everything is all right).

The bug here tho should be addressed in the block to not show the off canvas editor in this instance.

**Comment by draganescu** [comment] 2023-01-30 14:24
So 1/2 of this issue has been solved in https://github.com/WordPress/gutenberg/issues/46202. The other part with the state of a broken navigation (pointing to a deleted menu) is not a bug.

**Comment by scruffian** [comment] 2023-01-30 17:17
Let's close this out then!

**Closed as completed by scruffian** 2023-01-30 17:17 UTC
Labels: Needs Design Feedback, [Block] Navigation
