### ISSUE TITLE
Sites unscrollable on mobile after 7.5.0 update

### ISSUE THREAD

**Issue by arjendejong12** [WordPress/gutenberg#20214] opened 2020-02-13 15:01 UTC
**Describe the bug**
After the latest update (7.5.0), sites viewed on mobile cannot be scrolled anymore.
The following css is responsible for this:
```css
html {
    position: fixed;
    width: 100%;
}
```
inserted by the following file: `gutenberg/build/block-editor/style.css?ver=1581605516`, which it gets from the [following](https://github.com/WordPress/gutenberg/blob/c219fed9e282a1c8467827edacf0b90303587497/packages/block-editor/src/components/editor-skeleton/style.scss#L3) `.scss` file.

The `style.css` file in version 7.4.0 doesn't contain this css.

**To reproduce**
1. Update to the latest version (7.5.0)
2. View site in mobile view or device

**Expected behavior**
Page should be scrollable.

**Comment by frankyifei** [comment] 2020-02-14 04:43
can confirm. same here

**Comment by mariohamann** [comment] 2020-02-14 07:44
I can confirm for every theme – but only if I use our individual self-created block suite. I tested Ghost Blocks, Ultimate Blocks and CoBlocks and they do work. Maybe there is a bug in our block collection. @frankyifei  @arjendejong12 @glendaviesnz   – do you have self-created blocks as well?

**Comment by arjendejong12** [comment] 2020-02-14 09:25
Yeah, I do have my own blocks created with cgb. Let's hope this gets resolved quickly! Thanks for getting deeper into this.

**Comment by ahmadawais** [comment] 2020-02-14 10:58
@mariohamann feel free to send in a PR and post about the tests you did. I'll merge that. @asharirfan can you help with this?

**Comment by youknowriad** [comment] 2020-02-14 11:06
Closing as it seems to be a CGB bug loading editor styles in the frontend.

**Closed by youknowriad** 2020-02-14 11:06 UTC
Labels: [Type] Bug, [Type] Plugin Interoperability

**Comment by ahmadawais** [comment] 2020-02-14 11:12
CGB gives you all the code you can modify it. 

This PR must have solved the issue https://github.com/ahmadawais/create-guten-block/pull/267/files

I suggest you update the cgb-scripts and your code manually

Successfully published:
 - cgb-scripts@1.23.0
 - create-guten-block@1.14.0

**Comment by jorgefilipecosta** [comment] 2020-02-14 11:14
Hi @ockham, @youknowriad PR https://github.com/WordPress/gutenberg/pull/20050 moved some styles form edit post to the block editor module that applied to the "html" element https://github.com/WordPress/gutenberg//blob/c219fed9e282a1c8467827edacf0b90303587497/packages/block-editor/src/components/editor-skeleton/style.scss#L3.

The block editor may be used in contexts we are not expecting, e.g: maybe someone uses a small block editor for comments on a website. Would it make sense to revert the change back to the edit-post module?

**Comment by youknowriad** [comment] 2020-02-14 11:20
I don't think we should revert the change. What we should/can do though, is to only apply the global style if the "EditorSkeleton"  component is mounted. (maybe by adding a className to html when it's mounted). 

Ideally we don't have to do this html styling at all but due to how scrolling work on mobile devices, it seems that it's the only solution we have for now.

**Comment by jorgefilipecosta** [comment] 2020-02-14 13:58
> I don't think we should revert the change. What we should/can do though, is to only apply the global style if the "EditorSkeleton" component is mounted. (maybe by adding a className to html when it's mounted).

That seems like a nice solution, maybe just having an effect that on mount ands a class to html if html still has no the class would be enough?

**Comment by youknowriad** [comment] 2020-02-14 16:00
yes, this should work.

**Comment by frankyifei** [comment] 2020-02-15 09:27
> I can confirm for every theme – but only if I use our individual self-created block suite. I tested Ghost Blocks, Ultimate Blocks and CoBlocks and they do work. Maybe there is a bug in our block collection. @frankyifei @arjendejong12 @glendaviesnz – do you have self-created blocks as well?
> 
> ## Edit 1
> I'm getting deeper into it. After activating our personal block suite, there are a lot of styles, that shouldn't be there. In fact our block suite has no frontend styles at all as everything is saved in our theme.
> 
> **Without block suite:**
> ![without-block-suite](https://user-images.githubusercontent.com/26542182/74512464-9a94d800-4f08-11ea-9b05-d395fe8ca4ef.png)
> 
> **With block suite:**
> ![with-block-suite](https://user-images.githubusercontent.com/26542182/74512453-94066080-4f08-11ea-9ef5-85ad605ffd8a.png)
> 
> ## Edit 2
> 1. I created a completely clean WordPress-Website.
> 2. I installed Gutenberg 7.5: Everything fine.
> 3. I created a new block with create-guten-block: It loads all backend styles AND we can't scroll because in the backend style  is fixed.
> 4. I deactivated Gutenberg 7.5: It still loads all backend styles BUT we can scroll.
>    -> **There seems to be a problem with create guten block**! It seems to load all backend styles – that's an real performance issue and now even a usability problem. @ahmadawais
> 
> ## Edit 3
> Wrote an issue in create-gutenblock project: [ahmadawais/create-guten-block#268](https://github.com/ahmadawais/create-guten-block/issues/268)

I do not have self created blocks

**Comment by mariohamann** [comment] 2020-02-15 10:31
Maybe you use a third-party block which is based on crare-guten-block?
