### ISSUE TITLE
Classnames break after style change

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#12947] opened 2018-12-17 14:25 UTC
There is a weird behavior when I apply a style on one of my block

Here are my classes before changing style:
`wp-block-advanced-gutenberg-blocks-notice wp-block-advanced-gutenberg-blocks-notice--advice`

(I use BEM notation)

After changing style: 
`wp-block-advanced-gutenberg-blocks-notice is-style-full wp-block-advanced-gutenberg-blocks-notice is-style-full--advice`

Is-style-full is injected twice, and the second time, not at the right place. I think there is somewhere a  wrong regexp 

I'm gonna switch to state naming (is-something) : I won't have the issue anymore, and it will be more WP proof. 

But I think than someone should take a look because I think it can cause issues someday.

**Comment by swissspidy** [comment] 2018-12-17 14:33
Looks like you're using https://wordpress.org/plugins/advanced-gutenberg-blocks/. Is this perhaps a bug in that plugin? Or is it happening with a custom built block? If so, could you share the code you're using to register it?

**Comment by maximebj** [comment] 2018-12-17 14:47
That's mine ;)

Bug occurs with or without this plugin. I think the issue comes from the fact than it search the classname and append .is-style-something. 

It should check if the classname is over (because in my case the second one is a modifier with a -- at the end) 

You can see the code here: https://github.com/maximebj/advanced-gutenberg-blocks/blob/master/src/blocks/notice/index.js

It's a very standard block registration.

**Comment by swissspidy** [comment] 2018-12-17 15:03
Whoops :D Sorry about that. I must have confused it with the Gutenberg Custom Fields plugin.

**Comment by swissspidy** [comment] 2018-12-17 15:06
Not sure, but this might be the code responsible for getting the active style before updating it: https://github.com/WordPress/gutenberg/blob/448d9f47abf6d78728aec14cf3acf262de6b78c1/packages/editor/src/components/block-styles/index.js#L20-L42

**Comment by youknowriad** [comment] 2019-04-22 10:23
Do you still have the issue? I tried using similar classNames in a core block and couldn't reproduce the bug.

**Comment by youknowriad** [comment] 2019-05-10 18:03
Closing. Let's reopen if we manage to reproduce again.

**Closed by youknowriad** 2019-05-10 18:03 UTC
Labels: Block API, [Status] Needs More Info
