### ISSUE TITLE
Gutenberg 4.5 Error

### ISSUE THREAD

**Issue by UniversalMovies** [WordPress/gutenberg#12140] opened 2018-11-20 23:51 UTC
Hello,
version 4.5 of Gutenberg immediately gave problems. Automatic saving blocks the form and sends it to a bug. In addition it is impossible to create new blocks or make changes to what has been written.

and more… This is another error:

L’editor ha riscontrato un errore inaspettato.

Tentativo di recupero
Copia il testo dell’articolo
Copia l’errore

**Comment by rkcrane11** [comment] 2018-11-21 01:36
This looks like it could be identical to the issue I just posted: #12143

Error details and more are posted over there

**Comment by pratikthink** [comment] 2018-11-21 04:37
I am not able to click on Title in editor after 4.5
Steps to reproduce:

1. Add new post
2. Give a title
3. Add a paragraph block
4. Click on title

WordPress 4.9.8

**Comment by pratikthink** [comment] 2018-11-21 08:46
After deactivating the Yoast plugin, everything works fine in the editor.

**Comment by gziolo** [comment] 2018-11-21 08:51
Duplicate of #12150 where we have more details.

**Closed by gziolo** 2018-11-21 08:51 UTC
