### ISSUE TITLE
Floated blocks issue

### ISSUE THREAD

**Issue by jvmediadesign** [WordPress/gutenberg#8533] opened 2018-08-04 18:39 UTC
**Bug**
Floated blocks appear above other blocks, making those blocks hard to access the content and hard to create new blocks below.  I only tested this with the base WordPress install (no other plugins active) with Twenty Seventeen.

**To Reproduce**
Just start creating blocks and the floating at the top or middle of the blocks.  

**Expected Behavior**

Size of block could be reduced if it's floated so whole container is visible/accessible. OR all blocks remain the same size, regardless of float. 

Also, it would be nice to be able to insert an image in any block and float the image around text (just like it was in classic editor). It's cumbersome to have to create image blocks for every image and then try to carefully float them around. 

**Screenshots**

![block-float-bug](https://user-images.githubusercontent.com/42098408/43679371-ea73948a-97d8-11e8-8d8d-c7600cd2d2ca.jpg)

**Desktop (please complete the following information):**

Mac OS 10.12.6)
Tested on:

- Chrome Version 67.0.3396.99

- Firefox 61.0.1 

- Safari Version 11.1.2 (12605.3.8.1)

**Comment by youknowriad** [comment] 2018-08-04 19:14
Thanks for the report, this looks like a duplicate of #7500

**Closed by youknowriad** 2018-08-04 19:14 UTC
