### ISSUE TITLE
Syntax highlighting for Edit as HTML / Text mode

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#3505] opened 2017-11-15 21:06 UTC
Now that WordPress 4.9 adds syntax highlighting to the customizr and the code editor, it would be great to have that in Gutenberg when we edit a block as HTML or in text mode.

Gutenberg version tested: 1.7

**Comment by aduth** [comment] 2017-11-15 21:17
Thanks for the feedback. Closing as duplicate of #1733.

**Closed by aduth** 2017-11-15 21:17 UTC
