### ISSUE TITLE
Stop Offering "Block Recovery" for HTML Blocks

### ISSUE THREAD

**Issue by TheSimArchitect** [WordPress/gutenberg#30468] opened 2021-04-02 10:22 UTC
## Description

Post or page with HTML Block. You save, you open again, there's a nagging message saying there's something wrong and a big blue button offering block recovery, even though it's an HTML block without issues. Can't edit the block or see it's content until you click the three dots and "convert the block to HTML" again.

## WordPress information
- WordPress version:  Latest
- Gutenberg version:  Latest
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by priethor** [comment] 2021-04-02 15:01
Hi @TheSimArchitect ! Thanks for reporting.

Could you please provide an HTML snippet that triggers the Block Recovery message, as I can't seem to reproduce it? Thanks!

**Comment by TheSimArchitect** [comment] 2021-04-02 15:14
Sure! Thanks for replying quickly!

```
<table style="margin: -4px auto 0 auto; min-width: 600px; width: 100%; border-style: none;">
  <tr style="border-style: none;">
    <th><h3>[s2Member-PayPal-Button details redacted /]</h3><h3 style="margin: -14px auto 0 auto;">$ 5.99 / Month</h3><h5 style="font-style: italic; margin-top: 0px;">($6.99 on 1<sup>st</sup> Month)</h5></th>
    <th style="vertical-align: bottom;"><h3 style="margin: 0 auto; text-align: center"><a target="_blank" href="https://www.patreon.com/bePatron?u=30189497" rel="noopener noreferrer"><img alt="Patreon" src="https://thesimarchitect.com/wp-content/uploads/2020/11/Patreon-Button-360x102-1.jpg" style="width: 180px;" /></a></h3><h3 style="margin-top: 4px;">$ 7 / Month</h3><h5 style="font-style: italic; margin-top: -16px;">(+Lab for $ 12 / Month)</h5></th>
    <th><h3>[s2Member-PayPal-Button details redacted /]</h3><h3 style="margin: -14px auto 0 auto;">$ 4.99 / Month</h3><h5 style="font-style: italic; margin-top: 0px;">(Yearly Plan)</h5></th>
  </tr>
</table>
```

**Comment by ntsekouras** [comment] 2021-04-05 14:51
It seems that the specific snippet above get invalidated by missing `tbody`, which is not required there. So it's a bug related to `Table` block. 

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody

**Comment by TheSimArchitect** [comment] 2021-04-05 15:29
> It seems that the specific snippet above get invalidated by missing `tbody`, which is not required there. So it's a bug related to `Table` block.
> 
> Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody

Thanks! Yes, like you mention, html tables don't require that, plus it's an HTML block, not a table block. I encoded the entire HTML and I set it up as an HTML block. I'd like for Wordpress to not mess it up if possible, even if I choose a specific way to code that's not "perfect".

If the block was already set as HTML, it makes no sense for Gutenberg to try to recover anything or convert to html. Gutenberg should just ignore it and treat it as a custom HTML block and just parse it 😉

**Comment by talldan** [comment] 2022-01-27 03:46
This doesn't seem related to the table block, more with the HTML block and the way it validates HTML. It's just a coincidence that the example html contains a table, but it happens with any invalid markup (the provided HTML is invalid due to the `h3` elements inside a `th` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th).

This seems very similar to https://github.com/WordPress/gutenberg/issues/10889.

**Comment by TheSimArchitect** [comment] 2022-01-27 05:30
> This doesn't seem related to the table block, more with the HTML block and the way it validates HTML. It's just a coincidence that the example html contains a table, but it happens with any invalid markup (the provided HTML is invalid due to the `h3` elements inside a `th` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th).
> 
> This seems very similar to #10889.

Thanks. I'll look into it, but I'd like to be able to have an option to turn that feature off for a specific block (or in general), so wordpress doesn't try to validate the same block again and let us have our "bad code" alone 😉

**Comment by codebymikey** [comment] 2022-02-21 17:24
I agree that not all clients might have the capability to create custom blocks, so providing the flexibility to provide a custom "wrapping" (yet technically invalid HTML) is a very viable usecase for certain editors.

Is this something that should be feasible to implement with the current API/the way Gutenberg/React currently works?

**Comment by TheSimArchitect** [comment] 2022-02-21 21:25
> I agree that not all clients might have the capability to create custom blocks, so providing the flexibility to provide a custom "wrapping" (yet technically invalid HTML) is a very viable usecase for certain editors.
> 
> Is this something that should be feasible to implement with the current API/the way Gutenberg/React currently works?

This would be awesome! Custom HTML is Custom HTML. We should be able to write whatever we want in those blocks without Wordpress nagging about it.

If we make certain mistakes on those blocks they still break our pages, so having that nuisance isn't helpful at all.

**Comment by Mamaduka** [comment] 2022-09-27 12:23
I am closing this as a duplicate of #10889.

Thanks for commenting on the original issue @TheSimArchitect!

**Closed as not planned by Mamaduka** 2022-09-27 12:23 UTC
Labels: [Type] Bug, [Block] HTML
