### ISSUE TITLE
Backspace to empty first block makes block uneditable

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#9126] opened 2018-08-18 11:02 UTC
When I empty the contents of a paragraph block using backspace, then the block becomes unusable. I have to delete the block entirely to be able to edit content again.

**To Reproduce**
1. Create a new post
2. Enter some content
3. Press backspace a bunch of times until everything has gone, then once more for luck
4. The block has gone, selecting it and typing does nothing.

**Expected behavior**
I expect to be able to empty the contents of the block and then be left with an empty block that I can continue writing in.

**Screenshots**

![gutenbug](https://user-images.githubusercontent.com/1004130/44298611-3b87e000-a2de-11e8-9ddb-61f676f1c531.gif)

**Setup:**
 - OS: MacOS 10.13.6
 - Browser Chrome 68
 - Gutenberg 3.6.2

**Comment by BinaryMoon** [comment] 2018-08-18 11:15
Note that I have had this happen in other positions as well. It doesn't have to be the first block in a document.

**Comment by kjellr** [comment] 2018-08-20 18:57
I just tested using the same OS, Browser, and Gutenberg version, but was unable to reproduce. 

@BinaryMoon, are you seeing this all the time, or just under some circumstances? Also, does your site have any other plugins activated?

**Comment by BinaryMoon** [comment] 2018-08-20 19:35
I see it every time I write an article - 4 or 5 times on each article.

There are plugins on my site but none that (intentionally) interact with Gutenberg.

This is on my live site - https://www.binarymoon.co.uk

**Comment by BinaryMoon** [comment] 2018-10-04 21:45
Turns out this was happening because of an editor style that was hiding empty paragraphs.

My editor styles are generated with SASS and reuse styles from the theme (to avoid duplication and work). I have now removed the p:empty { display:none; } and the bug no longer happens.

**Comment by designsimply** [comment] 2018-11-06 00:01
🎉 closing based on the latest comment saying the bug no longer happens. 

Thanks for the explanation about the editor style interference @BinaryMoon!

**Closed by designsimply** 2018-11-06 00:01 UTC
Labels: Blocks, [Type] Bug
