### ISSUE TITLE
Snap! Chrome crashes

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#9248] opened 2018-08-22 15:07 UTC
**Describe the bug**
While edtiting a post with Gutenberg, every 20 minutes or so, the page will crash. thankfully it autosaves or this would be aweful!

**To Reproduce**

Start writing a long post for like 20 minutes... lol, it takes dedication to get this bug. but when your actually writing a long post this seems to happen to me a lot.

**Screenshots**
<img width="1107" alt="screenshot 2018-08-22 11 03 25" src="https://user-images.githubusercontent.com/11615474/44472028-45218880-a5fb-11e8-9455-46797baf8493.png">

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser: Chrome
 - Version 68

Im not sure what more to say as I have no clue other than maybe some javascript error or a caching error?
Maybe a chrome extension is in the way? I do have Grammarly installed?

**Comment by tofumatt** [comment] 2018-08-22 15:10
I've definitely had Chrome open for longer without a crash–I'm guessing it's more to do with the content over the length of time.

If you click "Learn More" does Chrome give you any extra debugging info? Do you have any Browser plugins or WordPress plugins installed that might affect behaviour? I haven't seen this happen before.

**Comment by saltnpixels** [comment] 2018-08-22 15:22
This is where the learn more goes:
https://support.google.com/chrome/answer/95669?visit_id=636705471359176574-1366698415&p=e_awsnap&rd=1

I can try disabling stuff in the browser. I also notice the typing comes in slow. I can type fast and it doesn't show up right away.

**Comment by saltnpixels** [comment] 2018-08-22 15:35
I got to this:
<img width="1563" alt="screenshot 2018-08-22 11 35 04" src="https://user-images.githubusercontent.com/11615474/44473944-7a2fda00-a5ff-11e8-9079-53aa9fd6dbe2.png">

**Comment by ianbelanger79** [comment] 2018-08-22 15:51
Hi @saltnpixels,

I have had a Gutenberg post open for hours while writing and never encountered this issue. I am on a Windows 10 machine, using the latest Chrome version (68.0.3440.106). Have tested it on a local install and a "live" install, both using trunk and very few, if any plugins other than Gutenberg.

I would suggest deactivating any other plugins and browser extensions, as suggested by @tofumatt. Could you please report back if you figure out which plugin or browser ext. is causing the issue. Thanks

**Comment by saltnpixels** [comment] 2018-08-22 16:30
I think it might be yoast. I uninstalled and so far I am not crashing...

**Comment by tofumatt** [comment] 2018-08-22 16:34
Ah, thanks for the update. I'll close this issue for now as we can't reproduce and it sounds like it could be Yoast. It's definitely worth filing an issue with them with as many steps to reproduce as possible: https://github.com/Yoast/wordpress-seo/issues

Feel free to reference this issue by URL in the new issue if you think it's useful 👍

**Closed by tofumatt** 2018-08-22 16:34 UTC
Labels: [Status] Needs More Info
