### ISSUE TITLE
Images showing as Thumbnail size when added to image block - possible plugin conflict

### ISSUE THREAD

**Issue by abrightclearweb** [WordPress/gutenberg#8734] opened 2018-08-08 21:39 UTC
**Describe the bug**

An image added to an Image block has the wrong Image Size in Block Settings. It shows as Thumbnail instead of Full. 
When the image size is changed in the dropdown, the image changes size in the Gutenberg editor but when the post is published all images are full size.

Related issue: https://github.com/WordPress/gutenberg/issues/8663

Setup: WordPress 4.9.8
Theme: Twenty Sixteen

Active Plugins: 
- Classic Editor
- Gutenberg 3.4
- Duplicate Post
- Jetpack - connected to WordPress.com with Photon, Tiled Galleries, Portfolio & Testimonial content types activated
- ManageWP - Worker
- WordPress Importer
- WPMU DEV Dashboard

Theme Unit Test Data imported.

**To Reproduce**
Insert an image and change the size of it to Thumbnail or another size. Publish the post.

**Expected behavior**
Image Size should be Full on addition to an image block in the Block settings.

**Screenshots**

![full size image](https://user-images.githubusercontent.com/7430856/43865485-a8217734-9b5a-11e8-8ee6-3847ade638d5.png)

![medium image](https://user-images.githubusercontent.com/7430856/43865495-acda5e08-9b5a-11e8-9e8b-17fcca0a5bfd.png)

![thumbnail image](https://user-images.githubusercontent.com/7430856/43865514-b636dc4c-9b5a-11e8-9576-0e9823038da7.png)

![jetpack images](https://user-images.githubusercontent.com/7430856/43865190-be82c24a-9b59-11e8-9801-a601c7a6457f.png)

![inspected code](https://user-images.githubusercontent.com/7430856/43865726-3f61a1e6-9b5b-11e8-9cc3-27f9da35cb2d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Firefox Quantum
 - Version 61.0.1 (64-bit)

**Comment by youknowriad** [comment] 2018-08-08 22:14
Should we close one of these two issues #8663? Seems like the same thing to me.

**Comment by nosilver4u** [comment] 2018-11-09 01:55
I think #8663 is the same, but not as well described, because the behavior is tricky to pin down. I was noticing this issue also, where the Image Size field showed Thumbnail, but the image in the editor was very clearly not the thumbnail. When I saved, it was the Full version of the image.
That was a few days ago, and then today I tried it again, and the same thing happened. But then I disabled EWWW IO, and the problem went away.
In particular, I've discovered that the ExactDN parser does something which causes this behavior. The common denominator with the original report is the JetPack plugin, as their Photon option was the base upon which ExactDN is built.
The problem is related to the image_downsize filter, which is normally suppressed (in both Photon and ExactDN) by a call to is_admin(), but Gutenberg doesn't use admin-ajax, it uses the REST API, which doesn't send any signals about being in wp-admin.

So, it appears there are two issues:
1. Photon and ExactDN should pre-empt the parsing of image_downsize for the REST API when it is detected that the request is made from the editor.
2. Gutenberg shouldn't choke if it gets urls that have been parsed by ExactDN or Photon. The REST API response is identical in structure, the only difference I can see is in the urls themselves.

I've already implemented a fix in EWWW IO for ExactDN, I'll be pinging the JetPack team about Photon, but in the meantime this remains as a bug, since there could be other plugins that trigger it. And you can reproduce it simply by enabling Jetpack with Photon and then inserting an image to the editor.

**Comment by jeherve** [comment] 2018-11-09 07:32
> I'll be pinging the JetPack team about Photon

Thanks a lot for the warning! We'll be taking a look at this here:
https://github.com/Automattic/jetpack/issues/10580

**Comment by youknowriad** [comment] 2019-04-03 10:42
I'm closing as this seems fixed upstream.

**Closed by youknowriad** 2019-04-03 10:42 UTC
Labels: Media, Needs Testing, [Type] Bug
