### ISSUE TITLE
Link color in post content cannot be over-ridden with global styles

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#53534] opened 2023-08-10 14:52 UTC
### Description

When the Twenty Twenty-Three theme is activated and you try to change the link color in global styles the color of links does not change in the post content, though they do change in other parts of the template, e.g. footer, comments form, etc...

Interestingly changing the link hover color does work okay.

### Step-by-step reproduction instructions

1. Make Twenty Twenty-Three your active theme
2. Create a post with links in the post content
3. Go to global styles -> colors
4. Change the link color
<img width="274" alt="Screenshot 2023-08-10 at 15 44 45" src="https://github.com/WordPress/gutenberg/assets/20643925/3b0a6ec8-b634-4d18-8785-c5fc16d5689a">

5. View the page in the front end
6. Verify that links still use the Secondary color - #345C00 (though hover color defined in global styles works okay)

### Environment info

WP 6.3
Chrome Version 114.0.5735.106
macOS Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-08-11 13:47
Thanks for the report.

I think the problem is because Twenty Twenty Three applies text color to the link in the post content block via theme.json.

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentythree/theme.json#L329

In the global style, You should be able to override this style by changing the link color in the post content block.

**Comment by t-hamano** [comment] 2023-08-11 16:32
> In the global style, You should be able to override this style by changing the link color in the post content block.

There was insufficient explanation on this point. Color support for te Post Content block was added in #51326. This will be available in Gutenberg 16.5.

**Comment by mburridge** [comment] 2023-08-11 16:35
Thanks @t-hamano , I couldn't change the link color from the post content block. Thanks for the explanation.

**Comment by t-hamano** [comment] 2023-08-12 08:24
I believe this issue has been resolved and would like to close it, but if I have missed something, please comment.

**Closed as not planned by t-hamano** 2023-08-12 08:24 UTC
Labels: [Feature] Themes, Global Styles, [Block] Post Content
