### ISSUE TITLE
Blank page when editing custom post type

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#12148] opened 2018-11-21 03:15 UTC
**Describe the bug**
CPT edit screen is no longer working. 
White screen (not of death). 
ACF is completely broken. 
You can no longer edit a field group.

**To Reproduce**
1. Install Gutenberg 4.5.
2. Install ACF (any version).
3. Navigate to the "Custom Fields > Add New" page .
4. Notice the lack of anything.

**Expected behavior**
ACF CPT should appear as expected with the classic editor edit page.

**Screenshots**
![screen shot 2018-11-21 at 2 11 14 pm](https://user-images.githubusercontent.com/2296425/48816818-c8d44800-ed97-11e8-8f69-af1a41b3be4f.png)

**Additional context**
- This was not an issue with Gutenberg version 4.4

**Comment by andremacola** [comment] 2018-11-21 03:49
If you have the Classic Editor installed, you can use the dropdown menu and all works fine. But this is not the correct solution.

![captura de tela 2018-11-21 as 00 48 53](https://user-images.githubusercontent.com/3408809/48817879-3c8a3c80-ed27-11e8-98d5-c1ad1ed253f9.png)

**Comment by pento** [comment] 2018-11-21 03:53
Thank you for the bug report, @elliotcondon!

I can reproduce this same bug, it seems to be a regression caused by #12000.

**Comment by pento** [comment] 2018-11-21 04:04
Ah, I see. It's because adding `user_can_richedit()` to the `gutenberg_can_edit_post`/`gutenberg_can_edit_post_type` filters will cause them to always return `true` if the current user has rich editing enabled. This will override the other checks that a CPT can work with the block editor.

I suspect that #12000 was the wrong approach here: rather than falling back to classic when rich editing is disabled, we should still load the block editor, but default to the code editor view, or perhaps a HTML block.

The fix for this should also include e2e tests confirming that CPTs that don't work in the block editor won't try to load it.

**Comment by thmarx** [comment] 2018-11-21 07:48
I run into the same problem. Until it is fixed and released, I use this workaround:
`add_filter('user_can_richedit', "disable_richedit", 10, 1);`
`public function disable_richedit($is_enabled) {

	if (get_post_type() === "my_post_type") {

		return false; 

	}

	return $is_enabled;
}
`

**Comment by anantajitjg** [comment] 2018-11-21 08:08
Same issue for me...I hope it will be fixed soon....

**Closed** 2018-11-21 08:16 UTC
Labels: Priority High, Regression, [Type] Bug

**Comment by merc28** [comment] 2018-12-13 15:30
I tried just deactivating my TinyMCE Advanced editor but it didn't help. So I assume this is a gantry 5 or an issue with my isotope rocket theme

**Comment by BramPeerlings** [comment] 2019-01-27 13:07
Related; #12442

**Comment by merc28** [comment] 2019-01-28 17:40
I found on the WordPress support forums that they have a quick fix: a script that restores the classic editor which then fixes this bug.

**Comment by alexnl** [comment] 2020-02-06 00:40
I had this same issue. The following in `register_post_type` will fix the issue:
`show_in_rest => false`
This uses the classic editor for the post type as opposed to Gutenberg.
I realize this is not ideal and does not "fix" the issue. Commenting it here in case someone needs it working temporarily while the issue is debugged.
