### ISSUE TITLE
More block doesn't work after being saved as a reusable block

### ISSUE THREAD

**Issue by caimin-j** [WordPress/gutenberg#14618] opened 2019-03-25 12:18 UTC
**Describe the bug**
The More block doesn't work after being saved as a reusable block.

**To Reproduce**

1. Add two Paragraph blocks with one More block between them.
2. Customize the more text and save the block as a reusable block.
3. Publish the post.
4. Notice how the resuable version of the block is ignored on the live page.

**Expected behavior**
That the resuable block would function in the same way as the default version.

**Screenshots**

With the standard more block:

<img width="385" alt="Screenshot 2019-03-25 at 12 11 58" src="https://user-images.githubusercontent.com/37620825/54918888-47342880-4ef7-11e9-837f-af545b6810c5.png">

With a more block that's been saved as reusable block (the reusable block is between the two paragraph blocks.:

<img width="361" alt="Screenshot 2019-03-25 at 12 13 50" src="https://user-images.githubusercontent.com/37620825/54919173-025cc180-4ef8-11e9-89e0-920cec33b8c7.png">

**Comment by aduth** [comment] 2019-05-31 20:02
Closing as duplicate of #8633. @caimin-j In my testing there, I was unable to reproduce in the latest version of Gutenberg. Are you able to reproduce this in the plugin? Could you report there if you are with additional information about your theme?

**Comment by aduth** [comment] 2019-05-31 20:02
Duplicate of #8633.

**Closed by aduth** 2019-05-31 20:02 UTC
Labels: Needs Testing, [Block] More, [Component] Reusable Blocks
