### ISSUE TITLE
aligning the latest comment block merges another block

### ISSUE THREAD

**Issue by Jackie6** [WordPress/gutenberg#14695] opened 2019-03-29 02:39 UTC
**Describe the bug**
When you right align the latest comment block, then it overlapped with the block below.

![g78dYlUMgk](https://user-images.githubusercontent.com/24849874/55205602-f435cc00-51a9-11e9-91cb-8f69bc95e30d.gif)
![image](https://user-images.githubusercontent.com/24849874/55205616-fe57ca80-51a9-11e9-8127-a13fb54feb27.png)

**To Reproduce**
1. Create a paragraph block with some text and background color
2. Insert the latest comment block before the paragraph block
3. Right align the latest comment block

**Desktop:**
 - OS: Mac OS
 - Browse: chrome
 - Version: latest master

**Comment by ashwin-pc** [comment] 2019-04-17 23:30
@Jackie6 This doesn't seem to be a bug as it seems that all blocks with this property work this way. (e.g. the images block also works this way). The issue final version however does not look pretty and probably being able to set the width in some way could be a solution to this.

**Comment by liloo2040** [comment] 2019-04-24 13:42
Hi! I agree with you ashwin-pc.

It's not a bug.

@Jackie6, if you want it to align the way you want, I think you have to work on your own css stylesheet, if you have your theme. I did exactly what you said to do.

Just work with a `float:right` on your comment block + the width and it should be working. 

I hope it helps you!

**Comment by youknowriad** [comment] 2019-11-18 10:52
Closing as works as intended.

**Closed by youknowriad** 2019-11-18 10:52 UTC
Labels: Good First Issue, Needs Dev, [Block] Latest Comments, [Type] Bug
