### ISSUE TITLE
The editor has encountered an unexpected error

### ISSUE THREAD

**Issue by HolbyOnline** [WordPress/gutenberg#32307] opened 2021-05-28 09:27 UTC
## Description
 When I go to add a new post I am greeted with an error saying "The editor has encountered an unexpected error" When I deactivate Gutenberg I am reverted to the Classic Editor (which I do not like) and the editor works fine, but when I deactivate the Classic Editor to use Gutenberg I get the message above, so something is wrong.

## Step-by-step reproduction instructions
Not sure as I believe this is only happening on my website

## Expected behaviour
 I expect for the gutenberg editor to work and allow me to add posts.

## Actual behaviour
 Greeted with an error message saying the editor has encountered an unexpected error.

## Code snippet (optional)
TypeError: Cannot read property 'setOpenState' of null
    at render (https://holbyonline.com/wp-content/plugins/full-site-editing/wpcom-block-editor-nux/dist/wpcom-block-editor-nux.js?ver=a31f2374725b217b853837e5e5b1763b:6:15560)
    at we (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at zj (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:226:496)
    at Th (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    at tj (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    at Te (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    at https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
    at Da (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:280)
    at Pg (https://holbyonline.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:14)

## WordPress information
- WordPress version:  5.7.2
- Gutenberg version:  10.7.1
- Are all plugins except Gutenberg deactivated?  No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Chrome Version 90.0.4430.212

**Comment by KGrand78** [comment] 2021-05-29 14:04
I have the same issue. I can't post or edit my posts with Gutenberg enabled. Do something and assign this to someone! I will open my own ticket if necessary.
![Screen Shot 2021-05-29 at 10 03 52 AM](https://user-images.githubusercontent.com/85025289/120073172-3f3b1a80-c065-11eb-8b83-75125d4f648a.png)

**Comment by stokesman** [comment] 2021-05-29 16:13
This looks to be a duplicate of #32236 which was closed as not applicable. The recommendation is to report this to wordpress.com support: https://wordpress.com/support/.

**Comment by paaljoachim** [comment] 2021-08-22 11:06
Environment:
WordPress 5.8.
None default theme.
Various plugins activated.
Chrome

When the [SEO Framework plugin](https://wordpress.org/plugins/autodescription/)  is activated along with Gutenberg 11.3.0 
I also get the "The editor has encountered an unexpected error"

I posted on the SEO Framework plugin forum the following (comment is held for moderation on the support forum):

Hey

I noticed today when logging into a customer site and clicking to start a new blog entry that this message showed up:

The editor has encountered an unexpected error. (buttons) Attempt Recovery – Copy Post Text – Copy Error

I copied the error:
```
TypeError: Cannot read property 'indexOf' of undefined
    at u (https://religionskritikk.no/wp-content/plugins/autodescription/lib/js/pt-gb.min.js?ver=4.1.4:1:755)
    at Object.initSelectors (https://religionskritikk.no/wp-content/plugins/autodescription/lib/js/pt-gb.min.js?ver=4.1.4:1:3146)
    at Object.render (https://religionskritikk.no/wp-content/plugins/autodescription/lib/js/pt-gb.min.js?ver=4.1.4:1:3259)
    at Te (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:119:308)
    at Ch (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:119:105)
    at Pj (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:233:139)
    at di (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:305)
    at Nj (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:236)
    at sc (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:96)
    at gf (https://religionskritikk.no/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:109)
```

The reason why I am posting in this forum is that I deactivated a bunch of plugins and when reactivating The SEO Framework plugin also reactivated the error.

Clicking Attempt Recovery just leads to a blank white Gutenberg editor screen.

Chrome Console errors I see this:
```
react-dom.min.edd8b7a6.js:141 TypeError: Cannot read property 'indexOf' of undefined
    at u (pt-gb.min.js?ver=4.1.4:1)
    at Object.initSelectors (pt-gb.min.js?ver=4.1.4:1)
    at Object.render (pt-gb.min.js?ver=4.1.4:1)
    at Te (react-dom.min.edd8b7a6.js:119)
    at Ch (react-dom.min.edd8b7a6.js:119)
    at Pj (react-dom.min.edd8b7a6.js:233)
    at di (react-dom.min.edd8b7a6.js:168)
    at Nj (react-dom.min.edd8b7a6.js:168)
    at sc (react-dom.min.edd8b7a6.js:168)
    at gf (react-dom.min.edd8b7a6.js:162)
Ye @ react-dom.min.edd8b7a6.js:141
```

I deactivated the latest Gutenberg plugin version 11.3.0 and the error went away.

I rolled back with WP Rollback plugin to Gutenberg plugin version 11.2.1. Activated and noticed no error while the SEO Framework plugin was still active.

@Cybr

Btw
I came across this article related to the bug: https://thomas.vanhoutte.be/miniblog/wordpress-fix-the-editor-has-encountered-an-unexpected-error/

**Comment by paaljoachim** [comment] 2021-08-22 19:49
I heard back from Sybre Waaijer in this thread:
https://wordpress.org/support/topic/the-editor-has-encountered-an-unexpected-error-46/#post-14793573

He mentioned these things:

> Automattic reached out to us as they learned about this issue a few weeks ago, but I couldn’t verify/test this until Gutenberg 11.3.0 landed for semantical reasons.
> 
> I believe they made an oversight with property removal. We read the terms property, which has since been removed from the component, something they shouldn’t have done.
> 
> Moreover, Gutenberg is now blocking the “Primary Term” selection feature of TSF because we seemingly cannot read category-selection-state changes. I also believe this to be an oversight; but, if we cannot find a workaround soon, I might have to turn off that feature until we can.
> 
> Please mind that Gutenberg is marked as beta-software, although it’s not as explicit about it as it could be, it still shouldn’t be used on production websites.

EDIT: 26 Aug.
Sybre the author of the SEO framework has updated the plugin.

**Comment by sybrew** [comment] 2021-08-26 14:42
This issue is about a scripting conflict with https://wordpress.org/plugins/full-site-editing/.

Because WordPress has been updated since, and both plugins Gutenberg and Full Site Editing have also received updates, I consider this issue outdated, and I think it would be best to close it.

TSF had an unrelated conflict with another part of Gutenberg 11.3.0, albeit with the same outcome: An unrecoverable error.

**Comment by paaljoachim** [comment] 2021-08-28 11:14
@mcsf @mkaz Perhaps you could take a look at this issue?

**Comment by mkaz** [comment] 2021-08-30 17:14
@paaljoachim What's the current issue? From the update on Aug 26 it sounds like the SEO framework plugin has been updated which I assume mean it all works. Also from @sybrew comment it sounds like this issue outdated.

**Comment by paaljoachim** [comment] 2021-08-31 12:29
Ok. I am going to close this  issue. Do please reopen if I  am mistaken.

**Closed as completed by paaljoachim** 2021-08-31 12:29 UTC
Labels: [Status] Duplicate
