### ISSUE TITLE
Paragraph block drop card disappears when editing the text

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#30722] opened 2021-04-12 08:28 UTC
This issue was originally reported by @benvaassen

## Description
Paragraph block drop card disappears when editing the text.

## Step-by-step reproduction instructions
1. Create a new page / post
2. Add a paragraph block and some text inside
3. Enable the **Drop cap** option in the block options panel.
4. Start editing the content of the paragraph block

## Expected behaviour
The letter in cap should not return to normal state.

## Actual behaviour
When editing the paragraph, letter in cap returns to normal state.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/33403964/114364003-e117ae00-9b70-11eb-9339-ba725d447cee.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?Yes

## Device information
- Device: MacBook Pro
- Operating system: macOS 11.3
- Browser: Firefox Developer Edition 88.0b9 (64 bits)

**Comment by annezazu** [comment] 2021-04-16 16:40
As explained originally here https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph/style.scss#L18 and referenced in this previous issue https://github.com/WordPress/gutenberg/issues/12172 this is intended behavior! Closing this out as a result.

**Closed as completed by annezazu** 2021-04-16 16:40 UTC
Labels: [Type] Bug, [Block] Paragraph
