### ISSUE TITLE
In Japanese environment, only two characters are displayed for the block name that appears when using select mode

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#21060] opened 2020-03-21 08:45 UTC
In a Japanese environment, the component button that appears when using select mode displays only two characters.

**To reproduce**
1. Set the language setting to Japanese.
2. Use selection mode.
3. Select any block.
4. Then, the block name is displayed only for 2 characters.

**Expected behavior**
It should look like the following image.

<img width="400" alt="wp54_expected" src="https://user-images.githubusercontent.com/31400297/77222958-7f6a5780-6b9b-11ea-8deb-fa7ef6348a34.png">

**Screenshots**
However, it now looks like the following image.

<img width="600" alt="wp54_error" src="https://user-images.githubusercontent.com/31400297/77222964-8b561980-6b9b-11ea-982d-6676ea267541.png">

**Solution**
When "white-space: nowrap;" was applied to the component button (.edit-post-visual-editor .components-button), it became horizontal even in Japanese.

<img width="400" alt="dev_tool" src="https://user-images.githubusercontent.com/31400297/77222986-ab85d880-6b9b-11ea-969a-0e0ae004f4cf.png">

**Verification environment**
- Mac OS
- Google Chrome
- WordPress 5.4-RC3-47477

**Comment by ddryo** [comment] 2020-03-21 08:49
The same problem occurs with the Replace button of the image block.

<img width="335" alt="wp54_replace_img_btn" src="https://user-images.githubusercontent.com/31400297/77223031-41216800-6b9c-11ea-907d-e87fad5b207c.png">

**Comment by waviaei** [comment] 2020-03-22 08:23
This is not Japanese environment issue, because I can recreate it with site's language setting set to:

Korean
<img width="573" alt="スクリーンショット 2020-03-21 21 54 37" src="https://user-images.githubusercontent.com/1564991/77245411-be62e080-6c61-11ea-9ef4-c3d44750d380.png">

Chinese
<img width="545" alt="スクリーンショット 2020-03-21 21 57 50" src="https://user-images.githubusercontent.com/1564991/77245417-c3c02b00-6c61-11ea-90dc-9b8b616bdecd.png">

and English (US)
<img width="594" alt="スクリーンショット 2020-03-22 17 20 34" src="https://user-images.githubusercontent.com/1564991/77245419-cb7fcf80-6c61-11ea-8ebc-0d1ec731171e.png">

**Comment by aduth** [comment] 2020-03-23 20:33
Thanks for reporting this issue. If you are able to, could you test to see if this is still an issue in newer versions of the Gutenberg plugin? Was it working correctly in versions of WordPress earlier than the 5.4 release candidates (WordPress 5.3.2)? 

There is a significant redesign to this user interface in newer versions of the plugin (#19344) and this issue may have been affected as part of those changes.

I haven't yet debugged to confirm, but I'd wonder if this is in-part caused by a hard-coded width in the styling of these buttons.

**Comment by ddryo** [comment] 2020-03-24 05:36
In the latest version of Gutenberg it was displayed without problems!

<img width="284" alt="スクリーンショット 2020-03-24 14 35 17" src="https://user-images.githubusercontent.com/31400297/77391740-d0b55980-6ddc-11ea-8a65-3e4e01e9b4f4.png">

**Comment by ddryo** [comment] 2020-03-24 05:37
However, we will be using 5.4 for a while, so if you can fix the bug, please do.

**Comment by skorasaurus** [comment] 2021-06-08 13:40
Hi, 

I'm closing this since you have reported that this has been fixed in the latest version of Gutenberg. Please reopen if  you are still experiencing this.

**Closed by skorasaurus** 2021-06-08 13:40 UTC
Labels: [Feature] Blocks, [Type] Bug
