### ISSUE TITLE
Rich Text: Caret should be positioned outside inline boundary on code pattern

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#12597] opened 2018-12-04 19:34 UTC
**Steps to Reproduce:**

1. Navigate to Posts > Add New
2. Insert a new paragraph block
3. Type: \`hello\`

**Expected Result:**

Upon entering the terminating \` tick, it should be inferred that the formatted region is completed and that I can continue typing text as unformatted.

**Actual Result:**

The caret stays placed within the code region. Continued typing will be formatted as code, requiring the user to ArrowRight to escape the formatted region.

**Comment by designsimply** [comment] 2018-12-04 23:43
Tested and confirmed that the caret lands _inside_ the inline boundary when typing a terminating backtick.

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.6.1 `master` @ `46f789a5c` using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by iseulde** [comment] 2018-12-05 07:51
Duplicate of #11276.

**Closed by iseulde** 2018-12-05 07:51 UTC
Labels: Writing Flow, [Component] Rich Text, [Type] Enhancement
