### ISSUE TITLE
Prototypes: Requirements

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#190] opened 2017-03-06 20:08 UTC
All technical prototypes need to accomplish the following:

- Use [post-content.js](https://github.com/WordPress/gutenberg/blob/master/shared/post-content.js) data.
- Infer blocks from content structure.
- Should follow design of UI prototype and [mockups for blocks](https://github.com/WordPress/gutenberg/issues/198).
- Have “selected”, “writing”, and “hover” states.
- - Selected state shows all controls.
- - Writing state fades out UI.
- - Hover state shows block outline and move-arrows.
- Moving a block should select the block.
- Moving a block should scroll the window to focus on the block.
- Implement block type switcher that works for text/heading/quote.
- Implement block level attributes for text, image, and quote.
- Implement insert-block menu toggled by the (+).
- Any new line outside of blocks should show the (+) and if you start writing should default to text block.
- Insert-block menu should allow to insert any of the post-content blocks.
- When a block is at the top or bottom and they cannot be moved further, the corresponding arrow should be grayed out.
- Integrate basic API for defining a block markup and inferring block data from it.

## Text
- Should support alignment options at block level.
- Should support TinyMCE formatting.
- Enter creates new text block.

## Heading
- Should show band with different headings.

## Image
- All alignment needs to work (floated and full-bleed).
- Implement caption and handle markup variations.
- Caption field should appear only when block is selected.

## Quote
- Needs to support two styles.
- Should support cite attribute that is edited in place.
- Cite field should appear only when block is selected.
- It should not be possible to mess the cite or quote markup in visual mode.

**Comment by annaephox** [comment] 2017-03-07 06:23
@mtias should we add "Design" label to this issue? Thx

**Comment by jasmussen** [comment] 2017-03-07 07:43
> should we add "Design" label to this issue? Thx

Since all the prototypes should look virtually the same, it's probably best to keep the discussion on the visuals on the individual tickets for the design.

**Comment by mtias** [comment] 2017-03-07 10:42
Yes, this is a list of requirements for the technical prototypes to have a comparable set of features. If there are things here that we don't yet have in the UI Prototype we should make mockups for them separately.

**Comment by iseulde** [comment] 2017-03-07 11:33
Sounds good, I'll work on this for single.

> Enter should do single line break; double enter should create new text block.

Are we settled on this? Has there been any discussion? Could someone describe the behaviour a bit better? Should other blocks still create a new paragraph (e.g. heading)?

**Comment by mtias** [comment] 2017-03-07 11:37
Good question. Not settled, but we need to pick one behaviour now to have a comparable experience. I'd be ok with punting this and having a simpler "enter creates new text block". Does that sound more reasonable?

**Comment by jasmussen** [comment] 2017-03-07 11:41
> Are we settled on this? Has there been any discussion? Could someone describe the behaviour a bit better? Should other blocks still create a new paragraph (e.g. heading)?

Not settled. But we also haven't really tried it yet, given it a fair shake. So feels worth trying. And if it's a bit-flip in TinyMCE, seems worth a shot, with the goal being to make informed decisions.

**Comment by jasmussen** [comment] 2017-03-07 13:55
See also https://github.com/WordPress/gutenberg/issues/198 for mockups for every base block.

**Comment by mtias** [comment] 2017-03-07 14:43
Adding them to the description.

**Comment by iseulde** [comment] 2017-03-08 14:08
Single MCE tracking comment:

- [ ] Use [post-content.js](https://github.com/WordPress/gutenberg/blob/master/shared/post-content.js) data.
- [ ] Infer blocks from content structure.
- [ ] Should follow design of UI prototype and [mockups for blocks](https://github.com/WordPress/gutenberg/issues/198).
- [ ] Have “selected”, “writing”, and “hover” states.
  - [x] Selected state shows all controls.
  - [x] Writing state fades out UI.
  - [ ] Hover state shows block outline and move-arrows.
- [ ] Moving a block should select the block.
- [x] Moving a block should scroll the window to focus on the block.
- [ ] Implement block type switcher that works for text/heading/quote.
- [ ] Implement block level attributes for text, image, and quote.
- [ ] Implement insert-block menu toggled by the (+).
- [x] Any new line outside of blocks should show the (+) and if you start writing should default to text block.
- [ ] Insert-block menu should allow to insert any of the post-content blocks.
- [ ] When a block is at the top or bottom and they cannot be moved further, the corresponding arrow should be grayed out.
- [ ] Integrate basic API for defining a block markup and inferring block data from it.

## Text
- [x] Should support alignment options at block level.
- [x] Should support TinyMCE formatting.
- [ ] Enter should do single line break; double enter should create new text block.

## Heading
- [x] Should show band with different headings.

## Image
- [x] All alignment needs to work (floated and full-bleed).
- [x] Implement caption and handle markup variations.

## Quote
- [ ] Needs to support two styles.
- [ ] Should support cite attribute that is edited in place.
- [ ] It should not be possible to mess the cite or quote markup in visual mode.

**Comment by iseulde** [comment] 2017-03-08 14:09
If anyone likes to work on these, let me know, just so we're not working on the same. Trying to get the inserter in today.

**Comment by youknowriad** [comment] 2017-03-08 14:25
Multi-Instance MCE tracking comment:

- [x] Use [post-content.js](https://github.com/WordPress/gutenberg/blob/master/shared/post-content.js) data.
- [x] Infer blocks from content structure.
- [x] Should follow design of UI prototype and [mockups for blocks](https://github.com/WordPress/gutenberg/issues/198). (Not perfect)
- [ ] Have “selected”, “writing”, and “hover” states.
  - [x] Selected state shows all controls.
  - [x] Writing state fades out UI.
  - [ ] Hover state shows block outline and move-arrows.
- [ ] Moving a block should select the block.
- [x] Moving a block should scroll the window to focus on the block.
- [x ] Implement block type switcher that works for text/heading/quote.
- [x] Implement block level attributes for text, image, and quote.
- [x] Implement insert-block menu toggled by the (+).
- [x] Any new line outside of blocks should show the (+) and if you start writing should default to text block.
- [x] Insert-block menu should allow to insert any of the post-content blocks.
- [ ] When a block is at the top or bottom and they cannot be moved further, the corresponding arrow should be grayed out.
- [x] Integrate basic API for defining a block markup and inferring block data from it.

## Text
- [x] Should support alignment options at block level.
- [x] Should support TinyMCE formatting.
- [ ] Enter should do single line break; double enter should create new text block.

## Heading
- [x] Should show band with different headings.

## Image
- [x] All alignment needs to work (floated and full-bleed).
- [x] Implement caption and handle markup variations.

## Quote
- [] Needs to support two styles.
- [x ] Should support cite attribute that is edited in place.
- [x] It should not be possible to mess the cite or quote markup in visual mode.

**Comment by aduth** [comment] 2017-03-09 18:36
What of #179 should we integrate into the requirements here? Many of these text interactions will be important to preserve.

cc @azaozz

**Comment by intronic** [comment] 2017-03-12 23:06
@iseulde - fyi we are working today on:
- making drag&drop work with hover
- 'Moving a block should select the block.'

**Comment by mimo84** [comment] 2017-03-13 04:11
@iseulde: @intronic  and me have just opened a new PR #249 which provides

- Hover shows the outlines 
- Hovered blocks can now be dragged and dropped.

**Comment by youknowriad** [comment] 2017-03-13 09:02
I checked all the requirements for the "Multi" prototype. I'm sure I've missed some use-cases or introduced some regressions. Please let me know if you notice something missing.

**Comment by jasmussen** [comment] 2017-03-14 09:52
> I checked all the requirements for the "Multi" prototype. I'm sure I've missed some use-cases or introduced some regressions. Please let me know if you notice something missing.

Looks _amazing_. Very very good work 👏👏👏

There are some little things UI wise, but nothing critical for evaluating the prototype at all. I'll see if I can take a stab at them, but as it stands this prototype works excellently, in fact better than I'd expected it to!

**Comment by azaozz** [comment] 2017-03-14 21:17
> What of #179 should we integrate into the requirements here? Many of these text interactions will be important to preserve.

Ideally, all of them. I realize most of these behaviors are not used commonly. Personally I use only 2-3 on a regular basis. However the so called "power users" will probably use many. Also all of them are important for accessibility, some even critical. They are at approximately the same "level of importance" as using Cmd+C and Cmd+V for copy/paste.

There is a very easy way to test :) Unplug your mouse (literally) and try to create some content in few different editors, including both prototypes and the current editor.

**Comment by jasmussen** [comment] 2017-05-10 09:27
Closing this one as it seems no longer relevant.

**Closed by jasmussen** 2017-05-10 09:27 UTC
Labels: Task, Technical Prototype
