### ISSUE TITLE
Issue with the closing of the posts that created in Classic Editor

### ISSUE THREAD

**Issue by georgefyro** [WordPress/gutenberg#8475] opened 2018-08-03 23:21 UTC
If you open with Gutenberg a post that you have created in the past to the Classic Editor of Wordpress then you can't close the post, the window, nothing. You must restart the pc to close it.

**Comment by ngygen323** [comment] 2018-08-04 08:40
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by designsimply** [comment] 2018-08-04 09:03
Noting I deleted a comment which was saying the same thing over and over many times per minute in various locations. Spamming and unacceptable behavior towards anyone, or this community, will not be allowed. If you want to give feedback, please do it without spamming or personal attacks.

My apologies for those who were effected during this. Please know we have a zero tolerance policy over this type of behavior.

**Comment by designsimply** [comment] 2018-08-04 09:13
@georgefyro I tested Gutenberg with Internet Explorer 11 on Windows 7 and I was able to open posts I created in the past with the classic editor using Gutenberg without any problems. 

May I ask what OS and browser versions you are using?

Do you see any errors in your browser's Developer Tools console or Network info?

Do you have anything in your web server error logs which may help pin down steps to reproduce the problem?

**Comment by georgefyro** [comment] 2018-08-04 16:46
Dear Sheri,

I tested it on firefox and there isn't problem. The problem appears on
Google Ghrome.

I can't close an old post or leave a page if I open it with gutenberg.

I use Google Chrome on Windows 10.

Best Regards,
George

**Comment by youknowriad** [comment] 2018-11-27 10:11
I'm going to close this issue as we can't reproduce it. Let's reopen if we find ways to reproduce consistently.

**Closed by youknowriad** 2018-11-27 10:11 UTC
Labels: [Type] Help Request
