### ISSUE TITLE
Collapsed margins is breaking the reusable blocks border

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#9730] opened 2018-09-10 08:10 UTC
Use two sequential reusable blocks in a post and notice that their borders are not spaced properly. It's probably a regression of the margin-collapsing PR 

<img width="680" alt="screen shot 2018-09-10 at 09 08 04" src="https://user-images.githubusercontent.com/272444/45284796-4c8cd100-b4d9-11e8-816c-a56d53fa1a7d.png">

cc @jasmussen

**Comment by jasmussen** [comment] 2018-09-10 09:28
Are there any additional steps? I can't reproduce:

<img width="781" alt="screen shot 2018-09-10 at 11 26 47" src="https://user-images.githubusercontent.com/1204802/45289022-697ecf80-b4ec-11e8-91d2-6d6642911de0.png">

Note that although collapsing margins could definitely cause this, until such a time as we decide to move forward with #8350, that PR should not have affected margins. Yes, it enabled margin collapsing, but it also compensated for those collapsing margins to ensure there wasn't any visual change. "Why then?" you might ask? Well because now we _can_ allow margins to collapse on a per-block basis, which is a useful tool for themers who want their editor styles to look as closely as possible to the end result.

**Comment by youknowriad** [comment] 2018-09-10 10:05
I guess it more surfaced in #9732

I thought it was a generic error happening for every reusable block but it only happens for reusable blocks with InnerBlocks usage (columns or multi-selection)

**Comment by jasmussen** [comment] 2018-09-10 10:15
I found out why this is. We apply negative margins to any block that contains a `editor-block-list__layout` element inside. I think we did this for columns, but I'll be tracking this down.

**Comment by jasmussen** [comment] 2018-09-10 10:39
Pushed a fix. That will fix it for #9732 as well, but good to have separate for now.

**Closed** 2018-09-10 12:28 UTC
Labels: [Type] Bug
