### ISSUE TITLE
"_edit_last" meta value doesn't appear to be saved at all with Gutenberg

### ISSUE THREAD

**Issue by samulimartikainen** [WordPress/gutenberg#36485] opened 2021-11-15 10:50 UTC
### Description

Saving in Gutenberg block editor does not seem to set the "_edit_last" to post meta values.
Tried using classic editor and "_edit_last" was set correctly, so is the problem REST API related?

Issue noticed when tried to show (in front end) the name of the user who made last revision but `get_the_modified_author()` function returns NULL. Also `get_post_meta($post_id)` function showed "_edit_last" value isn't set.

### Step-by-step reproduction instructions

1. Edit post/page
2. Update changes
2. "_edit_last" meta value doesn't seem to appear

### Environment info

- Latest WordPress version, Latest Gutenberg which comes with latest WP

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-08-09 15:07
Thanks for contributing, @samulimartikainen.

It looks like a duplicate of #31501, and the fix should be applied in WP Core. See this comment for more details: https://github.com/WordPress/gutenberg/issues/31501#issuecomment-891562483.

**Closed as completed by Mamaduka** 2022-08-09 15:07 UTC
Labels: [Type] WP Core Ticket
