### ISSUE TITLE
Too many notifications shown when resetting customisations

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#49165] opened 2023-03-17 16:28 UTC
### Description

When using the site editor to reset customisations to a few templates and template parts in a row:

1. immediately opening one will result in one top notification and one snackbar per reset template or template part
2. there is a site updated snackbar that shows up just because I clicked manage templates
3. there are stacked entity reverted notifications as well

### Step-by-step reproduction instructions

1. In a block theme
2. Make modifications to three templates and one template part
3. Using the site editor go to manage all templates and manage all template parts
4. Reset each of the customized one
5. Open a template
6. Notice the notification Armageddon

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/107534/225963347-21f0f971-19a0-4308-a325-b17c9d9e67fb.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-03-17 17:30
This is a duplicate of https://github.com/WordPress/gutenberg/issues/46901 from my point of view. Mind closing out and deferring to the original?

**Comment by draganescu** [comment] 2023-03-17 17:49
It's not a duplicate. This describes the problem of accumulating notifications about actions that a user does in one part of the UI and showing them all at once in an unrelated part of the UI. https://github.com/WordPress/gutenberg/issues/46901 is about sequential actions producing one notification per action, which can be stacked or debounced. So no, don't close :)

**Comment by annezazu** [comment] 2023-03-18 03:31
What do you see as the solution? In my mind, that aligns nicely with the currently open issue. The outcome feels the same to me (how best to display notifications) but perhaps I'm missing some nuance :D Will leave open either way but let's look at both at the same time.

**Comment by jasmussen** [comment] 2023-03-20 07:20
I think I discussed with @scruffian or @apeatling about reducing the time those snackbars stay on screen. Right now they linker for a long time.

**Comment by apeatling** [comment] 2023-03-20 16:55
Yes, there was a PR to reduce the time on screen here, that came along with some concerns. Happy to revisit that: https://github.com/WordPress/gutenberg/pull/47199

I also opened a spin off that repositioned the snackbars. It's stalled currently on moving them to canvas only and out of the site editor chrome: https://github.com/WordPress/gutenberg/pull/47298

**Comment by draganescu** [comment] 2023-03-21 09:55
We should also clean up notifications when the context changes!

**Comment by jasmussen** [comment] 2023-05-04 15:27
In addition to reducing the snackbar time (it seems even a small reduction would help), it seems like we could also make a heuristic of showing no more than 3 or 4 at any one time, any more than that and the older ones disappear. Could perhaps even be 2 or 3. The way they work, they already steal focus away from the previous one, so for announcement purposes and to keep things from being too loud, there's really little incentive to keep the older ones around. 

Can even just have one timeout for the latest snackbar, and a very reduced timeout for older ones.

**Comment by glendaviesnz** [comment] 2023-05-15 04:06
Fixed by https://github.com/WordPress/gutenberg/pull/50302

**Closed as completed by glendaviesnz** 2023-05-15 04:06 UTC
Labels: [Type] Bug, General Interface, [Feature] Site Editor

**Comment by glendaviesnz** [comment] 2023-05-15 04:17
Although this fixed the mulitple notices appearing, they still reappear in some circumstances when moving between modes - [another issue for this here.](https://github.com/WordPress/gutenberg/issues/50624)
