### ISSUE TITLE
Gutenberg Keeps hanging when trying to edit old posts!

### ISSUE THREAD

**Issue by Dark-Cod3r** [WordPress/gutenberg#23146] opened 2020-06-14 22:06 UTC
**Describe the bug**
When try to editing old post, it just keep hanging. A single letter editing takes up to 1 min. Don't you think its too much. Check the video below and you will see, after 30 to 40 sec it apply changes. Seriously... -_-
And before you say that my system is crap or old (instead of accepting that gutenberg is literal garbage), i have attached SS of my system specs. 
![System Spec](https://user-images.githubusercontent.com/6500557/84605388-37b34d80-aeb6-11ea-86fb-8a68e134b071.png)

**To reproduce**
1. Go to 'any of your old post which has been created using older gutenberg version'
2. Try to editing a word, sentence or whatever you like.
3. It just hangs up for like 30 sec

**Expected behavior**
Gutenberg suppose to be smooth but clearly it is not. I mean what this gutenberg is exactly(i cant edit properly, i cant work properly, lags everywhere). To me, it seems like a laggy garbage plugin to annoy users.?!

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [gutenberg plugin]
- If the Gutenberg plugin is installed, which version is it? [8.3.0]

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Edge]
 - Version [Version 85.0.538.0 (Official build) dev (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 6 Pro]
 - OS: [Android 9.0]
 - Browser [Chrome Beta]
 - Version [84]

**Additional context**
Either remove gutenberg garabage completely, or just stop working on it and improve classic editor. Seems like their is no way gutenberg is going to be smooth, lag free anytime soon. I hope some random experienced dev (clearly current gutenberg team is useless and don't know any thing about user experience) will make a new classic editor so we can ditch this gutenberg garbage forever. 

*Check Below Video
 **_https://streamable.com/4vypr0_**

**Comment by annezazu** [comment] 2020-06-22 22:49
@Dark-Cod3r Hey there. Thanks for this thorough report and for taking the time to flag this. To better help get to the bottom of this, I'd appreciate if we can get more information about your site:

- What theme are you using? 
- What other plugins are you using on your site? 
- Do you know even roughly what version of Gutenberg you were using for this post originally?

From what I can see in your video, you're definitely using some additional plugins on top of Gutenberg (as expected). By chance, are you open to testing what happens if just the gutenberg plugin is enabled? 

For now, I'll make this as needs testing so we can try to get more information about what might be going on. 

> I hope some random experienced dev (clearly current gutenberg team is useless and don't know any thing about user experience) will make a new classic editor so we can ditch this gutenberg garbage forever.

Please review and [keep in mind our code of conduct](https://github.com/WordPress/gutenberg/blob/master/CODE_OF_CONDUCT.md) when you're filing issues here. I understand you're frustrated but there are very real people on the other side of this feedback just as there are people like you using the software that's created. We're better if we work kindly together offering goodwill and patience. The experience you're having is very much not what those working on Gutenberg want you to have :)

**Comment by nerrad** [comment] 2020-06-23 08:34
Hi there!

I definitely understand how this degradation of performance could be frustrating. This sounds fairly similar to [this issue reported for the CoBlocks plugin](https://wordpress.org/support/topic/latest-update-slows-down-wp-com-block-editor/). By any chance did you recently update CoBlocks to 2.0? If so, that is more than likely the cause in your case and you could try installing CoBlocks 2.0.1 to see if that fixes.

**Comment by Dark-Cod3r** [comment] 2020-06-23 14:44
> @Dark-Cod3r Hey there. Thanks for this thorough report and for taking the time to flag this. To better help get to the bottom of this, I'd appreciate if we can get more information about your site:
> 
> * What theme are you using?
> * What other plugins are you using on your site?
> * Do you know even roughly what version of Gutenberg you were using for this post originally?
> 
> From what I can see in your video, you're definitely using some additional plugins on top of Gutenberg (as expected). By chance, are you open to testing what happens if just the gutenberg plugin is enabled?
> 
> For now, I'll make this as needs testing so we can try to get more information about what might be going on.
> 
> > I hope some random experienced dev (clearly current gutenberg team is useless and don't know any thing about user experience) will make a new classic editor so we can ditch this gutenberg garbage forever.
> 
> Please review and [keep in mind our code of conduct](https://github.com/WordPress/gutenberg/blob/master/CODE_OF_CONDUCT.md) when you're filing issues here. I understand you're frustrated but there are very real people on the other side of this feedback just as there are people like you using the software that's created. We're better if we work kindly together offering goodwill and patience. The experience you're having is very much not what those working on Gutenberg want you to have :)

1: Only one theme i am using since the day i have created this website, Theme Name: SoleDad Magzine theme
2: Check screenshot for full list of plugins which i am using. (Screenshot: https://i.ibb.co/421fw4Z/Plugins.jpg)
3: it was version 8.1 i guess.

As for the last paragraph (Code of conduct). I understand but still, why would create something this horrible and unfinished product. Yes it is volunteer work but at least honor other users and devs opinion too who trying to contribute by making free plugins. Only i am seeing is some 4,5 people voted for gutenberg development and it started. if you look around, its not just me but a lot of devs are bashing gutenberg (which i am pretty sure you are well aware and now i can see why it is the most hated wordpress project ).

**Comment by Dark-Cod3r** [comment] 2020-06-23 14:47
> Hi there @Dark-Cod3r!
> 
> I definitely understand how this degradation of performance could be frustrating. This sounds fairly similar to [this issue reported for the CoBlocks plugin](https://wordpress.org/support/topic/latest-update-slows-down-wp-com-block-editor/). By any chance did you recently update CoBlocks to 2.0? If so, that is more than likely the cause in your case and you could try installing CoBlocks 2.0.1 to see if that fixes.

Hi. Thank You for your reply.
I have never used coblocks plugin.

**Comment by annezazu** [comment] 2020-06-25 05:11
@Dark-Cod3r Thanks for the screenshot of your plugins! That's super helpful. [Because your theme appears to be a paid theme](https://themeforest.net/item/soledad-multiconcept-blogmagazine-wp-theme/12945398),  I can't rule out a theme conflict since I can't test this personally. Using a test site of mine, I wasn't able to replicate the problem you're having with posts I wrote from 8.1's release.

With that said, based on your screenshot of plugins, I imagine this is likely a plugin conflict of some sort. I see you have All in One plugin installed. Can you try following these instructions to [export your site to a staging environment](https://theme-fusion.com/documentation/avada/how-to/how-to-migrate-your-website-with-all-in-one-wp-migration/#export)? [WP Staging ](https://wordpress.org/plugins/wp-staging/)might work well too. Once your site is duplicated and you have a staging environment, can you try deactivating your other plugins other than Gutenberg and seeing if you have the same problem? If you don't, please then re-enable each plugin one at a time until you find the culprit and reach out to that plugin author. If you can replicate, please try using a different theme. Either way, let us know how this goes. I know this is a big ask to make - it's the best way to confirm the problem though. Thanks for being up to digging in here thus far. I understand if this is too much to ask going forward. 

> As for the last paragraph (Code of conduct). I understand but still, why would create something this horrible and unfinished product. Yes it is volunteer work but at least honor other users and devs opinion too who trying to contribute by making free plugins. Only i am seeing is some 4,5 people voted for gutenberg development and it started. if you look around, its not just me but a lot of devs are bashing gutenberg (which i am pretty sure you are well aware and now i can see why it is the most hated wordpress project ).

WordPress and the web as a whole is unfinished. That's personally my favorite aspect of it. No one is trying to build something horrible though - quite the opposite actually. Saying unncessary unkind things to the people actively trying to make what you want better only slows them down. Critical feedback including bug reports and frustation points are always welcome though (I file them often). Just remember that we're all wanting this to be a better experience - you want your site to work, I want to help get to the bottom of the issue, and the devs want to build a product that doesn't result in these problems in the first place. Assuming positive intent on all parties goes a long way.

**Comment by Dark-Cod3r** [comment] 2020-06-25 13:26
> @Dark-Cod3r Thanks for the screenshot of your plugins! That's super helpful. [Because your theme appears to be a paid theme](https://themeforest.net/item/soledad-multiconcept-blogmagazine-wp-theme/12945398), I can't rule out a theme conflict since I can't test this personally. Using a test site of mine, I wasn't able to replicate the problem you're having with posts I wrote from 8.1's release.
> 
> With that said, based on your screenshot of plugins, I imagine this is likely a plugin conflict of some sort. I see you have All in One plugin installed. Can you try following these instructions to [export your site to a staging environment](https://theme-fusion.com/documentation/avada/how-to/how-to-migrate-your-website-with-all-in-one-wp-migration/#export)? [WP Staging ](https://wordpress.org/plugins/wp-staging/)might work well too. Once your site is duplicated and you have a staging environment, can you try deactivating your other plugins other than Gutenberg and seeing if you have the same problem? If you don't, please then re-enable each plugin one at a time until you find the culprit and reach out to that plugin author. If you can replicate, please try using a different theme. Either way, let us know how this goes. I know this is a big ask to make - it's the best way to confirm the problem though. Thanks for being up to digging in here thus far. I understand if this is too much to ask going forward.
> 
> > As for the last paragraph (Code of conduct). I understand but still, why would create something this horrible and unfinished product. Yes it is volunteer work but at least honor other users and devs opinion too who trying to contribute by making free plugins. Only i am seeing is some 4,5 people voted for gutenberg development and it started. if you look around, its not just me but a lot of devs are bashing gutenberg (which i am pretty sure you are well aware and now i can see why it is the most hated wordpress project ).
> 
> WordPress and the web as a whole is unfinished. That's personally my favorite aspect of it. No one is trying to build something horrible though - quite the opposite actually. Saying unncessary unkind things to the people actively trying to make what you want better only slows them down. Critical feedback including bug reports and frustation points are always welcome though (I file them often). Just remember that we're all wanting this to be a better experience - you want your site to work, I want to help get to the bottom of the issue, and the devs want to build a product that doesn't result in these problems in the first place. Assuming positive intent on all parties goes a long way.

First of all, their are many ways to figure out that lag issue more efficiently. For example adding debug support, or adding some kind event listening support (or using browser event listener) will help much better to figure out what exactly causing this lag. Trying to reproduce on other system is not enough, a lot of other factors needs to be considered (for example, maybe your system is much faster than mine, so that lag means nothing to your PC hence smooth experience for you). 
Now, i am 100 % sure problem is related to Gutenberg. I disabled all plugins, enabled only gutenberg related plugins. Then disabled one by one and still same lag. But today i noticed i got an gutenberg update. I updated gutenberg, re-enabled all plugins and noticed lag kinda reduced (but not disappeared completely even after disabling all other plugins), and guess what, another stupid bug got introduced in new version. I mean seriously, what kind of testers gutenberg has, it is a pretty common bug and i am sure a lot of users has reported it by now .. Seeing this bug, i'm pretty sure gutenberg team is not even interested in its development. 
Anyway, about the new bug, when you scroll blocks in search box, it covers the search area making impossible to search blocks. (BTW, it took me less than 5-min to notice that bug, so please don't say this time that team is trying hard to fix bugs, i have seen much better open source developers than gutenberg, team not even testing its basic features to make sure it is bug free).  
Check this video.
https://streamable.com/e2vjfh

**Comment by nerrad** [comment] 2020-06-25 17:57
Hi @Dark-Cod3r,

Please stop making assumptions about the motivations of people contributing to the Gutenberg project. Phrases like this are **unacceptable**:

> Seeing this bug, i'm pretty sure gutenberg team is not even interested in its development.

and 

> i have seen much better open source developers than gutenberg, team not even testing its basic features to make sure it is bug free).

This dismisses the effort of and attributes malicious intent to the hundreds of contributors to the project who not only develop for it, but also test it, suggest features, write blog posts about it, write documentation, participate in weekly meetings, do bug triages, and numerous other ways that people are involved in the project.

We _are_ always open to receiving and investigating bug reports that are discovered and reported by folks like yourself, but as with _any_ software, occasionally there may be bugs or issues that pop up in certain environments that don’t surface broadly and are not picked up immediately. Rest assured that when problems _are discovered and reproducible_ effort is made to squash those bugs.

Please focus your reports on the issues you are experiencing and leave out your guesses and assumptions about the motivation and skill of folks contributing to the project.

Thanks.

**Comment by youknowriad** [comment] 2020-09-15 10:07
I'm going to close this as a duplicate of #22822 

Unfortunately, we are not able to reproduce such issues. If you have additional information add them to the issue there.

**Closed by youknowriad** 2020-09-15 10:07 UTC
Labels: [Status] Needs More Info, [Type] Performance
