### ISSUE TITLE
FSE: Single Link color is inadequate

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#39841] opened 2022-03-29 08:42 UTC
### Description

Only being able to select a single colour for Links is inadequate. There needs to be options so that `hover`, `active`, and `visited` colours can be set also.

![fse-link-color](https://user-images.githubusercontent.com/2078245/160569914-faa57639-4245-47c7-bcd4-a1795213b272.png)

### Step-by-step reproduction instructions

Use Twenty Twenty-Two theme
Enter Editor (Appearance > Editor)
Select Page template from Templates menu option
Open Styles Sidebar
Select Colors and then Links options
View options for only setting a single link color

### Environment info

macOS Monterey 12.2.1
Firefox 98.0.1
WP 5.9.2
Twenty Twenty-Two
Core only, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment] 2022-03-30 15:22
Hey @maddisondesigns Anthony

Here is an issue by @kjellr Kjell
**Consider a standardized way to modify hover/focus/active states for blocks**
https://github.com/WordPress/gutenberg/issues/27075

There are a few different issues that are related.

As your issue is related to Global Styles.
@jorgefilipecosta

**Comment by mtias** [comment] 2022-05-23 10:15
Closing as duplicate of #27075.

**Closed as not planned by mtias** 2022-05-23 10:15 UTC
Labels: [Type] Enhancement, Global Styles
