### ISSUE TITLE
Site Editor: block toolbar covers blocks that are close to top of header template

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#31008] opened 2021-04-20 15:49 UTC
## Description

In the site editor, when editing the header, any blocks that are close to the top of the template are obscured by the toolbar.
This is very apparent when removing the spacer block in the header of TT1-Blocks theme.
When the toolbar obscures the block it is almost impossible to edit that particular block.
Not all themes will contain a 70px spacer as the first block in the header, so making editing such things as site-title/tagline/navigation almost impossible.

## Step-by-step reproduction instructions

1. With TT1-Blocks theme, go to Site Editor
2. Select the header template part
3. Remove the 70px spacer block at the top of the header
4. Notice how you cannot edit the blocks that are now appearing at the top of the header, because they become obscured by the toolbar when selecting the block

## Expected behaviour

All blocks should be editable and not obscured.

## Actual behaviour

Blocks close to the top of the header are obscured and uneditable.

## Screenshots or screen recording (optional)

![gutenberg-header-editing-01](https://user-images.githubusercontent.com/76742815/115426103-1f0f7480-a1f8-11eb-9a46-621f35ef8288.jpg)
![gutenberg-header-editing-02](https://user-images.githubusercontent.com/76742815/115426134-26368280-a1f8-11eb-8a24-76cbda0638db.jpg)
![gutenberg-header-editing-03](https://user-images.githubusercontent.com/76742815/115426146-2a62a000-a1f8-11eb-945a-81d7fca9a47a.jpg)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by skorasaurus** [comment] 2021-04-30 18:30
similar problem at https://github.com/WordPress/gutenberg/issues/26239

**Comment by ellatrix** [comment] 2021-05-21 06:48
I wonder if some gray padding like the template editor would be beneficial here. It would also ensure there's always some clickable area to clear selection. Cc @jasmussen

**Comment by jasmussen** [comment] 2021-05-21 06:59
Is this a duplicate of https://github.com/WordPress/gutenberg/issues/29464? In that I also suggest that instead of adding padding, we can move the toolbar below the block. That lets us reserve the padding for indicating template editing, and it also takes up less space.

**Comment by ellatrix** [comment] 2021-05-21 07:04
Yes, this is a duplicate of #31008.

**Closed as completed by ellatrix** 2021-05-21 07:04 UTC
Labels: [Type] Bug
