### ISSUE TITLE
Disappearing navigation when adding subpages

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#32828] opened 2021-06-18 18:52 UTC
## Description
Adding subpages to a navigation block inside a group, while editing in the site editor, pushes up the navigation until it's not seen.

This is how I started:
<img width="519" alt="Screen Shot 2021-06-18 at 1 51 02 PM" src="https://user-images.githubusercontent.com/46652/122604905-4e95fe00-d03c-11eb-9f51-7e888dcd204a.png">

This is what I ended up with:
<img width="796" alt="Screen Shot 2021-06-18 at 1 51 26 PM" src="https://user-images.githubusercontent.com/46652/122604924-55247580-d03c-11eb-8d21-409f11dcdb80.png">

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No... Blockbase

## Device information
- Device: Desktop
- Operating system: macOS 11.4
- Browser: Safari  14.1.1

**Comment by jasmussen** [comment] 2021-06-22 05:56
Thank you for the report! I can confirm a few issues:

1. Menu items are white:

<img width="707" alt="Screenshot 2021-06-22 at 07 49 39" src="https://user-images.githubusercontent.com/1204802/122870865-82b83a00-d32e-11eb-8c0d-b4458893fd5a.png">

That appears to be due to a blockbase theme style:

<img width="551" alt="Screenshot 2021-06-22 at 07 49 35" src="https://user-images.githubusercontent.com/1204802/122871000-b2674200-d32e-11eb-9258-5cdb2a20db8e.png">

2. A horizontal scrollbar appears in group:

<img width="707" alt="Screenshot 2021-06-22 at 07 49 39" src="https://user-images.githubusercontent.com/1204802/122871028-bd21d700-d32e-11eb-9459-c928fabf8420.png">

That appears to also be the result of blockbase theme styles:

<img width="538" alt="Screenshot 2021-06-22 at 07 50 05" src="https://user-images.githubusercontent.com/1204802/122871059-c743d580-d32e-11eb-8047-40fd4bae6e61.png">

3. Because of that scrollbar/overflow handling, submenus are cropped:

<img width="698" alt="Screenshot 2021-06-22 at 07 50 10" src="https://user-images.githubusercontent.com/1204802/122871089-d1fe6a80-d32e-11eb-9a0e-41b515d80a60.png">

Since these are all theme issues, I've gone ahead and created a ticket in the blockbase repository (https://github.com/Automattic/themes/issues/4083) and close this one. If that was in error, I'll be happy to reopen!

**Closed as completed by jasmussen** 2021-06-22 05:56 UTC
Labels: Needs Testing, [Block] Navigation

**Comment by bbertucc** [comment] 2021-06-22 19:52
Amazing @jasmussen this should take care of the issue 🤞
