### ISSUE TITLE
Bug IconButton Setting-Menu

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#5899] opened 2018-03-30 08:29 UTC
The IconButton in english and german.
![image](https://user-images.githubusercontent.com/6922544/38130846-db1fb35c-3404-11e8-927d-86a772bb0e49.png)
![image](https://user-images.githubusercontent.com/6922544/38130835-d286c3e8-3404-11e8-8b5f-48b1a782329f.png)

But the String is
![image](https://user-images.githubusercontent.com/6922544/38130882-0829b97e-3405-11e8-81b2-37470ee8cdee.png)

**Why is "option" change written in small letters?**

https://github.com/WordPress/gutenberg/blob/master/editor/components/block-settings-menu/index.js
The Code
![image](https://user-images.githubusercontent.com/6922544/38130909-276ca8dc-3405-11e8-9664-80c68ae718fa.png)

**Comment by ocean90** [comment] 2018-03-30 10:33
Duplicate of #5789.

**Closed by ocean90** 2018-03-30 10:33 UTC
Labels: [Type] Bug, i18n
