### ISSUE TITLE
Bold behavior inverted on headings

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#16454] opened 2019-07-08 08:00 UTC
**Describe the bug**
There are some problems with bold text and heading blocks.

**To reproduce**
What I did was:
- Converted a classic block in an old post to gutenblocks.
- The 'headings' in this block were just bolded text with a line break after them, so they didn't convert into headings automatically.
- I added a proper line break to split the block in two, and converted the bolded paragraph to a heading.
- It seems like some of those headings kept the bold styling, but the bold button somehow didn't register that, and now the bold behavior is inverted...

![wat](https://user-images.githubusercontent.com/6073772/60573246-93ed9200-9d77-11e9-8c5f-c0ae756e9e1f.gif)

Then, things got really interesting.

I tried to replicate this behavior in another post:
- added a new paragraph
- added a soft line break between two lines
- bolded the first line
- added a proper line break to split the block
- converted the bolded paragraph to a heading
- oops now the heading text is gone...

![what2](https://user-images.githubusercontent.com/6073772/60573579-373ea700-9d78-11e9-8388-eef2413bafcc.gif)

**Expected behavior**
For bolding to work the way it is supposed to (maybe some markup got carried over from the classic block?) and for no text to disappear 😄 

**Desktop (please complete the following information):**
WordPress 5.2.2
Gutenberg plugin 6.0.0
Chrome 75.0.3770.100
MacOS Mojave 10.14.5 Macbook Pro

**Comment by karmatosed** [comment] 2019-07-18 13:52
In the latest version of Gutenberg using Chrome I can't replicate this as shown here:

![image](https://user-images.githubusercontent.com/253067/61463092-a36dfd00-a96b-11e9-8a21-0884aca0a229.png)

Would you perhaps be able to try again @hedgefield and see if this is resolved?

**Comment by hedgefield** [comment] 2019-07-24 08:07
I just pasted the code of the affected post into an up-to-date gutenberg 6.1.1. install because I couldn't check it on the site where it first happened (don't have admin access), but this happened:

![bold](https://user-images.githubusercontent.com/6073772/61774633-8f0c8300-adf7-11e9-9661-7e967993bdd8.gif)

All the headings disappear when I click on them.

I've pasted a portion of the code below so you can try it (replaced the text with lorem ipsum).

```
<!-- wp:heading -->
<h2>Lorem</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem ipsum.</span></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem ipsum&nbsp;</span></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem </span><a href="#"><span style="font-weight: 400;">ipsum</span></a><span style="font-weight: 400;">.</span> <span style="font-weight: 400;">Lorem ipsum.</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Lorem</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem ipsum</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2><b>Lorem</b></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem ipsum.</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2><b>Lorem</b></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><span style="font-weight: 400;">Lorem ipsum. </span><br><span style="font-weight: 400;">Lorem ipsum. </span></p>
<!-- /wp:paragraph -->
```

**Comment by youknowriad** [comment] 2019-08-19 17:30
I can't reproduce either with the content above. I'm going to close this issue now but let's reopen if we find a consistent way to reproduce.

**Closed by youknowriad** 2019-08-19 17:30 UTC
Labels: [Block] Heading, [Package] Format library, [Status] Needs More Info

**Comment by tbob18** [comment] 2022-10-05 16:28
Had the same issue. A simple fix, just add this to admin css override:

.wp-block-heading {
  font-weight: normal;
}
.wp-block-heading b, .wp-block-heading strong {
	font-weight: 700;
}
![bold-heading](https://user-images.githubusercontent.com/1667028/194112610-b4e12a6b-f743-4701-ba3c-5c77c4cc1ad8.png)
