### ISSUE TITLE
List block won't delete li node on block edit with backspace

### ISSUE THREAD

**Issue by p2er** [WordPress/gutenberg#13358] opened 2019-01-17 14:24 UTC
**Describe the bug**
List block won't delete li node on block edit with backspace.

**To Reproduce**
1. Go to editor
2. Add list block
3. Add bullet value and hit enter to create new bullet point
4. Repeat 4 times to get 5 bullet points
5. Remove last bullet point with backspace
6. Editor no longer shows last bullet point
7. Switch to block markup view
8. Last `<li></li>` does still exist while content is empty
9. Preview article
10. List has been saved with empty bullet point at the end 

**Expected behavior**
The last bullet point should not be empty if removed in the editor view. Empty `<li></li>` should be removed from markup and only be created if enter is hit again. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser chrome
 - Version 71.0.3578.98

**Additional context**
- Gutenberg Version 4.8.0

**Comment by chthonic-ds** [comment] 2019-01-17 18:35
Duplicate of #12787

**Closed** 2019-01-17 18:55 UTC
