### ISSUE TITLE
meta postboxes might stay invisible in the Gutenberg post editor sidebar

### ISSUE THREAD

**Issue by Theremingenieur** [WordPress/gutenberg#5920] opened 2018-04-01 14:32 UTC
## Steps to Reproduce (for bugs)
1) Revert temporarily to the classic editor
2) Use "screen options" to hide a specific meta postbox
3) Go back to the Gutenberg editor
4) Forget about having hidden the meta postbox
5) Wonder later why that specific meta postbox is never shown in the Gutenberg post editor sidebar where no "screen options" settings are available.
6) (Optional) Blame the plugin author for his meta postbox being incompatible with the Gutenberg editor ;)

## Possible Solution
- Either show all meta postboxes in the Gutenberg post editor sidebar by default, independent of their respective visibility settings
- Or add option settings to the sidebar similar to the "screen options" in the classic editor

**Comment by jasmussen** [comment] 2018-04-03 11:25
Thanks for the report. Closing, as this is a duplicate of #5841.

**Closed by jasmussen** 2018-04-03 11:25 UTC
