### ISSUE TITLE
Editing a post in Gutenberg generates too many revisions 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3656] opened 2017-11-26 12:18 UTC
See also https://github.com/WordPress/gutenberg/issues/3258 and https://github.com/WordPress/gutenberg/issues/2385

Definitely not my area of expertise and I haven't followed the discussion about saving / autosave / revisions so I'm probably missing something. However, seems to me this is an issue of fundamental importance, as the amount of revisions that get saved is insanely big.

I've just created a new post, nothing special: just a title, couple paragraphs, a list, and an image. Then pressed "Publish" once. And I've got 9 revisions:

![screen shot 2017-11-26 at 12 17 14](https://user-images.githubusercontent.com/1682452/33239614-df40246e-d2a5-11e7-8d72-b47340461b2b.png)

![screen shot 2017-11-26 at 12 19 10](https://user-images.githubusercontent.com/1682452/33239649-9657224c-d2a6-11e7-8def-d289a8996682.png)

The amount of saved revisions can be way bigger with more complex post content and workflows. Even applying some basic formatting, for example making a word bold, puts Gutenberg in a "save draft" state, and then when the autosave triggers, a new revision gets created. This happens with any edit, also when changing a block position, or alignment, etc. Creating a post with some more blocks and formatting can easily generate dozens of revisions.

Seems to me every time Gutenberg auto-saves the post content, it creates a new revision. This can be easily observed also in the Gutenberg sidebar: while adding and editing content, the number of revisions increases. I'm not sure this is ideal, and seems to me it's a big change in how revisions and autosaves are handled in WordPress. 

Creating a similar post in the Classic Editor typically saves just the post, one revision (which isn't even shown in the UI) and sometimes (depending on the workflow) the special "autosave" revision.

**Comment by afercia** [comment] 2017-11-26 12:22
I guess this happens also with the Gutenberg plugin, to it's happening to everyone who's testing the Gutenberg on their site. I'd recommend to clearly state to not test Gutenberg on productions sites, since at the moment it's adding lots of unnecessary stuff in the database.

**Comment by afercia** [comment] 2017-11-28 13:08
Seems to me this is a blocker, I'd like to see some higher priority for this issue.

**Comment by aduth** [comment] 2017-11-29 14:36
Related: https://github.com/WordPress/gutenberg/issues/1773#issuecomment-316434091

**Comment by adamsilverstein** [comment] 2017-12-11 13:49
The way autosaves work on core currently, a revision is created whenever the content has changed. In the classic editor, I believe we only perform autosaves in specific intervals, after x seconds, when the user is idle. It seems like Gutenberg currently autosaves too frequently, on every block blur maybe? For now, I think we can better match the timing of autosaves to get similar behavior to the classic editor.

**Comment by aduth** [comment] 2017-12-11 17:39
As I understand the logic, it appears the main difference in the classic editor is not the timing of the saves, but that the automatic save assigns a constant which is checked against to abort creating a new revision:

https://github.com/WordPress/wordpress-develop/blob/1b5554e/src/wp-admin/includes/post.php#L1871-L1873
https://github.com/WordPress/wordpress-develop/blob/1b5554e/src/wp-includes/revision.php#L112-L114

**Comment by lancewillett** [comment] 2017-12-13 19:27
Would be well worth looking at how this has already been solved in other top-of-class editors like Google Docs. The best user experience seems to be a combination of:

Automatic saves:
1. Time elapsed: don't wait too long, in case of a crash.
2. Create revisions with a meaningful enough chunk of text, but not every single character change if in rapid succession. Phrases or sentences.

Manual saves:
Creates a revision for each one. Consider the ability to name revisions.

**Comment by adamsilverstein** [comment] 2017-12-15 20:27
>  it appears the main difference in the classic editor is not the timing of the saves, but that the automatic save assigns a constant which is checked against to abort creating a new revision:

The classic editor uses wp.autosave to save every 10 seconds at most, and only if the content has changed, is that logic in place in Gutenberg? https://github.com/WordPress/wordpress-develop/blob/1b5554e8188f24a0b522d82a2eccb7d098b878bb/src/wp-includes/js/autosave.js#L599

**Comment by aduth** [comment] 2017-12-15 20:31
>The classic editor uses wp.autosave to save every 10 seconds at most, and only if the content has changed, is that logic in place in Gutenberg?

Similar logic, yes:

https://github.com/WordPress/gutenberg/blob/master/editor/components/autosave-monitor/index.js

The "content has changed" behavior may not match what exists in core. Previously this was more accurate to performing a deep comparison on the current editor state against the last saved post (#1996), but was simplified recently (#3298).

**Comment by adamsilverstein** [comment] 2017-12-18 02:31
Ok, i finally see what is happening here. 

When creating new posts, Gutenberg is currently creating a new revision for each modification/autosave - instead of saving to a single draft post. regular revisions should only be created when the user explicitly clicks the publish or update button. In the classic editor no matter how many times you save a draft only a single draft revision (and single db row) is created.

When a post is published we create **_at most one autosave per user_**. regular revisions are only created when you actually update a post by saving a draft or updating a published post. autosaves are a special kind of revision and are created after 10 seconds when content changes. note that  data is also stored in localStorage if available so if the save fails (offline) the autosave still works.

**Comment by adamsilverstein** [comment] 2017-12-18 13:23
I took a pass at addressing this in https://github.com/WordPress/gutenberg/pull/4062 - this change prevents saving of revisions when a draft is autosaved. 

Along the way I noticed that **_Gutenberg currently does not autosave changes to published posts_**. The inline docs indicate this is due to lack of support from core, however we may be able to achieve the correct result with existing filters. Is there an issue open for this already?

**Comment by aduth** [comment] 2017-12-18 16:47
Closest issue is #1773, which was closed when draft autosave support was added. There's a [mention there](https://github.com/WordPress/gutenberg/issues/1773#issuecomment-316434091) of published posts autosave. 

>however we may be able to achieve the correct result with existing filters.

Could you elaborate on this?

**Comment by adamsilverstein** [comment] 2017-12-19 03:53
> Could you elaborate on this?

I was thinking we could hook in during the normal rest handler process (not certain which hook yet) and given a certain condition, call wp_create_post_autosave instead. This seems cleaner than the other option which would be a custom endpoint. I'll create a separate issue and see if I can get these working.

**Comment by adamsilverstein** [comment] 2018-02-02 14:51
This should be resolved by https://github.com/WordPress/gutenberg/pull/4218

**Comment by DrewAPicture** [comment] 2018-03-05 22:04
Just following up here, @adamsilverstein does the resolution for #4218 cover the case where there's an unnaturally high number of revisions for the level of editing going on? I'm current writing a post in Gutenberg that's at ~220 revisions, whereas I'd expect more like 20 or 30 under the classic editing conditions.

**Comment by adamsilverstein** [comment] 2018-03-07 03:48
@DrewAPicture thanks for checking in. No, unfortunately the scope for https://github.com/WordPress/gutenberg/pull/4218 was narrowed to only showing the autosave notice - I was never able to get much traction on my heartbeat based approach to autosaving despite many passes at suggested corrections and rebases. I'll work on a newer, narrower pr soon that leverages the REST API instead, see https://core.trac.wordpress.org/ticket/43316.

Out of curiosity, is your post a draft or published?

**Comment by DrewAPicture** [comment] 2018-03-07 04:56
> Out of curiosity, is your post a draft or published?

Currently a draft on make/docs.

**Comment by mhsabbagh** [comment] 2018-03-25 15:47
Same issue here, except that I get something like 225 revisions for a complete 700-word post.

**Comment by aduth** [comment] 2018-05-31 18:47
Can this be considered closed by #6257 ?

**Comment by danielbachhuber** [comment] 2018-05-31 18:48
Yep, I think so. We can open new issues for other items.

**Comment by danielbachhuber** [comment] 2018-06-04 23:27
@adamsilverstein @aduth This is (somehow) still happening with 3.0

**Comment by danielbachhuber** [comment] 2018-06-04 23:57
> This is (somehow) still happening with 3.0

To clarify, I updated to Gutenberg 3.0 on my personal blog. I then published a blog post that was mostly a copy and paste from Simplenote. Somehow, I ended up with 11 revisions:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/36432/40947460-a010624c-6817-11e8-81f9-5400f5bb94bf.png">

Here's a GIF of the revision history:

![travelpost](https://user-images.githubusercontent.com/36432/40947504-e29a1216-6817-11e8-85ba-6d061dff9fe2.gif)

It _seems_ like revisions are being created when autosave fires.

However, I can't reproduce against my local copy of Gutenberg.

**Comment by danielbachhuber** [comment] 2018-06-05 00:05
Ah, I've figured it out: the presence of Yoast SEO (aka a classic metabox) is causing autosave to trigger a normal save (or something of that sort).

See this GIF:

![toomanyautosaves](https://user-images.githubusercontent.com/36432/40947782-709b4458-6819-11e8-92c6-bfd81851d80b.gif)

Notably, see the "Autosaving..." animation, quickly followed by "Saving..."

I'm going to open a new separate issue for this.

**Comment by danielbachhuber** [comment] 2018-06-05 00:10
#7135

**Closed by danielbachhuber** 2018-06-05 00:10 UTC
Labels: Core REST API Task, Priority High, [Type] Try Gutenberg Blocker
