### ISSUE TITLE
The inline Inserter position jumps

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#23081] opened 2020-06-10 22:06 UTC
**Describe the bug**
When hovering over the inserter between blocks, it jumps. At first I thought my animation was problematic when [working on the hover delay and animation speed.](https://github.com/WordPress/gutenberg/pull/23043) Then, I looked a bit closer. It seems the Inserter is actually moving causing some serious jank.

To confirm this, I shortened the animation and delay to almost 0. It makes it really clear what is happening. You can see it in this gif:

![2020-06-10 15 57 27](https://user-images.githubusercontent.com/1123119/84323259-b49b9b80-ab33-11ea-843f-8c0ff5681fe5.gif)

**To reproduce**
1. Add a few paragraph blocks.
2. Hover slowly right below where the inserter. It's hard to figure out unless you dramatically shorten the animation time found [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L387) to something like `0.01s`. You might also remove this [80% bit here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/style.scss#L397).

**Expected behavior**
I expect the inserter to not jump.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Gutenberg master

**Desktop (please complete the following information):**
 - OS: MacOS latest
 - Browser: Firefox latest

**Comment by paaljoachim** [comment] 2020-06-23 16:46
Let's get this bug squashed..:)

**Comment by ZebulanStanphill** [comment] 2020-06-24 14:16
I've definitely seen this weirdness before, but I never dug into it to find out exactly what triggered it. Thanks for looking into it and creating this issue, @MichaelArestad!

**Comment by ellatrix** [comment] 2020-07-20 15:28
I've done some refactoring in #20792 while fixing another bug. I'm not noticing any issues after that. Could you retest with master?

**Comment by MichaelArestad** [comment] 2020-07-20 16:20
@ellatrix I tested on master and I'm still seeing it.

To reproduce:
1. Create a new post/page
2. add several paragraphs in a row
3. Move your cursor over the inserter icon and move very slowly downward (very slow). It's not consistent so try between more than one paragraph.

**Comment by youknowriad** [comment] 2020-07-23 12:19
Due to how difficult it is to reproduce this and the severity, I'm removing this from  the 5.5 Must-Haves.

**Comment by MichaelArestad** [comment] 2020-07-27 19:54
@youknowriad sounds good as long as we eventually figure it out. Keep up the good work!

**Comment by talldan** [comment] 2021-07-21 08:09
I haven't seen this happen for a while now and I just tested and can't reproduce. I believe the code for the in-between inserter was reworked quite a bit, and it seems much more reliable. I'll close this, but can always reopen or open a new issue if it reoccurs.

**Closed by talldan** 2021-07-21 08:09 UTC
Labels: [Feature] Inserter, [Type] Bug
