### ISSUE TITLE
"URL" instead of "Slug" in "Permalink" sidebar section

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#12261] opened 2018-11-24 05:22 UTC
**Describe the bug**
The new "Permalink" sidebar section says "URL" where it probably means "slug."

**To Reproduce**
1. Edit an existing post
2. Roll open the "Permalink" sidebar section
3. Notice the label for the slug says "URL" above the slug input box

**Expected behavior**
I know "slug" is kind of jargony, but "URL" doesn't make sense here either, because what's in the box isn't actually a URL, and confused users may enter a full URL in there trying to follow the instruction of what's supposed to be in the box according to the label.

**Screenshots**
<img width="278" alt="screen shot 2018-11-23 at 11 21 19 pm" src="https://user-images.githubusercontent.com/88951/48964861-8157e280-ef76-11e8-8424-910b16627ce1.png">

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
- WordPress 5.0 RC 1

**Comment by swissspidy** [comment] 2018-11-24 07:10
That was a deliberate decision. Many other systems use something sinilar. Slug is hard to understand and even harder to translate.

Since there is a preview underneath the input field, I don‘t think users will ever enter a full URL.

**Comment by ocean90** [comment] 2018-11-24 17:06
Duplicate of #12033.

**Closed by ocean90** 2018-11-24 17:06 UTC
Labels: [Component] Permalink
