### ISSUE TITLE
Consider changing the return value of `wp_get_global_settings` and `wp_get_global_styles()` when non-existent arguments are passed

### ISSUE THREAD

**Issue by ivan-ottinger** [WordPress/gutenberg#39905] opened 2022-03-30 15:15 UTC
## What problem does this address?

Currently, when non-existent `$path` and/or `$context` is passed to the following two functions:

```php
wp_get_global_settings( $path = array() , $context = array() );
wp_get_global_styles( $path = array(), $context = array() );
```

all settings/styles are returned. I think it would be easier to use the above APIs if `null` was returned instead. This would signal that the requested settings/styles cannot be returned.

## What is your proposed solution?

Instead of returning all settings/styles, we could return `null`. All settings/styles are already returned when no arguments are passed.

**Comment by mrwweb** [comment] 2022-10-10 23:45
Duplicate of #39657?

**Comment by ndiego** [comment] 2022-10-11 14:50
Closing in favor of https://github.com/WordPress/gutenberg/issues/39657 since that issue was submitted first and they are both the same.

**Closed as completed by ndiego** 2022-10-11 14:50 UTC
Labels: [Type] Enhancement, Needs Technical Feedback
