### ISSUE TITLE
SandBox not re-rendered after HTML changes

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#16831] opened 2019-07-31 05:33 UTC
**Describe the bug**
The `SandBox` component from the `@wordpress/components` package is not re-rendered when the injected `html` prop changes.

**To reproduce**
* Paste the following code in `playground/src/index.js`:
```js
import { render, useState, Fragment } from '@wordpress/element';
import { SandBox, SelectControl } from '@wordpress/components';
import './style.scss';
import '@wordpress/components/build-style/style.css';

function App() {
	const [ fruit, setFruit ] = useState( 'Bananas' );
	const html = `<div>Selected fruit: <strong>${ fruit }</strong>!</div>`;

	return (
		<Fragment>
			<SelectControl
				label="Fruit"
				value={ fruit }
				options={ [
					{ label: 'Bananas', value: 'Bananas' },
					{ label: 'Oranges', value: 'Oranges' },
					{ label: 'Apples', value: 'Apples' },
				] }
				onChange={ ( value ) => { setFruit( value ) } }
			/>
			<SandBox html={ html } />
		</Fragment>
	);
}

render(
	<App />,
	document.querySelector( '#app' )
);
```

* Run `npm run playground:start`.
* Go to `http://localhost:1234`.
* Select any other fruit than _Bananas_.

**Expected behavior**
The selected fruit text displayed below the fruit selector should be updated after selecting any other fruit, but it keeps unchanged:

**Screenshots**
<img width="642" alt="Screen Shot 2019-07-31 at 14 32 38" src="https://user-images.githubusercontent.com/1233880/62186151-1df14080-b3a0-11e9-8d17-61c784ac207b.png">

**Comment by swissspidy** [comment] 2019-07-31 08:12
Sounds like a duplicate of #16612.

Can you test #16669 to see if that fixes the issue?

**Comment by mmtr** [comment] 2019-08-01 00:09
> Sounds like a duplicate of #16612.
> 
> Can you test #16669 to see if that fixes the issue?

I don't think it's related to #16612. I verified I can still reproduce the issue with #16669.

Seems to be more a problem on how the `SandBox` component is implemented. The `render` function [doesn't use at all the `html` prop](https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/components/src/sandbox/index.js#L200-L214), which is why any change to that prop doesn't trigger any update. The `html` prop is only [used on `trySandbox`](https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/components/src/sandbox/index.js#L175), but that method is only called after the `SandBox` component has been already rendered.

**Closed** 2020-02-13 18:53 UTC
Labels: [Package] Components, [Status] In Progress, [Type] Bug
