### ISSUE TITLE
Site Editor: theme.json + core/navigation.spacing.blockGap not working properly

### ISSUE THREAD

**Issue by gyurmey2** [WordPress/gutenberg#46876] opened 2023-01-04 07:25 UTC
### Description

Adding the following snippet to your theme.json file has no effect in the Site Editor.

```
"core/navigation": {
   "spacing": {
      "blockGap": "10rem"
   }
}
```

### Step-by-step reproduction instructions

1. Add the above snippet to your theme.json file.
2. Check if there are any changes.

### Environment info

WordPress: 6.1.1
Theme: TT3
Gutenberg: 14.8.4 & 15.0.20230103 & without.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-01-10 14:22
Hi @gyurmey2. This issue came up in today's Weekly Editor Bug Scrub, but we were unable to replicate. Can you confirm that you are placing the snippet inside of the "blocks" section of "styles". Here is a simified version that is working for me. 
```
"styles": {
    "blocks": {
        "core/navigation": {
            "spacing": {
                "blockGap": "10rem"
            }
        }
        ...  
```

**Comment by gyurmey2** [comment] 2023-01-11 07:46
@ndiego, thank you.

Yes, I can confirm that the problem is still there. You can test this on a [completely fresh install](https://app.instawp.io/wordpress-auto-login?site=$2y$10$PzPOWPWEbD8O9BTsEQnjFeg8a4lv7IJC5p4eLPtfQbRdsjRFQW3LK).

**Comment by t-hamano** [comment] 2023-01-12 03:05
I was able to reproduce it.

The `blockGap` defined in `theme.json` is reflected in the global style, but changing the value doesn't actually reflect it.
In the Dimensions control of the block, it works correctly.

https://user-images.githubusercontent.com/54422211/211966133-e2c10e11-d0b1-428a-beae-c0532beed00e.mp4

**Comment by t-hamano** [comment] 2023-01-12 10:14
This problem occurs only in the editor. I expect that it is probably due to the fact that the markup is different from the front end.
We can see that the elements to which the `is-layout-flex` and `wp-container-X` classes are given are different.

```html
<!-- Frontend -->
<nav class="wp-block-navigation is-layout-flex wp-container-X">
	<ul class="wp-block-navigation__container">
		<li class="wp-block-navigation-item wp-block-navigation-link">
			<a class="wp-block-navigation-item__content" href="#"><span class="wp-block-navigation-item__label">Page</span></a>
		</li>
	</ul>
</nav>

<!--! Editor -->
<nav class="block-editor-block-list__block wp-block wp-block-navigation">
	<div class="wp-block-navigation__container block-editor-block-list__layout wp-container-X is-layout-flex">
		<div class="wp-block-navigation-item wp-block-navigation-link">
			<a class="wp-block-navigation-item__content">
				<div role="textbox" class="wp-block-navigation-item__label rich-text" contenteditable="true">Page</div>
			</a>
		</div>
	</div>
</nav>
```

**Comment by ndiego** [comment] 2023-01-12 21:19
@t-hamano, do you think it could be a caching thing? It's working for me in both the Site Editor and the post Editor.

**Comment by t-hamano** [comment] 2023-01-13 04:05
@ndiego 
I am curious why it cannot be reproduced, but since this is a problem that can be reproduced in the editor, I think the cache appears to be irrelevant.

I can reproduce the following steps:

- Access the template editor
- Insert a navigation block
- Access "Styles" > "Blocks" > "Navigation" > "Layout"
- Changing the value of the block spacing will not be reflected in the navigation block

**Comment by ndiego** [comment] 2023-05-30 17:34
I just retested and was able to replicate it in WordPress 6.2 and Gutenberg trunk.

**Comment by t-hamano** [comment] 2023-06-15 11:50
I have tested this issue again and have confirmed that it does not reproduce in the latest Gutenberg.

@gyurmey2
I would like to close this issue, but if you have any questions please comment.

https://github.com/WordPress/gutenberg/assets/54422211/2609d649-ebc6-416a-974a-1236bcf9e5c0

**Closed as completed by t-hamano** 2023-06-15 11:50 UTC
Labels: [Type] Bug, [Block] Navigation, Global Styles

**Comment by gyurmey2** [comment] 2023-06-15 15:44
@t-hamano, now it works perfectly! Thank you very much.
