### ISSUE TITLE
Spacer block causing a layout shift (CLS)

### ISSUE THREAD

**Issue by design311** [WordPress/gutenberg#23727] opened 2020-07-06 23:16 UTC
**Describe the bug**
The Spacer block seems to be causing a layout shift, triggering the core web vitals. The height of the block seems to be added through JS rather than direct CSS meaning that the layout shifts.

**To reproduce**
1. Go to any page
2. Add a Spacer block
3. Increase the spacer size to 500px (to make it really visible)
4. Load the site with a slow connection (or emulate a slow connection using Chrome devtools)
5. Review using Google Lighthouse ( [example ](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fproteo.yithemes.com%2Fclassic-shop%2F&hl=en_GB) )

**Expected behavior**
No layout shifts should happen.

**Editor version (please complete the following information):**
WordPress 5.4.2 running YITH Proteo Child theme.
Default WordPress, no Gutenberg plugin

**Screenshots**

During loading
![image](https://user-images.githubusercontent.com/4565650/86664852-00344e80-bfe7-11ea-9d6a-aea0b8174fd9.png)

After loading
![image](https://user-images.githubusercontent.com/4565650/86664973-1e9a4a00-bfe7-11ea-90de-decbfd28971b.png)

Demo URL: https://proteo.yithemes.com/classic-shop/

**Comment by ntsekouras** [comment] 2020-07-08 09:07
Hey @design311! I've looked into the page you're showing as a Demo and the source code for spacer.

`Spacer` block saves the `height` style inline in content, so it's not applied with JS. [Take a look here.](https://github.com/WordPress/gutenberg/blob/965a5ada67216bd366e2aea94340cb0975ed30df/packages/block-library/src/spacer/save.js#L2)

Also in the top page you're noticing the layout shift, there isn't any `Spacer` block. There are two `Spacers` here ( made them red to be more noticeable ).

https://d.pr/free/i/0yq7dv

**Comment by ntsekouras** [comment] 2020-07-09 12:00
Hey @design311! I'm closing this issue for now since it seems there is not a bug here. If you find anything different just ping to the issue to check it again.

**Closed by ntsekouras** 2020-07-09 12:00 UTC
