### ISSUE TITLE
YouTube embed block in/as reusuable block shows URL of video not the video player

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#21860] opened 2020-04-24 08:47 UTC
**Describe the bug**
Making a YouTube embed into a reusable block (or when using a YouTube embed anywhere inside a Reusable block) the output on the frontend is the URL of the video not the player.

**To reproduce**
1. Create a new page
2. Add a YouTube embed by adding the video link to embed via the block
3. Save as a reusuable block
4. View the page on the frontend
5. You will see there is no player, only the URL you entered to embed (e.g. https://youtu.be/123456)

**Expected behavior**
Show the YouTube video player to watch the video embedded, as it does when not using a reusable block.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Default block editor not plugin

**Comment by annezazu** [comment] 2020-04-28 18:58
Thank you for this report. I tested this and can confirm the functionality breaks. Great find! Here are screenshots for good measure. 

Editor View: 
<img width="741" alt="Screen Shot 2020-04-28 at 11 56 53 AM" src="https://user-images.githubusercontent.com/26996883/80526306-66498900-8947-11ea-9ff1-2ee431eaa73c.png">

Front end Page View:
<img width="612" alt="Screen Shot 2020-04-28 at 11 56 45 AM" src="https://user-images.githubusercontent.com/26996883/80526300-65b0f280-8947-11ea-96c9-98bf0c4469f8.png">

**Comment by earnjam** [comment] 2020-05-11 18:01
Closing as a duplicate of #14608

**Closed by earnjam** 2020-05-11 18:01 UTC
Labels: [Block] Block, [Block] Media & Text, [Feature] Reusable Blocks, [Type] Bug
