### ISSUE TITLE
Gutemberg requires to enable Javascript in Safari even if it's enabled

### ISSUE THREAD

**Issue by ferdi2005** [WordPress/gutenberg#17318] opened 2019-09-03 20:01 UTC
**Describe the bug**
Javascript in Safari 12.1.2 (14607.3.9) is active, but Gutemberg continues asking to enable it. It's not an important bug, but it's important to take note. No console errors.
 
**To reproduce**
Open Gutemberg in Safari 12.1.2.
 
**Screenshots**
<img width="885" alt="Schermata 2019-09-03 alle 21 57 46" src="https://user-images.githubusercontent.com/19609180/64204496-302a3700-ce96-11e9-8726-5882b749bc12.png">
 - OS: macOS 10.14.6 (18G87)
 - Browser: Safari
 - Version 12.1.2.

**Comment by ferdi2005** [comment] 2019-09-03 20:01
<img width="1329" alt="Schermata 2019-09-03 alle 22 01 32" src="https://user-images.githubusercontent.com/19609180/64204582-649df300-ce96-11e9-8ef5-90868a377b5c.png">

**Comment by Soean** [comment] 2019-09-03 20:50
Thanks for reporting this issue. I can't reproduce the issue in Safari.
Can you deactivate all plugins to see if the problem is caused by an other plugin or the browser?

**Comment by ferdi2005** [comment] 2019-09-03 20:55
I deactivated all the plugins, but nothing changed.

**Comment by donmhico** [comment] 2019-09-04 00:09
Hello @ferdi2005,

Like @Soean, i'm unable to reproduce the issue too.

<img width="1518" alt="Screen Shot 2019-09-04 at 8 07 13 AM" src="https://user-images.githubusercontent.com/5747475/64216382-372f6480-ceeb-11e9-8cdf-b5cbd47649c0.png">

**Comment by talldan** [comment] 2019-09-04 03:26
I've also not been able to reproduce this. Looking at the code, this can happen if the `js` class is not applied to the body element.

@ferdi2005 — would you be able to let us know which version of WordPress you have installed and whether you're using the Gutenberg plugin (and if so, which version of the plugin)?

Btw, I think might also need to be moved to trac as the code for the notification is in core. Will wait for a response from @ferdi2005 though before doing that so that I have the full details.

**Comment by ferdi2005** [comment] 2019-09-04 12:45
WordPress 5.2.2. I don't know Gutemberg version because I'm not admin of the site.

**Comment by youknowriad** [comment] 2019-10-01 09:36
This could also be a safari extension or something like that.
I'm going to close the issue right now as unfortunately, we can't reproduce, so it's not actionable. If we find solutions to reproduce it, let's reopen again.

**Closed by youknowriad** 2019-10-01 09:36 UTC
Labels: General Interface, [Status] Needs More Info, [Type] Bug
