### ISSUE TITLE
Updatated changes in published posts still not appearing

### ISSUE THREAD

**Issue by matto15** [WordPress/gutenberg#12921] opened 2018-12-16 02:00 UTC
**Describe the bug**
Any updates made to already published posts do not appear in the post preview unless the post is updated. Wordpress 5.0.1 with the latest version of Gutenberg editor.

**To Reproduce**
Steps to reproduce the behaviour:
1. Publish any post (or open an existing one).
2. Make any change to the post.
3. Click preview post.
4. See error. (not updated).
5. Click update.
6. Preview post (changes now available).

**Expected behaviour**
The preview should show any new updates to posts before updating as the classic editor does.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [71.0]

**Comment by swissspidy** [comment] 2018-12-16 10:50
Duplicate of #12617.

**Closed by swissspidy** 2018-12-16 10:50 UTC
Labels: [Status] Duplicate
