### ISSUE TITLE
Slash command shortcuts for different heading levels

### ISSUE THREAD

**Issue by cbirdsong** [WordPress/gutenberg#50258] opened 2023-05-02 16:23 UTC
## What problem does this address?

You can easily add a heading block by typing `/he` and using the autocomplete box, like so: 

![The text "/he" entered into the block editor, followed by a popup that shows the heading block as the first option](https://user-images.githubusercontent.com/1672206/235725130-8867c781-6d36-4b74-bdea-284915ea5c06.png)

However, when I'm writing something and am adding a heading I usually know what heading level it should be, and if it's not an H2, I'll need to change the heading level after adding the block. To do that, I have to either:
- take my hands off the keyboard and use the mouse to pick in the toolbar
- do a lot of arrow key work on the keyboard

Both routes are pretty involved and make it easy to lose my train of thought.

## What is your proposed solution?

Add slash command shortcuts for `/h3`, `/h4`, etc that add a heading block with that heading level preselected.

**Comment by ndiego** [comment] 2023-05-02 23:55
I know this is not what you are looking for, and a slash command would be great, but you can do this with markdown. For example, `###` and then a space will create an `h3`.

**Comment by cbirdsong** [comment] 2023-05-03 01:28
That trick definitely gets the job done for me, but it's not very discoverable or explainable to someone who isn't familiar with markdown.

**Comment by talldan** [comment] 2023-05-03 07:55
Typing `/h4` and enter does already work, it's just the autocompleter doesn't show any suggestions as there are no blocks called that.

I think there might be other issues already open for making it show something, possibly using block variations. I think the tricky part is that it wouldn't be great to flood the autocompleter with only heading block suggestions.

**Comment by cbirdsong** [comment] 2023-05-03 12:39
See, I didn't even think to try that because the "Heading" autocomplete option disappears once you add a number to `/h`. I think the shortcut would be a bit more discoverable if that stayed visible once you've typed `/h#`, even if they label stayed as just "heading".

(It would obviously be clearer if it said "Heading 3" or whatever, but I can see how that introduces a lot of potential complications)

**Comment by Mamaduka** [comment] 2024-11-13 11:57
Closing as duplicate of #32472.

**Closed as not planned by Mamaduka** 2024-11-13 11:57 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Block] Heading
