### ISSUE TITLE
Can't swap templates in the post editor

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#61031] opened 2024-04-24 08:07 UTC
### Description

Possible the same as https://core.trac.wordpress.org/ticket/60997
Potentially related to #60946

In a block theme, by default, The Template setting in the Post/Page panel only has Edit template, Create new template, and Template preview. I can see the custom templates registered in the site editor under the Custom section of Templates. The "Swap Template" menu item is not visible when you have custom templates.

Apparently adding the `customTemplate` setting to `theme.json` shows the templates there.

It seems that it used to be visible in previous version of WordPress.

### Step-by-step reproduction instructions

Just open the post editor for a block theme where you created or has custom templates.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment] 2024-04-24 08:42
cc @ntsekouras as I believed you worked on some of this (well me as well :P)

**Comment by Mamaduka** [comment] 2024-04-24 19:44
@youknowriad, can you reproduce the issue? In that case, would you mind adding the reproduction steps?

The obvious guess is that the `useAvailableTemplates` hook doesn't return all available templates.

**Comment by youknowriad** [comment] 2024-04-25 06:07
I can't really reproduce actually :) I'll ask more information about it.

**Comment by mike-henderson** [comment] 2024-04-25 13:41
## Steps to Reproduce
Download 2024 Theme
Run wp-env in 2024 Theme folder
Remove `customTemplate` array from `theme.json`, save `theme.json`
Open the backend of the site 
Navigate to Site Editor 
Select Template section
Observe custom templates are still listed under *Custom*: `page-no-title`, `page-wide`, `page-with-sidebar`, `single-with-sidebar`

<img width="654" alt="Screenshot 2024-04-25 at 7 41 53 AM" src="https://github.com/WordPress/gutenberg/assets/78349/d4a6ba80-b17b-4236-ba66-f5a4af6c2286">

Navigate back to dashboard
Add new Page
Open Page panel
Observe **Swap template** is missing

<img width="971" alt="Screenshot 2024-04-25 at 7 42 19 AM" src="https://github.com/WordPress/gutenberg/assets/78349/f9866112-e242-4acd-82ab-587c9af5ed26">

**Comment by Mamaduka** [comment] 2024-04-26 12:32
I think I know where regression is coming from. The old component [was merging values](https://github.com/WordPress/gutenberg/blob/efa4b01e8eb3d01be82eb45f4838f99286e28640/packages/edit-post/src/components/sidebar/post-template/form.js#L61-L73) from REST API and editor settings `availableTemplates`. This was a requirement for Template Editing mode. Classic themes with special support flags can have mixed templates — block and PHP.

Unfortunately, this behavior also covered a bug for the block themes, where querying the templates endpoint by `postType` was returning incorrect results.

## Why are the REST API and `availableTemplates` setting results different?

* The `availableTemplates` is populated via `WP_Theme::get_post_template` and, due to its data structure, uses a different filtering method.
* The REST API uses `get_block_templates( [ 'post_type' => 'page' ], 'wp_template )`, and this is where we have a bug when filtering file-based block templates. The filtering happens much earlier than we have all the information about the template.

## Solutions

~~**Short-term for minor release:** Merge template values like before.~~ This won't work. The `availableTemplates` setting returns just the `slug => title` template map. Block themes need the whole object.

Fix underlying bugs in PHP functions. I'll start working on the fix on Monday, and then we can evaluate its inclusion in a minor release.

**Comment by Mamaduka** [comment] 2024-04-30 12:27
@oandregal, I tracked down this regression to this performance ticket - https://core.trac.wordpress.org/ticket/57756.

The problem with [55687](https://core.trac.wordpress.org/changeset/55687) changeset:

* When a custom template doesn't list the post types it belongs to, it can be assigned to any post type.
* The `_get_block_templates_files` isn't aware if the file is a custom template. So, it does strict post-type checks.

**Comment by Mamaduka** [comment] 2024-04-30 14:33
A fix is ready for testing #61244. I would like to add PHPUnit tests before landing them in the core, but I still haven't figured out the best way.

**Closed as completed** 2024-05-01 11:27 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Templates API, Needs Testing

**Comment by oandregal** [comment] 2024-05-02 09:16
Based on the test instructions provided by @mike-henderson I'm unconvinced this needed any fixing, and #61244 introduces a performance regression (timeToFirstByte, front-end).

I've shared what I know at https://github.com/WordPress/gutenberg/pull/61244#issuecomment-2089975586 to gather feedback. The TLDR is: how custom templates are registered by block themes? Via `customTemplates` in `theme.json` (my expectation) or by merely being present in the `templates/` folder?
