### ISSUE TITLE
Gallery: Improve the "edit gallery" button

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1129] opened 2017-06-11 11:55 UTC
Current state:

![current](https://user-images.githubusercontent.com/1204802/27010799-7ad010a6-4ead-11e7-8c95-2df36c325994.png)

That button on the left opens the gallery so you can edit it. 

Let's make this a separate button, with an edit icon:

![button](https://user-images.githubusercontent.com/1204802/27010803-8ea264ee-4ead-11e7-93a4-d25b1125a432.png)

(the right most one here)

**Comment by njpanderson** [comment] 2017-06-11 12:55
Would like to take this one on if possible for an outsider? I've had a bash at it already and it looks like this:

<img width="293" alt="screen shot 2017-06-11 at 13 52 11" src="https://user-images.githubusercontent.com/12379690/27011124-31f7dd46-4ead-11e7-9a58-86750146222c.png">

I've used the `leftDivider` attribute for the control item and given it the `edit` icon using the [dashicons](https://developer.wordpress.org/resource/dashicons/) page as reference.

Two things I'd like to figure out:

1. Is a separation possible in the current codebase? Looking at `components/toolbar/index.js` seems to imply that it's just a single array of buttons.
2. Where does the edit button you've shown in your screenshot come from?

If you think this is beyond the scope of a newbie, just say so - happy to spend my time on another issue.

**Comment by njpanderson** [comment] 2017-06-11 13:01
Interestingly I'm not sure the edit button actually works either way. The dialog that appears implies there will be the images to shift about but it's empty.

<img width="1194" alt="screen shot 2017-06-11 at 14 00 54" src="https://user-images.githubusercontent.com/12379690/27011175-6ca44db6-4eae-11e7-83da-234c892351ca.png">

**Comment by jasmussen** [comment] 2017-06-11 14:46
Solid work, thank you!

For the technical aspect, I think we'll want to give the button it's own group. I think this is the first block having such a group, so it's probably not a super easy task. 

Don't worry about the icon, it's from the Gridicons set which I used for the mock-ups. We're using Dashicons here and you picked the right one.

**Comment by jasmussen** [comment] 2017-06-11 14:47
The media library issue I can't speak to, it worked for me when I tried.

**Comment by njpanderson** [comment] 2017-06-11 16:24
I'm going to have a go at splitting the buttons out first, then will make a PR either way.

**Comment by njpanderson** [comment] 2017-06-11 18:18
Ok, I've done something that might take a bit of explaining. Essentially, I saw that this was already sort-of done with other blocks such as text/heading:

<img width="652" alt="screen shot 2017-06-11 at 18 57 44" src="https://user-images.githubusercontent.com/12379690/27013267-a4778238-4ed8-11e7-82a8-3c2759a9ab28.png">

... But it seemed to me that the split of controls was at a higher level than the `components-toolbar`, and not something that looked to be editable within abilities of the `registerBlockType`  function.

As such, I've augmented the way the controls are defined a little. the `VisualEditorBlock` and/or `Toolbar` components now take an array of arrays for the `block.controls` property. Each child array contains the same data as before (that is to say, individual controls), but the outer array is considered to be one of potentially many single `components-toolbar` toolbars.

This is by design an optional configuration when using `registerBlockType`, although there are checks put in place to ensure that the proposed structure is always used when it comes to rendering. Firstly, at the block level (`visual-editor/block.js:233`) and at within the `Toolbar` component (`toolbar/index.js:17`).

The end result looks like this:

<img width="674" alt="screen shot 2017-06-11 at 18 57 19" src="https://user-images.githubusercontent.com/12379690/27013273-fd971e8c-4ed8-11e7-8e63-f70c6a00ce70.png">

Which I think is pretty much what you're after.

**Alternative method:** I had also tried an alternative to the nested array, which was to add a "break" point in the control items by way of a property similar to `leftDivider`, which would trigger a split of the controls array to result in a similar nested array, although only operating within the render of `components/toolbar`. This, while less of a sweeping change, felt a bit suboptimal as it required mutation of the array at render time of the toolbar itself, which happens quite a bit during the lifecycle of the block interface.

Of course, I could be barking up the wrong tree entirely with either of these methods, and there might be a better way (likely involving the same technique which produces three discrete toolbars in blocks such as text or heading). I've got little to know exposure to how that part works and if this is the case, then someone with better knowledge of the codebase might want to take up the challenge instead.

**Comment by jasmussen** [comment] 2017-06-11 18:22
Thank you for this! @mtias can you take a look later?

**Comment by mtias** [comment] 2017-06-11 22:26
@njpanderson thanks for giving this a try. We already support multiple children in toolbars through Slot/Fill. This is how you would accomplish it within the gallery `edit()` method:

```jsx
				<Fill name="Formatting.Toolbar">
					<Toolbar controls={ [ {
						icon: 'format-image',
						title: wp.i18n.__( 'Edit Gallery' ),
						onClick: () => editMediaLibrary( attributes, setAttributes ),
					} ] } />
				</Fill>
```

**Comment by mtias** [comment] 2017-06-11 22:32
See #1136. We were also considering completely removing the `controls` key on the block definition object in general.

**Comment by njpanderson** [comment] 2017-06-12 05:37
Aah, I thought it might have something to do with that `edit` method I was seeing in other components.

Given that this appears to be solved in #1136 then, the icon appears to be the only issue here. Is that correct?

**Comment by jasmussen** [comment] 2017-06-12 05:40
Correct, thanks @njpanderson. I left a comment on the other pr.

**Comment by njpanderson** [comment] 2017-06-12 05:43
Great. If the icon is resolved in the other PR then this issue is largely redundant. I'll go and look into the methods @mtias suggested for reference then work on a less integrated task ;)

**Closed** 2017-06-12 12:26 UTC
Labels: Blocks
