### ISSUE TITLE
Cannot reach some text positions in nested formatting

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#13153] opened 2018-12-31 22:46 UTC
**Describe the bug**
When nesting formatting, it can be difficult to select which text section we want to edit. In the following example I want to add a space on the italicized text rather than the `<em>`. I'm incapable of doing so, and would need to add a space after the `i` in `is` then delete text.

![nested formatting](https://user-images.githubusercontent.com/1270189/50568674-2f8b4080-0d0a-11e9-9c0f-76bf6a58bcc4.gif)

**To Reproduce**
1. Start a new post in the block editor.
2. Add text to a paragraph block containing "This is italicized" and add italicized formatting to the section
3. After the word "This", add more text "is a code block", then select that section and add backticks to trigger `<em>` formatting
4. Try to add a space to the start of "is" in the italicized section instead of the codeblock. 

**Expected behavior**
I can add a space before `is` that is italicized. Right now I can only do that in the code block, or one character after the italicized section begins.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
- WP 5.0.2

**Comment by youknowriad** [comment] 2019-01-04 10:16
duplicate of #12975 ?

**Comment by youknowriad** [comment] 2019-01-04 12:13
Closing please reopen if you think it's a different issue.

**Comment by gwwar** [comment] 2019-01-04 16:50
Steps here are for a paragraph block, but I imagine this is the same for any nested text formatting. Maybe add a gif or screenshot in #12975 if you think this is the same issue.

**Comment by youknowriad** [comment] 2019-01-05 09:43
I'm fine keeping it open for now and see later.

**Comment by mcsf** [comment] 2019-01-15 17:44
cc @iseulde, if you're already looking at some text boundary stuff

**Comment by iseulde** [comment] 2019-01-15 17:53
Will be fixed as part of #11322.

**Closed** 2019-02-08 19:54 UTC
Labels: [Type] Bug
