### ISSUE TITLE
Intermittent test failure: "Template Part › Template part block › Should load customizations when in a template even if only the slug and theme attributes are set."

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#24336] opened 2020-08-03 15:51 UTC
## Description
This end-to-end test failure is happening intermittently:

```
FAIL packages/e2e-tests/specs/experiments/template-part.test.js (47.978s)
  ● Template Part › Template part block › Should load customizations when in a template even if only the slug and theme attributes are set.

    TimeoutError: waiting for XPath "//button[contains(text(), "header")]" failed: timeout 30000ms exceeded

      46 | 				'.components-dropdown-menu__toggle[aria-label="Switch Template"]'
      47 | 			);
    > 48 | 			const switchToHeaderTemplatePartButton = await page.waitForXPath(
         | 			                                                    ^
      49 | 				'//button[contains(text(), "header")]'
      50 | 			);
      51 | 			await switchToHeaderTemplatePartButton.click();

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:486:34)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:420:26)
      at DOMWorld.waitForXPath (../../node_modules/puppeteer/lib/DOMWorld.js:393:21)
      at Frame.waitForXPath (../../node_modules/puppeteer/lib/FrameManager.js:575:51)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:106:31)
      at Page.waitForXPath (../../node_modules/puppeteer/lib/Page.js:1015:33)
      at Object.<anonymous> (specs/experiments/template-part.test.js:48:56)
          at runMicrotasks (<anonymous>)
```

Discovered via [this discussion](https://github.com/WordPress/gutenberg/pull/23072#issuecomment-668081121).

**Comment by swissspidy** [comment] 2020-08-04 11:08
Duplicate of #24281

**Closed by swissspidy** 2020-08-04 11:08 UTC
Labels: Automated Testing, [Status] Duplicate
