### ISSUE TITLE
Buttons block: center-aligned buttons aren't exactly centered in the editor due to (invisible) appender

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#21805] opened 2020-04-23 01:42 UTC
I've noticed a centre aligned button is off centre in the editor. It seems to be caused by the right margin on the button and the appender.

![Frame 1](https://user-images.githubusercontent.com/908665/80049429-c769fa80-850a-11ea-9e2f-5526cadb00c7.png)

Tested with Mac Chrome, Twenty Twenty theme active.

Sorry, if it has already been reported. I had a quick look, but I didn't see one mentioning the appender making the misalignment worse.

**Comment by talldan** [comment] 2020-04-23 02:06
@iamtakashi https://github.com/WordPress/gutenberg/issues/21685 seems like a very similar issue.

**Comment by iamtakashi** [comment] 2020-04-23 10:40
@talldan Thanks for the info. I'm seeing this issue with a fresh new button though.

**Comment by talldan** [comment] 2020-04-24 03:00
I see that too in the editor, so I've labelled as a bug:
<img width="567" alt="Screenshot 2020-04-24 at 10 59 25 am" src="https://user-images.githubusercontent.com/677833/80170531-be684e80-861a-11ea-9ad3-d695b85b2655.png">

**Comment by paaljoachim** [comment] 2020-06-09 08:38
I made an issue with some additional information. I closed it as a duplicate.

**Comment by ZebulanStanphill** [comment] 2020-08-27 00:47
I've updated the title to be more descriptive. The cause of the issue is the appender (inserter button), which, although invisible when the Buttons block is unselected, still takes up space, pushing the other buttons to the left slightly.

**Closed** 2020-09-22 09:27 UTC
Labels: CSS Styling, [Block] Buttons, [Status] In Progress, [Type] Bug
