### ISSUE TITLE
Pasting Images will result in a classic editor block before and after the image

### ISSUE THREAD

**Issue by LZL0** [WordPress/gutenberg#12654] opened 2018-12-06 19:56 UTC
**Describe the bug**
Upon pasting the copied image from the content Gutenberg inserts a Classic editor block before and after the image.

**To Reproduce**
1. Insert image
2. Highlight image
3. Copy
4. Paste it somewhere

**Expected behavior**
The image should be pasted without the addition of the two Classic editor blocks.

**Video**
https://www.youtube.com/watch?v=dWM5hJsToiI&feature=youtu.be

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Opera 57, Chrome 71
 - Gutenberg 4.6.1

**Comment by GlennMartin1** [comment] 2018-12-07 00:10
Related / duplicate of https://github.com/WordPress/gutenberg/issues/9504.

**Comment by designsimply** [comment] 2018-12-07 12:44
Closing in favor of #9504.

**Closed** 2018-12-07 12:45 UTC
Labels: [Block] Classic, [Component] Raw Handling, [Status] Duplicate, [Type] Bug
