### ISSUE TITLE
Alignment: images in a centered 3-column gallery appear left-aligned in one column on the front end

### ISSUE THREAD

**Issue by newdrop20** [WordPress/gutenberg#9533] opened 2018-09-01 12:28 UTC
Hi i have an issue with gallery . 

I added some images in gallery and arrange as 3 images need to show in one row . But what happen is every images in coming in separate rows .

https://drive.google.com/drive/folders/1SJKQ3BGs47nogfqwCuH7wd_LE4PEqw1i?usp=sharing

![input-1](https://user-images.githubusercontent.com/1119271/45166641-c3ae2680-b1b4-11e8-8135-8cbc0a998cf4.jpg)

![output-1](https://user-images.githubusercontent.com/1119271/45166646-c6108080-b1b4-11e8-9f6f-b571fdda4e10.jpg)

I tried this  in two themes (Twenty fifteen and Twenty seventeen) but still the same problem occur . gutenberg version is 3.7.0

Please see the code below 

```
<!-- wp:heading {"align":"center"} -->
<h2 style="text-align:center">hi this is h2v</h2>
<!-- /wp:heading -->

<!-- wp:list -->
<ul><li>This is test </li><li>this is second </li><li>this is third</li></ul>
<!-- /wp:list -->

<!-- wp:gallery {"columns":3,"align":"left"} -->
<ul class="wp-block-gallery alignleft columns-3 is-cropped"><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/images.jpg" alt="" data-id="324" data-link="http://localhost:81/wordpress/home-page/images/" class="wp-image-324"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/images-8.jpg" alt="" data-id="325" data-link="http://localhost:81/wordpress/home-page/images-8/" class="wp-image-325"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/images44.jpg" alt="" data-id="326" data-link="http://localhost:81/wordpress/home-page/images44/" class="wp-image-326"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/index.jpg" alt="" data-id="327" data-link="http://localhost:81/wordpress/home-page/index/" class="wp-image-327"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/maxresdefault.jpg" alt="" data-id="323" data-link="http://localhost:81/wordpress/home-page/maxresdefault/" class="wp-image-323"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:81/wordpress/wp-content/uploads/2018/08/maxresdefault9.jpg" alt="" data-id="322" data-link="http://localhost:81/wordpress/home-page/maxresdefault9/" class="wp-image-322"/></figure></li></ul>
<!-- /wp:gallery -->
```

**Comment by madavibr** [comment] 2018-09-01 16:01
It's not just in the gallery. Now any image inside the posts do not get more center, even checking in the code and seeing that there is aligncenter.
Left and Right is working normal but center does not work and the images are all left when I select aligncenter for the images.

**Comment by designsimply** [comment] 2018-09-06 17:34
Thank you for reporting this as a separate issue! I tested and confirmed using the following steps:

1. Add a gallery block with 3 or more images.
1. Check that the block settings have Columns set to 3.
1. Select "Align center" in the block toolbar.
1. Publish the post and view it on the front end.

<strong>Result:</strong> in the editor, selecting "Align center" doesn't change the appearance of a gallery with 3+ images and it shows images in 3 columns as expected while on the front end a centered gallery appears with images left-aligned in a single column.

![screen shot 2018-09-06 at 9 37 55 am](https://user-images.githubusercontent.com/1119271/45168655-11c52900-b1b9-11e8-89dc-a99d95c34778.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14823&action=edit running WordPress 4.9.8 and Gutenberg 3.7 using Firefox 61.0.2 on macOS 10.13.6.</sup>

![screen shot 2018-09-06 at 9 43 22 am](https://user-images.githubusercontent.com/1119271/45168871-93b55200-b1b9-11e8-91bd-c19e87d75503.png)
<sup>Seen at http://alittletestblog.com/2018/09/06/gallery-3/ running WordPress 4.9.8 and Gutenberg 3.7 using Firefox 61.0.2 on macOS 10.13.6. Note: also tested with WordPress 4.9.8 and Gutenberg 735ab8da2 (3.8-pre-release) with the same result.</sup>

> It's not just in the gallery. Now any image inside the posts do not get more center.

The problem with centering images was reported in #9503 and fixed in #9509 and you should be able to see the update working in 3.8 when it is released.

**Comment by nfmohit-wpmudev** [comment] 2018-09-07 16:47
Submitted #9694 which fixes this issue.

**Comment by karmatosed** [comment] 2018-10-11 21:11
To me this should work over need design feedback. Looks like a PR is underway so let's remove the design feedback label from this.

**Closed** 2018-10-15 12:51 UTC
Labels: Blocks, [Type] Bug
