### ISSUE TITLE
Internet Explorer 11 - using bold freezes/crashes the page

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#14383] opened 2019-03-12 05:45 UTC
**Describe the bug**
If you're using IE 11 (11.590.17134.0) when trying to use the Bold styling, the page freezes for a few seconds and refreshes.

**To Reproduce**
1. Try to add a post or page
2. Add a text you wish to bold
3. Click on the Bold button
4. It should be crash/freeze

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: IE 11 
 - Version 11.590.17134.0

**Comment by knuch** [comment] 2019-04-02 09:27
I had the same Behavior on a client machine (crash on bold usage), with the following complementary informations:

**Screenshots**
<img width="505" alt="Capture d’écran 2019-04-02 à 11 20 58" src="https://user-images.githubusercontent.com/4548432/55391494-c3eb8600-5539-11e9-8a63-89bffc535d28.png">
<img width="1251" alt="Capture d’écran 2019-04-02 à 11 27 04" src="https://user-images.githubusercontent.com/4548432/55391756-48d69f80-553a-11e9-9528-0a4e5639b2e2.png">

TinyMCE version: 
`// 4.9.2 (2018-12-17)`

**Desktop (please complete the following information):**
OS: Win 7
Browser: IE 11
Version 11.0.9600.19230

**Comment by krohn** [comment] 2019-04-15 06:02
Here, click on "bold" or "italic" in Gutenberg causes IE11 to crash. 
But: Writing in regular, marking a word and then click "bold" or "italic" works as expected. 
No issues in "classic block" of Gutenberg. No issues with Chrome.

OS: Windows Server 20112 R2
Browser: IE11 11.0.9600.19267
Wordpress 5.1.1

**Comment by jasmussen** [comment] 2019-08-27 09:57
I just tried this today in the latest version of the plugin, and can't reproduce this. It may have been fixed? Can someone else test and verify? Thank you!

**Comment by krohn** [comment] 2019-09-03 07:33
I'm back at that Windows-maschine mid of next week and can re-check.
Thanks for looking into it.

**Comment by Robertght** [comment] 2019-09-05 09:49
I tried to make it bold by using CTRL + B and it didn't crash but this is what I see now:

![image](https://user-images.githubusercontent.com/6737345/64330910-84d6ca80-cfda-11e9-81dc-57ddf79d6b1e.png)

So I'm unable to click on it because it's opening the alignment dropdown. Should I make a new report for this?

**Comment by jasmussen** [comment] 2019-09-05 09:57
I believe that dropdown should be fixed in the plugin version of Gutenberg. Are you using the plugin, or the WordPress release version of the editor? If the latter, you'll have to wait for WordPress to be updated.

**Comment by krohn** [comment] 2019-09-09 12:48
The Browser-Freeze seems to be fixed in my current environment (OS: Windows Server 20112 R2, Browser: IE11 11.0.9600.19362, Wordpress: 5.2.3).
The toolbar-icons are looking fine to me, too (but never had issues with them..).

No more issues on my side. Thank you!!

**Comment by jasmussen** [comment] 2019-09-09 12:51
Thanks for the reports. Closing as fixed, we can always reopen if need be.

**Closed by jasmussen** 2019-09-09 12:51 UTC
Labels: Browser Issues, Needs Testing
