### ISSUE TITLE
Selecting an inner block in Comment Template is unreliable and requires two clicks.

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/gutenberg#39510] opened 2022-03-16 16:23 UTC
### Description

The selection of inner blocks of the Comment Template sometimes requires two clicks and is unreliable.

When the block is inactive, and the user clicks on one of the inner blocks of one of the comments (e.g. Comment Date or Comment Content) the **first** click selects the Comment Template and only the **second** click selects the correct inner block.

~~Additionally, _occasionally_, the on the **second** click, the selection is not applied to the block that is being clicked on, but rather to the block that was **previously** selected.~~

### Step-by-step reproduction instructions

1. Go to Posts > Add New
2. Add some comments to the post
3. Add a Comments Query Loop Block - use the default Inherit option
4. Deselect the block and try to select one of the inner blocks of the Comment Template (Comment Date or Comment Content, for example)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5417266/158637584-a07722db-3a02-44f0-ba01-3f202409a9b8.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by DAreRodz** [comment] 2022-03-21 14:43
Hi @michalczaplinski 👋 , I've been taking a quick look at this issue and I have a couple of comments:

> When the block is inactive, and the user clicks on one of the inner blocks of one of the comments (e.g. Comment Date or Comment Content) the **first** click selects the Comment Template and only the **second** click selects the correct inner block.

What I see is that, by default, you can select the first comment's inner blocks ― i.e., when you hover the mouse over the comment's inner blocks, they are highlighted and selectable. Inner blocks of other comments are not selectable unless you click first on that comment (you would need two clicks in that case).

https://user-images.githubusercontent.com/6917969/159284191-8283cebd-f644-42a9-a75b-e85898266d2e.mov

The same exactly happens with Post Template, so my guess is that this is a more general issue rather than something comment-specific.

> Additionally, _occasionally_, the on the **second** click, the selection is not applied to the block that is being clicked on, but rather to the block that was **previously** selected.

If I'm not mistaken, this will be fixed once https://github.com/WordPress/gutenberg/pull/39472 is merged, am I right? The issue is not reproducible on that branch.

**Comment by michalczaplinski** [comment] 2022-03-21 17:43
> The same exactly happens with Post Template, so my guess is that this is a more general issue rather than something comment-specific.

yes, I have noticed that too - good catch 🙂 

> > Additionally, occasionally, the on the second click, the selection is not applied to the block that is being clicked on, but rather to the block that was previously selected.

You're right about that! I can't reproduce it anymore either 🤔 It's possible that I've tested it on the branch before adding the fix... Will remove that line from the issue description.

**Comment by kathrynwp** [comment] 2022-09-27 15:58
As it sounds like the issue was fixed a while back and no longer reproducible, I'm going ahead and closing this out.

**Closed as completed by kathrynwp** 2022-09-27 15:58 UTC
Labels: [Type] Bug, Needs Testing, [Block] Comment Template
