### ISSUE TITLE
Post date block: Transform to Post Modified Date

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52205] opened 2023-07-01 14:48 UTC
### Description

This issue describes two things, that are probably connected.

1. The Post date block should be transformable to the Post Motified Date via the transform option (instead of columns or Groups)
<img width="504" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/59a1a70e-aeae-4c40-a712-4ea41a9ae42c">

2. From the Group Block we know the behavior to transform blocks in the right sidebar on the top.
The post date block uses a different behavior: A toggle for "Display last modified date", which essentially transform the block. 
<img width="279" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/056e2a79-07d8-40f2-8393-a16d092f62aa">
<img width="276" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/43f287a6-df0b-4345-ad24-23dd6f70c5c7">

### Step-by-step reproduction instructions

1. Create a post date block
2. Try to transform it via the know UX patterns _or_
3. transform it via the toggle - a not so known (and not ideal) UX behavior

### Environment info

- WP 6.2.2
- GB 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment] 2023-10-26 07:41
This is a duplicate of #49584

**Closed as completed by fabiankaegy** 2023-10-26 07:41 UTC
Labels: [Type] Enhancement, [Block] Post Date
