### ISSUE TITLE
Cover image: full width not displayed correctly in page editor

### ISSUE THREAD

**Issue by uok** [WordPress/gutenberg#17010] opened 2019-08-12 14:13 UTC
After reloading the page in editor, the cover image is not displayed full width although it was set so before.

1. Insert cover image block
2. Select image and change to full width
3. Save
4. Later return to edit this page
5. Cover image is no longer displayed in full width but setting still exists. If you save again, cover remains full width on website.

WP 5.2.2
WooCommerce 3.6.5

**Comment by mapk** [comment] 2019-08-12 16:21
I just tested this out and didn't experience any problems. The Cover block remained at full-width when returning to edit the page.

Which theme are you using? I'm thinking it could be a theme issue.

**Comment by uok** [comment] 2019-08-13 09:18
Thanks for testing! I'm using regular Storefront theme, but afaik this theme does not affect the backend.

What I found: If you click any of the icons in the block toolbar, e.g. full with, the script sets `data-align="full"` on the block. On page load this attribute exists, but it is empty. So this could be the reason why it is not displayed correctly.

**Comment by youknowriad** [comment] 2020-01-15 09:37
Closing as we can't reproduce this. Let's reopen if we get more information about how to reproduce it.

**Closed by youknowriad** 2020-01-15 09:37 UTC
Labels: Needs Testing, [Block] Cover, [Feature] Themes, [Type] Help Request
