### ISSUE TITLE
Now it takes a lot of clicks to set a link to open in a new tab

### ISSUE THREAD

**Issue by jogpr** [WordPress/gutenberg#53463] opened 2023-08-09 09:50 UTC
I was shocked with this WordPress update.

Now to set a link to open it in a new tab you need to do a lot of clicks. This is hilarious.

I already mentioned, I don't know who makes these kind of decisions, but it seems that they don't use Wordpress on a daily basis.

For those who write a few posts sporadically this is not a problem, but for those who write daily it greatly increases the workflow.

This UX for setting a link to open in a new tab is terrible, it doesn't make any sense, I was stunned by it. Now I have a lot more work.

Please leave it as it was.

**Comment by Mamaduka** [comment] 2023-08-09 10:08
Duplicate of #52216. The issue was fixed in #52799 and should ship with Gutenberg 16.4.

**Comment by jogpr** [comment] 2023-08-09 11:08
@Mamaduka 
This answer leaves me even more stunned.

So a new feature is released without being ready?

Anyway, the problem is not solved with this PR, you still have to give a lot of clicks, it doesn't solve anything...

**Comment by Mamaduka** [comment] 2023-08-09 11:22
Sorry, that wasn't my intention.

#52799 wasn't ready for WP 6.3, but it might be included in the next minor release.

Happy to keep the conversation open for now.

cc @getdave, @richtabor

**Comment by richtabor** [comment] 2023-08-09 11:36
> So a new feature is released without being ready?

It's all iteration—this is a step towards allowing more controls within the link editing experience as requested often (https://github.com/WordPress/gutenberg/issues/13542 and https://github.com/WordPress/gutenberg/issues/23011). 

There's a long list of continued improvements/enhancements around linking holistically tracked in https://github.com/WordPress/gutenberg/issues/50891, but in particular https://github.com/WordPress/gutenberg/issues/50892, and https://github.com/WordPress/gutenberg/pull/52799 tidy this flow up a good bit. 

There shouldn't be so many steps between adding the link, then configuring it further (with even more options in the future).

**Comment by jogpr** [comment] 2023-08-09 11:43
Thanks for the answers. Sorry for my irritation, but the additional work I'm going to have with this new WordPress is very frustrating.

**Comment by richtabor** [comment] 2023-08-09 11:49
> Thanks for the answers. Sorry for my irritation, but the additional work I'm going to have with this new WordPress is very frustrating.

Really appreciate your feedback!

**Comment by richtabor** [comment] 2023-08-09 17:14
Closed as a duplicate of https://github.com/WordPress/gutenberg/issues/52216.

**Closed as completed by richtabor** 2023-08-09 17:14 UTC
Labels: [Status] Duplicate, [Feature] Link Editing
