### ISSUE TITLE
Add functionality to re-arrange document settings sidebar panels

### ISSUE THREAD

**Issue by lizkarkoski** [WordPress/gutenberg#9035] opened 2018-08-15 16:45 UTC
**Is your feature request related to a problem? Please describe.**
Pulling this feature request for Gutenberg in form the public forum. Here is the original thread: 
https://wordpress.org/support/topic/cant-rearrange-document-boxes/#post-10582857

**Describe the solution you'd like**
When a user has a large number of categories it will push the rest of the document box down the page. It'd be awesome if we could rearrange the order of that document box. In this scenario, you could have your categories at the bottom where they wouldn't bury any other menu items. 

> 1) I like to rearrange these boxes so that Status is at the bottom. That way, I am more likely to check all the other boxes have been completed correctly before hitting Publish.

> 2) I have a custom box that belongs right next to the Featured Image box, but it’s now stuck at the bottom of the list.

3) I have a lot of Categories. When the Categories box is open, everything else is pushed down off the screen. It would be less intrusive if I could put it near the bottom of the list.

**Comment by designsimply** [comment] 2018-08-15 18:55
Adding screenshots for reference:

![screen shot 2018-08-15 at wed aug 15 12 51 49 pm](https://user-images.githubusercontent.com/1119271/44167081-6b3eaa00-a08a-11e8-8dcb-c0eadce5eaf1.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14319&action=edit&classic-editor running WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 on macOS 10.13.6.</sup>

![screen shot 2018-08-15 at wed aug 15 12 51 37 pm](https://user-images.githubusercontent.com/1119271/44167076-67ab2300-a08a-11e8-9e82-622ccabe64d7.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14319&action=edit running WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 on macOS 10.13.6.</sup>

**Comment by paaljoachim** [comment] 2021-06-20 19:23
@vdwijngaert Koen 

I happen to come across this interesting issue from 2018. Perhaps this is something for you to take a closer look at?

**Comment by mtias** [comment] 2021-07-13 11:59
Closing as we have no current plans for supporting manual reordering. Improvements to long running panels should still be addressed in different ways and remember collapsing state.

**Closed by mtias** 2021-07-13 11:59 UTC
Labels: [Feature] Document Settings, [Feature] Extensibility, [Type] Enhancement

**Comment by ShahriarKh** [comment] 2022-10-10 10:41
If it's not going to be supported yet, Is it possible to change the order with a plugin or something?
I know it's possible with some tweaks in css:
```css
.components-panel {
    dispaly: flex;
    flex-direction: column;
}

.components-panel__body .yoast-seo-sidebar-panel {
    order: 2; /* changing the order in flex container */
}
```
The problem is all native boxes only have the `.components-panel__body` class and I can't find a way to distinguish them.

**Comment by madfcat** [comment] 2023-08-03 21:24
Right now[ the only possible way ](https://stackoverflow.com/questions/63991199/how-to-fix-the-position-of-the-advanced-panels-in-wordpress-gutenberg-editor)is

1 – install classic editor
2 – drag the panels where you want and save
3 – remove the classic editor

then open a post in gutenberg to see the panels finally in place.

**Comment by CodingSamurai** [comment] 2023-09-25 21:10
Agree that if you're not going to allow custom ordering as a built in feature then the current panels need to be UNIQUELY identifiable so that customization can be done manually or a plugin could be built to do this functionality.

**Comment by rfischmann** [comment] 2024-01-03 16:26
I must add that it's very weird that this isn't a native feature inside of Gutenberg. I thought I was losing my mind until I found this topic.

**Comment by CodingSamurai** [comment] 2024-01-03 17:00
@mtias can't we re-open this and at LEAST get unique IDs or class attributes for each of the boxes?  or should we open that as a separate issue.
