### ISSUE TITLE
The Gutenberg demo page is broken. Chrome, OS X, Dec 10th 2018

### ISSUE THREAD

**Issue by x1024** [WordPress/gutenberg#12772] opened 2018-12-10 19:46 UTC
https://wordpress.org/gutenberg/

Simply opening the page reproduces the issue for me.
OS: Mac OS, Mojave
Browser: Chrome 72
Notable plugins: uBlock

In incognito mode, I don't even get the blocks themselves - just editable code blocks. No JS or CSS seems to be loading.
<img width="1392" alt="screenshot 2018-12-10 at 20 51 55" src="https://user-images.githubusercontent.com/113459/49757309-cbee9400-fcc4-11e8-988b-497ee83841fa.png">

When logged-in to wordpress.org, I see the editor but there are style issues - most notably, the call-to-action buttons feature black text on a dark blue background.

<img width="1392" alt="screenshot 2018-12-10 at 20 52 10" src="https://user-images.githubusercontent.com/113459/49757308-cbee9400-fcc4-11e8-9292-29acb84c3820.png">

I showed this page to a client in an attempt to explain what's new in WordPress 5.0 (this is the first result when googling "wordpress gutenberg"). I think they're not ready to upgrade just now.

**Comment by realworldev** [comment] 2018-12-10 20:46
> I showed this page to a client..

Same here a few hours ago, pretty embarrassing.

![gutenberg-fail](https://user-images.githubusercontent.com/45342592/49760487-e6c10880-fcc4-11e8-9e44-4d2d51c35c8d.png)

**Comment by swissspidy** [comment] 2018-12-10 22:09
Is this still happening to you? The page works just fine for me.

Please note that the #meta Slack channel or meta.trac.wordpress.org is better suited for reporting problems related to https://wordpress.org/gutenberg/.

**Comment by x1024** [comment] 2018-12-10 22:17
Unfortunately, the "just boxes, no JS/CSS" issue still happens. Notably, when I refresh the page in incognito, the demo works. But the first time the page is loaded, it's broken.   
When I tried this several times just now, it only reproduced maybe half the time. So perhaps a distributed cache/cdn needs to be flushed? I'll be around in 8-10 hours to try it again.

I can also still reproduce the "black text on dark blue button" issue when I'm logged-in, this time with 100% consistency.

**Comment by Otto42** [comment] 2018-12-10 23:23
The "black text on dark blue button" is actually in the content. Not a bug. Maybe not the prettiest, but not a bug.

And I can't reproduce the issue. I mean, I can, if I block some of the scripts from loading or otherwise intentionally pause execution at the right time, but I'm not getting any case where it just happens.

When it does happen, what scripts are missing or broken?

**Comment by dd32** [comment] 2018-12-11 00:01
Currently looking into this, it's not immediately obvious what the cause is, but I suspect I know what's causing it

**Comment by dd32** [comment] 2018-12-11 00:46
This was related to 278b32204ddf63a3c7022ce42145137131a44e4b I think, but i suspect there's something else at play too, either way, the page which was cached had `richEditingEnabled` set to `false` which is why it was disabled.

https://meta.trac.wordpress.org/changeset/7970 has forced it on, even if the browser doesn't support richEditing - which does mean that https://wordpress.org/gutenberg/ may now break in old browsers.

I think we'll need to add some logic that replicates the UA checking done in https://core.trac.wordpress.org/browser/trunk/src/wp-includes/general-template.php?marks=3087-3093#L3063 as currently there's a hard dependancy on IE10+ (although I don't think 10 is actually supported) which results in a white-screen in those older browsers.

I'm going to close this and migrate over to a meta ticket for the remaining:  https://meta.trac.wordpress.org/ticket/3992

**Closed by dd32** 2018-12-11 00:46 UTC
Labels: [Status] Needs More Info

**Comment by dd32** [comment] 2018-12-11 01:05
Additionally, the button styling has been fixed in https://meta.trac.wordpress.org/changeset/7972
