### ISSUE TITLE
Customizer auto refresh moves cursor to form field on page

### ISSUE THREAD

**Issue by kelliwise** [WordPress/gutenberg#9172] opened 2018-08-20 16:41 UTC
**Describe the bug**
I have an embedded iframes form in a widget area on my page. In the Customizer, when I try to add a text widget to another widget area on the site, as the screen refreshes with my edits, the cursor jumps to the first input field on the embedded form. If I'm not watching carefully, my edits are not typed into the text widget, they are typed into the form field. Gutenberg Version 3.6.2

**To Reproduce**
1. Add iframes login form
2. Go to 'Customizer.'
3. Click on 'Widgets'
4. Add a text widget to any of your widget areas
5. Start typing in text widget title or body
6. Wait for live update to occur
7. See that cursor is now in the first login form input field

**Expected behavior**
That the cursor would remain in the widget being edited.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 68.0.3440.106

**Additional context**
- Please add the version of Gutenberg you are using in the description. - done
- This is a screen shot of what the iframes login form looks like in the Customizer window
![2018-08-20 09 35 19 am](https://user-images.githubusercontent.com/1483830/44353838-14a3e800-a45d-11e8-9ba9-005dab509af6.jpg)

**Comment by designsimply** [comment] 2018-08-20 18:43
Would it be possible to reply with the `iframe` code you are using for reference?

**Comment by kelliwise** [comment] 2018-08-20 18:50
`<IFrame height="200px" width="400px" src=" https://hbStage.onlineaccounts.org/Olympia1262WA/HBNet/App/signon/tetheredframeloginentry" allowtransparency="true" frameborder="0" marginwidth="0" marginwidth="0" title="Home Banking Login" /></iframe>`

This is an iframe for staging and not the production login form. Used for testing the system without triggering any security measures, since it's a banking login.

**Comment by designsimply** [comment] 2019-01-29 00:11
Apologies for the delay in reply! Hopefully you've already resolved or worked around the problem and I am writing now because I've had time to loop back around to testing and wanted to post about what I've found.

First, when adding the `iframe` code you provided, I found that I was unable to save it without first correcting three errors in the syntax:

1. The html element name of [ IFrame ] must be in lowercase.
2. Duplicate of attribute name [ marginwidth ] was foud. 
3. Tag must be paired, no start tag: [ </iframe> ]

Next, I updated the `iframe` code to the following and was able to successfully add it to a Custom HTML widget after that:

```
<IFrame height="200px" width="400px" src=" https://hbStage.onlineaccounts.org/Olympia1262WA/HBNet/App/signon/tetheredframeloginentry" allowtransparency="true" frameborder="0" marginwidth="0" marginwidth="0" title="Home Banking Login" /></iframe>
```

```
<iframe height="200px" width="400px" src=" https://hbStage.onlineaccounts.org/Olympia1262WA/HBNet/App/signon/tetheredframeloginentry" allowtransparency="true" frameborder="0" marginwidth="0" title="Home Banking Login"></iframe>
```

Here are the results of my test: [2m27s](https://cloudup.com/ct60x9ShvfH).
<sup>Tested with WordPress 5.0.3 and no active plugins using Chrome 71.0.3578.98 on macOS 10.13.6.</sup>

You may have used a widget other than Custom HTML to add the iframe and that could have made a difference or it's possible the problem had been resolved in an update somewhere between now and the time of your original report. 

I would like to close this issue since I was unable to reproduce the problem in testing and because several updates have been made since that time. If you are still having any trouble with this, please check my test and let me know where you are getting stuck and I will see any reply you add here in my notifications and can re-open the issue if I've missed anything. Thank you!

**Closed by designsimply** 2019-01-29 00:11 UTC
Labels: Needs Testing, [Type] Help Request
