### ISSUE TITLE
Removing the first block from the List View breaks UI

### ISSUE THREAD

**Issue by delowardev** [WordPress/gutenberg#38763] opened 2022-02-12 16:24 UTC
### Description

If you remove the first item/block from the "List View" using **BACKSPACE** it breaks the UI and shows an error to the console.

The error message is: `TypeError: Cannot read properties of null (reading 'title')`

### Step-by-step reproduction instructions

1. Open List View
2. Remove the first block using the keyboard ( BACKSPACE )

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17360543/153719207-fc18a77f-2fd5-4e7b-9172-b216562a3e3c.mov

![Screen Shot 2022-02-12 at 10 13 35 PM](https://user-images.githubusercontent.com/17360543/153719438-c1f67ac0-4225-4c5f-9f00-13b8d3ffc1ec.png)

### Environment info

- Gutenberg: 12.6.0-rc.1
- WordPress: 5.9
- Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2022-02-14 02:52
It doesn't seem to happen all the time, but I was able to reproduce it a few times. This is the line that causes the error
https://github.com/WordPress/gutenberg/blob/9543b72e701a452858b1434977275bc3fbf3a8bd/packages/block-editor/src/components/list-view/block.js#L152

`blockInformation` can be `null` so it makes sense to guard against that. I'll make a PR to fix it.

**Comment by delowardev** [comment] 2022-02-14 03:25
@talldan It never happens if we remove the first block from the dropdown menu, maybe it's worth debugging a little further?

https://github.com/WordPress/gutenberg/blob/6b4b8c45b9cfdb1a46869cdc92a2226b9a71ef0d/packages/block-editor/src/components/list-view/index.js#L70-L74

Here I noticed a different behavior in `clientIdsTree` for the Backspace key & Dropdown remove button, it may help further debugging:

`console.log(clientIdsTree)`

* After removing any block using Backspace from the list view, it logs `clientIdsTree` three times; first time with old IDs tree and 2nd & 3rd time with new IDs tree. (I assume that error happens when it renders with old IDs tree)
* But if we remove a block from the dropdown menu, it logs only new `clientIdsTree` once

**Comment by delowardev** [comment] 2022-02-14 03:37
https://user-images.githubusercontent.com/17360543/153796088-421caee4-e511-413a-80f8-2be12f09cbf2.mov

**Comment by talldan** [comment] 2022-02-14 03:50
@delowardev I've made a PR here to prevent the error - https://github.com/WordPress/gutenberg/pull/38775

**Comment by talldan** [comment] 2022-02-14 04:25
I had a look to see if I could understand what the root cause might be.

It might be another issue like this previous bug - https://github.com/WordPress/gutenberg/issues/29498. The problem is that the inner `useSelect` (inside `useBlockDisplayInformation`) is called before the outer `useSelect` (in `useListViewClientIds`). 

It looks like what happens is a `clientId` for the deleted block is passed to `useBlockDisplayInformation`. That clientId no longer exists in the store. `useBlockDisplayInformation` returns `null` because it can't get the block type for that deleted block and there's no code in List View for handling a `null` value.

https://github.com/WordPress/gutenberg/issues/29498 was fixed by handling errors differently in `useSelect` (https://github.com/WordPress/gutenberg/pull/32088). The thing here is that `useBlockInformation` doesn't throw an error, instead it returns `null` and expects the code that called the hook to handle that value.

**Closed as completed** 2022-02-14 07:49 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] List View
