### ISSUE TITLE
Incorrect permalinks being generated when saving

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#11229] opened 2018-10-30 05:22 UTC
**Describe the bug**
I created a new page called "Gutenberg Blocks", copied in some sample blocks from another site, and when I saved, I ended up with a permalink that didn't have my page name, but instead was called `__trashed`.

![screenshot_905](https://user-images.githubusercontent.com/2078245/47697412-12c98280-dc5f-11e8-985c-dc924a25dd92.png)

**To Reproduce**
1. Create new Page
2. Add Title
3. Switch to Code Editor
4. Copy in some generic sample blocks
5. Switch to Visual Editor
6. Save page

**Expected behavior**
Permalinks should contain Page/Post title, as expected

**Desktop (please complete the following information):**
- OS: macOS Sierra 10.12.6
- Browser: Firefox Quantum 63.0 (64-bit)
- Version: WP 5.0 Beta 1

**Comment by earnjam** [comment] 2018-10-30 16:17
I'm not able to replicate this at the moment, though I'm pretty sure I remember running into something like this a week or two ago. 

Do you have any more information that could help in replicating this?

**Comment by maddisondesigns** [comment] 2018-10-31 02:49
I don't have lot of information, sorry. As mentioned above, all I did was created a new page, switched to the Code Editor, copied in some standards blocks from a test page on another site, and then tried to publish and preview.

**Comment by kriskarkoski** [comment] 2018-11-16 18:13
I experienced something similar yesterday. It wasn't __trashed, but I updated the title, emptied the permalink, and when it autocompleted it used the previous version of the title instead of the new one. I'll try to capture the flow if I can reproduce it consistently.

**Comment by maddisondesigns** [comment] 2018-11-29 03:07
I know that I definitely didn't send my post to the trash (and/or subsequently restore it). All I did was created a new page, copied in some content and then saved the page.

**Comment by designsimply** [comment] 2018-11-30 21:46
Adding `Needs Testing` to see if we can get more eyes on this.

@maddisondesigns have you noticed this problem is persistent even after updating to later betas or the RC or was it a super rare case in your experience?

**Comment by maddisondesigns** [comment] 2018-12-01 01:59
@designsimply It's been fairly rare. It's not something I've been able to reproduce consistently, unfortunately.

**Comment by designsimply** [comment] 2018-12-18 01:42
I tested with WordPress 5.0.1 and Gutenberg 4.7.0 `master` @ `ddac4f3cf` today and found that I can see `__trashed` in the permalink for any draft restored from the trash (published posts do not seem to have the same problem).

Steps to reproduce:

1. Go to Settings > Permalink, choose an option that includes `%postname%`, and save changes.
1. Go to Posts > Add New.
1. Add a title and some content.
1. Click "Save Draft."
1. Click Settings > Document > "Move to trash".
1. Go to Posts > Trashed and click "Restore" below the post.
1. Check the permalink for the post.

<strong>Result:</strong> `__trashed` is appended to the slug for drafts restored from the trash. ([42s](https://cloudup.com/c61OudsQP9z))

![screen shot 2018-12-17 at 6 30 51 pm](https://user-images.githubusercontent.com/1119271/50126398-f5aa3c80-0229-11e9-950b-af9be487a566.png)
<sup>Tested with WordPress 5.0.1 and Gutenberg 4.7.0 `master` @ `ddac4f3cf` using Firefox 63.0.3 on macOS 10.13.6.</sup>

I also found that it happens even if you trash and restore the post from outside Gutenberg ([29s](https://cloudup.com/cF8LJD2GZiK)), and I would like to close this issue in favor of  https://core.trac.wordpress.org/ticket/40588

@maddisondesigns even though you mentioned you think you definitely didn't send your post to the trash then restore it but also that the problem appears fairly rarely for you, the issue isn't really actionable unless we get more reports or find better steps for replicating the problem. Since we do have something actionable in https://core.trac.wordpress.org/ticket/40588 I would like to close this issue in favor of that one and re-visit your case once the restored drafts problem has been fixed in core. I will also keep an eye out for additional reports that do not involve `__trashed` appearing in the slug for posts which have not been restored from the trash.

**Closed by designsimply** 2018-12-18 01:42 UTC
Labels: [Component] Permalink, [Type] WP Core Bug

**Comment by coreyworrell** [comment] 2020-05-23 00:32
Could this be related to this? (saving nav menu caused it in this case): https://wordpress.org/support/topic/wordpress-permalinkslug-changed-page-to-page_trashed/
