### ISSUE TITLE
Add Block Icon double 

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/gutenberg#17416] opened 2019-09-12 15:03 UTC
![Bildschirmfoto 2019-09-12 um 17 00 32](https://user-images.githubusercontent.com/15845265/64795879-14eab600-d57f-11e9-8bf9-f268d06c2e4a.png)

I use the new version of the Gutenberg Plugin and the new Default 
Twenty Nineteen Theme. Why we need double add Icons? :D 

The double icon comes if I hover on the content. 

![Bildschirmfoto 2019-09-12 um 17 05 06](https://user-images.githubusercontent.com/15845265/64796108-7f9bf180-d57f-11e9-8be2-90926fe9ce33.png)

**Comment by HardeepAsrani** [comment] 2019-09-20 15:50
Hey,

That icon is there to allow you to insert a block on top of your current block, giving you a way to insert blocks before the block. As a user, it does seem that there is an option to add a block before an empty block, but technically it's giving you an option to add a block before the default Paragraph block. :)

**Comment by BenjaminZekavica** [comment] 2019-09-20 19:13
Oh ok :D  Close :)

**Comment by HardeepAsrani** [comment] 2019-09-20 20:28
I tried to mess around and found it a bit irritating too, so I've fixed it and sending a PR. Would be great if you could re-open this issue? @BenjaminZekavica  :)

**Comment by HardeepAsrani** [comment] 2019-09-21 13:51
This should fix it: https://github.com/WordPress/gutenberg/pull/17508 @BenjaminZekavica Feel free to try and improve if you see anything missing. :)

**Comment by BenjaminZekavica** [comment] 2019-09-21 13:55
:) Fantastic I think it's now better!

**Comment by HardeepAsrani** [comment] 2019-09-21 13:56
You shouldn't close the ticket until the PR is merged/rejected, as the issue is not solved until the PR is addressed, either positively or negatively :D

**Closed** 2020-07-24 19:10 UTC
Labels: [Feature] Inserter
