### ISSUE TITLE
Image block image sizes do not appear to use media setting sizes

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#30504] opened 2021-04-05 14:08 UTC
## Description
Unsure if this is supposed to happen, but when using the dropdown options for image size in the image block if you select thumbnail it sets the image size to 150x150. In media settings my thumbnail size is 300x300. Are the sizes within the block unique to that block in Gutenberg or should they use the media settings thumbnail size?

## Step-by-step reproduction instructions

1. Set your WordPress media settings to be 300x300 for thumbnails
2. Create a page
2. Add an image block
3. Select an image
4. Select a different image size (as thumbnail will be selected even though it is not the thumbnail, see bug below)
5. Go back and select the thumbnail size
6. Image will be 150x150 even though thumbnails in media settings is 300x300
7. Just as a test I also regenerated all thumbnails with no change.

Note that there is an issue when adding the image at the option is set to "Thumbnail" even though it is the full size image, to select a thumbnail size you need to select any other image size, then go back and select thumbnail https://github.com/WordPress/gutenberg/issues/27198 https://github.com/WordPress/gutenberg/issues/21681

## Expected behaviour
Thumbnail sizes set here match the thumbnail size set in WordPress media settings.

## Actual behaviour
Thumbnail gets set to 150x150 disregarding the thumbnail size from WordPress media settings.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Ubuntu 20.04
- Browser: Chrome 89

**Comment by skorasaurus** [comment] 2021-04-12 17:22
Hi, 
Thanks for reporting. 

I'm unable to reproduce the condition that you reported using Gutenberg 10.3.2 plugin. 
Could you confirm that you're experiencing this when you have the Gutenberg plugin installed? 

Also, in step 4, did you upload a new image or did you select an image from the media gallery? (I uploaded a new image)

**Comment by ninetyninew** [comment] 2021-04-13 16:45
I am using the editor in WP 5.7 - no Gutenberg plugin. Number 4 I have tried both an existing and new.

**Comment by skorasaurus** [comment] 2021-04-13 17:06
I'm not able to reproduce this in WordPress 5.7 with and without the gutenberg plugin enabled. 

See this video where the thumbnail being generated is 300x300 as expected. Perhaps I'm not following your steps to reproduce correctly.

https://user-images.githubusercontent.com/955351/114592067-8b1e3580-9c58-11eb-8281-4d8ecec7f313.mp4

**Comment by ninetyninew** [comment] 2021-04-13 17:57
What happens if you now change your thumbnails back to 150x150 in the media settings and then edit this page, then:

Does the image remain 300x300?
If you add the same image in a new image component and select the thumbnail option then what size is the image?

**Comment by skorasaurus** [comment] 2021-04-14 14:41
When I change my thumbnails back to 150x150 in the media settings then edit that published page; the existing image's thumbnail remains 300x300 in the editor.

When I create a new image block and select that same image from the media library, the thumbnail is still 300x300. 

When I create a new image block and upload a new image, the thumbnail is 150x150. 

This is expected because: 
When an image is first uploaded into WordPress' Media Library, WordPress will create additional copies of the same image at different dimensions based on the WordPress' media settings and on a theme's settings **at the time of the upload**. 

To automatically change the dimensions of an image after the image has been upload is not yet possible unless you install additional plugins. There is an existing ticket requesting this functionality in core WordPress at https://core.trac.wordpress.org/ticket/34223

**Comment by annezazu** [comment] 2021-05-17 20:33
Based on @skorasaurus's great replies, I'm going to go ahead and close this issue out since the related functionality has already been reported in Core WordPress. As always, feel free to re-open!

**Closed as completed by annezazu** 2021-05-17 20:33 UTC
Labels: [Feature] Media, Needs Testing
