### ISSUE TITLE
Paragraph block: When more than one link is present, incorret URL is shown when editing

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#22575] opened 2020-05-22 23:17 UTC
When two links are present in a paragraph block, editing the URL of the second one shows me the wrong URL.

I first saw this on one of the make.wordpress.org blogs:

![2020-05-22 16-01-26 2020-05-22 16_02_30](https://user-images.githubusercontent.com/3276087/82715147-76f3d300-9c57-11ea-973a-a5f2cfaf371f.gif)

... but was also able to reproduce on tip of master:

![2020-05-22 16-04-17 2020-05-22 16_05_01](https://user-images.githubusercontent.com/3276087/82715150-7b1ff080-9c57-11ea-896a-a0eb102d0a6b.gif)

You'll notice on the gifs above, that when I try to edit the URL of the second link, the link popover shows the URL of the first link.

**To reproduce**
1. Create a paragraph block with two different links in it
2. Click on the second link and select 'Edit'
3. Notice the URL that appears in the link's URL field

**Expected behavior**
Each link should show the correct URL when attempting to edit.

**Comment by skorasaurus** [comment] 2021-07-20 16:23
Hi,  

I'm not able to reproduce on Gutenberg 11.0 and I'd think this issue would have numerous comments if it were an issue; closing. Please reopen if you're still experiencing this.

**Closed by skorasaurus** 2021-07-20 16:23 UTC
Labels: [Block] Paragraph, [Feature] Link Editing
