### ISSUE TITLE
Chrome: Cannot scroll while dragging a block from the inserter

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#28790] opened 2021-02-05 15:24 UTC
## Description

In Chrome:
If a page has a lot of content and a scrollbar is visible, 
I cannot select a block or pattern in the inserter and drag it up or down the page past the visible content.
If I start at the top of the page, I can not drag the block to the bottom part of the page, the page does not scroll.

Sometimes it is possible to drag the block on the side of the content, but not if the content has a full width block.

The result is the same in the block editor and site editor.

In Firefox, I can drag the block or pattern over the content and the page will scroll correctly.

## Step-by-step reproduction instructions

1. Open an existing post in the editor, or create a new one.
2. Make sure that there is plenty of content so that the page is long enough to display a scrollbar.
3. Scroll to the top of the page.
3. Open the Inserter.
4. Select a block, and drag it to the bottom of the page.
5. Confirm whether or not it was possible to drag it to the bottom and place it last.

## Expected behaviour

I expect the page to scroll, and I expect it to be easy to drag a block from the inserter to the bottom of the page.
See the clip from Firefox for the expected behavior.

## Actual behaviour

The page does not scroll past the content, I can not place the block at the bottom of the page.

## Screenshots or screen recording (optional)

Chrome:
https://user-images.githubusercontent.com/7422055/107052367-d84fd800-67cd-11eb-9f8e-a55754f53710.mp4

Firefox:
https://user-images.githubusercontent.com/7422055/107052778-590ed400-67ce-11eb-8301-958fc3ffda04.mp4

## WordPress information
WordPress version: 5.7-beta1-50172
Gutenberg version: Master branch: 1f1bcc6
Are all plugins except Gutenberg deactivated? No, the beta tester plugin is installed
Are you using a default theme (e.g. Twenty Twenty-One)? Yes, and, TT1 Blocks version 0.4.3

##Device information
Device: Desktop
Operating system: Windows 10
Browser: Chrome 88.0.4324.104, Firefox 85.0

**Comment by carolinan** [comment] 2021-02-08 07:48
This was mentioned by a user while testing 5.7 beta during a contributor day on February 5:

It would be nice if you can also use the scroll wheel of your mouse to scroll while dragging a pattern or block.
Browser: Google Chrome - Version 88.0.4324.96
Operating system: macOS Catalina - Version 10.15.7

**Comment by joshm33333** [comment] 2021-03-27 23:03
can i just add, i've been using gutenberg, along with my team of developers, for almost 2 years now, for over 50 clients.
every single one of my team members agrees, the drag and drop scrolling behavior is bad

    1. click and drag, move mouse to desired target area
    2. wait for screen to scroll (which is very slow cause theres so much html and javascript going on)
    3. do a little dance with my mouse to make the screen STOP scrolling
    4. release mouse, and 4 out of 5 times, i miss, even thought the blue line was clearly where i wanted it, because of the painful delay, i often miss anyway
    
just saying, that's how bad it is to move something to something that is ON SCREEN, nevermind moving to something that requires scrolling. if i have to scroll, i dont bother, i just copy and paste cause its 10x faster

maybe its because of the theme im using, causing it to be slow, and maybe when it's not slow it's actually useful
but i was taught in school that you should never create "animations" that are **required** for functionality, otherwise you alienate all your users with slow computers. its a major accessibility issue.

**Comment by Mamaduka** [comment] 2024-03-20 07:18
I think this is a duplicate of #23491.

Also, I can no longer reproduce the issue with the scroll wheel.

**Comment by ellatrix** [comment] 2024-07-11 09:31
@carolinan Can you still reproduce this? Even so, let's close in favour of #23491 and discuss it there further.

**Closed by ellatrix** 2024-07-11 09:31 UTC
Labels: [Type] Bug, Browser Issues, [Feature] Drag and Drop
