### ISSUE TITLE
Highlight text: Color of highlighted text is not preserved when setting text color in the text block

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#41462] opened 2022-05-31 16:07 UTC
## Description

On a text block (e.g. Paragraph block) setting a text color changes the color displayed for all its content, including the parts that are highlighted with a different color. This behavior differs from the web version of the editor.

## Step-by-step reproduction instructions

1. Add a Paragraph block.
2. Type some text.
3. Select a word.
4. Tap on the Highlight text format button located in the toolbar (i.e. the `(A)` button).
5. Select a color different from the currently displayed.
6. Observe that the selected text is displayed with the color picked.
7. Tap on the ⚙️ button.
8. Tap on "Text" button.
9. Select a color different from the currently displayed.
10. Observe that all text is displayed with the color picked, including the previously highlighted.

## Expected behaviour

The highlighted text should preserve its color when setting text color to the text block.

## Actual behaviour

The color of highlighted text is not preserved when setting text color to the text block.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/171218729-2496e4df-99d8-46c9-986b-7214b026da25.mp4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 13 (simulator)
- Operating system: iOS 15.4
- WordPress app version: `trunk`

**Comment by SiobhyB** [comment] 2023-12-20 17:52
Tested and confirmed I could reproduce this on iOS in the latest version of the app (23.8.1). The issue is _not_ reproducible on Android.

**Comment by geriux** [comment] 2024-01-12 11:21
I have a fix for this that I'm working on currently so I'll remove the High priority label.

**Closed as completed** 2024-03-21 15:30 UTC
Labels: [Type] Bug, Mobile App - i.e. Android or iOS, [Feature] Colors
