### ISSUE TITLE
Broken "Improve on GitHub" links in Handbook

### ISSUE THREAD

**Issue by hirasso** [WordPress/gutenberg#57630] opened 2024-01-07 15:36 UTC
### Description

On https://developer.wordpress.org/block-editor/, the links on every page "Improve it on GitHub" contain an empty `href` attribute. I wasn't able to find the related repository, so leaving this note here. Can someone move it to the correct repo? Thanks 🙏

### Step-by-step reproduction instructions

1. Go to one of the handbook subpages, [Extending the Query Loop block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/) for example
2. Scroll down to the link "Improve on GitHub"
3. Click it (page reloads as the `href` is empty)

### Screenshots, screen recording, code snippet

![CleanShot 2024-01-07 at 16 31 49@2x](https://github.com/WordPress/gutenberg/assets/869813/99f19862-7b07-424c-873d-7b29ba9d0f74)

![CleanShot 2024-01-07 at 16 32 52@2x](https://github.com/WordPress/gutenberg/assets/869813/a2ec73b0-92a5-4573-9e8e-990c994d318a)

### Environment info

n/a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by skorasaurus** [comment] 2024-01-07 16:14
Hi, 

Thanks for reporting with the clear screenshot and information; I think this is the correct place for the issue.

**Comment by ramonjd** [comment] 2024-01-07 22:00
Could this be a duplicate of https://github.com/WordPress/wporg-developer/issues/438

cc @ndiego 

I couldn't find a corresponding file in the Gutenberg repo.

I think we can close this issue in favour of the one above or it could be moved to https://github.com/WordPress/Documentation-Issue-Tracker/issues.

**Comment by hirasso** [comment] 2024-01-08 08:39
@ramonjd I can't tell if it's a duplicate, since I can't log in to the handbook. But it sure looks related. Feel free to close/move this as you see fit.

**Comment by skorasaurus** [comment] 2024-01-08 16:28
thanks; this does appear to be a duplicate of https://github.com/WordPress/wporg-developer/issues/438. 

Thank you again for reporting @hirasso

**Closed as completed by skorasaurus** 2024-01-08 16:28 UTC
Labels: [Type] Bug, [Type] Developer Documentation, [Status] Duplicate
