### ISSUE TITLE
ColorPalette: Custom color picker is wrong positioned

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8558] opened 2018-08-05 20:40 UTC
**Describe the bug**
When rendering a `ColorPalette` component outside Gutenberg, the custom color picker is wrong positioned. 

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components` and `@wordpress/compose`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { ColorPalette } from '@wordpress/components';
import { withState } from '@wordpress/compose';

import '@wordpress/components/build-style/styles.css';

const MyColorPalette = withState( {
	color: '#f00',
} )( ( { color, setState } ) => { 
	const colors = [ 
		{ name: 'red', color: '#f00' }, 
		{ name: 'white', color: '#fff' }, 
		{ name: 'blue', color: '#00f' }, 
	];
	
	return ( 
		<ColorPalette 
			colors={ colors } 
			value={ color }
			onChange={ ( color ) => setState( { color } ) } 
		/>
	) 
} );

ReactDOM.render(
	<MyColorPalette />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
The custom color picker should be displayed below the custom color icon.

**Screenshots**
![screen shot 2018-08-05 at 22 37 25](https://user-images.githubusercontent.com/1233880/43689826-2f834df4-9900-11e8-9bab-d2a94f32d381.png)

**Desktop:**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by mtias** [comment] 2018-10-27 21:34
Closing as duplicate of #8559.

**Closed by mtias** 2018-10-27 21:34 UTC
Labels: UI Components, [Package] Components, [Type] Bug
