### ISSUE TITLE
Tips: status should be user-based not browser-based

### ISSUE THREAD

**Issue by folletto** [WordPress/gutenberg#8052] opened 2018-07-19 14:01 UTC
![screen shot 2018-07-19 at 14 46 29](https://user-images.githubusercontent.com/4389/42947016-4151035e-8b64-11e8-8cab-2f536eb45ffb.png)

While reviewing tips I was informed that to try a new one I had to clear my local data (related: #8051 about triggering it via URL). Which seems pointing out that the flags to trigger tips are local to the browser.

However, it doesn't make sense that a specific user have to get new tips every time they switch browser or device or profile. These kinds of informations are designed to be provided to each person once, and as such they shouldn't be repeated (unless requested by the user).

Suggestion:

* Store the tips "dismissed" status per-user

**Comment by afercia** [comment] 2018-07-26 07:16
As far as I know, technically it's already stored on a per-user basis, but just in the browser's local storage :) It should be saved in the DB.

Worth noting many other preferences are stored just in the browser, for example:
- sidebar state
- sidebar panels toggled state 
- fixed toolbar
- editor mode
- plugins pinned items
- etc.

That means the same user will see different UI settings when logging in with a different browser. So I guess the actual issue is a bit broader... 😉

**Comment by JJJ** [comment] 2018-10-18 15:09
>That means the same user will see different UI settings when logging in with a different browser. So I guess the actual issue is a bit broader

I agree. I expect all of those preferences to follow my account around, not my browser.

**Comment by aduth** [comment] 2020-02-27 18:16
Thanks for the report. While I had created it after this one, the issue at #15105 contains the actionable technical implementation related to this task. I will close this to consolidate discussion.

See also: #19177

**Comment by aduth** [comment] 2020-02-27 18:16
Duplicate of #15105

**Closed by aduth** 2020-02-27 18:16 UTC
Labels: Needs Dev, [Feature] NUX, [Type] Enhancement
