### ISSUE TITLE
Image style issue in Gutenberg's gallery block

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#38481] opened 2022-02-03 11:08 UTC
### Description

I created a page on my local site and added a Gutenberg block of the gallery to that page. I added images to that block. When I clicked on an image, went to its settings and changed the style to 4 image style options. If any one of them was selected, then it was working perfectly.

But when I was selecting the style of the image from the style drop-down, it is not working.

### Step-by-step reproduction instructions

1. Go to Website Dashboard
2. After that create any one page
3. Add gallery Gutenberg block to your page
4. Add images to gallery Gutenberg block
5. Then select on any one image and go to its settings
6. Then change the style of the image from the style drop-down in the style setting of the image.
7. Image style won't change

### Screenshots, screen recording, code snippet

please watch this video.

[https://www.loom.com/share/35aaec7e305e40a7ad4fbc9b68964dc6](url)

### Environment info

- WordPress Version 5.9, Gutenberg version 10.8-11.9, Active theme Twenty Twenty-One
- I am using the google chrome browser
- I am using mac laptop

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-02-03 12:09
Hi!
This is working as intended, the settings have different purposes:
The select list is used to change the default style for new blocks that are added.
To change the style of the selected image block, click on the style, as you illustrate in the video.

**Comment by annezazu** [comment] 2022-02-22 05:13
Going to close this out based on the above :)

**Closed as completed by annezazu** 2022-02-22 05:13 UTC
