### ISSUE TITLE
10.8 Update Warnings on Typography Support

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#32600] opened 2021-06-10 22:08 UTC
Upgrading to 10.8 with `WP_DEBUG` enabled produces these warnings:

```
Warning: Block core/loginout is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-date is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-date is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-excerpt is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-excerpt is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-terms is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-terms is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-title is declaring __experimentalFontFamily support on block.json under supports.__experimentalFontFamily. __experimentalFontFamily support is now declared under supports.typography.__experimentalFontFamily. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-title is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/post-title is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-pagination-next is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-pagination-next is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-pagination-previous is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-pagination-previous is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-title is declaring __experimentalFontFamily support on block.json under supports.__experimentalFontFamily. __experimentalFontFamily support is now declared under supports.typography.__experimentalFontFamily. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-title is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/query-title is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-tagline is declaring __experimentalFontFamily support on block.json under supports.__experimentalFontFamily. __experimentalFontFamily support is now declared under supports.typography.__experimentalFontFamily. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-tagline is declaring __experimentalTextTransform support on block.json under supports.__experimentalTextTransform. __experimentalTextTransform support is now declared under supports.typography.__experimentalTextTransform. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-tagline is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-tagline is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring __experimentalFontFamily support on block.json under supports.__experimentalFontFamily. __experimentalFontFamily support is now declared under supports.typography.__experimentalFontFamily. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring __experimentalFontStyle support on block.json under supports.__experimentalFontStyle. __experimentalFontStyle support is now declared under supports.typography.__experimentalFontStyle. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring __experimentalFontWeight support on block.json under supports.__experimentalFontWeight. __experimentalFontWeight support is now declared under supports.typography.__experimentalFontWeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring __experimentalTextTransform support on block.json under supports.__experimentalTextTransform. __experimentalTextTransform support is now declared under supports.typography.__experimentalTextTransform. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring fontSize support on block.json under supports.fontSize. fontSize support is now declared under supports.typography.fontSize. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459

Warning: Block core/site-title is declaring lineHeight support on block.json under supports.lineHeight. lineHeight support is now declared under supports.typography.lineHeight. in C:\xampp\htdocs\wp-content\plugins\gutenberg\lib\blocks.php on line 459
```

**Screenshot:**

![10 8-warnings](https://user-images.githubusercontent.com/1816309/121603471-7074fc80-ca0e-11eb-9f49-13492b0333b8.jpg)

**Comment by youknowriad** [comment] 2021-06-11 11:18
Mmm I believe that warning has bee added at the same time as the refactoring that hides them for core blocks, so I'm a bit surprised to see them show up for core blocks for you.

Would you mind sharing more about your setup, what WP version are you using?

cc @jorgefilipecosta

**Comment by justintadlock** [comment] 2021-06-11 16:46
That was on 5.8-alpha-51066.  I just pulled in 5.8-beta1-51138, and the warning only shows for third-party blocks now.

**Comment by jorgefilipecosta** [comment] 2021-06-11 16:59
> That was on 5.8-alpha-51066. I just pulled in 5.8-beta1-51138, and the warning only shows for third-party blocks now.

It seems now the behavior is correct, provided the block.json of the third party blocks in fact defines typography supports outside the typography key, it is expected that these warnings appear.

**Comment by skorasaurus** [comment] 2022-05-27 00:00
Sounds like this is working as expected per https://github.com/WordPress/gutenberg/issues/32600#issuecomment-859718056 and unable to reproduce on core blocks, so closing.

**Closed as completed by skorasaurus** 2022-05-27 00:00 UTC
Labels: [Feature] Block API
