### ISSUE TITLE
Switching between custom colors segmented control occasionally crops overflowing content on Android

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#30878] opened 2021-04-15 16:55 UTC
## Description
When toggling a segment control on Android, the scrollable, overflowing content is occasionally cut off. This was found in the steps within the [GB Mobile TC005 color settings test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#tc005). 

## Step-by-step reproduction instructions
1. Launch block editor on WPAndroid. 
2. Add a Button block. 
3. Open the Button block settings. 
4. Tap Background Color. 
5. Tap Gradient. 
6. Scroll to the end of the gradient list. 
7. Tap Solid. 

## Expected behaviour
The horizontal color list is not cut off and scrollable to reveal all colors. 

## Actual behaviour
The horizontal color list is cut off and not scrollable to reveal all colors. 

## Screenshots or screen recording (optional)

<details>
<summary>Screenshots</summary>

![android-segment-control-scroll](https://user-images.githubusercontent.com/438664/114906340-8cc63580-9ddf-11eb-95a0-191b172a3b24.jpg)

https://user-images.githubusercontent.com/438664/114906238-74eeb180-9ddf-11eb-9900-6bdd2ec4b4d4.mp4

</details>

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v10.3.2-with-autocomplete-perf-fix
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S20
- Operating system: Android 11
- WordPress app version: 17.1-rc-3

**Comment by chipsnyder** [comment] 2021-04-15 17:32
@antonis or @geriux would one of you be available to help look into this?

**Comment by antonis** [comment] 2021-04-15 18:52
@chipsnyder I reproduced this and I’ll have a look tomorrow during groundskeeping. It’s weird that it is happening only on Android and with the specific steps 🤷

**Comment by antonis** [comment] 2021-04-16 12:21
I'm able to reproduce this consistently on release builds but not on debug mode with metro. I was able to reproduce since 16.8-rc-3 and is probably older than that.

**Comment by antonis** [comment] 2021-04-16 18:14
I confirm that this was introduced in `16.8` since I was not able to reproduce it in [`16.7`](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/16.7-rc-1). I wasn't able to pinpoint any relevant commits though.
I tried a couple of fixes ([e.g.](https://github.com/WordPress/gutenberg/pull/30915)) but nothing worked. I plan to revisit this next week. cc @chipsnyder, @geriux

**Comment by antonis** [comment] 2021-04-19 18:42
After investigating this further it seems that the changes introduced in [`1.47`](https://github.com/wordpress-mobile/gutenberg-mobile/releases/tag/v1.47.0) with [this PR](https://github.com/WordPress/gutenberg/pull/28740) are causing the reported issue. This seems also to be related with the [disappeared custom button](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3104#issuecomment-820581892).
I need to retest to confirm the above in the latest WPAndroid version and evaluate the implications of falling back to the [temporary workaround](https://github.com/WordPress/gutenberg/pull/28698).

**Comment by antonis** [comment] 2021-05-07 09:35
Fixed with https://github.com/WordPress/gutenberg/pull/30994

**Closed as completed by antonis** 2021-05-07 09:35 UTC
Labels: [Type] Bug, Mobile App - i.e. Android or iOS
