### ISSUE TITLE
Pattern block not expanded in Site Editor > Pages

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#52983] opened 2023-07-26 15:01 UTC
### Description

- In Dashboard > Pages, it is expanded.
- I would like it to be expanded in Site Editor > Pages but it is not.
- I noticed when using a custom template, once the custom template edit screen is opened, it is also expanded in Site Editor > Pages.

### Step-by-step reproduction instructions

1. Using TwentyTwentyThree theme.
2. Create custom template. in `themes/twentytwentythree/templates/my-template.html`

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:pattern {"slug":"core/query-standard-posts"} /-->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->
```

3. Apply My Template to any page.
4. Open Site Editor > Pages.
5. Open the page to which you have applied My Template.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1094306/da7d3316-be52-45bc-b54b-66a073d601ad

### Environment info

- WordPress 6.3 RC2
- Twenty Twenty Three 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-07-27 14:26
I have confirmed this issue. The Pattern block that has been added to a custom template is not rendered when viewing a Page in the Site Editor. Note that if you view the template itself in the Site Editor, the pattern is rendered. So the issue appears to be isolated to the Page view in the Site Editor.

**Comment by aaronrobertshaw** [comment] 2023-07-31 08:18
I don't have a full explanation yet as to the true cause of the issue however it appears that the page content focus manager prevents the rendering of `wp:pattern` blocks when it disables block editing.

There's a small draft PR (https://github.com/WordPress/gutenberg/pull/53166) with a tweak that gets `wp:pattern` blocks to show again although it hasn't been tested thoroughly yet and there might be unintended side effects or better approaches. 

While exploring this issue I also found that some template parts that reference `wp:pattern` blocks provided via themes weren't displaying either.

Unfortunately, I'm out of time but will pick this up again tomorrow if needed.

**Comment by aaronrobertshaw** [comment] 2023-08-01 06:55
Closing this as fixed now that https://github.com/WordPress/gutenberg/pull/53169 & https://github.com/WordPress/gutenberg/pull/53206 have landed.

**Closed as completed by aaronrobertshaw** 2023-08-01 06:55 UTC
Labels: [Type] Bug, [Feature] Site Editor, [Block] Pattern
