### ISSUE TITLE
It is impossible to go to the first line of a text block, if you are in the beginning of line

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#36421] opened 2021-11-11 21:52 UTC
### Description

When you press <kbd>Up</kbd> while your cursor is in the middle or end of each line, you can easily go to any previous line, including first one.

On contrary, when cursor is before the first letter (i.e. you press <kbd>Home</kbd> before <kbd>Up</kbd>) then going to the first line is **not possible**. Pressing <kbd>Up</kbd> while having cursor at the first character of second line navigates you to the previous block instead of first line of current block.

This may sound simply or even trivia, but turns out extremely irritating, if one is using Gutenberg with keyboard mostly.

### Step-by-step reproduction instructions

1. Place your cursor anywhere within second line of any text block.
2. Press <kbd>Home</kbd> and then press <kbd>Up</kbd>.
3. Observe cursor shifting to previous block instead of first line.

### Screenshots, screen recording, code snippet

![coursor](https://user-images.githubusercontent.com/60975060/141373741-49712743-83b7-4d01-a9f7-fb6389eaab80.gif)

### Environment info

* WordPress 5.8.2
* Gutenberg (the development plugin) version 11.9.0
* Theme WR-Elite version: 1.6 by WooRockets
* Chrome version 95.0.4638.69 (Official Build) (64-bit)
* Windows 10 version 10.0.19042 Build 19042

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment] 2023-08-16 13:21
This is a duplicate of #34215.

**Closed as completed by ellatrix** 2023-08-16 13:21 UTC
Labels: [Focus] Accessibility (a11y)
