### ISSUE TITLE
There is an issue with the link color of the text in the heading and paragraph blocks

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#40221] opened 2022-04-11 09:50 UTC
### Description

When we use paragraph and heading blocks in a post and page. And if we add a link to any text and change the color of that link, then it is working perfectly, but whenever we add background color to that link after we change the color of this link, then the color of the link would not change.

### Step-by-step reproduction instructions

1. Go to the editor
2. Add paragraph/heading block
3. enter text and add a link to any text
4. Go to the sidebar Color option
5. Choose the Link color for the paragraph/heading text
6. Choose a Background color for the paragraph/heading text

### Screenshots, screen recording, code snippet

I have added the video link of the issue below

https://screencast-o-matic.com/watch/c3fXQzVqd8r

### Environment info

-WordPress version: 5.9.3
-Gutenberg Plugin Version: 12.9.0
-Google Chrome version: Version 100.0.4896.75 (Official Build) (arm64)
-OS Version: Mac 12.2.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-04-11 10:50
Hi @aezazs-multidots I am closing this issue because it is a duplicate of https://github.com/WordPress/gutenberg/issues/40219

**Closed as completed by carolinan** 2022-04-11 10:50 UTC
Labels: [Status] Duplicate
