### ISSUE TITLE
More Editing Capabilities for Default Header

### ISSUE THREAD

**Issue by Mayaerin1** [WordPress/gutenberg#8787] opened 2018-08-09 17:05 UTC
As of now it seems the only way to edit the automatic hyperlinked heading added to the top of every page is through custom CSS. There is no way otherwise to change font size or family and you are forced to use the preset size of the theme. In other blocks it at least allows you to change between the various headings/paragraph.

**Comment by AndreaBarghigiani** [comment] 2018-08-19 10:31
@ZebulanStanphill I completely understand the Gutenberg focus on `post_content` side but I am writing this comment because a client of mine actually had the same kind of feeling.

She wanted to change the alignement of the title because, different from the classic editor where the two section were well separated, Gutenberg does not show any separation between the title and the actual post content.

I think that would be useful to add a kind of inline help or something like it in the "welcome tooltips" (I do not remember the actual name of the tooltips shown the first time a user uses Gutenberg) that explain that the user can change the styles of all the content but not the title of the article.

**Comment by ZebulanStanphill** [comment] 2018-08-19 11:36
@AndreaBarghigiani Yeah, I think it would be a good idea to have more visual separation between the title and the block editor, because right now it looks like the title is just another block, which is not actually the case.

**Comment by tellthemachines** [comment] 2019-11-28 05:24
This issue seems to be a duplicate of #8469, so I'm closing it in favour of that one. See also #11553 for the likely future of post title as a block.

**Closed by tellthemachines** 2019-11-28 05:24 UTC
Labels: [Feature] Blocks, [Type] Enhancement
