### ISSUE TITLE
When changing style variations in the right sidebar, the preview changes abnormally vertically

### ISSUE THREAD

**Issue by Olein-jp** [WordPress/gutenberg#52092] opened 2023-06-29 00:45 UTC
### Description

Access the site editor in WordPress 6.3 Beta 2.

The live preview works fine after changing the style variations that can be selected in the left sidebar.

However, when changing the style in the style variation accessible from the right sidebar (the old one), we observed a behavior where the preview screen keeps growing more vertically than it should.

### Step-by-step reproduction instructions

1. Access site editor in Appearance
2. No problem changing style variation on left panel(sidebar)
3. Then access style variation on right sidebar and change another style variation
4. Keep growing more vertically on preview

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/28924629/e2801805-54ad-45fd-8cc5-11bb34549c18

### Environment info

- WordPress 6.3 Beta 2 on LocalWP
- No plugin activated without WordPress Beta Tester

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by megane9988** [comment] 2023-06-29 03:05
Yes, I also hit the same issue.

https://github.com/WordPress/gutenberg/assets/1205958/b9458f8f-e1c1-4d64-ad97-385d4ee0303d

But it did not happen Twenty Twenty-Two Theme.

**Comment by inc2734** [comment] 2023-06-29 03:06
The pattern inserter also confirmed that some pattern previews are extended. WordPress 6.3 beta2 + TT3


https://github.com/WordPress/gutenberg/assets/1094306/183a388e-eafd-4a0b-96c2-f5ac3da12f76

**Comment by megane9988** [comment] 2023-06-29 03:14
This issue looks similar to https://github.com/WordPress/gutenberg/issues/49120.

**Comment by ndiego** [comment] 2023-06-29 11:36
I believe this is due to certain patterns that have the height of blocks set to 100vh or 100%. If so, this issue has existed for a while.

**Comment by megane9988** [comment] 2023-06-29 15:29
It seems related to

https://github.com/WordPress/gutenberg/issues/50449 and https://github.com/WordPress/gutenberg/pull/38181

**Comment by annezazu** [comment] 2023-07-19 18:50
Going to close this out as this issue is covered in the issues linked above.

**Closed as completed by annezazu** 2023-07-19 18:50 UTC
Labels: [Type] Bug, [Feature] Patterns
