### ISSUE TITLE
Block Widgets: Unable to use the theme Customizer to edit

### ISSUE THREAD

**Issue by davipontesblog** [WordPress/gutenberg#32707] opened 2021-06-15 18:29 UTC
After enabling block widgets on my test site, previous widgets do not show in the Customizer: 

<img width="1106" alt="Screen Shot 2021-06-15 at 15 11 12" src="https://user-images.githubusercontent.com/31009008/122104740-637d5200-cdee-11eb-8602-f3ef2c0059c9.png">

However, they do show in the Appearance > Widgets area in WP Admin.

I am also not able to add or edit any widgets in the Customizer now.

Test site environment:

Twenty Sixteen theme
WordPress.com simple site
Gutenberg: v10.8.0
CoBlocks: 2.10.1
Editing Toolkit: 3.8300
WP AMP: 2.0.5

**Comment by AtrumGeost** [comment] 2021-06-15 18:35
Got the same behavior. Here's a video.


https://user-images.githubusercontent.com/3696121/122105509-7c7e0700-cdde-11eb-9303-10dc773130d3.mp4



This happened on a site with pre-existing widgets.

Test site environment:

Apostrophe 2 theme
WordPress.com simple site
Gutenberg: v10.8.0
CoBlocks: 2.10.1
Editing Toolkit: 3.8300
WP AMP: 2.0.5

**Comment by draganescu** [comment] 2021-06-16 10:13
I cannot reproduce this using WordPress core trunk or 5.7 and migrating to Gutenberg's block widgets. Looking at the details it may be an implementation issue for WordPress.com, so this issue should be moved to an Automattic project. 

Closing for now, but feel free to comment/reopen if this is core related in the end.

**Closed as completed by draganescu** 2021-06-16 10:13 UTC
Labels: Needs Testing, [Feature] Widgets Screen, [Feature] Widgets Customizer

**Comment by davipontesblog** [comment] 2021-06-16 10:57
Thank you for triaging @draganescu. I've now recreated the issue in https://github.com/Automattic/wp-calypso/issues/53741
