### ISSUE TITLE
[4.3.0-RC-1] floating images create selection issues 

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11698] opened 2018-11-09 20:12 UTC
**Describe the bug**
Floating images have click-through issues to the underlying paragraph.

**To Reproduce**
1. Insert text
2. Insert image
3. Float image right/left.

- If the image is **larger** than one paragraph , then you cannot select the image.
- If the image is **smaller** than one paragraph, then you cannot select the paragraph.

**Comment by GlennMartin1** [comment] 2018-11-09 20:13
This is a 4.3 regression.

**Comment by youknowriad** [comment] 2018-11-10 08:42
Probably related to #11357

**Comment by youknowriad** [comment] 2018-11-12 07:45
@GlennMartin1 I can't reproduce personally. I do trigger multi-selection sometimes If the mouse moves slightly but I can select in all cases, can you record a screenshot or something?

**Comment by jasmussen** [comment] 2018-11-12 08:17
This is fixed by #11748, and let the record be known that Riad is my hero.

The issue is not present in Chrome and Safari:

![large img](https://user-images.githubusercontent.com/1204802/48334661-b94c5500-e65b-11e8-8e25-f04ea6092e75.gif)

![small img](https://user-images.githubusercontent.com/1204802/48334666-bbaeaf00-e65b-11e8-93de-487afb731c0e.gif)

But the issue is present in Firefox:

![small img ff](https://user-images.githubusercontent.com/1204802/48334675-c0736300-e65b-11e8-9364-173ac48f35ab.gif)

But with #11748 merged, the issue is no longer present:

![fix](https://user-images.githubusercontent.com/1204802/48334688-ccf7bb80-e65b-11e8-9491-e008067ee7a2.gif)

**Closed** 2018-11-12 11:00 UTC
Labels: Browser Issues, Regression, [Type] Bug
