### ISSUE TITLE
Can't / Hard to add content when more than 2 columns

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#5364] opened 2018-03-03 02:40 UTC
Trying to create more than 2 columns and it's hard to add content. The icons to add new block are blocking the edit content. I think it's better to just show the + icon and not the recently used blocks? Thanks!

<img width="1109" alt="screen shot 2018-03-03 at 10 44 19 am" src="https://user-images.githubusercontent.com/3365507/36929680-530566a4-1e49-11e8-9aa4-eac95fe3d5bc.png">

**Comment by youknowriad** [comment] 2018-03-06 16:05
closing as duplicate of #5114

**Closed by youknowriad** 2018-03-06 16:05 UTC
