### ISSUE TITLE
Filterable block inspector tabs

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#67054] opened 2024-11-17 12:34 UTC
## Block inspector tabs

Block inspecor tabs are defined in `packages/block-editor/src/components/inspector-controls-tabs/use-inspector-controls-tabs.js`.
I have a need to add custom tab for my block. The easiest way to achieve that would be to add filter in the source to allow adding custom tabs.

**Comment by aminul-xs** [comment] 2024-11-18 04:31
[Block Inspector Tabs](https://github.com/WordPress/gutenberg/issues/59115)

**Comment by talldan** [comment] 2024-11-18 08:22
Closed as a duplicate of #59115

**Closed as not planned** 2024-11-18 08:22 UTC
Labels: [Type] Enhancement, [Status] Duplicate
