### ISSUE TITLE
Insert link: the link selection disappears when entering a link

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#6156] opened 2018-04-12 23:58 UTC
## Issue Overview
When inserting a link, your text selection disappears when the focus changes into the _Paste URL or type_ text field. This makes it hard to tell exactly what text you are linking.

## Screenshots / Video
![new links](https://user-images.githubusercontent.com/1204802/38667596-199b195e-3e42-11e8-9e03-387fe8162350.gif)

## Steps to Reproduce (for bugs)
1. Create a paragraph block
2. Select some text
3. Click on the _Link_ button in the formatting toolbar

## Expected Behavior
Your cursor should be in the _Paste URL or type_ text field and there should be a blue selection rectangle around the text that you selected.

## Current Behavior
Your cursor is in the _Paste URL or type_ text field but the text you selected is no longer selected.

## Possible Solution
The classic editor solves this by immediately inserting a link placeholder, as soon as you create a link:

![classic links](https://user-images.githubusercontent.com/1204802/38667625-2d8bc7e2-3e42-11e8-8355-c291165d585c.gif)

## Related Issues and/or PRs
This was flagged as an issue in https://github.com/WordPress/gutenberg/issues/4572 and https://github.com/WordPress/gutenberg/issues/5960#issuecomment-380733802. https://github.com/WordPress/gutenberg/pull/4909 contained a failed attempt at fixing this.

**Comment by designsimply** [comment] 2018-07-27 22:39
I tested using WordPress 4.9.7 and Gutenberg 3.3.0 and confirmed that, if I select text and click the link icon in the paragraph block, no formatting or highlighting appears to show me what link text is currently selected. Tested with WordPress 4.9.7 and Gutenberg 3.3.0. ([screenshot](https://user-images.githubusercontent.com/1119271/43349212-972ce376-91bb-11e8-9d59-a9d84ae59c9e.png))

**Comment by talldan** [comment] 2018-10-05 15:45
This seems to have regressed in master - reopening the issue. Unsure why the e2e tests didn't catch it.

**Comment by noisysocks** [comment] 2018-10-05 18:04
Is this to do with the recent `RichText` changes? @WordPress/gutenberg-core

**Comment by iseulde** [comment] 2018-10-31 10:46
I can look into this, but I'm considering it low priority. Feel free remove my assignment if someone else would like to fix.

**Comment by gziolo** [comment] 2018-10-31 11:53
@talldan would you mind helping us with this one? I can tell you that @iseulde is super busy with work these days :)

**Comment by iseulde** [comment] 2018-10-31 12:19
Tbh I wouldn't add a link placeholder before it's inserted. That seems not so clean, we'd have to make sure the link is removed again etc. Would be nice if we could somehow keep the a selection or render a fake selection or something visible around the target.

**Comment by talldan** [comment] 2018-11-02 08:03
> Would be nice if we could somehow keep the a selection or render a fake selection or something visible around the target.

@iseulde By fake selection, I'm guessing you mean an element overlayed over the top of the text? I had a look into this idea, and I think it could be a winner. I used a similar approach to positioning the overlay as used in PositionedAtSelection to position the popover. Here's an example of how it looks (it seems to even work for multiple selected lines 🎉, though note the popover isn't particularly well positioned for multiline selections 😢 ):

![selection](https://user-images.githubusercontent.com/677833/47900615-71d60400-deb8-11e8-8bae-7b0fb8d72dc8.gif)

Need to do some cross-browser testing and tidy up the code, but I'll try to have a PR submitted soon if all goes to plan.

**Comment by talldan** [comment] 2018-11-02 08:49
Clean up isn't an issue with this approach, as the selection renders in the <InlineLinkUI> as a sibling of the popover (plus some additional logic to to not render once the link is applied).

**Comment by noisysocks** [comment] 2018-11-05 00:32
Remember that different operating systems style text selection differently, and that users can change their text selection colour:

<img width="285" alt="screen shot 2018-11-05 at 11 16 57" src="https://user-images.githubusercontent.com/612155/47972086-84d11a00-e0ec-11e8-8a0c-e0ab75ed794b.png">

The fake selection would have to be styled in a platform agnostic way.

Personally, I think styling the placeholder selection or link as blue underlined text sends the strongest signal that a _link_ is being inserted.

**Comment by talldan** [comment] 2018-11-05 09:53
@noisysocks Yeah, worth making it OS/Browser agnostic as you say. I think it could have the same light blue styling as selected links do in the editor. 

An underline would require a different implementation using placeholder tags. I don't know how feasible that is at the moment.

**Comment by iseulde** [comment] 2018-11-05 11:56
I could be something different from the browser, doesn't have to be a blue background. Can e.g. also be a dotted outline, or, as you say, underlining the text.

> An underline would require a different implementation using placeholder tags. I don't know how feasible that is at the moment.

Can't you underline it by styling the selection?

**Comment by youknowriad** [comment] 2018-11-20 14:46
This is more a "nice to have" than a blocking issue.

**Comment by paaljoachim** [comment] 2021-01-22 13:10
I am doing a status update.
Using Gutenberg plugin 9.8. Twenty Twenty One. WordPress 5.6.0.

![Screen Shot 2021-01-22 at 14 09 24](https://user-images.githubusercontent.com/5323259/105494710-7d8d8b00-5cbb-11eb-8e83-192b45450175.png)

The issue is still very much valid.

**Comment by ellatrix** [comment] 2021-01-26 11:03
Iframing the content (#21102) will fix this.

**Comment by paaljoachim** [comment] 2021-01-26 11:15
Great! As I see the [Site Editor iframe PR](https://github.com/WordPress/gutenberg/pull/25775) has been merged then the work on iframing the Post Editor can also continue.

**Comment by jordesign** [comment] 2023-07-10 03:05
Iframing task is complete and merged - and this issue is no longer present in my testing - so I'm going to close this issue.

**Closed by jordesign** 2023-07-10 03:05 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Package] Format library
