### ISSUE TITLE
Template for custom post type does not appear in editor

### ISSUE THREAD

**Issue by ericnicolaas** [WordPress/gutenberg#5873] opened 2018-03-29 08:10 UTC
I am attempting to define a template for a custom post type, `campaign`. For now I stuck with the description outlined at https://wordpress.org/gutenberg/handbook/templates/. This is my custom post type definition:

```
register_post_type( 'campaign',
	apply_filters( 'charitable_campaign_post_type',
		array(
			'labels' => array(
				'name'                  => __( 'Campaigns', 'charitable' ),
				'singular_name'         => __( 'Campaign', 'charitable' ),
				'menu_name'             => _x( 'Campaigns', 'Admin menu name', 'charitable' ),
				'add_new'               => __( 'Add Campaign', 'charitable' ),
				'add_new_item'          => __( 'Add New Campaign', 'charitable' ),
				'edit'                  => __( 'Edit', 'charitable' ),
				'edit_item'             => __( 'Edit Campaign', 'charitable' ),
				'new_item'              => __( 'New Campaign', 'charitable' ),
				'view'                  => __( 'View Campaign', 'charitable' ),
				'view_item'             => __( 'View Campaign', 'charitable' ),
				'search_items'          => __( 'Search Campaigns', 'charitable' ),
				'not_found'             => __( 'No Campaigns found', 'charitable' ),
				'not_found_in_trash'    => __( 'No Campaigns found in trash', 'charitable' ),
				'parent'                => __( 'Parent Campaign', 'charitable' ),
			),
			'description'           => __( 'This is where you can create new campaigns for people to support.', 'charitable' ),
			'public'                => true,
			'show_ui'               => true,
			'capability_type'       => 'campaign',
			'menu_icon'             => '',
			'map_meta_cap'          => true,
			'publicly_queryable'    => true,
			'exclude_from_search'   => false,
			'hierarchical'          => false,
			'rewrite'               => array( 'slug' => 'campaigns', 'with_front' => true ),
			'query_var'             => true,
			'supports'              => array( 'editor', 'title', 'thumbnail', 'comments' ),
			'has_archive'           => false,
			'show_in_nav_menus'     => true,
			'show_in_menu'          => false,
			'show_in_admin_bar'     => true,
			'show_in_rest'          => true,
			'rest_base'             => 'campaigns',
			'rest_controller_class' => 'WP_REST_Posts_Controller',
			'template'              => array(
				array(
					'core/image',
					array(
						'align' => 'left',
					),
				),
				array(
					'core/heading',
					array(
						'placeholder' => 'Add Author...',
					),
				),
				array(
					'core/paragraph',
					array(
						'placeholder' => 'Add Description...',
					),
				),
			),
		)
	)
);
```

This is included in a function that is called on the `init` hook; the post type is properly registered. But when I go to create a new campaign, this is what I see:

![screenshot 2018-03-29 17 37 00](https://user-images.githubusercontent.com/676582/38077342-d61616cc-3377-11e8-88b8-cba3f3de7e02.png)

I expected at this point to see the image, header and paragraph blocks, but they're absent. 

The above code can be tested in this experimental branch of my plugin: https://github.com/Charitable/Charitable/tree/feature/gutenberg

**Comment by ericnicolaas** [comment] 2018-04-02 02:38
I removed the `core/image` block and investigated what `editorSettings` is set to:

```
var editorSettings = {
    "alignWide":false,
    "availableTemplates":[],
    "blockTypes":true,
    "disableCustomColors":false,
    "disablePostFormats":false,
    "titlePlaceholder":"Enter campaign title",
    "bodyPlaceholder":"Write your story",
    "template":[
        ["core\/heading",
            {"placeholder":"Add Author..."}
        ],
        ["core\/paragraph",
            {"placeholder":"Add Description..."}
        ]
    ],
    "templateLock":false
}
```

That is almost exactly the same (the only difference is `titlePlaceholder`, which seems inconsequential) as the `editorSettings` if I use the example code from function https://wordpress.org/gutenberg/handbook/templates/#custom-post-types:

```
myplugin_register_book_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Books',
        'show_in_rest' => true,
        'template' => array(
            array( 'core/image', array(
                'align' => 'left',
            ) ),
            array( 'core/heading', array(
                'placeholder' => 'Add Author...',
            ) ),
            array( 'core/paragraph', array(
                'placeholder' => 'Add Description...',
            ) ),
        ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

For the book post type, it works. For the campaign post type, it does not.

**Comment by youknowriad** [comment] 2018-11-03 21:04
Are you still having issues? This works for me with the exact same post type. Closing for now. Let's reopen if we find ways to reproduce this.

**Closed by youknowriad** 2018-11-03 21:04 UTC
Labels: Needs Technical Feedback, Needs Testing, Templates API
