### ISSUE TITLE
Blob URL is inserting to Video block during file upload

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [WordPress/gutenberg#20168] opened 2020-02-11 14:42 UTC
**Describe the bug**
I've met the issue with Video block.
After publishing the post - video doesn't play. And it has a URL with "blob": <video controls src="blob:https://..."></video>
It seems, that the reason is I published the post before video-file uploading prosess was fineshed. 

**Expected behavior**
It would be nice to see loadbar with file loading progress and disabling Publish button until the end of uploading.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  chrome
 - Version 78.0.3904.108
- WordPress v.5.3.2

**Comment by youknowriad** [comment] 2020-02-12 12:27
Thanks for opening the issue, this is already tracked #16030
Duplicate of #16030

**Closed by youknowriad** 2020-02-12 12:27 UTC
