### ISSUE TITLE
Cursor position error after copy

### ISSUE THREAD

**Issue by QiShaoXuan** [WordPress/gutenberg#15166] opened 2019-04-25 08:38 UTC
When I copy a piece of text into the editor, the cursor always precedes the text, I think it need appear at the end of text.
You can try it in [gutenberg website](https://wordpress.org/gutenberg/).

**Comment by maurisrx** [comment] 2019-04-26 06:56
Yes, I can also confirm that. Every time I copy paste text to new paragraph block, the cursor doesn't automatically move to the end of the text but it stays at the beginning of the text.

**Comment by GlennMartin1** [comment] 2019-04-26 22:41
Same here.  Using Chrome on Windows.

**Comment by arunsathiya** [comment] 2019-05-18 08:15
This is a duplicate of https://github.com/WordPress/gutenberg/issues/5317.

**Comment by gziolo** [comment] 2019-05-23 11:25
> This is a duplicate of #5317.

Thanks for reporting, let's close it in favor of #5317.

**Closed by gziolo** 2019-05-23 11:25 UTC
