### ISSUE TITLE
Classic Block in Block Editor - "Open Link In New Tab" not staying checked (AT Site Only)

### ISSUE THREAD

**Issue by gwensmithx** [WordPress/gutenberg#13682] opened 2019-02-05 19:46 UTC
**Describe the bug**
**On an AT site** - Using the "Open Link In New Tab" checkbox in Classic Block in new Block Editor (Gutenberg) does not save selection when updated. E.g. Add a Classic Block, add and any link and click update. Then go back to your link and click the gears icon and check-off the "Open link in new tab" checkbox and click update on the window then update the post/page. Click into the link again and you'll notice the checkbox is still unchecked even though you checked it off and saved it.

**To Reproduce**
1. On an AT site - on any post or page add the Classic Block
2. Add any link and save the post.
3. You can preview the post - everything looks good. Link opens up in the same window since you left it unchecked. 
4. Go back to post editor and click your link and click the gears icon to edit. Check off the "Open link in new tab checkbox" and click update on the window, then update the post. After successful update you can either preview your post or click into the link settings again and you'll see the checkbox is still unchecked and the link will still open in the same window.

**Expected behavior**
After checking the "Open link in new tab" checkbox and saving I expected it to open the link in a new tab and save my settings.

**Screenshots**
![gutenberg-but4](https://user-images.githubusercontent.com/5779512/52299969-003ca480-2944-11e9-8cc1-efc076813835.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Browser: Firefox Quantum

**Additional context**
Running WordPress 5.0.3 AT Site (Business Plan)
-Tested on Premium Plan and **could not reproduce the issue** so I think it is an AT issue with Gutenberg
-Deactivated all other plugins and changed themes to rule out any theme or plugin conflicts. Still was able to reproduce issue with all plugins deactivated and switching to default theme.

**Comment by youknowriad** [comment] 2019-02-06 15:54
Looks like this is a duplicate of #7932 which has been closed in favor of this Core ticket  https://core.trac.wordpress.org/ticket/46071

**Closed by youknowriad** 2019-02-06 15:54 UTC
