### ISSUE TITLE
latest release BREAKS Gutenberg

### ISSUE THREAD

**Issue by harryherbert** [WordPress/gutenberg#11850] opened 2018-11-14 11:50 UTC

**Comment by harryherbert** [comment] 2018-11-14 11:56
> A clear and concise description of what the bug is.
ver4.3
Some pages frozen cannot edit them.
Clicking Preview does not show update just shows what was there before.
Problem so serious I have had to revert to classic editor as I cannot work on websites.
This has occurred on several of my website.
I think you have a serious problem.

**Comment by designsimply** [comment] 2018-11-14 16:13
@harryherbert it's hard to tell what might be going wrong in your case based on the description so far. I can tell you that other have been testing and have not reported the same issues so far (this doesn't mean they don't exist but it does mean not everyone is seeing the same). I'm not having trouble with pages freezing in my experience but I would like to learn more about your setup. May I ask where you are hosted and whether anything else has changed on your site recently such as plugins or maybe anything for your web server configuration. May I ask where your site is hosted? For what you described, I'm not sure it will be possible to see, but if you open the console in your web browser tools are you able to see any errors there that could help narrow down the source of the trouble?

**Comment by designsimply** [comment] 2019-01-30 22:48
@harryherbert I am looping back to check in to see if you are still experiencing some pages freezing and to note that we are now tracking a problem with previews not working for changes to previously published posts for some people at https://github.com/WordPress/gutenberg/issues/12617. 

If pages are still freezing for you, would it be possible for you to check to see if the issue is caused by a plugin conflict? You can do that by temporarily disabling all plugins for one of your sites and then checking to see if the problem goes away. If it doesn't, then it makes sense to continue troubleshooting and we may want to move this discussion to https://wordpress.org/support/forum/how-to-and-troubleshooting/ because there may be more people with an eye toward troubleshooting in that forum compared to here.

**Comment by designsimply** [comment] 2019-02-12 22:53
I am closing this issue since there hasn't been a reply in several weeks but also adding a note to say we can absolutely re-open if more information can be provided and also that the support forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ are the best place to start if you are still at a point where you need help gathering information about the problem which will be most helpful when submitting a bug report. Thank you!

**Closed by designsimply** 2019-02-12 22:53 UTC
Labels: [Type] Help Request
