### ISSUE TITLE
Editing on mobile sometimes shows the inspector unexpectedly

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#26152] opened 2020-10-15 12:34 UTC
On mobile tapping around the widgets or blocks opens the inspector:

To reproduce:

1. Have the Gutenberg plugin active
2. Go to Appearance > Widgets
3. Tap around and try to deselect the widget
4. With enough persistence you'll suddenly open the block inspector

Screenshots:

![mobile-inspector](https://user-images.githubusercontent.com/107534/96123755-f5e5f280-0efb-11eb-9ea6-3133ae9fe87e.gif)

**Comment by talldan** [comment] 2021-01-06 07:36
I can reproduce this, so moving to the Needs Dev column in the project.

**Comment by draganescu** [comment] 2021-06-02 14:58
Updated the priority in the widgets editor project board as it is very inconvenient on mobile.

**Comment by kevin940726** [comment] 2021-06-03 04:36
@draganescu I can't reproduce it, can you still reproduce it?

**Comment by draganescu** [comment] 2021-06-03 18:00
Yes, I was testing how this works on mobile using trunk and it still happened. Used a device iPhone.

**Comment by tellthemachines** [comment] 2021-06-04 04:08
I can repro this on both mobile and desktop by first selecting a block and then clicking in the grey area just under one of the widget areas. If on desktop and the sidebar is closed, it opens the sidebar.

**Comment by kevin940726** [comment] 2021-06-04 04:14
I can reproduce it now on mobile too. For some reasons I read Widgets Customizer instead of the Widgets screen 😅.

**Closed** 2021-06-07 10:48 UTC
Labels: [Feature] Widgets Screen, [Status] In Progress, [Type] Bug
