### ISSUE TITLE
Block Inserter/Add Block Icon shows in wrong place

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24743] opened 2020-08-23 08:25 UTC
**Describe the bug**
The Add Block icon shows in the wrong place making it impossible to click to insert a new block.

Vid: https://share.getcloudapp.com/L1uJr1pr

**To reproduce**
1. Edit a page
2. Move cursor between blocks
3. Check Add Block icon shows in correct position

**Expected behavior**
Add block icon should show in correct location when hovering between blocks

**Editor version (please complete the following information):**
- WordPress version: [5.5]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):
- OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

**Comment by annezazu** [comment] 2020-08-25 21:34
@maddisondesigns thanks for reporting this (along with the various other issues too). I tried to replicate this problem but wasn't able to using 5.5 without Gutenberg installed using Chrome or Firefox. Here's a video from my chrome test:

https://cloudup.com/cIB9ov_HagI

I'm going to flag this as needing further testing as a result since I can't replicate.

**Comment by maddisondesigns** [comment] 2020-08-26 02:59
One of the many problems with testing this is that half the time, the Add Block icon doesn't even show at all, let alone showing in the right or wrong place.

**Comment by annezazu** [comment] 2020-08-26 16:39
I see 😕 Thanks for following up here!

**Comment by talldan** [comment] 2021-02-02 05:41
This was tested during a core-editor triage session and those attending the meeting couldn't reproduce the bug, so I'll close the issue.

There is a separate issue for the other problems mentioned triggering the inserter (https://github.com/WordPress/gutenberg/issues/22801).

**Closed by talldan** 2021-02-02 05:41 UTC
Labels: Needs Testing, [Feature] Inserter
