### ISSUE TITLE
Standarize 'close' icon across the UI

### ISSUE THREAD

**Issue by enriquesanchez** [WordPress/gutenberg#20278] opened 2020-02-18 00:18 UTC
**Describe the bug**
We are currently using different versions of the 'close' icon in different parts of the UI. It'd be best if we standarize to a single one.

**Screenshots**
<img width="287" alt="Screen Shot 2020-02-17 at 18 10 39" src="https://user-images.githubusercontent.com/3276087/74693468-96d7ae80-51b1-11ea-9376-90e04ed53924.png">
<img width="721" alt="Screen Shot 2020-02-17 at 18 10 28" src="https://user-images.githubusercontent.com/3276087/74693470-9808db80-51b1-11ea-83f6-3ff77e9e0a6b.png">
![Screen Shot 2020-02-17 at 3 58 16 PM](https://user-images.githubusercontent.com/3276087/74693472-993a0880-51b1-11ea-8d25-7243f657450f.png)

**Comment by mapk** [comment] 2020-02-18 17:20
In [today's Design triage in slack](https://wordpress.slack.com/archives/C02S78ZAL/p1582045453484800), we felt the different action of the input field icon was reason enough to keep it different from the other close `X` icons.

**Next steps:**
1. Make the circle icon in the search input field larger so it's clear.
2. Make the blue icon in the Publish slideout grey so that it matches the other icons.

**Comment by Soean** [comment] 2020-02-24 04:11
**1.** The circle icon is a native browser feature for `<input type="search">`. Every browser renders it a little different. Only Firefox is not showing this icon, but there is [an issue in mozillas bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=558594). 
There is a way to style this icon in webkit based browsers and IE , see: https://stackoverflow.com/a/20804207/1378097

Chrome
<img width="413" alt="Bildschirmfoto 2020-02-24 um 10 35 36" src="https://user-images.githubusercontent.com/695201/75128286-f116c900-56f5-11ea-80f3-3d963b9c8e90.png">

Safari
<img width="429" alt="Bildschirmfoto 2020-02-24 um 11 08 26" src="https://user-images.githubusercontent.com/695201/75128301-01c73f00-56f6-11ea-8f7e-842e57033bc0.png">

Firefox
<img width="414" alt="Bildschirmfoto 2020-02-24 um 11 08 54" src="https://user-images.githubusercontent.com/695201/75128314-13104b80-56f6-11ea-8ae4-bbff13508cb4.png">


**2.** I am not able to reproduce the blue icon:
<img width="283" alt="Bildschirmfoto 2020-02-24 um 10 34 43" src="https://user-images.githubusercontent.com/695201/75127456-c0349500-56f1-11ea-9262-b1beaeab4c5c.png">

**Comment by Amberlisi** [comment] 2020-03-02 23:09
To keep things consistent from a design standpoint, we could set the webkit appearance to none, and add in a custom image that can be displayed on browsers that support the search cancel button webkit.

Of course, this won't be visible on IE or Firefox browsers since they do not support this webkit. They will still be left with an inconsistent clear search button.

Also, I am unable to reproduce the blue X icon as well.

![image](https://user-images.githubusercontent.com/43859793/75726502-28621880-5ca8-11ea-9f11-9728634516ab.png)

Example below:
`#Search::-webkit-search-cancel-button{
    -webkit-appearance: none;
    height: 40px;
    width: 40px;
    background-image: url('Cancel-512.png');
    background-size: contain;
    background-repeat: no-repeat;
}`

**Comment by enriquesanchez** [comment] 2020-03-03 23:15
>The circle icon is a native browser feature for <input type="search">. Every browser renders it a little different. 

Thanks @Soean, I did not know this!

Here are some sample screenshots from Safari and Chrome (both on Mac):

Chrome:
<img width="155" alt="Screen Shot 2020-03-03 at 17 10 46" src="https://user-images.githubusercontent.com/3276087/75828689-0e8d0800-5d72-11ea-8118-7fbb7470e0f5.png">

Safari:
<img width="221" alt="Screen Shot 2020-03-03 at 17 10 53" src="https://user-images.githubusercontent.com/3276087/75828693-1056cb80-5d72-11ea-8d45-a729f46ec595.png">

Given that the clear icon is a native browser element, I don't think we should attempt to style it differently then. What do y'all think? @mapk 

I'm still able to reproduce the different colored hover state on the sidebar.

**Comment by mapk** [comment] 2020-03-06 21:12
How does this look now in light of G2 being merged? Can you take a look, @enriquesanchez?

**Comment by enriquesanchez** [comment] 2020-03-07 00:44
@mapk it's a little less noticeable now that we're using those new close icons, but the color difference is still there:

<img width="375" alt="Screen Shot 2020-03-06 at 18 38 55" src="https://user-images.githubusercontent.com/3276087/76132707-dc7ddf00-5fd9-11ea-83fa-d24dc811a1ce.png">

<img width="400" alt="Screen Shot 2020-03-06 at 18 39 04" src="https://user-images.githubusercontent.com/3276087/76132709-dee03900-5fd9-11ea-92d9-bf3904c80a78.png">

I did a little digging and I think I found the source of the problem:

in `button/style.scss` there's this:

```
&[aria-expanded="true"],
    &:hover {
        color: $theme-color;
    }
```

Looks like the close button on the publish panel has the "hover" style because of the `aria-expanded` attribute. Removing that "fixes" this difference in color, I'm however not sure about why that declaration is there in the first place, and the implications a change like this would have on other buttons.

@joen would you happen to know why we apply the hover style to buttons that have `aria-expanded="true"`?

**Comment by enriquesanchez** [comment] 2020-03-11 17:36
@jasmussen I meant to ping you on the above comment and instead pinged someone else.

**Comment by jasmussen** [comment] 2020-03-11 17:46
I'll take a look first thing tomorrow!

**Comment by jasmussen** [comment] 2020-03-12 08:13
Good detective work. The aria-expanded property is at fault, but the rule presence in the button is appropariate — the button SHOULD be blue when toggled/expanded.

The question is: why does the close button have an aria-expanded property set to true in the pre-publish dialog? The close button hasn't opened a menu. So that seems to be the thing to track down and remove.

**Closed** 2020-03-19 23:52 UTC
Labels: Good First Issue, Needs Dev
