### ISSUE TITLE
Add option to see the Code Editor in the Full Site Editing page

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#27979] opened 2021-01-05 04:51 UTC
**Is your feature request related to a problem? Please describe.**
I want to see the Code Editor in the FSE page.

**Describe the solution you'd like**
To have the option to toggle between the Visual Editor and the Code Editor, similar to the posts or pages block editors.

**Describe alternatives you've considered**
Looking at the code saved in the custom post type (`wp_template`).

**Comment by ntsekouras** [comment] 2021-01-05 07:45
Hey @chvillanuevap - thanks for reporting this. I'll close this one though as is duplicate of https://github.com/WordPress/gutenberg/issues/22528 and there is already some discussions there.

**Closed by ntsekouras** 2021-01-05 07:45 UTC
