### ISSUE TITLE
Drop cap toggle causes cursor position jump in safari

### ISSUE THREAD

**Issue by earnjam** [WordPress/gutenberg#11729] opened 2018-11-11 12:07 UTC
**Describe the bug**
When using Safari on OS X, if you write a paragraph, then toggle the drop cap setting, it will cause the cursor to jump back one character after typing. 

This is similar to #6273 but slightly different in that the text is no longer deleted. It just leaves the first character typed at the end of the line. I wanted to open a new issue to better track the specific problem. 

Related: #11119

**To Reproduce**
1. Write a sentence in Paragraph block using Safari
2. Click on drop cap toggle
3. Begin typing
4. Notice that after the first keystroke, the cursor jumps back one spot. 

**Expected behavior**
Cursor shouldn't jump. 
In Chrome and Firefox the cursor actually disappears and you can't type until focus is restored to the paragraph. Seems like this would be a possible solution. 

**Screenshots**
![drop-cap-test](https://user-images.githubusercontent.com/4267290/48312631-be3bd680-e57f-11e8-9540-4e6b8c28b95d.gif)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Safari
 - Version: 12

**Additional context**
- Gutenberg: latest from `master`
- WordPress: 5.0 beta 3

**Comment by iseulde** [comment] 2019-02-19 15:56
Is this still an issue in Gutenberg `master`?

**Comment by iseulde** [comment] 2019-02-26 20:34
I can reproduce the issue. We cannot have the caret + the drop cap visible otherwise it causes input issues. Unfortunately, this seems to be a browser issue. The only thing we could do it make sure focus is moved away so you'd have to refocus before typing.

**Comment by paaljoachim** [comment] 2021-02-21 09:43
Testing with WordPress 5.7 beta 3.
Gutenberg plugin 10.
Twenty Twenty One.
OSX 10.15.7
Safari

> To Reproduce
> Steps to reproduce the behavior:
> 
> Write a sentence in Paragraph block using Safari
> Click on drop cap toggle
> Begin typing
> Notice that after the first keystroke, the cursor jumps back one spot.

This is what I am seeing:


https://user-images.githubusercontent.com/5323259/108621187-73cd8380-7431-11eb-8d0e-a779b86ba5c2.mp4

**Comment by carolinan** [comment] 2022-07-08 10:39
I am still able to reproduce this using Safari. Gutenberg 13.6.

**Comment by youknowriad** [comment] 2023-04-11 15:18
In my test, toggling drop cap moves the focus to the drop cap toggle these days and this behavior seems consistent across browsers. So I'm going to close this issue as fixed.

**Closed by youknowriad** 2023-04-11 15:18 UTC
Labels: [Type] Bug, [Priority] Low, [Feature] Rich Text, Browser Issues, [Block] Paragraph
