### ISSUE TITLE
Remove the wrapper tagName for Template Part block wp:template-part

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#36853] opened 2021-11-25 10:23 UTC
@aristath Said to open a new issue about this and there it is.

The why to remove the wrapper tagName you can find all in this issue https://github.com/WordPress/gutenberg/pull/36571 but for the simpler version is to remove side effect generated by that wrapper, as I already said many times `wp:template-part` must work like `get_template_part()` only includes the template you want to include and nothing else.

**Comment by youknowriad** [comment] 2021-11-25 10:36
Thanks for the issue.

If the idea is to remove the wrapper element entirely, then it's not possible to do so because of the way blocks are rendered on the editor. Blocks do need a wrapper to be aligned properly otherwise there's a difference between frontend and editor that causes important visual differences (especially when alignments are used). If it's just about removing the tagName attribute and always using "div", then it's another subject.

**Comment by overclokk** [comment] 2021-11-25 11:22
It's about to remove also the div wrapper, this block is not a design block but only a block that include other file that have blocks inside, this block must not have any behavior alignment so should not have any issue about alignment, if editor has issue about alignment so it is an issue for the editor and should be solved there.

**Comment by youknowriad** [comment] 2021-11-25 11:26
>  if editor has issue about alignment so it is an issue for the editor and should be solved there.

I agree with you on principle, but it's not something that can be fixed in the editor. Block UI require extra DOM node, I've thought for a long time about potential approaches to get rid of that DOM node in the editor but it's not possible IMO.

We have to make tradeoffs and I think this is a fine tradeoff, better than leaving all themes feel broken when loaded in the site editor.

**Comment by youknowriad** [comment] 2021-11-25 11:38
I'm going to close this issue for now but if at some point in the future we find a way to render wrapper-less blocks, we should revisit it.

**Closed as completed by youknowriad** 2021-11-25 11:38 UTC

**Comment by overclokk** [comment] 2021-11-25 11:40
If it is not possible to remove the wrapper element entirely (I dont' know but there is only a way) then it can be made optional with a controller so if I want to remove the wrapper I don't have to filter the block.

**Comment by youknowriad** [comment] 2021-11-25 11:44
There's already a filter for [render_block](https://developer.wordpress.org/reference/hooks/render_block/) that you can use to filter any block if that's what you wish to do. Personally I wouldn't encourage it as the essence of FSE is to have the frontend match the editor and the user do visual editing for everything but it's up to you..

**Comment by overclokk** [comment] 2021-11-25 11:47
I already used that filter and I know it is a hack, so this is the reason I think it needs to be resolved in the editor.

**Comment by ellenbauer** [comment] 2021-11-25 21:10
Ok, thanks for picking up the discussion about the template tag wrapper here in this issue. I have to admit I'm a bit confused now on how to proceed.

I want to create our block theme template files as stable as somewhat possible for now, so I'm not sure if I should use the `tagname` in the `wp:template-part` to add my header, footer slugs and so on or should I, as someone suggested in #36571 , add an extra div inside the header pattern and include the slug there?

I hope it's ok to ask here, of course we can always update the block theme files, but it would be awesome to have a recommendation on what would be best practice for now.

**Comment by overclokk** [comment] 2021-11-26 07:09
@youknowriad I just saw that reusable block does not have a wrapper on front-end but only on editor and they work fine, so this could be applyed also to wp:template-part block.

@ellenbauer From my point of view the thing is that using the tagName (or every other support|attributes) on `wp:template-part` is a bad design, because you will have to modify every file you imported the needed part if you want to change something, let say you have 20 template (I know bad devs that creates more than 20 templates) and all of them use the same template-part, now if you want to add a new class name you have to open all of the 20 files and update them, if you add the container only in the file itself you will have to midify only one file, are you with me?
In my theme I will use this block as is and add a group block with the tagName I need.

**Comment by ellenbauer** [comment] 2021-11-26 08:28
@overclokk Thank you so much for your reply. Yes, I totally understand the issue. At the moment neither option seems ideal, I think. I guess I wait a bit until I change our current template files and see how `wp:template-part` evolves further.

**Comment by youknowriad** [comment] 2021-11-26 09:04
> @youknowriad I just saw that reusable block does not have a wrapper on front-end but only on editor and they work fine, so this could be applyed also to wp:template-part block.

Yes, and they actually don't work well, we have an issue there for some time and we are not able to find a solution for it. The issue only surfaced after the initial implementation of Reusable blocks so we were not able to add the wrapper there without impact. #8288 (3 years old)

There were several attempts to solve it and none of them worked so far.

**Comment by tomjn** [comment] 2023-03-14 19:47
Is this issue referring to DOM nodes in the editor, or DOM nodes on the frontend? It was suggested that #49071 may be a duplicate of this, but I'm not sure. In my situation the `<div>` is causing inconsistent behaviour between the editor and the frontend, not preserving it

**Comment by talldan** [comment] 2023-03-15 04:22
> In my situation the `<div>` is causing inconsistent behaviour between the editor and the frontend, not preserving it

The other issue doesn't seem to mention these inconsistencies you're having. It'd be good to add extra detail if you can.
