### ISSUE TITLE
Ampersand in post tag causes editor crash

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#12832] opened 2018-12-13 04:15 UTC
**Describe the bug**
It appears that re-using any tag containing an ampersand character on a post causes the editor to crash entirely.

**To Reproduce**
1. Create a new post
2. In the Document tab click on Tags, and enter a tag containing an ampersand, e.g. `foo & bar`
3. Update/save the post
4. Create another new post
5. Again try to type in the tag `foo & bar`, followed by a comma

** What happens**
The editor crashes completely with an error message.

![edit_post_ _my_core_sandbox_ _wordpress](https://user-images.githubusercontent.com/11873759/49915344-c4ceae00-fe9d-11e8-8daf-83c2c3edb34c.png)

**Expected behavior**
For the tag to be added, and to remain after the draft saves

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.1
 - Browser: Reproduced in Chrome 71 and Firefox 63.0.3

**Additional context**
- Gutenberg 4.7.0 (site's on Pressable, and they're not allowing update to Core 5.0 yet)
- Also able to replicate on WordPress.com
- Reported by a WordPress.com user [via Twitter](https://twitter.com/dgtronic/status/1073039369626312704)

**Comment by designsimply** [comment] 2018-12-14 07:18
Tested and confirmed that adding `foo & bar` as a tag a 2nd time to a post results in "The editor has encountered an unexpected error." with the following errors in the console:

* TypeError: "e is undefined"
* Unhandled promise rejection TypeError: "t is undefined"

In the Network panel, the second time you try to add a tag with an ampersand in it such as `foo & bar` to a post, a 400 Bad Request error appears for `/wp-json/wp/v2/tags?_locale=user` with the following response:

* `{"code":"term_exists","message":"A term with the name provided already exists in this taxonomy.","data":{"status":400,"term_id":2}}`

![screen shot 2018-12-14 at 12 11 12 am](https://user-images.githubusercontent.com/1119271/49988645-c7301700-ff34-11e8-9ce1-0eb16fa6e875.png)

Aside: the _first_ time the tag `foo & bar` is added to any post, the result looks like this but the tag is removed from the post if you save.

![screen shot 2018-12-14 at 12 13 53 am](https://user-images.githubusercontent.com/1119271/49988814-6b19c280-ff35-11e8-9c4f-c19f7600554b.png)

<sup>Tested with WordPress 5.0.1 and Gutenberg 4.7 using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by jorgefilipecosta** [comment] 2018-12-14 20:04
Hi @aduth, I started debugging the issue before you assigned it, and then as soon as I found a possible solution I created a PR (https://github.com/WordPress/gutenberg/pull/12889) without rechecking if it was assigned. I'm sorry I should have assigned it to me as soon as I started the debugging I hope you did not start already working on it.

**Comment by KokkieH** [comment] 2018-12-26 12:54
Another report from the [WordPress.com forums](https://en.forums.wordpress.com/topic/getting-this-error-message-when-trying-to-add-rb-tag-to-my-blog-posts-the-editor-has-encountered-an-unexpected-error/) - noting here for follow-up once this is fixed.

**Comment by davoraltman** [comment] 2018-12-31 09:45
The only workaround I found so far is to add the tag via Quick Edit options in the All Posts page. This doesn't cause the error to appear.

**Closed** 2019-01-09 09:06 UTC
Labels: Priority High, [Component] Post Settings, [Type] Bug
