### ISSUE TITLE
Image size text is too close to side on settings

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19423] opened 2020-01-06 12:12 UTC
This might be related to the #19422 and other ones reported today, logging separate as good first issues and incase not. On the image size the input is a little close to the edge:

![image](https://user-images.githubusercontent.com/253067/71817419-b55c6d00-307d-11ea-90af-10f3c0c905ed.png)

**Comment by tellthemachines** [comment] 2020-01-06 23:42
@karmatosed I'm unable to reproduce this on latest master, mac OS (any browser). Could you recheck and close if no longer valid? Thanks!

<img width="267" alt="Screen Shot 2020-01-07 at 10 38 36 am" src="https://user-images.githubusercontent.com/8096000/71857022-15b0e480-313a-11ea-92cd-74efe7f5c8d9.png">

**Comment by karmatosed** [comment] 2020-01-07 14:54
@tellthemachines what theme are you using as this might be theme specific:

Twenty Nineteen:

![image](https://user-images.githubusercontent.com/253067/71904191-9208ef00-315d-11ea-8dd6-7d1ffe09ecb1.png)


Twenty Twenty:

![image](https://user-images.githubusercontent.com/253067/71904020-3fc7ce00-315d-11ea-8d75-3facd367d7a8.png)

I was using today's latest version from master.

Mac Chrome is being used for these but as you can see this is still valid.

**Comment by tellthemachines** [comment] 2020-01-09 03:11
I can reproduce this with Gutenberg 7.2 on a production website, but not on my local dev environment. Seems to be the same issue with CSS bundling as [described here](https://github.com/WordPress/gutenberg/issues/19414#issuecomment-572332893).

**Comment by jorgefilipecosta** [comment] 2020-02-09 16:14
Hi @karmatosed, are you still able to reproduce the issue with the last version of Gutenberg?

**Comment by aktasfatih** [comment] 2020-05-30 12:13
Hi, there is a merged PR #19590 about this problem. I tested it on Gutenberg 8.2.1 with both Firefox and Chrome and the problem seems to be solved. Right now it works for both Twenty Twenty and Twenty Nineteen themes.

**Comment by tellthemachines** [comment] 2020-06-01 00:59
Yup, this issue can be closed now.

**Closed by tellthemachines** 2020-06-01 00:59 UTC
Labels: Good First Issue, [Package] Components, [Type] Bug
