### ISSUE TITLE
Gallery block: UI not updated after re-sizing images

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#27630] opened 2020-12-09 23:41 UTC
**Describe the bug**

The Gallery block "Image size" selector doesn't update to show the currently selected option.

**To reproduce**
1. Add a Gallery block with multiple images
2. In the Gallery block settings panel, change the "Image size" from Large to Thumbnail
3. Notice that Large is still selected

**Expected behavior**
After selecting the Thumbnail image size, "Thumbnail" should be shown.

**Screenshots**

| <img src="https://user-images.githubusercontent.com/1898325/101701885-8d7c4300-3a5e-11eb-9b13-fbdc8d3a3719.gif" alt="Screenshot showing image sizing in Gallery block not working">  |
| - |

**Editor version (please complete the following information):**
- Gutenberg: 9.4.1
- CoBlocks: 2.2.2
- Editing Toolkit: 411483440

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 83.0

**Comment by noisysocks** [comment] 2021-01-06 04:10
Duplicate of https://github.com/WordPress/gutenberg/issues/27492.

**Closed by noisysocks** 2021-01-06 04:10 UTC
Labels: [Block] Gallery, [Type] Bug

**Comment by Hefestos21** [comment] 2021-01-11 15:26
I can replicate the same issue only not all the pics are changed in size. The procedure is pretty random actually, some pics stay in the old size and some update.


    Gutenberg: 9.4.1
  


    OS: Windows 10
    Browser Firefox
    Version 84.0.2
