### ISSUE TITLE
Language Support or Formatting for <Code> block.

### ISSUE THREAD

**Issue by barkz** [WordPress/gutenberg#9336] opened 2018-08-24 22:32 UTC
**Is your feature request related to a problem? Please describe.**
Plugs like Crayon for Syntax Highlighting provide language select support (eg. powershell, python, etc.) This has always been helpful to end users to copy code, clear read via lines#, etc.

**Describe the solution you'd like**
Provide support for the <Code> block to have some type of formatting options or formatting based on a language selection. 

**Describe alternatives you've considered**
I use Crayon on my blog for code/syntax highlighting. There are several others available as well.

**Comment by youknowriad** [comment] 2018-08-24 22:39
I think this could be considered a duplicate of #8331

Personal opinion, I see this as plugin territory.

**Closed by youknowriad** 2018-08-24 22:39 UTC

**Comment by youknowriad** [comment] 2018-08-24 22:41
See https://github.com/mkaz/code-syntax-block
