### ISSUE TITLE
Block Library: Columns: Error when selecting column count before picking a template

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#16397] opened 2019-07-02 17:04 UTC
**Describe the bug**
The Columns block breaks when adjusting the number of columns before selecting a template from the new template picker added in #16129. Relevant to #15663.

**To reproduce**
1. Add Columns block
2. Open the block's sidebar settings
3. Adjust the column count

**Expected behavior**
The columns RangeControl component should not be available for manipulating, until a template has been chosen. After that point, the control should be present.

**Screenshots**
![columns](https://user-images.githubusercontent.com/1813435/60531651-72ce6800-9cc9-11e9-99c4-4d5b9a99a739.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Majave
 - Browser: Safari

**Additional context**
- Gutenberg 6.0

**Comment by Soean** [comment] 2019-07-02 17:08
Thanks @richtabor for reporting this issue, seems like a duplicate of #16343

**Closed by Soean** 2019-07-02 17:08 UTC
Labels: [Block] Columns, [Type] Bug
