### ISSUE TITLE
Writing Flow: Repeated multi-selection in consecutive blocks of same type limited to two blocks

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9848] opened 2018-09-12 21:03 UTC
**Describe the bug**

When using Shift+ArrowDown to create a multi-selection, it is not possible to select more than two blocks of the same type†.

† "Of the same type" is important to note because the block transform toolbar option only appears when the multi-selection consists of blocks of the same type. I suppose it should also be noted that it might only be an issue for blocks of the same type which have transform options.

**To Reproduce**

1. Navigate to Posts > Add New
2. Add three paragraphs
3. Select the first paragraph block
4. Shift+ArrowDown to select all three blocks
5. Observe that after the second block becomes selected, the next Shift+ArrowDown causes focus to be moved into the transform modal, rather than continuing the multi-selection.

**Expected behavior**

I should be able to multi-select as many blocks as I continue to Shift+ArrowDown.

**Comment by aduth** [comment] 2018-09-12 21:05
In fixing this, we should add an end-to-end test case to protect against future regressions.

**Comment by youknowriad** [comment] 2018-09-13 07:39
So I tried looking at this and it's not an easy fix: The issue is where should we put the focus when we're on multi-selection and when.

For example, when you shift+arrow to select two blocks, do you leave the cursor in the first block's RichText or do you move elsewhere while you're still selecting (shift is still pressed)? 

Right now the behavior is: we put the cursor in the block toolbar as soon as we select more than one block even if we didn't finish the multi-selection. This creates a bug when multiselecting with the keyboard because sometimes the toolbar is not displayed inside the "WritingFlow" making it impossible to continue the multiselection. And even if we showed the toolbar inside WritingFlow, it's not working great because it conflicts with the toolbar's navigation.

Should we move the focus to the container of the first block instead, I feel like this would solve all issues?

**Comment by youknowriad** [comment] 2018-09-13 07:41
cc @jasmussen

**Comment by jasmussen** [comment] 2018-09-13 07:53
GIF:

![shift select](https://user-images.githubusercontent.com/1204802/45474726-c2dc3e00-b73a-11e8-9a46-ae0495d9c70a.gif)

So as far as solutions go, can we do the following?

- When you're in a a single text block, shift tab enters the toolbar.
- When you've selected multiple text blocks, you still have to press shift tab to enter the multi toolbar.

**Comment by youknowriad** [comment] 2018-09-13 08:00
The issue is not about entering the toolbar but about where to put the focus when multi-selecting and still allowing to continue the selection.

**Comment by jasmussen** [comment] 2018-09-13 08:11
Gotcha, CC: @iseulde in case she has input as well.

When I click a text block and set focus on it, focus according to my bookmarklet is on:

<img width="440" alt="screen shot 2018-09-13 at 10 09 39" src="https://user-images.githubusercontent.com/1204802/45475629-3aab6800-b73d-11e8-8ee3-edb75c004195.png">

When I press "shift tab" that puts me into the block toolbar. 

Is there an equivalent in multi selections we can set focus on, where shift tab would set focus in the block toolbar? My point is that multi selection across more than two blocks still works, the problem here is that the dropdown menu opens, which means if the dropdown menu doesn't have focus, that should solve it. All we need to ensure is that the block toolbar is still tabbable.

Where is focus set when you tab to a new block? Possibly tangentially related: #9858.

**Comment by youknowriad** [comment] 2018-09-13 09:04
The multiselection doesn't work if you're in Unified toolbar mode and I believe `alt + f10` is the keyboard shortcut to navigate to the toolbar right?

**Comment by mcsf** [comment] 2018-09-13 10:54
Possibly related: when multi-selecting with the _cursor_, the caret unexpectedly appearing:

![gutenberg-multi-selection-caret](https://user-images.githubusercontent.com/150562/45484303-8c5aef00-b74b-11e8-97a6-7b050db1e93c.gif)

(in the GIF above, it only happened the second time, likely due to Licecap interaction)

**Comment by mcsf** [comment] 2018-10-15 17:42
> Possibly related: when multi-selecting with the cursor, the caret unexpectedly appearing:

Tracked in #10617.

**Comment by gziolo** [comment] 2018-10-29 19:14
Looking into it.

**Comment by gziolo** [comment] 2018-10-29 19:34
It looks like this behavior to focus block transformed for 2 or more blocks of the same type was added with #9572. This logic isn't triggered when:
- a single block is being edited
- two or more blocks are selected but one of them  has different type - in effect block transformed isn't displayed

I would argue that for consistency we should remove this behavior altogether which will solve the original issue and will bring back consistency. Any objections?

**Comment by jasmussen** [comment] 2018-10-30 08:28
Thank you SO much for looking! This is critical path stuff. 

> I would argue that for consistency we should remove this behavior altogether which will solve the original issue and will bring back consistency. Any objections?

This sounds right to me. But to understand why this change was introduced, can you clarify the following a bit?

> two or more blocks are selected but one of them has different type - in effect block transformed isn't displayed

So whether or not the transform button should be there, is what triggers this issue, correct?

I would say overall, that so long as you can tab (or shift tab) into the transform menu from a multi selection, it's fine to remove that behavior.

**Comment by youknowriad** [comment] 2018-10-30 12:47
closed by #11237

**Closed by youknowriad** 2018-10-30 12:47 UTC
Labels: Priority High, Regression, Writing Flow, [Component] Multi-Select, [Type] Bug
