### ISSUE TITLE
[Pull Quote Block] Setting a left/right text alignment applies a max width on the block

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#42247] opened 2022-07-07 19:23 UTC
### Description

By default, the text in the pull quote block is centered. If you change the text alignment to either left or right, the pull quote block unexpectedly gets a max width of 420 pixels.

### Step-by-step reproduction instructions

1. Add a pull quote block.
2. Set the text alignment to either left or right.
3. The block gets a max width of 420 pixels.

### Screenshots, screen recording, code snippet

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8181091/177855086-1a804918-d941-4657-97ac-31bec547458e.png">

In the screenshot, a wide group with a background color contains a pull quote with a text alignment set to left. If left to a centered text alignment, the pull quote block fills the group, as expected.

### Environment info

WordPress 6.0
Gutenberg 13.6.0
Twenty Twenty-Two
Safari 15.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-08-04 09:52
I am not able to reproduce this using the text alignment. If I use the block alignment, yes. But I believe that is expected, so that items can align next to each other.

**Comment by andersnoren** [comment] 2022-08-06 08:55
It seems this doesn't happen if the pull quote is a direct descendant of the entry content, since the pull quote will then have the max width set to the content width with a higher specificity. If wrapped in a group, the 420px max width is applied (when set to a left/right text alignment).

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/8181091/183242173-7adbb75f-e140-43ea-ac91-b8930725d897.png">
↑ Not wrapped in a group

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/8181091/183242147-20d4dd26-03e2-4f04-8ae7-32520397daff.png">
<p>↑ Wrapped in a group</p>

<p>Note that the 420px CSS is still there in the inspector in the first image – it's just overwritten.</p>

**Comment by Mamaduka** [comment] 2022-08-23 14:49
The issue was fixed via #43188.

**Closed as completed by Mamaduka** 2022-08-23 14:49 UTC
Labels: [Type] Bug, [Block] Pullquote
