### ISSUE TITLE
Duplicates, triplicates, quadruplicates widgets.. into the Legacy widget's block selectbox

### ISSUE THREAD

**Issue by imath** [WordPress/gutenberg#32019] opened 2021-05-19 19:41 UTC
## Description

Hi,
First congrats for the work achieved so far about the Widget Block Editor. I've started working on migrating the [BuddyPress Legacy widgets](https://github.com/buddypress/bp-blocks/issues/37). So far it's going great. I just noticed something weird about legacy widget block: the select box is listing more than once widgets as soon as you add/remove a widget.

## Step-by-step reproduction instructions

1. Download [BuddyPress trunk](https://buddypress.trac.wordpress.org/browser/trunk?rev=12951&format=zip) (a fix has been added to avoid the use of `get_current_screen()` function to cause a fatal into the new Widget Block editor screen).
2. Rename the unzip folder to `buddypress`
3. Install & Activate BuddyPress
4. Go to the new Widget Block editor screen
5. Add a legacy widget block
6. Select one of the BuddyPress widgets
7. Update the Widgets
8. Remove the just added BuddyPress widget
9. Update the Widgets
10. Refresh the page
11. Add a new Legacy Widget block, now the select box contains 2 duplicate options for the BuddyPress widget you added/removed.

## Expected behaviour
Only list a widget once into the select box of the Legacy widget block

## Actual behaviour
Duplicates as soon as you add/remove a legacy widget

## Screenshots or screen recording (optional)

![dupes](https://user-images.githubusercontent.com/1834524/118873357-f27b7500-b8e9-11eb-85cf-859a4202dadb.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? No, BuddyPress is activated to test plugin widgets.
- Are you using a default theme? Yes Twenty Nineteen

## Device information
- Device: Desktop
- Operating system: macOS 10.13.6
- Browser: Google Chrome 90.0.4430.212

**Comment by tellthemachines** [comment] 2021-05-25 05:18
I can reproduce this with both WooCommerce and SiteOrigin widgets, but only on the second delete. So my steps are: 
1. Add a legacy widget, save page, delete widget. 
2. Refresh the page, repeat process with same widget.
3. Refresh the page again and verify that widget is repeated in the legacy widget block dropdown.

I can also reproduce the issue by adding two identical legacy widgets in the same widget area, saving and refreshing the page.

Deleting all widgets (including inactive) from the old widgets screen fixes the issue.

**Comment by noisysocks** [comment] 2021-05-31 06:46
Thanks for the report! This is due to a REST API bug which will need to be fixed in core now that that code has been merged. I've opened https://core.trac.wordpress.org/ticket/53305.

**Closed as completed by noisysocks** 2021-05-31 06:46 UTC
Labels: [Type] Bug, [Block] Legacy Widget
