### ISSUE TITLE
Group Block - add support for Background Images

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#14744] opened 2019-04-01 13:41 UTC
The [Group Block recently merged](https://github.com/WordPress/gutenberg/pull/13964) with support for background _colors_. As a next step, it would be good to add support for background images along with the focal picker.

#### Describe the solution you'd like
This would upgrade the Group Block with the following:

- Ability to choose a background image as the background
- Ability to pick the focal point for that background image
- Ability to set color overlay (as per `cover` Block) (thanks to @SchneiderSam )

#### Considerations

* Would this bring the Block too close to the current `cover` Block? Or should we encourage users to utilise a `cover` Block within a `section` to achieve this?

**Comment by SchneiderSam** [comment] 2019-04-01 13:52
Great would be in this move also a color overlay as with the Cover Block.

**Comment by youknowriad** [comment] 2019-04-02 07:46
Yeah, I'm not sure about this as this will just be a cover block in the end if we do this.

**Comment by SchneiderSam** [comment] 2019-04-02 10:47
As an end user, I understand it this way:

**Cover Block:** a block to add text to a background image at the beginning of a post. Alternatively it can also be used in the middle of a post as call-to-action.

**Section Block:** can do anything. Columns, background color, background image, Section in Section, ect... Simply: The LEGO building block for a website.

It would be great to know which block should be used for what. For me the cover block is completely superfluous. The Block section should have all the functions currently available in the cover block.

A section block without the possibility to insert pictures just doesn't make sense. This is a must have!

**Comment by youknowriad** [comment] 2019-04-02 10:51
> A section block without the possibility to insert pictures just doesn't make sense. This is a must have!

Thanks for sharing your opinion, let's keep the discussion flowing but let's avoid "absolute" statements. "this doesn't make sense, this is a must have".

**Comment by SchneiderSam** [comment] 2019-04-02 11:18
Ok. Sorry!

**Comment by oxyc** [comment] 2019-04-03 23:01
I would prefer if the cover block (and all blocks with InnerBlock) supported filtering the list of allowed inner blocks. The themes that want to add 3 columns inside a Cover Block could write the styles to support it.

**Comment by truchot** [comment] 2019-04-28 21:55
Why not use the cover block if the aim is to have a background image ?

**Comment by bbertucc** [comment] 2019-05-07 19:49
@truchot - the cover block doesn't support nested blocks. 

Adding to @getdave's feature request: The ability to fix image position and add a background overlay.

**My use case**: 
I want to create a masthead with a header, subtitle and button. Masthead like these are very common. See Bootstrap's [Punny headline](https://getbootstrap.com/docs/4.3/examples/product/).

**Comment by truchot** [comment] 2019-05-07 19:53
> @truchot - the cover block doesn't support nested blocks.

Yes it does :)

1. You can install Gutenberg as a plugin to get last features 
2. Or wait WordPress 5.2 that will be released very soon

**Comment by bbertucc** [comment] 2019-05-07 19:56
o perfect @truchot! Didn't catch that in the release notes. 

My question now: Why not get rid of the cover block and just add the same background settings to the group? We can add the extra spacing with a spacing block

**Comment by melchoyce** [comment] 2019-05-15 15:36
Mockups:

![Image](https://user-images.githubusercontent.com/2846578/57787187-ea890900-7702-11e9-8dca-e3a4d4de72de.png)
![Color](https://user-images.githubusercontent.com/2846578/57787201-eceb6300-7702-11e9-87dd-d8035081d606.png)

_(Please note that as this is an older mockup, many general UI elements are outdated.)_

Some questions:
- We'd be reusing image settings from Cover.
- Instead of overlay color, I'm using opacity, so color and image can remain independent. Does this make sense?
- Should we use the new swap image flow for changing background images and include an image icon in the toolbar, instead of putting it in the sidebar?
- Is there any way to measure color contrast of text over an image?

**Comment by SchneiderSam** [comment] 2019-05-15 17:05
Well, I still think that's a great thing. I hardly use the cover block at all. I'm a big fan of these groups and at the moment I'm still solving everything about the function: individual classes. If this is pushed further, it would be a nice thing for the end user! Please carry on!

**Comment by getdave** [comment] 2019-05-22 15:22
This wouldn't be that difficult to achieve. Personally, I feel it is a worthy addition to the Group Block, but I know others have reservations.

**Comment by afercia** [comment] 2019-05-24 14:28
Discussed during today's accessibility bug scrub, agreed on a couple recommendations:

- Important settings in the sidebar should be avoided: this is part of the long standing issue related to navigation from the content area to the sidebar and back. Noted in many other issues and PRs. All controls that are essential to producing content should be within the block itself. We, as a team, recommend to reconsider and place the most important ones within the block
- re: "Is there any way to measure color contrast of text over an image?". Not that we're aware of. This always require manual checking. An idea could be a short explanatory text to inform users to take care of the contrast.

**Comment by melchoyce** [comment] 2019-05-24 14:37
> All controls that are essential to producing content should be within the block itself. We, as a team, recommend to reconsider and place the most important ones within the block

Which setting are the a11y team thinking?

**Comment by afercia** [comment] 2019-05-24 16:20
We haven't discussed specifically which settings. Personal opinion: all the ones that are needed to "get the job done" :) at the very least: edit / replace / remove image.

**Comment by klihelp** [comment] 2019-06-10 18:56
+1

**Comment by LyleBennett** [comment] 2019-06-12 15:08
Either being able to nest more blocks (especially columns) in the cover block; or adding background image and overlay to the groups block would be great.

**Comment by SchneiderSam** [comment] 2019-06-12 16:11
> Either being able to nest more blocks (especially columns) in the cover block; or adding background image and overlay to the groups block would be great.

Absolutely. It would be nice if a decision was made.

**Comment by boemedia** [comment] 2019-06-12 19:08
We discussed this in today's design meeting. It seems like there's a need for a background image option in the group block. However, at this point, it starts competing with the cover image block and I think it would be a good idea to have one type of block for both a start of a page post or a section with all forementioned functionality.

**Comment by SchneiderSam** [comment] 2019-08-10 21:45
Are there any developments here? I find this function so fundamental and I as an end user somehow **get totally mixed up when to use a group block and when to use a cover block**. That's kind of confusing.

After posting mtias in #16479 the goal is to add a background function here. Is there a roadmap @getdave or @youknowriad ?

**Comment by LyleBennett** [comment] 2019-08-12 07:21
#16751 Was merged and this helped a fair amount for me @SchneiderSam. It seems like a great quick fix to me until #16479 can be implemented. Interested to see how the cover/group similarities are addressed in the future.

**Comment by amandablum** [comment] 2019-09-11 15:15
relevant use case for bg images not currently supported- repeating bg images on a block, for patterns, etc. This is a common design element in modern sites (think of a pattern on a row). The cover block doesn't address this because the image is set to cover, and while it sounds like section will, only if the tools to repeat the bg image are included. seems more appropriate to the section, so you could include other elements. 
bg image:
![cubes](https://user-images.githubusercontent.com/2366499/64709933-edef8f80-d46b-11e9-8ee8-3e3e28adcbfc.png)
in use: 
![cubesfull](https://user-images.githubusercontent.com/2366499/64710092-327b2b00-d46c-11e9-8c57-84702f0ddcf8.png)

**Comment by getdave** [comment] 2019-10-23 13:46
This was discussed in Core Editor chat in Slack https://wordpress.slack.com/archives/C02QB2JS7/p1571837618043400 (requires signup).

We agreed that we should incrementally improve Group and retain Cover for the foreseeable future.

Therefore adding this feature is valid.

**Comment by bharath** [comment] 2019-10-23 14:18
That's good news @getdave . Thank you.

**Comment by woorise** [comment] 2020-02-09 06:45
+1 for background images in Group block

**Comment by PaddleStroke** [comment] 2020-03-26 07:31
Did it happenned already?
Cover block is not much use currently as only one block of text can be inserted, and it's not possible to choose the position.
+1 for background images in Group block and get rid of cover as it would mean merging cover functionnality in the group block.

**Comment by bfiessinger** [comment] 2020-05-13 18:11
Are there any news on this?

**Comment by noahtallen** [comment] 2020-05-13 18:14
I investigated it several months ago and didn't land on a clear solution by myself. I also have other priorities at the moment, so I can't look into it any more

**Comment by Tymek** [comment] 2020-05-15 09:24
I'd like to take a shot at it. What should I watch out for?

**Comment by ayyilmaz** [comment] 2020-07-05 15:33
We are waiting for this nice feature. I hope this feature will be released in near future.

**Comment by draganescu** [comment] 2021-01-12 16:22
Could we use the same mechanism that the post featured image use?

**Comment by draganescu** [comment] 2021-01-12 18:06
Should this support videos as well like the cover block does?

**Comment by paaljoachim** [comment] 2021-01-13 21:36
I would say if it is in the Cover block then it should also be in the Group block.
@Tymek if your still up for it then you can probably work with @draganescu Andrei to get this into place.

**Comment by jasmussen** [comment] 2021-01-14 07:32
I think the big challenge here isn't a lack of desire to add this, but rather, adding it in a way that is a good user experience and does not make the group block, which is widely used, any less stable. UX wise, I like to think that #27331 will benefit this a lot.

**Comment by stokesman** [comment] 2021-01-18 20:25
I think there's an opportunity here to surpass what's been done with the Cover block in terms of feature support and user experience. I see #20193 as pointing the way, though the proposal isn't very fleshed out. It ought to offer a better experience because it's a more [directly manipulable interface](https://developer.wordpress.org/block-editor/designers/block-design/#the-primary-interface-for-a-block-is-the-content-area-of-the-block). With regard to features, the impetus for the proposal seems to have been providing custom background-size support which is lacking in the Cover block. 

It may add to the challenge of getting this in for WP 5.7. For one thing, it wants for #25890 to have landed (not absolutely needed but it was suggested for 5.7 already). Also since the design proposal isn't fully fleshed out there are still UI details to figure out.

**Comment by Snadex** [comment] 2021-01-20 11:45
Guys, let's be honest with ourselves here - 
the Group block is the de-facto "Section" block, and everybody is using it to group multiple inner blocks into a section simply because there is no other option. 

It has a Background setting - you can put a background to that block. I really can't get my head around, why would we limit ourselves to Color backgrounds only in 2021?! Yes, I'm sure there are challenges, backward compatibility, and so on, but these are just details to overcome. If it's gonna have a background option then it has to be full. If not, just remove it and call that it should NOT have any background. This middle state is just non-sense. (sorry if being too direct, but it is the truth)

**Comment by bnikkhah** [comment] 2021-02-19 17:58
I'm a front-end developer and the pain point I find about the _Group_ block not having a background image is because of the section hierarchy. For example, let's say you have a section without a background image and you send it off to the client. The client comes back in a month or two and says, "Oh, I would actually like a background image on this section".

So, when we go back to the section we find the hierarchy of the section reads like this:

`Group > Container > Row >` etc.

However, we need the hierarchy to now read like this:

`Group > Cover > Container > Row >` etc.

The easiest way to go about this is to copy everything from _Container_ down and then paste it once the _Cover_ block has its background image, but it would be _much_ easier to simply add a background image to the _Group_ block.

I'm guessing the WordPress team is trying to avoid _bloat_ in their code because once _Group_ blocks support background images, then the code from the  _Cover_ block needs to be copied over to the _Group_ block which may cause two things:

- The _Cover_ block will now become less attractive; and
- The _Group_ block now has the same or most of the _Cover_'s block functionalities and might cause bloat

I'm assuming the WordPress team has their reasons for the _Group_ block not having background images yet, but I'm certain that front-end developers will have an easier time making section revisions if this was to become a feature for the _Group_ block.

**Comment by draganescu** [comment] 2021-02-26 10:09
This is something that a lot of folks support and it does make a lot of sense. However, today, the tools used by the cover to set backgrounds are not standardized. There is a lot of logic around handling various media formats (images, videos) and other items such as color, overlay, transparency and so on.

Simply porting all that to the group block would add (as @bnikkhah suggests) quite a bit of bloat. Plus, ideally, any block should have access to adding background controls, not only core blocks, and it should be in a simple straightforward way.

One way in which blocks declare support for features is the block `supports` API accessible via the `block.json` configuration file. However, that is not yet able to handle the peculiarities of backgrounds. Some backgrounds, in order to work well, require markup and the block `supports` API does not allow adding markup, nor does it handle it.

So, while there is a lot of interest and support around improving the group block and in general in unlocking the potential of using background tools (see https://github.com/WordPress/gutenberg/issues/28643), it's tricky and has a lot of complexity to step around. However, it's obvious, from this thread alone this is something that is both important and incoming :)

**Comment by wwdes** [comment] 2021-04-15 19:51
The biggest difference between a group block and a cover block to me is that gutenberg does not add any "padding" to group blocks. The second thing is that groups don't allow images.

I am trying my best to come up with reasons to why I would need two blocks instead of one unified block. If someone has examples please do tell.

A merge of these blocks would be a move in the right direction in my opinion, but seeing as that may take a while, ability to transform a cover block to a group would be nice. Right now when you transform a cover to a group it actually only wraps the cover in a new group, which is weird to say the last considering that the triple dot dropdown in the block toolbar already has a perfectly fine "group" button.

**Comment by stephendwolff** [comment] 2021-05-01 22:22
> `Group > Cover > Container > Row >` etc.

@bnikkhah has a point. I can't find a way to make a `Cover` block inside a group, then add a `Column` block to decide how i'm going to proceed with a layout that isn't just a full width background image with a more complex layout inside. This strikes me as slightly insane, as with basic HTML building blocks this is very simply possible. We now have a very mature Wordpress with a new content 'arranger' which can't do something basic. i can't think of any reason apart from Wordpress allowing their ecosystem to provide tools which could easily be part of the existing offering.

**Comment by getdave** [comment] 2021-05-05 11:58
> Right now when you transform a cover to a group it actually only wraps the cover in a new group, which is weird to say the last considering that the triple dot dropdown in the block toolbar already has a perfectly fine "group" button.

I agree that we should consider removing the Group `transform` action and instead create a new piece of UI such as "Wrap with" (I'm avoiding the word "Group" here). It's a little confusing saying you will transform to "Group" when that isn't actually what happens.

**Comment by j-nicolas** [comment] 2021-06-10 14:11
Hi there!

**"Section":**

What we have is:
```
.wp-block-group
  .wp-block-group__inner-container
    <!-- here we might have a width restriction -->
```
What we need is:
```
.wp-block-group
  .wp-block-group__bg-container  <!-- wow! - this is new! -->
  .wp-block-group__inner-container
    <!-- here we might have a width restriction -->
```
**What means:**

The `.wp-block-group__bg-container` has _no_ width-restrictions, 
fills the complete outer container (and has z-index: -999 by default)
and can be
- CSS-background
  - color
  - gradient
  - image
- HTML-canvas (!)

The best would be: with _additional_ overlay like cover-block already has.

Yeah!  :)

**Comment by stephendwolff** [comment] 2021-06-10 14:14
I just ended up using a Cover Block in the end with a background, then inserted a Group Block inside it. The UI isn't intuitive which is why i completely missed it. You have to hit return to add another block inside the Cover, then the + appears. The Group Block can be picked the (or Column or whatever), and content added as desired. The extra text block (from the return) can be deleted.

**Comment by j-nicolas** [comment] 2021-06-10 14:16
> I just ended up using a Cover Block in the end with a background, then inserted a Group Block inside it. The UI isn't intuitive which is why i completely missed it. You have to hit return to add another block inside the Cover, then the + appears. The Group Block can be picked the (or Column or whatever), and content added as desired. The extra text block (from the return) can be deleted.

I tried this (inserted a group including columns into the cover) but the UI failed (it didn't appear)
but
I'LL TRY AGAIN  :)

**Comment by stephendwolff** [comment] 2021-06-10 14:21
good luck! i think it took me a while to realise it had actually worked. The UI needs work!

**Comment by j-nicolas** [comment] 2021-06-10 14:55
WORKS! Thank you!

**Comment by strarsis** [comment] 2021-09-06 17:13
Just ran into this issue again today. Well, I still have to use a cover block inside the column block.
One could philosophize that the job of the column block is to ensure the layout, and the cover block to show a background color/image behind its content.
On the other hand, the functionality of some blocks overlap and they differ in their meaning instead (heading and paragraph).

Re-usable blocks can help a bit - but what if I want to re-use the same re-usable block aggregate and just change e.g. the text of one heading block and the background image of the cover block inside? Or change the blocks for all of these at the same time?

**Comment by afmarchetti** [comment] 2022-02-09 15:35
Any news on this? it will be super usefull, for developers and client have this simple feature near the colors.

**Comment by getdave** [comment] 2022-02-09 17:17
AFAIK there's been no progress here. There seems to still be strong demand though. I will raise this for discussion in next week's Core Editor chat (unless someone else would prefer to?).

**Comment by afmarchetti** [comment] 2022-02-10 13:38
@getdave it will be super useful! i think it's the natural evolution of the component as a developer that what to use gutenberg i will use it al lot. Can i participate in some way at the discussion?

**Comment by getdave** [comment] 2022-02-10 13:48
@afmarchetti It would be great if you were to raise the question. [The Core Editor agenda is posted here](https://make.wordpress.org/core/tag/core-editor-agenda/) early next week. When it's up leave a comment saying "For the Open Floor". You can then reference this Issue and ask your question. It will be raised for you in the chat even if you cannot attend.

I would highly recommend adding some detail beyond just "who will work on this". Ideally presenting a clear use case and illustrating the level of demand (such as you can determine). This will help to make the conversation more productive.

The Core Editor chat can be joined in the `#core-editor` channel at 14:00 UTC by signing up for [Core WordPress Slack](https://make.wordpress.org/chat/). You can then participate in real time.

**Comment by getdave** [comment] 2022-02-15 09:34
If anyone is keen to see [background images land in the Group block](https://github.com/WordPress/gutenberg/pull/38784) then please do add your 👍 to [this experimental PR which looks to add that feature](https://github.com/WordPress/gutenberg/pull/38784). 

<img width="1019" alt="Screen Shot 2022-02-15 at 09 34 27" src="https://user-images.githubusercontent.com/444434/154034098-5e90b810-1976-44a8-8724-bd0a0a000684.png">


It would be helpful to gauge the current demand for the feature. Many thanks 🙇

**Comment by masteradhoc** [comment] 2023-01-31 21:46
+1!

**Comment by room34** [comment] 2023-02-16 01:04
I'm guessing since there's been little movement on this for a year, it's not happening, but I would like to advocate for it. Adding the ability to put a background image on a Group does _not_ just make it a Cover block. The Cover block is much more "opinionated" in the placement of inner content than a Group is.

I would argue that adding the ability to put a background image on a Group _might_ obviate the need for the Cover block at all, but I think there's room for both of them. A good way to think about it is that the Cover block is _primarily_ about the image (with limited options for overlaying content), whereas the Group is _primarily_ about the inner content… and would probably have more limited options for handling the background image. For example, the "Minimum Height of Cover" setting would not make sense, because the inner content of the Group would dictate the height of the image.

**Comment by wwdes** [comment] 2023-02-16 01:57
Imo both group and cover block are a failed concept. This “simplicity” or “less is more” type of interfaces always end up being too niched and opinionated. People come to this repo and make suggestions like these, hoping that the development of the block builder will somehow skew towards some utopian free and flexible site builder, which is not what the devs have in mind. If it were then there should have been a container block with ALL the features and all other blocks would have had lots more features, basically following the 3 C’s holy grail of content and page building. Then they would have implemented an API, like the theme json, where features would have been turned off/on or customized. They could even come up with a default config to keep the interface simple and blog oriented or whatever. Of course this will not happen for lots of reasons.

**Comment by jamieschmid** [comment] 2023-04-18 13:39
Is this not a feature at all? How else are you supposed to put a background on a container with core blocks? Maybe I'm missing something but the cover block is not a container, it's kind of a superfluous feature block in my opinion that has few uses. A group block is incredibly flexible, limiting it to only color backgrounds makes no sense. I wonder if it's a limitation in how the block is built? Any other ideas on how to get a background on a container using core blocks?

**Comment by room34** [comment] 2023-04-18 14:19
@jamieschmid
> Is this not a feature at all?

Well… it kind of is; you can put any blocks into the inner container of a Cover, including a Group. But that does still leave some weird issues because the Group is inside the Cover's more restrictive padding rules.

It just seems to me that the Cover block conceptually missed the mark; eliminating it and giving the Group block some of Cover's capabilities (background image + its positioning/sizing features, overlay color) would address this concern.

The problem is a lack of a singular cohesive and comprehensive vision for Gutenberg from the outset, but that kind of Platonic ideal was never possible in reality. Overall I think Gutenberg has shaped up much better than I expected it to early on, but this weird dichotomy between the Cover and Group blocks is definitely a sticking point.

I'm guessing the biggest deterrent to combining them would be that the Cover block is something conceptually easier to understand for novice users, who seem to be a primary intended audience for Gutenberg… even though I do _not_ think Gutenberg is easier for novices to understand.

**Comment by paaljoachim** [comment] 2023-05-02 17:27
https://github.com/WordPress/gutenberg/issues/49273
https://github.com/WordPress/gutenberg/pull/49992

The Site Logo block now has in a recent Gutenberg plugin a Media panel for uploading/adding an image as a site logo.
![Screenshot 2023-05-02 at 19 06 36](https://user-images.githubusercontent.com/5323259/235739759-ae92d035-925e-4706-a3df-1d4e4b9f0c5a.jpg)

What about adding the media panel to the Group block. To which clicking Add media opens a drop down of options such as Media Library, Upload, URL etc? To which one would be able to add a background image or video.

**Comment by draganescu** [comment] 2023-05-11 16:06
@paaljoachim the site logo _is media_ - an image we decied it has the meaning of Logo. But backgrounds are style, it should be set from the design panel I think?

**Comment by porg** [comment] 2023-06-13 15:51
## Further use cases
  - Background-patterns (repeating image tiles) for Group block (my use case why I came here)
    - In other words: #49106
    - Or open up a possibility for plugins: #51465
  - For template editing: #38436


## Possible way forward?
- I agree that the Cover block is superfluous.
- Dropping it is a though decision to make I guess (legacy!)
- **Idea for a feasible compromise:** Make the Cover block a [block variation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/) of the Group block. That could be the solution to all issues raised:
  1. **Efficient Codebase:** Image block just a variation of the Group block.
  2. **Usability:** Beginner users who primarily want a "Cover block" can still so add it it via Block Inserter like a "true block" and still have the reduced UI and interactions and do not need to discover this more hidden as sub-options of the powerful Group block.
  3. **Legacy:** Deprecated cover blocks in all templates/pages/posts can get auto-transformed to the corresponding Group block variation.
  - When/how would need to be decided.
    - WordPress → Tools > Transform deprecated blocks
    - Or during an update: Admin gets notified prior/after update.
    - In both cases: Link to help page, which tells about the deprecation, and FAQs for a smooth upgrade process.

**Comment by Ren2049** [comment] 2023-06-13 16:15
@porg 

Sounds good, together with the group renaming option it would give the site editor a huge boost in usability. Is there a possibility to have a dedicated color for the group block, e.g. green, complementing the purple of template parts when it's used as the outer wrapper?

**Comment by t-hamano** [comment] 2023-06-21 04:55
Since this issue was first submitted, various features have been added to the Cover block.

- The featured image is available: #39658
- HTML elements can be changed: #46969
- Has lots of block support ( align, anchor, color, spacing, typography, border)
- Supports the flow layout: #45326
- Has `allowedBlocks` and `templateLock` attributes
- Has duotone support: #26752
- Can convert from group block: #30890

What would be the ideal approach in light of the latest Gutenberg specifications?

**Comment by jasmussen** [comment] 2023-06-22 07:51
> What would be the ideal approach in light of the latest Gutenberg specifications?

The primary blocker for bringing background support to the group block has been maturing the inspector controls to afford them. The interface from the Cover block shows that in the current implementation it doesn't scale well:

<img width="1392" alt="Screenshot 2023-06-22 at 09 48 04" src="https://github.com/WordPress/gutenberg/assets/1204802/7bf1ae3b-3c22-40ac-88b5-8acd8317c34a">

I think we have a path forward with the recent inspector interface that landed for the Site Logo block:
![site logo](https://github.com/WordPress/gutenberg/assets/1204802/a00af471-d4f2-493b-9c9e-cadb6f7b6050)

Essentially here, the media is a single small ItemGroup Item, both before and after adding media. That's just a raw media item with no background property, but the inspector compactness is one to follow, and it would seem like we can add background properties in a flyout menu, similar to how we have flyout menus for color.

**Comment by porg** [comment] 2023-06-27 21:08
@jasmussen I concur regarding Inspector controls in particular and also in general that in the Inspector Panel one accumulates way too much time…

**… scrolling** 
  - e.g. the inline text hints are always there, also when long learned already, no way to dismiss/collapse them.
  - ultra huge controls (contemporary webdesign trend ok for content, but to be used with care with UI elements/widgets)

**…clicking** the same long pathways again and again due to:
  - #49268  

The Inspector panel UI certainly **needs compacting** and clever minimalism to get efficient.

**Comment by porg** [comment] 2023-06-27 21:23
Dear Gutenberg team, @mtias @getdave @annezazu @mrfoxtalbot @jameskoster @jasmussen, et al

An overarching UX topic like **optimizing the content/inspector interaction and the inspector controls** would require a closer integration of me into the team. This makes me think…

Are you in need of an extra Senior UX Designer in your team?
  - Many of you here have interacted with [me on Github](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+author%3Aporg+sort%3Acomments-desc) or WP.org in some of my volunteer contributions so far.
  - Should I apply to join your team?

**Comment by annezazu** [comment] 2023-06-27 21:53
Anyone is welcome to apply to work for Automattic but this definitely isn't the right avenue to discuss. Let's keep it focused on the work at hand. If you'd like to talk about life at Automattic, feel free to ping me on WordPress.org slack (@annezazu there too).

**Comment by andrewserong** [comment] 2023-08-25 05:40
> I think we have a path forward with the recent inspector interface that landed for the Site Logo block:

I really like the approach used in the Site Logo block. Between that and recent work with the HTML Tag Processor, I think we're likely in a good place to re-explore adding in a background image / media block support now.

I've opened up a draft PR over in #53934 exploring one way to implement it if anyone would like to take a look!

**Closed** 2023-09-08 08:50 UTC
Labels: [Type] Enhancement, [Type] Accessibility (a11y), [Status] In Progress, Needs Dev, [Block] Group

**Comment by andrewserong** [comment] 2023-09-11 01:40
Now that the initial version of background image support has landed in #53934, I've opened up a follow-up issue for ideas for enhancements over in #54336. Feel free to add any ideas there! I imagine most enhancements will likely be for releases beyond WP 6.4.
