### ISSUE TITLE
Columns Block: Provide Gutter Size Control

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#24058] opened 2020-07-20 15:02 UTC
I often wish the block has gutter size control to make a design like this example.

![Frame 4](https://user-images.githubusercontent.com/908665/87951779-eabc2b80-caa0-11ea-8e32-82caeefbfa1a.jpg)

Currently, this is impossible to do with the column block as it always adds gutters.

![Frame 5](https://user-images.githubusercontent.com/908665/87951932-1ccd8d80-caa1-11ea-8e4e-1dd6f01ec063.jpg)

I've seen an exploration adding presets like `None, S, M, L`, but I don't believe that it'd satisfy the various needs, and I personally prefer a fine control similar to the setting added to the Cover block.

**Comment by richtabor** [comment] 2020-07-20 16:37
At CoBlocks we're thinking through a component that supports `None`, `S`, `M`, `L`, and `(custom)` for sizing controls such as gutter. Our plan is that `S`, `M`, `L` are each CSS variable driven (for consistency across the site design), but that CSS variable can be overwritten with a custom selection.

**Comment by talldan** [comment] 2020-07-22 06:57
This looks like a duplicate of #10730

**Closed by talldan** 2020-07-22 06:57 UTC
Labels: [Block] Columns, [Type] Enhancement
