### ISSUE TITLE
MediaUpload: Hidden Button Element Is Created When Block Rendered

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#26422] opened 2020-10-23 14:24 UTC
**Describe the bug**

Whenever the Site Logo is rendered, a `<button type="button" class="browser" style="display: none;"></button>` element is added to the DOM, right before `</body>`.

cc @scruffian 

**To reproduce**
1. Create a new post, and open the browser's inspection tool; scroll to the bottom to observe what happens near `</body>`.
2. Insert a Site Logo block.
3. Look at the browser's inspection tool: you'll see a new hidden `button` element added to the DOM right before `</body>`.

This happens **whenever** the Site Logo block is rendered, for example, try inserting the block and switch to code editor and back to visual (which renders the block again).
In some cases it only creates 1 `button`, but usually 2 of them.

**Expected behavior**

I didn't expect to see a hidden `button` added to the DOM. 😅 

**Screenshots**

The browser's element inspection tool, after adding a few Site Logo blocks to the editor.

<img width="392" alt="Screenshot 2020-10-23 at 14 41 06" src="https://user-images.githubusercontent.com/2070010/97014703-95316800-1542-11eb-9cf3-d389f3b5b516.png">

**Editor version (please complete the following information):**
- Gutenberg plugin on master (95188199c8b8045322d7f75a2666d47ea6504ad2)

**Desktop:**
 - OS: MacOS 10.15.17
 - Browser: Chrome
 - Version: 86

**Comment by ntsekouras** [comment] 2021-01-05 14:51
After debugging I found out that these `buttons` are created from `core` here: https://github.com/WordPress/WordPress/blob/972c42288a1078d691a1f47239ae26fdd3117ad1/wp-includes/js/media-views.js#L5020

This affects all blocks/components that use the `MediaUpload` component, like `Image, Cover etc... The created buttons seem to be important for the upload process (I deleted them in dom and it wasn't working) but I didn't go any deeper.

I'm not sure if there is a bug here... Probably someone could look why and prevent creating these blocks in every render.
You can test it just by opening the `Page/Post Setting` in Inspector Controls, which load the component for the featured image.

**Comment by Mamaduka** [comment] 2021-07-20 12:56
I think this is a duplicate of #9184.

**Closed** 2021-07-21 07:56 UTC
Labels: [Feature] Media, [Type] Bug
