### ISSUE TITLE
Assets Files do not load inside the responsive editor iframe after WP 5.9 update.

### ISSUE THREAD

**Issue by RajkiranBagal** [WordPress/gutenberg#40421] opened 2022-04-18 13:47 UTC
### Description

We have used the `enqueue_block_editor_assets` hook & enqueued a CSS file inside that.

That CSS file successfully loads inside the editor on Desktop preview.

When we switch the preview to Mobile/Tablet then all the Markup is loaded inside an iframe, but the CSS file is not loaded inside it.

Due to which, it breaks things on responsive mode.

### Step-by-step reproduction instructions

1. Enqueue any CSS file using `wp_enqueue_style` function on `enqueue_block_editor_assets` hook.
2. Go to the Editor, On Desktop you will the file is loading.
3. Now switch preview to Tablet/Mobile.
4. The CSS file will not load inside the iframe.

### Environment info

- Using Gutenberg version 13.0.0
- Issue reproduces on both Google Chrome & Mozilla Firefox browsers when the Gutenberg plugin is active.
- When Gutenberg Plugin is deactivated it only reproduces on the Mozilla Firefox browser. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ALJ** [comment] 2022-04-18 22:13
This might be a duplicate of https://github.com/WordPress/gutenberg/issues/38673

**Comment by ndiego** [comment] 2022-04-22 11:16
Yes, this appears to be a duplicate of #38673. Since more discussion is taking place on that issue, I am going to close this in favor of #38673. Thank you for reporting this @RajkiranBagal! Keep an eye on the other issue as we work towards a solution.

**Closed as completed by ndiego** 2022-04-22 11:16 UTC
