### ISSUE TITLE
Rich Text getTextContent() returns "Object replacement character" on an html string with no text

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#11542] opened 2018-11-06 12:40 UTC
**Describe the bug**
In an html string that has no text, creating an instance of the Rich Text module and using the getTextContent returns an "invisible" Object replacement character.

**To Reproduce**
````
wp.richText.getTextContent( wp.richText.create( { html: `<img src="#" />` } ) )
````
returns the [Object replacement character](https://www.fileformat.info/info/unicode/char/fffc/index.htm), to verify it we can check the length which is equal to 1.

**Expected behavior**
I believe an empty string would be the expected output.

**Additional context**
- Gutenberg 4.2.0-rc.1
- WordPress 4.9.8

**Comment by iseulde** [comment] 2018-11-06 14:42
This is the expected output. The value has an image as an object in the string. I don't see what the problem is? What are you trying to do?

**Comment by alvaro0555** [comment] 2018-11-06 15:09
Thanks for the reply. Maybe I misunderstood the use of getTextContent(), I thought it was meant to return the text from an html element or  html string. In a similar way to how [jQuery text()](https://api.jquery.com/text/) works.

**Comment by iseulde** [comment] 2018-11-06 15:47
Yeah, maybe that's a bit confusing. What use case do you have for that. We could provide it too, but we need a convincing use case.

**Comment by alvaro0555** [comment] 2018-11-06 17:31
I'm getting the text content from blocks (for example in a core/paragraph from its "content" attribute). The issue came out when trying to get the text from a paragraph which only had an image and although the output looked like an empty string it was not. So it took me some time to figure out there was something inside the returned string.
I thought it was unintended, but if not I can simply replace it with an empty string.

Thanks for the quick response.

**Comment by tellthemachines** [comment] 2023-05-10 05:20
I'm going to go ahead and close this as there's nothing actionable in here. Please feel free to reopen if needed!

**Closed by tellthemachines** 2023-05-10 05:20 UTC
Labels: [Type] Question, [Package] Rich text
