### ISSUE TITLE
Not save additional fields

### ISSUE THREAD

**Issue by programmister** [WordPress/gutenberg#9368] opened 2018-08-27 02:54 UTC
Hello!

On post edit page I have title field (tinymce) and Permalink field. But title field dont save (it save only if it is a simple textarea). And button of Permalink field does not work.
On classic edit page all fields work.
Please see screen.

![bug1](https://user-images.githubusercontent.com/3492399/44638059-8cbe6080-a9bd-11e8-8d7b-bd7ebc18046e.JPG)

**Comment by designsimply** [comment] 2018-08-27 18:49
This may be caused by a plugin conflict. Are you able to identify which plugin is adding the "Title" field and the extra "Permalink" option by temporarily turning off all plugins, checking to see if the problem goes away, and then turning each plugin back on until you find the source of the conflict? It is good to note plugin conflicts here, however, if we identify one then the best route is to report the issue to the plugin developer directly so they are aware of the incompatibility so that it may be fixed. I can help guide you if you need help with that.

**Comment by programmister** [comment] 2018-08-27 19:33
Thanks for answer!
It is kohette-framework installed in theme.

This is a code of insert of title:
```
/**
* Creation of the metabox_id with the hyper-amazing KTT Framework
*/
$args = array();
$args['metabox_id'] 					= 	'post_title_formated';
$args['metabox_name']					= 	esc_html__("Title", 'narratium');
$args['metabox_post_type'] 		= 	'post';
$args['metabox_vars'] 				= 	array(
                                      KTT_var_name('post_title_formated')
                                  );
$args['metabox_callback']			= 	'KTT_post_title_meta_box';
$args['metabox_context']			= 	'advanced';
$args['metabox_priority']			= 	'high';
$metabox = new KTT_new_metabox($args);



/**
* Metabox render
*/
function KTT_post_title_meta_box($post) {

    /**
    * If currently the entry does not have a formatted title we put
    * by default the normal title of the entry.
    */
    if (!isset($post->post_title_formated)) $post->post_title_formated = $post->post_title;

    /**
    * We declare the configuration of our editor
    */
    $editor_settings = array(
                                      'wpautop' => true,
                                      'media_buttons' => false,
                                      'textarea_name' => KTT_var_name('post_title_formated'),
                                      'textarea_rows' => 0,
                                      'quicktags' => false,
									//'tinymce' => false
                                      'tinymce' => array(
                                          'toolbar1'=> 'bold,italic,underline,link,unlink,forecolor',
                                        )
    );

    ?>
    <div id="titlediv">
      <p>
        <?php esc_html_e('Insert a title for your post. You can use format tags.', 'narratium');?>
      </p>
    <?php

    /**
    * We create the editor
    */
    wp_editor( $post->post_title_formated, KTT_var_name('post_title_formated'), $editor_settings );


      /**
      * Post name / slug / permalink magic
      */
      global $post_type, $post_type_object;
      $sample_permalink_html = $post_type_object->public ? get_sample_permalink_html($post->ID) : '';

    	if ( $post_type_object->public && ! ( 'pending' == get_post_status( $post ) && !current_user_can( $post_type_object->cap->publish_posts ) ) ) {
    	        $has_sample_permalink = $sample_permalink_html && 'auto-draft' != $post->post_status;
    	?>
    	        <div id="edit-slug-box" class="hide-if-no-js">
    	        <?php
    	                if ( $has_sample_permalink ) echo get_sample_permalink_html($post->ID);
    	        ?>
    	        </div>
    	<?php
    	}
      wp_nonce_field( 'samplepermalink', 'samplepermalinknonce', false );


    ?>
    </div>



    <script>
    jQuery(document).on('before-autosave', function(event,data) {


        if (jQuery("#wp-ktt_post_title_formated-wrap").hasClass("tmce-active")){
            editor = tinyMCE.get('ktt_post_title_formated');
            var title = editor.getContent();
        } else {
            var title = jQuery('textarea[name=ktt_post_title_formated]').val();
        }

		//remove tags
        title = jQuery(title).text();

        data.post_title = title;
    } );
    </script>

    <?php
}
```

In POST data ktt_post_title_formated = old title. So tinymce does not update textarea. And as I wrote button for permalink does not work.

**Comment by danielbachhuber** [comment] 2018-08-27 20:59
@programmister Is this a duplicate of #7176?

**Comment by programmister** [comment] 2018-08-28 17:07
Mmm... maybe... And what do I must to add to our code?
But it does not resolve problem with permalink button.
I think that some error in js of gutenberg break next code of tinymce and permalink button,

**Comment by danielbachhuber** [comment] 2018-08-28 22:56
> And what do I must to add to our code?

You shouldn't need to add anything. It'll hopefully eventually be fixed in Gutenberg.

> But it does not resolve problem with permalink button.

The permalink button has been implemented in a different way with Gutenberg, so your existing code won't work without modifications.

**Comment by programmister** [comment] 2018-08-29 00:43
@danielbachhuber , when will it be fixed?
Does this problem has a temporary solution?

**Comment by programmister** [comment] 2018-08-30 01:12
@danielbachhuber , from https://github.com/WordPress/gutenberg/pull/6293/commits/edefa5e26509064618189ed049e648f3161a8f84 I modify wp-content/plugins/gutenberg/build/edit-post/index.js:
```
		INITIALIZE_META_BOX_STATE: function (e, t) {
			if (Object(S.some)(e.metaBoxes)) {
				setTimeout(function () {
					var e = Object(a.select)("core/editor").getCurrentPostType();
					window.postboxes.page !== e && window.postboxes.add_postbox_toggles(e)
				});
				var n = Object(S.reduce)(e.metaBoxes, function (e, t, n) {
					if ( window.tinyMCE ) {
						window.tinyMCE.triggerSave();
					}
					return t && (e[n] = jQuery(De(n)).serialize()), e
				}, {});
```
and ()
```
		}, REQUEST_META_BOX_UPDATES: function (e, t) {
			var n = t.getState(), r = Object(S.reduce)(Ne(n), function (e, t, n) {
				if ( window.tinyMCE ) {
					window.tinyMCE.triggerSave();
				}
				return t.isActive && (e[n] = jQuery(De(n)).serialize()), e
			}, {});
```

And it's work ).

**Closed** 2018-11-28 23:20 UTC
Labels: [Type] Help Request, [Type] Plugin / Theme Interoperability
