### ISSUE TITLE
Norwegian Z-index Inserter: Add Gutenberg to already classic page. 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11518] opened 2018-11-05 23:06 UTC
**Describe the bug**
On an existing page where there is some classic editor content. Then installed Gutenberg and went back to page. I noticed the inserter is partly behind the classic block.

![screen shot 2018-11-06 at 00 01 30](https://user-images.githubusercontent.com/5323259/48032299-65bba200-e157-11e8-940b-92142c907542.png)

**To Reproduce**
1. Add some content using the classic editor to a page.
2. Then install Gutenberg version 4.1.1.
3. Hover over the inserter and see if it is in front of the classic block or partly behind it.

**Expected behavior**
That the inserter is in front of the classic inserter.

**Desktop (please complete the following information):**
 - OS: Max OS 10.13.6
 - Browser Chrome on live site.
 - Version Gutenberg 4.1.1

Ahh the Norwegian Z-index inserter.... :)

**Comment by youknowriad** [comment] 2019-08-22 11:21
Duplicate of #10471

**Closed by youknowriad** 2019-08-22 11:21 UTC
Labels: Priority Low, [Block] Classic, [Component] Inserter, [Type] Bug
