### ISSUE TITLE
Export `useMultipleOriginColorsAndGradients`

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#41438] opened 2022-05-30 16:47 UTC
## What problem does this address?

Not sure if this is a bug report of feature request...

I see `useMultipleOriginColorsAndGradients()` is not exported via the [block editor components](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/index.js).

However it does seem to be exported in [block editor components for native](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/index.native.js#L65).

Without it we can't add the necessary colors + gradients that are supported in the current setup, eg when implementing `ColorGradientSettingsDropdown` in our own blocks/ui's.

## What is your proposed solution?

Export it via the block editor components index.js.

I was wondering if it should be exported as experimental, although it seems in native it is not marked as such.

PR incoming

**Comment by rmorse** [comment] 2022-05-30 16:48
Ok it seems I am unable to contribute this change (or make a simple commit to the repo) as husky fails with an error when I try to commit...

```
Running tasks for packages/**/*.{js,ts,tsx,json} [failed]
```

Not sure what's going on here, but its my first time contributing again since husky was added.  Seems it might be related to line endings but really not sure at this stage.

**Comment by corentin-gautier** [comment] 2022-07-25 12:01
It's been added in #41102 but weirdly enough I was not able to use it using :

```jsx
import { __experimentalUseMultipleOriginColorsAndGradients as useMultipleOriginColorsAndGradients } from "@wordpress/block-editor" 
```
It's used that way [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/edit/inspector-controls.js#L26)

EDIT : I was not on the dev version of gutenberg, it works now even though the latest changes requires the `<ColorGradientSettingsDropdown>` to be used inside a `<ToolsPanel>` (because it's wrapped in a `<ToolsPanelItem>`)

**Comment by rmorse** [comment] 2022-08-03 10:32
@corentin-gautier I'm wondering if it's been released in the Gutenberg feature plugin yet, maybe its not in a release yet (assume that its merged means it will be soon).

**Comment by jorgefilipecosta** [comment] 2022-09-01 14:31
Closing this issue as according to the conversation, the hook seems to be exported now.

**Comment by justintadlock** [comment] 2022-11-09 23:58
I can confirm that this works now:

```js
import {
	__experimentalUseMultipleOriginColorsAndGradients as useMultipleOriginColorsAndGradients
} from '@wordpress/block-editor';
```

**Closed as completed by justintadlock** 2022-11-09 23:58 UTC
Labels: [Type] Question, [Package] Components
