### ISSUE TITLE
The metaboxes are overlaid with Gberg.

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#11137] opened 2018-10-26 22:00 UTC
**Describe the bug**
When converting an existing article to blocks, the metaboxes are overlaid with Gberg.

**To Reproduce**
1. Go to 'existing page from the classic editor'
2. Click on 'transform to blocks'
3. Scroll down to 'see the meta boxes in Gberg'
4. See error: http://recordit.co/E9iF6KeMxi

**Expected behavior**
That the metaboxes are displayed at the bottom and not in the middle of the editor.

**Screenshots**
http://recordit.co/E9iF6KeMxi

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version 70.0.3538.77 (Offizieller Build) (64-Bit)

**Additional context**
- Gberg 4.1
- Wordpress 4.9.8.

**Comment by youknowriad** [comment] 2018-11-07 10:35
closing as duplicate of #11378

**Closed by youknowriad** 2018-11-07 10:35 UTC
Labels: [Type] Plugin / Theme Interoperability
