### ISSUE TITLE
Can't enter a tab

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1621] opened 2017-06-30 18:53 UTC
Everytime I use the tab key, it takes me to a new block. I expect the tab key to insert a tab charachter while I am typing.

**Comment by swissspidy** [comment] 2017-07-01 13:59
Possible duplicate of #1552.

Just note that such behaviour could quickly result in a keyboard trap for users, where you can't use tab for navigation anymore.

Probably one of the reasons it's not implemented in the current WordPress editor.

**Comment by afercia** [comment] 2017-08-29 14:36
@aaronjorbin I;d be in favor of closing this issue, as the native behavior when pressing the Tab key is navigating through focusable elements. Even in TinyMCE, pressing Tab doesn't insert a tab character. Only in ordered/unordered lists it's used to indent the list items.

**Comment by jasmussen** [comment] 2017-12-05 10:44
Given that there are accessibility concerns with this particular approach, and the discussion is likely to resurface for the code editor, I'm going to close this one for now. I would suggest that it is fine to open for discussion on a per-block basis.

**Closed by jasmussen** 2017-12-05 10:44 UTC
Labels: Accessibility, [Type] Question
