### ISSUE TITLE
Custom select control component cuts off type preview

### ISSUE THREAD

**Issue by jffng** [WordPress/gutenberg#25875] opened 2020-10-06 21:09 UTC
When very large font sizes are supplied to the editor (via `add_theme_support('editor-font-sizes')`), the dropdown component can cut off the preview:

![Screen Shot 2020-10-06 at 1 57 07 PM](https://user-images.githubusercontent.com/5375500/95260093-0819af80-07dd-11eb-847e-510494b51583.png)

**Comment by talldan** [comment] 2020-10-06 21:24
Duplicate of #25862

**Closed by talldan** 2020-10-06 21:24 UTC
