### ISSUE TITLE
Expose all retrieveFastAverageColor settings with a new filter

### ISSUE THREAD

**Issue by jhned** [WordPress/gutenberg#46173] opened 2022-11-29 20:29 UTC
## What problem does this address?
The retrieveFastAverageColor package is set up to prioritize speed over accuracy. This means that sometimes the average color is off. In my own tests, an image's average color was observed to be off by 8% on the lightness spectrum.

## What is your proposed solution?
If developers prefer to change the strategy to precision, we'd need a new filter to change out the retrieveFastAverageColor settings. There is a filter for the [crossOrigin setting](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/edit/use-cover-is-dark.js#L38-L42). I propose that we add another filter that would let developers change out any of the settings for retrieveFastAverageColor.

**Comment by talldan** [comment] 2023-04-11 06:59
The issue is lacking a little in detail for other contributors. What does `retrieveFastAverageColor` do that needs to be filtered?

**Comment by priethor** [comment] 2023-06-30 12:38
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏

**Closed as completed by priethor** 2023-06-30 12:38 UTC
Labels: [Type] Enhancement, [Status] Needs More Info, [Feature] Extensibility
