### ISSUE TITLE
Bug: wrong class name `has-background-dim-0` with opacity 0.5

### ISSUE THREAD

**Issue by vHeemstra** [WordPress/gutenberg#27495] opened 2020-12-04 05:43 UTC
**Description**
When you set the transparency on a cover block to 1 through 4 in the editor, this will be rounded to `0` but is not ignored by the `! ratio` check. So it ends up with a class name of `has-background-dim-0` which has no styling, **but** defaults to opacity `0.5` because of the `.wp-block-cover__gradient-background` class default opacity. This happens in the editor WYSIWYG as well as on the front-end.

**Possible solution 1**
https://github.com/WordPress/gutenberg/blob/5cd71f42499173e6d6f10a20a4b066f3aab77e34/packages/block-library/src/cover/shared.js#L58-L62
Let line #59 also check on the rounded opacity value by adding `|| 0 === Math.round( ratio / 10 )` or similar.

**Possible solution 2**
https://github.com/WordPress/gutenberg/blob/5cd71f42499173e6d6f10a20a4b066f3aab77e34/packages/block-library/src/cover/style.scss#L68-L75
Have the SCSS file include a `has-background-dim-0` class definition with `opacity: 0` by starting the `@for` on `0`.

**NB:**
I'm not sure if this the only place where this bug occurs. (Not that familiar with the code base ;) )

**Comment by ramonjd** [comment] 2022-02-15 03:57
I can't reproduce this. I think it might have been addressed by https://github.com/WordPress/gutenberg/pull/35065 or an earlier PR. 

Feel free to reopen if the problem persists. Thank you!

**Closed by ramonjd** 2022-02-15 03:57 UTC
Labels: [Type] Bug, Good First Issue, [Status] In Progress, [Block] Cover
