### ISSUE TITLE
Background flashes when editing italicized or bolded text

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#13152] opened 2018-12-31 22:29 UTC
**Describe the bug**

It's a bit subtle but when typing with bold or italicized options on, the text background will flash on keypress between white and gray. Ideally this we should not see this.

![flash](https://user-images.githubusercontent.com/1270189/50568497-9ce9a200-0d07-11e9-8ea5-10300d366e50.gif)

**To Reproduce**
1. Visit /post.php
2. Start typing in a paragraph block
3. Italicize or bold that text
4. With the formatting active (folks see a gray background) continue to type
5. After some keypresses, the text background appears to flash

**Expected behavior**
No visible background flashing. Background should remain gray until we exit that formatted text section.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
- WP 5.0.2

**Comment by youknowriad** [comment] 2019-01-04 10:20
Duplicate of #12978

**Closed by youknowriad** 2019-01-04 10:20 UTC
Labels: [Type] Bug

**Comment by youknowriad** [comment] 2019-01-05 09:37
Sure added. Thanks
