### ISSUE TITLE
Cursor placed at beginning of paragraph instead of where click happened

### ISSUE THREAD

**Issue by KPeregrinePgh** [WordPress/gutenberg#11573] opened 2018-11-07 10:12 UTC
**Describe the bug**
When editing a Paragraph in a post that has several Paragraph blocks. (No Paragraphs are selected yet. I'm proofreading.)  I click on the spot I want to edit in a not-yet-selected Paragraph. Instead of positioning the cursor where I clicked (as in prior versions) 4.2.0 positions it at the *start* of the block so when I start to type I'm changing the beginning of the Paragraph, not the location where I clicked.

Might be the return of this very old bug, but this time it's on Windows 10 Firefox:  https://github.com/WordPress/gutenberg/issues/2472
My Firefox version did not change between Gutenberg 4.1.1 and 4.2.0

**To Reproduce**
1. In Firefox Open an existing draft that has more than one paragraph. Don't click on anything yet. (i.e. Do not select any of the paragraphs.)
2. Click on a location in the middle of a Paragraph where you want to make a change.
3. Notice that the cursor is not placed where you clicked. It's at the beginning. If you want to make yourself crazy, start typing immediately and you'll be changing the *beginning* of the paragraph.

NOTE:  Once you've selected a paragraph - just once - the good behavior returns to that paragraph for the rest of the edit session.  If you click on every paragraph before you begin proofreading you can click on any one of them and get the proper cursor behavior.

**Expected behavior**
Click in the middle of an existing Paragraph block (that you have not yet selected) and the cursor is immediately positioned where you click.  *This is how it used to work prior to 4.2.0.*

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 63.0.1

**Smartphone (please complete the following information):**
 n/a

**Additional context**
- Gutenberg 4.2.0  **** This issue is new in 4.2.0  Was not a problem in 4.1.1
-- My Firefox version did not change between Gutenberg 4.1.1 and 4.2.0

**Comment by designsimply** [comment] 2018-11-28 17:29
Tested and confirmed that the caret lands at the beginning of a paragraph when clicked but only for the first time you click on that paragraph within a given editing session. ([45s](https://cloudup.com/cJl60Pey6gd))

<sup>Tested with WordPress 4.9.8 and Gutenberg `master` `e4fd51cb5` (latest previous release: 4.5.1) using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment] 2018-11-28 17:33
Noting another tester was unable to replicate with macOS 10.14.1: https://github.com/WordPress/gutenberg/issues/12380#issuecomment-442522044.

**Comment by bph** [comment] 2018-11-28 20:54
I can reproduce on Mac OX 10.13.6 Firefox Developer 64.0B12 -- Gutenberg 4.5.1.

First time clicking into paragraph block goes to the beginning of it. Clicking into another paragraph I also end up at the beginning. Trying to click 2nd time in 1st paragraph the cursor lands where I wanted it to click…

**Comment by frogmorris** [comment] 2019-01-28 11:07
We have been having the problem too on OSX chrome and my colleague has reported it on window (will find out what browser). We've noted it happens if you leave the keyboard idle for a moment eg. you are typing, pause to check notes and then return to keyboard to finish sentence and the cursor has jumped back to the start of text block. If not aware you get edits in the wrong place and have to redo them which is very frustrating and time consuming.

**Comment by designsimply** [comment] 2019-01-28 18:02
> We've noted it happens if you leave the keyboard idle for a moment eg. you are typing, pause to check notes and then return to keyboard to finish sentence and the cursor has jumped back to the start of text block.

I haven't observed this exact behavior myself, so I'm adding the `Needs Testing` label again to ask for help again from testers to get a confirmation. 

@frogmorris for that check, do you by chance know if your colleague who is using Windows was also using Chrome? Also, is there any chance you can check from a different browser yourself just to rule out a browser-specific problem in your case? I ask because it could prove useful later to note whether there is a brower-specific problem at play and it's also worth noting that the behavior you have described is definitely a little different than the one in the original report here but I am not sure yet if it's different enough to warrant opening a separate issue.

**Comment by frogmorris** [comment] 2019-01-29 09:35
It is Chrome. My colleague reported it on Chrome on Windows and I have seen the same problem on Chrome on Mac OSX Mojave.
I noted the problem when editing posts and stopping mid paragraph so it sounds very similar.

**Comment by desrosj** [comment] 2019-02-05 15:39
I encounter this a lot when composing posts. I mainly use Firefox on MacOS.

**Comment by mrwweb** [comment] 2019-02-05 16:21
Having now used the block editor for a lot more writing _and editing_, this is the #1 bug I want fixed. It doesn't happen every time, but it does happen frequently (it feels like a majority of clicks when I'm proofing a post). I'm on Firefox, Win 10.

**Comment by designsimply** [comment] 2019-02-05 19:15
Thank you for the extra comments! I now feeling like there are two separate issues here:

1. I click on the spot I want to edit in a not-yet-selected paragraph and the cursor is positioned at the start of the block and not where I clicked.
2. The cursor jumped back to the start of text block after leaving the the keyboard idle for a moment (without clicking).

I think these should be tracked as two separate things because although related they are not exactly the same problem any may need to be solved differently in the code (someone do please correct me if that's wrong!). @frogmorris if you're still experiencing the 2nd issue, would you mind creating a new bug report for that and including a note about the OS/Browser versions where you've observed it for reference? In the mean time, we can continue the discussion about the problem where when you *click* on a previously unselected paragraph the cursor jumps to the start of the paragraph instead of at the position that was clicked.

**Comment by iseulde** [comment] 2019-02-19 15:17
I think this is a duplicate of #11812, which was fixed and will be in Gutenberg 5.1.

**Closed by iseulde** 2019-02-19 15:17 UTC
Labels: Input Interaction, [Type] Bug
