### ISSUE TITLE
Avatar block throws encountered error if the Avatar Display turned off from the Discussion settings

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/gutenberg#41311] opened 2022-05-25 11:45 UTC
### Description

Please check the instructions for more info about the error.

WordPress core: https://core.trac.wordpress.org/ticket/55818

### Step-by-step reproduction instructions

If the Avatar Display turns off from the Settings > Discussion > Show Avatars(checkout):
Avatar block still shows on Gutenberg blocks(which should not be shown):
And if the Avatar block takes on an editor, it throws encountered error:

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/10103365/170254031-3481724c-4311-4808-bd27-ebca8143cba3.png)

![image](https://user-images.githubusercontent.com/10103365/170254116-2ea93094-7038-45b3-8830-e352c17e4f0f.png)

![image](https://user-images.githubusercontent.com/10103365/170254153-66baa460-c556-414d-aee1-09ffb4ed69c5.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-05-25 12:16
Hi, @mukeshpanchal27

Thanks for creating the issue and a PR!

This is a duplicate of #41308, so let's close this one and reference the initial issue in your PR>

**Comment by mukeshpanchal27** [comment] 2022-05-25 12:23
Ok, thanks. Let's close this issue.

**Closed as completed** 2022-05-25 12:25 UTC
