### ISSUE TITLE
Saving: Post with only "Classic" block fails to autosave

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7727] opened 2018-07-05 14:55 UTC
When a post only contains a "Classic" block, it attempts to autosave but fails.

![image](https://user-images.githubusercontent.com/1779930/42330680-a730ff04-8041-11e8-90cb-4f8a46362f5f.png)

**Steps to reproduce:**

1. Navigate to Posts > Add New
2. Insert a "Classic" block
3. Wait a few seconds
4. Autosave kicks in, then fails with notice

**Suspected cause:**

There is special handling for the classic block to omit its comment demarcation wrapper, so while the editor knows that a block exists and thus thinks the post is saveable, when it's the only content, it will be serialized as the empty string, which is not valid for save.

https://github.com/WordPress/gutenberg/blob/622bbfb6bc6364a4e49991081aafed4257309c92/editor/store/selectors.js#L351-L364

It is not a safe assumption to imply that the presence of blocks means that content is non-empty. `isEditedPostEmpty` should at least be updated to account for this special Classic block behavior.

**Comment by danielbachhuber** [comment] 2018-07-05 14:56
Duplicate of https://github.com/WordPress/gutenberg/issues/6556#issuecomment-397743308

**Closed by danielbachhuber** 2018-07-05 14:56 UTC
Labels: [Component] Saving, [Type] Bug

**Comment by olygoelements** [comment] 2018-09-12 00:46
i have the same error. 
gutenberg have a conflict
i have upgrade php 7.1 to 7.2
and now is work

**Comment by aduth** [comment] 2018-09-12 12:49
@olygoelements The "Updating failed" message is a pretty common error that applies broadly to issues where the request to save the post via the REST API fails for some reason. I expect your issue may not be quite the same as what was described here.
