### ISSUE TITLE
9.6 RC1: Button block appears incorrectly by default

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#27773] opened 2020-12-17 00:37 UTC
**Describe the bug**

Running Gutenberg 9.6 RC1, the button block appears incorrectly by default in the editor and in the front end: 

Editor|Front End
---|---
<img width="367" alt="Screen Shot 2020-12-16 at 7 28 53 PM" src="https://user-images.githubusercontent.com/1202812/102422722-63360280-3fd5-11eb-96ca-75e3e0241a92.png">|<img width="179" alt="Screen Shot 2020-12-16 at 7 31 34 PM" src="https://user-images.githubusercontent.com/1202812/102422725-63ce9900-3fd5-11eb-92b2-684460b943db.png">

Discovered by @annezazu in https://github.com/WordPress/theme-experiments/issues/147. I am able to reproduce in any theme that does not provide its own button styles. (Twenty Twenty-One Blocks, the Gutenberg Starter Theme, etc). For reference, here's the expected button appearance by default: 

Editor (Expected)|Front End (Expected)
--|--
<img width="350" alt="Screen Shot 2020-12-16 at 7 35 27 PM" src="https://user-images.githubusercontent.com/1202812/102422979-f4a57480-3fd5-11eb-9de6-440f22428e03.png">|<img width="201" alt="Screen Shot 2020-12-16 at 7 35 34 PM" src="https://user-images.githubusercontent.com/1202812/102422980-f53e0b00-3fd5-11eb-83c9-e7454dba706c.png">

For me, this only showed up using [9.6 RC-1](https://github.com/WordPress/gutenberg/releases/tag/v9.6.0-rc.1) on a fresh site, not after running the compiled `master` on my existing test site.

Gutenberg 9.6 RC-1
WordPress 5.6

**Comment by talldan** [comment] 2020-12-17 06:32
> For me, this only showed up using 9.6 RC-1 on a fresh site, not after running the compiled master on my existing test site.

I also can't reproduce after checking out the `9.6.0-rc.1` tag locally either, so if my testing was correct it seems like it might be related to the build of the plugin rather than something that was fixed since rc1.

**Comment by youknowriad** [comment] 2020-12-29 22:24
Is this fixed on the last 9.6.2 release, we had a build issue that was fixed on 9.6.1?

**Comment by annezazu** [comment] 2020-12-29 22:38
Whew! Just tested with 9.6.2 across three different themes to be safe: TT1 blocks, Twenty Twenty, and Q. Can confirm it's no longer an issue. Closing this out.

**Closed by annezazu** 2020-12-29 22:38 UTC
Labels: [Block] Buttons, [Priority] High, [Type] Regression
