### ISSUE TITLE
Image Captions do not Update in Editor

### ISSUE THREAD

**Issue by biselblog** [WordPress/gutenberg#8859] opened 2018-08-11 01:43 UTC
**Describe the bug**
If I change or add a caption to an image in the editor, the caption does not save. 

**To Reproduce**
1. Go to any image in a post.
2. Click on an image to add or edit a caption.
3. Make your changes and save.
4. The caption reverts back to what it was before your edit.

**Expected behavior**
I expected the edited caption to appear on my post.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: 54.0.2952.64

**Additional context**
- Gutenberg version: 3.5.0

**Comment by brandonpayton** [comment] 2018-09-27 05:06
Hi @biselblog, I am not able to reproduce this in Windows 10 with Opera 56. Here's my attempt to reproduce. Should something be done differently below? Are you still experiencing this issue?

![opera-image-caption](https://user-images.githubusercontent.com/530877/46124329-505a6c00-c1d8-11e8-94ee-8c78696ccdfb.gif)

Should something be done differently to reproduce? Are you still experiencing this issue?

**Comment by biselblog** [comment] 2018-09-27 13:11
The issue appears to be resolved.

**Comment by brandonpayton** [comment] 2018-09-27 18:37
Thanks for following up! Let's close this.

**Closed by brandonpayton** 2018-09-27 18:37 UTC
Labels: Blocks, Needs Testing, [Type] Bug
