### ISSUE TITLE
If no JavaScript is available Gutenberg is returning a blank white page

### ISSUE THREAD

**Issue by rpkoller** [WordPress/gutenberg#2719] opened 2017-09-12 19:50 UTC
I am well aware that Gutenberg relies heavily onto JavaScript with React, ESNext and Webpack in particular. But never the less from a Progressive Enhancement standpoint it should never ever be the case with the unavailability of JavaScript that there is no content accessible at all, like seeing a blank page for Gutenberg at the moment (WordPress 4.8.1 and Gutenberg 1.1.0) . :/  There are many scenarios where that might happen, you never know (https://kryogenix.org/code/browser/everyonehasjs.html). I am not saying that the same functionality should be provided like in the presence of JavaScript but the content inside the editor should be visible in any given scenario in my humble opinion.

**Comment by iseulde** [comment] 2017-09-25 14:20
Yes, we should send the basic form and fields from the server. In case of the editor, this will be just the text mode with the raw post content, nothing else. Not sure about the post settings, but perhaps just the bare fields as well. It would be nice to also load the basic structure of the page and styles, which would also benefit JS users as it will look like it loads faster. Unfortunately, whatever needs to be rendered server side will be duplicated logic. :/

**Comment by afercia** [comment] 2018-07-02 14:56
Quickly discussed during today's accessibility bug-scrub, we'd like to remove the a11y label as this is certainly something to address but really a general compatibility issue with no-js environments.

**Comment by rpkoller** [comment] 2018-09-26 12:14
At the time of writing that issue there was at least the admin menu still visible. If you load a Gutenberg page nowadays with Javascript not available you get a complete white screen, even the admin menu is missing.

**Comment by afercia** [comment] 2018-09-26 16:45
Interesting. I think this is caused by the Fullscreen Mode implementation, see #9567 as it hides by default the admin menu and the admin bar with `display: none`. If so, it's a bug because, at least, users should be able to navigate away. In a way, it's also a regression compared to the previous behavior. /Cc @youknowriad

**Comment by designsimply** [comment] 2018-11-01 20:38
Tested and confirmed that I see a completely white screen after installing the Disable JavaScript 2.3.1 add-on from https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/ then turning off Javascript and viewing `/wp-admin/post-new.php` using Firefox.

![screen shot 2018-11-01 at 2 34 02 pm](https://user-images.githubusercontent.com/1119271/47878290-885e5b80-dde3-11e8-82f4-438d2ff24506.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

**Comment by rpkoller** [comment] 2018-11-09 11:11
@iseulde hm with the pull request by @mkaz  the initial issue of that ticket wouldn't be fixed at all and the issue should be kept open. 

> There are many scenarios where that might happen, you never know (https://kryogenix.org/code/browser/everyonehasjs.html). I am not saying that the same functionality should be provided like in the presence of JavaScript but the content inside the editor should be visible in any given scenario in my humble opinion.

Cuz the content of the post is still inaccessible to the users affected by!

**Comment by mkaz** [comment] 2018-11-09 15:07
@rpkoller I think that would be a different issue. The issue as opened is the entire page is blank. My thought was we should at the very least fix the issue with all the wp-admin chrome disappearing so there isn't a blank white page with Javascript disabled. 

It seems like the solution of Javascript being disabled would be to use the Classic Editor, I didn't want to redirect the user automatically because it seems displaying a message and letting them choose  puts them in control.

I'm open to changing the message to reflect that, here is what it looks like now with PR #11642 

<img src="https://user-images.githubusercontent.com/45363/48222398-60be4480-e349-11e8-9c7c-ac342315b53d.png">

**Comment by rpkoller** [comment] 2018-11-09 15:43
@mkaz No. The issue opened by me back in 2017 was about the content not visible inside the editor. the blank page was just the described symptom but the feature request for the fix in that regard was to provide a progressively enhanced experience. Meaning even if javascript is not available, at least display the posts content. with javascript available then the complete gutenberg experience should be provided. and it is not just about javascript "disabled" as you can read up in link provided in the initial issue https://kryogenix.org/code/browser/everyonehasjs.html - there are way more scenarios where javascript is unavailable for the browser and the editor will simply fail in those cases. so providing just an admin notice won't solve the issue - but i agree falling back onto tinymce neither. gutenberg should be able to manage that progressive enhancement experience on its own and @iseulde agreed back then that it is possible.

**Comment by mkaz** [comment] 2018-11-09 15:53
@rpkoller  You're right, I apologize for not reading the full issue closer, I read the title and skimmed through the comments and saw the really broken experience. I see it as two separate issues, first fix the completely broken experience, and second, fix in a way that makes it usable even with Javascript disabled.

When you say:
> the content inside the editor should be visible in any given scenario

Do you mean just visible and able to see it, or the full ability to edit, save, etc...

**Comment by rpkoller** [comment] 2018-11-09 16:39
@mkaz no problem. ;) about the javascript not available scenario. i am not that savy in react to know how to handle things if javascript is not available and what functionality would be possible in that case. but there should be at least a textfield for the post_title, a text area for the post_content as well as a submit button as the bare minimum. so the content is still accessible and basically editable.

**Comment by afercia** [comment] 2018-11-09 17:33
@mkaz proposal in https://github.com/WordPress/gutenberg/issues/2719#issuecomment-437387268 seems to me perfectly in line with what WordPress already does in other screens, for example:

![screenshot 2018-11-09 at 18 23 41](https://user-images.githubusercontent.com/1682452/48278426-bb40c900-e44d-11e8-95e0-2a9ec118362a.png)

![screenshot 2018-11-09 at 18 23 10](https://user-images.githubusercontent.com/1682452/48278427-bb40c900-e44d-11e8-972c-cf128e94c03e.png)

I'd consider to add a link to install the Classic Editor plugin.

**Comment by mtias** [comment] 2018-11-14 02:54
Closing as main functionality is addressed. Further improvements could be expanded upon in future releases.

**Closed** 2018-11-14 02:53 UTC
Labels: General Interface, Regression, [Component] Plugin, [Type] Bug

**Comment by rpkoller** [comment] 2018-11-14 09:43
@mtias the main functionality this issue brought to attention is not addressed yet at all! the only thing introduced now as a "fix" is stating that javascript is necessary for using the editor by the aid of an admin notice. this is cosmetics but not a solution. if javascript is not available for what ever reason i laid out in the initial post and which was confirmed by @iseulde one year ago and you and others as well as @mkaz lately, the content is still not accessible. so i would keep it open cuz the issue making gutenberg progressively enhanced is not solved at all yet.

**Comment by mkaz** [comment] 2018-11-20 21:47
@rpkoller - Another option can be to use the Disable Visual Editor user setting, PR #12000 will go out with Gutenberg 4.5 and WordPress 5.0, this change honors the existing user setting and if checked will present you with the plain text editor which you can use without JavaScript enabled.

Hopefully that addresses your concern, if not probably best to open a new ticket.

**Comment by rpkoller** [comment] 2018-11-23 11:40
@mkaz hm tested the RC and well not even this ticket with the new hi-jacked goal of an admin notice is fixed. 
![bildschirmfoto 2018-11-23 um 12 34 21](https://user-images.githubusercontent.com/1665422/48941710-f1397f00-ef1c-11e8-93e0-b2f1b4761c9c.png)

**Comment by rpkoller** [comment] 2018-11-30 23:38
@mkaz RC2 it is still a white screen. and i repeat myself " not even this ticket with the new off-topic goal of an admin notice is fixed." for the initial issue i open up a ticket also again. :/

**Comment by mkaz** [comment] 2018-12-01 03:43
@rpkoller I noticed that also and opened a core trac ticket: https://core.trac.wordpress.org/ticket/45453

**Comment by mkaz** [comment] 2018-12-04 17:56
@rpkoller The core ticket looks like it is slated for 5.0.1
