### ISSUE TITLE
Post templates that use blocks with meta data fail when new post created

### ISSUE THREAD

**Issue by buhlahkay** [WordPress/gutenberg#17831] opened 2019-10-07 22:35 UTC
**Describe the bug**
If you create a post type that uses a block template, and that template has a block with meta attributes, then whenever you try to create a new post, it throws an error and doesn't allow post creation. If meta key is "my_meta" like so:
```
attributes: {
    myMeta: {
        type: 'string',
        source: 'meta',
        meta: 'my_meta'
    }
}
```
Console log says: "Cannot read property 'my_meta' of undefined"

**To reproduce**
1. Create post type with block template.
2. Give one of those blocks an attribute of source = meta
3. Try to create a new post

**Additional context**
- Gutenberg 6.6.0

**Comment by youknowriad** [comment] 2019-10-08 08:04
This is a duplicate of #17767

**Closed by youknowriad** 2019-10-08 08:04 UTC
