### ISSUE TITLE
Site Editor: The Options menu is displayed behind an active Block Inspector

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#48060] opened 2023-02-14 05:59 UTC
### Description

When editing a Post/Page with the Block Inspector active, clicking the Options menu cause it being displayed behind the Block Inspector. However, this problem doesn’t happen in the Templates/parts editor.

First reported on trac https://core.trac.wordpress.org/ticket/57703

It seems this is a core-specific issue, the problem does not affect the Gutenberg 15.1 plugin.

### Step-by-step reproduction instructions

1. Edit a Post/Page
2. Activate the Block Inspector sidebar
3. Click the Options ellipsis menu
4. Observe the Options menu is displayed behind the Block Inspector

### Screenshots, screen recording, code snippet

![options-menu-behind-block-inspector](https://user-images.githubusercontent.com/79677758/218652044-674dc82f-7f33-4eb4-904e-8874245fdc31.gif)

### Environment info

WP 6.2 beta 1, Firefox 109.0.1, Chrome 110.0.5481.78, Windows 11, TT3 & Powder themes.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-02-14 14:15
Thanks for reporting @franzaurus. This looks to be a duplicate of https://github.com/WordPress/gutenberg/issues/47923, which is currently being investigated. Therefore, I am going to close this one out. Thanks!

**Closed as completed by ndiego** 2023-02-14 14:15 UTC
Labels: Needs Testing
