### ISSUE TITLE
Header block settings has H1 as option

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1766] opened 2017-07-06 15:37 UTC
## Issue Overview
The H1-level should not be available on the header block.
This is not available on the Quick toolbar, but is in the settings.

## Steps to Reproduce (for bugs)

1. Create a header block
2. Open the options
3. See `H1` in the different header levels

<img width="989" alt="new_post_ _test_ _wordpress" src="https://user-images.githubusercontent.com/2005352/27919252-767a9a6c-6271-11e7-94be-b51c6834826e.png">

Plugin version: 0.3.0

## Possible Solution

Remove it from the settings.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by iseulde** [comment] 2017-07-07 08:45
> The H1-level should not be available on the header block.

Why? It is available in core. We are de-emphasising it by moving it to the inspector.

**Comment by iseulde** [comment] 2017-07-07 08:51
Duplicate of https://core.trac.wordpress.org/ticket/38049 for the larger discussion.

**Closed by iseulde** 2017-07-07 08:51 UTC
