### ISSUE TITLE
Widgets link in Admin bar loads legacy widgets screen

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26000] opened 2020-10-09 21:39 UTC
**Describe the bug**
When accessing the Widgets link in the admin toolbar the Legacy widgets screen loads.

**To reproduce**
1. Log in to site
2. Hover over site name in admin bar
3. Click Widgets link
4. Legacy Widgets Screen Loads

**Expected behavior**
Expected behavior would be for the block based widgets screen to load.

**Screenshots**
![Screen Capture on 2020-10-09 at 17-36-33](https://user-images.githubusercontent.com/1975950/95633621-0dcdfa00-0a56-11eb-861e-4fa54b07fc8b.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg plugin installed and active
- 9.1.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 85.0.4183.121

**Comment by tellthemachines** [comment] 2020-10-14 00:18
Closing this a duplicate of #25828

**Closed by tellthemachines** 2020-10-14 00:18 UTC
Labels: Needs Dev, [Feature] Widgets Screen
