### ISSUE TITLE
.update-nag broken for display:block !important

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#2711] opened 2017-09-09 13:34 UTC
The gutenberg CSS defines `body.toplevel_page_gutenberg .update-nag { display:none; }`, but some nags *are* important and may be defined as `display:block !important;` by some themes and plugins. Perhaps the margins should adjusted instead trying to hide the nag? Something like `margin: 50px 280px 0 0;`?

**Comment by jeffpaul** [comment] 2018-01-19 02:24
Per today's Gutenberg [bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1516296292000130), we're closing this as it appears to be a duplicate of #3395.

**Closed by jeffpaul** 2018-01-19 02:24 UTC
