### ISSUE TITLE
Error in 6.3 with blocks with render.php

### ISSUE THREAD

**Issue by jupa8712** [WordPress/gutenberg#53954] opened 2023-08-25 15:51 UTC
### Description

Hi, I have an extend option for blocks that allow add some classes to blocks to animated them. This functionality works fine in 6.2 and previous versions.

In 6.3 I getting the next error in block with render.php: Error loading block: Invalid parameter(s): attributes. Whit others block works normally.

Here my code where error is:

export const attributesToAdd = {
	animate: {
		type: 'string',
		default: '',
	},
    delay: {
		type: 'string',
		default: '',
	}
};

/* Add attributes to block attributes. */
const addClassAttributes = (settings) => {
	
	return{
		...settings,
		attributes:{
			...settings.attributes,
			...attributesToAdd
		}
	}
}
addFilter('blocks.registerBlockType', 'jupa-bs/animate/list-block', addClassAttributes);

If I comment this line, error is not showing, and the additional codes works (Components, panels etc)
addFilter('blocks.registerBlockType', 'jupa-bs/animate/list-block', addClassAttributes);

Thanks for any help

### Step-by-step reproduction instructions

1. Go to edit page
2. Put a block with render php (Mega Max Menu)
3. Block show error

### Environment info

- Wordpress 6.3
- Theme Twenty Twenty Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-09-05 16:20
Hi @jupa8712, would you be able to provide a more complete code example that we could test with? This will make it much easier to test and try and replicate the issue. Thanks!

**Comment by jupa8712** [comment] 2023-09-11 21:17
Hi, here my entire code, also here a video with error.
The problem occurs with the blocks that use render php. This error did not occur in version 6.2 of WP.

https://www.youtube.com/watch?v=v59IM9YOz2A

[animated.zip](https://github.com/WordPress/gutenberg/files/12580460/animated.zip)

Thanks for help

**Comment by t-hamano** [comment] 2023-11-16 16:44
Hi @jupa8712,

Could you please confirm if this issue also occurs with WP6.4 and the latest Gutenberg plugin? Thanks!

**Comment by jupa8712** [comment] 2023-11-21 16:29
Hello, I chose to look for another solution and update the code. So far my new solution already works. Thank you so much

**Comment by t-hamano** [comment] 2023-11-22 14:25
@jupa8712 I'm glad that the problem seems to have been resolved. However, if the problem is with Gutenberg itself, we should investigate the cause. I would like to close this issue, but if you have time, I would appreciate it if you could attach a sample code that can reproduce the problem.

**Closed as not planned by t-hamano** 2023-11-22 14:25 UTC
Labels: [Type] Bug, [Feature] Block API, [Status] Needs More Info, Needs Testing
