### ISSUE TITLE
Previews: cannot preview a published post that has an autosave

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7852] opened 2018-07-10 03:22 UTC
**Describe the bug**
This bug has come and gone several times and it appears to be back again. I simply clicked on a page to edit it, and before I did actually start editing, I clicked on Preview. The front-end simply shows _Please wait… Generating preview_ and never actually displays the page.

![screenshot_726](https://user-images.githubusercontent.com/2078245/42487309-c7878c7c-8443-11e8-83b5-92bf82e9f51c.png)

**To Reproduce**
1. Open previously published page (in the Dashboard)
2. Click on _Preview_ button

**Expected behavior**
Published page should open in new browser tab

_macOS Sierra 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by designsimply** [comment] 2018-07-11 16:45
I tested with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5 and was unable to reproduce the problem based on your steps. Here are the scenarios I tested:

**Video:** [1m18s](https://cloudup.com/coSkfUoBwNV)

1. Open a published post, click Preview.
1. Open a published post, make a change, click Preview.
1. Open a draft post, click Preview.
1. Open a draft post, make a change, click Preview.
1. Start a brand new post, click Preview before autosave.

@maddisondesigns would you mind having a look at the video linked above and let me know if you can see anything different in my tests compared to yours? I noticed the url in your screenshot is `dev.wordpress-test.com/wp-admin/post.php?post2852&action=edit` which makes me think you may be using a local install running bleeding edge. Are you running 3.2.0 stable or a different revision of Gutenberg? If it's the 2nd thing, let me know what revision you are on and I'll try to match up with you for testing.

fwiw, I have seen that bug before but for the life of me couldn't break it with 3.2.0 today when I tested!

**Comment by maddisondesigns** [comment] 2018-07-12 04:54
The site I'm using is a test site on my own local server but I'm only using the stable 3.2.0 plugin version of Gutenberg.

I've disabled all plugins, retested and can consistently reproduce the issue by adding a Classic block.

The test page where I first encountered the error had all sorts of different blocks on it. To try and narrow it down I created a new page and started adding different blocks and clicking preview. As soon as I add a Classic Block, the preview breaks.

Here's a vid: https://cl.ly/0J071E2z0u1F

**Comment by designsimply** [comment] 2018-07-19 22:59
Nice sleuthing! I added the `Needs Testing` label so someone can loop back around and help test/verify.

**Comment by Clorith** [comment] 2018-07-22 23:06
I'm able to reliably reproduce this, it seems that if you hit the preview button before some kind of state change occurs, it's left in the "generating preview" screen for ever, it's not receiving the URL it needs to redirect to. If you wait a second or two after updating before hitting the preview, it works just fine.

I'm wondering if implementing https://github.com/WordPress/gutenberg/issues/7922#issuecomment-406352371 would remove this problem entirely, as it seems to be the intermediary of our fancy "generating preview" page that's causing the issue, and the content is already saved and ready for viewing?

**Comment by designsimply** [comment] 2018-08-14 23:40
I re-tested and found that previews get stuck for me any time I try to preview an autosaved post:

1. Create and publish a post.
1. Make a change to the post and leave without saving.
1. Re-open the post and see an autosave notice at the top.
1. Click the "Preview" button.

**Result:** cannot preview published posts that have an autosave.

**Video:** [41s](https://cloudup.com/c98QK9_wjeM)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14242&action=edit running WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 on macOS 10.13.6.</sup>

![autosave-400-error-when-trying-to-preview-a-post-with-an-autosave](https://user-images.githubusercontent.com/1119271/44123667-995a042e-9fe6-11e8-884e-f0adc74a353a.png)

Here is the autosave API response from the Network tab in my browser:

`{"code":"rest_autosave_no_changes","message":"There is nothing to save. The autosave and the post content are the same.","data":{"status":400}}`

@maddisondesigns can you check to see if the steps above consistently result in stuck previews for you?

**Comment by designsimply** [comment] 2018-08-15 00:32
While researching preview issues today, I realized that this one is a duplicate of #7416.

**Closed by designsimply** 2018-08-15 00:32 UTC
Labels: [Component] Saving, [Type] Bug
