### ISSUE TITLE
Multiple RichText issues

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#6740] opened 2018-05-14 13:47 UTC
Hello.

I'm not sure if this is a bug or if I made a mistake: 

When I create a block with multiple RichText I have several issues: 

### 1. Toolbar Duplication

First, the toolbar displays as many toolbars as RichText called : 

![capture 2018-05-14 a 15 30 36](https://user-images.githubusercontent.com/1785489/40000760-ee968018-578c-11e8-84d0-2a1841c0c12d.jpg)

###  2. All placeholder disappear

Then, when entering the block, all the placeholder disappear 

The user doesn't know where are the next RichText in the block. Eg: on my screenshot, the 2 "text here" are not displaying anything and become really hard to spot without using tab.

(note: as the block is right floated, I've put a minimum width in order to be able to click on the fields.)

According to the documentation, I've used the RichText as intended. 

keepPlaceholderOnFocus="true" helps a little but it never removes the label

I think it could be better if only the focused RichText removes the placeholder.

### 3. Set focus to a RichText on block focus 

And last : 

I don't find a way to set the focus on, let's say, the second Richtext by default. I think it was possible in the past. Any idea ?

**Comment by ocean90** [comment] 2018-05-14 14:06
You have to work with an `editable` state and the `onFocus`/`isSelected` attributes. Take a look at the Quote block for an example: https://github.com/WordPress/gutenberg/blob/eabf6821c76d56bbbc00dd70f6d539b9199fbe67/core-blocks/quote/index.js#L82-L132

The placeholder issue should be fixed with #6470.

**Comment by maximebj** [comment] 2018-05-14 15:47
Thank you both for your answers. 

I'm in 2.8 yes. 

You can reproduce the issue with this simple example : 

`		edit: props => {

			const { attributes: { title, content }, setAttributes, className } = props

			return (
				<div className={ className }>
					<RichText
						tagName="p"
						placeholder={ __( 'title' ) }
						value={ title }
						className="title"
						onChange={ title => props.setAttributes( { title } ) }
					/>
					<RichText
						tagName="p"
						placeholder={ __( 'content' ) }
						value={ props.attributes.content }
						className="content"
						onChange={ content => props.setAttributes( { content } ) }
					/>
				</div>
			)
		},
`

Maybe I need something more in this particular case.

**Comment by gziolo** [comment] 2018-05-15 07:34
This issue is duplicate of #6213 and it was solved in `master` branch. 2.9 should be released later this week and you shouldn't have this issue anymore. Displaying formatting toolbar is now automatically handled by `RichText` component with changes introduced in #6419. When you omit `isSelected` and `onFocus` props, as you did, it should work perfectly fine.

**Closed by gziolo** 2018-05-15 07:34 UTC
Labels: [Component] Rich Text, [Type] Bug

**Comment by maximebj** [comment] 2018-05-15 07:52
Ok thanks a lot!
