### ISSUE TITLE
Getting confirmation popup when trying to leave page after Saving Draft

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3447] opened 2017-11-13 01:31 UTC
## Issue Overview
I created a new Page and added a Paragraph Block and an Image. I then clicked the _Save Draft_ link. When I tried to exit back to the dashboard, I received a popup, warning that I might lose data.

I then clicked Save Draft again, and tried to exit the editor again, and still received the same popup. This kept happening no matter how many times I clicked _Save Draft_.

## Steps to Reproduce (for bugs)

1. Create Page
2. Add content
3. Click _Save Draft_ link
4. Select another menu option to go to another page in the Dashboard (i.e. Exit the editor)

## Expected Behavior
Once I've clicked _Save Draft_ and haven't made any further changes, I should be able to simply exit without any prompts

## Current Behavior

Receiving popup warning of possible data loss if I exit the page.

![screenshot_518](https://user-images.githubusercontent.com/2078245/32706021-1acb37a4-c86e-11e7-90aa-3bc23b16c8e3.png)

_Gutenberg 1.6.1
Firefox 56.0.2 (64-bit)
macOS Sierra 10.12.1_

**Comment by pento** [comment] 2017-11-13 06:59
Duplicate of #3296, fixed in Gutenberg 1.7.

**Closed by pento** 2017-11-13 06:59 UTC
