### ISSUE TITLE
Image Block's max-width is not 100% in the Editor, while following max-width 100% at the frontend

### ISSUE THREAD

**Issue by frankyhung93** [WordPress/gutenberg#25276] opened 2020-09-13 12:11 UTC
**Describe the bug**
At the backend(Gutenberg Editor):
 - I created an image block within the first column in a 2-col columns block. I set the image to display 100% under Image Dimensions then it becomes too large and overshoots the column's boundary.

At the frontend(after the page is saved): 
 - the Image follows the css `max-width: 100%` as defined in `wp-includes/css/dist/block-library/style.css?ver=5.5.1` and fills up 100% of the column's width.

**Screenshots**
(In Editor) The image block in the first column:
![image](https://user-images.githubusercontent.com/12358072/93017574-63042080-f5fc-11ea-83d8-250d78a44223.png)

(In Editor) The second column shown with the background of the oversized img from the first column:
![image](https://user-images.githubusercontent.com/12358072/93017560-4962d900-f5fc-11ea-9de7-df34789421a9.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by paaljoachim** [comment] 2020-12-16 12:57
Hi @frankyhung93 

I believe this is a duplicate of this issue (I am linking to a comment I just made in the other issue.)
https://github.com/WordPress/gutenberg/issues/12168#issuecomment-746215190

We can then close your issue. Thank you for bringing it up!
If I am mistaken let me know and I will reopen the issue.

**Closed by paaljoachim** 2020-12-16 12:57 UTC
Labels: [Block] Image, [Type] Enhancement
