### ISSUE TITLE
 Gutenberg error with tag “&” and adding spaces

### ISSUE THREAD

**Issue by HelArcherix** [WordPress/gutenberg#14027] opened 2019-02-21 17:57 UTC
Adding a tag with “&” crashes the new Gutenberg editor
Video: https://youtu.be/mafw4Onq6zc

When I make a copy/paste of some hyperlinked text it adds blank spaces around that word.
Video: https://www.youtube.com/watch?v=upD3xbYSFDI

**Comment by aduth** [comment] 2019-02-25 15:57
I believe this is a duplicate of #12832, which was fixed in #12889 and included in the Gutenberg 4.9 plugin release . I don't believe this has been included yet in a WordPress release, so for the fix to take effect in the meantime, you'll need to use the latest version of the plugin.

Duplicate of #12832

**Closed by aduth** 2019-02-25 15:57 UTC
