### ISSUE TITLE
Separator block: Can't access block toolbar with mouse

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#12968] opened 2018-12-18 10:28 UTC
**Describe the bug**
Gutenberg v 4.7.0, WP 5.0.1
You can't access the toolbar for a separator block by hovering/clicking on it. You have to click the block before or after the separator block and navigate to it with the keyboard for the toolbar to display. Tested with and without the "Top Toolbar" setting checked.

**To Reproduce**
1. Add a separator block
2. Click on another block
3. Try to bring up the toolbar for the separator block by hovering/clicking on the separator block

**Expected behavior**
You should be able to access the separator block toolbar either by hovering or clicking on the block.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/50148018-c6daa780-02b7-11e9-952d-a57b30d900a1.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Safari
 - Version: 12.0

**Comment by swissspidy** [comment] 2018-12-18 11:39
Closing as duplicate of #12080 as it already has a PR (#12950).

**Closed by swissspidy** 2018-12-18 11:39 UTC
Labels: [Block] Separator, [Status] Duplicate
