### ISSUE TITLE
Block option menu: block option menu doesn't open upwards if its' too long and the block near the bottom

### ISSUE THREAD

**Issue by mohmed98** [WordPress/gutenberg#40402] opened 2022-04-17 01:46 UTC
### Description

When opening the block option menu and the block is placed near the screen bottom the menu is still open to the bottom and the last elements get hidden the block must be so close to the screen bottom to open it upwards.

### Step-by-step reproduction instructions

1-scroll the block to be near the screen bottom
2-click option

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/43110858/163696693-50940300-778a-41ea-9a56-5c94f124f8c7.png)

### Environment info

I am using the WordPress Beta Tester plugin
WordPress version development version (6.0-beta1-53191). 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-04-18 12:36
I can confirm.

**Comment by Mamaduka** [comment] 2022-04-18 13:18
@paaljoachim, I think you also created a similar issue. Can you confirm, and we can close one as a duplicate?

**Comment by paaljoachim** [comment] 2022-04-18 15:26
Hey @mohmed98 
Here is the issue I made:
https://github.com/WordPress/gutenberg/issues/40224

Can you close your issue as a duplicate of the one I made?

**Comment by mohmed98** [comment] 2022-04-18 15:29
Yeah, sure I didn't see it when I was searching for similar issues

**Closed as completed** 2022-04-18 15:30 UTC
Labels: [Type] Bug, General Interface, [Status] Duplicate
