### ISSUE TITLE
Highlight text color selection is not preserved when cursor is placed in the middle of text

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#42714] opened 2022-07-26 19:35 UTC
## Description
If the cursor is placed in the middle of Paragraph text, setting the color has no impact on newly typed text. 

## Step-by-step reproduction instructions
1. Add text to a Paragraph block. 
1. Move cursor to the middle of the text. 
1. Set a different color.
1. Begin typing. 

## Expected behaviour
The typed text is displayed in the selected color. 

## Actual behaviour
The type text is displayed in the default theme color. 

## Screenshots or screen recording (optional)

<details><summary>UX Recording</summary>

https://user-images.githubusercontent.com/438664/181096016-563fab16-67a7-4df5-ab28-6288f733f3e4.MP4

</details>

## WordPress information
- WordPress version: 6.0
- Gutenberg version: 13.7.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Geologist. 

## Device information
- Device: iPhone SE
- Operating system: iOS 15.6
- WordPress app version: 20.3

**Comment by fluiddot** [comment] 2022-07-27 08:49
I also reproduced this issue in an older version (20.0), so looks like it was introduced several versions ago.

**Comment by SiobhyB** [comment] 2023-05-30 13:23
Verifying that this is still an issue with the latest version of the app (22.5).

**Comment by dcalhoun** [comment] 2023-12-07 13:00
> For edge cases where we don't have support yet, it won't try to apply the format to avoid confusion seeing this format in the toolbar enabled but not showing in the actual test. An example of this edge case would be placing the caret in the middle of a word and toggling on the highlighted text format.

@geriux the above quote is from https://github.com/WordPress/gutenberg/pull/37915. Do you consider fixing highlighting when the caret is in the middle of text not possible with the current Aztec limitations or is it possible if we implement the necessary workarounds in the relevant code below? 

https://github.com/WordPress/gutenberg/blob/5067361dc000cb3ab2b0a180b6a4eae19cd7e7a2/packages/format-library/src/text-color/inline.native.js#L92-L117

Completely fine if your answer is "I don't know." I just figured I'd ask you before diving into the code in case you definitely knew it was not possible due to the native limitations from your previous explorations. Thanks! 🙇🏻

**Comment by geriux** [comment] 2023-12-07 19:45
Hey @dcalhoun 👋 

> Do you consider fixing highlighting when the caret is in the middle of text not possible with the current Aztec limitations or is it possible if we implement the necessary workarounds in the relevant code below?

I think it could be worth revisiting that implementation, I remember there were a few issues when applying this formatting and If I recall correctly some improvements have been made after we implemented it so I think we could try if we can make it work on the JS side. If not it would require some native work in Aztec and the `mark` tag formatting.

**Comment by dcalhoun** [comment] 2023-12-08 18:57
After reviewing the code and observing its behavior, there doesn't appear to be a simple fix for highlighting text when placing the cursor in the middle of text and having no text selected. I'll note a few aspects I observed for future reference: 

* The JavaScript includes a [few workarounds](https://github.com/WordPress/gutenberg/blob/5067361dc000cb3ab2b0a180b6a4eae19cd7e7a2/packages/format-library/src/text-color/inline.native.js#L92-L117) to manually apply highlight formatting, i.e., `mark`, in specific scenarios by invisibly selecting one adjacent character when it is "safe" (an invisible space character). 
* When placing a cursor in the middle of text and enabling a highlight color, the `text-color` or "mark" format is correctly activated in JavaScript and past to and received by the native Aztec editor (iOS). 
* When one begins typing after enabling after enabling a highlight color, an expected `<mark></mark>` tag is _not_ inserted into the value, which is the crux of the originally reported issue. 

With the time I allotted, I did not make it far enough into the native Aztec implementation to understand _why_ or _where_ the received `mark` format is lost and not applied. Presumably, the same result occurs on Android, but I did not spend time investigating that. 

## Next Steps

From my current understanding, I do not foresee us solving this on the JavaScript side without replacing Aztec. So, we'll either need to replace Aztec or improve Aztec to handle this "cursor placed in the middle of text without selecting text" scenario. 

I am removing my assignment for the time being, as I plan to focus on other work for the foreseeable future.

**Comment by geriux** [comment] 2024-01-12 11:22
I have a fix for this that I'm working on currently so I'll remove the High priority label.

**Closed as completed** 2024-03-21 15:30 UTC
Labels: [Type] Bug, Mobile App - i.e. Android or iOS, [Block] Paragraph, [Feature] Colors
