### ISSUE TITLE
[ Navigation Screen ] No initial nested inserter

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#23308] opened 2020-06-19 12:17 UTC
When the navigation only contains top level links, in the Navigator clicking one does not allow to add nested links.

![no-initial-add-link](https://user-images.githubusercontent.com/107534/85131632-da195b00-b23f-11ea-83be-2e8b9e345c8c.gif)

I expect the navigator to allow me to form the entire menu without having to resort to the block on the right. Also showing an inserter even if there is no nesting yet seems consistent.

**Comment by adamziel** [comment] 2020-07-03 12:01
I can't reproduce the top-level links issue, it must have been fixed in the meantime.

As for the inserter not being visible by default, this PR solves it: https://github.com/WordPress/gutenberg/pull/23676

**Comment by adamziel** [comment] 2020-07-07 11:32
The inserter is now visible by default. I wonder if the other issue was related to https://github.com/WordPress/gutenberg/pull/23680 ? Either way - I am unable to reproduce the problem anymore so I'm closing the issue. Feel free to reopen if it returns.

**Closed by adamziel** 2020-07-07 11:32 UTC
Labels: [Feature] Navigation Screen, [Type] Bug
