### ISSUE TITLE
Image Size dialog box disappears from the Image Settings

### ISSUE THREAD

**Issue by MichaelCampanella** [WordPress/gutenberg#12762] opened 2018-12-10 13:31 UTC
I am having a very strange issue. I cloned my website and installed it locally because I wanted to change the image sizes and rebuild my thumbnails. 

On the version of my website that is live on my server when I click on an image, I get an option in the right-hand sidebar to change the image size.  See the screenshot below: 

<img width="1450" alt="screenshot 2018-12-10 at 14 18 44" src="https://user-images.githubusercontent.com/45566100/49735312-354fb200-fc87-11e8-9aa9-a5f64cf99380.png">

However on my local copy that I cloned that option is missing. See the screenshot of the exact same post from the local copy: 

<img width="1450" alt="screenshot 2018-12-10 at 14 18 55" src="https://user-images.githubusercontent.com/45566100/49735348-52848080-fc87-11e8-8717-db68da5030f9.png">

**Comment by designsimply** [comment] 2018-12-11 23:59
Would it be possible for you to compare the HTML for an image from the live site and the cloned site to see if the HTML is different? You can see the HTML by clicking the More menu in the very top right toolbar and then selecting the "Code Editor" option.

> I cloned my website and installed it locally. 

How exactly did you clone the site? Can you list out your steps for that?

**Comment by MichaelCampanella** [comment] 2018-12-12 06:45
I used Duplicator to make a copy and installed it on my localhost. My plan was to rebuild the image sizes locally since I have a lot of photographs and then replace the version on my web server with the local copy. 

But it's not just that there are discrepancies between identical posts on the real site and the clone site. I can open a post with multiple images and clicking on the various image blocks will produce a different result as I go through the page. It makes no sense and I never know what I am going to get. 

Look at these screenshots, all from the same post. I will scroll through and click on each of the images. 

<img width="1429" alt="screenshot 2018-12-12 at 07 37 48" src="https://user-images.githubusercontent.com/45566100/49851365-29780300-fde1-11e8-8a4a-423df37f76ae.png">

The first image in the post, click on the image block and the panel on the right only has an option for the alt text.  The image is set to wide alignment by the way. 

<img width="1429" alt="screenshot 2018-12-12 at 07 37 55" src="https://user-images.githubusercontent.com/45566100/49851434-52989380-fde1-11e8-8e9f-8aa8b5fa333e.png">

Scroll down a bit to the second image in the post, also set to wide alignment and it has Alt Text and image size options. 

<img width="1429" alt="screenshot 2018-12-12 at 07 38 25" src="https://user-images.githubusercontent.com/45566100/49851459-6fcd6200-fde1-11e8-8cfa-d8a269f1445f.png">

Third image in the post and we are back to just having the Alt Text option. 

<img width="1429" alt="screenshot 2018-12-12 at 07 38 36" src="https://user-images.githubusercontent.com/45566100/49851491-84a9f580-fde1-11e8-8883-8272bb9034f8.png">

Then finally on the final image in the post we get Alt Text and Image Dimensions. Just to change things up a bit. 

This is confusing as hell. Clicking an image block should produce the same settings in the Image Settings panel each time. Alt Text, Image Size, and Image Dimensions should all be present each and every single time in my opinion.

**Comment by MichaelCampanella** [comment] 2018-12-27 08:37
@designsimply No, it occurs on my live site too. Especially on older posts that were made pre-Gutenberg and then converted to Gutenberg blocks and updated. 

If you look at my previous post those screenshots are from a [post I made on December 30th, 2017](https://blog.campanella.se/2017-year-in-review/) which I then updated to Gutenberg once the 5.0 release was approaching. 

Just click on some of the various image blocks in that post I get different options in the Image Settings. Sometimes just Alt-Text (this is the most annoying one), sometimes Alt-Text + Image Size, and sometimes Alt-Text + Image Dimensions. 

There is no consistency and as a user, I definitely do not understand why I am seeing varying versions of the Image Settings panel. I would expect one Image Settings panel that consistently displays when you click and select an image block.

**Comment by youknowriad** [comment] 2019-08-23 09:20
I'm going to close this issue now as we've been unable to reproduce this issue. I think the difference in your installs is the timing between the image size thumbnails definition and the upload of the said image.

A plugin like this https://wordpress.org/plugins/regenerate-thumbnails/ would make the experience consistent by regenerating all the required thumbnails for all the images.

**Closed by youknowriad** 2019-08-23 09:20 UTC
Labels: Needs Testing, [Block] Image

**Comment by kuworking** [comment] 2020-08-15 20:41
It has happened to me right now

In my local copy I do see the Image Size option, I've created an identical site online (both WP 5.5), and I've created the same posts with the same image dropped there

In my online site I cannot see the Image Size option in the gutenberg block

Still looking to see what can be the problem, @MichaelCampanella did you find out what happened?
