### ISSUE TITLE
Paragraph block: Floating drop-cap is problematic

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8447] opened 2018-08-03 14:26 UTC
Drop caps are problematic due to their floatyness:

![2018-07-25 11 55 54](https://user-images.githubusercontent.com/376315/43199777-0aa4b3a4-900b-11e8-867f-7c7ad9d48b3d.gif)

<img width="675" alt="screenshot 2018-07-25 12 33 32" src="https://user-images.githubusercontent.com/376315/43199913-72a3cd96-900b-11e8-9884-08bb1cc1aa31.png">

<img width="679" alt="screenshot 2018-07-25 11 55 39" src="https://user-images.githubusercontent.com/376315/43199935-82ea5526-900b-11e8-96d3-324f47c869a9.png">

The ideal solution would be to use `:initial-letter` here and nix the float altogether, but it has terrible browser support still. 😭 

Better might be to clear the float at the end of the block, but I'm not sure if that has potential to collide with other layout elements and it's been already considered and discarded. I can't think of anything offhand though, since the paragraph block itself can't be floated in the overall layout. 

Related, possible the same issue: #8428
Also related: #8293

**Comment by youknowriad** [comment] 2018-08-03 14:27
Let's consolidate all "Drop cap" floating issues on this one. I'm closing the other issues.

**Comment by mcsf** [comment] 2018-11-18 14:13
#10832 seems to have more momentum and is kind of a duplicate of this one. It is also milestoned. Should we close this issue in favor of #10832?

**Comment by mcsf** [comment] 2018-11-18 14:14
Closing but feel free to reopen if you feel this is a separate concern.

**Closed by mcsf** 2018-11-18 14:14 UTC
Labels: Blocks, [Block] Paragraph, [Type] Enhancement
