### ISSUE TITLE
Floated blocks don't get Move or Drag Controls

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#10300] opened 2018-10-03 11:23 UTC
**Describe the bug**
Normally when you select a block, the move controls and drag control show on the left of the block. When a Cover Image block is right aligned and then selected, no controls appear which means that it can no longer be moved.

Another issue is that when the cover image is left aligned, the controls appear, but it's incredibly difficult to move the block. Whenever you try to click and drag the using the drag control, the text block beneath it gets selected instead. Occasionally, if you're lucky and move the cursor fast enough, you can drag the Cover Image.

Vid: https://cl.ly/c65a76f434e5

**To Reproduce**
1. Add multiple Paragraphs of text
2. Insert Cover Image Block below second Paragraph block and right align
3. Select Cover Image block and see there's no drag/move controls showing

**Desktop (please complete the following information):**
 - OS: MacOS Sierra 10.12.6
 - Browser: Firefox Quantum 62.0.3 (64-bit)
 - Gutenberg 3.9

**Comment by saulirajala** [comment] 2018-10-06 19:43
I can confirm this bug. I tested with Chrome 69.0.3497.100 on MacOS 10.13.6 with fresh WordPress install (runs in docker setup of Gutenberg) and Twentyseventeen-theme.
<img width="856" alt="nayttokuva 2018-10-6 kello 22 33 58" src="https://user-images.githubusercontent.com/5536354/46575140-5e6a7280-c9b8-11e8-8ff3-cf8c291f7a53.png">

The same happens, if Cover Image Block is aligned left. Although Move-controls are visible, you can't really use them. If you try to use Move-controls, it will move paragraph-block instead of Cover Image -block
<img width="857" alt="nayttokuva 2018-10-6 kello 22 38 17" src="https://user-images.githubusercontent.com/5536354/46575162-b3a68400-c9b8-11e8-9ca6-3b5f313a5604.png">

**Comment by saulirajala** [comment] 2018-10-06 19:49
This issue might have something to do with #4764 🤔

**Comment by carladoria** [comment] 2018-10-26 20:04
I was able to reproduce this too and even worst, I can only see the controls to move blocks for the central block:

![download](https://user-images.githubusercontent.com/23703267/47589945-bc93d100-d938-11e8-991c-f1b448f8f556.jpeg)

**Comment by chrisvanpatten** [comment] 2018-10-26 20:18
This is intentional behaviour for floated blocks now, per #10085.

**Comment by maddisondesigns** [comment] 2018-10-27 02:01
That is absolutely ridiculous that you can't move an item that is right aligned, and it's even more ridiculous that you're no longer trying to fix the issue.

**Comment by chrisvanpatten** [comment] 2018-10-27 03:04
@maddisondesigns No one ever said we weren't going to try to improve this. The fact is that drag and movement controls on floated blocks caused a lot of UI issues and we still hope we can solve those issues, especially in Phase 2 which will have a much bigger focus on block layout. We just have to prioritise other things right now especially for those of us who are volunteering and have limited hours to commit to the project.

**Comment by maddisondesigns** [comment] 2018-10-28 02:50
> It hides the side UI entirely. Because this is now just the ellipsis and drag handle, this is not the end of the world. The argument being, that when you need to move an image up or down, you do it before you float.

Pretty sure that's exactly what that says (from #10085). This bug is being justified for a ridiculous reason.

> We just have to prioritise other things right now

I totally understand that people like yourself who are volunteering have limited hours, and I really appreciate the work that you've put into this, but there are Automatticians who are getting paid to work on this, so trying to justify this bug purely because there are a bunch of other bugs that also need fixing, is irresponsible.

What happened to the whole "This wont be merged until its ready" argument. Seems like nobody cares about that now and the priority is to simply get it in before WordCamp US, no matter the cost.

**Comment by designsimply** [comment] 2018-11-03 15:05
Tested and confirmed using an image block (#11454). Updated the title to note it's not limited to Cover. Closing this one because it's a known issue, the missing movers are a temporary workaround, and there are plans to re-visit when more time is available to spend because it needs a special implementation. See #11454.

I also wanted to say thank you for raising these kinds of issues! It's good to raise them and your feedback is definitely heard.

**Closed by designsimply** 2018-11-03 15:05 UTC
Labels: Drag and Drop, Needs Testing
