### ISSUE TITLE
upload images throw error"The response is not a valid JSON response"

### ISSUE THREAD

**Issue by rewalax** [WordPress/gutenberg#9720] opened 2018-09-09 03:04 UTC
when i upload an image or image gallery,it will throw an error"The response is not a valid JSON response".it works fine when pick an image from media library. pls fix this.
(my env: windows server 2008 R2/IIS 7.5/PHP 7.2)

**Comment by youknowriad** [comment] 2018-09-10 12:39
I think you probably have some PHP warnings/errors in the response of the XHR requests uploading the images. Can you check the network panel of your browsers to see the response for these API calls? Thanks

**Comment by designsimply** [comment] 2018-09-10 19:09
I tried testing and am unable to reproduce the problem. Note: I did not test with an IIS server but this is something I can setup in the future if needed.

Noting that this is a duplicate of #8935 but I will leave this open for a little while since more information was asked for and it would be really nice to have some extra details on this one!

**Comment by katiebethbrown** [comment] 2018-09-25 14:51
I am seeing the same error - "The response is not a valid JSON response" - when adding an image block and either choosing the upload dialog or dragging the image in.

When I try dragging the image straight into the editor, the image appears and flashes in and out. If I preview the post, the image shows. If I update and then view the published version the image is not there.

I have tried with multiple different images and all have the same result.

I am using FF Quantum 62.0.2 (64-bit).

GIF of what I am seeing: https://cld.wthms.co/XCDHZH

**Comment by designsimply** [comment] 2018-09-27 18:54
Thank you for the details @katiebethbrown! I saw that you also posted the same in #8935 so let's close this issue in favor of consolidating into one.

**Closed by designsimply** 2018-09-27 18:54 UTC
Labels: [Status] Duplicate, [Status] Needs More Info
