### ISSUE TITLE
Tooltip overflows when used in a modal

### ISSUE THREAD

**Issue by moon0326** [WordPress/gutenberg#28311] opened 2021-01-19 00:55 UTC
## Description
The popover component overflows or positioned incorrectly when used in a model component. 

## Step-by-step reproduction instructions

1. Open https://wordpress.github.io/gutenberg/?path=/story/components-modal--default
2. Click "Open Modal"
3. Mouse over "X" button and wait for the popover to popup.

## Expected behaviour
The popover should be displayed correctly without overflowing the modal.

## Actual behaviour
The popover overflows the modal and does not display.

## Screenshots or screen recording (optional)

Chrome -- Overflows and the popover is positioned incorrectly

![chrome](https://user-images.githubusercontent.com/4723145/104974657-8590b680-59ad-11eb-8829-1ad474a01f4b.gif)

Safari -- Does not show the popover

![safari](https://user-images.githubusercontent.com/4723145/104974667-89bcd400-59ad-11eb-826b-00b4d8d3b1ed.gif)

Firefox: Overflows

![firefox](https://user-images.githubusercontent.com/4723145/104974675-8d505b00-59ad-11eb-81f4-e7359be782a3.gif)

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.4.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme? Yes

## Device information
- Device: Desktop
- Operating system: Mac OS 10.15.4
- Browser: Chrome 87.0.4280.88, Safari 13.1, Firefox 84.0.2

**Comment by talldan** [comment] 2021-01-19 06:56
Seems to only be an issue in the storybook, in the editor it still works:
<img width="360" alt="Screenshot 2021-01-19 at 2 55 15 pm" src="https://user-images.githubusercontent.com/677833/104998564-6ace4880-5a66-11eb-9f9f-74ec4d982c19.png">

Maybe there's some extra styling that fixes things in the editor 🤔

**Comment by moon0326** [comment] 2021-01-19 07:16
> Seems to only be an issue in the storybook, in the editor it still works:
> <img alt="Screenshot 2021-01-19 at 2 55 15 pm" width="360" src="https://user-images.githubusercontent.com/677833/104998564-6ace4880-5a66-11eb-9f9f-74ec4d982c19.png">
> 
> Maybe there's some extra styling that fixes things in the editor 🤔

Thank you for taking the time to test it. We actually have the same issue on our welcome modal in WC Admin. You can see some screenshots in the linked [issue](https://github.com/woocommerce/woocommerce-admin/issues/6085).

**Comment by IslamYehia1** [comment] 2021-01-19 11:46
I can fix this issue.. working on it.

**Comment by iandunn** [comment] 2021-02-01 19:41
Possibly related: #15434

**Comment by youknowriad** [comment] 2023-06-01 08:38
I'm not able to reproduce this issue anymore. Closing.

**Closed by youknowriad** 2023-06-01 08:38 UTC
Labels: [Type] Bug, Good First Issue, [Package] Components
