### ISSUE TITLE
Improve contrast of site editor navigation current state color

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51942] opened 2023-06-26 20:48 UTC
Proposing that the `.edit-site-sidebar-navigation-item.components-item[aria-current]` is changed to white. 

Before: 
<img width="355" alt="CleanShot 2023-06-26 at 16 45 43" src="https://github.com/WordPress/gutenberg/assets/1813435/f00f0b20-d401-46ee-b759-59c9a4f98853">

After: 
<img width="357" alt="CleanShot 2023-06-26 at 16 46 05" src="https://github.com/WordPress/gutenberg/assets/1813435/ac2b6ef4-967a-4488-836c-970b7f555ddf">

**Comment by jasmussen** [comment] 2023-06-27 07:30
Should be white text, yes, could this be a recent regression from #51856 @jameskoster?

**Comment by jameskoster** [comment] 2023-06-27 09:26
Yes looks like it. I'll open a PR shortly.

**Comment by jameskoster** [comment] 2023-06-27 10:52
Closed via https://github.com/WordPress/gutenberg/pull/51965.

**Closed as completed by jameskoster** 2023-06-27 10:52 UTC
Labels: [Feature] Site Editor
