### ISSUE TITLE
Menu-bar pop-up menu-things only hide on blur, not on click

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#11579] opened 2018-11-07 13:14 UTC
**Describe the bug**
When clicking the buttons in the top menu-bar thing that have drop-downs (vertical ellipsis, block navigator, or content structure) clicking them makes a pop-up pointer thing appear, but there is no visual indication on how to make them disappear.

Clicking them again does not hide them. Hovering off of them makes them go flat, giving the appearance that the button is unaware that the menu exists.

**To Reproduce**
1. Go to 'Add New Post'
2. Click on 'circle with an "I" in it' icon
3. A pop-up menu pointer thing appears
4. Clicking the pop-up menu pointer thing does not hide the thing
5. Clicking the 'circle with an "I" in it' button does not hide the pop-up menu pointer thing
6. These menu-buttons lack a "pressed-down" state or styling in WordPress 5.0 beta 3.

**Expected behavior**
These look like menus, have drop-down pop-up menu box things, so they should work similarly.

1. Clicking on a menu button should invoke a "pressed-down" state & styling
2. Re-clicking the menu button should hide the menu and restore the button state

**Screenshots**
<img width="575" alt="screen shot 2018-11-07 at 7 11 49 am" src="https://user-images.githubusercontent.com/88951/48133467-7144c100-e25c-11e8-819d-c94d6c2d57d6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser All
 - Version: Any

**Additional context**
- WordPress 5.0 Beta 3

**Comment by designsimply** [comment] 2018-11-07 14:44
Testing note: need to check this against the plugin to see if it happens here as well as with WP 5.0 beta.

**Comment by afercia** [comment] 2018-11-07 15:35
Quickly testing the plugin version 4.2.0 the buttons don't have a "pressed" style but clicking again on them does close the popups. Instead, on current Gutenberg master https://github.com/WordPress/gutenberg/commit/26ccc159f373e5412d4fabf20fa00431d8fce7b6 clicking on the buttons again does nothing. Seems to be a regression in master?

**Comment by afercia** [comment] 2018-11-08 08:02
Same happens on the "More" button in the top bar: it is now impossible to close the menu clicking again on the button. Adding the label "regression".

<img width="520" alt="screenshot 2018-11-08 at 09 00 43" src="https://user-images.githubusercontent.com/1682452/48185326-eedc0000-e334-11e8-8c80-41fbcca25344.png">

**Comment by afercia** [comment] 2018-11-08 08:18
Reverting https://github.com/WordPress/gutenberg/commit/58725c42980f81dbcf18d921be7ca43507c968e0 fixes it for me. /Cc @aduth

**Comment by aduth** [comment] 2018-11-08 13:49
As best I can tell, this issue includes two actionable tasks:

>1. Clicking on a menu button should invoke a "pressed-down" state & styling
>2. Re-clicking the menu button should hide the menu and restore the button state

The first was a known compromise in transitioning focus to the modal to preserve tab order. It's not strictly unavoidable, but the technical implementation has proven challenging enough that it's been not likely to change anytime soon. See previously: #5595

The second does appear to be a regression. I'll plan to tackle it today, including an end-to-end test to avoid similar future regressions.

**Comment by aduth** [comment] 2018-11-08 15:59
Pull request fixing toggle behavior at #11633

**Comment by mtias** [comment] 2018-11-15 20:19
Closing and moving the "pressed state" issue here: #6177

**Closed by mtias** 2018-11-15 20:19 UTC
Labels: Needs Design, Regression, UI Components, User Experience (UX)

**Comment by aduth** [comment] 2018-11-16 00:52
I assume that's meant to be #11937
