### ISSUE TITLE
Allow displaying only Pages which are a child of another Page

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#42599] opened 2022-07-21 12:29 UTC
## What problem does this address?

Currently the Page List has no configuration options and simply dispays all Pages. This is rarely what we want.

One common use case is to display only pages which are children of another Page.

## What is your proposed solution?

Let's update the Page List block to allow it to display only Pages which are children of another Pages which we choose.

Ideally this would be via some kind of simple UI where you can pick a page.

@javierarce Do you have any ideas of existing UI we could reuse for this task?

**Comment by skorasaurus** [comment] 2022-07-22 17:17
closing this as it's a duplicate of https://github.com/WordPress/gutenberg/issues/37130

**Closed as completed by skorasaurus** 2022-07-22 17:17 UTC
Labels: [Status] Duplicate, [Type] Feature, [Block] Page List
