### ISSUE TITLE
Allow all Gutenberg theme support options to be defined in theme.json

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#26901] opened 2020-11-11 17:39 UTC
Many of [Gutenberg's `add_theme_support()` options](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-support.md) are already available to define in `experimental-theme.json`: 

- `disable-custom-font-sizes`
- `disable-custom-colors`
- `disable-custom-gradients`
- `editor-color-palette`
- `editor-gradient-presets`
- `editor-font-sizes`
- `custom-line-height`
- `custom-units`
- `custom-spacing`
- `experimental-link-color`

The rest should be made available there as well: 

- `align-wide`
- `core-block-patterns` (opt-out)
- `editor-styles`
- `dark-editor-style`
- `post-thumbnails`
- `responsive-embeds`
- `wp-block-styles`

**Comment by nosolosw** [comment] 2020-11-12 10:26
Some of these are already [possible](https://developer.wordpress.org/block-editor/developers/themes/theme-json/#settings):

- `disable-custom-font-sizes` => settings.typography.customFontSize
- `disable-custom-colors` => settings.color.custom
- `disable-custom-gradients` => settings.color.customGradient

From the [convo](https://github.com/WordPress/theme-experiments/pull/81/files/81d5dc5379b624f5fdc51f6ab83a035eecbdac0a#r520623670), I presume the list of missing options should also contain: `align-wide`, `wp-block-styles`.

**Comment by kjellr** [comment] 2020-11-12 13:00
Thanks, I updated the list above. 👍

**Comment by jorgefilipecosta** [comment] 2020-11-13 17:44
I wonder if for themes with theme.json "editor-styles", and "wp-block-styles" should be true by default. These are new themes being build and it seems like they should play well with all the styles a block contains.

**Comment by kjellr** [comment] 2020-11-13 20:35
> I wonder if for themes with theme.json "editor-styles", and "wp-block-styles" should be true by default.

Yeah, I think that makes sense.

**Comment by pagelab** [comment] 2021-01-13 00:26
It would be nice to include `add_theme_support('html5', ['script', 'style']);`, as [the `type` attribute is not required in HTML5](https://www.w3.org/TR/html52/semantics-scripting.html#element-attrdef-script-type) and currently  enqueued files show them by default. [Reference](https://core.trac.wordpress.org/ticket/42804).

**Comment by carolinan** [comment] 2021-02-22 05:36
> I wonder if for themes with theme.json "editor-styles", and "wp-block-styles" should be true by default. 

Does it make sense to have editor-styles on by default if the theme has no editor style file?

**post-thumbnails**  The block works without theme support being enabled, but without the setting in the document sidebar. I wonder if this is already working as intended. (https://github.com/WordPress/gutenberg/issues/22313) 
It depends on how we want to convert existing featured images to blocks 🤔

**Comment by LeoSeyers** [comment] 2021-06-15 13:56
+1 for alignement controls in theme.json (not only wide)

**Comment by devfle** [comment] 2021-08-02 15:50
Do we need something like this the other way around? Things like the new border settings, or the margin feature can currently only be used by FSE themes.

**Comment by youknowriad** [comment] 2021-10-08 16:25
> core-block-patterns (opt-out)
> editor-styles
> post-thumbnails
> responsive-embeds
> wp-block-styles
> html5

For what reasons these are disabled by default? I mean shouldn't we take the opportunity of FSE themes (or themes with theme.json) to enable these automatically? Does it still make sense for these to be configurable, should they be opt-in or opt-out.

**Comment by kjellr** [comment] 2021-10-08 19:01
> editor-styles
> post-thumbnails
> responsive-embeds
> wp-block-styles
> html5

Yeah, all of those seem like things we should enable by default for block themes.

**Comment by jasmussen** [comment] 2021-10-13 13:42
Fairly sure that `dark-editor-style` has been absorbed and retired as a separate feature.

**Comment by noisysocks** [comment] 2021-10-18 06:32
It seems then that the only action required here is to add a setting that equates to `align-wide`?

**Comment by carolinan** [comment] 2021-10-18 07:10
Isn't `align-wide`  the layout setting? If you do not include that in theme.json, the wide and full width is not enabled.

**Comment by youknowriad** [comment] 2021-10-18 08:10
yes `align-wide` is kind of deprecated for block themes.

**Comment by youknowriad** [comment] 2021-10-18 08:10
Let's close this for now.

**Closed by youknowriad** 2021-10-18 08:10 UTC
Labels: [Type] Enhancement, [Feature] Themes, Global Styles
