### ISSUE TITLE
Embedded wordpress URL has too large height.

### ISSUE THREAD

**Issue by yohgaki** [WordPress/gutenberg#10419] opened 2018-10-09 01:31 UTC
**Describe the bug**
Embedded wordpress URL has too large height.

**To Reproduce**
1. Copy wordpress URL
2. paste the URL to article
3. It has too large height both admin and user view

Changing extra CSS value for the element from 

`wp-embed-aspect-1 wp-embed-aspect-1-1`

to 

`wp-embed-aspect-1 wp-embed-aspect-1`

Fixes the issue. 

However, the value is restored on next edit. i.e. The change cannot persist.

Therefore, I suppose there are 2 bugs regarding this issue.

**Expected behavior**
Appropriate height for embedded wordpress URL.

**Screenshots**
 - https://blog.ohgaki.net/php-session-cookie-based-save-handler#i-3

**Desktop (please complete the following information):**
 - OS: linux/macos/windows
 - Browser chrome/firefox/edge
 - Version - current latest

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 6/7/8
 - Browser chrome
 - Version - current latest

**Additional context**
- gutenberg: 3.9.0 WP: 4.9.8 Template: Twenty Seventeen
- this issue is introduced recent updates.

**Comment by desrosj** [comment] 2018-10-15 14:20
I also ran into this issue on my [most recent post](https://make.wordpress.org/core/2018/10/15/wordpress-and-php-7-3/) for the [Make WordPress Core blog](https://make.wordpress.org/core/).

<img width="1128" alt="screen shot 2018-10-15 at 10 15 15 am" src="https://user-images.githubusercontent.com/359867/46956452-5e770c00-d063-11e8-9205-0d1fb4577d24.png">

**Comment by ianbelanger79** [comment] 2018-10-15 19:10
This issue appears to be caused by the new option for media embeds in the blocks toolbar "Automatically scale content". It is turned on by default and it causes the WP and URL embeds to have a much larger height than the content. Turning it off does fix the issue, but this is still a bug, because it is on by default.

![scale-content](https://user-images.githubusercontent.com/34601694/46972337-54b5ce80-d08c-11e8-8d07-a70cd2f099e0.PNG)

**Comment by mtias** [comment] 2018-10-26 22:41
@notnownikki can you look at this one please?

**Comment by notnownikki** [comment] 2018-10-27 12:58
Sure, traveling at the moment but I'm pretty sure this is fixed in master
now. It was a responsiveness issues so we've opted the WP block out. Will
post links to the PR when the m back at a computer.

**Comment by ajitbohra** [comment] 2018-10-27 13:29
@mtias 	@notnownikki 	

Related PR's 
https://github.com/WordPress/gutenberg/pull/10985 
https://github.com/WordPress/gutenberg/pull/11011

Both are marked for 4.2

**Comment by mtias** [comment] 2018-10-30 14:43
Closing as fixed by #10985.

**Closed by mtias** 2018-10-30 14:43 UTC
Labels: Good First Issue, [Block] Embed, [Type] Bug
