### ISSUE TITLE
Putting a dash in the beginning of a line creates a list

### ISSUE THREAD

**Issue by kivig2** [WordPress/gutenberg#13284] opened 2019-01-11 02:07 UTC
**Describe the bug**
Putting a dash+space in the beginning of a paragraph line converts the block into a list, and forcing it back to a paragraph erases the dash.

1. While it is visually quite understandable (although not universally welcome) that the list was automatically created, it takes some time for a new user to understand that it is not a formatting option but a change of paragraph type, turning into frantic clicking in attempts to deactivate the list type button that looks to be at fault.

2. Changing the block back to paragraph erases the dash. Although I've found a workaround of forcing a dash there by copy/paste, a user won't be able/agree to.

3. "But why would anyone ever do that?" - because sometimes you need to write:
"A heading font statement or a quote or an image"
" - an explanation in other font"

**Comment by kivig2** [comment] 2019-01-11 02:40
A separate issue, but perhaps relevant only in case this one gets approved - a space character inserted at the beginning of a line gets deleted upon saving.

**Comment by talldan** [comment] 2019-01-11 04:34
This seems like a duplicate of https://github.com/WordPress/gutenberg/issues/13134.

@kivig2 If you don't mind I'll close this issue in favour of that one. Please feel free to add any thoughts over there, but I'll add a link back to your issue as well.

**Closed by talldan** 2019-01-11 04:34 UTC
Labels: [Status] Duplicate
