### ISSUE TITLE
Pattern Inserter: the panel re-renders after inserting a pattern and doesn't close after clicking on canvas

### ISSUE THREAD

**Issue by miksansegundo** [WordPress/gutenberg#58665] opened 2024-02-05 11:24 UTC
### Description

The pattern inserter panel re-renders multiple times after inserting a pattern and does not close after clicking on the canvas.

### Step-by-step reproduction instructions

- Make sure Gutenberg 17.6 is activated
- Visit the site editor
- Open the Pattern Inserter "[+]" from the top bar
- Click the "About" category and then click on any pattern
- Expect to see the panel flashing multiple times
- Click on any block on the editor canvas
- Expect to see the panel flashing multiple times again when it should close
- Deactivate Gutenberg 17.6 and repeat the steps to verify the issue is not reproducible

### Screenshots, screen recording, code snippet

![Screen Capture on 2567-02-05 at 18-15-19](https://github.com/WordPress/gutenberg/assets/1881481/2f2b99fd-d0ad-434f-84ab-1919d9221f92)

### Environment info

- WordPress 6.4
- Gutenberg 17.6
- Google Chromer 120 
- MacOS Sonoma 14.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2024-02-12 14:59
Thanks for the issue @miksansegundo! I couldn't reproduce on trunk right now 🤔 . @Mamaduka could you reproduce this?

**Comment by Mamaduka** [comment] 2024-02-13 05:29
I can't reproduce it either on the latest trunk (60fc52d1e9bbaa43ec3cc337579b963c8d5ee474) + WP 6.4.x.

I'm unsure which commit fixed it. The #58661 was supposed to be a fix.

Update: Probably was fixed via #58813.

**Closed as completed by Mamaduka** 2024-02-13 05:29 UTC
Labels: [Type] Bug, [Feature] Inserter, [Feature] Site Editor

**Comment by ellatrix** [comment] 2024-02-14 10:19
https://github.com/WordPress/gutenberg/pull/58813 couldn't have been the fix because it's a different UI that was fixed there. I'm guessing it occurs inconsistently? There's been no fix, so this will probably appear again?
