### ISSUE TITLE
Duplicated buttons in block toolbar on paste

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7148] opened 2018-06-05 14:46 UTC
**Describe the bug**

When pasting something in Gutenberg, all buttons in the block toolbar are duplicated until you move the mouse around.

**Screenshots**

<img width="699" alt="screen shot 2018-06-05 at 16 42 16" src="https://user-images.githubusercontent.com/4710635/40983385-cbd9d76e-68df-11e8-9f0a-5c3203e8ba21.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 66.0.3359.139 (Official Build) (64-bit)

**Comment by mcsf** [comment] 2018-06-07 12:50
I can't repro. Can't you provide step-by-step instructions and screencast?

**Comment by iseulde** [comment] 2018-06-08 18:43
![drag-label](https://user-images.githubusercontent.com/4710635/41175164-78f4d998-6b5c-11e8-9404-58557aee697b.gif)

The steps to reproduce are above, I can't really be more detailed I think.

**Comment by ajitbohra** [comment] 2018-07-08 20:15
Unable to reproduce this on the master. Hence closing this for now, feel free to reopen.

Steps followed:
- Created new post
- Posted 5 Paragraphs from https://www.lipsum.com/
- Switched between paragraphs 

The toolbar works as expected.

**Closed by ajitbohra** 2018-07-08 20:15 UTC
Labels: [Type] Bug
