### ISSUE TITLE
Crash adding style to Columns block with registerBlockStyle

### ISSUE THREAD

**Issue by joemaller** [WordPress/gutenberg#10148] opened 2018-09-25 01:45 UTC
**Describe the bug**
Trying to apply the `wp.blocks.registerBlockStyle` filter to the `core/columns` block crashes the editor when trying to open the style selector. 

Tested with Gutenberg 3.9.0 on WordPress 4.9.8.

**To Reproduce**
1. Include this JS snippet somewhere:
```js
wp.blocks.registerBlockStyle("core/columns", {
  name: "column-wrap",
  label: "Wrap Columns",
});
```
2. Add a Columns block to the editor
3. Select the Columns block, click the Block Style selection button
4. Editor crashes on click

**Expected behavior**
`registerBlockStyle` should be able to filter `core/columns/` just like any other block. 

**Screenshots**
![registerblockstyle-crash](https://user-images.githubusercontent.com/8320/45987973-528ac200-c042-11e8-832f-bdbfdac8c813.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6, Windows 10 Pro v1803
 - Browsers/versions:
     - Chrome 69.0.3497.100
     - Edge 42.17134
     - Safari 12.0 (13606.2.11)

**Error text, copied from browser**
```
TypeError: Cannot read property 'innerBlocks' of null
    at t.value (http://iop.test/wp-content/plugins/gutenberg/build/editor/index.js?ver=1537547977:50:134123)
    at t.value (http://iop.test/wp-content/plugins/gutenberg/build/editor/index.js?ver=1537547977:50:133797)
    at commitLifeCycles (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14939:22)
    at commitAllLifeCycles (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16040:7)
    at HTMLUnknownElement.callCallback (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:14)
    at Object.invokeGuardedCallbackDev (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:16)
    at invokeGuardedCallback (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:29)
    at commitRoot (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16181:7)
    at completeRoot (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17196:34)
    at performWorkOnRoot (http://iop.test/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17141:9)
```

**Comment by joemaller** [comment] 2018-09-25 20:28
This looks like a bigger issue with style previews and InnerBlocks. I just tried adding styles to a clone of Columns and the editor crashed the same as above. Using `wp.blocks.registerBlockStyle` is probably the fastest way of revealing the problem and a decent isolation of the problem. 

This should probably be renamed **Editor crash with InnerBlocks and Block Styles**?

**Comment by joemaller** [comment] 2018-09-25 20:57
Very much related: https://github.com/WordPress/gutenberg/issues/9897

**Comment by youknowriad** [comment] 2018-09-25 21:08
Yes closing as duplicate of #9897

**Closed by youknowriad** 2018-09-25 21:08 UTC
Labels: Needs Technical Feedback
