### ISSUE TITLE
default CSS class 'has-text-color' is not replaced

### ISSUE THREAD

**Issue by robincornett** [WordPress/gutenberg#13359] opened 2019-01-17 17:31 UTC
**Describe the bug**
It looks like blocks such as the core paragraph block start with a CSS class of `has-text-color`. When the text color is changed to something else in the presupplied color palettes, instead of this class being replaced, a new class is added, so a paragraph might end up with a duplicate `has-*-color` class, and whichever is later in the stylesheet wins.

**To Reproduce**
1. Activate Twenty Nineteen and create a new post
2. Create a simple paragraph
3. Change the background color (optional)
4. Change the text color to an editor color palette supplied color

**Expected behavior**
I expect just one `has-*-color` class to be applied to the block.

**Actual behavior**
This is the HTML output in the HTML editor. Removing `has-text-color` by hand breaks the block and results in this warning: "This block contains unexpected or invalid content."
```html
<p class="has-text-color has-primary-color">This is a new paragraph.</p>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 64.0.2 (64 bit)

**Additional context**
- Using WordPress 5.0.3
- This happens with and without Gutenberg (4.8.0) active

**Comment by youknowriad** [comment] 2019-01-18 16:11
Thanks for opening the issue.

I think this is expected behavior. The first class here indicates that there's a color applied, the second classes indicates which class is applied.

I'm closing this but let me know why you think this is problematic?

**Closed by youknowriad** 2019-01-18 16:11 UTC

**Comment by robincornett** [comment] 2019-10-14 15:08
I know this was closed long ago, but I've _finally_ realized why this was causing me issues, why it's expected behavior, and why it's still a bit problematic.
* if a colored background is applied to a block, the block receives two classes: `has-background` and `has-{$color}-background-color`.
* if a text color is selected for a block, the block receives two classes: `has-text-color` and `has-{$color}-color`.
The potential issue comes in if I define my own set of colors. If I have a color for my default site text which I want to add to the color set, I might define my colors like this:
```
$colors = array(
	array(
		'name'  => __( 'Text', 'my-theme' ),
		'slug'  => 'text',
		'color' => '#292c33',
	),
	array(
		'name'  => __( 'White', 'my-theme' ),
		'slug'  => 'white',
		'color' => '#fff',
	),
	array(
		'name'  => __( 'Light gray', 'my-theme' ),
		'slug'  => 'light-gray',
		'color' => '#ebecef',
	),
	array(
		'name'  => __( 'Medium gray', 'my-theme' ),
		'slug'  => 'medium-gray',
		'color' => '#999',
	),
	array(
		'name'  => __( 'Primary Accent', 'my-theme' ),
		'slug'  => 'theme-primary',
		'color' => '#1d5e8a',
	),
	array(
		'name'  => __( 'Secondary Accent', 'my-theme' ),
		'slug'  => 'theme-secondary',
		'color' => '#e0ac34',
	),
);
```
And then I would define my CSS classes accordingly, including the following:
```
.has-text-color {
    color: #292c33;
}

.has-text-background-color {
    background-color: #292c33;
}
```
At this point, I think you can see where I might run into trouble. My color slugs can never conflict with the general `has-background-color` class, which simply indicates that a block has a background color, but if I use `text` as a slug for my site's general text color--which doesn't seem like a completely unexpected scenario--it is very possible to run into issues with the generic `has-text-color` class always being present, even if another text color is set, if the classes are defined in a different order in the CSS.

At this point, I understand the purpose of the `has-text-color` class, and why it's always added, but because there is the potential for conflict with custom defined colors, I am commenting here to suggest that **the [block editor handbook](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes) should be updated to indicate that `text` should be considered a reserved slug** and not used to define colors in a custom palette (I'm thinking to use `default` instead).

**Comment by craigiswayne** [comment] 2023-07-26 10:33
I ran into a similar issue whereby the `.has-text-color` class was overriding the `.has-primary-color` class

This was expected behaviour because my theme.json had defined the palette in the incorrect order...

Incorrect Order
```json
{
  "settings": {
    "color": {
      "palette": [
        {
          "color": "#8486b9",
          "name": "Primary",
          "slug": "primary"
        },
        {
          "color": "#070707",
          "name": "Text",
          "slug": "text"
        }
      ]
    }
  }
}
```


Correct Order
```json 
{
  "settings": {
    "color": {
      "palette": [
        {
          "color": "#070707",
          "name": "Text",
          "slug": "text"
        },
        {
          "color": "#8486b9",
          "name": "Primary",
          "slug": "primary"
        }
      ]
    }
  }
}
```

The css generated in wordpress depends on the order of the variables defined in the palette in your theme.json

**Comment by cvladan** [comment] 2025-03-12 14:47
> The css generated in wordpress depends on the order of the variables defined in the palette in your theme.json

Wow! This is extremely important and not sure where it is mentioned in the documentation.
Thanks for the info!

**Comment by hchouhan** [comment] 2025-04-25 04:50
@craigiswayne Thank you so much. I have wasted so much time on this already.
