### ISSUE TITLE
Loss of width controls in widgets since WordPress 5.9

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#41418] opened 2022-05-28 16:18 UTC
### Description

With the release of WordPress 5.9, blocks would start having their `alignwide` and `alignfull` options stripped out, while they can be used within the block editor normally just fine.

This makes legacy themes harder to use with blocks, since it is not uncommon for themes to have widget areas defined to accommodate what (for example) the Footer template part editor within FSE would do for bleeding edge themes right now.

### Step-by-step reproduction instructions

Using a theme that supports wide/full width content;

In WordPress 5.8:
- Go to Widgets
- Add an image block
- Set alignment to "Wide"

In WordPress 5.9/6.0
- Go to Widgets
- Add an image block
- Set alignment and see that "Wide" is no longer available

### Environment info

- WordPress version 5.9.0 -> 6.0.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-08-05 09:30
I can confirm this.  It does not make a difference if I use a container block with the layout option.

If I activate Gutenberg, add a group block, toggle the layout setting to enable wide and full, and place an image block inside,
then the image still only has left, center and right alignment options.

**Comment by carolinan** [comment] 2022-08-05 09:37
There seems to be several duplicates of this. I will close this issue and discussions can continue in https://github.com/WordPress/gutenberg/issues/35468

**Closed as not planned by carolinan** 2022-08-05 09:37 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Widgets Screen
