### ISSUE TITLE
Gutenberg RTL Issues

### ISSUE THREAD

**Issue by nawras92** [WordPress/gutenberg#12876] opened 2018-12-14 14:19 UTC
Hello, 

I'm using Gutenberg editor with Wordpress 5.0, and some options don't work properly with RTL languages (Arabic, Hebrew...etc).

**I faced the following problems:**

1. **Cover Image**: The title isn't centered, and a part of the cover image got damaged and turned to black.
2. **Gallery**: Gallery is shown as list of images.
3. **Columns** : Columns are shown as rows rather than columns.
4. **pullquote:** It isn't centered as it is in the LTR version.
5. **Media & Text** : it's also shown as rows rather than two columns.

I have recorded a video explaining these issues (_it's a one minute video_):
https://youtu.be/ZGiqME3eYhw

Thanks!

**Comment by emads3** [comment] 2019-07-05 18:24
same issue here

**Comment by senadir** [comment] 2019-07-25 15:14
cannot reproduce, using vanilla install on arabic with the default theme
![rtl](https://user-images.githubusercontent.com/6165348/61886096-f6f5c300-aef6-11e9-8779-b12644884587.gif)

```
<!-- wp:cover {"url":"http://localhost:8888/wp-content/uploads/2019/07/image.png","id":64} -->
<div class="wp-block-cover has-background-dim" style="background-image:url(http://localhost:8888/wp-content/uploads/2019/07/image.png)"><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p style="text-align:center" class="has-large-font-size">Testing Titles</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:columns {"columns":5} -->
<div class="wp-block-columns has-5-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Testign 1</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Testing 2</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:gallery {"ids":[78,79,80,81,82]} -->
<ul class="wp-block-gallery columns-3 is-cropped"><li class="blocks-gallery-item"><figure><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.01.45-PM-1024x575.png" alt="" data-id="78" data-link="http://localhost:8888/?attachment_id=78" class="wp-image-78"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.02.34-PM-1024x684.png" alt="" data-id="79" data-link="http://localhost:8888/?attachment_id=79" class="wp-image-79"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.02.13-PM-1024x683.png" alt="" data-id="80" data-link="http://localhost:8888/?attachment_id=80" class="wp-image-80"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.02.01-PM.png" alt="" data-id="81" data-link="http://localhost:8888/?attachment_id=81" class="wp-image-81"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.01.52-PM.png" alt="" data-id="82" data-link="http://localhost:8888/?attachment_id=82" class="wp-image-82"/></figure></li></ul>
<!-- /wp:gallery -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>Testing the pull</p><cite>testing</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:media-text {"mediaId":79,"mediaType":"image"} -->
<div class="wp-block-media-text alignwide"><figure class="wp-block-media-text__media"><img src="http://localhost:8888/wp-content/uploads/2019/07/Screen-Shot-2019-07-25-at-4.02.34-PM-1024x684.png" alt="" class="wp-image-79"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">Media &amp; Text</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->
```

**Comment by youknowriad** [comment] 2019-08-19 17:27
Closing, let's reopen if we find ways to reproduce.

**Closed by youknowriad** 2019-08-19 17:27 UTC
Labels: Internationalization (i18n), Needs Testing, [Status] Needs More Info
