### ISSUE TITLE
Unexpected clicking behaviour

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#828] opened 2017-05-17 17:40 UTC
I was using Chrome desktop. I experienced some really weird clicking behaviour that saw me move around the pages and also feel like it wasn't that stable in expected behaviour.

Here is the video:

https://cldup.com/9-fEAxixln.mov

**Comment by karmatosed** [comment] 2017-05-17 18:54
I shook this about a bit to try and get steps, but I couldn't get exact ones. It seems to do with focus. Here is another video that is a little clearer.

https://cldup.com/TzeK7c2lLr.mp4

**Comment by jasmussen** [comment] 2017-05-18 07:46
Nice ticket, thanks for the report! I know there are a few other focus issues, (#567 and #480 #517 ), possibly related.

**Comment by mtias** [comment] 2017-05-18 18:01
Fairly sure this was caused by the Button block only, and should have been fixed in #811 (not on the plugin download).

Feel free to reopen if it still happens.

**Closed by mtias** 2017-05-18 18:01 UTC
Labels: [Type] Bug
