### ISSUE TITLE
Child theme issue: Duplicate Templates and Template Parts in Site Editor

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#53138] opened 2023-07-29 15:58 UTC
### Description

When a child theme is active and includes templates, there is a duplication issue in the Site Editor. Two instances of each template that exists in the child theme are present, with the parent template being loaded in the Site Editor (while the front end is properly using the child theme template).

### Step-by-step reproduction instructions

1. Create a child theme with templates and template parts.
2. Activate child theme and access the Site Editor > Templates (or Template Parts) screen.

For testing purposes, I am attaching a zip file with TT3 and a sample TT3 child theme.
[tt3-themes.zip](https://github.com/WordPress/gutenberg/files/12207513/tt3-themes.zip)

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/a595f8bf-837b-4f41-9bed-4b5e85e8b291

### Environment info

Problem DOES NOT exist with WP 6.2.2 and Gutenberg 16.3 active.
Problem DOES exist with WP 6.3 RC2 (with or without Gutenberg 16.3 active).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment] 2023-07-29 16:02
Similarly, Template Parts are also being duplicated:

https://github.com/WordPress/gutenberg/assets/486261/fce90d8a-9b33-4faa-bcb0-a8516b91c142

**Comment by ndiego** [comment] 2023-07-29 17:24
I have confirmed this issue and have added it to the 6.3 Board.

cc @tellthemachines @ramonjd

**Comment by ramonjd** [comment] 2023-07-31 01:53
@oandregal 

Could this change be related? https://github.com/WordPress/wordpress-develop/pull/4097/files#diff-1d8e05d3ea69557ca8742330e62c1893a72d4ca4ff2ed4ccc5b94bcf5d20fed7R324

**Comment by oandregal** [comment] 2023-07-31 09:32
@ramonjd just tested by reverting that commit and I cannot longer reproduce the issue. So it seems to be the root cause. I'm taking a look.

This is a change in core, those functions no longer live in Gutenberg. I presume this is why it was only reported now despite being merged since more than 3 months ago :disappointed: I reopened the original ticket https://core.trac.wordpress.org/ticket/57756#comment:26 in case you want to follow it. I'll also report here for redundancy.

**Comment by oandregal** [comment] 2023-07-31 14:51
Prepared a fix at https://github.com/WordPress/wordpress-develop/pull/4940

**Comment by bgardner** [comment] 2023-07-31 15:05
@oandregal Any chance that makes its way into RC3? IMO, this issue is a pretty big one, because it prevents ANY child theme's templates from being able to be edited via the Site Editor.

**Comment by tellthemachines** [comment] 2023-08-01 04:26
Closing as the fix has been committed to the release branch in https://core.trac.wordpress.org/changeset/56330. Thanks everyone!

**Closed as completed by tellthemachines** 2023-08-01 04:26 UTC
Labels: [Type] Bug, [Type] Regression, [Feature] Site Editor
