### ISSUE TITLE
BlockVerticalAlignmentToolbar on custom block causes console error

### ISSUE THREAD

**Issue by sarahannnicholson** [WordPress/gutenberg#15672] opened 2019-05-16 03:37 UTC
Wordpress version:  5.1.1
Gutenberg version: 5.7.0
React version: 16.8.6
react-dom version: 16.8.6

### My Setup
I am using [create guten block](https://github.com/ahmadawais/create-guten-block) to build my ES6 JS. 
I followed the code in [BlockVerticalAlignmentToolbar readme](https://github.com/WordPress/gutenberg/blob/39f568faf2e62c57736bb80d7088a996eb067944/packages/block-editor/src/components/block-vertical-alignment-toolbar/README.md), as well as following the code in the [column block](https://github.com/WordPress/gutenberg/tree/5494bc57fc77de6cada4295823a3fb047e168f89/packages/block-library/src/column).

### The Code
```
const { registerBlockType } = wp.blocks;
const { BlockControls, BlockVerticalAlignmentToolbar } = wp.editor;

registerBlockType("custom/test-block", {
	title: "Vertical Test",
	description: "Testing vertical aligment on my block",
	icon: "cover-image",
	category: "layout",
	//supports: {
		//align: ["full", "wide"],
		//verticalAlignment: ["top", "center", "bottom"]
	//},
	attributes: {
		verticalAlignment: {
			type: "string"
		}
	},

	edit({ attributes, setAttributes }) {
		const { verticalAlignment } = attributes;

		// Change handler to set Block `attributes`
		const onChange = alignment =>
			setAttributes({ verticalAlignment: alignment });

		return (
			<div>
				<BlockControls>
					<BlockVerticalAlignmentToolbar
						onChange={onChange}
						value={verticalAlignment}
					/>
				</BlockControls>
				<div>My Block</div>
			</div>
		);
	},

	save: () => {
		return <div>My Block</div>;
	}
});

The block is imported properly. I can select it from the layout category:
```
![image](https://user-images.githubusercontent.com/10520771/57824443-e59e7680-774f-11e9-9702-d2e5a76912da.png)

### The Problem
Once I select the block, I get the following screen: 
![image](https://user-images.githubusercontent.com/10520771/57824599-6bbabd00-7750-11e9-823a-09fb5fbed6fd.png)

and error in the console:
```
react-dom.min.fa9ca8c8.js:117 Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at pb (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:12:454)
    at n (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:13:221)
    at wc (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:61:140)
    at Ff (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:73:361)
    at u (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:76:145)
    at http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:80:149
    at N (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:90:3)
    at hi (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:106:194)
    at Qg (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:144:217)
    at Rg (http://localhost:8080/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:145:76)
```

No matter what I do, I cannot seem to get the vertical alignment toolbar to work with my simple block. Any suggestions would be greatly appreciated! :)

**Comment by talldan** [comment] 2019-05-16 08:20
Hi @sarahannnicholson,

That React error usually means one of the components you're using isn't imported properly (it's `undefined`.)

It looks like the issue is that `BlockVerticalAlignmentToolbar` is in the block editor (`wp.blockEditor`) package instead of the editor (`wp.editor`) package. Adjusting the second line in your code to reference the right package should fix things.

The history of this is that `blockEditor` is a fairly new package that largely supercedes 'editor'. Most of the components from `editor` were refactored over to it (but had to be kept defined in both `editor` and `blockEditor` for backwards compatibility). `BlockVerticalAlignmentToolbar` was introduced after that change though, so it's only in `blockEditor`. The right thing to do is to use `wp.blockEditor` for both `BlockControls` and  `BlockVerticalAlignmentToolbar`.

I'll close the issue, hope that solves the problem.

**Closed by talldan** 2019-05-16 08:20 UTC
Labels: [Type] Help Request

**Comment by sarahannnicholson** [comment] 2019-05-16 16:37
Hey @talldan that totally fixed it! Thanks a million ! :)
