### ISSUE TITLE
Text Blocks not working. TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by EneOli** [WordPress/gutenberg#8839] opened 2018-08-10 15:02 UTC
## Issue Overview

Using Gutenberg in  version 3.5.0 on a wordpress site causes the following error:
```


TypeError: Cannot read property 'init' of undefined
    at t.value (index.js?ver=1533912167:12)
    at t.value (index.js?ver=1533912167:12)
    at jc (react-dom.min.82e21c65.js:134)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at wg (react-dom.min.82e21c65.js:137)
    at Ze (react-dom.min.82e21c65.js:41)

bg @ react-dom.min.82e21c65.js:110

```

for each text block.
Neither disabling all plugins nor switching the theme resolves the issue.

## Steps to Reproduce (for bugs)

1.  Install Gutenberg plugin via dashboard notification
2.  Try to use it

Tested in Chrome and Firefox

## Expected Behavior

The plugin should work as expected and let me write my text.

## Current Behavior

When clicking on the block to edit it, the error appears.

## Screenshots / Video

![grafik](https://user-images.githubusercontent.com/23139864/43964758-d02a2744-9cbd-11e8-9f70-783fdb97043c.png)

**Comment by youknowriad** [comment] 2018-08-10 15:33
Do you use plesk? It looks like something is blocking the loading of the `wp-tinymce.php` script. 

I'm closing as this is a duplicate of #8690 

There's also a workaround here https://github.com/WordPress/gutenberg/issues/8791#issuecomment-411967237

**Closed by youknowriad** 2018-08-10 15:33 UTC
