### ISSUE TITLE
@wordpress/scripts@26.10.0 has deprecated NPM modules and unsupported node v.20.5.0

### ISSUE THREAD

**Issue by stein2nd** [WordPress/gutenberg#53553] opened 2023-08-11 03:53 UTC
### Description

When `ncu` was executed, `@wordpress/scripts` was displayed as `^26.9.0 → ^26.10.0`, so `ncu -u` `npm install` was executed in sequence.
As a result, several npm modules were shown as deprecated as follows:

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@39.9.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.36.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

This issue appears to be due to the same cause as [53213](https://github.com/WordPress/gutenberg/issues/53213) reported under 26.9.0.

### Step-by-step reproduction instructions

1. ncu
2. ncu -u
3. npm install

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/531628/47e3dba8-c771-4f41-8453-43254179e9d7)

![image](https://github.com/WordPress/gutenberg/assets/531628/ff75a149-0688-48ee-9379-8a078ebd4437)

![image](https://github.com/WordPress/gutenberg/assets/531628/b1fae12d-f778-4c03-9c87-36fc61a8b2d0)

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 531.77 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @wordpress/scripts: ^26.10.0 => 26.10.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment] 2023-08-14 11:42
I opened #53629 which tries to fix the issue with `eslint-plugin-jsdoc`.

**Comment by gziolo** [comment] 2023-08-14 12:04
I also opened https://github.com/WordPress/gutenberg/pull/53630 to see what's required to get rid of the deprecated `stable@0.1.8` deep dependency.

**Comment by gziolo** [comment] 2023-08-14 12:05
Actually, closing it as duplicate of https://github.com/WordPress/gutenberg/pull/53629.

**Closed as completed by gziolo** 2023-08-14 12:05 UTC
Labels: [Type] Bug, [Priority] High, [Tool] WP Scripts, [Status] Duplicate
