### ISSUE TITLE
Changing the Title doesn't actually change the Title

### ISSUE THREAD

**Issue by KPeregrinePgh** [WordPress/gutenberg#8898] opened 2018-08-12 10:36 UTC
While writing a blog article I sometimes change the title several times.  In Classic Editor I used to change it, save, preview and the new title was there.  In Gutenberg I get maybe one chance to make a new title stick. When I do it again Gutenberg ignores the change.  
Workaround: The only reliable way to change the title is by using Quick Edit in the list of posts.

Write a title for the blog post. Save and Preview. 
The first attempt will probably work.  
(don't close the Preview window. Mine opens in another tab.)
Try it over & over. Eventually Gutenberg won't display the title change.

**Editing using Desktop version**
 - Windows 10
 - Firefox Version 61.0.2 (64-bit)
 - Gutenberg version: 3.5.0

**Comment by designsimply** [comment] 2018-08-13 18:57
Welcome, and thank you for testing Gutenberg! 

I am closing this issue as a duplicate of #7927 and noting that re-tested and confirmed that this problem only happens when you click "Save Draft" before clicking "Preview" before an autosave happens. If you find something different, please let me know! ([3min](https://cloudup.com/cC6U6iNcGcS))

**Closed by designsimply** 2018-08-13 18:57 UTC
Labels: [Component] Saving, [Status] Duplicate, [Type] Bug

**Comment by SheElf** [comment] 2019-10-10 13:18
I'm a little frustrated. I'm unable to change the title of an article. It keeps reverting to my old title not matter how many times I change and save it. What can I do other than go back to the Classic editor?

**Comment by KPeregrinePgh** [comment] 2019-10-10 13:25
On Dashboards go to your list of posts (left panel selection) and choose Quick Edit on that post. Change the title and click update. If it's already published and you use permalinks, don't change the permalink (unless you want to confuse Google).

**Comment by SheElf** [comment] 2019-10-12 11:33
Yes, this seems to work, thank you very much for this helpful information.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/12/19,
05:32:56 AM

**Comment by JuanDBB** [comment] 2019-11-04 08:34
This is still happening with latest version under certain circunstances (I have not been able to reproduce it but it is happening to many clients of mine).
