### ISSUE TITLE
Reusable blocks do not honor width of inner blocks in editor.

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#47658] opened 2023-02-01 20:51 UTC
### Description

When adding a reusable block that contains full-width inner blocks the editor view remains narrow.  When converting from standalone to reusable the experience is a bit jarring.

The front-end displays properly, but the editor view discrepancy can confuse users.

This issue was brought to my attention by a theme developer @fatesallow during a conversation about the experience with developing themes for the block editor.

### Step-by-step reproduction instructions

1. Add a full-width group of blocks or patterns to the content editor.
2. Create a Reusable block from the outermost block
3. Observe the width shift to a narrower width as defined by the `.wp-block` selector

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1975950/216159758-d9e4475a-7991-4537-a190-5fc17b6d78b1.mp4

### Environment info

- Local Installation via LocalWP
- WordPress 6.1 with and without Gutenberg activated
- Twenty Twenty Theme Active
- Also tested with Twenty Twenty-Three Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-04-08 04:52
This issue is also discussed in #8288.

**Comment by talldan** [comment] 2023-04-28 06:07
Seems like a duplicate of https://github.com/WordPress/gutenberg/issues/8288, so I'll close it.

**Closed as not planned by talldan** 2023-04-28 06:07 UTC
Labels: [Type] Bug, [Feature] Synced Patterns
