### ISSUE TITLE
Pasting an image URL creates a (failed) Embed block instead of an Image block

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#18696] opened 2019-11-22 16:38 UTC
Pasting an image into the editor results in an Embed block that has failed to embed the image, rather than an Image block that successfully shows the image.

For example: https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg

I've tried w/ several others and gotten the same results, though.

The console says:

```
Received HTML:

 <meta charset='utf-8'><a href="https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg">https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg</a>
rich-text.min.js?ver=3.7.2:6 

Received plain text:

 https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg
blocks.min.js?ver=6.7.2:2 

Processed HTML piece:

 <p><a href="https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg">https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-1500x1346.jpg</a></p>
```

I'm copying the URLs straight from the address bar in Chrome. I've even pasted them into TextEdit to strip away any fancy stuff Chrome might be adding, and then copy/pasted that resulting raw string URL into the editor, but that still ends up with the failed Embed block.

I'm guessing this is a regression where something is causing the URL to be wrapped in HTML, rather than just passing the raw URL through, and that's why it's creating an Embed block in the first place?

**Comment by epiqueras** [comment] 2020-01-31 20:30
What browser are you using? I can't reproduce this on Chrome.

**Comment by karmatosed** [comment] 2020-03-16 21:37
I also can't replicate this, so for now going to close this. We can always reopen if this is still the case.

**Closed by karmatosed** 2020-03-16 21:37 UTC
Labels: [Feature] Raw Handling, [Status] Needs More Info, [Type] Bug, [Type] Regression
