### ISSUE TITLE
Toolbar formatting breaks RichText components in custom blocks

### ISSUE THREAD

**Issue by mikemcalister** [WordPress/gutenberg#8467] opened 2018-08-03 21:08 UTC
**Describe the bug**
I notice that the formatting toolbar is now available by default on `RichText` components (image below) on custom blocks. Previously, you needed to declare `inlineToolbar` support for the formatting bar. 

<img width="1000" alt="image 2018-08-03 at 1 30 51 pm" src="https://user-images.githubusercontent.com/1415737/43666736-b8bfcec0-973a-11e8-8e65-09025f67e34d.png">

When I use this new formatting bar on text, such as a link, I’m getting this error: `Objects are not valid as a React child`. On the core editor Slack channel, @aduth mentioned "I suspect it might be related to recent changes where the value of a RichText field is not a React element (it’s now a custom object shape) and any attempts to render it as one would log a message like what you see." This is happening in Gutenberg 3.4.0. 

This is the `RichText` component producing the error: 

```
<RichText
	tagName="h2"
	placeholder={ __( 'Add name' ) }
	keepPlaceholderOnFocus
	value={ profileName }
	className='ab-profile-name'
	style={ {
		color: profileTextColor
	} }
	onChange={ ( value ) => setAttributes( { profileName: value } ) }
/>
```

**To Reproduce**
1. Create a custom block and add a RichText field
2. Add text to the RichText field in the editor
3. Add a link, bold, or italic styling to the text
4. Save and reload the page

**Expected behavior**
The block should be rendered with the formatting or the formatting options shouldn't be shown unless declared.

**Comment by davidfcarr** [comment] 2018-08-04 14:54
I'm running into the same error. Screenshot here https://twitter.com/davidfcarr/status/1025756220869799936

**Comment by youknowriad** [comment] 2018-08-06 16:47
Hi there!

Can you share the full block settings object? that would help debugging this. 

Thanks

**Comment by mikemcalister** [comment] 2018-08-06 16:51
@youknowriad You can find a gist of the [index.js file here](https://gist.github.com/mikemcalister/95b330ee0962b04494e53925f19f405d).

**Comment by davidfcarr** [comment] 2018-08-06 23:02
@youknowriad mine was created with create guten block and had been working -- but apparently broke with a recent Gutenberg plugin update 

https://gist.github.com/davidfcarr/3fd65a3c28e97d864a8381d922019d72

**Comment by davidfcarr** [comment] 2018-08-06 23:04
showing two blocks, both of which were designed to collect the user's rich text info and add a little extra info / styling for an application where the documents are meeting agendas. The signup form text shows up on the meeting signup form but is hidden on the agenda (with CSS display:none tied to a class)

**Comment by youknowriad** [comment] 2018-08-07 07:46
Ok I got it, the issue is that you're trying to display `content` in your `edit` function. The thing is we were not expecting plugin authors to "display" the value of RichText elements outside of RichText elements in the `edit` function. It used to work incidentally in previous versions but was never meant to as is.

The workaround is you can replace:

`{ content }` in your edit functions with `<RichText.Content value={content} />` and this should do the trick. I also encourage you to always wrap the RichText values with `RichText.Content` in the save function too.

See https://wordpress.org/gutenberg/handbook/blocks/introducing-attributes-and-editable-fields/#attributes

I'm closing the issue for now, let's reopen if the original issue is not the same

**Closed by youknowriad** 2018-08-07 07:46 UTC
Labels: Extensibility, [Component] Rich Text, [Type] Bug

**Comment by mikemcalister** [comment] 2018-08-08 18:53
@youknowriad Could you elaborate on this a bit please? I'm not sure I follow. If you could link me to the line in [this gist](https://gist.github.com/mikemcalister/95b330ee0962b04494e53925f19f405d) that's causing the issue, that'd be a good start.

I've converted my `RichText` elements in the save function to `RichText.Content` but the original issue remains. 

If you want to see the issue live, you can download the [Atomic Blocks plugin](https://wordpress.org/plugins/atomic-blocks/), add the Author Profile block, and try to add formatting to the Name field.

**Comment by youknowriad** [comment] 2018-08-08 19:04
In this gist the error is different. You're using `profileTitle` as a value for the `RichText` component, which means it should be of type "array" and use the source "children" or you should use a type "string" with the source "html" (but in this case the RichText component should have `format="string"` prop). 

you have the same issue in multiple attributes.

**Comment by mikemcalister** [comment] 2018-08-08 19:49
@youknowriad Thanks so much! That fixed up my issue! 👍
