### ISSUE TITLE
BlockFormatControls fills have inconsistent placement when inserting new block

### ISSUE THREAD

**Issue by JustinSainton** [WordPress/gutenberg#27279] opened 2020-11-25 17:16 UTC
**Describe the bug**
Placement of filled components for `BlockFormatControls` are consistent **except** when inserting a new block. I would expect they would always be consistent.

**To reproduce**
1. Fill `BlockFormatControls`. I have a simple POC: https://gist.github.com/JustinSainton/63c725da82a553b15e3feeee68e964dc. 
2. Add blocks, note consistent placement in toolbar
3. Insert new block, note placement is different

**Expected behavior**
I'd expect consistent placement of Fill on new blocks.

**Screenshots**
See this video for a quick example: https://vimeo.com/483651149/d2b8142a80

**Editor version (please complete the following information):**
- WordPress version: 5.6-RC`
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Same experience with latest Gutenberg plugin (9.4.1) active or inactive.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS Big Sur
 - Browser [e.g. chrome, safari] All (Chrome, Safari, Firefox)
 - Version [e.g. 22] (Latest)

**Comment by Mamaduka** [comment] 2021-04-13 05:28
Hello, @JustinSainton

It looks like the issue was fixed via #29287.

I'm not able to reproduce it with Gutenberg 10.3, only with WP 5.7.

**Closed by Mamaduka** 2021-04-13 05:28 UTC
Labels: Needs Testing, [Feature] Extensibility
