### ISSUE TITLE
Selecting All Text With "CMD+A" or "CTRL+A"

### ISSUE THREAD

**Issue by themightymo** [WordPress/gutenberg#5125] opened 2018-02-18 14:57 UTC
## Issue Overview
I do a lot of "selecting all" text using CMD+A.  In Gutenberg, CMD+A selects text in the current block-only.  

In Medium, Word, Gmail, Notes, etc. CMD+A selects _all_ text.

Gutenberg has different behavior for CMD+A than what I'm used to and what I expect.

## Steps to Reproduce (for bugs)
1. Write 2 blocks of text
2. Press CMD+A (or CTRL+A on PC).

WP 4.9.4
Gutenberg 2.2.0

## Expected Behavior
CMD+A should select _all_ text like this Medium example:

## Current Behavior
CMD+A selects only the current block

## Screenshots / Video
<img width="1280" alt="cmd a" src="https://user-images.githubusercontent.com/179105/36353232-7e6728a6-1489-11e8-939d-73076027a05a.png">

**Comment by youknowriad** [comment] 2018-02-18 16:16
If no block is selected `Ctrl + A` selects all the blocks, we're planing to improve the current behavior to do a two step `Ctrl + A` when you're on a textual block. First `Ctrl + A` selects the first block, second one selects the whole content. cc @jasmussen @iseulde

**Comment by jasmussen** [comment] 2018-02-18 16:19
See also https://github.com/WordPress/gutenberg/issues/4369 which we are considering.

**Comment by youknowriad** [comment] 2018-02-18 16:36
I'm going to close this one as a duplicate of #4369 Ket's continue the discussion there.

**Closed by youknowriad** 2018-02-18 16:36 UTC

**Comment by themightymo** [comment] 2018-02-19 16:47
@youknowriad @jasmussen 
Brilliant!  Sorry for the duplicate - I searched but didn't find it yesterday.

Keep up the great work!  I'm loving Gutenberg!
