### ISSUE TITLE
After switching a block to html mode there is no way to switch back

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#21826] opened 2020-04-23 12:52 UTC
**Describe the bug**
Once you start editing a block as HTML mode the block toolbar does not appear anymore so you cannot switch back to visual.

**To reproduce**
1. Add a post
2. Add a quote block
3. Fill in some content
4. Use the block toolbar to click on the thee dots and then Edit as html
5. Deselect the block
6. Select the HTML block again
7. Notice the bug: no more block toolbar

**Expected behavior**
The block toolbar should appear.

**Screenshots**

![html-mode](https://user-images.githubusercontent.com/107534/80101603-4cd8c380-857a-11ea-9ef5-c745741de6b8.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.4
- "gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it? 7.9.1

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version latest

**Comment by talldan** [comment] 2020-05-04 02:21
Duplicate of https://github.com/WordPress/gutenberg/issues/21722

**Closed by talldan** 2020-05-04 02:21 UTC
Labels: [Feature] Blocks, [Feature] Writing Flow, [Type] Bug
