### ISSUE TITLE
Color Settings: Favorite or Most-Used Colors

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#13017] opened 2018-12-19 15:31 UTC
**Problem**
When setting text and background colors on a block, a common use case is to use the same color or set of colors for each block. 

For example, a company may have a specific color scheme they wish to stick to, and it would be useful to have their colors available in the color picker instead of needing to select it as a custom color each time (which gets tedious.) 

The theme sets the colors listed in the color settings, but perhaps this power should be given to the user via the interface.

**Potential Solution**
A solution would be to see the most-used colors populate in a paragraph block's color settings, or to have the option to set 'favorite' colors.
![image](https://user-images.githubusercontent.com/30727666/50229710-d2ef6380-03a2-11e9-96a1-acb93023c4fc.png)

**Alternatives**
Alternatives to use include:

1) using the duplicate block feature, so you can set the custom color on your first block and then duplicate that block to copy over the color settings.
2) there may be a plugin option for this. However, it would be nice to have favorite/most-used colors available in the block color settings without a plugin.

**Comment by talldan** [comment] 2020-02-19 02:48
Duplicate of #6941

**Closed by talldan** 2020-02-19 02:48 UTC
Labels: General Interface, [Status] Duplicate, [Type] Enhancement
