### ISSUE TITLE
Gutenberg issue with ACF Page Link or Page Object Field

### ISSUE THREAD

**Issue by abhisheksupple** [WordPress/gutenberg#9789] opened 2018-09-11 12:14 UTC
ACF Page Link or Page Object Field not display page/post drop down list.

**Comment by tofumatt** [comment] 2018-09-11 20:05
Could you please provide more information and steps to reproduce so we can understand this issue? Right now I don't understand what the bug is and if it's a Gutenberg or an Advanced Custom Fields plugin issue.

If you could attach any screenshots as well that'd be great.

**Comment by designsimply** [comment] 2018-10-02 21:16
Closing because there's not enough information. Please check to see if #10284 covers the same case since it has more detail. If the issue is not the same as #10284, please either reply with version numbers and steps to reproduce the problem or start a new issue with more information. Thanks!

**Closed by designsimply** 2018-10-02 21:16 UTC
Labels: [Status] Needs More Info, [Type] Plugin / Theme Interoperability
