### ISSUE TITLE
Page totally white after installing 6.1.0

### ISSUE THREAD

**Issue by locksoft** [WordPress/gutenberg#16517] opened 2019-07-10 17:04 UTC
I've just updated Gutenberg to last version and I can't modify any article anymore.
All I get is a blank page. I need to disable it completely to be able to keep working. :(

Please, fix it.

**Comment by quicoto** [comment] 2019-07-10 17:20
Duplicate of:

https://github.com/WordPress/gutenberg/issues/16515
https://github.com/WordPress/gutenberg/issues/16502

**Comment by aduth** [comment] 2019-07-10 17:33
Closing in favor of #16502 to simplify tracking. Thanks for the report.

**Comment by aduth** [comment] 2019-07-10 17:34
Duplicate of #16518

**Closed by aduth** 2019-07-10 17:34 UTC
