### ISSUE TITLE
Columns block spacing doesn't work with 'disable-layout-styles' option

### ISSUE THREAD

**Issue by BeholdPL** [WordPress/gutenberg#49782] opened 2023-04-12 23:39 UTC
### Description

While using add_theme_support( 'disable-layout-styles' ) option, **block spacing** doesn't applied for Columns block. 
<img width="1417" alt="Screenshot 2023-04-13 at 01 34 11" src="https://user-images.githubusercontent.com/34622592/231608494-cc62749e-b620-420b-a929-e329bb8032fc.png">
<img width="1421" alt="Screenshot 2023-04-13 at 01 34 46" src="https://user-images.githubusercontent.com/34622592/231608501-e80140fe-aea5-4029-a3d3-9042fc62fd40.png">

### Step-by-step reproduction instructions

1. Add `add_theme_support( 'disable-layout-styles' );` to functions.php
2. Add Columns block
3. Try to change Block Spacing

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment] 2023-04-17 01:09
Thanks for taking the time to submit an issue @BeholdPL 👍 

I believe this is actually intended behaviour. There were major changes to layout support in WordPress 6.1 and some of those changes impacted the [disabling of layout styles](https://make.wordpress.org/core/2022/10/10/updated-editor-layout-support-in-6-1-after-refactor/#:~:text=Themes%20can%20opt%2Din%20to,is%20handled%20explicitly%20in%20code.).

In the linked breakdown of layout changes, it notes the following:

> Note: Opting into this feature will remove required styles for blocks such as Group, Columns, Social icons and Buttons, so themes that use this feature will need to supply their own structural layout styles in order for these blocks to render correctly in the editor and on the site’s frontend.

The docs also flag that [disabling layout styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#disabling-base-layout-styles) will opt out of generated block layout styles for core blocks.

> Themes can opt out of generated block layout styles that provide default structural styles for core blocks including Group, Columns, Buttons, and Social Icons. By using the following code, these themes commit to providing their own structural styling, as using this feature will result in core blocks displaying incorrectly in both the editor and site frontend:

I believe part of the problem here is that block gap is displayed under dimensions/spacing but is in part dependent upon layout support. There are ongoing discussions and proposals towards merging the layout and dimensions panels to better group related controls.

- https://github.com/WordPress/gutenberg/issues/47902
- https://github.com/WordPress/gutenberg/issues/44560
- https://github.com/WordPress/gutenberg/issues/34698

I hope that helps!

/cc @tellthemachines and @andrewserong just to confirm

**Comment by andrewserong** [comment] 2023-04-17 01:22
Thanks for the ping!

> I believe this is actually intended behaviour. 

Yes, it's expected that core blocks that depend on the layout block support will fail when `disable-layout-styles` is in use, and that includes the block spacing. When using `disable-layout-styles`, you might also want to switch off any UI controls that are not applicable. `disable-layout-styles` was introduced primarily with classic themes, or themes that don't use the `appearanceTools` option in mind.

**Comment by ndiego** [comment] 2023-04-18 14:18
Since this is expected behavior, as detailed by the previous comments, I am going to close this issue out. Feel free to reopen as needed. Thanks!

**Closed as completed by ndiego** 2023-04-18 14:18 UTC
Labels: [Type] Bug, Needs Testing, [Block] Columns
