### ISSUE TITLE
Explore ways of showing where template parts and templates are currently in use

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38967] opened 2022-02-21 19:46 UTC
## What problem does this address?

In the latest [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2334), the following feedback came up: 

>I wonder if in FSE, if there would be an intuitive way to show when a part uses other parts from the selector screen. Some bit of text. “Header” This part is reused in _______. Or the opposite way! “Header Large” this template part uses the template part “Header”. On the “templates” page, you have no idea what template parts are used on each page. It’s not so bad when each page only uses a header and a footer, but I imagine in the future templates might include even more template parts. So when you see the Archive page in twenty-twenty two, you can’t tell till you get into it what parts it includes. It would be nice for the uninitiated into WordPress if there were more information here. Some of this information can be found in other places, and some it can’t

Tied to this, I've been hearing anecdotal and have personally experienced in building my own site confusion around editing one template part and then needing to go through every single template to ensure that template part is used. It would be nice to have an easy way to know where each template part is or isn't used in order to quickly make changes to the _right one_ and/or to know where updates need to be made. In my case, I ended up just opening every single template to ensure it was using the template part I wanted. 

The same is true with templates. When one is updating a template, it would help to be able to see, at a glance, where each is used in more detail rather than just relying on the description. This too came up in the same call for testing above:

>I really do not know which template affects which pages/posts. So I assume that a Page template affects all the pages.

## What is your proposed solution?

Need some major design thought here :) Some ideas in no particular order around where to show this:

- Multi entity saving (this feels a bit late).
- Site Editor > Template parts or Templates respectively.
- For template parts, perhaps in the isolated template part mode (perhaps in the block settings sidebar when selecting the entire template part since that's currently empty)

**Comment by annezazu** [comment] 2022-04-06 19:32
More feedback has come in as a result of the [thirteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/03/31/fse-program-testing-call-13-authoring-an-author-template/#comment-2394):

>Different headers use different menus. Depending on which header and menu I used. I do not know how to select to use another menu for the header template I selected to use.

Specifically, this is discussing the experience of adding a Header template part to a brand new blank template, using the "choose" option, and seeing the various template parts presented. When you are looking there, there's no indication of where else a template part is in use:

<img width="816" alt="Screen Shot 2022-04-06 at 12 31 55 PM" src="https://user-images.githubusercontent.com/26996883/162054269-a8ef62af-176d-49b3-a9ab-eb374377c10f.png">

Here's a video from @paaljoachim that starts at 1:47 showing this quickly for about a minute: https://youtu.be/ywpN_1VRrt4?t=107

**Comment by mtias** [comment] 2022-05-22 14:17
Closing as duplicate of #20476.

**Closed as completed by mtias** 2022-05-22 14:17 UTC
Labels: Needs Design, [Type] Feedback, [Block] Template Part, [Feature] Focus Mode
