### ISSUE TITLE
Prevent users from switching to the Code Editor

### ISSUE THREAD

**Issue by woorise** [WordPress/gutenberg#12871] opened 2018-12-14 12:05 UTC
Is there any way/filter to prevent users from switching to the Code Editor or completely remove the Editor section from "tools and options"?

![screenshot_2018-12-14 edit giveaway - demo](https://user-images.githubusercontent.com/22965450/50002559-27f93700-ffa9-11e8-8c84-bf9160583779.png)

**Comment by youknowriad** [comment] 2019-04-22 10:01
Thanks for the issue, this seems like a duplicate of #14647

**Closed by youknowriad** 2019-04-22 10:01 UTC
Labels: Code Editor, Needs Technical Feedback
