### ISSUE TITLE
Theme.json: Gradient / Solid Background (Gradient cannot be unset)

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#42645] opened 2022-07-22 19:26 UTC
### Description

I am designing a theme which sets the background with a gradient in theme.json, per the following:

```
"styles": {
	"color": {
		"gradient": "var(--wp--preset--gradient--primary-base)",
		"text": "var(--wp--preset--color--main)"
	}
}
```

This results in CSS that looks like:

```
body {
    background: var(--wp--preset--gradient--primary-base);
}
```

The problem, however, is that there does not seem to be a way to programmatically disable the gradient set by the theme. One can attempt to do so by selecting a solid color in Site Editor > Styles > Elements> Background, but that only adds to the CSS, as seen below:

```
body {
    background: var(--wp--preset--gradient--primary-base);
    background-color: var(--wp--preset--color--base);
}
```

Because background > background-color, the gradient continues to show on both the back / front end—which means solid colors can never be successfully selected.

### Step-by-step reproduction instructions

1. Set background in theme.json to gradient.
2. Go to Site Editor > Styles > Elements> Background and select a solid color.
3. Save and view front end.

### Screenshots, screen recording, code snippet

Theme sets background to gradient, user selects solid color, sees no change.

![image](https://user-images.githubusercontent.com/486261/180512254-0fb1db5d-bc98-493e-bc19-fb93a49fa810.png)

### Environment info

WordPress 6.0
Gutenberg active _or_ not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment] 2022-07-22 19:31
It seems that a toggle function should be in place here, similar to how colors (Solid/Gradient) work in the block editor.

**Comment by carolinan** [comment] 2022-07-22 22:51
This is a duplicate of #42105.

**Closed as not planned by carolinan** 2022-07-22 22:51 UTC
Labels: [Status] Duplicate
