### ISSUE TITLE
The focus ring of the editor buttons in the header is cut off in the widgets editor

### ISSUE THREAD

**Issue by dhruvang21** [WordPress/gutenberg#65393] opened 2024-09-17 09:06 UTC
I found that the focus ring of the editor buttons in the header is cut off in the widgets editor

<img width="405" alt="Screenshot 2024-09-16 at 19 24 45" src="https://github.com/user-attachments/assets/64bdd138-9412-494b-a108-f733aafe0fce">

_Originally posted by @draganescu in https://github.com/WordPress/gutenberg/pull/65367#pullrequestreview-2307145127_

**Comment by dhruvang21** [comment] 2024-09-17 09:24
This issue resolved by the following PR:- https://github.com/WordPress/gutenberg/pull/65395

**Comment by draganescu** [comment] 2024-09-24 12:08
@dhruvang21 a quick hint for the future: if the PR contains in the description closes #xxx or fixes #xxx where xxx is the id of the fixed issue, the issue is autoclosed when the PR is merged.

Thanks for the work!

**Closed as completed by draganescu** 2024-09-24 12:08 UTC
