### ISSUE TITLE
Classic widget inside columns causes invalid content error.

### ISSUE THREAD

**Issue by QuietNoise** [WordPress/gutenberg#16186] opened 2019-06-15 11:45 UTC
Classic widget inside columns and group containers causes ‘invalid content’ error. Also the error dialog box cannot be bypassed.
User has no way to get back to editing affected content. This does not affect Classic when placed on root of the Editor, only when in columns, group and possibly other containers.

1. Go to post / page edit screen.
2. Place a column or group component
3. Inside columns place a Classic widget.
4. Inside a Classic paste some content from word or internet (I though discovered that regular typing in editor won’t save you from this bug).
5. Save, publish go to view the page.
6. Return to edit screen.
7. Your columns containing Classic will be covered with “This block contains unexpected or invalid content.” 
8. On top of the error appearing, the user has no way to bypass it.  
- There are two options presented: Resolve and Convert to HTML. 
- Convert to HTML does nothing. Resolve opens Diff. 
- Selecting either  of the two options in Diff does nothing. 
- In the block contextual menu thera also two options: Convert to Classic Block and Attempt Block Recovery. None of them do anything.
- Sometimes Diff shows no differences and the error still happens.

**Expected behavior**
I expect steps 7 and 8 to not happen. And if step 7 must happen and user should have a working way to bypass it.

**Screenshots**
Screens attached.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome  75, Firefox, (also in incognito)
 - Version: 75
CMS experience. Not tested on mobile

I discovered it on G 5.9. Not sure if happened earlier. Tested on latest WP 5.2.1 and  G 5.9.2. Fresh install.

Edit: 
Just tested with Gutenberg plugin deactivated, with the built in Editor. Experience and bugs are  same. 

Some comments to screens.

Classic widget in columns is affected by the bug. While below classic editor rules like nothing happened.
![2019-06-15_13h42_55](https://user-images.githubusercontent.com/3076187/59551024-8791c880-8f73-11e9-8df7-c2497c56aaef.png)

Diff shows some differences from what was in editor to what it expects. None of the buttons below work.
![2019-06-15_13h43_43](https://user-images.githubusercontent.com/3076187/59551029-9c6e5c00-8f73-11e9-844d-eb99df6d14f1.png)

Here diff show that content is not modified. Though bug still appear.
![2019-06-15_13h44_17](https://user-images.githubusercontent.com/3076187/59551036-b90a9400-8f73-11e9-9f07-8cb0a948815d.png)

**Comment by talldan** [comment] 2019-06-17 02:47
Hi @QuietNoise, thanks for the really detailed bug report. I'll close this issue as it's a duplicate of #13187. That issue has been given a high priority. Thanks.

**Closed by talldan** 2019-06-17 02:47 UTC
Labels: [Block] Classic, [Block] Columns, [Status] Duplicate, [Type] Bug

**Comment by QuietNoise** [comment] 2019-06-17 08:46
Thanks. No idea how I didn't find.
