### ISSUE TITLE
Comma in slug?

### ISSUE THREAD

**Issue by eliorivero** [WordPress/gutenberg#16445] opened 2019-07-06 18:14 UTC
I don't _remember_ ever seeing this in WordPress pre-Gutenberg so I might as well be mistaken. However, shouldn't commas be stripped off the slug?

<img width="632" alt="Captura de Pantalla 2019-07-06 a la(s) 15 12 29" src="https://user-images.githubusercontent.com/1041600/60759775-b8a86a80-a000-11e9-8580-81f54948cddf.png">

**Comment by Soean** [comment] 2019-07-07 16:28
When the post is published, the comma is stripped out. So we should also strip it out in the editor preview.

**Comment by Soean** [comment] 2019-07-07 17:51
The function [cleanForSlug](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/utils/url.js#L41) is responsible for the url preview in the editor.

> Performs some basic cleanup of a string for use as a post slug. This replicates some of what santize_title() does in WordPress core, but is only designed to approximate what the slug will be.

**Comment by epiqueras** [comment] 2019-07-09 16:37
>When the post is published, the comma is stripped out.

Are you sure this is the case? I was just able to publish a post with a comma.

**Comment by donmhico** [comment] 2019-09-03 10:32
I'm not able to reproduce the bug.

WP - 5.3-alpha-45282-src
Gutenberg - f198997e2

**Comment by skorasaurus** [comment] 2020-01-14 14:49
I tested this Gutenberg, as of commit 5ca4a9bccb306191b1a8a44936108ca694141a7d (January 9th, 2020) and although the commas appeared in the post title when I saved the an initial draft, the commas were stripped from the permalink when I published the post.  

Perhaps we can clarify the title of this issue to be something like "comma appears in permalinks within the editor" ? 
A screenshot shows the multiple places within the editor that has the permalink.
![Selection_274](https://user-images.githubusercontent.com/955351/72353899-cbd47b00-36b2-11ea-825a-4b8f890e0225.png)

**Comment by Soean** [comment] 2020-04-16 06:32
I can't reproduce the issue anymore, fixed in #21007. 
Please reopen if the issue still exists in the current master.

**Closed by Soean** 2020-04-16 06:32 UTC
Labels: [Feature] Permalink, [Type] Bug
