### ISSUE TITLE
Navigating columns with arrow keys is not intuitive

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30660] opened 2021-04-09 11:38 UTC
## Description

The following was reported during user testing on April 9 2021.

"When navigating within a columns block, I expected that using the left/right arrow keys would allow me to switch between columns.
Instead, using these keys, focus is moved to the block inside the first column.

When a columns block is selected and you use the down arrow key, the first column is selected.
Press the down arrow key again, and the block inside that column is selected.
Press the down arrow key again, and the next block _after_ the columns block is selected.

Now, if you press the up arrow key, the focus is on the block inside column number two.
If you press the up arrow key again, the focus is on column number two
Press the up arrow key again, and the parent columns block is focused."

## Step-by-step reproduction instructions

Add a columns block and navigate with arrow keys as described above.

## Expected behaviour

Using left and right arrow keys should move focus between the (inner) columns.

When using the down or up arrow key, focus should move to the next column, and only move out of the columns block when you are at the last column.

## WordPress information
WordPress version: 5.7
Gutenberg version: trunk
Are all plugins except Gutenberg deactivated? yes
Are you using a default theme (e.g. Twenty Twenty-One)? TT1 blocks

## Device information
Device: Desktop
Operating system: Windows 10
Browser: Chrome Version 89.0.4389.114

**Comment by annezazu** [comment] 2021-04-28 19:24
More feedback related to this [here starting at 2:43](https://youtu.be/j3rajAseREU?t=163). Here's a re-recording for ease of use:

https://user-images.githubusercontent.com/26996883/116461075-0a009a00-a825-11eb-895a-abf421a9cbb7.mov

Very frustrating/nearly unusable experience.

**Comment by ellatrix** [comment] 2021-08-30 16:43
Duplicate of #30155?

**Comment by annezazu** [comment] 2021-08-30 16:51
I think it is since yours is a more umbrella issue for the behavior. Going to close this out to consolidate efforts :) cc @alexstine who asked about this recently. Please follow along on 30155!

**Closed as completed by annezazu** 2021-08-30 16:51 UTC
Labels: [Focus] Accessibility (a11y), Needs Accessibility Feedback, [Block] Columns
