### ISSUE TITLE
Post & Site Editor: Not loading on IE11

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#28249] opened 2021-01-15 19:22 UTC
## Description

When visiting the site editor in IE11, the editor displays a wsod. I didn't see any console warnings.

## Step-by-step reproduction instructions

- Select a block theme that enables site editing
- Visit site editor in IE11 browser

## Screenshots or screen recording (optional)

<img width="2004" alt="Screen Shot 2021-02-05 at 11 45 43 AM" src="https://user-images.githubusercontent.com/5414230/107081772-0f12f780-67a8-11eb-99e7-4f218fa274cc.png">

## WordPress information
- WordPress version: 5.7-alpha-49962
- Gutenberg version: Dev version up to commit 6accb5b
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No (Using TT1-blocks)

## Device information
- Device: Macbook Pro
- Operating system: macOS Big Sur 11.0.1
- Browser: IE11

**Comment by jeyip** [comment] 2021-01-30 00:17
I just tested it again. It looks like IE11 is loading the full site editor properly again.

**Comment by jeyip** [comment] 2021-02-05 19:53
Reopened the ticket because the wsod is back 😞

**Comment by paaljoachim** [comment] 2021-02-21 11:35
Microsoft has ended all support of IE 11. Should we close this issue?

**Comment by aristath** [comment] 2021-02-22 10:10
IE11 usage dropped to < 1%, so I wouldn't be surprised if we stop supporting it pretty soon. That was the threshold we always had for browser supports... 
FSE also relies heavily on CSS-Variables and other features that IE11 doesn't support so it's safe to assume that IE is not on the top of anyone's priorities list.

**Comment by diegohaz** [comment] 2021-02-24 20:32
I see these errors on the console:

```
SCRIPT5009: 'Proxy' is undefined
index.js (27557,5)
SCRIPT5007: Unable to get property 'withFilters' of undefined or null reference
index.js (9650,30)
SCRIPT5007: Unable to get property 'withFocusReturn' of undefined or null reference
index.js (3990,30)
SCRIPT5007: Unable to get property 'withNotices' of undefined or null reference
index.js (17200,30)
SCRIPT5007: Unable to get property 'createSlotFill' of undefined or null reference
index.js (2962,1)
SCRIPT5007: Unable to get property 'withSpokenMessages' of undefined or null reference
index.js (1207,30)
SCRIPT5007: Unable to get property 'initializeEditor' of undefined or null reference
post-new.php (2508,4)
SCRIPT7002: XMLHttpRequest: Network Error 0x2ee7, Could not complete the operation due to error 00002ee7.
post-new.php
```

Looks like the first one (`SCRIPT5009: 'Proxy' is undefined`) is related to the Framer Motion dependency. Not sure if it supports IE11.

**Comment by paaljoachim** [comment] 2021-02-24 21:02
It looks like we are getting very near to just closing this issue. As a wont fix.
Let me know and I will close it.

**Comment by jeyip** [comment] 2021-02-25 00:16
This definitely isn't the highest on the priority list for the full site editing project, but IE11 is still technically listed as a browser supported by both [Gutenberg](https://developer.wordpress.org/block-editor/handbook/faq/#what-browsers-does-gutenberg-support) and [WordPress](https://make.wordpress.org/core/handbook/best-practices/browser-support/). I also think there's value in keeping this open so others don't post duplicate issues.

With all that being said, if I'm not mistaken, there's already discussion about dropping support for IE11 in the broader WordPress community. I'd personally prefer to close this when dropping support is finalized, but if others feel strongly about this, it's not something I'll oppose strongly.

**Comment by annezazu** [comment] 2021-02-26 16:45
Just chiming in here to say that, after this [last week's core editor meeting](https://make.wordpress.org/core/2021/02/24/editor-chat-summary-24-february-2021/), a group of us are working on a post to propose dropping IE11 support. I'd hold off until that discussion has been had and a decision is reached in time by project leadership.

**Comment by ryelle** [comment] 2021-03-01 18:00
It looks like this affects all editors - the post editor is also white-screening for me on WP trunk, with the same errors from https://github.com/WordPress/gutenberg/issues/28249#issuecomment-785356297

**Comment by youknowriad** [comment] 2021-03-01 18:06
I agree here, if this is affecting the post editor we need to fix this for WP 5.7 (which is very soon 😬 )

**Comment by noisysocks** [comment] 2021-03-02 05:18
I dug into this a little bit. The error comes from `framer-motion` using `Proxy` which is an ES6 API that we do not polyfill. `framer-motion` is included by `@wp-g2` which we use in a few `@wordpress/components`.

We do not use `@wp-g2` in Core, however, which sets `process.env.COMPONENT_SYSTEM_PHASE` to `0`. In Core, this dependency tree is omitted from the generated bundle so long as `'mode'` in webpack is set to `'production'`.

I confirmed this locally by navigating to Posts → Add New in an IE 11 virtual machine.

- Running 5.7 branch with no Gutenberg, assets built using `grunt build`: No error
- Running 5.7 branch with no Gutenberg, assets built using `grunt build --dev`: Error
- Running 5.6 branch with Gutenberg `trunk`, assets built using `grunt build` and `npm run build`: Error
- Running 5.6 branch with Gutenberg `trunk`, assets built using `grunt build` and `npm run dev`: Error

Users using WordPress 5.7 without the Gutenberg plugin activated still be able to create and edit posts in IE 11. I'm therefore removing this issue from the Must Haves board.

Users using any version of WordPress with the Gutenberg plugin activated are not able to create and edit posts in IE 11. I'm therefore leaving the issue open.

**Comment by gziolo** [comment] 2021-03-02 07:18
@ItsJonQ and @sarayourfriend, can you investigate what's required to convenience IE11 to work with G2 components?

**Comment by ItsJonQ** [comment] 2021-03-02 15:55
@gziolo Will do! Thank you all for the notes!

**Comment by youknowriad** [comment] 2021-04-23 14:25
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.

**Closed by youknowriad** 2021-04-23 14:25 UTC
Labels: Browser Issues, [Type] Bug
