### ISSUE TITLE
.wp-block-table shouldn't have display: block;

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8796] opened 2018-08-09 21:00 UTC
`.wp-block-table` shouldn't have `display: block;` in /gutenberg/build/core-blocks/theme.css

Otherwise I would have to write in my style.css `table { display: table; }`.

Whatever this is trying to accomplish I think you need to use some other way to do that as this is counter-intuitive.

**Comment by jasmussen** [comment] 2018-08-10 06:54
This is intentional, insofar as this allows the table block to be born with some basic responsive measures. By being `block`, it can scale to the width of the parent element, and apply a horizontal scrollbar on smaller breakpoints. Additionally it helps enable a fixed table cell width as an option:

<img width="274" alt="screen shot 2018-08-10 at 08 50 21" src="https://user-images.githubusercontent.com/1204802/43943118-a7d7be16-9c7a-11e8-87a7-e348fffab29a.png">

Though note there's a regression with that particular aspect, see https://github.com/WordPress/gutenberg/pull/7899#issuecomment-411732824

Note also that theme.scss is an "opinionated visual style", in that it requires you as a themer to opt in to receiving that style. If you make no change in your functions.php to opt into Gutenberg opinionated styles, the theme style will not be loaded for the theme. See https://github.com/WordPress/gutenberg/issues/5360.

@earnjam since you recently mad a pull request to address a related issue, can you think of a way to keep the table `table` yet keep the responsive and optional fixed cell behaviors?

**Comment by manake** [comment] 2018-08-10 08:50
Thank you for detailed explanation.

Based on what you wrote I'm going to refrain from commenting in this ticket further (as for me it can be closed) and I'm going to:

- Not touch /gutenberg/build/core-blocks/theme.css styles.
- Create `.wp-block-my-custom-version-of-table` class for alternative styling with regular `display: table;` which I'll be assigning to the tables that I need to have `display: table;`.

**Comment by jasmussen** [comment] 2018-08-10 09:11
That sounds like a good approach! 

Closing for now but we can always reopen if there are issues with the opinionated style. Thanks!

**Closed by jasmussen** 2018-08-10 09:11 UTC
Labels: [Type] Question
