### ISSUE TITLE
Pasting text adds a single space before and after the content

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#17480] opened 2019-09-19 12:06 UTC
**Describe the bug**
If you copy’n’paste text, the text will be surrounded by a single space.

**To reproduce**
1. Mark text manually by dragging the cursor.
1. Copy text from anywhere outside the editor.
2. Create a new paragraph block.
3. Press `CTRL + V`.

It doesn’t occur if you select text with a triple click.

**Expected behavior**
The text is inside the paragraph block as is.

**Screenshots**
![gutenberg-spaces](https://user-images.githubusercontent.com/1018979/65242544-9219ac00-dae6-11e9-9d18-88f3d99b1c95.png)

The block on top of the selected block shows how it should be, the active block, how it actually displays the text.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Google Chrome
 - Version 76.0.3809.132

**Comment by Computino** [comment] 2019-09-21 14:45
Hi @KittMedia 

I noticed the same problem and it's very annoying. I am on Windows 10 and it happens both with Firefox and Chrome.

I "**solved**" the problem by pasting using `CTRL + SHIFT + V` instead of `CTRL + V`

This is not a solution, of course, but I hope it helps you.

**Comment by jalefkowit** [comment] 2019-10-22 19:04
I have the same problem when pasting text (on Ubuntu 19.04 + Firefox). I mostly paste text that I copy from LibreOffice Writer, so I've been wondering if it was something specific about copy/paste from LibreOffice that was causing the issue. Sounds like it may be a more generic thing. It is incredibly tedious to have to manually remove all the spaces from each individual pasted block by hand.

@Computino's `Ctrl+Shift+V` solution works in the sense that it doesn't result in the extra spaces being added, but it also means that things like formatting, hyperlinks, etc. in the original copied text get discarded. So instead of having to go manually tweak each block to remove extra spaces, I have to go manually tweak each block to add all its formatting back in. In most cases this is more work than removing the spaces would have been.

**Comment by ellatrix** [comment] 2019-12-12 13:19
This should be fixed with #19043, and will be in Gutenberg 7.2. The issues is also a duplicate of #19043.

**Closed** 2019-12-12 13:19 UTC
Labels: Needs Testing, [Feature] Raw Handling
