### ISSUE TITLE
Embed video into column - text overlap

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12283] opened 2018-11-25 09:19 UTC
**Describe the bug**
Adding video into column. Text for the 2nd area of the column overlaps the video.

![screen shot 2018-11-25 at 10 16 55](https://user-images.githubusercontent.com/5323259/48977483-55824d00-f09b-11e8-9fb1-5c7cc4821252.png)

**To Reproduce**
1. Add a column block. Select 2 cells/areas.
2. Add a video into the left cell.
3. Notice the text overlap.

**Expected behavior**
That the text would not overlap.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.6
 - Browser Chrome and Desktop Server
 - Gutenberg Version 4.5.1

**Comment by designsimply** [comment] 2018-11-27 02:34
Tested and confirmed that adding a video embed such as YouTube doesn't fit into a 2 column block and explodes outside of the block container area. Tested with WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6. ([screenshot](https://user-images.githubusercontent.com/1119271/49054553-d92e5d80-f1b1-11e8-9b35-e992c6d7f8f7.png))

Note: I also tested with WordPress 4.9.8 and Gutenberg `c33e91785` (>4.5.1) and found the same result. ([screenshot](https://user-images.githubusercontent.com/1119271/49054652-30ccc900-f1b2-11e8-9641-7d15dc3fbf25.png))

**Comment by iandunn** [comment] 2019-06-03 23:10
This also happens with Image & Gallery blocks:

![Screen Shot 2019-06-03 at 4 08 57 PM](https://user-images.githubusercontent.com/484068/58840307-fdb03a00-8619-11e9-8806-9a6a7242a6c2.png)

That's a 3-column block; the first two columns have Images and the 3rd has a Gallery.

**Comment by eshannon3** [comment] 2019-07-24 14:15
I'm having the same problem. Seems like some CSS limiting the width of images and videos inside columns in the editor would go a long way toward improving the editing experience for the column block. On the front end they look fine.

**Comment by paaljoachim** [comment] 2019-08-19 17:29
I was about to create a new issue for this when I discovered that I had already earlier created one...
Some additional screenshots.

![Screen Shot 2019-08-19 at 19 28 59](https://user-images.githubusercontent.com/5323259/63286158-a2f0bb00-c2b7-11e9-9f5a-1cff7584033e.png)

Frontend:
![Screen Shot 2019-08-19 at 19 29 40](https://user-images.githubusercontent.com/5323259/63286178-b56af480-c2b7-11e9-8d9b-67a050366584.png)

**Comment by paaljoachim** [comment] 2019-08-19 23:45
Here is a suggestion on how to fix this.
In the right sidebar have a drop down that selects the size of the embed.

https://support.google.com/youtube/answer/6375112?co=GENIE.Platform%3DDesktop&hl=en
For the default 16:9 aspect ratio, encode at these resolutions:

2160p: 3840x2160.
1440p: 2560x1440.
1080p: 1920x1080.
720p: 1280x720.
480p: 854x480.
360p: 640x360.
240p: 426x240.

**Comment by mapk** [comment] 2019-08-23 21:07
@draganescu let me know if this is a bug that can be resolved without design, or if you need some design help.

**Comment by paaljoachim** [comment] 2020-03-18 10:30
This is still a problem in Gutenberg 7.7.1.

![Screen Shot 2020-03-18 at 11 28 43](https://user-images.githubusercontent.com/5323259/76951269-b0345d80-690b-11ea-88a5-3a57a9f11b08.png)

Video embed overlaps column boundaries on the backend.

**Comment by paaljoachim** [comment] 2020-03-18 19:38
Is this something that Andrei @draganescu and/or Andrew @aduth could take a closer look at?
Is there a way to block content from bleeding out of the column they are placed into?

**Comment by draganescu** [comment] 2020-03-20 07:15
@mapk what is a good default here? clip the content in a column or attempt to resize the width?

**Comment by paaljoachim** [comment] 2020-03-20 11:57
Hey Andrei.

Here is an example of hiding the left and right sidebars. I am resizing the window. It would be natural to resize the video in relation to the space of the column it is placed into. 

![Resize-columns-containing-video](https://user-images.githubusercontent.com/5323259/77161581-561dce80-6aaa-11ea-9a7c-7f0833d698b8.gif)

**Comment by jasmussen** [comment] 2020-03-30 09:42
The problem is the following CSS:

```
.wp-block-embed {
    min-width: 360px;
}
```

That needs a lower min-width, and it should fix this issue. CC: @draganescu

**Comment by mapk** [comment] 2020-04-14 02:43
Thanks for pinpointing the problem, @jasmussen!

**Comment by jasmussen** [comment] 2020-04-14 06:22
By the way, I'm almost completely certain that we added this min-width CSS to embed blocks because a number of them aren't responsive. For example, embed an Amazon book and it won't work below something around that number.

However, such min-widths should arguably be applied on a per-embed basis, rather than in a blanket way like this, so this is something we should let individual tickets be created for, and proceed with removing that min-width as noted!

**Comment by draganescu** [comment] 2020-04-14 08:39
I added a small PR that appear to fix this but not sure if something else breaks instead. @jasmussen

**Closed** 2020-04-15 14:13 UTC
Labels: [Block] Columns, [Block] Video, [Status] In Progress, [Type] Bug

**Comment by paaljoachim** [comment] 2020-04-15 14:48
We will find out Andrei! Thanks for fixing it..:)
