### ISSUE TITLE
Expose method to get current active style

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#14336] opened 2019-03-08 09:20 UTC
**Is your feature request related to a problem? Please describe.**

Consider plugin author wanting to show or disable different block sidebar settings depending on active style.

`wp-editor`'s `blockStyles` component has `getActiveStyle` method but it isn't exposed to be used outside the package:

https://github.com/WordPress/gutenberg/blob/cb809b98654151416646c56f5de42c93ce656315/packages/editor/src/components/block-styles/index.js#L22-L44

**Describe the solution you'd like**
Please export utils to modify styles; get lists, get active state, change styles so that plugin authors can build more complex sidebar settings around these features.

**Describe alternatives you've considered**
It's obviously already possible to use these methods by just copying them directly to block code. _Boo code duplication._

**Comment by youknowriad** [comment] 2019-03-08 09:23
I agree this should be done, I think we could expose the active style directly in a special prop in the edit/save functions. I think there might be an existing issue about this?

**Comment by simison** [comment] 2019-03-08 09:28
I like that even better. :-)

I'm trying to imagine if there are a situations where plugin author would want to use a setter method?

Perhaps activate different style by default when inserting the block, perhaps by picking the style from previously inserted child block inside the parent block? Or hide some styles by changing some setting at the sidebar?

**Comment by youknowriad** [comment] 2019-03-08 09:29
Actually, this is a duplicate of #13506, so let's discuss there instead.

**Closed by youknowriad** 2019-03-08 09:29 UTC
Labels: [API] Style Variations, [Type] Enhancement
