### ISSUE TITLE
RaneControl block triggers onChange event during mouseMove event when focused in safari

### ISSUE THREAD

**Issue by snovosel** [WordPress/gutenberg#34965] opened 2021-09-20 17:03 UTC
### Description

When working in safari browser (desktop), clicking the arrows within the RangeControl component will correctly trigger  an onChange event, however subsequent mouseMove events above said RangeControl arrow elements will continue to trigger onChange events. 

It looks like the RangeControl component ultimate renders an input of type number. I've looked and it doesn't seem that this is default behavior on Safari.

### Step-by-step reproduction instructions

1. Add any block that either uses a RangeControl component within its edit function or implements the component within the block's settings inspector. In my testing I've used the `core/spacer` block . 

2. In Safari, manipulate the `Height in Pixels` within the Block tab in the settings panel by clicking the arrows to the right of the number within the input.

3. Observe the attributes are updated successfully

4. Move the mouse up and down while remaining in the dimensions of the two arrows.

5. Observe the attributes are continued to change without clicking anything.

### Environment info

- Safari , Wordpress 5.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stokesman** [comment] 2021-09-21 01:01
Thanks for reporting this @snovosel. It seems like a duplicate of #32497 so I'll close it as such but do let me know if you think this is a separate issue.

**Closed as completed by stokesman** 2021-09-21 01:01 UTC
Labels: [Feature] UI Components, Needs Testing, [Status] Duplicate, [Package] Components
