### ISSUE TITLE
Error message when marking several blocks one below the other (WordPress 5.6-RC1-49690)

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#27278] opened 2020-11-25 16:58 UTC
Hi,
If I mark several blocks one below the other by moving down with the mouse, the following error message appears:
An unexpected error has occurred in the editor: 
An empty reusable block is not available.

However, this is a local development environment on Laragon. On another development environment that is not local, I could not reproduce the problem.

TypeError: r is not a function
    at http://twenty-twenty.test/wp-includes/js/dist/components.min.js?ver=7b2eb7033cd3c6d2b4ea663e7d4774a7:7:311452
    at Bh (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126:456)
    at Dj (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:476)
    at unstable_runWithPriority (http://twenty-twenty.test/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
    at xb (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:231)
    at mk.Events.current (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236:102)
    at Ei (http://twenty-twenty.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41:59)

`
### wp-core ###

version: 5.6-RC1-49690
site_language: de_DE
user_language: de_DE
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: D:\laragon\www\twenty-twenty
wordpress_size: 240,83 MB (252527536 bytes)
uploads_path: D:\laragon\www\twenty-twenty/wp-content/uploads
uploads_size: 54,53 MB (57181938 bytes)
themes_path: D:\laragon\www\twenty-twenty/wp-content/themes
themes_size: 61,44 MB (64423955 bytes)
plugins_path: D:\laragon\www\twenty-twenty/wp-content/plugins
plugins_size: 34,40 MB (36068129 bytes)
database_size: 26,38 MB (27656192 bytes)
total_size: 417,57 MB (437857750 bytes)

### wp-active-theme ###

name: Twenty Twenty Child-Theme Master (twenty-twenty-childtheme-master)
version: 1.0 (2020-04-08)
author: Hans-Gerd Gerhards
author_website: https://haurand.com/
parent_theme: Twenty Twenty (twentytwenty)
theme_features: core-block-patterns, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: D:\laragon\www\twenty-twenty/wp-content/themes/twenty-twenty-childtheme-master

### wp-parent-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.5
author: the WordPress team
author_website: https://de.wordpress.org/
theme_path: D:\laragon\www\twenty-twenty/wp-content/themes/twentytwenty

### wp-themes-inactive (14) ###

customizr-pro-child: version: 12.2018, author: Hans-Gerd Gerhards
Customizr Pro: version: 2.1.36, author: Press Customizr
OceanWP: version: 2.0.0, author: Nick
Twenty Eleven: version: 3.5, author: WordPress-Team
Twenty Fifteen: version: 2.7, author: WordPress-Team
Twenty Fourteen: version: 2.9, author: WordPress-Team
Twenty Nineteen: version: 1.7, author: WordPress-Team
Twenty Seventeen: version: 2.4, author: WordPress-Team
Twenty Sixteen: version: 2.2, author: WordPress-Team
Twenty Ten: version: 3.1, author: WordPress-Team
Twenty Thirteen: version: 3.1, author: WordPress-Team
Twenty Twelve: version: 3.2, author: WordPress-Team
Twenty Twenty Child-Theme: version: 1.0 (2020-04-08), author: Hans-Gerd Gerhards
Twenty Twenty-One: version: 1.0.0, author: the WordPress team

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.7.0

### wp-plugins-active (7) ###

All-in-One WP Migration: version: 7.31, author: ServMask
Block Pattern Builder: version: 1.1.0, author: Justin Tadlock
Contact Form 7: version: 5.3, author: Takayuki Miyoshi
Health Check & Troubleshooting: version: 1.4.5, author: The WordPress.org community
Simple Lightbox: version: 2.8.1, author: Archetyped
WordPress Beta Tester: version: 3.0.7, author: Peter Westwood, Andy Fragen
WordPress Importer: version: 0.7, author: wordpressdotorg

### wp-plugins-inactive (7) ###

Add infos to the events calendar: version: 1.4, author: Hans-Gerd Gerhards (haurand.com)
Akismet Anti-Spam: version: 4.1.7, author: Automattic
Code Snippets: version: 2.14.0, author: Code Snippets Pro
Custom Haurand Block Styles: version: 1.4, author: Hans-Gerd Gerhards
Leaflet Map: version: 2.22.1, author: bozdoz
The Events Calendar: version: 5.2.1.1, author: Modern Tribe, Inc.
WP-Optimize - Clean, Compress, Cache: version: 3.1.4, author: David Anderson, Ruhani Rabin, Team Updraft

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Nicht verfügbar
imagemagick_version: Nicht verfügbar
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.35 (Win64) OpenSSL/1.1.1g PHP/7.4.8
php_version: 7.4.8 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_size: 2G
php_post_max_size: 2G
curl_version: 7.70.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: false
server-headers: 
	date: Wed, 25 Nov 2020 16:55:47 GMT
	server: Apache/2.4.35 (Win64) OpenSSL/1.1.1g PHP/7.4.8
	x-powered-by: PHP/7.4.8
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	link: Array
	content-type: text/html; charset=UTF-8
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.24
client_version: mysqlnd 7.4.8

### wp-constants ###

WP_HOME: http://twenty-twenty.test
WP_SITEURL: http://twenty-twenty.test
WP_CONTENT_DIR: D:\laragon\www\twenty-twenty/wp-content
WP_PLUGIN_DIR: D:\laragon\www\twenty-twenty/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

Best regards,
Hans-Gerd

**Comment by talldan** [comment] 2020-11-26 05:14
Thanks for reaching out @hagege. This looks like the same error message as reported here #27246, though the reproduction steps seem completely different, which is curious. It would be good to establish if it's the same bug. Are you using the time format mentioned in that issue?

**Comment by hagege** [comment] 2020-11-26 06:22
Thanks for the quick feedback. I tested it again several times today, but could not reproduce the issue. Even if I switch to English in settings and set the time format as in the problem mentioned, everything works fine. Very strange - I will keep watching this. Yesterday I got the issue several times and could reproduce it.
![timezone_time_date_format](https://user-images.githubusercontent.com/27292550/100314950-0cca3b00-2fb8-11eb-9609-d4f29ed614e6.jpg)

**Comment by talldan** [comment] 2020-11-27 04:31
The fix for the linked issue has been committed to the plugin and will be backported to 5.6 for the next RC (https://github.com/WordPress/gutenberg/pull/27316).

Let's keep monitoring and if it doesn't reoccur we can close this.

**Comment by hagege** [comment] 2020-11-27 05:53
thanks for info.

**Comment by talldan** [comment] 2020-12-04 09:54
I haven't seen any other reports, so I'll close this, but let us know if it reoccurs and it can be reopened.

**Closed by talldan** 2020-12-04 09:54 UTC
Labels: [Status] Needs More Info
