### ISSUE TITLE
Are Terms saved after wp_insert_post-Hook with Gutenberg?

### ISSUE THREAD

**Issue by carstenwawer** [WordPress/gutenberg#3898] opened 2017-12-10 14:39 UTC
## Issue Overview

Hi,

we are managing a Wordpress-Multisite-Network, thats publishes new and updated Posts into an external API. We are using the wp_insert_post-Hook to get all the data and publish it to the API.

With the classic Editor, when wp_insert_post is called, all Term-Data is saved and a call of wp_get_post_terms gets me the data.

With the current Gutenberg on the Beta-Wordpress-Nightly-Build, this Behaviour seems to have changed. When the wp_insert_post is called the Term-Data is not available, but if you save the post again, it is.

I suspect the that the saving of Terms moved to a later Point in Gutenberg. Is that right?

So my questions are:

Is this expected behaviour?
Is there a way to hook into the end of gutenberg-save-process when all Data is saved?

**Comment by pento** [comment] 2017-12-11 03:29
Thank you for the issue, @carstenwawer! This is caused by the REST API updating posts slightly differently to how the current post editor updates them.

Unfortunately, there currently isn't an action triggered after all post data has been saved via the REST API, I've opened a [Core ticket](https://core.trac.wordpress.org/ticket/42864) to get one added in.

**Comment by danielbachhuber** [comment] 2018-05-21 22:17
Closing in favor of the Core ticket, which is filed against `WordPress 5.0`. No action needed within Gutenberg.

**Closed by danielbachhuber** 2018-05-21 22:17 UTC
Labels: Core REST API Task
