### ISSUE TITLE
Update message overlaps permalink area

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#8612] opened 2018-08-06 17:44 UTC
Update message area overlaps the title permalink area.

![screen shot 2018-08-06 at 19 43 04](https://user-images.githubusercontent.com/5323259/43732140-0cce174c-99b1-11e8-9047-254c53f320fa.png)

**Comment by youknowriad** [comment] 2018-08-06 17:45
duplicate of #7276

**Closed by youknowriad** 2018-08-06 17:45 UTC
