### ISSUE TITLE
Keyboard disabled after turning paragraph into list

### ISSUE THREAD

**Issue by jamiebergen** [WordPress/gutenberg#2558] opened 2017-08-27 22:18 UTC
## Issue Overview
If I start an ordered list by typing "1. " into a paragraph block, it will automatically indent the number and convert the block into a list, but I can't enter additional text until I click back into the block - even though the blinking cursor is visible after the number.

## Steps to Reproduce (for bugs)
1. Open a post using the Gutenberg editor.
2. Click the "+" Insert block icon.
3. Select the Paragraph block.
4. Type "1. " (note the space after the dot)
5. Attempt to type the content for the first list item.

## Expected Behavior
I should be able to type the content for the first list item, and it should output where the blinking cursor appears after "1. ".

## Current Behavior
The blinking cursor displays, but what I type doesn't appear.  I have to click back into the block to be able to add content after the "1. ".

**Comment by EphoxJames** [comment] 2017-08-28 02:36
I can confirm. The bug seems to be a selection/focus issue:

When the keyboard doesn't work the activeElement and selection is as follows:
`activeElement: <ol class="blocks-editable__tinymce mce-content-body" aria-label="Write list…" id="mce_5" data-is-placeholder-visible="false" contenteditable="true"> selection: Selection { anchorNode: <ol#mce_5.blocks-editable__tinymce.mce-content-body>, anchorOffset: 0, focusNode: <ol#mce_5.blocks-editable__tinymce.mce-content-body>, focusOffset: 0, isCollapsed: true, rangeCount: 1, caretBidiLevel: null }`

As soon as you click the editor again it changes to this:
`activeElement: <ol class="blocks-editable__tinymce mce-content-body" aria-label="Write list…" id="mce_5" data-is-placeholder-visible="false" contenteditable="true"> selection: Selection { anchorNode: <li>, anchorOffset: 0, focusNode: <li>, focusOffset: 0, isCollapsed: true, rangeCount: 1, caretBidiLevel: 0 }`

**Comment by EphoxJames** [comment] 2017-08-28 02:37
It seems that the selection is being set to the ordered list instead of the list item.

**Comment by EphoxJames** [comment] 2017-08-28 02:38
I don't know why using the "+" menu would change this though.

**Comment by youknowriad** [comment] 2017-12-22 13:35
This works well for me now. Closing. Feel free to reopen if I missed something.

**Closed by youknowriad** 2017-12-22 13:35 UTC
Labels: [Component] TinyMCE
