### ISSUE TITLE
Generated slug is "auto-draft" when a new post is created

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#8770] opened 2018-08-09 11:39 UTC
**Describe the bug**
The `generated_slug` attribute in the `core/editor` store is set to `auto-draft` by default.

**To Reproduce**
1. Create a new post in Gutenberg.
1. In the console execute the following line:
```
wp.data.select( 'core/editor' ).getEditedPostAttribute( 'generated_slug' );
```

**Expected behavior**
I expect `generated_slug` to be empty.

**Additional note on autosaving**
When I look at the slug that is generated when the autosave is triggered before a draft is saved manually, I see that the url is: `http://example.com/?p=123` (you can view the url when hovering over the title). So either the `generated_slug` should be `?p=123` or an empty string, after an autosave.

Why `auto-draft` (which is a post status) is in the `generated_slug` field in the first place seems unintentional?

**Screenshots**

**Additional context**
Gutenberg version: 3.4

Currently we use the following logic to get the slug from the `core/editor` store:
```
/**
 * Get the post's slug.
 *
 * @returns {string} The post's slug.
 */
getSlug() {
	const getPostAttribute = wp.data.select( "core/editor" ).getPostAttribute;
	/**
	 * Before the post has been saved for the first time, the generated_slug is "auto-draft".
	 *
	 * Before the post is saved the post status is "auto-draft", so when this is the case the slug
	 * should be empty.
	 */
	if ( getPostAttribute( "status" ) === "auto-draft" ) {
		return "";
	}
	let generatedSlug = getPostAttribute( "generated_slug" );

	if ( generatedSlug === "auto-draft" ) {
		generatedSlug = "";
	}
	// When no custom slug is provided we should use the generated_slug attribute.
	return getPostAttribute( "slug" ) || generatedSlug;
}
```

**Comment by aduth** [comment] 2019-05-31 15:51
In debugging this, I've found that while this is perhaps a not-desirable result, it is expected by the current logic of the REST API and permalink-generating. I'm not familiar enough with the context for why it is implemented the way it is, but you can follow it back from the logic:

```
$ wp shell
wp> $default_post_to_edit = get_default_post_to_edit( 'post', true );
wp> $post = get_post( $default_post_to_edit->ID );
wp> get_sample_permalink( $post->ID, $post->post_title, '' );
=> array(2) {
  [0]=>
  string(26) "http://editor.test/?p=5362"
  [1]=>
  string(10) "auto-draft"
}
```

The second member of the array is what's returned as the `generated_slug` ([source](https://github.com/WordPress/WordPress/blob/13da094c39e345c62210b7177cb3c31291589530/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1626)). The arguments in this example are pulled directly from how the posts REST API controller operates ([source](https://github.com/WordPress/WordPress/blob/13da094c39e345c62210b7177cb3c31291589530/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1620)).

There is a peculiar though: The result of a `WP_Post` instance differs between `get_default_post_to_edit` and what would be produced by `get_post` when using the ID from `get_default_post_to_edit` (which is what the REST API is operating with). In the former case, you _would_ get an empty `generated_slug` when fed directly into `get_sample_permalink`. This is because `get_default_post_to_edit` explicitly overrides the post object's title ([source](https://github.com/WordPress/WordPress/blob/13da094c39e345c62210b7177cb3c31291589530/wp-admin/includes/post.php#L718)), presumably to be able to display it correctly in the Classic Editor interface with an empty title field.

With that in mind, there could be possible actions to produce an empty string, if that's the desired result: 

- `get_sample_permalink` should be more aware of the post status to assign the slug to always be an empty string
- The [arguments passed to `get_sample_permalink`](https://github.com/WordPress/WordPress/blob/13da094c39e345c62210b7177cb3c31291589530/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1620) in the posts controller should account for the auto-draft status

Since this is not a problem caused by Gutenberg, I'm going to close the issue. Depending on expected behaviors and possible resolution paths, I'd encourage you to consider opening a [Trac ticket](https://core.trac.wordpress.org/) instead.

**Closed by aduth** 2019-05-31 15:51 UTC
Labels: [Component] Saving, [Package] Editor, [Type] Bug
