### ISSUE TITLE
Welcome tooltips appear every time I create a new post

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#12697] opened 2018-12-08 07:15 UTC
**Describe the bug**
Every time I open Gutenberg to create a new post, the tooltips introducing me to Gutenberg pop up, even though I've used the editor before.

**To Reproduce**
1. Create a new page/post.
2. Watch the tooltips appear!

**Expected behavior**
I expect these tooltips to only appear the first time you use the editor, and not after. 

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [63.0.3 (64-bit)]

**Additional context**
- I am using WordPress 5.0, which includes Gutenberg.

**Comment by designsimply** [comment] 2018-12-08 13:49
Can you try completely clearing your browser cache and cookies and try dismissing the tips again?

Any chance you can check whether this problem happens for you in browsers other than Firefox?

Are you using any browser add-ons that affect cache?

**Comment by Wingo5315** [comment] 2018-12-08 17:55
I have tried this and it doesn't work. I have checked and this still happens in the latest version of Chrome. I am not using any add-ons that affect cache/cookies.
I think a solution to this would be to store on the database whether the individual user has seen the tooltips or not.

**Comment by pbrocks** [comment] 2018-12-09 21:43
@Wingo5315 Does the checkbox under Options not remain unchecked? I was not able to reproduce, but I'm on a Mac


![tooltip-dismissed](https://user-images.githubusercontent.com/5721313/49703324-2f939700-fbc9-11e8-887f-c93c68b52404.gif)

**Comment by Wingo5315** [comment] 2018-12-11 15:51
It was unchecked, but only after I had closed the first tooltip.
Even then, this is reset at the end of my browsing session.

**Comment by bupotalovo** [comment] 2018-12-11 16:02
> Even then, this is reset at the end of my browsing session.

Gutenberg does not save settings to database but only in local storage of browser which almost everybody I know clears on a regular basis. This has been discussed several times, a few examples:

- https://github.com/WordPress/gutenberg/issues/11797
- https://github.com/WordPress/gutenberg/issues/8052
- https://github.com/WordPress/gutenberg/issues/10742
- ...

**Comment by designsimply** [comment] 2018-12-20 21:33
Closing with the explanation that @bupotalovo provided. 

@Wingo5315 I do think something in your local environment or browser settings is causing the trouble in your case. If you can try testing from a completely different computer and/or network location, I think you will see that the tips stay gone as long as you're in the same browser session.

**Closed by designsimply** 2018-12-20 21:33 UTC
Labels: NUX, [Type] Help Request
