### ISSUE TITLE
Hamburger menu not working since last update!

### ISSUE THREAD

**Issue by linwoodlana** [WordPress/gutenberg#45921] opened 2022-11-19 16:02 UTC
Hi, 
Since last plugin update when clicking hamburger menu it doesn't work. When I deactivate, the menu works as expected!
It is not conflicting with other plugins because it is the only one activate!

**Comment by t-hamano** [comment] 2022-11-24 12:47
@nitamorais 
Thanks for the report.

A similar problem was recently reported in[ comment #33273](https://github.com/WordPress/gutenberg/issues/33273#issuecomment-1315161156). However, since this PR solves the path problem in a Windows environment, it should not have originally caused the problem in a Unix-based environment.

In what environments have you encountered this problem? It would be great if you could tell us your OS and browser.

**Comment by linwoodlana** [comment] 2022-11-24 18:02
@t-hamano 
Thanks for replying .
My OS - Windows 11
Browser - Chrome (last version)
Firefox and Edge (also last versions) same situation.

**Comment by t-hamano** [comment] 2022-11-25 10:22
@nitamorais
If the problem is occurring on Windows, #45773 should resolve it. However, since this PR is part of Gutenberg 14.7, it has not yet been released as a plugin. When version 14.7 is released, it would be good to see that this issue is resolved.

I would like to close this issue, but if that Gutenberg version has not solved the problem, it would be great if you could report back here.

**Closed as completed by t-hamano** 2022-11-25 10:22 UTC
Labels: Mobile Web, Gutenberg Plugin, [Block] Navigation
