### ISSUE TITLE
CSS and JS is not loading in Editor 

### ISSUE THREAD

**Issue by abkarim** [WordPress/gutenberg#55683] opened 2023-10-29 12:02 UTC
### Description

CSS and JS is not loading in Editor, but these load on frontend

## Home page 
![Screenshot from 2023-10-29 17-52-52](https://github.com/WordPress/gutenberg/assets/84965867/26c7392a-0e33-44b6-91a2-36ecf0fb81b6)

## In Editor 
![Screenshot from 2023-10-29 17-53-11](https://github.com/WordPress/gutenberg/assets/84965867/9f0ea80b-f117-4521-b9d0-9ca5260ebd53)

### Step-by-step reproduction instructions

1. Go to localhost  (Site frontend) - it works fine
2. Go to Editor - does not load, no error and warning in console

### Screenshots, screen recording, code snippet

```php
    /**
     * Load frontend custom files
     *       
     * @since 0.2.4
     * @access public
     */
    public static function load_frontend_custom_files()
    {
        require_once XYNITY_BLOCKS_DIR . "includes/classes/FileSystem.php";

        $dir_src = FileSystem::get_xynity_blocks_folder_url();

        foreach (self::$_frontend_custom_files as $file) {
            if ($file->file_type === 'css') {
                wp_enqueue_style("xynity-blocks-custom-file-{$file->file_slug}", "$dir_src/css/{$file->file_slug}.css", [], "{$file->file_version}", 'all');
            } elseif ($file->file_type === "js") {
                wp_enqueue_script("xynity-blocks-custom-file-{$file->file_slug}", "$dir_src/js/{$file->file_slug}.js", [], "{$file->file_version}", intval($file->load_in_footer));
            }
        }
    }
```

### Environment info

- WP *6.3.2* in docker

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-10-30 02:16
Hi @abkarim,

What hook does the `load_frontend_custom_files` function run through? If the assets you want to load are content-related, they should be enqueued to both the editor and the frontend via [the enqueue_block_assets hook](https://developer.wordpress.org/block-editor/how-to-guides/enqueueing-assets-in-the-editor/#editor-content-scripts-and-styles).

**Comment by abkarim** [comment] 2023-10-30 05:45
Thank you

**Comment by t-hamano** [comment] 2023-10-30 12:11
I would like to close this issue, but if the issue is still not resolved, please feel free to comment.

**Closed as completed by t-hamano** 2023-10-30 12:11 UTC
Labels: [Status] Needs More Info

**Comment by abkarim** [comment] 2023-10-30 12:56
```php
  /**
   * Load in editor
   */
  add_action('enqueue_block_editor_assets', function () {
      self::load_frontend_custom_files();
  });
```

![Screenshot from 2023-10-30 18-55-55](https://github.com/WordPress/gutenberg/assets/84965867/5f267a16-90dd-4ed5-bcdf-d3e688ff0296)


It loads content in editor but, it doesn't affect the content. The problem is - it's loading in the editor, not in the iframe that is used for displaying the site.

How to actually load these styles and scripts in the iframe.  
I think it's a bug @t-hamano 

Why do I need to configure hooks or filter to work in the editor ? It works perfectly in the frontend! It should be the same how it works in the frontend. Don't you think, it should work without any configuration?

**Comment by t-hamano** [comment] 2023-10-30 13:09
> It loads content in editor but, it doesn't affect the content. The problem is - it's loading in the editor, not in the iframe that is used for displaying the site.

f the CSS you're enqueuing contains a specific selector, it should also be loaded in the iframe editor, even if you use the `enqueue_block_editor_assets` hook. Please see [Backward compatibility and known issues](https://developer.wordpress.org/block-editor/how-to-guides/enqueueing-assets-in-the-editor/#backward-compatibility-and-known-issues) section.

This page also explains in detail why there are multiple hooks and when you should use them.
