### ISSUE TITLE
Generate a Theme Style Guide with theme.json data

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#48141] opened 2023-02-16 19:11 UTC
## What problem does this address?
Using theme.json is great progress in the efforts to standardize and streamline. However there is no one quick and easy way to see what is set in the theme.json as a user. I propose we look into creating a theme style guide. It would be a WordPress admin page that shows all the theme.json details in a more user pleasing manner. For example we could have a section showing all the colors created in the theme.json along with their names, and slugs. Yes users can use devtools, or edit a post and look at the choose colors control, but neither are great options (or obvious) if you want to read all the color names in an easy list format.

**Comment by carolinan** [comment] 2023-02-17 10:02
@bhubbard Do you mean specifically for classic themes that do not support the Site Editor?
Because all the colors are already listed in the Site Editor, and the blocks can be previewed in the Site Editor style book.

**Comment by bhubbard** [comment] 2023-02-24 00:44
@carolinan I was referring for classic themes, but also having an dedicated admin page showing the style book might be enough, as its not always obvious where to find it.

**Comment by annezazu** [comment] 2023-10-03 19:55
I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/41119 I'm going to close out as a result but let me know if I'm missing something and this needs to be reopened :)

**Closed as completed by annezazu** 2023-10-03 19:55 UTC
Labels: [Type] Enhancement, Global Styles
