### ISSUE TITLE
Dragging a couple of paragraphs to a column crashes gutenberg

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33610] opened 2021-07-21 19:25 UTC
## Description

Dragging a couple of paragraphs to a column crashes gutenberg

## Step-by-step reproduction instructions

1. Create a column block with 2 columns
2. Create 3 paragraph blocks with text OUTSIDE the column
3. Press and hold Shift and select those 3 paragraph blocks
4. If you have the tool menu not fixed on the top, you should be able to drag and drop the whole 3 blocks with the 6-dots icon
5. Drg it and place it inside one of the columns

## Expected behaviour

It should move all the content within that particular column, like always has been.

## Actual behaviour

It crashes gutenberg.

Here is the the report:
TypeError: Cannot read property 'firstChild' of null
    at pp (https://kiltros.cl/wp/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:393446)
    at https://kiltros.cl/wp/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:394426
    at Bh (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126:456)
    at Dj (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:476)
    at unstable_runWithPriority (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
    at xb (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:231)
    at Te (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:79)
    at https://kiltros.cl/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:68
    at unstable_runWithPriority (https://kiltros.cl/wp/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/11801254/126547771-b115d8d7-89bf-4f65-8370-93a03798d766.png)
![image](https://user-images.githubusercontent.com/11801254/126547681-7e7db5e4-cef9-4de1-916f-fa716305bf18.png)

## WordPress information
- WordPress version: 5.8
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)?no 

## Device information
- Device: desktop
- Operating system: chrome os
- Browser: chrome 91

**Comment by kevin940726** [comment] 2021-07-22 03:31
I can confirm this issue. Here's a recording of the reproduction.

https://user-images.githubusercontent.com/7753001/126586517-1f8b20df-00ff-43b5-9be5-448cb31a0b40.mp4

**Comment by diggeddy** [comment] 2021-07-23 11:11
This issue is not just with the Columns block. It affects all nested blocks eg. Group Block, Cover Block and any other 3rd party nestable block

**Comment by codysmith44** [comment] 2021-07-23 19:19
Can also confirm...starting writing a new bug report but figured I'd add my voice to this one.

**Comment by talldan** [comment] 2021-07-26 06:58
Seems to be the multi-selection code that triggers the error. Right here the `startRef.current` and `endRef.current` are `null`:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/writing-flow/use-multi-selection.js#L134-L135

`getDeepestNode` then throws an error.

**Comment by vortacan** [comment] 2021-08-04 13:52
Can confirm the issue on the Group Block and a Custom Block of mine (with InnerBlocks and ButtonBlockAppender). Selecting and moving (dragging) multiple blocks in the editor to another location (changing the order without dropping them on a nested block) works though. Makes no difference if the Group block is empty or already contains child blocks.

**Comment by tehjaymo** [comment] 2021-09-29 11:53
This is becoming a bigger. Behaviour also seems to also happen over time if working Inside a media block too.

**Comment by TheRadicalDreamer** [comment] 2021-11-12 21:37
still crashes gutenberg and i cannot make my pages!

**Comment by annezazu** [comment] 2023-04-28 13:26
Just tried to replicate this with WordPress 6.2 and cannot replicate anymore. Closing this out as a result! If anyone else can replicate, please let me know and I'll reopen.

**Closed as completed by annezazu** 2023-04-28 13:26 UTC
Labels: [Type] Bug, [Feature] Block Multi Selection, [Feature] Drag and Drop, [Block] Columns
