### ISSUE TITLE
Add an option to only view media for a specific post versus the entire library

### ISSUE THREAD

**Issue by lizkarkoski** [WordPress/gutenberg#9031] opened 2018-08-15 15:59 UTC
**Is your feature request related to a problem? Please describe.**
This is request came to us from the Gutenberg forum. Here is the thread with screen shots outlining the request: 
https://wordpress.org/support/topic/images-uploaded-to-a-special-post/

**Describe the solution you'd like**
When editing a post and clicking on the media option, it'd be nice to have a toggle to only view the media that's been added to the post, versus the entire library. 

This would help folks who have a large media library to sort through when making changes or editing posts.

**Comment by designsimply** [comment] 2018-08-15 18:46
Thank you for the report! Closing as a duplicate of #8748.

**Closed by designsimply** 2018-08-15 18:46 UTC
Labels: Media, [Status] Duplicate, [Type] Enhancement
