### ISSUE TITLE
Buttons-block item justification alignement for post not working

### ISSUE THREAD

**Issue by c24b** [WordPress/gutenberg#52209] opened 2023-07-01 20:04 UTC
### Description

When using button block in a post or a custom post type, 
alignment is not set in the FRONT but in the editor 
it keeps aligned to left (default behaviour)
This happens because no classes is output at wp-buttons or wp-button.
Clicking on button produce this code
 
<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Test</a></div>
</div>
</div>

This happens only in the post. Page are ok...

### Step-by-step reproduction instructions

1. Create a post
2. Add a button block
3. Click on the editing bar and select change item  justification 
4. Choose an alignement option such as  right or center
5. Register the post
6. Consult the post 

### Screenshots, screen recording, code snippet

```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --> 
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Test</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>

```

### Environment info

- WordPress 6.2.2 
- Gutenberg: 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2023-07-02 09:48
Hi
I copied the code from the issue, and then duplicated so that I had one copy each of the justifications.
I was not able to reproduce the problem. I tested using Twenty Twenty-Three.

What theme are you using, does the problem persist if you change themes?

**Comment by t-hamano** [comment] 2023-07-02 15:07
I, too, could not reproduce it in the following environment.

- WordPress 6.2.2 (with / without Gutenberg v16.1.0 enabled)
- WordPress 6.3-beta2-56124 (with / without Gutenberg v16.1.0 enabled)

**Comment by c24b** [comment] 2023-07-02 16:46
I confirm this is not happening using Twenty Twenty-Three Theme. I imagine that might be a problem in my theme that use theme.json and backward compatibility with functions.php, when declaring custom template for custom post type. Therefore, could anyone can point me out the documentation to make the default behaviour of  core/button available in post not only pages?  How to attached button core to post?

**Comment by carolinan** [comment] 2023-07-02 20:39
It is not possible, for me at least, to answer what may be the cause without reading the custom code.

I am not sure if there is a code example missing? 
You wrote "Clicking on button produce this code"  _Which_ code? Is there an error message in the console? 

- Block settings are independent of post types.
- Both classic themes and block themes can use functions.php and theme.json, so this does not narrow it down. 
- There are no theme.json settings that can disable settings for a post type, so you can exclude that. 
- Make sure your theme is not overriding the block CSS.

**Comment by c24b** [comment] 2023-07-02 22:18
I understand very well that it impossible to define the cause without reading the custom code, nobody could. And I apologize for probably making you wait your precious time (which is I insist very valuable as you make a pretty great job sincerely)

There was a mistake typing my issue I changed the place of the code. Apologies. 


If I understood correctly the expected behaviour when clicking on the button in Gutenberg Editor and then clicking on edit justification, it is supposed to inject a custom class in the parent buttons container. 
Such as for pages that are working well
```html
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --> 
<div class="wp-block-buttonswp-block-buttons is-content-justification-center is-layout-flex wp-container-1"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Test</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>   
```

For custom posts clicking on the option doesn't inject the proper class name: basically no classname are injected
```html
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --> 
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Test</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>   
```
 So I wonder how I can make buttons layout option be supported for my custom post type as I have seen no option in blocks that could specify this. 

Maybe you could pointed me out where exactely  in the code this injection is made? It would be so kind, as I have no time to rewrite all my theme to be fully compliant to 2023 Theme. But next one, promise!

**Comment by carolinan** [comment] 2023-07-03 04:16
I am not sure where you are copying the code from.
This code is incorrect, the class name should not be duplicated this way:
```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --> 
<div class="wp-block-buttonswp-block-buttons is-content-justification-center is-layout-flex wp-container-1">

```

The markup that is in the editor, that includes the class names, is not the same markup that you see if you select the **code editor mode.**

Here is the results from my test. All justifications are working both in the editor and front.
Custom post type, actual editor markup:

`<div tabindex="0" class="block-editor-block-list__block wp-block wp-block-buttons block-editor-block-list__layout wp-container-2 is-layout-flex is-content-justification-center" id="block-3a2eb994-0352-49ab-8582-7c47d35ea576" role="document" aria-label="Block: Buttons" data-block="3a2eb994-0352-49ab-8582-7c47d35ea576" data-type="core/buttons" data-title="Buttons" data-is-drop-zone="true"><div tabindex="0" class="block-editor-block-list__block wp-block wp-block-button" id="block-6e5bd219-1b39-4938-8595-bc2e22c318f0" role="document" aria-label="Block: Button" data-block="6e5bd219-1b39-4938-8595-bc2e22c318f0" data-type="core/button" data-title="Button"><div role="textbox" aria-multiline="true" aria-label="Button text" class="block-editor-rich-text__editable wp-block-button__link wp-element-button rich-text" contenteditable="true" style="white-space: pre-wrap; min-width: 1px;">text</div></div></div>`

Code editor mode:
```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">text</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

Front:
```
<div class="wp-block-buttons is-content-justification-center is-layout-flex wp-container-10">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">text</a></div>
</div>

```

**Comment by carolinan** [comment] 2023-07-03 04:23
The source you are looking for is probably https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/layouts

**Comment by c24b** [comment] 2023-07-03 07:11
Thanks!

**Comment by towercity** [comment] 2023-07-11 19:52
Hello all,

I am having this exact issue as well. I am using a non-block theme. 

When I create a center justified button block with the following code:
```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"}} -->
<div class="wp-block-buttons"><!-- wp:button {"textAlign":"center","width":25} -->
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-center wp-element-button">button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

The page renders the following markup:
```
<div class="wp-block-buttons">
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-center wp-element-button">button</a></div>
</div>
```

I am using WordPress 6.2

Are there any troubleshooting steps I can take for this?

**Comment by carolinan** [comment] 2023-07-12 04:36
Hi
Thank you for the details.
I still am not able to reproduce this. I copied the code from above. The button is centered correctly in the editor and front.

**Resulting markup in the code editor after saving:**

WP 6.2.2
```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"}} -->
<div class="wp-block-buttons"><!-- wp:button {"textAlign":"center","width":25} -->
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-center wp-element-button">button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```


WP 6.3 beta 4:

```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"}} -->
<div class="wp-block-buttons"><!-- wp:button {"textAlign":"center","width":25} -->
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-center wp-element-button">button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```


macOS
nginx, PHP 8.1.9
Gutenberg was not active for this test.

**Comment by towercity** [comment] 2023-07-12 14:27
I am currently using PHP 7.4.30. Is it possible this could be causing the issue?

**Comment by t-hamano** [comment] 2023-07-12 15:36
I am also unable to reproduce this problem.

- WordPress Version: WordPress 6.3-beta4
- PHP Version: 7.4.33
- Tested with Gutenberg plugin both enabled and disabled
- Tested with both TT1 and TT3 themes

@c24b @towercity 

Could you switch to the default theme and see if this problem still occurs when all plugins are stopped?

**Comment by towercity** [comment] 2023-07-12 20:13
When I switch to the default theme (Twenty Twenty Two), the buttons function properly for me. 

The following block editor markup:
```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```
Is rendered on the page as:
```
<div class="wp-block-buttons is-content-justification-center is-layout-flex wp-container-7">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button</a></div>
</div>
```

**Comment by t-hamano** [comment] 2023-07-13 12:50
@towercity 

Thanks for testing. So what is the theme that is causing the problem? Is it a theme available for download from the theme directory?

**Comment by towercity** [comment] 2023-07-13 14:34
I'm using a custom theme based off of Genesis, not available in the theme directory. If I enable Genesis on its own, the buttons do center properly, and the html markup gets the "is-content-justification-center" class.

Clearly this is an issue with the custom theme I'm using, but I've never encountered an error where a theme causes a block to completely ignore settings from the block editor.  Is there a likely place in the theme that could be causing this?

**Comment by t-hamano** [comment] 2023-07-13 14:40
> Clearly this is an issue with the custom theme I'm using, but I've never encountered an error where a theme causes a block to completely ignore settings from the block editor. Is there a likely place in the theme that could be causing this?

I have not encountered this problem, but you may be able to find the cause by removing the custom theme features one by one. For example, if you have functions.php, comment out any hooks or functions you have defined in them.

**Comment by towercity** [comment] 2023-07-14 18:51
I've found the reason this error was occurring, at least for my theme.

Following [this](https://github.com/WordPress/gutenberg/issues/38127#issuecomment-1132432252) advice from another issue, I had added the following hooks to my theme:
```
remove_filter( 'render_block', 'wp_render_layout_support_flag', 10, 2 );
remove_filter( 'render_block', 'gutenberg_render_layout_support_flag', 10, 2 );
```
This was also preventing the block editor from adding any layout classes to the buttons block. I removed the hooks above, and now all is working as it should

This may just be a particular little edge case for me, but I'm adding this here in case anyone else finding this issue later has the same cause.

**Comment by t-hamano** [comment] 2023-07-15 06:10
@towercity

Glad you were able to solve the problem. It would be great if @c24b , who originally created this issue, could also confirm whether this problem is reproduced in the default theme or if some code in the custom theme is affected.

**Comment by carolinan** [comment] 2023-07-17 04:18
Doesn't removing the layout support have rather large consequences for other features? It doesn't seem like the right solution for me to fix one issue with a buttons block.

I also think that when writing issues and solutions and also when testing, it is important that we make sure that we clarify if we are using:
a block theme
a classic theme without theme.json
a classic theme with theme.json, (also called hybrid theme)

Because different features are available for these theme types.

_Perhaps we need to add a theme type to the issue template._

**Comment by towercity** [comment] 2023-07-17 14:18
I may have been unclear. A previous issue I linked to in my response above suggested adding those lines to fix a layout problem. I removed those lines from my theme to fix this issue. All this was on a classic theme without a theme.json

**Comment by jordesign** [comment] 2023-07-18 03:31
Just to chime in here - if the issue is only recreatable in a custom theme (or themes) but not with default themes (like T23) then it is likely not an issue with Gutenberg, but one to follow up with the theme(s) developers.

I'd be inclined to recommend this issue be closed.

**Comment by t-hamano** [comment] 2023-07-18 04:26
As suggested in [this comment](https://github.com/WordPress/gutenberg/issues/38127#issuecomment-1132432252), removing the `wp_render_layout_support_flag` from the `render_block` filter will stop the output of the `wp-container-{}` class. At the same time, classes related to layouts will no longer be output. However, I think this is not a bug, but expected behavior, and the developer needs to fully control over which classes are output instead.

Both @c24b and @towercity said they were unable to reproduce this issue with the default theme, so I expect the problem exists in the custom theme.

I, too, would like to close this as I don't think this is a WP Core or Gutenberg issue.

**Closed as not planned by t-hamano** 2023-07-18 04:26 UTC
Labels: [Type] Bug, [Status] Not Applicable, [Block] Buttons
