### ISSUE TITLE
Site Editor: not possible to change site icon

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29126] opened 2021-02-18 20:37 UTC
Once the FSE is enabled by activating the supporting theme, it's no longer possible to change the site icon. This was previously done through Customizer but since it's disabled and replaced with Site Editor, this option is no longer reachable.

**Comment by Sandstromer** [comment] 2021-02-19 10:56
The Customizer is not completely disabled, only the links in the adminbar/sidebar have been removed.

It is still possible to reach the customizer and change the site icon by going directly to `/wp-admin/customize.php`

I agree there does need to be a way of editing the site icon in the site editor, and possibly disabling access to the customizer.

**Comment by vindl** [comment] 2021-02-19 11:37
> The Customizer is not completely disabled, only the links in the adminbar/sidebar have been removed.

Yes, that's what I had in mind. As for disabling access to it completely - it might be useful to keep that around as an escape hatch before Site Editor achieves parity.

**Comment by carolinan** [comment] 2021-02-22 05:05
> It is still possible to reach the customizer and change the site icon by going directly to `/wp-admin/customize.php`

This is not a solution for non technical end users. 
One solution would be to move it to Settings > General, and not depend on either the customizer or the site editor.
(This would be a core issue)

**Comment by Sandstromer** [comment] 2021-02-22 11:34
Interested to hear why the site icon should not be editable in the site editor?

Currently if a site has a site icon defined - for example was previously added in the customizer, and then switched to a FSE theme - the WordPress icon in the top left of the site editor is replaced with the site icon.

So in this case the site icon is visible in the site editor, but with no obvious way to change it.

**Comment by carolinan** [comment] 2021-02-22 14:21
> Interested to hear why the site icon should not be editable in the site editor?

I understand the problem that you describe.

But having the control in two places increases complexity both for users and developers.
There is no documented plan, as far as I can tell, for how FSE and the customizer will or will not work together.
Moving the option to the WordPress admin bypasses that problem.

**Comment by Sandstromer** [comment] 2021-02-22 16:52
> But **having the control in two places** increases complexity both for users and developers.
> There is no documented plan, as far as I can tell, for how FSE+ site editor and the customizer will or will not work together.
> Moving the option to the WordPress admin bypasses that problem.

Thanks. That makes sense. I understand now.

**Comment by jasmussen** [comment] 2021-03-05 08:43
@annezazu mentioned in #29578 (a duplicate of this one) something worth copying over:

> This might work nicely in Global Styles as a start as I imagine that would be a natural place where users might look.

I would agree, the global styles interface seems a potentially good place to put a favicon control.

If not there, then potentially it could be related to how the "Site Block" (#16998) could surface site related properties.

**Comment by mtias** [comment] 2021-03-15 14:20
It has always felt a bit weird for me to find this buried in "site identity" in the customizer. It's also not clear that the "logo" is separate from the site-icon.

I think it makes more sense for the site-icon to be in Settings > General than to add it the site editor. This is an attribute that is not used in the site itself. I'd add one caveat: the "logo" block should probably include a flow for updating the icon or replacing it using the logo image.

In any case, with the current approach of hiding the customizer this is a problem that needs to be addressed.

**Comment by hedgefield** [comment] 2021-05-06 11:55
This didn't cross my mind until I was looking at #30406, very good point, we need a place to set this. I'm not sure keeping it out of the Site Editor is what I'd do, that feels even more buried. But it's not exactly something visual in the sense that it fits into the site editor block paradigm. Thinking about where I'd go looking for this, iI think it would make sense if it was in the Template tab in the sidebar, but I'm not sure whether it's intended for Templates to have sidebar settings like that?

**Comment by noisysocks** [comment] 2021-10-28 00:01
What's the status of this one? Are we still awaiting design, or looking for a dev?

**Comment by carolinan** [comment] 2021-10-28 01:22
I think we can call this a partial fix https://github.com/WordPress/gutenberg/pull/35892

Another option is to revert the removal of the customizer menu item....

**Comment by stacimc** [comment] 2021-10-29 23:39
> I think we can call this a partial fix #35892

#35892 adds an option to sync the site icon to the Site Logo from the Site Logo block. The help text also contains a direct link to the Customizer to update the site icon independently.

<img width="279" alt="Screen Shot 2021-10-29 at 12 30 33 PM" src="https://user-images.githubusercontent.com/63313398/139511387-e1c89188-e227-4ed2-ad7e-68486dbf3c37.png">

That does provide a path to the customizer from blocks themes, although I'm unable to link directly to the Site Identity section. It may be a bit hidden, but I think it makes sense as a partial fix.

**Comment by Mamaduka** [comment] 2021-11-03 07:55
Hi, folks

It was decided not to hide Customizer in WP 5.9 release and until we have full feature parity in Side Editor. You can find more details in this PR - #36168.

I'm going to remove this issue for WP 5.9 must-haves, but we should start looking into this Enhancement early for the next major releaase.

**Comment by jameskoster** [comment] 2021-11-03 12:36
> It was decided not to hide Customizer in WP 5.9 release and until we have full feature parity in Side Editor. You can find more details in this PR - #36168.

Looks like this may no longer be the case? :D 

While adding an option to set the site icon via the Site Logo block helps somewhat, it doesn't cover instances where the active theme isn't utilising that block.

Couldn't we just add an option to the general settings screen to configure this?

<img width="851" alt="Screenshot 2021-11-03 at 12 34 17" src="https://user-images.githubusercontent.com/846565/140060955-14fee037-e55b-4b43-a222-0cf9c321916c.png">

**Comment by Mamaduka** [comment] 2021-11-03 13:00
> Looks like this may no longer be the case? :D

It looks that way 😄 

The problem with Site Icon is that it doesn't fit in the content canvas, so it can't be a block. We also don't have a place other than "Global Styles" for displaying site-wide settings in the editor.

I like the idea of moving the feature in Settings -> General.

P.S. It's been a while since I've built an image uploader component outside of Block Editor, so I'm not sure how much work that would require.

**Comment by jameskoster** [comment] 2021-11-03 13:13
Hopefully we can just reuse something from the media library :d

**Comment by carolinan** [comment] 2021-11-03 13:36
I would be happy with the option being under general settings. That would be a core change and need a Trac issue?

**Comment by Mamaduka** [comment] 2021-11-03 14:22
Yes, I think @jameskoster suggestion should be a Trac ticket.

**Comment by jameskoster** [comment] 2021-11-03 15:23
Ticket opened: https://core.trac.wordpress.org/ticket/54370

**Comment by noisysocks** [comment] 2021-11-04 00:14
Thanks @jameskoster. Closing this in favour of https://core.trac.wordpress.org/ticket/54370.

**Closed by noisysocks** 2021-11-04 00:14 UTC
Labels: [Type] Task, General Interface, Needs Design, [Release] Do Not Punt, [Feature] Full Site Editing
