### ISSUE TITLE
Shortcode block - Crash when switching dark mode on/off [only on Android]

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#29730] opened 2021-03-10 17:25 UTC
## Description

After adding a Shortcode block, switching dark mode on and then off produces a crash. I checked this behaviour with the rest of blocks and looks like it only happens with this one.

I also tested on production version `16.7` and it's also happening here so it's not a new regression.

**Sentry issue:** https://sentry.io/organizations/a8c/issues/1634562844/?project=1438083&project=1438088&query=is%3Aunresolved+user.email%3Afluiddot%40gmail.com&statsPeriod=14d

## Step-by-step reproduction instructions

1. Add a Shortcode block.
1. Enable dark mode.
1. Disable dark mode.
1. Observe that the app crash.

## Expected behaviour

Switching dark mode on/off shouldn't produce a crash.

## Actual behaviour

Switching dark mode on/off should update the styles as expected.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/110669398-93ec9900-81cc-11eb-90b4-8853edda5019.mp4

## WordPress information
- WordPress version: 16.9
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: 16.9

**Comment by hypest** [comment] 2021-03-12 12:32
Thanks for the ticket @fluiddot !
The flow is not super common (changing dark mode while in the editor or in a particular block) so looks like we don't need to make it a top priority. That said, it's a crash and most probably a simple™ one to fix so I'll find someone to work on it.

**Comment by hypest** [comment] 2021-03-12 12:34
BTW, does the crash happen on production builds too, or is it a silent failure?

**Comment by fluiddot** [comment] 2021-03-12 12:51
> BTW, does the crash happen on production builds too, or is it a silent failure?

Yeah, it's happening on production builds too, I tested on the latest one in Google Play (`16.7`) and crashes.

**Comment by mchowning** [comment] 2021-03-15 20:58
I'm wondering if maybe this is more of a `Medium` priority issue since it only occurs when switching from light to dark mode. As I understand it, the only way a user would repeatedly see this issue is if they repeatedly changed the dark mode setting, which I'm hoping is an edge case.  wdyt?

**Comment by fluiddot** [comment] 2021-03-16 09:46
>As I understand it, the only way a user would repeatedly see this issue is if they repeatedly changed the dark mode setting, which I'm hoping is an edge case. wdyt?

The scenario for producing the crash is:
- Have the editor opened
- Have a Shortcode block
- Switch dark mode on/off

I'm not sure how often users switch dark mode on/off but if it's not very common we could keep it as `Medium` priority.

**Comment by mchowning** [comment] 2021-03-16 11:22
I'll bump it down to `Medium` for now. If you or anyone else thinks it really should be a `High` feel free to go ahead and change it back.

**Comment by geriux** [comment] 2023-06-12 15:48
Hey there 👋 this issue seems to be solved as I can't reproduce it in the latest versions so I'll close it.

**Closed by geriux** 2023-06-12 15:48 UTC
Labels: [Type] Bug, Mobile App - i.e. Android or iOS
