### ISSUE TITLE
Posts : Add title text is not show properly.

### ISSUE THREAD

**Issue by Umangvaghela** [WordPress/gutenberg#3751] opened 2017-12-01 09:34 UTC
## Issue Overview
Add title text is not show properly when we click "Add text or type / to insert content" Text field. 
Toolbar section displays the above section while toolbar div is displayed after post content text html.

## Steps to Reproduce (for bugs)
1. Create a new post.
2. Click text field.

## Screenshots / Video

![gutenburge-image](https://user-images.githubusercontent.com/26810472/33476570-6eb0e20e-d6a8-11e7-96a0-f6de9eb5f92c.png)

## Todos
- [X] Tests

**Comment by jasmussen** [comment] 2017-12-01 10:37
I'm not entirely sure I understand the issue — are you referring to the fact that the placeholder text is invisible when the text block has focus? If so that's intentional. The following is intended behavior:

![placeholder](https://user-images.githubusercontent.com/1204802/33479073-fd5f3bee-d68b-11e7-9d5d-3efae7910bc4.gif)

**Comment by Umangvaghela** [comment] 2017-12-01 10:59
@jasmussen 

Sir, My issue is that when we click first time then Toolbar crop the Add title text.

Thanks

**Comment by jasmussen** [comment] 2017-12-01 11:06
Ah, so the issue is that the toolbar on the text block when selected covers the Add Title input field?

This is intended default behavior for now, but you can change your preferences to put this toolbar at the top of the screen:

<img width="348" alt="screen shot 2017-12-01 at 12 05 03" src="https://user-images.githubusercontent.com/1204802/33480097-fdc56b40-d68f-11e7-8010-21c70b190532.png">

Uncheck the "fix toolbar to block" option.

Upcoming usability tests will center around these two toolbar options, so I'm closing this one for now. Thanks for the report!

**Closed by jasmussen** 2017-12-01 11:06 UTC
Labels: [Status] Needs More Info
