### ISSUE TITLE
Zoom out: vertical toolbar should be positioned off-canvas?

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#63520] opened 2024-07-13 13:21 UTC
### Description

I thought the point of the vertical toolbar was to utilise the extra space we have off-canvas. Instead, it seems to be positioned in the canvas.

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/1f64aabb-242c-49ad-9fd8-b6b895eadd70">

Additionally there's the weird glitch, but it would be fixed by moving it off canvas as well.

![image](https://github.com/user-attachments/assets/45d9cfeb-cab9-441c-9985-6625f2f77fb3)

### Step-by-step reproduction instructions

Open a pattern inserter category and click a block.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment] 2024-07-13 17:57
Related #63463

**Comment by richtabor** [comment] 2024-07-16 14:41
I'm going to close this as a duplicate of https://github.com/WordPress/gutenberg/issues/63463.

**Closed as completed by richtabor** 2024-07-16 14:41 UTC
Labels: [Type] Bug, [Feature] Zoom Out
