### ISSUE TITLE
Previewing the page designated as "latest posts" shows to the frontpage.

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#2409] opened 2017-08-14 16:22 UTC
Discussion for Trac ticket https://core.trac.wordpress.org/ticket/34005
What should happen when you edit the Page designated as Latest Posts?

(Edited to add reproducing steps below)
**To reproduce:**
* Create two pages (let's call them "Front" and "Blog")
* Set Homepage to "Front" and Posts page to "Blog"
* Edit page 2 in editor mode
* Press preview
* Confirm you got Front instead of Blog

**Comment by karmatosed** [comment] 2017-11-07 17:42
For now, this I think needs closing as not something we should tackle in v1 of Gutenberg. It is worthy of consideration as we iterate.

**Comment by joyously** [comment] 2019-11-29 17:21
This issue needs to be reopened.
In the below test, I have assigned "a Blog Page" to be the page for Latest Posts, and "Page with Comments" to be the Home page.
When I edit the Blog Page, it shows the content as expected. But clicking on the Preview button shows the Page with Comments Home page, although the menu styling indicates that the Blog Page is the current page.
Tested with WP 5.3 (also got same result with GB 6.8 and GB 7.0).
![edit-latest-posts-page-2019-11-29 11-10](https://user-images.githubusercontent.com/7957680/69883354-690d5880-1299-11ea-8ec5-63501ddad4df.gif)

**Comment by melchoyce** [comment] 2019-12-13 21:24
Weirdly, when I try to open my Posts Page in the editor, it loads it in the Classic Editor instead of Gutenberg.

**Comment by talldan** [comment] 2019-12-16 02:01
@joyously Please could you update the title and description of this ticket? If you can provide steps for reproduction that would be appreciated.

**Comment by youknowriad** [comment] 2020-01-13 13:54
Closing. Let's reopen when this https://github.com/WordPress/gutenberg/issues/2409#issuecomment-565875649 gets adressed

**Comment by joyously** [comment] 2020-01-13 14:12
Hey, I don't see the point in closing because you want a different title.
There is a problem here, and it's not fixed, so this should remain open. I clearly show what happens. What more do you need?

**Comment by youknowriad** [comment] 2020-01-13 15:41
It's not closed because it needs a different title, it's closed because contributors didn't understand the issue and how to reproduce making the action non-actionable.

**Comment by khacoder** [comment] 2020-01-16 15:30
So I am getting a very similar problem to joyously.
My page settings are Homepage: Frontpage and Posts page: Blog.
When in editor mode on the Blog page and I press Preview I get the Front Page and not the blog index (blog posts). So I just wanted to confirm that there is definitely a problem.

I have WordPress 5.3.2 installed. This happens with and without the Gutenberg plugin installed.

**Comment by youknowriad** [comment] 2020-01-16 16:00
I tried again and I was actually able to replicate the issue with these steps. https://github.com/WordPress/gutenberg/issues/2409#issuecomment-575205552

**Comment by adamziel** [comment] 2020-04-21 11:29
I tracked down why the preview shows the front page and it's a core issue. After clicking "Open preview in new tab" while editing posts page, Gutenberg redirects to a preview URL like this one:

`https://mywpsite.com/?page_id=5&preview_id=5&preview_nonce=12bd60d6f4&preview=true`

When you visit that URL, WordPress will load the front page instead of the posts page. This is because `class-wp-query.php` assumes that posts page is also the front page:

https://github.com/WordPress/WordPress/blob/b4373fafe9b87f75bf9d65e808be8049510dff8b/wp-includes/class-wp-query.php#L1032

Then, when rendering a preview, it substitutes the `page_id` that was requested with the value of `get_option( 'page_on_front' )`:

https://github.com/WordPress/WordPress/blob/b4373fafe9b87f75bf9d65e808be8049510dff8b/wp-includes/class-wp-query.php#L1904

If I remove the preview parameters and leave only `?page_id=5`, it displays the correct page. It could be an okay-ish workaround since marking posts page as a draft or private doesn't actually prevent unauthenticated users from viewing it. Still, I think we should be really addressing the root cause in the core - I am going to close this one and fill a core ticket.

**Closed** 2020-04-21 11:29 UTC
Labels: [Feature] Saving, [Type] Bug

**Comment by adamziel** [comment] 2020-04-21 11:33
The core ticket is available here: https://core.trac.wordpress.org/ticket/49969

**Comment by joyously** [comment] 2020-10-30 14:31
I think you all sidetracked my original question for this issue, which was "What should the editor show when editing the Page designated as Latest Posts?"
Because the editor is WYSIWYG, should it show the actual contents of the Page (which is the current action) or should it show what is on the front end (which is the Preview-which happens to be wrong)? Perhaps this case is one way to enter into the Full Site Editor to be consistent, but that means there would be no way to edit the Page in preparation to switch it back to being a normal page.
