### ISSUE TITLE
FSE breaks admin when WooCommerce is active

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#30372] opened 2021-03-30 08:41 UTC
## Description
I wanted to try out the new **Full Site Editing** feature. After installing the [TT1 Block theme](https://wordpress.org/themes/tt1-blocks/) as recommended by [this post](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/), I then clicked on the new _Site Editor_ menu option, causing the Dashboard to break.

After checking my plugins, I noticed WooCommerce was activated. If I deactivate it, the _Site Editor_ feature loads as expected, but as soon as I activate it again, it breaks.

https://user-images.githubusercontent.com/2078245/112958745-83598e00-918e-11eb-87d5-2246937bd2aa.mp4

Console Error message
`TypeError: window.wpEditorL10n is undefined
    edit http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/block-library/index.js?ver=46baaa6f3f784fe4ecf746bbdb740050:68
    Bh http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:126
    Dj http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    unstable_runWithPriority http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25
    Da http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    xb http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    Bj http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    U http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:16
    onmessage http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:24
    EventHandlerNonNull* http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:24
    <anonymous> http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:9
    <anonymous> http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:9
react-dom.min.de439aae.js:125:24
`

## Step-by-step reproduction instructions
1. Install TT1 Theme and activate
2. Activate WooCommerce
3. Click on Site Editor
3. See White Screen

## Expected behaviour
The Dashboard shouldn't break

## Actual behaviour
See above

## Screenshots or screen recording (optional)
See above

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? No. Gutenberg & WooCommerce only
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Mac Mini
- Operating system: macOS Big Sur 11.2.3
- Browser: Firefox 87.0

**Comment by aristath** [comment] 2021-03-30 11:07
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/29132

**Closed as completed by aristath** 2021-03-30 11:07 UTC
Labels: [Type] Plugin Interoperability
