### ISSUE TITLE
Front-end markup doesn't update when Gutenberg updates

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8015] opened 2018-07-18 10:42 UTC
**Describe the bug**
I had a test page that I had created months ago. On the page it had a Multi-Column block (among lots of others). Up until only recently, the Multi-Column block was using CSS Grid. Recently, this has now changed to use Flexbox and more importantly, the content for each column is contained within its own container/div.

Even though my Gutenberg plugin was up to date, when I viewed this page on the front-end, it was still using the old markup (i.e. The blocks for each column weren't in their own container/div). The markup only changed to the new format once the page was re-saved.

Hypothetically, what happens in say 5 years time, when some new css grid spec is all the rage and WP is updated to use this all-new fancy grid? Is my page that I created 5 year earlier, still going to use the old markup? Based on the what I just saw with my old page, it would. I shouldn't have to go back and re-save all my old pages so that the front-end markup updates.

Obviously the most logical answer is no, I wouldn't have to re-save my old pages. In that case though, why did I just have to resave my old page now before seeing the new markup? How is this going to be avoided once Gutenberg is in core?

_Gutenberg 3.2.0_

**Comment by GlennMartin1** [comment] 2018-07-18 14:14
Related: https://github.com/WordPress/gutenberg/issues/7825

Keep in mind that the Columns block is designated "beta," and as such it's reasonable that there may be breakage while in the beta period.

**Comment by designsimply** [comment] 2018-07-18 23:13
Duplicate of #4849.

**Comment by f00d4tehg0dz** [comment] 2018-07-18 23:31
Further to that discussion @maddisondesigns  What happens when you have that block on 1,000 of pages. How will you update the block. Are you going to sit there and press "update" on every 1,000 pages?

**Comment by youknowriad** [comment] 2019-02-14 10:33
Let consolidate all the block validation, deprecation, migration discussions in a single issue #13611 thanks.

**Closed by youknowriad** 2019-02-14 10:33 UTC
Labels: Backwards Compatibility, Extensibility, [Type] Documentation, [Type] Question

**Comment by maddisondesigns** [comment] 2019-02-15 02:12
@youknowriad 
> Let consolidate all the block validation, deprecation, migration discussions in a single issue #13611

#13611 is closed so it seem pretty pointless to add comments there. I presume you mean #7604

**Comment by youknowriad** [comment] 2019-02-15 07:29
yes, sorry for the confusion, I discovered the existence of #7604 later.
