### ISSUE TITLE
Block Style variations that share the same name can overwrite each other

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#21386] opened 2020-04-03 18:06 UTC
If you are using multiple blocks that have the block style variation name, their styles will be reproduced on other blocks, leading to unintentional styling conflicts on blocks. 

Right now, block style variations are used to provide styling variations that would slightly modify an entire block (like background-color, border colors) of a particular block. Block Style Variations can be applied on blocks within Gutenberg and custom blocks from 3rd-party developers that a user may install. 

These [block style variations](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#block-style-variations) create classes whose names are fixed: 'is-style' followed by the name of that the developer gives to the variation class. Some of these variation names can have generic names. 
e.g. if you have a style variation named secondary, the class generated named is `.is-style-secondary`

**Because block style variations rely on a single class name and users will have multiple blocks from multiple sources on their websites, it will be inevitable that users that have style variations with the same name.** 

These styling conflicts/leaks will occur within the editor even if only one of the blocks is present on a page. 
These styling conflicts/leaks will occur across different themes if the plugins' blocks have style variations with the same name. 

**To reproduce**
1. Install Rich Tabor's coblocks (Not to pick on you Rich, it's just an example of a popular block plugin that also has somewhat common style variation names). It [has an 'alert' block with a style variation named 'success'](https://github.com/godaddy-wordpress/coblocks/blob/02f4b2cfbfe0a05392fa01c6c43340817c774674/src/blocks/alert/index.js#L42)

2. Install my example plugin. https://gitlab.com/cpl/cpl-example
The cpl-example block has a block style variation of the quote block named 'success' (https://gitlab.com/cpl/cpl-example/-/blob/master/src/index.js#L17)

3. activate both plugins 
4. create a page that contains an alert block from coblocks

This first image is when the coblocks plugin is installed., the block displays with the style that the block author has intended. This is before my plugin is activated. 
![Selection_002](https://user-images.githubusercontent.com/955351/78578764-f3446b00-77fd-11ea-870a-e4d07979859d.jpg)

After activating my plugin, you'll see a result similar to the image below; where the font-size and the border of my block variation style leaks into the coblock because they both share the same class, `.is-style-success`

![Selection_003](https://user-images.githubusercontent.com/955351/78579522-14598b80-77ff-11ea-8bf2-a8a9b79fece7.jpg)

Examples of where this occurs or was mentioned: 
https://github.com/phpbits/block-options/issues/249#issuecomment-599241478

**Comment by skorasaurus** [comment] 2020-04-03 19:31
This can be resolved by a couple ways: 

- requiring to use a namespace at the beginning of the class name 
- [ enabling Custom class names for for block style variations](https://github.com/WordPress/gutenberg/issues/11763) (#11763)

**Comment by carolinan** [comment] 2020-04-11 07:49
I agree with this, developers use a unique name space and prefix, -even for custom image sizes and script handles, so they need to adopt it for the styles and block patterns too.

**Comment by gziolo** [comment] 2020-04-26 04:35
@youknowriad, what would be your preferred approach to mitigate this issue?

**Comment by youknowriad** [comment] 2020-04-27 10:27
> enabling Custom class names for block style variations - #11763

I think one would be good to have regardless. So I'd favor this approach personally.

**Comment by peterwilsoncc** [comment] 2020-10-27 05:30
[This was discussed in the #core-editor triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1603775829037000).

It was decided to close this as a duplicate of #11763 as both can be resolved with the same approach: allowing plugin and theme developers to specify class names that include a prefix, as suggested both above and in the linked ticket.

**Closed by peterwilsoncc** 2020-10-27 05:30 UTC
Labels: [Feature] Extensibility, [Feature] Style Variations, [Status] Duplicate
