### ISSUE TITLE
Unhandled error when adding or removing columns in Text Columns

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3710] opened 2017-11-29 08:16 UTC
As reported by @mhenrylucero in https://github.com/WordPress/gutenberg/issues/219#issuecomment-347680512: 

> So I just updated the Gutenberg plugin, and tried to mess with columns in it. I created a new post and added a column layout block, and tried to increase it using the slider. Every time I try to do this, it displays the error: "This block has encountered an error and cannot be previewed."

## Steps to Reproduce (for bugs)

1. Insert a Text Columns block
2. Open block settings sidebar
3. Resize to fewer or more columns

You get an unhandled error.

![columns](https://user-images.githubusercontent.com/1204802/33364743-02c3c1ce-d4e6-11e7-922e-f07a282b189f.gif)

**Comment by mtias** [comment] 2017-11-29 11:45
Duplicate of #3709.

**Closed by mtias** 2017-11-29 11:45 UTC
Labels: [Type] Bug
