### ISSUE TITLE
The inline block inserter button is not being displayed after the initial empty paragraph loses focus

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#66632] opened 2024-10-31 10:06 UTC
### Description

The inline block inserter button - the one aligned to the right of an empty paragraph block, is present when the page first loads, but disappears after giving that paragraph block focus, and then removing focus.

I expect that an empty inline paragraph block always has a plus button to insert a block.

### Step-by-step reproduction instructions

1. Open up the post editor
2. Notice the paragraph block has a plus icon to open the block inserter menu
3. Click on the paragraph block
4. Notice that the plus icon disappears
5. Click on the title, notice that the plus icon still doesn't appear.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/d6eb30e4-1f8e-4263-84eb-d0d9e2c9203f

### Environment info

 - Using GB trunk (7d4ee569844adf6) with the supplied wp-env, no other plugins activated. TT4 theme active. I checked in Firefox 131.0.2 and Chrome 130.0.6723.71
 - I can also repro on the 19.5.0 release in a separate wp-env environment.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by ellatrix** [comment] 2024-10-31 10:26
I checked out 7d4ee569844adf697ff4deb57019e2f01200e7dd. Cannot reproduce unfortunately:

![Image](https://github.com/user-attachments/assets/0dd276e8-ebdf-4436-9bbb-28b0e9c34709)

**Comment by arthur791004** [comment] 2024-10-31 10:45
It's related to the [editorMode](https://github.com/WordPress/gutenberg/blob/3ed56acb9472eebc82d2ebad2d9b9e291f577298/packages/block-editor/src/components/block-tools/use-show-block-tools.js#L43). If you have configured the editorMode before, it's stored in your local storage on the client side or persisted_preferences on the server side so the value might be `null` instead of `edit` if it's never configured.

It seems Gutenberg might not initialize the `editorMode` on a certain situation.

**Comment by david-binda** [comment] 2024-10-31 10:55
Yeah, looks like it's related to https://github.com/WordPress/gutenberg/commit/fa8b36fb14 which is making some preferences persistent. Which could explain that folks are not able to reproduce the issue unless they reload the screen.

**Comment by arthur791004** [comment] 2024-10-31 11:34
Proposed https://github.com/WordPress/gutenberg/pull/66636 to fix it but I'm not sure whether it's the correct way.

**Comment by priethor** [comment] 2024-10-31 15:22
I can indeed reproduce it only with a fresh install and Gutenberg 19.5.

**Comment by arthur791004** [comment] 2024-11-01 02:46
> I can indeed reproduce it only with a fresh install and Gutenberg 19.5.

Yes. The issue happens only when the `persistedData.core.editorTool` is never configured because the `showEmptyBlockSideInserter` checks whether the `editorMode` is `edit` or not. If it's `null`, the block inserter would be missing.

**Comment by Mamaduka** [comment] 2024-11-05 06:20
Fixed via #66636.

**Closed as completed by Mamaduka** 2024-11-05 06:20 UTC
Labels: [Type] Bug, [Package] Editor
