### ISSUE TITLE
Extra <br/> tag on Heading blocks

### ISSUE THREAD

**Issue by yuanworks** [WordPress/gutenberg#6929] opened 2018-05-24 02:46 UTC
**Describe the bug**
Occasionally, when adding new Heading blocks, an extra `<br/>` will be added to the tag when you press shift+Enter and then delete the line:

![image](https://user-images.githubusercontent.com/3508123/40461841-ce4a929e-5f3f-11e8-86aa-e496b4152ecc.png)

**Notice from the screenshot that the heading (Future of WordPress) is only one line, and as such, it makes it impossible to delete this extra line `<br/>` using the Visual editor; the only way to delete it is using the HTML editor.**

EDIT: This also happens in regular P blocks too.

**To Reproduce**
1. Create a new Heading block.
2. Press shift+Enter and write some text to add a new line.
3. Proceed to delete the line break. the <br/> tag will stay.

**Expected behavior**
Extra `<br/>` tag should be deleted.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 60

**Comment by SuperGeniusZeb** [comment] 2018-05-24 04:27
Duplicate of #5872. Also related: #6021.

**Comment by youknowriad** [comment] 2018-05-24 10:53
Closing as duplicate

**Closed by youknowriad** 2018-05-24 10:53 UTC
