### ISSUE TITLE
Data views: Switching layout shouldn't reset filters

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#62057] opened 2024-05-28 10:46 UTC
It's unexpected that switching layout in data views resets filters.

To reproduce:

* Go to All Pages data view
* Filter by author (and select an author)
* Switch to a different layout
* Notice that the author filter is removed

This behavior is inconsistent with bundled views like 'Drafts', where the filters do persist when you change layout.

**Comment by jorgefilipecosta** [comment] 2024-08-06 10:12
This issue seems fixed on the tests I did. So I'm closing it. @jameskoster if the issue is still happening in your tests please reopen and let me know so I can debug further.

**Closed as completed by jorgefilipecosta** 2024-08-06 10:12 UTC
Labels: [Type] Bug, [Feature] DataViews
