### ISSUE TITLE
Preformatted block does not respect tabs, spaces, and blank lines

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#7836] opened 2018-07-09 18:05 UTC
**Describe the bug**

The Preformatted block's description claims to "respect your spacing and tabs", but there are several situations where it doesn't.

**To Reproduce**

1. Add a Preformatted block, then paste in the text below:

```
registerBlockType( 'foo/bar', {
	title: 'Lorum ipsum ...',
	icon: 'editor-code',
	category: 'formatting',

	// ...
} );
```

Instead of being left exactly as it should be, the tabs and blank lines are removed, resulting in:

```
registerBlockType( 'foo/bar', {
title: 'Lorum ipsum …',
icon: 'editor-code',
category: 'formatting',
// ...
} );
```

2. Paste in a single tab character at the start of a line. I'd expect to get this:

```
	title: 'Lorum ipsum …',
```

...but instead the tab is converted to `2` spaces:

```
  title: 'Lorum ipsum …',
```

3. Try pasting in 4 spaces at the start of a line. They'll be ignored entirely. The console will show entries for `Received HTML`, `Received plain text:`, and `Processed inline HTML:`, but there won't be any visual changes in the UI.

4. Manually Adjust the text so that each line has `4` leading spaces:

```
registerBlockType( 'foo/bar', {
    title: 'Lorum ipsum …',
    icon: 'editor-code',
    category: 'formatting',

    // ...
} );
```

Those changes will take effect for the current session, but once you save and reload the page, it'll be converted to this:

```
registerBlockType( 'foo/bar', {
  title: 'Lorum ipsum …',
icon: 'editor-code',
category: 'formatting',

    // ...
} );
```

Two of the spaces were removed from the `title` line, and all of them were removed from the `icon` and `category` lines.

**Desktop:**
 - OS X 10.13.5
 - Firefox Developer Edition 62.0b6
 - Gutenberg `master` @ e697f722ad1b1c5f3bcdf6b55dd0c5c22fbca5e7

**Comment by iandunn** [comment] 2018-07-10 20:56
FWIW, the `code` block doesn't exhibit the problems above, so maybe the sample text I provided wasn't the best example of this. The same problems come up with non-code text, though, like [this](https://www.asciiart.eu/movies/star-wars):

```
                    ____
                 _.' :  `._
             .-.'`.  ;   .'`.-.
    __      / : ___\ ;  /___ ; \      __
  ,'_ ""--.:__;".-.";: :".-.":__;.--"" _`,
  :' `.t""--.. '<@.`;_  ',@>` ..--""j.' `;
       `:-.._J '-.-'L__ `-- ' L_..-;'
         "-.__ ;  .-"  "-.  : __.-"
             L ' /.------.\ ' J
              "-.   "--"   .-"
             __.l"-:_JL_;-";.__
          .-j/'.;  ;""""  / .'\"-.
        .' /:`. "-.:     .-" .';  `.
     .-"  / ;  "-. "-..-" .-"  :    "-.
  .+"-.  : :      "-.__.-"      ;-._   \
  ; \  `.; ;                    : : "+. ;
  :  ;   ; ;                    : ;  : \:
 : `."-; ;  ;                  :  ;   ,/;
  ;    -: ;  :                ;  : .-"'  :
  :\     \  : ;             : \.-"      :
   ;`.    \  ; :            ;.'_..--  / ;
   :  "-.  "-:  ;          :/."      .'  :
     \       .-`.\        /t-""  ":-+.   :
      `.  .-"    `l    __/ /`. :  ; ; \  ;
        \   .-" .-"-.-"  .' .'j \  /   ;/
         \ / .-"   /.     .'.' ;_:'    ;
          :-""-.`./-.'     /    `.___.'
                \ `t  ._  /  bug :F_P:
                 "-.t-._:'
```

...although something like this does mostly work, so there must be some additional complexity to when things get mangled.

```
        =   =   =   =   =   =
	| Foo	| Bar	| Quix	|

	-------------------------

	| Cats	| Dogs	| Birds	|

	-------------------------

	| Apple	| Grape	| Pear	| 
        =   =   =   =   =   =
```

It works when some of the lines aren't intended:

```
this is some line of poetry
	where every other line
is intended to be
	indented
for stylistic purposes
	and stuff
```

...but doesn't work when they all are:

```
	this is some line of poetry
	where every single line
	is intended to be
	indented
	for stylistic purposes
	and stuff
```

I can reproduce all of the problems above with this sample:

```
this is some piece of poetry
	where the indentation increments
		with every single line

		until the midway point
	and then the following lines
match the indentation of their earlier counterparts
```

**Comment by danielbachhuber** [comment] 2018-07-11 12:34
Hi @iandunn,

Thanks for the report. This issue is a duplicate of #6917

**Closed by danielbachhuber** 2018-07-11 12:34 UTC
Labels: Blocks, [Component] Rich Text, [Type] Bug
