### ISSUE TITLE
Widgets Screen: The 'Edit' current view state appears like a button. Can the views be a toggle control?

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26229] opened 2020-10-17 00:01 UTC
**Describe the bug**
Coming from this thread - 
> Initially the ‘Edit’ looks like a button and not the selected view
> | - Currently, this is how the “active” or toggled “on” elements display in Gutenberg related screens.
<img width="682" alt="Screen Shot 2020-10-16 at 4 42 52 PM" src="https://user-images.githubusercontent.com/8726005/96323068-79711380-0fd0-11eb-842e-1012a8e107ef.png">
The Edit/Preview control are meant to be tabs to indicate the current view. They appear to be more like a button so when first using the widgets editor I attempted to click 'Edit' with no avail thinking it may be broken.
Could they be either tabs or a toggle control. In my eyes a toggle control has both the selected and unselected items tied together like a see-saw.

**To reproduce**
1. Go to the new widgets screen with Gutenberg plugin installed.
2. Click on a widget.
3. The Edit looks like a button but only Preview is clickable.

**Expected behavior**
A clear and concise denotation that the controls are not a button but instead the active state of a toggle where currently the inactive state appears non-clickable..

**Screenshots**
<img width="682" alt="Screen Shot 2020-10-16 at 4 42 52 PM" src="https://user-images.githubusercontent.com/8726005/96323068-79711380-0fd0-11eb-842e-1012a8e107ef.png">

**Editor version (please complete the following information):**
- WordPress version:  trunk
- Gutenberg version: 9.1.1

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Browser: Chrome 86.0.4240.75

**Comment by draganescu** [comment] 2020-11-10 10:57
Howdy @garretthyder thanks for opening this issue, as you mentioned it is a duplicate of #25960 so I'll close this one. 🙇

**Closed by draganescu** 2020-11-10 10:57 UTC
Labels: [Feature] Widgets Screen
