### ISSUE TITLE
Line breaks are not saved in TextareaControl

### ISSUE THREAD

**Issue by christofervas** [WordPress/gutenberg#42056] opened 2022-06-29 16:49 UTC
### Description

I have created a textarea field with the TextareaControl component but after upgrading the WordPress to version 6.0 it doesn't save the line breaks. Is this a bug or I'm missing a new update/option?

### Step-by-step reproduction instructions

Here is how I register the meta. In the following code the `dfield` is the textarea field.

```
register_post_meta( 'post', '_custom_field', [
	'type'          => 'object',
	'single'        => true,
	'auth_callback' => '__return_true',
	'sanitize_callback' => 'sanitize_text_array',
	'show_in_rest'  => [
		'schema' => [
			'type'       => 'object',
			'properties' => [
				'afield' => [
					'type' => 'string',
				],
				'bfield' => [
					'type' => 'string',
				],
				'cfield' => [
					'type' => 'string'
                                ],
                                'dfield' => [
					'type' => 'string',
                                ]
			],
		],
	],
]);
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment] 2022-07-12 17:59
I can confirm that the `TextareaControl` component itself is preserving line breaks as expected. (See the "Actions" tab in this [Storybook story](https://wordpress.github.io/gutenberg/?path=/story/components-textareacontrol--default) and enter text with line breaks into the TextareaControl.)

The problem is likely happening somewhere after that point in the chain. Are you (or anyone else) able to debug when exactly the line breaks are lost?

**Comment by priethor** [comment] 2023-06-30 12:36
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏

**Closed as completed by priethor** 2023-06-30 12:36 UTC
Labels: [Status] Needs More Info, Needs Technical Feedback
