### ISSUE TITLE
There are some extra UI elements the navigation inspector controls in WP 6.2 beta 4

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#48671] opened 2023-03-02 09:45 UTC
### Description

In WordPress beta 4 this extra panel heading is visible:

<img width="1525" alt="screenshot_2023-03-02_at_11 13 55" src="https://user-images.githubusercontent.com/107534/222391965-6f505a5f-3cf0-405f-ad11-bb9e96427ce1.png">

### Step-by-step reproduction instructions

1. Install WordPress 6.2 beta 4
2. In a block theme
3. Open a template part with a navigation block
4. Select the navigation block
5. Notice the bug in the inspector

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jameskoster** [comment] 2023-03-02 11:01
Possible duplicate of https://github.com/WordPress/gutenberg/issues/48657?

**Closed as completed** 2023-03-02 12:50 UTC
Labels: [Type] Bug, [Block] Navigation
