### ISSUE TITLE
Allow post meta to be arranged inline

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#26899] opened 2020-11-11 16:38 UTC
Many themes list post meta one after the other like so: 

![Screen Shot 2020-11-11 at 11 35 17 AM](https://user-images.githubusercontent.com/1202812/98838432-432d8500-2412-11eb-9c02-7a3194042712.png)

This isn't currently possible with the set of meta blocks we have. I can place them in a columns block, but the column width can't vary depending on the width of items. If there are two categories, it should push the tags over like so:

![Screen Shot 2020-11-11 at 11 35 44 AM](https://user-images.githubusercontent.com/1202812/98838292-0d889c00-2412-11eb-8ea8-a0cfb5f478d5.png)

These should be a way to set the meta blocks to be inline-block elements to achieve this effect.

**Comment by carolinan** [comment] 2021-02-14 10:28
I think it would be a good idea to have a post meta template part or area for this with different variations.
Perhaps meta is not a user friendly name, maybe post information?

But first template parts need to be able to use the context from the query.

**Comment by scruffian** [comment] 2021-03-29 13:37
One way to achieve this this might be to let users set "display: flex" on the group block... https://github.com/WordPress/gutenberg/issues/24473

**Comment by ntsekouras** [comment] 2021-12-29 08:40
Is this possible now with the `Row` block? Would something more be needed?

**Comment by jasmussen** [comment] 2021-12-29 10:03
Tangential to this ticket (as noted by @ntsekouras a row block might go a long way here), but one use case I'd love to see supported is to allow more direct prose in the post meta, a la `Alice in Wonderland was posted on Nov. 25th and filed in Books`. A standalone "post meta" block has been suggested before, but to put the idea out there, inline chips if at all feasible could bring a lot of flexibility:

<img width="777" alt="Meta chips" src="https://user-images.githubusercontent.com/1204802/147650103-60724eb3-965d-4e34-8366-ebba7e55297b.png">

These should conceptually not be that different from `@mentions` or the likes, but could provide flexibility that bespoke blocks could not. Even beyond post meta, what if I want to link my featured image to the post itself? What if I wanted to customize my "Read more" link to say "Read [post title] in [posts page]"?

**Comment by dsas** [comment] 2022-05-09 07:46
The post terms block on trunk (#40559) now supports a prefix and a suffix, so that's one step closer to @jasmussen's suggestion

**Comment by ellatrix** [comment] 2023-08-15 19:07
Is this a duplicate of #25448?

**Comment by jasmussen** [comment] 2023-08-16 08:17
I'd tend to think that the original issue can be partialy solved with the Row block and flex properties, and the other aspects can indeed be handled by #25448.

**Closed by jasmussen** 2023-08-16 08:17 UTC
Labels: [Type] Enhancement, Needs Design Feedback, [Feature] Themes, [Block] Post Author, [Block] Post Date, [Block] Post Tags, [Block] Post Terms, [Feature] Site Editor
