### ISSUE TITLE
some kind of link make gutenberg crash

### ISSUE THREAD

**Issue by joergschimke** [WordPress/gutenberg#9551] opened 2018-09-02 15:54 UTC
Inserting a link makes gutenberg crash. It is this one, perhaps a unusual link: 

https://www.bpb.de/wissen/Q01ETK,1,0,Das_Grundgesetz_f%FCr_die_Bundesrepublik_Deutschland.html

My workaround: I use a link shortener for that link.

Gutenberg v. 3.7.0
Wordpress v. 4.9.8
Firefox 61.0.1
Ubuntu

1. mark some text
2. Click insert link
3. paste above link
4. click arrow
5. crash

Error Message: 
Gc@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/build/editor/index.js?ver=1535894444:12:206477
yh@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:96:396
lg@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
mg@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
gc@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
vb@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
ub@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
wg@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182
Ze@https://demokratieforum-linden-limmer.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24

**Comment by caxco93** [comment] 2018-09-03 05:53
Tested and confirmed that pasting the above link is causing a crash.
Apparently it's caused by the `%FC` (ü) character, as pasting the URL without it works normally.

**Comment by talldan** [comment] 2018-09-19 15:15
It's hard to tell whether this url is malformed or not. It seems to be `decodeURI` in this line of code throwing the error, but it seems unusual we wouldn't catch earlier before the attempted render:
https://github.com/WordPress/gutenberg/blob/99ca7ea54f0ee5d0fea044b3a829147b3f7bd190/packages/editor/src/components/rich-text/format-toolbar/link-container.js#L92

If `%FC` is replaced with `%C3%B` it fixes things. If you try this link it works ok:
https://www.bpb.de/wissen/Q01ETK,1,0,Das_Grundgesetz_f%C3%BCr_die_Bundesrepublik_Deutschland.html

If this is a malformed url I think the user experience could be improved for invalid urls - the 'The editor has encountered an unexpected error.' feels major when we should be able to easily catch this type of issue

**Comment by Chintiger** [comment] 2018-09-29 08:39
If you set "%" for link URL, Gutenberg crashes immediately.

**Comment by johngodley** [comment] 2018-10-19 14:45
I've not been able to reproduce this with 4.0 (using the original URL and '%'). Can you re-test with 4.0 and see if the problem still exists for you?

**Comment by Chintiger** [comment] 2018-10-19 14:52
Confirmed fix in 4.0.

**Comment by Soean** [comment] 2018-10-20 09:01
Two confirmations of the fix. I am closing this ticket, feel free to reopen if you still can reproduce it

**Closed by Soean** 2018-10-20 09:01 UTC
Labels: Needs Technical Feedback, [Type] Bug
