### ISSUE TITLE
Gallery Block: Reordering doesn't work on mobile

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#12965] opened 2018-12-18 05:05 UTC
**Describe the bug**

When editing a gallery in the gallery modal, it's possible to drag and drop images to reorder them, when using a desktop browser. It's not possible to do the same thing on a mobile device.

This differs to classic editor behaviour, where drag and drop works on both desktop and mobile devices.

**To Reproduce**
Repeat these steps for the block editor on desktop and mobile, as well as the classic editor on desktop and mobile:
1. Create a new post.
2. Add a gallery.
3. Click/tap the Edit Gallery button.
4. Attempt to reorder the images by dragging and dropping.

**Notes**

This was [reported in the forums](https://wordpress.org/support/topic/sort-in-gallery/) as not working on an iPad, I was able to reproduce the same inconsistency on an Android phone, it seems to be a generic touch/mobile device issue.

**Comment by designsimply** [comment] 2018-12-18 06:20
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/11738 and I will rejigger the milestones (but if you'd prefer to keep this one open and close the other then I can totally swap them!).

**Closed by designsimply** 2018-12-18 06:20 UTC
Labels: Media, [Block] Gallery, [Type] Bug

**Comment by pento** [comment] 2018-12-18 06:36
Ah, "touchscreen" was the search I didn't try when I was looking for a duplicate. 🙂

Let's leave this one closed, as we already have an issue for it.
