### ISSUE TITLE
3.7: Links are sometimes not displayed with direct copy-paste

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#9482] opened 2018-08-30 19:47 UTC
Hi,

**Describe the bug**
This is related to item 7 of the call for Testing concerning Gutenberg 3.7: https://make.wordpress.org/test/2018/08/30/call-for-testing-gutenberg-3-7-pre-release

if the link could not be embedded, the link is not generated when I copy/paste the link directly in my paragraph block.

**To Reproduce**
1. In a blank new paragraph block:
2. Paste a link from some websites that can not be **embedded** in Gutenberg.
3. Wait for auto-embed process.
4. See error: Sorry this link can not be embedded.

**Expected behavior**
If the link can not be embedded it should remain a classic URL link.

**Screenshots**
![d0875a5bae93080e72f156663bdbe5bf](https://user-images.githubusercontent.com/1590998/44875285-072d0000-ac9e-11e8-8152-d927bd31ae79.gif)

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Chrome
 - WP 4.9.8
- Gutenberg 3.7 pre-release ZIP from the make/test Post
- French locale (fr_FR) (but I believe it doesn't matter here ;) )

**Comment by youknowriad** [comment] 2018-08-30 20:52
This is duplicate of #4799 and it's not a regression, it's a known bug for sometime now and won't be fixed for 3.7

**Closed by youknowriad** 2018-08-30 20:52 UTC
