### ISSUE TITLE
Drag & drop block: dropping can fail in many ways

### ISSUE THREAD

**Issue by drw158** [WordPress/gutenberg#13068] opened 2018-12-21 21:49 UTC
**Is your feature request related to a problem? Please describe.**
I'm frequently frustrated when using the drag and drop feature. It can fail in many ways and can cause unexpected behavior. Dragging to the outside margins produces no results. I realize the blue inserter line must be present for the drop to work, but there are several instances when the blue line does not show when it should. This causes frustration and causes me to repeat several drag action in a row until I get it right.

<img width="792" alt="screen shot 2018-12-21 at 3 50 40 pm" src="https://user-images.githubusercontent.com/618551/50365013-352d9d00-0538-11e9-89e4-82220c3faaa0.png">

Example:

https://cloudup.com/cqIjLo3Qvrf

Example of Dropbox Paper (notice how no matter where the cursor is dragged, there is always an option to drop it somewhere.)

https://cloudup.com/cUZ-kah2W0o

**Describe the solution you'd like**
I'd like the blue inserter line to be present most of the time, ideally 100% of the time.

related #6289

**Comment by aduth** [comment] 2019-04-29 14:06
This was raised in today's Gutenberg triage session ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C02QB2JS7/p1556546100056500

It was considered to be a duplicate of #6289 .

**Comment by aduth** [comment] 2019-04-29 14:06
Duplicate of #6289

**Closed by aduth** 2019-04-29 14:06 UTC
Labels: Drag and Drop, User Experience (UX), [Type] Enhancement
