### ISSUE TITLE
Renaming of Blocks

### ISSUE THREAD

**Issue by ewerkstatt** [WordPress/gutenberg#53011] opened 2023-07-27 07:17 UTC
## What problem does this address?

List View becomes confusing in case of many blocks within a post or page

## What is your proposed solution?

I suggest that blocks can have an additional custom name, so that the list view shows quickly the editorial structure (similar to elementor navigation and other sitebuilders). Currently the usage of an internal anchor would only work with the core editor, but the usage of an additional block editor plugin (stackable or similar) removes that functionality as they just can do it. Thus we would need something which works across all editors.
![Screenshot 2023-07-27 091630](https://github.com/WordPress/gutenberg/assets/56106102/f078d146-3ade-4c29-948d-6abb40caa9fd)

**Comment by hanneslsm** [comment] 2023-07-27 09:51
This is in discussion: https://github.com/WordPress/gutenberg/pull/42605

**Comment by Mamaduka** [comment] 2023-07-27 10:26
This is a duplicate of #42605.

**Closed as not planned by Mamaduka** 2023-07-27 10:26 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Feature] List View
