### ISSUE TITLE
Lock down TinyMCE to support blocks like Table etc.

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#2889] opened 2017-10-05 15:32 UTC

**Comment by iseulde** [comment] 2017-10-06 13:01
@androb Could you elaborate? Doesn't it already support that?

**Comment by androb** [comment] 2017-10-06 13:50
Sorry @iseulde - would love your insights actually. I had heard we needed TinyMCE to behave better when it was used on a dedicated block such as Tables or lists. But I could be wrong, it could be working just fine? :)

**Comment by iseulde** [comment] 2017-10-06 14:02
I guess I'm lacking some context here. What's behave better? Any issues or conversations to link to?

**Comment by Afraithe** [comment] 2017-10-09 18:17
Well the support for setting the base element of editing to a table (and not allow for anything outside of that) is more of a hack than a supported solution, TinyMCE was not built to do that. The thought was to make that type of limited locking (tables, lists even images) some proper support in the core, otherwise it is tricky to track down issues with this, if it isn't UNIT tested etc.

**Comment by iseulde** [comment] 2017-10-09 18:28
Ah, that makes sense, thanks! We also make use of `forced_root_block` there, which wasn't guaranteed to work properly last time I checked?

**Comment by Afraithe** [comment] 2017-10-10 09:40
That is correct, those types of implementations have been kind of experimental, so the idea here was to revisit this from the ground up and provide proper support for it.

**Comment by jeffpaul** [comment] 2018-03-07 03:39
@androb as discussed in [last week's bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1519926931000033), we're opting to close this Issue as these blocks are working as intended but if you disagree then we can discuss further what changes may be needed.

**Comment by androb** [comment] 2018-03-07 17:39
No problem @jeffpaul - sorry I have been eyes on other projects for a bit. Please reach out to us individually, on the TinyMCE Github project itself or on #core-tinymce if you have any issues we need to look at!

**Closed** 2018-03-07 17:39 UTC
Labels: [Component] TinyMCE, [Type] Question
