### ISSUE TITLE
Lightbox: Theme styles are applied to the button element

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#54940] opened 2023-09-29 15:07 UTC
### Description

Enabling Lightbox on an image block adds a button element to click on the image and an element to close the Lightbox.

Many themes, especially classic themes, apply styles to the button element, which causes unintended styles to be applied to the two buttons in the Lightbox.

Below is examples:

- Twenty Twenty One:
    - If you do not hover over the image, the image will be covered in dark blue
  - Close lightbox button has black background
- Twenty Nineteen:
  - The image turns black when you hover the mouse over it 
  - Close lightbox button has black background

I think we need a minimal style to override the theme's styles.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

Note: Warning messages displayed in screencasts are reported with #54930.

https://github.com/WordPress/gutenberg/assets/54422211/b893e1d0-0af5-4ded-87da-fd6c4a8627ec

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-10-02 16:29
@artemiomorales can you dive into this? Adding to the 6.4 board.

**Comment by artemiomorales** [comment] 2023-10-03 23:54
This is related to https://github.com/WordPress/gutenberg/issues/54682, because the close button color is not being read or determined properly in classic themes. I've begun adding a fix in the linked PR.

**Comment by oglekler** [comment] 2023-10-07 07:09
Related Core ticket: https://core.trac.wordpress.org/ticket/59513

**Comment by artemiomorales** [comment] 2023-10-11 13:05
This is a duplicate of https://github.com/WordPress/gutenberg/issues/54682 — I'll close this issue so we can consolidate conversation on just one.

**Closed as completed by artemiomorales** 2023-10-11 13:05 UTC
Labels: [Type] Bug, [Status] In Progress, Backwards Compatibility, [Block] Image, [Feature] Themes
