### ISSUE TITLE
Add google maps as an embed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3970] opened 2017-12-13 11:56 UTC
This is a user request from the forums: https://wordpress.org/support/topic/great-new-tool/#post-9765086

**Comment by overclokk** [comment] 2017-12-13 17:34
Maybe this is better in plugins and not in core bacause gmaps has a lot of customizations.

**Comment by aduth** [comment] 2017-12-14 16:59
Related: #315

**Comment by iseulde** [comment] 2018-01-25 15:53
We can do this without API keys or oEmbed. #4660 semi addresses this, but in addition to that we could create a proper embed block for Google maps where the user can paste the iframe embed code and the block just saves the iframe attributes and URL. A content filter could put this into an iframe similar to the way oEmbed works, so in other words, the Google Maps domain would be whitelisted to use iframes.

**Comment by iseulde** [comment] 2018-01-25 15:54
Anything other than the iframe embed code would be plugin material though.

**Comment by mtias** [comment] 2018-03-06 16:11
Duplicate of https://github.com/WordPress/gutenberg/issues/315.

**Closed by mtias** 2018-03-06 16:11 UTC
Labels: Blocks, New Block
