### ISSUE TITLE
Cannot insert new blocks in iOS Safari

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2602] opened 2017-08-30 08:03 UTC
When I select a block, scroll up a bit to get the plus icon, and click it, the inserted appears in a strange location. Most of it is hidden. When I try to scroll to get to the rest, it scrolls a lot slower compared to the rest of the screen, and I never really get anywhere before I hit the top of the page. It also seems that most of it is clipped off by the page boundaries.

![img_0481](https://user-images.githubusercontent.com/4710635/29861684-f15ae88e-8d61-11e7-8477-d325e2add5fb.PNG)

**Comment by iseulde** [comment] 2017-08-30 08:10
It sometimes appears in a different place:

![img_0482](https://user-images.githubusercontent.com/4710635/29861967-03b9a640-8d63-11e7-9192-967714d0ac5a.PNG)

**Comment by aduth** [comment] 2017-08-30 12:52
Duplicate of #2471

It's a tricky problem to solve because the Popover component has built-in logic to try to flip itself when exceeding bounds, but doesn't yet have the ability to know how to handle the case where there is no suitable position to open.

In my mind, I'm thinking one or more of:

- The inserter menu probably shouldn't have [offset `100vh` height for the content inserter](https://github.com/WordPress/gutenberg/blob/32647cd2075c8549d39c6982c7742270f584792e/editor/inserter/style.scss#L36)
- If we encounter the case where no suitable position exists, we should at least set a max height/width of the popover to ensure it doesn't go offscreen, then allow remaining content to be scrollable

**Closed by aduth** 2017-08-30 12:52 UTC

**Comment by BE-Webdesign** [comment] 2017-08-30 16:54
> Edit: Another, perhaps more preferable option, is to treat the inserter as a full-page modal in mobile contexts, not "attached" to the specific anchor node.

:point_up:

 👍

**Comment by karmatosed** [comment] 2017-09-07 08:57
Closing as we now have a single place to include all issues for mobile inserter in #2691
