### ISSUE TITLE
wp_editor() does not work in the meta box area

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#5365] opened 2018-03-03 09:14 UTC
## Issue Overview

In the meta box area, if we use a custom field that renders an old editor via `wp_editor()`, then that editor is broken. I understand that Gutenberg removes all the instances of TinyMCE, but the core PHP function `wp_editor()` should work as expected.

The TinyMCE editor is quite important for users. They need more "areas" to enter extra content, not just in the main editor, which can be outputted in different locations in the frontend.

## Steps to Reproduce (for bugs)

I tested with my plugin [Meta Box](https://metabox.io), but I guess it happens with any code that uses `wp_editor()`.

To reproduce the bug, please install the [Meta Box](https://wordpress.org/plugins/meta-box/) plugin. Then put the following code into `functions.php` of the active theme:

```php
add_filter( 'rwmb_meta_boxes', function( $meta_boxes ) {
    $meta_boxes[] = [
        'title' => 'Test file upload',
        'fields' => [
            [
                'id' => 'my_custom_editor',
                'type' => 'wysiwyg',
                'name' => 'Test editor',
            ]
        ],
    ];
} );
```

Then go to add a new post and see how it works.

Any solution is appreciated! Thanks for your time and hard work!

**Comment by chthonic-ds** [comment] 2018-03-03 09:33
Related https://github.com/WordPress/gutenberg/issues/3302

**Comment by youknowriad** [comment] 2018-03-06 16:03
I'm closing this as duplicate of #3302 There's a PR that might land in the future fixing this #3840

**Closed by youknowriad** 2018-03-06 16:03 UTC
