### ISSUE TITLE
Template part selecting and editing unavailable in “Write” mode

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66777] opened 2024-11-05 23:09 UTC
### Description

When the editor is set to “Design” mode, users can select template parts, which renders an “Edit” button allowing isolated editing of the template part. However, this functionality is unavailable in “Write” mode.

### Proposal

To improve consistency and user experience, enable the same functionality that exists in Design mode within Write mode. This will allow users to edit elements like the logo, site title, and navigation directly, without needing to switch modes. 

Otherwise you'll end up in the loop I've recorded below, not understanding why you can't edit what you should be able to.

 
### Visual 

https://github.com/user-attachments/assets/bd9b9487-2fc6-4fe0-8655-9f51aab91afc

**Comment by annezazu** [comment] 2024-11-06 22:13
This is a duplicate of https://github.com/WordPress/gutenberg/issues/66463. Closing this out.

**Closed as completed by annezazu** 2024-11-06 22:13 UTC
Labels: [Feature] Write mode
