### ISSUE TITLE
Inline Text Color only shows when 'de-highlighted' 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#23719] opened 2020-07-06 17:49 UTC
In my paragraph, I apply formatting to highlighted text by using the rich-text feature from the Block toolbar. All formatting is instantly applied and displayed, I select strike through and the highlighted text shows the  strike through formatting. 

When I try to do this with text color, it doesn't do that. The changed color only shows after I remove the highlighting. 

1.add paragraph block to a post
2. Highlight a partial line
3. Apply a different Text Color

**Expected behavior**
I would expect changed text color also to be applied to my highlighted text. 

Here is a video recording. https://recordit.co/kpUWYo6AZw

**Editor version:**
- WordPress version: 5.4.2
- Gutenberg plugin 8.5 RC

**Desktop:**
 - OS: MAC 10.14.6
 - Browser Chrome
 - Version 83.0.4103.116

**Comment by getdave** [comment] 2020-09-07 11:53
Thanks for raising this.

I tested this just now with WP 5.6 + Gutenberg `Version 8.9.1` and the issue is no longer in evidence.

![Screen Capture on 2020-09-07 at 12-51-46](https://user-images.githubusercontent.com/444434/92385000-017a1880-f109-11ea-8e03-abc01445a55d.gif)

Can you confirm that it's fixed for you in latest @bph? Much appreciated.

**Comment by jordesign** [comment] 2023-08-17 04:03
Agreed that I can no longer recreate this in testing - closing this as resolved.

**Closed by jordesign** 2023-08-17 04:03 UTC
Labels: [Feature] Rich Text
