### ISSUE TITLE
‘Highlight’ feature not in my toolbar

### ISSUE THREAD

**Issue by lorenzobvp** [WordPress/gutenberg#62941] opened 2024-06-27 18:12 UTC
### Description

In my editor, when I select a word within my block header, the toolbar appears, but there is no option to highlight a text within the toolbar. Either this must be a bug, or there is a way to disable it.

### Step-by-step reproduction instructions

1. go to front site editor
2. place a block, for example a header block
3. type a sentence
4. select a word within that sentence
5. go to the toolbar and click on the arrow below
6. click 'highlight' -> not there for me

### Screenshots, screen recording, code snippet

[https://imgur.com/a/HprTROE](https://imgur.com/a/HprTROE)

### Environment info

Plugins might not cause this problem. I tested it on a test website, and the highlight option was available with the same plugins installed. I'm using MailPoet, Gutenverse, Updraft, and Yoast. I'm using the latest version of WordPress, 6.5.5, and the Zeever theme from Gutenverse.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2024-06-28 05:18
> Plugins might not cause this problem. I tested it on a test website, and the highlight option was available with the same plugins installed. I'm using MailPoet, Gutenverse, Updraft, and Yoast. I'm using the latest version of WordPress, 6.5.5, and the Zeever theme from Gutenverse.

@lorenzobvp I think there really needs to be an example of this not working with no plugins installed. Otherwise it seems more likely that it is a problem with a plugin.

**Comment by Mamaduka** [comment] 2024-06-28 09:59
I can't reproduce locally. Likely, one of the plugins is removing the format.

**Comment by carolinan** [comment] 2024-07-10 06:01
I am not able to reproduce this with or without the mentioned plugins active,  - including the custom heading blocks that are added by Gutenverse.

**Comment by lorenzobvp** [comment] 2024-07-10 08:46
Hi all, I've already fixed it using custom HTML. Check this post for more information: https://wordpress.org/support/topic/different-colored-words-within-a-heading/

But I'm pretty sure it's a bug within WordPress...

**Comment by Mamaduka** [comment] 2024-07-15 07:40
@lorenzobvp, we could not reproduce the bug with fresh WP installations + plugins mentioned in the descriptions. This looks like a plugin or theme conflict with WP core.

The text highlighting is hidden when a theme doesn't provide color presets and turns off custom colors. I would recommend reaching out to the Gutenverse team with this inquiry.

Closing the issue as it's not actionable on the Gutenberg project side.

**Closed as not planned by Mamaduka** 2024-07-15 07:40 UTC
Labels: [Type] Bug, Needs Testing, [Package] Format library
