### ISSUE TITLE
Font Weight issue on Cover Image Title

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4405] opened 2018-01-11 12:06 UTC
**Issue Overview**
Font Weight difference on Cover Image Title displayed. By default cover image title displayed in font-weight 600 but after click on bold it reduces font-weight to 300.

**Steps to Reproduce (for bugs)**
1. Insert Cover Image
2. Enter Title
3. By Default it displayed bold
4. Click on Bold to make it bold but it will reduce font-weight

I am Using Linux and Google Chrome browser

## Expected Behavior
After clicking on Bold it should display in bold text.

## Current Behavior
Displayed by default in bold and after clicking on bold displayed in thin font.

Default Cover Image Title
![default-title](https://user-images.githubusercontent.com/17018981/34824773-da0ebbd0-f6f5-11e7-92c7-e37a56073d6e.png)

Bold Cover Image Title
![clickonbold](https://user-images.githubusercontent.com/17018981/34824771-d9da70dc-f6f5-11e7-8034-4ea2a538d36d.png)

**Comment by Soean** [comment] 2018-01-11 13:15
This "feature" was added in #1495 by @mtias
I agree, that this behavior is not expected by the user.

**Comment by monika-12** [comment] 2018-01-11 16:32
Yes @Soean  It's confusing for user. So let's find out the solution for it.

**Comment by mtias** [comment] 2018-03-06 15:39
This was originally disabled but we considered giving it a try. I don't feel strongly either way.

cc @jasmussen @iseulde

**Comment by jasmussen** [comment] 2018-03-07 08:57
This definitely needs to be fixed:

![cover image](https://user-images.githubusercontent.com/1204802/37082825-dfcfc38e-21ed-11e8-8e7c-b28a4b765ce4.gif)

Originally the font was always bold, and clicking "B" to make it bold did not make it _bolder still_. I believe there's simply a bug in the implementation of this that sort of inverts the behavior. Seems like we should simply switch places for the 300 and 600 font weights.

**Comment by iseulde** [comment] 2018-03-07 09:33
It’s not a bug, we just tried it this way because the heading is already
bold. Some editors do the same. The behavior is similar to having a whole
line bold and then selecting a word and clicking the button. Maybe what is
missing here to this experiment is having the button active by default for
heading, inactive when clicked.

**Comment by jasmussen** [comment] 2018-03-07 09:45
Ah, understood. 

> Maybe what is
missing here to this experiment is having the button active by default for
heading, inactive when clicked.

👍 👍 that seems like it could work.

Alternatively, I think we should just revert to the behavior where the "bold" button does nothing, because as you say, headings are usually bold. In this case the theme would at least be able to change whether a heading was bold or not, which would then surface the bold behavior. I'd be fine with that, because as you mention, this is an issue with headings, including the Heading block.

**Comment by mtias** [comment] 2018-03-07 12:37
> Alternatively, I think we should just revert to the behavior where the "bold" button does nothing, because as you say, headings are usually bold.

The original implementation didn't have the bold button there. The point being raised is that a theme could not have a cover image or heading in bold weights, and then the button just looks broken.

**Comment by SuperGeniusZeb** [comment] 2018-04-27 20:58
I guess this can be closed now that the Cover Image block is switching to use nested blocks and so it will just use a standard Heading block by default? See #5452.

**Comment by designsimply** [comment] 2018-07-19 17:59
I tested this with WordPress 4.9.7 and Gutenberg 3.2.0 and found that cover image text (in the editor) has this markup before clicking bold:

`<p class="wp-block-cover-image-text">Cover Image Text</p>`

and this markup after clicking bold:

`<p class="wp-block-cover-image-text"><strong>Cover Image Text</strong></p>`

In my test (I'm using the Atomic Blocks theme at the moment if that's relevant? also Firefox 61.0.1 on macOS 10.13.6), I did not see a difference in the font weight when clicking the bold button. I _think_ this is working as expected now so I am closing this issue, but @monika-12 would you please leave a new comment if you think the issue should stay open?

**Closed by designsimply** 2018-07-19 17:59 UTC
Labels: [Type] Bug
