### ISSUE TITLE
Block Preview: Prevent templateInsertsUpdateSelection grabbing focus

### ISSUE THREAD

**Issue by pablinos** [WordPress/gutenberg#26917] opened 2020-11-12 07:32 UTC
**Describe the bug**

This is a strange edge case but could cause more serious bugs in future.

A particular block pattern on WPCOM was using the cover block, but with no inner blocks. This meant that as it is inserted, the length of `innerBlocks` is 0 and the block is initialised with the template.

As a consequence the `templateInsertsUpdateSelection` property, if set to true, causes focus to be placed on the inner block. This is fine in the main editor block list, but if a preview of the pattern is rendered in the block inserter, then the focus is grabbed by the block in the preview. In Firefox this causes the focus to be lost when searching for a block, but in Chrome the loss of focus closes the block inserter.

**To reproduce**
1. Using the code in #26916
2. Click on on the`+` on the right side of the editor
3. Type `l`
4. Type `i` and the preview of 'List with Image' will be shown, that grabs focus, and will either close the inserter or leave it open with the focus on the inner block of the cover block in the preview

**Expected behavior**

That the focus remains on the input in the block inserter

**Screenshots**

![insert-bug](https://user-images.githubusercontent.com/96462/98907088-3498a980-24b6-11eb-8777-e6889fe8d0c6.gif)

It's a little hard to see here, but you'll notice that as I type the `i` character the blue focus border on the input is lost.

**Possible Solutions**
- Change the `templateInsertsUpdateSelection` option for the cover block
- Always have inner content for block patterns
- Make the preview aware of its context, and not grab focus
- As the `replaceInnerBlocks` code is run, check if this is a pattern and assume that no inner blocks is intentional.

**Comment by talldan** [comment] 2020-11-12 07:40
@pablinos Thanks for creating the issue. There was a similar report here - https://github.com/WordPress/gutenberg/issues/26735, I wondered if it could be related to the preview causing a focus loss, which then results in the popover closing.

Preview does use a component called `Disabled` that I think is supposed to prevent this, but it must not be working when focus is programmatically set.

**Comment by pablinos** [comment] 2020-11-12 10:03
> Preview does use a component called Disabled that I think is supposed to prevent this, but it must not be working when focus is programmatically set.

Yes, I had a look at that, and that prevents the events so components can't be tabbed into for example. This explicitly sets the focus in the code. I think it would be good to be able to work out if we were in a preview/`Disabled` component, perhaps via context? That way we could ignore the option to set the focus.

Looking at #26735 it seems to be the same problem. Which key is pressed determines the previews being displayed.

**Comment by pablinos** [comment] 2020-11-12 10:49
Actually, thinking about it, this is a specific situation where blocks are being created as part of a pattern. If there are no inner blocks in the pattern, then we need to assume that is intentional, and call `replaceInnerBlocks` with an empty list. What's happening is that as the cover block is created the lack of inner blocks is causing the default to be inserted, and that triggers the code to focus the selection.

I'm not sure where is best to fix this:

- Ensure that blocks without `InnerBlocks` in patterns remain that way
- Prevent the focus being set in preview/`Disabled` contexts.
- Both
- Something else :)

**Comment by youknowriad** [comment] 2024-10-24 12:49
I think this is fixed, I can't reproduce anymore.

**Closed by youknowriad** 2024-10-24 12:49 UTC
Labels: [Type] Bug, [Feature] Inserter
