### ISSUE TITLE
Navigation block: Allows users without permission to create navigation posts to create navigation block

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#38030] opened 2022-01-17 16:15 UTC
## What problem does this address?
Currently users that do not have the `edit_theme_options` capability can not create a navigation block within the contents of a psot / page. This is because, they are unable to make a `wp_navigation` post and save it.  However, using legacy menu / menu items, they should be able to import them and create a navigation. 

## What is your proposed solution?

Instead of saving navigation post, save the block data to the content of the current post or page.

**Comment by jordesign** [comment] 2023-10-26 23:56
Hey @spacedmonkey (and maybe @getdave ) - is this issue still the case with all the changes that have happened with the Nav Block over the last 18 months?

**Comment by getdave** [comment] 2023-10-27 06:27
It's still an issue but I think it's a duplicate of https://github.com/WordPress/gutenberg/issues/38278. I don't mind which one stays open but they seem to be the same issue.

**Comment by jordesign** [comment] 2023-10-30 00:15
Looks like there's more discussion in https://github.com/WordPress/gutenberg/issues/38278 - so I'll close this in favour of that one.

**Closed as not planned by jordesign** 2023-10-30 00:15 UTC
Labels: [Type] Enhancement, [Block] Navigation
