### ISSUE TITLE
[Widgets Screen] Text disappears when Heading Block level is changed

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/gutenberg#32753] opened 2021-06-16 22:42 UTC
## Description
When you add the Heading Block to the new Widgets Screen, 

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Go to the new Widgets Screen
2. Add the Heading Block
3. Type something in that Heading Block.
4. Change the level (for example, from the current one to h3 or h4)

## Expected behaviour
To always see what I typed in the heading block

## Actual behaviour
* The label changes back to the `Heading` placeholder
* If you click on other labels, the heading reappears

## Screenshots or screen recording (optional)

https://d.pr/v/86ONuo/Ks5y9whfvj

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Chrome 91.0.4472.77 

cc @rafaelfunchal

**Comment by talldan** [comment] 2021-06-17 01:23
This is possibly a duplicate of #32730, which has just been reopened. @eduardozulian does this only happen in the widget editor for you? #32730 seems to show this in the post editor as well.

**Comment by Mamaduka** [comment] 2021-06-17 09:11
Should be fixed in 10.9.0-RC - https://github.com/WordPress/gutenberg/issues/32730#issuecomment-862947769.

**Closed as completed by Mamaduka** 2021-06-17 09:11 UTC
Labels: Needs Testing, [Feature] Widgets Screen, [Block] Heading, [Feature] Widgets Customizer
