### ISSUE TITLE
Deleting value of dimensions resets to px

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38872] opened 2022-02-17 03:38 UTC
### Description

This came up as part of the [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324):

>When adjusting certain dimensions, say you set the variable as ’em’ or ‘rem’ or ‘vh’ or ‘vw’. Deleting/ removing the value associated with that variable, it automatically changes to ‘px’. For example: ‘Min height of cover’, ‘Border radius’ for image block:

Want to note that I found this to be similar to this issue: https://github.com/WordPress/gutenberg/issues/37856

### Step-by-step reproduction instructions

1. Add a cover block. 
2. Open the block settings.
3. Under ‘Min height of cover’ change the dimensions to ’em’ or ‘rem’ or ‘vh’ or ‘vw’ and add in a number.
4. Delete the number and notice it reverts back to px.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/154400548-27af4579-f49b-4fbb-baf8-fb373e60d442.mov

### Environment info

- WordPress 5.9
- Gutenberg 12.6
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-02-17 14:02
I can reproduce and by looking the code of the `cover` block... 🤷 So many things going on there with a lot of complexity. I'll try to see if I can find the problem and also simplify things a bit..

**Comment by richtabor** [comment] 2022-02-24 20:21
Came here to report this as well 🎯

**Comment by annezazu** [comment] 2022-03-07 23:43
@andrewserong in case you might have some insights based on this recent effort https://github.com/WordPress/gutenberg/pull/39109

**Comment by andrewserong** [comment] 2022-03-08 00:03
@annezazu thanks for the ping, I think this one is now resolved as of #39145?

**Comment by andrewserong** [comment] 2022-03-08 00:04
I'll just ping @ntsekouras since that PR says that it's part of resolving this issue, so there might have been intended follow-ups before we close out this one?

**Comment by annezazu** [comment] 2022-03-08 00:06
Wow! Totally missed that somehow 🙈 . This is what GitHub rabbit holes do to me. Will see if more follow up is needed - neat to see so much work happening to improve all of these tools either way.

**Comment by ntsekouras** [comment] 2022-03-08 16:03
>I'll just ping @ntsekouras since that PR says that it's part of resolving this issue, so there might have been intended follow-ups before we close out this one?

Yes, my fix was about `min height` of  Cover. block, but this issue's description also mentions this:

> For example: ‘Min height of cover’, ‘Border radius’ for image block:

It seems that at least for `border radius` control this is still a thing..

https://user-images.githubusercontent.com/16275880/157276005-a9d28db7-adfe-4757-90b4-444befbe85fa.mov

**Comment by andrewserong** [comment] 2022-03-17 03:48
Just adding the UI Components label, as it might be something for us to look at in the `UnitControl` component directly to see if there's a way to solve it across all instances of the component 🤔 (not sure if it's possible but just an idea).

**Closed as completed** 2022-03-21 12:22 UTC
Labels: [Type] Bug, [Feature] UI Components, [Block] Cover, [Feature] Design Tools
