### ISSUE TITLE
Third-party metaboxes?

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1076] opened 2017-06-08 11:19 UTC
Hey all! I'm really digging the new editor, but looking at the mockups of the edit post screen I was wondering what the plans are for third-party metabox integration? Initially, it seems like there's only the right column, but is it the intention that the Extended Settings foldout will also house metaboxes?

**Comment by aduth** [comment] 2017-06-08 12:20
Hey @hedgefield ! Gonna close this as a duplicate of #952 . You'll find a fair bit of related discussion there. Please do chime in.

**Closed by aduth** 2017-06-08 12:20 UTC

**Comment by hedgefield** [comment] 2017-06-08 12:22
Ah perfect thanks, didn't recognize it with that technical name in the search results :)

**Comment by aduth** [comment] 2017-06-08 12:29
Yeah, took me a moment to find it too. I added "metabox" to the title so hopefully it's a little easier for the next person to search.
