### ISSUE TITLE
Updating to Gutenberg 6.0.0 causes corruption of some blocks.

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#16335] opened 2019-06-27 18:16 UTC
**Describe the bug**
For most of my pre-existing Group blocks in the backsite I'm getting - "This block contains unexpected or invalid content", trying to resolve the issue button does not help. On the front end, all is fine - I found out the bug is showing up when the Group block has an anchor set.

**To avoid the bug**
1. Remove all anchors from the blocks and then update the Gutenberg plugin to 6.0.0.
2. And this is a weird one. if you don't do step 1 above to avoid the bug and update the Gutenberg plugin, resulting in corrupted blocks... Edit the page that has the corrupted blocks, edit to the Code Editor (not visual), and remove the first instance of the id tag you find. Update the page/post and you are done. You can now go into the visual mode and re-enter the anchor tag you deleted. The weird part for me was that even though contained a total of 5 Group blocks with anchors set to them, just removing the id (anchor) of just the first Group block, fixed all of them...

**Comment by youknowriad** [comment] 2019-06-27 18:19
Duplicate of #16328

**Closed by youknowriad** 2019-06-27 18:19 UTC
