### ISSUE TITLE
Impossible to interact with block toolbars on Firefox

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#25535] opened 2020-09-22 15:52 UTC
On any block and any theme, just trying to hover/edit a block it's impossible to interract with the block's toolbar. As soon as I try, it disappears.

Investigated using `git bisect`, the issue is a result of https://github.com/WordPress/gutenberg/pull/23034

**To reproduce**
1. Add a paragraph, header or any other block
2. Try to hover its toolbar

**Screenshots**
![Peek 2020-09-22 18-46](https://user-images.githubusercontent.com/588688/93906011-52426180-fd04-11ea-82f6-0384ccec60ca.gif)

**Editor version:**
- WordPress version: **5.6-alpha-49031**
- Gutenberg version: master branch, currently on https://github.com/WordPress/gutenberg/tree/19be5f0bc01e7b972f9d6f15f19e17649bd22e1c

**Desktop:**
 - OS: Pop!_OS (for all intents and purposes Ubuntu)
 - Browser Firefox 80.0.1

**Comment by ZebulanStanphill** [comment] 2020-09-23 02:22
I can confirm this is an issue. Tested on Firefox 80.0.1 (64-bit). It's not happening on Chromium.

**Comment by talldan** [comment] 2020-09-23 05:25
Duplicate of #25526

**Closed by talldan** 2020-09-23 05:25 UTC
Labels: Browser Issues, [Priority] High, [Type] Bug, [Type] Regression
