### ISSUE TITLE
Inspector is hidden when inserter is open and stays hidden afterwards

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22525] opened 2020-05-21 14:31 UTC
**Describe the bug**

**To reproduce**
1. Open a post
2. Add some content (text, images)
3. Open the inspector and select a block
4. Open the block inserter
5. Observe the inspector is now closed
6. Close the inserter
7. Observe the inspector is still closed

**Expected behavior**
I expect that if something closes something else, closing the something that closed the something else will open the closed something else back,

**Screenshots**
![sidebars](https://user-images.githubusercontent.com/107534/82569372-d33bf180-9b88-11ea-9d54-d628e116c5bf.gif)

**Comment by paaljoachim** [comment] 2020-05-26 17:11
We triaged this issue during the [Gutenberg Design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1590510060072900)

We noticed the behavior in the smaller browser window.
Settings sidebar is open. Clicking to open the Block Inspector closes the Settings sidebar.
Clicking to close the Block Inspector should reopen the Settings sidebar.
For consistency the sidebar should reopen.

**Comment by jasmussen** [comment] 2020-05-27 11:35
Thank you for the renewed attention on this one!

I'm actually going to close it as "working as intended".

- When the viewport is small, less than 600px, any open sidebar gets closed and from then on behaves as modal.
- When the viewport is medium, more than 600px but less than 1440px, the sidebar gets closed when the inserter gets opened, to preserve space, and not reopened.
- When the viewport is large, more than 1440px, the sidebar isn't touched.

2 is what this ticket is about, but reopening something that was closed is not a simple heuristic — what if the user had a Yoast sidebar open? In that vein, this is working as intended.

**Closed by jasmussen** 2020-05-27 11:35 UTC
Labels: [Feature] Inserter, [Feature] Inspector Controls

**Comment by paaljoachim** [comment] 2020-06-11 16:28
A comment from @talldan here:
https://github.com/WordPress/gutenberg/issues/22525
"I notice at the moment when opening the inserter menu on narrower screens, the right hand sidebar closes, but then doesn't reopen when the inserter menu is closed. That could be something to improve, and would make this kind of sidebar more usable."
