### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by QinCai-rui** [WordPress/gutenberg#63727] opened 2024-07-19 03:55 UTC
### Description

Feature 'Block Editor' is not working as it doesn't load. I expect it to load within 1 minute but it still doesn't load after 5 mins. 

### Step-by-step reproduction instructions

1. Hover mouse over 'Appearance'
2. Select 'Editor'

### Screenshots, screen recording, code snippet

![截屏2024-07-19 15 51 29](https://github.com/user-attachments/assets/e4d2adee-675a-4f92-ac9a-1c23f19cb55e)

### Environment info

WordPress: 6.7-alpha-58763
- PHP: 8.2.20
- Server: Apache
- Database: mysqli (Server: 10.4.17-MariaDB / Client: mysqlnd 8.2.20)
- Browser: Edge 126.0.2592.102 (macOS)
- Theme: Twenty Twenty-Four 1.2
- MU-Plugins: None activated
- Plugins:
  * My Private Site 3.1.1
  * WordPress Beta Tester 3.5.6

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by QinCai-rui** [comment] 2024-07-19 03:57
Looks like other people are having the same issue: [https://wordpress.org/support/topic/site-editor-not-loading-from-backend/](https://wordpress.org/support/topic/site-editor-not-loading-from-backend/). I had the same issue with WP 6.6 and now am using 6.5.5 for production site.

**Comment by carolinan** [comment] 2024-07-19 06:27
I am unable to reproduce this

=== Environment
- WordPress: 6.6
- PHP: 8.2.20
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.2.20)
- Browser: Chrome 126.0.0.0, Edge 126.0.0.0
- OS: Windows 10/11
- Theme: Twenty Twenty-Four 1.2
- MU Plugins: None activated
- Plugins:
  * With and without My Private Site 3.1.1
  * Test Reports 1.1.0

**Comment by talldan** [comment] 2024-07-19 09:05
@QinCai-rui Are there any errors logged? There's some information here about how you can check - https://developer.wordpress.org/advanced-administration/debug/debug-javascript/

Even if you don't enable SCRIPT_DEBUG, the errors from the console can still be useful.

**Comment by aaronrobertshaw** [comment] 2024-07-22 01:04
I wasn't able to replicate this issue either. I tested with a few different versions of PHP, MySQL, with and without any plugins active.

In the environment info shared, it appears you have a plugin I can't test `My Private Site 3.1.1`. Can you confirm if deactivating that plugin resolves the issue?

There was an [issue](https://github.com/WordPress/gutenberg/issues/63208) earlier during the WP6.6 beta that would crash the site editor if blocks with block style variations were being deregistered via JS. However, given the version indicated in your environment info that should have had the [fix](https://github.com/WordPress/gutenberg/pull/63252).

As @talldan noted, any error message you can provide would be very helpful. If the issue has been resolved, we might be able to close this issue.

**Comment by QinCai-rui** [comment] 2024-08-18 06:48
Sorry for the reply delay. I discovered that my hosting service, [InfinityFree](https://www.infinityfree.com/), blocks some content in the Editor. I was able to resolve this issue by switching to another hosting platform, [Hack Club Nest](https://hackclub.app). Thanks guys!

**Closed as not planned** 2024-08-18 06:49 UTC
Labels: [Type] Bug, [Feature] Site Editor

**Comment by QinCai-rui** [comment] 2024-08-21 21:07
To make it clearer, WordPress versions before 6.6 worked fine on InfinityFree servers.

**Comment by aaronrobertshaw** [comment] 2024-08-22 02:53
It could be possible that InfinityFree changed what they were doing around "blocks some content in the Editor". 

Unfortunately, without extra information such as error messages or confirmation that disabling the `My Private Site 3.1.1` plugin fixes the issue, it is very difficult to debug. 

If you run into further problems, please don't hesitate to create another issue with as much information as possible. Thanks!
