### ISSUE TITLE
Close overlay menu when clicking an anchor link

### ISSUE THREAD

**Issue by JosVelasco** [WordPress/gutenberg#39585] opened 2022-03-18 16:30 UTC
## What problem does this address?
Clicking an anchor link inside an overlay menu won't close the menu in the navigation block. Anchor links work but the overlay should hide to make the content visible without having to click on the Close button.

**Comment by Trapsta** [comment] 2022-03-20 09:27
Thanks @JosVelasco for catching and reporting this. I was able to reproduce this in v12.8.1 and Chrome v99

https://user-images.githubusercontent.com/276316/159156105-fe396942-b3f3-48bc-96b5-f7ad35de2e2f.mov

Will start working on a fix

**Comment by getdave** [comment] 2022-03-21 09:29
This seems like a worthwhile issue. Thanks for raising.

**Comment by jasmussen** [comment] 2022-04-04 06:07
Potentially a duplicate of #37387.

**Closed as completed** 2022-05-03 13:41 UTC
Labels: [Type] Enhancement, Needs Dev, [Block] Navigation
