### ISSUE TITLE
Media & Text block image settings are not working properly.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#48395] opened 2023-02-24 05:28 UTC
### Description

Hello Team,

I have worked with the "Media & Text" block and I have uploaded its images and added text based on requirements. But, when I tried to set the image size for the "Media & Text" block then it was not affected and it did not change.

But, for more clearance, I took the "Image" block and uploaded my image. Then I tried to set the image size for the "Image" block and it's working as expected. 

For better understanding I prepared its video, Please see my attachment.
[Media & Text Image size issue ](https://share.cleanshot.com/0VGSWVPZrykHkkr8Gz3C)

### Step-by-step reproduction instructions

- Type / to choose a block
- Select Media & Text block
- Upload the Image and add its text
- Go to its setting and try to change "Image Size"

### Environment info

- WordPress version: 6.1.1, Gutenberg Version 15.2.0, Theme active: Twenty Twenty-Three,
- Browser: Google chrome, Version 110.0.5481.100 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS 13.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment] 2023-02-24 09:32
I am not 100% sure, but I think it is working as intended - but it is in fact super confusing. "Image size" should not be confused with "image dimensions". 
An image with the size of a Thumbnail (150x150px) could be scaled up to a 1000px image, even though it's totally pixelated then. The dimension can be changed with the "media width" setting.
However, what adds to the confusion is that when having a regular image block, the image size setting also changes the dimensions…

I personally would suggest to remove "image size" settings (or or at least move  it to the advanced tab). Does anyone really still care about what image size is selected? It looks like this old post-thumbnail behaviour was brought to the editor where it does not make any sense anymore. The best size should be rendered automatically. Users shouldn't be faced with the option of the "image size" because they get confused - they (rightfully) only care about the image dimensions.

**Comment by ghost** [comment] 2023-02-27 11:09
@viralsampat-multidots Thanks for creating the issue with a good video.

Like @HannesDev said, the actual rendered size you're seeing is being determined by the height of your text column. If you'd like a small image with some text next to it you could add a columns block and add an image to one of the columns and text to the other.

We might also choose to add a block setting that removes the 100% height and width from the media column, if you'd like that, please create a separate issue for it. I'll close this one as resolved, if you have any more questions feel free to re-open it.

**Closed as completed by ghost** 2023-02-27 11:09 UTC
