### ISSUE TITLE
[Block] Buttons: Border color does not respond to text color in FSE themes

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#43535] opened 2022-08-23 17:51 UTC
### Description

In classic themes, a button set to the style `Outline` would have a border whose color would follow the color selected for the button's text. 

In Block-based themes, the border does not respond to color selections for the Text, meaning there's no way to change the button's border color. 

### Step-by-step reproduction instructions

1. Install and activate a Block theme, like TT2
2. In a page or post, add a Buttons block
3. Set the button style to **Outline**
4. Change the colors of the block

Where in older themes we see the outline color change with the text, in block themes, the outline color doesn't respond to changes. 

### Screenshots, screen recording, code snippet

Tested with theme **TT2** here:

https://user-images.githubusercontent.com/27249804/186229241-ea9dd409-efea-4b3a-8f7d-a484a09b4d4d.mov

Have also replicated the issue in Blockbase and several other FSE themes.

### Environment info

- WordPress 6.0.1
- Gutenberg 13.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by diegosomar** [comment] 2022-08-23 21:52
Same here. In my case, in editor the border are not shown, but works fine in front page.

### Editor print (theme TT2):
![print1](https://user-images.githubusercontent.com/11670836/186272542-781752b7-fbf8-4504-9bbb-e9bae349329b.png)

> PT-BR to EN: Preenchimento = Fill | Contorno = Outline | Cor = Color | Texto = Text | Fundo = Background

### Front-page print (theme TT2):
![print2](https://user-images.githubusercontent.com/11670836/186272573-63d08898-be2c-4dc6-9ed2-381dc32410f5.png)

**Comment by glendaviesnz** [comment] 2022-08-30 05:23
Seems to be working in TT2 in editor and frontend for me:

<img width="804" alt="Screen Shot 2022-08-30 at 3 22 07 PM" src="https://user-images.githubusercontent.com/3629020/187356083-1ddcac2a-8d74-49f2-9ed4-343fbba2b4d6.png">

This is also likely to be fixed when the Button block gets broader support for border styling, eg. width and color options.

**Comment by t-hamano** [comment] 2022-09-18 13:39
This problem could be reproduced with version 13.9, but not with the latest version (14.1.0).
As @glendaviesnz mentioned, it must have been resolved by the border support and styling changes.
As shown below, the latest Gutenberg properly overrides the default `border-width:0`.

## Gutenberg 13.9

![13 9](https://user-images.githubusercontent.com/54422211/190905049-a732468c-17e0-4cfe-a965-9a57d438208a.png)

## Gutenberg 14.1.0

![latest](https://user-images.githubusercontent.com/54422211/190905052-9512dffd-667b-419f-84e6-2d3aed82bfb3.png)

Therefore, I would like to close this issue.

**Closed as completed by t-hamano** 2022-09-18 13:39 UTC
Labels: [Block] Buttons
