### ISSUE TITLE
Creating Reusable block in Twenty Twenty duplicates toolbar icons 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21577] opened 2020-04-14 13:55 UTC
**Describe the bug**
After having created a Reusable Block in Twenty Twenty the toolbar icons are duplicated. Creating another Reusable Block another set of icons are added 3x icons. Creating a 4th Reusable Block there becomes 4x toolbar icons.

**To reproduce**
1. Go to create a Reusable block. Click the 3 dots and choose "Add to Reusable blocks."
2. Click the empty paragraph block area below it.
3. Check out the paragraph toolbar.

**Expected behavior**
I expected the toolbar not to change because of adding a reusable block.

**Screenshots**
![Reusable-Block-Test](https://user-images.githubusercontent.com/5323259/79195317-581b4900-7e2e-11ea-8905-dbf2033be7e1.gif)

**Desktop (please complete the following information):**
OSX 10.15.4
Chrome
Desktop Server
Gutenberg version 7.9 RC
WordPress 5.4

I originally thought that it was the Gutenberg Forms plugin that was making this error but I am now seeing that the bug is still there even though Gutenberg Forms plugin is deactivated.
https://github.com/munirkamal/gutenberg-forms/issues/101

Others also need to test this out.

**Comment by chrisvanpatten** [comment] 2020-04-14 13:57
Looks potentially related to #19436.

**Comment by nosolosw** [comment] 2020-04-15 08:28
I can't repro this: tried with Chrome & Firefox, using the TwentyTwenty & TwentyNineteen themes, with Gutenberg 7.9RC & 7.8.

Going to leave the issue open until more people can test and confirm. Thanks for all the details of your env, that's great to debug. Until we know more about the root cause and how to reproduce it, I'm going to edit the issue title to remove the 7,9RC reference.

**Comment by jasmussen** [comment] 2020-04-16 10:00
I have reproduced it, but closing in favor of #19436 as it's definitely the same issue. Will add steps there.

**Closed by jasmussen** 2020-04-16 10:00 UTC
