### ISSUE TITLE
Image alignment left and adding a spacer

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#15099] opened 2019-04-22 08:06 UTC
**Describe the bug**
Add a few image blocks and align them to the left so that the caption shows up correctly below them. Then add a spacer block. Mine looked like this:

<img width="725" alt="Screen Shot 2019-04-22 at 10 03 55" src="https://user-images.githubusercontent.com/5323259/56490630-193a0800-64e6-11e9-99d9-6e3c750c5b60.png">

The conclusion I reach is that I have to add CSS code to get the spacer to show up below the 3 image blocks that are all aligned to the left.

How can we control when the wrap is active or not? For the last image it would be good to turn off the wrap so that I can add the spacer below the 3 images. (I can not use a gallery as each image needs to have a custom link.)

This issue seems to be very similar:
https://github.com/WordPress/gutenberg/issues/13784

**Comment by jorgefilipecosta** [comment] 2019-05-28 18:08
It seems the issue is caused because the images are floated and so the spacer just takes there space.
Given that images are behaving as they should (floating), I guess the only fix for this problem would be adding some CSS that clears the previous floats on the spacer block. Given the nature of the spacer block that change would probably make sense, in fact, using spacer blocks would become a simple way for users to apply a float clear operation. Any thoughts on this @youknowriad, @mapk?

**Comment by mapk** [comment] 2019-05-29 03:05
By adding a `clear: both;` on the spacer block, we could get it to look like this.

![Screen Shot 2019-05-28 at 8 03 37 PM](https://user-images.githubusercontent.com/617986/58526402-c0fcc280-8183-11e9-8fb7-9452b1915120.png)

It's still a little odd looking, but provides the outcome I think you're expecting.

**Comment by paaljoachim** [comment] 2019-05-29 08:52
Yeah that will help a lot!

**Closed** 2019-06-07 12:15 UTC
Labels: [Type] Bug
