### ISSUE TITLE
Add way to break out of lists

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1551] opened 2017-06-28 11:14 UTC
This came up in user tests and got me thinking how the current editor has trained people to expect to get out of lists. Could we add a way to double return out of a list block like you currently can?

Some user comments:

"I understand this is beta but it seems very limited if I can't even end a list and start another paragraph. It looks cool though and I think it'll be great when it gets more usable for real writing"

"Easy enough to do but when your on a new line of a list item (ie. you've entered text on point 2, then press enter and point 3 appears but is blank) you can't press enter again to stop the list like you can in the current editor."

**Comment by swissspidy** [comment] 2017-06-28 11:21
Closing as a duplicate of #1482.

**Closed by swissspidy** 2017-06-28 11:21 UTC
Labels: [Type] Enhancement
