### ISSUE TITLE
Quote Block: Missing Text Color Option

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17797] opened 2019-10-07 07:52 UTC
It is currently not possible to change the text color to a readable color if the quotes block overlays a dark background. This option is already available for the Heading and Paragraph block.

<img width="1192" alt="Bildschirmfoto 2019-10-07 um 09 47 44" src="https://user-images.githubusercontent.com/31563167/66293953-26a64b80-e8e8-11e9-911a-022087337e13.png">

How we can handle this?

**Comment by youknowriad** [comment] 2019-10-07 10:02
Duplicate of #8171

**Closed by youknowriad** 2019-10-07 10:02 UTC
