### ISSUE TITLE
Settings panel overflow-x scroll

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#31165] opened 2021-04-24 13:58 UTC
This happens when the Gutenberg plugin is installed and updated I think I have seen this for more than a month.

You can see unnecessary overflow-x scroll when a settings panel toggle is opened.
![Gutenberg settings panel scroll problem](https://s18.picofile.com/file/8431699784/bandicam_2021_04_24_17_50_17_907_gif.gif)

To look further it happens when overflow-y has to scroll and in codes, it is here that make this problem:
![Gutenberg settings panel scroll problem](https://s18.picofile.com/file/8431700050/1.jpg)

This fixed size makes the problem so I solved it with this CSS snippet:
```
@media (min-width: 782px) {
     .interface-complementary-area {
          /* width: 280px; */
         width: 100%;
     }

     .is-sidebar-opened .interface-interface-skeleton__sidebar {
          width: 280px;
     }
}
```

To simplify, The fixed width should be set to its wrapper, not the child [.interface-complementary-area].

The result after that snippet:
![solved](https://s18.picofile.com/file/8431700700/bandicam_2021_04_24_18_25_11_999_gif.gif)

**Comment by vdwijngaert** [comment] 2021-04-25 12:48
I can't seem to be able to reproduce this issue. Can you provide some steps to reproduce, along with information on your OS, browser and resolution?

Also, please confirm:
* All plugins except for Gutenberg have been disabled
* Active theme is set to Twenty Twentyone
* WordPress, Gutenberg and Twenty Twentyone are up-to-date

Thanks!

**Comment by amir2mi** [comment] 2021-04-25 16:55
@vdwijngaert Hi, I checked it with Chrome last version and it was OK (There was no problem), **the problem is Firefox.**
After disabling all plugins except Gutenberg and test it with Twenty Twentyone it was still there just in Firefox.

It is what happens in Win10 and Linux Firefox 88.0 (64-bit) with different sizes:
![bug in firefox88](https://s18.picofile.com/file/8431807900/bandicam_2021_04_25_21_06_33_003_gif.gif)
Tested on: Windows 10 with a 15.60-inch display that has a resolution of 1366x768 pixels.

**Comment by vdwijngaert** [comment] 2021-04-26 06:20
Problem seems to be that blink based browsers (like Chrome and Edge) add the width of the scrollbar to the container width, while Firefox does not. So in this case, as soon as the sidebar starts overflowing content, a scrollbar appears. In Chrome, the sidebar's width will grow from 281px to 296px in my case, so the sidebar width of 15px is added. This prevents the sidebar from overflowing on the x-axis. Firefox doesn't do this, resulting in the awful horizontal scrollbar. 

Related issue: https://github.com/WordPress/gutenberg/issues/29840

As far as I can tell, your proposed solution seems to fix the issue, without any obvious regressions I can spot (tested in Chrome and Firefox). Good job!

**Comment by amir2mi** [comment] 2021-04-26 12:24
Thanks, glad it helps!
What I know Firefox scrollbar behaviors are way more different from Chrome and Edge. Besides various operating systems have their own styling for scrollbars, therefore it is better to consider all possible situations like this.

**Comment by geertvdheide1** [comment] 2021-04-28 11:07
@amir2mi Thank you so much for reporting this, and offering a fix. There have been several earlier tickets relating to the sidebar's scroll behavior which got fixed, but this one in Firefox is still ongoing. I hope this gets fixed in core soon, or maybe Firefox should change their scroll logic. But for now, you are my savior.

**Closed as completed** 2021-05-25 07:11 UTC
Labels: Browser Issues
