### ISSUE TITLE
Components Popover Misalignment

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27653] opened 2020-12-10 19:26 UTC
**Original report by lflier**
https://core.trac.wordpress.org/ticket/51936

**Describe the bug**
When attempting to replace an image, there is a misalignment in the components popover such that the interface is only partly visible. It appears to be related to the "overflow-y" property of the `.components-popover .components-popover__content` selector. Functionality is severely impaired.

**Screenshots**
![popover scrolled a little to the right of the target content](https://core.trac.wordpress.org/raw-attachment/ticket/51936/Screen%20Shot%202020-12-04%20at%207.24.26%20AM.png)

Possible solution: removing `overflow-y: auto`
![popover without scrolling](https://core.trac.wordpress.org/raw-attachment/ticket/51936/Screen%20Shot%202020-12-04%20at%207.30.11%20AM.png)

**To reproduce**
1. Use Google Chrome.
2. Add an image block, and select or upload an image.
3. Activate the Replace button to open the popover, where the content may scroll away from the left end (LTR).

**Expected behavior**
Popover shows the full buttons for Open media library, Upload, and Edit URL (if horizontal scrolling is allowed, it scrolls all the way to the left/beginning).

**Editor version**
- WordPress version: 5.5.3 (still happens in 5.6)

**Comment by sabernhardt** [comment] 2020-12-10 19:29
I didn't notice this in Firefox, but I see it in Chrome (both Windows 10).

With Chrome:
- Sometimes the popover content scrolls a little, as in the screenshot.
- Sometimes it does not scroll, so you can see the full buttons.
- Sometimes the popover scrolls so far that you cannot see the buttons at all.

**Comment by simison** [comment] 2020-12-11 10:50
Same as  https://github.com/WordPress/gutenberg/issues/27186

**Comment by youknowriad** [comment] 2020-12-11 10:58
Closing as duplicate of #27186

**Closed by youknowriad** 2020-12-11 10:58 UTC
