### ISSUE TITLE
Spotify Embed works in editor, but not on front-end

### ISSUE THREAD

**Issue by waterfireprov** [WordPress/gutenberg#23371] opened 2020-06-22 18:40 UTC
**Describe the bug**
Spotify Embed works in editor, but not on front-end. In the editor I have an embed block and I have the Spotify link. The block shows Spotify player. The front-end I only see the Spotify link.

**To reproduce**
1.) In the editor, insert an embed block.
2.) Paste in Spotify link (playlist).
3.) Block renders Spotify mini-player.
4.) Update page/save changes.
5.) View front-end of site, see only the Spotify link.

**Expected behavior**
Embed block should render and show the Spotify player.

**Screenshots**
![spotify player in editor](https://user-images.githubusercontent.com/29959688/85323225-a6377300-b495-11ea-8be0-b8df82e67f82.jpg)

![spotify no work on front-end](https://user-images.githubusercontent.com/29959688/85323329-cc5d1300-b495-11ea-9efc-0448b19933e4.jpg)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default editor, no Gberg plugin.
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Chrome & Firefox
 - Version 83.0.4103.106 (Chrome) 7.7.01 (Firefox)

This used to work. I have hundreds of Spotify embeds on the website and they all used to work.

Site: https://waterfire.org/about/music-of-waterfire/august-17-2019-waterfire-music-program/

**Comment by annezazu** [comment] 2020-06-30 21:52
@waterfireprov thanks for reporting this although I'm bummed you're having issues with spotify embeds! I tried testing this using WordPress 5.4.2 (no gutenberg plugin installed and no other plugins activated) using the TwentyTwenty theme but wasn't able to replicate what you described:

<img width="1376" alt="Screen Shot 2020-06-30 at 3 49 13 PM" src="https://user-images.githubusercontent.com/26996883/86180394-e7a4cf80-bae0-11ea-9d1f-1488802f819e.png">
<img width="1364" alt="Screen Shot 2020-06-30 at 3 49 22 PM" src="https://user-images.githubusercontent.com/26996883/86180397-e8d5fc80-bae0-11ea-9a33-3ae8186af637.png">

This tells me the problem is likely a theme/plugin conflict rather than related to Gutenberg development itself. I'd recommend using [Theme Switcha](https://wordpress.org/plugins/theme-switcha/) to rule out a theme conflict to start. Hope this helps! 

Going to close this out either way since I can't replicate this in my testing environment.

**Closed by annezazu** 2020-06-30 21:52 UTC
