### ISSUE TITLE
Lifecycle methd warning

### ISSUE THREAD

**Issue by dgwyer** [WordPress/gutenberg#13006] opened 2018-12-19 09:38 UTC
**Describe the bug**
I'm seeing a lifecycle warning in the Gutenberg editor as follows:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode
    in Unknown (created by r)
    in r (created by Context.Consumer)
    in WithSelect(Component)

componentWillUpdate: Please update the following components to use componentDidUpdate instead: t
```

**To Reproduce**
1. Open Chrome dev tools with the console tab active.
2. In WordPress admin click Pages > Add New to open up the Gutenberg editor.
2. See error.

**Screenshots**
![gb-error](https://user-images.githubusercontent.com/1482075/50211802-7293fe00-0371-11e9-8f28-0b7c80f59a04.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome v70.0.3538.110
 - WordPress: 5.1-alpha-44295
- Gutenberg Plugin: 4.7.1
- Theme: Twenty Nineteen v1.0

**Additional context**
- The only active plugin running is Gutenberg v4.7.1.

**Comment by designsimply** [comment] 2018-12-19 21:39
Thank you for reporting this! Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/7897 and noting that the remaining deprecated APIs surfaced by `StrictMode` of React 16.6 are being tracked at https://github.com/WordPress/gutenberg/issues/11360.

**Closed by designsimply** 2018-12-19 21:39 UTC
Labels: Framework, [Status] Duplicate, [Type] Bug

**Comment by dgwyer** [comment] 2018-12-20 07:32
Thanks, I'll watch those tickets.
