### ISSUE TITLE
Author select not visible for editor level access

### ISSUE THREAD

**Issue by DarrenJamieson** [WordPress/gutenberg#14051] opened 2019-02-22 11:50 UTC
On the latest version of WordPress the option to add a new post and select the relevant author from a dropdown is not available for Editor level access. It is present when logged in as an admin level.

However, when you go back to the post list with editor level, you can click ‘Quick edit’ and change the author, so obviously there is no issue with editors being unable to see, and select different authors.

Is the author select something that has been accidentally left out of the ‘add post’ page for editor level users?

We need this feature for editors as we update hundreds of sites each day with hundreds of blogs, and need our editor level team to select different authors. It’s not an option to give them Admin access, nor is it feasible to have every editor go back to the post list each time to change the author that way.

**Comment by jorgefilipecosta** [comment] 2019-02-25 12:07
Hi @DarrenJamieson, thank you for submitting this issue.
I was not able to reproduce the issue on Gutenberg master and on a brand new test install of WordPress 5.1. In my tests in both cases editors had a dropdown available that allows editors to choose the author of a post:
<img width="289" alt="screenshot 2019-02-25 at 12 02 18" src="https://user-images.githubusercontent.com/11271197/53336195-8457cb80-38f5-11e9-985a-1b0e341b3519.png">

Maybe the default rules on the website the problem is happening were changed? Or perhaps some plugin is applying a change/hiding this option? Would it be possible to try disabling plugins that may impact author mechanism?
Thank you in advance.

**Comment by DarrenJamieson** [comment] 2019-02-25 16:48
Thanks for taking a look. This is really odd as this isn't what I'm seeing. We don't have any plugins affecting author select, and I've tried more than one site with the same issue. Admin users can see the Author select dropdown, whereas Editor level users cannot see it.

**Comment by andytheapedemontague** [comment] 2019-04-21 14:28
Hi,

I'm also experiencing this on 5.1.1, but for an Admin user. No ability to change an author anywhere, neither when creating a post, editing it. No plugins installed that I can image would mess with the author mechanism.


Andy

**Comment by Inwerpsel** [comment] 2020-01-03 10:12
In our case (and probably in many) this was caused by the Wordfence plugin: they added a filter on `rest_request_before_callbacks` to do additionally check in all cases if the current user has the `list_users` permission, whereas by default wordpress only checks this permission if `'edit' === $request['context']`.

see `\wordfence::jsonAPIAuthorFilter`.

You can resolve this either by giving the role of the user the `list_users` permission, or by disabling the wordfence rule. Though I'm not sure if the latter solution is safe, as the same setting for that rule also controls other rules, so it cannot be turned of independently.

**Comment by enriquesanchez** [comment] 2020-03-16 22:41
Closing this issue as there seems to be a solution. Please feel free to reopen if necessary.

**Closed by enriquesanchez** 2020-03-16 22:41 UTC
Labels: Needs Testing, [Feature] Document Settings, [Type] Help Request
