### ISSUE TITLE
Navigation editor - data is lost when menu is deselected

### ISSUE THREAD

**Issue by grzim** [WordPress/gutenberg#30424] opened 2021-03-31 20:33 UTC
## Description

When any change is made in the sidebar and they are unsaved, the user loses them all when clicks on the background (deselect block).

## Step-by-step reproduction instructions

1. Go to Navigation Editor
2. Select menu (add at least one if you don't have any)
3. Make a change in a sidebar (change a name or theme locations)
4. Click on the background
5. Select the block
6. See the changes are lost

## Expected behaviour

Data should either persist or a user should be [warned they will lose it ](https://github.com/WordPress/gutenberg/issues/30423)

## Actual behaviour
Data is lost when the block is deselected

## WordPress information
Gutenberg version: 10.3.0-rc.1

**Comment by talldan** [comment] 2021-04-01 01:13
👍 Seems to only be an issue with the Menu Locations, I couldn't reproduce this issue with the Menu Name.

**Comment by getdave** [comment] 2021-04-21 08:05
@talldan Should this be in the `PRs pending review` column?

**Comment by talldan** [comment] 2021-04-21 08:12
I've moved it to the right place and linked the relevant PR 😄

**Comment by getdave** [comment] 2021-06-29 08:04
Moving to Needs Dev as it actually needs a developer to take this on.

**Comment by Mamaduka** [comment] 2022-08-30 12:06
I'm closing this issue since the navigation screen is no longer actively developed.

Related: https://github.com/WordPress/gutenberg/issues/43620.

**Closed as completed by Mamaduka** 2022-08-30 12:06 UTC
Labels: [Type] Bug
