### ISSUE TITLE
Blockquote block - Quote style toolbar icons change relative position

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#4993] opened 2018-02-10 20:31 UTC
## Issue Overview
When using the Blockquote block the toolbar icons change their relative position when you click into Write citation...

## Steps to Reproduce (for bugs)

1. Select a Blockquote block 
2.Click on Write citation...

## Expected Behavior
Toolbar icons don't move about

## Current Behavior
They do move about - but don't move back when you return to the blockquote section.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/2474435/36066444-a85173c6-0ea1-11e8-84e3-955a62b94a37.png)
![image](https://user-images.githubusercontent.com/2474435/36066462-e20b3714-0ea1-11e8-8d7f-a8dee9d9f0de.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by paulwilde** [comment] 2018-02-11 13:12
Duplicate of #4024.

**Comment by karmatosed** [comment] 2018-02-11 20:50
Losing as duplicate.

**Closed by karmatosed** 2018-02-11 20:50 UTC
