### ISSUE TITLE
Cover and Media & Text blocks are missing Insert from URL option

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#47355] opened 2023-01-23 14:18 UTC
### Description

Adding a Cover block or a Media & Text block, the _Insert from URL_ option is not present like it is with the Image block.

A workaround is to start with an Image block, use the _Insert from URL_ option to add the image URL, and then convert the block to either a Cover or Media & Text block.

Is this intentionally missing, or is it a bug?

### Step-by-step reproduction instructions

1. Add a Cover block or a Media & Text block
2. Notice the _Insert from URL_ option is missing

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment] 2023-08-29 01:59
Spotting this is a duplicate of https://github.com/WordPress/gutenberg/issues/10853 - so will close in its favour

**Closed as not planned by jordesign** 2023-08-29 01:59 UTC
Labels: [Type] Enhancement, [Block] Cover, [Block] Media & Text
