### ISSUE TITLE
Gutenberg messed up permalink and added automatic 301 redirect

### ISSUE THREAD

**Issue by pawel-tomkiel** [WordPress/gutenberg#13508] opened 2019-01-25 18:20 UTC
I created post with permalink /008, but on edit editor changed it to /008-2. Now I can't get back to /008. Opening /008 results in 301 redirect to /008-2 😮

**To Reproduce**
1. create a page with any title
2. save draft
3. set permalink to some number (e.g. /9000)
4. save page
5. you'll see that permalink has changed to 9000-2 -> when entering /9000 you'll be 301 redirected to /9000-2

**Screenshots**
![zrzut ekranu 2019-01-25 o 19 12 22](https://user-images.githubusercontent.com/6754562/51764677-0a55dc00-20d6-11e9-8247-dbb8cb17cef0.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by pawel-tomkiel** [comment] 2019-01-25 19:06
So basically post name is saved incorrectly and later we got `redirect_canonical` with 301 in place from `./wp_includes/canonical.php` because of that

**Comment by jayhill90** [comment] 2019-01-25 23:30
Have you ensured that the database entries in that post within the posts and postmeta tables are /008 rather than /008-2?

**Comment by pawel-tomkiel** [comment] 2019-01-26 07:49
@jayhill90 - I don't know - maybe? Today I'll need to fix this. But that's incorrect behaviour in the first place. Follow my steps to reproduce this on totally new post.

**Comment by jayhill90** [comment] 2019-01-28 17:41
So are you just unable to change it back? Is there anything in your database that took the slug over?

**Comment by pawel-tomkiel** [comment] 2019-01-29 07:49
Yeah, I managed to change it only via database. And to be clear - I have no other post with name "008". Looks like it's not Gutenberg case at all - rather core is doing something weird with numeric permalinks. Can we migrate the issue?

**Comment by jayhill90** [comment] 2019-01-29 11:43
The canonical redirect is an expected part of core. There’s an action you can use to remove that functionality in your themes functions file or as a drop in plugin. I don’t believe migrating issues from Github to Trac is possible but I may be mistaken. I would recommend filing a new issue in the Core Trac if you believe that canonical redirection could be improved upon.

**Comment by youknowriad** [comment] 2019-01-29 11:45
Let's close this as it seems to work as intended. (Follow up in Trac if needed)

**Closed by youknowriad** 2019-01-29 11:45 UTC

**Comment by pawel-tomkiel** [comment] 2019-02-02 07:11
Moved to Trac: https://core.trac.wordpress.org/ticket/46172
