### ISSUE TITLE
Can't save or publish page with custom piece of code

### ISSUE THREAD

**Issue by mmki** [WordPress/gutenberg#14835] opened 2019-04-05 08:00 UTC
**Describe the bug**
I have this piece of code:

    
    <figure class="wp-block-image"><img src="https://foo.bar.com/wp-content/uploads/2019/04/mm-1030x562.jpg" alt="sh" class="wp-image-1"/></figure>
    
    
    
    <p>Test (test)</p>
    
    
    
    <p style="text-align:center"><a href="https://foo.bar.com"><strong>ZAREJESTRUJ SIĘ</strong></a></p>
    

    
    <p>Hotele, biurowce…</p>
    

I cannot publish or save it as it is. I can remove different part of this code and save it but cannot save this full piece.

**To Reproduce**
1. Copy the code
2. Open new page and paste it
3. Click 'Publish'
4. See 'Publishing failed' error

**Expected behavior**
Post should be published or saved.

**Screenshots**
https://imgur.com/a/xII76RQ

**Desktop (please complete the following information):**
 - Ubuntu 18.04 (bionic)
 - Chromium, Firefox
 - Chromium 73.0.3683.75 (Official Build) snap (64-bit), Firefox Quantum 66.0.2 (64-bit)

**Additional context**
- WP v. 5.1.1
- Can be reproduced with all plugins turned off and standard wordpress theme.

**Comment by amielucha** [comment] 2019-04-07 11:19
I could not reproduce the issue on a plain WordPress installation with Twenty Nineteen and no plugins installed.

Can you make sure you have all plugins disabled? If the issue persists, can you check if you have any errors in the browser console?

**Comment by mmki** [comment] 2019-04-08 08:27
Yes, all plugins are disabled, persist with Twenty Nineteen theme.

There is one error in console:

    api-fetch.min.js?ver=2.2.8:1 POST http://foo.bar.com/wp-json/wp/v2/pages/24461?_locale=user 403 
    (Forbidden)
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    tryCatch @ wp-polyfill.min.js?ver=7.0.0:3
    invoke @ wp-polyfill.min.js?ver=7.0.0:3
    t.(anonymous function) @ wp-polyfill.min.js?ver=7.0.0:3
    n @ api-fetch.min.js?ver=2.2.8:1
    c @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    g @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    i @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    m @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    i @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ api-fetch.min.js?ver=2.2.8:1
    _ @ api-fetch.min.js?ver=2.2.8:1
    (anonymous) @ editor.min.js?ver=9.0.11:55
    tryCatch @ wp-polyfill.min.js?ver=7.0.0:3
    invoke @ wp-polyfill.min.js?ver=7.0.0:3
    t.(anonymous function) @ wp-polyfill.min.js?ver=7.0.0:3
    r @ editor.min.js?ver=9.0.11:12
    a @ editor.min.js?ver=9.0.11:12
    Promise.then (async)
    r @ editor.min.js?ver=9.0.11:12
    a @ editor.min.js?ver=9.0.11:12
    (anonymous) @ editor.min.js?ver=9.0.11:12
    (anonymous) @ editor.min.js?ver=9.0.11:12
    (anonymous) @ editor.min.js?ver=9.0.11:55
    REQUEST_POST_UPDATE @ editor.min.js?ver=9.0.11:55
    (anonymous) @ editor.min.js?ver=9.0.11:12
    (anonymous) @ data.min.js?ver=4.2.1:1
    value @ data.min.js?ver=4.2.1:1
    onClick @ editor.min.js?ver=9.0.11:55
    Fg @ react-dom.min.js?ver=16.6.3:154
    Eg @ react-dom.min.js?ver=16.6.3:13
    Hg @ react-dom.min.js?ver=16.6.3:13
    ae @ react-dom.min.js?ver=16.6.3:15
    Ig @ react-dom.min.js?ver=16.6.3:155
    Hc @ react-dom.min.js?ver=16.6.3:15
    Jc @ react-dom.min.js?ver=16.6.3:16
    gh @ react-dom.min.js?ver=16.6.3:39
    lg @ react-dom.min.js?ver=16.6.3:148
    re @ react-dom.min.js?ver=16.6.3:23
    Xb @ react-dom.min.js?ver=16.6.3:40
    ng @ react-dom.min.js?ver=16.6.3:149
    Se @ react-dom.min.js?ver=16.6.3:40

**Comment by youknowriad** [comment] 2019-04-09 09:05
Looks like there's a REST API error, I personally can't reproduce, can you check the response of the network request, you'll most likely have more info there.

**Comment by larsonreever** [comment] 2019-04-10 05:25
make sure you have all plugins disabled. If the issue persists, you check if you have any errors in the browser console?

https://secure.wphackedhelp.com/blog/wordpress-5-gutenberg-editor/

**Comment by mmki** [comment] 2019-04-10 06:40
It seems like it is cloudflare issue:

  Request URL:http://foo.bar.com/wp-json/wp/v2/pages/24471?_locale=user
  Request method:POST
  Remote address:104.25.229.35:443
  Status code:
  403
  Version:HTTP/2.0
  Referrer Policy:strict-origin-when-cross-origin


Response headers 

  HTTP/2.0 403 Forbidden
  date: Wed, 10 Apr 2019 06:13:57 GMT
  content-type: text/html; charset=UTF-8
  x-frame-options: SAMEORIGIN
  server: cloudflare
  cf-ray: 4c5293e74f52cc7d-WAW
  content-encoding: gzip
  X-Firefox-Spdy: h2

Request headers:

  Host: foo.bar.com
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
  Accept: application/json, */*;q=0.1
  Accept-Language: en-US,en;q=0.5
  Accept-Encoding: gzip, deflate
  Referer: http://foo.bar.com/wp-admin/post.php?post=24471&action=edit
  X-WP-Nonce: 3a67556730
  X-HTTP-Method-Override: PUT
  Content-Type: application/json
  Origin: http://foo.bar.com
  Content-Length: 719
  Alt-Used: foo.bar.com:443
  Connection: keep-alive
  Cookie: *

---

Here similar request. After removing one paragraph everything works fine

  Request URL:http://foo.bar.com/wp-json/wp/v2/pages/24480?_locale=user
  Request method:POST
  Remote address:104.25.229.35:443
  Status code:
  200
  Version:HTTP/2.0
  Referrer Policy:strict-origin-when-cross-origin

Response headers

  HTTP/2.0 200 OK
  date: Wed, 10 Apr 2019 06:25:26 GMT
  content-type: application/json; charset=UTF-8
  x-robots-tag: noindex
  link: <http://foo.bar.com/wp-json/>; rel="https://api.w.org/"
  x-content-type-options: nosniff
  access-control-expose-headers: X-WP-Total, X-WP-TotalPages
  access-control-allow-headers: Authorization, Content-Type
  expires: Wed, 11 Jan 1984 05:00:00 GMT
  cache-control: no-cache, must-revalidate, max-age=0
  x-wp-nonce: 3a67556730
  allow: GET, POST, PUT, PATCH, DELETE
  access-control-allow-origin: http://foo.bar.com
  access-control-allow-methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
  access-control-allow-credentials: true
  vary: Origin
  server: cloudflare
  cf-ray: 4c52a4ba08d2cca9-WAW
  content-encoding: gzip
  X-Firefox-Spdy: h2

Request Headers

  Host: foo.bar.com
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
  Accept: application/json, */*;q=0.1
  Accept-Language: en-US,en;q=0.5
  Accept-Encoding: gzip, deflate
  Referer: http://foo.bar.com/wp-admin/post.php?post=24480&action=edit
  X-WP-Nonce: 3a67556730
  X-HTTP-Method-Override: PUT
  Content-Type: application/json
  Origin: http://foo.bar.com
  Content-Length: 524
  Alt-Used: foo.bar.com:443
  Connection: keep-alive
  Cookie: *

**Comment by youknowriad** [comment] 2019-04-10 10:06
Thanks for the update, closing as nothing actionable in Gutenberg.

**Closed by youknowriad** 2019-04-10 10:06 UTC
Labels: [Status] Needs More Info
