### ISSUE TITLE
There is so many issues need to resolve, why gutenberg has been merged into wordpress core and released?

### ISSUE THREAD

**Issue by lealife** [WordPress/gutenberg#13004] opened 2018-12-19 04:55 UTC
I don't like wordpress 5.0.1 because the Gutenberg editor is not work well. I found some issues and has been issued on https://github.com/WordPress/gutenberg/issues.
I like the classic editor, it's simple and easy to use.
I have to change my wordpress to 4.9.x

**Comment by SqTH** [comment] 2018-12-19 08:51
Hello,

You can keep WP 5.0.1 and use the old editor. Install the Classic Editor plugin, or seek help on https://wordpress.org/support/, as your issue is not a bug-related Gutenberg.

Feel free to create new issues with maximum details if it's not already listed in the issue list.

**Comment by swissspidy** [comment] 2018-12-19 14:15
> Feel free to create new issues with maximum details if it's not already listed in the issue list.

Agreed.

I'm closing this as it's not an issue itself.

**Closed by swissspidy** 2018-12-19 14:15 UTC
Labels: Feedback
