### ISSUE TITLE
Taking the Gallery Block refactor out of experimental

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#34881] opened 2021-09-16 14:26 UTC
## What problem does this address?

The refactored Gallery Block was released in Gutenberg 11.4 as an opt-in experimental flag. Since its release, [a few bugs](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+label%3A%22%5BBlock%5D+Gallery%22+label%3A%22%5BType%5D+Bug%22) have appeared but, in general, no breaking feedback has been received. However, this might be either because the refactored version is very stable or because of a lack of wider testing.
## What is your proposed solution?

We should consider moving the refactored Gallery Block out from experimental as the next step towards wider adoption and as a means to receive more organic feedback from users.

**Comment by glendaviesnz** [comment] 2021-09-16 23:12
Thanks for raising this @priethor. I think removing the experimental flag is currently dependent on two things:

- The version of the mobile apps that fixes the breaking/data loss issue with the new gallery format needs to be released across all the app platforms. @mkevins are you able to provide an update on the timelines for this?
- It turns our there is an issue with sites that may have the legacy `use_balanceTags` flag enabled. In these instances the new gallery format is invalidated when saved. There is a [patch submitted for this](https://github.com/WordPress/wordpress-develop/pull/1678) which has been flagged for the 5.9 release.

I am not sure how critical the second issue is in terms of removing the experimental flag. @mtias, @youknowriad do you have any thoughts on whether we should remove the experimental flag before a [fix is in for the breaking of the nested figures layout](https://github.com/WordPress/wordpress-develop/pull/1678) in core? I am not sure how extensive the use of this legacy flag might be, but it will certainly be a problem for any sites that have this enabled and update the gutenberg plugin to a version with the experimental flag removed.

**Comment by glendaviesnz** [comment] 2021-09-20 22:30
One option for taking the block out of experimental, while avoiding issues with legacy sites that have `useBalanceTags` set would be to replace the experimental flag with a check for `useBalanceTags`, eg. https://github.com/WordPress/gutenberg/pull/34979

**Comment by mkevins** [comment] 2021-09-21 04:52
Hi Glen :wave: :smile: 

> * The version of the mobile apps that fixes the breaking/data loss issue with the new gallery format needs to be released across all the app platforms. @mkevins are you able to provide an update on the timelines for this?

The version that has forward compatibility on the WordPress mobile apps is 18.2 (for both WordPress Android, and WordPress iOS). Regarding timelines, if we use version 18.1 as an indicator to track adoption, that was released on September 3rd, and currently has adoption ~90% on iOS, and ~80% on Android. If we assume similar roll out for the 18.2 release, we'd have the majority of users on 18.2 (or later) in a similar timeframe, so in approximately 2-3 weeks (18.2 was just released on GitHub, I believe it is available already on the App store (iOS), and will be available soon in the Play store (Android)).

Hope that helps, but let me know if you have any other questions.

**Comment by glendaviesnz** [comment] 2021-09-23 02:00
@mkevins The 11.7 release is 13 Oct, and 11.8 is 27 Oct. In the first week of Oct do you think we would be in a position to make an educated guess if 11.7 or 11.8 is the release to aim for to remove the experimental flag?

**Comment by mkevins** [comment] 2021-09-23 04:04
Hi Glen.

> In the first week of Oct do you think we would be in a position to make an educated guess if 11.7 or 11.8 is the release to aim for to remove the experimental flag?

I think we should have a good idea by then if we should lean toward delaying a release or not. Aside from any issues discovered while testing via setting the flag to `true`, one of the factors I'm interested in is what adoption looks like for the plugin releases. Do we have a ballpark on how many / how quickly users will be on the latest versions of the plugin? Though I have a feeling confounding variables would be in our favor here (e.g. bleeding edge users on web might tend to also be on the latest mobile app) this doesn't account for multi-user sites (since this is a site-level setting).

**Comment by glendaviesnz** [comment] 2021-09-23 04:33
> Do we have a ballpark on how many / how quickly users will be on the latest versions of the plugin

@priethor do we have any stats on gutenberg plugin installations by version?

**Comment by priethor** [comment] 2021-10-05 18:35
Apologies for the time it took to get the stats. This is the distribution of plugin installations by version, updated on October 4th, a few days after the 11.6 release:
![image](https://user-images.githubusercontent.com/27339341/136082442-5c844428-361a-4a19-b4c9-89b9be613af8.png)

**Comment by mkevins** [comment] 2021-10-07 05:41
A quick check of Sentry adoption figures for Android shows the following stats for rollout:

18.1: 4%

18.2: 4%
18.2.1: 32%
18.3: 42%
18.4-rc-1: 1%

Total compatible: ~ 79%

It's not clear where the other numbers are (these don't add to 100%) but I suspect they are spread over many other versions, or perhaps the metrics used to calculate adoption rates are imprecise. In any case, there are at least 4% still on incompatible versions (18.1 and earlier), so I believe it may be a bit safer to wait an additional release cycle (~2% of users could face content loss scenarios if we released now - assuming the 52% noted above is independent of mobile app version).

**Comment by glendaviesnz** [comment] 2021-10-07 20:08
Based on the mobile figures I think it makes sense to delay removal of the flag until 11.8

**Comment by priethor** [comment] 2021-10-08 12:15
Gutenberg 11.9 will be the last version included in WordPress 5.9, so I think it makes sense to target Gutenberg 11.8 with 11.9 as a buffer.

**Comment by celloexpressions** [comment] 2021-10-24 23:23
Noting that [the dev note](https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note/) does not mention anything about this being an experiment that needs to be enabled. I just spent a bunch of time testing with what I've now confirmed was the previous version of the gallery block (using 5.9-alpha with plugin version 11.7.1). Others have likely made the same mistake and confirmed that their themes/plugins are compatible with the previous version instead of the new version. 

I would suggest removing the experimental flag ASAP and also publishing an addendum to the make/core post (as a new post to trigger notifications) advising extenders to confirm that they actually tested the correct version. This may cause more issues to surface pending broader testing.

**Comment by glendaviesnz** [comment] 2021-10-25 21:16
> Noting that [the dev note](https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note/) does not mention anything about this being an experiment that needs to be enabled

Thanks for pointing this out. I thought is was mentioned there, but it was in fact only mentioned on the call for testing post. I will get the dev not updated. There is currently a delay with getting the gallery experimental flag removed due to a backwards compatibility issue with mobile app. The flag will be removed once we can determine that enough users have upgraded to compatible versions of the app.

**Comment by bph** [comment] 2021-10-25 21:25
@celloexpressions @glendaviesnz the [DevNote](https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note/#access) was updated.

**Comment by priethor** [comment] 2021-10-26 13:04
> Gutenberg 11.9 will be the last version included in WordPress 5.9, so I think it makes sense to target Gutenberg 11.8 with 11.9 as a buffer.

As @glendaviesnz mentioned, there is a delay and the current target to remove the flag is Gutenberg 11.9.

**Comment by glendaviesnz** [comment] 2021-11-01 01:10
Closed by https://github.com/WordPress/gutenberg/pull/34979

**Closed as completed by glendaviesnz** 2021-11-01 01:10 UTC
Labels: [Block] Gallery, [Type] Experimental
