### ISSUE TITLE
[widgets screen] Since 9.8.0 the widgets screen settings cog no longer opens/closes sidebar

### ISSUE THREAD

**Issue by richardtape** [WordPress/gutenberg#28402] opened 2021-01-21 17:43 UTC
## Description
Since updating to Gutenberg version 9.8.0 which includes a temporary fix for blocks not being able to save on the widgets screen (see https://github.com/WordPress/gutenberg/issues/27173), the block controls sidebar is no longer visible meaning there is no access to block-level settings for each block.

The settings cog button (traditionally in the top right hand corner on my screen) is visible, but pressing the button only changes the status of the button itself, it doesn't open (or, I guess, close) the block controls sidebar.

## Step-by-step reproduction instructions
Install version 9.8.0 of Gutenberg plugin
WordPress version 5.6
Go to wp-admin/themes.php?page=gutenberg-widgets (Or Appearance > Widgets)
Select a block -- no block sidebar is visibible
Click Settings button (cog icon) -- no sidebar appears

## Expected behaviour
When selecting a block being used on the widget screen, the block controls sidebar should open

## Actual behaviour
When selecting a block being used on the widget screen, the block controls sidebar is not visible and pressing the settings button (cog icon) does not show it.

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook Pro 16"
- Operating system: OS 10.15.7
- Browser: Chrome 87.0.4280.141

**Comment by richardtape** [comment] 2021-01-21 17:52
Immediately after submitting this, I managed to get the block sidebar panel up... it still seems super intermittent and I can't explain why it sometimes appears or disappears.

I add a list block, and some items to the list, no sidebar. clicking cog did nothing
I added an image block, uploaded an image to it, still no sidebar, clicking cog did nothing
I clicked on the auto-inserted paragraph block at the bottom of the widget area and the sidebar appeared (!)

clicking the cog settings icon now open/closed the sidebar

It's almost like the state of the sidebar wasn't listening to the focused item for some reason. i.e. when you click on the widget area itself, the sidebar disappears, but if you click on a block, the sidebar should open (if the settings cog is set to show it). But for a while after updating, nothing I did would get the sidebar to open, but after adding some blocks, it seems to now open the sidebar appropriately.

I had used an incognito window to test the behaviour reported above wasn't cookie/cache related. But it seems... ok now? Will report back as I continue to test.

**Comment by bph** [comment] 2021-01-21 21:23
I only tested this with one paragraph block, and had initial trouble getting the sidebar to open. 
I selected the paragraph block and the sidebar doesn't open automatically as it does in the post editor but when I click on the wheel it showed all paragraph settings. 

Once I clicked on the wheel, it seems to open automatically again on select. 
Then I click it again to close it. 

Next time I select the Paragraph block it wouldn't open automatically, almost like there is a show/noshow sidebar toggle on the wheel, instead of open automatically. 

I am not confident  if I explained it right, so I made a little video 
https://user-images.githubusercontent.com/39980/105414021-ef56cd80-5c04-11eb-85aa-3c0fcb904626.mp4

If feels like intended behavior, though.

**Comment by youknowriad** [comment] 2021-01-22 12:08
cc @noisysocks @talldan @kevin940726

**Comment by kevin940726** [comment] 2021-01-25 02:55
Seems like #28044 broke this. Should just be an easy fix though.

https://github.com/WordPress/gutenberg/blob/eb9e5fd675219410a87015b9cb4387b04c18ef85/packages/edit-widgets/src/components/layout/interface.js#L51

**Comment by rafaelgalani** [comment] 2021-02-03 15:24
Hey @kevin940726! Could I work on this one? And, also, sorry, since I'm the author of #28044 😓.

**Comment by kevin940726** [comment] 2021-02-03 17:17
@rafaelgalani Sure! That's perfectly fine :), everybody makes mistakes 😉. We should think how to prevent this from happening instead. Maybe adding some e2e tests would help?

**Comment by rafaelgalani** [comment] 2021-02-03 18:03
@kevin940726 Yes! 
But for most PRs like #28044 (replacing `store` name with `store` definition), no e2e tests were changed or added... Do you think this might cause other issues as well? I didn't know I was supposed to add them for this development, sorry. 😞
In the meantime, I will try to start working on this issue.

**Comment by noisysocks** [comment] 2021-02-03 23:52
@rafaelgalani: Thanks for volunteering! I'll assign you to this issue so that we know it's being worked on. Let me know if you want to be unassigned.

**Comment by kevin940726** [comment] 2021-02-04 02:19
@rafaelgalani It's up to you! It's not required to add those tests, just recommended :). Normally, we would try to add tests if there're corresponding regressions, but I totally understand that it might not be straightforward to add though. We can add them in another PR next time.

**Comment by rafaelgalani** [comment] 2021-02-05 01:34
I just had the time to give more attention to it now. But seems like #28732 already fixed it!
Anyway... I haven't seen the quoted code, but when I saw it... Sorry, really, I let that one pass... 😓

**Comment by Copons** [comment] 2021-02-05 16:04
Hi folks! I didn't know of this issue, and "accidentally" addressed it in #28732 (as mentioned by @rafaelgalani) as part of a similar fix on the site editor.
I'll go ahead and close the issue. 🙂

**Closed by Copons** 2021-02-05 16:04 UTC
Labels: Needs Testing, [Feature] Widgets Screen, [Type] Regression
