### ISSUE TITLE
Text selection weirdness

### ISSUE THREAD

**Issue by mikelinden1** [WordPress/gutenberg#37730] opened 2022-01-05 17:56 UTC
### Description

My team found a very interesting bug. Sometimes when you are selecting text in Gutenberg and you add some formatting (bold, italics, a link, etc) the text you selected changes to something else in the same paragraph.

### Step-by-step reproduction instructions

- Edit a post with paragraph blocks
- Select a paragraph block and start dragging immediately
- Select some text on the left side of the paragraph (the first two words or something similar)
- After selecting move your cursor to the left of the paragraph and then click bold

Sometimes this causes weirdness.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/13936304/148265549-04503c4f-5e97-4f1e-a512-957cc440eb58.mov

https://user-images.githubusercontent.com/13936304/148265574-fc45461d-34d7-47a5-b3a2-6fe07e0b3ab8.mov

### Environment info

- WP 5.8.2
- Google Chrome Version 96.0.4664.110
- Mac OS 12.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by DrizzlyOwl** [comment] 2022-02-14 15:40
Thanks for posting this issue, it matches exactly with the problem my client has reported. Quite difficult for me to recreate but your videos capture it exactly.

Still exists on WP 5.8.3 using Chrome 98 on Windows 10.

**Comment by skorasaurus** [comment] 2022-02-14 17:06
Hi, 

Thanks for reporting with the detailed reproduction steps and the screen recordings.

This appears to be a duplicate of https://github.com/WordPress/gutenberg/issues/33712 

Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Closed as completed by skorasaurus** 2022-02-14 17:06 UTC
Labels: Needs Testing, [Status] Duplicate
