### ISSUE TITLE
Indenting list item (li element) creates a new ordered list (ol element) instead of a new ordered list item (li)

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#28251] opened 2021-01-15 20:07 UTC
## Description

This has been a minor annoyance for our editors; when they go to add a new sub item in an ordered list, the numbering is not followed and a new ordered list is created, instead of adding the item to the existing list.

This bug is best demonstrated through this video -  https://user-images.githubusercontent.com/955351/106202151-808aee80-6187-11eb-8758-766ba2c41c5f.mp4 (especially 0:25-0:35)

## Step-by-step reproduction instructions

1. create new post
2. create list block (ordered)
3. Add 3 list elements (li)
4. indent the second element (it creates a new ol element and li element as expected; 0:20 of attached video)
6. leave the list block, and go back to it 
7. go to the end of the line of first list element, press enter (and create) to another list element  (0:29 of attached video)
8. indent the newly created list item (0:31 of attached video)

## Expected behaviour
Expected the nested ordered list numbers to change, (assign the newly created item, #1 in the list; and the existing nested list item to change to number 2)

Expected HTML to be created: 
`<li>meeting agenda item number 1 topic<ol><li>another subtopic</li><li>sub topic</li></ol></li>`

## Actual behaviour
the HTML that is created in the block is:
`<li>meeting agenda item number 1 topic<ol><li>another subtopic</li></ol><ol><li>sub topic</li></ol></li>`

a second nested ordered list is created as shown below
![Selection_034](https://user-images.githubusercontent.com/955351/104772903-36931900-5742-11eb-9651-55e21d34507e.jpg)

## Screenshots or screen recording (optional)
This is probably best articulated through this video -https://user-images.githubusercontent.com/955351/106202151-808aee80-6187-11eb-8758-766ba2c41c5f.mp4

## WordPress information
- WordPress version: 5.6
- Gutenberg version: reproducible as recently as today (2020-01-15,  built from the master branch (most recent commit 9b323e81b4a133e09b08c4e4975c933b384d45ce)
- Are all plugins except Gutenberg deactivated? Yes
- 
- reproducible on Q and twentytwentyone themes

## Device information
- Operating system: ubuntu
- Browser: both chrome and firefox

**Comment by ellatrix** [comment] 2022-07-26 18:26
Duplicate of #17052.

**Closed by ellatrix** 2022-07-26 18:26 UTC
Labels: [Block] List
