### ISSUE TITLE
Downloadeble file won't download

### ISSUE THREAD

**Issue by hlrnet** [WordPress/gutenberg#10158] opened 2018-09-25 09:07 UTC
I insert a file download block, upload a file and publish. The block is published and visible, but the file won't download.

**Comment by hlrnet** [comment] 2018-09-25 11:51
It was a series of DOCX files - a whole bunch of them inserted each one in one blick in a separate post The download link started with blob:
The downloads are vital to the very sense of the site - I deleted Gutenberg and went beck to classic editor).

**Comment by talldan** [comment] 2018-09-28 21:01
Hi @hlrnet - Could I check which browser and os you're using? I've tested on Mac OS X Chrome, and couldn't spot any issues. 

It sounds a bit like either an issue in a particular browser, or that the post was saved while the file was still being uploaded. The blob protocol indicates a temporary file object that can be used before an upload is fully completed, so it could well be the latter.

**Comment by hlrnet** [comment] 2018-09-28 21:11
Hi,
I don't know what used the users that reported the issue, but I couldn't download the attached files on no one of the browsers I have on my W10 machine (Edge, Firefox, Opera, IE). No Chrome here. And since then I deleted Gutenberg and went back to classic editor...

**Comment by hlrnet** [comment] 2018-09-28 21:32
Hi,
Howmany time would require a 30K file ? It ocurred me in nine different posts in three weeks. I can't believe I closed browsers to early three times.

**Comment by talldan** [comment] 2018-10-05 14:34
Hi @hlrnet - sorry for not being clear earlier, the issue will have happened when uploading the file, so it'd be great to know the browser/os was used to upload the file and how you're uploading the file? (i.e. drag and drop, or from a file dialog)

**Comment by hlrnet** [comment] 2018-10-05 15:42
Hi,
I used Firefox and Opera on Win10, and the file dialog.
I'm pretty sure I didn't close the tab or browser before the upload was done, but I've been thinking that maybe the renaming of the caption (the bit between <a href=""> and </a>) was quick.

**Comment by talldan** [comment] 2018-11-07 10:01
The issue above seems like it could be related to this. Autosave may have triggered during the file upload, which resulted in the blob url being saved to post content.

**Comment by youknowriad** [comment] 2019-10-02 10:00
Let's close this as a duplicate of #5936

**Closed by youknowriad** 2019-10-02 10:00 UTC
Labels: Blocks, Needs Testing
