### ISSUE TITLE
Resolution setting (size slug) missing for featured image block

### ISSUE THREAD

**Issue by butesa** [WordPress/gutenberg#65350] opened 2024-09-14 11:14 UTC
### Description

In the featured image block, there is a setting called "resolution" (internal name "sizeslug"), with can be set to "Thumbnail", "Medium", "Large" or "Full size". This setting is only visible if a featured image is assigned. Further, is the image is to small, some of the options or the complete setting is not visible.
This makes sense for editing a blog post, but not for editing a template, since the images shown in template editing are just examples.

### Step-by-step reproduction instructions

1. Install Wordpress 6.6.2
2. Create a new blog post and assign a featured image
3. Open the "Index" template in the site editor
4. Select a featured image block

Depending on which column you select, the "resolution" setting is visible or not. It should always be visible.

### Screenshots, screen recording, code snippet

![Bildschirmfoto vom 2024-09-14 12-49-03](https://github.com/user-attachments/assets/da2b88fb-7d30-4e13-9c3f-e2644497dbed)
![Bildschirmfoto vom 2024-09-14 12-49-23](https://github.com/user-attachments/assets/c15dc39e-29fd-4b2b-93c7-b5c3ebcf00c3)

### Environment info

- Wordpress 6.6.2, Theme Twenty Twenty-Four v1.2 (fresh install)
- Ubuntu 22.04.4 LTS, Firefox 115.14.0esr (64-Bit)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by akasunil** [comment] 2024-12-14 05:41
Closing this as its duplicate of https://github.com/WordPress/gutenberg/issues/50271 and there is ongoing discussion referenced issue.

**Closed as completed by akasunil** 2024-12-14 05:41 UTC
Labels: [Type] Bug, [Block] Post Featured Image
