### ISSUE TITLE
ACF (Pro) fields dont save

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3730] opened 2017-11-30 02:50 UTC
## Issue Overview
I have some test ACF Pro fields that display at the bottom of a Page. When I added content into one of the fields, a simple text field, and then clicked Update, it didn't save.

I'm raising this because #952 was just recently closed and it was stated that Custom Fields were "Feature Complete". I can't see how they can be called "Feature Complete" when they still don't save your content.

## Steps to Reproduce (for bugs)
1. Create ACF fields and display them on a Page (I have numerous fields, diaplying but I only added content into one simple text field
2. Click Update and Update

## Expected Behavior
Custom Fields should save

## Current Behavior
Custom Fields don't save

You can download the json files for the fields that I have, from here. I had two sample Field Groups set up...
https://www.dropbox.com/s/npdoeqahfqq0ps3/group_58e48c86cc51e.json?dl=0
https://www.dropbox.com/s/tb9sayjy2c34wv8/group_5911300e9f97c.json?dl=0

_Firefox Quantum 57.0
Gutenberg Version 1.8.0
macOS Sierra 10.12.1_

**Comment by youknowriad** [comment] 2017-11-30 07:37
This is a duplicate of #3277 AFAIK and #3616 should fix it for most fields.

**Comment by maddisondesigns** [comment] 2017-12-07 05:32
@youknowriad Can you please re-open this as custom field content still isn't saving. I just tried adding content into a simple text field and it didn't save, as per my original issue above.

_Gutenberg Version 1.8.1
ACF Pro Version 5.6.7_

**Comment by youknowriad** [comment] 2017-12-07 07:37
@maddisondesigns Good catch, actually it's working but only on "saved" post but not "new" posts.

**Comment by amandablum** [comment] 2018-01-08 01:24
A few more notes: 

1. custom fields used in any other part of WP than posts/pages/CPTs work fine (options pags, menu items, etc). 
2. In my case, ACF is only saving the original values the first time you save the page. You can't edit any of the fields later. 
3. Regardless of where you are where you save the initial values (classic edit or edit) if you then open the page in gutenberg, all values are lost.

**Comment by dmje** [comment] 2018-01-30 08:26
Same issue for me, latest version of Gutenberg (2.1.0) and ACF Pro (5.6.7)

**Comment by tomatillodesign** [comment] 2018-02-04 15:53
Same issue here, same latest versions.

**Comment by gubbigubbi** [comment] 2018-02-27 02:56
Just letting you all know that ACF just released an update which should fix issues with the fields not saving:
[](url)https://www.advancedcustomfields.com/blog/acf-pro-5-6-9-update/[](url)

**Comment by maddisondesigns** [comment] 2018-02-27 06:07
Have just tried out the 5.6.9 ACF Pro update and my sample are saving now too. Haven't tried every ACF field but my sample text field and repeater fields seem to be saving ok.

**Comment by pento** [comment] 2018-02-27 06:12
Awesome, thanks for the continued testing and feedback!

**Closed by pento** 2018-02-27 06:12 UTC
Labels: [Type] Bug, [Type] Plugin / Extension Conflict

**Comment by Shulidomains** [comment] 2018-08-02 09:12
I was running into a similar issue when using ACF Pro along with SiteOrigin Page Builder. After a lot of testing and troubleshooting, I figured out the problem:

Inside the PageBuilder settings, there is a checkbox for "Field Groups" under Post Types (where the page builder should appear/be active) and there is a checkbox for "Default To Page Builder Interface". If both are checked, the problem exists. If only one is checked, there doesn't seem to be an issue. 

This may not be a solution for everyone, as not everyone uses SiteOrigin or page builders for that matter. Most page builders do offer similar settings, so it's something to look out for when troubleshooting. 

Hope this was able to help someone.

**Comment by audetcameron** [comment] 2018-12-20 17:20
this is happening again....
Wordpress Version 5.0.2   ACF Pro Version 5.7.9 
![image](https://user-images.githubusercontent.com/6738453/50300190-aa727280-0451-11e9-827c-f94d97f57c9a.png)

**Comment by strarsis** [comment] 2019-02-03 19:16
I have the same issue with latest ACF PRO (5.7.10) and Gutenberg plugin (4.9.0), 
also with the warning message as above.

**Comment by guytzhak** [comment] 2020-05-07 16:30
I have the same issue with ACF PRO (5.8.9) and can't solved this

**Comment by leo277** [comment] 2020-06-05 06:53
Hi, I have updated ACF Pro to 5.8.11, and the checkbox field value is gone. Nor can I update the checkbox. 
My checkbox is in a repeater. but other repeater fields works fine. 
Is the database corrupted or something?

**Comment by leo277** [comment] 2020-06-05 07:20
I have checked, all the checkboxes values are gone. Something must be different for checkboxes. I have tried 5.8.0-beta3, still not saving

**Comment by aircrescio** [comment] 2020-06-26 15:30
Same issue with Avada Wordpress Theme. When i try to Update my post, ACF fields not saving value.

**Comment by bilalmalkoc** [comment] 2021-01-08 11:33
Same issue on 5.9.3
