### ISSUE TITLE
Caption text from Images and Galleries appear in the_excerpt() output.

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#8865] opened 2018-08-11 08:47 UTC
**Describe the bug**
When adding Caption text to a Image or a Gallery, the text itself appears on the frontend when using the_excerpt. 

**To Reproduce**
1. Create a Post
2. Give it a name
3. Add an Image block, or a Gallery block.
4. Add captions if not already there.
5. Publish.
6. Review.
7. Repeat with Classic editor to see normal behavior.

**Expected behavior**
To not show Caption text in the_excerpt() 

**Screenshots**
In this shot, you can see the first Post has a bunch of text that is output without spaces.
Except for the first sentence, this is all Caption text.
<img width="1440" alt="screen shot 2018-08-11 at 1 22 32 am" src="https://user-images.githubusercontent.com/1586037/43989836-65d573fa-9d06-11e8-89a4-dfee2377ceda.png">

This is the first post in the Admin. The first block is a Paragraph block, the second is a regular image, and the third is a Gallery block. You can see the captions.
<img width="1440" alt="screen shot 2018-08-11 at 1 40 52 am" src="https://user-images.githubusercontent.com/1586037/43989898-aab5bbdc-9d07-11e8-88c0-d795f13c1ca8.png">

This is the Classic editor for the second post. It's using the old Gallery method. The photos for that also have captions, but do not show up in the first screenshot. 
<img width="1440" alt="screen shot 2018-08-11 at 1 40 36 am" src="https://user-images.githubusercontent.com/1586037/43989900-b20979f0-9d07-11e8-8cb7-a1621579c8de.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.4
 - Browser: Chrome
 - Version: 67.0.3396.99
 - WordPress: 4.9.8
 - Gutenberg: 3.5.0

**Additional context**
- Running Multisite

**Comment by bahia0019** [comment] 2018-09-20 06:52
Confirmed with a clean install (not multisite) of WP 4.9.8 & Gutenberg 3.8.0.
Captions for images/galleries are outputting in the_excerpt()

<img width="1004" alt="screen shot 2018-09-19 at 11 47 44 pm" src="https://user-images.githubusercontent.com/1586037/45800840-f94c1880-bc66-11e8-952a-af669f0571f8.png">

**Comment by bahia0019** [comment] 2018-09-21 21:02
@designsimply 
Could it be due to <figacaption> using RichText.Content? Maybe Content not being filtered out when using the_excerpt()?

Image block:
https://github.com/WordPress/gutenberg/blob/01bb2f2a19667969ccaadff08de078cfd9858e95/packages/block-library/src/gallery/index.js#L184

Gallery block:    https://github.com/WordPress/gutenberg/blob/01bb2f2a19667969ccaadff08de078cfd9858e95/packages/block-library/src/image/index.js#L223

**Comment by mmwb** [comment] 2018-12-22 12:41
Still [experiencing this annoying feature/bug](www.mmwb.nl) with WP 5.0.2. Could it be a theme thing (Weaver Xtreme in my case)?

**Comment by mmwb** [comment] 2018-12-22 12:43
Still experiencing this annoying feature/bug with WP 5.0.2. Could it be a theme thing (Weaver Xtreme in my case)? https://www.mmwb.nl

**Comment by mmwb** [comment] 2019-05-12 18:39
Will this issue ever be solved? @ https://www.mmwb.nl/had-omar-al-bashir-zoveel-gespaard/
"Omar al-Bashir" is the caption of the image in the first part of the article. This caption is also shown in the excerpt, that I use in a slider of the newest four posts.

Excerpt = 
"Medio april 2019 werd, na 30 jaar aan de macht te zijn geweest, de Soedanese president Omar al-Bashid (1944) afgezet door het leger na maandenlange protesten door grote delen van de bevolking. Zelf kwam hij aan de macht na een staatsgreep tegen de regering van premier Sadiq al-Mahdi in 1989, waarna hij in 1993 president werd. **Omar al-Bashir** Dat bij een huiszoeking enkele dagen later ruim 6,5 miljoen euro aan contant geld werd aangetroffen, is wellicht één van de mildere …"

Bold is mine

**Comment by mmwb** [comment] 2019-06-17 19:04
For now I use a clumsy band Aid function that finds the first image in a post, takes the caption and removes it from the excerpt. On theme update I will have to repair a few lines of code.
Hope this bug will be solved any time soon.

**Comment by mmwb** [comment] 2019-06-24 14:29
Or finds the <figcaption> ... </figcaption> string(s) and removes the first one - if any - from the excerpt

**Comment by mmwb** [comment] 2020-01-26 20:19
Will this issue be solved in WP 5.4?

**Comment by skorasaurus** [comment] 2020-02-11 18:41
@mmwb ; 

I am unable to reproduce this bug using the Gutenberg 7.4 plugin and WordPress 5.3.2.. 
I've tried a couple different themes (maxwell and popper) where the_excerpt is on the front page and the caption is not included there. 
This may be a problem with your theme or using an older version of WordPress.

**Comment by mmwb** [comment] 2020-02-12 13:51
@skorasaurus 

Might be G7.4, not sure when this lands in WP. I'm using WP 5.3.2 with Weaver Xtreme theme. They assured me last June [it's not a theme thing](https://forum.weavertheme.com/forums/topic/image-caption-in-excerpt/).
Thanks for adding to the discussion / solution!

**Comment by skorasaurus** [comment] 2020-02-12 17:54
The image captions do not appear for me when using WP 5.3.2. and without gutenberg 7.4 enabled; I even double checked and made a couple posts using Gutenberg built into WP 5.3.2 and did not rrely on posts made in gutenberg 7.4. 

The image captions did appear for me in excerpts on my site when I installed and enabled the theme weaver-xtreme. 


Themes typically use get_the_excerpt and the_excerpt to obtain the excerpt for a particular post. 
when called, [the_excerpt actually just directly calls get_the_excerpt ](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/post-template.php#L379). 

get_the_excerpt checks if there's 
post_excerpt column [of a post](https://codex.wordpress.org/Function_Reference/$post) object post_excerpt is empty by default; it is only filled in when you customize a post's excerpt. 
(see the following as an example) 
![Selection_277](https://user-images.githubusercontent.com/955351/74361456-f2123700-4d94-11ea-950d-a742db869c77.png)

There's [get_the_excerpt hook then calls wp_trim_excerpt ](https://github.com/WordPress/WordPress/blob/1dbe25bc0ad45b49de25b6e670685da85e49b48c/wp-includes/default-filters.php#L185)

Then, every time that get_the_excerpt is called, [wp_trim_excerpt is also called. ](https://github.com/WordPress/WordPress/blob/1dbe25bc0ad45b49de25b6e670685da85e49b48c/wp-includes/default-filters.php#L185)

Within [wp_trim_excerpt](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/formatting.php#L3788), another function, [excerpt_remove_blocks](https://developer.wordpress.org/reference/functions/excerpt_remove_blocks/) is called. That function decides which blocks should be included and omits the image and gallery block. excerpt_remove_blocks function was introduced in WordPress 5.0 which is why what @Otto42 wrote at the time no longer applies. 

The weaver theme removes the filter of wp_trim_excerpt (line 1171 of includes/lib-content.php) a
and instead uses a custom function that does not filter out any blocks' content; (line 1145). 

I'd suggest to go back to your theme author and share the update ; and this can now be closed as a result of the implementation of excerpt_remove_blocks in WordPress 5.0.

**Comment by mmwb** [comment] 2020-02-12 18:05
Thanks again,
have similar results in local dev, using just WP 5.3.2 with themes like Astra (2.3.0) and Blocksy (1.6.15).
Will contact Weaver Xtreme again.

**Comment by mmwb** [comment] 2020-02-18 09:28
@skorasaurus
Issue solved on my side/site for now. Will be adjusted in next version of Weaver theme.
Thanks again for the guidance.

**Comment by skorasaurus** [comment] 2020-02-18 13:35
Thanks for following up @mmwb and letting us know that you're able to solve it. 

This issue can be now closed with the introduction of [excerpt_remove_blocks](https://developer.wordpress.org/reference/functions/excerpt_remove_blocks/) in WP 5.0

**Comment by annezazu** [comment] 2020-06-18 19:31
Looping back just to close this issue out since it can no longer be replicated in more recent versions of Gutenberg.

**Closed by annezazu** 2020-06-18 19:31 UTC
Labels: Needs Testing, [Type] Enhancement, [Type] WP Core Bug

**Comment by FreelancermapUA** [comment] 2020-07-04 19:32
I have the same issue with Wordpress 5.4.2. and MagazinePro theme. The excerpts include caption text. All excerpts on this page (and others) include caption: https://moneysaurus.com/collectible-cars/

Would be thankful for suggestions on how to get rid of captions there.

**Comment by annezazu** [comment] 2020-07-07 14:48
@FreelancermapUA can you try following the guidance given above by @skorasaurus around contacting the MagazinePro theme author?

**Comment by FreelancermapUA** [comment] 2020-07-07 14:55
@annnezazu: I will contact the MagazinePro theme author about this. Thanks!
