### ISSUE TITLE
Site Editor: Hide appender in non-empty documents

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36827] opened 2021-11-24 15:19 UTC
The appender inserter that appears at the root level of the document degrades the site editing experience, particularly when focussing on a template part:

<img width="1534" alt="Screenshot 2021-11-24 at 15 12 28" src="https://user-images.githubusercontent.com/846565/143264687-478ff4ca-4db7-4ad1-b9e9-65077372cae3.png">

The white space in the screenshot above is caused by the appender inserter.

Since template composition is generally a less linear flow than authoring a post or a page, having an appender at the bottom of the document flow feels a little arbitrary. I don't think we would miss it if removed, and the result would be a more accurate representation of the document on the canvas:

<img width="1532" alt="Screenshot 2021-11-24 at 15 18 13" src="https://user-images.githubusercontent.com/846565/143265225-abe8e4f5-508b-4a3e-9f3c-730890a62821.png">

**Comment by paaljoachim** [comment] 2021-11-24 17:50
I believe that @shaunandrews and @jasmussen might want to take a look at this issue.

**Comment by shaunandrews** [comment] 2021-11-24 18:51
Agreed all around. Also better matches the reality of the partial when rendered in the template and front-end.

**Comment by jasmussen** [comment] 2021-11-25 08:02
Generally agreed, but I think it's important for us to think of a clear and intuitive heuristic for when it shows and when it doesn't, one that ideally works across every instance of the editor. I'm not sure "non-empty" is enough. I know @youknowriad is busy as always, but he recently tinkered with this behavior a bit: what are your thoughts Riad?

**Comment by youknowriad** [comment] 2021-11-25 08:51
Well right now, when you focus the template part, the inserter shouldn't be visible (per the last changes), so the issue is less present. the inserter is still visible when nothing is selected but maybe that's an acceptable tradeoff for now (we also need to think about post editor, it's the same behavior)

**Comment by youknowriad** [comment] 2021-11-25 08:52
If that behavior is a good one for everyone and a must have for 5.9, we should backport #36656 in that case.

**Comment by jameskoster** [comment] 2021-11-25 10:41
> the inserter is still visible when nothing is selected but maybe that's an acceptable tradeoff for now

This is actually the behaviour I think we need to change here. It is much less problematic in the post editor, and even the template editor to some extent, because the bottom of the document is not visually defined except by the browser window itself.

But in template part focus mode it makes it difficult to interpret whether the whitespace at the bottom of the document is added by the inserter, or some padding / margin values on the blocks in the document. Especially as when you do select a block, the inserter disappears but the space it occupies remains.

**Comment by youknowriad** [comment] 2021-11-25 10:51
@jasmussen this makes me wonder why this appender is not "absolute positioned" like the ones in container blocks? That would solve the issue I believe.

**Comment by jasmussen** [comment] 2021-11-25 10:58
Abs positioning would probably help here, yes. I think the challenge there is that it's actually _yet another appender_ that's different, but still the same, as the others, because technically it _is_ abs positioned. It's just abs positioned inside an empty paragraph that you're meant to be able to click to start typing. If that empty paragraph wasn't there, the appender wouldn't be either. I've referred to this particular appender as the "Trailing appender" (paragraph and plus in a box), and past conversations suggested it could be removed entirely in favor of selecting the last block and pressing Enter, as you would in most other editors. It's just unclear whether that would be intuitive in a site editing context.

One thought is to enable replace that trailing appender with allowing the sibling inserter to function after the last block. 🤔

**Comment by jameskoster** [comment] 2021-11-25 11:12
> and past conversations suggested it could be removed entirely in favor of selecting the last block and pressing Enter, as you would in most other editors. It's just unclear whether that would be intuitive in a site editing context.

That seems perfectly reasonable to me.

**Comment by mtias** [comment] 2021-11-29 12:38
We don't need a trailing inserter for these views. The main inserter in the header should already accomplish that.

**Comment by noisysocks** [comment] 2021-12-01 22:18
I'm going to leave this marked as a bug to be fixed during the 5.9 beta period as that large white area at the bottom of the canvas is not correct behaviour.

**Comment by noisysocks** [comment] 2021-12-02 00:24
I took a quick look at this and hiding the appender for templates parts doesn't fix the white gap at the bottom. The white gap comes from the Group block having a `style.spacing.margin.bottom` set to `var(--wp--custom--spacing--large, 8rem)`.

https://github.com/WordPress/twentytwentytwo/blob/trunk/parts/header-small-dark.html

I don't think we should hide this since it's a part of the template part's content? Perhaps we could change the background of the isolated template part editor to a checkered pattern so that it better indicates that "nothing" is there? (Excuse the rough mockup.)

<img width="1129" alt="Screen Shot 2021-12-02 at 11 22 50 am" src="https://user-images.githubusercontent.com/612155/144335391-6f005595-467a-4632-88bf-bd87af6ce4d4.png">

**Comment by jasmussen** [comment] 2021-12-02 09:30
Hey @noisysocks good catch, I can confirm that bottom margin comes from the theme (TwentyTwentyTwo):
![isolation](https://user-images.githubusercontent.com/1204802/144394830-8c99489c-1b6a-4602-bfa3-f88851b83025.gif)

My instinct would be to accept that this is showing (I wouldn't show the checkered background, the margin is presumably there to actually push content down and let the white part show), so I personally think it's fine. I'll let @jameskoster chime in as well.

**Comment by jameskoster** [comment] 2021-12-02 11:01
Agreed, we should allow the margin to affect the canvas dimensions. 

The background is a little tricky. Effectively it _is_ transparent since the template part itself has no background color. But of course the template part is never accessed independently on the frontend, so that transparent area will always be "filled" by the background of the parent template.

All that said, can we use the "Background" color from global styles as a default? And if that is not set, use the transparent texture as a fallback.

**Comment by paaljoachim** [comment] 2021-12-02 11:18
I just checked with TT1 as my install of Twenty Twenty Two is not working correctly.

Focused Header area.

![Screenshot 2021-12-02 at 12 09 49](https://user-images.githubusercontent.com/5323259/144411203-3b695257-7c38-456c-b28a-9e35aaeceeec.jpg)

It looks like the appender is just hanging in the air so to speak. I wonder why I see it there. As I see no hanging appenders in the template I was just in before editing the header in focused mode. 

Deselecting the layout an appender should not be seen. As it should just show a pure layout.
Hovering over specific areas appenders are seen.
Clicking into Paragraph or empty paragraph block areas the appender is seen.

**Comment by shaunandrews** [comment] 2021-12-02 16:23
Regardless of any margins added by the theme, I still think it makes sense to remove the appender. If we ignore the margins, the appender still adds unintentional whitespace:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/191598/144460509-fa76f836-52fe-4c58-a317-81b29dfb7c51.png">

--

I do actually like the idea of the "transparent" background. If we treat it like a spacer block, with a drag handle, I think it could be fairly nice.

<img width="2150" alt="image" src="https://user-images.githubusercontent.com/191598/144461718-3ea8a4db-90ca-4694-bc46-ee1e948be004.png">

With that in mind, I do think some of these margins/paddings belong on the Header Template Part within a Template.

**Comment by jameskoster** [comment] 2021-12-02 17:34
One important consideration with the transparent texture is that it would add a lot of noise for template parts where there are no background colors present.

<img width="1204" alt="Screenshot 2021-12-02 at 17 33 31" src="https://user-images.githubusercontent.com/846565/144473707-d7a214aa-0fb4-420b-b200-95093d522e74.png">

**Comment by shaunandrews** [comment] 2021-12-02 17:48
> it would add a lot of noise for template parts where there are no background colors present.

Sorry, I wasn't suggesting it for the entire canvas — just as a way to denote the margin that exists _outside_ of the canvas; I think the canvas should default to the GS background color, with white as a fallback.

**Comment by jameskoster** [comment] 2021-12-02 17:55
Gotcha, yeah that could work well.

For the drag handle, would that just increase the margin value? I wonder how that would work if there are multiple margins. I also worry a little that folks might mis-interpret that as setting an overall height value.

**Comment by jasmussen** [comment] 2021-12-02 18:13
I may be the only one not a total fan of the photoshop transprency texture. I don't think it really adds any value since there will always be a background around content.

**Comment by paaljoachim** [comment] 2021-12-02 23:04
To me it sounds like this is becoming more complex than it need to. 
I am not fully "getting" the conversation, so I will just share from the angle I see it at.

The appender automatically adds space. I highlighted the Spacer area above it through List view. Removing the appender we can also remove the default "Paragraph block" space. As it is really not a space that exist in the layout, but it is added in automatically associated with the appender.

![Screenshot 2021-12-03 at 00 01 41](https://user-images.githubusercontent.com/5323259/144516812-c3c29835-b9a3-4458-a94b-c288c3019e3e.jpg)

**Comment by noisysocks** [comment] 2021-12-03 05:42
> Regardless of any margins added by the theme, I still think it makes sense to remove the appender. 

I agree.

> I may be the only one not a total fan of the photoshop transprency texture. I don't think it really adds any value since there will always be a background around content.

Good point.

> All that said, can we use the "Background" color from global styles as a default? And if that is not set, use the transparent texture as a fallback.

This seems simpler.

---

In the interest of iterating, how about for now we just hide the appender and set the background colour to be the same as the one defined in global styles?

**Comment by jasmussen** [comment] 2021-12-03 05:46
Sounds good to me, we can always follow up. I suspect we might be over indexing on Twenty Twenty Two’s dark background and built in bottom margin.

**Comment by jameskoster** [comment] 2021-12-03 10:27
> there will always be a background around content

This is true, but I suppose the argument is that we don't always know what the background will be. Quick example... let's take this header:

<img width="1444" alt="Screenshot 2021-12-03 at 10 09 04" src="https://user-images.githubusercontent.com/846565/144584947-76ee2c6f-4090-4626-b0ac-29f6c8ef6d78.png">

The light blue area is a Group with a bottom margin, and let's say the global `background` color is white (therefore the canvas is also white). 

Now let's say that you want a blue body background color just on your Page template. When you insert this Header template part, that white area from before will not be white, it will inherit the blue background color from the template like so:

<img width="898" alt="Screenshot 2021-12-03 at 10 15 31" src="https://user-images.githubusercontent.com/846565/144586004-0966c145-fac7-4775-8645-422a1f54aa32.png">

So the point is that the white background in isolated view may be accurate most of the time, but not _all_ of the time. The transparent texture better indicates that the background  color of the parent document will bleed through in to the template part.

The other consideration here is patterns. When viewing a header pattern like the example above in the directory, there is no `background` color to reference, so the transparent texture works better in that context too.

**Comment by paaljoachim** [comment] 2021-12-03 16:46
I opened the following issue in the repo for Twenty Twenty Two:
Empty gaps seen in the site editor.
https://github.com/WordPress/twentytwentytwo/issues/272

**Comment by noisysocks** [comment] 2021-12-08 04:59
> In the interest of iterating, how about for now we just hide the appender and set the background colour to be the same as the one defined in global styles?

I've opened https://github.com/WordPress/gutenberg/pull/37213 which does this.

While tinkering with it I realised that fixing https://github.com/WordPress/gutenberg/issues/36141 will also help here.

**Closed as completed** 2021-12-08 23:33 UTC
Labels: [Type] Bug, [Status] In Progress, Needs Dev, [Feature] Site Editor
