### ISSUE TITLE
Mix <li> with other block type

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#12561] opened 2018-12-03 20:20 UTC
Hello,
I'like to have a list with code or / and paragraph.
I open a list and write my 1st item then pressing enter will add an new item.
If I want to a "p" or a "code" it will automatically close the list

Example:
I'd like to have 
```<ul>
<li>some text</li>
<code>some code</code>
<li>some new text</li>
<p>some parapgraph</p>
</ul>```

and Gutenberg editor force me to have:

```<ul>
<li>some text</li>
</ul>
<code>some code</code>
<ul>
<li>some new text</li>
</ul>
<p>some parapgraph</p>```

Testing on WP.4.9.8 and Gutenberg 4.6.1

**Comment by Soean** [comment] 2018-12-03 21:01
Hey @sebastienserre 
`code` or `p` are not allowed inside the `ul` tag you can only use `li`, see https://www.w3.org/TR/html52/grouping-content.html#the-ul-element

What you can do:
````
<ul>
  <li>some text</li>
  <li><code>some code</code></li>
  <li>more text</li>
  <li><p>A paragraph</p></li>
</ul>
````

**Comment by designsimply** [comment] 2018-12-04 00:01
@sebastienserre I'm closing this issue because it has a reply, but please let me know if we need to re-open it for any reason!

**Closed by designsimply** 2018-12-04 00:01 UTC
Labels: [Type] Help Request

**Comment by Soean** [comment] 2018-12-04 10:31
@sebastienserre 
Can you show the source code of your last screenshot? I cant reproduce it in the Classic Editor.

If you really want to use the `ul` with invalid HTML, you can use the HTML block.

**Comment by sebastienserre** [comment] 2018-12-04 10:49
the code is:
!![Code of list on old Editor](https://i.imgur.com/0eRp4cZ.png)
I made it on a WP4.9.8 without Gutenberg by pressing "maj/shift + enter" to go on new line without making a new paragraph

**Comment by Soean** [comment] 2018-12-04 10:58
Thanks, so this is valid HTML and not mixed. 
We have an open issue about this line break feature, see #11215

**Comment by sebastienserre** [comment] 2018-12-04 11:00
great ;-) so now we can close this one ;-)
