### ISSUE TITLE
Components: focus is lost from Modal on keyboard operation in Firefox

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#42652] opened 2022-07-23 03:26 UTC
### Description

In the Firefox browser, the focus sometimes goes out of the modal f you use the TAB key to move.
This issue is very unstable and seems to occur when the machine is under load or when tabs are moved at high speed.

### Step-by-step reproduction instructions

- Open one of the modal window from [the Storybook page](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default) or "Welcome Guide" of the post editor, etc.
- Press `tab` key or `tab + shift` key to change the focus in the modal window.
- Alternatively, hold down `tab` key to change the focus to fast.
- Sometimes you should see the focus goes out of the modal.

## On Post Editor

https://user-images.githubusercontent.com/54422211/180588815-2936c9ab-6831-4d9c-8a8c-b03821a1fe37.mp4

## On Storybook

https://user-images.githubusercontent.com/54422211/180588813-18444700-e618-4909-a035-76dd0a660118.mp4

### Environment info

- WordPress Version: 6.1-alpha-53579
- Gutenberg Version: 13.7.2 (with or without)
- Browser Version: Firevox 102.0.1 (64bit)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by afercia** [comment] 2022-11-21 13:23
See also the reproduction instructions on https://github.com/WordPress/gutenberg/issues/45903, closed as duplicate of this issue.

I'd like to highlight that this isn't a browser bug. The current implementation is just relying on the fact that a native browser behavior occurs with some timing that isn't predictable. As such, the change implemented in https://github.com/WordPress/gutenberg/pull/34836 seems very fragile to me.

**Closed as completed** 2022-11-24 16:22 UTC
Labels: [Type] Bug, [Focus] Accessibility (a11y), [Type] Regression
