### ISSUE TITLE
Select text across paragraphs/blocks

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#5303] opened 2018-02-28 11:24 UTC
When writing something a couple of paragraphs long, it is useful to be able to quickly edit back and forth your thoughts, until the text is sound.

This GIF compares the interaction between classic editor and Gutenberg in selecting text across blocks/paragraphs:

![select-across-blocks](https://user-images.githubusercontent.com/583546/36784811-1809c9d8-1c81-11e8-8c4b-cf86e146b97a.gif)

Gutenberg selects the whole blocks themselves, not the text. For the writing flow, this is sub-optimal, so I thought I would fill a ticket for us to be aware of this. Feel free to close it if optimizing for the block selection use case is a design decision.

**Comment by jasmussen** [comment] 2018-02-28 11:30
Closing this as a duplicate of #3629, with some of the reasoning provided in [this comment](https://github.com/WordPress/gutenberg/issues/3629#issuecomment-346840261).

**Closed by jasmussen** 2018-02-28 11:30 UTC
