### ISSUE TITLE
Embeds sometimes appear with lots of additional space underneath

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#27720] opened 2020-12-14 16:02 UTC
**Describe the bug**

Sometimes embeds appear with far too much space below them. I've seen this with Spotify and Soundcloud. In these cases, the embed's `figure` is much taller than the actual iframe inside. This appears to be due to the aspect ratio padding here, since modifying those values can lead to fixing this: 

https://github.com/WordPress/gutenberg/blob/52db498780b153029dc9f811df5dd780dbbd650f/packages/block-library/src/embed/style.scss#L56-L84

**Screenshots**

_Spotify embed in Twenty Twenty-One_
![Screen Shot 2020-12-14 at 10 50 47 AM](https://user-images.githubusercontent.com/1202812/102103824-77260c80-3dfb-11eb-99ae-d3ec2a1dc7e3.png)

_Spotify embed in Twenty Twenty_
![Screen Shot 2020-12-14 at 10 51 27 AM](https://user-images.githubusercontent.com/1202812/102103825-77260c80-3dfb-11eb-8040-15ab4e8bf655.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg version: 9.5.2

_[Originally reported in the Twenty Twenty-One forums](https://wordpress.org/support/topic/too-much-white-space-after-spotify-and-soundcloud-embeds/)_

**Comment by covertnine** [comment] 2020-12-19 00:40
Seconded. Discovered this issue today in backend only from inline styles for aspect ratio. 

This goes for embed blocks added to innerblock containers as well.

**Comment by noisysocks** [comment] 2021-01-06 04:44
This has come up quite often in support channels, see #18518.

**Comment by jasmussen** [comment] 2021-03-03 11:47
I have drafted a fix for this one in https://github.com/WordPress/gutenberg/pull/29510, but I will need developer help to land it.

**Comment by paaljoachim** [comment] 2021-03-04 19:11
We are now getting into the final stretch for the release of WordPress 5.7. Hurra!
Which means this looks like an issue that we should aim to get fixed for a 5.7.1 release instead.
@noisysocks

**Comment by noisysocks** [comment] 2021-03-05 00:35
Yes let's punt this. The solution in #29510 is a nice one but will require more testing than we can give it in this short amount of time for 5.7.

**Comment by paaljoachim** [comment] 2021-03-05 08:40
I added a "Backport to WP Minor Release" label here with a focus on getting this into 5.7.1. (I am not sure this is the correct label....)

**Comment by paaljoachim** [comment] 2021-03-16 07:40
@noisysocks 
Let's get this into WP 5.7.x project board: https://github.com/WordPress/gutenberg/projects/54
(It looks like I do not have the permission to add issues to the project board.)

**Comment by noisysocks** [comment] 2021-03-16 23:59
I don't think we should backport https://github.com/WordPress/gutenberg/pull/29510 as it needs time in the plugin to be tested.

**Comment by mikeicode** [comment] 2021-03-18 18:37
Just had this issue on a SoundCloud block.

**Comment by paaljoachim** [comment] 2021-03-18 18:50
Hey Mike @mikeicode 

It looks like the PR has been merged and will be added to Gutenberg plugin 10.3. 
RC will I assume be released Wednesday next week. You can then test it out and see if the fix works for you.

**Comment by sajmes** [comment] 2021-11-04 17:54
I believe I just ran into this issue again on a Spotify block. Significant white space beneath the embedded content for a single file.

**Comment by kosiew** [comment] 2021-11-05 03:03
Here is the screenshot 

![image](https://user-images.githubusercontent.com/29057562/140451386-7bceed77-eff2-4ef2-962a-c5eaad4a3ce9.png)

source: https://ourcommonprayer.org/2021/11/04/testy-sandbox/
#4428978-zen

**Comment by paaljoachim** [comment] 2021-11-05 09:34
I am reopening this issue.

**Comment by supernovia** [comment] 2022-01-28 01:24
I'm seeing this again with a Youtube block. It seems fine in the editor, but once on the site, the frame height is too tall for the video. A user requested help [here](https://wordpress.com/forums/topic/large-space-underneath-embedded-video/). I Tested in Twenty Twenty and Twenty Twenty One: 

![image](https://user-images.githubusercontent.com/3476361/151470638-ca366809-b746-4d95-aa9c-624593a4c44d.png)

Toggling off the resize for smaller devices option makes it less gappy and still seems to work fine with this video on smaller devices, fwiw.

**Comment by georgeh** [comment] 2022-07-13 18:44
I have tried to recreate this in Twenty Twenty, Twenty Twenty One, TT1 Blocks, and Twenty Twenty Two with embed blocks for Spotify and YouTube. In all cases, there was no extra space under the embed blocks. I tested in the editor and the published page, and did not see this display bug. 

Firefox Developer 103.0b2, macOS, Gutenberg `trunk` branch d0973e7b

<details>
<summary>Screenshots:</summary>
<img width="1440" alt="Screen Shot 2022-07-13 at 2 18 14 PM" src="https://user-images.githubusercontent.com/128240/178806272-809f7cdd-1f44-45d6-9f41-38858402a24e.png">
<img width="1440" alt="Screen Shot 2022-07-13 at 2 18 25 PM" src="https://user-images.githubusercontent.com/128240/178806291-5eec387d-3b0b-4722-8d07-99b88c8be204.png">
<img width="1440" alt="Screen Shot 2022-07-13 at 2 19 09 PM" src="https://user-images.githubusercontent.com/128240/178806305-2b42547a-268b-47e7-801d-1a56d7b25206.png">
<img width="1440" alt="Screen Shot 2022-07-13 at 2 19 15 PM" src="https://user-images.githubusercontent.com/128240/178806314-2bb4e869-1b0b-4ef9-9088-53042e060a4a.png">
</details>

If no one else can reproduce, can we close this?

**Comment by bozzmedia** [comment] 2022-07-18 21:18
It seems this issue is exacerbated by either 

(1) having the responsive mode enabled on the block
  and/or 
(2) setting a max height for the embedded iframe via custom CSS. 

In my instance the 4:3 ratio seems to really trip it up.

Thing is, setting a max-height for the CSS seems to be the most readily available way to control the size of these embed blocks which will otherwise be enormous given no container constraints so I'm not sure what to do here.

![image](https://user-images.githubusercontent.com/4435114/179619009-0bc2b9f0-3f77-4764-8725-de9f5615d18f.png)

**Comment by ndiego** [comment] 2022-08-02 14:36
@bozzmedia this issue came up in this weeks Editor Bug Scrub. The attendees of the scrub had trouble reproducing the issue using a YouTube embed, like the one that appears in your screenshot. Would you be able to provide the steps to reproduce the issue you are seeing? I.e. the theme you are using, Gutenberg/WordPress version, etc. Thanks!

**Comment by bozzmedia** [comment] 2022-08-02 21:12
Thanks for the followup Nick, I am using GeneratePress theme. I had set block video embeds to have a max-height with custom css. When I removed the custom CSS the gap was not nearly as large. I am not sure what the best method is to control the video embed sizing otherwise. 

WP 6.0, core gutenberg (no plugin)

**Comment by t-hamano** [comment] 2022-08-03 02:41
@bozzmedia

I have also tested it on various themes and could not reproduce it.
The URL I used for testing is the same as yours (https://www.youtube.com/watch?v=WiVaa68DA6c).

<details>
<summary>See Screenshots</summary>

### Twenty Twenty Two

![WiVaa68DA6c_tt2](https://user-images.githubusercontent.com/54422211/182510703-1aadad88-fb1a-48bb-bd73-f2670f72353d.png)

### Twenty Twenty One

![WiVaa68DA6c_tt1](https://user-images.githubusercontent.com/54422211/182510696-f202ac46-d734-44a6-ae8b-a7f8e29a0209.png)


### Twenty Twenty
![WiVaa68DA6c_tt0](https://user-images.githubusercontent.com/54422211/182510679-31da8878-a72a-40cd-88b4-13e0b51a7786.png)

### GeneratePress (No Sidebar)

![WiVaa68DA6c_GeneratePress](https://user-images.githubusercontent.com/54422211/182511649-cfbc0e37-5fbb-4269-99cb-803f58f7459c.png)

</details>

What is interesting in your screenshot is that it appears to be cropped at 16:9, even though the ratio of the video is 4:3.

As you can see from the block's class name `.wp-embed-aspect-4-3`, this block is parsing the video ratio correctly.

If the iframe tag in the block is rendered in the same 4:3 ratio as the original video, there should be no space.

- What CSS is applied to this iframe tag?
- Is there any CSS written that enforces the ratio?
- What URL did you type in?

**Comment by bozzmedia** [comment] 2022-08-03 22:08
I set

```
.wp-block-embed__wrapper iframe {
    max-height: 640px;
}
```

  in my child theme's style.css.   Same URL. I also experimented with height:auto; on the same tag, and removing the responsive option also helped. I resolved this by removing the max-height, so if there is a better way to control the width of iframes without messing up the responsive ratio option, I would be curious. 

Otherwise it seems this is no longer a reproducible, thank you for the thorough investigation.

**Comment by t-hamano** [comment] 2022-08-04 01:20
If you don't write any new CSS and only enable responsive mode, the ratio of the embedded video should be detected and maintained correctly.

Please check to see if the issue reproduces in a flat environment using a default theme or similar.

If you want to reduce the width of the video, setting `max-width` to `.wp-block-embed__wrapper` (not iframe) instead of height should work fine.

**Comment by abhansnuk** [comment] 2022-08-09 14:13
I tested it again this week, and could not reproduce it with YouTube or Spotify embeds on a default theme. Last year, I did face the issue on the Twenty Twenty Theme, but this is no longer the case.

**Comment by t-hamano** [comment] 2022-08-10 05:27
I think the problem originally mentioned in this issue should have been resolved in #29510.

I would also like to close this issue as we have been unable to reproduce it on YouTube and consider this to be a theme or custom CSS issue.

If anyone finds any other problems with this issue, please don't worry about it and re-open it.

**Closed by t-hamano** 2022-08-10 05:27 UTC
Labels: [Type] Bug, Needs Testing, [Block] Embed
