### ISSUE TITLE
Framework gutenberg playground, BlockTools cursor issue.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#57139] opened 2023-12-17 15:30 UTC
### Discussed in https://github.com/WordPress/gutenberg/discussions/57138

<div type='discussions-op-text'>

<sup>Originally posted by **kohheepeace** December 17, 2023</sup>
@youknowriad 

## Assumption
I have started a gutenberg project for framework(standalone) with the following referenced Links. In doing so, I encountered a problem, so I would like to ask a question.

📍 stackblitz URL
https://stackblitz.com/edit/stackblitz-starters-papfri

### Referenced links to setup project
- https://github.com/WordPress/gutenberg/blob/trunk/storybook/stories/playground/fullpage/index.js
- [platform docs#intro "Bootstrap your block editor"](https://github.com/WordPress/gutenberg/blob/cdeca67b63635cca295ba8f4874130c53f394ab0/platform-docs/docs/intro.md?plain=1#L33)

## Problems
As shown in the following video, **it takes two clicks to edit paragraph.**

The first click places the focus on the BlockTools button, and the second click makes it editable.

https://github.com/WordPress/gutenberg/assets/29557494/f24f6377-8e2b-470a-9604-7d7210c6b5aa

</div>

**Comment by youknowriad** [comment] 2023-12-17 15:31
cc @ellatrix maybe you have a quick idea about why the toolbar is stealing the focus on the implementation above.

**Comment by costasovo** [comment] 2023-12-18 14:45
I'm experiencing the same issue on a standalone editor after updating to tag `wp-6.4`.
On the first click on the block, it and the toolbar are focused, but I can’t type, and the toolbar is missing inline format tools. On the second click, I can type in rich text, and format tools are displayed. 
I tried to debug the issue and I found that on the first click useSlotFills ([#](https://github.com/WordPress/gutenberg/blob/16ec554a2605d45414ee121e2f36c1d7177974ad/packages/components/src/slot-fill/bubbles-virtually/use-slot-fills.ts#L17)) for "BlockFormatControls" returns an empty array, but on the second click it returns an array with one item.

**Comment by costasovo** [comment] 2023-12-18 17:09
I found that, in my case, the issue is present only when StrictMode is enabled. When I compile the code for production or remove the `<StrictMode>` wrap, BlockTools works as expected. So this might be related to how StrictMode reruns useEffects or additionally re-render components.

**Comment by youknowriad** [comment] 2023-12-18 18:17
Also @jeryj maybe you have an idea about this.

**Comment by jeryj** [comment] 2023-12-18 20:24
I thought the issue would be from `focusOnMount` in the `<NavigableToolbar />` running when it shouldn't, so I removed the `<NavigableToolbar />` to debug. The toolbar was still getting focused though... 

I ended up removing pieces of the toolbar until it wasn't stealing focus. That led me to this [code that focuses the toolbar when the block lock modal is closed](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-lock/toolbar.js#L30-L52). Commenting out that `useEffect` from https://github.com/WordPress/gutenberg/pull/51666 fixes this focus-stealing on mount when using `<StrictMode />`. I haven't looked into the specifics of why that was added, so I'm not sure what to do to fix it.

Unrelated Note: In the StackBlitz demo, I believe the `<BlockTools />` should not be wrapping `<BlockCanvas />`, as `<BlockTools />` is included within `<BlockCanvas />` already.

**Comment by jeryj** [comment] 2023-12-18 20:26
Also, thank you @costasovo for figuring out the `<StrictMode />` piece of it! That was hugely helpful for debugging this.

**Comment by kohheepeace** [comment] 2023-12-18 20:49
> Unrelated Note: In the StackBlitz demo, I believe the `<BlockTools />` should not be wrapping `<BlockCanvas />`, as `<BlockTools />` is included within `<BlockCanvas />` already.

Yes! that was my mistake 😢 I fixed it in stackblitz! Thanks!

<table>
    <tbody>
        <tr>
            <td>
                Before
            </td>
            <td>
                After
            </td>
        </tr>
        <tr>
            <td>
                <pre><code class="language-plaintext">&lt;BlockTools className="playground__content"&gt;
                    &lt;BlockCanvas height="100%" styles={editorStyles} /&gt;
                &lt;/BlockTools&gt;</code></pre>
            </td>
            <td>
                <pre><code class="language-plaintext">&lt;div className="playground__content"&gt;
                    &lt;BlockCanvas height="100%" styles={editorStyles} /&gt;
                &lt;/div&gt;</code></pre>
            </td>
        </tr>
    </tbody>
</table>

**Comment by jeryj** [comment] 2023-12-20 21:17
This should be fixed by https://github.com/WordPress/gutenberg/pull/57185

**Closed as completed by jeryj** 2023-12-20 21:17 UTC
Labels: [Type] Bug, Framework, [Status] In Progress
