### ISSUE TITLE
feature request: showing duplicate titles

### ISSUE THREAD

**Issue by hosseinfarnia** [WordPress/gutenberg#11241] opened 2018-10-30 11:25 UTC
Hi,
It would be nice if the gutenberg shows duplicate titles.
I mean when there is a similar title, the editor can show a message to prevent duplicate titles.
It's even good for SEO.
Thanks a lot

**Comment by youknowriad** [comment] 2019-12-13 08:09
Duplicate of #15282

**Closed by youknowriad** 2019-12-13 08:09 UTC
Labels: [Type] Enhancement
