### ISSUE TITLE
If you add a button at the bottom of the post/page the url field extends under the meta area

### ISSUE THREAD

**Issue by NikoVee** [WordPress/gutenberg#64623] opened 2024-08-19 20:06 UTC
### Description

Hey there,

There seems to be a bit of an issue with the button block. There seems to be an issue with every metafield that get's added if you use other plugins like ACF, Yoast or any that actually adds the metafield at the bottom of the editor. Basically even post meta related plugins.

### Step-by-step reproduction instructions

If you add even one of these plugins:
1. Then add a page full of content
2. Scroll down and add a button. Then add text. Then try to link that button somewhere. Then you should be able to see that the url area is actually under that metafield area.
3. Then you need to scroll up and down a bit so that the actual URL area is visible again.

### Screenshots, screen recording, code snippet

![18147b514f55be07437cf41b6c9165c1](https://github.com/user-attachments/assets/9cde0171-fab2-4d2f-b408-fcb0c81ff65b)

### Environment info

- WordPress version 6.6.1
- Theme Twenty Twenty-Four
- Active plugins JSM Show Post Metadata

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by helenaartmann** [comment] 2024-08-19 22:30
Hi Niko, can you please confirm that you tested without having the JSM Show Post Metadata plugin active? 

I tested it using WP 6.6, theme Twenty Twenty-Four, JSM Show Post Metadata plugin was not active, and I couldn't reproduce it.

**Comment by t-hamano** [comment] 2024-08-20 03:56
Thanks for the report. This issue has been fixed in #63939.

![image](https://github.com/user-attachments/assets/6552dce2-1449-473c-9407-652e19b2db9f)

**Closed as not planned by t-hamano** 2024-08-20 03:56 UTC
Labels: [Type] Bug, [Feature] Meta Boxes
