### ISSUE TITLE
"Return to editor" link is wrong when comparing revisions

### ISSUE THREAD

**Issue by GaryJones** [WordPress/gutenberg#2808] opened 2017-09-27 10:01 UTC
__Edit by @aduth (2017-09-27):__ The original issue reported here has since been resolved, but behavior of "Return to editor" is still not always correct. See https://github.com/WordPress/gutenberg/issues/2808#issuecomment-332617564 for more details.

---

## Issue Overview
"Return to editor" link (and post title link) is wrong when coming from Gutenberg editor.

## Steps to Reproduce (for bugs)

1. Save a post (can be draft or published), and then make edits and update, so WordPress has at least two revisions.
2. Click the Revisions link in the Document inspector:
![screenshot 2017-09-27 10 48 35](https://user-images.githubusercontent.com/88371/30907025-7d40274a-a371-11e7-8485-17f1a617424a.png)
3. Now click the "Return to editor" link:
![screenshot 2017-09-27 10 46 49](https://user-images.githubusercontent.com/88371/30907047-90628bc4-a371-11e7-9aea-61be4a8f9050.png)

## Expected Behavior
I'd expect to go back to the Gutenberg editor.

## Current Behavior
I end up in the normal editor:
![screenshot 2017-09-27 10 50 43](https://user-images.githubusercontent.com/88371/30907104-bafa593e-a371-11e7-8519-64586f133cc2.png)

## Possible Solution
Add a querystring argument to the "X revisions" link in Document inspector, and use that to conditionally filter the URL for the return to editor link (`get_editor_post_link` filter).

https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-admin/revision.php#L75-L78

**Comment by aduth** [comment] 2017-09-27 11:58
Are you running from the plugin version? I expect this is fixed by the `get_edit_post_link` filter introduced in #1797 , which will be included in the next plugin release. Testing myself, this seems to work correctly.

Closing, but please reopen if the issue is not resolved.

**Comment by GaryJones** [comment] 2017-09-27 18:25
> Are you running from the plugin version?

Sorry - yes, I was (`1.1.0`).

I'll wait until 1.2.0 and give that a go.

**Comment by aduth** [comment] 2017-09-27 18:25
@GaryJones 1.2.0 was released today, if you want to try giving it another go.

**Comment by GaryJones** [comment] 2017-09-27 18:42
Testing with 1.2.1, and generally it works, though there is an edge case that it doesn't.

The commit in #1797 has [this line](https://github.com/WordPress/gutenberg/pull/1797/files#diff-9dfc2b70ad1c71918441461179054b0bR221) which checks that the post has at least one block.

The edge case can therefore be triggered by:
1. Select Gutenberg -> New Post.
2. Add a title only. 
3. Save, and reload the page to see the Revisions link in the Document inspector.
4. Click Revisions link, then the Return to editor link.

You'll end up back in the old editor.

**Comment by aduth** [comment] 2017-09-27 21:01
Thanks for the detail @GaryJones . I've edited the original message with a pointer to the new steps, and will reopen.

**Comment by mor10** [comment] 2017-10-30 18:53
This is still happening in 1.5.2

**Comment by jacboy** [comment] 2017-12-05 14:56
It seems like this still hasen't been fixed yet. I am using WordPress 4.9.1 with Gutenberg 1.8.1.
I am not able to restore a revision, it already produces an empty post.

See here: https://de.wordpress.org/support/topic/gutenberg-revisionen-wiederherstellen-fuehren-zu-leerem-beitrag-wie-loesen/

Any ideas on how to bring the content back?

**Closed** 2017-12-13 19:49 UTC
