### ISSUE TITLE
Handle menu items with _invalid flag 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34818] opened 2021-09-14 17:32 UTC
## What problem does this address?

A nav menu_item object returned from calling [wp_setup_nav_menu_item](https://developer.wordpress.org/reference/functions/wp_setup_nav_menu_item/). This object contains a property called `_invalid`. It is used for the following. 

> Whether the menu item represents an object that no longer exists.

A menu item can be invalid for the following reasons. 
- Linked post is post status trash
- Linked term does not exist
- post_type_archive post type doesn't exist.
- Taxonomy archive, taxonomy doesn't exist.

The new navigation editor should handle this case. See the existing menu screens. 

<img width="468" alt="Screenshot 2021-09-14 at 18 29 03" src="https://user-images.githubusercontent.com/237508/133305634-8b46a5d2-93c9-4f25-a1b5-1161253a7c8e.png">
<img width="323" alt="Screenshot 2021-09-14 at 18 29 22" src="https://user-images.githubusercontent.com/237508/133305663-ba3687f5-8029-49db-bec0-999da860674a.png">

Related: https://github.com/WordPress/gutenberg/pull/34670

**Comment by spacedmonkey** [comment] 2021-09-15 09:58
Related: https://github.com/WordPress/gutenberg/pull/31716

**Comment by talldan** [comment] 2021-09-15 11:49
@spacedmonkey I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/23573, which is a high priority on the tracking issue.

**Comment by spacedmonkey** [comment] 2021-09-15 20:37
@talldan Feel like it. Wanted to ensure we respect the value come from the REST API. If #23573 will do this, then I am happy to close this ticket.

**Comment by talldan** [comment] 2021-09-16 02:24
👍 I've added the details from this description to that one.

**Closed as completed by talldan** 2021-09-16 02:24 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Feature] Navigation Component
