### ISSUE TITLE
Legacy center-aligned buttons are no longer center aligned on the front end. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#23291] opened 2020-06-18 22:39 UTC
**Describe the bug**

Individual buttons created before the "Buttons" block existed are no longer center-aligned by default in the front end. 

Gutenberg loads front-end code to ensure that center-aligned buttons appear centered within their container: 

https://github.com/WordPress/gutenberg/blob/cbef07223613a6f1d59f4035dbfc6dd1598129ba/packages/block-library/src/buttons/style.scss#L13-L15

It looks like Gutenberg does _not_ provide this code for legacy `button` blocks however, which means they do not properly center-align themselves on the front end. 

**To reproduce**

Using (just about) any theme: 

1. Use the old button block, center align it. ([here's the sample markup](https://cloudup.com/cAV9t6uZV0a) I used in the screenshots if that's helpful)
2. View on the front end.
3. See that the button is not center-aligned. 
### Screenshots

**Editor:** 

_Using the Gutenberg Starter Theme_
<img width="712" alt="Screen Shot 2020-06-18 at 6 31 21 PM" src="https://user-images.githubusercontent.com/1202812/85078343-37ef6980-b192-11ea-82da-dffc8e17fc18.png">

_Using Twenty Twenty_
<img width="607" alt="Screen Shot 2020-06-18 at 6 34 42 PM" src="https://user-images.githubusercontent.com/1202812/85078428-6f5e1600-b192-11ea-8874-81f82cd9b3ca.png">

**Front end:** 

_Using the Gutenberg Starter Theme_
<img width="660" alt="Screen Shot 2020-06-18 at 6 31 30 PM" src="https://user-images.githubusercontent.com/1202812/85078353-3c1b8700-b192-11ea-8edc-fbebe24fd657.png">

_Using Twenty Twenty_
<img width="1066" alt="Screen Shot 2020-06-18 at 6 34 55 PM" src="https://user-images.githubusercontent.com/1202812/85078469-856bd680-b192-11ea-9e56-3d0595e54520.png">

**Editor version:**
- WordPress v5.4.1
- Gutenberg v8.3.0

**Comment by youknowriad** [comment] 2020-06-22 14:46
Is this a regression? I feel alignments were always left to the theme?

**Comment by kjellr** [comment] 2020-06-22 14:59
I _think_ so? Maybe @jasmussen can gut check that too. 

It looked like buttons that used to be center-aligned all of a sudden stopped working, even when the theme had not been updated.

**Comment by jasmussen** [comment] 2020-06-22 15:40
Question before I dive deeper: is the off-centering in the editor only when the block is selected? Because then it's the same issue with the appender taking up space and therefore changing the centering.

And other question: it looks like the frontend styles were broken before, but fixed now, am I interpreting that correctly?

**Comment by kjellr** [comment] 2020-06-22 17:01
> Question before I dive deeper: is the off-centering in the editor only when the block is selected? Because then it's the same issue with the appender taking up space and therefore changing the centering.

No, this is different. The editor looks great, it's just the front end that's the problem. 

> And other question: it looks like the frontend styles were broken before, but fixed now, am I interpreting that correctly?

The opposite actually. Center-aligned buttons using the old markup worked before, but now appear to be uncentered in the front end. 

I just dug into this a little more thoroughly, and I'm more sure that it's a regression. You can test this pretty easily by making a new post that includes the old button markup:

```
<!-- wp:button {"align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link" href="https://balasanademo.wordpress.com/classes/">Center-Aligned Button</a></div>
<!-- /wp:button -->
```

With the Gutenberg plugin active, the button will not be center-aligned on the front end using most themes. Here's Twenty Twenty for example: 

![Screen Shot 2020-06-22 at 12 48 00 PM](https://user-images.githubusercontent.com/1202812/85313853-a5e3ab80-b486-11ea-8b38-8c82cd7c20f5.png)
 
When you deactivate the Gutenberg plugin, the button will center itself: 

![Screen Shot 2020-06-22 at 12 47 41 PM](https://user-images.githubusercontent.com/1202812/85313893-b562f480-b486-11ea-911d-e267ecd211a0.png)

The difference is that when the plugin is inactive, a `.wp-block-button.aligncenter { text-align: center; }` rule is provided in `/block-library/style.css`. 

It looks like this style style stopped working right when #21642 was merged, and the `.wp-button` selector was changed to `.wp-block-button__link` (thus taking the `.aligncenter` rule along with it).

**Comment by jasmussen** [comment] 2020-06-23 06:55
Yep. I see it. Sorry, you meant the old markup. Apologies.

We output this for the new Buttons (plural) block:

```
.wp-block-buttons.aligncenter {
    text-align: center;
}
```

We output nothing at all for the button. Let me push a fix.

**Comment by jasmussen** [comment] 2020-06-23 07:04
Fixed in #23381.

**Closed** 2020-06-23 12:42 UTC
Labels: [Block] Buttons, [Feature] Themes, [Status] In Progress, [Type] Regression

**Comment by florianbrinkmann** [comment] 2021-04-01 09:58
@jasmussen I think this is an issue again, because of the modifications in a03ea51e11a36d0abeecb4ce4e4cea5ffebdffc5. With that, the styling for `.wp-block-button.aligncenter` that is *not* inside a `.wp-block-buttons` was removed again.

**Comment by cryptocurls** [comment] 2021-04-01 17:16
@jasmussen Also experiencing this issue now - all buttons on Twenty Twenty child theme that were centered are now not on the frontend

**Comment by jasmussen** [comment] 2021-04-05 07:09
@florianbrinkmann @mvbdigital I'm having a bit of a hard time reproducing:

<img width="776" alt="Screenshot 2021-04-05 at 09 09 07" src="https://user-images.githubusercontent.com/1204802/113547650-a18c1780-95ee-11eb-90ae-17b05ffdd4a8.png">

Can you provide me with some problematic example markup, plus theme and plugin information? I'd be happy to take a look again.

**Comment by florianbrinkmann** [comment] 2021-04-05 11:31
@jasmussen sure, here is an example:

```
<div class="wp-block-button aligncenter"><a class="wp-block-button__link" href="#">Not centered</a></div>
```

This is from a site with a custom theme, created before the buttons block was introduced. And so it has the old button markup in various places (without the wrapper `wp-block-buttons`).

**Comment by jasmussen** [comment] 2021-04-06 07:32
Thanks for the example. I did manage to reproduce, however it's an issue with both new and old button markup, as far as I can tell:

<img width="1035" alt="Screenshot 2021-04-06 at 09 27 10" src="https://user-images.githubusercontent.com/1204802/113674474-838be900-96ba-11eb-9665-90f5a09f0585.png">

Here's a small debugging session:

![debugging](https://user-images.githubusercontent.com/1204802/113674484-871f7000-96ba-11eb-9847-8a5bfe1d0b99.gif)

If the issue is what I think it is, then it's a recent change that introduces a higher specificity default left/right margin on blocks. There are more details in [this PR](https://github.com/WordPress/gutenberg/pull/30337) where I tried to fix it, however I'm closing that one in favor of https://github.com/WordPress/gutenberg/pull/30375 which, if I'm not mistaken, should fix the issue for both new and old buttons.

If you are able to test that PR, perhaps using Gutenberg Run (here: http://gutenberg.run/30375) — and comment with your findings on that PR, it would help us land it. Thank you!

**Comment by florianbrinkmann** [comment] 2021-04-06 09:40
Hi @jasmussen, thanks for looking into this. Maybe my description was misleading: the issue is the frontend CSS. When I paste the button markup in a HTML block in the gutenberg.run instance, it is centered in the frontend, but only because Twenty Twenty-One comes with a `text-align: center` for the `.aligncenter` class. After removing that, the button is left aligned again. The Gutenberg styles had a `.wp-block-button.aligncenter { text-align: center; }` rule until https://github.com/WordPress/gutenberg/commit/a03ea51e11a36d0abeecb4ce4e4cea5ffebdffc5, where the following change breaks it:

https://github.com/WordPress/gutenberg/commit/a03ea51e11a36d0abeecb4ce4e4cea5ffebdffc5#diff-ba5e352fd98cd49d679e248a86f7d04077ed547c26ca9482d002d015cf93c9b4L34

After that, it became a `.wp-block-buttons.aligncenter` rule, which, of course, does not work for buttons inserted before the buttons block was introduced.

**Comment by jasmussen** [comment] 2021-04-06 10:12
Thanks for the clarification @florianbrinkmann. Can you try this one and see if that addresses your issue? https://github.com/WordPress/gutenberg/pull/30525

That would be http://gutenberg.run/30525. 

If yes, then we need to test that PR against all sorts of combinations of the new Buttons block, to see that the code doesn't regress anything there. It shouldn't as far as I can imagine, but important to still test.

**Comment by florianbrinkmann** [comment] 2021-04-11 12:41
Yes, that seems to fix it @jasmussen!

**Comment by jasmussen** [comment] 2021-04-12 07:29
Cool, thanks for testing. I'll request some reviews on that PR!
