### ISSUE TITLE
Enhancement: Continue to display drop cap when block is active

### ISSUE THREAD

**Issue by jancavan** [WordPress/gutenberg#7292] opened 2018-06-12 17:45 UTC
**Describe the bug**
When I activate the drop cap setting, the drop cap only shows up when the block is inactive - ie when the block is not in focus.

**To Reproduce**
1. Add a text block.
2. Activate the drop cap setting.
3. Start typing the rest of the text in your block.
4. Notice how the drop cap disappears and returns to its normal state. If you click outside of the block, I was also expecting the drop cap to at least get displayed, but it was sort of just flickering instead.

**Expected behavior**
I expected the drop cap to still be displayed even as I am typing.

**Screenshots**
https://cloudup.com/cCgoBQaviyy

**Desktop (please complete the following information):**
 Mac OS High Sierra 10.13.3
Chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by GlennMartin1** [comment] 2018-06-12 17:58
Duplicate of https://github.com/WordPress/gutenberg/issues/6273

**Comment by jancavan** [comment] 2018-06-12 18:02
Closing as it's a duplicate.

**Comment by earnjam** [comment] 2018-11-11 11:49
This was done intentionally in #6359. But perhaps we could change this functionality as a future enhancement. It's definitely a bit confusing and seems buggy in Safari specifically.

**Comment by earnjam** [comment] 2018-11-11 11:53
Actually, there are better details and gifs showing the issue in #11119, so I'm going to close in favor of that one.

**Closed by earnjam** 2018-11-11 11:53 UTC
Labels: [Block] Paragraph, [Type] Enhancement
