### ISSUE TITLE
The block controls popover scroll speed differs from other elements on page

### ISSUE THREAD

**Issue by DenKoren** [WordPress/gutenberg#24946] opened 2020-08-31 17:38 UTC
**Describe the bug**
When you open page or post edit screen and add a new block on blank page everything looks OK: you select the block, the block controls popover shows up and you can easily change block settings.
But when you have long page that does not fit one screen things become complicated: if you select some block, the controls popover appear as usual, but once you start scrolling down, the block controls popover scrolls much faster than block itself. 

This makes block controls popover detach from the block it belongs to. When you try to select a block on the bottom of post after scrolling several screens, the block controls popover appear in an unpredictable place and you have to select block and then slowly scroll up until your screen scroll meets block control popover scroll. 

This looks very funny but makes UI unusable when working with long texts.

**To reproduce**
1. Go to WordPress content editor (create page, for example) 
2. Create several blocks of various content on page so they does not fit the single screen of your browser.
3. Select some block in the middle
4. Scroll down the page and look how block control popover runs away from the selected block. :)

**Expected behavior**
The block controls popover scrolls on the same speed as its block and remains glued to the block every time.

**Screenshots**
![image](https://user-images.githubusercontent.com/3419381/91748758-27636280-ebc9-11ea-8fdc-b469dbe79dc3.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?
    default

**Desktop (please complete the following information):**
 - OS: Mac OS X v 10.15.5
 - Browser Chrome, Safari, Yandex.Browser, Firefox
 - Version: Firefox v80.0, Safari v13.1.1

**Comment by cedkim** [comment] 2020-09-19 07:06
I'm also experiencing this issue.

**Comment by tim9192** [comment] 2020-10-20 07:28
+1. Same problem here.

**Comment by getsource** [comment] 2021-03-02 05:42
Hi @DenKoren!
Thanks much for the report, and apologies for the long wait for a reply.

This was tested [during today's triage](https://wordpress.slack.com/archives/C02QB2JS7/p1614662990389400), and folks present weren't able to reproduce the issue on master.

As it's likely that this has been fixed between since the issue was created, in the meeting it was decided to close this issue.

However, if you are still having the problem, please feel free to re-open, so that it can be fixed.

Thanks again!

**Closed by getsource** 2021-03-02 05:42 UTC
Labels: Needs Testing
