### ISSUE TITLE
Bug when clicking on a block and then on new block

### ISSUE THREAD

**Issue by kamataryo** [WordPress/gutenberg#1428] opened 2017-06-25 05:52 UTC
If you select the title block, then click on the empty "Write your story" block, the appearing 'Write…" block after "Write your story" block is highlighted as selected for a second.
![blink](https://user-images.githubusercontent.com/6292312/27513967-93f05542-59b5-11e7-86f9-e6bca18554a3.gif)

**Comment by youknowriad** [comment] 2017-06-26 08:38
This is not a bug, this is the current behaviour, we know this might seem confusing and we're working on improving it. The idea is to ease adding text at the end of the post (the last block could be an image for example). I'm closing in favour of related discussion in https://github.com/WordPress/gutenberg/issues/1181#issuecomment-310069918

**Comment by mtias** [comment] 2017-06-26 09:33
I think the bug here is just about the block outline persisting on the second "Write..." block when you click on the first one.

**Comment by youknowriad** [comment] 2017-06-26 11:04
Yeah, I'm tired this monday :)

**Comment by youknowriad** [comment] 2017-08-02 11:18
Not a bug anymore because we don't auto-create empty placeholders at the end of the post

**Closed by youknowriad** 2017-08-02 11:18 UTC
