### ISSUE TITLE
Embed blocks no longer appear when content position is set on cover block

### ISSUE THREAD

**Issue by lakellie** [WordPress/gutenberg#28640] opened 2021-02-01 19:32 UTC
## Description
When an embed block is inserted inside a cover block, the embed block does not appear when a non-default content position is selected for the cover block.

## Step-by-step reproduction instructions
1. Add a cover block
1. Add an image background
1. Add an embed block inside the cover block (I tested with both YouTube and SoundCloud)
1. Set the content position on the cover block to something besides the default center position, like "top center" or "bottom center"
1. Save and view the post on the frontend.

## Expected behaviour
The embed to appear inside the block

## Actual behaviour
When you view the post/page, the embed does not appear

## Screenshots or screen recording (optional)

https://d.pr/i/C6sSE3

## WordPress information

- WordPress version: 5.6
- Gutenberg version: Gutenberg 9.8.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, issue occurs on all themes

## Device information
- Device: Desktop
- Operating system: MacOS Catalina
- Browser: Chrome 88

**Comment by sirreal** [comment] 2021-02-02 09:10
Thanks for the report. I've just confirmed this is an issue with Gutenberg 9.8. You can see an example here from the frontend. Notice that the `iframe` containing the video is present in the HTML, but has `0px x 0px` size:

![Screen Shot 2021-02-02 at 10 03 08](https://user-images.githubusercontent.com/841763/106577000-1df67180-653e-11eb-89e8-f50f70139640.png)

By quickly tweaking some rules in the browser we can give the iframe some size and it appears (just a demo, this is not a fix):

![Screen Shot 2021-02-02 at 10 03 29](https://user-images.githubusercontent.com/841763/106577075-36ff2280-653e-11eb-80cb-633173c08dc0.png)

I suspect this is a regression introduced by https://github.com/WordPress/gutenberg/pull/25171. It looks like the new markup introduced there is not compatible with responsively sized embeds.

FYI @ajlende @mkaz

**Comment by sirreal** [comment] 2021-02-02 09:14
This is a problem with the latest Gutenberg build from the main branch as well.

**Comment by brentswisher** [comment] 2021-02-03 21:52
Just noting that #28653 has merged and appears to have fixed this - I know @jasmussen has some questions in that PR (Is it the right default size etc) so I will leave it up to him to close this or not, but it is working for me in the latest master. At least wanted to get this linked to that PR

**Comment by jasmussen** [comment] 2021-02-04 08:43
Yep, this one is can definitely be closed, as the problem has been addressed.

There's a conversation to be had from the PR you link, on whether the arbitrary dimensions applied to prevent the embed from collapsing can be improved. But at least now it's functional to the point that it's clear what's going on when you use the embed with the matrix alignment tool and you see the result. If that result is not good, you can un-align.

Thanks everyone!

**Closed by jasmussen** 2021-02-04 08:43 UTC
Labels: CSS Styling, [Block] Cover, [Status] In Progress, [Type] Bug, [Type] Regression
