### ISSUE TITLE
Instagram embeds not working properly in the editor (alignment and content display)

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#20515] opened 2020-02-27 22:45 UTC
**Describe the bug**
Instagram embeds no longer display their content in the editor. They appear fine on the front-end.

![2020-02-27 19 28 28](https://user-images.githubusercontent.com/1451087/75493074-e24f4100-5997-11ea-8151-638efb892019.gif)

Also, both “Align wide” and “Align full” options aren't working at all in the editor. When you specify either one, the width is limited to 600 pixels, which is the hardcoded value. The theme has `responsive-embeds` activated.

![2020-02-27 19 28 52](https://user-images.githubusercontent.com/1451087/75493141-06ab1d80-5998-11ea-8599-66de2f0127b5.gif)

This alignment bug also occurs in previous versions of the editor. Setting `max-width` to `100%` solves the issue.

![2020-02-27 19 00 07](https://user-images.githubusercontent.com/1451087/75493448-a7014200-5998-11ea-8838-0fe9d6b20648.gif)

**To reproduce**
1. Add a new Instagram block. See that there's no preview.
2. Click on the “Change alignment” icon.
3. Change the alignment either to “Align wide” or “Align full”.
4. The embed does not fill the width of the wrapper element.

**Expected behavior**
– The Instagram embed should display it's content's preview on the editor.
– The embed should also occupy the entire width of the parent element, as specified by the alignment option.

**Desktop (please complete the following information):**
 - MacOS 10.14.6 (Mojave).
 - Chrome 80, Firefox 73, Edge 80.
 - WordPress 5.3.2 and 5.4-beta3-47383.
 - TwentyTwenty (with `add_theme_support( 'responsive-embeds' )`).
 - Gutenberg 7.6.0.

**Comment by jorgefilipecosta** [comment] 2020-03-01 19:56
Hi @pagelab thank you for reporting this issue 👍  In your tests without the Gutenberg plugin does the issue happens in 5.3.2 and/or 5.4-beta3-47383? Thank you in advance for the additional information!

**Comment by jorgefilipecosta** [comment] 2020-03-02 10:49
I did some tests, It seems Instagram embeds have a max-width and sometimes alignment controls do not work as expected. This issue affects WordPress 5.3.2, WordPress 5.4 Beta 3 and Gutenberg 7.6.

Regarding the problem of Instagram embeds not appearing on the editor I was able to reproduce this issue on Gutenberg 7.6. The problem is not affecting WordPress 5.3.2 and WordPress 5.4 Beta 3.

**Comment by pagelab** [comment] 2020-03-02 12:11
@jorgefilipecosta Yeah, I confirm your findings.

**Comment by pagelab** [comment] 2020-03-02 12:13
Only the alignment issue happens in both WordPress 5.3.2 and 5.4-Beta 3.

**Comment by pagelab** [comment] 2020-10-26 21:03
Just a quick update: this remains an issue even though official support for Instagram embeds [has been removed in core](https://core.trac.wordpress.org/ticket/50861).

There is at least [one plugin](https://wordpress.org/plugins/instagram-feed/) out there that can restore the embeds.

**Comment by jorgefilipecosta** [comment] 2020-10-28 22:07
Hi @pagelab thank you for the update. Given that now there is no Instagram embed I guess we should close the issue. I guess the issue should be reported on the support forums of the plugin that offer this functionality https://wordpress.org/support/plugin/instagram-feed/.

**Closed by jorgefilipecosta** 2020-10-28 22:07 UTC
Labels: [Block] Embed, [Type] Bug
