### ISSUE TITLE
Inserting images is very cumbersome

### ISSUE THREAD

**Issue by uncertainquark** [WordPress/gutenberg#26651] opened 2020-11-03 06:59 UTC
**Describe the bug**
Inserting images in the Block editor is a pain. What used to be one-click upload in the Classic editor is now a multi-step process. One has to either change the paragraph block manually with multiple-mouse clicks or insert using the keyboard shortcut which doesn’t even suggest the “image” block despite an exact name type out.

![telegram-cloud-photo-size-5-6122697952188280492-y](https://user-images.githubusercontent.com/22585732/97956791-99297980-1dcf-11eb-9c05-dc9f2d4cc5a1.jpg)

Even after you select the right block, all it does is add that block. Then I have to click “Select an image” and then it asks to select three options––Upload, Media library or Web––and then we can get to the point. Sighs.

**Expected behavior**
One-click image upload. Two-click at best if selecting from the media library.

**Editor version (please complete the following information):**
- WordPress version: v5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Safari, Firefox

**Comment by talldan** [comment] 2020-11-03 08:26
There are a few different issues here by the looks of it. Firstly that the listings in the `/` menu aren't sorted very well, but secondly about the rest of the interface. 

Another option you might not have considered—you can drag an image into the editor. That seems to be the fastest way to upload.

> One-click image upload. 

Maybe nitpicking here, but I'm not sure how one-click image upload is possible, seems like you first have to indicate that you want an image and secondly choose the image itself.

**Comment by uncertainquark** [comment] 2020-11-04 06:24
> There are a few different issues here by the looks of it. Firstly that the listings in the / menu aren't sorted very well, but secondly about the rest of the interface for adding blocks.

Yes, I’d typically expect the blocks to be listed in order of relevance to the term I’m typing based on alphabetical match or most-used block or both.

> Another option you might not have considered—you can drag an image into the editor. That seems to be the fastest way to upload.

This is what I do but isn’t handy all the time. Picking from a file picker can be fast too and it’s good to have both.

> Maybe nitpicking here, but I'm not sure how one-click image upload is possible, seems like you first have to indicate that you want an image and secondly choose the image itself.

I mean that if you look at the Classic Editor and editors of competing platforms, there’s a persistent “Add image” button which either opens the file picker or the media library (along with the picker option). It’s easy to hit that button directly for every image upload, rather than doing this multi-step process _every single time_. :(

**Comment by jeherve** [comment] 2020-11-09 08:23
>  insert using the keyboard shortcut which doesn’t even suggest the “image” block despite an exact name type out.

This was also reported here:
https://github.com/Automattic/jetpack/issues/17732

It would appear that the quick inserter suggests blocks created by third-party plugins before core blocks. This seems to happen with all plugins. I'm not quite sure if it's done by design, but I agree it can be frustrating when using searches like `image`; one would expect to get the core block that exactly matches that name before to get suggestions from third-party plugins.

Potentially related: #21080 where more changes are being discussed for the quick inserter.

**Comment by simison** [comment] 2020-11-10 15:38
Related to inserter improvements discussed here: https://github.com/WordPress/gutenberg/issues/26404

**Comment by jasmussen** [comment] 2021-06-30 06:31
I believe the core of this issue relates to inserting images with the slash command, and the fact that typing `/image` and pressing enter didn't always insert an image was extremely frustrating.

However as of #25105, that behavior has been fixed:

![slash](https://user-images.githubusercontent.com/1204802/123911271-ddc7dd80-d97b-11eb-8383-c80a4767f86b.gif)

While that fix landed in September 2020 and this ticket is from November, the delay could still be explained by the fix needing release in plugin and software.

The other aspect, inserting the block first and then choosing the content meaning an extra click, there are a few aspects to that. Dan already mentions the drag and drop aspect for handling that. There are some additional improvements on the way around that, including #32819 and #32820. But perhaps most importantly, there is an opportunity to remove the need for that extra click, by showing a part of the media library directly in the Image placeholder block, when there's space, as ticketed in #15773. While it's still block first then content, it will reduce the amount of clicks to get images inserted, while keeping with the core behavior of inserting the block first, and then choosing the content.

To keep discussions focused on those tickets, and because the other part of this issue appears to have been addressed, I'm going to close this one. If that was in error, let me know and it will be super easy for me to reopen it!

**Closed by jasmussen** 2021-06-30 06:31 UTC
Labels: Needs Design Feedback, [Block] Image, [Type] Feedback
