### ISSUE TITLE
Query Loop pattern selection missing with 5.8-RC3

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#33398] opened 2021-07-13 19:35 UTC
## Description

The pattern selection normally built into the Query Loop block is missing with the latest nightly version (5.8-RC2-51407). 

## Step-by-step reproduction instructions

1. Add a new post. 
2. Add a Query Loop Block
3. Notice that the pattern selection is missing. 

## Expected behaviour

Expect to be able to pick from various patterns. 

## Actual behaviour

No option to scroll through patterns. 

## Screenshots or screen recording (optional)

Current experience: 
https://user-images.githubusercontent.com/26996883/125514021-9df331e8-8bf0-4604-8cbc-d423eb296562.mov

Prior experience shows this flow:

<img width="955" alt="Screen Shot 2021-07-13 at 1 34 25 PM" src="https://user-images.githubusercontent.com/26996883/125514104-d71de506-f30e-4140-9e0c-21cd0ad9f7ee.png">

## WordPress information
- WordPress version: 5.8-RC2-51407
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? No, using WP Beta Tester plugin. 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes.

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 89

**Comment by annezazu** [comment] 2021-07-14 18:05
Just tested this with RC3 and still can confirm.

**Comment by ntsekouras** [comment] 2021-07-14 20:59
I did some testing now and it seems to work properly.. 🤔 

`Query Loop` block will fallback to just showing the `block variations` if no matching patterns are found (internally this is handled by `__experimentalBlockPatternSetup`. So a possible thing here could be using a theme that removes core patterns with something like `remove_theme_support( 'core-block-patterns' );`? What theme do you test this with?

**Comment by annezazu** [comment] 2021-07-14 21:45
Hmm. Just tried with Twenty Twenty-One, Twenty Twenty, Twenty Nineteen, and Twenty Seventeen just for fun :) All replicated the same problem. No patterns appear and only the block variations show.

**Comment by Mamaduka** [comment] 2021-07-15 05:06
This is what I'm seeing when testing with TT1 and TT1 Blocks. WordPress 5.8-RC3 with and without Gutenberg active.


https://user-images.githubusercontent.com/240569/125731829-85ac711f-8ee9-4503-a001-acdad9acb779.mp4

**Comment by annezazu** [comment] 2021-07-15 05:32
Spun up a new test site with the same setup (5.3RC, no GB, using WP Beta Tester, TT1 blocks latest version). On my first test site, I can see the problem at hand. On the second test site, it works. I tried completely removing the TT1 blocks theme over SSH and reinstalling :/ Tried enabling a debug log but no errors relate. Tried using the nightly RC version but still can replicate. 

If no one else can replicate, can mark this as an edge case of some sort!

**Comment by ntsekouras** [comment] 2021-07-15 05:46
@annezazu if you click on the main inserter and go to the `patterns` tab, can you see the `Query` patterns there?

**Comment by bobbingwide** [comment] 2021-07-15 11:36
I tried this with a child theme of Twenty Eleven. Patterns are being listed.
![image](https://user-images.githubusercontent.com/2474435/125781711-97ad51fc-7dea-4754-8460-a43bb85339db.png)

**Comment by youknowriad** [comment] 2021-07-15 12:23
I can't reproduce the issue either. Tried several configuration and patterns are showing up for me.

**Comment by youknowriad** [comment] 2021-07-15 12:26
Closing this as everything seems correct for a few of us. If we manage to find the conditions that trigger this we can reopen.

**Closed as completed by youknowriad** 2021-07-15 12:26 UTC
Labels: [Type] Bug, [Block] Query Loop

**Comment by annezazu** [comment] 2021-07-15 16:16
Noting here for good measure that I tried with the same site in a different browser with a cleared cache and was able to get the query loop block to work as expected. Not sure what's going on but keeping this closed as it seems like a fluke :)
