### ISSUE TITLE
Post Author Biography: Allow it to be previewed in the editor

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#51263] opened 2023-06-06 10:08 UTC
The author biography is edited through the user profile, it would be nice to preview it in the editor. So, instead of seeing what's on the left saying "Author Biography" we'd see what's on the right without having to preview it live.

| Current | Suggested |
| --- | --- |
| <img width="714" alt="Captura de ecrã 2023-06-06, às 10 57 32" src="https://github.com/WordPress/gutenberg/assets/65220155/4bd008ed-58e4-4803-b644-875ac4fc6a6a"> |  <img width="968" alt="Captura de ecrã 2023-06-06, às 11 05 43" src="https://github.com/WordPress/gutenberg/assets/65220155/d8358390-e4a2-45c8-af23-5cae09477b16"> |

**Comment by aurooba** [comment] 2023-06-08 00:24
@beafialho I tested this in core WordPress 6.2.2 and with the Gutenberg installed, and I see the Author biography preview in both the post editor and in the Site Editor. Could you share more information about your environment?

**Comment by t-hamano** [comment] 2023-09-23 08:30
I also couldn't reproduce this problem with the latest Gutenberg trunk.

This block should work as follows in the editor:

- In the Query Loop Block: The biography of the author who posted the article will be displayed.
- In the Post: The biography of the author who posted the article will be displayed.
- In the Single Template: It will display "Author Biography". However, this is expected behavior since the Single Post Template is not tied to a specific post in the editor.

![bio](https://github.com/WordPress/gutenberg/assets/54422211/d6107223-d01b-4519-b3f3-a6fae17d6b77)

This behavior does not change between the Author block (`core/post-author`) and the Author Biography block (`core/post-author-biography`).

I would like to close this issue, but if the issue is not resolved, please feel free to comment.

**Closed as not planned by t-hamano** 2023-09-23 08:30 UTC
Labels: [Block] Post Author
