### ISSUE TITLE
Problem redoing after undoing to start of history in some situations

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#40277] opened 2022-04-12 14:47 UTC
### Description

It's sometimes possible to lose editor undo history by undoing to the start of the editor history. In some situations when you try to redo the history it is no longer available.

### Step-by-step reproduction instructions

With top toolbar option enabled (haven't tried with inline toolbar):

1. Open editor and type a single letter (e.g. `a`)
2. Press `cmd+z` to undo. Note the format toolbar is reduced to just a couple of options
3. Press ellipsis menu on toolbar to open, then again to close
4. Press `cmd+z` to undo again. Note the format toolbar has no options
5. Try to redo with `cmd+shift+z` and it's not possible to undo the typed letter `a` - history has been lost

This is the simplest test case I can come up. I think there might be other situations where it could also trigger.

### Environment info

- WordPress 5.9.3
- Gutenberg 13.0.0 RC 3
- Chrome 100.0.4896.79 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-12-27 14:21
Hi, @johngodley

I couldn't reproduce the issue using WP 6.1.2 and Gutenberg 14.8.

Does this only happen when using keyboard shortcuts? Asking because the second `cmd+z` can cause focus loss in the editor, which prevents us from using the global shortcuts. See https://github.com/WordPress/gutenberg/pull/45151#issuecomment-1285544700.

**Comment by johngodley** [comment] 2022-12-27 19:39
Yes this still happens in WP 6.1.2 / Gutenberg 14.8. I'm following the above steps using keyboard shortcuts.

**Comment by youknowriad** [comment] 2023-05-25 06:22
I can't reproduce this personally either. I think we need more details here, do you have a screenshot or something?

**Comment by johngodley** [comment] 2023-05-25 06:50
It happens every time if I follow the steps exactly. This is on 15.8.1.

At 0.04 I press `cmd+z`. I don't focus the editor after I press the ellipsis. At 0.10 I press `cmd+z` again. At 0.13 I repeatedly press `cmd+shift+z` to try and get back my undo, but it's now gone, even if I do focus in the editor.

https://github.com/WordPress/gutenberg/assets/1277682/8045460a-e2df-4ab9-8a0d-b89e725409d4

**Comment by youknowriad** [comment] 2023-05-25 07:17
So actually almost everything is behaving as expected here, there are two small issues but both unrelated with undo/redo history.

 1- First step, you click the "type / to choose a block". This creates a paragraph block (recorded undo step)
 2- You type something "a" or "cat" or whatever. This counts as a single undo step as well.
 3- First: Ctrl + Z. You're emptying the paragraph. **First bug** The format toolbar is gone. I'm not entirely certain why that happens especially since it's there for empty paragraphs when you create them.
 4- Open/close menu does nothing
 5- Second: Ctrl + Z. The paragraph is removed. So no block selected, no toolbar. **Second bug** There's a focus loss happening. Meaning keyboard shortcuts won't work anymore including the `Ctrl + shift + z` to redo. But if you click anywhere on the page and try `Ctrl + shift + z` it's going to work as expected.

Note that the "focus loss" doesn't happen if you don't open/close the toolbar in the intermediary step.

**Comment by johngodley** [comment] 2023-05-25 07:22
> But if you click anywhere on the page and try Ctrl + shift + z it's going to work as expected.

This bit doesn't work - if you click into the editor and then redo the previously entered text has also been lost.

**Comment by youknowriad** [comment] 2023-05-25 07:29
Not in my tests, there must be something else that we're missing.

https://github.com/WordPress/gutenberg/assets/272444/54c13fbb-c5c0-4745-a21b-43d9ca6042c6

**Comment by johngodley** [comment] 2023-05-25 07:46
Ok I think the difference is that at 0:18 you click in the toolbar. If I repeat that action then the redo history is fine, but if you don't, the history is lost.

So, after the open/close ellipsis, press keyboard undo and then click into the editor and keyboard redo - no content.

**Comment by youknowriad** [comment] 2023-05-25 10:35
Yes, this is what I meant by "click anywhere on the page" :)

**Comment by Mamaduka** [comment] 2024-11-14 06:54
Is this still an issue? I think even the originally reported problem was related to the focus loss and not "History" handlers.

**Comment by youknowriad** [comment] 2024-11-14 08:43
Yes, I think we can close the issue.

**Closed as completed by youknowriad** 2024-11-14 08:43 UTC
Labels: [Type] Bug, [Feature] History
