### ISSUE TITLE
Custom Blocks don't show up in Widgets

### ISSUE THREAD

**Issue by JanP2ER** [WordPress/gutenberg#15644] opened 2019-05-15 10:13 UTC
**Describe the bug**

Custom-created Blocks can't be accessed in the widget-editor (e.g. in the Footer)

**To reproduce**
1. Register custom block
2. Click on 'Gutenberg' --> 'Widgets'
3. Try to add a new block to any selection
4. Custom blocks don't show up

**Expected behavior**
Custom created blocks should be displayed and accessible.

**Screenshots**
Block selection of regular posts:
![Bildschirmfoto 2019-05-15 um 12 04 37](https://user-images.githubusercontent.com/40175971/57767617-1c519e00-770a-11e9-90fe-86ab3e72fed1.png)

Block selection of widgets:
![Bildschirmfoto 2019-05-15 um 12 05 17](https://user-images.githubusercontent.com/40175971/57767701-47d48880-770a-11e9-91f8-222f0a928b4b.png)

**Desktop**
 - OS: macOS10.14.4
 - Browser: all browsers

**Additional context**
- Gutenberg version: 5.7.0
- Wordpress version: 5.2

**Comment by swissspidy** [comment] 2019-05-23 08:51
How did you register your block types? Have you verified your scripts are loaded on that screen?

**Comment by adambiggs** [comment] 2020-05-12 18:27
I just ran into this issue. @swissspidy do you have any more info about how custom blocks should be registered so they show up in the widget editor?

I would have expected that if a block is registered successfully and shows up when editing a post, that it would automatically also show up in the widget editor, but that doesn't seem to be the case.

**Comment by adamziel** [comment] 2020-09-17 13:56
The root cause are these two checks:

https://github.com/WordPress/wordpress-develop/blob/23528d419ab2968f250392e8552095783b138fec/src/wp-includes/script-loader.php#L2165
https://github.com/WordPress/wordpress-develop/blob/23528d419ab2968f250392e8552095783b138fec/src/wp-includes/script-loader.php#L2199

Neither widgets nor navigation editors are marked block editor pages which seems to be required for custom block types to be loaded. Unfortunately the resolution is not as simple as marking them as block editor pages since it results in the following:

<img width="1129" alt="Zrzut ekranu 2020-09-17 o 15 50 53" src="https://user-images.githubusercontent.com/205419/93480341-9ea13200-f8fd-11ea-8b2c-8140ff5a7ab2.png">

It seems like `is_block_editor()` is responsible for too many things at once. I suggest resolving this one by updating `script-loader.php` to rely on a filter as follows:

```php
	$is_block_editor_screen = ( $current_screen instanceof WP_Screen ) && ! $current_screen->is_block_editor();
	$should_load_block_scripts_and_styles = apply_filters( 'should_load_block_scripts_and_styles', $is_block_editor_screen, $current_screen );
	if ( is_admin() && ! $should_load_block_scripts_and_styles ) {
		return;
	}
```

**Comment by adamziel** [comment] 2020-09-17 14:18
Since this requires updating the core, I created a core PR and a Trac ticket:

https://github.com/WordPress/wordpress-develop/pull/537
https://core.trac.wordpress.org/ticket/51330

**Comment by annezazu** [comment] 2020-09-24 01:38
Removing the needs testing label and changing this to a WP Core Bug since this requires a core update.

**Comment by adamziel** [comment] 2020-10-05 11:49
Now that the core patch is merged, I started working on the Gutenberg part here: https://github.com/WordPress/gutenberg/pull/25826

**Closed** 2020-10-07 12:12 UTC
Labels: [Feature] Widgets Screen, [Type] WP Core Bug
