### ISSUE TITLE
Code editor adds <br> to style

### ISSUE THREAD

**Issue by vladaman** [WordPress/gutenberg#12668] opened 2018-12-07 07:41 UTC
When using new Code Editor, it adds <br> tags into style tag.

![screenshot from 2018-12-07 08-40-45](https://user-images.githubusercontent.com/907206/49634038-d88c9700-f9fb-11e8-91ab-62a55c127561.png)

**Comment by UserBOE** [comment] 2018-12-08 21:34
Yes, having the exact same issue on my site. It's really screwing up pages and posts.

**Comment by TimothyBJacobs** [comment] 2018-12-09 01:14
Have you tried putting your styles inside the Custom HTML block?

**Comment by youknowriad** [comment] 2019-04-22 11:50
I confirm the issue but I noticed that I had the same issue with the classic editor too. And yes using the custom HTML block seems like a good workaround (I confirmed it works)

**Comment by youknowriad** [comment] 2019-04-22 11:55
So this looks like a duplicate of #9056 though

**Closed by youknowriad** 2019-04-22 11:55 UTC
Labels: Code Editor, [Type] Bug

**Comment by josefanderson215** [comment] 2020-05-22 13:42
remove_filter('the_content', 'wpautop');
