### ISSUE TITLE
Pattern previews do not load reliably

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#33307] opened 2021-07-08 18:18 UTC
## Description
I've noticed in my testing of 5.8 that pattern previews are not loading reliably. Sometimes, they do not load at all.

## Step-by-step reproduction instructions
1. Open the Block Inserter.
2. Click patterns.
3. Observe patterns not loading correctly.

Sometimes, they do load, but fail after returning to blocks, and clicking patterns again. Other times you need to refresh the page after they load successfully to trigger the issue again.

This also happens when viewing pattern suggestions for a specific block.

## Expected behavior
Block pattern previews should display.

## Actual behavior
They do not.

## Screenshots or screen recording (optional)
![Some previews rendered](https://user-images.githubusercontent.com/359867/124971190-e614be00-dff6-11eb-801c-8a277efebd94.png)

![Block level pattern suggestions not previewing](https://user-images.githubusercontent.com/359867/124971315-08a6d700-dff7-11eb-9b71-04815500990f.png)

![No previews loading](https://user-images.githubusercontent.com/359867/124971363-16f4f300-dff7-11eb-96c2-49d0e2200588.png)

## WordPress information
- WordPress version: 5.8 RC2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook
- Operating system: MacOS 10.15.x
- Browser: Reproduced in Firefox nightly (`91.0a1 (2021-07-07) (64-bit)`) and `Version 89.0.4389.128 (Official Build) (x86_64)`

**Comment by desrosj** [comment] 2021-07-08 18:28
Also just noticed that this happens when choosing a layout when inserting a Query Loop block.

![Screen Shot 2021-07-08 at 14 28 01](https://user-images.githubusercontent.com/359867/124972792-c54d6800-dff8-11eb-94bb-db4ce29d116c.png)

**Comment by skorasaurus** [comment] 2021-07-08 19:02
Hi, 

Thanks for reporting; 
This appears to be a duplicate of https://github.com/WordPress/gutenberg/issues/29436  . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue. Please reopen and comment if this is different than that issue.

**Closed as completed by skorasaurus** 2021-07-08 19:02 UTC
Labels: [Status] Duplicate
