### ISSUE TITLE
wp-env: mysqlcheck: Got error: 1045: Access denied for user 'username_here'@'xxx.xx.x.x' (using password: YES) when trying to connect

### ISSUE THREAD

**Issue by leeshadle** [WordPress/gutenberg#29847] opened 2021-03-13 02:49 UTC
## Description
 Getting an 'Access denied error' from mysql when starting a local WordPress environment using the wp-env package. 

## Step-by-step reproduction instructions
1. Create a block using create-block command:
npx @wordpress/create-block --wp-scripts --wp-env wp-block

2. Start wp-env using command:
npx wp-env start

3. Get an error in the terminal:
mysqlcheck: Got error: 1045: Access denied for user 'username_here'@'xxx.xx.x.x' (using password: YES) when trying to connect

4. Get an error when I go to localhost:8888:
Error establishing a database connection

## Code snippet (optional)
.wp-env.json:
{
	"core": "WordPress/WordPress",
	"plugins": [
		"."
	]
}

## WordPress information
- docker version: 3.2.1
- wp-env version: 3.0.2
- wp-scripts version: 13.0.3
- node version: 12.16.1

## Device information
- Device: Desktop
- Operating system: macOS Catalina version 10.15.7
- Browser: Chrome Version 89.0.4389.82

Thank you for your help!!

**Comment by renatonascalves** [comment] 2021-03-13 23:16
I'm getting the same error!

**Comment by ribaricplusplus** [comment] 2021-03-13 23:58
This is a duplicate of: https://github.com/WordPress/gutenberg/issues/29752

The issue was fixed in https://github.com/WordPress/gutenberg/pull/29800 but that version of `@wordpress/env` hasn't been pushed to NPM yet, so if you want the fix you'll need to manually install the latest version of `@wordpress/env`.

Two ways to install the latest version that I know of:
1. Local dependency: Check out the gutenberg repository, navigate to `packages/env`, run `npm pack`, and then install the produced tarball
2. Global dependency: Check out the gutenberg repository, navigate to `packages/env`, run `npm install -g .` (haven't done this personally but it should work)

If you previously used `wp-env` in a project, unfortunately you'll have to run `wp-env destroy` and then `wp-env start` in order to make it work (after you update `wp-env` as described above).

**Comment by renatonascalves** [comment] 2021-03-14 00:20
I tried two ways without luck (getting the same error).

`npm i @wordpress/env@latest`
`npm i @wordpress/env@next`

Destroying and starting again from scratch. Both are giving me the same .

```
✖ Error while running docker-compose command.
Creating bf292d91513c610b30731f7ee397005c_cli_run ... 
Creating bf292d91513c610b30731f7ee397005c_cli_run ... done
mysqlcheck: Got error: 1045: Access denied for user 'username_here'@'192.168.32.5' (using password: YES) when trying to connect
```

**Comment by ribaricplusplus** [comment] 2021-03-14 00:21
It's not pushed to NPM, you're not going to be able to install it that way.

**Comment by renatonascalves** [comment] 2021-03-14 00:22
Ops! I see!

**Comment by renatonascalves** [comment] 2021-03-14 13:21
Installing globally solved it for me.

**Comment by talldan** [comment] 2021-03-15 03:57
Closing as a duplicate of #29752.

**Closed by talldan** 2021-03-15 03:57 UTC

**Comment by leeshadle** [comment] 2021-03-15 22:49
> Here are 2 ways to install the latest version:
> 

>1. Local dependency: Clone the gutenberg repository, navigate to packages/env, run npm pack, and then install the produced tarball
>2. Global dependency: Clone the gutenberg repository, navigate to packages/env, run npm install -g . (haven't done this personally but it should work)

Installing globally (option 2) worked for me too!

It doesn't work if @wordpress/env is already installed globallly.  If that's the case run `npm uninstall -g @wordpress/env` and then run `npm install -g .` from the `packages/env` directory

Thank you!!

**Comment by nicolad** [comment] 2021-03-16 14:31
> It's not pushed to NPM, you're not going to be able to install it that way.

setting the version this way might work:

`"@wordpress/env": "https://gitpkg.now.sh/WordPress/gutenberg/packages/env?trunk"`

as seen in [jetpack](https://github.com/Automattic/jetpack/pull/19151/files#diff-447a13a9521e260aaa7d493ad3e2e8d85e1939d40daab6926e633091a658d47cR29) :point_up:

**Comment by ribaricplusplus** [comment] 2021-03-16 14:33
There are discussions in WordPress slack about this, and it's going to be updated in npm very soon.

**Comment by diegohaz** [comment] 2021-03-18 12:57
`npx @wordpress/env@next start` worked for me.

**Comment by porada** [comment] 2021-05-12 16:54
I just encountered this issue and only the following worked for me:

```sh
npx @wordpress/env@next destroy
npx @wordpress/env@next start
```
