### ISSUE TITLE
Indenting paragraph in HTML view causes an error

### ISSUE THREAD

**Issue by vesaraiskila** [WordPress/gutenberg#14672] opened 2019-03-28 01:46 UTC
**Describe the bug**
Using `<p style="padding-left: 30px;">` in a block causes an error message

**To Reproduce**
1. Create a new text block.
2. Choose to edit it in HTML format.
3. Enter the following in the block:

`<p style="padding-left: 30px;">This is a paragraph to be indented.</p>`

4: Click the three dots to open the dialog to switch to visual editing mode.

**Expected behavior**
The block is shown visually.

**Observed behavior**
The error "This block contains unexpected or invalid content" is shown. (In Finnish in the screensot below)

**Screenshots**
The error message:
![image](https://user-images.githubusercontent.com/46203937/55122955-77531580-5109-11e9-879d-04b86496f8d4.png)

When selecting "Ratkaise" (=Resolve) the following is  @shown:
![image](https://user-images.githubusercontent.com/46203937/55123313-afa72380-510a-11e9-84e6-3795e40bf1ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Opera
 - Browser version: 58
 - WordPress version: 5.1.1

@swissspidy

**Comment by michaelswengel** [comment] 2019-03-28 15:32
We really need the ability to indent natively in Gutenberg. This is a very important feature for many.

**Comment by swissspidy** [comment] 2019-03-29 09:53
Let's close this in favor of #14554.

Getting a validation error after changing a block's expected markup is intended behavior.

**Closed by swissspidy** 2019-03-29 09:53 UTC
Labels: [Block] Paragraph

**Comment by vesaraiskila** [comment] 2019-03-29 12:23
@swissspidy, I would like to know in what way

`<p style="padding-left: 30px;"> </p>`

is **non-expected**. It is, after all (as far as I know) valid HTML.

In addition, after resolving the error so that the desired indentation is maintained (ie, by converting the block to HTML), editing the block is cumbersome, as it can only be edited in HTML format, not graphically.

**Comment by aduth** [comment] 2019-03-29 12:38
Block validation is not simply a matter of verifying that the contents are valid HTML. The paragraph block cannot support this style attribute. The message is shown because it otherwise risks content loss (it can't handle the style, and thus it would be removed next time a save occurs).

There are pending discussion for ideas in improving block invalidation at #7604.

Based on how the paragraph block works, I suspect you may find some luck with the following variation:

```html
<p><span style="padding-left: 40px;"></span>Hello</p>
```

**Comment by vesaraiskila** [comment] 2019-03-30 09:58
Alas, that seems to indent only the first line, not the entire paragraph as
required. And it, too, invokes the error dialog.

pe 29. maalisk. 2019 klo 14.38 Andrew Duthie (notifications@github.com)
kirjoitti:

**Comment by phpbits** [comment] 2020-02-11 13:39
@vesaraiskila If you are still looking for a way to indent Paragraph on Gutenberg editor, you can use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I've recently added Indent and Outdent Formats. Here's how it works. Thanks!

![Indenting paragraph](https://user-images.githubusercontent.com/3365507/74241389-e849ee80-4d16-11ea-90e2-ff71dc35c39a.gif)
