### ISSUE TITLE
Placeholders to render theme colors alongside custom colors

### ISSUE THREAD

**Issue by javiercasares** [WordPress/gutenberg#64734] opened 2024-08-23 05:20 UTC
### Description

Having in mind that, probably, the theme colors are “more important” than the personalized colors, when you have both, blocks only show the personalized colors by default in the block (for example, in the Cover block), although in the sidebar all colors appears correctly.

Tested in WordPress 6.6.

### Step-by-step reproduction instructions

1. Have some theme colors (not personalized colors).
2. Add a Cover block. It shows to pick one theme color.
3. Add some personalized colors.
4. Add a cover block. It only shows the personalized colors in the block. In the sidebar are all the colors.

### Screenshots, screen recording, code snippet

![Cover only with personalized colors](https://github.com/user-attachments/assets/077a8e67-9bce-4557-9146-07431fa0de68)
![Text only with personalized colors](https://github.com/user-attachments/assets/b0b7e2c7-7758-4520-9552-945527794ae0)
![Cover Sidebar with all the colors](https://github.com/user-attachments/assets/ee77f40e-cc1f-45cb-bd01-8673e6ad8275)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ndiego** [comment] 2024-08-26 01:08
Yup, I can confirm. This behavior is a bit strange. 

| TT4 With Custom Colors | 
|-|
|<img width="1385" alt="image" src="https://github.com/user-attachments/assets/5884ced6-46f2-4cb2-b687-e939db046486">|

| TT4 **Without** Custom Colors | 
|-|
|<img width="1384" alt="image" src="https://github.com/user-attachments/assets/f0997407-e24a-47a2-84df-e6b73f152a7b">|

**Comment by AKSHAT2802** [comment] 2024-10-25 10:01
Hii @javiercasares.
This issue seems to be connected to https://github.com/WordPress/gutenberg/issues/64857.

I have raised a PR for the solution.[PR Link](https://github.com/WordPress/gutenberg/pull/65148).
Please reach out in case of any suggestions or feedback :)

**Comment by richtabor** [comment] 2024-11-07 14:16
> This issue seems to be connected to https://github.com/WordPress/gutenberg/issues/64857.

Yes, this is a duplicate of #64857. Let's close this and push that one ahead as there is more discussion there.

**Closed as completed by richtabor** 2024-11-07 14:16 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Cover
