### ISSUE TITLE
Code Editor: Text removed on Syntax Error in Link

### ISSUE THREAD

**Issue by benjaminstocker** [WordPress/gutenberg#8521] opened 2018-08-04 08:44 UTC
To reproduce the Problem, create the following Text in the Code Editor:

<code>Test: &lt;a href="/to/file"&gt;To File&lt;/a&gt;. Text will continue here.</code>

This will work fine when saving it. Now, remove the second Double-Apostroph (“), save again and see what happens. The entire Text beginning with the Link gets removed. The Editor now only shows: Test:

Thanks for having a look into this.
Kind regards, Benjamin

**Comment by designsimply** [comment] 2018-08-06 21:11
I tested this with Gutenberg 3.4 and I can confirm that if you try save malformed HTML in the code editor in a paragraph block the bad HTML and everything after it is removed. ([3m55s](https://cloudup.com/cJPAcJoM-Rf))

The removal of bad or malformed HTML is done by design. One of the reasons for Gutenberg is to allow us to create content without the need to switch to the code editor. The thinking behind this is that while code editor is important for developers and people that understand HTML, it is not important for everyone. In cases like the one you have outlined above, past advice has been to use the Custom HTML block and it will show you the validation errors so that you can correct them before converting to blocks where validation is more strict. Will this work for you?

**Comment by benjaminstocker** [comment] 2018-08-07 07:05
Thanks for your reply and for the Guide! As for me, that is ok and I will give it a try!

However, I'm thinking on all that people using existing Blog Posts/Articles with - maybe - malformed HTML. If Gutenberg is removing everything after the invalid HTML, this will confuse the User. Maybe it would be a good Idea to display a Warning when such a Post is opened in Gutenberg the first time.

**Comment by ZebulanStanphill** [comment] 2018-08-20 15:45
#7604 has some mockups of ways to notify the user when the HTML content has been modified due to malformed content.

**Comment by youknowriad** [comment] 2018-11-27 10:20
The block validation experience have been improved a lot since. Let's close this issue now as not really actionable.

**Closed by youknowriad** 2018-11-27 10:20 UTC
Labels: Code Editor, [Type] Help Request
