### ISSUE TITLE
Wrong author is assigned to post in Multisite

### ISSUE THREAD

**Issue by lordmatt** [WordPress/gutenberg#11000] opened 2018-10-24 11:03 UTC
With the classic editor, we are able to write a post and set a different user as the author. In a multi-blog network, this has proven vital for some of our users' workflow. However, with Gutenberg this option is noticeably absent. I saw a ticket for this issue that was opened last year but that has already been marked as closed. However, I was not able to find anything like a solution.

The current workaround is to switch to classic, assign the correct author and switch back. Obviously, this is sub-optimal.

**Comment by Soean** [comment] 2018-10-24 11:34
It is possible in a default WP installation, so maybe it's an issue on Multisite.

**Comment by lordmatt** [comment] 2018-10-24 12:18
I've done some testing and it seems to only affect some blogs.

It is most noticeable where the Super Admin (network admin) is creating content on a blog where they would otherwise only be a participant.

**Comment by Soean** [comment] 2018-10-24 19:32
- You need the user cap `edit_others_posts`
- Subscribers are not in the dropdown.
- If you only have one user, the field is hidden.
https://github.com/WordPress/gutenberg/blob/94f54892c214ebd014ec126a9575b7e902198ad9/packages/editor/src/components/post-author/check.js#L18-L19

**Comment by danielbachhuber** [comment] 2018-10-30 12:11
@lordmatt Did @Soean's comment above answer your question?

**Comment by mcsf** [comment] 2018-11-26 15:31
Closing as stale. Feel free to reopen.

**Comment by iandunn** [comment] 2019-06-21 08:02
I've run into this several times, and it feels like a bug to me, since the wrong author is attributed to the post.

**Comment by lordmatt** [comment] 2019-07-01 06:58
I agree. The desired behaviour should probably be to treat the super admin as a temporary contributor. That or detect that the user is not in the approved author list and offer the option which is much the same.

**Comment by dd32** [comment] 2019-10-22 07:02
https://meta.trac.wordpress.org/ticket/4768 is another example of how it can happen for multisite.

If a post which is assigned to a user id that doesn't have an explicit role on the site is edited, the author is forced to be changed to a user who does have a role.

It also seems likely that editing a post whose author had been removed from a given site would also reproduce it.

**Comment by SergeyBiryukov** [comment] 2020-09-17 21:38
Just stumbled upon this on a Rosetta site (https://ru.wordpress.org/).

In the Posts list, the author was displayed correctly, but  when editing a post, only three users were displayed instead of the actual author with the Locale Manager role:
* A couple of (no longer active) users with a Contributor role.
* `wordpressdotorg` user.

When accidentally setting the author to `wordpressdotorg`, the post became inaccessible for further editing.

The majority of users on Rosetta sites have a custom role (Locale Manager, General Translation Editor, Translation Editor), however it looks like the Author box in the block editor doesn't handle that correctly.

I'm not sure whether it's a bug in Gutenberg, REST API, or the custom role implementation on WordPress.org.

**Comment by TimothyBJacobs** [comment] 2020-10-25 01:42
AFAICT this needs to be fixed in Core by adjusting the `the_block_editor_meta_box_post_form_hidden_fields()` function. See https://core.trac.wordpress.org/ticket/50754#comment:3.

**Closed by TimothyBJacobs** 2020-10-25 01:42 UTC
Labels: Needs Testing, REST API Interaction, [Feature] Multisite
