### ISSUE TITLE
Child Navigation default background with Dark Header 

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/gutenberg#40908] opened 2022-05-07 17:08 UTC
WordPress 6.0 RC1, Twenty Twenty Two, Theme Unit Test Data installed. 

![image](https://user-images.githubusercontent.com/5519705/167264511-f3f5f936-539e-4d4a-b0ae-ee1eace1a704.png)

## What problem does this address?
Default installs with Twenty Twenty Two active + child navigation item have a default background of white font on white background. The default header is a dark background. I can't see the child navigation text without first adjusting the navigation block background color. 

## What is your proposed solution?
All navigation block backgrounds should Inherit the same background color as the default header. This should not be transparent.

**Comment by bph** [comment] 2022-05-07 18:12
Great find @courtneyr-dev 
I am not sure if that's a Gutenberg issue, though. It looks to me that this needs to be fixed via Twenty-Twenty-Two theme,  I filed [a trac ticket](https://core.trac.wordpress.org/ticket/55697) as well. 
.. pinging @jffng

**Comment by getsource** [comment] 2022-05-17 05:33
Folks chatted about this issue in a [Core triage session today](https://wordpress.slack.com/archives/C02RQBWTW/p1652764257869639).

Leaving a note here because [follow-up testing on the Core ticket](https://core.trac.wordpress.org/ticket/55697#comment:10) (comment from @carolinan) mentions that the issue is with link color specificity in the Editor.

The Core ticket is still open because a workaround is being discussed.

**Comment by carolinan** [comment] 2022-09-13 08:48
Can confirm that this is still an issue in current Gutenberg trunk (14.0.3+).

**Comment by jasmussen** [comment] 2022-10-03 12:13
This should be fixed by #44578.

**Closed as completed by jasmussen** 2022-10-03 12:13 UTC
Labels: [Type] Bug, [Type] WP Core Ticket, [Block] Navigation

**Comment by bph** [comment] 2022-10-06 12:19
Tested it again this morning and yes, it has been fixed.  
Using WordPress 6.1 Beta 3 alone didn't fix it. It only is resolved after installing Gutenberg Nightly (includes 14.3 RC). 
## Before 

https://user-images.githubusercontent.com/39980/194310558-d7ee6839-ab38-4f4f-97b9-64755d8688e9.mp4

## After

https://user-images.githubusercontent.com/39980/194310715-25a3a7d9-d97b-4d84-8cd2-a3496a7038da.mp4


[Also closed trac issue as reported upstream](https://core.trac.wordpress.org/ticket/55697#comment:26)
