### ISSUE TITLE
Image block: Display bugs with inline images in captions

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#22808] opened 2020-06-01 19:33 UTC
**Describe the bug**
If someone puts LaTex in an image caption, it renders as an image and adopts that block's alignment. Also, the LaTex does not render inline as expected, and appears as a separate block.

**To reproduce**
1. Add an image and add some LaTeX to its caption, like `$latex d_f$`
2. Set image to Wide or Full width
3. Add another image with LaTex in its caption. Keep default alignment.

**Expected behavior**
LaTex renders as a small image, and it should appear inline like this:
![Screen Shot 2020-06-01 at 1 27 31 PM](https://user-images.githubusercontent.com/3476361/83446286-ab138480-a40b-11ea-981f-377386cc354a.png)

Instead, it's rendering like this:

**Screenshots**
![Screen Shot 2020-06-01 at 1 18 32 PM](https://user-images.githubusercontent.com/3476361/83446345-bf578180-a40b-11ea-9c20-269195c98ea1.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Has Gutenberg
- If the Gutenberg plugin is installed, which version is it? 8.1.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Current on both

**Additional context**
Brought up here: https://wordpress.com/forums/topic/latex-in-caption-of-full-width-image/

This CSS fixes the too-wide LaTeX and keeps it inline:
```
.entry .entry-content .wp-block-image img :not(.latex) {
    display: block;
}
.wp-block-image.alignfull img :not(.latex), .wp-block-image.alignwide img :not(.latex) {
    width: 100%;
}
```

**Comment by oxyc** [comment] 2020-06-20 16:44
Cannot reproduce in master using Twentytwenty

<img width="1440" alt="Screen Shot 2020-06-20 at 13 43 07" src="https://user-images.githubusercontent.com/302736/85206956-01356280-b2fc-11ea-898f-378db38b22bf.png">

So it seems it's a theme issue. Also since LaTeX is not supported by Gutenberg but added by Jetpack I think this is not the place to provide any defaults.

**Comment by supernovia** [comment] 2020-07-21 19:53
@oxyc sorry I missed your comment! The inline vs block issue seems to be fixed now.

**Comment by talldan** [comment] 2020-12-08 06:08
I've updated the label to reflect that LaTeX isn't supported by default in WordPress, but the issue still happens for me with inline images (and now seems to happen whether the block is aligned or not).

**Comment by paaljoachim** [comment] 2021-02-10 15:23
I am testing using WordPress 5.7 beta 1
Twenty Twenty One.
With only the WordPress Beta Tester plugin activated.
Chrome
OSX 10.15.7

I tested with $latex d_f$ in the image caption as mentioned by @supernovia and noticed no errors.
I also tested adding the $latex d_f$ into the image caption and then adding an inline image. Like so

![Screen Shot 2021-02-10 at 16 22 18](https://user-images.githubusercontent.com/5323259/107530467-2ee95780-6bbc-11eb-88b9-6507d0b4a8ca.png)

I did not notice any errors.
I will close this issue. If I am mistaken then please reopen.

**Closed by paaljoachim** 2021-02-10 15:23 UTC
Labels: [Block] Image, [Type] Bug

**Comment by oxyc** [comment] 2021-02-10 23:41
Did you try it with alignwide/alignfull? Screenshot isn’t at least.

**Comment by paaljoachim** [comment] 2021-02-11 00:24
Retesting.

New post.
Added image block.
Added image. Adjusted to Full Size.
Changed to Full width
Added $latex d_f$ into the caption.
Save draft and previewed.
Looked fine in backend and frontend.

Added an inline image.
Saved draft.
Previewed.
I did not see any display bugs.

I will also ask @tellthemachines to take a look. I will keep it closed for now. Let's see what Isabel notices.

**Comment by tellthemachines** [comment] 2021-02-11 01:23
I can no longer reproduce this either.
