### ISSUE TITLE
blockquote and pullquote blocks should be one block?

### ISSUE THREAD

**Issue by hugobaeta** [WordPress/gutenberg#17562] opened 2019-09-24 21:59 UTC
There are two blocks allowing you to insert blockquotes in the post, one called `blockquote` and the other `pullquote`. They output slightly different markup.

I don't understand the redundancy here: why two blocks that do, semantically, the same thing? Shouldn't this be block styles/options territory?

One uses a `<blockquote>` at the root level, the other is the same but with a `<figure>` wrapper. Wouldn't it be more consistent and flexible to use the `<figure>` wrapper on both blocks?

Better yet, why not make them just one block and provide a block option variation like other blocks do?

Let's discuss!

<img width="342" alt="Screen Shot 2019-09-24 at 2 53 44 PM" src="https://user-images.githubusercontent.com/1514660/65553353-8ad61200-dedb-11e9-8591-6f1be29bae17.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.6)
 - Browser: Chrome
 - Version: 77

**Additional context**
- Gutenberg bundled with core in 5.2.3.

**Comment by youknowriad** [comment] 2019-09-25 08:11
This is a duplicate of #11610 there's some discussion there to explain the reasoning.

**Closed by youknowriad** 2019-09-25 08:11 UTC
