### ISSUE TITLE
List item: Allow user to add nested text which isn't an ordered list or numbered list.

### ISSUE THREAD

**Issue by SNaushadS** [WordPress/gutenberg#13367] opened 2019-01-18 14:21 UTC
**Describe the bug**
Unable to get non-list text in Ordered List Or Unordered List.

**To Reproduce**
1. Create a new post
2. Add a List Block
3. Populate few list items.
4. Use Shift + Enter / Return 
Expectation: New non-list item should be shown below the list item.
5. Observe that such thing doesn't happen.

**Expected behavior**
When using shift+ enter or simply using backspace i should be able to create a nested item which is a non list item.

**Screenshots**
**Current Behavior**
![gutenberg-list-item-details](https://user-images.githubusercontent.com/1532907/51392043-d1f45200-1b59-11e9-9ed2-fe6e8f4e37a1.gif)

When trying to use Shift + Enter
![gutenberg-shift-enter-behaviour](https://user-images.githubusercontent.com/1532907/51392061-e2a4c800-1b59-11e9-853c-7d895f85db2c.gif)

**Desired Behavior:**
![list-with-sub-nonlist](https://user-images.githubusercontent.com/1532907/51392077-ef292080-1b59-11e9-9ca1-d87b4ecbb4d2.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 64.0.2

**Comment by youknowriad** [comment] 2019-01-18 16:05
Thanks for the issue, this is a duplicate of https://github.com/WordPress/gutenberg/pull/13327

**Closed by youknowriad** 2019-01-18 16:05 UTC
