### ISSUE TITLE
Post Navigation Link: Empty Div Tag On No Previous/Next Posts. It Must Be Removed From HTML

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#67340] opened 2024-11-27 09:22 UTC
### Description

If current post have no previous post then previous post link must be absent. But it's empty div tag still remains in HTML:

`<div class="post-navigation-link-previous wp-elements-e4b6b9c8d8fff370d095f2f918844ad5 wp-block-post-navigation-link has-text-color has-contrast-2-color"></div>`

### Step-by-step reproduction instructions

1. Add Previous/Next Post blocks into single post template;
2. Open the first post and check that Previous post link not visible;
3. Look at HTML code and check that empty div tag with `wp-block-post-navigation-link` class still exists.

Expected result: 
The tag should be removed because it's CSS styles may be displayed when the link to the previous post is missing.
For example, If link has background color and padding then it will be displayed as an empty box with no link.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by carolinan** [comment] 2024-11-27 11:24
Duplicate of https://github.com/WordPress/gutenberg/issues/59996

**Closed as not planned by carolinan** 2024-11-27 11:24 UTC
Labels: [Status] Duplicate
