### ISSUE TITLE
Add Support for Custom Devices in the Preview

### ISSUE THREAD

**Issue by abder** [WordPress/gutenberg#67753] opened 2024-12-09 16:28 UTC
**Description:**

Currently, the Gutenberg editor provides built-in device previews for Desktop, Mobile, and Tablet. While these are useful, many developers and designers require additional custom devices to reflect specific breakpoints or scenarios. For example, devices like Laptop, MobileLandscape, or even specific resolutions (e.g., 1440px for large desktops) are commonly used in responsive design workflows.

**Proposed Solution:**
Introduce the ability to add custom devices with their associated breakpoints. A custom device should be defined by:

**Alias:** A unique identifier for the device (e.g., laptop or mobileLandscape).
**Label:** A user-friendly name displayed in the device preview menu (e.g., "Laptop" or "Mobile Landscape").
**Icon:** A visual representation in the device preview menu.
**Style Object:** Defines the styles and breakpoints for the editor canvas when the device is active.

![Image](https://github.com/user-attachments/assets/b043e93a-d63d-47c1-9657-9750d751f4b5)

**Comment by Mamaduka** [comment] 2024-12-09 17:47
This is a duplicate of #65005.

**Closed as not planned** 2024-12-09 17:48 UTC
Labels: [Type] Enhancement, [Feature] Extensibility, [Status] Duplicate
