### ISSUE TITLE
Formatted content isn't always immediately removed when erased

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#14032] opened 2019-02-21 22:12 UTC
Erasing formatted (e.g. bold) content doesn't completely erase it, it appears to remain in state until the next change to the block.

**To Reproduce**

1. Open a new block
2. Start a format, e.g. cmd-b on a Mac to start writing bold text
3. Write content
4. Select the text using "select all", e.g. cmd-a on a Mac
5. Erase the text using the backspace/delete key
6. The content is still in the block even though you can't see it. If you save the post and reload, it will be saved and the content will return. If you instead "Edit as HTML" you'll see the content unaltered; returning to editing visually the content will return. Lastly, if you "unbold" using the toolbar button, the content will return.

Something similar happens when backspacing-through the content instead of using select-all, except that only the last character remains, not the entire block of text. The same behavior _does not_ occur when using the mouse to select the text or holding shift and using the keyboard arrows to select the text.

**Expected behavior**

When erasing content, I expect the content to be removed from the post.

**Screenshots**

![erasing-formatted](https://user-images.githubusercontent.com/465154/53204581-f7152e00-35f9-11e9-83b4-4d9d25915743.gif)
![erasing-formatted-2](https://user-images.githubusercontent.com/465154/53205120-5fb0da80-35fb-11e9-92d6-6b33ca758f4b.gif)
![erasing-formatted-3](https://user-images.githubusercontent.com/465154/53205121-60497100-35fb-11e9-90c3-7145ba389b92.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 72.0.3626.109
 - WordPress 5.0.3

**Comment by iseulde** [comment] 2019-02-22 11:41
Sound like a duplicate of #13911. Additionally, I think this is fixed in Gutenberg 5.1. I'm unable to reproduce. Could you confirm?

**Closed by iseulde** 2019-02-22 11:41 UTC
