### ISSUE TITLE
Blocks Hidden by Metaboxes

### ISSUE THREAD

**Issue by kraftbj** [WordPress/gutenberg#12598] opened 2018-12-04 19:56 UTC
**Describe the bug**
On a site with a number of legacy metaboxes, if I scroll up a fair amount, I can never scroll down far enough to reach the last block, in effect, making it impossible to continue writing.

**To Reproduce**
1. Install a number of plugins that create legacy metaboxes: Jetpack, Genesis theme, Liveblog, Syndication Links, etc
2. Write a number of blocks to ensure plenty of scrolling is needed.
3. Scroll to the top.
4. Scroll to the bottom.

**Expected behavior**
Ability to scroll to the last block.
What happens: The scroll ability stops before the last block comes into view.

**Screenshots**
![2018-12-04 at 13 48](https://user-images.githubusercontent.com/88897/49469040-186d3780-f7cc-11e8-808f-f3ca1329616e.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS X latest
 - Browser: Chrome
 - Version 70.0.3538.110

**Additional context**
On WordPress svn branches/5.0 with RC3 plus anything committed as of r43798-build.

**Comment by youknowriad** [comment] 2018-12-04 20:00
I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/11378 which has been closed as some plugins are triggering php notices. After some discussions, a warning is being added in https://github.com/WordPress/gutenberg/pull/12575 to warn plugin authors about the errors.

**Closed by youknowriad** 2018-12-04 20:00 UTC

**Comment by kraftbj** [comment] 2018-12-04 20:08
This is going to be incredibly painful for support teams.

**Comment by jasmussen** [comment] 2018-12-05 07:14
Yes, both PHP notices and many other things can trigger quirks mode, and quirks mode is the root cause indeed. 

For starters we are showing a JS console warning, and updating the documentation. If the issue continues to grow, we will upgrade the JS console warning to become a full-on notice in the editor.
