### ISSUE TITLE
Unable to copy and paste text from Adobe Illustrator into the visual editor

### ISSUE THREAD

**Issue by carfis** [WordPress/gutenberg#13293] opened 2019-01-11 16:25 UTC
**Describe the bug**
It is not possible to copy and paste text from Adobe Illustrator into a block in the visual editor of Gutenberg. 

**To Reproduce**
1. Go to Adobe Illustrator
2. Select text
3. Cmd C or Ctrl C (Copy the text into the clipboard) 
4. Go to an open document in the visual editor of Gutenberg.
5. Go to a paragraph block
6. Cmd V or Ctrl V

**Expected behavior**
The text from the clipboard gets pasted

**Actual behavior**
No text gets pasted at all inside the visual editor. But if you go to the code editor pasting actually works. I also tried to copy and paste a text from an Adobe Photoshop textfield. There it is actually working to paste into the visual editor as well. Only for Adobe Illustrator it does not work. For Adobe Indesign I was unable to test. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 64.0.2
- Adobe Illustrator 23.0.1

**Additional context**
 WordPress 5.0.3 with Gutenberg 4.8.0 Plugin

**Comment by designsimply** [comment] 2019-01-11 20:28
I am closing it as a duplicate of #11683 to continue the discussion there. Thank you for the report @carfis!

**Closed by designsimply** 2019-01-11 20:28 UTC
Labels: Needs Testing, [Component] Raw Handling
