### ISSUE TITLE
unified toolbar option not remebered after logout

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#11797] opened 2018-11-13 07:43 UTC
The jumping toolbar in Gutenberg is a real nightmare when editing a text with more than one paragraph => very irritating and covers text of the paragraph above! So, the unified toolbar is really essential for real work. But Gutenberg does not remember the setting of this option after logout. Whith every new login you have to activate unified toolbar again (... and again, ... and again, ...)

**Comment by earnjam** [comment] 2018-11-28 15:41
This works for me. It keeps my preferences when I log out and back in. Are you clearing the browser's local storage when you log out? Or are you using private browsing mode or something? 

The main thing to note about these editor preferences is that they are stored in browser's local storage. They aren't stored in the WordPress database (which could be the possible enhancement here). 

The downside of that is that it isn't persistent across devices, so you have to set it anytime you log in to a new location. 

The upside is **_also_** that it isn't persistent across devices, so can have it be unique to the device you are using.

**Comment by burnuser** [comment] 2018-11-29 10:18
Yes, my browser's local cache is cleared when I log out AND I use different browsers for editing my site.

But if other people would not like a permanent setting (stored in userprofile in WP database) of the unified toolbar, it can be an optional/separate setting "store unified toolbar setting permanent".

**Comment by youknowriad** [comment] 2020-01-16 17:28
Going to close this as a duplicate of #15105 which proposes to persists the preferences to the user profile.

**Closed by youknowriad** 2020-01-16 17:28 UTC
Labels: General Interface, [Type] Enhancement
