### ISSUE TITLE
Imgur Embed block doesn't work

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12924] opened 2018-12-16 09:14 UTC
**Describe the bug**
I tried to embed two different Imgur URLs using the Imgur Embed block and both simply returned an error. I tried on two different sites and had the same issue.

![screenshot_261](https://user-images.githubusercontent.com/2078245/50051872-8ae7fb00-016e-11e9-87d2-b0f3731cf893.png)

URLS:
https://imgur.com/gallery/q68SoCn
https://imgur.com/gallery/FLsRjY2

**To Reproduce**
1. Add Imgur Embed Block
2. Enter one of the above Imgur URLs
3. Click the Embed button

**Expected behavior**
Imgur Embed Block should allow you to embed an Imgur URL

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3
- WP 5.0.1

**Comment by maddisondesigns** [comment] 2018-12-16 09:45
Some more testing:

It looks like the Embed must've broken with WP 5.0. It doesn't work when using the Classic Editor either.

![screenshot_263](https://user-images.githubusercontent.com/2078245/50052115-38f5a400-0173-11e9-9d93-80322e9ee354.png)

But it does work fine on a site running 4.9.9 (without Gutenberg but with the Classic Editor V0.5)

![screenshot_262](https://user-images.githubusercontent.com/2078245/50052125-6e9a8d00-0173-11e9-8e1c-d788271cf75a.png)

**Comment by adampatterson** [comment] 2019-05-06 05:04
I noticed the same problem, If you use the embed code it will work but I am not able to center align it.

**Comment by skorasaurus** [comment] 2020-01-22 20:02
I can confirm this; neither link will embed for me and I receive the same in-block message 
("Sorry, this content could not be embedded.")

Using Gutenberg 7.3.0; Firefox 72.0.1)

**Comment by oxyc** [comment] 2020-06-20 23:05
Tested and it seems to work now. I can embed it by 1) pasting the URL, 2) using the embed block 3) using the imgur block.

Could you test it again and see if it works on your site too @maddisondesigns? I only tested the master branch of Gutenberg.

**Comment by maddisondesigns** [comment] 2020-06-22 01:54
@oxyc Just tested Imgur Embed again;

With Gutenberg plugin activated (v8.3.0 )
https://share.getcloudapp.com/4guj1YYQ

Without Gutenberg plugin activated
https://share.getcloudapp.com/OAuBgwE1

And neither option worked (on WP5.4.2).

Is the Master branch the same as the latest plugin version?

**Comment by skorasaurus** [comment] 2020-06-22 15:00
@maddisondesigns 

The master branch is always newer than the plugin version; it contains all commits of code that have been 'officially' approved 
to be included into Gutenberg. 
The master branch is typically updated several times every day and you can view an ongoing list of these at https://github.com/WordPress/gutenberg/commits/master

[gutenberg.zip](https://github.com/WordPress/gutenberg/files/4813960/gutenberg.zip)
I built a zip file of the master branch (as of this commit https://github.com/WordPress/gutenberg/commit/3156d0bbec4983bab009f7fe5dd1b5282df37d18 ) you should be able to unzip this into your plugins directory, activate the plugin and (you'll need to delete the existing gutenberg directory in your plugins folder first)

**Comment by oxyc** [comment] 2020-06-22 15:22
When embedding there should also be an XHR request done to a /wp-json/oembed/1.0/proxy?... url. Could you check your developer tools if there's something there? Does it get some kind of error? This is what a successful request looks like

<img width="1228" alt="Screen Shot 2020-06-22 at 12 12 33" src="https://user-images.githubusercontent.com/302736/85304216-decd5180-b481-11ea-8c4e-6ed69d2c4b6d.png">

[Here's someone](https://wordpress.org/support/topic/embeds-not-working-on-all-websites/) who got the same message for Youtube videos and the XHR request returned `rest_forbidden`. 

I seem to remember at some point I had an issue with oembed requests timing out too early. You could try increasing the timeout limit with:

```php
add_filter( 'http_request_timeout', function () {
  return 30;
} );
```

Also, I think oembed caches responses, so always try with a new imgur URL while debugging.

**Comment by maddisondesigns** [comment] 2020-06-23 04:38
@skorasaurus Thanks for that zip file.

I replaced my existing Gutenberg plugin with the new zip contents, and still couldn't embed anything from Imgur (https://imgur.com/gallery/aXIPvRG). The same thing happened as previously.

<img width="1323" alt="screenshot_407" src="https://user-images.githubusercontent.com/2078245/85360792-83709180-b55d-11ea-8dae-59040b2fb61a.png">

Also tried a different browser (Chrome & Firefox) and clearing the browser cache, but no luck. Here's the updated plugin showing in the Dashboard.

<img width="1046" alt="screenshot_408" src="https://user-images.githubusercontent.com/2078245/85360874-c599d300-b55d-11ea-9cfd-517210558d66.png">

I couldn't see any errors using the dev tools, and that XHR request didn't appear to return any errors either, although it does look different to @oxyc's example above .

<img width="1920" alt="screenshot_409" src="https://user-images.githubusercontent.com/2078245/85361306-e282d600-b55e-11ea-8162-e7295dc0bb56.png">

**Comment by oxyc** [comment] 2020-06-23 10:47
Have you tried disabling all plugins?

It's either that [something has removed](https://github.com/WordPress/WordPress/blob/07f71058c3c5b570160f494bd57c98ebfb850a58/wp-includes/class-wp-oembed.php#L351) the imgur provider. 

Or I guess more likely, that [the HTTP request to imgur fails](https://github.com/WordPress/WordPress/blob/07f71058c3c5b570160f494bd57c98ebfb850a58/wp-includes/class-wp-oembed.php#L545) somehow.

If it was me, I'd add some debug statements (such as using a debugger or eg. `var_dump` would be visible in the XHR response) around those functions to see what gets returned from the HTTP request. I guess there are [plugins that log HTTP requests](https://wordpress.org/plugins/log-http-requests/) also.

**Comment by maddisondesigns** [comment] 2020-06-24 08:26
@oxyc Still no luck.

Have changed themes to a default theme (Twenty Seventeen) and deactivated all plugins except Gutenberg, and still couldn't embed Imgur.

I then installed that _Log HTTP Requests_ plugin as suggested and it looks like it's getting a response of "Permission denied".

<img width="1920" alt="screenshot_410" src="https://user-images.githubusercontent.com/2078245/85521482-a7100680-b647-11ea-9328-eec09b2140b4.png">

**URL:**
```
 https://api.imgur.com/oembed?maxwidth=600&maxheight=788&url=https%3A%2F%2Fimgur.com%2Fgallery%2FF04fLg1&dnt=1&format=json
```
**Request:**
```
{
  "method": "GET",
  "timeout": 5,
  "redirection": 5,
  "httpversion": "1.0",
  "user-agent": "WordPress/5.4.2; http://dev.wordpress-test.com",
  "reject_unsafe_urls": true,
  "blocking": true,
  "headers": [],
  "cookies": [],
  "body": null,
  "compress": false,
  "decompress": true,
  "sslverify": true,
  "sslcertificates": "/Users/anthonyhortin/Documents/sites/dev.wordpress-test.com/wp-includes/certificates/ca-bundle.crt",
  "stream": false,
  "filename": null,
  "limit_response_size": null,
  "_redirection": 5
}
```

**Response:**
```
{
  "headers": {},
  "body": "Permission denied",
  "response": {
    "code": 403,
    "message": "Forbidden"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```

**Comment by oxyc** [comment] 2020-06-24 10:03
Are you using any particular development environment for your local site? Is it a Virtual Machine? I could see if I can reproduce it using your environment.

If it's a VM I'm interested if running `curl  https://api.imgur.com/oembed?maxwidth=600&maxheight=788&url=https%3A%2F%2Fimgur.com%2Fgallery%2FF04fLg1&dnt=1&format=json` to see if it's only in WP or if it happens for the host in general.

**Comment by maddisondesigns** [comment] 2020-06-24 10:42
I'm just using MAMP Pro, running on a separate Mac Mini. Prior to WP 5.0, when this was originally raised, it used to work fine.

Here's an old site on my dev machine running WP 4.9.15. You can see it works. There's a Imgur Embed (https://imgur.com/gallery/F04fLg1) and a Tumblr embed, that I've just added now.
<img width="1821" alt="screenshot_413" src="https://user-images.githubusercontent.com/2078245/85540591-856c4a80-b65a-11ea-8672-a41cee6c7321.png">

Since WP 5.0, it hasn't worked in the Block Editor, but other Embeds do.
<img width="1551" alt="screenshot_414" src="https://user-images.githubusercontent.com/2078245/85540666-a16fec00-b65a-11ea-87a4-0b0688f1584e.png">

And it doesn't work in the Classic Editor either, but other Embeds like Tumblr do.
<img width="1774" alt="screenshot_415" src="https://user-images.githubusercontent.com/2078245/85540761-bba9ca00-b65a-11ea-9038-2b18ae827fad.png">

So, it's very unlikely that it has to do with either my site, computer or environment.

**Comment by enriquesanchez** [comment] 2020-07-16 21:11
Tested on `master` and I was able to embed the two links.

macOS 10.15.5
Firefox 78.0.1
WP 5.4.2 (localhost)

<img width="527" alt="Screen Shot 2020-07-16 at 15 58 16" src="https://user-images.githubusercontent.com/3276087/87722320-7d955700-c77d-11ea-90c0-84ef0d16f149.png">

**Comment by maddisondesigns** [comment] 2020-07-17 06:00
Can you please create me a plugin version of master so that I can try it as It's still not working with Gutenberg v8.5.1.
Thanks.

**Comment by skorasaurus** [comment] 2020-07-20 20:13
@maddisondesigns Try [this build from today, 2020-07-20](https://github.com/WordPress/gutenberg/files/4949844/gutenberg.zip) it contains the 'master' whose most recent commit is https://github.com/WordPress/gutenberg/commit/8d64aa3092d5d9e841895bf2d495565c9a770238

**Comment by maddisondesigns** [comment] 2020-07-21 04:37
Thanks for that plugin. Still no luck, I'm afraid though.

Same results as previously. Using that Log HTTP Requests plugin as suggested above...

**URL:**
```
[0] https://api.imgur.com/oembed?maxwidth=640&maxheight=960&url=https%3A%2F%2Fimgur.com%2Fgallery%2FF04fLg1&dnt=1&format=json 
```

**Request:**
```
{
  "method": "GET",
  "timeout": 5,
  "redirection": 5,
  "httpversion": "1.0",
  "user-agent": "WordPress/5.4.2; http://dev.wordpress-test.com",
  "reject_unsafe_urls": true,
  "blocking": true,
  "headers": [],
  "cookies": [],
  "body": null,
  "compress": false,
  "decompress": true,
  "sslverify": true,
  "sslcertificates": "/Users/anthonyhortin/Documents/sites/dev.wordpress-test.com/wp-includes/certificates/ca-bundle.crt",
  "stream": false,
  "filename": null,
  "limit_response_size": null,
  "_redirection": 5
}
```

**Response:**
```
{
  "headers": {},
  "body": "Permission denied",
  "response": {
    "code": 403,
    "message": "Forbidden"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```

**Comment by annezazu** [comment] 2020-09-24 03:01
@maddisondesigns I wasn't able to replicate this using WordPress 5.5.1 and Gutenberg 9.0. Digging in a bit, I found a 403 response is referenced in [Imgur's documentation](https://api.imgur.com/errorhandling#:~:text=sent%20were%20invalid.-,Status%20Code%3A%20403,and%20have%20valid%20tokens%2Fsecrets.) along with this [stackexchange thread that might be helpful](https://webapps.stackexchange.com/questions/25681/how-to-remedy-imgur-403-forbidden-errors). I'm going to close this out since I can't replicate and it seems to be related to Imgur's API rather than Gutenberg functionality. Feel free to re-open if you believe I'm incorrect!

**Closed by annezazu** 2020-09-24 03:01 UTC
Labels: Needs Testing, [Block] Embed

**Comment by maddisondesigns** [comment] 2020-09-24 04:09
@annezazu Can you please re-open this. It seems very strange that this stopped working with WP 5.0. As mentioned in my second Post above, it works fine in WP 4.9.x, but as soon as you upgrade to WP 5.0, it breaks. I have a test site that is running WP 4.9.15 that I just tried again now, and the Imgur embed still works fine. As soon as I try it on a site with 5.0+ though, it breaks.

This still seems like a WP and/or Gutenberg issue, not an Imgur issue. It's highly improbable that imgur has somehow managed to ban every single one of my local WP sites that happens to be WP5.0+, which is what that StackExchange thread talks about. Also, the 4.9.15 site that I just tried again now, is running http, not https, just like all my other local sites, which is the other thing mentioned in that StackExchange post.

**Comment by draganescu** [comment] 2020-09-24 15:35
Hi @maddisondesigns :) Since:

- the response from Imgur clearly states a permission denied problem
- the embed works in the testing done by others in this thread

... it may be a super edge case you found. I noticed you use a local "dev" https cert, that might be the issue.

All in all, there seems to be no reason to reopen, because since this cannot be reproduced it cannot be fixed.

The only remaining course of action that I can think of is to inspect with "Log HTTP Requests", both WP installs, and see if between 4.9.x and 5.x the actual request to Imgur is different in a substantial way. If it is open another issue to discuss how we can find a reconciliation for that.
