### ISSUE TITLE
Should we migrate old reusable blocks that use deprecated syntax?

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#9070] opened 2018-08-17 07:02 UTC
This issue came up yesterday as a friend had created reusable blocks of a couple of paragraphs that used old, now-deprecated syntax. 

Because all reusable blocks are validated on Gutenberg initialization, this meant even adding a new post caused a JS error message in the console. 

The fix was to insert the old reusable block, edit it, then save it. This process "healed" the syntax and made it up to snuff. 

However that fix is not very discoverable, and it's not unlikely that a lot of users are experiencing block-validation related errors in their JS console, if they've been using reusable blocks for a long time. Can we improve this?

- Can we move or delay the validation of reusable blocks until the point where they are used?
- Can we automatically "edit and save" a reusable block if deprecated markup is detected?
- Can we provide a better error message, perhaps one that helps suggest how to fix it? Perhaps as a notice instead of a console error?

Already now we are showing console warnings in advance of deprecating features. However looking in the console is a very developery thing to do — should we consider showing these messages as notices instead?

**Comment by tofumatt** [comment] 2018-08-23 19:18
I think this is a duplicate of #8015, but your write-up here is great, so I'll cross-post it there 😄

**Comment by tofumatt** [comment] 2018-08-23 19:19
Wait, sorry, I misread this. Not a duplicate; my bad.

**Comment by youknowriad** [comment] 2019-02-14 10:37
Technically speaking we can't migrate the blocks as the migration is JS based and there's no parsing server-side yet. But let's consolidate the discussions about the deprecation/validation/migration flows here #7604

**Closed by youknowriad** 2019-02-14 10:37 UTC
Labels: [Type] Question
