### ISSUE TITLE
Weird popover overlapping when using the `/` quick inserter

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19353] opened 2019-12-27 22:45 UTC
**Describe the bug**
If I'm doing the `/` quick search for a particular block and the popover appears... if I click elsewhere on the page that original popover doesn't disappear and there arises a weird overlapping of popovers.

**To reproduce**
1. Type `/` and search for a block.
2. Leave the popover open without adding the block just yet.
3. Use your mouse and click to open the Block Library from the Top Toolbar.
4. Observe the overlapping because the original popover didn't disappear.

**Expected behavior**
I expect the original popover to disappear when I click elsewhere on the page.

**Screenshots**

![cols-overlapping 2019-12-27 14_29_04](https://user-images.githubusercontent.com/617986/71534969-4a5daa00-28b7-11ea-851d-4974b53fcd8a.gif)

**Desktop (please complete the following information):**
 - Mac OS Catalina
 - Firefox 71.0
 - Gutenberg 7.1

**Comment by earnjam** [comment] 2020-03-20 20:03
This is fun. While testing this one it took on a life of its own! 

![Kapture 2020-03-20 at 16 01 51](https://user-images.githubusercontent.com/4267290/77202214-46ab7f00-6ac4-11ea-8113-a8c92eb1fdef.gif)

**Comment by earnjam** [comment] 2020-05-14 14:15
Just realized this is actually a duplicate of #18918, which you also opened @mapk! 🙂

**Closed by earnjam** 2020-05-14 14:15 UTC
Labels: Needs Dev, [Feature] Inserter, [Package] Block library, [Type] Bug

**Comment by mapk** [comment] 2020-05-14 16:50
All we need is me opening duplicating issues... no wonder our number is so big!!
