### ISSUE TITLE
Query loop variation affect the queries loop placed after it when rendering in frontend

### ISSUE THREAD

**Issue by datvimaru50** [WordPress/gutenberg#49810] opened 2023-04-13 18:27 UTC
### Description

Query loop variation does not work properly in the frontend. Any query loop placed after it are affected by it.

### Step-by-step reproduction instructions

1. Create a core/query variation that add extra query params, for example, add `include` param
2. In a template or a post, place these block: `core/query` -> `core/query variation` -> one or more `core/query`.
3. In the variation block, set some specific post ids to display, set the others as default
4. _Save_ and _preview_ in the **frontend side**
5. Look at the the core/query blocks that are placed _after_ the **variation** block, they all show the same result as the variation, but the core/query block that is placed _before_ the variation is not affected.

### 1. The result in the editor is as expected:
<img width="1280" alt="editor" src="https://user-images.githubusercontent.com/16316461/231848115-3eb60160-9d9a-4255-a54d-d179aa53d30b.png">

### 2. But the result in the frontend side is not as expected, the query after the variation is affected.
<img width="1280" alt="frontend" src="https://user-images.githubusercontent.com/16316461/231848349-bd091c3d-e2c2-40f2-bec9-4fdfa718ac77.png">

### 3. Here is the code to modify the query in the frontend side:
```
function wpmaster_modify_pre_render_block_defaults($pre_render, $parsed_block, $parent_block) { 
    if( 'wpmaster/master-query-loop' === $parsed_block[ 'attrs' ][ 'namespace' ] ) {
        add_filter(
            'query_loop_block_query_vars',
            function( $query ) use ( $parsed_block ) {
                if ( $parsed_block[ 'attrs' ][ 'query' ][ 'include' ] ) {
                    $query[ 'post__in' ] = $parsed_block[ 'attrs' ][ 'query' ][ 'include' ];
                    $query[ 'orderby' ] = 'post__in';
                }
                return $query;
            },
            10,
            2
        );
    }
    return $pre_render; 
}
add_filter( "pre_render_block", "wpmaster_modify_pre_render_block_defaults", 10, 3 );
```

### Environment info

- Wordpress 6.1.1
- Wordpress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by Mamaduka** [comment] 2023-04-18 15:25
@datvimaru50, can you share an example block markup used by those query blocks? You can use the Code Editor to copy it.

My current guess is that `query_loop_block_query_vars` from your example is leaking into the next blocks. After that filter is applied, it will affect any query block that has `$parsed_block[ 'attrs' ][ 'query' ][ 'include' ]` set.


## Screenshot

![CleanShot 2023-04-18 at 19 21 54](https://user-images.githubusercontent.com/240569/232825249-d3332c39-453e-4f2b-9246-1ed56e5c4783.png)

**Comment by datvimaru50** [comment] 2023-04-19 01:35
@Mamaduka This is the block markup of my block variation:

<img width="1280" alt="Screen Shot 2023-04-19 at 08 29 30" src="https://user-images.githubusercontent.com/16316461/232943727-1c59e83f-6c03-4aa4-be1b-ca1ef13062d8.png">

**Comment by Mamaduka** [comment] 2023-04-28 10:24
Hi, @datvimaru50

The problem is with the filter you're using.

Here's what is happening - when the `query_loop_block_query_vars` filter is applied after the `namespace` condition is met (second Query block), it will be applied for every Query block that comes after. That's how WP works.

Unfortunately, we cannot access the Query block attributes to check `namespace` inside the `query_loop_block_query_vars` and just use this hook.

Instead, you could try using the "one-time hook" method, which will apply the changes and then remove itself without affecting other Query blocks.

Here's updated example that worked in my tests:

```php
function wpmaster_modify_pre_render_block_defaults( $pre_render, $parsed_block, $parent_block ) {
	// Apply the filter only once. Based on https://gist.github.com/stevegrunwell/c8307af5b88310ac1c49f6fa91f62bcb.
	$filter = function( $query ) use ( $parsed_block, &$filter ) {
		if ( $parsed_block[ 'attrs' ][ 'query' ][ 'include' ] ) {
			$query[ 'post__in' ] = $parsed_block[ 'attrs' ][ 'query' ][ 'include' ];
			$query[ 'orderby' ]  = 'post__in';
		}

		remove_filter( 'query_loop_block_query_vars', $filter, 10, 2 );
		return $query;
	};

	if ( 'wpmaster/master-query-loop' === $parsed_block[ 'attrs' ][ 'namespace' ] ) {
		add_filter( 'query_loop_block_query_vars', $filter, 10, 2 );
	}

	return $pre_render;
}
add_filter( "pre_render_block", "wpmaster_modify_pre_render_block_defaults", 10, 3 );
```

**Comment by datvimaru50** [comment] 2023-05-01 23:51
Hi, @Mamaduka 

I tested this method and this works. This is exactly what I want.

**Comment by Mamaduka** [comment] 2023-05-02 05:13
Happy to hear that. I'm going to close the issue.

**Closed as completed by Mamaduka** 2023-05-02 05:13 UTC
Labels: Needs Technical Feedback, [Block] Query Loop
