### ISSUE TITLE
Going back from Design > Pages > {template} brings to unexpected navigation screen 

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#52127] opened 2023-06-29 14:26 UTC
### Description

In the Site Editor:
- Go to Design > Pages
- The navigation shows a list of pages. In the navigation footer, some special pages that use templates mey be listed e.g. 'Page 404' and 'Search results'.
- Click on any page, e.g. 'Sample page'.
- Click the Back button.
- You're back to the Pages navigation screen. So far so good.
- Click on 'Page 404'.
- Click the Back button.
- You're brought to the templates list at Design > Templates.
- As a used, I'd expect to be brought back to where I was before: Design > Pages.

To my understanding, the special 'pages' such as 404 and Search results are actually templates so when you go back from the, you're brought to their 'parent' object, which is the Templates screen.

However, from an user experience perspective, this is extremely confusing and just feels broken.

There may be more places where going back from a screen brings to an unexpected place.

### Step-by-step reproduction instructions

See above.

### Screenshots, screen recording, code snippet

<img width="2000" alt="Screenshot 2023-06-29 at 16 14 30" src="https://github.com/WordPress/gutenberg/assets/1682452/05330051-3b0e-4a22-89c8-a24e9e09468f">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-07-01 13:41
This issue seems to have been discussed in #50676.

**Comment by noisysocks** [comment] 2023-07-06 07:08
Closing as dupe of https://github.com/WordPress/gutenberg/issues/50676.

**Closed as completed by noisysocks** 2023-07-06 07:08 UTC
Labels: [Type] Bug, [Package] Edit Site
