### ISSUE TITLE
Consider implementing existing keyboard behaviours

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2179] opened 2017-08-03 11:51 UTC
I had a little look and couldn't see this one, please close / redirect if there are relevant tickets for this though. I think having one ticket that collects potential existing behaviours we may want to support is a good idea also.

One thing we have to do is remember because the editor has been around so long there are existing behaviours people use with regards to key combinations. Now some, we won't want to support, some though are really worth considering.

Here are two examples I think are really common that @helen says in her Twitter investigation of Gutenberg:

> I have a habit of select-all+copy before I leave something, which doesn't work here because it selects within the block only :(

> I've decided against making this a list though, and now I can't just backspace to remove it. Have to click delete for the block.

**Comment by helen** [comment] 2017-08-03 12:26
FWIW I don't think select-all is necessarily "broken" in its decision to select all within the block and not the document (see #3), in fact many use cases for select-all are to compensate for things that we accept as broken (web form data loss, lack of good cross-posting across the web, etc.).

What I do think is important is being to navigate across blocks easily because it's still a single linear document, so being able to delete a block by emptying it and backspacing, moving up and down and not just side-to-side, and other things I'm sure we can find with a little dedicated digging.

**Comment by karmatosed** [comment] 2017-08-03 13:53
Another one worth considering ( just going through your Tweet thread @helen :) ) - would be:

>  I miss cmd-s triggering an autosave in the old editor, now it brings me a browser save dialog. Preview not autosaving sucks.

**Comment by karmatosed** [comment] 2017-09-08 20:48
Another bit of feedback from a user:

> To start with , there’s a real problem for me with what the backspace key does in Gutenberg compared with how practically every text writer/Word processor interface I’v
ever used in over 25 years of computer use.
Backspace in Gutenberg deletes an entire section/paragraph!
I cant change the way I intuitively type for this single program (ie expecting backspace to only delete the character after the cursor) as in virtually every other type interface I know and I suspect many other users specially those otherwise used to old WP Tiny MCE etc or even newcomers coming to WP from other Word processing programs will be thrown by this .

**Comment by aduth** [comment] 2017-10-03 00:14
Is this a duplicate of #71?

**Comment by mtias** [comment] 2017-11-20 11:59
Closing as duplicate.

**Closed by mtias** 2017-11-20 11:59 UTC
Labels: [Type] Enhancement
