### ISSUE TITLE
I can't input list blocks on my iPhone (when inputting Japanese)

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#18708] opened 2019-11-23 15:26 UTC
**Describe the bug**
As the title says,I can't input list blocks on my iPhone when inputting Japanese.

**To reproduce**
- Add a list block on your smartphone
- Enter the first list in Japanese
- The character you entered will disappear.
- After a line break, move to the next paragraph block
- When Delete is pressed at the beginning of a paragraph block, the second item in the list is generated for some reason.
- Therefore, if you enter Japanese characters in two items in the list, the list item will become one.
- If there is already a first item, a new line will be generated if you start a new line, but if you enter Japanese there, it will be combined with the first item again.

**Screenshots**
![output](https://user-images.githubusercontent.com/31400297/69481048-ef1c4000-0e50-11ea-8030-9f435e632e8c.gif)

**My Smartphone:**
I'm using iPhone11.
 - OS: iOS 13.2
 - Browser : chrome

**Comment by jorgefilipecosta** [comment] 2020-02-08 00:16
Hi @ellatrix, does this issue rings any bell?

**Comment by ellatrix** [comment] 2020-02-10 12:17
Thanks for the report! @jorgefilipecosta I haven't seen it before, and it's been a while since I touched to list block.
@torounit Have you seen this bug before, or maybe know someone that has?

**Comment by torounit** [comment] 2020-02-18 17:06
@ellatrix 
It doesn't seem to happen on Chrome on Android.
Not tested on iPhone yet. ( I'm not an iPhone user.  😢 )

**Comment by naogify** [comment] 2020-02-19 00:32
I can't reproduce the bug. My environment is below.

- WordPress 5.3.2
-  iPhone7 (iOS13.3.1)
- Chrome and Safari

**Comment by ddryo** [comment] 2020-02-20 13:40
I'm sorry, it seems to be a bug that only happens with my theme.
Twenty Twenty could not reproduce.
Investigate which code is the cause.

**Comment by jorgefilipecosta** [comment] 2020-03-01 18:36
Thank you @ddryo, I'm closing the issue for now, if you have any further insights feel free to leave a comment.

**Comment by ddryo** [comment] 2020-03-18 01:55
Finally, we were able to determine the cause of this bug.

If the "position: relative" style hits the li tag of the list block, the above bug seems to occur.

**Comment by ddryo** [comment] 2020-03-18 05:41
@jorgefilipecosta

I created a child theme for Twenty Twenty to apply "position: relative" to the li tag of "list block" so that the bug can be reproduced.

[twentytwenty_child.zip](https://github.com/WordPress/gutenberg/files/4347160/twentytwenty_child.zip)


With this child theme used, if you enter Japanese into the list tag from the iPhone, the following behavior will occur.

![list_bug](https://user-images.githubusercontent.com/31400297/76928910-31005300-6926-11ea-9958-f858be0de00f.gif)

This bug is very critical in Japan because "position: relative" is commonly used, such as when adding a block style and using a list with icons.

**Comment by jorgefilipecosta** [comment] 2020-03-20 19:06
Thank you for the additional insights, I

**Comment by ddryo** [comment] 2020-03-21 07:14
Thanks!

**Comment by ddryo** [comment] 2020-06-02 14:32
This bug is very serious.

**Comment by ddryo** [comment] 2020-06-02 14:50
@jorgefilipecosta

I created a plugin to apply "position: relative" to the li tag of "list block" so that the bug can be reproduced.

[reproduce_18708.zip](https://github.com/WordPress/gutenberg/files/4717868/reproduce_18708.zip)

The name of the plugin is "Reproduce #18708".

With this plugin used, if you enter Japanese into the list tag from the iPhone, the following behavior will occur.

![list_bug](https://user-images.githubusercontent.com/31400297/76928910-31005300-6926-11ea-9958-f858be0de00f.gif)

This bug is very critical in Japan.

Because `position: relative` is commonly used, such as when adding a block style and using a list with icons.

**Comment by jorgefilipecosta** [comment] 2020-06-17 20:13
cc: @ellatrix, @mcsf in case you can help.

**Comment by ndiego** [comment] 2022-08-02 17:50
This issue came up today in our weekly Editor Bug Scrub. I retested the issue with the example plugin provided and am not able to reproduce the issue using the latest version of Gutenberg. Something must have been updated in the List block.  

I tested on an iPhone as well as with Japanese on desktop, all are working correctly. Therefore, I am going to close this issue, but if anyone is reliably able to reproduce can can isolate this issue to Gutenberg, please feel free to reopen.

**Closed by ndiego** 2022-08-02 17:50 UTC
Labels: [Type] Bug, [Feature] Writing Flow, Needs Testing, [Block] List

**Comment by ddryo** [comment] 2022-10-05 15:06
Just checked with 6.0.2 and it's cured!
