### ISSUE TITLE
Link control: No way to see which word will become a link.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#23112] opened 2020-06-12 09:42 UTC
**Describe the bug... well not really a bug.... perhaps just a missing enhancement.**

Opening up the link control to add a link the word or sentence marked to become a link becomes non selected/non marked. Like so...

![Screen Shot 2020-06-12 at 11 32 55](https://user-images.githubusercontent.com/5323259/84488617-c3539100-aca0-11ea-9b23-1e9a433144e7.png)

From the above I have no idea to know which word will receive a link.

-- 

Example solution is to mark the selected future link. Black underline, blue outline etc.
![Here-marked-by-blue-outline](https://user-images.githubusercontent.com/5323259/84489225-a5d2f700-aca1-11ea-8e49-6c1cde3ee80c.jpg)

Yes. I do! I can see which word will become a link! Yay that makes me happy!

---

**To reproduce**
1. Write some words.
2. Select one of the words to become a link.
3. Open the link control.
4. Notice that one can not see which word will become a link.

**Expected behavior**
I expect to be able to see which word I selected to become a link when the link control is active.

Chrome
WP 5.4.2
Local test site using Twenty Twenty
Gutenberg plugin 8.3.0

**Comment by getdave** [comment] 2020-06-15 08:00
@paaljoachim I believe that originally the popover UI used to have an arrow which pointed toward the element that triggered it. 

See screencapture in https://github.com/WordPress/gutenberg/pull/17846#issue-325799134 for example of this.

Perhaps this got removed in G2 or perhaps it was never implemented for the RichText version of the Link Control?

**Comment by paaljoachim** [comment] 2020-06-16 21:52
I asked Joen. He told me that @ellatrix can fix this by using iframe.

He mentioned that the text becomes cleared when the focus is on the popover. As one is not able to have a selection in the input field in one place while the focus is in the input field in another place. It is possible with an iframe.

**Comment by paaljoachim** [comment] 2020-07-19 16:14
Here is a new very interesting Link control feature being designed by @shaunandrews 
https://github.com/WordPress/gutenberg/issues/23375

**Comment by ellatrix** [comment] 2021-01-26 11:03
Duplicate of #6156.

**Closed by ellatrix** 2021-01-26 11:03 UTC
Labels: [Feature] Link Editing, [Type] Enhancement
