### ISSUE TITLE
Links get removed when adding multiple links

### ISSUE THREAD

**Issue by jadekins** [WordPress/gutenberg#9943] opened 2018-09-17 01:16 UTC
**Describe the bug**
On a page of my website, I am adding multiple links to websites where customers can get photographic prints. When I add a link, it’s live and clickable, then when I attempt to ad a second link below, the first link disappears and it becomes standard text again.

**Expected behavior**
I expect to be able to create multiple links to different websites.

**Desktop (please complete the following information):**
iPad Pro 9.7inch using safari and iOS 11.4.1

**Comment by arunsathiya** [comment] 2018-09-17 04:35
Hi @jadekins! Thanks for your report, but I am not able to reproduce what you mentioned. Check this [video](https://cloudup.com/c5_hgYX05LH). As you can notice on that video, I was able to add two links to two different words, in two different paragraphs. The first link did not become a standard text during this test.

I also tested adding two links to two words in the same block, and I was able to achieve the same just fine as well. [Video demonstrating the same](https://cloudup.com/cuGsjC5XQ_R).

Can you share a few screenshots (a video would help even better!) of the issue at your end? 

Can you also help with the Gutenberg version, browser, browser version and computer OS version?

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.8.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.13.6

**Comment by arunsathiya** [comment] 2018-09-17 04:35
Also, can you consider removing the unused parts of your bug report template, please? Or, consider filling them up! Thanks!

**Comment by talldan** [comment] 2018-09-19 11:09
This could be related to https://github.com/WordPress/gutenberg/issues/9867#issuecomment-421026589 - that it's not very clear that a user has to hit enter or the apply button.

**Comment by tellthemachines** [comment] 2020-01-23 05:26
Hi there @jadekins ! I'm closing this issue because I can no longer reproduce it. Feel free to reopen if needed.

**Closed by tellthemachines** 2020-01-23 05:26 UTC
Labels: Needs Testing, [Feature] UI Components, [Package] Format library
