### ISSUE TITLE
Image structure and behaviour (for responsive images) after using "convert to blocks" feature of the Classic block

### ISSUE THREAD

**Issue by bluisier** [WordPress/gutenberg#9550] opened 2018-09-02 15:19 UTC
**Describe the bug**
I use the Image Size "Custom Size" in a theme to implement responsive images and and insert the correct sizes attribute according to the image width using the `wp_calculate_image_sizes` filter like this (I'm not saying it is the best way but it is how I did it)
```
add_filter('wp_calculate_image_sizes',  __NAMESPACE__.'\content_image_sizes_attr', 10 , 4);
function content_image_sizes_attr($sizes, $size, $image_src, $image_meta) {
    $width = $size[0];
	if ($width == 795) {
		return '(min-width: 861px) 795px, 100vw';
	}
	if ($width == 363) {
		return '(min-width: 861px) 363px, (min-width: 481px) 50vw, 100vw';
	}
	return $sizes;
}
```
After installing Gutenberg, I wanted to convert my classic block into blocks and after doing it I realized that all my Custom Sizes had disappeared and that my sizes attributes where not correctly set anymore (because the image width is not the custom width I defined anymore...which was for ex 363px).
I had this

`<img class="alignright" src="..." width="363" sizes="(min-width: 861px) 363px, (min-width: 481px) 50vw, 100vw" srcset="..."...>`

and after the converting to blocks I had this

`<figure class="alignright" ><img src="..." sizes="sizes="(max-width: 768px) 100vw, 768px" (default sizes attribute) srcset="..."...></figure>`

So I tried to specify the width in the Image Dimensions of the gutenberg editor. But even after I did this, my custom width was not passed in the size parameter of the  `wp_calculate_image_sizes` filter. It just added a width attribute to the image tag...

`<figure class="alignright" ><img src="..." sizes="sizes="(max-width: 768px) 100vw, 768px" (default sizes attribute) srcset="..." width="363"></figure>`

I also realized that all my single `<img class="alignright" ...>` where converted to more complex structure with `<figure class="alignright"><img></figure>` even If I did not defined  any caption creating some styling issues in my theme.

**To Reproduce**
1. Add an image in the classic block
2. Click the Edit image button
3. In Size choose Custom Size and choose a custom width... for ex 363px
4. Click on Update
5. Use the "convert to blocks" feature of the Classic block

**Expected behavior**
I was expecting two things 
1. That my defined custom width would be kept in the image block after the conversion and that I could still use it in the `wp_calculate_image_sizes` filter to set custom sizes attribute in my images. This filter only provide the size parameter (which is [width, height] and the only useful parameter of this filter) for us to customize the sizes attribute and I'm not sure how I can correctly implement responsive images if I don't have this.
2. That I would only have a simple `<img>` tag if there is no caption defined in the image block (as it could cause styling issues in some cases).

Maybe I'm also just missing something and someone can explain me how to correctly implement responsive images for the gutenberg editor (and also why the figure tag is needed in all cases).

**Desktop**
 - OS [Ubuntu 18.04]
 - Browser [Firefox]
 - Version [61.0.1]

**Additional context**
- Gutenberg 3.7.0

**Comment by designsimply** [comment] 2018-09-06 17:30
@bluisier I think support for custom sizes hasn't been added yet and this issue is a duplicate of #1450, can you confirm? I will close this for now but will re-open if there's not a way to consolidate this issue into #1450. 🙂

**Closed by designsimply** 2018-09-06 17:30 UTC
Labels: Media, [Status] Duplicate, [Type] Enhancement

**Comment by bluisier** [comment] 2018-09-06 18:10
@designsimply after taking a look at #1450 which is more about the gallery block, I found out #6177 and I think this issue would rather consolidate #6177 . It seems there is still a lot of things going on with responsive images and the `srcset` and `sizes` attributes there.
About all my `<img>` tags beeing converted to more complex structure with `<figure><img></figure>` (after block conversion), maybe I should open another issue as it is not related to responsive images.
