### ISSUE TITLE
Button Block Bug? - Styles disappear in block editor on save.

### ISSUE THREAD

**Issue by ThomasG1** [WordPress/gutenberg#19248] opened 2019-12-19 18:01 UTC
Please see this image - self explanatory. 
Tested themes and plugins - narrowed to WP update newer than v5.25.
![NLuCMv3](https://user-images.githubusercontent.com/677833/73723621-6aa94000-4764-11ea-97ff-da94e1753495.png)

Apologies if this is not the place to record this.

**Comment by ThomasG1** [comment] 2019-12-23 14:48
Thank MKAZ for responding to this. Glad (?) to see that it is a bug and that others have recognized it.

**Comment by ThomasG1** [comment] 2020-01-02 22:45
Any updates on this issue? I can't really edit any of my live pages, because saving breaks the button styling.

**Comment by talldan** [comment] 2020-02-04 07:44
Hi @ThomasG1, it looks like the squared style has now been replaced with an option that allows you to change Border Radius. That change was made here: https://github.com/WordPress/gutenberg/pull/17253.

That shouldn't have broken your existing blocks, though, the PR specifically mentions that backwards compatibility was tested.

It could be that the issue @mkaz mentions on https://github.com/WordPress/gutenberg/issues/19287 was the cause of the styles being removed on your block. When I tested it looks like that has been fixed with the latest version of the Gutenberg plugin. That should be released in WordPress 5.4, or you can install the plugin.

PS. just a note you can add images to github by dragging/dropping them into the text field. I edited the description to add the imgur image.

**Comment by annezazu** [comment] 2020-08-25 21:21
@ThomasG1 just wanted to check in to see if this was still an active issue for consideration! Thanks in advance.

**Comment by getsource** [comment] 2021-02-02 05:35
This issue was brought up for discussion in a [triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1612243594460500). 

Since @talldan [noted about a year ago](https://github.com/WordPress/gutenberg/issues/19248#issuecomment-581782396) that there has been a likely fix merged, and there isn't any additional information about the bug still happening, I'm going to go ahead and close this issue.

Please feel free to comment/reopen this issue if you are still seeing this happen, and we can continue discussing.
Thanks much!

**Closed by getsource** 2021-02-02 05:35 UTC
Labels: Backwards Compatibility, Needs Testing, [Block] Buttons
