### ISSUE TITLE
Navigation block mobile menu closes unexpectedy when using Chrome devtools

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/gutenberg#63067] opened 2024-07-02 19:51 UTC
### Description

The mobile menu of the Navigation block closes unexpectedly when using the Chrome devtools.

The issue does **not** appear in Safari. 

This might be related to the Interactivity API, but needs further investigation.

### Step-by-step reproduction instructions

1. Create a new site using a Twenty-Twenty-Four theme.
2. Open a home page, which contains a Navigation block.
3. Open Chrome devtools.
4. Resize the browser to a "mobile" resolution so that the hamburger menu appears in the Navigation block.
5. Open the navigation menu (click on the hamburger).
6. Click anywhere within the Chrome devtools, e.g. attempt to select an HTML node.
7. **Observe that the menu closes unexpectedly**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5417266/eda1d63d-d432-42fe-b8ac-9f6cc73517fd

### Environment info

- WordPress version: 6.5.3
- GB version: trunk
- Theme: 2024 or 2023

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2024-07-03 07:18
Hi @michalczaplinski thank you for reporting this problem. I am closing this issue as a duplicate of https://github.com/WordPress/gutenberg/issues/57603

**Closed as not planned by carolinan** 2024-07-03 07:18 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Navigation, [Feature] Interactivity API

**Comment by michalczaplinski** [comment] 2024-07-03 16:14
Apologies and thanks for catching it @carolinan ! I seem to have only searched for issues with the `[Feature] Interactivity API` label and missed it!
