### ISSUE TITLE
10.5 breaks templating logic and use index.php instead of dedicated template.

### ISSUE THREAD

**Issue by chdenat** [WordPress/gutenberg#31399] opened 2021-05-01 17:12 UTC
## Description
Using 10.5.3 on some site breaks page rendering. 
My home page is binded to a specific page template but with Gutenberg 10.5 WordPres uses  index.php template instead.
I'm using understrap child theme. The index.php was really simple, just to display title/excerpt, but of course I never use it. 
Installing Gutenberg breaks the look by using index.php. 
## Step-by-step reproduction instructions

add a customised template  to a page : WordPress render it using index.php template but not the required template.
change it to default template : WordPress uses page.php template

## Expected behaviour

DIsplay as defined and rendered  without gutenberg plugin.
![expected](https://user-images.githubusercontent.com/9724885/116789557-b2299380-aaaf-11eb-85ea-c38731a6f434.png)

## Actual behaviour

Wrong look due to wrong template
![actual](https://user-images.githubusercontent.com/9724885/116789565-b9e93800-aaaf-11eb-8929-c56a34968f48.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version:  10.5.3
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? no,  child of understrap

## Device information
- Device:  Desktop
- Operating system:  W10
- Browser:  Edge

**Comment by carolinan** [comment] 2021-05-03 09:13
Hi
<del>I am not able to reproduce this with the Twenty Twenty theme which has two page templates.
When I assign a template to a page and set that page as the Homepage in the reading settings, it uses the correct templates.</del>
Update 4/5, This may be incorrect, I will do more testing.

What is the name of the template and what is the file slug? 
Is it using the parent themes index.php, or did you add an index.php file to https://github.com/understrap/understrap-child ?

**Comment by chdenat** [comment] 2021-05-03 09:54
Hi

It used the parent index.php because I did not have any in my child theme (normal behaviour).
Then, as a 1st workaround I put my own index.php  (in child theme) to have a rendering similar to my theme and WordPress used it. 
But if I use default template, WP uses page.php ...

I did it in DEBUG_MODE on , in order to check any error, but I saw nothing.

PS :  I'm not alone ... 
https://wordpress.org/support/topic/10-5-2-causes-some-sites-to-break/

**Comment by carolinan** [comment] 2021-05-03 15:25
What is the name of the template and what is the file slug?

**Comment by carolinan** [comment] 2021-05-03 15:42
I am able to reproduce it with Argent, a theme that was mentioned in the support topic. https://wordpress.org/themes/argent/
In Argent, the custom template I tested is called front-page.php. But this is a reserved name in the template hierarchy, maybe that is why. It needs further testing.

**Comment by WraithKenny** [comment] 2021-05-04 13:47
I am having the same issue. If it helps, my template is in a folder in the theme.

**Comment by dreamwhisper** [comment] 2021-05-04 13:56
We are also seeing pages use `index.php` with our Genesis themes with template names like `templates/full-width.php`, `templates/landing.php` & `templates/blocks.php`.

**Comment by MaggieCabrera** [comment] 2021-05-04 16:43
Does this still happen for you after this was merged? https://github.com/WordPress/gutenberg/pull/31336

**Comment by WraithKenny** [comment] 2021-05-04 16:45
I've found something that's part of the problem: https://github.com/WordPress/gutenberg/blame/trunk/lib/init.php#L181

This code seems to be for testing; for forcing theme support. Testing should have been done via actually using a theme, and registering theme support, but whatever. It's obvious this bit should be removed at least.

**Comment by ockham** [comment] 2021-05-04 16:53
> I've found something that's part of the problem: https://github.com/WordPress/gutenberg/blame/trunk/lib/init.php#L181
> 
> This code seems to be for testing; for forcing theme support. Testing should have been done via actually using a theme, and registering theme support, but whatever. It's obvious this bit should be removed at least.

I think this was a deliberate addition; there's some discussion about it [here](https://github.com/WordPress/gutenberg/pull/30438#discussion_r625892418), plus some more background provided [here](https://github.com/WordPress/gutenberg/pull/30465#discussion_r606174487).

**Comment by ockham** [comment] 2021-05-04 17:15
> I am able to reproduce it with Argent, a theme that was mentioned in the support topic. https://wordpress.org/themes/argent/
> In Argent, the custom template I tested is called front-page.php. But this is a reserved name in the template hierarchy, maybe that is why. It needs further testing.

~I've been able to repro the issue using these instructions with GB 10.5.3. I'll now try to see if #31123+#31336 fixes it.~

~Edit: Spoke too soon -- I was looking at the wrong page, i.e. I didn't haven't repro'd with Argent yet.~

Edit 2: I've been able to repro with Argent now. Some notes (in case others are also struggling to repro):

- This is about _pages_, not posts 😬 
- Open any page (e.g. WP's "Sample Page") in the editor, and set the its page template to "Front Page".

Without GB:

![image](https://user-images.githubusercontent.com/96308/117047693-76dacf00-ad12-11eb-8973-c779cc9ae543.png)

With GB 10.5.3 active:

![image](https://user-images.githubusercontent.com/96308/117047966-bf928800-ad12-11eb-9e5e-2e33ee380fb1.png)

**Comment by WraithKenny** [comment] 2021-05-04 17:28
I can replicate the issue simply by nesting a template file in a folder (templates/full-width.php), in a blank from scratch theme, or a default 2021 theme, etc.; It doesn't need to be a reserved word.

Please test that this case is also addressed, as putting templates in a folder named 'template's is widely considered best practice, and is even established by the Coding Standards.

**Comment by WraithKenny** [comment] 2021-05-04 18:07
I'm replicating this _**without**_ a Child Theme, and without Reserved Words, btw, tho the patches seem to be focusing on that.

**Comment by ockham** [comment] 2021-05-04 18:08
> I'm replicating this _**without**_ a Child Theme, and without Reserved Words, btw, tho the patches seem to be focusing on that.

Thanks! Yeah, I seem to be able to [confirm](https://github.com/WordPress/gutenberg/issues/31399#issuecomment-832105757).

Furthermore, it seems like the bug is still present on `trunk`...

**Comment by vdwijngaert** [comment] 2021-05-04 18:23
I'll try to replicate and see if I can get it fixed, or at least point in the right direction!

**Comment by ockham** [comment] 2021-05-04 18:42
I'm looking into a fix as we speak. I'm pretty sure the issue is in https://github.com/WordPress/gutenberg/blob/d1764758b42353fce76dbf7d355d99538d58642d/lib/full-site-editing/template-loader.php#L65

We need to get the fallback priority of templates that are returned right (which is a bit finicky -- we really need some unit test coverage 😅 ).

**Comment by WraithKenny** [comment] 2021-05-04 19:15
Specifically,

When we have 

```php
$template = '/var/www/html/wp-content/themes/test/templates/full-width.php'; 
$type = 'page';
$templates = [
    'templates/full-width.php',
    'page-slug.php',
    'page-1.php',
    'page.php',
];
```

https://github.com/WordPress/gutenberg/blob/d1764758b42353fce76dbf7d355d99538d58642d/lib/full-site-editing/template-loader.php#L70

Only gives us `full-width.php`, which is not `templates/full-width.php` and fails.

**Comment by vdwijngaert** [comment] 2021-05-04 19:36
> Specifically,
> 
> When we have
> 
> ```
> $template = '/var/www/html/wp-content/themes/test/templates/full-width.php'; 
> $type = 'page';
> $templates = [
>     'templates/full-width.php',
>     'page-slug.php',
>     'page-1.php',
>     'page.php',
> ];
> ```
> 
> https://github.com/WordPress/gutenberg/blob/d1764758b42353fce76dbf7d355d99538d58642d/lib/full-site-editing/template-loader.php#L70
> 
> Only gives us `full-width.php`, which is not `templates/full-width.php` and fails.

This hack seems to fix it:

```php
$current_template_slug = str_replace( [ trailingslashit( get_template_directory() ), '.php' ], [ '', '' ], $template );
```

Here: https://github.com/WordPress/gutenberg/blob/d1764758b42353fce76dbf7d355d99538d58642d/lib/full-site-editing/template-loader.php#L70

Edit: not sure whether to use `get_template_directory` or `get_stylesheet_directory`, or both to make it work for child themes as well, need to test that. I'll make a WIP PR, if that's okay.

**Comment by WraithKenny** [comment] 2021-05-04 19:52
I've been comparing the variables when a Block Template is set, versus when a custom theme file is set, versus when default is set...

It appears that $template is always blank if a theme file isn't selected, and $current_block_template_slug is always blank when a Block isn't set.

If these are correct assumptions, we can delete a lot of code and have a very clean and reliable function.


(@vdwijngaert For that, you'd have to check child/parent theme stuff too.)

**Comment by ockham** [comment] 2021-05-04 20:11
Thanks @vdwijngaert and @WraithKenny -- I think we're on the right track here.

I  agree that the template resolution algorithm has unfortunately become a bit hard to reason about. The crucial point is probably indeed the way that some functions attempt to strip e.g. `.php` suffixes and directories (but don't take template subfolders into account).

If we get those right, we can probably strip the child-theme specific code: https://github.com/WordPress/gutenberg/blob/9c242ee1c7064d159c520fb7cf6524f6cc0b58f3/lib/full-site-editing/template-loader.php#L79-L93

which I believe is basically duplicating this logic: https://github.com/WordPress/gutenberg/blob/9c242ee1c7064d159c520fb7cf6524f6cc0b58f3/lib/full-site-editing/template-loader.php#L105-L111

However, let's make sure we don't add any more obscure string parsing and the like to the algorithm 😬  -- ideally, we should have a good understanding of what we're doing (as there's always the chance that our fix for custom templates might affect other scenarios, e.g. pure block themes, or child themes, etc).

I'll follow up with a few more concrete notes in a moment...

**Comment by ockham** [comment] 2021-05-04 20:23
Let's try to state what we know:

If a custom template is assigned to a page, it's always the first entry in the `$templates` arg (as @WraithKenny mentioned [here](https://github.com/WordPress/gutenberg/issues/31399#issuecomment-832180888)):

> ```
> $template = '/var/www/html/wp-content/themes/test/templates/full-width.php'; 
> $type = 'page';
> $templates = [
>     'templates/full-width.php',
>     'page-slug.php',
>     'page-1.php',
>     'page.php',
> ];
> ```

So if we can determine that `$templates[ 0 ]` is a custom page template (and maybe additionally that the `$template` that was found indeed matches it), we might be able to exit early (via `return $template`). I believe that I've seen some functions in WP that should help determine that.

As stated above, we need to make sure if that has any implications for the other scenarios; and specifically, we need to find out the role of this check: https://github.com/WordPress/gutenberg/blob/9c242ee1c7064d159c520fb7cf6524f6cc0b58f3/lib/full-site-editing/template-loader.php#L98-L101

---

I've seen a number of scenarios described in the descriptions of PRs that modified the algorithm, e.g. #29026, #30599, #31123, or #31336. We'd need to make sure that we're not breaking any of these by reading them, and recreating them in our local testing. This is where unit test coverage would come in immensely helpful -- it could do that for us automatically, and would protect us from regressions, as we further refine the algorithm.

**Comment by WraithKenny** [comment] 2021-05-04 20:24
Yes, in trying to reason through the purpose of this code, the best I can grep about it is that the `$templates` loop is intended as a "source of truth" about the priority, allowing overrides.

The thing that's blocking me is that we already do a lot of the logic of child/parent, subdirectory templates inside of `locate_template` and related code. I think we are just duplicating too much effort.

We should instead, in the `$templates` loop, keep the existing simple `break` for a block-template match, redo the `$is_custom_template` to a `continue` if `true`, and then simply check if `$template_item` is present at the end of the `$template` string, and delete all the other stuff.

Can I get a sanity check on my assumptions, from someone more familiar with the history?

**Comment by ockham** [comment] 2021-05-04 20:35
> Yes, in trying to reason through the purpose of this code, the best I can grep about it is that the `$templates` loop is intended as a "source of truth" about the priority, allowing overrides.
> 
> The thing that's blocking me is that we already do a lot of the logic of child/parent, subdirectory templates inside of `locate_template` and related code. I think we are just duplicating too much effort.

Exactly my sentiment 👍

> We should instead, in the `$templates` loop, keep the existing simple `break` for a block-template match, redo the `$is_custom_template` to a `continue` if `true`, and then simply check if `$template_item` is present at the end of the `$template` string, and delete all the other stuff.
> 
> Can I get a sanity check on my assumptions

Sounds pretty good to me! @WraithKenny It'd be great if you could file a PR to that effect -- it's getting pretty late here, unfortunately 😅 

> from someone more familiar with the history?

I did a major refactor to this stuff about a year ago but haven't worked with it recently, so I'm not that familiar with the latest changes. Even back then, it was kinda hard to get it right -- the template hierarchy resolution algorithm is complex as it is, and we're extending it here for a whole new breed of themes. Edge cases tend to fall through the cracks easily. My biggest regret is not having added unit test coverage back then. This issue is renewed motivation to finally do that.

**Comment by WraithKenny** [comment] 2021-05-04 20:40
I've done a simple edit via the Github website UI, because I don't have a Gutenberg repo set up. (I tested via editing a local copy of the downloaded plugin.)

But at least folks can look at the code, and see if what I wrote makes any sense!

**Comment by ockham** [comment] 2021-05-04 20:45
> I've done a simple edit via the Github website UI, because I don't have a Gutenberg repo set up. (I tested via editing a local copy of the downloaded plugin.)
> 
> But at least folks can look at the code, and see if what I wrote makes any sense!

Awesome, I'll give it a spin!

**Comment by vdwijngaert** [comment] 2021-05-04 20:45
I was going for a fix for the issue that crept in 10.5. If the code responsible for the issue can be removed completely, as suggested, that's even better! 

It's getting late here, too, so I'm not able to look into the full history to make sure nothing breaks, but it might be a good idea to ask @aristath to take a look as well.

**Comment by ockham** [comment] 2021-05-04 21:40
Here's a very basic unit test:

```php
<?php
/**
 * Template_Loader_Test class
 *
 * @package WordPress
 */

/**
 * Tests for the block template loading algorithm.
 */
class Template_Loader_Test extends WP_UnitTestCase {
	private static $post;
	private static $template_part_post;

	public static function wpSetUpBeforeClass() {
		switch_theme( 'tt1-blocks' );
		gutenberg_register_template_post_type();
		gutenberg_register_template_part_post_type();
		gutenberg_register_wp_theme_taxonomy();
		gutenberg_register_wp_template_part_area_taxonomy();

		// Set up template post.
		$args       = array(
			'post_type'    => 'wp_template',
			'post_name'    => 'page',
			'post_title'   => 'Page',
			'post_content' => 'Content',
			'post_excerpt' => 'Description of my template',
			'tax_input'    => array(
				'wp_theme' => array(
					get_stylesheet(),
				),
			),
		);
		self::$post = self::factory()->post->create_and_get( $args );
		wp_set_post_terms( self::$post->ID, get_stylesheet(), 'wp_theme' );
	}

	public static function wpTearDownAfterClass() {
		wp_delete_post( self::$post->ID );
	}

	function test_gutenberg_page_template() {
		$type = 'page';
		$templates = array(
			'page-slug.php',
			'page-1.php',
			'page.php',
		);
		$resolved_template_path = gutenberg_override_query_template( $custom_page_template_path, $type, $templates );
		$this->assertEquals( plugin_dir_path( __DIR__ ) . 'lib/template-canvas.php', $resolved_template_path );
	}

	function test_gutenberg_custom_page_template() {
		$custom_page_template = 'templates/full-width.php';
		$custom_page_template_path = get_stylesheet_directory() . '/' . $custom_page_template; 
		$type = 'page';
		$templates = array(
			$custom_page_template,
			'page-slug.php',
			'page-1.php',
			'page.php',
		);
		$resolved_template_path = gutenberg_override_query_template( $custom_page_template_path, $type, $templates );
		$this->assertEquals( $custom_page_template_path, $resolved_template_path );
	}
}
```

This fails on current `trunk`, but passes both for https://github.com/WraithKenny/gutenberg/commit/8a70acd76f2c23fece9658166dc37e04ae71a05e and https://github.com/WordPress/gutenberg/pull/31478.

**Comment by ockham** [comment] 2021-05-04 21:45
Let's do the following:

- Merge @vdwijngaert's #31478 (since its surface of impact is actually smaller, which can give us more confidence that it doesn't have (m)any unwanted side effects).
- Cherry-pick to `release/10.5`, and cut a 10.5.4 release with the fix.

Once that short-term fix is out:

- File a PR based on @WraithKenny's https://github.com/WraithKenny/gutenberg/commit/8a70acd76f2c23fece9658166dc37e04ae71a05e, and including unit tests (based on https://github.com/WordPress/gutenberg/issues/31399#issuecomment-832266229, but also covering behavior described in #29026, #30599, #31123, and #31336, to make sure we don't break any other cases).

Since it's very late here now, I won't do the release tonight. I'll continue work tomorrow, unless someone from @WordPress/gutenberg-core beats me to it.

**Closed as completed** 2021-05-05 09:43 UTC
Labels: [Type] Bug, [Status] In Progress, [Type] Regression, [Feature] Themes

**Comment by vdwijngaert** [comment] 2021-05-05 10:01
> Let's do the following:
> 
> * Merge @vdwijngaert's #31478 (since its surface of impact is actually smaller, which can give us more confidence that it doesn't have (m)any unwanted side effects).
> * Cherry-pick to `release/10.5`, and cut a 10.5.4 release with the fix.
> 
> Once that short-term fix is out:
> 
> * File a PR based on @WraithKenny's [WraithKenny@8a70acd](https://github.com/WraithKenny/gutenberg/commit/8a70acd76f2c23fece9658166dc37e04ae71a05e), and including unit tests (based on [#31399 (comment)](https://github.com/WordPress/gutenberg/issues/31399#issuecomment-832266229), but also covering behavior described in #29026, #30599, #31123, and #31336, to make sure we don't break any other cases).
> 
> Since it's very late here now, I won't do the release tonight. I'll continue work tomorrow, unless someone from @WordPress/gutenberg-core beats me to it.

Thanks @ockham! Could you create these follow-up issue(s)?

**Comment by ockham** [comment] 2021-05-05 11:53
> Thanks @ockham! Could you create these follow-up issue(s)?

I've gone ahead and created a PR draft for the unit tests: #31498.

**Comment by chdenat** [comment] 2021-05-05 12:01
Thanks to all of you  !!!
