### ISSUE TITLE
Page/post preview doesn't work after converting legacy post to blocks with Gutenberg

### ISSUE THREAD

**Issue by ElectricFeet** [WordPress/gutenberg#3654] opened 2017-11-25 18:02 UTC
## Issue Overview
When editing the WP standard "Sample Page" on a brand new site with Gutenberg, the `Preview` (eye) button opens a new tab displaying the page. After converting the first paragraph to blocks, the preview page hangs.

## Steps to Reproduce (for bugs)

1. From a brand new site, with Gutenberg installed as the only active plugin, edit the page "Sample Page".
2. Click the `Preview` (eye) button. A new tab opens with the page preview. All fine so far.
3. Click the **&vellip;** (vertical ellipsis: "Open settings menu") to the right of the first paragraph and choose "Convert to blocks".  
4. Click the `Preview` (eye) button and a new tab opens with a page saying:
    > Please wait…
    > 
    > Generating preview.

The preview doesn't generate.

Happens on:
- Mac OS 10.13.1, using BOTH Firefox Quantum 57 and Mac OS Safari 11.0.1.
- Brand new WP install.
- No active plugins, apart from Gutenberg.
- On the client, there are a few pretty standard web extensions installed in Firefox (1Password, uBlock Origin, Privacy Badger etc.) and only two extensions (1Password and uBlock Origin) installed in Safari. But the page preview works fine before converting to Gutenberg blocks, so I don't think the browser extensions are implicated in any way.  
- On the server side, the only thing that's odd is that it's a test environment on an https site using a wildcard certificate, which gives browser errors the first time you access the site. But again, page preview works fine before converting to Gutenberg blocks, so I don't think the server environment is implicated in any way. 
- WordPress 4.9
- Tested the above with TwentySeventeen and Customizr Pro, with the same results.
 
## Expected Behavior

Should show the page preview.
## Current Behavior

It hangs and doesn't show the page preview.
## Screenshots / Video

<img width="840" alt="screen shot 2017-11-25 at 18 58 41" src="https://user-images.githubusercontent.com/6003638/33233222-bcbfef48-d212-11e7-8042-6cbc9323bb24.png">

## Related Issues and/or PRs

Can't see any.

## Todos
- [ ] Tests
- [ ] Documentation

Not clear what this section means in the template...

**Comment by ElectricFeet** [comment] 2017-11-25 18:41
I should add that once you update the page with the `Update` button, it previews fine. But of course, the whole point of previewing is to see what it looks like _before_ publishing the changes.

**Comment by ElectricFeet** [comment] 2017-11-25 19:25
Added "legacy post" to title, because this doesn't appear with a new Gutenberg-created post, but does happen with the standard "sample post" in a new WP installation.

**Comment by ephox-mogran** [comment] 2017-11-27 03:27
I can also replicate this. My steps to replicate were:

1. Create a new post using the classic editor
2. Add paragraph and quote to the content
3. Publish
4. Edit that post using Gutenberg
5. Convert to blocks
6. Preview

For me, it was important that the post had been published first otherwise I couldn't replicate it.

**Comment by jeffpaul** [comment] 2018-03-22 19:49
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521734964000100)._

**Comment by jorgefilipecosta** [comment] 2018-05-24 10:02
Hi @ElectricFeet thank you for reporting this issue.
I retested & did some debugging on this issue, and the cause is that the preview is not working correctly on published posts.
Given that we already have an issue with the cause https://github.com/WordPress/gutenberg/issues/4099 I will close this one, so we keep the discussion on the same issue.

**Closed by jorgefilipecosta** 2018-05-24 10:02 UTC
Labels: Needs Testing, [Type] Bug
