### ISSUE TITLE
FSE: Query block encounters an error with sample content in Site Editor

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#29051] opened 2021-02-16 23:10 UTC
## Description
A fresh WordPress install includes a Hello World sample post, and this post is part of the content returned inside a Query block in the Site Editor. The block containing this content displays the error, "This block has encountered an error and cannot be previewed."

## Step-by-step reproduction instructions
1. Install WordPress 5.6.1 with TT1 Blocks theme
2. Install Gutenberg 9.9.3
3. Visit Site Editor
4. Observe an error notice returned by the block containing content from the Hello World post.

## Expected behaviour
Content returned by the Query block should be available.

## Actual behaviour
The block displays the "this block has encountered an error and cannot be previewed" message.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/29587253/108132971-a9642b00-7118-11eb-80c3-30a04ea2b353.png)

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: 88.0.4324.150, Firefox Developer 86.0b9

**Comment by ntsekouras** [comment] 2021-02-25 11:58
Hey @chthonic-ds - thanks for reporting this!

I couldn't reproduce this. Is this still happening?

**Comment by chthonic-ds** [comment] 2021-02-25 23:56
Thanks for taking a look, @ntsekouras !

Yes, I'm still seeing this issue, though there's now a slightly different path to see the error after updating to the latest WP core, Gutenberg and TT1 Blocks theme.

- Install WordPress 5.6.2
- Install and activate TT1 Blocks 0.4.4
- Install and activate Gutenberg 10.0.2
- Visit Site Editor
- Focus the Query block
- Observe an error notice returned by the block containing content from the Hello World post.

Similar console error as well (neglected to add in the initial report, apologies):
`
TypeError: Cannot read property 'tinymce' of undefined
    at index.js?ver=dcc947abe08a21aa9d1ca40da9585bb5:58
    at Bh (react-dom.min.de439aae.js:126)
    at Dj (react-dom.min.de439aae.js:162)
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)
    at xb (react-dom.min.de439aae.js:162)
    at Te (react-dom.min.de439aae.js:146)
    at react-dom.min.de439aae.js:61
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)`

The Hello World! post is saved in a Classic Block. When I convert it to a Paragraph block, the issue is gone.

**Comment by chthonic-ds** [comment] 2021-02-26 00:23
Struck me as odd that a Classic block would be used in Hello World!, and I think I know now why I'm seeing this behaviour.

I was testing with an old version of Laragon and this was initially installing an earlier version of WordPress which was then **updated** to the latest. The initial WordPress installation is where the Classic block was coming from. Testing again with 5.6.2 installed from the outset, a regular Paragraph block is used and the error doesn't occur.

I guess this means the actual issue here is that the Classic block generates an error in the Query block. I can't see an open issue for this but will hold off creating one until someone else confirms.

**Comment by david-szabo97** [comment] 2021-03-01 13:57
This PR might be the fix: https://github.com/WordPress/gutenberg/pull/27059

**Comment by skorasaurus** [comment] 2023-03-14 20:46
Hi, I'm not able to reproduce this; believe it was fixed in https://github.com/WordPress/gutenberg/issues/48938 ; please reopen if you're still experiencing this.

**Closed by skorasaurus** 2023-03-14 20:46 UTC
Labels: [Type] Bug, [Feature] Full Site Editing, [Block] Query Loop
