### ISSUE TITLE
Add Media in Classic editor doesn't work correctly

### ISSUE THREAD

**Issue by JuliaArr** [WordPress/gutenberg#12425] opened 2018-11-29 15:05 UTC
There are two bugs in adding media in the Classic Editor block.

1). The height of the embed .mp4 video.
Steps to reproduce the error:
1. Add new Classic Editor.
2. Add Media
3. Upload .mp4 file
4. See error: https://www.screencast.com/t/KBwkdwJSTwF - its height is 150px instead of needed 640px

2) The location of the media content after adding it.
Steps to reproduce the error:
1. Add new Classic Editor.
2. Add some content (text, for example: https://www.screencast.com/t/maCMi409LzL )
3. The cursor is now after the text. Add Media (Image or Video) and it will be inserted above the content: https://www.screencast.com/t/ETdEE3Fzn instead of being displayed after it.

I'm using Twenty Nineteen default WordPress theme.
WordPress development version 5.0-RC1-43946

**Comment by youknowriad** [comment] 2018-11-29 15:08
Duplicate of #10509 Should be closed by #12415

**Closed by youknowriad** 2018-11-29 15:08 UTC
