### ISSUE TITLE
Button Design should be proper , when we add the button block and check different style preview.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#15958] opened 2019-06-03 05:30 UTC
Theme issue: Twenty Seventeen (v2.2)

Steps to Follow :

1. Active Twenty Seventeen theme.

2. Open Editor.
3. Add button Block.
4. Add button label and URL.
5. Check button Style preview with the content.

Please find the below attached video :

https://www.screencast.com/t/nEclKgbAbRDR

**Comment by sanketio** [comment] 2019-06-03 11:08
I believe it can be fixed by removing `margin-top: 2em` from here - https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyseventeen/assets/css/editor-blocks.css#L722

@swissspidy : Any other suggestions?

**Comment by swissspidy** [comment] 2019-06-03 13:52
I am not an expert on the bundled themes. Maybe @laurelfulford can chime in here.

If anything in Twenty Seventeen needs to be changed, a ticket would need to be created at https://core.trac.wordpress.org/, as it's not an issue caused by Gutenberg itself.

**Comment by laurelfulford** [comment] 2019-06-04 03:51
Yes, this looks like some weirdness in the theme's styles -- thanks for reporting this, @nayana96249!

It looks like you've already reported it in the WordPress Trac, too: https://core.trac.wordpress.org/ticket/47414 -- this issue should be good to close, and a fix can be taken care of in the theme itself.

**Closed** 2019-08-22 10:47 UTC
Labels: [Block] Button, [Component] Style Variations, [Type] Plugin Interoperability
