### ISSUE TITLE
Post should be marked dirty immediately on typing

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1740] opened 2017-07-05 15:06 UTC
Currently you have to type inside of a block, then click/tab outside of it before the post is marked as dirty (the "Saved" indicator changes to a "Save" link).

Instead, this should happen immediately (probably with a debounce) upon typing.

**Comment by aaronjorbin** [comment] 2017-07-05 18:46
Duplicate of #1240?

**Closed** 2017-07-05 18:51 UTC
Labels: Framework, [Type] Bug
