### ISSUE TITLE
Tap goes through toolbar on mobile

### ISSUE THREAD

**Issue by androidacy-user** [WordPress/gutenberg#36167] opened 2021-11-03 04:36 UTC
### Description

Touches on the toolbar at the top on mobile instead select the element below it. If the element below it is already selected, then it correctly selects the toolbar item. 

### Step-by-step reproduction instructions

1. Select any element
2. Try to interact with toolbar
3. Notice that the element below the toolbar, not the toolbar, gets the tap. 

### Environment info

- WordPress 5.8.1, Gutenberg 11.8.0, bootScore
- Chrome 95, tested also since chrome 92 and Firefox 78
- Android, tested with 9 through 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mchowning** [comment] 2021-11-04 16:16
Thanks for the issue report. 🙇  

It sounds like this is occurring on mobile web, not the mobile apps, is that right?

**Comment by androidacy-user** [comment] 2021-11-04 16:19
Mobile web yes.

**Comment by torounit** [comment] 2022-08-09 14:50
I tested it on android 12 chrome 104 and could not reproduce it. (WP 6.0.1)

**Comment by ndiego** [comment] 2022-08-16 16:01
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone is able to replicate it in the future, please feel free to reopen with additional information.

**Closed as completed by ndiego** 2022-08-16 16:01 UTC
Labels: [Type] Bug, Mobile Web, Needs Testing, [Feature] List View
