### ISSUE TITLE
Unable to redo text entry for Quote/Pull Quote block

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#30976] opened 2021-04-19 19:25 UTC
## Description
If a Quote/Pull Quote block is added with text, ~but not a citation~, it is not possible to undo and then redo the block addition and text entry. The act of entering text into the Quote/Pull Quote block is not redo-able. ~If the Quote/Pull Quote block in question _does have a citation_, the redo functionality works as expected.~ 

## Step-by-step reproduction instructions
1. Launch the block editor. 
2. Add a Quote/Pull Quote block.
3. Enter quote text. ~_Do not enter a citation._~
4. Press the Undo button in the toolbar repeatedly until the Quote/Pull Quote block is removed.
5. Press the Redo button in the tool bar repeatedly until all redo actions have been replayed. 

## Expected behaviour
The Quote/Pull Quote block is added back with the text entered.

## Actual behaviour
The Quote/Pull Quote block is added back _without_ the text entered.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/115291294-311ae580-a11a-11eb-94a2-8fb3c94dd2bb.MP4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone SE
- Operating system: iPhone 14.4.2
- WordPress app version: 17.1 (17.1.0.3)

**Comment by dcalhoun** [comment] 2021-05-21 18:22
Updated the title and description, as this issue appears to occur regardless of the presence of a citation. I am unsure if it was merely overlooked originally or the problem has worsened. 

https://user-images.githubusercontent.com/438664/119181668-89a21300-ba37-11eb-868f-0b67d9da194c.MP4

**Comment by dcalhoun** [comment] 2021-08-12 13:24
Following up to share that I have noticed that redoing _insertion_ of a Quote block loses subsequent redo history. Similar to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2499.

**Comment by geriux** [comment] 2023-06-12 14:23
Hey there @dcalhoun 👋 ! I've just tried to reproduce this issue on the latest versions of the mobile editor and I'm unable to reproduce it. Since almost two years have passed I guess it was fixed during that time. I'll close this for now but feel free to re-open if it happens again thanks!

**Closed as completed by geriux** 2023-06-12 14:23 UTC
Labels: [Type] Bug, [Priority] Low, Mobile App - i.e. Android or iOS, [Package] Block library, [Block] Quote, [Feature] History
