### ISSUE TITLE
Quote toolbar is not shown for mobile view

### ISSUE THREAD

**Issue by oksanayoast** [WordPress/gutenberg#55709] opened 2023-10-30 20:38 UTC
### Description

The quote toolbar should be shown on mobile while it's not shown on smaller viewport sizes.

Initially I've created this bug here: https://core.trac.wordpress.org/ticket/59537

### Step-by-step reproduction instructions

1. Create a post
1. Add a quote
1. Check that the capture toolbar in the quote block is shown
1. Change screen size (ex. 768X1024)
1. Quote toolbar is not shown

### Screenshots, screen recording, code snippet

<details>
<summary>Expected result:</summary>

<img width="606" alt="expected result 2" src="https://github.com/WordPress/gutenberg/assets/88657898/f9131af0-e3f9-416c-8ef1-cd16421fab80">
<img width="606" alt="expected result" src="https://github.com/WordPress/gutenberg/assets/88657898/9b3db3be-c19d-44c1-bbe1-cbf669ca7a32">

</details>

<details>
<summary>Actual result:</summary>

<img width="576" alt="Actual result" src="https://github.com/WordPress/gutenberg/assets/88657898/ad6b227a-00ca-4f55-a04e-01bb9c051532">

</details>

### Environment info

WP 6.3, WP 6.4 beta, Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment] 2023-10-31 01:08
Confirmed this bug in testing 👍

**Comment by jorgefilipecosta** [comment] 2023-10-31 10:54
Hi @oksanayoast, @jordesign. I'm not able to reproduce the issue. The quote toolbar is in fact not visible because the paragraph inside it is selected, but I have the option to select the quote and in that case, the quote toolbar becomes visible.
<img width="417" alt="Screenshot 2023-10-31 at 10 52 59" src="https://github.com/WordPress/gutenberg/assets/11271197/583c55a7-57bb-40ad-a131-b1f401e3123c">


Could you share screenshots of what you are seeing?

**Comment by t-hamano** [comment] 2023-10-31 12:48
From the screenshot attached to [the core ticket](https://core.trac.wordpress.org/ticket/59537), it appears that in mobile layouts, @oksanayoast expects the parent selector button to appear in the toolbar.

<img width="576" alt="Actual result" src="https://github.com/WordPress/gutenberg/assets/54422211/2d897e4d-c780-4444-81e4-f875f91cecd3">

However, as mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/55709#issuecomment-1786976529), I think it is by design that the parent selector button is not displayed when the block inside is selected.

**Comment by t-hamano** [comment] 2023-11-16 12:41
Hi @oksanayoast,

I would like to close this issue as I believe the current behavior is expected. If I have misunderstood anything, please feel free to comment.

**Closed as not planned by t-hamano** 2023-11-16 12:41 UTC
Labels: [Status] In Progress, [Block] Quote
