### ISSUE TITLE
Consolidate consecutive drop zones

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#9821] opened 2018-09-12 11:53 UTC
There are two consecutive drop zones between blocks, we should consolidate them into one drop zone between blocks. We may also want to avoid suggesting adjacent drop zones to the block being dragged:

![45422690-40e40a80-b691-11e8-8cc8-7bda4e3859cd](https://user-images.githubusercontent.com/583546/45423313-404c7380-b693-11e8-9f10-59d4f37a4197.gif)

**Comment by talldan** [comment] 2018-09-21 13:03
Closing as a duplicate of #8540.

**Closed by talldan** 2018-09-21 13:03 UTC
Labels: Drag and Drop, [Type] Enhancement
