### ISSUE TITLE
CTRL + A does not select anything if editor only has (or had) only one Classic block

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#12341] opened 2018-11-27 00:23 UTC
**Describe the bug**
Hitting `CTRL` + `A` makes no selection if there is only one block. This is particularly an issue using the "hybrid" workflow of Gutenberg + a single Classic block.

**To Reproduce**
1. Insert a classic block or paragraph block
1. Put at least a few characters in it.
1. Press `CTRL` + `A`
1. Nothing happens

**Expected behavior**
The entire paragraph/classic/other block is selected.

**Desktop (please complete the following information):**
Win 10, Firefox 63.0.3, WordPress 5.0-RC1-43944, no plugins, Twenty Nineteen

**Comment by designsimply** [comment] 2018-11-27 02:18
I tested with WordPress 5.0-RC1-43944 and Firefox 63.0.3 on macOS 10.13.6 and found that pressing `Cmd + A` from within a single classic block with a few words in it resulted in the contents of the block being selected as expected and if I unselect the block by clicking on the white space in the page then I needed to press `Cmd + A` twice to select the content.

![12341](https://user-images.githubusercontent.com/1119271/49053891-50162700-f1af-11e8-869f-0266efb8bb3c.gif)
<sup>Seen at https://madefortesting.com/wp-admin/post.php?post=722&action=edit running WordPress 5.0-RC1-43944 tested with Firefox 63.0.3 on macOS 10.13.6.</sup>

I also tested using WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6 and found the same result with the plugin. 

Testing note: leaving the `Needs Testing` label and noting it would be good to have another tester confirm whether or not this happens for them on Windows (since the original report was for Windows and my first pass of testing was with macOS).

**Comment by mrwweb** [comment] 2018-11-27 03:44
Thanks for testing this, @designsimply. I did some further testing and now realize this bug is more specific than I thought, though you'll see why I ended up thinking it was broader.

This seems to only happen when the Classic block is the first and only block. (Even an empty second block will make `CTRL` + `A` "work".) HOWEVER, once the classic block _has been_ the first and only block (i.e. it was there and then deleted), _then_ the bug will also happen if a paragraph block is now the first and only block.

I've updated the title accordingly.

(What do you use for GIFs that shows the keystrokes?)

**Comment by designsimply** [comment] 2018-11-27 18:16
> What do you use for GIFs that shows the keystrokes?

ScreenFlow and I ❤️ it!

**Comment by designsimply** [comment] 2018-11-27 18:20
> This seems to only happen when the Classic block is the first and only block. (Even an empty second block will make CTRL + A "work".)

By empty block do you mean the default block—as in the one with the (+) inserter to the left? I tried but I couldn't figure out how to get a post into a state where there was a classic block and no default block. I think it's possible this could happen if you have a plugin installed that changes the default block to something other than paragraph but I am not sure. In any case!, how do I get a post into a state where there's a classic block and no empty/default block? I tried creating a post with the Gutenberg plugin deactivated then re-activating Gutenberg, but the default/empty block is always there in my testing. Note: I'm using Firefox 63.0.3 on macOS 10.13.6 so maybe I should try with Windows (but I can't imagine that would make a difference for this case!)?

**Comment by mrwweb** [comment] 2018-11-27 18:36
There would seem to be at least three ways:

1. Insert the block with the "/" inserter
1. Insert the block, delete the empty block below it
1. Make a template with only that block (I hadn't thought about that until you suggested it, but it's a good idea!)

Ways 1 and 2:

![only-classic](https://user-images.githubusercontent.com/1238696/49103433-3537c700-f230-11e8-956b-22daee81c79d.gif)

> ScreenFlow and I ❤️ it!

Mac only 😢

**Comment by designsimply** [comment] 2018-11-27 19:11
I tested with Firefox 63 on Windows 10 and found that `Ctrl+A` works for me on a first pass but does not work subsequently.

![12341](https://user-images.githubusercontent.com/1119271/49105143-21469200-f23d-11e8-8463-5abfd1da8a52.gif)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=127&action=edit tested with Firefox 63 on Wondows 10.</sup>

Related: #8180

Aside: okay, after seeing the your explanation, I think we're just thinking of the default/empty block slightly differently ([screenshot](https://user-images.githubusercontent.com/1119271/49105270-65d22d80-f23d-11e8-91d3-f78430b121cf.png)) and I think my testing was good.

> Mac only 😢

Gah! I didn't know…

**Comment by mrwweb** [comment] 2018-11-27 19:50
> I think we're just thinking of the default/empty block slightly

I think you're right. I think of the "default/empty" block as the paragraph with placeholder text to the left of what you're pointing at.

**Comment by skorasaurus** [comment] 2021-01-26 15:29
still reproducible in Gutenberg 9.8.0

**Comment by ellatrix** [comment] 2023-08-09 07:49
The Classic Block is now is a modal and much more stable than before (closer to the old editor, which was also iframed). Closing this because these are now separate editing experiences.

**Closed by ellatrix** 2023-08-09 07:49 UTC
Labels: [Type] Bug, [Priority] Low, [Feature] Writing Flow
