### ISSUE TITLE
The plus sign is in the way when writing a list

### ISSUE THREAD

**Issue by jan-vandenberg** [WordPress/gutenberg#46086] opened 2022-11-26 09:18 UTC
### Description

The plus sign is in the way when writing a list so it covers the last word of a sentence.

Tested on two different themes:

![image](https://user-images.githubusercontent.com/13764557/204081485-2f458a22-79ef-43e5-961a-9ef52dc11b78.png) ![Screenshot 2022-11-26 09 58 20](https://user-images.githubusercontent.com/13764557/204081512-e834ef55-77c9-4e9b-96d4-bf1290c34486.png)

### Step-by-step reproduction instructions

1. Start a new post
2. Select the list option
3. Type a sentence all the way to the end of the line.
4. Notice the last word is covered by the plus sign.

The plus sign indicates that you can click for a new list item (however an enter will do).

### Environment info

- WordPress 6.1.1
- Neve theme from Themeisle
- Also tested on Independent Publisher theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment] 2022-11-29 14:23
This issue was reviewed during today's Editor Bug Scrub and is confirmed. It's likely a tricky one to solve, but any ideas @javierarce @jasmussen?

**Comment by jasmussen** [comment] 2022-11-29 14:30
I believe this issue is not happening in trunk. When a list item is focused, there's no black plus:

<img width="859" alt="Screenshot 2022-11-29 at 15 29 22" src="https://user-images.githubusercontent.com/1204802/204556116-d37a6cab-b23a-4afa-8c6f-90680758dafe.png">

There still is one when you select the List block itself, and I think we should consider removing it (including the one for group) so you have to rely on the top left inserter button. But that's orthogonal. Can you reproduce this in the latest version of the plugin?

**Comment by ndiego** [comment] 2022-11-29 15:30
@jasmussen Ah yup, I must have been testing in a prior version, or perhaps just 6.1 🤦‍♂️ All looks good in 14.6. 

@jan-vandenberg Since this has been resolved in Gutenberg 14.6, I am going to close this out. But if you run into any further issues, feel free to reopen. Thanks again for reporting!

**Closed as completed by ndiego** 2022-11-29 15:30 UTC
Labels: Needs Design Feedback, [Block] List
