### ISSUE TITLE
Button active and focus state needs more distinct styling

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#127] opened 2017-02-23 16:51 UTC
Why? Accessibility. Some people don't see well. 👓

The contrast difference between active state and normal state is not big enough. Ideally it needs something like a border, inverted colours, underline...

http://webaim.org/resources/contrastchecker/

This is the style in core:

<img width="166" alt="screenshot 2017-02-21 19 02 07" src="https://cloud.githubusercontent.com/assets/4710635/23177791/6f4aa458-f868-11e6-8815-21e4656848c7.png">

**Comment by mapk** [comment] 2017-02-23 18:04
Current view of hover state:
![current-hover-state](https://cloud.githubusercontent.com/assets/617986/23272161/148f6eac-f9af-11e6-9a81-b0b9ac74ef8f.png)

Proposed revision:
I know there was discussion about the UI being _heavy_, so I tried to keep this as light as possible. I'm basing it all from the sketch file. 

The contrast on the active states is compliant for WCAG 2 AA (18pt+). Does that work in relation to our icons there?
![hover-state](https://cloud.githubusercontent.com/assets/617986/23272183/2d43477a-f9af-11e6-9503-55ff009a9ecd.png)

**Comment by iseulde** [comment] 2017-02-23 18:56
Trying something as well:

<img width="226" alt="screenshot 2017-02-23 19 55 41" src="https://cloud.githubusercontent.com/assets/4710635/23274239/356173e8-fa02-11e6-9c4f-4d1dd3cb2574.png">

**Comment by iseulde** [comment] 2017-02-23 18:59
<img width="290" alt="screenshot 2017-02-23 19 59 19" src="https://cloud.githubusercontent.com/assets/4710635/23274319/98a89a26-fa02-11e6-8228-71449142be24.png">

**Comment by iseulde** [comment] 2017-02-23 19:05
_Maybe_ contrast between two backgrounds is allowed to we smaller though, worth checking.

**Comment by afercia** [comment] 2017-02-23 19:41
Contrast ratio can be just 3:1 instead of the usual 4.5:1 for "Large-scale" text, which is text "with at least 18 point or 14 point bold or font size". I'm not sure how to apply this to svg icons :) THey look bold to me, not sure about the font-size.

Adding a shape, even a subtle one, can surely help.

Just as a reminder: controls need also a focus style.

**Comment by iseulde** [comment] 2017-02-23 19:44
The contrast between the white background and the grey background is 1.27:1.

**Comment by afercia** [comment] 2017-02-23 20:10
Ah well that. The difference between the two states should be perceivable. That reminds me of https://core.trac.wordpress.org/ticket/28599 where our recommendation is to use an additional indicator, like a shape.

**Comment by afercia** [comment] 2017-02-23 20:13
Reference about font-size for contrast ratio:
https://www.w3.org/TR/WCAG20-TECHS/G18.html
> The ratio between sizes in points and CSS pixels is 1pt = 1.333px, therefore 14pt and 18pt are equivalent to approximately 18.5px and 24px.

Still not clear how to apply that to svg icons 😬

**Comment by mapk** [comment] 2017-02-23 20:52
I believe the svg icons are 24px, so we should be ok. But the lighter grey against the white non-active state is still an issue.

**Comment by afercia** [comment] 2017-02-23 21:37
Well, the icons rect is 24px. The glyphs inside the rect are smaller :) But as long as they're bold and they don't go under a corresponding font-size of 18.5px they should be ok.

**Comment by iseulde** [comment] 2017-02-23 21:58
The issue is not really the contrast between the icons and the background. That is 👌. The issue's the difference between the normal and active state, the white and light grey background. Which may be enough, I'm not entirely sure about that.

> The difference between the two states should be perceivable. That reminds me of https://core.trac.wordpress.org/ticket/28599 where our recommendation is to use an additional indicator, like a shape.

So it sound like an extra indicator is good, but it hard to know what contrast between backgrounds is actually enough.

**Comment by jasmussen** [comment] 2017-02-24 08:59
Good explorations so far. Keep the thoughts coming. 

Let's expand our minds, as Ella suggests, and think beyond just _color_ as something that can add contrast. Some other ideas:

![formatting click](https://cloud.githubusercontent.com/assets/1204802/23296929/8e00c268-fa77-11e6-885e-7a63df5106e6.png)

![formatting click 2](https://cloud.githubusercontent.com/assets/1204802/23296936/903920d4-fa77-11e6-9076-aa68c41f23ff.png)

![formatting click 3](https://cloud.githubusercontent.com/assets/1204802/23296939/93217cb0-fa77-11e6-80c9-91850cf8c8a2.png)

![formatting -click-4](https://cloud.githubusercontent.com/assets/1204802/23296942/96d5a098-fa77-11e6-8f4e-f0230e5e48b9.png)

Neither of 👆 feel juuust right to me, but we're making progress here. @mapk importantly noted that the blocks were mentioned as feeling _heavy_, and as soon as we lightened the block borders and used the light white floaty chrome everywhere, <a href="https://make.wordpress.org/design/2017/02/23/core-editor-meeting-notes-2017-02-22/">the critique subsided</a>. This is important to keep in mind, so we don't regress here.

We have to find a balance between the light UI and proper accessability, and we are on the cusp of it. Keep thinking folks! 🌟 work so far.

**Comment by jasmussen** [comment] 2017-02-24 09:01
Also — this is a UI that has been solved in the past. Let's look at what others have been doing, like Google Docs, Word, Pages, Keynote, any other app or web-app that uses formatting controls like this.

**Comment by jasmussen** [comment] 2017-02-24 09:07
Here's yet another attempt, which still doesn't feel right, but hopefully inspires more experiments:

![formatting click](https://cloud.githubusercontent.com/assets/1204802/23297228/fb9216dc-fa78-11e6-8338-f71a1cd0e2ab.png)

**Comment by iseulde** [comment] 2017-02-24 09:45
> Also — this is a UI that has been solved in the past. Let's look at what others have been doing, like Google Docs, Word, Pages, Keynote, any other app or web-app that uses formatting controls like this.

And WordPress 😉



<img width="138" alt="screenshot 2017-02-24 10 21 16" src="https://cloud.githubusercontent.com/assets/4710635/23297750/029c9aa4-fa7b-11e6-89dc-8f67ff775b44.png">

_Google Docs_ ^

<img width="263" alt="screenshot 2017-02-24 10 25 47" src="https://cloud.githubusercontent.com/assets/4710635/23297905/a4968176-fa7b-11e6-9dfa-91eea883bb7e.png">

_Apple Pages_ ^

**Comment by iseulde** [comment] 2017-02-24 09:48
Anyway, let's not dig too deep into this issue, there are larger problems to solve. :)

**Comment by jasmussen** [comment] 2017-02-24 10:19
The old TinyMCE look is very dated at this point, and very heavy looking. This on its own is not a reason to change it, but since we are doing a lot of modernization elsewhere in the UI, the time to modernize is now, make sure it fits the "language" of the rest of the optimizations we are making. 

The splash of color that Pages adds seems worth exploring! There's a lot of gray in the UI already. The best color person I know in the whole world is @hugobaeta — if I may borrow a minute of your time (please ❤️ ) — is this a place where we can introduce an accent color to the default blue? I know you have some accent colors in your <a href="http://codepen.io/hugobaeta/pen/grJjVp">codepen</a>...

**Comment by jasmussen** [comment] 2017-02-24 10:42
More inspiration. Note, my posting these is not an endorsement — some of these are terrible. 

Here's what Adobe Spark does:

![screen shot 2017-02-18 at 15 04 56](https://cloud.githubusercontent.com/assets/1204802/23299818/4f1b012e-fa83-11e6-8eed-48554fee52af.png)

Here's what Dropbox Paper does:

<img width="515" alt="screen shot 2017-02-24 at 11 20 16" src="https://cloud.githubusercontent.com/assets/1204802/23299837/61a4d1d0-fa83-11e6-9651-bd1784ef6bd5.png">

Here's what Facebook notes does:

<img width="229" alt="screen shot 2017-02-24 at 11 27 37" src="https://cloud.githubusercontent.com/assets/1204802/23300072/4653c2b4-fa84-11e6-8fe8-3069f93cde38.png">

Here's what Google Sites does:

<img width="672" alt="screen shot 2017-02-24 at 11 31 35" src="https://cloud.githubusercontent.com/assets/1204802/23300264/0e475c72-fa85-11e6-9a45-d1791fa12844.png">

Here's what LivingDocs does:

<img width="331" alt="screen shot 2017-02-24 at 11 35 14" src="https://cloud.githubusercontent.com/assets/1204802/23300326/566c5458-fa85-11e6-98aa-58a35dbc4a08.png">

This is what Medium does:

<img width="328" alt="screen shot 2017-02-24 at 11 36 01" src="https://cloud.githubusercontent.com/assets/1204802/23300361/734845aa-fa85-11e6-9bc9-e335ab057cf8.png">

This is what notion does:

<img width="196" alt="screen shot 2017-02-24 at 11 37 34" src="https://cloud.githubusercontent.com/assets/1204802/23300407/ac6e8a74-fa85-11e6-9a94-19cf6048e90f.png">

Quip:

<img width="297" alt="screen shot 2017-02-24 at 11 39 31" src="https://cloud.githubusercontent.com/assets/1204802/23300461/f2a0b206-fa85-11e6-88d6-0468bcb4de7c.png">

Squarespace:

<img width="685" alt="screen shot 2017-02-24 at 11 40 11" src="https://cloud.githubusercontent.com/assets/1204802/23300484/084d3264-fa86-11e6-8d1a-9d6a8dfb949b.png">

Weebly:

<img width="998" alt="screen shot 2017-02-24 at 11 41 34" src="https://cloud.githubusercontent.com/assets/1204802/23300540/3ce07de2-fa86-11e6-83df-3b63fbf84630.png">

Wix, sort of:

<img width="137" alt="screen shot 2017-02-24 at 11 42 18" src="https://cloud.githubusercontent.com/assets/1204802/23300557/52e997ae-fa86-11e6-9aaa-b319ea08843b.png">

**Comment by melchoyce** [comment] 2017-03-02 02:24
Some more ideas:

<img width="811" alt="screen shot 2017-03-01 at 9 22 57 pm" src="https://cloud.githubusercontent.com/assets/2846578/23490267/7f82bd0c-fec5-11e6-881c-eaf92533808b.png">
<img width="815" alt="screen shot 2017-03-01 at 9 24 26 pm" src="https://cloud.githubusercontent.com/assets/2846578/23490268/7f8b33b0-fec5-11e6-8ce1-e8c262cb40de.png">

**Comment by afercia** [comment] 2017-03-02 07:44
Inversion of colors ^^ could help :) Noting the active state should be clear for all controls, so maybe this issue should be extended to other parts of the UI?

<img width="309" alt="screen shot 2017-03-02 at 08 41 59" src="https://cloud.githubusercontent.com/assets/1682452/23497631/63297b28-ff24-11e6-820e-95e01b0709e6.png">

**Comment by jasmussen** [comment] 2017-03-06 10:22
Quick attempt at color inversion:

![formatting click](https://cloud.githubusercontent.com/assets/1204802/23605989/1f15df74-025f-11e7-8aa2-d1f62b521fd3.png)

![type switcher](https://cloud.githubusercontent.com/assets/1204802/23605991/213a1a0e-025f-11e7-8805-7964b7773dba.png)

Feels like it's getting a little busy. But let's keep thinking about this.

**Comment by jasmussen** [comment] 2017-03-06 11:10
Another shot at contrast:

![type switcher](https://cloud.githubusercontent.com/assets/1204802/23607620/ccf74136-0265-11e7-8671-55d45826b1f6.png)

This one looks good to me. The gray is a little darker, but the UI still feels light. The white boundary around the active one adds contrast too.

**Comment by melchoyce** [comment] 2017-03-06 15:39
That last one's a winner.

**Comment by afercia** [comment] 2017-03-06 15:46
I'm sorry to bring bad news 😬 but can't be done with color alone, especially it the difference between non-active/active is so light. It needs an additional indicator, e.g. a shape.

**Comment by iseulde** [comment] 2017-03-06 15:46
Also wanted to point out that the white border doesn't make a difference here. :/

**Comment by melchoyce** [comment] 2017-03-06 15:48
Would a box shadow inside the selected button count?

**Comment by mapk** [comment] 2017-03-06 15:48
The white boundaries around the active states works really well. My only concern is the contrast between the grey background on active states (I realize its darker) and the white background of the toolbar. In the last one posted by @jasmussen its contrast ration is 1.21. 

Really good work.

**Comment by afercia** [comment] 2017-03-06 15:57
I see this issue as very similar to the one discussed for the admin menu in https://core.trac.wordpress.org/ticket/28599 (still to be solved).
From an accessibility perspective there was consensus to add a border (actually a box-shadow) and recently the same pattern was introduced in the Customizer. Not to mention Press This always used that "border".
Not saying the same "border" should be added here, but the active state is a relevant information that shouldn't rely on color alone. Really needs a shape  :)

**Comment by Afraithe** [comment] 2017-03-06 16:15
Our theory here on the TinyMCE side of things is we want our UI to be skinnable, so we could add a high contrast skin. TinyMCE 3.x had that, haven't really had the need for it for TinyMCE 4, but 4 is also skinnable so perhaps ppl are using custom skins for that already. http://skin.tinymce.com/

**Comment by hugobaeta** [comment] 2017-03-06 16:18
Looks like the experiment with the color inversion solves both issues (contrast, and shape). Maybe an ever so slight rounding of the corners of the selected elements would help in softening them?

**Comment by jasmussen** [comment] 2017-03-06 19:48
Thank you @afercia for the context, I hope you'll continue to keep us on our accessibility toes! The core tickets help too.

Could a splash of color like this work?

![type switcher](https://cloud.githubusercontent.com/assets/1204802/23626681/0aa526ea-02ae-11e7-8631-969ae617cf20.png)

This still keeps it visually light, and if we use that shade of blue elsewhere it could be visually coherent also. You mention that "color alone" is not enough — can you elaborate? Does it have to be 

Alternately we should probably do what Hugo suggests and go full on inversion. 

Here's a sketch file just with this piece, for quick iteration: https://cloudup.com/czgnRr9c4P2

**Comment by TheSpyder** [comment] 2017-03-07 00:05
To throw another idea into the pool: what we've ended up with in https://textbox.io is a border on hover, switching to filled on active. It means you don't get a distinct "hover+active" state but we think it works quite well.

This also worked really well for windows high contrast mode where the background colour is ignored; it's still easily usable.

**Comment by jasmussen** [comment] 2017-03-07 08:21
> To throw another idea into the pool: what we've ended up with in https://textbox.io is a border on hover, switching to filled on active. It means you don't get a distinct "hover+active" state but we think it works quite well.

Screenshots, active:

![screen shot 2017-03-07 at 09 18 31](https://cloud.githubusercontent.com/assets/1204802/23647641/1fb45100-0317-11e7-8065-5517e8b1a8d3.png)

Hover:

![screen shot 2017-03-07 at 09 18 37](https://cloud.githubusercontent.com/assets/1204802/23647645/2203404c-0317-11e7-8807-d2f4d6b37883.png)

I like this a lot. 

But is it sufficient with regards to contrast, @afercia? Also, can you refer to any editors with formatting toolbars you've used that pass the WordPress contrast standards? I'd like to look at a few for inspiration. As a reminder, <a href="https://github.com/WordPress/gutenberg/issues/127#issuecomment-282261229">here are a bunch of screenshots</a>.

**Comment by afercia** [comment] 2017-03-07 10:00
> can you refer to any editors with formatting toolbars you've used that pass the WordPress contrast standards

I'm not sure I've used so many editors :) Many of them use a shape, or a combination of background color + shape (e.g. TinyMCE) so they pass the requirement. 

As for the spec, the WCAG don't mention the "active" state (or at least I haven't been able to find anything specifically related to it) but have a lot of recommendations about the focus state, which we should take care of anyways. We can extend what it's recommended for the focus state to the active state too. 

Understanding the "Focus visible" requirement:
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html

Specifically, about colors, see Example 3: Menus:
https://www.w3.org/TR/WCAG20-TECHS/G195.html
> ... the currently focused menu item changes its background to a different color, which has a 3:1 contrast ratio with the surrouding [sic] items and a 4.5:1 contrast ratio with its own text.

So, if you want to use only color, the active/focused button background should have a contrast ratio of at least 3:1 with the other buttons. Otherwise, it needs an additional indicator, like a shape.

I'd say the current implementation in WordPress passes the requirement because it uses a shape (rounded border) together with a slight background color change (which wouldn't be sufficient alone).

<img width="221" alt="screen shot 2017-03-07 at 10 23 58" src="https://cloud.githubusercontent.com/assets/1682452/23650071/290b14fa-0321-11e7-8f31-d876dae7c850.png">

In the screenshot above, the Bold button is focused and the Italic one is active. Both slightly change the background color but that alone wouldn't be sufficient. Luckily, there's a border. If the new editor is going to have an implementation that doesn't allow to clearly distinguish the different states, I'd consider that an accessibility regression.

I'd encourage everyone to make a little effort and try to change the usual approach to design. There are accessibility requirements to satisfy. When designing with accessibility in mind, "design" should have a broader meaning: solving issues and yes, also try to make things look pretty as much as possible :)

**Comment by afercia** [comment] 2017-03-07 10:02
> To throw another idea into the pool: what we've ended up with in https://textbox.io is a border on hover, switching to filled on active. 

@TheSpyder interesting. Aside: I love how in textbox.io all the controls are properly grouped and the toolbars are properly labeled :)

**Comment by jasmussen** [comment] 2017-03-07 10:25
Thank you @afercia, this is very helpful.

> I'd say the current implementation in WordPress passes the requirement because it uses a shape (rounded border) together with a slight background color change (which wouldn't be sufficient alone).

This was the 🔑  bit of clarity needed. The *high contrast border* ensures that the *button* (as a whole) has sufficient contrast with the surrounding items.

I got the vibe from the previous core trac ticket that the current core-bundled TinyMCE (as shown in your screenshots) did not solve the accessibility requirements, which made me confused.

Incidentally here's another shot at the color inversion:

![text](https://cloud.githubusercontent.com/assets/1204802/23652324/bd0d7470-0328-11e7-94f5-a1efac7737a0.png)

**Comment by Afraithe** [comment] 2017-03-07 10:58
Ppl that have contrast issues should be running their OS in contrast mode? So needs to work in that setting more than anything right?

**Comment by jasmussen** [comment] 2017-03-07 11:03
> Ppl that have contrast issues should be running their OS in contrast mode? So needs to work in that setting more than anything right?

Can we detect that OS level setting inside TinyMCE?

**Comment by afercia** [comment] 2017-03-07 11:43
> Ppl that have contrast issues should be running their OS in contrast mode?

Our goal here should be making it accessible out of the box.

**Comment by TheSpyder** [comment] 2017-03-07 13:42
@afercia thanks! We have put a lot of effort into making sure the editor passes ainspector validation, including all dialogs ;)

@Afraithe the standards have contrast requirements even when not running in high contrast mode :(

@jasmussen you can, we have detection in textbox.io to activate our high contrast stylesheet. Chrome has an easy way to do it, other browsers need a bit of CSS trickery to detect that the browser isn't rendering backgrounds.

**Comment by jasmussen** [comment] 2017-03-07 15:56
@afercia I'm digging the active/inactive design that Sketch uses:

![screen shot 2017-03-07 at 16 53 46](https://cloud.githubusercontent.com/assets/1204802/23664787/dd5ae73e-0356-11e7-87f3-5cdb16b16dc6.png)

Would this design pass accessibility requirements? If no, why not? Thanks much for letting me ask you these questions.

**Comment by joyously** [comment] 2017-03-07 16:50
@jasmussen When I first saw that, my eye went to the larger boxes and I thought brighter meant selected (or active). Then I looked at the smaller ones and realized it was the other way around. I see this kind of confusion on a lot of mobile apps that just have a toggle. It's difficult to tell which way it is set to.

**Comment by afercia** [comment] 2017-03-07 17:11
@jasmussen it's simple :) there are several tools to pick colors and calculate the contrast ratio. We often refer, improperly, to "color contrast" but actually it's about the luminosity contrast ratio.

About Sketch, pick the color of the active and inactive buttons, they're white and approximately `#e5e5e5` right? For quick checks I often use this online tool our friend Joe Dolson made available for us: https://www.joedolson.com/tools/color-contrast.php

Enter the two colors and the ratio is `1.26:1`. Instead, it must be at least `3:1`, unless we're going to use some additional indicator to distinguish the different states.

Additionally, the contrast between the buttons text (icons) and their background must always be at least `4.5:1`. Only for text with a font size of at least 18 point or 14 point bold (equivalent to approximately 24px and 18.5px bold) the minimum contrast ratio is `3:1`.

**Comment by annaephox** [comment] 2017-03-08 06:34
Great discussion with some really interesting insights, which I think distill down to three (+1) key points:

1. Accessibility should be designed into the product from the start, not added in later
2. **It's quite challenging to meet accessibility requirements using colour alone - especially in the context of wanting a "light and modern" aesthetic**
3. If colour alone is not enough, we need to use something else - like shape
4. [optional bonus] The interaction is a little fun :)

So today we had a crack at playing around with something that meets the above criteria: you can interact with it here [http://codepen.io/napy84/pen/LWbBrv](http://codepen.io/napy84/pen/LWbBrv)

<img width="256" alt="screen shot 2017-03-08 at 4 24 43 pm" src="https://cloud.githubusercontent.com/assets/25762760/23692674/c9b7286c-041b-11e7-8dea-b670b74bf03c.png">

It's possibly too much/not the right kind of animation ( discussion on animation style guide here #15 ) to be used on every button, but perhaps if used selectively, like on the block level controls, could be both elegant and provide differentiation from the [selection]-toolbars

**Comment by jasmussen** [comment] 2017-03-08 08:31
Thank you for your endless patience here, @afercia. This is important to get right. It sounds like the following would pass:

![type switcher](https://cloud.githubusercontent.com/assets/1204802/23695752/f77d423a-03e0-11e7-8ae0-56bc5f59571c.png)

But by those rules put out alone it sounds like Google Docs, Office 365, Apple Pages, Sketch would all fail:

![office365](https://cloud.githubusercontent.com/assets/1204802/23695806/374c85e2-03e1-11e7-807c-a8d01306e478.png)

![docs](https://cloud.githubusercontent.com/assets/1204802/23695809/3aab538a-03e1-11e7-81c7-0984905c17ec.png)

![sketch](https://cloud.githubusercontent.com/assets/1204802/23695814/3faeb52a-03e1-11e7-969a-3a4064f9e8a1.png)

![apple pages](https://cloud.githubusercontent.com/assets/1204802/23695820/45229256-03e1-11e7-8c59-e3929e7eb17a.png)

That last one is Apple Pages, which achieves a 2.6:1 contrast ratio, the most of them all. But it's still not 3:1. 

Can you confirm that all those above fail the accessibility bar, or do they pass through other means? If so, what makes them pass? You mention:

> unless we're going to use some additional indicator to distinguish the different states

To me this sounds like a border, or an inset shadow on the active item. But in all of those above, the border itself does not have enough contrast either. Is it the very dark border around the active item in current TinyMCE that makes the current iteration of the editor pass? 

![screen shot 2017-03-08 at 09 30 27](https://cloud.githubusercontent.com/assets/1204802/23695963/ed047e8a-03e1-11e7-967a-a8a6b351d260.png)

I am very grateful for your time here.

**Comment by iseulde** [comment] 2017-03-08 08:59
> Is it the very dark border around the active item in current TinyMCE that makes the current iteration of the editor pass?

Yes, it is. :) Here's the most recent commit for that: https://github.com/WordPress/wordpress-develop/commit/e9f19035864e432453ff0978eaa5a6379ccdc6c5

Would be good to know which others pass or not. It sounds like inverse colours make it so that appearance is distinct enough from the other buttons.

Even if the others do _not_ pass, it doesn't mean our editor shouldn't, and this is a great area where the WordPress editor can shine, together with all the other improvements we're doing. Like @afercia mentioned, it's a really interesting design challenge, where alternative creative solutions are welcome. Maybe there's a whole new way to design active states. :)

**Comment by jasmussen** [comment] 2017-03-08 09:01
> Even if the others do not pass, it doesn't mean our editor shouldn't

Absolutely, did not mean to imply otherwise. 😉

**Comment by Afraithe** [comment] 2017-03-08 09:46
Googles Material Design could also be a source of inspiration around this I guess.

https://material.io/guidelines/components/buttons.html

**Comment by jasmussen** [comment] 2017-03-08 09:57
How's this?

![type switcher](https://cloud.githubusercontent.com/assets/1204802/23699010/ecc523aa-03ed-11e7-944e-a0ec73ede09a.png)

That's a 4.8:1 on the contrasts, as far as I can tell.

**Comment by mapk** [comment] 2017-03-08 15:42
According to @afercia:

> Enter the two colors and the ratio is 1.26:1. Instead, it must be at least 3:1, unless we're going to use some additional indicator to distinguish the different states.

So that means this ones fails:

![374c85e2-03e1-11e7-807c-a8d01306e478](https://cloud.githubusercontent.com/assets/617986/23710422/88f79522-03d1-11e7-8f55-2a0e18ae6c1b.png)
Luminosity Contrast is 1.46:1


The gradient in this one might be a bit more tricky?
![3faeb52a-03e1-11e7-969a-3a4064f9e8a1](https://cloud.githubusercontent.com/assets/617986/23710482/c3035972-03d1-11e7-9a35-c4858b663a47.png)

Lighter top Lum Contrast is 2.15:1
Darker bottom Lum Contrast is 3.1:1
But it's also inverting the color, which is more than just changing the background.


I do like this one below the best. But we still need a HOVER state designed.
![f77d423a-03e0-11e7-8ae0-56bc5f59571c](https://cloud.githubusercontent.com/assets/617986/23710625/37c5141c-03d2-11e7-93ef-c334ab0988e2.png)

**Comment by afercia** [comment] 2017-03-08 20:19
I think the one with the subtle dark border, the last one posted by @jasmussen would pass 🙂 Also the last one by @mapk 🙂 

> by those rules put out alone it sounds like Google Docs, Office 365, Apple Pages, Sketch would all fail

I'm really not sure what are their accessibility requirements 🙂 

>  it's a really interesting design challenge, where alternative creative solutions are welcome. Maybe there's a whole new way to design active states. :)

Yay! +1

**Comment by TheSpyder** [comment] 2017-03-08 21:45
There's a tool to help you know if it passes - a Firefox addon called ainspector. It will likely complain about a lot more than contrast, but if you're diving into accessibility that's a good tool to use in general. It's very picky but so are the standards 😉

The last one by @mapk is what we do in textbox.io which definitely passes.

**Comment by jasmussen** [comment] 2017-03-29 07:47
Closing as this is solved by the inverted version in the mockups: https://wpcoredesign.mystagingwebsite.com/gutenberg/

Feel free to reopen if this issue surfaces again.

**Closed by jasmussen** 2017-03-29 07:47 UTC
Labels: Accessibility, Design
