### ISSUE TITLE
When confirming Kanji conversion in Japanese input, characters disappear

### ISSUE THREAD

**Issue by mt8** [WordPress/gutenberg#65675] opened 2024-09-26 11:31 UTC
### Description

Enter Japanese into the paragraph block/heading block, etc., and confirm the kanji conversion.

### Step-by-step reproduction instructions

- Open the post page.
- Enter Japanese into a paragraph block and convert it to Kanji.
- Confirm the conversion with the ENTER key

Press the space key or enter key during conversion to reproduce

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/35745f36-d0f6-40d7-9e90-9bfbb3901fd6

### Environment info

WordPress: 6.6.2 (Japanese)
Gutenberg Plugin: 19.3  (Japanese)

macOS Sonoma
Chome (129)

This problem is theme independent.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by torounit** [comment] 2024-09-26 11:38
I could reproduce the same problem.

This problem seems to have occurred since 19.2.0

Chrome 129 / mac OS 14.6.1

https://github.com/user-attachments/assets/317e7947-aba8-406c-a0e9-b03e628e7c74

This did not occur in firefox 131.

**Comment by mt8** [comment] 2024-09-26 11:40
Reproduced with Microsoft Edge (129) installed on Mac

**Comment by torounit** [comment] 2024-09-26 11:47
ping: @t-hamano @mirka

**Comment by t-hamano** [comment] 2024-09-26 12:14
Thanks for the report.

I tested on Windows OS and was not able to reproduce the issue.

- Tested Gutenberg versions:
  - Gutenberg version 19.3: https://playground.wordpress.net/?plugin=gutenberg
  - Gutenberg trunk (5df9613)
- Browser:
  - Chrome 129.0.6668.71
  - Firefox 130.0.1
  - Edge 129.0.2792.52

This might be an OS-specific issue, but I cannot test on MacOS in my environment.

I'd be grateful if someone who can reproduce this issue could use `git bisect` or similar to identify which commit caused the problem.

**Comment by mt8** [comment] 2024-09-26 12:20
Additional information.
It didn't reproduce in 19.1, but it did in 19.2.

**Comment by mt8** [comment] 2024-09-26 12:36
Looks like this revert PR fixes it.
https://github.com/WordPress/gutenberg/pull/65414

I also confirmed that the problem does not occur on the trunk/6.7 branch.

**Comment by Mamaduka** [comment] 2024-09-26 12:38
Thanks for confirmation, @mt8!

I was about to suggest testing that revert commit, but I'll close the issue now that it's fixed.

**Closed as completed by Mamaduka** 2024-09-26 12:38 UTC
Labels: [Type] Bug, [Feature] Rich Text

**Comment by mt8** [comment] 2024-10-07 12:46
Did not reproduce in `19.4.0 RC1`
