### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by photogenicworld** [WordPress/gutenberg#10030] opened 2018-09-19 12:48 UTC
**Describe the bug**
Featured image doesn't show in preview

**To Reproduce**
1. Set a Featured image in Gutenberg
2. Click Preview

**Expected behavior**
Featured image appears in preview

**Actual behaviour**
Featured image does not appear

**Comment by tofumatt** [comment] 2018-09-19 15:46
Tested this and it does appear when set in the Classic Editor but not in Gutenberg.

**Comment by designsimply** [comment] 2018-09-19 15:49
Thanks for the report! Closing as a duplicate of #9151.

**Closed by designsimply** 2018-09-19 15:49 UTC
Labels: [Component] Post Settings, [Component] Saving, [Status] Duplicate, [Type] Bug
