### ISSUE TITLE
Regression: can no longer activate block by clicking in the top area

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#12163] opened 2018-11-21 09:53 UTC
**Describe the bug**
You can no longer activate a block when clicking in the green area indicated on the image:

![](https://user-images.githubusercontent.com/1204802/48617788-b0c78780-e997-11e8-8f32-d41258c36305.png)

Video of current Frontenberg (Gutenberg 4.5.0):

![cantselect](https://user-images.githubusercontent.com/6892634/48832493-ee565700-ed81-11e8-964c-770d7c4dbb47.gif)

Can only select a paragraph by clicking on the rich text directly.

Video of Gutenberg 4.1.1:

![canselect](https://user-images.githubusercontent.com/6892634/48832500-f31b0b00-ed81-11e8-9d1e-38b587030c3b.gif)

Could select the paragraph by clicking whereever the blue border hover effect appears.

In some nested block scenarios there is very little area available to click to select a "parent" block:

![](https://camo.githubusercontent.com/3899fcfc5e42c7d2d70222c96da19a49447025bd/68747470733a2f2f692e696d6775722e636f6d2f356a6330447a792e706e67)

forcing the use of Block Navigation item in the top toolbar, which is somewhat cumbersome for a simple goal.

**Additional context**

Likely a regression of https://github.com/WordPress/gutenberg/pull/11018

More info at https://github.com/WordPress/gutenberg/pull/11357#issuecomment-439538510

**Comment by aduth** [comment] 2019-05-29 17:18
While technically it was created afterward, I'm going to close this in favor of #13723 as a duplicate.

I'll copy context of your comment into the discussion for posterity.

Duplicate of #13723

**Closed by aduth** 2019-05-29 17:18 UTC
Labels: Regression
