### ISSUE TITLE
pasteHandler ignores FormattingControls prop

### ISSUE THREAD

**Issue by leorospo** [WordPress/gutenberg#18637] opened 2019-11-20 15:40 UTC
**Describe the bug**
Setting the formattingControl prop in a RichTextComponent to `['italic']` will limit the formatting options in said block to only show the italic button.
The problem is that when you copy / paste some text from a word document it will keep the orignal formattimg even if it is not allowed in the component. Moreover because of the lack of the other formatting buttons the user is not able to manually remove the unwanted/unallowed formatting styles.

**To reproduce**
1. Register a Block with a RichText component and formattingControls prop set to italic
```
            <RichText
                tagName="h4"
                value={text}
                formattingControls={['italic']}
                onChange={(content) => setAttributes({ text: content })}
            />
```
2. Copy / paste some text containing various combination of bold and italics
3. Try to remove the unallowed bold formatting.

**Expected behavior**
On paste the unallowed formatting styles are ignored and treated like normal text.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox Developer Edition

**Might reference**
Overview: Writing Flow #16280
https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Raw%20Handling

**Comment by ellatrix** [comment] 2019-12-10 20:56
I'm not sure if this is to be expected or not. The `formattingControls` props controls the formatting controls. It doesn't disallow certain formatting in the RichText instance. You can still go to the HTML view and add anything you like there. I'm open to limiting paste in this case though.

**Comment by leorospo** [comment] 2020-07-23 16:19
The behaviour persist with th `allowedFormats` prop

**Comment by mirka** [comment] 2021-04-16 12:25
Related: #7591

**Comment by Mamaduka** [comment] 2024-08-22 07:19
I'm going to close the issue.

## Why

* The `allowedFormats` prop works as designed. The setting controls format options displayed for a RichText instance, not the paste behavior.
* The `__unstablePastePlainText` can change the latter.

**Closed by Mamaduka** 2024-08-22 07:19 UTC
Labels: [Type] Enhancement, [Feature] Rich Text, [Feature] Paste

**Comment by rafaucau** [comment] 2026-01-19 22:18
Looks like `__unstablePastePlainText` is not working anymore.
