### ISSUE TITLE
Image block: 180 degrees rotation forces the image to crop

### ISSUE THREAD

**Issue by evakaneva** [WordPress/gutenberg#30962] opened 2021-04-19 13:53 UTC
## Description
When the image is rotated to 180 degrees, a crop area appears.

## Step-by-step reproduction instructions
1.Insert an Image block
2.Upload image 
3.Click the crop icon 
4.Click rotation button twice
4.Observe image has crop

## Expected behaviour
I would expect the image to rotate without crop.

## Actual behaviour
The image cannot be rotated without it being cropped. 

## Screenshots or screen recording (optional)
![cropbug0](https://user-images.githubusercontent.com/51059617/115246947-038c6700-a12f-11eb-8ad9-eb983a6d703e.gif)

## WordPress information
- WordPress version:  5.7.1
- Gutenberg version:  Version 10.4.1 
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Q (q) version 0.7

## Device information
- Device:  Desktop
- Operating system:  Big Sur 11.1
- Browser:  Safari Version 14.0.2

**Comment by skorasaurus** [comment] 2021-04-20 14:33
Thank you for reporting and including clear steps and a screenshot. 

I'm able to reproduce this; also on Version 10.4.1; using firefox/ubuntu and twentytwentyone theme.

**Comment by Thelmachido** [comment] 2022-08-12 10:30
I tested this recently but I am unable to reproduce the issue as shown in the video below:

https://user-images.githubusercontent.com/41231764/184336278-aa553c7d-bb15-45f9-8b6c-08cd949d7301.mov

WordPress 6.0.1

Gutenberg 13.8.1 active

Closing this issue

**Closed as completed by Thelmachido** 2022-08-12 10:30 UTC
Labels: [Type] Bug, [Block] Image
