### ISSUE TITLE
Group: Add background support

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#15664] opened 2019-05-15 15:21 UTC
See #4900.

Now that the group block is pretty solid, let's explore adding background support:

![Image](https://user-images.githubusercontent.com/2846578/57787187-ea890900-7702-11e9-8dca-e3a4d4de72de.png)
![Color](https://user-images.githubusercontent.com/2846578/57787201-eceb6300-7702-11e9-87dd-d8035081d606.png)

_(Please note that as this is an older mockup, many general UI elements are outdated.)_

Some questions:
- We'd be reusing image settings from Cover.
- Instead of overlay color, I'm using opacity, so color and image can remain independent. Does this make sense?
- Should we use the new swap image flow for changing background images and include an image icon in the toolbar, instead of putting it in the sidebar?
- Is there any way to measure color contrast of text over an image?

**Comment by youknowriad** [comment] 2019-05-15 15:26
This is a duplicate of #14744, can we consolidate?

**Comment by melchoyce** [comment] 2019-05-15 15:36
Good catch, I'll close & move over.

**Closed** 2019-05-15 15:36 UTC
Labels: Needs Accessibility Feedback, Needs Design Feedback, [Block] Group
