### ISSUE TITLE
Exiting a scheduled post triggers "Do you want to leave"

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2997] opened 2017-10-12 04:55 UTC
Gutenberg version: 1.4

## Issue Overview

When I schedule a post for later and then attempt to leave the page, I get a warning asking if I want to leave despite not having any unsaved changes

## Steps to Reproduce (for bugs)

1. write a post
2. schedule it for later
3. Try to leave the page
4.

## Expected Behavior

Scheduling a post should be considered the same as publishing it and no warning should be triggered.

**Comment by vladanost** [comment] 2017-10-16 14:04
Gutenberg version 1.4
I followed recommended steps and I'm not able to reproduce the issue.

**Comment by youknowriad** [comment] 2017-10-20 09:06
I'm not able to reproduce either.

**Comment by karmatosed** [comment] 2017-11-07 17:57
Closing as unable to reproduce in latest version of Gutenberg.

**Closed by karmatosed** 2017-11-07 17:57 UTC
Labels: [Status] Needs More Info
