### ISSUE TITLE
Changing top and bottom causes "custom html" blocks to be uneditable

### ISSUE THREAD

**Issue by jeiseman** [WordPress/gutenberg#14071] opened 2019-02-24 00:06 UTC
**Describe the bug**
Reducing the top and bottom margins of blocks causes the "custom html" blocks to be uneditable.
The problem shows up in all blocks but is more severe in the "custom html" blocks. You can see from the following screenshot that even for paragraph blocks the first block is interfering with the second block:
https://cl.ly/4bff581651a0

**To Reproduce**
1. Create a post containing two "custom html" blocks with a single line of html in each one.
2. Add the following custom css to the admin block-editor.css
`.editor-block-list__layout .editor-block-list__block .editor-block-list__block-edit {
    margin-bottom: 10px;
    margin-top: 10px;
}`
3. Try to edit the first of the two "custom html" blocks.

You will find that you can't edit the first block.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - chrome
 - Version 72

**Additional context**
- WordPress 5.1

**Comment by gziolo** [comment] 2019-05-24 05:44
It's duplicate of #12577 and it's an issue even when you don't change margins at all.

**Closed by gziolo** 2019-05-24 05:44 UTC
Labels: Needs Technical Feedback, [Block] HTML
