### ISSUE TITLE
Uncaught TypeError in Gutenberg 16.6.0

### ISSUE THREAD

**Issue by vishalBoleGIT** [WordPress/gutenberg#54660] opened 2023-09-20 11:46 UTC
### Description

**PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, null given in /wordpress/plugins/gutenberg/16.6.0/lib/compat/wordpress-6.4/script-loader.php:38**

### Step-by-step reproduction instructions

My site is working till starting of September then it is showing "**There has been a critical error on this website.**".

Showing me the this error in my **debug.log** file:  "**PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, null given in - wordpress/plugins/gutenberg/16.6.0/lib/compat/wordpress-6.4/script-loader.php : line number 38**"

When i deactivate gutenberg plugin from **ftp** then my site is working.

Please help me!

### Environment info

WordPress Version 6.3.1.
Gutenberg Version 16.6.0
Elementor theme
Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by felipevelzani** [comment] 2023-09-21 00:45
Hi @vishalBoleGIT,

I couldn't reproduce the same issue from my end.

I see you added the Elementor theme as part of your environment. 

Can you please try with a default WordPress theme? Also, please ensure that all your plugins are deactivated.

I'm closing this issue for now, but please let me know if you still reproduce this after all.

**Closed as not planned by felipevelzani** 2023-09-21 00:45 UTC
Labels: [Type] Question
