### ISSUE TITLE
Reusable Blocks Missing

### ISSUE THREAD

**Issue by ChrissiePollock** [WordPress/gutenberg#21547] opened 2020-04-11 16:44 UTC
I am scheduling posts for November on https://chrissie.blog/ (WordPress.com site on the Business plan with plugins) and have a Reusable Block I created in January. I went to add to my post, and I discovered my reusable block is missing. The other reusable blocks I had created last year are missing as well. There are now templates I did not create in the Reusable Blocks options instead.

![screenshot](https://d.pr/i/Q1CYop+)

Next, I went to scheduled posts I created in January and February, and I see that my Reusable Block is missing from those posts as well.

![screenshot](https://d.pr/i/rmemaw+)

I added two new Reusable Blocks then went into the blocks to edit them. I clicked on Manage all Reusable Blocks and it took me to a page with this message:

![screenshot](https://d.pr/i/eVcuxR+)

Chrome and Firefox and in the WordPress app on my iPhone SE I see:

![screenshot](https://d.pr/i/H51YAa+)

**Comment by jasmussen** [comment] 2020-04-16 11:32
Hi Chrissie, thanks for the ticket. I was able to learn that this issue was caused by [an issue with the AMP plugin](https://github.com/ampproject/amp-wp/releases/tag/1.5.1). So I'm closing it here.

**Closed by jasmussen** 2020-04-16 11:32 UTC
