### ISSUE TITLE
Classic block doesn't get removed on Cmd (or Ctrl) + Z Undo shortcut

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6977] opened 2018-05-28 12:36 UTC
As a default behavior, when a block gets added, the Undo command removes it. This works also with the keyboard shortcut Cmd + Z (or Ctrl + Z depending on the operating system).

However, the keyboard shortcut doesn't work for the Classic block. Only the Undo button in the top toolbar works. To reproduce:
- create a new post
- add a paragraph
- add some text within the paragraph
- press Cmd + Z (or Ctrl + Z) and observe: entered text gets removed and eventually the paragraph block itself gets removed

Repeat the steps above with a Classic block: the block doesn't get removed.

While I understand "undo" works a bit differently in a Classic block (it's TinyMCE), the behavior across blocks should be consistent.

**Comment by ajitbohra** [comment] 2018-07-08 20:29
Unable to reproduce this on the master. Hence closing this for now, feel free to reopen.

**Closed by ajitbohra** 2018-07-08 20:29 UTC
