### ISSUE TITLE
Padding - youtube embedded videos

### ISSUE THREAD

**Issue by andreasdiehl** [WordPress/gutenberg#9952] opened 2018-09-17 08:48 UTC
When embedding a youtube video there its imo not enough padding to the next abstract / block:

https://www.dropbox.com/s/40zb4yyi6ms18qr/2018-09-17_10-43-20.png?dl=0

![kfkx_6eq](https://user-images.githubusercontent.com/1119271/45643668-db20c580-ba78-11e8-81db-bf8c0222ea3c.png)

**Comment by arunsathiya** [comment] 2018-09-18 17:44
I am not able to see the same behaviour though. This is how it looks at my end. The blocks tested with, the ones following the YouTube embed are:

- Paragraph
- Heading
- Quote
- List

<img width="697" alt="screen shot 2018-09-18 at 23 12 32" src="https://user-images.githubusercontent.com/18581859/45705913-7bb9d700-bb98-11e8-8e23-fa5fc0c21464.png">
<img width="697" alt="screen shot 2018-09-18 at 23 12 41" src="https://user-images.githubusercontent.com/18581859/45705914-7bb9d700-bb98-11e8-96e4-7ea6a1a047ef.png">
<img width="690" alt="screen shot 2018-09-18 at 23 12 53" src="https://user-images.githubusercontent.com/18581859/45705917-7bb9d700-bb98-11e8-8483-151135ea604a.png">
<img width="710" alt="screen shot 2018-09-18 at 23 13 08" src="https://user-images.githubusercontent.com/18581859/45705918-7c526d80-bb98-11e8-9129-bbe1c47b9058.png">

Can you expand a bit more on what block you are using right after the YouTube block?

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.8.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.13.6

**Comment by andreasdiehl** [comment] 2018-09-18 18:09
Thanks for taking care of that.

This is a screenshot from the backend:
https://www.dropbox.com/s/cvfz5u1bp3ycx9h/2018-09-18_20-07-06.png?dl=0

It doesn't  t matter if the youtube block is followed by a headline or text block.

You can check this behaviour here:
https://digitaleneuordnung.de/blog/jobs-to-be-done/

**Comment by arunsathiya** [comment] 2018-09-19 14:59
I see what the behaviour on your page, but I am not able to reproduce the same at my end. Please check the images below.

<img width="662" alt="screen shot 2018-09-19 at 10 27 11" src="https://user-images.githubusercontent.com/18581859/45761781-8a60c680-bc4a-11e8-853d-d46a3bd7aebe.png">
<img width="653" alt="screen shot 2018-09-19 at 10 27 26" src="https://user-images.githubusercontent.com/18581859/45761782-8a60c680-bc4a-11e8-9068-4ce4e3e6c980.png">
<img width="659" alt="screen shot 2018-09-19 at 10 27 40" src="https://user-images.githubusercontent.com/18581859/45761783-8af95d00-bc4a-11e8-9b08-93dc87f85d2b.png">
<img width="660" alt="screen shot 2018-09-19 at 10 27 55" src="https://user-images.githubusercontent.com/18581859/45761784-8af95d00-bc4a-11e8-8e3c-cd7f5269b42f.png">

I also looked at your site's CSS and nothing seems to be off. It could be possible that I am overseeing something. Do you see any specific CSS for the YouTube or the block beneath that? Places to look - the CSS section on you WordPress Customizer or any CSS plugins you might be using?

**Comment by andreasdiehl** [comment] 2018-09-19 15:06
I am not a developer, no plugins. Maybe i should discuss that with the theme developper?

**Comment by arunsathiya** [comment] 2018-09-19 15:27
A good starter would be to test this behaviour using another theme. If you are not able to reproduce that on that theme, I would encourage checking with your theme developer, yes.

**Comment by andreasdiehl** [comment] 2018-09-19 15:38
Thats what you did already.:) I will simply add this thread to the ticket.

**Comment by andreasdiehl** [comment] 2018-09-20 06:08
Thanks for the efforts, the theme developer does not yet officially support Gutenberg, so I have to wait. Thanks though.

**Comment by youknowriad** [comment] 2019-01-26 14:44
I'm closing as it looks like a theme issue not actionable within Gutenberg. Thanks.

**Closed by youknowriad** 2019-01-26 14:44 UTC
Labels: Blocks, Needs Testing, [Block] Embed, [Type] Enhancement
