### ISSUE TITLE
Duotone: Presets with custom variables don't work

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52875] opened 2023-07-24 09:49 UTC
### Description

When defining a duotone palette in the theme.json but using colors from the color palette, those duotone filters won't work then. (the name is also not correctly displayed as in here https://github.com/WordPress/gutenberg/issues/52733)

### Step-by-step reproduction instructions

1. Define colors in your theme.json
2. Try to use those colors for duotone filters

### Screenshots, screen recording, code snippet

<img width="450" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/d7dc22d3-f84c-47e9-a889-4b3bc2d39ef9">

```
  "settings": {
    "appearanceTools": true,
    "color": {
      "duotone": [
        {
          "colors": [
            "var(--wp--preset--color--light)",
            "var(--wp--preset--color--dark)"
          ],
          "name": "Light",
          "slug": "light"
        },
        {
          "colors": [
            "var(--wp--preset--color--dark)",
            "var(--wp--preset--color--light)"
          ],
          "name": "Dark",
          "slug": "dark"
        },
        {
          "colors": [
            "var(--wp--preset--color--primary-90)",
            "var(--wp--preset--color--primary-120)"
          ],
          "name": "Primary 90",
          "slug": "primary-110"
        }

…
```

However, it is possible to select from the color palette in the editor:
<img width="450" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/e4467515-f065-4ea3-bc8f-0d9ccfa12281">

### Environment info

- Wp 6.2.2
- GB 16.2.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Olein-jp** [comment] 2023-07-28 12:22
I was thinking exactly the same thing.

I find it quite useful to be able to set the colours of the colour palette defined in theme.json with CSS variables, so that I can control the colour scheme even when switching between Style Variations.

**Comment by ajlende** [comment] 2023-08-02 11:41
This is a duplicate of https://github.com/WordPress/gutenberg/issues/33905

**Closed as completed by ajlende** 2023-08-02 11:41 UTC
Labels: [Type] Bug, Needs Testing, [Feature] Colors
