### ISSUE TITLE
wordcount does not count numbers as a word

### ISSUE THREAD

**Issue by phena109** [WordPress/gutenberg#26339] opened 2020-10-21 02:42 UTC
**Describe the bug**
As title, the wordcount function does not count plain numbers as a word.

**To reproduce**
Put something like "Should be 4 words"

**Expected behavior**
Total words (based on the example) should be 4 words (rather than 3)

**Screenshots**
no

**Editor version (please complete the following information):**
I use the npm package of @wordpress/wordcount

**Desktop (please complete the following information):**
 - OS: Ubuntu (via WSL)
 - Browser Firefox

**Additional context**
no

**Comment by Soean** [comment] 2020-10-22 09:47
I think the behavior is intended, numbers are no words.

See this test: https://github.com/WordPress/wordpress-develop/blob/6b366c6620fdd5960cedcdf80955966a715efa82/tests/qunit/wp-admin/js/word-count.js#L35-L39

**Comment by phena109** [comment] 2020-10-22 22:30
I wouldn't be surprise that's the case. I have done research before raising this, MS Words, and libraries (PHP, JS) I found count numbers as words with no exception. Not that this library has to conform with others but this makes it unusable to most people that are thinking the other way. Will you at least consider an option for the alternative behaviour?

**Comment by Soean** [comment] 2020-10-27 08:19
Good point, I tested Microsoft Word, Google Docs and Libre office, all apps count numbers as a word. So I think we should change it in WordPress

**Comment by gaavar** [comment] 2020-11-09 15:25
- Hi! I am new to open source and would like to take a stab at this issue. Can I work on this?

**Comment by skorasaurus** [comment] 2020-11-14 19:04
duplicate of #17988

**Comment by bosconian-dynamics** [comment] 2020-11-26 03:03
@gaavar if you would like to take a stab this please do! If not, please let me know - I would be happy to jump in on this as well :)

[The contributor's guide](https://developer.wordpress.org/block-editor/contributors/) is a good resource if you haven't read through it yet.

**Comment by phena109** [comment] 2020-11-26 08:53
Sorry, I actually did a PR. I am a first time contributor. It seems the pipeline failed. Is there something I can do to get it approved?

**Comment by Soean** [comment] 2020-11-26 09:51
@phena109 Thanks for your contribution. I restarted the tests. 
Your pull request will be reviewed in the next days. If you get no feedback, you can ask in the #core-editor channel in the [wordpress slack](https://make.wordpress.org/chat/).

**Closed** 2021-05-14 10:13 UTC
Labels: Good First Issue, Needs Dev, [Package] Word count, [Status] In Progress, [Type] Enhancement
