### ISSUE TITLE
Inconsistency in Google Fonts Activation Status

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#58762] opened 2024-02-07 05:04 UTC
### Description

After successfully activating and installing the Google Fonts asset, there is an inconsistency in the font's selection status. Despite receiving a success message indicating that the font was installed correctly, the user interface displayed the font as unchecked or unselected, suggesting it had not been chosen.

**Expected Behavior:**
The font should appear as selected or checked off immediately after installation, reflecting the success message.

**Actual Behavior:**
The font appears unchecked or as if it hadn't been selected despite the success message. However, upon navigating back to the Library tab, the font is listed as Active.

### Step-by-step reproduction instructions

- Open the Font Library modal 
- Select the `Install Fonts` tab
- Click one of Google Fonts and check some variations 
- Click the `Install` button
- Observe the success message confirming the font's installation.
- Observe that the font appears **unchecked**
- Select the `Library` tab
- Observe that the fonts are active

### Screenshots, screen recording, code snippet

<img width="704" alt="Screenshot 2024-02-07 at 14 01 58" src="https://github.com/WordPress/gutenberg/assets/5287479/7bfe26e9-5d7a-45ae-894c-49705c3c39ce">

### Environment info

- Gutenberg > 17.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by arthur791004** [comment] 2024-02-07 08:19
The condition of “checked” seems to be different from the “Library” and ”Install Fonts“.
* The “Library” checks whether the font variant is installed or activated. See https://github.com/WordPress/gutenberg/blob/7472c0d3aa03c28be19f9814f73824970cabf257/packages/edit-site/src/components/global-styles/font-library-modal/library-font-variant.js#L51
* The “Install Fonts” checks whether the font variant is in outline. See https://github.com/WordPress/gutenberg/blob/7472c0d3aa03c28be19f9814f73824970cabf257/packages/edit-site/src/components/global-styles/font-library-modal/collection-font-details.js#L43

I guess it's the expected behavior but the user may feel confused 😅

**Comment by annezazu** [comment] 2024-02-07 16:19
This feels related to this issue: https://github.com/WordPress/gutenberg/issues/58276 Perhaps we can consolidate there to think about the entire experience?

**Comment by colorful-tones** [comment] 2024-02-16 03:06
This also overlaps with #58989 and considerations around UI/UX could impact both of these.

**Comment by ironprogrammer** [comment] 2024-02-23 01:10
IMHO this is the same as #58989, which has a bit more recent activity and design discussion going on.

@okmttdhr, would you mind if this issue was closed and continued to be tracked over in #58989?

**Comment by arthur791004** [comment] 2024-02-23 02:52
Sure. Let's close this one in favor of https://github.com/WordPress/gutenberg/issues/58989 🙂

**Closed as completed by arthur791004** 2024-02-23 02:52 UTC
Labels: [Type] Bug, [Feature] Font Library
