### ISSUE TITLE
List block - Pasting Multiline Text - Strange behavior

### ISSUE THREAD

**Issue by dionysous** [WordPress/gutenberg#9476] opened 2018-08-30 16:06 UTC
## Describe the bug

Pasting multiline text from clipboard into list element creates two empty list blocks and a paragraph block in between.

## To Reproduce

1. I have a bit of text _(including line breaks)_, which I copied to clipboard. E.g.:
```
Lorem ipsum dolor sit amet.
Ipsum dolor sit amet.
Lorem ipsum dolor sit amet.
```

2. Then I go to the Gutenberg **Editor** > **Add new Block** > **Add List Block**

3. I insert the text into the first list element in that block. Instead of being inside the first list element, which is expected from other editors, you get an empty list block, then one paragraph block with the pasted text and under that an empty list block again:

![list-block-behavior-pasting](https://user-images.githubusercontent.com/12687777/44863578-cd4c0180-ac7d-11e8-9eb9-c809580fa9ff.gif)
## Expected behavior

When pasting the text into the first list element, the text should be in that list element, not in an paragraph block:

![list-block-expected-behavior](https://user-images.githubusercontent.com/12687777/44863922-bd80ed00-ac7e-11e8-8a0e-dd781d84cbf5.gif)
## Desktop used:
 - OS: MacOS Mojave
 - Browser: Google Chrome, Mozilla Firefox, Safari
 - Versions: Latest

## Additional context
- Gutenberg Version 3.6.2

**Comment by designsimply** [comment] 2018-08-31 21:18
Tested and confirmed using WordPress 4.9.8 and Gutenberg 3.7.

I think it would be a nice enhancement to remove leading and trailing white space from pasted content within list items, but it would also be good to see what developers working on the project think about that as well.

**Comment by mcsf** [comment] 2018-09-14 10:07
Related: https://github.com/WordPress/gutenberg/issues/5727

**Comment by designsimply** [comment] 2018-10-16 20:44
Thank you for testing Gutenberg at this stage and for reporting the issue! I am closing this one in favor of #10042 because it has a bit more information and also notes a problem with undo which could be relevant. Both issues are good but I want to keep just one of them open!

**Comment by wvega** [comment] 2019-01-04 12:47
@designsimply should this issue be reopened?

I'm still able to reproduce this issue on the Gutenberg version included with WordPress 5.0.2, but #10042 is now closed as a duplicate of #8882 which no longer mentions the problem that occurs pasting multiline text on a List Block.

**Comment by dionysous** [comment] 2019-06-04 08:24
This issue and the related issue #10042 have both been closed. The problem still exist. It has not been fixed.

**It still behaves like this:**
![GitHub Logo](https://user-images.githubusercontent.com/12687777/44863578-cd4c0180-ac7d-11e8-9eb9-c809580fa9ff.gif)

@codebykat | Can you please re-open this issue? Thank you!

**Comment by codebykat** [comment] 2019-06-04 13:09
I tried to reproduce this since folks are pinging me on it for whatever reason (🤷‍♀) and I'm not getting the empty list blocks before and after, though it does replace the selected list block with a paragraph block. I'm not sure if that's the intended behavior -- it would seemingly be better to have it paste into a list block and assume newlines delimit new list items. I'll defer to @designsimply or someone else on the Gutenberg team as to whether this should be re-opened as an enhancement.

**Comment by designsimply** [comment] 2019-06-06 21:17
Re-opening for another review and feedback from Gutenberg developers.

I tested and confirmed I can see the exact same behavior showing in @dionysous's gif when I tested using a site running WordPress 5.2.1 and no active plugins. For reference, I tested with Firefox 67.0 on macOS 10.14.5. 

This issue doesn't seem like a duplicate of #8882 to me.

@codebykat I suspect you got a mention since you were the author of the #10042 issue.

**Comment by dionysous** [comment] 2019-08-21 11:23
I can confirm @designsimply - I've tested it again on my Mac using Safari _12.1.2_, Chrome _76.0.3_ and Firefox _68.0.2_:

**Screen capture when pasting the text into a list block:**

![list-element-wordpress-gutenberg-bug](https://user-images.githubusercontent.com/12687777/63427785-41932e00-c416-11e9-8dcb-ac52f985a755.gif)

**Comment by ellatrix** [comment] 2019-08-22 11:44
Hi @dionysous! Thanks for the report.

Could you share what the console is logging for you when you paste?

I'm looking for this:

<img width="657" alt="Screenshot 2019-08-07 at 10 53 18" src="https://user-images.githubusercontent.com/4710635/62609234-ac664480-b901-11e9-972a-7383ec88b930.png">

Please copy the text and paste it in between backticks:
````
```
content
```
````

Thank you!

**Comment by skorasaurus** [comment] 2020-12-14 15:37
I'm able to reproduce this on Gutenberg 9.5.2, Firefox 83, Ubuntu. 

Pasting from a plain text editor (sublime text), each line of text is its own line: 

```
one, this is a ditty
two, this is for a bug report
three, is two plus one
```
and in the console:

```
Received HTML:
 <empty string> 
Received plain text:

 one, this is a ditty
two, this is for a bug report
three, is two plus one 
Processed HTML piece:

 <p>one, this is a ditty<br>two, this is for a bug report<br>three, is two plus one</p>
```

**Comment by darwin370** [comment] 2021-02-14 18:47
Also reproducable in WordPress 5.6.1, Twenty Twenty 1.6, no plugins.

Console:
```
Received HTML:

 <empty string> rich-text.min.js:2:44525
```
```
Received plain text:

 one, this is a ditty
two, this is for a bug report
three, is two plus one rich-text.min.js:2:44568
```
```
Processed HTML piece:

 <p>one, this is a ditty<br>two, this is for a bug report<br>three, is two plus one</p> blocks.min.js:3:139223
```

**Closed** 2022-11-30 12:44 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Raw Handling, [Feature] Writing Flow, [Block] List
