### ISSUE TITLE
multiple toolbars in three columns block

### ISSUE THREAD

**Issue by iescuer** [WordPress/gutenberg#5922] opened 2018-04-01 21:44 UTC

**Comment by iescuer** [comment] 2018-04-01 21:53
Hello, I'm doing tests with the block of three columns, I find the problem that the three toolbars overlap, I have prevented doing some task such as inserting links.
If you do the test you will verify that the field where the link has to be inserted is multiplied by three.
Thank you.

![imagen1](https://user-images.githubusercontent.com/6759889/38177861-70d6f082-3607-11e8-906e-baefb59e877a.png)

![imagen2](https://user-images.githubusercontent.com/6759889/38177887-d3294ca8-3607-11e8-85e3-7b059026ad31.png)

**Comment by SuperGeniusZeb** [comment] 2018-04-02 16:19
I think this is a duplicate of #5633.

**Comment by jasmussen** [comment] 2018-04-03 11:20
Thanks for the report. Yes, this is a duplicate, so closing.

**Closed by jasmussen** 2018-04-03 11:20 UTC
