### ISSUE TITLE
Editor crashes with error “TypeError: Cannot read property 'apiVersion' of undefined”

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#32815] opened 2021-06-18 12:38 UTC
## Description
If a block is in the post content which is no longer registered, the editor crashes irretrievably with the error message _TypeError: Cannot read property 'apiVersion' of undefined_.

## Step-by-step reproduction instructions
1. Open the editor of a post containing a block which is no longer registered.
2. Click into the editor.

## Expected behaviour
I should be able to manually delete the block which is no longer registered.

## Actual behaviour
The editor throws the “unexpected error” message and cannot be recovered using any of the available options.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Brave 1.25.73, Chrome 91. Firefox shows a classic editor element instead of the usual "block not supported" message in the editor, which can successfully be removed.

**Comment by gziolo** [comment] 2021-08-27 09:07
I tested it with the latest Gutenberg plugin activated and with WordPress 5.8.0. I couldn't reproduce the issue. I see in the code a few places that @glendaviesnz added in #25940 additional checks whether `blockType` object is defined when accessing `apiVersion`. I searched through the code and noticed a few more places so I plan to open PR with some code quality improvements that might prevent some edge cases.

**Comment by gziolo** [comment] 2021-08-27 09:24
I opened #34346 with a changes that check if the `blockType` is defined before accessing `apiVersion` in 3 more places.

The remaining question is whether we want to do anything about WordPress 5.7. We didn't see similar reports before so it's hard to tell if that isn't related to the theme used. It needs to be tested with WordPress 5.7 and the default theme to verify how serious this issue is.

**Comment by markhowellsmead** [comment] 2021-11-10 11:32
Current status with WordPress 5.8.1 and Plugin version 11.8.3. The editor no longer crashes. The block which was formerly registered and filled with content is visible, but clicking on it removes everything except a simple, unlabelled control, which allows the user to remove the block. This is a good solution, but the interface needs to show some kind of label to indicate to the user what is happening/what has happened.

<img width="778" alt="Screenshot 2021-11-10 at 12 30 29" src="https://user-images.githubusercontent.com/1571592/141105447-94e97d79-a96d-4784-a36d-0e22faef84ed.png">

**Comment by gziolo** [comment] 2021-11-10 11:41
@noisysocks and @Mamaduka, I wanted to flag this issue for your consideration in the context of the upcoming 5.9 release. The last update shared in https://github.com/WordPress/gutenberg/issues/32815#issuecomment-965043554 is the only remaining concern.

**Comment by markhowellsmead** [comment] 2021-11-10 11:47
Additional: this appears to only apply to core blocks. De-registering a custom block where content has already been created shows a suitable message and action control.

<img width="754" alt="Screenshot 2021-11-10 at 12 46 48" src="https://user-images.githubusercontent.com/1571592/141107621-daabceff-ec6e-46cc-bf8e-722774f51b9b.png">

**Comment by StefanXhunga** [comment] 2021-11-10 11:57
I think is Ok, thank you for your assistance!

**Comment by Mamaduka** [comment] 2021-11-10 12:49
Thanks for the ping, @gziolo.

We should display a similar message for core blocks as we do for custom ones - https://github.com/WordPress/gutenberg/issues/32815#issuecomment-965054089. What do you think?

**Comment by glendaviesnz** [comment] 2021-12-15 00:45
On GB trunk on WP 5.8 if I deregister the `core/image` block and then load an image block into the editor it shows the standard unrecognised block error message:

![no-core](https://user-images.githubusercontent.com/3629020/146101911-d8306674-093b-4105-a42b-591fa7e618e6.gif)

@markhowellsmead, how did you deregister the block in order to get the [empty block toolbar](https://github.com/WordPress/gutenberg/issues/32815#issuecomment-965043554)

**Comment by markhowellsmead** [comment] 2021-12-15 08:52
<s>Please refer to https://github.com/WordPress/gutenberg/issues/32815#issuecomment-965054089 in which I confirm that this relates to custom blocks, not core blocks.</s>

`unregisterBlockType('core/image')`

**Comment by markhowellsmead** [comment] 2021-12-15 08:58
Note that you have to add the block, save the post, then amend the code to deregister the block which is already placed in the content, then reload the editor.

**Comment by glendaviesnz** [comment] 2021-12-15 22:03
> Note that you have to add the block, save the post, then amend the code to deregister the block which is already placed in the content, then reload the editor.

I get the same result doing this as when unregistering in the terminal and pasting the block markup into the editor terminal view. Below I add a quote block, then in a plugin add `unregisterBlockType( 'core/quote' )` and reload the editor, and the same message appears as for non-core blocks:

![no-quote](https://user-images.githubusercontent.com/3629020/146271855-d78724d6-4104-45ec-8e12-afd92fb9dd6f.gif)
 
 Are you still seeing this error on latest trunk @markhowellsmead?

**Comment by Mamaduka** [comment] 2022-01-05 05:22
Hi, folks

I'm removing this issue from WP 5.9 project board since RC1 was released last night.

Let's try and land a fix for this in a minor release.

**Comment by ndiego** [comment] 2022-08-02 14:46
I just tested with a few custom blocks and there is now a clear message that the block is disabled. See screenshot below with the Icon Block. I believe this issue can be closed. 

![image](https://user-images.githubusercontent.com/4832319/182403489-9b6190e4-778c-4a32-b722-225b248daef6.png)

**Comment by Mamaduka** [comment] 2022-08-02 14:55
Thanks, @ndiego.

@markhowellsmead, I'm going to close the issue.

We shipped several improvements for missing blocks, but feel free to re-open if you encounter new errors.

**Closed as completed by Mamaduka** 2022-08-02 14:55 UTC
Labels: [Type] Bug, [Feature] Block API

**Comment by markhowellsmead** [comment] 2022-08-02 14:59
Thanks for the feedback. Seems to work and provides the natural error message when a newly-unregistered block is in the block editor.
