### ISSUE TITLE
Update button doesn't become enabled after adding a tag to a published post

### ISSUE THREAD

**Issue by iamthomasbishop** [WordPress/gutenberg#12599] opened 2018-12-04 20:07 UTC
**Describe the bug**

When adding a tag to an already-published post or page, the `Update` button stays disabled.

**To Reproduce**
1. Go to a previously-published post or page
2. Click on the tags input
3. Type a string
4. See `Update` button is inactive

**Expected behavior**

I would expect to be able to tap/click `Update` at any time, unless an auto-save is in progress.

**Screenshots**

![issue-tag-add-update](https://user-images.githubusercontent.com/1200432/49468716-4ef68280-f7cb-11e8-9604-fe55028094f0.gif)

**Desktop (please complete the following information):**

 - OS: MacOS 10.14
 - Browser Safari 12.0 (14606.1.36.1.9), Chrome (70.0.3538.110)

**Comment by swissspidy** [comment] 2018-12-04 22:54
Sounds like a duplicate of https://github.com/WordPress/gutenberg/issues/12450.

What I see in this GIF is expected behavor. Just writing some text doesn‘t add the tag to the post. You actually need to press enter to add the tag. Only then will the button become active.

**Comment by designsimply** [comment] 2018-12-04 23:08
Closing as a duplicate of #12450.

**Closed by designsimply** 2018-12-04 23:08 UTC
Labels: [Component] Post Settings, [Status] Duplicate

**Comment by iamthomasbishop** [comment] 2018-12-10 20:56
> Just writing some text doesn‘t add the tag to the post. You actually need to press enter to add the tag.

To clarify, that's what was happening in the earlier part of the gif – I pressed enter and it didn't convert the string into a tag. However, I'm no longer seeing this, so maybe it was fixed or I was experiencing some sort of bandwidth issue (I was on shoddy broadband at the time). 

Thanks for investigating!
