### ISSUE TITLE
Gutenberg Editor Image Scaling - Issues with Thumbnail Regenration - Missing Images

### ISSUE THREAD

**Issue by shuttermuse** [WordPress/gutenberg#32441] opened 2021-06-03 19:52 UTC
When an image is inserted, either singularly, or with a gallery, Gutenberg is using the URL for the selected scaled version of the image. eg. image-name-500x1024.jpg

If a user changes their image sizes in Settings>Media, and then, as many people so often seem to suggest, regenerates their thumbnails using a plugin, this can cause major issues. Several of these thumbnail regeneration plugins delete (either by default or as an option) the old thumbnails.

With Gutenberg using the scaled image URL in the editor, this means when you go to edit an old post after doing this, all of your images are broken in the editor. When the post is viewed on the front end, there is no problem, but the editor will be filled with a mess of broken image icons. If someone does this by accident, it can be a while before the problem is realized. New posts will work fine, and old posts look ok on front end. The issue is only visible if you happen to go back and edit an old post. If your backup system does not keep backups for a longer period of time than it takes you to discover this issue, it could be a real headache that can only really be solved by deleting and then re-inserting all the images again into your old posts. 

It would be great to have a way to prevent this. Perhaps by having the editor fall back to the URL of the original image when the scaled version is not available? Or by rewriting the scaled image URL to the URL of the closest new scaled version?

**Comment by noisysocks** [comment] 2021-08-31 05:12
Related: https://github.com/WordPress/gutenberg/issues/28914, https://github.com/WordPress/gutenberg/issues/23262

This was a problem in the classic editor, too.

I suppose the image block could detect when loading the image has a 404 error and use the stored image ID to change the stored URL to a new URL.

It wouldn’t totally be automatic, the user would have to press _Update_, but that might be a nice thing to do that’s not updating `post_content` in every single post (maybe not even practical e.g. on a site with lots of posts).

**Comment by Mamaduka** [comment] 2024-11-27 05:28
As noted in the previous comment, the issue isn't specific to the Block Editor, and it's up to plugins like [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) to replace old URLs with new ones.

I'm going to close this issue. General discussion for better handling deleted media continues in #23262.

**Closed as not planned by Mamaduka** 2024-11-27 05:28 UTC
Labels: [Type] Enhancement, [Feature] Media
