### ISSUE TITLE
TypeError: this.obj._listeners is undefined

### ISSUE THREAD

**Issue by ariestop** [WordPress/gutenberg#19382] opened 2020-01-02 06:48 UTC
**Describe the bug**
TypeError: this.obj._listeners is undefined   load-scripts.php:297:3747

When I try to load media in an article, a window with a library opens, click on the Upload file tab, and just a white tab.

Screenshot attached.
![bdb34-clip-84kb](https://user-images.githubusercontent.com/50791509/71654856-6ba61680-2d4d-11ea-81a8-b2813b63c830.png)

I get out of the situation - first I load the copper through /wp-admin/media-new.php

But she doesn’t want to work through articles.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 71 64 bit

**Additional context**
- Version WP [5.3.2]
- PHP 7.3

**Comment by youknowriad** [comment] 2020-01-13 13:32
Hi There!

It is possible that this is coming from a conflict with a plugin.  Did you try disabling your plugins, especially the media related ones.

Thanks.

**Comment by recofka** [comment] 2020-01-22 09:44
I got the same error and indeed was correlated to a media plugin.

For me was this problem and plugin: https://stackoverflow.com/questions/58875627/wordpress-5-3-update-with-enhanced-media-library-free-or-pro-causes-media-libr

**Comment by youknowriad** [comment] 2020-01-22 10:10
Thanks, I'm closing this as it doesn't seem to be Gutenberg's fault.

**Closed by youknowriad** 2020-01-22 10:10 UTC
Labels: [Status] Needs More Info

**Comment by hypergeneric** [comment] 2020-01-31 19:47
i am also experiencing this -- what was the plugin conflict?

**Comment by adamk22** [comment] 2020-03-05 11:13
The plugin causing this issue is Enhanced Media Library, I've opened up an issue ticket here: https://github.com/webbistro/enhanced-media-library/issues/2 

Deactivating the plugin obviously fixes the issue. But I'm hoping they will release a quickfix.

**Comment by ogrosko** [comment] 2020-03-05 12:30
Can confirm same problem with WP 5.3.2 and Enhanced Media Library plugin. After deactivating plugin all works fine

**Comment by kadimi** [comment] 2020-09-08 01:48
This may be caused by mixed content. So make sure your site URL (in the settings or in the wp-config file) starts with `https://`.
