### ISSUE TITLE
The Noto Serif font is no longer available after one on latest updates

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#29389] opened 2021-02-26 20:43 UTC
## Description
After one of latest updates to Gutenberg plugin, the Noto Serif font has become unavailable. Ever since then the entire WordPress block editor is rendered using Times New Roman.

## Step-by-step reproduction instructions
1. Start editing any post or page
2. Observe font of the block editor

## Expected behaviour
As previously, block editor should be rendered using Noto Serif font

## Actual behaviour
Block editor has all blocks rendered with Times New Roman font

## Screenshots or screen recording (optional)
![Clipboard01](https://user-images.githubusercontent.com/2903392/109352551-4f333a80-787b-11eb-8a5f-d6497792f66c.jpg)

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: Version 10.0.2
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by carolinan** [comment] 2021-02-27 07:02
Hi
I am closing this as a duplicate of #29177.  Discussions can continue there.

**Closed by carolinan** 2021-02-27 07:02 UTC
