### ISSUE TITLE
link icon missing in block editor

### ISSUE THREAD

**Issue by genem80** [WordPress/gutenberg#46777] opened 2022-12-23 23:59 UTC
### Description

On 12/19/22 when I highlight text I can add a link or edit an existing link with the link icon.  On 12/21/22 the link icon no longer exists when I highlight text.  Version 14.8.0 was the gutenberg version.  I just checked version 14.8.1 and the link icon is still missing.  

### Step-by-step reproduction instructions

1.Create a paragraph block
2. type some text 
3. Highlight the text
4. The toolbar that pops up does not have the link icon

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-12-24 10:07
I have tested with Guetnberg 14.8.1 and it appears to be working as expected.
Am I missing something?

![link](https://user-images.githubusercontent.com/54422211/209431120-2ec46d59-d593-4185-8b5f-4d54edc65c0b.png)

**Comment by smtping** [comment] 2022-12-24 11:40
I have the same problem too, here is a screenshot 
![image](https://user-images.githubusercontent.com/107704346/209434354-0f8c762d-8c9b-4ed8-b6c2-9224e590fdfa.png)

**Comment by smtping** [comment] 2022-12-24 11:52
Well, **I disabled gutenberg** now and it works like before (@genem80  keep it disabled)
![image](https://user-images.githubusercontent.com/107704346/209434907-3ed64379-c653-4741-944a-9e1f2b346d9b.png)

**Comment by t-hamano** [comment] 2022-12-24 12:01
@smtping 
Thanks for the info.
However, I could not reproduce the problem in my environment even after activating the latest Gutenberg 🤔

**Comment by genem80** [comment] 2022-12-24 14:43
So I deactivated gutenberg as @smtping said and the link icon returns (thanks @smtping).  I'm relatively new to WP,  so what am I losing by not using the gutenberg plugin.  Do a base set of gutenberg block editing features come built in with WP?

**Comment by xoex** [comment] 2022-12-24 15:03
I can confirm I have this problem too, sometimes url button is exist, but most of times it's not.
I got this error in console :

register-format-type.js:86 Format "core/unknown" is already registered to handle bare tag name "a".

P.S: I can't edit other links from previous posts, It shows error formatting.

**Comment by smtping** [comment] 2022-12-24 15:27
@xoex just keep it disabled (keep the classic editor disabled too). I think that with the last update it became embedded (by default) with wordpress

**Comment by t-hamano** [comment] 2022-12-25 02:49
I have enabled Gutenberg version 14.8.1 on a clean install of WordPress 6.1.1 and still cannot reproduce the problem. Is there any improvement by disabling plugins other than Gutenberg and changing to the default theme?

**Comment by xoex** [comment] 2022-12-25 14:32
> @xoex just keep it disabled (keep the classic editor disabled too). I think that with the last update it became embedded (by default) with wordpress

Best was rollback to previous version for me. But problem is really there,

**Comment by gyurmey2** [comment] 2022-12-25 15:51
I confirm that the problem exists.
Gutenberg version: 14.9.20221224

**Comment by t-hamano** [comment] 2022-12-26 02:58
I have not yet found the conditions to reproduce this problem, but since it is considered a major problem, I would assign the label "[Priority] High".

**Comment by t-hamano** [comment] 2022-12-26 03:01
If possible, we would appreciate it if you could provide us with the following information:

- Does this happen even if I disable all plugins except the Gutenberg plugin and change to the default theme?
- Are there any error messages in your browser's console log? For example, like [the one mentioned in this comment](https://github.com/WordPress/gutenberg/issues/46777#issuecomment-1364542606).

**Comment by Gierand** [comment] 2022-12-26 10:27
@t-hamano, I noticed the same problem, but the Rank Math SEO plugin is responsible for it.

**Comment by t-hamano** [comment] 2022-12-26 11:17
@Gierand
Thanks to you I was able to reproduce this problem!

This plugin [remove the core inline link and add its own inline link control](https://github.com/rankmath/seo-by-rank-math/blob/ca14e5ce7c85b44798936cf808017e02bac551f9/assets/admin/src/gutenberg/formats/index.js#L14-L15). It appears that perhaps due to #44086, we can no longer re-register format types ~~with the same settings~~ s that don't have `className`.

This problem can be reproduced in the browser console.

### Without Gutenberg Plugin 14.8.1

The format type is successfully registered.

![success](https://user-images.githubusercontent.com/54422211/209542761-95e3ca94-62ef-4531-af73-159a370f5cd7.png)

### WordPress6.1.1 with Gutenberg Plugin 14.8.1

Format type registration fails.

![fail](https://user-images.githubusercontent.com/54422211/209542948-1b7e0844-92c8-44a8-9c0c-41266209b0b0.png)

**Comment by genem80** [comment] 2022-12-26 14:50
I don't use the "Rank Math SEO" plugin.  I do use the "All in One SEO" plugin  so I don't know if the same issue occurs there.  Some basic questions on plugins:
1.  Are there guidelines that all plugin developers need to follow so as not to step on each other toes
2.  Do you do extensive regression testing on new releases against a variety of theme/plugin combinations?  I think it's not reasonable for users to do this type of QA for you.

**Comment by Thelmachido** [comment] 2022-12-27 09:42
I can't reproduce the issue, however, we have 4 other reports on the Gutenberg Forums with the same issue. 

1. https://wordpress.org/support/topic/cant-add-links-to-posts-link-button-is-missing/
2. https://wordpress.org/support/topic/clear-unknown-formatting-instead-of-a-link-button/


One of the folks noticed that the link option comes back when the Rank Math Seo plugin is deactivated so they reach out to them here: https://wordpress.org/support/topic/conflicts-with-gutenberg-cant-add-links/

**Comment by t-hamano** [comment] 2022-12-27 09:48
@Thelmachido
Thank you for the report.

As I understand it, the problem is that the latest Gutenberg doesn't allow registering format types that don't have a `className`. I expect that the users reported in the forum have probably disabled the core link functionality and are using their own link formats.

I would again mark this issue as a high priority.

**Comment by davilera** [comment] 2022-12-27 19:12
I think my PR https://github.com/WordPress/gutenberg/pull/46798 fixes the issue. Can anybody please confirm?

**Comment by noahtallen** [comment] 2022-12-27 21:33
I verified the fix and merged it. Thanks @davilera! I'll work on creating a patch release for 14.8 now.

**Comment by noahtallen** [comment] 2022-12-27 22:02
This should now be fixed in Gutenberg v14.8.2! Of course, please let us know if there are still issues.

**Closed as completed by noahtallen** 2022-12-27 22:02 UTC
Labels: [Type] Bug, [Priority] High, [Feature] Rich Text, [Type] Regression, [Block] Paragraph, [Feature] Link Editing
