### ISSUE TITLE
Parent editor-style.css is not loaded if a child editor-style.css is present

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#38944] opened 2022-02-21 08:00 UTC
### Description

I'm using the following code in WP 5.9 to load an editor stylesheet in a parent theme:

```
function parent_setup() {
    add_editor_style( array( 'assets/css/editor-style.css' ) );
}
add_action( 'after_setup_theme', 'parent_setup',  );
```

And I'm using the following code to load an editor stylesheet in a child theme to override some styles from the parent:

```
function child_setup() {
    add_editor_style( array( 'assets/css/editor-style.css' ) );
}
add_action( 'after_setup_theme', 'child_setup', 99 );
```

This results in the parent stylesheet not loading at all. If I change the filename of one of the stylesheets in order for them to be different, both stylesheets (parent and child) are loaded:

```
function child_setup() {
    // Changing the filename of the child editor stylesheet
    add_editor_style( array( 'assets/css/child-editor-style.css' ) );
}
add_action( 'after_setup_theme', 'child_setup', 99 );
```

Is this a bug? Is this the expected behavior? I don't see anything related to this mentioned in the Codex. The only thing is the following:

> If a child theme is used, both the current child and parent theme directories are tested and both the files with the same relative path are linked with this single call if they are found.

Any ideas?

### Step-by-step reproduction instructions

1. Install a parent theme in WP 5.9
2. Create a child theme that loads an editor stylesheet with the same filename as its parent.
2. Edit a page and check the source code. The parent theme editor stylesheet is not loaded in the `wp.editPost.initializeEditor` function.

### Environment info

- WP 5.9
- Firefox and Chrome
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by justintadlock** [comment] 2022-02-21 22:32
This is the correct behavior if you just reference a relative URL like `assets/css/editor-style.css`.  WordPress will use the file from the child theme over the parent.

I'm not sure if it's in the Codex or Handbooks, but it is documented in the code: https://developer.wordpress.org/reference/functions/get_editor_stylesheets/

Instead, use the full URL if you want both.  In the parent:

```php
add_editor_style( [
	get_parent_theme_file_uri( 'assets/css/editor-style.css' )
] );
```

In the child:

```php
add_editor_style( [
	get_theme_file_uri( 'assets/css/editor-style.css' )
] );
```

**Comment by mrleemon** [comment] 2022-02-22 08:16
Thanks for the answer, @justintadlock!

**Comment by skorasaurus** [comment] 2022-02-24 19:49
I'm closing this since you have the answer @mrleemon . Please reopen if you feel there's additional actions to take.

**Closed as completed by skorasaurus** 2022-02-24 19:49 UTC
Labels: [Type] Help Request

**Comment by metropoliscreative** [comment] 2022-03-08 20:34
@justintadlock Can you provide some clarity on this? The `get_editor_stylesheets()` function seems to search both the child and parent theme directories for the file path given in `add_editor_style()`, and I confirmed that `get_editor_stylesheets()` returns two separate file URLs when the filenames/paths are the same, but only the child theme's stylesheet is loaded in the (Gutenberg) editor. 

When I tried to use either the `get_parent_theme_file_uri()` or `get_theme_file_uri()` functions I ran into "Error while traversing the CSS" errors in the editor, even with 1 line of basic CSS in the stylesheets, so there seem to be other issues there, at least with the Gutenberg editor.

I was able to load both stylesheets by renaming one of the files, **however the child theme's stylesheet is loaded first**. In the parent theme I have:

`add_editor_style( 'assets/css/editor-style.css' );`

and in the child theme: 

`add_editor_style( 'assets/css/editor-style-child.css' );`

**Update:** Order of stylesheets fixed by adding priority 99 to the `after_setup_theme` hook in the child theme as shown in the original post.

**Comment by guillaumer** [comment] 2022-04-12 07:55
Experiencing the same issue on a Linux server (nothing on my Windows machine). This might also be related to https://github.com/WordPress/gutenberg/issues/11981.

Experiencing same otherwise, get_theme_file_uri() and get_parent_theme_file_uri() must be avoided, with the direct path to be specified (see above), and with a different editor file name between the parent and child themes.

**Comment by joloco** [comment] 2022-05-19 13:52
If a child theme file over-rides a file of the same name that's in the parent theme (which is the desired behaviour, as explained clearly above by @justintadlock) then this line in the documentation is confusing at best:

> If a child theme is used, both the current child and parent theme directories are tested and both the files with the same relative path are linked with this single call if they are found.

Shouldn't this be changed to explain that the child theme file will be the only one loaded in such a case? As it stands, it sounds like both files will be loaded.

**Comment by wmalexander** [comment] 2025-05-09 16:33
This should be reopened - the behavior and the documentation are at odds with each other. I hit this problem, read the documentation, and the documentation all but verified that my code was correct (set up as described in the first post in this issue). I had to insert debug into core block-editor.php in order to verify that my code did not work as the documentation suggested that it should. I'll be renaming the stylesheets and adjusting the child theme's priority as suggested here - but in doing that I'll be following documentation that I found here, in this issue, rather than in the documentation itself. Furthermore, the documentation is outdated, and refers to "Adds callback for custom TinyMCE editor stylesheets." That should be changed to clarify that this method also works for Gutenberg.
