### ISSUE TITLE
WordPress logo is not clean in the "Go back" button on fullscreen mode

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#20787] opened 2020-03-11 12:06 UTC
**Describe the bug**
WordPress logo looks "pixelized" in the "Go back" button on fullscreen mode.

**To reproduce**
It occurs on Chrome (last version) / Mac OS.
The screenshot bellow shows the logo rendering on Make/Core P2 blog.

**Screenshots**
![Capture d’écran 2020-03-11 à 12 57 05](https://user-images.githubusercontent.com/1590998/76415163-fda74c80-6398-11ea-9266-798084e47b9d.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser : Chrome
 - Version : last

**Comment by talldan** [comment] 2020-03-16 07:08
@audrasjb I couldn't see any issues also in Chrome, Mac OS X. This is what I'm seeing:
<img width="104" alt="Screenshot 2020-03-16 at 3 06 21 pm" src="https://user-images.githubusercontent.com/677833/76731235-e5b83a00-6797-11ea-84e5-25d06472eb77.png">

**Comment by jorgefilipecosta** [comment] 2020-03-16 17:48
I'm also not being able to reproduce the issue. I also tried on make blog, @audrasjb could you verify if the issue is still happening?

**Comment by audrasjb** [comment] 2020-03-16 17:53
Yeah I still have the issue on Make/Core.
Chrome 80.0.3987.132 / Mac OS 10.14.4

![Capture d’écran 2020-03-16 à 18 52 26](https://user-images.githubusercontent.com/1590998/76786411-7a7e6000-67b7-11ea-9b86-182bd5b2c16d.png)

**Comment by talldan** [comment] 2020-03-30 00:41
Fixed by #21217

**Closed by talldan** 2020-03-30 00:41 UTC
Labels: Needs Testing
