### ISSUE TITLE
Widgets area is gone after update of the Gutenberg 11.5.1

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#35051] opened 2021-09-22 14:56 UTC
### Description

After I updated Gutenberg 11.5.1 ,  the widgets area
![Screen Shot 2021-09-22 at 7 14 53 AM](https://user-images.githubusercontent.com/24829573/134366228-4bacac97-8698-4182-a52a-e71ccafa6ea9.png)
 is gone from WordPress dashboard.

Also I don't see customize anymore
![Screen Shot 2021-09-22 at 7 15 21 AM](https://user-images.githubusercontent.com/24829573/134366487-03b95fb6-2ccc-419f-964b-a44c920daf75.png)

### Step-by-step reproduction instructions

Go to the dashboard
click on the appearance
there is option to go widget area.
Also, there is not option to go customize area. Please see the screenshots above.

### Environment info

WordPress Version 5.8.1, Gutenberg version 11.5.1 and TT1 theme
Browser: Chrome version 93.0.4577
MAC OS Gig Sur Version 11.6 , MAC Book Pro

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by lwangdu** [comment] 2021-09-22 15:12
I have tested three different themes "TT1, Genesis block theme, and Hansen. I think this something to do with TT1 and Hansen Block Theme. The widgets works with Genesis block theme.

**Comment by chad1008** [comment] 2021-09-23 13:06
Hi @lwangdu!

When you say TT1, do you mean [Twenty Twenty One](https://wordpress.org/themes/twentytwentyone/), or [Twenty Twenty One Blocks](https://wordpress.org/themes/tt1-blocks/)?

If it's the latter, I suspect that is the cause. TT1 Blocks, Hansen, and Genesis Blocks are all Experimental Block Based Themes. This means they'll activate the current version of the Full Site Editing, which takes the place of current implementations like Customizer and the Widgets panel.

You'll notice in your screenshot that you now have a Site Editor (Beta) option, and that Appearance allows you to modify template parts. That's all part of Full Site Editing, which is still a work in progress :)

Can you try switching to a non block-based theme like [Twenty Twenty One](https://wordpress.org/themes/twentytwentyone/)? That should bring back the widgets interface and Customizer as you're used to seeing them.

**Comment by lwangdu** [comment] 2021-09-23 13:50
It worked with Twenty Twenty one theme. I can see both customizer and widgets. Thanks for your help.

**Comment by annezazu** [comment] 2021-09-29 23:17
Going to go ahead and close this out :)

**Closed as completed by annezazu** 2021-09-29 23:17 UTC
Labels: [Status] Not Applicable, [Feature] Widgets Screen
