### ISSUE TITLE
Font Size issue when using predefined sizes

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#8689] opened 2018-08-07 20:47 UTC
**Describe the bug**
If I pick "XL" size and see in the front-end, I see no change in size. I think that's the expected behavior to leave that to themes.

However, when I use 48px as custom size, it doesn't work as it changed the font size to "XL" and I don't get 48px in front-end. It works just fine with 47 and 49. Same happens with all other sizes.

**To Reproduce**
1. Add a paragraph block.
2. Set font size to 36 or 48.
3. See in the front-end.

**Comment by jorgefilipecosta** [comment] 2018-08-23 08:35
Hi @HardeepAsrani thank you for reporting this issue. I'm not being able to reproduce it. Could you please specify what theme you are using? When setting the font size to 48 could you check in the code editor if the paragraph contains the class "has-larger-font-size"? Thank you in advance for the help!

**Comment by jorgefilipecosta** [comment] 2018-09-17 19:11
Hi, @HardeepAsrani now I understand the situation you are describing. This happens because even if a specific font size is chosen if there is a named font size that represents that value, a class is used instead of an inline style. The same happens in colors even if a color is chosen by value on the color picker if a named color exists a class is used. This decision was made with the objective of minimizing the use of inline styles.
I think If the theme you are using sets the font size for the class has-large-font-size things will work as expected.

**Comment by HardeepAsrani** [comment] 2018-09-19 19:12
I'll leave out the developer part, but as a user this doesn't make sense. I'm using a theme that we made (at themeisle) for this which has no Gutenberg support so far. So it's like this by default.

That class should have a default font-size if the theme isn't setting one.

**Comment by chrisvanpatten** [comment] 2018-11-09 14:06
I've posted #11671 now, which discusses how we map numeric sizes to named sizes. I agree that we shouldn't. #11413 reported the same issue.

I'm going to close this to consolidate the discussion, and I would love your thoughts on that ticket, @HardeepAsrani. I agree we can make this better!

**Closed by chrisvanpatten** 2018-11-09 14:06 UTC
Labels: Blocks, Needs Testing, [Type] Bug
