### ISSUE TITLE
E2E test plugin blocks not loading in the Customize Widgets editor.

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#31491] opened 2021-05-05 08:31 UTC
# Description
https://github.com/WordPress/gutenberg/pull/31406 seems to fix loading blocks from plugins in the customize widget editor.

But for some reason plugin blocks that are used for e2e tests aren't loading (https://github.com/WordPress/gutenberg/pull/31406#issuecomment-831093152).

This might indicate a similar problem will occur with some plugins.

When observing the block registration, I can see that several different instances of the `core/blocks` store are being registered (possibly due to https://github.com/WordPress/gutenberg/issues/8981).

In the customizer editor, the plugin block is being registered after core blocks, while for the standalone editor the plugin block is being registered before.

## Step-by-step reproduction instructions
1. In a local wp-env environment open `localhost:9999/wp-admin`
2. Enable the Customize Widgets experiment
3. Enable a test plugin that adds a block, like 'Gutenberg Test Custom Grouping Block'
4. Open Appearance > Customize > Widgets
5. Open the block library using the '+' button

## Expected behaviour
The 'Alternative Group Block' is available

## Actual behaviour
The 'Alternative Group Block' isn't available

**Comment by noisysocks** [comment] 2022-02-21 06:52
I'm having trouble testing this. For some reason the widgets block editor doesn't load at all for me in the Customizer when browsing to localhost:8889. (It's fine in localhost:8888.)

**Comment by ndiego** [comment] 2022-08-02 14:42
@talldan and @noisysocks this issue came up in our weekly Editor Bug Scrub and just wanted to check in and see if this was still an issue?

**Comment by ndiego** [comment] 2022-08-09 14:14
Hi all, this issue was reviewed again during this week's Editor Bug Scrub. A few testers were not able to reproduce, and given that this issue has not seen any activity in quite a long time, we have decided to close it. If anyone is able to reproduce, feel free to reopen.

**Closed as completed by ndiego** 2022-08-09 14:14 UTC
Labels: [Type] Bug, Needs Testing, [Feature] Widgets Customizer
