### ISSUE TITLE
Error 400 when trying to save a post with an empty Classic block as only content

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6979] opened 2018-05-28 12:54 UTC
Gutenberg allows to save posts with empty blocks, for example:
- create a new post
- leave the title empty
- add a paragraph and leave it empty
- save as draft
- saving is successful
- add an Image block but don't add an image
- add a List block and leave it empty
- save as draft
- saving is successful

Instead:
- create a new post
- leave the title empty
- add a Classic block and leave it empty
- click on Save draft
- you will get an "Updating failed" warning (see screenshot below)

Actually, for a brief moment you will see the Save draft button changed in "Saved" together with the "Updating failed" warning. A bit confusing:

![screen shot 2018-05-28 at 14 40 11](https://user-images.githubusercontent.com/1682452/40615316-8e76145a-6286-11e8-95f6-98a54a8e627a.png)

After that, "Saved"  turns back into "Save Draft":

![screen shot 2018-05-28 at 14 39 49](https://user-images.githubusercontent.com/1682452/40615342-a3f72b48-6286-11e8-9fc7-820582740ec4.png)

The API response is:
`{"code":"empty_content","message":"Content, title, and excerpt are empty.","data":{"status":400}}`

Instead, saving a post with only an empty paragraph returns the whole post data, with an empty paragraphs as content: `"<p><\/p>\n"`

**Comment by danielbachhuber** [comment] 2018-06-04 14:22
Duplicate of #6556

**Closed by danielbachhuber** 2018-06-04 14:22 UTC
