### ISSUE TITLE
List bullet contents mostly deleted after ENTER + ENTER + BACKSPACE + ENTER

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11165] opened 2018-10-27 23:09 UTC
**Describe the bug**
When escaping a list through multiple returns ([which doesn't always work](https://github.com/WordPress/gutenberg/issues/11163)), back spacing into a list, and hitting return again, I lose a majority of the data in my list.

I observed this bug a few other times in other conditions but this series of keystrokes is the only one I could consistently reproduce. In working on a blog post, I completely lost a bullet's contents twice and trying to UNDO/REDO to get it back did not work.

**To Reproduce**
1. Make a list
2. Hit `RETURN` twice to escape the list ([doesn't always work](https://github.com/WordPress/gutenberg/issues/11163))
3. Hit `BACKSPACE` to return cursor to end of last bullet
4. Hit `RETURN`
5. All but the first few characters in the last bullet are lost.

**Expected behavior**
Gutenberg doesn't delete what I've written :(

**Screenshots**

To be extra sure this was really happening, I did it twice in two separate posts.

![list-data-loss](https://user-images.githubusercontent.com/1238696/47610142-976b9500-da02-11e8-9fb3-1befeb340230.gif)

![list-data-loss-2](https://user-images.githubusercontent.com/1238696/47610143-9a668580-da02-11e8-9447-7b330511888e.gif)

**Desktop (please complete the following information):**
 - Win 10
 - Firefox 63
 - 5.0-beta1-43823

**Comment by dbullock** [comment] 2018-10-28 19:49
I was able to recreate this with Gutenberg Version 4.1.1 .. WP beta1-43832 .. in Chrome

**Comment by Smith-erin** [comment] 2018-10-28 19:53
I was partially able to recreate this issue. It was not consistent with this set of steps. However, while going in and out of the list block, I had similar results. I was unable to reproduce those errors again, though.

**Comment by mrwweb** [comment] 2018-10-29 14:48
> I was partially able to recreate this issue. It was not consistent with this set of steps.

The ENTER + ENTER + BACKSPACE + ENTER seems to be the most consistent way I can trigger it, but I've _definitely_ seen it happen in other circumstances as well.

**Comment by youknowriad** [comment] 2018-10-30 10:19
Should be fixed by #10799

**Closed by youknowriad** 2018-10-30 10:19 UTC
Labels: [Block] List, [Type] Bug
