### ISSUE TITLE
When clicking on formatted text, Gutenberg replaces the background color with a grey color

### ISSUE THREAD

**Issue by pauljacobson** [WordPress/gutenberg#8113] opened 2018-07-22 08:08 UTC
**Describe the bug**

When clicking into a section of formatted text, Gutenberg highlights all of that formatted text with a grey background, ignoring the current background color of the block the text is in.

Gutenberg **doesn't** select that text, however. It just highlights the formatted text.

**To Reproduce**

1. We created a block of dummy text, added a random background color to the text.
2. We then formatted some text as **bold**, _italicized_ some text, and used <s>strikeout</s> for some text.
3. We then clicked somewhere inside the formatted sections of the text.
4. The whole section of formatted text was highlighted in a grey color, without actually selecting the text.

**Expected behavior**

Clicking inside formatted text need not add any further text annotation.

**Screenshots**

![](http://cld.wthms.co/BMLMTY+)

**Desktop:**

 - OS: macOS 10.13.6
 - Browser: Firefox 62.0b10 (Developer Edition) and Chrome 67.0.3396.99

**Additional context**

- This behavior is apparent in Gutenberg v3.3.0 and WordPress.com.
- This testing was done by myself and @thehenrybyrd

**Comment by chrisvanpatten** [comment] 2018-07-22 12:54
This is intentional behaviour, as part of the [inline boundaries feature](https://github.com/WordPress/gutenberg/blob/6d0fc3be1d052c5427bd6a4762c0bed3d667faba/editor/components/rich-text/tinymce.js#L164). This exists in the Classic Editor for links, but it is new to other types of formatting.

Would you say the problem is that it happens at all, or just that the formatting in a selected block context isn't necessary? I suspect it'd be a `wontfix` if the former, but the latter (not showing the inline boundaries while the whole block is elected) seems like a fair point.

**Comment by chrisvanpatten** [comment] 2018-07-22 12:55
Further context is available over in #459 and #2947.

**Comment by pauljacobson** [comment] 2018-07-23 09:06
@chrisvanpatten Thanks for your feedback. It's just not clear what the value of that is to a user? Adding this effect either looks like the text is being selected (which it isn't), or that there is some sort of glitch and the background is breaking up in some way (I can see users reporting this one - it's confusing).

**Comment by youknowriad** [comment] 2019-02-08 14:04
This behavior have been in place for some time (even in the classic editor) and we didn't a lot negative feedback for it. Let's close and reconsider if there's more evidence that it's wrong.

**Closed by youknowriad** 2019-02-08 14:04 UTC
Labels: Input Interaction, [Type] Question
