### ISSUE TITLE
Image Block: Media URL is not updated when the image is replaced with another one

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#18231] opened 2019-11-01 09:53 UTC
**Describe the bug**
When an image has a target link to the Media file, this URL should be updated when the image is replaced with another one. Instead, the link remains the same and it's still targeting the previous media URL.

**To reproduce**
1. Use Image block to insert an image
2. Add a link to "Media file"
3. Click on the "Edit image" button and replace the image with another one
4. The link to "Media file" remains the same as before, so the image is linking to the previous image.

**Expected behavior**
Media URL link should be automatically updated when the image is replaced by another one.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: last

**Additional context**
- Reproduced on WordPress 5.3 RC 3.

**Comment by jorgefilipecosta** [comment] 2019-11-25 19:23
Hi @audrasjb,
Thank you for reporting this issue.
I am not being able to reproduce this issue on Gutenberg master.
I verified the code and checked that we have a condition to avoid this bug, that seems to be working well.
During this check I verified, we did not have logic to update the "Attachment Page" link so we had exactly this issue happening when the user selects "Attachment Page". I submitted a fix at https://github.com/WordPress/gutenberg/pull/18731.
I'm closing this issue as it refers to the "Media Link" option and I'm not able to reproduce the problem. If you are still able to reproduce this issue on Gutenberg master please leave a comment so we can look deeper into the issue.

**Closed by jorgefilipecosta** 2019-11-25 19:23 UTC
Labels: [Block] Image, [Feature] Media, [Type] Bug
