### ISSUE TITLE
Cannot drag and scroll

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#18498] opened 2019-11-14 09:22 UTC
**Describe the bug**

It's not possible to drag and drop block to a point outside the viewport.
I've run into this several times before, and I'm surprised I hadn't reported it yet.

![drag-scroll](https://user-images.githubusercontent.com/4710635/68843398-55be9280-06c8-11ea-8351-1412f0b57643.gif)

Support thread: https://wordpress.org/support/topic/drag-scroll-impossible-not-working/

**To reproduce**
Drag a block up or down the page. The page doesn't scroll.

**Comment by ntsekouras** [comment] 2020-06-17 14:35
Hey @ellatrix. I just tried to reproduce and work on it, but seems to work for me (Chrome + Firefox).

**Comment by ellatrix** [comment] 2020-06-17 17:33
I still cannot get it to scroll, not by moving it to the edge, not with the mouse wheel/trackpad gesture.

**Comment by talldan** [comment] 2020-06-18 05:35
Looks like https://github.com/WordPress/gutenberg/pull/23082 is a fix for this? I've linked them and will give the PR a review.

**Closed** 2020-06-25 03:42 UTC
Labels: [Feature] Drag and Drop, [Feature] Writing Flow
