### ISSUE TITLE
Preview Button - Remove Extra Click / Add Nipple-click Dropdown Option

### ISSUE THREAD

**Issue by grand-lotus-iroh** [WordPress/gutenberg#31462] opened 2021-05-04 13:13 UTC
When creating a page, or post, there are TOO MANY clicks required to preview a page. Why would anyone want to click "Preview" just to click "Preview in new tab" again? Two clicks to preview is non-sense. Make it so there is a nipple dropdown arrow that you can popup that menu BUT make it so when you click the actual preview button, you don't have to click a 2nd time to preview.

Think about it... you are developing site, and click preview button MANY MANY times. You are just creating non-sense cycle / flow.

**Comment by stokesman** [comment] 2021-05-04 17:41
I agree with your critique. Just in case it might help, I'll mention I tend to keep the preview tab open and use keyboard shortcuts to save the edits, switch back to the preview tab, and refresh. Now that I'm thinking about this, it would seem ideal that a keyboard shortcut could be made for preview in a new tab (along with improved UI for clicking).

Closing as a duplicate of #24584.

**Closed as completed by stokesman** 2021-05-04 17:41 UTC
Labels: [Status] Duplicate

**Comment by grand-lotus-iroh** [comment] 2021-05-05 17:10
I too, used to click the preview button and just tab over and click CTRL + F5 but I've noticed that does not work, and also, sometimes, when I add "reuseable blocks" those don't show in preview mode. It have to publish or save draft and than look to see the updates.
