### ISSUE TITLE
Use move arrows to move widgets/blocks between widget areas

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#26020] opened 2020-10-12 09:53 UTC
**Is your feature request related to a problem? Please describe.**
It is not easy to move a widget between one widget area and another.

**Describe the solution you'd like**

It would be helpful to be able to move a widget between widget areas using the up and down arrow icons.

Here is an example of moving the Heading block from the top of Footer 1 and to the bottom of Footer 1. Notice the down arrow is greyed out when reaching the bottom of the Footer 1 widget area.

![Move-widget](https://user-images.githubusercontent.com/5323259/95732638-4dc4f500-0c81-11eb-8fcc-47b437aa3aa3.gif)

Being able to continue moving the widget over to the next widget area would make moving widgets a lot easier.

**Describe alternatives you've considered**
Drag & drop. There is also a "Move to" option in the 3 dot drop down menu.

**Up/Down arrows - move blocks independent of relation to placement inside/outside a container**
Associated issue: https://github.com/WordPress/gutenberg/issues/24328

**Comment by draganescu** [comment] 2020-10-14 07:46
Closing as somewhat duplicate of #24328

**Closed** 2020-10-14 07:46 UTC
Labels: [Feature] Widgets Screen, [Type] Enhancement
