### ISSUE TITLE
MS Edge: Attempting to add content causes a client crash and page refresh.

### ISSUE THREAD

**Issue by kwight** [WordPress/gutenberg#17723] opened 2019-10-02 17:58 UTC
**Describe the bug**
Testing 6.6 on a VirtualBox Edge install, I'm unable to add content to a new post; the editor freezes, then I see thousands of `unable to get property of 'nativeEvent' on undefined or null value` console errors before the page refreshes.

While VirtualBox isn't great for reproducing bugs, I can see that the issue doesn't happen in older plugin versions.

**To reproduce**
1. Load the Edge browser.
2. Start a new block editor post.
3. Attempt to add a new paragraph of content.
4. Notice the freeze, errors, and page refresh.

**Expected behavior**
Text entry should happen normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 in VirtualBox on macOS
 - Browser MS Edge
 - Version 42.17134.1.0

**Comment by kwight** [comment] 2019-10-02 18:02
Originally discovered attempting to verify #17707 .

**Comment by ellatrix** [comment] 2019-10-02 18:04
Could you share where exactly the error is coming from?

**Comment by kwight** [comment] 2019-10-02 19:21
I'm seeing the error in the console when trying to add a paragraph of content.

I just tried this again but in Browserstack, with the newest Edge (and devtools closed). I still see a big delay when attempting to add a paragraph, but no crash (@gwwar had a similar experience). I'm fine closing this; I'll chalk it up to an old VM version of Edge and emulation. If users with real hardware see issues, I'm sure we'll hear about it 🙃 Thanks for rubber ducking @ellatrix !

**Comment by youknowriad** [comment] 2019-10-03 09:48
I was able to reproduce this in a VM with IE11 but only when the dev tools are open.
The issue is triggered by this line 

https://github.com/WordPress/gutenberg/blob/master/packages/rich-text/src/component/index.js#L339

**Comment by ellatrix** [comment] 2019-12-10 20:59
@youknowriad Could you re-link the line that is triggering it. The file seems to have changed meanwhile. You can right click the line and "Copy Permalink" so it's attached to a certain commit.

**Comment by youknowriad** [comment] 2019-12-11 07:26
Tbh, I don't know exactly anymore. maybe this one https://github.com/WordPress/gutenberg/blob/ae1eccdfac8c23159e7dfbbe7b360f766ab7ea17/packages/rich-text/src/component/index.js#L410

**Comment by youknowriad** [comment] 2021-04-23 14:26
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.

**Closed by youknowriad** 2021-04-23 14:26 UTC
Labels: Browser Issues, [Feature] Rich Text, [Type] Bug
