### ISSUE TITLE
Navigation Block: Buttons Block can't be inserted from the "Add Link" modal

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#54877] opened 2023-09-27 15:02 UTC
## What problem does this address?
I'm not sure if this is intentional, but when testing the new support for the Buttons Block in Navigation, I noticed that there is no way of adding a Button by clicking on the [+] button that shows up inline in the Navigation Block and pulls up the option to search for links or add Search/Social/Logo/Page List.

Clicking on an empty "Custom Link" menu item also doesn't allow you to select a button block. The only way of adding a Button seems to be from the menu editing tag in the Block Inspector sidebar:

https://github.com/WordPress/gutenberg/assets/14153300/54031f74-4497-4a42-a9eb-9521d6804e69

## What is your proposed solution?
Buttons should be treated like other blocks allowed in the Navigation Block, meaning they should show up in the Transform options, and should show up when searching for button/s.

**Comment by jordesign** [comment] 2023-09-27 21:27
Confirmed in testing with the most recent beta - there's no option to insert a button from the inline inserter

**Comment by bph** [comment] 2023-09-28 12:07
It's correct that the button block isn't available via the Inserter! 

The button can be successfully added to the Navigation menu via the Sidebar in the Site Editor. 

https://github.com/WordPress/gutenberg/assets/39980/3e4f7422-dda1-4c43-9c87-5d2537a3b989

**Comment by bph** [comment] 2023-09-28 12:10
After I added a button to the navigation, the button would also be available in the inserter in the canvas. Definitely a bug. :-) Thanks for reporting. @liviopv

**Comment by annezazu** [comment] 2023-09-28 15:32
Noting that the other option is through transforming a block:

<img width="504" alt="Screenshot 2023-09-28 at 9 32 24 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/02b2656f-0ed4-44ab-bb1a-ed05dd4c0959">

**Comment by annezazu** [comment] 2023-10-05 23:00
@torounit or @scruffian since you two worked on this, might one of you be able to dig in to get this into the 6.4 release cycle? Right now, the option is quite hidden and hard to get to making for a subpar user experience.

**Comment by Sidsector9** [comment] 2023-10-06 13:26
Hello everyone 👋 

I have raised a PR for this issue and would love your thoughts on the same - PR #55126

**Comment by torounit** [comment] 2023-10-07 06:39
Fixed this issue in https://github.com/WordPress/gutenberg/pull/55144

Add Buttons to Transfrom as well as Search/Social/Logo/Page List.

**Comment by Sidsector9** [comment] 2023-10-09 07:12
@torounit Just saw your PR. Since the featured block has limited options, for example it doesn't have the Submenu block, in this case what is the general approach to add the Submenu after a custom link? Is transforming a custom link to Submenu block the only option the user has?

**Comment by torounit** [comment] 2023-10-09 13:15
@Sidsector9 
Right now, I think the only way to insert a submenu is to insert a custom link and then transform it.
Also, spacer and the like are allowed to be inserted into Navigation block, but there is usually no way to insert them.

And I think it is a confusing behavior to add elements in different ways depending on the type of InnerBlock block.

I think these problems should be solved by other issue or pull request.

**Comment by getdave** [comment] 2023-10-13 12:50
For context, the reason for this conditional behaviour is to try and keep the block simple for the most common use case which us just inserting a link to a Page.

Therefore, if your Navigation contains only "simple" blocks (links and some other whitelisted blocks) then when you click the + inserter it will auto-insert a link into the Navigation. Whereas if you Navigation already contains more complex blocks then when you click `+` you are required to first choose the type of block.

As @richtabor mentioned, we are looking at improving this flow by changing the behaviour of the `<LinkControl>` component.

**Comment by annezazu** [comment] 2024-01-23 22:46
Noting that this should ease the experience greatly and close this issue out: https://github.com/WordPress/gutenberg/pull/57756

**Comment by getdave** [comment] 2024-01-24 09:36
> Noting that this should ease the experience greatly and close this issue out: #57756

We need more eyes on this change though.

**Comment by annezazu** [comment] 2024-09-02 18:33
Closing this out as https://github.com/WordPress/gutenberg/pull/57756 was implemented and the following video reflects the current experience in WordPress 6.6.1 with GB 19.1:


https://github.com/user-attachments/assets/2572bd0e-5745-4544-883b-a1d61652dd5e

**Closed as completed by annezazu** 2024-09-02 18:33 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Navigation
