### ISSUE TITLE
FSE templates not rendering shortcodes used in blocks

### ISSUE THREAD

**Issue by Stiofan** [WordPress/gutenberg#35258] opened 2021-09-30 12:49 UTC
### Description

If a block output contains a shortcode it will be renedered when used in a page/post or block widget, however if used on a template such as single-post.html then the shortcode will not be rendered.  The backend editor WILL render it, but the frontend will not.

### Step-by-step reproduction instructions

I have a framework that serverside renders blocks as they are shortcodes. It can be installed as a plugin to test.
https://github.com/AyeCode/wp-super-duper

There is a "Hello World" example, add the example to a normal post and view the source code, you will see it's contens as a shortcode.  If used on a single-post.html template it will render in the backend but not on the front end.  I guess as it does not get put through "the_content" filter.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/10433311/135457481-0640693d-e438-4cda-8def-d28f4adabf21.mp4

### Environment info

WP 5.8.1
GB  11.6.0
Theme: armando (theme experiments)
Chrome
Ubuntu 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ianlin** [comment] 2021-12-09 06:04
There is a similar findings that was reported in WordPress/twentytwentytwo/issues/280, but turns out it's more like the behaviour described in this issue.

**Comment by Stiofan** [comment] 2022-10-12 13:31
This issue is not actually solved by the above pull request.  Can we re-open this?

**Comment by carolinan** [comment] 2022-10-13 05:12
Please include the full details about what, more precisely, is not working, and how to reproduce it without third party plugins.
If it can not be reproduced without third party plugins, it can not be excluded that the problem is within that plugin.

**Comment by bph** [comment] 2022-11-09 18:07
@Stiofan I tried to install [the plugin ](https://github.com/AyeCode/wp-super-duper)from zip, and it ran into a 500 error. 
@ agree with @carolinan, we need some updated steps for reproducing your issue without using a 3rd party plugin.

**Comment by justintadlock** [comment] 2022-11-09 22:15
**Edit no. 4:** (sorry for the edits---been a while since I've tested shortcodes).

I have tested this with a custom shortcode and haven't been able to reproduce.  I'd like to see more detailed steps too.  Here's what I tried:

1) Create a test shortcode in my theme's `functions.php`:

```php
add_action( 'init', function() {
	add_shortcode( 'test', function() {
		return '<p>Hello, world</p>';
	} );
} );
```

2) Used it within the Shortcode block in a theme template:

```html
<!-- wp:shortcode -->
[test]
<!-- /wp:shortcode -->
```

3) View output in the editor and front end:

```html
<p>Hello, world</p>
```

**Comment by bph** [comment] 2022-12-08 10:52
With information still missing on how the PR #37545 is not working, I close this again.

**Closed as completed by bph** 2022-12-08 10:52 UTC
Labels: [Status] Needs More Info, Needs Testing, [Feature] Shortcodes, [Feature] Site Editor, [Feature] Template Editing Mode

**Comment by hastinbe** [comment] 2023-05-17 20:50
I'm having this exact same issue on 6.2.1 which according to this should've been fixed long ago. All shortcodes in our templates are being output as plaintext, but in the post content is working fine.

**Comment by carlomanf** [comment] 2023-05-17 22:39
@hastinbe This is a very old ticket and has nothing to do with the recent 6.2.1 change. Please voice your concerns at https://core.trac.wordpress.org/ticket/58333 and leave this ticket archived.

**Comment by hastinbe** [comment] 2023-05-17 22:48
It does however have the same symptom, which is how I ended up here for those of us who searched the issues. But thanks for the link, I did find it earlier after I made that comment and I'm sure it will help others who end up here like I did
