### ISSUE TITLE
Button (Layout Element) shows incorrect title on front-end 

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#7311] opened 2018-06-14 21:27 UTC
**Describe the bug**
A button (under Layout Elements) does not show the entered button text on the front-end of the site. The URL functions correctly. In my testing, the text "Click me" is displayed as "T" on the front-end. Another local tester saw "d" on the front-end instead of "WordPress.com".

We think the displayed letter may be related to the first entered letter in the post, but have not been able to reproduce this. There is also inconsistency between buttons, as some buttons in the same post will show this behavior and others will function normally.

**To Reproduce**
1. Create a new post
2. Add a Button element from the Layout Elements section
3. Add a URL and button text
4. Publish or preview the post and note the button text will differ from what was entered in Gutenberg

**Expected behavior**
The front-end button will display the exact text entered in the Editor

**Screenshots**
Gutenberg:

<img width="261" alt="screen shot 2018-06-14 at 5 16 07 pm" src="https://user-images.githubusercontent.com/1900444/41439322-4dfd3406-6ff8-11e8-9125-071e13abe6c1.png">

Front-end:

<img width="184" alt="screen shot 2018-06-14 at 5 17 30 pm" src="https://user-images.githubusercontent.com/1900444/41439173-c12c297e-6ff7-11e8-8308-640b78c249b3.png">

**Desktop (please complete the following information):**
 - OS: OS X 10
 - Browser Chrome
 - Version 66

**Additional context**
Gutenberg 3.0.1

**Comment by danielbachhuber** [comment] 2018-06-14 23:38
Hi @kriskarkoski,

Thanks for the report. I can't reproduce this issue in my local WP install:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/36432/41443333-05a5e29a-6ff1-11e8-8c8e-741c361a1df9.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/36432/41443340-0d5ae44a-6ff1-11e8-85cd-9ce53f3a546e.png">

Could this be specific to WordPress.com, perhaps? Can you share the full HTML contents of a post that reproduces the issue?

**Comment by krilor** [comment] 2018-06-17 16:40
I just experienced this in my local Wordpress running WP 4.9.6 and GB 3.0.1 on latest Chrome.

I've tried a bunch of stuff to reproduce it, and I think the key is to empty the button, unfocus and then refocus and enter some new text.

1. Create a new page
2. Add a button element
3. Write some button text, and remove it, leaving an empty button
4. Shift focus a way from the button (click somewhere else)
5. _Notice that there is no placeholder text in the button._
6. Click the button again to enter some new text
7. Save/preview the page

Frontend will have a button with one letter (seems random). Editor still has the new text.

Reloading the editor returns the one-letter button.

Editor with text

![image](https://user-images.githubusercontent.com/6005028/41510007-708c1b92-725d-11e8-9597-d573ff4eab2f.png)

Front end
![image](https://user-images.githubusercontent.com/6005028/41510013-934249a4-725d-11e8-9e15-3e3c688cfa6c.png)

Sometimes the whole button text area disappeared on me
![image](https://user-images.githubusercontent.com/6005028/41510031-cf24fd68-725d-11e8-93ae-7ad764605d3f.png)

I'm guessing that this is related to missing placeholder text when text has been added, then removed completely.

**Comment by danielbachhuber** [comment] 2018-06-18 12:18
@kriskarkoski @krilor Could one of you use [Licecap](https://www.cockos.com/licecap/) or similar to document your reproduction steps? I tried reproducing again in Chrome and was unable to.

Also, do you have any plugins, etc. running?

**Comment by krilor** [comment] 2018-06-18 17:39
Just to make sure I fired up a fresh wordpress:4.9.6 using Docker and installed Gutenberg. Nothing else installed.

Here's my recording:

![gb 7311](https://user-images.githubusercontent.com/6005028/41552520-427ebb7e-732f-11e8-954c-799ceee28a12.gif)

**Comment by danielbachhuber** [comment] 2018-06-18 17:40
Huh. That is so weird. I wonder if it's some race condition with autosaves.

**Comment by edisonake** [comment] 2018-07-09 21:20
Just wanted to add a gif here of this error since I also experienced it. I noticed it when I was creating a block with a button following the code of the core button block. This was happening anytime the text was being deleted with the backspace key letter-by-letter. Selecting the text and deleting it didn't seem to bring up the issue.

![gutenberg-button](https://user-images.githubusercontent.com/3782010/42476308-89c99eaa-839b-11e8-82dd-cf67cc5764ed.gif)

After testing, I realized this only happens when inline elements are used instead of block elements for the `tagName` in the RichText component. 

```
<RichText
	tagName="span"
```

Replacing span with 'p' or 'div' fixed my issue.

**Comment by oxyc** [comment] 2018-07-09 22:31
Using a div fixed it in my case as well.

**Comment by designsimply** [comment] 2018-10-18 17:34
Closing because I re-tested with WordPress 4.9.8 and Gutenberg 4.0 and I can no longer reproduce the problem. Checked with Firefox 62.0.3 on and Chrome 69.0.3497.92 ([38s](https://cloudup.com/csyxjj-ICNz)) on macOS 10.13.6.

**Comment by bfintal** [comment] 2019-01-09 09:36
Please reopen as it still happens.

Following the steps illustrated by @krilor still produces the problem.

It might not be happening with the core button block since the RichText `tagName` was changed to `a` (which doesn't seem to show the problem anymore), but block plugins which are still using a RichText `span` still produces the problem in WordPress 5.0.2

**Comment by youknowriad** [comment] 2019-01-09 12:46
RichText don't support inline elements as `tagName`. This is a TinyMCE limitation. you can't use TinyMCE on inline elements. I'll close again and ask people to consider using non inline elements for RichText here.

**Closed by youknowriad** 2019-01-09 12:46 UTC
Labels: Blocks, [Type] Bug

**Comment by bfintal** [comment] 2019-01-09 15:38
@youknowriad If that's the case, shouldn't RichText instead throw a warning if it's used with inline elements like `tagName="span"`?

Anyway, I figured I'd investigate it still even though the issue was closed in hopes of getting this thing fixed.

I think I know why things result in a seemingly random single letter all the time. It's because when the RichText is set as `tagName="span"` and then you keep hitting backspace to delete the text.. after deleting the last remaining letter, the DOM is replaced with a new one, and the references to the old editable text are lost. Event calls on the RichText won't work any more after this.

The single letter that kept showing up when publishing posts was the last letter saved as the value before the first time the RichText was cleared via backspacing.. before the DOM was replaced.

I've created gifs to show this. Here's when `tagName="div"` and the value in the RichText is backspaced one by one:

![screen recording 2019-01-09 at 11 23 pm 1](https://user-images.githubusercontent.com/1033611/50909555-10f21b80-1467-11e9-8c35-7d8abbebfe01.gif)

Nothing special, a placeholder element is added.. things look normal.

Here's when it's `tagName="span"` and the value in the RichText is backspaced one by one. You can see here the DOM being replaced with a span with an id of `_mce_caret` when the value gets emptied:

![screen recording 2019-01-09 at 11 23 pm](https://user-images.githubusercontent.com/1033611/50909648-3bdc6f80-1467-11e9-9ccf-8fde7b5188c9.gif)

**Comment by bfintal** [comment] 2019-11-21 17:16
Just wanted to check in and say that I don't encounter this (the gifs I posted) anymore as of WordPress 5.3
