### ISSUE TITLE
Possible overflow style removal from panel

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#5535] opened 2018-03-09 15:56 UTC
In my block's inspector control, I want to display a Select2 component made using react but the options panel is partially hidden as shown in the image below:

![select2](https://user-images.githubusercontent.com/1268089/37216187-dbb9903c-23c2-11e8-832d-69d0265dc827.png)

For me the only way to solve this was to do something like:

```
.components-panel{
  overflow: visible !important;
}
```

but I guess this is not safe. I also suppose that there is no way to target this only for my block using a CSS selector or something.

After posting this on Slack, @aduth replied, wondering why the panel needs an overflow style, so he suggested that I create this ticket in order to further investigate this issue.

Thanks

**Comment by aduth** [comment] 2018-03-09 16:00
Related Slack conversation: https://wordpress.slack.com/archives/C02QB2JS7/p1520609257000746

**Comment by spwarner** [comment] 2019-02-12 16:57
This is still an issue (at times at least) in WP 5.0.3 - see attached screenshot. There is overflow: inherit; applied to @media (min-width: 600px) {.edit-post-sidebar>.components-panel} which pulls overflow: auto; from .edit-post-sidebar. See screenshot: 
![overflow](https://user-images.githubusercontent.com/7016339/52653129-b7499a80-2ec5-11e9-88e7-38ecd50c6edd.JPG)

**Comment by aduth** [comment] 2019-02-12 17:03
@spwarner Can you clarify which plugin is shown in the screenshot, for one who might want to try to reproduce it in their own test environment?

**Comment by spwarner** [comment] 2019-02-12 17:49
It's an unreleased update to a plugin I develop so I can't point to it yet, but it's just a react-select@2.3.0 Select component with a long list of options - should be easy to dump it into a demo and reproduce the issue. I'll see if I can make a quick demo plugin.

**Comment by spwarner** [comment] 2019-02-12 18:14
Here's a .zip of a demo plugin to test on. I'm still learning React, Blocks and all this new JS so the code isn't pretty I'm sure, but it worked on my local dev environment.
[async-test.zip](https://github.com/WordPress/gutenberg/files/2857088/async-test.zip)

**Comment by kmgalanakis** [comment] 2019-02-13 07:49
@spwarner I've had this issue with `react-select` quite recently and as I didn't have time to make a pull request, I ended up adjusting the styles of the control I used to work around the issue. So I created a custom style

```
customStyles = {
		menu: ( styles ) => {
			return { ...styles, position: 'relative' };
		},
	};
```

and then used it in my control this way

```
<Select	styles={ this.customStyles } ...
```

Of course this is not a solution to the actual problem but it can help you move on.

**Comment by spwarner** [comment] 2019-02-13 13:52
Thanks for the tips @kmgalanakis - they work around the issues nicely. This method does push any lower inspector panels offscreen while the menu is open so it's not ideal, but it's not really a problem as it snaps back when the menu shuts which is fine with me.

Seems like it might still be worth exploring the CSS overflow rule however as it may come up in other ways.

**Comment by tellthemachines** [comment] 2020-04-20 04:33
The overflow on `components-panel` is now set to visible. Closing as the issue is no longer reproducible.

**Closed by tellthemachines** 2020-04-20 04:33 UTC
Labels: General Interface
