### ISSUE TITLE
Issue with Edit Post

### ISSUE THREAD

**Issue by stefanos82** [WordPress/gutenberg#5686] opened 2018-03-18 19:34 UTC
I have installed Gutenberg so I can start experimenting and have discovered a rather awkward behavior.

I have saved and published the generated "Welcome to the Gutenberg Editor" demo post and attempted to edit it under Marinate theme (version 1.0.2) by Metric Themes and returned this error message:

![image](https://user-images.githubusercontent.com/1777466/37570061-8e66c3d0-2af3-11e8-979a-2455c3d4dc73.png)

I have tried the same thing with Twenty Sixteen (version 1.4) and Astra by Brainstorm Force (version 1.2.5) and worked just fine, as it should in the first place.

Is there anything I should do or check in case it's not a bug?

Please advice, thank you.

**Comment by aduth** [comment] 2018-03-18 20:39
Can you share the error message? Clicking "Copy Error" will copy the message to your clipboard, then you can paste here as a comment. Thanks.

**Comment by stefanos82** [comment] 2018-03-18 21:37
Sure. Here it is

```log
this.wp.components</u<@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:360090
p@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:169104
value/i<@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:358252
n/<@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:44409
n/<@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:35563
r@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:12264
r/<@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:39872
n@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:44376
r@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:24857
value@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:358172
value@http://stefanos82.cy/wp-content/plugins/gutenberg/components/build/index.js?ver=1521319628:6:356213
mountClassInstance@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:126:423
beginWork@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:134:45
d@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393
f@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214
g@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462
t@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3
x@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247
r@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:164:368
v@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:163:278
updateContainer@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:172:31
Hb/<@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:83:450
unbatchedUpdates@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:169:269
Hb@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:83:420
render@http://stefanos82.cy/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:191:247
o@http://stefanos82.cy/wp-content/plugins/gutenberg/edit-post/build/index.js?ver=1521319628:6:72891
window._wpLoadGutenbergEditor<@http://stefanos82.cy/wp-admin/post.php?post=1721&action=edit:1662:11
then/</</<@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:28766
i@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:27444
add@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:27748
then/</<@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:28738
each@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:2879
then/<@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:28684
a.Deferred@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:9:9928
then@http://stefanos82.cy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.9.4:2:28661
@http://stefanos82.cy/wp-admin/post.php?post=1721&action=edit:1660:254
@http://stefanos82.cy/wp-admin/post.php?post=1721&action=edit:1660:3
```

**Comment by ajitbohra** [comment] 2018-07-08 13:20
Unable to reproduce this on the master. Hence closing this for now, feel free to reopen.

**Closed by ajitbohra** 2018-07-08 13:20 UTC
Labels: [Type] Bug
