### ISSUE TITLE
[Toolbar ColorPicker] In the Toolbar in the Colorpicker the Colors are jumping between two hexCode colors

### ISSUE THREAD

**Issue by Floriandrias96** [WordPress/gutenberg#41088] opened 2022-05-16 13:49 UTC
### Description

Feature ColorPicker in the Tollbar is not working as intended. I expext when I paste a hex Color in the ColorPicker to see the Color, but when you paste a Hex Color the ColorPicker jumps between the new and old Color instead. see gif: "Toolbar ColorPicker Jumping Bug".

### Step-by-step reproduction instructions

1. Open the Toolbar of a TextBlock (e.g. Paragraph).
2. Click on "Displays more block tools.
3. Click on "Highlight" but with no Text selected (works with Link or just Text) .
4. Open CustomColor.
5. Click on "Show detailed inputs".
6. Paste a different Hexcolor into the inputfield that is curently used.

### Screenshots, screen recording, code snippet

![Toolbar ColorPicker Jumping Bug](https://user-images.githubusercontent.com/105651433/168604515-55277b54-0ce7-4e33-8446-46c8d7654ceb.gif)

### Environment info

Wordpressversion: 5.9.3
Gutenbergversion: 12.9.0
Active Theme: Twenty Twenty-Two
Testet on Browser: Chrome, Firefox and Edge
Device: PC

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-05-18 15:19
This can be also reproduced by clicking `backspace` in the input for the custom color. It seems it might involve inner input components handling... --cc @ciampo @mirka

**Comment by ciampo** [comment] 2022-05-19 16:01
Thank you for the ping!

I can reproduce the issue as described by both @Floriandrias96 and @ntsekouras in the editor, however I was not able to reproduce it on the [`ColorPicker` component in isolation](https://wordpress.github.io/gutenberg/?path=/story/components-colorpicker--default).

I'll look a bit more into that and come back with any further discovery.

**Comment by ciampo** [comment] 2022-05-19 16:41
I also checked [the `ColorPalette` component](https://wordpress.github.io/gutenberg/?path=/story/components-colorpalette--default) in isolation, and wasn't able to reproduce the issue.

The issue seems related to some sort of "infinite loop" where a new color value is not committed properly to whatever "state" is stored.

Next up, I would look at the `InlineColorUI` component, in particular at its ["internal" `ColorPicker`](https://github.com/WordPress/gutenberg/blob/c386fd09299aab83df2b9da2dbab59016c6dba50/packages/format-library/src/text-color/inline.js#L112-L136) and at its logic to [set / get colors](https://github.com/WordPress/gutenberg/blob/c386fd09299aab83df2b9da2dbab59016c6dba50/packages/format-library/src/text-color/inline.js#L62-L110).

I'm really not familiar with this part of the codebase, and so it'd be great if someone with more familiarity could take a look as well.

It would also be interesting to find out when this bug introduced — it may give further hints to what's causing it.

**Comment by cuemarie** [comment] 2023-03-22 18:32
In case these are related, I've opened the following reports based on the https://github.com/Automattic/wp-calypso/issues/59566 issue above:

- https://github.com/WordPress/gutenberg/issues/49286
- https://github.com/WordPress/gutenberg/issues/49287

**Comment by ciampo** [comment] 2023-04-05 14:24
Hey @Floriandrias96 and @ntsekouras , I took another quick look and couldn't reproduce this issue on latest `trunk` (i.e. the flashing between two different colors in the color picker).

In case you can't reproduce it either, we can close this issue.

**Comment by ntsekouras** [comment] 2023-04-07 08:41
I couldn't reproduce either.. Let's close for now and feel free to reopen if someone can reproduce.

**Closed as completed by ntsekouras** 2023-04-07 08:41 UTC
Labels: [Type] Bug, [Package] Components, [Package] Format library
