### ISSUE TITLE
RichText onSplit is passed an empty string immediately after an onMerge event when using the delete key

### ISSUE THREAD

**Issue by mwnciau** [WordPress/gutenberg#38207] opened 2022-01-25 11:58 UTC
### Description

Using the RichText block editor control, when you are at the end of one block and press the delete key, thus triggering an onMerge event, and then immediately press enter, triggering the onSplit, the new block that is generated is always empty.

### Step-by-step reproduction instructions

1. Create a Buttons block in the gutenberg editor
2. Create two buttons, the first with text "abcd", the second with text "1234"
3. Place the cursor at the end of the first button
4. Press delete to merge the two blocks
5. Press enter to split the two blocks

Expected behaviour: two buttons with content "abcd" and "1234"
Actual behaviour: two buttons with content "abcd" and "" (empty string)

Tested with the default "Buttons" block. With a custom block, I can see that the onSplit function is passed: ("abcd", true) and ("", false). I also verified that the content attribute is correctly being set.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/2857218/150972956-f21f60cf-7ba2-4c95-95bb-a466eb09efd0.png)

### Environment info

Wordpress 5.8.2 (without the gutenberg plugin installed)
Firefox 96.0.2, Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-02-01 13:14
This problem is specific to the Windows OS and seems to be very similar to this issue.

- https://github.com/WordPress/gutenberg/issues/38322

**Comment by ntsekouras** [comment] 2022-02-23 08:20
👋 Actually I could reproduce in macOS, before this fix: https://github.com/WordPress/gutenberg/pull/38991. Can you verify that the issue has been resolved with the above merged fix? If yes we should close the issue.

**Comment by ntsekouras** [comment] 2022-02-23 08:45
👋 Actually I could reproduce in macOS, but it seems it's been resolved with this fix: https://github.com/WordPress/gutenberg/pull/38991. I'm closing this now, but feel free to reopen if it still persists.

**Closed as completed by ntsekouras** 2022-02-23 08:45 UTC
Labels: [Feature] Rich Text
