### ISSUE TITLE
Disabling separation block breaks pasting text with repeated undescores

### ISSUE THREAD

**Issue by ofadam** [WordPress/gutenberg#45977] opened 2022-11-22 21:05 UTC
### Description

When separation blocks are disabled and you try to paste text that contains repeated underscore characters on a new line, nothing is pasted.

### Step-by-step reproduction instructions

1. Disable embed blocks. (to make it easy to reproduce, only allow the paragraph block) 
```
add_filter( 'allowed_block_types', function() {
   return [ 'core/paragraph' ];
} );
```

2. Create a new page and try to paste the text: 
```
Lorem ipsum dolor sit amet.
___
Lorem ipsum dolor sit amet.
```

### Environment info

- WordPress 6.1
- Any theme
- Gutenberg from WP 6.1
- Firefox 106
- MacOS Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-11-23 09:28
Thanks for contributing, @ofadam!

I believe this is a duplicate of #27835. In your case editor tries to transform `___` into a Separator block.

I will close this issue as a duplicate.

**Closed as not planned by Mamaduka** 2022-11-23 09:28 UTC
Labels: [Type] Bug, [Feature] Rich Text, [Feature] Paste, [Status] Duplicate
