### ISSUE TITLE
Classic editor -> GB. Converting Preformated to code blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13189] opened 2019-01-04 14:33 UTC
**Describe the bug**
I have a lot of preformated TinyMCE sections that I want to convert over to code blocks in Gutenberg. What happens is that the code in the preformated sections upon converting to GB bunches all the code together.

**To Reproduce**
1. In Classic Editor/TinyMCE.
2. Create preformated areas that contain code.
3. Convert it to Gutenberg and notice the line breaks disappear.

**Expected behavior**
That I can go from preformated sections in the Classic Editor to preformated or code blocks in Gutenberg without losing any line breaks. I also expected to be able to switch from preformated over to a code block.

**Screenshots**
Classic block in Gutenberg:
![screen shot 2019-01-04 at 15 25 39](https://user-images.githubusercontent.com/5323259/50692693-02ee6600-1035-11e9-9fa5-3cbafe725c4f.png)

Converting over to GB blocks. Line breaks are gone. I am not able to switch preformated classic to code blocks in Gutenberg.
![screen shot 2019-01-04 at 15 31 56](https://user-images.githubusercontent.com/5323259/50692970-eb63ad00-1035-11e9-8baa-8d9d47e01812.png)

WordPress version: 5.0.2
Mac OSX10.13.6
Chrome

**Comment by designsimply** [comment] 2019-02-05 00:15
Closing as a duplicate of #12109.

**Closed by designsimply** 2019-02-05 00:15 UTC
Labels: Block Conversion, Needs Testing
