### ISSUE TITLE
In the Block editor, if you enter a negative value for the margin, it will be reset to 0.

### ISSUE THREAD

**Issue by nendeb** [WordPress/gutenberg#41145] opened 2022-05-19 03:26 UTC
### Description

If I enter a negative value in the Dimensions margin of a Group Block or Heading Block, it will be reset to 0.

### Step-by-step reproduction instructions

We have tried other methods.
In the Code editor, if I enter a negative value directly in margin, it can be saved, but if I go back to the Visual editor and try to change the value, it is set to 0.

### Environment info

WordPress6.0 RC3
Twenty Twenty-Two 1.2

### Please confirm that you have searched existing issues in the repo.

Yes,

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2022-05-19 05:27
Thanks for reporting this. I am going to close it as it is a duplicate of https://github.com/WordPress/gutenberg/issues/32644

**Closed as completed by glendaviesnz** 2022-05-19 05:27 UTC
Labels: [Status] Duplicate
