### ISSUE TITLE
When in selection/navigation mode, the advanced CSS class names field loses focus after entering a character

### ISSUE THREAD

**Issue by pyronaur** [WordPress/gutenberg#22458] opened 2020-05-19 08:52 UTC
Adding a group block with a couple of inner blocks prevents user from entering class names.

**To reproduce**
Here's a video of the issue:
https://cloudup.com/c5NPGHPJBHs

The bug is visible at starting around 1:00 minute mark

Create a couple of blocks within a Block Group and then try to set a class name for that block group - the CSS Class names input is going to lose focus on each key press.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Tried and reproduced in both WordPress 5.4.1 and Gutenberg 8.1.0

**Desktop**
 - OS: Mac 10.15.4
 - Browser Firefox 76

**Comment by talldan** [comment] 2020-05-22 09:15
It seems as though the key thing here is that the editor is in Selection/Navigation Mode:
<img width="266" alt="Screenshot 2020-05-22 at 5 14 24 pm" src="https://user-images.githubusercontent.com/677833/82652161-bb7b7080-9c4f-11ea-9ec3-9f0aeed00460.png">

The issue seems to happen for any block when in navigation mode, but isn't present in Edit Mode.

**Comment by talldan** [comment] 2020-06-05 05:25
Just spotted that this looks to be a duplicate of #21837

**Closed by talldan** 2020-06-05 05:25 UTC
Labels: [Feature] Writing Flow, [Type] Bug
