### ISSUE TITLE
Flipped Color picker in Gutenberg in Rtl languages

### ISSUE THREAD

**Issue by hamedmoody** [WordPress/gutenberg#17622] opened 2019-09-27 06:43 UTC
We have flipped color picker in rtl languages such as Persian

![ezgif com-optimize](https://user-images.githubusercontent.com/9475089/65747804-429f3580-e10f-11e9-913c-0aa98024ea6b.gif)

this problem is in Css  style for rtl languages

Another problem is: hue slider does not move!

**Comment by talldan** [comment] 2019-09-27 07:11
@hamedmoody - thanks, though I thought this issue was fixed by #17381, are you still having problems with the color picker?

If you're able to test version 6.5 of the Gutenberg plugin, that would be really appreciated.

**Comment by hamedmoody** [comment] 2019-09-27 08:37
Oh sorry, But how can i test version 6.5 in wordpress 5.2?

**Comment by talldan** [comment] 2019-09-27 09:10
@hamedmoody It should just be a matter of installing the plugin, the latest version is 6.5:
https://en-au.wordpress.org/plugins/gutenberg/

In your screenshot it looks like you're using a local site (which I'd recommend for testing this).

**Comment by brezocordero** [comment] 2019-11-03 21:37
Tested with Gutenberg 6.8.0
Chrome 77.0.3865.120 (Official Build) (64-bit)
Couldn't reproduce it. Color picker was not flipped and hue slider moves.
![ColorPickerRTL](https://user-images.githubusercontent.com/8002881/68092344-c3102f00-fe4f-11e9-90a3-c563abb00756.gif)

**Comment by mapk** [comment] 2019-11-19 00:17
@hamedmoody are you still experiencing this issue, or has it been resolved?

**Comment by hamedmoody** [comment] 2019-11-23 04:08
it was resolve, thanks

**Closed** 2019-11-27 22:46 UTC
Labels: Needs Testing, [Type] Bug
