### ISSUE TITLE
Latest post: Category selection triggers notice, displayed on front end

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#21550] opened 2020-04-11 22:07 UTC
**Describe the bug**
 "Notice: Undefined index: items in /app/public/wp-includes/rest-api.php on line 1245

**To reproduce**
1. Add Latest Post Block to a page
2. Select Category "Uncategorized"
3. Publish page
4. View page. 

**Expected behavior**
No display of notices. 

**Screenshots**
![Screen Shot 2020-04-11 at 6 05 26 PM](https://user-images.githubusercontent.com/39980/79055936-12d4fc80-7c1f-11ea-95bd-c17cb992e2a0.png)

Tested it with clean install 
![Screen Shot 2020-04-11 at 6 03 23 PM](https://user-images.githubusercontent.com/39980/79055946-241e0900-7c1f-11ea-83f2-c82468c291f4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.15.3
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 80.0.3987.163

**Additional context**
WordPress 5.4 - Note: I was not able to reproduce in 5.4 RC. if that helps with locating things. 
Gutenberg 7.8.1

**Comment by draganescu** [comment] 2020-04-13 13:01
I was not able to reproduce this with WordPress 5.4 and Gutenberg 7.8.1 even after enabling display all errors in PHP. I wonder if I am missing anything?

**Comment by bph** [comment] 2020-04-13 14:01
When trying to edit the page with the Latest Post block, I also get for a brief moment these warnings, before the editor is fully loaded. 
![Screen Shot 2020-04-13 at 10 00 06 AM](https://user-images.githubusercontent.com/39980/79126287-aae0fc00-7d6d-11ea-96a5-de0566089dfc.png)

**Comment by bph** [comment] 2020-04-13 14:14
@draganescu Thanks for testing this. Here is my Block Settings in the sidebar
![Screen Shot 2020-04-13 at 10 02 14 AM](https://user-images.githubusercontent.com/39980/79126425-e54a9900-7d6d-11ea-9d96-3bfec97415ad.png)

**Comment by bph** [comment] 2020-04-13 18:07
Using the Site Health Troubleshooting Mode on a live site: 
It occurs only when Gutenberg plugin is enabled (7.8.1)
There is a chance it'll be fixed with this PR #21359

**Comment by draganescu** [comment] 2020-04-14 14:44
@bph I can confirm this now and it is indeed a problem that #21359 may fix. If the block is created in pre 7.8.1 Gutenberg and is filtered, then after upgrading this error starts to show up. Will investigate further!

**Comment by draganescu** [comment] 2020-05-11 12:13
Closed by #21359

**Closed by draganescu** 2020-05-11 12:13 UTC
Labels: [Block] Latest Posts, [Type] Bug
