### ISSUE TITLE
Drop Cap applies to punctuation

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#1622] opened 2017-06-30 19:12 UTC
If the text starts with a since letter and a punctuation mark (such as the word "I've"), then both the letter and the punctuation mark appear bigly.

**Comment by westonruter** [comment] 2017-07-08 01:14
This seems to be due to `::first-letter` is being used, and [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter):

> The first letter of an element is not always trivial to identify: ¶ Punctuation that precedes or immediately follows the first letter is included in the match. Punctuation includes any Unicode character defined in the open (Ps), close (Pe), initial quote (Pi), final quote (Pf), and other punctuation (Po) classes.

The solution may involve #1340 in which the PHP render callback can wrap the actual first letter with a `span` which can then be styled without using `::first-letter`.

**Comment by mtias** [comment] 2017-08-18 20:50
Sounds like the alternative of just making the `I` bigger but keep the `'` as the first item of the small line wouldn't be a great typographic experience either. Since this is opt-in, I think we should just consider it a tradeoff.

**Comment by jasmussen** [comment] 2017-11-20 11:49
I'm going to close this one as, while I agree with the sentiment of the ticket — it would be nice with smarts here — there isn't really anything we can do. Since it's an advanced feature, off by default, and actively toggled presumably through intent, an argument can be made that this is both _expected behavior_ and a "feature". In other words if we were able to make some smarts here, then the opposite argument could be made — drop cap doesn't work for punctuation. Who knows what crazy poetry someone might want to write.

**Closed by jasmussen** 2017-11-20 11:49 UTC
Labels: Needs Design Feedback

**Comment by JJJ** [comment] 2018-11-24 05:32
I do not expect for an apostrophe to be part of the drop-cap. It looks really weird, and feels like a bug.

<img width="673" alt="screen shot 2018-11-23 at 11 30 28 pm" src="https://user-images.githubusercontent.com/88951/48964918-127b8900-ef78-11e8-8fc6-ad600f591383.png">
<img width="262" alt="screen shot 2018-11-23 at 11 32 16 pm" src="https://user-images.githubusercontent.com/88951/48964919-127b8900-ef78-11e8-86a2-e7052306d9eb.png">
