### ISSUE TITLE
Issue in Pullquote Block

### ISSUE THREAD

**Issue by KAJALwp** [WordPress/gutenberg#43566] opened 2022-08-24 09:09 UTC
### Description

When we select Pullquote block in post or page, we can view Top and Bottom separator in editor side but we can't view separator in front-side.

For better understanding I provide video attachment link. 

### Step-by-step reproduction instructions

1. Go to editor
2. Open page or post
3. Add Pullquote Block
4. Save page or post
5. See preview in front-side

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/awAMQ0VPRAKeNry3K85K

### Environment info

WordPress:- 6.0.1
Mac OS:- Monterey 12.4
Chrome:- Version 104.0.5112.101 (Official Build) (arm64)
Theme: Twenty Seventeen
Gutenberg Plugin: 13.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by courtneyr-dev** [comment] 2022-08-25 15:50
This seems isolated to Twenty Seventeen theme.  I tested this with 

- Twenty Twenty Two
- TT1
- Wabi
- Twenty Sixteen
- Twenty Twenty One

All were formatted with the lines on front of site as expected. I tested in Twenty Seventeen and reproduced it there.

**Comment by aatanasovdev** [comment] 2022-08-26 19:26
It looks like a theme related issue. The border lines shown inside the Editor come from the theme itself (in our case Twenty Seventeen).

<img width="1245" alt="Screenshot 2022-08-26 at 22 09 19" src="https://user-images.githubusercontent.com/38669058/186974944-c7b83dfc-7435-4a20-a504-7ce704b1e763.png">

We can see the theme's styles overwrite the default Editor styles inside the Editor. However, on the front-end, the Editor's styles have high priority.

This isn't the case for other themes like Twenty Twenty Two.

When it comes to custom styles, I think the theme authors should handle such cases and make sure the styles are added as expected to both the front-end and back-end sides.

In regards to the Pullquote Block, its border settings work as expected on my side.

**Comment by t-hamano** [comment] 2022-11-12 08:35
@KAJALwp 
Thank you for your contribution.

I have found that you have submitted a similar ticket to Trunk: https://core.trac.wordpress.org/ticket/56441

I would like to close this PR as I think this issue should be addressed on the theme side. If you have any clarifications, please feel free to reopen it at any time.

**Closed as completed by t-hamano** 2022-11-12 08:35 UTC
Labels: [Block] Pullquote
