### ISSUE TITLE
View in Editor is totally different from the Preview or Published view

### ISSUE THREAD

**Issue by kosiew** [WordPress/gutenberg#10376] opened 2018-10-06 08:37 UTC
**Describe the bug**
The paragraphs in the Editor are ignored when published

**To Reproduce**
Cannot reproduce.
I published 2 posts on 2 different blogs. The first had this disastrous outcome. The second had the desired output.

**Expected behavior**
The paragraph formatting in Preview and Published mode should look exactly like the in Editor mode.

**Screenshots**
http://cld.wthms.co/6wAZ3W

![screen shot on 2018-10-06 at 16-30-37](https://user-images.githubusercontent.com/1119271/49248708-977efc00-f3d7-11e8-9436-af77b0f0f52c.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser : Chrome
 - Version : Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by chrisvanpatten** [comment] 2018-10-06 11:54
@kosiew Could you check the Code Editor mode inside Gutenberg to ensure there are paragraph tags in the code? Then could you inspect the source of the live page to see if those paragraph tags are still there or if anything has been stripped out?

Also, it looks like this might be a WordPress.com blog; could you provide a link to the post so we can take a look?

Thanks!

**Comment by kosiew** [comment] 2018-10-08 06:33
@chrisvanpatten 
Code Editor view - http://cld.wthms.co/sUx7Ag

link to the post - https://xizunite.blog/2018/10/06/the-unseen-unremembered/.

I also noticed that when I `edit` the post, I got the message that there is another version. 
http://cld.wthms.co/Mhdg7q

I have not clicked on Restore yet.
Workflow-wise, the paragraphs is not really a later version of the post. We don't normally write one big paragraph and then later edit it to smaller paragraphs.

**Comment by kosiew** [comment] 2018-10-16 08:46
@chrisvanpatten 

I opened the post in Classic Editor, clicked Update and that fixed the formatting issue.

**Comment by kristarella** [comment] 2018-10-18 06:38
I think this might be Calypso-specific, so I have linked to https://github.com/Automattic/wp-calypso/issues/21973

**Comment by designsimply** [comment] 2018-11-29 20:12
Closing in favor of https://github.com/Automattic/wp-calypso/issues/21973 and noting they would like new issues opened at https://github.com/Automattic/wp-calypso/issues with steps to reproduce, including the theme being used. 

@kosiew, several updates have been made since you first posted. Can you let me know if you're still having trouble with the same blogs as before and which themes those blogs are using?

**Closed by designsimply** 2018-11-29 20:12 UTC
