### ISSUE TITLE
wp-env latest images broken with error `mysqlcheck access denied for user`

### ISSUE THREAD

**Issue by andrewmumblebee** [WordPress/gutenberg#29810] opened 2021-03-12 08:43 UTC
## Description
`wp-env` was working fine until yesterday for me, when i decided to change a bit of the wp-env.json file and it seemed to rebuild the container with the latest images. now i can't use it to run a WordPress environment. I assumed it was the change i made at first, but after retrying it without a config file and then on a separate machine (with a fresh install of wp-env) i still have the exact same error.

This is what i get running `wp-env start`

```
✖ Error while running docker-compose command.
Creating 0be3c9e22068177d621496940e46490a_cli_run ... 
Creating 0be3c9e22068177d621496940e46490a_cli_run ... done
mysqlcheck: Got error: 1045: Access denied for user 'username_here'@'172.20.0.5' (using password: YES) when trying to connect
2
```

The containers are still running, but the database connection is borked.

## Step-by-step reproduction instructions
1. run `wp-env start` after changing config file

## Expected behaviour
I can run a WordPress environment

## Actual behaviour
I can't run a WordPress environment and have had to resort to traditional dev setup i.e. Local or setting up WordPress with LAMP on WSL.

## Device information
- Device: Desktop
- Operating system: Windows 10

**Comment by mirka** [comment] 2021-03-12 14:27
Duplicate of #29752

**Closed** 2021-03-15 00:42 UTC
