### ISSUE TITLE
Schedule Button and Publish Button

### ISSUE THREAD

**Issue by benlumia007** [WordPress/gutenberg#20173] opened 2020-02-11 18:27 UTC
is it normal that sometimes when creating a new post or page, I see the schedule button instead of publish button, and sometimes it just goes back and forth?

was there a release that may cause this problem. I don't' know if I would put this in help request or a bug request so. 

I'm on wordpress 5.3.2, and i have disabled and enabled the gutenberg plugin, same thing. 

please point me to the correct destination if there is :D

**Comment by danielbachhuber** [comment] 2020-02-25 13:36
I'm seeing this quite often too.

Something interesting though: I literally saw "Schedule...", switched to a different tab, switched back to my editor, and the button changed back to "Publish...".

**Comment by paaljoachim** [comment] 2021-04-15 20:06
Is this issue still valid?
@retrofox Damian might have some input here.

**Comment by ghost** [comment] 2021-04-15 20:09
oh wow, this is still open! :)

**Comment by retrofox** [comment] 2021-04-15 21:25
HI, there. I can take a look at it these days. :-)

**Comment by ndiego** [comment] 2022-08-02 14:16
This issue was reviewed in the weekly Editor Bug Scrub and 3 testers were unable to reproduce in the latest version of WordPress and Gutenberg. Therefore, I am closing but if someone is able to reproduce, feel free to reopen.

**Closed by ndiego** 2022-08-02 14:16 UTC
Labels: [Type] Bug, Needs Testing
