### ISSUE TITLE
Full size image with 100% width larger than canvas

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#13944] opened 2019-02-19 11:59 UTC
**Describe the bug**
When adding an image (original size larger than gutenberg width) with the image size "full size" and a width of 100%, the image is larger than than the gutenberg canvas.

Every try to solve this error causers other problems with the bottom handle positioned wrong.

**To Reproduce**
1. Add an Image
2. Choose Image Site "Full Size"
3. Click the "100%" Button in the Image Dimensions section.

**Expected behavior**

**Screenshots**

Screenshot showing the Error:

<img width="1792" alt="bildschirmfoto 2019-02-19 um 12 24 14" src="https://user-images.githubusercontent.com/6911678/53011750-6ac00b00-3441-11e9-9d56-e97a697e5f5b.png">

When Trying to overwrite the max with via css i get another error with the bottom handle positioned wrong:

<img width="1791" alt="bildschirmfoto 2019-02-19 um 12 25 02" src="https://user-images.githubusercontent.com/6911678/53011783-7f9c9e80-3441-11e9-8e5a-ed504543ecb6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 73

**Comment by designsimply** [comment] 2019-02-21 23:41
Thank you for the clear report including screenshots! I am closing this issue as a duplicate of https://github.com/WordPress/gutenberg/issues/12168 and have added your notes to that issue so the conversation can be continued there.

**Closed by designsimply** 2019-02-21 23:41 UTC
Labels: Needs Testing, [Block] Image
