### ISSUE TITLE
Minifield React Error #185 Version 4.5.0

### ISSUE THREAD

**Issue by rkcrane11** [WordPress/gutenberg#12143] opened 2018-11-21 01:33 UTC
**Describe the bug**
When attempting to create a new paragraph block or edit an existing block in the most recent version of Gutenberg, the above logs appear.
**To Reproduce**
1. Create post
2. Click Enter in Paragraph block to create a new paragraph block.
3. One of 2 errors consistently appears: "this block has encountered an error and cannot be 
 previewed" or the post completely crashes and you have to enter recovery mode

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44347309/48813075-4601ad80-ed03-11e8-9507-8f97030a49a2.png)

**Desktop (please complete the following information):**
 - OS: Mac OSx Mojave 10.14.1
 - Browsers Tested in: Browser Settings: Version 70.0.3538.110 (Official Build) (64-bit)
Reproducible in Safari Version 12.0.1 (14606.2.104.1.1) with the same error message

**Additional context**
This error is currently making it almost impossible to get any sort of post written using Gutenberg at this moment in time.

**Comment by rkcrane11** [comment] 2018-11-21 01:49
Update: rolled back to the previous version, 4.4.0 and everything appears to be working fine at the moment. Error appears to be a part of one of the fixes in the most recent update

**Comment by pento** [comment] 2018-11-21 04:35
Thank you for the bug report, @rkcrane11!

Do you have an plugins installed that add blocks or other functionality to the block editor?

Are you able to set these options in your `wp-config.php` file, and get the error message then?

```php
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
```

**Comment by gziolo** [comment] 2018-11-21 08:50
Duplicate of #12150 where we have more details :)

**Closed by gziolo** 2018-11-21 08:50 UTC
