### ISSUE TITLE
PDF documents are not displayed in mobile device version

### ISSUE THREAD

**Issue by NAROLLES** [WordPress/gutenberg#50702] opened 2023-05-17 14:39 UTC
### Description

The basic widget block in gutemberg called “file” allows you to put a pdf online and it does very well on desktop device but on mobile, there is no thumbnail or preview proposal which would be better. Currently this makes it almost invisible as there is only the download link

Last discussion with an gutenberg expert
https://wordpress.org/support/topic/bloc-file-pdf-on-mobile-device/#post-16745383
reference link for example
https://www.jardinerie-animalerie-fleuriste.fr/actualites/la-biodiversite-est-a-lhonneur-chez-botanic-decouvrez-le-carnet-dinspiration/802373/

### Step-by-step reproduction instructions

1 watch this post on mobile
https://www.jardinerie-animalerie-fleuriste.fr/actualites/la-biodiversite-est-a-lhonneur-chez-botanic-decouvrez-le-carnet-dinspiration/802373/

2 You see or not at the end of the post an overview of the Pdf document as you can see it on a desktop

If i deactivated all the plugins …. no change
if i changed the Hello theme from elementor to theme 2023 ...On my mobile I have the display of an “iframe” to open….see screenshots

The same tests on Edge give the same result

### Screenshots, screen recording, code snippet

https://www.awesomescreenshot.com/image/39886443?key=d18ae67e1482990857d461ab38df7f1c
https://www.awesomescreenshot.com/image/39923885?key=767ca741f93ffec78d3bc601bfdefe9b
https://www.awesomescreenshot.com/image/39923884?key=ef8bdfa2df8562b7061225f3d86f1b13

### Environment info

Wordpress - Woocommerce - Budypress - Elementor Elementor Pro Up to date
Windows 11 chrome Edge - Up to date
Android 13 One UI 5.1 Samsung S20 FE ou Samsung S8+ - Up to date

`
### WordPress Environment ###

WordPress address (URL): https://www.jardinerie-animalerie-fleuriste.fr
Site address (URL): https://www.jardinerie-animalerie-fleuriste.fr
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.1
WP Multisite: –
WP Memory Limit: 5 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.18
PHP Post Max Size: 5 Go
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 8.0.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB
Max Upload Size: 400 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Taille totale de la base de données: 1927.00MB
Taille de la base de données: 1331.24MB
Taille de l’index: 595.76MB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Admin Columns Pro: par AdminColumns.com – 6.2.1
AdRotate Professional: par Arnan de Gans – 5.12.3
Advanced Custom Fields: par WP Engine – 6.1.6
Akismet Anti-Spam: par Automattic – 5.1
BuddyPress: par La communauté BuddyPress – 11.2.0
Classic Editor: par Contributeurs et contributrices WordPress – 1.6.3
Yoast Duplicate Post: par Enrico Battocchi & l’équipe Yoast – 4.5
GTM4WP: par Thomas Geiger – 1.16.2
Elementor Pro: par Elementor.com – 3.13.1
Elementor: par Elementor.com – 3.13.2
Folders Pro: par Premio – 2.8.7
Health Check & Troubleshooting: par La communauté WordPress – 1.6.0
Login Lockdown: par WebFactory Ltd – 2.06
MailPoet Premium: par MailPoet – 4.16.0
MailPoet: par MailPoet – 4.16.0
Meks Video Importer: par Meks – 1.0.10
OneSignal Push Notifications: par OneSignal – 2.4.0
OWM Weather: par Uwe Jacobs – 5.6.14
Public Post Preview: par Dominik Schilling – 2.10.0
Rank Math SEO: par Rank Math – 1.0.114
Advanced Editor Tools: par Automattic – 5.9.0
WooCommerce Numéro de TVA intracommunautaire: par Woocommerce – 2.8.3
Teams for WooCommerce Memberships: par SkyVerge – 1.6.3
WooCommerce Memberships: par SkyVerge – 1.24.0
Paiements WooCommerce: par Automattic – 5.8.1
Abonnements WooCommerce: par WooCommerce – 5.1.2
WooCommerce: par Automattic – 7.7.0
WordPress Popular Posts: par Hector Cabrera – 6.1.1
Gestionnaire de fichiers WP: par mndpsingh287 – 7.1.9
WP-Polls: par Lester 'GaMerZ' Chan – 2.77.1
WP Rocket: par WP Media – 3.13.2

### Inactive Plugins (4) ###

BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce: par Pagup – 1.4.6.2
Imagify: par Imagify – Optimize Images & Convert WebP – 2.1.1
Rank Math SEO PRO: par Rank Math – 3.0.35
reCaptcha by BestWebSoft: par BestWebSoft – 1.71

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: Memcached Redux

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: par  – 1.9.0

### Theme ###

Name: Hello Elementor Child 2023
Version: 2.0.0
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.7.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: Articles: 2 itemsPages: 1 item
Excluded from discounts:: –
Membership plans:: 1
Plan Premium:: Members: 2Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No

### Abonnements ###

WCS_DEBUG: ✔ Non
Subscriptions Mode: ✔ En direct
Subscriptions Live URL: https://www.jardinerie-animalerie-fleuriste.fr
Subscriptions-core Library Version: 5.7.1
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Oui
Cache Update Failures: ✔ 0 échecs

### Configuration de la boutique ###

Country / State: France

### Prise en charge de la passerelle de paiement ###

Virement bancaire: products

###

Daily Cron: ✔ Next scheduled: 2023-05-17 22:30:18 +02:00
Options: ✔
Notes: 127
Onboarding: completed

### Action Scheduler ###

Complete: 20 511
Oldest: 2023-04-16 18:11:39 +0200
Newest: 2023-05-17 16:23:27 +0200

Pending: 3
Oldest: 2023-05-17 16:25:27 +0200
Newest: 2023-05-17 20:15:14 +0200

### Status report information ###

Generated at: 2023-05-17 16:23:59 +02:00
`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2023-05-18 11:32
Thanks for contributing, @NAROLLES!

This is probably a duplicate of #46382. The file block only enables PDF previews if the device/browser supports them - #30857.

**Closed as completed** 2023-05-18 15:10 UTC
Labels: [Status] Duplicate, [Block] File

**Comment by NAROLLES** [comment] 2023-05-18 16:01
> Merci pour votre contribution,@NAROLLES!
> 
> Il s'agit probablement d'un doublon de #46382 . Le bloc de fichiers n'active les aperçus PDF que si l'appareil/le navigateur les prend en charge - #30857 .

THANKS
I would point out, however, that pdf display plugins work on the same mobiles and browsers. Samsung mobiles and Chrome browsers are still widespread
Thank you for your attention
