### ISSUE TITLE
[Widgets Screen]Resizing Images Blocks Preview Broken

### ISSUE THREAD

**Issue by azollafox** [WordPress/gutenberg#32708] opened 2021-06-15 18:39 UTC
## Description
Image block preview in Widget Block area is broken

## Step-by-step reproduction instructions

1. Follow guide to enable Widget Editor
2. Click to Appearance> Customize
3. Add an image block
4. try adjusting the size to anything larger than the pixels for the widget column

## Expected Behavior

I expected image adjustment on the widget editor to match image adjustment in a page or post editor

## Actual behaviour

<img width="1779" alt="Screenshot on 2021-06-15 at 14-32-53" src="https://user-images.githubusercontent.com/7907292/122105915-4bee9b00-cde7-11eb-9bea-31e2b16f1100.png">

**Comment by noisysocks** [comment] 2021-06-16 04:25
Thanks for the issue. Looks like a bug. One shouldn't be able to resize an image to be larger than the widget area.

**Comment by tellthemachines** [comment] 2021-06-23 03:44
> I expected image adjustment on the widget editor to match image adjustment in a page or post editor

Thanks for creating this issue @sarahfg ! This behaviour does match the post/page editor, though it's far from consensual that it is correct and there are a few issues open about it: #28915 and #26715. As the widgets editor behaviour doesn't vary in any way I'll go ahead and close this as a duplicate of the issues mentioned above.

**Closed as completed by tellthemachines** 2021-06-23 03:44 UTC
Labels: [Type] Bug, [Feature] Widgets Screen
