### ISSUE TITLE
Space bar not registering spaces

### ISSUE THREAD

**Issue by nanrector** [WordPress/gutenberg#15238] opened 2019-04-28 18:41 UTC
I started having this problem recently and I’m unsure what preceded it. Much of the time when I hit the space bar between words it will not add a space as I type in the text editor in wordpress.   It does it intermittently and ONLY in wordpress so it can’t be a keyboard issue. It does not work more than it does so I have to keep a text doc open to type in then copy over which is a pain.

Is there something I can do to fix this?

Thanks!
Nancy
Windows 10 Home
http://www.craftyourhappiness.com

**Comment by nerrad** [comment] 2019-04-29 13:32
Hi there, thanks for taking the time to report your issue.

I'm unable to reproduce this and we need a bit more information before we can action this.  There's some excellent folks in the [WordPress support forums](wordpress.org/support/forums) who can assist you with further troubleshooting this and finding out what can be reported in more detail here.

I'm going to close this for now but once you've received more help from the support forum if there is additional information you can repost in here.

Thanks again!

**Closed by nerrad** 2019-04-29 13:32 UTC
Labels: [Status] Needs More Info
