### ISSUE TITLE
Parent theme wrongly missing (6.5-alpha-57505)

### ISSUE THREAD

**Issue by DennysDionigi** [WordPress/gutenberg#58549] opened 2024-02-01 10:16 UTC
### Description

Following https://github.com/WordPress/twentytwentyfour/issues/733

### There is a bug in latest WordPress FSE Core Updates and/or any FSE theme.

The following is the error: The parent theme is missing. Please install the "XXX" parent theme. when trying to set up the most basic of Child Themes. 

I also believe this could be related to Multisite, or to the way the core searches for any php file related to parent theme (which blocks based themes have not, or at least... not mandatory).

The double problem is that: even both sibling theme exist, parent and child, and even if folder names and directories are the required and right ones, this alert should not appear.

### Step-by-step reproduction instructions

# Steps to Reproduce

## Create a child theme
Create a new directory: wp-content/themes/twentytwentyfour-child
Create a child theme style.css file, containing Theme Name: Twenty Twenty-Four Child and Template: twentytwentyfour ([Screenshot](https://3cd.co/jku6GmrK))
Visit WordPress Admin > Appearance > Themes ([Screenshot](https://3cd.co/Z4upR1P2))
Activate the Twenty Twenty-Four Child ([Screenshot](https://3cd.co/4guRqZzv))
([Screenshot of Directory Structure](https://3cd.co/yAunNkoB))

## Expected Behavior
Visiting the site with the active child theme displays the [default Twenty Twenty-Four home page](https://3cd.co/OAu7X4L6) with all styles loaded correctly.

## Actual Behavior
At first, there is a success message "New theme activated. [Visit site](https://github.com/WordPress/twentytwentyfour/issues/733#)"
Reloading the page results in the following error message: "Error: The parent theme is missing. Please install the "twentytwentyfour" parent theme." ([Screenshot](https://3cd.co/xQuN2zbk))
Visiting the site results in a blank white screen where the .wp-site-blocks element is empty. ([Screenshot](https://3cd.co/yAunNkky))

# Potential patch
I added an empty index.php inside parent child theme

***

### Other Notes
This is a fresh, standard WordPress installation (v6.5-alpha-57505)
There are no active plugins on the site.
There are no special directory changes or customizations.

As mentioned before, this is a Multisite install, even if there's no actual secondary website. 
I tested on a non-Multisite instance, and randomly I still have the issue.

I would assume patching WordPress would be more difficult than just dropping a blank index.php file into the theme (and it doesn't appear to have any affect on anything), so maybe as a temporary solution, index.php could be added to block themes?

Or skip the requirement on an index.php at all.

### Environment info

Wordpress 6.5-alpha-57505

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by swissspidy** [comment] 2024-02-01 10:35
Hi there,

as per the previous issue you've opened:

> If this is related to the index.php file missing, then **it is not a problem with the theme, but with WordPress core** and how it detects the parent theme and determines if it is a block theme or classic theme, and **the ticket should be moved to the WordPress trac**.

https://core.trac.wordpress.org/newticket is the right place for reporting bugs in WordPress core.

**Comment by DennysDionigi** [comment] 2024-02-01 11:08
Here I am @swissspidy , thanks :)

Previous one was not mine, but I got it .

Strangely I found this issue only after last update.

**Comment by carolinan** [comment] 2024-02-01 11:24
I  am still not able to reproduce it. I wonder if it depends on os / server / etc.

**Comment by DennysDionigi** [comment] 2024-02-01 11:34
> I am still not able to reproduce it. I wonder if it depends on os / server / etc.

Litespeed. Wp 6.5 alpha, no plugins, multisite enabled.

Any FSE theme, I solved easily adding an index.php - please just check on your side any theme which should not have any (not required on FSE) index.php.

Thanks anyway. 🙂

**Comment by carolinan** [comment] 2024-02-15 09:45
I can reproduce this today on 6.5-beta1-57630
- it doesn't matter if the child theme is a block theme or not
- It doesn't matter if it is  multisite or not

**Comment by carolinan** [comment] 2024-02-15 09:48
I found the following core ticket: https://core.trac.wordpress.org/ticket/60411

**Comment by scruffian** [comment] 2024-02-15 16:41
I have a fix for this here: https://github.com/WordPress/wordpress-develop/pull/6118

**Comment by bgardner** [comment] 2024-02-16 16:33
Let's get this shipped in Beta 2!

**Comment by annezazu** [comment] 2024-02-26 18:23
Closing this out [as a fix was merged](https://core.trac.wordpress.org/changeset/57661)!

**Closed as completed by annezazu** 2024-02-26 18:23 UTC
Labels: [Type] Bug, [Type] WP Core Ticket
