### ISSUE TITLE
Conversion Back to Classic TinyMCE Renders List Item Links Useless

### ISSUE THREAD

**Issue by VR51** [WordPress/gutenberg#9277] opened 2018-08-23 15:10 UTC
When content is copied and pasted from Gutenberg blocks back into a post being edited in the classic TinyMCE editor any links stated as list items (`<li>`) are rendered non clickable when viewed / interacted with in the frontend.

The problem stems from this crap added to the `<ul>` element:

`<ul id="mce_29" class="editor-rich-text__tinymce mce-content-body" role="textbox" contenteditable="true" aria-label="Write list…" aria-autocomplete="list" aria-expanded="false" aria-multiline="true" data-is-placeholder-visible="false">`

**Why would someone need to paste from Gutenberg blocks back into classic 'tinyMCE' editor?**

Because Gutenberg does not play nice in many sites and is apparently designed to not save any content converted from the classic editor into Gutenberg blocks.

[sarcasm alert]

I would bother to whittle down to the exact cause of the error but I don't suppose the Gutenberg devs will even bother to correct the fault so I'm not going to waste my time on it :p 

[/sarcasm alert]

I actually quite like Gutenberg. I'm hopeful for its future. It will eventually replace the need for most plugin settings screens and will replace custom fields. I just wish the devs would pay more attention to the feedback they are getting.

**Comment by designsimply** [comment] 2018-08-23 17:02
Thank you for testing Gutenberg.

> any links stated as list items (<li>) are rendered non clickable when viewed / interacted with in the frontend

I tried the following testing steps based on your description:

1. Create a post in Gutenberg.
1. Add a list block.
1. Add links to the list items.
1. Save the post.
1. Copy the list using the visual editor.
1. Switch to the classic editor.
1. Publish the post.

**Result:** all of the links inside the list I created in and copied from Gutenberg worked normally after pasting the content into the classic editor and then publishing the post.

I suspect my steps might not match exactly with yours. Can you have a look and let me know what I can change in the testing steps?

How are you creating "links stated as list items" exactly? Are you writing that html by hand? Can you include a full example instead of just the `<ul>` part so I can see what you are trying to do?

**Note:** most of the attributes in the `<ul>` snippet you provided are related to accessibility and none should not affect links the way you've described, so it may be something else in how the list items themselves are coded that is the source of the problem.

**Comment by VR51** [comment] 2018-08-23 18:32
Thank you for looking, @designsimply. I'm beginning to suspect the latest Opera browser is at fault re links presented as list items. I'll test in a couple of hours and report back.

**Comment by VR51** [comment] 2018-08-23 22:16
This issue is present in Firefox, Chrome and Opera (which is chrome based).

**Steps to reproduce**

- Create a post in Gutenberg
- Add list of links to the Gutenberg post
- Publish the post
- Create a new post in WordPress by clicking _Edit in Classic Editor_ i.e. use regular old TinyMCE
- Copy the list item content from the Gutenberg block as shown in the Gutenberg editor in the backend of the website and paste the copied list of links into the new post being authored with the Classic Editor. Has to be done this way when Gutenberg fails to save any content into the post i.e. the post content disappears from the editor when the Gutenberg post editor page is reloaded.

**Result**

Any links contained within a `<ul><li></li></ul>` block are non-clickable when copied from a Gutenberg List block into a pre-Gutenberg TinyMCE editor in visual editor mode. `<ul>` blocks copied from the Gutenberg editor contain lots of attributes that interfere with content presented with Gutenberg disabled.

**Images**

**List of links in a Gutenberg List block**

![image](https://user-images.githubusercontent.com/5859901/44554250-253bb300-a728-11e8-9691-bf8248165bf5.png)

**Code view of the Gutenberg block**

![image](https://user-images.githubusercontent.com/5859901/44554345-777cd400-a728-11e8-9ce6-7b446c754838.png)

**Copying the block's content**

![image](https://user-images.githubusercontent.com/5859901/44554438-d93d3e00-a728-11e8-9e81-354a458ccd79.png)

**List items pasted into TinyMCE in visual mode**

![image](https://user-images.githubusercontent.com/5859901/44554379-a09d6480-a728-11e8-9df3-347b374dfac5.png)

**Code view of list items pasted into TinyMCE**

![image](https://user-images.githubusercontent.com/5859901/44554472-01c53800-a729-11e8-99b9-a6aebc0892d2.png)

**Frontend list item links listed in a post written in Gutenberg**

![image](https://user-images.githubusercontent.com/5859901/44554543-4650d380-a729-11e8-89d4-fe070bb98a3b.png)

**Frontend list item links copied from Guttenberg and pasted into a post written in TinyMCE**

![image](https://user-images.githubusercontent.com/5859901/44554617-9af44e80-a729-11e8-9b05-58d886ef97d3.png)

Look at the mouse cursor over 'Apple' in the last two images.

The extra attributes added into the `<ul>` tag by Gutenberg in its visual editor mode makes text copied from Gutenberg to other editors non clickable.

When Gutenberg refuses to save post content it is impossible to switch to code mode to copy the HTML and still retain the post content: Gutenberg deletes everything.

**Comment by designsimply** [comment] 2018-10-16 20:39
@VR51 thank you for re-testing and for the updated testing steps!

I tested with WordPress 4.9.8 and Gutenberg 4.0.0-rc.1 using Firefox 62.0.3 on macOS 10.13.6 by simply using the generated HTML snippet you included in your original post and found that if I add `contenteditable="true"` to the `ul` HTML tag then the links do not work on the front end. However, when I followed the testing steps you provided I didn't see those attributes get added to my HTML and I am not sure how that is happening in your case. I know that several changes have been made since your last reply. Any chance you can try testing this again and let me know if the problem is still happening for you or not? If it is still happening, could you confirm which version of Gutenberg you are testing with. From there, it will be good to try to figure out how/when those extra attributes are getting added! Do you happen to have any plugins installed which modify TinyMCE in any way?

**Comment by VR51** [comment] 2018-10-17 03:52
@designsimply Thanks for testing this. It is possible the issue has resolved itself since I first reported it. I will take a look during the next 24 hours and report back.

**Comment by designsimply** [comment] 2018-11-29 23:24
I tested again with WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6 and couldn't replicate the problem. [(1m6s)](https://cloudup.com/c_pG4EJrvG0)

I'm going to close this issue with a note saying to please re-open if you're still having trouble after upgrading to the latest version of Gutenberg or to WordPress.com 5.0-RC. Please also note your OS and browser versions.

> Copy the list item content from the Gutenberg block as shown in the Gutenberg editor in the backend of the website and paste the copied list of links into the new post being authored with the Classic Editor. Has to be done this way when Gutenberg fails to save any content into the post i.e. the post content disappears from the editor when the Gutenberg post editor page is reloaded.

The last part of that testing step caught my eye this time around. If you're still having trouble with Gutenberg failing to save content into a post, can you tell me a bit more about that issue and also list your active plugins?

**Closed by designsimply** 2018-11-29 23:24 UTC
Labels: Block Conversion, [Block] Classic, [Status] Needs More Info
