### ISSUE TITLE
Widgets editor: blocks do not restore when deactivate plugin > view screen > reactivate plugin

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#31900] opened 2021-05-17 15:59 UTC
## Description
Blocks do not restore ~(are lost / deleted)~ after deactivating the Gutenberg plugin, viewing the Widgets screen, and then reactivating the plugin.

## Step-by-step reproduction instructions
1. Activate the Gutenberg plugin
2. Go to Appearance → Widgets
3. Add a block to a widget area
4. Update
5. Go to Plugins → Installed Plugins
6. Deactivate the Gutenberg plugin
7. Go to Appearance → Widgets => _Don't make any changes to the existing blocks._
8. Go back to Plugins → Installed Plugins
9. Reactivate the Gutenberg plugin
10. Go back to Appearance → Widgets => _Notice the block is gone_.

## Expected behaviour
Block(s) should remain and be displayed when reactivating the Gutenberg plugin.

## Actual behaviour
Block(s) is deleted when viewing the classic Widgets screen (but no changes made to the widgets) after deactivating the Gutenberg plugin.

This behavior does not occur when deactivating and then reactivating the plugin without going to the classic Widgets screen (see in the gif).

## Screenshots or screen recording (optional)
![remove-block-bug](https://user-images.githubusercontent.com/7284611/118519566-db2c6400-b6fe-11eb-83a2-6313d3a0130a.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur
- Browser: Chrome 90.0, Firefox 88.0.1, Safari 14.1

**Comment by hellofromtonya** [comment] 2021-05-17 17:06
Upon further testing, the block is not deleted from the database.

When activating the Classic Widgets plugin after reactivating the Gutenberg plugin, the missing block is now shown in the Inactive Widgets of the classic widgets screen. 

![remove-block-classic-widgets](https://user-images.githubusercontent.com/7284611/118527474-f4391300-b706-11eb-9b97-28125b384468.gif)

Steps to reproduce:
1. Activate the Gutenberg plugin
2. Go to Appearance → Widgets
3. Add a block to a widget area
4. Update
5. Go to Plugins → Installed Plugins
6. Deactivate the Gutenberg plugin
7. Go to Appearance → Widgets => _notice the block is gone_
8. Go back to Plugins → Installed Plugins
9. Reactivate the Gutenberg plugin
10. Activate the Classic Widgets plugin
11. Go to Appearance → Widgets => _notice the block is now available in the Inactive Widgets section_
12. Move the block back to the widget area (skip this step to see if the block is available in the Inactive Widgets section of the Widgets Editor)
13. Go back to Plugins → Installed Plugins
14. Deactivate the Classic Widgets plugin
15. Go back to Appearance → Widgets => _notice the block renders as expected_

What happens when leaving the block in the Inactive Widgets area?
Skip step 12 above. Notice the block is now available in the Widgets Editor inactive widgets section after deactivating the Classic Widgets plugin.

**Comment by noisysocks** [comment] 2021-06-01 05:50
This no longer happens when running Gutenberg against 5.8-alpha because 5.8-alpha has the widgets editor merged into it. I can still reproduce when running Gutenberg against 5.7 though.

**Comment by noisysocks** [comment] 2021-06-01 05:52
Thinking about this some more, I don't think we can fix this. The problem is due to `WP_Widget_Block` not being registered unless the Gutenberg plugin is active. We can't do anything about that unless we add `WP_Widget_Block` to Core which is exactly what we've done for 5.8 🙂

Thanks for testing @hellofromtonya!

**Closed as completed by noisysocks** 2021-06-01 05:52 UTC
Labels: [Type] Bug, [Feature] Widgets Screen
