### ISSUE TITLE
URL UI edit Error

### ISSUE THREAD

**Issue by lumaypl** [WordPress/gutenberg#39020] opened 2022-02-23 13:06 UTC
### Description

There is problem with edit long URL in Guttenberg Editor - details on screenshot:
<img width="975" alt="Zrzut ekranu 2022-02-23 o 13 56 36" src="https://user-images.githubusercontent.com/60925113/155324374-064f9168-ca2c-4c83-a8a6-8081ccd20f37.png">

### Step-by-step reproduction instructions

1. Got to Editor
2. Add long URL for text (more than 60 characters in URL)
3. Try edit URL in visual editor

### Screenshots, screen recording, code snippet

<img width="975" alt="Zrzut ekranu 2022-02-23 o 13 56 36" src="https://user-images.githubusercontent.com/60925113/155325147-1dfd86b6-f1e5-4b71-8055-7102e6fea7ca.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-11-15 02:27
Hi @lumaypl,

I think this is due to a plugin, like #45702. The only option that the core has is "Open in new tab", and no such issues have occurred.

![link_1](https://user-images.githubusercontent.com/54422211/201811216-e95915fd-1b5b-4f9d-a677-cca7dcb1c845.png)

![link_2](https://user-images.githubusercontent.com/54422211/201811226-a5263fc5-0ae8-4d69-96d9-e55dd2c7bbb3.png)

**Comment by ndiego** [comment] 2023-01-31 16:27
Yes, I have confirmed that this issue is caused by third-party plugins hooking into the link modal. I tested with Yoast SEO and was able to generate the same issue. 

I think this needs to be looked at, because if the functionality exists for third parties to add custom content to link popovers, then it should not break the popover. That said, I am not sure of the method that these plugins are using, so perhaps the link popover was simply not designed for this. 

@carolinan would you be able to inquire with Yoast to see how they are inserting the `nofollow` and `sponsored` toggles?

![image](https://user-images.githubusercontent.com/4832319/215820464-a6a9eff1-96b2-4730-a68a-4109b3ba4c5f.png)

**Comment by t-hamano** [comment] 2023-02-01 03:36
From the image provided by @lumaypl , that link UI is probably achieved by the  [Rank Math SEO](https://ja.wordpress.org/plugins/seo-by-rank-math/) plugin. The plugin appears to [disable the core link UI and implements its own format type entirely](https://github.com/rankmath/seo-by-rank-math/blob/ca14e5ce7c85b44798936cf808017e02bac551f9/assets/admin/src/gutenberg/formats/index.js#L14-L15). The Yoast SEO plugin tested by @ndiego also seems to [replace the core link UI](https://github.com/Yoast/wordpress-seo/blob/2d8684764e6e23a620e6690cdd2d09f01042caf8/packages/js/src/inline-links/edit-link.js#L22).

Therefore, I believe that this issue should be resolved on the plugin side.

**Comment by ndiego** [comment] 2023-02-01 12:21
> Therefore, I believe that this issue should be resolved on the plugin side.

Yup, it looks like it. Thanks for digging into this @t-hamano 🙌 

I am going to close out this issue since it cannot be fixed on our end. @lumaypl if you can open a support ticket with whatever plugin you are using that adds those additional options, it would be great if they could update their link UI to match the changes in Core. I am going to add a ticket for Yoast this week.

**Closed as completed by ndiego** 2023-02-01 12:21 UTC
Labels: [Type] Bug, [Feature] Link Editing
