### ISSUE TITLE
 Editor stylesheet CSS specificity issues

### ISSUE THREAD

**Issue by brettsmason** [WordPress/gutenberg#10067] opened 2018-09-20 11:41 UTC
**Describe the bug**
Editor stylesheet CSS specificity issues.

**To Reproduce**
1. Add editor stylesheet as per the documentation.
2. Add a basic heading tag eg `h2`
3. An example of the generated style I'm using which works fine:
```
.editor-block-list__block h2 {
   font-size: 2rem;
   line-height: 1.16666667;
}
```
4. The `line-height` rule is being overruled by a few rules in core with higher specificity:
```
.wp-block-heading h1.editor-rich-text__tinymce, .wp-block-heading h2.editor-rich-text__tinymce, .wp-block-heading h3.editor-rich-text__tinymce {
   line-height: 1.4;
}

.editor-rich-text__tinymce.mce-content-body {
    line-height: 1.8;
}
```

**Expected behavior**
Core styles should have less specificity to allow for an easier time adding a comprehensive custom editor stylesheet.

Could the above rules not be written like:
```
.wp-block-heading h1, .wp-block-heading h2, .wp-block-heading h3 {
   line-height: 1.4;
}

.editor-rich-text__tinymce {
    line-height: 1.8;
}
```
This allows the editor stylesheet to correctly trump the core styles.
This is only a brief example, but I'm sure there are others. I'd be happy to list all problematic styles that I find if it helps.

**Additional context**
Gutenberg 3.8 and WordPress 4.9.8

**Comment by designsimply** [comment] 2018-09-20 13:56
Tested and confirmed with the following steps:

1. Add the following to the theme's functions.php file:

```
add_theme_support( 'editor-styles' );
add_editor_style( 'editor-style.css' );
```
2. Add this to editor-style.css in the theme folder:

```
h2 {
   color: salmon;
   font-size: 4rem;
   line-height: 3;
}
```

**Result:** I expected the line height to be 3 (exaggerated for visibility) and it wasn't.

![screen shot 2018-09-20 at 7 52 19 am](https://user-images.githubusercontent.com/1119271/45823250-85cbfa80-bcaa-11e8-8fe6-f97099020076.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15045&action=edit running WordPress 4.9.8 and Gutenberg 3.9.0-rc.2 using Firefox 62.0 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment] 2018-09-20 14:15
This issue is great for a specific case and to see if we can improve something by continuing the work started in #9008. There is another issue #9534 which asks for feedback related to styling, and I thought I would point you there in case you would like to contribute to that conversation—which is more about critical thinking on the approach for styling on a more general level.

> I'd be happy to list all problematic styles that I find if it helps.

Thanks! Let's ask about this. @youknowriad, would it help to have more examples here?

**Comment by youknowriad** [comment] 2018-09-21 09:08
Yes, this is very useful and I expect we polish this over time. Most of these styles can be resolvers by changing the way they are being applied but we need to do these changes with care. A list of specificity issues would be great to have.

@jasmussen might also be interested in this.

**Comment by m-e-h** [comment] 2018-09-25 21:12
Another unnecessarily specific block is the Code block:

in **block-library/edit-blocks.css** we have:
```
.wp-block-code .editor-plain-text {
    font-family: Menlo,Consolas,monaco,monospace;
    font-size: 14px;
    color: #23282d;
}
```
in **editor/style.css** we have:
```
.gutenberg .editor-plain-text {
    border: none;
    box-shadow: none;
    color: inherit;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    margin: 0;
    padding: 0;
    width: 100%;
}
``` 
Since `.editor-plain-text` is already set to `inherit` *color, font-family,* and *font-size*, we could probably just add the styles to `.wp-block-code` rather than `.wp-block-code .editor-plain-text`

**Comment by m-e-h** [comment] 2018-10-08 20:21
```
.editor-block-list__block ul:not(.wp-block-gallery) {
    list-style-type: disc;
}
```
A little less specific would be:
```
.editor-block-list__block ul {
    list-style-type: disc;
}
.editor-block-list__block .wp-block-gallery {
    list-style-type: none;
}
```

**Comment by chrisvanpatten** [comment] 2018-10-08 20:41
@m-e-h That one in particular has been fixed as of this morning in #10358.

**Comment by celloexpressions** [comment] 2018-10-15 00:16
This should be considered a blocker for API freeze and 5.0. Theme authors can't effectively implement block and editor style support until CSS specificity requirements can be finalized. This also impacts bundled theme updates, which will set the precedent for theme best practices.

**Comment by nickcernis** [comment] 2018-10-15 15:10
Specificity issues are also blocking work we're doing to make existing themes Gutenberg-friendly.

We currently have to add more specific rules for editor widths in order to override default editor block styling when using `add_editor_style( 'editor-style.css' );`.

For example, the CSS in the Gutenberg theme support handbook to [change editor width](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor) looks like this:

```CSS
/* Main column width */
body.gutenberg-editor-page .editor-post-title__block,
body.gutenberg-editor-page .editor-default-block-appender,
body.gutenberg-editor-page .editor-block-list__block {
    max-width: 720px;
}

/* Width of "wide" blocks */
body.gutenberg-editor-page .editor-block-list__block[data-align="wide"] {
    max-width: 1080px;
}

/* Width of "full-wide" blocks */
body.gutenberg-editor-page .editor-block-list__block[data-align="full"] {
    max-width: none;
}
```

But this has no effect when using `add_editor_style( 'editor-style.css' );`, as noted in [this closed issue](https://github.com/WordPress/gutenberg/issues/9894#issuecomment-423189558).

We are currently using more specific rules as a workaround (with an extra `.wp-admin` class):

```CSS
body.wp-admin.gutenberg-editor-page .editor-block-list__block,
body.wp-admin.gutenberg-editor-page .editor-default-block-appender,
body.wp-admin.gutenberg-editor-page .editor-post-title__block {
	max-width: 732px;
}
```

**Comment by youknowriad** [comment] 2018-10-15 15:55
When using `add_editor_style( 'editor-style.css' );` this should be enough:

```css
.wp-block {
	max-width: 732px;
}
```

**Comment by nickcernis** [comment] 2018-10-16 15:04
Thanks, @youknowriad. It looks like additional hacks are also required beyond that to handle block alignment and full-width cases:

https://github.com/WordPress/twentynineteen/blob/de75cbdecdfc95a3309e3420acbaabc4c981e574/style-editor.css#L4-L6

Once a method is finalised it would be good to update the handbook at https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor, which does not currently reflect the `.wp-block` styling or the way Twenty Nineteen is handling block styles.

**Comment by chrisvanpatten** [comment] 2018-10-16 15:40
`body` mapping to `.editor-block-list__block` is definitely an issue; it basically renders the cascade useless for any properties you set inside `body`. I ran into this in #10562, and had to put an override in so nested blocks [inherited `color` from the container block](https://github.com/WordPress/gutenberg/blob/dee2ba204bebee945b3a3d7f996f7098193b67f5/packages/block-library/src/container/editor.scss#L2-L4).

I think it would make more sense for `body` to map to `.edit-post-visual-editor` or `.editor-writing-flow`, and have `.wp-block` map to `.editor-block-list__block` (or something like that).

**Comment by youknowriad** [comment] 2018-10-16 15:59
Agreed we should try to refactor the editor styles to apply to the editor's container instead of the block's wrapper. 

The downside though is that it can affect the UI bits (toolbars, movers...) so we need to be careful there and check for feasibility first.

**Comment by m-e-h** [comment] 2018-10-16 16:32
The UI bits are definitely the issue when scoping beyond the block itself. https://github.com/WordPress/gutenberg/issues/10178

But `.editor-block-list__block` already wraps the UI that would be most problematic. Things like `.editor-block-mover` and `.editor-block-contextual-toolbar`. So moving it to the editor's container shouldn't change too much.

But I think globalizing the CSS scope may be a move in the wrong direction.
I actually created my own PostCSS plugin to narrow the scope even more by wrapping my styles in `[data-block]` or `.editor-block-list__block-edit`.

**Comment by chrisvanpatten** [comment] 2018-10-17 12:10
@m-e-h actually raises a good point, and also we know that the styles are reasonably well scoped because of nested blocks. Otherwise, the styles mapped to `editor-block-list__block` would cascade down into child blocks, but they currently don't.

I think simply changing `body` to map to `edit-post-visual-editor` or similar would likely work more smoothly than we think!

**Comment by chrisvanpatten** [comment] 2018-10-18 19:19
Encountered another case where there are specificity issues:

![web_inspector_ _dev_tomodomo_co_ _post_php](https://user-images.githubusercontent.com/1231306/47178394-1f59ec80-d2e9-11e8-97c3-a0f5f227a4b5.png)

The font size classes are being overridden by the core editor style classes.

**Comment by youknowriad** [comment] 2018-10-19 08:39
I'm planning to try this in the days and see if it's viable

> I think simply changing body to map to edit-post-visual-editor or similar would likely work more smoothly than we think!

**Comment by kjellr** [comment] 2018-10-23 12:20
Leaving a few notes over here from Twenty Nineteen land... There are a few things we've been trying to customize that've been difficult with the current stylesheet setup: 

- In our standard Gutenberg editor styles stylesheet, we've [had to hook into some `[data-align]` properties](https://github.com/WordPress/twentynineteen/blob/master/style-editor.scss#L325) in order to style blocks with different alignments. This doesn't seem totally ideal, but works for now. 
- We aren't yet able to customize styles for the page title (`.editor-post-title__block`, #10485)
- Same with the default appender (`.editor-default-block-appender__content`)
- We are also doing some [alignment changes](https://github.com/WordPress/twentynineteen/pull/22) to match the front-end, and these required hooking into something like `.edit-post-layout` to adjust container margins a little bit. 

Since those last 3 bullets are outside the scope of [the usual injected CSS file](https://github.com/WordPress/twentynineteen/blob/master/style-editor.scss), we've added a [second, un-modified CSS](https://github.com/WordPress/twentynineteen/blob/master/style-editor-frame.scss) file to house those styles. Calling two stylesheets for the editor styles isn't ideal, and we hope to bring those into one, once it's possible to do so.

**Comment by youknowriad** [comment] 2018-10-23 14:32
Thanks all for your input. I opened #10956 which changes the wrapper where we apply the editor styles. Hopefully, this solves a lot of these issues. It doesn't solve everything though.

I'd appreciate some help testing the PR and once we get it, let's try to split this massive issue into discrete issues to ease tracking and solving those. 

Thanks

**Comment by designsimply** [comment] 2018-11-06 00:37
Re-tested with `master` at `70c80680b` and found that `font-size` and `line-height` are still overridden ([screenshot](https://user-images.githubusercontent.com/1119271/48035490-70f3db00-e121-11e8-81ab-87bfe0b67951.png)) for editor styles added using the steps noted at https://github.com/WordPress/gutenberg/issues/10067#issuecomment-423192865. @youknowriad I noticed #10956 was merged (and should be included for my test just now), does that mean this issue should remain open or should it have been solved in #10956 ?

**Comment by kjellr** [comment] 2019-02-13 21:06
```
.editor-rich-text__tinymce.mce-content-body {
    line-height: 1.8;
}
```

^ Just noting that this line height issue should be gone now, as we're no longer using the `mce-content-body` class. #13867 is open to remove that style entirely.

**Comment by youknowriad** [comment] 2019-02-14 07:21
Noting that it would be good to maybe close this issue right now and do smaller ones as we made a lot of improvements recently for these styling issues?

**Comment by jasmussen** [comment] 2019-02-14 07:35
Yep, I think that would be good. Even though we already have many tickets in the repo, I would rather have 10 separate, small tickets, than one meta ticket.

**Comment by samikeijonen** [comment] 2019-02-14 07:42
Can you point all the issues related to this? I'd like to take a closer look.

**Comment by jasmussen** [comment] 2019-02-14 07:44
No, that's the point, these issues would need to be created, one ticket for each issue that hasn't been addressed.

**Comment by tellthemachines** [comment] 2020-04-23 01:45
Is there anything still left to address on this ticket? I notice that the issues described on the description have been fixed, as well as the ones mentioned on [this comment](https://github.com/WordPress/gutenberg/issues/10067#issuecomment-423471998), [this comment](https://github.com/WordPress/gutenberg/issues/10067#issuecomment-424503170), [this comment](https://github.com/WordPress/gutenberg/issues/10067#issuecomment-427966542) and [this comment](https://github.com/WordPress/gutenberg/issues/10067#issuecomment-429893279). 

We should, in any case, create new tickets for any remaining issues before we close this one. But my question here is _if there are any remaining issues_, among the ones mentioned on this ticket, to be addressed.

**Comment by jasmussen** [comment] 2020-04-23 07:55
@tellthemachines I would tend to agree, good assessment. It's very easy to reopen this ticket if we close it in error, people can comment and ask it reopened and we will. So I'll go ahead and close it and direct to https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Custom%20Editor%20Styles, which is usually the best source for specific editor specificity issues. Thanks everyone!

**Closed by jasmussen** 2020-04-23 07:55 UTC
Labels: CSS Styling, Customization, Good First Issue, [Feature] Custom Editor Styles, [Status] In Progress, [Type] Enhancement
