### ISSUE TITLE
FSE Theme: Custom Templates Drop-Down (Returning name, not title)

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#35550] opened 2021-10-12 13:05 UTC
### Description

I am developing a FSE theme and have a Custom Template with a file name page-no-title.html, which resides in the theme's /block-templates/ folder. In my theme.json file, I have registered it:

```
{
"version": 1,
	"customTemplates": [
		{
			"name": "page-no-title",
			"title": "Page No Title"
		}
	]
}
```

When I add a page and select the Template drop down (happens on edit/quick edit screens), the template is listed, though it appears to be output as the file name (page-no-title) as opposed to the title (Page No Title). 

### Step-by-step reproduction instructions

1. Add new page.
2. Go to Template section in the right sidebar and select the drop down.
3. See list of templates.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/486261/136960867-f350cabe-fd05-4f77-85fe-eedc961c601d.png)

![image](https://user-images.githubusercontent.com/486261/136961190-dae95ec7-3a19-41f4-bb17-7f8beb76f71a.png)

### Environment info

WordPress 5.8.1, Gutenberg 11.6.0, Chrome browser.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2021-10-12 13:59
Thanks for contributing, @bgardner.

I think this is a duplicate of #32818.

**Comment by kjellr** [comment] 2021-10-12 14:25
Yeah, I think this one is a duplicate. It looks like that issue covers the notes from here, but if I missed anything new, feel free to add it over in #32818. Thanks!

**Closed as completed by kjellr** 2021-10-12 14:25 UTC
Labels: [Type] Bug, [Status] Duplicate

**Comment by bgardner** [comment] 2021-10-12 14:30
Eeek, sorry for the dupe. I tried search and could not find anything.
