### ISSUE TITLE
Enqueue styles with hook `enqueue_block_editor_assets` not working on Gutenberg 13.0

### ISSUE THREAD

**Issue by suyogagitayana** [WordPress/gutenberg#40603] opened 2022-04-26 03:44 UTC
### Description

On WordPress 5.9.x with Gutenberg 13.0 activated, when other plugin enqueue styles using the action hook `enqueue_block_editor_assets`, the enqueued styles didn't show up inside the FSE iframe.
This is not the case if Gutenberg 13.0 is not activated.

Need more confirmation on this issue just in case if i did my implementation wrong or there is a new way to enqueue styles inside FSE iframe on Gutenberg 13.0.

At the section below `Please confirm that you have tested with all plugins deactivated except Gutenberg.`
I set it to no because technically i need to use a custom plugin for testing.

### Step-by-step reproduction instructions

1. Use WordPress 5.9.x but don't activate Gutenberg 13.0
2. Enqueue a css file using the action hook `enqueue_block_editor_assets`
3. Check on the FSE, your file will be enqueued inside the iframe.
4. Now activate Gutenberg 13.0, and check FSE again, the file now not enqueued.

### Screenshots, screen recording, code snippet

Enqueue style
<img width="727" alt="Screen Shot 2022-04-26 at 11 22 20" src="https://user-images.githubusercontent.com/48169787/165213849-e9130725-8c58-4379-ac30-43838684303e.png">

With only WordPress 5.9, no Gutenberg 13.0
<img width="424" alt="Screen Shot 2022-04-26 at 11 09 54" src="https://user-images.githubusercontent.com/48169787/165213061-ef52d1eb-17cb-4caf-a435-ef88ef8ff509.png">

With WordPress 5.9 and Gutenberg 13.0, the enqueued file missing
<img width="417" alt="Screen Shot 2022-04-26 at 11 11 11" src="https://user-images.githubusercontent.com/48169787/165213071-6ad41ed1-cf32-4870-987e-3f896aa756ec.png">

### Environment info

- WordPress version : 5.9.x
- Gutenberg version : 13.0
- Theme : Any FSE theme
- Chromium based browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by nextgenthemes** [comment] 2022-04-26 20:19
You can use `add_editor_style` like the TT2 theme uses. I lost time over this, it's not documented, and I am not sure if this is intended.

Did you find out that `enqueue_block_editor_assets` still works post editing mode? Does it work for the frontend?

**Comment by nextgenthemes** [comment] 2022-04-26 21:36
I can confirm it's not working at all from TT2 theme, not even in post editor or frontend. And not with GB 13.1.0-rc.1 either.

Added this to TT2 functions.php
```
add_action( 'enqueue_block_editor_assets', 'tt2test' );

function tt2test() {

	wp_register_style(
		'tt2test',
		get_template_directory_uri() . '/style.css',
		array(),
		'versionstring'
	);

	wp_enqueue_style( 'tt2test' );
}
```

and commented these 2 lines out: 

```
//add_editor_style( 'style.css' );`.

//add_action( 'wp_enqueue_scripts', 'twentytwentytwo_styles' );
```

**Comment by suyogagitayana** [comment] 2022-04-27 01:29
> Did you find out that `enqueue_block_editor_assets` still works post editing mode? Does it work for the frontend?

I think `enqueue_block_editor_assets` is an action hook for the editor only, i don't think it supposed to work on frontend.

What confused me is that i'm not sure if this hook supposed to enqueue assets inside the editor **iframe** (full site editor) or not because previously enqueuing assets using this hook worked, but now it's not if Gutenberg 13.0 activated.

The assets only not enqueued inside the iframe, it's still enqueued inside root html head.

**Comment by nextgenthemes** [comment] 2022-04-28 14:34
I had an error in my code, it actually _does_ work, just not as expected, maybe it's intended. 

`enqueue_block_editor_assets` loads the CSS on the top level document of the FSE. And `add_editor_style()` injects it inside the iframe for the site.

**Comment by suyogagitayana** [comment] 2022-04-29 01:45
> `enqueue_block_editor_assets` loads the CSS on the top level document of the FSE. And `add_editor_style()` injects it inside the iframe for the site.

Yes, it does work for themes but I was talking about enqueuing custom css files from the plugin.
It still doesn't work.

Previously discussed in this issue #38673, we need to have a `.editor-style-wrapper` or `.wp-block` selector inside the css file so the file will be enqueued inside the iframe.

Here's the comment which explains it. You can find the whole code in `gutenberg/packages/block-editor/src/components/iframe/index.js`.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/48169787/165872832-380cf51d-2304-41df-8898-d1a06ff9656c.png">

And yes it does indeed work when we have those selectors inside the css file, **but** now after Gutenberg 13.0 it is no longer working and I'm not sure why.

Am I missing something?

**Comment by priethor** [comment] 2022-05-04 14:32
Hi @suyogagitayana , thanks for reporting this issue!

It appears the underlying issue here is the same as #40469, which is being worked on. If you don't mind, let's close this issue so that contributors have better clarity on what bug fixes need to be fixed and we don't duplicate efforts. The context provided here is very helpful for solving the issue! 🙏

**Closed as completed by priethor** 2022-05-04 14:32 UTC
Labels: [Type] Bug, [Type] Regression, [Status] Duplicate, [Feature] Themes, [Feature] Site Editor
