### ISSUE TITLE
Unable to copy/paste text without block boundary comments

### ISSUE THREAD

**Issue by scottybo** [WordPress/gutenberg#9018] opened 2018-08-15 14:16 UTC
**Describe the bug**
When writing content I hit enter for a new paragraph which creates a new paragraph block. However if I then want to copy/paste what I've written my clipboard contains the text PLUS the comment tags.

**To Reproduce**
1. Go to the editor and add a paragraph block
2. Start typing and then hit enter (repeat for a few paragraphs)
3. Select all the paragraphs and do CTRL-C
4. CTRL-V into notepad

**Expected behavior**
Just copy my text please...

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by tofumatt** [comment] 2018-08-15 14:54
To be clear, when you copy text it includes the HTML comments used to denote a Gutenberg block, correct?

eg:

```html
<!-- wp:paragraph -->
<p>My text.</p>
<!-- /wp:paragraph -->
```

right?

**Comment by scottybo** [comment] 2018-08-15 14:57
Correct

**Comment by designsimply** [comment] 2018-08-15 17:03
I tested with WordPress 4.9.8 and Gutenberg 3.5.0 and Firefox 61.0.2 on macOS 10.13.6 and confirmed that Gutenberg HTML block comments are copied into the clipboard when using the "Copy All Content" option in the More menu in the top toolbar or if I select multiple blocks at once but they are not included if I copy content from a single block.

My understanding is that this is by design to allow content to be copied from one post to another using the visual editor without losing block information.

@scottybo may I ask your use case and what your reasons are for wanting to leave the block boundary comments out of copied content and what you think about the balance on being able to copy and paste content as blocks within the Gutenberg editor versus elsewhere?

**Comment by scottybo** [comment] 2018-08-15 17:39
Personally? I might be copying and pasting into Word for spell checks, for feedback (sharing in an email), for copying snippets into social media. There are loads of use cases that I'm sure others need for basic copy paste functionality.

**Comment by aduth** [comment] 2018-08-21 15:56
Noting that there is some intentionality to this, originally implemented in #1013 and #1331. The content of the paragraphs are markup, and a similar expectation exists that one can copy the content from one post to another editor session and preserve the same formatting.

This can tie in to some similar discussions about:

- Does a paragraph block need the comment demarcations? For non-default-formatting, the answer is yes. 
- Gutenberg's avoidance of [`wpautop`](https://developer.wordpress.org/reference/functions/wpautop/)

**Comment by tofumatt** [comment] 2018-08-21 19:07
Sounds like this is working as intended. If you had more than plain text content the HTML would preserve it, so this approach makes sense.

I can see the use case of wanting to copy *only* the text from the post, but that sounds like a new feature (a "copy as plain text" button). I don't think it fits into the common use-case for multi-block copy/paste and would be better-suited to a Gutenberg editor plugin.

I think a "Copy as plaintext" plugin would do the trick here but I don't see it as being part of the core Gutenberg experience, so I'm closing this one as a won't fix.

**Comment by pento** [comment] 2018-10-07 23:33
Reopening, as this appears to be a bug. `CopyHandler` sets both the `text/plain` and the `text/html` MIME types to be the serialised content, which is incorrect for `text/plain` (which should just be the text content), and correct-but-inaccurate for `text/html` (which doesn't need the block demarcations).

I'm inclined to have multiple data formats:

`text/plain`: Text content, all block demarcations and HTML stripped.
`text/html`: HTML content, with block demarcations comments stripped. This improves the behaviour of pasting block content into the Classic Editor, too.
`application/vnd.wordpress.block+json`: The unserialised JSON blob of blocks, which we can use when pasting into Gutenberg.

@iseulde: I could tell from #1013 why `text/plain` is set to include the HTML, can you confirm what's going on?

**Comment by iseulde** [comment] 2018-10-08 11:49
@pento Sounds good to me, as long as there is a way to copy the HTML content including HTML comments to some other application. I guess that is still possible by copying the contents of the code editor. Also, what should the copy all button do in your opinion? Should it depend on the editor you're in?

**Comment by pento** [comment] 2018-10-09 01:34
Other applications should be able to access the `application/vnd.wordpress.block+json` data, native clipboard APIs provide that functionality, and I assume browsers pass that data into the native clipboard correctly. We could add a `application/vnd.wordpress.block+html` type, too, which would contain the string the `serialize()` returns (the string that's currently put into `text/plain` and `text/html`), if native applications want the HTML-ified version, instead.

I think Copy All should have the same behaviour as if you press Cmd+A, Cmd+C. In the Visual Editor, that would be the same as above. In the Code Editor, it should put the HTML content (including HTML comments) into `text/plain`.

**Comment by mtias** [comment] 2018-11-13 19:01
@pento @iseulde what is the status of this one? Also have to consider copying content to paste in the same editor to create a new block.

In the future, it might be nice to evolve the "Copy All" to be a flyout "Export" menu including options for copying with all attributes, copying just the visual render, and even downloading an HTML version.

There's also the option of opening "preview" and copying from there (which doesn't include comments).

**Comment by mcsf** [comment] 2018-11-13 19:59
> I'm inclined to have multiple data formats:
> 
> `text/plain`: Text content, all block demarcations and HTML stripped.
> `text/html`: HTML content, with block demarcations comments stripped. This improves the behaviour of pasting block content into the Classic Editor, too.
> `application/vnd.wordpress.block+json`: The unserialised JSON blob of blocks, which we can use when pasting into Gutenberg.

This is pretty much what I had in mind, at least when using the native Copy action. (I don't think expecting third-party apps to look at `application/vnd.wordpress.block+json` is realistic yet, but at least the format is there for Gutenberg itself and, perhaps in the future, any specialised processing tool that looks for it.) I'm undecided on whether the Copy All Content button should follow this behavior, or whether it should still copy the boundaries onto the `text/*` formats.

**Comment by askel45** [comment] 2020-09-13 16:35
> I might be copying and pasting into Word for spell checks

This is also a usage case for me. Would be glad if this feature was implemented.

**Comment by paaljoachim** [comment] 2021-02-20 21:00
With WordPress 5.7 beta 3.
Gutenberg plugin 10.
Twenty Twenty One.

To Reproduce
Steps to reproduce the behavior:

1. Go to the editor and add a paragraph block
2. Start typing and then hit enter (repeat for a few paragraphs)
3. Select all the paragraphs and do CTRL-C
4. CTRL-V into notepad

I added a few paragraph blocks with text. Selected all the paragraphs and did a CTRL-C. Then into TextEdit did a CTRL-V.
Only the text was copied in. Based on the issue initially created I would say that this issue is solved, and should be closed.
If there are other concerns that have not been solved then I assume these should be opened in new issues.

Can we go ahead and close this issue?

**Comment by thomashigginbotham** [comment] 2021-02-25 19:48
I followed the same steps as @paaljoachim, but in Windows 10, Notepad, and WordPress 5.6.2.

Pasting into Notepad includes the comments and paragraph tags:


<p>Paragraph 1</p>



<p>And two</p>



<p>And three</p>

**Comment by gwwar** [comment] 2021-02-25 19:49
@pento @mcsf do you think we have any follow up tasks here, or is this okay to close?

**Comment by smwcollege** [comment] 2021-02-25 19:51
with WordPress 5.6.2
Gutenberg 10
Twenty Twenty One
Windows 10

In notepad:
![image](https://user-images.githubusercontent.com/42584667/109208759-b7e5be80-7778-11eb-87de-451ab6e93c04.png)

In MS Word:
![image](https://user-images.githubusercontent.com/42584667/109208775-c03df980-7778-11eb-93e1-791b11a1f36c.png)

Agreed with the comments above, this seems to be an issue with notepad only using plaintext, since copy-pasting the Gutenberg formatting is a core feature.

**Comment by pento** [comment] 2021-03-02 04:48
By default, TextEdit is not a plaintext editor, it appears to use the `text/html` data for pasting. To demonstrate, if you add formatting to some of the text in Gutenberg, this will also be pasted into TextEdit. As an alternative demonstration, if you use MacOS' "Paste and Match Style" option, it will use the `text/plain` data, and reproduce this issue even in TextEdit.

To answer your question, @gwwar, my [earlier summary](https://github.com/WordPress/gutenberg/issues/9018#issuecomment-427696469) is still valid, there have been no changes to address the original issue that I'm aware of.

**Comment by gwwar** [comment] 2021-03-02 15:24
Thanks for the extra context @pento! We'll keep this one open

**Comment by Mamaduka** [comment] 2022-09-02 17:01
Hi, everyone

I'm no longer able to reproduce the issue.

## My testing steps

* Used example content (see below)
* Selected all blocks - CMD + A + A.
* Copied selected blocks - CMD + C
* Pasted in different editors using CMD + V.

Tested editors: Notes, TextEdit, VSCode, Gmail, Google Docs, Github's comment textarea.

## Example content

```
<!-- wp:paragraph -->
<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Example</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
<!-- /wp:paragraph -->
```

**Comment by Mamaduka** [comment] 2022-09-26 07:56
I'm going to close the issue. I can no longer reproduce it.

Feel free to re-open it if you're still experiencing the problem.

**Closed by Mamaduka** 2022-09-26 07:56 UTC
Labels: [Type] Bug, [Feature] Raw Handling

**Comment by phy25** [comment] 2022-10-03 02:22
This is still an issue for me on Windows Chrome and Firefox, WordPress 6.0.2, when I pasted "select all" content into GitHub comments, VSCode, and the Windows Textpad, that they contain the Gutenberg HTML comment.

I will comment back if I can reproduce it on another OS.

**Comment by Mamaduka** [comment] 2022-10-03 05:02
Thanks for the update, @phy25.

Have you tried testing with Gutenberg plugin active?

It would be great to narrow down the issue to OS or WP versions.

**Comment by phy25** [comment] 2022-10-11 03:16
Thanks. So I can reproduce this with Gutenberg 14.2.0, in both Windows Chrome and macOS Chrome. When I paste it to a plaintext textbox (e.g. GitHub search bar) it's giving me those extra tags.

**Comment by phy25** [comment] 2022-10-11 03:38
I am not sure if https://wordpress.org/gutenberg/ is always reflecting the latest editor, but I can reproduce the issue even there on Windows Chrome.
