### ISSUE TITLE
Open in new tab, removes the link from my content

### ISSUE THREAD

**Issue by AbuAlKarmi** [WordPress/gutenberg#19363] opened 2019-12-30 08:45 UTC
**Describe the bug**
I have a content that available on Google Docs Document, the content has links inside, I copied the content, pasted it inside new article, I went over the links and update them to open in new tab, the link removed from the content. 
Notes: I have the Arabic version of Wordpress v5.2.2

**To reproduce**
1. Copy a content from Google Docs that has links
2. Go to link, and change it to "Open in new Tab" option
3. The link removed

**Expected behavior**
The link to stay and open in new tab

**Screenshots**
<a target="_blank" href="https://ibb.co/7ppYSNJ"><img src="https://i.ibb.co/7ppYSNJ/ezgif-4-ed3b856f0889.gif" alt="ezgif-4-ed3b856f0889" border="0"></a>

**Desktop (please complete the following information):**
 - OS: [macOS v10.15.2]
 - Browser [chrome]
 - Version [79.0.3945.88]

**Comment by youknowriad** [comment] 2020-01-13 13:44
Hi There!

I can't reproduce the issue, would you mind sharing an example of post content to reproduce it?

Thanks.

**Comment by AbuAlKarmi** [comment] 2020-01-19 07:56
@youknowriad Thanks for the help, 
here is an example of the content that I'm trying to import [ [https://docs.google.com/document/d/1awb7xNqHcxqt7EQsZIPdU2DnCQ0N9Of97xtnCoB4xNM/edit?usp=sharing](Here) ]

**Comment by youknowriad** [comment] 2020-01-20 08:48
Hi There!

I just tried with that content and I was not able to reproduce either. Maybe it's a plugin conflict, do you have other plugins that could cause this? Can you try disabling one by one?

In the meantime, I'm going to close this issue as it doesn't appear to be a Gutenberg issue.

Thanks

**Closed by youknowriad** 2020-01-20 08:48 UTC
Labels: [Status] Needs More Info
