### ISSUE TITLE
Navigation screen: Clicking outside the Navigation block should close any open submenus

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24808] opened 2020-08-26 01:47 UTC
Split out from https://github.com/WordPress/gutenberg/issues/24760.

When a submenu is open, clicking outside the Navigation block should close the submenu. This can be done by selecting the Navigation block.

![click-outside](https://user-images.githubusercontent.com/612155/91245817-be778700-e791-11ea-8f2b-a895aa9e475e.gif)

**Comment by noisysocks** [comment] 2020-08-28 06:41
https://github.com/WordPress/gutenberg/issues/24875 may make this unnecessary.

**Comment by talldan** [comment] 2021-01-19 06:18
Duplicate of #22626

**Closed by talldan** 2021-01-19 06:18 UTC
Labels: [Feature] Navigation Screen, [Type] Bug
