### ISSUE TITLE
Article preview doesn't work with Firefox

### ISSUE THREAD

**Issue by locksoft** [WordPress/gutenberg#13968] opened 2019-02-20 12:15 UTC
**Describe the bug**
While in other browsers, like Safari, previews works correctly, it doesn't on Firefox.
The page gets reloaded but contents aren't changes. After like 5-6 manual refreshes it may work but it's a so long procedure it's faster to save the article and check it directly.
But, of course, it's not the best way.
The preview problem doesn't appears at all in classic editor. It works perfectly there.
Gutenberg version I'm using is 5.1.0.

**To Reproduce**
Edit an article and press "Preview".

**Expected behavior**
Have the preview page showing the new changes.

**Screenshots**
--

**Desktop (please complete the following information):**
- OS: MacOs High Sierra version 10.13.6
- Browser Firefox version 65.0.1

**Smartphone (please complete the following information):**
--

**Additional context**
--

**Comment by youknowriad** [comment] 2019-02-20 12:50
Closing as a duplicate of #13232

**Closed by youknowriad** 2019-02-20 12:50 UTC
