### ISSUE TITLE
Issue in post/page Update success message

### ISSUE THREAD

**Issue by 1naveengiri** [WordPress/gutenberg#5915] opened 2018-03-30 20:22 UTC
## Issue Overview

I have faced two issues or improvement we can say here. 

1. Success message got before the post update completed. 

2. While Updating page it still showed a message **post updated..!**
for non-technical person post and page are two different things. 

## Steps to Reproduce (for bugs)

1. Go in page section
2. click on edit link to edit  a page 
3. Click on Update button above once done with Update
4. check the success message **Post updated! View post**
and update button behavior  

## Expected Behavior

1. It should show success message when the update button is stable, or page is completely saved.
2. should show message **Page updated! View page** When the page is updated. 
because for non-technical person page and post are two different things. 
they are not aware of post_type => page or post :D

## Screenshots / Video

https://drive.google.com/file/d/1006iagR4BtbRhL7_NDF3DpgJ6YTRFV5p/view

**Comment by SuperGeniusZeb** [comment] 2018-03-30 22:34
This is a duplicate of #5877.

**Comment by 1naveengiri** [comment] 2018-03-31 05:38
What about 1st issue.

**Comment by SuperGeniusZeb** [comment] 2018-03-31 06:18
Oops, I missed that part of the issue. But as it turns out, that issue is also already reported in #5868.

Also, I recommend creating separate issues for different problems like these. They do not belong in a single report as they are two separate bugs that do not affect each other and can be fixed independently of each other.

**Comment by karmatosed** [comment] 2018-04-01 09:47
I am going to close this as yes it seems already reported. Thanks.

**Closed by karmatosed** 2018-04-01 09:47 UTC
