### ISSUE TITLE
Removing block alignment makes toolbar disappear

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#21799] opened 2020-04-22 18:29 UTC
**Describe the bug**
If I remove a block alignment (not text alignment) by clicking the selected alignment, the toolbar disappears. It does not come back until I click outside of the block and then select it again. This is different than the behavior of _changing_ block alignment or applying any other format where the toolbar stays visible. Therefore, this is a bug :)

**To reproduce**
1. Click a block
2. Give it an alignment (left, center, right, wide full)
3. Click the same alignment to remove that selection
4. Toolbar disappears

**Expected behavior**
Toolbar remains visible so I can continue with another action or continue adjusting alignment.

**Screenshots**
![animated GIF demonstrating the described but](https://user-images.githubusercontent.com/1238696/80018925-9f878200-848b-11ea-8c23-3bf7451bf9f1.gif)

**Editor version (please complete the following information):**
WordPress 5.4, no Gutenberg

**Desktop (please complete the following information):**
Win 10, Firefox 76.05b

**Comment by talldan** [comment] 2020-04-23 02:12
I couldn't reproduce this in the latest version:
![alignment](https://user-images.githubusercontent.com/677833/80051462-c6f15400-854a-11ea-9a66-2882a39fc654.gif)

@mrwweb Is this something you'd be able to re-test with the latest version of the plugin installed?

**Comment by mrwweb** [comment] 2020-04-23 17:40
Confirmed what @talldan reported. This is the behavior in WordPress 5.4 but not Gutenberg 7.9.1.

**Comment by talldan** [comment] 2020-04-24 02:54
Thanks for testing. I'll close the issue as those improvements will eventually make their way into WP core.

**Closed by talldan** 2020-04-24 02:54 UTC
Labels: Needs Testing
