### ISSUE TITLE
Updating Failed and Publishing failed

### ISSUE THREAD

**Issue by khanhquocnguyen** [WordPress/gutenberg#16009] opened 2019-06-05 17:07 UTC
**Describe the bug**
I created a website with (fresh installation, no wordpress plugin was added):

- Wordpress 5.2.1
- Nginx 1.14.0
- Ubuntu 18.04
- MariaDB 10.1.38
- PHP 7.2.17

I can not publish (Publishing failed) a new page or edit an existing page (Updating Failed).

**To reproduce**
Those errors happen when Permalink Settings is any format except Plain.

**Screenshots**

Edit an existing page :
![edit](https://user-images.githubusercontent.com/13175175/58975088-4f112280-87ee-11e9-869a-70f8c70624d8.PNG)

Publish a new page:
![add](https://user-images.githubusercontent.com/13175175/58977221-728a9c00-87f3-11e9-8095-e66d9e59c959.PNG)

**Additional information: **
If we back to the **Classic Editor**, those error will be fixed.

**Comment by draganescu** [comment] 2020-04-22 13:24
Hi there @khanhquocnguyen with WordPress 5.4 and Gutenberg 7.9.1 I was unable to reproduce this bug. I will close this as it appears fixed or not a problem. Thank you!

**Closed by draganescu** 2020-04-22 13:24 UTC
Labels: [Feature] REST API Interaction
