### ISSUE TITLE
Editor cursor overlap while switching the section through popover 

### ISSUE THREAD

**Issue by abdullah1908** [WordPress/gutenberg#5157] opened 2018-02-20 06:55 UTC
## Issue Overview
Editor cursor overlap while switching the section through popover in Microsoft Edge

## Steps to Reproduce (for bugs)
1. Publish a Gutenberg demo post 
2. Click on the content structure (info bar icon)
3. Move to the different heading section and see the cursor  
4. For more details see attached video below

Browser: 
Microsoft Edge _41.16299.248.0_
Microsoft EdgeHTML _16.16299_
Gutenberg: _2.2_ 
WordPress: _4.9.4_
## Expected Behavior
Cursor shouldn't be overlapped while switching the different heading section 

## Current Behavior
The cursor is overlapped with the popover. See attached video.

## Possible Solution
Reason: Cross Browser Compatibility Issue in Microsoft Edge

## Screenshots / Video
![gutenberg-cursor overlapping issue with popover content structure](https://user-images.githubusercontent.com/14175927/36410330-4c4ebaa0-1632-11e8-9a27-40b76fda62fa.gif)

**Comment by designsimply** [comment] 2018-07-09 22:46
Tested and confirmed using Edge 17 on Windows 10 via browserstack.com that I can see the cursor prompt on top of the Content Structure window if I click the document info icon (i) and then "Title" and move the cursor underneath the Content Structure window using the keyboard.

![screen shot 2018-07-09 at mon jul 9 4 39 51 pm](https://user-images.githubusercontent.com/1119271/42479692-46f53188-8397-11e8-9385-dc908cb2f059.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php?gutenberg-demo running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by adamziel** [comment] 2020-04-20 12:23
This seems to be Edge issue, potentially a [legacy issue form IE](https://stackoverflow.com/questions/27864884/cursor-caret-bleeding-through-overlay-in-ie). I was able to reproduce it with Edge 17. The recommended fix seems to be just ensuring that it's not possible to write in that field when an overlay is visible. It seems like that's what we started doing at some point - I had to copy and paste HTML using devtools in order to actually see the overlay while typing. Another good news is that Edge switched to WebKit recently, and the issue is no longer reproducible in Edge 81. It seems like no further action is required so I am going to close this one - feel free to reopen if needed.

**Closed by adamziel** 2020-04-20 12:23 UTC
Labels: Browser Issues, [Priority] Low, [Type] Bug
