### ISSUE TITLE
Paste: Markdown parsing fails in Chrome if any HTML is present

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#4256] opened 2018-01-03 15:29 UTC
## Issue Overview

See https://github.com/WordPress/gutenberg/pull/4232#discussion_r159262078.

This is because Chrome does not encode HTML inside a plain text string that it gets when creating an HTML version in the clipboard. If the HTML is not encoded, the HTML version will fail the `isPlain` check.

## Steps to Reproduce (for bugs)
Paste the following from a plain text field into Gutenberg.

```md
* one
* two <em>test</em>
* three
```

This will work in Safari, but fail in Chrome.

**Comment by kevinfodness** [comment] 2018-02-01 03:03
I believe I'm encountering this bug when I try to paste content from Word for Mac. It works in Safari, but fails in Chrome. macOS 10.12.6, Chrome 64.0.3282.119, Word 16.9.1. The test string was one paragraph that included some bold and italic text.

**Comment by kevinfodness** [comment] 2018-02-01 03:05
Specifically, the behavior in Chrome is that the paste converts to an image of the text. It's possible that this is a different bug entirely, but this issue seemed to be the closest match to the behavior I'm experiencing.

**Comment by kevinfodness** [comment] 2018-02-05 15:53
A more specific issue has been created to track the paste from Word problem in #4854.

**Comment by iseulde** [comment] 2018-02-05 18:34
@kevinfodness Thanks! That seems indeed like a different issue.

**Comment by iseulde** [comment] 2018-02-06 09:28
This one is not. It is different from the one that you reported in #4854. That one has a fix, but it's not merged yet.

**Comment by brandonpayton** [comment] 2018-09-03 09:44
Hi @iseulde, I'm not able to reproduce this today with Gutenberg `master` and Chrome 68 on macOS 10.13. Here's what I'm doing to test. Does this appear to be fixed now?

![markdown-parse-in-chrome](https://user-images.githubusercontent.com/530877/44979909-4db48000-af66-11e8-91a9-ad70b3edfbaa.gif)

**Comment by designsimply** [comment] 2018-11-01 21:29
Closing because I tested with WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Chrome 70.0.3538.77 on macOS 10.13.6 and, similar to @brandonpayton, I was not able to reproduce the bug.

**Closed** 2018-11-01 21:30 UTC
Labels: Priority Low, [Component] Raw Handling, [Type] Bug
