### ISSUE TITLE
[Widgets Screen] Allow for a holistic Preview option

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26182] opened 2020-10-16 00:31 UTC
**Is your feature request related to a problem? Please describe.**

Right now, one can individually preview legacy blocks in the Widgets Screen but if you want to see the entire section previewed with a mix of legacy widgets and blocks, you can't unless you individually preview each legacy widget. 

**Describe the solution you'd like**

I'd love an option to preview in one fell swoop without having to update the widgets screen and seeing what it looks like. Similar to the flow with previewing a post, it would be great to have this option especially with the customizer flow unable to work with blocks in a way that one might usually preview changes to the widgets. 

Here's a hacky design stolen from the preview button you see when adding a new post:

<img width="1248" alt="Screen Shot 2020-10-15 at 6 30 57 PM" src="https://user-images.githubusercontent.com/26996883/96199427-ae1f9500-0f14-11eb-9a74-0be5377fde3a.png">

I would expect when clicking on this that it would automatically show the preview for every legacy widget alongside the blocks.

**Comment by annezazu** [comment] 2020-10-17 03:12
For even more feedback on this, here's a copy and paste from here (props @garretthyder ) https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40072

> It would be nice to introduce a preview capability to the sidebar sections as a whole so you can preview the entire sidebar to see how the widgets interact visually without having to click each one’s Preview individually. Ideally, once the widget form is filled in, I’d like it so that the widget defaults to the Preview mode when unselected. This would provide more of a Gutenberg feel. It would be nice to either default the widget blocks to preview mode, or provide a preview ability to view ALL blocks in preview.

**Comment by paaljoachim** [comment] 2020-10-19 20:49
I think it is a very good idea to use the preview button which would then automatically shift all widgets over to a preview mode.

**Comment by paaljoachim** [comment] 2020-10-19 21:12
Hey @annezazu 
@enriquesanchez opened this issue 11 days ago: https://github.com/WordPress/gutenberg/issues/25960 which is very similar to the issue you made here. The question becomes should we close the issue you opened and continue discussion in 25960?

**Comment by annezazu** [comment] 2020-10-19 23:26
I think the two issues are a bit separate. One is about the general, individual block preview behavior whereas this is about being able to preview everything at once. I don't feel strongly though so happy to have this closed if it's better!

**Comment by enriquesanchez** [comment] 2020-10-22 21:38
@paaljoachim @annezazu Agreed that these two are related but separate issues. I think both should remain open.

**Comment by mapk** [comment] 2020-11-09 21:05
As I mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/25960#issuecomment-712431106), if we forced the Legacy Widget to show the preview state when unselected, it would resolve this issue as well. But the Legacy Widget would only show the Preview if there was enough info filled out in the widget's form to display the preview correctly.

**Comment by noisysocks** [comment] 2021-04-19 04:15
I would very much like the Widgets screen to have an actual _Preview_ button which opens the frontend of your site in a new tab with your unpublished changes. This can be implemented using Customizer changesets. See https://github.com/WordPress/gutenberg/issues/26012. 

It's a significant undertaking though and not something that I think is necessary for WordPress 5.8 given that we will be defaulting all of the Legacy Widget blocks to show a preview as @mapk says above. See https://github.com/WordPress/gutenberg/issues/26179.

So, closing this as "maybe later" / "duplicate of https://github.com/WordPress/gutenberg/issues/26012". Thanks for the discussion and ideas everyone.

**Closed by noisysocks** 2021-04-19 04:15 UTC
Labels: Needs Design Feedback, Needs Technical Feedback, [Block] Legacy Widget, [Feature] Widgets Screen, [Type] Enhancement
