### ISSUE TITLE
Image Block: Manually resizing a square image distortion

### ISSUE THREAD

**Issue by mikeicode** [WordPress/gutenberg#28927] opened 2021-02-10 19:52 UTC
## Description

If you crop an image to a square and then manually resize by dragging the image returns to a vertical image and is distorted.

## Step-by-step reproduction instructions

1. Add an Image block with a vertical image to a page
2. Crop to a square
3. Manually drag to resize

## Expected behaviour

The image should remain square as you resize it.

## Actual behaviour

The image returns to a vertical image and is distorted.

## Screenshots or screen recording (optional)

[Screen recording](
https://d.pr/i/mYUlJ8)

## WordPress information
- WordPress version:   5.6.1 
- Gutenberg version: 9.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: iOS 10.15.5 
- Browser: Firefox: 85.0.1

**Comment by paaljoachim** [comment] 2021-02-10 23:05
Hei Mike @mikeicode 

There are a lot of overlapping issues that deal with the image resize tools.
I have listed a bunch of them here: https://github.com/WordPress/gutenberg/issues/28915

Which means I assume your issue is likely a duplicate of one or more of the issues listed above. Take a look.
I am also looking forward to getting the Image block resizing tools fixed.

**Comment by mikeicode** [comment] 2021-02-11 12:27
@paaljoachim I reviewed the items on that link and don't see one that looks like this specific issue. Perhaps after resolving one of those this issue will also be resolved but since the descriptions do sound different I'll leave this open. Thanks!

**Comment by jordesign** [comment] 2023-09-08 03:10
I can no longer recreate this issue in WP6.3 - so will close it as such.

**Closed by jordesign** 2023-09-08 03:10 UTC
Labels: [Block] Image
