### ISSUE TITLE
Don't save a reusable block until the user adds a name

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21259] opened 2020-03-30 13:00 UTC
At the moment, when creating a reusable block, we save an entry on the post type immediately. We should require the user to enter a name first. Saving immediately also has the issue that if you start typing and the async update happens a brief moment later, it removes the text you typed.

**Comment by youknowriad** [comment] 2020-03-30 13:03
It seems like this might be a duplicate of #12940

**Comment by youknowriad** [comment] 2020-04-08 12:12
closing as duplicate

**Closed by youknowriad** 2020-04-08 12:12 UTC
Labels: [Feature] Reusable Blocks, [Type] Enhancement
