### ISSUE TITLE
Coloring Specific Text in Text Blocks

### ISSUE THREAD

**Issue by cdfleming** [WordPress/gutenberg#9826] opened 2018-09-12 12:51 UTC
Gutenberg has text color options, but you can't color **specific** text. It colors the entire block. Please make it so users can highlight and color a specific word or set of words rather than coloring all the text in the entire text block.

**Comment by youknowriad** [comment] 2018-09-12 13:34
Duplicate of #6080

Thanks

**Closed by youknowriad** 2018-09-12 13:34 UTC
