### ISSUE TITLE
Site Editor: templates do not save if already edited in another theme

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#28951] opened 2021-02-11 15:40 UTC
## Description

In the Site Editor, when editing a template or a template part, unable to save if template or template part already exists as a previously edited template from another theme.

## Step-by-step reproduction instructions

Install more than one FSE enabled theme e.g. [TT1 Blocks](https://github.com/WordPress/theme-experiments/tree/master/tt1-blocks) and [Q](https://github.com/aristath/q)
Activate either theme.
Go to Site Editor and make changes to a template part (e.g. header) or a template (e.g. index), save changes by clicking Update Design.
Exit the Site Editor, go to Appearance > Themes and switch themes to the other FSE theme.
Go back into Site Editor and make changes to a template e.g. if you previously edited header in TT1 Blocks theme, then edit the header in Q theme.
Click Update Design to save and the button should change state to disabled to signify that the changes have been saved.
Notice the button stays active.
Exit the Site Editor and notice the 'This page is asking you to confirm that you want to leave - data you have entered may not be saved.' message. Click 'Leave Page' to exit the Site Editor.
View the live site and notice how the edited template has not changed.
Go to Appearance > Themes and switch back to TT1 Blocks theme, view the live site and notice how the template has now changed to the template that we were trying to edit when the Q theme was active.

## Expected behaviour

The template or template part should only save for the active theme, not another theme with the same previously edited template name.

## Actual behaviour

The template or template part is saved for the wrong theme.

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes and No. TT1 Blocks and Q

## Device information
- Device: Desktop
- Operating system: Win 10
- Browser: Firefox

**Comment by Sandstromer** [comment] 2021-02-13 10:31
@paaljoachim would you also consider tagging with the [Priority]High and [Type]Bug labels?

**Comment by paaljoachim** [comment] 2021-02-13 10:46
Hi @Sandstromer 

I will instead ping folks who work with Full Site Editing so that are alerted to this issue:
@jameskoster @Addison-Stavlo @aristath

**Comment by Sandstromer** [comment] 2021-02-13 11:02
Thank you for the explanation @paaljoachim 
I'm new to this so it definitely helps and is much appreciated.

**Comment by paaljoachim** [comment] 2021-02-13 19:15
Thank you for finding this bug and reporting it here! 
Have a great continued weekend!

**Comment by carolinan** [comment] 2021-02-23 09:58
I can confirm that I am able to reproduce this.

**Comment by annezazu** [comment] 2021-02-25 23:03
Confirming that I can replicate this as well.

**Comment by carolinan** [comment] 2021-03-12 04:09
Highlighting this because I think this must be solved for the MVP @mtias @david-szabo97

**Comment by Addison-Stavlo** [comment] 2021-03-12 19:04
That is super funky!  I can repro as well:

* Theme A - load site editor, edit header template part, and save
* Switch to theme B - load site editor, edit header template part, and save does not take.
* Switch back to theme A - load site editor, notice theme B's header template part is being used. 😕 

cc @youknowriad to add to the list of pings for folks that may have ideas.

**Comment by Addison-Stavlo** [comment] 2021-03-12 21:09
I think I found the problem.  I have a band-aid solution on https://github.com/WordPress/gutenberg/pull/29842 - but it seems like this may be a result of a larger underlying issue and may make sense to fix elsewhere.

**Comment by Addison-Stavlo** [comment] 2021-03-24 16:33
should be fixed now with https://github.com/WordPress/gutenberg/pull/29842

**Closed by Addison-Stavlo** 2021-03-24 16:33 UTC
Labels: [Feature] Full Site Editing, [Type] Bug
