### ISSUE TITLE
Error on Create/Add new Post (plugin conflict fixed in Yoast SEO 8.1.1)

### ISSUE THREAD

**Issue by alandesbonnet** [WordPress/gutenberg#9548] opened 2018-09-02 12:19 UTC
**Describe the bug**
With Gutenberg activated, attempting the create/add a post results in the error shown in the screenshot below:

![screen shot 2018-09-02 at 8 04 37 am](https://user-images.githubusercontent.com/18398763/44955827-b8db5500-ae87-11e8-9e72-fbb461e6e555.png)

**To Reproduce**
This happens every time I attempt to add/create a page or post when Gutenberg is active.

**Expected behavior**
In order to be able to add/create a post or page, Gutenberg must be deactivated. When activated again the same results occur EXCEPT if WordPress is signed out of, browser closed, reopened and a new log in is made to WordPress. A page/post can then be created with Gutenberg activated, but the screenshot above occurs as soon as a Save command is issued. 

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: macOS High Sierra v.10.13.6
 - Browser: Safari v.11.1.2 (13605.3.8)
 - Version of WordPress is 

**Smartphone (please complete the following information):**
 - Gutenberg Version: 3.7.0

**Additional context**
With Gutenberg deactivated, all pages on the website created with Gutenberg then revert I presume to Classic version, which is a major mess. The must be fixed quickly or I will remove Gutenberg so that our website is functional.
Thank you.

**Comment by GlennMartin1** [comment] 2018-09-02 12:34
Are you using Yoast SEO?

There is a known issue with Yoast; they intend to have 8.1.1 released on Monday.

**Comment by GlennMartin1** [comment] 2018-09-02 12:36
Here's a workaround: https://github.com/Yoast/wordpress-seo/issues/10867#issuecomment-417696845

**Comment by GlennMartin1** [comment] 2018-09-02 12:40
I understand the issue arises when Yoast is installed, and the Category panel is opened. 

If the Category panel was opened when you last saved a page/post, it defaults open. And vice versa. 

You can open Classic Editor on a post, close the Category panel, and save. Then go back and reopen Gutenberg. That will work as long as you do not again try to reopen Category panel.

**Comment by alandesbonnet** [comment] 2018-09-03 12:33
I give up until an update can fix this. No matter what I do or try I continue to get the error message about encountering an unexpected error. I cannot seem to find a work around.


Thanks for trying to help.
Alan

**Comment by alandesbonnet** [comment] 2018-09-03 14:14
Yes, I do. I will wait until Monday and see what happens after their patch. Thank you.

**Comment by GlennMartin1** [comment] 2018-09-03 14:18
Today is Monday, and the Yoast 8.1.1 is available now.

**Comment by designsimply** [comment] 2018-09-06 17:06
I am closing this issue because others have reported the Yoast SEO 8.1.1 is working for them. If you're still having any trouble please reply back even though the issue is closed. 🙂

**Closed by designsimply** 2018-09-06 17:06 UTC
Labels: [Status] Duplicate, [Type] Plugin / Theme Interoperability
