### ISSUE TITLE
Block validation failed for core/freeform

### ISSUE THREAD

**Issue by ericbhanson** [WordPress/gutenberg#14441] opened 2019-03-14 18:12 UTC
**Describe the bug**
We've recently upgraded some of our sites to WordPress 5. When editing old posts, our users have noticed that they will occasionally an error, "This block contains unexpected or invalid content." Looking at a console log of the first error, there is an error, "Block validation: Block validation failed for `core/freeform` (Object)."

**Screenshots**
Screen shot of the error:
![Unexpected or invalid content](https://user-images.githubusercontent.com/7453426/54380758-a164fc00-4662-11e9-9f18-7b4c45f76abe.png)

Console log from the error:
[WordPress_Invalid_content_error_message_browser_console.txt](https://github.com/WordPress/gutenberg/files/2967831/WordPress_Invalid_content_error_message_browser_console.txt)

**Comment by tellthemachines** [comment] 2019-10-03 06:35
Hi there,

Thanks for reporting this. I'm unable to reproduce the issue by creating a post in the classic editor and then opening it with the block editor. Is it possible that it might be caused by a plugin?

To rule that option out, could you try reproducing it with the default theme and all plugins disabled?

**Comment by tellthemachines** [comment] 2020-04-16 05:26
Closing this issue as I can't reproduce it and OP didn't respond to request for more info. Feel free to reopen if necessary.

**Closed by tellthemachines** 2020-04-16 05:26 UTC
Labels: Needs Testing, [Block] Classic
