### ISSUE TITLE
Copy/paste issue did not fill out the quote block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5946] opened 2018-04-03 08:51 UTC
Steps to reproduce:

- Copy text from [this post](https://ownyourcontent.wordpress.com/2018/03/26/maria-popova/) — include the paragraph before and after the pullquote
- Past in Gutenberg

Observe that the quote isn't transferred.

Screenshots:

<img width="757" alt="screen shot 2018-04-03 at 10 49 00" src="https://user-images.githubusercontent.com/1204802/38239349-bb99fb52-372c-11e8-909c-c14b35d40d54.png">

<img width="780" alt="screen shot 2018-04-03 at 10 49 08" src="https://user-images.githubusercontent.com/1204802/38239352-bd793f8c-372c-11e8-8143-beb215ef296b.png">

If pasted as raw text (⌘+Shift+V) it converts better and at least includes the text of the quote, but when copying the markup it doesn't work.

**Comment by iseulde** [comment] 2018-04-23 19:57
This should be fixed by #6054 when merged.

**Comment by ZebulanStanphill** [comment] 2018-08-24 02:36
@designsimply Just so you know, #6054 was reverted by #6501. A second attempt at making the Quote block use nested blocks exists in #6520.

**Comment by iseulde** [comment] 2018-11-26 18:02
Duplicate of #4992.

**Closed by iseulde** 2018-11-26 18:02 UTC
Labels: Writing Flow, [Component] Raw Handling, [Type] Bug
