### ISSUE TITLE
There are no blocks available in the "Legacy Widget" block.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#29018] opened 2021-02-16 03:33 UTC
Thank you for your development.

I'm testing a new blocked widget feature, but I have questions, so let me ask you a question.

No blocks can be used in the "Legacy Widget" block, and the display is as follows.

<img width="693" alt="スクリーンショット 2021-02-16 12 17 28" src="https://user-images.githubusercontent.com/31400297/108015178-f4b40600-7052-11eb-9c12-4e2832a729bc.png">

## WordPress information
- WordPress version: 5.6.1 & 5.7 beta2
- Gutenberg version: 9.9.3
- Are all plugins except Gutenberg deactivated? : "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? : "Yes"

## Device information
- Device: "Desktop"
- Operating system: MacOS Catalina
- Browser: Chrome

**Comment by talldan** [comment] 2021-02-16 04:25
I think the idea is that users should use the block equivalents of the old legacy widgets. 

It's something that I also found confusing at first. The message is not very clear. It could be improved. Thanks for flagging this.

**Comment by ddryo** [comment] 2021-02-16 05:56
Thank you for your reaction!
Is it just for keeping the past, not for using legacy widgets?

**Comment by talldan** [comment] 2021-02-16 06:05
Yep that is the main use case. I think other widgets that don't have a block equivalent might show up here as well, at least I'm sure I remember seeing that happen in the past.

There are other folks who might be able to answer better than me. I've moved this issue onto the widget project board.

**Comment by ddryo** [comment] 2021-02-16 06:29
I see. Thank you!

However, if that's the case, then the current specification of being able to add a "Legacy Widget" block seems inappropriate.

Why is it that this block, which is not supposed to be used, can be added?

**Comment by draganescu** [comment] 2021-02-18 15:36
Howdy! I will close this as a duplicate of #26240

**Closed by draganescu** 2021-02-18 15:36 UTC
Labels: [Block] Legacy Widget, [Feature] Widgets Screen
