### ISSUE TITLE
Consider adding Ctrl + Y as redo keyboard shortcut

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#10325] opened 2018-10-04 01:25 UTC
**Is your feature request related to a problem? Please describe.**
A common keyboard shortcut for Redo in the Windows world is Ctrl + Y. Currently the editor is using Ctrl + Shift + Z, another common keyboard shortcut, without having Ctrl + Y. I apologize if this is a duplicate, as I tried searching and did not see anything bringing this up.

**Describe the solution you'd like**
Ideally if we could support both Ctrl + Y, and Ctrl + Shift + Z, that would be awesome. I think it would also be more in line with what a lot of user expectations. If I need to accumulate data to support this claim, let me know.

**Describe alternatives you've considered**
Keeping Ctrl + Shift + Z is fine, but I imagine others will have a similar question, if they are used to using Ctrl + Y everywhere else.

**Comment by WesCook** [comment] 2018-10-23 02:32
I had to search this out after trying Ctrl+Y and having it fail.  This is definitely the expected keybind, versus Ctrl+Shift+Z.

**Comment by iseulde** [comment] 2019-02-11 09:25
Duplicate of #8921.

**Closed by iseulde** 2019-02-11 09:25 UTC
Labels: [Type] Enhancement
