### ISSUE TITLE
Can't cancel creation of Resuable Block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#12940] opened 2018-12-17 08:36 UTC
**Describe the bug**
If you accidentally click the _Add to Reusable Blocks_ menu option, there's no Cancel button to allow you to cancel the Creation of the Block.

**To Reproduce**
1. Select a block
2. Click the _Add to Reusable Blocks_ menu option and then try and cancel out of that action

**Expected behavior**
I should be able to cancel the creation of a Reusable Block if I accidentally click that menu option or decide that I no longer want to create a Reusable Block.

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3
- WP 5.0.1

**Comment by swissspidy** [comment] 2018-12-17 09:35
Closing as duplicate of #12286 because this was suggested there already.

**Comment by paaljoachim** [comment] 2019-02-06 18:21
@swissspidy 
@youknowriad  
please re-open as we need to create separate issues for each item from my list. https://github.com/WordPress/gutenberg/issues/12286

Thanks.

We need the cancel button.

Existing:
![screen shot 2019-02-06 at 19 15 49](https://user-images.githubusercontent.com/5323259/52363799-e6828680-2a43-11e9-8113-4ef570898ca8.png)

With a cancel button:
![reusable-block-cancel-button](https://user-images.githubusercontent.com/5323259/52363985-63adfb80-2a44-11e9-9eb1-7556459b8d2c.jpg)

**Comment by youknowriad** [comment] 2019-02-06 18:25
A solution here would be to use a "modal" to give a name for the block before even saving it. I tried this in a custom development at some point, I think it works fairly well.

**Comment by paaljoachim** [comment] 2020-03-14 15:29
@youknowriad 
I was testing out reusable blocks again and was reminded that there is still no cancel button.
Let's get this in..:)
Who should we ping whom has earlier worked on Reusable blocks?

Or is there another iteration of Reusable blocks being worked on these days were this and whatever else needed is being upgraded?

**Comment by youknowriad** [comment] 2020-03-16 08:52
I believe this should be fixed with an alternative design. In a personal project, I implemented something close to reusable blocks but before showing the reusable block in place like we do now, I showed a small modal to enter the initial title and potentially fill other informations (icon, description..). A design like that would allow. "canceling", the current design doesn't.

**Comment by mapk** [comment] 2020-03-18 00:51
Here's a quick mockup with the "cancel" button. Ignore the black background. I had trouble with Figma. :) 

![reusable](https://user-images.githubusercontent.com/617986/76914514-cbee2400-6877-11ea-9196-071a1bf1b96c.gif)

**Comment by chrisvanpatten** [comment] 2020-03-18 02:15
@youknowriad Any chance that personal project is open source? I'm looking to implement something similar and would be very interested in seeing some prior art.

**Comment by youknowriad** [comment] 2020-03-18 07:59
@chrisvanpatten no it's not unfortunately :( 

@mapk With this UI (block toolbar ...), it's already a reusable block. The idea I believe here is to propose this modal as soon as you click "Add to Reusable Blocks" before even persisting the reusable block.

**Comment by paaljoachim** [comment] 2020-03-24 09:04
In regards to https://github.com/WordPress/gutenberg/pull/12009

I notice that clicking Edit one can adjust the permalink. If one changes ones mind and does not want to save then one can just click outside of it and the open save is automatically closed. The same method can be used for Creating a reusable block, and deciding not use create one anyway. One can just click outside of it. 

@youknowriad @mapk

**Comment by mapk** [comment] 2020-03-24 18:25
> The idea I believe here is to propose this modal as soon as you click "Add to Reusable Blocks" before even persisting the reusable block.

I think adding a modal is too much here. I noticed that the keyboard command for "undo" works just fine except it has a flaw. The first undo shows a weird state [block has been deleted or unavailable]. After doing "undo" again, it returns back to the original state. 

![undo](https://user-images.githubusercontent.com/617986/77462904-fe40d980-6dc1-11ea-80ed-1cb06408295e.gif)

If we can fix this weird step in the undo process, I'd say we're golden.

**Comment by earnjam** [comment] 2020-03-26 12:45
The problem here is that the block is already saved from the moment you select "Add to reusable blocks" and you can't really undo it. Doing an undo doesn't delete the block you've already created from the database. 

This also leads to the problem of every block having slugs like `untitled-reusable-block`, `untitled-reusable-block-2`, `untitled-reusable-block-3`, etc. We don't currently use those slugs for anything, but they can't be changed after being created either. Even if you were to change the title. See #5152

**Comment by paaljoachim** [comment] 2020-04-01 15:55
The issue title could probably be read as 
"bug: Reusable block saved before clicking save."

Actionable items.

Clicking "Add to reusable blocks" does not save a reusable block but opens the screen to give the option to do so.

One version.
![Screen Shot 2020-03-30 at 22 38 40](https://user-images.githubusercontent.com/5323259/78111788-7e3bf480-73fd-11ea-9985-1284d8e70b57.png)

Another version I made in Figma.
![Reusable Block toolbar](https://user-images.githubusercontent.com/5323259/78158810-004e0c80-7442-11ea-88e0-9613628b08fc.jpg)

**Comment by paaljoachim** [comment] 2020-04-10 11:42
@earnjam @chrisvanpatten 

Is it possible for one of you or someone else to tackle this issue and fix the Reusable Block so we get correct save/cancel?

Thanks.

**Comment by mapk** [comment] 2020-04-13 23:53
I think working in a "Cancel" button here which deletes the resuable block would work just fine.

**Comment by noisysocks** [comment] 2020-04-20 05:19
The difficulty with the proposed flow here is that while you're in the intermittent step in between creating the reusable block and saving the block, the post's content will have gone from looking like this:

```html
<!-- wp:paragraph -->
<p>Paragraph 1.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Paragraph 2.</p>
<!-- /wp:paragraph -->
```

To looking like this:

```html
<!-- wp:paragraph -->
<p>Paragraph 1.</p>
<!-- /wp:paragraph -->

<!-- wp:block /-->
```

If, at this point, the user saves the post but does **not** save the reusable block, they will have permanently lost Paragraph 2. This is why, for simplicity's sake, we opted for a flow saves the reusable block immediately.

**Comment by paaljoachim** [comment] 2020-04-28 16:31
It seems the next step is to fix the technical hurdle you mentioned @noisysocks 
Before a cancel button can be added as suggested above.

**Comment by paaljoachim** [comment] 2020-10-10 09:40
This issue is still valid. 
With an existing reusable block.
Click the edit button.
Notice only a save button is seen.
There is no cancel button.

![Reusable-block-no-cancel-btn](https://user-images.githubusercontent.com/5323259/95651835-2b9a6e00-0aed-11eb-9b74-29023bf42531.gif)

@noisysocks

**Comment by mapk** [comment] 2020-10-12 23:25
Okay, I've returned to take another look at this. So from what I gather, the reusable block creation process needs a cancel button for the primary purpose that it creates stored elements elsewhere in the backend that can't be removed by just converting it back into regular blocks. It differs from all other transforming or grouping processes in that detail. 

For example the Group block can group blocks together, and be ungrouped without needing a cancel option because no additional content is created elsewhere in the backend. But when I create a reusable block and convert it back into regular blocks, there remains a Reusable block in the Inserter. And that is the thing we want to avoid from being created if the click was a mistake.

This messaging should then be displayed BEFORE the reusable block shows up on the page. As @youknowriad mentioned above, a modal or notification of sorts is the way to go. Riad, do you have a PR for the work you mentioned above?

Aligning with that concept, Riad, I created this prototype:

![reusable](https://user-images.githubusercontent.com/617986/95798664-72cc5e80-0ca7-11eb-8396-d203f1282a5e.gif)

**Comment by paaljoachim** [comment] 2021-02-15 23:41
@noisysocks Robert and @youknowriad Riad.
What should we do with this issue?

**Closed** 2021-02-18 10:26 UTC
Labels: Needs Design Feedback, [Feature] Reusable Blocks, [Priority] Low, [Status] In Progress, [Type] Enhancement
