### ISSUE TITLE
Orphan buttons after focus on an Image or a Gallery

### ISSUE THREAD

**Issue by caxco93** [WordPress/gutenberg#9184] opened 2018-08-21 03:59 UTC
**Describe the bug**
Whenever you focus an Image Block or Gallery Block, a `button` element is created just before the closing `body` tag. Then, after blurring, the `button` is still there. This can be performed indefinitely times, leading to a massive amount of orphan `button` elements

**To Reproduce**
1. Create an Image Block
2. Upload 1 image to the Image Block
3. Select another Block like the Title or click on the white blank space.
4. Select the Image Block
5. Go back to step 3 (please feel free to exit this loop)
6. Check the `Elements` tab in your Dev Tools, right before the closing `body` tag

**Expected behavior**
There shouldn't be any left over `button` elements

**Screenshots**
![orphanbutton_click](https://user-images.githubusercontent.com/3190666/44379658-a0089200-a4cc-11e8-8f6b-097d9e17eac7.gif)
![orphanbutton](https://user-images.githubusercontent.com/3190666/44379665-a26aec00-a4cc-11e8-848a-b7b7ad2a3126.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 - Version: Gutenberg 3.6.2

**Comment by designsimply** [comment] 2018-08-21 22:06
Tested and confirmed that clicking on an image block or clicking on another kind of block after clicking on an image results in the following empty button HTML appearing just above the `</body>` tag:

![screen shot 2018-08-21 at tue aug 21 3 59 27 pm](https://user-images.githubusercontent.com/1119271/44431691-3041e800-a55c-11e8-89e1-a803f30ab2a8.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14478&action=edit running WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

Note: clicking between paragraphs or other types of blocks doesn’t seem to trigger the empty buttons.

**Comment by jorgefilipecosta** [comment] 2019-04-22 14:50
This is a complex problem I was able to reproduce it in my tests.
When If I focused the title and then I focused any block a new button element appears and stays in the dom forever. If I repeat the same tests with the sidebar closed or with the publish sidebar open the problem stops happening so I think it may be related with the main sidebar.

**Comment by youknowriad** [comment] 2019-08-23 08:54
I can reproduce with Gallery today but not the image block

**Comment by talldan** [comment] 2020-02-07 06:59
I can still reproduce this.

**Comment by talldan** [comment] 2020-02-13 02:08
I found another way to reproduce this, switching between the document and block tabs in the sidebar.

Debugged it by breaking on subtree modifications of the body element. It's caused by the MediaUpload component. The featured image uploader is what's causing it in the sidebar. Every time that's constructed it initialises wp.media:
https://github.com/WordPress/gutenberg/blob/a59a5d9ab761bb2e0ee37eb67aab96d7f3dcf91b/packages/media-utils/src/components/media-upload/index.js#L150

It looks like this bit of code that appends the button when that initialisation happens:
https://github.com/WordPress/wordpress-develop/blob/3dd39ffecea808afe86b8071331551d9d5e8cf89/src/js/media/views/uploader/window.js#L30

Not quite sure why, but I'll keep digging to see if I can find out 😄

**Comment by talldan** [comment] 2020-02-14 07:40
I've opened a trac issue for this as well:
https://core.trac.wordpress.org/ticket/49431

It might be that the issue can be solved in wp core alone, but until we can verify where the fix should take place I think it's best to leave both issues open.

**Comment by noisysocks** [comment] 2020-04-21 06:17
I'm inclined to say that the block editor should do what the classic editor does and not reinitialise the media frame when it already exists. See https://core.trac.wordpress.org/ticket/49431#comment:3 for more info.

**Comment by dsifford** [comment] 2020-04-29 15:23
Chiming in here to say that I'm able to reproduce this with just the `<MediaPlaceholder>` component.

**Comment by ntsekouras** [comment] 2021-07-21 08:38
Just moving my comment from the marked as duplicate closed issue ..

>After debugging I found out that these buttons are created from core here: https://github.com/WordPress/WordPress/blob/972c42288a1078d691a1f47239ae26fdd3117ad1/wp-includes/js/media-views.js#L5020

>This affects all blocks/components that use the MediaUpload component, like `Image, Cover etc... The created buttons seem to be important for the upload process (I deleted them in dom and it wasn't working) but I didn't go any deeper.

>I'm not sure if there is a bug here... Probably someone could look why and prevent creating these blocks in every render.
You can test it just by opening the Page/Post Setting in Inspector Controls, which load the component for the featured image.

**Comment by glendaviesnz** [comment] 2021-09-10 01:48
Just confirmed that this still happens in WP5.8 and Gutenberg 11.4.1

**Comment by jasmussen** [comment] 2021-12-15 08:17
I'm seeing this button appear unrelated to the media placeholder component. Just select the title block, then the another block, then the title block:
![buttons](https://user-images.githubusercontent.com/1204802/146149118-4caa0b23-e870-42c8-968d-4f388fd91292.gif)

**Comment by glendaviesnz** [comment] 2022-05-06 02:57
I couldn't replicate this on WP 5.9 and GB 13.1:

https://user-images.githubusercontent.com/3629020/167059468-8d915e49-e0eb-4d82-8046-926c7f4df9e6.mp4

Seems to have been resolved somehow, can't see any obvious fix anywhere, but going to close for now. Feel free to reopen if you can still replicate.

**Closed by glendaviesnz** 2022-05-06 02:57 UTC
Labels: [Type] Bug, [Feature] Blocks, [Feature] Media, [Block] Image, [Block] Gallery
