### ISSUE TITLE
Unexpected value in entry field when creating link with first word ending with a colon

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#27832] opened 2020-12-19 22:59 UTC
**Describe the bug**

I was playing with rich text links and accidentally discovered that if you select a word or words containing a colon that the block editor assumes you're using a special **protocol**.

Is this working as designed? I can understand it if I was using `mail:` or `tel:`, when the selection also contains the email address or telephone number, but don't think it's much use for other words.

**To reproduce**
1. Create a new post.
2. Type some text including a word ending with a colon or phrase containing a colon at the end of the first word.
3. Select text starting from the word ending with the colon and click on the Link tool icon.
4. The dialog assumes you're using a special protocol. 

eg
```
wp:template-part 
Issue: 
```

**Expected behavior**
I expected an empty entry field with the **Search or type URL** placeholder to allow me to select the target from current content.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/102700953-e5c6f800-4249-11eb-886f-efd91544f91a.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] 9.5.2 
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
-

**Comment by annezazu** [comment] 2020-12-29 19:17
@bobbingwide hey there! Thanks for reporting this. It appears to be a duplicate of this previously opened issue: https://github.com/WordPress/gutenberg/issues/26266 As a result, I'm going to close this out but feel free to chime in there :)

**Closed by annezazu** 2020-12-29 19:17 UTC
