### ISSUE TITLE
Don't render shuffle control when there are no patterns to shuffle

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63618] opened 2024-07-16 14:33 UTC
Don't render the shuffle control when there are no available patterns to shuffle to. In this visual below I have an "About" category with only one pattern. The "Shuffle" control should not render in this instance.

![CleanShot 2024-07-16 at 10 27 01](https://github.com/user-attachments/assets/09295b68-41b1-4e05-b57e-7cf125b88dff)

**Comment by talldan** [comment] 2024-07-17 02:41
@richtabor This looks like a duplicate of https://github.com/WordPress/gutenberg/issues/63069, so I'll close it. Someone has worked on a PR for the other issue, so I can give that a review.

**Closed as not planned by talldan** 2024-07-17 02:41 UTC
Labels: [Type] Bug, [Feature] Patterns, [Feature] Zoom Out
