### ISSUE TITLE
Custom color picker in the paragraph block closing prematurely

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#21163] opened 2020-03-26 04:01 UTC
**Describe the bug**
When clicking on the (hue selector?) part of the custom color picker, the color picker is closed prematurely:

![screen_capture_on_2020-03-25_at_11-56-06](https://user-images.githubusercontent.com/22446385/77608973-67fbe780-6f6a-11ea-95e3-f5fa88d8bd25.gif)

**To reproduce**
1. Open the Gutenberg editor and select a paragraph block
2. Under "Block Settings -> Color settings" click Custom Color
3. Move the color hue selector

**Expected behavior**
The custom color picker is closed

**Additional context**
- This was noticed by WordPress.com users using Gutenberg 7.7.1

**Comment by yansern** [comment] 2020-03-26 08:05
As far as I can track down, when a color is selected from the color picker, something in the editor is stealing focus from the color picker, causing the dropdown to think it has been blurred, and thus, closing the color picker.

**Comment by yansern** [comment] 2020-03-26 10:03
The component structure looks like this:

```
Paragraph
    |__TextColor (HOC from `useColors`)
       |__RichText
```

The `TextColor` HOC is responsible for changing the text color. However, the issue is that, whenever the text color has changed, the entire `RichText` component block gets **recreated**.

When the `RichText` component is recreated, it does all the content initialization (see `applyRecord` in `componentDidMount`) which includes setting a caret which causes the contenteditable element to steal focus. (see `range.setStart()/range.setEnd()` under `applySelection()` in `to-dom`).

When the focus is stolen, the `Dropdown` component that holds the color picker thinks user is clicking outside of the dropdown, and hides the color picker.

I see there are 2 ways around this:

**1. Fix the TextColor HOC by ensuring it doesn't recreate the `RichText` component.**

I haven't look deeper into `useColors` so at this point if this is possible as React is responsible to decide how to best rerender the DOM tree. Also, interesting to note that `useColors` hook dynamically generates HOC component. Therefore, do not try to use `TextColor` as a search keyword, you'll reach a dead end, just look directly inside `use-colors.js`.

**2. Introduce an option to disable close on focus on `Dropdown` component.**

While it is nice to have this option, I predict the logic around deciding when the color picker dropdown should stay open, and it shouldn't, could be tricky or dirty as well.

**Comment by yansern** [comment] 2020-03-26 10:10
@ellatrix Would you be able to take a look at this or offer a few pointers as I see you've got your fingerprints all over this in the commit history?

**Comment by jorgefilipecosta** [comment] 2020-03-26 11:11
According to the git bisect this issue is a regressing that happened on https://github.com/WordPress/gutenberg/pull/19701. I'm not sure the relation that PR has to the issue. cc: @ellatrix

**Comment by ellatrix** [comment] 2020-03-26 12:14
I see somehow RichText is setting focus back, which shouldn't be happening.

**Comment by ellatrix** [comment] 2020-03-26 12:40
Actually, this has nothing to do with RichText. The problem is that the `<Block>` is now nested in the `<TextColor>` components, which rerender the children if the color changes. `<Block>` sets focus on mount.

**Comment by ellatrix** [comment] 2020-03-26 12:59
@jorgefilipecosta Any idea how we could avoid the color components remounting its children?

**Comment by ellatrix** [comment] 2020-03-26 14:08
#21037 fixes this issue.

**Comment by jorgefilipecosta** [comment] 2020-03-26 20:57
> components, which rerender the children if the color changes
> @jorgefilipecosta Any idea how we could avoid the color components remounting its children?


I'm not totally familiar with how the hook works but given that https://github.com/WordPress/gutenberg/pull/21037 fixes the issue and that is the new approach we are trying I guess we should try to merge that PR instead of trying a fix for this in useColors.

**Closed** 2020-03-27 09:31 UTC
Labels: [Status] In Progress, [Type] Bug
