### ISSUE TITLE
Wordpress 5.6 causes some custom blocks to disappear

### ISSUE THREAD

**Issue by arts4u** [WordPress/gutenberg#27983] opened 2021-01-05 07:48 UTC
Hello,
 Posted this with wordpress.org but was directed to post here. After updating to Wordpress 5.6 from 5.5.3 some of our custom blocks disappear even though others in the same folder are still available. When editing a page using these blocks we get an error: “Your site does not include support for the “name of block” block. You can leave this block intact or remove it entirely.”They are written in ES5. A downgrade to just the wp-includes 5.5.3 has them all come back. Other people are also having this issue. I have tried disabling all plugins with same result. The frontend of the site works fine when this is happening. I have attached code of two blocks, one that shows up and one that doesn't and are located within our theme. These have to do with the artist pages that can be found here: https://sawdustartfestival.org/artists/  . The site is currently downgraded to 5.5.3 and has default block editor.
[does not show up.txt](https://github.com/WordPress/gutenberg/files/5768728/does.not.show.up.txt)
[this one shows up.txt](https://github.com/WordPress/gutenberg/files/5768729/this.one.shows.up.txt)
Is there something we are missing?
Thank You, Troy

**Comment by bph** [comment] 2021-01-07 22:52
Hi @arts4u I looked briefly at the shared code  in "does not show up.txt". You used
`wp.data.dispatch('core/editor').editPost` - but I don't see that the `wp.data` package was actually imported into your script.

**Comment by htmgarcia** [comment] 2021-01-08 00:46
Thanks for jumping into discussion @bph! Not sure if is related, `wp.data` is actually being imported. [Here is the full script](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/editor-sidebar/sidebar.jsx). 

I appreciate your thoughts!

**Comment by htmgarcia** [comment] 2021-01-08 00:48
Hi @arts4u,
as @bph pointed out and after seeing the attached .txt files, it seems `wp.data` is not being imported. This doc may help: https://developer.wordpress.org/block-editor/packages/packages-data/

Regards

**Comment by arts4u** [comment] 2021-01-10 21:19
Hello,
 Sorry I have been reading everything but don't see why this same block was visible in the editor in 5.5.3 (as well as 5.5, 5.5.1 and 5.5.2) but isn't in 5.6. I did not write this code, only trying to fix it but not great at code. Could it be shared how it should look?
Thank you, Troy

**Comment by htmgarcia** [comment] 2021-01-11 19:47
@arts4u I don't have the full picture of the plugin you use, however worth to add the line below after `const { __ } = wp.i18n;`:
`const { dispatch } = wp.data;`

Then change this part `wp.data.dispatch` to `dispatch`.

**Comment by arts4u** [comment] 2021-01-11 21:46
Hello,
Thank you for the reply, unfortunately it did not work. I also just realised that WP5.6 breaks the custom post template for adding a new Artist of which this block is part of. If I click to add new it just opens to a white page, downgrade to 5.5.3 and everything works again. There just seems to be something in the new version that is not compatible with certain code that worked in 5.5.3. I will keep trying to figure this out but I really think this should be looked at. If you need more information please ask.

Thank You, Troy

**Comment by stokesman** [comment] 2021-01-12 01:37
>I also just realised that WP5.6 breaks the custom post template for adding a new Artist of which this block is part of. I click to add new it just opens to a white page...

It would help if you can include the error messages from the console. If you're not familiar with that here's [a short how-to video](https://youtu.be/0P4xbEN1yjs).

**Comment by arts4u** [comment] 2021-01-12 04:49
Hello, That looks helpful. Please find attached screenshots of both the New Artist Template and an Artist page that has the artist-details block in use in both WP5.6 and WP5.5.3 . I see that in WP5.6 the block is not registered for some reason even though it doesn't have that error in 5.5.3 .  Please let me know what else you may need. Thank You, Troy

![WP5 5 3_Artists-Details block showing](https://user-images.githubusercontent.com/76988775/104270545-9f7e4680-544d-11eb-98f7-ff8945a7ef0b.png)
![WP5 5 3NewArtistTemplate](https://user-images.githubusercontent.com/76988775/104270549-a0af7380-544d-11eb-947e-4ec4825f2547.png)
![WP5 6_Artist-Details block missing](https://user-images.githubusercontent.com/76988775/104270550-a1480a00-544d-11eb-9413-778bc85b49ec.png)
![WP5 6_NewArtistTemplate](https://user-images.githubusercontent.com/76988775/104270553-a1e0a080-544d-11eb-9046-28a8ea96a6e2.png)

**Comment by stokesman** [comment] 2021-01-12 18:01
Thanks for those Troy. They don't really give away much. Are these custom blocks provided as part of the theme or a plugin? If it's a plugin is there any chance that plugin is not installed/active on the WP5.6 site? Otherwise, it would be good to see the PHP that enqueues those JS files you've already shared. If you can find that, I'd suggest pasting it into a gist (see: https://gist.github.com) so it can be viewed without downloading (just link to it from this thread).

**Comment by arts4u** [comment] 2021-01-12 20:36
Hello,
 They are custom blocks part of the theme. Here are links to functions.php, blocks.php, core.php and blocks-editor.js located in the theme. Not sure which you needed or if any.  Troy
[https://gist.github.com/arts4u/0413a4a7cf30a3375758b63eb9ed461f](url)
[https://gist.github.com/arts4u/16961fdaf34101c7d5f40dbc6a13e0fa](url)
[https://gist.github.com/arts4u/9057e91f1bacb27e8d8e0fb8c931782c](url)
[https://gist.github.com/arts4u/b64d6d75751bba4948645ab29f8dc2bd](url)

**Comment by stokesman** [comment] 2021-01-12 23:46
I see code that might be the culprit in the built version of [blocks-editor.js](https://troyp32.sg-host.com/wp-content/themes/sawdust/dist/js/blocks-editor.js) but I don't see that in the source of the artist-details block you posted originally (as does.not.show.up.txt). I'm not sure where it's coming from. Can you share the contents of hide-artist.js which should be sitting alongside blocks-editor.js?

**Comment by arts4u** [comment] 2021-01-13 00:15
Hello, Here is the link for the artist-hide code. Its name is actually index.js as all blocks in the theme are. I have attached a screenshot of the file structure to show where all these blocks are. What has changed in 5.6 that may cause this? Troy
[https://gist.github.com/arts4u/f92f18838b52eb095dfedd826a91fe57](url)
![Screenshot (134)](https://user-images.githubusercontent.com/76988775/104389835-33edb500-54f1-11eb-844c-82dba4d917c6.png)

**Comment by stokesman** [comment] 2021-01-13 02:31
Okay, what I was looking for wasn't in hide-artists, but now that I could see where the source files are I checked the one for artist-details, the last few lines of the file were left out of does.not.show.txt from your original post. Here they are:
```javascript
domReady(() => {
	// Make block only available to artist post type.
	if (wp.data.select('core/editor').getCurrentPostType() !== 'artist') {
		wp.blocks.unregisterBlockType('sawdust/artist-details');
		return;
	}

	// Disable the post title textearea because the title is generated automatically.
	document.querySelector('.editor-post-title__input').setAttribute('disabled', true);
});
```
So what I believe is happening is that domReady callback is executing too soon. Which means `getCurrentPostType` returns null instead of the post type and the block gets unregistered. You could just remove all those lines from the file and things should work. But it should also work to change those lines to these:
```javascript
window.addEventListener('load', () => {
	// Make block only available to artist post type.
	if (wp.data.select('core/editor').getCurrentPostType() !== 'artist') {
		wp.blocks.unregisterBlockType('sawdust/artist-details');
		return;
	}

	// Disable the post title textearea because the title is generated automatically.
	document.querySelector('.editor-post-title__input').setAttribute('disabled', true);
});
```

That said, you'll need to run the build process to generate the file being loaded in the block editor. Which I'm guessing you are aware of just want to be sure.

>What has changed in 5.6 that may cause this?

I don't know. There are [other](25330) [issue](27607)s about `domReady` triggered callbacks failing to work as before but at least one those originated with 5.5. So if this is due to the same changes it seems like it should have been happening on 5.5 as well.

**Comment by arts4u** [comment] 2021-01-13 18:54
Hello, Thanks for this. I have already tried removing the lines which is why I submitted the file with them missing already. This was done on our test site and it reacts the same way - block not shown and white page for Add New Artist in 5.6, downgrade to 5.5.3 and all works again. Will try the second version you sent, but I am unclear of the build process to generate. I guess I need to do some more reading but where to look?

**Comment by stokesman** [comment] 2021-01-13 20:16
Yeah, without running the build, changes to those files in the blocks directory will have no effect because they are not loaded by the editor. All those files listed [here](https://gist.github.com/arts4u/b64d6d75751bba4948645ab29f8dc2bd) are built into [a single minified file](https://troyp32.sg-host.com/wp-content/themes/sawdust/dist/js/blocks-editor.js) and that is what is being loaded in WP.

The build process is something you'd need to run on your computer and then upload the results (in the dist directory) to the server. Can you find a package.json file in your theme? It would likely be in the blocks directory but could be in the parent folders. That file will reveal what needs to be run to build the blocks. You'll need node and npm on your machine and willingness to use the terminal. How does that sound?

**Comment by arts4u** [comment] 2021-01-14 18:41
Hello, Ok something new to learn. There is no package.json, only a package-lock.json.

**Comment by stokesman** [comment] 2021-01-14 20:58
Without the package.json file, it's going to be more challenging. If you can get that from the original developer that would be ideal. Otherwise, I think it may be easier to refactor a bit and remove the need to build the JS. 

Many of those files in the blocks directory would run fine as is in most browsers. The ones that won't use JSX but could be converted easily to use `createElement` so that they'd run in the browser. A few of those also use an `import` statement and while that would be fine in many browsers it would require changing the script tags to have the `type=module` attribute. That's a bit of a hassle, so instead, you could just inline the imported files into the file that imports them. The final thing you'd have to do is have your blocks.php enqueue all those files instead of the single file blocks-editor.js.

Something else to keep in mind is that it looks like the images, CSS, and frontend JS for the theme are part of the build so if you end up needing to change any of that the same thing applies. Without having the build process available, you have to edit stuff in the dist folder for it to have any effect.

The last idea I'll throw out is you could edit the [built blocks JS](https://troyp32.sg-host.com/wp-content/themes/sawdust/dist/js/blocks-editor.js) directly. It would likely work to find and replace all instances of `wp.domReady` with `(cb)=>{window.addEventListener('load',cb)}` but then you're still stuck with a file you'd never want to edit by hand.

**Comment by arts4u** [comment] 2021-01-14 23:29
Hello, I am unable to get the package.json file as the developers have been unresponsive to other requests. The site has been live for 3 1/2 months and has been nothing but problems, especially with WooCommerce and I have had to fix parts there. Really want to start over myself but trying to figure out how to remake an Artist Directory.
 I do like the last idea as the block-editor.js only has 6 instances of domReady but is written like this line example: m=wp.domReady,b=wp.blocks.registerBlockType,v=wp.components,y=v.TextControl,g=v.Placeholder,h=wp.i18n.__;b("sawdust/artist-details",{title:h("Artist Details","sawdust") . Should it look like this: m=(cb)=>{window.addEventListener('load',cb)},b=wp.blocks.registerBlockType,v=wp.components,y..... Do I need to change it anywhere else?  Troy

**Comment by stokesman** [comment] 2021-01-15 01:01
Yes, that's how it should look. You'd maybe only need to replace the one that corresponds to the artist-detail block but I saw most of the other uses were similar and seem like they may be failing as well. Perhaps their failures aren't as obvious. So changing all those to happen on window load shouldn't hurt. You'll have to test and see.

**Comment by arts4u** [comment] 2021-01-15 20:07
Hello, changed all in blocks-editor and still reacts the same. It does seem to only be this block. I thought there were others since the "add new artists template" didn't work. Works fine on the front end, just not in the editor. Troy

**Comment by stokesman** [comment] 2021-01-15 21:49
It could be that the old file was loaded from the cache. You can try shift+refresh. If that doesn't seem to have an effect I'd still want to check with the developer tools to make sure the edited version is loaded. The console would be good to check as well in case there are any errors different from those seen before. Let me know if you do see anything different in the console.

As for why caching is likely, that theme enqueues all styles and scripts with version arguments equal to the const set on line 9 in functions.php: `define( 'SAWDUST_VERSION', '0.3.9' );`. After any changes, it'd good to update that. Just make it '0.3.10' or whatever just something that hasn't been used previously. That will ensure that the latest files are loaded.

**Comment by arts4u** [comment] 2021-01-16 19:07
Hello, I had flushed site cache in Siteground and thought I had refreshed the browser, tried again. Found it works but only in Chrome. In Firefox you need to refresh every artist's page every time it is opened to get the block to show even if you close that page and reopen it. Same with New Artist. There are no errors before or after the refresh only the same warnings. So this is a timing issue?

**Comment by stokesman** [comment] 2021-01-17 17:14
Glad to hear that at least changes can finally be seen. Yes, it's a timing issue. I have a similar block that goes in a custom post type template and tested by adding the same logic for it. In Firefox, I never saw it work but it did work every time in Chrome. Apparently, `getCurrentPostType` can be well late to the knowing-the-post-type party. How about an alternative?

The admin puts a class for the post type on the body tag. The JS can just look for that which will definitely be there by the time `domReady` executes. So in place of `"post"===wp.data.select("core/editor").getCurrentPostType()` use `document.body.className.indexOf('post-type-post')!==-1`. And it's fine to run that with domReady so you can revert to using that. Works in my testing.

There are four places in the blocks-editor.js file with checks against `getCurrentPostType`. I'd recommend converting all of them to make sure all the original features are working as intended. Each condition is a little different but shouldn't be too hard to figure out the conversions.

**Comment by arts4u** [comment] 2021-01-19 18:33
Hello, Yes it all seems to work. Tested in Chrome, Firefox and Edge on a PC and Chrome and Safari on Mac. I believe I have them all written correct. Will have a few others try it as well and let you know. Thank you

**Comment by arts4u** [comment] 2021-01-27 20:05
Hello,
 So have gone through testing and made some changes as it caused "Add New Class" to come up as a blank page. Just did not add the "document.body.className.indexOf('post-type-post')!==-1" to the "class-artists" block. 
 It does come up with one error in console of "Uncaught TypeError: Cannot read property 'setAttribute' of null, at HTMLDocument.<anonymous> (blocks-editor.js?ver=0.3.12:1)" for editing or creating a new artist, but does not seem to affect anything.
 Also I have now obtained the the package.json file so I am able to use that.
 I am now doing this testing at troyp41.sg-host.com
Troy

**Comment by stokesman** [comment] 2021-02-02 03:36
Sounds like the condition for that case wasn't written as needed. It would not be hard to fix editing the built file some more. Though if you have any expectation to maintain this theme for the future, I'd definitely recommend getting the theme build process working.

As I mentioned before the prerequisite is having node and npm installed on your computer (there are plenty of [guides to that](https://duckduckgo.com/?q=node+and+npm+install&atb=v117-1&ia=web)). The theme files will need to be on your local computer (you don't need to have WordPress running locally but it could help for testing the theme without the need to upload). Then from the command line and in the directory with `package.json` run `npm install`. After that completes, `npm run` will list available commands. One of those is likely `build` and if so you could then `npm run build` and the final files will be written to the `dist` directory. I'd be curious to see the package.json file if you'd care to share that.

**Comment by arts4u** [comment] 2021-02-02 20:23
Ok something to start learning. Thank you for the link. Here is the package.json
[https://gist.github.com/arts4u/bdd2b2bcc4a7b22e7b19aee4e63da871](url)
Troy

**Comment by tellthemachines** [comment] 2023-05-09 04:56
I'm going to go ahead and close this as it's not an issue with Gutenberg but with the custom theme code.

**Closed by tellthemachines** 2023-05-09 04:56 UTC
Labels: [Type] Help Request
