### ISSUE TITLE
Editor text has no default left/right margin unless theme opts into site-wide padding 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35884] opened 2021-10-22 15:09 UTC
If a theme does not opt into site-wide padding through theme.json, and the user does not specify site padding through Global Styles, the post/page editor currently provides no left/right margins to prevent text from bumping up against the edges of the screen: 

<img width="898" alt="Screen Shot 2021-10-22 at 11 00 42 AM" src="https://user-images.githubusercontent.com/1202812/138477796-34fd32ef-ce88-44ef-a881-9d9c03008f7e.png">

This is sort of an issue for block themes, since it effectively requires them to supply either a site-wide padding value, or some custom CSS. More importantly though, it's a regression in the editor experience for users of classic themes that don't manually provide these margins. 

To reproduce: 

1. Activate an older theme, like Twenty Eleven.
2. Open the post editor, and either switch to one of the device previews (tablet/mobile), or make your browser window smaller. 
3. Note that the text bumps against the edges fo the screen. 

Gutenberg version: Version 11.8.0-rc.2
Related: https://github.com/WordPress/twentytwentytwo/issues/144

cc @youknowriad since this may be related to removing the site-wide margin.

**Comment by youknowriad** [comment] 2021-10-25 08:04
I think this is a side effect of the removal of the `8px` padding we had around the canvas. So how should this work? add this padding for the "post editor" only?

**Comment by kjellr** [comment] 2021-10-25 12:19
To start with, we should definitely add it by default for non-block themes. That'll fix the regression aspect. 

For block themes, I wonder if it makes sense to add a default padding value back in — when we removed it, there was no site padding control, but now it's a bit easier to specify that. And I think explorations like https://github.com/WordPress/gutenberg/pull/35919 will make the control even more useful. 

@jasmussen do you have any ideas?

**Comment by jasmussen** [comment] 2021-10-25 12:36
Could we add those 8px by default to lib/theme.json? If the "outer padding" aspect gets addressed, then it seems like it might thread the needle between a good default, theme control, and flexibility? Or am I missing a piece?

**Comment by kjellr** [comment] 2021-10-25 12:41
Yeah, that's more or less what I'm thinking at this point too.

**Comment by kjellr** [comment] 2021-11-03 14:50
@noisysocks I think we should add this to 5.9 must-haves, since it effects a large quantity of themes.

**Comment by MaggieCabrera** [comment] 2021-11-08 14:33
I was testing and checking emptytheme and on trunk, with no padding defined, emptytheme doesn't have padding at all on frontend or backend, I think that's the correct behavior. I talked about this with @kjellr and it seems like this is more of a problem for classic themes not using theme.json.

Would the solution be to add this padding in the editor only for classic themes? And let block themes handle this padding or lack thereof via theme.json and ideally https://github.com/WordPress/gutenberg/pull/35919 or a similar solution?

**Comment by jeffikus** [comment] 2021-11-09 10:12
> Would the solution be to add this padding in the editor only for classic themes? And let block themes handle this padding or lack thereof via theme.json and ideally #35919 or a similar solution?

@MaggieCabrera Are you saying add the padding only if theme.json is not present in a classic theme?

**Comment by MaggieCabrera** [comment] 2021-11-09 10:14
> @MaggieCabrera Are you saying add the padding only if theme.json is not present in a classic theme?

Yeah, and only in the editor, not the frontend, so that it behaves like before the regression, but excluding themes with a theme.json file.

**Comment by jeffikus** [comment] 2021-11-09 10:16
@MaggieCabrera that makes sense to me, I agree with that solution.

**Comment by kjellr** [comment] 2021-11-09 12:54
I think that makes sense for now as a fix the regression in older themes.

**Comment by Mamaduka** [comment] 2022-01-05 06:10
It looks like we don't have a solution for this issue yet.

I'm going to remove the issue from the 5.9 board. We can try and fix this in the next release.

**Comment by kjellr** [comment] 2022-01-05 14:25
I think it's acceptable (but not great) to punt this issue for block themes, but it's not ok to punt the regression that happens for all classic themes. By default today, any theme that provides no editor styles suffers from this issue: 

<img width="377" alt="Screen Shot 2022-01-05 at 9 21 46 AM" src="https://user-images.githubusercontent.com/1202812/148232939-07448055-7b24-430a-a339-e9f8064b18fd.png">

This effects many of our own recent default themes as well: 

Twenty Twenty|Twenty Nineteen
---|---
<img width="376" alt="2020" src="https://user-images.githubusercontent.com/1202812/148232258-64939475-edae-48e3-ae41-c651d1175136.png">|<img width="376" alt="2019" src="https://user-images.githubusercontent.com/1202812/148232261-009a666e-3aa4-4382-9cf4-9c0f551e9ddf.png">

This wasn't the case in 5.8, and it's a pretty obvious regression. I think a reasonable fallback would be to push a change that re-imposes the `8px` margins from 5.8 for non-block themes. 

Is that something we can still fit in? 

cc @youknowriad @noisysocks

**Comment by scruffian** [comment] 2022-03-03 12:30
Reopening as this was never resolved.

**Comment by ramonjd** [comment] 2022-03-24 22:28
Adding https://github.com/Automattic/themes/blob/trunk/archeo/style.css as an example of how themes have worked around current issues

props @scruffian

**Comment by andrewserong** [comment] 2022-03-24 23:17
Just in case it helps for whoever picks up this issue, we currently output styles for the root block selector at this line in the theme JSON class: https://github.com/wordpress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-gutenberg.php#L106, so that (`get_block_classes`) could be a good place to put additional styles?

**Comment by tellthemachines** [comment] 2022-03-25 01:35
I'm not sure what the intended goal for this issue currently is. The classic theme regression has been fixed, which [this comment](https://github.com/WordPress/gutenberg/issues/35884#issuecomment-963220520) and following imply is the major concern here. 

It would be good to at least be clear about the scope of the problem we're trying to fix: do we want a default padding added for block themes just in the post editor? Or can this be addressed globally as part of #35607?

**Comment by kjellr** [comment] 2022-03-28 12:59
I think this could be addressed globally as part of #35607, if that issue implemented a default that wasn't `0`.

**Comment by scruffian** [comment] 2022-06-13 11:27
I think can close this as it's part of https://github.com/WordPress/gutenberg/issues/35607

**Closed as completed by scruffian** 2022-06-13 11:27 UTC
Labels: [Status] In Progress, [Type] Regression
