### ISSUE TITLE
Style Variations Render Incorrect Preview When Selected Style Is Unregistered

### ISSUE THREAD

**Issue by jgcaruso** [WordPress/gutenberg#24973] opened 2020-09-01 13:50 UTC
**Describe the bug**
When programattically unregistering a style variation that has been selected by a user, the Styles panel is re-rendered, however the incorrect previews are then displayed in the panel.

**To reproduce**
This was noticed in my in-development plugin, but I can reproduce it with manual steps in an existing Block
1. In the editor, add a 'social links' block
2. Select the 'Pill Shape' style, notice the preview images shows Default as circles, and Pill Shape with wide circles
3. Enter the following in the browser console (this would be called by the block plugin after the user takes some action that makes one of the styles no longer valid in my block) `wp.blocks.unregisterBlockStyle('core/social-links', 'pill-shape')`
4. Look at the Style previews, notice that the Default preview is now showing the preview for Pill Shape.

**Expected behavior**
The  styles panel, when re-rendered, should show the correct previews based on their style name.

**Screenshots**
In the Social Links block (just used to help reproduce the issue in a block everyone has access to)
All block styles
<img width="269" alt="Screen Shot 2020-09-01 at 9 47 00 AM" src="https://user-images.githubusercontent.com/4081020/91859318-4d741b80-ec38-11ea-87b5-3c7379fce749.png">

After Pill Shape is unregistered
<img width="252" alt="Screen Shot 2020-09-01 at 9 44 33 AM" src="https://user-images.githubusercontent.com/4081020/91859328-4fd67580-ec38-11ea-9a35-d806e04f6142.png">

With the block I'm working on
Initial State, both styles are available
<img width="255" alt="Screen Shot 2020-09-01 at 9 32 21 AM" src="https://user-images.githubusercontent.com/4081020/91857795-68459080-ec36-11ea-9d58-bb65ae174639.png">

After unregistering the selected style, that styles preview is moved to the 'Default' style
<img width="255" alt="Screen Shot 2020-09-01 at 9 32 30 AM" src="https://user-images.githubusercontent.com/4081020/91857785-654aa000-ec36-11ea-986c-596666fc3a77.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Happens with both latest gutenberg plugin and default.
- If the Gutenberg plugin is installed, which version is it? 8.8.0

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox, Chrome and Safari
 - Version Latest for all (80, 85, 13)

**Comment by talldan** [comment] 2021-02-16 05:59
I can reproduce this, though it is a real edge case, and not sure there's a good way to resolve it.

It seems unusual, but what's happening is that when the Pill Shape style is unregistered it's added to the 'Additional CSS class(es)' field because it's an extraneous classname on the block.

The block preview shows all styles from Additional CSS classes because it tries to show the most accurate preview possible.

This would be very difficult to handle any other way. Solving would mean going through every block and removing the class for matching unregistered style variations. Unfortunately, this would change a user's content, so it'd be undesirable.

I think given that I'll close the issue.

**Closed by talldan** 2021-02-16 05:59 UTC
Labels: [Feature] Style Variations
