### ISSUE TITLE
Request: expose theme.json layout presets in global styles

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/gutenberg#33184] opened 2021-07-03 02:21 UTC
## What problem does this address?

The theme.json layout presets `contentSize` and `wideSize` are not exposed as custom properties in Gutenberg's global CSS.

## Why is this a problem?
I’m working on a FSE theme that uses CSS Grid for layout. This is different to the layout model currently presumed by Gutenberg: a full-width parent with children constrained by max-width + left/right auto margin values. With the Grid approach I have a parent container constrained to the value of `contentSize` (dynamic content and wide alignments are handled per block with a customised version of the `gutenberg_render_layout_support_flag` filter printing the syntax required for a Grid layout).

The relevant CSS looks like this:
```
.wp-block-post-content {
	display: grid;
	grid-template-columns: 1fr min(var(--wp--custom--layout--content-size), 100%) 1fr;
}

.wp-block-post-content > * {
	grid-column: 2;
}

.alignwide,
.alignfull {
	grid-column: 1 / -1;
}

.alignwide {
	justify-self: center;
	max-width: var(--wp--custom--layout--wide-size);
}
```
## What is your proposed solution?

In theme.json I currently have a custom layout setting that duplicates the native one. This exposes properties in the global CSS I can use in my Grid-related styles. It would be nice to use variables based on the actual `contentSize` and `wideSize`. Following the convention of other presets exposed in global styles, I'd like to write something like this:

```
grid-template-columns: 1fr min(var(--wp--preset--layout--content-size), 100%) 1fr;
```

(Please note: there's an earlier issue from a couple of weeks ago that I closed after thinking I'd found a solution. This new one provides a bit more context, apologies for the double-up: https://github.com/WordPress/gutenberg/issues/32811)

**Comment by justintadlock** [comment] 2021-07-03 04:01
See: https://github.com/WordPress/gutenberg/pull/30081

**Comment by oandregal** [comment] 2021-07-13 11:50
Going to close this one as a duplicate of https://github.com/WordPress/gutenberg/pull/30081

**Closed as completed** 2021-07-13 11:50 UTC
Labels: [Type] Enhancement, [Feature] Themes, Global Styles

**Comment by chthonic-ds** [comment] 2021-07-14 03:40
Just noting this issue doesn't seem to be covered by #30081 since the "Types of changes" description was updated to "Exposing the CSS-variables in styles generated for containers."

See: https://github.com/WordPress/gutenberg/pull/30081/commits/ccb1c466af130a9d81b3805ff2fbfa372638e01c

**Comment by oandregal** [comment] 2021-07-14 08:43
Hey, yes, I know. Essentially, it's the same conversation: whether those values should be exposed or not as CSS Custom Properties and where (global, containers, etc).
