### ISSUE TITLE
Scrolling to the end, or top end, of Insert modal continue to scroll whole page (content area)

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1617] opened 2017-06-30 15:44 UTC
When scrolling in Insert popup, and comes to the bottom-end or top-end, prevent scrolling of whole page and content editor area. There is no need for it, it is not desired goal of User, to scroll content editor area.

Can make, and it will, editing very unpleasant.

I know one thing. It will happen a lot, maybe on all post editings.

**Comment by swissspidy** [comment] 2017-07-01 14:00
Possible duplicate of #656.

**Closed** 2017-08-02 11:50 UTC
