### ISSUE TITLE
Percentage Image Sizes Don't Make Sense, Result in Weird Behavior

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#12276] opened 2018-11-24 19:57 UTC
**Describe the bug**
As presented and functioning right now, I don't think the image percentage feature should be included with the 5.0 release.

Primarily, it's quite opaque to the user what the percentage is relative to and how it is calculated. As mentioned #11530, it would at least make more sense (though I'm still not sure if it would warrant inclusion) if it were relative to content width and an _alternative_ to the named sizes rather than being a percentage of the named size.

Some of the odd behaviors and problems that result what seems like the intended behavior:

- If an image size is larger than the full width, the image is constricted to full width at first, but clicking a percentage less than 100% can make it BIGGER! (See also: #12168)
- A "25%" image set relative to the Large size could quite possibly be larger than 100% of a medium or thumbnail image. This just feels weird.
- The percentage sizing is "lost" when changing from one named image size to another. This has an internal logic to it, but feels quite odd in practice. This is at least partially due to the fact that the percentages are broken away from the Sizes select menu by the pixel size controls.
- This likely will encourage inconsistency across a site with multiple editors. It seems very plausible that one editor would use "Medium" images while another might use a "Large" image at 50%. What would the impact of that be long-term.
- I don't know how this will impact the output of a sane `sizes` attribute, but it seems like it adds another layer of complexity to an already-challenging issue.

**Screenshots**
GIF showing strange behavior described in first point above in which 75% and 100% of a "Large" image are both larger than the initially inserted image.

![percentage-image-sizes](https://user-images.githubusercontent.com/1238696/48972478-15aa5f80-efe0-11e8-8b83-f44be613fd18.gif)

Screenshot showing interface that divides a primary control from a means of modifying the selection.
![Image Size and Percentage controls should be next to each other if the percentage controls are a means of modifying the named size](https://user-images.githubusercontent.com/1238696/48972464-c06e4e00-efdf-11e8-8215-5cc77cc02c08.png)

**Desktop (please complete the following information):**
Win 10, WP 5.0-RC1, Firefox 63.0.3, Twenty Nineteen, No plugins

**Comment by youknowriad** [comment] 2019-08-23 09:24
I'm to close this as a duplicate of #11530 as it seems to refer to the same thing.

**Closed by youknowriad** 2019-08-23 09:24 UTC
Labels: Media, [Block] Image, [Type] Enhancement
