### ISSUE TITLE
Misplaced featured image when using SVG's

### ISSUE THREAD

**Issue by vricop** [WordPress/gutenberg#9154] opened 2018-08-20 08:19 UTC
The featured image is not placed properly when setting an image with **SVG format**. I'm seeing this bug in a **custom post** type with nothing more than the default arguments for the register function.

Here's the screenshot:
![svg_featured_image_in_cpt](https://user-images.githubusercontent.com/3494708/44328151-1bccf500-a461-11e8-9378-3fde23893bdd.png)

As you can see the SVG is positioned on top of the button and "Remove logo" link ("Eliminar logo").

A quick look in the source reveals this image is positioned with "absolute", if I remove it, everything goes back to normal:

![image](https://user-images.githubusercontent.com/3494708/44328641-5aaf7a80-a462-11e8-8367-a94b9654ae83.png)

**Comment by designsimply** [comment] 2018-08-20 18:36
Thank you for reporting this issue! Closing as a duplicate of #5477.

**Closed by designsimply** 2018-08-20 18:36 UTC
Labels: Media, [Component] Post Settings, [Status] Duplicate
