### ISSUE TITLE
Safari Bug: Select tool does not always select the correct layer

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#19454] opened 2020-01-07 08:44 UTC
The select tool (press Escape, or choose from the toolbar) selects the layers of a block parent first. Click a columns block and you select the columns block itself, then the column, then contents inside that column. This is the inverse behavior of the default tool, where you click to edit text directly. 

In Safari this behavior is slightly buggy in that the selection is not instantly reset when you click outside a block to deselect. Observe Safari:

![safari](https://user-images.githubusercontent.com/1204802/71881131-0168e980-3132-11ea-9780-01da10eab14f.gif)

Note how when I've clicked through to the **Paragraph** layer, then deselect the block and quickly select it again, I can select the Paragraph again, even though the selection index should have been reset. It does get reset after a delay, but it is not instant.

Here's Chrome:

![chrome](https://user-images.githubusercontent.com/1204802/71881203-23626c00-3132-11ea-87c1-5680f4ac7d40.gif)

Note how regardless of which layer I select, when I deselect the block the selection index is immediately reset, as it should be. 

The issue appears to be related to the [BlockAsyncRenderProvider](#19343).

**Comment by momotofu** [comment] 2020-01-14 11:12
I was also able to reproduce this bug on Safari Version 13.0.4

**Comment by paaljoachim** [comment] 2021-04-15 19:24
Testing using:
WordPress 5.7
Twenty Twenty One.
Gutenberg plugin 10.4
Safari

I tested similar to what @jasmussen Joen mentioned and to me it now seems to be working correctly.
As parent block is selected I can click directly into the paragraph block inside the columns block.
I believe this issue can now be closed.

**Comment by jasmussen** [comment] 2021-04-16 06:29
@gziolo in relation to https://github.com/WordPress/gutenberg/issues/30299, should this one or that be closed? Are they the same do you know? Thanks for testing Paal.

**Comment by gziolo** [comment] 2021-04-16 08:09
It's very likely they are the same, see my comment: https://github.com/WordPress/gutenberg/issues/30299#issuecomment-808451499. There is also https://github.com/WordPress/gutenberg/issues/29678 that looks similar. Ideally, we test them all and close all that can't be reproduced. @jasmussen, can you still reproduce this one?

**Comment by Mamaduka** [comment] 2021-04-16 08:16
There's also #30249, which I could reproduce on Chrome, but it's inconsistent compared to Safari.

Unfortunately, I'm not sure where to look next for the source of the issue.

**Comment by ellatrix** [comment] 2021-05-21 07:19
Should be fixed after #30995. Please reopen if that's not the case :)

**Closed by ellatrix** 2021-05-21 07:19 UTC
Labels: Browser Issues, [Type] Bug
