### ISSUE TITLE
Missing "Wide" button on the "Welcome to the Gutenberg Editor" page

### ISSUE THREAD

**Issue by joehills** [WordPress/gutenberg#3789] opened 2017-12-03 21:22 UTC
## Issue Overview
In the "Welcome to the Gutenberg Editor" page, the "wide" button fails to appear when clicking on the image that is supposed to teach users how to widen images.

## Steps to Reproduce (for bugs)

1. Click "Gutenberg" in the sidebar of the WordPress dashboard
2. Scroll down the photo of the mountain with the caption: Give it a try. Press the "wide" button on the image toolbar.
3. Click the image to load the image toolbar
4. Observe the lack of a "wide" button.

## Expected Behavior
A "wide" button should appear when clicking on the image.

## Current Behavior
A "wide" button does not appear when clicking on the image.

## Possible Solution
If something about the image is preventing the button from appearing, maybe replace the image?

## Screenshots / Video
<img width="698" alt="screen shot 2017-12-03 at 3 19 48 pm" src="https://user-images.githubusercontent.com/970141/33529950-8685aa9a-d83d-11e7-974b-1a39529e552f.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by maddisondesigns** [comment] 2017-12-04 01:46
To get the "Wide" and "Full Wide" buttons, your theme needs to declare support for them.

See: http://gutenberg-devdoc.surge.sh/reference/theme-support/#wide-images

I bought up the same issue in #2243 and was told about the need to declare Theme Support. I also suggest that the demo text should be updated to inform people of this, but that still hasn't been done, so very few people know about requiring this Theme Support.

**Comment by youknowriad** [comment] 2017-12-22 13:39
This is also a duplicate of #2595 where we discuss a better way to solve this "demo" issue.

**Closed by youknowriad** 2017-12-22 13:39 UTC
