### ISSUE TITLE
German translation Error | Not able to work on a site

### ISSUE THREAD

**Issue by terobes** [WordPress/gutenberg#5529] opened 2018-03-09 13:19 UTC
## Issue Overview
First at all, I use the German Wordpress interface, since a few days my Gutenberg editor shows me an error if want to edit any post, site what ever. If I open a site it displays casual, when I hover into the Editor a error message pop up and says that a unexpacted error arrives. If I try to copy the error code for you nothing happens. 

After many tests about problems with JS or CSS and caching I tested to change my Language configuration to english. Now it works... I was a little surprised about that fix.

![image](https://user-images.githubusercontent.com/7466828/37209062-07e65aec-23a4-11e8-8ff8-1a9f5d24e3c0.png)

A List of all things I tested before:

- Caching on / off
- Minify On / Off
- HTTP2 on / off
- Every Plugin on / off
- CDN on / off
- Reinstall Gutenberg
- recovery doesn't work as well (error popup button)

**Comment by Presskopp** [comment] 2018-03-09 14:13
omgbbq, I feel like I deleted the internet, see #5472

**Comment by aduth** [comment] 2018-03-09 14:52
Closing as duplicate of #5459 (a few workarounds listed there).

**Closed by aduth** 2018-03-09 14:52 UTC
