### ISSUE TITLE
Consider adapting background color depending on tone set for navigation block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22465] opened 2020-05-19 15:43 UTC
If you set a dark background color for example in Twenty Twenty, the following is what you get for navigation block:

![image](https://user-images.githubusercontent.com/253067/82347625-c932bb00-99ef-11ea-9b38-61e5ba69db10.png)

I wonder if we could set the background to be a dark or light one, depending on the background?

**Comment by MichaelArestad** [comment] 2020-05-26 16:50
@karmatosed Perhaps we could do some magic detect background color and match it for the menu backgrounds (and adjust text color accordingly)? For now, this is low priority and hopefully, in the future, themes will style these blocks themselves resolving this issue.

**Comment by joyously** [comment] 2020-05-26 17:04
I think if the navigation block used the same classes as the standard menu walker, then the block itself would not need any styling. The theme is already styling the menu, so being consistent is the best bet for the majority of themes to display it well with no effort.

**Comment by alaczek** [comment] 2020-06-17 02:48
How about we drop the default background for the top-level menu items altogether as suggested in #22327 ?

**Comment by MichaelArestad** [comment] 2020-06-17 19:08
@alaczek That definitely works for the top level items.

**Comment by mtias** [comment] 2020-08-26 13:41
This is something that the them should be addressing. Exposing more tools as needed for the theme to inform how blocks should render is an ongoing part of the work of global styles and theme.json.

**Closed by mtias** 2020-08-26 13:41 UTC
Labels: [Block] Navigation, [Priority] Low, [Type] Enhancement

**Comment by ZebulanStanphill** [comment] 2020-08-29 03:28
@mtias Hold up, shouldn't the Navigation block's top level at least use `currentColor` and a transparent background, rather than the current hardcoded white background?

**Comment by mtias** [comment] 2020-08-29 12:14
I don't think defaulting to transparent menus would be good — it'd likely make text illegible in many circumstances.

**Comment by ZebulanStanphill** [comment] 2020-08-29 19:41
What? Paragraph blocks, Quote blocks, and basically every other text-based block doesn't have a background by default. Considering where Navigation menus are used (usually headers/footers that already have a background color), I don't see why the top-level menu shouldn't have a transparent background. As for the sub-menus, yeah, those should have a solid background by default.

**Comment by mtias** [comment] 2020-08-29 20:14
I was referring to sub-menus. Top-level ones were supposed to be handled with https://github.com/WordPress/gutenberg/pull/23678 and #22327

**Comment by ZebulanStanphill** [comment] 2020-08-29 21:33
Oh, I got confused by your initial comment upon closing this issue (and subsequently misreading the current `style.scss` file). I think this issue was just a duplicate of #22327, so yeah, it's already fixed now.

**Comment by mtias** [comment] 2020-08-30 09:45
Yes, it seems I also got confused :)
