### ISSUE TITLE
JavaScript error: 'Permission denied to access property "nodeType"' when trying to drag a tag

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#6703] opened 2018-05-11 08:30 UTC
**Describe the bug**
When trying to drag a tag (for example, to attempt to reorder them), a JavaScript error occurs (twice in a row):

`Error: Permission denied to access property "nodeType"`
`https://example.com/wp-includes/js/tinymce/tinymce.min.js?ver=4607-20180123 line 9`

This occurs in non-hierarchical custom taxonomy meta boxes (are they still called that?) as well.

**To Reproduce**
1. Add a tag to a post.
2. Click and drag the tag in the editor screen.
3. The JavaScript error occurs. Nothing happens to the tag visually, just an error appears in the console.

**Expected behavior**
No error when attempting to drag the tag.

**Related issues**
A similar error occurs in a different context: #4744.

**Desktop (please complete the following information):**
 - OS: Kubuntu 16.04
 - Browser: Firefox Nightly
 - Version: 61.0a1 (2018-03-31)

**Additional context**
- Gutenberg 2.8.0

**Comment by danielbachhuber** [comment] 2018-05-17 01:16
Hi @SeanDS,

Can you provide direction on how to "drag" tags? I'm unable to:

![dragtags](https://user-images.githubusercontent.com/36432/40151504-486c0bfe-5935-11e8-88e0-460fa217947c.gif)

**Comment by SeanDS** [comment] 2018-05-17 06:15
Hi @danielbachhuber. You can't actually drag them, it's just that when I _attempt_ to do so, the debug bar I have installed goes red to indicate an error (in this case in JavaScript). So, just click and hold on the text of one of the tags and move the mouse. Nothing will happen visually.

**Comment by SeanDS** [comment] 2018-05-17 20:19
The issue doesn't disrupt anything, but it triggers the JavaScript error on my browser. Usually such errors are indicative of some deeper problem, so I thought I'd report it. #4744 appears to trigger the same error.

**Comment by danielbachhuber** [comment] 2018-05-17 22:15
It seems like https://github.com/tinymce/tinymce/issues/2194 is the actual error? I'm still unable to reproduce this.

**Comment by danielbachhuber** [comment] 2018-05-17 22:34
Closing per https://github.com/WordPress/gutenberg/issues/4744#issuecomment-390032908

**Closed by danielbachhuber** 2018-05-17 22:34 UTC
Labels: [Status] Needs More Info
