### ISSUE TITLE
Navigation: submenus transparent and overlapped by block selection outline

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21449] opened 2020-04-07 08:15 UTC
**Describe the bug**

I happen to add a spacer just below the navigation.
Hovering a menu item while the spacer is selected this is seen.

![Screen Shot 2020-04-07 at 10 12 15](https://user-images.githubusercontent.com/5323259/78645890-80e49100-78b8-11ea-8490-29afb0a0d67b.png)

**Chrome**
Live site.

**Comment by karmatosed** [comment] 2020-04-07 11:22
@paaljoachim what browser are you using as I am currently unable to replicate this.

**Comment by paaljoachim** [comment] 2020-04-07 11:30
Hey Tammie. @karmatosed 

Chrome with a custom theme.

I will test this in Twenty Twenty. Chrome. Localhost. 
Clicking to add a submenu. So the drop down arrow is seen.

![Screen Shot 2020-04-07 at 13 29 40](https://user-images.githubusercontent.com/5323259/78664261-f0b44500-78d3-11ea-9050-702da33dddde.png)

**Comment by talldan** [comment] 2020-04-20 02:36
I can reproduce this. It looks like two separate issues:
1. The background color of submenu is transparent. This isn't apparent on the other screenshots shown in this PR, but can be seen on the one below.
2. The z-index of the blue outline is higher than the submenu. This is also happening with the outline used on the nav block itself.

<img width="884" alt="Screenshot 2020-04-20 at 10 32 15 am" src="https://user-images.githubusercontent.com/677833/79708667-a7f88500-82f2-11ea-8c68-7559a63a41eb.png">

**Comment by tellthemachines** [comment] 2020-04-20 03:23
see [this comment](https://github.com/WordPress/gutenberg/issues/21454#issuecomment-616276233) for some additional context.

**Comment by adamziel** [comment] 2020-05-07 11:03
I think that's the culprit: https://github.com/WordPress/gutenberg/pull/22167

**Comment by adamziel** [comment] 2020-05-12 08:23
Fixed by https://github.com/WordPress/gutenberg/pull/22228

**Closed by adamziel** 2020-05-12 08:23 UTC
Labels: CSS Styling, [Block] Navigation, [Type] Bug
