### ISSUE TITLE
Add a Row Block

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#32522] opened 2021-06-08 16:19 UTC
## What problem does this address?
The Columns block allows you to do interesting layouts like this, where there are columns of text with different alignments: 

![image](https://user-images.githubusercontent.com/2846578/121221310-6fe43680-c853-11eb-8f42-cd1996a0c8f0.png)

But there isn't an equivalent way to handle this vertically:

![image](https://user-images.githubusercontent.com/2846578/121221438-8d190500-c853-11eb-9fdc-12d5756a96c5.png)

The best approximation is to add a spacer between the top and bottom text, which is subpar for a number of reasons — the spacer maxes out at 500px tall, it looks bad on mobile, there isn't a way to make the spacer take up a percentage of height, etc.

## What is your proposed solution?
Add a row block that acts the same as columns, but vertically instead of horizontally.

**Comment by kjellr** [comment] 2021-07-13 16:52
I think this is more or less a duplicate of https://github.com/WordPress/gutenberg/issues/24473. @melchoyce can you confirm?

**Comment by melchoyce** [comment] 2021-07-13 17:14
Honestly can't tell, that seems more specifically about flexbox integration and horizontal grouping?

**Comment by kjellr** [comment] 2021-07-13 17:46
Hmm yeah maybe it's a little different. The end result is the same though: blocks arranged horizontally in columns.

**Comment by paaljoachim** [comment] 2021-09-13 13:50
@youknowriad merged this PR: https://github.com/WordPress/gutenberg/pull/34535

**Comment by annezazu** [comment] 2022-05-24 23:18
I think this can be closed out with the addition of the Row block in 6.0. If folks disagree, happy to reopen <3

**Closed as completed by annezazu** 2022-05-24 23:18 UTC
Labels: New Block
