### ISSUE TITLE
Hook for saving/updating post in Gutenberg

### ISSUE THREAD

**Issue by wpsoul** [WordPress/gutenberg#40765] opened 2022-05-02 18:10 UTC
In current point we need to use hook like

`subscribe( () => {
  const isSavingPost = select('core/editor').isSavingPost();
  const isAutosavingPost = select('core/editor').isAutosavingPost();

  if ( isAutosavingPost && ! isSavingPost ) {
    return;
  }

  // Do action.
});`

But this trigger to get saving post function from core/editor on any changes in editor. I tried console.log to see when it's triggered and found that in some situations, it's made near 200 requests on just typing a word. So, why do not add hook for Gutenberg the same as we have for PHP hook save_post?

**Comment by t-hamano** [comment] 2022-05-15 09:36
Hi @wpsoul,

Thanks for opening this.
This looks like a duplicate of #17632 / #15568 / #13413, so we will close this issue at once.

I think #17632 is pretty close to this report, although it have been closed.
Can we consolidate the discussion there?

**Closed as completed by t-hamano** 2022-05-15 09:36 UTC
Labels: [Status] Duplicate
