### ISSUE TITLE
Style Revisions: solid border matching background around the preview for revisions

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#57601] opened 2024-01-05 15:49 UTC
Excitedly testing out the new ability to use the Style Book with revisions when I noticed a border exists around the revision preview. This doesn't match with [what I could see in the video of the PR](https://github.com/WordPress/gutenberg/pull/56800) that implemented this new feature.  cc @ramonjd 

https://github.com/WordPress/gutenberg/assets/26996883/071d47a1-1d4c-41b2-8cb9-e39677aa6a56

This is using 6.4.2, GB 17.4.1, and TT3 theme.

**Comment by ramonjd** [comment] 2024-01-05 22:12
Hi @annezazu! 

Thanks for the ping. 

Do you mean the red/white border?

I spun up clean WP instance with TT3, added some revisions, and couldn't reproduce (Gutenberg 17.4.1). 🤔 Also checked with TT4 and TT2. 


https://github.com/WordPress/gutenberg/assets/6458278/e45360e1-7a04-4e25-b174-0e15734ac241



Is it possible that there's a border style on the body in your setup? If you have time, could you reset the global styles and save a few revisions to check?

Thank you!

**Comment by ramonjd** [comment] 2024-01-07 22:18
I retested and couldn't replicate. I also checked the editor container styles and there are no border declarations.

The "Whisper" style variation on TT3 does have a body border style built in, but I can't see that the editor is adding any extra  border styles.

I'll close for now. Please reopen and assign to me if the problem persists.

🙇🏻

**Comment by annezazu** [comment] 2024-01-08 01:32
Yes! I am talking about the border around the zoomed out view. I can still replicate from the site I took the video from using WP 6.4.2, GB 17.4.1, and TT3. Happy to add you to the site. We've used it for demos in the past ahead of releases.

**Comment by ramonjd** [comment] 2024-01-08 01:39
> Happy to add you to the site. We've used it for demos in the past ahead of releases

Thanks! Yes please. It'd be great to see the test site. I'll report back here.

**Comment by ramonjd** [comment] 2024-01-11 03:11
🤦🏻 

Firstly, sorry for closing this prematurely, and missing the complete obvious.

I've been able to replicate thanks to @annezazu 🙇🏻 

PR here:

- https://github.com/WordPress/gutenberg/pull/57748

**Comment by annezazu** [comment] 2024-01-11 19:55
Thanks so much for tracking this down!

**Comment by ramonjd** [comment] 2024-01-11 20:42
> Thanks so much for tracking this down!

And to you for pointing me in the right direction 🚀

**Closed as completed** 2024-01-12 01:47 UTC
Labels: [Type] Bug, [Status] In Progress, Global Styles
