### ISSUE TITLE
Modal navigation: getting trapped in site editor outside the navigation

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#51291] opened 2023-06-07 11:40 UTC
### Description

When I open the full browser window navigation modal in [Lettre theme](https://wordpress.org/themes/lettre/) using site editor, and then click outside the modal, I cannot get back to edit it easily.

### Step-by-step reproduction instructions

- Using [Lettre theme](https://wordpress.org/themes/lettre/)
- In site editor
- Click yourself into header template, and navigation hamburger icon, and open the navigation modal.
- All is fine, you can edit the navigation styles
- Click outside the navigation. I think you end up selecting something _outside_ the header, but I'm not sure.
- The navigation modal stays open.
- I cannot enter navigation modal by clicking the editor canvas anymore
- I can enter navigation modal via List view

Maybe ther problem is that navigation modal isn't closing, yet editing context is switched to something else? Or that I cannot enter back to header just by clicking it again? Result feels buggy.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/87168/6089b5fe-f603-458e-8678-873cede90b6f

### Environment info

- Gutenberg v15.8.1
- Chrome browser
- [Lettre theme](https://wordpress.org/themes/lettre/)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by aurooba** [comment] 2023-06-07 15:42
@simison Thanks for adding this report! When you open the menu modal in the site editor, the way to close it is by clicking the `X` close icon. I've attached a screenshot where I'm doing it in the Twenty Twenty Three theme.

https://github.com/WordPress/gutenberg/assets/6925260/125033a1-e005-4f0b-9fe4-75fbdd60b9f9

I did also test the Lettre theme you mentioned and it looks like the styling in that theme makes the close icon hard to select in the header, although with a few tries, I did manage it. This is definitely something you should take up with the theme author. I hope that helps!

I'm closing this issue because it doesn't seem to be a problem with Core or Gutenberg, but rather is affected by the theme styling. But if you find that the issue is replicable in other themes/plugins and is related to Core or Gutenberg, this issue can be reopened!

**Comment by scruffian** [comment] 2023-06-09 14:05
I think the problem here is that the blocks behind the navigation overlay can be selected. I proposed a fix in https://github.com/WordPress/gutenberg/pull/51378.

**Comment by scruffian** [comment] 2023-06-23 00:01
Closed by https://github.com/WordPress/gutenberg/pull/51378#event-9604330626

**Closed as completed by scruffian** 2023-06-23 00:01 UTC
Labels: [Type] Bug, [Block] Navigation, [Feature] Site Editor
