### ISSUE TITLE
No templates or template parts found when activating a block theme

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36325] opened 2021-11-08 20:15 UTC
### Description

After activating TT1 and TT2 (thank you @jffng for confirming) while using WP 5.8.2 and Gutenberg 11.9RC3, if you head to Appearance > Templates there are no templates found to edit. The same is true for template parts. 

### Step-by-step reproduction instructions

1. Activate Gutenberg 11.9 RC 3.
2. Install and activate TT1.
3. Go to Appearance > Templates.
4. See no templates :) 

### Environment info

- WordPress 5.8.2
- Gutenberg 11.9 RC3
- TT1 blocks
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2021-11-09 07:04
Are there any user created templates or template parts?
Because those are the only templates and parts that will show up, since they are saved in the database.
I can confirm that templates with saved changes and custom templates show up.

Displaying the theme files has not been implemented yet: https://github.com/WordPress/gutenberg/issues/35994

**Comment by kevin940726** [comment] 2021-11-09 07:08
Yep, this should be a duplicate of #35994. I'll close this for now, but feel free to re-open it if it's not the case.

**Closed as completed by kevin940726** 2021-11-09 07:08 UTC
Labels: [Type] Bug

**Comment by annezazu** [comment] 2021-11-09 16:15
Ah ha! Thank you for connecting these dots :)
