### ISSUE TITLE
Feature Request: Change the color (or other visual queue) for Reusable Blocks

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#40311] opened 2022-04-13 11:11 UTC
### **Issue**
The value of reusable blocks is being able to make a change in one place and have that change reflected across an entire website (awesome!).

However, I foresee clients being confused about what _is_ and _is not_ a reusable block. Although they are named and when you save you get a list of what was changed, they are not distinct enough from "regular blocks".

### **Proposed Solution**
 I think there needs to be a more obvious visual queue to distinguish reusable blocks from others. 

Elegant Themes' Divi does this very well with global modules (see screenshot below). Anything in Lime Green is a global module - so a user knows if they make a change there it will affect the entire site - whereas if they make a change in the regular module, it's for that page only.

![Screen Shot 2022-04-13 at 7 01 26 AM](https://user-images.githubusercontent.com/43501707/163167552-91989aec-936f-4391-b597-8e03068fb610.png)

Either a highlight around the reusable block on hovering in the visual panel and/or even a highlighted background or outline in the List View would be easy to communicate to clients - "if you make a change to this highlighted block, it's going to change everything."

![Screen Shot 2022-04-13 at 7 08 59 AM](https://user-images.githubusercontent.com/43501707/163167855-0ed0adc7-9412-4515-a8d6-a3faff7f3562.png)

**Comment by annezazu** [comment] 2022-04-13 23:45
Thanks for opening this issue! I see it as a duplicate of this one: https://github.com/WordPress/gutenberg/issues/32163 Can you confirm if I've missed anything and if you agree that it's a duplicate? If so, I'll go ahead and close this out.

**Comment by samxmunoz** [comment] 2022-04-14 10:54
@annezazu - yes, that one definitely sums up my thoughts! Thank you!

**Comment by annezazu** [comment] 2022-04-14 17:28
Awesome! Closing this one out -- thanks so much for giving feedback and opening this up to begin with.

**Closed as completed by annezazu** 2022-04-14 17:28 UTC
