### ISSUE TITLE
6.1.1 - Setting a 49%+ for width of a child column breaks column

### ISSUE THREAD

**Issue by theRealHal9000** [WordPress/gutenberg#46009] opened 2022-11-23 15:00 UTC
### Description

We previously set % widths for most of our child columns for more granular control. After 6.1.1 those sizes are no longer working/accurate.

Please see the attached recording.

Setting any flex-basis greater than 48% breaks the two columns, forcing the 2nd column down. I understand there are a lot of different factors causing this, but using 50% worked previously, which is why this is head-scratching.

### Step-by-step reproduction instructions

1. Create a new column
2. Set a column split like 50/50
3. Add something to the two new blocks
4. In the two child columns set a column width of 50%

### Screenshots, screen recording, code snippet

[Uploading Column Width-1.webm…]()

### Environment info

-Wordpress 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment] 2022-11-23 22:26
Thanks for the report @theRealHal9000 ! Could you add the recording again? It doesn't seem to have uploaded properly.

Going through those steps with Twenty Twenty and Twenty Twenty Three themes, I couldn't reproduce the issue. Are you using a custom theme, or a non-default theme at all? Might there be an incompatibility with the styles from that theme?

**Comment by tellthemachines** [comment] 2022-11-23 22:43
Oooh, I wonder if this could be related to #45713

**Comment by theRealHal9000** [comment] 2022-11-25 16:11
[flex-basis issue.webm](https://user-images.githubusercontent.com/14895842/204022470-3c144c1c-102d-462e-9c02-8d8b4ef8d158.webm)
Hopefully this upload works.

Setting the column width in the editor adds {flex-basis: n%} to wherever. I only tested this with 2 columns at 50%, but there might be more.

**Comment by ndiego** [comment] 2022-11-29 14:42
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg, WordPress, and the Twenty Twenty-Three theme. I have included a gif below. 

Would you be able to share the theme that you are using?

![columns](https://user-images.githubusercontent.com/4832319/204559149-3f91fb87-49ea-42ed-b545-5a4cc577cef2.gif)

**Comment by ndiego** [comment] 2022-12-13 15:03
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.

**Closed as completed by ndiego** 2022-12-13 15:03 UTC
Labels: [Type] Bug, [Status] Needs More Info, Needs Testing, [Block] Columns
