### ISSUE TITLE
WP 6.3 Beta: Too many unnecessary clicks to set a link to open in new tab, please, keep it simple

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#52489] opened 2023-07-10 21:34 UTC
In WordPress 6.3 Beta, setting a link to open in a new tab is a bad experience, it takes too many clicks.

In the current WordPress, two clicks are enough, in the beta version it takes 5 clicks. This is much more annoying and makes editing less productive. Why add this complexity? Please leave it simple as it is, it's much better.

Another advantage in the current version is that you just have to click on the link to be able to check if it is set to open in a new tab or not, whereas in the development version more clicks are required.

**Comparing the two versions:**

**WordPress 6.2.2: simple, good using experience**

[Wordpress new tab.webm](https://github.com/WordPress/gutenberg/assets/11923491/39c7b74c-92b2-4c4b-a884-482e519b4c14)

**WordPress 6.3 beta3-56182: too many clicks, bad user experience**

[Wordpress beta new tab.webm](https://github.com/WordPress/gutenberg/assets/11923491/39c0cdc2-cad8-490e-953e-9ede052d7ecd)

**Comment by jordesign** [comment] 2023-07-11 00:33
Hi @ricjcs - thanks for the report. You're correct that this is something that changes in 6.3 - it was also introduced as part of Gutenberg 16.1

You can see details of the design, decision making and development in this thread - it's definitely something that was a considered and deliberate change. I do understand that for some actions, it introduces some steps - but this was a tradeoff considered worth it.

That being said - I'll leave this open in case there are other reports or additions from people who find similarly.

**Comment by t-hamano** [comment] 2023-07-11 03:00
Hi @ricjcs,

What you see as the problem would be the same as [this comment](https://github.com/WordPress/gutenberg/issues/50891#issuecomment-1621815783). Also, it appears that #52321 is in progress to allow the default state of the drawer to be set.

**Comment by ricjcs** [comment] 2023-07-11 09:39
Hi, thank you very much for the reply.

Honestly, there is so much that can be improved in WordPress/gutenberg, that I don't see much need in spending time and energy on something that works really well.

It seems that the purpose is not to encourage links to be opened in a new tab, perhaps it may make sense in theory, but in day-to-day practice it seems inappropriate to me, furthermore, I think that purpose is already fulfilled by not having this option set by default.

Personally I only set external links to open in a new tab. On sites where there are a lot of external links, having to take so many steps on something that can be done with 2 is really annoying.

Although I do not see the need to implement these changes, adding an option in the editor preferences seems to be a good solution.

Sorry if I'm being too harsh, it's just an opinion. Thank you very much for your attention and work on WordPress!

**Comment by xoex** [comment] 2023-07-11 10:15
I agree with poster. I think it forces user a lot of clicks to do a simple job.

**Comment by Mamaduka** [comment] 2023-07-11 11:04
Thanks, @ricjcs!

I think we can close this as duplicate of #52216.

**Closed as not planned** 2023-07-11 11:04 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Link Editing
