### ISSUE TITLE
SEO problem with Site Title Block

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/gutenberg#45111] opened 2022-10-19 12:14 UTC
### Description

The site title block in the header section of FSE is shared with the theme's templates and thus if you set the site title to use the H1 HTML tag could be OK for a blog posts homepage but it could conflict with user-generated content inside the page, where is common to apply H1 tag to the main claim inside the page.

There's a similar issue when editing a single or page template, where the (shared) header section inherits & shares the site title settings and the site title will conflict with the post/page title, which should be the H1 in a single post/page template. The only solution is to change the site title or post/page title to another heading HTML tag or to a paragraph, and this will offer a worst SEO structure on the homepage (first option) or pages/posts (the second one).

Additionally, the site title block can be changed to a paragraph block in order to get rid of the heading HTML tags, but again is a site-wide change.

I see 2 possible good solutions to this SEO issue:

1. The site title block should be different according to the template being edited (good solution, not only because it solves the SEO issue letting the user ºdecide what HTML tag to apply to the site title depending on the template, but furthermore it will allow a lot more of customization of headers, with this template-based approach.
2. Header (perhaps the footer too) should be template parts editable separately depending on the template being edited (I think this is the best solution because allows full customization of the header(s) and footer(s) per template.

### Step-by-step reproduction instructions

1. Go to Site Editor or Templates Editor
2. Open the header section
3. Edit the Site Title block
4. Changes to Site Title are site-wide, no matter if you are in the Site Editor, Template Editor, or, of course, the Template Parts Editor

### Environment info

- WordPress 6.1-RC1-54541
- Twenty Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-10-19 12:39
The implementation details of which tag to use is up to the theme developer, Gutenberg only offers the set of options the developer can choose from.

- Another way around it is also to use the site title as a paragraph in the site header, and have a separate H1 on the home page.
- From the support requests for Twenty Twenty-Two, we can see that having nested headers or different headers on the home page and the inner pages is more difficult for users, than having the same header on all templates.
- Detecting what the template is, to change the tag depending on the template, may not be as easy since the install can have custom page templates from the theme, user, and plugins.

**Comment by aristath** [comment] 2022-10-19 12:40
Multiple H1 elements on a page are completely valid and have no effect whatsoever on a page's SEO. It used to be the case years ago, but it hasn't been the case for many years. Google even has some videos regarding that same topic, you can watch https://www.youtube.com/watch?v=WsgrSxCmMbM for example.
That being said, if you absolutely want to control the element on a per-template basis, you can definitely do that by using a different header on a per-template basis in FSE 👍

**Comment by fernandotellado** [comment] 2022-10-19 12:48
@carolinan I've detected the issue with Twenty Twenty-Three (default) theme :)

Your first bullet is my option 1, and it's a valid one :) 

@aristath I don't want to begin a SEO debate :D  My point is exactly your second appreciation :)

Thank you all for the responses and interest ;)

I think that, specially being a default WordPres theme it should offer the best option possible: a per template site title block :)

**Comment by carolinan** [comment] 2022-10-19 13:26
TT3 uses a paragraph for the site title, and an H1 on the home template: [Header,](https://github.com/WordPress/twentytwentythree/blob/trunk/parts/header.html#L5) [Home](https://github.com/WordPress/twentytwentythree/blob/trunk/templates/home.html#L5)

**Comment by fernandotellado** [comment] 2022-10-19 14:56
@carolinan I've just reverted changes to templates and template parts and header is shared. If I make any changes in header section of site editor it changes header template part

**Comment by carolinan** [comment] 2022-10-20 08:53
That is correct, is there an issue? If the issue is with the theme please consider closing this issue and opening a new one in the GitHub repository of the theme (linked above).

**Comment by fernandotellado** [comment] 2022-10-20 08:57
Thanks @carolinan but I don't really know if it's a theme or Gut related issue :/

**Comment by kathrynwp** [comment] 2022-10-20 16:25
> I think that, specially being a default WordPres theme it should offer the best option possible: a per template site title block :)

Please open an issue in the Twenty Twenty-Three repo if you would like the developers to consider making a change there:

https://github.com/WordPress/twentytwentythree/issues

I'm going to go ahead and close this one out.

**Closed as not planned by kathrynwp** 2022-10-20 16:25 UTC
Labels: [Type] Enhancement, [Block] Site Title
