### ISSUE TITLE
Sticky Posts not sticking

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#38979] opened 2022-02-22 10:56 UTC
### Description

In TT2 (and all block themes I tested) when I set a post to "Sticky" it doesn't seem to have any impact on the order that the posts are displayed in.

I first noticed this when investigating a [related issue](https://github.com/WordPress/gutenberg/pull/38422#issuecomment-1047352619), but it seems to have become more broken since then...

### Step-by-step reproduction instructions

- Switch to a block theme (e.g. TT2)
- Create a sticky post
- Look at a template with a query loop in it (e.g. home.html)
- Confirm that the sticky post isn't at the top.

### Screenshots, screen recording, code snippet

<img width="1264" alt="Screenshot 2022-02-22 at 10 53 19" src="https://user-images.githubusercontent.com/275961/155118042-0ddd94ce-f0fe-4214-81c1-f2c64f8c9f1e.png">
<img width="309" alt="Screenshot 2022-02-22 at 10 53 45" src="https://user-images.githubusercontent.com/275961/155118057-48baf63a-0192-43af-bcd9-021657f2dca4.png">

### Environment info

- 5.9, trunk, TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment] 2022-02-22 22:18
I am able to reproduce this bug! I've tested on both WordPress 5.9 and WordPress 5.9.1, with TT2.

**Comment by aurooba** [comment] 2022-02-22 22:34
So there's a few things going on here. When you query posts, `wp.data.select("core").getEntityRecords('postType', 'post', {})` with no sticky parameter, it actually doesn't give you the sticky post(s) at the top. So either this should be fixed in the REST API, or we need to alter [this section](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/edit.js#L135-L153) of the `post-template` block to grab any sticky posts if they exist, and pop them on top if the query option for `sticky` is set to `include`, which in this case means if it's empty.

**Comment by scruffian** [comment] 2022-02-23 12:14
I think an API fix makes sense.

**Comment by draganescu** [comment] 2022-04-27 12:40
Another problem here is that when `Inherit query from template` is set the sticky preferences should either be hidden or they should be merged in the global query. Which one is more expected for the user? Given how the sticky behavior works in WordPress (`get_option( 'sticky_posts' );`) I think we should keep the sticky settings and merge them into the global query.

**Comment by draganescu** [comment] 2022-04-27 13:47
The problem with sticky posts not sticking is because `$query->is_home` is not true. Only if `is_home` is true the sticky posts logic is executed. it is weird b/c `is_home()` returns `true`. It is not home because by default there is an `s` query arg which makes the WP_Query think this is a search.

**Comment by draganescu** [comment] 2022-04-27 14:24
#40656 fixes the rendering I think, in a new PR the editor side should be also fixed.

**Closed as completed** 2022-07-06 07:27 UTC
Labels: Needs Testing, [Block] Query Loop
