### ISSUE TITLE
Block Widgets: Not possible to select a group block added to widgets without using the List View or adding content

### ISSUE THREAD

**Issue by jamiepalatnik** [WordPress/gutenberg#43619] opened 2022-08-25 19:30 UTC
### Description

Once a Group block has been added to a block widget area, there is no way to select it to see the block toolbar without using the List View on the widgets.php page. This means block selection/editing/removal isn't available for empty Group blocks in the Customizer.

A workaround is to use the List View in Widgets to select the Group block, or add a block nested in the Group block, and then select the parent block in the block toolbar.

### Step-by-step reproduction instructions

1. Open a site's Customizer view and navigate to a widget area.
2. Add a Group block.
3. Click on the block to select it.

### Screenshots, screen recording, code snippet

Customizer:
![Customizer](https://user-images.githubusercontent.com/30788962/186751163-ef07b3c1-4516-4945-9697-548ed9c014d9.gif)

Widgets:
![Widgets](https://user-images.githubusercontent.com/30788962/186751170-9470953d-9eec-4f06-af41-5a4c1ed7ce31.gif)
 

### Environment info

- Core version: 6.0.1
- Gutenberg version: 13.2.2
- Tested on MacBook Pro, macOS Big Sur
- Tested on Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-08-26 05:43
The other editors have the same issue.

@jasmussen, will #43513 fix this issue?

**Comment by jasmussen** [comment] 2022-08-26 09:52
Thank you for the ping. Yes, 43513 (now merged!) should fix this. Including for other empty container blocks, such as Columns.

**Comment by Mamaduka** [comment] 2022-08-26 10:19
I just tested on the current trunk, and the issue is fixed. Thanks, @jasmussen.

**Closed as completed by Mamaduka** 2022-08-26 10:19 UTC
Labels: [Type] Regression, [Block] Group
