### ISSUE TITLE
IE11: cover image text and inline toolbar misplaced

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5791] opened 2018-03-25 21:32 UTC
In IE11, the cover image text and inline toolbar appear at the top instead of vertically centered:

![screenshot 90](https://user-images.githubusercontent.com/1682452/37880155-88f341b2-3084-11e8-918d-a897bcada99b.png)

For a list of known flexbox bugm see https://github.com/philipwalton/flexbugs

**Comment by kjellr** [comment] 2018-08-06 16:25
I can reproduce. Also, note that the background behind the inline options for the title (Bold, Italic, Strikethrough, Link), has a visual issue as well. Not sure if it's related or not:

![cover-image-title](https://user-images.githubusercontent.com/1202812/43728656-bed42a96-9973-11e8-8d84-609edd432a41.gif)

**Comment by webmandesign** [comment] 2018-08-21 13:05
Hey guys,

The bug is being triggered by `min-height` applied on flexbox container in IE11. Fix seems to be pretty straightforward simply by applying aditional `height` styles. https://github.com/philipwalton/flexbugs/issues/231

Have created #9196 pull request to fix this.

Regards,

Oliver

**Comment by webmandesign** [comment] 2018-08-21 13:16
Actually, I've just retested it and it seems the better fix would be using `::after` pseudo element https://github.com/philipwalton/flexbugs/issues/231#issuecomment-362790042 to account for cases with larger cover image text.

Tested and works for me.

**Comment by brandonpayton** [comment] 2018-09-19 00:09
> Also, note that the background behind the inline options for the title (Bold, Italic, Strikethrough, Link), has a visual issue as well.

I played with this a bit and was able to avoid the visual issue by setting `flex-shrink: 0` for direct children of `.editor-rich-text__inline-toolbar`. I don't know why this is necessary in IE11 though.

After making the entire toolbar visible no matter the width of the entered text, there was still an issue of centering it. The left edge of the toolbar was aligned with the left edge of the text field regardless of the `justify-content: center` property on the toolbar. It's possible IE11 won't center when the flex items overflow their container.

**Comment by kjellr** [comment] 2018-10-24 15:13
Just noting that @ianbelanger79 came across this issue while testing the Twenty Nineteen theme. Would be great to have it fixed in Gutenberg for 5.0, rather than pushing an individual theme stylesheet fix. 

https://github.com/WordPress/twentynineteen/issues/269

**Closed** 2018-11-21 13:51 UTC
Labels: Browser Issues, Needs Dev, [Status] In Progress, [Type] Bug
