### ISSUE TITLE
Images disappearing from gallery block

### ISSUE THREAD

**Issue by arnopeck** [WordPress/gutenberg#10091] opened 2018-09-21 12:22 UTC
After uploadingg imagges in a gallery block, when i save some images are missing, from the gallery.
Even checking the media gallery some images are missing.
When i come back to the editing page i can see JS error about wrong JSON.

**To Reproduce**
1. Edit an article or a page
2. Click on 'insert Gallery Block
3. Drag images (or click select images)
4. Save Article
5 See the problem

**Expected behavior**
Just have my gallery on the article or page.

**Comment by Soean** [comment] 2018-09-21 14:45
What is you user role? We have an open issue, if you are not an admin. See #9875 Should be fixed in 3.9.

**Comment by arnopeck** [comment] 2018-09-21 14:52
My user is administrator...

**Comment by designsimply** [comment] 2018-09-27 22:37
> When i come back to the editing page i can see JS error about wrong JSON.

Does the error message that you are seeing say, "The response is not a valid JSON response"?

Is there any chance you would be able to check the Network panel in your browser's web developer tools at the time the error appears to see if there is any more detailed information about the error? Here is an example of a successful response in a test I did, and we would want to know if you see a 400 or 500 error instead of a 200 response:

<img width="1280" alt="screen shot 2018-09-27 at 3 03 51 pm" src="https://user-images.githubusercontent.com/1119271/46170204-256d2800-c26b-11e8-91e3-a18dbcabd637.png">

If you are able to check with a plugin, noting the details from the Server section in Dashboard > Health Check > Debug screen found in the [Health Check](https://wordpress.org/plugins/health-check/) plugin as well as noting what size the images are that you are trying to upload would be good things to document if possible.

**Comment by youknowriad** [comment] 2018-11-03 18:57
Looks like a duplicate of #8935

**Closed by youknowriad** 2018-11-03 18:57 UTC
Labels: Blocks, Media, [Block] Gallery, [Status] Needs More Info
