### ISSUE TITLE
Block search: Expand matching behaviour disabled but looks functional

### ISSUE THREAD

**Issue by anevins12** [WordPress/gutenberg#7279] opened 2018-06-12 09:06 UTC
**Describe the bug**
When searching blocks using the main inserter functionality, the results are shown in an accordion but the accordion is not functional. It is intention that the accordion is not functional, however it should not _look_ like it is functional.

Related to #7065

**To Reproduce**
1. Press the "Add block" icon at the top left
![step1](https://user-images.githubusercontent.com/2318561/41280905-098c167e-6e28-11e8-9dd9-1bf25262efc8.png)

2. Search for a matching block term
![step2](https://user-images.githubusercontent.com/2318561/41280919-1026e2de-6e28-11e8-827d-2ef7024a4e79.png)

3. Press on the accordion trigger
4. Accordion does not function but looks pressable

**Expected behavior**
The accordion should not look like it is functional. Ideally the accordion behaviour should disable and should revert back to headings instead of buttons.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Latest

**Comment by ashwin-pc** [comment] 2019-04-23 23:00
I'm not able to reproduce this issue with the latest build of Gutenberg

**Comment by skorasaurus** [comment] 2020-10-27 14:59
I am not able to reproduce this either on Gutenberg; the accordion is not present when the search results are only 2 (using chrome, ubuntu; gutenberg 9.2.2); this can be closed.  
![Selection_019](https://user-images.githubusercontent.com/955351/97319760-8a791a80-1843-11eb-9549-14012fe5d4d3.jpg)

**Comment by annezazu** [comment] 2020-11-05 18:18
Closing this out due to inability to replicate at this time (thank you @skorasaurus). Feel free to re-open if you can replicate with the latest version of Gutenberg (9.3).

**Closed by annezazu** 2020-11-05 18:18 UTC
Labels: Good First Issue, Needs Dev, [Type] Enhancement
