### ISSUE TITLE
Setup publish date more easier

### ISSUE THREAD

**Issue by kharisecario** [WordPress/gutenberg#8650] opened 2018-08-07 09:37 UTC
When I use gutenberg to publish what it suppose to old posts (let say 10 years ago), the only way to change the date is by scrolling month-by-month. There should be an option to switch by year and month for easy navigation to old date

**Comment by earnjam** [comment] 2018-08-07 11:03
Duplicate of #7241

We're consolidating discussion of enhancements to the date picker on #1311.

**Closed by earnjam** 2018-08-07 11:03 UTC
Labels: [Status] Duplicate, [Type] Enhancement
