### ISSUE TITLE
Alignment: deselecting alignment in some blocks results in an unrecognized block

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7098] opened 2018-06-02 02:34 UTC
The pull quote block has an issue when switching from wide/full alignment back to none. Gives 
"This block appears to have been modified externally." message after switching for an alignment to none.
It generates Actual:

`<blockquote class="wp-block-pullquote alignundefined">`

instead of Expected:

`<blockquote class="wp-block-pullquote alignnone">`

(per console output)

**To Reproduce**

1. Tested with Gutenberg Starter Theme on Firefox.
2. Create a post with a Pull Quote
3. Set it to Wide or Full (probably left/center/right as well, but I didn't test)
4. Update
5. Unset the Wide/Full so that no alighment is picked.
6. Update, then refresh editor
7. Get the "This block appears to have been modified externally." message, and the above console output.

**Comment by designsimply** [comment] 2018-07-16 23:55
Tested and confirmed that selecting then de-selecting any alignment option for the pullquote block results in block becoming unrecognized. I also found that if I click "Convert to Blocks" at that point, the citation is lost.

**Video:** [28s](https://cloudup.com/cuoZtRSc2Uy)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13977&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

Before de-selecting an alignment:

```
<blockquote class="wp-block-pullquote aligncenter">
	<p>People are the best puzzles you’ll never solve.</p><cite>Michael Lopp</cite></blockquote>
```

After de-selecting an alignment:

```
<blockquote class="wp-block-pullquote alignundefined">
	<p> People are the best puzzles you’ll never solve.</p><cite>Michael Lopp</cite></blockquote>
```

Save, refresh the post, click "Convert to Blocks", note that citation is lost:

```
<blockquote class="wp-block-quote">
	<p>People are the best puzzles you’ll never solve.</p>
</blockquote>
```

**Comment by designsimply** [comment] 2018-07-17 00:13
Updated the title to reflect this happens for multiple blocks. The ones I have tested and confirmed so far are:

1. Pullquote
1. Button
1. Gallery

**Comment by aduth** [comment] 2018-07-17 20:37
The issue is that these blocks carelessly concatenate the `align` value, which can be `undefined`:

https://github.com/WordPress/gutenberg/blob/6462f080e54db1c78741d4334c26e6b024323f00/core-blocks/pullquote/index.js#L118

A solution could be to test whether it's assigned, like as is done in the Quote block:

https://github.com/WordPress/gutenberg/blob/6462f080e54db1c78741d4334c26e6b024323f00/core-blocks/quote/index.js#L234

Seems simple enough a fix: Adding "Good First Issue"

**Comment by wpscholar** [comment] 2018-07-25 16:13
It appears that all instances of: 
```js
`align${ align }`
```
have been removed in favor of using the `addAssignedAlign` hook.
(https://github.com/WordPress/gutenberg/blob/master/editor/hooks/align.js#L130)

As such, I think this issue can be closed.

The issue raised by @designsimply doesn't require the alignment to be changed. I was able to add a pullquote block to the page, add a citation, convert to a shared block and the citation was altered (middle character only was retained). However, this appears to be an intermittent issue or some sort of race condition as I've not had it break since. This may warrant a separate ticket and further investigation/testing.

**Comment by sarahmonster** [comment] 2018-07-31 19:03
FYI I tried to reproduce either of these issues when auditing this block (#8329) and couldn't reproduce. It sounds like at least the original issue has been sorted, and the second issue may need to be filed separately if someone is able to reproduce. 🙃

**Comment by wpscholar** [comment] 2018-08-01 20:02
Closing this issue since it can't be reproduced in the current version of Gutenberg.

**Closed by wpscholar** 2018-08-01 20:02 UTC
Labels: Blocks, Good First Issue, [Type] Bug
