### ISSUE TITLE
File Block: file name needs to use PlainText component

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#10967] opened 2018-10-23 18:54 UTC
**Describe the bug**
`formattingControls` of `RichText` should be honored in pasting within the block.`

**To Reproduce**
1. Add a file block
2. Copy this text: [File name](http://example.org)
3. Paste text into file name
4. Note that there's no way to remove the link
5. Save post and reload page
6. Block is now invalid "This block contains unexpected or invalid content."

**Expected behavior**
No formatting should be applied if `formattingControls` is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/617637/47383154-4d359b80-d704-11e8-9eb8-3f1ab2aabd95.png)

**Additional context**
-  Related Slack discussion: https://wordpress.slack.com/archives/C02QB2JS7/p1540301310000100

**Comment by iseulde** [comment] 2018-10-26 07:40
Why can't we just use the `PlainText` component for this? :)

**Comment by nitishkaila** [comment] 2018-10-26 11:15
@ocean90, I have created a PR for solution of above issue. Kindly review it.

**Comment by iseulde** [comment] 2018-10-26 11:20
Worth noting that `PlainText` is an enhanced `textarea` element. I don't know what's more suitable here. You could also use an `input` control.

**Comment by iseulde** [comment] 2018-10-26 11:21
(From what I understand, `RichText` was only used here for how it looks, not for its functionality. :/

**Comment by prajapatisagar** [comment] 2018-11-21 06:38
@ocean90 and @iseulde Is there any update about this ticket? I have also tested this patch and it is working fine.

**Comment by talldan** [comment] 2019-07-18 01:32
In the latest version of Gutenberg it looks like you can remove the link, but that's because the file block now has link formatting. That seems like a new issue that needs to be solved.
![Screen Shot 2019-07-18 at 9 28 57 am](https://user-images.githubusercontent.com/677833/61422517-a0a8e300-a93e-11e9-8f2c-b336ab37a27c.png)

The same problem is also present with the download button.

**Comment by paaljoachim** [comment] 2021-02-20 23:30
WordPress 5.7 beta 3 and Gutenberg plugin 10.
Twenty Twenty One.

Added a file block. Removed the text link. 
This is what I see in the backend.

<img width="671" alt="Screen Shot 2021-02-21 at 00 29 33" src="https://user-images.githubusercontent.com/5323259/108611148-ef9ce100-73db-11eb-81da-dccaf0e3093a.png">

Is the issue still valid based on what was reported?
@ocean90

**Comment by glendaviesnz** [comment] 2021-08-26 06:00
I just retested with WP5.8 and Gutenberg 11.3 and there is still no way to edit/remove a link if linked text is pasted into the filename field.

![file-name-link](https://user-images.githubusercontent.com/3629020/130909125-43a2189a-fdaf-40a4-b788-c3294fd5aa79.gif)

**Comment by aurooba** [comment] 2022-01-25 04:42
^ Working on it!

**Comment by paaljoachim** [comment] 2022-01-25 07:56
Thank you @aurooba 
I went ahead and assigned the issue to you.

**Comment by paaljoachim** [comment] 2022-01-25 08:06
Should the file name, button, and the file become inner blocks?
I assume so as each would have their own properties/options. As the user would then also be able to move each around, and align each as they would like.

I will also bring in this somewhat associated issue (which also could use a closer look):
PDF thumbnail preview
https://github.com/WordPress/gutenberg/issues/15097

**Comment by aurooba** [comment] 2022-01-25 15:20
@paaljoachim I'm going to try two things today: innerBlocks is a good idea, you're right, why can't we make the block more flexible? Also I'm not sure the PlainText component is correct, I think RichText is still the right way to go with the link functionality exposed so it can be changed/edited. I have to test a bit more, because obviously we don't want the initial issue @ocean90 reported to be a thing.

#15097 definitely feels related. I'm going to tackle this issue first, and then I can start some explorations around the PDF issue as well. :)

**Comment by paaljoachim** [comment] 2022-01-25 15:32
That is great! Thank you @aurooba

**Comment by carolinan** [comment] 2023-05-08 05:16
I am no longer able to reproduce the issue.
In WordPress 6.2, it is possible to remove both the text and the link, and there are no validation errors when the content is saved and the page reloaded.

**Comment by paaljoachim** [comment] 2023-05-08 07:17
It is now possible to click into the file name and adjust it directly in the Gutenberg canvas/document area.
![Screenshot 2023-05-08 at 09 16 32](https://user-images.githubusercontent.com/5323259/236759763-0cdecebf-0ca6-4472-b0da-f5855bcd421c.jpg)

We should now be able to close this issue.

@aurooba it would be very helpful if you have a chance to look at the
PDF thumbnail preview issue
https://github.com/WordPress/gutenberg/issues/15097
Thanks!

**Comment by akasunil** [comment] 2024-06-16 09:12
Closing this as can't reproduce with gutenberg 18.5.0

**Closed by akasunil** 2024-06-16 09:12 UTC
Labels: [Type] Bug, Good First Issue, [Status] In Progress, [Block] File
