### ISSUE TITLE
Invariant Violation/Minified React Error #31 on Welcome to The Gutenberg Editor

### ISSUE THREAD

**Issue by cassands** [WordPress/gutenberg#8150] opened 2018-07-23 20:58 UTC
While testing some plugins, I came across an error that made the editor completely disappear from "Welcome to The Gutenberg Editor".  After receiving the error, I deactivated all plugins and successfully reproduced the error.

While I'm not sure if this is anything major given it only occurred on the "Welcome to The Gutenberg Editor" sample post, I wanted to make note of this. I don't know React well enough to know what's going on here or why it's only on one page. 

**Expected Behavior:**
I was expecting the information about the number of paragraphs, etc on the page to be displayed when the circle with an "i" (content structure) was clicked.

**Actual Behavior:**
The entire editor disappeared, everything except for the Wordpress sidebar and header disappearing. A message with 3 buttons appeared [Attempt Recovery], [Copy Post Text], and [Copy Error]. The editor reappeared upon leaving the post and re-entering it.

**Text from Copy Error:**
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20props%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)
    at m ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)
    at Xb ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:79:171)
    at If ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:82:291)
    at v ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:84:389)
    at [redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:88:328
    at rd ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)
    at O ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)
    at yh ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:105:190)
    at lg ([redacted]/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)

**Error Text from URL:**
Objects are not valid as a React child (found: object with keys {type, props}).

**Steps to reproduce:**
On "Welcome to the Gutenberg Editor" Sample Post (draft) 
- Click Anywhere
- click the "i" in a circle (content structure) on the toolbar
 
**Notes about actions taken:**
- Managed to reproduce the error on every block tried on that draft post.
- Was not able to reproduce the error on a different non-draft post.
- Was not able to reproduce the error on a new draft post.
- Error did not go away upon publishing "Welcome to the Gutenberg Editor" sample post.
- Managed to reproduce the error on page information instead of just block information.
- Attempt Recovery did not solve the error.
- Deleting the post and re-entering it through the Gutenberg plugin menu did not solve the error.
- Updating the browser did not solve the error.
- Changing the browser did not solve the error.
- Updated to Gutenberg 3.3.0 today before encountering this error.

I did not try deleting the Gutenberg folder and re-downloading it in case of a corrupt file somewhere.

**Computer Information:**
Windows 7
Browsers Tried:
Opera 54.0.2952.60
Chrome 67.0.3396.99

**Comment by designsimply** [comment] 2018-07-24 00:57
Can you try clearing local browser cache and then try again? If that doesn't solve the problem, could you reply back with notes about which plugins you were testing when the problem happened and if you are able could you deactivate the other plugins to see if that makes the problem go away?

Since I am not sure whether this is a bug or not yet, I'm going to close the issue. If you reply back with more information to confirm the issue then we can reopen!

**Comment by cassands** [comment] 2018-07-24 12:57
It still occurs in both browsers (Opera & Chrome) with the cache cleared. As I mentioned I already tried deactivating all plugins. That had actually been my first thought and I'd originally gone through the diagnostic steps I did, intending to make a report to whichever plugin was the issue. However it still occurs without any plugins active except Gutenberg itself. 

As a bonus I also deleted Gutenberg entirely and re-downloaded it. The issue persists. I then tried IE11 and Firefox 61.0.1 which both give the error as well. This is definitely the weirdest thing I've encountered thus far.

The plugins I was rotating through and testing:
Advanced Gutenberg
Advanced Gutenberg Blocks
Advanced WordPress Backgrounds
Atomic Blocks
Gutenberg Custom Fields
Stackable

All, some, or none of these plugins active, that one page still errors out. I can work around it for now easily enough, but I couldn't pinpoint what was causing it; hence the report.

Thanks for trying to help with this.

**Comment by designsimply** [comment] 2018-07-25 01:58
Thanks for the extra info! I tested today and was able to reproduce the problem using Gutenberg 3.3 and the steps you provided:

1. Click "Gutenberg" in the left menu to open the "Welcome to the Gutenberg Editor" sample post.
1. Click the "Content Structure" icon "(i)" in the editor toolbar.

<strong>Result:</strong> as soon as the Content Structure icon is clicked on the sample post, the following message, options, and console warnings/errors appear:

> The editor has encountered an unexpected error.

* Attempt Recovery
* Copy Post Text
* Copy Error

> block `id` prop in `edit` function is deprecated and will be removed from Gutenberg in 3.4. Please use block `clientId` prop instead. Note: This is a global warning, shown regardless of whether blocks exist using the deprecated prop.
> index.js:1:5685

> Invariant Violation: "Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20props%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
> react-dom.min.82e21c65.js:110:57

![screen shot 2018-07-24 at tue jul 24 7 53 50 pm](https://user-images.githubusercontent.com/1119271/43175281-8d46c472-8f7b-11e8-9a60-b4aaa4a622ab.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php?gutenberg-demo running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by aduth** [comment] 2018-07-25 17:30
I suspect this is a regression caused by #7934, where we are attempting to render one of these RichText values directly as a React child within the DocumentOutline:

```json
{
  "type": "em",
  "props": {
    "children": [
      "Inserter"
    ]
  }
}
```

**Comment by designsimply** [comment] 2018-07-25 18:37
Closing in favor of #8160 (which is a duplicate but more succinct). Thank you for the report @cassands! Please follow #8160 for updates.

**Closed by designsimply** 2018-07-25 18:37 UTC
Labels: Chrome, [Type] Bug

**Comment by KishokanthJeganathan** [comment] 2020-06-22 19:42
Im getting the same error :( Can anyone see where the issue is? 

9:40:34 PM: warning chunk styles [mini-css-extract-plugin]
9:40:34 PM: Conflicting order. Following module has been added:
9:40:34 PM:  * css ./node_modules/css-loader??ref--12-oneOf-0-1!./node_modules/postcss-loader/src??postcss-1!./src/components/index-page/textHolder/textHolder.module.css
9:40:34 PM: despite it was not able to fulfill desired ordering with these modules:
9:40:34 PM:  * css ./node_modules/css-loader??ref--12-oneOf-0-1!./node_modules/postcss-loader/src??postcss-1!./src/components/global/newsLetter/newsLetter.module.css
9:40:34 PM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-template-js
   - while fulfilling desired order of chunk group(s) component---src-pages-index-js
9:40:34 PM: success Building production JavaScript and CSS bundles - 38.116s
9:40:34 PM: success Rewriting compilation hashes - 0.002s
9:40:34 PM: success run queries - 40.046s - 14/14 0.35/s
9:40:40 PM: failed Building static HTML for pages - 5.672s
9:40:40 PM: error Building static HTML failed for path "/blog/historia-falafela"
9:40:40 PM: 
9:40:40 PM: 
9:40:40 PM:   WebpackError: Minified React error #31; visit https://reactjs.org/docs/error-d  ecoder.html?invariant=31&args[]=object%20with%20keys%20%7Bdata%2C%20content%2C  %20nodeType%7D&args[]= for the full message or use the non-minified dev enviro  nment for full errors and additional helpful warnings.
9:40:40 PM:

**Comment by kucharzgotuje** [comment] 2021-02-27 10:43
Same issue here, exactly described here: 
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Brendered%7D&args[]

Tried on fresh, out-of-the-box copy of wordpress without ANY plugins or templates.

**Comment by alex-dev-junior** [comment] 2021-12-14 10:35
![image](https://user-images.githubusercontent.com/59199470/145981736-d09f2204-3a97-4abc-91f2-a66b947c1491.png)
Faced this problem. Could you describe in more detail how to solve it?

Error text:
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Brendered%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nc (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:72:61)
    at http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:81:433
    at T (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:95:472)
    at zj (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:230:156)
    at Th (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:223)
    at tj (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:152)
    at Te (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:151)
    at http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:68
    at unstable_runWithPriority (http://alex/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (http://alex/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
