### ISSUE TITLE
Gallery Block Uploads Keep Freezing

### ISSUE THREAD

**Issue by Kpudlo** [WordPress/gutenberg#24764] opened 2020-08-24 13:15 UTC
**Describe the bug**
When creating multiple Gallery Blocks to a page, uploads to the Media Gallery will freeze when uploading via selecting Media Library > Upload after doing this more than once. 

I've tested on fresh installs of WP Engine, WP Sandbox, and WordPress.com. On the wp.com it provides the error "Updating failed. User cannot access this private blog.".

**To reproduce**
1. Create a fresh install of WordPress
2. Create a new Post
3. Add a Gallery Block and select Media Library > Upload Files
4. Upload one or more images, and follow the prompts to create the Gallery.
5. Repeat steps 3 and 4 one or two more times to see the error. 

**Expected behavior**
Images should upload without issue and they should be able to repeat steps 3-4 as many times as needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4432822/91048803-3014d100-e5ea-11ea-8f51-d855f7a4204a.png)
Uploading failed on wpsandbox.pro

![image](https://user-images.githubusercontent.com/4432822/91048185-42423f80-e5e9-11ea-873a-24dae4c3d464.png)
Uploading failed on wp.com

https://www.loom.com/share/129e1208503b4c4390edaef3afdd8e6b
Video showing issue in action

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 84.0.4147.125

**Comment by annezazu** [comment] 2020-09-02 19:13
@Kpudlo Thanks so much for reporting this. I was able to replicate this as well with 5.5.1 and found the upload flow to be very odd as well. I labeled this appropriately so devs can jump in.

**Comment by annezazu** [comment] 2020-09-03 18:09
Can confirm this does not work with Gutenberg installed in version 8.9.1 either using WordPress 5.5.1 in a new test site with TwentyTwenty and no other plugins active.

**Comment by obenland** [comment] 2020-09-15 22:49
Console shows `Uncaught TypeError: Cannot read property 'text' of undefined (media-views.js:5585)`, [leading to me to this line](https://github.com/WordPress/wordpress-develop/blob/b936a4131db69fe946d2ac3cf9c4d23adbb25e03/src/js/media/views/uploader/status.js#L99).

It looks like `this.$index` only gets properly set for the first gallery instance (or upload instance?). [The underlying code hasn't changed in eight years](https://core.trac.wordpress.org/changeset/22816) which leads me to assume the media modal doesn't get set up properly?

Not sure who Gutenberg's resident Media expert is, @mcsf or @draganescu know maybe?

**Comment by mcsf** [comment] 2020-09-17 10:21
> It looks like `this.$index` only gets properly […]

Thanks for looking into this.

> Not sure who Gutenberg's resident Media expert is […]

Maybe @antpb or @johnbillion can help?

**Comment by talldan** [comment] 2021-02-09 05:46
https://core.trac.wordpress.org/ticket/50142 was also reported in trac and seems to be the same issue.

**Comment by glendaviesnz** [comment] 2021-09-10 02:44
I think this is a duplicate of https://core.trac.wordpress.org/ticket/53169, which was fixed by https://core.trac.wordpress.org/changeset/51123, which is in 5.8, so closing.

**Closed by glendaviesnz** 2021-09-10 02:44 UTC
Labels: [Type] Bug, Needs Dev, Needs Technical Feedback, [Block] Gallery
