### ISSUE TITLE
Remove arbitrary padding when there is a background colour

### ISSUE THREAD

**Issue by phil-sola** [WordPress/gutenberg#49230] opened 2023-03-21 13:31 UTC
## What problem does this address?
I am currently trying to move more and more away from ACF blocks in favour of core blocks, and today while setting up a header template part for my navigation, I wrapped it in a group block to enable the sticky functionality, added a white background colour so the navigation is still visible on scroll, and for some random reason there is padding now added to the group block on the basis that it has a background colour. 

The CSS being applied: 

:where(.wp-block-group.has-background) {
    padding: 1.25em 2.375em;
}

There is already a padding UI setting for the group block so it makes no sense really for this opinionated CSS to be applied. 

I can think of some use cases when this may be helpful but it is so easy to add in the UI, it doesn't seem necessary to have a blanket CSS rule on background colours. 

## What is your proposed solution?
Remove the unneccesary CSS targeting blocks when they have a background colour to apply padding. 

It isn't needed and only gets in the way. I could very easily add padding, if that is what I needed or wanted. The opposite isn't true.

**Comment by cbirdsong** [comment] 2023-03-21 14:39
I think this is a good default, since in most cases you would want to avoid text running right up against the edges of a container and having to manually assign padding every time you add a background color would add a lot of clicks and leave space for someone to forget to do that. 

For your case, couldn't you remove it using the padding controls specifically for your sticky header?

**Comment by fclaussen** [comment] 2023-03-21 14:52
@cbirdsong If this were the case, the padding would be there from the start without the colors.
Why are the colors related to paddings?

**Comment by cbirdsong** [comment] 2023-03-21 15:24
If padding was added universally, group blocks would have a bunch of extra whitespace around them even if you were only using them to adjust non-layout properties like font size and text color:
![CleanShot 2023-03-21 at 10 22 48](https://user-images.githubusercontent.com/1672206/226654284-8ca138ce-a1ec-4d1a-8d7b-15886dc4e6c5.png)

If padding was not added with a background, group blocks with a background color would require the user to add padding in most cases, since generally you wouldn't want text to run directly against the edges of the container:
![CleanShot 2023-03-21 at 10 19 27](https://user-images.githubusercontent.com/1672206/226653298-f9312401-f8bd-456d-8ae8-2ced21d74d0b.png)

**Comment by phil-sola** [comment] 2023-03-21 15:25
> For your case, couldn't you remove it using the padding controls specifically for your sticky header?

Yes I can and have done, but I still don't think this is a good default personally. I don't think the editor should be making decisions for users and theme developers, especially where the UI exists for that specific setting. 

I also don't think padding should be tied to selecting a colour. I understand fully *why* you wouldn't want text running up against the edges of a container, but there are so many other ways to add padding. 

I'm currently forced to override this CSS with custom CSS or assign padding 0 with a load of unneccesary inline styles.

I appreciate this is probably personal preference but I still think we need to be very careful about adding opinionated styles to core blocks, espeically where the UI exists literally for this purpose.

**Comment by fclaussen** [comment] 2023-03-21 16:09
The inconsistency is also bothersome.
Here's an example:

I've added a paragraph and added a background color to it. Now I have padding that I did not have before but the padding control isn't marked with anything. This padding is coming from nowhere visible.
<img width="1276" alt="Screenshot 2023-03-21 at 12 04 33 PM" src="https://user-images.githubusercontent.com/1021860/226668851-00fdf3ba-0a45-4777-99de-7253bb3af698.png">

However, if I just click the padding control it now says 0 and the padding goes away.
<img width="1239" alt="Screenshot 2023-03-21 at 12 05 47 PM" src="https://user-images.githubusercontent.com/1021860/226668978-78b1fcca-05ac-46ba-b8b5-26eb7031c8e3.png">

~~But if I move it to 1 it goes back to the same magical padding as before.~~
<img width="1266" alt="Screenshot 2023-03-21 at 12 06 11 PM" src="https://user-images.githubusercontent.com/1021860/226669079-e9e712e9-32fb-453c-9ca0-15b7562d6237.png">

I just realized looking at both images that the padding is slightly different which is even worse than I thought.
<img width="781" alt="Screenshot 2023-03-21 at 12 08 48 PM" src="https://user-images.githubusercontent.com/1021860/226669897-067ed924-03c8-4b32-abec-349218ad150b.png">

So why not set padding control to 1 instead of putting an obscure padding decision there?

**Comment by cbirdsong** [comment] 2023-03-21 17:27
Yeah, it's really unintuitive. It's much more clear when the slider is a `<select>`-style box, which happens when you add more than 6 or 7 spacing presets[^1]: 
![CleanShot 2023-03-21 at 12 17 04](https://user-images.githubusercontent.com/1672206/226689918-d3e6ec8b-62b4-45a4-9bcf-65e848bd5398.png)

Otherwise, the only way to reset to the default is by clicking on the three dots menu and then clicking the padding item:
![CleanShot 2023-03-21 at 12 18 41](https://user-images.githubusercontent.com/1672206/226690914-6022b950-3ba2-41f1-b46b-45f3f5275ba1.png)

6.2 changes it to say "reset", but it's still buried in the menu:
![CleanShot 2023-03-21 at 12 20 56](https://user-images.githubusercontent.com/1672206/226691385-e5bc89e4-c709-40cc-b696-d0964acede5e.png)

In my opinion, there needs to be a much clearer "revert to default" button on all control types. There is further discussion of this problem in https://github.com/WordPress/gutenberg/issues/43082 and https://github.com/WordPress/gutenberg/issues/47976.

[^1]: This also happens for font sizes.

**Comment by kathrynwp** [comment] 2023-03-21 18:49
Heya @phil-sola this looks like it may be a duplicate of #30725 -  would you mind having a look and confirm? Thanks!

**Comment by phil-sola** [comment] 2023-03-21 19:20
Hi @kathrynwp, you’re absolutely right, sorry I did look as I always do beforehand but couldn’t find that one. Happy for you to close this in favour of the existing issue, sorry for duplicating!

**Comment by kathrynwp** [comment] 2023-03-21 20:48
@phil-sola Absolutely no problem, there are a ton of issues here and it can be tricky to find dupes! Thank you for adding your thoughts to the other issue.

**Closed as not planned by kathrynwp** 2023-03-21 20:48 UTC
Labels: [Type] Enhancement, [Status] Needs More Info, [Feature] Colors
