### ISSUE TITLE
Youtube Emded not showing when viewing page.

### ISSUE THREAD

**Issue by cjpartridge91** [WordPress/gutenberg#12987] opened 2018-12-18 16:35 UTC
**Describe the bug**
When trying to use the Youtube embed block the video does not show up when viewing the page, it only shows the link to the video. Its does show in the wordpress backend but not the frontend.

**To Reproduce**
1. Add a youtube embed block
2. Copy and paste link into block and click embed.
3. View Page
```
<figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio">
    <div class="wp-block-embed__wrapper">
        https://youtu.be/aJ3p6QKg_i8
    </div>
</figure>
```

**Expected behavior**
I expected to see the video embedded when I view the page. However I only see the link.

**Screenshots**
Wordpress backend
![Wordpress backend](https://user-images.githubusercontent.com/22506594/50168004-6e57da00-02b8-11e9-8ad8-eb81571476b3.png)

Wordpress frontend
![Wordpress frontend](https://user-images.githubusercontent.com/22506594/50168027-7adc3280-02b8-11e9-83d6-6f5c2f20c34b.png)

**Desktop**
 - OS: OS X El Capitan Version 10.11.6
 - Browser is chrome
 - Version  71.0.3578.98

**Additional context**
- Latest version of Gutenberg and Wordpress.

**Comment by designsimply** [comment] 2018-12-18 16:58
I tested with WordPress 5.0.1 and Gutenberg 4.7.1 and the and I was able to see a YouTube block normally on the front end.

What theme are you using?

<img width="1280" alt="screen shot 2018-12-18 at tue dec 18 9 55 21 am" src="https://user-images.githubusercontent.com/1119271/50169565-0f3f9880-02ab-11e9-88b3-e5e4181c2bb5.png">
<sup>Tested with WordPress 5.0.1 and Gutenberg 4.7.1 using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by cjpartridge91** [comment] 2018-12-18 17:38
I am using my own custom theme. Here is the dev link: https://wp5test.docerodev.net/sample-page/

**Comment by notnownikki** [comment] 2018-12-18 18:15
Can you reproduce with another theme? I can't reproduce this with any of the default themes.

**Comment by notnownikki** [comment] 2018-12-18 20:31
Glad you got it sorted :smile: I'll close this out as that's working for you now.

**Closed by notnownikki** 2018-12-18 20:31 UTC
Labels: [Block] Embed, [Status] Needs More Info

**Comment by Jmetters** [comment] 2019-08-29 17:43
Which file did you add the code in for your custom themes

**Comment by CODECRATER** [comment] 2019-11-05 16:24
> Ok so I figured out whats different between my theme and the default twentyninteen theme.
> I was using this to display the content on the page:
> 
> ```
> <?php
>     $content = get_the_content();
> ?>
> 
> <?php echo $content; ?>
> ```
> 
> Default theme just uses `<?php the_content(); ?>`
> When I changed it to that the video appeared. Didn't realize get_the_content doesn't auto-embed videos.

This worked for me as well, but why?

Is there an intentional difference in Gutenberg between the_content() and get_the_content() ? Or is this a bug?

**Comment by rrikesh** [comment] 2019-12-16 07:31
> This worked for me as well, but why?

`the_content` filter isn't applied when you use `get_the_content()` instead of `the_content()`.

You'd have no issues if you replace 

    <?php echo $content; ?>

by

    <?php echo apply_filters('the_content', $content); ?>
