### ISSUE TITLE
table in mobile is not responsive 

### ISSUE THREAD

**Issue by lelelaileabc** [WordPress/gutenberg#9524] opened 2018-09-01 02:12 UTC
That's not good when I use table in mobile

**Comment by ianbelanger79** [comment] 2018-09-04 20:08
Hi @lelelaileabc,

Thanks for your ticket. Tables are not inherently responsive and cannot really be made responsive due to the limits of the `table` html elements. This is not an issue with Gutenberg, it is an issue with tables. Adding tables into the Classic Editor will result in the same issues on mobile. There are a few plugins in the .org repo that will help to make your tables responsive. I would suggest trying this plugin [Magic Liquidizer Responsive Table](https://wordpress.org/plugins/magic-liquidizer-responsive-table/)

I am going to close this ticket because it is not a bug or feature request.

**Closed by ianbelanger79** 2018-09-04 20:08 UTC
Labels: [Type] Question

**Comment by Lehmax** [comment] 2019-05-16 11:36
I think this issue should probably stay open since the table block looks really bad on mobile. Considering that most users come from mobile devices, I'd consider this a bug. HTML tables can't really be made responsive, but there is a way to make them look much better in [Bootstrap](https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables). Is it possible to implement the required CSS?

**Comment by SchneiderSam** [comment] 2019-05-21 18:41
Yes an + for this issue. That's supposed to be a mushave, isn't it?

See also:
https://github.com/tomusborne/generatepress/issues/92#issuecomment-494479762
