### ISSUE TITLE
Cannot enter `'` in paragraph block

### ISSUE THREAD

**Issue by j-maas** [WordPress/gutenberg#35705] opened 2021-10-16 15:09 UTC
### Description

I want to enter bank credentials on the website for an association. The association's name contains an apostrophe, but since most banks only support ASCII, I'd like to write the name in the bank details with a single quote (`'`).

Single quotes get converted to apostrophes in the preview, and there is no way to escape the single quote.

This issue is related to #15816, but I'm concerned with this specific use case and as far as I understand this other issue is concerned with a bigger problem.

### Step-by-step reproduction instructions

1. Write `Association' Name` in a paragraph block.
2. Preview: It is written `Association‘ Name`.
3. Go to HTML mode and write `Association' Name`.
4. Preview: It is written `Association‘ Name`.
5. In HTML mode, write `Association&#39; Name`.
6. Click somewhere else.
7. The `&#39;` is converted to a single quote, such that the block reads `Association' Name` with the same issues as above.

### Environment info

- WordPress: 5.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by j-maas** [comment] 2021-10-16 15:10
If there is a way I can contribute for this issue, please direct me to where to start looking. :)

**Comment by j-maas** [comment] 2021-11-19 13:15
I found a workaround: Using the "Custom HTML" block I can use `&apos;` to display the single quote without it getting converted.

**Comment by kathrynwp** [comment] 2022-07-12 18:46
Thank you for the report. Since you were able to find a workaround, and since there have been no other reports of this issue from others, I'm going to go ahead and close it out.

**Closed as not planned by kathrynwp** 2022-07-12 18:47 UTC
Labels: [Status] Not Implemented, [Block] Paragraph

**Comment by RatzeR** [comment] 2022-08-05 17:47
@kathrynwp I just found this bug and can confirm, that this bug is still not solved. 

For example: 

- It is not possible to add a apostrophe in a paragraph
- It is not possible to add a apostrophe in a headline in a cover block

**Comment by kathrynwp** [comment] 2022-08-08 15:49
Hi @RatzeR I've been able to add an apostrophe within both a paragraph and cover block without any issues. 

Could you please provide the following so I can investigate further:

- Exact steps to replicate the issue
- What version of WordPress are you using?
- If you also have the standalone Gutenberg plugin active, what version is it?
- Is the issue present with all your plugins temporarily deactivated? You can use the Health Check plugin for this, which will not change your live site – https://wordpress.org/plugins/health-check/
- What theme are you using?
- Is the issue present with a default theme? Again, you can use the Health Check plugin for this.

**Comment by RatzeR** [comment] 2022-08-09 16:43
Hi @kathrynwp, 

maybe may description was a bit unclear. Adding an apostrophe in the backend is possible, but in the frontend no apostrophe is shown. They are converted to a `’` instead of a `'`.

**Steps to reproduce**
- Create a new page
- Add a Cover Block
- Write a text as a headline with an apostrophe, for example `Dem'o`
- Optional: Add a paragraph block below the cover and add the same text
- Save the page
- Open up the frontend
- Check the apostophes - they are converted to a `’` instead of a `'`

**Wordpress Version**
- Wordpress 6.0.1

**Gutenberg Version**
- No extra plugin, just the Gutenberg Version shipped with this Wordpress version

**Plugins / Themes**
- All deactivated with the Health Check Plugin, used Theme: Twenty Twenty
- Also reproducible with my own theme, so this is not a bug caused by the theme

**Comment by kathrynwp** [comment] 2022-08-09 17:01
Thanks for the additional information, @RatzeR

I do think it's the expected behaviour that the editor converts straight quotes/apostrophes to curly quotes/apostrophes; the pre-Gutenberg editor also did this.

**Comment by RatzeR** [comment] 2022-08-09 18:52
@kathrynwp I just found the file where it is implemented: `wp-includes/formatting.php` 

But I do not really understand, whats the reason behind this. Why convert the apostrophe to `&#8217;` instead of `&#39;`?

**Comment by kathrynwp** [comment] 2022-08-09 19:52
@RatzeR I don't know the answer behind that, but you might want to ask in the `#core` channel in [WordPress.org Slack](https://make.wordpress.org/chat/) to see if someone remembers why that is.

**Comment by j-maas** [comment] 2022-08-10 17:31
This is likely because people tend to write single quotations 'like this', since on the keyboard the real quoation marks are missing. The algorithm probably just looks whether the simple mark is at the start or the end of a word and converts it to the starting or ending quotation mark.
