### ISSUE TITLE
List Block: Indentation removed when first item is deleted

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#45494] opened 2022-11-02 16:22 UTC
### Description

When the first item is removed from a list, the indentation is unexpectedly removed from the list block:

https://user-images.githubusercontent.com/36432/199544193-1614925d-f357-4d0b-81cd-70a0e63af832.mp4

I would expect the list's indentation to remain.

### Step-by-step reproduction instructions

1. Create a new List Block.
2. Add three items: `First list item`, `Second list item`, `Third list item`.
3. Remove the first list item.
4. Observe indentation removed from the entire block.

### Environment info

- WordPress 6.2-alpha-20221102.090915
- Gutenberg 14.5.0-rc.1
- Firefox 106.0.3 and Chrome 106.0.5249.119 on Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment] 2022-11-02 18:43
This has been the behaviour since the start of Gutenberg, which I don't like either and want to change with #45075. Closing as a duplicate of #34100.

**Closed as completed by ellatrix** 2022-11-02 18:43 UTC
Labels: [Block] List

**Comment by danielbachhuber** [comment] 2022-11-02 18:48
@ellatrix Makes sense, thanks for clarifying!
