### ISSUE TITLE
IE11: the meta boxes area overlays the post

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13503] opened 2019-01-25 11:55 UTC
Previously #5503.

See also #13328, #11378, and #12455.

Tested with:
- Windows 10
- Internet Explorer 11
- WordPress trunk (5.1)
- Yoast SEO 9.5

Note: I've used the JS snippet from #12455 and the browser is running in Standards mode.

Depending on the length of the post content, the meta boxes area is misplaced: it doesn't stay at the bottom of the page. This is more noticeable when collapsing the meta boxes area, see screenshot below:

- make sure the post has some lengthy content
- collapse the meta box area
- scroll the page

![screenshot 179](https://user-images.githubusercontent.com/1682452/51744450-2b9bd580-20a0-11e9-8455-e46ecdb8e4cb.png)

**Comment by friendofpa** [comment] 2019-05-23 16:58
I can confirm that this issue is still persisting.  If the post body extends the exceeds the desired height the post meta boxes are overflowing through the elements.  As seen in image below:

![Capture](https://user-images.githubusercontent.com/9539235/58271638-7978cf80-7d5a-11e9-90df-52a320f79e32.PNG)

 - Yoast SEO, Custom Fields Plugins
 - Chrome: (Windows 10) Version 74.0.3729.157

**Comment by LordSimal** [comment] 2019-09-13 20:44
I got the same problem with the current Chrome Version 77 but not with Version 76 or Firefox 69 or Safari 12.1.2

I already created a Chrome Issues since it seems to be a render issue.

See https://wordpress.org/support/topic/yoast-12-0-breaks-gutenberg/ for the details

![image](https://user-images.githubusercontent.com/9105243/64893609-c240f500-d677-11e9-85fe-e4dbbbf00127.png)

**Comment by LordSimal** [comment] 2019-09-14 07:49
FYI: My Problem is actually https://github.com/WordPress/gutenberg/issues/17406 which already includes a temporary fix.

**Comment by kajcula** [comment] 2019-11-06 13:24
In CSS `display` for .edit-post-layout__content element is set to `flex` but I think that it isn't necessary. All Gutenberg blocks are stacked one below the other inside this edit-post-layout__content, so this should fix the issue:  Set `display` to `block` for admin styles: 

```
.edit-post-layout__content {
  display: block;
}
```

**Comment by paaljoachim** [comment] 2021-02-21 11:11
Is this still an issue? @tellthemachines 
How can we move this forward?

**Comment by LordSimal** [comment] 2021-02-21 11:27
In the current state I am not able to reproduce it (Yoast 15.8, WP 5.6.1)
![image](https://user-images.githubusercontent.com/9105243/108623557-e2b1d900-743f-11eb-8776-d436fb51b3d3.png)

But as said above my resolution was found in #17406 which basically was a chrome bug, not a gutenberg bug

**Comment by paaljoachim** [comment] 2021-02-21 11:30
I will then go ahead and close this issue.
If I am mistaken then please reopen the issue.

**Closed by paaljoachim** 2021-02-21 11:30 UTC
Labels: Browser Issues, CSS Styling, [Type] Bug, [Type] Regression

**Comment by LordSimal** [comment] 2021-02-21 11:32
Besides the fact that the current yoast doesn't even work anymore with IE11
![image](https://user-images.githubusercontent.com/9105243/108623724-bb0f4080-7440-11eb-84fc-8a58e87b4554.png)

**Comment by paaljoachim** [comment] 2021-02-21 11:34
Microsoft is ending support for IE 11. 
Which means I believe we can also close all IE 11 issues in Gutenberg.
