### ISSUE TITLE
Couldn't Edit Text When I Picked A Custom Size Font for Text Block

### ISSUE THREAD

**Issue by PenofJen** [WordPress/gutenberg#8694] opened 2018-08-07 21:38 UTC
**Describe the bug**
I was playing with the text blocks and the different sizes of fonts. When I tried to use a custom size for a font, I was unable to go back in and edit the actual text in the block.

**To Reproduce**
1. Click on a text block.
2. Use a custom font size. 
3. Try to edit the text.

**Expected behavior**
I felt I should have been able to change the text in the block.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac iOS High Sierra 10.13.6
 - Browser Chrome
 - Version 67.0.3396.9

**Additional context**
- Please add the version of Gutenberg you are using in the description. The one that I downloaded today (8/7) in the dashboard of my Wordpress site. I'm not a programmer as you can probably tell. Just trying to help. : )

**Comment by jorgefilipecosta** [comment] 2018-08-23 08:28
Hi @PenofJen thank you for reporting this issue, I did some tests, and I was not able to replicate the problem. Could you please specify what plugins you have installed on the site?

**Comment by PenofJen** [comment] 2018-08-23 13:27
The only plugin I have installed is Autooptimize. My theme is Brilliant Plus. I just went in and checked and I still can’t edit the text that I did in a custom size. The custom size was 8 pt type. Hope that helps.

Jennifer Pfliegler - The Pen of Jen
Freelance Writer and Editor
> Web: penofjen.com
> Email: jen@thepenofjen.com

**Comment by skorasaurus** [comment] 2018-11-27 16:36
I was unable to replicate this when I had the autooptimize plugin installed (note the plugin's slug is autoptimize for anyone testing this). 

Sorry I can't help further, this may be a bug with your theme; perhaps contact them if you're still experiencing this.

**Comment by jorgefilipecosta** [comment] 2019-06-06 12:25
Thank you for your tests @skorasaurus, given that people are not able to reproduce the issue I'm going to close it for now. If anyone has any additional information, feel free to reopen the issue/comment, and we will look further.

**Closed by jorgefilipecosta** 2019-06-06 12:25 UTC
Labels: Blocks, Needs Testing, [Type] Bug
