### ISSUE TITLE
Image Block: Advanced > Block Name doesn't effect List View

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#57944] opened 2024-01-17 23:51 UTC
### Description

When adding a custom Block Name (under Advanced > Block Name) the new name isn't reflected on the Image Block in the list view.

### Step-by-step reproduction instructions

1. Add a new Page or Popst
2. Insert an image block
3. Go to the Block Settings > Advanced and add a 'Block Name'
4. Open the list view to see the block (without a custom name)

### Screenshots, screen recording, code snippet

<img width="1727" alt="Screenshot 2024-01-18 at 10 49 38 am" src="https://github.com/WordPress/gutenberg/assets/1842363/fbf0731e-518c-4c71-bb38-2e2ff0d64dce">

### Environment info

WP 6.4.2
GB 17.5.0
Twenty Twenty-Four

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2024-01-18 09:54
I was also able to reproduce this problem. In addition to the Image block, I can also reproduce this problem with the Gallery block. In other words, some kind of conflict may be occurring in the block that has a thumbnail image in the list view.

![image](https://github.com/WordPress/gutenberg/assets/54422211/0121cb8e-3fb5-4ad2-9425-ee3b0143d86e)

**Comment by t-hamano** [comment] 2024-01-18 10:35
After investigating this problem, I found that this problem occurs in other blocks besides the Image block. I have summarized the cause of this problem and the tasks to be done in #57954, so I would like to close this issue.

**Closed as completed by t-hamano** 2024-01-18 10:35 UTC
Labels: [Type] Bug, [Block] Image
