### ISSUE TITLE
size-{image size} classes are missing from images in the front-end

### ISSUE THREAD

**Issue by gschoppe** [WordPress/gutenberg#12604] opened 2018-12-05 04:43 UTC
**Describe the bug**
In the existing editor, images announce their size in a class on the image tag. In guteberg this class is missing. As a result, front-end styles and scripts cannot target images based on their size for functionality such as auto lightbox linking or special styling. This breaks compatibility with plugins such as wp-smartcrop, which needs to be able to identify images that are using cropped thumbnail sizes.

This is a breaking regression.

**To Reproduce**
1. create a new post
2. insert an image block
3. publish
4. view post
5. inspect the image tag

**Expected behavior**
The image tag should have two classes attached to it. One is `wp-image-{id}`, and the other is `size-{image-size}`. The first appears, but the second is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/133798/49490450-22b82180-f81e-11e8-9cf5-1048ef797664.png)
This image should have the `size-thumbnail` class attached, but doesn't

**Comment by swissspidy** [comment] 2018-12-05 08:47
Duplicate of #11603.

**Closed by swissspidy** 2018-12-05 08:47 UTC

**Comment by gschoppe** [comment] 2018-12-05 14:17
That issue is tagged as an enhancement when this is clearly a bug that breaks compatibility. I'm trying to make plugins compatible with Gutenberg, under the new insane release cycle, where I now have less than 24 hours to roll an update. Can anyone tell me how to identify a cropped image size vs an uncropped image size, from the front end? I'd be willing to bet this messes with Responsive image src-sets too, since cropped sizes can't be source-sets for uncropped images and vice-versa.

**Comment by designsimply** [comment] 2018-12-05 21:37
@gschoppe the label was because of me! I'm always happy to re-visit labeling and I've updated #11603  with an explanation and to get some extra help on that one.

**Comment by gschoppe** [comment] 2018-12-05 21:52
I appreciate the explanation, and I've added additional context there. it's just very frustrating to find issues like this with the extremely limited notice developers were given of a final release date.
