### ISSUE TITLE
Create a table of contents block

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#18556] opened 2019-11-16 12:23 UTC
Ħêllo,
in my Web‑Dev projects I like to have a table content in a page.
I use pro that TocBot.
I would like to have in GutenBorg an identical system, « T.O.C. Block »
Please do it…

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Not applicable.

**Describe alternatives you've considered**
In TocBot we need to use ID pro links in table of content to work,
so it would be great if gutenberg added automatically `id=""`,
to achieve this.
and in titles <a href="?#title-h2-table-of-contents">Title_n°? :</a> to access table of content block in start of the page, just under in `<main>`.

**Exemple**
```html
<main id="main" class="ui container">

	<article id="article">

		<section id="#section-table-of-contents">
			<fieldset>
				<legend><h2 id="title-h2-table-of-contents"><a href="?#title-h2-table-of-contents">Table de's matière's :</a>
					</h2></legend>

				<div id="js-toc" class="js-toc"></div>
			</fieldset>
		</section>
```

**Comment by draganescu** [comment] 2019-11-19 16:17
Should core include a ToC block?

**Comment by Nemzag** [comment] 2019-11-19 16:19
Da, of course Draganescu.

**Comment by talldan** [comment] 2020-01-14 01:45
Duplicate of #11047

**Closed by talldan** 2020-01-14 01:45 UTC
Labels: Needs Design Feedback, [Package] Blocks, [Type] Enhancement, [Type] Question
