### ISSUE TITLE
Preview page / post don't load if post not saved.

### ISSUE THREAD

**Issue by MarieComet** [WordPress/gutenberg#5375] opened 2018-03-03 17:36 UTC
## Issue Overview
Preview page or post don't load if content not saved before.

WP 4.9.4
Gutenberg 2.3.0
Twenty Seventeen 1.4
Firefox 58.0.2 (64 bits) (Ubuntu)

## Steps to Reproduce (for bugs)
1. Create a page / post
2. Add some blocks
3. Publish page / post
4. Edit block content - or just page/post title
5. Click on "preview"

## Expected Behavior
Preview page / post should open and load preview.

## Current Behavior
Preview tab open, but stay on "Please wait…Generating preview."

## Related Issues and/or PRs
Maybe related to https://github.com/WordPress/gutenberg/issues/4099

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment] 2018-03-06 15:56
Closing as duplicate of #4099

**Closed by youknowriad** 2018-03-06 15:56 UTC
