### ISSUE TITLE
Link not updated when you changed it

### ISSUE THREAD

**Issue by achmedislamic** [WordPress/gutenberg#15587] opened 2019-05-12 08:31 UTC
**Describe the bug**
I have a link on a sentence. When I change it, it doesn't updated to the new link that I provided. But when I click other content and click the link back again, the link is updated.

**To reproduce**
1. Update your post that contain link.
2. Click on the sentence that have link and edit it.
3. When you done changed it, the link not updated right away.

**Expected behavior**
The preview link should be updated.

**Screenshots**
![link-bug-gutenberg](https://user-images.githubusercontent.com/25688207/57579731-c515b880-74d2-11e9-9346-7de9c7e8cabc.gif)

![link-bug-gutenberg-2](https://user-images.githubusercontent.com/25688207/57579759-4705e180-74d3-11e9-956a-38ed5a944f55.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 October 2018 Update
 - Browser Google Chrome
 - Version 74

**Additional context**
- Using latest Wordpress 5.2

**Comment by youknowriad** [comment] 2019-05-12 08:32
Duplicate of #15522

**Closed by youknowriad** 2019-05-12 08:32 UTC
