### ISSUE TITLE
Bugs in non-core legacy widgets (Appearance Widgets screen only)

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#31960] opened 2021-05-18 22:25 UTC
Hi all, I just completed the recent Widgets [Call for Testing](https://make.wordpress.org/core/2021/05/12/help-test-the-widgets-editor-for-wordpress-5-8/) and compiled a list of bugs I noticed with Legacy widgets in the Appearance Widgets editor. I'm adding images as external links to keep this list easy to read!

- Some functionality within SiteOrigins widgets doesn't work. For example, the [SiteOrigin Slider](https://cloudup.com/c_AuLbaB1rY) widget has a notice with a close button that I'm unable to close and expandable/collapsable areas that don't open and close.
- Some widgets are cut off in preview mode, such as the [Astra Address](https://cloudup.com/cr9KfVU6Jc5) widget (spotted in this [blog post](https://shaunandrews.com/2021/05/testing-the-widget-editor-for-wordpress-5-8/) by @shaunandrews)

**Comment by talldan** [comment] 2021-05-27 07:15
#32260 should hopefully take care of the second issue. The top margin that most widgets have on their headers wasn't being taken into account when calculating the size of the preview.

**Comment by kevin940726** [comment] 2021-06-01 01:54
I'm looking into the first issue.

**Comment by kevin940726** [comment] 2021-06-01 05:22
The first issue is a duplicate of #22765, which should be resolved on the plugin author's end. I think we can close this since #32260 is also resolved.

**Closed as completed** 2021-06-01 05:23 UTC
Labels: [Feature] Widgets Screen, [Block] Legacy Widget
