### ISSUE TITLE
NUX Tip Confusion: Asked to Open Settings When Sidebar Already Open, Settings Label Not Available Until Hover

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/gutenberg#9255] opened 2018-08-22 18:56 UTC
**Describe the bug**
One of the NUX tips currently says
```
You’ll find more settings for your page and blocks in the sidebar. Click “Settings” to open it.
```

However, the `Settings` label isn't visible unless the user has hovered over the Settings gear or the See Next Tip link.

Also, the Sidebar is open by default (at least on Desktop), so prompting the user to click the settings gear actually hides these settings.

**To Reproduce**
1. Go to Add New Post in Gutenberg 3.6.2 & stock WP trunk In Incognito Window.
2. Click through first NUX tip to second tip.
3. Sidebar with Block/Document settings is open by default, Settings label not visible unless user has cursor properly positioned to trigger Settings label.

**Expected behavior**
Tip explains the Settings gear or forces identifying label to active state regardless of hover while tip is active.
Tip language describing Settings reflects the default active state (instructions don't result in hiding settings instead of opening).

**Screenshots**
1. Tip asks user to click 'Settings' but that label isn't available if the mouse cursor is off the tip.
<img width="475" alt="screen shot 2018-08-22 at 11 54 52 am" src="https://user-images.githubusercontent.com/9565066/44484284-38ecf980-a602-11e8-9864-6ef714b9cf54.png">

2. Settings sidebar is open by default. Tip encourages clicking again to open, which actually closes the sidebar because it's already active. Toggle nature needs to be explained differently.
<img width="464" alt="screen shot 2018-08-22 at 11 55 53 am" src="https://user-images.githubusercontent.com/9565066/44484326-5c17a900-a602-11e8-8662-8afae84c13c0.png">

**Comment by 0aveRyan** [comment] 2018-08-22 18:59
Also, the direct reference to page should probably be removed from this tip, as it could be Post, Page, Product, etc.

**Comment by jasmussen** [comment] 2018-10-23 12:17
Thanks for the tip, this is actually a duplicate of #8060, so closing as such. But this has a better title, so I'm stealing it!

**Closed by jasmussen** 2018-10-23 12:17 UTC
Labels: NUX, [Type] Bug
