### ISSUE TITLE
Request: Block themes: link 'Customize' button to FSE 'Styles' instead of the old customizer

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36512] opened 2021-11-16 10:08 UTC
## What problem does this address?

When activating a block/FSE theme in Appearance > Themes, the 'Customize' button links to the old classic Customizer.

As this is not applicable to a block theme, this button would be better if it takes the user to the Site Editor or 'Styles' when activating a block theme.

Not too sure whether this would be a Gutenberg enhancement or core WP.

**Comment by annezazu** [comment] 2021-11-16 17:06
Duplicate of this: https://github.com/WordPress/gutenberg/issues/30643

Thank you for opening though!

**Closed as completed by annezazu** 2021-11-16 17:06 UTC

**Comment by Sandstromer** [comment] 2021-11-16 17:19
Thank you for pointing me to the original issue. Guess I didn't look back far enough!
