### ISSUE TITLE
Copy-paste text becomes an image

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/gutenberg#11683] opened 2018-11-09 17:20 UTC
**Describe the bug**
It appears that if you copy text from Adobe Illustrator (rich with style data), and paste it into Gutenberg using Chrome, it gets treated as an image of the text, instead of text.

**To Reproduce**
1. Go to Adobe Illustrator
2. Copy some text
3. In Chrome, paste into Gutenberg
4. See an image in the text block, instead of text.

**Expected behavior**
I expected copied text to be pasted as text.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1
 - Browser: Chrome 70.0.3538.77
 - Gutenberg 4.2.0

**Comment by WraithKenny** [comment] 2018-11-09 17:32
Also note: The pasting creates images in the Media Library.

**Comment by WraithKenny** [comment] 2018-11-09 17:36
Pasting first into VSCode, and then Copying that, somehow "cleans" the text and it's Pasted properly. The Mac Clipboard view looks the same though.

**Comment by WraithKenny** [comment] 2018-11-09 17:58
HA! OK, you smart guys are `console.log()`ing everything!

Anyway, it appears that Illustrator includes information in it's clipboard that isn't accounted for at https://github.com/WordPress/gutenberg/blob/a134d0c3c5e7640f306d5020a1b4257b21982ed2/packages/editor/src/components/rich-text/index.js#L312

My console show `html` as empty, and `plainText` as having content.

So clipboard is actually `item` true, `html` false, and `plainText` true.

I think the line should be `if ( item && ! html && ! plainText ) {`

**Comment by WraithKenny** [comment] 2018-11-09 18:01
However, I don't know the concern about the plain text containing a url, so that might not be a full solution.

**Comment by WraithKenny** [comment] 2018-11-09 18:05
Perhaps a check to see if the plain text is actually a URL, rather than assuming it is and assuming the item is preferred over plainText pasting?

The edge case would be only when copying only an actual URL out of Illustrator (or similar program) as text, and you end up pasting an image of the URL (lol), but I suppose that's livable.

**Comment by WraithKenny** [comment] 2018-11-09 18:58
Or, maybe we actually need user feedback here. An `alert` to confirm either text or image.

**Comment by designsimply** [comment] 2018-11-12 23:51
If you copy text from Adobe Illustrator rich with style data, would you not expect the style data to be part of the paste and possibly be treated as an image since it came from an image editing application (or am I oversimplifying)?

**Comment by designsimply** [comment] 2018-11-13 00:14
Note: I asked for help with this one (because I don't have Adobe Illustrator) and received a confirmation back and am noting it here:

> I can confirm that selecting text in Illustrator and hitting copy, pastes as an image in Gutenberg.. and also Slack. TextEdit on mac receives text however.

https://wordpress.slack.com/archives/C02S78ZAL/p1542067984477700

**Comment by cooen-a-kurokawa** [comment] 2019-11-15 22:11
**Workarounds**

**To Reproduce**
Steps to reproduce the behavior:

1. Go to Adobe Illustrator
2. Copy some text
3. In Chrome, paste「Ctrl」+「shift」+「v」 into Gutenberg
4. text pasted.

**Desktop (please complete the following information):**

OS: Windows10
Browser: Chrome 78.0.3904.87（Official Build） （64 bit）
WordPress 5.2.4
Illustrator(23.1)（64 bit）

**Comment by paaljoachim** [comment] 2021-02-21 01:23
I believe that one will need to do a CTRL + SHIFT + V to paste text without formatting into Gutenberg.
I will close this issue. If I am mistaken it can of course be reopened.

**Closed by paaljoachim** 2021-02-21 01:23 UTC
Labels: [Feature] Raw Handling, [Type] Bug

**Comment by MagdalenaH1** [comment] 2024-11-04 14:12
This is an issue when copying and pasting text from OneNote into Github comments, when using (ctrl + shift + c) + (ctrl + shift + v), or (ctrl + c) + (ctrl + v)
