### ISSUE TITLE
Dash types different in front-end and back-end output.

### ISSUE THREAD

**Issue by danielmcclure** [WordPress/gutenberg#12860] opened 2018-12-13 22:35 UTC
**Describe the bug**
Typing - – — on the backend shows three different lengths, but on the front end, the first two appear as equal length characters. Using HTML entities seems to create different types of dashes again.

**To Reproduce**
1. Go to post editor and type - `-` – `⎇ -`  — `⎇ ⇧ -` into a paragraph block.
2. Type `&dash; &ndash; &mdash; &horbar;` into a Custom HTML block.
3. View difference between front end and back end.

**Expected behavior**
Described above and below.

**Screenshots**
It seems as if maybe Gutenberg converts manually typed dashes and em dashes into en-dashes? The list below shows the steps I took and the code output below was copied from the front end page on brand new installation using WP 5.0.1 and 2019 Theme.

- In the first line I manually typed - – — into a paragraph block (which the editor also tried to turn into a list block)
- In the second line I used &dash; &ndash; &mdash; &horbar;

````
<div class="entry-content">	
Manual Typing (first two characters appear to become the same):
– – —
HTML Entities 
‐ – — ―
</div>
````

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome / Firefox

**Comment by swissspidy** [comment] 2018-12-13 22:38
WordPress has a function called [`wptexturize()`](https://developer.wordpress.org/reference/functions/wptexturize/) which converts dashes like that on the front end. This has been around since the beginning of WordPress. At the same time, the dashes and quotes are never touched in the editor.

So I don't see any regression nor any unexpected behavior here.

**Comment by danielmcclure** [comment] 2018-12-14 00:49
Ah, this must just be the first time I've noticed that particular quirk. 

If we are really going for WYSIWYG then I'd prefer retaining what is typed, but if it is filtered on the front then shouldn't it be filtered on the back-end rendering as well for an accurate preview?

**Comment by iseulde** [comment] 2019-01-29 15:09
See also #13240. We could do this directly in rich text, but it's low priority atm. Closing because the issue exists since a long time.

**Closed by iseulde** 2019-01-29 15:09 UTC
Labels: Feedback, [Component] Rich Text, [Type] Question
