### ISSUE TITLE
Table block: Stripes table text color setting not working in the Twenty Twenty-One theme.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#51828] opened 2023-06-23 05:38 UTC
### Description

I have tested table block with all setting in different different themes and found the stripes table text color not working in the theme twenty twenty-one.

### Step-by-step reproduction instructions

1. Active theme Twenty Twenty-One.
2. Create a new page and take new table block.
3. move to style setting and change stripes setting tab.
4. After change any text color( Do not working it. ).

### Screenshots, screen recording, code snippet

Please check below provided screen recording video for a better understanding issue.

URL: https://share.cleanshot.com/L4VV5KtQZpyhzhTwN7Qw

### Environment info

- WordPress 6.2.2 
- Chrome
- MacBook Air 13

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-06-23 11:20
Hi @VipulUpadala,

Thanks for the report.

I think the problem is that the text color is overridden by the style that Twenty Twenty One has.

I have submitted a ticket because I think this problem should be solved on the theme side. The details of the problem are also described in this ticket.

https://core.trac.wordpress.org/ticket/58608

I would like to close this issue, but if you have any questions, please feel free to comment.

![striped-table](https://github.com/WordPress/gutenberg/assets/54422211/fe5738cc-e499-4a72-8078-e34cff0b5804)

**Closed as completed by t-hamano** 2023-06-23 11:20 UTC
Labels: [Type] WP Core Ticket, [Block] Table
