### ISSUE TITLE
Global Styles - Custom Colors given the same name cannot be applied properly

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#49593] opened 2023-04-04 21:33 UTC
### Description

If custom colors are added in the global styles theme settings with the same name (eg Color 1), it becomes impossible to select any color but the last custom color of that name.

### Step-by-step reproduction instructions

1. Start in site editor
2. Select global styles
3. Colors>Palettes>Custom Colors, add custom colors
4. Select "Show Details" in the menu for custom colors, and rename all the colors to the same name, such as "Color 1"
5. Return to the editor, and try selecting one of these custom color for any block color setting 

### Screenshots, screen recording, code snippet

**Setup**

![Markup on 2023-04-04 at 13:35:31](https://user-images.githubusercontent.com/27249804/229927449-b0889f6a-cac0-4c6c-861f-916d30c27ef6.png)

**Result**

![Markup on 2023-04-04 at 13:37:48](https://user-images.githubusercontent.com/27249804/229927493-6c551440-273c-43e8-9f37-398718132539.png)

### Environment info

Originally reported here: https://github.com/Automattic/wp-calypso/issues/75197
Replicated in WP version 6.2 with all Gutenberg plugin active and deactivated.
Theme: Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment] 2023-04-12 07:03
I believe this issue might be considered a duplicate of https://github.com/WordPress/gutenberg/issues/43197.

The issue was also touched on in a related PR https://github.com/WordPress/gutenberg/pull/43096#issuecomment-1210321423.

**Comment by ramonjd** [comment] 2024-09-24 05:06
I added some thoughts over in: https://github.com/WordPress/gutenberg/issues/43197#issuecomment-2370177475

**Comment by ramonjd** [comment] 2024-10-30 01:18
I think this PR fixes the issue:

- https://github.com/WordPress/gutenberg/pull/65772

but only for duplicate named colors created _after_ that PR.

Is that sufficient to close this issue?

**Comment by aaronrobertshaw** [comment] 2024-10-30 01:59
> Is that sufficient to close this issue?

In my view, yes. 

More than likely, anyone having hit this issue renamed the colors so they could be applied correctly.

**Comment by ramonjd** [comment] 2024-10-30 02:02
Fixed by https://github.com/WordPress/gutenberg/pull/65772

**Closed as completed by ramonjd** 2024-10-30 02:02 UTC
Labels: [Type] Bug, Global Styles
