### ISSUE TITLE
Allow canceling out of setup / edit state

### ISSUE THREAD

**Issue by alexislloyd** [WordPress/gutenberg#12401] opened 2018-11-28 21:44 UTC
Currently, if you go into the "edit" state for a block that offers this option, there is no way to cancel out of that screen and retain the content you had. For example, if I have an image block with an image loaded in it, then I click on the edit button from the image block toolbar, but decide that I don't want to change the image after all, I can't get out of that screen and go back.

I propose adding a text link at the bottom of the edit state to cancel out of that view, as shown in the GIF below. The only question this raises is whether that cancel link should be present in the initial setup state as well or only when you get to this state after having content in the block?

![screen capture on 2018-11-21 at 16-33-50](https://user-images.githubusercontent.com/3238155/49184156-a2c91d80-f32c-11e8-8106-f5029b3f25a2.gif)

**Comment by draganescu** [comment] 2019-02-13 12:52
Specifically for the image block, the behaviour of the Edit icon varies based on the kind of image it contains, from URL or from the media library:

- if I add an image from an URL, then click on the edit Icon, I get to the initial block screen, where I can either upload, add from media library or from URL
- if I upload or add from media library, then click on the edit button, I get the Select or Upload Media dialog.

This means I cannot simply switch in the same block between an image from the media library or an image from an URL. Is this as intended?

**Comment by melchoyce** [comment] 2019-04-09 16:22
Fixed in #14142. See #14795 for adding "cancel" to more blocks.

**Closed by melchoyce** 2019-04-09 16:22 UTC
Labels: Needs Design Feedback, Needs Technical Feedback
