### ISSUE TITLE
Title block Edit as HTML crashes preview

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#3423] opened 2017-11-10 12:22 UTC
When a Title block is opened in Edit as HTML, removing the first H tag will cause the preview to crash.

Tested in Chrome 62.0 and Firefox 56.0
Gutenberg 1.6.1, WordPress 4.8.3 in Multisite mode, PHPv 7.0

To reproduce:

1. Open the Gutenberg demo page
2. Scroll down to the first title block, click the three dots on the right and choose Edit as HTML
3. Remove the `<h2>` tag
4. Click outside the block.

The title will disappear and a warning dialog "This block has suffered from an unhandled error and cannot be previewed."

**Comment by youknowriad** [comment] 2017-11-10 13:36
I agree the workflow can be improved, maybe triggering the warning dialog should be done only if we return to the Visual mode, but this is not really a bug since if you remove the `h2` from a heading block, it can't be parsed as a heading anymore. You could replace by `h3` ... or something else but you can't remove it entirely.

**Comment by RavanH** [comment] 2017-11-10 15:14
yep, i noticed the invalid markup warning in some tests too but that's not the one indeed ... the "invalid markup" warning dialog would be perfectly acceptable ;)

**Comment by EphoxJames** [comment] 2017-11-21 04:56
I looked into this and fixed one problem #3582 but I wasn't getting a block crash only the "This block appears to have been modified externally." dialog, which seems to have been intentional.

It might be good to add an option to return to editing the HTML to that dialog.

**Comment by jorgefilipecosta** [comment] 2017-12-27 14:56
Thank you for your report @RavanH, it looks like on master this problem is solved, the correct "invalid markup warning" is appearing so I'm closing the issue if the problem is still happening to feel free to reopen it.

**Closed by jorgefilipecosta** 2017-12-27 14:56 UTC
Labels: [Type] Bug
