### ISSUE TITLE
No clear visual indication of what blocks are inside Group block

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#19221] opened 2019-12-18 16:37 UTC
**Is your feature request related to a problem? Please describe.**
There is no clear visual indication as to what blocks are inside the Group block. This could confuse users and is not very accessible.
![image](https://user-images.githubusercontent.com/25369857/71104857-64f79b00-21b4-11ea-9f13-cb4fafe734a7.png)

**Describe the solution you'd like**
I would want a dark grey border that surrounds all of the blocks that are within a particular Group block, regardless of what "mode" you are in. (I am testing this using Gutenberg 7.1.)

**Comment by talldan** [comment] 2019-12-19 04:00
Duplicate of #14935.

@Wingo5315 Thanks for reaching out about this—it looks very similar to the above issue so I'm marking it as a duplicate and closing.

**Comment by talldan** [comment] 2019-12-19 04:01
Duplicate of #14935.

**Closed by talldan** 2019-12-19 04:00 UTC
Labels: [Status] Duplicate
