### ISSUE TITLE
Styles variations don't work for blocks using `InnerBlocks`

### ISSUE THREAD

**Issue by macemmek** [WordPress/gutenberg#9897] opened 2018-09-14 08:31 UTC
**Describe the bug**
I'd like to create a custom section block with additional style variants. The section is going to be a wrapper for multiple blocks - so parent block with some inner blocks.
Unfortunately, an attempt of choosing styles triggers an error _Cannot read property 'innerBlocks' of null_
Maybe there's a bug or maybe I'm doing wrong.

**To Reproduce**
Create the block:
```const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks;
const { InnerBlocks } = wp.editor;

export default registerBlockType(
	'my-blocks/section',
	{
		title: __( 'My Section', 'my-blocks' ),
		description: __( 'A section of blocks.', 'my-blocks' ),
		category: 'layout',
		icon: 'index-card',
		keywords: [
			__( 'Text', 'my-blocks' ),
			__( 'Content', 'my-blocks' ),
			__( 'Paragraphs', 'my-blocks' ),
		],
		styles: [
			{ name: 'default', label: __( 'Regular', 'my-blocks' ), isDefault: true },
			{ name: 'intro', label: __( 'Intro', 'my-blocks' ) },
		],
		edit: () => {
			return (
				<InnerBlocks />
			);
		},
		save: () => {
			return (
				<div>
					<InnerBlocks.Content />
				</div>
			);
		},
	},
);
```

1. Insert the block "My Section" into the editor.
2. Click block switcher to choose between style variants.
3. The popup appears: "The editor has encountered an unexpected error.  Attempt Recovery  Copy Post Text  Copy Error"

The copied error is like below:
``` 
TypeError: Cannot read property 'innerBlocks' of null
    at t.value (http://mysite.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1536831520:12:157572)
    at t.value (http://mysite.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1536831520:12:157246)
    at commitLifeCycles (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14939:22)
    at commitAllLifeCycles (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16040:7)
    at HTMLUnknownElement.callCallback (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:14)
    at Object.invokeGuardedCallbackDev (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:16)
    at invokeGuardedCallback (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:29)
    at commitRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16181:7)
    at completeRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17196:34)
    at performWorkOnRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17141:9)
```

**Expected behavior**
Style variants to choose should appear without an error.

**Additional context**
- Gutenberg 3.8.0
- WordPress 4.9.8

**Comment by youknowriad** [comment] 2018-09-17 14:40
This issue raises something interesting:

It's impossible to "preview" a block (Use `<BlockPreview>` component) if this block is a container block. The problem is related to how the `<InnerBlocks>`  component work because it assumes the block is available in the editor while it's not the case when trying to preview a block that hasn't been inserted yet.

One potential solution is to change how `InnerBlocks` component work and instead of fetching the block from the state, we fetched from a context made available by the `BlockEditProvider` which also means `BlockEdit` should be refactored in the same way to accept a `block` object instead of a `clientId`.

Thoughts @aduth and others?

**Comment by aduth** [comment] 2018-09-17 14:46
@youknowriad Would your idea also fall along the same lines of thinking of having an `<Editor value={ [ /* ...blocks */ ] } />` component interface?

**Comment by youknowriad** [comment] 2018-09-17 14:52
@aduth yep, right. I guess if we had `<Editor value={blocks} />` we could refactor the `<BlockPreview />` component to use it instead of using `<BlockEdit />`. We might have a small performance decrease because we need to go through init steps etc...

I guess it's related to #7453

**Comment by aduth** [comment] 2018-09-17 15:01
Also worth noting that initial explorations of block nesting in #3745 created substores similar to what we're talking about here, which was eventually [abandoned](https://github.com/WordPress/gutenberg/pull/3745#issuecomment-358034174).

**Comment by youknowriad** [comment] 2018-11-12 11:18
> Just to get a clearer sense of this, is it accurate to say that blocks with InnerBlocks do not support style variations at present?

That's true. I think we can provide a less than ideal fix for now until the root issue (which requires a big refactoring) is addressed.

What we can do right now, is to use an error boundary around the preview component as it should possible to use the style variation without the need to preview it.

**Comment by mahdiyazdani** [comment] 2018-11-22 17:40
Tested with the latest version of the Gutenberg 4.5.1, but the problem still persists.

**Comment by phpbits** [comment] 2018-12-01 03:49
Same here. Tested and problem still exists. Thanks!

**Comment by phpbits** [comment] 2018-12-08 03:02
@youknowriad  @aduth Are there any fixes available for this issue yet? With 5.0 already available we need to have this issue fixed in order to release our plugin. Do you have function that we can use to check if it's on preview? Like `is_blockPreview` or something. Thanks!

**Comment by carrieforde** [comment] 2018-12-12 23:37
I'd really love to see a fix for this. Adding styles to blocks with `InnerBlocks` has allowed me and my team to create unique variations on a block (for example, a set of steps) with nothing more than a classname change on the parent element. The main workaround we've been using is to manually add the class via the `Advanced` panel, but this isn't a very discoverable solution for our content team.

If there is anything I can do to get my hands dirty and help address this, please let me know--I'd love to help out.

**Comment by drdogbot7** [comment] 2018-12-17 19:46
Is the problem just with the little previews that display in the Inspector?  Those make a lot of sense for things like buttons, but not-so-much for large blocks.

Maybe the simplest solution would just be to have an option to disable/customize the previews in the style selector, as opposed to refactoring InnerBlocks.

for instance:

```
styles: [
	{ name: 'default', label: _x( 'Regular', 'block style' ), isDefault: true },
	{ name: 'large', label: _x( 'Large', 'block style' ) },
],
stylePreviews: FALSE
```

I would be fine with just having a fallback vanilla radio input or dropdown… after all the user will see the effects in the editor anyway.

**Comment by youknowriad** [comment] 2018-12-18 14:09
I'd be fine with an error boundary and we fallback to "no-preview" when there's an error. If anyone has bandwidth for this, go for it.

**Comment by kraftner** [comment] 2018-12-19 16:38
@phpbits Can you elaborate on that fix? I don't get where/what you are doing to bypass the error.

**Comment by phpbits** [comment] 2018-12-19 16:41
@kraftner It's seems that `this.props.insertBlocksAfter` returns undefined on styles preview, so to prevent the errors I chose to do this in order to not display InnerBlocks. I hope this make sense.

**Comment by torounit** [comment] 2018-12-22 17:39
Error when clicking on Style Panel. 

`this.props.block` is null.

https://github.com/WordPress/gutenberg/blob/v4.7.1/packages/editor/src/components/inner-blocks/index.js#L41
and 
https://github.com/WordPress/gutenberg/blob/v4.7.1/packages/editor/src/components/inner-blocks/index.js#L55

**Comment by SpencerCloud** [comment] 2019-01-07 18:10
@phpbits @kraftner Could you let me know where and how the code is implemented? Is this in an `if` statement somewhere, in the `edit:` function? I'm confused on where and how the implementation of `( typeof this.props.insertBlocksAfter !== 'undefined' )` prevents displaying InnerBlocks.

Much appreciated!

**Comment by lushkant** [comment] 2019-01-08 11:11
@SpencerCloud Yes, it's just a conditional check in `edit` function, and let the save function load normally with `<InnerBlocks.Content />`.
Thanks @phpbits for this +1

**Comment by SpencerCloud** [comment] 2019-01-08 13:18
It worked! Thank you both @lushkant @phpbits!

**Comment by jweston491** [comment] 2019-01-10 23:54
@lushkant @phpbits Can you provide a basic example of using `( typeof this.props.insertBlocksAfter !== 'undefined' )` ? 

Here's what I have so far, same error:

`edit(props) {
        const { className, insertBlocksAfter } = props;
        if ( typeof insertBlocksAfter !== 'undefined' ) {
            return (
                <div className={ className }>
                    <InnerBlocks />
                </div>
            ); 
        }
    },

    save() {
        return (
            <div>
                <InnerBlocks.Content />
            </div>
        );
    },`

**Comment by scottblackburn** [comment] 2019-01-15 14:12
Great, thanks @SpencerCloud !

**Comment by hamannjames** [comment] 2019-01-18 23:45
Wanted to comment and ask if this is being looked at? It seems like a pretty significant bug. I'd love to have options for styling my container blocks without having to rely on people pasting in classnames

**Comment by markhowellsmead** [comment] 2019-03-22 16:03
This is still happening as of today with WordPress 5.1.1.

**Comment by hrsetyono** [comment] 2019-03-31 17:44
Does anyone have a snippet on how to disable Style preview on `core/columns`?

It's probably from here https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#editor-blockedit

But I can't figure it out.

**Comment by nicpelletier** [comment] 2019-04-18 20:10
I think this is even more important with the introduction of the Group bloc.

**Comment by strarsis** [comment] 2019-04-23 17:27
+1, just encountered it with the Group block and with the [Description List block](https://github.com/lassemt/wp-block-description-list).

**Comment by hamannjames** [comment] 2019-04-23 17:37
Squeaky wheel gets the grease adding another comment.

**Closed** 2019-05-16 10:03 UTC
Labels: Priority High, [Component] Nested / Inner Blocks, [Component] Style Variations, [Type] Bug

**Comment by mevanloon** [comment] 2019-08-16 15:54
This error, exactly as described by @macemmek, just reared its head again. I'm running 5.2.2, fresh  install, and trying to register a style for the core/cover block. When I click on styles the editor crashes, yielding the following message in the console:

```
TypeError: null is not an object (evaluating 'this.props.block.innerBlocks')
value — block-editor.min.js:55:124070
qi — react-dom.min.js:130:216
ui — react-dom.min.js:133:323
(anonymous function) — react-dom.min.js:158:380
unstable_runWithPriority — react.min.js:27
Vc — react-dom.min.js:158:363
Sc — react-dom.min.js:158:147
Z — react-dom.min.js:156:495
ah — react-dom.min.js:159:229
xf — react-dom.min.js:40
xf
```

Times the amount of styles registered. I've got a couple of sites that use styles like this, and I think this might be a regression somewhere.

**Comment by youknowriad** [comment] 2019-08-16 20:58
@mevanloon It's fixed in the plugin but it's not shipped yet in WordPress Core.

**Comment by hamannjames** [comment] 2019-08-16 21:00
@youknowriad What is the usual timeframe between fixes to the plugin and implementation in WP Core?

**Comment by youknowriad** [comment] 2019-08-16 21:05
That depends on the timeframe of the major Core releases. Core doesn't follow a strict schedule. Here's the planning for the next one. https://make.wordpress.org/core/2019/08/07/wordpress-5-3-planning-roundup/

**Comment by mevanloon** [comment] 2019-08-17 17:47
Thanks @youknowriad, glad to know I'm not going mad. I'll just wait for the proper release then.

**Comment by laras126** [comment] 2019-10-31 15:21
I'm experiencing the same problem when adding a block style to the core/cover block via `wp.blocks.registerBlockStyle`. I am able to apply the style successfully _before_ uploading an image, but when I open the "Change block style or type" panel after an image has been uploaded, the fatal error described above occurs.

**Comment by mbruschi** [comment] 2020-03-05 07:00
Unfortunately I've experienced the same error while registering Block Styles for `core/columns`.

Here is how it's done
```
wp.blocks.registerBlockStyle( 'core/columns',
	// [
	// 	{
	// 		name: 'default',
	// 		label: 'has-no-background-color',
	// 		isDefault: true,
	// 	},...
```

The error code
```
TypeError: Cannot read property 'innerBlocks' of null
    at t.value (http://webshop.localhost/wp-includes/js/dist/block-editor.min.js?ver=2.0.3:55:124070)
    at qi (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:130:198)
    at ui (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:133:320)
    at http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:377
    at unstable_runWithPriority (http://webshop.localhost/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:27:36)
    at Vc (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:360)
    at Sc (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:144)
    at Z (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:156:492)
    at ah (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:159:227)
    at xf (http://webshop.localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:40:45)
```

**Comment by hannahmwool** [comment] 2021-09-27 14:14
Was there ever a resolve here? I get the issue when trying to register a block style for media-text
`wp.blocks.registerBlockStyle( 
    'core/media-text', 
    [
      {
        name: 'padded-background',
        label: 'Padded Background',
      }
    ]
  );`
