### ISSUE TITLE
TypeError: "n is null" for block variations on custom block

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#7925] opened 2018-07-12 09:24 UTC
**Describe the bug**

I created a custom columns block that has two columns. Now I wanted to use the new block variations feature to add three variations, but after adding them and going in the edit mode of the block, I get the error `TypeError: "n is null"` three times in the console (I assume one time for each variant).

I tried to add those variation styles to another custom block and there it works without problems.

I created a Gist with the block’s code: https://gist.github.com/florianbrinkmann/28564f30cbf559ab858c4be548f98704

Does it maybe have something to do with the `compose()` call in the `edit`? I got this part from the paragraph block.

Thanks in advance!

**Comment by florianbrinkmann** [comment] 2018-07-13 12:48
It seems to be related to the `InnerBlocks`. I tried to add the styles to the core column block like this with the current state of the Gutenberg repo:

```
styles: [
	{ name: 'default', label: '50 / 50', isDefault: true },
	{ name: 'one-third-two-thirds', label: 'One third' },
	{ name: 'two-thirds-one-third', label: 'Two third' },
],
```

And get the following error after clicking on the icon to modify the block style of the core columns block:

```
TypeError: block is null
The above error occurred in the <InnerBlocks> component:
```

**Comment by florianbrinkmann** [comment] 2018-08-21 08:07
@Soean could you add the bug label please? :) Here is a small piece of code that should cause the bug:

```
const {
	registerBlockType,
} = wp.blocks;

wp.hooks.addFilter(
	'blocks.registerBlockType',
	'slug/modify-register-block-type',
	modifyRegisterBlockType
);

function modifyRegisterBlockType( settings, name ) {
	if ('core/columns' === name) {
		settings.styles = [
			{ name: 'default', label: 'Standard', isDefault: true },
			{ name: 'style-1', label: 'Style 1' }
		]
	}

	return settings;
}
```

After inserting it, just add a columns block and try to switch the style.

**Comment by youknowriad** [comment] 2018-11-12 11:20
yes, closing as a duplicate of #9897

**Closed by youknowriad** 2018-11-12 11:20 UTC
Labels: [Type] Bug
