### ISSUE TITLE
Fonts defined in theme.json are loaded in frontend, but not in editor (and admin area)

### ISSUE THREAD

**Issue by xoex** [WordPress/gutenberg#52252] opened 2023-07-03 15:09 UTC
### Description

I defined a weighted font (.woff) in theme.json and it loads and works in frontend.
Previously it worked in admin area too, for example in block editor.
I also defined a css so admin navigation menu used this font too.

But in recent gutenberg updates (I don't know exact version but it should be recent like 16) suddenly it doesn't add font styles when in admin area.
I debugged and WP_Fonts_Provider::print_styles() never run in admin.

### Step-by-step reproduction instructions

1. define fonts in theme.json
2. doesn't show up in editor

### Environment info
Astra theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-07-03 19:51
Seems like this relates to the following: https://github.com/WordPress/gutenberg/pull/51770#issuecomment-1613265955 @ndiego thoughts?

**Comment by ndiego** [comment] 2023-07-03 20:04
@xoex can you share some more details about your setup? Which version of Gutenberg and/or WordPress are you running? Also are there any metaboxes present in the post Editor? Thanks, this will help us diagnose the issue further.

**Comment by xoex** [comment] 2023-07-04 11:01
> @xoex can you share some more details about your setup? Which version of Gutenberg and/or WordPress are you running? Also are there any metaboxes present in the post Editor? Thanks, this will help us diagnose the issue further.

Gutenberg 16.1.1
Wordpress 6.2.2



> Seems like this relates to the following: [#51770 (comment)](https://github.com/WordPress/gutenberg/pull/51770#issuecomment-1613265955) @ndiego thoughts?

Yes it's exactly related to this problem, I had cusotm fields enabled and fonts didn't loaded. I disabled custom fields and when no metaboxes exists, fonts became visible in editor.
But fonts are not still loaded in admin area (not editor)

**Comment by annezazu** [comment] 2023-07-04 16:12
Thanks for confirming. I'm going to close this out as a result and let's defer to the main issue referenced above to track this! It's an important issue to solve for 6.3.

**Closed as completed by annezazu** 2023-07-04 16:12 UTC

**Comment by hellofromtonya** [comment] 2023-07-05 15:23
The issue is reported in https://github.com/WordPress/gutenberg/issues/51209. 

The [new Font Face PR](https://github.com/WordPress/gutenberg/pull/51770) referenced in comments above is unrelated as it has not been merged or shipped yet.

Let's move the discussion, investigation, and resolution to https://github.com/WordPress/gutenberg/issues/51209.
