### ISSUE TITLE
IE11: Full size, center aligned images exceed column bounds

### ISSUE THREAD

**Issue by spencerberry** [WordPress/gutenberg#21697] opened 2020-04-17 21:19 UTC
**Describe the bug**
It looks like there are still some lingering IE11 issues with our column blocks, related to images that are set larger than their parent column.

**To reproduce**
1. Create a columns block with 2 or more columns
2. Add an image to a column, set to align center and a size larger than the column (full size is good)
3. Preview in any modern browser, the image conforms to the column's size.
![ChromeColumns](https://user-images.githubusercontent.com/1162736/79614810-316f4380-80b6-11ea-8b3b-f557567fd709.png)

4. Preview in Internet Explorer, where the image exceeds the column's width
![IE11Columns](https://user-images.githubusercontent.com/1162736/79614818-37652480-80b6-11ea-8421-cc035e270a1f.png)

**Editor version (please complete the following information):**
- WordPress version: WordPress.com, which I think is 7.8 right now?

**Desktop (please complete the following information):**
Tested and reproduced in Windows 10, IE11 through browserstack

**Thoughts Beyond**
Sorry I didn't add labels, I might not have permission.

I think it might be related to this bug?
https://github.com/WordPress/gutenberg/pull/17901
There is a min-height: 0; on the column

**Comment by talldan** [comment] 2020-09-01 07:52
Hey @spencerberry 👋 

We discussed this issue in a triage session on slack (https://wordpress.slack.com/archives/C02QB2JS7/p1598939334048300). I couldn't reproduce the bug against a more recent version, so I think this may have been fixed.

Are you able to test again to confirm? Thanks.

**Comment by paaljoachim** [comment] 2021-02-10 15:44
Hi @spencerberry 

I noticed the PR you linked to has been merged. Based on @talldan 's response I believe this issue is not valid any longer, and I will go ahead and close it. If I am mistaken please let us know and it will be reopened.

**Closed by paaljoachim** 2021-02-10 15:44 UTC
Labels: Needs Testing, [Block] Columns, [Block] Image
