### ISSUE TITLE
Shared block not working with columns

### ISSUE THREAD

**Issue by billerickson** [WordPress/gutenberg#6662] opened 2018-05-09 16:04 UTC
**Describe the bug**
When a shared block is created from a Columns block and inserted into different pages, only the outer markup of the block is produced - not the content inside the columns. 

It appears correctly on the original page (frontend + backend), as well as within the Gutenberg editor on the other pages. 

**To Reproduce**
1. Insert a Columns (Experimental) block. 
2. Add content to the columns.
3. Convert to a shared block.
4. Insert into another page. **It will appear correct in the backend editor**.
5. When viewing the page, your block won't be visible. If you view source you'll see the outer markup.

**Expected behavior**
The content of the shared block should be visible on both the frontend and backend. Currently it is only visible on the backend.

**Screenshots**
1. [Shared block with paragraph text](https://cl.ly/1S1y081x3Q0l)
2. [Shared block with images](https://cl.ly/0h1K0s0n2r03)
3. [Markup on frontend](https://cl.ly/0o3t2V3M4723)

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.4
 - Browser Chrome
 - Version 66.0.3359.139 

**Additional context**
- Gutenberg version 2.8.0

**Comment by nk-o** [comment] 2018-05-18 23:45
Additional info:
* Not only Columns but all blocks, that uses **InnerBlocks** (https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks)
* When trying to convert shared block to regular:
    * ![image](https://user-images.githubusercontent.com/14810891/40262248-9981d098-5b0e-11e8-976f-28c94431790a.png)
    * ![image](https://user-images.githubusercontent.com/14810891/40262258-a6e58f40-5b0e-11e8-9f5e-a1882c96b8c7.png)
* Tested in 2.9.0

**Comment by aartjan** [comment] 2018-06-01 12:51
I had the same issue, in my case it turned out to be related to the moving of InnerBlocks to wp.editor (was: wp.blocks)

const {  InnerBlocks} = wp.editor;

Hope this helps....

**Comment by roborourke** [comment] 2018-06-08 14:39
Ah sorry think I created a duplicate of this in #7169

**Comment by roborourke** [comment] 2018-06-08 14:43
The problem is that `gutenberg_render_block()` does nothing with the `innerBlocks` item in the `$block` array. It's tricky because there's nothing in the raw HTML on the PHP side to act as a placeholder or place to consistently inject the output for the inner blocks, so if your `<InnerBlocks.Content/>` component is nested amongst other markup you're gonna have a bad time.

**Comment by mcsf** [comment] 2018-07-13 11:37
IIRC, this was fixed since 2.8.0, but I'm now reporting a regression. See screencast below, and also note the outcome of detaching a saved columns block:

![gutenberg-saved-columns](https://user-images.githubusercontent.com/150562/42689704-69be7e72-8699-11e8-8dce-151f1e609f72.gif)

**Comment by mcsf** [comment] 2018-07-13 11:55
For what it's worth, here's the serialized content of the `wp-block` object stored:

```sh
> …cli post get --field=content $ID
```
```html
<!-- wp:columns -->
<div class="wp-block-columns has-2-columns">
	<!-- wp:column -->
	<div class="wp-block-column">
		<!-- wp:paragraph -->
		<p>Hi</p>
		<!-- /wp:paragraph -->
	</div>
	<!-- /wp:column -->

	<!-- wp:column -->
	<div class="wp-block-column">
		<!-- wp:latest-posts /-->
	</div>
	<!-- /wp:column -->
</div>
<!-- /wp:columns -->
```

**Comment by mcsf** [comment] 2018-07-13 12:14
On further digging, it seems that `gutenberg_parse_blocks`, when called with the above post content, returns an empty array.

**Comment by roborourke** [comment] 2018-07-13 12:38
@mcsf odd, not what I saw. The problem was what I mentioned in my comment above. The nested blocks are available in the `innerBlocks` key of the `$block` var passed to `gutenberg_render_block()` which handles shared blocks but nothing is done with it.

**Closed** 2018-07-19 15:11 UTC
Labels: Shared Blocks, [Component] Nested / Inner Blocks, [Type] Bug
