### ISSUE TITLE
Using the select all keyboard shortcut makes title uneditable

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#35407] opened 2021-10-06 15:55 UTC
### Description

When using the CMD+A shortcut twice with a post's title focused, I end up with all the blocks selected and the title deselected. That is unexpected, I expected to either have a selection that includes the title or not be able to select more than the title. But, even so, the problem is I seem to be stuck unable to edit the title anymore.

### Step-by-step reproduction instructions

1. Add a post
2. Add a title
3. Add some content (more than one block)
4. Click on the title
5. Press CMD+A twice
6. Notice blocks are selected
7. Click to edit the title
8. Notice the title is not editable

### Environment info

OSX, latest safari.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2021-10-12 09:45
I also noticed this bug, and Post Title remains uneditable even after deselecting the blocks.

**Comment by ntsekouras** [comment] 2021-12-22 08:44
Is this something still happening? I couldn't reproduce..

**Comment by Mamaduka** [comment] 2021-12-22 08:51
It was probably fixed via #33699.

**Comment by ntsekouras** [comment] 2021-12-22 09:07
>It was probably fixed via #33699.

Dates don't match though 😄 . Anyway, George can you reproduce though? If not, I guess we could close for now.

**Comment by Mamaduka** [comment] 2021-12-22 09:11
I'm not able to reproduce the "uneditable" part of the issue. CMD + A once selects title; CMD + A twice moves the selection to blocks.

Testing with TT2 theme and Chrome / OSX.

**Comment by ntsekouras** [comment] 2021-12-22 09:30
>Testing with TT2 theme and Chrome / OSX.

I was testing with the same setup 😆 . I now tested with other themes as well and Firefox and still couldn't reproduce. Let's close this.

**Closed as completed by ntsekouras** 2021-12-22 09:30 UTC
Labels: [Type] Bug, [Feature] Writing Flow
