### ISSUE TITLE
Block appender appears when a reusable Heading block is selected

### ISSUE THREAD

**Issue by rowroll** [WordPress/gutenberg#21546] opened 2020-04-11 14:51 UTC
**Describe the bug**
A modified Heading block saved as a Reusable block appears frozen, it neither accepts text or adds a new block when the + is pressed.

**To reproduce**
1. In the editor, click the + and add a Heading block
2. Change the Heading block to be H3, and Align Text Center.
3. Click on Add to reusable blocks
4. Change Resuable Block name to H3C and hit Save
5. Click on the Write heading... text to enter text, but nothing happens.  No text can be entered.
6. Click on the + inside the Reusable block, and find that it does nothing.

**Expected behavior**
I expect in step 5 to see the text I'm trying to enter appear.  I expect in step 6 to have a new block appear when I hit the +.

**Screenshots**
![image](https://user-images.githubusercontent.com/12249954/79046963-61749d80-7c03-11ea-9925-07b1ffd99863.png)
The upper box is the non-working saved reusable block, the lower asdf-text is the text inside a regular Heading block.

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.163

**Additional context**
- Please add the version of Gutenberg you are using in the description: Version 7.8.1

This is the only thing in the console:
load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.4:8 JQMIGRATE: Migrate is installed, version 1.4.1
post.php?post=25380&action=edit:1 [DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"8cf45b233c">​ <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"a13fa8130a">​

**Comment by draganescu** [comment] 2020-04-13 15:09
Howdy @rowroll, while this is not actually a bug - because you need to click edit on a reusable block to make the reusable block's content editable - I did add the Needs Design Feedback label because the (+) appender should probably not appear, and it does according to my testing.

**Comment by rowroll** [comment] 2020-04-13 15:41
Hi, 
Thanks for the clarification @draganescu !  As the Name of the Block was the only thing that got highlighted when I pressed Edit, I did not think to even try adding text to the heading box itself.  Especially since that's not how the original Heading block works at all.  I would say this is pretty unintuitive UI design.

I agree you need to remove the + appender, it seems to add the new block inside the Reusable block, and if you click back into the resuable one, the page goes white with "Uncaught TypeError: Cannot read property 'ref' of undefined at index.js?ver=cba84a3448265f67f4ce6738496d3c00:6  ..."
   
Now, this was my first time of encountering the "Reusable Block" option, and as it stands it's too cumbersome to use (the "edit" and "save" is very slow).  What I wanted was a way to preformat the two blocks I use all the time (Heading and Image), and otherwise have to modify Every. Single. Time. to Align Center.

Is there a way to format the default blocks to align center?  Or do I "just" have to dig into the css?  (I'm not a UI programmer).

Thanks for any insight, I know this isn't a help-forum, but haven't found a good answer anywhere.

**Comment by draganescu** [comment] 2020-04-14 08:52
I believe you can have your theme set this up for you. Gutenberg supports [editor styles](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#editor-styles) and you could have your theme tell the editor to always center the heading and image blocks.

Another option would be to create a plugin that registers a [block style ](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#styles-optional) and in that style center the content. Then in the editor you can make that style the default.

**Comment by noisysocks** [comment] 2020-04-21 04:34
I wasn't able to reproduce what @rowroll described exactly but there definitely is a bug here, as @draganescu mentions, which is that the appender button should not appear when the reusable block is not in editing mode.

To reproduce:

1. Insert a Heading block
2. Convert it to a reusable block
3. Save the reusable block
4. With the block selected, observe that there is an appender in the bottom right

<img width="655" alt="Screen Shot 2020-04-21 at 14 33 02" src="https://user-images.githubusercontent.com/612155/79825723-31848180-83dd-11ea-9b15-c488f1127e2a.png">

**Comment by ntsekouras** [comment] 2020-07-02 09:02
Closing this issue as it's been resolved with this PR https://github.com/WordPress/gutenberg/pull/23584.

**Closed by ntsekouras** 2020-07-02 09:02 UTC
Labels: [Feature] Reusable Blocks, [Type] Bug
