### ISSUE TITLE
WordPress will store post metadata in wp_postmeta table at the time of Autosave.

### ISSUE THREAD

**Issue by dipankardipu123** [WordPress/gutenberg#37060] opened 2021-12-02 12:47 UTC
Can anyone suggest me is there any way we will store metadata in wp_postmeta table. at the time of autosave.
Currently i am using below code:

_> subscribe(() => {
>   const wasAutosavingPost = select('core/editor').isAutosavingPost();
>   if (wasAutosavingPost) {
>     if (select('core').__experimentalGetDirtyEntityRecords().length > 0) {
>       const intervalId = setInterval(() => {
>         if (select('core/editor').isAutosavingPost() === false) {
>           dispatch('core/editor').savePost();
>           clearInterval(intervalId);
>         }
>       }, 100);
>     }
>   }_

Using this code its created new revision in wp database, But I need proper solution.

1. currently i am using all custom blocks.
2. its create  new revision if modify any changes on editor.

Requirement:
1. instead of create new revision it will store all metadata in postmeta table at the time of autosave.

**Comment by hj-collab** [comment] 2022-05-28 18:44
@dipankardipu123 Can you properly format your code? Some code seem to be cut off here.

**Comment by Mamaduka** [comment] 2023-07-18 11:18
This is a duplicate of #16006. The post revisions currently do not support post meta.

Track ticket: https://core.trac.wordpress.org/ticket/20564.

**Closed as completed by Mamaduka** 2023-07-18 11:18 UTC
Labels: [Type] Help Request, [Feature] Saving, [Status] Duplicate, [Feature] History
