### ISSUE TITLE
Page List Block: Crash when deleting All Pages with the keyboard

### ISSUE THREAD

**Issue by georgeh** [WordPress/gutenberg#29722] opened 2021-03-10 14:20 UTC
## Description
If you try to delete the "All Pages" Page List by pressing the delete/backspace key, the block crashes.

## Step-by-step reproduction instructions
1. Insert a Navigation (Horizontal) block
2. Click "All Pages" to create a Page List block inside
3. Select the Page List block
4. Press the delete key

## Expected behaviour
The block is deleted and the Navigation block goes back to its empty state

## Actual behaviour
The block crashes

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/128240/110641941-88738080-8180-11eb-9645-c95ff8f4a9c2.mov

## Errors:

<details>
<summary>Uncaught Error: An error occurred while running 'mapSelect': can't access property "title", Object(...)(...) is undefined</summary>
<pre><code>The error may be correlated with this previous error:
useBlockProps/_useSelect&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=3ad4f21eb8879677ec4ca9bd36d0336b:12300:89
onStoreChange/newMapOutput&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:2221:36
__experimentalMarkListeningStores@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:4606:27
withPlugins/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:4668:30
useSelect/trapSelect&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:2170:21
onStoreChange@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:2220:40
onChange@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:2249:9
instantiate/subscribe&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:3756:13
dispatch@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:981:7
createMiddleware/&lt;/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:838:18
promiseMiddleware/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:3536:14
createResolversCacheMiddleware/&lt;/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:4853:16
dispatch@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:1323:28
unhandledActionControl@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:987:13
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:430:17
any@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:255:12
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:429:30
createRuntime/rungenControls&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:975:18
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:430:17
iterate@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:443:24
runtime@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:465:12
iterator@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:330:9
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:430:17
createRuntime/rungenControls&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:975:18
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:430:17
createRuntime/rungenControls&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:975:18
next/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:439:18
next@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:438:18
yieldValue/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:430:17
iterate@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:443:24
runtime@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:465:12
createRuntime/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:996:14
createRuntime/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:995:12
createMiddleware/&lt;/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=7193c330700014c5057beba3c4b61fad:841:16
promiseMiddleware/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:3536:14
createResolversCacheMiddleware/&lt;/&lt;/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:4853:16
createBoundAction/&lt;@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=8e3e709fa4f33ba76fb67daa3492a202:3870:36
onKeyDown@http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=3ad4f21eb8879677ec4ca9bd36d0336b:12822:20</code></pre>
</details>

<details>
<summary>The above error occurred in the &lt;PageListEdit&gt; component:</summary>
<code><pre>    in PageListEdit (created by Edit)
    in Edit (created by WithToolbarControls(Edit))
    in WithToolbarControls(Edit) (created by WithInspectorControl(WithToolbarControls(Edit)))
    in WithInspectorControl(WithToolbarControls(Edit)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))) (created by WithFilters(Edit))
    in WithFilters(Edit) (created by BlockEdit)
    in BlockEdit (created by BlockListBlock)
    in BlockCrashBoundary (created by BlockListBlock)
    in BlockListBlock (created by (BlockListBlock))
    in (BlockListBlock) (created by ((BlockListBlock)))
    in ((BlockListBlock)) (created by WithFontSizeInlineStyles(((BlockListBlock))))
    in WithFontSizeInlineStyles(((BlockListBlock))) (created by WithFilters(BlockListBlock))
    in WithFilters(BlockListBlock) (created by IfCondition(WithFilters(BlockListBlock)))
    in IfCondition(WithFilters(BlockListBlock)) (created by WithDispatch(IfCondition(WithFilters(BlockListBlock))))
    in WithDispatch(IfCondition(WithFilters(BlockListBlock)))
    in Unknown (created by Pure(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock))))))
    in Pure(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock))))) (created by Items)
    in Items (created by BlockListItems)
    in BlockListItems (created by UncontrolledInnerBlocks)
    in BlockContextProvider (created by UncontrolledInnerBlocks)
    in UncontrolledInnerBlocks (created by Navigation)
    in ul (created by Navigation)
    in nav (created by Navigation)
    in Navigation (created by WithDispatch(Navigation))
    in WithDispatch(Navigation)
    in Unknown (created by WithSelect(WithDispatch(Navigation)))
    in WithSelect(WithDispatch(Navigation)) (created by Edit)
    in Edit (created by WithToolbarControls(Edit))
    in WithToolbarControls(Edit) (created by WithInspectorControl(WithToolbarControls(Edit)))
    in WithInspectorControl(WithToolbarControls(Edit)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))) (created by WithFilters(Edit))
    in WithFilters(Edit) (created by BlockEdit)
    in BlockEdit (created by BlockListBlock)
    in BlockCrashBoundary (created by BlockListBlock)
    in BlockListBlock (created by (BlockListBlock))
    in (BlockListBlock) (created by ((BlockListBlock)))
    in ((BlockListBlock)) (created by WithFontSizeInlineStyles(((BlockListBlock))))
    in WithFontSizeInlineStyles(((BlockListBlock))) (created by WithFilters(BlockListBlock))
    in WithFilters(BlockListBlock) (created by IfCondition(WithFilters(BlockListBlock)))
    in IfCondition(WithFilters(BlockListBlock)) (created by WithDispatch(IfCondition(WithFilters(BlockListBlock))))
    in WithDispatch(IfCondition(WithFilters(BlockListBlock)))
    in Unknown (created by Pure(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock))))))
    in Pure(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock))))) (created by Items)
    in Items (created by BlockListItems)
    in BlockListItems (created by BlockList)
    in div (created by BlockList)
    in BlockList (created by VisualEditor)
    in div (created by WritingFlow)
    in WritingFlow (created by VisualEditor)
    in div (created by VisualEditor)
    in div (created by VisualEditor)
    in VisualEditor (created by Layout)
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in div (created by ForwardRef(InterfaceSkeleton))
    in ForwardRef(InterfaceSkeleton) (created by Layout)
    in Layout (created by Editor)
    in ErrorBoundary (created by Editor)
    in BlockEditorProvider
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(BlockEditorProvider) (created by EditorProvider)
    in BlockContextProvider (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EditorProvider
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(EditorProvider) (created by Editor)
    in DropZoneContextProvider (created by Editor)
    in SlotFillProvider (created by Provider)
    in SlotFillProvider (created by Provider)
    in Provider (created by Editor)
    in StrictMode (created by Editor)
    in Editor</pre></code>
</details>

## WordPress information
- WordPress version: 5.8-alpha-50460 via wp-env
- Gutenberg version: trunk 
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes 

## Device information
- Device:  Laptop
- Operating system:  macOS Big Sur 11.2.2
- Browser:  Firefox Developer Edition 87.0b6

**Comment by georgeh** [comment] 2021-03-10 16:01
@Quintis1212 thanks for taking a look! I'm running Gutenberg on `trunk` with the latest commit [96b6588](https://github.com/WordPress/gutenberg/commit/96b6588625542888b3f7cca7208be840bbeb675f). I had trouble reproducing initially too. I think the key parts are that it has to be a fresh Navigation block and it has to be deleted with the keyboard. @jasmussen initially found this and was able to make it happen consistently. I am testing it inside a post, not with FSE, if that helps too.

**Comment by Quintis1212** [comment] 2021-03-10 17:06
@georgeh  when I started to delete nav block by pressing delete key it cause errors that you showed here, but when I delete nav block there was no errors. I will try to fix this )

**Comment by Quintis1212** [comment] 2021-03-10 20:53
Well , it seems title variable is missed when its transfered from useBlockProps to use Select function.
Even when i made changing below error still was :
path - gutenberg/packages/block-editor/src/components/block-list/use-block-props/index.js
`
				blockTitle: getBlockType( blockName ).title || "nav",
`

Than useSelect call useSelector function but variable title undefined
Can any one help with this bug ?

**Comment by talldan** [comment] 2021-03-11 02:32
Closing as a duplicate of #29498

**Closed by talldan** 2021-03-11 02:32 UTC
Labels: [Block] Navigation, [Block] Page List, [Feature] Navigation Screen, [Package] Edit Navigation, [Type] Bug, [Type] Regression
