### ISSUE TITLE
Horizontal scrollbar in right-aligned verse block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/gutenberg#13075] opened 2018-12-22 11:26 UTC
**Describe the bug**
Add verse block, write the content in add setting Align text right see the issue

**To Reproduce**

1. Click on Verse block
2. Write caption....
3. Align text right

**Screenshots**

![verse](https://user-images.githubusercontent.com/45058029/50373777-9a9d8e80-0609-11e9-9483-6a25240917ac.gif)

**Desktop (please complete the following information):**
OS: Linux
Browser Chrome
Version 71.0.3578.98
Additional context

**Gutenberg: latest from master**
WordPress: 5.0.2

**Comment by laurelfulford** [comment] 2019-02-20 20:09
This was also reported to the Core Trac as an issue for Twenty Nineteen: https://core.trac.wordpress.org/ticket/46221

I wasn't able to reproduce it with the other default themes -- I haven't tested beyond that, but it seems like this is coming from the theme's styles, rather than the block.

**Comment by youknowriad** [comment] 2019-11-18 09:28
Closing as this seems to be a Twenty Nineteen bug already tracked in Core.

**Closed by youknowriad** 2019-11-18 09:28 UTC
Labels: [Block] Verse, [Type] Bug
