### ISSUE TITLE
There is a inconvenient function in Gutenberg when transfer classical html code

### ISSUE THREAD

**Issue by a2d8a4v** [WordPress/gutenberg#12666] opened 2018-12-07 01:44 UTC
**Describe the bug**

Hello, Gutenberg team. I found Gutenberg will change my html code even if in classical blocks.
And the most inconvenient part is that, it will change the [code] blocks like some functions or command of the special characters, which we do not make changes.

For instance, " will be change to ;quote, &amp;&amp; will be changed to &amp;&amp;
which is useless for our articles, and make us put more unnecessary strength on modifying our articles, some please fix this bug!

Thank you for your reading.

**To Reproduce**
1. Edit the page which wasn't edited by Gutenberg before.
2. Just save it.
3. Special characters will be change to other 

**Expected behavior**
Just transfer the code blocks to "insert code blocks" blocks but not change any words especially some command lines or function words in articles.

**Screenshot**
![bugs_gutenberg](https://user-images.githubusercontent.com/17486472/49623913-8606a700-fa0a-11e8-9a04-424a8ef96e7d.gif)

**Desktop (please complete the following information):**
 - OS : OSX
 - Browser : safari
 - Version : Gutenberg 4.6.1, WordPress 4.9.8

**Comment by starxedsteph** [comment] 2018-12-09 20:40
I tested this but was not able to replicate the issue.

The steps I took were:
1. Created a new post in WP 4.9.8
2. Added the code displayed in the above gif between html `<code>` tags.
3. Activated Gutenberg 4.6.1 plugin
4. Opened the post editor and updated the post.

Sample code:
```echo "net.core.somaxconn= 1024" > /etc/sysctl.conf
echo "vm.overcommit_memory=1" > /etc/sysctl.conf
echo never > /sys/kernel/mm/transparent_hugepage/enabled sysctl -p```

Can you provide some more information so that we can replicate the issue? I'm not sure if it's relevant but it may be helpful to know:

* Do you happen to use a plugin for syntax highlighting that may have a conflict?
* Language setting of your site

Tested in Chrome 70.0.3538.110 macOS Mojave 10.14.1

**Comment by a2d8a4v** [comment] 2018-12-09 22:17
Hello @starxedsteph , thank you for testing the problem for me. Sorry for not prepared more detail about this question.
I am now update my website to 5.0, also syntax highlighting released a update and I tried yesterday.

The steps I just took were like that:
1. Update to WordPress 5.0 or install Gutenberg 4.6.1 in WordPress 4.9.8
2. Open a old post, which has "[code]" tag article.
3. Click "Save" button.

And the sample code in old post was like:
`[code language="bash"]
echo "net.core.somaxconn= 1024" > /etc/sysctl.conf
echo "vm.overcommit_memory=1" > /etc/sysctl.conf
echo never > /sys/kernel/mm/transparent_hugepage/enabled sysctl -p
[/code]`

It tested in Sarafi 12.0.1 macOS Mojave 10.14.1

**Comment by tellthemachines** [comment] 2019-10-17 06:45
Hi there @a2d8a4v,

Thanks for taking the time to update this issue. I cannot reproduce it with a clean install of the latest WP/Gutenberg, so this is likely related to the syntax highlighting plugin you are using. Perhaps you can report it to the plugin developers?
I'm closing this issue for now but feel free to reopen it if you verify the issue is still occurring with no plugins enabled.

**Closed by tellthemachines** 2019-10-17 06:45 UTC
Labels: Needs Testing, [Block] Classic

**Comment by talldan** [comment] 2019-10-18 00:50
Looks like there's a fix here for the syntax highlighter plugin - https://github.com/Automattic/syntaxhighlighter/pull/3

Definitely seems as though this isn't a Gutenberg bug, and more an issue with that plugin, so closing is the right action.
