### ISSUE TITLE
Нет произвольных полей

### ISSUE THREAD

**Issue by ErdTim** [WordPress/gutenberg#9598] opened 2018-09-04 05:28 UTC
**Describe the bug**
Нет произвольных полей в редакторе.

does not show fields.
Advanced Custom Fields 4.4.12

**Comment by Soean** [comment] 2018-09-04 06:07
Gutenberg will be compatible with Advanced Custom Fields 5, see https://www.advancedcustomfields.com/blog/the-state-of-acf-in-a-gutenberg-world/

**Comment by youknowriad** [comment] 2018-09-04 07:48
Duplicate of #8539

**Closed by youknowriad** 2018-09-04 07:48 UTC
Labels: [Type] Plugin / Theme Interoperability
