### ISSUE TITLE
White screen after updating 6.1.0

### ISSUE THREAD

**Issue by quicoto** [WordPress/gutenberg#16515] opened 2019-07-10 16:23 UTC
WordPress: Version 5.2.2
Gutenberg: 6.1.0
URL: /wp-admin/post-new.php?gutenberg-demo
Browser: Firefox 67
OS: MacOS 10.14

Error: White screen on new posts
JS Console: TypeError: n is undefined  wp-content/plugins/gutenberg/build/compose/index.js?ver=1562775422

Screenshot:
![JS Error](https://cldup.com/1lxquss0if.png)

**Comment by aduth** [comment] 2019-07-10 17:33
Closing in favor of #16502 to simplify tracking. Thanks for the report.

**Comment by aduth** [comment] 2019-07-10 17:34
Duplicate of #16502

**Closed by aduth** 2019-07-10 17:34 UTC
