### ISSUE TITLE
[Post Excerpts]: Add support to show font styling used in the post's content

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#43163] opened 2022-08-11 18:29 UTC
## What problem does this address?

At the moment, font styles such as `bold`, `italics`, `strike-through`, `underline`, etc, do not appear when the post's excerpt is displayed on another page. 

If the post's font styles are important for clarity, then there's no option but to display the post's full content in order to see those styles.

**Example**

![Markup on 2022-08-11 at 11:28:52](https://user-images.githubusercontent.com/27249804/184213033-13e57ba7-3d58-45e5-ae67-2a12aad66697.png)

## What is your proposed solution?

Add support for font styles in the display of Post Excerpts in areas like Latest Posts pages, Latest Posts Block, Query Loop block, etc.

**Comment by carolinan** [comment] 2022-10-17 06:53
I believe this is working as intended, that it is the purpose of the excerpt to display (part of) the content without this kind of formatting?

**Comment by annezazu** [comment] 2024-09-05 22:17
I can still replicate this with WP 6.6.1 and GB 19.1 and am left wondering about what @carolinan  shared :D. I pulled up info about the prior excerpt function: https://developer.wordpress.org/reference/functions/the_excerpt/

>An auto-generated excerpt will also have all shortcodes and tags removed. It is trimmed down to a word-boundary and the default length is 55 words. For languages in which words are (or can be) described with single characters (ie. East-Asian languages) the word-boundary is actually the character.

As a result, I do agree this is working as expected and am going to close this out.

**Closed as completed by annezazu** 2024-09-05 22:17 UTC
Labels: [Type] Enhancement, [Block] Post Excerpt
