### ISSUE TITLE
Cover Image with fixed background causes Problems in Chrome

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#9619] opened 2018-09-04 21:30 UTC
**Describe the bug**
When using the cover image with a fixed background the image is not always shown correctly in chrome. Sometimes it is not visible and sometimes only a part is visible.

**To Reproduce**
1. Use Chrome 67, WP 4.9.8 and Gutenberg 3.7.0
2. Add a Cover Image Block to a post
3. Activate "Fixed Background"
4. The Image is not completely visible

This error exists both in the backend and in the frontend

This does not happen with all Images.

**Expected behavior**
The image should be completely visible

**Screenshots**

The image is only partly visible:

<img width="1276" alt="bildschirmfoto 2018-09-04 um 22 58 45" src="https://user-images.githubusercontent.com/6911678/45057961-79835300-b097-11e8-8572-b501c114c799.png">

Here a Video for better understanding:

![ezgif-4-2073639eb6](https://user-images.githubusercontent.com/6911678/45058777-fd3e3f00-b099-11e8-8663-8f9ed4f010f1.gif)

**Desktop :**
 - OS: macOS 10.13.3
 - Browser Chrome
 - Version 67

**Additional context**
 I think this bug has something to do with the bug described here:
https://stackoverflow.com/questions/20268962/fixed-attachment-background-image-flicker-disappear-in-chrome-when-coupled-with

The following CSS Code fixes this bug:
`
 .wp-block-cover-image.has-parallax{
   will-change: top;
 }
`

**Comment by karmatosed** [comment] 2018-10-08 20:12
If we can get the same visual but with a browser fix, then yes let's get this done. Design wise it shouldn't change how looks.

**Comment by jasmussen** [comment] 2019-02-05 07:51
Given we're at Chrome 71 now, and I can't reproduce it, can we close this ticket? 

Very sorry this did not receive a review sooner, it's been pretty hectic these past few months. For context, I recall trying to fix probably the same issue #2872 way back. I also remember this being fixed upstream, see discussion https://github.com/WordPress/gutenberg/pull/2872#issuecomment-367305724.

**Comment by colorful-tones** [comment] 2019-02-08 20:23
I just tested on Chrome 71.0.3578.98 macOS 10.14.3 WP 5.0.3 and I was no longer able to reproduce this.

**Comment by jasmussen** [comment] 2019-02-11 08:31
Cool. Closing this for now, we can reopen if issues arise again.

**Closed by jasmussen** 2019-02-11 08:31 UTC
Labels: Browser Issues, General Interface, Media, [Type] Bug

**Comment by colorful-tones** [comment] 2019-02-11 20:05
Further context... I did some more testing and verified this was not an issue. Please see: https://github.com/WordPress/gutenberg/pull/11608#issuecomment-461956746
