### ISSUE TITLE
Additional Styles not selectable in reusable blocks

### ISSUE THREAD

**Issue by leph83** [WordPress/gutenberg#21473] opened 2020-04-08 07:18 UTC
**Describe the bug**
I've added a style with 
`wp.blocks.registerBlockStyle`
which works totally fine. But when I convert the block to a reusable block, I can't select or change the style. At least not directly, when I edit it, where I've added the reusable block. 

**Expected behavior**
I expected to be able to change the settings of the reusable block wherever I've added it. Since I can already click on edit, I thought I would see all the settings in the sidebar but no, I have to go to "manage reusable blocks" to do that. Which is really hard to find!!!!
I mean, it's not even in the Backend Navigation. At least I couldn't find it there. 

Wordpress 5.4 with I guess the current Gutenberg Version that comes with it.

**Comment by mlbrgl** [comment] 2020-04-10 09:28
I noticed this too after migrating from Wordpress 5.3.2 to 5.4. The settings panel of a block selected within a reusable block is not shown any more:

![image](https://user-images.githubusercontent.com/13406362/78979595-7b878080-7b1c-11ea-96e6-94ed16516dc9.jpg)

Interestingly, clicking an empty area within the reusable block after selecting the paragraph block does show the fully populated panel in 5.4:

![Screenshot 2020-04-10 at 11 19 42](https://user-images.githubusercontent.com/13406362/78980265-d9689800-7b1d-11ea-9eb0-c5698ed65ce5.png)

It works fine as @leph83 mentioned when editing the content of the reusable block directly (accessed through the "Manage reusable blocks" menu item).

**Comment by talldan** [comment] 2020-04-20 03:28
Thanks for reporting this. I can confirm this does seem to be a bug.

Initially I thought this might be a high priority, but there's a workaround at the moment (using the 'Manage reusable blocks' menu and editing the reusable block from there).

**Comment by noisysocks** [comment] 2020-04-21 04:20
Duplicate of https://github.com/WordPress/gutenberg/issues/18560.

**Closed by noisysocks** 2020-04-21 04:20 UTC
Labels: [Feature] Reusable Blocks, [Type] Bug
