### ISSUE TITLE
Pressing enter too quickly can result in paragraphs within paragraphs

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#10272] opened 2018-10-01 12:56 UTC
**Describe the bug**

A paragraph block should never contain a child paragraph.

If you press enter too quickly in succession, you can end up with paragraphs inside paragraphs. These act weirdly with delete and backspace, and cause tests to fail.

This is also the cause of the intermittent test failure in `e2e/specs/splitting-merging.js`

**To Reproduce**

Start a new post.

In the console, enter this code so you can see the internal state of the post:

```
const f = wp.data.select('core/editor');
wp.data.subscribe( () => { console.log( f.getEditedPostContent() ) } );
```

Focus the post and press enter 5 times in quick succession. :hammer: it!

If your system is as slow as mine, you'll see multiple new paragraph blocks, but some of them will not have the `Add text...` placeholder. Those paragraph blocks contain a child paragraph that's empty.

Check the console and you'll see the malformed blocks.

This causes an intermittent test failure in `e2e/specs/splitting-merging.js` sometimes in `should remove at most one paragraph in forward direction` because that test presses enter three time in quick succession.

**Comment by iseulde** [comment] 2018-10-03 02:55
Sounds like a duplicate of #6021.

**Closed** 2018-10-03 02:55 UTC
Labels: Performance, [Component] Rich Text, [Type] Bug
