### ISSUE TITLE
Template change cannot be previewed without saving the page

### ISSUE THREAD

**Issue by oglekler** [WordPress/gutenberg#37894] opened 2022-01-11 19:53 UTC
### Description

Template change cannot be previewed without saving the page.

### Step-by-step reproduction instructions

1. Open a page
2. Check its preview
3. Change template
4. Preview the page - there will be no changeits

### Screenshots, screen recording, code snippet

![template-update](https://user-images.githubusercontent.com/16874687/149011517-978622eb-2d6d-48b8-b43b-498853bad775.gif)

### Environment info

WordPress version: 5.9-RC1-52550
Browser: Google Chrome 96.0.4664.110
OS: Windows 8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-01-11 23:36
This is a duplicate of https://github.com/WordPress/gutenberg/issues/28208 Closing out!

**Closed as completed by annezazu** 2022-01-11 23:36 UTC
Labels: [Status] Duplicate
