### ISSUE TITLE
Shortcode Rendering Issue After WordPress Update with block_template_part()

### ISSUE THREAD

**Issue by IonPulbere** [WordPress/gutenberg#58727] opened 2024-02-06 12:42 UTC
### Description

Hi,

 We recently performed an update on our WordPress website to the latest
 version, 6.4.3. However, we have encountered an issue where the shortcodes
 are not rendering as expected.

 This problem specifically arises when the shortcodes are added in the
 block template and an attempt is made to display them using
 `block_template_part()`. It's worth mentioning that the shortcodes were
 rendering successfully on WordPress version 6.2.

 See images attached:
 1)WP 6.4.3 - ![wp6 4 3](https://github.com/WordPress/gutenberg/assets/21276228/3b96c2dd-dd8a-4920-9d0a-0960e7a5b9c8)
 2)WP 6.2 -![wp 6 2 - ok](https://github.com/WordPress/gutenberg/assets/21276228/8136c28f-8218-4e26-bee9-91169022a5d1)

 Could you please investigate and provide a solution for this issue at your
 earliest convenience? Your prompt attention to this matter would be highly
 appreciated.

 Thank you for your assistance.

 Best regards,
 Ion

### Step-by-step reproduction instructions

1) Create a custom template part, for example, "my-dash.html" on the path (\wp-content\themes\twentytwentyfour\parts\my-dash.html)
2) In the WordPress backend, access /wp-admin/site-editor.php
3) Navigate to "Patterns/Manage all templates part."
4) Select the "My Dash" template part.
5) Add a shortcode element (add any desired shortcode)
6) In the theme files, call the template part from a custom PHP file using block_template_part("my-dash"). For example, I used the following file path: \wp-content\themes\twentytwentyfour\woocommerce\myaccount\dashboard.php.

### Screenshots, screen recording, code snippet

![wp6 4 3](https://github.com/WordPress/gutenberg/assets/21276228/86982888-8937-4e35-b2e6-0b8eb0c6b116)
![wp 6 2 - ok](https://github.com/WordPress/gutenberg/assets/21276228/01d05ed8-8a6d-4dc8-82d3-5302c526f556)

### Environment info

WordPress Version - 6.4.3
Active Theme: Twenty Twenty-Four Version: 1.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2024-02-06 13:23
Thanks for creating the issue, @IonPulbere.

I believe this is a duplicate of https://core.trac.wordpress.org/ticket/56780. Core PR - https://github.com/WordPress/wordpress-develop/pull/3851.

**Closed as not planned** 2024-02-17 16:43 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Template Part

**Comment by srokatonie** [comment] 2024-04-11 11:42
@IonPulbere This is not fixed - can you confirm with the newest Wordpress?

**Comment by srokatonie** [comment] 2024-04-11 11:49
For anyone struggling this may work for you:
``` 
add_filter('render_block_core/shortcode', function(string $block_content): string {
    return do_shortcode($block_content);
}); 
```

**Comment by editandpost** [comment] 2024-05-18 18:55
> add_filter('render_block_core/shortcode', function(string $block_content): string {
>     return do_shortcode($block_content);
> });

Worked for me. THANK YOU!
