### ISSUE TITLE
Cover block DropZone renders when dragging media anywhere on the canvas

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#66764] opened 2024-11-05 16:56 UTC
### Description

The Cover block’s DropZone auto-engages whenever any media is dragged into the editor, regardless of where it’s dragged. The DropZone renders even when media is not being dragged over the Cover block specifically.

### Steps to Reproduce

1. Open the editor and insert a Cover block.
2. Add media to the Cover block, so that it's not in a placeholder state.
3. Drag any media file into the editor, but not directly over the Cover block.
4. Observe that the Cover block’s DropZone renders even though the media is not dragged over it.

### Expected

The DropZone should only render when media is dragged over the Cover block, and not otherwise.

### Actual

The DropZone renders regardless of where media is dragged in the editor.

### Visual 

In the visual below I have two cover blocks. This demonstrates how dragging media over the canvas will engage the Cover block's DropZone, regardless of if you initiate over the cover block first, or not.

https://github.com/user-attachments/assets/1dff1f05-172a-437a-b96a-3e739f8b408b

**Comment by Mamaduka** [comment] 2024-11-05 17:14
This looks duplicate of #66422. Do we need to keep both issues open?

**Comment by richtabor** [comment] 2024-11-05 19:14
> This looks duplicate of https://github.com/WordPress/gutenberg/issues/66422. Do we need to keep both issues open?

These are different. #66422 is the behavior of the drag and drop functionality. This issue is how any cover block's DropZone is rendered when dragging anywhere on the page.

**Closed as completed** 2024-11-12 06:29 UTC
Labels: [Status] In Progress, [Block] Cover
