### ISSUE TITLE
FSE Block Height for SelectControl fills whole View Height

### ISSUE THREAD

**Issue by cmstew** [WordPress/gutenberg#38231] opened 2022-01-26 04:37 UTC
### Description

Something fishy is going on with the Full Site Editor and the HTML Forms Plugin. The block has a normal height in the regular Post Block Editor, but it has a massive height in the Full Site Editor.

It seems to be connected to the Browsers VH. I think it's quite possible that this issue affects other Plugins that use similar blocks.

I've also reported this on the HTML Forms Support forum at https://wordpress.org/support/topic/gutenberg-block-height/

### Step-by-step reproduction instructions

1. Install WP 5.9
2. Install HTML Forms Plugin
3. Create Form (HTML Forms -> Add New)
4. Open FSE
5. Add HTML Forms Block
6. Resize the height of the browser to see that it appears to be connected to the VH
7. Repeat process in regular block editor to see it not stretched

### Screenshots, screen recording, code snippet

<img width="1920" alt="Screen Shot 2022-01-25 at 4 59 31 PM" src="https://user-images.githubusercontent.com/8193597/151104562-e657de74-57ef-49af-8b48-6a0bc8d5ce1f.png">

### Environment info

- Wordpress 5.9
- No Gutenberg Plugin
- Theme: Twenty Twenty Two
- Chrome 97.0.4692.99
- Macbook Pro: Mac OS Monterey

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment] 2022-02-09 07:46
Apologies for the delay here! I wonder if this is related to this issue: https://github.com/WordPress/gutenberg/issues/37573 cc @Mamaduka for some insights here. Noting for now though that, like the forum thread, I can't replicate this and that this is likely something for the plugin author to address. Just want to be sure since similar behavior has popped up elsewhere :)

**Comment by cmstew** [comment] 2022-02-09 22:43
No problem. I'm not even using this in production yet. Just something I came across.

One thing to note is that it's only reproducible in the new Full Site Editing version of Gutenberg. Not the one you'd use in the post editor. I can setup a sample site and give credentials if it helps.

I think there's some fancy new iframe magic happening that may be causing it.

But if you deem it a plugin issue, it seems like the author is also willing to patch it on his end.

**Comment by tellthemachines** [comment] 2023-05-10 03:01
I can no longer reproduce this in the site editor with WP 6.2:

<img width="794" alt="Screenshot 2023-05-10 at 1 00 02 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/84172a38-34de-43c1-95af-58c403f78907">

so I'm going to go ahead and close the issue. Please feel free to reopen if the problem still occurs!

**Closed as completed by tellthemachines** 2023-05-10 03:01 UTC
Labels: [Type] Question
