### ISSUE TITLE
Pasting multiple lines into a list creates a new text block and wipes out undo buffer

### ISSUE THREAD

**Issue by codebykat** [WordPress/gutenberg#10042] opened 2018-09-19 19:27 UTC
**Describe the bug**
Pasting multi-line text into a list block splits the block into two blocks, with a text block in the middle. Worse, it also wipes out the undo buffer -- if you hit cmd+Z after this happens, the entire second part of the list gets deleted.

This is similar to https://github.com/WordPress/gutenberg/issues/9476, but not quite the same issue.

**To Reproduce**
1. Start a new post
2. Create a list with several items
3. Position the cursor at the end of one of the middle items
4. Paste text that includes a line break
5. Note that multiple blocks now exist
6. Use cmd+Z to undo
7. Note that half of your original list has vanished into the ether

**Expected behavior**
1. Pasting multiple lines into a list should create more than one list item. Ideally if it's pasted at the end of an existing list item, the first line of the pasted text should be appended to the existing item, and subsequent lines should become their own list items, within the same block.
2. Undo after a paste should work without losing content.

**Screenshots**
Here's a gif in which I run through the above steps (pasting multi-line text and then hitting undo):
![listpaste](https://user-images.githubusercontent.com/52152/45776005-64193780-bc06-11e8-9ad8-d85a0688430d.gif)

**Desktop (please complete the following information):**
 - OS: OSX High Sierra
 - Browser: Firefox 62
- Gutenberg version: 3.8.0

**Comment by mcsf** [comment] 2018-09-20 11:39
Oof, the content loss concerns me. Thanks for the report, Kat. /cc @iseulde

**Comment by mcsf** [comment] 2018-09-20 12:37
OK, so there isn't real content loss, but rather too many undo levels are added: if you keep pressing Undo, you'll retrace the editor's steps back to before pasting.

**Comment by iseulde** [comment] 2018-11-27 08:50
Duplicate of #8882.

**Closed by iseulde** 2018-11-27 08:50 UTC
Labels: Writing Flow, [Block] List, [Component] Raw Handling, [Type] Bug
