### ISSUE TITLE
Slow/unresponsive as of late

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#7623] opened 2018-06-29 06:10 UTC
**Describe the bug**
Theme 2017, disabled all plugins except Gutenberg. Went to the demo page, selected a paragraph, held down "a" key for like 5 seconds, the whole thing froze for 30 seconds at least. Just typing text is also very unresponsive. Dev tools were not open at that time.

There is a warning in the console:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in Unknown (created by WithSelect(Component))
    in WithSelect(Component)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: t

componentWillUpdate: Please update the following components to use componentDidUpdate instead: t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Don't think it's related though.

In chrome dev tools I went to Performance tab, set it to record, then held down a key in a paragraph block for some seconds. It's telling me `Event (keypress)`, `Event (textInput)` and `Event (input)` handlers took upwards of 500ms. 

Is that related to React strict mode?

**To Reproduce**
1. Type text
2. Is it responsive?

**Comment by aduth** [comment] 2018-06-29 12:00
Performance may suffer some while running in development mode, though certainly not to the extent that you've seen. To consolidate, I'm going to close this as a duplicate of #6466. Let's continue discussion there.

**Closed** 2018-06-29 15:28 UTC
