### ISSUE TITLE
Post Updated message appears while it's still saving, which is confusing

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#5868] opened 2018-03-29 05:12 UTC
## Issue Overview
When you click the _Update_ button to update your Page, it changes to an animated _Updating..._ button and the _Switch to Draft_ button changes to a flashing "saving" message. 

Before these buttons have even finished saving, the green _Post Updated_ bar appears on the screen.

This is confusing. The button is telling me it's still saving but the message is telling me it's saved. Which is it?

![gutenberg-postupdatedmessage](https://user-images.githubusercontent.com/2078245/38070850-c8a35cc4-3369-11e8-829f-a3bae986fc47.gif)

## Steps to Reproduce (for bugs)
1. Open a published Page
2. Make a change and click the Update button
3. View the green message bar appears before it's finished saving

## Expected Behavior
I would expect the green Update message bar to only appear after both the saving/Updating messages on the right hand side of the screen have disappeared.

## Current Behavior
One side of the screen tells me the page is updated. The other side tells me it's still saving. Which one is correct?

## Possible Solution
Only display the Post Updated mesasge once the Update button stops saying _Updating..._ and the "saving" message disappears.

## Related Issues and/or PRs
#3315 - Message still says Post Updated when it's actually a Page

_Gutenberg 2.5.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.4_

**Comment by SuperGeniusZeb** [comment] 2018-05-24 04:48
I think this is a duplicate of #5784.

**Comment by jorgefilipecosta** [comment] 2018-05-24 11:17
Hi @maddisondesigns thank you for creating this issue, it is complex problem related to meta boxes (the message appears after post itself is saved while the button only stops the save state after post + meta boxes are saved).
Given that https://github.com/WordPress/gutenberg/issues/5784 refers to the same problem I will close this issue so we can keep the discussion together. Thank you @SuperGeniusZeb for catching this duplication.

**Closed by jorgefilipecosta** 2018-05-24 11:17 UTC
Labels: [Type] Bug
