### ISSUE TITLE
Difficult to select Page List block in certain circumstances

### ISSUE THREAD

**Issue by naxoc** [WordPress/gutenberg#38305] opened 2022-01-27 22:43 UTC
### Description

When I click any other block in the editor, I get the toolbar as I expect. When I click the Pages list I get a border around the block, but no toolbar. I _can_ trigger the toolbar, but it takes some clicking in and out. 

I can see why the links in the list should be disabled so one does not click away from the editor by accident, but I wonder if that is what is causing the odd behaviour for the block as a whole?

### Step-by-step reproduction instructions

1. Add a couple of paragraphs
2. Add a Page List block
3. Try clicking the Page List block to get the toolbar - it's hard to trigger.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/193283/151455483-885ceac5-9316-4c8a-8242-ed1f5cdf9bd6.mov

### Environment info

Wordpress: 5.9
Gutenberg version: 12.4.1
Theme: Hever (also happens in other themes).
Happens in both Firefox and Chrome on MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-10-21 13:26
I have encountered this problem in the past and was able to reproduce it in WordPress 6.1. However, I can't reproduce it with the latest Gutenberg.
This issue might have been fixed with the Page List Block fix in #45143. Can anyone reproduce this issue with the latest gutenberg?

cc @getdave

**Comment by getdave** [comment] 2022-10-24 08:53
Thank you for reporting this Issue.

It sounds very similar (if not identical) to https://github.com/WordPress/gutenberg/issues/45083 which I recently fixed in https://github.com/WordPress/gutenberg/pull/45143.

https://github.com/WordPress/gutenberg/pull/45143 will be backported to the WP 6.1 release. The easiest way to test for now would be to use the Gutenberg Plugin.

@naxoc Are you able to re-test? 🙏

**Comment by ndiego** [comment] 2022-10-25 14:34
This issue was reviewed in today's Editor Bug Scrub. We tested with Gutenberg trunk and confirmed that this issue is now fixed and will be included with Gutenberg 14.5 and in WordPress 6.1. Therefore I am going to close this issue.

**Closed as completed by ndiego** 2022-10-25 14:34 UTC
Labels: [Type] Bug, Needs Testing, [Status] Duplicate, [Block] Page List

**Comment by getdave** [comment] 2022-10-26 09:43
Thank you for testing and confirming @ndiego. Glad it's working as intended.

> and will be included with Gutenberg 14.5 and in WordPress 6.1.

My understanding is that this will now _not_ be included in WP 6.1. See https://wordpress.slack.com/archives/C02RQBWTW/p1666710735198029.

**Comment by ndiego** [comment] 2022-10-26 11:50
> My understanding is that this will now not be included in WP 6.1. See https://wordpress.slack.com/archives/C02RQBWTW/p1666710735198029.

Ah darn. Yeah looks like it.
