### ISSUE TITLE
Flex Layout: Add "stretch" alignment option

### ISSUE THREAD

**Issue by cbirdsong** [WordPress/gutenberg#46008] opened 2022-11-23 14:57 UTC
## What problem does this address?
For vertical alignment, the row layout defaults to `align-items: center;` and the stack layout defaults to `align-items: flex-start;`, resulting in this layout:

![A set of paragraphs aligned to the left edge of the container when laid out vertically, and aligned to the center of the container when laid out horizontally](https://user-images.githubusercontent.com/1672206/203578038-b07a545d-ae65-4a67-a24f-ba5673f7ddbb.png)

The existing alignment options only allow you to adjust the position of the container's children to top/middle/bottom or left/center/right, but you can't set them to fill the container.

## What is your proposed solution?
Add a "stretch" layout option (`align-items: stretch`) so you can ensure the flex children always fill the container, like this:

![A set of paragraphs that fill the container horizontally when laid out vertically, and fill the container vertically when laid out horizontally](https://user-images.githubusercontent.com/1672206/203578124-be227211-28e7-4bf4-853b-071a80f27eb9.png)

Codepen example: https://codepen.io/cbirdsong/pen/KKeoqOq

**Comment by kathrynwp** [comment] 2022-11-23 17:27
Hey there @cbirdsong I think this may be a duplicate of #41280 so I'm going ahead and closing this, but if I'm mistaken, please let me know and I'll have another look. Thanks!

**Comment by cbirdsong** [comment] 2022-11-23 20:16
Yeah, pretty much, though I was thinking about this more broadly than the row/stack blocks? Ideally this would also apply to buttons and anywhere else that uses flex layout.

Also, should these have the "[Feature] Layout" label? That is where I looked for duplicates before filing this.

**Comment by kathrynwp** [comment] 2022-12-13 15:57
I went ahead and reopened this issue and added the tag you suggested to both this issue and the older one. Thanks a lot, @cbirdsong!

**Comment by phil-sola** [comment] 2023-01-13 10:13
I agree this would be a welcome addition to any flex settings. +1 from me

**Comment by tellthemachines** [comment] 2023-02-07 02:39
Closing as "stretch" has now been added for all flex layouts in #47134 (In horizontal orientation it's in the alignment options, and in vertical in the justification options).

**Closed as completed by tellthemachines** 2023-02-07 02:39 UTC
Labels: [Type] Enhancement, [Block] Group, [Feature] Layout
