### ISSUE TITLE
Allow filtering internationalized strings

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#12516] opened 2018-12-02 11:23 UTC
In WordPress core, every single string that is passed to `__()` & co. can be filtered using the `gettext` filter in `translate()`.

Arguments to that filter are the original text, the translation, and the text domain.

For ultimate flexibility, I suggest adding the same filters to gettext functions in the i18n package.

**Comment by gziolo** [comment] 2019-10-20 02:22
Is it a duplicate of https://github.com/WordPress/gutenberg/pull/12517?

**Comment by leewillis77** [comment] 2020-03-11 11:43
Hi;

I'm jumping into this after reading the linked PR (#12517). I'm the author of the Say What? plugin (https://wordpress.org/plugins/say-what/) which uses the PHP gettext filters extensively to do it's job. Currently there's no way (that I can tell) that it can do the same job on JS strings without that PR (or an alternative) landing. It looks like other plugins have similar issues (https://wordpress.org/support/topic/wp_set_script_translations/)

#12517 was closed but without a clarifying comment about the status so I'm unsure where things lie currently. I don't think the filters have been added. Is there anything I can do to help quantify the need, discuss potential solutions / test?

**Comment by kuuak** [comment] 2020-06-30 15:45
Hello there,

I'm exactly in the same situation as @leewillis77.
I've been looking around for a solution to replace a string in the publish_panel and without a JS filter, like `i18n.gettext` in #12517, there is no way to change the strings.

Is there any indication wether this feature could be set for a next release?

Thanks

**Comment by gziolo** [comment] 2021-01-28 11:45
Resolved with #27966 🎉

**Closed by gziolo** 2021-01-28 11:45 UTC
Labels: Internationalization (i18n), [Package] i18n, [Type] Enhancement
