### ISSUE TITLE
Can't style embedded videos properly due to inline width & height

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8383] opened 2018-08-02 09:56 UTC
**Describe the bug**
There's numerous issues open that discuss the inability to style various blocks so I'm not going to repeat all that again here. The only thing I will say is that we need the ability to specify the content width, and Wide width, at the very minimum.

When you insert a YouTube or Vimeo embed Block, it adds inline width and height to the iframe:

![screenshot_763](https://user-images.githubusercontent.com/2078245/43576887-bf458472-968d-11e8-8dac-11c22c0c4ed8.png)

This causes the content to end up looking something like this (when you have Wide and Full videos):

![gutenberg_videoembeds](https://user-images.githubusercontent.com/2078245/43576585-07b873e6-968d-11e8-898d-223281acfd75.jpg)

Whilst its possible to override the width settings by doing something like `.wp-block-embed.is-type-video iframe {width: 100%;}`, this just makes it look even worse as we can't control the height and the vid just ends up looking squished.

There needs to be a better way to style these video embeds on the front-end.

**To Reproduce**
1. Add YouTube or Vimeo Embed
2. View inline iframe styles on front-end

**Desktop (please complete the following information):**
 - macOS 10.12.6
 - Firefox Quantum 61.0.1 (64-bit)
 - Gutenberg 3.4.0

Some related issues:
#5650
#6131

**Comment by notnownikki** [comment] 2018-08-31 08:33
Thanks, that's filling in bits of the puzzle for me!

> it either (A) needs to let us supply those widths in the same way that we can specify $content_width

I need to look more into the internals of how this works, but I'm pretty sure this is the way we need to go with things, because...

> or (B) It needs to automatically fix these hard-coded widths based on how the vid (or any embed) is getting embeded.

... all the editor does when it saves an embed block is to put the URL on its own line, and oEmbed does the rest when the post is rendered, so by that point, Gutenberg isn't involved.

The bit about **(A)** that seems trickiest to me at the moment is that we wouldn't have a single content width for the post, so the problem becomes how we let oEmbed know that one bit of embedded content is `$content_width`, but another embed is `$wide_width`. I do think that **(A)** seems the way to go, and we should start discussions around this. Perhaps there would a post-oembed filter that fixes the widths...

@karmatosed, @jasmussen might have some input here?

**Comment by jasmussen** [comment] 2018-08-31 08:49
Would it be a solution to provide two configurations for embedded video, perhaps as advanced settings in the sidebar?

- Option 1: Responsive & full-width (default) 
This would be what we have now — the video embed is as wide as the main column, and uses aspect-ratio CSS to make the video responsive.
- Option 2: Full-width
This would basically be the same as what's in the classic editor — the full dimensions are output in the iframe like in the screenshot above, and perhaps we bundle the `max-width` CSS along with it. But it's not responsive beyond that, or it let's the theme itself handle that responsiveness.

**Comment by notnownikki** [comment] 2018-08-31 08:51
@jasmussen 

> Option 1: Responsive & full-width (default)

This would get 100% of my vote! However my CSS-fu hasn't been able to come up with anything that makes the embed 100% width and keeps the aspect ratio. It's not as simple as setting the iframe width to `100%` and height to `auto` is it? I _really_ want to see how this works :)

**Comment by jasmussen** [comment] 2018-08-31 08:54
I could swear we had this working at one time, with CSS in place for it. Perhaps this regressed a bit? I can take a look next week.

The basic idea is that the video is 100% full wide. We then _decide_ an assume an aspect ratio for the video, 16:9, and use that knowledge to use _paddings_ to define the aspect ratio. 

It's all in this pamphlet: http://www.mademyday.de/css-height-equals-width-with-pure-css.html

Sidenote, it would be nice to expand this further so the user can choose the aspect ratio from a sidebar dropdown, like 1:1 (square) 4:3, etc.

I can take a look at this next week if it regressed.

**Comment by notnownikki** [comment] 2018-08-31 08:57
Ah.

We can't assume an aspect ratio of 16:9 for video any more, because YouTube have started putting 4:3 videos in 4:3 aspect ratio. That's why the code in the embed block (which I think has regressed due to some style changes, but fundamentally works) gets the initial height and width and calculates an aspect ratio so that the iframe can resize correctly.

**Comment by jasmussen** [comment] 2018-08-31 08:59
Oh that's interesting. I'll take a look next week and see how we can handle that.

**Comment by notnownikki** [comment] 2018-08-31 09:01
Perhaps the embed block can get the aspect ratio (should be able to access to that information when it renders the preview) and set styles on the block so that the CSS can be told about the aspect ratio?

**Comment by jasmussen** [comment] 2018-08-31 09:08
That would be sort of amazing. We'd have to work out the math to figure out the percentage, though, but that should be simple enough:

- To get a 1:1 aspect ratio, we have a 100% top padding
- To get a 2:1 aspect ratio, we have a 50% top padding
- To get a 1:2 aspect ratio, we have a 200% top padding
- To get a 4:3 aspect ratio, we have a 75% top padding
- To get a 16:9 aspect ratio, we have a 56.25% top padding

**Comment by notnownikki** [comment] 2018-08-31 09:16
Yep, the HTML that would be embedded in the front end is available to the editor, so if we get the `height` and `width` from the iframe in the preview, we can calculate that and set the styles as needed and preserve the aspect ratio on the front end, no matter what the width is.

**Comment by notnownikki** [comment] 2018-08-31 10:26
That's great! I think that having the block apply the correct class for the content's aspect ratio will work nicely then, and we should be able to apply it to any embed that comes in an iframe with fixed height and width.

I'll update here when there's a PR up :smile:

**Comment by notnownikki** [comment] 2018-08-31 13:32
In progress PR at https://github.com/WordPress/gutenberg/pull/9500

That will apply the correct class names, we need to get the CSS written that applies the correct padding etc.

**Comment by notnownikki** [comment] 2018-09-07 14:55
#9500 has been merged, and on embeds that have a fixed size iframe, it sets CSS classes that allow it to resize and keep the correct aspect ratio. You'll see a new wrapper div with classes that look like `wp-has-aspect-ratio wp-embed-aspect-16-9` and the embedded content will automatically be set to 100% width.

**Comment by shaunrfox** [comment] 2018-09-13 01:51
Hi there. I'm working on a custom Wordpress theme and trying to use Gutenberg. The responsive video thing is one of the last things I'm running into. In my googling I found this thread :) Do you know when this will be released? (I just updated to 3.8.0 today and don't see it)

**Comment by jasmussen** [comment] 2018-09-13 09:38
Hi @shaunrfox, the pull request for this feature was merged for the 3.9 milestone. We hope to release 3.9 release candidate today (which you can manually install, follow https://make.wordpress.org/test/ for details), and push 3.9 out hopefully next week.

**Comment by shaunrfox** [comment] 2018-09-14 01:41
Ok, awesome! Thanks for the reply @jasmussen

**Comment by maddisondesigns** [comment] 2018-09-27 01:52
Have just tried v3.9. YouTube vids get the `wp-embed-aspect-` class and now display nicely, which is great, but Vimeo vids still don't get that aspect ratio class and therefore look the same as before.

![screenshot_860](https://user-images.githubusercontent.com/2078245/46118782-9d2b5a80-c24b-11e8-9c56-09dd97909ae3.png)

**Comment by maddisondesigns** [comment] 2018-09-27 08:08
@notnownikki I tried adding your Vimeo vid and it added the aspect ratio classes ok. I also tried adding in the same video in my screenshot above (https://vimeo.com/139290912), again, but it still didn't added the aspect ratio classes.

While your video did get the classes on the front-end, it also caused a number of issues in the editor though.

First up, I embedded the video twice, I wanted to see if it displayed properly in wide/full widths. The second one that I embedded though, displayed at a completely different width than the first embed. In the following pic, neither of those embeds have the wide/full buttons selected. They should appear identical, but they don't.

![screenshot_862](https://user-images.githubusercontent.com/2078245/46131273-966a0b00-c27e-11e8-8a97-692795bf0c3a.png)

Here's a better look at the second embed that I added. You can see a heap of empty space in the embed container.

![screenshot_865](https://user-images.githubusercontent.com/2078245/46131484-15f7da00-c27f-11e8-976c-a8e56c99d850.png)

After embedding multiple vids, the whole editor goes completely weird. When you try to scroll down the page, it jumps back up again. If you do manange to scroll down, and then try to scroll up, you get huge gaps of white space between the blocks. Here's a vid...

https://cl.ly/1c6d5d307b77

This last issue I've raised before but it was marked as low priority, which it obviously shouldn't be because it's still happening  - https://github.com/WordPress/gutenberg/issues/8603

**Comment by notnownikki** [comment] 2018-09-27 13:55
@maddisondesigns the scroll problem seems to be related to drag-n-drop and toolbars, I've pinged @nosolosw who knows more about that.

I'm on the way to a fix for the other issues.

**Comment by nosolosw** [comment] 2018-09-27 15:12
Hi - regarding the scroll. Is https://github.com/WordPress/gutenberg/issues/8603 that we're talking about, right? That has nothing to do with drag-n-drop. As @maddisondesigns [suggested](https://github.com/WordPress/gutenberg/issues/8603#issuecomment-411261585), the problem is reproducible when the embed is selected. My guess would that the code that makes the toolbar pinnable is somewhat related to that?

**Comment by notnownikki** [comment] 2018-09-27 15:14
Yes, #8603. Sorry, I misunderstood, not dnd.

**Comment by jasmussen** [comment] 2018-09-28 08:27
I may have fixed the scrolling issue in https://github.com/WordPress/gutenberg/issues/8603#issuecomment-425362023.

**Closed** 2018-09-29 20:03 UTC
Labels: Blocks, [Type] Enhancement

**Comment by niklasp** [comment] 2018-11-23 16:43
Can you help me getting this work on the front-end? In the backend everything works for me and also in the front end the embeds are getting their respective classes attached like:
```
<figure class="wp-block-embed-youtube alignfull wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio">
  <div class="wp-block-embed__wrapper">
    <iframe width="500" height="281" src="https://www.youtube.com/embed/4iO5INzXLNc?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</figure>
```
But where can I get the responsive styling of these classes from in my frontend?

**Comment by GlennMartin1** [comment] 2018-11-23 16:55
If I understand properly, the reason it doesn't work in the front-end is because of themes that have not yet adapted.

The theme needs to opt into Gutenberg styles, and when they do, it will work correctly on the front-end.

**Comment by jasomdotnet** [comment] 2019-09-15 11:51
> The theme needs to opt into Gutenberg styles
Too much additional code. Somebody could just share the embed part (proper height in css).

**Comment by lbrand309** [comment] 2019-09-25 23:08
Thank you so much for posting the CSS - fixed my issue marvelously!!

**Comment by khoug** [comment] 2020-01-14 01:18
> Here's basic front-end css:
> 
> ```
> figure.wp-block-embed.is-type-video {
>     position: relative;
>     width: 100%;
>     height: 0;
>     padding-bottom: 56.25%; /*16:9*/
> }
> figure.wp-block-embed.is-type-video iframe {
>     position: absolute;
>     top: 0;
>     left: 0;
>     width: 100%;
>     height: 100%;
> }
> ```
> 
> You are welcome.

This was definitely my solution, **thank you very much boss**!

**Comment by Mishkamshka** [comment] 2021-05-01 15:41
Hey, I've just started using Gutenberg so I'm not sure if the code has changed. But when I was putting in @jasomdotnet code it showing up blank. But this works for me! 

figure.wp-block-embed.is-type-video, .wp-block-embed__wrapper {
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 56.25%; /*16:9*/
}
figure.wp-block-embed.is-type-video iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

Thanks for this!

**Comment by anyway** [comment] 2021-06-24 13:37
> figure.wp-block-embed.is-type-video, .wp-block-embed__wrapper {
> position: relative;
> width: 100%;
> height: 0;
> padding-bottom: 56.25%; /_16:9_/
> }
> figure.wp-block-embed.is-type-video iframe {
> position: absolute;
> top: 0;
> left: 0;
> width: 100%;
> height: 100%;
> }

@Mishkamshka thank you so much... this saved me my afernoon!
