### ISSUE TITLE
Preview don't work

### ISSUE THREAD

**Issue by skiokko** [WordPress/gutenberg#12717] opened 2018-12-09 13:24 UTC
**Describe the bug**
The preview of posts and pages don't work, it show only the saved content not the preview one. The preview work only if I reload the preview page after 3-6 seconds. 
Details here: https://youtu.be/FhCssW8JpEc

**To Reproduce**
1. Go to Pages
2. Edit or create a new page
3. Preview it

 - Device: desktop
 - OS: W10 with XAMP PHP 5.6
 - Browser Chrome
 - Version latest

**Additional context**
- This issue happen sometime also with the original WP Themes like Tweenty Fifteen and without any external plugin.
- This issue don't happen with the latest WP Theme Tweenty nineteen.

**Comment by soup-bowl** [comment] 2018-12-10 20:37
Reproducing this on the edition of Gutenberg built into WordPress **5.0.**
Device: Laptop.
OS: macOS Mojave
Browser: Chrome
Site Host: Ubuntu 16.04
Site Server: Apache
Site Theme: Custom fork of Sparkling ([here](https://github.com/ReviveToday/Sparkling)).

**Comment by designsimply** [comment] 2018-12-12 00:17
Thank you for the video! I am closing this one as a duplicate of #12617 and would like to continue the conversation there.

**Comment by designsimply** [comment] 2018-12-12 00:20
@skiokko would it be possible to get a list of your active plugins here on this issue even though it's closed? When we come back around to testing #12617 it would be cool to have that documented if possible.

**Comment by skiokko** [comment] 2018-12-12 09:46
Hi,

I tested the issue also with no plugins activated and with the WP Theme Twenty Seventeen and I got the same issue. But this issue not happen always. It's really strange.

**Comment by designsimply** [comment] 2018-12-18 01:49
It *is* strange! I can see that a few others have reported it, but I'm still having trouble figuring out steps to replicate the problem in testing.

**Closed by designsimply** 2018-12-18 01:49 UTC
Labels: [Status] Duplicate
