### ISSUE TITLE
The sidebar should "remember" which panel is open

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2194] opened 2017-08-03 15:31 UTC
When working on the sidebar and switching from the Document inspector to the Block inspector, the expanded/collapsed state of the sidebar panels is not stored and always gets reset to its initial state.

This is particularly annoying when intensively working on the sidebar. Just a quick example, see the screenshot below:
- I've closed the "Status & Visibility" panel because I want to comfortably work inspecting the Table of Contents (screenshot left)
- I want to change a header in h5 or h6 and to do so I have to switch to the Block inspector (screenshot center)
- I do my edit
- when I switch back to the Document inspector, the Table of Content panel is now closed and it's back to its initial state, with "Status & Visibility" open (screenshot right)

![screen shot 2017-08-03 at 14 30 26](https://user-images.githubusercontent.com/1682452/28929818-483b0f90-7871-11e7-8af5-1d15141353da.jpg)

**Comment by youknowriad** [comment] 2017-08-03 15:34
duplicate of #450 ?

**Comment by afercia** [comment] 2017-08-03 17:04
More or less... will close and add a comment on #450

**Comment by afercia** [comment] 2017-08-03 17:06
Hm no sorry, #450 is about persistence across _page reloads_. This is a different issue: persistence across re-renderings.

**Comment by youknowriad** [comment] 2017-08-28 10:55
fixed by #2533

**Closed by youknowriad** 2017-08-28 10:55 UTC
