### ISSUE TITLE
Automatically added <br> and <p> tags in HTML blocks of sidebar widgets

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#33936] opened 2021-08-06 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

After 5.8 update I always get automatically added `<br>` and `<p>` tags in my HTML blocks in widgets. It breaks my advertisements' code and it's bad.

### Step-by-step reproduction instructions

1. Open sidebar (widget) editor (appearance>widgets) and paste this code in any widget using HTML block.
```
<!-- Yandex.RTB R-A-460934-22 -->
<div id="yandex_rtb_R-A-460934-22"></div>
<script>window.yaContextCb.push(()=>{
  Ya.Context.AdvManager.render({
    renderTo: 'yandex_rtb_R-A-460934-22',
    blockId: 'R-A-460934-22'
  })
})</script>
```
2. Save widget, close editor, and go to the main page or somewhere else.
3. Again open widget editor, you will see something like this
```
<p><!-- Yandex.RTB R-A-460934-22 --></p>
<div id="yandex_rtb_R-A-460934-22"></div>
<p><script>window.yaContextCb.push(()=>{<br />
  Ya.Context.AdvManager.render({<br />
    renderTo: 'yandex_rtb_R-A-460934-22',<br />
    blockId: 'R-A-460934-22'<br />
  })<br />
})</script></p>
```

### Expected Behavior

HTML doesn't change.

### Current Behavior

HTML gets extra tags

### WordPress Information

5.8

**Comment by sparklingrobots** [comment] 2021-08-10 21:29
I tested & can confirm this behavior. 

Possible workaround for @Arskrigitsioniets, though: Have you tried making everything in the script into a single line, e.g.: 
`<script>window.yaContextCb.push(()=>{Ya.Context.AdvManager.render({renderTo: 'yandex_rtb_R-A-460934-22',blockId: 'R-A-460934-22'})})</script>`

Let us know if that works for you.

**Comment by Arskrigitsioniets** [comment] 2021-08-10 22:34
> I tested & can confirm this behavior.
> 
> Possible workaround for @Arskrigitsioniets, though: Have you tried making everything in the script into a single line, e.g.:
> `<script>window.yaContextCb.push(()=>{Ya.Context.AdvManager.render({renderTo: 'yandex_rtb_R-A-460934-22',blockId: 'R-A-460934-22'})})</script>`
> 
> Let us know if that works for you.

It doesn't help because Gutenberg forces the HTML to go to the next line when the current becomes too long, so I eventually get the same just with fewer lines.

**Comment by n3wjack** [comment] 2022-01-16 11:22
Just confirming I'm also having this issue.
Legacy HTML blocks don't seem to be affected.

**Comment by noisysocks** [comment] 2022-02-15 05:42
Hi @Arskrigitsioniets, thanks for reporting this. It's the same root cause as https://github.com/WordPress/gutenberg/issues/33832, so closing this in favour of that issue.

**Closed as completed by noisysocks** 2022-02-15 05:42 UTC
Labels: [Type] Bug, [Feature] Widgets Screen
