### ISSUE TITLE
Site Logo on Twenty Twenty Two Theme Not Working

### ISSUE THREAD

**Issue by maxwellhankner** [WordPress/gutenberg#45132] opened 2022-10-19 23:17 UTC
I deleted the site logo when I first started with this theme. Now, when I try to create a new site logo, it's not working as expected. It just displays a "0" in a box and doesn't let me replace it or do anything.

![Screen Shot 2022-10-19 at 6 15 45 PM](https://user-images.githubusercontent.com/25621984/196821953-7c13bd68-a422-4e5a-a3c7-101db7976d4b.png)
![Screen Shot 2022-10-19 at 6 15 58 PM](https://user-images.githubusercontent.com/25621984/196821961-9239ec91-ceea-4d27-95a0-a94996ddce86.png)

**Comment by ramonjd** [comment] 2022-10-20 01:20
Did you delete the Site logo block or the image itself?

I just tried both on Twenty Twenty Two and could replace it.

<img width="1001" alt="Screen Shot 2022-10-20 at 12 19 37 pm" src="https://user-images.githubusercontent.com/6458278/196833780-d9278cbc-0824-437e-9b80-0163da6a4467.png">


Which version of Gutenberg and WordPress are you using?

**Comment by maxwellhankner** [comment] 2022-10-20 01:34
@ramonjd Thanks for the response! I am using wp version 6.0.3 Not sure how to check Gutenberg version. I deleted the site logo and the image out of media I believe. This exact thing has happened to me on two sites now.

**Comment by ramonjd** [comment] 2022-10-20 02:00
> Not sure how to check Gutenberg version.

If you're not running any plugins, then Gutenberg is probably not activated. The reason I asked is because if it's a Gutenberg bug, then this issue is in the right place 😄 

But I can't reproduce 🤔 So maybe if it was broken, it's been fixed in the meantime?

You might be able to confirm this by installing/activating the Gutenberg plugin on your WordPress 6.0 site.

**Comment by maxwellhankner** [comment] 2022-10-20 02:03
@ramonjd Wow, that did it. I thought Gutenberg came with wordpress by default. Now that I have installed it everything works as expected.. thank you

**Closed as completed** 2022-10-20 03:35 UTC
Labels: [Type] Bug, [Status] Needs More Info, [Block] Site Logo
