### ISSUE TITLE
Linking to an existing post triggers a pingback

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3625] opened 2017-11-23 11:11 UTC
To reproduce:

- make sure in Settings > Discussion (`options-discussion.php`) the checkbox "Attempt to notify any blogs linked to from the article" is checked 
- create a new post in Gutenberg
- add a paragraph and link to an existing post: the existing post must have the setting "Allow trackbacks and pingbacks on this page" enabled
- publish the post
- wait a few seconds
- go in the Comments screen (`edit-comments.php`)
- there's now a new pingback

**Comment by jeffpaul** [comment] 2018-03-22 19:47
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521734480000020)._

**Comment by jorgefilipecosta** [comment] 2018-04-19 18:17
Hi @afercia, thank you for reporting this issue. I did some tests and tried to replicate this behavior but I was not able to get the pingback. Could you confirm if the problem is still happening?

**Comment by afercia** [comment] 2018-04-20 07:27
Hi @jorgefilipecosta just reproduced following the steps above and got a new pingback. Standard VVV environment here.

<img width="1279" alt="screen shot 2018-04-20 at 09 25 15" src="https://user-images.githubusercontent.com/1682452/39036128-e6658948-447c-11e8-9797-a73348b8e620.png">

**Comment by jorgefilipecosta** [comment] 2018-05-24 10:38
Thank you for your tests @afercia, I had troubles initially reproducing the problem not sure why, but I "refreshed" my dev environment and I manage to reproduce the described behavior.
When testing creating both the "post receiving link" and the "linking post" in the classic editor I get the same pingback, this happens even in new test sites and even if Gutenberg is not installed.
@afercia in your setup are you able to reproduce this in the classic editor?

**Comment by afercia** [comment] 2018-05-24 13:37
@jorgefilipecosta seems you're right, happens also with G. disabled and linking to a post in the classic editor. Weird I didn't know WordPress allows for auto-pings...

**Comment by jorgefilipecosta** [comment] 2018-05-24 13:50
Thank you for confirming @afercia my tests, given that it is an existing behavior in Core/classic editor I will close the issue for now.
Thank you for reporting this issue and your testing/debugging efforts.

**Closed by jorgefilipecosta** 2018-05-24 13:50 UTC
Labels: [Type] Bug
