### ISSUE TITLE
Theme.json configurations with styles not expressed in a block's block.json breaks FSE

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#31560] opened 2021-05-06 18:15 UTC
## Description
Not sure exactly the scenario but it can be observed in [this experiment](https://github.com/WordPress/theme-experiments/pull/256).

It appears that when a theme.json contains block styles not officially supported by a block the FSE stops working with the following errors:
```
Uncaught TypeError: Cannot read property 'selector' of undefined
    at index.js:20
    at lodash.js:4925
    at baseForOwn (lodash.js:2990)
    at lodash.js:4894
    at forEach (lodash.js:9368)
    at index.js:20
    at index.js:20
    at index.js:20
    at commitHookEffectListMount (react-dom.development.js:19866)
    at commitPassiveHookEffects (react-dom.development.js:19904)
react-dom.development.js:19662 The above error occurred in the <ut> component:
    in ut (created by Mn)
    in $l (created by Mn)
    in jt (created by Mn)
    in jt (created by Mn)
    in jt (created by Mn)
    in v (created by w)
    in y (created by w)
    in w (created by Mn)
    in Mn

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:19662
react.development.js:2210 Uncaught TypeError: Cannot read property 'selector' of undefined
    at index.js:20
    at lodash.js:4925
    at baseForOwn (lodash.js:2990)
    at lodash.js:4894
    at forEach (lodash.js:9368)
    at index.js:20
    at index.js:20
    at index.js:20
    at commitHookEffectListMount (react-dom.development.js:19866)
    at commitPassiveHookEffects (react-dom.development.js:19904)
```

NOTE: The VIEW renders just fine with these values in place.  It's just the FSE that blows up.

For example the quote block doesn't express support for padding in its block.json file, however prior to 10.6.0 we were able to express padding styles via theme.json configuration anyway.

```
...  (version 0 configuration)
	"styles": {
		"core/quote": {
			"spacing": {
				"padding": {
					"left": "50px",
					"right": "50px"
				}
			}
		}
	}
```

However in 10.6.0 (and up) this support seems to break the loading of the FSE.

It appears that using either version 0 OR version 1 of the theme.json configuration causes this error.

Adding support of padding to the quote block.json file makes things work again.

## Step-by-step reproduction instructions
* Install the [demonstration theme](https://github.com/WordPress/theme-experiments/pull/256).
* Note that it's broken.

## Expected behaviour
The demonstration theme would be loaded fine in the FSE.

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: /trunk, 10.6.0, 10.6.0-rc.1
- Are all plugins except Gutenberg deactivated? YES
- Are you using a default theme (e.g. Twenty Twenty-One)? -ish

**Comment by youknowriad** [comment] 2021-05-06 18:49
cc @nosolosw @jorgefilipecosta

**Comment by oandregal** [comment] 2021-05-07 08:11
Jason, thanks for the report and, especially, for preparing a reproducible setup. I'm looking into this.

**Comment by oandregal** [comment] 2021-05-07 09:03
There's a fix for this at https://github.com/WordPress/gutenberg/pull/31588 Probably this should be backported to 10.6 RC.

I'm looking deeper into this because the root cause seems to be that some blocks appear as unregister (the quote), or perhaps they're registered at a later point. Not sure something changed in that area. Anyway, the fix is proper because we need to be cautious. It only affects the site editor because the server already has these guards.

**Comment by oandregal** [comment] 2021-05-07 09:08
Also found a smaller testcase. Add styles for the quote block to you theme.json:

```json
"styles": {
    "blocks": {
        "core/quote": {
            "spacing": {
                "padding": {
                    "top": 12,
                    "bottom": 12
                }
            }
        }
    }
}
```

**Comment by oandregal** [comment] 2021-05-07 09:22
Got https://github.com/WordPress/gutenberg/pull/31590 ready to fix the root cause. We need to merge both fixes.

**Closed as completed** 2021-05-07 13:05 UTC
Labels: [Type] Bug, [Status] In Progress, Global Styles

**Comment by oandregal** [comment] 2021-05-07 17:19
Both fixes are merged in `trunk`
