### ISSUE TITLE
InnerBlocks / Inserter: Auto-Add new block on click when allowedBlocks only contains 1 block

### ISSUE THREAD

**Issue by rhurling** [WordPress/gutenberg#18017] opened 2019-10-18 07:27 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to build multiple blocks where there is only 1 specific block allowed in the InnerBlocks component, which is the specific sub-block i build for the main block (Slider -> Slider Item; Accordion -> Accordion Item, ...). The frustrating thing is that I can't find a way to make the Inserter autoselect the only block available.

**Describe the solution you'd like**
I'd like the `InnerBlocks.ButtonBlockAppender` to automatically add the block if only 1 is available.

**Describe alternatives you've considered**
Otherwise some form of documentation for an example `renderAppender` function that actually adds a block. I've been trying to look through the `InnerBlocks.ButtonBlockAppender` but I can't seem to find where the actual adding of the block is handled.

**Comment by swissspidy** [comment] 2019-10-18 08:32
This seems like a duplicate of #16659 which has a PR at #16708. Can you confirm that?

**Closed** 2019-10-18 08:54 UTC
Labels: [Feature] Inserter, [Feature] Nested / Inner Blocks, [Status] Duplicate
