### ISSUE TITLE
Multi-select: backspace or delete, should delete selection

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#2101] opened 2017-07-31 09:22 UTC
Use case: you create 10 paragraphs. You are fed up, and want it gone. You hit ⌘ A to select them all, and press backspace. 

Current behavior: only the last block selected gets deleted. Desired behavior: all selected blocks get deleted.

**Comment by iseulde** [comment] 2017-08-01 17:26
Duplicate of #1058.

**Closed by iseulde** 2017-08-01 17:26 UTC
Labels: Blocks
