### ISSUE TITLE
Image and Paragraph Block: alignment 

### ISSUE THREAD

**Issue by catkiinson** [WordPress/gutenberg#14782] opened 2019-04-03 00:01 UTC
#### Steps to reproduce
1. Create a new page, add an image block and insert image. 
2. Add a paragraph block below with text. 
3. Resize image and change to left alignment. Text wraps around image. 
4. Preview/publish 

#### What I expected

- Expected the image and text to be almost exactly aligned, as it appears in the editor. 

#### What happened instead

- When previewed/published, the first line of text has a gap above it. 

- Workaround: Adding an empty paragraph block above the image block removes the gap. 

#### Browser / OS version
Chrome Version 73.0.3683.86
macOS Mojave 10.14.3

#### Screenshot / Video
Page creation: 
![Screen Recording 2019-04-01 at 05 29 PM](https://user-images.githubusercontent.com/43645273/55367858-f6e33a80-54a3-11e9-97fe-437cd8595eab.gif)

Before adding empty paragraph block: 
![b33468de4d58b6b4cc095fed8224d5f2 _Image 2019-04-01 at 5 12 00 PM](https://user-images.githubusercontent.com/43645273/55367906-30b44100-54a4-11e9-8097-a33786806203.png)

Empty paragraph block applied in editor: 
![Screen Shot 2019-04-01 at 5 38 49 PM](https://user-images.githubusercontent.com/43645273/55368124-175fc480-54a5-11e9-81c1-f4adcdbbd0b1.png)

After adding empty paragraph block: 
![Screen Shot 2019-04-01 at 5 13 59 PM](https://user-images.githubusercontent.com/43645273/55367914-39a51280-54a4-11e9-8667-330aa452a740.png)

https://github.com/Automattic/wp-calypso/issues/31943#issuecomment-478937658

**Comment by youknowriad** [comment] 2019-04-03 09:15
I can't reproduce this. I guess it's probably fixed in the last Gutenberg versions.

@kjellr anything that you think is related.

**Comment by arunsathiya** [comment] 2019-04-03 09:35
If it helps, I am not able to reproduce this either. It appears to be fine with no indication of extra space above the paragraph block. Tested on a WordPress.org site with Gutenberg on wp-admin. 

<img width="899" alt="Screenshot 2019-04-03 at 15 01 45" src="https://user-images.githubusercontent.com/18581859/55468881-f375bd80-5621-11e9-921f-6a3e58a8f9be.png">
<img width="818" alt="Screenshot 2019-04-03 at 15 01 53" src="https://user-images.githubusercontent.com/18581859/55468884-f4a6ea80-5621-11e9-8868-6f5aa6045fdb.png">

**Comment by kjellr** [comment] 2019-04-03 13:23
Thanks for the ping. This is almost certainly a Twenty Seventeen bug. I'm able to reproduce there: 

<img width="587" alt="Screen Shot 2019-04-03 at 9 11 33 AM" src="https://user-images.githubusercontent.com/1202812/55481699-f310fe80-55f0-11e9-9838-cc71491e65a7.png">

@catkiinson, I see you've already ported this over from one repo to another, so I've gone ahead and migrated it over to the right place for Twenty Seventeen issues for you: 

https://core.trac.wordpress.org/ticket/46785

Sorry for the back and forth — please follow along there for a fix. I'll close this issue in the meantime. Thanks for the report!

**Closed by kjellr** 2019-04-03 13:23 UTC
