### ISSUE TITLE
Link on text block not working properly.

### ISSUE THREAD

**Issue by parmarhardip** [WordPress/gutenberg#1834] opened 2017-07-10 12:40 UTC
Hello All,

Today, I have updated the new version of the plugin to the Version 0.4.0.

I have tried to give a link in text block but it allowed me to give a blank link on the text. I think that was something weird.

For more information, I have attached a GIF file.

Thanks,

![textblock-link-issue](https://user-images.githubusercontent.com/23077242/28018413-dfc9442e-659a-11e7-8080-6e1356332902.gif)

**Comment by karmatosed** [comment] 2017-07-10 15:34
@parmarhardip hi there, unfortunately I can't recreate your issue. One thing that got me thinking was maybe it's the theme you are using - it may not be. Can you give maybe some more details such as:

- Exact steps to do this, I tried to follow from video.
- What theme you are using.
- What browser you are using to view on.

**Comment by westonruter** [comment] 2017-07-10 22:00
@parmarhardip So your suggestion is that the URL should be required? I think this is a duplicate of #1838.

**Comment by karmatosed** [comment] 2017-09-24 12:31
I think as I can't recreate and this could be a duplicate, closing for now. We can always open again.

**Closed by karmatosed** 2017-09-24 12:31 UTC
Labels: [Status] Needs More Info
