### ISSUE TITLE
[WP 6.1] Block-specific global styles don't seem to save

### ISSUE THREAD

**Issue by RahiDroid** [WordPress/gutenberg#44434] opened 2022-09-24 14:59 UTC
### Description

- Original trac ticket: https://core.trac.wordpress.org/ticket/56644 by @jorgefilipecosta 
- Moving here along with some added visuals to help out better understand the issue.
- I could reproduce it with multiple blocks like `paragraph`, `heading`, `button`, `site title`, etc. It doesn't seem to be happening with all of the blocks, though. 
- The issue isn't specific to only colors. It's happening with other properties of a block too. 
- Block-specific global styles don't seem to save. Changing the global styles not under the `Blocks` section still works. 
- Was able to reproduce with both TT2 and TT3 themes. 

### Step-by-step reproduction instructions

Copy pasting from the trac ticket,
1. Go to the site editor.
1. Open the global styles sidebar.
1. Open the blocks section.
1. Navigate to the paragraph block (or button, heading, etc, I think most static blocks).
1. Apply a background color.
1. Save the global styles.
1. The background color is wholly discarded on save.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/59014930/192104832-a8b0f526-0baf-41b9-8c7a-f1e57099fa58.mov

### Environment info

- WP(6.1-beta1-54298)
- TT2 or TT3 theme
- PHP 7.4
- **Gutenberg plugin deactivated**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-09-26 13:56
I can confirm this issue. It's a pretty major one 😬
![global-style-no-saving](https://user-images.githubusercontent.com/4832319/192294999-a8c3be98-a3d8-4f54-b774-9341bb43af4f.gif)

**Comment by glendaviesnz** [comment] 2022-09-27 00:35
Looks like the values are being saved to the styles custom post type, but are not being retrieved for some reason, will see if I can work out why that is.

**Comment by glendaviesnz** [comment] 2022-09-27 03:23
It looks like in wordpress-develop [this call](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-theme-json-resolver.php#L438) is not returning the custom global styles data. The correct data is there in the [preceding config var](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-theme-json-resolver.php#L433), ran out of time to try and work out why it is working in GB trunk and not 6.1 beta.

@oandregal may have some thoughts  - [this PR](https://github.com/WordPress/gutenberg/pull/44015) touched on some of these areas, but it all seems to have been ported to 6.1

**Comment by andrewserong** [comment] 2022-09-27 06:14
Interestingly, in wordpress-develop I can save styles for server rendered blocks in global styles (e.g. site title), but not static blocks (like Group). Just in case that points in any particular direction for this one or the linked [trac issue](https://core.trac.wordpress.org/ticket/56644).

**Comment by andrewserong** [comment] 2022-09-27 06:48
I _think_ this one will likely need to be fixed from the core side, but I noticed (and commented [here on the trac issue](https://core.trac.wordpress.org/ticket/56644#comment:2)) that if we update the priority of the `register_core_block_types_from_metadata` callback on the `init` action to have a priority of `1`, that appears to resolve the issue ([this line](https://github.com/WordPress/wordpress-develop/blob/537e5239f94853049ce84e815ddf15f8ecf7d259/src/wp-includes/blocks/index.php#L29)). So it sounds like it's likely related to a caching issue / order of calls with `get_blocks_metadata` being called too early, like @jorgefilipecosta described? (While updating the priority worked in my local environment, I imagine that won't work as a proper fix, as it possibly obfuscates the real bug 🤔)

**Comment by ndiego** [comment] 2022-09-27 18:10
I can confirm that this issue does not occur with Gutenberg active. Only in 6.1 Beta. So it seemly like something might not have been ported over properly? 🤔

**Comment by oandregal** [comment] 2022-09-27 20:37
I've done some testing: go to the global styles sidebar and set the global background color and the background color of the heading block. This is how I'm tracing this data usage:

- the database has the actual user data

```json
{
  "styles": {
    "color": { "background": "var:preset|color|vivid-red" },
    "blocks": {
      "core/heading": {
        "color": { "background": "var:preset|color|luminous-vivid-amber" }
      }
    }
  },
  "isGlobalStylesUserThemeJSON": true,
  "version": 2
}
```

- the result of [calling](https://github.com/oandregal/wordpress-develop/blob/bb7ddf5b569de07448b130d0ef374e8dffe93cea/src/wp-includes/class-wp-theme-json-resolver.php#L482) `WP_Theme_JSON_Resolver::get_user_data()` is this (notice how the block data is missing):

```php
(
    [theme_json:protected] => Array
        (
            [styles] => Array
                (
                    [color] => Array
                        (
                            [background] => var:preset|color|vivid-red
                        )

                )

            [version] => 2
        )

)
```

So the data is properly saved but is discarded when rendering.

**Comment by oandregal** [comment] 2022-09-27 21:33
What happens is that, at some point, the theme.json class receives the data saved in the database. It wants to [sanitize](https://github.com/oandregal/wordpress-develop/blame/bb7ddf5b569de07448b130d0ef374e8dffe93cea/src/wp-includes/class-wp-theme-json.php#L516) it. One of the things it does is removing data for blocks that are not registered. And, apparently, the `core/heading` is not, hence its data is removed and the styles are generated without it. These are the "valid blocks" at the point the user data is first calculated:

```php
(
    [0] => core/legacy-widget
    [1] => core/widget-group
    [2] => core/archives
    [3] => core/avatar
    [4] => core/block
    [5] => core/calendar
    [6] => core/categories
    [7] => core/comment-author-name
    [8] => core/comment-content
    [9] => core/comment-date
    [10] => core/comment-edit-link
    [11] => core/comment-reply-link
    [12] => core/comment-template
    [13] => core/comments
    [14] => core/comments-pagination
    [15] => core/comments-pagination-next
    [16] => core/comments-pagination-numbers
    [17] => core/comments-pagination-previous
    [18] => core/comments-title
    [19] => core/cover
    [20] => core/file
    [21] => core/gallery
    [22] => core/home-link
    [23] => core/image
    [24] => core/latest-comments
    [25] => core/latest-posts
    [26] => core/loginout
    [27] => core/navigation
    [28] => core/navigation-link
    [29] => core/navigation-submenu
    [30] => core/page-list
    [31] => core/pattern
    [32] => core/post-author
    [33] => core/post-author-biography
    [34] => core/post-comments-form
    [35] => core/post-content
    [36] => core/post-date
    [37] => core/post-excerpt
    [38] => core/post-featured-image
    [39] => core/post-navigation-link
    [40] => core/post-template
    [41] => core/post-terms
    [42] => core/post-title
    [43] => core/query
    [44] => core/query-no-results
    [45] => core/query-pagination
    [46] => core/query-pagination-next
    [47] => core/query-pagination-numbers
    [48] => core/query-pagination-previous
    [49] => core/query-title
    [50] => core/read-more
    [51] => core/rss
    [52] => core/search
    [53] => core/shortcode
    [54] => core/site-logo
    [55] => core/site-tagline
    [56] => core/site-title
    [57] => core/social-link
    [58] => core/tag-cloud
)
```

**Comment by oandregal** [comment] 2022-09-27 22:06
I've quickly looked at the places where we require global styles data. Inspected the usage of the `wp_get_global_stylesheet` (and similar functions) as well as the classes (`WP_Theme_JSON` and `WP_Theme_JSON_Resolver`). I wanted to learn if we had changed the places where we use this code (`script-loader.php`, etc.) and made it so it runs earlier than block registration. I haven't found anything meaningful.

The other reason some blocks may not be registered at that point is that block registration had changed, as Jorge suggested in the trac ticket. A bit out of my expertise at the moment, and given some time-constraints I have this week I'm not sure if I'm going to be able to help investigate much further this path.

**Comment by andrewserong** [comment] 2022-09-28 01:19
Thanks for writing all that up @oandregal — I think I've found where the caching issue is occuring:

After a git-bisect on wordpress-develop that pointed to [this backport commit](https://github.com/WordPress/wordpress-develop/commit/3b63a75108b7f6d5e9112c556285ab1bc80ddbcf#diff-19f8095f13b47e6d366be46c37c142fb971a4ce9c514607a86e1e1a2382b6235), I tried looking through the backported server-rendered blocks, and I think I've found the area that's causing the issue in the Template Part block's `build_template_part_block_instance_variations` function. This function is called when the block is registered, rather than when it's rendered, and uses the get_block_templates function [on this line](https://github.com/WordPress/wordpress-develop/blob/3b63a75108b7f6d5e9112c556285ab1bc80ddbcf/src/wp-includes/blocks/template-part.php#L193), which appears to eventually further down the line call `get_theme_data` [here](https://github.com/WordPress/wordpress-develop/blob/f9769f5eaea747a2183d912d649046a5dbb0d291/src/wp-includes/block-template-utils.php#L354), causing the list of registered blocks to be cached.

If I update the following line in `register_block_core_template_part` to set variations to `null`, then global styles appears to be working correctly again: https://github.com/WordPress/wordpress-develop/blob/3b63a75108b7f6d5e9112c556285ab1bc80ddbcf/src/wp-includes/blocks/template-part.php#L248

So, the problem appears to be calling a getter function like this at registration time prior to all blocks being registered.

For a bit more background, this caused a few issues in the Gutenberg plugin earlier on. The solution at the time was to adjust the caching in Gutenberg, but it looks like this didn't get to the root of the problem for when the block was backported. Here are some earlier links:

* https://github.com/WordPress/gutenberg/pull/42454 (the PR that introduced block variations for template parts)
* https://github.com/WordPress/gutenberg/pull/42748 (one of the potential fixes in Gutenberg, where @scruffian flagged the issue)
* https://github.com/WordPress/gutenberg/pull/42756 (the update to the cache check that we merged at the time to fix the issue in Gutenberg)

The question now, then, is what's the right fix for this problem? @ramonjd mentioned the idea of potentially calling or adding an action to call `clean_cached_data` again, similar to the switch theme action: `add_action( 'switch_theme', array( 'WP_Theme_JSON_Resolver', 'clean_cached_data' ) );`.

I'm wondering if we should either a) avoid calling a getter function for theme data at registration time in the Template Part block, or b) work out a way to reliably clean the cached data at the right time once all blocks are registered. CC: @talldan in case this sparks any ideas, too.

Does anyone have any strong opinions on what the correct caching behaviour should be here?

**Comment by talldan** [comment] 2022-09-28 03:24
> I'm wondering if we should either a) avoid calling a getter function for theme data at registration time in the Template Part block, or b) work out a way to reliably clean the cached data at the right time once all blocks are registered. CC: @talldan in case this sparks any ideas, too.

A short term fix isn't a bad idea for 6.1. A longer term fix should also be investigated as this code is too fragile. `get_block_templates` is a public function, and it's one that plugins could very well be interested in calling, so while there's some ability to fix this internally, the deeper problem is exposing brittle APIs for public consumption.

Possibly a quick fix would be to add a way to get templates without filling the theme json cache.
 
Looking at the deeper problem, to me it seems like there should be some cache invalidation at certain points.

There are also dependency issues. Getting template parts shouldn't require compiling and caching the entire theme json. A lot of the settings in theme json are completely unrelated, so it might be worth breaking the cache into smaller sub-caches. The filling and invalidation of those caches can then be optimized in a way that wouldn't have been possible before.

**Comment by andrewserong** [comment] 2022-09-28 06:36
Thanks @talldan, you raise some great points! Ideally `get_block_templates` wouldn't have such potentially risky side-effects 👍

In order to try to find a pragmatic short-term fix, I've opened up a core PR in https://github.com/WordPress/wordpress-develop/pull/3352 to try adding a comparable `clean_cached_data` static method to the `WP_Theme_JSON` class and call both it and `WP_Theme_JSON_Resolver::clean_cached_data()` when the Template Part block has finished gathering its variations. I'm wrapping up for the day now, but happy to try to look into adding tests for it tomorrow if it looks viable (I'm not 100% sure how to reliably test for it, so also very happy for any ideas on that PR if anyone gets the chance 🙂)

I figure a core PR is a better way to test for a fix than doing it in the GB repo. Whichever fix we come up with, we can then port it back over to GB once it's landed.

**Comment by ockham** [comment] 2022-09-28 13:55
Thanks @oandregal @andrewserong @talldan for helping track this down!

Upon reading @andrewserong's [comment](https://github.com/WordPress/gutenberg/issues/44434#issuecomment-1260270326), especially this part:

> [...] I think I've found the area that's causing the issue in the Template Part block's `build_template_part_block_instance_variations` function. This function is called when the block is registered, rather than when it's rendered, and uses the get_block_templates function [on this line](https://github.com/WordPress/wordpress-develop/blob/3b63a75108b7f6d5e9112c556285ab1bc80ddbcf/src/wp-includes/blocks/template-part.php#L193), which appears to eventually further down the line call `get_theme_data` [here](https://github.com/WordPress/wordpress-develop/blob/f9769f5eaea747a2183d912d649046a5dbb0d291/src/wp-includes/block-template-utils.php#L354), causing the list of registered blocks to be cached.

...I had one idea off the top of my head: It seems like there's actually a few unneeded function calls, mostly due to the fact that templates and template _parts_ share a lot of logic. Specifically, we're obviously only interested in template _parts_ here; still we end up [calling `WP_Theme_JSON_Resolver::get_theme_data()->get_custom_templates()`](https://github.com/WordPress/wordpress-develop/blob/f9769f5eaea747a2183d912d649046a5dbb0d291/src/wp-includes/block-template-utils.php#L354). But that's the list of [custom page templates](https://developer.wordpress.org/themes/template-files-section/page-template-files/) that are included in the theme -- which shouldn't have any bearing on template _parts_.

So maybe we can leverage the fact that we already know (and specify) that we're only interested in template _parts_ upon [invoking `get_block_templates`]((https://github.com/WordPress/wordpress-develop/blob/3b63a75108b7f6d5e9112c556285ab1bc80ddbcf/src/wp-includes/blocks/template-part.php#L193)) in order to avoid calling functions that are only relevant to templates (but not parts) 🤔

**Comment by ockham** [comment] 2022-09-28 14:21
Uh, nevermind. I think the line we're calling is [this](https://github.com/WordPress/wordpress-develop/blob/f9769f5eaea747a2183d912d649046a5dbb0d291/src/wp-includes/block-template-utils.php#L374) (rather than [this](https://github.com/WordPress/wordpress-develop/blob/f9769f5eaea747a2183d912d649046a5dbb0d291/src/wp-includes/block-template-utils.php#L354)), so it goes through `_add_block_template_part_area_info` rather than `_add_block_template_info`. That's the correct behavior; `_add_block_template_part_area_info` just also happens to call `WP_Theme_JSON_Resolver::get_theme_data()` -- albeit to chain it to `->get_template_parts()` rather than templates.

So no potential to fix this here 😬

**Comment by ockham** [comment] 2022-09-28 19:00
I've filed an alternative fix here, based on y'all's findings: https://github.com/WordPress/wordpress-develop/pull/3359 😊

**Comment by andrewserong** [comment] 2022-09-28 23:58
Great work @ockham, that feels much closer to an ideal fix. Just left a comment over on that PR — I think there's still a bit more fussing we need to do with the clearing the resolver cache to get the Button styling in TwentyTwentyTwo working again, but I think we're heading in the right direction!

**Comment by andrewserong** [comment] 2022-09-30 05:09
Building on the idea @ockham is exploring, I've opened up another alternative PR in https://github.com/WordPress/wordpress-develop/pull/3373 which tries to be a bit more explicit about when we cache bust in the Theme JSON and Resolver classes — basically, trying to make sure that a change in the number of registered blocks results in the cache being regenerated for just what we need. I think this should fix the issue while still preserving the performance benefits of the current caching.

If anyone gets a chance to take a look, I can work through any feedback on Monday. CC: @talldan @jorgefilipecosta @oandregal

**Comment by andrewserong** [comment] 2022-10-03 05:41
I've opened (yet another) PR in https://github.com/WordPress/wordpress-develop/pull/3392 to explore a potential solution. @ramonjd and @ajlende rightly pointed out that checking for the number of registered blocks can result in edge cases where the caching isn't busted when we expect it to be. In this alternative PR, I'm proposing adding a `registered_block_type` action, and to use this to flush the Theme JSON and Resolver caches — that way it's ensured the caches are cleared whenever a block is registered, rather than attempting to infer the current state within the Theme JSON/Resolver classes.

Happy for any feedback / ideas if folks think a different approach would be better!

**Comment by oandregal** [comment] 2022-10-03 11:57
I've looked at alternatives and https://github.com/WordPress/wordpress-develop/pull/3392 (cleaning data when a new block is registered) sounds theoretically the best approach, though 1) we also need to consider that blocks can be unregistered as well, and 2) there are a few paths 3rd parties can use to register a block AFAIK.

It sounds like https://github.com/WordPress/wordpress-develop/pull/3359 may be a more robust fix for 6.1. We can look at this more holistically after 6.1.

**Comment by andrewserong** [comment] 2022-10-03 22:59
Thanks for taking a look @oandregal! I think @ajlende's feedback about moving the "registered" hook to the `WP_Block_Type_Registry` class would ensure we catch all block registrations (including 3rd party ones), and remove a little duplication. I'll have a play at updating https://github.com/WordPress/wordpress-develop/pull/3392 today.

**Comment by andrewserong** [comment] 2022-10-04 00:29
I've updated https://github.com/WordPress/wordpress-develop/pull/3392 to move the hook to the registry class, which now seems to capture all cases where a block might be registered.

**Comment by ockham** [comment] 2022-10-04 09:08
Update: We now have a few candidates to fix this issue:

- https://github.com/WordPress/wordpress-develop/pull/3352
  - Adds a static `clean_cached_data` method to `WP_Theme_JSON` and uses that plus the existing `WP_Theme_JSON_Resolver::clean_cached_data` method after registration of the Template Part block.
  - ⚠️ _This [would require exposing those static methods through a wrapper function](https://github.com/WordPress/wordpress-develop/pull/3352#issuecomment-1261293667), plus adding a fallback in Gutenberg in case the required functions aren't present in Core._
  - ⚠️ _It also means manually clearing a -- seemingly unrelated -- cache from within registration of a specific block. While not a problem currently, there's a risk that other blocks might need similar intervention -- and it's likely not a pattern we'd like to see proliferate._
- https://github.com/WordPress/wordpress-develop/pull/3359
  - Changes `WP_Theme_JSON::get_blocks_metadata` to add blocks metadata for any blocks that aren't cached yet.
  - Removes caching altogether from `WP_Theme_JSON_Resolver::get_theme_data`.
  - ⚠️ _Removing caching altogether [might present some performance issues](https://github.com/WordPress/wordpress-develop/pull/3359#issuecomment-1263105858)._
- https://github.com/WordPress/wordpress-develop/pull/3373
  - Invalidates cache for both `WP_Theme_JSON` and `WP_Theme_JSON_Resolver` based on number of blocks.
  - ⚠️ _This has some [issues when a block is unregistered](https://github.com/WordPress/wordpress-develop/pull/3373#issuecomment-1263806141) and a new one is registered -- which is [already happening](https://github.com/WordPress/wordpress-develop/pull/3373#issuecomment-1263888253)._
- https://github.com/WordPress/wordpress-develop/pull/3384
  - Registers the Template Part block after all other blocks.
  - ⚠️ _Similar concerns as with https://github.com/WordPress/wordpress-develop/pull/3352: Block-specific fix that might not scale in case other blocks will be affected similarly._
- https://github.com/WordPress/wordpress-develop/pull/3392
  - Adds an action to block registration which we then use to clear the cache.
  - ⚠️ _Adds new actions to key events in the block registration lifecycle that didn't previously exist._

Finally, while not a fix to this issue, there's https://github.com/WordPress/gutenberg/pull/44658, which is a related minor performance and code quality improvement.

---

I'll review these alternatives in a follow-up comment and will try to draw up a strategy that we can take from here.

**Comment by ockham** [comment] 2022-10-04 09:33
We have two partial fixes/improvements that I consider very low-risk:

- https://github.com/WordPress/gutenberg/pull/44658
  - Doesn't change any functionality but is a related minor performance and code quality improvement. (This probably disqualifies it from backporting into WP 6.1, but it doesn't harm to have it in GB).
- https://github.com/WordPress/wordpress-develop/pull/3359 (the `WP_Theme_JSON::get_blocks_metadata` part only) 
  - This fixes part of the issue: With it, manual Global Styles changes to individual blocks _are_ applied.
  - Note that this invalidates caching based on the actual blocks registered -- not just their number, see https://github.com/WordPress/wordpress-develop/pull/3359#discussion_r986577138.
  - I'll revert the other part of the PR (the one that removes caching altogether from `WP_Theme_JSON_Resolver::get_theme_data`). While that would fix the other part of the issue (`theme.json` per-block Global Styles settings aren't applied; _edit: I just learned that we have a separate issue for this: https://github.com/WordPress/gutenberg/issues/44619_), [the performance impact might be too big](https://github.com/WordPress/wordpress-develop/pull/3359#issuecomment-1263105858).

I would then like to land those two.

This leaves us with the caching issue in `WP_Theme_JSON_Resolver`. I would like to explore [this suggestion](https://github.com/WordPress/wordpress-develop/pull/3359#discussion_r985689298) by @oandregal for a bit, since it seems like it would tackle the caching issue at its core.

If we cannot get that ready in time, we might instead merge a fallback. I'm currently leaning towards https://github.com/WordPress/wordpress-develop/pull/3384, since it doesn't introduce any new APIs.

**Comment by ockham** [comment] 2022-10-04 12:07
I think one important thing is to treat the issues separately:

1. The `WP_Theme_JSON` [PR](https://github.com/WordPress/wordpress-develop/pull/3359) fixes the manual Global Styles-styling of buttons by the user (this issue).
2. The `theme.json` stuff is broken because of WP_Theme_JSON_Resolver caching ([#44619](https://github.com/WordPress/gutenberg/issues/44619)).

@c4rl0sbr4v0 is currently looking into @oandregal's [suggestion](https://github.com/WordPress/wordpress-develop/pull/3359#discussion_r985689298).

**Comment by ockham** [comment] 2022-10-04 17:45
Update:
1. We've now landed the `WP_Theme_JSON` caching [fix](https://github.com/WordPress/wordpress-develop/pull/3359); it's part of WP 6.1 Beta 3.
2. Carlos has filed https://github.com/WordPress/wordpress-develop/pull/3401 as a tentative fix for https://github.com/WordPress/gutenberg/issues/44619.

I'm considering closing this issue (since it's arguably fixed), and moving discussion over to https://github.com/WordPress/gutenberg/issues/44619 (which AFAICS covers the remaining issue with the theme resolver). Thoughts? 👍 / 👎

**Comment by ndiego** [comment] 2022-10-04 19:25
> I'm considering closing this issue (since it's arguably fixed), and moving discussion over to https://github.com/WordPress/gutenberg/issues/44619 (which AFAICS covers the remaining issue with the theme resolver). Thoughts?

Yeah, in my testing, this issue appears to be fixed in Beta 3

**Comment by andrewserong** [comment] 2022-10-05 01:52
Thanks for weighing up all the options @ockham, and landing the incremental fixes! 🙇

> I'm considering closing this issue (since it's arguably fixed), and moving discussion over to https://github.com/WordPress/gutenberg/issues/44619 (which AFAICS covers the remaining issue with the theme resolver). Thoughts? 👍 / 👎

That sounds good to me. Should we keep a trac issue open for #44619, though, as it's still a blocker for 6.1?

> @c4rl0sbr4v0 is currently looking into @oandregal's https://github.com/WordPress/wordpress-develop/pull/3359#discussion_r985689298.

To keep efforts streamlined, I've closed out my alternate PRs now, but do ping me if you need a review on anything. Thanks for digging in to find the right solution!

**Comment by ockham** [comment] 2022-10-05 11:04
> That sounds good to me. Should we keep a trac issue open for https://github.com/WordPress/gutenberg/issues/44619, though, as it's still a blocker for 6.1?

Yeah, good point. I'll file one 👍 

> To keep efforts streamlined, I've closed out my alternate PRs now, but do ping me if you need a review on anything. Thanks for digging in to find the right solution!

Thank _you_ for all your work and research! ❤️

**Closed as completed by ockham** 2022-10-05 11:04 UTC
Labels: [Type] Bug, [Priority] High, Global Styles

**Comment by ockham** [comment] 2022-10-05 11:14
> > That sounds good to me. Should we keep a trac issue open for #44619, though, as it's still a blocker for 6.1?
> 
> Yeah, good point. I'll file one 👍

https://core.trac.wordpress.org/ticket/56736
