### ISSUE TITLE
"Add a link" only offers posts whereas current WP Editor offers posts and pages

### ISSUE THREAD

**Issue by aileenf** [WordPress/gutenberg#8152] opened 2018-07-23 21:51 UTC
The "add a link" icon within the paragraph (and other) blocks brings up a set of suggestions as you start to type.  This only seems to offer posts, whereas the current WP Editor offers posts and pages and, I think, custom post types as well.

Create a block,
Type in some text.
Select some of the text.
Click on the "add a link" icon.
Start typing the title of a page (not post) on your site.
See if the page appears in the suggestions drop-down. (I believe it won't)

The current WP Editor offers posts and pages and, I think, custom post types as well, in that suggestions drop-down. This is much more helpful and I think should be mirrored in the Gutenberg editor. It seems to me to be a step backward to only offer posts.

Seen in Gutenberg v3.3.0
I did spot this in earlier versions but thought it might be corrected by now.

Thanks for listening.

**Comment by chrisvanpatten** [comment] 2018-07-23 21:55
Hi @aileenf — Thanks for the report!

This is a duplicate of #2084, which is slowly working its way into Gutenberg. You can follow along with the progress at #7894, which will hopefully land soon!

**Closed** 2018-07-24 03:11 UTC
Labels: [Status] Duplicate, [Type] Bug
