### ISSUE TITLE
When using the same classic menu at more than 1 instance on the FSE, the menu duplicates itself

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#38034] opened 2022-01-17 19:00 UTC
### Description

Note: this issue was originally report on Trac. See https://core.trac.wordpress.org/ticket/54792.

**When using the same classic menu at more than 1 instance on the FSE, the menu duplicates itself**

### Step-by-step reproduction instructions

1. Create a classic menu before activating block theme
2. Add a Nav Menu Block -> select the classic menu
3. Add a new Nav Menu Block -> select the same classic menu selected above. (Repeat the same step however times you need)
4. Go to Manage Menu. You'll find the same classic menu duplicated. 

The same happens every time 'start empty' is used in Nav Menu.

### Screenshots, screen recording, code snippet

![xuJp8Kn](https://user-images.githubusercontent.com/1590998/149824436-547571b2-cf23-4445-a224-abb30aeb2886.png)

### Environment info

WordPress 5.9 RC 2 without Gutenberg plugin installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-01-17 19:23
I can replicate this! Going to flag in the navigation block feature channel for good measure.

**Comment by talldan** [comment] 2022-01-18 01:03
When a classic menu is selected, it's copied to the new navigation block format and the original menu is kept in place. The same will also happen a second time. I think this is probably mostly a case of unclear UI, but there has also been discussion about how to better handle menus in https://github.com/WordPress/gutenberg/issues/36307 and https://github.com/WordPress/gutenberg/pull/36311.

**Comment by annezazu** [comment] 2022-01-18 01:11
Thanks for connecting the dots. The fact that every time I select the classic menu (no matter how many times), it recreates the new block format resulting in a new menu seems like something to resolve before 5.9. I imagine many folks will want to first use their classic menu and might continue to select it out of habit/lack of knowledge. 

In any case, +1 on unclear UI.

**Comment by talldan** [comment] 2022-01-18 01:50
I definitely see that.

It's now too late to include anything in 5.9, the final backports from Gutenberg have already been made. So 5.9.1 is the best we can do.

Some options have been outlined in #36311. I'm not sure there's value in keeping two very similar issues open, so I think it's worth closing this as a duplicate of #36307 and I'll add some more comments over there.

**Closed as completed by talldan** 2022-01-18 01:50 UTC
Labels: [Type] Bug, [Block] Navigation
