### ISSUE TITLE
Can't use hooks with the save function

### ISSUE THREAD

**Issue by tlosbar** [WordPress/gutenberg#36265] opened 2021-11-05 16:32 UTC
### Description

I'm trying to implement some gutenberg blocks for a plugin. I wrote custom hooks, working with axios and simply use the hooks useEffect() from @wordpress/elements and I have also some components (React Function) which use hooks  like useState() , useContext() from @wordpress/elements too.

These components and their hooks inside work well in the Edit function. But I can't get rid of the Invariant React Error when using it in the Save function.

### Expected
Use hooks inside the Save function deeply or even at top level

### Currently happening

```error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

### Step-by-step reproduction instructions

To reproduce the error, you can start any simple plugin with the @wordpress/scripts create-blocks like I did.

(I updated my folder architecture just because I want to implement multiple blocks. But I think this is not important to reproduce the error)

Then this is an example of my code : 

_ckanRequestContainer.js_

```javascript
import { createContext, useContext, useMemo } from '@wordpress/element';
import axios from 'axios';

export const CkanContext = createContext();

export const useCkan = () => useContext(CkanContext);

export default function CkanProvider({ children }) {
	const api = useMemo(() => {
		const _api = axios.create({
			baseURL:
				'http://ckanUrl' + '/api/3/action/',
		});
		return _api;
	}, []);

	return <CkanContext.Provider value={api}>{children}</CkanContext.Provider>;
}
```

_save.js_

```javascript
export default function Save() {
	const blockProps = useBlockProps.save();

	return (
		<div {...blockProps}>
			<CkanProvider>
				<Recents></Recents>
			</CkanProvider>
		</div>
	);
}
```

_index.js_

``` javascript
registerBlockType('wpckan-blocks/recent-datasets', {
	/**
	 * @see ./edit.js
	 */
	edit: Edit,

	/**
	 * @see ./save.js
	 */
	save: Save,
});
```

### Environment info

I'm working on a Mac
nvm version : 14.15.0
npm version 8.1.0

Few dependencies: 

```json
"dependencies": {
	"@heroicons/react": "^1.0.5",
	"@tailwindcss/forms": "^0.3.4",
	"@tailwindcss/line-clamp": "^0.2.2",
	"@wordpress/block-editor": "^7.0.3",
	"@wordpress/blocks": "^11.1.1",
	"@wordpress/components": "^18.0.0",
	"@wordpress/data": "^6.1.2",
	"@wordpress/dom-ready": "^3.2.2",
	"@wordpress/element": "^4.0.3",
	"@wordpress/i18n": "^4.2.3",
	"@wordpress/icons": "^6.0.0",
	"@wordpress/notices": "^3.2.5",
	"axios": "^0.24.0",
	"bytes": "^3.1.0",
	"markdown-it": "^12.2.0",
	"portal": "github:datopian/portal.js",
	"prop-types": "^15.7.2",
	"timeago.js": "^4.0.2"
},
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment] 2021-11-07 21:37
Hey @tlosbar,

This is a common misunderstanding of what the `save` method is actually doing. Unlike the `edit` method the react code here won't actually get executed on the frontend of the site. Instead, the `save` method gets used to generate a string of HTML markup that gets saved to the database. 

Therefore the `save` method won't allow you to execute async code. 

If you want/need to have some interactivity on the frontend of the site the recommended way is to use the `save` method to pass the data / a server site generated version of the component to the frontend and then also add a frontend `script` file in which you can rehydrate the component on the frontend again. That is a manual process though. 

You can see a small example of a core block that does something similar is the Core Navigation block here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/view.js

Hope this helps :) 

I'm going to close the issue for now since there is no unexpected behavior as far as I can tell. Feel free to open it up again if I missed anything though.

**Closed as completed by fabiankaegy** 2021-11-07 21:37 UTC

**Comment by omar-snutig** [comment] 2023-10-18 10:15
> Hey @tlosbar,
> 
> This is a common misunderstanding of what the `save` method is actually doing. Unlike the `edit` method the react code here won't actually get executed on the frontend of the site. Instead, the `save` method gets used to generate a string of HTML markup that gets saved to the database.
> 
> Therefore the `save` method won't allow you to execute async code.
> 
> If you want/need to have some interactivity on the frontend of the site the recommended way is to use the `save` method to pass the data / a server site generated version of the component to the frontend and then also add a frontend `script` file in which you can rehydrate the component on the frontend again. That is a manual process though.
> 
> You can see a small example of a core block that does something similar is the Core Navigation block here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/view.js
> 
> Hope this helps :)
> 
> I'm going to close the issue for now since there is no unexpected behavior as far as I can tell. Feel free to open it up again if I missed anything though.

I'm sorry, but what's the point of introducing WP to the React ecosystem if it doesn't support rendering basic react features like useState? Why would anyone want to use React in the editor but not in the normal WP Pages?

**Comment by wpsoul** [comment] 2025-06-13 19:30
I had the same question. So, I made custom block as React Rooter. How it works - it creates edit function and also add React initialization on frontend with usage of the same file. So, it's like block that has full React usage in editor and on frontend and it loads only necessary things + webpack everything so it's browser friendly

You can download code and find details [in blog ](https://greenshiftwp.com/react-rooter-for-wordpress/)
