### ISSUE TITLE
Image block styles (e.g. circle mask) not available after making parent block reusable

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#20139] opened 2020-02-10 13:48 UTC
**Describe the bug**
I have a cover block containing columns, one of these columns has an image block which has had a circle mask style defined using the options in the block options. If I convert the cover block to a reusable block and attempt to edit the block there are no longer styles available for changing the image style.

**To reproduce**
1. Create a cover block
2. Create a columns block inside the cover
3. Add an image block to a column
4. Change the image style to a circle mask
5. Save cover block as a reusable block
6. Edit the reusable block, check the image settings
7. There is no longer image styles available for selection

**Expected behavior**
Image styles still available once image blocks parent block has been made reusable.

**Comment by draganescu** [comment] 2020-02-11 13:31
Howdy, @ninetyninew I have tested your scenario and indeed, there appears to be a problem. It is not only that the images have no styles but apparently the sidebar does not register any block being selected:

<img width="855" alt="Screenshot 2020-02-11 at 15 29 40" src="https://user-images.githubusercontent.com/107534/74240938-9d62b380-4ce3-11ea-86bb-6ff36c866e30.png">

**Comment by noisysocks** [comment] 2020-04-21 03:33
Duplicate of https://github.com/WordPress/gutenberg/issues/18560.

**Closed by noisysocks** 2020-04-21 03:33 UTC
Labels: [Feature] Reusable Blocks, [Type] Bug
