### ISSUE TITLE
Header block toolbars hidden under site editor top menu

### ISSUE THREAD

**Issue by bbertucc** [WordPress/gutenberg#32827] opened 2021-06-18 18:38 UTC
<img width="522" alt="Screen Shot 2021-06-18 at 1 33 56 PM" src="https://user-images.githubusercontent.com/46652/122603630-4210a600-d03a-11eb-90ca-89264737970a.png">
<img width="429" alt="Screen Shot 2021-06-18 at 1 35 11 PM" src="https://user-images.githubusercontent.com/46652/122603633-4210a600-d03a-11eb-9299-fbc8857210dc.png">

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No... Blockbase

## Device information
- Device: Desktop
- Operating system: macOS 11.4
- Browser: Safari  14.1.1

**Comment by talldan** [comment] 2021-06-22 04:22
I can't reproduce this in Twenty Twenty One (Blocks). Could it be a theme issue?

**Comment by bbertucc** [comment] 2021-06-22 19:53
Could be @talldan ! I am using Blockbase

**Comment by skorasaurus** [comment] 2021-06-25 19:57
This appears to be a duplicate of https://github.com/WordPress/gutenberg/issues/27840

**Closed as completed by skorasaurus** 2021-06-25 19:57 UTC
Labels: General Interface, Needs Testing, [Feature] Site Editor
