### ISSUE TITLE
"Leave site?" alert too aggressive

### ISSUE THREAD

**Issue by jomurgel** [WordPress/gutenberg#46235] opened 2022-12-01 14:39 UTC
### Description

The "Leave site?" alert is too aggressive. When using the post type template argument for creating pre-defined block layouts for core/custom post types an entity edit is created `{ blocks: ... }` which looking at the logic added in https://github.com/WordPress/gutenberg/pull/24659 which only checks to see if the `wp.data.select('core/editor').getPostEdits()` return object has any keys, would ALWAYS return the "Leave site?" alert even if no other changes were made.

This is also true for any features that might make some update (create blocks, etc) with or without an undo level.

I would expect that the alert only changes if there are valid or manually-added changes to the new post. Or at the very least a title has been added or some non-default post content.

This is also a persistent change in the entity which means even after an update the blocks key exists in the entity object which would then ALWAY return the "Leave site?" alert, again, even though the post was just edited.

NOTE: Tests a brand new WP install no plugins active, installed. Tested filtering the post post type as well as with custom post types.

Entity added here: https://github.com/WordPress/gutenberg/blob/33d84b036592a5bf31af05b7710f3b2b14163dc4/packages/core-data/src/entity-provider.js#L187
Check here: https://github.com/WordPress/gutenberg/pull/24659/files#diff-53f39da7a5f1f996f5359a2dd7b2747fb3d60a494523dd73dba946fab8e82592R102 for length, or https://github.com/WordPress/gutenberg/pull/24659/files#diff-8933c0b377d83066f7dde9c8b573bab9a7bfe60f73919e4e5e80aff92a88800cR119 which uses https://github.com/WordPress/gutenberg/blob/dc107885fec50ab7417afcb545d97cd63cbc9577/packages/editor/src/store/selectors.js#L117 which returns a length check here: https://github.com/WordPress/gutenberg/blob/dc107885fec50ab7417afcb545d97cd63cbc9577/packages/core-data/src/selectors.ts#L730

### Step-by-step reproduction instructions

- Create a custom post type (or filter an existing post type).
- Add a custom template (https://developer.wordpress.org/reference/functions/register_post_type/) and include at least one block. For example:

```
'template' => [
  [ 'core/paragraph' ],
  [ 'core/list' ],
],
```

- "Add New" post that uses this template. Make not other edits.
- In the console run `wp.data.select('core/editor').getPostEdits()` and confirm the existence of blocks in the entity. Something like `{ blocks: ... }`.
- Confirm also that when leaving the page by either clicking out of the editor or trying to close the tab that the "Leave site?" alert is present.
- Confirm multiple times.
- Remove the template. Confirm that the behavior above does not take place if a template is not present.

### Environment info

- WordPress 6.1.1
- All Browsers
- Macbook Pro M1 | macOs 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2022-12-06 06:38
The issue is happening specifically when you include an empty list block in a template. With WordPress 6.1, the list block has been changed to use inner blocks and when loading a post an inner 'list item' block is automatically added. That makes the post content dirty.

To work around it, you could update your template to this:
```php
'template' => [
  [ 'core/paragraph' ],
  [ 'core/list', [], [ [ 'core/list-item' ] ] ],
],
```

Essentially it makes sure the list item inner block is there from the start so that post isn't made dirty.

I couldn't reproduce the issue with the Gutenberg plugin active, it seems this problem has been fixed (the workaround isn't required). I think the fix is this PR - https://github.com/WordPress/gutenberg/pull/45843, it was in Gutenberg 14.7. It should be solved when WP 6.2 is released. As such I'll close the issue, but do perform your own testing and share results in this issue.

**Closed as completed by talldan** 2022-12-06 06:38 UTC
Labels: [Feature] Templates API

**Comment by jomurgel** [comment] 2023-01-23 18:04
@talldan that is actually not the issue, regardless of list item or not the issue is persistent. The list/paragraph template was an example. This would be true including any block. I would have appreciated additional questioning or a request for context before closing the ticket. This is still an issue.

**Comment by talldan** [comment] 2023-01-24 01:59
> The list/paragraph template was an example. This would be true including any block.

@jomurgel Could you provide some additional steps to reproduce these situations? In my testing I couldn't reproduce the situation you're describing, but if you have some additional steps that might be helpful.

Could you also let me know which version of Gutenberg you have active?
