### ISSUE TITLE
Video block: URL edit button is inaccessible

### ISSUE THREAD

**Issue by EricDu** [WordPress/gutenberg#50488] opened 2023-05-09 20:05 UTC
### Description

Reported on https://core.trac.wordpress.org/ticket/58280

When replacing a video, the "Edit URL" button is out of sight and requires horizontal scrolling to find it.

### Step-by-step reproduction instructions

1. Add a video block. Input vide URL.
2. Select "Replace".
3. Video URL is outside the modal. You have to scroll horizontally to find it.

Solution would be to add a max-width to _block-editor-link-control__search-item-header_ (hoping that doesn't break anything else).

### Environment info

WordPress 6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment] 2023-05-10 05:00
Thank you for opening this issue! From a little big of digging, it appears that it's already been fixed in the Gutenberg plugin (in https://github.com/WordPress/gutenberg/pull/47949, which landed in GB version 15.3), and the fix will be rolled out into WordPress core in WordPress 6.3.

Here's how that component is looking in my test environment:

<img width="590" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/9ad4739b-a3fa-44fd-bc98-dd045a35e6fa">

It looks like the wrapper for `block-editor-link-control__search-item-info` was missing a `max-width`, so the text wasn't being truncated. #47949 added in the missing `max-width`.

I'll close out this issue now since the fix is in the plugin. Feel free to re-open if you can reproduce the issue with the current version of the Gutenberg plugin active.

**Closed as completed by andrewserong** 2023-05-10 05:00 UTC
Labels: [Type] Bug, [Feature] Link Editing
