### ISSUE TITLE
Widgets editor: removed block reappearing when disabling the editor

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#31912] opened 2021-05-17 20:02 UTC
## Description
Removed block or widget removes it from the Widgets Editor; however, when the editor feature is disabled, the removed block/widget reappears as "Inactive widgets".

## Step-by-step reproduction instructions

1. Go to Appearance → Widgets
2. Remove a widget/block
3. Click on the "Update" button
4. Open the "Inactive widgets" area and notice the removed widget/block is not there
5. Go to Plugins → Installed Plugins
6. Activate the Classic Widgets plugin
7. Go to Appearance → Widgets => _notice the removed widget/block still exists and is in the "Inactive widgets" area_

## Expected behaviour

Removed widgets/blocks are deleted from memory and database after successfully updating (i.e. clicking on the "Update" button and getting the "Widgets saved" message and then not restored as inactive when disabling the Widgets Editor feature.

## Actual behaviour

Removed widgets/blocks do not display in the Widgets Editor and are not in the `sidebars_widgets` option (in Options database table). However, when disabling the Widgets Editor feature, the removed widgets/blocks are reinserted into the  `sidebars_widgets` option and then render in the "Inactive widgets" area.

## Screenshots or screen recording (optional)

![removed-widgets-restored-to-inactive](https://user-images.githubusercontent.com/7284611/118548770-463a6280-b720-11eb-839b-7bb97c8a91b8.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? Yes, except when checking for inactive widgets
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur
- Browser: Chrome 90.0, Firefox 88.0.1, Safari 14.1

**Comment by noisysocks** [comment] 2021-06-01 02:06
Thanks for the detailed report! This is a duplicate of https://github.com/WordPress/gutenberg/issues/31575 which now lives in https://core.trac.wordpress.org/ticket/53313.

**Closed as completed by noisysocks** 2021-06-01 02:06 UTC
Labels: [Type] Bug, [Feature] Widgets Screen
