### ISSUE TITLE
Flickr embed not embedding from flic.kr shared url

### ISSUE THREAD

**Issue by josephdickson** [WordPress/gutenberg#22361] opened 2020-05-14 16:01 UTC
I originally shared this on trac a moment ago at https://core.trac.wordpress.org/ticket/50172

Flickr albums or collections from a "sharing url" do not embed.

**Steps to reproduce**

1. Visit a Flickr album
2. Use the sharing features on Flickr to provide their _tiny-url_ such as https://flic.kr/s/aHsmLCQa2e
3. Try embedding this url into a Flickr block. 

**Possible fix**
Update block to recognize alternate flickr domain.
https://flic.kr/s/aHsmLCQa2e

**Watch this brief video for a workflow example in Twenty Twenty.**
https://www.linuxbookpro.com/flickr-wordpress-block-not-working/

**Special Notes**
Full URLs work but users may not be aware to test both
https://www.flickr.com/photos/nasa2explore/albums/72157713265937611

Problem exists using Gutenberg Beta plugin a well.

**Comment by karmatosed** [comment] 2020-05-15 13:35
@josephchesterton Thanks for reporting this, do you think it's an issue because of a change in Flickr or specific to albums? I can also confirm the problem so going to put a few labels on for more insights.

**Comment by skorasaurus** [comment] 2021-05-04 15:57
Hi, 

Thanks for reporting. @earnjam [determined it was an issue with flickr's oembed endpoint](https://core.trac.wordpress.org/ticket/50172#comment:2)

Should this be closed here or at trac or both issues closed?

**Comment by tellthemachines** [comment] 2023-05-11 05:01
I can no longer reproduce this issue so assume it has been fixed upstream. Closing.

**Closed by tellthemachines** 2023-05-11 05:01 UTC
Labels: [Type] Enhancement, Needs Technical Feedback, [Block] Embed
