### ISSUE TITLE
[Post Comments] Blocks under comments pagination do not clear floats

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#38188] opened 2022-01-24 18:42 UTC
Originally reported in https://github.com/WordPress/twentytwentytwo/issues/314.

---

When breaking the comments into pages, the comment navigation is missing CSS styles to clear those elements after float.

**To Reproduce**

1. Create a post and make a few comments, let's say 13 (why not?)
2. Activate Break comments into pages under Settings -> Discussion. Set to an amount that will ensure the comment navigation to show.
3. Visualise the post with the comments
4. See CSS problem

**Expected behavior**

Elements before and after the wp comment block containing the navigation should be cleared and avoid overlapping.

## Screenshots:

Current|Expected
---|---
<img width="1029" alt="147603584-9d793132-5868-4acf-8b66-3390cc553bc3" src="https://user-images.githubusercontent.com/1202812/150844022-ea9b5270-ff60-4e37-a2f9-8e4b5c880d4f.png">|<img width="1029" alt="147603659-0152fc79-ead3-443a-ac51-2a6d20256300" src="https://user-images.githubusercontent.com/1202812/150844026-343d5d6e-4833-4f98-a908-95bf271787c1.png">

**Comment by cbravobernal** [comment] 2022-05-03 14:05
Hi @kjellr !

I cannot reproduce the issue. Could you please provide some more information? Has it already been addressed?

**Comment by jordesign** [comment] 2023-08-21 00:51
Closing this issue as the Legacy Comments block has been deprecated.

**Closed as not planned by jordesign** 2023-08-21 00:51 UTC
Labels: [Type] Bug, [Block] Comments (legacy)
