### ISSUE TITLE
Block hover outline appears on another block while typing

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11133] opened 2018-10-26 17:58 UTC
**Describe the bug**
This feels like a critical violation of the "just write" ethos Gutenberg hopes to achieve.

**To Reproduce**
When typing, hover your cursor over a different block. The outline will appear for the block you are _not_ working on. This is especially distracting if you happen to nudge your cursor into a different block area.

**Expected behavior**
If I'm writing, the UI should not encourage me to look elsewhere. I also don't know what caused the formatting toolbar to briefly pop up.

**Screenshots**
![Animated GIF showing described behavior](https://user-images.githubusercontent.com/1238696/47584035-e97ebe80-d90d-11e8-9649-4c98ca285afd.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 62.0.3
 - Version WP 5.0 beta-1

**Comment by designsimply** [comment] 2018-10-26 18:10
Adding the `Needs Testing` label and noting we should check whether this also happens with the 4.1.1 plugin or whether it's limited to WP 5.0 beta.

**Comment by Robertght** [comment] 2018-10-28 11:17
I can confirm the behaviour on Gutenberg 4.1.1 with WordPress 4.9.8 as well.

OS: MacOS Mojave,
Browser: Chrome 69.0.3497.100 and Version 70.0.3538.77 (ran an update after checking the version the first time :) )

cc @designsimply

**Comment by earnjam** [comment] 2018-10-29 10:30
I'm going to label this as a bug. The cursor is supposed to disappear when typing resumes, and it does in my testing, however the blue block hover outline still remains.

**Comment by earnjam** [comment] 2018-10-29 10:31
Actually, we may need some feedback from design that this wasn't on purpose before we make it actionable though.

**Comment by mrwweb** [comment] 2018-11-01 19:41
Running 5.0-beta2 this (and all hover outlines on paragraphs?) seem to be gone. Is that intended? Was this addressed elsewhere?

**Comment by melchoyce** [comment] 2018-11-15 21:17
@mrwweb It's intended in Focus mode — see #9394.

**Comment by designsimply** [comment] 2019-03-11 20:31
Re-tested and confirmed using WordPress 5.1 and no plugins that the block outline and label are always on for blocks the mouse is hovered over, even if you start typing into a different block. This does appear to be the intended behavior. @mrwweb, just to check, does using Spotlight Mode which has no outlines on hover solve this issue for you? I think this is exactly the kind of thing the different modes were designed to help solve.

**Comment by mrwweb** [comment] 2019-03-12 14:15
If that's intended behavior, then so be it. I don't like spotlight mode, so that's not a solution for me.

My overall goal is that I like to write where I can see what's before (and sometimes after) what I'm writing so that I work in context. I don't like it when those things are obscured, adorned or flashing. That's why for me, I turn on Top Toolbar but not Spotlight.

That said, sounds like this ticket isn't going anywhere so probably just worth closing? :/

**Comment by ellatrix** [comment] 2019-03-18 08:56
I keep running into the same issue:

<img width="677" alt="Screenshot 2019-03-18 at 09 49 51" src="https://user-images.githubusercontent.com/4710635/54518150-eb502980-4963-11e9-831f-d82b7cfa0a24.png">

@melchoyce I don't think this intended behaviour? All block UI is supposed to fade away when typing starts.

**Comment by melchoyce** [comment] 2019-03-18 14:41
You're right — pinging @jasmussen and @kjellr in on this.

**Comment by kjellr** [comment] 2019-03-18 16:17
Thanks for the ping. I'd definitely be supportive of removing those hover states when the user is typing.

**Comment by mrwweb** [comment] 2019-11-23 16:26
Just noting that while the hover style has changed significantly since the screenshots were taken, the issue remains in WP 5.3.

**Comment by jasmussen** [comment] 2019-11-25 07:43
> Just noting that while the hover style has changed significantly since the screenshots were taken, the issue remains in WP 5.3.

I would suggest that #17088 (which suggests to explore _no hover style_) and even #18667 might help finally address this one.

**Comment by ZebulanStanphill** [comment] 2019-12-03 13:23
Closing since #18862 removed the hover indicator entirely.

**Closed by ZebulanStanphill** 2019-12-03 13:23 UTC
Labels: General Interface, Good First Issue, [Priority] Low, [Type] Bug
