### ISSUE TITLE
Customize widgets: Link Popover not visible in full (Entire toolbar not visible)

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#41739] opened 2022-06-15 10:21 UTC
### Description

On a theme with block widgets, the toolbar on the widgets area of the Customizer is not visible in full. It gets cut in the middle, with half appearing outside of the display area.

### Step-by-step reproduction instructions

- Start with a theme that has block widgets, like [Twenty Twenty-One](https://wordpress.org/themes/twentytwentyone/) or [Espied](https://wordpress.org/themes/espied/).
- Open the site's Customizer and click on the widgets area.
- Add a list block, or any block.
- Choose the text on the block and add a link.
- Notice that the toolbar that pops up to add the link does not appear in full.

### Screenshots, screen recording, code snippet

<img width="620" alt="image" src="https://user-images.githubusercontent.com/18581859/173804751-3d62fa71-111d-4968-93c0-a6d9ad3d7020.png">

### Environment info

- WordPress 6.0
- Gutenberg 13.4.0
- Firefox 101.0.1 on Mac 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by arunsathiya** [comment] 2022-06-15 10:21
I did my best to locate an existing issue with keywords like `block widget toolbar` and `missing` but can't spot one so far. Happy to be pointed at a report, if one exists already.

**Comment by Thelmachido** [comment] 2022-06-17 14:21
Closing this issue in favor [of this one](https://github.com/Automattic/wp-calypso/issues/64249) since that is already being looked at there.

**Comment by arunsathiya** [comment] 2022-06-17 14:52
@Thelmachido From our testing, it looks like a core bug though, which is why I created this issue. Could we reopen this issue?

**Comment by annezazu** [comment] 2022-06-22 02:39
Re-opening as I can replicate with GB 13.5 RC 1, WP 6.0, and TT1:

<img width="559" alt="Screen Shot 2022-06-21 at 7 37 10 PM" src="https://user-images.githubusercontent.com/26996883/174931497-dd5a7db5-6667-421d-98a5-54b79dd16c2f.png">

While it can be investigated in a separate repo for third party work, it's definitely important to track down the root cause in Gutenberg here, since something seems amiss!

**Comment by talldan** [comment] 2022-06-28 08:58
Is it the Link popover that's cut off? The issue title says toolbar, but it's ok in the screenshots.

edit: Seems so, I've updated the title.

**Comment by talldan** [comment] 2022-07-13 09:10
This issue also happens in other editors. I've worked on a fix for that - #42389.

I expected this to also resolve the issue in the customizer, but it seems now the Link Popover ends up off the other side of the sidebar 😱 
![Screen Shot 2022-07-13 at 4 59 58 pm](https://user-images.githubusercontent.com/677833/178696160-cb4c9762-0fb9-41cf-965b-1a3842f10ae3.png)

I think it should overflow the sidebar like the block toolbar does.

**Comment by andreszs** [comment] 2022-07-13 12:49
**These grotesque GUI flaws could be expected from a Microsoft-owned website**, it's really sad to see them in Wordpress too. There's an alarming lack of testing of new features nowadays, who's rushing the WP team to add more and more features without proper testing?

**Comment by JoryHogeveen** [comment] 2022-08-29 12:21
As mentioned in #43678 the following commit is the cause: https://github.com/WordPress/gutenberg/commit/8b1492131355aa6d42272faba25b841f0cd4509d#diff-7895f8092f907d624abdbe647e2201f1cebe9198cd3fae6ba759b70a4c0bfef4

I believe this is because the `is-expanded` class is never added thus the popover stays in `position: absolute` by default instead of switching to `position: fixed`

**Comment by ciampo** [comment] 2022-09-05 09:03
This issue should have been fixed with the recent work on addressing popover regressions (https://github.com/WordPress/gutenberg/issues/42770). 

Feel free to re-open in case the issue can still be replicated on latest `trunk`. Thank you!

**Comment by ciampo** [comment] 2022-09-05 09:07
> This issue also happens in other editors. I've worked on a fix for that - #42389.
> 
> I expected this to also resolve the issue in the customizer, but it seems now the Link Popover ends up off the other side of the sidebar 😱 ![Screen Shot 2022-07-13 at 4 59 58 pm](https://user-images.githubusercontent.com/677833/178696160-cb4c9762-0fb9-41cf-965b-1a3842f10ae3.png)
> 
> I think it should overflow the sidebar like the block toolbar does.

I actually missed [this comment](https://github.com/WordPress/gutenberg/issues/42770) — it looks like the issue that still needs to be fixed is that the link toolbar is cut off by the toolbar's edges. I'll look into it and report back

**Closed as completed** 2022-09-21 02:23 UTC
Labels: [Type] Bug, [Feature] Link Editing, [Feature] Widgets Customizer
