### ISSUE TITLE
Up Arrow Keypress won't move caret from empty block in Safari

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#51351] opened 2023-06-08 19:40 UTC
### Reproduction
- In Safari
- Add New post
- Press Enter key several times to create new empty paragraphs
- Use up arrow key to try to move caret to previous block
- Caret does not move

Expected: Caret would move to previous block

### Video
https://github.com/WordPress/gutenberg/assets/967608/751015d5-5ca5-4071-9713-2d726d21e99d

**Comment by jordesign** [comment] 2023-07-18 04:35
Confirmed this behaviour in Safari when testing

**Comment by annezazu** [comment] 2023-08-04 19:11
Closing this out as a duplicate of https://github.com/WordPress/gutenberg/issues/53333.

**Closed as completed by annezazu** 2023-08-04 19:11 UTC
Labels: [Type] Bug, [Focus] Accessibility (a11y), Browser Issues, [Feature] Writing Flow, [Package] Block editor
