### ISSUE TITLE
Widget Screen: Unable to remove inactive widgets

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#32583] opened 2021-06-10 11:23 UTC
## Description
Currently, it's not possible to fully remove inactive widgets.

## Step-by-step reproduction instructions
1. Go to `Appearance > Widgets`
2. Add or move widgets to the "Inactive Widgets" area. Save widgets.
3. Delete all widgets from the "Inactive Widgets" area. Save widgets.
4. Switch theme. Widgets are visible in the inactive widgets area.
5. Switch back to the original theme results should be the same.

I was only able to remove them by deleting option: `wp option delete widget_block`

## Expected behaviour
Unable to delete inactive widgets.

## Actual behaviour
I should be able to delete inactive widgets.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: `trunk`
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

**Comment by noisysocks** [comment] 2021-06-11 02:10
Confirmed, though it's hard to narrow this down to a small test case as there's buggy behaviour surrounding moving a block to Inactive Widgets.

**Comment by noisysocks** [comment] 2021-06-11 05:24
I _think_ all of the weirdness I saw in my own testing is due to the one bug which is fixed by https://github.com/WordPress/gutenberg/pull/32608. Give it a test and let me know if that fixes this for you.

**Closed as completed** 2021-06-16 05:04 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Widgets Screen
