### ISSUE TITLE
Focus lost when tabbing to an adjacent paragraph block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#9858] opened 2018-09-13 08:08 UTC
Steps to reproduce:

- Have multiple paragraphs on the page
- set focus in Paragraph 1
- Press tab, to set focus on Paragraph 2

Notice that the text caret is not inserted in paragraph 2, it's only present when pressing an arrow key

GIF:

![tab bug](https://user-images.githubusercontent.com/1204802/45475508-eb653780-b73c-11e8-8fdc-efe96d32c1dd.gif)

**Comment by gziolo** [comment] 2018-10-19 09:16
I don't see any corresponding PRs linked, moving to 4.2.

**Comment by talldan** [comment] 2018-10-25 10:12
I looked into this a bit, and what's happening is that when tabbing, the wrapper of the next block is the next thing in the tab order. Specifically it's the div rendered by this component in BlockListBlock (notice it has a tab index):
https://github.com/WordPress/gutenberg/blob/578d0ef634f33f599e19806d0e479677b9594b59/packages/editor/src/components/block-list/block.js#L469-L488

When continuing to tab, the block prepender and all the toolbar items are then next in the tab order, and then after that the rich-text contenteditable comes into focus.

Potentially a tricky one to solve. I've tried a couple of different approaches, but not really found a solution that doesn't have other drawbacks.

**Comment by ellatrix** [comment] 2019-03-15 15:43
Isn't this what is supposed to happen? The block itself is a tabbable element. Cc @afercia.

**Comment by afercia** [comment] 2019-03-15 17:29
Yep, this is what is supposed to happen.

We're mixing two things here:
- writing flow: non-standard behavior implemented to emulate interaction with a textarea: arrow keys move directly to the _content_ of the block
- tabbing: native behavior: pressing tab (or shift-tab) navigates through the whole block UI, including the "appender inserter" (or whatever it's called), the block movers, the block toolbar buttons. This needs to happen otherwise how keyboard users are supposed to access these controls?

A complete different consideration is how much it's _easy_ to navigate with the keyboard through all these controls:
- the order of the UI is not ideal: this has been mentioned multiple times in various accessibility issues since the very beginning of this project
- there are a lot of controls (at some point it was proposed to make the toolbar an ARIA toolbar with just one tab stop)
- some controls appear/disappear unexpectedly when tabbing (see formatting buttons)
- at some point navigation / edit mode was proposed as a mean to drastically simplify and reduce the number of tab stops in the blocks list
- etc.

All known issues. However, this:

> Press tab, to set focus on Paragraph 2

is not the expected behavior.

Suggest: close.

**Comment by gziolo** [comment] 2019-10-20 03:37
> Suggest: close.

Agreed. In addition, there is now navigation mode.

**Closed by gziolo** 2019-10-20 03:37 UTC
Labels: [Feature] Writing Flow
