### ISSUE TITLE
Site Title Block changes font size when viewed as a template part

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#22483] opened 2020-05-19 23:36 UTC
**Describe the bug**

The Site Title Block changes when viewed as a header template part vs as part of the wider front  page template.

**To reproduce**
1. Head to Gutenberg > Experiments and check both "Enable Full Site Editing"  +  "Enable Full Site Editing demo templates".
2. Edit the Site Title Block.
3. Use the Template Selector to select Template Part > Header.
4. Notice the difference in size of the font of the Site Title Block.

**Expected behavior**

I expected the Site Title Block font size to remain unchanged.

**Screenshots**

Here's a video: https://cloudup.com/c0IAFN0MVBf

View of header template part:

<img width="1440" alt="Screen Shot 2020-05-19 at 4 24 42 PM" src="https://user-images.githubusercontent.com/26996883/82388409-6856b300-99ee-11ea-9c4a-492ded92c5fc.png">

View as part of overall front page template:

<img width="1440" alt="Screen Shot 2020-05-19 at 4 24 52 PM" src="https://user-images.githubusercontent.com/26996883/82388412-6a207680-99ee-11ea-8d75-1beda58b4d62.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 8.1.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 81.0.4044.138

**Comment by alaczek** [comment] 2020-06-16 01:11
Could this possibly be theme related? I tested in Seedlet blocks theme and the font-size remains the same:

![image](https://user-images.githubusercontent.com/4550351/84720406-50f4f080-afc1-11ea-8c43-99b629ca0c68.png)

View of header template part:
![image](https://user-images.githubusercontent.com/4550351/84720582-c52f9400-afc1-11ea-8fa2-7d0c66a79e03.png)

**Comment by carolinan** [comment] 2021-03-24 06:56
Twenty Twenty Blocks is not maintained so I was not able to test with that theme.
I am closing this issue as I am not able to reproduce it in TT1 Blocks, empty theme, Q or Armando.

**Closed by carolinan** 2021-03-24 06:56 UTC
Labels: [Block] Site Title, [Feature] Full Site Editing
