### ISSUE TITLE
Confusing behavior of the sticky position

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#53050] opened 2023-07-27 15:03 UTC
### Description

When a sticky positioned group is inside a template part the sticky behavior does not apply anymore. I am unsure if this is a bug, or just confusing.

### Step-by-step reproduction instructions

1. Create a template in the site editor
2. Create a group 
3. Place some content in the group
4. Set the group to sticky
5. **The group is behaving sticky**
6. Select the group and from the bloc more menu choose create template part
7. **The group is not behaving sticky**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/37a37b8b-168a-4b8c-a1de-b627d1963a53

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment] 2023-07-28 08:18
I can't comment here with absolute confidence, but just looking at the setup here, this seems like "intended behavior of CSS". I say CSS, because I agree it's not user-intuitive. But the group column scrolls out of view because it is not sticky, and does not take up the full height of the column, so whatever content is inside will stick to very little and thus, scroll out of view.

I think the solution here is a combination of CSS warnings ("Hey, careful, the parent is not full-height so you might not see anything sticky effect", something like that), or just general visualization. I believe a blue overlay highlight was discussed when interacting with a sticky position container, or even just the control. This could/should highlight the scrollable area the sticky item would stick to, and if that shows up as _very short_, perhaps it's made clearer that, yeah, it won't stick for very long.

**Comment by tellthemachines** [comment] 2023-08-04 01:39
Yeah the block will only be sticky if its direct parent has enough height to be scrollable.

**Comment by carolinan** [comment] 2024-10-26 11:50
Hi, I am closing this as a duplicate of #50617.

**Closed as not planned by carolinan** 2024-10-26 11:50 UTC
Labels: [Status] Duplicate
