### ISSUE TITLE
SHIFT + Enter doesn’t work in list block

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#12467] opened 2018-11-30 13:43 UTC
**Describe the bug**
If you have a list block and just want to add a line break inside the current list item, there is no way to do this. It should work in list blocks exactly the same as it does in paragraph blocks (which is described in #9930).

**To Reproduce**
1. Add a list block
2. Write content
3. Try to add a line break without adding a new list item with `SHIFT` + `ENTER`

**Expected behavior**
By using `SHIFT` + `ENTER` a new line inside the current list item should be made.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Safari
 - Version: 12.0.1
 - Gutenberg: 4.6.0

**Comment by iseulde** [comment] 2018-11-30 14:02
Duplicate of #11215.

**Closed by iseulde** 2018-11-30 14:02 UTC
