### ISSUE TITLE
BlocK Editor Buggy

### ISSUE THREAD

**Issue by TableDesigns** [WordPress/gutenberg#29006] opened 2021-02-15 14:10 UTC
![ERRORS - BLOCK EDITOR 2!](https://user-images.githubusercontent.com/61430600/107955568-edfe9380-6f6b-11eb-8c78-df8bb40f79d6.jpg)
![ERRORS - BLOCK EDITOR!](https://user-images.githubusercontent.com/61430600/107955570-ee972a00-6f6b-11eb-861c-2ea7885de370.jpg)

## Description

I find bugs in the interface itself. I not only find objects that I created obscured when going back in to do any edits - I also get messages in the editor to try to resolve blocks etc (as can be seen from screenshots)
Additionally, if an interface is going to work like a WYSIWYG I expect to be able to see the objects - example 2 of my attachments demonstrates that there are 'spaces" where there were once 'rows' but I cannot simple select a row in either example or page where I am using the block editor.  A row was created with 3 columns, I can grab the column because it has an image within it, but I can not select "the row"
## Expected behaviour

 I expect the editor to behave as an editor and not have to learn the syntax to hack around what starts not to work or what is the point in having one.
## Actual behaviour

Previous blocks that were built do not display and I am not able to edit - to add a new vendor for example. SIMPLY AND QUICKLY and not having to write github to try to help them with their plugin!
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by TableDesigns** [comment] 2021-02-15 14:16
I am not able to accomodate for every question above. I have to work. The site is live and in order to answer all of our questions i need to be doing so on staging. But I am working for github and sadly can't invest this kind of time. 

Yes I know to disable plugins - but franly they're all working and the block editor isn't

I am using Storefront theme (reliable) with Woocommerce - and up to date Wordpress (always)

Devices - a few - wrok remotely and on different machines. Same issues. Browser Chrome or Firefox.

Apologies if I sound short but this is an issue because it SHOULDN'T BE an issue and I don't feel users should have to help bug test - when I was in dev we did our own before announcing an app was ready to go live.

**Comment by paaljoachim** [comment] 2021-02-15 15:24
Hey @TableDesigns 

It would be very helpful with a step by step. I did this and so that.... etc. So that I can do the same steps and hopefully end up with the same results that you got.

We also need to figure out if this is only related to the Storefront theme and WooCommerce or if I can also recreate the results you had in one of the default WordPress themes.

**Comment by TableDesigns** [comment] 2021-02-15 16:40
Ok so for example, today I had to add a new vendor to the metal category today and within the metal category, the 4 vendor logos displayed should all be the same dimensions (displayed) as all of the others on the page and though they are specified in code to do so – they do not.

https://tabledesigns.com/partners-and-vendors/#metal

Additionally, there are large gaps of space from the Titles (example: https://tabledesigns.com/partners-and-vendors/#metal) to the corresponding logos -

AND too, a few do not align center as requested (on backend)

Example: Under — In-Lay Material Vendors —
Vahallan is OFF -

Example: Under — Laminate and Vinyl Vendors —
The last row vendor “Octopus” does not center

Also, I notice if I want to insert a row – the page forces me to + and then adds the module to the bottom of the page but then DOESN’T display the arrow to MOVE that mod up to where I want it to be – or skips areas – and misbehaves SO much that I give up trying to add it with the block editor – I find myself in code trying to hack it in

Another thing I’ve seen – hand code disappaear -

On staging I have a menu at the top of the page for navigation -
https://www.tabledesigns.com/new_vs3_cloned/partners-and-vendors/

The last few times I have made edits to the LIVE site (page) that menu disappears completely and I have to go get it from staging and insert the code again.

https://tabledesigns.com/partners-and-vendors/

**Comment by paaljoachim** [comment] 2021-02-15 17:23
Hi @TableDesigns 

Please focus on the exact steps so that we can reproduce the error you are getting.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'

**Comment by Sandstromer** [comment] 2021-02-15 17:34
Hi @TableDesigns 

Please also mention the plugin(s) you are using.

It looks like the CoBlocks plugin? If you seeing issues with that plugin it may better to ask their support.

CoBlocks support: https://wordpress.org/support/plugin/coblocks/

CoBlocks github: https://github.com/godaddy-wordpress/coblocks

**Comment by TableDesigns** [comment] 2021-02-15 17:55
It is “WooCommerce Blocks”

WooCommerce blocks for the Gutenberg editor.

Version 4.4.2 | By Automattic and I’m so frustrated, I don’t have time to work on it now and it’s a mess

**Comment by TableDesigns** [comment] 2021-02-15 17:58
It is a page that I had to replicate from a previous website – for vendors and links to them

There isn’t a way for me to tell you to go to … and click on …

I detailed the issues I am having and sent you screenshots smh

Would be great if the objects that were meant to be interface objects were apparent – example a row is a row is a row and when you add one, you can select it – you can see it – it doesn’t disappear as an unknown container

**Comment by paaljoachim** [comment] 2021-02-15 18:07
@TableDesigns Sorry but I can not help you. It sounds like a Storefront WooCommerce issue that you are having. 
This might be the place to ask for support: https://woocommerce.com/my-account/create-a-ticket/
Or see if there is a mention of documentation and support directly in the theme.

**Comment by TableDesigns** [comment] 2021-02-15 18:22
No I am sorry but it is most definitely the block editor and here is an example

On the page I’ve been using as an example – this is code generated from the visual editor
You will see the many many <p></p> paragraphs it inserts – unnecessary and causing way too much space – it does NOT display though on the “visual editor” side where you can DO anything with it

<p></p>
<div class="wp-block-columns">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-column">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-group">
<div class="wp-block-group__inner-container">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-image mb-0 mt-0">
<figure class="aligncenter size-large"><a href="https://veneers.com/wood-veneers/" target="_blank" rel="noreferrer noopener"><img class="wp-image-12652" src="https://tabledesigns.com/wp-content/uploads/2020/04/logo-brookside-veneers.jpg" alt="Brookside Veneers" /></a></figure>
</div>
<p></p>
</div>
</div>
<p></p>
<p></p>
<p> </p>
<p></p>
</div>
<p></p>
<p></p>
<div class="wp-block-column">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-group">
<div class="wp-block-group__inner-container">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-image">
<figure class="aligncenter size-large"><a href="http://www.veneertech.com/species" target="_blank" rel="noreferrer noopener"><img class="wp-image-9584" src="https://tabledesigns.com/wp-content/uploads/2019/12/veneer-tech.jpg" alt="Veneer Tech" /></a></figure>
</div>
<p></p>
</div>
</div>
<p></p>
</div>
<p></p>
<p></p>
<div class="wp-block-column">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-group">
<div class="wp-block-group__inner-container">
<p> </p>
<p> </p>
<p> </p>
<div class="wp-block-image">
<figure class="aligncenter size-large"><a href="https://www.materials-inc.com/products/?term_id=682" target="_blank" rel="noreferrer noopener"><img class="wp-image-9585" src="https://tabledesigns.com/wp-content/uploads/2019/12/materials-inc-logo.jpg" alt="Materials Inc" /></a></figure>
</div>
<p></p>
</div>
</div>

**Comment by talldan** [comment] 2021-02-16 01:51
> You will see the many many <p></p> paragraphs it inserts – unnecessary and causing way too much space – it does NOT display though on the “visual editor” side where you can DO anything with it

@TableDesigns It may be partly the theme causing paragraphs to have styling that results in them having zero height. I also notice you're using the classic block, which may make it harder to identify them. Empty paragraph blocks in the editor usually look like this and can be deleted using the delete key:
<img width="628" alt="Screenshot 2021-02-16 at 9 50 01 am" src="https://user-images.githubusercontent.com/677833/108008913-6cc30180-703c-11eb-9c73-150340e9c6cb.png">

**Comment by TableDesigns** [comment] 2021-02-16 13:48
Yes I have I can delete them and then in doing so, have the “row” with “columns” below them get distorted and come undone -

starting fresh with a page and using it, all goes well – it isn’t until you go back and have to edit one small thing that the ‘visuals’ of the editor aren’t visual anymore – and honestly, theme aside since it is supposed to work with “Wordpress” one doesn’t expect to have these issues.

Storefront is Woocommerce’s main theme – it isn’t like it is some theme from out in the stratosphere?
I’ve had to opt out of using it for now and working around it to be frank.

It’s more aggravation than it’s worth.

**Comment by talldan** [comment] 2021-02-25 03:15
Seems like the issues are related to the theme? That's not something that can be solved here, it'd need to be addressed by Woocommerce.

I'll close the issue as I can't see anything that needs to be addressed here.

**Closed by talldan** 2021-02-25 03:15 UTC

**Comment by bcr8tive** [comment] 2021-02-25 14:03
Talidan, it WAS the plugin. SInce the last 2 updates the problems have lessened. But thank you.
