### ISSUE TITLE
Gutenberg block lost color icon, and edit show yellow color upon it (mark), saving replace valeur with mark tag & remove style. 

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#35702] opened 2021-10-16 08:34 UTC
### Description

Hi,

In wordpress.com blog,
Gutenberg block lost color icon,

<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_Git-Hub_Issues_shared-pictures_-_img/master/VorzPremsh/issues/bug/2021-10-16_-_10H23_-_color_style_remove_to_replace_with_mark_tag_03.PNG">

and edit show yellow color upon it (mark),
saving replace value with mark tag & remove precedent style.

<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_Git-Hub_Issues_shared-pictures_-_img/master/VorzPremsh/issues/bug/2021-10-16_-_10H23_-_color_style_remove_to_replace_with_mark_tag_01.PNG">

<img src="https://raw.githubusercontent.com/Nemzag/2020-05-05_-_Git-Hub_Issues_shared-pictures_-_img/master/VorzPremsh/issues/bug/2021-10-16_-_10H23_-_color_style_remove_to_replace_with_mark_tag_02.PNG">

Also since one month entity are not shown in title, and disappear when saving, but are shown in result (article, page).
Edit is difficult with this kind of bugs.

- <a href="https://www.youtube.com/embed/Et_s-zkpZgE" target="_blank" title="" alt="">https://www.youtube.com/embed/Et_s-zkpZgE</a>

I dô‑n’t have much time to report about this & add details. Sorry.

### Step-by-step reproduction instructions

1. Create or edit article / Page.
2. All previous color add‑ed with icon, are shown with yellow <mark>.
3. Save all previous values are lost (big problem).

### Environment info

- Windows 10
- Chrome & FireFox same trouble.
- WordPress.Com not .Org

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment] 2022-09-06 14:32
Hi @Nemzag, this issue came up in today's Editor Bug Scrub. We are a bit unclear about what the issue is. Are you referring to a bug related to the change in the way you can highlight the text and background: https://github.com/WordPress/gutenberg/pull/34680? Any more information you can provide would be greatly appreciated.

**Comment by kathrynwp** [comment] 2022-09-22 16:11
Hi @Nemzag,

> WordPress.Com not .Org

If this is an issue only on WordPress.com and not with a self-hosted install, I'd suggest getting in touch with WordPress.com, so their support team can report the issue as needed. You can do that here while logged into your account:

https://wordpress.com/help/contact

I'm going to go ahead and close this out.

**Closed by kathrynwp** 2022-09-22 16:11 UTC
Labels: [Status] Needs More Info, Needs Testing
