### ISSUE TITLE
Word flow in columns

### ISSUE THREAD

**Issue by hartsook** [WordPress/gutenberg#29184] opened 2021-02-20 22:02 UTC
## What problem does this address?
In a post with 2 columns for example a news story with many paragraphs of text it's easier to read if you use 2 columns so the lines of text are shorter. Currently you have to make 2 columns and add the paragraphs to the left column then decide where to stop and begin adding paragraphs to the right column.

## What is your proposed solution?
It would make it much easier for the content creator/writer to just write a series of paragraphs and tell gutenberg to display these as 2 columns instead of one and WordPress could figure out where to break the text so the column lengths were pretty much equal.

In addition you might want to add a page break so the 2 column display with continuing text would continue on the next page. You could have a setting where you could specify the column length so the page break would be inserted automatically.

**Comment by Sandstromer** [comment] 2021-02-22 11:19
I believe this should be left to a theme to define a block style to accomplish this.

e.g.
```
register_block_style(
  'core/group',
  array(
    'name'  => 'text-columns',
    'label' => __( 'Text Columns', 'themename' )
  )
);
```

and in stylesheet something like this:
```
.is-style-text-columns {
  columns: 3 200px;
}
```

Would give you this:
![text-columns-group](https://user-images.githubusercontent.com/76742815/108701378-c70e0780-74ff-11eb-9c4f-65b7323a809b.png)

**Comment by mtias** [comment] 2021-07-14 11:30
Closing as duplicate of #29184. We might end up adding a text flow tool across blocks to accomplish text columns.

**Closed by mtias** 2021-07-14 11:30 UTC
Labels: [Block] Columns, [Type] Enhancement

**Comment by Mamaduka** [comment] 2021-07-14 11:38
Hi, @mtias

I think you referenced this issue in a comment instead of the original one.

**Comment by mtias** [comment] 2021-07-14 12:08
Ah, thanks, I meant to reference #25459 for this design setting.
