### ISSUE TITLE
do not open image from post when I click on it

### ISSUE THREAD

**Issue by RafalSzrajnert** [WordPress/gutenberg#28750] opened 2021-02-04 17:59 UTC
## Description

long version on wp forum: [https://wordpress.org/support/topic/do-not-open-image-from-post-when-i-click-on-it/](https://wordpress.org/support/topic/do-not-open-image-from-post-when-i-click-on-it/),

but here I try to make it short.
after update to 5.6 in december I have automatic hyperlink added to my posts when I choose "image"
youtube short vid from my phone, you can see there is already link: https://youtu.be/rrehRidHd3Q

example of blog post: [https://uniqueseo.pl/co-to-jest-blog/](https://uniqueseo.pl/co-to-jest-blog/)

It is adding hyperlink only to new posts, did not applied it to older ones

and hyperlink is added only in "image"

when I add for example "media and text" there is no link automatically added, which is correct behaviour, because using "image" I have to delete every link, and I use photos a lot
## Step-by-step reproduction instructions

I have been advised to try old editor and when I delete link it remembers last action, which is correct and next photos have no "a href" after upload,

but when I swith back to new editor lik is added everytime

so i switched my theme to default WP theme, and switched off all plugins but...

it did not help!

what helped was when I  downloaded this plugin https://pl.wordpress.org/plugins/wp-downgrade/ and went back to 5.5.3 version and problem dissapeared!

## Expected behaviour

no automatically inserted hyperlink when i add "image"
## Actual behaviour

adding hyperlink to image every time, then I have to delete it on every photo i use in blog post
## Screenshots or screen recording (optional)

I already pastet this youtube from phone https://youtu.be/rrehRidHd3Q no need for better quality I think, just to show that is is added automatically
## WordPress information
- WordPress version:  bad behaviour: 5.6 and 5.6.1, good behaviour after downgrade to 5.5.3
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? yes, when I was troubleshooting. Normally betheme by muffingroup

## Device information
- Device: 
- Operating system:  windows 10
- Browser:  new firefox

last thing, 
maybe I just pasted long time ago some code to my wordpress php or something that now is affecting this? but I doubt. I know other people do not have this problem but as I said I switched all plugins and theme and problem still persisted. If you will need some code from me or access just let me know.

and suggestion from WP moderator:
_But it may not get much traction if the issue cannot be reproduced by others. It might make more sense to frame it as an enhancement where whatever option was used last is the default behavior._

**Comment by paaljoachim** [comment] 2021-02-04 19:02
Hi @RafalSzrajnert 

I am testing. 
Using a local site running the theme: Twenty Twenty One.  
WordPress: 5.6.1
Gutenberg plugin 9.8.4 and no other plugins activated. I also deactivated the Gutenberg plugin and had no plugins activated.
Testing in Chrome.

1. Creating a new post.
2. Adding the Image block.
3. Adding an image from the Media Library.
4. Clicked the link icon.
5. I could not see any included link.

See the above test instructions I wrote. It would be great if you can do something similar.
Deactivate all plugins except Gutenberg. Switch to a default theme such as Twenty Twenty One.
Then see if the link is still present after adding an image.

**Comment by RafalSzrajnert** [comment] 2021-02-04 19:29
@paaljoachim I did it yesterday with 5.6
now I am on 5.6.1 and problem persist.
But tomorrow I try as you said with 5.6.1 and I will let you know

**Comment by RafalSzrajnert** [comment] 2021-02-05 08:57
@paaljoachim 
nothing has changed:
https://youtu.be/uY4AVHpOfdY
all plugins switched off, only gutenberg left
plus default theme 2021

**Comment by paaljoachim** [comment] 2021-03-18 20:31
Thank you for sharing @RafalSzrajnert 
I am still not able to reproduce.
Kerry @gwwar could you take a look?

**Comment by gwwar** [comment] 2021-03-22 19:03
I'm afraid I can't reproduce this one on 5.6.1 WP (with the gutenberg plugin disabled) or in more recent versions.
<img width="890" alt="Screen Shot 2021-03-22 at 12 03 01 PM" src="https://user-images.githubusercontent.com/1270189/112044087-9fae5880-8b06-11eb-8d42-fbeb5753884a.png">

**Comment by annezazu** [comment] 2021-05-19 00:50
With two people unable to reproduce this and no further reports, I'm going to go ahead and close this out! @RafalSzrajnert if you can provide additional steps or information, those of us interacting on this issue can re-open and try once more to replicate. Thanks so much.

**Closed by annezazu** 2021-05-19 00:50 UTC
Labels: Needs Testing, [Block] Image
