### ISSUE TITLE
Embed Block: How to select the block without starting video

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#483] opened 2017-04-24 07:34 UTC
The Embed block (#316) appears to work well up until a video is actually embedded, at which point it looks as though clicking the block will start it playing. Even though that won't be the case (we should port the click interceptor that's in WordPress now), the UI observation still stands. 

What's a good approach to make this interface less obtuse, so we don't frighten users from clicking the block? Let's discuss. Some ideas:

- Abstract live preview for the block —  don't show 1:1 what it will look like, perhaps include a generic border with meta information
- Add a clickable UI fixture permanently docked near the embed
- Add a clickable UI fixture that shows up on hover

**Comment by notnownikki** [comment] 2017-04-24 09:08
@iseulde brought up an excellent point about fixtures that show up on hover - how do we handle that on mobile? This is especially important as it's on mobile that users are least likely to click a video because they expect youtube apps to pop up and to be charged for data used playing the video.

My preference would be for the abstract preview, perhaps with an option to toggle and see the "live" content? (but I'm not a designer, just a pretty good new-user-simulator :smile: )

**Comment by jasmussen** [comment] 2017-04-24 09:17
> My preference would be for the abstract preview, perhaps with an option to toggle and see the "live" content? (but I'm not a designer, just a pretty good new-user-simulator 😄 )

I lean towards this as well. It's a stellar argument for why abstract live preview has benefits, over 1:1 100% live preview.

**Comment by iseulde** [comment] 2017-04-24 13:43
What would an "abstract preview" look like? How to make it?

**Comment by jasmussen** [comment] 2017-04-24 14:39
By "abstract live preview" I mean a block design that clearly indicates that this is a video that's embedded, and it suggests what the end result will look like, without being a 100% 1:1 preview. 

Take the `[gallery]` block in the current editor, that's an abstract preview. It's arguably _too_ abstract, but it's the same vein as what I mean.

**Comment by rileybrook** [comment] 2017-04-26 02:44
I may be misunderstanding the description of the problem but I think your second idea would be best @jasmussen:
> Add a clickable UI fixture permanently docked near the embed

![screen-shot-2016-08-26-at-5 18 21-pm](https://cloud.githubusercontent.com/assets/7691812/25415893/f20a35d2-29f7-11e7-97ff-42e0919c3764.png)

![mincp](https://cloud.githubusercontent.com/assets/7691812/25415898/f5a0d9a8-29f7-11e7-9af3-5d070bf6e430.png)

For mobile users who won't have hovering available to them - A large play button that could be fixed centred, and shown without hovering. A large play button would indicate it is a video that can be clicked to begin playing, or scrolled past.

**Comment by rileybrook** [comment] 2017-04-26 03:12
If I understand @jasmussen correctly:
> a block design that clearly indicates that this is a video that's embedded, and it suggests what the end result will look like, without being a 100% 1:1 preview.

A solution could be something like the following: 
![embed](https://cloud.githubusercontent.com/assets/7691812/25416585/cc041fb6-29fb-11e7-8563-bd8d639e4e73.png)
Another alternative could be something like:
![embed 1](https://cloud.githubusercontent.com/assets/7691812/25416592/cfdb1464-29fb-11e7-8f3d-f5f2c9699c91.png)

A UI element that appears with or without hovering - for mobile users it indicates itself as a block that can be moved around without worry of playing the video. Just brainstorming ideas, please let me know if I am off-base here, as I could be misunderstanding the problem.

**Comment by jasmussen** [comment] 2017-04-26 08:04
That's solid work @rileybrook, and aside from a few stylistic tweaks, pretty much exactly what I meant. 

Inspired by Riley I took it a step further:

![embed](https://cloud.githubusercontent.com/assets/1204802/25424170/ada6b71a-2a67-11e7-8258-87654290ecc4.png)

**Comment by notnownikki** [comment] 2017-04-26 08:44
Wow, fading out the video and showing the caption placeholder changes the feel of it completely! There's no doubt that I'm in editing mode there.

:+1: from me!

**Comment by mtias** [comment] 2018-02-06 15:45
@jasmussen do we still want to do this?

**Comment by jasmussen** [comment] 2018-02-06 15:50
> do we still want to do this?

This is not a feature that has to be part of the shipping version, but it's definitely something that would enhance the experience. I struggle with selecting embedded videos every time.

**Comment by aduth** [comment] 2018-02-27 20:38
This is also related to selection of embeds generally, not just videos. Notably, selecting any embed block (say, a Twitter block) recently regressed to not being possible in #4872 (previously fixed in #4011).

The idea of showing an overlay could work just as well for non-video in helping to make the blocks selectable. Open questions are:

- Would it have the same background color?
- Would it include the label for embed type? (Twitter is "rich")

Alternatively, we can restore the intended behaviors of #4011, but this would require reintroducing a prop for blocks to programmatically call to select themselves (e.g. `setSelected`).

**Comment by notnownikki** [comment] 2018-02-27 20:51
> Would it include the label for embed type? (Twitter is "rich")

I'd say it should be the name of the block instead of the type. There are cases where oembed is overridden and we don't get type information at all, so how we handle type information in the embed blocks is going to change at some point (I'm working on this now). To make this properly useful, we'd need to switch to the right block based on the URL, and I'm working on that too.

**Comment by aduth** [comment] 2018-04-13 18:02
Embed blocks can now be easily selected again as of #5730.

**Comment by karmatosed** [comment] 2018-05-19 21:13
The embed block seems to now work without the video playing. I just tested this using a YouTube video. I am closing, if this is not fixed we can always reopen.

**Comment by jasmussen** [comment] 2018-12-20 08:17
Reopening this issue as the problem is present again, and being worked on in #12981. This ticket has a lot of discussion, including mockups, so it's worth resurfacing these to keep things collected.

**Comment by youknowriad** [comment] 2019-02-11 12:05
closed by #12981

**Closed by youknowriad** 2019-02-11 12:05 UTC
Labels: Blocks, Needs Design Feedback, Priority Low, Regression
