### ISSUE TITLE
Unescaped HTML inside shortcode attributes breaks block validation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#13399] opened 2019-01-21 11:58 UTC
Note, this is a direct port of a ticket filed on Trac and which can be found here: https://core.trac.wordpress.org/ticket/45684

(edited by mcsf to use the term "quotes" throughout)

> When inserting shortcode containing both single and double quotes (like so: [plugin query="a='b' c=1"] ) using a Shortcode Block, Gutenberg will show a warning next time you load the page, saying that the Block contains unexpected or incorrect code. You can choose to "restore" the code by converting it to a Block (whatever that means in this context), completely wrecking your code, or you can convert it to Custom HTML in which case the single quotes will be converted to double quotes, breaking the HTML. This also happens when you insert the code into the page using Custom HTML right away. Either way, the shortdcode will not work properly and there's no way around it, using vanilla WP 5.0.

> The only solution I have found, is to install the Classic Editor Plug-In and then switch to Text View. That basically rules out the possibility of any of my editors being able to make and maintain pages containing such shortcodes, which is extremely not cool. (I'm classifying this as a Bug of Critical Severity, since it effectively breaks an essential plug-in of my site.)

> When saving the above code as a Reusable Block (I'm using WP with a Dutch translation so the exact term may differ), you get to see the resulting HTML. Everything between the single quotes is replaced by a single line-break. Ouch.

**Comment by mcsf** [comment] 2019-01-21 12:12
I can't reproduce this. Is there a specific series of steps we could have to better test?

**Comment by mcsf** [comment] 2019-01-22 17:32
Thanks for the report, @chunkyRice. From your account and what I then reproduced, this seems unrelated to quotes, but related to how escaped and unescaped HTML entities are handled.

This also affects the classic editor. For instance:

![classic-text-to-visual](https://user-images.githubusercontent.com/150562/51552625-e772c000-1e68-11e9-9153-6eaf6a48c56e.gif)

This is because any rich-text editor (including classic) will be looking for HTML elements in post content. Inside the shortcode there is such an element (`<div class="xi-item">…</div>`), which interferes with the rest of content. In order for the shortcode attributes to be ignored by the editor, the HTML entities would have to be escaped, meaning we would have:

```
[xilipostinpost query="tag=dossier" beforeeach="&lt;div class='xi-item'&gt;" aftereach="&lt;/div&gt;"]
```

Incidentally, the above snippet is exactly what we obtain if we paste the shortcode *when in Visual mode instead of Text* mode:

![classic-visual-to-text](https://user-images.githubusercontent.com/150562/51552976-b5ae2900-1e69-11e9-8fcc-c120a8ab9db4.gif)

When this is the case, Gutenberg has no problem parsing the content and helping with the conversion:

![classic-to-shortcode](https://user-images.githubusercontent.com/150562/51553121-0160d280-1e6a-11e9-9df6-9749c740d4db.gif)

* * *

Note: I understand that the shortcode in question, `xilipostinpost`, may not even support attributes whose HTML has been escaped. (If that's the case, I would bring up this issue with the plugin maintainer.) However I would personally argue that shortcodes shouldn't operate on unescaped HTML. At the very least, it's a grey area.

There may be room for improvement somewhere in Gutenberg to make situations like these easier on users, but I'm not sure which.

**Comment by iseulde** [comment] 2019-01-29 15:05
@mcsf How does this relate to the RichTex component?

**Comment by mcsf** [comment] 2019-01-29 15:09
@iseulde: Not very specifically, this is more about the serialisation layer. Fine to remove whatever labels you like.

@chunkyRice, does the explanation in this issue help you in any way? Is there a course of action you see for yourself or for core Gutenberg? Otherwise, I'm inclined to say there are no action items for Gutenberg and that we can close this issue. Let me know! Thanks.

**Comment by chunkyRice** [comment] 2019-01-30 12:09
I've tested what @mcsf suggested, but it only works a single time. When you save the page and reopen it, everything is a mess again. 

I expected the snippet block to handle raw ascii text, but apparently that's not the case. Doing so would solve this problem, but from your answers I understand that it would also be a potential safety hazard.

I've submitted the problem to the support forum of the plugin.

**Comment by mcsf** [comment] 2019-01-30 18:36
> When you save the page and reopen it, everything is a mess again.

Yeah, never mind what I said. The block-validation process runs the serialised HTML through the block parser, where attributes are parsed according to their type:

https://github.com/WordPress/gutenberg/blob/f2c5db6c8202a7cab09384c1d2b691882d977ae0/packages/blocks/src/api/parser.js#L181-L217

The block type for Shortcode defines that the `text` attribute is of source `'text'`. This makes the parser parse the attribute via [hpq's `text()`](https://github.com/aduth/hpq/blob/d9b5a480cd56866a2af196c9a8e0ccfc91431e56/src/index.js#L122-L132), which ultimately uses [Node#textContent](
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) instead of [Element#innerHTML](
https://developer.mozilla.org/en-US/docs/Web/API/element/innerHTML) to return the parsed shortcode. This is where `&lt;` becomes `<`.

The discrepancy between the serialised escaped HTML (`&lt;`) form and the "expected" unescaped forms (`<`) is what makes the block invalid upon editor initialisation.

Changing Shortcode's `text` attribute to be of source `'html'` does solve your particular case. But I can't speak to any kind of instability that that would bring. @aduth, do you have any insight there? The Code block is the only other core block using `source: 'text'`, since it also deals with plain-text content.

**Comment by aduth** [comment] 2019-01-30 19:11
To me, particularly because it saves using `RawHTML`, there's no reason the shortcode block shouldn't also define its attribute as being sourced via `'html`'. I expect the original implementation didn't expect HTML to be embedded within a shortcode, so it defaulted to text.

It's worth pointing out that regardless of whether the source is changed, the default WordPress [`unfiltered_html` capability](https://codex.wordpress.org/Roles_and_Capabilities#unfiltered_html) will apply when the post is saved; i.e. the text will be escaped anyways server-side for any user who is not an administrator.

**Comment by mcsf** [comment] 2019-01-30 23:14
Thanks for the input. Opened #13609.

**Closed** 2019-02-14 20:53 UTC
Labels: [Component] Raw Handling, [Type] Plugin / Theme Interoperability
