### ISSUE TITLE
Change the precommit script to detect the mutation of const variable

### ISSUE THREAD

**Issue by Jackie6** [WordPress/gutenberg#14498] opened 2019-03-18 15:39 UTC
**Is your feature request related to a problem? Please describe.**

Every time we commit our code, there is a precommit script that will be run automatically to check whether your code has some problems like missing trailing space or comma. But for the following code:
```Javascript
const newBlockAttributes = attributes;
newBlockAttributes.content = after;
```
The precommit script will not find any problems. However, I think Ideally we don't mutate the attributes object of the current object.
A better way would be 
```Javascript
const newBlockAttributes = {
   ...attributes,
   content: after
};
```

**Describe the solution you'd like**
Is this possible to change `wp-scripts lint-js` to prevent this?

**Comment by swissspidy** [comment] 2019-03-18 18:26
Sounds like the [`no-param-reassign`](https://eslint.org/docs/rules/no-param-reassign#disallow-reassignment-of-function-parameters-no-param-reassign) ESLint rule.

You could totally add this to your custom ESLint config for the time being.

**Comment by sainthkh** [comment] 2020-04-02 03:13
@gziolo @swissspidy 

There's an eslint plugin that does this. ([link](https://www.npmjs.com/package/eslint-plugin-const-immutable))

I applied it to Gutenberg and found there were 538 errors. But the problem is that they don't improve the readability of code or prevent hard-to-find bugs. 

For example:

### 1. They're necessary because it sets values.

```
// a11y/src/index.js
const containerAssertive = document.getElementById(
	'a11y-speak-assertive'
);
const containerPolite = document.getElementById( 'a11y-speak-polite' );

if ( containerAssertive && ariaLive === 'assertive' ) {
	containerAssertive.textContent = message;
} else if ( containerPolite ) {
	containerPolite.textContent = message;
}
```

We're setting the text content of an element by assigning value to `containerAssertive.textContent = message;`. There is no alternative. 

### 2. An object is used as a record and the contents can be changed.

```js
// annotations/src/format/annotation.js
const positions = {};

formats.forEach( ( characterFormats, i ) => {
	if ( ! positions.hasOwnProperty( id ) ) {
		positions[ id ] = {
			start: i,
		};
	}
} );
```

`positions` are used as a record. `positions[id]` is inserting new value to that record. It's necessary.

### 3. It's against usual JavaScript convention

The code below is error with 

```js
// block-library/src/cover/deprecated.js
const style =
	backgroundType === IMAGE_BACKGROUND_TYPE
		? backgroundImageStyles( url )
		: {};
if ( ! overlayColorClass ) {
	style.backgroundColor = customOverlayColor;
}
if ( focalPoint && ! hasParallax ) {
	style.backgroundPosition = `${ Math.round(
		focalPoint.x * 100
	) }% ${ Math.round( focalPoint.y * 100 ) }%`;
}
if ( customGradient && ! url ) {
	style.background = customGradient;
}
style.minHeight = minHeight || undefined;
```

It can be re-written like below:

```js
let style =
	backgroundType === IMAGE_BACKGROUND_TYPE
		? backgroundImageStyles( url )
		: {};
if ( ! overlayColorClass ) {
	style = {
		...style,
		backgroundColor: customOverlayColor,
	}
}
if ( focalPoint && ! hasParallax ) {
	style = {
		...style,
		backgroundPosition: `${ Math.round(
			focalPoint.x * 100
		) }% ${ Math.round( focalPoint.y * 100 ) }%`,
	}
}
if ( customGradient && ! url ) {
	style = {
		...style,
		background: customGradient,
	}
}

style = {
	...style,
	minHeight: minHeight || undefined,
}
```

But as you can see, it just makes code longer and harder to read. 

I believe we can close this issue without any changes.

**Comment by swissspidy** [comment] 2020-04-02 08:36
Makes sense to me!

**Comment by gziolo** [comment] 2020-04-02 15:39
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const:

> The `**const` declaration** creates a read-only reference to a value. It does **not** mean the value it holds is **immutable**—just that the variable identifier cannot be reassigned. For instance, in the case where the content is an object, this means the object's contents (e.g., its properties) can be altered.

It looks we are good. Let’s close it 👍

**Closed** 2020-04-02 15:39 UTC
Labels: Good First Issue, Needs Dev, [Package] ESLint plugin
