### ISSUE TITLE
Removal of "Write your story" placeholder

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#11492] opened 2018-11-05 14:16 UTC
**Is your feature request related to a problem? Please describe.**
This is a suggestion, not a problem. The placeholder "write your story" seems to create inconsistency because it changes to another placeholder "add text or type / to add content" after clicking the text area / paragraph block. The font family seems to be different as well (although it depends on the theme and can be changed in the css but its an extra step) It doesn't look visually appealing in multiple InnerBlocks like the columns block. Please see attached screenshot. It also seems a little misguiding because the first thing people may want to do is add a block / build a layout, not write a story.

**Describe the solution you'd like**
Maybe using a single placeholder for paragraph / default blocks like "add text or type / to add content" will be better. Or having an option to choose a placeholder based on the post type. It feels odd having a placeholder change to another placeholder.

![screen shot 2018-11-05 at 4 09 37 pm](https://user-images.githubusercontent.com/3076742/48003047-fd989c00-e115-11e8-8e90-25bbc92e4db6.png)

**Comment by GlennMartin1** [comment] 2018-11-05 14:37
duplicate of https://github.com/WordPress/gutenberg/issues/9076

**Closed** 2018-11-05 14:40 UTC
