### ISSUE TITLE
Classic Block leaves us stranded in HTML view

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#22653] opened 2020-05-27 02:25 UTC
**Describe the bug**
When editing a Classic Block visually, I've encountered a situation where the floating ellipsis menu, after switching to HTML view, disappears and strands the creator in the HTML editor mode with no way back to visual editing.

**To reproduce**
Steps:
1. Create a new Classic Block
2. Add enough text to allow wrapping around an image
3. Insert an image from Media Library
4. Resize the image and set the image wrapping to left (image on left, text on right)
5. Click the block's floating ellipsis menu and and select 'Edit as HTML'
6. Note that at this point, the ellipsis menu is still visible.
7. Click into the HTML editor so the cursor is flashing
8. The Ellipsis menu now disappears. At this point, there's no way to get that menu back, leaving you stranded in this view mode for this block.

Note: Steps 3 and 4 may not be strictly necessary, but having content in the block may be helpful.

**Expected behavior**
The floating ellipsis menu should always remain visible no matter what mode you're in.

**Screenshots**
Screenshots can't adequately illustrate this.

**Editor version (please complete the following information):**
- WordPress version: Ask Wordpress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Ask Wordpress.com
- If the Gutenberg plugin is installed, which version is it? Ask Wordpress.com

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser Firefox
 - Version 76.0.1

**Additional context**
Once you click into the editor, the ellipsis menu disappears entirely. Clicking out of the block and back into it doesn't return the menu. Changing the article view mode from visual to code and back doesn't fix this. The undo button doesn't affect navigation, so this doesn't work. The only way to get the menu back is to quit entirely out of the editor back to the Posts page, then re-enter the editor for that article, reloading the entire article. At this point, the Classic Block will be placed back into visual editing mode. This problem happens each time you attempt to edit a Classic Block in the HTML editor.

As a side note, I'm not a big fan of the floating menu. In fact, I believe this one aspect of Gutenberg needs an overhaul. Instead, of using a floating block menu, this menu should be a static visual element that remains attached to the top of the block itself at all times when block editing is active. It is disconcerting to have this thing floating around all over the screen. In fact, I believe blocks should have a border around the entire block while they are being edited. Having no border around the block makes it difficult to know where one block ends and the next begins. The block's border can disappear when deselected. This menu should also have a different color (light grey or another color) to differentiate it from the white of the background.

**Comment by jasmussen** [comment] 2020-05-28 07:14
Thank you for the excellent report. Through your descriptive steps, I was able to reproduce this:

> The floating ellipsis menu should always remain visible no matter what mode you're in.

I recorded this GIF:

![classic](https://user-images.githubusercontent.com/1204802/83110249-10d9d680-a0c3-11ea-880b-132743079fc0.gif)

I believe the issue you describe here is the same as is described in #21722, @talldan I saw you commenting on that, do you agree?

Definitely frustrating, and something we need to fix. 

> As a side note, I'm not a big fan of the floating menu. In fact, I believe this one aspect of Gutenberg needs an overhaul. Instead, of using a floating block menu, this menu should be a static visual element that remains attached to the top of the block itself at all times when block editing is active.

We have found that a large number of users strongly prefer this permanently docked toolbar, and an equally and slightly larger number of users prefer the direct context the floating toolbar gives. Because of that, the block editor supports both. Here's how you enable the docked-to-the-top toolbar:

![top toolbar](https://user-images.githubusercontent.com/1204802/83110598-9a89a400-a0c3-11ea-8f9b-deb6bd6deda4.gif)

Thanks again for the ticket, hope this helps!

**Comment by talldan** [comment] 2020-05-28 09:28
@jasmussen Yep, definitely looks like the same issue as #21722, I'll close this as a duplicate.

Thanks for the excellent bug report!

**Closed by talldan** 2020-05-28 09:28 UTC

**Comment by commorancy** [comment] 2020-06-08 23:04
> Thanks again for the ticket, hope this helps!

Just as an FYI, the 'Top Toolbar' doesn't work on Wordpress.com. When I select 'Top Toolbar', the floating menu disappears, but nothing appears as part of the block. I'm guessing I'll need to create a new bug report.
