### ISSUE TITLE
Global Styles: Custom color palettes with non-Latin character labels do not work

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#49740] opened 2023-04-12 02:48 UTC
### Description

If I use a non-Latin language for the labels of custom color palette, I encountered the following two problems:

- Exactly the same CSS variables are generated
- When exporting a theme, the color palette is missing

![custom-color](https://user-images.githubusercontent.com/54422211/231333741-c2cad1d6-a43c-438b-82ca-b3bfcc65c806.png)

### Step-by-step reproduction instructions

- In the Site Editor, open the template.
- Move to "Styles" > "Colors" > "Pa;ette".
- Define two palettes with labels `メイン` and `サブ` (This is Japanese.).

If you open the developer tools in your browser, you will see that the same CSS variables have been generated:

![user-color-jp](https://user-images.githubusercontent.com/54422211/231334512-58e1ac85-238a-4029-964f-7b64cdde2b67.png)

If the label is in English, the CSS variable is output correctly:

![user-color-en](https://user-images.githubusercontent.com/54422211/231334646-826a68b3-8768-437e-b22b-afdf463f4c17.png)

When the theme is exported, there is only one custom color palette and the slugs are incorrect:

![theme-json-ja](https://user-images.githubusercontent.com/54422211/231334883-2f4e0616-b356-4fb3-bd7f-c83b7fd2277c.png)

If the label is in English, all color palettes are generated correctly:

![theme-json-en](https://user-images.githubusercontent.com/54422211/231334979-31dbaacd-efdf-4aae-bdf5-f685aa313ac8.png)

### Environment info

WordPress Version: WordPress 6.2
Gutenberg Version: 15.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-05-28 06:52
May be related to #39210.

**Comment by ellatrix** [comment] 2023-08-17 11:15
Yes, I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/39210?

**Closed as not planned** 2023-08-17 14:02 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Themes, Global Styles, [Feature] Colors
