### ISSUE TITLE
New Lightbox (expand on click) does not work in WordPress 6.4 Beta 1

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#54869] opened 2023-09-27 13:35 UTC
### Description

No Lightbox at all
Maybe (?) in conjunction with the usual layout error of Beta version, seen in navigation:
![image](https://github.com/WordPress/gutenberg/assets/32030147/69a8a16d-ffca-4b92-a689-784cd882049b)

### Step-by-step reproduction instructions

1. Make a fresh WordPress installation.
2. set "sample page" as Homepage
3. Install Beta Plugin
4. select Bleeding Edge version
5. update wordpress
6. insert an image
7. select "expand on click"
8. view page
9. see image and try to click => ?

### Screenshots, screen recording, code snippet

Regular page without Lightbox:
![image](https://github.com/WordPress/gutenberg/assets/32030147/9e2bb892-1962-4970-a701-e72cad4a9c4d)

Page with "expand on click":
![image](https://github.com/WordPress/gutenberg/assets/32030147/42d1f558-54a0-4240-9a21-5319599abb86)

Click on grey area opens image at the bottom of the page:
![image](https://github.com/WordPress/gutenberg/assets/32030147/0f40e221-e178-44a3-8c97-46fae9a4ad61)

### Environment info

- WordPress: 6.4-beta1-56730
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: 8.1.23)
- Browser: Chrome 117.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.2
- MU-Plugins: Keine aktiviert
- Plugins:
  * WordPress Beta Tester 3.5.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment] 2023-09-27 21:20
Hey @burnuser - I'd seen that general layout error in testing 6.2 as well - does it (or the lightbox issue) go away when the Gutenberg plugin is installed and active?

**Comment by jordesign** [comment] 2023-09-27 21:22
In my testing of the beta - I'm getting the expand/lightbox operating as expected - so I wonder if there's something else at play here. We may need to narrow things down further.

**Comment by burnuser** [comment] 2023-09-28 05:28
@jordesign

1.) Test with Gutenberg to Beta added and activated:
a) general layoutbug is gone
b) lightbox works

Gutenberg deactivated (Beta alone):
both errors are back again

2.) Test with fresh environment: WP 6.3.1 + Gutenberg:
no layoutbug + lightbox works

Result: problem must be located in Beta

**Comment by michalczaplinski** [comment] 2023-09-28 16:42
cc: @artemiomorales

**Comment by artemiomorales** [comment] 2023-09-28 17:36
Has anyone else been able to reproduce this? I'm unable to replicate.

CC
@burnuser 
@michalczaplinski

**Comment by carolinan** [comment] 2023-09-29 04:09
While not a long-term solution, does it work if you set `define( 'SCRIPT_DEBUG', true );` in wp-config?

**Comment by burnuser** [comment] 2023-09-29 05:44
Test with local WP environments (which I - and many other people around the world - use for development and testing) - using http:
Laragon: https://laragon.org/
Local: https://localwp.com/
=> both show the described bugs

Test with 2 Online environments - using https:
InstaWP
TasteWP
=> no bug visible

**Comment by t-hamano** [comment] 2023-10-02 11:27
Considering that this problem occurs on a site built on a local Windows OS machine, does not occur on a site built using InstaWP, etc., and the screenshot posted in the issue, it is the same as the problem reported in #54849. Therefore, I would like to close this issue.

A description of the cause for this problem and a patch to resolve it can be found in this core ticket: https://core.trac.wordpress.org/ticket/59489

**Closed as not planned by t-hamano** 2023-10-02 11:27 UTC
Labels: [Type] Bug, [Type] Regression, [Status] Duplicate, OS Issues
