### ISSUE TITLE
Bug in "Convert to Blocks" and images

### ISSUE THREAD

**Issue by trevorjwood** [WordPress/gutenberg#13040] opened 2018-12-20 14:05 UTC
Convert to Blocks is not working properly for images with captions. The original HTML looks like this

`<figure id="attachment_91" style="width: 200px" class="wp-caption alignleft"><a href="http://the-woods.local/wp-content/uploads/Keithwedding.jpg"><img class="size-full wp-image-91" title="Keith and Tigi's wedding" src="http://the-woods.local/wp-content/uploads/Keithwedding.jpg" alt="Keith and Tigi's wedding" width="200" height="133" /></a><figcaption class="wp-caption-text">Keith and Tigi&#8217;s wedding</figcaption></figure>`

the converted HTML looks like this

`<div class="wp-block-image"><figure class="alignleft"><a href="http://the-woods.local/wp-content/uploads/Keithwedding.jpg"><img src="http://the-woods.local/wp-content/uploads/Keithwedding.jpg" alt="Keith and Tigi's wedding" class="wp-image-91"/></a><figcaption><a href="http://the-woods.local/wp-content/uploads/Keithwedding.jpg"><img class="size-full wp-image-91" title="Keith and Tigi's wedding" src="http://the-woods.local/wp-content/uploads/Keithwedding.jpg" alt="Keith and Tigi's wedding" width="200" height="133"></a> Keith and Tigi's wedding</figcaption></figure></div>`

All the code between the `<figure> and <figcaption>` tags has been duplicated as part of the caption

**Comment by tellthemachines** [comment] 2019-07-25 07:00
Hi there,

I can't reproduce the issue by pasting in the original HTML above and then converting to blocks. The HTML I get is the following:
`<div class="wp-block-image wp-caption alignleft"><figure class="alignleft"><a href="http://the-woods.local/wp-content/uploads/Keithwedding.jpg"><img src="http://the-woods.local/wp-content/uploads/Keithwedding.jpg" alt="Keith and Tigi's wedding" class="wp-image-91"></a><figcaption>Keith and Tigi’s wedding</figcaption></figure></div>`

I'm closing this issue for now, feel free to reopen it if you can still reproduce the issue with the lastest version of Gutenberg.

**Closed by tellthemachines** 2019-07-25 07:00 UTC
Labels: Block Conversion, Needs Testing, [Block] Image
