### ISSUE TITLE
"Copied to clipboard" (Ctrl-C) notifications blocking editor view; lower timeouts or limited amounts would be helpful.

### ISSUE THREAD

**Issue by oldrup** [WordPress/gutenberg#58519] opened 2024-01-31 19:00 UTC
## What problem does this address?

When I'm copying and pasting content from the block editor, it pops up with a notification that I pressed Ctrl-C. That's really not necessary, but harmless. Unless, you do a lot of copy/pasting, when translating content, maybe. The notifications stack and stay in view for so long, that at some point they block much of the editor view:

I'm not sure "notifications" is the right name, but look at the screenshot.

![image](https://github.com/WordPress/gutenberg/assets/17141205/a2eb9b9e-4049-473b-a7ae-dbf95ef152e6)

## What is your proposed solution?

Proposed solutions in no particular order:
- Add a filter that allows us to **disable notifications about copy and pasting.**
- Add a filter that allows us to **set the timeout for these notifications**
- **Just reduce the timeout for these notifications**, a few seconds should suffice imo
- **Limit the amount of concurrent notifications** to, say, 3, first in, first out.

**Comment by Mamaduka** [comment] 2024-02-01 07:27
Thanks for creating the issue, @oldrup!

I believe this is a duplicate of #53201.

**Closed as not planned by Mamaduka** 2024-02-01 07:27 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Package] Components

**Comment by oldrup** [comment] 2024-02-01 07:39
Ah! Yes. You are right, @Mamaduka -- "Snackbar" is a new term to me 🍫😁

**Comment by Mamaduka** [comment] 2024-02-01 07:45
Yeah, this design pattern has a lot of names, such as "Snackbar," "Toast," etc. I can understand the confusion :)

**Comment by oldrup** [comment] 2024-02-01 08:35
Well, I'm experiencing "pancakes" then, I suppose 😁 

![119674](https://github.com/WordPress/gutenberg/assets/17141205/de5db39c-f8e1-4a73-9104-d564be586db0)

Learned something new today. Thank you, Mamaduka. I'll let you get back to work 😊
