### ISSUE TITLE
FormTokenField: ADD NEW TAG is entered twice in Japanese

### ISSUE THREAD

**Issue by xs-hito** [WordPress/gutenberg#45599] opened 2022-11-08 10:27 UTC
### Description

In WordPress 6.1, when I type Japanese in ADD NEW TAG on the editor screen and press Enter, Japanese is typed twice.

In WordPress 6.0, Japanese is entered only once and works correctly.

When entering characters in Japanese language ( including Kanji), after entering "Hiragana", select which character to convert to and press Enter to confirm.

I would expect the same problem in other languages that perform the same operation.

### Step-by-step reproduction instructions

I expect users to use a Japanese keyboard.

1.On the editor screen. type `あああ` in the ADD NEW TAG input.

2.Confirm that a character is unintentionally typed twice when the enter key is pressed.

#### WordPress 6.1

・Type in Japanese and press Enter key unintentionally types the word twice.

![スクリーンショット 2022-11-08 190328](https://user-images.githubusercontent.com/102792171/200536704-9fb27c4b-5348-4a25-a358-0e0025467198.png)

#### WordPress 6.0

・Type in Japanese and press Enter Key for correct operation.

![スクリーンショット 2022-11-08 190620](https://user-images.githubusercontent.com/102792171/200536657-4aa8bb83-e192-489c-8edd-9ce50cd93ec7.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by xs-hito** [comment] 2022-11-08 10:37
I believe it is related to this issue. https://github.com/WordPress/gutenberg/issues/45496

**Comment by t-hamano** [comment] 2022-11-08 14:15
@ito-x 

Thank you for your contribution.

As you mentioned, I believe the cause of this issue is similar to #45496. I have submitted a tracking issue (#45605) as this problem is occurring in several other components as well.

**Comment by t-hamano** [comment] 2022-11-08 15:03
I believe this issue will be fixed by #45607.
I will also add it to the WP6.1 board as I think this is as big a bug as #45496.

**Closed as completed** 2022-11-12 03:47 UTC
Labels: [Type] Bug, [Package] Components
