### ISSUE TITLE
Reusable Blocks: Blocks should be resized in the editor when you make them reusable

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#22363] opened 2020-05-14 16:35 UTC
**Describe the bug**
When you make a reusable block in the editor, it goes from whatever width it is currently set to:

![image](https://user-images.githubusercontent.com/2846578/81960569-276e3100-95df-11ea-8826-4b6596cc5a49.png)

To display at the content width:

![image](https://user-images.githubusercontent.com/2846578/81960605-36ed7a00-95df-11ea-95d5-630cfe076415.png)

This is confusing. The block is still full-width, but the reusable wrapper is constraining it. It means your editor and front-end don't match.

**Expected behavior**
The block should remain the correct width.

**Comment by noisysocks** [comment] 2020-11-05 01:28
Dupe of https://github.com/WordPress/gutenberg/issues/8288.

**Closed by noisysocks** 2020-11-05 01:28 UTC
Labels: [Feature] Reusable Blocks, [Type] Bug
