### ISSUE TITLE
Overrides in Synced Patterns: Unable to preview newly defined overrides without saving

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#61978] opened 2024-05-25 09:47 UTC
### Description

Immediately after enabling the overrides option of synced pattern, if you preview without saving, the changes are not reflected.

This issue was found during the [Early opportunities to Test WordPress 6.6](https://make.wordpress.org/test/2024/05/09/early-opportunities-to-test-wordpress-6-6/).

### Step-by-step reproduction instructions

1. Create a pattern includes some Paragraphs.
2. Create a new page and add the newly created pattern.
3. Select the pattern and click 'Edit original' button.
4. Select a paragraph block in the pattern, and in the block settings sidebar expand the Advanced section. Check the ‘Enable overrides’ option and give the override a name.
5. Click 'Back' button in the header area of the editor to go back to the page.
6. Add the same pattern and change overrides paragraph.
7. Click 'Preview in the new tab'.
 => You wont't see the changes.

### Environment info

WordPress 6.5.3
Gutenberg 18.4.1
Twenty Twenty-Four
Google Chrome 124.0.6367.203
Desktop with Windows 10 22H2 19045.4412

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2024-05-27 03:20
Thanks for reporting the issue @atachibana .

I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/32864, so I'll close the issue.

The problem isn't related to overrides, any change made to a synced pattern won't be reflected in the preview unless you save the synced pattern first.

When the changes made to the synced pattern are unsaved, they only exist in memory. When you open another browser tab to preview, there's no way for that other tab to know about those unsaved changes.

A potential fix could be to prompt the user with a message like this before the preview is shown - "You have unsaved changes to patterns used in this post, do you want to save these changes? If the changes are not save they won't be shown in the preview."

**Closed as not planned by talldan** 2024-05-27 03:20 UTC
Labels: [Type] Bug, [Feature] Synced Patterns
