### ISSUE TITLE
Meta box can be dragged in the sidebar, but never back

### ISSUE THREAD

**Issue by tijmensmit** [WordPress/gutenberg#31739] opened 2021-05-12 07:43 UTC
I maintain the [WP Store Locator](https://wordpress.org/plugins/wp-store-locator/) plugin, and have had several users report that the 'Store Details' meta box is draggable in Gutenberg and can be moved into the sidebar. But once it’s there it can’t be dragged back. I raised this issue on the wp forum yesterday, and it was [suggested](https://wordpress.org/support/topic/prevent-main-content-block-from-being-draggable-into-sidebar/#post-14425576) to open a bug report for it.

This is what it [normally looks like](https://www.awesomescreenshot.com/image/8119647), and [this is](https://www.awesomescreenshot.com/image/8119646) the messy end result if they drag it into the sidebar.

The expected behavior would be to be able to drag it back, or simply not be able to move it into the sidebar in the first place. Now it's stuck there forever.

**Comment by talldan** [comment] 2021-06-09 09:12
@tijmensmit Please could you fill out the bug report template (you can edit your description and update it with these details - https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.md).

This is unlikely to be looked at without that.

**Comment by aristath** [comment] 2021-06-09 14:05
If I'm not mistaken this is a duplicate of https://github.com/WordPress/gutenberg/issues/7960, and there's a pending PR in https://github.com/WordPress/gutenberg/pull/25187

**Closed as completed** 2021-06-10 01:41 UTC
Labels: [Feature] Meta Boxes, [Status] Duplicate
