### ISSUE TITLE
Add front-end edit link

### ISSUE THREAD

**Issue by parmarhardip** [WordPress/gutenberg#1779] opened 2017-07-07 12:58 UTC
Hello All,

Today I have installed Gutenberg plugin and created few posts using it. But when I publish them I did not see any edit button for open specific Gutenberg editor for that particular post.

Thanks,

**Comment by swissspidy** [comment] 2017-07-07 13:02
Hey there,

Thanks for your report! Would you mind following [the steps you should have seen when creating this issue](https://raw.githubusercontent.com/WordPress/gutenberg/6b8c93c01a88c16ec26a59c5d5e73eaab33377dd/.github/ISSUE_TEMPLATE.md) to add some more information? Where exactly don't you see an edit button? Can you perhaps provide a screenshot?

Thanks again.

**Comment by nylen** [comment] 2017-07-07 13:02
Probably refers to the front-end edit link.

**Comment by swissspidy** [comment] 2017-07-07 13:05
> Probably refers to the front-end edit link.

That would be a duplicate of #1627 then. That's why some more details would be good.

**Comment by westonruter** [comment] 2017-07-07 20:50
@parmarhardip there is a Gutenberg link in the row actions in the post list table:

![image](https://user-images.githubusercontent.com/134745/27976350-f4b4c714-631a-11e7-87f7-8886cf32ab9d.png)

That being said, we should probably actually cause any post that was created using Gutenberg perhaps to open in Gutenberg by default instead of the current post editor.

**Comment by westonruter** [comment] 2017-07-07 21:02
I'm working on a patch for that.

**Comment by westonruter** [comment] 2017-07-07 22:19
Please review #1797. It improves the links in the post list table as well as adding links to the admin bar and for the edit links for posts with blocks.

**Closed** 2017-09-08 17:36 UTC
