### ISSUE TITLE
Editing a template with a `Site logo` block does not allow me to edit that block

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#32391] opened 2021-06-02 09:01 UTC
## Description

On the template editing mode, add a `Site logo` block to it. Try clicking on it to choose the logo from the media library, but it does not show any actionable interface.

## Step-by-step reproduction instructions

- Start with a template and enter its editing mode.
- Add a `Site logo` block to it.
- See that does not have any actionable interface.

## Expected behaviour

The `Site logo` block allows me to choose a logo from the media library.

## Actual behaviour

It does not allow me to choose one.

## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/18581859/120451008-a3841400-c3ae-11eb-904b-f0ba54cb3745.png)

![image](https://user-images.githubusercontent.com/18581859/120451058-b26ac680-c3ae-11eb-9ff5-2ebb0e5b5896.png)

## Code snippet (optional)

None.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.5.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Mayland Blocks

## Device information
- Device: MacBook Pro
- Operating system: Mac OS
- Browser: Firefox 88.0.1

**Comment by aristath** [comment] 2021-06-02 13:27
This has already been fixed in trunk.
Duplicate of https://github.com/WordPress/gutenberg/issues/32171

**Closed as completed by aristath** 2021-06-02 13:27 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Site Logo
