### ISSUE TITLE
srcset attribute in Gutenberg gallery blocks

### ISSUE THREAD

**Issue by aitormendez** [WordPress/gutenberg#13963] opened 2019-02-20 08:26 UTC
Gallery block are very useful to layout thumbnails. However, when I choose a columns layout (for example, four columns layout), the `srcset` for this thumbnail remains the same as a large image.

In other words, with a four columns layout, the thumbnails `srcset` come with:

`sizes="(max-width: 768px) 100vw, 768px"`

So, all thumbnails are built with the large images. For example, in this page: https://stage.margenesdelarte.org/productions/relato-de-salida-al-albergue-2018/

Is it possible to get something like this?:

`sizes="(max-width: 768px) 100vw, 200px"`

Further more, is it possible to set `srcset` up regarding the number of columns in the gallery block layout?

**Comment by swissspidy** [comment] 2019-02-20 11:11
Related and possible duplicates: #6177, #5674

**Comment by youknowriad** [comment] 2019-02-21 07:09
Duplicate of #9620

**Closed by youknowriad** 2019-02-21 07:09 UTC
Labels: Media, [Block] Gallery
