### ISSUE TITLE
Categories & Tags (taxonomy) panel doesn't show for authors and below

### ISSUE THREAD

**Issue by helen** [WordPress/gutenberg#4787] opened 2018-01-31 22:55 UTC
## Issue Overview
In 2.1, author and contributor users do not have the Categories & Tags panel at all, though they do in the classic editor. This has been reproduced by myself and several others across a variety of installs.

## Steps to Reproduce (for bugs)

1. Log in / switch to an author or contributor user.
2. Edit a post.
3. Look to assign a category or tag.

## Expected Behavior

I would expect to be able to see the panel and be able to assign terms as an author or contributor.

## Current Behavior

There's no panel at all.

## Screenshots / Video

![screenshot](https://user-images.githubusercontent.com/906334/35651995-c150a6f2-06af-11e8-990d-38c43da29b2e.png)

## Related Issues and/or PRs

#2545 seems to show the panel showing at one point for the author user.

**Comment by bobbingwide** [comment] 2018-02-03 13:18
In my reproduction of this problem I can see that the REST request to list categories and tags 
```
https://qw/src/wp-json/wp/v2/taxonomies?context=edit
```
is getting a 403

```
wp-content\plugins\oik-bwtrace\includes\bwtrace-actions.php(498:32) bw_trace_rest_pre_echo_response(1) 33 2018-02-03T13:00:03+00:00 0.257115 0.091565 cf=parse_request,rest_pre_echo_response 4 0 2097152/2097152 128M F=246 result Array
(
    [code] => rest_cannot_view
    [message] => Sorry, you are not allowed to manager terms in this taxonomy.
    [data] => Array
        (
            [status] => 403
        )

)
```

The user should at least be able to select the Category for the post.

IMO this Issue should be labelled: 
- Backward compatibility. 
- Severity: 3. existing Categories and Tags are not lost
- Workaround available.

### Workaround 
The workaround is either to switch to the `&classic-editor` or use quick edit

**Comment by LZL0** [comment] 2018-03-14 14:15
Obviously it's an issue with the initial request being an EDIT instead of a VIEW type request. EDIT is tied to the manage_categories capability. It seems, that first Gutenberg should check manage_categories for the user and decide whether or not the Add Category field should be displayed.

**Comment by mtias** [comment] 2018-03-19 20:00
Adding this one to the set of API issues to sort out. The biggest challenge here is the apparent impossibility of describing the request without the context of `edit` or `view`. This is relevant beyond the sidebar panel, as blocks start to interact with various resources (like latest-posts or the categories widget). Ideally we don't want developers having to build logic for this outside of declaratively representing their UI for the right audience.

Explorations like https://github.com/WordPress/gutenberg/pull/5219 are in the spirit of modeling a querying system that allows us to evolve the tooling and flow around data. We'd want to absorb, in our data layer, the responsibility of determining the context and firing the request. I want to avoid adding logic bifurcations just to handle the individual cases because it's going to cascade out of control rapidly, and we'd lose control of concerting the potentially similar requests to reduce network and bandwidth costs.

**Comment by LZL0** [comment] 2018-04-11 19:59
Does anybody have an ETA on this?

**Comment by danielbachhuber** [comment] 2018-04-11 20:17
> Does anybody have an ETA on this?

No ETA, but it's on my radar now to look into.

**Comment by LZL0** [comment] 2018-04-12 10:34
Thank you. Appreciated.

**Comment by danielbachhuber** [comment] 2018-04-13 01:13
Closing in favor of https://github.com/WordPress/gutenberg/issues/5879#issuecomment-380990325

**Closed by danielbachhuber** 2018-04-13 01:13 UTC
Labels: Core REST API Task, [Type] Bug
