### ISSUE TITLE
Lists > Editing flow : typing is getting slower and managing nested lists generates unattended behaviors / content losts

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#53353] opened 2023-08-04 14:03 UTC
### Description

This was observed for few months, not only on recent Gutenberg versions.
I use the buttons of the floated toolbar to indent my lists.

**1/ When we write down a quite long (normal) content, the typing become slower and slower**
My example is a content with those figures, i make usage of many nested lists into my paragraphs.
- Characters:12463
- Words:1923

<!>I observe this mostly on Firefox, less on Chrome but is occurs on both browsers after few minutes at editing your article

**2/ Manage List entries generate flickering / flackiness**

If you have a list and sublists, it's extremely difficult to update the sublists. Adding some, delete empty sublists, etc.

```
* list 1
   * sublist 1-1
       * sub-sublist 1-1-1
       * sub-sublist 1-1-2
   * sublist 1-2
   * sublist 1-3
* list 2
   * sublist 2-1
   * sublist 2-2
   * sublist 2-3
```

Several cases here :
- [a] When deleting a sublist, for instance 1-2, it impacts the next the next List2  that is sometimes merged into List 1 ! Sublist 1-3 can disapear. It is a nightmare.
- [b] Sometimes, when inserting a sublist betweeen two already sublists, the content of the next sublists are superposed (character becomes non readable). The only way to make this disappear is to save + refresh the page
- [c] When you want to delete an empty list, you hit Delete on your keyboard but it deletes the next sublists, you loose content !

<!> I observe these behaviors in Chrome+FF also.

Seems Gutenberg is getting lost even if we save the page frequently. There are issues with List vs List Item : child items are displayed as child of the same list item but Gutenberg created another List at another level that is not visible. 
The only workaround i found is to manage nested levels with the List View in the Editor. it is impossible directly when typing.

To sum up, the List block is very instable, and its very hard to manage our contents. We have to take care not to loose some when editing our articles.

I guess those 2 List specific ssues are related, and rely on sublists. 

### Step-by-step reproduction instructions

Just create an article with List block

### Screenshots, screen recording, code snippet

It'll post screenshots / screencasts as a follow up as soon as the errors occur back

![image](https://github.com/WordPress/gutenberg/assets/919332/ac58c215-8e3a-41c7-93d3-b0b52c782ba0)

### Environment info

- WP 6.2.2 / WP 6.3 RC3 but it's a old behavior
- Gutenberg but it's not specific to this release
- FF or Chrome latests versions

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Marc-pi** [comment] 2023-08-04 14:34
About [2]
I think the culprit is a mess up in List / List items. List blocks creates groups of list whenever it wants, leading to unespected behavior. Those are not visible in the interface, only the List View can give you the explanation of the mess up.

Here is a screencast that explains the difference between the writing flow and the block List View. Lists levels are created but not visible. So when we delete some entries, sometimes we delete non visible levels !

ping @ellatrix 

[screen-recorder-fri-aug-04-2023-16-29-36.webm](https://github.com/WordPress/gutenberg/assets/919332/456d80f0-851d-4bfc-b3ba-0c985e333eb6)

**Comment by ellatrix** [comment] 2023-08-10 06:24
Did #52949 fix this issue?

**Comment by annezazu** [comment] 2023-08-30 01:06
@Marc-pi can you follow up on the above to confirm if the issue is still present?

**Comment by Marc-pi** [comment] 2023-08-30 10:48
hello,
@ellatrix / @annezazu it is better. The "list tree" is cleaner, seems you improved the nested lists.

There is one issue : see the video below 
* when we want to merge 2 sub-lists by clicking the suppress key, the 2 lists are merged. 
* If we make i mistake and want to add back the sublist with adding "a return", it creates a new list, the child list level is getting lost.
* It works well when using parent list level, not when we have sublists.

[screen-recorder-wed-aug-30-2023-12-41-38.webm](https://github.com/WordPress/gutenberg/assets/919332/3bbb42a1-c648-4ec9-a532-07587d949f5b)

and you get strange display : 

![image](https://github.com/WordPress/gutenberg/assets/919332/4578a931-ac15-4f5b-83fc-d59fc2a0dbb8)


----

WP 6.3
Gutenberg 16.5.1
TT2 theme

**Comment by ellatrix** [comment] 2023-09-01 14:15
Would you be able to share the starting content of the code editor here, and then the steps you do to end up with the unexpected behaviour? Or just the steps from a blank page if it can be reproduced more simply?

**Comment by Marc-pi** [comment] 2023-09-06 05:49
hum, i will try to replicate the exact point of my previous post.
Going back to the initial findings to ensure it is still fixed (and prepare a replication of my previous post), seems the nested lists are still wrongly declined into blocks (despite my previous comment).
So when we try to manage the list (add a new child line, click suppress button at the end of one child elements), it leads to unespected behaviors.
For instance, if i click suppress at the end of one child line to merge 2 lines, it deletes a line outside the list.
The editor get lost...

![image](https://github.com/WordPress/gutenberg/assets/919332/5ccd2b46-77c7-4fbb-a24c-819ad604e8a3)

**Comment by ellatrix** [comment] 2023-09-07 07:20
@Marc-pi are you editing an existing list or a newly created one? It's worth noting that if the existing list has a bad structure, it won't get fixed. I'm interested in how you ended up with this bad structure, so the step you took to end up in this state with a list item having multiple lists inside it.

We could update your badly structured list by merging all those nested lists, but I'm wondering how you got to this state so we can fix the problem at the root.

**Comment by Marc-pi** [comment] 2023-09-14 20:01
@ellatrix i created completely new lists under Gutenberg 16.6 / WP 6.3.1
and then i play with them : moving child to parent, trying to merge 2 lists, adding new childs, adding new parent
(exactly like i do with Google Docs for instance)
i saw one of your commit https://github.com/WordPress/gutenberg/pull/52995, does it fix partially my findings ?
tell me if you need more info, so we tackle down this issue quickly before beta1.

**Comment by ellatrix** [comment] 2023-09-15 07:21
@Marc-pi That will help, but I'm still wondering how you ended up in a state where you have a list item with multiple nested lists. Could you give me exact steps to reproduce from an empty post? Or alternatively, here is a list with a nested list:

```
<!-- wp:list-item -->
<li>one<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></li>
<!-- /wp:list-item -->
```

How do you get to the state where you have one list item with _multiple_ lists nested in it?

**Comment by Marc-pi** [comment] 2023-09-19 16:57
@ellatrix,
to help you understand, here is a vid i recorded for you, from a fresh new Page
You will notice 2 issues i was talking about above :
- the reworked nested lists are lost at a certain point (see at the end of the video)
- trying to merge parent into the previous parent make loose the child elements of the merged parent
- i cannot ident by tab, i've to use the toolbar (but that's another issue)

Hopes that helps you
Please note that i do use Firefox in that recording

[screen-recorder-tue-sep-19-2023-18-53-59.webm](https://github.com/WordPress/gutenberg/assets/919332/8c97102d-4daa-4a08-930d-f95050a6c706)

**Comment by annezazu** [comment] 2023-09-25 21:13
Moving this out of the 6.4 board as we are out of time to iterate further.

**Comment by ellatrix** [comment] 2023-10-06 11:13
@Marc-pi Thanks for the video! I now understand what's happening. You're pressing (forward) Delete with this state (using ↦ to indicate where you press the Delete key):

* parent 1
  * child 1.1 ↦
* parent 2
  * child 2.1

Then you end up with a list item that has two sub lists.

I'll make a PR to fix this.

**Comment by ellatrix** [comment] 2023-10-06 11:43
Fixed in https://github.com/WordPress/gutenberg/pull/55121.

**Comment by ellatrix** [comment] 2023-10-06 11:43
It's an easy fix if there's desire to back port it.

**Comment by Marc-pi** [comment] 2023-10-07 10:58
@ellatrix 
hello,
in fact, like in Google Doc or CKeditor (both are ok with accessibility norms), i do use on my keyboard :
- Suppr button OR Delete button &#x2190; // in case i want to merge 2 lists
- Enter &ldsh; (line break) // to add new child
- &mapstoleft; / &#8614; (with shift) // to adjust childs vs parent ie to ident the list
- Double Enter &ldsh; // to exit the list block
- ALT+Enter (return to line) // i do not use

Those should work to manage the lists
hope you understand the attended behavior

**Closed as completed** 2023-10-10 08:54 UTC
Labels: [Type] Bug, [Status] In Progress, [Status] Needs More Info, [Block] List
