### ISSUE TITLE
The classic editor block breaks HTML in shortcodes content

### ISSUE THREAD

**Issue by decodekult** [WordPress/gutenberg#12068] opened 2018-11-19 15:37 UTC
**Describe the bug**
Shortcodes with HTML in their content get that HTML content encoded as soon as you end up typing them.

**To Reproduce**
1. Go to a new post edited with Gutenberg and add a classic editor block.
2. Copy the example for the shortcode with content `[caption]<a href="http://example.com/">My Caption</a>[/caption]` in the official documentation: https://codex.wordpress.org/Shortcode_API#Enclosing_vs_self-closing_shortcodes
3. Save the post and see it in the frontend.
4. See tha the link contained in the caption shortcode was HTML encoded.

In fact, the content of the shortcode is HTML encoded as soon as you paste it inside the Gutenberg classic editor block. This does not happen on a post edite with the classic editor using the TinyMCE Visual tab.

**Expected behavior**
The HTML inside the shortcode content should be respected.

**Screenshots**
Classic block editor with the example just pasted:
![image](https://user-images.githubusercontent.com/1232205/48716987-d1524480-ec18-11e8-8d11-19da1f769bc8.png)

HTML source of the portion of the classic editor block with the example just pasted:
`<p>[caption]&lt;a href="http://example.com/"&gt;My Caption&lt;/a&gt;[/caption]</p>`

Frontend:
![image](https://user-images.githubusercontent.com/1232205/48717141-1d04ee00-ec19-11e8-8a0b-5e2acb4e2cbf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox
 - Version 63

**Additional context**
- Gutenberg plugin 4.4.0
-  WordPress 5.1-alpha-43678

**Comment by catehstn** [comment] 2018-11-19 17:21
@designsimply Can you please take a look at this and see if you can repro?

**Comment by La-Geek** [comment] 2018-11-19 21:36
**_Confirmed_**
Windows 10 64bit, Chrome browser, (all recent), WP (5.0-beta5-43908) without Gutenberg Plugin, Theme Twenty Nineteen

![shortcode_bug](https://user-images.githubusercontent.com/1585416/48736450-8a317700-ec4b-11e8-8483-3910729796a2.gif)

**Comment by designsimply** [comment] 2018-11-19 22:18
Thanks @La-Geek! ❤️

I also tested and confirmed with the plugin standalone (WP4.9.8 & WordPress 4.9.8 and Gutenberg master `1e5f88595`). ([screenshot](https://user-images.githubusercontent.com/1119271/48738445-48cea680-ec0e-11e8-8596-14eaeea0ca10.png))

**Comment by azaozz** [comment] 2018-11-20 11:39
Hm, does that work the same in the Classic Editor? Pasting raw HTML in the "Visual" editor always encodes the `<`, `>`, `&`, etc.

**Comment by decodekult** [comment] 2018-11-20 11:43
No, in the classic editor any HTML content you paste inside a shortcode content is kept, no encoding happens. The example in the official documentation lnked in the opening comment works fine in the Visual tab of the classic editor.

**Comment by azaozz** [comment] 2018-11-20 11:55
Hmm, that doesn't work here :)

Any raw HTML pasted in the Visual editor gets entity-encoded, wrapped in a shortcode or not. Thinking this may be caused by a plugin that doesn't work well (or at all) in the Classic Block. Could you please check what WP plugins you have enabled?

**Comment by La-Geek** [comment] 2018-11-20 12:11
I tested the block classic (like described above). No additional plugin or theme installed/activated.

Windows 10 64bit, Chrome browser, (all recent), WP (5.0-beta5-43908) without Gutenberg Plugin, Theme Twenty Nineteen

**Comment by azaozz** [comment] 2018-11-20 12:19
This is how the Visual editor works: any raw HTML gets entity-encoded. Here the same happens in both the (old) editor in the Visual tab, and in the Classic Block in Gutenberg.

If you need to add raw HTML to a post, it needs to be pasted (or typed) in the Text/Code tab. Then it works as expected. Both the old editor and Gutenberg work the same way.

**Comment by youknowriad** [comment] 2018-11-20 12:21
Closing as works as intended.

**Closed by youknowriad** 2018-11-20 12:21 UTC
Labels: [Block] Classic, [Type] Bug
