### ISSUE TITLE
Image Upload - Invalid JSON warning

### ISSUE THREAD

**Issue by eliorivero** [WordPress/gutenberg#16372] opened 2019-07-01 14:18 UTC
**Describe the bug**
While uploading a bunch of images–42 to be exact, most of them using the gallery block and a few with the image block, I started getting red notices on the gallery blocks as shown in the gifs below. Now, despite the red notices, only 5 images out of the last gallery weren't uploaded: all other 37 images were correctly uploaded the first time. However, the last gallery hung up and had to reload the page to upload those 5 images again.

**To reproduce**
1. Go to a post
2. Add gallery and image blocks and upload many images at once. I was uploading 42 images.

**Expected behavior**
Images to be uploaded correctly.

**Screenshots**
![invalidjson](https://user-images.githubusercontent.com/1041600/60443181-0c761680-9bf1-11e9-8f01-cddf03920361.gif)
![invalidjson2](https://user-images.githubusercontent.com/1041600/60443182-0c761680-9bf1-11e9-9108-51f2fd9b1f19.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome 75 - 64 bits

**Additional context**
- Gutenberg stable included with WordPress 5.2.2
- The post with the images can be found at https://elio.blog/wordcamp-europe-2019/

**Comment by suziwilson** [comment] 2019-11-03 22:05
I was able to reproduce the same behavior. I uploaded 44 images into a gallery block and it did NOT generate an error, but when I uploaded 45 images into a gallery block (the same images +1) I DID get the same error. 

OS: macOS Mojave
Gutenberg: Version 6.8.0
Browser: Version 78.0.3904.70

**Comment by mapk** [comment] 2019-11-19 00:20
Looks like it might be related to: https://github.com/WordPress/gutenberg/issues/10251

**Comment by skorasaurus** [comment] 2021-02-10 15:53
I'm able to reproduce this in certain conditions and I think the cause of this is the total size (in megabytes) of the images being uploaded, not the number of them. 

Based of https://github.com/WordPress/gutenberg/pull/25940 as of commit https://github.com/WordPress/gutenberg/pull/25940/commits/c9b9aa2906216536da5d3a75d50e6a3b15143405

Was successful to:
upload about 35 images (all under 20kb each)
upload about 40 images (from 5kb to 600kb each)
upload 3 images (3 mb each)

Received this error with: 
upload about 15 images (ranging from 300kb to 3mb each); I

My `upload_max_filesize` in my php configuration is 1024mb (this is on my local development environment/server) so I'm not sure if this is related to #10251; since I am able to upload the same files of large file sizes individually.

**Comment by glendaviesnz** [comment] 2021-09-10 02:32
On WP 5.8 and Gutenberg 11.4, and with the [gallery block refactor merged](https://github.com/WordPress/gutenberg/pull/25940), and the [related upload issue fixed](https://github.com/WordPress/gutenberg/pull/34371) I was not able to replicate this with the gallery refactor experiment enabled, or with it disabled and using the old gallery block format. I uploaded 60 images, including some that were bigger than max upload size, so closing this issue for now. Feel free to open again if you can still replicate with the gallery block experiment enabled.

**Closed by glendaviesnz** 2021-09-10 02:32 UTC
Labels: [Type] Bug, [Feature] Media, REST API Interaction, [Block] Image, [Block] Gallery
