### ISSUE TITLE
Image block does not respect image_default_size

### ISSUE THREAD

**Issue by laurentdebricon** [WordPress/gutenberg#19407] opened 2020-01-04 21:16 UTC
**Describe the bug**
Add an image, by default the size is always 'Full', even if you put in your functions.php

`	update_option('image_default_size', 'woocommerce_thumbnail' );
`

and you have also
```

function wp_70048_remove_image_sizes($sizes) {
    unset($sizes['thumbnail']);
    unset($sizes['medium']);
    unset($sizes['large']);

	return array_merge( $sizes, array(
		'woocommerce_thumbnail' => 'Instagram carré',
		'woocommerce_single' => 'Large'
	));

    return $sizes;
}
add_filter('image_size_names_choose', 'wp_70048_remove_image_sizes');
```

**Comment by talldan** [comment] 2020-02-19 03:42
Duplicate of #15091

**Closed by talldan** 2020-02-19 03:42 UTC
Labels: [Block] Image, [Type] Bug, [Type] Plugin Interoperability
