### ISSUE TITLE
Deprecating a save function

### ISSUE THREAD

**Issue by andreyc0d3r** [WordPress/gutenberg#56535] opened 2023-11-26 23:26 UTC
### Description

I have a save function, All i Did was added a class to the div.

so we went from this:

Original save function (to be deprecated):
```
class BlockSave extends Component {
...
<div className="swiper-container swiper"></div>
...
}
```

to this
New save function:
```
class BlockSave extends Component {
....
<div className="swiper-container swiper test"></div>
...
}
```

...

I copied original save function to the deprecated array

```
/**
 * Internal dependencies
 */
import metadata from './block.json';
import save1034 from './save1034';

export default [
	{
		supports: metadata.supports,
		attributes: {
			...metadata.attributes,
		},
		save: save1034
	}
];
```

save1034 is an exact copy of the original class BlockSave, minus the `test` class on the div

Why am I still seeing

```
Block validation: Block validation failed for `da/wp-swiper-slides` ({name: 'da/wp-swiper-slides', icon: {…}, keywords: Array(4), attributes: {…}, providesContext: {…}, …}attributes: {align: {…}, txtColor: {…}, overlayColor: {…}, containerWidth: {…}, overlayImg: {…}, …}blockHooks: {}category: "media"deprecated: [{…}]description: "Create an awesome slider."edit: class extendsicon: {src: {…}}keywords: (4) ['swiper', 'slider', 'wp slider', 'wp swiper']name: "da/wp-swiper-slides"providesContext: {}save: class extendsselectors: {}styles: []supports: {html: false, className: false, anchor: true, align: Array(2)}title: "WP Swiper"usesContext: []variations: [][[Prototype]]: Object).

Content generated by `save` function:

<div class="wp-swiper"><div class="wp-swiper__wrapper"><div class="swiper-container swiper test" data-swiperconfig="{&quot;data-slidesperview&quot;:1,&quot;data-navigation&quot;:true,&quot;data-pagination&quot;:true,&quot;data-autoplay&quot;:false,&quot;data-delay&quot;:3000,&quot;data-speed&quot;:500,&quot;data-loop&quot;:false,&quot;data-effect&quot;:&quot;slide&quot;,&quot;data-direction&quot;:&quot;horizontal&quot;,&quot;data-freemode&quot;:false,&quot;data-autoheight&quot;:true,&quot;data-spacebetween&quot;:0,&quot;data-mousewheel&quot;:false,&quot;data-releaseonedges&quot;:false,&quot;data-paginationtype&quot;:&quot;bullets&quot;,&quot;data-clickablepagination&quot;:&quot;&quot;}" data-slidesperview="1" data-navigation="true" data-pagination="true" data-autoplay="false" data-delay="3000" data-speed="500" data-loop="false" data-effect="slide" data-direction="horizontal" data-freemode="false" data-autoheight="true" data-spacebetween="0" data-mousewheel="false" data-releaseonedges="false" data-paginationtype="bullets" data-clickablepagination=""><div class="swiper-wrapper"></div></div><div class="swiper-button-prev"></div><div class="swiper-button-next"></div><div class="swiper-pagination"></div></div></div>

Content retrieved from post body:

<div class="wp-swiper"><div class="wp-swiper__wrapper"><div data-swiperconfig="{&quot;data-slidesperview&quot;:1,&quot;data-navigation&quot;:true,&quot;data-pagination&quot;:true,&quot;data-autoplay&quot;:false,&quot;data-delay&quot;:3000,&quot;data-speed&quot;:500,&quot;data-loop&quot;:false,&quot;data-effect&quot;:&quot;slide&quot;,&quot;data-direction&quot;:&quot;horizontal&quot;,&quot;data-freemode&quot;:false,&quot;data-autoheight&quot;:true,&quot;data-spacebetween&quot;:0,&quot;data-mousewheel&quot;:false,&quot;data-releaseonedges&quot;:false,&quot;data-paginationtype&quot;:&quot;bullets&quot;,&quot;data-clickablepagination&quot;:&quot;&quot;}" class="swiper-container swiper" data-slidesperview="1" data-navigation="true" data-pagination="true" data-autoplay="false" data-delay="3000" data-speed="500" data-loop="false" data-effect="slide" data-direction="horizontal" data-freemode="false" data-autoheight="true" data-spacebetween="0" data-mousewheel="false" data-releaseonedges="false" data-paginationtype="bullets" data-clickablepagination=""><div class="swiper-wrapper"></div></div><div class="swiper-button-prev"></div><div class="swiper-button-next"></div><div class="swiper-pagination"></div></div></div>
(anonymous) @ blocks.min.js?ver=7204d43123223474471a:10
(anonymous) @ blocks.min.js?ver=7204d43123223474471a:10
Zn @ blocks.min.js?ver=7204d43123223474471a:10
(anonymous) @ blocks.min.js?ver=7204d43123223474471a:10
Xn @ blocks.min.js?ver=7204d43123223474471a:10
(anonymous) @ core-data.min.js?ver=99b262137df116eb6013:2
useMemo @ react-dom.min.js?ver=18.2.0:10
e.useMemo @ react.min.js?ver=18.2.0:10
Un @ core-data.min.js?ver=99b262137df116eb6013:2
(anonymous) @ editor.min.js?ver=3f5791ae786456067a27:12
wt @ react-dom.min.js?ver=18.2.0:10
js @ react-dom.min.js?ver=18.2.0:10
wl @ react-dom.min.js?ver=18.2.0:10
bl @ react-dom.min.js?ver=18.2.0:10
yl @ react-dom.min.js?ver=18.2.0:10
fl @ react-dom.min.js?ver=18.2.0:10
Nn @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
setTimeout (async)
s @ data.min.js?ver=dc5f255634f3da29c8d5:2
i @ data.min.js?ver=dc5f255634f3da29c8d5:2
(anonymous) @ edit-post.min.js?ver=6720d8a86f225f3ce492:7
(anonymous) @ data.min.js?ver=dc5f255634f3da29c8d5:9
__unstableMarkListeningStores @ data.min.js?ver=dc5f255634f3da29c8d5:2
(anonymous) @ data.min.js?ver=dc5f255634f3da29c8d5:2
l @ data.min.js?ver=dc5f255634f3da29c8d5:9
(anonymous) @ data.min.js?ver=dc5f255634f3da29c8d5:9
Je @ data.min.js?ver=dc5f255634f3da29c8d5:9
Qe @ data.min.js?ver=dc5f255634f3da29c8d5:9
Ya @ edit-post.min.js?ver=6720d8a86f225f3ce492:7
wt @ react-dom.min.js?ver=18.2.0:10
js @ react-dom.min.js?ver=18.2.0:10
wl @ react-dom.min.js?ver=18.2.0:10
bl @ react-dom.min.js?ver=18.2.0:10
yl @ react-dom.min.js?ver=18.2.0:10
ol @ react-dom.min.js?ver=18.2.0:10
v @ react.min.js?ver=18.2.0:10
ce @ react.min.js?ver=18.2.0:10
```

### Step-by-step reproduction instructions

- Created a block, everything works as expected
- Decided to manually add an additional hardcoded class to a div
- Copied a save function to be included in the deprecation array
- Still seeing block validation error

### Environment info

Wordpress latest, all latest packages

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2023-11-27 02:05
Looks like the block in your post has no paragraph, but the save function is generating a paragraph.

**Comment by andreyc0d3r** [comment] 2023-11-27 11:48
@talldan thank you for your reply, I have updated my ticket. The <p> was generated by another attempt when I was tyring to debug this myself.

I have updated the post.

Original save function (to be deprecated):

class BlockSave extends Component {
...
<div className="swiper-container swiper"></div>
...
}
to this
New save function:

class BlockSave extends Component {
....
<div className="swiper-container swiper test"></div>
...
}

**Comment by andreyc0d3r** [comment] 2023-11-27 21:06
@talldan even with the paragraph example, the probelm is still there. I only tried it that way thinking may be it has something to do with a class. 

The deprecation is not working as expected.

I literally cloned my save function to a deprecation array. But it is not being used.

**Comment by talldan** [comment] 2023-11-28 01:56
It's hard for me to say exactly, but the main approach I use is to compare the HTML under 'Content generated by save function' and 'Content retrieved from post body' in the error messages to see why your save function is producing something different. You then need a deprecation that matches the post body html. In the updated example there's a 'test' class name that the save function is adding. I'm not sure if it's also an issue that the data attribute and class name attribute are swapped around.

I think there's also some additional logging for each deprecation in development builds so that might be useful.

**Comment by andreyc0d3r** [comment] 2023-11-28 12:10
@talldan may be this video will help me convey my message better https://youtu.be/zkPgQgWTZ8I

Thank you for taking time responding to me, I know its not easy to do this over the wire.

**Comment by andreyc0d3r** [comment] 2023-11-30 08:14
can anyone assist please? why is he deprecation not working?

**Comment by Mamaduka** [comment] 2023-11-30 10:21
Hi, @andreyc0d3r

It's hard to debug deprecation issues with the limited info provided here. Can you provide a barebone example of a block so we can reproduce the bug locally?

**Comment by andreyc0d3r** [comment] 2023-12-01 22:34
I really think its a bug, I refactored my code to use functional components and I solved the problem. So that means that class based components are failing to be deprecated.

If you wish to replicate the issue simply use classes for edit and save functions, add also add class to the deprecated array.

**Comment by Mamaduka** [comment] 2024-05-31 10:47
The class components were never [supported](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/serializer.js#L137-L143) for `save` and React now considers them [legacy API](https://react.dev/reference/react/Component).

I would say this is a "won't fix" issue.

**Closed as not planned by Mamaduka** 2024-05-31 10:47 UTC
Labels: [Type] Question, [Feature] Block API, [Feature] Block Validation/Deprecation
