### ISSUE TITLE
Pullquote colors conflict when only one swatch is registered

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#12024] opened 2018-11-17 22:28 UTC
**_No idea, how to descirbe these bugs_**, since I have no idea, how it should work (when it works), but I am sure, as they are atm., this can't be okay.

Windows 10, chrome browser (all recent), theme twentynighteen, WP (5.0-beta5-43907)

I made an animated Gif, please see yourself:

![pullquote_confusion](https://user-images.githubusercontent.com/1585416/48666370-6988e600-eac0-11e8-830a-fcecd81c9cb4.gif)

**Comment by earnjam** [comment] 2018-11-18 11:30
Screenshot of the not-a-radio-button

![image](https://user-images.githubusercontent.com/4267290/48671788-724add80-eafb-11e8-95de-68eba2a69f9d.png)

**Comment by La-Geek** [comment] 2018-11-18 12:04
There's more confusing than that.
Once you click on the left circle under Text Color it has an effect on both (pullqoute and citation), once it has an effect only on citation.
Similar when you click on the left circle under Main Color it has different inconsistent effects.
Imho the best solution would be a third row with circles for "citation" text and all should work in a simiar way to the circles in block paragraph=
First row = background color
Second row = (quote) text color
Third row = (citation) text color

**Comment by La-Geek** [comment] 2018-11-18 13:02
And here is, how Genesis Framework handles this (imho the better name for `Main Color` would be `Background Color`), there is no difference in text color between quote and citation text:


![genesis_pullquote](https://user-images.githubusercontent.com/1585416/48672776-9679df00-eb3a-11e8-98d1-74737f9601d7.gif)

**Comment by jasmussen** [comment] 2018-11-19 12:29
Thanks for the ticket. I would like to re-label to something like "Pullquote colors conflict when only one swatch is registered", or something like that.

Let me show a few GIFs and then elaborate on what's going on. Vanilla stylesheet:

![vanilla](https://user-images.githubusercontent.com/1204802/48706803-a27aa500-ebfd-11e8-9457-f1e30ca8ce98.gif)

TwentyNineteen:

![2019](https://user-images.githubusercontent.com/1204802/48706810-a7d7ef80-ebfd-11e8-862c-c9ecfadb3d52.gif)

So, there are a number of issues here. Notably with the "Solid Color".

1. Note how in the Regular style, if you set the main color, you _only_ set the main color. But in the Solid style, when you set the main color, you _also_ set the text color. This is a problem because a theme, as in the case of TwentyNineteen, might not have registered more than a single color. Which means it's a buggy experience. We should fix this so you only ever set a single color. 
2. TwentyNineteen, as mentioned above, only sets a single color swatch. Not only that, but it's the same color as the solid pullquote style has by default. Suggested fix: expand the TwentyNineteen palette to have more than one color.
3. TwentyNineteen does not make use of the main color in the "Solid" style at all. It should. Main color should always be the background, or the decoratives, and the text color should always be the text above.

3 is worth expanding on, because there's a matrix of bugginess here. This refers only to the "solid" style:

A: When no color options are set, you get a blue quote with white text:

![screenshot 2018-11-19 at 13 23 24](https://user-images.githubusercontent.com/1204802/48706993-53813f80-ebfe-11e8-9d6c-5706d047b772.png)

B: When you set a blue background main color, not only is the _text_ color option also set to blue, but weirdly only the citation text color is changed:

![screenshot 2018-11-19 at 13 24 01](https://user-images.githubusercontent.com/1204802/48707028-6d228700-ebfe-11e8-8612-774713f93ca7.png)

C: If you then clear the text color, so there's a blue main color, you get basically the same as the default pullquote:

![screenshot 2018-11-19 at 13 24 26](https://user-images.githubusercontent.com/1204802/48707055-8297b100-ebfe-11e8-94c9-02c38b0fa140.png)

D: If you set only the text color, you get this:

![screenshot 2018-11-19 at 13 25 20](https://user-images.githubusercontent.com/1204802/48707077-92af9080-ebfe-11e8-9185-18d0bb5ca3e5.png)

C and D technically appear to be behaving correctly, as the main color is the same as the background, and the text color appears to apply to the whole text. But when you compare D with B, you realize that if you set the Main color to blue, then the pullquote text is _white_.

Suggested next steps:

1. Fix so setting the Main color of the pullquote doesn't _also_ set the text-color. While the intention is probably to ensure contrast, this stresscase proves that doesn't work. I would also argue that this is lossy behavior, as it makes a change to an option you didn't touch yourself. CC: @tofumatt @jorgefilipecosta I think you two worked on the pullquote, do you have insights here?

2. Make the TwentyNineteen pullquote customization _slightly_ less opinionated. By default it's fine that the pullquote is white text on a blue background, but that's where the customization should stop, and both the main color and text color should behave predictably like it does in the vanilla style. Additionally the color palette should be expanded. I will take a stab at this but CC: @kjellr for insights.

**Comment by tofumatt** [comment] 2018-11-21 18:20
I hope I followed everything here but I'd say the main issue is that the limited numbers of swatches make it tough to ensure contrast. The code put in place to ensure text stays visible should work with slightly less opinionated pull quote colours, I think.

Sorry if I'm missing something or you wanted more specific feedback, there's a lot to follow in this issue but I think the main thing is that the theme should tweak its colour options rather than us remove the code we have to ensure contrast. 🤷‍♂️

**Comment by kjellr** [comment] 2018-11-21 18:30
Just circling back to say that Twenty Nineteen now includes the two recommendations @jasmussen made above: 

> ... both the main color and text color should behave predictably like it does in the vanilla style. 

As of https://github.com/WordPress/twentynineteen/pull/643, the "Main" color now works reliably in both of the Pullquote variations. The display of the default pullquote is has no top or bottom border, but if someone specifies the "Main" color, borders using that color will be added.

>  Additionally the color palette should be expanded. I will take a stab at this but CC: @kjellr for insights.

The palette was expanded from 1 color to 5 colors in https://github.com/WordPress/twentynineteen/pull/642

**Comment by jasmussen** [comment] 2018-11-21 18:56
> I hope I followed everything here but I'd say the main issue is that the limited numbers of swatches make it tough to ensure contrast. The code put in place to ensure text stays visible should work with slightly less opinionated pull quote colours, I think.

Yeah sorry that got very cryptic.

However that's actually not the biggest issue. The biggest issue as I can tell is that setting the background color _also_ sets the text color. This is the cause of most of the issues up there, and is only slightly mitigated by expanding the color palette.

**Comment by jasmussen** [comment] 2018-11-21 19:00
To elaborate on this, there are two problems with automatically setting the text color when you set the main color:

1. It overrides any choice the user might have made, i.e. picked a custom text color first. It's also unpredictable, as one option usually only sets that one option.
2. It is actually _as bad_ and sometimes _worse_ for contrast, because as was the case initially, there was only one swatch registered for TwentyNineteen, blue, and when it was the only one to choose it was blue on blue with zero contrast. At least by keeping the text color the default black, the user would've seen the contrast warning, and been able to act on it.

**Comment by dreamwhisper** [comment] 2019-01-23 16:23
From what I've experienced, if there are 2 custom colors set by the theme, when selecting one, the alternate color is being selected as the text color. My expectation is that if I have not specified a text color, the color would be set with acceptable contrast. 

This seems to work well with buttons, but not with the pullquotes.

**Comment by ghost** [comment] 2023-03-10 18:23
Since it's been inactive a long time, is this still considered an issue or has it been resolved in the meantime? What can we do to move this forward? @jasmussen @dreamwhisper @La-Geek

**Comment by jasmussen** [comment] 2023-03-13 09:55
Thanks for the ping. The UI has advanced substantially since this issue, with both a better color picker system, as well as the retirement of the pullquote style variation:

<img width="529" alt="Screenshot 2023-03-13 at 10 53 44" src="https://user-images.githubusercontent.com/1204802/224667483-08bec9d8-46ff-46a7-9ec0-df558fbfae54.png">

In that light, I'll close this one. If the issue remains in some form, let me know and we can open a new issue describing what remains to do.

**Closed by jasmussen** 2023-03-13 09:55 UTC
Labels: [Type] Enhancement, [Block] Pullquote
