### ISSUE TITLE
Columns Block (beta): sibling inserters don't work within the columns block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7920] opened 2018-07-12 05:57 UTC
**Describe the bug**
None of the Block Inserters work on the Column Block. It's impossible to add a Block above a Column Block and it's also impossible to insert blocks into the column block itself

![gutenberg_columnblockblockinsertersdontwork](https://user-images.githubusercontent.com/2078245/42614100-add37340-85e7-11e8-99db-f777342cb91e.gif)

**To Reproduce**
1. Add Column Block
2. Add multiple Paragraph Blocks into the Column Block
3. Try to insert a Block above the Column Block
4. Try to insert another Paragraph Block above the top Paragraph Block

**Expected behavior**
Block inserters should work and should be easier to click

_macOS Sierra 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by designsimply** [comment] 2018-07-19 14:12
Closing because I tested with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6 and found that the block inserters within the columns block work for me. ([45s](https://cloudup.com/crd_GCRHib5))

#7766 should address the problem described about not being able to select the whole columns block.

Related note: the inserters are not present when a block is selected and I believe that is by design. I noticed in your video that you tried to find an inserter on the 2nd paragraph block _after_ clicking on the content which will not work with the way inserters are currently designed to work—I am not sure if that will change and it is a different issue/discussion but helpful to know when testing here.

**Comment by chrisvanpatten** [comment] 2018-07-19 15:11
@designsimply I can reproduce this in Safari 11.1.1 and I think it might be related to #7642.

**Closed** 2018-07-19 19:58 UTC
Labels: Blocks, [Status] Duplicate

**Comment by maddisondesigns** [comment] 2018-07-20 04:00
@designsimply @chrisvanpatten Can you please reopen this. The sibling inserters still don't work properly. Here's another gif I just created. Out of about a dozen clicks I was only able to get the inserter to work once.

Not only that, when it doesn't work, it simply selects the block and shows the toolbar. You then have to click outside of the block to deselect it because the sibling inserter wont even display when the block is selected because it's hidden by the toolbar. It shouldn't be this hard for users to add content into multiple columns.

![gutenberg_columnssiblinginsertersdontwork](https://user-images.githubusercontent.com/2078245/42981903-03687dce-8c22-11e8-9fc8-f493861560da.gif)
