### ISSUE TITLE
First save and preview leads to 404

### ISSUE THREAD

**Issue by bymrbanks** [WordPress/gutenberg#49424] opened 2023-03-29 07:27 UTC
### Description

When saving a new post and pressing preview it goes to myurl.com/undefined

### Step-by-step reproduction instructions

1. Create a new page/post
2. Save and preview

### Environment info

- WordPress: 6.2-RC5
- PHP: 7.4.1
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.1)
- Browser: Chrome 111.0.0.0 (macOS)
- Theme: 
- MU-Plugins: None activated
- Plugins: 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2023-03-29 07:47
Thanks for contributing, @bymrbanks!

I'm not able to reproduce the issue. Are you using the Gutenberg plugin or just testing with WP 6.2-RC5?

If possible, can you share a screen recording of the problem? That might help us to narrow it down.

Thank you!

**Comment by ndiego** [comment] 2023-04-18 15:22
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.

**Closed as completed by ndiego** 2023-04-18 15:22 UTC
Labels: General Interface, [Status] Needs More Info, Needs Testing, [Package] Edit Post
