### ISSUE TITLE
No Option to Set Parent in Custom Post Type Editor

### ISSUE THREAD

**Issue by zachatkinson** [WordPress/gutenberg#40524] opened 2022-04-21 17:43 UTC
Hi All,

Recently a client was trying to set a CPT as a child and noticed there is no drop down option for parent in the page settings when in the Gutenberg editor. This is also discussed here:

[https://wordpress.org/support/topic/parent-page-missing-in-page-attributes/](https://wordpress.org/support/topic/parent-page-missing-in-page-attributes/)

It seems like this has been a bug for a long time. My CPT has the following settings: 

`
'hierarchical' => true,
'supports'      => array( 'title', 'editor', 'thumbnail', 'excerpt', 'comments', 'revisions', 'page-attributes' ),
`

Quick edit will allow me to set the parent fine, but it would be much better UX to allow the user to select parent within the post, just like pages and default post type.  

Is there another flag I need to enable in my CPT to allow GB to show this dropdown, or is there a solution being worked on?  Thanks in advance!

**Comment by ALJ** [comment] 2022-04-22 00:09
Hi @zachatkinson on a clean install of WordPress 5.9.3 (no Gutenberg plugin), the custom post type parenting hierarchy works for me.

When I add the following config to `register_post_type()`, I get a panel in the content editor labeled "**CPT Attributes**" allowing me to set a parent (where the "CPT" is the name of your custom post type):

```
'hierarchical'  => true,
'supports'      => array( 'title', 'editor', 'page-attributes' ),
```

Another thing to check is whether you have the panel disabled in your block editor preferences:

1. In the content editor, open the `Options` menu (the three little dots in the far upper-right corner).
2. In the menu that appears, click `Preferences`.
3. In the modal that appears, click `Panels` and make sure `Page attributes` is turned on like in this screenshot.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/389936/164570004-c0d018fe-d8e2-4eb4-b7e0-83f43fb1a9b6.png">

**Comment by ndiego** [comment] 2022-04-22 10:59
I can confirm this is working for me as well in the latest version of WordPress. @zachatkinson here is the demo code that I am using: 

```
function myplugin_register_book_post_type() {
    $args = array(
        'public'        => true,
        'label'         => 'Books',
        'show_in_rest'  => true,
        'hierarchical'  => true,
        'supports'      => array( 'title', 'editor', 'page-attributes' ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

And as @ALJ mentioned, make sure to double-check that the  "Page Attributes" panel is enabled. 

Since this functionality has been confirmed to work as expected in the latest version of WordPress and Gutenberg, I am going to close this out. But please let us know if we can be of further assistance!

**Closed as completed by ndiego** 2022-04-22 10:59 UTC

**Comment by derekashauer** [comment] 2022-12-06 19:00
Had same issue but found that if I made the "parent_item_colon" label empty then the entire parent selection doesn't show. Seems odd to me the whole thing doesn't show simply because there is not a label. Only lost a little hair on this one.

**Comment by ALJ** [comment] 2022-12-06 19:34
> if I made the "parent_item_colon" label empty then the entire parent selection doesn't show

I see similar behavior. To tease it out:

1. **If I pass an empty string** (`'parent_item_colon' => ""`), the entire parent post selector goes missing from the Attributes panel. This might be intentional to prevent an unlabeled field showing.
2. **If I omit it totally** (`/* 'parent_item_colon' => "Parent CPT:" */`), the parent post selector appears with a default label of "PARENT PAGE:". That makes sense to me.

I _think_ everything is working as it should

**Comment by derekashauer** [comment] 2022-12-06 20:51
Yes, you got it. I just wanted to document it even though this is closed in case someone else is losing hair over it like I did.
