### ISSUE TITLE
Post type is 'post' when calling get_current_screen with Gutenberg active even when editing CPTs

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#5048] opened 2018-02-14 07:41 UTC
## Issue Overview
When calling `get_current_screen` with Gutenberg active the resulting object has a post type of `post` instead of the current post type being edited in the admin.

It actually looks like this filter is running twice, with the first run being the correct post type and the second being `post` no matter what the CPT is. Is there a more reliable way we should be using on the server side to get the current post type being edited in wp-admin?

## Steps to Reproduce (for bugs)

Install The Events Calendar and add the following code to functions.php of a child theme. When you go to edit an event, `$screen->post_type` will be `post` instead of `tribe_events` as expected.

```
add_action( 'current_screen', function() {
	if ( ! function_exists( 'get_current_screen' ) ) {
		return;
	}
	$screen	= get_current_screen();
	// $screen->post_type is 'post' instead of 'tribe_events'
} );
```

**Comment by fastlinemedia** [comment] 2018-02-14 07:46
Just tested with the `$typenow` global and am getting the same result. It's `tribe_events` on the first run and `post` on the second.

**Comment by bobbingwide** [comment] 2018-02-14 08:50
Can you check if this is a duplicate of #4772 and whether or not the outstanding PR fixes it.

**Comment by youknowriad** [comment] 2018-02-14 22:19
closing as duplicate of #4772 and should be fixed by #4889 

Let me know if it's not the case.

**Closed by youknowriad** 2018-02-14 22:19 UTC

**Comment by fastlinemedia** [comment] 2018-02-14 22:21
Thanks! That does appear to be the case. My apologies for missing that one.

**Comment by youknowriad** [comment] 2018-02-14 22:30
No problem @fastlinemedia it's easy to miss issues.
