### ISSUE TITLE
Bottom metaboxes float over the editing window in Chrome

### ISSUE THREAD

**Issue by xenobytezero** [WordPress/gutenberg#5653] opened 2018-03-16 01:58 UTC
## Issue Overview
Metaboxes that appear at the bottom of the editing panel float over the editing blocks in Chrome 64/65

## Steps to Reproduce (for bugs)
Tested with Chrome 65 / 66.0.3359.33
Does not appear in Edge 41.16299.248.0
Gutenberg Plugin 2.4.0

1. Ensure you have a plugin that creates a metabox at the bottom of the main editing page (CoAuthor Plus for instance)
2. Edit a post in Gutenberg that is longer than a single screen

## Expected Behavior
The "Authors" metabox exists at the bottom of the page under all of the editing blocks

## Current Behavior
The "Authors" metabox floats over the editing blocks

## Possible Solution
It seems like the `.edit-post-visual-editor` element does not encompass all of the content, and instead just sets its height to 100% of the window. This means the footer metaboxes sit just under 100% height

## Screenshots / Video

![ss](https://user-images.githubusercontent.com/5059527/37499738-459699f6-28bd-11e8-8cff-79cfed50db2d.png)

**Comment by youknowriad** [comment] 2018-03-30 10:43
I can't reproduce this myself, any particularity about this setup or the post content?

**Comment by xenobytezero** [comment] 2018-03-30 23:40
Can't think of anything that is specific to my setup.

- Deactivated all plugins except Gutenberg (2.5.0) and Co Authors Plus (3.2.2)
- Switched to stock Twenty Seventeen theme
- Created a new post and just dumped enough Lorum Ipsum to create a long post 

- Still seeing the issue in Chrome (66.0.3359.66)

![capture](https://user-images.githubusercontent.com/5059527/38157145-fc8f5700-347b-11e8-8f9f-eb45f8262660.PNG)

**Comment by xenobytezero** [comment] 2018-03-30 23:43
In DevTools, changing the `.edit-post-visual-editor.editor-writing-flow` element to remove the `height:100%` rule fixes the issue but creates a large space between the bottom of the actual post and the bottom metaboxes

**Comment by xenobytezero** [comment] 2018-03-30 23:54
So it turns out this appears to be related to the fact that the CoAuthors plugin. If I deactivate that plugin then the metaboxes appear to be fine.

The CoAuthors plugin currently produces a number of notices when activated with Gutenberg (#5654). It's currently unclear if this is due to the notices on the page or if the plugin itself is doing this.

If this plugin is deactivated, everything seems to behave, tested with a custom ACF metabox.

**Comment by karmatosed** [comment] 2018-04-11 23:17
Unless I am mistaken this seems to be the plugin issue over Gutenberg. As a result going to close this, I would encourage reaching out to the plugin author. This can be reopened if needed.

**Closed by karmatosed** 2018-04-11 23:17 UTC
Labels: Browser Issues, [Status] Needs More Info, [Type] Bug

**Comment by mazzopalazzo** [comment] 2019-09-11 06:34
Bump.

Still there on Version 77.0.3865.75 (Official Build) beta (64-bit)

**Comment by johnReeve** [comment] 2019-09-14 19:28
We are having a similar issue.  I have not been able to diagnose the root cause, but the symptom is the same.  Works fine in Firefox but breaks in Chrome (macOS) If I mess with 

.edit-post-layout__content .edit-post-visual-editor {
    flex-basis: 100%;
}

it will modify how this is failing.

**Comment by lkraav** [comment] 2019-09-18 08:54
Hi. I can also reproduce this and so can my users. This might be some kind of a regression specifically with Chrome 77.

**Comment by mrdonduck** [comment] 2022-08-08 21:18
I am also seeing this issue happen only when previewing in mobile or tablet, the meta boxes do not get reset when going back to desktop without having to refresh the page. Not using the plugin mentioned here or in a related thread regarding Yoast.
