### ISSUE TITLE
Add content alignment option into the main reusable block toolbar

### ISSUE THREAD

**Issue by mainiomooses** [WordPress/gutenberg#17640] opened 2019-09-29 22:09 UTC
**EDIT 27 Nov 2019: Changed title of post to match the progression of thought.**

**Problem:** I've converted a centered button block into a reusable one. However, the created reusable block only allows the button to be aligned to the left - even though the buttons for aligning content appear on the reusable block.

**Feature request:** Allow alignment of content within reusable blocks.

**Alternative solutions:** 1. Add class / css to achieve this. 2. Drop the reusable block back to single use form after adding the block - alignment becomes available.

Neither of the alternative solutions are acceptable in my opinion.

Attached a .gif with the problem occurring.

![Gutenberg tasaa globaali nappi (1)](https://user-images.githubusercontent.com/47380226/65840215-da26a300-e31e-11e9-8f9d-18931b7a2f5d.gif)

**Comment by MainioMooses** [comment] 2019-09-30 07:31
**This problem has been solved in an upcoming release.**

**Comment by paaljoachim** [comment] 2019-11-07 04:25
Hey Jaakko @MainioMooses 

I am working on a site right now and I am using the Gutenberg plugin version 6.8.0. I see no way to align the reusable buttons. As your saying they are automatically aligning to the left.

Has this been solved? How? If not can you reopen this issue?
Thanks.

**Comment by mcsf** [comment] 2019-11-07 11:35
As of today (`master`, post-6.8), I can't reproduce the issue.

**Comment by MainioMooses** [comment] 2019-11-07 12:20
Hello Paal @paaljoachim 

Can confirm issue still exists. Here's a link to a video on YouTube, on which I show the issue.

[https://youtu.be/f9uJt7HWaWA](https://youtu.be/f9uJt7HWaWA)

Upon converting a block to a Reusable block, you loose the ability to align the items within - at least with a button. Even if you convert a block into a Reusable block AFTER you've aligned the content, the alignment is lost when the block is converted into a Reusable block.

In my mind, this is a major issue as there's no way (without the methods I described in the original post) to have centered buttons in Reusable blocks. Which is just incredeibly silly :P

Cheers.

**Comment by paaljoachim** [comment] 2019-11-08 00:37
I made a reusable block in Gutenberg 6.8. Button block in itself has alignment but when changing it to a reusable block alignment goes away.

It looks like this:
![Screen Shot 2019-11-07 at 19 33 50](https://user-images.githubusercontent.com/5323259/68439498-c54af400-0195-11ea-98a1-2ab058cc74e2.png)

Comparison to saving a paragraph as a reusable block:
![Screen Shot 2019-11-07 at 19 36 20](https://user-images.githubusercontent.com/5323259/68439551-fa574680-0195-11ea-991b-0bceddc3845b.png)

**Comment by mcsf** [comment] 2019-11-11 14:48
I had misunderstood the new reports to be about editing the alignment of the reusable content, not the frame of the reusable content:

![gutenberg-reusable-button-alignment](https://user-images.githubusercontent.com/150562/68595537-8668b700-0491-11ea-8176-ba8d8b6caa02.gif)

Indeed, the whole frame of the reusable block doesn't support alignment.

**Comment by mcsf** [comment] 2019-11-11 14:48
However, I believe the following to be a separate issue:

> Comparison to saving a paragraph as a reusable block

The fact that there are alignment controls appearing on the outer block toolbar seems like a leak from the inner toolbar, because in my testing I see the controls unexpectedly switching from one to the other:

![gutenberg-reusable-button-controls](https://user-images.githubusercontent.com/150562/68595900-3e965f80-0492-11ea-9b30-7c2f7cdd9fb0.gif)

**Comment by mapk** [comment] 2019-11-21 01:32
The button block works just fine with alignments in a Reusable block for me as well.

![btn 2019-11-20 17_30_28](https://user-images.githubusercontent.com/617986/69292685-8ec0a080-0bbb-11ea-9fc6-3e73b1e7677f.gif)

I'm using Gutenberg 6.9 with WordPress 5.3.

**Comment by paaljoachim** [comment] 2019-11-21 02:38
Hey @MainioMooses 

With Gutenberg 6.9 I noticed that there is no alignment controls for the buttons block or the paragraph block in the reusable toolbar. I believe that in 6.8 or perhaps earlier I noticed that there were still alignment controls for aligning the paragraph block.

As the reusable toolbar alignment controls are now gone. 

---

As @mcsf and @mapk are mentioning the use of alignment from within the block controls inside the reusable block as they have shown examples of above.

**It would be helpful to have reusable toolbar alignment controls outside the edit area of the reusable block. **

Editing/adding a reusable block one has the block controls. Saving it as a reusable block there are at present no controls to control the reusable block instance used on a page. It would be helpful to align the instance of the reusable block WITHOUT having to edit all the reusable blocks. This would make for page specific reusable block controls affecting ONLY the instance used on that page and not all.

**Comment by paaljoachim** [comment] 2019-11-27 15:21
Hey @MainioMooses 
Because of the changes to Gutenberg could you rename this issue to: 
"Add alignment option into the main reusable block toolbar."

**Comment by noisysocks** [comment] 2020-04-21 03:11
This could possibly be done by adding the align attribute to `core/block` and modifying its `render_callback` to replace the referenced block's align class with the reusable block's align class.

**Comment by talldan** [comment] 2021-01-07 08:28
Agree that adding alignment options to the reusable block would be a nice way to solve it, would be interesting to see a PR exploring that.

https://github.com/WordPress/gutenberg/issues/28024 is an issue that I've closed and covers a similar issue for the reusable block—if you make a full-width block reusable it suddenly becomes non-full-width, there's no way to make it full-width again. Adding the alignment option seems like a good way to solve the issue.

https://github.com/WordPress/gutenberg/issues/22479 also mentions that aligned content can overflow a reusable block.

**Comment by jordesign** [comment] 2023-10-30 11:36
With greater control over the internal content of Synced Patterns now - I'm inclined to say this issue is no longer relevant. I'll leave it open for 2 more weeks and then close it unless I hear otherwise.

**Closed** 2023-11-10 03:13 UTC
Labels: [Type] Enhancement, Needs Dev, [Feature] Synced Patterns, [Block] Block
