### ISSUE TITLE
`onDrop` function of `DropZone` component

### ISSUE THREAD

**Issue by guvkon** [WordPress/gutenberg#21483] opened 2020-04-08 13:31 UTC
**Describe the bug**
`onDrop` function of `DropZone` component doesn't have position object any more (since upgrade to WP 5.4.0). Instead the second argument is `null` now. Was is it removed or is it a bug?

**To reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop:**
 - OS: macOS
 - Browser: Chrome 80.0.3987.149, Firefox 74.0.1

**Comment by talldan** [comment] 2020-04-20 03:44
Hey @guvkon. It looks like it's still passed to `onDrop` in the code:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/drop-zone/provider.js#L249

The code hasn't changed much lately looking at the history.

I've also done some debugging of the dropzones used in Gutenberg and could see the position passed to the handler:
<img width="601" alt="Screenshot 2020-04-20 at 11 43 12 am" src="https://user-images.githubusercontent.com/677833/79712010-2c9bd100-82fc-11ea-8111-2781d4c48d95.png">

Would you be able to provide some reproduction steps, possibly even some code snippets to help reproduce this?

**Comment by karmatosed** [comment] 2020-05-15 14:00
For now, let's close this as we can always reopen if more details surface.

**Closed by karmatosed** 2020-05-15 14:00 UTC
Labels: [Feature] Drag and Drop, [Status] Needs More Info
