### ISSUE TITLE
Error: The parent theme is missing (When activating child theme)

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#59033] opened 2024-02-14 18:57 UTC
### Description

When trying to activate a child theme, I am seeing this error, even though the TT4 theme is there.

`Error: The parent theme is missing. Please install the "twentytwentyfour" parent theme.`

I first noticed this when a child theme was already active on a site of mine and then I updated to WordPress 6.5 Beta 1. In this case, it was a child theme of Powder.

### Step-by-step reproduction instructions

1. Create a child theme.
2. Make sure parent is installed.
3. Try activating a child theme.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/1a895de2-a8f1-429c-a609-2138c5dc9d44

### Environment info

WordPress 6.5 Beta 1 (Gutenberg active or not active)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2024-02-15 09:41
This is a duplicate of https://github.com/WordPress/gutenberg/issues/58549
While I was not able to reproduce it two weeks ago, I can reproduce it today on 6.5-beta1-57630

**Closed as completed by carolinan** 2024-02-15 09:41 UTC
Labels: [Type] Bug, [Feature] Themes

**Comment by 5AMsan** [comment] 2024-02-23 10:27
I had the exact same issue and Site Editor was only rendering a black page. Deactivating Gutenberg on network and activating per site resolved.
