### ISSUE TITLE
Attempting to rename Template Part deletes Template Part

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24000] opened 2020-07-16 17:37 UTC
**Describe the bug**

When trying to edit the template part name, the entire template section is removed. cc @epiqueras since this _might_ be resolved with your PR https://github.com/WordPress/gutenberg/pull/23661

**To reproduce**
1. Enable Full Site Editing and the demo content.
2. Head to Site Editor (beta) tab.
3. Try to edit the template part name
4. The entire template part will be removed.

**Expected behavior**

I expected the template part to be renamed.

**Screenshots**

Here's a video of me walking through this (44 seconds): https://cloudup.com/cc_RpdQWy8F

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by epiqueras** [comment] 2020-07-16 18:37
Does #23661 fix it?

**Comment by noahtallen** [comment] 2020-07-21 00:30
Possibly related: #22639

**Comment by ZebulanStanphill** [comment] 2020-07-22 17:53
> Does #23661 fix it?

No. Interestingly, I can only reproduce this bug with the template parts created by the Full Site Editing Demo Templates experiment. If I create a new Template Part, I have no trouble renaming it, even after a save and refresh.

**Comment by ZebulanStanphill** [comment] 2020-07-22 20:57
The issue also happens with Template Parts provided by a block-based theme, so I think the issue may have something to do with the difference between those and user-created Template Parts.

**Comment by Addison-Stavlo** [comment] 2020-07-22 21:18
> The issue also happens with Template Parts provided by a block-based theme

Interesting, I am able to reproduce as well without demo-templates.  It seems that the renaming is problematic if we haven't saved a custom version of the template part.

Flow errors when:
* Navigate to site editor.
* Immediately rename the theme supplied template part.

Does not error when:
* Navigate to site editor.
* Edit the template part and 'save'.
* Rename the template part.

**Comment by ZebulanStanphill** [comment] 2020-07-22 21:33
I guess once you edit and save the content of a template part originally provided by a theme, it stops being sourced from the theme since its been modified, so I guess that's why renaming works afterwards.

**Comment by Addison-Stavlo** [comment] 2020-07-22 21:35
> I guess once you edit and save the content of a template part originally provided by a theme, it stops being sourced from the theme since its been modified, so I guess that's why renaming works afterwards.

Right.. something along those lines.

So initially the theme references the template part by a name and has a template-part file with that name.  When we change the name to something else, the file is not found and the template part disappears.

When we edit the template part first and 'save', the Template is also updated and saved to reference the new template part cpt with a given ID.  So when that name is updated it still has the ID to display the template part?

**Comment by epiqueras** [comment] 2020-07-22 21:53
Renaming it needs to save as well then.

**Comment by Addison-Stavlo** [comment] 2020-07-22 22:11
> Renaming it needs to save as well then.

Or maybe we shouldn't allow renaming if it's not saved?  Or a more elegant way of handling this?

I feel like the forcing a save is going to be problematic?  It would need to save the template part and template as soon as the user types into the name input.  If there are already changes dirtied in the template or template part the forced save would either overwrite those changes to only save the new TP name / how the template references it, or will save all those other dirty changes without user confirmation?

**Comment by epiqueras** [comment] 2020-07-23 02:37
Good points. That sounds like a sensible solution.

**Comment by ZebulanStanphill** [comment] 2020-07-23 17:05
Perhaps a theme-supplied template part should be in read-only mode by default, with a button exposed to enable customizing it. Upon pressing this button, a user-created clone of the template part will be created and the block will be updated to reference the user one rather than the theme one. That makes the action a bit more explicit, which makes it clearer that you're no longer user the unmodified theme template part.

**Comment by MichaelArestad** [comment] 2020-08-11 19:40
I would expect to be able to rename a template part without hitting save until I am ready. I expect the template part to remain in place with the new name.

**Comment by noahtallen** [comment] 2020-08-11 19:53
> It would need to save the template part and template as soon as the user types into the name input.

Should we just delay persistent changes to the title until clicking save? Doesn't it currently update the actual title in the DB just when typing in the field?

**Comment by ZebulanStanphill** [comment] 2020-08-11 20:09
> > It would need to save the template part and template as soon as the user types into the name input.
> 
> Should we just delay persistent changes to the title until clicking save? Doesn't it currently update the actual title in the DB just when typing in the field?

If it _is_ currently updating the DB just upon typing, then that's inefficient, and it should definitely be changed to only happen upon save.

**Comment by Addison-Stavlo** [comment] 2020-08-11 20:49
> Should we just delay persistent changes to the title until clicking save? Doesn't it currently update the actual title in the DB just when typing in the field?

I think whats happening is when you type in to change the name, it uses `setAttribute` on the block to change the `slug` attribute (not necessarily save it).  But since there is no ID at this stage, the slug is the only thing used to find the template part.  The component tries to retrieve this after the block updates from `setAttribute`, but a template part file corresponding to this new slug doesn't exist.  So we need to NOT re-retrieve the entity when the slug changes (probably only when an Id is not present?)

**Comment by Addison-Stavlo** [comment] 2020-08-11 21:13
https://github.com/WordPress/gutenberg/pull/24500 should fix it 🤞

**Comment by Addison-Stavlo** [comment] 2020-08-11 22:45
I found an alternative solution on #24500 - however it means that when a template supplied by a theme is first loaded, the template and all of its template parts are marked as 'dirty'.  I don't think this is necessarily a bad thing, just slightly different behavior than before.

**Closed** 2020-08-12 04:07 UTC
Labels: [Feature] Full Site Editing, [Feature] Templates API, [Status] In Progress, [Type] Bug
