### ISSUE TITLE
Changes to code editor lost when closing it with keyboard shortcut.

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#22007] opened 2020-04-30 20:06 UTC
**Describe the bug**
You can switch between Code Editor and Visual Editor using either context menu (three dots menu in right up corner) or using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd> keyboard shortcut. If you use the other option then all changes that you enter to Code Editor will be lost permanently when you switch back to Visual Editor.

This is verified to be Edge browser-related bug only.

The changes are lost permanently. Meaning that text you've added, deleted or changed in Code Editor is not only not replicated in Visual Editor, but also, when you switch to Code Editor for second time, it is gone from there as well.

**To reproduce**
1. Write any text in Visual Editor.
2. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd> to go to Code Editor.
3. Write some text in Code Editor.
4. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd> again to go back to Visual Editor.
4. See that changes made in Code Editor are not replicated in Visual Editor and are lost.

**Expected behavior**
Changes made in one editor should always be replicated in another one.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- gutenberg plugin 8.0.0 (updated 5 minutes ago and validated that bug exists there).

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1803
 - Browser Microsoft Edge
 - Version newest (Windows Update)

Verified that this is Edge-related bug only. I am able to replicate it in Edge on any PC that I have it installed, but I can't replicate it on other browser, i.e. Chrome (in Chrome switching editors using keyboard shortcut works just fine and content is updated on both sides).

**Comment by talldan** [comment] 2020-05-01 04:36
Thanks for reporting this @pansamolot, I was able to reproduce the issue too.

**Comment by noisysocks** [comment] 2020-11-23 03:20
Reported here also: https://core.trac.wordpress.org/ticket/47892

**Comment by noisysocks** [comment] 2020-11-23 04:25
Duplicate of https://github.com/WordPress/gutenberg/issues/9512.

**Closed by noisysocks** 2020-11-23 04:25 UTC
Labels: [Feature] Code Editor, [Type] Bug
