### ISSUE TITLE
Deleting first item in an InnerBlocks list with delete key causes exception

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#29498] opened 2021-03-03 02:20 UTC
## Description

If the delete key or keyboard shortcut is used to delete the first item in an InnerBlocks list an exception is thrown. Using the 'Remove block' menu option for the block works as expected. Using the delete key for any block other than the first one also works as expected.

This issue can be replicated with the Navigation block, and also on the [gallery block refactor PR](https://github.com/WordPress/gutenberg/pull/25940/)

## Step-by-step reproduction instructions:
1. Add a Navigation block and add several child navigation items to it.
2. Select the first item in the navigation and hit delete key to remove
3. Block shows unable to preview message and exception in console

![deletekey](https://user-images.githubusercontent.com/3629020/109742051-389e3200-7c33-11eb-9d82-2bf2fc29d244.gif)

## Code snippet 

Exception is thrown at https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/use-block-props/index.js#L86 

For some reason the useBlockProps hook for the block that has been deleted gets stuck in a loop and throws an exception when trying to get the title of the block that is now deleted.

**Comment by Quintis1212** [comment] 2021-03-03 08:04
Hello ) I can reproduce this bug ) I will try to fix it )

**Comment by Quintis1212** [comment] 2021-03-03 11:07
In my closed PR I fix yours bug , you just need to add more dependence to select function : 
https://github.com/WordPress/gutenberg/pull/29504/commits/0e0eae3ef229d1eef324cb8c5caed6fdbbbf29e4

In tha latest version gutenberg there is no such bug

**Comment by talldan** [comment] 2021-03-09 08:42
@glendaviesnz I was checking if this was affected by #29059, but I can't reproduce this one in `trunk`, would you be able to see if it's still happening?

**Comment by glendaviesnz** [comment] 2021-03-09 20:06
> @glendaviesnz I was checking if this was affected by #29059, but I can't reproduce this one in `trunk`, would you be able to see if it's still happening?

It doesn't happen in trunk for me with the navigation block, but I just rebased the [Gallery PR](https://github.com/WordPress/gutenberg/pull/25940) and it still happens with that block - it has a slightly different block structure to the navigation block.

**Comment by talldan** [comment] 2021-03-11 02:32
Also reported on #29722, this also happens when deleting a Page List block from within the Navigation block.

Closing that one as a duplicate.

**Comment by talldan** [comment] 2021-03-11 02:57
The main cause seems to be that `useBlockProps` assumes that a block will always be defined, but when deleting, momentarily it isn't defined.

There seem to be a few cases where that's causing an issue:
- The type is undefined here, and attempting to access the title property throws an error - https://github.com/WordPress/gutenberg/blob/647a41cbab8e44e5ecd79af381f54cec080a3758/packages/block-editor/src/components/block-list/use-block-props/index.js#L86
- Looks like that also might be a problem here - https://github.com/WordPress/gutenberg/blob/647a41cbab8e44e5ecd79af381f54cec080a3758/packages/block-editor/src/components/block-list/use-block-props/use-block-default-class-name.js#L28

I think it's a similar issue to what Riad describes on this PR - https://github.com/WordPress/gutenberg/pull/29059.

**Comment by talldan** [comment] 2021-03-18 10:19
Also reported in #29958.

**Comment by paaljoachim** [comment] 2021-04-03 13:57
Using the Backspace/Del key might cause a block error.

I was just about to create an issue for what I believe is the same error. As I was in the Site Editor in TT1.
I have earlier mentioned the error for Glen in relation to the updated Gallery block. 

I am using WordPress 5.7.
Theme: TT1
Gutenberg plugin 10.3.1


https://user-images.githubusercontent.com/5323259/113480566-2a8f3b80-9495-11eb-8e6e-5f92a6285d81.mp4

**Comment by leeshadle** [comment] 2021-04-05 20:33
I'm not sure if this is related, but I'm getting an error after updating to Gutenberg versions 10.3 & 10.3.1:
"Uncaught TypeError: Cannot read property 'apiVersion' of undefined" 

I built a package that allows me to hot reload blocks during development.

During development, if a registered block's code changes I run unregisterBlockType().  I then immediately run registerBlockType() with the updated block's code.

I'm not sure what's causing the error, but it appears that the BlockListBlock component re-renders despite the block being unregistered?

<img width="1575" alt="Screen Shot 2021-04-05 at 1 20 21 PM" src="https://user-images.githubusercontent.com/557884/113623268-f6da2000-9612-11eb-9dda-3262c7273dcb.png">

**Comment by markhowellsmead** [comment] 2021-04-06 06:57
The error _Cannot read property 'apiVersion' of undefined_ is also thrown when trying to delete a block in the editor which is no longer registered.

**Comment by klokie** [comment] 2021-04-10 10:37
I'm seeing what seems to be the same issue presented when following the [recommended practice for replacing editor content](https://github.com/WordPress/gutenberg/issues/28488#issuecomment-767503834), i.e. using `resetBlocks()`.

**Comment by annezazu** [comment] 2021-05-06 19:23
Noting that I found this error when deleting the Featured Image Block inside a Query Block. This was found as part of the fifth call for testing for the FSE Outreach Program: 


https://user-images.githubusercontent.com/26996883/117354155-3ee89e80-ae6e-11eb-9b27-b71d1677fdda.mov

**Closed** 2021-06-14 09:02 UTC
Labels: [Feature] Block API, [Feature] Nested / Inner Blocks, [Priority] High, [Status] In Progress, [Type] Bug
