### ISSUE TITLE
Permalink: Not correctly displayed or editable until manually saved

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#11993] opened 2018-11-16 18:24 UTC
**Describe the bug**
When a title is added on a new post and the post auto-saves the Permalink is displayed in the default format (ex. /?p=ID) rather than the correct structure (/2018/11/16/example-title/) and is not editable until the post is manually saved. Originally noticed on 4.3 and still reproducible on 4.4.

**To Reproduce**
1. Go to '/wp-admin/post.php'
2. Add a title
3. Wait for auto-save to occur
4. Note the permalink uses the default, ID format rather than the correct permalink structure and is not editable.
5. Click save
6. The correct permalink is now shown and can be edited.

**Expected behavior**
To see the correct permalink and be able to edit it as soon as the title is set or when auto save occurs

**Screenshots**
![gutenberg permalink on auto save](https://user-images.githubusercontent.com/1900444/48639763-92b35480-e9a2-11e8-9aae-dfff10813a98.gif)

**Desktop (please complete the following information):**
 - OS: OS X 10
 - Browser Chrome 
 - Version 70.0.3538.77

**Comment by designsimply** [comment] 2018-11-16 18:46
Thank you for the report! Closing as a duplicate of #7129 and noting it's milestoned in WP5.0-RC.

**Closed by designsimply** 2018-11-16 18:46 UTC
Labels: [Component] Permalink, [Status] Duplicate, [Type] Bug

**Comment by kriskarkoski** [comment] 2018-11-16 20:41
Thanks Sheri, not sure how I didn't come across that one!
