### ISSUE TITLE
Theme colors can override default colors

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#36772] opened 2021-11-23 11:55 UTC
In testing https://github.com/WordPress/gutenberg/issues/36770 there's an issue with the theme palette that may override the default palette, creating weird interactions in the editor.

## How to reproduce:

- Use the empty theme and add a color with the same slug as one in the default palette. For example (note that I use red as the color value for debugging purposes, the important bit is that I'm using the `black` slug):

```json
{
	"version": 2,
	"settings": {
		"color": {
			"palette": [
				{
					"name": "Black",
					"slug": "black",
					"color": "red"
				}
			]
		},
```
- Go to the post editor and add a paragraph.
- Select the black color from the default palette.

Notice that the text color becomes red instead.

## Future

In the future, we may consider adding an explicit API for themes to override colors in the default palette.

**Comment by oandregal** [comment] 2021-11-23 12:32
We can also look at simplifying the merge algorithm, as presets no longer are merged but live under a different key (default, theme, or custom).

**Comment by carolinan** [comment] 2021-11-24 08:27
Duplicate of https://github.com/WordPress/gutenberg/issues/36360?

**Comment by oandregal** [comment] 2021-11-24 08:36
Thanks for sharing, Carolina. That's the same sort of problem (colors from different palettes having the same slug) but the conflict, in that case, comes from user colors. The fix for that was different and part of https://github.com/WordPress/gutenberg/pull/36674

**Comment by chthonic-ds** [comment] 2021-11-24 21:47
Is it possible to continue allowing theme colours to override the default ones if core palettes are disabled by the theme?

My use-case: I have a theme with "black" and "white" values that are not pure black and white. I originally set these up with custom colour names but later switched to overriding the default `--wp--preset--color--black` and `--wp--preset--color--white` properties. This allows the theme's patterns to have those colours set as defaults, while also allowing those patterns to persist across a theme change by inheriting the default black and white properties.

**Closed as completed** 2021-11-25 08:45 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Design Tools, [Feature] Colors

**Comment by oandregal** [comment] 2021-11-30 17:05
Hi @chthonic-ds thanks for raising that issue. I've created a draft PR to address it at https://github.com/WordPress/gutenberg/pull/37008
