### ISSUE TITLE
Initial view after install/activation: header is cutoff

### ISSUE THREAD

**Issue by jameslesliemiller** [WordPress/gutenberg#8930] opened 2018-08-13 16:10 UTC
## Issue Overview
I installed a fresh copy of WordPress, running the default Twenty Seventeen theme, and had not installed anything else. I clicked the button in the Try Gutenberg callout to install Gutenberg. Then I clicked the button to activate it. I was then delivered to a post editor screen where the header wrapped to a second line, and that second line was almost entirely cutoff until I clicked in the box.

## Steps to Reproduce (for bugs)
1. Download and install WordPress core
2. Click install Gutenberg button in the Try Gutenberg callout
3. Click activate plugin button in Gutenberg callout
4. See second line of header get cutoff

Safari 11.1.2
Mac OS 10.13.6
Screen Resolution 1680 x 1050
Web Browser Size 1579 x 931
Installed/activated browser extensions: Ghostery and 1Password

## Expected Behavior
The whole header block should be visible

## Current Behavior
Almost the entire second line of the header block is cutoff

## Screenshots / Video
<img width="1113" alt="screen shot 2018-08-13 at 10 47 34" src="https://user-images.githubusercontent.com/1000411/44043662-05cfb7a6-9ee9-11e8-9f93-b109e7c1df4f.png">

**Comment by designsimply** [comment] 2018-08-14 21:39
Thank you for commenting! Closing as a duplicate of #6897.

**Closed by designsimply** 2018-08-14 21:39 UTC
Labels: Blocks, Needs Testing, [Type] Enhancement
