### ISSUE TITLE
Remove Instagram Caption

### ISSUE THREAD

**Issue by theanikay** [WordPress/gutenberg#13023] opened 2018-12-19 16:55 UTC
Support Forums: https://wordpress.org/support/plugin/gutenberg

Does anyone have the CSS to remove the Instagram caption once embedded?

**Comment by manake** [comment] 2018-12-20 19:50
Instagram is changing its output sometimes (I know because I experienced this in my code once and it was recently in 2018).

**Comment by bph** [comment] 2019-01-01 18:00
Not sure that there is a CSS solution for this. It might needs to be enabled via the oEmbed provider for Instagram. Maybe @notnownikki has some input.

**Comment by notnownikki** [comment] 2019-01-02 09:12
I don't use Instagram so I'm not sure what the issue is here. Could you give me an example of a URL I can embed to see what parts you want to hide?

**Comment by bph** [comment] 2019-01-19 20:31
To get the instagram embed from their site the screen looks like this: 
![screen shot 2019-01-19 at 3 06 37 pm](https://user-images.githubusercontent.com/39980/51431880-f5bca400-1bfc-11e9-8df7-c0835ca04fa1.png)

the using the Custom HTML block you can post the photos on the site. 
Here is a view with and without the caption. (The caption with a lot of hashtags might make sense in the context of Instagram, when showing the image on the website, it might just be a little distracting.) 
![screen shot 2019-01-19 at 3 11 47 pm](https://user-images.githubusercontent.com/39980/51431891-2f8daa80-1bfd-11e9-80e1-d5ad90c76ded.png)

When using the embed block on of the WordPress editor it only give the full version of the photo entry. 
![screen shot 2019-01-19 at 3 31 10 pm](https://user-images.githubusercontent.com/39980/51432038-4fbe6900-1bff-11e9-9da9-c855961eada8.png)

**Comment by designsimply** [comment] 2019-02-12 19:22
> Does anyone have the CSS to remove the Instagram caption once embedded?

This is not possible because Instagram embeds are done in an `iframe` and because the `iframe` comes from a different domain that you do not have control over directly, you cannot apply CSS to it. Also see https://stackoverflow.com/q/217776/1100719

Closing because the answer for how to exclude a caption from an Instagram embed was provided by @bph (thank you!) with instructions for how to get the embed code from Instagram directly and showing how you can uncheck the "Include caption" and then use a Custom HTML block instead of an Embed or Instagram block.

**Closed by designsimply** 2019-02-12 19:22 UTC
Labels: [Block] Embed, [Type] Help Request

**Comment by brianrc** [comment] 2020-03-23 08:05
Found this online. Can do it by changing the URL parameter via a filter, but it only seems to work in the frontend, not the backend block editor. Any clue how to get this to work in the backend?

```
// Hide Instagram Captions
function custom_instagram_settings($code){
  if(strpos($code, 'instagr.am') !== false || strpos($code, 'instagram.com') !== false){ // if instagram embed
    $return = preg_replace("@data-instgrm-captioned@", "", $code); // remove caption class
    return $return;		
  }
return $code;
}
add_filter('embed_handler_html', 'custom_instagram_settings');
add_filter('embed_oembed_html', 'custom_instagram_settings');
```

**Comment by SamStrike0809** [comment] 2021-09-29 13:58
Hello, to solve this problem I suggest you to find something called 'data-instgrm-captioned' inside the blockquote.
It should be on the first line. Just delete remove that and you should be fine.
I repeat...just delete the text -  data-instgrm-captioned
