### ISSUE TITLE
Inconsistency: Button heights "Publish" and "Update"

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/gutenberg#61674] opened 2024-05-15 11:24 UTC
## What problem does this address?

The "Publish" button has a height of `32px`, while the "Update" button has a height of `36px`.

## What is your proposed solution?

Propose to set the same size for the buttons. I guess the correct size should be 32px, which is the same size of the icon on the right of the `interface-pinned-items` button.

![publish-update-buttons-2](https://github.com/WordPress/gutenberg/assets/83702259/fe6b6e96-3cc4-439f-9f18-f37956580b49)

**Comment by talldan** [comment] 2024-05-16 02:27
@marcarmengou In the latest version of the gutenberg plugin I see a 'Save' button instead of 'Update':
<img width="190" alt="Screenshot 2024-05-16 at 11 25 28 am" src="https://github.com/WordPress/gutenberg/assets/677833/0ae59507-17e2-4763-83b0-05c8fa6958be">

It seems to be the correct height, so perhaps this has been fixed.

I'll close the issue, but let me know if I'm reproducing it incorrectly.

**Closed as not planned by talldan** 2024-05-16 02:27 UTC
Labels: [Type] Bug, [Feature] Saving, [Status] Not Applicable
