### ISSUE TITLE
On paste formatting for RichText that has disabled formatting

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#28031] opened 2021-01-06 22:55 UTC
Hi, I am working with Gutenberg these days so I have found a bug related to the RichText component.
As it is mentioned in the documentation, it is possible to disable RichText formatting options like bold, italic, and so on. 

But there is a problem when I paste formatted text (from another text editor) they will be applied also in Gutenberg and as you might expect there is no formatting button to unbold them (for example).
I know "CTRL + SHIFT + V" can solve this (paste plain text) but it can be a good feature to not apply formatting on paste when: `formattingControls={[]}`.

**Comment by mirka** [comment] 2021-04-16 12:24
Duplicate of #18637?

**Comment by amir2mi** [comment] 2021-05-06 17:31
I found `__unstablePastePlainText` in the [Code block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/code/edit.js#L19) so it will solve the problem for now.

**Comment by Mamaduka** [comment] 2024-08-22 07:18
I'm going to close the issue.

## Why

* The `allowedFormats` prop works as designed. The setting controls format options displayed for a RichText instance, not the paste behavior.
* The `__unstablePastePlainText` can change the latter.

**Closed by Mamaduka** 2024-08-22 07:18 UTC
Labels: [Type] Enhancement, [Feature] Rich Text
