### ISSUE TITLE
Arrow Selection in Canvas Broken after Multiselect

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#65838] opened 2024-10-02 16:41 UTC
### Description

There are instances (not sure on all of them) where arrow selection is broken after multiselection. 

### Step-by-step reproduction instructions

- Add List block with two items
- Add paragraph
- With paragraph typing caret active, press shift + up arrow
- Try to us arrows on canvas (they won't work)

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1588546d-4e27-4384-b1a5-caae0b4f49a3

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by jeryj** [comment] 2024-10-02 16:41
@ellatrix - found a bad writing flow arrow nav issue after multiselect. It think multiselect is having some issues with where focus is applied in general. I'll look into it as well.

**Comment by ellatrix** [comment] 2024-12-24 09:40
I believe this is a duplicate of #63259.

**Closed as completed by ellatrix** 2024-12-24 09:40 UTC
Labels: [Type] Bug, [Focus] Accessibility (a11y), [Feature] Writing Flow
