### ISSUE TITLE
More tools & options popup flashes multiple times

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24735] opened 2020-08-22 07:54 UTC
**Describe the bug**
Clicking the _More tools & options_ menu when in Responsive Design Mode causes panel to flash open multiple times.

Vid: https://share.getcloudapp.com/6queYovy

**To reproduce**
1. Turn on Responsive Design Mode
2. Edit Page
3. Click More tools & option icon
4. See panel flash

**Expected behavior**
Panel shouldn't open mutiple times

**Editor version (please complete the following information):**
- WordPress version: [5.5]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
- OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

**Comment by talldan** [comment] 2020-08-25 01:33
@maddisondesigns What's 'Responsive Design Mode'?

**Comment by maddisondesigns** [comment] 2020-08-25 02:45
Responsive Design Mode is a tool in Firefox that allows you to easily change the viewport width, among other things. It's ideal for when you're developing/testing responsiveness. It's also useful when writing WordPress documentation and you need screenshots to be certain size.

example vid: https://share.getcloudapp.com/nOuk9dLk

more info: https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by talldan** [comment] 2020-08-25 04:07
Thanks for the quick reply. I just tested and noticed it tends to work ok whenever 'Enable Touch Simulation' is turned on, but not when that option is disabled. 

The CSS animation seems to be re-triggering, particularly when hovering over blocks, which is curious as there don't seem to be any changes to the DOM for the menu.

This could be a firefox bug seeing as the feature works in other browsers, though I couldn't find anything related in bugzilla:
https://bugzilla.mozilla.org/buglist.cgi?product=DevTools&component=Responsive%20Design%20Mode&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&resolution=---&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED

**Comment by talldan** [comment] 2020-12-09 04:20
Closing as per https://github.com/WordPress/gutenberg/issues/24748#issuecomment-741516457

**Closed by talldan** 2020-12-09 04:20 UTC
Labels: General Interface
