### ISSUE TITLE
Twitter Flickering

### ISSUE THREAD

**Issue by Imatoni** [WordPress/gutenberg#16576] opened 2019-07-13 11:32 UTC
**Describe the bug**
If I create two cols with Gutenberg and embed any Twitter tweet, there is a flickering on one of theme. Not always, but mostly. 

**To reproduce**
![ezgif-2-15a9beb3d5fe](https://user-images.githubusercontent.com/46871406/61171045-307f1380-a572-11e9-86ad-2733d4a86601.gif)
1. create two cols
2. embed any tweet link in each cols

**System/Browser**
mac, chrome Version 75.0.3770.100

**Additional context**
WordPress 5.2.2

**Comment by ellatrix** [comment] 2019-11-20 13:17
Thanks for the report! This is a duplicate of #15416.

**Closed by ellatrix** 2019-11-20 13:17 UTC
Labels: Needs Testing, [Block] Embed, [Type] Bug
