### ISSUE TITLE
Inserter UI doesn't appear on selected blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#9437] opened 2018-08-29 15:59 UTC
**Is your feature request related to a problem? Please describe.**
When hovering over a selected block, all the UI elements appear as my mouse gets closer to them. Except the inserter UI element. That never appears. I have to deselect the block which means clicking outside the block, then re-hover over that block to get the inserter UI to appear.

![add- block](https://user-images.githubusercontent.com/617986/44799826-b7e5b300-ab69-11e8-9496-8c801022510e.gif)

**Describe the solution you'd like**
I'd like the inserter `+` to appear even on selected blocks just like all the other UI elements do.

**Comment by designsimply** [comment] 2018-08-29 16:30
Closing as a duplicate of #7519 and noting the prior explanation given:

> This was changed intentionally in #7220 to better handle cases where the sibling inserter would be covered by the toolbar.

Please reply back here if you'd like to re-open this issue to discuss an alternate solution or design proposal!

**Closed by designsimply** 2018-08-29 16:30 UTC
Labels: [Component] Inserter, [Type] Enhancement
