### ISSUE TITLE
Incorrect core data permissions in site editor

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#57837] opened 2024-01-14 23:58 UTC
## Description

`canUser( 'update', 'settings' )` is `false` in site editor but `true` in post editor for administrator. I discovered this when trying to set a site logo in the site editor.

## Example

Sign in as administrator.

In the site editor, you _cannot_ select a site logo. (incorrect)

<img width="1280" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/b52cfb55-4254-41a5-b0bc-c23ef5096436">

However, in the post editor, you _can_ select a site logo. (correct)

<img width="1280" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/c162bb79-786d-4cf3-aa19-8f7b0226ce29">

**Comment by t-hamano** [comment] 2024-01-20 05:44
I was unable to reproduce this problem with a clean installed WordPress (`6.5-alpha-57319`) and the latest Gutenberg. Are there any other steps required?

![site-logo](https://github.com/WordPress/gutenberg/assets/54422211/673b3aa1-8889-4be1-a698-9e1380fb6ec8)

**Comment by t-hamano** [comment] 2024-09-11 02:36
I'm unable to reproduce this issue so I would like to close it.

If you have any steps to reproduce it please let me know.

**Closed as not planned by t-hamano** 2024-09-11 02:36 UTC
Labels: [Type] Bug, [Package] Core data, [Feature] Site Editor
