### ISSUE TITLE
Widgets: HTML block is formatted using `autop` and has its attributes removed

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#33832] opened 2021-08-03 00:13 UTC
### Description

In the new widget editor, Custom HTML widget blocks can get (additional) paragraph and line break tags.

Originally reported by jim5471 on [Trac #53778](https://core.trac.wordpress.org/ticket/53778)

### Step-by-step reproduction instructions

1. Go to Dashboard > Appearance > Widgets.
2. Insert a Custom HTML Block into the footer and insert this code:
```
<div><p>some text</p>
<a href="http://www.test.com">link text</a>
</div>
<svg height="90" width="200">
  <text x="10" y="20" style="fill:red;">Several lines:
    <tspan x="10" y="45">First line.</tspan>
    <tspan x="10" y="70">Second line.</tspan>
  </text>
</svg> 
```
3. Update and check it appears on the webpage and is correct.
4. Go back to Dashboard and then back to Appearance > Widgets.
5. Observe the Custom HTML code has additional paragraph and line break tags.

Firefox:
```
<div>
<p>some text</p>
<p><a href="http://www.test.com">link text</a>
</p></div>
<p><svg height="90" width="200"><br></br>
  <text x="10" y="20" style="fill:red;">Several lines:<br></br>
    <tspan x="10" y="45">First line.</tspan><br></br>
    <tspan x="10" y="70">Second line.</tspan><br></br>
  </text><br></br>
</svg></p>
```
Edge/Chrome:
```
<div>
<p>some text</p>
<p><a href="http://www.test.com">link text</a>
</p>
</div>
<p><svg height="90" width="200"></svg><br>
  <text x="10" y="20" style="fill:red;">Several lines:<br>
    <tspan x="10" y="45">First line.</tspan><br>
    <tspan x="10" y="70">Second line.</tspan><br>
  </text>
</p>
```
6. Change another widget and update.
7. Go back to Dashboard and then back to Appearance > Widgets.
8. In Chrome and Edge, the code stays the same as in step 5. In Firefox, though, the Custom HTML code changes again:
```
<div>
<p>some text</p>
<p><a href="http://www.test.com">link text</a>
</p>
</div>
<p><svg height="90" width="200"><br></br></svg><br><br>
  <text x="10" y="20" style="fill:red;">Several lines:<br><br><br>
    <tspan x="10" y="45">First line.</tspan><br><br><br>
    <tspan x="10" y="70">Second line.</tspan><br><br><br>
  </text><br><br><br>
</p>
```

### Expected Behavior

The Custom HTML block widget contents should remain exactly as entered.

### Current Behavior

The block widget has `autop` formatting (from @wordpress/autop).

### WordPress Information

WordPress 5.8
Twenty Twenty-One theme
no plugins
local installation with PHP 7.3.21

### Gutenberg Information

Gutenberg not activated

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Device Information

Desktop browsers:
Google Chrome 92.0.4515.107 (64-bit) - Incognito mode
Mozilla Firefox 90.0.2 (64-bit) - Private window
Microsoft Edge Version 92.0.902.62 (64-bit)

### Operating System Information

Windows 10 Home 20H2 19042.1110

Is there an existing issue for this?

- [X] I have searched the existing issues

Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

**Comment by talldan** [comment] 2021-08-03 07:00
I haven't had a chance to test this yet, but I wonder if it's related to https://github.com/WordPress/gutenberg/pull/33164.

There's this case where autop is applied, but I don't think it was supposed to happen for something intentionally inserted as the HTML block:
https://github.com/WordPress/gutenberg/blob/a3445ccd3a2f16d923b1bc2873159d8f0cecde01/packages/blocks/src/api/parser.js#L499-L504

It might be an unexpected side-effect.

**Comment by azaozz** [comment] 2021-08-03 23:33
Yes, the handling of `freeformContentFallbackBlock` is the cause, thanks @talldan. Happens because on the widgets settings screens the fallback block is set to Custom HTML.

The assumptions there (from 4 years ago) are somewhat incorrect. Autop might be needed only when editing posts, not in any other case. The removal of paragraph tags  (the `pre_wpautop` part) was applied only on the content from the old post editor. 

Seems the fix would be to move the decision outside of the parser, perhaps pass `autop = true|false` in the settings. Then autop can be applied only when editing posts. Alternatively (to keep this hard-coded) autop should be applied only on the new Edit Post screen or perhaps only when the Classic block is the fallback (the default).

Another bug that needs fixing (imho) is to apply autop only on `undelimited content`, i.e. when actually using the `freeformContentFallbackBlock`. Currently autop is applied to all blocks that are set as fallback, regardless of whether they are actually used as fallback.

Looking at usage (https://wpdirectory.net/search/01FC72F5R2CC5Q15W9M1GYHEG2), there are only two plugins that have `setFreeformContentHandlerName` but seems it is in their dependencies, not used to change the default block. Seems this is virtually unused feature.

**Comment by azaozz** [comment] 2021-08-12 22:00
Been looking at this for a while, see several bugs and inconsistencies with how FreeformContentHandler is used. For this particular case the most straightforward fix seems to be to run the FreeformContent through wpautop only when editing a post as `pre_wpautop` was applied in the old editor only when saving posts.

**Comment by mcsf** [comment] 2021-08-20 08:47
> For this particular case the most straightforward fix seems to be to run the FreeformContent through wpautop only when editing a post as `pre_wpautop` was applied in the old editor only when saving posts.

I'll defer to others w.r.t. how many editing contexts should be affected by this fix, but I too think that the solution is to disable autop _at least_ in the Widget editor. Doing the same in nascent block editors, like Nav and Site, might be a step towards phasing out autop (perhaps around 2050 AD).

**Comment by draganescu** [comment] 2021-09-13 14:23
So I've been through the conversation here and in #34023 and I don't have a clear picture how could this be fixed. I understand that we need:

1. a way to disable `wpautop` for some editors (widgets, nav, site)
2. a way to disable `wpautop` for some `freeform` handlers

Can we filter parser "settings" and then pass a setting to not run `wpautop` or does it have to be more complicated? Sorry for asking if the answer is here :D but I couldn't grasp the summary from the conversations.

**Comment by talldan** [comment] 2021-09-30 09:44
There's a discussion in slack that the core html block is also not saving its comment delimiters in the widgets editor. (https://wordpress.slack.com/archives/C01D71823PB/p1632988086021300)

I think it's likely caused by the same issue, since this is the same behavior the classic block has in the post editor.

I'm not fully up-to-date on the entire story. Could a solution involve passing some more information to setFreeformContentHandler? (https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/index.js#L103)

e.g. `setFreeformContentHandler( 'core/html', { autop: false, commentDelimiters: true } );`

**Comment by azaozz** [comment] 2021-09-30 17:25
> I think it's likely caused by the same issue

It's not an issue, it is a "feature" that needs fixing :) 
Yes, as the html block is the "freeform handler" it is removed when saving so its content becomes "freeform" again. This seems to be the (early) back-compat behaviour made for the classic block, to support a specific edge case: editing an old post with the block editor, and using only one classic block (yeah, this effectively bypasses most of the block editor's features).

Thinking this has outlived its usefulness and should be changed/removed, i.e. the freeform block boundaries should not be removed on saving. Perhaps an exception can still be made but only when the classic block is the freeform-handler, and only when editing posts (but will look at/think a bit more if it's needed).

> Could a solution involve passing some more information to setFreeformContentHandler?

It could but seems it will only be a temporary patch-up. Better would be to (finally) update and fix how freeform content is handled. For that there are few requirements/considerations:

- Autop doesn't belong in the block editor. It is only needed for the freeform content when editing (very) old posts that have their `<p>` tags stripped. To fix this Gutenberg will need context about what is being edited.
- The two types of freeform content: loose HTML between blocks and content without blocks should be saved with the blocks boundaries when edited in the block editor. There's no point to strip the block boundaries. That may have been somewhat nice when Gutenberg was merged to core 3-4 years ago, but not any more. This will also help with phasing out the remaining use of `autop` and `removep`.
- An "automated" or "semi-automated" solution is needed for removing white space/line breaks between block boundaries, see https://github.com/WordPress/gutenberg/issues/34023. It cannot be part of the parser but line breaks were added programmatically to the user's content, and they should be removed in a consistent way. That removal should work well regardless of the freeform-handler block, etc.

**Comment by manooweb** [comment] 2021-09-30 18:14
> It's not an issue, it is a "feature" :) 

Are you sure? 😉

With older WordPress version we were able to add new field (attribute) to all the widgets to be able to change their behaviour for example.
With blocks now, we found that we can use block attribute to do the same thing. It works fine for all the core block except core/html.

Note that the same block also works fine with the post block editor.

**Comment by azaozz** [comment] 2021-09-30 18:26
> It works fine for all the core block except core/html.
> Note that the same block also works fine with the post block editor.

Yes, the reason it fails is that the html block is used as the freeform-handler, i.e. it is "special" :) 
The feature here is that the freeform-handler block is removed on saving (including any attributes). This is done to keep the freeform html that existed before loading the post in the editor, and save it as "freeform" again. Fixing how that works will fix several "gotcha's" there.

**Comment by flexerd** [comment] 2021-11-04 15:11
Just noticed this happening, but only in widgets and not in the Custom HTML block in Gutenberg editor.
Is this on anyone's radar?

In case anyone gets to this thread adding this code to theme functions.php is a temporary fix.
//Disable p and br in HTML widget
remove_filter('widget_custom_html', 'wpautop');

**Comment by webprom** [comment] 2021-12-13 18:38
> remove_filter('widget_custom_html', 'wpautop');

unfortunately, it's not working for me :(

**Comment by flexerd** [comment] 2021-12-13 19:47
> > remove_filter('widget_custom_html', 'wpautop');
> 
> unfortunately, it's not working for me :(

Try this remove_filter('widget_custom_html', 'wpautop' , 10, 3 );

This really should be fixed, if it's not in the pipeline IMO anyway.

**Comment by webprom** [comment] 2021-12-13 20:20
> > > remove_filter('widget_custom_html', 'wpautop');
> > 
> > 
> > unfortunately, it's not working for me :(
> 
> Try this remove_filter('widget_custom_html', 'wpautop' , 10, 3 );
> 
> This really should be fixed, if it's not in the pipeline IMO anyway.

unfortunately, no luck :( thanks for the help!

**Comment by noisysocks** [comment] 2022-02-15 05:41
It makes intuitive sense to me that the widgets screen should not have a freeform handler during _parsing_, since we know that the underlying storage mechanism (widgets) can always be transformed into a list of valid non-freeform blocks. That is, there shouldn't ever be anything in between the `<!-- wp: -->` delimiters in the widgets screen.

But we do need a freeform handler during _pasting_, so that non-block markup is handled when pasted into the widgets editor. See https://github.com/WordPress/gutenberg/issues/33097.

Perhaps we need to split `setFreeformContentHandler` up.

```js
setParseFreeformContentHandlerName( null ); // Ignore non-block content during parse.
setPasteFreeformContentHandlerName( 'core/html' ); // Turn non-block content into a HTML block during paste.
```

**Comment by noisysocks** [comment] 2022-02-15 05:50
A related issue to this is that we strip all of the HTML block's metadata when saving. See https://github.com/WordPress/gutenberg/issues/35266.

**Comment by Z3r0XG** [comment] 2022-07-21 23:21
Can someone provide the latest "up-to-date" workaround for fixing this issue?  I can't do a Custom HTML block for widget areas without coming back and seeing the code full of `<p>` and `<br>` tags.

**Comment by talldan** [comment] 2022-07-22 09:08
I had a go at fixing this in #42623. 

> Perhaps we need to split setFreeformContentHandler up.

I had a look at this option @noisysocks, but the parser doesn't know if it's currently handling a paste or a normal parse of content, and it seems like a big refactor of some critical code to make that happen. 🤔

**Closed as completed** 2022-07-25 05:56 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Paste, [Feature] Widgets Screen, [Feature] Widgets Customizer

**Comment by Marielle83** [comment] 2023-03-23 10:38
I'm getting this issue in WordPress 6.2 RC2, so not sure if this bug may be back for 6.2.

**Comment by talldan** [comment] 2023-03-27 03:57
@Marielle83 I tested and wasn't able to reproduce the problem. Could you share which steps you're following to cause the issue and which editor you're using (widgets or site editor?)

**Comment by Marielle83** [comment] 2023-03-27 10:48
@talldan I'll try, let me know if you need a better explanation.

WordPress version: 6.2 RC4
No plugins installed, using Twenty Twenty-Three Theme, but happens with any block theme.

Open the Site Editor and edit a template, for example Page template. Insert Custom HTML block somewhere and put in some HTML. Save and refresh the page (or save and exit Editor then come back to edit the template) The HTML now has added `<p>` and `<br>` tags added.

I'll add some screenshots as an example showing it also happens if you add scripts in the Custom HTML block. Probably wouldn't need the Custom HTML block for this, but it's just an example.

[Intact HTML](https://i.imgur.com/oj0FVy1.png)
[Destroyed HTML and script](https://i.imgur.com/mdI8SQK.png)

Expected result should be the HTML and script being intact, without added tags.

The issue isn't currently in 6.1.1, but if using the Gutenberg development plugin (the one that says "This is the development plugin for the block editor, site editor, and other future WordPress core functionality.") in 6.1.1 the issue is there though and I can reproduce it using the steps above. The issue was fixed before [https://github.com/WordPress/gutenberg/pull/42623](https://github.com/WordPress/gutenberg/pull/42623), but seems to be back in newer versions of Gutenberg.

A bug report was done last week [https://github.com/WordPress/gutenberg/issues/49166](https://github.com/WordPress/gutenberg/issues/49166)

**Comment by talldan** [comment] 2023-03-27 11:13
Thanks for the extra details, @Marielle83.

This issue and the fix https://github.com/WordPress/gutenberg/pull/42623 were just for the Widget Editors (in non-block themes).

The site editor issue sounds like a different bug. Good to see it's tracked in https://github.com/WordPress/gutenberg/issues/49166.

**Comment by Marielle83** [comment] 2023-03-27 11:47
Oh I thought they were the same, thank you for clarifying.
I'll add my steps to the new bug report too I think.
