### ISSUE TITLE
Publish confirmation panel doesn't close after publishing

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4560] opened 2018-01-18 01:55 UTC
## Issue Overview
After publishing a page, the Publish sidebar panel remains open. This is really confusing as it's showing the following text;

_**Are you ready to publish?**
Here, you can do a last-minute check up of your settings below, before you publish._

![gutenberg-publishpanel](https://user-images.githubusercontent.com/2078245/35076753-01f849e2-fc4e-11e7-993e-7472ff0f5cfa.png)

This panel should close as soon as the page is published.

## Steps to Reproduce (for bugs)
1. Create new page
2. Insert content
3. Click Publish
4. Click Publish
5. Verify that the publish panel remains open

## Expected Behavior
The publish panel should close as soon as the page is published. Asking if I'm ready to publish, after I've just published, is wrong and confusing

## Current Behavior
Publish panel remains open with confusing message

## Related Issues and/or PRs
Please note that this is a different issue to the one mentioned in #4470. That is an issue with the panel remaining after creating a new page. This is an issue with the panel remaining open after publishing the current page.

_Firefox Quantum 57.0.4 (64-bit)
Gutenberg 2.0.0
WordPress 4.9.2_

**Comment by youknowriad** [comment] 2018-01-18 07:36
This area is meant for post-publish information like "preview link", "social media" sharing options etc... I think that's intended.

**Comment by maddisondesigns** [comment] 2018-01-18 07:50
Eww I hope not. That'll be really annoying if we have to constantly close this every single time. Gutenberg is already making the Publishing process more difficult by insisting on having that two-step publishing process. Adding this in as yet another step, would be really, really annoying and frustrating. At the very least if you don't remove it, that message needs to be changed/removed, because that's extremely confusing. Gutenberg is supposed to be making things easier for end users, not more cumbersome and time consuming.

**Comment by youknowriad** [comment] 2018-01-18 15:32
After long discussions, the design of this panel has been discussed and agreed on in #3496. I understand that it may pointless for you but the majority thinks the post publish panel is something important to have. That doesn't mean this can't be iterated in the future if there's further evidence on this being an issue.

Closing for now

**Closed by youknowriad** 2018-01-18 15:32 UTC
Labels: [Type] Question

**Comment by maddisondesigns** [comment] 2018-01-20 02:37
@youknowriad So, you're seriously going to leave that message "Are you ready to publish?
Here, you can do a last-minute check up of your settings below, before you publish.", after the page is already published??

**Comment by youknowriad** [comment] 2018-01-20 08:20
@maddisondesigns If you still see this message after the page has been published, then it's a bug. Can't see it myself

**Comment by maddisondesigns** [comment] 2018-01-21 01:35
@youknowriad I provided a screenshot when I raised the issue, that shows exactly this!

**Comment by youknowriad** [comment] 2018-01-21 07:43
@maddisondesigns but I can't fix the bug if I can't reproduce. If you would provide more information, that would be great. Do you see JS errors?

**Comment by maddisondesigns** [comment] 2018-01-21 23:59
I've just tried publishing a few more pages and it's not showing that message now. If you want to close this, that's fine. People are going to constantly experience these random issues though and they're going to be ignored because they can't be reproduced consistently. This thing is so horribly inconsistent and unstable!
