### ISSUE TITLE
Query block pagination (prev/next links) use non standard implementation.

### ISSUE THREAD

**Issue by rmorse** [WordPress/gutenberg#54423] opened 2023-09-13 12:17 UTC
### Description

All pagination functions in WP have historically had a filter to modify the URL of the pagination link (for adding or removing query args for example) however the prev/next links do not have a filter as they are not using a WP function to generate it.

[Query Pagination Numbers](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination-numbers/index.php) looks to be ok, it uses `paginate_links()`

However [Query Pagination Next](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination-next/index.php) and [Query Pagination Previous](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination-previous/index.php) blocks use some [non standard implementation of creating the link](https://github.com/WordPress/gutenberg/blob/a6a28094e5dfa46fb9cae68fbc2b69fdd0b08beb/packages/block-library/src/query-pagination-next/index.php#L56-L60), and this means we can't modify the URLs using filters.

### Step-by-step reproduction instructions

Check the code for prev/next pagination:
```
$content = sprintf(
	'<a href="%1$s" %2$s>%3$s</a>',
	esc_url( add_query_arg( $page_key, $page + 1 ) ),
	$wrapper_attributes,
	$label
);
```
Here the URL is passed in to the `sprintf` so there is no way to modify it.

My guess is this is an issue because we are not using the usual rewrites for page links such as `/page/1` for query blocks so we're probably not able to use the classic WP functions for this.

### Possible solutions

1. We could expose this URL and filter it:
```$url = apply_filter( 'get_pagenum_link', esc_url( add_query_arg( $page_key, $page + 1 ) ) );```
This means the regular pagination filter `get_pagenum_link` would be fired and would keep it inline with  all the other pagination links.

2. An alternative would be to create another hook specifically for the block for filtering the URL.

3. We could update the original WP functions `get_next_posts_link()` and `get_prev_posts_link()` so that they accept an arg to specify the format (like `paginate_links()` does) ,

### Screenshots, screen recording, code snippet

-

### Environment info

- latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-09-13 18:25
Nearly positive this is a duplicate of https://github.com/WordPress/gutenberg/issues/48814 Can you confirm? If so, I'll close this out and we can keep the discussion there.

**Comment by rmorse** [comment] 2023-09-13 18:57
> Nearly positive this is a duplicate of https://github.com/WordPress/gutenberg/issues/48814 Can you confirm? If so, I'll close this out and we can keep the discussion there. 

Yup 100%, thanks. I didn't find that one unfortunately.

Just to confirm it's an enhancement and not a bug?

I feel like it's a bug as it's breaking behaviour/conventions.

Thanks 🙏

**Comment by annezazu** [comment] 2023-09-13 19:54
Awesome. I'll close this out. Right now, it's listed as an enhancement as it's around adding a filter in but I do think it likely lives between bug/enhancement land (which we don't have a good marking for).

**Closed as completed by annezazu** 2023-09-13 19:54 UTC
Labels: [Type] Enhancement, [Status] Needs More Info, [Block] Query Pagination
