### ISSUE TITLE
Toolbar interfering with editor messages

### ISSUE THREAD

**Issue by dartiss** [WordPress/gutenberg#5174] opened 2018-02-21 11:50 UTC
Now, I'm not sure if this is Jetpack to blame or an issue with Gutenberg, but I was greated with the following today...

![screen shot 2018-02-21 at 11 45 33](https://user-images.githubusercontent.com/14928971/36478560-1cb57b28-16fd-11e8-9b65-0be3eb319d76.png)

The Jetpack message is appearing under the toolbar. Thankfully I can just click on the message dismissible icon to get rid of it. None-the-less, this is an awkward UI issue.

I'm on WordPress 4.9.4 and Gutenberg 2.2.0.

**Comment by jasmussen** [comment] 2018-02-21 11:51
This will be closed on #4811.

**Comment by Soean** [comment] 2018-02-21 14:35
@dartiss thanks for your report. This ticket is a duplicate of #3395, so I close this issue.

**Closed by Soean** 2018-02-21 14:35 UTC
Labels: [Type] Bug
