### ISSUE TITLE
Post editor: remove ability to drag metabox outside of scope of the editor

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#48999] opened 2023-03-10 17:47 UTC
### Description

Expected behaviour was moving the metabox to the sidebar. Instead I got this weird behavior. If we can't move it, why are we able to drag it to the side like this?

### Step-by-step reproduction instructions

1. Install any theme
2. Install the plugin The SEO Framework
3. Drag the meta box

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/118618474/224387248-992e5f27-8704-4e1e-bf39-303bf9a0fc42.mov

### Environment info

Using WordPress 6.2-beta4-55454, Gutenberg 15.3.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-03-14 03:40
Thanks so much for reporting. Updated the title to be a bit more descriptive and noting I can replicate with just WordPress 6.2 RC1 along with WordPress 6.1.1. This also seems to be a duplicate of this prior issue: https://github.com/WordPress/gutenberg/issues/17432 As a result, I'm going to close this out as a duplicate.

**Closed as not planned by annezazu** 2023-03-14 03:40 UTC
Labels: [Type] Bug, [Feature] Meta Boxes
