### ISSUE TITLE
How-To: Structured Data with Gutenberg

### ISSUE THREAD

**Issue by Luehrsen** [WordPress/gutenberg#4575] opened 2018-01-18 14:47 UTC
We are currently prepping a new project which we want to do with Gutenberg. 

Part of the project is a database of some sort, with structured data at it's heart. I understand the nature of 'templates' and 'fixed templates', but I'm not yet sure about the proposed UX and the implementation. 

Let's say we want to create a database of books. The books shall be searchable, and queryable. I would quickly do this to structure the content. 

- Book title => post_title
- Book description => post_content
- Publisher => taxonomy
- Author => taxonomy
- Release Date => post_meta
- Review Score => post_meta
- Testimonials => post_meta
- Shop URLs => post_meta

Due to the nature, that a lot of the post_meta described here is more content than administrative, I would want to keep the resulting interface somewhere in the editor, not buried in the sidebar.

What I tried to do is to create a custom block as an interface for the post meta. That resulted in two questions: 

**How do I save contents of a block as post_meta?**

**How do I force a certain block to either the start or the end of the editor, without interfering with the rest of the content?**

**Comment by youknowriad** [comment] 2018-01-18 15:03
> How do I save contents of a block as post_meta?

See here https://wordpress.org/gutenberg/handbook/block-api/attributes/#meta

> How do I force a certain block to either the start or the end of the editor, without interfering with the rest of the content?

You can create a locked template see https://wordpress.org/gutenberg/handbook/templates/
But right now, you want be able to add a "free" area where you can just add any block, but this will come when nesting is ready which makes this issue a duplicate of #4477

**Closed by youknowriad** 2018-01-18 15:03 UTC
