### ISSUE TITLE
Scripts: Problem with build command when using multiple blocks scaffolded with create block

### ISSUE THREAD

**Issue by S-Blank** [WordPress/gutenberg#27969] opened 2021-01-04 11:52 UTC
Good day,

I have been having problems developing Gutenberg blocks for days.

I use ‘@wordpress/create-block’ to build my blocks. As long as I build the blocks with ‘npm start’, the blocks work fine and without any error messages, but as soon as I use ‘npm run build’ for building, I get problems, especially if other custom blocks of mine are already installed (the new block or other blocks can no longer be found in the editor, or throw an error message: ‘Object(…) is not a function at anonymus’). Sometimes renaming the new block and clearing the browser cache / website cache helps, sometimes not.
If I then build the block again via ‘npm start’, everything works again.

Does anyone have an idea what this could be?

Many thanks in advance for your help.

Many greetings
Simon

**Comment by skorasaurus** [comment] 2021-01-04 19:07
Could you describe more 'Object' error by including its entire content of the error message? 

This sounds similar to #23607 and #24321 but I don't know if they're a duplicate of what you're experiencing.

**Comment by gziolo** [comment] 2021-01-04 22:46
@skorasaurus, thank you for cross linking with existing issues. 

It's very likely it's the same bug with webpack v4 that was fixed in webpack v5. I tried today to upgrade `@wordpress/scripts` that Create Block uses to the latest version of webpack but it looks like the plugin ecosystem needs some more time to upgrade. I plan to propose a fix similar to what @ocean90 shared in comments and include it in the next npm release hopefully later this week.

**Comment by timnolte** [comment] 2021-01-05 04:04
@S-Blank have you tried the solution as explained here: https://github.com/WordPress/gutenberg/issues/23607#issuecomment-692374275

**Comment by S-Blank** [comment] 2021-01-05 10:03
I have, as described in [#23607 (comment)](https://github.com/WordPress/gutenberg/issues/23607#issuecomment-692374275), added a webpack.config.js with the following code in all my blocks.

![image](https://user-images.githubusercontent.com/76944718/103633005-69b8f980-4f45-11eb-92a0-22755517b241.png)




Now it works for me. Thank you very much for your help.

**Comment by gziolo** [comment] 2021-01-05 10:06
Fix is almost ready to land in https://github.com/WordPress/gutenberg/pull/27985 :)

**Closed** 2021-01-05 10:35 UTC
Labels: [Package] Scripts, [Status] Needs More Info, [Type] Bug
