### ISSUE TITLE
Floating an inner block collapses the outer block.

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#16958] opened 2019-08-08 07:47 UTC
**Describe the bug**
Floating an inner block collapses the outer block.

**To reproduce**
1. Add a group block
2. In the group block add a button block
3. Align the button to right
4. Observe the bug

**Expected behavior**
The outer blocks should not collapse if the inner blocks have a float, but instead wrap them as a container.

**Screenshots**
![image](https://user-images.githubusercontent.com/107534/62684661-d125ef00-b9c9-11e9-9cd2-4a5003cc138c.png)

Related: #13681

**Comment by draganescu** [comment] 2020-03-27 16:52
This is still a problem in latest Gutenberg.

**Comment by youknowriad** [comment] 2020-04-10 23:28
I think that's expected behavior, that's just how float works. We have an issue somewhere about adding an option to "clear" floats.

**Comment by youknowriad** [comment] 2020-04-10 23:29
So I'm wondering if we should just close this as duplicate of #10299

**Comment by roman02** [comment] 2020-08-14 19:40
I don't think that floats should be used for aligning horizontally. At least, not for aligning buttons. Gutenberg adds a wrapper (with the class of wp-block-buttons) when a button is added. Using text-align on the wrapper aligns the button and avoids container collapse.

Using flex box is another option. See how Oxygen page builder handles this!

**Comment by draganescu** [comment] 2020-08-18 14:48
@youknowriad yes, this is how floats work, but the result being the one in my screenshot is not a good user experience. Regular users do not know how floats work and all they see is the container is botched :)

**Comment by gwwar** [comment] 2021-04-08 18:36
I'm unable to reproduce alignment issues, now that a button is usually inserted with a buttons block. Do we still need this one @draganescu ?

<img width="736" alt="Screen Shot 2021-04-08 at 11 33 35 AM" src="https://user-images.githubusercontent.com/1270189/114079138-a9ea8980-985e-11eb-9c73-8abad71b8850.png">

**Comment by paaljoachim** [comment] 2021-04-08 18:49
Testing with WordPress 5.7. Twenty Twenty One. Gutenberg plugin 10.3.2.

I did notice this behavior:
Justify right then clicking the most right button moves the toolbar outside the canvas/layout area.


https://user-images.githubusercontent.com/5323259/114080617-e0022a80-98ab-11eb-91e3-54e6b83fdfcf.mp4

**Comment by annezazu** [comment] 2021-05-18 03:55
Closing this out since I can't replicate both the original issue or what Paal described above in 10.6.1:

https://user-images.githubusercontent.com/26996883/118587766-638c2280-b75a-11eb-9b94-c4126f9096d7.mov

If that's incorrect, feel free to reopen! If it's related to the latter issue, I would recommend commenting here: https://github.com/WordPress/gutenberg/issues/30398 as they seem to be related.

**Closed by annezazu** 2021-05-18 03:55 UTC
Labels: [Block] Group, [Block] Media & Text, [Type] Bug

**Comment by paaljoachim** [comment] 2021-05-18 22:12
Hey Anne @annezazu 

I just retested with WordPress 5.7. Twenty Twenty One. Gutenberg plugin 10.6.1.

It looks alright now. I am not seeing the error I did back in April.

![Screen Shot 2021-05-19 at 00 13 08](https://user-images.githubusercontent.com/5323259/118729916-0619d380-b837-11eb-87ff-7cc227ed99ac.png)

**Comment by annezazu** [comment] 2021-05-18 22:16
Thank you for retesting, friend <3
