### ISSUE TITLE
Block Widgets in Customizer: Editing takes them to widget screen but applying focus would be helpful.

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26243] opened 2020-10-17 07:34 UTC
**Is your feature request related to a problem? Please describe.**
When you click 'Edit' on a Block widget in the Customizer > Widgets screen you're taken to the new widget screen. 

**Describe the solution you'd like**
It would be nice if it placed your focus directly onto the block you went to 'Edit'.

**Comment by draganescu** [comment] 2021-02-18 15:17
Howdy! Thanks for opening this issue. This is the entire scope of the work for having an embeddable editor in the customizer. Will close this as a duplicate of 27343

**Closed by draganescu** 2021-02-18 15:17 UTC
Labels: [Feature] Widgets Screen, [Type] Enhancement
