### ISSUE TITLE
IE11: Block Toolbar Misalignment with Media Replace Dropdown

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#21389] opened 2020-04-03 20:35 UTC
**Describe the bug**
After switching the Image block's Edit Image button to a Replace button with dropdown options in [PR 16200](https://github.com/WordPress/gutenberg/pull/16200), the buttons do not line up again in Internet Explorer. 

The stacking occurs in (at least) the Image, Video and Audio blocks.

**To reproduce**
1. Add or edit a post using Internet Explorer 11.
2. After inserting an image into the Image block, click on the image (block).
3. View the row of toolbar buttons, with three of them stacked.
4. Add a video or audio clip to the Video or Audio block, and see two buttons stacked.

**Expected behavior**
The toolbar buttons should appear in a single row.

**Screenshots**
Image block in WordPress 5.4, **without** Gutenberg plugin:
![Image block buttons are stacked instead of in a row in WordPress 5.4](https://user-images.githubusercontent.com/17100257/78399795-34007200-75bb-11ea-86e1-ca1952c16215.png)

Image block in WordPress 5.4, with Gutenberg plugin 7.8.1:
![Image block buttons are also stacked with Gutenberg plugin, with newer styling](https://user-images.githubusercontent.com/17100257/78399955-7c1f9480-75bb-11ea-81f8-3a1ac1e27291.png)

Audio block in WordPress 5.4, with Gutenberg plugin:
![Audio block buttons also stack](https://user-images.githubusercontent.com/17100257/78401782-19c89300-75bf-11ea-8440-233f3161cb2a.png)

**Desktop**
 - OS: Windows 10
 - Browser: Internet Explorer 11
 - WordPress version: 5.4
 - Gutenberg version: 7.8.1

**Comment by sabernhardt** [comment] 2020-04-03 20:36
The alignment seems to work with **all** browsers set to `inline-flex`.
```
.block-editor-block-toolbar__slot {
    display: inline-flex;
}
```

**Comment by ambienthack** [comment] 2020-11-11 17:46
> The alignment seems to work with **all** browsers set to `inline-flex`.
> 
> ```
> .block-editor-block-toolbar__slot {
>     display: inline-flex;
> }
> ```

this works for me too, but **display: inline-block;** was introduced specifically for IE11 in #17214
i will research further what led to regression

```
.block-editor-block-toolbar__slot {
	// Required for IE11.
	display: inline-block;
	// Fix for toolbar button misalignment on IE11
	line-height: 0;

	// IE11 doesn't read rules inside this query. They are applied only to modern browsers.
	@supports (position: sticky) {
		display: inline-flex;
	}
}
```

**Comment by ambienthack** [comment] 2020-11-11 18:48
it seems overall support for ie11 is rather poor. can anyone confirm that it is still a priority? sorry, i'm new here  🤷‍♂️ 

![Screenshot_1](https://user-images.githubusercontent.com/70915/98851309-23747c00-2467-11eb-8e58-25117e0a85ee.jpg)

**Comment by sabernhardt** [comment] 2020-11-11 19:56
There are probably higher priorities for IE11 than this issue, though it would be nice if someone could make this pull request (and test it).

IE11 is still officially supported:
https://make.wordpress.org/core/handbook/best-practices/browser-support/

Regarding the most recent screenshot, I'm not able to reproduce the cutoff shown with the Publish and menu buttons. If buttons are not visible and/or usable, that needs to be in a separate issue (and more important than this one).

**Comment by ambienthack** [comment] 2020-11-12 13:27
created issue #26932 for bugs from the last screenshot

**Comment by ambienthack** [comment] 2020-11-23 20:03
Created a pull request #26987

**Comment by youknowriad** [comment] 2021-04-23 14:17
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.

**Closed by youknowriad** 2021-04-23 14:17 UTC
Labels: Browser Issues, Good First Issue, [Feature] Media, [Status] In Progress, [Type] Bug
