### ISSUE TITLE
The block editor's post title doesn't seem to allow titles containing HTML elements, but it actually does.

### ISSUE THREAD

**Issue by tenman** [WordPress/gutenberg#45582] opened 2022-11-07 09:57 UTC
### Description

gutenberg_render_block_core_post_title() use get_the_title()

get_the_title function allows HTML elements in the post title

If it's correct to disallow strings containing HTML elements, wouldn't it be better to add strip_tags?

### Step-by-step reproduction instructions

In my testing, I was able to paste a title containing the HTML element below.

`<a href="https://example.com">hello world</a>`

If you add the above link to the title of your post, the link from your home page will replace the link destination.

`<span style="color:red;">hello</span> world
`
The post title will be displayed in red, but the post title block will remain in the currentColor with the HTML removed.

### Environment info

- WordPress 6.1
- Windows 10
- Chrome 107.0.5304.88

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tenman** [comment] 2022-11-07 10:20
For the title including html, please use the one described in notepad++ utf8 , windows (cr/lf).
Just copying the code written in this report may not work.

**Comment by Mamaduka** [comment] 2022-11-22 14:11
Thanks for contributing, @tenman!

I think this is a duplicate of #38668. I will close it as duplicate, so please subscribe to the original issue report.

**Closed as not planned by Mamaduka** 2022-11-22 14:11 UTC
Labels: [Type] Bug, [Status] Duplicate, [Package] Editor
