### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by dmitrydrynov** [WordPress/gutenberg#15438] opened 2019-05-05 13:09 UTC
Hello everyone,
I need help!

I have a problem with images, When I add any images in my post is ok, I see my image. But when I reopen my post for edit I have 404 error.
![image](https://user-images.githubusercontent.com/4089575/57194484-1ca2aa00-6f50-11e9-95bc-bc3c7fd5dc5f.png)

**Comment by nerrad** [comment] 2019-05-06 13:01
Hi there,

Thanks for reporting your issue.  We need more information before we can assist with reproducing.  Can you please follow the [bug report template](https://github.com/WordPress/gutenberg/issues/new?template=Bug_report.md) when crafting your issue.

I'm unable to reproduce this on the master branch using the Gutenberg plugin.  You may also want to rule out this being another plugin/theme conflict as well.

I'm going to close this because there's not enough information for us to definitely confirm this is an issue or fix it if its determined to be an issue.

**Closed by nerrad** 2019-05-06 13:01 UTC
Labels: [Status] Needs More Info

**Comment by dmitrydrynov** [comment] 2019-05-06 13:12
I have url for images "/wp-admin/{uploads}/". is it corret?

**Comment by nerrad** [comment] 2019-05-06 13:24
@dmitrydrynov as I stated in my reply I'm unable to reproduce anything in your screenshot and there's not enough info for me (or others) to try and align my testing environment with yours (i.e. what version of GB are you using?  Are you using what's bundled with WordPress core (what version) or a released version of the GB plugin?  Have you verified other plugins or a theme are not introducing the problem on your site?  As mentioned in my above reply, filling out the questions from the bug report template will help provide that necessary information. 

The `/wp-admin/{uploads}` url pattern is not something I've seen before for images in the content so it suggests there's something specific to your environment that is causing the issue.
