### ISSUE TITLE
Featured Image Panel always requires "edit_posts" capability even for CPT

### ISSUE THREAD

**Issue by derweili** [WordPress/gutenberg#14660] opened 2019-03-27 11:18 UTC
**Describe the bug**
To assign a featured image to a custom post type the capability `edit_posts` is always required. Event when the post type has other (custom) capabilities assigned.

When Switching back to classic editor, the `edit_posts` capability is not required, only the `upload_files` capability is required.

**To Reproduce**

I added a Custom Post Type "People" with "thumbnail" support and these custom capabilities:
```
'capabilities' => array(
	'edit_post'          => 'edit_people',
	'read_post'          => 'read_people',
	'delete_post'        => 'delete_people',
	'edit_posts'         => 'edit_peoples',
	'edit_others_posts'  => 'edit_others_people',
	'publish_posts'      => 'publish_people',
	'read_private_posts' => 'read_private_people',
	'create_posts'       => 'create_people',
),
```

I then added a custom user role "Human Resource" with following capabilities:
```
          'read'            => true,
          'edit_posts'      => false,
          'edit_post'       => false,
          'upload_files'    => true,
          'edit_dashboard'  => true,
          'create_projects' => false,


          // Job Roles
          'edit_job'          => true,
          'read_job'          => true,
          'delete_job'        => true,
          'edit_jobs'         => true,
          'edit_others_jobs'  => true,
          'publish_jobs'      => true,
          'read_private_jobs' => true,
          'create_jobs'       => true,
```

When a user with this "Human Resource" user role tries to edit the people post type, everything works except adding a featured image. The whole "Featured Image" panel ist hidden.

After adding the `edit_posts` capability to the custom user role, the user is able to add a featured image.

When enabling the "classic editor" plugin, the `edit_posts` capability is not required. The only required capability to add featured images in classic editor is `upload_files`.

**Expected behavior**
The Featured Image Panel should be visible as long as the user has the capabilities to edit the custom post type and the capability `upload_files`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version WordPress 5.1.1

**Comment by miya0001** [comment] 2019-04-03 16:19
I think it is a same problem with #12198 .

I opened a ticket on Trac.
https://core.trac.wordpress.org/ticket/46723

Actually, if it allows user who has capability "upload_files", we will run into a next problem that attaching featured image requires "edit_post" capability to access `v2/media` endpoint. 😓

**Comment by aduth** [comment] 2019-04-22 20:30
Thanks for reporting.

As a duplicate of #12198 with [upstream Trac ticket](https://core.trac.wordpress.org/ticket/46723) for the underlying REST API issue, it's my understanding that this is to be closed as consolidated to following the Trac ticket.

**Closed by aduth** 2019-04-22 20:30 UTC
Labels: REST API Interaction, [Component] Post Settings
