### ISSUE TITLE
Pullquote 'solid style' keeps all previous background color css classes if saved

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#24615] opened 2020-08-18 08:51 UTC
**Describe the bug**
If you create a `Pullquote` block with `Solid color` style and save, after having set a background color, the color related classes are persistent and merged across each save. So if you had saved with a background color and then change it to another color, the `figure` element has both classes. Also if you try to unset it, you can't.

ex produced `figure` classes after multiple color changes/saves:
```
wp-block-pullquote has-background has-secondary-background-color has-accent-background-color
is-style-solid-color has-background has-secondary-background-color
```

**To reproduce**
1. Create Pullquote block and select `Sold color` styles
2. Change background color and save.
3. Reload post
4. Try to change or even unset the background color
5. Observe that the classes and therefore the colors are not working as expected.

**Expected behavior**
When you change background color the previous color's classes should be removed.

**Comment by youknowriad** [comment] 2020-08-18 09:15
Duplicate of #11352

**Closed by youknowriad** 2020-08-18 09:15 UTC
Labels: [Block] Pullquote, [Type] Bug
