### ISSUE TITLE
Code Editor: Content changes not respected when using mode change keyboard shortcut

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9512] opened 2018-08-31 15:18 UTC
**Describe the bug**

When making a change to the post content in the Code Editor and retaining focus within the Code Editor's textarea, switching back to Visual Editor reveals that the changes were not applied if the change in editor modes is applied using the keyboard shortcut.

**To Reproduce**

1. Navigate to Posts > Add New
2. (Prerequisite) Switch to Code Editor if not already
3. Enter text in the Code Editor textarea
4. _Without leaving the field_, press the keyboard combination to switch editor modes (<kbd>⇧⌥⌘M</kbd>)
5. Note that your changes made in Step 3 are not shown.

**Expected behavior**

Changes made in Step 3 are shown in Visual Editor.

**Additional context**

This is due to the PostTextEditor component's "delayed sync" behavior, where we do not parse on individual keypresses, only when the user "finishes editing". The current metric for determining that a user has finished their edits is the `blur` event. But within this workflow, the `blur` event is not triggered (or at least not handled by PostTextEditor, perhaps due to the fact that it will have unmounted by the time it's called).

A possible fix may be to consider whether there are unsaved changes in the PostTextEditor's `componentWillUnmount` and invoking the `onPersist` prop.

**Comment by noisysocks** [comment] 2018-09-03 10:56
> A possible fix may be to consider whether there are unsaved changes in the PostTextEditor's componentWillUnmount and invoking the onPersist prop.

Looked into this. The problem is that `componentWillUnmount` is called in the same call stack as when `SWITCH_MODE` is dispatched which means that dispatching `RESET_BLOCKS` doesn't cause the UI to update. 

We can fix this by calling `onPersist` in a `setTimeout` but that's a little too hacky for my liking.

I'm thinking that we should change our approach again so that `onPersist` is called on every key stroke. We can debounce it so that excessive undo levels aren't created.

Any thoughts?

**Comment by aduth** [comment] 2018-09-04 12:43
>The problem is that `componentWillUnmount` is called in the same call stack as when `SWITCH_MODE` is dispatched which means that dispatching `RESET_BLOCKS` doesn't cause the UI to update. 

I'm curious to learn more about this. It doesn't seem to follow that the UI should ever be falling out of sync with state, regardless in which tick the change to state occurs.

What specifically do you observe? Are the blocks in the Visual Editor not "up to date" with changes made in the Code Editor?

**Comment by yankiara** [comment] 2019-11-25 13:00
Hi all,

Any news about this???
Issue still here in WP 5.3 :-( How can this major bug still be present one year later?

How can we help? (coding, reviewing...?)

Thx,
Yan

**Comment by noisysocks** [comment] 2020-11-23 04:25
Reported here also: https://core.trac.wordpress.org/ticket/47892

**Comment by noisysocks** [comment] 2020-11-23 04:27
An issue related to this is that the _Preview_ and _Publish_ buttons don't transition from disabled to enabled until the text field is unfocused. See https://core.trac.wordpress.org/ticket/47791.

**Comment by jikamens** [comment] 2020-11-23 21:38
I am genuinely surprised that this **data loss bug** (and yes, I have personally lost data because of this bug, so I'm not just talking about theoreticals here) has remained unfixed for more than two years.

**Comment by noisysocks** [comment] 2020-11-24 05:32
Would you like to channel your frustration into a PR? It's very cathartic 🙂

**Comment by grzim** [comment] 2021-01-20 11:21
Fixed in https://github.com/WordPress/gutenberg/issues/9512

**Comment by mcsf** [comment] 2021-04-05 18:16
> Fixed in #9512

@grzim: see https://github.com/WordPress/gutenberg/issues/29988#issuecomment-813552286

**Comment by grzim** [comment] 2021-04-06 10:11
The issue has to be reopened due to regression made by #9512

The issue can be solved in a different way than saving content on blur. The alternative is to save on switching editors.

**Comment by Mamaduka** [comment] 2022-05-16 13:16
The issue was fixed in #40730 and will be included in WP 6.0.

**Closed by Mamaduka** 2022-05-16 13:16 UTC
Labels: [Type] Bug, [Feature] Code Editor, Needs Dev
