### ISSUE TITLE
Enable formatting text highlighted over two paragraphs

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#40907] opened 2022-05-07 16:05 UTC
### Description

It seems that the multi-select of text doesn't work for formatting, as the formatting toolbar is switched out for the group toolbar. 

For instance, if I select a text inside one paragraph, I can use bold, italic. I can't do that when selecting text over two paragraphs. 

_It works with keyboard short cut `cmd + b` and `cmd+i`, though. 👏_ 

If I would like to also change the color for selected text. The tool is not available when highlighting text over two paragraphs. 

I found #40063 but it only suggest hiding the tool bar not enable more text formatting. 

### Step-by-step reproduction instructions

1. Create two paragraphs. I use [business lorem impsum](https://www.cipsum.com/) 
2. Highlight text words from end of the last row in one paragraph and words from the first row of the next paragraph. 
3. try to change the color to a different color. 

### Screenshots, screen recording, code snippet

I created a video with all the steps. I  tried also if the text color tools on the right would work. I was only able to change the colore for a whole paragraph (as expected)

https://user-images.githubusercontent.com/39980/167262438-a905f08f-004f-418f-9459-3fd76db89e78.mp4

 

### Environment info

WordPress 6.0 RC 1
no Gutenberg plugin
Chrome Version 100.0.4896.127 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment] 2023-08-17 13:30
This is a duplicate of #27221.

**Closed as completed by ellatrix** 2023-08-17 13:30 UTC
Labels: [Type] Enhancement, [Feature] Block Multi Selection, [Block] Paragraph
