### ISSUE TITLE
Edge: Unable to get property 'handleEvent'

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2066] opened 2017-07-28 10:25 UTC
On current master, using Microsoft Edge on both the New Post and Demo page I get this error:

`Unable to get property 'handleEvent' of undefined or null reference`

![screenshot 11](https://user-images.githubusercontent.com/1682452/28713545-bd37dfda-738f-11e7-845b-0466f7f8510e.png)

**Comment by aduth** [comment] 2017-07-28 12:51
Hmm, I'm not able to reproduce this one, on neither the New Post or Demo screens.

![Not same error](https://user-images.githubusercontent.com/1779930/28717911-b706446c-7371-11e7-8b91-62d868a0179f.png)

Is it potentially a conflict from one of the other plugins you have activated?

**Comment by afercia** [comment] 2017-07-28 13:24
> Is it potentially a conflict from one of the other plugins you have activated?

All plugins inactive :)

**Comment by afercia** [comment] 2017-07-28 14:31
Tested again, all plugins inactive, cleared cache: getting same error. 

![screenshot 15](https://user-images.githubusercontent.com/1682452/28721319-30db4dc6-73b0-11e7-8db7-04bd526203c4.png)

Edge version:
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

![screenshot 16](https://user-images.githubusercontent.com/1682452/28721333-3d73e228-73b0-11e7-92a7-4771aabad7e9.png)

**Comment by aduth** [comment] 2017-07-28 14:43
Is this from a development build (`npm run dev`) or a production build (`npm run build`) ?

Do you have a `SCRIPT_DEBUG` (or other relevant) constant defined in `wp-config.php`. What's its value?

**Comment by afercia** [comment] 2017-07-28 15:18
npm run build
WP_DEBUG true
SCRIPT_DEBUG true

**Comment by aduth** [comment] 2017-07-31 13:32
It appears this is specific to Edge 40+ . After upgrading I was able to reproduce the error.

**Comment by aduth** [comment] 2017-08-14 16:24
I'm not sure what specifically might have changed, but I no longer see the error in Edge (41+)

![image](https://user-images.githubusercontent.com/1779930/29281053-871fdbdc-80eb-11e7-995c-ecb6f29e7e41.png)

**Comment by mtias** [comment] 2017-11-20 11:56
Closing this as seems fixed. If it still happens, please, reopen.

**Closed by mtias** 2017-11-20 11:56 UTC
Labels: Browser Issues, [Type] Bug
