### ISSUE TITLE
Undo pastes the copied text

### ISSUE THREAD

**Issue by GutenDev** [WordPress/gutenberg#11568] opened 2018-11-07 09:39 UTC
**Describe the bug**
I copied a text and pasted it on a paragraph block, hit Return and clicked command+z; the text pasted twice;

**To Reproduce**
1. Copy a text
2. Paste it on a paragraph block
3. Hit Return
4. Hit Command+Z / Ctrl+Z

**Expected behavior**
Should delete the new paragraph block created. 

**Screenshots**
![unknown behavious](https://user-images.githubusercontent.com/44389517/48123366-e7204b00-e2a3-11e8-9cda-6c8ed17e5699.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Google Chrome
 - Version 70.0.3538.77

**Comment by swissspidy** [comment] 2018-11-07 10:04
Noticed the same behavior a short while ago in https://github.com/WordPress/gutenberg/issues/6516#issuecomment-433920438.

**Comment by afercia** [comment] 2018-11-07 15:49
Seems to me it happens also witn an already existing paragraph. Just make sure to:
- put the caret _at the beginning_ of the paragraph
- press Enter
- a new paragraph is created _before_ the existing one (I guess Gutenberg considers the previous one as "deleted"?)
- press Command+Z / Ctrl+Z: the previous paragraph re-appears

**Comment by designsimply** [comment] 2018-12-05 18:18
Closing as a duplicate of #8882. @GutenDev I think a fix for #8882 will cover this case as well, but please let me know if you feel otherwise!

**Closed by designsimply** 2018-12-05 18:18 UTC
Labels: History, [Component] Raw Handling, [Component] Rich Text, [Type] Bug
