### ISSUE TITLE
New Media & Text Block isn't responsive

### ISSUE THREAD

**Issue by munirkamal** [WordPress/gutenberg#10828] opened 2018-10-20 10:30 UTC
**Describe the bug**
It would be great to have the new media & text block responsive similar to how it's done with the column block.

**Expected behavior**
It should stack in small screens.

**Screenshots**
https://www.useloom.com/share/e910cb1d7b3947e680c19b2c6264d02f

**Comment by youknowriad** [comment] 2018-10-20 12:12
duplicate of #10798

**Closed by youknowriad** 2018-10-20 12:12 UTC
