### ISSUE TITLE
Suggestion: Add a custom palette to the Gutenberg editor color settings for colors that are often reused

### ISSUE THREAD

**Issue by alaJoAnn** [WordPress/gutenberg#9633] opened 2018-09-05 15:14 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by 0aveRyan** [comment] 2018-09-05 15:39
Truncated original title: 
```Suggestion: Add a custom palette to the Gutenberg editor color settings for colors that are often reused. For instance, I always end my posts with a signature "blurb" that is bolded with a specific color from the current color pallet. Another instance, sometimes I set off a block of text with a certain color -- and I always use the same color for that purpose, from the current color pallet. When you improve the Gutenberg color palette, maybe you could have two "Text" and "Background" tabs. And the lower section of either tab could be a custom palette.```

**Comment by talldan** [comment] 2020-02-19 02:45
Duplicate of #6941

**Closed by talldan** 2020-02-19 02:45 UTC
Labels: [Feature] UI Components, [Status] Duplicate, [Type] Enhancement
