### ISSUE TITLE
Color settings broken for custom editor-color-palette since v7.9.0

### ISSUE THREAD

**Issue by styledev** [WordPress/gutenberg#22325] opened 2020-05-13 16:16 UTC
When defining custom colors with the add_theme_support('editor-color-palette') function the editor no longer renders the color settings in any block except for the cover block.

This functionality works as expected in v7.8.1 and has been broken since v7.9.0.

First block is a cover block with custom editor-color-palette color selected. Second block with text "test" is a group block with custom editor-color-palette background and text colors selected.

![Screen Shot 2020-05-13 at 9 12 03 AM](https://user-images.githubusercontent.com/12783/81837769-1eeffa80-94fa-11ea-8373-29673538412d.png)

To note: using the Custom color picker works as expected.

**Comment by talldan** [comment] 2020-05-22 09:27
Thanks for reporting @styledev, looks like this was already caught in https://github.com/WordPress/gutenberg/issues/21931 and there's a fix in https://github.com/WordPress/gutenberg/pull/22356.

**Comment by youknowriad** [comment] 2020-05-22 09:27
duplicate of #21931

**Closed** 2020-05-22 09:27 UTC
Labels: Needs Testing, [Feature] Themes
