### ISSUE TITLE
Group contextual menu option: Ensure Cover block is wrapped in a Group block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#42613] opened 2022-07-22 01:38 UTC
### Description

Using 13.7.1, after grouping a cover block, the cover block itself is removed. If you use 6.0.1, the cover block remains. This was found as part of the[ fifteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/#comment-2627)

>Trying to control the featured image presentation inside the cover block. I understand that the automatic application of that image is part of the curated experience for the cover block, but I wish it still have the same image operation when it is grouped, and not just disappeared. Or is that a bug?

### Step-by-step reproduction instructions

1. Add a Cover block.
2. Transform to Group block.
3. Notice the Cover block is removed. 

***Update:*** The issue with transforming a Cover block has been resolved as of https://github.com/WordPress/gutenberg/pull/42638. The remaining task is to update the "Group (verb) menu item" in the block settings dropdown menu to wrap blocks instead of using the transform.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/180342759-178087ef-319c-4839-a5f4-4f11af50adc2.mp4

### Environment info

Works properly in 6.0.1. Broken with 6.0.1 + Gutenberg 13.7. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-07-22 02:09
I can replicate. Interestingly enough, if you add an image from the Media Gallery and then group the Cover block, the Cover block remains inside of the Group (the expected result). There must be some logic in the grouping mechanism that's causing this.

**Comment by annezazu** [comment] 2022-07-22 02:35
Ah ha -- I wonder if this has been impacted at all by the featured image functionality being added in. @draganescu just in case you might know.

**Comment by glendaviesnz** [comment] 2022-07-25 00:14
Probably related to https://github.com/WordPress/gutenberg/pull/40293 where this was added as intended behaviour

**Comment by andrewserong** [comment] 2022-07-25 00:41
Oh, this is a pretty interesting one. #42638 looks like a good short-term fix to me for dealing with the case of a Cover block that has the featured image set, thanks for getting that one up @ndiego!

In this case, I think there's a subtle difference between two potential user interactions when it comes to grouping things.

1. If a user has a Cover block selected, and selects to transform to Group from the transform menu, then I think the expectation would be that the block would be transformed to a Cover block, rather than being nested in another Group block (which was what we were attempting to do in #40293)
2. If a user selects Group (verb) from the settings menu, then I think the expectation would be that the current block would be wrapped in a Group block.

So, perhaps a fix for this issue would be to separate the behaviour here a bit more and ensure that the `Group` (verb) menu item always wraps the selected blocks instead of using a transform?

**Comment by ndiego** [comment] 2022-07-25 01:57
> So, perhaps a fix for this issue would be to separate the behaviour here a bit more and ensure that the Group (verb) menu item always wraps the selected blocks instead of using a transform?

Yeah, I was a bit surprised when I realized the "Group (verb) menu item" was using the transform functionality under the hood. I agree with all the transform logic in the Cover block (once the featured image bug is fixed), but I think it can be a bit unintuitive when you are trying to "group" blocks rather than transform a Cover block into a Group block.

**Comment by andrewserong** [comment] 2022-07-25 23:53
Thanks for merging #42638 @ndiego! I thought I'd re-open this issue so that we can keep it for tracking updating the "Group (verb) menu item" to wrap blocks instead of using the transform. Feel free to re-close the issue, though, if you think we should have a separate issue for it 🙂

**Comment by ndiego** [comment] 2022-07-26 13:13
@andrewserong yup, that sounds good. The issue got automatically closed and forgot to manually reopen. Thanks

**Comment by jordesign** [comment] 2023-08-28 10:46
Checking back over this - I'm seeing the behaviour correct where selecting 'Group' from the contextual menu _does_ correctly wrap it in the group (instead of transforming).

I'll close this for now - please feel free to reopen if I've misunderstood.

**Closed as completed by jordesign** 2023-08-28 10:46 UTC
Labels: [Type] Bug, [Block] Cover, [Block] Group
