### ISSUE TITLE
Adding a link url via copy/paste doesn't work on previously formatted text

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#63434] opened 2024-07-11 13:28 UTC
### Description

For some of my content I add a link to text and then bold it. Sometimes, I bold it first and then add the link. 
For a while now I noticed that copy/page over a highlight text didn't always work, and I finally chased down the source of this "misbehavior" 

If the text is formatted in bold, highlighting and adding the link via copy/paste doesn't work anymore. It does\work when using the link button, but that makes the process two clicks longer. 

See below video for illustration. 

### Step-by-step reproduction instructions

- Add a paragraph block with text. 
- Highlight a portion of the text 
- Format it in bold
- Highlight the text again
- copy/paste a URL. (use https://google.com or any other url) 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/39980/eda3994c-2856-436d-9dd4-0d595f5b86f0

### Environment info

- WordPress 6.6 RC3 (but it has been there for a while so it's not a WordPress 6.6 issue)
- Gutenberg 18.7.1
- Google Chrome Version 126.0.6478.127

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2024-07-16 19:46
Yes, I can confirm. This issue also happens on any previously formatted text. For example, the same thing happens when text is italicized or set to inline code.

**Comment by t-hamano** [comment] 2024-07-19 15:13
I was able to reproduce this issue, and it seems to occur when copying and pasting text with some inline formatting.

https://github.com/user-attachments/assets/d2cf26c3-9547-4364-9e00-612f2d0c328e

**Comment by t-hamano** [comment] 2024-07-20 14:54
I discovered that this problem was caused by the following PR:

- #54543

Commenting out [this conditional statement](https://github.com/WordPress/gutenberg/blob/3099d18e430a70c905b429e4a8b5545daead823b/packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js#L32-L34) seems to fix the problem, but it might have some side effects.

Maybe @ellatrix knows something.

**Comment by ellatrix** [comment] 2024-07-21 09:07
@t-hamano do you want to try a PR and see what tests fail?

**Comment by rfischmann** [comment] 2024-07-25 18:29
We have a reusable block in our site that adds a `<span>` with a specific class and some text inside of it. I also can't select the text and paste a link anymore on WordPress 6.6.

**Comment by t-hamano** [comment] 2024-08-23 05:10
I think this issue was resolved as a result of #63671 and is not reproducible in the latest Gutenberg, so I would like to close it.

I think it will be important to see if we backport the fix for this issue to a WP6.6 minor release. See [this comment](https://github.com/WordPress/gutenberg/pull/63779#issuecomment-2306020796).

**Closed as completed by t-hamano** 2024-08-23 05:10 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Link Editing
