### ISSUE TITLE
useBlockProps with apiVersion 2 generates invalid CSS class names

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#27764] opened 2020-12-16 15:23 UTC
**Describe the bug**
`useBlockProps.save` with `apiVersion` 2 generates invalid CSS class names.

**To reproduce**

```javascript
const blockProps = useBlockProps.save({
    className: 'sht/my-block'
});
````

…generates the CSS class name `wp-block-sht-my-block sht/my-block`. [W3C spec](https://www.w3.org/TR/CSS2/syndata.html#characters) indicates that the forward slash isn't allowed.

**Editor version (please complete the following information):**
- WordPress version: **5.6**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **default**

**Desktop (please complete the following information):**
 - OS: **macOS**
 - Browser **Chromium**
 - Version **88**

**Comment by markhowellsmead** [comment] 2020-12-16 15:25
Updated: the issue relates to `useBlockProps.save`, mot `useBlockProps`.

**Comment by talldan** [comment] 2020-12-17 03:59
Maybe I'm misunderstanding, but it looks like you're passing in the value `sht/my-block`?

This doesn't seem like a regression, it was possible to do the same before `useBlockProps`, React allows classnames with a forward slash. I'll close as something that won't be fixed.

**Closed by talldan** 2020-12-17 03:59 UTC

**Comment by markhowellsmead** [comment] 2020-12-17 11:37
Thanks for the speedy answer. My bad. I misunderstood the instructions at https://make.wordpress.org/core/2020/11/18/block-api-version-2/ - the `className` is optional, where I understood it to be the block name.
