### ISSUE TITLE
It's been a really long time, still no shortcut key for Headings

### ISSUE THREAD

**Issue by brkykmsz** [WordPress/gutenberg#22738] opened 2020-05-29 10:11 UTC
The classic mode has shift + alt + 1/2/3... for headings or shift + alt + c for center alignment. These are really useful if you are trying to avoid getting carpal tunnel syndrome. Gutenberg is pain in the hand so far.

**Comment by phpbits** [comment] 2020-05-30 07:15
@brkykmsz You can use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin to use those shortcuts 👍

**Comment by talldan** [comment] 2020-06-03 09:13
Duplicate of #7438

**Closed by talldan** 2020-06-03 09:13 UTC
