### ISSUE TITLE
List Block: Cutting and Pasting Highlighted Text Doesn't Retain Styles

### ISSUE THREAD

**Issue by edequalsawesome** [WordPress/gutenberg#39359] opened 2022-03-10 20:19 UTC
### Description

For unordered and ordered lists, if you apply a custom text or background color using the Highlight tool, then "cut" that list item and paste it elsewhere within the same list, it appears with a yellow highlight instead.

This highlight can't be removed except by editing the code for the post/page, and after adding any new color using the Highlight tool again to the affected text, the Highlight tool becomes inaccessible for it.

### What you expected to happen

The list item should retain its custom text/background color(s) when pasted again.

### What actually happened

The custom colors are stripped, and instead the text appears with the default font color and a yellow highlight. Examining the code editor, this is coming from a basic <mark> tag with no style attributes.

There is no option to remove this yellow background using the Highlight tool (it behaves as if there is no Highlight applied yet). If the text was pasted into the same place it was cut from, or if you paste it elsewhere and use the Highlight tool again, trying to use Highlight again results in the tool not being accessible.

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Add a List block (ordered or unordered) with a few list items.
3. Select some/all text in one item. From the hovering toolbar, select the downward arrow > Highlight.
4. Choose any text and/or background color.
5. Select the entire list item and "cut" it (ctrl/cmd + X). Note: copying doesn't seem to result in the same issue, only cutting.
6. Paste the item anywhere on the post/page: elsewhere in the list, in the same spot it came from, or outside the List block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4000628/157747670-246a8735-401e-471d-aa4c-e735d810ecef.mp4

### Environment info

WordPress 5.9.1
Gutenberg 12.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment] 2022-10-17 12:37
I can't reproduce here. Copy pasting coloured text works fine in lists. Could you retest with the latest Gutenberg release. Maybe the list rewrite fixed this.

**Comment by skorasaurus** [comment] 2023-02-14 17:29
Thank you for the detailed instructions; I'm able to reproduce this on Gutenberg 15.1 and WordPress 6.1.

**Comment by annezazu** [comment] 2023-07-19 00:25
I couldn't replicate with 6.3 RC1. Closing this out but happy to reopen if it can be replicated:

https://github.com/WordPress/gutenberg/assets/26996883/41c4cbbc-7b3f-4c36-9db0-0f6c2b9d192b

**Closed as completed by annezazu** 2023-07-19 00:25 UTC
Labels: [Type] Bug, [Block] List
