### ISSUE TITLE
Button block font-weight setting not working on twenty twenty-one theme.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/gutenberg#53338] opened 2023-08-04 11:10 UTC
### Description

I have tested button block with deterrent deferent WordPress themes and found the button block font-weight setting not working in twenty twenty-one theme. And, I think this a theme css overriding issues. Please check the below attachment video recording for a better understanding off issue.

### Step-by-step reproduction instructions

1. First activated twenty twenty-one theme.
2. Next, create a new page and take the button block.
3. Apply font weight setting and check it( not working ).

### Screenshots, screen recording, code snippet

Video URL: https://share.cleanshot.com/b196mZcF0Z1l4DdBJZsx

### Environment info

- WordPress version: 6.2.2 running, Gutenberg version: 16.3.0, and Active theme: Twenty Twenty-One
- Browsers: Chrome
- Device: MacBook( Desktop )

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment] 2023-08-04 13:26
The issue for font-weights is not specific to TT1.
All font-weights get displayed and are selectable, no matter if they are enqueued by the theme. This also happens for all themes build with the "Create Block Theme" Plugin. https://github.com/WordPress/gutenberg/issues/52201

**Comment by t-hamano** [comment] 2023-08-07 12:33
Thanks for the report.

I have submitted a ticket because I believe this is an issue that should be resolved on the bundle theme side. I have also described the cause as to why font-weight is not applied.

https://core.trac.wordpress.org/ticket/58991

I would like to close this issue, but if I have missed something, please feel free to comment.

**Closed as not planned by t-hamano** 2023-08-07 12:33 UTC
Labels: [Type] WP Core Ticket, [Block] Buttons
