### ISSUE TITLE
Using Tables, there should be a feature to "center" the table in the window

### ISSUE THREAD

**Issue by subguy** [WordPress/gutenberg#10578] opened 2018-10-13 15:26 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by La-Geek** [comment] 2018-10-13 16:15
![center_table](https://user-images.githubusercontent.com/1585416/46907522-f4038600-cf13-11e8-96dc-1532b4369b98.jpg)

**Comment by designsimply** [comment] 2018-10-16 03:48
Thank you for the report! Closing as a duplicate of #9778 and noting an update was recently made in #10468 and that should show up in one of the next few releases (probably 4.0 or 4.1).

**Closed by designsimply** 2018-10-16 03:48 UTC
Labels: Blocks, [Status] Duplicate, [Type] Bug
