### ISSUE TITLE
Dropcap paragraph as last block causes twitchy focus behaviour

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12176] opened 2018-11-21 13:19 UTC
A paragraph block with dropcap only shows the dropcap when the block is not being edited. If the block is the last on the page and you try and click out of the block to the area beneath, the focus is removed causing the block to show the dropcap. However, focus is then returned to the block and the dropcap is removed. This makes it very twitchy. Here I'm clicking in the space below the block:

![dropcaps](https://user-images.githubusercontent.com/1277682/48843020-cbca3b00-ed8d-11e8-9d54-742fec1ca210.gif)

Copied from #12172

**To Reproduce**
1. Create a post with a single paragraph block
2. Enable dropcaps from block options
3. Try and click out of the block to the area beneath. Note how the focus is removed, the dropcap is shown, and then focus is returned and the dropcap removed.

**Expected behavior**
Not entirely sure. I understand the dropcap is not shown while editing for various reasons, and I think the focus is given to the last block as part of the standard editor. This problem may exist for other blocks where the edit and view states are so different.

**Comment by ItsJonQ** [comment] 2020-01-23 14:38
![Screen Capture on 2020-01-23 at 09-36-44](https://user-images.githubusercontent.com/2322354/72993818-067d9800-3dc4-11ea-8003-78dcbca6e0bf.gif)

@johngodley Thanks for reporting this. I just noticed this as well. It looks like the issue is still there

**Comment by carolinan** [comment] 2021-10-05 11:43
I am not able to reproduce this issue, I will close it as fixed. Please comment and ask for it to be reopened if you encounter the problem again.

**Closed by carolinan** 2021-10-05 11:43 UTC
Labels: [Block] Paragraph
