### ISSUE TITLE
Dynamic block encodes ampersand & to &#038; in output from render_callback

### ISSUE THREAD

**Issue by martindrapeau** [WordPress/gutenberg#11789] opened 2018-11-13 03:04 UTC
I have registered a dynamic block and use a PHP function to generate some script tags and inline JavaScript. The JavaScript code gets modified upon output - some of the & get url encoded to &#038. The JavaScript interpretation then errors out.
![image](https://user-images.githubusercontent.com/104156/48388193-81c6c280-e6c6-11e8-9336-98a2c335e45f.png)

This same code is being used by shortcodes with no url encoding (as expected).
![image](https://user-images.githubusercontent.com/104156/48388176-6fe51f80-e6c6-11e8-8242-19db1db6b623.png)

The odd thing is that not all & get url encoded (see yellow underlined lines 117 or 118).

**To Reproduce**
You can view the broken JavaScript on this test page (generated from dynamic block): https://lab.amilia.com/gutenberg-bug/
You can view the working JavaScript on this test page (generated by shortcode): https://lab.amilia.com/plugin-calendar/

The source code for the plugin is here:
Block registration: https://plugins.trac.wordpress.org/browser/amilia-store/trunk/blocks/amilia-store-calendar.php
PHP back-end rendering function: https://plugins.trac.wordpress.org/browser/amilia-store/trunk/shortcodes/amilia-store-calendar.php

**Desktop**
 - OS: Windows 10 & Linux give the same thing
 - PHP: Version 5 & 7 gives the same thing
 - Browser: chrome
 - Versions: latest (12 Nov 2018)

**Comment by drpraveenss** [comment] 2019-01-04 12:13
I am also facing exactly the same issue.  Any fix/alternative for this ?

**Comment by martindrapeau** [comment] 2019-01-04 13:30
I found a workaround. It is to extract the JavaScript code into its own file. In PHP, you load that file and call a function to trigger the code.

Its not a solution though - there is a true bug that needs to be fixed. And to @designsimply this is not a help request - this is a bug report.

**Comment by drpraveenss** [comment] 2019-01-10 07:36
Thanks @martindrapeau ,
I found one more workaround for this. This issue is occurring because of comparator operator ('<' and '>') . Gutenberg is escaping characters inside '<'  . 
The workaround is to put these operator into a function (let's say function gt(int a, int b) {return a>b;} , then it works.

**Comment by designsimply** [comment] 2019-02-12 22:16
> And to @designsimply this is not a help request - this is a bug report.

Gotcha! I've fixed the label and send my apologies for the mistake!

**Comment by rafiee** [comment] 2019-06-25 06:18
change condition orders. For instant if your condition is like this: ( x<y  && z>w)   replace with  (z>w && x<y) 
this will solve the conflict.

**Comment by paaljoachim** [comment] 2021-02-21 01:08
Hi @martindrapeau and others.
Please retest with the newest version of WordPress and Gutenberg plugin.
Thanks!

**Comment by godismyjudge95** [comment] 2021-03-30 18:30
@paaljoachim 

Just ran into this issue again with the latest version of wordpress (5.7).
I realize this is probably low priority, but it kinda stinks that we can't add javascript to script blocks without possibly breaking it.

**Comment by paaljoachim** [comment] 2021-03-30 21:28
Hi @godismyjudge95 Daniel.

I added the question into the Slack core editor channel to hear if this method is (still) valid.

**Comment by godismyjudge95** [comment] 2021-03-31 15:28
@paaljoachim I meant to mention, this also happens with just the plain Custom HTML block.  So it must be something with the HTML parser.

Another thing that might help narrow it down, the javascript appears to work in the HTML preview of the block.  So maybe it is the save/retrieve functions that is malfunctioning?

**Comment by paaljoachim** [comment] 2021-04-01 08:52
Greg @gziolo and/or Miguel @mcsf perhaps you are able to respond here?

**Comment by mcsf** [comment] 2021-04-15 17:59
> I meant to mention, this also happens with just the plain Custom HTML block. So it must be something with the HTML parser.

This should be completely independent from the `render_callback` issue. That said, could you provide instructions for this? In my testing I found no issues. Here's what I did:

1. In a new post, add a Custom HTML block.
2. In its blank text area, paste the snippet attached below.
3. Hit _Preview_ to get the front-end result.
4. Observe that the browser presents an alert box, and that the page's source shows that the ampersands were preserved.

```html
<script>
  if (true && true) alert('ok')
</script>
```

**Comment by dancodedev** [comment] 2021-05-24 18:25
> > I meant to mention, this also happens with just the plain Custom HTML block. So it must be something with the HTML parser.
> 
> This should be completely independent from the `render_callback` issue. That said, could you provide instructions for this? In my testing I found no issues. Here's what I did:
> 
> 1. In a new post, add a Custom HTML block.
> 2. In its blank text area, paste the snippet attached below.
> 3. Hit _Preview_ to get the front-end result.
> 4. Observe that the browser presents an alert box, and that the page's source shows that the ampersands were preserved.
> 
> ```
> <script>
>   if (true && true) alert('ok')
> </script>
> ```

Try this case 

```
<script>
for (var t = 0; t < 10; t+= 1) {
}

if (true && true) alert('ok')
</script>
```

**Comment by mcsf** [comment] 2021-06-07 15:58
> Try this case
> 
> ```
> <script>
> for (var t = 0; t < 10; t+= 1) {
> }
> 
> if (true && true) alert('ok')
> </script>
> ```

@dancodedev: thanks, that was helpful.

I've tracked this down to a bug in `wptexturize`. It predates Gutenberg altogether (I was able to reproduce this issue in a vanilla WP 4.9.8 site). The issue stems from [how `wptexturize` tries to leave certain HTML elements untouched](https://github.com/WordPress/wordpress-develop/blob/37a4faa7ed8f20c36e5bd6766fe9e7eb0c7db0f1/src/wp-includes/formatting.php#L252), including — by default — `<script>` elements. When a script contains no `<` character, all is good; but when there is such a character (as in the case of `for (let i = 0; i < 5; i++)`), it messes with [how `wptexturize` breaks down its input into elements](https://github.com/WordPress/wordpress-develop/blob/37a4faa7ed8f20c36e5bd6766fe9e7eb0c7db0f1/src/wp-includes/formatting.php#L239).

~I think this should be reported as a Core WordPress bug at https://core.trac.wordpress.org/.~ There is a ticket from 2018 on this: https://core.trac.wordpress.org/ticket/45387.

**Comment by mcsf** [comment] 2021-06-07 16:34
I've [added a comment](https://core.trac.wordpress.org/ticket/45387#comment:9) under the original issue to describe this particular case.

Closing as a duplicate of [t45387](https://core.trac.wordpress.org/ticket/45387).

**Closed by mcsf** 2021-06-07 16:34 UTC
Labels: [Feature] Parsing, [Type] Bug

**Comment by allocater2** [comment] 2023-11-01 12:36
Still happening in Wordpress 2023. I inverted my logic

`if(a && b)`

became

`if(!(a || b))`

since only & is affected 🤷‍♂️

**Comment by zhouwei0211** [comment] 2024-10-29 14:32
Hi there, and in 2024 the Problem is still there.
I found a solution, maybe that make the code not such cool, but it works:
the problem is that, between "<" and ">", if there is any "&", it will automatcally escaping. So just put an always-right(or always-wrong) answer before it, the problem should be solved, here is my example:

Original Code:
      _if(dayOfWeek >= 2 && dayOfWeek <= 5)
                {
                if ((hour === 14 && minute >=31) || (hour >= 15 && hour < 18)) {
                    instance.clear();
                    alert("Das Restaurant ist von 15:00 bis 18:00 Uhr geschlossen. Bitte wählen Sie einen anderen Zeitraum");
                    }
       }_
then no wonder there is Sytax Problem in Broswer, because it is automatically escaping into:
      _if(dayOfWeek >= 2 & dayOfWeek <= 5)
                    {if ((hour === 14 &/#038;&/#038; minute >= 31) || (hour >= 15 && hour < 18)) {
                            instance.clear();
                            alert("Das Restaurant ist von 15:00 bis 18:00 Uhr geschlossen. Bitte wählen Sie einen anderen Zeitraum");
                     }
                        }_
but if I put a 1>2 before inner if-sentence like this:
      _if(dayOfWeek >= 2 && dayOfWeek <= 5)
				{    
				if ((1 > 0)&&(hour === 14 && minute >=31) || (hour >= 15 && hour < 18)) {
        			instance.clear();
        			alert("Das Restaurant ist von 15:00 bis 18:00 Uhr geschlossen. Bitte wählen Sie einen anderen Zeitraum");
    				}
	                        }_
and then problem solved.
the key point is, making <> this paar finish and no "&" in them to aovid the excaping.

**Comment by Gebarx** [comment] 2024-11-14 17:30
The bug does not occur only for blocks. It occurs also for code added to functions.php of a child theme, and in code added through the Snippets plugin, despite the advice of a WordPress.org Moderator [here](https://wordpress.org/support/topic/produces-error/#post-16323624) to "use a plugin specifically meant for inserting JS onto pages."
