### ISSUE TITLE
Gutenberg List View has limits on the length it can display

### ISSUE THREAD

**Issue by CrazyEarthGuy** [WordPress/gutenberg#41613] opened 2022-06-09 03:50 UTC
### Description

It seems there are annoying limits on how may items the Gutenberg "List View" can display (using WordPress 6.0 on Win 10 system, latest version of Chrome browser). On long complicated pages, that contain many blocks, if I scroll far down my page, past many many blocks, and click on a block, that block often won't get highlighted in List View.  Lets refer to such a block as a "far down block". In fact, it won't even be visible in List View, because the List View is cut off, and not showing blocks beyond some fairly small limit of items.  If I go into List View, and close most of the nested items, to shrink what's shown, then I can have better luck for it letting me access a "far down block".  This is a tremendous hassle.
     I imagine this bug has been reported dozens of times, but I've not used GetHub before to search for existing bug reports. I see something like 12K bugs when doing a "Gutenberg List View" search, so not sure how I'm supposed to verify if this particular bug has already been reported. If there are work arounds to this bug reported, can someone send me a link to where this bug is being discussed?

### Step-by-step reproduction instructions

See my Description

### Environment info

See my description

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2022-06-20 04:52
Thanks for report this @CrazyEarthGuy. I wasn't able to replicate the issue on a page with approx 2800 blocks:

https://user-images.githubusercontent.com/3629020/174527418-398e67b6-c461-4797-9f86-e2b4c537854d.mp4

Are you able to provide a screen recording of the issue please? If you are able to also show any errors that might appear in the Chrome javascript dev console that might help track down the cause of the issue in your instance. Thanks.

**Comment by CrazyEarthGuy** [comment] 2022-06-21 15:53
I've attached a video to the original bug report at the top of this page, which demonstrates the issue.

**Comment by CrazyEarthGuy** [comment] 2022-10-11 07:47
I've attached this video to my original bug report that shows the "List View Limited Number of Items" bug.
https://user-images.githubusercontent.com/107164698/174843212-0c0d5032-29c4-40f1-bcb5-13c00145c017.mp4

Please let me know if you notice anything that could be causing this bug, or if you know of an easy work-around. I sure hope the bug can be fixed, since it wastes a lot of time fighting this issue.

**Comment by glendaviesnz** [comment] 2022-10-12 00:13
@CrazyEarthGuy thanks for the video. What version of Gutenberg are you using? Would you be in a position to try this on the  [WordPress 6.1 release candidate](https://wordpress.org/news/2022/10/wordpress-6-1-release-candidate-1-rc1-now-available/) to see if the problem is still there on the latest release for you?

**Comment by beckej13820** [comment] 2022-11-12 20:22
I was able to recreate this issue on a site running Wordpress 6.1 and Gutenberg 14.5.0

Specifically, when 50 blocks or more are nested inside a group, the list cuts off at around 50. If there are collapsed lists above the cutoff, expanding those lists will move the cutoff to keep ~50.

**Comment by beckej13820** [comment] 2022-11-12 20:26
Here’s a screenshot showing the cutoff. Main idea is that there more columns on the right than in the list view. 

![4EF3AFEB-2DE7-4C13-895D-838D7238A21A](https://user-images.githubusercontent.com/29982981/201493186-8df10611-23ee-45aa-b918-dab45bb81988.jpeg)

The design of the page may be a contributing factor, where to put a shaded background behind the text, all 100 blocks are nestled inside a group  

![C5915C43-5377-4D04-914B-CF166A479486](https://user-images.githubusercontent.com/29982981/201493243-f77fa5d6-53d5-4d35-9059-72c2328024c4.jpeg)

**Comment by paaljoachim** [comment] 2022-11-12 21:28
Reopening issue based on additional feedback.

**Comment by vicobot-0815** [comment] 2023-07-13 20:36
This problem still seems to exist in:
    -   6.2.2
    -   6.2.2 with Gutenberg 16.2.1
    -   6.3-beta4 (with Beta Tester Plugin 3.5.2)
on fresh installs, using 6.2.2-php8.2-apache docker image

Browsers: Firefox 115.0 (Linux) and Chrome 114.0 (Linux)
    
Test:
1. Create a post and add about 40 blocks (for me the cutoff was 34 - 36 most of the time). To better see what is going on, you could put the numbers 1 - n into heading blocks.
2. Check that they look ok in List View, in the Outline, Content Canvas and Frontend. I tried with 200 heading blocks - everything everywhere was fine.
3. Group them all together in one Group Block.
4. Open the Group Block in List View. If you were adding blocks from inside the Group Block and already had it open in List View, you may have to navigate away from it (e.g. to Outline) and then open it again.

Result: 

The Group Block only shows blocks 1 to 34 (on some installs I tested on, it was 35 or 36). Sometimes editing the post in a different browser upped the numer of visible blocks in List View to 50.
Any additional blocks only show up in List View, if they are selected in the Content Canvas, but then the blocks around them are shown as white space only and cannot be selected in List View. Everywhere else the blocks all look ok.

This open issue seems to be the same or related: #42031

**Comment by andrewserong** [comment] 2023-08-18 05:50
I believe I have a fix for this, over in #53716. The fix looks to update / refresh the list view's windowing calculation when the expanded state of blocks changes (expanding / collapsing anywhere in the tree).

**Closed as completed** 2023-08-20 23:43 UTC
Labels: [Type] Bug, [Feature] List View
