### ISSUE TITLE
I wanted to see the code and switched to HTML but now can't switch back to the regular view even though that is checked.

### ISSUE THREAD

**Issue by patpatten** [WordPress/gutenberg#8615] opened 2018-08-06 18:14 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by qlstudent** [comment] 2018-08-06 18:38
I tried to reproduce it but couldn't 

![screenshot from 2018-08-06 14-37-14](https://user-images.githubusercontent.com/38367184/43734626-48f3549c-9986-11e8-95b9-1615239b1d36.png)
![screenshot from 2018-08-06 14-37-22](https://user-images.githubusercontent.com/38367184/43734627-48fd226a-9986-11e8-947f-ef735ec2aec3.png)

**Comment by patpatten** [comment] 2018-08-07 03:02
You have the option to use the visual or code when editing a post. I got to use the code then tried to go back to the regular visual and couldn't. It said I was already in the visual but wasn't and couldn't do anything. then I couldn't even exit out and had to shut off my computer to get out of it. This is a nightmare!






________________________________

**Comment by designsimply** [comment] 2018-09-13 20:39
@patpatten I'm sorry to hear about the trouble you had with Gutneberg "Edit in HTML" mode. I also tried testing this and couldn't reproduce the problem.

I know you reported this issue a while ago. I am going to close the issue since no other testers could reproduce the problem and I would also like to ask that, if you are able to test Gutenberg again, and if you are still having the same problem, please reply back here and note your OS and browser version so that can be tested if needed. We can continue talking here even if the issue is closed, and I may need to ask for more information again to try to get to the bottom of the problem.

**Closed by designsimply** 2018-09-13 20:39 UTC
Labels: [Status] Needs More Info, [Type] Help Request
