### ISSUE TITLE
Block column with "alignright" not working as expected

### ISSUE THREAD

**Issue by desrosj** [WordPress/gutenberg#15815] opened 2019-05-24 17:08 UTC
Move from core Trac: https://core.trac.wordpress.org/ticket/47372

I am trying to create a block column row where the first column (containing an image and caption) is aligned right and shows up after the second column (containing text) at full page width. (So that when the row collapses at mobile resolutions, the image appears first and the text comes after.)

You can see a simplified version of the code I used on my test page below, however, the first column is not getting aligned right as expected. When I inspect the page using developer tools in my browser, I can see that the "alignright" CSS styles (including "float:right;") are getting applied to the column, and it does not look as though anything else is interfering, yet the column does not actually float right. The problem occurs both in my current theme and in Twenty Nineteen.

```
<div class="wp-block-columns has-2-columns">
	<div class="wp-block-column alignright">
		<img src='https://placekitten.com/g/500/500' />
		<p><em>Image Caption</em></p>
	</div>
	<div class="wp-block-column alignleft">
		<h2>A Header</h2>
		<p>Some content goes here.</p>
	</div>
</div>
```

**Comment by marybaum** [comment] 2019-05-24 18:03
I've volunteered to take this on.

**Comment by nerrad** [comment] 2019-05-27 00:14
Thanks Mary for taking this on.  I have to confess it's not entirely clear what the expected behaviour here is.  Is the user entering custom code in the block editor?  Are they using the existing columns block?  If the latter, the existing columns block doesn't have a way (that I can see) for aligning right the contents of the left column and aligning left the contents of the right column (which is what I read the user request to be).  It also appears the desire is to control how columns collapse in mobile view.

On the surface this sounds like more of an enhancement request?

**Comment by ComputerTinker** [comment] 2019-05-28 14:02
I'm the OP. Mary, thanks for taking on the issue and Darren, thanks for the questions. Basically I was trying to duplicate an existing page on our main website (https://www.bju.edu/academics/faculty/facultymember.php?id=gmazak) with code generated through a custom plugin in Wordpress, and I was confused why the 'alignright' class was adding 'float:right' to the div, yet the div was not actually floating right as I would have expected.  Perhaps I'm just missing something.  

My workaround for now has just been to output the photo first (http://bjuscope.wpengine.com/faculty-profile/?facid=gmazak)  But I thought I'd submit an issue in case something was not working as the developers intended.  

I should point out that I did adjust my plugin at one point so that it output the special comments containing alignment code like Gutenberg does, and that did not seem to have an effect.  Thanks!

**Comment by marybaum** [comment] 2019-05-28 19:17
@ComputerTinker You are most welcome!

@nerrad I think it probably is an enhancement. I haven't dug into the code yet, but if an alignright class isn't aligning things right -- whatever the cause -- I think that's an unexpected behavior. 

If an align-right class has children that aren't aligning right, and it is furthermore asking them to float right, we could have a specificity problem (how do we get more specific than an inline element? Inquiring Mommas will be investigating 🥴🤔) or a conflict with some other rule.

To tackle after a couple of other things this afternoon ... hope your suns (or moons) are shining!

**Comment by marybaum** [comment] 2019-05-28 19:38
Russ, we will definitely investigate the behavior.

In the meantime, I notice you're staging at WPEngine. May I suggest a short-term fix? 

It is possible your current staging theme, which seems to be no longer in active development, has a role in this behavior.

As a WPEngine client you have access to the Genesis framework and a number of child themes at no extra charge, so I invite you to try out either  Genesis and a child theme or Atomic Blocks, free on wordpress.org but now owned and supported as part of the StudioPress/Genesis squad. 

There is one called Education Pro that will work with the block editor, but you'd be better served, I think, by choosing one of the child themes that have been updated in this calendar year, which have been specifically tuned to take advantage of the block editor.

**Comment by marybaum** [comment] 2019-05-28 19:40
Darren, given the theme involvement here, I think my first move will be to see what happens if I try to build a page like this in 2019. Then we can decide if this is a bug or an enhancement and what the milestone is.

**Comment by ComputerTinker** [comment] 2019-05-28 22:28
@marybaum thanks for the suggestion.  I did switch to the Twenty Nineteen theme and verify that the issue occurs there before I submitted my bug report earlier.  (For some reason the text doesn't wrap up above so you have to scroll waaaay to the right to read that portion of the second line. ;-) )

**Comment by youknowriad** [comment] 2019-08-22 13:09
Honestly, I don't really think this is an issue.

`alignright` is basically `float: right`. Themes do these in a generic way without any block specificity but all blocks don't support float alignments. If you apply this to a "div" that is not supposed to be floated (columns for example where the columns are supposed to be flex aligned), the result is somewhat random. 

My opinion is that we should just close this issue.

**Closed** 2020-02-27 13:12 UTC
Labels: [Block] Columns, [Type] Enhancement
