### ISSUE TITLE
When a new paragraph is started with only keyboard input, UI should not appear.

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#1616] opened 2017-06-30 15:36 UTC
When <kbd>return</kbd> is pressed twice to start a new paragraph, a bunch of UI pops up. It goes away with the first keystroke in the new paragraph, but the appearance of all these things is jarring. Shouldn't it just assume that if you used they keyboard to start a new paragraph, you want to continue writing, and that if you actually want to do something like choose a different block type, you'll move the cursor, at which point the UI can appear?

![gutenberg](https://user-images.githubusercontent.com/353790/27743183-29ca7a8a-5d89-11e7-8bf6-c667652a1085.gif)

**Comment by mtias** [comment] 2017-06-30 20:19
Yes, see #1561 :)

**Comment by nylen** [comment] 2017-07-01 08:40
Duplicate of #1561.

**Closed by nylen** 2017-07-01 08:40 UTC
