### ISSUE TITLE
Minor styling glitch: the Author select is too large

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3432] opened 2017-11-10 16:09 UTC
The authro select is too large and makes the whole sidenar horizontally scrollable:

![screen shot 2017-11-10 at 17 05 08](https://user-images.githubusercontent.com/1682452/32667028-bbfae17e-c639-11e7-9cb8-964b5a66d4ed.png)

Also, worth reminding all the labels are translatable so in other languages "Author" could be way longer and I doubt the label and select can stay on the same line.

**Comment by aduth** [comment] 2017-11-10 16:13
Might be specific to having an option in the dropdown with a very long name? If so, could use a max width on the `select`.

**Comment by Rahmon** [comment] 2017-11-14 11:58
What I have to do to see author select?

**Comment by aduth** [comment] 2017-11-14 13:05
@Rahmon It would require that your site has at least two users who are capable of authoring posts.

**Comment by aduth** [comment] 2017-12-04 16:26
Fixed by #3786

**Comment by aduth** [comment] 2017-12-13 18:43
This appears to still be an issue in IE11.

![IE11 overflow](https://user-images.githubusercontent.com/1779930/33956092-91ea2d0e-e00b-11e7-92a6-7c0acbab553b.png)

cc @laras126

**Comment by Soean** [comment] 2018-07-12 16:47
Can't reproduce the issue in IE11 / Safari / Chrome / FF, if someone can please reopen this ticket.

**Closed** 2018-09-04 13:49 UTC
Labels: Browser Issues, Good First Issue, [Type] Bug
