### ISSUE TITLE
Floating blocks hide toolbar

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#16055] opened 2019-06-08 13:01 UTC
**Describe the bug**

If you have an image floated to the left, it can cover up the block toolbar for paragraphs wrapping around it.

**To reproduce**

Insert an image in the middle of a bunch of short paragraphs.

**Expected behavior**

Block toolbar should always be visible and usable.

**Screenshots**

![cant see the toolbar](https://user-images.githubusercontent.com/3314354/59147619-e6949200-89f5-11e9-9909-57156d228c23.png)

**Comment by ValentinGratz** [comment] 2019-06-09 12:30
Did you try to go up the page, to see if the edit menu does not appear at the bottom of the block?

Otherwise, for future releases, ask to include this possibility.

**Comment by jaybeaton** [comment] 2019-06-11 16:38
This appears to be a duplicate of WordPress/gutenberg/#12758

**Comment by jasmussen** [comment] 2019-06-12 09:15
This issue was fixed by #15537 🎉

<img width="806" alt="Screenshot 2019-06-12 at 11 14 44" src="https://user-images.githubusercontent.com/1204802/59338796-557a2f80-8d03-11e9-981c-3cdc20a99c24.png">

☝️ Okay that's not the greatest look, but it's _technically accurate_ with how floats work. Thanks for the report!

**Closed by jasmussen** 2019-06-12 09:15 UTC
Labels: Blocks, [Type] Bug

**Comment by bph** [comment] 2019-07-08 19:25
Seems this was only fixed for paragraph block. 

Here are two examples from today (6.1)  involving the cover block. 
the heading block, only partially hidden. 
![Screen Shot 2019-07-08 at 3 19 20 PM](https://user-images.githubusercontent.com/39980/60836622-19b47780-a194-11e9-8fb4-bbfbdd093ce1.png)
Gallery Block's toolbar is almost entirely hidden. 

![Screen Shot 2019-07-08 at 3 17 54 PM](https://user-images.githubusercontent.com/39980/60836665-2b961a80-a194-11e9-9928-50b61cd84d63.png)

it seems to be connected to the Cover Block as the gallery's toolbar works well with the paragraph block. 
![Screen Shot 2019-07-08 at 3 22 53 PM](https://user-images.githubusercontent.com/39980/60836749-5d0ee600-a194-11e9-8f9a-35e8e5b6b69a.png)

**Comment by jasmussen** [comment] 2019-07-09 06:29
@bph good catch! Would you mind opening a new ticket? Thank you.
