### ISSUE TITLE
Add drag-and-drop to List View

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#32403] opened 2021-06-02 14:28 UTC
Once collapsible container blocks (https://github.com/WordPress/gutenberg/pull/32117) arrive, it might be nice to explore adding drag-and-drop capabilities to List View. 

Arranging blocks this way on the canvas can feel quite uncomfortable due to the real estate that larger blocks occupy, and the amount of scrolling-while-dragging that can be required. Greater finesse can be exercised in List View since all blocks are the same size. 

Another benefit is the precision in List View due to the document structure being clearly visible – this isn't always easy to determine on the canvas, especially when the nesting gets quite deep.

Here are the interactions we might concentrate on:

* Arranging blocks at the same level
* Dragging a block down a level in the tree (IE from the root level in to a group), accounting for when the target container is either open or closed
* Dragging a block up a level, IE from a group to the root level of the doc.
* Dragging a block to an incompatible area of the document, IE dragging a Column block to the root level
* Any others that I'm missing? :D 

For design we can most likely build on the excellent work @shaunandrews did last year (https://github.com/WordPress/gutenberg/issues/24029#issuecomment-670662555), coupled with the latest on-canvas drag and drop interactions. 

---

Figma file for design exploration [here](https://www.figma.com/file/VaNb38S2OOihqSu2lAIIhN/List-view-Drag-and-drop?node-id=2901%3A13866).

**Comment by jameskoster** [comment] 2021-06-03 12:54
I think most of these are fairly straight-forward. I outlined the flows in Figma [here](https://www.figma.com/file/VaNb38S2OOihqSu2lAIIhN/List-view-Drag-and-drop?node-id=603%3A3798).

The most complicated is when you drop a block from the root level into a closed container within another container. Here's a video detailing that interaction:


https://user-images.githubusercontent.com/846565/120647790-e27b9d80-c472-11eb-8e6f-aa6f6709d61d.mp4

**Comment by jasmussen** [comment] 2021-06-04 06:24
This is cool, but is it a duplicate of #29727?

We might want to consolidate just to have a central point of conversation, but I love your design here, we should move it over!

**Closed as completed** 2021-06-04 08:51 UTC
Labels: Needs Design Feedback, [Feature] List View
