### ISSUE TITLE
Show Welcome Guide on first visit to Customizer Widgets screen and Appearance Widgets screen

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#30887] opened 2021-04-16 03:53 UTC
Hi all, opening this issue to discuss the possibility of showing the "Welcome to the block editor" modal that appears on first visit to the post editor upon first visit to the Customizer Widgets screen.
 
It would be great to add this for the standalone Widgets screen as well, but just focusing on the Customizer for now as the modal appearing on this screen is less straightforward in terms of sizing and placement.

![welcome-modal](https://user-images.githubusercontent.com/77359364/114961709-5e744480-9e37-11eb-83e2-63f1bdc3c9a2.jpg)

One idea is to repurpose the content from the existing modal (left) and display it as a slightly more compact version (right). The compact version could use the same sizing for internal components like the close button, carousel dots, and type. The GIF could also remain the same aspect ratio so the existing assets can be reused.

While the modal _could_ appear centered over the full page area without sizing adjustments, it feels a lot more communicative IMO when only placed over the editor canvas area:

![welcome-modal-3](https://user-images.githubusercontent.com/77359364/114964194-3affc880-9e3c-11eb-8433-1d368f59f72e.jpg)

Ideally once the ellipses menu is incorporated into the Customizer top bar area (#30886), the modal will be accessible from the "Welcome Guide" option in the menu as well.

**Comment by karmatosed** [comment] 2021-04-16 11:06
> It would be great to add this for the standalone Widgets screen as well, but just focusing on the Customizer for now as the modal appearing on this screen is less straightforward in terms of sizing and placement.

I wonder what problem this is solving so would love to dig a little into that. My guess is you are looking to solve the first experience of wondering what the editor is now it's in this area? Is that correct?

I think the problem with reusing this in the size of space is that the space is smaller and also it was designed to be used in a different setting. That doesn't mean that the useful elements of it couldn't be taken out though. Perhaps it shouldn't overlay but be a top section to the block area? However, I think it's worth exploring would just some copy be better than a step through guide in this interface.

**Comment by critterverse** [comment] 2021-04-16 14:11
This is super helpful feedback, thanks @karmatosed! ❤️

>I wonder what problem this is solving so would love to dig a little into that. My guess is you are looking to solve the first experience of wondering what the editor is now it's in this area? Is that correct?

This Welcome Guide feels especially important for users who may not have encountered the block editor in _any_ context before.

>Perhaps it shouldn't overlay but be a top section to the block area? However, I think it's worth exploring would just some copy be better than a step through guide in this interface.

I'm a fan of the Welcome Guide format because I think it's a nice layer of user-friendliness that's often missing in WordPress (plus amazing GIFs!). Just thinking out loud but I wonder if some of the weirdness around it being an overlay with multiple steps could be resolved by trying something like this:

![welcome-guide](https://user-images.githubusercontent.com/77359364/115036862-e12eeb00-9e9b-11eb-8ea6-5d99f1100257.jpg)

^ In this version, the overlay effect could be a little more harmonious with the sidebar area if the modal expands to fit the full height of the sidebar. I also tried incorporating the most high-level information from the modal in a single step to avoid the need for a carousel, which I think could work as long as it doesn't feel too dense for a single screen 🤔

Quick look at how this might work on a shorter screen:

https://user-images.githubusercontent.com/77359364/115036911-ed1aad00-9e9b-11eb-95e4-112a941bd85c.mov

**Comment by karmatosed** [comment] 2021-04-17 15:49
> This Welcome Guide feels especially important for users who may not have encountered the block editor in any context before.

I appreciate that, it's an interesting problem as there is a new discovery point by having the editor in the customizer. 

> ^ In this version, the overlay effect could be a little more harmonious with the sidebar area if the modal expands to fit the full height of the sidebar. I also tried incorporating the most high-level information from the modal in a single step to avoid the need for a carousel, which I think could work as long as it doesn't feel too dense for a single screen 

I much prefer however more harmonious this can be, I also appreciate you are taking an interface designed for a different situation. I guess that's where I wonder about taking the copy over the entire welcome guide into this space.

In seeing this one thing struck me, I think calling it 'widgets block editor' might also bring confusion. Just putting on my 'not me' hat for a moment and thinking as someone that might not know 'all editors are the same just in different places', it makes it sound daunting like there are multiple editors and I therefore might need to learn multiple experiences.

I sympathise with you trying to work on this, it's a wooly problem.

**Comment by critterverse** [comment] 2021-05-12 19:23
Hi all, have a few updates on the Welcome Guide!

I’m adjusting this issue to also include a Welcome Guide for the Appearance > Widgets editor. This screen could use the normal Welcome Guide format and for the Customizer, it could be a condensed version of the guide that hits the most top-level info on one screen.

Based on some early feedback around it being a little weird to have the overlay/modal appear over the sidebar area, I’ve revised the Customizer design a bit so that it is no longer a modal and can be dismissed via a “Got it” button.

I’m not entirely sure what’s possible here from a technical standpoint but wanted to float an idea about showing two different versions of the Welcome Guide — one for users with existing/customized widgets, and another for new users. For new users, the messaging could be more generally about blocks and block areas, and for legacy users it could include the details about opt-ing out via the Classic Widget plugin, if we decide to go that route.

Side note: There are various ongoing discussions re: considerations for opt-in and opt-out of these screens. This design is based on an idea that came up recently in the [Core Editor chat](https://make.wordpress.org/core/2021/05/06/editor-chat-summary-5th-may-2021/) on the Making WordPress Slack about potentially using the Welcome Guides as a place to provide clear information about how to install the Plugin to easily opt-out.

Here’s what I was thinking for the different variations.

Customizer screen legacy user:

![Customizer - legacy user](https://user-images.githubusercontent.com/77359364/118030847-cf722380-b333-11eb-8ed8-475400d99d07.jpg)

Customizer screen new user:

![Customizer - new user](https://user-images.githubusercontent.com/77359364/118029299-07786700-b332-11eb-9f7c-3869ebb00b7f.jpg)

Appearance screen legacy user:

![Appearance - legacy user](https://user-images.githubusercontent.com/77359364/118029782-7d7cce00-b332-11eb-8cfc-fd90ed7f9147.jpg)

Appearance screen new user:

![Appearance - new user](https://user-images.githubusercontent.com/77359364/118029499-3989c900-b332-11eb-8ff2-241b2be42bc5.jpg)

**Comment by noisysocks** [comment] 2021-05-17 05:16
Moving this to Needs Dev as this looks like it's ready for a dev to pick it up and run with it.

**Closed as completed** 2021-05-19 07:59 UTC
Labels: Needs Design Feedback, [Feature] Widgets Customizer
