### ISSUE TITLE
Cover block should have an "Insert from URL" like Video Block does.

### ISSUE THREAD

**Issue by kauaicreative** [WordPress/gutenberg#41880] opened 2022-06-22 16:58 UTC
## What problem does this address?
Cover block should have an "Insert from URL" like Video Block does.
Link to external resources without opening code view

**Comment by Mamaduka** [comment] 2022-06-23 07:24
Probably a duplicate of #10853.

**Comment by akasunil** [comment] 2022-06-23 12:08
@kauaicreative please check PR [41908](https://github.com/WordPress/gutenberg/pull/41908)

**Closed as completed** 2022-06-23 12:08 UTC
Labels: [Status] Needs More Info, [Status] Duplicate, [Block] Cover
