### ISSUE TITLE
Moving Query Loop nested blocks with Grid View

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37645] opened 2021-12-28 19:59 UTC
### Description

In WordPress 5.9 beta 4 using the Twenty Twenty theme (not a block theme), I'm seeing some strange disappearing/moving nested blocks within the Query Loop upon selection if you use the Grid View. This only seems to happen if you have the Query Loop in different column setups from what I can tell with testing. cc @ntsekouras 

### Step-by-step reproduction instructions

1. Use WordPress 5.9 Beta 4.
2. Add a Query Loop
3. Select the first pattern. 
4. Switch pattern to "grid view" in the block toolbar. 
5. Try selecting individual posts to edit with the Query Loop. Find they move around/disappear. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/147602418-2dd8026f-7a57-41e4-a8e6-a1bf20de5db4.mov

https://user-images.githubusercontent.com/26996883/147602538-b1de1712-7124-4b82-a015-263b8a4ffa9d.mov

### Environment info

- WordPress 5.9 beta 4
- No Gutenberg
- Twenty Twenty theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment] 2022-01-04 13:47
I can repro this, by using the Twenty Twenty theme as prescribed, and adding a few very bare-bones posts (title and a bit of content), and creating a page with the Query Loop block. It seems indeed like this might be a duplicate of #37681 (but I'm not 100% sure).

I've left a [comment](https://github.com/WordPress/gutenberg/issues/37681#issuecomment-1004823649) there that points to what I believe might be a relevant code change.

**Comment by ntsekouras** [comment] 2022-01-04 20:47
Thanks for reporting this Anne! I'll close this one in favor of https://github.com/WordPress/gutenberg/issues/37681 (even if yours was first 😄 ) because it has also the details about the problem in the implementation.

**Closed as completed by ntsekouras** 2022-01-04 20:47 UTC
Labels: [Type] Bug, [Block] Query Loop
