### ISSUE TITLE
Select size of inline image

### ISSUE THREAD

**Issue by jdhau** [WordPress/gutenberg#16920] opened 2019-08-06 06:20 UTC
Hi,

It’s a bit frustrating that you can’t select the image size of inline images. Yes, you can enter the size in pixels, but this just results in a resized version of the main image, which is bad for page speed. This is especially annoying when you want to insert an image in a table cell, eg for a product comparison table.

A selector that allows you to insert any of the available image sizes (thumbnail, medium, full size, etc.) version of the image would be highly preferable.

Thanks!

**Comment by karmatosed** [comment] 2019-08-07 09:08
@jdhau I am having a little trouble understanding where you are having an issue, apologies about that. Can I check are you using the media block or adding an image? On the media + text block, for example, you can drag like this:

![image](https://user-images.githubusercontent.com/253067/62610147-fa2b7e80-b8fa-11e9-8f3c-683f214e06a0.png)

For just the image block you can do the following in the sidebar:

![image](https://user-images.githubusercontent.com/253067/62610192-129b9900-b8fb-11e9-979d-b603f5e664aa.png)

You mention adding to a table cell, are you pasting that in?

**Comment by jdhau** [comment] 2019-08-07 09:32
Hello Tammie,

The issue I’m having is that you can’t select one of wordpress’
pre-generated sizes for an inline image. This means than any inline image
is scaled down on the front-end, which slows down the website, because it
has to request and downloads the full-size image, and apply resizing on the
fly.

Does that help?

John

**Comment by youknowriad** [comment] 2019-11-19 13:02
Duplicate of #7764

**Closed by youknowriad** 2019-11-19 13:02 UTC
Labels: [Status] Needs More Info
