### ISSUE TITLE
Move the blocks "More" button (ellipsis) to the toolbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#9074] opened 2018-08-17 09:09 UTC
The "More" button for blocks is increasingly becoming more useful, to the point where it now contains features that are starting to become critical to the use of the block

<img width="311" alt="screen shot 2018-08-17 at 11 06 09" src="https://user-images.githubusercontent.com/1204802/44257851-90a7f100-a20d-11e8-882b-32a86df0f481.png">

But in being auto-hiding side-UI for the block, it is not as discoverable as it perhaps deserves to be. 

Additionally, when the block is shown in nested contexts, there are often stacking issues with the side UI. This is also being discussed in https://github.com/WordPress/gutenberg/issues/6224, and although removing just the More button doesn't _solve_ that, it mitigates it a fair bit by addressing some of the stacking issues you might see if you have two blocks side by side.

<img width="683" alt="screen shot 2018-08-17 at 11 07 31" src="https://user-images.githubusercontent.com/1204802/44257918-c2b95300-a20d-11e8-8de9-2bf8e4c81051.png">

In that vein, moving the More button to the toolbar improves two issues:

1. Discoverability
2. Nested block UI

The challenge this brings with it is: the block toolbar grows wider. How do we address this especially in nested situations? This is something we need to tackle even without the More button in the toolbar, so let's look at addressing that as part of #9075. 

Mockup:

![wide](https://user-images.githubusercontent.com/1204802/44257953-ebd9e380-a20d-11e8-84b8-57a8b147eb39.png)

Tasks to accomplish this move:

- [ ] Move More Button/ellipsis from side UI to toolbar
- [ ] Make sure it works with a fixed to the top toolbar, and with multi select

**Comment by jasmussen** [comment] 2018-08-17 09:30
Here's a mockup showing the toolbar be 100% full-width:

<img width="602" alt="screen shot 2018-08-17 at 11 28 05" src="https://user-images.githubusercontent.com/1204802/44259133-f77ad980-a210-11e8-96a5-c34f13d0e290.png">

I don't personally have a strong opinion either way.

**Comment by chrisvanpatten** [comment] 2018-08-17 12:05
I definitely prefer the look of a full-width toolbar, but it does decrease the surface area available to click through to the block above. Visually, though, it's great.

This is a great step, and I am hopeful it can make it in!

**Comment by ZebulanStanphill** [comment] 2018-08-17 15:06
I think I would prefer it to be on the left for the sake of taking up as small an area as possible, but since having it on the right provides a large potential drag area, I really would not mind that much either way. Left or right, I think this is a good move and a definite improvement over `master`.

Also noting that the issues mentioned in #8880 would be significantly reduced if this was implemented.

Please, please, _please_ do this.

**Comment by talldan** [comment] 2018-08-20 04:30
Does the icon in that location make it seem like it might display more formatting tools? That was my first reaction, I think because of the similarity of the icon to an ellipsis.

I prefer the mockup with it on the right for that reason.

**Comment by jasmussen** [comment] 2018-08-20 06:36
> Does the icon in that location make it seem like it might display more formatting tools? That was my first reaction, I think because of the similarity of the icon to an ellipsis.

Possibly, though I don't think it's a big issue since it takes a single click to learn what's in that menu, and what's there is always the same across blocks. I definitely understand what you're saying, but I don't think it's a blocker to the discoverability issues moving the button there solves. 

Note that even if we do go with the button on the right, in thin contexts the button will still snuggle up next to the other icons as the toolbar grows thin.

**Comment by jasmussen** [comment] 2018-08-20 09:27
> One other challenge is that currently the block settings menu can be clicked without the block being selected - it just needs to be hovered. The toolbar behaves slightly differently and is only visible once the block is selected.

Yes, this would be a tradeoff: in this design, the ellipsis menu is only available after first having selected the block. 

However I think this tradeoff is worth it.

**Comment by ZebulanStanphill** [comment] 2018-08-20 14:31
@jasmussen I agree, the tradeoff is **definitely** worth it, especially now that there are keyboard shortcuts for most of the options in the ellipsis menu.

**Comment by nosolosw** [comment] 2018-08-21 10:58
Would it make sense to use this toolbar as the drag handler? It could help alleviate some problems with refactoring drag and drop to use the hover label (there is no hover label for classic blocks and the selected block doesn't have it either). If we wanted to do so, we'd perhaps want to show the toolbar on hover instead of selecting a block. It'd help to discover the options menu (now it's shown on hover) as well as the drag-n-drop handle.

**Comment by ZebulanStanphill** [comment] 2018-08-21 13:57
@nosolosw I think the toolbar (as in, the whole thing including the buttons, like what GNOME does) should be a drag handle, but that does not mean it should be the only one. The up/down movers could also double as a drag handle, which would be available on hover.

**I would strongly caution against showing the toolbar on hover.** The UI for hovering over blocks should be as light as possible, and my mockups in #6224 were often shot down for this very issue. Even my latest one is still considered too heavy, and I can't deny it does add quite a bit of weight:
![image](https://user-images.githubusercontent.com/19592990/44405750-99efd100-a51f-11e8-9ff7-c06328084aa2.png)
![image](https://user-images.githubusercontent.com/19592990/44405690-7dec2f80-a51f-11e8-8995-b9ca942a4e80.png)

(I think that for my next mockup, I will leave the up/down movers on the side and turn the sibling inserter into a floating control that looks and acts similar to to the up/down movers, but appears below the block.)

**Comment by jasmussen** [comment] 2018-08-22 06:42
> Would it make sense to use this toolbar as the drag handler? It could help alleviate some problems with refactoring drag and drop to use the hover label (there is no hover label for classic blocks and the selected block doesn't have it either). If we wanted to do so, we'd perhaps want to show the toolbar on hover instead of selecting a block. 

I don't think we'll want to show this toolbar on hover, as this only adds weight to an already heavy UI. I know that @mtias has some thoughts on drag handles.

**Comment by youknowriad** [comment] 2018-08-22 10:37
Question here: Where to show the menu if the "toolbar is fixed to top" especially if we choose to right align the button?

**Comment by jasmussen** [comment] 2018-08-22 10:39
> Question here: Where to show the menu if the "toolbar is fixed to top" especially if we choose to right align the button?

Same as today, and we would not right align the block ellipsis, it would have to be present in sequence with the others I'd think.

**Comment by mtias** [comment] 2018-08-22 11:01
This should also apply to multi-select (would be good to have one mockup for it), which largely depend on also having the multi-select toolbar ready.

**Comment by jasmussen** [comment] 2018-08-22 11:05
Here's a very quick and dirty mockup for multi select:

<img width="728" alt="screen shot 2018-08-22 at 13 04 31" src="https://user-images.githubusercontent.com/1204802/44460042-f3352e80-a60b-11e8-80d9-c01ac1c198cf.png">

Also, the PR for multi select toolbar seems underway here https://github.com/WordPress/gutenberg/pull/7635

**Comment by mtias** [comment] 2018-08-22 11:08
That works much better than what we have, I think.

**Comment by folletto** [comment] 2018-08-22 17:06
Some random feedback points:

1. I find great to reduce the number of "tool areas", as Riad said. Definite +1 from me.
2. I find the "100% full-width" version to be difficult because it will cover the entire line of whatever is above, instead of minimizing the covering impact. Also: large screens will split the two too much (same problem we have now tho so not a regression, but would feel more stretched).
3. I agree with Zebulan that it shouldn't be on hover, same on being "a drag handler but not the only one".
4. When "toolbar is fixed to top" I think would be totally fine in having the ••• menu there too. Seems more consistent and intuitive if the whole bar moves.
5. It also seems more consistent on mobile, which is a great win as mobile is massively important. ;)

**Comment by youknowriad** [comment] 2018-08-22 22:52
@jasmussen on multi-selection, sometimes there's no block switcher, is it fine to show only the more menu in that case?

**Comment by youknowriad** [comment] 2018-08-22 22:52
Sorry, these buttons are too close :) (comment, comment and close)

**Comment by jasmussen** [comment] 2018-08-23 03:58
> on multi-selection, sometimes there's no block switcher, is it fine to show only the more menu in that case?

Yes then it's just the more menu.

**Comment by ZebulanStanphill** [comment] 2018-08-23 17:02
One thing that just occurred to me is that this change would make it considerably easier to interact with floated blocks, because the option to remove them would now be right above them, rather than on the far right even when the block was floated to the left.

Of course, the up/down movers would still have the same issue that the ellipsis had, but this would definitely be an improvement over the current situation. If you could use the toolbar as a drag handle, then that would reduce the moving issue, though it would not be fully resolved, as the up/down movers should always be usable, with drag-and-drop being a secondary bonus.

Similarly, the overlapping ellipsis menu issue you get with blocks on the right column of a Columns block would be fixed as well.

In general, I think this change would fix pretty much all the issues with the current ellipsis menu button. :+1:

**Comment by youknowriad** [comment] 2018-09-05 09:55
closed by #9572

**Closed by youknowriad** 2018-09-05 09:55 UTC
Labels: [Type] Enhancement
