### ISSUE TITLE
Block: Gallery - Hovering last item shows actions

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#21109] opened 2020-03-24 15:34 UTC
**Describe the bug**

<img width="646" alt="Screen Shot 2020-03-24 at 11 30 41 AM" src="https://user-images.githubusercontent.com/2322354/77445102-09483980-6dc3-11ea-978c-ae7df68a2713.png">

When the Gallery block is selected, hovering the last item shows the item actions (move left/right and close).

Clicking on these actions do nothing. They're just visible on hover.

**To reproduce**
1. Add a gallery block
2. Add at least 1 image
3. Deselect the Gallery block (or click the editor background)
4. Hover mouse on last item

**Expected behavior**
No actions should be visible unless the Gallery item is selected.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 80

**Comment by talldan** [comment] 2021-07-21 05:29
I can't reproduce this now, so closing the issue.

**Closed by talldan** 2021-07-21 05:29 UTC
Labels: General Interface, [Block] Gallery, [Type] Bug
