### ISSUE TITLE
No Indication that Panel Body cannot be collapsed

### ISSUE THREAD

**Issue by milesdelliott** [WordPress/gutenberg#9889] opened 2018-09-14 00:07 UTC
**Describe the bug**
The Panel Body component accepts an `opened` prop which if passed will force the panel open. When the panel is forced open there is no indication that the panel cannot be collapsed( visually or in the code)

**Expected behavior**
I think at a minimum the arrow should be hidden, and maybe a disabled state on the button, or rendering a different element other than button. I'm not sure what other indications should be there

I have a branch ready to remove the arrow icon, but I figured I would open this issue to get feedback on what more should be done.

**Screenshots**
This Panel cannot be collapsed
![screen shot 2018-09-13 at 7 19 46 pm](https://user-images.githubusercontent.com/11066701/45522350-79b6d900-b790-11e8-9700-b256c50db8f5.png)

This panel can be collapsed
![screen shot 2018-09-13 at 7 19 54 pm](https://user-images.githubusercontent.com/11066701/45522354-7d4a6000-b790-11e8-8f05-4297e6dbf4f2.png)

**Additional context**
Using Gutenberg version 3.8

**Comment by karmatosed** [comment] 2018-10-08 19:55
I would say the arrow should be hidden if it can't be collapsed, there seems no point in showing the arrow if that is the case.

**Comment by rodrigoi** [comment] 2019-03-09 19:42
I think I'll close this since it'sa duplicate of #9522 .

**Closed by rodrigoi** 2019-03-09 19:42 UTC
Labels: UI Components, [Type] Enhancement
