### ISSUE TITLE
Add Post Comments Form block to the Comments Query Loop template.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40225] opened 2022-04-11 12:04 UTC
### Description

I am testing: https://make.wordpress.org/test/2022/04/08/help-test-the-comments-blocks-for-wordpress-6-0

Initially we start out with the default Post Comments block but we switch over to Comments Query Loop block in the Single Post FSE. Going to a post I do not see the comments area in place. Switching back to the old Post Comments block I do see the comments area in place.

### Step-by-step reproduction instructions

1. Remove the Post Comments block.
2. Add the Comments Query Loop block.
3. Check the frontend and go to a single post.
4. Check the Hello post and see that it contains a comment.
5. Go to another post.
6. It does not contain a comment area.

### Screenshots, screen recording, code snippet

Frontend:
With the older Post Comments block and the Comments Query Loop block.
![Screenshot 2022-04-11 at 13 53 58](https://user-images.githubusercontent.com/5323259/162734354-2a46a98e-c7f3-439b-8e65-0d341e9d5fc7.jpg)

Removing the Post Comments block but keeping the Comments Query Loop block there is no comments area.

![Screenshot 2022-04-11 at 13 54 25](https://user-images.githubusercontent.com/5323259/162734389-dc24ebec-246d-46eb-aed1-f0cbe940ef9a.jpg)

Which makes me wonder if I did something wrong.... 
I even made a new post to see if the comments area would show up. It did not..
![Screenshot 2022-04-11 at 13 58 37](https://user-images.githubusercontent.com/5323259/162734841-5cc16a3b-79da-4687-ae40-27a102b60582.jpg)

Hmm.... 

### Environment info

WP 5.9.3
Gutenberg 13.0 RC
Twenty Twenty Two

Desktop Server local test site
OSX 12.2.1
Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by paaljoachim** [comment] 2022-04-11 15:30
AHA thanks to @amustaque97 

I noticed the error I made.
There is a Post Comments Form. Which needs to be added it seems for the comment reply box to show up.
The Comments Query Loop block is then added below this...... or so I assume. I will need to experiment.

**Comment by ockham** [comment] 2022-04-11 15:35
> AHA thanks to @amustaque97
> 
> I noticed the error I made. There is a Post Comments Form. Which needs to be added it seems for the comment reply box to show up. The Comments Query Loop block is then added below this...... or so I assume. I will need to experiment.

Yeah, that's correct. The Comments Query Loop really only shows the comments that have already been posted under the current post (plus pagination links). In order to allow the user to post a new comment, you need to add the Post Comments Form block. Apologies if this wasn't clear!

**Comment by paaljoachim** [comment] 2022-04-11 15:39
Hey Bernie.

I compared the Post Comments block = to the Comments Query Loop block and expected the same features.
Now I know they are not. Good to know.

**Comment by ockham** [comment] 2022-04-11 15:48
> Hey Bernie.
> 
> I compared the Post Comments block = to the Comments Query Loop block and expected the same features. Now I know they are not. Good to know.

Yeah, that's a fair assumption 🤔  We might need to clarify that.

**Comment by ockham** [comment] 2022-04-11 17:39
I think I'd like to close this issue, since it's the expected behavior of the Comments Query Loop block. If anything, we need to update the Call-for-testing to clarify this.

@paaljoachim LMK if you disagree, we can re-open if needed!

**Comment by paaljoachim** [comment] 2022-04-11 19:37
@ockham 

I believe the best solution would be to have a new default in the Single Post FSE template.
Instead of the Comments block the new default would be the Post Comments Form block and the Comments Query Loop block. This way there is no question as both block will automatically be added, and one would see the comments area on the frontend.

**Comment by SantosGuillamot** [comment] 2022-04-12 06:58
We could also add the Post Comments Form block to the [Comments Query Loop template](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/comments-query-loop/edit.js#L11-L67), the same way we are adding the inner blocks directly. This way, whenever the Comments Query Loop is added, the Post Comments Form block would show. Do you think that could help?

**Comment by paaljoachim** [comment] 2022-04-12 07:09
Hi @SantosGuillamot Mario

Yes. That would be the best solution! As it keeps everything that has to do with comments in one parent container block.

**Comment by paaljoachim** [comment] 2022-04-12 07:11
I reopened the issue and changed the title.

**Comment by SantosGuillamot** [comment] 2022-04-12 07:53
I have just created this [Pull Request](https://github.com/WordPress/gutenberg/pull/40256) to work on it.

**Closed as completed** 2022-04-22 10:33 UTC
Labels: [Type] Bug, [Block] Comments
