### ISSUE TITLE
Padding range control not working with single side border

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#49648] opened 2023-04-06 22:33 UTC
### Description

If you have a column or group block (might happen elsewhere as well), and you add a single border (a border to one side of the column or group), then try to add padding, the range control does not work.

### Step-by-step reproduction instructions

1. create a new page
2. add a group block
3. add a single border (bottom border of 1px for example)
4. then try to add padding

### Screenshots, screen recording, code snippet

<img width="1317" alt="Screen Shot 2023-04-06 at 4 33 04 PM" src="https://user-images.githubusercontent.com/1781226/230505819-ecf3a588-e5ad-4f1d-81b3-9ad021695576.png">

### Environment info

- wp 6.2
- gutenberg 15.5.0
- mac 
- chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-04-09 04:55
@bradhogan 

Thank you for the report.

I also tested it and could not reproduce it. Am I missing something? It would be great if you could check to see if this problem also occurs in the default theme and if any other plugins are affecting it.

My test environment is:

- Gutenberg Plugin 15.5.0
- WordPress WordPress 6.3-alpha-55632

https://user-images.githubusercontent.com/54422211/230755087-5653b61d-d734-4347-ab3f-00289250ddb2.mp4

**Comment by bradhogan** [comment] 2023-04-09 22:22
@t-hamano Hey there.  Maybe try using WP 6.2.  Could also be the order with which you're testing.  See this example of the error when only using WP default 2023 theme with Gutenberg - https://soapbox.wistia.com/videos/45ZYaL2mvS

**Comment by t-hamano** [comment] 2023-04-10 05:56
@bradhogan 

Thanks for the info. I was able to reproduce it as well. However, this problem seems to reproduce itself in certain environments.

- ✅ Not reproduced in WordPress 6.2
- ❌ Reproduced after activating _the release version_ of Gutenberg plugin 15.5
- ✅ Not reproduced in the latest trunk Gutenberg

It may be a good idea to check again when plugin version 15.6 is released.

**Comment by Mamaduka** [comment] 2023-04-11 14:38
I can't reproduce it on the latest Gutenberg trunk with 2023 theme. Here's the markup generated by the editor.

<details><summary>The block markup</summary>

```
<!-- wp:group {"style":{"border":{"bottom":{"color":"var:preset|color|contrast","style":"solid","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-bottom-color:var(--wp--preset--color--contrast);border-bottom-style:solid;border-bottom-width:1px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)"><!-- wp:paragraph -->
<p>Testing</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
``` 

</details>

**Comment by t-hamano** [comment] 2023-05-13 14:04
Hi @bradhogan,

I tested again with Gutenberg 15.7.1, which is released as a plugin, but did not reproduce the problem.
I would like to close this issue as I believe it has been resolved.
If the issue has not been resolved, please feel free to reopen it at any time.

**Closed as completed by t-hamano** 2023-05-13 14:04 UTC
Labels: Global Styles
