### ISSUE TITLE
A few issues I've noticed

### ISSUE THREAD

**Issue by ArchivesofAdventure** [WordPress/gutenberg#9096] opened 2018-08-17 15:32 UTC
Here are a few things that I've had problems with:

1) Trying to create a link is a nightmare. The box to input the link only sometimes shows up and rarely will accept any text in the box.
2) Once you finally get the hyperlink in the box, it only sometimes will accept it. And when it does, all custom colors/sizes/etc don't appear anymore. The only way to change this is to turn the box into html and code it all manually
3) You should be able to change the code in reusable boxes
4) The "Preview" and the "Publish" buttons are way too close together. I get a heart attack everytime I press Preview because I don't want to accidentally publish an unfinished post

**Comment by tofumatt** [comment] 2018-08-17 16:13
Hi there! Thanks for taking the time to file issues with Gutenberg. The first issue has been solved in the 3.6.2 release, which we just shipped recently. Really sorry about that, it was a bug! 😓

It's difficult for us to address multiple issues in one GitHub issue; we generally try to keep one task per issue. I'm going to close this issue because it's a bit too much in one issue, but if you could submit each issue separately, preferably with steps to reproduce, screenshots, etc. that would be great.

**Closed by tofumatt** 2018-08-17 16:13 UTC
Labels: Invalid

**Comment by designsimply** [comment] 2018-08-17 17:16
> custom colors/sizes/etc for links

Tracking in https://github.com/WordPress/gutenberg/issues/6254 (note that it is in the "Customization (awaiting triage) project and that means it's on the list to be considered as a planned update). Adding a comment there about your use case and specifics would be super helpful!

> You should be able to change the code in reusable boxes

I found a related comment in a past discussion at https://github.com/WordPress/gutenberg/issues/4305#issuecomment-377911225 that says, "Creating and optionally detaching [shared/reusable blocks] are a way for authors to create a custom block without having to write code." If you open a separate feature request asking for the ability to edit code for shared/reusable blocks, please include a use case or explanation about why you feel it's an important feature to you and how you plan to use it.

> The "Preview" and the "Publish" buttons are way too close together.

Great feedback! Please consider making a separate issue for this.
