### ISSUE TITLE
Table block has missing children and attributes

### ISSUE THREAD

**Issue by caraya** [WordPress/gutenberg#5753] opened 2018-03-22 23:37 UTC
## Issue Overview

Working with a fresh compile of 2.4 built today. 

The table block has missing children that cannot be added from the visual editor, but they can be added through code view. Some of the elements missing are:

* caption
* summary
* details
* colspan and rowspan to group cells together
* scope

While it is possible to add them from the HTML editor it's not easy or intuitive. The edit table drop down menu only offers ways to add and remove columns and rows... I would expect to see more table edit functionality under it. 

Is this working as intended and not meant for complex tables?

## Screenshots / Video

<img width="872" alt="screen shot 2018-03-22 at 16 12 23" src="https://user-images.githubusercontent.com/409841/37803815-42c37ede-2dee-11e8-8765-e68b7e46fee6.png">
<img width="1058" alt="screen shot 2018-03-22 at 16 31 15" src="https://user-images.githubusercontent.com/409841/37803979-39226998-2def-11e8-9399-eee8aee3ed02.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment] 2018-04-27 19:09
This is working as intended and not meant for complex tables. It could be extended to do that but right now let's close this up as intended.

**Closed by karmatosed** 2018-04-27 19:09 UTC
Labels: [Type] Enhancement

**Comment by caraya** [comment] 2018-04-28 22:44
Then please explain that in the docs somewhere. If it's not meant for complex tables it should say so somewhere to set expectations accordingly...

**Comment by karmatosed** [comment] 2018-04-30 13:01
@caraya absolutely this is something we can add to the docs. Would you like to make a PR for this yourself or have it added?

**Comment by changeling** [comment] 2019-12-27 04:45
Are there plans to extend gutenberg table blocks to a mosre robust implementation including the mentioned elements. At least `colspan`?

Alternatively, what is the preferred design for equivalent structures?

**Comment by abursill** [comment] 2020-03-05 06:14
Any way to stop Gutenber stripping out the valid HTML code colspan when converting to blocks. it is ridiculous and is destroying a site I am working on,
