### ISSUE TITLE
Page Attributes for a Custom Post Type

### ISSUE THREAD

**Issue by saltnpixels** [WordPress/gutenberg#8307] opened 2018-07-30 18:52 UTC
**Describe the bug**
I cannot set a post type as a child to another when the post type has hierarchal capabilities.
I created a "documentaiton" post type and found this bug when trying to set the parent of one.
As you can see below It works via the classic editor but not Gutenberg.

![screenshot 2018-07-30 14 43 03](https://user-images.githubusercontent.com/11615474/43416939-a9e4a280-9407-11e8-9f35-b610912cd9a1.png)
![screenshot 2018-07-30 14 43 23](https://user-images.githubusercontent.com/11615474/43416940-a9ed3fd0-9407-11e8-8c05-9f3e85563826.png)

**To Reproduce**
1. Create a post type and give it WP REST API capabilities, so gutenberg works.
2. Add hierarichal capabilities to the post type
3. Try making a post a child of another

**Expected behavior**
I want the parent dropdown.

**Desktop (please complete the following information):**
 - iMac 2011, MacOs High Sierra
 - Browser Chrome

**Additional context**
Searching I found this issue was considered solved. :/

**Comment by designsimply** [comment] 2018-07-31 16:03
@saltnpixels thanks for including screenshots and steps! Can you note which version of Gutenberg you tested with so that's included with this issue for reference? May I also ask where you found this issue was considered solved?

**Comment by saltnpixels** [comment] 2018-07-31 16:16
Thanks for Responding.

I did a google search and I figured if it was merged then that means it was fixed.
#4175

I am using gutenberg 3.3.0

**Comment by designsimply** [comment] 2018-07-31 18:07
Ace. Thanks. I added the `Needs Testing` label to see if we can get some help testing and verifying that this is a regression.

**Comment by Clorith** [comment] 2018-08-03 10:51
Just tested this, and it sends an unbound request for the post type to `http://gutenberg.test/wp-json/wp/v2/documents?context=edit&per_page=-1&exclude=58&parent_exclude=58&_fields=id%2Cparent%2Ctitle&orderby=menu_order&order=asc`

The problem is the `per_page=-1` bit, as it triggers the protection at https://github.com/WordPress/gutenberg/blob/master/lib/rest-api.php#L491

**Comment by saltnpixels** [comment] 2018-08-22 14:47
This seems to working now.

**Comment by tracyapps** [comment] 2018-12-05 19:55
i'm having this same issue. i just installed the latest version about 5 hours ago, so i'm assuming that's the latest version (and most likely the version that is launched  **tomorrow**. any word on if this will be working by then?

**Comment by tracyapps** [comment] 2019-01-15 16:02
so... is there any update on this? i really can't believe no one else needs to make custom post type pages for their sites.

**Comment by viniciusbig** [comment] 2019-01-17 00:01
I've just installed a fresh WP and the 'parent' field is missing even in the default Pages post type.
There is any workaround for this?

**Comment by designsimply** [comment] 2019-01-17 01:45
I am still learning when it comes to dev, but I can test if you can walk me through some more detailed instructions for the first two testing steps: 

> 1. Create a post type and give it WP REST API capabilities, so gutenberg works.
> 1. Add hierarichal capabilities to the post type

@viniciusbig am I right that I wouldn't need step 1 for your case since you're testing with the default Pages post type and it already has WP REST API capabilities? (sorry if this sounds like an obvious quesiton!) Also, did you do step 2 from the original testing steps?

**Comment by viniciusbig** [comment] 2019-01-21 22:20
Yeah... I.ve tried again and its working. Sorry to open this thread again.
My custom post type has REST capabilities and therefore, Gutenberg functionality.

I've installed everything again trying to reproduce and its working as expected with regular pages and my new post type!

(I'm sure the field was not there before, but I could not reproduce anymore)

**Comment by designsimply** [comment] 2019-01-25 23:38
No problem! Thanks tons for the follow-up!

Closing based on the last reply, but @tracyapps please do comment again if you are still having trouble and I will loop back around.

**Closed by designsimply** 2019-01-25 23:38 UTC
Labels: Extensibility, [Type] Bug

**Comment by lindsaywebstudio** [comment] 2019-11-16 20:36
I am having the same problem as everyone else. I'm using latest WP version. I have enabled 'show_in_rest' and page attributes for my heirarchical post type. The page attribute box shows up, but only the "Order" field is visible. No option to set a parent. I can correctly set the parent if I switch back to the classic editor. Has this issue resurfaced?
