### ISSUE TITLE
Not compatible with WPBakery Visual Designer plugin.

### ISSUE THREAD

**Issue by webphilosopher** [WordPress/gutenberg#9339] opened 2018-08-25 03:08 UTC
Gutenberg breaks the WPBakery plugin. The only way to describe what it does is for you to see a screenshot, which I have included. 
![2018-08-24-23-05-www ericsenglish com](https://user-images.githubusercontent.com/7143228/44614445-829c3680-a7f2-11e8-9b6e-8b57bc8398f0.png)

**Comment by youknowriad** [comment] 2018-08-25 08:05
This is a duplicate of #7377 

Note that they published a post about Gutenberg compatibility https://visualcomposer.io/gutenberg-compatibility-and-element/

Thanks.

**Closed by youknowriad** 2018-08-25 08:05 UTC
