### ISSUE TITLE
Dispatching (core/editor).refreshPost fails

### ISSUE THREAD

**Issue by ryanboswell** [WordPress/gutenberg#11426] opened 2018-11-02 17:04 UTC
**Describe the bug**
While working on a plugin that requires refetching the post object from the API and resetting the editor state after taking certain actions (which modify other post fields server-side in their own API requests), we've been hitting an issue with calling `wp.data.dispatch('core/editor').refreshPost()` for a few months now where it fails with a message saying the response isn't valid JSON. From what I can tell it also never actually makes a network request, so I can't inspect what about the response Gutenberg considers invalid JSON. I don't remember the exact version it last worked in, but it was sometime in early August if I remember correctly. 

I can confirm other API-based editor behavior like autosave, manual saves, and publishing work without a problem.

I've also tested on a vanilla install of Gutenberg and WordPress with the same results so I'm fairly confident it's not something else in the plugin interfering.

**To Reproduce**
1. Go to edit any post in Gutenberg.
2. Run the following in the JS console: `wp.data.dispatch('core/editor').refreshPost()`
3. See error demonstrated in the Screenshots below.

**Expected behavior**
When dispatching `refeshPost`, I'd expect Gutenberg to make an API call to fetch the full post and reset the editor data with what it retrieves.

**Screenshots**
![refresh-promise-rejection](https://user-images.githubusercontent.com/1580218/47928974-fd35a200-de84-11e8-8d39-eae387a1d88f.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browsers: Chrome (70.0.3538.77), Safari (12.0)

**Additional context**
Testing against Gutenberg 4.1.1 and WordPress 4.9.8 as the latest release as of writing.

**Comment by designsimply** [comment] 2018-11-02 23:54
I can confirm that if I follow the steps provided, I can see the following error in the console after running `wp.data.dispatch('core/editor').refreshPost()` on a new post. ([7s](https://cloudup.com/coc-p1O4QXJ)) I tested using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and Chrome 70.0.3538.77 on macOS 10.13.6. Aside, I also tested with Firefox 63.0 on macOS 10.13.6 and noticed the error looks like it's attached to ` wp-polyfill-ecmascript.min.2ae96136.js:2:29718` in that case. ([screenshot](https://user-images.githubusercontent.com/1119271/47945540-478c4280-dec8-11e8-8f83-2f2d0be58fc2.png))

> Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}

**Comment by ockham** [comment] 2018-11-19 11:34
Should be fixed by #11879 (I didn't notice this bug report when filing that PR, apologies).

**Comment by ockham** [comment] 2018-11-19 11:45
To be more precise, #11879 fixes the error message. However, `refreshPost` still doesn't fire a network request (but uses cached data). Issue: #12055.

**Comment by catehstn** [comment] 2018-11-19 18:01
Closing this as fixed then as both #11879 and #12060 (alternative for #12055) have been merged.

**Closed by catehstn** 2018-11-19 18:01 UTC
Labels: Needs Technical Feedback
