### ISSUE TITLE
Permalink settings are hidden behind the "Post updated" notification

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#4289] opened 2018-01-04 15:26 UTC
When saving a post or a page, the post permalink settings are hidden behind the "Post updated" notification, see the screenshot below:

![gutenberg_permalink_settings](https://user-images.githubusercontent.com/1268089/34570373-3f23a616-f174-11e7-92fa-250657986448.png)

**Comment by youknowriad** [comment] 2018-01-04 15:27
This is a duplicate of #4172 which has been closed considering the notifications as temporary UI.

**Closed by youknowriad** 2018-01-04 15:27 UTC

**Comment by kmgalanakis** [comment] 2018-01-04 15:30
Oops, sorry, didn't see that. :man_facepalming:

**Comment by youknowriad** [comment] 2018-01-04 15:31
It's fine. issues are easy to miss
