### ISSUE TITLE
ToolsPanel: Selections in menu should persist

### ISSUE THREAD

**Issue by simonwammerfors** [WordPress/gutenberg#53425] opened 2023-08-08 14:07 UTC
## What problem does this address?
If I select a block and activate one of the options in the ToolsPanel, the selected options don't persist if I then deselect the block or select another block. Once I re-select the first block the options needs to be activated again. This is also the case if a block is unintentionally deselected when trying to close the ToolsPanel menu, see issue #41546.

https://github.com/WordPress/gutenberg/assets/88452801/72a477da-578b-4a90-934b-74d7c393eef2

## What is your proposed solution?
Selections in the ToolsPanel menu should persist. If an option is activated for a block, I expect that option to be active until I de-activate it.

**Comment by aaronrobertshaw** [comment] 2023-08-10 00:55
Thanks for taking the time to submit this @simonwammerfors 👍 

The issue described has come up previously in https://github.com/WordPress/gutenberg/issues/41544. It is made a little worse by the way in which the panel's menu expands over the panel content generally as detailed in https://github.com/WordPress/gutenberg/issues/41545.

The [decision](https://github.com/WordPress/gutenberg/issues/41544#issuecomment-1242733713) made on the original issue was that the impact of this, unfortunately, didn't warrant the greater complexity of tracking the unmounted component state. 

With the current behaviour, if a user customises an item once selected, that control continues to display the next time the block is selected. An argument could also be made that if a user toggles an item on and decides against customizing it, they don't want it to show the next time the block is selected.

Perhaps we can keep this issue open for a week or two to see if there is a ["wider concern"](https://github.com/WordPress/gutenberg/issues/41544#issuecomment-1242733713) about the behaviour. If not, we might need to close it.

**Comment by simonwammerfors** [comment] 2023-08-12 06:37
Thank you for taking time to explain and point to those issues I didn't managed to find.

Maybe then it would be better to focus on the issue in #41546. The combination of non-persistent menu options and the fact that it's quite easy to accidentally deselect the block while trying to close the menu is probably what causes most of the annoyance here.

**Comment by aaronrobertshaw** [comment] 2023-08-14 00:13
> Maybe then it would be better to focus on the issue in https://github.com/WordPress/gutenberg/issues/41546.

Sounds like a plan 👍 

I'll close this issue now then as a duplicate of #41544

**Closed as completed by aaronrobertshaw** 2023-08-14 00:13 UTC
Labels: [Type] Enhancement, [Package] Editor
