### ISSUE TITLE
Support for Grammarly browser extension

### ISSUE THREAD

**Issue by webmaster-cob** [WordPress/gutenberg#20543] opened 2020-02-28 19:41 UTC
When using the Grammarly Chrome browser extension while using the block editor, blocks without a min-height of at least 39px won't be checked by the extension. 

**To reproduce:**
1) Install the [Chrome Grammarly extension](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen)
2) Create a new post
3) Type a misspelled title and Grammarly will find the misspelling, underline it, and suggest alternatives.
4) Create a paragraph block and some text that is misspelled and Grammarly will not underline the error.
5) Add an image and type a misspelled word in the caption of the image and Grammarly will not underline the error.

The expected behavior is that Grammarly would detect the misspellings and suggest corrections. 

<img width="233" alt="2020-02-28 11_30_27-Edit Page ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/26336976/75581132-c8f0d800-5a1d-11ea-8523-da61288dd0f5.png">

While many browsers offer real-time spellcheck, they don't offer grammar checks without extensions. Since there's no built-in grammar tool for the WordPress block editor, an extension is needed to ensure quality content for editors. Attempts to find a plugin for WordPress like WProofreader have not resulted in a usable alternative to browser extensions. Grammarly is used by over 10 million and is a good solution for spelling and grammar in WordPress. 

It seems the main reason Grammarly is failing to work on these blocks specifically is they don't have a min-height of at least 39px declared in the block editor screen. Adding a min-height to block containers would allow Grammarly to work. 

To test the behavior, repeat the steps to reproduce the issue above and then use your browser dev tools to add a min-height of 39px to the div container for the paragraph block. Grammarly successfully detects the misspelling. Same for the figcaption container for the inserted image. 

It would be great to have a tweak added to the block editor CSS that ensured the affected blocks with text areas had a min-height of 39. Maybe just start with headings, paragraphs, and image captions to start with. Some headings work if their line height and font size equal at least 39 pixels. So H1/H2 may work, but as you get down the H3/H4 Grammarly may stop working.

Thanks for considering this issue. I've seen a number of posts about user frustration around the lack of spelling/grammar check in the block editor as I've researched options.

[Grammarly Support documentation](https://support.grammarly.com/hc/en-us/requests/new#/technical-issues/i-can-t-use-grammarly-browser-extension/i-don-t-see-the-grammarly-icon-in-some-text-fields/) on the requirements for a text field the extension looks for before it will attempt to perform a check on it.

**Comment by webmaster-cob** [comment] 2020-02-28 19:45
I've temporarily added the following to my editor style sheet and it's improved the experience so far:

p, h3, h4, h5, h6, figcaption {min-height:39px;}

**Comment by talldan** [comment] 2020-03-03 04:59
@webmaster-cob I don't think this is something that can be fixed in the editor without lots of repercussions. The issue is that the size of the paragraph block is highly dependent on how a theme styles it. Adding a default min-height would make life harder for theme developers and most themes would probably end up overriding the `min-height` to reset it, resulting in Grammarly not working again.

I'd suggest creating a support ticket with Grammarly, perhaps their heuristic can be adjusted to work better with blocks. If a Grammarly developer wanted to reach out through this or another issue to discuss the best approach, that might be a good idea.

**Closed by talldan** 2020-03-03 04:59 UTC
