### ISSUE TITLE
I can't see Gutenberg editor. My post editor is the same. Please advise

### ISSUE THREAD

**Issue by zunigideas** [WordPress/gutenberg#7377] opened 2018-06-19 18:26 UTC
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by tofumatt** [comment] 2018-06-19 18:54
Hi there,

If you want to try using the Gutenberg editor in your WordPress install, please install the plugin from https://wordpress.org/plugins/gutenberg/

If you aren't seeing Gutenberg after installing the plugin, please post steps to reproduce, including other plugins you have installed, your version of WordPress, etc.

Because there's not enough info in your report to help with I'm closing this issue, but if you can add more info we're happy to fix a bug.

**Closed by tofumatt** 2018-06-19 18:54 UTC

**Comment by zunigideas** [comment] 2018-06-19 21:16
Hi @tofumatt ,
Please don't close this case. Is important to me.

1. I installed Gutenberg editor through https://wordpress.org/plugins/gutenberg/
2. I activated it.
As you can see, I uploaded two screenshots, how looks.

![screen shot 2018-06-19 at 4 57 00 pm](https://user-images.githubusercontent.com/40403969/41623814-e24f39dc-73e1-11e8-909e-c9075b93b6c3.png)
![screen shot 2018-06-19 at 4 56 15 pm](https://user-images.githubusercontent.com/40403969/41623815-e27a578e-73e1-11e8-8b39-20c0275f39bc.png)

Also, I enclosed screenshots of my plugins if that helps:

![screen shot 2018-06-19 at 5 02 39 pm](https://user-images.githubusercontent.com/40403969/41624155-c69782c0-73e2-11e8-9beb-893e69826f6f.png)
![screen shot 2018-06-19 at 5 02 31 pm](https://user-images.githubusercontent.com/40403969/41624156-c6b4dc44-73e2-11e8-9aa1-d770e1a3cdb9.png)
![screen shot 2018-06-19 at 5 02 18 pm](https://user-images.githubusercontent.com/40403969/41624158-c6d77e84-73e2-11e8-8e34-a06be30d945f.png)

My WordPress version is 4.9.6
I'm using Google Chrome
I'm using a Mac Book Pro.  MacOS High Sierra version 10.13.4 

Gutenberg editor is activated, as you can see:
![screen shot 2018-06-19 at 5 11 29 pm](https://user-images.githubusercontent.com/40403969/41624524-f9475294-73e3-11e8-8122-665728f39637.png)
![screen shot 2018-06-19 at 5 11 11 pm](https://user-images.githubusercontent.com/40403969/41624525-f96ed1c0-73e3-11e8-8b40-83d16cc639bb.png)

My Post editor hasn't changed like a Gutenberg editor.

Many thanks for your support,

MZ

**Comment by tofumatt** [comment] 2018-06-19 22:03
My immediate guess, looking at your plugins, is that WPBakery's Visual Composer plugin is incompatible with Gutenberg and causing the editor to fall back to the classic editor. I can't recall exactly what conditions cause this to happen but I think certain editor plugins will cause the classic editor to activate.

Is there any chance you can reproduce this issue on a fresh install of WordPress? Does the editor work with, say, that Visual Composer plugin disabled?

**Comment by bph** [comment] 2018-06-19 22:19
I would think it is related to the Visual Composer, too. They published an article how to make your site Gutenberg ready with the Gutenberg Element within Visual Composer. You can read up about it here[https://visualcomposer.io/gutenberg-compatibility-and-element/](url)

**Comment by zunigideas** [comment] 2018-06-20 02:41
Fixed up!
I disabled the Visual Composer Website Builder, fortunately, I didn't purchase it. Only I'm using free plugin WPBakery Visual Composer. 
Quick question. What will happen when I buy WPBakery? I hope it works.

Anyway, many thanks, @tofumatt, and @bph  !!!  I greatly appreciate all your help.

**Comment by zunigideas** [comment] 2018-06-20 03:38
Many thanks!

**Comment by brianvandenBerg** [comment] 2018-06-20 05:38
GitHub 

Transmitting Private Internal Voice Vibration Radio Frequencies....

To Alexa compatible devices...


My Software was Stolen by a girl...

Now the main stream media seems to be “tuned” into my 
Baseline “Private” Internal Voice Vibrations Radio Frequencies....

I need a Patent attorney since my “Tech” doesn’t exist...cough cough..

OpenSource “Speech Recognition Software”...

Who works for free...?

OpenSource is Free...

File sharing with the OpenSource Licensing applied is legal...@FBI nor any other can/will do anything...


Like MUSIC....buy ONE copy...

source code...

apply your logo/name and...apply 

Apache or 
Free BSD Licensing 



Sale a Million$$$$....

It’s legal 

#LeftFlutterEH do I continue? 
Pay me for my Services..

@Outcomes_Matter for more Free “Methods” & Sources...

Because I haven’t been paid....I will give away all the secrets....@Outcomes_Matter 


Brian VandenBerg 
620-249-0771 
Lamar, Mo 64759

**Comment by tofumatt** [comment] 2018-06-20 06:58
@zunigideas You'll need to contact the Visual Editor plugin author (WPBakery) and ask them about the issue. Unfortunately it's an issue with their plugin and we aren't able to help further.
