### ISSUE TITLE
Cover Block: Block toolbar partially hidden

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17796] opened 2019-10-07 07:15 UTC
If the cover block have a small width (for example left or right aligned) the block toolbar is partially hidden.

<img width="322" alt="Bildschirmfoto 2019-10-07 um 09 08 54" src="https://user-images.githubusercontent.com/31563167/66291592-8ef22e80-e8e2-11e9-984e-413a69168d00.png">

The reason of this issue is the `overflow: hidden` of following default block css:

```
.wp-block-cover, .wp-block-cover-image {
    position: relative;
    background-color: #000;
    background-size: cover;
    background-position: 50%;
    min-height: 430px;
    height: 100%;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
}
```
Without `overflow: hidden` the entire toolbar is visible again:

<img width="381" alt="Bildschirmfoto 2019-10-07 um 09 09 34" src="https://user-images.githubusercontent.com/31563167/66291719-d24c9d00-e8e2-11e9-8d60-7efcb6ad1354.png">

Tested with Gutenberg 6.6

**Comment by youknowriad** [comment] 2019-10-07 10:04
Duplicate of #15443

**Closed by youknowriad** 2019-10-07 10:04 UTC
