### ISSUE TITLE
Is this plugin an unstable prototype for experimentation?

### ISSUE THREAD

**Issue by MikeWhelan** [WordPress/gutenberg#15907] opened 2019-05-30 08:26 UTC
A suggestion for the developers of this plugin.

I think the description of this plugin is missing some basic information. You need to make a clear distinction between this plugin and the version that is part of core Wordpress. It would be helpful to publish answers to the following questions: 

1. What is the purpose of this plugin?

2. Is it stable?

3. Can it be used on production sites?

4. Who is this plugin for?

The answers could be published on the [description](https://wordpress.org/plugins/gutenberg/) page and/or the <a href="https://developer.wordpress.org/block-editor/contributors/faq/" rel="noopener" target="_blank">FAQs</a>

**Comment by talldan** [comment] 2019-05-30 08:45
Thanks for raising the issue @MikeWhelan. The readme files sometimes don't get enough attention, especially as the project changes, so it's great to flag this.

I think it's this readme that would need to be updated for the description page:
https://plugins.trac.wordpress.org/browser/gutenberg/trunk/readme.txt

**Comment by swissspidy** [comment] 2019-05-30 11:33
Related pull request: #15394.

To answer your questions right away in the mean time:

1. To develop new features that can eventually be integrated into WordPress core, at a faster pace than working on core directly and independent of core's release cycle.  
  A good example is the new widgets management screen. 
2. If you download the plugin from WordPress.org, yes.
3. It's stable, so yes. That's for you to decide really. Personally I'd just use what is in WordPress, so all people have the same experience.
4. Anyone who wants to keep up with latest development and use the latest features and bug fixes before they're in core.

**Comment by MikeWhelan** [comment] 2019-05-30 11:43
Thank you for the clarification and well done for acting so quickly. For people like me, who are not fully involved in Wordpress, it is really useful to get this simple overview.

**Comment by gziolo** [comment] 2019-10-20 01:38
Cc @youknowriad @mapk

**Comment by youknowriad** [comment] 2019-10-21 09:16
Duplicate of #17998

Let's tweak these for the next plugin release.

**Closed by youknowriad** 2019-10-21 09:16 UTC
Labels: [Type] Documentation, [Type] Task
