### ISSUE TITLE
FSE - spacing/padding not applied visually

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#29765] opened 2021-03-11 11:08 UTC
## Description

In a FSE enabled theme with support for `spacing->customPadding` the padding is not applied to the block without clicking somewhere outside of the padding input control.
~~Additionally the padding value is not saved unless there are also other post/page changes to save.~~

## Step-by-step reproduction instructions

Install a FSE theme with support for `spacing->customPadding` e.g. TT1-Blocks
Add/edit a post or page.
Insert a Group or Cover block.
Adjust the Padding value for the block.

## Expected behaviour

The padding value should be applied visually to the block.

~~When saving/updating the padding value should be saved.~~

## Actual behaviour

The padding value is only applied visually to the block after clicking somewhere outside of the padding input control.

~~When saving/updating the post, the padding value is not saved when that is the only change being made to the post.
Edit: I should also say the Update button is disabled without other changes to the post, so unable to save when the padding is the only change.~~

## WordPress information
- WordPress version:  5.7
- Gutenberg version:  10.1.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1-Blocks

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox

**Comment by carolinan** [comment] 2021-03-11 11:11
Is this group inside a template part? Asking because of my findings here https://github.com/WordPress/gutenberg/issues/29758

**Comment by Sandstromer** [comment] 2021-03-11 11:13
No, the group block is in the post/page content.

**Comment by Sandstromer** [comment] 2021-03-11 11:48
After clearing browser cache and also testing in other browsers, I am able to save/update the post when the padding is the only change.

I have updated the title as appropriate.

**Comment by jordesign** [comment] 2023-09-08 02:52
Hi @Sandstromer  - looping back to this older issue - do you still see it present if you test in WP6.3 ?

**Comment by jordesign** [comment] 2023-09-18 01:37
I'm not able to reproduce this - and with 2 years passed since the last updates - I'm going to close this issue.

**Closed by jordesign** 2023-09-18 01:37 UTC
Labels: [Type] Bug, [Feature] Site Editor
