### ISSUE TITLE
Return AttributeKey as number 

### ISSUE THREAD

**Issue by akasunil** [WordPress/gutenberg#58996] opened 2024-02-14 06:13 UTC
### Description

`getSelectionStart()` function of block editor return attributeKey as number in Gutenberg file block. is it expected behavior? Shouldn’t it return selected attribute key from available attributes of file block instead of number ? what does this number represent ?

### Step-by-step reproduction instructions

Execute `wp.data.select("core/block-editor").getSelectionStart()` after selecting file block in editor

### Screenshots, screen recording, code snippet

![CleanShot 2024-02-14 at 11 40 34@2x](https://github.com/WordPress/gutenberg/assets/61308756/f78a9ecb-b6c7-4188-9357-256d4cd42c41)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2024-02-14 08:14
I believe it returns the `identifier` prop set on the RichText. The file block doesn't have an `identifier` set, so a numeric id seems to be used instead.

It could be fixed by adding identifiers in the block, which I think might be best practice when a block contains more than one RichText element.

**Closed as completed** 2024-03-21 09:22 UTC
Labels: [Type] Bug, [Package] Block library

**Comment by gziolo** [comment] 2024-03-21 12:01
@ellatrix, should we make `identifier` a required prop when using `RichText` in the context of block edit?

**Comment by Mamaduka** [comment] 2024-03-21 12:08
@gziolo, I think it's only "required' when RichText is bound to the attribute. @jsnajdr added the documentation in #60036.

**Comment by jsnajdr** [comment] 2024-03-21 12:19
Site Title and Site Tagline are examples of blocks where there's no reasonable `identifier` for the `RichText`. The editable field is bound to the `editEntityRecord( 'root', 'site' )` entity, not to a block attribute.

It's bit of an unsolved problem what the `identifier` should be in this case, and what the Redux state (`getSelectionStart()`) should contain as `attributeKey`. I posted a comment about it (https://github.com/WordPress/gutenberg/pull/58913#issuecomment-2009235601) demonstrating a few little bugs that are caused by this.
