### ISSUE TITLE
url popover appears outside editor

### ISSUE THREAD

**Issue by shodoi** [WordPress/gutenberg#19310] opened 2019-12-23 19:14 UTC
**Describe the bug**
If you select the text and click the link button, the url popover will appear outside the editor after the second click.

**To reproduce**
1. Select text
2. Click on link button
3. Click the link button again

**Screenshots**
![blockeditor](https://user-images.githubusercontent.com/759562/71375243-e7db8400-2600-11ea-93b5-7cf737e7d537.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version Chrome 80.0.3987.16（Official Build）dev, Firefox 71.0

Reproduced on WordPress 5.3.2 and Gutenberg 7.1.0

**Comment by ellatrix** [comment] 2019-12-23 20:37
Thanks for the report! I can reproduce the bug.

**Comment by jorgefilipecosta** [comment] 2020-03-17 19:23
Closing as the issue is solved on Gutenberg master and WordPress 5.4.

**Closed by jorgefilipecosta** 2020-03-17 19:23 UTC
Labels: [Type] Bug
