### ISSUE TITLE
From WordPress 5.4, the behavior when focusing on a block with long content became very difficult to use

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#21415] opened 2020-04-06 03:57 UTC
When editing a block with very long content, such as a group block or list block, the behavior when focusing on the block became very difficult to use.

**To reproduce**
For example, list block,
1. Prepare a list block that exceeds the height of the screen.
2. Edit the outer block and then focus on that block.
4. Scroll to an unintended location.

![wp54-list](https://user-images.githubusercontent.com/31400297/78521637-787f4e00-7805-11ea-807e-db0716182b59.gif)

Or in the case of a group block,
1. Prepare a group block that exceeds the height of the screen.
2. Set group block to "full width"
4. After editing the inner block, move the focus to the outside of the inner block (parent group block) to check the contents.
5. Or, when you try to select the inner content and accidentally select the parent block.
6. Scroll to an unintended location.

![wp54-group](https://user-images.githubusercontent.com/31400297/78521676-9fd61b00-7805-11ea-8998-0aa75e10f35d.gif)

**Expected behavior**
The behavior in WordPress5.3 is ideal.

List Block
![wp53-list](https://user-images.githubusercontent.com/31400297/78521647-80d78900-7805-11ea-8ee3-e1f049011675.gif)

Group Block
![wp53-group](https://user-images.githubusercontent.com/31400297/78521783-f93e4a00-7805-11ea-95a3-ee075ed7044f.gif)

**Comment by gigatyrant** [comment] 2020-04-06 04:09
Same problem for me.

I'm using long blocks for my clients, and this "jump" introduced by WordPress 5.4 is very, very annoying.

This behavior break ACF Blocks too...

Is it possible to remove this ?

**Comment by talldan** [comment] 2020-04-07 00:50
Duplicate of #19682 and #20111

**Closed by talldan** 2020-04-07 00:50 UTC
Labels: Needs Testing, [Feature] Writing Flow, [Status] Duplicate
