### ISSUE TITLE
Justify alignment

### ISSUE THREAD

**Issue by AtwoodEditor** [WordPress/gutenberg#9545] opened 2018-09-01 21:00 UTC
I’d like the ability to add justified alignment please! Our magazine uses this exclusively and the inability to customize/efficiently justify paragraphs is a huge detractor for us. Thank you!

**Comment by ianbelanger79** [comment] 2018-09-04 20:56
Closing as this is a duplicate of #8433

**Closed by ianbelanger79** 2018-09-04 20:56 UTC
Labels: [Status] Duplicate
