### ISSUE TITLE
Meta box reordering does not save in user preferences

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#30071] opened 2021-03-22 03:57 UTC
## Description
Originally reported as [WP#52818](https://core.trac.wordpress.org/ticket/52818) by wordpress.org user [terraling](https://profiles.wordpress.org/terraling/)

> Post edit screens with metaboxes allow for drag and drop re-ordering.
> 
> This worked up to WordPress 5.6.2, but stopped working in WP 5.7, though it continues to work if you use the Classic Editor to edit posts rather than the block editor.
> 
> When re-ordering the metaboxes, an ajax update with the action 'meta-box-order' occurs, and this reports a succesful response both in the working and non-working cases, so it appears as if updating the metabox order works.
> 
> But, when the page is reloaded, the metaboxes are displayed in an unchanged order.

At the moment this is on the WP 5.7.1 milestone but please let me know if this isn't possible.

## Step-by-step reproduction instructions
1. Create a legacy meta box with this code in a plugin https://gist.github.com/peterwilsoncc/65e80a277a1ac1d1d700502638d80fb3
2. Create a new post
3. Enable the custom fields panel
3. You should see two meta boxes at the bottom of the screen
4. Reordeer the two meta boxes, either by dragging and dropping or clicking the buttons
5. Refresh the editor
6. Observe the two meta boxes are not showing in the user's selected order.

## Expected behaviour

At the final step the order should reflect the user's preferences.

## Actual behaviour

The order of meta boxes is reset to the default WP order each time the editor is loaded.

@desrosj has determined that the `page` parameter is been left off the AJAX request to the admin-ajax action `meta-box-order`. 

A git bisect shows it was apparently introduced in this package update during the WP 5.7 cycle https://github.com/WordPress/wordpress-develop/commit/bc405697b025841c0b897f4248ee78ae9f9baf5c.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/519727/111938237-a85e5900-8b1d-11eb-8419-763af20c28e0.mov

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: latest (built from 49c6fb99edd685db0cc63bafb5a884c87a0ef141 )
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Firefox Developer Edition 87

**Comment by vlad-timotei** [comment] 2021-03-24 10:02
Most probably, another problem caused by the missing _page_ parameter in the request to the _admin-ajax_ is with  `closed-postboxes` action, resulting in failing to save the closed status of metaboxes. (see this [ forum topic](https://wordpress.org/support/topic/expand-collapse-not-saved-in-wp-admin/))

**Comment by paaljoachim** [comment] 2021-03-26 15:48
These might be associated:

No way to drag metabox back into sidebar / below content if there are no other metaboxes there
https://github.com/WordPress/gutenberg/issues/7960
PR: https://github.com/WordPress/gutenberg/pull/25187

Meta box back-compat concurrency.
https://github.com/WordPress/gutenberg/issues/10711

Meta boxes: update core styles to match Gutenberg's 
https://github.com/WordPress/gutenberg/issues/12101

EDIT: 8th April.
This issue might also be associated:
Persist user's editor preferences to database rather than local storage
https://github.com/WordPress/gutenberg/issues/15105

**Comment by peterwilsoncc** [comment] 2021-04-06 02:15
I've labelled this for backporting and moved in on to the 5.7.x project board.

With WP 5.7.1 RC due later this week, you may wish to bump this to the .2 release. Please advise and I will move [WP#52818](https://core.trac.wordpress.org/ticket/52818) accordingly.

**Comment by ribaricplusplus** [comment] 2021-04-08 14:12
I have a fix for this, setting up a PR

**Comment by rodrigo-arias** [comment] 2021-04-23 15:15
Hi, is there any chance this will be released before 5.7.2 in the standalone plugin? I am not worried about the metabox ordering, but in my case using ACF, after selecting a taxonomy, the rest of the metaboxes do not respond. Going back to 5.6.3 solves the problem. Thanks

**Comment by peterwilsoncc** [comment] 2021-04-30 05:15
@vlad-timotei I've confirmed #30617 fixes both the order and open/close state described in the linked forum post. I can see the post type is included in each of the relevant admin-ajax requests.

**Comment by rodrigo-arias** [comment] 2021-05-11 15:05
Hi, thank you for your work here. I have seen that they continue to work on a PR, do they have an ETA of when it will merged? As a workaround I have rollback to 5.6 several sites.

**Closed as completed** 2021-08-30 10:58 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Meta Boxes

**Comment by paaljoachim** [comment] 2021-08-30 12:04
Hey @peterwilsoncc 

> I've labelled this for backporting and moved in on to the 5.7.x project board.
> 
> With WP 5.7.1 RC due later this week, you may wish to bump this to the .2 release. Please advise and I will move WP#52818 accordingly.

I assume this is the 5.8.x project board...:)
WP 5.8.1 RC is due September 1st.
