### ISSUE TITLE
Block toolbar is not shown in HTML editing mode

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#21722] opened 2020-04-20 08:53 UTC
**Describe the bug**
If you use a BlockQuote, and edit it in HTML,
the small "option square" is invisible so we can't get back to W.Y.S.I.W.Y.G. mode.

**To reproduce**
Steps:
1. Create a new Classic Block
2. Add enough text to allow wrapping around an image
3. Insert an image from Media Library
4. Resize the image and set the image wrapping to left (image on left, text on right)
5. Click the block's floating ellipsis menu and and select 'Edit as HTML'
6. Note that at this point, the ellipsis menu is still visible.
7. Click into the HTML editor so the cursor is flashing
8. The Ellipsis menu now disappears. At this point, there's no way to get that menu back, leaving you stranded in this view mode for this block.

Note: Steps 3 and 4 may not be strictly necessary, but having content in the block may be helpful.

**Expected behavior**
The floating ellipsis menu should always remain visible no matter what mode you're in.

**Comment by talldan** [comment] 2020-04-21 03:12
Hi @Nemzag. This was also reported in #21640. I tested and didn't have any issues seeing or using the options to change between HTML and Visual mode. Do you have any plugins installed that might be causing a conflict?

**Comment by talldan** [comment] 2020-04-21 03:15
Actually, I can reproduce this for the Quote block, so I'll reopen the issue.

The problem seems to occur when first clicking into the block to edit it.

It looks like for some reason block selection isn't working correctly in HTML mode.

**Comment by Nemzag** [comment] 2020-04-27 17:12
Hi,
I use wordpress.com,
and no I don't have any plug‑in,
thank pro you response.

**Comment by talldan** [comment] 2020-05-04 02:24
#21826 seems to be a duplicate of this. As noted on that issue the problem seems to be occurring on multiple blocks.

I've updated the title to make this issue easier to find.

**Comment by talldan** [comment] 2020-05-04 02:27
https://github.com/WordPress/gutenberg/issues/14036 also seems related, but possibly an older different issue.

**Comment by talldan** [comment] 2020-05-28 09:29
#22653 was also created and mentions that this also occurs on the classic block. That report has some good testing instructions and screen captures, and I've updated the description here with the testing steps.

**Comment by talldan** [comment] 2021-07-21 05:03
This seems to be resolved in more recent versions, but let me know if anyone still experiences it.

**Closed by talldan** 2021-07-21 05:03 UTC
Labels: [Block] Quote, [Type] Bug
