### ISSUE TITLE
Double scrollbar issue when block is selected

### ISSUE THREAD

**Issue by simom** [WordPress/gutenberg#62319] opened 2024-06-05 08:32 UTC
### Description

With the first WordPress 6.6 beta 1, I found a strange scrollbar issue when a block is selected and you scroll on the page. When the block disappears from the viewport, a second scrollbar is displayed.

### Step-by-step reproduction instructions

1. Select a block
2. scroll in the viewport with the block selected
3. when the block disappear from the viewport area a second scrollbar will appear

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/492145/78abd516-411e-4dc0-86dc-c4edd3a2f41b

### Environment info

- WordPress 6.6 beta 1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment] 2024-06-06 22:11
I just confirmed this against trunk b2e649f147baddf4837159a2dbe94b6c04bc92d3

It is a bug. Setting `overflow-y: clip` on `.interface-interface-skeleton__content` fixes it, but I'm not sure if this is the ideal solution.

https://github.com/WordPress/gutenberg/assets/405912/acffef23-ff0e-45a1-a2b7-e9469de3adc6

**Comment by colorful-tones** [comment] 2024-06-06 22:13
Also, confirming that it happens in both the site editor and the post editor.

**Comment by stokesman** [comment] 2024-06-13 18:44
And if you like scrollbars, try with the tablet or mobile views and you can have three! Whether or not you have block toolbar scrolled out of view (EDIT: In the post editor that is. In the site editor a block toolbar does have to be scrolled out of view to get three).

![Image](https://github.com/WordPress/gutenberg/assets/9000376/7d0bcecc-9a4a-4e46-b9a6-74b297830634)

**Comment by stokesman** [comment] 2024-06-17 20:26
I’ve looked into fixing this and there is more than one way to go about it. A minimal way I came up with is similar to what Damon mentioned:

> Setting `overflow-y: clip` on `.interface-interface-skeleton__content` fixes it

It does but has to be applied only when the block canvas is iframed or it breaks scrolling when not iframed. That’s doable and relatively simple but it means creating a cross-package dependency that it’d be nicer to avoid. That’s how I came up with the approach in #62632 which fixes this with only changes in the block-editor package.

**Comment by stokesman** [comment] 2024-06-27 14:40
From my testing #62894 fixed this. I'll leave closing the issue to anyone who confirms. There is still the triple scrollbars in the post editor I mentioned earlier https://github.com/WordPress/gutenberg/issues/62319#issuecomment-2166539672 but that can be treated separately.

**Comment by t-hamano** [comment] 2024-06-28 01:52
I have also confirmed that this issue has been fixed, so I will close it.

If anyone has found that the issue is still not resolved, please feel free to comment.

**Closed as completed by t-hamano** 2024-06-28 01:52 UTC
Labels: [Type] Bug, [Status] In Progress, [Package] Editor
