### ISSUE TITLE
Sudden lag to the point its unusable after "Updating Post" and above 1000 words

### ISSUE THREAD

**Issue by bantilan** [WordPress/gutenberg#24959] opened 2020-09-01 03:00 UTC
Hi Gutenberg team,

I experience this lag after updating the new version **8.8.0**, it happens every time I reach above 1,000 words and after hitting the **"Update"** button on the post or from an automatic saving.

The lag is about 5 to 10 seconds, after typing any letters.

Also tried it on Incognito and other computer still the same.

Installed Plugin:

- Akistmet Anti-Spam
- AMP
- Dashboard Notes
- Gutenberg
- Instant Articles for WP
- Jetpack by Wordpress.com
- Meta Box by MetaBox.io
- Multi-column Tag Map by Alan Jackson
- Multicote Theme Core by An-themes
- Review Plugin by An-themes
- Shortcake (Shortcode UI) by Fusion Engineering and community
- Shortcodes Plugin by An-Themes
- Thumbs Rating by An-Themes
- WordPress Importer
- WP External Links
- WP Super Cache
- WP-PageNavi

Server:
- PHP 7.4.9
- Nginx 1.19.2
- MySQL 8.0.21

**Comment by aristath** [comment] 2020-09-01 05:01
@bantilan this looks like a duplicate of https://github.com/WordPress/gutenberg/issues/24690
Could you please test with the 8.9.0-RC1 version and see if that fixes your issue?

**Comment by bantilan** [comment] 2020-09-01 06:34
@aristath, awesome! it works.. thank you so much ..

**Comment by aristath** [comment] 2020-09-01 06:38
Perfect :+1: 
I'll go ahead and close this issue then.

**Closed by aristath** 2020-09-01 06:38 UTC
