### ISSUE TITLE
Post Comments Block

### ISSUE THREAD

**Issue by t-pabla** [WordPress/gutenberg#38468] opened 2022-02-03 04:25 UTC
## What problem does this address? 

WP 5.9
Twentytwentytwo theme
When viewed in templates such as "Single Post", "Index", "page", the Post Comments block has no option in the Editor to remove "date" , "at", and "time"
## What is your proposed solution?

option in the Editor to remove "date" , "at", and "time" should be added

**Comment by gziolo** [comment] 2022-02-03 04:50
It looks like duplicate of https://github.com/WordPress/gutenberg/issues/34994.

**Comment by t-pabla** [comment] 2022-02-03 16:36
> It looks like duplicate of https://github.com/WordPress/gutenberg/issues/34994.

May be , I'm not sure.

Anyhow, meanwhile is there a filter I can use to remove (1) "date" , (2) "at", and (3) "time" from post comments?

**Comment by carolinan** [comment] 2022-06-30 08:54
With the new comments block, you can remove the date in the editor, so I would like to close this issue as solved.

If you are using Twenty Twenty-Two with WordPress 6.0, you can open the templates and remove the old comment block, and replace it with the new.
The new block is not used by default, since the theme is built to support an earlier version of WordPress.

**Closed as completed** 2022-10-17 18:17 UTC
Labels: [Block] Comments (legacy)
