### ISSUE TITLE
Character encoding issue on front end - (â€™) instead of apostraphe

### ISSUE THREAD

**Issue by hempsworth** [WordPress/gutenberg#24384] opened 2020-08-05 16:23 UTC
**Describe the bug**
Since upgrading to Gutenberg 8.7.0, character encoding seems to be broken when pages are rendered on the front end. In my example, I am seeing `â€™` instead of `'`

I have tested this with the default theme, and I have confirmed it does not happen when the Gutenberg plugin is disabled.

**To reproduce**
1. Edit any page and use an apostraphe (for example) in _any_ block that accepts text
2. Save and view the rendered page on the front end
3. The encoding is incorrect, and renders `â€™` instead of `'`

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg plugin installed, version 8.7.0

**Comment by ItsJonQ** [comment] 2020-08-05 16:45
Haii!! Hmm, I can't seem to replicate this. I'm testing this locally by checking out Gutenberg at `v8.7.0`

<img width="561" alt="Screen Shot 2020-08-05 at 12 43 51 PM" src="https://user-images.githubusercontent.com/2322354/89440282-65c84780-d719-11ea-984f-e4894459631a.png">

The above screenshot shows a couple of paragraph blocks with quotes (double, single) and backticks. They seem to be rendering okay.

* WordPress Version: 5.5-beta2-48515
* Gutenberg plugin. v8.7.0

I'm curious if anyone else is experiencing this!

**Comment by JuanCarlosNieto** [comment] 2020-08-06 18:40
I have the same error in spanish with apostrophe and question marks
![error gutenberg](https://user-images.githubusercontent.com/3809750/89569410-f3dd2480-d824-11ea-9e6a-99054d2945fd.png)

**Comment by dennisheiden** [comment] 2020-08-07 09:54
We have the same problem after the update to v8.7. 
With Gutenberg Plugin deactivated, everything is fine.

![image](https://user-images.githubusercontent.com/25924499/89633802-a6080100-d8a4-11ea-8a7e-f7fc7ba15e44.png)

**Comment by ms-studio** [comment] 2020-08-09 20:40
Could it have the same cause as #24445 ? I notice a similar issue with the "Latest Posts" block – all french accented characters are garbled.

**Comment by mcsf** [comment] 2020-08-10 10:35
This does seem like a duplicate of #24445. To everyone who reported this issue: could you answer the following questions?

* With what blocks specifically did you have this issue?
* Are these blocks server-side rendered?
* Do these blocks have alignment support, and did you choose a specific align for your block (e.g. Wide)?

Finally:

* Does #24447 **not** fix the issue for you?

**Comment by dennisheiden** [comment] 2020-08-10 12:06
Does any of the commentators use WPML? I did a test with a mostly vanilla WP + GB 8.7 and the issue doesn't appear.

**Comment by JuanCarlosNieto** [comment] 2020-08-10 12:21
- I have detected error in background blocks with full width.
- They are not server-side rendered.
- I made the code modificacion in #24447  and solved the problem.
- I am not using WPML there is only one language, spanish

**Comment by mcsf** [comment] 2020-08-10 12:34
>     * I have detected error in background blocks with full width.
> 
>     * They are not server-side rendered.

Thanks for the feedback. What are these background blocks? Are they `core/cover`, `core/group`? (It may be surprising, but the Cover block is actually [server-side rendered](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/cover/index.php), partly as a workaround to KSES restrictions on post content for certain user roles (#22346).

**Comment by JuanCarlosNieto** [comment] 2020-08-10 16:06
Sorry for my english, I use administrator role. Perhaps its "cover block" in spanish is translated.

Here are block in back-end and front-end. In back-end the text is correct and in front-end there is a codification error
![backend](https://user-images.githubusercontent.com/3809750/89804239-3019c900-db34-11ea-8d8d-2a01eef8549f.jpg)
![frontend](https://user-images.githubusercontent.com/3809750/89804253-3314b980-db34-11ea-87a1-35baaa28cebe.jpg)

**Comment by ockham** [comment] 2020-08-10 16:41
@JuanCarlosNieto Yep, that's the Cover block :+1:  Thanks for confirming. That's indeed #24445, which should be fixed by #24447.

**Comment by mcsf** [comment] 2020-08-10 16:45
Ah, I see, it became Fondo in the Spanish translation. ¡Gracias, @JuanCarlosNieto!

**Comment by dennisheiden** [comment] 2020-08-11 08:11
Confirmed on by test bench. Cover Block is causing the issue so -> https://github.com/WordPress/gutenberg/issues/24445

Thanks!

![image](https://user-images.githubusercontent.com/25924499/89873513-d6a8ad00-dbba-11ea-99fa-148a54e4010b.png)

**Comment by mcsf** [comment] 2020-08-12 19:48
Thanks for your responses. I'm closing this as a duplicate of #24445, now fixed in `master` by #24447.

**Closed by mcsf** 2020-08-12 19:48 UTC
