### ISSUE TITLE
Make it possible to assign more than one style at a time using registerBlockStyle()

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#11582] opened 2018-11-07 13:38 UTC
Is it possible to assign more than one style using registerBlockStyle()?

For example a block could have a style which relates to the position of the elements and another to borders. So instead of having:

- horizontal layout with border
- horizontal layout without border
- vertical layout with border
- vertical layout without border

We could simply assign two styles at a time and have:

- horizontal layout
- vertical layout
- with border

This is just a basic example but I think it can be extended to many other cases. Thanks.

**Comment by chrisvanpatten** [comment] 2018-11-07 14:04
Right now you can only select one block style at a time, but being able to select multiple is interesting. They are applied as CSS classes so you can also just apply the styles in the "additional CSS" field in the "advanced" inspector panel, but I can see how it'd be useful to have a visual interface.

**Comment by youknowriad** [comment] 2020-04-10 22:48
Closing this as duplicate of #14598 there seem to be more discussions there.

**Closed by youknowriad** 2020-04-10 22:48 UTC
Labels: Customization, [Feature] Extensibility, [Type] Enhancement
