### ISSUE TITLE
Converting a shared block to a regular block breaks if it contains a column

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#9499] opened 2018-08-31 13:25 UTC
**Describe the bug**
Any shared blocks that contains a column will break (become empty) when converting to regular block

**To Reproduce**
1. create column block
2. convert to shared block
3. convert shared block to regular block

**Expected behavior**
I expect the shared block to keep whatever it contained and not transform in to an empty block.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
Gutenberg Version 3.7 (same issue in previous versions)

**Comment by designsimply** [comment] 2018-08-31 22:02
Thank you for reporting! I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/9278. Please follow along in that issue!

**Closed by designsimply** 2018-08-31 22:02 UTC
Labels: Reusable Blocks, [Component] Nested / Inner Blocks, [Status] Duplicate
