### ISSUE TITLE
Pasted text with superscript loses formatting

### ISSUE THREAD

**Issue by withinboredom** [WordPress/gutenberg#10946] opened 2018-10-23 11:30 UTC
**Describe the bug**
I would expect that text copied from one editor into Gutenberg has the same formatting as copied. This is not the case

**To Reproduce**
1. Go to a popular editor such as Google Docs
2. Write some text that includes super/subscript
3. Paste the text into a Gutenberg editor
4. Text has improper formatting (or lacking super/subscript in this case)

**Expected behavior**

Formatting to be retained

**Comment by designsimply** [comment] 2018-10-23 16:59
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.1.0-rc.2 and Chrome 69.0.3497.92 on macOS 10.13.6.

**Comment by desrosj** [comment] 2018-10-25 18:32
Tested and confirmed using WordPress 5.0 Beta 1 with the Gutenberg plugin disabled.

**Comment by desrosj** [comment] 2018-10-25 18:35
I am also seeing this happen with strikethrough and underline.

**Comment by antpb** [comment] 2018-10-25 18:35
As @desrosj pointed out in Slack: https://wordpress.slack.com/archives/C02RQBWTW/p1540492500000100

This is also happening on strikethrough

**Comment by iseulde** [comment] 2018-10-29 13:43
This is what I get from Google Docs:

Superscript:

```html
<span style="font-size: 6.6pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: super; white-space: pre-wrap;">2</span>
```

Strikethrough:

```html
<span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: line-through; -webkit-text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">t</span>
```

We would need to convert this because Google Docs doesn't give us any semantic tags. I'm not sure if we can do this reliably.

This same happens in the old editor, which is why I'll close this issue for now.

**Closed by iseulde** 2018-10-29 13:43 UTC
Labels: [Component] Raw Handling, [Type] Bug
