### ISSUE TITLE
Remove inline style from Group Block preview item (it overrides registered background color)

### ISSUE THREAD

**Issue by Jugibur** [WordPress/gutenberg#30450] opened 2021-04-01 13:45 UTC
## What problem does this address?
I've registered a style to a paragraph and a group with a background color.

Unfortunately, the preview item of the Group Block does not show this color style because inline the following style is set:
```
color: rgb(0, 0, 0);
background-color: rgb(255, 255, 255);

```
I haven't found a reason why on a Group Block the inline style should override a background-color. 

## What is your proposed solution?
Would be great to get a way to disable this if it can not be removed by default. 
Overriding with "!important" doesn't feel the right solution in long term.

**Comment by getdave** [comment] 2021-04-23 15:53
@Jugibur Thanks for raising this. I can confirm that this is where those colors are added by the `example` definition on the Group block:

https://github.com/WordPress/gutenberg/blob/3ac3f5a1df5b77d4a6545ad214a07344192b383d/packages/block-library/src/group/index.js#L30-L38

Instead of using CSS to manipulate this you can manually override these examples via hooks. For example, if you want to change the colours used in the example on the `core/group` block you could register a plugin and enqueue some JS and do something like this:

```js

function alterGroupBlockExample( settings, name ) {
	if ( name !== 'core/group' ) {
		return settings;
	}

	// Amend the color used in the example.
	settings.example.attributes.style.color = {
		text: '#000000',
		background: '#ff69b4', // pink!
	};
	return settings;
}

wp.hooks.addFilter(
	'blocks.registerBlockType',
	'my-plugin/examples/group-block',
	alterGroupBlockExample
);
```

More info on using hooks in JS is available at https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/.

I was able to run this and see the colors change on the Group block example.

As to why these styles are applied inline - I suspect it is because they are defined dynamically and thus we can't enqueue CSS files for them. 

I hope that helps? I'm going to close this Issue for now but feel free to reopen if you feel there is more information you can provide or you have further concerns.

**Closed as completed by getdave** 2021-04-23 15:53 UTC
Labels: Needs Technical Feedback, [Feature] Theme Style Variations
