### ISSUE TITLE
Publish or update post doesn't work with Gutenberg 2.3 and 2.4

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#5660] opened 2018-03-16 13:36 UTC
## Issue Overview
Wordpress 4.9.4, PHP 7.0.19, Database Percona 5.6.35
Publish or update a post doesn't work ("Updating failed") with Gutenberg 2.3 and 2.4.
Deactivating all other plugins does not help.
Changing language from German to English does not help.
Deleting Gutenberg, logout from wordpress, login again , reinstalling Gutenberg does not help.
Tried with Firefox, Chrome, Opera - does not help.
Only if I make a rollback of the plugin to version 2.2 everything works again.

**Comment by jasmussen** [comment] 2018-03-16 15:19
Thanks for the issue. I can't reproduce this myself. 

Can I ask you to open the JavaScript console and see if there are any errors you can share? Here's how to open the console in Chrome: https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by burnuser** [comment] 2018-03-16 17:47
New page, but unable to publish or save it.
Error (replaced real website with term "WEBSITE"):
PUT http://WEBSITE/wp-json/wp/v2/pages/182 403 (Forbidden)
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,underscore,shortcode,backbone,wp-util,wp-backbo&load[]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=4.9.4:4
PUT http://WEBSITE/wp-json/wp/v2/pages/182 403 (Forbidden)

**Comment by SuperGeniusZeb** [comment] 2018-03-16 23:44
What content are you putting on the post, or is it just an empty one? Is it literally a post or is it a page or some other post type? I've been having an issue with saving drafts of / publishing posts in Gutenberg since 2.3 (and continuing into 2.4) as well, but only with certain textual content... I'm still trying to figure out precisely what causes it, and every time I try saving the post a bunch of times and get the "Updating failed" error, I end up getting temporarily banned from the server I'm using for around 30 minutes or so. (I'm not using Cloudflare like some other people who posted similar issues were.) And when trying to save the draft / publish I'm getting errors about PUT requests and involving `load-scripts.php`, but with error code 500. I'm not sure if it's the same or a different bug from what you're having, but I thought I'd post what I know here since I don't think I have enough info to make my own ticket yet.

**Comment by thebugfixnet** [comment] 2018-03-17 11:32
Please see also https://github.com/WordPress/gutenberg/issues/3252 or https://github.com/WordPress/gutenberg/issues/2565 it might be related to a firewall / security plugin ... and yes some firewall plugin keeps the entries in .htaccess active also if they plugin ist deactivated or uninstalled...

**Comment by nikola3244** [comment] 2018-03-22 20:29
Same issue here. (I think. Might be different one.)

## Details
### Environment details

- Apache/2.4.29 (Unix) PHP/7.2.3
- localhost (whole WordPress instance is contained in a subdirectory, if it matters)
- Tried on *WordPress 4.9.4* (latest public release) and on *WordPress 4.9.5-beta1-42867-src* (latest code on SVN)
- No firewalls
- No security plugins
- REST API is accessible at `/wp-json`
- Active plugins:
    * 4.9.4:
        - Gutenberg: Version 2.4.0 by Gutenberg Team<sup>[1]</sup>
        - Health Check: Version 1.0.1 by The WordPress.org community<sup>[1]</sup>
    * 4.9.5-beta1-42867-src
        - Gutenberg: Version 2.4.0 by Gutenberg Team<sup>[1]</sup>

### How to reproduce

1. Open an existing or try to create new post/page
2. Make any change in the page<sup>[2]</sup>, and click on "Update"
3. Error message `Updating failed`/`Publishing failed` appears

#### Network request data<sup>[3]</sup><sup>[4]</sup>
- General
    * Request URL: http://localhost/~nikola/wp495b1/wp-json/wp/v2/posts/11
    * Request Method: PUT
    * Status Code: 403 Forbidden
- Response Headers
    * HTTP/1.1 403 Forbidden
    * Server: Apache/2.4.29 (Unix) PHP/7.2.3
- Request Headers
    * PUT /~nikola/wp495b1/wp-json/wp/v2/posts/11 HTTP/1.1
    * Host: localhost
    * Connection: keep-alive
    * Content-Length: 40
    * Pragma: no-cache
    * Cache-Control: no-cache
    * Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    * Accept: */*
    * X-Requested-With: XMLHttpRequest
    * X-WP-Nonce: *[redacted]*
    * Referer: http://localhost/~nikola/wp495b1/wp-admin/post-new.php
    * Cookie: *[redacted]*
- Form Data: `title=test&status=publish&content=&id=11` (with no blocks and title set to `test`)

#### Console data<sup>[3]</sup>

```
Failed to load resource: the server responded with a status of 403 (Forbidden)          /~nikola/wp495b1/wp-json/wp/v2/posts/11
```

### Additional Comments
Not sure if it's related, but clicking on `Preview` gives a blank window with the following text centered in the middle of the screen:
```
Please wait… 

Generating preview.
``` 

Also, "Save Draft" returns HTTP 403 as well.

----
1. Installed from [Gutenberg](https://wordpress.org/plugins/gutenberg/) and [Health Check](https://wordpress.org/plugins/health-check/) wordpress.org plugin pages.

2. Example content:
Title & Classic block, Classic block contains any plain text. Issue still occurs even when Classic block is removed.

3. The request data is from *WordPress 4.9.5-beta1-42867-src*, but it is identical in *WordPress 4.9.4* as well

4. Removed unrelated headers

**Comment by pento** [comment] 2018-03-22 22:26
Thanks for the bug report, @burnuser and @nikola3244!

I think I have a fix for this, could I get you to test #5741?

If you don't have a development environment setup, you can also test with Gutenberg 2.4, by copy/pasting this [function and hook](https://github.com/WordPress/gutenberg/blob/315475406d1882351f7b7b74111e347218a8abcc/lib/compat.php#L105-L134) into your install.

**Comment by nikola3244** [comment] 2018-03-22 23:44
@pento Cheers! That did it :+1:

**Comment by mtias** [comment] 2018-03-26 03:15
Closing as appears the change fixed it for folks. Please, reopen if you still see issues.

**Closed by mtias** 2018-03-26 03:15 UTC
Labels: [Status] Needs More Info

**Comment by jutta-livingmiracles** [comment] 2018-12-25 21:08
Hi, this issue is still occurring for me. I'm not a developer in any way, so if someone can help me troubleshoot, that would be really lovely. I have a SiteGround-hosted WordPress site; WP 5.0.2 and cannot update pages. I get the "Updating failed" error in the editor, and the following console errors in the Chrome Inspector:

POST /wp-json/wp/v2/pages/1242?_locale=user 403
POST /wp-json/wp/v2/pages/1242/autosaves?_locale=user 403

**Comment by chibani** [comment] 2019-02-01 15:57
Same for me.
With the classic editor, the current command: `wp.media.frame.on('all', function(e) { console.log(e); });` logs every event in browser's dev console.  
With Gutenberg, the same command doesn't do anything.

Originally, I was working on a script that uses : `wp.media.featuredImage.frame.on('open', /* my code */);`, that has stopped working since I upgraded my WordPress installation to WP 5
