### ISSUE TITLE
Increase the width of media-attachment-date-filters on Media Upload Box

### ISSUE THREAD

**Issue by monika-12** [WordPress/gutenberg#4034] opened 2017-12-15 09:24 UTC
## Issue Overview
On Media Upload Modal Box the width of "Date Filter" is too small. It's not displaying properly.

## Steps to Reproduce (for bugs)
1. Click on set featured image
2. Check "Date Filter" on Media Upload Box 
3.Text is not visible on select field because of small width.

## Expected Behavior
It should display on required width so text will visible on select field.

### Current Behavior - Issue on date Filter on Media Upload Box
![date_filter](https://user-images.githubusercontent.com/695201/34041959-c4ce19ac-e19a-11e7-8640-ec9bfdb46b73.png)

### Expected Behavior - Increase the width of date filter on Media Upload Box
![date_filter_correct](https://user-images.githubusercontent.com/695201/34041967-ccd35d7e-e19a-11e7-8dff-678de3cca6ed.png)

<sup>Edit @Soean: added the screenshots as inline image. (Drag&drop into the textarea)</sup>

**Comment by Soean** [comment] 2017-12-15 10:19
@monika-12 Thanks for your bug report. I can't see the video / screenshot you linked, because they need a login.

**Comment by monika-12** [comment] 2017-12-15 11:43
Hey @Soean 
I've updated the link please try this one. You will get screenshots of image.

**Comment by rahulsprajapati** [comment] 2017-12-17 12:20
I think this one is because of the first dropdown is missing.

<img width="355" alt="screen shot 2017-12-17 at 5 48 42 pm" src="https://user-images.githubusercontent.com/10358350/34079381-b2b490a2-e352-11e7-90a7-bfffd3566171.png">

**Comment by Soean** [comment] 2017-12-29 19:16
Duplicate of #2202 
@nielslange thanks for referencing

**Closed by Soean** 2017-12-29 19:16 UTC
Labels: Good First Issue, Media, [Type] Bug
