### ISSUE TITLE
CSS rules for links in the editor are too specific

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#59782] opened 2024-03-12 12:43 UTC
### Description

The rules which apply link colours in the editor are too specific and cannot easily be overridden.

The specificity of `.editor-styles-wrapper a:not([class^=components-]):not([class^=editor-]):not([class^=block-]):not([aria-owns]):not([id^=mceu_])` is 0,6,1.

The rule `.editor-styles-wrapper .wp-block-sht-author-list__author-name-link` (from a custom block) cannot override it, because the specificity is 0,2,0.

### Step-by-step reproduction instructions

1. Compare the specificity of the rules above.

### Environment info

- WordPress 6.4.3, no plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2024-03-12 17:04
Thanks for the report.

> The specificity of `.editor-styles-wrapper a:not([class^=components-]):not([class^=editor-]):not([class^=block-]):not([aria-owns]):not([id^=mceu_])` is 0,6,1.

I couldn't find such a selector in the Gutenberg project. Also, for example, if I define a link color in a group block, the CSS selector will be as follows (Tested on WP6.4.3):

```
.editor-styles-wrapper .wp-elements-0 a
```

![css-selector](https://github.com/WordPress/gutenberg/assets/54422211/0db4f2c0-1636-47c0-8a12-928a324284bd)

Is there a way to reproduce that selector?

**Comment by markhowellsmead** [comment] 2024-03-12 18:58
Thanks for your feedback. That selector is copied from the developer tools inspector, from any link in the editor.

**Comment by t-hamano** [comment] 2024-03-13 10:45
Maybe it's due to another library? I found the issue below.

https://github.com/m-e-h/postcss-editor-styles/issues/2

**Comment by aaronrobertshaw** [comment] 2024-03-14 01:53
Thanks for taking the time to submit this issue @markhowellsmead 👍 

I'd like to second @t-hamano's comments here.

There are no references to any of the `a:not` clauses from the reported selector within Gutenberg or WordPress core. It stems from the `postcss-editor-style` plugin [here](https://github.com/m-e-h/postcss-editor-styles/blob/master/index.js#L37).

On the Gutenberg and WP Core side of things, link colors are applied in the following manner:

Within the editor, the [selector used](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/constants.js?plain=1#L265) to apply link colors is `a:where(:not(.wp-element-button))`. It gets applied to specific blocks by [scoping that selector](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/style.js?plain=1#L404-L407) with a [single class generated](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/style.js?plain=1#L372-L374) for that block instance e.g. `.wp-elements-0`. This also matches the [selector and approach used on the frontend](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/elements.php?plain=1#L133-L138).

As this is an issue with a plugin rather than Gutenberg specifically, I'll close this GitHub issue.

**Closed as not planned by aaronrobertshaw** 2024-03-14 01:53 UTC
Labels: [Type] Bug, [Status] Needs More Info, Needs Testing

**Comment by markhowellsmead** [comment] 2024-03-14 11:47
> There are no references to any of the a:not clauses from the reported selector within Gutenberg or WordPress core. It stems from the postcss-editor-style plugin here <https://github.com/m-e-h/postcss-editor-styles/blob/master/index.js#L37>.
> 

Thanks for looking into this so thoroughly. You’re right, the additional clauses are being added by PostCSS. I’ve used the reference at https://github.com/m-e-h/postcss-editor-styles/blob/master/index.js#L36 to amend our build process: by removing the `tagSuffix` in the config, only the Block Editor rules are added.
