### ISSUE TITLE
Wrong stylesheet loading order in the editor.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#30246] opened 2021-03-25 13:54 UTC
When you open a saved post/page in the editor, the stylesheets are not being loaded in the right order causing potentially some differences between editor and frontend.

For example:

 - Use the empty theme (no stylesheet)
 - Add the "latest comments" block
 - Save and reload the editor
 - Notice the comment text's size is different.

This is due to the "enqueue" calls existing in the WP_Block_Type class's render function.

 - A potential fix could be to not enqueue these in the admin
 - The idea fix would be to rearchitecture how lazy loading styles works because that render function can be triggered in any context when fetching "posts" even if we're not actually rendering that post.

cc @aristath @gziolo

**Comment by gziolo** [comment] 2021-03-25 14:00
Related work in progress in https://core.trac.wordpress.org/ticket/50328.

**Comment by skorasaurus** [comment] 2021-07-19 18:42
@gziolo is this fixed with https://core.trac.wordpress.org/ticket/50328 being closed?

**Comment by gziolo** [comment] 2021-07-19 19:19
I think @aristath would be the best person to confirm.

**Comment by ndiego** [comment] 2022-07-19 13:20
In following the testing steps, this issue appears to no longer exist. @youknowriad are you comfortable with closing this issue?

**Comment by kathrynwp** [comment] 2022-09-05 17:53
@youknowriad @aristath @gziolo I'm going to go ahead and close this out, but if it's still valid, feel free to add a comment with additional details and I’ll be glad to reopen it. Thanks!

**Comment by aristath** [comment] 2022-09-05 17:57
Perhaps I'm misunderstanding the purpose or I'm missing some context... But if this has not been tested and actually been resolved, then why close it? 
Closing unresolved issues and marking them as resolved doesn't exactly make things easier when we're trying to figure out what bugs we need to address and why...

**Comment by kathrynwp** [comment] 2022-09-05 18:19
@aristath I'm helping triage this repo, focussing on issues marked as Stale.

Further above, someone had asked "is this fixed with https://core.trac.wordpress.org/ticket/50328 being closed?" and @gziolo then mentioned that you would be the best person to confirm. If you're able to confirm, that would be really helpful. 

I'll reopen this for now. Thanks!

**Comment by kathrynwp** [comment] 2022-09-05 18:21
In addition, @ndiego mentioned that 

>  In following the testing steps, this issue appears to no longer exist.

So it seems like the issue is fixed, unless someone is able to confirm otherwise.

**Comment by aristath** [comment] 2022-09-06 06:01
Tested and confirmed this has been resolved.
Thank you @kathrynwp 👍

**Closed as completed by aristath** 2022-09-06 06:01 UTC
Labels: [Type] Bug, [Status] Needs More Info, [Feature] Themes, CSS Styling
