### ISSUE TITLE
Abysmal response time when fetching pages to be listed in page attributes

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#5376] opened 2018-03-03 18:02 UTC
## Issue Overview
In my development machine the elapsed server time for invoking the classic-editor is around 2.5 seconds. 

When using Gutenberg the elapsed server time to return the results for the Page Attributes
select list is 7.5 seconds. 

And that's just one of the REST requests.

It needs to be a lot quicker.

## Steps to Reproduce (for bugs)

1. Edit a hierarchical custom post type  which has a custom taxonomy
2. Measure the elapsed server performance for each request
3. Tabulate the results and compare with the time to load the classic-editor

## Expected Behavior
From the Core philosophies [Clean lean and mean section](https://make.wordpress.org/core/handbook/about/philosophies/#clean-lean-and-mean)

The core of WordPress will always provide a solid array of basic features. 
It’s designed to be lean and fast, and will always stay that way.

Gutenberg should be as quick as or better than the classic-editor. 

## Current Behavior
It's not. It's far too sluggish. 

Time to invoke classic editor. 2.5 secs
For Gutenberg, in a particular development environment I'm getting

Time (secs)  | Request 
----- | --------
3.2 |  Edit
2.0 | Custom taxonomy query
2.0  | Custom taxonomy list
2.4 | Users
7.5 | Page attributes
17.1   | TOTAL

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by bordoni** [comment] 2018-03-04 01:30
Just to make sure, are all of these Requests sequential? On my local environment they seem to fire at the same time when I load the page, and they are pretty fast (about 1.2seconds for Page Attributes).

Do you have any particular plugins active?

**Comment by bobbingwide** [comment] 2018-03-04 08:15
In that particular environment I have quite a few plugins, none of which do anything which is REST related except perhaps some the_content filtering. The requests aren’t run in parallel if you keep the sidebar boxes closed initially. I admit my environment is slow. 
I’m just using these figures to make a point. 
The server load of the editor is much greater.
And this is before we take mega data (more than 100 items)  into account.

**Comment by bobbingwide** [comment] 2018-03-04 13:53
When using the classic-editor the total elapsed time for `page_attributes_meta_box()` is just over 0.14 seconds, the SQL query taking just 0.005 seconds.

The REST API is slow since:
1. The whole of WordPress has to be loaded.
2. `the_content` is being run for every post. 
3. Sometimes more than once.

**Comment by danielbachhuber** [comment] 2018-03-19 17:08
It looks like a `_fields=` parameter [landed in WordPress 4.9](https://core.trac.wordpress.org/ticket/38131#comment:36). However, WordPress still _generates_ every field and then filters it out. Ideally, the fields wouldn't be generated in the first place.

@bobbingwide I suspect your particular problem is exacerbated by having so many shortcodes in your post content.

**Comment by bobbingwide** [comment] 2018-03-20 08:47
@danielbachhuber Yes. Any shortcode expansion, other than for the title, is unnecessary. So is wpautop and, of course, dynamic block processing. Perhaps you like to try the same experiment with 40 or so pages each containing the Recent posts block. 

When I convert my shortcodes to blocks I’ll still have the problem.

**Comment by lougreenwood** [comment] 2018-04-24 15:52
Just wanted to say +1 for any REST API performance improvements - @bobbingwide, you mentioned that part of the reason for the problem is that the "whole of WP has to be loaded" - seems that issue is also being felt in the wild for some time: https://stackoverflow.com/questions/45421976/wordpress-rest-api-slow-response-time/45425091#45425091

Personally, we're about to launch a product which extensively uses WP as a REST-only application server and the UI is provided by an SPA, so I'm very encouraged to see WP REST API "dogfooding" happening :)

**Comment by danielbachhuber** [comment] 2018-04-26 22:08
> However, WordPress still _generates_ every field and then filters it out. Ideally, the fields wouldn't be generated in the first place.

I've created a Trac ticket for this: https://core.trac.wordpress.org/ticket/43874

**Comment by danielbachhuber** [comment] 2018-05-09 23:40
With https://core.trac.wordpress.org/changeset/43087, the performance of `GET wp/v2/pages?_fields=id,title` will significantly improve. You may see this as soon as WordPress 4.9.7. There are no additional changes we need to make in Gutenberg, however.

**Closed by danielbachhuber** 2018-05-09 23:40 UTC
Labels: Core REST API Task, Performance, [Type] Enhancement

**Comment by bobbingwide** [comment] 2019-01-31 11:18
I need to reopen this issue. I can't see the `_fields` parameter being used for the Page Attributes requests.
