### ISSUE TITLE
Date picker formatting on publishing flow has too much space one side

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19416] opened 2020-01-06 11:31 UTC
The spacing seems a little off on Chrome, latest build:

![ cd](https://user-images.githubusercontent.com/253067/71815669-1bde8c80-3078-11ea-8599-1d518b971f80.png)

**Comment by tellthemachines** [comment] 2020-01-07 00:15
Closing as duplicate of #19228 which has been fixed in #19294.

**Closed by tellthemachines** 2020-01-07 00:15 UTC
Labels: Good First Issue, [Package] Components

**Comment by karmatosed** [comment] 2020-01-07 13:19
@tellthemachines it hasn't been fixed though if I saw this in master has it?

**Comment by tellthemachines** [comment] 2020-01-09 03:04
Rebuilding latest master should the updated version:

<img width="286" alt="Screen Shot 2020-01-09 at 2 03 18 pm" src="https://user-images.githubusercontent.com/8096000/72034321-ceb52180-32e8-11ea-8928-c1d668bfc183.png">
