### ISSUE TITLE
The block I'm trying to move up goes behind the block I am trying to move the block.

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#18520] opened 2019-11-14 16:47 UTC
**Describe the bug**
When I am trying to move a block up, it seems that the Heading block merges with the block in front of it.
**To reproduce**
1. Create a new page/post
2. Add 3+ blocks (I tried Paragraph blocks)
3. Add a heading block.
4. Try to move the block up with the up arrow button in the editor.
5. Heading seems to merge into Paragraph block.
**Expected behavior**
I expect the block I am trying to move up moves up as well as the block that was there moving down. This has only been happening since I updated WordPress to 5.3.
**Screenshots**
I do have a video: [http://calumchilds.com/videos/wordpress-gutenberg-issue-1.mp4](http://calumchilds.com/videos/wordpress-gutenberg-issue-1.mp4)
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 70
**Additional context**
- I am using Gutenberg 6.8, which is the version that shipped with WP 5.3. I haven't had any problems like this before upgrading.

**Comment by Wingo5315** [comment] 2019-11-16 07:28
Just an update: I tested it in Brave (Chromium) and it seems to be working fine. I never had this problem before I upgraded to WP 5.3, so I think it must be something to do with the moving up-and-down animations not working properly in Firefox. #17890

**Comment by ellatrix** [comment] 2019-11-20 14:09
Cc @youknowriad.

**Comment by ellatrix** [comment] 2019-11-20 14:11
I cannot reproduce the bug on a Mac, so maybe it's Window+Firefox specific.

**Comment by Wingo5315** [comment] 2019-12-18 16:29
Until we find a solution to this problem, maybe disable the Storybook animations for devices with a Windows + Firefox setup?

**Comment by talldan** [comment] 2020-02-03 05:33
@Wingo5315 I think you mentioned in slack that you're still experiencing this issue. I tested and wasn't able to reproduce an issue using the steps provided (Firefox 72.0.2 / Windows 8.1 / Gutenberg plugin v7.3.0 ).

Could you let us know which theme you're using? I tried a couple. Also, did you update the plugin when testing most recently?

**Comment by Wingo5315** [comment] 2020-02-19 05:28
> Could you let us know what theme you're using?

I was using my own custom-made theme, Ballyhoo (http://ballyhoo.calumchilds.com) but if you reproduce these steps at [wordpress.org/gutenberg](http://wordpress.org/gutenberg) or with any other theme, whether custom-made or not, the same glitches still happen.

**Comment by karmatosed** [comment] 2020-03-16 20:42
I am unable to replicate this using the latest version of Gutenberg. If you are still experiencing we can absolutely reopen, for now, closing.

**Closed by karmatosed** 2020-03-16 20:42 UTC
Labels: Needs Testing, [Package] Block editor, [Status] Needs More Info, [Type] Bug
