### ISSUE TITLE
Parent pages REST API call poses a serious performance issue

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#17160] opened 2019-08-23 09:41 UTC
**Describe the bug**
When the editor loads for a new page, a REST API request is made to fetch the possible parent posts in order to populate the relevant dropdown.

```
http://my-server.test/wp-json/wp/v2/pages?per_page=100&exclude=2&parent_exclude=2&orderby=menu_order&order=asc&context=edit&_locale=user
```

What this dropdown need is only the post ID and the post title. What actually happens is that for each of the possible parent posts retrieved, a full post object (with `edit` context) is returned, which causes all the relevant filters to be applied.

**To reproduce**
1. Create a simple filter hooked on the `the_content`.
2. Create a new page and notice how many times the filter callback is triggered.

**Expected behavior**
The filter callback is triggered as many times as the number of possible parent posts retrieved by this REST API call.

I know that the maximum number of posts that this filter will be applied is 100 and in most sites, there are even less than 100 posts available, but again this behavior is something that could be avoided.

**Comment by youknowriad** [comment] 2019-08-23 11:35
I agree, that's a concern. This issue is a duplicate of #13618 though.

**Closed by youknowriad** 2019-08-23 11:35 UTC

**Comment by kmgalanakis** [comment] 2019-08-23 12:18
Thanks @youknowriad
