### ISSUE TITLE
No Content Block editing option is displayed when Show Template + Design Mode is turned on

### ISSUE THREAD

**Issue by yogeshbhutkar** [WordPress/gutenberg#67231] opened 2024-11-22 13:02 UTC
### Description

When Show Template is enabled, the content block editing options displayed in the write mode are missing from the Visual Design mode.

### Step-by-step reproduction instructions

1. Go to edit a post screen.
2. Turn on show template.
3. Navigate to the Design Mode and choose the content block.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/09b7a663-7b11-4ac7-9d16-ccea86569e6e)

![Image](https://github.com/user-attachments/assets/c88ae608-0bcd-464a-8e28-4c663be84e9e)

### Environment info

- WordPress Version 6.7 RC 1
- Gutenberg Plugin: 19.7.0-rc.2
- OS: Mac OS Sonoma

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment] 2024-11-22 13:05
The issue (https://github.com/WordPress/gutenberg/issues/67129) discusses removing the content block editing features from the Write Mode but does not discuss adding them to the Visual Mode. Not sure if it's intentional.

**Comment by annezazu** [comment] 2024-11-26 18:13
Hey folks! Thanks for opening this issue. From what I can see, this is a duplicate of https://github.com/WordPress/gutenberg/issues/67129 mentioned above. As a result, I'm going to close this out. If I'm missing something about how this is not a duplicate, please say so. I'm happy to reopen if that's the case.

**Closed as completed by annezazu** 2024-11-26 18:13 UTC
Labels: [Type] Bug
