### ISSUE TITLE
"The theme you are currently using is not compatible with the Site Editor" on hybrid themes

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#52847] opened 2023-07-21 20:01 UTC
### Description

We use a hybrid theme (use Block Editor for content, has a couple of Template Parts, but doesn't use FSE.)

When testing out 6.3-RC-1, I keep running into "The theme you are currently using is not compatible with the Site Editor".

### Step-by-step reproduction instructions

Just one of may ways:

1) Appearance -> Template Parts.
2) Edit a template part.
3) Use "<" to go 'back' to Patterns, and select Manage all of my Patterns.
4) Hit my browser's back button, and voila.

### Screenshots, screen recording, code snippet

![2023-07-21 15_00_13-WordPress › Error](https://github.com/WordPress/gutenberg/assets/945157/f5634fa9-c36a-46d8-b858-dce72025408e)

### Environment info

WordPress 6.3-RC-1. Windows 10, Chrome. No Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-07-24 17:16
Thanks so much for reporting this on!

**Comment by Mamaduka** [comment] 2023-08-14 15:35
@ndiego, any reason for re-opening this?

**Comment by MadtownLems** [comment] 2023-08-14 15:42
I'm exploring this again on the 6.3 actual release, and it does seem like it's harder to trigger the error, I'm still getting it a lot. Here's an easy way:

Appearance -> Template Parts
Ctrl-K to open the Command Palette
Manage all of my Patterns
Then use the Browser's Back Button

"The theme you are currently using is not compatible with the Site Editor."

I'm wondering if perhaps things are showing up in the Command Palette that I'm not supposed to be able to access, being a hybrid theme?

**Comment by Mamaduka** [comment] 2023-08-14 15:45
@MadtownLems, correct. Some of the commands shouldn't be available for hybrid themes. That's being tracked in #52154.

**Comment by t-hamano** [comment] 2023-08-21 13:15
Since #53718 has been merged, I believe all commands are now properly displayed in the search results on all themes in the latest trunk. I would like to close this issue, but if the issue remains, please comment.

**Closed as completed by t-hamano** 2023-08-21 13:15 UTC
Labels: [Status] In Progress, [Type] Regression, [Feature] Template Editing Mode

**Comment by manspaniel** [comment] 2024-10-02 23:49
For me, navigating to the Template Part editor worked fine, but refreshing triggered this error.

Simple fix that worked in my case:
```php
add_theme_support('block-template-parts');
```

**Comment by t-hamano** [comment] 2024-10-03 08:48
@manspaniel 
If you are experiencing any issues, could you tell me the steps to reproduce the problem? Does this mean that classic themes that don't support template parts can unintentionally open the template part editor?
