### ISSUE TITLE
adding new category in gutenburg editor doesn't show in preview

### ISSUE THREAD

**Issue by DigitalDavo** [WordPress/gutenberg#13171] opened 2019-01-03 01:03 UTC
If you add a new category to an existing post using the gutenburg editor, this new category is not present in the preview window, but does appear after you update the post.

Update an existing post and create a new category. Hit the preview button and see that the preview does not include the new category as a link. You need a theme that lists the categories in the post itself to see this.

Could be a theme bug I guess but it was certainly unexpected behaviour and made me wonder if the category creation in the edit session had suceeded.

**Comment by youknowriad** [comment] 2019-01-04 10:33
duplicate of #12472

**Closed by youknowriad** 2019-01-04 10:33 UTC
Labels: [Component] Post Settings
