### ISSUE TITLE
List block: Equalise spacing between list elements

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#14100] opened 2019-02-25 20:12 UTC
Spacing between list elements isn't consistent throughout a nested list. It's easiest to see this when using underscores instead of text:

![list-item-spacing](https://user-images.githubusercontent.com/376315/53365466-3c5a9800-3939-11e9-8c8f-a794f5e35ada.png)

But I measured to be sure I wasn't seeing things:

![list-item-spacing-counted](https://user-images.githubusercontent.com/376315/53365465-3c5a9800-3939-11e9-9cff-9e777b53319e.png)

This looks to be happening because the margin between the content of an `<li>` and the `<ul>` nested inside it is defined solely by the line-height of the parent `<li>` element. Adding a bit of top-padding to the child `<ul>` will even things out, so the spacing between list items is consistent across the list.

**Comment by kjellr** [comment] 2019-03-05 17:13
@sarahmonster Is this still an issue? I just tested using the Gutenberg Starter Theme (which has no editor styles), and the spacing appears uniform for me: 

![artboard](https://user-images.githubusercontent.com/1202812/53823529-fa84af80-3f3f-11e9-8292-665e8cd3269c.png)

**Comment by sarahmonster** [comment] 2019-03-26 21:24
Hm—in both Firefox and Safari, here's what I'm seeing with the Gutenberg Starter Theme:

<img width="912" alt="Screenshot 2019-03-26 at 21 20 38" src="https://user-images.githubusercontent.com/376315/55034282-0d554600-500d-11e9-88c8-52afd1425321.png">

It looks like it's happening on the frontend too:

<img width="358" alt="Screenshot 2019-03-26 at 21 23 02" src="https://user-images.githubusercontent.com/376315/55034540-894f8e00-500d-11e9-94e4-216ad7b09c8c.png">

**Comment by mapk** [comment] 2019-07-16 17:37
I just tested in Firefox using the Gutenberg Started theme and got good results.

**Editor:**

![Screen Shot 2019-07-16 at 10 35 21 AM](https://user-images.githubusercontent.com/617986/61316284-855e9c00-a7b5-11e9-943b-7ecb3b6ac6b7.png)

**Frontend:**

![Screen Shot 2019-07-16 at 10 37 17 AM](https://user-images.githubusercontent.com/617986/61316394-bd65df00-a7b5-11e9-8ded-c781592675ab.png)

**Comment by tellthemachines** [comment] 2020-04-02 05:20
Closing this as I can't reproduce it with the starter theme on any browser. Feel free to reopen if the problem persists!

**Closed by tellthemachines** 2020-04-02 05:20 UTC
Labels: Needs Testing, [Block] List, [Type] Enhancement
