### ISSUE TITLE
Gutenberg reversing the ordered number list not working

### ISSUE THREAD

**Issue by debaryadas** [WordPress/gutenberg#37817] opened 2022-01-10 09:00 UTC
### Description

When you try to reverse the ordered list items in gutenberg block, it is not working.

### Step-by-step reproduction instructions

1. Go to any post page
2. Add the **List** Block
3. <img width="1440" alt="list_block" src="https://user-images.githubusercontent.com/16287281/148736336-bde6f6d3-3ea6-4f32-a77c-7058802d28b1.png">
4. Select **Converted to Ordered List**
5. <img width="1440" alt="converted_to_ordered_lists" src="https://user-images.githubusercontent.com/16287281/148737002-2a820ec0-ca21-4f24-9aac-3d80ef88cd56.png">
6. Add list items.
7. <img width="1440" alt="ordered_list_working" src="https://user-images.githubusercontent.com/16287281/148739284-0a0e22c1-76ae-49dc-85e1-ecd6449a5042.png">
8. Then click on the block and select **Reverse list numbering**
9. <img width="1440" alt="reversed_ordered_listing_not_working" src="https://user-images.githubusercontent.com/16287281/148739335-72cf4013-6a42-4ba6-bdaf-4fd1009af8da.png">
10. It is not working

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment] 2022-01-10 17:45
Thank you for your report and including screenshots. 
i'm able to reproduce this on gutenberg 12.3.0.

**Comment by Mamaduka** [comment] 2022-01-11 06:25
@skorasaurus, I'm not able to reproduce the issue on the current trunk. Am I missing any details?

Testing with Chrome/OSX and TwentyTwentyTwo/TwentyTwenty themes.

## Screencast

https://user-images.githubusercontent.com/240569/148891996-348f76a8-9124-4c66-8eed-0dbea445fb4c.mp4

**Comment by skorasaurus** [comment] 2022-01-11 17:54
@Mamaduka, I am still able to reproduce this, even on trunk (as of commit 15bef9d200e48b0f6f3d2bab8ac0cbdc705ad0fb, built an hour ago from writing this). The issue described by  @debaryadas occurs anytime when you assign an integer to the start attribute.

View the attached video: 

https://user-images.githubusercontent.com/955351/148986533-6e68a3a2-e4cd-44d1-b3dd-d5cd812cfe8e.mp4


You would expect that when the "reversed" attribute is true; that the largest integer, which was previously placed at the last item in the list, would be placed first; which is what happens in @Mamaduka 's example, when you do not assign any value to the 'start' attribute.

**Comment by Mamaduka** [comment] 2022-01-11 18:26
Thanks for the clarification, @skorasaurus. I missed the "start value" settings.

We're using native `<ol>` element attributes, so I think this is expected behavior by the HTML spec.

You can check the official MDN [demo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol), try adding `reversed start="3"` to the `ol` element.

![CleanShot 2022-01-11 at 22 25 23](https://user-images.githubusercontent.com/240569/149000023-4504ab7a-e541-4d8b-94cd-2548e1e07ad5.png)

**Comment by skorasaurus** [comment] 2022-01-11 20:25
Good point; 

Update: hrm, here's an example that I created  https://codepen.io/skorasaurus/pen/zYEMOyd 



The behavior seems according to[ the spec ](https://html.spec.whatwg.org/multipage/rendering.html#lists)seems counterintuitive to me (I too would expect the same behavior that @debaryadas had):

![image](https://user-images.githubusercontent.com/955351/149015879-3143bc39-757b-4b5b-9fcc-763443968008.png)

That when you explicit list 1 as the start; 1 is the first value; 

but when you do not explicit list 1 as the start value; the first value in the list is the highest integer in the list...

but the behavior in gutenberg matches the HTML spec, so I'm closing as expected.

**Closed as completed by skorasaurus** 2022-01-11 20:25 UTC
Labels: [Type] Bug, [Block] List
