### ISSUE TITLE
Add standard block class to List blocks on frontend

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#37871] opened 2022-01-11 12:40 UTC
## What problem does this address?
Currently, List blocks are rendered on the frontend as simply a `<ul>` or `<ol>` and do not include the standard block class `wp-block-list`. In the editor, this class is included. 

Since other blocks use list markup, such as the Navigation block and Social Icons block, it can be hard for theme developers to target List blocks with custom CSS without inadvertantly targeting the list markup in other blocks. 

## What is your proposed solution?
I propose we update the List block to include the class `wp-block-list`. The frontend markup would then be `<ul class="wp-block-list">` or `<ol  class="wp-block-list">`.

**Comment by aristath** [comment] 2022-01-11 13:01
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/12420
PR already exists in https://github.com/WordPress/gutenberg/pull/36676 👍

**Closed as completed by aristath** 2022-01-11 13:01 UTC
Labels: [Status] Duplicate

**Comment by ndiego** [comment] 2022-01-11 13:12
Oops my apologies for the second Issue, thanks @aristath!
