### ISSUE TITLE
Provide configured layout values from theme JSON as CSS variables.

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#33705] opened 2021-07-27 04:31 UTC
## What problem does this address?

Sometimes it's necessary to use the values of `layout.contentSize` or `layout.wideSize` defined in theme.json in a theme's CSS.

## What is your proposed solution?

Render the `layout` values as wp-preset CSS variables: 
```
--wp--preset--layout--content-size
--wp--preset--layout--wide-size
```

**Comment by chthonic-ds** [comment] 2021-07-27 05:43
Previously: https://github.com/WordPress/gutenberg/issues/33184

**Comment by anton-vlasenko** [comment] 2021-07-27 09:17
Since this issue is a duplicate of https://github.com/WordPress/gutenberg/issues/33184 and https://github.com/WordPress/gutenberg/pull/30081, just as @chthonic-ds mentioned, I think it makes sense to close it.

**Closed as completed by anton-vlasenko** 2021-07-27 09:17 UTC
Labels: [Status] Duplicate
