### ISSUE TITLE
Allow custom order by options for query block

### ISSUE THREAD

**Issue by coreyworrell** [WordPress/gutenberg#41440] opened 2022-05-30 17:52 UTC
## What problem does this address?

Currently you can only select from two order options (date or alpha). Allowing other options would be very helpful (modified date, menu_order, etc).

## What is your proposed solution?

Add a filter or something to be used to extend the options [provided here](https://github.com/WordPress/gutenberg/blob/f6a75904cbf4979be6213034e1459ff1c397a948/packages/block-library/src/query/edit/inspector-controls/order-control.js)

**Comment by annezazu** [comment] 2022-05-31 23:03
Hey @coreyworrell! Thanks for opening this up. It appears to be a duplicate of this issue https://github.com/WordPress/gutenberg/issues/40170 so I'm going to close that out and recommend that you follow along there. If this is incorrect though and I've misunderstood, just let me know and I'm happy to reopen :)

**Closed as completed by annezazu** 2022-05-31 23:03 UTC
Labels: [Status] Duplicate
