### ISSUE TITLE
Add Widget Type endpoint

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#25969] opened 2020-10-08 23:15 UTC
Add Widget Type endpoint. This endpoint will list all registered widget types registered in WordPress. 

Fields could include properties from WP_Widget object. 

- id_base
- name
- classname
- customize_selective_refresh
- description

There also could be a method to render the widget's admin form. 

This would not replace https://github.com/WordPress/gutenberg/pull/25958 but would break it into two apis.

**Comment by adamziel** [comment] 2020-10-09 15:01
It seems to be a duplicate of https://github.com/WordPress/gutenberg/issues/25232

**Comment by TimothyBJacobs** [comment] 2020-10-09 16:03
No, this is separate. Something that we could address after the initial widgets changes.

**Comment by spacedmonkey** [comment] 2020-10-09 17:48
@adamziel no it isn't. A widget type api would list all the registered widget types, like search or calendar. Is it the same difference between a block and block type. One is the type of type and other is an instance of it. If that makes sense.

**Comment by adamziel** [comment] 2020-10-12 09:11
> One is the type of type and other is an instance of it. If that makes sense.

Thank you for clarifying - it does make sense now, it would "normalize" the API to speak in database terms and enable developers to reason about types of available widgets. It sounds useful for a minor price of another layer of requests in the widgets editor - should be okay if we leverage batch requests here.

One note I'd like to make here is that if the widgets keep moving in the same direction, the endgame would be deprecating them, migrating to some other format (template parts?), and editing them with FSE. It may or may not happen and if it does it may take some months or years. Still, it's good to look at the widgets-related APIs and plans through the lens of eventually embracing FSE in full.

**Comment by adamziel** [comment] 2020-10-12 09:14
@spacedmonkey to address a note you made in #25958:

> Sidebar endpoint with embeded widgets, widget with embedded widget type.

If all information was embedded, that makes it even easier. I imagine saving would still require separate (batched) requests though?

**Comment by spacedmonkey** [comment] 2020-10-12 09:30
> I imagine saving would still require separate (batched) requests though? 

It would would. 

I like to think of widget a little like a custom post type. With a custom post type, you have an end point to get post data, another for the post type to describe the type and other for an taxonomy. 

So 
https://www.spacedmonkey.com/wp-json/wp/v2/posts <- Raw data 
https://www.spacedmonkey.com/wp-json/wp/v2/types/post <- Type data
https://www.spacedmonkey.com/wp-json/wp/v2/categories <- Taxonomy 
https://www.spacedmonkey.com/wp-json/wp/v2/posts?category=test <- Filtered data. 

I think widgets should be the same. 

https://www.spacedmonkey.com/wp-json/wp/v2/widgets <- Raw data 
https://www.spacedmonkey.com/wp-json/wp/v2/widget-type <- Type data
https://www.spacedmonkey.com/wp-json/wp/v2/sidebar <- Sidebars 
https://www.spacedmonkey.com/wp-json/wp/v2/widgets?sidebar=test <- Filtered data. 

This keeps the design of the api the same across WordPress. 

@adamziel I am completely onboard with getting rid of widgets. But I think that in the process of getting rid of these widgets, I think that gutenberg will need this widget type data at point. Specially as we have to think about a migration path for the like thousands of custom widgets out there.

**Comment by spacedmonkey** [comment] 2020-10-12 18:03
I think can / should roll this endpoint into the widget types endpoint.

**Closed** 2020-10-14 04:26 UTC
Labels: Core REST API Task, [Feature] Widgets Screen
