### ISSUE TITLE
Twitter blocks don't align to center.

### ISSUE THREAD

**Issue by MasterRedz** [WordPress/gutenberg#10473] opened 2018-10-10 12:05 UTC
Hello,

I have some issues to the alignment of twitter and some embedded blocks. For example, in the Twitter block, changing from no alignment to center alignment has no effect on the editor and in the preview.
![immagine](https://user-images.githubusercontent.com/25555957/46734941-f3a98780-cc94-11e8-8436-d53f6340fcc6.png)
![immagine](https://user-images.githubusercontent.com/25555957/46735006-2d7a8e00-cc95-11e8-8a83-3960dcf7b2e2.png)

**Comment by arunsathiya** [comment] 2018-10-14 09:18
My understanding is that by default the block is aligned to the center. When you try to align the block to the left/right, you would notice that the editor and preview show the respective behaviour.

Although the center and no alignment views show that the block is aligned to the center by default.

Without the center alignment:

<img width="722" alt="screenshot 2018-10-14 at 14 45 42" src="https://user-images.githubusercontent.com/18581859/46914803-0dfaa280-cfc0-11e8-9d84-ce86f4ee9d79.png">
<img width="1019" alt="screenshot 2018-10-14 at 14 45 55" src="https://user-images.githubusercontent.com/18581859/46914804-0dfaa280-cfc0-11e8-8f77-3dd2b8691fe6.png">

With the center alignment:

<img width="731" alt="screenshot 2018-10-14 at 14 46 40" src="https://user-images.githubusercontent.com/18581859/46914799-02a77700-cfc0-11e8-92f4-85257b557cae.png">
<img width="1005" alt="screenshot 2018-10-14 at 14 46 52" src="https://user-images.githubusercontent.com/18581859/46914800-02a77700-cfc0-11e8-8ca0-c07d6f76dae3.png">

With left alignment: 

<img width="741" alt="screenshot 2018-10-14 at 14 47 44" src="https://user-images.githubusercontent.com/18581859/46914819-397d8d00-cfc0-11e8-9665-6ec3bb572b59.png">
<img width="983" alt="screenshot 2018-10-14 at 14 47 50" src="https://user-images.githubusercontent.com/18581859/46914820-3a162380-cfc0-11e8-9779-3089bdb4e41e.png">

With right alignment:

<img width="748" alt="screenshot 2018-10-14 at 14 47 59" src="https://user-images.githubusercontent.com/18581859/46914811-32567f00-cfc0-11e8-8e4a-78e589ab2a59.png">
<img width="980" alt="screenshot 2018-10-14 at 14 48 06" src="https://user-images.githubusercontent.com/18581859/46914812-32567f00-cfc0-11e8-8e90-237c245a8d48.png">

[Video indicating this behaviour in the editor and the preview](https://cloudup.com/cBwYA0y2_pJ).

**Comment by designsimply** [comment] 2018-10-16 02:01
Closing since it appears the question has been answered. Thanks @arunsathiya!

**Closed by designsimply** 2018-10-16 02:01 UTC
Labels: [Type] Help Request

**Comment by dadrake** [comment] 2019-04-29 14:42
I wanted to respond to this, as I don't believe this was ever resolved. The answer given doesn't address the content of the block. The block is centered, yes. That's not the issue. The content INSIDE the block is not. So when you have a Tweet embedded, it's left aligned, while the caption text is centered. See below:

![left align](https://user-images.githubusercontent.com/14784191/56903833-13ef3700-6a6b-11e9-9472-d43be74f0785.png)

When using Twitter's basic blockquote embed code, you can add "tw-align-center" to the <blockquote class> seen below:

<blockquote class="twitter-tweet tw-align-center" data-lang="en"><p lang="en" dir="ltr">Since his daughter Jaime was killed in the Marjory Stoneman Douglas High School shooting, <a href="https://twitter.com/fred_guttenberg?ref_src=twsrc%5Etfw">@fred_guttenberg</a> has become one of the loudest and fiercest voices for gun safety. <a href="https://twitter.com/hashtag/OrangeRibbonsforJaime?src=hash&amp;ref_src=twsrc%5Etfw">#OrangeRibbonsforJaime</a> <a href="https://t.co/syI9Zaeso3">pic.twitter.com/syI9Zaeso3</a></p>&mdash; Brut America (@brutamerica) <a href="https://twitter.com/brutamerica/status/1120995799222169602?ref_src=twsrc%5Etfw">April 24, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

This does the intended centering of the Twitter embedded content. However, this can't be accomplished in the Gutenberg blocks.

**Comment by adampatterson** [comment] 2019-05-06 04:21
I can confirm that centering of most media embeds does not work.

Left and right alignment work but it then cause content to wrap around the media in an undesirable ( for me ) way.

Here is some SCSS that mostly worked for me. There is some spacing on the right that I haven't tracked down yet so the Tweet is not 100% centered.

This works for Twitter, Instagram, and Tumblr, if there is something else let me know.

Facebook Posts have some funky static widths applied in a few places so I haven't been able to adjust that one yet.
Facebook Video I treated as a responsive embed (100% width)

```
.wp-block-embed.aligncenter.is-type-rich {
        > .wp-block-embed__wrapper iframe,
        > .wp-block-embed__wrapper twitter-widget {
            margin-left: auto !important;
            margin-right: auto !important;
        }
    }
```

**Comment by CodingNagger** [comment] 2019-10-03 16:38
The issue is still there, adding the "tw-align-center" class to the twitter embed blockquote seems to fix the issue as mentioned by @dadrake .

**Comment by designsimply** [comment] 2019-10-03 18:19
@dadrake 

> The block is centered, yes. That's not the issue. The content INSIDE the block is not. 

I believe this is expected. In general, we affect the container of the embed but not the content inside it. 

> So when you have a Tweet embedded, it's left aligned, while the caption text is centered. See below:

This looks more like a problem with the width of the caption not matching up with the width of the embed. It looks theme-related to me.

I looked a bit deeper and found the centering of the Twitter embed seems to be a overridden by some CSS in the Twenty Nineteen theme: https://cloudup.com/cWEHAH0_jce It would be good to ask about this at https://core.trac.wordpress.org/newticket with the Summary starting with "Twenty Nineteen:".

@CodingNagger

> The issue is still there, adding the "tw-align-center" class to the twitter embed blockquote seems to fix the issue as mentioned by @dadrake .

I couldn't see how to add the "tw-align-center" class to the twitter embed blockquote: https://cloudup.com/cIlySPsMv1q

But even if that worked, we probably wouldn't try to inject CSS in to an external stylesheet like that.

@adampatterson

Using `!important` may be a good workaround for individuals, but it's not a good practice to add `!important` to CSS used by a project such as WordPress as a general practice. We should try to fix the issue in another way.

I think the next step here would be to ask about why the `aligncenter` styles don't work for Twitter embeds in a core Trac ticket and then go from there. Thanks so much for the discussion and for posting workarounds and including screenshots!
