### ISSUE TITLE
Long month name text overflows into drop-down arrow in date picker month selection

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#19230] opened 2019-12-19 00:45 UTC
**Describe the bug**
On WordPress 5.3.2, with Gutenberg 7.1.0, when scheduling a post for a future publish date, the month text for (US English) longer month names (September, November, December) overflows its space into the drop-down indicator.

**To reproduce**
1. Add a new post.
2. Click on "Immediately" next to "Publish".
3. Select "December" from the month drop-down.

**Expected behavior**
I would expect the drop-down menu to have a larger static size and/or resize based on its contents.

**Screenshots**
<img width="388" alt="Screen Shot 2019-12-18 at 4 40 47 PM" src="https://user-images.githubusercontent.com/286171/71135154-b3f20000-21b5-11ea-8e68-e329a563e863.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox
 - Version: 71.0

**Comment by youknowriad** [comment] 2020-01-13 08:19
Closing this as a duplicate of #19415 cause it has an attached PR.

**Closed by youknowriad** 2020-01-13 08:19 UTC
