### ISSUE TITLE
Aspect ratio overridden by featured image link

### ISSUE THREAD

**Issue by djcowan** [WordPress/gutenberg#49017] opened 2023-03-13 03:44 UTC
### Description

Post featured Image aspect-ratio is ignored or overwritten if Post featured image link is enabled.

### Step-by-step reproduction instructions

1. Add a featured image to a post or page.
2. add post-featured block
2.1 enable "Link to page" block setting
2.1. Select an aspect-ratio block setting
2.3 update page
3. View published page
result aspect ratio ignored. 
`.wp-block-post-featured-image a {
    display: block;
}`

### Screenshots, screen recording, code snippet

<img width="1792" alt="Screen Shot 2023-03-13 at 2 31 58 pm" src="https://user-images.githubusercontent.com/2137698/224602298-78ff58bb-93ce-4215-a66d-4edbe39d7bbc.png">
<img width="1792" alt="Screen Shot 2023-03-13 at 2 32 17 pm" src="https://user-images.githubusercontent.com/2137698/224602332-b9f85e78-473d-4c31-a262-e8ba1fbd7fc1.png">
<img width="1792" alt="Screen Shot 2023-03-13 at 2 32 40 pm" src="https://user-images.githubusercontent.com/2137698/224602341-7e1599e3-0c1d-40f9-be26-69222368fe7b.png">
<img width="1792" alt="Screen Shot 2023-03-13 at 2 32 47 pm" src="https://user-images.githubusercontent.com/2137698/224602349-c111bd61-560b-402a-a946-8ec478d9906d.png">
<img width="1454" alt="Screen Shot 2023-03-13 at 2 18 45 pm" src="https://user-images.githubusercontent.com/2137698/224602423-dcd6e0bf-b2d6-48bc-9603-bb6a7a13013c.png">
<img width="1464" alt="Screen Shot 2023-03-13 at 2 19 01 pm" src="https://user-images.githubusercontent.com/2137698/224602452-1ebe1311-e2d8-4bb6-8560-7874bd0ebef0.png">

### Environment info

Wordpress 6.1
Gutenberg Version 15.3.1
Themes: Twenty Twenty-One: 1.7 && Twenty Twenty-Three: 1.0
refs #48079

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by djcowan** [comment] 2023-03-13 04:28
IMHO The child element `<a>` should inherit an innerblock aspect-ratio property value
`.wp-block-post-featured-image **a** {
    display: block;
    aspect-ratio: **inherit**;
}`

**Comment by carolinan** [comment] 2023-03-13 10:17
I am able to reproduce this with WP 6.1.1, Gutenberg 15.3.1 
I am not able to reproduce it with WordPress 6.2 RC1, Gutenberg  15.3.1.

So I wonder if it could be considered solved?

**Comment by kathrynwp** [comment] 2023-03-13 20:09
I _was_ able to replicate with:

WP 6.2-RC1-55510
Twenty Twenty-Three
Gutenberg 15.3.1
No other active plugins

Noting that the bug is only present when "link to page" is toggled **on**:

<img width="278" alt="Edit_Page_“Featured_Image”_‹_Test_Site_ABC_—_WordPress" src="https://user-images.githubusercontent.com/7662449/224820675-1e0d4446-070a-49f6-a53b-2d8972619e4d.png">

As soon as it's toggled off, the selected aspect ratio is respected.

### Editor

<img width="1128" alt="Edit_Page_“Featured_Image”_‹_Test_Site_ABC_—_WordPress" src="https://user-images.githubusercontent.com/7662449/224819981-8a5bddfe-3952-4670-80bc-d63cff67aea9.png">

### Front End

<img width="845" alt="Featured_Image_–_Test_Site_ABC" src="https://user-images.githubusercontent.com/7662449/224820096-10718da6-3abc-4d74-930f-9017d082833e.png">

**Comment by ndiego** [comment] 2023-03-14 14:17
Thanks for reporting @djcowan. This issue has been fixed in https://github.com/WordPress/gutenberg/pull/48495 and will be included in the next version of Gutenberg.

**Closed as completed by ndiego** 2023-03-14 14:17 UTC
Labels: [Type] Bug, Needs Testing, [Block] Post Featured Image
