### ISSUE TITLE
Header Navigation menus aren't displayed when added to site footer

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#47085] opened 2023-01-11 19:04 UTC
### Description

Menus created in the site editor while the Header template part is selected (auto-named `Header Navigation`, `Header Navigation 2`, etc.) won't display if they're added to the Footer template part.

Note: the inverse of this bug is _not_ a problem. `Footer Navigation` menus _will_ display properly if they're added in the Header.

### Step-by-step reproduction instructions

- On a fresh test site (existing sites may have difficulty reproducing), launch the site editor.
- Click into the site header and add a new Navigation block. This will create a `Header Navigation` menu. Modify it however you like.
- Add a second Navigation block. In the editor sidebar, in the `Menu` panel, select `Create new menu` from the dropdown. This one will get the name `Header Navigation 2`. Again, modify it how you like, just ensure you can tell them apart.
- Save your changes.
- Click into the site footer and add a Navigation block.
- In the editor sidebar, in the `Menu` panel, select one of your `Header Navigation` menus.
- Save changes.
- Load the site, and check to see if the menu is visible on the front end.
- Experiment with swapping to `Header Navigation 2` in the footer, and adding both in separate blocks in the footer.
- Load the site and confirm that neither `Header Navigation` menu appears.
- Finally, create a new menu from the footer, which will be name `Footer Navigation`. Save it and confirm that it displays normally.

### Environment info

- WP 6.2-alpha-55053, Gutenberg 14.9.1
- Chrome 109.0.5414.87
- Various themes, but I've just tested specifically in Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment] 2023-01-14 16:46
I've traced this back to 

https://github.com/WordPress/gutenberg/blob/3d2a6d7eaa4509c4d89bde674e9b73743868db2c/packages/block-library/src/navigation/index.php#L585-L587

It was introduced in [this PR which attempted to fix circular references](https://github.com/WordPress/gutenberg/pull/46387/files#r1042803651).



@ajlende Do you have a suggestion for resolving this? Basically the issue is that there might be more than one Nav block on a page with the same `ref`. I thought we could create hierarchical tracking of refs within refs but I don't think there's a way to determine the nested relationship within the block rendering.

I noticed the template part and reusable blocks [handle this by unsetting the "seen" value after rendering the inner blocks](https://github.com/WordPress/gutenberg/pull/28456/files#r587403257). Not sure we can do that though...

**Closed as completed** 2023-01-26 14:58 UTC
Labels: [Type] Bug, [Block] Navigation
