### ISSUE TITLE
Made site unusable

### ISSUE THREAD

**Issue by jwkokc** [WordPress/gutenberg#8668] opened 2018-08-07 16:52 UTC
I installed and activated the plugin yesterday. Immediately, all of the published pages for my site vanished. The dashboard still indicated 12 pages in its count, but displayed only one and it was stored as a draft.

Attempting to view the site showed no pages at all, although the header, widgets, and footer were visible and operated as expected.

After an hour or so of attempting to discover what was happening, I deactivated the gutenberg plug-in. The missing pages returned immediately, and the site once again worked properly.

I won't be re-activating it until the reviews indicate it's closer to being ready for use, but I've felt that the development team should be aware of this show-stopper.

**Comment by youknowriad** [comment] 2018-08-07 17:45
Thanks for the report.

I think this is a duplicate of #8455 

The main reason for this was fixed by a recent PR #8578 

That said, it can still happen if you have conflicting plugins, (you may want to check the JavaScript console for any potential errors from conflicting plugins)

ì'm going to close this issue, feel free to create a new one if you have more details about conflicting plugins/ errors.

**Closed by youknowriad** 2018-08-07 17:45 UTC
