### ISSUE TITLE
Group visibility

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#21341] opened 2020-04-02 07:50 UTC
Hi
I had a 1px solid rgba($primary,0.1) and 10px padding to .wp-block-group in the admin and it made my life easier editing content.
Groups are powerful, but interacting with them in the admin is sometime frustrating.
It also help the final user understand the structure.

**Comment by talldan** [comment] 2020-05-27 01:26
Seems to be a duplicate of #20453

**Closed by talldan** 2020-05-27 01:26 UTC
Labels: [Block] Group, [Type] Enhancement
