### ISSUE TITLE
Editor crash if no used/registered block pattern categories

### ISSUE THREAD

**Issue by NicktheGeek** [WordPress/gutenberg#27864] opened 2020-12-22 20:29 UTC
**Describe the bug**
When core block patterns are disabled and registered block patterns do not use a category the block editor crashes into recovery mode.

Copied error from recovery mode
```
https://example.com/wp-includes/js/dist/block-editor.min.js?ver=5f6a75cdc59f1a900e9d4bcfb43bddba:12:207782
some@[native code]
filter@[native code]
useMemo@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:216:442
Vl@https://example.com/wp-includes/js/dist/block-editor.min.js?ver=5f6a75cdc59f1a900e9d4bcfb43bddba:12:207694
we@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84:294
zj@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:226:498
Th@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:225
tj@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:154
Te@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:153
Te@[native code]
https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:69
unstable_runWithPriority@https://example.com/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:261
Pg@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:16
ha@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:453
https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236:61
Ei@https://example.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41:90
Ei@[native code]
```

Additional console logged error copied:
```
[Error] TypeError: undefined is not an object (evaluating 't.categories.includes')
```

**To reproduce**
1. Unregister core block patterns with `remove_theme_support( 'core-block-patterns' );`
2. Register at least one non-core block pattern without a category
3. Go to edit a post or create a new post
4. Click top "plus" button to add a new block
5. Click the "patterns" tab.

This should generate the error.

**Expected behavior**
The code should check to see if there are categories before attempting to use them and not fail if none of the registered block patterns are using a category.

**Media**
To help with my explanation of what triggers the error in the block editor, I recorded a short video.

https://user-images.githubusercontent.com/835568/102930389-52204200-446a-11eb-8a99-d905c79c011f.mp4

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: osX but likely affects all
 - Browser Verified in Chrome and Safari but likely affects all.

**Comment by youknowriad** [comment] 2020-12-24 09:37
closing as duplicate of #27249

**Closed by youknowriad** 2020-12-24 09:37 UTC
Labels: [Feature] Patterns, [Type] Bug
