### ISSUE TITLE
Parent Page Drop Down not loading correctly on site with large about of pages.

### ISSUE THREAD

**Issue by randivera** [WordPress/gutenberg#21667] opened 2020-04-16 22:38 UTC
Parent Page Drop Down has duplicates and missing pages on a multiple sites that has 400+ pages. The parent pages load fine in classic editor, but when I disable and use Guttenburg many things are missing and/or duplicated. It appears to be caught is some kind of repeating loop. Perhaps the JSON Response from REST is incorrect. I have no php errors and no javascript errors. I have disabled all plugins. Seems to be a core issue.

Using WordPress version: 5.4
The Screenshot  shows that there is no parent however it is not showing in Guttenburg many duplicated pages and missing page as well.

![Screen Shot 2020-04-16 at 5 33 36 PM](https://user-images.githubusercontent.com/2116941/79513051-85bbea00-8008-11ea-9491-3113f651ea19.png)

![Screen Shot 2020-04-16 at 5 36 30 PM](https://user-images.githubusercontent.com/2116941/79513243-f6630680-8008-11ea-86ba-dd67b12cbcd0.png)

**Comment by talldan** [comment] 2020-04-20 05:00
Duplicate of #12795

**Closed by talldan** 2020-04-20 05:00 UTC
