### ISSUE TITLE
Using the delete key inside the "Rename" modal deletes the current block

### ISSUE THREAD

**Issue by bacoords** [WordPress/gutenberg#61750] opened 2024-05-16 23:20 UTC
### Description

When renaming a block if I hit delete to backspace and change some text, the entire block is deleted.

### Step-by-step reproduction instructions

1. Open the block editor
2. Add a block and rename it in the list view
3. Type a few letters and then hit `delete` to backspace

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/6867360/3daa706c-8651-445c-90fa-cb8a5a7f72df

### Environment info

- Gutenberg 18.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bacoords** [comment] 2024-05-17 14:46
CC @fabiankaegy @colorful-tones  If this is still in trunk, then this is probably something that should be cleaned up before the next release.

**Comment by Mamaduka** [comment] 2024-05-18 10:03
Thanks, @bacoords!

This is a duplicate of #61544 and was fixed via #61583.

**Closed as not planned by Mamaduka** 2024-05-18 10:03 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] List View
