### ISSUE TITLE
List block - Cannot delete last empty list item 

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#12787] opened 2018-12-11 09:06 UTC
**Describe the bug**
I had a list block with an empty item as the last item. When I deleted the item the bullet disappeared. But the `<li></li>` tags didn't. So, after update, the empty item reappeared. 

Workarounds... 
- Use the code editor to remove the empty item.
- Click on the indent/outdent buttons.

**To Reproduce**
1. Create a List block with an empty item
2. Save, view and edit
3. Attempt to delete the empty item using the Delete key
4. The bullet disappears 
5. But switch to ordered and see the empty item reappear.

**Expected behavior**
The empty `<li></li>` should be deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/49789125-1ef73400-fd23-11e8-844e-0b000287024e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 
**Smartphone (please complete the following information):**

**Additional context**
- Gutenberg 4.6.1

**Comment by skorasaurus** [comment] 2018-12-11 13:34
Confirmed this also occurs in WordPress 5.1-alpha-43678

**Comment by chthonic-ds** [comment] 2018-12-23 01:42
Can confirm this happens in WordPress 5.0.2, same desktop specs as OP.

**Comment by kadamwhite** [comment] 2019-01-03 15:59
This also happens in custom blocks when using a multiline `RichText` element:
```
// edit() method:
<RichText
	tagName="ul"
	multiline="li"
	value={ listItems }
	onChange={ listItems => setAttributes( { listItems } ) }
	placeholder={ __( 'Enter text here. Text may contain links.', 'project' ) }
/>

//save() method:
<RichText.Content
	tagName="ul"
	multiline="li"
	value={ listItems }
/>
```

**Comment by youknowriad** [comment] 2019-02-11 07:50
Can't reproduce this anymore. I suspect it was fixed by #13697.

**Closed by youknowriad** 2019-02-11 07:50 UTC
Labels: Needs Testing, [Block] List

**Comment by iseulde** [comment] 2019-02-11 08:44
Thanks for testing!

**Comment by kennethz3** [comment] 2019-04-13 13:02
This issue has appeared again on my site

**Comment by kennethz3** [comment] 2019-04-14 07:48
Scenario to reproduce:

- Classic block before List block in a post
- Classic block containing bullet list, and list block containing a few list items
- Add a new list item at the end of the list in the classic block
- New empty list item appears at the end of the list block

**Comment by timofeycom** [comment] 2019-04-27 20:26
Related issue #14977
