### ISSUE TITLE
Start of week setting isn't being pulled in to Gutenberg editor

### ISSUE THREAD

**Issue by lizkarkoski** [WordPress/gutenberg#9109] opened 2018-08-17 21:36 UTC
**Describe the bug**
In my WordPress settings the start of week setting is set to Monday. This does not get incorporated in to the calendar when using Gutenberg.

Gutenberg 3.6.2

**To Reproduce**
1. Go to Dashboard
2. Click on Settings
3. Scroll down to the bottom of page
4. `Week Starts On` with dropdown selector. 

Next:
1. Edit an existing post or create a new one.
2. From the Document view choose the date link next to Publish.
3. Note that the week starts on Sunday regardless of the settings set above. 

**Expected behavior**
I would expect for the `Week Starts On..` settings to be displayed in the publication date link from Gutenberg. 

General Settings: 
<img width="390" alt="screen shot 2018-08-17 at 5 32 07 pm" src="https://user-images.githubusercontent.com/16867830/44289734-886aa880-a243-11e8-98bc-4713fe18de5d.png">

Gutenberg Calendar display when editing/creating a post:
<img width="351" alt="screen shot 2018-08-17 at 5 33 08 pm" src="https://user-images.githubusercontent.com/16867830/44289757-a506e080-a243-11e8-9fb0-c4794844844a.png">

Note that the classic editor does not give a calendar display option for this. It's a manual entry of the date. 

**Desktop (please complete the following information):**
 - OS: Sierra 
 - Browser Chrome
 - Version 67

There's an additional report of this in the Gutenberg support forums at: 
https://wordpress.org/support/topic/calendar-for-posting-date-starts-week-always-on-sunday/

**Comment by HonkXL** [comment] 2018-08-17 21:41
Can confirm this here. Browser Safari on Mac OS High Sierra.

**Comment by WPprodigy** [comment] 2018-08-26 04:52
Probably worth closing this in favor of #4533, since there are other localization issues at play such as Date Format and Time Format as well.

**Comment by designsimply** [comment] 2018-11-01 22:33
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and Firefox 63.0 on macOS 10.13.6 that if I go to Settings > General and set "Week Starts On" to "Wednesday", that change is not reflected in the editor's date picker under Settings > Document > Status & Visibility > Publish.

![screen shot 2018-11-01 at 4 30 17 pm](https://user-images.githubusercontent.com/1119271/47883704-af248e00-ddf3-11e8-90df-6e6227a79c90.png)

@WPprodigy I think #4533 is about localization but this issue is actually a settings issue so I _think_ it should stay separate.

**Comment by youknowriad** [comment] 2018-11-20 16:07
closed by #11938

**Comment by nellofn** [comment] 2020-09-10 19:37
Can we re-open or triage this one again, please?

The issue with the Calendar date picker is still present if the user's dashboard **Interface language** is set to other than **English**.

**To Reproduce**
Steps to reproduce the behavior:

- Go to Me > [Account Settings](https://wordpress.com/me/account)
- Under "Interface Language", choose Spanish, Italian or other than English
- Save account settings
- Go to WP-Admin > Settings > General
- Scroll down to the bottom of page
- On Week Starts On, choose "Monday" and save the changes

Next:
- Edit an existing post or create a new one.
- From the Document view choose the date link next to Publish.
- Note that the week starts on Sunday regardless of the settings set above (Monday in the example).

**Examples:**

With Language set to Spanish (doesn't honor Week Starts On setting): 
![Markup 2020-09-10 at 14 42 45 (1)](https://user-images.githubusercontent.com/17755234/92792223-5a50e780-f37b-11ea-8861-b2302e2ba14c.png)

With Language set to English (works as expected):
![Markup 2020-09-10 at 14 57 15](https://user-images.githubusercontent.com/17755234/92791959-207fe100-f37b-11ea-86a8-9a55e98285fc.png)


**Expected behavior**
I would expect for the Week Starts On.. settings to be displayed in the publication date link from Gutenberg regardless of the user's Interface language settings. Also, the calendar string does not appear to be translated either.

**Comment by youknowriad** [comment] 2020-09-14 08:07
Reopening so we can test whether it regressed.

**Comment by shohanhossainnab** [comment] 2020-11-18 12:09
The issue still there. Just tested.

**Comment by carinapilar** [comment] 2021-01-12 20:18
I got a new report for this and was able to replicate it, even with the interface in English, and either with the Gutenberg plugin installed or not.

**Comment by paaljoachim** [comment] 2021-02-21 00:43
Testing with WordPress 5.7 beta 3. Gutenberg plugin 10.
Twenty Twenty One.

I went ahead and added Norwegian. 
Set the week to start on a Wednesday.
Went to an existing page. Clicked the date beside Publish, and noticed the calendar start on a Wednesday.
I also deactivated the Gutenberg plugin and received the same results.

<img width="423" alt="Screen Shot 2021-02-21 at 01 39 56" src="https://user-images.githubusercontent.com/5323259/108612116-b8333200-73e5-11eb-8048-c64718dd3d3f.png">

Went back to Settings -> general and changed back to Monday.
Refreshed the Gutenberg page and noticed the calendar changed to Monday.

It looks like this issue is fixed, and I will go ahead and close it.
If I am mistaken we can of course reopen.
Thanks.

**Closed by paaljoachim** 2021-02-21 00:43 UTC
Labels: [Feature] Document Settings, [Type] Bug
