### ISSUE TITLE
Feature Request: Technical or Documentation Support for "Hero" or "Cover Block" Header Patterns

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#24634] opened 2020-08-18 22:01 UTC
This feature request, related to block patterns, template parts, and block-based-theming may not require a technical solution. Here are the options I see as possible solutions …

1. A technical block-level solution.
2. Documentation in a handbook for this scenario as a "you might try this!" sort of thing. (For now.)
3. Accounting for user flows in the Site Editor and Post/Page Editors.

Here's the feature request. Support for the following "Header Pattern".

![image](https://user-images.githubusercontent.com/545779/90568988-a2149280-e172-11ea-99d4-28f7b777d653.png)

- On the left is the front page of a WordPress site loading a header-front-page.html template part. - On the right is a page on that site loading a header-page.html template part.
- Peeking over the edge of the page on the right is my text editor with the theme structure supporting that. I thought it'd be useful.

Everything with a blue background is the "header". Here are some perhaps unusual features of these template parts.

Both of these template parts use cover blocks. Here's a screenshot of one with the Detective Wapuu extension doing it's thing.

![image](https://user-images.githubusercontent.com/545779/90569237-1a7b5380-e173-11ea-9cb7-b336b43a5910.png)

It's becoming more and more common to see Header Patterns like this. With what we think of as the Header of a site over top of a "hero section" that feels like "part of the page." It's especially common to see this pattern with an image or even a video in the background.

Here's a picture with a picture.

![image](https://user-images.githubusercontent.com/545779/90574118-bf9b2980-e17d-11ea-8427-096690378080.png)

Also perhaps somewhat unusual, in the page on the right. The header template part has the post title inside the header, not the page content. I could envision scenarios where this might seem strange for a user.

Why? This was the only way I could _currently_ think of to achieve this type of header pattern with a block-based theme. Which leads me to my list at the start of this issue.

1. Should there be some sort of technical block-level solution for this type of pattern?
2. If not, should there be documentation in a handbook for this scenario as a "you might try this!" sort of thing. (For now.)
3. Either way we should perhaps make sure there is an accounting for user flows around this in the Site Editor and Post/Page Editors.

Possibly related issue: https://github.com/WordPress/gutenberg/issues/16281

**Comment by DaisyOlsen** [comment] 2022-11-09 19:11
@ianstewart It's been a minute or two since you posted this idea. Do you think it would still be necessary to document this specifically? It seemed pretty simple to create this in a template part with minimal fuss at this point with all the improvements since the time this issue was opened.

**Comment by DaisyOlsen** [comment] 2022-11-09 22:38
Confirmed with @ianstewart that it's fine to close this.

**Closed by DaisyOlsen** 2022-11-09 22:38 UTC
Labels: [Type] Developer Documentation, [Feature] Themes, [Feature] Full Site Editing
