### ISSUE TITLE
Navigation block: can't unlink items

### ISSUE THREAD

**Issue by sophiegyo** [WordPress/gutenberg#18866] opened 2019-12-02 11:16 UTC
After creating a navigation block and adding a few items, it doesn't seem possible to un-link them.

Gutenberg version tested: 7.0.0

**To reproduce**
1. Add a new page, and add a navigation block
2. Add a few items to the block, making sure they're linked pages
3. Save/publish the page
4. Attempt to unlink an item by modifying it and deleting the listed page
5. Notice appears to fill in the field. Clicking away from the field closes it and loses the modification (removal)

**Expected behavior**
I would have expected to be able to modify the link, to prevent the link from being active!

**Screenshots**

Chrome:
![navblockunlink](https://user-images.githubusercontent.com/36608681/69954820-85f59600-14fc-11ea-813a-b05643a77d08.gif)

Firefox:
![navblockff](https://user-images.githubusercontent.com/36608681/69955106-306db900-14fd-11ea-8e96-003a9cc31d3d.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome 78.0.3904.108, also tested on Firefox 70.0.1

I've not yet tested on a smartphone!

**Comment by karmatosed** [comment] 2019-12-02 11:17
I can confirm I also am unable to remove a link once added. Thanks for finding this @sophiegyo.

**Comment by obenland** [comment] 2019-12-03 18:26
Currently the navigation block only allows (navigation) links as child blocks. There has been some exploration in #18442 to allow non-linked links, but I'm not sure that'll be viable. The idea here is that other types of blocks (like a text block in this case) could be added later, to enable a way to create richer navigation menus.

Rather than considering this a bug, I'd advocate for adding the ability to accept other types of child blocks.

/cc @mtias

**Comment by sophiegyo** [comment] 2019-12-09 06:53
Is that still the case for top-level items?  The Firefox screencast I linked shows me trying to unlink a top-level navigation item, rather than a child item.

**Comment by paaljoachim** [comment] 2021-04-08 19:23
Testing using WordPress 5.7. Twenty Twenty One. Gutenberg plugin 10.3.2

Clicking a link and removing the url. Then clicking outside of the link control box automatically adds the link back in again.
So yes one can not unlink items. Either one changes the link or one deletes the link.  (There still needs to be a way to add text into the menu.)

**Comment by gwwar** [comment] 2021-04-08 19:28
I agree that it'd be good to allow folks to add text headings to help group navigation links. I do think we could let folks add this more directly, vs adding a link and then removing the url. For example in the inserter we might let folks pick adding a heading.

Were there any thoughts on this already? cc @jasmussen or @scruffian 

 As a quick example Amazon does the following, to group links together. Notice how "Trending" isn't a  link

<img width="341" alt="Screen Shot 2021-04-08 at 12 23 31 PM" src="https://user-images.githubusercontent.com/1270189/114085107-c5a55e00-9865-11eb-897e-490749666101.png">

**Comment by shaunandrews** [comment] 2021-04-08 20:05
What purpose does "unlinking" a Link block serve?

As I see it, the Link block (and its variations) requires a URL to do its job. Once set, there's no way to remove a URL, only change it. This is intentional, and I'm not sure we should build a way to "unset" a Link block's URL without some greater purpose or workflow.

**Comment by jasmussen** [comment] 2021-04-09 05:43
A few things have changed since this ticket was created, here's a fresh look:

![current status](https://user-images.githubusercontent.com/1204802/114133547-82e79280-9906-11eb-9f30-9d69479cc689.gif)

Notably, there's a new menu item placeholder state which does not allow you to edit a label until a link has been added. By adding this we're implicitly saying: a menu item without a link is useless. In that vein, unlinking a menu item isn't directly useful anymore. However we can be clearer about the user experience. While the "The field must be filled out" is a good start, the messaging around it can be improved. I don't know if that has to be this ticket or a separate URL component-specific one.

The second part, being able to add text to a menu, that absolutely should be possible. A brief (and intentionally crazy) [exploration](https://github.com/WordPress/gutenberg/issues/23745#issuecomment-813965553) suggests that's not going to be too hard. The biggest challenge for that is [this ticket](https://github.com/WordPress/gutenberg/issues/29036). I'm tinkering with a mockup ([wip](https://user-images.githubusercontent.com/1204802/114133993-3781b400-9907-11eb-8f4e-39063c73d5ed.png)) that relies on being able to add single paragraphs, so it's definitely something we want.

**Comment by tellthemachines** [comment] 2021-07-08 04:43
Now that #29036 has been resolved, would this issue be fixed if we allowed adding Paragraph blocks at the top level of the Navigation block? If so, that's easy to sort out 🙂

**Comment by jasmussen** [comment] 2021-07-08 09:18
Good thought @tellthemachines. If not the paragraph, then at least a range of other blocks would bring value, so I created #33278 to track that. 

If we were to allow the Paragraph block, would that change the default behavior of the appender? I'd think we'd still want the black plus being the only way to add items, rather than having an input field with a slash command prompt.

**Comment by tellthemachines** [comment] 2021-07-09 04:38
> If we were to allow the Paragraph block, would that change the default behavior of the appender? I'd think we'd still want the black plus being the only way to add items, rather than having an input field with a slash command prompt.

We'd have to look into it, though I'm starting to think using Paragraph might not be a good idea, for multiple reasons outlined [here](https://github.com/WordPress/gutenberg/issues/33278#issuecomment-876884199).

**Comment by getdave** [comment] 2021-07-30 08:41
Just to say that we have [added an `Unlink` behaviour in the Post Editor](https://github.com/WordPress/gutenberg/pull/32541). I can add this to the Nav Editor as well.

Update: PR to implement this now ready for review in https://github.com/WordPress/gutenberg/pull/33777

**Comment by draganescu** [comment] 2021-08-04 08:13
Closed by #33777

**Comment by getdave** [comment] 2021-08-04 08:17
@draganescu Worth noting that we may need to create a follow up to address another part of this Issue which is that folks want to be able to create link items which have no hyperlink. I believe this is what @tellthemachines is addressing in https://github.com/WordPress/gutenberg/pull/33775

**Comment by jasmussen** [comment] 2021-08-04 08:27
#33091 would also be related to link items with no link, insofar as that ticket can only be addressed if we were to allow that.

**Comment by tellthemachines** [comment] 2021-08-30 06:08
Hm, I think this was mistakenly closed; it's not possible to create navigation items that render on the front end without links yet.

**Closed** 2021-09-13 01:18 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Navigation, [Feature] Link Editing
