### ISSUE TITLE
ESLint does not accept spaces in the path?

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42588] opened 2022-07-21 08:07 UTC
### Description

I am using _Local_ and the path to where I placed Gutenberg is:
`/Users/carolina/Local Sites/60/app/public/wp-content/plugins/gutenberg-git`

Using the _GitHub Desktop app_ to submit an update to a branch with a pull request, I received this error:

```

✖ wp-scripts format found some errors. Please fix them and try committing again.

[error] No files matching the pattern were found: "/Users/carolina/Local".
[error] No files matching the pattern were found: "Sites/60/app/public/wp-content/plugins/gutenberg-git/packages/block-library/src/post-navigation-link/edit.js".



✖ wp-scripts lint-js found some errors. Please fix them and try committing again.
  
  
Oops! Something went wrong! :(

ESLint: 8.3.0

No files matching the pattern "/Users/carolina/Local" were found.
Please check for typing mistakes in the pattern.
husky - pre-commit hook exited with code 1 (error)

```

It seems to be splitting Local and Sites?

### Step-by-step reproduction instructions

1. Set up Local for WordPress development **with their default folder names**
2. Clone Gutenberg into the plugin directory
3. Checkout the branch you are working on.
4. Make your changes and try to commit them to the branch.

### Screenshots, screen recording, code snippet

![Screen Shot 2022-07-21 at 09 53 53](https://user-images.githubusercontent.com/7422055/180162249-b71e95af-5102-4c07-b9af-252b38d1790d.png)

### Environment info

Local, version 6.4.1+5978
Mac OS 12.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-07-24 14:03
I also tested it and reproduced it when the directory contains spaces.
This same problem has been reported on ESLint and still seems to be unresolved.

https://github.com/eslint/eslint/issues/14025

It might be good to leave this issue open in the hope that it will be fixed by the library.

**Comment by ndiego** [comment] 2022-08-06 14:26
I have also been running into this. Very frustrating. @carolinan have you found a reliable workaround? I am just renaming the folder, committing, and then reverting the name. Not ideal 😅

**Comment by carolinan** [comment] 2022-08-07 12:59
I renamed the folder permanently.

**Closed as completed** 2024-05-22 04:51 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Tool] ESLint plugin
