### ISSUE TITLE
Editor jumps when selecting long block

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/gutenberg#20111] opened 2020-02-07 22:56 UTC
Hey,

I have a pretty long block with InnerBlocks inside of it. When I jump from editing the InnerBlocks to the actual block, the editor jumps to the bottom of it. Is that normal behaviour?

See this gif:
![giphy (7)](https://user-images.githubusercontent.com/39319746/74071997-bcbcc080-4a05-11ea-88b6-e25295474aa7.gif)

**Comment by talldan** [comment] 2020-02-19 06:07
I can reproduce this using the group block with lots of content inside it. I also set a background color and full width alignment to make the group block easier to select. Clicking on the block causes the page to scroll to the bottom of the block.

**Comment by iandunn** [comment] 2020-02-19 21:02
I've been experiencing this too, and find it really frustrating.

Possible related/duplicate issue: https://github.com/WordPress/gutenberg/issues/2514

**Comment by gigatyrant** [comment] 2020-04-03 09:45
I have the same problem in WP 5.4 when I select long blocks.

It's very frustrating. Any news ?

**Comment by Triggsy22** [comment] 2020-04-03 13:39
Same Problem here. In WP 5.4.
In our Business we often use very big Blocks and this Bug is so annoying, that we decided to not update the Websites of our Customers to 5.4

Its now two Months since this Bug is reported.
Does someone knew a possibility to remove this jump Action?

Just Info for easy reproduction:
- New Wordpress Site
- Put a simple Paragraph Block on a Site
- Write into this Paragraph Block realy much Text, like youre Terms of Service
- Deselect this Block
- Click at the beginning of the Text inside the Block.
- Now youre Browser scrolls to the bottom of youre Block.
- And you have to scroll up again, to edit the text at the position you wanted.

**Comment by Log1x** [comment] 2020-04-06 21:16
I hate to be an echo but I am also experiencing this issue on 5.4 (and/or using the plugin) and as others have said, it is incredibly frustrating. 

Some additional attention to this issue would be greatly appreciated.

**Comment by talldan** [comment] 2020-04-07 00:51
It looks like this was originally reported in #19682, so I'll close this as a duplicate.

**Closed by talldan** 2020-04-07 00:51 UTC
Labels: [Type] Bug
