### ISSUE TITLE
Post Updated message is showing multiple times

### ISSUE THREAD

**Issue by avinapatel** [WordPress/gutenberg#1697] opened 2017-07-04 11:52 UTC
"Post Updated!" a message is showing multiple times when we update
![gutenberg-multiple-time-message-issue](https://user-images.githubusercontent.com/27285861/27829003-e79b59a2-60dc-11e7-9510-09baf737fb01.png)
 a post.

**Comment by swissspidy** [comment] 2017-07-04 11:55
Duplicate of #1604.

**Closed by swissspidy** 2017-07-04 11:55 UTC
