### ISSUE TITLE
Site Editor Styles Theme Gradients are missing Previews

### ISSUE THREAD

**Issue by beatricekulcsar** [WordPress/gutenberg#36717] opened 2021-11-22 08:56 UTC
### Description

When trying to pick a theme gradient in the site editor the theme gradients are missing previews.

### Step-by-step reproduction instructions

1. click on styles
2. click on colors
3. click on background
4. click on gradient

### Screenshots, screen recording, code snippet

<img width="279" alt="Bildschirmfoto 2021-11-22 um 09 53 01" src="https://user-images.githubusercontent.com/71608597/142831494-43f62200-7f0c-46ba-a912-5c507fdfaa5e.png">

### Environment info

WordPress Version 5.8.2
Gutenberg Version 11.9.1
Active Theme: TT1 Blocks (tt1-blocks), Version 0.4.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2021-11-23 12:14
Hi, I am closing this as a duplicate of: https://github.com/WordPress/gutenberg/issues/30642

**Closed as completed by carolinan** 2021-11-23 12:14 UTC
Labels: [Status] Duplicate, [Feature] Site Editor, [Feature] Colors
