### ISSUE TITLE
Post update doesn't fail cleanly when ACF fields are invalid

### ISSUE THREAD

**Issue by TobyWilkes** [WordPress/gutenberg#10284] opened 2018-10-02 03:11 UTC
**Describe the bug**
When saving a post using gutenberg which has custom fields, or some other field requiring validation, if the validation fails the request to "_wp-admin/post.php_" will return 500. However the UI will remain locked in "saving", making it impossible to update the contents or retry saving any further.

Further, a "Post updated!" notification appears, even though the post update has failed.

**To Reproduce**
1. Go to 'Edit Post' on a site with _required_ custom fields.
2. Leave some of the fields empty
3. Press 'Update'
4. See incorrect "Post updated!" notice and be locked in "Updating..." state forever.

**Expected behavior**
When the request to "post.php" fails, some error should be displayed at best. At worst the UI should fall out of the "Updating..." state and allow the user to edit the contents again and retry updating.

The UI reads "Post Updated!" even though it is not. This shouldn't be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9653724/46327002-6fbf2200-c63a-11e8-8590-ecdf5ae0b926.png)
![image](https://user-images.githubusercontent.com/9653724/46327052-a1d08400-c63a-11e8-9467-4adb501be98e.png)
(erroneous 'Post Updated!' notification and locked 'Saving...' state) 

**Desktop:**
 - OS: MacOS High Sierra
 - Browser: Firefox
 - Version: 62.0.2 

**Additional context**
- Gutenberg 3.8

**Comment by designsimply** [comment] 2018-10-02 21:18
Hi! I think this is a duplicate of #9699. Please have a look and if it's not the same please reply here.

**Closed by designsimply** 2018-10-02 21:18 UTC
Labels: Needs Testing, [Type] Plugin / Theme Interoperability
