### ISSUE TITLE
Dropzone indicator doesn't disappear when dragging files or HTML from outside the window and pressing Escape

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#26013] opened 2020-10-12 05:39 UTC
The blue dropzone indicator doesn't disappear when dragging files or HTML from outside the window and pressing Escape

#25986 adds handling for cancelled drag events using the `dragend` event. Unfortunately `dragend` only fires when the source of the drag originates from inside the document, which mostly affects files since they're dragged from outside the document (in most cases I can think of).

`keyup` also can't be used as the window isn't actively focused when dragging from outside, so `keyup` doesn't fire.

Potentially `dragleave` is an option, though this seems a little complicated to implement.

**To reproduce**
**Files**
1. Drag a file into the editor canvas from finder or windows explorer
2. Drop indicators should be displayed
3. Press escape
4. Observe the blue drop indicator is still displayed

**HTML**
1. Drag HTML into the editor canvas from another browser window (usually the easiest way to do this is to drag a link from one window into another).
2. Drop indicators should be displayed
3. Press escape
4. Observe the blue drop indicator is still displayed

**Expected behavior**
The drag event should be cancelled and the drop indicators shouldn't be displayed.

**Comment by gwwar** [comment] 2021-03-11 20:00
I'm still seeing this one in Gutenberg 10.2 

Here's a video example, using an image dropzone for emphasis:

https://user-images.githubusercontent.com/1270189/110847039-48d09580-8261-11eb-91e2-28255359e81a.mp4

**Comment by Mamaduka** [comment] 2022-05-16 11:35
I'm no longer able to reproduce this issue. Not sure if it was fixed with recent Dropzone rewrite - #30310.

**Comment by kevin940726** [comment] 2022-09-30 02:36
I can't reproduce this either and I believe it's fixed in #30310. It looks like the `dragend` event won't be dispatched if we're dragging from outside the current window. However, it will dispatch a `dragleave` event on the drop zone, which we can use to indicate that the dragging is finished. This only accidentally fixed the issue though because we won't fire `onDragEnd` in `useDropZone` in that case, not until the user moves the mouse and triggers the `mousemove` event.

**Comment by Mamaduka** [comment] 2023-07-11 19:03
@kevin940726, can we close this issue?

**Comment by ellatrix** [comment] 2024-07-11 09:30
Can this be closed?

**Closed** 2024-07-12 03:15 UTC
Labels: [Type] Bug, [Feature] Drag and Drop, [Package] Components
