### ISSUE TITLE
Font Library: Allow the deletion of a single font face

### ISSUE THREAD

**Issue by akasunil** [WordPress/gutenberg#63753] opened 2024-07-19 14:08 UTC
### Description

Currently, In font library, when we try to delete single font face from custom installed fonts from google, it remove whole font family containing other font faces. We should allow user to only remove selected font face from library, same as we allow theme to installed selected font faces. Currently implementation is bit confusing from user point of view. 

### Step-by-step reproduction instructions

- Go to typography setting under global styles
- Open font library
- Add font from google
- Go to newly installed font
- Select one font face and delete it
- Whole font family gets removed

### Screenshots, screen recording, code snippet

[Blog-Home-‹-Template-‹-gutenber-‹-Editor-—-WordPress (1).webm](https://github.com/user-attachments/assets/3f6d03b2-b0e5-42ed-846a-b24361208463)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ndiego** [comment] 2024-07-19 17:08
Thanks for reporting @akasunil. I just tested and confirmed. 

That said, I do not think this is a bug. The "Delete" button is intended to delete the entire font family. If you want to just disable a few of the variants, you can uncheck them and click the "Update" button. It is a bit confusing.

As an enhancement, it might be nice if you could delete individual variants, but that is not currently possible. I have removed the `bug` label for now, but perhaps you can update this issue to be a feature request to add this enhancement or make the button more clear? Otherwise, we can close it.

**Comment by akasunil** [comment] 2024-07-20 05:42
Isn't it bit confusing from user point of view, that we allow user to install individual font faces, but when it comes to delete, whole font family will be deleted?  I know we have message on confirm dialog of delete action, but still i think we should allow to delete single font face. 





> perhaps you can update this issue to be a feature request to add this enhancement or make the button more clear?

Sure, I'll update the issue.

**Comment by ndiego** [comment] 2024-07-20 13:32
> Isn't it bit confusing from user point of view

Yeah, it's definitely confusing.

**Comment by annezazu** [comment] 2024-07-23 18:40
Thanks for opening this! However, this is a duplicate: https://github.com/WordPress/gutenberg/issues/55176 Going to close this out as a result and encourage you to comment on the original issue.

**Closed as completed by annezazu** 2024-07-23 18:40 UTC
Labels: [Type] Enhancement, [Feature] Font Library
