### ISSUE TITLE
Site Editor: Export template/parts markup made in the site editor UI to html files

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#42609] opened 2022-07-21 19:10 UTC
Frustrating to lose work if you click on clear customization accidently.

Current solution:  Copy and paste code from site editor to html files when changes made but is very tedious. 

### Proposed Solution

**Click save:**

![image](https://user-images.githubusercontent.com/10998875/180293921-4fb25877-e20a-4d59-aba8-73cc5752588b.png)

**Markup is exported to html file:**

![image](https://user-images.githubusercontent.com/10998875/180294354-6a907ef4-9b4d-4f78-88fb-2ee91db0e4e3.png)

Drawbacks, will overwrite original template/parts. Maybe a option for DEV mode, which allows overwriting but regular users will keep current workflow and eventually revisions will be available https://github.com/WordPress/gutenberg/issues/36060

Or maybe instead of overwriting we can have it like the site editor ui where multiple versions(customizations) are created except in this case would be multiple html files.

**Comment by carolinan** [comment] 2022-07-22 10:59
Hi!
I'm sorry but I did not understand the last paragraph.

Did you mean, that you want an option to use the Site Export functionality in the Site editor to only export templates and parts, not the whole theme?

[Theme developer handbook: Site Editor export](https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor/#block-272728d5-633a-4b12-87d2-d058a021dc6b)

**Comment by LukaszJaro** [comment] 2022-07-22 15:48
Hi @carolinan 

I want the process to be automated when clicking 'save' and only export the template and template parts to my current working directory. So not exactly the way the site export functionality works, I don't want a zip file created but instead write it to my current working directory i.e., templates or parts.

For example:
```
function export_templates()
{
	$path =  'mytheme/templates/get-the-current-template.html';
        $data = 'site editor template markup'; i.e., <!-- wp:template-part {"slug":"header","theme":"pii"...

    file_put_contents($path, $data);
}
add_action('save_post', 'export_templates');
```

**Comment by carolinan** [comment] 2022-07-22 16:42
OK. This was attempted, and you can read about why it was not added here: https://github.com/WordPress/gutenberg/issues/39194#issuecomment-1138294471


I will close this as a duplicate of #39194. Further discussion can continue in the original issue.

**Closed as completed by carolinan** 2022-07-22 16:42 UTC
Labels: [Status] Duplicate, [Feature] Site Editor
