### ISSUE TITLE
JS Warning when inserting image: Received `false` for a non-boolean attribute `placeholder`.

### ISSUE THREAD

**Issue by marcusig** [WordPress/gutenberg#8137] opened 2018-07-23 11:59 UTC
**Describe the bug**

```
Warning: Received `false` for a non-boolean attribute `placeholder`.

If you want to write it to the DOM, pass a string instead: placeholder="false" or placeholder={value.toString()}.

If you used to conditionally omit it with placeholder={condition && value}, pass placeholder={condition ? value : undefined} instead.
    in input
    in div (created by De)
    in div (created by De)
    in De
    in Unknown (created by WithInstanceId(Component))
    in WithInstanceId(Component) (created by t)
    in div (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by InspectorControlsSlot)
    in InspectorControlsSlot
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component) (created by nt)
    in div (created by t)
    in t (created by nt)
    in div (created by to)
    in to (created by nt)
    in div
    in div (created by t)
    in t (created by SidebarSlot)
    in SidebarSlot
    in div
...
```

**To Reproduce**
1. Open the console
2. Add an image block
3. Select / upload an image
4. The warning is shown when inserting the image.

**Comment by youknowriad** [comment] 2019-02-08 14:00
I can't reproduce this. Closing.

**Closed by youknowriad** 2019-02-08 14:00 UTC
Labels: Blocks, Needs Testing
