### ISSUE TITLE
Caret is oddly positioned (to the left) when undoing in Firefox

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#9400] opened 2018-08-28 15:01 UTC
**Describe the bug**
When undoing a paragraph, the caret position shifts outside the block inserter and goes all the way to the left.

**To Reproduce**
1. Add a new page
2. Click on the block inserter
3. Type a paragraph
4. Press "Enter"
5. Type another paragraph
6. Press "Enter"
7. Type *another* paragraph
8. Press <kbd>Command</kbd>+<kbd>Z</kbd> (<kbd>Control</kbd>+<kbd>Z</kbd> on Windows/Linux)
9. Press <kbd>Command</kbd>+<kbd>Z</kbd> (<kbd>Control</kbd>+<kbd>Z</kbd> on Windows/Linux) again

Observe the caret position; it's all the way to the left.

**Expected behavior**
Caret is in the previous block.

**Screenshots**
![2018-08-28 15 55 46](https://user-images.githubusercontent.com/90871/44731684-a5249d00-aadb-11e8-97cf-da7e002bc565.gif)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra (`10.13.6 (17G65)`)
 - Browser: Firefox Developer Edition
 - Version: `62.0b20 (64-bit)`

**Additional context**
- Latest `master`

**Comment by skorasaurus** [comment] 2018-11-23 18:03
I can confirm this behavior on Gutenberg 4.5.1; wordpress 4.9.8; firefox 63 (on ubuntu 16.04)

**Comment by iseulde** [comment] 2018-11-27 07:55
Related: #12002.

**Comment by iseulde** [comment] 2018-11-27 07:57
Confirmed. Setting the selection back still needs to be implemented though. Sounds like a glitch in Firefox when a focussed element suddenly disappears.

**Comment by iseulde** [comment] 2019-02-11 09:37
I can no longer reproduce this issue with master. Probably fixed by #13697. Could someone confirm?

**Comment by youknowriad** [comment] 2019-03-07 12:21
yes, I can't reproduce, the caret disappears for me entirely. I guess this is part of a more global issue related to the persistence of the selection in state.

**Closed by youknowriad** 2019-03-07 12:21 UTC
Labels: Browser Issues, Input Interaction, [Component] Rich Text, [Status] Needs More Info, [Type] Bug
