### ISSUE TITLE
13.2 breaks Query Loop taxonomy filters (on front end)

### ISSUE THREAD

**Issue by andrewstaffell** [WordPress/gutenberg#41067] opened 2022-05-14 07:15 UTC
### Description

Between 13.1 and 13.2 the category / tag / taxonomy filters for Query Loop stop having an effect on the front end. I tried to see what was causing it in the [diff](https://github.com/WordPress/gutenberg/compare/v13.1.0...v13.2.0) but can't work it out. However, I added logging to a function hooked to `pre_get_posts` and it is not being called at all in 13.2. Verified in both local and server environments. 

The issue doesn't affect the editor. Just front end. 

### Step-by-step reproduction instructions

1. Install Gutenberg 13.1.
2. Set up a Query Loop block and choose a Category from Filters in the block sidebar. 
3. Verify that on front end the Category filter is being applied correctly. 
4. Update Gutenberg to 13.2.
5. Check same page. Filters no longer apply. Query Loop just shows all posts chronologically. 

### Before (13.1)
<img width="1056" alt="Screenshot 2022-05-14 at 09 11 05" src="https://user-images.githubusercontent.com/696154/168415211-f32554aa-c400-4162-9ca8-00422522e961.png">

### After (13.2)
<img width="1077" alt="Screenshot 2022-05-14 at 09 12 43" src="https://user-images.githubusercontent.com/696154/168415266-a2386c03-e223-431f-a544-110e9d12385b.png">

### Environment info

WP 5.9, Gutenberg 13.2 (but not 13.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by poof86** [comment] 2022-05-16 21:15
I can confirm that category filters do not work front-end in version 13.2
Is there a quick fix I can apply without going back to 13.1?

**Comment by Diachrony** [comment] 2022-05-17 20:17
Also can confirm this issue. Would love a fix or work-around asap as my site is completely broken without this functionality.

**Comment by ntsekouras** [comment] 2022-05-18 06:31
If you create a new Query Loop filter with `category` filters in `13.2`, does it work for you? For me it does, but will investigate more.

----
--**edit**

I just tried having a Query Loop from 13.1 and then in 13.2, everything seemed to worked fine as well. 🤔 

Can you share more info about your setup or more details in general?

**Comment by andrewstaffell** [comment] 2022-05-18 07:07
@ntsekouras: The filters work fine in the block editor, but have stopped working on the front-end (where I understand they are using `gutenberg_build_query_vars_from_query_block()` via  `gutenberg_render_block_core_post_template()` although I can't see any changes to those in the 13.2 diff). 
Nothing special about the setup, it arose in a project with custom theme + plugins but then I tested with Twenty Twenty Two and no plugins (WP 5.9.3). 
Multiple people reporting the same issue and it's just been reported in the Calypso repo too.

**Comment by Diachrony** [comment] 2022-05-18 07:24
@ntsekouras I have a fairly simple, non-custom set-up using the block editor on Twenty Twenty-Two. I have tried creating a new post draft with a standard query and it also fails to do any requested filtering in the preview (like other 3 other published pages I have that use queries), however the editing page shows the expected proper filtering. 
WordPress version 5.9.3
Current theme: Twenty Twenty-Two (version 1.0.1-wpcom)
Forminator (version 1.15.12)
PHP version 7.4.29

**Comment by ntsekouras** [comment] 2022-05-18 07:35
>The filters work fine in the block editor, but have stopped working on the front-end

I know, I tested that.

@andrewstaffell and @Diachrony do you experience the problem through `Calypso`? Because you both mention it. I'm testing with core.

**Comment by Diachrony** [comment] 2022-05-18 07:41
@ntsekouras I'm sorry. I'm not sure about Calypso. Where can I look to find whether it is being used. It is not anything I intentionally installed but may be there by default? 

edit: it may have been @alliebbush2 that mentioned it above?

**Comment by andrewstaffell** [comment] 2022-05-18 07:47
@ntsekouras I'm using Core too. WP 5.9.3.

**Comment by poof86** [comment] 2022-05-18 07:49
Wordpress.org 5.9.3 on server here with Gutenberg installed and updated from Wordpress plugin page

**Comment by ntsekouras** [comment] 2022-05-18 08:05
I mean if your sites are in WordPress.com. If yes they will be using Calypso.

@Diachrony your mention was implicit through:
>Current theme: Twenty Twenty-Two (version 1.0.1-wpcom)

**Comment by andrewstaffell** [comment] 2022-05-18 08:05
@ntsekouras I'm using .org. Bug reproduced locally and in server environment.

**Comment by youknowriad** [comment] 2022-05-18 09:15
I'm following the instructions above, and I was not able to reproduce either 🤔 There must be another parameter in the equation.

**Comment by Diachrony** [comment] 2022-05-18 09:24
![image](https://user-images.githubusercontent.com/20742820/169005554-bcbc4d5e-70ea-41e4-8df1-a8c40df6b0a1.png)

Plugins and their versions if that helps. Let me know if you can think of any other info that I can grab for you and I'll send what I can tomorrow. Really appreciate your work on this!

**Comment by ntsekouras** [comment] 2022-05-18 09:34
Thanks for all the info @Diachrony! I could reproduce in `.com` (that's your case), but we are trying to reproduce in core.

**Comment by andrewstaffell** [comment] 2022-05-18 09:43
@youknowriad I completely removed and redid the block with 13.2.1 installed and it now seems to be working OK here. I need to test this out on the production environment where the bug first arose, but in the meantime I wanted to share something I've spotted in the source code of one of the intermediate revisions, which is that both `category` and `categoryIDs` were set in the attributes at some point:

```
<!-- wp:query {"queryId":44,"query":{"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"perPage":8,"taxQuery":{"category":[16]},"categoryIds":[16]},"displayLayout":{"type":"list"},"align":"wide"} -->
```

I think one of these is an older format but it's strange they were both showing up in the same revision? Possible issue with block migration code?

**Comment by youknowriad** [comment] 2022-05-18 09:46
> I think one of these is an older format but it's strange they were both showing up in the same revision? Possible issue with block migration code?

Yes, that's a possibility, it would be good to have the "old" markup (before the upgrade) that failed to try with.

**Comment by andrewstaffell** [comment] 2022-05-18 10:06
Still failing for me in production in 13.2.0 or 13.2.1 (but fine in 13.1). Example markup that's failing:
```
<!-- wp:query {"queryId":2,"query":{"perPage":2,"pages":0,"offset":"0","postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false,"taxQuery":{"category":[6]}},"displayLayout":{"type":"flex","columns":2},"align":"full","className":"is-style-default","layout":{"contentSize":"70rem"}} -->
```

**Comment by chad1008** [comment] 2022-05-18 19:36
I've been testing this today both locally and on WordPress.com and I'm also not able to reproduce. Clearly there's something going on, but there's some obscure variable preventing some of us from seeing it.

Even copypastaing @andrewstaffell's provided markup renders as expected for me! Not sure what's triggering it for some sites/users but not others 🤔 

Tested with Chrome 101.0.4951.64. Unable to reproduce on either a WordPress.com site, or locally running WordPress 5.9.3 and Gutenberg 13.0, 13.1, or 13.2.1

**Comment by chad1008** [comment] 2022-05-18 19:47
I won't repeat the full [comment](https://github.com/WordPress/gutenberg/issues/41135#issuecomment-1130468911) from the other issue, but I do find myself wondering if there might be a link between this issue and https://github.com/WordPress/gutenberg/issues/41135. They seem to have a lot in common 🤔

**Comment by Diachrony** [comment] 2022-05-18 20:20
@chad1008 
>wondering if there might be a link between this issue and #41135. 

I don't normally show "Author name" on my posts, but I just added into a test query and you are correct. The author name does not seem to show in the preview page
![image](https://user-images.githubusercontent.com/20742820/169148845-f87e6324-c1a2-4ef7-ac18-ee1b04fafc7c.png)

**Comment by andrewstaffell** [comment] 2022-05-18 21:12
Post Author Name block is showing empty for me too (on front). Whether in Query Loop or directly in Post Content.

Note my first comment above, that it appears the `pre_get_posts` hook is not being executed by the query loop when it fails. If I restore 13.1 the logging in that hook reappears.

It’s an odd one for sure…

**Comment by ironprogrammer** [comment] 2022-05-18 21:28
## Reproduction Report

### Environment
- OS: macOS 12.3.1
- Web Server: Nginx
- PHP: 7.4.29
- WordPress: 5.9.3 (tested with clean install and after `wp db reset` on a pre-existing install)
- Browser: Safari 15.4, Google Chrome 101.0.4951.64
- Theme: Twenty Twenty-Two, Twenty Twenty-One
- Active Plugins:
  - Gutenberg 13.1.0, 13.2.0, 13.2.1

### Steps to Reproduce
1. **Prerequisites:** Install/enable Gutenberg 13.1.0. Create at least two categories, and then multiple posts using one of those categories. This is required to filter the Query Loop block. (E.g. `wp post generate --count=10` is helpful toward this.)
2. Create a new post and add a Query Loop block. Click the **Choose** button and accept the default loop template.
3. In the block sidebar, under *Filters* in the *Categories* box, type and select one of the categories created in Step 1. You may need to re-select the Query Loop wrapping block, such as through the List View sidebar (<kbd>Ctrl-Opt-O</kbd> on macOS).
4. After category selection, the backend editor will refresh and display the filtered results.
5. Publish post, and open frontend page in a new tab/window.
6. Observe that the query displays posts filtered by the chosen category.
7. Upgrade Gutenberg to 13.2.0 (or 13.2.1). (E.g `wp plugin update gutenberg --version=13.2.0`.)
8. Refresh the frontend page.
9. 🐛 Observe that the posts are no longer filtered by category.

### Reproduction Results
- ✅ [Reported issue](#issue-1235900033) was reproducible.

### Screenshots (from TT2)
\*Note that even-numbered posts have test filter applied.
| | |
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/824344/169156986-1651e2e8-fdf7-4227-9c98-d510a67d6695.png"><br>Gutenberg 13.1.0 | <img src="https://user-images.githubusercontent.com/824344/169156996-3ceee610-7f7a-4b9e-9d29-cefa0cd38839.png"><br>Gutenberg 13.2.0 |

**Comment by andrewstaffell** [comment] 2022-05-19 17:02
Apparently fixed by https://github.com/WordPress/gutenberg/pull/41122 (not yet tested by me, but according to https://github.com/WordPress/gutenberg/issues/41135)

**Comment by ironprogrammer** [comment] 2022-05-19 17:42
Just confirming here for additional consensus 👍🏻

After testing `gutenberg:trunk` following [PR 41122 merge](https://github.com/WordPress/gutenberg/pull/41122), this has resolved the [reported issue](#issue-1235900033).

## Test Report
Patch: #41122 

### Environment
- OS: macOS 12.3.1
- Web Server: Nginx
- PHP: 7.4.29
- WordPress: 5.9.3
- Browser: Google Chrome 101.0.4951.64
- Theme: Twenty Twenty-Two
- Active Plugins:
  - Gutenberg 13.2.1 and `trunk` after merge of #41122 

### Steps to Test Patch
- **Prerequisites**: Install/enable Gutenberg 13.2.1. Create at least two categories, and then multiple posts using one of those categories. This is required to filter the Query Loop block. (E.g. `wp post generate --count=10` is helpful toward this.)
- Create a new post and add a Query Loop block. Click the **Choose** button and accept the default loop template.
- In the block sidebar, under *Filters* in the *Categories* box, type and select one of the categories created in Step 1. You may need to re-select the Query Loop wrapping block, such as through the List View sidebar (<kbd>Ctrl-Opt-O</kbd> on macOS).
- After category selection, the backend editor will refresh and display the filtered results.
- Publish post, and open frontend page in a new tab/window.
- Observe that the query displays posts filtered by the chosen category.
- 🛠 Apply patch / upgrade Gutenberg to `trunk`.
- Refresh the frontend page.
- ✅ Observe that the posts remain filtered by category.

### Test Results
✅ Patch addresses reported issue.

### Screenshots
<img src="https://user-images.githubusercontent.com/824344/169362951-a4c18cf8-9c95-448a-acee-5ba025c6edef.png" width="376" style="width:50%;height:auto" alt="Screenshot of test result">
Gutenberg `trunk`

**Comment by Mamaduka** [comment] 2022-05-20 05:21
The issue should be fixed with Gutenberg 13.2.2. See the details - https://github.com/WordPress/gutenberg/issues/41135#issuecomment-1131923762.

**Closed as completed by Mamaduka** 2022-05-20 05:21 UTC
Labels: Needs Testing, [Type] Regression, [Block] Query Loop

**Comment by slaFFik** [comment] 2022-07-30 21:34
I'm not sure what has been fixed (so many seemingly unrelated issues are linked in the thread), but I get exactly the same problem as OP shared in initial issue description in both clean WordPress 6.0.1 and Gutenberg 13.7.3 with FrostWP theme.

See screenshot. 
On the left - Block Editor (GB 13.7.3)
On the right - front-end (FrostWP)
![image](https://user-images.githubusercontent.com/282234/181996912-0404281e-efe5-4ac1-948d-864a9a528357.png)

So filtering by category for a CPT created using Pods plugin works fine inside the Block Editor, but not working on the front-end.

**Comment by FlorientR** [comment] 2023-01-26 10:57
Hi !

After search on code, the taxonomy must be "publicly_queryable" for work on front.

Bye !

**Comment by FlorientR** [comment] 2023-01-26 11:04
> I'm not sure what has been fixed (so many seemingly unrelated issues are linked in the thread), but I get exactly the same problem as OP shared in initial issue description in both clean WordPress 6.0.1 and Gutenberg 13.7.3 with FrostWP theme.
> 
> See screenshot. On the left - Block Editor (GB 13.7.3) On the right - front-end (FrostWP) ![image](https://user-images.githubusercontent.com/282234/181996912-0404281e-efe5-4ac1-948d-864a9a528357.png)
> 
> So filtering by category for a CPT created using Pods plugin works fine inside the Block Editor, but not working on the front-end.

Hi !

After search on code, the taxonomy must be "publicly_queryable" for work on front.

Bye !

**Comment by slingshotdesign** [comment] 2023-04-21 09:09
@FlorientR thank you!

**Comment by marcizus** [comment] 2024-07-11 11:53
@FlorientR thank you. Your answer helped me.
