### ISSUE TITLE
onRender callback on serverSideRender block

### ISSUE THREAD

**Issue by Arifursdev** [WordPress/gutenberg#61479] opened 2024-05-08 09:38 UTC
Is there any existing official way to have `onRender` callback when block is Server Loaded on the Block Editor?

```js
const { serverSideRender } = wp;
const __namespace = 'abcd-blocks/abcd-featured-row';
el(serverSideRender, {
    block: __namespace,
    attributes: attributes
})
...
```

so when any settings are changed, we can do something to the markup of the page.

is this possible?
```js
const { serverSideRender } = wp;
const __namespace = 'abcd-blocks/abcd-featured-row';
el(serverSideRender, {
    block: __namespace,
    attributes: attributes,
    onRender: () => {
        console.log('changed')
    }
})
...
```

**Comment by Mamaduka** [comment] 2024-05-08 09:57
Probably a duplicate of #7346 and #35294.

**Closed as not planned** 2024-05-08 09:58 UTC
Labels: [Type] Enhancement, [Package] Server Side Render

**Comment by Arifursdev** [comment] 2024-05-08 11:25
duplicates are from 2018-19, i wonder what's the alternative there is since this is not getting approved.

**Comment by Mamaduka** [comment] 2024-05-08 11:59
The second issue has more details and proposes a better API - https://github.com/WordPress/gutenberg/issues/35294#issuecomment-933214497.

The `serverSideRender` component is small, and folks can duplicate it to make modifications if waiting for a core solution isn't an option.
