### ISSUE TITLE
Site Editor: undo button not working properly

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#24359] opened 2020-08-04 21:08 UTC
**Describe the bug**

Undo functionality is not working properly in Site Editor experiment. 

**To reproduce**
1. Enable Site Editor experiment in Gutenberg Experiments page.
2. Open the Site Editor and make a couple of changes to the header and in different places in post content.
3. Try clicking on undo button.
4. Notice that blocks are not focused before removal and that remove isn't always working.

**Expected behavior**

I'd expect undo to work seamlessly work across different entities (template parts, post content), similar to how it works in post editor.

**Comment by jeyip** [comment] 2020-10-06 17:30
- [Original PR that implemented the undo/redo functionality](https://github.com/WordPress/gutenberg/pull/21955)
- **Reproducing the issue**
  - There are two seemingly unique conditions under which I can reproduce unexpected behavior.
  - When modifying paragraph block text to a template part and attempting to undo the new content (add 1 character, pause, and click the undo button).
    - I don't see the same problem when modifying site title and site description in a template part.
    - Maybe this is related to updating specific data sources (site title and site description persist data in a unique way)
  - When adding a block to the site editor template and attempting to undo the addition (add paragraph block to the document and click the undo button)
- **Relevant files**
  - The undo button component: `packages/edit-site/src/components/header/undo-redo/undo.js`
  - How undo metadata is added to the undo "stack" when editing an entity `packages/core-data/src/actions.js:256`
  - How undo actions are processed: `packages/core-data/src/reducer.js:414`

**Comment by ianstewart** [comment] 2021-02-23 20:01
Strange issue today that I can't replicate, perhaps related to https://github.com/Automattic/wp-calypso/issues/50396 but I was somehow able to undo so much that my page/post content disappeared from the site editor. Template part content was still there but all the content from the Post Content block was gone.

**Comment by Addison-Stavlo** [comment] 2021-02-23 20:45
It has been a while since I tested 'undo' in the site editor.  But I went back and tested around with it a bit today and it seems to be working much better than I expected.  I am unable to repro the original issues we discussed here such as:

> When modifying paragraph block text to a template part and attempting to undo the new content (add 1 character, pause, and click the undo button).
> When adding a block to the site editor template and attempting to undo the addition (add paragraph block to the document and click the undo button)

I tested by adding and editing different blocks (paragraphs, buttons, spacers) inside the template level, template part, and the post content (and all 3 tied together).  'Undo' seems to undo everything, step by step, in the expected order.

**Comment by Addison-Stavlo** [comment] 2021-02-23 20:49
^^ That said Im definitely interested to figure out how to repro what @ianstewart experienced!

**Comment by siriusmw** [comment] 2021-03-10 04:24
Does this help? From console after installing Gutenberg plugin (trying to get updates) 
inspecting the now-not-working undo button. I don't see this issue on sites without the actual plugin--only on this one.
(I don't really know what I am looking at here--apologies if it doesn't help)***The plugin also broke the widget display. Maybe not needed?

react-dom.min.js?ver=16.13.1:125 TypeError: Cannot read property 'replace' of undefined
    at ie (gutenberg-editor.js?ver=6048430c49dbe:1)
    at WithAdvancedControls((WithAdvancedControls(WithAdvancedControls(WithAdvancedControls(WithAdvancedControls(WithAdvancedControls(WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component)))))))))))) (gutenberg-editor.js?ver=6048430c49dbe:16)
    at we (react-dom.min.js?ver=16.13.1:84)
    at zj (react-dom.min.js?ver=16.13.1:226)
    at Th (react-dom.min.js?ver=16.13.1:152)
    at tj (react-dom.min.js?ver=16.13.1:152)
    at Te (react-dom.min.js?ver=16.13.1:146)
    at react-dom.min.js?ver=16.13.1:61
    at unstable_runWithPriority (react.min.js?ver=16.13.1:25)
    at Da (react-dom.min.js?ver=16.13.1:60)

**Comment by t-hamano** [comment] 2023-02-19 04:50
I have tested it with the latest Gutenberg and it generally appears to work as expected:

https://user-images.githubusercontent.com/54422211/219922654-9319015f-cc44-4d66-bcf3-c3811c992f72.mp4

---

However, I have confirmed that undo works on a character-by-character basis in the query loop block:

https://user-images.githubusercontent.com/54422211/219922916-cc982639-d71a-4e70-8bf1-81e7e03dac3b.mp4

---

If this issue is not a site editor issue, how about closing this issue and submitting a new one that focuses more on the problem?

**Comment by Addison-Stavlo** [comment] 2023-02-23 20:41
Hi @t-hamano ,

> If this issue is not a site editor issue, how about closing this issue and submitting a new one that focuses more on the problem? 

Its been a few years since this issue was opened and I wouldn't necessarily expect the original author to reply.

Given that I was able to test this working as expected back in 2021, no one has been able to reproduce any of the original issues, and its been 2 years since last action of any sort on this issue... id totally say its safe to close it.

Il close it here, but in the future Id say feel free to close it yourself if it makes sense and you feel comfortable with it. People can always re-open them if needed. 😁

**Closed by Addison-Stavlo** 2023-02-23 20:41 UTC
Labels: [Type] Bug, [Feature] History, [Feature] Full Site Editing

**Comment by vindl** [comment] 2023-02-24 18:53
> Its been a few years since this issue was opened and I wouldn't necessarily expect the original author to reply.

The original author here. 😄 This was filed in the early days of the Site Editor when Undo functionality was very broken. Things have improved significantly since then, and it's safe to close this issue now.
