### ISSUE TITLE
Enable opening links in new tab for Button block

### ISSUE THREAD

**Issue by mvpspl619** [WordPress/gutenberg#10073] opened 2018-09-20 14:50 UTC
**Is your feature request related to a problem? Please describe.**
It would be awesome to add option to open links in new tab for the `core/button` component. I see some work for the `core/image` component in [this PR](https://github.com/WordPress/gutenberg/pull/9520). But it would be awesome to add that functionality to the `core/button` component as well. 

**Describe the solution you'd like**
A good solution is to add the option to open links in new tab in the `<InspectorControls />` so it shows up in the block settings sidebar. 

**Describe alternatives you've considered**
An alternative I've thought about is creating a custom component that behaves like `core/button` but our own. This is not a good solution, it's best to add this most-commonly required functionality to the existing component in Gutenberg.

**Comment by chrisvanpatten** [comment] 2018-09-21 11:39
Hi @mvpspl619 — I hope it's okay but I edited your issue title to make it clear that you mean the button _block_. We also have a button component that we use for buttons in the Gutenberg user interface, but it's separate and mostly unrelated.

Thanks for the suggestion, and I agree it'd be great to see.

**Comment by LakenH** [comment] 2018-09-21 14:35
This looks like it's most likely a duplicate of #8000, #8550, and #8829

**Comment by youknowriad** [comment] 2018-09-21 14:37
yes, Duplicate of #8000

**Closed by youknowriad** 2018-09-21 14:37 UTC
Labels: Blocks, [Type] Enhancement

**Comment by mvpspl619** [comment] 2018-09-21 14:46
@youknowriad @LakenH Sorry about the duplicate. Thank you for cleaning this up.

**Comment by LakenH** [comment] 2018-09-21 14:51
@mvpspl619 no problem, there are so many issues that it's hard to keep track of them all and find them even!
