### ISSUE TITLE
Clicking on the pencil icon in the Customizer does not work anymore

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31183] opened 2021-04-26 08:34 UTC
## Description
Clicking on the pencil icon in the Customizer does not work anymore. Normally clicking on the pencil icon in the preview should open in the sidebar the widget area that contains the corresponding widget.

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk` and a theme with sidebars
1. Go to Appearance > Widgets
2. Add a block to any widget area
3. Go to Appearance > Customize > Widgets > [your widget area]
4. Notice in the preview the pencil icon appears on the widget/block you added at (2)
5. Nothing happens :(

## Expected behaviour
Clicking on the pencil icon in the preview should open in the sidebar the widget area that contains the corresponding widget.

## Actual behaviour
Clicking on the pencil icon in the preview does nothing.

## Screenshots or screen recording (optional)

<img width="1296" alt="pencil" src="https://user-images.githubusercontent.com/107534/116053229-1d73ff80-a683-11eb-8885-ba17f2f47b5f.png">

**Comment by vdwijngaert** [comment] 2021-04-26 13:41
Looks like the `focus-control-for-setting` event is not yet implemented for the experimental sidebar block editor control in the Customizer.  This is where the event gets triggered: https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/js/customize-selective-refresh.js#L339

**Comment by noisysocks** [comment] 2021-04-28 02:22
Related, probably the same: https://github.com/WordPress/gutenberg/issues/30897

**Comment by talldan** [comment] 2021-04-29 05:51
This is a duplicate of #30897

I've renamed the other one so it's a bit clearer.

**Closed as completed by talldan** 2021-04-29 05:51 UTC
Labels: [Type] Bug, [Feature] Widgets Customizer
