### ISSUE TITLE
Template author incorrect for customized plugin templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#49089] opened 2023-03-15 09:49 UTC
### Description

If you edit a template that supplied by a plugin, the details panel for that template should state the author as:

> Plugin name (customized)

This is how it works in the templates list which is correct:

<img src="https://user-images.githubusercontent.com/846565/223988436-b32511a2-d827-42dd-b819-3b4f7d38a6d9.png">

However, it displays the author as the user who made the customizations instead:

<img src="https://user-images.githubusercontent.com/846565/223697872-082832b9-53f8-43f0-b4ce-f50beb32b07e.png">

The issue seems to resolve itself on refresh so it's not a huge problem, but one that would be nice to tidy up.

cc @kevin940726 

### Step-by-step reproduction instructions

1. Install a plugin that supplies its own templates, like WooCommerce.
2. Open a plugin template, make changes, save.
3. Click the W button to expose the template details panel.
4. Observe that the author is listed as a user rather than the plugin.
5. Refresh.
6. Now the author is correctly listed as the plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment] 2023-03-17 07:57
I'm not able to reproduce this, I am not listed as a template author when I edit and save the template. 
<img width="557" alt="Screenshot 2023-03-17 at 14 55 00" src="https://user-images.githubusercontent.com/41231764/225845653-41204d64-00d7-410a-8135-422cf31dec63.png">

**Environment**
Twenty Twenty-Three theme
WP 6.1.1 
Gutenberg 15.3.1

**Comment by jameskoster** [comment] 2023-03-17 10:45
> Gutenberg 15.3.1

Apologies, I should have stated that this is an issue on trunk.

**Comment by kevin940726** [comment] 2023-03-23 06:06
It seems like it's because the results coming from `/wp/v2/templates/{template_id}` is different from the results from the list API `/wp/v2/templates`.

If we're viewing the template then the editor will call the API `/wp/v2/template/{template_id}` to get the `template` data. When we visit the list view either in the sidebar or in the manage view, the editor will call `/wp/v2/templates` and override any existing template data in the global cache.

Calling from `/wp/v2/templates/{template_id}` gives me this result for the `woocommerce/woocommerce//taxonomy-product_attribute` template:

```json5
{
    "id": "woocommerce/woocommerce//taxonomy-product_attribute",
    "theme": "woocommerce/woocommerce",
    "content": {
        // ...
    },
    "slug": "taxonomy-product_attribute",
    "source": null,
    "origin": "plugin",
    "type": "wp_template",
    "description": "Displays products filtered by an attribute.",
    "title": {
        "raw": "Products by Attribute",
        "rendered": "Products by Attribute"
    },
    "status": "publish",
    "wp_id": 886,
    "has_theme_file": false,
    "is_custom": true,
    "author": 1,
}
```

However, when I'm calling the `/wp/v2/templates` API, the result for the this template is as follow:

```json5
{
    "id": "woocommerce/woocommerce//taxonomy-product_attribute",
    "theme": "woocommerce/woocommerce",
    "content": {
        // ...
    },
    "slug": "taxonomy-product_attribute",
    "source": "custom",
    "origin": "plugin",
    "type": "wp_template",
    "description": "Displays products filtered by an attribute.",
    "title": {
        "raw": "Products by Attribute",
        "rendered": "Products by Attribute"
    },
    "status": "publish",
    "wp_id": 886,
    "has_theme_file": true,
    "is_custom": false,
    "author": 0,
}
```

Notice the mismatch between the two objects, especially the `source`, `has_theme_file`, `is_custom`, and `author` fields. These are the fields used by the `useAddedBy` hook to determine which type the author is.

I can dig deeper but I'm not too familiar with the PHP side of the code. I could use some help from folks who understand this more than me.

**Comment by youknowriad** [comment] 2024-10-24 14:50
Closing as there's no details panel anymore.

**Closed as completed by youknowriad** 2024-10-24 14:50 UTC
Labels: [Type] Bug, [Feature] Site Editor
