### ISSUE TITLE
wp-block-post-featured-image missing the lazy attribute

### ISSUE THREAD

**Issue by Mte90** [WordPress/gutenberg#41783] opened 2022-06-17 11:13 UTC
### Description

Since WP 5.5 the lazy attribute to img tags is added automatically.

Well this block doesn't have that value... https://github.com/WordPress/gutenberg/blob/ba9b739ef9bb11e4107cf02f8f2366f34a99f9ed/packages/block-library/src/post-featured-image/edit.js#L152

### Step-by-step reproduction instructions

1. Add that block and see the html generated

### Environment info

- WP 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aristath** [comment] 2022-06-17 11:25
I remember seeing a discussion somewhere that featured-images should _not_ get the lazy attribute, because _usually_ they are above the fold, and lazy-loading them is bad for performance and the user-experience... 🤔 
I can see a post on make that says the 1st image won't be lazy-loaded, could that be what's happening here? https://make.wordpress.org/core/2021/12/29/enhanced-lazy-loading-performance-in-5-9/

**Comment by Mte90** [comment] 2022-06-17 12:07
I remember that discussion but when in a page there is more then one?

**Comment by aristath** [comment] 2022-06-21 08:10
> but when in a page there is more then one?

An example would be an archive of posts, where each post has its featured image inside the query loop 😉

**Comment by ockham** [comment] 2022-10-31 15:24
Potentially related Trac ticket: https://core.trac.wordpress.org/ticket/56930.

**Comment by spacedmonkey** [comment] 2022-11-01 17:16
Related: #45224

**Comment by felixarntz** [comment] 2022-11-02 20:19
@Mte90 @aristath @ockham @spacedmonkey https://core.trac.wordpress.org/ticket/56930 is primarily caused by https://core.trac.wordpress.org/ticket/55996, which is also covered in #45224 and now has a working (core) PR in https://github.com/WordPress/wordpress-develop/pull/3549.

The problem here is a different one though: I'm unsure whether the original issue description is accurate - the `loading="lazy"` attribute is expected to not be present if the featured image appears on top of the page (specifically, the very first image that is either a featured image or part of any post content blob), while it is expected to be present on the featured image otherwise. I just tested this with the https://github.com/WordPress/wordpress-develop/pull/3549 PR branch, that fixes the root problem around lazy-loading attriibutes being incorrectly applied in block themes, and with Twenty Twenty-Two: In a post where I have the featured image as the first image on the page, it still receives the `loading="lazy"` attribute - so that is incorrect, but it's still the opposite of what the issue description here says the problem would be.

I believe there is something we need to tweak in the `core/post-featured-image` block PHP implementation so that the core heuristics for whether the attribute should be added applies correctly. Will look into it.

**Comment by felixarntz** [comment] 2022-11-03 22:00
I found the problem here and addressed it as part of https://github.com/WordPress/wordpress-develop/pull/3560: Basically, the issue with the `core/post-featured-image` block here is the lack of https://github.com/WordPress/wordpress-develop/pull/3560/files#diff-a9372558b4bbc50ffb4ff3b685da5c4e1ed1e2d58cf97e47c0abbfd7c58681c9R24 in that block rendering function. This is currently breaking backward compatibility (and this core feature!); the fix here is exactly the same that has already been added to the `core/post-content` block for the same reason.

**Comment by felixarntz** [comment] 2022-11-22 17:40
Fixed via #45534.

To follow the wider-reaching WP core fix, please follow along https://core.trac.wordpress.org/ticket/56930.

**Closed as completed by felixarntz** 2022-11-22 17:40 UTC
Labels: [Type] Bug, [Type] WP Core Ticket, [Type] Performance, [Block] Post Featured Image
