### ISSUE TITLE
Switching from editing page to pattern causes incorrect editing template notification

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#51927] opened 2023-06-26 16:24 UTC
Using 16.1 RC1, I noticed that if I went to edit a page then switched to editing a pattern, I immediately was met with a notification that I was editing a template and offering the option to go back to a page. If I click on it, nothing happens. This notification shouldn't happen at all but is likely related to how we're storing custom patterns right now, especially since we show "template" in the sidebar tabs Patterns: https://github.com/WordPress/gutenberg/issues/51925

https://github.com/WordPress/gutenberg/assets/26996883/d4e5bc19-d2ca-43fc-a519-122d40b9ad52

cc @SaxonF @noisysocks

**Comment by annezazu** [comment] 2023-06-26 16:44
Noting that this is likely the same issue: https://github.com/WordPress/gutenberg/issues/51261 and will be solved by https://github.com/WordPress/gutenberg/pull/51880 hopefully! Let's confirm.

**Comment by noisysocks** [comment] 2023-06-27 00:17
Yep dupe of https://github.com/WordPress/gutenberg/issues/51261.

**Closed as not planned by noisysocks** 2023-06-27 00:17 UTC
Labels: [Type] Bug, [Feature] Patterns, [Feature] Site Editor
