### ISSUE TITLE
IE11: Enter in a paragraph loses focus.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#12113] opened 2018-11-20 14:14 UTC
Steps to reproduce:

- Use IE11
- Set focus in a Paragraph
- Type some text and press Enter
- Note that focus is lost and you have to click the new paragraph to set focus there again

Expected result: you should just be able to keep typing.

When focus is lost, it's actually set on the body element. An additional side effect is that _clicking_ a paragraph to type requires _two_ clicks. The first click sets focus on the block itself (`.editor-block-list__block`), and the 2nd click finally sets focus where it needs to be.

This appears to have been a regression that happened between Gutenberg 3.8.1 and 3.9.1. 

3.8.1 GIF of the expected behavior:

![3 8 1](https://user-images.githubusercontent.com/1204802/48778980-e7263f00-ecd6-11e8-848d-740bef5d23fd.gif)

3.9.1 GIF of the bug:

![3 9 1](https://user-images.githubusercontent.com/1204802/48778990-eee5e380-ecd6-11e8-8546-c5e631a85177.gif)

**Comment by afercia** [comment] 2018-11-21 16:51
Some more details from #12180 (a duplicate of this). Worth noting this is not just about mouse interaction, but it also breaks the "Enter – create a new paragraph – just write" flow.

To me, seems the first time focus is set on the block _wrapper_ (not on the body). I'm using a testing tool that adds a red outline to elements that receive focus:

Testing in latest master 4.5.1
Windows 10, IE 11

- create a new post
- enter a title
- press Enter
- focus is apparently moved to the default empty block:

![screenshot 147](https://user-images.githubusercontent.com/1682452/48850752-96334b00-eda9-11e8-8cf7-abb354026ac4.png)

- notice there's no visible caret
- try to type something: nothing happens
- expected: caret to be in the editable field and typing to work

Now, there's the need to press the Tab key to actually move focus to the editable area:

![screenshot 148](https://user-images.githubusercontent.com/1682452/48850811-b6fba080-eda9-11e8-9a54-1860c57fbef3.png)

- notice the focused element is now the actual editable field 
- the caret appears initially misplaced below the editable field (tried both in Twenty Nineteen and Twenty Seventeen)
- start typing: characters are entered in the field as expected

This happens with all the following added blocks, making the writing experience with the keyboard less than ideal.

**Comment by jasmussen** [comment] 2018-11-21 16:56
Perhaps should've noted here also. The following PR was the cause of the regression:

https://github.com/WordPress/gutenberg/issues/10723

**Comment by afercia** [comment] 2018-11-22 09:07
Please verify if the fix for this fixes also https://github.com/WordPress/gutenberg/issues/12181

**Closed** 2018-11-22 14:55 UTC
Labels: Accessibility, Regression, [Type] Bug

**Comment by jasmussen** [comment] 2018-11-22 15:00
💥
