### ISSUE TITLE
RichText: Using formats at the boundaries doesn't work as expected

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#11326] opened 2018-10-31 19:08 UTC
**Describe the bug**

**To Reproduce**
1. Add new block containing RichText control (Paragraph, List, etc)
2. Write any text.
3. Select some text and make it bold (or italic, underline, whatever).
4. Move the cursor at the end of selection.
5. You will notice that the block toolbar no longer highlights applied formater and it hides after a brief time.
6. When you continue typing from the end of the selection, format will continue to be applied.
7. No move the cursor to the beginning of the selection. Actually one keypress before.
8. UI shows that format option is still selected and toolbar can be see.
9. When you start typing you don't see format applied but UI tells something else.

**Expected behavior**
Formats should be properly applied with the proper visual state of Block Toolbar controls.

**Screenshots**
![typing at the end of selection](https://user-images.githubusercontent.com/699132/47812009-7f1fb100-dd47-11e8-807a-e2735d6e9d05.gif)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: the latest

**Comment by iseulde** [comment] 2018-11-01 12:49
Sounds like a duplicate of #11091.

**Closed** 2018-11-01 13:57 UTC
Labels: Regression, [Component] Rich Text
