### ISSUE TITLE
Extremely slow to show editor on longer pages

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#2822] opened 2017-09-28 10:44 UTC
I have a Post that takes almost 2 minutes before gutenberg is actually displayed with the content. It's one of my longer Gutenberg posts, but still not excessively long. It takes an unacceptable amount of time for Gutenberg to load. This is a local site so it's not a hosting issue.

I've opened it over and over again and without fail it takes at least 1min 50sec's to open, every time.

Let me know if you'd like me to post the content somewhere, if that's of any use.

_Firefox 55.0.3 (64-bit)
macOS Sierra 10.12.1
Gutenberg 1.2.1_

**Comment by youknowriad** [comment] 2017-09-28 10:51
Yeah, It would be great if you can share the post content with us. A pastebin or anything else!

**Comment by maddisondesigns** [comment] 2017-09-28 11:37
Here ya go...

https://pastebin.com/EC0TUtnw

You obviously wont be able to see the images since it's a local site, but in case it helps, here's a screenshot of the whole page. As you can see, most of the content is just from the default Gutenberg post.

![welcome_to_the_gutenberg_editor_gutenberg_2](https://user-images.githubusercontent.com/2078245/30964544-1f485494-a495-11e7-97fd-3f376173a072.png)

**Comment by youknowriad** [comment] 2017-09-28 12:04
Thanks for sharing the post, First results:

I tried profiling a bit, and it looks like there are still some "network" requests even on a local machine (Some javascript dependencies are fetched externally, they are cached in prod I think) and also some assets of this post are fetched remotely.

<img width="253" alt="screen shot 2017-09-28 at 12 55 24" src="https://user-images.githubusercontent.com/272444/30965251-9fd36304-a44c-11e7-82ba-02a97a64208d.png">

so in my tests, loading everything takes 14s (I have a slow connection) and the `DomContentLoaded` is very high. which means the initial HTML takes time to being fetched and loaded in the browser.

If you dig more in the network tab, you'll notice the first HTTP request loading the page is the one causing the issues, so I assume the issue is on the backend.

I suspected the backend block parser but compared this to loading the same post in the frontend, it's way quicker on the frontend and the frontend also uses the parser. So more likely, it's elsewhere and I still suspect this to be related to the vendors being fetched from the internet (react, moment, react-dom...) which makes me think, this could be minor since we're more likely change the way we load these vendors in the future and probably bundle them.

**Comment by gziolo** [comment] 2017-10-26 10:33
@maddisondesigns how many revisions does your post have? I might have found the root cause of this issue. I just need to do some more research. I should file an issue soon.

**Comment by maddisondesigns** [comment] 2017-10-27 01:55
@gziolo The post has zero revisions. The only reason I know this, is because I just had to use phpMyAdmin to run an sql query on the Post ID. I tried opening the page using Gutenberg and it will no longer open, with the latest version of the plugin (1.5.2). My other Gutenberg posts open fine, but this one no longer opens. I waited for over 10 mins before giving up, and I tried multiple times.

**Comment by gziolo** [comment] 2017-10-31 10:32
It seems like we found a bug that could cause your issue. It has been fixed in #3233 and it's going to be released this week in 1.6.0 version. Let us know if that is going to improve experience with your post. Thanks for sharing all details, it was very helpful 👍

**Comment by maddisondesigns** [comment] 2017-11-01 02:29
@gziolo I just tried with v1.6 and the above post now opens again, and also opens in a reasonable time as well, so it looks like this issue was been resolved. Thanks for that.

**Comment by gziolo** [comment] 2017-11-01 03:19
I’m more than happy to hear that and close this issue 👍

**Closed by gziolo** 2017-11-01 03:19 UTC
