### ISSUE TITLE
Handbook Sidebar Tutorials Give a Sidebar That dissapears When unstarred and can never be retrieved

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#15162] opened 2019-04-24 23:20 UTC
**Describe the bug**

Registering a sidebar as described in the handbook, gives you a "starred" sidebar. If you unstar this sidebar and close it, there's no way to bring it back.

Visit here: https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/plugin-sidebar-0/

And try to use the code example provided, reproduced here:

```js
( function( wp ) {
    var registerPlugin = wp.plugins.registerPlugin;
    var PluginSidebar = wp.editPost.PluginSidebar;
    var el = wp.element.createElement;

    registerPlugin( 'my-plugin-sidebar', {
        render: function() {
            return el( PluginSidebar,
                {
                    name: 'my-plugin-sidebar',
                    icon: 'admin-post',
                    title: 'My plugin sidebar',
                },
                'Meta field'
            );
        },
    } );
} )( window.wp );
```

This will create a sidebar if you put it in the console or load it into the browser. However, if you click on the star in the sidebars header, it dissapears from the toolbar. Once closed, the sidebar can never be displayed and no UI is available for bringing it back. Running the code again in the console no longer works without a complete flush of the browsers local storage

**Expected behavior**

When registering a sidebar, I expect it to appear as an option in the 3 dot menu, or at the very least, display when registered via code a second time on a fresh page request.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 66

**Additional Information**

This was originally reported on WP Stack Exchange at https://wordpress.stackexchange.com/questions/336218/show-missing-sidebar-from-gutenberg-admin-area/336223?noredirect=1#comment494338_336223

Clearly either there is a bug, or the handbook is missing critical information

**Comment by tomjn** [comment] 2019-04-25 10:53
It turns out the issue is that the handbook makes no mention of `PluginSidebarMoreMenuItem` in that tutorial, and that a more complete example solves this: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-plugins/

**Comment by swissspidy** [comment] 2019-05-03 08:37
Sounds like a duplicate of #14457.

**Closed by swissspidy** 2019-05-03 08:37 UTC
Labels: Plugins API, [Component] Plugin, [Status] Duplicate
