### ISSUE TITLE
Formatting options don't work well on existing posts

### ISSUE THREAD

**Issue by patilswapnilv** [WordPress/gutenberg#1529] opened 2017-06-28 05:21 UTC
When I try editing an existing post with Gutenberg, The formatting options does not seem to work as they are expected to. The select and edit action makes changes to the whole content.

I made a screencast to show that.  Please check if that is helpful.
 https://www.useloom.com/share/49987909d2ce487498b9c3e8d2063e13

**Comment by swissspidy** [comment] 2017-06-28 09:41
Ugh, I cannot even open an existing post right now. See #1533.

**Comment by patilswapnilv** [comment] 2017-06-29 02:02
So today I decided to clone the plugin repo and use it instead of the one on WordPress.org.
Since the bug @swissspidy reported was worked in yesterday.

And the results don't make me happy. Now when I open an existing post it just gives me a white screen. Nothing else. I am assuming Gutenberg should be editing previous posts, right?

Here is a screencast https://www.useloom.com/share/253fac8b60564bd1bfdbd0129f3efcb5

**Comment by youknowriad** [comment] 2017-08-02 11:44
Can't reproduce this in the last version, closing.

**Closed by youknowriad** 2017-08-02 11:44 UTC
