### ISSUE TITLE
Paragraph is still being used as the appender of inner blocks, when it is not included in the allowedBlocks

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#10726] opened 2018-10-18 10:13 UTC
**Describe the bug**
The alternative block appender included in version 4.0 is not being used when a block is inserted through the menu option "insert after" (of one of the inner blocks); instead, the paragraph appender is included.

**To Reproduce**
1. Create a nestable block where paragraph is not allowed and with templateLock set to false.
2. Select any of the inner blocks and in the toolbar click on the more menu and then on "Insert Before" or "Insert After".
3. A paragraph is added instead of the new appender.

**Expected behavior**
Expected the new appender instead of the paragraph appender.

**Additional context**
- Gutenberg 4.0
- WordPress 4.9.8

**Comment by chrisvanpatten** [comment] 2018-10-18 19:11
Thanks for the report! This is also a duplicate of #10301 so I'll close to consolidate everything there and make sure your report is mentioned!

**Closed by chrisvanpatten** 2018-10-18 19:11 UTC

**Comment by alvaro0555** [comment] 2018-10-18 21:00
Great, thanks.
