### ISSUE TITLE
Scaled image doesn't align to center

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#3325] opened 2017-11-03 08:35 UTC
To reproduce:

- New post
- Insert new image
- Scale an image
- No alignment shows
- Left align: it pops over
- Center and this shows:

![2017-11-03 at 08 34](https://user-images.githubusercontent.com/253067/32365537-fa52caae-c071-11e7-9fc5-61fe1e4793b8.png)

**Comment by hedgefield** [comment] 2017-11-07 11:51
The problem is mainly that it looks like you have `left-center-right` controls, but those actually affect the block itself, with the options `float left - wide - float right` (so it can appear next to a text block).

I can imagine that having the block take up the full width of the content column but have the image within it aligned to the right would be nice, so maybe there should be two sets of alignment controls? I don't know, that might get confusing, maybe for v1 it's best to only offer options to align the image within the block. If we ever [do column layouts](https://github.com/WordPress/gutenberg/issues/219) the block alignment problem will solve itself.

**Comment by mtias** [comment] 2017-11-29 15:22
Closing as duplicate of #2548.

**Closed by mtias** 2017-11-29 15:22 UTC
Labels: Media
