### ISSUE TITLE
Add New Tag in bug and limited writing tag and limits 

### ISSUE THREAD

**Issue by ygpcode** [WordPress/gutenberg#19878] opened 2020-01-24 18:20 UTC
**Describe the bug**

add new post >document >tag>add new tag section in bug

i am check in different website in post section in add new tag box 
Fix the box 
Add new tag in box report 
limitation the tag in provide (**suppose title length** )(**limited tag length** )

**Screenshots**

![slide3](https://user-images.githubusercontent.com/25919963/73092695-0df78b00-3f03-11ea-8219-0b21528328fb.jpg)

![Slide1](https://user-images.githubusercontent.com/25919963/73092234-3632ba00-3f02-11ea-8813-c8cff562d55f.JPG)
![Slide2](https://user-images.githubusercontent.com/25919963/73092235-36cb5080-3f02-11ea-9093-b19acbeb7c50.JPG)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome,Mozilla Firefox]

**Comment by talldan** [comment] 2020-02-06 06:53
I can reproduce that the text is flowing slightly outside the input when on the last line of the text box, but it does still seem to scroll and doesn't seem to be limiting the length of the tag..

**Comment by glendaviesnz** [comment] 2020-02-14 03:54
seems to be caused by: 

https://github.com/WordPress/gutenberg/blob/master/packages/components/src/form-token-field/style.scss#L44 

Removing this fixes the issue, but I imagine this auto width was set for a specific reason, so something else may be broken by removing this.

**Comment by paaljoachim** [comment] 2021-04-15 19:13
Testing with WordPress 5.7.
Twenty Twenty One.
Gutenberg plugin 10.4.1
A local test site.
Chrome

Made a new post.
Added characters that fill the box making it horizontally scroll.
![Screen Shot 2021-04-15 at 21 12 39](https://user-images.githubusercontent.com/5323259/114925396-56180b80-9e2f-11eb-87f0-3871102070fe.png)

It looks fine to me. I think we should leave it as it is. Even though the user can add as long of tag as they want to.
My suggestion would be to close this issue.

**Comment by paaljoachim** [comment] 2021-05-13 21:20
I just retested and it scrolls just like I mentioned in my last comment.
I will go ahead and close the issue.

**Closed by paaljoachim** 2021-05-13 21:20 UTC
Labels: [Type] Bug
