### ISSUE TITLE
Removing a block(s) with keyboard selection + backspace/delete does not reflect on preview or publish

### ISSUE THREAD

**Issue by vajrasar** [WordPress/gutenberg#42213] opened 2022-07-07 06:37 UTC
### Description

The issue can be seen when a new post is created (with or without the Gutenberg plugin installed), and you try to remove some lines of text or paragraph by the method of selecting them (keyboard selection) and pressing backspace/delete. Those lines/para won't be deleted and you can see that in preview, and also when the post is published.

### Step-by-step reproduction instructions

1. Create a new post, and put some content on it.
2. Say you have two consecutive blocks of text on the content that you want to remove.
3. Place the cursor on the starting of the first line of text.
4. Use the keyboard to select that line and the line below it.
5. Use the backspace/delete button on keyboard to remove those lines.
6. You should be able to see the expected change in editor.
7. But checking preview, saving draft, and publishing the post won't show the change.

### Environment info

- WordPress version 6.0
- Gutenberg version 13.6.0
- Browser: Chrome 102.0.5005.115 (arm64)
- Machine: M1 MBP

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment] 2022-07-08 03:53
Sounds like it's related to this comment by @youknowriad https://github.com/WordPress/gutenberg/pull/38892#issuecomment-1080319204 but for rich text blocks only.

cc @ellatrix

**Comment by talldan** [comment] 2022-07-08 04:31
I think the problem might be that when selecting two blocks in this way, the editor doesn't seem to consider it a multi-selection. This is how the editor is supposed to look when two blocks are selected using the mouse (notice the block toolbar shows grouping buttons because the editor considers this a multi-block selection):
![Screen Shot 2022-07-08 at 11 50 23 am](https://user-images.githubusercontent.com/677833/177913429-69325930-fd3b-4e57-8565-f80a6c32bd36.png)

This is how it looks when following the reproduction steps (the grouping buttons aren't shown):
![Screen Shot 2022-07-08 at 11 51 46 am](https://user-images.githubusercontent.com/677833/177913488-cf2a109e-8c9d-4a1e-a74e-700132e38c38.png)

I think that because the editor doesn't consider this a multi-block selection, it doesn't properly delete the blocks when backspace or delete is pressed.

From what I can tell it's this bit of code that isn't working, it doesn't set the end selection when the second block is selected. I'm not sure what the right fix would be, it seems difficult to determine when the second block is selected versus when the whole of the first block is selected:
https://github.com/WordPress/gutenberg/blob/dd8d577b859a07d1ea1798104123a162311435de/packages/rich-text/src/component/use-input-and-selection.js#L150-L173

Hopefully @ellatrix has an idea 😄

**Comment by alanjacobmathew** [comment] 2022-09-09 08:29
> I think that because the editor doesn't consider this a multi-block selection

Also notice when selecting using keyboard, it doesn't get reflected on the list view

**Comment by alanjacobmathew** [comment] 2022-09-09 09:12
A few more issue related with this, 
1: It doesn't always happen. Problem persists when I use the down arrow key and not the right arrow keys. If I select the very first character using the right key and rest using the down key, it works as expected.  

2: Cases where the problem persist, after removing the blocks, once you click on the next block it automatically replaces that block to the first block

3: Doesn't happening always, when multiselecting. Note the list view selection in the video. 
![Multi Select](https://user-images.githubusercontent.com/33965848/189314356-f589d3bf-1cfd-4faf-9f76-e3c53c904f7f.gif)
Here, in the first case, first 3 block weren't selected, but once the fourth block was selected, the entire set was selected.
In the second case, when the very last block was selected every other blocks were also selected.

**Comment by glendaviesnz** [comment] 2022-10-04 04:18
I wasn't able to replicate this on GB trunk or 6.1 Beta - I also tried just using the down arrow as @alanjacobmathew suggested but got the same result:

https://user-images.githubusercontent.com/3629020/193733307-b6adafe4-4bde-4255-abb8-c418cef3a666.mp4

**Comment by mcsf** [comment] 2022-10-04 16:13
> I wasn't able to replicate this on GB trunk or 6.1 Beta

Indeed, this seems to only affect 6.0.x.

**Comment by talldan** [comment] 2022-10-05 08:22
Same here. 🎉  

Thanks for checking. I'll close the issue.

**Closed as not planned by talldan** 2022-10-05 08:22 UTC
Labels: [Type] Bug, [Priority] High, [Feature] Block Multi Selection
