### ISSUE TITLE
Add Block: Parallax Image

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#734] opened 2017-05-09 15:32 UTC
Stemming from the Image Block, I'm mocking up a concept for a Parallax Image Block. The background image would move at a different transition speed than the rest of the page when scrolling. 

Not sure how detailed we want to go with this (allowing users to manipulate speed, etc.), so I kept it basic for now.

**Empty Block**
![parallax block-empty](https://cloud.githubusercontent.com/assets/617986/25858617/07c61e1a-3491-11e7-8c4a-6161c06fa16f.png)

**Neutral**
![parallax block-neutral](https://cloud.githubusercontent.com/assets/617986/25858663/238c50d8-3491-11e7-9624-09e2f63dfbb2.png)

**Selected UI**
![parallax block-selected ui](https://cloud.githubusercontent.com/assets/617986/25858675/2cb27278-3491-11e7-8bad-5be5ef2a6e58.png)

**Add Caption UI**
![parallax block-caption ui](https://cloud.githubusercontent.com/assets/617986/25858689/3422d5de-3491-11e7-97a2-9c58bd27a068.png)

I've included a video to get an idea of how this might work.
https://cldup.com/M3sp6ADiLK.m4v

A few unknowns...

1. Will the image always be full bleed for a parallax block?
2. Should we include text overlay? If so, should it scroll like the rest of the page, or do something similar to the video example where it fades out, and scrolls differently?
3. I'm struggling with an icon to represent this block, and selected one that I thought might work, but am up for suggestions.

**Comment by rileybrook** [comment] 2017-05-09 22:08
I like this idea, and regarding:
> 3. I'm struggling with an icon to represent this block, and selected one that I thought might work, but am up for suggestions.

Since a Parallax image is an offshoot of a regular image, it could be useful to demonstarte this to the user through the icon used. This could be done by designing a Parallax icon that is an alternate version of the image icon, showing the user they are still adding an image. 

A potential problem could be users correlating arrows in the icon with the block mover tool. Some first ideas combining your icon example and the image icon could like like these.

![parallax icons](https://cloud.githubusercontent.com/assets/7691812/25874580/6ab90778-34d0-11e7-80e5-49ae8aa4c26b.png)

**Comment by jasmussen** [comment] 2017-05-10 07:52
🎉

Love it! Mockups are on point! 

I was previously waffling on whether "Parallax" should be a separate block from Image, or whether it should just be a toggle you could apply to any image. But the video you recorded really drives home the uniqueness of this, and I think people are going to love having it as a separate thing in the inserter.

Question: should it be different from the Hero Image/Cover Image, though? That block already uses some fixed-position magic. Perhaps it's the same block as that, but parallax being a different option for the background positioning. CC: @georgeh

**Comment by karmatosed** [comment] 2017-05-17 17:13
Interesting @mapk, parallax to me is more a different option for position than a separate block, like you suggest @jasmussen.

**Comment by jasmussen** [comment] 2017-05-17 17:16
Want to add that I kindly asked for Marks help in imagining a parallax image block to get us closer to a decision on whether or not it's a separate block or not. Still not sure, but the mockups are very helpful!

**Comment by karmatosed** [comment] 2017-05-17 17:19
One ponder with this is mobile and actually the theme itself. Not a hurdle, more how we can add parallax into those circumstances.

**Comment by jasmussen** [comment] 2017-05-17 17:25
> One ponder with this is mobile and actually the theme itself. Not a hurdle, more how we can add parallax into those circumstances.

Yes, that's going to be a challenge indeed. https//me.sh uses 3D CSS horizontally for parallax. It's performant, nice, and JS free. But that can't ever work properly on iOS because then the rubberbanding effect and momentum scrolling has to be disabled. So it probably has to be JS parallaxing if need be, so we could probably marry that with both the editor block and the frontend rendition also.

**Comment by melchoyce** [comment] 2017-06-01 21:17
IMO, I think it makes more sense for Parallax to be a setting on Hero Image blocks. It seems like it would otherwise be identical.

**Comment by georgeh** [comment] 2017-06-02 14:26
I'm inclined to agree with @melchoyce - although I don't know if it makes sense at anything other than full-width. I'll try it out with the other hero image configurations and see

**Comment by mtias** [comment] 2017-06-26 18:14
@jasmussen can we close this with the "Cover Image" block merged? It needs a bit of work still, but it should be done in separate issues.

**Comment by jasmussen** [comment] 2017-06-27 07:53
Closing in favor of https://github.com/WordPress/gutenberg/issues/1476

**Closed by jasmussen** 2017-06-27 07:53 UTC
Labels: Blocks, Chrome, Design
