### ISSUE TITLE
Poor default presentation of menu items with longer names in mobile overlay

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#66741] opened 2024-11-05 10:01 UTC
### Description

Navigation Block: On mobile devices (mobile menu), longer menu items are apparently displayed left-aligned instead right-aligned from a certain width - regardless of which block theme I use, i.e. also with Twenty Twenty-Five.
I was able to simulate the issue in the developer console via Playground. To be on the safe side, I also created a “real” test page and was able to reproduce the issue there as well on mobile device. 

![Image](https://github.com/user-attachments/assets/916eec1d-2dd4-49ab-8fc1-ca07d098f53c)

![Image](https://github.com/user-attachments/assets/5bcc97f1-21c9-4ebd-a658-ceaa39b9a92f)

### Step-by-step reproduction instructions

1. Create a menu with the navigation block in TT4 
2. Create a menu item for example "Creating Webdesign with WordPress 6.7"
3. Save menu
4. Show Website on mobile device

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by sarthaknagoshe2002** [comment] 2024-11-14 19:17
Hey @hagege can you please provide more details to reproduce this bug.

**Comment by getdave** [comment] 2024-12-02 17:10
I think what we're seeing here is that the menu items are right aligned. Therefore to denote a hierarchy the sub levels are indented. However, because the alignment is to the right then the indentation happens from the _right_.  This is expected behaviour.

However, I acknowledge the presentation of submenus in the overlay on the Nav block needs improvement. Therefore I am closing this in favour of https://github.com/WordPress/gutenberg/issues/44346

**Closed as completed by getdave** 2024-12-02 17:10 UTC
Labels: [Type] Bug, [Block] Navigation, [Block] Submenu, [Feature] Navigation Menus
