### ISSUE TITLE
Reduce Spacer Block's minimum height

### ISSUE THREAD

**Issue by Sven74Muc** [WordPress/gutenberg#21702] opened 2020-04-18 09:39 UTC
Transfering this topic to github:
https://core.trac.wordpress.org/ticket/49862#comment:3

As discussed in the last editor chat ther is in issue in the backend with blocks with a smaller high then 20px.  Think this shouldn't stop changing the min high for the front end to 1px. Within the backend there could be 20px high to make a block usable.

**Comment by talldan** [comment] 2020-04-20 05:40
Closing as a duplicate of #18906

**Closed by talldan** 2020-04-20 05:40 UTC
