### ISSUE TITLE
If the attribute is set to the array in PHP block register it throws Notice: Undefined index: items in ***/wp-includes/rest-api.php on line 1092

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#8522] opened 2018-08-04 09:28 UTC
**Describe the bug**
If the attribute is set to the array in PHP block register it throws: 

> Notice: Undefined index: items in ***/wp-includes/rest-api.php on line 1092

**To Reproduce**
1. Register block in PHP, and declare attributes only in PHP.
2. Set attribute type to the array.
4. See the error in the editor.

**Expected behavior**
Not throwing notices.

**Additional context**
- Function that throws notices: 
https://developer.wordpress.org/reference/functions/rest_validate_value_from_schema/

**Comment by chrisvanpatten** [comment] 2018-08-04 15:15
Hi @bartekcholewa —

For arrays, you also have to pass in the type of the items in the array. Here's an example from one of my blocks, which uses an array of `int` IDs:

```php
...
'postIds' => [
	'type'    => 'array',
	'default' => [],
	'items'   => [
		'type' => 'integer',
	],
],
...
```

This is so `rest_validate_value_from_schema` knows what to expect inside the array.

I had similar trouble with it when I first started building blocks, so I think this might be something we can improve in the documentation.

**Comment by andreilupu** [comment] 2018-08-04 22:04
I also lost a few hours until I realized what's happening and what @chrisvanpatten said is what I ended up with.

Unfortunately, there is no documentation about this `items` entry. I found this [trac](https://core.trac.wordpress.org/ticket/42989), but I'm not sure what are the further steps for such a case or how I could document these params in the handbook.

Since it triggers a PHP notice, I think there should be a fair way to avoid it, and I see two ways:
1. Add a note about this in the Gutenberg handbook -> dynamic blocks attributes. (which I fail to find, but I'm sure that I've seen it at some point)
2. Add a default `items` entry as I suggested in this PR https://github.com/WordPress/gutenberg/pull/8538

But it's also good that this issue is here, and other devs won't lose as much time as we did investigate this.

**Comment by danielbachhuber** [comment] 2018-08-06 12:13
> I had similar trouble with it when I first started building blocks, so I think this might be something we can improve in the documentation.

I agree that updating the documentation is the appropriate fix https://github.com/WordPress/gutenberg/pull/8538#issuecomment-410687419

**Comment by prajaktagadhave** [comment] 2018-09-04 13:07
'tm_content' => array(
				'type' => 'array',
				'default' => [],
				'items'   => [
					'type' => 'object',
				],
			),

Is type = > 'object' valid ?? For nested array

**Comment by prajaktagadhave** [comment] 2018-09-04 13:11
what are the valid item types ?

My content will be like this - `array(5) {
  [0]=>
  array(2) {
    ["time_heading"]=>
    array(1) {
      [0]=>
      string(3) "123"
    }
    ["time_desc"]=>
    string(67) "This is Timeline description, you can change me anytime click here "
  }
  [1]=>
  array(2) {
    ["time_heading"]=>
    string(18) "Timeline Heading 2"
    ["time_desc"]=>
    string(67) "This is Timeline description, you can change me anytime click here "
  }
  [2]=>
  array(2) {
    ["time_heading"]=>
    string(18) "Timeline Heading 3"
    ["time_desc"]=>
    string(67) "This is Timeline description, you can change me anytime click here "
  }
  [3]=>
  array(2) {
    ["time_heading"]=>
    string(18) "Timeline Heading 4"
    ["time_desc"]=>
    string(67) "This is Timeline description, you can change me anytime click here "
  }
  [4]=>
  array(2) {
    ["time_heading"]=>
    string(18) "Timeline Heading 5"
    ["time_desc"]=>
    string(67) "This is Timeline description, you can change me anytime click here "
  }
}`

**Comment by matthewbrent** [comment] 2019-08-15 01:25
Its been 11 months since this post - do we still not have documentation for defining the attributes in PHP? I'm using dynamic blocks and i literally cant find solid information anywhere on this. 

Is there anything I can do to speed this along other than searching every inch of the project to see how to format attributes correctly? Specifically objects and arrays, It says something when searching for this the top results are github issue tracs?

**Comment by Alexius08** [comment] 2019-09-06 01:16
> 
> 
> 'tm_content' => array(
> 'type' => 'array',
> 'default' => [],
> 'items' => [
> 'type' => 'object',
> ],
> ),
> 
> Is type = > 'object' valid ?? For nested array

Yes. It worked on my case.

**Comment by ryanwelcher** [comment] 2023-02-07 14:49
I'll pick this up and get some documentation in place ( if this is still an issue )

**Comment by t-hamano** [comment] 2023-12-17 08:54
I would like to close this issue because I was unable to reproduce this issue with the latest version of Gutenberg.

The code I used is below and I also set `WP_DEBUG` to `true`, but no errors were shown in the editor or dashboard.

```php
register_block_type(
	'my-plugin/my-custom-block',
	array(
		'attributes' => array(
			'some_array' => array(
				'type' => 'array',
			),
		),
	)
);
```

**Closed by t-hamano** 2023-12-17 08:54 UTC
Labels: [Type] Enhancement, [Type] Developer Documentation
