### ISSUE TITLE
My Parent Pages Are Still Missing In Gutenberg

### ISSUE THREAD

**Issue by Janatomy** [WordPress/gutenberg#9441] opened 2018-08-29 17:08 UTC
My parent categories are still not displaying when I am building a page using Gutenberg. When I switch to the Classic Editor, the categories are all there.

I read on a few closed threads that this particular issue would be fixed with the next Gutenberg update (3.0 I believe), which seemed as if that was suppose to be sometime last week. I have deactivated and reinstalled my plug-ins, including Gutenberg, but I am still having the same issue.

When can I expect to see this issue resolved?

**Comment by youknowriad** [comment] 2018-08-29 23:10
Do you have a security plugin on your website? Do you Cloudflare?
It can also be a "plugin incompatibility", so you might want to try disabling plugins to find the conflicting one.

**Comment by designsimply** [comment] 2018-08-29 23:36
Noting there's an example of a plugin conflict with iThemes Security at #8763.

I tested with WordPress 4.9.8 and Gutenberg 5a630c2cf (3.7-beta) just now and I am able to see parent categories in Settings (gear icon) > Document when creating a new post.

**Comment by Janatomy** [comment] 2018-09-04 13:18
Sorry for the delay in responding. 

We do have an anti-spam plugin. I have deactivated each plugin, including Gutenberg. The categories only appear when I am using the Classic Editor. I am not familiar with the network tab, but I guess there's no better time than now to become familiar with it.

**Comment by Janatomy** [comment] 2018-09-04 13:18
![screenshot 60](https://user-images.githubusercontent.com/42813163/45033755-7a7a9d00-b023-11e8-886c-dc1768d2978b.png)

**Comment by Janatomy** [comment] 2018-09-04 13:25
I've always created pages (with the Classic Editor, of course). 

Yes - I am referring to the "Parent Page" selector. I have well over 100 categories that I've used to build pages and I definitely don't want to lose them

**Comment by youknowriad** [comment] 2018-09-04 13:28
I can confirm that I personally see the parent page selector, It would be great if you can look for the API request retrieving the pages in the network tab of your browser's console and see what's wrong (what content it returns).

**Comment by Janatomy** [comment] 2018-09-04 13:39
I just remembered this was mentioned in the above comments: "Gutenberg 5a630c2 (3.7-beta)", I will look through it to see if it will help.

**Comment by danielbachhuber** [comment] 2018-09-11 00:48
@Janatomy Were you able to sort this out?

**Comment by Janatomy** [comment] 2018-09-12 17:20
@danielbachhuber - not yet. Actually just getting a chance to sit and look more into it now.

**Comment by Janatomy** [comment] 2018-09-12 18:37
These are the two errors that were flagged. Guidance anyone? I am new to this so any help is appreciated.

![screenshot 63](https://user-images.githubusercontent.com/42813163/45443767-bbae2500-b693-11e8-931b-b1b21edd6107.png)

**Comment by danielbachhuber** [comment] 2018-09-12 20:12
@Janatomy It looks like this is your specific problem:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/36432/45450503-4dfefa80-b68d-11e8-83c3-e0cb7fb9984b.png">

How many pages do you have in total?

Related #6694

**Comment by Janatomy** [comment] 2018-09-12 20:14
I know for sure it's over 200 pages (that includes both parent and subpages)

**Comment by danielbachhuber** [comment] 2018-09-12 20:18
@Janatomy Can you provide a specific count? Here's where you can reference it:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/36432/45450743-f9a84a80-b68d-11e8-9183-47243211ae4f.png">

Also, it would be great if you could switch to the "Network" tab in Chrome Developer tools, find the specific failed API request, and share the full contents of the response. Here's what that looks like on my site:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/36432/45450876-4f7cf280-b68e-11e8-9a8c-9510b96d42d0.png">

**Comment by danielbachhuber** [comment] 2018-09-12 20:33
> I have 416 pages total

Ok, thanks for that.

Can you switch to the "Network" tab in Chrome Developer tools, find the specific failed API request, and share the full contents of the response?

**Comment by Janatomy** [comment] 2018-09-12 20:45
![screenshot 67](https://user-images.githubusercontent.com/42813163/45452152-359dd880-b6ab-11e8-8b34-de1a3a0c9e2a.png)

**Comment by danielbachhuber** [comment] 2018-09-12 20:46
@Janatomy Thanks. Can you look at your PHP error logs to see if there are any relevant details?

**Comment by Janatomy** [comment] 2018-09-14 15:35
I came across this while looking through the plugin editor. Is this missing something, causing it not to pull my categories/attributes that are all in the classic editor?
![screenshot 69](https://user-images.githubusercontent.com/42813163/45560136-4a48b080-b812-11e8-9ee1-b19dec3fa0f4.png)

**Comment by Janatomy** [comment] 2018-10-23 16:11
I am just now getting back to looking into this. I clicked on the link next to the error message that was noted as being the problem above and this is what it says:

{"code":"rest_forbidden_per_page","message":"Sorry, you are not allowed make unbounded queries.","data":{"status":401}}

**Comment by Janatomy** [comment] 2018-10-23 16:12
![screenshot 76](https://user-images.githubusercontent.com/42813163/47374817-db862f00-d6bc-11e8-8332-98af40767ddf.png)

**Comment by catkiinson** [comment] 2018-10-30 21:05
Tags and Categories being inaccessible also appeared in chat #7550526.

**Comment by amoree97** [comment] 2018-10-30 22:54
I am having the same issues with not seeing my categories and my tags are not sticking. I am NOT a fan of Gutenberg. 

I do not have security settings that I know of.

**Comment by designsimply** [comment] 2018-11-29 22:42
I tested with the following steps using WordPress 4.9.8 and Gutenberg 4.5.1:

1. Log in as an administrator.
1. Go to Pages and confirm there is at lease 1 or more published pages.
1. Go to Pages > Add New.
1. Go to Settings > Document > Page Attributes.
1. Check to see if the "Parent Page" option is present.

Result: I can see the option for Parent Page in the document settings sidebar for a site running Gutenberg 4.5.1 with no other plugins.

![screen shot 2018-11-29 at 3 35 44 pm](https://user-images.githubusercontent.com/1119271/49256655-f307b480-f3ec-11e8-9328-b47b821f98cb.png)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post-new.php?post_type=page running WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6.</sup>

@Janatomy are you able to update to the latest version of Gutenberg (currently 4.5.1) and test again?

> Yes - I am referring to the "Parent Page" selector. I have well over 100 categories that I've used to build pages and I definitely don't want to lose them

Pages are not allowed to have categories in WordPress by default. Are you saying categories when you mean parent page or are you perhaps using a theme which has made some modifications to allow categories? 

To confirm, the problem persists for you if you deactivate all other plugins except Gutenberg?

May I ask what theme you are using for reference?

**Comment by designsimply** [comment] 2018-11-29 23:06
@amoree97 I'm really sorry to hear about your troubles! Because Gutenberg on WordPress.com has received some recent updates, may I ask you to try testing categories and tags again and report it to WordPress.com support if you're still having problems? I tested adding categories and tags to a new post on a WordPress.com site just now and was able to do so without any problems. I also made sure I was able to set parent categories for posts and parent pages for pages. I tested using a free site without any plan. To contact WordPress support, first log in at https://wordpress.com/ and then go to https://wordpress.com/help/contact — it will help them to know some steps you're taking right before you see the problem, the full URL of the page where you're testing, and any other relevant details you can think of such as if you've more than several hundred categories or tags saved on your site.

**Comment by amoree97** [comment] 2018-11-30 23:33
When I closed the program and restarted my computer everything was back to
normal. So far it is working, but I am still a long way from being a
Gutenberg fan. It is just not as user-friendly as Wordpress used to be.
Nothing is readily accessible. You have to click to get to things that I
use often and that irritates me to no end.

What was wrong with the old program? I am not sure why people believe that
change for the sake of change is a good thing. (See image) I want to always
see the Document info, and that is not the case. Not a big deal if I only
had to click it once, but I am continually having to reopen that and it is
quite irritating.
[image: Screen Shot 2018-11-30 at 6.11.50 PM.png]

There are things that I use in every book review post (the section for Book
Details) and I have them saved on a page. I have to copy all the sections
one by one to get them to the new page to use them. UGH...the frustration
of that! If I copy and paste from my Notes app, I get a gobbled-dy goop of
junk that I have to clean off to be able to use it. This used to be a very
simple task of fewer than 5 seconds that now takes minutes to complete.

Also, when I add these, instead of just hitting the enter key to add more
text, I have to choose to add a block. Extremely frustrating. Why can we
not just hit the enter key like before and start typing? This is NOT a
change for the better. Any time you add a step to things it is not better,
it is more time consuming and more discouraging and this is making me
really consider looking for a new platform.
[image: Screen Shot 2018-11-30 at 6.25.45 PM.png]

There are also 2 pages (Reviews by Author
<https://propensitytodiscuss.wordpress.com/reviews/reviews-by-author/>
and Reviews
by Title <https://propensitytodiscuss.wordpress.com/book-reviews-list/>)
that I add to with each book review I post. Now it asks if I want to
unpublish these pages to be able to edit them. I do NOT want to unpublish
them and republish because I do not want to send unnecessary notices to my
readers. I just want to add to them and update so that it gets done, but no
one is notified. Not only for the extra notices, but also because sometimes
I add links that are not yet live (scheduled to post later), and I do not
really want to call attention to that.

So, even though the reason that I wrote seems to be fixed, there are other
issues that need to be fixed, or at the very least reverted to what they
were before. Or at least give users a choice as to which platform they
would like to use.


*Alicia Moree*
*Propensity to Discuss <http://propensitytodiscuss.wordpress.com>*

**Comment by Janatomy** [comment] 2018-12-01 18:37
@designsimply - When I mentioned parent categories, I was referring to Parent Page. I have over 400 pages that have been built through the Classic Editor. I am still able, in the Classic Editor, to see all of my pages that have been built and add subpages.

I have already tested by deactivating all plugins except Gutenberg, but the problem still persists. I am currently building my pages using DIVI theme.

**Comment by Janatomy** [comment] 2018-12-01 18:42
My situation - even after the latest Gutenberg update.

Gutenberg:
![screenshot 78](https://user-images.githubusercontent.com/42813163/49331664-ec08af80-f56e-11e8-87aa-267f50284ca9.png)

Classic Editor:
![screenshot 80](https://user-images.githubusercontent.com/42813163/49331672-fc208f00-f56e-11e8-9aa3-a86dde30a3f6.png)

**Comment by ajeet001** [comment] 2018-12-06 21:40
I have updated to wordpress 5.0 today and still I can see only 2 categories out of 14   in gutenberg but classic editor shows all. I tried a couple of troubleshooting given above but no luck,

![classic](https://user-images.githubusercontent.com/30115193/49613458-a5331380-f9cd-11e8-9df4-1e0de4de30ac.PNG)
![gutenberg](https://user-images.githubusercontent.com/30115193/49613460-a5331380-f9cd-11e8-99bf-397d58818f57.PNG)

**Comment by designsimply** [comment] 2018-12-20 23:15
@Janatomy would it be possible for you to temporarily switch to the default theme (Twenty Nineteen) and check to see if the parent pages work normally for you in Gutenberg then? From everything I can see in your notes above, I think the problem may either be a theme conflict or a problem with the REST API based on seeing `{"code":"rest_forbidden_per_page","message":"Sorry, you are not allowed make unbounded queries.","data":{"status":401}}`.

May I also ask what your user role is on the site? Are you an administrator, editor, author?

**Comment by Janatomy** [comment] 2018-12-23 18:13
Will switching to the default theme change the layout of my pages that have already been published?

I am one of the site admins, as well as and editor/author.

**Comment by designsimply** [comment] 2019-01-07 20:32
It should not, however, there is no guarantee. If you are unsure about that step, please make a backup of your site or check with your host to find out if they provide daily backups that you can roll back to in case something goes wrong. The theme may not be the problem but it is something I would consider testing to make sure. The API `rest_forbidden_per_page` error while making changes as a site admin is of more concern.

**Comment by youknowriad** [comment] 2019-01-25 19:08
Anything actionable here, it seems safe to close this issue?

**Comment by bobbingwide** [comment] 2019-01-30 21:22
I've got a similar problem in my development environment. 
Console shows `{"code":"rest_forbidden_context","message":"Sorry, you are not allowed to edit posts in this post type.","data":{"status":401}}`
in response to `https://s.b/oikcom/wp-json/wp/v2/pages?per_page=100&exclude=33789&parent_exclude=33789&orderby=menu_order&order=asc&context=edit&_locale=user`

### Workaround
Use Classic editor

### Notes
- WordPress 5.0.3
- with / without Gutenberg 4.9
- 349 published pages

**Comment by designsimply** [comment] 2019-02-01 23:05
Added the `Needs Testing` label to loop back and ask for additional testing from more testers and noting we should test with ~400 pages and with some page hierarchy involved.

Testing note: using https://jurassic.ninja/ (or a local development environment) may be a good [testing environment](https://make.wordpress.org/test/handbook/get-setup-for-testing/) for this case.

@bobbingwide may I assume your local dev test was using the Twenty Nineteen theme?

**Comment by bobbingwide** [comment] 2019-02-01 23:16
@designsimply no. I was testing with https://github.com/bobbingwide/genesis-oik 
The failure to display any results was due to the 500 internal server error that was produced when the server process reported the Fatal error. This response was ignored by the client. A poor user experience.

**Comment by kraftbj** [comment] 2019-02-22 17:55
On a site with a lot of pages, on the `/pages/` API call, I'm getting a JSON syntax error on the response since the JSON isn't fully returned, which seems to keep the Parent page selector from displaying.

**Comment by kraftbj** [comment] 2019-02-22 18:39
I spent a bit more time with this and figured it out. The site I'm working with has 2400+ pages and I was looking too quickly. It appears that Gutenberg makes multiple requests to the API until all of the pages are returned, limiting each call to 100 items.

After the 25th API request to the `pages` endpoint was returned, the editor displayed the Parent Page selector for me.

Theory: The page selector is actually working, but for sites with a high number of pages (and/or a site where the API is returning relatively slow), it takes so long to render it feels broken.

In my use case, the first thing I wanted to do when starting a new page was set the parent before I forgot. For the API, it took about 2500ms for each response and at 25 responses, that was over a minute before all of the items were returned and the selector was rendered.

Suggestion: If verified, what about some type of loading indicator if nothing else?

**Comment by bobbingwide** [comment] 2019-02-22 21:28
@kraftbj Brandon, see #13618

**Comment by leecollings** [comment] 2019-04-15 10:53
The parent page dropdown still isn't appearing, using the latest versions... why hasn't this been fixed yet?

**Comment by designsimply** [comment] 2019-04-15 20:13
@leecollings it is not happening for all sites and that is one reason why something might be lower in priority over something else. Issues that appear to only apply to some sites or that are difficult to reproduce can take longer than others. It also depends a lot on what else is ahead of it in the queue. For cases like this, it's helpful to note the details of your case when you add a reply. For example, noting the total number of pages on a site you are working with where you can see the problem happen.

**Comment by Clorith** [comment] 2019-05-30 23:11
I'm wondering if loading in all the pages is really the way to go here, or if loading in the X most recent ones and adding a typeahead like search would be a better experience?

**Comment by bobbingwide** [comment] 2019-06-05 09:15
> I'm wondering if loading in all the pages is really the way to go here, or if loading in the X most recent ones and adding a typeahead like search would be a better experience?

The problem is the way the request is being performed. See #13618.

- The browser doesn't need the content nor the excerpt of every page in order to display the page tree. - - But the server processing is being asked to produce this. 
- And for some content it can take a long time to produce the output.
- This can lead to a 500 internal error when the processing is killed due to the elapsed execution time being exceeded. 
- increasing the number of pages being loaded per request will only make the problem worse.
 
Quick edit and the Classic editor have absolutely no problems in listing the pages. 
The REST request needs to be changed.

**Comment by benfruch** [comment] 2019-06-19 09:49
Hello,
I have the same issue. I have more than 2300 pages and I end up having a 503 error during the 12th request of 100 pages after a few minutes.
When I'm on All Pages, I don't have any problem to get the list of parents.
It would be nice to change the REST request that load way too much data.

**Comment by adamsilverstein** [comment] 2019-06-25 23:07
When we have a large number of pages, we can use an accessible autocomplete component to enable search/selecting. See https://github.com/WordPress/gutenberg/pull/7385 where work is ongoing to solve a similar issue with the post author selector for sites with many users.

**Comment by MohammadAlBanna** [comment] 2019-07-10 22:18
It's almost one year ago since this issue is opened but it's still there! Our website has more than 300+ pages and not all pages are listed (even after waiting times). What makes this worse is if we updated a child page with a parent page, the URL will be changed and the value of `parent_page` in the database will be set `0`.

**Comment by adamsilverstein** [comment] 2019-07-18 19:48
I started work on implementing an accessible-autocomplete for sites with a large number of pages in https://github.com/WordPress/gutenberg/pull/16666.

**Comment by CalebWoodbridge** [comment] 2019-09-06 10:36
I have this problem on my WordPress site, which is a University website with thousands of pages. I get a 500 error after around 3 minutes and 50+ pages of calls to the REST API. I can see that the full post data (including content) is being returned, which seems very inefficient.

**Comment by davouid** [comment] 2019-11-18 15:10
I had this problem too, in french and and the accent circonflexe "ê" seems to be the reason why my page did not show up in the attribute >> parent 

Hope it helps

**Comment by pnrma** [comment] 2020-03-03 09:24
I also have this problem but luckily it works using quick modification.
Hoping that @adamsilverstein  work will soon be integrated.

> 
> 
> I started work on implementing an accessible-autocomplete for sites with a large number of pages in #16666.

Thank you for your work to resolve this bug.

**Comment by maowebsolutions** [comment] 2020-05-26 14:23
I was having the same issue seeing the parent selector. I installed this plugin (Disable Gutenberg) and it fixed it.

**Comment by pnrma** [comment] 2020-05-26 14:23
The original message was received at Tue, 26 May 2020 16:23:49 +0200
from vsmtp17.inforoutes.fr [46.18.231.70]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by eshannon3** [comment] 2020-05-26 14:55
@pnrma - that would be a great solution, not requiring all Pages to be queried on page load, but still allowing editors to search for and find any Page they need to select.

@maowebsolutions - hopefully that may help others, but disabling the Block Editor isn't a solution for me. I'm taking advantage of a number of blocks and finding it frustrating that Classic Editor functionality has been lost rather than added to in this case.

**Comment by pnrma** [comment] 2020-05-26 14:56
The original message was received at Tue, 26 May 2020 16:56:06 +0200
from vsmtp17.inforoutes.fr [46.18.231.70]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by eshannon3** [comment] 2020-05-26 14:56
For others who may find this issue, a temporary fix is to apply a filter that forces the REST API to pull more Pages: https://wordpress.org/support/topic/how-to-filter-parent-page-posts_per_page-value-in-gutenberg-editor/#post-12871582

**Comment by pnrma** [comment] 2020-05-26 14:57
The original message was received at Tue, 26 May 2020 16:56:54 +0200
from vsmtp17.inforoutes.fr [46.18.231.70]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Closed** 2020-10-16 07:24 UTC
Labels: [Feature] Document Settings, [Type] Bug, [Type] Performance
