### ISSUE TITLE
Unable to dismiss block inserter panel after inserting a V2 block

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#43090] opened 2022-08-09 13:50 UTC
### Description

After using the block inserter panel to insert a V2 block like the Buttons block, it is not possible to dismiss the panel.

### Step-by-step reproduction instructions

- Start a new post.
- Click on the `+` icon to open the block inserter panel.
- Search for Buttons.
- Select the Buttons block.
- Click on the `x` icon to close the block inserter panel.
- The panel remains visible.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1233880/183873149-ed396187-2d54-41f9-847a-7904a9bef0e1.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-08-17 01:43
Can replicate with Gutenberg Version 13.8.2. This feels like a pretty bad bug considering. Going to flag in #core-editor.

**Comment by glendaviesnz** [comment] 2022-08-17 03:00
Had a quick look to try and see when it was introduced, but was able to replicate as far back as 12.9, so just isolating the cause and fixing in trunk is probably going to be quicker/easier than a git bisect/blame. I probably won't have time to have a closer look until tomorrow, so if someone else wants to take a look in the mean time go for it.

**Comment by priethor** [comment] 2022-08-17 12:36
Thanks @glendaviesnz , it would be great if you could have a look at it 🙂

**Comment by ntsekouras** [comment] 2022-08-17 17:12
Thanks for reporting this @mmtr!

>After using the block inserter panel to insert a V2 block like the Buttons block

What do you mean by `V2 block`?

**For the below text pay attention to the difference of `Buttons`(plural) and `Button` block.

After digging a bit, in order for this to happen, the inserted block needs to satisfy a couple of conditions:
1. Have innerBlocks and use [templateInsertUpdatesSelection: true](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inner-blocks/README.md#templateinsertupdatesselection)
2. Declare allowed blocks that don't contain the parent(for example Buttons allow only the `Button` block

In the main inserter when we insert the block we select it(in the store) but not focus it, so as the inserter remains open. With the above conditions, when we insert let's say the `Buttons` block, it inserts a `Button` block and selects it, making the available blocks in the inserter to be only other `Button` blocks. This makes the original `Buttons` block we clicked unmount and the focus is not restored.

**Comment by glendaviesnz** [comment] 2022-08-18 04:03
I didn't have much time to look at this today, but the PR that introduced the focus criteria for closing [is here](https://github.com/WordPress/gutenberg/pull/24429/files#diff-1c34f42ea9b48a189e8749621eaf9672c4637ee35a26acb807499a6374e2f235R86), and I confirmed that switching back to a simple toggle fixes the issue of it not closing, but reintroduces the focus trap issue that this PR fixed.

**Comment by mmtr** [comment] 2022-08-18 07:33
> What do you mean by V2 block?

A block registered using [the block API Version 2](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-api-versions.md#version-2--wordpress-56). That could have been a wrong assumption from my end though, since I couldn't reproduce this on blocks using the Version 1, but maybe because I was missing the other conditions you noted.

**Comment by youknowriad** [comment] 2022-09-08 13:04
@ntsekouras That makes sense. It seems that we need some kind of focus loss detection in the inserter when it's supposed to stay focused. That said, it's a bit tricky because we rely on the focus loss happening to actually close the inserter in several situations:

 - Ctrl + click on any block for instance

**Comment by Mamaduka** [comment] 2022-12-07 06:43
Do we have any possible solution for this issue? I noticed that this is causing some E2E test failures.

**Comment by ndiego** [comment] 2023-01-26 22:03
Confirmed that this remains an issue in Gutenberg trunk (~15.1)

**Comment by Mamaduka** [comment] 2023-01-27 08:03
Adding this to the WP 6.2 project board's todos.

**Comment by talldan** [comment] 2023-01-30 08:09
This comment from @youknowriad seems to imply that this code is in place to ensure this doesn't happen:
https://github.com/WordPress/gutenberg/blob/6611f8e20f07861b34eac0325a9c960fcbbaf6cd/packages/block-editor/src/components/inner-blocks/use-inner-block-template-sync.js#L108-L109

Something must have changed that caused it to stop working.

For me, I'd question whether selecting the templated inner `button` block is the right thing when inserting from the library. I think the parent should stay selected

It can lead to some weird situations, like if you try inserting four quotes in a row from the library, it actually does something weird where the quotes are recursively nested. I'm not sure the quote block should allow other quotes within it anyway, but still, the issue is that the person inserting the block is not necessarily aware of the context change around where blocks are being inserted.

**Comment by kevin940726** [comment] 2023-02-09 12:08
What's stopping us from calling `setIsInserterOpened( false )` again just to be sure? It might not be the best solution, but at least I think it works. I can put up a PR and add some comments above referencing this issue.

**Closed as completed** 2023-02-10 15:27 UTC
Labels: [Type] Bug, [Priority] High, [Feature] Inserter
