### ISSUE TITLE
Block style previews don't always match final output if block settings are different to those in an example

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#18424] opened 2019-11-11 02:43 UTC
Since the level is set to 2 in the “example” setting of the heading block, H3 and H4 cannot be confirmed on the preview screen of the style panel.

<img width="431" alt="example_setting_of_heading" src="https://user-images.githubusercontent.com/31400297/68556961-aa1f0380-0477-11ea-959d-6336ca94ed59.png">

▼ The following gif image is when the style is changed

![bug_demo_heading_preview](https://user-images.githubusercontent.com/31400297/70298313-8f506c80-1834-11ea-9371-8510fdc5a8c0.gif)

**Comment by ddryo** [comment] 2019-12-06 05:30
The same problem can be seen on the style preview screen of the list block.
Since it is forcibly fixed to the ul tag, the style preview of the ol tag cannot be confirmed.

▼ The following gif image is when the style is changed
![bug_demo_list_preview](https://user-images.githubusercontent.com/31400297/70298414-f3733080-1834-11ea-8b88-c25be6423292.gif)

**Comment by ddryo** [comment] 2019-12-06 05:41
Of course, eliminating the example setting solves this problem, but without the example setting, the preview in the block inserter help menu (.block-editor-inserter__menu-help-panel) cannot be displayed.

I think that there is a problem with the processing method that the "preview screen in the help menu of the block inserter" and the "block style preview screen" refer to the same "example".

I think it would be nice to be able to divide the process well between the two types of preview screens, but I'm not mature enough to come up with a concrete good solution.
I'm sorry, can the core team consider it?

**Comment by ddryo** [comment] 2019-12-06 05:46
Created a plugin that adds a simple block style to heading and list blocks.

I hope you can use it for verification.

▼ The plugin.
[my-guten.zip](https://github.com/WordPress/gutenberg/files/3930618/my-guten.zip)

**Comment by talldan** [comment] 2020-05-14 06:10
Hey @ddryo, Thanks for reporting this and sorry that there hasn't been a reply for a while.

What you mention about the previews not updating is by design. They were previously dynamic, but the issue is that a lot of blocks require content to be previewed so the static `examples` were a way to solve that.

The issue you mentioned with the heading doesn't seem like something the preview could accurately portray. If I remember correctly, the preview is scaled, so increasing the size would probably scale down the preview and it'd look pretty similar.

I see your point in terms of the list block, and probably any block were a setting might change what the block looks like considerably could result in a preview that isn't quite right.

I'll label this as an enhancement, though as you mention it might be something that's difficult to resolve.

**Comment by jordesign** [comment] 2023-08-25 02:50
As this has been sitting formant for 3 years, and the preview mechanism for variations has changed - I'm going to close this issue. If it is still something worth having as an enhancement - we can open a new issue considering the _current_ state of things.

**Closed by jordesign** 2023-08-25 02:50 UTC
Labels: [Type] Enhancement, [Package] Block library, [Block] Heading
