### ISSUE TITLE
Convert to blocks: Gallery shortcode sometimes converted to Gallery block, sometimes to paragraph block with a gallery shortcode

### ISSUE THREAD

**Issue by bluisier** [WordPress/gutenberg#26458] opened 2020-10-26 14:12 UTC
**Describe the bug**
I have quite a lot of Gallery shortcodes in my posts. When I convert my posts from the classic block to Gutenberg blocks, my gallery shortcodes are sometimes converted to gallery blocks, sometimes only to paragraph block with a gallery shortcode in it.

**To reproduce**
1. Create A new post
2. Insert for instance the following html in a classic block:
```
<p>The <strong>Gastlosen massif</strong> (it means inhospitable in english ;) ) is located on the border between the canton of Fribourg and Bern in <a href="http://localhost/en/backpacking-switzerland/">Switzerland</a> (and almost the canton of Vaud too... it is a question of a few kms). <img class="alignright wp-image-15457" src="http://localhost/app/uploads/2019/10/gastlosen.jpg" alt="gastlosen switzerland" width="363" height="561" />In fact, it was our friends Letizia and Raph from the <a href="https://prenezplace.org/" target="_blank" rel="noopener noreferrer">blog Prenez Place</a> who told us about this mountain range 2 years ago when they came to join us on <a href="http://localhost/en/backpacking-switzerland/via-alpina-hike/" rel="">the Via Alpina hike</a>.<br />We must say that they sold us this hike quite well by telling us about landscapes that looked a lot like the famous Dolomites but in Switzerland. So I (Benoît) took advantage of a beautiful Sunday in September to go with my sister and one of my best friends to <strong>hike the Gastlosen</strong> and see if it was up to its reputation :)</p>
<h2>The Gastlosen range : where and what is it?</h2>
<p>As I told you before, the Gastlosen chain is located just above the village of Jaun, practically on the border of the 3 Swiss cantons of Fribourg, Berne and Vaud... it is also the linguistic border of Switzerland (or Röstigraben... the Rösti barrier) so don't be surprised if you hear people speaking Swiss German.</p>
<p>The Gastlosen are best known for 2 things:</p>
<ul>
<li><strong>The grossmutterloch (grandmother's hole)</strong>: It is a hole in the middle of the Gastlosen face. According to the legend, the devil, angry with his grandmother, threw her against the rock which would have made a hole in the mountain ;) . In fact the hole is mostly known to photographers who hurry to come in winter to see and capture the sun's rays passing through this opening (you just have to google Grossmutterloch to see what I'm talking about).</li>
<li><strong>Rock Climbing</strong>: The Gastlosen and its vertical walls are a paradise for climbers in the region (and even the whole world). There are hundreds of different routes, of all difficulties.... Moreover, the best climber in the world, Adam Ondra, even went here to do the path nicely called "physical torture" in 2013 ;)</li>
</ul>
<div class="novobox novobox-transport">
<p><span class="box-title">How to get to Gastlosen?</span>The are several ways to come to the Gastlosen:</p>
<ul>
<li><mark>By public transport</mark>: You can reach the village of Jaun by bus from the city of Bulle and then there is a chairlift that goes up to the feet of the Gastlosen to start the hike. You will find the necessary information on the <a href="https://www.sbb.ch/en/home.html" target="_blank" rel="nofollow noopener noreferrer">website of the SBB</a> (but we have to say that this is not the most accessible place by public transport in Switzerland)</li>
<li><mark>By car</mark>: You can easily drive to the village of Jaun and then drive up to <a href="https://www.buvettesattels.com/" target="_blank" rel="nofollow noopener noreferrer">the Sattels buvette</a>. If you continue perhaps 500m after it, there is an ideal car park to start the hike</li>
</ul>
</div>
<h2>The Gastlosen circle hike</h2>
<p>So I reassure you right away, <mark>you don't need to be a professional climber to enjoy the Gastlosen</mark>. In fact, there is a pretty loop that goes all the way around the mountain range and can be done easily in one day. So that's what we decided to do on this beautiful Sunday in September.</p>
<p>As I mentioned above, it is possible to come by train and bus to the village of Jaun and then take the chairlift that takes you on the Gastlosen Tour trail. But as we had a vehicle, we preferred to go directly to the parking lot just after the Sattels buvette (note that the parking lot was already half full on Sunday morning at 9am... so <mark>if you can come for this hike during the week to avoid the crowd it's better</mark>).</p>
<p>The circuit is doable in both directions but for some reason I don't understand, most people walk counter-clockwise (and start by going to the soldier's chalet). Perhaps in a spirit of contradiction, we decided to do the opposite. So first we go up towards the arrival of the chairlift. The sun is still on the other side of the Gastlosen but we are already passing by a nice viewpoint that has been set up for instagrammers (I think it's more like ruining the landscape but well #GrumpyOldMe ;) )</p>
[caption id="attachment_15452" align="aligncenter" width="795"]<img class="wp-image-15452" src="http://localhost/app/uploads/2019/10/gastlosen-instagram.jpg" alt="Gastlosen instagram" width="795" height="462" /> Well... you can like it or not ;)[/caption]
<p>After the chairlift, we go down a little and then go back up into the forest to the free chalet. We find the sun again by passing on the other side of the massif while enjoying beautiful views of the Fribourg pre-alps.</p>
<p>[gallery ids="15461,15462"]</p>
<p>The next part of the hike consists of following the entire Gastlosen range for perhaps 4-5 km to the Wolfs Ort. The landscapes are really spectacular and we have all the time to observe the many climbers who are climbing different routes (sometimes very impressive). To our left we also have a magnificent view of all the Bernese Alps and we can see very clearly the magical trio of the Eiger, Jungfrau and Mönch mountains.</p>
<p>While walking you can also see the famous grandmother's hole (Grossmutterloch) in one of the Gastlosen walls. I will have to come back once in the winter to admire the spectacle of the sun's rays passing through this opening.</p>
<p>[gallery ids="15468,15465,15466,15467"]</p>
<p>Once we arrived at the Wolfs Ort, we decided to climb a little bit on the left towards <strong>Wandflue</strong> to have a nice view over the whole Gastlosen massif. Unfortunately we didn't have time to climb to the top but frankly halfway we already had a great view. We took advantage of this beautiful view to open a good beer from the <a href="https://7peaksbrasserie.ch/en/home/" target="_blank" rel="nofollow noopener noreferrer">7 peaks brewery</a> that we had taken with us in our backpacks. So frankly if you have the energy, we really recommend you to climb a little up to the Wandflue for the view. Even if the path is steep and a little difficult, you will be rewarded for your efforts ;)</p>
<p>[gallery ids="15473,15474,15472,15471"]</p>
<p>After this well-deserved break we go down to the Wolfs Ort and then continue down to the <strong>soldier's chalet</strong> (which was previously used by the mountain infantry but which offers food and beds today). We intended to sit on the terrace for a while to eat something, but unfortunately there were so many people that we didn't have the courage to wait our turn (I repeat, but try to come during the week if you can). So we continued our way on the track that goes down to the parking lot where we had left the car a few hours earlier.</p>
<p>Instead of the soldier's chalet, we had the good idea to stop and eat a few things at the Sattels buvette, which has a great menu with local and seasonal products. Frankly, we highly recommend it!</p>
[caption id="attachment_15477" align="aligncenter" width="795"]<img class="wp-image-15477" src="http://localhost/app/uploads/2019/10/chalet-du-soldat-gastlosen.jpg" alt="soldier chalet" width="795" height="580" /> the terrace of the soldier's chalet with a very beautiful view of the Gastlosen mountains[/caption]
<div class="infos">
<p><span class="infos-titre">Infos utiles</span></p>
<ul class="infos-liste">
<li><span class="infos-sous-titre">Distance</span> 11-12kms</li>
<li><span class="infos-sous-titre">Deniv.</span> +- 7/800m (It depends on whether you go up to the Windflue or not.)</li>
<li><span class="infos-sous-titre">Difficulty</span> facile (only the part that goes up towards the Windflue can be a little more difficult)</li>
<li><span class="infos-sous-titre">Duration</span> 4-5h</li>
</ul>
<p> </p>
<p><iframe class="gpsies" src="//www.gpsies.com/mapOnly.do?fileId=wwzkyfsfgidmuuor" width="100%" height="400" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
</div>
<p>That's it for this hike! I hope I have made you want to discover the Gastlosen, our little Dolomites of Switzerland. In any case, this first glimpse really made me want to come back with Fabienne once (during the week) to maybe sleep at the soldier's chalet and enjoy the beautiful evening or morning lights in complete quietness. To be continued ;)</p>
<p> </p>
<h3>Pin it on Pinterest</h3>
<p> </p>
<p>[gallery ids="15518,15517"]</p>
```
3. Convert the classick block to Gutenberg blocks
4. With this HTML example, only the last gallery shortcode at the end is converted to a Gallery block, all the others are converted to paragraph blocks with gallery shortcode in it

**Expected behavior**
Either all gallery shortcodes are converted to gallery blocks or to paragraph blocks with the gallery shortcode inside (not a mix of both)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? --> "default"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 82.0

**Comment by annezazu** [comment] 2020-10-26 23:51
@bluisier Thanks for reporting this! I've labeled this appropriately so others can dig in. Of note for anyone trying to replicate, the content above won't work to copy/paste from as the gallery image links won't port over unless you have the images locally on your site. I'd recommend setting up your own test to replicate!

**Comment by talldan** [comment] 2020-10-30 09:53
Just noting that I tested this as part of debugging #26460, the galleries seemed to convert fine, but that was with a more recent version of WordPress and the Gutenberg plugin.

Would be good for more testing, I've reached the end of my day so won't be able to test WordPress 5.5.1.

**Comment by torounit** [comment] 2021-03-30 05:37
@bluisier 

I was not able to reproduce this issue.
I think it has already been resolved at https://github.com/WordPress/gutenberg/pull/28211.

 still experiencing this issue?

**Comment by miminari** [comment] 2021-07-06 05:25
@bluisier

We checked this issue in [Today's triage](https://wordpress.slack.com/archives/C02QB2JS7/p1625548516322000) again, and we think we can close this issue.
If you have more info, please tell us again. Thank you.

**Closed by miminari** 2021-07-06 05:25 UTC
Labels: Needs Testing, [Block] Gallery, [Feature] Block Conversion, [Type] Bug
