### ISSUE TITLE
Post Content behaves inconsistently in Query Loop block

### ISSUE THREAD

**Issue by robglidden** [WordPress/gutenberg#40743] opened 2022-04-29 18:55 UTC
### Description

The Post Content block behaves inconsistently inside a Query Loop block. 

For the first post displayed in the query loop, the content does not display at all.

Sometimes the excerpt instead of the post content displays in the query loop.

### Step-by-step reproduction instructions

1. Create an empty page.
2. For the empty page, create a new template ("Query Loop w Content and Excerpt").
3. In the template put a Query Loop block with both a Post Excerpt and Post Content block.  I separated the 2 blocks into columns to more clearly see what happens.
4. Create a set of simple posts with various combinations of content and excerpts.  I created these posts:

- 1 Content 1 paragraph; Excerpt in Sidebar
- 2 Content 1 paragraph; Excerpt none
- 3 Content after More block; Excerpt before More block
- 4 (same as 1) Content 1 paragraph; Excerpt in Sidebar

5. View the the page, sorting the query loop in the template to both A>Z and Z>A.

6. Notice that:

a) The post content does not appear in the first post listed in the query loop, whether sorted by A>Z or Z>A.

b) If the post has a More block, the excerpt instead of the content appears as content in the template.

### Screenshots, screen recording, code snippet

![template](https://user-images.githubusercontent.com/2780622/166007670-844bee6b-25c8-4eed-abbf-eb5846fafb91.png)
![A to Z](https://user-images.githubusercontent.com/2780622/166007659-5c3f1b13-ee68-449a-aae2-5124274c8550.png)
![Z to A](https://user-images.githubusercontent.com/2780622/166007664-a5b57702-2833-413b-b61d-fecdae6a9f49.png)

### Environment info

WordPress 6.0 beta 3 with theme Twenty Twenty-Two.

Same result in 5.93 and Frost theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-08-16 16:27
Hi @robglidden, this issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Are you able to retest on your end and see if this issue still exists?

**Comment by robglidden** [comment] 2022-08-16 20:32
Hi @ndiego, yes issue still exists in WordPress 6.02, both with and without Gutenberg 13.8.2.

Screenshots below: note that "I am content" appears in template editor, but not on rendered page.

template editor:
<img width="1213" alt="template-editor" src="https://user-images.githubusercontent.com/84926617/184978816-972f4ade-1628-4370-86f8-416b448fb66e.png">

<img width="1223" alt="template-editor-2" src="https://user-images.githubusercontent.com/84926617/184979026-666f278a-8cfd-43af-a867-f202249fbd1c.png">


post-editor:
<img width="1212" alt="post-editor" src="https://user-images.githubusercontent.com/84926617/184978230-ed3c534c-da4e-4ec6-ba05-89f271a174ea.png">

rendered page:
<img width="843" alt="rendered-page" src="https://user-images.githubusercontent.com/84926617/184978279-9c3f961f-9e3d-4ae8-8188-9eeebf649f3a.png">

**Comment by robglidden** [comment] 2022-08-16 20:36
Here is template, if it helps.


<div class="wp-block-columns">
<div class="wp-block-column" style="flex-basis:40%">
<h4>Post Title and Excerpt</h4>
</div>



<div class="wp-block-column" style="flex-basis:60%">
<h4>Post Content</h4>
</div>
</div>



<div class="wp-block-query">

<div class="wp-block-columns">
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:40%">

</div>



<div class="wp-block-column" style="flex-basis:60%"></div>
</div>

</div>

**Comment by robglidden** [comment] 2022-08-16 20:37
oops, I guess templates don't upload correctly.

**Comment by t-hamano** [comment] 2022-08-27 04:44
I was able to reproduce this problem.  

As the following steps show, I think the fundamental problem is not that the content of the first post in the query loop isn't displayed, but **that it is rewritten by the content of that page**.

---

Create multiple posts with content and excerpt as follows:

![post](https://user-images.githubusercontent.com/54422211/187014377-fd2ff6bc-404c-482a-a6f1-09529c9d616b.png)

Create a custom template and set only Post Title, Post Content, Post Excerpt blocks in the query loop block.
Title, content, and excerpt are shown CORRECTLY on the template editor:

![template](https://user-images.githubusercontent.com/54422211/187014524-f4842d2f-c418-44e3-9168-31fa5a1e7a48.png)

Create a page and apply a custom template:

![page](https://user-images.githubusercontent.com/54422211/187014625-df0512b7-d0c1-4226-a4c8-398abbf6c889.png)

The content of the first post is NOT displayed:

![frontend](https://user-images.githubusercontent.com/54422211/187014694-64351850-7374-4534-9250-c558757cda88.png)

Additionally, if the page has the content, the content of that page will appear as the content of the post:

![sample page](https://user-images.githubusercontent.com/54422211/187014853-11a9d67b-6db2-409c-aded-503bdb651553.png)

**Comment by t-hamano** [comment] 2022-08-27 04:58
https://github.com/WordPress/gutenberg/blob/3b6a399cf5f2f82ea49a422d97adf46e8ef5dc01/packages/block-library/src/post-content/index.php#L39-L43

I haven't yet determined the exact cause, but it appears that before and after this conditional statement, the result of `get_the_content` is being rewritten to the content of the page instead of the post in the loop. Perhaps this conditional statement needs to be updated appropriately.

**Comment by sophiegyo** [comment] 2022-10-11 14:05
I ran into exactly this problem today and found myself very baffled by it.

I could reproduce it reliably on WP 6.0.2 with Gutenberg 14.2.0, in three different Site Editor-compatible themes including TT2.

Conditions:

* Create new page (post_type=page)
* Create new _custom template_ in Appearance > Editor
* Add a Query Loop to the custom template, and insert the Post Content block into the Post Template block.
* Save custom template
* Apply custom template to the page I created
* Most recent post will not show post content - that div is simply missing from the HTML
* Older posts are fine

If I offset the Query Loop by one, it still affects whatever is the most recent post shown.
I could not replicate it for a Home/Index template in the site editor, nor if I inserted a Query Loop into a regular page template - it has to be a new custom template. 

Excerpts are fine; it's specifically the Post Content.
![Image showing browser inspector with arrows highlighting lack of post content element](https://user-images.githubusercontent.com/36608681/195114328-fb90b952-5674-4100-a460-5792941885a2.png)

**Comment by frishcat** [comment] 2023-02-17 03:02
Since now ( Feb 17, 2023 ) this bug has not been resolved yet, I met the same issue. some additional information:

> Wordpress 6.11
> Gutenberg 15.1.1
> Theme: Powder or other block themes

1. This issue only found in when close `inherit query from template`, when you open it, it works well. 

2. Temporary solution without update if you want to close `inherit query from template`:
- Create a new post with blank content, set to sticky article
- Put a `post content` block out of and before `query loop block`
- Set this 👆block css: `display: none`
- Set your query loop block `exclude sticky articles`

It seems worked.

**Comment by rbaugh** [comment] 2023-03-15 20:17
I noticed that the `Post Content` and `Post Excerpt` seem to have the same issues at times. Looking at the `Post Title`, `Post Author` and `Post Date`, they all seem to be utilizing the `postId` from the context to get the current `postId` whether it is in the loop or on a current post.

Could this not solve the issue? I was using the `Post Excerpt` inside an InnerBlock that had the parent block assigning the `postId` context value, but it wasn't loading in the excerpt since the current page I added it to didn't have an excerpt. The code for these blocks is checking for the `$block->context['postId']` and bailing if it doesn't exist, but then seems to not use it for getting the data of the post in question.

**Comment by charliecha67** [comment] 2023-03-25 14:27
Hi,

I got the same issue with Twenty Three + WP 6.1.1 and spent so many hours looking for the reason.
I even made a new clean install of my website and started everything from the beginning, step by step, because I thought I did something wrong with the database.... 

So I feel kind of relieved to find these reports of the issue !

It seems that the next version of WP 6.2 -which will be released very soon- won't fix the bug .... (???)

Waiting for that, I use the temporary fix wrote by @frishcat :
- Create post
- Make it sticky Post
- Give it ALL the categories and ALL the tags (for this to work on all archive pages)
- Hide it with post ID in CSS - .post-126{display: none}

Wish the next versions will fix it !
Thank you

**Comment by t-hamano** [comment] 2023-08-31 13:24
I have confirmed that this problem is not reproduced in the latest Gutenberg. Perhaps #49904 resolved the issue. Please test the Gutenberg plugin 16.6, which includes #49904, when it is released.

I would like to close this issue, but if I have missed something, please comment.

Below is a recording of the problem being resolved when the latest Gutenberg plugin is activated, following the test procedure I mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/40743#issuecomment-1229122424).


https://github.com/WordPress/gutenberg/assets/54422211/24e90145-facf-4fc5-a4f3-f4bfd3f652d7

**Closed as completed by t-hamano** 2023-08-31 13:24 UTC
Labels: [Type] Bug, [Block] Post Content, [Block] Query Loop
