### ISSUE TITLE
Inserter: Preview panel not showing up

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#39582] opened 2022-03-18 14:40 UTC
### Description

The `InserterPreviewPanel` component is not showing up when hovering or focusing a block item in the inserter.

#### Notes

- The preview in the Block Transform tool works fine.

- This only happens with the Gutenberg plugin.
WP Core is unaffected, so it's a regression introduced after the merge into 5.9.2.

### Step-by-step reproduction instructions

1. Open the inserter.
2. Move the mouse over any one of the items in the inserter.
3. You'll notice that no preview shows up.

### Screenshots, screen recording, code snippet

| Expected | Actual |
| - | - |
| <img width="680" alt="Screenshot 2022-03-18 at 14 27 29" src="https://user-images.githubusercontent.com/2070010/159021869-8e26982c-3a44-4a5b-9aea-562089d3bb4f.png"> | <img width="660" alt="Screenshot 2022-03-18 at 14 27 37" src="https://user-images.githubusercontent.com/2070010/159021889-d65d41c0-dcf1-4976-8e5f-a1f5f1033255.png"> |

### Environment info

- Tested with Chrome and Firefox on macOS 12.
- The issue happens only with the Gutenberg plugin. Tested with 12.8.0 and 12.8.1, and on the [WP.org Gutenberg Demo](https://wordpress.org/gutenberg/), and [Frontenberg](https://frontenberg.tomjn.com/).
- The issue does not happen without the plugin: WP Core is unaffected.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ironprogrammer** [comment] 2022-03-18 16:26
Hi, @Copons:

This looks like it may have been introduced by https://github.com/WordPress/gutenberg/pull/38893, where `.interface-interface-skeleton__content` is now set to `z-index: 91`. (Original issue: https://github.com/WordPress/gutenberg/issues/38723.)

I tested reverting that PR and the preview is visible again, so this can likely be addressed by adjusting the z-axis position or the slot/fill location for `block-editor-inserter__preview-container`.

**Comment by mtias** [comment] 2022-03-21 12:18
@ironprogrammer can we revert that PR first and address the fallouts separately? It's a significant regression compared to the relatively minor original issue it's trying to solve.

**Comment by ironprogrammer** [comment] 2022-03-21 23:59
#39620 has been created to revert the change that introduced this issue. I'll keep an eye on things and touch base on this item once it drops.

**Comment by youknowriad** [comment] 2022-03-22 08:56
It seems the inserter previews are not something we're e2e checking at the moment, might also be a good addition to our testing pipeline.

**Closed as completed** 2022-03-22 09:33 UTC
Labels: [Type] Bug, [Feature] Inserter
