### ISSUE TITLE
Preview link not working properly

### ISSUE THREAD

**Issue by jankimoradiya** [WordPress/gutenberg#1693] opened 2017-07-04 09:59 UTC
Hello,

Preview does not display refreshed result when user change any content in editor and check it using preview button without saving this changes. It's always open in new tab. I mean when I click on Preview button it is not open in previously opened preview tab. In our current wordpress editor this preview changes is display without update or publish the content and also open in previously opened preview tab.

I have attached a video for your review. 

*Note: Attached video is open in browser.
[preview_button_for_Gutenberg.zip](https://github.com/WordPress/gutenberg/files/1121660/preview_button_for_Gutenberg.zip)

Thanks

**Comment by swissspidy** [comment] 2017-07-04 10:06
> Preview does not display refreshed result when user change any content in editor and check it using preview button without saving this changes.

Duplicate of #1673.

**Comment by karmatosed** [comment] 2017-07-04 13:36
Agree duplicate so closing.

**Closed by karmatosed** 2017-07-04 13:36 UTC

**Comment by kortekconsulting** [comment] 2018-04-25 15:51
Hello, I am having the same issue, and I don't see the answer or solution here, or on the linked #1673 ticket. My wordpress opens a new tab everytime i want to preview changes, and because it's not opening in the old preview tab, it's caching from it. So the only way to preview changes, is to update, rather than preview, and then under caching, i have to purge all. This takes 2 full refreshes of 2 pages, rather than one preview, very frustrating and time consuming when making small modifications. Is it a setting in my wordpress?

**Comment by mrajabtech** [comment] 2018-09-08 11:04
I'm having the same issue. Is there any update on this issue?
