### ISSUE TITLE
Method to be able to have search result with "Reusable Block"

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#16258] opened 2019-06-24 08:37 UTC
**Is your feature request related to a problem? Please describe.**
Yes,
now if we search,
we don't have result of content made in "Reusable Block"…
- [https://github.com/WordPress/gutenberg/issues/14595](url)

**Describe the solution you'd like**
That you create a SQL table where all the "Reusable Block",
have all their links (page where they are used),
so when you search,
it seek in the table where the content of "Reusable Block" are stocked,
and after that with another SQL request,
to display the links in home page…
Simple no ?

**Describe alternatives you've considered**
Not any one pro now.

**Comment by swissspidy** [comment] 2019-06-25 14:15
Thanks a lot for your report.

Since you already mention #14595, which in turn is a duplicate of #3739, which is about this exact issue, I am closing this one as a duplicate.

If you require 100% accurate search results, the best option is to use a dedicated search engine. There are solutions like SearchWP and Elasticsearch which solve this issue.

Adding a separate database table for search is out of scope for the block editor itself, however, feel free to report this as an enhancement for WordPress core at https://core.trac.wordpress.org/.

**Closed by swissspidy** 2019-06-25 14:15 UTC
Labels: [Component] Reusable Blocks, [Status] Duplicate, [Type] WP Core Bug

**Comment by Nemzag** [comment] 2019-06-25 17:57
I use wordpress.com, free blog,
I can't use plugin,
so please add this method pro anyone.
To be able to search content inside "Reusable Block"
Thank you.

**Comment by swissspidy** [comment] 2019-06-25 18:35
If you use WordPress.com, you should report this to them instead of here.

**Comment by Nemzag** [comment] 2019-06-25 18:36
Ok, I will contact them,
but you can also contact them,
you vorg on this project not me.
It's your job not mine.
Jood day.
