### ISSUE TITLE
Navigation editor: Speed issues with saving and loading

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#35046] opened 2021-09-22 13:32 UTC
This is a copy&paste of a [comment by @spacedmonkey from 34541](https://github.com/WordPress/gutenberg/pull/34541#issuecomment-922555964):

---

I wrote a little script that creates a new menu and creates 500 items. This script looks like this. 
```
function create_mock_menu( ) {
	$rand = rand();
	for ($x = 0; $x <= 500; $x++) {
		$test = wp_insert_post( [ 'post_type' => 'nav_menu_item', 'post_status' => 'publish', 'menu_order' => $x,'post_title' => 'Title '.$x ] );
		update_post_meta( $test, '_menu_item_type', 'custom' );
		update_post_meta( $test, '_menu_item_url', '#' );

		wp_set_post_terms( $test, 'Test menu '.$rand, 'nav_menu' );
	}
}
```

My testing, there seem to be some performance issues with saving 500 items. See this video. 

https://user-images.githubusercontent.com/237508/133945695-90bb5931-7474-4dc2-85f0-26cc2aa0aab7.mov

Issues, I spotted. 
1. Loading is very slow and does start render when items are coming in, but waits for all items to load. 
2. When pressing save, the save button should be disabled. 
3. When pressing save, a spinner or other something should show the user that menu is saving.

**Comment by spacedmonkey** [comment] 2021-09-22 14:05
Is this is a duplicate of https://github.com/WordPress/gutenberg/issues/34999 ?

**Comment by Mamaduka** [comment] 2023-03-19 07:37
Closing the issue since the editor is no longer maintained and has been removed from the project.

**Closed as completed by Mamaduka** 2023-03-19 07:37 UTC
