### ISSUE TITLE
Gutenberg Gallery images not updating after delete

### ISSUE THREAD

**Issue by guesttttttt** [WordPress/gutenberg#33741] opened 2021-07-29 05:47 UTC
I've started using the gutenberg gallery, but noticed when you upload the images to the gallery of gutenberg, and then decide to delete 1 image, it doesn't update it. 

## Step-by-step reproduction instructions
1.Create a post
2.Insert gutenberg gallery block with several images which you upload after clicking upload files
3.Post it, then decide that one of the images are not correct
4.Go to Media>Select one of the images and click Delete
5.When you go to the post thebrowser says 404 for that image
6.When you edit the post you can clearly see a missing image
7.To update it you have to delete it from the block itself

## Expected behaviour
To update the image

## Actual behaviour
The browser says 404

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Not sure
- Are all plugins except Gutenberg deactivated? - No
- Are you using a default theme - No

## Device information
- Device: Desktop
- Operating system: Windows 7
- Browser: Chrome

**Comment by johngodley** [comment] 2021-08-02 14:23
Are you deleting the image from the media library? This would seem to be expected behaviour, and deleting media won't update the posts that reference that media. The same would apply to any block that uses media.

**Comment by guesttttttt** [comment] 2021-08-02 16:37
Yes, i am deleting images from the media library.

**Comment by johngodley** [comment] 2021-08-03 06:01
Thanks. For me this seems to be expected behaviour. I wouldn't expect deleting an item from the media library to also update content - the image could be used in multiple blocks across multiple posts and to be consistent they would all need updating. That sounds like a lot of unexpected, and potentially damaging, changes to perform when deleting an image.

**Comment by jasmussen** [comment] 2021-08-05 13:16
Thanks for the ticket, thanks for the response. I'm closing this one as it appears to be working as intended. 

An alternative would be to rephrase this "are you sure" text that's shown when deleting an item to be more verbose:

<img width="436" alt="Screenshot 2021-08-05 at 15 15 28" src="https://user-images.githubusercontent.com/1204802/128356170-80830932-6fb6-4877-a40c-27f71e5b181d.png">

I'm not sure if that's necessary, but if yes then it would need to be reported on https://core.trac.wordpress.org/.

**Closed as completed by jasmussen** 2021-08-05 13:16 UTC
