### ISSUE TITLE
Preview in new tab does not reflect on block removal

### ISSUE THREAD

**Issue by naumanahmed19** [WordPress/gutenberg#49909] opened 2023-04-19 01:09 UTC
### Description

"Preview in new tab" option does not autosave when removing blocks and still shows content from previous revision.

### Step-by-step reproduction instructions

1: Add a new **paragraph** block
2: "Preview in new tab"
3: remove block 
4: Preview in new tab again, the block will be still there 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2023-04-19 04:11
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/48717

**Closed as completed by glendaviesnz** 2023-04-19 04:11 UTC
