### ISSUE TITLE
Add Classic    -   This block has encountered an error and cannot be previewed.

### ISSUE THREAD

**Issue by thewebarea** [WordPress/gutenberg#4919] opened 2018-02-07 11:14 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Soean** [comment] 2018-02-07 11:41
@thewebarea Thanks for your report. We need a little more informations to reproduce an solve the error.

What where your steps to produce this error? 
Have you just added an Classic Block?
Do you see an error in the console log?
Are you using a fresh installation or any special theme and plugins?

**Comment by thewebarea** [comment] 2018-02-12 10:22
![error](https://user-images.githubusercontent.com/9139543/36092249-5ccc88d8-0fef-11e8-9f47-09d3abafde13.jpg)
![console](https://user-images.githubusercontent.com/9139543/36092250-5cee1070-0fef-11e8-8165-91a7f8fe0b30.jpg)

**Comment by thewebarea** [comment] 2018-02-12 10:24
I just added a Classic Block.
I use Theme UnderStrap.
ACF Plugins.

**Comment by zakoops** [comment] 2018-02-21 18:25
With Gutenberg version 2.2.0, I'm having the same problem (tested with Safari and Chrome).

But as soon as I deactivate the ACF plugin, the _Classic_ block is working again, back on track.

So at least we can probably pinpoint the problem to the presence of this plugin.

My first small grain of salt... (all new to GitHub here).

**Comment by youknowriad** [comment] 2018-03-21 16:49
When you use meta boxes, a second version of TinyMCE is loaded conflicting with the one used by default by the classic blocks. This kind of issues will be closed once we merge in Core and align the TinyMCE scripts used. Right now we're loading two scripts.

see #3840

**Comment by danielbachhuber** [comment] 2018-06-04 13:11
This will be fixed by #6848

**Closed by danielbachhuber** 2018-06-04 13:11 UTC
Labels: [Type] Plugin / Theme Interoperability

**Comment by meymigrou** [comment] 2018-06-16 19:47
I'm having the same problem with a test blog that I have. No other plugins installed expect Gutenberg. Any ideas on how to fix it? It shows the error in every block in every article (published, trashed or drafted).

**Comment by soerencarl** [comment] 2018-06-18 07:42
![gutenberg_issue](https://user-images.githubusercontent.com/40351523/41523581-bc12b542-7304-11e8-9b7a-d119736fde85.png)
I have the same error as @meymigrou "This block has encountered an error and cannot be previewed.". It seems to be only a display problem. If I go on View Page I can see everything as described in the Code Editor as well: "
<figure class="wp-block-image"><img src="https://810union.com/wp-content/uploads/2018/06/placeholder-1.jpg" alt="" class="wp-image-184" /></figure>
". But in the View Editor I can not see anything. How can I change that? Is it maybe a problem related to the Theme I am using? The Preview Button as well only leads to an about:blank site. That is not very useful at the moment. I hope it will change soon as I believe in Gutenberg Editor is a very nice project and once it would work smoothly would led me change from wix to wordpress.

**Comment by meymigrou** [comment] 2018-07-22 15:05
@peterluit @Soean  I don't understand why they closed this issue ticket. There are a lot of people having the same problem. I even asked the theme creator and he told me that the problems occur from the Gutenberg plugin. They should fix that. I'm having the same problem in two websites right now.

If anyone has found a way to fix the problem, they should tell us. I'm only using the Gutenberg plugin on my WordPress website, so deactivating any plugins won't work for me.

**Comment by peterluit** [comment] 2018-07-22 19:39
OK, let me explain the issue here and the possible solution. I am on Plesk and the latest Plesk version does supply an enormous amount of protections. So the wp-includes folder will be protected against external execution of php files (if you set all protections on). There is one files there: wp-tinymce.php which is needed by Gutenberg. If you use the Plesk protection, you will see the error message, caused by the fact that this file cannot be executed (error 403, if you use 'inspect' in Chrome'.
![beeld 329](https://user-images.githubusercontent.com/6135068/43049376-3f39a3b0-8df7-11e8-98d4-63a8c22f3d8f.jpg)

OK, the solution, switch off the protection of the wp-includes folder and add the following in an independent .htacces file in the wp-includes folder:

<FilesMatch "\.(?i:php)$">
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
</FilesMatch>
<Files wp-tinymce.php>
  Allow from all
</Files>
<Files ms-files.php>
  Allow from all
</Files>

Please let me know if you have any questions.

Peter

**Comment by ryancwalsh** [comment] 2018-08-11 14:53
I keep getting these "This block has encountered an error and cannot be previewed." errors too. I haven't been able to get the simple official editable example https://github.com/WordPress/gutenberg-examples/tree/master/03-editable to work.

I first had to change `title: __( 'Example: Editable', 'gutenberg-examples' ),` to `title: __( 'Example: Editable'),` because of some error about a domain not being found. But other than that, I think my files are clones of that repo example.

**Comment by crabilld** [comment] 2019-01-30 22:36
For me, there was a problem in wp-includes. Downloading a fresh install of Wordpress, and replacing my wp-includes folder solved the problem. Apparently, sometimes the problem is with wp-includes/.htaccess. That wasn't the problem for me, but you might want to check that first.
