### ISSUE TITLE
Convert to 2,3,4 column to 1 Column in Mobile View,

### ISSUE THREAD

**Issue by dhwalin** [WordPress/gutenberg#7742] opened 2018-07-06 09:26 UTC
How can I convert multiple column content to 1 column in Mobile view? It looks very weird when I add 4 columns in content & they show side by side even in mobile.

Please guide how can I change layout by desktop and mobile?

**Comment by SuperGeniusZeb** [comment] 2018-07-08 23:34
Duplicate of #6048. See also: #7315.

**Comment by designsimply** [comment] 2018-07-09 20:31
Please keep in mind that the Columns Block is still in beta. 🙂 I tested the beta columns block and didn't find a way to set the numbers of columns, however, since this block is in beta and since there's already a discussion about making it responsive, I am closing this issue in favor of #6048 and I will make sure to note your question on that issue.

![screen shot 2018-07-09 at mon jul 9 2 22 57 pm](https://user-images.githubusercontent.com/1119271/42474337-89a526a4-8384-11e8-9da6-447ff4f6ba42.png)
<sup>Seen at http://alittletestblog.com/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Chrome 67.0.3396.99 on macOS 10.13.5.</sup>

**Closed by designsimply** 2018-07-09 20:31 UTC
Labels: [Status] Duplicate, [Type] Help Request

**Comment by chrisvanpatten** [comment] 2018-07-09 20:32
@designsimply you need to have the containing "Columns" block selected to change the number of columns. In your screenshot, you have a nested "Column" block selected. (It's a subtle but key change.)

**Comment by designsimply** [comment] 2018-07-18 17:17
@chrisvanpatten thanks! Found it! Screenshot for reference:

![screen shot 2018-07-18 at wed jul 18 11 04 29 am](https://user-images.githubusercontent.com/1119271/42896982-cb30b63a-8a7b-11e8-9cf4-a6a71e2e57af.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13886&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Also wanted to note that I was focusing on the UI before, but really the answer to this question is that a decision needs to be made about if/whether/how the columns block will behave on small screens (responsiveness), which is being discussed in #6048 so we're still good to go with closing this one as a duplicate. 👍

Current front-end view with the Atomic Blocks theme (to document the current state):

![screen shot 2018-07-18 at wed jul 18 11 04 42 am](https://user-images.githubusercontent.com/1119271/42897019-ea32990e-8a7b-11e8-9374-843630b15ca7.png)
<sup>Seen at http://alittletestblog.com/2018/07/18/columns-block-beta-test/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

<img src="https://user-images.githubusercontent.com/1119271/42897024-ed3c8eca-8a7b-11e8-923d-53b56c8d35d3.png" width="270" alt="screen shot 2018-07-18 at 11 05 13">
<sup>Seen at http://alittletestblog.com/2018/07/18/columns-block-beta-test/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Pixel, Android 8.1.0.</sup>
