### ISSUE TITLE
Quote block: CSS regarding "is-style-big" from WordPress 6.0 breaks existing styles.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#41219] opened 2022-05-23 03:12 UTC
### Description

With WordPress 6.0, the level of detail in the CSS regarding `.wp-block-quote.is-style-large` is too strong.

It is changing from `.wp-block-quote.is-style-large` to `.wp-block-quote.is-style-large:not(.is-style-plain)`.

Specifically, the following CSS.

```
.wp-block-quote.is-style-large:not(.is-style-plain), .wp-block-quote.is-large:not(.is-style-plain) {
    margin-bottom: 1em;
    padding: 0 1em;
}
.wp-block-quote.is-style-large:not(.is-style-plain) p, .wp-block-quote.is-large:not(.is-style-plain) p {
    font-size: 1.5em;
    font-style: italic;
    line-height: 1.6;
}
.wp-block-quote.is-style-large:not(.is-style-plain) p, .wp-block-quote.is-large:not(.is-style-plain) p {
    font-size: 1.5em;
    font-style: italic;
    line-height: 1.6;
}
```

I understand that the change is due to Large style being removed in [37580](https://github.com/WordPress/gutenberg/pull/37580), but the impact on existing styles is too strong.

As one example, the theme I am developing will be affected as follows.

Before
<img width="870" alt="スクリーンショット 2022-05-23 12 08 44" src="https://user-images.githubusercontent.com/31400297/169735982-97ee082a-95b4-48ab-81ce-545d61d1a879.png">

After
<img width="872" alt="スクリーンショット 2022-05-23 12 09 48" src="https://user-images.githubusercontent.com/31400297/169736001-3f9e91bd-1f4c-4f50-a55d-642c2971f0f1.png">

Previously, we could simply prepare CSS with the same level of detail in `.wp-block-quote.is-style-large` and load it later than the core style, but starting with 6.0, you need to write it as `.wp-block-quote.is-style-large.is-style-large`.

As discussed at [#40163](https://github.com/WordPress/gutenberg/issues/40163), it would be better to use `:where`.

### Step-by-step reproduction instructions

.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ddryo** [comment] 2022-05-23 03:21
I understand that we can make the selector stronger and adjust it on the theme side.

However, if that is really the only way to do it, I think it would be better to remove the `is-style-large` CSS altogether.

That way, the amount of CSS can be reduced without changing the amount of work on the part of the theme developer.

**Comment by markhowellsmead** [comment] 2022-05-23 10:26
See also #40159, #36135, #35840, #34047, #29705, #17511 and #39971.

**Comment by carolinan** [comment] 2022-08-03 07:45
I will close this as a duplicate of #40163.

**Closed as not planned by carolinan** 2022-08-03 07:45 UTC
Labels: [Status] Duplicate, [Block] Quote, CSS Styling
