### ISSUE TITLE
Block: New Slider Block that can slide other blocks

### ISSUE THREAD

**Issue by ahmadbaig1** [WordPress/gutenberg#39412] opened 2022-03-13 20:00 UTC
## What problem does this address?
The core blocks currently lack a feature-rich slider block.

Things which cannot be done for now-
* Sliding multiple images at once (sliding group of 3 images for example).
* Having a logo slider
* Sliding a combo of image and text

## What is your proposed solution?

I am requesting a Slider block, that can have other blocks inside it to make a slideshow of.

For example, we have the Cover block, that allows us to add other blocks inside it, the same way, we could have a Slider block, that allows us to slide various blocks or a combination of them. A few possibilities-

Slide Media and Text blocks- Have a beautiful carousel of an image and related text as a slideshow.
Slide Column blocks- If we can slide a column block, we could show three rows of text in a slideshow, that can be used as a testimonial showcase
Slide Gallery blocks- We can create a nice company logo slider that many users seek to implement. Ex plugin- [Logo Slider](https://wordpress.org/plugins/logo-slider-wp)
Slide Video blocks- We can have a slider that shows videos/gifs as a slideshow.

**Comment by carolinan** [comment] 2022-03-25 05:14
I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/34075.
You may also be interested in
https://github.com/WordPress/gutenberg/issues/25502
https://github.com/WordPress/gutenberg/issues/25501

**Closed as completed by carolinan** 2022-03-25 05:14 UTC
Labels: New Block, [Status] Duplicate
