### ISSUE TITLE
custom class support for shortcode block

### ISSUE THREAD

**Issue by anischarolia-multidots** [WordPress/gutenberg#17142] opened 2019-08-22 10:07 UTC
**Is your feature request related to a problem? Please describe.**
"Shortcode" blog doesn't have support to add custom classes. So, when in need we would not be able to add custom classes to specific shortcode.

**Describe the solution you'd like**
Custom class support can be provided to "shortcode" block.

**Comment by youknowriad** [comment] 2019-08-22 10:37
Duplicate of #16420

You can now add a shortcode block inside a Group block with a custom className. The shortcode block itself doesn't have any markup by default (depends on the shortcode), so it's not really possible to add a className directly to it.

**Closed by youknowriad** 2019-08-22 10:37 UTC
