### ISSUE TITLE
Column Range Control Values Should be filterable

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#11985] opened 2018-11-16 15:19 UTC
**Is your feature request related to a problem? Please describe.**
The values for min and max on the Range Control component with the column block is fixed. There should be a way to filter this either from JS or PHP.

**Describe the solution you'd like**
I'd like to see this filterable via a theme_support function in PHP, but a way to set this in JS would also be okay.

**Describe alternatives you've considered**
The only way we can use core columns in our large organization is if we can maintain control of their allowed depth. Since this isn't possible in core, we would have to build a custom column solution.

**Comment by youknowriad** [comment] 2019-02-01 15:25
duplicate of #10791

**Closed by youknowriad** 2019-02-01 15:25 UTC
Labels: Needs Technical Feedback
