### ISSUE TITLE
Uploading image in an existing gallery gives an error on Autosave/Save Draft

### ISSUE THREAD

**Issue by khushbooinani** [WordPress/gutenberg#10218] opened 2018-09-27 17:01 UTC
**Describe the bug**
Using Gutenberg 3.9 Pre Release
Uploading an image to an existing gallery in the editor gives The response is not a valid JSON response error on autosave as it's not uploaded in the Media yet.

**To Reproduce**
1. Add a gallery with a single image in the editor.
2. Click on the gallery and then Upload an image button.
3. Upload an image.
4. Newly uploaded image will appear in the gallery.
5. Click on save draft.
6. See the error.

**Expected behavior**
If the uploaded image is not saved in Media, then we should display a progress bar instead of image. So user will not try to save draft as it's still uploading.

**Screenshots**
![img2](https://user-images.githubusercontent.com/16896677/46161825-38501e80-c2a4-11e8-818c-c87b538a3c70.png)
![img2-1](https://user-images.githubusercontent.com/16896677/46161833-3d14d280-c2a4-11e8-9c32-3081375165d2.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by designsimply** [comment] 2018-09-27 19:10
Thank you for reporting this! I think it's a duplicate of the report in #8935 and so I'd like to consolidate there. I tested and I was unable to see the same problem happen using your steps, so my guess is that there's possibly something blocking image uploads (or large image uploads?) either through your connection or on your web server where your site is hosted. If you are able to keep working together to uncover details, it would be helpful to post the following in a comment on #8935:

* Size of the image being uploaded.
* The API response for the media upload in your browser's web developer tools Network panel.
* The details from the Server section in Dashboard > Health Check > Debug if you are able to install the Health Check plugin.

Here is the result from my test for reference which also shows the successful media API response in the Network panel. I tested using WordPress 4.9.8 and Gutenberg 3.9.0 and Firefox 62.0 on macOS 10.13.6:

<img width="1280" alt="screen shot 2018-09-27 at 3 03 51 pm" src="https://user-images.githubusercontent.com/1119271/46168764-6105f300-c267-11e8-99bc-aa2538181de7.png">

**Closed by designsimply** 2018-09-27 19:10 UTC
