### ISSUE TITLE
Content doesn't consistently save

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1292] opened 2017-06-20 08:09 UTC
After performing some adhoc content changes such as inserting text, adding headings, adding blockquotes, moving blocks up and down, the page will no longer update. I tried clicking the _Save_ link and also the _Update_ button, and neither worked.

**Comment by aduth** [comment] 2017-06-20 17:47
Are there a specific set of steps you can put together that consistently puts you in this state, so that we can try to reproduce?

Can you try opening your browser's developer tools console to see if you find any error messages you could share here? ([Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console), [IE](https://msdn.microsoft.com/library/dn255006(v=vs.85).aspx), [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3), [Safari](https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html#//apple_ref/doc/uid/TP40007874-CH2-SW1)).

**Comment by mtias** [comment] 2017-08-18 20:14
Closing this for now due to lack of details. Feel free to open a new one if issues persist.

**Closed by mtias** 2017-08-18 20:14 UTC
Labels: [Status] Needs More Info, [Type] Bug
