### ISSUE TITLE
Navigation block: How to add a new, clean Nav block?

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#18355] opened 2019-11-07 00:21 UTC
**Describe the bug**
I was trying to add a brand new Nav block to my post, but every time it would automatically initialize with my current nav items already added. How do I add a new Nav without any items to my post?

**To reproduce**
1. Make sure you have a Menu already created.
2. Add a Navigation block.
3. Observe that items are already added to the block and there is no way to start with a clean new Nav block.

**Expected behavior**
I expect to be able to add a new Nav block that doesn't contain any items. I couldn't figure out how to do this. I didn't see an option to clean out all my items. Maybe we should add something like this?

**Screenshots**

![add-nav 2019-11-06 16_17_15](https://user-images.githubusercontent.com/617986/68349250-62802c80-00b1-11ea-8f44-784e4ee6648f.gif)

**Desktop (please complete the following information):**
 - OS Catalina
 - Firefox 70.0.1
 - Gutenberg 6.8

**Comment by mtias** [comment] 2019-11-07 12:20
Closing as duplicate of #18307.

**Closed by mtias** 2019-11-07 12:20 UTC
Labels: Needs Design Feedback, [Block] Navigation Menu
