### ISSUE TITLE
Edge case: Invalid content can disappear

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#12350] opened 2018-11-27 09:39 UTC
**To Reproduce**
1. Go to [Frontenberg](https://frontenberg.tomjn.com/)
2. Switch to Code editor
3. Delete all content
4. Paste this content:
```
<!-- wp:paragraph -->
<!-- wp:paragraph -->
<p>Paragraph</p>
<!-- /wp:paragraph -->
<!-- /wp:paragraph -->
```
5. Content completely disappears after you unfocus the Code editor, switch to Visual editor, or do anything really (on the bright side there is still a validation error in the console).

**Expected behavior**
Of course this is an absolute edge case that shouldn't really happen, but it still is a concerning thing that content can just take off and leave without any warning or message (other than console).

For example I'm adding a tool to my WP installation that wraps the old post content in `<!-- wp:html -->` so it doesn't load in the Classic editor block that removes indentation and adds `<p>` and `<br>` tags everywhere. If my code messed up and ran the action twice, it would make everything disappear when I open the post in Gutenberg for the first time.

So if it's possible that 3rd party developers may develop such tools that alter/convert/etc the post content and happen to do it wrong then it can result in unexpected content losses if this is not handled properly.

Expected behavior would be a similar message as `This block contains unexpected or invalid content` that currently happens when block content is manually altered.

**Comment by dreamwhisper** [comment] 2018-11-29 16:48
[Related issue](https://github.com/WordPress/gutenberg/issues/12275) where content containing invalid HTML is removed without notification to the user.

**Comment by ellatrix** [comment] 2019-11-14 08:32
This may be a duplicate of #12350?

**Comment by talldan** [comment] 2024-07-24 04:53
Closing as a duplicate of #10980

**Closed by talldan** 2024-07-24 04:53 UTC
Labels: [Type] Bug, [Priority] Low, [Feature] Parsing
