### ISSUE TITLE
In Microsoft Edge, Custom Fields are not saved when "Save Draft"

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#25596] opened 2020-09-24 02:03 UTC
_Originally reported in https://core.trac.wordpress.org/ticket/45843._

In Microsoft Edge only, when I create a new post and add a Custom Field, the Custom Field is not saved when I save the draft.

Even when a Custom Field was saved to the post (e.g., in Chrome browser, or pressing "Add Custom Field" button in either Chrome or Edge), the Custom Field(s) get erased upon "Save Draft" in Edge.

It works properly in Chrome.

Problem has only existed upon WordPress update to version 5.x with Gutenberg editor. Custom fields were saving properly in Edge in all earlier versions.

**Comment by AshiqKiron** [comment] 2021-03-02 05:59
Just tested the issue on Edge Version 88.0.705.81 (Official build) (64-bit) couldn't reproduce.

**Comment by talldan** [comment] 2021-03-02 06:01
Same here. I was unable to reproduce this when testing. Closing the issue as resolved.

**Closed by talldan** 2021-03-02 06:01 UTC
Labels: Browser Issues, Needs Testing, [Feature] Custom Fields
