### ISSUE TITLE
Custom padding control doesn't accept float values

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#34849] opened 2021-09-15 16:25 UTC
### Description

It's not possible to set customPadding to e.g. 0.5vw using the editor control. Only integers are accepted.

### Step-by-step reproduction instructions

1. Try and set e.g. 0.5vw or 1.25rem as a custom padding value.

### Environment info

- WordPress 5.8.1
- Gutenberg plugin is not in use.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment] 2021-09-15 16:39
Hi, 
Thanks for reporting. 

This was fixed in https://github.com/WordPress/gutenberg/pull/32692 . 

I'm not able to reproduce this using the newest version of the Gutenberg plugin either so please reopen if you're able to reproduce this with the plugin. This probably should be included in WP 5.9. :)

**Closed as completed by skorasaurus** 2021-09-15 16:39 UTC
