### ISSUE TITLE
Template parts do not load in the full-site editor. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#27072] opened 2020-11-18 14:03 UTC
**Describe the bug**

Template parts that had previously been loading fine using Gutenberg 9.3 are no longer loading in 9.4. 

**To reproduce**

1. Activate a block-based theme that uses block template parts.
2. Visit the full-site editor. 
3. Check to see if the template parts load. 

**Screenshots**

![spinning](https://user-images.githubusercontent.com/1202812/99539883-cbfd7100-297c-11eb-92c2-63f59b8b28af.gif)

Tested with Gutenberg 9.4, and a handful of block-based themes ([Twenty-Twenty One Blocks](https://github.com/WordPress/theme-experiments/tree/master/twentytwentyone-blocks), [Seedlet Blocks](https://github.com/Automattic/themes/tree/trunk/seedlet-blocks), etc.)

**Comment by kjellr** [comment] 2020-11-18 14:08
cc @noahtallen since you noted something similar in https://github.com/WordPress/gutenberg/pull/26383#pullrequestreview-529606052

**Comment by ockham** [comment] 2020-11-18 14:37
As always, let's add some e2e coverage for this when fixing (however minimal -- just to make sure this stuff loads).

**Comment by kjellr** [comment] 2020-11-18 15:08
Upon further testing: I'm still able to reproduce this on all of my usual local test sites, using both `master`, and `9.4-rc1`. But if I spin up a fresh, live testing site it seems to work ok. 😩 There's a possibility it's just a me problem, though I've heard similar reports in other contexts lately. 

I'm curious if others can reproduce.

**Comment by jffng** [comment] 2020-11-18 15:29
I can reproduce this locally on `master`. 

The requests for the template parts return a 200 status, but the response is empty. 

<img width="1186" alt="Screen Shot 2020-11-18 at 10 25 53 AM" src="https://user-images.githubusercontent.com/5375500/99550341-a1191a00-2988-11eb-91ec-71e1590bea5c.png">

Please let us know if there is other info we can provide to help debug, thank you!

**Comment by noahtallen** [comment] 2020-11-18 17:00
I came across this here: https://github.com/WordPress/gutenberg/pull/26383#pullrequestreview-530467717 and thought it was an issue in the PR. I guess folks thought it got fixed before merging? Could also be somewhere else, but that was the only place I noticed it.

**Comment by vindl** [comment] 2020-11-24 16:57
This is a result of https://github.com/WordPress/gutenberg/pull/27016. We changed the way of tagging templates with themes (from meta to taxonomies), and they no longer work with old sites created with 9.3. This can be resolved by cleaning the CPTs locally. Since FSE is experimental feature we are not planning on providing migration code in Gutenberg to fix this automatically.

**Closed by vindl** 2020-11-24 16:57 UTC
Labels: [Feature] Full Site Editing, [Feature] Themes, [Type] Regression
