### ISSUE TITLE
A way to get all defined blocks from the rest-API / php

### ISSUE THREAD

**Issue by janw-oostendorp** [WordPress/gutenberg#3024] opened 2017-10-16 07:43 UTC
Currently most core blocks are defined in `gutenberg/blocks/build/index.js` and `gutenberg/editor/build/index.js` (PS I'm using the plugin from dotorg)

I want to set up some conditionals depending on what blocks are in a post. And I want a user to select which blocks are allowed. But for that I need to fill a select with the blocks.

It's doable to fill the select with JS if you `wp_enqueue_script( 'wp-blocks' );` on the pages you need, but then you are loading most of gutenburg on that page just to get the blocks.
I've red the way to add [new blocks](https://github.com/WordPress/gutenberg/tree/master/blocks)

Shouldn't there be an other way to do this?
Putting this in the rest API seems like a nice way to do this.

**Comment by aduth** [comment] 2017-10-16 20:00
Yes, it's been proposed that all blocks should have some amount of a server definition. Considering this as a duplicate of #2751, but the reference will prove valuable as a concrete use-case. Thanks!

**Closed by aduth** 2017-10-16 20:00 UTC
