### ISSUE TITLE
Block Insertor: Option to add block above the first block is missing

### ISSUE THREAD

**Issue by sunnyssr** [WordPress/gutenberg#30470] opened 2021-04-02 13:39 UTC
## Description

Can you make
```div.block-editor-block-list__insertion-point.is-vertical```
clickable and add the insert block option when you mouse over the top of the first block please? The add block option is missing now. We have to add a block below the first block then move it up everytime instead of just adding a block at the top. All the other positions are okay. Just the first one is missing.

## Step-by-step reproduction instructions

1. Go to the Gutenberg editor
2. Add multiple blocks on the page.
3. Try to insert block above the first block
## Expected behaviour

There should be an option to insert block before first block just like in other blocks.
## Actual behaviour

No options shows up to insert block before first block.
## WordPress information
- WordPress version: 5.6.1 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device:  
- Operating system: 
- Browser: 

Upstream from [Ticket #52532 on WordPress Trac](https://core.trac.wordpress.org/ticket/52532)

**Comment by talldan** [comment] 2021-04-12 03:23
Thanks for reporting this in the right place.

**Comment by a4jp-com** [comment] 2021-10-27 16:04
The title here is "Block Insertor: Option to add block above the first block is missing". I think the problem is totally different from "Inserter: Inline inserter is difficult to discover and use #22801". Why does that case number show up as closed here? https://github.com/WordPress/gutenberg/issues/22801#issuecomment-940941469

Did it just automatically link here?

The top inserter isn't showing up in Wordpress. Chrome Version 95.0.4638.54 (Official Build) (64-bit) & other browsers; Windows 10/iOS.

**Comment by talldan** [comment] 2021-10-28 01:44
@a4jp-com This issue is still open.

#22801 is a different issue.

**Comment by a4jp-com** [comment] 2021-11-17 13:12
Is there anyone that can look at this problem?

**Comment by youknowriad** [comment] 2024-10-24 12:58
This is a duplicate of #27540

**Closed as completed by youknowriad** 2024-10-24 12:58 UTC
Labels: [Type] Enhancement, [Feature] Inserter
