### ISSUE TITLE
How to let users search for content in Gutenberg

### ISSUE THREAD

**Issue by maxhartshorn** [WordPress/gutenberg#7356] opened 2018-06-18 21:17 UTC
We make use of the Media Explorer plugin to let users search and embed custom content into our posts
https://github.com/Automattic/media-explorer (screengrab below)

This plugin essentially lets you build an interface for users to search and embed content, in the same way that all users can search and embed images.

Our problem is that this plugin is not compatible with Gutenberg and it is not apparent if it ever will be. Is there a Gutenberg approved way to do something similar?

Blocks seem like a great tool for embedding a certain type of content, but I see no way within the block interface to let users search through entries in a custom post type.

I'm curious to know what the Gutenberg solution to this problem will be, as I am sure others have similar functionality.

![mexp](https://user-images.githubusercontent.com/8988954/41562488-cc49c8e0-731a-11e8-912c-dcb8e522ee9e.JPG)

**Comment by danielbachhuber** [comment] 2018-06-19 00:11
Hi @maxhartshorn,

Is this issue a duplicate of #6523?

**Closed** 2018-06-26 13:55 UTC
Labels: [Status] Needs More Info
