### ISSUE TITLE
Mobile UI for moving blocks, switching type, and formatting

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#44] opened 2017-02-09 23:18 UTC
Steps to reproduce:

1. Go to https://wordpress.github.io/gutenberg/ using an Android device.
1. Tap on a content block to select it.
1. Try to move the block to a new location.

<strong>Result:</strong> the options to move a block seem to be hidden off-left. (<a href="https://cloudup.com/cvBBTFpMLz1">14s</a>) I expected to be able to drag and drop the content blocks from an edit mode of some sort, as https://github.com/WordPress/gutenberg/issues/38 suggests.

Tested with Chrome on a Pixel with Android 7.1.1.

**Comment by jasmussen** [comment] 2017-02-10 09:00
Mobile is very important to the editor project, but hasn't been a focus quite yet. No reason that can't change. Here's a very early draft for how the block and inline level formatting controls, as well as the type switcher and block move controls could work on mobile:

![mobile](https://cloud.githubusercontent.com/assets/1204802/22820595/b7f94c6c-ef77-11e6-80c2-f647d0410943.png)

**Comment by jasmussen** [comment] 2017-02-14 09:26
I took the liberty of renaming the ticket, to make it our canonical "consider mobile UI" ticket.

Here's a new mockup:

![mobile](https://cloud.githubusercontent.com/assets/1204802/22922988/031695a8-f2a0-11e6-99a0-2df2b7e42d12.png)

**Comment by diegoliv** [comment] 2017-02-14 13:25
@jasmussen great prototypes! I think that the first one is better, for two main reasons:

1. The first one takes less screen space than the second one, so you can see more of your content and less UI. This is critical on mobile.

2. When you have the controls at the bottom of the screen on mobile, the user is more confortable to do everything with one hand. Take a look at this article about bottom "navigation" (https://uxplanet.org/perfect-bottom-navigation-for-mobile-app-effabbb98c0f) and this one about how users hold mobile devices (http://www.uxmatters.com/mt/archives/2013/02/how-do-users-really-hold-mobile-devices.php).

By the way, keeping the formatting options "attached" to the keyboard feels more intuitive.

**Comment by jasmussen** [comment] 2017-02-14 13:41
Great thoughts @diegoliv. I do completely agree with having navigation bottom-side when possible, which is why that was my first instinct also. However @afraithe reminded me that it isn't actually possible to know when the soft-keyboard is open on mobile, and so we can't actually calculate where to place the bottom toolbar. To put it differently, if we added `position: fixed; bottom: 0;` to the toolbar, it would be covered by the keyboard when that popped up. 

If we were building an app it would be a different thing of course :D 

If new developments have happened in the mobile CSS space, would be cool to revisit this, but I think sadly we're stuck with a top-bound toolbar for now.

**Comment by hypest** [comment] 2017-02-15 16:17
Hey @jasmussen, thx for the mobile mocks! May I ask, do I read it correctly that the block/inline formatting options only appear when text is already selected?

**Comment by jasmussen** [comment] 2017-02-15 16:23
> May I ask, do I read it correctly that the block/inline formatting options only appear when text is already selected?

Something to explore when we get to this point, probably. Alternatively they could be grayed out.

**Comment by nheagy** [comment] 2017-02-15 16:59
@jasmussen This looks great!

> However @afraithe reminded me that it isn't actually possible to know when the soft-keyboard is open on mobile, and so we can't actually calculate where to place the bottom toolbar

I'd love to make sure this is (still) true. Seems the problem is iOS Safari wasn't always adjusting the viewport correctly. I'd love to find out if that's been fixed… maybe I'll make an attempt at it.

**Comment by jasmussen** [comment] 2017-02-15 17:05
> I'd love to find out if that's been fixed… maybe I'll make an attempt at it.

😍 There's a 🌟 emoji in it for you!

**Comment by sirbrillig** [comment] 2017-02-15 17:41
> However @afraithe reminded me that it isn't actually possible to know when the soft-keyboard is open on mobile, and so we can't actually calculate where to place the bottom toolbar

@nheagy the last time I worked on this, the first challenge was that Android Chrome and Mobile Safari behave differently:

- On Android, when the keyboard slides up it collapses the viewport height to the remaining available screen height, which actually is helpful because a fixed-bottom element will appear just above the keyboard.
- On iOS, when the keyboard slides up it covers the viewport, meaning that in order to position an element above the keyboard, it must be absolutely positioned at the right place on the page. This means that it is necessary to determine the height of the keyboard. Since iOS now supports different keyboards, and the native above-keyboard tools may or may not be present, this is quite a lot of guess work (there are some hacks which make it possible but they are not pretty and could break at any time).

Secondly, as Joen said, it's quite hard to determine if the device has the keyboard shown at all. There are also cases when the keyboard is "shown" but it is not actually visible, such as when an external bluetooth keyboard is being used.

All of which is to say that I think it's still a good idea in the current state of the web to use top-fixed elements whenever possible.

**Comment by shaunandrews** [comment] 2017-02-23 20:43
Made a few GIF's walking through typing and adding a new block on mobile:

![gutenberg mobile typing](https://cloud.githubusercontent.com/assets/191598/23278194/aca15c76-f9de-11e6-8665-a92e86a26a53.gif)

![gutenberg mobile block adding](https://cloud.githubusercontent.com/assets/191598/23278221/bcca49fa-f9de-11e6-95c2-c0a7a80eca1d.gif)

**Comment by annaephox** [comment] 2017-04-01 00:30
A summary of [where TinyMCE is headed with mobile capability](https://www.ephox.com/blog/tinymce-is-going-mobile/) (and what we learned from making Textbox.io, a fully accessible, professional quality text editor for mobile)

**Comment by jasmussen** [comment] 2017-05-22 12:01
Closing this in favor of individual tickets: https://github.com/WordPress/gutenberg/labels/%5BComponent%5D%20Mobile

**Closed by jasmussen** 2017-05-22 12:01 UTC
Labels: Design, [Type] Question
