### ISSUE TITLE
Gutenberg page editor is becoming dirty for no reason

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3995] opened 2017-12-14 08:35 UTC
**Steps to reproduce**
* Create a page using Gutenberg, adding only the page title.
* Save the page and reload (browser refresh).
* Click the paragraph block right below the page title without doing anything else.
* Try to refresh the page (browser refresh).

**This is what I see**
![dirty](https://user-images.githubusercontent.com/1268089/33982741-4e2ba4f8-e0ba-11e7-9b85-833e2be18bcc.png)

For some reason the editor becomes dirty.

I cannot reproduce this on the posts edit page.

**Comment by youknowriad** [comment] 2017-12-18 11:34
When you click the empty placeholder, it creates a new paragraph. The content did change from "" to "<p></p>". This could be improved by adding a specific-case for the paragraph block but I think this is an "ok" tradeoff for now.

**Comment by aduth** [comment] 2018-01-10 15:17
Duplicate of #1501

**Closed by aduth** 2018-01-10 15:17 UTC
