### ISSUE TITLE
Theme.json: Heading in selectors aren't set correctly at the block level

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/gutenberg#48706] opened 2023-03-03 00:06 UTC
### Description

A font size was [added](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/theme.json#L201-L206) to the heading of our customized block in theme.json.

```
"wporg/table-of-contents": {
    "color": {
	"background": "var(--wp--preset--color--blueberry-4)",
	"text": "var(--wp--preset--color--blueberry-1)"
    },
    "typography": {
	"fontSize": "var(--wp--preset--font-size--small)"
    },
    "elements": {
	"heading": {
            "typography": {
		"fontSize": "var(--wp--preset--font-size--normal) !important"
	     }
	}
    }
}
```

It is expected to generate something like `.wp-block-wporg-table-of-contents h1, .wp-block-wporg-table-of-contents h2, .wp-block-wporg-table-of-contents h3, .wp-block-wporg-table-of-contents h4, .wp-block-wporg-table-of-contents h5, .wp-block-wporg-table-of-contents h6.` But we saw these instead:

![image](https://user-images.githubusercontent.com/18050944/222592774-f046f2ac-bd8c-42cf-a44d-bcf02518d8ba.png)

This would affect all h2-h6 headings on the page.

### Step-by-step reproduction instructions

1. Add font size to the heading of customized block.
2. It would generate styles that affect all h2-h6 headings on the page.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/theme.json#L202-L206

### Environment info

- WP version: 6.2-beta4-55456
- GB version: 15.2.4
- Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-03-05 07:38
I was able to reproduce it. This problem can be reproduced **when the latest Gutenberg plugin is activated**. We may not have backported any core changes to the plugin.

This also occurs in the core block. For example, the following applies a style to elements in a group block:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		}
	},
	"styles": {
		"blocks": {
			"core/group": {
				"elements": {
					"heading": {
						"typography": {
							"fontSize": "20px"
						}
					},
					"button": {
						"typography": {
							"fontSize": "20px"
						}
					},
					"caption": {
						"typography": {
							"fontSize": "20px"
						}
					}
				}
			}
		}
	}
}
```

From this theme.json definition, the following styles are generated:

```html
<style id='wp-block-group-inline-css'>
.wp-block-group h1,
h2,
h3,
h4,
h5,
h6{
	font-size: 20px;
}
.wp-block-group .wp-element-button,
.wp-block-button__link{
	font-size: 20px;
}
.wp-block-group .wp-element-caption,
.wp-block-audio figcaption,
.wp-block-embed figcaption,
.wp-block-gallery figcaption,
.wp-block-image figcaption,
.wp-block-table figcaption,
.wp-block-video figcaption{
	font-size: 20px;
}
</style>
```

As you can see, if an element has multiple selectors, the selector of the parent block is added only to the first selector.

**Comment by t-hamano** [comment] 2023-03-05 08:33
As far as I can tell, #47833 is involved.

**Comment by ndiego** [comment] 2023-03-05 14:22
Moving this issue and the associate PR to the [6.2 Project Board](https://github.com/orgs/WordPress/projects/63). It seems like an important issue to get fixed by release if we can.

**Comment by t-hamano** [comment] 2023-03-05 14:28
@ndiego
I believe this issue is specific to the Gutenberg Plugin. This is because the source of this problem resides in `lib/class-wp-theme-json-gutenberg.php`, which is not part of the core, as seen in #48759. This problem should not reproduce on WordPress 6.2 Beta.

**Closed as completed** 2023-03-06 10:10 UTC
Labels: [Type] Bug, Gutenberg Plugin, Global Styles
