### ISSUE TITLE
List items temporarily appear more apart after saving the post

### ISSUE THREAD

**Issue by wvega** [WordPress/gutenberg#13183] opened 2019-01-04 12:50 UTC
List items on a List Block are visually more apart after saving (Save as Draft, Update or Publish) the post. The items return to their normal position when the List Block gains focus or clicking on it if the block already had focus.

![list-block](https://user-images.githubusercontent.com/45068/50687974-62c31d80-0ff1-11e9-809b-524d9756c208.gif)

Reloading the Edit Post screen also shows the items in their normal position.

The appearance of the list on the frontend doesn't seem to be affected.

**To reproduce**

1. Add a New Post.
2. Add a List Block with two or more items.
3. Click Save Draft.

**Expected behavior**

The appearance and position of list items is not changed.

**Desktop:**
 - OS: macOS
 - Browser:
     - Safari 12.0.2 (14606.3.4)
     - Google Chrome 71.0.3578.98 (Official Build) (64-bit)

I was able to reproduce the same behavior on two different WordPress installations:

* WordPress 5.0.2 running latest version of [Responsive](https://wordpress.org/themes/responsive/) theme.
* WordPress 5.0.2 running a custom and pretty outdated theme.

**Additional context**

- Both websites are using the version of Gutenberg included in core.

**Comment by ClarusDignus** [comment] 2019-01-28 14:09
Very same issue reported/observed here:

https://wordpress.org/support/topic/new-editor-buggy-empty-list-items-added-after-publishing-updating-post-page/

Upon saving, it's possible to click in the newly created undesired space before/after list items.

See cursor: https://imgur.com/a/LCOlvnt

**Comment by youknowriad** [comment] 2019-02-11 12:32
I can't reproduce this personally. Maybe it's has been fixed with the latest RichText refactorings. I'm closing please reopen if you find how to reproduce in master.

**Closed by youknowriad** 2019-02-11 12:32 UTC
Labels: History, [Block] List, [Type] Bug
