### ISSUE TITLE
Some user Documentation would be nice. 

### ISSUE THREAD

**Issue by steveangstrom** [WordPress/gutenberg#13736] opened 2019-02-07 13:40 UTC
Clients are asking me for support on Gutenberg.  I looked for User level support, guidance or handbook on using Gutenberg and I could not find one. Essentially I want to send them to the "New WP Editor User manual"  so they can look up topics such as "how to convert a heading" or "shortcuts".

**Places I looked for a manual**
https://wordpress.org/support/plugin/gutenberg/  (is a support request forum, not docs)
https://wordpress.org/plugins/gutenberg/#faq  (outdated links)
https://wordpress.org/gutenberg/handbook/  (is developer and designer guides only)
https://wordpress.org/gutenberg/ (is a demo of the new editor)

and more like that, but I cannot find a _user_ manual for documentation for this editor anywhere. There are a lot of dev docs.

**Describe the solution you'd like**
A manual for users to learn how to use the editor. Or if one exists - add it into the pages linked at the top of this post.  Even better - have it linked to the editor itself inside wp-admin !   A help button.

**Describe alternatives you've considered**
Searching Google endlessly. Combing the support threads, and GH tickets, ancient and modern.
There's no real coherent guide to using the editor anywhere.
Searches such as "wp Gutenberg handbook" "wp new editor user docs" "manual wordpress getting started gutenberg" , etc. will return a variety of 3rd party op/ed pieces and old tickets.

**Comment by skorasaurus** [comment] 2019-02-07 19:31
Agreed; it's another reason that I've held off my organization from migrating to it; our concerns would be addressed by the User Handbook https://github.com/WordPress/gutenberg/issues/11252
but it still doesn't appear to be done....

**Comment by youknowriad** [comment] 2019-02-08 16:22
Closing as duplicate of #11252

**Closed by youknowriad** 2019-02-08 16:22 UTC
Labels: [Type] Documentation
