### ISSUE TITLE
alignfull/alignwide classes not applied in editor, only on frontend

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19331] opened 2019-12-26 03:41 UTC
**Describe the bug**
`alignfull` and `alignwide` alignment options are not reflected by the block classes in editor.
These classes are only applied to their element counterparts in frontend.
Edit: Even worse, manually added classes `alignfull` and `alignwide` are automatically removed when saving.

**To reproduce**
1. Add `align-wide` theme support.
2. Add group element in Gutenberg editor.
3. Select `full` or `wide` alignment option for that group element.
4. Inspect the group element in editor and notice that it gets no class for `alignfull` or `alignwide` assigned to it, on frontend however the class is assigned to the element for that block.
The element is still somehow styled by the editor (inline) to become somehow wide or full aligned, but the theme can't optimize or change this process using the appropriate classes for CSS.

**Expected behavior**
`alignfull` and `alignwide` classes are correctly applied to block elements in editor as they are already in frontend, too. Edit: And that these classes `alignfull` and `alignwide` aren't removed automatically during editor save.

**Comment by strarsis** [comment] 2020-02-03 19:48
As a workaround, I have to provide separate styles for the editor (but not editor-styles!), 
that override some of the frontend styles:
```scss
.wp-block[data-align=wide] {
    & > .is-block-content {
      & > .wp-block-group {
        // some specific max-width, etc
      }
    }
  }
}
````

**Comment by strarsis** [comment] 2020-02-03 20:17
For clarifying: Some themes may have a different interpretation of "wide" alignment.
In my case for some group block styles the outmost group element extends to 100% width, no max-width constraints and provide a background, while the inner content got a max-width.

**Comment by talldan** [comment] 2020-02-04 08:38
Duplicate of #18644

**Closed by talldan** 2020-02-04 08:38 UTC
