### ISSUE TITLE
Paragraph: paste contents at cursor point rather than as new blocks

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#53076] opened 2023-07-27 20:04 UTC
Hat tip @richtabor for the text and video: When selecting, copying, and pasting, across more than one paragraph block, the selected contents are not pasted at the cursor point. Unexpectedly, the contents are pasted as new blocks. 

The expectation is that one pastes the copied contents of more than one block, right where the cursor is. The contents should inherit the attributes of the pasted-in paragraph. 

https://github.com/WordPress/gutenberg/assets/26996883/6f5b7d5b-b2f8-424c-b82b-9e0d21b662b6

cc @ellatrix for consideration as you weave your way through writing flow issues.

**Comment by ellatrix** [comment] 2023-08-08 08:45
Could you elaborate more on what you're expecting? Yes, currently, for multiple blocks, we split the paragraph into two at the caret, and then insert the pasted blocks in between.

Do you expect all content to be inlined? Do you expect only the first pasted block to be merged with the first split block, and then last pasted block to be merged with the end of the split?

More visually:

This is your clipboard:

```
Paragraph one

Paragraph two

Paragraph three
```

This is your content with a caret:

```
Existing‸ post.
```

What do you expect when you paste the two paragraphs?

What happens now:

```
Existing

Paragraph one

Paragraph two

Paragraph three

 post.
```

Is this what you expect?

```
ExistingParagraph one

Paragraph two

Paragraph three post.
```

**Comment by richtabor** [comment] 2023-08-10 01:56
> Is this what you expect?

<img width="818" alt="CleanShot 2023-08-09 at 21 55 59" src="https://github.com/WordPress/gutenberg/assets/1813435/345f95e0-6b73-4665-a673-6d05ea6d3265">

Yes. :)

**Comment by ellatrix** [comment] 2023-10-04 20:17
@richtabor What if you replace `Paragraph one` with a heading `Heading one`? What should happen? My current PR does this:

```
Existing

**Heading one**

Paragraph two

Paragraph three post.
```

**Comment by richtabor** [comment] 2023-10-04 21:18
### Into 

If pasting _into_ an existing paragraph block, I'd expect the new contents to inherit the new block:

```
<p>Existing‸ post.</p>
```

with a clipboard of 
```
<h2>Heading one</h2>
<p>Paragraph two</p>
<p>Paragraph three.</p>
```

to be

```
<p>ExisitingHeading one post.</p>
<p>Paragraph two</p>
<p>Paragraph three.</p>
```

### Replace 

If replacing an existing paragraph block entirely, I'd expect the origin contents to remain in as intended. Below I'm emulating selection on the entire first paragraph block.

```
[<p>Existing post.</p>]
```

with a clipboard of 
```
<h2>Heading one</h2>
<p>Paragraph two</p>
<p>Paragraph three.</p>
```

to be

```
<h2>Heading one</h2>
<p>Paragraph two</p>
<p>Paragraph three.</p>
```

**Comment by ellatrix** [comment] 2023-10-04 21:35
Yeah, then there's also the difference when selecting the contents of a paragraph vs the paragraph.

Ok, and what if you paste into a heading? :)

**Comment by richtabor** [comment] 2023-10-04 22:47
> Ok, and what if you paste into a heading? :)

I think it's fine to work exactly the same way as above, where the difference is replace v. inserting within.

**Comment by ellatrix** [comment] 2023-10-05 09:51
@richtabor No, I meant for the first case, if you have a collapsed selection. Should the heading disappear for the second part?

**Closed as completed** 2024-05-03 10:56 UTC
Labels: [Type] Bug, [Feature] Paste, [Feature] Writing Flow, [Block] Paragraph
