### ISSUE TITLE
Dragging Widget or block over text widget and letting go pastes text

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26226] opened 2020-10-16 21:46 UTC
**Describe the bug**
When I dragged the Tag Cloud and happened to be over a Text widget’s text area when I let go of it, the text went into the Text widget instead of moving the Tag Cloud widget.

**To reproduce**
1. Go to Widgets Screen
2. Classic Text widget should be in widget area
3. Add a Tag Cloud (probably not limited to this specific block or widget)
4. Drag Tag Cloud over text widget and let go

**Expected behavior**
Widget or block should not paste the text into the text widget.

Originally reported here: https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40016

**Comment by draganescu** [comment] 2020-11-10 11:00
I wasn't able to test this because the classic editor throws an error on master in the widgets screen.

**Comment by kevin940726** [comment] 2021-01-14 09:17
It's still unclear whether we should add support for the classic widget in the widgets screen: https://github.com/WordPress/gutenberg/issues/15916#issuecomment-702543307.

**Comment by Mamaduka** [comment] 2021-04-13 06:02
I was able to reproduce this issue using the following steps:

1. Add Text widget in Classic Widget editor.
2. Activate the Gutenberg plugin.
3. Add Tag Cloud.
4. Dragged Tag Cloud over text widget and let go.

**Screenshot**
![CleanShot 2021-04-13 at 09 49 26](https://user-images.githubusercontent.com/240569/114503820-eba07900-9c3e-11eb-808f-4da2b8cea7ce.png)

We discussed this issue during the triage session, and a possible solution is to ignore text area when dragging a block.

Discussion link - https://wordpress.slack.com/archives/C02QB2JS7/p1618293123294400

**Comment by adamziel** [comment] 2021-06-22 15:48
I found that the text widget remains in editing mode only as long as I keep editing it (keep focus inside). As soon as I click on the tag cloud (or anywhere else), it defaults to the preview mode. While this doesn't solve the problem of dropping blocks in textareas, it seems good enough to close this issue.

**Closed by adamziel** 2021-06-22 15:48 UTC
Labels: [Feature] Widgets Screen, [Type] Bug
