### ISSUE TITLE
Provide some way of editing ALL theme templates and template parts

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36403] opened 2021-11-11 11:32 UTC
## What problem does this address?

Prior to 11.9.0 one could edit all of the active theme's templates and template parts in the "Editor".

Now as of 11.9.0 we seem to be able to only edit Index template, and Header and Footer template parts.
Clicking 'Browse all templates' now takes us to 'Appearance' > 'Templates' where only the edited templates that previously been saved in the database are available.
There does not seem to be any way of editing the theme's .html templates, so we're now stuck in a catch-22 situation where we can only edit the previously saved templates, but they will not be available until they have been edited, and with no way to edit them in the first place.
## What is your proposed solution?

Please bring back the ability to edit a theme's templates and template parts.

**Comment by Sandstromer** [comment] 2021-11-11 11:38
OK so I found these issues; https://github.com/WordPress/gutenberg/issues/36325 & https://github.com/WordPress/gutenberg/issues/35994

Is the intention to make all templates and template parts available at 'Appearance' > 'Templates' with the editing done in the post editor, rather than the site editor?

Will the site editor be removed, and we just have the styles editor in future?

**Comment by Sandstromer** [comment] 2021-11-11 11:49
Apologies if this issue is just adding more noise and is not needed.

I now found this issue too; https://github.com/WordPress/gutenberg/issues/29630

It seems a little bit weird to drop template editing when this new way is not yet ready, forcing us to roll back to 11.8

If someone with better knowledge of these issues thinks this issue is not needed, please close it out.

**Comment by jameskoster** [comment] 2021-11-11 14:20
Ultimately this feels like a duplicate of https://github.com/WordPress/gutenberg/issues/35994, would you agree?

**Comment by Denis74F** [comment] 2021-11-11 14:24
Hi, in my opinion this is a problem to be solved, because not having the possibility to modify the templates, penalizes a lot its development and the development of the themes.
For example, I made a template for a homepage. I create a "Home" page and set this template, but then if the user does not have the possibility to modify it, it makes no sense to pursue this path.

**Comment by jameskoster** [comment] 2021-11-11 14:25
Agreed, and #35994 will resolve that 🙂

Edit: Y'all may also be interested in this work-in-progress PR: https://github.com/WordPress/gutenberg/pull/36379

**Comment by Denis74F** [comment] 2021-11-11 14:34
Hi @jameskoster ,
I have read the various comments, and I must say that I am very confused as to which is the best solution.
What I hope is that they will be given the opportunity to modify them.

**Comment by jameskoster** [comment] 2021-11-11 15:37
The main point is that #35994  – once closed – will also resolve the problems outlined in this issue. So I'll close this one for now. If y'all have anything to add please contribute in #35994 :)

**Closed as completed by jameskoster** 2021-11-11 15:37 UTC
