### ISSUE TITLE
Navigation block: error when setting custom color

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#18799] opened 2019-11-28 04:32 UTC
**Describe the bug**

When setting a custom color in the Navigation block, the message Notice: `Array to string conversion in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/navigation.php on line 80` is output to the published page.

**To reproduce**
1. Add a Navigation block to a post;
2. Set a custom color for the block;
3. Check preview, or publish and check published post.
4. See error message printed above nav.

**Expected behavior**

Expected no error to be output to the front end.

**Comment by murshed** [comment] 2019-11-28 05:18
Checked and got the issue [https://i.imgur.com/8WqWn0H.png](url)

**Comment by frontdevde** [comment] 2020-01-09 14:40
@tellthemachines I followed your instructions and couldn't reproduce the issue on my end on the current master. If possible, could you test with the current master and tell if the issue still persists? If so, any further information on how to reliably reproduce the issue would be appreciated.

**Comment by frontdevde** [comment] 2020-01-09 14:50
Looks like the file got moved since and the issue was resolved in https://github.com/WordPress/gutenberg/pull/18883

h/t @marekhrabe who dug this up

**Closed by frontdevde** 2020-01-09 14:50 UTC
Labels: [Block] Navigation, [Type] Bug
