### ISSUE TITLE
Media/Image does not insert at cursor in Classic Block

### ISSUE THREAD

**Issue by JessBoctor** [WordPress/gutenberg#12804] opened 2018-12-11 17:12 UTC
**Describe the bug**
When trying to add media within the Classic Block, the media is inserted at the top of the text rather than where the cursor is placed

**To Reproduce**
1. Go to 'Edit/New Post'
2. Add a 'Classic' block
3. Enter some text
4. Place your cursor below or within your text
5. Click on 'Add media' button from the 'Classic' block toolbar
6. Select your media item, click 'Insert into post'
7. Media will be inserted before any text, not where the cursor placement is

**Expected behavior**
It is expected that the media would be inserted where the cursor was placed.

**Screenshots**
<img width="697" alt="ce-block-bug-1" src="https://user-images.githubusercontent.com/12505355/49817327-c32daa80-fd24-11e8-98f6-1253a130e68b.png">
<img width="673" alt="ce-block-bug-2" src="https://user-images.githubusercontent.com/12505355/49817328-c32daa80-fd24-11e8-8560-e0186f78053f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.11.6
 - Browser: Chrome
 - Version 71.0.3578.80 (Official Build) (64-bit)

**Additional context**
Tested on:
- WordPress 5 installed on ServerPress localhost site
- WordPress Calypso on a WordPress.com site.

**Comment by annestk** [comment] 2018-12-12 12:53
Seems like a duplicate of #10509 which will be fixed by #12415 in the next update

**Comment by swissspidy** [comment] 2018-12-12 13:11
Thanks for the link, @annestk! I knew I have stumbled upon that issue before 😄 

Closing as a duplicate of #10509.

**Closed by swissspidy** 2018-12-12 13:11 UTC
Labels: Media, Needs Testing, [Block] Classic, [Status] Duplicate
