### ISSUE TITLE
FSE: Alignment options missing on Columns block added to new or existing templates

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/gutenberg#41579] opened 2022-06-07 15:59 UTC
### Description

As expected, block alignment options (such as Full-Width) are present on Column blocks that already exist in templates and template parts or when added within blocks that already exist within the default content. However, if you add a **new** Column block to an existing template or to a new template part, the alignment options are not present.

I expect to be able to set an alignment on any Columns block, added anywhere, in any template.

Reported in this forum thread:
https://wordpress.org/support/topic/stretching-row-for-the-footer/

### Step-by-step reproduction instructions

First, activate a FSE theme. I tested with both Twenty Twenty-Two (v.1.2) and Archeo (1.0.8). Here are instructions for replicating with Twenty Twenty-Two:

1. Go to Appearance > Editor
2. Click the W logo at top left
3. Click Template Parts
4. Click Footer (I also tested with the Header block and the same problem is there)
5. Select the outermost Group block
6. Choose Insert Before

![Editor__beta__‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/172425040-c30b6120-9449-48e4-8a9b-3719b8ef2862.jpg)

7. Click the block inserter icon and add a Columns block, with any split, such as 50/50
8. Look at the block toolbar and see how there is NO alignment icon, so you can't set an alignment on the Columns block:

![Editor__beta__‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/172425739-68a44a1f-c60e-466c-85f5-597e498c3302.jpg)

I also tested adding a **new** Footer template, and the same problem is present. I also tried Grouping the Columns block, in case that was a factor, but it did not result in the alignment options appearing.

Note that this problem does **not** exist if you add a Columns block within the default content in the same template. As you can see here, the alignment options are present:

![Editor__beta__‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/172426416-49cbf8cd-3362-4c6a-b050-463c82363ede.jpg)

### Screenshots, screen recording, code snippet

See above

### Environment info

WP 6.0
Gutenberg plugin **not** active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-06-09 06:20
Hi!
This is a known usability problem with how the layout and alignment settings work.
What you are describing is not a bug, it is intentionally created to work this way.

When editing a template or template part, alignments are available if the blocks are placed inside a group block (or for example a query block) with the setting "Inherit default layout" enabled.

I believe the most active discussion about how to solve this issue is in [#36082 ](https://github.com/WordPress/gutenberg/issues/36082)
This issue for updating the text for the setting, to make it easier to use, is also important: [#40861 ](https://github.com/WordPress/gutenberg/issues/40861)

I will close this as a duplicate, I encourage you to continue the discussion in the open issues.

**Closed as not planned by carolinan** 2022-06-09 06:20 UTC
Labels: [Status] Duplicate
