### ISSUE TITLE
Poor colour choice for update button

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15231] opened 2019-04-27 08:50 UTC
**Describe the bug**
When clicking the Update button on a Page/Post, it changes to white text on a white button with a white gradient, and becomes totally unreadable.

![Gutenberg_updatebutton](https://user-images.githubusercontent.com/2078245/56847340-c795e100-691c-11e9-81aa-123b611a0e81.gif)

**To reproduce**
1. Edit a page
2. Click the update button

**Expected behavior**
Buttons should be readable at all times, including when disabled or during an update process

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox Quantum 66.0.2
 - Version: 5.2-RC1-45273

**Comment by sarahmonster** [comment] 2019-05-17 12:53
This seems to be a duplicate of #15029, which I apparently assigned to myself and then promptly ignored. ;)

**Comment by jemlovestodraw** [comment] 2019-05-17 12:53
Agreed, it is hard to read. A simple fix could be to put the text (Updating...) in the medium blue of the original button.

**Comment by aduth** [comment] 2019-05-17 13:09
Closing as duplicate of #15029. This is a regression.

**Comment by aduth** [comment] 2019-05-17 13:09
Duplicate of #15029.

**Closed by aduth** 2019-05-17 13:09 UTC
Labels: Needs Design Feedback
