### ISSUE TITLE
Navigation Block: Reconsider placeholder state

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#23207] opened 2020-06-16 15:22 UTC
When adding a Navigation block to a document, you see the block's placeholder state.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/191598/84788394-1721eb00-afbd-11ea-848f-d56e65a1eb7f.png">

There's a number of things that this UI is trying to do, including:
1. Create a new, empty menu.
2. Create a new menu using a sites existing Pages.
3. Choose a previously created menu to populate a new menu.

I think the dropdown UI is a little complicated, and the current copy is awkward to read. There's an [issue to update the copy](https://github.com/WordPress/gutenberg/issues/22987), but it's kind of stalled; The UI is difficult to explain.

Looking at the Image block for inspiration I wound up with something like this:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/191598/84789458-408f4680-afbe-11ea-851a-b029c14d9b89.png">

This feels a little easier to understand, but it is still a rather _large_ representation of a real websites navigation. Lets take a look at it in the context **Full Site Editing**, where you would be adding a Navigation block to a page template:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/191598/84791123-340bed80-afc0-11ea-906f-43706f6b2b81.png">

After digging through more of the previous Issues and PRs around this subject, I tried rethinking things a little bit; What if we default to adding an _empty_ menu (1 above), with shortcuts for adding existing Pages or Menu's (2 and 3 above):

<img width="708" alt="image" src="https://user-images.githubusercontent.com/191598/84792077-741fa000-afc1-11ea-90f6-2870abc4d56e.png">

An alternative to this is to default to a menu containing all top-level Pages, with a _somewhat_ hidden option to remove all Link blocks within the menu:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/191598/84793734-7551cc80-afc3-11ea-9cb8-f44e2a47fcd8.png">

**Comment by mapk** [comment] 2020-06-16 15:46
I like where you landed Shaun. Your first iterations that followed the Image block still left some confusion around how the "Add existing menu" option would work. I believe that's why a dropdown was proposed.

The further iterations to just add all top-level pages automatically remind me of some very early concepts that were explored. When seeing this block added to a template, I agree that this direction fits better in the allotted space than showing a large placeholder screen. 

The last iteration also works better than the option to "Add all page" because it just focuses on top-level pages and not on ALL pages. If I were to add all pages, I'd assume sub-pages would also be added automatically. This could get a little daunting.

While it's somewhat hidden, the "Remove all links" option is vital and I'm glad that's being considered.

I'm still left wondering about existing menus though. If I've got an existing menu for my Footer already built, how would I select it from the block in regards to your last iteration?

**Comment by MichaelArestad** [comment] 2020-06-16 15:48
> An alternative to this is to default to a menu containing all top-level Pages, with a somewhat hidden option to remove all Link blocks within the menu:

The more I think about this idea, the more it makes sense to me in a majority of situations. What if I go to add a menu to my header and I just insert it, maybe arrange the links a little, and that's it?! I think it would feel like I inserted a menu and not a container for a DIY menu.

There are pitfalls:
* It isn't the most straightforward to move or remove current links. I think this is the biggest blocker to an "Add all links by default" method. 
* What happens on sites with hundreds of pages? Perhaps we could detect this and default to an empty state with a warning letting the user decide if they want to spawn a huge menu?

**Comment by jasmussen** [comment] 2020-06-16 16:29
Shaun, an idea that I heard Matías float, could the quick inserter absorb some of this functionality? I don't have a full mental picture of how it might work, but if the quick inserter is limited to the allowed child blocks, could it also hold options to insert a full menu? I imagine Riads new inserter might accommodate it potentially https://github.com/WordPress/gutenberg/pull/22789

**Comment by draganescu** [comment] 2020-06-17 08:10
@jasmussen there is an open topic to start developing a Pages block that would track the pages structure.

This Pages block doesn't solve all issues immediately (say a site with a hundred pages) but it could alleviate some of the burden of the Navigation block. Also filtering and customizing this Pages block is easier in a stand along fashion, without the other options of a Navigation.

If we go wild we could have a block for "Legacy menu" :) - I don't think this is a great idea, but thought I'd mention it to maybe spark some other idea. This delegation to more particular blocks could make the Navigation block more useable and easier to grasp.

cc @shaunandrews

**Comment by tellthemachines** [comment] 2020-06-19 05:45
> What if we default to adding an _empty_ menu (1 above), with shortcuts for adding existing Pages or Menu's (2 and 3 above):

I love this idea! It's much more flexible than defaulting to top-level pages, because if we want to create a completely different menu, we don't have to delete all our pages first. Having it empty and the options to add stuff a click away seems ideal. 

I wonder if it would make sense to have the ability to add and combine multiple existing menus too.

**Comment by shaunandrews** [comment] 2020-06-19 16:33
> could the quick inserter absorb some of this functionality? I don't have a full mental picture of how it might work, but if the quick inserter is limited to the allowed child blocks, could it also hold options to insert a full menu?

Maybe something like this, @jasmussen

<img width="731" alt="image" src="https://user-images.githubusercontent.com/191598/85157138-0a093400-b229-11ea-84d1-94cb056bf824.png">

**Comment by jasmussen** [comment] 2020-06-19 16:37
That just might work! Could add the basic "all pages" there too.

**Comment by shaunandrews** [comment] 2020-06-19 16:41
<img width="371" alt="image" src="https://user-images.githubusercontent.com/191598/85157996-38d3da00-b22a-11ea-94e2-8af406059a3a.png">

**Comment by jasmussen** [comment] 2020-06-22 06:12
As a wireframe and concept, this feels like it checks the boxes of allowing you to quickly add a specific menu, without having a giant setup state full of dropdowns and boxes and cogs, yet it still uses existing UI — the inserter and the plus button. 

Question: once you've inserted an existing menu, or "all pages" — the behavior of the plus changes, doesn't it? I guess this is why you're using the big white appender button in the empty state, and presumably the black plus button would take over when no longer empty?

The only downside I see to this approach, is that in its empty state, it still doesn't look like a "navigation menu" — it's just a white blob. Smaller and with a plus, but still. This is no worse than what we have today, and solves a lot of problems, but it speaks to a larger issue we should keep thinking about: how can we improve the setup states to look more like the end results.

Nice work, Shaun!

**Comment by draganescu** [comment] 2020-06-24 10:03
@shaunandrews @jasmussen we also seem to have this issue #20853 on the same topic. Should we close that and track here? If so just making sure we're updated with the discussion there :)

**Comment by jasmussen** [comment] 2020-06-24 10:05
They do seem to tackle the same problem, yes, but we need to port the good stuff from this ticket to the other then ;)

**Comment by draganescu** [comment] 2020-06-24 10:15
I would close that other one.

**Comment by jasmussen** [comment] 2020-06-24 10:17
That works.

**Comment by getdave** [comment] 2020-07-02 06:59
Great to see this evolving!

How about rather than just a blank block appender +, we have some "ghosted" placeholder nav items to make the placeholder look more like a navigation that already has items in it? 

Also I know we are supporting lots of block types in the Nav but do we need to have a search? It immediately made me feel the UI was quite intimidating with a lot of items to diggest and understand. 

Also how would this search work for existing WP Menus?

Also could you clarify what the graphics next to each of the existing menus represent? This wasnt clear to me.

Nice work 👍

**Comment by jasmussen** [comment] 2020-07-02 09:05
> How about rather than just a blank block appender +, we have some "ghosted" placeholder nav items to make the placeholder look more like navigation that already has items in it?

The important part here is to focus on a solution that is generic to any block, or any theme, or any background. I.e. ideally we find something that works also for Buttons and Social Links, or perhaps even an empty group block. 

The color problem we have already with the Spacer block, the light gray looks great on a white background, but not on a black background, or even an arbitrary color like green or blue.

> I know we are supporting lots of block types in the Nav but do we need to have a search? Is it warranted given how few blocks are compatible with Nav? 

It does seem worth pondering how to make this quick inserter as contextual as you can make it, so if there are less than n blocks allowed, maybe a search isn't necessary? 

I also wanted to clarify my comment in https://github.com/WordPress/gutenberg/issues/23207#issuecomment-647305798, because Matías pointed out to me that we can easily slide to the wrong side of the fence on this one.

It's good for the inserter to be contextually smart. But it's important that it only deal with _actual blocks_, or we risk it not behaving as you would expect.

**Comment by shaunandrews** [comment] 2020-07-02 21:27
> Ideally we find something that works also for Buttons and Social Links, or perhaps even an empty group block.

This got me thinking. The Buttons block starts out with a single Button placed by default. Now, it might be weird to default to a single Link block, but maybe we start with a new block that lists all your site's pages; A Pages block.

Here's a quick GIF that shows how that could work:

![nav blocks 4](https://user-images.githubusercontent.com/191598/86410255-730c9500-bc88-11ea-9f4a-808500e2f559.gif)

In the GIF, I'm adding a new Navigation block to a (mostly) empty document; By default, the Navigation block contains the Pages block. This new block displays links for all my site's pages. I'm unable to edit the individual links, but I can turn on/off sub-menu drop-downs, letting me only show top-level pages. If I remove the Pages block, I get an add button similar to the Group and Column blocks.

**Comment by jasmussen** [comment] 2020-07-03 07:54
Looks promising Shaun! 

The idea of an "All Pages" block, I believe, was brought up by @mtias at some point. In theory it seemed clunky, but thank you for mocking it up, because in practice it does not seem clunky. 

_I think it should be called "All Pages", though, not just "Pages"._

The idea solves a number of problems:

- It implies (and is the case) that the pages block is locked to showing the pages on your website, which almost always make up the structure of your website: when you add or remove pages, it will be reflected here. This is a big one.
- It allows faster building of your menu — just insert this block, and you're probably done.
- It vastly simplifies management, because titles, links, sort order are defined by the metadata stored in the pages themselves. 
- We could even default to inserting the All Pages block when you insert a Navigation Block. This would be a highly useful initial state.

There are downsides, of course. You click a menu item expecting to edit it, and you can't. There's no easy way to sort items in the menu, or change their labels, and items aren't in sync with new pages. However those interactions were also the ones adding the most complexity to the block.

This effort also does not preclude still allowing such editing of individual menu items. I'm sure you have a mockup of this already: selecting the "all pages" block, and transforming it to editable link blocks, just like you might transform a Gallery block into multiple Image blocks. Doing so would actively sever the connection between your pages, but at the same time let you edit to your hearts content — remove items, sort, change labels. 

---

We used to have a Button block (singular). But it was hard putting two of them side by side. The Buttons block (plural), was created to solve that. I remember the discussion — isn't that just a group block? Yes, but it's a specialized group block that is tailored to handling just Buttons inside, enabling features tailored to just that.

Similarly, thinking of the Navigation block as a "tailored group" block, I could see it working. You can have an "All Pages" block inside, a "Social Links" block, a "Search" block, and you can choose whether to show them vertically or horizontally, `space-between` or `flex-end`. I can see it working.

**Comment by shaunandrews** [comment] 2020-07-03 13:31
> I think it should be called "All Pages", though, not just "Pages".

I started by calling it "All Pages" but has since decided up on "Pages." Mostly, this is due to the ways I can see this block adapting and being used; For example, perhaps the Pages block allows you to hide/show pages. Or, perhaps its added inside some imagine Submenu block and used to only show child Pages. Basically, I think its possible this new block might not actually contain literally "all" of your site's pages.

That said, its a little early to tell and the name is easy enough to change still.

> We could even default to inserting the All Pages block when you insert a Navigation Block. This would be a highly useful initial state.

This is exactly what I suggested in my comment above: "By default, the Navigation block contains the Pages block."

> I'm sure you have a mockup of this already: selecting the "all pages" block, and transforming it to editable link blocks

I do, but I didn't want to go on too much of a tangent in this issue. Since you've asked, here's a few options I've worked up for how the Pages block could be "broken" or transformed into editable Link blocks:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/191598/86473869-b4945300-bd0f-11ea-98d2-e45b06d2197e.png">

**Comment by ZebulanStanphill** [comment] 2020-07-03 15:17
I like the concept of the "All Pages"/"Pages" block and being able to convert it to Navigation Link blocks. It reminds me of something I have in my [Table of Contents block PR](https://github.com/WordPress/gutenberg/pull/21234), where the Table of Contents can be transformed into a List block if you want to customize the order/links, though this comes at the cost of losing the auto-add-headings-to-the-list functionality.

**Comment by shaunandrews** [comment] 2020-07-03 18:59
Some more discussion around the proposed Pages block over in #23689.

**Comment by noisysocks** [comment] 2020-07-15 07:52
In an attempt to make the Navigation screen project board contain only issues that are needed to ship the new Navigation screen, I removed this issue from the board and created https://github.com/WordPress/gutenberg/issues/23953 which is smaller in scope.

**Comment by shaunandrews** [comment] 2020-08-26 17:56
To circle back to this one, I still think an "All Pages" (or more general Page Listing) block makes sense to be inserted by default.

Seeing as we don't have that block right now, we should update the current placeholder so its not so large.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/191598/91338938-b3c5ed80-e7a3-11ea-80d5-7aabba57a33c.png">

**Comment by ZebulanStanphill** [comment] 2020-08-26 19:19
Removing the big "Navigation" label from the placeholder... would that be an accessibility regression?

**Comment by shaunandrews** [comment] 2020-08-26 20:33
> would that be an accessibility regression?

How so? There's still the block toolbar (not shown in my screenshot) and the block would still identify itself as a Navigation block.

**Comment by enriquesanchez** [comment] 2020-08-26 20:35
>Removing the big "Navigation" label from the placeholder... would that be an accessibility regression?

I don't think so. The block type is already announced as you enter the block. In the case of the Image block, you hear "Block: Image, group" when you focus the block. If I hit `tab` I jump straight to the Upload button.

I'd expect for this to be a similar case on this block: "Block: Navigation group", if I then hit `tab` I'd hear: "Add all pages, button"

**Comment by jasmussen** [comment] 2020-08-27 06:41
There's also a great deal of usability to consider, insofar as the compact placeholder state actually looks even a smidgeon like the final result. That definitely conveys the purpose of the block setup state in a way a big white slab doesn't.

**Comment by shaunandrews** [comment] 2020-11-16 18:48
@mkaz is looking at this over in https://github.com/WordPress/gutenberg/pull/26947

--

I really dig what @jasmussen proposed for the Social Links block: https://github.com/WordPress/gutenberg/pull/26953#issuecomment-727842572

I tried something similar for the Navigation block and think it might be worth trying it out:

![Navigation Placeholder Unselected - Block Only](https://user-images.githubusercontent.com/191598/99294375-fbdc3580-2811-11eb-8fdb-ce5db8979b58.gif)

Here's how that could look within a template, perhaps inheriting some colors from the theme:

![Navigation Placeholder Unselected](https://user-images.githubusercontent.com/191598/99294153-aacc4180-2811-11eb-9a3a-4cd106c785e3.gif)

**Comment by jasmussen** [comment] 2020-11-17 08:21
Love it, Shaun, and in fact the social links placeholder state was inspired by your mockups right in this thread. Definitely agree this is worth trying. 

>  perhaps inheriting some colors from the theme

We can use `currentColor` and `opacity` and it should work.

**Comment by jasmussen** [comment] 2020-11-23 13:16
I'm making progress on this in https://github.com/WordPress/gutenberg/pull/27018#issuecomment-732154168.

**Closed** 2020-12-03 19:20 UTC
Labels: Needs Design Feedback, [Block] Navigation, [Status] In Progress
