### ISSUE TITLE
Microsot Word Post Compatiability 

### ISSUE THREAD

**Issue by revpixel** [WordPress/gutenberg#12368] opened 2018-11-27 16:20 UTC
Gutenburg installation prevents posting with Microsoft Word 2016 and 2019

**Comment by designsimply** [comment] 2018-11-27 16:39
Is this something you found after connecting Word to your blog via `xmlrpc.php` before updating to Gutenberg and then it did not work after installing the plugin? Or are you testing with WordPress 5.0-RC1? 

It would definitely help to have more detail here. Any chance you can provide some steps to reproduce the problem and mention whether or not you were publishing from Word to the same site you're using now prior to adding Gutenberg to that site and also please mention the versions of WordPress, Gutenberg (if installed as a plugin), and OS you are using? Also, if you are seeing a specific error message, please make a note of it.

**Comment by designsimply** [comment] 2018-11-28 20:35
I downloaded Office 365 on Windows 10 and followed these instructions to test: 

https://support.office.com/en-us/article/help-with-blogging-in-word-3ad4ad8d-06a3-441d-99cd-c65e13a3433d

I was able to create a new blog post directly from Word without any problems. I used WordPress 4.9.8 and Gutenberg 4.5.1 for my test. 

Because I was unable to replicate the problem, I am going to close this issue. If you're still having trouble and can provide additional details, please reply here and please note what step you got stuck on in the linked instructions above and whether you saw any specific error message that could help in troubleshooting what might be going wrong in your case.

**Closed by designsimply** 2018-11-28 20:35 UTC
Labels: Needs Testing, [Status] Needs More Info
