### ISSUE TITLE
Too many refreshes while editing long link in new editor

### ISSUE THREAD

**Issue by scegg** [WordPress/gutenberg#21554] opened 2020-04-13 03:18 UTC
**Describe the bug**
When editing a post with new editor, not the classic one, it is very difficult to edit a long link.

When try to edit a link target, a small popup window is shown. If the link is longer than the window, every editing key pressing (a char, delete or backspace key), the small window will flash and refresh. If keep pressing key quickly, it may hurt the doc other than link.

**To reproduce**
1. Write a post with a link and something else. The target of the link should be not so short.
2. Click on the edit button of the link.
3. Try to edit the target by pressing keys.
4. See refreshing.

If you press quicker in step 3, it will hurt other text before the window re-popup.

**Expected behavior**
The window should not close and reopen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.7 dev

**Comment by draganescu** [comment] 2020-04-13 13:49
Hi @scegg thanks for raising this issue. Unfortunately I could not reproduce this issue using the latest Gutenberg and WordPress:

![link-edit](https://user-images.githubusercontent.com/107534/79125386-c5839700-7da6-11ea-88f1-27ee694ae389.gif)

**Comment by scegg** [comment] 2020-04-13 13:55
Here is on my side.

I record a screen video on my macos with chrome 83.0.4103.7 (Official Build) dev (64-bit). It's very same like the problem in Windows.

Any way to sent it to you?

**Comment by scegg** [comment] 2020-04-13 13:57
https://send.firefox.com/download/f304c0515c8251aa/#l9yg26XwS3Bne-l1g5RAQg

This link is valid within 7 days and 100 downloads.

**Comment by draganescu** [comment] 2020-04-13 15:33
Oh I see now @scegg you are using the classic editor block in Gutenberg. I have not tested with that one.

**Comment by azaozz** [comment] 2020-04-13 18:46
Cannot reproduce here in the classic block in both WP 5.4 and Gutenberg master. 

> If you press quicker in step 3, it will hurt other text before the window re-popup.

To me it looks like there's -something- that moves the focus from the link modal to the text/elements around the link while typing (can see the caret in different places).

As far as I see there are some third-party TinyMCE plugins in the classic block instance of TinyMCE. Could you disable them and try again?

**Comment by scegg** [comment] 2020-04-14 04:28
Still the same with no plugin enabled.

**Comment by jasmussen** [comment] 2020-04-16 11:18
I also cannot reproduce this issue in the classic block.

@scegg Can you test in a different browser, or without any browser extensions enabled? An extension might conflict.

**Comment by scegg** [comment] 2020-04-16 13:00
It works great in Safari.
Failed in Version 83.0.4103.14 (Official Build) dev (64-bit) w/o plugins.

It seems that Google don't like this code.

**Comment by jasmussen** [comment] 2020-04-16 13:01
I'm using Chrome myself and can't reproduce, so it could be a chrome extension. An easy way to test without chrome extensions is to open an incognito window, then log into your website there and test.

If it works there, then it's one of the extensions you're using, causing trouble.

**Comment by scegg** [comment] 2020-04-16 13:03
That's exactly what I did.
Maybe the problem is only on the version 83 dev?

**Comment by jasmussen** [comment] 2020-04-16 13:05
Oh sorry, I missed that bit about plugins. Let me test in Canary now and see if I can reproduce there.

**Comment by jasmussen** [comment] 2020-04-16 13:08
Yep, I can definitely reproduce this issue in Chrome Canary (that's version 85). However I'm not sure the gutenberg plugin should go to a lot of effort to support a beta version, let alone a dev or canary version. Do you think you could switch to the stable channel for your editing work? And if you don't mind, I think I might close this one out — then if Google doesn't fix this themselves when it lands in the stable channel, we can reopen. What do you think?

**Comment by scegg** [comment] 2020-04-16 13:10
Of coz you are right. Hope that is something wrong in Chrome dev and will be fixed by Google soon. Or we may need fix for them.

**Closed** 2020-04-16 13:10 UTC
Labels: [Block] Classic, [Type] Bug
