### ISSUE TITLE
Generated aria labels for links in block elements can destroy the output

### ISSUE THREAD

**Issue by black-forever** [WordPress/gutenberg#12683] opened 2018-12-07 16:13 UTC
**Describe the bug**
If in block elements (e.g. Listings) with the characters * ">" * or * "<" * are used in the text, there is a problem with the Aria labels for links.

The entire text of the block is included in the Aria labels. With all the special characters. The special characters are not escaped. This will destroy the output.

**To Reproduce**
1. Create a block element (e.g. a List) within a post or page
2. Write several list elements 
3. Use special characters - (for example: "Use a PHP version> 7.2")
4. Use the Link Function and Edit the Link
5. Save or Update your post and Preview the post/page.
6. See the error

**Expected behavior**
Before copy the content to the Aria label - escape the special characters / html charakters
Example: "&lt" for < | "&gt" for >

Another question: Why is the entire text of the block used for the Aria labels?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 63.0.3

**Version of Gutenberg**
- WordPress 5.0 with integrated Gutenberg

**Comment by swissspidy** [comment] 2018-12-07 22:18
I feel like I saw a similar issue before about this 🤔

**Comment by afercia** [comment] 2018-12-08 13:06
Right, in https://github.com/WordPress/gutenberg/pull/12154 it was suggested to use a `screen-reader-text` appended to the link content instead of using `aria-label`. Unfortunately, that hasn't been addressed yet.

> Another question: Why is the entire text of the block used for the Aria labels?

This is a bug, tracked in https://github.com/WordPress/gutenberg/issues/12325

**Comment by afercia** [comment] 2018-12-08 13:21
To clarify: insert a link with the text link including a greater than `>` character:

<img width="399" alt="screenshot 2018-12-08 at 14 15 45" src="https://user-images.githubusercontent.com/1682452/49686394-2a184d00-faf4-11e8-95b6-2d6873451b68.png">

Generated markup (notice the `>` within the HTML attribute):

<img width="671" alt="screenshot 2018-12-08 at 14 15 49" src="https://user-images.githubusercontent.com/1682452/49686402-5af88200-faf4-11e8-9ec7-9e669d2c57f3.png">

Layout breakage in the front end, due to invalid markup:

<img width="695" alt="screenshot 2018-12-08 at 14 15 28" src="https://user-images.githubusercontent.com/1682452/49686411-706dac00-faf4-11e8-9bd7-d46fb3cc911e.png">

**Comment by black-forever** [comment] 2018-12-08 16:34
Thank you for the clarification and the included screens. Due to #12325 the error happens even if the greater than > character is not in the link text itself.

**Comment by aduth** [comment] 2018-12-11 21:48
Related (partially duplicates):

- #8779 
- #9915

Fixed by one of:

- #9963 
- https://core.trac.wordpress.org/ticket/45387

**Comment by Otto42** [comment] 2018-12-16 05:36
Easily reproducible from the description here:
https://wordpress.org/support/topic/a-minor-gutenberg-hyperlink-bug/

**Comment by afercia** [comment] 2019-01-27 10:59
Just to note this was reported again on Trac, see https://core.trac.wordpress.org/ticket/46114

**Comment by afercia** [comment] 2019-02-24 16:54
Removing the Accessibility label because not a real a11y bug. I guess it should get prioritized though. /Cc @youknowriad

**Comment by youknowriad** [comment] 2019-10-23 16:22
This seems fixed by #9963

**Closed by youknowriad** 2019-10-23 16:22 UTC
Labels: [Package] Format library, [Priority] High, [Type] Bug
