### ISSUE TITLE
Site Editor: Navigation block items window modal goes out of screen when both the List View & Block Inspector sidebar are active or inactive

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#48059] opened 2023-02-14 05:49 UTC
### Description

When trying to add menu items under the navigation block, the block items modal appears in half or completely goes out of screen when both the List View and the Blocks Inspector are toggled ON/OFF.

First reported on trac [https://core.trac.wordpress.org/ticket/57694](https://core.trac.wordpress.org/ticket/57694)

It seems this is a core-specific issue, the problem does not affect the Gutenberg 15.1 plugin.

### Step-by-step reproduction instructions

1. Activate TT3 or other block theme
2. Go to its header
3. Edit the Navigation block via the Editor
4. Toggle both the List View and the Block Inspector ON/OFF
5. Add menu items
6. Notice the blocks window modal appears in half or even goes out of the screen.

### Screenshots, screen recording, code snippet

![navigation-added-items](https://user-images.githubusercontent.com/79677758/218649900-17bffe8e-36c7-4d4e-bfc9-b136f75f1842.gif)

### Environment info

WP 6.2 beta 1, Firefox 109.0.1, Windows 11, TT3 & Powder themes.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment] 2023-02-14 16:56
![Screenshot 2023-02-14 at 5 54 21 PM](https://user-images.githubusercontent.com/118618474/218804450-6be8adae-e703-426f-a4fe-f1ef317cb6cc.png)

I can't reproduce this issue in Gutenberg, probably because of the updates in the Navigation Block that seem to have replaced the Add Block pop-up with a new Add Link design. Does that mean this issue belongs to the `WordPress/wordpress-develop` repo?

**Comment by annezazu** [comment] 2023-02-16 03:52
@getdave & @scruffian tagging for you all!

**Comment by scruffian** [comment] 2023-02-21 09:53
I think this is fixed by https://github.com/WordPress/gutenberg/pull/48195

**Comment by getdave** [comment] 2023-02-21 09:58
I can't replicate this on TT3 on WP 6.2 Beta 2.

@franzaurus Are you still able to replicate this? Are there any more specific conditions that trigger it. I tried everything I could think of 🙏

**Comment by franzaurus** [comment] 2023-02-21 13:33
@getdave Unfortunately I'm still able to reproduce the issue on 6.2 Beta 2. I found that clicking the Navigation block or Social icons after adding items will trigger the popover cut off.

### Adding navigation links item

![nav-add-links-beta2](https://user-images.githubusercontent.com/79677758/220353481-34b638dd-197f-4bbc-8c51-77c542d2226e.gif)


### Adding social icons item

![nav-social-links-beta2](https://user-images.githubusercontent.com/79677758/220353558-99aa87e3-246d-4655-a1c9-a85d47a5649e.gif)

**Comment by annezazu** [comment] 2023-02-21 16:12
Similar to https://github.com/WordPress/gutenberg/issues/48148, I wonder if there's something again related to pop overs here: https://github.com/WordPress/gutenberg/issues/48140 and https://github.com/WordPress/gutenberg/issues/47923.

**Comment by t-hamano** [comment] 2023-02-22 02:51
I have tested again with WordPress Beta 3.

WordPress 6.2-beta3-55401 _without_ Gutenberg enabled (**Reproduced**)

https://user-images.githubusercontent.com/54422211/220508914-117ea5f3-809b-47ec-a360-24856d4422ac.mp4

---

WordPress 6.2-beta3-55401 _with_ Gutenberg enabled (**Not reproduced**)

https://user-images.githubusercontent.com/54422211/220508946-71fd722e-4286-4e13-80b4-cee7013d58d2.mp4

**Comment by ntsekouras** [comment] 2023-02-24 09:49
Related: https://github.com/WordPress/gutenberg/issues/48398

**Comment by ntsekouras** [comment] 2023-02-24 10:07
This seems to be a similar issue with dependencies resolution in core, as we had with [valtio](https://github.com/WordPress/gutenberg/pull/48237).

**Comment by carolinan** [comment] 2023-02-24 11:49
I am also able to reproduce this in 6.2-beta3-55409 without Gutenberg active.

**Comment by getdave** [comment] 2023-02-24 12:17
@ntsekouras Can I clarify. Do you believe this is a dependency related issue rather than, say, a Issue relating specifically to the Navigation block (or its List Viww editing feature)?

**Closed as completed** 2023-02-24 13:19 UTC
Labels: [Type] Bug, [Block] Navigation

**Comment by ntsekouras** [comment] 2023-02-24 13:22
> @ntsekouras Can I clarify. Do you believe this is a dependency related issue rather than, say, a Issue relating specifically to the Navigation block (or its List Viww editing feature)?

Yes, it related to `floating-ui` version and therefore affects Popover in general. By pinning the version, this should be resolved for beta 4.
