### ISSUE TITLE
Lots of extra markup in v2.6

### ISSUE THREAD

**Issue by rwrobe** [WordPress/gutenberg#6089] opened 2018-04-09 17:56 UTC
## Issue Overview
The 2.6 release adds a lot of wrapping divs and internal divs to various components in a block.

## Steps to reproduce
- Add any core block (or custom block) to a post
- Inspect and see the extra divs

## Images
https://imgur.com/a/IkCWz

**Comment by aduth** [comment] 2018-04-09 18:04
Can you elaborate on the problem that these divs are causing?

Aside: Looking briefly, most are from event normalization (e.g. [focus outside detection](https://github.com/WordPress/gutenberg/blob/268af89a53509f6d758c2602e49ec5970ff366b4/components/higher-order/with-focus-outside/index.js#L119-L126)). There's some hope that the need for element wrappers can be avoided in the future with enhancements to React's new `Fragment`:

>`key` is the only attribute that can be passed to Fragment. **_In the future, we may add support for additional attributes, such as event handlers._**

https://reactjs.org/docs/fragments.html#keyed-fragments

**Comment by mtias** [comment] 2018-04-09 19:03
Also, these are internal to the editor and not part of the content.

**Comment by rwrobe** [comment] 2018-04-09 20:52
It's causing issues for styling more complex blocks. Specifically those with multiple elements that aren't laid out vertically-- e.g., a recent post with a thumbnail on the left and text content to the right.

**Comment by gziolo** [comment] 2018-04-10 07:02
> https://imgur.com/a/IkCWz

/cc @brandonpayton. I think this is caused by the fact that we apply `Autocomplete` to all `RichText` components. It existed before, but was only the case for `Paragraph` block.

**Comment by brandonpayton** [comment] 2018-04-13 23:08
> I think this is caused by the fact that we apply Autocomplete to all RichText components. It existed before, but was only the case for Paragraph block.

Those divs are indeed due to `Autocomplete` being added to `RichText`:

* There is a [`div` added by the base `Autocomplete` component](https://github.com/WordPress/gutenberg/blob/972788cc84a3d27b6148262553304c04873ec09c/components/autocomplete/index.js#L617).
* Another [added by the `withFocusOutside` HOC](https://github.com/WordPress/gutenberg/blob/972788cc84a3d27b6148262553304c04873ec09c/components/higher-order/with-focus-outside/index.js#L119) in order to add event listeners.
* Another [added by the blocks `Autocomplete`](https://github.com/WordPress/gutenberg/blob/972788cc84a3d27b6148262553304c04873ec09c/blocks/autocomplete/index.js#L101) component to add event listeners.

@gziolo and I were not pleased with these additions but did not see a better solution at the time. I'm hoping that React will eventually support specifying event listeners on Fragments as mentioned in the [React 16.2 fragment support post](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html):
> In the future, we may add support for additional attributes, such as event handlers.

**Comment by rwrobe** [comment] 2018-04-17 13:16
Does this mean that the divs are here to stay until there are updates to React? If so, can we add a class or wrapper so we can target these divs without having to use nth-child selectors in CSS?

**Comment by gziolo** [comment] 2018-04-17 13:57
We will take a closer look if we can limit the number of divs that are there before Gutenberg gets merge into WordPress core. 👍

**Comment by danielbachhuber** [comment] 2018-05-18 23:45
Related #6839

**Comment by SuperGeniusZeb** [comment] 2018-06-28 22:35
#7477 removed some unneeded wrapping `<div>`s from Paragraph blocks.

**Comment by mtias** [comment] 2018-07-19 11:17
Closing this as there's been some changes on the HoC wrappers. If there's anything specific still causing issues, please, open new issues.

**Closed by mtias** 2018-07-19 11:17 UTC
Labels: Blocks, [Type] Bug
