### ISSUE TITLE
Disable reordering of inserter

### ISSUE THREAD

**Issue by studionenontwerp** [WordPress/gutenberg#23074] opened 2020-06-10 20:50 UTC
The inserter is constantly (re)ordering blocks in each category by most used. I dont think that's the right way. When each block type has its own position within the category, it's easier to find it. Now its changing position after you select one. So the next time you trigger the popup inserter, the ordering is changed. The user has to 'search' / scan the blocks for the preferred block because the position is changed. The ordering of the top category (most used) should always be reordered of course. 

I changed the layout of the inserter as list by css so I prefer an alphabetical ordering. So:
1) is it possible to switch off the reordering of blocks in the category
2) is it possible to set a custom or alphabetical ordering

**Comment by richtabor** [comment] 2020-06-11 16:30
Duplicate of #22406, apart from the enhancement suggestions.

**Closed** 2020-07-06 09:03 UTC
Labels: [Feature] Inserter, [Status] In Progress
