### ISSUE TITLE
Text Block cursor issue

### ISSUE THREAD

**Issue by LZL0** [WordPress/gutenberg#8797] opened 2018-08-09 21:20 UTC
**Describe the bug**
When I start a new text block and instantly press Ctrl+V the pasted content will appear but the cursor will be at the beginning of the block. This issue does not appear to happen if there is already content in the text block.

**To Reproduce**
1. Start a new text block
2. Paste some content into it

**Expected behavior**
The cursor should appear at the end of the content.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser latest Chrome Beta

Gutenberg 3.5
WordPress 4.9.8

**Comment by designsimply** [comment] 2018-08-10 20:38
Tested and confirmed using WordPress 4.9.8 and Gutenberg 3.5.0 that when I paste plain text content into a paragraph block the cursor lands at the beginning of the pasted content and not the end.

**Comment by designsimply** [comment] 2018-08-10 20:45
Closing as a duplicate of #5317.

**Closed by designsimply** 2018-08-10 20:45 UTC
Labels: Writing Flow, [Component] Raw Handling, [Type] Enhancement
