### ISSUE TITLE
Footer copyright block

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34761] opened 2021-09-11 20:54 UTC
## What problem does this address?

Many sites adopt the pattern of putting something like `Copyright {Author / Company name} 2021` in their footer.

To avoid the need to update this manually every year, in classic themes most developers would use PHP to programatically output the correct year.

With Site Editing there is no way to do this without creating a custom block.

## What is your proposed solution?
Given the ubiquity of the pattern should we offer a `core/copyright` block?

**Comment by Sandstromer** [comment] 2021-09-13 09:55
A footer copyright block feels a bit too narrow in focus to me.

IMHO a more general "Site Info" block would be great.
This could pull in such things as Site Title, Tagline, custom text, current date (with format options to display e.g. just the year etc.), current theme name/author and so on.

Similar to how the Social Icons block works, select something like a "Site Info" block and add/order the pieces you want.

**Comment by mtias** [comment] 2021-09-13 10:15
Closing as duplicate of #18895 and #33475.

**Closed as completed by mtias** 2021-09-13 10:15 UTC
Labels: New Block, [Package] Block library
