### ISSUE TITLE
Changes to blocks don't preview and can't be published

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#25153] opened 2020-09-08 14:28 UTC
**Describe the bug**
There is no way to publish block updates in the widget editor embedded in the customizer

**To reproduce**
1. Be on a theme that supports widgets and have the Gutenberg 8.9 plugin set up
2. Go to Appearance > Customize
3. Try to customize blocks, change order, settings
4. Notice you cannot publish changes and that the changes do not preview

**Expected behavior**
When I edit blocks the publish button should become blue and the changes should reflect on the right side.

**Comment by carolinan** [comment] 2020-09-09 12:04
I am able to reproduce this with 8.9.3. and I see the following JS errors:


`14:01:31.794 widgets.min.js?ver=5.5.1:2 Uncaught TypeError: window.wp.deprecateL10nObject is not a function
    at widgets.min.js?ver=5.5.1:2
(anonymous) @ widgets.min.js?ver=5.5.1:2
14:01:33.414 index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1 GET http://localhost:8888/wp-json/wp/v2/types/widget-areas?context=edit&_locale=user 404 (Not Found)
H @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
tryCatch @ wp-polyfill.min.js?ver=7.4.4:1
invoke @ wp-polyfill.min.js?ver=7.4.4:1
t.<computed> @ wp-polyfill.min.js?ver=7.4.4:1
n @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
a @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
U @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
p @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
U @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
p @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
t @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
C @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
(anonymous) @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
I @ index.js?ver=62e90f761f68eb1cc0c59f23d1afdba8:1
API_FETCH @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
e @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
r.any @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
e @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
e @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
c @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
t @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
r.iterator @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
e @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
c @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
t @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=ad785dcae37e85d5d48a4af4f6b5e6d8:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
tryCatch @ wp-polyfill.min.js?ver=7.4.4:1
invoke @ wp-polyfill.min.js?ver=7.4.4:1
t.<computed> @ wp-polyfill.min.js?ver=7.4.4:1
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
K @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
tryCatch @ wp-polyfill.min.js?ver=7.4.4:1
invoke @ wp-polyfill.min.js?ver=7.4.4:1
t.<computed> @ wp-polyfill.min.js?ver=7.4.4:1
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
setTimeout (async)
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
tryCatch @ wp-polyfill.min.js?ver=7.4.4:1
invoke @ wp-polyfill.min.js?ver=7.4.4:1
t.<computed> @ wp-polyfill.min.js?ver=7.4.4:1
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
f @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
s @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
Me @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
ar @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
ir @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
fe @ index.js?ver=d4c487ba0cf97e40a8e6b6c9db8f6f0f:1
we @ react-dom.min.de439aae.js:84
zj @ react-dom.min.de439aae.js:226
Th @ react-dom.min.de439aae.js:152
tj @ react-dom.min.de439aae.js:152
Te @ react-dom.min.de439aae.js:146
Ja @ react-dom.min.de439aae.js:224
md @ react-dom.min.de439aae.js:173
(anonymous) @ react-dom.min.de439aae.js:175
Rh @ react-dom.min.de439aae.js:147
nd @ react-dom.min.de439aae.js:175
I.render @ react-dom.min.de439aae.js:238
Ge @ index.js?ver=d4c487ba0cf97e40a8e6b6c9db8f6f0f:2
(anonymous) @ customize.php?return=%2Fwp-admin%2Fthemes.php%3Fpage%3Dgutenberg-widgets:449
Show 41 more frames
14:01:33.415 index.js?ver=86e17756483edb79c5c2acf422ecb400:1 Uncaught (in promise) {code: "rest_type_invalid", message: "Invalid post type.", data: {…}}
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
a @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
Promise.then (async)
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
setTimeout (async)
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
tryCatch @ wp-polyfill.min.js?ver=7.4.4:1
invoke @ wp-polyfill.min.js?ver=7.4.4:1
t.<computed> @ wp-polyfill.min.js?ver=7.4.4:1
n @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
f @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
s @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
c @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
(anonymous) @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
Me @ index.js?ver=86e17756483edb79c5c2acf422ecb400:1
ar @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
ir @ index.js?ver=7c1b3086aac36c0635659487cd7b9bfb:1
fe @ index.js?ver=d4c487ba0cf97e40a8e6b6c9db8f6f0f:1
we @ react-dom.min.de439aae.js:84
zj @ react-dom.min.de439aae.js:226
Th @ react-dom.min.de439aae.js:152
tj @ react-dom.min.de439aae.js:152
Te @ react-dom.min.de439aae.js:146
Ja @ react-dom.min.de439aae.js:224
md @ react-dom.min.de439aae.js:173
(anonymous) @ react-dom.min.de439aae.js:175
Rh @ react-dom.min.de439aae.js:147
nd @ react-dom.min.de439aae.js:175
I.render @ react-dom.min.de439aae.js:238
Ge @ index.js?ver=d4c487ba0cf97e40a8e6b6c9db8f6f0f:2
(anonymous) @ customize.php?return=%2Fwp-admin%2Fthemes.php%3Fpage%3Dgutenberg-widgets:449
14:01:36.091 ?customize_changeset_uuid=caaf20f8-eb50-4610-b614-70a61ea01760&customize_theme=starting-block&customize_messenger_channel=preview-0:72 GET http://localhost:8888/wp-content/themes/starting-block/assets/css/min/global.min.css?ver=1.0.0 net::ERR_ABORTED 404 (Not Found)
14:01:36.253 VM7722 extension_properties.js:38 Uncaught TypeError: Cannot read property 'frameURIs' of undefined
    at VM7722 extension_properties.js:38
(anonymous) @ VM7722 extension_properties.js:38
postMessage (async)
(anonymous) @ VM7723 extension_properties.js:35
postMessage (async)
(anonymous) @ VM7722 extension_properties.js:52
(anonymous) @ VM7722 extension_properties.js:57
`

**Comment by styledev** [comment] 2020-09-15 17:32
I am also getting this error:
`{code: "rest_type_invalid", message: "Invalid post type.", data: {status: 404}}
code: "rest_type_invalid"
data: {status: 404}
status: 404
message: "Invalid post type."`

**Comment by adamziel** [comment] 2020-09-21 15:22
This is caused by `sync-customizer.js` trying to sync to widgetArea entity records. The store now uses a "sidebar" entity combined with a "temporary post". This issue might be a good opportunity to revisit that design choice and either correct it or stay with it and adjust `sync-customizer.js`.

**Comment by adamziel** [comment] 2020-09-24 08:12
@draganescu oh that was just an early update - my next step here is to take a deeper dive :-)

**Comment by adamziel** [comment] 2020-09-24 11:10
Moving away from the top-level post is not trivial as mentioned in https://github.com/WordPress/gutenberg/issues/25405. I'm going to move forward with this data model for now.

**Comment by adamziel** [comment] 2020-09-25 09:07
Blocked by https://github.com/WordPress/gutenberg/issues/25625

**Comment by noisysocks** [comment] 2021-01-05 04:33
Closing this out as we are completely rearchitecting our implementation of how blocks work in the Customiser.

**Closed by noisysocks** 2021-01-05 04:33 UTC
Labels: Customizer, [Feature] Widgets Screen, [Type] Bug
