### ISSUE TITLE
Cannot delete all text from multiline RichText field

### ISSUE THREAD

**Issue by thatdevgirl** [WordPress/gutenberg#12880] opened 2018-12-14 16:30 UTC
**Describe the bug**
It is impossible to delete all of the text from a multiline RichText field. If I highlight all of the text and delete it, the text is deleted from the editor, but when I save and view the page, the original text is still there. 

I first discovered the issue in a custom block that I am developing, but I am able to reproduce in out-of-the-box blocks, like Quote.

**To Reproduce**
1. Go to a page and add the Quote block.
2. Add content to the quote part of the block (i.e. where it says "Write quote...".
3. Highlight all of that content and press Delete on your keyboard.
4. The content is no longer in the block on the edit screen.
5. Save and view the page.
6. Note that the deleted content appears on the front end.

Note: I was also able to reproduce in the Pull Quote block and the caption on the Image block.

**Expected behavior**
The deleted content should not appear on the front-end.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome (latest)

**Additional context**
- Tested on Gutenberg 4.7.0.

**Comment by jeremyfelt** [comment] 2018-12-15 01:05
I'm able to reproduce this in Mac OSX using the latest Chrome in both the Pull Quote block and in a custom multiline block.

Note: If you delete the content one character at a time, it seems to work. If you highlight the line of text and delete, it does not.

**Comment by iseulde** [comment] 2019-02-09 19:47
Is this still an issue with the latest `master` branch, after #13697? I cannot reproduce any longer.

**Comment by berengerzyla** [comment] 2019-02-26 03:54
Still an issue under 5.1.
Same comment as @jeremyfelt .
Chrome, OSX, WP 5.1
Deleting one char at a time USUALLY works. 
Selecting all text and deleting at once won't trigger onChange, nor will make the placeholder visible.

**Comment by berengerzyla** [comment] 2019-02-26 12:15
I do not know if it's related, but there is an inconsistency in the value of a RichText, in that way.
A newly created one will have a content equal to an empty string. One in which we removed all data (100% empty) will have `<p></p>` content data. Both empty, different data.

**Comment by berengerzyla** [comment] 2019-02-27 12:29
@iseulde , is the master different than the version shipped in 5.1? If so, how to test this version?

**Comment by iseulde** [comment] 2019-02-27 19:41
You can test the latest Gutenberg version by installing the plugin. It’s
updated more often than WordPress. Thanks!

**Comment by berengerzyla** [comment] 2019-02-28 00:46
Did so. The issue first mentioned in the ticket is indeed fixed under 5.1.1.
All the previous tests are conclusive.
There is still this discrepancy between the initial state (which will return an empty string) and "empty state" (which will return <p></p>). Will check in the other issues if it exists.
Thank you!

**Comment by iseulde** [comment] 2019-02-28 08:55
@berengerzyla Do you mean that for multiline instances it will return e.g. `<p></p>`? This has been brought up in 
https://github.com/WordPress/gutenberg/pull/10678#discussion_r226456573 and there's a tracking issue #10763. Thanks for testing!

**Comment by iseulde** [comment] 2019-02-28 09:02
Since you created #14160, I'm going to close this issue.

**Closed by iseulde** 2019-02-28 09:02 UTC
Labels: Needs Testing, [Component] Rich Text, [Status] Needs More Info
