### ISSUE TITLE
Permanent crash / not recoverable (solved by updating the permalink structure)

### ISSUE THREAD

**Issue by techmagus** [WordPress/gutenberg#8899] opened 2018-08-12 11:52 UTC
**Describe the bug**
- Permanent crash

```
this.wp.editor</el</<@https://domain.tld/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533882368:9:289895
i@https://domain.tld/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:636
x/An.filter@https://domain.tld/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:53487
this.wp.editor</el<@https://domain.tld/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533882368:9:289864
yh@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:3936
lg@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2629
mg@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2927
gc@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6310
vb@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820
ub@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655
zd@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5027
ra@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:4386
enqueueSetState@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:8:9426
q.prototype.setState@https://domain.tld/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:1:5015
value/this.unsubscribe<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:64732
r/</<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:60675
r/<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:60646
d@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:47086
n/<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:61755
w@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:38351
x/i._invoke</<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:38141
j/</t[n]@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:38527
o@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:32252
c@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:32454
u@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:42704
A/<@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:42849
s@https://domain.tld/wp-content/plugins/gutenberg/build/data/index.js?ver=1533882368:1:41118

```

**To Reproduce**
1. Blog as usual
2. Then open the Categories dropdown
3. Crash permanently
4. Tried disabling plugins one-by-one (like YoastSEO) but Gutenberg doesn't want to recover regardless.

**Desktop (please complete the following information):**
 - OS: Windows 7 32-bit
 - Browser Firefox
 - Version 62.0b16 (32-bit)

**Additional context**
- Gutenberg: Version 3.5.0

See also: https://github.com/WordPress/gutenberg/issues/3953#issuecomment-409337526 someone left a new comment 12 days ago from the time of this new report (Chrome & Firefox, no SEO plugins).

**Comment by techmagus** [comment] 2018-08-12 12:09
Here's the error copy without any plugins attaching itself to the editors (gutenberg and classic).

```
this.wp.editor</el</<@https://domain.tld/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533882368:9:289895
i@https://domain.tld/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:636
x/An.filter@https://domain.tld/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:53487
this.wp.editor</el<@https://domain.tld/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533882368:9:289864
yh@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:3458
lg@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2629
mg@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2927
gc@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6310
vb@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820
ub@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655
wg@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:11362
Ze@https://domain.tld/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:3:3054

```

**Comment by designsimply** [comment] 2018-08-14 21:33
I tested with Firefox 61 on Windows 7 and was unable to reproduce the problem using WordPress 4.9.8 and Gutenberg 3.5.0 ([20s](https://cloudup.com/ckCa0VsIyS7)). Noting that I tested with a stable release and you appear to be testing the development version and so I should loop back around to try testing that as well.

May I ask what plugins were still active at the time you did your second test? May I also ask what theme you are using (may not be relevant, asking just in case).

**Comment by ccprog** [comment] 2018-08-15 19:31
I see the same error with a basically fresh install (Firefox 60/Linux Mint Cinnamon, WP 4.9.8, no other plugins, default theme Twenty Seventeen, only update was from Gutenberg 3.4 to 3.5/production versions; the crash happens for both), for both tags and categories. No terms have been entered, so basically there is only the "Uncategorized" category.

I then both entered a category and a tag to see if this was caused by empty lists, but it made no difference.

The ability to use Gutenberg can be restored by deleting the `localStorage` entry, which amounts to reseting the `core/edit-post` panels preferences.

 Log output with `define('SCRIPT_DEBUG', true);` is

```
The above error occurred in one of your React components:
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component) (created by Ot)
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component) (created by Ot)
    in Ot (created by kt)
    in div (created by eo)
    in eo (created by kt)
    in div
    in div (created by t)
    in t (created by SidebarSlot)
    in SidebarSlot
    in div
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithViewportMatch(Component) (created by NavigateRegions(WithViewportMatch(Component)))
    in div (created by NavigateRegions(WithViewportMatch(Component)))
    in NavigateRegions(WithViewportMatch(Component)) (created by r)
    in r (created by RemountOnPropChange(r))
    in RemountOnPropChange(r)
    in Unknown (created by WithDispatch(NavigateRegions(WithViewportMatch(Component))))
    in WithDispatch(NavigateRegions(WithViewportMatch(Component))) (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(WithDispatch(NavigateRegions(WithViewportMatch(Component))))
    in t
    in t (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by r)
    in r (created by RemountOnPropChange(r))
    in RemountOnPropChange(r)
    in Unknown (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component)

React will try to recreate this component tree from scratch using the error boundary you provided, t.
react-dom.24169eaf.js:14804:5
logCapturedError
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14804:5
logError
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14843:5
callback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:15525:7
callCallback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:11456:3
commitUpdateQueue
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:11500:7
commitLifeCycles
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14955:11
commitAllLifeCycles
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16040:7
callCallback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:9
invokeGuardedCallbackDev
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:7
invokeGuardedCallback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:5
commitRoot
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16181:7
completeRoot
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17196:34
performWorkOnRoot
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17141:9
performWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17060:7
performSyncWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17032:3
requestWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16932:5
scheduleWork$1
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16796:11
enqueueSetState
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:11877:5
Component.prototype.setState
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react.832d746b.js:524:3
value/this.unsubscribe<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:64732
r/</<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:60675
r/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:60646
d
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:47086
n/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:61755
w
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38351
x/i._invoke</<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38141
j/</t[n]
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38527
o
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:32252
c
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:32454
u
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:42704
A/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:42849
s
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:41118
TypeError: e.visibility is undefined[Weitere Informationen]
index.js:12:289893
this.wp.editor</el</<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/editor/index.js:12:289893
arrayFilter
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:574:11
filter
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:9165:14
this.wp.editor</el<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/editor/index.js:12:289862
updateFunctionalComponent
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:13703:20
beginWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14400:14
performUnitOfWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16441:12
workLoop
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16480:24
callCallback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:9
invokeGuardedCallbackDev
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:7
invokeGuardedCallback
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:5
replayUnitOfWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:15888:5
renderRoot
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16540:11
performWorkOnRoot
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17138:22
performWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17060:7
performSyncWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17032:3
requestWork
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16932:5
scheduleWork$1
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16796:11
enqueueSetState
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:11877:5
Component.prototype.setState
http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react.832d746b.js:524:3
value/this.unsubscribe<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:64732
r/</<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:60675
forEach self-hosted:261:13 r/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:60646
d
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:47086
n/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:61755
w
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38351
x/i._invoke</<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38141
j/</t[n]
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:38527
o
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:32252
c
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:32454
u
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:42704
A/<
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:42849
s
http://wpvanilla.intern/wp-content/plugins/gutenberg/build/data/index.js:1:41118
```

**Comment by ccprog** [comment] 2018-08-15 19:41
A crash also happens with Chrome 68, but with a slightly different stack trace (React error report is identical):

```
    TypeError: Cannot read property 'show_ui' of undefined
    at http://wpvanilla.intern/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533834382:12:289913
    at arrayFilter (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:574:11)
    at filter (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/lodash.2cfc2504.js:9165:14)
    at http://wpvanilla.intern/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533834382:12:289878
    at mountIndeterminateComponent (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:13958:13)
    at beginWork (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14398:14)
    at performUnitOfWork (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16441:12)
    at workLoop (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16480:24)
    at renderRoot (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16520:7)
    at performWorkOnRoot (http://wpvanilla.intern/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17138:22)
```

**Comment by designsimply** [comment] 2018-08-15 19:50
I found a similar report at #8456 and the source of the problem in that case was Cloudflare and if that is the cause for your trouble as well then updating to the latest version should resolve the problem. 

There is also a note in #8456 about permalink structure ([ref](https://github.com/WordPress/gutenberg/issues/8456#issuecomment-410433454)) and a note in #8802 about rewrite rules being the cause of the same error ([ref](https://github.com/WordPress/gutenberg/issues/8802#issuecomment-411961456)). If you aren't already using the default permalink structure, can you try that to see if it makes the problem go away? Are you using any custom rewrite rules on your server?

**Comment by ccprog** [comment] 2018-08-15 20:03
Interesting. Changing the permalink structure made the problem go way, and despite trying out a lot of different customizations, I can't reproduce the error now.

There are no server-defined rewrite rules (I use a lighttpd server, so `.htaccess` doesn't work anyway.)

**Comment by ccprog** [comment] 2018-08-15 21:12
OK, here it is:

After a fresh install, option `permalink_structure` has the value `/%year%/%monthnum%/%day%/%postname%/`. As soon as I change the setting, a leading `index.php` is inserted. `index.php/%year%/%monthnum%/%day%/%postname%/` works out fine. What makes Gutenberg crash is the missing file name in that option.

The source of the problem is in the installation call to `wp_install_maybe_enable_pretty_permalinks()` in `wp-admin/includes/upgrade.php`. Let me quote the inline doc:

```
    /*
     * The Permalink structures to attempt.
     *
     * The first is designed for mod_rewrite or nginx rewriting.
     *
     * The second is PATHINFO-based permalinks for web server configurations
     * without a true rewrite module enabled.
     */
    $permalink_structures = array(
        '/%year%/%monthnum%/%day%/%postname%/',
        '/index.php/%year%/%monthnum%/%day%/%postname%/'
    );
```

So, for my case (neither mod_rewrite nor nginx), the second structure is supposed to be used, but it isn't. While I understand WP Core has no reason to accomodate every existing server setup, maybe it is worth finding out why the test routine fails for lighttpd.

**Comment by ccprog** [comment] 2018-08-15 21:28
If anyone with a lightpd comes across this, the workaround is:

    server-modules += ( "mod_rewrite" )

    url.rewrite-if-not-file = (
        "^/(.+)/?$" => "/index.php/$1"
    )

**Comment by ccprog** [comment] 2018-08-15 22:26
reported in Core as https://core.trac.wordpress.org/ticket/44804

**Comment by techmagus** [comment] 2018-08-17 04:42
Hi,

I tested it today (without clearing and changing anything) in my affected blog it is now loading fine. I tried to replicate it but I can no longer repeat it. In any case:
* Theme: eMag 1.1.4
* nginx

If I encounter it again, I'll post an update.

**Comment by techmagus** [comment] 2018-08-18 12:06
Hi,

I got the same crash again and to recover, as per what was suggested above, I can get Gutenberg back after clearing Local Storage.

It appears that, on my end, it has to do with opening the Categories and Tags section (for Tags, it crashes for existing posts with Tags already defined; but for new posts, it crashes when clicking the Tags field).

I don't have the issues experienced in the linked reports like stuck "saving draft" and not generating previews -- I had these two last week of July and first week of August only. Also, I'm on free Cloudflare so WAF is locked to Off and the Firewall Evets log for it is also empty.

I turned-off Cloudflare to test but still crashing. I checked the server for any related rules mentioned in the other reports but I don't have those either.

In addition to that, I never encountered the crashes until this August or after the recent minor update by Wordpress, the one where they encouraged installing the Classic plugin. (Yet, even without the classic plugin, it crashes.)

The workaround I have is to just avoid opening the Categories and Tags sections and then edit in Classic. No other areas of Gutenberg is causing the crash, only Categories and Tags, which wasn't the case before August.


Copy Error:
`
this.wp.editor</$a</<@https://example.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534530390:12:291372
i@https://example.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:636
x/An.filter@https://example.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:53487
this.wp.editor</$a<@https://example.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534530390:12:291341
yh@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:3458
lg@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2629
mg@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2927
gc@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6310
vb@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820
ub@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655
wg@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:11362
Ze@https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:3:3054
`

Console:
`
TypeError: "e.visibility is undefined"
ahttps://example.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534530390:9:291374ihttps://example.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:636filterhttps://example.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:1:53487ahttps://example.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534530390:9:291343yhhttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:3936lghttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2629mghttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2927gchttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6310vbhttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820ubhttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655zdhttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5027rahttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:4386enqueueSetStatehttps://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:8:9426setStatehttps://example.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:1:5015unsubscribehttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:64692rhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:60636rhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:60607dhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:47100nhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:61716whttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:38364_invokehttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:38154nhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:38540ohttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:30431chttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:30633uhttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:43078Ahttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:43223shttps://example.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534530390:1:41492 react-dom.min.82e21c65.js:5:10666
bg
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:10666
ig/c.callback
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:679
Jf
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:4:15949
Kf
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:4:16409
jc
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:10036
gc
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6331
vb
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820
ub
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655
zd
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5027
ra
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:4386
enqueueSetState
https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:8:9426
q.prototype.setState
https://example.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:1:5015
value/this.unsubscribe<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:64692
r/</<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:60636
r/<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:60607
d
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:47100
n/<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:61716
w
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:38364
x/i._invoke</<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:38154
j/</t[n]
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:38540
o
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:30431
c
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:30633
u
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:43078
A/<
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:43223
s
https://example.com/wp-content/plugins/gutenberg/build/data/index.js:1:41492
`

**Comment by designsimply** [comment] 2018-10-22 16:19
I am going to close this as it appears a solution was posted. 

@techmagus, if you are still having trouble can you let me know? If things are still problematic for you then I would like to help track down a better solution that what has been discussed above.

**Closed by designsimply** 2018-10-22 16:19 UTC
Labels: [Component] Post Settings, [Type] Bug

**Comment by P4ulJC** [comment] 2019-10-31 03:25
Took me a while to track down the issue causing Gutenberg to crash with `TypeError: "e.visibility is undefined"` but it turned out to be my Lighttpd rewrite rules for Wordpress. 

The line causing the Gutenberg crash in my case was:
 `"^/(wp-.+).*/?" => "$0"`

I changed the above  to `"^/wp-admin/$" => "$0"` and Gutenberg no longer crashes.  So my virtual host  config now looks like: 


```
$HTTP["host"] =~ "your-virtual-host-name" {
    server.document-root = "your/doc/root/here"
    
    url.rewrite-if-not-file = (
        "^/wp-admin/$" => "$0",
        "^/.*?(\?.*)?$" => "/index.php$1"
    )

    server.error-handler-404 = "/index.php"
}
```

**Comment by Jamie0** [comment] 2019-11-21 23:54
To echo above, a similar workaround for nginx could be the following:

    location ~ /wp-json/ {
        try_files $uri $uri/ /index.php?$args;
    }
