### ISSUE TITLE
Add "X" to close dimensions popup or close when added padding/margin

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#55487] opened 2023-10-19 13:32 UTC
## What problem does this address?
Currently when adding padding/margin in the dimensions the popup does not close and sometimes overlaps the respective input fields. The only way to close it is to click somewhere else on the sidebar. (check screenshot)

## What is your proposed solution?
Add a click handler for better usability

First suggestion: Add an "X" button  
Second suggestion: Close the popup once margin/padding option is clicked

![image](https://github.com/WordPress/gutenberg/assets/112690182/e734482a-7204-4da7-93ca-0f2be906fc03)

**Comment by hanneslsm** [comment] 2023-10-19 17:03
This is very much needed. The related discussion is only slowly moving forward: https://github.com/WordPress/gutenberg/issues/41546

**Comment by richtabor** [comment] 2023-10-20 15:10
I'll close this as a duplicate of #41546, but let's keep the effort/ideas moving.

**Closed as completed by richtabor** 2023-10-20 15:10 UTC
Labels: [Type] Enhancement, [Feature] Design Tools
