### ISSUE TITLE
Way to output custom html-tag-attributes from blocks

### ISSUE THREAD

**Issue by estebanwaseaten** [WordPress/gutenberg#15492] opened 2019-05-08 08:27 UTC
is there any way to include custom html-tag-attributes (not necessarily data-*) in the output of a block? Example:
`<div someAttribute="test">`
These attributes seem to get removed by the block's save() function as well as its php render_callback function. This makes it impossible to use third party frameworks that rely on these attributes.

I was thinking of using filters 'block_parser_class' or 'render_block', but without success so far.
Any hints are greatly appreciated.

**Comment by youknowriad** [comment] 2019-08-19 13:58
Duplicate of #15477

**Closed by youknowriad** 2019-08-19 13:58 UTC
Labels: Block API, [Type] Help Request
