### ISSUE TITLE
Allow pattern files in subfolders

### ISSUE THREAD

**Issue by huubl** [WordPress/gutenberg#53669] opened 2023-08-15 09:06 UTC
## What problem does this address?
Right now patterns can't be organized in subfolders, like [template parts](https://github.com/WordPress/gutenberg/issues/20375).

## What is your proposed solution?
Scan the /patterns directory recursively to find patterns in subfolders.

PR: https://github.com/WordPress/gutenberg/pull/53668

**Comment by bgardner** [comment] 2023-08-15 17:03
I would love to see this happen, especially since I made the same suggestion to @richtabor recently.

**Comment by aaronrobertshaw** [comment] 2023-08-16 00:20
Thanks for taking the time to not only create this issue @huubl but spin up a PR to get the ball rolling 🙇 

This issue is a duplicate of https://github.com/WordPress/gutenberg/issues/50144, so I'll close it for now. I've also linked the PR to the original issue and commented there.

**Closed as completed by aaronrobertshaw** 2023-08-16 00:20 UTC
Labels: [Type] Enhancement, [Feature] Patterns
