### ISSUE TITLE
Group: Full width doesn't set child images to full width

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#15723] opened 2019-05-19 09:43 UTC
#### Describe the bug 

All the child `Image` blocks inside a `Group` block are not set to `Full width` when the `Group` block is set to `Full width`.

#### Steps to reproduce 

- Add a `Group` block.
- Add a `Image` block inside the group block.
- Set the `Group` block to `Full width`.

#### What is expected 

The image blocks are set to full width, as is the case when the `Image` block is used individually (outside of a group block)

<img width="1920" alt="Screenshot 2019-05-19 at 15 08 04" src="https://user-images.githubusercontent.com/18581859/57980376-8ccd2780-7a48-11e9-9985-49c405fe6971.png">

The above image is of an `Image` block outside a `Group` block, and that `Image` block is set to `Full width`. See how it covers the entire display?

#### What happens instead 

The image is not set to full width.

<img width="1920" alt="Screenshot 2019-05-19 at 15 08 14" src="https://user-images.githubusercontent.com/18581859/57980374-8a6acd80-7a48-11e9-8709-60b776cf2241.png">

#### Gutenberg, browser and device version:

I am using Gutenberg 5.7.0-rc-1 on a Pressable site, with Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on macOS 10.14.4 - Mac OS Mojave. 

#### Notes

I am not entirely sure if this is an intended design, but thought I might flag this up anyway.

**Comment by youknowriad** [comment] 2019-05-21 09:29
I think that might be the expected behavior because even a group is full width not all of its images should be show full width. You might one to center everything and only show one single image full-width...

**Comment by youknowriad** [comment] 2019-05-21 09:30
Closing by pinging others to confirm @kjellr @jasmussen

**Closed by youknowriad** 2019-05-21 09:30 UTC

**Comment by jasmussen** [comment] 2019-05-21 09:34
Based on a decision during the development of the group block, this behavior is intended. 

I can understand the confusion though — the centered main column is sort of a property of the post content container, moreso than group blocks themselves. But I recall discussing this with Kjell, and he had some very solid arguments for this behavior, and ideas for what to explore in the future to help set expectations.

**Comment by kjellr** [comment] 2019-05-21 12:35
> I recall discussing this with Kjell, and he had some very solid arguments for this behavior, and ideas for what to explore in the future to help set expectations.

Yep. This isn't the exact same scenario, but it's related: in  https://github.com/WordPress/gutenberg/pull/14908 actually has a new enhancement built in that will ensure that grouped blocks start out with the width of their widest child. So consider the following process: 

1. You have a full-width image. 
2. You put that inside of a group block.

Using that new PR, your new group block will be full width automatically, and the image inside will still be full width too. This should result in no visual change to the child blocks when they're grouped. 

---

The issue above is also likely complicated by the fact that the core themes (based on the font I see in the screenshoot, I'm guessing this was with Twenty Nineteen) are not currently up to date to work with the Group block. That is coming soon, and tracked here: 

https://core.trac.wordpress.org/ticket/46750
