### ISSUE TITLE
HTML content of a dynamic block cannot be retrieved by the render function

### ISSUE THREAD

**Issue by gschoppe** [WordPress/gutenberg#5968] opened 2018-04-04 00:08 UTC
https://github.com/WordPress/gutenberg/blob/ea9416b9e489fd4ba6375413fcd7248a55bffa43/lib/blocks.php#L181

Despite supporting non-self-closing dynamic blocks, there is no functionality for passing the html content of a dynamic block to the render function.

**Comment by danielbachhuber** [comment] 2018-04-04 12:48
Hi @gschoppe,

What change would you suggest? Can you share more detail on what you're trying to accomplish?

**Comment by danielbachhuber** [comment] 2018-04-04 13:29
Actually, it looks like this is a duplicate of #5760. Closing in favor of that issue (but happy to look at a PR too)

**Closed by danielbachhuber** 2018-04-04 13:29 UTC
Labels: [Status] Needs More Info
