### ISSUE TITLE
Section styles: editing a block variation in Styles doesn't reflect in the editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62303] opened 2024-06-04 20:13 UTC
While recording a demo of section styles with 6.6 beta 1, I noticed that while I could change the variation in Styles, the changes would update on the front end of the site but would revert in the editor after hitting save. Here's a video showing front end vs back end:

https://github.com/WordPress/gutenberg/assets/26996883/a68230ef-d48c-4bbe-81cb-f183b1d8abd1

Here's the demo video I was working on for good measure:

https://github.com/WordPress/gutenberg/assets/26996883/0465c244-4498-4c94-bcad-40654bfbc989

Here's the theme.json:

```
	"styles": {
		"blocks": {
			"variations": {
				"Dark": {
					"blockTypes": [
						"core/group",
						"core/columns"
					],
					"color": {
						"background": "#1e1e1e",
						"text": "#FFF"
					},
					"elements": {
						"heading": {
							"color": {
								"text": "#FFF"
							}
						}
					}
				}
			}
		}
	}
```

I am assuming this is likely because I'm _adding_ an element style to the variation (button in this case) but that doesn't explain why the Heading doesn't update. This could very well be user error but wanted to report just in case cc @aaronrobertshaw

**Comment by aaronrobertshaw** [comment] 2024-06-05 01:07
Thanks for writing up the issue @annezazu 👍 

I can replicate the problem with WP 6.6 beta 1 via the following steps:

1. Add a group block style variation to theme.json
2. Navigate to Appearance > Editor > Styles > Blocks > Group > Variation e.g. "dark"
3. Tweak variation styles and note editor does update accordingly
4. Save and note the loss of the tweaked styles
5. Reload the editor and see the saved styles back

If I activate Gutenberg the user customizations in Global Styles save correctly and everything works as expected.

The beta is behaving a bit weird here. I'm not aware of anything that was outstanding or missed in terms of this feature being backported or included in GB18.5. 

I'll dig into this today and try and work out what's gone awry.

**Comment by aaronrobertshaw** [comment] 2024-06-05 05:59
**Update:**

After debugging, I've managed to track this down to the REST API response stripping custom variations data when saving global styles. 

This is due to the REST API endpoint not triggering the theme json resolver and the theme json data filters that the section styles feature currently relies upon to register the custom variations as block styles, in turn allowing them to pass theme.json sanitization.

Gutenberg has a couple of duotone actions registered which access merged theme json data. The result is those actions cause the custom variations to be registered in Gutenberg. Hence the feature working for the site editor there.

One quick solution might be to enforce the registration of any variations contained in the global styles data being returned from this endpoint.

**Comment by aaronrobertshaw** [comment] 2024-06-05 08:58
This a tentative fix up in https://github.com/WordPress/gutenberg/pull/62321. 

It is still to be seen whether this approach is sufficient long term but it would fix this bug for the 6.6 beta and unblock deeper testing.

**Comment by aaronrobertshaw** [comment] 2024-06-07 08:54
An alternative approach to solving the root cause of this issue is available in https://github.com/WordPress/gutenberg/pull/62405.

**Comment by aaronrobertshaw** [comment] 2024-06-11 05:08
Gutenberg port of the fix proposed in https://github.com/WordPress/wordpress-develop/pull/6756 is available in: https://github.com/WordPress/gutenberg/pull/62461

**Closed as completed** 2024-06-11 06:11 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Block Variations

**Comment by annezazu** [comment] 2024-06-11 16:46
Great work here.

**Comment by aaronrobertshaw** [comment] 2024-06-12 03:19
Quick update: We found another small edge case that would trigger the same issue. A fix for that has been rolled into the [core patch](https://github.com/WordPress/wordpress-develop/pull/6756) and a fresh Gutenberg PR (https://github.com/WordPress/gutenberg/pull/62495)
