### ISSUE TITLE
[Block style] - Add CSS style directly to the block

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#62964] opened 2024-06-28 09:40 UTC
The subject has already been discussed #56127, is there anything new ?

Would it be possible to add CSS style directly to the block in the right-hand side panel in a "CSS Style" tab, contextualized directly where it is and not globally in theme.json or in customizers ?
This would make it possible to create a quick override for anyone, on a page for example, rather than globally, without having to install a plugin.

- https://gutenberghub.com/how-to-apply-custom-css-to-any-gutenberg-block/
- https://wordpress.stackexchange.com/questions/414366/how-to-add-arbitrary-custom-css-to-a-wordpress-block-theme-using-site-editor

**Comment by annezazu** [comment] 2024-07-02 21:55
Hey there! Thanks for opening this. I believe it's a duplicate of the following: https://github.com/WordPress/gutenberg/issues/47862 As a result, I'm closing this out and encourage you to share your feedback on that prior issue.

**Closed as completed by annezazu** 2024-07-02 21:55 UTC
Labels: [Type] Enhancement, CSS Styling
