### ISSUE TITLE
New inserter search input-field classname breaks e2e/performance tests

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#22045] opened 2020-05-01 23:29 UTC
**Describe the bug**
The new classname of the search input-field of the inserter breaks the e2e/performance tests because the classname wasn't changed in the test utility functions yet.

Old class name: `block-editor-inserter__search-input`
New class name: `block-editor-inserter__search`

**To reproduce**
1. Run the performance test script `test-performance` (after having prepared everything, also see https://github.com/WordPress/gutenberg/issues/22038)
2. Notice that the test will fail because of failing to focus on the element `-block-editor-inserter__search-input`.
3. When you dump the DOM right before the line `await page.focus( '.block-editor-inserter__search-input' );` in `packages/e2e-test-utils/src/search-for-block.js:14` you will notice that the inserter search input field got the classname `block-editor-inserter__search`, but the e2e test utility expects the old classname `block-editor-inserter__search-input`, hence focusing it times out in puppeteer and the test fails.

**Expected behavior**
e2e/performance tests can finish without errors.

**Comment by strarsis** [comment] 2020-05-01 23:34
PR ready: https://github.com/WordPress/gutenberg/compare/master...strarsis:patch-1
Though there may be more occurrences of the previous classnames that also have to be replaced/refactored.

**Comment by talldan** [comment] 2020-05-08 03:57
The performance tests in `master` passed ok for me.

The classname `block-editor-inserter__search-input` does still seem to be in use:
https://github.com/WordPress/gutenberg/blob/3b5bfa3964c336597687b62ac43906109c05f9aa/packages/block-editor/src/components/inserter/search-form.js#L25

But maybe it was fixed in another ticket. I'll close this given I'm unable to reproduce the issue.

**Closed by talldan** 2020-05-08 03:57 UTC

**Comment by strarsis** [comment] 2020-05-08 12:24
@talldan: Probably another build task has to be run before the e2e tests and some built files are checked in, that had been built before that commit.
