### ISSUE TITLE
WritingFlow: ArrowDown from last paragraph misplaces caret to the right

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18342] opened 2019-11-06 18:28 UTC
**Describe the bug**

When pressing <kbd>ArrowDown</kbd> from a final paragraph block, the caret shifts to the right.

**To reproduce**

1. Navigate to Posts > Add New
2. Click the writing prompt
3. Press <kbd>ArrowDown</kbd>
4. Observe misaligned caret

**Expected behavior**

If the current selection is already within an "initial default block" (empty paragraph), it should not move.

**Screenshots**

![caret](https://user-images.githubusercontent.com/1779930/68326335-38227500-0099-11ea-8f6f-7c77b08d123f.gif)

**Desktop:**
 - OS: macOS Catalina 10.15 (19A603)
 - Browser: Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)

cc @ellatrix

**Comment by waviaei** [comment] 2019-11-08 09:11
Hi. I would like to mention below issue which we have been looking into in Japanese community for past day. It involves Input Method Editor (IME) + Chrome, and "delete" key. **But similarly only seems to occurs in the last paragraph**. Possibility of relation?

https://github.com/WordPress/gutenberg/issues/18362

**Comment by aduth** [comment] 2019-11-08 16:25
Hi @waviaei , I can't speak to whether it's a related cause, since I'm not sure what the underlying issue is. But they do seem to share some similarities in how they both impact the last block, so it's a good issue to reference in case they are related. Thanks!

**Comment by talldan** [comment] 2020-10-05 08:45
I couldn't reproduce an issue in Firefox, but this does still happen in Chrome (Mac OS).

**Comment by ellatrix** [comment] 2020-12-15 11:20
Typing still happens in the right place, so I'll consider it a minor issue. It's probably going in the placeholder, so we might need to restore the right selection.

**Comment by ellatrix** [comment] 2024-07-12 13:59
Related: #23882
I also can no longer reproduce.

**Comment by ellatrix** [comment] 2024-07-12 19:16
Also not seen in issue #23882 in a long time, so l closing.

**Closed by ellatrix** 2024-07-12 19:16 UTC
Labels: [Type] Bug, [Priority] Low, [Feature] Rich Text, Browser Issues, [Feature] Writing Flow
