### ISSUE TITLE
Too easy to get empty blocks

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1540] opened 2017-06-28 10:31 UTC
Its a natural behaviour to click in, however you can easily stack up quite a few blocks doing this. See this video:

https://cldup.com/KVEVwYHPfh.mp4

**Comment by swissspidy** [comment] 2017-06-28 10:34
Related: #1502 / possible duplicate of #1501.

**Comment by mtias** [comment] 2017-06-28 10:48
Yes, closing as duplicate.

**Closed by mtias** 2017-06-28 10:48 UTC
Labels: Blocks, [Type] Bug
