### ISSUE TITLE
Caret gets moved to the beginning of the current block's content after undoing bold text

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#3998] opened 2017-12-14 11:20 UTC
**Steps to reproduce**
* In a paragraph block, add some words.
* Then press the bold button and type another word.
* Undo the new word addition by pressing `Ctrl+z`.

**What I see** 
The caret gets moved to the beginning of this block's content.

**Comment by danielbachhuber** [comment] 2018-01-23 14:08
Thanks for the report, @kmgalanakis.

I've been able to reproduce this behavior in Gutenberg 2.0:

![boldtext](https://user-images.githubusercontent.com/36432/35279889-4ace9b5e-0003-11e8-94f4-12d84d2badde.gif)

However, the behavior is consistent with the classic editor:

![boldtext2](https://user-images.githubusercontent.com/36432/35279982-8d667054-0003-11e8-953f-713e7b0f8fd4.gif)

Closing this as `maybelater` because it's not a departure from the existing behavior.

**Closed by danielbachhuber** 2018-01-23 14:08 UTC
Labels: Blocks, maybelater

**Comment by kmgalanakis** [comment] 2018-01-23 14:48
I didn't notice that both editors had the same behavior. Thanks @danielbachhuber.
