### ISSUE TITLE
ButtonBlockAppender ignores clientId when filtering menus and returns no blocks

### ISSUE THREAD

**Issue by daledesilva** [WordPress/gutenberg#25886] opened 2020-10-07 02:14 UTC
**Describe the bug**
The ButtonBlockAppender (available directly in block-editor components) ignores clientId when filtering the popup's _immediate_ list and when clicking _browse all_. This makes it unusable because clicking browse all to see all blocks results in _no results found_.

block-editor components:
https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components

This buttonBlockAppender file:
https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/button-block-appender

**To reproduce**
1. Create a block which includes Inner Blocks
2. Define a blank renderAppender inside the InnerBlocks tag (This is just so you don't get two appender plus buttons).
3. Outside the InnerBlocks tag, include the ButtonBlockAppender and pass in the blocks clientId.
Note, you'll have to be aware of this bug: https://github.com/WordPress/gutenberg/issues/25885

ie
```
<InnerBlocks
    renderAppender = { () => (<>
        {/* This is blank so the plus button doesn't show up twice */}
    </>) }
/>

{/* rootClientId doesn't work :( */}
<ButtonBlockAppender
    rootClientId = { clientId }
/>
```

**Expected behavior**
- The _immediate_ list should be filtered according to the allowed blocks of the rootClientId passed in.
- The _browse all_ list should be filtered according to the allowed blocks of the rootClientId passed in.

**Versions**
- WordPress version: 5.5.1
- Default block editor

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
Note, this is different to InnerBlocks.ButtonBlockAppender. In that, the clientId is taken from an HOC which uses the clientId of the block the InnerBlocks tag is placed in. The component described above requires the clientId to be passed in.

**Comment by talldan** [comment] 2020-10-22 08:46
Thanks for reporting. ButtonBlockAppender passes the value to `Inserter`:
https://github.com/WordPress/gutenberg/blob/55bf7ec3b7c032df68437b4605673c13fdf2c6cf/packages/block-editor/src/components/button-block-appender/index.js#L32

I couldn't reproduce an example with the *immediate* list, here I hacked the Buttons block to support paragraphs and button and it worked without issue:
<img width="526" alt="Screenshot 2020-10-22 at 4 43 27 pm" src="https://user-images.githubusercontent.com/677833/96847566-eaf40a80-1485-11eb-9911-0482b41be2ad.png">

My appender was defined the same as yours:
```jsx
<ButtonBlockAppender rootClientId={ clientId } />
```

Maybe check your clientId definitely has a value.

The 'Browse all' issue would be related to this bug - https://github.com/WordPress/gutenberg/issues/24403

I'll close this as a duplicate

**Closed by talldan** 2020-10-22 08:46 UTC
