### ISSUE TITLE
Block library above another showing through toolbar of block below

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19445] opened 2020-01-06 21:15 UTC
I was testing columns block and managed to create this:

![image](https://user-images.githubusercontent.com/253067/71849258-88ce4280-30c9-11ea-87c7-527ac702c870.png)

Whilst, it's a bit of a stress case, I would suggest we set a rule potentially of only having one open at a time.

**Comment by karmatosed** [comment] 2020-01-07 17:38
Whilst #18918 will fix the popover for 'slash command' there is a second issue here of the top block's library peering through.

![image](https://user-images.githubusercontent.com/253067/71915812-71985f00-3174-11ea-8761-28b10528a703.png)

I created this by adding a column block then a paragraph one. I'll update the title.

**Comment by youknowriad** [comment] 2020-01-17 13:22
Duplicate of #19353

**Closed by youknowriad** 2020-01-17 13:22 UTC
Labels: Good First Issue, Needs Dev, [Type] Bug
