### ISSUE TITLE
Make Gutenberg remember image-size preference when adding to post

### ISSUE THREAD

**Issue by STHLMWebDesign** [WordPress/gutenberg#12348] opened 2018-11-27 08:59 UTC
Working on a photography heavy website one thing I really dislike about Gutenberg is it does not remember my preferences when adding to images. In the classic editor I could set it use full size images and it would remain that way until I added an image and changed it to something else. Where as with Gutenberg it seems to default to using the large image size every time. This really slows you down when making an image heavy post.

**Comment by designsimply** [comment] 2018-11-27 17:47
Thank you for posting about this. Closing as a duplicate of #8663.

My personal feedback: I ❤️ this suggestion! I like having sticky image size preferences.

**Closed by designsimply** 2018-11-27 17:47 UTC
Labels: Media, [Block] Image, [Status] Duplicate, [Type] Enhancement
