### ISSUE TITLE
Listing subcategories that were not selected

### ISSUE THREAD

**Issue by taludelito** [WordPress/gutenberg#23383] opened 2020-06-23 08:25 UTC
**Describe the bug**
When editing the post, the subcategories (which are not also selected in the parent category) do not appear in the list. However, in the post all of the posts in the child categories are appearing, even if they were not selected in the parent category.

**Reproduce**
example categories:
sports> basketball
sports> football
any post in football or basketball are being listed in the post. (but on the edit page it appears correctly)

**Expected behavior**
Posts created in a subcategory should not appear. Unless, of course, the parent category is also selected.

**Screenshots**
in the editor is correct
https://i.imgur.com/LbcJC80.png
in the post, listed the child categories that were not selected
https://i.imgur.com/W53Y33W.png

**Editor's version (fill in the following information):**
- WordPress version: [for example: 5.4.2]
- The website has the Gutenberg plug-in ["standard"]

**Desktop (fill in the following information):**
 - OS: linux
 - Chrome browser
 - Version 83

**Comment by annezazu** [comment] 2020-07-28 22:21
@taludelito thanks for reporting this! I went to try to replicate this but struggled to do so based on the information you provided. Can you clarify which block you are using? Is it the categories block or the latest post block or another one entirely? Further, can you confirm what WordPress version you are using and whether you're using the Gutenberg plugin along with what version if so? Thanks in advance!

**Comment by taludelito** [comment] 2020-07-28 23:11
> @taludelito obrigado por denunciar isso! Fui tentar replicar isso, mas lutei para fazê-lo com base nas informações que você forneceu. Você pode esclarecer qual bloco você está usando? É o bloco de categorias ou o último bloco de postagem ou outro totalmente? Além disso, você pode confirmar qual versão do WordPress está usando e se está usando o plug-in Gutenberg juntamente com qual versão? Desde já, obrigado!

Table of Contents

**Comment by taludelito** [comment] 2020-07-28 23:17
> @taludelito thanks for reporting this! I went to try to replicate this but struggled to do so based on the information you provided. Can you clarify which block you are using? Is it the categories block or the latest post block or another one entirely? Further, can you confirm what WordPress version you are using and whether you're using the Gutenberg plugin along with what version if so? Thanks in advance!

I use WordPress 5.4.2 with the standard Gutenberg.
when including in the edition of the Table of Contents block, the result is correct, as I hope it works. But on the front end, subcategories are listed together. 
see this image side by side
https://i.imgur.com/3cPMlag.png

**Comment by tellthemachines** [comment] 2021-01-19 05:23
Hi @taludelito , I can't reproduce this issue with the Latest Posts block on WP 5.6. It may have been fixed in the meantime. Or else, are you using a third party block from another plugin? If so, best contact the plugin author with a bug report.

**Closed by tellthemachines** 2021-01-19 05:23 UTC
Labels: Needs Testing, [Block] Categories
