### ISSUE TITLE
Excerpt limit is overruled

### ISSUE THREAD

**Issue by jeffreyvr** [WordPress/gutenberg#48403] opened 2023-02-24 10:34 UTC
### Description

Since Gutenberg 15.2.0, the set excerpt length limit is not always respected. 

When you have a Homepage set (Settings -> Reading), and have a custom query on `front-page.php`, it does no longer limit the length.

This bare bones theme reproduces the issue: 

https://github.com/jeffreyvr/gutenberg-excerpt-limit-bug

### Step-by-step reproduction instructions

1. Create a page called 'Home' and setting it as the 'Homepage' in Settings -> Reading.

2. Create a posts with text exceeding the excerpt limit. Example:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum porttitor gravida. Nulla efficitur, enim in ultrices dignissim, augue justo efficitur tellus, et condimentum enim magna id erat. Nam a consectetur magna, dapibus gravida tortor. Nulla quis dapibus massa. Phasellus mattis sem vitae maximus congue. Praesent pharetra vulputate quam a sodales. Quisque in risus turpis. Maecenas eu molestie arcu. Sed sed finibus magna. Integer in rhoncus velit, in luctus turpis. Nam volutpat lorem vel purus ultrices bibendum non vel enim. Duis sem nibh, ultrices quis pulvinar vitae, congue vel lorem. Praesent suscipit risus quis lacinia consectetur. Etiam ornare scelerisque convallis. Aenean id nibh eget massa aliquam laoreet quis non ex. Aliquam non tortor et neque placerat tempus eu non sapien.

Nulla sodales sapien ac nisl luctus, nec finibus odio aliquet. Nunc massa neque, ultricies eu elementum non, vehicula at nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec dapibus enim id varius placerat. Ut vel orci bibendum sem viverra sollicitudin. Sed ullamcorper eros arcu, vehicula pulvinar dui posuere eget. Cras ut nisl sit amet sapien tristique eleifend at vel sapien. Quisque congue, odio vel vestibulum interdum, ex nisl malesuada mauris, ac hendrerit nulla nisi et sem. Nam id risus vestibulum, congue ante in, ornare justo. Vestibulum consequat justo ac eros faucibus, at interdum est placerat.
```

3. The `front-page.php` should contain a custom query to display recent posts.

```php
<?php
    $custom_query = new WP_Query( array(
        'post_type' => 'post',
        'posts_per_page' => 3,
        'orderby' => 'date',
        'order' => 'DESC',
    ) );
?>

<?php if ( $custom_query->have_posts() ) : ?>
    <?php while ( $custom_query->have_posts() ) : $custom_query->the_post(); ?>

        <div>
            <h2><?php the_title(); ?></h2>

            <div><?php the_excerpt(); ?></div>
        </div>

    <?php endwhile; ?>

<?php endif; ?>
```

4. In `functions.php` limit the excerpt length:

```php
function example_site_custom_excerpt_length( $length ) {
    return 20;
}

add_filter( 'excerpt_length', 'example_site_custom_excerpt_length', 999 );
```

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/9550079/221156884-1cc7a34e-c73c-4348-9390-d60503c15992.mov

### Environment info

- Gutenberg v15.2.0
- WordPress v6.1.1
- Theme (very basic): https://github.com/jeffreyvr/gutenberg-excerpt-limit-bug

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tmanhollan** [comment] 2023-02-28 00:20
Came here to report this as well. I believe it's this line:

https://github.com/WordPress/gutenberg/blob/3faa015215d6a1dcca0416e7a80a82e23f67ca4d/packages/block-library/src/post-excerpt/index.php#L88

The condition always evaluates to true because the constant, REST_REQUEST is quoted. And I'm not sure, but if the purpose of this was to determine whether the the editor is active, I think the logic should be _AND_ not _OR_.

**Comment by skorasaurus** [comment] 2023-02-28 18:16
Came here to report this as well (and thanks @jeffreyvr for the very detailed test case). 

I am able to reproduce this under additional conditions: 

Settings at /wp-admin/options-reading.php  are set to "Your homepage displays": "your latest posts" ; 

used a couple different classic themes (maxwell, ernesto) and in both, the excerpt_filter is ignored even when the priority is manually changed to 999.

**Comment by jeffreyvr** [comment] 2023-03-02 10:43
https://github.com/WordPress/gutenberg/pull/48654 fixes this particular issue.

**Comment by skorasaurus** [comment] 2023-03-02 21:57
thanks; closing.

**Closed as completed by skorasaurus** 2023-03-02 21:57 UTC
Labels: [Type] Bug, [Type] Regression, [Block] Post Excerpt
