### ISSUE TITLE
No home/blog body class

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#14990] opened 2019-04-15 16:44 UTC
**Describe the bug**
The body class `home` or `blog` for front page/blog page is 
missing for `<body>` in Gutenberg editor page.

**To reproduce**
1. Create a new page in backend.
2. Make that new page the front page.
3. Open this new front page in Gutenberg editor.
4. Notice (e.g. in Web Developer Tools) that `<body>` got no `home` or `blog` class assigned.

Current code for switching template class in `<body>` (based on code of others here on GitHub):
https://discourse.roots.io/t/gutenberg-body-class-elements-by-template/15310

**Comment by strarsis** [comment] 2019-04-15 18:03
Quite related: https://github.com/WordPress/gutenberg/issues/8948

**Comment by swissspidy** [comment] 2019-04-21 14:16
Closing as a duplicate of #10640, for the same reason #8948 was closed as a duplicate too.

**Closed by swissspidy** 2019-04-21 14:16 UTC
