### ISSUE TITLE
Video block: Video is not displayed when post is saved in the web version

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#30987] opened 2021-04-20 08:28 UTC
## Description

**This issue was initially identified here: https://github.com/wordpress-mobile/WordPress-iOS/issues/15184**

When a video block is saved in the web version then the video can't be displayed in the mobile app and shows the message “Problem displaying block” within the block. Looks like there's some kind of incompatibility on the HTML produced when this block is used in the mobile app and web.

## Step-by-step reproduction instructions

**The steps for reproducing it are:**
1. In the app
    1. Create/edit a post
    2. Add a video block
    3. Insert a video
    4. Save the post
2. In the web
    1. Open the post
    2. Observe that the HTML code is different when changing to code editor
    3. Save the post
3. In the app again
    1. Open the post
    2. Observe that the video block shows an error

**NOTE:** This issue can be also reproduced by adding a video block in the web version and then opening the post in the mobile app.

As an example, here is the HTML produced in each case:

## Native app (WPiOS)
```
<!-- wp:video {"id":<MEDIA_ID>} -->
<figure class="wp-block-video"><video controls src="<VIDEO_SRC>"></video></figure>
<!-- /wp:video -->
```

### When opened first time with code editor:
```
<!-- wp:video {"autoplay":false,"id":<MEDIA_ID>,"loop":false,"muted":false,"src":"<VIDEO_SRC>"} -->
<figure class="wp-block-video"><video controls src="<VIDEO_SRC>"></video></figure>
<!-- /wp:video -->
```

### When opened with visual editor:

**In this case the web version generates a preview, maybe this is related to why it produces a different HTML code.**

```
<!-- wp:video {"autoplay":false,"guid":"<VIDEO_GUID>","id":<MEDIA_ID>,"loop":false,"muted":false,"src":"<VIDEO_SRC>","videoPressClassNames":"wp-block-embed is-type-video is-provider-videopress"} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/<VIDEO_GUID>?preloadContent=metadata
</div></figure>
<!-- /wp:video -->
```

## Expected behaviour

The video should be displayed in the mobile app.

## Actual behaviour

The video is not displayed in the mobile app.

## Screenshots or screen recording (optional)

<img src=https://user-images.githubusercontent.com/14905380/115363127-7b57a180-a1c2-11eb-8446-8fa2412efc48.jpeg width=400>

## WordPress information
- WordPress version: N/A
- Gutenberg version: v10.4.1
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: 17.0.1.0

**Comment by fluiddot** [comment] 2021-04-20 08:38
On Android, it produces a block validation error when testing with a debug build (see attached screenshot).

I saw that we already have an issue, in this case [related to the Cover block](https://github.com/WordPress/gutenberg/issues/28972), that shows a similar error, maybe both issues are caused by the same problem 🤔 .

<img src=https://user-images.githubusercontent.com/14905380/115365176-6c71ee80-a1c4-11eb-9dd7-909f5429ef4e.jpg width=400>

**Comment by jd-alexander** [comment] 2021-09-14 12:03
Thanks for the investigation you did here @fluiddot so I can confirm what you have suggested. On the web, it seems the video content of the blocks is converted to an embed hence the failure. 

An initial idea, I had was to utilize the `replaceBlock` functionality from the `blockEditorStore` to make the block compliant and valid ( [Done here](https://github.com/WordPress/gutenberg/commit/868f444a1110f4378d1aec5bef2917cf8711921f)) as a fallback mechanism within the `BlockInvalidWarning` native component as this is done in the web variant. This worked to an extent, however, the problem I ran into is that the `src` is stripped from the attributes.
The PR that introduced this change is https://github.com/WordPress/gutenberg/pull/11410 I think its approach has stripped the attributes. 

----
Below is how the Video block looks as an Embed block, and it also shows that it's not playable in the mobile app due to the missing `src`.
```
 {"attributes": {"autoplay": false, "caption": "", "className": "wp-block-embed is-type-video is-provider-videopress", "controls": false, "id": 369, "loop": false, "muted": false, "playsInline": false, "preload": "metadata", "tracks": []}, "clientId": "3281c2c6-1fbf-4cc1-b93b-07170c78723e", "innerBlocks": [], "isValid": false, "name": "core/video", "originalContent": "<figure class=\"wp-block-video wp-block-embed is-type-video is-provider-videopress\"><div class=\"wp-block-embed__wrapper\">
https://videopress.com/v/eIfxnIud?resizeToParent=true&amp;preloadContent=metadata
</div></figure>"}
```

<kbd><img src="https://user-images.githubusercontent.com/1509205/133252930-c9decc4b-7f15-41a2-92f5-f50683b299d8.png" width="320"></kbd>

------
A solution to this may be to create a rollback mechanism on mobile that replaces the Embed blocks in `Video` and `Cover` blocks that are upgraded on the web.

**Comment by fluiddot** [comment] 2021-09-14 14:09
> Thanks for the investigation you did here @fluiddot so I can confirm what you have suggested. On the web, it seems the video content of the blocks is converted to an embed hence the failure.

Good catch 🎊 !

> An initial idea, I had was to utilize the `replaceBlock` functionality from the `blockEditorStore` to make the block compliant and valid ( [Done here](https://github.com/WordPress/gutenberg/commit/868f444a1110f4378d1aec5bef2917cf8711921f)) as a fallback mechanism within the `BlockInvalidWarning` native component as this is done in the web variant. This worked to an extent, however, the problem I ran into is that the `src` is stripped from the attributes.
> The PR that introduced this change is #11410 I think its approach has stripped the attributes.
> 
> Below is how the Video block looks as an Embed block, and it also shows that it's not playable in the mobile app due to the missing `src`.
> 
> ```
>  {"attributes": {"autoplay": false, "caption": "", "className": "wp-block-embed is-type-video is-provider-videopress", "controls": false, "id": 369, "loop": false, "muted": false, "playsInline": false, "preload": "metadata", "tracks": []}, "clientId": "3281c2c6-1fbf-4cc1-b93b-07170c78723e", "innerBlocks": [], "isValid": false, "name": "core/video", "originalContent": "<figure class=\"wp-block-video wp-block-embed is-type-video is-provider-videopress\"><div class=\"wp-block-embed__wrapper\">
> https://videopress.com/v/eIfxnIud?resizeToParent=true&amp;preloadContent=metadata
> </div></figure>"}
> ```

I'm wondering why the `src` is not being included 🤔. I did a quick test and I saw that the `src` attribute was present when switching to HTML mode in the web version of the editor, so maybe the native version of the Video block is the one that is stripping out the `src` when loading the post, does it make sense?
 
> A solution to this may be to create a rollback mechanism on mobile that replaces the Embed blocks in `Video` and `Cover` blocks that are upgraded on the web.

Yeah, that's a good option although we should investigate potential side effects.

**Comment by jd-alexander** [comment] 2021-09-15 17:06
> I'm wondering why the src is not being included 🤔. I did a quick test and I saw that the src attribute was present when switching to HTML mode in the web version of the editor, so maybe the native version of the Video block is the one that is stripping out the src when loading the post, does it make sense?

Interesting. That's a hypothesis worth checking out. 👍🏾

**Comment by SiobhyB** [comment] 2022-05-19 10:19
To tie up all the pieces to this I've found in my investigations so far: I've only been able to reproduce this behaviour on WP.com sites or sites connected to the Jetpack plugin (with VideoPress enabled). Videos uploaded to self-hosted sites without any plugins that automatically change the video block, like VideoPress, displayed as expected within the app.

There's an older issue related to this here, also, that outlines some discussions and possible solutions, particularly in [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152#issuecomment-738817171): https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152

There are also some other related issues that may be resolved by addressing this, such as https://github.com/wordpress-mobile/gutenberg-mobile/issues/3292.

I'm planning to look into recreating the PR in https://github.com/WordPress/gutenberg/pull/15674 to improve the way unsupported blocks are handled.

**Comment by fluiddot** [comment] 2024-01-18 12:02
I'm re-opening the issue as I managed to reproduce a similar issue to this one when testing version 24.0. I tested previous versions (from 24.0 to 23.5) and can also be reproduced in old versions. No error is displayed within the Video block but it's rendered as empty (see attached video capture).

https://github.com/WordPress/gutenberg/assets/14905380/19a7ee5f-c075-4aa1-8f0a-05bccf96a71e

**Comment by fluiddot** [comment] 2024-01-18 17:40
I noticed that this regression was introduced in this change https://github.com/WordPress/gutenberg/pull/49858. After further investigations, I checked the following cases and found two scenarios for the condition:

https://github.com/WordPress/gutenberg/blob/3f010e6c72a04cd6f314d1061842cf40c3b68daa/packages/block-library/src/video/edit.native.js#L239-L242

## Scenarios

### Video uploaded (hosted in VideoPress)
```
<!-- wp:video {"id":1234} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/<VIDEO_FILE>.mp4"></video></figure>
<!-- /wp:video -->
```

* Source can be validated with `src` attribute.

### Video from media library:
```
<!-- wp:video {"id":1234} -->
<figure class="wp-block-video"><video controls src="https://<SITE>.files.wordpress.com/<VIDEO_FILE>.mp4"></video></figure>
<!-- /wp:video -->
```

* Source can be validated with `src` attribute.

### Video from URL
```
<!-- wp:video -->
<figure class="wp-block-video"><video controls src="http://<VIDEO_FILE>.mp4"></video></figure>
<!-- /wp:video -->
```

* Source can be validated with `src` attribute.

### Video uploaded from the web (hosted in VideoPress)
```
<!-- wp:video {"guid":"ABCD1234","id":1234,"videoPressClassNames":"wp-block-embed is-type-video is-provider-videopress"} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/<VIDEO_ID>
</div></figure>
<!-- /wp:video -->
```

* Source can be validated with `guid` and `id` (these two parameters are the ones needed to generate a VideoPress video URL).

### Post created in the app and saved on the web with videos (hosted in VideoPress)
```
<!-- wp:video {"id":1234} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/<VIDEO_FILE>.mp4"></video></figure>
<!-- /wp:video -->
```

**is converted to:**

```
<!-- wp:video {"guid":"ABCD1234","id":1234,"videoPressClassNames":"wp-block-embed is-type-video is-provider-videopress"} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/<VIDEO_ID>
</div></figure>
<!-- /wp:video -->
```

**NOTE:** It also transforms Video blocks that point to media URLs (e.g. `https://<SITE>.files.wordpress.com/<VIDEO_FILE>.mp4`).

* Source can be validated with `guid` and `id` (these two parameters are the ones needed to generate a VideoPress video URL).

## Conditions

1. For most cases, we can simply check if attribute `src` is empty (current implementation).
2. For other cases, specific to VideoPress videos, we need to check the presence of `guid` and if `id` is empty.

<hr>

I'll open a PR with a temporary workaround, as the VideoPress case, should not be handled in the core block.

**Closed as completed** 2024-01-22 09:59 UTC
Labels: [Type] Bug, [Priority] High, [Status] In Progress, Mobile App - i.e. Android or iOS
