### ISSUE TITLE
When editing a page in the site editor, blocks inside Post Content should be directly selectable

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51259] opened 2023-06-06 09:15 UTC
If you open a Page in the Site Editor (Pages > Page > Edit), you cannot directly select blocks inside Post Content – The Post Content block itself is selected first. Since you cannot _do_ anything with the Post Content block in this context, this adds some friction to the experience. 

Notice in the video below that I have to click twice to select the Image block:

https://github.com/WordPress/gutenberg/assets/846565/570c45e0-ff9a-4d05-b8e8-58056f8fee19

Would making child blocks of Post Content directly selectable be worth a try? 

cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment] 2023-06-06 09:18
Consistency seems to be the most important thing to find here. What is the intended behavior for selecting blocks in this context? Is it the clickthrough as applied here? How, generally, are we applying clickthrough these days? Is it a part of the new content/template editing split?

**Comment by jameskoster** [comment] 2023-06-06 09:35
Yes it would be good to define that more clearly.

The original intent for the click-through pattern was to help indicate when you're working with something beyond the scope of the original edit focus. For example: Selecting a header while editing a template, or; selecting a Reusable block while editing a page.

But now that we have purple colorisation of synced blocks, it may no longer be necessary. Especially if https://github.com/WordPress/gutenberg/issues/50796 is implemented. 

In any case, since the 'edit focus' in this flow is the _page_, having to click through the Post Content block feels a bit unnecessary.

**Comment by paaljoachim** [comment] 2023-06-06 11:12
First off all it is important for a user to really understand when a template is being edited compared to post/page content.
That means making a clear differentiation between template vs post content. If these slide too much into each other it can become very confusing.

**Brain storming.** 

1- Let's say that clicking the Post Content block brings up a kind of message overlay of the block asking the user if they want to edit the post/page content.

2- Let's say that clicking the Post Content block shows something similar to a Reusable block.
![Screenshot 2023-06-06 at 13 04 39](https://github.com/WordPress/gutenberg/assets/5323259/5986e433-5291-4ecd-a4cb-680f24e41d1d)

2- Or something like a template part.
![Screenshot 2023-06-06 at 13 07 03](https://github.com/WordPress/gutenberg/assets/5323259/c4552aa1-325f-4ab7-9271-78ed23e150e7)

The main point is that we are now seeing the edit of a post gradually merge with editing a template. For the Front Page and Home templates that can work nicely. As they each only affect the front page and the blog page. The more difficult part is when the same gradual merge applies to a page template or post template. What does the Post Content block look like in a Page or Post Template? Should it look different compared to where the template only affects one page?

Example. Post Content for the Front page and Blog can be seen in the templates.
Post Content for multiple pages should be different as it can not show content as this varies from page to page.

**Comment by jameskoster** [comment] 2023-06-06 15:40
> Let's say that clicking the Post Content block brings up a kind of message overlay of the block asking the user if they want to edit the post/page content.

This feels unnecessary to me. If a user has navigated through the Pages panel, selected a page, and clicked edit... isn't it implied that they want to edit the page content?

**Comment by paaljoachim** [comment] 2023-06-06 21:57
Hey James.
Will one see Post Content when editing a page in the Pages panel? Ok it sounds like it. I believe a few different PR's need to land before I get a better perspective on what this will look like. 

So I got to say yes to your question there. As one is editing a page it is implied that they want to edit the page content.

**Comment by aurooba** [comment] 2023-06-08 00:18
But you would select the Post Content block if you wanted to move it around using the arrows in its toolbar. I can see an argument for that being a secondary action for which a person could go and purposefully select the Post Content block from the breadcrumbs or list view if needed, but I agree with @jasmussen that consistency is more important here.

**Comment by jameskoster** [comment] 2023-06-08 08:47
> But you would select the Post Content block if you wanted to move it around using the arrows in its toolbar

The Post Content block cannot be moved when you're editing the page because it's part of the template. The toolbar doesn't even appear. Those kind of actions can only be performed when editing the template. That's another reason why it feels particularly strange for Post Content to be selected before you can work with any child blocks.

**Comment by aurooba** [comment] 2023-06-08 16:19
> The Post Content block cannot be moved when you're editing the page because it's part of the template.

Oooh, this must be a feature that hasn't landed in a stable release of Gutenberg yet (I haven't updated to 16 RC yet), because I am able to move the post content block when I'm in the page editor within the site editor (in Twenty Twenty Three). And it definitely looks different from your video recording. Is this part of the upcoming release?

https://github.com/WordPress/gutenberg/assets/6925260/4143bf14-c9e9-4489-b8cb-3a8d981209ce

**Comment by SaxonF** [comment] 2023-06-09 03:39
+1 . Added to the [follow up list](https://github.com/WordPress/gutenberg/pull/50857)

**Comment by jameskoster** [comment] 2023-06-09 12:11
> Is this part of the upcoming release?

That's correct, apologies I should have made that clearer!

**Closed as completed** 2023-06-23 04:30 UTC
Labels: Needs Design Feedback, [Feature] Site Editor, [Feature] Page Content Focus
