### ISSUE TITLE
"Updating failed" error and cannot change permalink and preview is not working

### ISSUE THREAD

**Issue by topkhoj** [WordPress/gutenberg#8412] opened 2018-08-03 04:28 UTC
TypeError: Cannot read property 'show_ui' of undefined
    at https://topkhoj.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533269593:12:302843
    at i (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:6:91)
    at An.filter (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:99:338)
    at https://topkhoj.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533269593:12:302808
    at yh (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:96:396)
    at lg (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://topkhoj.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)

**Comment by caxco93** [comment] 2018-08-03 05:29
Could you please share with us **where** and **when** did you get this error?

**Comment by topkhoj** [comment] 2018-08-03 05:41
Today, I got an update for WordPress 4.9.8 after updating the WordPress it suggested me to install Gutenberg editor plugin. And when I tried the editor I got this error.
Currently, I'm also not getting Yoast Seo suggestion tool below the Gutenberg editor or in the sidebar of the editor. Can you suggest me how to add focus keyword, meta description, edit permalink, and slug?

**Comment by pento** [comment] 2018-08-03 05:52
Thank you for the details, @topkhoj!

The Yoast team are currently working on their full Gutenberg support, so there may be some features that aren't quite available yet. I'd suggest contacting Yoast support for more info.

For editing the permalink/slug, if you click on the post title, you'll see the current permalink and an edit button you can use.

**Comment by gziolo** [comment] 2018-08-03 05:54
We should also improve the handling of custom taxonomies to ensure they don't impact Gutenberg itself. This is where we can do much better:
https://github.com/WordPress/gutenberg/blob/94f54892c214ebd014ec126a9575b7e902198ad9/packages/editor/src/components/post-taxonomies/index.js#L21

**Comment by topkhoj** [comment] 2018-08-03 06:17
Thanks for your suggestions @pento, but I'm not getting the option for editing the permalink/slug. Another error is the post preview is also not working.
Here is screecshots - [https://docs.google.com/document/d/1jkh_VTqyiZYHyU2xsAgqnNCI7Kdb0DjpkvC5zXSiaLI/edit?usp=sharing](https://docs.google.com/document/d/1jkh_VTqyiZYHyU2xsAgqnNCI7Kdb0DjpkvC5zXSiaLI/edit?usp=sharing)

**Comment by pento** [comment] 2018-08-03 06:38
To be able to edit the permalink, you'll need to select a permalink structure other than "Default", there should be a link to the permalink settings page when you click on the title.

For post preview, the "Updating Failed" message you're seeing suggests that Gutenberg wasn't able to talk to the REST API properly. Do you have any security plugins that might be disabling the REST API? Also, if you use CloudFlare, there's a problem with the CloudFlare WAF that they're working on a fix for. There's a [workaround here](https://github.com/WordPress/gutenberg/issues/2704#issuecomment-41009093) that you can use.

**Comment by youknowriad** [comment] 2018-08-04 15:41
Thanks for the report, I'm going to close this one as a duplicate of #8441 and #8456, Let's try to consolidate all CloudFlare issues in the same one.

**Closed by youknowriad** 2018-08-04 15:41 UTC
Labels: [Type] Help Request
