### ISSUE TITLE
Adding an image block after an image aligned to the side produces unexpected behavior

### ISSUE THREAD

**Issue by LZL0** [WordPress/gutenberg#6634] opened 2018-05-08 08:51 UTC
## Issue Overview
Adding an image block after an image aligned to the side produces unexpected behavior resulting in the misplacement of the second image and all other boxes after the second image.

## Steps to Reproduce (for bugs)
1. Create an image block, align it to the left
2. Create another image block, leave it as is, don't apply an alignment
3. Try to create a rich text field

Tested with Chrome 67 and Opera 53 (Chrome 66).

## Expected Behavior
The second image should be displayed properly (including the resize dots and "Write caption..." text) and the rich text block should be placed after the second image.

## Current Behavior
The added (second) resize handlers and the "Write caption..." text is on the top in line with the first image, while the image is displayed below the first image block. If there meta boxes are present the second image will be displayed behind them. After adding a paragraph to the bottom of the post it will be then placed somewhere inside the second image.
**Important:** Interestingly, the problem will not occur until the secondary image is selected from the media gallery/uploaded.

## Screenshots / Video
https://www.youtube.com/watch?v=bta1vBdC0cc
https://youtu.be/UmHcQpGXOtw

The same thing occurs if the second image block is set to "center."

**Comment by LZL0** [comment] 2018-05-08 11:56
Found the possible source of the issue. When I get back I will add a fork request for it.

**Comment by danielbachhuber** [comment] 2018-05-10 12:29
Thanks for the report, @LZL0.

#4127 is related. I believe the true source of the problem is that we don't _know_ what our expected behavior is. Specifically, whether: 1) blocks should clear one another, or 2) it should be possible to align blocks around one another. We need to make this decision before we can identify the appropriate fix.

**Comment by LZL0** [comment] 2018-05-10 19:00
I respectfully disagree. My apologies for not uploading a video explaining the issue.
This, of course, is just a possible solution to the issue.
https://youtu.be/JOobYdR1Ihs

**Comment by danielbachhuber** [comment] 2018-05-10 19:07
> I respectfully disagree.

Which part do you disagree with? The video you've uploaded doesn't appear to be playable.

**Comment by LZL0** [comment] 2018-05-10 19:13
https://youtu.be/UmHcQpGXOtw

**Comment by karmatosed** [comment] 2018-05-19 20:57
It seems that #4127 and #4010 are where the focus for this should be, unless I am mistaken? I feel clearing floats makes sense and in this case with nesting and the adaptions that gives we're moving away from this as an issue. For now closing, but we can always reopen.

**Closed by karmatosed** 2018-05-19 20:57 UTC
Labels: Needs Design Feedback, [Type] Bug
