### ISSUE TITLE
Image block caption link input field disappears when clicked into

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#5479] opened 2018-03-07 15:28 UTC
## Issue Overview
The Image block supports a caption field. The caption field supports highlighting and links. When attempting to create a link I found cases where clicking into the "Paste URL or type" field caused the field to disappear... so I was unable to create the link.

Note: The focus was already in the input field... so I could have just started typing.

## Steps to Reproduce (for bugs)

1. Insert an Image block
2. Upload an image
3. Type a caption
4.Select part of the caption and click on Link
5. Click into the "Paste URL or type" input field
6. The input field disappears, the backgrounds of the blocks turn blue and
7. Sometimes the More Options tooltip appears.

## Expected Behavior
The "Paste URL or type" placeholder disappears then I can start typing the URL.

## Current Behavior
I have no idea what's actually happened. 
It looks like two blocks get selected. 

I discussed this briefly with @aduth, but it took me a long time to reproduce the issue.
When the problem occurs it's easy to reproduce.

## Possible Solution
No idea. The problem could be related to 
- the block immediately below the image block 
- or the fact that the image borders are selected 
- or that the image sizes are not yet available in the Additional block settings. 
- or I'm just clicking badly.

## Screenshots / Video

![issue-click-image-caption-link-field](https://user-images.githubusercontent.com/2474435/37099668-d9ce24f0-2218-11e8-9cb0-c1bafcea17aa.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ajitbohra** [comment] 2018-07-08 13:43
Unable to reproduce this on the master. Hence closing this for now, feel free to reopen.

**Closed by ajitbohra** 2018-07-08 13:43 UTC
Labels: Media, [Type] Bug
