### ISSUE TITLE
env: chown: cannot access 'wp-config.php' when running wp-env start

### ISSUE THREAD

**Issue by tmdk** [WordPress/gutenberg#29814] opened 2021-03-12 10:24 UTC
## Description
While testing the fixes from https://github.com/WordPress/gutenberg/pull/29800 using the `trunk` version of wp-env, running `wp-env start` fails with the following error:

```
✖ Error while running docker-compose command.
chown: cannot access 'wp-config.php': No such file or directory
```

Using this `.wp-env.json` file:

```
{
  "plugins": [
    "."
  ]
}
```

I think there might be a timing issue with the docker image not having finished copying the WordPress files, when listing the contents of /var/www/html right before the chown is executed, only three directories are listed, and no files. Also, it seems to be working on another machine, but not on my (not so beefy) laptop.

Furthermore, adding `"core": "WordPress/WordPress"` to `.wp-env.json` seems to be a workaround, which makes sense because wp-env does wait for WP files to be copied when using external core sources.

## Step-by-step reproduction instructions
1. Create a directory containing the `.wp-env.json` described above.
2. Run `wp-cli start` (using the version from `trunk`) in the created directory.

## Expected behaviour
wp-env environment comes up successfully

## Actual behaviour
command fails

## WordPress information
- WordPress version: latest from docker image
- Gutenberg version: `trunk`
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

**Comment by ribaricplusplus** [comment] 2021-03-12 11:41
I'm giving this a go

**Comment by ribaricplusplus** [comment] 2021-03-12 13:16
Well it seems there are quite a few issues here. Unfortunately I don't have time to sort all of this out now. But I have some pointers for the next person who works on this (which might end up being me later when I have time if no one else does it).

I was not able to reproduce this issue.

This is where the issue happens.

https://github.com/WordPress/gutenberg/blob/877f61535c7064fbcd845b0b7f841b12dbfc6bbd/packages/env/lib/commands/start.js#L137-L147

`makeConfigWritable` should be moved a few LoC below into `shouldConfigureWp` conditional. That can be done right now, doesn't seem to break anything.

I think this is broken
https://github.com/WordPress/gutenberg/blob/877f61535c7064fbcd845b0b7f841b12dbfc6bbd/packages/env/lib/commands/start.js#L153-L158
these lines of code are never going to execute because it doesn't seem that `config.coreSource` ever exists. I think the check is meant to be "Is core set to null in `.wp-env.json`?" but I'm not sure how exactly to best do that check. `config.core` doesn't seem to work.

When the aforementioned "is core null" check is fixed, `makeConfigWritable` and  `makeContentDirectoriesWritable` can be merged into a single function and called together.

This issue could be fixed by doing retries for chown if it fails, just like it's done for the MySQL database below, but the thing is that the problem should never even arise because we await for containers to go up... So, they should be up and ready, this issue shouldn't happen.

**Comment by tmdk** [comment] 2021-03-12 15:33
> This issue could be fixed by doing retries for chown if it fails, just like it's done for the MySQL database below, but the thing is that the problem should never even arise because we await for containers to go up... So, they should be up and ready, this issue shouldn't happen.

Well, the copying to /var/www/html happens in the docker entrypoint before `exec`ing php-fpm, so it would be wrong to assume that copying has finished when `docker-compose up -d` returns. You only know that the entrypoint is running.

**Comment by gagan0123** [comment] 2021-03-18 19:08
@tmdk 
I think this issue is fixed in the latest wp-env release on npm two days ago(version 0.4.0).
Can you please try updating the wp-env package(`npm -g i @wordpress/env`) and run the command again?

**Comment by TimothyBJacobs** [comment] 2021-03-19 00:00
I also got this error using version `4.0.0`. Specifying `"core": "WordPress/WordPress"` worked for me as well to fix that error.

**Comment by tmdk** [comment] 2021-03-26 14:25
@ribaricplusplus your fix in https://github.com/WordPress/gutenberg/pull/30053 works for me 👍

**Closed** 2021-04-09 00:36 UTC
Labels: [Package] Env, [Status] In Progress
