### ISSUE TITLE
Gallery block: Empty space on front-end when an empty image block is added

### ISSUE THREAD

**Issue by SiobhyB** [WordPress/gutenberg#39612] opened 2022-03-21 13:43 UTC
### Description

When an empty image block is added to a gallery and saved, it creates an empty space, both in the editor and on the site's front-end.

My expectation would be for empty image blocks to have no impact on the gallery's appearance on the front-end. 

This was first brought up in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4317. It can be replicated in both the mobile app and on the web.

### Step-by-step reproduction instructions

1. Add a gallery block to the Gutenberg editor.
2. Upload some images to the gallery.
3. Select an image within the gallery and then select the block inserter (+) to add an empty image block.
4. Save the post and preview the gallery.
5. Verify that an empty space appears in the position where the empty image block was added.

### Screenshots, screen recording, code snippet

The following is a recording of the steps to reproduce on the web:

https://user-images.githubusercontent.com/2998162/159274642-29eb3a8e-8550-456f-ab73-b3fc33dec979.mov

The following video shows the steps to replicate the issue in the mobile app, including a preview of the site's front-end where the empty image placeholder can be viewed:

https://user-images.githubusercontent.com/2998162/144097814-6f4dd1bf-8b89-4c59-a612-e906018ca05b.mov

### Environment info

Tested in both the latest version of the WordPress Android app and the latest version of Gutenberg running on a WordPress.com site.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2022-03-21 20:54
This is replicating the behaviour of the Image block, which also adds an empty `figure` and `img` tag to the frontend markup if no image is selected for the block - it is just more noticeable in the Gallery due to the grid layout:

https://user-images.githubusercontent.com/3629020/159361894-b54ef28b-7861-476e-bbcc-2257fb708e76.mp4

I wonder if we also want to remove the empty tags for the standalone Image block, or if there is a reason why these are left in the frontend markup?

**Comment by NicoHood** [comment] 2022-08-24 21:39
Is it possible to remove this extra box around the image? My usecase is a bit different, I want to have this visual space, but only for the large, not the mobile gallery. I want each row to have the same column size, but that seems currently not possible, isnt it?

**Comment by ramonjd** [comment] 2022-08-30 05:28
~What about adding the following in [render_core_block_image](https://github.com/WordPress/gutenberg/blob/7f0a211da6603b336b75b75d8235a50bf547e6f3/packages/block-library/src/image/index.php#L16)?~

Sorry, ignore my comment - only relevant to images in a gallery.

 I just saw https://github.com/WordPress/gutenberg/pull/39952

**Comment by t-hamano** [comment] 2023-12-08 12:09
This issue cannot be reproduced with trunk and appears to be resolved by #45220 and #55269.

## Image Block

### Editor

There is an image block with no media set between two paragraphs.

![editor](https://github.com/WordPress/gutenberg/assets/54422211/ebb26573-6e65-4800-a552-d52924567a97)

### Frontend

Nothing is rendered between the paragraph blocks.

![frontend](https://github.com/WordPress/gutenberg/assets/54422211/6c19ea21-d58b-44da-8baa-d8f2db4ebc57)

## Gallery Block

### Editor

Contains two image blocks with no media set.

![editor-gallery](https://github.com/WordPress/gutenberg/assets/54422211/0798c82e-42b9-4481-ad2a-1ce4eeec33c2)

### Frontend

Empty image blocks are not rendered and there are no empty columns.

![frontend-gallery](https://github.com/WordPress/gutenberg/assets/54422211/7c4ffefa-68db-4145-b587-ab9fbd58f674)

I would like to close this issue, but please let us know if you are still experiencing issues.

**Closed as completed by t-hamano** 2023-12-08 12:09 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Gallery
