### ISSUE TITLE
Site Editor: Image cropping tools broken

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38557] opened 2022-02-07 03:47 UTC
### Description

Cropping in the site editor seems broken across multiple levels compared to in the post editor:
- The aspect ratio tools don't work/don't have any effect.
- The zooming is out of control (best way I can put it) and you aren't able to really use it to get what you want.
- The ability to move where the image is zoomed in on is no longer available.
- The greying out of what you are cropping out isn't visible. 
- The image itself seems to get outsized from the cropping tools/easily out of frame in a way that feels very broken.

This only seems to happen in the Site Editor. I could replicate this across two different sites with 5.9.

### Step-by-step reproduction instructions

1. Open Site Editor.
2. Add an image
3. Try to crop.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/152721340-69604b20-029d-484b-bf6d-c7a8df3e3bf7.mp4

### Environment info

- WordPress 5.9
- With Gutenberg 12.5.3 and without Gutenberg
- TT2
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by costdev** [comment] 2022-02-08 02:46
I can reproduce the behaviour.

**Zoom**
- Post Editor: The image does not spread outside of the container as you zoom.
- Site Editor: The image container doesn't seem to be clipped via `overflow: hidden` (or similar), so the image spreads outside of the container as you zoom.
- Both Editors: Moving the zoom slider to max, clicking _Apply_, moving the zoom slider to max again and clicking _Apply_ again, makes the image smaller. Not what I expected.

**Aspect ratio**
- Post Editor: There is masking to show what the aspect ratio will look like.
- Site Editor: There is no masking to show what the aspect ratio will look like. However, clicking _Apply_ will correctly change the aspect ratio.

**Rotation**
- Both editors: Seems fine, I think.

**Comment by Mamaduka** [comment] 2022-02-08 10:03
I think this might be an issue with the `react-easy-crop` library and iframed editors. The styles are injected in parent windows instead of the iframe.

cc @talldan.

**Comment by ajlende** [comment] 2022-02-08 16:28
I tested manually adding `react-easy-crop/react-easy-crop.css` to a style element in the iframe. The appearance was fixed, but dragging to position the crop was still not working. So fixing it might be more involved than just manually adding the styles to the iframe.

There's more info in the react-easy-crop docs about [loading styles](https://github.com/ricardo-ch/react-easy-crop#styles).

**Comment by dugyen** [comment] 2022-02-21 15:38
@annezazu I could also see it in a different way. 
How could I reproduce 

1.  WordPress 5.9 and TT2 with our without latest Gutenberg. 
2. Add a duotone filter to a Cover block with an image or video in it and add text over top, adjusting the opacity as needed.
3. Add an image to the background of your header.
4. Publish your WordPress Post/Page with above steps. 
5. Here you could see the your image is not crop as it should be. 

https://user-images.githubusercontent.com/21174885/154986002-54ed9c70-d623-4abf-9e62-aa53d9fa8aa8.mp4

**Comment by annezazu** [comment] 2022-02-21 19:33
Thanks for the video here! I'm wondering what's going on since your image dimensions are showing -1777 for width and -1918 for height 😱 . I tried to replicate but couldn't even if I tried adding duotone and text. Here's a condensed video:


https://user-images.githubusercontent.com/26996883/155016750-d6982302-f290-47db-a592-14be030d0f53.mov

**Comment by annezazu** [comment] 2022-09-05 21:51
This is still a problem with GB 14.0.2 and WP 6.0.2:

https://user-images.githubusercontent.com/26996883/188515240-4823afb6-26d8-40ba-baca-cb8bf5ff5c5f.mp4

Going to add this to the 6.1 board just in case it can be addressed.

**Comment by talldan** [comment] 2022-09-19 08:16
I've removed the 'Backport to WP Beta/RC' label as that's just for PRs.

> cc @talldan.

I don't know much about it unfortunately, I just refactored some of the code to make fixing a bug easier. IIRC though, pretty much everything was implemented by that easy-cropper library, apart from rotation, which is our own implementation. Rotation seems to be working ok, so it'd suggest the bulk of the issues are to do with react-easy-cropper/iframes.

> I tested manually adding react-easy-crop/react-easy-crop.css to a style element in the iframe. The appearance was fixed, but dragging to position the crop was still not working. So fixing it might be more involved than just manually adding the styles to the iframe.

@ajlende Would you be able to create a PR with this change? A partial fix would be better than nothing.

**Comment by dugyen** [comment] 2022-09-19 09:42
@talldan @vcanales @annezazu will this fix be seen in WordPress 6.1

**Comment by talldan** [comment] 2022-09-19 09:46
@dugyen The target is to get a fix for WordPress 6.1, but there isn't any working code that resolves the issue yet. There's a bit of a risk as well because the feature depends on a third-party library, but hopefully it's something that can be solved. 👍

**Comment by glendaviesnz** [comment] 2022-09-20 00:52
Had a brief look and I think we would either need to fork the library, or see if we can push back a change to the project. Currently the lib makes a number of calls to the global `window` and `document` which will need to instead happen on the iFrame doc and window in the case of the site editor.  

It shouldn't be too hard to sort in theory, by either adding some props to pass in the doc and window references, or to work them out using one of the refs within the component, similar to what happens in the [Jetpack maps block](https://github.com/Automattic/jetpack/pull/19552/files#diff-f000f0971bb099cff4a472237c057a4b7eb64a7739ca58ed4b2e16cf815d0892R8) to gets its 3rd party library to work in the site editor.

I will try and take a look and see if we can get this fixed, but if it involves getting a patch accepted by the library it may not be doable in 6.1 timeframes.

**Comment by ajlende** [comment] 2022-09-20 18:53
> see if we can push back a change to the project

@ValentinH was very responsive when I made some changes to react-easy-crop earlier, so unless he's especially busy, I think there's a good chance of landing the change.

@glendaviesnz it sounds like you have a plan for fixing it already, but I'll be here to help out with testing if you have a branch pushed up that I can take a look at.

**Comment by ValentinH** [comment] 2022-09-20 19:35
Hey, `react-easy-crop` maintainer here 👋
Yes, I'm available to review a PR and provide guidance if needed. It would be a pity if you had to fork 😅

**Comment by glendaviesnz** [comment] 2022-09-21 00:09
thanks @ajlende and @ValentinH, if my cunning plan works I should have a PR up in the `react-easy-crop` repo sometime tomorrow - will be back in touch for help if my plan turns out to not be as cunning as I imagined 😄

**Comment by annezazu** [comment] 2022-09-21 03:00
Love this cross collaboration. Thanks so much for chiming in and offering to help @ValentinH!

**Comment by glendaviesnz** [comment] 2022-09-22 05:26
@ValentinH [this approach](https://github.com/ValentinH/react-easy-crop/pull/410) seems to work for our iframed instance, but not sure if it has any potential issues/drawbacks in other contexts.

**Comment by glendaviesnz** [comment] 2022-09-23 03:42
A [PR in the 3rd party library](https://github.com/ValentinH/react-easy-crop/pull/410) is ready for review

**Comment by glendaviesnz** [comment] 2022-09-23 05:17
[PR to bring in the updated version of react-easy-crop here](https://github.com/WordPress/gutenberg/pull/44408)

**Comment by glendaviesnz** [comment] 2022-09-26 20:15
Fixed by https://github.com/ValentinH/react-easy-crop/pull/410 & https://github.com/WordPress/gutenberg/pull/44408

**Closed as completed by glendaviesnz** 2022-09-26 20:15 UTC
Labels: [Type] Bug, [Type] Regression, [Block] Image
