### ISSUE TITLE
Adjusting link text and clicking to open in a new tab closes link modal without saving the adjustments

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#45741] opened 2022-11-13 09:49 UTC
### Description

When I open an existing link and adjust the text and then also click Open in new tab the link dialog box suddenly closes without the adjustments being saved.

I have to do two operations.
Open a link and change the link text. Click the enter symbol to close it.

Open the link again and then click the Open in new tab and then click the enter symbol to close it.

### Step-by-step reproduction instructions

1. Create a link.
2. Open the existing link.
3. Change the link text.
4. Click the Open in new tab toggle.
5. Notice the link modul closes and does not save the changes.

---> It should not close the link modal before I click enter on my keyboard or the enter symbol in the link modal.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5323259/201515745-1cd2b3bc-d222-4741-8fbe-72738195d67b.mp4

### Environment info

WordPress 6.1
Gutenberg plugin 14.5
Theme: Twenty Twenty Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-11-15 14:21
This issue was reviewed in today's Editor Bug Scrub. I was able to confirm this issue. I do think some design feedback is needed on the correct way to handle this. My thought is toggling the "Open in new tab" should never close the modal. This would require an additional click outside the modal to close, but I think it's unintuitive that toggle the setting auto-closes the modal. 

Quick note, this issue also seems related to https://github.com/WordPress/gutenberg/issues/35795 and [#40892](https://github.com/WordPress/gutenberg/issues/40892).

**Comment by richtabor** [comment] 2022-11-15 14:32
> My thought is toggling the "Open in new tab" should never close the modal. 

Agreed.

**Comment by paaljoachim** [comment] 2022-11-15 15:14
As one has the link modal open and does does various things. It should close on clicking the enter symbol or clicking enter on the keyboard.

> My thought is toggling the "Open in new tab" should never close the modal.

I too agree.

**Comment by javierarce** [comment] 2022-11-29 11:25
+1 to prevent closing the modal

I think this is a duplicate of [this older issue](https://github.com/WordPress/gutenberg/issues/25946)

**Comment by paaljoachim** [comment] 2022-12-02 03:57
Thanks for finding that @javierarce ..:)

I noticed that @getdave Dave made the older issue. Perhaps he or someone else might be able to take a closer look.

**Comment by getdave** [comment] 2022-12-02 09:58
These issues are likely come increasingly into focus as a result of the work on [the Nav block offcanvas experiment](https://github.com/WordPress/gutenberg/issues/41549#issuecomment-1333735733).

**Comment by hz-tyfoon** [comment] 2023-05-05 18:57
I'm amazed that this issue exists since `Oct 8, 2020` and it's not yet fixed.

I spent an almost 1.5 hours of going through all the conversations here and the related issues (#49091) & spent another 2.5 hours reading the codebase and trying to understand it & finally going for a fix. 

Created a PR just now to the `wp/6.2` branch as the trunk branch's current work isn't merged with WordPress core. 
But,
I'd really appreciate for any feedback if any change needed or if anything can be improved.

PR: #50401

**Comment by richtabor** [comment] 2023-05-23 19:07
Accomplishing https://github.com/WordPress/gutenberg/issues/50890 will resolve this issue as well.

**Comment by getdave** [comment] 2023-06-06 12:44
@paaljoachim Should now be fixed by https://github.com/WordPress/gutenberg/issues/50945

**Closed as completed by getdave** 2023-06-06 12:44 UTC
Labels: [Type] Bug, Needs Design Feedback, [Feature] Link Editing

**Comment by paaljoachim** [comment] 2023-06-06 13:24
Great! Thanks Dave @getdave !
