### ISSUE TITLE
Add support for custom post types in navigation editor

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34440] opened 2021-09-01 09:32 UTC
## What problem does this address?

The current menu screen, allows for custom post types to be added to menu. This includes both custom post type posts and archives. See screenshot from current editor. 

<img width="299" alt="Screenshot 2021-09-01 at 10 28 48" src="https://user-images.githubusercontent.com/237508/131648021-2603f2f8-abe2-4472-b2b1-3f807d0a16f4.png">

However these custom post types are not reflected in navigation editor. 

<img width="436" alt="Screenshot 2021-09-01 at 10 31 30" src="https://user-images.githubusercontent.com/237508/131648151-b7709cad-5a2d-4dda-92f8-9c3a6493bd79.png">

## What is your proposed solution?

Add support for custom post types in navigation editor

**Comment by talldan** [comment] 2021-09-21 09:18
This is supposed to be supported, but it does seem like a bug has crept into the navigation block.

I registered a custom 'Books' post type, and this is what I see in the inserter:
<img width="343" alt="Screenshot 2021-09-21 at 5 16 45 pm" src="https://user-images.githubusercontent.com/677833/134145325-767213dc-409a-431b-8e86-f0ab9b82700d.png">

There are two Post Link block variations! I'm pretty sure the second one is supposed to be Books.

**Comment by talldan** [comment] 2021-09-21 09:51
Did some more digging, and I've changed my mind, I don't think this is a regression, but just a shortcoming of how the block variation's title is handled:
https://github.com/WordPress/gutenberg/blob/44062c586af16dcb0c7ae376f38d2de16b2ed81c/packages/block-library/src/navigation-link/index.php#L258-L263

A lot of variations probably won't have an `item_link` property, but from what I recall the custom post type's labels are merged with the base labels object for a Post, which is why 'Post Link' is shown. I think it should probably fallback to `singular_name` or `name`, but it'll be tricky to detect the absence of an `item_link`.

**Comment by spacedmonkey** [comment] 2021-09-27 17:07
@talldan How does this work, if `show_in_rest` is false but `show_in_nav_menus` is true? This means that post type can be shown in menus but we can't get the data via the REST API?

Also, is there any way to use the post type's icons as the block icon?

**Comment by kathrynwp** [comment] 2022-09-21 18:53
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!

**Closed as not planned by kathrynwp** 2022-09-21 18:53 UTC
Labels: [Block] Navigation, [Block] Navigation Link
