### ISSUE TITLE
First bock toolbar hidden by site header in FSE

### ISSUE THREAD

**Issue by hawkmusician** [WordPress/gutenberg#27840] opened 2020-12-21 09:25 UTC
**Describe the bug**
The Block Toolbar is hidden for the first block by the site header in FSE when not enough elements are present to make the page scroll (then it appears).

**To reproduce**
1. Go to Site Editor
2. Add a new block
3. Block toolbar is hidden if it is the first block
4. Add cover block + others to make the page scrollable (long enough). Toolbar appears for first block.

**Expected behavior**
The toolbar should be available at all times.

**Screenshots**

![hiddentoolbar](https://user-images.githubusercontent.com/23136551/102761051-ab0eae00-4376-11eb-8d2b-15f1de343558.PNG)

**Editor version**
- WordPress version: 5.6
- Gutenberg installed, version 9.6RC

**Comment by annezazu** [comment] 2020-12-29 19:38
@hawkmusician thanks for reporting this! I tried to replicate with WordPress 5.6 and Gutenberg 9.6.2 but was unable to do so. Each time, the first block still showed the toolbar. Can you confirm this happens with all other plugins except Gutenberg deactivated?

<img width="1130" alt="Screen Shot 2020-12-29 at 12 37 56 PM" src="https://user-images.githubusercontent.com/26996883/103309590-b98e4280-49d2-11eb-91b5-dac28c9d9d89.png">

**Comment by hawkmusician** [comment] 2020-12-30 07:37
Hi @annezazu. Thanks for taking a look at this. 

Tested again on WordPress 5.6 and Gutenberg 9.6.2 with TT1 theme and still getting this issue, although less pronounced. 

https://user-images.githubusercontent.com/23136551/103336843-b306d600-4a79-11eb-8712-d2a301b6695f.mp4

I think this has to do with the margins that are applied to the blocks themselves. In my last screenshot, I had deactivated margins on blocks which makes me understand that the toolbar stays contained within `.edit-site-visual-editor` which would create some trouble in FSE when there isn't enough top margin to stop the toolbar being hidden by the header.

**Comment by annezazu** [comment] 2021-01-04 19:23
Thanks so much for this video. I'll make this as a bug as I was able to replicate the same issue when I had a template part at the very top of the Site Editor.

**Comment by carolinan** [comment] 2021-03-02 05:24
I am no longer able to reproduce this (Gutenberg 10.1.0-rc.1)

**Comment by annezazu** [comment] 2021-03-03 22:16
Ditto with the full 10.1 release. Closing out but feel free to re-open if it returns :)

**Comment by melchoyce** [comment] 2021-04-13 19:25
I'm encountering this issue in Gutenberg 10.3.2, creating a new block theme. I added a navigation block to the top of my page, but I can't edit it because the toolbar overlaps:

![image](https://user-images.githubusercontent.com/2846578/114609148-79df2400-9c6c-11eb-8996-64d0b5693189.png)

**Comment by carolinan** [comment] 2021-04-14 02:50
This was also found during user testing on April 9 using 10.3.2.

**Comment by skorasaurus** [comment] 2021-06-25 19:57
still present in 10.9.1

**Comment by skorasaurus** [comment] 2021-08-31 18:35
I'm no longer able to reproduce this thanks to https://github.com/WordPress/gutenberg/pull/33981 :) 

This will be added into Gutenberg 11.5. :)

**Closed by skorasaurus** 2021-08-31 18:35 UTC
Labels: [Type] Bug, [Feature] Full Site Editing, [Feature] Site Editor
