### ISSUE TITLE
Font Library: Improve Error Message

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55328] opened 2023-10-12 23:28 UTC
## What problem does this address?
Good error messages are essential for good UX. 
The current error message is rather on the bad spectrum, because the users do not get any information other than "it didn't work".
Additionally, currently the error message automatically disappears after a few seconds, which definitely shouldn't happen.

<img width="2339" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/930ac49d-93d2-4faf-abd5-7de7538be361">

## What is your proposed solution?
There are a lot info out there about how to write better error messages. Let's focus at least on one aspect: Show a error code, so that people at least can google on what went wrong. The console has some more info, so let's use it.

**Comment by Mamaduka** [comment] 2023-10-13 05:54
Duplicate of #54777.

**Closed as completed by Mamaduka** 2023-10-13 05:54 UTC
Labels: [Status] Duplicate, [Feature] Typography
