### ISSUE TITLE
Gutenberg just doesn't work on a clean WP 4.9.8 installation

### ISSUE THREAD

**Issue by mlopezcoria** [WordPress/gutenberg#8480] opened 2018-08-04 07:05 UTC
**Describe the bug**
I installed Gutenberg using the dashboard 'Try Gutenberg' button and activated it. After that when I select 'New Post' i get a blank screen. Even thou I've enabled debug log display on WP config and also enabled the display errors options within php.ini, I'm not getting any error message

**To Reproduce**
1. Go to 'WP Dashboard'
2. Click on 'Try Gutenberg'
3. Activate Gutenberg
4. See blank page

5. Click on 'New post'
6 See blank page

7 Go to 'WP Dashboard'
8 Click on 'Try Gutenberg' again
9 See blank page

**Expected behavior**
It should display the new Gutenberg editor in a new post

**Screenshots**
![screenshot_2018-08-04 add new post mauricio s blog wordpress](https://user-images.githubusercontent.com/15494802/43673515-cc0159ee-979a-11e8-80c2-62bb9419b396.png)

**Server:**
 - OS: GNU/Linux CentOS 7.5
 - Web Server: Apache/2.4.6
 - WP Plugins activated: just Gutenberg 3.4.0

***Desktop:
 - OS: GNU/Linux Manjaro 17.1.11
 - Browser Firefox 61.0.1 and Chrome 68.0.3440.84

**Additional context**
- Gutenberg version 3.4.0

**Comment by youknowriad** [comment] 2018-08-04 07:41
Closing as duplicate of #8455

**Closed by youknowriad** 2018-08-04 07:41 UTC
