### ISSUE TITLE
Newline on empty list item does not create new paragraph

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#5416] opened 2018-03-05 16:11 UTC
## Issue Overview

Normally when in a bullet list, starting a new line on an empty bullet point eliminates that empty bullet point and starts a new paragraph. Instead, nothing happens, and there is no way to start a new paragraph without clicking on the inserter UI

## Steps to Reproduce (for bugs)

1. create a list block
2. add several items
3. create a new item but instead of typing an item, press return

## Expected Behavior

When in a list block, and a newline is started, if there is nothing in that list item, remove it and move to a new paragraph block

## Current Behavior

Nothing happens and the user is stuck in the list item block

## Screenshots / Video

<img width="765" alt="screen shot 2018-03-05 at 16 10 29" src="https://user-images.githubusercontent.com/58855/36985657-c4abc7c4-208f-11e8-97ec-5d190ace8818.png">

No amount of return or key pressing will create a new paragraph when the cursor is on that last bullet point item

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment] 2018-03-05 17:10
Duplicate of #5284 

Fixed by #5409

**Closed by aduth** 2018-03-05 17:10 UTC

**Comment by newscloud** [comment] 2019-01-09 07:00
I'm seeing this repro at https://jeffreifman.com/2019/01/09/states-health-insurance-marketplace-toxic-to-entrepreneurs-self-employed ... an extra empty li was added to the end of a list regardless of what I did to clean up below it.

I had to insert distinct lists e.g. multiple ul blocks for each item :(

WordPress 5.02

Doubt it's theme related since it's an empty unstyled li

**Comment by aduth** [comment] 2019-01-09 13:39
@newscloud You should be able to press Enter from the last empty item of the list to drop it.
