### ISSUE TITLE
Bad style for post thumbnail with Svg images

### ISSUE THREAD

**Issue by hamedmoody** [WordPress/gutenberg#41181] opened 2022-05-20 04:06 UTC
### Description

When I allow Svg upload and set as post thumbnail it has bad style

### Step-by-step reproduction instructions

1. Add below code to functions.php
`add_filter( 'upload_mimes', function ( $mimes ){
	$mimes['svg'] = 'image/svg+xml';
	$mimes['svgz'] = 'image/svg+xml';
	return $mimes;
});`
2. Go to Post > new
3. Upload Svg image
4. You can see bad style

### Screenshots, screen recording, code snippet

You can see ticket [#55778](https://core.trac.wordpress.org/ticket/55778) in wordpress core track or [click here](https://core.trac.wordpress.org/raw-attachment/ticket/55778/invalid-svg-style-as-thumbnail.PNG)

### Environment info

Wordpres 6.0 RC3

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-05-20 04:31
Thanks for contributing, @hamedmoody.

I think this is a duplicate of #5477.

**Closed as completed** 2022-05-20 04:32 UTC
Labels: [Feature] Document Settings, [Feature] Media, [Status] Duplicate
