### ISSUE TITLE
Image options are not visible in pop up on clicking replace button from Image block

### ISSUE THREAD

**Issue by speedyprem** [WordPress/gutenberg#28601] opened 2021-01-29 16:28 UTC
## Description
Image options are not visible in pop up on clicking replace button from Image block due to the horizontal scroll.

## Step-by-step reproduction instructions
1.Create new article.
2.Add image block.
3.Add any image inside the image block.
4.Click on replace button from the image block.

## Expected behaviour
Options such as Open Media Library, Upload, Current Media URL is not visible from the pop up due to horizontal scroll bar.

## Actual behaviour
Image options are not visible in pop up on clicking replace button from Image block due to horizontal scroll.

## WordPress information
- WordPress version: 5.6.0
- Are you using a default theme: Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Mac book Pro
- Browser: Chrome 86

**Comment by talldan** [comment] 2021-02-01 03:19
@speedyprem Thanks for reporting. This sounds like the same issue as #27186, so I'll close this issue as a duplicate of that one.

**Closed by talldan** 2021-02-01 03:19 UTC
