### ISSUE TITLE
Display icons in select field

### ISSUE THREAD

**Issue by ravishakya** [WordPress/gutenberg#14236] opened 2019-03-05 10:25 UTC
For a project I want to add font awesome icons but it is not possible. It would be great if we can add icons in select field.

eg.
![alt text](https://camo.githubusercontent.com/528bfa2ba0d92a8747fa06cab0e841b65c71284f/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323736333136372f3839363830322f30386131373561632d666165362d313165322d396161372d6162643833363664396534312e706e67)

**Comment by youknowriad** [comment] 2019-03-05 11:28
Thanks for the issue, this is a duplicate of #9780

There's no such use-case in Core at the moment to warrant creating one, you can create any third party icon picker in your plugins. Closing as "wontfix" for the moment but we can revisit later.

**Closed by youknowriad** 2019-03-05 11:28 UTC
