### ISSUE TITLE
How to: Re-render edit() after setAttributes() in edit()?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7238] opened 2018-06-08 21:56 UTC
Regarding this documentation page:
https://wordpress.org/gutenberg/handbook/block-api/block-edit-save/

```
test: { type: 'array', default: [1, 2, 3] },

edit: function( props ) {
	return el( 'div', {
		onClick: function(){
			var newTest = [4, 5, 6];
			props.setAttributes({ test: newTest });
		},
	}, props.attributes.test );
}
```

How to re-render displayed attribute `props.attributes.test` right after `onClick` and without de-selecting and selecting the block to trigger `edit()` again?

**Comment by mattyrob** [comment] 2018-06-09 16:33
I think I ran into a similar issue to this, I was told that `setAttributes` is asynchronous so you should not rely on the value being updated immediacy after `setAttributes` is called.

You need to find a way to pass the new value back in edit(), so in the above example instead of returning `props.attributes.test` you'd return the new value of 123456.

**Comment by manake** [comment] 2018-06-09 17:58
I need to correct this:

1. When I update only one "array" attribute then `setAttribute` doesn't trigger `edit()` again.
```
items: { type: 'array', default: [] },
```

2. But when I `setAttribute` for any `string` then `edit()` is triggered again.

It looks like a bug to me.

**Comment by aduth** [comment] 2018-06-10 23:57
It should be expected that `edit` will automatically be called any time an attribute of the block changes, notably by your own `setAttributes`. So it should not be your own responsibility to ensure that anything happens after the `onClick`s `setAttributes` to force the render. 

This is in-line with the [React way of thinking](https://reactjs.org/tutorial/tutorial.html), where `edit` is effectively describing what should be shown given the set of parameters, notably the block's attributes.

That you aren't seeing `edit` being called again with the `setAttributes` does sound unintentional. I tried recreating, but from my own testing, it appears to work exactly as expected. Here's the entire block code I'm using:

```js

( function( blocks, element ) {
    var el = element.createElement;

    blocks.registerBlockType( 'my-demo/demo-block', {

            title: 'Demo Block',

            icon: 'format-aside',

            category: 'common',

            attributes: {
                test: { type: 'array', default: [1, 2, 3] },
            },

            edit: function ( props ) {
                return el( 'div', {
                    style: { height: '20px' },
                    onClick: function(){
                        var newTest = [4, 5, 6];
                        props.setAttributes({ test: newTest });
                    },
                }, props.attributes.test );
            },

            save: function () {
                return el( 'div' );
            }

    } );
} )(
	window.wp.blocks,
	window.wp.element
);
```

When I click the block, the `edit` is called again, with the new updated `test` attribute, and the block is serialized as:

```html
<!-- wp:my-demo/demo-block {"test":[4,5,6]} -->
<div class="wp-block-my-demo-demo-block"></div>
<!-- /wp:my-demo/demo-block -->
```

Note the array attribute.

Can you check to see if your attribute types are defined in an `attributes` property like in my snippet above?

**Comment by aduth** [comment] 2018-06-11 00:15
I'm going to close this in favor of #7242 as the original question has been answered (it should render automatically on `setAttributes`), just to keep focus on a single issue for additional debugging of the array-type specific issue.

**Closed by aduth** 2018-06-11 00:15 UTC
Labels: [Type] How Do I?

**Comment by mikethicke** [comment] 2020-02-15 02:55
I'm having this same issue of the block not re-rendering when I use setAttribute to change the value of an array.

In the following code, if I click the checkbox in InspectorControls, neither the checkbox nor the editor content will re-render until I force a render by clicking away and back on the block or something like that. However, if I uncomment ```// a_boolean: ! a_boolean``` both will re-render as expected.

```js
import { InspectorControls } from '@wordpress/blockEditor'
import { CheckboxControl } from '@wordpress/components';
import { registerBlockType } from "@wordpress/blocks";
import { Component } from '@wordpress/element';

const edit = class EditComponent extends Component {

    render() {
        const { attributes, setAttributes } = this.props;
        const { an_array, a_boolean } = attributes; 
        return [
            <>
                <InspectorControls>
                    <CheckboxControl 
                        label = 'Checkbox'
                        checked = { an_array[0] === 1 }
                        onChange = { ( val ) => { 
                            an_array.push( an_array[0] );
                            val ? an_array[0] = 1 : an_array[0] = 0;
                            setAttributes( {
                                an_array: an_array,
                                // a_boolean: ! a_boolean
                            } );
                        } } 
                    />
                </InspectorControls>
                <div>
                    Array: { an_array.toString() }
                </div>
            </>
        ];
    }

}

registerBlockType('test/array-not-update', {
    title: 'Array Attribute Change Issue',
    icon: 'universal-access-alt',
    category: 'layout',
    attributes: {
        an_array: {
            type: 'object',
            default: []
        },
        a_boolean: {
            type: 'boolean',
            default: false
        }
    },
    edit,
    save() { return null; },
});
```

**Comment by aduth** [comment] 2020-02-26 18:49
@mikethicke The problem is that you're mutating the attribute, not creating a new value, so the editor does not detect that a change has occurred.

That logic boils down to `nextAttributeValue !== previousAttributeValue`

[`Array#push`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) will not create a new value, so these are equal:

```js
const { an_array, a_boolean } = attributes;
const previousAttributeValue = an_array;
an_array.push( an_array[0] );
const nextAttributeValue = an_array;
console.log( previousAttributeValue === nextAttributeValue );
// true
```

The simplest solution would be to use [`Array#concat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) instead, which will create a new array:

```js
const nextArray = an_array.concat( an_array[0] );
```

At one point, I think there was a suggestion to freeze attribute values or warn when they're mutated, at least in development environments, to help developers avoid this common pitfall.

**Comment by aduth** [comment] 2020-02-26 18:51
Not exactly the same, but very similar: #7252

**Comment by markhowellsmead** [comment] 2020-03-02 17:04
My head's spinning a bit with this one. I've been battling with it, but can't get my head around it. I've tried @aduth's suggestion above, to no avail.

I have a set of block `attributes`. One of them is an array of image (attachment) IDs, which is passed to `MediaUpload` with `multiple={true}` and `gallery={true}` in order to indicate which images are selected.

By studying the Gallery core block, I can see that I need to pass `undefined` to the `MediaUpload` component if there are no images, as passing an empty array results in **all** images being pre-selected. Thus:

    value={!!this.props.attributes.ids.length ? this.props.attributes.ids : undefined}

In the block I'm battling with, I have a reset button which calls the following function `onClick`:

    function resetImages() {
        this.props.setAttributes({ ids: [] });
    }

This fires the re-rendering and the result is that the `ids`  attribute is an empty array, as expected. This leads to `value={!!this.props.attributes.ids.length ? this.props.attributes.ids : undefined}` passing `undefined` to the `MediaUpload` as expected.

But the formerly selected images are still selected in the Media Gallery.

**Comment by mikethicke** [comment] 2020-03-02 22:28
@aduth 's solution worked for me. Thanks! I see why Array.push wasn't triggering a re-render, but this seems like a very counterintuitive way for things to work.

@markhowellsmead I'm not sure if this is the same issue that I was having. If you toggle another attribute, does it cause the selected images to update in Media Gallery? Are you sure it's a rendering issue?

**Comment by markhowellsmead** [comment] 2020-03-04 16:24
Thanks for the feedback. Firstly, I misread the Gallery block: it uses the `MediaPlaceholder`, where I'm using the `MediaUpload` component. The basic issue is the same, though. I've opened a new issue for this: https://github.com/WordPress/gutenberg/issues/20627.
