### ISSUE TITLE
Group block does not enlarge to contain left or right aligned images

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#15182] opened 2019-04-25 15:41 UTC
**Describe the bug**
When you add an image to a group block and you left or right align the image, the group block does not expand to encapsulate the image in it.

**To reproduce**
1. Create a group block (I added a background color for clarity)
2. Add a paragraph block and an image block with a tall image. Align the image next to the paragraph.
3. Save and check the page.

**Expected behavior**
I would expect the group block to expand to contain all blocks in it.

**Screenshots**
![screenshot-robinroelofsen nl-2019 04 25-17-36-33](https://user-images.githubusercontent.com/7248645/56748803-c334c100-6780-11e9-8381-d542dcb7f071.png)

(Creating a manual to use the editor... in Dutch)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103

**Additional context**
WP: 5.1.1
Gutenberg: 5.5.0

**Comment by youknowriad** [comment] 2019-08-23 09:32
that's how regular divs and floats work I think. The solution would be to add a `clearfix` at the end of the div but I'm not sure that we want to that by default or let the user add the classname to the container on its own.

cc @kjellr @jasmussen

**Comment by jasmussen** [comment] 2019-08-23 10:20
Ah was confused by the screenshot for a second. Inside the gray box is a screenshot showing parts or the editor :) 

This is correct and intended behavior for the `float` property. I agree as a user that does not seem intuitive or even appropriate. Therefore we will be adding an option to "clear" the float in #10299 which needs a developer. That way you'd be able to open the advanced section for the group block, and toggle a "Clear floats" switch which would then contain the image inside the group.

However making the group block clear floats by default, I suspect, would cause more problems than it solves, given it would prevent intended use of the float behavior entirely. So I would recommend closing this ticket in favor of #10299.

**Comment by youknowriad** [comment] 2019-08-23 11:09
Thanks for the clarification 👍

**Closed by youknowriad** 2019-08-23 11:09 UTC
Labels: General Interface, [Block] Group, [Block] Image, [Type] Bug
