### ISSUE TITLE
Missing alignment options for reusable-blocks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#14811] opened 2019-04-04 01:05 UTC
**Describe the bug**
Currently only "center" is available for alignment of reusable-blocks, 
but not "left" and "right" as with other blocks.

**To Reproduce**
1. Insert a reusable block.
2. If necessary, first select "edit" for the reusable block.
3. Notice that for alignment only "center" is available.

**Expected behavior**
"left" and "right" should also be available for alignment.

**Comment by youknowriad** [comment] 2019-04-11 08:54
In my testing, the reusable blocks don't have any alignment options and that's intended because they are just "virtual wrappers" around other blocks that can be aligned. For example, you can use a "section / group" block around a reusable block to align it left or right.

**Comment by aduth** [comment] 2019-04-22 15:28
Given https://github.com/WordPress/gutenberg/issues/14811#issuecomment-482028594 , closing as "Working as Intended" and providing a workaround using the Group block to align as wide or full. Other alignment options are applied to the block itself being made reusable.

Otherwise, there'd need to be more information here. The reusable block doesn't have any alignment options. I believe those seen when selecting "Edit" are specific to the block made reusable (e.g. a paragraph block).

**Closed by aduth** 2019-04-22 15:28 UTC
Labels: [Component] Reusable Blocks, [Status] Needs More Info, [Type] Enhancement, [Type] Help Request

**Comment by strarsis** [comment] 2019-04-22 18:45
And how can I then align a reusable block? E.g. I inserted a reusable block that wraps a section block and 
I want to align it to the left on page A but to the right on page B.

**Comment by aduth** [comment] 2019-04-29 18:43
@strarsis Could you have the reusable block be nested within the section block?

**Edit:** I see the alignment options for section are constrained. I'm not sure I understand the reason for this, though I think in general this is probably how it would be encouraged to align a reusable block, and layouts in general, to lean more on nested blocks to provide the functionality of layouts (columns, section, etc). In that light, it may be good to either reopen this issue or create a new issue which is aimed directly at the alignment options for the section block. What do you think?

**Comment by strarsis** [comment] 2019-04-29 22:25
@aduth: Even when the reusable block is nested inside the group (formerly section) block,
instead having the group block inside the reusable block, there is still no alignment option for the resuable block.

**Comment by aduth** [comment] 2019-04-30 12:42
I sense that's because there _are_ alignment controls, but they're limited to "Wide" and "Full", which a theme must opt-in as supporting.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#wide-alignment

If your theme doesn't support these alignments, they won't be shown.

As mentioned though, I don't see a particularly compelling reason why the alignment options ought to be limited (why to not allow for left, right, etc).

**Comment by strarsis** [comment] 2019-04-30 12:46
@aduth: +1, there is no reason for limiting the alignment options, the reusable block is a block like any other block and alignment of elements inside the reusable block can't leak out anyway.
