### ISSUE TITLE
Default Browser Behavior of CTRL + HOME/END Does Not Work

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11726] opened 2018-11-10 23:12 UTC
**Describe the bug**
CTRL + HOME moves cursor to the beginning of the _current block_. CTRL + END moves the cursor to the end of the _current block_.

**To Reproduce**
1. Place cursor at start post with at least 2 paragraph blocks
1. Alternate between `CTRL` + `END` and `CTRL` + `HOME`

![ctrl home-end](https://user-images.githubusercontent.com/1238696/48307092-a2422180-e4fa-11e8-8b73-3c33a438a420.gif)

**Expected behavior**
WordPress 4.9.8 shows the expected behavior:
![ctrl home-end-expected](https://user-images.githubusercontent.com/1238696/48307097-aff7a700-e4fa-11e8-881e-f9c54cce456c.gif)

A default `<textarea>` also displays the expected behavior:
![ctrl home-end-expected-textarea](https://user-images.githubusercontent.com/1238696/48307132-76736b80-e4fb-11e8-8b43-c92e36920236.gif)

**Desktop (please complete the following information):**
Win 10, Firefox 63/Chrome 70, WP 5.0-beta3, no plugins, Twenty Nineteen

**Comment by designsimply** [comment] 2018-11-11 16:50
Thanks for reporting! Closing this one as a duplicate of #8353.

**Closed by designsimply** 2018-11-11 16:50 UTC
Labels: Writing Flow, [Status] Duplicate
