### ISSUE TITLE
Table of Contents Plus plugin brings some bugs when used with Gutenberg

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#10523] opened 2018-10-11 16:00 UTC
**Describe the bug**
The Table of Contents Plus plugin brings some bugs when used with Gutenberg. I have only activated the following plugins: Table of Contents Plus and Gutenberg. Nothing else. 

1) Some Layout Bugs: http://prntscr.com/l4xipc
2) The shortcode cannot be inserted. The article cannot be saved: http://prntscr.com/l4xk9b

![download 1](https://user-images.githubusercontent.com/1119271/47102521-3a016800-d1fa-11e8-94f1-6418c67c3445.png)

![download 2](https://user-images.githubusercontent.com/1119271/47102526-3cfc5880-d1fa-11e8-8748-82eb41cf5efc.png)

**To Reproduce**
1. Go to 'pages'
2. Click on 'edit' and insert the shortcode from Table of content plus
3. See error

**Expected behavior**
That the article is saved and that no display errors occur.

**Screenshots**
http://recordit.co/f6NRQEohhT

**Desktop (please complete the following information):**
 - Win 10
 - Chrome
 - Version 69

**Additional context**
- Please add the version of Gutenberg you are using in the description: 3.9

**Comment by SchneiderSam** [comment] 2018-10-15 15:51
Yes, that's true. But the problem is: I need this flexibility otherwise the other pages will collapse. And then I'd rather wait until a plugin can do both.

**Comment by designsimply** [comment] 2018-10-17 16:59
Thank you for testing Gutenberg and filing a note about plugin incompatibilities! 

slimmilkduds is correct that the best place to report depends on what the problem is and the first best place to start is in the support forum for the plugin to ask the plugin author if they are able to check on the plugin and update to work with the latest version of WordPress. What we can do to help you from here is provide a place to log such cases and help you learn what to report to the plugin author that will be the most helpful to them.

Plugin link for reference: https://wordpress.org/plugins/table-of-contents-plus/

Where to report issues: https://wordpress.org/support/plugin/table-of-contents-plus

As a troubleshooting step, check whether you are able to save a page without the `[TOC]` shortcode to see if the problem only happens when the shortcode is present or if it happens any time the Table of Contents Plus plugin is active.

If you are able to open the Console and Network panels using your browser's web developer tools while attempting to publish and catch the errors from there, it may help pinpoint the problem and shed some light that will be helpful to whomever volunteers to make updates (the plugin author or perhaps a developer who would like to contribute).

From there, I would recommend copying the steps to reproduce (everything from above, that looks great!) and either a copy of any errors found in the Console/Network browser developer tools or a screenshot if that's easier and posting to https://wordpress.org/support/plugin/table-of-contents-plus

**Comment by SchneiderSam** [comment] 2018-10-18 18:05
> As a troubleshooting step, check whether you are able to save a page without the `[TOC]` shortcode to see if the problem only happens when the shortcode is present or if it happens any time the Table of Contents Plus plugin is active.

Done! And now it works fine. Definitely a TOC+ bug. But I can't insert a short code either: http://prntscr.com/l7nbcv

> If you are able to open the Console and Network panels using your browser's web developer tools while attempting to publish and catch the errors from there, it may help pinpoint the problem and shed some light that will be helpful to whomever volunteers to make updates (the plugin author or perhaps a developer who would like to contribute).
>

This one? http://prntscr.com/l7nc16
And this one: http://prntscr.com/l7ncpm

> From there, I would recommend copying the steps to reproduce (everything from above, that looks great!) and either a copy of any errors found in the Console/Network browser developer tools or a screenshot if that's easier and posting to https://wordpress.org/support/plugin/table-of-contents-plus

Ok!

**Comment by youknowriad** [comment] 2018-12-25 09:40
I think there's nothing we can do from the Gutenberg side here, I'm closing this issue. Let's reopen if there's any actionable item. Thanks.

**Closed by youknowriad** 2018-12-25 09:40 UTC
Labels: [Type] Plugin / Theme Interoperability
