### ISSUE TITLE
Editor screen is showing content from a different post.

### ISSUE THREAD

**Issue by fredbradley** [WordPress/gutenberg#7468] opened 2018-06-22 10:34 UTC
**Describe the bug**
My Gutenberg Editor is constantly showing POST ID 9 of my posts table, rather than the `post` in the uri query string. 

This means I can't actually edit any page with Gutenberg?

**To Reproduce**
WP 4.9.6. Gutenberg 3.1.0
the primary site of a Multisite, with Custom Post types. (Worth saying that ID 9 is a custom post type, rather than just a post, and not the post type I'm intending to view!) 

Click to edit any post of _*any*_ post type. 

**Expected behavior**
The edit screen of the item you clicked on (and of the item that URI Query string suggests)

**Screenshots**
Not applicable/private information

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser CHROME
 - Version, latest

**Additional context**
- Gutenberg 3.1.0

**Comment by easilyamused** [comment] 2018-06-22 19:44
I'm also having this issues, however if I click on classic edit it the correct content.

**Comment by fredbradley** [comment] 2018-06-22 20:14
@easilyamused Yes - as in it's the Gutenberg editor that is picking up the wrong ID somehow. ?

**Comment by easilyamused** [comment] 2018-06-22 20:15
That's what it looks like to me with my debugging.

**Comment by fredbradley** [comment] 2018-06-22 20:16
@easilyamused Also  - are you on a Multisite install of a normal single site?

**Comment by easilyamused** [comment] 2018-06-22 20:20
Single site, I have a multisite setup using the Gutes, but did not install after this bug popped up.

All my settings seem to be the same as your @fredbradley too.

**Comment by opicron** [comment] 2018-06-23 14:34
Can confirm, happening on custom post/page types for me too.

**Comment by danielbachhuber** [comment] 2018-06-27 13:44
Hi folks,

Some follow-up questions:

* Does the issue reproduce with all other plugins deactivated?
* Are you able to reproduce the issue with a fresh WordPress install?

**Comment by easilyamused** [comment] 2018-07-07 09:57
@danielbachhuber I have not checked and I did not try on a fresh Install. However I do have done new news. 

This issues does not seam to be a problem in 3.0.1 and before(Have been using the Gutes since the beginning).

Today I tried Gutenberg on a site for the first time on a new host and everything seemed fine for the first 9ish hours. I converted 19 pages without any real problems. I even edited some of them too. Was super happy the grid for nested blocks was fixed(not related). Then the problem showed back up. This might seem crazy but as soon as all pages where Gutenberg pages, the problem showed back up. That last detail could be coincidence. 

The new site is running the current versions of all core, theme, and plugins. Its on storefront(Woocommerce site, and on a standalone(not the cheap hosting) at GoDaddy. Was messing up on Pantheon when I first reported the issue.

Also the classic edit works. When i click on edit, Gutenberg loads but  not the right content. We know that from above, but what's weird is that its loading a post not even a page. And what is even weirder is the version of the post that is loading is a pre converted post that I converted to use the new editor already. So, it might even be pulling the wrong content and from an older version. 

I will report on a different ticket, but the save seems to be hanging. It will save but the save never stops trying or at lest looking like its trying to save. A refresh seems to work and the saved data is there.

I know this is a lot of vague info and happy to provide more if I know what was needed.

**Comment by easilyamused** [comment] 2018-07-09 18:44
After more research, and looking at ticket #7833, it seems to be related to posts with shortcodes that query other post content. Pages with out shortcodes work fine. I have not debug different types of shortcode yet. The live page is https://www.freshfarmscbd.com/. The case studies is a blog category.

**Comment by thebugfixnet** [comment] 2018-07-10 15:36
'List Category Posts' did issue an update last night to the plugin. Error caused by that Plugin seems now to be fixed.

**Comment by annestk** [comment] 2018-07-10 18:19
Can confirm I'm experiencing the same error.

For me, it occurs only when the plugin [Display Posts Shortcode](https://wordpress.org/plugins/display-posts-shortcode/) is active, and the post I want to edit with Gutenberg contains a display posts shortcode.

**Comment by billerickson** [comment] 2018-07-10 20:55
I believe this is related to a bug in WP where wp_reset_postdata() doesn't work in the backend ([WP core ticket #18408](https://core.trac.wordpress.org/ticket/18408)). 

Is Gutenberg running the shortcodes to generate a preview? 

I think this should be something that is addressed in WordPress core, but Gutenberg could probably work around it by manually resetting the post data after shortcode previews are complete.

**Comment by danielbachhuber** [comment] 2018-07-10 21:36
> Is Gutenberg running the shortcodes to generate a preview?

Gutenberg runs shortcodes when it calls `GET /wp/v2/posts/<id>` on the initial pageload. 

https://core.trac.wordpress.org/ticket/18408 seems like it'd be the cause of the problem. If the shortcode sets up the global `$post`, but isn't able to reset it, then Gutenberg could load data some some erroneous `$post` data.

**Comment by aduth** [comment] 2018-07-11 12:56
Related: #7582 (previously #7461)

**Closed** 2018-07-11 23:53 UTC
Labels: Framework, [Type] Bug

**Comment by danielbachhuber** [comment] 2018-08-18 14:03
Hey @nmschaller,

Yes, the issue is fixed in the latest version of Gutenberg. It's been fixed as of Gutenberg 3.3.

**Comment by nmschaller** [comment] 2018-08-19 06:56
Thanks a lot, @danielbachhuber.
