### ISSUE TITLE
Editor doesn't consistently show content (or editor tools/panels)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#1293] opened 2017-06-20 09:38 UTC
On a number of occasions I've tried to edit existing (Gutenberg) content, and I simply get a blank page.

https://cl.ly/340F1b3O3k1v

**Comment by youknowriad** [comment] 2017-06-20 09:39
Could this be related and fixed by #1245

**Comment by jasmussen** [comment] 2017-06-20 09:42
It looks like the same issue I get when I insert the freeform block, open the "More" ellipsis, then click outside the block to deselect it.

**Comment by aduth** [comment] 2017-06-20 17:23
Closing as duplicate of #1235. Please reopen with additional information if it's not the same.

**Closed by aduth** 2017-06-20 17:23 UTC
