### ISSUE TITLE
Template Revisions Option Not Showing Until the Third Change is Made

### ISSUE THREAD

**Issue by upwardmomentum84** [WordPress/gutenberg#54503] opened 2023-09-15 14:09 UTC
### Description

When editing a template in Appearance > Editor, the template revisions option doesn't show until the third change is made.

I would expect the revisions option to show after ANY changes are made.

### Step-by-step reproduction instructions

1. Open a template for editing (be sure any customization made previously were cleared).
2. Make a change and then save.
3. Repeat step 2, after the third change is made, the "revisions" option shows in the sidebar.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/93800099/9dfb6d9c-0995-4458-abec-55fcf9b44f70

### Environment info

WP 6.3.1
Gutenberg 16.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by upwardmomentum84** [comment] 2023-10-19 03:05
The issue is still present in GB 16.8.1.

**Comment by annezazu** [comment] 2024-01-11 19:17
Might be related: https://github.com/WordPress/gutenberg/issues/49164

**Comment by annezazu** [comment] 2024-01-11 19:19
I can replicate this using WP 6.4.2 and GB 17.4.1. Adding to the 6.5 board as this feature will be available starting in 6.5.

**Comment by Mamaduka** [comment] 2024-02-06 07:05
@annezazu, the cause of the problem is the same as in #49164. I think we can close this one as a duplicate.

**Comment by annezazu** [comment] 2024-02-06 18:35
Agreed! Closing out.

**Closed as completed by annezazu** 2024-02-06 18:35 UTC
Labels: [Type] Bug, [Feature] History
