### ISSUE TITLE
BlockFormatControls and related SlotFills now exist on secondary toolbar. No longer "Top Toolbar"

### ISSUE THREAD

**Issue by JustinSainton** [WordPress/gutenberg#33619] opened 2021-07-22 02:07 UTC
## Description

BlockFormatControls and related SlotFills used to be a part of the Top Toolbar when the "Top Toolbar" toggle was checked. Now, they all exist on a secondary toolbar, not the Top Toolbar. Lots of our publishing clients are finding this to be sub-optimal.

## Step-by-step reproduction instructions
I recorded a video showing exactly what I'm talking about. But essentially, you don't need any special theme or plugin to see this. Simply compare the behavior and UI of the toolbars when Top Toolbar is checked. There is now a secondary toolbar.

## Expected behaviour
I'd expect these format controls, when the Top Toolbar toggle is flagged, to be a part of the top toolbar, not a secondary one.

## Actual behaviour
They exist on a new secondary toolbar.

## Screenshots or screen recording (optional)
https://vimeo.com/577847427/147e5f6633

## WordPress information
- WordPress version: WP 5.8
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

I understand that a _lot_ of work went into normalizing the block controls toolbar (https://github.com/WordPress/gutenberg/pull/29247). I think that work is *amazing*, but tend to agree with my publishing partners that this part of the UI is a regression. Even if a new SlotFill were made available to be a part of the top toolbar, that would be more than sufficient to get us back to where we were for the UI in WP 5.7. Thanks!

**Comment by talldan** [comment] 2021-07-22 03:37
@JustinSainton Thanks for reaching out. This change is intentional. The reason is that a lot of block toolbars were found to be overlapping other UI in top toolbar mode, particularly in the site/template editors where there's extra functionality in the top part of the screen, like the template options shown in this screenshot:
<img width="1442" alt="Screenshot 2021-07-22 at 11 31 24 am" src="https://user-images.githubusercontent.com/677833/126586598-a1a6bfe5-846c-4f0e-95cd-50930a7ad4ae.png">

Interested to hear why you think it's a regression—is it just that it takes up more horizontal space now?

I've personally found that it makes the separation between block specific tools and editor tools clearer (I always found having so many icons on one row made finding the right option a little slower) but granted that's open to interpretation.

I'll leave the issue open for further comment to see where the discussion goes.

**Comment by JustinSainton** [comment] 2021-07-22 04:48
@talldan Interesting perspective, for sure! I think the template editing point is a valid one, I hadn't considered that. 

Most of these folks are _probably_ a year or more away from anything related to FSE or template editing in Gutenberg - so the concern from a publishing perspective is the change/shift in UI and it not being expected.

**Comment by Mamaduka** [comment] 2023-09-14 20:25
I believe this was resolved by #49634, and toolbar updates shipped in WP 6.3.

## Screenshot

<img width="632" alt="Screenshot 2023-01-04 at 11 35 42" src="https://user-images.githubusercontent.com/846565/210546838-3ea8ba01-6391-4024-8421-cc8e9fd3cd03.png">

**Closed as completed** 2023-09-14 20:26 UTC
Labels: [Feature] Blocks, General Interface, [Type] Feedback
