### ISSUE TITLE
Don't close the "add link" box right away after making a change

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/gutenberg#32835] opened 2021-06-20 13:56 UTC
When I'm writing articles for my blog, I love to add links to older articles and to Wikipedia pages and such. 
I find it a tad bit annoying that when I add a link or change the "open in a new tab" feature that the box directly closes. 

It makes me have to do two more clicks. 

I would love to be able to AND select the link to the article I want to and change the "open in new tab" slider without having to reselect the link.

**Comment by talldan** [comment] 2021-06-22 04:17
I'm going to tentatively say this is a bug, though not sure if it might be by design.

**Comment by talldan** [comment] 2021-07-21 08:47
Just noticed #25946, so closing this as a duplicate.

**Closed as completed by talldan** 2021-07-21 08:47 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Link Editing
