### ISSUE TITLE
Navigation block: overlay issues with sub navigation

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21520] opened 2020-04-09 20:06 UTC
Using Twenty Nineteen and the latest build it seems the z-index issues that I know I've seen on sub-navigation have come back with vengeance. 

![2020-04-09 21 03 31](https://user-images.githubusercontent.com/253067/78936144-e9dd2c00-7aa5-11ea-8757-25cc8e137284.gif)

This was using Chrome. I don't think we have a current issue for this, however, if we do let's merge this one to that.

**Comment by talldan** [comment] 2020-04-28 04:16
Duplicate of https://github.com/WordPress/gutenberg/issues/21449

**Closed by talldan** 2020-04-28 04:16 UTC
Labels: Needs Dev, [Block] Navigation, [Type] Bug
