### ISSUE TITLE
Tags drop down selection list usability issues 

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#5951] opened 2018-04-03 12:24 UTC
## Issue Overview
When attempting to select an existing Tag from the list provided for a partial search, attempting to use the mouse to click on the scroll bar on the list box results in an unexpected selection of the 'wrong' item.
 
Using the keyboard down arrow gives me access to the list but then I have no option to not select an item other than to delete the characters in the search one by one. 

Clicking away from the field can cause a new (unwanted) tag to be created and stored in the database. 

After recording the problems in the attached .gif, I noticed that I was also getting lots of messages in the console.  Pairs of `500 (Internal Server Error)` and `Uncaught (in promise)` messages.

## Steps to Reproduce (for bugs)

1. Create a series of more than 4 tags that start the same. e.g. WordPress 4.1 to 4.9
2. Edit any post
3. In the tags field type `Word`
4. Attempt to click on the scroll bar down arrow to scroll down the list
5. Notice that an item is selected.

6. Delete the unwanted item and try again.
7. This time use cursor down to switch focus to the list.
8. Now try different ways of 'escaping'
9.  Click on a completely different window to find the search term used
10. Wait a while then go to the Tags admin page  ( wp-admin/edit-tags.php?taxonomy=post_tag&orderby=count&order=asc ) to see your unwanted terms in the tags list.

## Expected Behavior
- Ability to use the mouse to select an item from the list.
- Ability to escape from the list without selecting the wrong item or accidentally creating a new term.
- No messages in the console log.

## Current Behavior
See Steps to reproduce. 

## Possible Solution
I did not investigate the cause of the problems further, but there are multiple issues to be resolved. 

For the usability aspects I suggest having a look at how it works in the Classic editor. 
The drop down list is accessible by keyboard and mouse and the term is not created until I choose Add.

## Screenshots / Video
![issue-tag-select-list-problems](https://user-images.githubusercontent.com/2474435/38247923-b72d40d0-373e-11e8-8d5f-8e87fa95022f.gif)

![image](https://user-images.githubusercontent.com/2474435/38248049-0e69fb4a-373f-11e8-938f-f1faa361c384.png)

## Related Issues and/or PRs

The animated gif also displays an example of a problem that I expect to be fixed by 
https://github.com/WordPress/gutenberg/pull/5913

The post contained two tags - one of which is included in the first 100 returned, the other not. The tags which is not included in the first list is displayed as a blank entry. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by designsimply** [comment] 2018-10-16 17:56
<blockquote>Expected Behavior
Ability to use the mouse to select an item from the list.
Ability to escape from the list without selecting the wrong item or accidentally creating a new term.
No messages in the console log.</blockquote>

I have just tested with WordPress 4.9.8 and Gutenberg [4.0.0-rc.1](https://make.wordpress.org/test/2018/10/10/call-for-testing-gutenberg-4-0-pre-release/) using Firefox 62.0.3 on macOS 10.13.6 and I found that I can use the mouse to select tags and also pressing Escape or clicking to another completely separate window doesn't cause unwanted tags to be added to the list.

I am going to close this issue because it quite a few changes have been made since it was originally filed and because I was unable to see the problem happen after following the testing steps. If the problem is still happening for you, please reply here and include browser details and confirm which version of Gutenberg you are using now and we can re-open this issue if needed. Thank you for testing Gutenberg at this stage and for your bug report!

**Closed by designsimply** 2018-10-16 17:56 UTC
Labels: Needs Testing, [Component] Post Settings, [Type] Bug
