### ISSUE TITLE
Revisions accordion is different than other settings accordions.

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#2724] opened 2017-09-13 18:30 UTC
The settings sidebar has a Revisions item:

<img width="271" alt="screen shot 2017-09-13 at 11 25 25 am" src="https://user-images.githubusercontent.com/191598/30393862-4103a280-9876-11e7-8b90-5df227335ea9.png">

If you look closely you'll notice that the "Revisions" label is a slightly lighter colors than the rest of the sidebar labels. It also is the only one with an icon on the left, which isn't terrible, but does make it stand out from the rest — likely more than it deserves too...

Also, if you move your cursor over the Revisions item, you'll notice that only the label itself is clickable — the rest of the space around the label doesn't respond to clicks. To help explain, you can click on the green area, but not the red:

<img width="539" alt="screen shot 2017-09-13 at 11 28 24 am" src="https://user-images.githubusercontent.com/191598/30394070-dd077dc8-9876-11e7-8762-595685a1f1b2.png">

**Comment by mtias** [comment] 2017-11-20 12:58
Duplicate of #2297.

**Closed by mtias** 2017-11-20 12:58 UTC
Labels: Needs Design Feedback
