### ISSUE TITLE
Gutenberg crashes during opening

### ISSUE THREAD

**Issue by ppmakusu** [WordPress/gutenberg#13127] opened 2018-12-28 10:59 UTC
**Describe the bug**
When I click on New post, Gutenberg crashes with 2 errors : 

`block.js?3527:541 Uncaught TypeError: withAPIData is not a function
    at eval (block.js?3527:541)
    at Object.<anonymous> (block.js?ver=3.4.10:331)
    at __webpack_require__ (block.js?ver=3.4.10:20)
    at block.js?ver=3.4.10:63
    at block.js?ver=3.4.10:66 `

And 

`react-dom.min.js?ver=16.6.3:104 TypeError: Cannot read property 'show_ui' of undefined
    at editor.min.js?ver=9.0.6:55
    at i (lodash.min.js?ver=4.17.11:6)
    at An.filter (lodash.min.js?ver=4.17.11:99)
    at editor.min.js?ver=9.0.6:55
    at ph (react-dom.min.js?ver=16.6.3:97)
    at eg (react-dom.min.js?ver=16.6.3:125)
    at fg (react-dom.min.js?ver=16.6.3:126)
    at wc (react-dom.min.js?ver=16.6.3:138)
    at fa (react-dom.min.js?ver=16.6.3:137)
    at gg (react-dom.min.js?ver=16.6.3:135)`

I think the second error appears thanks to the first one.

**To Reproduce**
1. Go to 'Post'
2. Click on 'New Post'
3. See error

**Screenshots**
<img width="1178" alt="capture d ecran 2018-12-28 a 11 56 32" src="https://user-images.githubusercontent.com/15727121/50513381-bc7a9380-0a97-11e9-94ff-99d1abd3dcbd.png">

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
-  I use the last version of gutemberg on wordpress 5.0.2

**Comment by swissspidy** [comment] 2018-12-28 11:41
`withAPIData` has been removed from Gutenberg many months ago. It looks like one of your plugins ist still using it, hence the error.

Please try disabling all plugins to see if it works again. If so, try activating plugins again one by one to find the culprit.

**Comment by ppmakusu** [comment] 2018-12-28 12:47
thank you swissspidy , now I only have the second error : TypeError: Cannot read property 'show_ui' of undefined. It's appear even if I disabling all plugins. I saw other topics about this error, but it doesn't help.

**Comment by youknowriad** [comment] 2018-12-28 12:52
Looks like a duplicate of #11820 Check there for more information

**Closed by youknowriad** 2018-12-28 12:52 UTC
Labels: [Type] Help Request, [Type] Plugin / Theme Interoperability

**Comment by ppmakusu** [comment] 2018-12-28 12:56
> Looks like a duplicate of #11463 Check there for more information

Hum, I d'ont think so, 11463 its about autosave restoring ?

**Comment by youknowriad** [comment] 2018-12-28 12:58
Actually I shared the wrong issue initially and I edited the message (click the link again sorry)

**Comment by ppmakusu** [comment] 2018-12-28 13:18
Thank you, It's working now thanks to you 👍
