### ISSUE TITLE
Site Editor: template switching loading animations

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#28679] opened 2021-02-02 23:11 UTC
In some previous FSE PRs it was pointed out that that switching templates through Browsing sidebar looks a bit rough now. 

We could either:

- provide a transition animation that makes it more clear when the template has been change,
- show a snackbar notification informing the user that the new template has been loaded.

cc @jameskoster

**Comment by jameskoster** [comment] 2021-02-03 12:06
Here is the roughness I see:

https://user-images.githubusercontent.com/846565/106743967-f8896680-6616-11eb-8902-027669ea9195.mp4

To be honest I don't think it is too bad. It's hard to tell since it loads so fast, but the main issue seems to be a rogue full-width inserter button that flashes in and out for a split second. If we can remove that then we're probably good for now.

FWIW I tried this with a "Slow 3G" network simulation and the performance was virtually identical:


https://user-images.githubusercontent.com/846565/106744744-11dee280-6618-11eb-8df1-501a01b51924.mp4

So an elaborate loading state seems unnecessary.

**Comment by hedgefield** [comment] 2021-03-17 13:54
It's hard to fully benchmark how bad this could get for someone on a really dodgy connection with a theme that has a really elaborate template, so I'd support at least some kind of basic transition state. Something like the pulsing wireframe that facebook and many other apps show while waiting for the content paint to finish. I believe we already have an animating WordPress/Gutenberg logo for when the preview is loading, right? Could we insert that here? Even just a white overlay would probably be fine, just a brief fade out and in to ease the transition of things potentially jumping around.

**Comment by jordesign** [comment] 2023-09-08 03:21
The interface and mechanism for switching templates in the Site Editor are now quite difference, and in my testing the experience seems smooth.

I'll close this issue as no longer reproducible, but if there _are_ perceived issues in the switching in the new interface, a new issue can be opened with updated examples and screencasts.

**Closed by jordesign** 2023-09-08 03:21 UTC
Labels: Needs Design, [Feature] Site Editor
