### ISSUE TITLE
Gutenberg Block not working correctly with iframe srcdoc attribute

### ISSUE THREAD

**Issue by Dev-Ditrict-Web** [WordPress/gutenberg#46924] opened 2023-01-05 20:02 UTC
### Description

In gutenberg, when i am using a custom html block and i add the `srcdoc="<p>hello</p>"` attribute the output break for `srcdoc="<p>hello</p>“ `( the second " become “ ) and iframe not correctly closing

### Step-by-step reproduction instructions

- edit page or post
- add custom html block
- put the below code in the block 
`<iframe srcdoc="<p>hello</p>" ></iframe>`
-check source code on front-end if iframe output correctly

### Screenshots, screen recording, code snippet

<img width="960" alt="Capture d’écran, le 2023-01-05 à 13 56 21" src="https://user-images.githubusercontent.com/65787883/210868177-3a32425c-4c63-4f33-8d9e-9d02ad5bf4a9.png">

### Environment info

wordpress version 6.1.1
default theme: Twenty Twenty-Two
No plugin

chrome/firefox
Desktop mac os

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-01-12 21:49
I have been able to confirm this issue.

**Comment by t-hamano** [comment] 2023-01-16 04:32
I believe this is not a bug, but a standard WordPress core specification. And this is not limited to `iframe` elements.

The WordPress core [hooks content by default with the `wptexturize` function.](https://github.com/WordPress/wordpress-develop/blob/78f6ac9c29eedd528d5748ee99613b715ac94e9c/src/wp-includes/default-filters.php#L185)

This function will convert HTML as follows:

```html
<!-- from -->
<iframe srcdoc="<p>hello</p>"></iframe>

<!-- to -->
<iframe srcdoc="<p>hello</p>&#8220;></iframe>
```

If you wish to disable this, you may do so with the following hook.

```php
add_filter( 'no_texturize_tags', function( $default_no_texturize_tags ) {
	$default_no_texturize_tags[] = 'iframe';
	return $default_no_texturize_tags;
} );
```

However, you might need to be careful when using this filter, since it also allows the following code:

```html
<iframe srcdoc="<script>alert( 'Injection!' )</script>"></iframe>
```

**Comment by t-hamano** [comment] 2023-01-18 11:22
@Dev-Ditrict-Web 

I would like to close this issue as I believe this is not a bug but expected behavior. If there is anything I have missed, please feel free to comment.

**Closed as completed by t-hamano** 2023-01-18 11:22 UTC
Labels: [Block] HTML
