### ISSUE TITLE
Admin pull down action area is messed up

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#9751] opened 2018-09-10 14:46 UTC
**Describe the bug**
With Gutenberg editor activated when I go to create a post, the admin pulldown action area UI messes up. Screenshot attached.

**Expected behavior**
Should stay consistent

**Screenshots**
Attached
![screenshot from 2018-09-10 20_11_54](https://user-images.githubusercontent.com/11072678/45304754-601a5500-b536-11e8-85c1-5bce31f86474.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04 Trusty Thar
 - Browser Chrome 
 - Version 69.0.3497.81 (Official Build) (64-bit)

**Additional context**
- Gutenberg version: 3.7.0

**Comment by youknowriad** [comment] 2018-09-10 14:48
It works properly for me

<img width="381" alt="screen shot 2018-09-10 at 15 47 38" src="https://user-images.githubusercontent.com/272444/45304853-eae85900-b510-11e8-803d-5d206bea9d77.png">

I'm on MacOS though, I don't know if it impacts it.

It could be another plugin as well?

**Comment by emfluenceindia** [comment] 2018-09-10 14:51
When I hover over the action link the UI resets and looks right. But by default when I load the edit page it is messing up.

**Comment by youknowriad** [comment] 2018-11-26 10:46
I can't reproduce this issue and we didn't see any other similar reports. I'm closing as WFM but if we find reproducible steps, we can reopen. Thanks for the report.

**Closed by youknowriad** 2018-11-26 10:46 UTC
Labels: [Status] Needs More Info
