### ISSUE TITLE
"Ghosting" of Header placeholder content on block exit

### ISSUE THREAD

**Issue by kwhite** [WordPress/gutenberg#3784] opened 2017-12-03 20:08 UTC
## Issue Overview

When adding header blocks using the keyboard only, the placeholder text reappears after the header loses focus.

## Steps to Reproduce (for bugs)

1. Add a header block 
2. Enter header text
3. Press 'Esc'

Chrome Mac Version 62.0.3202.94

## Expected Behavior

When I escape or tab out of a heading block, I should see my entered text only.

## Current Behavior

When the heading loses focus, the placeholder text reappears offset behind my heading content.

## Possible Solution

Pretty sure it is focus related, but nothing beyond that. If I find a fix I'll comment on the issue.

## Screenshots / Video

https://www.dropbox.com/s/fzso4osuoisxz35/gutenberg-ghost-header-2017-12-03.mov?dl=0

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by hideokamoto** [comment] 2017-12-03 22:25
probably depends on the `isPlaceholderVisible` variable.
https://github.com/WordPress/gutenberg/blob/master/blocks/editable/index.js#L821

It controls the placeholder, so if it get invalid value, it will be happened.

**Comment by afercia** [comment] 2017-12-13 13:57
@kwhite thanks! I can't reproduce this on master any longer. Maybe it has been fixed in the meantime, can you still reproduce it?

**Comment by laras126** [comment] 2018-01-03 16:38
@afercia Not sure the status of this issue now, but I came across the same problem outside of keyboard-only use: http://recordit.co/YMloPfvGad

My steps where:
1. Create new post
2. Add Paragraph block
3. Add new Heading block *above* the Paragraph block 
4. Type or paste text into Heading block
5. Click on another block to exit the Heading block

This seems to happen whenever you add a Heading block above another block and click out of the Heading block in order to exit it. Rather than container changing to the non-editing state, the container stays the same height and shows the placeholder as it does during an editing state.

**Comment by afercia** [comment] 2018-01-03 17:08
@laras126 are you testing the plugin or the version from the GitHub repository? Can't reproduce following your steps. However, I'm still noticing same "reappearing" of the placeholder in other edge cases but I can't reproduce it consistently.

**Comment by laras126** [comment] 2018-01-04 16:08
@afercia I was using the plugin version. I updated my GitHub version and I can't seem to replicate it now either, but I'll keep an eye out for other occurrences.

**Comment by mtias** [comment] 2018-01-04 16:52
Closing as duplicate of #2865.

**Closed by mtias** 2018-01-04 16:52 UTC
Labels: [Status] Needs More Info
