### ISSUE TITLE
[Block] Comment Template color adjustment -> Overrides inner child color adjustments

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40255] opened 2022-04-12 07:51 UTC
### Description

Examples
Comments > Comment Template > Columns > Column > Row > Comment Date and Comment Author. Change the link color of each.

Comment Template. Change the Link color and notice that it also affects the inner blocks where the color has already been adjusted.

### Step-by-step reproduction instructions

1. Add the Comments Query Loop block.
2. In Comments > Comment Template > Columns > Column > Row > Comment Date change the link color.
3. In Comments > Comment Template > Columns > Column > Comment Author Name change the link color.
4. Go to Comments. Change the link color and notice it changes all the links also the Comment Date and Comment Author Name even though these are defined in their own blocks.

### Screenshots, screen recording, code snippet

Changing the Comment Date link color.
![Screenshot 2022-07-26 at 08 37 54](https://user-images.githubusercontent.com/5323259/180940069-15ae44f2-8955-46b8-9a94-37fe43154649.jpg)

Changing the parent Comment link color also affects inner child blocks.
![Screenshot 2022-07-26 at 08 38 12](https://user-images.githubusercontent.com/5323259/180940164-ba3810c9-aa74-48b6-bc8d-470c73fbb750.jpg)

### Environment info

WP 6.0.1
Gutenberg plugin 13.7.2
Twenty Twenty Two
Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-04-25 10:51
The edit link and comment reply link are always links and their color is changed by the link color option, not the text color option.

I do see a related issue:

Editor
When I change the link color of the comments query loop, the color of the edit link and the reply link inherit this color, even if they already specify their own link color in their own block setting.

Front
The edit and reply link uses the correct, individually assigned colors.

**Comment by paaljoachim** [comment] 2022-07-26 06:42
I have gone ahead and edited the issue title and the issue content to reflect that changing color of the parent block Comments will also change inner blocks that have already defined inner colors.

**Comment by paaljoachim** [comment] 2022-07-26 06:44
Hey @michalczaplinski 
This might be an issue for you to take a closer look at.

**Comment by michalczaplinski** [comment] 2022-07-26 23:07
After taking a quick look I can indeed confirm the issue @paaljoachim 

If you'd like to send a PR with a fix that would be awesome. I would be very happy to help 🙂 

As mentioned by @carolinan, the issue is only present in the editor:

https://user-images.githubusercontent.com/5417266/181128004-97f7bf82-40a0-46b1-97cb-28f7c1076243.mp4

**Comment by paaljoachim** [comment] 2022-07-27 05:39
Thanks for going through @michalczaplinski 

I am wondering if the fix would be a general fix for all parent blocks that affects the inner blocks that have already been modified and should not be overwritten by changes the parent block makes.

Hopefully a developer will show up that can fix the issue. 
I will also ping Carlos @c4rl0sbr4v0

**Comment by michalczaplinski** [comment] 2022-07-28 22:22
I dig a little more here and the same issue appears in the Query Loop block. There are 2 twists though:

1. The correct styles are applied after reloading the editor page:

https://user-images.githubusercontent.com/5417266/181646582-38b7d846-89d9-424c-af0d-32127ff183a3.mp4

2. The editor is sensitive to the **temporal order** in which the styles are applied. 
  - If we first change the styles of the _child_ (e.g. Comment Date block) and then the styles of the _parent_ (e.g. Comment block) the parent styles win, which is **incorrect**.
  - If we first change the styles of the _parent_ and then the styles of the child, the styles are applied correctly.

https://user-images.githubusercontent.com/5417266/181646597-2ce6929c-751e-4066-97c1-c87ca8889992.mp4

**Comment by michalczaplinski** [comment] 2022-07-28 22:50
Hi @oandregal 👋 I have a question

In [this comment](https://github.com/WordPress/gutenberg/issues/37582#issuecomment-1000287580) you mention that:

> Applying the link color is not deterministic in the editor. If I apply the link color to the paragraph and then to the group, the link color is the one set by the group. If I do it the other way around, the link color is the one set by the paragraph.

This is precisely the problem that we see in the current issue. Do you know if this behaviour is intentional or can be considered a bug?

**Comment by paaljoachim** [comment] 2022-07-28 22:52
Heya Nik @ntsekouras I believe this is an issue you might want to know about as well.

**Comment by ntsekouras** [comment] 2022-07-29 08:54
👋 - It's not specific to Query Loop or Comments Loop. It's related to `color` support in general. You can reproduce with just a `Group` block.  Actually the main issue is the one @michalczaplinski linked: https://github.com/WordPress/gutenberg/issues/37582 and probably other `supports` have this..

I think this can be closed as duplicate. What do you think?

**Comment by paaljoachim** [comment] 2022-07-29 11:05
Yeah. It looks like this is a duplicate issue and can be closed. I will let Michael decide.

**Comment by michalczaplinski** [comment] 2022-07-29 18:18
Indeed, let's close this one in favour of #37582 🙂

**Closed as completed by michalczaplinski** 2022-07-29 18:18 UTC
Labels: [Type] Bug, Good First Issue, Needs Dev, [Block] Columns, [Block] Comment Template
