### ISSUE TITLE
Gallery Block - Selecting images

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#1969] opened 2017-07-20 23:40 UTC
Is it by purpose ?

Selecting images for gallery does not work as before in WP. Now clicking new image deselect previous image. You have to use Ctrl + mouse click.
If it is by purpose maybe you should think to leave it as before. Dont bring complexity and need to explain to Editors what is not needed to explain.

Think it is just a bug, or oversight, lack of time to fix everything. Because when editing existing gallery under "Add to gallery" selecting works as before in WP.

**Comment by westonruter** [comment] 2017-07-21 05:55
Duplicate of #1401.

See pending fix in #1820.

**Closed by westonruter** 2017-07-21 05:55 UTC
