### ISSUE TITLE
Cursor is jumping to the start of the block when autosaving

### ISSUE THREAD

**Issue by Luxamman** [WordPress/gutenberg#12942] opened 2018-12-17 09:07 UTC
**Describe the bug**
It is a very annoying behavior that when writing, the cursor is jumping to the start of the block your in every time Gutenberg is auto saving. This is destroying the workflow of writing and publishing, because after the auto save you have to reposition the cursor again and again at the last point in order to be able to continue writing, or always type something so that it is not saved automatically.

I'm surprised that the bug has not been reported yet, otherwise I did not find it. After all for someone who is writing a lot, this is something like a no-go situation and to be more effective, I need to write outside Gutenberg - which should not be the way.

**To Reproduce**
Open Gutenberg, start writing a textblock and wait until it is saving. 

**Expected behavior**
Just let the cursor stay where it is inside the actual text. Maybe something to to with reloading the block?

**Screenshots**
![autosavebug](https://user-images.githubusercontent.com/20417555/50076722-bc9aa980-01e2-11e9-9314-0dc276754546.gif)

**Desktop (please complete the following information):**
Win10, Chrome 70/71, also Elementor Pro, Yoast, Pods and with theme Astra Pro. WordPress 5.0.1 - everything up to date at this point.

**Comment by designsimply** [comment] 2018-12-17 18:14
I tested and was unable to see the problem happen without the extra plugins you mentioned. In my testing, I used WordPress 5.0.1 and Gutenberg 4.7.0 using Firefox 63.0.3 and Chrome 70.0.3538.110 on macOS 10.13.6. I also tested WordPress 5.0.1 without the Gutenberg plugin active. ([1m8s](https://cloudup.com/cPABleu7aAi))

It may be worth also checking Windows. If the bug cannot be reproduced there, then the next step will be to ask if it's possible for you to temporarily deactivate some of the plugins you mentioned to see if you can determine which of those may be causing the problem.

**Comment by designsimply** [comment] 2018-12-17 18:15
Leaving `Needs Testing` to loop back around or get another person to help test from Windows.

**Comment by Luxamman** [comment] 2018-12-18 08:55
After testing on WIN/MAC/Linux, I was deactivating plugins on a testserver with the same problem and  now it seems, I found the plugin making problems: 

"Pods - Custom Content Types and Fields" 2.7.11 from Pods Framework Team

I have some Pods in use and every time I deactivate the plugin, the cursor stays where it is. 

Can anyone try and confirm that? 

Thanks!

**Comment by SmartlinkR** [comment] 2018-12-28 03:10
> Can anyone try and confirm that?

I am having the same problem, but I do NOT have the plugin in question...  "Pods - Custom Content Types and Fields"

I am on Wordpress 5.0.2 and I do not have the Gutenberg plugin...

**Comment by colinmcdermott** [comment] 2018-12-29 08:38
Same issue. Can confirm am NOT running the Pods plugin.

**Comment by talldan** [comment] 2019-01-07 06:32
Hi @SmartlinkR and @colinmcdermott - Would be great if you could both share which OS/Browser combination you're using when you see the issue?

**Comment by colinmcdermott** [comment] 2019-01-07 10:42
Hi @talldan - sure, Chrome + Windows 10.

Confirmed latest version of Chrome - Version 71.0.3578.98 (Official Build) (64-bit)

Cheers!

**Comment by pfvks** [comment] 2019-01-08 04:46
Having the same issue on Safari.

**Comment by colinmcdermott** [comment] 2019-01-08 10:50
Just tested, same issue in Firefox: autosave = return to start of line.

**Comment by StudentDawid** [comment] 2019-01-08 18:11
Same issue

**Comment by patrizz** [comment] 2019-01-12 11:56
Same in chrome on Mac. WordPress 5.0.3 running Twenty Seventeen theme.

**Comment by colinmcdermott** [comment] 2019-01-13 02:00
Went through the standard process of turning off all plugins enabling them one at time.

Plugin causing the issue for me was CMB2 https://wordpress.org/plugins/cmb2/ - which is required for my theme unfortunately :/

**Comment by dleigh** [comment] 2019-01-18 15:58
It was Pods for me too.  Thanks for the research @Luxamman !

**Comment by jimtrue** [comment] 2019-01-18 22:10
Are you running 2.7.11 or 2.7.12 of Pods? It would also help in these to at least mention the developer of the plugin in question so we can be alerted to the issue. This is the first we heard about them.

**Comment by designsimply** [comment] 2019-01-18 22:41
@jimtrue thanks for asking for a mention! I hadn't yet circled back to this issue but normally when we find a plugin or theme conflict, we try to work with people to help them get the best information possible to help them make a good bug report and then help them find a good place to post that for the plugin author. Often I will recommend posting in the plugin forum on WordPress.org. Is https://wordpress.org/support/plugin/pods a good place or is there a better spot?

**Comment by pglewis** [comment] 2019-01-18 22:56
Now that I'm aware of it I'll track an issue for it from the Pods side.  Those experiencing this issue with Pods can test the following PR and see if that clears things up: https://github.com/pods-framework/pods/issues/5274

**Comment by aduth** [comment] 2019-01-18 23:20
Based on pods-framework/pods#5275 and looking at [nearly identical code from CMB2](https://github.com/CMB2/CMB2/blob/c1fd51482184e7e01eda6ec7f07354684020db66/js/cmb2.js#L124-L135), the problem seems to stem from calling `save` on an instance of TinyMCE.

```
for ( var i = 0; i < tinyMCE.editors.length; i++ ) tinyMCE.editors[i].save()
```

If I understand correctly, the intent of this is the same as what was fixed in Gutenberg with #12568, which shipped with `@wordpress/edit-post@3.1.5` / Gutenberg 4.7 / WordPress 5.0.2 .

It does seem though that `window.tinyMCE.triggerSave();` introduced with #12568 suffers from the same issue with wrongful caret placement, but the code is only reached at very specific increments, corresponding to the following logic / comment:

https://github.com/WordPress/gutenberg/blob/837fda74400f6af9810a4ef0b3bb33d22eb0105a/packages/edit-post/src/store/effects.js#L56-L62

It's still not entirely clear to me why the caret position moves, and I've been unable to reproduce as being an issue in a [minimal TinyMCE test case](http://fiddle.tinymce.com/aAgaab/1). This is worth investigating further.

**Comment by jimtrue** [comment] 2019-01-19 17:20
> Often I will recommend posting in the plugin forum on WordPress.org. Is [wordpress.org/support/plugin/pods](https://wordpress.org/support/plugin/pods) a good place or is there a better spot?

@designsimply Yep, our forums are fine. I found out about it because it got mentioned on another WordPress.org forum and I have a 'pods' mention notification to alert me to those. Kinda hard to do that with the GitHub. We have our own GitHub as well, but I'd say once it's noticed, get it in front of the plugin developers, either in their WordPress.org forum or their GitHub if it's published and public (ours is). 

This issue has been around since 12/18 but within hours of us getting mentioned on it in WordPress.org, we had escalated to our developers and @pglewis got a PR out there. Had we been escalated to immediately, this fix would've been in December ;)

**Comment by colinmcdermott** [comment] 2019-01-21 13:20
This is now resolved in CMB2 with the latest update.

https://github.com/CMB2/CMB2/issues/1202
https://wordpress.org/support/topic/gutenburg-cursor-returns-to-start-on-autosave/#post-11112862

**Comment by aduth** [comment] 2019-01-21 13:33
I've found that this can also be reproduced in Gutenberg itself with any plugin which adds a meta box to the editor screen, specifically when the user saves the post by pressing Ctrl+S . Doing so while within a RichText (paragraph) field will reset the caret position to the start of the field.

([Example file to place in `wp-content/plugins` to demonstrate the issue](https://gist.github.com/aduth/cc858440e8d49e624fd75d318e7eca67))

**Comment by aduth** [comment] 2019-03-01 13:41
I feel fairly confident that the issue with caret moving unexpectedly in paragraph blocks will have been totally resolved with recent refactoring to the RichText component, specifically in #13697 (cc @iseulde).

There may still be a lingering issue for meta boxes which include their own TinyMCE editors, like the example provided in https://github.com/WordPress/gutenberg/issues/7176#issuecomment-412134455 (related: #12568). It should be tested to see whether the caret moves unexpected after saving the post in this scenario, though it may be difficult to test using the instructions at https://github.com/WordPress/gutenberg/issues/12942#issuecomment-456075573 if TinyMCE implements its own explicit handling for Ctrl+S.

**Comment by youknowriad** [comment] 2019-10-29 17:08
We haven't seen any recent reports of this. So i'm going to close this, if you manage to reproduce it please consider opening a new issue with as many details as you can.

**Closed by youknowriad** 2019-10-29 17:08 UTC
Labels: Needs Testing, [Feature] Meta Boxes, [Feature] Saving, [Type] Bug
