### ISSUE TITLE
Gallery Block: Adding images to gallery removes all existing images

### ISSUE THREAD

**Issue by pattyok** [WordPress/gutenberg#33769] opened 2021-07-29 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

When adding images to an existing gallery block, any existing images disappear. I have verified that this issue was introduced in 5.8. I tested on the same site prior to upgrading from 5.7 and it worked as expected. 

This appears to be an issue with the `<MediaUpload> `component as I found the bug when I was working on my own block using that component.

### Step-by-step reproduction instructions

1. Add a Gallery Block to a page or post
2. Add some images to the gallery
3. Click the Media Library link to add more images to the gallery
4. Select a new image to add to the gallery
5. Click Add to Gallery
6. The edit screen opens with only the new images, the existing images are gone

### Expected Behavior

Would expect that adding to gallery retains the existing images

### Current Behavior

When adding to the gallery the existing images disappear

IF you visit the Edit Gallery screen prior to adding images, it works as expected, though that's not an intuitive workflow..

### Screenshots or screen recording (optional)

![galleryissue](https://user-images.githubusercontent.com/2417080/127574652-123abeab-820c-41b4-b265-e154c65344a3.gif)

### WordPress Information

WP 5.8

### Gutenberg Information

Gutenberg not installed

### What browsers are you seeing the problem on?

Chrome

### Device Information

Desktop

### Operating System Information

MacOS 11.4

**Comment by talldan** [comment] 2021-07-30 04:34
Thanks for reporting. I could reproduce this. There also seems to be a bug with the Gutenberg plugin where the file picker is opened every time I click the Media Library button. 🤔

**Comment by sabernhardt** [comment] 2021-07-30 09:07
Thanks! This was also [reported on Trac 53835](https://core.trac.wordpress.org/ticket/53835).

**Comment by pento** [comment] 2021-08-06 00:45
I've been able to reproduce this issue. I've also found a workaround:

1. Add a Gallery Block to a page or post
1. Add some images to the gallery
1. Click the Media Library link to add more images to the gallery
1. **On the left side of the Media Library modal, click _Edit gallery_**
1. **On the left side of the Media Library modal, click _Add to gallery_**
1. Select a new image to add to the gallery
1. Click Add to Gallery
1. The gallery in the post now correctly contains the old images, and the new image.

**Comment by mpeshev** [comment] 2021-08-13 19:21
Still not sure why it isn't pulling the right attachments from the previous gallery, but I found that the [view](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/media-views.js#L7226) only contains the new entries before rendering the new modal instead of pulling the previous collection too.

It may be related to the [trigger](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/media-views.js#L7266) chaining and the necessity to pull the entries from Edit gallery and appending them as Attachments in the corresponding view.

**Comment by desrosj** [comment] 2021-08-31 14:19
With WordPress 5.8.1 RC due out in less than 24 hours and no proposed fix, I've moved this to the 5.8.2 milestone.

**Comment by glendaviesnz** [comment] 2021-09-14 21:39
> There also seems to be a bug with the Gutenberg plugin where the file picker is opened every time I click the Media Library button. 🤔

The issue of the file picker opening is noted in this issue https://github.com/WordPress/gutenberg/issues/34099 - initially closed thinking it was a duplicate of this one, but probably worth listing as a separate issue in case it is a separate fix to the issue of the existing images being lost

**Comment by andrewserong** [comment] 2021-09-23 07:22
I've come up with a fix in #35070 that should resolve this issue — it's a bit of a workaround due to how the GalleryAdd controller works in the media library, but hopefully it restores the expected behaviour.

**Closed as completed** 2021-09-26 23:27 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Gallery
