### ISSUE TITLE
Change Block Navigation's item values to content instead of type

### ISSUE THREAD

**Issue by rozmy** [WordPress/gutenberg#14309] opened 2019-03-07 12:32 UTC
As a blogger I write long articles. I'd like to navigate quickly between paragraphs, the middle of the document or jump to the end to fix typos or replace images. 
- CTRL+f as jump to a specific word works well
- Otherwise this is really hard (lack of scrollbar, or a simple TOC)

I found Block Navigation, which could solve this issue but in it's current state it only indicates the Block's type. 

How about changing the items to indicate block **type** by it's icon, and show a preview of it's **content**.

![image](https://user-images.githubusercontent.com/7920792/53956100-fb9e1400-40da-11e9-8ae6-cd375d626d4e.png)

**Comment by youknowriad** [comment] 2019-03-07 12:34
Seems like a duplicate of #11010

**Closed by youknowriad** 2019-03-07 12:34 UTC
