### ISSUE TITLE
Drag and drop content within blocks

### ISSUE THREAD

**Issue by sarahfg** [WordPress/gutenberg#13881] opened 2019-02-14 17:21 UTC
**Issue**
When writing text in a paragraph it would be wonderful to be able to highlight a sentence and drag it to another part of my paragraph. Currently I can highlight text, but if I hold on my cursor and try to move it it wont go. To rearrange content I have to cut and paste by keyboard shortcuts or through the menu on my mouse.

![trying to move text](https://cld.wthms.co/nom0jD+)

(Image link: https://cld.wthms.co/nom0jD )

**Solution**
When text is highlighted in a paragraph it can be dragged to another part of that same paragraph or a different paragraph block, much the same as how I can in a text editor on my computer.

![moving text](https://cld.wthms.co/MOCqhf+)

(Image link: https://cld.wthms.co/MOCqhf )

**Comment by sarahfg** [comment] 2019-02-14 17:22
Request came from a WordPress.com user in 1802915-zen

**Comment by iseulde** [comment] 2019-02-18 13:11
Duplicate of #3339.

**Closed by iseulde** 2019-02-18 13:11 UTC
Labels: Drag and Drop, Needs Design Feedback, [Block] Paragraph, [Component] Raw Handling
