### ISSUE TITLE
Choosing image from media library

### ISSUE THREAD

**Issue by shabikaplan** [WordPress/gutenberg#9027] opened 2018-08-15 14:57 UTC
Image blocks do not give me the option to choose from the media library nor do they allow me to switch my image for another one.

1. Go to the gutenberg editor
2. Click on add new image block
3. Attempt to choose image form media library or switch the image

**Comment by youknowriad** [comment] 2018-08-15 15:10
Duplicate of #8838 (Read the comments to understand how to fix the issue). If it's a different problem, let me know.

**Closed by youknowriad** 2018-08-15 15:10 UTC
