### ISSUE TITLE
Create New Templates Not Working from TT2 FSE editor 

### ISSUE THREAD

**Issue by dugyen** [WordPress/gutenberg#39548] opened 2022-03-17 15:30 UTC
### Description

When user try to create new template from TT2 theme editor with active latest Gutenberg, it's not function... the (Add New) button freeze. 

### Step-by-step reproduction instructions

1. Open the site editor
2. Select Template to create new template 
3. Click Add New Button to create new template 
3. Here you could see that it doesn't redirect to create new template. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/21174885/158834417-c885a509-d8cf-48bf-8bdc-133a1c846ad9.mov

### Environment info

- WordPress 6.0 alpha and Gutenberg 12.8 

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Addison-Stavlo** [comment] 2022-03-18 11:52
I can reproduce this as well on `v12.8.0`. It looks like it has since been resolved on the `trunk` branch as I can no longer repro there.

Are we able to get this fix into a point release for 12.8?  cc @priethor (or if you may know who else to ping related to this)

**Comment by Addison-Stavlo** [comment] 2022-03-18 17:41
It looks like the fix for this went live with `v12.8.1` a couple hours ago.

Im closing this issue, but if you still experience on 12.8.1 please feel free to reopen.

**Closed as completed by Addison-Stavlo** 2022-03-18 17:41 UTC
Labels: [Type] Bug, [Priority] High, [Feature] Site Editor

**Comment by dugyen** [comment] 2022-03-18 18:17
thanks for the release and fix @Addison-Stavlo would take a look

**Comment by dugyen** [comment] 2022-03-18 18:22
@Addison-Stavlo thanks it's working

**Comment by priethor** [comment] 2022-03-20 14:31
Thanks for reporting this! As @Addison-Stavlo mentions, it was fixed in trunk and 12.8.1 thanks to #39331
