### ISSUE TITLE
Empty/blank classic editor page

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#12992] opened 2018-12-18 18:24 UTC
**Describe the bug**
When opening the Classic Editor of a page, the page will be empty.

**To Reproduce**
1. Click on 'Classic Editor' of an existing page in backend.
2. Notice that now editor is shown, the page ie smpty/blank.

**Expected behavior**
The classic editor loads and can be used for editing the page.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: Version 70.0.3538.110 (Official Build) 64-bit

**Additional context**
- Gutenberg 4.7.1
- WordPress 5.0.1
- No Classic Editor plugin installed/activated

**Comment by designsimply** [comment] 2018-12-19 21:23
Thank you for reporting this. I am closing this report as a duplicate of #12958.

I've tried a few times to try to replicate this problem but haven't been able to so far, so if there's any additional information you can give at https://github.com/WordPress/gutenberg/issues/12958#issuecomment-448747995 that may help surface the source the problem or if you have any additional ideas for testing, that would be helpful.

**Closed by designsimply** 2018-12-19 21:23 UTC
Labels: [Status] Duplicate
