### ISSUE TITLE
Couldn't the Conversion be Accomplished More Easily?

### ISSUE THREAD

**Issue by VR51** [WordPress/gutenberg#14870] opened 2019-04-08 18:08 UTC
Is there a reason the upgrade from traditional widgets to Gutenberg block editor widgets is not being used to convert traditional widget areas to a Widgets Custom Post Type with an extendible Widget Area taxonomy?

Traditional widgets can be used as shortcodes within posts. There are plugins that accomplish this conversion well. It comes to my mind that it would be practical to deprecate the traditional widget admin screen by converting it into a sort of 'Legacy Widget to Shortcode Converter' tool which turns configured legacy widgets into named Gutenberg shortcode blocks which can then be used within the proposed new Widgets CPT.

Using a CPT for widget areas would provide a lot of play opportunity for those who wish to use taxonomy terms to contextually trigger the display of widget collections; and being a CPT, editor revisions would be available, the REST API would be usable and plugins that hook into CPTs would automatically work with the new Widgets CPT.

Be gentle if I'm wrong but wouldn't this be simpler than the current approach?

**Comment by aduth** [comment] 2019-04-08 18:44
Is this intended to be in direct response to #14812? If so, it would be most appropriate to keep discussion consolidated there.

**Comment by VR51** [comment] 2019-04-08 20:22
@aduth it is, I think. It's not 100% clear to me where responses to the RFC are supposed to be placed. If that issue number is where you feel this idea should be placed then please feel free to move it across.

**Comment by aduth** [comment] 2019-04-08 21:13
Yes, the pull request would be the best place. I can't directly move it across, but I'll copy your comment there.

Thanks for clarifying.

Duplicate of #14812

**Closed by aduth** 2019-04-08 21:13 UTC
Labels: [Status] Needs More Info
