### ISSUE TITLE
Rename Template Parts/Pattern options menu doesn't hide after selecting rename

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#54702] opened 2023-09-21 17:11 UTC
### Description

When you try to rename a template part or pattern, the context menu doesn't auto-hide and can overlap the Rename module.

### Step-by-step reproduction instructions

1. Open Appearance > Editor > Patterns
2. Select a category under Template Parts like Header
3. Create a custom Header Template Part (you can just duplicate the default "Header" using the `...` menu)
4. On a custom Template Part, select `...` > `Rename`

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/4e037767-b7c8-4867-a019-eb88a6199f01

### Environment info

- WP 6.3.1 running Twenty Twenty Three
- Gutenberg 16.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment] 2023-09-21 21:21
Confirmed in my testing as well. I noticed that with GB deactivated the menu still says visible - but the z-index is _lower_ than the modal, so the experience is not _as_ poor.

With GB active
<img width="696" alt="Screenshot 2023-09-22 at 7 18 59 am" src="https://github.com/WordPress/gutenberg/assets/1842363/c746d479-0059-4524-aae9-5d47c5c6d1cf">

With GB deactivated

<img width="808" alt="Screenshot 2023-09-22 at 7 20 05 am" src="https://github.com/WordPress/gutenberg/assets/1842363/e3ced2be-bfc5-4989-92fb-b1adccba4f0d">

**Comment by jordesign** [comment] 2023-09-21 21:23
I could also recreate this for renaming patterns as well - so I've updated the title to reflect that.

**Comment by Mamaduka** [comment] 2023-09-22 07:56
This was fixed in #54277. I can't reproduce the issue on the trunk.

**Closed as completed by Mamaduka** 2023-09-22 07:56 UTC
Labels: [Type] Bug, [Feature] Site Editor
