### ISSUE TITLE
`get_the_ID()` returning 1 for every post in `Query Loop` block

### ISSUE THREAD

**Issue by PH4NTOMiki** [WordPress/gutenberg#49840] opened 2023-04-14 16:07 UTC
### Description

I created custom post type with custom field `youtube_url` and in Query Loop block it's impossible for me to access /show that value to the user, so I tried making custom shortcode and putting the Shortcode block inside Query Loop/Post Template with value `[inject_yt_url]` and then creating that shortcode with following code using Code Snippets plugin

```php
add_shortcode( 'inject_yt_url', 'yt_shortcode' );
function yt_shortcode( $atts ) {
	return get_post_meta(get_the_ID(), 'youtube_url', true);
}
```

but it didn't work so I tried just showing ID using this code:

```php
add_shortcode( 'inject_yt_url', 'yt_shortcode' );
function yt_shortcode( $atts ) {
	return get_the_ID();
}
```
and it always shows `1`

and I also tried this with the same result:

```php
add_shortcode( 'inject_yt_url', 'yt_shortcode' );
function yt_shortcode( $atts ) {
	global $post;
	return $post->ID;
}
```

### Step-by-step reproduction instructions

above

### Environment info

WP 6.2
Nginx

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carlomanf** [comment] 2023-04-14 23:01
Duplicate of #43053

**Closed as not planned** 2023-04-17 03:04 UTC
Labels: Needs Testing, [Status] Duplicate, [Block] Query Loop
