### ISSUE TITLE
Keyboard shortcuts too hard to remember and use

### ISSUE THREAD

**Issue by lcswillems** [WordPress/gutenberg#12489] opened 2018-12-01 00:46 UTC
**Is your feature request related to a problem? Please describe.**
The keyboard shortcuts are too complicated for me, not intuitive for me. Moreover, even after using they during several hours, I still have troubles to remember them... Some keyboard shortcuts use `ctrl+shift`, others use `alt+shift` (the former is more convenient than the later).

**Describe the solution you'd like**
I often use [Jupyter Lab](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab%2Ftree%2Fdemo%2FLorenz.ipynb) and they have a concept of cells, which is similar to the concept of blocks in Gutenberg, and they have a lot of intuitive keyboard shortcut.

For example, `dd` to delete a cell, `a` to insert a cell above, `b` to insert a cell below, `c` to copy a cell, `x` to cut a cell...

The list of shortcuts can be seen here:
![image](https://user-images.githubusercontent.com/5437552/49321893-eda08c00-f50a-11e8-8da8-402299256f9f.png)

**Comment by swissspidy** [comment] 2018-12-01 13:02
There are plans to let users customize keyboard shortcuts. That's the only solution for this that will truly work for everyone.

I'm therefore closing this one as a duplicate of #3218.

**Closed by swissspidy** 2018-12-01 13:02 UTC
Labels: Accessibility, Feedback
