### ISSUE TITLE
Shortcode block need alignment option

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#5880] opened 2018-03-29 10:26 UTC
## Issue Overview
A lot of shortcodes are inserting elements that occupy only a (small) part of the screen width. In classic TinyMCE I can align these elements like any other text (left, middle, right).
I need this possibility in Gutenberg too.

**Comment by karmatosed** [comment] 2018-03-29 11:03
I don't think that's a bad idea, probably a good idea would be to add also in the class option, a shortcode could likely need that.

**Comment by youknowriad** [comment] 2019-01-09 10:19
At the moment, the shortcode block, doesn't have any wrapper, so there's no way to align it. 

In other words, I think this is a duplicate of #4900 as you'd be able to add a shortcode block inside any "section" block and you'd be able to align this section block.

Closing, let's reopen if it doesn't address the use-case properly.

**Closed by youknowriad** 2019-01-09 10:19 UTC
Labels: Blocks, Future, [Type] Enhancement

**Comment by krzysiekdrozdz** [comment] 2020-07-25 06:11
Really, is that the solution? Force users to wrap a block with another block? 

In such case there's no need for alignment option in any block - we can wrap every block with section/group...
