### ISSUE TITLE
Notices displaying behind components-popover, z-index.

### ISSUE THREAD

**Issue by dovy** [WordPress/gutenberg#22075] opened 2020-05-04 12:25 UTC
**Describe the bug**
`.components-notice-list` has a z-index of `29`.
`.components-popover.block-editor-block-list__block-popover` also has a z-index of `29`.

Result, `.components-notice-list` is displayed behind `.components-popover.block-editor-block-list__block-popover`

**To reproduce**
Display any notice and scroll down the page.

**Expected behavior**
Notice should be over top of everything I'd expect.

**Screenshots**
https://cloudup.com/cPimUTiSrTO

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?  gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.0.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 81.0.4044.122

**Comment by ryelle** [comment] 2020-09-11 00:25
This is a duplicate of https://github.com/WordPress/gutenberg/issues/22416, which already has a PR to fix at https://github.com/WordPress/gutenberg/pull/22757, so I'm going to close this one.

**Closed by ryelle** 2020-09-11 00:25 UTC
Labels: Needs Testing
