### ISSUE TITLE
Button is shown, even when no content is added to the button

### ISSUE THREAD

**Issue by leph83** [WordPress/gutenberg#20566] opened 2020-03-01 18:10 UTC
**Describe the bug**
Compared to the heading block the button block is shown, even if it doesn't have content

**To reproduce**
1. Add the Core Button
2. Save without adding a Text to the button or a link

**Expected behavior**
I don't wan't to see the button in the frontend, if I didn't put content in it

**Additional context**
Default Wordpress Installation 5.3.2

**Comment by karmatosed** [comment] 2020-04-27 15:26
Thanks for reporting this @leph83. I think you raise a valid point, my only pause is that you can still add a link so in theory, it can become just a link shape. I still think that this falls into enhancement and could be valid to explore despite that.

**Comment by leph83** [comment] 2020-04-27 15:38
If you're saing that it should be possible to have a button(shape) with a link on it without text, I do agree. 
`<a href="#home"></a>`
But if the button doesn't have a link AND no Text inside of it, I don't see the point of showing the button on the website. 
`<a href=""></a>`

**Comment by karmatosed** [comment] 2020-04-28 13:29
I think that's a valid split in behaviour we can bring in @leph83. Let me move this to needs dev as I feel that's a great split:

- If it has a link display.
- If no link and text, don't display.

**Comment by danielpost** [comment] 2020-04-28 13:34
Wouldn't an empty `<a>` element cause some accessibility issues? See for example here: https://web.dev/link-name/

**Comment by leph83** [comment] 2020-04-28 13:37
So does a link with the content "more" etc. That's up to the content creator to decide to use an "empty" button or not.

**Comment by danielpost** [comment] 2020-04-28 13:44
Well, the key difference here is that an empty link is _always_ wrong, as opposed to a link that might have inaccessible text. I think at the very least it's worth considering if this is a scenario where the Block Editor could encourage proper accessible links.

**Comment by leph83** [comment] 2020-04-28 13:52
My first suggestion was to hide the button, if the button doesn't have a content, regardless of the link. But as @karmatosed said, maybe you want to show the button without a text but with a hyperlink. I can see her point of view. 
And yes, it is important to create accessible content, but there's a limit to that for a developer. And that is the content creator. 
Do you want to implement a warning, if the content is missing completely? 
I would already be happy, if the button is not shown, if it doesn't have a link. Because the situation _now_ is that the button is shown, if it doesn't have a link nor content inside the a tag.

**Comment by skorasaurus** [comment] 2020-04-28 17:32
I understand we cannot stop every opportunity for a user unintentionally trying to create inaccessible button-like links but it's very reasonable to expect text in a URL. 

There may be some very remote cases where a develop would want a link without any text to describe it (a very convoluted example that I thought of if they're using a background-image and then using ARIA on it; but that is not a recommended practice, would be prone to breaking; and would be something that a the developer should be responsible for building on their own with their own custom block. 

I think there's already an open issue that proposes to require content in the link or (link-like) button block, but I cannot find it.

**Comment by leph83** [comment] 2020-04-30 07:27
So what now? My proposal to hide the button if it has not content is not needed, because there is already a proposal for that?

**Comment by mapk** [comment] 2020-05-04 23:45
Related to this Navigation block issue. https://github.com/WordPress/gutenberg/issues/21848

A proposed solution is to hide the elements that don't have content on the front-end.

**Comment by skorasaurus** [comment] 2020-11-23 21:00
duplicate of https://github.com/WordPress/gutenberg/issues/17221 ?

**Comment by Mamaduka** [comment] 2021-03-16 09:10
Potentially fixed via  #29717.

**Comment by skorasaurus** [comment] 2021-03-16 13:27
> Potentially fixed via #29717.

Yes, it is :)

**Closed by skorasaurus** 2021-03-16 13:27 UTC
Labels: Needs Dev, [Block] Buttons, [Type] Enhancement
