### ISSUE TITLE
Patterns: allow users to add a description

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#65724] opened 2024-09-29 12:38 UTC
Add support for "excerpts" and use them on the block description (inspector, previews, etc).

**Comment by talldan** [comment] 2024-09-30 14:08
I think there was already some work done on this by @carolinan, this is a PR I found from a quick search - [[Data Views] User patterns: Use excerpt as description](https://github.com/WordPress/gutenberg/pull/60549#top)

I'm not sure of the status right now, Carolina might be able to provide a summary of whether there's any work remaining.

**Comment by mtias** [comment] 2024-10-01 09:03
Yeah, I think this is a bit low priority but good to log it still.

**Comment by youknowriad** [comment] 2024-11-11 13:15
It is currently possible to assign descriptions to patterns in the UI. So the current issue is partially solved. Are there any remaining places where the description should be used?

**Comment by carolinan** [comment] 2024-11-11 13:43
Anne wrote a suggestion that it should be optional to display the pattern description in the DataViews (Hidden by default).
https://github.com/WordPress/gutenberg/issues/55242#issuecomment-2070876061

But that is related to **showing** the descriptions, not adding or editing them.

**Comment by youknowriad** [comment] 2024-11-11 13:52
Ok, so since the remaining work is about "displaying" these in different places. The current issue becomes just a duplicate of #55242 so I'm closing it.

**Closed as completed by youknowriad** 2024-11-11 13:52 UTC
Labels: [Priority] Low, [Feature] Synced Patterns, [Feature] Patterns
