### ISSUE TITLE
How to create custom embed block

### ISSUE THREAD

**Issue by thamibn** [WordPress/gutenberg#13872] opened 2019-02-14 09:31 UTC
Hi,

can some one please show me how can i create a custom embed block?

user should be able to add url for the video then the video preview should be shown.

**Comment by youknowriad** [comment] 2019-02-14 09:35
That's not easy at the moment, you'd have to duplicate a lot of existing code. Closing as a duplicate of #13490

**Closed by youknowriad** 2019-02-14 09:35 UTC
Labels: [Type] Help Request
