### ISSUE TITLE
Image Block: Allow toggling between figure/div wrapper

### ISSUE THREAD

**Issue by fienen** [WordPress/gutenberg#14550] opened 2019-03-21 13:59 UTC
**Is your feature request related to a problem? Please describe.**
Currently, all image blocks use a child `<figure>` element as a wrapper on images. This is appropriate in many cases, especially if being combined with a caption. But it isn't correct in all cases. Images can be included in content that would not semantically qualify as a "figure."

As the W3C describes:

> The figure element represents some flow content, optionally with a caption, that is self-contained and is typically referenced as a single unit from the main flow of the document.

As a result, it is technically incorrect to mark up something like a decorative image with as a figure, for instance.

**Describe the solution you'd like**
When an image block is created without a caption, offer a block attribute setting to explicitly enable or disable the use of a `<figure>` wrapper on the image, allowing the image to use only the block `<div>` wrapper by itself when desired. If a caption is defined, I believe it would be safe to enforce a figure wrapper.

**Describe alternatives you've considered**
None. Alternative solutions would require modifications to the core block. It could be possible to make a custom block that functions in this way, but I worry users would find multiple image blocks confusing.

**Comment by draganescu** [comment] 2020-04-22 08:34
It might be that `figure` covers so much cases that adding this option would not help that much. I think other blocks can add and subtract from core blocks.

>  I worry users would find multiple image blocks confusing.

Well, as long as we have block plugins and plugins offering blocks, making multiple similar blocks easy to grok is another issue (on how the inserter should work, on how suggestions and discoverability work and so on).

Personally I think these kinds of options (with some exceptions) that control wrapper tag name are not a good fit for the default implementations because it nudges the UI to a brick-a-brack :)

What do you think @fienen ?

**Comment by paaljoachim** [comment] 2021-02-10 10:09
Isabel @tellthemachines can you take a look?

**Comment by tellthemachines** [comment] 2021-02-10 23:50
> As a result, it is technically incorrect to mark up something like a decorative image with as a figure, for instance.

There's nothing in the W3C description to indicate that it's incorrect to use `figure` for a decorative image. The only recommendation for decorative images is to set their `alt` attribute` to an empty string, so that screen readers ignore it. This'll work whether the image is inside a `figure` or a `div`.

**Comment by talldan** [comment] 2021-07-21 04:07
I'm going to close this since the feedback seems to be that `figure` is ok, and there are no further comments against.

**Closed by talldan** 2021-07-21 04:07 UTC
Labels: [Block] Image

**Comment by depwd** [comment] 2022-05-08 15:41
> It might be that `figure` covers so much cases that adding this option would not help that much. I think other blocks can add and subtract from core blocks.

As stated above, the W3c definition of a figure element is:
> "The figure element represents a unit of content, optionally with a caption, that is self-contained, that is typically referenced as a single unit from the main flow of the document, and that can be moved away from the main flow of the document without affecting the document’s meaning." – [W3c.org](http://w3c.github.io/html-reference/figure.html)

Wouldn't the "figure" element cover far fewer use cases based on the definition? I understand that it is appropriate to use an "img" element in place of "figure", but not necessarily visa versa.

> > I worry users would find multiple image blocks confusing.

Multiple image blocks would indeed be confusing. The need for two blocks only arises due to using "figure" in the first place though. Ideally, the image block would use "img", and a second block, the "figure block", could use a "figure" element without confusing. Alternatively, "picture" for images and "figure" for figures.

> There's nothing in the W3C description to indicate that it's incorrect to use `figure` for a decorative image. 

There's also nothing in the W3C description to indicate that using "figure" exclusively is either best practice or how it was intended to be used. I'm curious why WordPress went with the figure, and it seems like an odd choice.
