### ISSUE TITLE
Character Count not getting updated for dynamic block

### ISSUE THREAD

**Issue by shridhamdeveloper** [WordPress/gutenberg#53839] opened 2023-08-21 05:48 UTC
### Description

When dynamic gutenberg block is created the characters present in that block are not getting updated to character count of wordpress document overview.  Below is the screenshot for your reference.

https://prnt.sc/tK9wQu-Ce463

### Step-by-step reproduction instructions

Create any dynamic block and click on document overview option in post editor

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment] 2023-08-21 07:45
Duplicate of https://github.com/WordPress/gutenberg/issues/24879

**Closed as completed** 2023-08-21 07:45 UTC
