### ISSUE TITLE
Using HTML entity `&nbsp;` in text blocks removes part of the undo/redo history

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#36527] opened 2021-11-16 17:17 UTC
## Description

I realized when copying HTML content that, if a text block contains the HTML entity `&nbsp;`, the undo/redo history might be affected and some redo actions are lost.

## Step-by-step reproduction instructions

1. Create a post and add the following HTML code:
```
<!-- wp:paragraph -->
<p>Block 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Block 2</p>
<!-- /wp:paragraph -->
```
2. Save the post and reopen it.
3. Remove the first block, second block, and third block in this order.
4. Undo all the actions until all the blocks are recovered.
5. Redo all the actions and observe that not all blocks are removed.

## Expected behaviour

Undo and redo actions should work as expected independently of the content of the paragraphs.

## Actual behaviour

Some of the redo actions are removed from the history if a paragraph contains `&nbsp;`.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/142032876-e835e275-4315-4b83-9fb2-96974eda827d.MP4

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 15.1
- WordPress app version: `18.7`

**Comment by hypest** [comment] 2021-11-17 11:10
Hmm, I can't replicate on my iPhone 6s, iOS 15.1, WPiOS v18.7. Does it happen consistently for you Carlos?

**Comment by fluiddot** [comment] 2021-11-17 11:32
> Hmm, I can't replicate on my iPhone 6s, iOS 15.1, WPiOS v18.7. Does it happen consistently for you Carlos?

Yeah, for me it happened consistently. Originally, I spotted this issue when copying/pasting the content from https://automattic.com/how-we-work/, specifically the block with text `Jobs` which contains this HTML entity. 

<img width="900" alt="Screenshot 2021-11-17 at 12 26 21" src="https://user-images.githubusercontent.com/14905380/142192103-615e8685-7288-4ca3-93c3-26fe8a9bace1.png">

You could try to reproduce it with the following steps:
1. Create a post.
2. Navigate to https://automattic.com/how-we-work/ and copy the content from `How We Work` to `Professional growth, open vacation policy, generous parental leaves, wellness support, sabbaticals, more.`.
3. Paste the HTML content into the post.
4. Save the post and reopen it.
5. Remove the following heading blocks:
    1. `How We Work` _(H2 heading)_
    2. `Jobs` _(H3 heading)_
    3. `How We Work` _(H3 heading)_
    4. `Benefits` _(H3 heading)_
6. Undo all the actions until all the blocks are recovered.
7. Redo all the actions and observe that not all blocks are removed.

**Comment by hypest** [comment] 2021-11-17 12:50
Hmm, still not replicating for me. Here's a video of my attempt copying from "how we work":


https://user-images.githubusercontent.com/1032913/142203516-6ddcf1d4-e969-4dfb-95f9-b7940fb855c9.mp4


> Remove the following heading blocks:
>
>   How We Work
>    Jobs
>    How We Work
>    Benefits

By the way, I'm not seeing the "Jobs" heading, and looks like the "How We Work" bullet is repeated twice?

**Comment by fluiddot** [comment] 2021-11-17 15:52
Oh sorry, I think I overlooked that two blocks have the same title 😅. The blocks I was referring to are the ones selected in the following screenshot:

<img src=https://user-images.githubusercontent.com/14905380/142234056-6cd38bba-bc1f-475f-943f-537054246a6c.jpeg width=400>

**Comment by hypest** [comment] 2021-11-19 14:25
Aha, reproduced now, thanks for elaborating Carlos! Indeed, the redo list cuts short, less levels available than the undo ones. Interesting. And, only happens on iOS.

**Comment by hypest** [comment] 2021-11-22 14:42
Marked this as "high prio" as there's no "medium prio" but this does break the trust on data safety.

**Comment by fluiddot** [comment] 2022-02-11 14:50
I spotted another side effect of having the HTML entity `&nbsp;` within text content. When selecting a block that contains this entity, it gets automatically removed producing a new undo level.

**Steps to reproduce it:**
1. Add the following HTML code _(extracted from https://automattic.com/how-we-work/)_ via the HTML mode in a post/page:
```
<!-- wp:paragraph -->
<p>We have a one-button deploy system for WordPress.com, and we push code to the site 60–80 times a day. WordPress.com is synced with the WordPress.org trunk pretty much every weekday.&nbsp;<strong>We’re strong believers in&nbsp;<a href="http://opensource.org/">Open Source</a></strong>, and we try to open source everything we can.</p>
<!-- /wp:paragraph -->
```
2. Switch back to Visual mode.
3. Select the Paragraph block.
4. Observe that a new undo level is created.
5. Switch to HTML mode and observe that the `&nbsp;` entities are no longer included in the content.

<details><summary>Click here to display video capture</summary>

https://user-images.githubusercontent.com/14905380/153612439-633ede53-e53a-45d6-aec6-090d5686c78a.MP4

</details>

**Comment by fluiddot** [comment] 2024-01-05 17:34
I confirmed this still happens in version 23.9. Following [this comment](https://github.com/WordPress/gutenberg/issues/36527#issuecomment-975598620) regarding the priority, I'd like to propose keeping the `[Priority] High` label. I'm assigning myself to the issue as I'll try to devote some time next week to take a look.

**Closed as completed** 2024-01-10 08:39 UTC
Labels: [Type] Bug, [Priority] High, [Status] In Progress, [Feature] Writing Flow, Mobile App - i.e. Android or iOS
