### ISSUE TITLE
Polldaddy embeds don't work

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#8608] opened 2018-08-06 16:46 UTC
**Description**

Pasting a polldaddy link into the gutenberg editor does not result in an oembed.

**To Reproduce**

1. Create a post in gutenberg
2. Try to copy any link from PD (http://polldaddy.com/poll/10073993/, [polldaddy poll="10073993"], and http://poll.fm/5zx55 don't work)

**Expected behavior**

I was expecting a preview of the poll to appear.

**Screenshots**

<img width="936" alt="screen shot 2018-08-06 at 9 44 05 am" src="https://user-images.githubusercontent.com/26996883/43729573-91e48cee-995d-11e8-8570-b4299404a3e5.png">

**Desktop (please complete the following information):**
 - iOS
 - Chrome

We should make our own products work with this :)

**Comment by youknowriad** [comment] 2018-08-06 16:52
Just tried with these two links:

 - http://polldaddy.com/poll/10073993/
 - http://poll.fm/5zx55

And it works for me in both cases?

**Comment by annezazu** [comment] 2018-08-06 16:55
@youknowriad  I'm expecting to see this while I'm editing the post in gutenberg not just after publishing. 

Is that an incorrect expectation?

**Comment by youknowriad** [comment] 2018-08-06 17:00
yes, it is. Here's a GIF of what I'm doing.

![pasting](https://user-images.githubusercontent.com/272444/43730206-87b4fe30-99a2-11e8-9d03-c19663f50979.gif)

Notice that the embed appears as soon as I type

**Comment by annezazu** [comment] 2018-08-06 17:55
Hmm - seems this might be related to just our p2s :) cc @designsimply

**Comment by youknowriad** [comment] 2018-08-06 17:56
I'm closing for now, Let's reopen if it comes up in a more generic installation.

**Comment by designsimply** [comment] 2018-08-06 19:08
I am able to confirm this bug with Gutenberg 3.4 using a site with HTTP.  Steps to reproduce:

1. Start with an HTTP site (in case this matters).
1. Copy one of the sample polldaddy poll links from below.
1. Paste the URL into a new block in a new post.

<strong>Sample code:</strong>

* `http://polldaddy.com/poll/10073993/`
* `[polldaddy poll="10073993"]`
* `http://poll.fm/5zx55`

<strong>Result:</strong> embed does not work, a console warning appears on the editor screen, and the poll is blank on the front end after publishing and viewing the post.

Console warning after pasting the poll URL in the editor:

`Loading failed for the <script> with source “http://static.polldaddy.com/p/10073993.js”.`

Resulting HTML in the block:

```
<figure class="wp-block-embed is-type-rich is-provider-polldaddy">
http://polldaddy.com/poll/10073993/
</figure>
```

<strong>Video:</strong> [53s](https://cloudup.com/cGJuXPtELUN)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14107&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

![polldaddy-embed-example](https://user-images.githubusercontent.com/1119271/43736137-ccbf4dc4-9979-11e8-86ce-b02c25830fc4.png)


I'm not re-opening yet because it may be fixed in master but not 3.4 and that still needs double checking.

**Comment by youknowriad** [comment] 2018-08-06 19:11
I'm also running an HTTP site, so this is probably something else. Any idea @notnownikki ?

**Comment by earnjam** [comment] 2018-08-06 19:45
@designsimply It worked for me on HTTP using the poll link you posted above on 3.4 and also on `master`. Did you try to pull up the JS file directly from the error message and seeing if it worked independent from WP?

(Also hi @annezazu! 😄 )

**Comment by notnownikki** [comment] 2018-08-06 21:15
Just tested with http://polldaddy.com/poll/10073993/ and it's showing up for me, the embed render endpoint doesn't have any issue.. My development site is also HTTP.

@designsimply What's interesting is that the shortcode `[polldaddy poll="10073993"]` isn't working for you, that suggests either something isn't getting processed correctly in the WP core side, or that there's some intermittent problem on the Polldaddy side. I think this is most likely a Polldaddy or network problem, as the embed is trying to load the assets, but as I can see from your console output, the script wasn't loaded. To make doubly sure, can you open the network tab and see what response you got for that script?

**Comment by designsimply** [comment] 2018-08-08 22:48
> To make doubly sure, can you open the network tab and see what response you got for that script?

Absolutely! I re-tested and found that the script response looks good (in both Chrome and Firefox!)  _but in Firefox_ the embed does not show up inside the editor (same as before). Here's a comparison: [1m28s](https://cloudup.com/cz-qUPaspMv).

![screen shot 2018-08-08 at wed aug 8 4 33 06 pm](https://user-images.githubusercontent.com/1119271/43867961-99f6ac74-9b28-11e8-8361-69853e054635.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14183&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Here are the console errors from Firefox:

> The resource at “http://static.polldaddy.com/p/10073993.js” was blocked because tracking protection is enabled.[Learn More] 
> post-new.php

> Loading failed for the <script> with source “http://static.polldaddy.com/p/10073993.js”. 
> post-new.php:12 

Here is a screenshot of the Network tab from Firefox showing the script response looks good but the embed has gone missing anyway:

![polldaddy-firefox-embed-showing-network-tab-with-script-response](https://user-images.githubusercontent.com/1119271/43868138-5e1c2840-9b29-11e8-8b0c-4907d3980784.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14183&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Here is the script response from the Network tab in Firefox:

`{"type":"rich","version":"1.0","provider_name":"Polldaddy","provider_url":"http:\/\/polldaddy.com","title":"What day do you want office hours to be on?","html":"<script type=\"text\/javascript\" charset=\"utf-8\" src=\"http:\/\/static.polldaddy.com\/p\/10073993.js\"><\/script><noscript><a href=\"http:\/\/polldaddy.com\/poll\/10073993\/\">What day do you want office hours to be on?<\/a><\/noscript>"}`

I also figured out that I can avoid this problem if I disable Tracking Protection by checking the option for "Never" in Firefox > Preferences > Privacy & Security and restarting Firefox (https://support.mozilla.org/en-US/kb/tracking-protection#w_how-to-turn-tracking-protection-on). I feel the embed should work without users needing to change a setting like that, do you agree? If so, is this something that should therefore be filed as a problem with Polldaddy directly?

**Closed** 2018-10-27 21:33 UTC
Labels: Blocks, Browser Issues, [Block] Embed, [Type] Bug
