### ISSUE TITLE
Inserter on Columns block is difficult to use

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#9438] opened 2018-08-29 16:14 UTC
**Describe the bug**
The inserter icon `+` is too difficult to click on the Columns Block (nested blocks). I'm using Gutenberg 3.6.2.

**To Reproduce**
1. Create a Columns Block
2. Enter content in each column
3. Deselect the block so that the inserter UI appears when you hover
4. Try to click the inserter `+` for the block container of the nested blocks. Good luck!

**Expected behavior**
I expected the inserter `+` not to be so difficult to click.

**Screenshots**
![inserter-nested-blocks](https://user-images.githubusercontent.com/617986/44800559-8a016e00-ab6b-11e8-9474-49de57842888.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Chrome
 - Version 68.0.3

**Comment by HippDesign** [comment] 2018-08-30 20:20
I can reproduce this issue. I agree with @mapk - the elements like the Inserter needs more space - there should be no overlapping.

**Comment by jasmussen** [comment] 2018-09-04 10:48
There are numerous tickets open for improving insertion of blocks, notably in nested situations, including:

- https://github.com/WordPress/gutenberg/issues/7271 for improving the consistency of behavior
- https://github.com/WordPress/gutenberg/issues/5772 general bugs

The issue is rather complex and is not just about making sure it's easy to select the sibling inserter that precedes a fully populated columns block. It's also about managing nested blocks in a good way.

One solution would be to simply remove the sibling inserter altogether, and require you to select the separator and press enter to make a new space below it. Or select the separator and use the top inserter. Those are all discussions that have been going on for a while now.

One thing that is going to be impoved soon, is the nested block selection. For example we might make it so before you can select any block inside the columns block, you have to select the columns block itself first. I.e. child blocks are locked until you click the colums block. This would solve the issue you're seeing here. I hope to work on this soon, stay patient as I try to fix it.

In the mean time I'm going to close this ticket as a duplicate of #6842.

**Closed by jasmussen** 2018-09-04 10:48 UTC
Labels: [Component] Inserter, [Component] Nested / Inner Blocks, [Type] Enhancement
