### ISSUE TITLE
Global Styles: Scroll bars appear when a variation panel is hovered, on certain browser and resolution

### ISSUE THREAD

**Issue by fushar** [WordPress/gutenberg#46506] opened 2022-12-13 14:14 UTC
### Description

In the Global Styles sidebar, scroll bars are displayed when a variation panel is hovered. As far as I observe, this only happens in this situation:

1. Browser is Firefox
2. External monitor is used

(see version details below)

I believe this is the exact same issue as #44796. It was fixed on 14.4.0 via #44823. Interestingly, this issue only occurs after 14.4.0 -- it didn't happen before that. So it looks like the fix (#44823) solved the previous issue but introduced another issue (this issue).

cc: @t-hamano @mtias 

### Step-by-step reproduction instructions

1. Activate a block theme with style variations (e.g. TT3)
2. Open the Global Styles sidebar, and click Browse Styles.
3. Observe that vertical and horizontal scroll bars appear momentarily when you mouse over or focus on a variation preview panel.

### Screenshots, screen recording, code snippet

![](https://user-images.githubusercontent.com/1525580/207348425-216d301e-9fc7-4806-bc50-84ef90df7a80.gif)

### Environment info

- WordPress 6.1.1
- Gutenberg 14.7.1
- Firefox 107.0.1 (64-bit)
- macOS Monterey 12.1 (M1 Pro)
- LG 27UP850-W Monitor 27-Inch IPS 4K UHD VESA HDR400 USB-C with the following settings:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/1525580/207355660-17e24e20-cfad-45b2-8e3d-960ff4147357.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by dsas** [comment] 2022-12-13 18:19
Oddly, I can reproduce that in Gutenberg 14.7.1 but I can't reproduce it in Gutenberg trunk (6a54882a9).

**Comment by t-hamano** [comment] 2022-12-14 04:40
@dsas 
I got the same result. This problem occurs in Firefox, but not in Chrome.

- Released Gutenberg Plugin version **14.7.1**: Reproduced
- Released Gutenberg Plugin version **14.7.2**: Reproduced
- Use the plugin built by `build:plugin-zip` in the `latest trunk`: NOT reproduced

~~I think Gutenberg plugin version 14.7.2 and trunk are almost identical, so I don't know why this difference occurs.~~
Sorry, this one was my misunderstanding.

Just to be sure, we will retest with Gutenberg Plugin 14.8, which will be released in two weeks, and  I think we can close this issue if the problem does not appear.

**Comment by t-hamano** [comment] 2022-12-14 05:49
I have identified a PR that has resolved this issue.
This issue appears to have been unintentionally resolved in #44770.

![44770](https://user-images.githubusercontent.com/54422211/207515950-33542b0c-faeb-49d6-836f-51838f456659.png)

The #44770 is included in the unreleased Gutenberg version **14.8**.

@fushar
I would like to close this issue as resolved. If you reproduce the problem in the version 14.8 to be released, I would be glad to receive your comments.

Thanks for your contribution!

**Closed as completed by t-hamano** 2022-12-14 05:49 UTC
Labels: [Type] Bug, [Type] Regression, Global Styles
