### ISSUE TITLE
Setting a jumpmark

### ISSUE THREAD

**Issue by andreasdiehl** [WordPress/gutenberg#23716] opened 2020-07-06 14:58 UTC
If a jumpmark is set in a default table and the jumperk should end at an abstract / headline which is immediately below the table, the jumpmark does not work.

How to reproduce:

1. create a table with 20 rows
2. create an abstract below the table
3. set a jumpmark from the first column to the abstract / headline directly below the table

I had this issue in this article, I only managed to fix this by setting this to an "advanced table"
https://digitaleneuordnung.de/blog/foerdermittel-digitalisierung/

**Comment by talldan** [comment] 2020-07-14 08:58
@andreasdiehl  Thanks for reaching out. I couldn't reproduce this issue. At the end of the day, this is just an HTML link, so I'm not sure how the table block could cause a problem like this.

> I had this issue in this article, I only managed to fix this by setting this to an "advanced table"

There isn't an "Advanced Table" option in Gutenberg, this makes me think your issue might be caused by a plugin?

**Comment by andreasdiehl** [comment] 2020-07-14 18:31
@talldan thats true, "advanced table" is from a plugin. As it works with the advanced table I will not further investigate, just wanted to bring this to attention. Though again to reproduce, the table should imo have > 20 rows.

**Comment by talldan** [comment] 2020-07-15 02:33
@andreasdiehl Yep, I tried with a table of over twenty rows, and didn't have any issues.

I'm going to close the issue as I can't reproduce it.

**Closed by talldan** 2020-07-15 02:33 UTC
Labels: [Status] Needs More Info
