### ISSUE TITLE
Calendar in 4.1 - Layout destroyed

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#10846] opened 2018-10-21 04:01 UTC
Are new features tested, before they go into a new release package?

Bug is described in the animated gif.
Gutenberg 4.1, Windows 10 64 bit, Chrome - all recent versions.

![calendar_oups](https://user-images.githubusercontent.com/1585416/47262977-c2338600-d4f6-11e8-8397-398bde6d9292.gif)

**Comment by GlennMartin1** [comment] 2018-10-21 07:04
This has already been fixed in https://github.com/WordPress/gutenberg/pull/10831

**Comment by ocean90** [comment] 2018-10-21 08:49
Duplicate of #10825.

**Closed by ocean90** 2018-10-21 08:49 UTC
Labels: [Status] Duplicate
