### ISSUE TITLE
Recent blocks shows empty at times

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1897] opened 2017-07-14 10:48 UTC
![image](https://user-images.githubusercontent.com/548849/28209415-b1630318-6892-11e7-93ae-cbc0d4f21d85.png)

@notnownikki haven't debugged this one, but I've seen the recent blocks inserter ending up empty in different occasions.

**Comment by notnownikki** [comment] 2017-07-14 10:52
That's super weird, never seen that happen! When you saw it then, were you changing tab back to recent, or just clicking on the inserter?

**Comment by mtias** [comment] 2017-07-14 11:59
Just clicking on the inserter.

**Comment by notnownikki** [comment] 2017-07-14 13:16
What browser are you using? I can't reproduce this one :disappointed: 

I can see in the screenshot that you've got blocks added, so this suggests one of the following:

1) Adding a block to the recently used list is going wrong, and we end up with an empty list - I can't see how this would happen, but lines 229-248 in editor/state.js are where this happens so if we see it happening, that's where we need some debug to find out if it's happening there.

2) Connecting the redux state to the component is not getting the correct state. This is the part of the react/redux lifecycle I understand the least, so it's possible that's messing up somehow, but right now I can't see how.

I don't think this is anything to do with the search state, because the tabs are still rendering, so we're not searching - if we were, there would be no tabs.

**Comment by westonruter** [comment] 2017-07-15 06:04
@notnownikki I can reproduce this by opening an _existing_ post in Gutenberg. Even though I have blocks in my content already, since I haven't actually inserted any blocks since I loaded the page, there is no data yet to populate the recent blocks. Is this not the same as #1859?

**Comment by notnownikki** [comment] 2017-07-15 11:33
Oh! Ok, it's not the same, as it seems I haven't hooked into all the correct actions, and #1859 is about providing the API for the current code to use. Thanks, I'll get on this, it should just be a matter on taking down which actions need to be responded to.

**Comment by notnownikki** [comment] 2017-07-17 08:59
Should be fixed in https://github.com/WordPress/gutenberg/pull/1920

**Comment by hedgefield** [comment] 2017-07-18 08:28
Have the same issue after updating to 0.5.0. It happens every time I open an existing post in gutenberg, like weston said.

**Comment by notnownikki** [comment] 2017-07-18 08:37
@hedgefield thanks for verifying :smile: I have a branch where this is fixed, we're just making sure that everything is in the right place and named correctly, as it introduces some hooks for loading and saving user specific data (such as block usage!)

**Comment by aduth** [comment] 2017-07-21 12:25
Should be fixed by #1920

**Closed by aduth** 2017-07-21 12:25 UTC
Labels: [Component] Inserter, [Type] Bug
