### ISSUE TITLE
Mobile testing: Android & iOS text toolbar overlaps block toolbar

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#3961] opened 2017-12-12 21:41 UTC
See below for screenshots from an Android mobile device and an iOS iPad 2. While selecting text (the word `Mountains` from the sample post in the screenshots below), the OS-level text toolbar overlaps the block toolbar, making it impossible to use it for text formatting.

Note that this is not a new problem in Gutenberg, this happens in the current editor too.

I'm not sure what could be done to mitigate this problem. Attempting to display the block toolbar higher up on such devices could work but could introduce its own problems. I've not looked at how similar editors behave on Android and iOS.

---

## Android

![screenshot_20171212-210153](https://user-images.githubusercontent.com/208434/33909665-50329392-df84-11e7-848a-764343851911.png)

## iOS

![file 12-12-2017 21 31 17](https://user-images.githubusercontent.com/208434/33909679-5c9033ba-df84-11e7-8520-077cdb7d1639.png)

**Comment by rosswintle** [comment] 2018-01-01 21:32
Just came here to +1 this. It needs attention. I REALLY struggled to create a post on my iPad with Gutenberg 1.9.1 and this was one of the main reasons.  My own screengrab:

![img_1284](https://user-images.githubusercontent.com/1532368/34471211-2b1930ae-ef3b-11e7-983e-b92ee80f96b6.PNG)

**Comment by jasmussen** [comment] 2018-05-17 09:48
In https://github.com/WordPress/gutenberg/pull/6347 I pushed a fix to put the block toolbar below the block on the mobile breakpoint.

If we can confirm that this addresses the initial issue, I can probably extend that feature to either apply to very short viewports (like an iPad with the soft keyboard showing), or we can use some user agent detection to use apply the same to iPads.

**Comment by johnbillion** [comment] 2018-05-17 09:54
I wonder if pinning the formatting toolbar to the _bottom_ of the viewport could work. So it appears as an extension to the keyboard. I've seen other apps do this.

**Comment by jasmussen** [comment] 2018-05-17 10:03
> I wonder if pinning the formatting toolbar to the bottom of the viewport could work. So it appears as an extension to the keyboard. I've seen other apps do this.

😭 
I know. This would be idea. We've tried both pinning to the top and pinning to the bottom. I've tried so many different things, but the short answer is that iOS Safari is a nightmare to work with, when it comes to text, and there's little we can do. [The ugly details are in this expose](https://github.com/WordPress/gutenberg/pull/6347#issuecomment-385473537).

![viewport](https://user-images.githubusercontent.com/1204802/40170932-1dd1d032-59ca-11e8-84b5-e6319832ec40.gif)

The problem is, that the soft keyboard on iOS doesn't change the viewport at all. And everything that's fixed or even abs positioned changes when the soft keyboard is showing. I would never say "it can't be done" because I'm sure it an. But I don't see how it can be done. 

It can be done in native apps, obviously, but we are at the mercy of Mobile Safari here. 

┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻

**Comment by youknowriad** [comment] 2019-01-26 15:35
There has been a lot of changes since the last updates here, is this still valid? anything actionable?

**Comment by jasmussen** [comment] 2019-01-26 16:19
Honestly this has been addressed to the best of our ability, given the technical reality of mobile Safari. By moving the block toolbar below the block on phones, and with the ability to dock the toolbar to the top on iPads, there is little more we can realistically do.

I'd suggest close and reopen if the issue resurfaces.

**Closed** 2019-01-26 16:31 UTC
Labels: [Component] Mobile
