### ISSUE TITLE
Document Actions: Block Toolbar overlaps Document Titles

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#25803] opened 2020-10-03 00:29 UTC
**Describe the bug**
When scrolling through the block editor, if a block toolbar is displayed, it can overlap the document actions labels.

**To reproduce**
1. Set up the site editor locally
2. Navigate to the site editor 
3. Hover over a sibling inserter
4. Scroll down through the editor until the block toolbar would overlap the document actions labels
5. Verify that there is no visual overlap

**Expected behavior**
When scrolling through the block editor, the block toolbar does not overlap document actions labels.

**Screenshots**
![2020-10-02 17 27 24](https://user-images.githubusercontent.com/5414230/94978922-b6b7aa80-04d4-11eb-8490-f834b67aedb8.gif)

**Comment by Addison-Stavlo** [comment] 2020-10-06 20:04
I noticed the block-popover has z-index of 31, while the header in the interface skeleton has z-index of 30.  It seems to be noted as intended to be above the header:
https://github.com/WordPress/gutenberg/blob/c2ea1b27df08117dbf53200630e8a627f4479df1/packages/base-styles/_z-index.scss#L91-L92

However, it does not behave this way in the post editor.  I tried to dig around a bit but am unsure why it behaves differently in the other editor. 🤔

**Comment by jeyip** [comment] 2020-10-14 23:31
@shaunandrews 

I see that you introduced the code Addie mentioned above. Link to the [commit](https://github.com/WordPress/gutenberg/pull/21056/commits/5e88bb6970a2c61abd6037ec5853187b767078f9) and the [pr](https://github.com/WordPress/gutenberg/pull/21056). Do you happen to remember why we wanted the popover above the block list _and_ the header

**Comment by shaunandrews** [comment] 2020-10-14 23:32
Mainly so the parent selector button would be visible.

**Comment by david-szabo97** [comment] 2021-02-25 13:54
This seems to be resolved by now:


https://user-images.githubusercontent.com/2256104/109163107-42c6b900-7779-11eb-9f65-18d84b9b914c.mov

**Comment by shaunandrews** [comment] 2021-02-25 22:39
Can confirm; This has been fixed.

**Closed by shaunandrews** 2021-02-25 22:39 UTC
Labels: [Feature] Full Site Editing, [Type] Bug
