### ISSUE TITLE
content_edit_pre does not affect Gutenburg  content

### ISSUE THREAD

**Issue by inoodle-Git** [WordPress/gutenberg#17836] opened 2019-10-08 10:17 UTC
**Describe the bug**
Filter content_edit_pre() does not affect Gutenburg  content. This filter hook is used to modify the post content before it is loaded into the editor, it works well in classic editor, but not making any difference in Gutenburg editor.

**To reproduce**
add this in theme function.php:
```
function test_of_content_edit_pre( $content, $post_id ) {
    return "Insert this before the content about to be edited ".$content;
}
add_filter( 'content_edit_pre', 'test_of_content_edit_pre', 10, 2 );

```
**Expected behavior**
When loading post content with gutenburg editor, the filtered content is expected, this will be displayed on screen:"Insert this before the content about to be edited"

**Desktop (please complete the following information):**
 - OS: mac os 10.13
 - Browser chrome
 - Version 70

**Screenshot - Gutenburg**
![image](https://user-images.githubusercontent.com/51308734/66387953-abcc5600-e9f7-11e9-83f1-938bc7052bca.png)

**Screenshot - Classic Editor **
![image](https://user-images.githubusercontent.com/51308734/66387854-6f005f00-e9f7-11e9-95d0-393ef91f1aac.png)

**Additional context**
- Please add the version of Gutenberg you are using in the description : wordpress 5.2.3

**Comment by talldan** [comment] 2019-10-08 22:59
Hi @inoodle-Git, thanks for reporting this. Since `content_edit_pre` is a filter defined in WordPress core, it'll have to be reported in trac. I had a quick search in trac and I think the issue is a duplicate of this: https://core.trac.wordpress.org/ticket/12939

Let me know if you think otherwise, but I think this is more of an issue now because of Gutenberg using the REST API, which it looks like is affected by this bug.

I'll close this issue, it'd be great if you could add more thoughts to the trac issue.

**Closed by talldan** 2019-10-08 22:59 UTC

**Comment by inoodle-Git** [comment] 2019-10-09 02:55
Thank you for your response. After some search I found the correct filter for changing content when loading post with REST api is `_rest_prepare_pos_t__`, I added this in function.php and it worked:

	function my_rest_prepare_post( $data, $post, $request ) {
		$_data = $data->data;
		$_data['content']['raw']="Insert this before the content about to be edited ".$_data['content']['raw'];
		$data->data = $_data;

		return $data;
	}
	
	add_filter( 'rest_prepare_post', 'my_rest_prepare_post', 10, 3 );
![image](https://user-images.githubusercontent.com/51308734/66448100-0a8ae180-ea83-11e9-8c01-5bd07f73814c.png)


And it seems for  3rd party offline editors, the hook `xmlrpc_prepare_post` should be used to change the content.
