### ISSUE TITLE
Command Palette: Back arrow takes you into a navigation loop under some circumstances

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/gutenberg#52946] opened 2023-07-25 16:31 UTC
### Description

After searching for a template or template part, you sometimes cannot get back to the main Design screen by using the back arrows. Instead, you get stuck in a loop going back and forth between "All template parts" and "Patterns."

### Step-by-step reproduction instructions

1. Go to Appearance > Site Editor
2. Click into the preview area on the right
3. Open the command palette (by clicking into it or typing command-K or control-K) and enter "Post meta"
4. Click the "Post Meta" template to select it
5. Click the WordPress icon at the top left
6. Click the back arrow to reach "All template parts"
7. Click the back arrow again to reach "Patterns"
8. Click the back arrow again, you're now at "All template parts" again

### Expected

There should be a way to get back to the main "Design" area of the Site Editor – without having to click the WordPress icon and repeat steps 1 & 2

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7662449/7093e582-e2ad-4ea4-983e-a2a63bbe06d5

### Environment info

- WP 6.3-RC1
- Gutenberg not active
- No other plugins active aside from Beta Tester

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stokesman** [comment] 2023-07-26 18:11
I'm not sure but maybe this was #52665 and addressed by #52910?

**Comment by t-hamano** [comment] 2023-07-27 12:32
I believe this issue is a duplicate of #52690. I would like to close this issue and add #52690 to the 6.3 project board.

**Closed as not planned by t-hamano** 2023-07-27 12:32 UTC
Labels: [Type] Bug, [Status] Duplicate, [Package] Commands
