### ISSUE TITLE
Broken editor style in some themes (Twenty Twenty and Twenty Nineteen)

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#34479] opened 2021-09-02 00:35 UTC
### Description

I've stumbled upon a few styling oddities when trying Gutenberg v11.4.0 with some themes, namely `Twenty Twenty` and `Twenty Nineteen`. I assume this issue _could_ be more widespread and affect other themes in unexpected ways, too (?)

WIth `Twenty Twenty`, the page title input has shifted way to the left of the page, not aligning with the block list area horizontally:

<img width="2800" alt="TwentyTwenty" src="https://user-images.githubusercontent.com/81248/131762701-dd06d9ea-5f43-4b96-89d3-88842818f251.png">

_Left is v10.3.0, right is v11.4.0._

In the case of `Twenty Ninteteen`, the same problem exists (though it looks like it was already present in previous versions of Gutenberg), but there's one minor issue thing that seems to have been introduced by v11.4.0:

![twentynineteen](https://user-images.githubusercontent.com/81248/131762709-44b61c98-2e0f-4334-85aa-aa82729a38f3.png)

_Left is v10.3.0, right is v11.4.0._

I've bisected and it seems to have been introduced by this changeset: https://github.com/WordPress/gutenberg/pull/34167.

### Step-by-step reproduction instructions

1. Using `trunk` or `v11.4.0`, set the theme to `Twenty Twenty` or `Twenty Nineteen`;
2. Start a new page or post;
3. Verify how the alignment between the title and the block list area looks odd. In the case of `Twenty Nineteen`, there's another minor alignment issue (see screenshot above);
4. If you built from source, try reverting `e30d875` and rebuild Gutenberg;
5. Verify that `Twenty Twenty` looks fine now. `Twenty Nineteen` still looks odd, though one of the alignment issues is gone (refer to the screenshots above for a visual reference).

### Environment info

- Wordpress `5.8-beta4-51266`;
- Gutenberg `v11.4.0` (or built from `trunk`);
- Ubuntu Linux 18.04;
- Firefox 92.0b9 (64-bit)

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by talldan** [comment] 2021-09-02 04:00
Thanks for reporting this! I also noticed yesterday that this is the situation in Twenty Seventeen:
<img width="915" alt="Screenshot 2021-09-02 at 11 57 53 am" src="https://user-images.githubusercontent.com/677833/131779595-a3f30e4e-9156-4e09-aa1b-4806fa6a670d.png">

Also had a situation where the toolbar also appeared underneath the first block because of the lack of space at the top 😱

**Comment by fullofcaffeine** [comment] 2021-09-02 21:45
> Also had a situation where the toolbar also appeared underneath the first block because of the lack of space at the top scream

I also noticed that, but this appears to be an older bug. I just tested and it happens on v11.3.0, too, it's just that the bigger top margin on (most?) of the themes created more space for the toolbar and it didn't overlap with the top bar in the Desktop viewport.

**Comment by fullofcaffeine** [comment] 2021-09-04 03:47
We found another issue that manifests with the `Twenty Twenty` theme on Firefox (`92.0b9 (64-bit), Linux`), `desktop`, and `mobile` viewports. The overflow rules for the title seem wrong or are not applying for some reason, and the title goes beyond the bounds instead of wrapping:

![Screenshot from 2021-09-03 13-48-15](https://user-images.githubusercontent.com/81248/132081435-0e25a189-1b74-4898-997e-233679a89db0.png)


Doesn't happen on Chrome and Safari.

**Comment by ellatrix** [comment] 2021-09-06 08:18
I cannot reproduce the issue in Firefox with Twenty Twenty. The text seems to wrap fine for me.

![image](https://user-images.githubusercontent.com/4710635/132184192-8094294a-7d4e-4c46-9cd3-f7bc5799b578.png)

**Comment by ellatrix** [comment] 2023-08-16 12:03
@fullofcaffeine Could you open a new issues if there's another problem with more info on how to reproduce and what style is missing?

**Comment by ellatrix** [comment] 2023-08-16 12:04
In any case, this seems unrelated to the original issue and more like a styling issue with the theme. I will close this PR but feel free to reopen if I'm wrong.

**Closed as completed by ellatrix** 2023-08-16 12:04 UTC
Labels: [Status] In Progress, [Type] Regression, [Feature] Themes, CSS Styling
