### ISSUE TITLE
Adding a "Classic" block as part of InnerBlocks leads to "Block validation failed" error

### ISSUE THREAD

**Issue by bperel** [WordPress/gutenberg#13916] opened 2019-02-18 10:42 UTC
**Describe the bug**
I created a simple Gutenberg block that allows the editor user to add inner blocks inside, using `<InnerBlocks />`. When inserting a Classic block in the inner blocks section, then saving the page and refreshing the editor page, it breaks with the error `Block validation: Block validation failed for me/section-block`.

**To Reproduce**
1. Create a Gutenberg block using [create-guten-block](https://github.com/ahmadawais/create-guten-block).
2. Use the following code in the file `src/block/block.js` : 
```javascript
const {__} = wp.i18n;
const {registerBlockType} = wp.blocks;
const {InnerBlocks} = wp.editor;

registerBlockType('me/section-block', {
	title: __('Section block'),
	icon: 'admin-site',
	category: 'layout',

	edit: props => {
		const { className } = props;
		return <div className={className}>
			Inner blocks :
			<InnerBlocks />
		</div>;
	},

	save: props => {
		return (
			<div>
				<InnerBlocks.Content />
			</div>
		);
	}
});
```
3. Activate the plugin in Wordpress 
4. Add a "Section block" on a page. Under "Inner blocks :", insert a classic block and write something in it :
![screenshot from 2019-02-18 11-22-06](https://user-images.githubusercontent.com/1484692/52945182-6debc600-3371-11e9-82df-547bac23aed2.png)
5. Publish the page and refresh the editor page.
6. An error shows in the editor page instead of the section block :
![screenshot from 2019-02-18 11-41-48](https://user-images.githubusercontent.com/1484692/52945543-3df0f280-3372-11e9-8327-741db6c79047.png)

The console shows the following error :
![screenshot from 2019-02-18 11-32-14](https://user-images.githubusercontent.com/1484692/52945199-77752e00-3371-11e9-9aa2-68a78ad93d35.png)

**Expected behavior**
The section block should show with the content written in the classic editor inside.

**Additional context**
- The problem appears both in Wordpress 5.0.3 and the bleeding edge version.

**Comment by youknowriad** [comment] 2019-02-18 10:45
duplicate of #13187

**Closed by youknowriad** 2019-02-18 10:45 UTC
