### ISSUE TITLE
Custom date range broken in Analytics

### ISSUE THREAD

**Issue by glagonikas** [WordPress/gutenberg#43900] opened 2022-09-06 10:50 UTC
### Description

When Gutenberg 14.0.2 and Woocommerce 6.8.2 are enabled, the "custom date" on the Analytics section (/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue) appears to be broken.

Think that's caused because of https://github.com/WordPress/gutenberg/blob/v14.0.2/lib/client-assets.php#L282-L288 which overwrites wp-components and the CSS is not loaded.

Disabling Gutenberg seems to resolve the issue.

### Step-by-step reproduction instructions

1. Enable Woocommerce 6.8.2
2. Enable Gutenberg 14.0.2
3. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue
4. Click on the date range
5. Click on "Custom"

### Screenshots, screen recording, code snippet

<img width="209" alt="image" src="https://user-images.githubusercontent.com/10516403/188616349-e2a6ecaa-78d1-4f3a-aec7-13062063522a.png">

### Environment info

- Wordpress 6.0.2
- Storefront 4.1.3
- Woocommerce 6.8.2
- Gutenberg 14.0.2
- Chrome on Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-09-09 00:44
@nerrad might you have any insights here?

**Comment by t-hamano** [comment] 2023-04-17 13:55
@glagonikas 

Thanks for the report.

I could not reproduce it with the latest WordPress and Gutenberg plugins. This issue was reported as [#35645](https://github.com/woocommerce/woocommerce/issues/35645) in the woocommerce GitHub repository and appears to have been fixed in [#35649](https://github.com/woocommerce/woocommerce/pull/35649).

I would like to close this issue, but if the issue has not been resolved, please don't mind commenting.

**Closed as completed by t-hamano** 2023-04-17 13:55 UTC
Labels: [Type] Plugin Interoperability
