### ISSUE TITLE
Gutenberg link in posts table takes you to a blank page

### ISSUE THREAD

**Issue by Kluny** [WordPress/gutenberg#1235] opened 2017-06-17 22:19 UTC
Gutenberg link in posts table takes you to a blank page. Expected: a Gutenberg editor with the text of the old post, which was written using the TinyMCE editor, ready to edit in Gutenberg. 

Using WordPress.org install on PHP 7 with WP 4.8.

Screencap of the link I'm talking about:
![screen shot 2017-06-18 at 00 16 56](https://user-images.githubusercontent.com/310102/27256634-7eb0403e-53bb-11e7-87ad-9caab0f6bdb5.png)

Screencap of the blank page I get after clicking it:
![screen shot 2017-06-18 at 00 19 06](https://user-images.githubusercontent.com/310102/27256637-d54164b4-53bb-11e7-96c1-63e7d8df4c22.png)

**Comment by westonruter** [comment] 2017-06-19 03:28
I notice this sometimes happening as well. Usually it is fixed by doing a hard reload.

**Comment by westonruter** [comment] 2017-06-19 03:29
In my console I see an error:

> Uncaught TypeError: wp.api.collections.Posts is not a constructor

**Comment by westonruter** [comment] 2017-06-19 03:31
The error can be reproduced when loading the screen after doing `sessionStorage.clear()`. The issue is in the latest-posts block. It's not deferring for the WP-API to be initialized.

**Comment by westonruter** [comment] 2017-06-19 03:56
@Kluny please test #1235

**Comment by Kluny** [comment] 2017-06-21 08:11
Tested. Blog is located at http://rocketships.ca and hosted by Webfaction. I uninstalled the plugin, and reinstalled, but there was no difference - I assume this fix hasn't made it into the public download yet. 

I removed it and installed using git clone git@github.com:WordPress/gutenberg.git.

After activating the plugin I see these errors on my dashboard at http://rocketships.ca/wp-admin/plugins.php?plugin_status=all&paged=1&s

```
Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/utils/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 51

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/date/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 57

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/i18n/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 89

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/element/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 95

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/components/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 101

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/blocks/build/index.js in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 107

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/components/build/style.css in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 115

Warning: filemtime(): stat failed for /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/blocks/build/style.css in /home/kluny/webapps/rocketblog/wp-content/plugins/gutenberg/lib/client-assets.php on line 
```

**Comment by youknowriad** [comment] 2017-06-21 09:49
@Kluny Did you try installing from the plugin repository? see https://github.com/WordPress/gutenberg/issues/1220

**Comment by Kluny** [comment] 2017-06-21 10:27
@youknowriad, I did try it that way first, but I got the same result (blank page when clicking the link in the posts table). I can try it again.

**Closed** 2017-06-21 16:23 UTC
Labels: [Type] Bug
