### ISSUE TITLE
The taxonomy panel post_tag do not refresh with programmatical update

### ISSUE THREAD

**Issue by herewithme** [WordPress/gutenberg#15147] opened 2019-04-24 13:09 UTC
**Describe the bug**

With WP 5.1.1 and Gutenberg plugin 5.5.0

The taxonomy panel post_tag do not refresh with programmatical update for a new relationship with a term

**To reproduce**

I have 2 tags with the term_id 3 & 4 
I edit an article that is already linked to the term 3

If i call this function
```
wp.data.dispatch('core/editor').editPost({tags: [4]})
```
The panel does not update.

If I delete the term 3 by hand, via my browser
and i call this function
```
wp.data.dispatch('core/editor').editPost({tags: [3]})
```
The panel is updated.

In both cases, the link between the article and the terms are well recorded in the database.

**Expected behavior**

The update of the tags via the API must be reflected in the user interface for a new as an existing tag.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 73

**Comment by herewithme** [comment] 2019-04-24 13:32
The behavior is OK, if the term appeared within autocompletion (even if not clicked), following the AJAX call on the REST API!

**Comment by Mamaduka** [comment] 2021-06-17 12:40
I'm able to reproduce the issue.

The `FlatTermSelector` fetches term objects on `componentDidMount`. When post tags are updated terms programmatically new term object isn't fetched.

If you close/open the "Tags" panel new term should be visible since component remounts.

**Comment by lear2012** [comment] 2021-06-18 02:06
I experienced the same issue. 
wp.data.dispatch('core/editor').editPost({tags: [3]}) invoked in component class, it doesn't work as expected.

**Comment by harisrozak** [comment] 2021-11-17 15:55
> I'm able to reproduce the issue.
> 
> The `FlatTermSelector` fetches term objects on `componentDidMount`. When post tags are updated terms programmatically new term object isn't fetched.
> 
> If you close/open the "Tags" panel new term should be visible since component remounts.

Nice catch!, so for now, we can programmatically toggle the "Tags" panel to achieve the right behavior, maybe something like this:

```
var tag_id              = 23;
var is_tax_panel_opened = wp.data.select( 'core/edit-post' ).isEditorPanelOpened( 'taxonomy-panel-tags' );
var selected_term_ids   = wp.data.select( 'core/editor' ).getEditedPostAttribute( 'tags' );

// set terms
if ( ! selected_term_ids.includes( tag_id ) ) {
	selected_term_ids.push( tag_id );
	wp.data.dispatch( 'core/editor' ).editPost( { 'tags': selected_term_ids } );

	// close and re-open the panel to reload the term data
	if ( is_tax_panel_opened ) {
		wp.data.dispatch( 'core/edit-post' ).toggleEditorPanelOpened( 'taxonomy-panel-tags' );
		wp.data.dispatch( 'core/edit-post' ).toggleEditorPanelOpened( 'taxonomy-panel-tags' );
	}			
}
```

**Comment by Mamaduka** [comment] 2021-11-18 06:13
Sorry forgot to post an update here. The issue should be fixed via #33459 and available in Gutenberg 11.9.

**Closed by Mamaduka** 2021-11-18 06:13 UTC
Labels: [Type] Bug, [Feature] Document Settings, REST API Interaction

**Comment by edufolios-matt** [comment] 2021-12-08 00:52
@Mamaduka - I'm currently using the approach by @harisrozak above. This updated the UI and the Redux store, yet if I save the Post (which I currently have to enable through updating a faux private metafield, otherwise the Update button doesn't enable), the tags / categories aren't saved, the UI reloads with the tags / categories cleared of any selection applied.

Is there a mechanism to mark tags / categories "dirty" that I've missed maybe?

**Comment by harisrozak** [comment] 2021-12-13 03:06
@edufolios-matt Just in case you haven't find the solution, you can try to create a new array to store the term ids instead of using the `selected_term_ids`. Please check my gist here: https://gist.github.com/harisrozak/64764a84cd4b3bd7845084572850ba78

**Comment by edufolios-matt** [comment] 2021-12-13 03:09
@harisrozak thanks for that. Are you thinking that is so the array will be seen as totally new data and saved differently?

**Comment by harisrozak** [comment] 2021-12-13 03:19
@edufolios-matt Yes, I don't know either why it's not working when it using the `selected_term_ids`, maybe it's not an array, or I did wrong with the adding the term_id into it.

**Comment by edufolios-matt** [comment] 2021-12-13 03:25
@harisrozak - you legend!! That worked!!
