### ISSUE TITLE
Keyboard shortcuts to create/move a block above or below

### ISSUE THREAD

**Issue by lcswillems** [WordPress/gutenberg#12490] opened 2018-12-01 00:53 UTC
**Is your feature request related to a problem? Please describe.**
There is no keyboard shortcut to create/move a block above or below the focused block. This is not really convenient.

**Describe the solution you'd like**
We could take inspiration from Jupyter Lab. For example `a` to create a block above, `b` to create a block below. In Jupyter Lab, we can create our own keyboard shortcut to move block above / below.

**Comment by swissspidy** [comment] 2018-12-01 13:00
Uhm, there _are_ shortcuts to create blocks before or after the current block and they work really well in my tests.

<img width="599" alt="screenshot 2018-12-01 at 13 58 16" src="https://user-images.githubusercontent.com/841956/49328443-620e1600-f571-11e8-9003-cfd548630e4c.png">

Make sure you check out the help modal that lists all available keyboard shortcuts:

<img width="371" alt="screenshot 2018-12-01 at 13 59 21" src="https://user-images.githubusercontent.com/841956/49328444-63d7d980-f571-11e8-99c4-638424ba9b4f.png">

**Comment by lcswillems** [comment] 2018-12-02 17:49
That's true, but there are no such shortcuts to move up or down a block.

**Comment by swissspidy** [comment] 2018-12-03 08:46
Keyboard shortcuts to move blocks are being discussed in #10455.

I'm therefore closing this one as a duplicate of #10455.

**Closed by swissspidy** 2018-12-03 08:46 UTC
Labels: [Type] Help Request
