### ISSUE TITLE
JS Error in Latest Posts block grid view

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#4276] opened 2018-01-04 03:08 UTC
## Issue Overview

This occurs in the current build of `master` (@ 7557026). When in grid view of the "Latest Posts" block, using the slider of the `RangeControl` causes a JS error and crashes the block.

## Steps to Reproduce (for bugs)

1. Add a Latest Posts block
2. Select "grid" view
3. Change the number of posts
4. `LatestPostsBlock.render()` throws an error, `Cannot read property 'length' of undefined`

## Expected Behavior

The number of posts would change, as happens successfully in the list view.

## Current Behavior

The block crashes due to a JS error.

## Screenshots / Video

![latest-posts-error](https://user-images.githubusercontent.com/465154/34548835-4cb768e6-f0d2-11e7-9450-fe983fc7591e.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment] 2018-01-10 10:36
Closing, can't reproduce anymore

**Closed by youknowriad** 2018-01-10 10:36 UTC
