### ISSUE TITLE
Intermittent e2e test failures

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6956] opened 2018-05-25 14:11 UTC
The e2e test suite currently fails intermittently. Sometimes the test failure looks like this:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/36432/40548864-c4fc4966-5fea-11e8-8017-de2646ef3965.png">

I have no idea on the cause of this, but it's getting in the way of other unrelated development.

**Comment by noisysocks** [comment] 2018-05-28 03:04
I spotted a few mistakes to do with `async` functions in our E2E tests which could be contributing to this problem. https://github.com/WordPress/gutenberg/pull/6971 attempts to fix some of them.

**Comment by danielbachhuber** [comment] 2018-05-29 15:04
Comment from @youknowriad to address (https://github.com/WordPress/gutenberg/pull/6995#discussion_r191330344):

> I'm pretty sure that's not the only place in our tests where we open the inserter, we should probably be consistent.
> Do you think we should factorize that in a `insertBlock( 'core' )` utility?
> And also, can we add a comment explaining why this is necessary? Is there an API request or something?

**Comment by aduth** [comment] 2018-06-20 20:59
There's a new suspect from the `change-detection.test.js` suite:

```
✕ Should prompt if changes made while save is in-flight (1747ms)
```

Have seen separately on both #7419 and #7220 .

As author of the offending test, I shall plan to investigate.

**Comment by gziolo** [comment] 2018-06-21 07:38
Moving to 3.2. This is an issue with tests rather than with actual code.

**Comment by youknowriad** [comment] 2018-06-27 12:34
I'm also starting to see this failure from time to time. 

<img width="1256" alt="screen shot 2018-06-27 at 13 33 47" src="https://user-images.githubusercontent.com/272444/41974091-d4f43660-7a0e-11e8-80b0-f6ca930000d1.png">

**Comment by aduth** [comment] 2018-06-27 12:49
FYI #7493 will resolve at least two of the intermittent failing tests I've seen.

**Comment by danielbachhuber** [comment] 2018-06-27 17:58
I just saw this:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/36432/41991036-00d9fc26-79f9-11e8-8fee-92e7e785026a.png">

On #7322, which was just rebased against master.

**Comment by aduth** [comment] 2018-06-28 12:42
Based on the error message, I'm inclined to think it should be resolved with #7544 . Let's continue reopening if it persists, though.

**Comment by aduth** [comment] 2018-06-28 15:38
A change was snuck into #6959 (689d79d5bb5a6a13c77d6100aa2edd98fd21013d) to run end-to-end tests in serial order (not parallel) which could help make the tests more deterministic and eliminate any chance of tests affecting one another (since, for example, some tests activate plugins which could have an impact site-wide if tests are run in parallel).

**Comment by aduth** [comment] 2018-07-06 13:10
I've been seeing this one a lot lately: https://github.com/WordPress/gutenberg/issues/6956#issuecomment-400775081

**Comment by aduth** [comment] 2018-07-09 20:36
Starting to see a new one.

```
FAIL test/e2e/specs/preview.test.js
  ● Preview › Should open a preview window for a new post
    Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
      
      at Promise (node_modules/puppeteer/lib/Connection.js:198:56)
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:197:12)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:71:75)
      at ExecutionContext.evaluate (node_modules/puppeteer/lib/ExecutionContext.js:46:31)
      at Frame.evaluate (node_modules/puppeteer/lib/FrameManager.js:299:20)
```

Example: #7841 https://travis-ci.org/WordPress/gutenberg/jobs/401939944

**Comment by talldan** [comment] 2018-07-24 07:52
I'm also seeing `block-icons.test.js` fail locally consistently.

Seems to be due to the wrong block being focused during the test (the inserted blocks seem to have a nested paragraph block and the paragraph block end up being focused):
https://github.com/WordPress/gutenberg/blob/master/test/e2e/specs/block-icons.test.js#L119-L122

Had a quick look but couldn't figure out a workaround.

**Comment by gziolo** [comment] 2018-07-24 08:36
@talldan, can you check PR from @jorgefilipecosta  #7896 and verify if that resolves this issue? It has been opened for some time but we didn't come up to the consensus if it resolves the issue or hides it deeper :)

**Comment by aduth** [comment] 2018-08-13 14:05
https://github.com/WordPress/gutenberg/pull/8707#issuecomment-411714831

**Comment by gziolo** [comment] 2018-08-14 04:47
@aduth - there is an open issue for it logged for it. Actually, there are 2 open issues with e2e test failures which happen from time to time:

- `test/e2e/specs/writing-flow.test.js` (#8712)
- `test/e2e/specs/undo.js` (https://github.com/WordPress/gutenberg/issues/5685#issuecomment-409172411) - it's a part of a bigger issue which isn't easy to reproduce

**Comment by aduth** [comment] 2018-08-14 18:15
Ok, #8712 appears to be the same as in https://github.com/WordPress/gutenberg/pull/8707#issuecomment-411714831 so let's close in favor of that one.

**Closed by aduth** 2018-08-14 18:15 UTC
Labels: Automated Testing, Priority High
