### ISSUE TITLE
In 5.8 RC2 on new block widgets screen JS error appears for the text widget

### ISSUE THREAD

**Issue by exstheme** [WordPress/gutenberg#33356] opened 2021-07-12 11:11 UTC
## Description
In 5.8 RC2 on new block widgets screen JS error appears for the text widget:
Error message:

> The "text" block was affected by errors and may not function properly. Check the developer tools for more details.

Console error:
```
widgets.js?ver=5ee29b11357eb747d08e2a33c8307fa7:763 TypeError: wp.editor.initialize is not a function
    at buildEditor (text-widgets.js?ver=5.8-RC2:265)
    at n.initializeEditor (text-widgets.js?ver=5.8-RC2:359)
    at renderWhenAnimationDone (text-widgets.js?ver=5.8-RC2:434)
    at HTMLDocument.handleWidgetAdded (text-widgets.js?ver=5.8-RC2:437)
    at HTMLDocument.dispatch (jquery.js?ver=3.5.1:5430)
    at HTMLDocument.elemData.handle (jquery.js?ver=3.5.1:5234)
    at Object.trigger (jquery.js?ver=3.5.1:8719)
    at HTMLDocument.<anonymous> (jquery.js?ver=3.5.1:8797)
    at Function.each (jquery.js?ver=3.5.1:385)
    at jQuery.fn.init.each (jquery.js?ver=3.5.1:207)
```

## Step-by-step reproduction instructions

1. Install starter content on version 5.7
2. Update WordPress to 5.8 RC2 with beta tester plugin
3. Go to Appearance -> Widgets

## Expected behaviour
Working without errors.

## Actual behaviour
Error message and console error appears.

## Screenshots or screen recording (optional)

[https://i.imgur.com/TjJfIqL.png](https://i.imgur.com/TjJfIqL.png)

## WordPress information
- WordPress version:  5.8 RC2
- Gutenberg version:  Not installed - Default used
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  No

## Device information
- Device:  Desktop
- Operating system:  Linux Mint 20
- Browser:  Chromium v90

**Comment by kevin940726** [comment] 2021-07-20 07:52
It's likely a duplicate of https://github.com/WordPress/gutenberg/issues/33203 and should already been fixed.

**Closed as completed by kevin940726** 2021-07-20 07:52 UTC
Labels: [Status] Duplicate
