### ISSUE TITLE
Full site editing: Unable to exit fullscreen mode

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#37118] opened 2021-12-04 00:25 UTC
### Description

In full site editing screens, I am unable to see or access the admin bar. The markup is rendered on the page but is covered by the editor. In post editor, it possible to exit full screening editing to access the admin bar and admin navigation, but this is not possible in full site editing. 

### Step-by-step reproduction instructions

1. Go to site editor. 
2. See no admin bar. 

### Settings in editor ( Fullscreen edit mode button )

<img width="338" alt="Screenshot 2021-12-04 at 00 12 42" src="https://user-images.githubusercontent.com/237508/144688868-6cf67d84-11d9-455f-a7f4-9201f7658d5a.png">

### Settings in site editor ( with fullscreen edit mode button )

<img width="313" alt="Screenshot 2021-12-04 at 00 16 23" src="https://user-images.githubusercontent.com/237508/144688900-9134344a-e2ca-445c-bdd2-d366becaa07d.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by spacedmonkey** [comment] 2021-12-04 00:31
I have done mockup of what is would look like. 
<img width="1904" alt="Screenshot 2021-12-04 at 00 30 27" src="https://user-images.githubusercontent.com/237508/144689236-a0780b30-e5f0-44cb-8454-b20c0be49bf0.png">

**Comment by christianmagill** [comment] 2021-12-04 02:01
I guess the problem is the more things you have surrounding the content, the less accurately media queries are represented.

**Comment by ntsekouras** [comment] 2021-12-07 16:26
I have a feeling that this might be intended, but I'm not sure. @jameskoster or @jasmussen maybe, might  know if this is a design decision about the site editor..

**Comment by jameskoster** [comment] 2021-12-07 17:45
It is intentional, due mostly to the Site Editor having a dedicated navigation area. Outside of full-screen mode things get... interesting:

https://user-images.githubusercontent.com/846565/145079782-478ed242-8650-4cda-8a15-c588d051a693.mp4

**Comment by spacedmonkey** [comment] 2021-12-07 21:41
@jameskoster I don't see the issue with the screencast you shared? Seems fine to me. Specially if you are a larger screen.

**Comment by annezazu** [comment] 2024-02-13 00:49
Closing this out as it's an intentional design decision.

**Closed as not planned by annezazu** 2024-02-13 00:49 UTC
Labels: [Type] Bug, [Feature] Site Editor
