### ISSUE TITLE
Heading shortcut broken in 6.2 in Firefox

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#49741] opened 2023-04-12 04:00 UTC
### Description

In WordPress < 6.2, typing ## followed by a space followed by some text results in that text becoming a heading block.

In Firefox in WordPress 6.2, the transformation does not occur until after you type another character after the space, and eats that character, preventing it from showing up.

Have tested and it works in the same browser in WordPress 6.1, as well as in Chrome in WordPress 6.2, so it's some connection between Firefox and 6.2. (Have also tested with all extensions disabled).

### Step-by-step reproduction instructions

Type `## Heading` into the editor.

In WordPress < 6.2 with Firefox, or 6.2 with Chrome, you will see **Heading**.

In WordPress 6.2 with Firefox, you will see **eading**.

### Environment info

WordPress 6.2, no Gutenberg plugin, all themes
Firefox 112.0 (64-bit), desktop Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2023-04-12 04:48
Thanks for contributing, @smerriman!

The issue was fixed in Gutenberg 15.3, and I cannot reproduce it with the latest stable version - 15.5.

I will mark #48210 to be backported into a minor release.

**Closed as completed by Mamaduka** 2023-04-12 04:48 UTC
Labels: [Type] Bug, [Block] Heading
