### ISSUE TITLE
Editor: Changes made in FSE aren't reflected in the Block Editor when editing Posts/Pages

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#39839] opened 2022-03-29 08:20 UTC
### Description

I made a simple change in the Full Site Editor, within the Page template. I simply changed the text color and background color for the Post Title block.

![fse-page-template](https://user-images.githubusercontent.com/2078245/160564196-8407194a-7efc-485d-828c-1d24ecefc8df.png)

When I go out of the FSE and edit a Page using Gutenberg, those changes aren't reflected.

<img width="1439" alt="fse-changes not-reflected-in-gutenberg" src="https://user-images.githubusercontent.com/2078245/160564462-e93cfbca-465e-4a7f-a580-eeaa9bd4b634.png">

If I make a change to a template, I would expect it to be reflected when I edit a Post/Page that is using that template.

As a second test, I also tried adding a separator block beneath the Post Title block and that wasn't reflected either.

### Step-by-step reproduction instructions

Use Twenty Twenty-Two theme
Enter Editor (Appearance > Editor)
Select Page template from Templates menu option
Change Text and Background colour of the Post Title block
Add Separator block beneath Post Title Block
Save Changes
Navigate back to Dashboard and Pages menu option
Edit existing Page
Ensure Page is using Default Page template
View previous changes not being reflected in editor

### Environment info

macOS Monterey 12.2.1
Firefox 98.0.1
WP 5.9.2
Twenty Twenty-Two
Core only, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment] 2022-09-28 11:50
This is still the case, the changes you would have made can be seen on the front end but not while you are editing the page. 

Not sure if FSE supports changing colors for pages in the backend at the moment. 

WordPress 6.0.1 
Gutenberg 14.1.1

**Comment by youknowriad** [comment] 2023-02-24 13:27
If I'm understanding properly. You're expecting the changes made to a "page" template to show up in the regular post editor. 

That is not how it's supposed to work. The post editor "focus" on the title and content of the page but don't render the "template" at all unless you click the "edit" link in the sidebar of the post editor to enter "template mode".

I'm going to close this as working as intended. But let me know if I missed anything.

**Closed as completed by youknowriad** 2023-02-24 13:27 UTC
Labels: [Type] Bug, [Feature] Site Editor, [Feature] Template Editing Mode

**Comment by maddisondesigns** [comment] 2023-02-27 08:39
> That is not how it's supposed to work. The post editor "focus" on the title and content of the page but don't render the "template" at all unless you click the "edit" link in the sidebar of the post editor to enter "template mode".

@youknowriad I honestly have no idea what you're referring to here. I don't know if it's because you're not understanding what my original issue was referring to, or if I just don't understand what you're trying to say.

If I make changes to a template such as the standard "Page" template (like I mentioned above), then yes, I would expect those changes to be reflected when I use the standard Block Editor/Gutenberg interface when editing the content of my pages.

> The post editor "focus" on the title and content of the page but don't render the "template" at all unless you click the "edit" link in the sidebar of the post editor to enter "template mode".

Where's this "Edit" link that you're referring to that switches you to "template mode"? This is the standard Block Editor screen (below). I can't see any "Edit" button or anything that is supposed to switch you to something called "template mode".

<img width="1919" alt="screenshot_1149" src="https://user-images.githubusercontent.com/2078245/221510909-6390d81e-7888-4253-8821-f351c1d0f874.png">

Whenever suggestions have been made in the past to improve the UI/UX of the editor, the typical response is no, with the main reason being because you want the editor to better reflect what the end user sees in the browser (even though editing content and viewing the end result are two completely different experiences). But now you're saying that changes you make to a template wont be reflected in the standard editor screens. There is zero consistency with this editor, across all the various interfaces you've created, from the standard Block Editor interface, to the widgets screen, and now to these (Full Site) Editor screens. It's no wonder this editor continues to provide a horrible UX for the end user.

**Comment by maddisondesigns** [comment] 2023-02-27 08:45
Just as another sidenote, when I switch to the _Twenty Twenty-One_ theme, the editor shows the background colour used within the templates. So, why does the editor show like this, reflecting how the template looks, but it doesn't show other changes that you make within the FSE? Again, zero consistency!

<img width="1806" alt="screenshot_1150" src="https://user-images.githubusercontent.com/2078245/221515137-2e5022b4-e841-48da-820c-cb62e0882d38.png">

**Comment by youknowriad** [comment] 2023-02-27 08:54
Yes, sorry that was not clear enough.

Here's the "edit template" link. It seems the design for this part changed a bit.

<img width="300" alt="Screenshot 2023-02-27 at 9 51 05 AM" src="https://user-images.githubusercontent.com/272444/221517052-bc6cf13f-2c16-4844-ab2e-b5e8e6a9b96f.png">

---
Now for the behavior:

 - The post editor (when you edit a post or page from the posts/pages screens) doesn't load the templates at all initially (unless you click edit template). Meaning any change to the templates associated with given posts/pages are not visible there.
 - For the background color, it's different because it's not a change in the template, it's a change in "editor styles".

---
I understand that you don't like it and we can consider iterations, like showing the "template mode" by default and things like that. This has been discussed several times and even showing "template mode" by default is confusing as well for some flows, like writing posts... So there's a balance to be found, there's no silver bullet.

**Comment by maddisondesigns** [comment] 2023-02-27 09:39
Thanks for explaining that further.

Is that "Edit Template" link something that is being introduced in WP 6.2, as it's not in WP 6.1.1? 

<img width="413" alt="screenshot_1151" src="https://user-images.githubusercontent.com/2078245/221523480-1c133b68-b7a9-44a5-9b64-2b2c6208e54d.png">

Is that icon at the top of the panel the "switch to template mode" option you were referring to? I presume this means it loads the template in the standard editor screen?

>The post editor doesn't load the templates at all initially
>For the background color, it's different because it's not a change in the template

This is going to be super confusing for the end user, especially those who aren't familiar with the intricacies of theme development. The average user, who simply wants to use the (Full Site) Editor to tweak how their Headings display (as an example), is not going to understand why their changes aren't reflected when they go back to editing their content. Even as a developer, having a completely separate option to "switch to template mode" is just needlessly confusing.

It would make more sense to completely remove this, and just fix the various preview modes within the editor, so that they actually load the template and display the screen just like you see in the front-end. The existing preview modes that don't display the page exactly how it appears in the browser on the front-end, makes them absolutely pointless. I brought up [this issue](https://github.com/WordPress/gutenberg/issues/34569) almost two years ago.

**Comment by youknowriad** [comment] 2023-02-27 09:55
> Is that "Edit Template" link something that is being introduced in WP 6.2, as it's not in WP 6.1.1?

No, that's there for 3 WP releases I think (or more). The link is only available for block templates and some themes can disable it as well. 

> Is that icon at the top of the panel the "switch to template mode" option you were referring to? I presume this means it loads the template in the standard editor screen?

yes "edit template" = "switch to template mode" link and yes, you're correct it loads the template with the post/page within it in the standard editor. That feature is in WP even before FSE.

**Comment by maddisondesigns** [comment] 2023-02-27 15:59
Thanks for explaining that. I forgot to switch back to the default (Twenty Twenty-Three) Block theme earlier, so now that I have, I can see those extra options in that Template popup.

Clicking on the Edit Template link gives you one super confusing editor screen. This is the very first time I've seen this edit screen. I didn't even know it existed. It's like some sort of hybrid Block Editor/FS Editor screen, where you can edit content as well as the different template parts. If you completely removed the standard Block Editor AND the FS Editor, and just had this "hybrid" type of edit screen, I can see this making sense. The fact that there's now all these different types of editors though, and every one looks and works slightly different, just makes for a super confusing editing experience.

One of the reasons I fell in love with WordPress, 17+ years ago, was it's ease of use over all the other content management systems out there. And for a good part of those 17+ years, this remained the case, even with all it's improvements. I completely understand that WordPress needed to change over that time, but this editor has taking it in a complete 180º turn. It's no longer the user friendly CMS that it used to be (and I'm not even gonna mention how increasingly difficult you've made the development side of things). If I was a brand new user and this was the editor I was presented with, to create/update my site, there's absolutely no way I would continue to use WP. Gutenberg has completely broken the "ease of use" experience that made WP so popular.
