### ISSUE TITLE
Editor List View: User naming of top level block labels

### ISSUE THREAD

**Issue by eirichmond** [WordPress/gutenberg#50729] opened 2023-05-18 08:08 UTC
## What problem does this address?
As multiple blocks are stacked in the top level list view the same naming convention is used eg Group, Spacer, Cover, Row, etc; it becomes more cumbersome to isolate particular sections from a user point of view, especially when the user stacks multiple blocks with the same name, eg Group, Group, Group, Cover, Cover, Cover, Group, Group, Cover, Cover, Cover, and so on...

These blocks might be particular types of sections of a page to the user, for example Features and Benefits, Call to action, Mood Image, 4 x Image gallery, Social Feed, Product Feature, Buy Now Call to action etc.

## What is your proposed solution?
Allow the user to rename the top level list items label to help them locate sections more visually and easily during the editing experience especially when the stacks grow larger in size.

### _Current List View_
![current-list-view](https://github.com/WordPress/gutenberg/assets/525490/1601d352-abca-4a55-861c-d03ef7281e14)

### _Proposed List View - after user label edits_
![proposed-list-view](https://github.com/WordPress/gutenberg/assets/525490/eede5ccf-c08c-41d7-ac18-4556c76fd689)

**Comment by Mamaduka** [comment] 2023-05-18 10:57
Thanks for contributing, @eirichmond!

This is a duplicate of #33583; there's already an in-progress PR for the enhancement. See #42605.

**Closed as not planned by Mamaduka** 2023-05-18 10:57 UTC
Labels: [Status] Duplicate, [Feature] List View
