### ISSUE TITLE
Changes not saving in FSE

### ISSUE THREAD

**Issue by sabuz** [WordPress/gutenberg#35664] opened 2021-10-15 09:05 UTC
### Description

When you change something in FSE e.g. add custom class, toggle layout settings etc. and click save, it does not save the changes. I'm facing the issue after updating to 11.5.0. The issue still exists in 11.7.0. If you switch back to 11.4.1 it works as expected.

### Step-by-step reproduction instructions

1. Open a template in FSE
2. Select Header/Footer
3. Add any custom class or toggle layout settings.
4. Save the changes and refresh the page.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7956101/137462136-2e6cf24c-0e7d-45a0-b678-0934cc467a54.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2021-10-16 07:00
Hi
Please include:
Which editor (block editor, template editor, site editor)?
And which block? Is it a specific block or are no changes saving at all?

**Comment by carolinan** [comment] 2021-10-16 07:03
For template part changes to save you need to save the **template**, not the template part.
To save changes to content **inside** template parts, you need to save the template part.
I agree this is very confusing.
Duplicate of https://github.com/WordPress/gutenberg/issues/30732?

**Comment by sabuz** [comment] 2021-10-16 10:31
Got you @carolinan. I included a footer using footer block. Prior to 11.5.0, saving changes were effected to my index template which worked as expected. Since 11.5.0 saving changes of footer block are effecting to footer template part. Which is not expected.

**Comment by talldan** [comment] 2021-10-21 07:24
I think I've just seen this bug too. A few people were flagging it on my PR, and I was concerned it was something I'd done, but I think it's also in `trunk`. It has been experienced in the site editor, but is more easily seen in the post editor by following the steps I mention here - https://github.com/WordPress/gutenberg/pull/35746#issuecomment-948329110

**Comment by talldan** [comment] 2021-10-21 09:15
Here's an easy way to repro:
1. Open the site editor
2. Select the Header from List View
3. Change colors from the sidebar
4. Click save. Observe that the sidebar only shows changes to the Header template part
5. Save those changes
6. Reload, observe changes are lost.

I did a git bisect and managed to track the issue down to #34241.

**Closed as completed** 2021-10-29 07:32 UTC
Labels: [Status] In Progress, [Type] Regression, [Block] Template Part
