### ISSUE TITLE
Post publish notification message design issue

### ISSUE THREAD

**Issue by viralsampat90** [WordPress/gutenberg#1762] opened 2017-07-06 12:41 UTC
Hello All,

Today, I have checked the "Gutenberg" plugin and created two or three posts using this plugin. During the creation of the post, I have found one design issue on post published notification message. The notification is messed up when I am scrolling the page.

Please refer mine below attachment.

![guternberg_notification_issue](https://user-images.githubusercontent.com/29949460/27911365-747b191c-6276-11e7-8779-dce4af5bdbaf.gif)

**Comment by hedgefield** [comment] 2017-07-06 15:02
Duplicate of #1604.

**Comment by youknowriad** [comment] 2017-07-06 21:44
The position issue is fixed

**Closed by youknowriad** 2017-07-06 21:44 UTC
