### ISSUE TITLE
Blog Posts block: allow full post display

### ISSUE THREAD

**Issue by tanjoymor** [WordPress/gutenberg#20019] opened 2020-02-03 23:35 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is the option to turn Excerpt on or off for the Blog Posts block, but no option to display the full post. Essentially only allowing the options of Title only or Title and Excerpt.

**Describe the solution you'd like**
I'd like to see this block offer the choices to turn each of these on or off:
Title
Excerpt
Full Post

**Describe alternatives you've considered**
The Latest Posts block provides the option of Excerpt or Full post, but no option for Title only. This provides for an alternative to the Blog Posts block when someone wants to display the full post - but it's not very friendly if they just want to display one specific full post (have to set a special category and limit post count).

This specific scenario was requested by a user: #18409697-hc

**Comment by draganescu** [comment] 2020-02-05 08:35
Howdy @tanjoymor ! 

The current iteration of the `LatestPosts` block includes a toggle named "Post Content" which does exactly this:

- Post Content **off** -> _Title Only_ list of posts
- Post Content **on** + Excerpt **checked** -> _Title and excerpt_ list of posts
- Post Content **on** + Full post **checked** -> _Title and full post body_ list of posts

<img width="864" alt="Screenshot 2020-02-05 at 10 31 47" src="https://user-images.githubusercontent.com/107534/73824405-c7f3ce80-4802-11ea-9aaa-5f8b0e35e754.png">

It might be the user who requested the scenario has an older version of WordPress, or that some of the  features described above are only in the plugin version of Gutenberg and are about to be included in the next release of WordPress.

In any case, since the functionality exists I will close this issue.

**Closed by draganescu** 2020-02-05 08:35 UTC

**Comment by mmwb** [comment] 2020-03-07 20:27
Get the impression that an **excerpt** in a latest-posts-block is different from an **excerpt** of a post on a blog page. I'm asking because shortcode tags (both begin and end tag) are removed/stripped from an excerpt of a post as used on a blog page, even including the text in between! 

Editor:
<img width="761" alt="Schermafbeelding 2020-03-07 om 21 13 55" src="https://user-images.githubusercontent.com/46068706/76151749-a1061200-60b8-11ea-9bf5-5551422149c3.png">

Excerpt of post on blog page in frontend:
<img width="685" alt="ScrPrt excerpt twentytwenty 2020-03-06" src="https://user-images.githubusercontent.com/46068706/76151703-fd1c6680-60b7-11ea-8b3f-996cde7321b6.png">

But this is not the case in a latest-posts-block. Then the excerpt looks like the full content

<img width="636" alt="ScrPrt Full Text twentytwenty 2020-03-06" src="https://user-images.githubusercontent.com/46068706/76151715-276e2400-60b8-11ea-86de-758f6af5f93b.png">

where only style attributes are stripped, but not html and shortcode tags.

The shortcodes in this example are created by 2 wiki lookup plugins. Is stripping of the tags ( [wiki] & [/wiki] ) including the content in between caused by the plugin or by WP/Gutenberg to your knowing?
Thanks in advance for your advise.

**Comment by mmwb** [comment] 2020-03-08 13:34
Created new issue  #20702
