### ISSUE TITLE
List block goes quirky when saving changes

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#13383] opened 2019-01-20 15:04 UTC
**Describe the bug**
List block goes quirky when saving changes. When you save a page with a list block, the block element get extra space in between them. Clicking the list box reverses the changes (luckily)

**To Reproduce**
1. Create a list block on a page
2. Click on the Save changes button
3. List block's items space out
4. Click on box, spacing disappears

**Expected behavior**
List block should not space out

**Loom video**
https://www.useloom.com/share/a66c0f3c37b4428d80f2c16c57ec02ca

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71.0.3578.98

**Additional context**
WP version 5.0.3

**Comment by swissspidy** [comment] 2019-01-21 10:37
Duplicate of #13183.

**Closed by swissspidy** 2019-01-21 10:37 UTC
Labels: [Block] List, [Status] Duplicate
