### ISSUE TITLE
[Full Site Editing] Editor sticking & white space problems

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24009] opened 2020-07-16 20:23 UTC
**Describe the bug**

While testing Full Site Editing, I started experiencing strange sticking behavior combined with white space suddenly appearing after adding in a Block Pattern at the bottom of the interface. cc @ockham 

**To reproduce**

I don't quite know what to write for this beyond enabling Full Site Editing under Experiments 😓 I just tried adding patterns, different blocks, and scrolling around.

**Expected behavior**

The editor wouldn't stick or cause white space to appear. There seems to be some sort of issue with the scrolling functionality too.  The white space might somehow be related to the scrolling for the inserter overall conflicting with the overall scrollbar for the editor. I'm not sure!

**Screenshots**
Video 1: https://cloudup.com/cwnpAzUjWWh
Video 2 (replicating from scratch): https://cloudup.com/cQNrR6mvV8I

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by Clorith** [comment] 2021-06-25 17:44
I'm able to replicate this behavior, in the global block inserter when making a search, it appears to add about 3 pages worth of whitespace below the block editor, and it remains until the block inserter on the side is closed.

The amount of whitespace appears related to how many rows of patterns are returned, looking up `gallery` for example results in fewer results, and less whitespace added)

Currently testing with WordPress 5.8-beta4 and no Gutenberg plugin enabled.

![overflow](https://user-images.githubusercontent.com/468735/123464795-95ac6200-d5ed-11eb-8871-c35ba3d1b586.gif)

**Comment by circlecube** [comment] 2021-06-25 22:06
I can replicate this behavior as well. It seems to be the changing height of the `.interface-interface-skeleton__secondary-sidebar` messing with the flexbox layout on the container `.interface-skeleton__body`.

I'm not sure what else it would mess with but for tinkering and debugging thus far it looks like if adding a css rule of  `overflow-y: hidden;` to `.interface-skeleton__body` fixes this issue. I don't think this element should be scrolling anyways, since any content would be within a child div like sidebar or content.

**Comment by jeyip** [comment] 2022-06-22 16:31
I can no longer replicate this issue as described in [this comment](https://github.com/WordPress/gutenberg/issues/24009#issuecomment-868730657) or when trying to replicate testing instructions in the PR description.

I tested on Gutenberg v13.5 and on the current version of WordPress v6.1-alpha-53519 without Gutenberg installed. Is anyone else still having trouble?

I'm going to close this for now but feel free to reopen.

**Closed** 2022-06-22 16:34 UTC
Labels: [Type] Bug, [Feature] Writing Flow, [Feature] Full Site Editing

**Comment by jack-h2ml** [comment] 2023-01-29 14:07
@jeyip I can confirm that this is issue happening for me, stable release of 6.1.1, both with and without the Gutenberg plugin installed, on the 2022, 2023, and custom FSE themes, no other plugins installed. 

Perhaps related, I have also noticed that searching in the block inserter results in a large number of 404 errors being generated, seemingly related to the Featured Patterns - these all seem to point to instances of Featured Patterns utilising assets with src's either pointing to the pattern dev's local testing site or to url's which are no longer publicly accessible.
