### ISSUE TITLE
Classic Block - Toolbar remains open

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#6889] opened 2018-05-22 09:42 UTC
After leaving any block (clicking in another block), the toolbar of the "no longer in focus" block is disabled / not shown.
After leaving "Classic Block" the toolbar of classic block remains open (and is consuming space)

**Comment by danielbachhuber** [comment] 2018-05-23 12:47
Hi @burnuser,

I believe this behavior is by design. I've flagged this issue `Needs Design Feedback` to verify.

**Comment by karmatosed** [comment] 2018-05-29 19:41
This only happens in the classic editor block and is done on purpose to make it as close to the classic editing experience. For now closing as the reason makes sense in this single case.

**Closed by karmatosed** 2018-05-29 19:41 UTC
Labels: Needs Design Feedback
