### ISSUE TITLE
Ugly double scrollbar in Add Block popup

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#24529] opened 2020-08-12 23:41 UTC
**Describe the bug**
In Firefox 79 (at least, likely others), on a commonly-used 1366x768 size screen, the Add Block interface often displays both horizontal and vertical scrollbars, which are very ugly and make it hard to use.

**To reproduce**
Click on Add Page in a new install of WordPress with the above specs, then click on the black (inline) add block button. If the popup does not fully fit on the screen (which it doesn't when you first try to add a block, and many other times), if will result in the attached.

**Screenshots**
![image](https://user-images.githubusercontent.com/6667004/90078632-9cc1dd00-dd59-11ea-8717-ea9ae4111732.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 79

**Comment by getdave** [comment] 2020-09-07 10:32
Confirmed. Tested this with WP 5.5 with no Gutenberg Plugin and saw the issue when using Firefox 79 at that specific screen size.

![Screen Shot 2020-09-07 at 11 31 18](https://user-images.githubusercontent.com/444434/92378475-c3c3c280-f0fd-11ea-9a31-cbd55dbf5994.png)

**Comment by skorasaurus** [comment] 2021-02-01 19:30
Closing since this appears to been fixed in https://github.com/WordPress/gutenberg/pull/25110

**Closed by skorasaurus** 2021-02-01 19:30 UTC
Labels: [Feature] Inserter
