### ISSUE TITLE
Cover Block with solid background has always black background in backend

### ISSUE THREAD

**Issue by davsev** [WordPress/gutenberg#28771] opened 2021-02-05 08:50 UTC
Hi, very similar to [issue 21709](https://github.com/WordPress/gutenberg/issues/21709) the cover blocks in the backend get a black background color instead of the assigned color.
in frontend everything looks o.k
if I choose a different background color and I do ctrl+z I will see the real color, but if I refresh the page the color returns to be black.

This class takes over all the blocks:
![image](https://user-images.githubusercontent.com/7754017/107011040-c9eac780-679f-11eb-9b59-b55a6b8f1d30.png)

if I clock the block properties I see that the background color wasn't changed.
![image](https://user-images.githubusercontent.com/7754017/107011176-fb639300-679f-11eb-8181-a062d5981e7a.png)

**Comment by gwwar** [comment] 2021-02-05 18:58
@davsev thanks for the report! I can see the black background when saving the cover placeholder, since https://github.com/WordPress/gutenberg/issues/10854 hasn't been resolved yet.

<img width="829" alt="Screen Shot 2021-02-05 at 10 56 16 AM" src="https://user-images.githubusercontent.com/1270189/107076900-f6531380-67a0-11eb-9d02-e7a00688d400.png">

I'm not having luck reproducing the false color in the edit view, would it be possible to add a quick video and noting which WP/gutenberg version you can reproduce this in?

**Comment by stokesman** [comment] 2021-02-08 17:34
This is likely the same as #28557 (plus a few other similar issues filed recently) and #28565 fixed. That PR has been included in the 9.9 release so the updated plugin could be tried @davsev.

**Comment by Mamaduka** [comment] 2021-05-25 05:43
Hello, @davsev

I'm no longer able to reproduce this issue with WP 5.7.2 or the latest version of the Gutenberg plugin.

I'm going to close this issue. Feel free to re-open it if you encounter the same issue in the future.

**Closed by Mamaduka** 2021-05-25 05:43 UTC
Labels: Needs Testing
