### ISSUE TITLE
Adding hover descriptions to footnotes

### ISSUE THREAD

**Issue by asafm7** [WordPress/gutenberg#55684] opened 2023-10-29 15:40 UTC
![image](https://github.com/WordPress/gutenberg/assets/14274769/d4f65832-973c-4cbb-966a-c1fe45470ebb)

Example from https://www.verywellhealth.com/how-soon-after-covid-can-you-get-vaccinated-8351034

The idea is to facilitate continuous reading by providing easy access to footnote content without disrupting the flow of the main text.

An elaborate implementation can look like the example above.

A basic and simple implementation can use the `title` attribute.

In fact, if the text of the footnote was added to the `title` attribute of the footnote itself, it would be very easy to copy it into the `title` attribute of the link-to-footnote in the body of the text using `WP_HTML_Tag_Processor `.

**Comment by Mamaduka** [comment] 2023-10-30 05:03
Thanks for opening the issue, @asafm7. I believe this is a duplicate of #54089. Feel free to add your comment there.

**Closed as not planned** 2023-10-30 05:03 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Block] Footnotes
