### ISSUE TITLE
Nasty margin on gallery block

### ISSUE THREAD

**Issue by hhjung2013** [WordPress/gutenberg#18852] opened 2019-12-01 14:25 UTC
The markup of the gallery block seemed to have changed on one the last releases. That causes the css rule margin-left: 0 in front-end.css to no longer applies which gives my galleries a left margin of 40px defined in my theme. Of course I can easily overwerite this rule but I was wondering if this behaviour is intended.

**Comment by epiqueras** [comment] 2020-01-31 20:25
I don't see any changes like that.

Can you pinpoint the specific markup change?

**Comment by talldan** [comment] 2020-02-04 05:18
@hhjung2013 Any update on this issue?

**Comment by hhjung2013** [comment] 2020-02-04 13:18
I don't remember the exact changes, but some classes of the <figure> and the <ul> elements must have changed:

```
<figure class="wp-block-gallery">
<ul class="blocks-gallery-grid">
...
</ul>
</figure>
```

**Comment by talldan** [comment] 2020-02-05 02:02
@hhjung2013 I think your problem is the same issue as this one - https://github.com/WordPress/gutenberg/issues/17693

The good news is, it looks like this has now been fixed by this change -  https://github.com/WordPress/gutenberg/pull/17694

It might be that you're not on the latest version, this fix should role out in WP 5.4. Alternatively the latest version of the Gutenberg plugin will also have the fix. 

If your theme's on the public repository, feel free to share which theme it is and I can also try to test to see if the problem is still present.

**Comment by talldan** [comment] 2020-02-05 02:04
I'll close this in the meantime, but if you're still experiencing the issue and we can narrow it down to a Gutenberg bug it can always be reopened.

**Closed by talldan** 2020-02-05 02:04 UTC

**Comment by epiqueras** [comment] 2020-02-05 03:24
Thanks @talldan.
