### ISSUE TITLE
Generated permalink ignores permalink settings.

### ISSUE THREAD

**Issue by hvsh** [WordPress/gutenberg#10146] opened 2018-09-24 22:38 UTC
**Describe the bug**
When adding a new post, the automagically generated permalink ignores site wide permalink settings till the post is published. This leaves the user to publish the post before the permalink can be edited.

**Expected behavior**
Permalink should be editable regardless whether it is a draft or a published piece.

**Additional context**
Version 3.9.0

**Comment by designsimply** [comment] 2018-09-25 20:01
Thank you for the report! I am closing this issue because I believe this is a duplicate of #7129. If that's not right, please let me know.

**Closed by designsimply** 2018-09-25 20:01 UTC
