### ISSUE TITLE
Add Discord to the Social Links block.

### ISSUE THREAD

**Issue by Gulamdastgir-Momin** [WordPress/gutenberg#68241] opened 2024-12-23 11:11 UTC
## What problem does this address?
Add Discord as a social link option in the Social Links block.

## Why?
Discord is a widely used platform, and many users might want to link it on their sites, Like me :)

**Comment by Mamaduka** [comment] 2024-12-24 11:36
This is a duplicate of #35487. The original report also has a PR - #60865.

**Closed as duplicate by Mamaduka** 2024-12-24 11:36 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Block] Social
