### ISSUE TITLE
Media Blocks: Strange additional markup appears for each media block inserted

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#15862] opened 2019-05-28 10:04 UTC
Additional, strange, markup is generated when you insert a Cover block, an Image block, or a Media & Text block:

```
<button type="button" class="browser" style="display: none;"></button> 
```

Two of these get inserted for each instance of a media block inserted. GIF:

![bug](https://user-images.githubusercontent.com/1204802/107529739-77ecdc00-6bbb-11eb-89f6-55d6afc230c3.gif)

**To reproduce**

1. Open the web inspector, scroll to the bottom of the DOM to keep an eye on markup that appears
2. Insert a block that leverages Media, such as Image or Cover or Media & Text.
3. Observe how additional markup is created, each time you insert another of these.
4. If you copy and paste a Cover block in place, you will just create more and more of this dummy markup.

**Expected behavior**
The extra markup may serve a purpose that I'm unaware of, but there certainly doesn't need to be more than one such button. 

**Additional context**

This was tested on a Mac and reproduced in both Firefox, Safari and Chrome, with or without extensions. This is latest master.

**Comment by jasmussen** [comment] 2020-02-03 10:22
@gziolo Do you have bandwidth to help me investigate what's going on here? It seems the issue is especially visible with lots of placeholders:

<img width="1554" alt="Screenshot 2020-02-03 at 11 21 37" src="https://user-images.githubusercontent.com/1204802/73645362-6eab6400-4677-11ea-99df-62ba3f665eda.png">

In that it's a harmless bug it's not urgent. But I kind of feel like it's a symptom of an underlying issue.

**Comment by gziolo** [comment] 2020-02-03 11:25
Try again with the following patch applied:

```diff
diff --git a/packages/media-utils/src/components/media-upload/index.js b/packages/media-utils/src/components/media-upload/index.js
index 160e2707e..d78e608f8 100644
--- a/packages/media-utils/src/components/media-upload/index.js
+++ b/packages/media-utils/src/components/media-upload/index.js
@@ -137,7 +137,7 @@ class MediaUpload extends Component {
 		this.onClose = this.onClose.bind( this );
 
 		if ( gallery ) {
-			this.buildAndSetGalleryFrame();
+			// this.buildAndSetGalleryFrame();
 		} else {
 			const frameConfig = {
 				title,
@@ -147,18 +147,18 @@ class MediaUpload extends Component {
 				frameConfig.library = { type: allowedTypes };
 			}
 
-			this.frame = wp.media( frameConfig );
+			// this.frame = wp.media( frameConfig );
 		}
 
 		if ( modalClass ) {
-			this.frame.$el.addClass( modalClass );
+			// this.frame.$el.addClass( modalClass );
 		}
 
 		if ( unstableFeaturedImageFlow ) {
-			this.buildAndSetFeatureImageFrame();
+			// this.buildAndSetFeatureImageFrame();
 		}
 
-		this.initializeListeners();
+		// this.initializeListeners();
 	}
 
 	initializeListeners() {
```

It looks like it's coming from `wp.media` call, so we would have to improve it inside WordPress core.

**Comment by paaljoachim** [comment] 2021-02-10 14:53
Is this issue still valid?
@gziolo 
Thanks!

**Comment by jasmussen** [comment] 2021-02-10 15:16
It's still an issue: 

![bug](https://user-images.githubusercontent.com/1204802/107529578-4d9b1e80-6bbb-11eb-81cf-f13ca7104617.gif)

I'll update the title and steps to make it easier to reproduce.

**Comment by Mamaduka** [comment] 2021-07-20 06:38
I think this is a duplicate of #9184.

**Closed** 2021-07-21 07:56 UTC
Labels: [Block] Cover, [Block] Image, [Block] Media & Text, [Feature] Media, [Type] Bug, [Type] WP Core Bug
