### ISSUE TITLE
Pasting Heading text from clipboard ads it to a new block

### ISSUE THREAD

**Issue by carladoria** [WordPress/gutenberg#8258] opened 2018-07-27 15:43 UTC
**Steps to reproduce the issue**

1. Copy Heading text into your clipboard 
2. Paste it to the block in which you're already working

**What I expected**

I expected the text to be copied inside the block where I was typing

**What happened instead**

It was copied in a new block as it was recognized as a Heading text

You can see the recording here:

https://drive.google.com/file/d/1vZiaebfqKm10DfKHb0FAbCcKpa_-Pit9/view

**Comment by designsimply** [comment] 2018-07-27 21:56
Tested and confirmed that pasting heading text into a paragraph creates a heading. ([41s](https://cloudup.com/cbxEdMMImYg))

I also tested with the classic editor and found that the heading formatting is preserved in the same way in that editor. I believe this is the intended behavior because we cannot always know the intent for every case of pasting formatted content and so the editor preserves the type of formatting of the content that was copied, however, I also saw another discussion noting the following:

<blockquote>If you're pasting the content into a paragraph with content already in it, you most likely want the content in the paragraph I think.</blockquote>

<strong>Note:</strong> in many applications, you can paste and match style by pressing `Option-Shift-Command-V` on macOS or `Option-Shift-Control-V` on Windows or right-click and select "Paste as plain text". This may vary by application. I tested it in a few different browsers macOS 10.13.6 and it worked in my testing.

**Comment by maddisondesigns** [comment] 2018-07-29 11:18
This is exactly the reason why I've said we need a Paste as Text button!
#6132

**Comment by mtias** [comment] 2018-08-24 10:38
Duplicate of https://github.com/WordPress/gutenberg/issues/6555

**Closed by mtias** 2018-08-24 10:38 UTC
Labels: Needs Decision, [Component] Raw Handling, [Type] Enhancement
