### ISSUE TITLE
Cover Block has multiple issues

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18282] opened 2019-11-05 08:13 UTC
**Describe the bug**
The Cover Block has multiple issues.

After inserting a Cover block and adding some text to the default field, you can then click the Block Inserter to insert another block. After inserting a new Paragraph Block, I then tried to move it below the other text but couldn't. As soon as I tried to move it, the block broke.
- The Block Toolbar would no longer display when clicking on the block.
- The drag handle and block mover arrows disappear completely, meaning you can't move it.
- The text changed to white on a white background, so you could no longer edit the block reliably.
- Trying to change the colour of the text and/or background colour no longer worked.

The exact same thing happens to the default Paragraph block if you also try to move that as well.

Vid: https://cl.ly/8760a29c8cd5

<img width="666" alt="screenshot_28" src="https://user-images.githubusercontent.com/2078245/68189118-d281aa80-fffe-11e9-840c-c77ba572f8c3.png">

**To reproduce**
1. Insert cover block with image
2. Add text to default paragraph block
3. Insert new Paragraph Block and add text
4. Try to drag the new Paragraph Block below the other block
5. See Block break.

**Expected behavior**
Block shouldn't break

**Desktop (please complete the following information):**
- OS: MacOS Mojave 10.14.6
- Browser: Firefox Quantum 70.0.1 (64-bit)
- Version: WP 5.3-RC3-46639
- Theme: TwentyNineteen

**Comment by ehti** [comment] 2020-04-20 21:12
This UI/behavior has changed quite a bit, so it doesn't appear to be an issue as of now. Can't reproduce either. Closing.

**Comment by maddisondesigns** [comment] 2020-04-21 03:41
@ehti Please re-open this issue. The Cover Block still has serious issues.
You can replicate one of these issues easily, by following the steps that I outlined in my original comment. After adding a second block to the Cover Block, it's impossible to drag it below the first block. When you 'drop' it, the block ends up outside the Cover Block. It's also incredibly difficult to move it back into the Cover Block, once it's outside.

Here's another vid that I just created: https://share.getcloudapp.com/4guyxYmx

Dragging 'n dropping in Gutenberg is getting worse and worse, instead of better.

**Comment by ehti** [comment] 2020-04-21 10:27
@maddisondesigns 

The behavior where one is not able to drag the paragraph blocks within the Cover block is still an issue indeed. I'm not able to reproduce the _blank_ block following the original steps, but, the dragging is definitely an issue.

Thanks

**Comment by maddisondesigns** [comment] 2020-04-21 11:12
Yeah, the problem I mentioned with the block colours (i.e. the block turning white), doesn't seem to be an issue any more, which is good.

**Comment by draganescu** [comment] 2020-07-21 12:58
I tested this with the master version of Gutenberg and it seems resolved.

![cover-issue-solved](https://user-images.githubusercontent.com/107534/88057566-ee1be980-cb6a-11ea-99bf-dfc87a1f71f8.gif)

**Closed by draganescu** 2020-07-21 12:58 UTC
Labels: [Block] Cover, [Feature] Drag and Drop, [Type] Bug
