### ISSUE TITLE
Block restricted to a parent block shouldn't be able to be moved outside their parent block

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#11674] opened 2018-11-09 14:28 UTC
**Describe the bug**
I’ve created a FAQ block which serves as a container for inner Faq Item blocks which are restricted to the FAQ block using the parent setting. Currently it’s possible to drag and drop the inner Faq Item blocks outside their parent block.

Parent FAQ block:
````
<div className={ classes }>
  <InnerBlocks 
	allowedBlocks={ [ gb/faq-item' ] } template={ [ [ 'gb/faq-item', {} ] ] }
 />
</div>
````
Child FAQ Item block:
````
registerBlockType( 'gb/faq-item', {
	title: __( 'FAQ item' ),
	parent: [ 'gb/faq' ],
});
````

**Expected behavior**
It shouldn't be possible to move a block restricted to a parent block outside its parent.

**Comment by chrisvanpatten** [comment] 2018-11-09 14:54
I'm about 90% sure there's another open ticket for this but for some reason I can't find it 😂 That said I totally agree this is a problem and should be fixed up!

**Comment by mtias** [comment] 2018-11-21 00:59
Duplicate of #11131.

**Closed by mtias** 2018-11-21 00:59 UTC
Labels: [Component] Nested / Inner Blocks, [Type] Bug

**Comment by chrisvanpatten** [comment] 2018-11-21 01:17
Aaaand @mtias in with the assist 😂
