### ISSUE TITLE
./install-node-nvm.sh No such file or directory

### ISSUE THREAD

**Issue by guiu-rocafort** [WordPress/gutenberg#15726] opened 2019-05-19 13:54 UTC
**Describe the bug**
Running the setup-local-env.sh script would result in the following error message:
`./setup-local-env.sh: line 16: ./install-node-nvm.sh: No such file or directory`

Running directly `./install-node-nvm.sh` works without any problem, so i don't think it is a permission issue.

**To reproduce**
1. git clone git@github.com:WordPress/gutenberg.git
2. Cd into the 'gutenberg/bin' folder
3. `'./setup-local-env.sh'`

**Expected behavior**
The script install-node-nvm.sh and other setup scripts should run.

**Desktop (please complete the following information):**
Ubuntu 19.94 5.0.0-15-generic x86_64

**Comment by talldan** [comment] 2019-06-13 06:49
Hi @guiu-rocafort, the issue seems to be that the `setup-local-env.sh` expects to be called from within the root folder of the repo, rather than within the `bin` folder. In testing I was able to reproduce the same. If you `cd ..` up into the parent folder and run `./bin/setup-local-env.sh`, it should work.

Let me know how you get on. I'll close the issue for now but keep an eye out for further responses.

**Closed by talldan** 2019-06-13 06:49 UTC
Labels: Needs Technical Feedback, Needs Testing
