### ISSUE TITLE
Block editor doesn't filter user list using wp_dropdown_users_args

### ISSUE THREAD

**Issue by viktorix** [WordPress/gutenberg#40860] opened 2022-05-05 19:00 UTC
### Description

wp_dropdown_users_args filter works as expected when Classic Editor is enabled but doesn't work when block editor is enabled. The following code should exclude user with ID 2 from showing up in the author dropdown on the post/page edit page:

```
function wpdocs_add_subscribers_to_dropdown( $query_args ) {
 
 $query_args['exclude'] = array( 2 );

 return $query_args;
}
add_filter( 'wp_dropdown_users_args', 'wpdocs_add_subscribers_to_dropdown' );
```

This works in the classic editor, but not in the block editor. See screenshot.

If this is expected, then documentation for the filter needs to be updated.

### Step-by-step reproduction instructions

You can perform this test with only 1 user, you don't need more than 1 to test.

1. Add the test code from description to your theme's functions.php file. If you have 1 user, change ID to 1.
2. Open new post page and check author dropdown. You should see normal user list dropdown.
3. Install and activate classic editor. 
4. Open new post page while classic editor is enabled, and check the author dropdown. The user we excluded **should not** be in that dropdown.
5. Now switch to block editor to confirm that all users are showing again.

### Screenshots, screen recording, code snippet

<img width="597" alt="5ebef012-016d-4281-ae5f-8d696a81c3ea" src="https://user-images.githubusercontent.com/1692600/167003563-4eb86dee-da61-486d-a9e4-81d6790d39be.png">

### Environment info

- Windows 10
- Chrome 100.0
- WordPress 5.9.3
- Astra theme
- Classic Editor 1.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-05-15 09:12
Hi @viktorix.

`wp_dropdown_users_args` is a hook in the `wp_dropdown_users` function that generates drop-down HTML.

I think that the hook is invalid on the block editor, because the user list is retrieved via REST API.

Please try [rest_user_query](https://developer.wordpress.org/reference/hooks/rest_user_query/) hook instead:

```php
function my_rest_user_query( $prepared_args ) {
	$prepared_args['exclude'] = array( 2 );
	return $prepared_args;
}
add_filter( 'rest_user_query', 'my_rest_user_query' );
```

**Comment by t-hamano** [comment] 2022-05-28 11:32
@viktorix
I would like to close the issue because I think it is not a bug.
If you have any problems, please do not hesitate to comment.

**Closed as completed by t-hamano** 2022-05-28 11:32 UTC
Labels: [Type] Help Request
