### ISSUE TITLE
Publish date should be displayed using WordPress’ timezone (instead of the browser’s)

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#25003] opened 2020-09-02 09:02 UTC
In WordPress 5.5, the Publish date should be displayed using WordPress’ timezone, but it uses the browser’s instead.

For example, let WordPress’ timezone be _America/Chicago_ and let the browser's be _Europe/Madrid_. If the author sets the publication date/time to be on "August 20, 2020 10am" (i.e. WordPress timezone), what they see in the UI is "August 20, 2020 3am" (i.e. browser's timezone).

**To reproduce**
1. Change your WordPress' timezone so that it's different from that of your browser
2. Create a new post in Gutenberg
3. Set a date/time
4. The time you set is different from the time shown in the UI (see screenshot)

**Expected behavior**
The Publish date should be displayed using WordPress’ timezone. This way, the UI would always be consistent: the value an author sets in the dropdown selector would (and should) be the same as the value they see in the date field.

**Screenshots**
![Inconsistent Publish Date](https://user-images.githubusercontent.com/12100954/91961436-76b1ac00-ed0b-11ea-8a45-e5a57e229501.png)

**Editor version:**
- WordPress version: 5.5.1
- Default Gutenberg

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version 77

**Comment by iandunn** [comment] 2020-09-07 23:09
I'm seeing this too.

**Comment by ryelle** [comment] 2022-03-31 21:28
This is a duplicate of #25256, which was fixed back in Dec 2020

**Closed** 2022-03-31 21:29 UTC
Labels: [Type] Bug, [Status] Duplicate, [Package] Editor
