### ISSUE TITLE
On blank page open inserter downward

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1098] opened 2017-06-10 07:59 UTC
Edit:
Inserter as it opens right now on a blank page.
![gutenberg-blank-page-inserter-opens-upward](https://user-images.githubusercontent.com/5323259/27001182-b67c04ce-4dc3-11e7-85a7-52bbdc5f675e.png)

Since the inserter opens upward on a blank page and that crashes into the toolbar it would be good to have it instead open downward.

![gutenberg-blank-page-open-inserter-downward](https://user-images.githubusercontent.com/5323259/27001164-38b728b6-4dc3-11e7-8d54-f3f357470990.jpg)

I have moved the title up a bit to have a bit of separation between the inserter and the title. (Since the title for the time being is not a block.)

**Comment by mehigh** [comment] 2017-06-15 13:01
This is a duplicate of https://github.com/WordPress/gutenberg/issues/1004

**Comment by aduth** [comment] 2017-06-15 13:01
Closing per https://github.com/WordPress/gutenberg/issues/1098#issuecomment-308722611

**Closed by aduth** 2017-06-15 13:01 UTC
Labels: Chrome, Task, [Component] Inserter
