### ISSUE TITLE
Jetpack subscription banner on New Post page looks awkward

### ISSUE THREAD

**Issue by zandyring** [WordPress/gutenberg#3703] opened 2017-11-28 19:42 UTC
## Issue Overview
Using Gutenberg 1.8.0 and Jetpack 5.5, the upsell banner for Jetpack on the New Post page is awkwardly layered between Gutenberg elements.
![screen shot 2017-11-28 at 2 35 22 pm](https://user-images.githubusercontent.com/7304712/33340381-f52c67a6-d449-11e7-9494-21a04174eaaf.png)

## Steps to Reproduce (for bugs)

1. Enable Gutenberg
2. Enable Jetpack Premium
3. Add new Post (or Page)
4. Notice the banner layering between the action bar and the rest of the page.

Chrome 61.0.3163.100, Macbook Air 10.11.6

**Comment by aduth** [comment] 2017-11-28 20:59
Possibly related: #3671 (cc @youknowriad @jasmussen )

**Comment by kraftbj** [comment] 2017-11-29 03:50
I think this is a duplicate of #3395

**Comment by jasmussen** [comment] 2017-11-29 08:18
Yes, Kraft is right, this is a duplicate. Thanks for the ticket, I'll add the notes from this one to the other!

**Closed by jasmussen** 2017-11-29 08:18 UTC
Labels: [Type] Plugin / Extension Conflict
