### ISSUE TITLE
Query Loop Block in Widget Areas

### ISSUE THREAD

**Issue by douglas-johnson** [WordPress/gutenberg#46132] opened 2022-11-28 19:26 UTC
## What problem does this address?

I am working on a site that uses a classic theme, but we're trying to use the block editor in every place possible. I would like to include a list of posts from a custom post type in a widget area, but haven't been able to make this work with features available in WordPress core 6.1.1

I am unable to add a `core/query` block to a widget area. I have not been able to find a specific piece of code that prevents this, but the query related blocks are not listed under the theme category when I try to add a block.

I could not find documentation about why this is the case. The closest I found was a support ticket on WordPress.org that mentioned pagination blocks were not available in widget areas.

## What is your proposed solution?
It would be helpful for my transition from classic themes to full site editing if widget areas could contain `core/query` without pagination or if `core/latest-posts` supported custom post types.

**Comment by t-hamano** [comment] 2022-11-29 10:29
Some blocks for FSE seem to be explicitly opted out, as seen in #32761, #32756.

From a quick test, the query loop block seems to work well, 

![widget](https://user-images.githubusercontent.com/54422211/204505484-6f76f151-f4d4-4ba2-b060-2be4b02a6c7b.png)

However, I would like to wait for advice from someone more knowledgeable to see if this causes any problems or issues that need to be resolved.

**Comment by talldan** [comment] 2023-04-11 07:06
I think most of those blocks are disabled as the widget editor has no way to save full site editing 'entities'. That possibly doesn't apply to the query block, as I don't think the post content is editable. Maybe it will be in the future, I don't know.

This is a duplicate of #32952, so I'll close it.

**Closed as not planned by talldan** 2023-04-11 07:06 UTC
Labels: Needs Technical Feedback, [Package] Edit Widgets
