### ISSUE TITLE
Success message is not spaced evenly

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#9579] opened 2018-09-03 14:37 UTC
Right now this is what you see on deleting a block:

![2018-09-03 at 15 33](https://user-images.githubusercontent.com/253067/44992424-11494a00-af8f-11e8-98c6-da6dab9cf5b6.png)

**Comment by Soean** [comment] 2018-09-03 15:50
Duplicate of #9422

**Closed** 2018-09-03 16:02 UTC
