### ISSUE TITLE
Non-dismissible notices block the content area.

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#6340] opened 2018-04-21 22:47 UTC
Gutenberg notices cannot be scrolled, so when creating several non-dismissible notices, the content area is no longer accessible - it's covered in notices that cannot be scrolled up to access the content.

js.

**Comment by noisysocks** [comment] 2018-04-23 02:02
Hey @jsmoriss. Could you provide some reproduction steps for this? e.g. how do I make several non-dismissible notices appear?

I'm going to close this for now but let's definitely re-open it once there's more information.

**Comment by jsmoriss** [comment] 2018-04-23 07:12
I'm not sure I understand your question - you're asking about how to create Gutenberg notices??? This issue is NOT about creating notices.

Gutenberg puts notices over the content area. If those notices are not dismissible, then the content area is less and less accessible the more non-dismissible notices there are - eventually, the content area is not accessible at all.

**Comment by noisysocks** [comment] 2018-04-23 23:46
@jsmoriss To be clear, are you referring to these notices?

<img width="856" alt="screen shot 2018-04-24 at 09 43 55" src="https://user-images.githubusercontent.com/612155/39158543-0bcd18c0-47a4-11e8-8c64-653b3da88f09.png">

I'm unable to re-create a scenario where there are so many notices that the content area is unusably small. Could you please write down some detailed steps to follow and upload a screenshot of the problem?

**Comment by jsmoriss** [comment] 2018-04-24 13:28
Really? You can't create multiple non-dismissible notices?

I've had to make all my notices dismissible, either for the current view (shown again on save), for the current page load (the Gutenberg default), for a period of time (1 hour, 1 month, etc.), or permanently. **Using non-dismissible notices is not an option because they block the content area.**

Example - imagine these are non-dismissible and you get the idea. ;-)

![screenshot-2018-4-24 featured image vertical surnia ulula admin wordpress](https://user-images.githubusercontent.com/2913687/39189919-b4dca1ba-4790-11e8-8f3d-4bd09e179261.png)

**Comment by jsmoriss** [comment] 2018-04-24 13:34
BTW, in case you notice - yes, there's a duplicate error message in there :) - I was working on that when I took the screencap. ;)

js.

**Comment by jsmoriss** [comment] 2018-04-25 19:35
It floors me that this issue was closed without bothering to understand or re-create the issue.

js.

**Comment by noisysocks** [comment] 2018-04-26 04:36
@jsmoriss: We get a lot of issues and so my preference is to close any that are un-actionable. Without a screenshot or a _Steps to Reproduce_ section in the description, it's really difficult to triage and action an issue. Thanks for being patient and for providing extra information about the issue 🙂

cc. @karmatosed for design input on this.

My feeling is that making notices scrollable is not something that we would support natively, as they're intended to be short messages that convey to the user that an asynchronous task has finished. It's probably better that persistent information such as SSO validation errors are located somewhere permanent e.g. the post sidebar.

**Comment by jsmoriss** [comment] 2018-04-26 12:40
Non-dismissible notices are a potential issue with the current design of Gutenberg notices - another option would be to remove support for isDismissible and make all notices dismissible.

Note that to access the content area, when there are multiple notices, the user MUST dismiss the notices. In some cases, this means dismissing the error for a period of time, or permanently, *which may not be what the user really wants to do* - but might be required to access the content area.

On a personal note - The WordPress notification / notice system has always been a problem, and Gutenberg seems to have made it worse.

js.

**Comment by karmatosed** [comment] 2018-04-27 13:55
@jsmoriss this is a foundational issue with they messaging in WordPress and I don't overly agree Gutenberg has made it worse as much as exposed it maybe. That all said, it doesn't get us a solution, so let's turn to that as a focus. I think where possible errors being contextual is a better option, I don't think making an area scrollable does that. 

This is a longer term issue but, what we should do I think in this case is turn our attention to core and work to make handling of messages better there, we can then have them work better in Gutenberg.

One possible 'now' option could be simply to only show latest 3 messages and have a 'notice' with a 'click to show more messages'. I don't like this as a solution though as it doesn't solve the ground problem, WordPress and plugins shouldn't be filling your page full of messages like this. It's a horrible user experience.

**Comment by jsmoriss** [comment] 2018-04-27 14:39
Gutenberg has hidden the native WordPress notices, and from what I understand, Gutenberg developers expect to show only 1 or maybe 2 single sentence notices. In some cases, more complete warning and error messages may be required for missing / incorrect content - as shown in this example. Obviously this example should not be taken as somekind of highwater mark - 3rd party developers will use the Gutenberg notices - how and why they use them is up to that developer.

**I am simply reporting that Gutenberg notices block the content area.** Non-dismissible notices are a serious issue since they cannot be dismissed, so the content area may be inaccessible. Dismissible notices force the user to dismiss the notices to gain access to the content area. Some notices may be dismissed temporarily, for a longer period of time, or permanently. Forcing users to permanently dismiss a notice (for example) to gain access to the content area is a problem.

If you would like to deal with this issue as a "Question" (as you've labeled this issue), then obviously that's up to you, but I don't agree. Fundamentally, I think the display of notifications in Gutenberg is flawed. Since Gutenberg blocks / hides WordPress notifications, developers will have to use Gutenberg notices and live with the awful UI experience for the user, as you've stated.

js.

**Comment by karmatosed** [comment] 2018-04-27 17:41
Let me add 'needs decision' as a that probably is a solid option for getting opinions and insights, that's what I meant by question.

**Comment by youknowriad** [comment] 2018-11-26 18:37
closing as duplicate of #12243 which is a bit more active.

**Closed by youknowriad** 2018-11-26 18:37 UTC
Labels: Needs Decision
