### ISSUE TITLE
ColorPicker gets stuck while changing the color.

### ISSUE THREAD

**Issue by delowardev** [WordPress/gutenberg#36337] opened 2021-11-09 05:36 UTC
### Description

When someone changes the color, suddenly it gets stuck and the pointer inside the picker starts blinking automatically. 

![](https://media.giphy.com/media/Q5kGxXHI7aY7R2iJlS/giphy.gif)

### Step-by-step reproduction instructions

1. Open ColorPicker
2. use `enableAlpha` true
3. Change alpha slider for few times
4. Keep moving the color pointer inside the color picker, it will start blinking suddenly

### Screenshots, screen recording, code snippet

Screen record: 
https://share.vidyard.com/watch/osmwf9H7Dtp1DxziRj6jP5?

Code Snippet: 
https://codesandbox.io/s/cocky-poitras-v9iht?file=/src/App.js

### Environment info

- Browser: Chrome 95.0.4638.69 (Official Build) (arm64)
- Device: MacBook Pro (M1)
- OS: macOs Monterey
- WordPress: 5.8.1, it happens both inside and outside of WordPress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2021-11-09 05:40
Hi, @delowardev

I think this might be a duplicate of #36314. I just tested the issue and confirmed it's a bug.

**Comment by delowardev** [comment] 2021-11-09 05:44
@Mamaduka they are different I think, this one doesn't break the UI and shows error only in the browser console. But mentioned issue breaks the layout and component itself.

**Comment by Mamaduka** [comment] 2021-11-09 05:48
I think we see a broken block message because of the error boudary. But I'm happy to re-open to issue if you think they are different.

**Comment by delowardev** [comment] 2021-11-09 05:51
@Mamaduka I did try inside WordPress, it just gets stuck, doesn't break UI. Please check this short clip: https://share.vidyard.com/watch/gaoM7cVFpqVN1QVkeGPrY9?

**Comment by Mamaduka** [comment] 2021-11-09 05:52
Thanks for the confirmation.

**Comment by mirka** [comment] 2021-12-02 22:59
Fixed in #36941

**Closed as completed by mirka** 2021-12-02 22:59 UTC
Labels: [Type] Bug, [Feature] Component System
