### ISSUE TITLE
Improve Global Styles label and description in Site Editor save panel

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#57313] opened 2023-12-21 15:29 UTC
## What problem does this address?

In working with users new to the site editor, the label and lack of description when saving Global Styles changes can be confusing.

<img width="283" alt="image" src="https://github.com/WordPress/gutenberg/assets/1699996/82cec2c0-ab70-419b-828b-16bef2c077a8">

## What is your proposed solution?

- Add a text description for the Global Styles section, similar to what other sections have
- Consider if there's a clearer term than "Custom Styles" to describe exactly what's being saved (but I can't think of one at the moment)

**Comment by annezazu** [comment] 2023-12-21 23:50
Closing this out as this is a duplicate of this prior longstanding issue: https://github.com/WordPress/gutenberg/issues/29388

**Closed as completed by annezazu** 2023-12-21 23:50 UTC
Labels: [Type] Enhancement, Global Styles, [Feature] Site Editor

**Comment by creativecoder** [comment] 2023-12-23 22:33
Thanks for the link to that issue!

I think there's a small, easy win here in adding a description for the Global Styles section. I'll comment there.
