### ISSUE TITLE
Footnotes: Unintended behavior in gallery image caption text

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52383] opened 2023-07-06 15:44 UTC
### Description

In the caption text of the image block in the gallery block, using the footnotes format inserts an unintended footnotes block. The footnotes block is generated, but nothing can be entered. This problem does not seem to occur with caption text in the gallery itself or in image blocks that are not in the gallery.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/98f28be7-d0b7-4bb9-8e81-659191dbc209

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2023-07-06 17:58
This is probably a duplicate of #52084.

**Comment by annezazu** [comment] 2023-07-06 18:46
Came here to connect the same thing :) Is anyone able to say for certain? For now, will add to 6.3 board to be safe.

**Comment by t-hamano** [comment] 2023-07-10 12:26
I have learned that #52084 has been closed, but the problem with this issue has not yet been resolved.

- ✅ Text in a paragraph block within a Quote block can be correctly anchored.
- ✅ Citation text within a Quote block can also be correctly anchored.
- ❌ Caption text in an image block within a gallery block cannot be anchored correctly.

https://github.com/WordPress/gutenberg/assets/54422211/d2654864-93bd-46c1-91ab-2da84a0075a6

**Comment by bph** [comment] 2023-07-10 19:20
#52241  fixed for the Image block caption and the Gallery caption 

What is still not working is the footnote for single image caption that belongs to a gallery. 
If there are already footnotes on the page the county is off, and it doesn't add footnotes rather seems to intend to replace. 

https://github.com/WordPress/gutenberg/assets/39980/3712295b-5558-4c49-9487-b9f523fc21c5



If there is only the gallery in place, and you create new footnotes, it doesn't add a footnotes block to the canvas. It seems to be adding it to the caption directly. 



https://github.com/WordPress/gutenberg/assets/39980/1807fcb2-8d08-4011-9cd4-442cfc13e225

**Comment by bph** [comment] 2023-07-17 14:13
Needs retesting when #52682 is merged.

**Closed as completed** 2023-07-17 16:42 UTC
Labels: [Type] Bug, [Block] Gallery, [Block] Footnotes
