### ISSUE TITLE
Updating Gutenberg failed

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2942] opened 2017-10-09 21:06 UTC
Reported from feedback form:

"Hi,Team!  Just now i installed and tested the plugin.It is not working within site.It is showing updating failed and while i click on preview it is showing blank.Even i tested it by shifting themes in that case also i got the same error!"

GitHub user: @basamrajesh reported this. Could you provide please more information on what happened and if possible an image?

**Comment by hedgefield** [comment] 2017-10-19 13:31
Seems like a duplicate of #2544?

**Closed** 2017-11-06 13:01 UTC
Labels: [Status] Needs More Info, [Type] Bug
