### ISSUE TITLE
Gutenberg crashes when User Tries to add Tags to Post

### ISSUE THREAD

**Issue by AMcGrady** [WordPress/gutenberg#13271] opened 2019-01-09 22:37 UTC
**Describe the bug**
User indfuse reports that Gutenberg Editor crashes when they try to add a Tag to a post.They are using Theme Baskerville 2.  When I log in as them I can add Tags to Post with no issue. 

**To Reproduce**
Unknown. See above.

**Expected behavior**
Gutenberg to remain stable when user adds Tags to Posts. 

*Desktop (please complete the following information):**
 - OS: macOS (Mojave)
 - Browser Chrome
 - Version 71
https://whatismybrowser.com/w/9ZC4PE7

**Additional context**
Gutenberg: 4.8.0

**Comment by designsimply** [comment] 2019-01-10 01:57
Would you be able to check the console panel in your browser developer tools at the time the problem happens? Specifically, if you open the console panel and then try to add a tag to a post, do any errors appear in the console at that point? If yes, it's possible they could help pinpoint the source of the trouble.

Are you using WordPress 5.0.3?

Are you able to temporarily deactivate all plugins and try adding tags to a post again to see if you can generally rule out a plugin conflict? If not, could you list the active plugins for reference?

**Comment by designsimply** [comment] 2019-01-10 16:31
For good measure, I tested with the Baskerville 2 theme on a WordPress 5.0.4-alpha-44523 install as well as on a WordPress 5.0.3 install (note: I had to install Jetpack 6.9 too since Baskerville 2 is a WP.com Jetpack theme) using Chrome 71.0.3578.98 on macOS 10.13.6 and I was able to add tags to a new post with that setup. Since you mentioned being able to log in yourself and add tags, I checked both logged as the Administrator and the Author role and didn't have problems with either one.

![13271-20s](https://user-images.githubusercontent.com/1119271/50981552-75899680-14b8-11e9-8c87-e4ae443339e4.gif)

I also did a quick check with a simple site on WP.com + Baskerville 2 and couldn't see the problem happen there either. ([14s](https://user-images.githubusercontent.com/1119271/50981949-563f3900-14b9-11e9-9fa2-36de7fea2c33.gif))

A few more troubleshooting ideas for the user you are working with:
- try clearing browser cache
- check for browser add-ons
- try from a different browser

If possible, having them check for console errors and (if it applies to them) temporarily disabling plugins are also very good troubleshooting steps for this case.

**Comment by designsimply** [comment] 2019-01-30 18:02
I looked at the chat transcript for this issue and found that the user reported the following: 

> The error happens as soon as I start typing in the tag section. The category section, featured image etc works fine.

and they noted that the error they see on screen when the problem happens is:

> The editor has encountered an unexpected error.

They also said that the problem started happening about three weeks prior to reporting the issue to the WordPress.com Happiness team on 2019-01-09.

I tested this again today with a clean install of WordPress 5.0.3 and no active plugins via https://jurassic.ninja/ and found that adding tags is working normally for me in that environment. ([53s](https://cloudup.com/c5ASylReqMx))

Since the original report came from someone using WordPress.com, I also tested again with WordPress.com using a simple site with a Premium Plan and a custom domain and I was able to add tags to new posts without any problems there as well. ([2m2s](https://cloudup.com/c5gcUWRMTGN))

I also tested with a WordPress.com Business Plan site running WordAds and was able to add tags without problems on that site too. ([40s](https://cloudup.com/cGhybC9vL15))

Closing as works for me and noting that more troubleshooting is recommended and I would like to include a few ideas for troubleshooting:

* Since we have been unable to reproduce the problem after several tests, it would be worth checking to see if the user experiencing the problem is able to look in the console and/or network panels of their browser tools to see if they can find an error that will help uncover more detail that could point us in the right direction. See [example](https://cloudup.com/cUJdqwFqhCV).
* Try from a different browser to rule out a browser-specific issue.
* Try from a different network location to rule out something blocking the REST API at the local network level (this one's a really long shot but might be worth a try if nothing else works).

@AMcGrady if you uncover any additional details to help make this issue more actionable, please let me know and I will re-open it!

**Closed by designsimply** 2019-01-30 18:02 UTC
Labels: [Status] Needs More Info, [Type] Help Request

**Comment by Jefak007** [comment] 2022-01-12 01:44
I am facing this same exact problem.
For over 3 months, it has been stressful to add tags, once I start typing, the entire page just freezes.
