### ISSUE TITLE
Error on update failed issue

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9662] opened 2018-09-06 13:53 UTC
**Describe the bug**
I am creating block related to post. Where I am trying to get post data which is retrieved through withSelect function and stored in state. Once I tried to store this state data to this.props.attributes.post_data = state.data then I am getting following error - 

<br />
<b>Warning</b>:  mysqli_query(): MySQL server has gone away in <b>C:\xampp\htdocs\gutenberg\wp-includes\wp-db.php</b> on line <b>1924</b><br />
<br />
<b>Warning</b>:  mysqli_query(): Error reading result set's header in <b>C:\xampp\htdocs\gutenberg\wp-includes\wp-db.php</b> on line <b>1924</b><br />
<br />
<b>Warning</b>:  mysqli_query(): MySQL server has gone away in <b>C:\xampp\htdocs\gutenberg\wp-includes\wp-db.php</b> on line <b>1924</b><br />
<br />
<b>Warning</b>:  mysqli_query(): Error reading result set's header in <b>C:\xampp\htdocs\gutenberg\wp-includes\wp-db.php</b> on line <b>1924</b><br />
{"author":0,"date":"","date_gmt":"","id":null,"modified":"","modified_gmt":"","parent":0,"slug":null,"guid":{"rendered":null,"raw":null},"title":{"raw":null,"rendered":""},"content":{"raw":null,"rendered":""},"excerpt":{"raw":null,"rendered":""},"permalink_template":"","generated_slug":"","preview_link":null,"_links":{"wp:action-unfiltered_html":[{"title":"The current user can post HTML markup and JavaScript.","href":null,"targetSchema":{"type":"object","properties":{"unfiltered_html":{"type":"boolean"}}}}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}

**Comment by tofumatt** [comment] 2018-09-06 18:05
As this is the issue tracker for the editor we aren't able to help with plugin development here. As this looks like a MySQL error I'm closing this issue, but if there's an issue with Gutenberg please let us know and provide code/steps to reproduce. Thanks!

**Closed by tofumatt** 2018-09-06 18:05 UTC
Labels: [Type] Help Request
