### ISSUE TITLE
Saving custom colors in Paragraph Block

### ISSUE THREAD

**Issue by fresatomica** [WordPress/gutenberg#25416] opened 2020-09-17 12:35 UTC
A user on the WordPress.com forums suggested they would like to be able to save their custom colors in the Block Settings so it's easy to reuse the same color all over the site.

It's a feature that was available in Classic Editor.

More information and screenshots can be found [here](https://wordpress.com/forums/topic/block-editor-causing-more-problems-than-it-solves/#post-3563290).

**Comment by youknowriad** [comment] 2020-09-17 13:36
Duplicate of #6941

**Closed by youknowriad** 2020-09-17 13:36 UTC
