### ISSUE TITLE
In ver. 5.6, the message display when the block registered in the "block library" is stopped is broken.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#27287] opened 2020-11-26 08:21 UTC
Thank you for your continuous development.

I'm sorry if an issue has already been raised.
While testing version 5.6RC, I found something like a bug, so I'll report it.

As the title says, the message display when the block registered in the "block library" is stopped is broken.

It should look like the screenshot below.

<img width="1495" alt="スクリーンショット 2020-11-26 17 11 08" src="https://user-images.githubusercontent.com/31400297/100324896-32346480-300b-11eb-945e-5c185e5f1c9c.png">

- The contents of the stopped block will spread to the full width.
- I cannot click on this area, so I cannot delete it.
- I can only click the install button or "Keep as HTML" button.

When I checked it with the developer tools, it seems that the cause is that the wrapper by `[data-tye="core/missing"]` has disappeared.

## My testing environment:

OS: macOS Catalina 10.15.7
Browser: Chrome
WordPress: 5.6 RC1
Language: Japanese, English
Theme: Twenty Twenty One

**Comment by ddryo** [comment] 2020-11-26 08:24
If a block that is not registered in the "block library" is stopped, it will be as follows.

<img width="1493" alt="スクリーンショット 2020-11-26 17 22 55" src="https://user-images.githubusercontent.com/31400297/100325516-2006f600-300c-11eb-8f83-5bc2b5b2dcb0.png">

- The content of a stopped block fits in the same width as other blocks.
- I can select it by clicking it, so I can delete it as it is.

**Comment by tellthemachines** [comment] 2020-11-27 04:33
I can reproduce this in WP 5.6 RC1. I also notice when loading the page, the warning is initially formatted properly, but then stretches out and becomes unclickable when page load is finished.

**Comment by mcsf** [comment] 2020-11-27 17:00
Thanks for the report. On the surface, this seems related to Block Directory work, so cc @tellyworth to make sure it's on your radar.

**Comment by ryelle** [comment] 2021-01-06 22:23
This is the same issue as #27916, which will be fixed with #28030 — since the other issue is already milestoned for WordPress 5.7, I'm going to close this one.

**Closed by ryelle** 2021-01-06 22:23 UTC
Labels: [Feature] Block Directory, [Feature] Blocks, [Type] Bug
