### ISSUE TITLE
Unregistered block styles appear in the global site editor

### ISSUE THREAD

**Issue by unscripted** [WordPress/gutenberg#58048] opened 2024-01-21 18:31 UTC
### Description

After unregistering a block style using `unregisterBlockStyle`, it remains as a variation that can be customized in the global style editor. 

As a developer, I expect that unregistering a default block style should remove it from the global style editor. I view this as an issue because an admin using the global style editor may try to edit something that is not a feature of the theme.

### Step-by-step reproduction instructions

1. Unregister a core block style variation. (I used `core/button, outline`)
2. Confirm that it does not appear as a variation in the block editor.
3. Navigate to the global styles editor > Blocks > Button.
4. You will see "Outline" as a variation that you can customize.

### Screenshots, screen recording, code snippet

Below is the js snipped I used to unregister the block style.

``` js
domReady(function () {
  unregisterBlockStyle('core/button', 'outline');
});
```

### Environment info

- WordPress 6.4.2
- Gutenberg 17.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2024-01-23 04:05
Hi @unscripted,

Could you tell me what code is used to enqueue that script? The reason I ask that is because #25330 reports an issue with `unregisterBlockStyle` not working due to dependency when enqueuing scripts.

**Comment by andrewstaffell** [comment] 2024-04-17 08:39
@unscripted I think you can fix this by including the `@wordpress/edit-site` dependency (as well as the `@edit-post` one which in my experience was already needed to unregister correctly in normal post/page editor), ie.

```
import domReady from '@wordpress/dom-ready';
import '@wordpress/edit-post'; /* dependencies needed to avoid unregisterBlockStyle race condition */
import '@wordpress/edit-site';
import { registerBlockStyle, unregisterBlockStyle } from '@wordpress/blocks';

domReady(() => {
	unregisterBlockStyle(
		'core/separator',
		['default', 'wide', 'dots']
	);
});
```

I figured this out thanks to [this comment](https://github.com/WordPress/gutenberg/issues/25330#issuecomment-1022935491) which implies that in some scenarios it might be necessary to import `edit-widgets` too? But I haven't tested that.

**Comment by t-hamano** [comment] 2024-05-04 05:54
I think the point of the problem is that we can't unregister block styles just by using `domReady`, and we need to include a specific editor package as a dependency.

These issues have already been discussed in #25330, so I would like to close this issue.

**Closed as not planned by t-hamano** 2024-05-04 05:54 UTC
Labels: [Type] Bug, [Status] Duplicate, Global Styles
