### ISSUE TITLE
Core group block as inner block shows the block variation picker 

### ISSUE THREAD

**Issue by upham-ui** [WordPress/gutenberg#64005] opened 2024-07-26 15:58 UTC
### Description

If I try to add a core/group block to the innerBlocks of a block variation (also of the core/group block) the block does not initialize properly, instead I see the experimental block variation picker. This prevents being able to set attributes on those inner blocks or adding inner blocks to them as well. 

### Expected Behavior
When I add a core/group block to an innerBlock template, that core/group block should be added to the editor fully initialized, assuming those group blocks have the attributes that specify their fully initialized configuration (as a Group, Row, or Stack, for example). Furthermore, any blocks within that group block should be added to the editor. 

### Actual Behavior 
Group blocks in the innerBlocks template are displayed in the editor with the block variation picker and attributes added to them in the template are gone, as are any innerBlocks added to them. 

<img width="1250" alt="Screenshot 2024-07-26 at 11 57 46 AM" src="https://github.com/user-attachments/assets/11c3d8e0-f52d-4e0a-8580-6a3f8d576c04">

```
wp.domReady(() => {
  wp.blocks.registerBlockVariation("core/group", {
    name: "accordion",
    title: "Accordion",
    icon: "list-view",
    attributes: {
      className: "folder has-children",
    },
    innerBlocks: [
      [
        "core/group",
        {
          attributes: {
            className: "accordion-button folder-header collapsible",
            layout: {
              type: 'default'
            },
          },
        },
      ],
    ],
    isActive: ["className"],
  })
})
```

### Step-by-step reproduction instructions

1. Add the above code.
2. Try adding the Accordion group block variation to a post.
3. See that the inner group block is not initialized -- instead its waiting for a variation selection. 

### Screenshots, screen recording, code snippet

<img width="1144" alt="Screenshot 2024-07-26 at 11 37 51 AM" src="https://github.com/user-attachments/assets/b1d4f5e9-a973-4ace-bdea-367c964012f6">

### Environment info

WP 6.6.1.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by talldan** [comment] 2024-07-29 04:42
@upham-ui Could you add what the expected behavior is, and why you believe that it should work that way?

It's unclear to me why the variation picker is not the right thing for the inner group block to show.

**Comment by upham-ui** [comment] 2024-07-29 13:21
@talldan sure. I updated the original issue. Here's what I added: 

### Expected Behavior
When I add a core/group block to an innerBlock template, that core/group block should be added to the editor fully initialized, assuming those group blocks have the attributes that specify their fully initialized configuration (as a Group, Row, or Stack, for example). Furthermore, any blocks within that group block should be added to the editor. 

### Actual Behavior 
Group blocks in the innerBlocks template are displayed in the editor with the block variation picker and attributes added to them in the template are gone, as are any innerBlocks added to them.

**Comment by talldan** [comment] 2024-07-30 03:00
There are two separate things happening with your example.

The first is that the outer group block's variation `isActive` isn't working. From debugging the issue, it looks like the group block's core variations are taking precedence over your one. 'Group' is actually defined as a variation internally. The same issue is documented here - https://github.com/WordPress/gutenberg/issues/41303.

There has been some progress on improving the situation - https://github.com/WordPress/gutenberg/pull/63100. My advice would be not to use `className` for `isActive`, as users can change the classname in the UI, and your variation will become inactive. Perhaps consider adding a new attribute to the group block using the `registerBlockType` filter or similar that can store some information about the variation. I think it still wouldn't fix your issue though.

The second is the inner group block doesn't retain the classnames specified in the template. You can fix your example by removing the incorrect `attributes` key in the template, the object itself is the attributes:
```js
wp.domReady(() => {
  wp.blocks.registerBlockVariation("core/group", {
    name: "accordion",
    title: "Accordion",
    icon: "list-view",
    attributes: {
      className: "folder has-children",
    },
    innerBlocks: [
      [
        "core/group",
        {
          className: "accordion-button folder-header collapsible",
          layout: {
            type: 'default'
          },
        },
      ],
    ],
    isActive: ["className"],
  })
```

To specify some inner blocks you can add a third item in the array:
```js
[
  "core/group",
  {
    className: "accordion-button folder-header collapsible",
    layout: {
      type: 'default'
    },
  },
  [
    [ "core/paragraph", { content: "Test" } ]
  ]
]
```

**Comment by upham-ui** [comment] 2024-07-30 14:56
Incredibly helpful. I had given up on the isActive; I assumed it had to do with core variations or something like that. But I was clueless about the form of the innerBlocks object. Thank you!

**Comment by talldan** [comment] 2024-07-31 02:24
Glad it helped. I'll close the issue if that's ok as the remaining problem is already tracked in https://github.com/WordPress/gutenberg/issues/41303.

**Closed as not planned by talldan** 2024-07-31 02:24 UTC
Labels: [Type] Bug, [Block] Group, [Feature] Block Variations
