### ISSUE TITLE
Site is Experiencing a Technical Issue in lib/client-assets.php file

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#16360] opened 2019-06-29 13:02 UTC
**Describe the bug**
There seems to be a bug in the client-assets.php file.

**To reproduce**
Actually, I am not sure how to reproduce this as I only received an email by my WordPress installation informing me that:

> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with one of your plugins, Gutenberg.
> 
> ...
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 58 of the file /.../httpdocs/wp-content/plugins/gutenberg/lib/client-assets.php. Error message: Uncaught Error: Call to a member function query() on null in /.../httpdocs/wp-content/plugins/gutenberg/lib/client-assets.php:58
> Stack trace:
> #0 /.../httpdocs/wp-content/plugins/gutenberg/lib/client-assets.php(539): gutenberg_override_script('react', 'https://www.dav...', Array, NULL)
> #1 /.../httpdocs/wp-content/plugins/gutenberg/lib/client-assets.php(435): gutenberg_register_vendor_script('react', 'https://unpkg.c...', Array)
> #2 /.../httpdocs/wp-content/plugins/gutenberg/lib/client-assets.php(230): gutenberg_register_vendor_scripts()
> #3 /.../httpdocs/wp-includes/class-wp-hook.php(286): gutenberg_register_scripts_and_styles('')
> #4 /.../httpdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
> #5 /...

When looking at my homepage, I was not able to see any problems, but as I received this email for the sixth time within a few weeks (using different versions of Gutenberg), I wanted to report this issue.

**Expected behavior**
I would expect that no such error messages occur.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 67.0.4. 64 bit

**Additional context**
- Gutenberg Version: 5.8, 5.9, 6.0

**Comment by swissspidy** [comment] 2019-07-01 10:36
Here's the code in question: https://github.com/WordPress/gutenberg/blob/08cda3f0dd23595e685d67209e4b4f811d2f824d/lib/client-assets.php#L55-L58

Given that this code runs on `wp_enqueue_scripts` / `admin_enqueue_scripts`, `$wp_scripts` **should** be available there.

To me that sounds more like a bug caused by some other plugin that accidentally removes that global variable.

I guess the code could first check whether the object is there, but that would also mean papering over an actual issue on the site.

**Comment by SeniorSpielbergo** [comment] 2019-07-02 17:50
@swissspidy What would you recommend? Is there a way for me to support you / identify which plug-in might be causing this issue?

**Comment by ehti** [comment] 2020-04-02 05:13
Hi @SeniorSpielbergo,

We discussed this in editor triage and couldn't really figure out how to reproduce this. Haven't seen this before either.

For now closing this, but if you're able to reproduce this after disabling all the plugins (preferably a fresh install), let us know and some steps to reproduce as well.

Thank you!

**Closed by ehti** 2020-04-02 05:13 UTC
Labels: Needs Testing
