### ISSUE TITLE
Dynamic blocks become unselectable when aligned left or right

### ISSUE THREAD

**Issue by maartenhunink** [WordPress/gutenberg#24653] opened 2020-08-19 11:54 UTC
When a dynamic block is aligned to the left or right, it is almost impossible to select it. This is only possible by clicking on a very narrow section right above the block. In that case the border which normal would wrap around the block, becomes a thin line above the block. Also the little toolbar is aligned all the way to the left.

I did a bit of digging and it seems like dynamic blocks add a `<div class="wp-block" data-align="right">` inside of the main `<div class="block-editor-block-list__block">`. While the other blocks wrap that same `<div class="wp-block" data-align="right">` around (outside) of the main `.block-editor-block-list__block`.

After changing this around for the dynamic block, it becomes selectable again and it now also shows the correct blue border/outline again.

**To reproduce**
1. Add the Latest Posts block to a post
2. Align it to the right.
3. Click somewhere else, and try to select the Latest Posts block again

**Expected behavior** 
After clicking on the block which is aligned to the right, the item becomes selected.

**Current behavior** 
A block which is aligned right/left can only be selected by clicking on a thing invisible area above the block. When selected it shows a blue border above and the toolbar is all the way to the left.

**Screenshots**
![Screenshot 2020-08-19 at 13 46 46](https://user-images.githubusercontent.com/106182/90631450-0db63880-e223-11ea-8f80-b74f81f75601.png)

**Editor version:**
- WordPress version: 5.5
- Bug is present with or without latest Gutenberg installed

**Desktop:**
 - OSX 10.15.6
 - Firefox 79

**Comment by talldan** [comment] 2020-08-20 03:28
Thanks for reporting the issue. It seems like the block's container is collapsing to 0 height, the blue line is the block's border.

The workaround for the moment would be to select the block using the List View/Block Navigation from the top toolbar, but agreed that this is less than ideal.

**Comment by maartenhunink** [comment] 2020-09-17 19:49
By the inactivity of this bug report it seems that this bug might not be impacting everybody? Because if this happens on every install I'd assume it would have been fixed already. Are other people also seeing this bug?

**Comment by maartenhunink** [comment] 2021-01-16 13:08
This bug has been fixed for the Latest Posts block, but is still broken for non core blocks. For instance any block created with ACF. Seems to be related to this bug report: https://github.com/WordPress/gutenberg/issues/25088

**Comment by youknowriad** [comment] 2021-03-08 08:55
Hey folks, I'm not able to reproduce this issue with Core blocks. Closing this in favor of #25088 for non core blocks.

**Closed by youknowriad** 2021-03-08 08:55 UTC
Labels: CSS Styling, [Type] Regression
