### ISSUE TITLE
WP 6.4 - Front End Does Not Work On Windows Machines

### ISSUE THREAD

**Issue by nick6352683** [WordPress/gutenberg#54849] opened 2023-09-27 02:37 UTC
### Description

This bug was also happening during the beta phases of WP 6.3, which was eventually fixed, but the issue is back - I have a feeling it has to do with caching.

In the backend all seems ok (although I only tested it for 2-3 minutes so far), but on the front end it's a nightmarish mess - Xampp php 7.4 Windows 10, no plugins active and  the newest default theme. Installed from the WP 6.4beta1 zip file.

Also tested on InstaWP using the WP Beta plugin, and everything is working as expected including my custom made hybrid theme.

With WP 6.3 the manual fix was doing the trick: In the file wp-includes/blocks/index.php file on line 49 we could change the code:

from
$files = $cached_files['files'];
to
$files = false;

Now this code is on line 65, but the old code replacement is not working with 6.4 beta1.

 

### Step-by-step reproduction instructions

1. Install WP 6.4 beta1 on a Windows PC
2. See the front end.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-09-28 12:13
Thanks for the report, @nick6352683.

Looking at the code you mentioned, it might be related to the following problem we've had in the past:

- #52391
- #52199

I was also able to reproduce the problem on my Windows machine:

- Fresh install WP6.3.1 using [Local app](https://localwp.com/)
- Intall Beta Tester Plugin
- Update to WordPress 6.4 Nightly (WordPress 6.4-beta1-56736)
- In the front end, some blocks are not styled

This issue was previously resolved in the following core changeset: https://core.trac.wordpress.org/changeset/56136

I'd like to find out why this problem started happening again.

**Comment by t-hamano** [comment] 2023-09-28 13:34
I have posted the cause and solution for this issue in a core ticket: https://core.trac.wordpress.org/ticket/59489

**Comment by nick6352683** [comment] 2023-09-28 15:40
@t-hamano , your fix works like a charm, your skills are amazing !!!

Thanks a million, I can now start testing my themes and plugins and prepare for WP 6.4...

**Comment by joemcgill** [comment] 2023-10-04 19:41
Anyone else experiencing this issue, please test and give feedback on https://core.trac.wordpress.org/ticket/59489. I've update the PR from @t-hamano in https://github.com/WordPress/wordpress-develop/pull/5409.

**Comment by t-hamano** [comment] 2023-10-05 13:53
Thank you for improving the patch and committing to core, @joemcgill!

I've confirmed that this issue has been resolved in the latest WordPress trunk, so I'd like to close this issue.

### Test Report

- Use [Local App](https://localwp.com/) on my Windows 11 machine
- Updated to WordPress 6.4 Beta 2 via the Beta Teter plugin
- The problem is reproduced with TT2, TT3, TT4 theme
- Updated to WordPress 6.4 nightly (WordPress 6.4-beta2-56785) via the Beta Teter plugin
- The problem is NOT reproduced with TT2, TT3, TT4 theme

**Closed as completed by t-hamano** 2023-10-05 13:53 UTC
Labels: [Type] Bug, [Type] Regression, OS Issues
