### ISSUE TITLE
Inserting blocks into columns sometimes inserts them in a new top level block below the columns

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#5982] opened 2018-04-04 19:44 UTC
## Issue Overview
Many times, clicking <kbd>(+)</kbd> inside a column and choosing a block type causes a new top level block to be inserted below the columns block.

## Steps to Reproduce (for bugs)
![kapture 2018-04-04 at 15 42 38](https://user-images.githubusercontent.com/353790/38330549-f22878c2-381e-11e8-86cc-9cfe7df96ad6.gif)

## Expected Behavior
Block is inserted in the column where the <kbd>(+)</kbd> was.

## Current Behavior
Sometimes inserts below.

**Comment by SuperGeniusZeb** [comment] 2018-04-04 19:48
Related to or a duplicate of #5772.

**Comment by karmatosed** [comment] 2018-04-05 16:26
Closing as I think this is the same as #5772, if not we can reopen.

**Closed by karmatosed** 2018-04-05 16:26 UTC
