### ISSUE TITLE
Make unchecked tooltip option permanent please

### ISSUE THREAD

**Issue by stefanos82** [WordPress/gutenberg#14512] opened 2019-03-19 12:19 UTC
It's so annoying, really.

I use the latest WordPress and every single time I try to edit a post or a page, this thing appears right in front of my face.

I go to `Hide more tools & options`, then `Options`, uncheck `Enable Tips`, do my job, save and close the dashboard.

After a while, I return back to edit new content and the tooltip is back.

I'm seriously considering installing Classic Editor until this whole thing gets fixed and become much more stable than already is.

**Comment by youknowriad** [comment] 2019-03-21 08:13
Hi there! sorry for the trouble. I can't reproduce personally. This setting is persisted on the browser though (local storage).

Which means it might happen again if you change browsers, computers or things like that.

**Comment by stefanos82** [comment] 2019-03-21 09:56
It can happen with the same browser; just edit a post or a page, save the changes, logout, close the browser, open it again, relogin to implement new changes, boom - the popup is right in front of your face.

**Comment by youknowriad** [comment] 2019-03-21 10:01
I don't reproduce, which browser are you using, is "local storage" disabled or not available in your browser for some reason?

**Comment by stefanos82** [comment] 2019-03-21 10:42
I use Firefox 60.5.1esr (64-bit) and 72.0.3626.109 on debian 64-bit testing.

Now about local storage, I have no idea. I haven't touched them and I use them as they come by default.

**Comment by steelbridge-io** [comment] 2019-03-26 18:59
The persistent tool-tip "can" be experienced with a browser cache extension where "local storage" is set to be cleared upon page refresh or manually per the extension option to "clear cache". In some browser extensions for Mozilla and Chrome, there is a list of browser storage destinations to clear for every "clear cache" process either manual or upon page refresh. Prevent "local storage" from being cleared and the tool-tip won't appear after refresh.

**Comment by jj-wd** [comment] 2019-03-26 19:31
For me, the tooltips appear when I move away from page editing to let's say updating a plugin and then back to page editing. No cache clearing or anything in between. Firefox 65.0.2 on Win 64.

Conceptional, I wonder why storing this per browser would be a good idea. I mean, many WordPress users are Web Developers, we clear the cache every other minute. Why not store stuff like this in the database?

**Comment by aduth** [comment] 2019-04-22 14:28
Closing in favor of technical proposal at #15105

As described there, I expect the root underlying cause of the preference not "sticking" to be one of (a) switching browsers (unique storage between browsers), (b) using private browsing tabs (storage cleared between sessions), or (c) the same user across a network of sites (storage unique by domain).

**Closed by aduth** 2019-04-22 14:28 UTC
Labels: [Status] Needs More Info
