### ISSUE TITLE
3.0 broked columns

### ISSUE THREAD

**Issue by dvdobrovolskiy** [WordPress/gutenberg#7132] opened 2018-06-04 21:43 UTC
update to 3.0 broke columns. Even little edit make 2 columns design now goes one under other. Columns consist of text only.

Even new page -> new columns - and they goes under each other

Twenty Seventeen default

**Comment by youknowriad** [comment] 2018-06-04 21:44
duplicate of #7127 fixed by #7128

**Closed by youknowriad** 2018-06-04 21:44 UTC
