### ISSUE TITLE
FlexItem wraps a div around items

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#36107] opened 2021-11-01 08:23 UTC
Extracting from https://github.com/WordPress/gutenberg/pull/35857#issuecomment-952483679, we had some problems using the FlexItem component for spacing things out. Quoting from the converesation:

<blockquote>
The problem with the Flex component is that FlexItem wraps an element around our buttons, so instead of having

```
<Flex>
    <button />
    <button />
</Flex>
```
which would allow us to style the buttons as flex children, we end up with

```
<Flex>
    <div>
        <button />
    </div>
    <div>
        <button />
    </div>
</Flex>
```
and because Flex is set up to use CSS-in-JS, we can't just hook some extra CSS to its classnames. We can pass the styles inline to FlexItem, but at that point it's easier (and much less messy) to not use Flex at all, and attach the CSS directly to our LinkControlTransforms markup.
</blockquote>

and

<blockquote>
Yeah, seems like FlexItem should have an `as` prop:
```jsx
<FlexItem as={ Button }>
```
But it doesn't right now. It always renders as a `View`, which is a `div`.
</blockquote>

Feel free to edit the description or title of this ticket if need be.

**Comment by ciampo** [comment] 2021-11-30 14:51
> Yeah, seems like FlexItem should have an `as` prop: ```jsx ``` But it doesn't right now. It always renders as a `View`, which is a `div`.

That shouldn't be the case, and I'd be curious to know why this didn't work out for the folks quoted above.

`FlexItem` props [are of type `WordPressComponentProps`](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/flex/flex-item/component.js#L9), which means that [the component accepts the `as` prop](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/ui/context/wordpress-component.ts#L22).

You can see the `as` prop being used on the `FlexItem` component in the [`ItemGroup` "Complex Layouts" example](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-itemgroup--complex-layouts).

To double-check this, I also quickly put together this example in Storybook:

```jsx
<Flex>
	<FlexItem as="button">Item</FlexItem>
	<FlexItem as="button">Item</FlexItem>
</Flex>
```

And everything seems to work as expected:

<img width="997" alt="Screenshot 2021-11-30 at 15 49 06" src="https://user-images.githubusercontent.com/1083581/144069348-96f9bc6a-6bd5-47f1-acf3-a2e954c7e5d5.png">

---

cc @tellthemachines and @talldan (since the quoted comments at the top of this issue are yours).

**Comment by talldan** [comment] 2021-12-01 01:35
I'll be honest, I probably didn't try it, I looked at the code and made a false assumption. Sorry about that!

If it already works, that's great, feel free to close the issue.

edit: although it would be great to have this prop documented in the README too.

**Comment by ciampo** [comment] 2021-12-01 09:33
> edit: although it would be great to have this prop documented in the README too.

Thank you for the feedback, @talldan — it's really appreciated!

In the documentation for our components, we usually only list the props that are specific to that component, and therefore props like `as` are not listed. We are definitely aware of the fact that the documentation could be better, and we're looking at ways to generate docs (rather than updating them manually).

**Closed as completed by ciampo** 2021-12-01 09:33 UTC
Labels: [Feature] UI Components, [Package] Components, [Feature] Component System

**Comment by tellthemachines** [comment] 2021-12-13 05:06
> That shouldn't be the case, and I'd be curious to know why this didn't work out for the folks quoted above.

@ciampo the issue is not the ability to choose the tag rendered by FlexItem, it's with FlexItem rendering a tag at all. We shouldn't need an extra markup element wrapped around each flex child.

The other issue is we often need to add specific properties to one or more of the flex children, e.g. `flex-grow` or `flex-basis`. Using Flex and FlexItem, we can pass those properties as inline styles to FlexItem, but if the point of these components is to avoid writing additional CSS, then that sort of defeats the purpose.

**Comment by talldan** [comment] 2021-12-13 05:17
> the issue is not the ability to choose the tag rendered by FlexItem, it's with FlexItem rendering a tag at all. We shouldn't need an extra markup element wrapped around each flex child.

I don't think this would be an issue. Something like:
```jsx
<FlexItem>
    <Button variant="primary" />
</FlexItem>
```

becomes:
```jsx
<FlexItem as={ Button } variant="primary" />
```

**Comment by tellthemachines** [comment] 2021-12-13 06:49
Oooh, can we pass actual components to `as`? Interesting. I suppose the wrapper is a non-issue then.

**Comment by talldan** [comment] 2021-12-13 06:56
Hopefully! That's how I've seen it work in other places. Props should be forwarded to the `as` component too (which is something I always forget).

**Comment by ciampo** [comment] 2021-12-13 11:39
> Hopefully! That's how I've seen it work in other places. Props should be forwarded to the as component too (which is something I always forget).

That should be the case — let us know in case it's not (@tellthemachines the couple of examples that I [listed above](https://github.com/WordPress/gutenberg/issues/36107#issuecomment-982709763) should also help)

> The other issue is we often need to add specific properties to one or more of the flex children, e.g. flex-grow or flex-basis. Using Flex and FlexItem, we can pass those properties as inline styles to FlexItem, but if the point of these components is to avoid writing additional CSS, then that sort of defeats the purpose.

Noted, thank you for the feedback!
