### ISSUE TITLE
In Editor Inserter Menu, 'Paragraph' block is kept at the top of 'Most Used'.

### ISSUE THREAD

**Issue by shinyabw** [WordPress/gutenberg#11400] opened 2018-11-02 11:30 UTC
**Describe the bug**

In Editor Inserter Menu, 'Paragraph' block is kept at the top of 'Most Used'.

**To Reproduce**
1. Go to 'Editor Inserter Menu'
2. Use 'Particular-non-Paragaraph block' more than 'Paragaraph' block
3. Go to 'Editor Inserter Menu.'
4. See error; 'Paragraph' block is still shown (kept) at the top of 'Most Used'.

**Expected behavior**

Once a particular block is used more than 'Paragraph' block, this 'Paticular' block should be shown before 'Paragraph' block.

**Screenshots**

![most-used](https://user-images.githubusercontent.com/36391308/47912774-18cc9700-dedd-11e8-867a-9ea578fee66f.jpg)

**Desktop (please complete the following information):**
 - OS: [Mac 10.13.6]
 - Browser [Firefox]
 - Version [63.0.1]

**Additional context**
- 4.2.0-rc.1

**Comment by designsimply** [comment] 2018-11-02 22:42
Thank you for testing! I tested with WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and can confirm that the paragraph block always appears first under "Most Used" in the inserter. I also found that this is by design. You can see it mentioned in https://github.com/WordPress/gutenberg/pull/2836 (2nd paragraph).

I am closing this issue and if you feel strongly that it would be good to get another design feedback on it, please let me know and we can re-open.

**Closed by designsimply** 2018-11-02 22:42 UTC
Labels: Needs Testing

**Comment by shinyabw** [comment] 2018-11-05 04:44
@designsimply Thank you for testing this. Thank you for finding [#2836](https://github.com/WordPress/gutenberg/pull/2836). I see... **Paragraph** block is still hardcoded. Since it is intentional, I would like to think about this issue a bit more.

Quoting from [#2836](https://github.com/WordPress/gutenberg/pull/2836):
> This also keeps a "highscore table" of block usage, so in a future PR, we can use this data to display the user's most frequently used blocks next to the inserter, where we currently hardcode paragraph and image.
