### ISSUE TITLE
Documentation/Tutorial issues/enhancements

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#6185] opened 2018-04-15 14:13 UTC
I just chatted to Tammie at WordCamp London where she encouraged me to open an issue.

## Overview of issue

The docs seem incomplete and confusing for developers coming to the handbook to work out how to create a custom block for the first time.

## Background

I confess that I've never actually created a block.  Rather then use one of the existing scaffolds/boilerplates I decided I'd try starting by writing a simple plugin that used ES5 JS to create a simple block.

I thought I'd find the information I needed to do this in the Handbook. But I quickly ran into dead ends and realised that the handbook does not currently help someone do this (perhaps this is a not what the handbook is intended for?)

## (Some) specific issues

1. I see no reference to or documentation of the `enqueue_block_editor_assets` and `enqueue_block_assets` hooks
1. [This page](https://wordpress.org/gutenberg/handbook/blocks/) sells itself as a tutorial, but it really isn't
1. The page linked above links to the Extensibility page which then links to the Tutorial, sending you round in a loop.
1. The footer next/prev (or possibly the sidebar nav) is broken in some places (e.g. at the bottom of [this page](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/), "Templates" does not exist in the sidebar nav on the left
1. There seems to be a PHP `register_block_type` function that is shown on [this page](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/) but that doesn't seem to be in the block API (because it's probably not part of the block API as such) or in the reference section

## Questions/what next?

I decided to open this rather than to dive into creating PRs because I'm not sure just going and adding/changing a load of stuff at this point is the right thing to do.

Questions then:

1. Is this handbook under review or being updated by someone else at the point? Does someone else have responsibility for updating the handbook? Or if I made a bunch of PRs are they likely to be accepted?
2. Is it worth doing this NOW or should I wait until the APIs are settled. If I updated the "tutorial" now would it soon be out of date?
3. Is the Handbook even the right place for a tutorial, or are you happy with the community writing tutorials on their own sites and linking the handbook off to them?

Thanks

**Comment by theleemon** [comment] 2018-04-15 14:39
Agreed. The documentation needs a STEP-BY-STEP tutorial on how to build a plugin that registers a custom simple block using both ES5 and ES6.

**Comment by gziolo** [comment] 2018-04-17 06:09
> There seems to be a PHP `register_block_type` function that is shown on this page but that doesn't seem to be in the block API (because it's probably not part of the block API as such) or in the reference section

It is part of the API. It is required to properly register dynamic block. Those that are rendered on the server using `render_callback`.

**Comment by pento** [comment] 2018-04-17 07:39
I fixed the ordering of the previous/next footer links: https://meta.trac.wordpress.org/changeset/7118

**Comment by rosswintle** [comment] 2018-04-17 09:48
Ah. OK. So, I'm gonna raise my hand ✋ and say that I got confused here because of a change that seems to have happened since I last tried to create a block: it looks like the PHP `register_block_type` function has replaced the use of the `enqueue_block_editor_assets` and `enqueue_block_assets` hooks.  `register_block_type` seems to have been around since v0.6 so not sure why so many block building tutorials (e.g. [this](https://modularwp.com/how-to-build-gutenberg-blocks/) and [Ahmad's Boilerplate](https://github.com/ahmadawais/Gutenberg-Boilerplate/blob/master/block/01-basic/index.php) ) seem to reference the `enqueue_*` hooks

Realising this has certainly helped, as has @pento's change (thank you!). So my specific issues 2, 3, and 4 have all been fixed by this, I think.

> [`register_block_type`] is part of the API. It is required to properly register a dynamic block. The one that is rendered on the server using render_callback.

I can't see this function documented anywhere (yet?). Have I missed it? Does it need adding?

I also find the [API page](https://wordpress.org/gutenberg/handbook/block-api/) really hard to navigate and digest.  The visual hierarchy really doesn't aid comprehension.  The first few paragraphs demonstrate this...

<img width="662" alt="screen shot 2018-04-17 at 10 42 47" src="https://user-images.githubusercontent.com/1532368/38862380-a972a3ec-422c-11e8-9a51-cf096a69da1b.png">
 
I'll try to take some time to make some PRs for some of this. But someone else may need to do some work on the API documentation design/styling - is this auto-generated from code at all?

Thanks - we are making this better! 👍

**Comment by gziolo** [comment] 2018-04-24 08:03
> I'll try to take some time to make some PRs for some of this. But someone else may need to do some work on the API documentation design/styling - is this auto-generated from code at all?

Gutenberg handbook is manually crafted using markdown and converted to HTML using some tooling on WordPress.org. There is a plan to introduce other docs for code which would be machine-generated.

**Comment by gziolo** [comment] 2018-04-24 08:06
>  it looks like the PHP register_block_type function has replaced the use of the enqueue_block_editor_assets and enqueue_block_assets hooks. register_block_type seems to have been around since v0.6 so not sure why so many block building tutorials (e.g. this and Ahmad's Boilerplate ) seem to reference the enqueue_* hooks

The issue is with community tooling which isn't updated with the recent recommendations in Gutenberg handbook. `register_block_type` helps to keep implementation details of using`enqueue_block_editor_assets` and `enqueue_block_assets` hidden for the plugin developer. They still can use it, but it is reserved for very advanced use cases. Otherwise, it should be enough to use `register_block_type`.

**Comment by chrisvanpatten** [comment] 2018-11-08 16:10
As a note we'd like to include this in the new designer/dev handbook. If anyone wants to step up to write this tutorial, that would be super cool :)

**Comment by mkaz** [comment] 2019-01-23 17:47
I think this issue is old and not actionable in the current state.
There now exists two tutorials which cover almost all of the above with examples and explanations

* [Getting Started with JavaScript](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/javascript/)

* [Block Tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/writing-your-first-block-type/)

The auto generation of documentation looks to be addressed in [PR #13329 ](https://github.com/WordPress/gutenberg/pull/13329) by @nosolosw 

So I think the main problems raised in this Issue have been or will be addressed. I'm going to mark as closed and please reopen, or add new issues if there is something I missed that still needs addressing. I'll be glad to help.

**Closed by mkaz** 2019-01-23 17:47 UTC
Labels: [Type] Documentation, [Type] Question
