### ISSUE TITLE
Fonts manually upload from backend do not show in frontend

### ISSUE THREAD

**Issue by bogao** [WordPress/gutenberg#60420] opened 2024-04-03 11:44 UTC
WP Version: 6.5
Action: Uploading font files from backend (FTP, etc.).
Expected: Fonts shown in the frontend (Font manager UI from Style panel)
Actual: Not shown.

**Comment by creativecoder** [comment] 2024-04-05 02:40
This was discussed a bit here: https://github.com/WordPress/gutenberg/issues/59417#issuecomment-1971947978

Fonts files use metadata attached to them to generate the css `@font-face` declaration, everything from [accent-override to unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face), but at a minimum the font-family name that should be used. So for a direct upload to work, there would probably need to be a json file or similar included with the font file(s) that defines its font-face properties. This would match how fonts are included in themes, with a font file and theme `fontFamilies` and `fontFace` properties defined in theme.json.

@bogao Is there a particular use case you're thinking of for being able to install fonts directly through the file system?

**Comment by creativecoder** [comment] 2024-04-05 02:59
I think this is a duplicate of https://github.com/WordPress/gutenberg/issues/59102

**Comment by skorasaurus** [comment] 2024-04-05 18:04
Thanks for reporting; this is a duplicate of https://github.com/WordPress/gutenberg/issues/59102 where you can follow its progress.

**Closed as completed by skorasaurus** 2024-04-05 18:04 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Feature] Font Library
