### ISSUE TITLE
Media and text Block : Image is getting blurred when we use "Thumbnail and Medium" size options

### ISSUE THREAD

**Issue by kushh23** [WordPress/gutenberg#45130] opened 2022-10-19 21:34 UTC
### Description

Hey there,

While creating a blog post I notice that the Media and text block is having some issues with image size options. The image that we upload on the block gets blurred with Thumbnail and Medium size options but works fine with Large and Full-size options.

Thanks

### Step-by-step reproduction instructions

1. Go to Post/pages add new and add the **Media and text block**.
2. Upload an Image and select the image size option ( available in the right corner) as **Full size** and **Large**.
3. You will observe that the image is not blurred (yet).
4. Now select the other two options - **Thumbnail and Medium**. 
5. You will observe that the image got blurred. 

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/110405452/196808032-a9036b79-a00a-4972-bd6e-41a03cd2c694.png)
![image](https://user-images.githubusercontent.com/110405452/196808136-743e3358-fee4-4ccb-899f-e4d1236c72d7.png)
![image](https://user-images.githubusercontent.com/110405452/196808264-44a8eed0-ecf6-4560-8744-ec2238a52cd6.png)
![image](https://user-images.githubusercontent.com/110405452/196808377-ddbd5833-1351-490b-aee7-4dbe64667143.png)

### Environment info

WP version: 6.0.3
PHP : 7.4
Theme Name: Twenty Twenty-Two (twentytwentytwo)
Theme version: 1.2
Plugins: None installed ( a clean TasteWP instance ) 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment] 2022-10-20 01:26
Also seeing it on GB trunk.

Maybe it's because the image is being resized with `-150x150.jpg`, but the CSS of the container stretches it to the maximum width ?

```
.wp-block-media-text .editor-media-container__resizer {
    width: 100% !important;
}
```

**Comment by andrewserong** [comment] 2022-10-20 01:27
Thanks for opening this issue @kushh23! I can confirm that the behaviour works the same for me, testing with Gutenberg `trunk`.

I believe what's going on here, is that with the Image block, when you adjust the Image Size control, the dimensions of the image block are updated as well as swapping out the image used for a lower resolution version of that image.

In the Media & Text block, the width of the media area is controlled by the "Media Width" slider, rather than determined by the physical dimensions of the image used. So in this case, adjusting Image Size to select a thumbnail or medium version of the image swaps out the image being used to a lower resolution version, but does not update the "Media Width" slider. The width is also controlled by a `grid-template-columns` percentage, so doesn't quite match up directly with pixel values (that are used in the Image block).

In this case, is the desired result from the block that you're adding that you'd expect the media width to change to match the dimensions of the Medium or Thumbnail image when you select it from the drop-down list? If so, that sounds like a nice idea for an enhancement to me, so I'll add the enhancement label to this one.

One thing to watch out for if you're using much smaller images is that by default the Media & Text block will be stacked on mobile, so smaller images will be stretched to the full width in that viewport size. Depending on the layout, it might be worth trying out switching off "Stack on mobile" if you want to preserve media and text being side-by-side in that context. Also, depending on the site you're building, if you're working with lower resolution or smaller images, it might be worth trying out a layout using the Columns block, as typically Media & Text is usually used with larger images as far as I'm aware.

**Comment by kushh23** [comment] 2022-10-26 18:01
Hey @andrewserong and @ramonjd ,

Thanks for looking into this.

Have a great day!

**Comment by jordesign** [comment] 2023-08-29 03:25
Closing this issue as it will be addressed as part of https://github.com/WordPress/gutenberg/issues/29362

**Closed as not planned by jordesign** 2023-08-29 03:25 UTC
Labels: [Type] Enhancement, [Block] Media & Text
