### ISSUE TITLE
Drag & Drop within the block navigation

### ISSUE THREAD

**Issue by daveloodts** [WordPress/gutenberg#18630] opened 2019-11-20 12:30 UTC
It's still difficult to drag & drop blocks within the editor: certainly using more overlapping blocks like the Group Block; or a general Section Block.
Sometimes it's just hard to find that exact pixel place point, where you can drag the wanted block.

Maybe the Block Navigation can be played out more in 2 ways:
1- drag and drop blocks within the section
2- collapse board to have a full block overview over the page

Don't know if this is mentioned before, or is even doable.

**Comment by youknowriad** [comment] 2019-11-20 12:31
Duplicate of #11408

**Closed by youknowriad** 2019-11-20 12:31 UTC
