### ISSUE TITLE
Support an optional namespace parameter for hasAction/hasFilter (matching core)

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7803] opened 2018-07-09 07:42 UTC
@adamsilverstein commented on [Tue Apr 10 2018](https://github.com/WordPress/packages/issues/104)

See: https://github.com/WordPress/packages/issues/78#issuecomment-379860775

**Comment by youknowriad** [comment] 2019-01-26 15:48
Seems like a duplicate of #7816

**Closed by youknowriad** 2019-01-26 15:48 UTC
Labels: [Package] Hooks, [Type] Bug
