### ISSUE TITLE
Table block: cut, copy, paste entire rows

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15822] opened 2019-05-24 20:30 UTC
The Table block currently only allows the selection of one cell at a time. It does not allow selection of an entire row. This feature would be beneficial for people who need to cut and paste entire rows into different rows.

User should be able to select multiple cells within a row to cut, copy, and paste.

**Google Docs example:** 

![cut](https://user-images.githubusercontent.com/617986/58354969-cd051f00-7e27-11e9-96c7-d58f9245f9ad.gif)

**Comment by mapk** [comment] 2019-05-24 20:31
Initially noted here https://github.com/WordPress/gutenberg/issues/6923 by @helen.

**Comment by mapk** [comment] 2019-06-25 16:49
[In today's triage on slack](https://wordpress.slack.com/archives/C02S78ZAL/p1561480954357700), @karmatosed discussed another potential use case. 

How will this work if the user wanted to copy data over from another application? Let's say a user wants to copy a table of data over from Google spreadsheet. Could they copy over all the data in one go, and the data will conform to the same structure in the Table block?

**Comment by talldan** [comment] 2019-07-19 04:42
Closing as a duplicate of #12116. Copying the comments over there.

**Closed by talldan** 2019-07-19 04:42 UTC
Labels: Needs Dev, [Block] Table, [Type] Enhancement
