### ISSUE TITLE
[4.3] pasting link onto an image doesn't work

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#11934] opened 2018-11-15 19:06 UTC
### Describe the bug
Pasting a link onto an image that has focus does not add that link to the image.

(in Gutenberg if you have text highlighted, you can paste a link directly to the text. This doesn't work with images. It does work in the Classic Editor).

### To Reproduce
1. Have a link on the clipboard.
2. Add an image to Gutenberg.
3. Click on the image to give it focus.
4. Paste (in Windows, CTRL-V).
5. Note that the image does not get the link.

### Expected behavior
- The "Link to" should become "Custom URL"
- The "Link URL" should become whatever the clipboard contents were.

**Comment by designsimply** [comment] 2018-11-15 20:57
Testing note: check to see if this is a regression for the plugin or not.

**Comment by La-Geek** [comment] 2018-11-17 18:50
Imho, if this would be a function of the block image, there would exist an icon "insert link" in the visual editor mode.

However: this is a missing feature, I do agree with @GlennMartin1

**Comment by GlennMartin1** [comment] 2019-03-20 13:27
This issue persists in Gutenberg 5.3.

**Comment by noisysocks** [comment] 2020-02-06 05:32
Confirmed that the classic editor has this functionality and that latest Gutenberg does not.

**Comment by jordesign** [comment] 2023-08-25 04:20
Confirming this issue still exists in WP6.3 - but closing as a duplicate of this one:
https://github.com/WordPress/gutenberg/issues/35839

**Closed by jordesign** 2023-08-25 04:20 UTC
Labels: [Type] Enhancement, [Feature] Raw Handling, Backwards Compatibility, [Block] Image
