### ISSUE TITLE
Setting image to > 75% width makes it break out of block boundary & causes horizontal scrolling

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#17795] opened 2019-10-07 02:58 UTC
**Describe the bug**
I added a Group Block and set it to Full width. Within the Group Block, I added a Paragraph block and a Columns Block with 2 columns. In the Columns block I added a Paragraph block and an image block.

If I set the image width to greater than 75%, the image extends outside the block boundaries and causes horizontal scrolling.

Have tested on TwentyTwenty:
Vid - https://cl.ly/87c20a637044

TwentyNineteen:
Vid - https://cl.ly/fae20963cdfe

And multiple other themes. All had the same issue.

Regardless of whether you set the Group Block width to Wide, Full or nothing, the same issues occurs.

Here's a screenshot of an image in both columns, with the same issue occurring:

<img width="1920" alt="screenshot_228" src="https://user-images.githubusercontent.com/2078245/66281932-38e4b180-e909-11e9-9c57-bc6a436299e5.png">
:

**To reproduce**
1. Add Group Block
2. Insert Columns block in Group Block
3. Add Paragraph Block with text to left column
4. Add image Block with a large image, to right column
5. Click on image and set width to 75% or 100%
6. See image expand past block boundaries.

**Expected behavior**
Content should never expand outside of block boundaries

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox Quantum 69.0.2
 - Version: WP 5.3-beta2-46416

**Comment by CreativeDive** [comment] 2019-10-07 06:22
#17685 could be a related issue.

**Comment by maddisondesigns** [comment] 2020-02-26 02:45
This still breaks in WP 5.4 beta 3

**Comment by torounit** [comment] 2020-07-21 06:05
This occurs even if the group block does not exist.

1. Add Columns block
2. Add large Image to column block using an image block. On the other side, insert some paragraph.
3. Set image size.

![](https://user-images.githubusercontent.com/1908815/88018865-84e4a800-cb63-11ea-970c-18003cd2f877.png)

need to set an appropriate value for max-width.

**Comment by paaljoachim** [comment] 2023-05-22 13:26
I tested this with Gutenberg plugin version 15.8.1.
The issue is still valid.

**Comment by jordesign** [comment] 2023-08-25 03:02
Closing this as a dupe of https://github.com/WordPress/gutenberg/issues/12168 - and consolidating there.

**Closed by jordesign** 2023-08-25 03:02 UTC
Labels: [Type] Bug, [Block] Image
