### ISSUE TITLE
WordPress 5.0.3 started inserting unwanted <p>

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#13345] opened 2019-01-16 18:03 UTC
Something like this is being returned in PHP render callback of a block (I removed some markup, I don't know if it was important):

```
function some_render_callback(){
	echo '<div class="swiper-slide">
		<img src="">
		<div class="title">Some title
			<div class="tagline"><p>Some tagline</p></div>
		</div>
		<div class="content"><p>Some content.</p></div>
	</div>';
}
```

And this I see in the source code:
```
<div class="swiper-slide">
	<p><img src=""></p>
	<div class="title">Some title</p>
		<div class="tagline"><p>Some tagline</p></div>
	</div>
	<div class="content"><p>Some content.</p></div>
</div>
```

So the image got wrapped in `<p>` and there is one invalid closing `</p>` that WordPress added.

None of these changes should be made by WordPress.

**Comment by spencerfinnell** [comment] 2019-01-16 18:31
For a while actually:

https://github.com/WordPress/gutenberg/issues/9528
https://github.com/WordPress/gutenberg/issues/12668
https://github.com/WordPress/gutenberg/issues/9056
https://github.com/WordPress/gutenberg/issues/12530

It's very easy to reproduce and currently makes dynamic blocks annoying to develop: https://gist.github.com/spencerfinnell/df70436ec9a711ca9e9d00f1492e2c91

This does not happen for core blocks because they generate a single string of HTML markup: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/index.php#L29

However this is not a realistic solution for more complex blocks where other partials/views are likely to be loaded in.

**Comment by youknowriad** [comment] 2019-04-22 11:51
This is a duplicate of #12530 and the core ticket seems fixed now.

**Closed by youknowriad** 2019-04-22 11:51 UTC
Labels: Block API, Needs Technical Feedback, [Type] Plugin / Theme Interoperability
