### ISSUE TITLE
Taxonomy meta box title language

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#8449] opened 2018-08-03 15:00 UTC
**Describe the bug**
When a users admin language is different from the default site language, the Categories and Tags meta box title in the Gutenberg editor sidebar initially show in the users admin language but as soon as one is clicked to open the meta box, the title will jump to the default site language.

The same thing happens with custom taxonomies, but other meta boxes, like Featured Image, do not suffer this issue. Also the taxonomy meta box content remains in the user admin language. Only the title changes. See screen shots before and after.

Gutenberg 3.4.0

**To Reproduce**
1. Set a different language (than the general site language) in your user Profile
2. Edit a post and see that the taxonomy meta boxes have titles in the alternative language set above
3. Now click on any taxonomy meta box title to toggle open/close
4. Notice that the title switches to the site default language

**Expected behavior**
Meta boxes keep their user admin language.

**Screenshots**
Before toggling the meta boxes, titles are English (user admin language) :
![schermafdruk van 2018-08-03 16-56-50](https://user-images.githubusercontent.com/1184853/43649890-a2a445d6-973e-11e8-81d4-2114e2fad089.png)

After toggling, taxonomy titles switched to French (site language) :
![schermafdruk van 2018-08-03 16-57-52](https://user-images.githubusercontent.com/1184853/43649945-c28217ca-973e-11e8-975b-ffdbc9c25336.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Google Chrome 68.0.3440.84

**Comment by youknowriad** [comment] 2018-08-08 10:33
The problem is that the preloaded API request is using the user's locale while the REST API triggered from the client is using the site's locale.

@danielbachhuber Any idea how to fix this? Do we have a global locale argument for REST API endpoints or can we make the REST API use the user's locale if the user is authenticated?

**Comment by danielbachhuber** [comment] 2018-08-08 13:26
> can we make the REST API use the user's locale if the user is authenticated?

This seems like a more appropriate solution to me. We'd make this change in core WordPress.

**Comment by danielbachhuber** [comment] 2018-10-18 17:41
Closing in favor of https://core.trac.wordpress.org/ticket/44758

**Closed by danielbachhuber** 2018-10-18 17:41 UTC
Labels: REST API Interaction, [Type] Bug, i18n
