### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by helen** [WordPress/gutenberg#37] opened 2017-02-09 19:26 UTC
As always, I get the great honor of reporting that some of this doesn't appear to work in Firefox, which is my primary browser. I use the developer edition.

Things that don't work as compared to Chrome:
* Up/down reordering
* Webfonts

Things that do:
* Image sizing / placement
* Text editing + new paragraph block

Things that don't work in either (assuming expected):
* Adding a new block beyond the ability to hit enter for a new paragraph block
* Filtering/searching of block types
* Text alignment

**Comment by JDGrimes** [comment] 2017-02-09 19:41
> Up/down reordering

See #36 😄

**Comment by jasmussen** [comment] 2017-02-10 12:05
Thank you @JDGrimes for fixing that 🎉 

I can't reproduce your webfonts issue though, Helen, can you clarify? Here's what I'm seeing:

<img width="1312" alt="screen shot 2017-02-10 at 13 02 35" src="https://cloud.githubusercontent.com/assets/1204802/22826174/54dd9678-ef91-11e6-9ed0-1ce3fafe8ecb.png">

Note, it's possibly working for me because I have both Merriweather and SF UI fonts installed on my machine. 

Inline controls, insertion dialog, those are dummy elements so far, mostly to get a feel for the UI. I opened a separate ticket to discuss how far to take this prototype: https://github.com/WordPress/gutenberg/issues/51

**Comment by helen** [comment] 2017-02-10 21:06
Here's what I see:

![screen shot 2017-02-10 at 4 04 18 pm](https://cloud.githubusercontent.com/assets/906334/22844133/ac5a1084-efaa-11e6-9a6b-2e7682f32296.png)

These errors appear in my console:

```
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Merriweather" style:normal weight:bold stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nshHwsiXhsDb0smKjAA7Bek.woff2  css:58:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Merriweather" style:normal weight:bold stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nshHwsiXhsDb0smKjAA7Bek.woff2  css:58:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Merriweather" style:normal weight:bold stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nshHwsiXhsDb0smKjAA7Bek.woff2  css:58:12
downloadable font: rejected by sanitizer (font-family: "Merriweather" style:normal weight:bold stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nshHwsiXhsDb0smKjAA7Bek.woff2  css:58:12
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: rejected by sanitizer (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
```

**Comment by jasmussen** [comment] 2017-02-13 08:52
That is super interesting, and turns out to be a bit of a 🐰🕳

In the past there seems to have been a bug specifically with the Google Fonts version of Merriweather, see https://bugzilla.mozilla.org/show_bug.cgi?id=1239176

But that bug should be fixed. However this ticket suggests that Nightly and Aurora versions of Firefox may be having this issue still today: https://bugzilla.mozilla.org/show_bug.cgi?id=1239176 — any chance you're running one of those versions?

**Comment by helen** [comment] 2017-02-14 14:56
I use the developer edition which is Aurora - currently at 53.0a2 (2017-02-09).

**Comment by jasmussen** [comment] 2017-02-14 15:39
That could explain the issue. Seems like it's upstream with either Google Fonts or with Firefox.

That said, it's probably worth discussing whether to use Merriweather in the first place. I think it's lovely, but Georgia might do fine as well.

**Comment by jasmussen** [comment] 2017-02-20 12:01
Closing for now, let's reopen if it isn't fixed in Google Fonts or Aurora.

**Closed by jasmussen** 2017-02-20 12:01 UTC
