### ISSUE TITLE
Query Loop Post Template block add Link to Post option

### ISSUE THREAD

**Issue by HairyCream** [WordPress/gutenberg#35288] opened 2021-10-01 11:15 UTC
## What problem does this address?

As at WP 5.8.1 with Gutenberg 11.6.0

The Query Loop Post Template block can have various Post element blocks included, such as Post Title, Post Content, Post Excerpt, etc.
Some of these Post element blocks often have an option to set a link to the selected Post. Such as ...
Post Title uses "Make title a link"
Post Featured Image, Post Date use "Link to post"
Post Excerpt gives an option "Show link on a new line", although the resulting Post Excerpt container itself is not a link.

This leaves the Post Template block container with potentially multiple links to the post, and much of the container area that would not respond to a click/tap with a post link.

For mobile users especially this can be frustrating as they try to find which part of the Post Template container reacts.

## What is your proposed solution?

Add an option to the Post Template block to set "Link to post"

**Comment by ocean90** [comment] 2022-02-14 16:16
Marking as a duplicate of #38014 which has a bit more information and a linked pull request #38012.

**Closed as completed by ocean90** 2022-02-14 16:16 UTC
Labels: [Status] Duplicate, [Block] Query Loop
