### ISSUE TITLE
Cant drag and drop blocks inside column

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#12059] opened 2018-11-19 12:36 UTC
**Describe the bug**
I can't drag and drop a block that lives inside a column

**To Reproduce**
1. create columns block
2. add a few blocks inside column
3. try to move a block
4. nothing happens

**Expected behavior**
I expect it to work the same way it does with non-nested blocks.

**Screenshots**
Ignore the crazy colors, I've tried this with an empty editor stylesheet as well. Notice that I move blocks without any issues when they are not in the column block.

![draghandle2](https://user-images.githubusercontent.com/40266703/48707509-ff775a80-ebff-11e8-947e-ce3dc6beba9a.gif)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrom
 - Version 70

**Additional context**
GB 4.4

**Comment by GlennMartin1** [comment] 2018-11-19 13:30
Confirmed. Same here since 4.4.

**Comment by designsimply** [comment] 2018-11-21 23:17
Thanks for the report! Tested and confirmed this is fixed in `master` and should appear in version 4.6. See #12159.

**Closed** 2018-11-21 23:18 UTC
Labels: Drag and Drop, [Block] Columns, [Type] Bug
