### ISSUE TITLE
Expand on click lightbox is activated on subsequent block images 

### ISSUE THREAD

**Issue by JosVelasco** [WordPress/gutenberg#55467] opened 2023-10-18 23:42 UTC
### Description

If the Expand on click option is activated for a block image, the subsequent image blocks will enable this function even if the switch is not selected.

The blocks above the one that has the lightbox activated won't have this function activated.

### Step-by-step reproduction instructions

1. Insert one image block.
2. Insert another image block and enable the Expand on click option.
3. Insert another image block without enabling the Expand on click option.
4. Confirm the third image block has the lightbox enabled on the front-end.

### Screenshots, screen recording, code snippet

https://youtu.be/HDP4VCMt5CA

### Environment info

- WP 6.4-RC1 and Gutenberg Version 16.8.1 activated. Twenty Twenty-Three theme.
- Chrome 118.0.5993.88 (Build oficial) (arm64)
- MacBook with Sonoma 14.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by karmatosed** [comment] 2023-10-19 11:38
I can confirm this is happening for me and give a bit more details from testing. This seems to be only happening using the Gutenberg plugin so something not in 6.4 but since the merge there.

**Comment by colorful-tones** [comment] 2023-10-19 12:27
This happened to me yesterday in my 6.4 walk-through, and I was running the same installation as reported.

**Comment by colorful-tones** [comment] 2023-10-19 14:35
Note: this issue is _not_ happening with latest Gutenberg `trunk`.

**Comment by colorful-tones** [comment] 2023-10-19 14:35
@artemiomorales might have some insight here.

**Comment by colorful-tones** [comment] 2023-10-19 14:41
It seems like this was addressed in #55120. However, if we want the Lightbox roll-out to be successful then I would prioritize cherry-picking that into a release (if possible) before the final WP 6.4 lands.

@karmatosed @mikachan for visibility.

**Comment by colorful-tones** [comment] 2023-10-19 14:51
_and_ @mikachan is already ahead of us all! She [cherry-picked the change already](https://github.com/WordPress/gutenberg/pull/55120#issuecomment-1757410223). 👏 

Closing this out.

**Closed as completed by colorful-tones** 2023-10-19 14:51 UTC
Labels: [Type] Bug, [Block] Image
