### ISSUE TITLE
Cannot set post formats in Page post type

### ISSUE THREAD

**Issue by wileycoyote78** [WordPress/gutenberg#44063] opened 2022-09-11 23:54 UTC
### Description

I am developing a theme for WP, and I am tinkering around with post formats. It works great on regular posts. However, when I try to add post-format support for pages, I run into a bit of a snag. From the drop down, I select a different format than 'Standard,' but after saving/updating the page, the selection reverts back to 'Standard.'

Upon querying the post format for the page on the front end, sure enough, 'Standard' is displayed. I reported the issue on the WP forums [here](https://wordpress.org/support/topic/on-page-post-formats-revert-to-standard/#post-15999230), and a moderator replied with a work around, as bcworkz was able to duplicate the problem.

Here is the code from the functions.php file to enable post formats.

`function mytheme_post_formats() {`
`add_theme_support( 'post-formats' , [ 'audio' , 'video' ] );`
`}`
`'add_action( 'after_setup_theme' , 'mytheme_post_formats' );`
`add_post_type_support( 'page' , 'post-formats' );`

Per bcworkz's suggestion, I installed the Classic editor plugin. I changed the selection to 'Audio' and updated the page. It worked. On the front end, it verified the post format was indeed 'audio.' I then reverted back to Gutenberg, and the page format selection continues to show 'Standard.' However, any additional updates after this retain the 'audio' format selected in Classic.

Long story short: It seems Gutenberg can't set or get post formats on page post types properly.

### Step-by-step reproduction instructions

1. After enabling post-formats support for page post-type, create a new Page.
2. Enter whatever content
3. Select a different format from the drop down list other than standard
4. Click Save/Update
5. The selection reverts back to Standard
6. In the pages.php file (or whatever template file handles your pages), `echo get_post_format($post->ID)? : 'Standard';` **NOTE** In my file, the previous line of code is being called outside the Loop, so I set the global $post to call the ID.
7. On the front end, regardless of selection (audio or video in my case), the page will display 'Standard'.
8. Install/Activate Classic Editor plugin.
9. Go to the page and select a different format, then update. Note that the selected format selection remains.
10. Revert back to Gutenberg by deactivating Classic.
11. Go back to the page. Note that the format says 'Standard' again. However, when the page is displayed on the front end, the desired format selected while in Classic echos out.

### Environment info

WP 6.0.2
Gutenberg: WP Block Editor AND plugin v 14.0.2
Theme(s): Custom theme, as well as WP Twenty Twenty-Two v1.2 after post type support is added to its functions.php file.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-09-27 14:46
This is a duplicate of https://github.com/WordPress/gutenberg/issues/19805.

Quoting the answer from the previous issue - https://github.com/WordPress/gutenberg/issues/19805#issuecomment-580428211

> The root cause of the problem is the rest API. The page has a specific schema that does not include post format(https://developer.wordpress.org/rest-api/reference/pages/) and even though the block editor is sending the post format change is ignored on server side.

**Closed as completed** 2022-10-03 08:36 UTC
Labels: [Type] Bug, [Feature] Document Settings, REST API Interaction
