### ISSUE TITLE
Opening Block inserter closes Settings sidebar

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24734] opened 2020-08-22 06:32 UTC
**Describe the bug**
When you open the Block Inserter, the Settings Sidebar closes, and doesn't reopen when the Block inserter is closed.
Why do you insist on hiding so much of the UI from users?? You're making editing harder, not easier!!
Stop hiding everything!!

Video: https://share.getcloudapp.com/4gu9l8z5

**To reproduce**
1. Add new Page
2. Open and Close Block Inserter
3. Watch Settings Sidebar close
4. Get frustrated because now you have to manually reopen the settings sidebar again!

**Expected behavior**
Don't change my UI layout by hiding panels that I have open. Stop making it harder for users to find things!!

**Editor version (please complete the following information):**
- WordPress version: [5.5]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Firefox 79.0

**Comment by mariohamann** [comment] 2020-08-23 17:19
It seems to depend on the window size. If I make my window smaller, it closes the settings, in larger sizes it stays open.
I published an idea a few weeks ago that could solve this problem - what do you think about it? I would be glad to recieve some more feedback.

https://github.com/WordPress/gutenberg/issues/22319
https://github.com/WordPress/gutenberg/issues/22113#issuecomment-642430024

**Comment by annezazu** [comment] 2020-08-25 21:36
Thanks for chiming in here @mariohamann. I was just about to say it seems to be dependent on window size. Excited to see you already have some explorations.

**Comment by maddisondesigns** [comment] 2020-08-29 05:57
Yes, it's dependent on the screen size, but it does it all the way up to about 1450px wide, which is ridiculous. If the Block Inserter is going to close the settings sidebar when it opens, then common sense should tell you that it should also re-open it when it closes. I shouldn't have to constantly re-open it myself every time a block is inserted. By not doing this you've just doubled the number of clicks that it requires to add content to your page. This is not making editing your content easier.

I don't mind the idea of merging the settings sidebar and block inserter, as proposed by @mariohamann, but not a fan of putting too much reliance on the Block Navigation functionality, at least in it's current format. At the moment, the Block Navigation feature is mostly useless. It provides very little useful information regarding the content on your page. If you've got a text heavy page, all it shows you is that you have a bunch of paragraph and heading blocks. It doesn't give you any indication of the content in those bocks. It doesn't even show you the heading text, so trying to drag 'n drop blocks into the correct location within this Block Navigation tools would be mostly futile as you'd rarely be able to place them in the position that you most likely want them.

One thing that I don't think was touched on, is what happens when you click on a block. If the Settings Sidebar and Block Inserter were merged in some way, it's important that the block inserter is automatically hidden when a block is selected, and the Settings Sidebar is displayed. I don't want to be having to re-open this settings sidebar every single time I select a block and want to change it's settings.

**Comment by mapk** [comment] 2020-10-20 21:38
This looks like a duplicate of https://github.com/WordPress/gutenberg/issues/23968. Mind if I close this one in favor of the other?

**Closed by mapk** 2020-10-20 21:38 UTC
Labels: Needs Technical Feedback, [Feature] Document Settings, [Feature] Inserter, [Type] Enhancement
