### ISSUE TITLE
Pasting into Firefox removes new lines instead of inserting as paragraph blocks

### ISSUE THREAD

**Issue by bfren** [WordPress/gutenberg#31624] opened 2021-05-08 16:35 UTC
## Description
Pasting into Firefox removes new lines instead of inserting as paragraph blocks

## Step-by-step reproduction instructions
1. Log in to backend using Firefox
2. Copy text from (e.g.) Word
3. Paste into new post

## Expected behaviour
A paragraph block should be added for each new line (as it is in Chrome)

## Actual behaviour
New lines are stripped so text is pasted as one big paragraph

## Screenshots or screen recording (optional)
![ffbug2](https://user-images.githubusercontent.com/17511478/117546785-1acebe00-b024-11eb-88c6-000f9ac0b81e.gif)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: whatever comes with 5.7.1
- Are all plugins except Gutenberg deactivated? No - but that's irrelevant as it works on Chrome but not Firefox
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 88.0.1, Brave 1.24.82 (Chromium 90.0.4430.93)

**Comment by priethor** [comment] 2021-05-14 13:50
Hi there! I'm not able to reproduce the issue, when I copy paragraphs from Word to the post content in Firefox it works the same as in Chrome.

Do line breaks disappear as well when copying paragraphs from other sources?

**Comment by bfren** [comment] 2021-05-14 15:14
Yes - it appears to be stripping out all formatting entirely:

![copy-paste](https://user-images.githubusercontent.com/17511478/118291340-658e8100-b4cf-11eb-8c70-fbde59ecb8fa.gif)

I don't think it's a Firefox setting, as doing the same thing in (e.g.) (https://richtexteditor.com/)[https://richtexteditor.com/] works fine:

![copy-paste-2](https://user-images.githubusercontent.com/17511478/118291639-bc945600-b4cf-11eb-853c-1c4be8c003a2.gif)

**Comment by t-hamano** [comment] 2022-07-25 13:34
I'm not able to reproduce the issue too.

- OS Version: Windows 11
- Browser Version: Firefox 102.0.1 (64*bit)
- WordPress Version: 6.1-alpha-53579
- Gutenberg Version: 13.7.2 (with or without)

https://user-images.githubusercontent.com/54422211/180789803-11f10e43-36e8-4602-87ff-496cd89ff533.mp4

**Comment by bfren** [comment] 2022-07-25 14:47
I'm at a loss then - I don't see how it can be my Firefox settings if rich text paste works on other non-Gutenberg editors (it does).  But presumably it is something to do with my config if it works fine for others.

**Comment by t-hamano** [comment] 2022-07-25 15:28
Is it only in Word that you cannot paste correctly into the Gutenberg Editor?
For example, if you copy a part of a web page and paste it into the Gutenberg Editor, does the same problem occur?

**Comment by bfren** [comment] 2022-07-26 07:58
Unfortunately it's HTML as well - as per the clip [here](https://github.com/WordPress/gutenberg/issues/31624#issuecomment-841306519).

**Comment by t-hamano** [comment] 2022-07-26 08:39
Hmmm, so this isn't a Word-specific problem.

Furthermore, I have also tested with the WordPress version (5.7.1) at the time this problem was reported and could not reproduce it.

Could you give me the browser console screenshot when you paste into the block editor?
You should see the result of parsing the HTML being pasted as follows:

![capture](https://user-images.githubusercontent.com/54422211/180962938-5cf7897a-174c-4a45-a7ee-65a609926a91.png)

**Comment by bfren** [comment] 2022-07-28 07:26
Literally nothing!  I tried pasting from another website and from Word, same result - it's like it's not recognising a formatted clipboard.

![Screenshot 2022-07-28 081959](https://user-images.githubusercontent.com/17511478/181445097-0617d711-17a4-493d-b187-e0cac19ff778.jpg)

So I end up with 

![Screenshot 2022-07-28 082205](https://user-images.githubusercontent.com/17511478/181445497-696e01a1-d801-41c5-918a-8504932f9278.jpg)

Yet, if I paste into another editor (e.g. https://richtexteditor.com/) with the same data on the clipboard, in the same instance and profile of Firefox (just a different tab) it pastes correctly as HTML - so the formatted data is obviously on the clipboard but for some reason Gutenberg is not recognising it.

![Screenshot 2022-07-28 082152](https://user-images.githubusercontent.com/17511478/181445505-3b0f8175-8eca-44ae-a5d7-cfc1736690d4.jpg)

And if I then paste the same clipboard into the same WP site using Chrome, I get this:

![Screenshot 2022-07-28 082457](https://user-images.githubusercontent.com/17511478/181446053-9abd1d4a-10a2-4a3a-8ab0-b1b1c63dfd02.jpg)

With the correct items in the console:

![Screenshot 2022-07-28 082531](https://user-images.githubusercontent.com/17511478/181446161-1ef8b7ec-14d4-48df-bd9c-f33873d6de89.jpg)

**Comment by bfren** [comment] 2022-07-28 07:30
(I even disabled all my add-ons and the same thing happens - so it must be a setting somewhere related to copy / paste?  I can't see anything in about:config that looks likely though.)

**Comment by bfren** [comment] 2022-07-28 07:39
Urgh I've cracked it - I was searching about:config for 'copy', 'paste' and 'script' - and then had a brainwave to search for 'clipboard'.  Somehow dom.event.clipboardevents.enabled was set to 'false', which is presumably what Gutenberg hooks into.  Resetting that to true, and finally pasting works as expected.

Other editors obviously have another way of detecting HTML paste.  So I guess after all that my suggestion might be to have an additional way of detecting what's being pasted in case that method fails?

**Comment by t-hamano** [comment] 2022-07-28 12:01
Thank you for getting to the bottom of what caused this!
I was finally able to reproduce it myself.

Upon examination, it appears that the paster handler is not firing and the browser default behavior is being executed.

https://github.com/WordPress/gutenberg/blob/8179690c4b79f49780a9e2ba94af00a98e85b97f/packages/block-editor/src/components/rich-text/use-paste-handler.js#L249

I don't know if this problem should be solved or if there is a way to solve it, but I would very much like to wait for someone's advice.

To be sure, I will summarize the steps to reproduce this problem.

## Testing Instructions

- Open Firefox browser
- Enter `about:config` in the url
- Find the configuration name `dom.event.clipboardevents.enabled` and change it to `false`
- Restart the browser
- Copy text from a Web page, Word or other document
- Confirm that the content is not parsed and becomes a single paragraph as plain text.

**Comment by jordesign** [comment] 2023-09-08 03:40
With this seeming to be an edge case, and no further movement in 12+ months - I'm going to close this issue. If we get more reports - we can always consider re-opening.

**Closed as not planned by jordesign** 2023-09-08 03:40 UTC
Labels: [Feature] Paste, Browser Issues, Needs Technical Feedback, [Package] Rich text
