### ISSUE TITLE
Reusable Blocks don't respect alignment settings of Blocks within them

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#14764] opened 2019-04-02 10:44 UTC
**Describe the bug**
Several Blocks have alignment controls which afford `wide` and `full` widths (eg: `section`, `cover`...etc). These Blocks display correctly in the Editor as a wide or full width as required.

When creating a Reusable Block however, a `core/block` Block `<div>` is created to contain the Blocks within the Reusable Block. 

```html
<div data-type="core/block" aria-label="Block: Reusable Block" class="wp-block editor-block-list__block block-editor-block-list__block"  />
```

By default this `core/block` behaves like other Block wrapper `<div>` and is the standard width as defined by the following CSS rule which applies to all Blocks:

```css
.wp-block {
    max-width: 610px;
}
```

This causes the Blocks _within_ the Reusable Block to be constrained to the standard width _even_ if they themselves are set to `wide` or `full`:

![Screen Shot 2019-04-02 at 11 26 03](https://user-images.githubusercontent.com/444434/55396179-2e50f600-553b-11e9-99f6-5bfebb7e701d.png)

**Expected behavior**

The resuable Block should not constrain the width of the Blocks within it. This can be achieved by removing the `max-width`, horiztonal `padding` and `margin`s. The result is then as expected (ie: the Blocks within are as wide as they need to be based on their align settings).

![Screen Shot 2019-04-02 at 11 27 52](https://user-images.githubusercontent.com/444434/55396277-6a845680-553b-11e9-8e1a-ed4070d2bf11.png)

Note the Reusable Block shown in the above screenshot contains a `section` Block with a blue background which is set to `full` align setting. See how it occupies the full width of the editor (almost! - a few tweaks still needed).

**To Reproduce**
1. Add a few Blocks which support `wide` and `full` align settings (eg: `cover`, `section`)
2. Set the Blocks to be `full` alignment - notice the width fills the editor canvas.
3. Create a Reusable Block from the Blocks created above
4. See how the Blocks are now constrained in width.

**Screenshots**
See above

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by youknowriad** [comment] 2019-04-02 10:45
I think this is a duplicate of #8288 Feel free to add context there.

**Comment by getdave** [comment] 2019-04-02 10:47
@youknowriad Quite right. I even did an Issue search but must have missed it. Closing in favour of https://github.com/WordPress/gutenberg/issues/8288

**Closed** 2019-04-02 14:00 UTC
Labels: [Block] Block
