### ISSUE TITLE
Feedback: Site block text options are inconsistent

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30727] opened 2021-04-12 09:07 UTC
During a user testing session on April 9, users expressed that it is confusing that different blocks have different text options.

Feedback included:
_Confusing: The H1 has a Letter case option, but the tag line has none. _(H1 refers to site title)_
Confusing: The H1 does not have the Letter case default configuration selected. _(H1 refers to site title)_
I cannot do bold or italic on the tagline._
_Site Title > I was not able to change to Bold/Italic and was not able to change the color of title_
_Site Title: I can either use lowercase or uppercase, no normal case. There are no labels for the Letter Case, the icons are not enough_

**Comment by carolinan** [comment] 2021-04-12 12:09
Related https://github.com/WordPress/gutenberg/issues/30738

**Comment by annezazu** [comment] 2021-04-16 16:16
As I'm going through feedback from Yoast's contributor day and reviewing these issues for the FSE program, I noticed this one is a duplicate of an earlier issue: https://github.com/WordPress/gutenberg/issues/27830 I'm going to close this out in favor of the earlier one to help keep things organized :)

**Closed as completed by annezazu** 2021-04-16 16:16 UTC
Labels: [Type] Feedback, [Block] Site Title, [Block] Site Tagline
