### ISSUE TITLE
Clear theme.json cache after saving Styles in FSE

### ISSUE THREAD

**Issue by SergeGusev** [WordPress/gutenberg#40048] opened 2022-04-05 13:48 UTC
## What problem does this address?

It is taking too long (for development) waiting for site's style changes after setting background color, for example. This is a video - https://drive.google.com/file/d/1h1Nn71QtCviAdPoruufSkC1rmKck_pON/view

## What is your proposed solution?

You can clear all caching after pressing Save button on Styles tab (well, on whole page too, I thinks)

**Comment by bradhogan** [comment] 2022-05-12 01:00
+1 on this.  Frustrating that multiple hard refreshes don't show global style updates in some cases.  Not a great UX when the idea is to make things instantly visually in the editor but not on the actual site.

**Comment by nick6352683** [comment] 2022-05-15 03:33
Same problem here... This should have a priority for WP 6.0 !

**Comment by mrleemon** [comment] 2022-05-22 07:12
This is a pain in the neck. The theme,json cache should be refreshed when a change in the file is made.

**Comment by kauaicreative** [comment] 2022-11-13 14:15
`define( 'SCRIPT_DEBUG', true );` or `define( 'WP_DEBUG', true );` in wp-config.php should fix the issue with theme.json
But I find styles unusable e.g. /styles/theme.json unusable. The cache never clears on my local environment.

**Comment by nick6352683** [comment] 2022-11-13 22:37
Thanks I'll give it a shot - although it will be in a localhost Xampp php 7.4 environment.

**Comment by oandregal** [comment] 2022-11-18 22:48
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/43914

It's been fixed at https://github.com/WordPress/gutenberg/pull/45679

**Closed as completed by oandregal** 2022-11-18 22:48 UTC
Labels: [Type] Enhancement, [Type] Performance, [Feature] Saving, Global Styles
