### ISSUE TITLE
New created block doesn't show in the block list when using devDependency latest  @wordpress/scripts version 28.0.0

### ISSUE THREAD

**Issue by ksthannan** [WordPress/gutenberg#62348] opened 2024-06-05 20:26 UTC
### Description

After creating new block using @wordpress/create-block@latest command, new created block doesn't appear in the block list when using @wordpress/scripts version 28.0.0 as devDependency. If it is downgraded to 27.9.0, then it will properly. There may have issues with the @wordpress/scripts latest version.

### Step-by-step reproduction instructions

1. Create new block using command,
2, Activate the plugin,
3. Check the block list in the Gutenberg page editor and there the new block is missing anyway.
4. If it has been downgraded to 27.9.0, then it works properly. There may have issues with the @wordpress/scripts latest version.

### Screenshots, screen recording, code snippet

Not work:
"devDependencies": {
		"@wordpress/scripts": "^28.0.0"
	}
	
Working:
"devDependencies": {
		"@wordpress/scripts": "^27.9.0"
	}

### Environment info

Windows localWP server,
Node JS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2024-06-06 04:36
This is a duplicate of #62202.

**Closed as not planned by Mamaduka** 2024-06-06 04:36 UTC
Labels: [Type] Bug, [Tool] WP Scripts, [Status] Duplicate
