### ISSUE TITLE
Add formatting options to the block toolbar for multiple list items

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#63178] opened 2024-07-05 09:50 UTC
## What problem does this address?
I copy/pasted a series of list items to the block editor and it retained the bolding of the original. I trie to highlight all list items, to remove the bold formatting. 

## What is your proposed solution?
Add a formatting choice to the toolbar when multiple list items are highlighted. It would also help with formatting list items in bulk instead of one at a time. 

![Screenshot 2024-07-05 at 11 47 16](https://github.com/WordPress/gutenberg/assets/39980/c288c732-4714-49e9-b5b0-9c4543faea00)

**Comment by ellatrix** [comment] 2024-07-12 14:06
Duplicate of #27221

**Closed as completed by ellatrix** 2024-07-12 14:06 UTC
Labels: [Type] Enhancement, [Block] List
