### ISSUE TITLE
In latests versions I cannot include a private video in Vimeo

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/gutenberg#21752] opened 2020-04-21 11:02 UTC
Don't know why it has been changed, but now I cannot include a link from vimeo.

**Comment by Soean** [comment] 2020-04-21 15:41
Maybe Vimeo has changed it and you can't embed privat videos? Do you have an example link?

**Comment by annezazu** [comment] 2020-04-21 19:48
As another follow-up, can you share what privacy option the video you are trying to share has? You can see the list of options [here](https://vimeo.zendesk.com/hc/en-us/articles/224817847-Privacy-settings-overview). Tied to this, any [screenshots](https://www.take-a-screenshot.org/) you can share with us here along with any error messages will help us better understand what might be going on.

**Comment by davidperezgar** [comment] 2020-04-24 14:44
Ok, you can test this URL
https://vimeo.com/410913518/64141e9075

And I share with you the settings:
Who can watch? People with the private link
Where can this be embedded? Anywhere
Who can comment? Anyone
People can download this video: No
People can add to collections: No

And it does not embed correctly.

**Comment by annezazu** [comment] 2020-04-24 21:01
@davidperezgar I was able to properly embed this link! As a next step, I'd recommend disabling all other plugins to rule out a plugin conflict. Here are some screenshots of what I found. 

While editing:

<img width="874" alt="Screen Shot 2020-04-24 at 1 55 38 PM" src="https://user-images.githubusercontent.com/26996883/80256262-55d99b80-8633-11ea-82e0-574a58a81f3e.png">

After publishing:

<img width="828" alt="Screen Shot 2020-04-24 at 1 55 42 PM" src="https://user-images.githubusercontent.com/26996883/80256271-58d48c00-8633-11ea-9801-b2fb51cc17c5.png">

I'm using WordPress 5.4, Gutenberg 7.9.1, and the Twenty Twenty theme without any additional plugins. For now, I'm going to close this out since I'm unable to replicate this issue using the Vimeo link you provided. You are welcome to re-open this if you're able to provide more information about how the issue is caused by Gutenberg.

**Closed by annezazu** 2020-04-24 21:01 UTC
Labels: [Status] Needs More Info
