### ISSUE TITLE
thumbnail in the gallery

### ISSUE THREAD

**Issue by HassaN0152** [WordPress/gutenberg#9927] opened 2018-09-15 06:17 UTC
There is no thumbnail in the gallery and the size of the stretched image image is displayed.
translate by google

**Comment by loganstellway** [comment] 2018-09-29 19:02
Yes - this is definitely an issue when including a gallery with many images on a page referencing large images. 

Load times 👎

**Comment by mtias** [comment] 2018-10-07 19:05
Closing as duplicate of #1450.

**Closed by mtias** 2018-10-07 19:05 UTC
Labels: [Type] Help Request
