### ISSUE TITLE
Media sidebar does not show when selecting an image in media library on mobile

### ISSUE THREAD

**Issue by alee8648** [WordPress/gutenberg#10232] opened 2018-09-28 13:32 UTC
**Describe the bug**
When using the Media Library to select an image in Gutenberg on mobile or zoomed screens, selecting the image does not cause the Media Sidebar to appear with the options to add caption, alt text, etc. This is the behaviour in the classic editor Media Library.

**To Reproduce**
1. Add an image block to a post in Gutenberg
2. Click on 'Media Library'
3. Select an image

This issue is present when zoomed in sufficiently, or on a small enough screen that the `media-modal-content` div fills the full screen, triggered by the following media query:
`@media only screen and (max-width: 640px), screen and (max-height: 400px)`

**Expected behavior**
Media sidebar appears with Attachment details, and fields to input Title, Caption, Alt Text, etc. Sidebar disappears when clicking off or deselecting the image.
![wp-media-library-expected](https://user-images.githubusercontent.com/11977269/46210853-dcc87400-c329-11e8-82f4-eed0f9e89e08.gif)

In the classic editor, a `visible` class is toggled on the media sidebar when an image is selected and deselected. In the Gutenberg version, the `visible` class is not toggled - but manually adding that class in inspector 'fixes' the issue.

**Screenshots**
Below gif shows how selecting an image does not cause the sidebar to appear.
![wp-media-library-gutenberg-issue](https://user-images.githubusercontent.com/11977269/46210880-eeaa1700-c329-11e8-9535-03444f6ae857.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.4
 - Browser: Chrome 69, Firefox 62, Safari 11.1

**Additional context**
- Gutenberg version 3.9.0

**Comment by jorgefilipecosta** [comment] 2019-06-06 10:31
I retested this issue and I'm still able to reproduce it.

**Comment by jorgefilipecosta** [comment] 2019-06-12 09:14
A patch was proposed to address this problem in core media library https://core.trac.wordpress.org/ticket/47527.
Thank you for reporting this problem @alee8648. I'm closing the issue is we can follow the progression of it on the trac ticket.

**Closed by jorgefilipecosta** 2019-06-12 09:14 UTC
Labels: Media, [Type] Bug, [Type] WP Core Bug
