### ISSUE TITLE
Styles missing from images when using useFirstImageFromPost

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#64851] opened 2024-08-27 21:08 UTC
The Post Featured Image block supports using the first image from a post's content using the `useFirstImageFromPost` attributes, when a featured image is not assigned to the post. 

However, this image does not receive styles on the front-end, as seen in the visual below (missing the border radius and aspect ratio styles). It is also missing `width: 100%; height: 100%; object-fit: cover;` which is added by the aspect ratio styling. 

### Editor 

![CleanShot 2024-08-27 at 17 03 31](https://github.com/user-attachments/assets/afa5de80-6783-4523-b009-a1971d29fed2)

### Frontend 

The brown image is a post pulled from the post; not a true featured image. 

![CleanShot 2024-08-27 at 17 03 40](https://github.com/user-attachments/assets/25ed4839-7aa2-4dc2-8f0b-5e8e8df26604)

Here's the pattern markup I'm using: 
```
<!-- wp:query {"queryId":1,"query":{"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":null,"parents":[],"perPage":5},"enhancedPagination":true,"metadata":{"categories":["blog"],"name":"Photoblog","patternName":"kanso/query-photoblog"}} -->
<div class="wp-block-query"><!-- wp:post-template {"style":{"spacing":{"blockGap":"var:preset|spacing|20"}},"layout":{"type":"grid","columnCount":3,"minimumColumnWidth":null}} -->
<!-- wp:group {"metadata":{"name":"Post Wrapper"},"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:post-featured-image {"aspectRatio":"1","useFirstImageFromPost":true,"style":{"border":{"radius":"16px"}}} /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:query -->
```

**Comment by richtabor** [comment] 2024-08-27 21:34
@scruffian I recall you worked on this originally.

**Comment by rohitmathur-7** [comment] 2024-08-29 11:52
Hii @richtabor ,
I have raised a PR for this issue can you please go through it once.
Thanks.

**Comment by justintadlock** [comment] 2024-08-30 23:23
Duplicate of https://github.com/WordPress/gutenberg/issues/63454

**Closed as not planned** 2024-09-09 21:21 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Post Featured Image
