### ISSUE TITLE
Scrollbars appearing in site logo and image block in Site Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38086] opened 2022-01-19 19:18 UTC
### Description

When adding in an image to the image or social icon block in the site editor (can't replicate when adding to page), scrollbars are showing up around the edges making it very cumbersome to interact with.  I think this is related to this issue: https://github.com/WordPress/gutenberg/issues/37573 

### Step-by-step reproduction instructions

1. Open site editor.
2. Add an image block or site logo.
3. Upload an image.
4. See scrollbars. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/150198808-7fc49945-d963-429f-a766-be9747b3b5e3.mov

https://user-images.githubusercontent.com/26996883/150198838-a4bcdd2a-9f33-431a-990d-e8c025eb18b5.mov

### Environment info

- WordPress 5.9-RC3-52601
- TT2 theme
- Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment] 2022-01-19 19:51
Hmm, I'm not able to reproduce with a site logo or image block.

Env:
* WordPress: WordPress 5.9-RC3-52601 and on `trunk`
* Browsers: Chrome, Safari, Edge, and Firefox
* OS: macOS Big Sur
* Theme: TT2
* Plugins: none and with Gutenberg v12.4.0
* Localhost: wp-env, Local, and on my personal live website

**Comment by chthonic-ds** [comment] 2022-01-19 20:24
I'm seeing this consistently with a Site Logo block in a template part in the Site Editor.

![image](https://user-images.githubusercontent.com/29587253/150217556-1ae5a57c-6c82-411b-82ac-75bc9660c131.png)

- WordPress: 5.9-RC3
- Browsers tested: Chrome, Firefox
- OS: Win 10
- Theme: first noticed with custom theme active, confirmed same with TT2
- Plugins: none

**Comment by walbo** [comment] 2022-01-19 20:25
Seeing the scrollbars here as well. Only getting the scrollbars when the styles are concatenated.

Env:
- WordPress 5.9-RC3-52601
- Browser: Chrome, Safari. (Firefox seems fine)
- OS: macOS Monterey
- Theme: TT2
- Plugins: none
- Localhost: Local
- SCRIPT_DEBUG: false
- CONCATENATE_SCRIPTS: Undefined

**Comment by hellofromtonya** [comment] 2022-01-19 20:30
Retested locally and on live website and made sure `SCRIPT_DEBUG` is `false`. Still can't reproduce. No scrollbars. Hmm.

**Comment by Mamaduka** [comment] 2022-01-20 17:37
I think I've got the fix for this issue; I will create PR tomorrow morning.

**Comment by piotrbak** [comment] 2022-01-21 13:59
I'm also not able to reproduce the issue. Applied proposed fix to search for regressions, but everything looks just fine.

**Closed as completed** 2022-01-23 17:07 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Image, [Block] Site Logo, [Feature] Site Editor
