### ISSUE TITLE
Applying Lightbox "Click on Expand" on 1 Image Block Automatically Adds the Option on All Other Images

### ISSUE THREAD

**Issue by thesunitarai** [WordPress/gutenberg#55290] opened 2023-10-12 02:56 UTC
### Description

I installed WordPress 6.4 Beta 3 via the Beta Tester plugin and the 2024 theme has been activated.
I went to Appearance> Editor > Templates > Blog Home and then added the "Click on Expand" option on the first image on the template.
And, when I checked the preview after saving the changes, I could see the Lightbox option had been automatically added to all the other images on the template.

### Step-by-step reproduction instructions

1. Install WordPress 6.4 Beta 3 via the Beta Tester plugin
2. Activate the Twenty Twenty Four theme
3. Go to Appearance > Editor > Templates > Blog Home
4. Click anywhere on the page to edit and once the editor opens, click on the first image block, and check the "Click on Expand" option 
5. Save the changes.
6. View the page and click on the first image to see whether the lightbox is working or not. Then also click on other images on the page and you'll see they also have the lightbox option. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/124130414/9350dc53-de5e-41bb-867a-f60b531eafc9

### Environment info

- PHP Version 8.1.23
- WordPress 6.4 Beta 3 (Installed via Beta Tester Plugin)
- MacBook Air (M2 Chip), Google Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kafleg** [comment] 2023-10-12 03:51
Here the the core ticket https://core.trac.wordpress.org/ticket/59598

**Comment by carolinan** [comment] 2023-10-12 06:23
Hi!
This is a duplicate of https://github.com/WordPress/gutenberg/issues/55119.
The problem has already been solved and the fix will be in WordPress 6.4 RC1: https://github.com/WordPress/gutenberg/pull/55120#issuecomment-1757410223

**Closed as not planned by carolinan** 2023-10-12 06:23 UTC
