### ISSUE TITLE
Can't select groups or columns since 7.1 update

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#19076] opened 2019-12-11 19:05 UTC
**Describe the bug**
Since updating to 7.1 the slight padding around the child objects is gone and selecting is impossible. This applies to the core/columns and core/group blocks. I've disabled my theme to verify it's native to Gutenberg, and also tested on multiple sites.

I've tried using CSS to add padding with no luck. I found that if clicking on the psuedo element works for columns works, but it is not visible and very difficuly to find. Adding this CSS helped as a temporary solution (just adding this to help convey the problem):
`[data-type="core/columns"]:before{border:1px solid;}`
No such luck for groups.

Ultimately downgraded to Gutenberg 7 because this issue makes Gutenberg unusable for me. Verified 7.0 still works fine. Will be watching this thread because I really want that drag-and-drop featured images feature.

**To reproduce**
Just create a group with a heading inside, and try to select the group.

**Expected behavior**
There used to be a cursor:pointer and a hover effect, those are both gone now. Clicking should select the parent element.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Beta
 - Version: Gutenberg 7.1

**Comment by ZebulanStanphill** [comment] 2019-12-11 20:10
You can select parent blocks using any of the following 3 methods:

1. The breadcrumb bar at the bottom of the screen.
![image](https://user-images.githubusercontent.com/19592990/70656211-40814900-1c1f-11ea-849c-3c889321789e.png)

2. The select tool, which selects parent blocks on first click, then children on second click, then children-of-children on third click, etc. Clicking the deepest child re-enters the standard edit mode, as does clicking the block title or pressing <kbd>Enter</kbd>.
![image](https://user-images.githubusercontent.com/19592990/70656265-61499e80-1c1f-11ea-81de-fdff1c8f4f82.png)

(Ignore the template library button in the screenshot; that's added by a plugin.)

3. The Block navigation menu.
![image](https://user-images.githubusercontent.com/19592990/70656462-bd142780-1c1f-11ea-9519-47c30200b3a4.png)

**Comment by joshm33333** [comment] 2019-12-11 20:13
Didn’t know any of that
Is what I found actually a bug then? Or is this expected behaviour?

**Comment by ZebulanStanphill** [comment] 2019-12-11 20:41
@joshm33333 It's expected behavior. One of the main pull requests involved is #18105, where you can see some of the reasoning for the change. This is the latest in a long series of iterations trying to improve the experience with nested blocks. The select tool was introduced partially because it was decided that trying to select specific blocks would need its own mode/tool in order to be as easy as possible without interfering with standard editing.

I think perhaps the select tool should be mentioned somewhere in the editor's welcome guide, but that belongs in a separate issue. Feel free to open a new issue suggesting that or other ways to make it more clear how to select parent blocks easier.

Notably, there _should_ be a 4th way to select parent blocks: pressing the up arrow key on your keyboard. This worked in 7.0.0 but has since been broken somehow. I've already reported this regression: #18928.

As a side note, there is also an open issue (#10524) and pull request (#15830) for adding an option be added to show visible toolbar labels in the top toolbar. That could make discovery of the select tool feature easier.

There is also a PR (#19034) that changes the style of the breadcrumb bar links in an attempt to make it more obvious that they are clickable. Feel free to leave feedback there on what you think of the proposed changes there.

Anyway, I'm closing this issue since technically there's no bug here, but feel free to open new issues suggesting ways to further improve the interface, or leave a comment on existing issues/PRs if you have any relevant thoughts/ideas you want to contribute.

**Closed by ZebulanStanphill** 2019-12-11 20:41 UTC
