### ISSUE TITLE
Verse Block: long lines scroll horizontally in the editor

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4138] opened 2017-12-22 05:45 UTC
## Issue Overview
Text in Verse block scrolls horizontally.

![gutenberg-verseblock](https://user-images.githubusercontent.com/2078245/34286783-155554c0-e737-11e7-8bcc-40aaeb94ad87.gif)

## Steps to Reproduce (for bugs)
1. Insert Verse Block
2. Type stuff

## Expected Behaviour
Text should never scroll horizontally

## Current Behavior
Text scrolls horizontally rather than continuing on the next line

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)
WordPress 4.9.1_

**Comment by youknowriad** [comment] 2017-12-22 07:17
This is a specificity of the verse block, It won't be a verse block anymore if we remove this.

https://github.com/WordPress/gutenberg/pull/2835#issuecomment-333092851

**Comment by maddisondesigns** [comment] 2017-12-22 07:20
I'm not understanding what the point of the Verse block is, or why it should scroll.

**Comment by youknowriad** [comment] 2017-12-22 07:29
I think the idea is that the text in verse block respects white space and new lines, if you do not want a space or a new line, it doesn't break. It has this CSS property `white-space: nowrap;`. It makes it the block of choice to write poetry, verses and stuff like that.

I think @jasmussen could speak more about this.

**Comment by jasmussen** [comment] 2017-12-22 07:44
The idea of the verse block is exactly to allow you to write poetry, haikus, verses, where the indentation and whitespace can be important. Like this:

```
Slow dulcimer, gavotte and bow, in autumn,   
Bashō and his friends go out to view the moon;   
In summer, gasoline rainbow in the gutter,

The secret courtesy that courses like ichor   
Through the old form of the rude, full-scale joke,   
Impossible to tell in writing. “Bashō”
```

Like that, but without the code font.

However I do agree that scrollbars take you out of it. Verses in bookform can sometimes break the lines forcefully, but then they indent the next lines a little, like this:

```
Slow dulcimer, gavotte and bow, in autumn,   
Bashō and his friends go out to view the
    moon;   
In summer, gasoline rainbow in the gutter,

The secret courtesy that courses like ichor   
Through the old form of the rude, full-scale
     joke,   
Impossible to tell in writing. “Bashō”
```

If we can achieve something like that using text indent and word break, that would feel like a nice compromise to me.

**Comment by maddisondesigns** [comment] 2017-12-22 07:58
Using the Gutenberg theme, this is the Verse block.

![screenshot_568](https://user-images.githubusercontent.com/2078245/34289638-8060af8e-e747-11e7-9d71-4e5e9344c579.png)

And this is the Code Block

![screenshot_569](https://user-images.githubusercontent.com/2078245/34289627-7796d25c-e747-11e7-8767-8b317766dbb9.png)

They're basically identical.

Does adding this block really adhere to the WordPress philosophy that states "The rule of thumb is that the core should provide features that 80% or more of end users will actually appreciate and use"? I would be highly sceptical.

If you want to write multiple lines, and also not write it in Courier, then why can't you simply shift-enter inside a Paragraph block? And if that minuscule audience specifically wants to respect white-space, then they can add a style to the CSS Panel in the Customizer.

**Comment by maddisondesigns** [comment] 2017-12-22 08:00
Guaranteed, if I raised a trac ticket after WP 5.0 was released, to get this block added to core, it would be closed within 15 minutes!

**Comment by jasmussen** [comment] 2017-12-22 08:51
I do agree with the similarities between preformatted and verse, to the point that I even suggested merging the two: #1729

That's why I also think it would be good to make the verse block more unique, which is why it'd be cool to explore some improvements like the linebreak behavior you suggest, then at least there'd be different use cases for the two. Longer term it would be fun to explore additional verse styles in the inspector, making the block more unique in a way that wouldn't be fitting for either preformatted or basic text.

Curiously, though, building a "poet block" was one of the first requests we received when starting work on this: https://wordpress.slack.com/archives/C02QB2JS7/p1484800211001617

☝️  since receiving that request, I've noted how much poetry is actually being written on blogs across the world (most of it bad, but that's beside the point :D ). I was blind to it before, but it's opened my eyes to the fact that it's a real use case.

**Comment by maddisondesigns** [comment] 2017-12-22 09:23
From what I can see is that it looks like it was suggest by Matt, which shouldn't automatically ensure that it gets added to core.

While I'm still very sceptical that it would pass the 80% rule, if you believe that it does, then that's fine. If that's the case though, then it needs to be styled significantly different to the way it's been currently styled.

Also, I still don't like the idea of horizontal scrolling. In #1483, which I opened 6 months ago, there needs to be a way to change the content width of the editor, much like you can do now with `editor-style.css` and by setting `html .mceContentBody {max-width: 900px;}`.

Assuming the existing editor block width is same size as the content area on the front-end, then it would still makes sense that the content wraps down to the next line, rather than horizontally scrolling. I'm guessing that anyone who is writing poetry/haiku's isn't going to want their content horizontally scrolling on the front-end, so why should it scroll on the back-end.

**Comment by youknowriad** [comment] 2017-12-22 09:27
> there needs to be a way to change the content width of the editor, much like you can do now with editor-style.css and by setting html .mceContentBody {max-width: 900px;}.

I can you can achieve something similar by enqueuing editor styles. I don't think we're using `max-width` maybe margin. We'll have to try how do it.

**Comment by karmatosed** [comment] 2018-04-27 14:31
For now I am closing this as whether we include the verse block or not, the intended use for this is what has been outlined. We totally may not include all the blocks we have now, that's something to be considered. I also think it's good to think that sometimes experimenting with blocks is fun, for what it's worth I think the verse block is pretty nifty.

**Comment by maddisondesigns** [comment] 2018-04-29 06:00
So, you're just gonna leave it scrolling in the Editor, even though on the front-end it wraps!? I thought one of the principles of Gutenberg was to make the editing experience more closely align with what you see on the front-end. The current implementation of the verse block does the complete opposite of what you see on the front-end. Regardless of whether the verse block is in the final core product, it's in Gutenberg now and therefore should be fixed. I will be extremely surprised if anyone decides to remove this block from the core product, especially since it was suggested by Matt.

**Comment by SuperGeniusZeb** [comment] 2018-07-09 14:01
Idea: use `margin-left` with a positive value and `text-indent` with a negative value to make the text lines start where they normally would without a margin, but the parts of lines that break onto a new line would be indented by the margin.
![image](https://user-images.githubusercontent.com/19592990/42454937-81ab0078-8356-11e8-92e0-5f6ae6281dc6.png)

Idea taken from here: https://www.sitepoint.com/community/t/word-wrap-indent/1352/4

Pinging @karmatosed and @maddisondesigns.

**Comment by SuperGeniusZeb** [comment] 2018-07-09 14:06
In the future, something like `text-indent: 20px each-line` could be used, but right now `each-line` is not in a recommended version of the CSS specification and is not supported in any major browser.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent
https://drafts.csswg.org/css-text-3/#text-indent-property

**Comment by karmatosed** [comment] 2018-07-09 21:19
How does that work across different sized devices @SuperGeniusZeb ?

**Comment by SuperGeniusZeb** [comment] 2018-07-09 22:11
@karmatosed Just fine. The overflow lines appear indented while the start of a new line appears to not be indented. The `text-indent` CSS property only affects the start of a hard new line, not one caused by wrapping, so by using a negative indent and applying a positive indent to the entire text, you can have only wrap-lines appear to be indented.

Also, I just noticed that in my previous comment I mentioned `each-line` when I meant `hanging`. I have now corrected my statement.

**Comment by designsimply** [comment] 2018-07-10 00:10
<blockquote>So, you're just gonna leave it scrolling in the Editor, even though on the front-end it wraps!?</blockquote>

I tested using Firefox 61.0.1 on macOS 10.13.5 and found that the verse block behaves the same way in the editor compared to the front-end: both allow horizontal scrolling. @maddisondesigns is this also what you are seeing with Gutenberg 3.2.0? If you are seeing something different, may I please ask your browser and OS version?

![screen shot 2018-07-09 at mon jul 9 6 02 36 pm](https://user-images.githubusercontent.com/1119271/42482055-d9fb2054-83a2-11e8-9378-653cdc28fde2.png)

![screen shot 2018-07-09 at mon jul 9 6 02 57 pm](https://user-images.githubusercontent.com/1119271/42482059-df631e20-83a2-11e8-99c2-d5f6abe7e737.png)

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13900&action=edit and http://alittletestblog.com/2018/07/10/verse-block-test/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

Labeling note: I feel this should be `[Type] Enhancement` instead of `[Type] Bug` because the block works as intended based on its original design and the issue makes a suggestion for how to improve it. Agree?

**Comment by maddisondesigns** [comment] 2018-07-10 03:35
@designsimply It depends what theme you're using.

In TwentySeventeen and TwentyTwelve it scrolls in the editor and scrolls on the front-end
In TwentyFifteen it scrolls in the editor and wraps on the front-end

Horizontal scrolling of any sort, within a web page is a horrible user experience. About the only time it's acceptable is when you're displaying a block of code where wrapping the text can make the code harder to read.

**Comment by SuperGeniusZeb** [comment] 2018-07-10 13:45
I agree that having horizontal scrolling in the Verse block seems weird, as you would not usually expect to see that used for a poem. I think the text indentation solution I suggested above is the right approach.

**Comment by brandonpayton** [comment] 2018-09-03 14:45
Hi @ZebulanStanphill, since all the Verse block text has the same parent element, the negative `text-indent` and positive `margin-left` isn't enough to fix this issue because subsequent stanzas will also be shifted left by the margin.

<img width="912" alt="screen shot 2018-09-03 at 11 51 20 am" src="https://user-images.githubusercontent.com/530877/44983530-71c98e80-af71-11e8-9f11-c77731077c8d.png">

For now, since we don't appear to have a good alternative solution, let's add a rule so Verse blocks consistently do not wrap lines in the editor or on the front end. I'll create a PR.

**Closed** 2018-09-05 17:10 UTC
Labels: Blocks, [Type] Bug
