### ISSUE TITLE
Table of Content Issue

### ISSUE THREAD

**Issue by Emilya55** [WordPress/gutenberg#41474] opened 2022-06-01 05:45 UTC
### Description

Hi There!
My table of content feature is not working. When I put table of content in my website the whole post get vanished and show unknown error. BUt when I remove table of content the whole post came back? Plz let me know what will be the issue?
Here is the [URL](https://theprintero.com/best-7-wide-format-sublimation-printers-all-in-one-high-quality/) of my post which is showing error. 
Thank you in Advance

### Step-by-step reproduction instructions

Post
Insert Table of content
Preview the post
The error will appear

### Environment info

![Error](https://user-images.githubusercontent.com/92599761/171335891-bf779925-c0aa-401c-9807-d9ad43f66e08.JPG)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment] 2022-06-01 15:13
Hi @Emilya55 - thanks for the report!

I haven't been able to replicate the issue so far. I inserted a table of contents, and it worked well. No errors, and no content was erased, either when previewing or publishing the page. 

Could you please provide the following information to help us better understand how to replicate the issue:

- What version of WordPress are you using?
- If you also have the standalone Gutenberg plugin active, what version is it?
- Is the issue present with all your plugins temporarily deactivated? You can use the [Health Check plugin](https://wordpress.org/plugins/health-check/) for this, which will not change your live site.
- Is the issue present with a default theme? Again, you can use the Health Check plugin for this.

Once we have more information, we'll try to replicate again. Thanks!

**Comment by Emilya55** [comment] 2022-06-17 11:45
Wordpress version: 6.0
No Gutenberg

**Comment by ZebulanStanphill** [comment] 2022-07-03 02:19
The official Table of Contents block isn't even included in WP 6.0. I'm guessing you're using a Table of Contents block from a plugin, then? If so, the bug is most likely not in WP/Gutenberg, but in the plugin that adds the block you're trying to use.

**Comment by kathrynwp** [comment] 2022-07-20 21:01
@ZebulanStanphill Thanks for catching that! You're totally right; the Table of Contents block is still only available via the standalone Gutenberg plugin, which @Emilya55 confirmed above that they are not using.

@Emilya55 - At the moment I see `lwptoc` referenced in the code for your table of contents, which looks like it's coming from this plugin: [LuckyWP Table of Contents](https://wordpress.org/plugins/luckywp-table-of-contents/). Feel free to request assistance with the plugin here if you're still having any issues with it: https://wordpress.org/support/plugin/luckywp-table-of-contents/

As it does not look like this issue is related either to WordPress core or to the Gutenberg plugin, I'm going ahead and closing out this issue.

**Closed as not planned by kathrynwp** 2022-07-20 21:01 UTC
Labels: [Type] Bug, [Status] Not Applicable, [Block] Table of contents (experimental)
