### ISSUE TITLE
Block menu sometimes extends underneath top toolbar/admin bar

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#6026] opened 2018-04-05 22:46 UTC
## Issue Overview

When clicking the 3 dot menu for a block, it tries to push the menu underneath or above, but sometimes it extends upwards, with the top menu items being obscured.

This can be observed in frontenberg on v2.6 but is also present in WP Admin

<img width="1440" alt="screen shot 2018-04-05 at 23 43 23" src="https://user-images.githubusercontent.com/58855/38395502-3199a212-392b-11e8-900a-35b4bada3bec.png">
<img width="1440" alt="screen shot 2018-04-05 at 23 44 15" src="https://user-images.githubusercontent.com/58855/38395518-45d9180c-392b-11e8-9403-6dde5de8e052.png">

## Steps to Reproduce (for bugs)

1. Create several paragraph tags
2. Scroll to the top of the page
3. Open the more options menu on a block around the middle of the page
4.

## Expected Behavior

The menu should drop down or to the left where there is space. The first block currently does this, so there is logic that tries to do this

## Current Behavior

Clipping/obscuring of the menu under some circumstances

## Screenshots / Video

See earlier

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by SuperGeniusZeb** [comment] 2018-04-05 23:51
Duplicate of #4519.

**Comment by noisysocks** [comment] 2018-04-05 23:51
It's particularly easy to reproduce this when you set your browser dimensions to something smaller e.g. 1024x768.

**Closed** 2018-05-23 09:27 UTC
Labels: [Type] Bug
