### ISSUE TITLE
Fix automatic handling of failures during image upload

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#18082] opened 2019-10-23 16:35 UTC
Follow up from https://github.com/WordPress/gutenberg/issues/17474.

After testing this in WP 5.3 beta and RC it became apparent that some servers may be configured to set different error codes on PHP fatal errors, for example 508 or 504. To catch all of them it would be best to look at all HTTP `5xx` errors while post-processing images in https://github.com/WordPress/gutenberg/pull/17858.

This is already implemented in the media modal and the old uploader code, see https://core.trac.wordpress.org/ticket/48379 and https://core.trac.wordpress.org/changeset/46566.

**Comment by azaozz** [comment] 2019-10-23 16:37
The only change needed would be from
`( response.status === 500 || response.status === 502 )`
to
`( response.status >= 500 && response.status < 600 )`

**Comment by youknowriad** [comment] 2019-10-23 16:41
Duplicate of #18081

**Closed by youknowriad** 2019-10-23 16:41 UTC

**Comment by azaozz** [comment] 2019-10-23 16:43
Ah, sorry, didn't see https://github.com/WordPress/gutenberg/issues/18081 was just created for the same thing :)
