### ISSUE TITLE
Previewing shows the galleries inserted through the Classic block as a shortcode

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#13133] opened 2018-12-29 08:08 UTC
**Describe the bug**
If you have inserted a gallery in the Classic editor block, presssing "Preview" will render the gallery shortcode and only get corrected on page refresh.

**To Reproduce**
1. Add a Classic block
2. Add a gallery of images.
3. Click on preview. This will send you to the preview page
4. Return to the editor and there should be a shortcode instead of the gallery instead.

**Expected behavior**
To keep the gallery in place and not to transform them into the shortcode.

**Screenshots**
https://monosnap.com/file/NCSfJBfRIuSWK5AfeUOlMFJZkyFxl9

Tested on both self-hosted and on WordPress.com - same behaviour.

**Comment by talldan** [comment] 2019-07-25 07:04
Hi @Robertght, thanks for reporting this back in 2018 (Sorry for the slow response!).

We discussed this during a core editor triage session (https://wordpress.slack.com/archives/C02QB2JS7/p1564037995221600 - slack link requires a slack account).

A couple of us couldn't reproduce it, so it seems that the issue has been resolved. I'll close this now, let us know though if you're still having issues.

**Closed by talldan** 2019-07-25 07:04 UTC
Labels: Needs Testing, Shortcodes, [Block] Classic
