### ISSUE TITLE
Reusable block, don't display properlly FaceBook, Pinterest, YouTube widget, just a link.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#22245] opened 2020-05-09 10:28 UTC
**Describe the bug**
When we add a FaceBook, Twitter, Pinterest, YouTube link, in a article or page,
in preview or result we have a nice widgets.
If we create a reusable block with these widgets,
they are not shown as widgets but only as links.

**Expected behavior**
The F.B., Twitter, YouTube, Pinterest, etc, widgets should be shown and visible in pages & articles.

**Screenshots**

**Editor version (please complete the following information):**
- wordpress.com version

**Comment by earnjam** [comment] 2020-05-11 18:01
Closing as a duplicate of #14608

**Closed by earnjam** 2020-05-11 18:01 UTC
