### ISSUE TITLE
Add login block to navigation

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#48704] opened 2023-03-02 23:56 UTC
## What problem does this address?
In most menu is usual to add login/logout link.

## What is your proposed solution?
Add login block to allowed navigation block

**Comment by ideadude** [comment] 2023-04-26 14:23
Seems to be a dupe of [#38512](https://github.com/WordPress/gutenberg/issues/38512)

**Comment by skorasaurus** [comment] 2023-05-05 19:05
this has been fixed in https://github.com/WordPress/gutenberg/pull/49160 and will appear in a new version of gutenbeg.

**Closed as completed by skorasaurus** 2023-05-05 19:05 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Block] Navigation, [Block] Login/out
