### ISSUE TITLE
Paragraph Block doesn't Render Custom Backgrounds when in Column Block

### ISSUE THREAD

**Issue by bobmatyas** [WordPress/gutenberg#39555] opened 2022-03-17 19:51 UTC
### Description

Paragraphs with custom background color don't render with the background color on frontend when inside a column block.

### Step-by-step reproduction instructions

1. Create a new page and add a column block w/3 paragraphs
2. Add custom background colors to each block using color picker
3. Backgrounds render in the editor, but not on the front end.

## Editor

<img width="785" alt="Screenshot on 2022-03-17 at 15-48-58" src="https://user-images.githubusercontent.com/45246438/158883914-072c8506-6dda-4e05-be03-5c0de79f2fb1.png">

## Frontend
<img width="1341" alt="Screenshot on 2022-03-17 at 15-48-44" src="https://user-images.githubusercontent.com/45246438/158883987-fe65e43b-819c-4d33-a6e1-c4204c145566.png">

The block with the red color in both screenshots is a paragraph block not inside of a column.

### Environment info

- WordPress v5.9.2
- Gutenberg v12.8.0
- Twenty Twenty One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-03-18 14:49
I could not reproduce it in my environment.
Could you check if each paragraph block has a style attribute on the front end with browser developer tool ?

### Editor

![editor](https://user-images.githubusercontent.com/54422211/159025471-79857e26-b1d9-49e2-a05b-932d141e6723.png)

### Frontend

![frontend](https://user-images.githubusercontent.com/54422211/159025485-80d7cb6b-dff9-47e8-a24c-2212e5b306d4.png)

**Comment by bobmatyas** [comment] 2022-03-18 18:15
I'm not sure what is going on here. I re-entered the backgrounds and 2 out of the 3 worked:
<img width="1515" alt="Screenshot on 2022-03-18 at 13-57-21" src="https://user-images.githubusercontent.com/45246438/159060201-3004c02a-95d5-4458-84bd-812de6b8299b.png">

The middle one has a class rather than the inline style attributes.

**Comment by bobmatyas** [comment] 2022-03-18 18:36
I tried another test and it looks like the color `#8ed1fc` is being converted to the class `has-pale-cyan-blue-background-color` and then it isn't working on the frontend.

<img width="1472" alt="Screenshot on 2022-03-18 at 14-33-57" src="https://user-images.githubusercontent.com/45246438/159063284-68d28325-d2b6-4836-b9ee-9184db1330a1.png">

**Comment by t-hamano** [comment] 2022-03-19 02:28
The `pale-cyan-blue` color is defined in the WordPress core `theme.json`.
If your theme does not have a `theme.json`( like Twenty Twenty One ), you should not be able to use that color:

![editor](https://user-images.githubusercontent.com/54422211/159103354-fe33898e-1ef4-435a-8d04-3aeae13afc85.png)

Have you customized the theme or added `theme.json`?

**Comment by bobmatyas** [comment] 2022-03-19 15:21
I have not customized the theme nor have I added a `theme.json` file. 

# Twenty Nineteen 

I tested on a newly installed default theme (Twenty Nineteen) and got the same result:
<img width="1411" alt="Screenshot on 2022-03-19 at 11-10-23" src="https://user-images.githubusercontent.com/45246438/159126712-9f853a2b-344e-4d74-8703-334fcb5b1e60.png">

# Twenty Twenty Two

If I switch to the Twenty Twenty Two theme, it works:

<img width="1486" alt="Screenshot on 2022-03-19 at 11-09-37" src="https://user-images.githubusercontent.com/45246438/159126708-2ba45786-5362-4a2e-af19-90de6b2c7b50.png">

# Twenty Nineteen (Default Gutenberg Version)

Additionally, if I uninstall Gutenberg v12.8 and use the version included in WordPress v5.9.2, the color works on Twenty Nineteen and Twenty Twenty One:

<img width="1398" alt="Screenshot on 2022-03-19 at 11-13-29" src="https://user-images.githubusercontent.com/45246438/159126806-3fed8499-e370-4145-88ac-97cacc599871.png">

**Comment by bobmatyas** [comment] 2022-03-19 15:22
Thanks for taking the time to look into this.

**Comment by t-hamano** [comment] 2022-03-19 16:23
First, the color palette variation is depending on the theme.
When a color is selected from the color palette, a slug corresponding to the selected color is assigned.

This causes the problem that  the color is not reflected when the theme is switched, because the style corresponding to that class is not defined.

If a block appears whose color is not reflected after switching themes, select the color again from the color palette provided by the theme.

Then you should be able to confirm that the colors are reflected correctly.

**Comment by bobmatyas** [comment] 2022-03-19 19:34
I'm having trouble selecting the color (`#8ed1fc`) from the color picker to test your solution:

https://user-images.githubusercontent.com/45246438/159135625-eda04bf8-91eb-4388-bbaf-1464bd70d276.mp4

That said, it seems like the behavior you are describing is less than ideal (if I am understanding it right). If I had a site that had dozens of blocks configured with custom block colors and I lost them each time I changed themes, that doesn't seem like a good experience.

---

Also, I tried to test this again with a fresh WP install. I activated Twenty Twenty One, created a new page, added 3 column blocks, w/nested paragraph. On the 3 paragraph blocks, I added two custom background colors and set the third as `#8ed1fc`. It doesn't render that color as a background:

<img width="1288" alt="Screenshot on 2022-03-19 at 15-09-47" src="https://user-images.githubusercontent.com/45246438/159135726-df611629-b0cf-4fe4-92c5-fdfd82abc797.png">

**Comment by t-hamano** [comment] 2022-03-20 00:32
Thanks for the info.
I was finally able to reproduce the symptoms.
I think the problem is that when a specific color is specified, it is forced to be converted to a class instead of a style attribute.
(e.g. `#f78da7` / `#ff6900` )

This problem also occurs with text colors or other blocks.
I will try to summarize this issue in more detail and submit another issue.


That said, it seems like the behavior you are describing is less than ideal (if I am understanding it right). If I had a site that had dozens of blocks configured with custom block colors and I lost them each time I changed themes, that doesn't seem like a good experience.

> That said, it seems like the behavior you are describing is less than ideal (if I am understanding it right). If I had a site that had dozens of blocks configured with custom block colors and I lost them each time I changed themes, that doesn't seem like a good experience.

We would be happy to make another issue about this one, if necessary.

**Comment by bobmatyas** [comment] 2022-03-21 16:16
>  was finally able to reproduce the symptoms...
> I will try to summarize this issue in more detail and submit another issue.

Thanks for sticking with this. Feel free to close this once you create the new issue. 

---

As for the other item with losing background colors on theme change, I think that merits an issue. I can make the issue if that's helpful.

**Comment by t-hamano** [comment] 2022-03-24 02:31
> As for the other item with losing background colors on theme change, I think that merits an issue. I can make the issue if that's helpful.

Yes, I think it is worth discussing and I hope you will create issue.

I would like to close this issue after clarifying the problem and making a new issue.

**Comment by t-hamano** [comment] 2022-03-27 07:30
@bobmatyas
I have submitted a new issue #39783, so I close this issue.
If you need further discussion or have questions, please do not hesitate to reopen this issue or create another one.

**Closed as completed by t-hamano** 2022-03-27 07:30 UTC
Labels: [Block] Paragraph
