### ISSUE TITLE
Vendor resources not found

### ISSUE THREAD

**Issue by gd-jroberts** [WordPress/gutenberg#4937] opened 2018-02-07 19:46 UTC
## Issue Overview

The plugin searches for numerous assets in the vendor folder which do not exist. The time searching for these missing assets make the save process take 10+ seconds to complete because it waits for each to 404.

## Steps to Reproduce (for bugs)

1. Install and activate latest version of Gutenberg
2. Open developer tools
3. Watch the console or network panel while attempting to add a new page.

## Expected Behavior

Plugin should not be loading resources that do not exist.

## Current Behavior

Plugin fails to load everything within the vendor folder because they do not exist.

## Possible Solution

Update the plugin or add those resources to the plugin zip.

## Screenshots / Video

![gutenberg2018-02-07at10 34 07am](https://user-images.githubusercontent.com/18486187/35937806-f1e2259a-0c0c-11e8-8163-a1e4c184db63.jpg)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment] 2018-02-08 09:05
This is a duplicate of #3512 and is due to the fact that we're using two versions of TinyMCE at the moment.

**Closed by youknowriad** 2018-02-08 09:05 UTC
