### ISSUE TITLE
Block menu is transparent and unclickable

### ISSUE THREAD

**Issue by lumpysimon** [WordPress/gutenberg#32202] opened 2021-05-25 14:25 UTC
## Description

The block menu often goes transparent and becomes unclickable. This is happening to me when the content has been copied and pasted from Google Docs. I haven't seen it happen for other non-Google Docs content.

## Step-by-step reproduction instructions

1. Paste some content from Google Docs into the block editor
2. Edit it and at some point sometimes (I can't work out any cause or pattern) a block menu will go transparent and not be clickable.
 
## Expected behaviour
The block menu should not be transparent and should be clickable.

## Actual behaviour
See above.

## Screenshots or screen recording (optional)

<img width="698" alt="Screenshot 2021-05-25 at 15 08 59" src="https://user-images.githubusercontent.com/625372/119514003-9b075a00-bd6c-11eb-8669-c888c08dbcfe.png">

<img width="401" alt="Screenshot 2021-05-25 at 15 14 50" src="https://user-images.githubusercontent.com/625372/119514041-a22e6800-bd6c-11eb-9483-23210a7ed9e7.png">

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed (using default block editor)
- Are all plugins except Gutenberg deactivated? No (the site will be unusable)
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Mac Book Pro
- Operating system: MacOS 11.2.3
- Browser: Firefox 88.0.1

**Comment by maccyd10** [comment] 2021-08-17 05:25
@lumpysimon 

I was unable to reproduce this issue. Would you be able to share which theme you were using, and if possible, the actual content that you pasted in to create this issue?

**Comment by amieiro** [comment] 2021-08-26 10:58
I was unable to reproduce this error:

- macOS Big Sur 11.5.2 13" M1
- WordPress 5.8 (local installation)
- Twenty Twenty-One
- Gutenberg ([last trunk commit](https://github.com/WordPress/gutenberg/commit/8d1ea0a3ad5440c64e8fae273e3d8125a3f61500))
- Google Chrome 92.0.4515.159 (Official Build) (arm64)

I have created a new Google doc with title, paragraphs and an unordered list.

![2021-08-26 12-52-19](https://user-images.githubusercontent.com/1667814/130950664-0a6d07c5-f584-4e2e-aefd-43990334dd23.png)

Then I have pasted it on a new post and the block options bar appears fine.

![2021-08-26 12-53-58](https://user-images.githubusercontent.com/1667814/130950737-d8b34735-eb25-4179-b6e4-a9eefeb88395.png)

**Comment by amieiro** [comment] 2021-08-26 11:04
Close this issue because it has a "[Status] Needs More Info" label, but the author didn't respond in 2+ weeks.

**Closed as completed by amieiro** 2021-08-26 11:04 UTC
Labels: [Feature] Blocks, [Status] Needs More Info

**Comment by lumpysimon** [comment] 2021-08-26 11:08
I was able to reproduce it many times at the time, but since upgrading to WP5.8 I've not seen it again, so it looks as if something has fixed it
