### ISSUE TITLE
Undo Font size - can't save page

### ISSUE THREAD

**Issue by Nike555** [WordPress/gutenberg#14069] opened 2019-02-23 21:24 UTC
**Describe the bug**
**Can't save** page/post if you did undo(ctrl+z) for return one step back of font size.

**To Reproduce**
1. Go to edit page in admin panel.
2. Write text in content, select it, and change font size (right menu), for example set "20".
3. Save page.
4. Again change font size, for example set "300".
5. Save page.
4. Press Ctrl+Z or arrow back (3 times, because text size does not return back)
5. Font size returned to "20".
6. You can't save page. (button for save is not enable)

**Screenshots**
https://i.imgur.com/N9SdGl2.gifv

**Wordpress version:**
5.0.3 - ro_RO

**Desktop:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 72.0

**Additional context**
This problem exist **only with font size**, with background or font color - all fine.

**Comment by jorgefilipecosta** [comment] 2019-02-25 11:24
Hi @Nike555, thank you for reporting this issue.
I managed to reproduce it with success.
In my tests, I found that this issue affects every type of attribute.
Even the content of paragraphs:
<img width="1680" alt="screenshot 2019-02-25 at 09 30 11" src="https://user-images.githubusercontent.com/11271197/53333929-2f18bb80-38ef-11e9-810b-34d7c1edd4bd.png">

The issue is caused because the "isDirty" flag is under editor.blocks in the state. This part of the state is affected by the undo mechanism. So when we undo we may revert back to a state where this flag is false even though the post was changed.
We need to move the isDirty flag outside of the part of the state kept on history.
@aduth is applying some changes to the undo/history works. @aduth would it be possible to address this problem as part of the changes you are making or it would be ok to apply a refactor now that moves the isDirty flag outside of the state kept on history?

**Comment by aduth** [comment] 2019-02-25 15:02
> @aduth is applying some changes to the undo/history works. @aduth would it be possible to address this problem as part of the changes you are making or it would be ok to apply a refactor now that moves the isDirty flag outside of the state kept on history?

#13088 would have included what revisions were necessary to support the block module. I'm not sure that this would have fixed the issue described here. There is also #8119, which describe some future improvements needed for history, but the immediate ambitions were scaled back for #13088.

**Comment by youknowriad** [comment] 2019-10-29 16:52
I think this is fixed now after the refactorings to edits and dirty detection.

**Closed by youknowriad** 2019-10-29 16:52 UTC
Labels: [Feature] History, [Type] Bug
