### ISSUE TITLE
Legacy plugin metaboxes disappear when activating custom Gutenberg plugin (wp.plugins.registerPlugin)

### ISSUE THREAD

**Issue by xenobytezero** [WordPress/gutenberg#8742] opened 2018-08-09 01:51 UTC
**Describe the bug**
I have noticed that activating any plugin which uses the ```wp.plugins.registerPlugin()``` call appears to make all plugin defined metaboxes disappear from the Gutenberg editor. They are still present in the Classic editor.

Tested with the following plugins, all of which have their metaboxes dissapear.
- ACF
- Seriously Simple Podcasting
- CoAuthors Plus

**To Reproduce**
1. Install a plugin which adds metaboxes (see examples above)
2. Note that the metaboxes appear in the Gutenberg editor
3. Install the Gutenberg Boilerplate [plugin from here](https://github.com/HardeepAsrani/gutenberg-boilerplate), which provides a simple Gutenberg plugin which registers a Hello World sidebar.
4. Open the Gutenberg editor again
5. Note that the plugin has been activated (new sidebar is visible) but all of the metaboxes are now no longer visible.
6. Note that the metaboxes are still visible in the classic editor

**Expected behavior**
The metaboxes should still be present even when using a custom plugin

**Screenshots**

Screenshot of sidebar before activating the plugin, note the custom ACF and CoAuthors Plus metaboxes
![before_plugin](https://user-images.githubusercontent.com/5059527/43873494-a543e41a-9b7e-11e8-93a1-cb9752d558de.png)

Screenshot of same post after activating the plugin, note the metaboxes are gone, and the custom plugin is active (the globe icon in the top right).
![after_plugin](https://user-images.githubusercontent.com/5059527/43873493-a52b18b8-9b7e-11e8-99e0-9cd4a4ed7583.png)

**Desktop (please complete the following information):**
 - OS: Win10x64
 - Browser: Chrome
 - Version: Version 69.0.3497.23 (Official Build) beta (64-bit)

- Browser: Edge
- Version: Microsoft Edge 42.17134.1.0

**Additional context**
Gutenberg Plugin Version 3.4.0

**Comment by youknowriad** [comment] 2018-08-09 08:32
Looks like a duplicate of #7537

**Closed by youknowriad** 2018-08-09 08:32 UTC

**Comment by xenobytezero** [comment] 2018-08-10 00:54
Confirmed that this is fixed in 3.5.0
