### ISSUE TITLE
Group Block - clear visual distinction between blocks in admin

### ISSUE THREAD

**Issue by paulkirspuu** [WordPress/gutenberg#15001] opened 2019-04-16 13:38 UTC
Suggestion for improvement regarding the Group block:

- update styling to have a clear distinction between Group blocks, e.g. https://i.snag.gy/cup3sY.jpg

Your thoughts, please.

**Comment by lkraav** [comment] 2019-04-16 13:53
"Visual distinction"

**Comment by youknowriad** [comment] 2019-04-17 12:51
I think this is a duplicate of #14935 and will be closed by #14961

**Closed by youknowriad** 2019-04-17 12:51 UTC
Labels: [Block] Group, [Type] Enhancement
