### ISSUE TITLE
Pattern block inside pattern results in empty pattern preview

### ISSUE THREAD

**Issue by ellenbauer** [WordPress/gutenberg#41890] opened 2022-06-23 07:52 UTC
### Description

Placing a pattern block inside a pattern using the new 'pattern' folder does work, but the Pattern preview is empty.

Example, I wanted to create a page pattern with multiple smaller patterns inside, so that later on only the smaller pattern can be updated. See code in my pattern.php file:
<img width="1168" alt="Screen Shot 2022-06-23 at 4 21 10 PM" src="https://user-images.githubusercontent.com/17613630/175244617-41490b6c-a284-41e2-973d-4ac4ae80d29f.png">

The pattern can be inserted and works, but the Pattern preview is broken and only shows an empty pattern, see: 
<img width="2093" alt="Screen Shot 2022-06-23 at 4 21 30 PM" src="https://user-images.githubusercontent.com/17613630/175244783-f7a6784e-8b07-44d5-a832-2abbb70da187.png">

### Step-by-step reproduction instructions

1. Create a pattern using the pattern block and place one or more pattern inside using this method:

``<!-- wp:pattern {"slug":"themename/your-pattern-slug"} /-->``
``<!-- wp:pattern {"slug":"themename/your-pattern-slug"} /-->``

2. Preview result in the Pattern explorer or sidebar.
3. Place the pattern inside the editor.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-06-23 07:55
Hi, @ellenbauer

I think this is a duplicate of #39732.

**Comment by ellenbauer** [comment] 2022-06-23 08:15
Oh, yes, so sorry, I didn't find that one. I think we can close it then.

**Closed as completed** 2022-06-23 08:20 UTC
Labels: [Status] Duplicate, [Feature] Patterns, [Block] Pattern
