### ISSUE TITLE
SelectControl doesn’t work if it’s wrapped in a Tooltip component

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#38113] opened 2022-01-20 14:39 UTC
### Description

In Firefox 96 (Linux and Windows), user can’t change the value of a `SelectControl` with their mouse when the `SelectControl` is wrapped in a `Tooltip` component. If they use the keyboard arrows instead, it works as expected.

### Step-by-step reproduction instructions

1. Create the following `Test` component:

```jsx
const Test = () => {
  const [ option, setOption ] = useState( 'b' );
  return (
    <div>
      <Tooltip text="Tooltip" position="top center">
        <span>
          <SelectControl
            label="SelectControl"
            value={ option }
            options={ [
              { value: 'a', label: 'Aaa' },
              { value: 'b', label: 'Bbb' },
              { value: 'c', label: 'Ccc' },
            ] }
            onChange={ ( v ) => setOption( v ) }
          />
        </span>
      </Tooltip>
    </div>
  );
};
```

2. Try to change the value of the `SelectControl` with your mouse and the value won’t change.

### Environment info

- WordPress 5.8.3
- Gutenberg: tested with no Gutenberg plugin as well as Gutenberg v.12.4.0
- OS/Browser: Windows 10/Firefox 96.0.1 and Linux/Firefox 89.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-02-06 12:23
I tested in a similar environment, but could not reproduce the problem.

Please see:

https://user-images.githubusercontent.com/54422211/152680467-7449dc42-318d-4a89-ae6a-7bf189026241.mp4

## Code 

```javascript
import { useState } from '@wordpress/element';
import { registerBlockType } from '@wordpress/blocks';
import { useBlockProps } from '@wordpress/block-editor';
import { SelectControl, Tooltip } from '@wordpress/components';

registerBlockType( 'create-block/gutenpride', {
  edit: () => {
    const [ option, setOption ] = useState();
    return (
      <div { ...useBlockProps() }>
        <p>SelectControl value: { option }</p>
        <Tooltip text={ 'tooltip label' }>
          <span>
            <SelectControl
              options={ [
                { value: 'AAA', label: 'AAA' },
                { value: 'BBB', label: 'BBB' },
                { value: 'CCC', label: 'CCC' },
                { value: 'DDD', label: 'DDD' },
              ] }
              onChange={ ( v ) => setOption( v ) }
            />
          </span>
        </Tooltip>
      </div>
    );
  },
  save: () => null,
} );
```

## Environment info
- WordPress version: 5.9
- Gutenberg version: 12.5.3 (plugin enabled)
- OS: Windows 11
- Browser: Firefox 96.0.3

**Comment by davilera** [comment] 2022-02-06 15:04
> I tested in a similar environment, but could not reproduce the problem.

Thanks for trying to reproduce the issue, @t-hamano. Your `SelectControl` is missing the `value={ option }` attribute.

**Comment by t-hamano** [comment] 2022-02-06 15:41
@davilera 

Thanks for the advice.
Indeed, I was able to reproduce it here.

For some reason, it only seems to happen when using a `SelectControl` wrapped in a `Tooltip` and a Firefox browser.

**Comment by t-hamano** [comment] 2022-07-23 09:46
@davilera

We were able to solve this problem with #42483.
After testing again, we no longer reproduce this issue and would like to close it.
If the issue has not been resolved, please feel free to reopen it.

**Closed as completed by t-hamano** 2022-07-23 09:46 UTC
Labels: Browser Issues, [Package] Components
