### ISSUE TITLE
When I'm trying to use Query Loop block, it is not giving me any option to filter via custom field.

### ISSUE THREAD

**Issue by muhammadharoonbro** [WordPress/gutenberg#44577] opened 2022-09-29 12:44 UTC
### Description

When I'm trying to use Query Loop block, it is not giving me any option to filter via custom field.

### Step-by-step reproduction instructions

Try using Query Loop block and you will see it for yourself. Because I'm trying to fetch all results where students' subject is English (acf field).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment] 2022-10-17 19:59
Duplicate of #31390

**Closed as not planned by kathrynwp** 2022-10-17 19:59 UTC
Labels: [Type] Enhancement, [Block] Query Loop
