### ISSUE TITLE
Keyboard shortcut for tab character is needed to insert a tab and/or indent list item

### ISSUE THREAD

**Issue by jb510** [WordPress/gutenberg#12142] opened 2018-11-21 01:32 UTC
It's impossible to insert a real tab character or indent a list using the keyboard.  Perhaps these should be two issues, but for me it's simply the need for a keyboard shortcut that does both things.

In the name of accessibility and avoiding a keyboard tab trap the tab key is used to navigate between blocks. I still think that is a design flaw and an alternative should have been specified to "exit the editor" like Google Docs does (alt-tab). However, there then needs to be an alternative keyboard shortcut added to actually indent a list and/or insert a tab character.

This was raised many times, a few of those:
https://github.com/WordPress/gutenberg/issues/4181
https://github.com/WordPress/gutenberg/issues/5087
https://github.com/WordPress/gutenberg/issues/7051

Use cases:
1. Indenting lists via the keyboard (which is needed for a11y reasons as well)
2. Indenting lines inside a pre blocks (for example code snippets)

Please note: This is not the same thing as using the TinyMCE indent/outdent icons (which also need keyboard shortcuts) as they add/remove inline padding to the html element, not insert an actual tab character.

**Comment by mrwweb** [comment] 2018-11-22 08:13
At a bare minimum there _has_ to be a keyboard shortcut to indent lists.

**Comment by mbedded** [comment] 2018-12-15 12:50
That's true. I was using the new editor for the first time and i was sketching some items i want to discuss/explain in my article. And "TAB" did not indent my list. That's a default behavior in so many applications.

**Comment by gziolo** [comment] 2019-01-03 09:23
Agreed about `tab` support. Let's close this one as a duplicate of #9611.

**Closed by gziolo** 2019-01-03 09:23 UTC
Labels: Needs Decision, Writing Flow
