### ISSUE TITLE
REST: excessive authors requests on sites with many authors when editing

### ISSUE THREAD

**Issue by rogertheriault** [WordPress/gutenberg#15985] opened 2019-06-04 19:12 UTC
**Describe the bug**
The REST API is used to request authors to support the Authors module in the Gutenberg editor.

That's problematic on sites with many thousands (or more) of authors.

Even disabling post type support for author, the REST requests still fire continually.

e.g.

`wp-json/wp/v2/users?who=authors&per_page=100&_locale=user&page=42`

On a site with thousands of authors, this results in hundreds of REST requests from each browser, for each currently open draft or post.

The resulting queries can cause DB performance issues.

**To reproduce**
1. On a site with 40,000 editors, open a new draft
2. Open the browser's developer tools, network tab, and inspect the XHR requests
3. Watch the number of requests to `wp-json/wp/v2/users?who=authors&per_page=100&_locale=user&page={n}`
4. Open several editor tabs (or have several editors do this)
5. Check the DB health

**Expected behavior**
Fewer resulting DB queries to accomplish this functionality.

Most of the time, authors will not be changed, so it seems one alternative might be to only obtain authors when actually needed.

Possible solutions:
- being able to disable the requests on the browser
- alternate functionality to modify authors only as needed

**Additional context**
WordPress core 5.2.1

**Comment by swissspidy** [comment] 2019-06-04 21:13
Sounds like a duplicate of #7384 which has a PR at #7385.

**Comment by rogertheriault** [comment] 2019-06-05 00:54
Thanks @swissspidy it does look like that would solve this, as a much more user friendly refactor. I’ve chimed in on the other issue.

**Comment by aduth** [comment] 2019-06-05 19:38
Let's consolidate this to #7384. I'll add a clarifying note there about the network impact described in this issue.

**Closed by aduth** 2019-06-05 19:38 UTC
