### ISSUE TITLE
Classic editor in columns cannot be edited after saving

### ISSUE THREAD

**Issue by DDI-Saadi** [WordPress/gutenberg#14958] opened 2019-04-12 14:38 UTC
**Describe the bug**
When creating a "Columns" block and then using the "Classic" block inside one of the columns, the block becomes unusable after saving and reloading the editor.
Instead of the classic editor the message "This block contains unexpected or unusable content" appears,

**To reproduce**

1. Create or edit a page
2. Add a "Column" block
3. Add a "Classic" block inside one of the columns
4. Write anything into the Classic block (like "hello")
5. Save Page
6. Close page
7. Edit page again

**Expected behavior**
Classic editor should show up again when trying to edit a page after saving and reloading it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox & Chrome

**Additional context**
- Wordpress Version 5.1.1

**Comment by DDI-Saadi** [comment] 2019-04-12 14:45
I need to extend the severity of the issue.

If you try to edit the page again and save it (without even doing anything), a lot of text that was in the classic editor just dissapears. If or how much gets lost seems to be random.

**Comment by MethylBromide** [comment] 2019-05-31 01:16
I too am seeing this. Is there any way to "bump" its priority?

**Comment by talldan** [comment] 2019-06-17 02:44
Hi @DDI-Saadi, thanks for the bug report. This is a duplicate of #13187, so I'll close your issue. That issue has been given a priority of high, it just needs someone to work on it now.

**Closed by talldan** 2019-06-17 02:44 UTC
Labels: [Block] Classic, [Block] Columns, [Status] Duplicate
