### ISSUE TITLE
Slash command no longer working in Responsive Design Mode

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24748] opened 2020-08-23 10:22 UTC
**Describe the bug**
The Slash command no longer works in Responsive Design Mode. As soon as you type the slash (/) the cursor appears to move to the left of it which means the text that you type next doesn't work to show the list of blocks. It's also impossible to insert a slash and then use the cursor keys to move your cursor to the right of the slash.

vid: https://share.getcloudapp.com/4gu9lgLd

**To reproduce**
Steps to reproduce the behavior 1:
1. Edit a page
2. Insert an empty block into your content
3. Type '/im' to show a list of image type blocks
4. See that the text in the Paragraph block is 'im/' instead of '/im' and therefore no blocks appear

Steps to reproduce the behavior 2:
1. Edit a page
2. Insert an empty block into your content
3. Type '/' and try to use the cursor keys to move the cursor to the right of the slash
4. See that you can't move the cursor

**Expected behavior**
The Editor should work in Responsive Design Mode in exactly the same way as it does in the normal browser mode

**Editor version (please complete the following information):**
- WordPress version: [5.5]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):
- OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

**Comment by talldan** [comment] 2020-08-25 01:38
Same as the other issue, please could you clarify what 'Responsive Design Mode' is?

**Comment by maddisondesigns** [comment] 2020-08-25 02:47
Responsive Design Mode is a tool in Firefox that allows you to easily change the viewport width, among other things. It's ideal for when you're developing/testing responsiveness. It's also useful when writing WordPress documentation and you need screenshots to be certain size.

example vid: https://share.getcloudapp.com/nOuk9dLk

more info: https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by talldan** [comment] 2020-12-09 04:20
It is a curious bug, but I'm going to close this as we can't effectively consider the Firefox dev tools as a supported environment. In testing I haven't been able to reproduce the issue in mobile or desktop browsers, so it could be a bug with the responsive mode in Firefox.

As per my comment here - https://github.com/WordPress/gutenberg/issues/24735#issuecomment-679567381 - this only seems to be a problem when disabling 'Enable Touch Simulation', which should really make Firefox behave just like itself, right? Maybe I'm misunderstanding, but it shouldn't have to do anything other than change the viewport size and maybe overwrite the user agent string if that's set, but instead you get these bugs. So that reaffirms my belief that it's an issue in Firefox.

If the issue can be reproduced in a production (non-development mode), then I think it could be considered as something we should definitely track.

**Closed by talldan** 2020-12-09 04:20 UTC
Labels: [Status] Needs More Info
