### ISSUE TITLE
"Replace template" option not visible with Gutenberg 16.7.1

### ISSUE THREAD

**Issue by luminuu** [WordPress/gutenberg#55218] opened 2023-10-10 18:49 UTC
### Description

I wanted to test [this functionality](https://github.com/WordPress/gutenberg/pull/54609) with Beta 3 and Twenty Twenty-Four, but when I have the Gutenberg plugin version 16.7.1 activated, the ellipsis icon does not show up. When I edit the template to get the "Clear customizations" function to show, it does not appear either. Deactivating Gutenberg brings back the functionality.

### Step-by-step reproduction instructions

Follow the instructions from the video in the above linked PR.
1. Open the site editor
2. Go to Templates
3. Select "Blog Home" template
4. Open the template to edit
5. In the sidebar next to the "Blog Home" headline, either: no ellipsis icon appears; or only the item "Clear customizations"

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7585600/d08a5d9e-a946-406d-8cd9-046727e3de84

### Environment info

- WordPress 6.4 Beta 3
- Gutenberg plugin 16.7.1 from the plugin repository
- Twenty Twenty-Four theme from the Github repository, latest trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2023-10-18 08:02
I am not able to reproduce this with current Gutenberg trunk.

**Comment by t-hamano** [comment] 2023-11-24 13:16
I believe this is correct behavior. #54609 was backported to WP6.4, but is part of version 16.8 in the Gutenberg plugin. Gutenberg version 16.7 does not yet have this feature implemented.

Therefore, I would like to close this issue.

**Closed as not planned by t-hamano** 2023-11-24 13:16 UTC
Labels: [Feature] Site Editor
