### ISSUE TITLE
Columns with padding breaks responsive layout

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#36404] opened 2021-11-11 12:05 UTC
### Description

When adding padding to an individual column in the columns block, the layout is broken in medium browser widths (600px to 781px).

### Step-by-step reproduction instructions

Add a columns block with more than 1 column.
Leave the default 'Stack on mobile' option on.
Adjust the padding within each column to a value greater than zero.
View the columns at browser widths between 600 and 781, and notice the 50/50 layout is broken.

### Screenshots, screen recording, code snippet

![columns-with-padding-responsive](https://user-images.githubusercontent.com/76742815/141295101-cb9f9d9c-5c29-466b-9072-01dd263380d5.jpg)

### Environment info

WP 5.8.2
Gutenberg 11.9.0
Any theme that does not provide it's own columns styling/layout override.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by webmandesign** [comment] 2021-11-27 16:26
Adding to the issue as this is related:

Not only that, but when setting up custom column widths for large screens, we can not control the smaller screen widths, which is unfortunate. And especially on tablet screen widths forcing [`flex-basis: calc( 50% - var(--column_gap) / 2)!important;`  styles](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/columns/style.scss#L46) can render creative layouts very unpleasant.

Some screenshots:

![issue](https://user-images.githubusercontent.com/2456735/143689136-5ac4b4d1-9b0c-4dcc-9412-5fa0c8bc48a1.jpg)
<img width="359" alt="Screen Shot 2021-11-27 at 13 02 08" src="https://user-images.githubusercontent.com/2456735/143689144-e4502e72-5d34-4b1b-885a-28102b68d887.png">

We really need responsive column width (and padding) setup!

**Comment by webmandesign** [comment] 2021-11-27 16:30
BTW, shoudn't  [`flex-basis: calc( 50% - var(--column_gap) / 2)!important;`  styles](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/columns/style.scss#L46) be a theme territory?

**Comment by jordesign** [comment] 2023-08-18 01:05
Checking back on this issue - I'm no longer able to recreate it. It seems the stacking behaviour kicks in sooner (at 781px) but even then the padding seems to behave correctly.


https://github.com/WordPress/gutenberg/assets/1842363/c8a792df-9e12-4ae7-896c-c7d59e102948

Accordingly I'll close this as no longer reproducible - but please feel free to reopen if there's something I've missed.

**Closed as not planned by jordesign** 2023-08-18 01:05 UTC
Labels: [Block] Columns, [Feature] Design Tools
