### ISSUE TITLE
Edit component remounts on input when block has block styles

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#28132] opened 2021-01-12 11:43 UTC
**Describe the bug**
I have a custom block with a `URLInput` component. When a post is selected, I fetch its data with the REST API and show a few data. Then I have almost the same block, but with a block style registered. And in that block, the edit component remounts after every input in the `URLInput` component.

I created a GitHub repo with a reduced test case, where the edit component is the same for two blocks, the only difference is one has block styles and the other does not: https://github.com/florianbrinkmann/styles-issue-example-block/blob/master/src/index.js

**To reproduce**
1. Download the `Styles issue example block` plugin from https://github.com/florianbrinkmann/styles-issue-example-block/
2. Install and activate it.
3. Add the blocks `Styles Issue Block 1 (with error)` and `Styles Issue Block 1 (without error)` to a post or page.
4. Type something in the `URLInput` of the blocks.
5. In the first block, the input should loose focus on each input.

**Expected behavior**
The edit component should not remount.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Core version of the block editor.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 85.0b7 (64-Bit)

**Comment by stokesman** [comment] 2021-01-13 05:35
I gave this a try and at first, I couldn't reproduce. Then I remembered to disable the Gutenberg plugin and could reproduce. So it would seem that whatever the cause it's now fixed.

I noticed a duplicate toolbar would appear when I selected the block:
![image](https://user-images.githubusercontent.com/9000376/104410626-9bb9f500-551d-11eb-9d53-ddb050c09009.png)

And hovering the block icon in that toolbar would outline the "Small text" block preview. So that preview block has its own toolbar showing up somehow!
![image](https://user-images.githubusercontent.com/9000376/104410705-c146fe80-551d-11eb-85cf-5c3e86ec3ec8.png)

I'm not sure the loss of focus is due to a remount. I noticed that the loss of focus and the duplicate toolbar only occur when the sidebar is open and on the Block tab. The block works fine if the sidebar is closed or if it's open and the Post tab is selected instead.

Not sure what would be the cause and haven't tried finding related issues.

**Comment by florianbrinkmann** [comment] 2021-01-13 06:32
Thanks for looking into this! Yes, I noticed the duplicate toolbar, too. In my initial commit of the example plugin, I had `componentDidMount()` in the edit component (https://github.com/florianbrinkmann/styles-issue-example-block/blob/c74d5c9688d9eec8af4f8d56747e685db2161c91/src/index.js). I added a `console.log('Mounted')` there and it got fired after each input (that was not the case with the other block), so that was the reason for me to say it remounts.

I can reproduce that it works when the sidebar is closed.

> Then I remembered to disable the Gutenberg plugin and could reproduce. So it would seem that whatever the cause it's now fixed.

That’s great to hear.

**Comment by peterwilsoncc** [comment] 2021-04-27 05:23
This was [discussed during a triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1619500068310700) today.

A couple of people tested it in WordPress 5.7.1 both with and without the Gutenberg plugin enabled. None of the testers were able to reproduce the issue so it seems it has been fixed sometime between logging your report and now.

Thanks for providing the plugin to test with, it was a great help. I'll close this issue for now but please follow up if you are still experiencing the problem.

**Closed by peterwilsoncc** 2021-04-27 05:23 UTC
Labels: Needs Technical Feedback, Needs Testing, [Feature] Style Variations
