### ISSUE TITLE
create-block and/or wp-scripts does not install correctly (following the tutorial)

### ISSUE THREAD

**Issue by JanLukasGithub** [WordPress/gutenberg#63701] opened 2024-07-18 11:32 UTC
### Description

I wanted to start a new Gutenberg Block plugin by following [this tutorial](https://developer.wordpress.org/block-editor/getting-started/tutorial/). But when I tried running `npx @wordpress/create-block@latest copyright-date-block --variant=dynamic` it would error with the output pasted below. I don't know if this is a bug with create-block or the scripts package. Manually running `npm run format` or `npm run build` does not work either, and I haven't found an easy workaround by invoking the script manually (usually errors because of missing modules/requires).

I have verified and even cleared the npm cache.

### Step-by-step reproduction instructions

1. Open a terminal
2. Run the command `npx @wordpress/create-block@latest any-slug-here`
3. Get the error pasted below
4. Running `npm run format` manually or even going into `node_modules/@wordpress/scripts/bin/` and running `wp-scripts.js format` doesn't work either

### Screenshots, screen recording, code snippet

The output of `npx @wordpress/create-block@latest any-slug-here` run in an empty directory:
    
    user@host:~/path/to/empty/dir$ npx @wordpress/create-block@latest any-slug-here

    Creating a new WordPress plugin in the any-slug-here directory.

    Creating a "block.json" file.

    Creating a "package.json" file.

    Installing `@wordpress/scripts` package. It might take a couple of minutes...

    Formatting JavaScript files.
    /home/user/.npm/_npx/9444c7de6ab42aae/node_modules/execa/lib/error.js:59
                  error = new Error(message);
                          ^

    Error: Command failed with exit code 127: npm run format
    sh: 1: wp-scripts: not found

    > any-slug-here@0.1.0 format
    > wp-scripts format

    at makeError (/home/user/.npm/_npx/9444c7de6ab42aae/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/user/.npm/_npx/9444c7de6ab42aae/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/user/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:25:2)
    at async module.exports (/home/user/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/scaffold.js:156:4)
    at async Command.<anonymous> (/home/user/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/index.js:120:6) {
      shortMessage: 'Command failed with exit code 127: npm run format',
      command: 'npm run format',
      exitCode: 127,
      signal: undefined,
      signalDescription: undefined,
      stdout: '\n> any-slug-here@0.1.0 format\n> wp-scripts format\n',
      stderr: 'sh: 1: wp-scripts: not found',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false
    }

    Node.js v22.5.0
The output of `npm run format` run in `any-slug-here`:
    
    user@host:~/path/to/empty/dir/any-slug-here$ npm run format

    > any-slug-here@0.1.0 format
    > wp-scripts format

    sh: 1: wp-scripts: not found
The output of `node_modules/@wordpress/scripts/bin/wp-scripts.js format` run in `any-slug-here`:
    
    user@host:~/path/to/empty/dir/any-slug-here$ node_modules/@wordpress/scripts/bin/wp-scripts.js format
    package.json 39ms
    src/block.json 9ms
    src/edit.js 22ms
    src/index.js 7ms
    src/save.js 3ms
    src/view.js 5ms
The output of `node_modules/@wordpress/scripts/bin/wp-scripts.js build` run in `any-slug-here`:
    
    user@host:~/path/to/empty/dir/any-slug-here$ node_modules/@wordpress/scripts/bin/wp-scripts.js build
    node:internal/modules/cjs/loader:1222
      throw err;
      ^

    Error: Cannot find module 'webpack-cli/package.json'
    Require stack:
    - /home/user/path/to/empty/dir/any-slug-here/node_modules/webpack/bin/webpack.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
        at Function.resolve (node:internal/modules/helpers:133:19)
        at runCli (/home/user/path/to/empty/dir/any-slug-here/node_modules/webpack/bin/webpack.js:78:26)
        at Object.<anonymous> (/home/user/path/to/empty/dir/any-slug-here/node_modules/webpack/bin/webpack.js:187:2)
        at Module._compile (node:internal/modules/cjs/loader:1504:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
        at Module.load (node:internal/modules/cjs/loader:1282:32)
        at Module._load (node:internal/modules/cjs/loader:1098:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:215:24) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/user/path/to/empty/dir/any-slug-here/node_modules/webpack/bin/webpack.js'
      ]
    }

    Node.js v22.5.0

### Environment info

- Distro: Kubuntu 24.04
- Kernel: 6.8.0-35-generic (64-bit)
- `node --version`: v22.5.0
- `npm --version`: 10.8.2
- `npx --version`: 10.8.2
- I'm happy to provide more info if needed

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ryanwelcher** [comment] 2024-07-18 14:53
I am able to reproduce this as well using node 22.5.0. The recommended version is the LTS which is currently at 20.15.1. When I switched to that version, the issue did not occur. Can you test and confirm?

**Comment by JanLukasGithub** [comment] 2024-07-19 13:44
Yes, it doesn't happen when using version 20.15.1 (then see this as something that should be fixed until v22.5.0 becomes the LTS version later this year).

I didn't understand the node website correctly and thought that all even numbered versions were LTS versions right from the beginning, as that's how most software projects I know of do it. But I guess this makes sense as well when thinking about it :+1:

**Comment by ryanwelcher** [comment] 2024-07-19 16:02
It looks like there may be some issues with 22.5.0:

* https://github.com/nodejs/node/issues/53902
* https://github.com/npm/cli/issues/7657

There is a new point release (22.5.1) that I just tested against and didn't get any errors. I'm going to close this out but feel free to comment/reopen if issues persist.

**Closed as completed by ryanwelcher** 2024-07-19 16:02 UTC
Labels: [Type] Bug, [Status] Needs More Info

**Comment by mohamed7x** [comment] 2025-02-11 21:30
# Troubleshooting the Create-Block Command in WordPress Block Development

While developing a WordPress block using the create-block tool, I encountered two main issues:

1. The command failed when using `npx` due to an incorrect package name.
2. The shell provided by Local by Flywheel did not work as expected, whereas running the commands in PowerShell did.

In this post, I explain the root causes of these problems and outline the solutions that worked for me.

## Problem Description

### Issue 1: Incorrect Package Name with npx

I initially attempted to create a new block with the following command in PowerShell:

```bash
npx @wordpress/wp-create-block@latest copyright-date-block2 --variant=dynamic
```

This command failed. However, the following command, which uses the globally installed version, worked perfectly:

```bash
wp-create-block copyright-date-block --variant=dynamic
```

### Issue 2: Shell Environment Differences

I also noticed that when I ran the command using the shell provided by Local by Flywheel, it failed. On the other hand, executing the same command in PowerShell worked without any issues.

## Root Causes

### 1. Incorrect Package Name

- **Mistaken Package Name:**  
  The command using `npx` was referencing `@wordpress/wp-create-block@latest` instead of the correct package name. The proper package name is **`@wordpress/create-block`**.
  
- **Global vs. npx Execution:**  
  When the package is installed globally with:
  ```bash
  npm install -g @wordpress/create-block
  ```
  it creates an executable named `wp-create-block`. This is why the global command works flawlessly.

### 2. Differences in Shell Environments

- **Local by Flywheel Shell:**  
  The shell provided by Local by Flywheel often runs in an isolated environment or container. This means it might not inherit the same environment variables as your system shell (such as PowerShell). In particular, it may not have the global npm modules’ path (e.g., `C:\Users\bouda\AppData\Roaming\npm`) included in its `PATH` variable. As a result, commands like `wp-create-block` may not be recognized when running inside that shell.
  
- **PowerShell:**  
  PowerShell uses your system's environment variables, including the correct `PATH` that contains the global npm binaries. This is why the same command works successfully in PowerShell.

## The Solution

### 1. Correcting the Package Name with npx

To resolve the package name issue, use the correct command with `npx`:

```bash
npx @wordpress/create-block@latest copyright-date-block2 --variant=dynamic
```

This command downloads and uses the proper package for creating your block.

### 2. Using the Globally Installed Command

If you prefer a more streamlined approach, install the package globally:

```bash
npm install -g @wordpress/create-block
```

Then, use the globally installed command:

```bash
wp-create-block copyright-date-block --variant=dynamic
```

Since this version is installed globally, it works reliably in your system shell (like PowerShell).

### 3. Recommendation on Shell Usage

- **Prefer Using PowerShell or CMD:**  
  Given that the shell provided by Local by Flywheel might not have the correct `PATH` settings or environment configurations, it is recommended to run development commands (like creating a block) using your system’s shell (e.g., PowerShell, CMD, or Git Bash). Once the block is created and built, you can then deploy or test it within Local by Flywheel.

- **Adjusting Environment in Local by Flywheel (Optional):**  
  If you must use the Local by Flywheel shell, check its environment settings and ensure that the path to the global npm modules (such as `C:\Users\bouda\AppData\Roaming\npm`) is included in the `PATH` variable. However, modifying the environment in an isolated shell might be more complex than simply using your system shell.

## Conclusion

The issues were caused by two factors:

1. **An incorrect package name** was used with `npx`—the correct package is `@wordpress/create-block` (which results in the `wp-create-block` command when installed globally).
2. **Differences in shell environments:** The isolated shell in Local by Flywheel did not have the same environment variables (especially the `PATH` to global npm modules) as PowerShell, leading to command recognition issues.

By using the correct package name with `npx` or by installing the package globally and using PowerShell for development tasks, these problems were resolved.

I hope this explanation helps anyone who encounters similar issues during WordPress block development. Feel free to leave any questions or suggestions in the comments!
