### ISSUE TITLE
Possible to paste links inside a button

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12223] opened 2018-11-22 13:17 UTC
The button block has format tools for bold, italic, and strikethrough. However, if you paste content it's possible to insert additional formatting, including links. This leads to nested links, which is not valid HTML.

Here's the button editor:

<img width="309" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48905093-7ad34900-ee58-11e8-8235-ff373c2705fc.png">

And copy/pasting some text with links results in this:

<img width="559" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48905133-9fc7bc00-ee58-11e8-991e-61d50f92e54f.png">

Looking at the HTML we have nested links:

```html
<div class="wp-block-button">
  <a class="wp-block-button__link">She is also the daughter of <a href="http://mlp.wikia.com/wiki/Twilight_Velvet_and_Night_Light">Twilight Velvet and Night Light</a></a>
</div>
```

**To Reproduce**
1. Create button block
2. Copy some text from a web page with links
3. Paste into the button

**Expected behavior**
Links to be stripped

**Comment by johngodley** [comment] 2018-11-22 13:38
Also noting that after saving the post and then reloading the page, the block is shown invalid.

**Comment by iseulde** [comment] 2018-11-26 17:36
Duplicate of #7591.

**Closed by iseulde** 2018-11-26 17:36 UTC
Labels: [Block] Button, [Component] Raw Handling, [Component] Rich Text, [Type] Bug

**Comment by Inwerpsel** [comment] 2020-01-06 13:23
> Duplicate of #7591.

The referred ticket would create an interface that would allow to more easily fix this issue, but it would not do so by itself. This is a bug report, so why close it unless the bug is fixed or there is an other bug report that duplicates it?
