### ISSUE TITLE
Post Title block: Letter case setting in the editor doesn't work when it's a link

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#65297] opened 2024-09-12 17:45 UTC
### Description

This is probably related to https://github.com/WordPress/gutenberg/pull/64911, https://github.com/WordPress/gutenberg/issues/65169, and https://github.com/WordPress/gutenberg/issues/41725. 

I also noticed an issue with the post title block.

### Step-by-step reproduction instructions

In the theme.json the theme has this:
```
"core/post-title": {
	"typography": {
		"textTransform": "uppercase"
	}
}
```
In the editor, the user changes the letter case setting to lowercase.

![CleanShot 2024-09-12 at 18 14 45@2x](https://github.com/user-attachments/assets/f3134063-e8b6-4067-975a-a09ee991d4e5)

It looks good in the editor, but when you see it on the front of the site, it stays uppercase since it's overridden by the style applied to the link.

![CleanShot 2024-09-12 at 18 22 46@2x](https://github.com/user-attachments/assets/8e272bc9-29db-44df-ac48-3041477bc24c)

If the post title isn't a link, the latter case setting is applied correctly.

![CleanShot 2024-09-12 at 18 28 42@2x](https://github.com/user-attachments/assets/6a1de9bc-b97b-4ca3-b5fd-f7394023377b)

### Environment info

WP: 6.6.2
Gutenberg: Trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by andrewserong** [comment] 2024-09-13 06:15
This might be fixed by https://github.com/WordPress/gutenberg/pull/65307 if you'd like to give it a test!

**Comment by ntsekouras** [comment] 2024-11-12 11:12
I couldn't reproduce and it seems fixed. Closing, but feel free to reopen if I missed to test a specific use case..

**Closed as completed by ntsekouras** 2024-11-12 11:12 UTC
Labels: [Type] Bug
