### ISSUE TITLE
FSE: Link Style Doesn't Match Page Editor Style

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#43939] opened 2022-09-07 08:47 UTC
### Description

Links are underlined in the Site Editor. In the Page editor, links are not underlined. The live view of the site does not underline links unless they are hovered.

Originally reported here: https://github.com/Automattic/themes/issues/6521

### Step-by-step reproduction instructions

Add a link to the home page editor. Notice that it is not underlined.
View the home page through the site editor. The link will be underlined.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/6737345/188834008-ae3c4ad9-bbaa-45d8-b288-09abf195e455.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2022-09-08 02:09
@Robertght Would you be able to improve the reproduction steps.

When I tested (adding a link to a paragraph in the page editor), the underline shows up fine:
![Screen Shot 2022-09-08 at 10 08 11 am](https://user-images.githubusercontent.com/677833/189017759-e04fd18d-19a5-4407-b6ae-e3b49bb84c0f.png)

But I have a feeling I might not be reproducing this as intended. The part I'm not sure about is "Add a link to the home page editor."

**Comment by Robertght** [comment] 2022-09-08 04:26
Thank you @talldan !

It looks like this is theme-specific for now.

I noticed the link underline doesn't show up on the frontend as opposed to the Site editor. Is this expected or an issue? 
If an issue, should I adjust this report or create a new one?

**Comment by talldan** [comment] 2022-09-08 06:17
So the situation is (for a specific theme):
- Frontend - no underline
- Page editor - no underline
- Site editor - underline

Is that correct?

It may be a bug with the theme, but it's hard to say for sure. Is there a theme I can test with?

**Comment by Robertght** [comment] 2022-09-08 06:40
Correct!

However, the frontend vs Site Editor thing is consistent regardless of the theme.

The one with the page vs site editor has been reported here:  https://github.com/Automattic/themes/issues/6521 (Blank Canvas)

**Comment by carolinan** [comment] 2022-09-09 08:04
Which block was used to test this? There are many blocks that can have links.
Please test with a theme that has no styling, like Emptytheme, that you can find in the Gutenberg/test folder.

A related navigation block issue was reported here:
https://github.com/WordPress/gutenberg/issues/42766

**Comment by Robertght** [comment] 2022-09-13 12:13
Sorry for the delay here @carolinan !

This was a simple paragraph block. I tried testing with the [Emptytheme](https://github.com/WordPress/theme-experiments/releases/tag/emptytheme%401.0.0) theme, but I got a missing style.css error during instalation

**Comment by carolinan** [comment] 2022-09-13 16:37
Empty theme in the Experiments repo is not the same files as in the Gutenberg repository. The experiments repo is not maintained.

**Comment by ndiego** [comment] 2022-09-27 14:33
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg, WordPress, and the Twenty Twenty-Two theme. Therefore, this seems to be a theme-specific issue, and I am going to close this. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.

**Closed as completed by ndiego** 2022-09-27 14:33 UTC
Labels: [Status] Needs More Info, Needs Testing
