### ISSUE TITLE
Add "stretch" as option on Row block. 

### ISSUE THREAD

**Issue by johnstonphilip** [WordPress/gutenberg#41280] opened 2022-05-24 15:04 UTC
## What problem does this address?
It's currently not possible to use `align-items:stretch` to make items inside a `row block` vertically fill the space available. 

While `stretch` is the default for a flex item in CSS, I am not able to use that in the block editor. 
<img width="357" alt="Screen Shot 2022-05-23 at 4 52 17 PM" src="https://user-images.githubusercontent.com/7538525/170068646-6fd99b55-ab2b-401d-a672-2933abd3d511.png">

## What is your proposed solution?
Add "stretch" to the available options, alongside `Align top`, `Align middle`, and `Align bottom`.

https://github.com/WordPress/gutenberg/blob/c761edb877a9581a66cb9a3679c86fd6e3d0792d/packages/block-editor/src/components/block-vertical-alignment-control/ui.js#L12-L25

**Comment by karmatosed** [comment] 2022-05-24 21:10
My thought around this is perhaps the naming. Would calling it something like 'fill' mean more to not just developers?

**Comment by cbirdsong** [comment] 2022-11-28 13:46
This would also be good to add on the Stack block, as outlined in #46008.

**Comment by willybahuaud** [comment] 2022-12-08 11:55
I think the problem is in the editor style. Il you look at the column block, it's stretched by default. But in the group (layout row) the css rules are :
```
.editor-styles-wrapper .is-layout-flex{align-items:center}
body .is-layout-flex{align-items:center}
```

I don't know why this is so. After changing the style, the only persistent effect is that the "centered" icon remains grayed out even if it is not checked.

Can someone explain us why centered is set by default here?

**Comment by tellthemachines** [comment] 2023-02-07 02:40
Closing as "stretch" has been added in #47134.

**Closed as completed by tellthemachines** 2023-02-07 02:40 UTC
Labels: [Type] Enhancement, [Block] Group, [Feature] Layout
