### ISSUE TITLE
Serious side-effects when login in another tab after session expiration in first tab

### ISSUE THREAD

**Issue by trejder** [WordPress/gutenberg#11531] opened 2018-11-06 08:32 UTC
# A. STEPS TO REPRODUCE:

1. Start editing a new blog post.
2. Open a preview of it in some other browser tab.
3. Leave it open and hibernate computer for several hours (or otherwise expire the session without refreshing / closing the editor).
4. Add a new comment to that blog that requires moderation or otherwise cause owner to receive e-mail with a link to a blog.
5. Click on received link. New browser tab or window will open. Session is expired so login screen appears (correct!).
6. Login to WordPress.
7. Go back to the other / left open / hibernated browser tabs and try to do anything.

In that "old" / other tab you're logged-off / you have session expired (even though you have just logged in again), but WordPress isn't able to handle this situation gracefully.

# B. SIDE-EFFECTS

## B1. UNABLE TO ADD AN IMAGE

1. An attempt to add an image causes image browser to display "loading knob" infinitely.

## B2. UNABLE TO SAVE THE DRAFT

1. An attempt to save the draft actually DESTROYS the draft in the database.
2. Clicking this button causes Wordpress to display login screen (even though you're already logged in; see below).
3. From this moment on your draft preview (the other "old" tab) will be constantly showing "Page not found".
4. After publishing and unpublishing the page it gets even worse -- only "Page not found" page title appears in tab and tab is constantly being refreshed endlessly by the browser.

## B3. UNABLE TO LOGIN

1. An attempt to refresh the page displays login screen (even though you're already logged in).
2. Logging in is impossible. After login Wordpress displays login page again and says that browser has cookies disabled (not true).
3. To solve this problem one must restart entire browser (cleaning session cookies?) and login again.

# C. Conclusions

Restarting browser solves the B3 and B1 problems only. B2 problem partially remains. Wordpress is able to save the draft, but still doing this incorrectly and later isn't able to show preview of the post, claiming that page is not found or reloading page forever.

To solve last part of B2 problem one must restart browser, re-login and save the draft several times.

https://core.trac.wordpress.org/ticket/45296#ticket

**Comment by designsimply** [comment] 2018-11-06 17:42
Thank you for reporting this! I believe it's a duplicate of https://github.com/WordPress/gutenberg/issues/9260 and there has been recent work to fix that issue in https://github.com/WordPress/gutenberg/pull/11347 which should become available in 4.3.

There are also some open issues which address the concerns in the side effects section: mainly #7367 which proposes some ideas around how to save post data to the REST API offline so data isn't lost and also #4590 which proposes improving the UX around the "Updating failed" error in general.

I am closing this issue as a duplicate and would like to thank you for taking the time to test and report! If you think I've missed anything or you don't agree that the issues I've noted above are enough, please let me know and I'll re-visit and check on this again with you.

**Closed by designsimply** 2018-11-06 17:42 UTC
Labels: REST API Interaction, [Component] Saving, [Status] Duplicate, [Type] Bug

**Comment by trejder** [comment] 2018-11-06 20:00
It is me, who should thank for such a professional approach to this bug. Which, in fact, is very poorly written, because it touches many areas and problems and should definitely be split into many tickets and checked for a possible duplicates. Thank you.

**Comment by designsimply** [comment] 2018-11-06 22:06
I care very much about doing good work. Thanks for saying thanks! ❤️
