### ISSUE TITLE
Add .wp-element-button class to Login/out block button

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#52813] opened 2023-07-20 22:27 UTC
### Description

There is a lack of styling for the login/out block button. It should have the .wp-element-button class applied to it, similar to the way the Post Comment submit button does. This would provide a more uniform appearance for all site buttons and make each one controlled by theme.json. Currently, here is the markup for:

**Button:**
`<a class="wp-block-button__link wp-element-button">This is a Button</a>`

**Post comments button:**
`<input name="submit" type="submit" id="submit" class="wp-block-button__link wp-element-button" value="Post Comment">`

**Login/out button:**
`<input type="submit" name="wp-submit" id="wp-submit" class="button button-primary" value="Log In">`

### Step-by-step reproduction instructions

1. Create new page and add the Login/out form block.
2. View login form with unstyled button.

### Screenshots, screen recording, code snippet

Here is a screenshot with a sample button for reference:

![image](https://github.com/WordPress/gutenberg/assets/486261/db76155b-4532-4ea4-a1ee-57107efb63f8)

By adding .wp-element-button to the Login/out button class, it looks like this:

![image](https://github.com/WordPress/gutenberg/assets/486261/ead3596b-7610-4a94-9524-25d45b0edde0)

### Environment info

WordPress 6.3-RC1.
Gutenberg not active (though with active, there is no difference.)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment] 2023-07-20 22:45
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/50466. Agreed; it should be consistent.

**Closed as completed by richtabor** 2023-07-20 22:45 UTC
