### ISSUE TITLE
Multiple copies of same tip being displayed one on top of the other

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8285] opened 2018-07-30 09:52 UTC
**Describe the bug**
I just edited a page and found that it's displaying multiple copies of the same tip over the top of each other.

![screenshot_761](https://user-images.githubusercontent.com/2078245/43390483-ab00032e-9431-11e8-89da-5a10cce106c7.png)

**To Reproduce**
1. Ensure tips haven't been cleared
2. Edit page

_macOS Sierra 10.12.6
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0_

**Comment by designsimply** [comment] 2018-07-31 15:41
I tested this with 3.4.0 and was not able to reproduce the problem. Can you check to see if the problem is still happening for you in 3.4.0? If it is, can you check to make sure your steps to reproduce are complete? I tried editing a previously created page that contained a columns block after upgrading to 3.4.0 and did not see the problem as described here. I tested using Firefox 61.0.1 on macOS 10.13.6.

Note: I will close this for now since I couldn't reproduce the issue based on my testing but we can re-visit any time if this comes up again or if there are missing steps.

**Comment by maddisondesigns** [comment] 2018-08-01 03:07
@designsimply On the site where this happened, it's still showing the two tips (one on top of the other) even after updating to 3.4.0. I'll try and see if I can replicate this on another site but before I do, I need #8342 fixed because I can't currently get the tips showing again (unless you can tell me what db option to remove to make them show). When I encountered this, there was nothing that I actually did. I simply opened up a previous page that I'd created and it was showing the two tips.

**Comment by pento** [comment] 2018-08-01 03:16
I can reproduce this behaviour when there are two block inserter buttons on the page.

To reproduce (assuming you're not affected by #8342):

- If it isn't already, uncheck the "Show Tips" option.
- Add a column block.
- Check the "Show Tips" option.

**Comment by chrisvanpatten** [comment] 2018-08-01 15:06
There have been a few reports of this in Slack. I've also experienced it a few times, and it's definitely related to columns.

**Comment by designsimply** [comment] 2018-08-02 13:56
Closed #8382 as a duplicate. And thank you for the updated steps!

**Closed** 2018-08-08 11:26 UTC
Labels: NUX, [Component] Nested / Inner Blocks, [Type] Bug
