### ISSUE TITLE
Sibling inserter is difficult to access

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24067] opened 2020-07-20 17:22 UTC
**Describe the bug**
Based on a comment from this issue here: https://github.com/WordPress/gutenberg/issues/22801#issuecomment-660371739 I'm creating a new issue for this problem.

1. When an Image block proceeds the block I have selected below it, and I'm able to target and click the inserter, it doesn't respond to my clicks.
2. Many of the block toolbars cover the Inserter still making it impossible to click.

**To reproduce**
1. Add an Image block with an image.
2. Add a Group block below.
3. With the Group block selected, try to click on the sibling inserter.
4. Observe that it is unclickable.

**Expected behavior**
I expected the sibling inserter to be clickable.

**Screenshots**

![inserter](https://user-images.githubusercontent.com/617986/87966754-9732e900-ca72-11ea-99c3-89462fee825a.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.3
- Latest Gutenberg version
- Latest Firefox

**Comment by talldan** [comment] 2020-08-25 01:35
Duplicate of #22801

**Closed by talldan** 2020-08-25 01:35 UTC
Labels: [Feature] Inserter, [Type] Bug
