### ISSUE TITLE
Permalinks: cannot define post/page permalink until after clicking Save Draft

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7129] opened 2018-06-04 20:13 UTC
Is this intended behavior?:

After creating a new post/page, it's not possible to assign a custom permalink before first saving it.

Is that the intended behavior?

Seems like the "Edit Permalink" button should be available, even before saving.

???

**Comment by hansschuijff** [comment] 2018-06-04 20:57
I agree, and miss the ability to enter a permalink too.

I also wonder if permalink shouldn't be put in the sidebar under document, instead of hanging above the title. When starting with Gutenberg I was looking for the permalink (when it couldn't yet be edited), and it took some time to find it hovering above the title since intuitively I expected it to be part of the document attributes.
When a green message is displayed at the top of the document (block saved), the placement of the permalink-hover is extra confusing, since than it invisible since it is lying behind the message and only becomes visible again after the green message-bar is removed by clicking a tiny x .

**Comment by matto15** [comment] 2018-07-23 14:16
Yes! I also noticed this issue. It has not been resolved in the latest version 3.3.0. The team should indeed work on this.

**Comment by mtias** [comment] 2018-11-20 23:12
Adding to 5.0.1 as it has a proposal to review.

**Comment by faystart** [comment] 2018-12-27 03:20
still have to rewrite the permlink name through quick edit or somewhere else instead of the editor panel?

**Comment by afercia** [comment] 2018-12-27 09:00
Just tested on WP latest trunk, following the steps from https://github.com/WordPress/gutenberg/issues/7129#issuecomment-417862796 (September 1st) and this is still an issue. More than 6 months have passed since this was originally reported, I'd recommend to give it some higher priority. /Cc @youknowriad

**Comment by SenorFusion** [comment] 2019-01-21 22:10
I feel this should really be a High Priority issue.

Allowing posts to be published with these terrible URLs even though permalink settings are explicitly the opposite is really bad.

There must be ten of thousands of regular bloggers who don't use the "Save Draft" function and are unknowingly publishing their posts with these terrible permalinks.

Sure, the permalink can be updated - BUT once a post goes live and is pushed out to Pingomatic (and search engines), RSS, Email Notifications, Social Media, etc it is a significant problem for the success of the post (marketing, sharing, and seo wise) to change the URL after the fact.

Several non-technical bloggers that I support have had exactly this problem for exactly this reason. I am having to try to retrain them to manually edit the permalink (they shouldn't have to).

As mentioned above, especially because of Gutenberg presenting itself as "just write".

This is a significant regression and should be moved up the priority list.

**Comment by earnjam** [comment] 2019-01-22 11:10
@SenorFusion Just want to clarify that it still auto-generates the permalink based on the permalink settings at the time of publishing. So it's not publishing with a `example.com/?p=123` type permalink if you have pretty permalinks enabled. 

You just can't see what the permalink will be and edit it until you execute a manual save or publish.

**Comment by mikedodd** [comment] 2019-05-13 08:28
Has anyone got a workaround or solution for this yet?

**Comment by eshannon3** [comment] 2019-06-04 13:42
If site editors don't tend to save drafts, but instead publish, then edit the permalink and hit Update, there's an additional problem - the postmeta table gets cluttered up with `_wp_old_slug` data.

**Comment by eshannon3** [comment] 2019-06-04 13:48
Sure, and it's helpful when you're changing old permalinks, but frustrating when people are simply wanting to set the permalink to the desired slug in the first place, and they can't without saving a draft or publishing.

**Comment by stefahn** [comment] 2019-07-17 08:47
I'm a very experienced WordPress user and it took me more than 1 minute to find out that I need to save my post in order to get the option to change the permalink. This is a no go and should be fixed with very high priority!

**Comment by shameeryou** [comment] 2020-02-05 09:58
Permalink changing is a serious issue for us. Because of that, we are still using classic editor. 

We have a non-english website, and we publish an average 40 posts per day. For all posts, we need to change the URL manulayy. So give us something better. At least an option change the URL before manually saving the draft.

**Closed** 2020-03-18 13:19 UTC
Labels: [Feature] Permalink, [Status] In Progress, [Type] Bug
