### ISSUE TITLE
Aligned image overlaps adjacent block controls

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15930] opened 2019-05-30 23:59 UTC
**Describe the bug**

When an image has a left/right alignment, it will sit on top of the controls for adjacent blocks, blocking them from being used.

Originally [reported on the forums](https://wordpress.org/support/topic/gutenberg-editor-controls-blocked/)
Related #13784, #7500

**Expected behavior**

The controls should always be on top of block content, including adjacent blocks.

**To reproduce**

Create paragraphs and an image like the ones in the screenshot.

1. Add a few paragraphs
2. Add an image block, left-align
3. Highlight text in one of the adjacent paragraphs

**Screenshots**

![Screen Shot 2019-05-30 at 4 53 09 PM](https://user-images.githubusercontent.com/484068/58672456-dac11580-82fb-11e9-895a-0cb7f55c5523.png)

**Desktop (please complete the following information):**
 - OS X 10.14.5
 - Chrome 74

**Comment by talldan** [comment] 2019-05-31 09:26
Duplicate of #15923.

**Closed by talldan** 2019-05-31 09:26 UTC
Labels: [Status] Duplicate, [Type] Bug
