### ISSUE TITLE
Gallery: Add inline reordering for images within block

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#2129] opened 2017-08-01 18:45 UTC
The gallery block relies on the core media modal dialog for reordering images within the block, this should be managed from within the block itself.

Add ability to drag and drop reorder images within the block

**Comment by afercia** [comment] 2017-08-01 19:47
> Add ability to drag and drop reorder images within the block

Users should be able to do this also when using only the keyboard, i.e. drag and drop needs an alternative UI.

**Comment by mtias** [comment] 2017-08-04 14:23
Closing as duplicate of #743.

**Closed by mtias** 2017-08-04 14:23 UTC
Labels: Accessibility, Media, Priority Low
