### ISSUE TITLE
Navigation Block: Change "Remove Block" label for items with "Remove Navigation Item" or "Remove Item"

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#20108] opened 2020-02-07 20:18 UTC
**Describe the bug**
The "Remove Block" label when removing a navigation menu item feels very far from my mental model of what I'm editing. I would suggest changing this to something more contextual:

![image](https://user-images.githubusercontent.com/1238696/74062763-dd542e80-49a3-11ea-8ee7-439efa436983.png)

**Desktop (please complete the following information):**
Windows, Firefox, WP 5.3.2, Gutenberg 7.4.0

**Comment by PaulGalinsky** [comment] 2020-06-04 15:10
I disagree with the original issue raised. The language "Remove Block" matches my mental model.

**Comment by jasmussen** [comment] 2021-01-26 07:36
Thank you for the ticket! Due to the amount of different block types and names, and the fact that block names can be very very long and need translation, "Remove block" provides an interface that is uniform across blocks, doesn't grow the popover menu randomly on a per block basis, and won't add complexities to the translation effort.

For that reason, I'm going to close this issue for now as intended. But comments will remain open, and I'm happy to reopen the ticket if there's a great use case I missed. Thanks again!

**Closed by jasmussen** 2021-01-26 07:36 UTC
Labels: [Block] Navigation, [Type] Copy, [Type] Enhancement
