### ISSUE TITLE
Toolbars don't show selected item in sidebar

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#21022] opened 2020-03-19 15:34 UTC
Toolbars do not show which item is selected. For example, the heading block sidebar:

<img width="271" alt="Screen Shot 2020-03-19 at 11 23 00 AM" src="https://user-images.githubusercontent.com/1783595/77083816-767b5980-69d4-11ea-96ec-b509d18e944f.png">

It appears the `is-pressed` class is not applying any styles to the `button` element in the toolbar.

**To reproduce**
1. Add a `heading` block
2. Select various heading levels (e.g. `h2`, `h3`)

**Expected behavior**
The current heading level should be selected.

**System**
- macOS 10.15.3
- Safari version 13.0.5 (also tested in Chrome version 80.0.3987.149)
- WordPress 5.3.2
- Gutenberg plugin version 7.7.1

**Comment by earnjam** [comment] 2020-03-21 14:29
I noticed this the other day, so can confirm this. I think it‘s a regression. Pretty confident it used to work.

**Comment by earnjam** [comment] 2020-03-21 16:01
Yep, previously: 
![image](https://user-images.githubusercontent.com/4267290/77230488-fa674a00-6b6a-11ea-9fa8-ca133bf5b4e6.png)

Looks like a mixin and a style referencing it was removed in `packages/components/src/toolbar-button/style.scss` the G2 commit and not added back anywhere else: https://github.com/WordPress/gutenberg/commit/ef73ed07bd59bdcbbe77cc1c537299d8e39167b1

**Comment by jorgefilipecosta** [comment] 2020-03-23 11:37
I verified this issue happens on Gutenberg master but not on WordPress 5.4.

**Comment by earnjam** [comment] 2020-05-01 13:36
This was fixed with #21252

**Closed by earnjam** 2020-05-01 13:36 UTC
Labels: [Block] Heading, [Package] Components, [Status] In Progress
