### ISSUE TITLE
On installation in an existing website, make intelligent choice whether a post or page contains classic or raw code

### ISSUE THREAD

**Issue by timreeves** [WordPress/gutenberg#7859] opened 2018-07-10 08:56 UTC
**Is your feature request related to a problem? Please describe.**
I installed the plugin on an existing site and it broke my landing page. This was due to the landing page being hand-coded HTML and having WP output processing suppressed. Gutenberg assumed it to be a classic block and added its own processing of the code, cutting out empty anchor links and adding break tags. This completely wrecked the page output.

**Describe the solution you'd like**
When Gutenberg first sees an existing page or post, it should make an intelligent decision as to whether to classify the content as a classic block or a Raw HTML block. This can hardly be done based on the content itself, so you will need to look at the settings for the page, here some suggestions:
- If the plugin [Raw HTML](https://wordpress.org/plugins/raw-html/) is installed, then check its options for this page. This plugin is in active use more than 40.000 times. If you do not do this, you will probably break most of those websites.
- If the plugin WP Edit is installed, it has an setting on its Post/Pages tab "Disable wpautop()". If selected then it adds a checkbox on the editing screen to do that on a per-page basis. You need to check if this is on.WP Edit has 100.000 + installations...
- The theme "Weaver Xtreme" (10.000 + installs) has a page template "blank", and a per page option to suppress wpautop().
- I'm sure there are other ways for a user to achieve this end in WordPress - perhaps it is possible to have a generic solution: inspect whether some other plugin is using the hook to suppress wpautop() and decide for a Raw HTML block?
If you don't manage to solve this you will break every site using Raw HTML on some page(s).

**Describe alternatives you've considered**
One alternative I can imagine is to install and activate a "Disable Gutenberg" plugin before upgrading WordPress to 5.0. Another idea would be to defer Gutenberg taking over a page or post until the administrator chooses a block type for it. The latter would be a safe thing, putting the choice back to the administrator. I would prefer that to having my site broken although I have not changed anything.

**Comment by danielbachhuber** [comment] 2018-07-11 12:33
Hi @timreeves,

Thanks for the report. Could you share the original HTML for your post (in a GitHub Gist or similar) so that we have it to work with?

I think some of the problems you ran into are already tracked in other issues (e.g. #3900 #4456 #7335 #7335). It'd be great to reproduce the problem and verify that all of the issues are tracked.

> Another idea would be to defer Gutenberg taking over a page or post until the administrator chooses a block type for it. The latter would be a safe thing, putting the choice back to the administrator. I would prefer that to having my site broken although I have not changed anything.

While it won't be included in core, you may want to check out [Gutenberg Ramp](https://wordpress.org/plugins/gutenberg-ramp/) for your personal needs.

**Comment by timreeves** [comment] 2018-07-11 14:36
Hi @danielbachhuber,

thanks for a prompt and friendly reply!

The author of the plugin "Disable Gutenberg" [blogs](https://digwp.com/2018/04/how-to-disable-gutenberg/) that Gutenberg will be in the core. You say not. Can you tell me where the definitive decision info can be found (URL)? This is like really important to know.
Here's the code I had problems with, when it was parsed and mangled as a classic block:

```
<div id="lpsizebox">
<img id="size-helper" src="/wp-content/uploads/images/lpsizer.png" width="100" height="68" alt="">
<a class="lpbox lpbox3" href="#"></a>
<a class="lpbox lpbox1" href="#"></a>
<a class="lpbox lpbox6" href="#"></a>
<a class="lpbox lpbox8" href="#"></a>
<a class="lpbox lpbox4" href="#"></a>
<a class="lpbox lpbox7" href="#"></a>
<a class="lpbox lpbox5" href="#"></a>
<a class="lpbox lpbox2" href="#"></a>
<a class="lplanguage" rel="alternate" href="https://werteagentur.net/en/"><img src="https://werteagentur.net/wp-content/uploads/images/flags/United-Kingdom.png" alt="English">English</a>
<a class="lphomelink" href="/home"></a>
<a class="lpenterlink" href="/home"><img id="lpweiter" src="/wp-content/uploads/images/weiter_d.png" width="155" height="35" alt=""></a>
</div>
<footer class="lpfooter">
<a id="lpfooterfirst" href="/impressum">Impressum</a>
<a href="/kontakt">Kontakt</a>
<a href="/datenschutz">Datenschutz</a>
<a href="/sitemap">Sitemap</a>
</footer>
```

Yup this is a complete landing page! It is a graphic display with CSS3 animation, whose visual content is mainly based on the background images of the HTML elements. That way I could keep the HTML absolutely minimal and make it responsive too.

- The empty anchor links are going to get relative URLs later, when the rest of the website is there. But in general you can't just delete an anchor because it's formally empty - who knows what some wizzkid has done in custom CSS to provide it with size, position, background images or even content. Not to mention what could be done to it in custom JavaScript...
- The empty anchor links get removed and what's left is a series of break tags )-:
- In the footer area, the anchor links do not get removed (they are formally non-empty), but they do get break tags inserted between them. They should be inline elements, so the breaks mean that only the first link is visible and the others are positioned below it, outside the fixed height container and thus invisible.

In general, I do not envy the people trying to sort all this out. So many possibilities to "get it wrong" or to "miss something". That's why I am thinking in the direction to defer Gutenberg taking over pages and posts after it has been installed and activated. My idea is that it should show a banner that action by an admin is needed: The admin can then choose to activate it for all or for particular post/pages with assumption of classic text blocks; OR to opt for manual control and get a list of all pages and posts, with radios or checkboxes where she can opt for (a) no Gutenberg, (b) as a classic block, or (c) as a Raw HTML block. Now THAT to my mind would be the respectful way, leaving the admin in control. Come on, we're Open Source guys, not Microsoft or Apple, yeah?

Cheers, thanks, Tim

**Comment by mkaz** [comment] 2018-11-16 16:59
@timreeves Yes, Gutenberg is expected to merge into core with the WordPress 5.0 release, expected to go out on Nov 27, 2018. The full schedule is available here: https://make.wordpress.org/core/5-0/

With regards to disabling Gutenberg based on other plugins, it is tricky to know the list of plugins. One of the reasons for the extended development window and beta is so all plugin developers can update for compatibility.

If there is still plugin compatibility issues, the Classic Editor plugin is available which will disable Gutenberg, https://wordpress.org/plugins/classic-editor/

Lastly for the specific code above, there is an HTML block which can handle raw HTML. I pasted the above HTML into that block and it renders out as expected, without changing anchor tags or other pieces. I'm not sure what state Gutenberg was in when this issue was created, so this might not of been available then.

Hopefully, the above addresses all your concerns listed, I'm closing out this issue. If not addressed, please do reopen with any additional information.

**Closed by mkaz** 2018-11-16 16:59 UTC
Labels: [Component] Raw Handling
