### ISSUE TITLE
Eliminate redundant instructions with blank blocks -- 'Start writing or type / to choose a block'

### ISSUE THREAD

**Issue by markarms** [WordPress/gutenberg#12896] opened 2018-12-15 04:55 UTC
It's visually distracting to see every paragraph break / unused block [repeating the same instructions](https://markarmsdotcom.files.wordpress.com/2018/12/Screen-Shot-2018-12-14-at-8.43.35-PM.png) -- we should hide repeat instructions when more than one block is created with nothing inside.

**Comment by alexcroox** [comment] 2019-02-21 09:56
Did you find a solution to this?

**Comment by kjellr** [comment] 2019-04-09 16:43
Thanks, @markarms! I'm going to close this issue as a duplicate of https://github.com/WordPress/gutenberg/issues/12896 since that one has a bit more detail and a screenshot. We'll still track this issue, and you can follow along there. 👍 

Thanks!

**Closed by kjellr** 2019-04-09 16:43 UTC
Labels: Blocks, Needs Design Feedback, [Block] Paragraph
