### ISSUE TITLE
Template part "Edit" toolbar control not functioning 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48216] opened 2023-02-17 20:41 UTC
### Description

The "Edit" toolbar control within the Template Part blocks are no longer functioning. 

The URL changes from `http://localhost:8888/wp-admin/site-editor.php?canvas=edit` to `http://localhost:8888/wp-admin/site-editor.php?canvas=edit&postId=twentytwentythree%2F%2Fheader&postType=wp_template_part` but the UI does not indicate anything happening.

### Step-by-step reproduction instructions

1. Navigate to the Site Editor.
2. Open List View.
3. Click on any template part.
4. Click the "Edit" control on its toolbar.
5. See error (nothing happening, no console errors). 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1813435/219787906-5699c554-074f-481e-b270-ffe968547288.mp4

### Environment info

- WordPress Beta 2
- Occurs with and without Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2023-02-20 07:46
I can reproduce this with 6.2-beta2-5536 without Gutenberg.

If I activate Gutenberg 15.1.1 it works.
if I activate Gutenberg current trunk, at [7f4bc29](https://github.com/WordPress/gutenberg/commit/7f4bc290d92c661f8d0e7e259166bfdae702b043), it also works.


macOS, Chrome
Twenty Twenty-Three
nginx
PHP 8.1.9

**Comment by ndiego** [comment] 2023-02-20 12:44
I am able to replicate it in Beta 2, but the issue is not present for me when Gutenberg trunk (at https://github.com/WordPress/gutenberg/commit/a770a6eaceacab0ae499950b4c539676662f4148)  is enabled.

**Comment by Mamaduka** [comment] 2023-02-22 06:09
I can no longer reproduce the issue with 6.2 beta 3.

**Comment by ndiego** [comment] 2023-02-22 12:17
I have also tested in 6.2 Beta 3 and can no longer replicate the issue. I'm going to close this out, but if anyone else continues to experience issues, please feel free to reopen. Thanks!

**Closed as completed by ndiego** 2023-02-22 12:17 UTC
Labels: [Type] Bug, [Block] Template Part
