### ISSUE TITLE
Provide an ID for the author selector

### ISSUE THREAD

**Issue by enventa** [WordPress/gutenberg#27684] opened 2020-12-11 16:22 UTC
**Is your feature request related to a problem? Please describe.**

The **author selector** under the **Status & visibility** panel in the sidebar of the editor has no HTML ID, so there is no trivial way to target it with a CSS rule. Neither with javascript.

**Describe the solution you'd like**

Provide either aunique ID or a CSS class to the component row of that field. Other fields in that same panel have an additional class, like the Visibility (.edit-post-post-visibility) or Publish (.edit-post-post-schedule) fields.

As described [here](https://core.trac.wordpress.org/ticket/52015), the solution could be as easy as edit the wp-includes/js/dist/edit-post.js file to change this piece of code:

```javascript
function PostAuthor() {
  return Object(external_this_wp_element_["createElement"])(external_this_wp_editor_["PostAuthorCheck"], null, 
    Object(external_this_wp_element_["createElement"])(external_this_wp_components_["PanelRow"], null,
    Object(external_this_wp_element_["createElement"])(external_this_wp_editor_["PostAuthor"], null)));
}
```

to

```javascript
function PostAuthor() {
  return Object(external_this_wp_element_["createElement"])(external_this_wp_editor_["PostAuthorCheck"], null, 
    Object(external_this_wp_element_["createElement"])(external_this_wp_components_["PanelRow"], { className: "edit-post-post-author" },
    Object(external_this_wp_element_["createElement"])(external_this_wp_editor_["PostAuthor"], null)));
}
```

**Describe alternatives you've considered**
As @mrwweb stated in #12067, there is no reliable way to target the author selector field (row container, in fact). Hacky CSS rules and javascript code could eventually break something unexpected.

**Comment by talldan** [comment] 2020-12-14 02:13
Thanks for reporting, though this just seems like a more specific duplicate of #12067, so I'll close this and link to your issue from #12067.

**Closed by talldan** 2020-12-14 02:13 UTC
