### ISSUE TITLE
Everything writes in RTL after pressing Enter

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#1254] opened 2017-06-19 09:21 UTC
So I was trying test the Gutenberg and started to write to see how it is. And apparently if I write and press enter, everything stars writing RTL. So it appears that the typing cursor stays in the left. Here's a GIF attached:

[![Gutenberg Bug](https://gifyu.com/images/Jun-19-201714-34-48.gif)](https://gifyu.com/image/bRy7)

Tried to search if it was reported before but couldn't find. Too many tickets. :)

**Comment by youknowriad** [comment] 2017-06-19 14:35
We need more details, I can't reproduce.
Do you have any JavaScript errors in the console?

**Comment by HardeepAsrani** [comment] 2017-06-20 05:53
@youknowriad I'm using Firefox on MacBook Pro 101, without any console errors. It's a MAMP setup, running PHP 7.0.12.

**Comment by youknowriad** [comment] 2017-06-20 10:55
@HardeepAsrani Are you using `shift+enter` here? related #1243

**Comment by HardeepAsrani** [comment] 2017-06-20 15:50
Nope, only enter.

**Comment by HardeepAsrani** [comment] 2017-06-20 15:50
I'll try doing it on a live server to see what happens.

**Comment by HardeepAsrani** [comment] 2017-06-20 16:10
Tested on a new MacBook Pro late-2016 in Firefox, and same happens.

**Comment by youknowriad** [comment] 2017-06-20 18:20
Enter works properly for me. I was having an issue with shift+Enter fixed by #1299. It'd be great if you can test again with master.

**Comment by youknowriad** [comment] 2017-06-30 12:28
Closing, I can't reproduce. Feel free to reopen if you still experience this but we'd need more information on how to do reproduce.

**Comment by HardeepAsrani** [comment] 2017-07-01 18:46
Hey, sorry I was out at a WordCamp + busy organizing a WC in our city. So little busy. And yes, it's still open. @youknowriad 

Don't see an option to re-open. And yes, I tried it with the latest master and still happening. And we can try to do a live screen share when I can try reproducing it on FF on your Mac. What say?

**Comment by nitrajka** [comment] 2017-08-21 11:25
@youknowriad I'm also not able to reproduce.
@HardeepAsrani  Could you please add steps to reproduce? It would be very helpful.

**Comment by nicolinuxfr** [comment] 2017-08-21 11:46
This bug looks a little like this one… maybe they are related ? 

https://github.com/WordPress/gutenberg/issues/1607

**Comment by HardeepAsrani** [comment] 2017-08-24 18:11
@nicolinuxfr Yup, it's the same. :)

**Comment by karmatosed** [comment] 2017-09-04 19:40
I am unable to reproduce this. It makes me wonder if we're missing some steps. Until we get more steps, I am closing as without it we are chasing reproducing - we can always reopen.

**Closed by karmatosed** 2017-09-04 19:40 UTC
Labels: [Status] Needs More Info, [Type] Bug

**Comment by nicolinuxfr** [comment] 2017-09-04 20:18
You can close it, the #1607 is still open so it's fine for me. :-)
