### ISSUE TITLE
[Cover Block] Changing gradient overlay color points using the color picker sometimes crashes the block

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#36320] opened 2021-11-08 18:15 UTC
### Description

When using the gradient overlay and clicking any of its color points to change its color using the color picker dialog sometimes crashes the block. 

It doesn't always happen, and It seems to be related to the amount and speed of clicks across the color picker's UI controls, but when it does, it completely crashes the block in the editor, and you need to reload the page in order to get it rendered correctly again.

### Step-by-step reproduction instructions

I couldn't pinpoint the *exact* steps to reproduce, yet. As I mentioned above, it's not very consistent, though I can say with certain confidence that it has to do with the (high) amount of click inputs in the color picker. Interestingly enough, _It doesn't seem to happen when setting a single color overlay._

1. Add a cover block to the page, you may set it up to display an image but it's not strictly needed;
2. Click it to give it focus and in the block settings pane (the gear icon at the top-right corner of the editor top toolbar), choose the "Block" settings and scroll down to the "Overlay" section. Choose "Gradient" and select one of the presets.
3. In the color bar, click one of the color points to bring up the color picker dialog. Now, start clicking around its UI controls and then changing color sliders, and eventually, it will hang for a second and finally crash (see the screencast below).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/81248/140796001-236693b3-9c13-40e6-9456-3f31915840fe.mp4

### Environment info

- Wordpress: `5.8-beta4-51266
- Chrome `95.0.4638.69 (Official Build) (64-bit) (Linux)`
- Ubuntu Linux 18.04 LTS
- Gutenberg: `trunk` / `11.9.0 RC2`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2021-11-08 21:40
Thanks for reporting. This is a duplicate of https://github.com/WordPress/gutenberg/issues/36066 - it is related to the color picker rather than the cover block.

**Closed as completed by glendaviesnz** 2021-11-08 21:40 UTC
