### ISSUE TITLE
Consider to add some spacing between inspector controls and their help text

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#9305] opened 2018-08-24 09:53 UTC
Some controls (e.g. input fields, textareas, etc.) in the inspector sidebar can have a help text which is displayed underneath the control.

For example, the Image block has a textarea for the alt text. Please notice in the screenshot below (on the left) there's a small, nice, vertical spacing between the textarea and the help text. I'd say this small spacing helps readability:

<img width="677" alt="screen shot 2018-08-24 at 11 26 39" src="https://user-images.githubusercontent.com/1682452/44577984-b9dafb00-a792-11e8-9f79-3608ad5dbcea.png">

However, input fields (and possibly other controls) don't have a vertical spacing: see in the screenshot above (on the right) an input field provided by a custom block. Visually, it's not so great and readability could be improved.

Turns out the textarea natively reserves some descender space, and that's the only reason why there's some spacing. I'd propose to try to standardize across the different controls / help text and add some default spacing with CSS. Very small change indeed, but worth considering. /Cc @jasmussen

**Comment by karmatosed** [comment] 2018-08-24 20:19
I'd be ok about this, can we try 20px maybe?

**Comment by jasmussen** [comment] 2018-08-27 07:43
A consistent bit of space below textareas, input fields and other controls that have help text, makes sense to me.

**Comment by afercia** [comment] 2018-08-27 16:06
I see https://github.com/WordPress/gutenberg/pull/8767/files#diff-7f4a5101433bca0f9e460c45196b772fR6 added a bottom margin to the `.components-base-control__field` so there's now some spacing:

`margin-bottom: $grid-size;` -> `$grid-size: 8px;`

The spacing below the textarea is still slightly bigger though, as the textarea has some descender space:

<img width="334" alt="screen shot 2018-08-27 at 17 59 47" src="https://user-images.githubusercontent.com/1682452/44670738-c9bd3e00-aa23-11e8-8aa2-e6146691df6c.png">

Can we live with this?

**Comment by karmatosed** [comment] 2018-08-27 21:16
> Can we live with this?

Yes I think that works for me.

**Comment by jasmussen** [comment] 2018-08-28 07:54
It looks like the additional spacing below the textarea is caused by who knows what — but adding `display: block;` to the textarea neutralizes this so the margin becomes the same below both textareas and input fields. 

In other words, 

```
.components-textarea-control__input {
display: block;
}
```

Should fix that up. But I'm not sure if there are adverse side-effects. Feel free to try it if you like, I'll approve quickly if need be.

**Comment by afercia** [comment] 2018-08-28 09:05
> It looks like the additional spacing below the textarea is caused by who knows what

It's called "descender space" 🙂Same happens, for example, with images which usually have a small spacing at the bottom of about 3 pixels (actually depends on the font-size). It's a feature of inline elements (and text). Yes, it is fixable with display block or vertical-align middle (or top).

**Comment by tellthemachines** [comment] 2020-04-22 05:25
If I'm reading this correctly, what remains to be done is only to remove the descender space from the textarea?

**Comment by afercia** [comment] 2020-04-22 13:35
Remove the descender space where it exists _and_ make the vertical spacing between a component and its help text / description consistent across all the UI.

Testing on latest Gutenberg plugin, these all have different spacing:

<img width="315" alt="Image settings" src="https://user-images.githubusercontent.com/1682452/79987065-3c0e4c00-84ad-11ea-8896-24d7adcaf738.png">

Uses the `help` prop of the `TextareaControl`.

<img width="319" alt="Excerpt" src="https://user-images.githubusercontent.com/1682452/79987103-492b3b00-84ad-11ea-8ea1-4734f5a3e189.png">

Although it's a `TextareaControl`, it uses a sibling `ExternalLink` component instead of passing it to the `help` prop.

<img width="311" alt="Additional CSS" src="https://user-images.githubusercontent.com/1682452/79987069-3d3f7900-84ad-11ea-8000-01765c94123d.png">

Uses the `help` prop of the `TextControl` component but the spacing is smaller.

<img width="306" alt="Tags" src="https://user-images.githubusercontent.com/1682452/79987070-3dd80f80-84ad-11ea-88f7-b50865010700.png">

Uses custom code.

They're all help text, except the Excerpt one

**Comment by JustinyAhin** [comment] 2021-04-06 11:15
I went through the input and text areas in the editor and those of blocks. And they all seem to have the `margin-bottom: 8px;`; which make this consistent across the editor.

So, I'm going ahead and close this issue. Please feel free to reopen if you spot others places where the vertical spacing is not consistent.

**Closed by JustinyAhin** 2021-04-06 11:15 UTC
Labels: CSS Styling, [Type] Enhancement

**Comment by metropoliscreative** [comment] 2022-10-25 14:08
This does not seem to be merged with core - the spacing is only correct if the Gutenberg plugin is active. 

This is on the TextControl component with help text, within the PluginPostStatusInfo SlotFill:

Gutenberg plugin deactivated

<img width="275" alt="Screen Shot 2022-10-25 at 10 02 54 AM" src="https://user-images.githubusercontent.com/3420909/197795591-e810daa7-7ebe-457a-b4a1-641c0fa8270e.png">

Gutenberg plugin activated:

<img width="276" alt="Screen Shot 2022-10-25 at 10 03 13 AM" src="https://user-images.githubusercontent.com/3420909/197795737-f23337af-8111-4849-9892-546aae93bdce.png">
