### ISSUE TITLE
Alignment: blocks using alignment should apply `data-align` consistently

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#7908] opened 2018-07-11 23:41 UTC
Moved from https://github.com/WordPress/gutenberg/issues/4010 h/t @bradyvercher.

## Edit Wrapper Data Attribute

Most of the blocks apply a `data-align` attribute to the edit wrapper with the alignment value similar to this:

```js
getEditWrapperProps( attributes ) {
    const { align } = attributes;
    if ( 'left' === align || 'right' === align || 'wide' === align || 'full' === align ) {
        return { 'data-align': align };
    }
}
```

Center aligning never seems to change the value of the data attribute for the edit wrapper despite it being a valid value for most blocks. It seems like this should be applied consistently in case themes treat `aligncenter` different than `alignnone` or an empty value.

**Comment by tofumatt** [comment] 2018-07-17 17:46
Also, the fact that we write `if ( 'left' === align || 'right' === align || 'wide' === align || 'full' === align ) {` is quite repetitive; we should really be [using a constant of allowed align values](https://github.com/WordPress/gutenberg/blob/master/editor/components/block-alignment-toolbar/index.js#L31) and [checking against it](
https://github.com/WordPress/gutenberg/pull/7941#discussion_r203101146).

**Comment by aduth** [comment] 2019-04-22 14:54
I'd consider the root underlying issue here to be that blocks should not be implementing this alignment behavior themselves, but rather opting in to the common implementation (`aligns` support, also noted as "Common Block Functionality" in [Roadmap](https://github.com/WordPress/gutenberg/blob/master/docs/roadmap.md)).

Duplicate of #13780

**Closed by aduth** 2019-04-22 14:54 UTC
Labels: Blocks, [Type] Code Quality, [Type] Enhancement
