### ISSUE TITLE
Document/Block Sidebar Covering Content on First Post Visit on Mobile

### ISSUE THREAD

**Issue by jarretc** [WordPress/gutenberg#17341] opened 2019-09-05 07:22 UTC
**Describe the bug**
When you first sign into the dashboard on mobile and go to edit a post, the Document/Block sidebar shows first instead of the post content. Additionally, the tips that are shown do no align with what is displayed on the screen.

**To reproduce**
1. Log into the dashboard as a new user (incognito/private if you've signed in before)
2. Attempt to edit a post
3. You'll see that instead of the content showing first the sidebar is shown while the "tips" try to explain content that isn't visible

**Expected behavior**
The post content is shown instead of the sidebar allowing the tips to properly explain the details to the user

**Screenshots**
![gutenburn-sidebar-display](https://user-images.githubusercontent.com/1584764/64320845-3262c300-cf74-11e9-964b-91d82a0ec6fa.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12.4
 - Browser: Chrome/Safari
 - Version: Chrome (76.0.3809.123) / Safari (12)

**Additional context**
Tested in WordPress 5.2.3

**Comment by talldan** [comment] 2019-10-10 22:27
https://github.com/WordPress/gutenberg/issues/17708 is a duplicate of this. Usually that one would be closed, but it's now in progress, so I'll close this one instead.

**Closed by talldan** 2019-10-10 22:27 UTC
Labels: General Interface, [Type] Bug

**Comment by gziolo** [comment] 2019-10-11 10:38
I opened #17902 which will address this issue.
