### ISSUE TITLE
Memory management on extended post content, on low powered/low spec machines

### ISSUE THREAD

**Issue by willstocks** [WordPress/gutenberg#14703] opened 2019-03-29 13:50 UTC
**Describe the bug**
So, I was midway through writing an article. So far it's not big - a featured image, one other in-content image block and the rest are simply headings and paragraphs. Everything was running REALLY smoothly...

... Then I added a table block. And performance just straight up plummeted. Entering text in that table resulting in a good couple of seconds of lag, switching from a paragraph block to the table block (and vice versa) has pretty noticeable delay and the overall typing feel in the rest of the post now feels quite clunky/laggy.

**To Reproduce**
1. Write up an article of about 47 blocks (1871 words)
2. Then add a table block around the middle of the post
3. Jank!

**Expected behavior**
Adding a table block shouldn't result in a significant performance hit? I should also be able to enter plain-text into a table without any lag!

**Screenshots**
Not applicable? Happy to supply someone with the content I wrote up via PM though!

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Browser: Chrome
 - Version: 73.0.3683.86

**Additional context**
 - Gutenberg 5.3 (plugin)

**Comment by gziolo** [comment] 2019-04-02 21:28
@youknowriad and @ellatrix - this needs to be investigated.

**Comment by ellatrix** [comment] 2019-04-03 07:52
I cannot reproduce this issue. Created a post that is twice the demo content and added a table. I don't see anything being slower.

Would you mind sharing the content you're working with? Use the three dots on the top right, then click "copy all content".

**Comment by willstocks-tech** [comment] 2019-04-03 08:05
Hey @ellatrix,
Yes, not a problem - I'll get that sent over shortly for you! Do you just want it pasted inline here?

**Comment by willstocks-tech** [comment] 2019-04-03 08:26
I'm now wondering whether it was something to do with my actual machine  rather than anything else - I just opened up the same post on another machine (nothing else open) and observed (via Chrome's task manager) the post start out using around 220MB of memory + 30-40% CPU:

![image](https://user-images.githubusercontent.com/43744514/55463562-43885c00-55f1-11e9-8aea-29534fd5d022.png)

When I then started scrolling around (not inputting any new content) and I saw memory hit 430MB + CPU hit 116% before everything then settled back to around 280MB memory + 30% CPU when scrolling.
I will try adding some more content and monitoring memory + CPU usage to see if it's that.

I'm just going to grab the actual post content now!

**Comment by ellatrix** [comment] 2019-04-03 19:12
I think we do have a lot of memory management problems in Gutenberg. Would be good to investigate. Any help there is appreciated!

**Comment by willstocks-tech** [comment] 2019-04-03 20:38
I’ll do what I can - what sort of info/diagnostics do you need, I can try
to obtain and send over 😊

**Comment by ellatrix** [comment] 2019-04-03 20:40
_I_ don’t need anything. :) We need to identify causes and fix it. :)

**Comment by ellatrix** [comment] 2019-04-04 09:09
@willstocks-tech I you mind updating this issue title, if it's not the table block causing it?

**Comment by willstocks-tech** [comment] 2019-04-04 09:23
Yes, happy to @ellatrix - any recommendations of what to re-title this to? I'm assuming something to do with memory, but I'm not quite sure what to call it at this point though...

Extended post content + memory management?
Large volume of RAM consumed for new post?

**Comment by ellatrix** [comment] 2019-04-04 09:27
Can you reproduce the issues without the table block?
Feel free to rename as you wish :)

**Comment by willstocks-tech** [comment] 2019-04-04 09:29
I'm going to try to do some more testing now. As I noted, everything was working fine up until adding the table block. It could be that memory was within limits up until that point, or maybe it was the table block that caused the issues... I'm not 100% sure at this point. I will try to replicate it with and without the table, as well as get some stats from the machine that I was working on at the time wrt memory consumption 😄

**Comment by willstocks-tech** [comment] 2019-04-24 21:12
I've just come back to this post today to finish it off (up to 93 blocks, 3211 words) and I'm on the same machine I originally was back when I reported this issue.

Reopening it (fresh browser session) with no other programs open on my machine, I'm not noticing any lag/delay (obviously, Gutenberg has also had a couple of updates since, so may be something there that has also improved).

That being said, the post (so far, all I have done is open it and scroll down about half way) is consuming 254MB of memory and 7% CPU (according to Chrome's task manager). According to macOS' activity monitor, the tab (post) is using 261MB of memory (71MB compressed), 18 threads and 272 ports.

Scrolling some more results in macOS' activity monitor to hit 60% CPU while memory remains consistent.

I will start adding and removing some blocks and will monitor throughout, but so far this is the only tab I have open and the only program I have open.

**Comment by willstocks-tech** [comment] 2019-04-24 21:16
Adding a table block (where I originally noticed the issue - again may have been a red-herring) sees a jump in memory usage of about 30 - 50MB, and Chrome's task manager reports 125% CPU usage + a further 30MB of memory allocated to the "Graphics Process"

@ellatrix would you still like me to send over the post content to see if you can replicate anything?

**Comment by youknowriad** [comment] 2020-09-16 08:03
Is this still relevant, it seems like we should close this issue and reopen when we find ways to reproduce consistently. Also, there has been several updates to Gutenberg duuring the last year to improve its performance.

**Closed by youknowriad** 2020-09-16 08:03 UTC
Labels: Needs Testing, [Block] Table, [Type] Performance
