### ISSUE TITLE
Added share options and buttons in Gutemberg

### ISSUE THREAD

**Issue by MatteumPrimo** [WordPress/gutenberg#10120] opened 2018-09-23 10:49 UTC
Hello everyone, 

I've noticed that Word Press **share buttons** are missed in currently Gutenberg version. Should be possible to added it as soon as possible?

They're very important to any website, in order to custom hashtag and tag in social media and get involved new viewers.

Here's an sample from currently Gutenberg version and Jectpack one.

1. [Gutenberg](http://bit.ly/2QV0Ygu)
2. [Jetpack](http://bit.ly/2xMaTfG) / with [hashtag and tag ](http://bit.ly/2zoJUJ8)

**Comment by designsimply** [comment] 2018-09-25 19:49
I tested and was unable to reproduce the problem. I am closing the issue for now and noting we can re-open an issue if needed and that it would likely need to be filed in the Jetpack project at https://github.com/Automattic/jetpack/issues/new

I tested using WordPress 4.9.8 and Gutenberg 3.9.0 and Jetpack 6.5 with the following settings in place:

1. WP Admin > Jetpack > Settings > Sharing > Sharing buttons > "Add sharing buttons to your posts" is toggled on.
1. WP Admin > Settings > Sharing > Sharing Buttons > "Show buttons on"  has "Posts" checked.
1. WP Admin > Settings > Sharing has three sharing buttons showing in the Live Preview.

Can you please check your settings to make sure the proper "Show buttons on" items are checked and that you can see sharing buttons in the Live Preview? If you don't see any, you should try dragging some of the buttons into the "Enabled Services" section and then let me know if it's still not working for you.

**Closed** 2018-09-25 19:49 UTC
Labels: [Type] Plugin / Theme Interoperability

**Comment by MatteumPrimo** [comment] 2018-09-26 14:16
Hello Sheri,

Thanks in advance for your support. Here’s some screenshots about gutember issue and what you asked me. For the records I’m an Italian videogame blogger, so all screenshots are in Italian language.

Best wishes,

Matteo "Matteum Primo" Sechi
Editor/Blogger del Videogame Post
https://ilvideogamepost.net/

[cid:image007.jpg@01D455B4.39D631C0][cid:image008.jpg@01D455B4.39D631C0][cid:image009.jpg@01D455B4.39D631C0][cid:image012.jpg@01D455B4.39D631C0]

Da: Sheri Bigelow<mailto:notifications@github.com>
Inviato: martedì 25 settembre 2018 21:49
A: WordPress/gutenberg<mailto:gutenberg@noreply.github.com>
Cc: MatteumPrimo<mailto:matteo.se@hotmail.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [WordPress/gutenberg] Added share options and buttons in Gutemberg (#10120)


I tested and was unable to reproduce the problem. I am closing the issue for now and noting we can re-open an issue if needed and that it would likely need to be filed in the Jetpack project at https://github.com/Automattic/jetpack/issues/new

I tested using WordPress 4.9.8 and Gutenberg 3.9.0 and Jetpack 6.5 with the following settings in place:

  1.  WP Admin > Jetpack > Settings > Sharing > Sharing buttons > "Add sharing buttons to your posts" is toggled on.
  2.  WP Admin > Settings > Sharing > Sharing Buttons > "Show buttons on" has "Posts" checked.
  3.  WP Admin > Settings > Sharing has three sharing buttons showing in the Live Preview.

Can you please check your settings to make sure the proper "Show buttons on" items are checked and that you can see sharing buttons in the Live Preview? If you don't see any, you should try dragging some of the buttons into the "Enabled Services" section and then let me know if it's still not working for you.
