### ISSUE TITLE
Components: Alert: Close action is misaligned

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#21107] opened 2020-03-24 15:11 UTC
**Describe the bug**
<img width="636" alt="Screen Shot 2020-03-24 at 11 09 42 AM" src="https://user-images.githubusercontent.com/2322354/77441658-1152aa00-6dc0-11ea-9dd9-ffccf84b76b2.png">

The `X` close icon is misaligned within the `Alert` box.

**Comment by t-hamano** [comment] 2022-08-05 12:55
I believe this is the `Notice` component, and it certainly reproduces the same layout on StoryBook.
Additionally, this also occurs when using the Notice component on the block editor:

![storybook_1](https://user-images.githubusercontent.com/54422211/183079236-256e63cc-3f57-44c4-ab9a-17dff1435db5.png)

However, I believe this is because the browser default margins are applied to the `p` tag of the child element.
If you reset the margins on the `p` tag as shown below, it will display correctly.

![storybook_2](https://user-images.githubusercontent.com/54422211/183079894-2522a388-3ce2-4438-8a5d-0b54ff8a7dbe.png)

Since any element can be specified as a child, I think their style should not be controlled by the component.
Furthermore, as noted in [this comment](https://github.com/WordPress/gutenberg/blob/19338201d8654729674fdb14f62f1a399c729747/packages/components/src/notice/style.scss#L59), the button is expected to be placed in the upper right corner, no matter how many lines of content are present.

**Comment by t-hamano** [comment] 2022-08-05 12:55
@ItsJonQ
I would like to close this issue as I believe this is expected behavior.
If there are any misunderstandings or clarifications, please don't worry about it and re-open it.

**Closed by t-hamano** 2022-08-05 12:55 UTC
Labels: General Interface, Needs Testing, [Package] Components
