### ISSUE TITLE
Gallery edit button appears on all blocks once a gallery block is added

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1307] opened 2017-06-20 14:49 UTC
Tested using the current plugin in the WordPress Plugin Directory (0.10.0).

Steps to reproduce:

1. Add a new embed block, e.g. for a tweet or a YouTube video
2. Select the newly added block
3. Click on the edit button with the pencil icon

<img width="690" alt="screen shot 2017-06-20 at 16 47 31" src="https://user-images.githubusercontent.com/841956/27339474-3595a690-55d8-11e7-8efc-a08d4a2219f2.png">

Expected:

The form to edit the embed URL is shown, or perhaps even a bunch of new options (e.g. timeframe for YouTube videos or color options for tweets).

Actual result:

The media modal gets opened, with the "Edit Gallery" view being shown. Obviously, I'm not editing a gallery.

<img width="1410" alt="screen shot 2017-06-20 at 16 47 13" src="https://user-images.githubusercontent.com/841956/27339472-355f7674-55d8-11e7-9fa6-e40e9ed21e19.png">

**Comment by notnownikki** [comment] 2017-06-20 14:56
I'm having trouble reproducing this, there _shouldn't_ be an edit button there at all.

Here's what I'm doing:

![wheresitcomingfrom](https://user-images.githubusercontent.com/3314354/27339901-f64ba482-55d0-11e7-8ac6-22aeee43f69f.gif)

Are there any image or gallery blocks in your post? Or do you get this with the embed block by itself, and no other blocks?

**Comment by swissspidy** [comment] 2017-06-20 15:06
Yeah, turns out this happens when there is a gallery block somewhere else in the content. It doesn't need to directly follow the embed block.

As soon as I remove the gallery, the edit button for the embed is gone. When I re-add it, it's back again.

**Comment by swissspidy** [comment] 2017-06-20 15:14
Worth noting that it does not only affect blocks _after_ the gallery block. In my dummy post, the embed block comes first.

**Comment by notnownikki** [comment] 2017-06-20 15:20
You're absolutely right, sorry, missed its appearance when I tested!

**Comment by notnownikki** [comment] 2017-06-20 15:33
First look at this... (and I'm most likely wrong, first time looking at this code...)

In `blocks/block-controls/index.js` we have a slot defined:

```
export default function BlockControls( { controls, children } ) {
        return (
                <Fill name="Formatting.Toolbar">
                        <Toolbar controls={ controls } />
                        { children }
                </Fill>
        );
}
```

And then in `blocks/library/gallery/index.js` we do this:

```
				<Fill name="Formatting.Toolbar">
					<Toolbar controls={ [ {
						icon: 'edit',
						title: __( 'Edit Gallery' ),
						onClick: () => editMediaLibrary( attributes, setAttributes ),
					} ] } />
				</Fill>
```

So that appears to me that we're adding the edit button to Formatting.Toolbar. and that's gettnig rendered on all blocks that use the formatting toolbar.

Calling @aduth, @iseulde, and @youknowriad :smile:

**Comment by aduth** [comment] 2017-06-20 16:57
The problem is that a block's `edit` return value is always rendered, even when the block is not currently selected. Since the Gallery block [always renders the formatting toolbar](https://github.com/WordPress/gutenberg/blob/8fd70f4/blocks/library/gallery/index.js#L147-L153), this also means it is rendered regardless of which block is currently selected, resulting in the bug reported here. Instead, we need to control _when_ the formatting toolbar is to be shown; namely, when its `focus` prop is truthy. If this is changed to:

```jsx
focus && (
	<Fill name="Formatting.Toolbar">
		<Toolbar controls={ [ {
			icon: 'edit',
			title: __( 'Edit Gallery' ),
			onClick: () => editMediaLibrary( attributes, setAttributes ),
		} ] } />
	</Fill>
)
```

...it should work correctly again. `<BlockControls>` is encouraged as an abstraction to avoid naming the fill directly (should we want to refactor the naming or implementation).

Documentation: https://github.com/WordPress/gutenberg/tree/master/blocks#blockcontrols
Related: #830, where this behavior is noted as a downside. This is a problem with slots in that we cannot distinguish _where_ the fill comes from, i.e. can't filter to slots rendered by blocks which have focus. This must be the responsibility of the block's render.

**Comment by notnownikki** [comment] 2017-06-20 16:59
Ah, that's making sense, ok great I think I can pick this up :)

**Comment by notnownikki** [comment] 2017-06-21 11:35
Fixed in https://github.com/WordPress/gutenberg/pull/1262

**Closed by notnownikki** 2017-06-21 11:35 UTC
Labels: [Type] Bug
