### ISSUE TITLE
Double-clicking to edit a word inside a link doesn't work in Firefox

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15220] opened 2019-04-26 17:25 UTC
As requested by @ellatrix in [this comment](https://github.com/WordPress/gutenberg/issues/14461#issuecomment-484816002) in #14461 , I've pulled the Firefox bug out into it's own issue.

**I can't select a single word by double-clicking it when inside a link.**

> in Firefox, it seems that this is an issue across different contenteditable-based editors. I have the same issue in TinyMCE. Unfortunately, there's no easy fix. The browser sets the selection after a double click, not us. Trying to recreate selecting a word after a double click is hard because word boundaries are different depending on your script. I would suggest not trying to fix this browser bug.

**Comment by draganescu** [comment] 2020-04-23 08:18
I opened [a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1632425) at Firefox.

**Comment by draganescu** [comment] 2020-06-04 16:43
The [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1632425) at Firefox has been solved!

**Comment by mapk** [comment] 2020-06-16 23:39
I just tested again in Firefox 77 and it's still not working for me.

**Comment by draganescu** [comment] 2020-06-17 07:34
Probably not released yet? :D no idea!

**Comment by paaljoachim** [comment] 2021-04-01 18:51
Tested using Firefox....:)
WordPress 5.7
Twenty Twenty One.
Gutenberg plugin 10.3

Added a few words. Created a link. Double clicked one of the words inside the link. The full word was selected.

<img width="558" alt="Screen Shot 2021-04-01 at 20 50 10" src="https://user-images.githubusercontent.com/5323259/113340295-fa785900-932b-11eb-9f08-70c0ca2ace36.png">

Closing issue.

**Closed by paaljoachim** 2021-04-01 18:51 UTC
Labels: Browser Issues, [Type] Bug

**Comment by gwwar** [comment] 2021-04-01 18:52
I also can't reproduce this in FF 87

**Comment by draganescu** [comment] 2021-04-19 19:00
\o/
