### ISSUE TITLE
Don't make "target=_blank" links clickable in the editor

### ISSUE THREAD

**Issue by fr-laurentn** [WordPress/gutenberg#25277] opened 2020-09-13 15:50 UTC
If you insert a link in the editor and want to edit it, when you click on the link to select it, it opens the link in a new tab instead of showing edit options.

This behavior is expected in the front-end, not in the editor.

It is very annoying because it generates unnecessary clicks.

Steps to reproduce:

- Create a paragraph with a link that **opens in a new tab**
- Click anywhere else on the screen or create a new block
- Click back on the link to edit it

Please note that it happens only if the "open in a new tab" option is selected.

**Comment by youknowriad** [comment] 2020-09-15 08:40
Hi There! 

I'm not able to reproduce this issue personally. I wonder if it's related to some browser extension or something like that? Did you try another browser to confirm?

**Comment by fr-laurentn** [comment] 2020-09-15 11:44
Oh, that's weird.

I just checked on Chrome, and can't reproduce it.

I use Firefox Windows and didn't think of checking with another browser before you mentioned it.

I couldn't find anything in the options, and deactivating all my browser extension doesn't change anything.
Can you reproduce it with Firefox?

At least we know it's somehow browser related!

**Comment by fr-laurentn** [comment] 2020-09-15 12:13
I noticed something weirder:

I can't reproduce the bug with a new post (or page). 
However, if I save the draft (or publish) **then** reload the page, I can reproduce the bug.

**Comment by youknowriad** [comment] 2020-09-15 12:38
- I tried with Firefox (MacOS though I don't have windows)
 - I tried after saving like suggested, still nothing. 

Note that there are plugins that override the link control entirely (like some SEO plugins), so potentially they could be related.

**Comment by fr-laurentn** [comment] 2020-09-15 12:45
Thanks Riad for the follow-up.

I'll try on a fresh install later this week. I'll let you know.

**Comment by fr-laurentn** [comment] 2020-09-16 07:24
Hi @youknowriad,

I tried with a fresh install: nothing.
I guess the issue is caused by a plugin I use.

Thanks for helping troubleshooting this issue 🙏

**Comment by youknowriad** [comment] 2020-09-16 07:46
I'm going to close the issue, but let me know when you find the culprit.

**Closed by youknowriad** 2020-09-16 07:46 UTC
Labels: [Status] Needs More Info
