### ISSUE TITLE
Unable to save posts/pages with specific shortcode

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#9923] opened 2018-09-14 20:23 UTC
**Describe the bug**
A post cannot save/autosave when inserting a shortcode containing the `[rpwe]` shortcode. This shortcode is from the plugin https://wordpress.org/plugins/recent-posts-widget-extended/

**To Reproduce**
1. Install and activate **Recent Posts Widget Extended** https://wordpress.org/plugins/recent-posts-widget-extended/
2. Create/modify a post/page containing a shortcode with `[rpwe]`
3. Save or wait for autosave
4. Note that save/autosave fails.

**Comment by designsimply** [comment] 2018-09-15 01:14
Any issues with a release candidate should be added to the still open milestone. Just note in the issue body the version you are testing such as 3.9.0-rc.1. ([ref](https://github.com/WordPress/gutenberg/issues/9919#issuecomment-421436952))

**Comment by GlennMartin1** [comment] 2018-09-15 15:13
@designsimply Thanks - can you please add this to the 3.9 milestone?

**Comment by mcsf** [comment] 2018-09-20 13:02
OK, a few notes here:

- I was able to repro in 3.8, so this isn't 3.9-specific, thus _a priori_ invalidating the need to rush it into this milestone.
- Saving doesn't actually fail, as confirmable via inspection of server log and saved page (or reloading the editor).
- The issue is that the response to the `POST` request to save the page, while of status code 200, is malformed due to injection of markup and PHP warnings caused by operation of the plugin:

<img width="619" alt="screen shot 2018-09-20 at 13 57 47" src="https://user-images.githubusercontent.com/150562/45819817-35ba5b80-bcdd-11e8-919d-b1deb36f4033.png">

The warnings are of the following type:

> **Warning**:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/recent-posts-widget-extended/includes/functions.php:309) in **/var/www/html/wp-includes/rest-api/class-wp-rest-server.php** on line **1248**

I'd consider this an issue to bring to the plugin developers. In any case, I'll remove it from the 3.9 milestone.

**Comment by designsimply** [comment] 2018-09-20 13:30
Awesome sleuthing! I learned to look deeper at API responses because of the replies here! 🤓 I might not have tried that before because I usually only scan for something other than a 200 response.

I noticed the issue was reported to the plugin developers at https://wordpress.org/support/topic/gutenberg-compatibility-15/ which is awesome, and I will close the issue here.

**Closed by designsimply** 2018-09-20 13:30 UTC
Labels: [Type] Plugin / Theme Interoperability
