### ISSUE TITLE
 Position of Gutenberg "More" menu popover 

### ISSUE THREAD

**Issue by man4toman** [WordPress/gutenberg#7937] opened 2018-07-12 16:23 UTC
Hi,
It's a small patch for Gutenberg "More" menu popover position in RTL locale. Please look at the images it's very clear.

The problem:
![original](https://user-images.githubusercontent.com/935397/42645928-93f7c8cc-8614-11e8-9c5a-67088e9be370.png)

After patch
![patched](https://user-images.githubusercontent.com/935397/42645931-97920042-8614-11e8-85bf-9150ccb97dbc.png)

And fix code:
```
.components-popover {
    position: fixed;
    z-index: 1000000;
    /*rtl:ignore*/
    right: 50%;
    /*rtl:ignore*/
}
```
It must change on this file(for generate correct style-rtl.css):
wp-content/plugins/gutenberg/build/components/style.css

Regards

**Comment by mtias** [comment] 2018-07-19 18:09
Closing as duplicate of #7660.

**Closed by mtias** 2018-07-19 18:09 UTC
Labels: UI Components, [Type] Bug, i18n
