### ISSUE TITLE
Blue Dot Missing on Last Day of Month When Scheduling Posts in Gutenberg

### ISSUE THREAD

**Issue by Korben00** [WordPress/gutenberg#48616] opened 2023-03-01 08:38 UTC
### Description

When scheduling posts in Gutenberg using the calendar, a blue dot appears under all the dates where a post is already scheduled. It's the classic behavior.
However, it has been noticed that on the last day of the month (30th or 31st, or 28th or 29th for February), the blue dot does not appear even when a post is scheduled for that date.

### Step-by-step reproduction instructions

Open the Gutenberg editor in WordPress.
Navigate to the "Posts" section and select "Add New."
Click on the calendar icon in the "Publish" section to schedule the post.
Select a date at the end of the month (30th, 31st, or 28th, 29th for February) and schedule a post.
Check the calendar view to confirm if the blue dot appears on the scheduled date.

### Screenshots, screen recording, code snippet

![SCR-20230301-d7h](https://user-images.githubusercontent.com/775494/222086910-2c67c6cf-a630-4a6f-9538-93a5dca43189.png)

### Environment info

WordPress version 6.1.1 with integrated Gutenberg editor.
Running on Linux with PHP and Nginx.
Safari, last version, on macOS last version.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-03-02 02:35
@Korben00 
Thank you for the report.

I think this problem has been fixed in #44540. I could not reproduce this issue with WordPress 6.2 Beta3, which reflects this PR, and the latest Gutenberg.

I would like to close this issue, but feel free to comment if I have missed something.

**Closed as not planned by t-hamano** 2023-03-02 02:35 UTC
Labels: [Type] Bug, [Package] Date, [Package] Edit Post
