### ISSUE TITLE
Paragraph Block Keeps Crashing. 

### ISSUE THREAD

**Issue by Dark-Cod3r** [WordPress/gutenberg#26744] opened 2020-11-05 18:10 UTC
**Describe the bug**
Updating To latest gutenberg, causing paragraph block keeps crashing.
**To reproduce**
Insert Paragraph block, error shown up.

**Expected behavior**
Should have shown paragraph block.

**Proof Video of The BUG**
https://streamable.com/4wqfo8

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.3]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [ "gutenberg plugin"]
- If the Gutenberg plugin is installed, which version is it? [9.3]

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Edge]
 - Version [88]

(Already Tried disabling all plugins, switching to twenty seven theme but still facing same bug. So please avoid suggesting these useless fixes)

**Comment by mapk** [comment] 2020-11-10 17:38
@Dark-Cod3r are you sure you're WP version is 5.3.3 or is it the latest 5.5.3?

I just tested with WP 5.5.3 and it worked fine.

![paragraph](https://user-images.githubusercontent.com/617986/98710359-63891100-2338-11eb-911e-2790139e7b72.gif)

**Comment by Dark-Cod3r** [comment] 2020-11-11 08:06
> @Dark-Cod3r are you sure you're WP version is 5.3.3 or is it the latest 5.5.3?
> 
> I just tested with WP 5.5.3 and it worked fine.
> 
> ![paragraph](https://user-images.githubusercontent.com/617986/98710359-63891100-2338-11eb-911e-2790139e7b72.gif)

I am also using 5.5.3.... (Wordpress version can be seen in Video).

**Comment by talldan** [comment] 2020-12-16 03:51
I'm unable to reproduce the issue, and an issue with the paragraph block would have seen lots of bug reports, so I'll close this.

@Dark-Cod3r this is likely caused by another plugin you have active. I'd recommend seeking help on the WordPress forums.

**Closed by talldan** 2020-12-16 03:51 UTC
Labels: Needs Testing, [Block] Paragraph, [Status] Needs More Info
