### ISSUE TITLE
No common used tags showing

### ISSUE THREAD

**Issue by moriartyviccar** [WordPress/gutenberg#9219] opened 2018-08-22 01:16 UTC
**Describe the bug**
Common Used tags were previously in a list on Classic Editor. Now they've disappeared.

**To Reproduce**
1. Go to Admin System
2. Look at tags
3. See error

**Expected behavior**
I expected a list of common used tags from the site that I could click on. Also when I do add tags manually, they disappear from the list. Sometimes they reappear, sometimes not. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
- Version 3.6.2

**Comment by designsimply** [comment] 2018-08-22 17:48
Thank you for reporting this. Closing as a duplicate of #8867.

You've noted two issues in one and we may want to open a separate issue for that. If you want to discuss here first, that's cool and can you tell me a bit more about the problem? How often does that happen for you? Is there any chance you are able to try to catch an error for that issue by opening your browser console and then adding tags and then checking the console to see if any related errors appear there?

I have seen tags temporarily flicker (if that's the right word?) after adding new ones, however, I have never seen them disappear without reappearing so I would want to know more ideas about how I can go about testing this if possible.

**Closed by designsimply** 2018-08-22 17:48 UTC
Labels: [Component] Post Settings, [Status] Duplicate, [Type] Enhancement

**Comment by moriartyviccar** [comment] 2018-08-22 18:42
Hi, thanks for your reply,

I've only just started using Gutenberg so haven't done much with it, but I run two websites and have the tag issue with both. I wrote out multiple tags for a post yesterday and looked at the admin panel > posts today and only three had registered on that article.

The classic editor has an option to click on most used tags which had it's issues with jumping up and down the screen, but was still very useful. With this it seems that I have to remember all the tags I use most often. As I type them in and confirm them, they will disappear and then sometimes reappear, but sometimes not. I wonder if it's because I don't click on the drop down option of which one to use? I should be able to just put a comma or press enter though to get the same result. Although it doesn't say which one.

**Comment by designsimply** [comment] 2018-08-22 22:06
Welcome! Thank you for trying out Gutenberg and for posting here.

Most-used tags have been requested at #8867.

> As I type them in and confirm them, they will disappear and then sometimes reappear, but sometimes not.

The ones that sometimes don't reappear, however, I can't figure out how to duplicate that problem yet. If you can think of any testing steps I can try, let me know! Otherwise, I'll circle back to this when it comes up again in another report.
