### ISSUE TITLE
Welcome message and full-screen editor keep resetting

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#34696] opened 2021-09-09 13:37 UTC
### Description

After clicking the editor welcome message away and turning off the full-screen editor layout, these reset at random intervals. The issue occurs sometimes when returning to edit a post which I've edited a few minutes ago. Sometimes the issue doesn't happen for a longer period of time. I cannot identify a sequence of actions which lead to the preferences being reset. The issue appears in several websites, each of which is running a different combination of Theme and Plugins. The debug info provided is from the site I'm working on today, which is the most common offender.

### Step-by-step reproduction instructions

1. Edit a post.
2. Click the welcome message away.
3. Turn off full-screen editing.
4. Continue working in WordPress, both in the same post and on other screens.
5. The welcome message will re-appear after a random interval, at which point, the editor reverts to full-screen editing.

### Environment info

- WordPress: 5.8.1.
- theme.json not in use.
- Browser: Brave 1.29.77 (Chromium 93.0.4577.63)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by markhowellsmead** [comment] 2021-11-10 11:33
I cannot replicate this issue with WordPress 5.8.1 and Plugin version 11.8.3.

**Comment by skorasaurus** [comment] 2022-01-12 17:42
Hi @markhowellsmead I'm closing this since you're no longer able to reproduce this.

**Closed as completed by skorasaurus** 2022-01-12 17:42 UTC
Labels: Needs Testing
