### ISSUE TITLE
Site Editor: Browse styles animation is too slow

### ISSUE THREAD

**Issue by miminari** [WordPress/gutenberg#49120] opened 2023-03-15 23:55 UTC
### Description

When a user selects a variation of the Browse styles in the Site Editor, the transition when the site preview display switches seems to be too slow and takes too long to fully display the site.

Perhaps the transition( `transition: all 0.3s ease 0s;` ) set in the iframe needs to be adjusted.

### Step-by-step reproduction instructions

1. Activate Block Themes
2. Go to 'Site Editor'
3. Click Site View
4. Click 'Styles'
5. Click 'Browse styles'
6. Choose a variation

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/487207/225466931-8f019cea-2e48-4354-a563-1856af3f8d37.mp4

### Environment info

- WordPress 6.1.1
- Gutenberg 15.3.1
- Mac OS 12.5.1
- Google Chrome 111.0.5563.64

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by inc2734** [comment] 2023-03-16 06:00
Same issue ?

https://user-images.githubusercontent.com/1094306/225528232-da8215dd-e124-4855-9e95-051b4e7e4d69.mp4

The list of patterns displayed when creating a new page also grows slowly, depending on the content.

**Comment by t-hamano** [comment] 2023-03-23 05:15
Upon investigation, this problem occurs when the block uses units such as `vh` that is dependent on the height of the viewport.  In the Twenty Twenty Three reported here, [`vh` is used for the height of the post featured image](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentythree/templates/home.html#L12).

For example, this can be reproduced by using `vh` as the unit for the min-height of the group block. Perhaps the height calculation of the iframe editor instance and the height of the blocks that depend on it interact to cause this unintended behavior.

https://user-images.githubusercontent.com/54422211/227109688-bc4f1630-3146-4db7-a236-8a3759573e59.mp4

---

However, this problem is not reproduced in WordPress 6.2 with the Gutenberg plugin disabled. Perhaps one of the reasons may be that the latest Gutenberg applies a **calculated height** to the iframe editor instance.

![iframe](https://user-images.githubusercontent.com/54422211/227110773-499264c9-5858-4e02-adaf-d42f86785033.png)

**Comment by t-hamano** [comment] 2024-02-28 04:13
I believe this issue has been fixed in https://github.com/WordPress/gutenberg/pull/59334, but if you can reproduce this issue on trunk, feel free to reopen it at any time.


https://github.com/WordPress/gutenberg/assets/54422211/f691eb25-0d31-4656-a07d-faaf22df2a37

**Closed as completed by t-hamano** 2024-02-28 04:13 UTC
Labels: [Type] Performance, [Feature] Site Editor
