### ISSUE TITLE
Pasting from apple notes into inline rich text causes the <style> contents to render first

### ISSUE THREAD

**Issue by jrmd** [WordPress/gutenberg#46280] opened 2022-12-02 14:30 UTC
### Description

When pasting text from apple notes (maybe other notes programs with styles included in the paste) into a rich text element that is handled by the inline HTML paste handler it strips the `<style>` tag but leaves the contents of the style tag in.

### Step-by-step reproduction instructions

1. Go to https://wordpress.org/gutenberg/
2. Add an image block
3. Open apple notes and write some text and then copy it
4. Paste this into the image caption field

### Screenshots, screen recording, code snippet

Output:
<img width="670" alt="Screenshot 2022-12-02 at 14 24 57" src="https://user-images.githubusercontent.com/7556775/205314589-ce9a400b-36e3-478b-9d54-a24081eef731.png">

Console log of the input/output:
<img width="725" alt="Screenshot 2022-12-02 at 14 25 14" src="https://user-images.githubusercontent.com/7556775/205314651-17896a57-b05e-49e0-a424-d00b367abf67.png">

### Environment info

- Latest on https://wordpress.org/gutenberg/
- Chrome 108 (this doesn't occur in firefox)
- Desktop with MacOS 12.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-12-05 16:50
I can confirm the issue, but it only happens when pasting inside the Image caption field. I cannot reproduce the same issue with paragraphs.

**Comment by Mamaduka** [comment] 2022-12-06 10:02
I found an original report on the issue. See #46280.

I'll close this as a duplicate. Thanks for contributing, @jrmd!

**Closed as not planned by Mamaduka** 2022-12-06 10:02 UTC
Labels: [Type] Bug, [Feature] Paste, [Status] Duplicate
