### ISSUE TITLE
Highlight: can't manually type in a custom HEX code

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#37628] opened 2021-12-26 02:07 UTC
### Description

The Highlight won't let me manually enter an HEX code, and the color picker also jumps.
Related bug: https://github.com/WordPress/gutenberg/issues/37018

![](https://user-images.githubusercontent.com/15944096/147397036-387594b9-4d03-4728-8a43-b2b69e938163.gif)

Current workaround is to copy/paste the HEX code (though it has a minor issue too, see https://github.com/WordPress/gutenberg/issues/37018#issuecomment-1001093803), or set it manually in HTML view.

### Step-by-step reproduction instructions

1. Add a text with a Paragraph block
2. Use Highlight, and manually set a HEX code

### Environment info

*   Gutenberg 12.0.1
*   WordPress 5.8.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by lwangdu** [comment] 2021-12-26 17:48
I am having seem issue with TT2 and WordPress 5.9 bate 4.

**Comment by annezazu** [comment] 2021-12-27 16:28
I can replicate with TT1 and 5.9 beta 4 as well cc @jorgefilipecosta once more.

**Comment by jorgefilipecosta** [comment] 2022-01-03 18:47
This issue seems to have been fixed on https://github.com/WordPress/gutenberg/pull/36263. I guess the fix needs some update. @alshakero would you be able to have a look?

**Comment by alshakero** [comment] 2022-01-04 13:50
I can confirm this is fixed by https://github.com/WordPress/gutenberg/pull/36263

**Comment by jorgefilipecosta** [comment] 2022-01-04 15:31
Hi @alshakero, I'm not sure if the issue is fixed I still seem to be able to replicate it on the trunk.

**Comment by alshakero** [comment] 2022-01-05 01:02
I'll double check tomorrow.

**Comment by Greatdane** [comment] 2022-02-17 04:33
@alshakero - Any update on this one, please? 

Also, is this a duplicate of https://github.com/WordPress/gutenberg/issues/37018 ?

**Comment by tellisbethel** [comment] 2022-03-25 09:16
Hey there, @alshakero! If you're still on this particular case, did you get a chance to take another look at this issue? If not, is there anyone else we should ping? Thanks!

**Comment by annezazu** [comment] 2022-05-18 21:32
Closing this back out as it should be resolved based on my testing with 6.0 RC4. Feel free to let me know if it needs to be reopened!

**Closed as completed by annezazu** 2022-05-18 21:32 UTC
Labels: [Type] Bug, [Status] In Progress, [Feature] Colors

**Comment by dhruv-15-03** [comment] 2025-07-17 12:09
Working on this! Will open a PR soon.
