### ISSUE TITLE
Show synced patterns (reusable blocks) in the Patterns tab of the main inserter

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52224] opened 2023-07-02 17:18 UTC
I got the idea from this core ticket: https://core.trac.wordpress.org/ticket/58697

## What problem does this address?
Patterns appear in `My Patterns` on the Library page of the Site Editor, with or without synced status.

![library](https://github.com/WordPress/gutenberg/assets/54422211/2135bb26-339e-4479-85ef-68f5ad2038db)

However, in the main block inserter, it is treated as a `Synced Pattern` (conventional Reusable Blocks), separate from the pattern tab.

![synced-patterns](https://github.com/WordPress/gutenberg/assets/54422211/2fde055b-41fa-4336-bfd7-46f96d8ec208)

## What is your proposed solution?

I would expect that the synced patterns tab would be discontinued and that the synced patterns would also be displayed in "My Patterns" in the Patterns tab.

In this case, I think the state of synchronization needs to be represented in some way.

**Comment by eric7186** [comment] 2023-07-03 15:03
## Bug Report
### Description
Describe the bug.

### Environment
- WordPress: 6.3-beta2
- PHP: 8.1.9
- Server: Apache/2.4.43 (Win32) mod_fcgid/2.3.9a
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.9)
- Browser: Chrome 114.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins:
  * WordPress Beta Tester 3.5.0

### Steps to Reproduce
1. Create a pattern with the option selected: Keep all pattern instances in sync.
2. The Pattern shows as a synced pattern here
3. 🐞 Synced pattern tab does not show up in the block inserter. I also checked firefox and edge browsers. It did work earlier in firefox but not today
### Expected Results
1.  ✅ What should happen.

### Actual Results
1.  ❌ What actually happened.

**Comment by annezazu** [comment] 2023-07-03 19:52
This seems to be a duplicate of https://github.com/WordPress/gutenberg/issues/51945. Closing out as a result.

**Closed as completed by annezazu** 2023-07-03 19:52 UTC
Labels: [Type] Enhancement, [Feature] Inserter, [Feature] Patterns
