### ISSUE TITLE
Unable to paste content into Verse block

### ISSUE THREAD

**Issue by pollyplummer** [WordPress/gutenberg#1909] opened 2017-07-15 03:56 UTC
## Issue Overview

When attempting to paste content from a webpage into the Verse block in version 0.5.0, it all pastes in as one line without respect to the formatting or line breaks. I'm using Chrome.

## Steps to Reproduce (for bugs)

1. Copy some verse from poets.org
2. Paste into verse block

## Expected Behavior

Line breaks should be preserved.

**Comment by iseulde** [comment] 2017-07-20 14:04
This seems to work for me... What exactly are you copy pasting? If it's long paragraphs, note that it won't wrap. If you paste poems with line breaks, it should work.

**Comment by iseulde** [comment] 2017-07-20 14:05
(Please link to the fragment you are copying.)

**Comment by jasmussen** [comment] 2017-08-18 08:32
Thanks for the ticket, but I can't reproduce so I'm closing for now:

![verse](https://user-images.githubusercontent.com/1204802/29450800-7e362e78-8400-11e7-9c3d-371e8a30933c.gif)

**Closed by jasmussen** 2017-08-18 08:32 UTC
