### ISSUE TITLE
New tag don't assign, retype and it's ok

### ISSUE THREAD

**Issue by RomainDev25** [WordPress/gutenberg#17159] opened 2019-08-23 09:09 UTC
**Describe the bug**
I have a little problem when I create new tag in editor.
I write it tap enter and I need to retype second time to select it. I don't have this problem with existing tag

**To reproduce**
You can see here the problem
https://streamable.com/f2qa0

**Desktop (please complete the following information):**
 - OS: mac OS X 10.14.6 / Windows 10
 - Browser Edge, Chrome, Safari, Firefox
 - Version 

**Additional context**
- Version Wordpress : 5.2.2

Thanks

**Comment by talldan** [comment] 2019-08-23 10:16
Tried testing, but I was unable to reproduce this in the latest version of the editor.

**Comment by youknowriad** [comment] 2019-08-23 11:33
I don't reproduce either, it might have been fixed in recent versions of Gutenberg.

**Closed by youknowriad** 2019-08-23 11:33 UTC
Labels: Needs Testing, [Type] Bug

**Comment by RomainDev25** [comment] 2019-08-23 11:48
Hello, I have the last version of wordpress, so it's fixed in the next release ?

**Comment by youknowriad** [comment] 2019-08-23 12:08
Yes, the next major release. @RomainDev25 you could also try to confirm yourself by installing the Gutenberg plugin.

**Comment by RomainDev25** [comment] 2019-08-23 12:11
Ok, no problem, I wait with the next release of wordpress.
