### ISSUE TITLE
Site Title Block: Custom CSS classes not being outputted on the frontend

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#23813] opened 2020-07-09 04:18 UTC
Site Title block has an option to add custom CSS classes in the Advanced section, but the class added there is not added to the element on the frontend.

**To reproduce**
1. With Full Site Editing enabled in Gutenberg go to "Site Editor (beta)" in WP Admin.
2. Start editing the site header. Select Site Title block.
3. Open the Advanced section in the options column on the right-hand side of the screen.
4. Add any custom CSS class name in the "Additional CSS class(es)" field. Click "Update design", and then "Save".
5. Preview the site. Open the developer tools and inspect the site title element. Notice the custom CSS class is not there.
6. The issue happens only on the frontend, the setting itself seems to be saved correctly.

**Expected behavior**
For the custom CSS class to be added to the site title elements' classes on the front end.

**Screenshots**
Editor view:

![image](https://user-images.githubusercontent.com/4550351/86996201-59ba9a00-c1ee-11ea-921e-8ebe164d060c.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/86996302-a3a38000-c1ee-11ea-921c-f79de3939b9e.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg plugin: 8.5.0

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser Chrome 83.0

**Comment by carolinan** [comment] 2020-07-09 09:44
Hi
This is a duplicate of https://github.com/WordPress/gutenberg/issues/21903, https://github.com/WordPress/gutenberg/issues/22097 and possibly solved by https://github.com/WordPress/gutenberg/pull/23007/

**Closed by carolinan** 2020-07-09 09:44 UTC
Labels: Needs Testing, [Block] Site Title, [Feature] Full Site Editing, [Status] Duplicate
