### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12857] opened 2018-12-13 21:23 UTC
<img src="https://i.imgur.com/auDRFq4.png">

Working with the editor is way too slow.

**Comment by chrisvanpatten** [comment] 2018-12-13 21:34
Hi @manake -

Have you read [this blog post](https://make.wordpress.org/core/2018/12/13/5-0-2-editor-performance-and-bug-fixes/) which discusses how the next release (5.0.2) will include a number of performance improvements? I'd recommend checking that out and trying Gutenberg 4.7, or waiting for WordPress 5.0.2 if you can't use the plugin.

In the interest of triaging this issue, could you clarify how the experience is slow for you so we can determine if this is a duplicate of one of our existing performance tickets, or a new bug you're experiencing?

**Comment by aduth** [comment] 2018-12-13 21:52
In your screenshot I see "47.7 MB transferred", which is quite exceptional. By contrast, a stock installation of WordPress 5.0 transfers 4.5 MB for me on the editor screen.

Could you share more about the specific content of the post you're editor, or plugins which may be contributing to the page size?

**Comment by designsimply** [comment] 2018-12-17 23:46
Closing in favor of #11782 but would also like to encourage you to re-open this issue if you think it should remain separate and please send us more details about the content of the post you're editing, a list of your active plugins, and the versions of WordPress and Gutenberg you are testing (if you have the plugin installed alongside WP 5.0.1+).

**Closed by designsimply** 2018-12-17 23:46 UTC
Labels: [Status] Duplicate, [Status] Needs More Info, [Type] Performance
