### ISSUE TITLE
Classic block should style the options in the Formats dropdown like the classic editor does

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#12123] opened 2018-11-20 17:34 UTC
Related: #8670 

When core's `tiny_mce_before_init` hook returns a value that contains `style_formats` the Classic block does not style the options in the Formats dropdown (like the classic editor does) and it should.

Screenshots from #8670:

Setting in [Advanced TinyMCE Configuation](https://wordpress.org/plugins/advanced-tinymce-configuration/) I've used on 1 particular site for years, this corresponds to returning `style_formats` in `tiny_mce_before_init`.

![43791017-90e33258-9a31-11e8-9a9a-02c02ff9d015](https://user-images.githubusercontent.com/3824560/48791630-5c7e1980-ecaf-11e8-8e6c-63632cc85e43.png)

With that setting, the classic editor produces:

![43791293-708a0fa8-9a32-11e8-8287-1b1cc080142b](https://user-images.githubusercontent.com/3824560/48791669-77e92480-ecaf-11e8-9650-62f1936e5963.png)

and the Classic block (after #10968 was merged) produces:

![43791398-cdca18d4-9a32-11e8-8d51-3f9f9e18ed3a](https://user-images.githubusercontent.com/3824560/48791723-a0711e80-ecaf-11e8-9745-b379413f0e0d.png)

**Comment by pbiron** [comment] 2018-11-20 17:36
It could be argued that the dropdown options not being styled is a bug, but this close to the 5.0 release I didn't want to add to the panic/worry of releasing with open known bugs, so I opened this issue an enhancement...since the "bug" doesn't actually affect behavior.

Feel free to relabel this as a bug if you want to.

**Comment by azaozz** [comment] 2019-02-07 13:26
Can't reproduce any more, probably fixed elsewhere. The "Formats" drop-down looks identical in Classic Editor and Classic Block:

![formats](https://user-images.githubusercontent.com/743931/52414072-f5247880-2aeb-11e9-8980-1324c87b3209.png)

There is another bug, possibly upstream (affecting both places): text color is not shown in the drop-down. Adding 

`{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},` 

to the formats config yields inline style

`text-decoration: none solid rgb(255, 0, 0);`

That's better fixed upstream :)

Closing as "worksforme". Feel free to reopen if that drop-down still looks different in Classic Block.

**Closed by azaozz** 2019-02-07 13:26 UTC
Labels: Extensibility, [Block] Classic, [Type] Bug

**Comment by pbiron** [comment] 2019-02-07 15:14
I'm still not seeing the the styling of the _Formats_ dropdown in the Classic block...however I have an idea as to why (it _may_ have to do with `editor-style.css` not loading properly for the Classic block).  When I get a chance I'll look into that and and reopen if necessary.

**Comment by pbiron** [comment] 2019-02-15 17:12
> I'm still not seeing the the styling of the _Formats_ dropdown in the Classic block...however I have an idea as to why (it _may_ have to do with `editor-style.css` not loading properly for the Classic block). When I get a chance I'll look into that and and reopen if necessary.

I didn't realize that I had to add `add_theme_support( 'editor-styles' );` to the theme's setup to get that styling in the Classic block.

Once I added that, I'm now seeing the styling on the _Formats_ dropdown.  So, all is well.  thanx.
