### ISSUE TITLE
Group Block Accessability

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#22595] opened 2020-05-25 11:24 UTC
The accessability of group blocks without background is currently very poor.

![group-block-accessability](https://user-images.githubusercontent.com/41627893/82808521-6f684000-9e8a-11ea-8d36-6b25f86e30ce.PNG)

As you can see I built a paragraph block inside a group block. The only way to access the group blocks attributes is to navigate to it using arrow keys or the block navigation. There's no way to select it with my mouse. 

Plus as an user I can't see that a block is inside a group without those navigation techniques.

**Editor Version**: 8.1.0
**WordPress Version**: 5.4.1

**Comment by talldan** [comment] 2020-05-27 01:25
@bfiessinger Thanks for reaching out. There's an issue created here that seems to cover the issue - #20453. I'll close this one as a duplicate of that.

**Closed by talldan** 2020-05-27 01:25 UTC
