### ISSUE TITLE
I cant save this block of code

### ISSUE THREAD

**Issue by ChinchillaReactor** [WordPress/gutenberg#19658] opened 2020-01-15 04:05 UTC
**Describe the bug**
I marked the new block as Code block... then I pasted this code of ES6
**To reproduce**
1.- I created a code block
2.- I pasted
`function tableReady(arr) {
			var nextIndex = 0;
			return {
				next() {
					if(nextIndex < arr.length) {
						return {value: arr.shift(), done: false}
					} else {
						return {done: true}
					}
				}
			}
		}

		var waitingList = ['Sarah', 'Heather', 'Anna', 'Meagan'];
		var iterateList = tableReady(waitingList);

		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`Is this finished? ${iterateList.next().done}`);

	</script>
	<title>Iterators</title>
</head>
<body>
</body>	
</html>`
3.- I clicked update (post)

**Expected behavior**
Saved and Updated content

**Screenshots**
There is no error... just "time out"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: Chrome 
 - Version: 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
Wordpress version: 5.2.5

**Comment by youknowriad** [comment] 2020-01-15 09:04
I don't have any issue with the same code above. Do you have any plugins that could cause conflicts?

**Comment by ChinchillaReactor** [comment] 2020-01-16 04:34
I dont think so. It was just a timeout.
Same day, I posted a lot of other codes blocks.
http://ntala.chinchillareactor.com/index.php/2020/01/15/

and the only one impossible (to be saved) was this one..
http://ntala.chinchillareactor.com/index.php/2020/01/15/ecmascript6-011-iterators/

What do you need?

**Comment by ChinchillaReactor** [comment] 2020-01-16 07:11
Hi again,
This block has the same problem:
`var promise = new Promise(function(resolve, reject) { 
  const x = "geeksforgeeks"; 
  const y = "geeksforgeeks"
  if(x === y) { 
    resolve(); 
  } else { 
    reject(); 
  } 
}); 
  
promise. 
    then(function () { 
        console.log('Success, You are a GEEK'); 
    }). 
    catch(function () { 
        console.log('Some error has occured'); 
    }); `
I cant update a previous post after pasting this.

**Comment by youknowriad** [comment] 2020-01-16 09:08
Just tested again and I'm still not able to reproduce. Maybe this was fixed in the last versions of Gutenberg. Can you try with the plugin and see?

**Comment by ChinchillaReactor** [comment] 2020-01-17 00:53
Gentlemen,
If this cant be reproduced in the newer version of guttenber, it is fine. But i won't update my wordpress sites again. 
The latest destroyed everything in 3 of them. bugs everywhere

**Comment by ChinchillaReactor** [comment] 2020-01-17 02:10
Ok, updated everything. However, it still there.

this are the plugins I'm using:

- CM Tooltip Glossary by CreativeMindsSolutions.
- Contact Form 7 by Takayuki Miyoshi.
- Elementor by Elementor.com.
- Gallery Custom Links by Jordy Meow.
- Google Analytics for WordPress by MonsterInsights by MonsterInsights.
- Image Widget - gallery & lightbox by rb by rbPlugins.
- Plugins List by David Artiss.
- Portfolio Filter Gallery by A WP Life.
- Press Elements - Widgets for Elementor by Press Elements.
- ReCaptcha v2 for Contact Form 7 by IQComputing.
- Social Login, Social Sharing by miniOrange by social login (miniOrange).
- UpStream by UpStream.
- WP Mail SMTP by WPForms.
- WP Security Audit Log by WP White Security.

**Comment by youknowriad** [comment] 2020-01-17 09:28
The most suspect plugin for me is "WP Security Audit Log" but that's not certain.
You can consider using https://wordpress.org/plugins/health-check/ to test disabling your plugins without affecting your visitors.

**Comment by ChinchillaReactor** [comment] 2020-01-19 01:39
Fixed.
There is a problem with the PHP version. 
I updated the PHP in apache2 in the VM ... from 7.0 to 7.3
and now I was able to update the one with this code:

`promise. then(function () { console.log('Success, You are a GEEK'); }). catch(function () { console.log('Some error has occured'); });`

So think that was the reason

**Comment by ChinchillaReactor** [comment] 2020-01-19 01:47
Verified...
Now I was able to fix this one too:
`<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.29/browser.js"></script>
	<script type="text/babel">

		var title = 'ES6';
		console.log(typeof title[Symbol.iterator]);

		var iterateIt = title[Symbol.iterator]();
		console.log(iterateIt.next());
		console.log(iterateIt.next());
		console.log(iterateIt.next());
		console.log(iterateIt.next());

		function tableReady(arr) {
			var nextIndex = 0;
			return {
				next() {
					if(nextIndex < arr.length) {
						return {value: arr.shift(), done: false}
					} else {
						return {done: true}
					}
				}
			}
		}

		var waitingList = ['Sarah', 'Heather', 'Anna', 'Meagan'];
		var iterateList = tableReady(waitingList);

		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`${iterateList.next().value}, your table is ready`);
		console.log(`Is this finished? ${iterateList.next().done}`);

	</script>
	<title>Iterators</title>
</head>
<body>
</body>	
</html>`

It is the PHP version

**Comment by youknowriad** [comment] 2020-01-20 08:44
I'm not certain it was the php version personally, but you probably had a php error somewhere in your code that got fixed with the update.

**Closed by youknowriad** 2020-01-20 08:44 UTC
Labels: [Status] Needs More Info
