### ISSUE TITLE
I'm not visible in list of Authors?

### ISSUE THREAD

**Issue by dankargo** [WordPress/gutenberg#8526] opened 2018-08-04 12:25 UTC
I installed the Gutenberg plugin to my site and when adding a new post,  I can see every other editor on my website in the Authors dropdown list, except myself.

I gathered that the issue was likely because my account is the admin one (ID=1) and perhaps Gutenberg doesn't display the super admin as an option.  So I created a brand new user account, assigned myself a post and yet I am still not visible in the Author list.   I thought perhaps its just me,  so I asked another administrator to check.  Whilst the value correctly defaulted to themselves when they went to the Add Post screen,  they confirmed that neither of my two accounts were showing up in the list of authors.

I've tried changing my second account to an editor to see if it made a difference but nothing -  the add post screen simply selects the first person from the alphabetical ordered list rather than defaulting to me.

Screenshots attached.

Screenshots:

![screen shot 2018-08-04 at 13 18 45](https://user-images.githubusercontent.com/42091466/43676448-77cff732-97e9-11e8-82ce-995d16ac9ae1.png)

![screen shot 2018-08-04 at 13 19 12](https://user-images.githubusercontent.com/42091466/43676447-77bc248c-97e9-11e8-81ce-ab6eedbf5d2c.png)

**Comment by earnjam** [comment] 2018-08-04 18:31
I haven't been able to recreate this. 

The author dropdown uses the result of a REST API request for `/wp/v2/users/?who=authors&per_page=-1`. If your user isn't returning in that result, then there is probably something filtering that. Could there be another plugin manipulating the REST API response to filter out the active username?

The other thing to check is that it is sorted alphabetically by login, not display name. So if your username is different from `Dan` or `Danny`, then you might confirm that you are not showing elsewhere on the list. 

In an HTML select element, if the `value` isn't included in the option list, then it will just default to the first element of the list. So if you're not being included in the full list, that makes sense it would just select the first person.

**Comment by dankargo** [comment] 2018-08-04 19:04
Many thanks for the response.

I have just had a look at my plugins list and can't see anything that may be using the REST API. I will have a more thorough check when I return home from work later on.

Logged in as my primary account (ID=1), I can now see the second account that I created earlier today (Danny), in the dropdown list.   Ideally though, I would like to be able to use my primary as I have almost 300 posts assigned to myself. 

Screenshot attached  (sorry I've blanked surnames just to stay within GDPR guidelines!)

![screen shot 2018-08-04 at 19 59 38](https://user-images.githubusercontent.com/42091466/43679686-9171e654-9821-11e8-8540-e94abcbff186.png)

**Comment by designsimply** [comment] 2018-08-06 19:50
I tested on a multisite install and was unable to reproduce the problem described. Here are my testing steps:

1. Go to WP Admin > Users and confirm the logged-in superadmin user is listed there. 
1. Open a new post as superadmin.
1. Check to see if the superadmin is listed in Add Post > Settings > Document > Authors.
1. Go to WP Admin > Users and add a new user with the Editor role.
1. Log in as the Editor.
1. Check to see if the Editor is listed in Add Post > Settings > Document > Authors.

<strong>Result:</strong> I can always see the logged-in superadmin or editor in the Authors list in the Document sidebar.

<sup>Tested with Gutenberg 3.2 on WordPress.com using Safari 11.1.2 on macOS 10.13.6.</sup>

@dankargo can you spot anything different in my testing steps compared to yours? 

Can you verify that your superadmin user appears in WP-Admin > Users? 

How many users total are there currently for the site you are testing? 

As a basic troubleshooting step, can you confirm whether or not clearing browser cache and cookies and logging in again resolves the problem? (this is to rule out a local caching glitch)

**Comment by dankargo** [comment] 2018-08-08 18:53
Thank you all for responding and for attempting to replicate the issue.  I can confirm that the steps @designsimply took were identical to what I did.  

The superadmin user (Dan) does indeed show in the list of users.   Clicking on the 'Administrator' link also brings up the account, along with the other administrators of the site (who are able to see themselves in the list and confirm that post author defaults to themselves)

![screen shot 2018-08-08 at 19 48 04](https://user-images.githubusercontent.com/42091466/43857700-044d5dfa-9b44-11e8-8bd9-a9ebdfc57592.png)

I even attempted changing my email address in the hope that it would trigger something but unfortunately not.   The only thing different with my account, opposed to other admins, is that I have a green jetpack badge which signifies that my profile is linked to Jetpack.  I have disabled Jetpack (along with other plugins) to see if it makes a difference but it does not.

I have purged the site cache as well as cloudflare cache.

I'd be very happy to screen share over Teamviewer or Skype in case I have missed something that may be strikingly obvious to others.

**Comment by lclarke522** [comment] 2018-08-17 00:09
I have the same problem on my site. I am the only administrator and my name is not on the list. Only the two authors are listed.

One thing I have in common with @dankargo is that I, too, have the Jetpack thingy next to my user.

**Comment by AndreaBarghigiani** [comment] 2018-08-19 08:39
Same problem here. If I am logged in as the user that have created the article I am not able to see myself on the list of authors. Even when the dropdown is close I see the alphabetically first user of the list but is not showing myself since I sould be the first of the list.

![author-not-shown](https://user-images.githubusercontent.com/190159/44306880-3b4c1b00-a398-11e8-9307-105bb5eaa1a0.png)

This kind of error happen only in Gutenberg in the Document sidebar because if I check the table showing all the articles I correctly see myself in there:

![author-showing-list](https://user-images.githubusercontent.com/190159/44306893-9f6edf00-a398-11e8-965d-32f45c4219a3.png)

I've also tried to preview the article and I confirm that Gutenberg does not change the author of the article.

I think that this is only a UI error and all the users are not been touched but I think that this issue could confuse some users (myself included) because when you simply chech the author of an article **inside Gutenberg** you'll see a different name instead of yours.

![author-different-gutenberg](https://user-images.githubusercontent.com/190159/44306912-01c7df80-a399-11e8-94aa-e6ec930d7967.png)

Hope this can help and address better the situation, I think that there is some problem with the API call because in a WordPress installation there are not only the Authors that can publish or edit a Post.

For example, in my own case I am usign LifterLMS plugin and my user has a role of LMS Manager. This role gives me the ability to manage all the courses and lessons (is an LMS plugin) as well as my posts and pages.

I think that this API call sould be changed in a search for users that has the capability of `edit_posts` in order to show a list of all users that can write something in WordPress.

PS: I've tried to create a better request URL but on each site i tried to call the `/wp-json/wp/v2/users/` I get a list of only one user, even if I know that inside the installation there are more. Maybe it's me that I do not know the use of the REST API ;)

**Comment by swissspidy** [comment] 2018-08-19 11:54
> For example, in my own case I am usign LifterLMS plugin and my user has a role of LMS Manager. This role gives me the ability to manage all the courses and lessons (is an LMS plugin) as well as my posts and pages.

Chances are high that your role doesn't have the correct `user_level` set. If that's the case, your user would also be missing in the list in the classic editor.

> I think that this API call sould be changed in a search for users that has the capability of `edit_posts` in order to show a list of all users that can write something in WordPress.

Unfortunately that's not as easy as one might think. However, that's the goal with core ticket https://core.trac.wordpress.org/ticket/16841.

**Comment by AndreaBarghigiani** [comment] 2018-08-19 16:10
@swissspidy I do not understand why you refer to `user_level` since it shoul be deprecated from version 2 and if I'm not getting wrong we should use roles and capabilities to recognize the level of a user.

I understand that Gutenberg changes the game and we can't connect to the database and run any query against the database. Also I understand that the REST API can not cover yet all the the functionality we had but I do not think that we should rely on something that should be deprecated.

Anyway I was trying to run some queries against `http://demo.wp-api.org/` but it seems I can't do something like this `http://demo.wp-api.org/wp-json/wp/v2/users/?username=jsmith`.

I am not and expert JavaScript developer and at the moment I didn't have mush time to use the REST API with some projects, but I undestood that if I want to get a list of users by `capabilities` I sould change the [context](https://developer.wordpress.org/rest-api/reference/users/#list-users) of my call but I do not know how to do it. Do I have to be autenticated to run it?

**Comment by swissspidy** [comment] 2018-08-19 16:39
@AndreaBarghigiani Although they're deprecated, user levels are still used by core. That's why they still matter, at least in the classic editor. Please read the Trac ticket I linked to understand the background.

**Comment by designsimply** [comment] 2018-09-13 21:58
Since more people have reported seeing the same problem since I last replied, I've added the `Needs Testing` label to see if we can get a 2nd tester to have a look at the steps to try to reproduce the problem again.

**Comment by mikeselander** [comment] 2018-09-25 17:14
FWIW I encountered this issue in multisite as well and it was not an issue with Gutenberg. Instead, a plugin (I haven't yet had time to track down which one) modified the roles when creating a new subsite and destroyed the permissions which caused the `who` clause in all author queries in core to fail.

The solution was to repair the roles in all affected subsites using [`wp role reset`](https://developer.wordpress.org/cli/commands/role/reset/)

**Comment by dankargo** [comment] 2018-10-27 13:41
I'm afraid to resolve it, I created a new user account with admin privileges and transferred all posts from user id = 1 to the new profile.  It wasn't ideal but sorted the issue.

**Comment by youknowriad** [comment] 2018-11-03 18:55
Looks like this is most likely related to wrong permissions persisted into the database. I'm closing for now.

**Closed by youknowriad** 2018-11-03 18:55 UTC
Labels: UI Components, [Status] Needs More Info
