### ISSUE TITLE
Gallery: fix media modal configuration

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1444] opened 2017-06-26 12:35 UTC
The media modal should be opened in the "gallery mode" where you can click to select multiple images.

**Comment by westonruter** [comment] 2017-07-09 05:36
Was this not implemented in 70c5b7fc5b501110589b6c05052fbe6ad3d7f957? The current behavior in the plugin seems to be the same as the classic post editor.

**Comment by mkaz** [comment] 2017-07-18 16:50
@westonruter - the behavior in the change you referenced opened the correct gallery modal when editing a gallery. I've got a change coming in shortly that will open the correct modal when first creating the gallery. The big difference is the current incorrect method requires you to ctrl/cmd/shift click to select multiple images, while the correct method is to just click each image and they are automatically multiple selected.

**Comment by westonruter** [comment] 2017-07-18 20:50
@mkaz ok, then is this not a duplicate of #1401? I had opened a PR to fix the issue there: #1820.

**Comment by mkaz** [comment] 2017-07-19 00:17
Ah, I didn't see #1401 until now - yes, it is a duplicate.
Let me test out your PR, I had some troubles when using the MediaUploadButton with how images get selected and inserted in.

**Comment by mkaz** [comment] 2017-07-20 17:07
Closing in favor of #1401 and PR #1820

**Closed by mkaz** 2017-07-20 17:07 UTC
Labels: Blocks, Media, [Type] Task
