### ISSUE TITLE
Navigating past the end of a list of blocks in the inserter with the keyboard throws errors

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#1662] opened 2017-07-03 11:52 UTC
This is getting fixed as part of the "recent blocks" work.

The current code expects the blocks to be in the order they were registered in, and this doesn't happen with recent blocks. The fix I'm working on with filter the blocks into a visibleBlocks list when a tab is changed or a search happens, and this list will be used for navigation.

**Comment by swissspidy** [comment] 2017-07-03 12:04
Duplicate of #1606 and probably fixed in #1661.

**Closed** 2017-07-03 12:05 UTC
