### ISSUE TITLE
Editor sometimes doesn't load

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1310] opened 2017-06-20 15:24 UTC
Sometimes when I click on "Gutenberg" in the post list table to edit a post, the app throws a JavaScript error. Probably 1 out of 4 times. The rest of the time it works fine.

The error in the console is as follows:

```
[Error] React caught an error thrown by one of your components.

value@https://example.com/content/plugins/gutenberg/editor/build/index.js?ver=1497618704:16:40809
value@https://example.com/content/plugins/gutenberg/editor/build/index.js?ver=1497618704:16:40277
h@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:13401
i@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:18475
l@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:19188
s@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:20102
c@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:20197
m@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:20724
g@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:21090
T@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:23524
t@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:26279
updateContainer@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:26617
https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:5:3246
S@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:7:23922
In@https://example.com/content/plugins/gutenberg/vendor/react-dom.min.912dc6cf.js?ver=4.8:5:3216
c@https://example.com/content/plugins/gutenberg/editor/build/index.js?ver=1497618704:16:14336
global code@https://example.com/wp-admin/admin.php?page=gutenberg&post_id=1484:1755:31
	Tn (react-dom.min.912dc6cf.js:4:26823)
	C (react-dom.min.912dc6cf.js:7:22597)
	i (react-dom.min.912dc6cf.js:7:18502)
	l (react-dom.min.912dc6cf.js:7:19189)
	s (react-dom.min.912dc6cf.js:7:20103)
	d (react-dom.min.912dc6cf.js:7:20286)
	h (react-dom.min.912dc6cf.js:7:20470)
	m (react-dom.min.912dc6cf.js:7:20741)
	g (react-dom.min.912dc6cf.js:7:21091)
	T (react-dom.min.912dc6cf.js:7:23525)
	t (react-dom.min.912dc6cf.js:7:26280)
	updateContainer (react-dom.min.912dc6cf.js:7:26618)
	(anonymous function) (react-dom.min.912dc6cf.js:5:3247)
	S (react-dom.min.912dc6cf.js:7:23923)
	In (react-dom.min.912dc6cf.js:5:3217)
	c (index.js:16:14337)
	Global Code (admin.php:1755)
```

```
[Error] TypeError: undefined is not a constructor (evaluating 'new wp.api.collections.PostRevisions({},{parent:t})')
	g (react-dom.min.912dc6cf.js:7:21446)
	T (react-dom.min.912dc6cf.js:7:23525)
	t (react-dom.min.912dc6cf.js:7:26280)
	updateContainer (react-dom.min.912dc6cf.js:7:26618)
	(anonymous function) (react-dom.min.912dc6cf.js:5:3247)
	S (react-dom.min.912dc6cf.js:7:23923)
	In (react-dom.min.912dc6cf.js:5:3217)
	c (index.js:16:14337)
	Global Code (admin.php:1755)
```

On that line 1755 on admin.php, there's the inline script that starts the editor:

```js
wp.editor.createEditorInstance( 'editor', window._wpGutenbergPost );
```

Tested using the current version in the plugin directory and Safari 11.

Let me know if I should build from master or anything to further test this.

**Comment by aduth** [comment] 2017-06-20 17:03
Duplicate of #1235, slated to be fixed by #1245

**Closed by aduth** 2017-06-20 17:03 UTC
