### ISSUE TITLE
Reintroduce support for meta+Y shortcut

### ISSUE THREAD

**Issue by fr-laurentn** [WordPress/gutenberg#8921] opened 2018-08-13 13:04 UTC
Hello, 

As discussed in #71, the support for meta+Y shortcut has been removed in https://github.com/WordPress/gutenberg/blob/0a211472bea6338dc106b87b51743524fc2f58b3/packages/editor/src/components/rich-text/index.js#L170

The only way to redo an undone action for Windows users is to type CTRL+SHIFT+Z which is very uncommon (and not very user friendly).

CTRL+Y is a standard shortcut known by most of Windows users, unlike CTRL+SHIFT+Z.

Would it be possible to reintroduce the use of the meta+Y shortcut (or at least CTRL+Y)?

Thanks a lot,

EDIT: please note that I'm not asking to remove the CTRL+SHIFT+Z shortcut.

**Comment by iseulde** [comment] 2019-02-08 10:05
Yes, if it's the way for Windows, then we probably should. It's a bit annoying that there's no universal shortcut for it. On a May, cmd+Y is used in browsers to show all history, so we'd have to only add this shortcut for Windows, otherwise it clashes with a browser shortcut.

**Comment by afercia** [comment] 2020-09-06 11:45
This was reported also on Trac, see https://core.trac.wordpress.org/ticket/49459, and that was one of the tickets the accessibility team milestoned for WordPress 5.5. The accessibility team would need some help ([we did ask for help](https://wordpress.slack.com/archives/C02RQBWTW/p1591820698452300)) to help this issue move on 🙂 Setting the milestone to WordPress 5.6. for visibility.

**Comment by merapi** [comment] 2020-10-21 15:22
CMIIW: `meta+y` on Windows is `win+y` (does nothing, win = metaKey), on macOS, it's `command+y` (we don't want to hijack this [Show Full History], command = metaKey), can't we just use `["ctrl+z", "command+z"]` for undo and `["ctrl+y", "command+shift+z"]` for redo?

**Comment by Slapbox** [comment] 2020-12-15 23:54
@afercia can you elaborate on what help is needed? I'm having trouble accessing the Slack thread and this issue is sooooo aggravating. I love WordPress and I appreciate all the team does, but I really can't convey how much the lack of Windows redo hotkey support irks me. I really hope this will be prioritized, because the issue is 30 months old now and I always pray it will be resolved the next time WordPress updates, but it never is.

It's especially bad for us since we have a global hotkey assigned to <kbd>Ctrl+Shift+Z</kbd> which means no redo unless we reassign that key any time we use WordPress. 99.9999% of the time not an issue on Windows because every other application supports <kbd>Ctrl+Y</kbd>.

**Comment by Nantris** [comment] 2022-07-20 23:01
It's been almost 4 years since this was reported Can we please get this simple quality-of-life feature back? 

Nobody uses <kbd>Ctrl+Shift+Z</kbd> for redo on Windows, and it conflicts with a global hotkey we use which makes the lack of the <kbd>Ctrl+Y</kbd> hotkey all the more annoying. That leaves us with only the option of using the mouse to redo, which is a horrible workflow.

I'm not sure who the relevant people would be to ping for this, so apologies for probably pinging the wrong people.

@afercia  @adamziel @ntsekoura @ellatrix

**Comment by ellatrix** [comment] 2022-07-22 12:04
@Slapbox I created #42627. Could you test?

**Comment by ellatrix** [comment] 2022-07-22 12:07
> it conflicts with a global hotkey

What program is using that combination?

**Comment by Nantris** [comment] 2022-07-22 22:06
@ellatrix thank you so much for your speedy response and PR to resolve this! I'm very appreciative for you taking a crack at this.

I'd be happy to test the changes, but I'm not sure how I can actually do that?

> What program is using that combination?

The program using that hotkey globally is [Recollectr](https://recollectr.io/). It's re-assignable, but it's a pain to re-assign it and revert it only when working in WordPress. Besides that, my brain is pretty much locked to <kbd>Ctrl+Y</kbd> for redo after decades of using it.

**Closed** 2022-07-27 18:50 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Feature] Rich Text, [Feature] History
