### ISSUE TITLE
Heading: Add `h1`, `h2`, `h3`… to the slash commands

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#66959] opened 2024-11-13 11:52 UTC
## What problem does this address?
Often times the user knows already which level of heading they want to use.
The slash command is a great shortcut to insert the heading block. However, it always starts at the level of `h2` as a default. If the user wants to add a heading block with another level, they must type in `/heading` and then manually change the level by selecting one in the toolbar.

## What is your proposed solution?
It should be possible to type in `/h1`, `/h2`, `/h3` as a slash command to add a Heading block with the correct heading level.
![Image](https://github.com/user-attachments/assets/0149d099-7464-4293-95e6-4b8a5022d891)

**Comment by Mamaduka** [comment] 2024-11-13 11:56
Closing as duplicate of #50258 and #32472.

**Closed as not planned by Mamaduka** 2024-11-13 11:56 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Block] Heading
