### ISSUE TITLE
Can't add blocks near bottom of browser window

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6819] opened 2018-05-18 10:01 UTC
**Describe the bug**
I've added Gutenberg to a new site to test it out. I've added a few images and a paragraph block. The paragraph block is now sitting at the very bottom of the browser window. I can't scroll down any further in the browser, and the block inserter doesn't display after the block so it's stopping me from adding any further blocks to my page. If I hit  tab whilst in the last Paragraph block, the cursor simply goes to the sidebar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new page
2. Add blocks to page until it hits the bottom of the browser window

**Expected behaviour**
The blocks shouldn't sit so close to the bottom of the browser window that It prevents me from adding more blocks

**Screenshots**
![screenshot_660](https://user-images.githubusercontent.com/2078245/40228751-7e2bf71c-5ad5-11e8-8fdc-3a53bd112c10.png)

_macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)
WordPress 4.9.6
Gutenberg 2.8.0_

**Comment by kjellr** [comment] 2018-08-09 17:01
I was just testing this, and it looks like this may just be a duplicate of #7006. It only happens when the last block on your page is a paragraph block.

For all other blocks, I see the trailing/appending inserter at the bottom:

<img width="629" alt="screen shot 2018-08-09 at 12 56 49 pm" src="https://user-images.githubusercontent.com/1202812/43913672-b58d0dba-9bd3-11e8-8596-a10d816e8194.png">

> The blocks shouldn't sit so close to the bottom of the browser window that It prevents me from adding more blocks

This part also reminds me a bit of https://github.com/WordPress/gutenberg/issues/5580.

**Comment by maddisondesigns** [comment] 2018-08-10 02:48
@kjellr I don't think I was aware that Gutenberg removed the Block Inserter on purpose from below Paragraph blocks, when I created this, so yeah, it could be called a duplicate of #7006.

Problem is though is that #7006 has now been closed, and removing the Block Inserter from below Paragraph blocks is a ridiculous decision that makes the interface inconsistent.

**Comment by kjellr** [comment] 2018-08-10 16:48
Ok, thanks @maddisondesigns — I'm going to close this one as a duplicate in that case.

There are still some fairly recent comments in #7006 (as well as #7271) around the decision to remove the inserter from below paragraph blocks, so we can continue do discuss that issue there.

**Closed by kjellr** 2018-08-10 16:48 UTC
Labels: Needs Design Feedback
