### ISSUE TITLE
Nested Blocks Feature

### ISSUE THREAD

**Issue by prasidhda** [WordPress/gutenberg#4227] opened 2018-01-02 10:41 UTC
Will there be nested behaviors of the block supported ? 
Example: We add the "columns" block and we want to add different blocks to the each column block not just text or image.

**Comment by youknowriad** [comment] 2018-01-02 11:06
Yes, nested blocks are in the works see #3745 

This is a duplicate of #428

**Closed by youknowriad** 2018-01-02 11:06 UTC
