### ISSUE TITLE
Error when build Gutenberg

### ISSUE THREAD

**Issue by truongwp** [WordPress/gutenberg#3547] opened 2017-11-18 04:39 UTC
I have just cloned Gutenberg from master branch. I run `npm install` then `npm run build`. It shows the below error:

![selection_007](https://user-images.githubusercontent.com/19748318/32976934-23389482-cc55-11e7-9bdc-8b47b2d85ee8.png)

**Comment by youknowriad** [comment] 2017-11-20 08:23
I can't reproduce locally. Which node version are you using? The last LTS version is the recommended version for Gutenberg.

**Comment by norewp** [comment] 2017-11-22 17:15
No issues with the install and build here!

**Comment by youknowriad** [comment] 2017-12-28 12:13
Closing, feel free to reopen if you still can't build the plugin

**Closed** 2017-12-28 12:12 UTC
Labels: [Status] Needs More Info
