### ISSUE TITLE
TRY: Hooks - make the namespace parameter optional

### ISSUE THREAD

**Issue by ntwb** [WordPress/gutenberg#7816] opened 2018-07-09 13:10 UTC
@adamsilverstein commented on [Tue Apr 24 2018](https://github.com/WordPress/packages/pull/113)

---

@codecov[bot] commented on [Tue Apr 24 2018](https://github.com/WordPress/packages/pull/113#issuecomment-383933842)

# [Codecov](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=h1) Report
> Merging [#113](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=desc) into [master](https://codecov.io/gh/WordPress/packages/commit/21f3ceae08e345b6de213165331278c568a83cc1?src=pr&el=desc) will **increase** coverage by `0.18%`.
> The diff coverage is `54.54%`.

[![Impacted file tree graph](https://codecov.io/gh/WordPress/packages/pull/113/graphs/tree.svg?src=pr&width=650&token=9Zw9xmxPWW&height=150)](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #113      +/-   ##
==========================================
+ Coverage   64.07%   64.26%   +0.18%     
==========================================
  Files          42       42              
  Lines         604      624      +20     
  Branches      118      123       +5     
==========================================
+ Hits          387      401      +14     
- Misses        175      180       +5     
- Partials       42       43       +1
```

| [Impacted Files](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [packages/hooks/src/createRemoveHook.js](https://codecov.io/gh/WordPress/packages/pull/113/diff?src=pr&el=tree#diff-cGFja2FnZXMvaG9va3Mvc3JjL2NyZWF0ZVJlbW92ZUhvb2suanM=) | `95.83% <100%> (+0.37%)` | :arrow_up: |
| [packages/hooks/src/createAddHook.js](https://codecov.io/gh/WordPress/packages/pull/113/diff?src=pr&el=tree#diff-cGFja2FnZXMvaG9va3Mvc3JjL2NyZWF0ZUFkZEhvb2suanM=) | `90% <40%> (-10%)` | :arrow_down: |
| [packages/hooks/src/createHasHook.js](https://codecov.io/gh/WordPress/packages/pull/113/diff?src=pr&el=tree#diff-cGFja2FnZXMvaG9va3Mvc3JjL2NyZWF0ZUhhc0hvb2suanM=) | `60% <50%> (-40%)` | :arrow_down: |
| [packages/i18n/src/index.js](https://codecov.io/gh/WordPress/packages/pull/113/diff?src=pr&el=tree#diff-cGFja2FnZXMvaTE4bi9zcmMvaW5kZXguanM=) | `93.54% <0%> (-1.46%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=footer). Last update [21f3cea...596bf12](https://codecov.io/gh/WordPress/packages/pull/113?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by youknowriad** [comment] 2019-01-26 15:48
Seems like a duplicate of #7816

**Closed by youknowriad** 2019-01-26 15:48 UTC
Labels: [Package] Hooks
