### ISSUE TITLE
Can't cut/paste multiple paragraphs

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#8280] opened 2018-07-30 08:04 UTC
Perhaps this has already been reported but I couldn't find a ticket so creating a new one.

1. Create a new post and add 3-4 paragraphs
2. Try to select 2+1/2 paragraphs
3. Cut them
4. Paste them somewhere else.

The fact that G. treats paragraphs as blocks adds a lot of complexity to a simple task and unfortunately that leads to unexpected results. Sometimes not all text is properly deleted/cut, sometimes content is not pasted exactly where it should, other times it gets deleted correctly, pasted on the right place, but content still gets messed-up, empty blocks get left behind etc.
The behavior doesn't seem to be consistent on my end.

OSX (10.13.6), Chrome 68, Gutenberg 3.3.0

**Comment by aristath** [comment] 2018-08-31 11:29
I don't know when this changed, but right now it's not even possible to select 2½ paragraphs.
If you try to select 2½ paragraphs of text, 3 blocks get selected, making it harder to do tasks that are ridiculously easy in any other editor.

**Comment by brandonpayton** [comment] 2018-09-26 07:05
Tested and confirmed this is an issue.

**Comment by iseulde** [comment] 2018-11-27 08:33
@aristath @brandonpayton How do I reproduce? It's never been possible to select two and a half blocks.

**Comment by youknowriad** [comment] 2018-11-27 08:37
Yes, this is a design decision made a long time ago. There were tradeoffs in both approaches we had to take and this is the tradeoff of having multiple content editables. I'm closing this as won't fix.

Would be good to find the context of these discussions and link here though.

**Closed by youknowriad** 2018-11-27 08:37 UTC
Labels: Priority High, [Component] Multi-Select, [Type] Bug

**Comment by supernovia** [comment] 2020-09-18 01:24
Just noting I see complaints about this and I personally find it frustrating still. If I'm using WordPress to write, sometimes I'll want to cut and paste sections here or there, but I can't do it without selecting entire blocks.

This is not a normal editing experience.

The fix seems to be to use something else for writing, then paste into WordPress for formatting. I don't think that's our intention.
