### ISSUE TITLE
Text is deleted when undoing a hard break inserted into a heading

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11108] opened 2018-10-26 11:48 UTC
Typing a hard return (Enter) in the middle of a heading, then using command+z to undo deletes everything that appeared after the line break:

![2018-10-26 12 41 18](https://user-images.githubusercontent.com/376315/47564308-7d578700-d91c-11e8-9098-38ecb16d5f46.gif)

Typing command+z a second time brings the text back.

Using the backspace key instead of command+z undos the line break in the way I'd expect.

I would expect that typing command-z at this stage would just undo the line break I'd inserted, rather than removing the second paragraph entirely. I'm not certain if this is a bug or expected behaviour—I suspect on a technical level, it's undoing the "create new block" first and then the "break heading", but from a ux perspective, it feels unexpected.

## To reproduce:

1. Create a heading.
2. Type a hard return (enter) in the middle of that heading, breaking the heading into a heading and a paragraph.
3. Type `command+z`. 
4. The paragraph of text disappears. 
5. Type `command+z` again to bring the deleted text back.

**Comment by carladoria** [comment] 2018-10-26 16:55
I was able to reproduce this. It seems to only happen with headings. With text blocks, using command+z will revert the action of the broken line (2 blocks created) without deleting the text.

**Comment by mrwweb** [comment] 2018-10-29 20:32
I just tested this behavior in a list and found something very similar. In that case it deleted _both_ list items:

![list-line-break-undo-bug](https://user-images.githubusercontent.com/1238696/47678409-fbb36380-db7e-11e8-9dd5-a84c31e8515f.gif)

This feels related-ish to #11165.

Win 10, Firefox 63, WP 5.0-beta1-43832

**Comment by earnjam** [comment] 2018-10-30 15:03
Paragraph duplicates the portion moved on the first undo, then removes the new block on the 2nd undo. 

This gif compares header and paragraph blocks doing following keyboard steps:
1. `return`
2. `cmd` + `z`
3. `cmd` + `z`

![return-undo](https://user-images.githubusercontent.com/4267290/47727628-2101a980-dc33-11e8-946d-5729f0572012.gif)

I'm using OS X, Chrome 70, WP 4.9.8 and latest from Gutenberg `master`

**Comment by earnjam** [comment] 2018-10-30 15:12
Related: #8882

List block seems to restore correctly with a single Undo (likely because the return doesn't create a new block), however the cursor gets placed at the end of the line after an undo. 

![cursor-move-undo](https://user-images.githubusercontent.com/4267290/47728409-acc80580-dc34-11e8-9b9b-2c8e419eddd5.gif)

**Comment by iseulde** [comment] 2018-11-27 08:59
Duplicate of #8882.

**Closed by iseulde** 2018-11-27 08:59 UTC
Labels: Needs Testing, [Block] Heading, [Type] Bug
