### ISSUE TITLE
The "Categories & Tags" panel title should reflect the actual taxonomy types

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#4934] opened 2018-02-07 15:26 UTC
In the classic editor, the "categories" and "tags" meta boxes titles change depending on the actual type of taxonoomy used. With custom taxonomies, the meta boxes use the taxonomy `name` label. Instead, Gutenberg always uses a hardcoded string `Categories & Tags`:

<img width="700" alt="screen shot 2018-02-07 at 15 03 02" src="https://user-images.githubusercontent.com/1682452/35923821-9c1a8f20-0c21-11e8-91f0-31aab9e65da7.png">

This is an issue in the UI that should probably be improved: as a user, I wouldn't have a clue where to find my project type, or product type, or download type, etc., and I probably wouldn't look under something named `Categories & Tags`.

Aside: there are other labels the UI should use, for example the "add new", "parent", "choose", etc.

**Comment by youknowriad** [comment] 2018-02-07 15:59
duplicate of #4599

**Closed by youknowriad** 2018-02-07 15:59 UTC
