### ISSUE TITLE
Plugins Blocking Editor

### ISSUE THREAD

**Issue by jralph3** [WordPress/gutenberg#12388] opened 2018-11-28 16:46 UTC
I have two plugins that appear in the editor, usually at the bottom of the page. They're now anchored in the editor at the location where they originally appeared.

1. You'll need a plugin that would appear at the bottom of the editor, the Yoast SEO plugin is one of the two that I'm currently experiencing this problem with.
2. Open the page and/or post editor. The plugin will be fully open at the bottom of the screen when you first open the editor. Try scrolling, you can't scroll past the last block on your screen in the editor.
3. Minimize the plugin and you can now scroll through all the blocks in the editor. 
4. Normally the plugin would be anchored at the bottom of the screen but it's now anchored towards the top of the post, in the location it started in.

**Expected behavior**
The plugins should stay anchored at the bottom of the page/post and you should be able to scroll through all the blocks in the editor when the plugins are opened.

**Screenshots**
[Screenshot showing that I can't scroll past the image blog in the editor.](http://jessicaralph.com/images/cant-scroll-past-image.jpg)

![cant-scroll-past-image](https://user-images.githubusercontent.com/1119271/49167546-d1c29d80-f2f2-11e8-929c-8165e2a03f84.jpg)

[Screenshot showing the plugins minimized and now anchored over the image, but I can now scroll past that image.
](http://jessicaralph.com/images/plugins-anchored.jpg)
![plugins-anchored](https://user-images.githubusercontent.com/1119271/49167553-d8e9ab80-f2f2-11e8-9a8d-ffe06a618ef1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version 4.5.1

**Comment by designsimply** [comment] 2018-11-28 18:16
Closing as a duplicate of #11378 and noting that there was a lot of testing in that issue resulting in a finding that the issue can be reproduced by having a plugin or theme that throws an error.

I can make a note in #11378 that this has come up again in a new issue, however, it would be super helpful to have a bit more information. If you are able to troubleshoot further, it would be helpful to know:

What version of WordPress are you using?

What theme are you using?

If you deactivate all plugins and only re-activate Yoast SEO 9.2.1 and Gutenberg 4.5.1, does the problem persist? If not, can you re-activate each plugin one at a time until the problem reappears and note which one is the source of the conflict in your case?

Note: I tested with WordPress 4.9.8 and Gutenberg 4.5.1 and Yoast SEO 9.2.1 using Chrome 70 on Windows 10 and was unable to replicate the problem in my own testing ([screenshot](https://user-images.githubusercontent.com/1119271/49172694-f91f6780-f2fe-11e8-91cb-a5f8c29bcf80.jpg)).

**Closed by designsimply** 2018-11-28 18:16 UTC
Labels: Needs Testing, [Component] Meta Boxes, [Status] Duplicate, [Type] Bug, [Type] Plugin / Theme Interoperability
