### ISSUE TITLE
Image block: Duplicate copies of media files created in library

### ISSUE THREAD

**Issue by KokkieH** [WordPress/gutenberg#25805] opened 2020-10-03 07:51 UTC
**Describe the bug**
Changing alignment of an image block while the image is still uploading, causes duplicate copies of the image to be created in the media library. This does not happen if one waits for the upload to complete before changing alignment settings.

**To reproduce**
1. Create a new post/page
2. Drag an image file from your computer into the editor
3. While the image is still uploading, change the alignment for the image block
4. Exit the editor and view the media library
5. There will be two copies of the image, one with `-1` appended to the file name.

**Expected behavior**
For just one copy of the image file I just uploaded to appear in the library

**Screenshots**
![Screen Capture on 2020-10-03 at 09-45-17](https://user-images.githubusercontent.com/11873759/94986369-89174380-055e-11eb-88b0-28916a5b0ef5.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Happens with both the default editor, and with Gutenberg 9.1.0

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser Firefox
 - Version 81.0

**Additional context**
Discovered and reported by a WordPress.com user in https://wordpress.com/forums/topic/wordpress-uploads-double-images/

**Comment by KokkieH** [comment] 2020-10-03 07:54
Additional detail: Once the upload completes, it's the duplicate `-1` version of the image that's actually added to the post. So it appears that changing the alignment causes the block to think a second image is being uploaded, and the second image is the one that's used.

**Comment by tellthemachines** [comment] 2020-11-03 05:10
I can reproduce this in both WP 5.5.2 and in Gutenberg 9.2.

**Comment by paaljoachim** [comment] 2021-02-04 18:32
I have also seen this bug multiple times when uploading one image. For client sites as well as my own local dev test sites running WP 5.6.1. Gutenberg plugin 9.8.4. Theme happen to be this time TT1. OSX 10.15.7 and Chrome.

Here is an example.

![Double-upload-Image-block](https://user-images.githubusercontent.com/5323259/106938553-6caf3180-671f-11eb-8c6b-9083e330cb44.gif)

**Comment by paaljoachim** [comment] 2021-02-05 17:36
The error is still in place also after testing WP 5.7 and no Gutenberg plugin activated. Using the theme Twenty Twenty One.

**Comment by paaljoachim** [comment] 2021-02-07 13:17
This issue is associated/a variant:
https://github.com/WordPress/gutenberg/issues/28512
(It will probably be fixed when this issue has been fixed.)

**Comment by paaljoachim** [comment] 2021-02-16 09:12
Retesting
Using WordPress 5.7 beta 2.
Theme: Twenty Twenty One.
Active plugins: WordPress Beta Tester.

Made a new page. Saved as draft.
Drag and drop an image directly into Gutenberg. Works
Adding Image block and dragging and dropping image directly on the Image block placeholder. Works
Adding Image block. Clicking the Media Library button. Dragging and dropping image into Media Library. Worked once and then did not work the next time.

Made a new page. Saved as draft. Clicked Save draft button once.
Adding Image block. Clicking the Media Library button. Dragging and dropping image into Media Library. 
Screen went white. Clicked x. Added image. Clicked replace. Noticed the duplicate image.

Activated Gutenberg plugin 10.0 RC.
I was again able to reproduce the error.

---

Using WordPress 5.6.1
Theme: Twenty Twenty One.
Ative plugins: Gutenberg 10.0 RC

New page.
Added title
Did not save draft.
Added Image block. Clicked Media Library. Noticed the white screen. Clicked X. It went back to Gutenberg and included the image. I clicked Replace and noticed the duplicate image in the Media Library.

Deactivated Gutenberg plugin.

New page.
Added title.
Clicked Save draft
Added Image block.
Click Media Library
Error with white screen. Click X to exit. See image in the Image block. Click Replace and Media library and notice the duplicate image.

---------

It seems like the error is seen when the first block added is the Image block. 
If one adds for instance a paragraph block/adds some words and then adds the Image block then it seems like the error is not seen

**Comment by paaljoachim** [comment] 2021-02-17 00:38
Testing

**WordPress version: 5.5.3
Theme: Twenty Twenty One.
Active plugins: none**

New page. (also tested new post)
Add title.
Click Save draft. (Updating failed. The response is not a valid JSON response. -Error message-)
Add Image block.
Click Media Library. 
Drag and drop image to the Select or Upload Media. 
Click Select.
Image added to the Image block.
Only the JSON error seen.

-----------

**WordPress version 5.5.3
Active plugins: Gutenberg 9.9.2**

New page. (also tested new post)
Add title.
Click Save draft (JSON save error showed up - autosave kicked in).
Add Image block.
Click Media Library. 
Drag and drop image to the Select or Upload Media. 
Click Select.
Image added to the Image block.
The image is seen but another Image block was added below it.

---------

**WordPress version 5.5.3
Active plugins: Gutenberg 9.9.1**

New page. (also tested new post)
Add title.
Click Save draft (JSON save error showed up - autosave kicked in).
Add Image block.
Click Media Library. 
Drag and drop image to the Select or Upload Media. (White screen is seen)
Click Select.
Image added to the Image block.(JSON error is seen inside the Image block.)

**Comment by ajlende** [comment] 2021-02-22 23:17
I'm seeing two different `POST` requests both which seem to be uploading the image.

<p align="center"><img width="741" alt="requests" src="https://user-images.githubusercontent.com/5129775/108780082-fdea1a80-750b-11eb-856c-1d1fa3e5cf58.png"></p>


<details>
<summary>Request Details as cURL</summary>
<p>

```
curl 'https://wp.local/wp-json/wp/v2/media?_locale=user' \
	-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:85.0) Gecko/20100101 Firefox/85.0' \
	-H 'Accept: application/json, */*;q=0.1' \
	-H 'Accept-Language: en-US,en;q=0.5' \
	--compressed \
	-H 'Referer: https://wp.local/wp-admin/post.php?post=284&action=edit' \
	-H 'X-WP-Nonce: 4543813c6d' \
	-H 'Content-Type: multipart/form-data; boundary=---------------------------20868862012189597302960151447' \
	-H 'Origin: https://wp.local' \
	-H 'DNT: 1' \
	-H 'Connection: keep-alive' \
	-H 'Cookie: wp-settings-1=libraryContent%3Dbrowse; wp-settings-time-1=1609278857; wordpress_test_cookie=WP+Cookie+check; XDEBUG_SESSION=XDEBUG_ECLIPSE; wordpress_logged_in_c50756dc7d79ac0ea07f5b03da389524=admin%7C1614202629%7CsZnpS3bV8xnc7ngOexJleduQTNOps0J3UNVtn3Cit3t%7C705cb0a63ff762b04cac612f5cb164c811d13c9751e7de07c0817eb7894d7530' \
	-H 'Sec-GPC: 1' \
	-H 'Pragma: no-cache' \
	-H 'Cache-Control: no-cache' --data-binary $'-----------------------------20868862012189597302960151447\r\nContent-Disposition: form-data; name="file"; filename="background_hsv_175.png"\r\nContent-Type: image/png\r\n\r\n-----------------------------20868862012189597302960151447\r\nContent-Disposition: form-data; name="post"\r\n\r\n284\r\n-----------------------------20868862012189597302960151447--\r\n'
```

```
curl 'https://wp.local/wp-admin/async-upload.php' \
	-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:85.0) Gecko/20100101 Firefox/85.0' \
	-H 'Accept: */*' \
	-H 'Accept-Language: en-US,en;q=0.5' \
	--compressed \
	-H 'Referer: https://wp.local/wp-admin/post.php?post=284&action=edit' \
	-H 'Content-Type: multipart/form-data; boundary=---------------------------14131572508514055401472863916' \
	-H 'Origin: https://wp.local' \
	-H 'DNT: 1' \
	-H 'Connection: keep-alive' \
	-H 'Cookie: wordpress_sec_c50756dc7d79ac0ea07f5b03da389524=admin%7C1614202629%7CsZnpS3bV8xnc7ngOexJleduQTNOps0J3UNVtn3Cit3t%7Cd51dab5d22fb6d6996e1023769359ed61a3090c0a3e07541524c55ef9eb7889f; wp-settings-1=libraryContent%3Dbrowse; wp-settings-time-1=1609278857; wordpress_test_cookie=WP+Cookie+check; XDEBUG_SESSION=XDEBUG_ECLIPSE; wordpress_logged_in_c50756dc7d79ac0ea07f5b03da389524=admin%7C1614202629%7CsZnpS3bV8xnc7ngOexJleduQTNOps0J3UNVtn3Cit3t%7C705cb0a63ff762b04cac612f5cb164c811d13c9751e7de07c0817eb7894d7530' \
	-H 'Sec-GPC: 1' \
	-H 'Pragma: no-cache' \
	-H 'Cache-Control: no-cache' --data-binary $'-----------------------------14131572508514055401472863916\r\nContent-Disposition: form-data; name="name"\r\n\r\nbackground_hsv_175.png\r\n-----------------------------14131572508514055401472863916\r\nContent-Disposition: form-data; name="action"\r\n\r\nupload-attachment\r\n-----------------------------14131572508514055401472863916\r\nContent-Disposition: form-data; name="_wpnonce"\r\n\r\n121dc23363\r\n-----------------------------14131572508514055401472863916\r\nContent-Disposition: form-data; name="post_id"\r\n\r\n284\r\n-----------------------------14131572508514055401472863916\r\nContent-Disposition: form-data; name="async-upload"; filename="background_hsv_175.png"\r\nContent-Type: image/png\r\n\r\n-----------------------------14131572508514055401472863916--\r\n'
```

</p>
</details>

The first one is coming from the drop listener in the image block in the editor. I haven't seen moxie.js before, but I'm assuming it's the JS that's used by the media library for image upload? If that's the case, the image block drop listener _and_ the media library drop listener are probably both active, causing the duplicated image.

**Comment by paaljoachim** [comment] 2021-02-23 08:06
Good find @ajlende Alex!

**Comment by ockham** [comment] 2021-02-24 19:27
> The first one is coming from the drop listener in the image block in the editor. I haven't seen moxie.js before, but I'm assuming it's the JS that's used by the media library for image upload? 

Seems like: See e.g. https://github.com/WordPress/wordpress-develop/blob/f2bd8d048116e40892df4d6429dad99ede2e4c12/src/js/_enqueues/vendor/plupload/moxie.js or  https://github.com/WordPress/wordpress-develop/blob/69751046d6de1df92919d19f597f1f887fcc834a/src/wp-includes/script-loader.php#L895

> If that's the case, the image block drop listener _and_ the media library drop listener are probably both active, causing the duplicated image.

Sounds plausible :+1:

**Comment by ockham** [comment] 2021-03-03 13:08
Testing this in a local Gutenberg dev environment is a bit tricky, since the default upload size limit seems to be around 1MB (related issue: https://github.com/WordPress/gutenberg/issues/29430); and uploading 1MB happens rather quickly when done locally, so there isn't a lot of time to change the block alignment.

As a workaround, I enable Chrome's device toolbar (`Ctrl+shift+M`), and pick 'Low-end mobile tier' from the connection speed dropdown.

**Comment by ockham** [comment] 2021-03-03 16:00
I've done a bit of manual testing now, and I seem to be getting different results:

I'm getting the error (i.e. duplicated image) when trying this with both WP 5.6 and 5.6.1 (with no Gutenberg plugin active). (I'm using the "WP Downgrade" plugin to downgrade a WP test install to those earlier versions).

Can someone confirm?

**Comment by ockham** [comment] 2021-03-03 16:16
> I've done a bit of manual testing now, and I seem to be getting different results:
> 
> I'm getting the error (i.e. duplicated image) when trying this with both WP 5.6 and 5.6.1 (with no Gutenberg plugin active). (I'm using the "WP Downgrade" plugin to downgrade a WP test install to those earlier versions).

I just noticed that that is confirm with the information given when this issue was originally filed:

> **Editor version (please complete the following information):**
> - WordPress version: 5.5.1
> - Happens with both the default editor, and with Gutenberg 9.1.0

**Comment by ockham** [comment] 2021-03-03 16:25
I can even repro in WP 5.4.4.

I'll stop going back further for now (since I need to switch focus to something else); it seems like this bug has been around for a couple of WordPress versions. (IMO, this means that we don't need to stress about getting a fix into 5.7, but can take more time to track down when the bug was first introduced.)

**Comment by paaljoachim** [comment] 2021-03-15 17:01
Retesting.

WordPress 5.7.
No plugins activated.

New page.
Added title.
Added image block.

Alternative 1.
Click Upload.
Uploaded image. I clicked replace to see if a duplicate was added to the media library. 
Worked fine.
Deleted Image block.

Alternative 2.
Click Media Library.
Dragged and dropped image into Media library.
Then added it to the Image block.
Worked fine.
Deleted Image block.

-------

Next test.

WordPress 5.7
I activated Gutenberg plugin version 10.1.1
Twenty Twenty One.

New page.
Added title.
Added image block.

Alternative 1.
Click Upload.
Uploaded image. I clicked replace to see if a duplicate was added to the media library. 
Worked fine.
Deleted Image block.

Alternative 2.
Click Media Library.
Dragged and dropped image into Media library.
Then added it to the Image block.
Worked fine.

Both of the above worked fine.
I have though experienced this issue on a live site.

Alternative 3.
Below the first image block.
Added a new Image block.
Click Media Library.
Dragged and dropped image into Media library. -> White screen is seen and I have to click the X to get out of the white screen. 
Image seen in the Image block. 
Clicked Replace to go to the Media Library.
Noticed two images.

---------

The problem is not consistent. The following shows adding one image with noe issue and then the next Image block does not show the white screen but it shows the duplicate directly in the Gutenberg layout and in the Media Library. This is one tricky issue.


https://user-images.githubusercontent.com/5323259/111191525-7185c180-85b8-11eb-92ba-001ede052d31.mp4

@ellatrix and @ntsekouras

**Comment by ellatrix** [comment] 2021-03-16 10:50
Does this happen for drag and drop? Wasn't this fixed in #29567?

**Comment by paaljoachim** [comment] 2021-03-16 11:33
I am testing again. WP 5.7. Gutenberg plugin 10.1.1 and Twenty Twenty One.

Dragging and dropping an image into Gutenberg seems to work fine.

https://user-images.githubusercontent.com/5323259/111300703-aabe4000-8651-11eb-8a3b-8127cb14ccd7.mp4

---

I went ahead and made a longer video (2min 48seconds) to have more time to show what is going on. This is in relation to opening the Media Library and dragging and dropping an image into the Media Library.
https://www.youtube.com/watch?v=Le_OY3kkBc4

**Comment by paaljoachim** [comment] 2021-03-27 08:41
Retesting on a client site using a 
custom theme, 
WP 5.7 and 
Gutenberg plugin 10.1.1.
(There are also various other plugins activated.)

Existing post.
Went to upload a featured image.
Noticed the white screen error.
Opened the Console screen and uploaded another image. This is the error I see:
(Shows the moxie.min.js error as mentioned above by @ajlende Alex.)

Uncaught TypeError: Cannot read property 'attachments' of undefined
    at Object.onDone (app.js?ver=4.5:1)
    at Object.<anonymous> (app.js?ver=4.5:1)
    at c (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2)
    at l (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2)
    at XMLHttpRequest.<anonymous> (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2)
onDone @ app.js?ver=4.5:1
(anonymous) @ app.js?ver=4.5:1
c @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
fireWith @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
l @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
(anonymous) @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
load (async)
send @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:2
s.ajax.s.ajax @ load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.7:5
getFolders @ app.js?ver=4.5:1
reloadFolders @ app.js?ver=4.5:1
(anonymous) @ app.js?ver=4.5:29
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
r @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
setTimeout (async)
v @ plupload.min.js?ver=2.1.9:1
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
s.status.F.UPLOADING.r.state.F.STOPPED.p.onload @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
trigger @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
load (async)
send @ moxie.min.js?ver=1.3.5:1
exec @ moxie.min.js?ver=1.3.5:1
shimExec @ moxie.min.js?ver=1.3.5:1
exec @ moxie.min.js?ver=1.3.5:1
r @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
send @ moxie.min.js?ver=1.3.5:1
g @ plupload.min.js?ver=2.1.9:1
b @ plupload.min.js?ver=2.1.9:1
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
r @ plupload.min.js?ver=2.1.9:1
start @ plupload.min.js?ver=2.1.9:1
(anonymous) @ wp-plupload.min.js?ver=5.7:1
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
setTimeout (async)
e @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ app.js?ver=4.5:29
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
addFile @ plupload.min.js?ver=2.1.9:1
e.ondrop @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
trigger @ moxie.min.js?ver=1.3.5:1
i @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1

![Screen Shot 2021-03-27 at 09 31 17](https://user-images.githubusercontent.com/5323259/112715327-d78b1680-8edf-11eb-89e8-01b53f3b67b0.png)



https://user-images.githubusercontent.com/5323259/112715561-284f3f00-8ee1-11eb-8363-aa18053ead35.mp4



Result is the duplication of the image in the media library.

**Comment by paaljoachim** [comment] 2021-03-27 08:53
Retesting on a client site using a
custom theme,
WP 5.7 and 
**updated Gutenberg plugin to 10.2.1** I also cleared the cache this time. I had not done so for the above test.
(There are also various other plugins activated.)

 Image uploaded with no error seen. It looks like a fix has been added to Gutenberg plugin 10.2. or 10.2.1.

@ockham @talldan @ellatrix

**Comment by Mamaduka** [comment] 2021-04-15 05:31
I was able to reproduce the issue using WP 5.7.1/Gutenberg 10.4.

Steps:
1. Throttle network to 3G via DevTools.
2. Drag the image to the editor.
3. **While the image is uploading, change alignment.** 
4. You should see duplicated images in the media library.

I can also see a second request in the Network tab.

<img width="1280" alt="image-block-duplicated-images" src="https://user-images.githubusercontent.com/240569/114818657-33550b00-9dcd-11eb-9125-bac4abc678cc.png">

**Comment by Mamaduka** [comment] 2021-04-15 07:41
I want to work on this issue. Should I assign it to myself?

**Comment by paaljoachim** [comment] 2021-04-15 07:49
Thank you, George!

**Comment by Mamaduka** [comment] 2021-04-15 11:34
I think the problem is with the "Upload a temporary image on mount" [effect](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/edit.js#L228). Changing alignment remounts component and triggers the second upload.

I'm not sure if there's a way to cancel the previous upload via the `useEffect` cleanp function.

The easiest solution here will be to hide Block Controls while uploading image. Uploads are usually fast.

Happy to work on PR.

/cc @ellatrix

**Comment by Mamaduka** [comment] 2021-04-16 07:44
I went ahead and created PR using the second option.

**Closed** 2021-04-22 11:42 UTC
Labels: [Block] Image, [Priority] High, [Status] In Progress, [Type] Bug

**Comment by paaljoachim** [comment] 2021-04-22 12:05
Yahhh!! It sure felt good to get this issue closed. Thank you again George!
