### ISSUE TITLE
Parent and Template Options missing from Page Attributes

### ISSUE THREAD

**Issue by landbryo** [WordPress/gutenberg#4132] opened 2017-12-21 21:39 UTC
The Parent and Template Options are missing from the Page Attributes. All that is visible is Order.

**Comment by carlhancock** [comment] 2017-12-25 19:55
Is this something that is going to be addressed? Pages, the post type Pages, are by their nature hierarchical so you’d need some sort of control over setting the parent or controlling that hierarchy. And page templates from a theme standpoint are very widely used. Can one of the Gutenberg leads comment on these 2 features and how they’ll be addressed with Gutenberg?

**Comment by landbryo** [comment] 2017-12-25 20:40
I agree. This should be addressed, especially since Gutenberg is going to be included in core. A current workaround is to switch to the standard editor to set Page and Template Options.

**Comment by greatislander** [comment] 2017-12-26 02:06
https://github.com/WordPress/gutenberg/issues/991#issuecomment-352379773

**Comment by mtias** [comment] 2017-12-26 17:03
Closing as duplicate of #991. The main blocker has been REST API support for it. If anyone would like to help, that's a good place to start looking at.

**Comment by joehoyle** [comment] 2018-01-02 19:23
#991 seems to just cover page templates, not really any mention of post parent. I'm also not sure why any chances are needed to add the page parent field?

**Comment by aduth** [comment] 2018-01-02 20:33
>I'm also not sure why any chances are needed to add the page parent field?

Yes, I expect this could be implemented without additional support from the REST API.

**Comment by jorgefilipecosta** [comment] 2018-01-02 21:20
Hi @joehoyle thank you for reporting this missing features. The PR https://github.com/WordPress/gutenberg/pull/4175 that adds post parent was just merged, so I will close this issue for now and leave https://github.com/WordPress/gutenberg/issues/991 open.

**Closed by jorgefilipecosta** 2018-01-02 21:20 UTC

**Comment by joehoyle** [comment] 2018-01-02 22:47
Great stuff!

**Comment by Bruce-Bilbo-Kent** [comment] 2018-08-18 21:38
After 24 hours I deactivated Gutenberg Editor and soon after removed it completely. However, any option to change the parent-child page hierarchy has disappeared along with Gutenberg. BTW I use the Elementor page-builder for most pages.
