### ISSUE TITLE
Top Toolbar: Expand tools outside of dropdown menu if your screen has extra space

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#27745] opened 2020-12-15 20:43 UTC
**Is your feature request related to a problem? Please describe.**
If you have a wide screen, there's a lot of unused room available in the top toolbar:

![gutenberg_space](https://user-images.githubusercontent.com/2846578/102270465-04e12500-3eec-11eb-8657-a79f603bfd4f.png)

**Describe the solution you'd like**
What if the tools hidden in the dropdown arrow menu were allowed to flow into the toolbar, when your screen has enough space?

Suggested by `@fahrenhe1t` on WordPress.org: https://wordpress.org/support/topic/sorry-its-not-finished/#post-13792906

**Comment by spawoz-work** [comment] 2021-01-19 06:41
That will be great

**Comment by mtias** [comment] 2021-07-14 10:23
Marking as duplicate of #16889.

**Closed by mtias** 2021-07-14 10:23 UTC
Labels: General Interface, [Type] Enhancement
