### ISSUE TITLE
Can't add blocks from block directory inside Group

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#24501] opened 2020-08-11 23:24 UTC
**Describe the bug**
I just downloaded WordPress 5.5, and was playing around with the new block directory. There is an issue when clicking on the Appender button in an InnerBlock, and then selecting "Browse All". This bug I think applies to all innerBlocks.

**To reproduce**
1. Add a new Post.
2. Click on the "+" sign. Add the "Group" block.
3. Click on the "+" sign inside the "Group" block.
4. Select "Browse All".
5. Select any block.

**Expected behavior**
The block should get added inside the "Group" block. But what happens is that the block get added outside the "Group" block. This completely kills the appender for all innerBlocks, especially if the innerBlock constrains which blocks can be added to it.

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? No Gutenberg plugin, just 5.5.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 84.0.4147.105 (64-bit)

**Comment by annezazu** [comment] 2020-08-14 23:31
@MichaelArestad this might be of interest to you!

**Comment by tomusborne** [comment] 2020-08-16 16:27
I'm seeing this as well - it definitely causes confusion when someone is trying to add a block inside of a parent block.

**Comment by ryelle** [comment] 2020-08-17 19:08
I can replicate this, but it's not just "block directory" blocks, the problem happens with installed blocks too.

**Comment by talldan** [comment] 2020-08-18 07:35
Closing as a duplicate of #24403

**Closed by talldan** 2020-08-18 07:35 UTC
Labels: [Feature] Inserter, [Feature] Nested / Inner Blocks, [Status] Duplicate, [Type] Bug
