### ISSUE TITLE
Can no longer drag n drop blocks reliably and block toolbars disappear

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#23863] opened 2020-07-10 08:39 UTC
**Describe the bug**
Just updated to Gutenberg 8.5 and can no longer drag n drop blocks reliably. When you click on a block you don't get any toolbar, drag handles, or even the Move up/down arrows.

I can consistently break it by dragging a block up the page, then hitting `esc` to undo the drag. From then on, Block Toolbars no longer display on any blocks, so you can't edit them, or drag them.

Here's a vid: https://share.getcloudapp.com/rRulDR4e

**To reproduce**
1. Open a page with multiple blocks
2. Click on a block and try to drag it to a new location
3. Before dropping the block, hit `esc`
4. Now try clicking on another block and the toolbars are broken and you can no longer edit the block or move it

**Expected behavior**
Moving blocks shouldn't be this difficult and inconsistent

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Browser: Firefox 78.0.1
- TwentySeventeen

**Comment by enriquesanchez** [comment] 2020-07-16 18:17
Hi @maddisondesigns 👋

I believe that what happened in your video is that when you clicked `ESC` you switched to 'Select' mode:

<img width="314" alt="Screen Shot 2020-07-16 at 13 12 00" src="https://user-images.githubusercontent.com/3276087/87706974-fee0ef80-c765-11ea-810b-8cfd7b87686e.png">

Currently, drag and drop is no supported in this mode, but if you were to click on the block label, the block's contents or hit `Enter` it should switch you back to 'Edit' mode, and you should be able to drag and drop again.

I agree that if someone's unfamiliar with these modes, this is an unexpected and confusing change.

**Comment by maddisondesigns** [comment] 2020-07-17 05:53
You're saying that by hitting `esc`, the editor is automatically changing it to the 'select' tool?? Why is it doing that? That's just horrible. Hitting `esc` should cancel the current action, not automatically change the editor into some other 'mode'. By doing this you're effectively making it impossible to cancel out of dragging a block. This is going to be incredibly frustrating for people editing their page. No-one is automatically going to assume that a different tool has been selected, because it literally makes no sense to do that, so everyone, like me, is just going to think that the editor has broken.

**Comment by draganescu** [comment] 2020-07-21 13:30
This sounds like a bug where ESC in drag and drop mode should cancel the drag but not change the mode.

**Comment by enriquesanchez** [comment] 2020-07-24 21:22
I tested again and it looks like hitting `ESC`does cancel the operation, but the "dropzone bar" stays visible, which makes it look like the operation is still active.

![2020-07-24 16-18-18 2020-07-24 16_20_19](https://user-images.githubusercontent.com/3276087/88436364-c4143280-cdc9-11ea-860d-6865d1ff8d2f.gif)

**Comment by talldan** [comment] 2021-03-03 01:58
I can't reproduce this any more, so closing.

**Closed by talldan** 2021-03-03 01:58 UTC
Labels: [Feature] Drag and Drop, [Package] Keyboard Shortcuts
