### ISSUE TITLE
Not possible to register style for media and text block

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#11612] opened 2018-11-08 10:15 UTC
**Describe the bug**
As soon as you register a style for the media and text block, the editor crashes when you attempt to change the block's style.

Here's the code I used:

```js
registerBlockStyle( 'core/media-text', {
	name: 'test',
	label: 'Test',
} );
```

**To Reproduce**
1. Register block style
2. Add new media & text block
3. Either click on styles panel in the block settings sidebar, or the style selector in the toolbar.
4. See error ("The editor has encountered an unexpected error…")

This is the error I'm getting:

```
TypeError: Cannot read property 'innerBlocks' of null
    at t.value (https://test.local/content/plugins/gutenberg/build/editor/index.js?ver=1541526670:50:141355)
    at jc (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (https://test.local/content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)
```

**Expected behavior**

I should be able to change the block style.

**Screenshots**

<img width="874" alt="screenshot 2018-11-08 at 11 14 08" src="https://user-images.githubusercontent.com/841956/48192225-77639c00-e347-11e8-8098-bc138c92ebaf.png">

**Desktop**

Chrome 70 on macOS

**Additional context**

Gutenberg 4.2 on WordPress 4.9.8

**Comment by jorgefilipecosta** [comment] 2018-11-08 13:38
Thank you for reporting this issue @swissspidy.

I'm able to reproduce this problem. In my tests, it happens in every block with innerBlocks.
```
registerBlockStyle( 'core/columns', {
	name: 'test',
	label: 'Test',
} );
````
Registering a style for the columns block also crashes the editor.

**Comment by youknowriad** [comment] 2018-11-12 11:19
Yes, let's close as a duplicate of #9897

**Closed by youknowriad** 2018-11-12 11:19 UTC
Labels: [Block] Media & Text, [Type] Bug
