### ISSUE TITLE
Gutenberg Plugin Issue 

### ISSUE THREAD

**Issue by nikitabhagat** [WordPress/gutenberg#33910] opened 2021-08-05 18:48 UTC
I have developed my site in Gutenberg editor plugin but when I made the site up on live hosting it is showing me fatal error 
Fatal error: Cannot declare class WP_Block_Template, because the name is already in use in /home/customer/www/antares.solutions/public_html/wp-content/plugins/gutenberg/lib/full-site-editing/class-wp-block-template.php on line 12

Could you please help me with this?
I need to activate the plugin now.

**Comment by glendaviesnz** [comment] 2021-08-06 03:54
Duplicate of https://github.com/WordPress/gutenberg/issues/33700

If running WP 5.8 you will need to update to the latest version of the Gutenberg plugin. See https://github.com/WordPress/gutenberg/issues/33700#issuecomment-887781372 for potential solution.

**Closed as completed by glendaviesnz** 2021-08-06 03:54 UTC
