### ISSUE TITLE
block media-text does not work on IE11

### ISSUE THREAD

**Issue by larrach** [WordPress/gutenberg#14517] opened 2019-03-19 16:39 UTC
**Describe the bug**
the display is not correct on IE11

**To Reproduce**
Use Ie11 and block media-text

**Expected behavior**
Same display that others browsers

**Comment by larrach** [comment] 2019-03-19 16:41
In wp-includes/css/dist/block-library/style.css

`.wp-block-media-text {
  display: -ms-grid;
  display: grid; }

.wp-block-media-text {
  -ms-grid-rows: auto;
  grid-template-rows: auto;
  -ms-flex-align: center;
  align-items: center;
  grid-template-areas: "media-text-media media-text-content";
  -ms-grid-columns: 50% 50%;
  grid-template-columns: 50% auto; }
  .wp-block-media-text.has-media-on-the-right {
    grid-template-areas: "media-text-content media-text-media";
    -ms-grid-columns: 50% 50%;
    grid-template-columns: auto 50%; }

.wp-block-media-text .wp-block-media-text__media {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: media-text-media;
  margin: 0; }
  .wp-block-media-text.has-media-on-the-right .wp-block-media-text__media{
  	-ms-grid-column: 2;}

.wp-block-media-text .wp-block-media-text__content {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  word-break: break-word;
  grid-area: media-text-content;
  padding: 0 8% 0 8%; 
  grid-column-algin: center;
  -ms-grid-row-align: center;
  grid-ro-align: center;}
  .wp-block-media-text.has-media-on-the-right .wp-block-media-text__content{
  	-ms-grid-column: 1;}

.wp-block-media-text > figure > img,
.wp-block-media-text > figure > video {
  max-width: unset;
  width: 100%;
  vertical-align: middle; }`

**Comment by ianbelanger79** [comment] 2019-03-22 18:37
Closing this issue as a duplicate of #11577

**Closed by ianbelanger79** 2019-03-22 18:37 UTC
Labels: Browser Issues, [Block] Media & Text
