### ISSUE TITLE
Full Width Nav Block submenus not aligned below menu item

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#31222] opened 2021-04-27 09:36 UTC
## Description
If I set my Nav block to full wide alignment then the submenus are positioned incorrectly. They appear to be missing the rule `top: 100%` which causes them to float about over the top of their parent nav item.

## Step-by-step reproduction instructions

1. Add Nav Block
2. Add some items with submenus.
3. Set Nav Block to "full wide" alignment.
4. Hover over nav items with submenus to trigger their display.
5. See bug.

## Expected behaviour
Submenu should align with bottom of parent nav item.

## Actual behaviour
Submenu was positioned on top of parent nav item.

## Screenshots or screen recording (optional)
![Screen Capture on 2021-04-27 at 10-34-35](https://user-images.githubusercontent.com/444434/116220094-41e3e080-a744-11eb-8c28-94f8b4afd92f.gif)

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by jasmussen** [comment] 2021-05-03 08:06
Thanks so much for ticketing this. I'd be very happy to fix this one, however I can't reproduce it anymore:

<img width="1477" alt="Screenshot 2021-05-03 at 10 04 41" src="https://user-images.githubusercontent.com/1204802/116853914-173bd100-abf7-11eb-8754-ec3c9eeb7ed6.png">

Is it possible this was fixed by #31195 or #31368?

**Comment by JustinyAhin** [comment] 2021-05-03 08:19
This seems to have been fixed by https://github.com/WordPress/gutenberg/commit/c1e4cfd5963271ae85edad2bf6f963746e60e7e8.

**Comment by JustinyAhin** [comment] 2021-05-03 08:20
> Is it possible this was fixed by #31195 or #31368?
Yeah, it was fixed in https://github.com/WordPress/gutenberg/pull/31368.

**Comment by jasmussen** [comment] 2021-05-03 08:22
Thank you Justin! I'm going to close this one then.

**Closed as completed by jasmussen** 2021-05-03 08:22 UTC
Labels: [Type] Bug, [Block] Navigation
