### ISSUE TITLE
Site Editor: block sibling inserter is positioned incorrectly

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#28885] opened 2021-02-09 15:37 UTC
We recently introduced an experiment for a less prominent sibling inserter in https://github.com/WordPress/gutenberg/pull/28550. It works fine in the post editor, but for some reason it's broken in the site editor. This makes it impossible to use it in horizontal case.

<img width="701" alt="Screenshot 2021-02-09 at 16 29 02" src="https://user-images.githubusercontent.com/1182160/107387194-e0bd5100-6af4-11eb-9038-4456ac8a2f67.png">
<img width="682" alt="Screenshot 2021-02-09 at 16 29 33" src="https://user-images.githubusercontent.com/1182160/107387200-e1ee7e00-6af4-11eb-851e-4e760122a8f7.png">

**Comment by vindl** [comment] 2021-02-09 15:49
There is an open PR that resolves this https://github.com/WordPress/gutenberg/pull/28630.

**Comment by jasmussen** [comment] 2021-02-09 15:50
Was about to say that this appears a duplicate of https://github.com/WordPress/gutenberg/issues/28457

**Comment by vindl** [comment] 2021-02-09 16:39
> Was about to say that this appears a duplicate of #28457

That one seemed related just to column block and with different positioning offset, while this one applies to all blocks. Fortunately the linked PR solves both issues.

**Comment by david-szabo97** [comment] 2021-02-09 16:52
We can close #28457 in favor of this one. But hopefully, we can merge soon and get both ticked off. My PR was more specific but it's basically the same issue, the same component that's causing it.

**Comment by david-szabo97** [comment] 2021-02-11 16:34
Fixed by https://github.com/WordPress/gutenberg/pull/28630

**Closed by david-szabo97** 2021-02-11 16:34 UTC
Labels: [Feature] Full Site Editing, [Priority] High, [Type] Bug
