### ISSUE TITLE
Pasting in a long text from Word - adds ekstra space before first letter of each paragraph

### ISSUE THREAD

**Issue by dejliglama** [WordPress/gutenberg#14403] opened 2019-03-13 10:53 UTC
When copy pasting the entire text from attached document, into Gutenberg, each paragraph starts with a Space (not visible in the code). 

**To Reproduce**
1. open docx (attached ticket)
2. Copy the entirety of the doc
3. create new post, and write a sample title - hit enter
4. (now you are in the first paragraph of the post> paste the content into the post

**Expected behavior**
The text with paragraphs as seen in the document

**Screenshots**
![gb-spacing-issue](https://user-images.githubusercontent.com/1443733/54273969-48746580-4587-11e9-84fa-9563cb2539bb.PNG)

[Har it-konsulenter et dataansvar.docx](https://github.com/WordPress/gutenberg/files/2961114/Har.it-konsulenter.et.dataansvar.docx)

**Comment by ellatrix** [comment] 2019-03-13 13:04
Duplicate of #13647.

**Closed by ellatrix** 2019-03-13 13:04 UTC
