### ISSUE TITLE
Formatting toolbar glitch

### ISSUE THREAD

**Issue by padraigobeirn** [WordPress/gutenberg#5408] opened 2018-03-05 14:14 UTC
## Issue Overview
WordPress 4.9.4 with Gutenberg 2.3.0 (Classic editor plugin not installed). Happens in latest versions of Chrome, Firefox and Edge. A large formatting toolbar appears over a block if you save a post as a draft then leave the post and re-visit it to edit. 

## Steps to Reproduce (for bugs)

1. Create a new post (All posts > Add New).
2. Copy and paste some text from a web page OR simply type in a few words.
3. Save a draft and go to All Posts.
4. Click on the draft to edit it again.
5. A large toolbar now appears over each block (you need to click on Code Editor, then back to Visual Editor to make it go away.). 

## Expected Behavior
The standard Gutenberg toolbar should appear over the block or docked to the top depending on the settings.

## Current Behavior
Some version of the Classic Editor toolbar appears over each block.

## Possible Solution
Could be peculiar to my setup. Suggestions welcome if it can't be reproduced.

## Screenshots / Video
![230editor](https://user-images.githubusercontent.com/33803178/36979030-2269d71e-207e-11e8-92c9-7a1cd9961708.gif)

**Comment by youknowriad** [comment] 2018-03-06 15:20
This is probably caused by a plugin you have, can you try to isolate it which plugin does this and see if they can work on Gutenberg compatibility?

**Comment by karmatosed** [comment] 2018-03-06 21:28
I am also unable to replicate this, closing for now but if you do feel this is down to Gutenberg not plugins, let's reopen.

**Closed by karmatosed** 2018-03-06 21:28 UTC

**Comment by padraigobeirn** [comment] 2018-03-08 12:03
Thanks guys. I've isolated the plugin and will contact the author to let him know.

**Comment by padraigobeirn** [comment] 2018-05-05 09:17
This issue has been resolved with the release of Gutenberg 2.80.
