### ISSUE TITLE
List: implement levels of indent buttons

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#549] opened 2017-04-28 12:30 UTC
To create nested lists and sub-levels.

**Comment by iseulde** [comment] 2017-05-04 11:37
For this one we probably need the TinyMCE list plugin for now, which gives us these additional commands.

**Comment by mtias** [comment] 2017-05-04 11:49
Should we couple `Editable` with that plugin or can we make a wrapper around it that is specific for List blocks?

**Comment by iseulde** [comment] 2017-05-04 11:53
We can either just add it for all Editable instances, or allow the block to change the plugins... I'm thinking for now it's fine to just add it to all?

**Comment by iseulde** [comment] 2017-05-04 11:54
Ah I see what you mean with adding the buttons... The plugin will come with the shortcuts working already. Somehow we'll need to tie the commands to the buttons.

**Comment by EphoxJames** [comment] 2017-05-08 00:37
In my current prototype I'm using tinymce.activeEditor to apply commands on the editor. I would like a better way if anyone has suggestions. Currently the only alternative I can think of is moving the indent/outdent code to the Editable like the alignment.

**Comment by EphoxJames** [comment] 2017-05-08 02:56
@jasmussen Are there plans for an isEnabled function for control buttons? I see in the blocks/README.md it mentions an isVisible function but that wouldn't be as useful for indent buttons.

**Comment by jasmussen** [comment] 2017-05-08 07:30
> Are there plans for an isEnabled function for control buttons? I see in the blocks/README.md it mentions an isVisible function but that wouldn't be as useful for indent buttons.

If we need it, we'll make it happen, is what I think. Could you ask @iseulde as well? She's our resident super expert on this stuff. She hangs out in #core-editor also.

**Comment by EphoxJames** [comment] 2017-05-08 23:13
The downside of the TinyMCE list plugin is that is captures tab keys to do list indenting which means that tab navigation stops working. :-( I'm still trying to find a way around this limitation.

**Comment by EphoxJames** [comment] 2017-05-09 06:34
I've submitted a pull request for this feature:
https://github.com/WordPress/gutenberg/pull/717
There are still some unresolved issues like how to tie the commands to buttons in nicer ways than using the global `tinymce.activeEditor`. There is also the known tab navigation issue caused by the lists plugin which I hope to fix on the TinyMCE side.

**Comment by aduth** [comment] 2017-05-26 20:49
Considering this resolved by #717

**Closed by aduth** 2017-05-26 20:49 UTC
Labels: Blocks, Task

**Comment by jb510** [comment] 2017-05-29 23:50
Apologies I'm having trouble finding somewhere appropriate for this feedback, but... I find not having tab function as indent (like it does in nearly every GUI) to be extremely confusing. That UI needs to get dropped for lots of reasons, along with rearranging blocks (those arrows drive me mad). Anyway, commenting here because it's related to tabs, but I really hope overriding the default keyboard shortcut for indenting lists isn't the ultimate solution here.

**Comment by BE-Webdesign** [comment] 2017-05-30 00:21
@jb510 

Tab support for list indentation can definitely be added in.  I recommend [opening a new issue](https://github.com/WordPress/gutenberg/issues/new).  In the title state the need ( tab support for list indentation ).  It is important to understand that Gutenberg is in active development, and is not fully polished yet.

If there is any common/standard functionality you feel is missing, chronicling each item in the issue tracker is of great help.  Keep each issue focused and concise.  If you have any questions, feel free to add a `Question: issue` or join the #core-editor slack channel.

**Comment by EphoxJames** [comment] 2017-05-30 00:31
@jb510 @BE-Webdesign The tab key was doing list indentation but I was told that it broke accessibility so it got disabled. It is very easy to re-enable it but you can't navigate out of the list block using the keyboard.
