### ISSUE TITLE
Separator block is difficult to select

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#20714] opened 2020-03-09 09:10 UTC
I'm using WP 5.4-RC1 right now, and I'm finding that selecting a separator block with the short line and wide line styles is a bit difficult, even more if it's inside a group block. Selecting a separator block with the dots style is easier because of the bigger size.

Am I the only one?

**Comment by jasmussen** [comment] 2020-03-09 14:26
This is fixed in the plugin version:

![separator](https://user-images.githubusercontent.com/1204802/76221975-2f45d980-621a-11ea-9e9d-fe3def88e4b2.gif)

Extra padding has been added to make that easier to select.

Unfortunately that fix is not part of the 5.4 RC release, and it's not easy to backport.

**Comment by jorgefilipecosta** [comment] 2020-03-09 21:00
Closing as the issue is fixed on the plugin.

**Closed by jorgefilipecosta** 2020-03-09 21:00 UTC
Labels: [Type] Bug
