### ISSUE TITLE
Can't transform embed to raw URL

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#16159] opened 2019-06-13 15:47 UTC
**Is your feature request related to a problem? Please describe.**

I often will paste a URL into the editor while I'm working on a draft for a post. My intent is not to create an embed, but just to save that URL in my notes so that I can later use it as a link in a paragraph.

When I paste it in, though, it automatically gets turned into an embed, even if the oEmbed process fails (which seems to be at least half the time for WP posts). There's no way to transform it back to the raw URL, so I have to right-click to copy the url, then remove the Embed block, then add some arbitrary character to the start of a new line, then paste the link again (because the link is only transformed when it's on a line by itself).

I could avoid that by adding that arbitrary character before I paste the link in the first place, but I always forget to do that, because I naturally don't expect the editor to do something contrary to my intent, even though I've known about the automatic oEmbed feature forever, and even agree that it's very useful _when I'm intending to embed something_. The problem is that, when I'm pasting in a URL, my intent is to save it as a note much more often than when my intent is to embed it.

**Describe the solution you'd like**

I don't know if there's a way to solve the underlying problem (the editor incorrectly assumes that my intent is always to create an embed), but we could at least provide an easy way to recover from that, by having a toolbar button to transform embeds to their raw URL, similar to how you can transform a paragraph to a heading.

**Related**

https://github.com/WordPress/gutenberg/issues/15102 is related, but I don't think this is a duplicate. I don't want to transform the block to a paragraph with a link, I want to transform it to a paragraph with the raw URL. If the anchor text for the link is the raw URL, then that'd probably be fine, but I wouldn't want the anchor text to be the title of the page that the URL references.

**Comment by melchoyce** [comment] 2019-06-14 00:15
Maybe backspace could revert this too, like I think we do with markdown?

**Comment by gziolo** [comment] 2019-11-20 12:30
I think it's a duplicate of #15102. The proposed solution is to convert embed to a text link which might be a raw URL. In the worst case you can always remove the anchor wrapper.

**Closed** 2019-11-20 12:30 UTC
Labels: [Block] Embed, [Status] Duplicate, [Type] Enhancement
