### ISSUE TITLE
Insert link on bold text

### ISSUE THREAD

**Issue by skariko** [WordPress/gutenberg#64572] opened 2024-08-16 09:45 UTC
### Description

In the new versions of Wordpress there is a bug on the editor.

If you put a text in bold and then paste a link to it, it does not create as a hyperlink but the text is deleted and the link is inserted in text version.

In order to put a link you must first paste the link on the selected text and only then put it in bold.

### Step-by-step reproduction instructions

1. Write a text
2. Put any word in bold
3. Try to paste a link on selected text in bold

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/d9fbad83-fafa-42b4-833e-128575983fb7

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by bph** [comment] 2024-08-21 04:46
Thank you @skariko this seems to be a duplicate of #63434 - please add your comments there. I close this for now.

**Closed as completed** 2024-08-21 04:47 UTC
Labels: [Type] Bug
