### ISSUE TITLE
Quote block V2: Crash when changing font size or line height

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#40545] opened 2022-04-22 14:00 UTC
## Description

The v2 of the Quote block is crashing when changing its font size or line height properties.

## Step-by-step reproduction instructions

**Precondition for enabling v2:**
- Use a self-hosted site and install the latest Gutenberg plugin version >= 13.0.0. You can install the latest version [here](https://github.com/WordPress/gutenberg/releases).
- Go to your site's admin page > Gutenberg > Experiments.
- Enable `Quote block v2`.

1. Add a Quote block.
2. Open the block settings by tapping on the gear icon button.
3. Change the font size or line height.
4. Observe that the editor crashes.

## Expected behaviour

Changing the font size or line height of the block shouldn't produce errors.

## Actual behaviour

Changing the font size or line height crashes the editor.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/14905380/164729021-d1b93cf9-39e6-4d17-8d0b-9eb1a77a0717.mp4

## WordPress information
- WordPress version: 5.9.3
- Gutenberg version: 13.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S20 FE 5G
- Operating system: Android 11
- WordPress app version: 19.7-rc-1

**Comment by fluiddot** [comment] 2022-04-22 14:07
@geriux @jhnstn I encountered this crash while beta testing version `19.7-rc-1` of WordPress-Android. However, I couldn't reproduce it using WordPress-iOS `19.7.0.1`.

**Comment by geriux** [comment] 2022-04-22 15:31
I found what the issue is 😅 , I'll work on a fix for this.

**Closed as completed** 2022-04-26 07:22 UTC
Labels: [Type] Bug, Mobile App - i.e. Android or iOS, [Block] Quote
