### ISSUE TITLE
Blocks behind blocks

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#3725] opened 2017-11-29 23:30 UTC
## Issue Overview

When I try the Einstein test, if I scale the image down to be left aligned with the quote on the right the block bounding box for the quote goes behind the image. 
<img src="http://cld.wthms.co/UhNDBp+"/>

## Steps to Reproduce (for bugs)

1. Use this [Einstein test](https://wpusabilitytesting.polldaddy.com/s/gutenberg-flow-a).
2. Resize the image to be smaller and left aligned.
3. Try adding the quote on the right of the image. (any block will do this) 

## Expected Behavior

I expected the bounding box of the quote to only be around the quote. Not to go behind the image. I also expected the toolbar to be above the quote, vs left aligned above the image. It feels disconnected from the quote block to me. 

## Current Behavior

When the quote box is selected the block outline is behind the image. 

## Possible Solution

It feels like the block outline should only be around the quote block like this: 
<img src="http://cld.wthms.co/pvu92j+"/>

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by hedgefield** [comment] 2017-12-05 10:24
Yes, I guess this is a side effect of the current alignment implementation, any block that is not marked as being left- or right-aligned stays full width, even though the content does align correctly when it falls behind an aligned block. For sure something that needs to be fixed, possibly by [this nested blocks PR](https://github.com/WordPress/gutenberg/pull/3745).

**Comment by jasmussen** [comment] 2018-01-04 08:47
This seems to be a duplicate of #3868, so I'm going to close this one and propose a fix ont he other one.

**Closed by jasmussen** 2018-01-04 08:47 UTC
