### ISSUE TITLE
Can't Click Right Side of Empty Menu Item on Navigation Block

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19482] opened 2020-01-07 16:19 UTC
**Describe the bug**
You can't click the right side of an empty menu item that contains the "Add Link..." placeholder text. The left side has a pretty narrow clickable area to activate it.

**To reproduce**
1. Add a new menu item to the navigation block
2. Don't add a link to it, but try to click on the right side of the placeholder "Add Link..." text
3. Cursor will not appear to edit the text unless you click on the left side near the "A" of "Add Link..."

**Expected behavior**
Clicking anywhere on the placeholder area should activate the menu item block.

**Screenshots**
![set-text-item](https://user-images.githubusercontent.com/967608/72075820-16708480-32ba-11ea-8d85-b7f22277fa76.gif)

**Desktop**
OS: MacOS Catalina - 10.15.2
Browser: Chrome
Version: Gutenberg 7.2.0-rc.1

**Additional context**
Tested locally with built version of master and WordPress Version 5.3.2 with Gutenberg as the only active plugin.

**Comment by momotofu** [comment] 2020-01-09 06:44
Hey @jeryj 👋 Can you upload an animated gif demonstrating the issue. I've tested it out on Firefox and Chrome by clicking on the right of the "Add link..." placeholder text. It seems to activate the textbox as expected.  

![Jan-09-2020 15-34-35](https://user-images.githubusercontent.com/5377298/72043859-a5e75900-32f5-11ea-9603-572724a50777.gif)

**Comment by jeryj** [comment] 2020-01-09 14:31
@momotofu, I updated the issue. It was originally supposed to be a gif, but I copy/pasted it and I didn't realize it only added a png 🤦

**Comment by getdave** [comment] 2020-01-09 16:46
@ellatrix Is there any chance this could be an issue with `RichText`? I know it's quite specific about where you click and focus management.

We'll look into it but I couldn't see any layout / CSS issues when I (briefly) tested.

**Comment by jeryj** [comment] 2020-01-14 20:30
This appears to be fixed. I can't get it to break anymore. Anywhere I click that shows the cursor works to activate the input.

**Comment by obenland** [comment] 2020-01-14 21:19
This is fixed for you in master? It still happens for me 🤔

**Comment by jeryj** [comment] 2020-01-14 21:20
Yup. Fixed in `master` for me... 🤔 I wonder what is different on our machines this week?!?

**Comment by apeatling** [comment] 2020-01-14 21:41
I can't reproduce it in master.

**Comment by apeatling** [comment] 2020-01-14 21:56
Prompted by @retrofox to try this again. It looks like this doesn't happen for the first navigation link in a navigation block, only for the second and beyond.

**Comment by jeryj** [comment] 2020-01-15 15:58
I can't get it to mess up anymore, first link or not 🤷‍♂ 

![select right side of nav link](https://user-images.githubusercontent.com/967608/72448896-6dc09a00-377d-11ea-989b-2cdaa03dd234.gif)

I tried clicking the right side of the placeholder in various places, multiple nav menus, submenus, etc.

**Comment by retrofox** [comment] 2020-01-21 15:40
Closing since it seems to be already fixed. Let's keep 👁.

**Closed by retrofox** 2020-01-21 15:40 UTC
Labels: [Block] Navigation, [Type] Bug
