### ISSUE TITLE
Navigation block doesn't open on mobile, also sub menus on click

### ISSUE THREAD

**Issue by derridHeidegger** [WordPress/gutenberg#38075] opened 2022-01-19 14:05 UTC
### Description

i have a clean WordPress install with the TT1 theme. without any plugins except Gutenberg. i edit the header in the fse, and add navigation. the navigation doesn't open on mobile. there are no errors in the dev tools console. just to test things i also upgraded to 5.9 beta tester, and the same result.

any idea?

### Step-by-step reproduction instructions

1. add navigation block
2. add pages, and sub pages too if you want
3. save
4. check the front end on mobile via chrome dev tools

### Environment info

wordpress version:  5.8.3 and 5.9-RC1
gutenberg version: 12.3.2
checked on: chrome, fifrefox, edge and opera

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by vcanales** [comment] 2022-01-19 15:42
Hi! Thanks for taking the time to report. This problem seems to be the same as https://github.com/WordPress/gutenberg/issues/37996 which was solved in https://github.com/WordPress/gutenberg/pull/38032 and backported to core for RC3. Let me know if the issue is persists after updating!

**Comment by derridHeidegger** [comment] 2022-01-19 16:40
hi thanks for answering, but it looks like her issue was the admin bar on mobile. in any case i have the latest gutenberg plugin.

**Comment by derridHeidegger** [comment] 2022-01-20 06:55
so yesterday i forgot to update to 5.9 after using the beta tester. it does work now. so will there be a workable navigation only after 5.9 will be released? or will there be an update before, so the navigation block can be used?

**Comment by aristath** [comment] 2022-01-20 07:25
> will there be a workable navigation only after 5.9 will be released?

For sites that don't use the Gutenberg plugin, the navigation block will be working properly after the 5.9 WP release.
For sites that use the Gutenberg plugin, it should be OK after updating the plugin.

Since this has already been resolved, I'll go ahead and close the issue 👍

**Closed as completed by aristath** 2022-01-20 07:25 UTC
