### ISSUE TITLE
Block tools are not showing correctly when viewing patterns

### ISSUE THREAD

**Issue by paulopmt1** [WordPress/gutenberg#63587] opened 2024-07-16 00:23 UTC
### Description

When editing a block text and previewing a pattern, the sidebar pushes the editor to the right, hiding some block tools and positioning it in the wrong place.

### Step-by-step reproduction instructions

1. Write some text in the editor
2. Open the `Toggle block inserter`
3. Select `Patterns`
4. Click on `All`
5. You'll see the error

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c06cd067-27d8-43e3-a51e-3100a3cede4c

### Environment info

Gutenberg v18.8.0-rc.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment] 2024-07-16 06:06
I think this was fixed via #63417.

**Comment by richtabor** [comment] 2024-07-16 14:45
Closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/63463.

**Closed as completed by richtabor** 2024-07-16 14:45 UTC
Labels: [Type] Bug, [Feature] Zoom Out
