### ISSUE TITLE
Removing wpautop does not work in Gutenberg

### ISSUE THREAD

**Issue by orchidGem** [WordPress/gutenberg#11895] opened 2018-11-15 09:16 UTC
**Describe the bug**
Removing the wpautop filter does not work when Gutenberg is activated. I write all of my content in posts and pages written in the text editor and have wpautop removed for all of my sites using remove_filter('the_content', 'wpautop');  This works fine in Classic editor, however when Gutenberg is installed it adds paragraphs and break tags and shifts content around and thus breaks the user front end of the pages. 

**To Reproduce**
1. Make sure Gutenberg is not installed
2. Write html inside the text tab of the editor
      `<p>Test</p>
      <img src="" />`
3. Add `remove_filter('the_content', 'wpautop');` to functions file
4. View page to ensure html is rendered same is written in text editor
5. Install and activate Gutenberg
6. View page and you will see the image tag is wrapped in a p tag now

**Expected behavior**
I expect backwards compatibility for this. I cannot take my sites live with the Gutenberg editor if this does not work as before. I plan to move everything to either blocks or the new html block at some point, but this is manual work that will take time and the site needs to look and function the same in the meantime.

**Comment by designsimply** [comment] 2018-11-15 15:36
@orchidGem could you note the versions of WordPress and the Gutenberg plugin you tested with for reference?

**Comment by designsimply** [comment] 2018-11-15 17:37
Thank you for the clear set of testing steps! 

I tested and confirmed that `<p>` tags are added around the `<img>` tag from the sample content after adding `remove_filter('the_content', 'wpautop');` to `functions.php` in the Twenty Seventeen theme when using WordPress 4.9.8 and Gutenberg 4.3. ([screenshots](https://cloudup.com/cn6TKMGV0lz))

Next, I tested the same steps with WordPress 5.0-beta4-43896 (no Gutenberg plugin) using the classic block and I found that the sample content `<p>Test</p> <img src="" />` became `Test <img src="" />`.

(If I am reading correctly!) I think that the intention is for it to be as backward-compatible as possible in the sense that it should work as closely as possible with WP4.9.8 (no plugin) and WP5.0 final. This is my interpretation after reading https://core.trac.wordpress.org/ticket/45290 and I think the next step will be to find out if the behavior where `<p>Test</p> <img src="" />` becomes `Test <img src="" />` is the expected outcome or not because I noticed that switching from text to visual and back to text using WP4.9.8 (no Gutenberg plugin) has the same result of `Test <img src="" />`.

I added `Needs Technical Feedback` label to get help finding out the intended behavior and to ask whether this case should be reported upstream at https://core.trac.wordpress.org/ or not given the changeset at https://core.trac.wordpress.org/changeset/43879

**Comment by orchidGem** [comment] 2018-11-15 18:20
> @orchidGem could you note the versions of WordPress and the Gutenberg plugin you tested with for reference?

I am using WP version 4.9.8 and Gutenberg version 4.3.0

**Comment by lkraav** [comment] 2018-11-19 14:50
@loratov you should not be using Gutenberg-global "Code Editor" to achieve that goal. It will try to re-parse everything into modern block format, and it should keep doing that.

For maintaining HTML as-is, use the HTML block, and paste HTML in there.

It will remove the ability to edit content in Visual mode, though.

I think the long-term smarter thing to do is actually let Gutenberg reformat your content with proper tag semantics, but I fully understand not everyone has the time/energy to undertake such a project.

**Comment by gziolo** [comment] 2019-05-24 05:03
> I just tested it with the 5.0 beta as well and now the layout, just after installing wordpress, is fine ( removing the wpautop filter still works after the 5.0 update).

Yes, it should be fixed. This issue existed pre-5.0.

**Comment by youknowriad** [comment] 2020-09-16 08:06
I'm closing this as the original issue here is fixed.

**Closed by youknowriad** 2020-09-16 08:06 UTC
Labels: Needs Testing, [Type] WP Core Bug
