### ISSUE TITLE
Gutenberg plugin 

### ISSUE THREAD

**Issue by bakoorahnin** [WordPress/gutenberg#31434] opened 2021-05-03 16:11 UTC
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by annezazu** [comment] 2021-05-03 16:23
@bakoorahnin hey there! Can you please provide more information here (what the problem is? what version you're using? etc)? Otherwise, we'll need to close this out :)

**Closed as completed** 2021-05-03 16:53 UTC
Labels: [Status] Needs More Info
