### ISSUE TITLE
Gutenberg with a custom block crashes when Featured Image Panel is open

### ISSUE THREAD

**Issue by crs1138** [WordPress/gutenberg#20170] opened 2020-02-11 15:02 UTC
**Describe the bug**

Default Gutenberg editor screen:
![Before opening Featured Image Inspector Panel Body](https://user-images.githubusercontent.com/1313681/74245543-72785f80-4ce3-11ea-80f1-7cf308e8698f.png)

I've made a custom Gutenberg block. Everything works as expected until I try to open the _Featured Image_ tab in the document inspector of the Gutenberg editor. The following screen is displayed:
![After opening the Featured Image Inspector Panel Body](https://user-images.githubusercontent.com/1313681/74245754-caaf6180-4ce3-11ea-9e33-a6d19fcb428b.png)

This happens only when a block is defined in my plugin. Here is an example of a minimum use case Gutenberg block:
```js
const { registerBlockType } = wp.blocks;

export default registerBlockType(
    'cv-wp-lib-gutenberg-blocks/minimal',
    {
        title: 'Minimal',
        description: 'Testing for the conflict of our plugin with the Featured Image tab in the page inspector',
        category: 'common',
        icon: {
            src: 'warning'
        },
        edit: () => <div className="test-block">
            <h1>Testing</h1>
        </div>,
        save: () => <div className="test-block">
            <h1>Testing</h1>
        </div>
    }
);
```
The block behaves fine if the _Featured Image_ PanelBody is closed. As soon as it's opened, the editor is blocked until I deactivate the plugin, edit the post and collapse the _Featured Image_ PanelBody. If no blocks are included in the plugin, the error does not appear.

Copy error:
```
TypeError: this.activateMode is not a function
    at http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2806:9
    at arrayEach (webpack-internal:///./node_modules/lodash/lodash.js:516:11)
    at Function.forEach (webpack-internal:///./node_modules/lodash/lodash.js:9342:14)
    at i._createModes (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2805:5)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2754:8)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2934:30)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:3287:35)
    at i.h.View (http://gutenberg.local/wp-includes/js/backbone.min.js?ver=1.4.0:1:14225)
    at i.constructor (http://gutenberg.local/wp-includes/js/wp-backbone.js?ver=5.3.2:503:18)
    at i.constructor (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2681:20)
```

Copy post text: _does nothing_

Attempt to recover: _does nothing_

**To reproduce**
1. Active the plugin that includes a custom Gutenberg block.
2. Create a new post/page or edit an existing one.
3. Click to expand the _Featured Image_ PanelBody in the _Document inspector_.

**Expected behavior**
I expect no error to happen regardless of the _Featured Image_ being expanded or collapsed.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- Operating system: OS X 10.15.2
- Javascript enabled: Yes
- Cookies enabled: Yes
- Flash version: Not installed
- Java version: Not installed
- Websockets supported: Yes
- WebGL supported: Yes
- Language: en-US
- Browser size: 1920 x 946
- Screen size: 1920 x 1080
- Colour depth: 24 bit
- AdBlock enabled: Yes
- Your full user agent string is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Smartphone (please complete the following information):**
 Not tested

**Additional context**
- Using Gutenberg that comes with WP 5.3.2

**Comment by crs1138** [comment] 2020-02-12 07:03
I've just tested with Gutenberg v7.4.0 - the same error.

**Comment by youknowriad** [comment] 2020-02-12 12:25
Hi There! this error seems unrelated to your custom block shared above. If you have plugins (especially media related ones) active on your websites, try disabling them one by one and see if it improves the situation.

**Comment by crs1138** [comment] 2020-02-12 14:39
It's a clean WP installation with only Gutenberg 7.4.0 plugin and our Gutenberg block installed.
```
https://barcelona.apeteat.com/leadtech +----------------------------+----------+--------+---------+
| name                       | status   | update | version |
+----------------------------+----------+--------+---------+
| cv-wp-lib-gutenberg-blocks | inactive | none   | 0.2.0   |
| gutenberg                  | active   | none   | 7.4.0   |
+----------------------------+----------+--------+---------+

+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| twentynineteen  | inactive | none   | 1.4     |
| twentyseventeen | inactive | none   | 2.2     |
| twentysixteen   | inactive | none   | 2.0     |
| twentytwenty    | active   | none   | 1.1     |
+-----------------+----------+--------+---------+
```

**Comment by crs1138** [comment] 2020-02-12 15:49
Also if I don't import the block itself (or any other block), the featured image does not crash. And I don't mean disabling the plugin, just not including any of the blocks in the compilation process by commenting out their import.

**Comment by crs1138** [comment] 2020-02-17 08:50
Let me know if you need more details (full code of the plugin).

**Comment by jorgefilipecosta** [comment] 2020-03-02 10:18
Hi @crs1138,
I used this block as test code equivalent to the one you you provided:
```
( function(){
    var registerBlockType = wp.blocks.registerBlockType;
    var el = wp.element.createElement;
    function outputMarkup() {
        return el(
            'div',
            {},
            el( 'h1', {},'Testing' )
        )
    }


    registerBlockType(
        'cv-wp-lib-gutenberg-blocks/minimal',
        {
            title: 'Minimal',
            description: 'Testing for the conflict of our plugin with the Featured Image tab in the page inspector',
            category: 'common',
            icon: {
                src: 'warning'
            },
            edit: outputMarkup,
            save: outputMarkup,
        }
    );
} )();
```

And I was not able to reproduce the issue with WordPress 5.3.2 (with and without the Gutenberg plugin).
Are you still facing this problem?

**Comment by crs1138** [comment] 2020-03-03 11:13
@jorgefilipecosta This is rather strange, your ES5 example works fine. It seems to be something to do with Webpack / Babel compilation of the ES6 as the problem only happens in development mode and only for the ES6 block. 
* If I compile for production, it all works fine.
* If I use only ES5 code, it all works fine.

Here's our set up.

Our package.json:
```json
{
  "name": "cv-wp-lib-gutenberg-blocks",
  "version": "0.2.0",
  "main": "blocks/index.js",
  "author": "***",
  "scripts": {
    "test": "echo \"Warning: no test defined, skipped\" && exit 0",
    "prebuild": "npm ci",
    "stage-build": "echo \"Warning: no stage built defined, skipped\" && exit 0",
    "master-build": "webpack --env.env=prod",
    "build": "npm run stage-build && npm run master-build",
    "dev": "webpack --env.env=dev --watch=true",
    "dev:nowatch": "webpack --env.env=dev --watch=false",
    "doc": "jsdoc -c jsdoc.json"
  },
  "devDependencies": {
    "@wordpress/babel-preset-default": "^4.10.0",
    "babel-core": "^6.25.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "classnames": "^2.2.6",
    "css-loader": "^2.1.0",
    "eslint": "^5.12.1",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "node-sass": "^4.8.3",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^1.0.0",
    "sass-loader": "^7.1.0",
    "sass-resources-loader": "^2.0.1",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "autoprefixer": "^9.4.6",
    "rupture-sass": "^0.3.0"
  },
  "browserslist": [
    "Defaults",
    "not op_mini all"
  ]
}
```
Our webpack.config.js:
```javascript
const webpack = require('webpack');
const path = require("path");
const commonPaths = {
  outputPath: path.resolve(__dirname, './', 'assets'),
  cssPath: path.resolve(__dirname, './', 'assets/css'),
  libPath: path.resolve(__dirname, './', 'lib'),
};
const ExtractTextPlugin = require("extract-text-webpack-plugin");

// Set different CSS extraction for editor only and common block styles
const blocksCSSPlugin = new ExtractTextPlugin({
    filename: "./css/blocks.style.css"
  });
  const editBlocksCSSPlugin = new ExtractTextPlugin({
    filename: "./css/blocks.editor.css"
  });

module.exports = () => {

    // Configuration for the ExtractTextPlugin.
    const extractConfig = {
        use: [
        { loader: "raw-loader" },
        {
            loader: "postcss-loader",
            options: {
            plugins: [require("autoprefixer")]
            }
        },
        {
            loader: "sass-loader",

        },
        {
            loader: 'sass-resources-loader',
            options: {
                // Provide path to the file with resources
                resources: [`${commonPaths.libPath}/global-style.scss`],
            },
        },
        ]
    };

    return {
        entry: {
          "./js/editor.blocks": "./blocks/index.js",
          './js/frontend.blocks' : './blocks/frontend.js',
        },
        output: {
          path: commonPaths.outputPath,
          filename: "[name].js"
        },
        devtool: false,
        module: {
          rules: [
            {
              test: /\.js$/,
              exclude: /(node_modules|bower_components)/,
              use: {
                loader: "babel-loader",
                options: {
                  presets: ["@wordpress/default"],
                  plugins: [
                    [
                      "@babel/transform-react-jsx",
                      { pragma: "wp.element.createElement" }
                    ]
                  ]
                }
              }
            },
            {
              test: /style\.s?css$/,
              use: blocksCSSPlugin.extract(extractConfig)
            },
            {
              test: /editor\.s?css$/,
              use: editBlocksCSSPlugin.extract(extractConfig)
            }
          ]
        },
        plugins: [blocksCSSPlugin, editBlocksCSSPlugin]
      };
};
```

Development compilation command: `node_modules/webpack/bin/webpack.js --mode=development`
Production compilation command: `node_modules/webpack/bin/webpack.js --mode=production`

Both compilation commands pass without error.

./src/index.js:
```javascript
/**
 * Import Minimal block - tests crashing Gutenberg editor with our plugin
 */
import "./minimal";

/**
 * Import Minimal block - tests crashing Gutenberg editor with our plugin
 */
import "./minimal-es5";
```

./src/minimal/index.js:
```javascript
( function(){
    const { registerBlockType } = wp.blocks;
    registerBlockType(
       'cv-wp-lib-gutenberg-blocks/minimal-es6',
       {
           title: 'Minimal ES6',
           description: 'Testing for the conflict of our plugin with the Featured Image tab in the page inspector',
           category: 'common',
           icon: {
               src: 'warning'
           },
           edit: () => (<div className="test-block">
               <h1>Testing ES6</h1>
           </div>),
           save: () => (<div className="test-block">
               <h1>Testing ES6</h1>
           </div>)
       }
   );
})();
```

./src/minimal-es5/index.js
```javascript
( function(){
    var registerBlockType = wp.blocks.registerBlockType;
    var el = wp.element.createElement;
    function outputMarkup() {
        return el(
            'div',
            {},
            el( 'h1', {},'Testing ES5' )
        )
    }


    registerBlockType(
        'cv-wp-lib-gutenberg-blocks/minimal-es5',
        {
            title: 'Minimal ES5',
            description: 'Testing for the conflict of our plugin with the Featured Image tab in the page inspector',
            category: 'common',
            icon: {
                src: 'warning'
            },
            edit: outputMarkup,
            save: outputMarkup,
        }
    );
} )();
```

The compiled editor.blocks.js in development mode: [editor.blocks.js.zip](https://github.com/WordPress/gutenberg/files/4280929/editor.blocks.js.zip)

**Comment by talldan** [comment] 2020-04-23 03:47
The stack-trace for the issue points to some code in WordPress core, so I think this is likely to be either an environment issue or a missing dependency:
```
TypeError: this.activateMode is not a function
    at http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2806:9
    at arrayEach (webpack-internal:///./node_modules/lodash/lodash.js:516:11)
    at Function.forEach (webpack-internal:///./node_modules/lodash/lodash.js:9342:14)
    at i._createModes (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2805:5)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2754:8)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2934:30)
    at initialize (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:3287:35)
    at i.h.View (http://gutenberg.local/wp-includes/js/backbone.min.js?ver=1.4.0:1:14225)
    at i.constructor (http://gutenberg.local/wp-includes/js/wp-backbone.js?ver=5.3.2:503:18)
    at i.constructor (http://gutenberg.local/wp-includes/js/media-views.js?ver=5.3.2:2681:20)
```

This issue seems to have moved on to being a general troubleshoot rather than anything specifically related to development of the editor. It's beyond the scope of the issue tracker for this project, so I'll close this.

I hope you manage to solve the issue though!

**Closed by talldan** 2020-04-23 03:47 UTC
Labels: [Status] Needs More Info, [Type] Help Request

**Comment by crs1138** [comment] 2020-06-03 07:44
Modifying the Webpack config as suggested in https://github.com/WordPress/gutenberg/issues/4043#issuecomment-633081315 seems to resolve the issue.
