### ISSUE TITLE
Improve new user experience with help

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#16147] opened 2019-06-13 08:00 UTC
The very first screen a new user sees when they go to add their first post with Gutenberg is very bare, and contains instructions that won't work if the user follows them. I've seen users close the editor at this screen, thinking it's broken.

![hello-there](https://user-images.githubusercontent.com/3314354/59414208-0098f080-8db9-11e9-9c7c-0e6dfd82767b.png)

1) There's no (+) in the user's visual focus to add blocks. It's hidden until you wave the mouse around. This is mystery meat, and a UI anti-pattern.
2) The title has the focus initially, as it should, but the paragraph placeholder that appears underneath the title doesn't look like a paragraph at all. It doesn't look like it can be interacted with. It appears to be an instruction for the user to follow. If they follow it by typing `/`, nothing happens. 
3) The new editor has many _many_ new features and ways to configure it, none of which we educate the user about. We need a link to the handbook here, as new users who have closed the popup hints by reflex (as the modern web has trained them to do) are left wondering what to do next. Faced with just this screen, how would you add an image? Remember -you have no idea what a block is at this point, and the instructions that mention them don't work because the title has focus and the instructions don't look like anything you can click on to give focus.

cc @melchoyce as they were adding help links to the embed blocks :)

**Comment by youknowriad** [comment] 2019-06-13 10:18
I think this is a duplicate of #16132 as it seems the suggestion here is to add links to the user handbook.

**Closed by youknowriad** 2019-06-13 10:18 UTC
Labels: NUX

**Comment by notnownikki** [comment] 2019-06-13 10:34
Maybe this should just address the confusion around the initial block paragraph looking like an instruction (that doesn't work if you follow it immediately)?

**Comment by youknowriad** [comment] 2019-06-13 13:42
In the last version, there's a "+" button always visible when you start a new post. Would this solve this confusion.
