### ISSUE TITLE
Interaction with neve theme causing Block "core/legacy-widget" is already registered. and Error: The “meta-sidebar” plugin cannot be rendered

### ISSUE THREAD

**Issue by donbowman** [WordPress/gutenberg#48749] opened 2023-03-03 20:35 UTC
### Description

In the browser javascript console when editing a post, i see:

Block "core/legacy-widget" is already registered.

In the browser as an error I see `Error: The “meta-sidebar” plugin cannot be rendered`

This appears to be an interaction between Gutenberg and Neve.

### Step-by-step reproduction instructions

install wp 6.1.1, neve, gutenberg
create a new post

the neve sidebar will not show.
the javascript console will show the Block "core/legacy-widget" is already registered.

### Screenshots, screen recording, code snippet

```
registration.js:276 Block "core/legacy-widget" is already registered.
ne @ registration.js:276
react-dom.min.js?ver=18:1 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at use-dispatch-with-map.js:40:11
    at Object.useMemo (react-dom.min.js?ver=18:1:115379)
    at e.useMemo (react.min.js?ver=18:1:9875)
    at use-dispatch-with-map.js:34:9
    at index.js:97:26
    at wt (react-dom.min.js?ver=18:1:47623)
    at $s (react-dom.min.js?ver=18:1:120736)
    at wl (react-dom.min.js?ver=18:1:88644)
    at bl (react-dom.min.js?ver=18:1:88572)
```

### Environment info

Wordpress 6.1.1
neve 3.5.4
gutenberg 15.2.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ghost** [comment] 2023-03-05 11:36
@donbowman Have you tried contacting the Theme Author/Support first?

**Comment by donbowman** [comment] 2023-03-09 00:38
Yes.
https://wordpress.org/support/topic/error-the-meta-sidebar-plugin-cannot-be-rendered/
there is a support thread open there. Its not clear to me which is the issue. It came w/ the gutenberg update, they were working together previous to 15.3.0

**Comment by donbowman** [comment] 2023-03-09 22:01
i don't think 'help request' label is accurate or correct, the newer version of gutenberg introduced this behaviour. I'm not looking for assistance in configuring it, but between gutenberg and neve an incompatibility was introduced.

**Comment by ghost** [comment] 2023-03-09 22:08
> I'm not looking for assistance in configuring it

Sure, but I can't reproduce it with any of the default WordPress themes (and a few others I'm using), so it does seem to be something the Theme Authors should have a look at first. If they believe they're doing everything right and something's broken in Gutenberg, they can pinpoint the issue with some context and we can attach a more specific label so the right contributors will notice it.

**Comment by donbowman** [comment] 2023-03-09 23:02
here's the minimal reproduction:
1. wp 6.1.1 (I used docker-compose). Stock settings
2. Install neve theme from dashboard
3. Install gutenberg plugin from dashboard, activate it
4. Create a new post

the problem shows up immediately on step 4.

```
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
```

is what i used.

**Comment by donbowman** [comment] 2023-03-10 16:50
narrowing it down, 15.2.0 breaks neve, 15.1.0 works ok.

**Comment by ghost** [comment] 2023-03-10 17:03
Thanks for the extra info @donbowman . I can indeed reproduce it with Neve, also in the 15.3 Release Candidate. Mentioned this in the Make WordPress Slack to gather some more info on what has changed here. My guess is the meta sidebar boxes are being replaced with [the new SlotFill system](https://developer.wordpress.org/block-editor/reference-guides/components/slot-fill/).

<img width="306" alt="Screenshot 2023-03-10 at 6 02 12 PM" src="https://user-images.githubusercontent.com/118618474/224377484-fb051171-e0e5-4c39-8499-1503fdb3d33a.png">

**Comment by bph** [comment] 2023-03-10 22:13
The error message, I encounter is 
`react-dom.min.js?ver=18:1 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)`
    
I also get the `The "meta-sidebar" plugin has encountered an error and cannot be rendered.` error message in the block editor. 
WP 6.2 RC
GB 15.3.1


If an error message can't be reproduced by a default theme and no other plugin activated, it is probably something that the Theme or the plugin developer would need to troubleshoot. So **help request** is correct for this issue in this repo. I would recommend filing a support ticket with the Theme developer, who seems to have plugin like code bundled with the theme, according to the error message.

**Comment by bph** [comment] 2023-03-10 22:21
@donbowman I would assume you already updated 15.3.0 to 15.3.1. 
Do you still encounter the 'core/legacy widgets is already registered' error message?

**Comment by donbowman** [comment] 2023-03-10 23:45
yes, 15.3.1 shows the error.
`the "meta-sidebar" plugin has encountered an error and cannot be rendered` is the primary issue (it blocks the use of the theme).

there is a ticket open w/ neve cross linked here (cross-linked both ways). The problem / interaction was introduced w/ gutenberg 15.2.0, no updates to the theme.

i don't know what plugin-like code means.

**Comment by bph** [comment] 2023-03-13 20:30
This only seems to be happening in the Neve theme and we weren't able to reproduce with a default theme. That's issue needs to be fixed by the Neve theme support.  I close this issue here.

**Closed as completed by bph** 2023-03-13 20:30 UTC
Labels: [Type] Help Request

**Comment by rifumi79** [comment] 2023-12-11 06:05
terimakasih para master...atas respon nya... its helfull me a lot.... best wishes for all of you..
