### ISSUE TITLE
Authors missing from author drop down menu on post

### ISSUE THREAD

**Issue by ChrisKellyBonhill** [WordPress/gutenberg#25914] opened 2020-10-07 16:15 UTC
Whilst creating an article, there is a dropdown menu that lists all the authors, editors and admins. However, on two of my websites, they stop at the letter F and C. This would obviously leave out a lot of names from the list.

Both sites run the most recent version of WordPress, and there are less than 20 contributors each.

**Comment by ntsekouras** [comment] 2020-10-08 10:35
Hey @ChrisKellyBonhill - thanks for reporting this.

I tested it now and it seems that when you have not typed anything there, it prefetches only 10 authors. If you start typing though it fetches results based on your input. So if you type any `missing` author from the initial list, it should be there.

Can you verify this and close this issue? I think an alternative to prefetch all users doesn't seem optimal and I believe it was that way until recently.

**Comment by nickpagz** [comment] 2020-10-16 18:41
Came across this issue today as well. Seems only a handful of the total authors are pre-fetched, like 11 out of 20. And searching for the missing ones does NOT fetch any additional results.

**Comment by ntsekouras** [comment] 2020-10-17 15:46
Hey @nickpagz - can you share a bit more information on that, as in my case there was no problem. My testing environment though was without other plugins, besides `WooCommerce` and my language was English. Does your site has authors in another language and/or maybe some punctuation? I haven't checked the code for the handling of these, but sometimes are the cause for problems.

**Comment by nickpagz** [comment] 2020-10-17 20:32
Hi @ntsekouras , actually, I added this here as I wasn't sure if the issue was related to gutenberg, or an issue on WordPress.com, as that's where I'm seeing the issue. So in that case, there really is no other plugins to speak of, only that it happens in gutenberg, and not in the classic editor.
It may be an issue with the WordPress.com interface, but the team is still trying to figure that out.

**Comment by annezazu** [comment] 2020-10-26 23:11
@nickpagz any update here on the root problem? If it is indeed related to WordPress.com's setup, please close this issue out. Thank you!

**Comment by talldan** [comment] 2020-12-16 04:28
Closing due to a lack of response. If it becomes possible to establish a way to reproduce this, it'd be appreciated if the bug report template could be used when filing an issue.

**Closed by talldan** 2020-12-16 04:28 UTC
Labels: [Status] Needs More Info
