### ISSUE TITLE
Block Patterns break

### ISSUE THREAD

**Issue by Horttcore** [WordPress/gutenberg#27290] opened 2020-11-26 08:49 UTC
**Describe the bug**
When I want to add a block pattern, the editor breaks

**To reproduce**
Press + icon
Switch to patterns

**Expected behavior**
Seeing all registered block patterns

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Gutenberg version: 9.4.1

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome / Firefix
 - Version: current stable

**Error**
```
TypeError: e.categories.map is not a function
    at https://***/app/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30:1877
    at https://***/app/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30:2163
    at Array.sort (<anonymous>)
    at https://***/app/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30:2136
    at mountMemo (https://***/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:15577:21)
    at Object.useMemo (https://***/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:15873:18)
    at useMemo (https://***/app/plugins/gutenberg/vendor/react.af754d50.js:1607:23)
    at is (https://***/app/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30:2114)
    at renderWithHooks (https://***/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:14938:20)
    at mountIndeterminateComponent (https://***/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:17617:15)```

**Context**
WordPress Bedrock Setup

**Comment by talldan** [comment] 2020-11-27 03:03
Thanks for reporting, the cause is that `categories` seems to now be required for patterns. This was previously reported at #27249, so I'll close this issue as a duplicate.

**Closed by talldan** 2020-11-27 03:03 UTC
