### ISSUE TITLE
Post Preview: Popover doesn't go away

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#20512] opened 2020-02-27 20:32 UTC
**Describe the bug**
When clicking the "Preview externally" link to view the page in the browser, then coming back to the page, the Post Preview dropdown does not go away. Even when clicking outside the popover, it doesn't go away.

**To reproduce**
1. Create a page.
2. Click the Post Preview dropdown and select the "Preview externally" option.
3. Return back to the editor and notice the popover hasn't disappeared yet.
4. Try clicking outside the popover and notice that it doesn't disappear still.

**Expected behavior**
I expect that as soon as I click the "Preview externally" option, the popover should disappear.

**Screenshots**

![2020-02-27 12-24-29 2020-02-27 12_25_46](https://user-images.githubusercontent.com/617986/75484087-f6298180-595c-11ea-870a-79dbfc2ce7ef.gif)

**Desktop (please complete the following information):**
 - OSX
 - Firefox

cc @tellthemachines

**Comment by youknowriad** [comment] 2020-02-27 21:12
Duplicate of #20404

**Closed by youknowriad** 2020-02-27 21:12 UTC
Labels: General Interface, [Type] Bug
