### ISSUE TITLE
Can't set global background color for Post Template

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#59455] opened 2024-02-29 05:35 UTC
### Description

Trying to set a background color for the Post Template block in global styles has no effect due to some overly-specific styling [in the block CSS](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/style.scss#L9). 

That was added in #37941 as a workaround for global styles for the List block bleeding into any other block that uses a `ul` (the same problem stands un-worked-around in the Navigation block)

The sustainable solution here would be to add a classname to the List block so we can attach global styles to it without contaminating other blocks with lists in their markup. My suggestion is revisiting #12420. Cc @carolinan who did some work on it previously!

### Step-by-step reproduction instructions

1. In global styles panel, under blocks > Post Template, try adding a background color.
2. Save and verify that it has no effect in the editor or in the front end.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment] 2024-05-09 10:39
I just came across this today.

It looks as if the  `.wp-block-post-template.wp-block-post-template` CSS rule is overwriting the global styles block rule `:where(.wp-block-post-template)`:

```css
.wp-block-post-template.wp-block-post-template {
    background: none;
}

:where(.wp-block-post-template) {
    background-color: var(--wp--preset--color--foreground);
}
```
This change —

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/style.scss#L8-L11

— was introduced a couple of years ago in https://github.com/WordPress/gutenberg/pull/37941 but it seems to deliberately unset background colors.

I'm guessing we could delete it now that the Post Template block has color supports? @jasmussen @ntsekouras if you can remember that far back 😄

**Comment by tellthemachines** [comment] 2024-05-10 01:37
Good timing, I had fixing this on my list for today now that #56469 is merged 😄

**Comment by ntsekouras** [comment] 2024-05-10 02:38
>I'm guessing we could delete it now that the Post Template block has color supports? @jasmussen @ntsekouras if you can remember that far back 😄

Yeah, the reason was mainly coming from the `list block`, but with https://github.com/WordPress/gutenberg/pull/56469 merged the problem is not there. 

I'm not sure whether we should remove it or adjust it a bit, because in general if theme devs add styles for `ul`, I don't think they would expect to affect Query Loop block too.

**Closed as completed** 2024-05-10 03:54 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] List, [Block] Post Template

**Comment by tellthemachines** [comment] 2024-05-10 03:57
> I'm not sure whether we should remove it or adjust it a bit, because in general if theme devs add styles for `ul`, I don't think they would expect to affect Query Loop block too.

There are multiple blocks using list elements; Navigation is another one. I think theme devs usually take them into account when styling lists, so it shouldn't be a problem.
