### ISSUE TITLE
Button block appender not working after update 6.1

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#45506] opened 2022-11-03 07:30 UTC
### Description

Hi,

I am experiencing an issue with the button block appender which I already stated here: https://github.com/WordPress/gutenberg/issues/45497 and here https://core.trac.wordpress.org/ticket/56965.

Now I just did a fresh install of WordPress 6.1 with the Twenty Twenty-Three theme and this issue still seems to persist.

Therefor I'm creating this new bug report since I think this is an issue on its own (different from #45497).

### Step-by-step reproduction instructions

- Clean/fresh install of WordPress 6.1
- Navigate to the site editor
- Select a template to edit (in this example I clicked on the "single" template to edit)
- Click on the "footer" template part
- Add a "columns" block inside the "footer" template part (it seems this is essential to reproduce the problem, outside of a template part it seems to work fine)
- Save your changes
- Refresh the page
- Scroll down to the block you just added (columns block)
- Try to click on the button block appender which appears inside the "column block"
- Nothing happens, can't add new blocks (seems like pointer-events:none; gets attached to the button block appender while it shouldn't?)

### Screenshots, screen recording, code snippet

![Scherm­afbeelding 2022-11-03 om 08 24 03](https://user-images.githubusercontent.com/117315486/199666639-fe6c28ce-bae0-49d2-941e-26999fe43295.png)
![Scherm­afbeelding 2022-11-03 om 08 24 30](https://user-images.githubusercontent.com/117315486/199666643-837a92c5-563f-4f33-871b-b845063f46ee.png)

### Environment info

- Clean/fresh WordPress 6.1 install with default Twenty Twenty-Three theme (no Gutenberg plugin used)
- All browsers
- All devices

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-11-03 18:45
Moving to the 6.1.1 board to be triaged.

**Comment by t-hamano** [comment] 2022-11-04 17:15
I have confirmed that this problem is not reproduced in the latest Gutenberg.
And this problem seems to have been unintentionally resolved in PR #44865.

By comparing before and after this commit is applied, we should be able to see that this PR has solved the problem.

- `git checkout 705d783`: Reproduced
- `git checkout d50e613`: Not reproduced

![gutenberg_45506](https://user-images.githubusercontent.com/54422211/200036471-a87d3360-186a-482a-9faf-0d2457e14b89.png)

@youknowriad 
Could you please advise if this PR should be backported to WP6.1?

**Comment by youknowriad** [comment] 2022-11-04 17:26
That PR is a bit impactful as it changes how useDisabled works. So our options are either:

 - Backport the PR and test properly (so far I didn't see any downsides to the PR)
 - Come up with a fix for the old implementation of useDisabled. (if that's even possible).

I'd suggest trying the second approach quickly first and if there's nothing obvious, backport that PR.

**Comment by t-hamano** [comment] 2022-11-08 12:44
Thanks for the advice, @youknowriad.

> Come up with a fix for the old implementation of useDisabled. (if that's even possible).

I found [a comment](https://github.com/WordPress/gutenberg/pull/40631#discussion_r858964409) related to this issue regarding some of the changes in #40631.

> This is another addition in this PR. Basically any clickable item inside the disabled element is now "non clickable"

As this comment indicates, removing the changes in this area will resolve this issue. However, the `useDisabled` hook is very complicated for me and I can't decide if this is the right way to do it 😅

**Comment by annezazu** [comment] 2024-09-06 03:08
Closing this out as the PR has since been backported into Core just by virtue of our release process in 6.2 per this tracking issue: https://github.com/WordPress/gutenberg/issues/47187

**Closed as completed by annezazu** 2024-09-06 03:08 UTC
Labels: [Type] Bug, [Feature] Inserter, [Package] Block editor
