### ISSUE TITLE
Post categories checkbox inputs issue

### ISSUE THREAD

**Issue by rthvanesa** [WordPress/gutenberg#17895] opened 2019-10-11 08:38 UTC
**Tested with WP 5.3-beta3**
When editing the post, I've noticed that category checkbox inputs don't store categories' ids in the checkbox value attributes, as they did before. The value attribute is always '1':
`<input id="inspector-checkbox-control-3" class="components-checkbox-control__input" type="checkbox" value="1" checked="">`
![categories](https://user-images.githubusercontent.com/7516117/66636644-4d32f200-ec1a-11e9-84c8-fe239158e81c.png)

1. Edit one post
2. See the categories checkbox list in the sidebar

**Expected behavior**
Category's id should be stored.

**Comment by rthvanesa** [comment] 2019-11-02 12:26
Is there any update on this? I consider it to be a bug introduced in the beta versions of WP 5.3.

**Comment by FeIix** [comment] 2021-03-01 13:11
Same problem.

Why change the behaviour of such a critical thing ?

**Comment by skorasaurus** [comment] 2021-05-26 16:21
I went back and checked and saw that the categories value has always been stored as '1'
(There have been two edits for that particular line of code - https://github.com/WordPress/gutenberg/commit/c1d4497bf0a9c30bed9a020d2ddc777e4494b5e4 
and 
https://github.com/WordPress/gutenberg/blame/a12ac00165d5c20d8cf2d0651e0c4eb6da80a854/packages/components/src/checkbox-control/index.js 

(Maybe a different component was used back then?)

**However**, I was able to reproduce this as you stated, in Wordpress 5.1 where the categories' values were unique and matched their term_id. 

![image](https://user-images.githubusercontent.com/955351/119695978-b7fb6600-be1c-11eb-9b8e-4412f86b3fc6.png)


To reproduce: 

install wordpress 5.1. 
create new post; 
go to post side bar, 
create categories (if necessary); 
inspect

**Comment by FeIix** [comment] 2021-05-26 16:36
I think it's a change introduced by gutenberg itself since its beginning, if I enable the classic editor, the ids are back, even in the last wp version

**Comment by jordesign** [comment] 2023-08-16 05:21
With no further discussion on this, and the fact it seems part of Gutenberg generally, I'm going to close this issue. Feel free to re-open with further re-testing and details if needed

**Closed by jordesign** 2023-08-16 05:21 UTC
Labels: [Feature] Document Settings, [Feature] UI Components
