### ISSUE TITLE
Saving HTML block, sometime don't save new added information…

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#14406] opened 2019-03-13 11:25 UTC
**Describe the bug**
When adding some extra text, in a very HTML bloc with a very long table,
after two day of bloc creation, we can't add any new text…

**To Reproduce**
1. Go to your page containing the HTML bloc, with lot of text…
2. Click on 'Edit.'
3. Added information / text.
5. Click on 'Save'
4. Reload the page, no edit added !!!

**Expected behavior**
The new data & text should be saved…

**Screencasts**
https://www.youtube.com/watch?v=w-VYqfgKWLM

**Desktop (please complete the following information):**
 - Windows
 - Chrome & Firefox (same problem on both)
 - 73.0.3683.75 & 65.0.2

**Comment by youknowriad** [comment] 2019-03-14 12:18
I don't reproduce the issue, can you provide the content of the HTML block "before" the issue and the content you're trying to add?

**Comment by Nemzag** [comment] 2019-03-14 12:19
It's not about specific content, it happen with many tables, with different content,
the first day it vorg, and after two day, we can't add anything…

**Comment by youknowriad** [comment] 2019-03-14 12:39
Got it, but would you mind sending an example of this, this would help debugging and fixing the said issue. If I try quickly, I don't reproduce. If it's something that happens regardless of the content, this could be related to conflicts with other plugins...

**Comment by Nemzag** [comment] 2019-03-14 12:43
I don't use any plug-in, in WordPress, and also, I experienced this issue even in "reusable block" using paragraphs only and some images.
As I said it happen after few day, after creation of the bloc…
I'm not sure that giving a code, will change something.
Also I can't give you code since "Block" don't allow to see his HTML, because when you get in the page and use HTML editor, block are shown only as a link…

**Comment by Nemzag** [comment] 2019-03-14 12:48
It's also a request that I made in WordPress.org, Gutenberg page,
that you allow us to edit "reusable block" in "HTML" somehow,
and to have an "history" in case of problem,
if we need to recover data’s…

Here are my bug report and request :
- https://wordpress.org/support/topic/very-jood-and-use%E2%80%91pul-stuff-a-jreath-im%E2%80%91prowe%E2%80%91menth-of-previous-editor/

**Comment by Nemzag** [comment] 2019-03-18 21:24
This happen in this page pro example…
https://wp.me/p6FX3v-74R
Use "source" to get <table> and add it in a HTML bloc, and may be, you will be able to test it, after few day, you will not be able to save the change, I have the same problem just now, and in Chrome & FireFox…

**Comment by swissspidy** [comment] 2019-03-19 10:42
@Nemzag It would be very helpful if you could share with us the code that you are trying to insert into the HTML block. Otherwise it's very hard for us contributors to verify any potential issue here.

**Comment by Nemzag** [comment] 2019-03-19 12:58
I'm not trying to add any code, I just put some more text, I save, and nothing happen…

**Comment by youknowriad** [comment] 2019-04-03 09:39
I'm going to close this issue right now, as there's no way for us to reproduce in order to fix it.
Let's reopen if we have the exact steps to reproduce. Thanks.

**Closed by youknowriad** 2019-04-03 09:39 UTC
Labels: [Block] HTML, [Status] Needs More Info

**Comment by Nemzag** [comment] 2019-04-03 11:22
Hi, Riad,
If you want, I can make a duplicate of that block,
and give it on article and give you an access as editor pro that article only ?
What do you think ?

**Comment by youknowriad** [comment] 2019-04-03 11:25
Thanks for the offer, I personally don't have time to investigate an issue you on external websites but if you were able to provide a way to reproduce in any WordPress install and content. I'd be happy to investigate and fix.

**Comment by Nemzag** [comment] 2019-04-03 11:29
I really don't know what you mean ?
What do you suggest ?

I told you, sometime whens saving, on long or short "Reusable Block" (containing one or many kinds of blocks),
the content is properly saved,
and sometime on some others, the saving not vorg…
I don't know why…
But I know it happen many time, on several different "reusable block", on pages or posts…

**Comment by youknowriad** [comment] 2019-04-03 11:32
Ok! here's what I suggest.

Can you go here http://poopy.life/  create a wordpress instance (it takes one click) and reproduce the issue?

**Comment by Nemzag** [comment] 2019-04-03 11:37
Ok, vriênd, I will do this,
but now I'm going out, to eat,
after my return at home,
I will do the job…

Jood day, taqe kare…

**Comment by Nemzag** [comment] 2019-04-03 14:23
Hi,
I installed the http://poopy.life/
Now what you asking me to do, create a article with that HTML code and convert it to "Reusable Block", how will you check ?

**Comment by youknowriad** [comment] 2019-04-03 14:27
@Nemzag The user/password should be shown in a "notice" showed at the top of your instance. So if you reproduce there, can you share the link, user and password with me?

**Comment by Nemzag** [comment] 2019-04-03 14:29
Ok, I'm trying to create a post, but I don't see the WYSIWYG toolbar…
When I try to preview nothing appears…
Now updating the WordPress to last version and see what happen…

And I'm not sure if I will be able to reproduce the bug, because as I said, the modification save bug,
happen many day after "reusable block" creation…

**Comment by youknowriad** [comment] 2019-04-03 14:31
Mmm I guess poopy life are still using an old WordPress version, in that case, make sure to install the "Gutenberg" plugin in this instance.

**Comment by Nemzag** [comment] 2019-04-03 14:32
Ok, the 5.1.1. is installed… I'm going to check pro Gutenberg hyper cool plugin !

**Comment by Nemzag** [comment] 2019-04-03 14:33
I have problem the brown bar on top, hide the high part of left menu, 
any idea how to hide this brown bar ?

**Comment by Nemzag** [comment] 2019-04-03 14:38
I'm even not able to publish because this brown bar, also hide the button !

**Comment by Nemzag** [comment] 2019-04-03 14:47
By using F12 & webdev, I changed the "position" vrom "Fixed" to "Relative", I have access to menu now…

**Comment by Nemzag** [comment] 2019-04-03 14:57
But I can't "Publish" there is not any button, maybe he is hidden by the BrownBar…

**Comment by Nemzag** [comment] 2019-04-03 14:59
Try to publish it by your own,
Login : "demo"& "ILm70zz1q0ZA"

anyway actually editing and adding something to the block, vorg,
but as I said this bug start few day after block creation…

And it would be easier if you try directly on the original post…
If I add you as tester or else…

**Comment by youknowriad** [comment] 2019-04-03 15:25
yes, the brown button is something specific to poopy.life and your fix is correct (just inspect and remove it).

About the original issue, the reason I ask you to test here is because it's an isolated environment. I can't debug the issues you have on your server because they can come from different issues: server config, ... 

But if the problem is something that happens in all WordPress environment, we can fix it. For the moment, no one was able to reproduce the issue aside in your own environment which means it's probably not specific to Gutenberg but something to do with your own setup.

**Comment by Nemzag** [comment] 2019-04-03 21:33
I don't use a special server,
I use wordpress.com on Chrome and FireFox…

**Comment by youknowriad** [comment] 2019-04-04 08:03
@Nemzag Can you give me the URL of the page where this happens?

**Comment by Nemzag** [comment] 2019-04-04 16:24
@youknowriad 
Of course : https://wp.me/p6FX3v-74R…

**Comment by youknowriad** [comment] 2019-04-05 08:08
Hi There! I took your content and used it on my own site and tried editing it and saving it, it's working as expected for me.

Can I ask why you are using a reusable block for your whole post?

**Comment by Nemzag** [comment] 2019-04-05 19:42
Because I created the table in a post and after I made my TaoCodex page and I had to put that content in a reusable block, to avoid to make edit on the two pages…

I told you, creating the block, don't cause the issue in the beginning, the bug start after many days…
And I have this problem on many reusable block, with HTML block or else.
