### ISSUE TITLE
Edit Site should edit the template for the current page

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#40211] opened 2022-04-10 21:35 UTC
## What problem does this address?
I find it frustrating when I am viewing a page and want to edit the layout (FSE) and so press "edit site" with the hope that I can edit the current template, but it always take me to the home template.

## What is your proposed solution?
I would like the "edit site" button in the admin bar to edit the template for the current page type, whatever that might be. I feel like if you click edit site from the front-end then you probably want to edit something that you've just seen and not on an unrelated page. This would also help users who don't know what the relevant template is (single vs page for example).

**Comment by Mamaduka** [comment] 2022-04-11 03:19
Hello @BinaryMoon, thanks for contributing.

I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/37850.

**Closed as completed by Mamaduka** 2022-04-11 03:19 UTC
Labels: [Status] Duplicate
