### ISSUE TITLE
Add option to Status & Visibility?

### ISSUE THREAD

**Issue by jsmoriss** [WordPress/gutenberg#6661] opened 2018-05-09 14:45 UTC
I've been unable to find information on how to add an option to the Status & Visibility box. Is this possible? And if not, will it be possible? :)

**Comment by greatislander** [comment] 2018-05-09 14:52
See https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/action-post-submitbox.md.

**Comment by youknowriad** [comment] 2018-05-09 14:53
Duplicate of #6299 closed in #6300

**Closed by youknowriad** 2018-05-09 14:53 UTC

**Comment by jsmoriss** [comment] 2018-05-09 15:02
Oh, wow, well that's a pretty big problem. :) Hopefully https://github.com/WordPress/gutenberg/issues/6299 will be resolved soon. Thanks! :)

**Comment by youknowriad** [comment] 2018-05-09 15:17
Oh sorry my message was not clear enough, it's already resolved https://github.com/ryanwelcher/gutenberg/blob/8efddae270b3cb451b39568fefac87e50f5097e7/edit-post/README.md#pluginpoststatusinfo

**Comment by jsmoriss** [comment] 2018-05-28 19:15
FYI - There seems to be a syntax error in that example...

https://github.com/WordPress/gutenberg/issues/6992
