### ISSUE TITLE
Interface controls: Remember if Settings tab or Style tab was previously opened

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51683] opened 2023-06-20 07:36 UTC
## What problem does this address?
As a Theme creator I want to apply style settings to multiple block very fast.
However, when I have worked on the styles of Block A and then select Block B, automatically the interfaces switches to the Settings of Block B. I then have to click the settings tab again, which can happen multiple times per minute. Let's save that click by remembering what tab (Settings or Styles) I have selected earlier.

## What is your proposed solution?
When having the styles tab open on Block A, and then selecting Block B the styles tab should be opened by default, not the Setting tab.

<img width="275" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/6b7a85ff-becf-4d02-af9e-02d4fc9a5976">

**Comment by Mamaduka** [comment] 2023-06-20 07:41
This is a duplicate of #51104.

**Closed as completed by Mamaduka** 2023-06-20 07:41 UTC
Labels: [Status] Duplicate
