### ISSUE TITLE
Pasting a long text from Word - brings along some errors.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#11012] opened 2018-10-24 14:20 UTC
**Describe the bug**
I copied and pasted a long text from Word.
The first work in each paragraph came above the rest of the paragraph.
I had to click after the first word between the first and second words to remove the space and then press spacebar to add the space again. The word was now moved into on the same line as the first line in the paragraph. I also noticed that the paragraph was also wider.
Actually I noticed just now from copy and pasted text that italic text is seen in Gutenberg as red colored text.

I noticed the text seemed somewhat messy inside the html area.

**To Reproduce**
1. Copy a long text from Word.
2. Paste it into Gutenberg.
3. Do a preview and see if it looks the same as in the backend.

**Expected behavior**
That all the first words would be on the first line of the paragraph. 
That the paragraph would be wider then I first noticed on the frontend.

**Screenshots**
![copy-paste-from-word](https://user-images.githubusercontent.com/5323259/47437313-9e976680-d7a8-11e8-851d-64c687a4fe14.gif)

Backend - Inside Gutenberg:

![screen shot 2018-10-24 at 15 59 53](https://user-images.githubusercontent.com/5323259/47437695-65abc180-d7a9-11e8-9fd8-1a24701529f7.png)

Frontend:

![screen shot 2018-10-24 at 15 59 36](https://user-images.githubusercontent.com/5323259/47437677-5f1d4a00-d7a9-11e8-8c26-fe3afbd93438.png)

HTML edit view:

![screen shot 2018-10-24 at 16 00 04](https://user-images.githubusercontent.com/5323259/47437734-70feed00-d7a9-11e8-931e-e314f916cba4.png)

Btw The below text is from a Word Doc that says Compatibility Mode...

Italic text from Word as seen in the backend:

![screen shot 2018-10-24 at 17 10 40](https://user-images.githubusercontent.com/5323259/47441138-d3f38280-d7af-11e8-98c2-596121938182.png)

Italic text seen as red text on the frontend:
(EDIT: The theme has a red em CSS so that explains the red italic text.)

![screen shot 2018-10-24 at 17 10 22](https://user-images.githubusercontent.com/5323259/47441164-de158100-d7af-11e8-9551-e687a23729b6.png)
 

Backend - HTML edit view:

![screen shot 2018-10-24 at 17 12 24](https://user-images.githubusercontent.com/5323259/47441295-1fa62c00-d7b0-11e8-84d9-29dedf237ca8.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Browser Chrome
 - Version newest

**Additional context**
- Version 4.1 - RC2.

**Comment by rleeson** [comment] 2018-10-28 19:34
I cannot reproduce this issue with different newlines with Word 2016, though on Windows.  Using a document saved in .docx and in .doc (97-2003 compatibility), I tested both newlines with Enter and Shift+Enter in Word.  Enter mapped to a new Paragraph block and Shift+Enter mapped to a <br /> tag. Italics was also properly mapped.

Perhaps there is a line ending issue with Mac specifically, or the document in question has some odd/special formatting.  Can you test the cases using manually created content in a new Word document?  Any Mac with Word testers available?

**Desktop**
- OS: Windows 10
- Browser: Chrome 70

**Additional context**
- WordPress 4.9.8
- Gutenberg 4.1.1

**Comment by paaljoachim** [comment] 2018-10-31 15:59
Here is a word doc the client sent me that shows a lot of red text on the frontend and not in the backend: https://www.dropbox.com/s/tnxz81aenhwh2d3/Luther%20og%20lorten.doc?dl=0

**Comment by spacedmonkey** [comment] 2018-12-05 12:52
I am still getting this issue. It comes up when copying text (of any length, I tried different lengths) from word to gutenberg on a mac. 

** Desktop **
 - OS: 10.14.1
 - Browser Chrome
 - Version 70.0.3538

** Additional context **
- WordPress 4.9.8
- Gutenberg 4.6.1

For me, it removes spaces randomly between words. No pattern that I can see. 

![screenshot 2018-12-05 at 12 49 37](https://user-images.githubusercontent.com/237508/49514548-444ff200-f88c-11e8-994f-ef1030e23f37.png)

Original text
`
Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document.
`

It is extremely common to copy from word into gutenberg, I would like to see a fix for this in 5.0.1 or 5.0.2.

**Comment by designsimply** [comment] 2018-12-05 15:11
Thanks for testing @spacedmonkey! The collapsed spaces issue was filed at https://github.com/WordPress/gutenberg/issues/11588 and reported as fixed in https://github.com/WordPress/gutenberg/pull/12166 which is planned for 4.7 (which should mean 5.0.1).

**Comment by benlk** [comment] 2018-12-06 13:15
For the red text area, can you right-click on the red text, choose "Inspect", and send a screenshot of the web inspector? 
<img width="1011" alt="screen shot 2018-12-06 at 8 13 35 am" src="https://user-images.githubusercontent.com/1754187/49586332-ddcfe000-f92e-11e8-9454-e746ce0c6469.png">

I'm wondering if the redness comes from your site's theme's styles for `em` tags.

**Comment by paaljoachim** [comment] 2018-12-06 19:50
Yeah... after creating the issue I noticed the em css tag is colored red in the theme. So we can skip the red color part and just focus on how the text looks.

**Comment by TymberDalton** [comment] 2018-12-09 08:07
> I am still getting this issue. It comes up when copying text (of any length, I tried different lengths) from word to gutenberg on a mac.
> 
> ** Desktop **
> 
> * OS: 10.14.1
> * Browser Chrome
> * Version 70.0.3538
> 
> ** Additional context **
> 
> * WordPress 4.9.8
> * Gutenberg 4.6.1
> 
> For me, it removes spaces randomly between words. No pattern that I can see.
> 

> 
> It is extremely common to copy from word into gutenberg, I would like to see a fix for this in 5.0.1 or 5.0.2.

I am also having this problem, which is a SERIOUS problem for me. I'm an author and I use my website for promoting my work, including copy/pasting excerpts from my books into Wordpress posts. There seems to be no rhyme or reason to what spaces are eliminated from the text, and in a 1k - 2k excerpt, that's excruciating to have to go through and verify every single line to make sure spaces weren't randomly zapped.

I'm also on a Mac, 
MacBook Air, 10.13.6, 
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
WP 5.0
Gutenberg 4.6.1

**Comment by desrosj** [comment] 2018-12-09 20:51
Closed [Trac-45557](https://core.trac.wordpress.org/ticket/45557) as a duplicate.

**Comment by brazenvoid** [comment] 2018-12-14 06:55
I am on Windows and getting this error.

Firefox v64
WP 5.0.1

```
Received plain text:

 After listening to Yang Chen’s explanation and sermon again, everyone clearly felt the improvement in the speed of their cultivation progress. This was not only the merits of the Spirit Gathering Formation, but the improvement brought on by the cultivation methods as well. _static:104:159080

Processed HTML piece:

 <p>After listening to Yang Chen’s explanation and sermon
again, everyone clearly felt the improvement in the speed of their cultivation
progress. This was not only the merits of the Spirit Gathering Formation, but
the improvement brought on by the cultivation methods as well.</p>
```

**Comment by wazzafab** [comment] 2018-12-19 09:37
Just a note as I see a lot of macs listed here, I'm on a desktop pc, running windows 10. When copying and pasting from word, I get the concatenated words, as well as the second word of some sentences starting with a capital letter. Imagine the pain of editing 2000+ words for spacing, as well as backspacing and replacing those letters. This is completely unacceptable and needs to be rectified asap. This issue as of December 19, 2018.

**Comment by badlydrawnben** [comment] 2018-12-19 18:52
I can replicate this issue too (random words concatenated when pasting from MS Word). On Mac/Chrome and WP 5.01

**Comment by designsimply** [comment] 2018-12-21 00:31
@paaljoachim I tested a few times and couldn't replicate the problem you described where all the first words would be on the first line of the paragraph or where there are shortened line lengths. Because several updates have been made since the time you first posted this issue, would you mind testing again after updating to 5.0.2 and open a new issue for each problem if any are still happening for you?

**Closed by designsimply** 2018-12-21 00:31 UTC
Labels: Needs Testing, [Component] Raw Handling, [Type] Bug

**Comment by paaljoachim** [comment] 2018-12-21 08:48
Hey Sheri. @designsimply 

I have retested with the same text using 5.0.2. The first word comes out as it should alongside the rest of the text. Switching to HTML the text is just as messy as earlier. It would be nice to also get this cleaned up.

Frontend:
<img width="653" alt="screen shot 2018-12-21 at 09 24 14" src="https://user-images.githubusercontent.com/5323259/50332374-393ec800-0502-11e9-8a50-f539f6730dec.png">

To everyone..
This Github issue was created because of the first word showing up on its own line while the rest of the text of the paragraph showing up below it (It would of course also be nice to see the HTML cleaned up but that is a secondary matter that we can perhaps get back to another time). If you have another issue with the pasting of text from Word or other text program then please create another issue listing the specific issue you have with it.

**Comment by designsimply** [comment] 2018-12-21 23:30
It's possible what you are copying has quite a bit of extraneous HTML included and when unnecessary code is stripped out it leaves the text for some lines shorter than others. In a case like that, it is technically copying line breaks as expected I believe.

If you still feel very strongly about wanting to address the line break placement of content copied from Word, may I ask that you please open a new issue for that with a short list of testing steps and screenshots for just that issue since this one is already very long?

**Comment by paaljoachim** [comment] 2018-12-22 07:49
Hey Sheri

I will just leave the HTML line breaks for now, and get back to it another time. The client will very likely send me additional Word file containing articles that I will add into GB so that I will continue to test it out. Then if needed create a new issue specific for that.
Happy Holidays!

**Comment by Warkman** [comment] 2019-01-15 23:32
I just tried pasting from a plain .txt file with the following funkiness.

Pastes fine though when you go do a return it adds another two returns, one for the new line of text but then add one before it too.

I assume since the direction in Guntenburg is "Start writing or type . . ." that it does not want you to copy and paste into it?

**Comment by designsimply** [comment] 2019-01-17 21:22
@Warkman copy and paste is absolutely supported and should be working. For your case, I would like to ask if you would please create a new issue and include details about your WordPress version, whether you have the Gutenberg plugin installed (it's not required unless you are testing bleeding edge changes), note whether you have tested with all plugins temporarily deactivated to rule out a plugin conflict, and please also note which OS and browser version you are using for reference. Thank you!
