### ISSUE TITLE
html Order tag is not supporting by Custom HTML block

### ISSUE THREAD

**Issue by jadhavravindra** [WordPress/gutenberg#16110] opened 2019-06-12 07:56 UTC
**Describe the bug**
When the user tried to display the HTML order list with the help of Custom HTML block, then it will not display the order list with the numbers.

**To reproduce**
Steps to reproduce the issue:
1.Go to gutenberg editor
2. add Custom HTML block
3.insert below code into the HTML block

```
 <ol>
<ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
<ul>
</ol>
```

4.publish it and View the page

**Expected behavior**
Order numbering should be displayed.
Example:
1.Coffee
2.Tea
3.Milk

**Screenshots**
https://www.screencast.com/t/wGMy0eNpSQ

**Comment by swissspidy** [comment] 2019-06-12 08:27
That's not an ordered list.

Correct would be:

```html
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```

So your HTML is wrong and the browser tries to fix it, only keeping the `ul` tags and removing the `ol` tags.

**Comment by jadhavravindra** [comment] 2019-06-12 09:00
Yes I tried both ways,, 
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
that also not working with custom block

**Comment by swissspidy** [comment] 2019-06-12 09:05
Looks like there's no padding for `ul` and `ol` in thee HTML block's preview iframe. That iframe exists as a sandbox. In the frontend it looks good though.

Which is why this is essentially a duplicate of #9129 (outside CSS is not applied to the editor).

Also, thanks for the video, but I cannot watch it without flash player 🙂

**Comment by jadhavravindra** [comment] 2019-06-12 09:48
Okay, I have updated the video.  You can check below one now for more details. 
![2019-06-12_15-09-09](https://user-images.githubusercontent.com/31184005/59341348-51f7a000-8d25-11e9-9729-add77b2b50d8.gif)!

**Comment by swissspidy** [comment] 2019-06-12 09:56
Awesome, thanks!

Definitely a duplicate of #9129 in that case. Please follow that issue for any progress.

As I mentioned, that whole HTML block preview in the editor is in a sandboxed iframe, so it's not as trivial as it seems to add the necessary styling there.

**Closed by swissspidy** 2019-06-12 09:56 UTC
Labels: [Block] HTML, [Status] Duplicate

**Comment by jadhavravindra** [comment] 2019-06-12 10:07
Okay. Thanks.
