### ISSUE TITLE
Mark the Social Links plugin as experimental

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17524] opened 2019-09-23 12:39 UTC
The social links block is a great block but it's also a very recent addition. 
I'm thinking we should give it more time to be used and polished in the plugin before making it available.

I'm proposing that we mark it as experimental (feature flag) in order to avoid including it in the upcoming WordPress 5.3 release.

cc @nicolad @mkaz @jasmussen thoughts?

**Comment by jasmussen** [comment] 2019-09-23 12:45
Sure! No objections. I've tracked 4 tickets to improve around this, with testing and those fixed it'll be a good time to revisit.

**Comment by gziolo** [comment] 2019-09-23 12:58
We identified also some potential performance issues when connected with REST API logic as explained in this track issue: https://core.trac.wordpress.org/ticket/48079. It needs to be further investigated and fixed in core if confirmed.

**Comment by mkaz** [comment] 2019-09-23 13:23
I'm fine marking as experimental, especially if there are potential issues. I'd rather get it in WP 5.3 but not if its going to problematic.

@gziolo is the performance issue related to Social Links, or that fact that it introduced a larger number of blocks making it more obvious?

**Comment by nicolad** [comment] 2019-09-23 13:25
I see that there are 2 experimental editor setting: `__experimentalEnableLegacyWidgetBlock` and `__experimentalEnableMenuBlock` .
Not 100% sure if `__experimentalEnableLegacyWidgetBlock` is the most appropriate flag for this case.

**Comment by jasmussen** [comment] 2019-09-23 13:31
> I'm fine marking as experimental, especially if there are potential issues. I'd rather get it in WP 5.3 but not if its going to problematic.

Well this will still be testable in 5.3 no? You just have to fiddle ...

**Comment by gziolo** [comment] 2019-09-23 13:37
> @gziolo is the performance issue related to Social Links, or that fact that it introduced a larger number of blocks making it more obvious?

It's an existing issue which gets more prominent since there are now 37 new blocks registered on the server.

**Comment by mkaz** [comment] 2019-09-24 22:20
@gziolo @youknowriad @jasmussen Would it be worthwhile to scale the number of child blocks down to 8 of the top social sites and then enable a filter or hook that allows people to extend to add more?

It kinds delays the issue of too many blocks during registration, but its a useful feature that would be great to launch and make available to users.

Top site icons I would include:

1. WordPress
2. Facebook
3. Instagram
4. Twitter
5. YouTube
6. Snapchat
7. Email
8. RSS

Open to suggestions.

**Comment by jasmussen** [comment] 2019-09-25 07:22
> Would it be worthwhile to scale the number of child blocks down to 8 of the top social sites and then enable a filter or hook that allows people to extend to add more?

From what I gather there are two reasons to mark this experimental.

1. It could benefit from (#17275, #17276, #17277, #17278) being fixed. None of those I consider blockers for launch, but still.
2. There's [a bug in the editor itself](https://github.com/WordPress/gutenberg/issues/17524#issuecomment-534102280) which moans over the amount of blocks registered. Since this registers a lot, and is new, it's the first on the chopping block.

Both of those are sort of "unfair", but such is software development. Triage literally means to select the patients that live. But in this case, with the added benefit that the Social Links block _will_ live — it's just postponed. 

In case the magic that Marcus proposes is quick to implement (probably means fixing #17278 right?) and, then I'd be super happy that we can create a canonical social links block. However if triage demands this one to be punted for the WordPress patient to live, I will absorb that and engage my patience :)

**Comment by youknowriad** [comment] 2019-09-25 07:25
I'm adding @mtias to the discussion. 

The reason I think we should give it more time is not just about the issue @gziolo discovered. The main reason is I feel we shouldn't rush it because we may want to do breaking changes

 - Implementing extensibility for the block might require breaking existing content
 - Also, we've been thinking whether this could be a good first "Core" block that lives in the block directory instead of being bundled to experiment with that.

**Comment by jasmussen** [comment] 2019-09-25 07:26
I'm totally fine with that :)

**Closed** 2019-11-19 13:40 UTC
Labels: [Block] Social, [Feature] Blocks, [Priority] High
