### ISSUE TITLE
Widget screen: No reaction when clicking the top left Inserter button

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25176] opened 2020-09-09 06:17 UTC
**Describe the bug**
The inserter button in the top left area of the Widget screen shows no reaction when clicking it.
I also noticed an error code in the Chrome console.

**Environment**
Twenty Twenty theme.
Gutenberg 8.9.3 activated.
Chrome

**To reproduce**
Go to the Widgets screen and click the top left inserter button.

**Expected behavior**
I expect to open the full Inserter panel and be able to see all the blocks and widgets.

**Screenshots**
I opened the Chrome Console.

![Screen Shot 2020-09-09 at 08 14 26](https://user-images.githubusercontent.com/5323259/92561495-977e8200-f274-11ea-87d5-aca68cb11fa1.png)

Noticed this error:
![Screen Shot 2020-09-09 at 08 16 06](https://user-images.githubusercontent.com/5323259/92561578-bbda5e80-f274-11ea-8fbb-47106470d661.png)

@draganescu

**Comment by carolinan** [comment] 2020-09-09 11:58
I am able to reproduce this with a different theme with Gutenberg 8.9.3 activated.

**Comment by kevin940726** [comment] 2020-09-10 16:00
I thought this is intended? One has to first click on the widget wish to insert to, then the inserter button will be enabled.
Maybe we should make it more clear though 🤔 , or am I missing something obvious?

**Comment by draganescu** [comment] 2020-09-11 11:20
Yes, this is an UX bug. (the console error is a problem, but it is not causing the button to not work)

@mapk what is the best solution here?

Having to click into one of the widgets areas to enable the inserter to work is counter-intuitive. It is not covered in the last update on the [overall design](https://github.com/WordPress/gutenberg/issues/24561#issuecomment-681167207) and neither in the original comment:

> There is still some ambiguity around which area the Global Block Inserter should add a block to.

**Comment by paaljoachim** [comment] 2020-09-11 12:14
Hey Andrei @draganescu 

I just tested the functionality in a page when no block is selected. Clicking the Inserter and then clicking a block automatically adds the block to the bottom of the page.

Regarding the Widgets screen one can adjust the behavior a bit. Clicking a block in the inserter panel can automatically add the block to the first widget area. This means that user does not need to first select a widget area, but here we assume at the user wants to add it to the first widget area. If they want it anywhere else they can click and drag it to the correct area.

I just tested and drag and drop is not working. So I made this issue for it: https://github.com/WordPress/gutenberg/issues/25243

**Comment by paaljoachim** [comment] 2020-09-11 12:27
Another option but I am not sure that I like it though.... as it might not be accessible or contain a good UX flow.
When no widget area is selected and one clicks the Inserter and clicks to add a widget/block that a dialog box/notification/etc shows up asking the user where to add the widget/block with a drop down of areas. 

In the older widget screen one could do so:
<img width="284" alt="Screen Shot 2020-09-11 at 14 26 31" src="https://user-images.githubusercontent.com/5323259/92925466-d2321700-f43a-11ea-9d76-316b85aa58dc.png">

**Comment by kevin940726** [comment] 2020-09-11 12:46
Maybe automatically select the first (or last, or lst edited, or whatever) widget and have a visual indicator would be simpler and more accessible?

**Comment by paaljoachim** [comment] 2020-09-11 13:04
That is a good idea Kai!

The scenario.
Today as one enters the widget screen the first widget area is open. In a sense this is already selected.
![Screen Shot 2020-09-11 at 15 02 54](https://user-images.githubusercontent.com/5323259/92928808-ecbabf00-f43f-11ea-94b5-726fba78217a.png)

As can be seen above the Footer #1 is open and thereby preselected when entering the Widget screen. Clicking the Inserter at the top left should automatically add widgets/blocks to the already selected Widget area.

**Comment by mapk** [comment] 2020-09-11 14:46
>@mapk what is the best solution here?

Thanks for the ping! The solutions discussed above by @paaljoachim and @kevin940726 are great starting points. I think we need to consider two flows.

1. When the page first loads.
2. When everything has been deselected.

### What the page first loads
The first widget area should be focused when the page loads. This means there will be a blue outline around it visually indicating it as the target area allowing the Inserter `+` to be clickable. 
I don't think an expanded area is selected by default because they can all be expanded at the same time by the user. But if the first area is focused, great!

![area 1](https://user-images.githubusercontent.com/617986/92937471-384d7880-f400-11ea-8f54-7ddd3e72caae.png)

### When everything has been deselected
This is a lot trickier. While I like Paal's idea of selecting an area to add to, it becomes a lot of UI for a small space which can be overwhelming. Can we automatically select the first area when the Inserter is clicked? The Inserter panel would open, and the first area would highlight with the blue border.

- When nothing is selected, both the Inserter panel and Inspector panel are hidden.

![opening](https://user-images.githubusercontent.com/617986/92939495-ba3ea100-f402-11ea-8ef2-24328e3f6e69.gif)

**Comment by adamziel** [comment] 2020-09-15 13:50
I think it is possible to specify the default widget area that's in effect even when nothing is selected. The auto-selection when inserter is clicked would still be a nice touch as it would clear up the expectations. 👍

**Comment by adamziel** [comment] 2020-09-16 14:59
The issue was solved by #24908. What's missing is selecting the block while the inserter is open. I have some concerns related to that @mapk. Normally when a block is selected is means it's focused and you can interact with it using the keyboard (think tab, arrow keys, enter). In your prototype it's not obvious when you use the keyboard - will it affect the inserter? The block? If I navigate to "Search for a block" does it mean it's going to have the blue selection border just like the widget area? How do I differentiate between the selection inside of the inserter and the "active" widget area?

I checked what does the global inserter do in the post editor, and it indicates the placement of the new block using a blue line like on the screenshot below - I think we should use the same pattern here:

<img width="1171" alt="Zrzut ekranu 2020-09-16 o 16 58 46" src="https://user-images.githubusercontent.com/205419/93355053-f4160a00-f83d-11ea-8100-a288552ccb72.png">

**Comment by mapk** [comment] 2020-09-16 15:10
@adamziel good call on the keyboard navigation. So it appears that pattern works when a block is selected. We still need a way to indicate which area that block would be added to when nothing is selected. 

![placement](https://user-images.githubusercontent.com/617986/93356395-f6537680-f7f3-11ea-9aa3-ed5f6ae9d6b9.gif)


The post editor works because it just add it to the bottom of the document. But if we have multiple areas open, but nothing selected, it's still not clear where the new block would be added.

I'll look at this today.

**Comment by draganescu** [comment] 2020-09-17 07:17
Closed by #24908.

**Closed by draganescu** 2020-09-17 07:17 UTC
Labels: [Feature] Widgets Screen, [Type] Bug
