### ISSUE TITLE
Navigation block submenu dropdown spacing styles overridden by List block

### ISSUE THREAD

**Issue by lushkant** [WordPress/gutenberg#57620] opened 2024-01-06 13:04 UTC
### Description

I found this bug while working with the Navigation block dropdown submenus. Specifically, the spacing styles of the dropdown menu gets overridden (at the front-end only, works fine in the editor) by List block styles when there is a submenu background color set in Navigation block. 

These are the styles coming from the List block -
```
ol.has-background, ul.has-background {
    padding: 1.25em 2.375em;
}
```

These are the styles that should take effect but gets overridden by the List block styles mentioned above-
```
.wp-block-navigation ul, .wp-block-navigation ul li {
    list-style: none;
    padding: 0;
}
```

This issue can be reproduced in any core theme, and I have tested it with TwentyTwentyFour to TwentyTwentyOne themes.

### Proposed Solution - 

To add preceding values in Navigation block styles -

```
.wp-block-navigation ul.has-background {
    padding: 0;
}
```

I have tested this and it works without breaking any existing behavior.
I'll now go on to add a PR, I'm open to making any changes in it if there's an issue with the current solution.

### Step-by-step reproduction instructions

1. Go to the block editor screen on any page.
2. Add a Navigation block, along with a submenu and dropdown items.
3. Set the Submenu overlay Background, Text color in the Navigation block (Take a look at the screenshots below for ref.)
4. Make sure to add/have a List block somewhere in that page.
5. Save/publish and visit live preview.
6. Hover/click over the submenu and see the dropdown taking additional spacing from List block.

### Screenshots, screen recording, code snippet

1. Screencast of the issue -
https://www.youtube.com/watch?v=-PiupdsKqxU&ab_channel=KrishnaisIndiehacking

2. Screenshot from the block editor where dropdowns work as expected - 
<img width="1481" alt="Screenshot 2024-01-06 at 6 14 37 PM" src="https://github.com/WordPress/gutenberg/assets/18240138/705d38ec-f72d-4639-8d56-c5095f2282d6">

3. Screenshot from the front-end/live preview where the issue is present -
<img width="1496" alt="Screenshot 2024-01-06 at 6 14 05 PM" src="https://github.com/WordPress/gutenberg/assets/18240138/97217698-0fe7-47ef-8ba1-2d74d8e22547">

4. Style settings tab reference -
<img width="283" alt="Screenshot 2024-01-06 at 6 18 19 PM" src="https://github.com/WordPress/gutenberg/assets/18240138/1c031feb-8623-41ac-8124-3ec6b25d8b0d">

### Environment info

- WordPress v6.4.2
- Gutenberg v17.4.1
- Themes: Any Core Theme
- Arc Browser v1.21.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment] 2024-01-07 22:05
I think this is a duplicate of:

- https://github.com/WordPress/gutenberg/issues/50486

Also related:

- https://github.com/WordPress/gutenberg/issues/12420


A longer-term fix might be to add a classname to the List Block. See:

- https://github.com/WordPress/gutenberg/pull/56469

**Comment by talldan** [comment] 2024-01-08 03:41
Closing as a duplicate

**Closed as not planned by talldan** 2024-01-08 03:41 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Navigation

**Comment by lushkant** [comment] 2024-01-08 03:48
@talldan @ramonjd My bad I searched everywhere for Navigation block related issues but should have also looked at List block issues. I'll remember to do so next time.

Still can you guys point me how to find if related/similar issue is already present, I mean is there any other rather efficient way to go at finding it?

**Comment by talldan** [comment] 2024-01-08 04:47
It is difficult with so many issues on the repo. I don't really have any good advice other than trying different labels and search terms. Often I know about the existence of duplicates from reading or being involved in the discussion on the other issue.

**Comment by lushkant** [comment] 2024-01-08 04:50
> It is difficult with so many issues on the repo. I don't really have any good advice other than trying different labels and search terms. Often I know about the existence of duplicates from reading or being involved in the discussion on the other issue.

Makes sense, I will try to be more involved as well in the coming days so that I don't end up posting a duplicate again. 

Thank you for your help Daniel 😃
