### ISSUE TITLE
Blocks adding rogue code

### ISSUE THREAD

**Issue by robjaykes** [WordPress/gutenberg#13107] opened 2018-12-27 10:09 UTC
I created a block of text and duplicated it. In the new block I changed the text only. The block added a line after 'your'. Nothing I could do would get rid of that unwanted line break.

The new block threw an error so I had to recreate. 

Upon looking at the code (below) I noticed there has been an unwanted injection of &nbsp;.

I manually removed the &nbsp; code and all is well.

`<p style="color:#ffffff" class="has-text-color has-background has-large-font-size has-primary-background-color"> -&nbsp;<strong>£800 for your website.&nbsp;You&nbsp;are&nbsp;responsible&nbsp;for&nbsp;updates,&nbsp;hosting&nbsp;and&nbsp;management.</strong></p>`

**Comment by iseulde** [comment] 2019-01-29 15:07
Duplicate of #13198.

**Closed by iseulde** 2019-01-29 15:07 UTC
Labels: Needs Testing, [Component] Raw Handling, [Component] Rich Text
