### ISSUE TITLE
Block toolbar dropdown menu unable to scroll.

### ISSUE THREAD

**Issue by delowardev** [WordPress/gutenberg#39933] opened 2022-03-31 08:50 UTC
### Description

Sometimes block toolbar dropdown menu doesn't display the scrollbar, so it makes it difficult to reach the last 1/2 items. Ideally, it should display the scrollbar whenever an item gets out of the screen/viewport.

Please check the video: 

https://user-images.githubusercontent.com/17360543/161015053-0a063156-53ae-4d1e-9fd8-2f01363b89db.mov

### Step-by-step reproduction instructions

https://share.vidyard.com/watch/ASe2n1Etqj3isGnr7p3HTt?

### Environment info

- Gutenberg: 12.9.0
- WordPress: 5.9
- Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-04-11 17:49
👋 - I tried to reproduce in Chrome and FF, but couldn't. Have you noticed some specific series of actions or anything that might help test it?

**Comment by ntsekouras** [comment] 2022-04-14 14:01
I'm closing this as a duplicate of: https://github.com/WordPress/gutenberg/issues/40224. This issue is older but there was an extra comment there about a related issue, and there are no other comments here.

Thanks for reporting @delowardev!

**Closed as completed by ntsekouras** 2022-04-14 14:01 UTC
Labels: [Type] Bug, Needs Testing
