### ISSUE TITLE
Text Highlight: Dashes in paragraphs with color appears longer on the live page

### ISSUE THREAD

**Issue by kspilarski** [WordPress/gutenberg#64237] opened 2024-08-04 12:24 UTC
### Description

A dash in a paragraph block that has color applied to it appears longer on the live page. 

### Step-by-step reproduction instructions

1. On a page or post, add a text with dashes in between letters.
2. Highlight the dash, in the toolbar More > Highlight > Text color add a color to the dash. 
3. Publish / Save and compare the text with the dash on the site editor and live page. 

### **Editor:**

The dashes with and without color appear the same size in the editor: 

**Twenty Twenty four:** 

<img width="1133" alt="Screenshot 2024-08-04 at 13 48 59" src="https://github.com/user-attachments/assets/7787910f-0425-4760-ad57-399d97bdb69b">

**Twenty Twenty:** 
<img width="1093" alt="Screenshot 2024-08-04 at 14 18 15" src="https://github.com/user-attachments/assets/613a3076-57f4-4c97-9d01-34141cc950a7">

<hr />

### **Live page:**

On the live page, the dashes with color appear longer than the dashes without color applied to them: 

**Twenty Twenty four:** 

<img width="915" alt="Screenshot 2024-08-04 at 13 49 07" src="https://github.com/user-attachments/assets/e1d8c938-43e2-479e-94d5-7aed79de040b">

**Twenty Twenty:** 
<img width="1197" alt="Screenshot 2024-08-04 at 14 18 20" src="https://github.com/user-attachments/assets/a425c67a-663e-4e38-8ac5-5572b738cc56">

<hr />

User report https://wordpress.org/support/topic/change-the-colour-of-only-one-character-in-the-site-title/ 

### Environment info

- WordPress 6.6.1
-  Gutenberg 18.8.0
- Tested with Twenty Twenty four, Twenty Twenty  

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment] 2024-08-04 14:02
Thanks for the report.

After investigating this issue, I found that it is most likely caused by a core function.

For more information, please see this ticket: https://core.trac.wordpress.org/ticket/61817

Therefore, I will close this issue.the report.

**Closed as completed by t-hamano** 2024-08-04 14:02 UTC
Labels: [Type] Bug, [Type] WP Core Ticket
