### ISSUE TITLE
Undo / Redo unreliable with the post title

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12075] opened 2018-11-19 18:35 UTC
Splitting this out from https://github.com/WordPress/gutenberg/issues/5685#issuecomment-439831378 / #10650

#10650 improved a lot the Undo / Redo behavior with regards to RichText.

However, seems the post title is not always included in the undo / redo history. Following the steps listed on https://github.com/WordPress/gutenberg/issues/5685#issue-306271173 there are still cases where the post title is not restored or not removed when undoing / redoing.

Quoting @iseulde:
> I think only blocks are included in the history reducers.

I haven't followed this part of the development but seems to me it's something worth investigating.

**Comment by aduth** [comment] 2018-11-19 19:11
Not sure it's entirely related to what's seen, but it occurs to me that since the title field is "controlled" by editor state, it should have its default Undo/Redo behavior absorbed by the application handler. 

Related discussion: https://github.com/WordPress/gutenberg/pull/10650#discussion_r233936835

**Comment by designsimply** [comment] 2018-11-21 23:47
Tested and confirmed that undo did not affect title changes and that redo took more clicks than expacted using WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.1 on macOS 10.13.6. ([52s](https://cloudup.com/cX9PcTq-Vk9))

**Comment by xy0** [comment] 2019-01-21 20:58
Undo/Redo is also unreliable with List Block as well. I haven't fully had time to test it, but Undo will often times not be able to be Redo'd.

**Comment by aduth** [comment] 2019-02-25 16:12
> Not sure it's entirely related to what's seen, but it occurs to me that since the title field is "controlled" by editor state, it should have its default Undo/Redo behavior absorbed by the application handler.

This should already be happening, looking at the implementation:

https://github.com/WordPress/gutenberg/blob/c8c1381f77c0cf1a2d67b96e5b612db2c4291395/packages/editor/src/components/post-title/index.js#L70-L88

Ideally there'd be some more reliable way to intercept / override the Undo & Redo, but at least for Cmd+Z (Ctrl+Z) and Cmd+Shift+Z (Ctrl+Shift+Z), the behaviors should operate on the store's history.

**Comment by aduth** [comment] 2019-04-24 21:06
This needs specific steps to reproduce. As described in https://github.com/WordPress/gutenberg/issues/12075#issuecomment-467072352 , it's expected the title edits should be reflected correctly in state for coordination by the Undo / Redo behavior, and key commands intercepted.

**Comment by ehti** [comment] 2020-03-05 06:00
We tested this in core editor triage.

Able to replicate the behavior where the title doesn't get deleted when Redoing.

**Comment by ehti** [comment] 2020-03-05 06:03
GIF credit Dan:
![undo-redo](https://user-images.githubusercontent.com/6505293/75952586-f54e9d80-5ed0-11ea-8cdf-c858bc108320.gif)

**Comment by paaljoachim** [comment] 2021-02-21 00:55
Testing with WordPress 5.7 beta 3.

It seems to be working fine.
I will close. If I am mistaken, then the issue can be reopened. 
Please add test instructions to that I can correctly test.
Thanks.

**Comment by paaljoachim** [comment] 2021-02-21 00:58
I noticed that the last letter in the post title was not added back on redo.
So there is still an error here.

**Comment by Mamaduka** [comment] 2022-12-13 10:39
I can still reproduce the issue mentioned in https://github.com/WordPress/gutenberg/issues/12075#issuecomment-595045136. The post title doesn't get deleted during redo.

@paaljoachim, the post title is correctly restored for me on the redo.

## Screencast

https://user-images.githubusercontent.com/240569/207295709-2b4912a6-cdb8-457b-b9f2-be5c18c05603.mp4

**Comment by paaljoachim** [comment] 2022-12-14 01:43
Great to hear George @Mamaduka !
Let's close this issue, and if for whatever reason it needs to be reopened then it can be so.

**Closed by paaljoachim** 2022-12-14 01:43 UTC
Labels: [Type] Bug, [Feature] History

**Comment by Mamaduka** [comment] 2022-12-14 02:41
Sorry, @paaljoachim. It looks like my issue confirmation comment was a little confusing :)
