### ISSUE TITLE
Hook for navigation menu icon

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#45723] opened 2022-11-11 16:46 UTC
I suggest a change in `core/navigation` block.

I think having a hook for changing (customizing) menu icon would be nice. In that way, menu icon could be changed natively, both in admin and front and without depending on "hacks" like `render_block` PHP hook.

**Comment by mtias** [comment] 2022-11-16 12:25
Yep! Closing as duplicate of #37930

**Closed as not planned by mtias** 2022-11-16 12:25 UTC
