### ISSUE TITLE
Block Toolbar Edit Icons inconsistent for Image & Gallery Blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18280] opened 2019-11-05 04:24 UTC
**Describe the bug**
Most blocks that require an image to be uploaded or an external URL to be entered, have an edit icon on their Block toolbar in the shape of a Pencil (<img width="33" alt="screenshot_25" src="https://user-images.githubusercontent.com/2078245/68177417-57a79800-ffdc-11e9-8db1-15a638b477d9.png">).

Here's some examples:
**Audio Block**
<img width="450" alt="screenshot_20" src="https://user-images.githubusercontent.com/2078245/68177453-7dcd3800-ffdc-11e9-9fc9-3018dd688f61.png">

**Cover Block**
<img width="484" alt="screenshot_21" src="https://user-images.githubusercontent.com/2078245/68177460-802f9200-ffdc-11e9-8d4f-f15090c36a88.png">

**Video Block**
<img width="412" alt="screenshot_22" src="https://user-images.githubusercontent.com/2078245/68177463-83c31900-ffdc-11e9-82b7-4d809321bca4.png">

**YouTube Embed**
<img width="431" alt="screenshot_23" src="https://user-images.githubusercontent.com/2078245/68177466-858cdc80-ffdc-11e9-96b1-0d67abf58961.png">

**Vimeo Embed**
<img width="399" alt="screenshot_26" src="https://user-images.githubusercontent.com/2078245/68177623-fdf39d80-ffdc-11e9-8961-2487ad5ac582.png">

The Image Block and Gallery Block are inconsistent with all these other Blocks. The Image block has some sort of 'swap' icon that is too similar to the Change Block Type icon, and the Gallery Block has no icon altogether.

**Image Block**
<img width="651" alt="screenshot_18" src="https://user-images.githubusercontent.com/2078245/68177738-6478bb80-ffdd-11e9-8798-c7c2230f3ffe.png">

**Gallery Block**
<img width="547" alt="screenshot_24" src="https://user-images.githubusercontent.com/2078245/68177760-6d698d00-ffdd-11e9-9565-cdfd51956a92.png">

I realise the Gallery block has _Upload_ and _Media Library_ buttons, but not having an edit icon like all the other blocks, not only makes it incredibly inconsistent, but it forces people to have to pause their workflow to find another way to edit the block. The Edit icon on a Gallery Block should simply do the same as the _Media Library_ button.

Both the Image Block and the Gallery Block should have the pencil edit icon to keep them consistent with all the other blocks.

**To reproduce**
1. Insert image block
2. Insert Gallery block
3. Insert Audio, Cover, Video, YouTube & Vimeo Blocks
4. Compare the Edit icon on each toolbar

**Expected behavior**
Icons that perform the same functionality should be consistent across every block.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Firefox Quantum 70.0.1 (64-bit)
 - Version: WP 5.3-RC3-46639

**Comment by maximebj** [comment] 2019-11-07 10:28
I went here for this. 

I think we should keep the "pen" icon for now for every block. 

For the Gallery block, it's an issue:  After creating a gallery, there is no way to change the pictures.
It works the first time.
Click on "Media Library" and "Edit Gallery". It's ok.

<img width="585" alt="capture 2019-11-07 à 11 26 09" src="https://user-images.githubusercontent.com/1785489/68381275-a4f94600-0151-11ea-8823-d69d17456021.png">

Close Media Library
Click again on "Media Library" 
This time : nothing found...

<img width="926" alt="capture 2019-11-07 à 11 26 30" src="https://user-images.githubusercontent.com/1785489/68381281-aa569080-0151-11ea-91a3-8f5e71fe930c.png">

I think this bug deserves a separate issue. It should really be fixed prior to 5.3 release.

**Comment by mtias** [comment] 2019-11-25 11:51
Duplicate of #18280 and related to #11952.

**Closed** 2019-11-25 12:22 UTC
