### ISSUE TITLE
Edit Site button should open the Site Editor with the current template open

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#38885] opened 2022-02-17 13:42 UTC
### Description

Clicking on the _Edit Site_ button on the top bar always redirects to the same template, without taking into account the template the user was viewing.

### Step-by-step reproduction instructions

0. Enable a block theme (Twenty Twenty-Two, for example).
1. Go to any post or page in your store.
2. In the top bar, press on _Edit Site_.
3. Notice you are redirected to the Site Editor, but the loaded template is _Home_.

Expected behavior:
3. I would expect the template I was in to be loaded by default. Ie, if I was in a post or page, it should load the _Single_ template (or the template that post/page is using).

### Screenshots, screen recording, code snippet

![Kooha-02-17-2022-14-36-41](https://user-images.githubusercontent.com/3616980/154493281-5b54ad6c-65b3-4b96-824e-b3e481b2f917.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-02-17 14:24
Hi, I am closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/37850

**Closed as completed by carolinan** 2022-02-17 14:24 UTC
Labels: [Type] Enhancement, [Feature] Templates API, [Status] Duplicate, [Feature] Site Editor
