### ISSUE TITLE
Theme editor font-size with number creates mismatch between font-size slug and block class

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#31629] opened 2021-05-08 20:13 UTC
When registering a custom font-size that begins with a number in `theme.json`, the CSS output doesn't match the class name.  I tested this with a slug of `2xl`.

The CSS that Gutenberg outputs is:

```
:root { --wp--preset--font-size--2xl: 30px; }

.has-2xl-font-size { font-size: 30px !important; }
```

However, when applying it to a block via the Font Size control under the Typography tab, it adds a hyphen between the `2` and `xl`.  The block CSS class becomes `has-font-size-2-xl` like so:

```
<h1 class="has-2-xl-font-size">Hello, World!</h1>
```

`theme.json` code:

```
{
	"settings": {
		"defaults": {
			"typography": {
				"fontSizes": [
					{
						"slug" : "2xl",
						"name" : "2 XL",
						"size" : "30px"
					}
                                ]
                        }
                }
        }
}
```

**Comment by skorasaurus** [comment] 2021-05-10 18:37
related https://github.com/WordPress/gutenberg/issues/26940

**Comment by annezazu** [comment] 2021-05-17 18:45
@ntsekouras might you be able to share some context here?

**Comment by ntsekouras** [comment] 2021-05-21 18:24
--cc @nosolosw @jorgefilipecosta

**Comment by oandregal** [comment] 2021-05-31 12:39
Thanks for the report @justintadlock Going to consolidate this into https://github.com/WordPress/gutenberg/issues/32347 as the issue is a bit larger than numbers (also affects camelCased slugs).

**Comment by oandregal** [comment] 2021-05-31 15:34
There's a fix at https://github.com/WordPress/gutenberg/pull/32352

**Comment by justintadlock** [comment] 2021-06-15 16:25
Just confirming that #32352 fixed this.

**Comment by justintadlock** [comment] 2021-06-18 17:29
Formally noting that this issue is no longer fixed as of #32742 and #32766.  The first ticket reverted the fix.  The second ticket changed this in a way that does not respect valid, theme-defined slugs.

I have further proposed a compromise that would allow theme authors to address this in their themes: https://github.com/WordPress/gutenberg/issues/32347#issuecomment-863256200

**Comment by skorasaurus** [comment] 2021-08-17 14:27
issue for include this in documentation https://github.com/WordPress/gutenberg/issues/19285

**Comment by skorasaurus** [comment] 2021-11-23 17:59
@justintadlock can you confirm this has been fixed in the current version of Gutenberg; should have been fixed in https://github.com/WordPress/gutenberg/pull/35751 ?

**Comment by skorasaurus** [comment] 2022-02-10 18:09
I'm no longer able to reproduce this as you instructed; the CSS outputs are all now `2-xl`. 
please reopen if you're still experiencing this.

**Closed as completed by skorasaurus** 2022-02-10 18:09 UTC
Labels: [Type] Bug, Needs Testing, [Feature] Themes, CSS Styling

**Comment by coreyworrell** [comment] 2022-05-05 23:56
Noticing issue mentioned here: #34509. I have `16x9` that is converted to `wp--custom--aspect--16-x-9`, which causes issues because we're reading from `theme.json` in PHP for autosuggest for class names as well as variables in Stylus. For PHP I can run the key name through `_wp_to_kebab_case` I suppose, but there is obviously no equivalent in Stylus/SCSS/etc. Not sure if there is any good solution though.

**Comment by justintadlock** [comment] 2022-05-06 00:16
The only way I have found to handle this across the board is to name them in `theme.json` as WP would output them.  So, instead of using `16x9` in `theme.json`, literally type out `16-x-9`.

This will make sure it's consistent everywhere.

**Comment by coreyworrell** [comment] 2022-05-06 00:23
@justintadlock yeah, that makes sense. But right now we use them for utility classes, like `aspect:16x9`, and it just isn't quite as nice to be forced to use `aspect:16-x-9`. But it kind of is an edge case I suppose.
