### ISSUE TITLE
Gutenberg Crashed When I Tried To Open One Of My Saved Post/Article.

### ISSUE THREAD

**Issue by Dark-Cod3r** [WordPress/gutenberg#22507] opened 2020-05-20 19:11 UTC
**Describe the bug**
Hi. I saved a post yesterday, today i tried to open same post but Gutenberg keeps crashing. 
**To reproduce**
Just save an article, wait for a day, try to open that article again , Gutenberg crashed.

**Expected behavior**
It should open my article without crashing

**Screenshots**
https://i.ibb.co/pW6xrt3/crash.png
**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
I am Using gutenberg plugin. 
- If the Gutenberg plugin is installed, which version is it? 
Version 8.1.0.
Using gutenberg plugin cause the default one is more horrible and buggy.

**Desktop (please complete the following information):**
 - OS: [Windows 7 64bit]
 - Browser [Microsoft Edge]
 - Version [Version 84.0.516.1 (Official build) dev (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 6 Pro]
 - OS: [Android 9.0]
 - Browser [Opera Touch]
 - Version [Latest]

**Additional context**
As for additional context, at least implement a fallback method so we don't lose the whole article. I am trying to like Gutenberg (and believe me, i am an advance users) but all these bugs really getting annoying. if you  people going to introduce more and more bugs with each update, making Gutenberg unusable, you can just simply ask us to switch to classic editor (or elementor). Don't force us to use this horrible, un-finished product.

- Crash Report
Error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at http://theworldhairsalon.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4e8f627dcdf739a28ab4a11ef3d7fca1:11:260077
    at Array.forEach (<anonymous>)
    at http://theworldhairsalon.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4e8f627dcdf739a28ab4a11ef3d7fca1:11:260033
    at Vb (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:104:431)
    at Xi (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:151:136)
    at unstable_runWithPriority (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340)
    at Ma (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:280)
    at Yb (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:150:420)
    at O (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:120:254)
    at ze (http://theworldhairsalon.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14)

**Comment by annezazu** [comment] 2020-05-20 20:55
@Dark-Cod3r Hey there. Thanks for reaching out here to report this although I'm bummed gutenberg is crashing for you. What theme are you using? What other plugins are you using on your site? For context I'm asking because I'm not able to replicate this with WordPress 5.4.1 and Gutenberg 8.1.0 using the TwentyTwenty theme.

**Comment by Dark-Cod3r** [comment] 2020-05-20 22:28
> @Dark-Cod3r Hey there. Thanks for reaching out here to report this although I'm bummed gutenberg is crashing for you. What theme are you using? What other plugins are you using on your site? For context I'm asking because I'm not able to replicate this with WordPress 5.4.1 and Gutenberg 8.1.0 using the TwentyTwenty theme.

Thank You for your response. I am using pixwell theme (was using same theme yesterday without any issue). so i am pretty sure theme has nothing to with it. As for further info such as plugins and testing gutenberg with default theme, Kindly check the below video link....
**https://streamable.com/jbvp4g**

**Comment by talldan** [comment] 2020-05-21 07:05
@Dark-Cod3r This had been previously reported and a fix was attempted, but it seems like if you're still experiencing the problem on a more recent version of the plugin it may still be an issue.

There have been some reports that browser extensions can result in this issue:
https://github.com/WordPress/gutenberg/issues/20632

Is that something you'd be able to test, disabling browser plugins and then retrying?

**Comment by Dark-Cod3r** [comment] 2020-05-21 09:50
> @Dark-Cod3r This had been previously reported and a fix was attempted, but it seems like if you're still experiencing the problem on a more recent version of the plugin it may still be an issue.
> 
> #20632 was the previous report. There were some comments that browser extensions can result in this issue.
> 
> Is that something you'd be able to test, disabling browser plugins and then retrying? If we can work out which browser plugin it'd help a developer reproduce the issue.

Yes, You are right. It is because of extension naming Ublock Origin. But it is pretty strange though cause on my other website , with ublock enabled i can access gutenberg editor but on the other site with ublock enabled, i can't. don't make sense though. 
Only difference in both sites is , one has HTTPS enabled and other one is just plain HTTP. 
Kindly see these Videos. 
**https://streamable.com/cepm9v (Gutenberg Crash Because When Ublock Enabled, HTTP)**
**https://streamable.com/qydqw6 (Gutenberg Not Crashed When Ublock Enabled, HTTPS, Different Website)**

**Comment by mcsf** [comment] 2020-06-23 10:43
```
Error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
  at http://theworldhairsalon.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4e8f627dcdf739a28ab4a11ef3d7fca1:11:260077
  at Array.forEach ())
```

This sounds like it might be an issue of itself, either in `use-simulated-media-query` or `Sandbox`. @youknowriad, what do you think?

**Comment by mcsf** [comment] 2020-06-23 10:55
> Only difference in both sites is , one has HTTPS enabled and other one is just plain HTTP.

Yes, this would explain the difference. Browsers treat assets differently depending on encryption context, and this affects [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) policies. Recently, Chromium introduced a [fix to remove write-access to cross-origin CSS assets](https://bugs.chromium.org/p/chromium/issues/detail?id=775525). Microsoft Edge being powered by Chromium, you are now probably experiencing the effects of that fix.

I can only guess at what is happening in this specific case. But one guess is that, in the HTTP scenario, certain assets are being loaded via HTTPS (perhaps a CDN is taking over and serving CSS instead letting the server serve from `wp-content`?). When uBlock attempts to modify styles, it fails because that write-access would violate CORS.

**Comment by mtias** [comment] 2022-05-22 14:05
I'm closing this because it doesn't seem to have anything actionable to follow up on. If there's a narrower reproducible case that we could aim to make better, please reopen.

**Closed by mtias** 2022-05-22 14:05 UTC
Labels: [Type] Bug
