### ISSUE TITLE
Auto-Save distracting in Full Screen/Spotlight/Unified Toolbar mode

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#9767] opened 2018-09-10 19:38 UTC
**Describe the bug**
When switching on all three modes:  I like the very clear workspace now. It's definitely a lot calmer now. I am writing while watching the screen instead of the keyboard so something caught my eye randomly. It took recording below video to actually realize what's happening. 

**To Reproduce**
1. Go to Editor Settings
2. Check Unified Toolbar, Spotlight Mode and Full Screen Mode
3. Start writing content 

**Expected behavior**
Instead moving buttons, maybe auto-save confirmation can be done with less intrusive way. 

**Screenshots**
Video recorded: http://recordit.co/wKUH0m583q

**Desktop (please complete the following information):**
 - OS: MAC 
 - Browser Google Chrome 68.0.3440.106

**Comment by youknowriad** [comment] 2018-09-10 19:42
Maybe best to consolidate with #9455 in an effort to enhance the autosave status and save button?

**Comment by chrisvanpatten** [comment] 2018-09-10 20:30
@bph Interpreting that thumbs up reaction as agreement so I'll close this up as a duplicate of #9455 (which it's _technically_ not but GitHub will do the cool thing where it crosslinks if I write that) and we can re-open if I misinterpreted :)

**Closed by chrisvanpatten** 2018-09-10 20:30 UTC

**Comment by youknowriad** [comment] 2018-09-10 20:33
Duplicate of #9455 ;)
