### ISSUE TITLE
Social Icons block: Customizer > Widgets view button is distorted, can't add link.

### ISSUE THREAD

**Issue by sophiegyo** [WordPress/gutenberg#35826] opened 2021-10-21 09:16 UTC
### Description

Issue:

When managing widgets from Customize > Widgets, the social icons block has distorted buttons (100% width) and the URL inserter won't show.

It works fine from widgets.php, and when the Gutenberg plugin is disabled, it works fine in Customize > Widgets too.

It only happens when the plugin is active.

### Step-by-step reproduction instructions

1. Make sure you're using Gutenberg 11.7.1
2. Go to Customize > Widgets > whichever widget area
3. Add a social icons block
4. Add a social icon
5. Button is full width and won't show the URL inserter

### Screenshots, screen recording, code snippet

Screen recording: Customize > Wigets > issue

https://user-images.githubusercontent.com/36608681/138247744-ca566826-c1ba-4ec4-841e-a7c46c258e21.mp4

How it looks in widgets.php for comparison:
![widgetsfine](https://user-images.githubusercontent.com/36608681/138248278-e70079c1-95a7-444c-bf96-71426024e7aa.png)

### Environment info

WordPress version 5.8.1 (Fresh install on a throwaway site - no other plugins active than Gutenberg)
Gutenberg 11.7.1
Screenshot for reference:

![plugins](https://user-images.githubusercontent.com/36608681/138248758-d9664164-ce2a-47e2-b992-a21f4f931586.png)

Browser tested:
Safari 15
Firefox 93.0
Chrome 95.0.4638.54 

OS:
Mac 11.6

Tested in several different themes - this isn't specific to one theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment] 2022-02-21 00:47
I can't reproduce this anymore! Looks like it was fixed by https://github.com/WordPress/gutenberg/pull/35865.

**Closed as completed by noisysocks** 2022-02-21 00:47 UTC
Labels: [Type] Bug, [Feature] Widgets Customizer
