### ISSUE TITLE
Toolbar Covers Admin Notices

### ISSUE THREAD

**Issue by bmoredrew** [WordPress/gutenberg#3395] opened 2017-11-08 21:11 UTC
## Issue Overview
In Gutenberg 1.6.1 the toolbar blocks admin notices, positioning fails to let user click, uncover or dismiss.

## Steps to Reproduce
1. Have an active admin notice
2. Create and/or Edit a Post

## Screenshot
Sidebar open:
![screen shot 2017-11-08 at 3 59 42 pm](https://user-images.githubusercontent.com/1743054/32574260-a47da6c2-c49e-11e7-917b-16d08d9d0b68.png)

Sidebar closed:
![screen shot 2017-11-08 at 4 09 32 pm](https://user-images.githubusercontent.com/1743054/32574512-6c0d7a5a-c49f-11e7-9bac-d3546f03435f.png)

**Comment by hedgefield** [comment] 2017-11-13 09:19
Yep, this has been an issue for a long time. Should we hide these notices in the editor, or move the UI down to make room for them? _Personally_ I wouldn't prefer the latter, so I'm interested to hear what people's feelings are on this.

**Comment by darrencoutts118** [comment] 2017-11-13 14:28
I would move them down. Developers will likely want to be able to add notices, and this would be more consistent

**Comment by maddisondesigns** [comment] 2017-11-14 02:02
Don't ever hide notices (as annoying as they can be). Notices are part of WordPress core and Gutenberg needs to accommodate them, not simply hide them or ignore them because you've change the ui.

**Comment by youknowriad** [comment] 2017-11-14 08:26
Later, we should think about building enhancing the "notifications" API (icon in the top bar, unread notifications...) Something like WP.com. But this is out of the scope of Gutenberg.

**Comment by maddisondesigns** [comment] 2017-11-14 08:42
Agreed! WP desperately needs a better system for managing notifications! To many plugins show their own style notifications, and/or useless notifications, when they update.

**Comment by jeherve** [comment] 2017-11-15 13:20
This looks like a duplicate of #3214

**Comment by jsmoriss** [comment] 2017-11-15 22:11
Moving the notices down makes no difference - the actual layout of the page is the problem.

Here's an example from a truly screwed up page. lol. :)

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2913687/32863002-97d80940-ca1f-11e7-9fab-fd27efe8f0e6.png">

js.

**Comment by wpmark** [comment] 2017-11-16 12:46
I have just noticed this is a problem with the VaultPress plugin admin notices. This is how the notice shows on the dashboard screen:

![screen shot 2017-11-16 at 12 34 02](https://user-images.githubusercontent.com/2027394/32891830-08b9598c-cacc-11e7-84e1-2d94a96f7e8c.png)

And this is how it shows on the editing screen:

![screen shot 2017-11-16 at 12 34 54](https://user-images.githubusercontent.com/2027394/32891836-14d9f8de-cacc-11e7-9445-96be8d8ab990.png)

Not ideal.

**Comment by nagpai** [comment] 2017-12-17 03:00
Looks like notifications that appear below the admin page title - eg- "Dashboard" appear to overlap in the Gutenberg page. 

Steps i did.

1. Created a test site 
2. Install and activate plugins - Gutenberg, WordFence, WooCommerce  Stripe payment gateway (without installing WooCommerce), to generate notifications.

I see this:
![sandbox-1](https://user-images.githubusercontent.com/4162931/34076163-f692f692-e302-11e7-84fb-5d0d7fe4552a.png)

3. Switch to Posts >> Add Post (wiith Gutenberg). We see only the Stripe Payment Gateway Plugin notifications overlapping the editor.  The WordFence notification that appears above the title is not visible in the overlap. If i disable the Stripe plugin, we do not see anything overlapping. 

![sandbox-2](https://user-images.githubusercontent.com/4162931/34076184-92d2686c-e303-11e7-9409-ecc8a6bd5180.png)

**Comment by edwinsnotje** [comment] 2018-01-17 13:16
Notifications can be relevant while editing a post. 

Some plugins show irrelevant or nagging notifications. However, that is no reason to end notifications, just as it is no reason to end plugins. There can be usefull notifications concerning a post, or concerning some meta-post website-condition. 

It would furthermore be nice to have notifications outside the editor, as we have now, and notifications inside the new toolbar, depending on the editing context.

**Comment by kmgalanakis** [comment] 2018-02-07 13:08
If you ask me, all the admin notices should go inside the div with class `components-notice-list` and the position of it should not be fixed.

**Comment by jasmussen** [comment] 2018-02-28 07:51
This has been addressed as part of #4811, which hides the notices in the editor. Notices are shown everywhere else in the admin, that is unchanged. 

There is also a [native interface for showing notices to the editor](https://github.com/WordPress/gutenberg/blob/18edc8edd6f958b3e939116eb54c65084433cb7a/components/notice/README.md).

**Closed by jasmussen** 2018-02-28 07:51 UTC
Labels: Chrome, [Type] Bug, [Type] Plugin / Extension Conflict

**Comment by maddisondesigns** [comment] 2018-02-28 08:47
You're seriously just going to hide them!? That's a horrible idea! Gutenberg needs to accommodate core functionality, not just hide things when you feel like it or because it interfere's with your new design. You need to change your UI to accommodate them if need be.

**Comment by jasmussen** [comment] 2018-02-28 09:13
This is the path forward we are looking at for now. Tickets can be reopened, patches can be reverted. But it's important, especially while we are in beta, to keep moving. In this case, the reasoning for hiding notices to provide a better API for notices in the new editor, where you won't end up with undismissable notices. 

In other words, these notices aren't hidden because you should never see notices in the editor, it's because there is no good path to changing notices that can consist of arbitrary HTML into something that the editor can provide a good interface for. 

Given that you still see these notices in every other screen in the admin, we decided to move ahead. But as with all things, we can move backwards again.

**Comment by maddisondesigns** [comment] 2018-02-28 09:27
So, now there's one way to display notices in the editor, and a completely different way to show notices elsewhere? That's ridiculous. If there's an issue with displaying notices in the editor, and the problem is due to the existing WP notification system (or lack thereof), then fix how notices work in core.

As per my comment above (back in Nov), I think everyone can agree that WP desperately needs a better notification system. Get it fixed in core so Gutenberg can make use of it. Don't just hide the problem.

**Comment by karmatosed** [comment] 2018-02-28 11:34
@maddisondesigns please be civil in way you approach this, passion is one thing but we are all working on a solution together and that takes respectful communication. Whilst we can work to make things better we can't solve all of core's issues in Gutenberg, that will happen over time. 

I do not think anyone will argue against having a better notification system, it's how that happens and it needs someone like you who is passionate about this area to in core help find a solution. I'd be very keen to see a feature plugin for notifications and messages worked on outside of Gutenberg and fully support that as a project.
