### ISSUE TITLE
YouTube Block Enhancement: Add Options to Customise

### ISSUE THREAD

**Issue by torres126** [WordPress/gutenberg#13350] opened 2019-01-16 21:39 UTC
**Is your feature request related to a problem? Please describe.**
Currently, hiding related videos or the top information bar requires adding a difficult-to-remember string to the end of the URL. It'd be great if there was a checkbox on the side to make that easier. 

**Describe the solution you'd like**
If there was a checkbox on the side to control customisation of the YouTube block, it'd be great. 

If "Hide related videos" is checked, `&rel=0` should be added to the end of the video URL. If "Hide information bar" is checked, `&showinfo=0` should be added instead. See here: https://en.support.wordpress.com/videos/youtube/

Here's how I imagine this looking, though I've not really considered an alternative:

![fgssdfgsfdg](https://user-images.githubusercontent.com/43215253/51279891-31295980-19d6-11e9-8dfd-4c962866cc33.png)

Gutenberg offers a lot to try and make publishing easier, this would go a huge way too in terms of convenience!

Related to #9678, but felt different enough to justify its own issue, since hiding related videos based on the URL works fine currently, it's just inconvenient to do.

**Comment by swissspidy** [comment] 2019-01-16 23:05
Duplicate of #9678

**Closed by swissspidy** 2019-01-16 23:05 UTC
Labels: [Block] Embed, [Status] Duplicate
