### ISSUE TITLE
No option to remove Block previews

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24742] opened 2020-08-23 08:08 UTC
**Describe the bug**
The _Inserter Help Panel_ option is no longer available in the _More tools & options_ panel. Why can we no longer turn off this preview? You insist on removing options that are actually important to the UI, like block drag handles, yet force unnecessary UI elements like this on users, and then remove the option to allow people to hide them when we don't want to see them. Just like the previous tips, preview panels like this are mostly useless and take up valuable screen real-estate by covering content. After you've inserted a couple of Paragraph blocks, I'm pretty sure that you no longer need a preview every time you go to insert a new one.

<img width="1197" alt="screenshot_82" src="https://user-images.githubusercontent.com/2078245/90974037-e1742200-e56a-11ea-83c9-d62414daa34f.png">

**To reproduce**
1. Go to More tools & options panel
2. Look for the _Inserter Help Panel_ option
3. Give up because it no longer exists

**Expected behavior**
Preview panels need an option to be able to be turned off, like it was available for the previous Block Inserter. 

**Editor version (please complete the following information):**
- WordPress version: [5.5]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):
- OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

**Comment by talldan** [comment] 2020-08-25 01:40
Closing as a duplicate of #22053

**Closed by talldan** 2020-08-25 01:40 UTC
