### ISSUE TITLE
Bigger block insertion box

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7141] opened 2018-06-05 08:43 UTC
I currently have 70 blocks and my resolution often is 1920&times;1080px or 2560&times;1440px.

The block insertion box shows 3 &times; 3 = 9 blocks.

That means I have to scroll 8 vertical lengths of that box to find what I want.

**Proposed solution:**
Make it bigger when it's possible to do so.
<img src="https://i.imgur.com/R6eLBSj.png">

**Comment by karmatosed** [comment] 2018-06-05 11:36
I would like us to test the new library we have right now and get feedback before we dive into changing that further. I do think personally that having too wide becomes a usability problem also, for example that screenshot is overwhelming. For now, let's see get opinions on this but I don't think we need to increase as far as you suggest.

**Comment by manake** [comment] 2018-06-05 14:17
**Subjective:**
- "[...] I do think personally [...]"
- "[...] that screenshot is overwhelming [...]"
- "[...] I don't think we [...]"

**Time**
I can propose some resolution: Implement A/B and measure how much time it takes from clicking `+` to finding and inserting a block. I bet it's going to be like:
  - 10-15 seconds average time with current box
  - <10 seconds with updated box

**Effort**
Doesn't need A/B. Scrolling 8 vertical lengths requires me to remember what was on 7 other positions while I"m looking at 1. I have to load this information to my brain and use more mental resources. I have a constant desire to see everything (and this desire finally led to me creating this ticket when it became too frustrating).

**Other variables**
You can propose some other **objective** variables to measure (like "overwhelmingness") but for me it's about saving time and effort.

**Comment by SuperGeniusZeb** [comment] 2018-06-05 14:48
Disclaimer: I am not a WordPress or Gutenberg developer.

@manake
I agree with @karmatosed that having the inserter be as big as in your screenshot is overwhelming. It feels busier and less focused. The larger size means a greater distance that your mouse has to travel to reach stuff, and your eyes have a harder time focusing because there is too much shown on-screen at once. The large size of the pop-up also obscures most of the post content, which makes it a bit harder to tell where you are in the content and where you are inserting the block. I think making the inserter too large would actually make it harder to use.

If one is trying to find a specific block, I would expect them to just use the search bar, which is bound to be faster in most cases than moving your mouse (and your eyes) around in that large pop-up. If one is just browsing to see what blocks are available, I think scrolling through a small pop-up is better than looking through a large one. You do not have to move your hand or eyes around as much, and you do not feel overwhelmed by all the options.

**Comment by manake** [comment] 2018-06-05 14:59
@SuperGeniusZeb

Thanks for the feedback. I see there is disagreement and different perception of the issue.

- In my opinion the decision should be made based on objective variables (time and effort).
- Do you have any scientific/statistical proof that a big box is in fact overwhelming? It's not overwhelming for me.
- Mouse travel and eyes travel is much less effort for me than loading 61 invisible/unknown words/icons into my brain and processing 9 visible ones.

I used this inserter 1000s of times already and maybe it **looks** good but it doesn't **work** well. If you're using it 1000 &times; 10 seconds = 10,000 seconds (166 minutes) then you think "if it could be bigger I would waste 1000 &times; 5 seconds = 5,000 seconds (83 minutes)".

**Comment by hedgefield** [comment] 2018-07-24 12:14
[Research has shown](https://en.wikipedia.org/wiki/The_Magical_Number_Seven%2C_Plus_or_Minus_Two) that humans are only capable of processing ~7 items at a time, and content is often limited to a width between 720 and 1280 px [because anything longer causes strain mentally and physically](https://www.fonts.com/content/learning/fontology/level-2/text-typography/length-column-width). Granted, this is based on text, but when mixing iconography and text, there is not much of a difference. It's the same reason why the content in Gutenberg, and all WordPress settings pages at that (generally) don't become any wider when you enlarge the browser on hi-res screens. This is also mirrored in the [Web Accessibility Guidelines](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-visual-presentation), which aim to make content easily digestible for people with disabilities and impairments.

I do agree that the Inserter could be bigger, but there should be a limit. In this case especially because the Inserter overlaps with the content, and both need to be visible to some degree to be effective. And when it is too wide, it throws a lot of unnecessary whitespace, such as in your screenshot where one block adds an entire extra row that is otherwise empty.

There will always be people who prefer different sizes, and that's fine - if it works for you, who are we to argue? But as the default experience we should ship something that is comfortable for anyone. Then people can iterate on that with extra options or plugins as they please.

So what we could experiment with is a responsive Inserter, maybe up to ~six horizontal items. And I'd also be interested in seeing if the height can be expanded to always fit the height of the screen, that would help too.

Here's the original:

<img width="1673" alt="screen shot 2018-07-24 at 14 02 45" src="https://user-images.githubusercontent.com/6073772/43137030-e20ff9b4-8f4a-11e8-872e-3cb16be06165.png">

Here's a version that's 480px wide with the items set to be 24%. Plus the height is set to fit the content for as long as there is room:

<img width="1672" alt="screen shot 2018-07-24 at 14 02 11" src="https://user-images.githubusercontent.com/6073772/43137044-eb1c3d6a-8f4a-11e8-8fff-4b7997e67cc4.png">

And a version that's 640px wide with the items set to 16%.

<img width="1674" alt="screen shot 2018-07-24 at 14 00 05" src="https://user-images.githubusercontent.com/6073772/43137035-e5aa30a8-8f4a-11e8-82d8-a7b7cc8aeebf.png">

For me personally the 480px feels good, and the 640 is starting to feel uncomfortable while still being reasonable. Could we maybe try the 480px version for larger breakpoints in the next release and see how it feels? cc @karmatosed @jasmussen

**Comment by SuperGeniusZeb** [comment] 2018-07-24 15:35
480px feels like the maximum width I would want it to be. I definitely think increasing the height would be a good idea though.

**Comment by karmatosed** [comment] 2018-07-25 02:02
@hedgefield what does 480px look like without the full height? I would be ok viewing that to then decide on implementing. I don't agree it needs to be full height of the content at this point.

**Comment by hedgefield** [comment] 2018-07-25 09:08
@karmatosed Here it is:

Width 480px
Height 432px (current default)
Item width 24% (was 33.3% but that stretches the items out instead of making more fit the space)

<img width="1721" alt="screen shot 2018-07-25 at 11 00 44" src="https://user-images.githubusercontent.com/6073772/43190983-83f168f8-8ffa-11e8-9155-5d1592d731e2.png">

And I did one more with slightly more height, to make it a nice square. Items look a little nicer too.

Width 480px
Height 480px
Item width 25%

<img width="1713" alt="screen shot 2018-07-25 at 11 03 33" src="https://user-images.githubusercontent.com/6073772/43191067-b500b1e2-8ffa-11e8-9a18-96e80f79b828.png">

**Comment by karmatosed** [comment] 2018-07-25 12:07
Thanks @hedgefield. I am a little torn on if this is the way forward. Having it larger makes it a lot more dominant on the page. However it could solve issues like translation. I wonder if seeing what it klooks like in other languages would help? Also whilst you are showing the top, the block library doesn't just appear there, it's a pattern that happens 'in' the content where you add blocks in a few places and for transforms in the block chip drop down - having 2 sizes would be weird. What do those look like mocked up along these lines.

**Comment by hedgefield** [comment] 2018-07-25 12:47
Right, forgot that there's an inline inserter too. Made a few screencaps of those situations too. And it doesn't have to be 480px all the way, right. On lower breakpoints we can do the 350 it is currently, just for 1080p and above, 480 feels much more comfortable in that ocean of space.

(click to enlarge)
<img width="200" alt="screen shot 2018-07-25 at 14 36 48" src="https://user-images.githubusercontent.com/6073772/43201664-67255bac-9019-11e8-8dad-147ab1d82777.png"> <img width="200" alt="screen shot 2018-07-25 at 14 37 10" src="https://user-images.githubusercontent.com/6073772/43201665-673aa674-9019-11e8-8bd8-1b52d41aad9c.png"> <img width="200" alt="screen shot 2018-07-25 at 14 42 41" src="https://user-images.githubusercontent.com/6073772/43201666-674e0cbe-9019-11e8-80a9-7729ae32df85.png">

We can certainly experiment with the item width to leave more room for translations too. I tried to include them in the screenshots, but setting my WP to another language didn't translate the Gutenberg interface? I guess it isn't prepped for translation yet?

The dominance on the page isn't a bad thing I think. Looking at time spent having the inserter open in the grand scheme of writing a post, it's no more than 1% I'd wager. Instead of always maintaining focus on the content, it makes sense to give room to the task you are trying to achieve at that moment, which is inserting a block. Again, definitely on 1080p and up, keeping that popover as tiny as it is only hinders that effort I would say.

**Comment by vincentariens** [comment] 2018-07-27 11:18
Maybe a better question is: why are there so many 'standard' blocks?

We are a WP agency en build a lot of custom templates. If this will be the way blocks are going to be added we need a lot of explanation what each block is going to do. So next to the fact that I agree that the current popup is way too small part of the problem is the amount of blocks that need to fit in it. Less blocks is a beter UX experience. 

Another point is that icons are nice, but not enough so that is the reason we put a small piece of text below it. Inspired by gravity forms I should say this is a solution that combines best of both worlds:

PS1 It is a rough UX example needs some tweaks on spacing etc
PS2 If there are so many blocks a search field is necessary something is wrong...

![gutenberg](https://user-images.githubusercontent.com/41729631/43318015-7abf6ffe-919f-11e8-8818-2d41c296ad76.png)

**Comment by vincentariens** [comment] 2018-07-30 07:34
@karmatosed Thanks for your reply, I think that the amount of itterations is not the best reason to keep things the way They are. With all the respect to the hard work :)

I am relatively new in this project and overwhelmed by the amount of blocks and choices combined with a very small and Tiny UX Solution for this major (maybe the most Important) functionality.

Pro’s for the lozenge sollution are from my perspective:

Takes less height
Could be flexible bases on length of words

The only difference with the current one is that it is more icon based. But as I already said, there are way to many blocks (unfortunately) to make that work.

**Comment by karmatosed** [comment] 2018-07-30 20:39
@vincentariens I wouldn't and didn't suggest the number of iterations as the reason. It's a path of progression and one that has proven to work so far. For now that's not going to change and is a design decision as a project we're sticking to. We can always revisit but let's focus back this issue on the width.

**Comment by maddisondesigns** [comment] 2018-08-20 02:41
I added the following styles to my own theme to improve the usability of the Block Inserter and to increase its size on larger screens.

```
@media only screen and (min-width: 1300px) {
	/* Increase the size of the block inserter to something more useful */
	.editor-inserter__popover .editor-inserter__menu {
		width: 700px;
	}
	.editor-inserter__popover .editor-block-types-list__item {
		width: calc(16.6% - 8px);
	}
	/* Increase the size of the block inserter icons so they're more readable */
	.editor-inserter__popover .editor-block-types-list__item-icon {
		padding: 10px 15px;
	}
	.editor-inserter__popover .editor-block-types-list__item-icon svg {
		width: 30px;
		height: 30px;
	}
}
```

It increases the overall size of the Block Inserter. It also increases the size of the icons to make them more readable, whilst also keeping each block roughly the same size as it was previously. It results in the following:

![screenshot_803](https://user-images.githubusercontent.com/2078245/44317602-8425d180-a475-11e8-8fff-cc0f1e8363c3.png)

**Comment by karmatosed** [comment] 2018-08-20 19:47
@maddisondesigns whilst I appreciate your exploration, as we have just made this change let's have this experience sit for a bit before we iterate again. Looking at your version, there is large line-length issue for readability in the actual posts. It's worth considering reading lengths and their impact.

**Comment by ZebulanStanphill** [comment] 2018-08-20 20:04
I feel like 4 columns is the maximum I would want the inserter to be, but I'm actually pretty happy with the current 3 columns. 5 columns feels too big and 6 feels over the top.

The more I use the inserter, the more I feel like there is little to be gained in making it much bigger; it is hard to focus on one when then are a lot. Just glancing at the 3 block rows and scrolling feels plenty fast, and if I am looking for a specific block, then the search bar or Most Used categories are faster anyway. (And this is all assuming I am not using the slash inserter, which is probably the fastest method of all.)

**Comment by karmatosed** [comment] 2018-10-08 19:27
Let's close this for now. We have some iterations happened on the block library and can iterate beyond phase 1. For now, let's keep the library width we have.

**Closed by karmatosed** 2018-10-08 19:27 UTC
Labels: Blocks, Needs Design Feedback, [Type] Enhancement
