### ISSUE TITLE
[Widget Screen] Unable to add classic block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#25595] opened 2020-09-24 01:54 UTC
**Describe the bug**
When trying to add the classic block to the widget screen, I receive an error. 

**To reproduce**
1. Go to Appearance > Widgets
2. Try to add the Classic Block
3. See error. 

**Expected behavior**
I expected to be able to add the classic block

**Screenshots**

<img width="685" alt="Screen Shot 2020-09-23 at 7 50 48 PM" src="https://user-images.githubusercontent.com/26996883/94091694-15469f80-fdd6-11ea-93cb-f6e11d921ed1.png">

![classic block](https://user-images.githubusercontent.com/26996883/94091708-22638e80-fdd6-11ea-8bd0-bb1540193df9.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 85.0.4183.102

**Comment by draganescu** [comment] 2020-09-30 08:19
This is a duplicate of #15916

**Closed by draganescu** 2020-09-30 08:19 UTC
Labels: Needs Testing, [Block] Classic, [Feature] Widgets Screen
