### ISSUE TITLE
Classic Block: Editing links forces a page jump to the top of the page

### ISSUE THREAD

**Issue by davipontesblog** [WordPress/gutenberg#21949] opened 2020-04-28 13:04 UTC
This bug happens when you edit a post using the Classic Block. Steps to reproduce as reported by the user:

**To reproduce**
1. Open a post in the editor, in this example they have a post that has a large content inside a classic block.
2. Scroll the page down, find a link, click to edit, edit it, apply the change.
3. The page scrolls back to the top automatically.

**Expected behavior**
We expect the page position to remain where it was, after editing the link.

**Video showing the issue**
https://drive.google.com/file/d/1DHVDbtOKcvv4BPVnNr2j4d-B4VNcaF2T/view?usp=sharing

**Editor version:**
- WordPress version: 5.4
- Gutenberg plugin version 7.7.1

**Additional context**
- Reported by a WordPress.com user, in #2911762-zen.

**Comment by youknowriad** [comment] 2020-04-28 13:10
Duplicate of #14134

**Closed by youknowriad** 2020-04-28 13:10 UTC
