### ISSUE TITLE
Adding Hover Text to Images in Gutenberg

### ISSUE THREAD

**Issue by AMcGrady** [WordPress/gutenberg#14147] opened 2019-02-27 17:22 UTC
**Is your feature request related to a problem? Please describe.**
I've interacted with a user who would like an easier way to add Hover Text to Images in Posts or Pages. 

The current process to do that looks like:
Steps for setting a title that will appear on images when hovering:
1. Visit your WP Admin (our older) dashboard to start.
2. Next go to: Posts on the left side menu, then select a blog post to edit
3. You will be brought to a post editor.
4. Click on the image to make the editing tools for the image appear, then select the Edit option.
5. A popup window will appear, click the Advanced Settings section at the bottom of the popup to be able to set an Image Title Attribute, as seen here: Screenshot: https://snag.gy/EK7FNb.jpg
6. Once you're done save your changes using the Update button on the popup and the update button on your post

There is also no way to add Hover Text to Featured Images which this user would like to be able to do.

**Describe the solution you'd like**
I'd like these features to be built into the Block Image Settings.

**Describe alternatives you've considered**
The process described above can add hover text to Posts or Pages. The only way I've found so far to add hover text to a Featured Image involves using both html and css.

**Comment by youknowriad** [comment] 2019-08-23 09:27
Duplicate of #11054

**Closed by youknowriad** 2019-08-23 09:27 UTC
Labels: [Block] Image
