### ISSUE TITLE
Text format is not proper

### ISSUE THREAD

**Issue by davidjeams** [WordPress/gutenberg#12712] opened 2018-12-09 11:08 UTC
There is a problem with the new update of Wordpress Gutenberg edition.
After updating WordPress, am facing a problem with writing. It is now working well. kindly check this link to understand the problem and give me solution if anyone have...

https://imgur.com/a/glh6ts1

Thanks

**Comment by swissspidy** [comment] 2018-12-09 17:00
Sounds like a duplicate of #12669.

**Closed by swissspidy** 2018-12-09 17:00 UTC
Labels: [Status] Duplicate
