### ISSUE TITLE
Partial dynamic block rendering / Static content in dynamic blocks

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7331] opened 2018-06-16 22:42 UTC
In the examples you `return null;` in `save()` for dynamic blocks. 
But what if I only want parts of my block to be dynamic and others to be static? 

What happens to saved content, when a block gets rendered dynamically with PHP?

I imagine something like this:
`$savedHTML` as a parameter

```php
// plugins/myBlock/index.php
add_action("init", function() {

    wp_register_script( ... );
    wp_register_stlye( ... );

    register_block_type( 'rene-blocks/test', array(
        'editor_script' => 'myScript',
        'editor_style' => 'myStyle',

        'render_callback' => function( $attributes, $savedHTML ) {
        	// create html with $attributes and mix in $savedHTML as I please
        }

    ) );
})
```

**Comment by nyordanov** [comment] 2018-06-18 13:43
@danielbachhuber I found this issue yesterday while toying with some ideas. Example use cases:

1. Static "author bio" block, which displays the latest post by the author.
2. A block which is saved as static, but its template is modified based on whether another plugin is active. Think of this as a per-block filter in `do_blocks()`. Maybe this is addressed by #2751?
3. A way to simplify the output of `save()` - possibly also related to #2751? Maybe used as a fallback when the plugin implementing a dynamic module is deactivated.

A related problem is that editing dynamic modules in the Code Editor in hard. This is just five lines in a RichText:

```html
<!-- wp:nyordanov/test {"text":[{"type":"p","key":"_domReact3","ref":null,"props":{"children":"RichText"},"_owner":null},{"type":"p","key":"_domReact5","ref":null,"props":{"children":["is ",{"type":"strong","key":"_domReact9","ref":null,"props":{"children":"hard"},"_owner":null}," to"]},"_owner":null},{"type":"p","key":"_domReact13","ref":null,"props":{"children":"edit"},"_owner":null},{"type":"p","key":"_domReact16","ref":null,"props":{"children":"in the"},"_owner":null},{"type":"p","key":"_domReact19","ref":null,"props":{"children":"Code Editor"},"_owner":null}]} /-->
```

**Comment by katerlouis** [comment] 2018-06-18 13:46
I wanted to use a mix of static and dynamic output as a workaround, since I am not able yet to output `<RichText>` properly #7332 

So I figured: Why not save the paragraph statically, and add the gallery stuff on top dynamically in php.

Another possible use-case:
I am extending a block but don't want to recreate all it's logic and html output in PHP. This can be very tedious for complex blocks. All I have to do now is add my own attribute and, make my own dynamic rendering logic, and add the saved html.

You could always argue everything is possible with both methods, so just pick one for the entire block. But as I see Gutenberg, it lives and breathes: I want to make working with content more convenient and give options to both editors and developers.

Maybe I'm missing something here, but to me not having access to what has been saved statically in php is a wasted potential.

**Comment by katerlouis** [comment] 2018-06-18 15:00
Similar issues: #5760 #5968

**Comment by mcsf** [comment] 2018-07-17 13:41
Closing as duplicate of #5760.

**Closed by mcsf** 2018-07-17 13:41 UTC
Labels: Block API, [Type] Help Request
