### ISSUE TITLE
List View: Always make the selected block visibile by scrolling the view automatically

### ISSUE THREAD

**Issue by zdenys** [WordPress/gutenberg#46828] opened 2022-12-30 07:29 UTC
## What problem does this address?

When a page/post has a high number of blocks they all don't fit in one view in the List View. In that case, there is a vertical scroll bar in List View. With List View open, if you select a block somewhere towards the bottom in the Editor, it will be selected in the List View, but it won't be visible as the List View doesn't scroll automatically to make it visible. 

https://user-images.githubusercontent.com/39308239/210045249-e5e8b7e2-bd34-4b3f-bd1f-3e3573d1f170.mov

## What is your proposed solution?

When the List View is open, it would be helpful to always see the selected block by ensuring that the view scrolls automatically. This is especially impactful for pages/posts with a high number of blocks.

**Comment by ntsekouras** [comment] 2023-01-25 07:19
I think this was the behavior in the past and it was removed for UX reasons 🤔 . Not 100% sure though... --cc @jasmussen

**Comment by jasmussen** [comment] 2023-01-25 07:43
I actually don't recall this. No strong feelings on my end.

**Comment by andrewserong** [comment] 2023-01-26 23:13
Oh, interesting... I was pretty sure it hadn't been implemented before, but at the very least there's been a prior open issue since April 2021 for it in https://github.com/WordPress/gutenberg/issues/30432.

I have a PR that looks to implement it over in https://github.com/WordPress/gutenberg/pull/46895 if anyone gets a chance to take it for a spin 🙂

**Comment by Mamaduka** [comment] 2023-02-09 06:57
Let's close this as a duplicate of #30432.

**Closed as completed by Mamaduka** 2023-02-09 06:57 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Feature] List View
