### ISSUE TITLE
Can't select text within paragraph without selecting entire paragraph

### ISSUE THREAD

**Issue by scottbuscemi** [WordPress/gutenberg#10772] opened 2018-10-19 03:45 UTC
**Describe the bug**
There isn't a way to select particular sentences in multiple paragraphs without selecting the entire paragraphs.

**To Reproduce**
1. Create two paragraphs that each have two sentences.
2. Select the second sentence in the paragraph, then begin to highlight the first sentence.

**Expected behavior**
You should be able to just select particular sentences within a paragraph. There may be the use case where you want to copy one paragraph and the start of a next and move it elsewhere - but Gutenberg forces you to select entire paragraphs if you start highlighting more than just paragraph.

**Screenshots**
![screen shot 2018-10-18 at 8 45 03 pm](https://user-images.githubusercontent.com/4336848/47196704-b5583c00-d316-11e8-8a53-67fea6370216.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
Nightly build of Gutenberg.

**Comment by designsimply** [comment] 2018-10-22 19:48
Thank you for testing Gutenberg at this stage! There is an open issue at #3629 discussing the same thing, so I am going to close this issue as a duplicate of that one.

**Closed by designsimply** 2018-10-22 19:48 UTC
