### ISSUE TITLE
Classic + Custom HTML blocks: Convert to Blocks removes valid inline formatting

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#6102] opened 2018-04-10 15:40 UTC
## Issue Overview
The Paragraph block, as well as other textual blocks, allow `<abbr>`, `<b>`, `<code>`, `<i>`, `<kbd>`, `<mark>`, `<span>`, `<time>`, and various other inline formatting and semantic tags to be added using the "Edit as HTML" option, and these are considered valid and are not removed on save.

However, when converting a Classic block to standard blocks using the "Convert to Blocks" option, the paragraphs, lists, and blockquotes are stripped of some inline formatting tags, and a few are converted to tags that have a different semantic meaning.

I think inline formatting that is considered valid by the standard blocks should not be removed when converting a Classic block to standard blocks. Otherwise, you are stripping out formatting from the original post when you do not need to.

## Steps to Reproduce (for bugs)
1. Create a post using the Classic Editor or insert a Classic block in the Gutenberg editor.
2. Insert the following:
```html
<abbr>abbr</abbr> <b>b</b> <br>br <bdi>bdi</bdi> <bdo dir="rtl">bdo</bdo> <cite>cite</cite> <code>code</code> <data value="value">data</data> <dfn>dfn</dfn> <em>em</em> <i>i</i> <kbd>kbd</kbd> <mark>mark</mark> <q>q</q> <ruby>ruby <rb>rb</rb> <rp>rp</rp> <rt>rt</rt> <rtc>rtc</rtc> <rp>rp</rp></ruby> <s>s</s> <samp>samp</samp> <small>small</small> <span style="color:red">span</span> <strong>strong</strong> <sub>sub</sub> <sup>sup</sup> <time datetime="2018">time</time> <u>u</u> <var>var</var> <wbr>wbr
```
3. Save the post.
4. Open the post in the Gutenberg editor.
5. Convert the Classic block to standard blocks using the <kbd><samp>Convert to Blocks</samp></kbd> option.
6. Notice how some of the inline formatting has been removed, and some of it has been converted to other elements with different semantic meaning, e.g. `<b>` tags are converted to `<strong>` tags.

## Expected Behavior
Converting a Classic block to standard blocks using the "Convert to Blocks" option should preserve all inline formatting tags that are considered valid by the resulting blocks.

## Current Behavior
Converting a Classic block to standard blocks using the "Convert to Blocks" option removes several valid HTML5 tags, and converts some tags to other tags with different semantic meanings, e.g. `<b>` tags are converted to `<strong>` tags. The previously given sample input above is transformed into the following:
```html
<p><abbr>abbr</abbr> <strong>b</strong> <br/>br bdi bdo cite <code>code</code> data dfn <em>em</em> <em>i</em> kbd mark q ruby rb rp rt rtc rp s samp small span <strong>strong</strong> <sub>sub</sub> <sup>sup</sup> time u var wbr</p>
```

## Other Notes
If a Classic block contains obsolete HTML tags like `<color>`, then converting them to `<span>` tags upon conversion to standard blocks seems like a good idea.

`<b>` and `<i>` tags are converted to `<strong>` and `<em>` respectively. However, it should be considered that there are valid cases where a `<b>` or `<i>` are used semantically as per the HTML5 specification. Additionally, `<span>` tags containing `font-weight:bold` or `font-style:italic` are converted to `<strong>` or `<em>` tags respectively, and this seems like a bad idea. Most of the time, when someone makes text bold or italic using a `<span>` tag, they are doing it for purely stylistic reasons and not semantic reasons, so converting those to `<strong>` and `<em>` tags seems like a bad idea.

## Related Issues and/or PRs
- #4186
- <s>#4498</s>
- <s>#5876</s>
- <s>#6096</s>
- #6878
- #7604

**Comment by danielbachhuber** [comment] 2018-07-27 19:56
#6878 and #7604 are both related.

The first is relevant because there's still some amount of the HTML5 spec we need to accommodate for: https://github.com/WordPress/gutenberg/issues/6878#issuecomment-407714781

The second because, in the scenario where we're stripping out HTML, we need to improve the user experience.

I don't think this needs to be resolved prior to the Try Callout though, for two reasons:

1. The user can undo the conversion process.
2. This is a much larger architectural conversation that there's not necessarily a "fix" for.

**Comment by SuperGeniusZeb** [comment] 2018-07-27 20:07
@danielbachhuber Okay, fair enough.

**Comment by fumikito** [comment] 2018-09-18 07:11
@ZebulanStanphill @danielbachhuber

F.Y.I.
I tried some fix [phrasingContentReducer](https://github.com/WordPress/gutenberg/blob/master/packages/blocks/src/api/raw-handling/phrasing-content.js#L6) for `ruby` tag.

```js
const phrasingContentSchema = {
	strong: {},
	em: {},
	del: {},
	ins: {},
	a: { attributes: [ 'href', 'target', 'rel' ] },
	code: {},
	abbr: { attributes: [ 'title' ] },
	sub: {},
	sup: {},
	br: {},
	ruby: {
		children: {
			rt: {
				children: {
					'#text': {}
				}
			},
			'#text': {}
		}
	},
	'#text': {},
};
```

Now it works and classic block conversion keeps expected HTML.

![2018-09-18 15 56 47](https://user-images.githubusercontent.com/84587/45669719-dbde5800-bb5b-11e8-91fe-031a80f3dac2.png)

Fundamentally, `ruby` tag is not supported by current WordPress(filtered by TinyMCE) and I need [a plugin](https://wordpress.org/plugins/wp-yomigana/) to enter `ruby`. `ruby` is rarely used but in Japanese.

In my opinion, [JS filter hook](https://core.trac.wordpress.org/ticket/21170) for `phrasingContentReducer` will help plugins for i18n or semantic freaks like `<q cite="some source">Some quotes</q>`, `<ins datetime="date-of-insertion">Inserted text</ins>`, and so on.

**Comment by michakrapp** [comment] 2018-10-08 10:35
I got a similar behaviour with the `<address>` element.
When converting to blocks link markup inside of it get completely strip off.

Unfortunately in this case it gets attached to a youtube link before them and are not "visible" to the user after the converting.

**Test:**
- new post with classic block
- switch to html mode of classic block
- add html text shown below
- switch to visual mode
- select "convert to blocks"

**HTML before:** (links exist)
```html
<p>https://www.youtube.com/watch?v=2DkaLmUHYOw&amp;rel=0</p>
<address><a href="http://www.wope.net" target="_blank" mce_href="http://www.wope.net">www.wope.net</a></address>
<address style="text-align: justify;" mce_style="text-align: justify;"><a href="http://www.mediaresourcegroup.de" target="_blank" mce_href="http://www.mediaresourcegroup.de">www.mediaresourcegroup.de</a><p></p>
<p>Foto/Text/Video: Markus Wilmsmann</p>
</address>
```

**HTML after:** (links are added to youtube link)
```html
<!-- wp:core-embed/youtube {"url":"https://www.youtube.com/watch?v=2DkaLmUHYOw\u0026rel=0www.wope.netwww.mediaresourcegroup.de"} -->
<figure class="wp-block-embed-youtube wp-block-embed"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=2DkaLmUHYOw&amp;rel=0www.wope.netwww.mediaresourcegroup.de
</div></figure>
<!-- /wp:core-embed/youtube -->

<!-- wp:paragraph -->
<p>Foto/Text/Video: Markus Wilmsmann</p>
<!-- /wp:paragraph -->
```

**Comment by susanpaigen** [comment] 2018-10-30 18:51
As an everyday user, preserving inline markup during "convert to blocks" is critical to making the transition to Gutenberg. I manage a college website with around 350 active pages. At least 80 - 90% of them use inline HTML for styling, primarily <span class="something">. If that all gets wiped out, "convert to blocks" is not an option. Having to manually create each block, and then copy and paste each chunk of content manually, will be a very time-consuming project! This is not blog content, with headings, straightforward paragraphs, and a few images. Many of our pages are very information heavy, and text formatting is an important tool for keeping pages scannable and not too intimidating.

**Comment by aduth** [comment] 2018-11-05 20:21
This is made challenging by the fact that at the root of this conversion feature is the raw handler, which is also responsible for adapting pasted content from external sources to blocks. The HTML received by these sources (e.g. Google Docs) is littered with attributes and markup which makes sense only in the context of Google Docs, and not as a standalone document. This is a major part of the reason the filtering is as strict as it is.

For example, consider an input document: 

https://docs.google.com/document/d/1wwL4H10bDUDAiYVAczLthGCdwxsNZ9YhWpWwO-YId_w/edit?usp=sharing

Whose copied text yields the pasted HTML:

```html
<meta charset='utf-8'><meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6a3f5726-7fff-f826-dcd7-8eef2659d75a"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><a href="https://drive.google.com/drive/u/0/folders/1k4bWkN088Hte1mehmPkKZHbois4Zjsar" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(View All Agendas)</span></a></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Slack Transcript:</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> TBD</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Summary Notes:</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> TBD</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Note Taker:</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> TBD</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><hr /></p><br /><br /></b>
```

So while filtering the phrasing content schema could provide some improvement to classic block conversion, it might also inadvertently reintroduce some of the unwanted markup from these other sources.

Perhaps then if we consider the classic conversion to be exempt to filtering, or conversely the paste handling to be exceptionally strict, we could do one of the following:

- Bypass schema validation for raw handling of classic conversion
- Allow a `'raw'` transform ([specifically paragraph](https://github.com/WordPress/gutenberg/blob/dfc2b5ff3915bab793fff1410136eda1587e51ff/packages/block-library/src/paragraph/index.js#L94-L104)) to receive the "purpose" of transform (paste vs. convert) as an argument to vary the schema it produces.

cc @iseulde : Since I'm not as familiar with the raw handling, have these sorts of approaches been considered previously?

**Comment by iseulde** [comment] 2018-11-05 20:41
Sounds like this is a duplicate of #6102. We should close one of these. I'll look into distinguishing paste from block conversion asap. @aduth bypassing the schema validation, or partly, seems fine. We can assume the data has already been validated and is there by intention.

**Comment by aduth** [comment] 2018-11-05 20:42
Let's close in favor of #6878 for technical implementation.

**Comment by danielbachhuber** [comment] 2018-11-05 21:18
Let's keep this open until the issue is fully addressed, and then we can use this issue to verify the implementation is complete.

Here's a prior example of an issue that was closed prematurely https://github.com/WordPress/gutenberg/issues/6648#issuecomment-433341838

**Comment by iseulde** [comment] 2018-11-05 22:16
@danielbachhuber This is a complete duplicate. Resolving one will resolve the other. The other issue you mention seems to contain several action items.

**Comment by iseulde** [comment] 2018-11-05 22:16
I'll close the other one then in favour of this.

**Comment by susanpaigen** [comment] 2018-11-05 22:40
1. As a front end user, it seems like 'paste' and 'convert to blocks' should be structurally different actions.
2. However, there also needs to be a way to 'paste' and keep formatting and css, so you can copy formatted chunks of content from one page to another. With the current behavior, the only way I can see to do this would be to make almost every block 'custom html'.
3. Also need a way to preserve <div> markup, including classes.
4. From a broader perspective - maybe what's needed is a version of 'convert to blocks', either built in or a plugin, that gives the user much more granular control over which type of block each chunk is converted to and what is preserved in the process.

**Comment by lkraav** [comment] 2018-11-06 09:11
I've also found "the cleanse" helpful in some cases. Would certainly be nice if there was a choice for "retain or clean" markup. But every `if` statement costs $10K as we all know.. :)

**Comment by iseulde** [comment] 2018-11-06 12:20
PR: #11539.

**Closed** 2018-11-07 09:49 UTC
Labels: Backwards Compatibility, Block Conversion, Blocks, [Component] Raw Handling, [Component] Rich Text
