### ISSUE TITLE
Can't save draft

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1672] opened 2017-07-03 16:38 UTC
I tried to search in issues but didn't find a related ticket to the bug (no separate autosave feature discussion and Save button logic/position) I'm talking about.

Currently, when writing a post from scratch using Gutenberg I can't save the draft. There is no Save button in top left corner, and there is no autosave feature yet, thus all the content that I type is not saved until clicked Publish. Even Preview link doesn't save a revision (is this may be considered a feature request?), and I see on front-end only the initial empty state of a post, without my text.

So, right now, I can't figure out how to save a draft while writing a post to be able to come back to it later before publishing.

**Comment by swissspidy** [comment] 2017-07-03 21:18
There really should be a Save link in the top left corner as soon as you edit something in a post. Does it really not show to you? Can you perhaps share a screenshot?

**Comment by elzette** [comment] 2017-07-04 14:36
When I started setting up a post it was not obvious where the Save button is. It is not a button and it felt uncomfortable for me top left.
Should the Save as a button rather be somewhere with the other actions?
![screen shot 2017-07-04 at 15 36 02](https://user-images.githubusercontent.com/2685390/27834362-931670b4-60ce-11e7-9d0a-cdd2284de11d.png)

**Comment by swissspidy** [comment] 2017-07-04 14:48
> Should the Save as a button rather be somewhere with the other actions?

That came up before in #1295.

**Comment by slaFFik** [comment] 2017-07-04 17:29
@swissspidy 
I don't know which screenshot you request, there is just no Save button in top left corner as it used to be with Gutenberg v0.1.

![image](https://user-images.githubusercontent.com/282234/27839102-7b843502-60f7-11e7-814a-960e88844cfb.png)

**Comment by swissspidy** [comment] 2017-07-04 19:07
Weird that it‘s empty. Can you give us some more info? Like what browser, OS, WordPress version, plugin version are you using? Are there any errors in the browser console? What happens if you disable all other plugins?

**Comment by slaFFik** [comment] 2017-07-04 20:58
Chrome 58, Windows 10 with all updates, WP 4.8, Gutenberg 0.3.0, no errors in console.
![image](https://user-images.githubusercontent.com/282234/27842644-6bad21d0-6114-11e7-8be1-67da2ccf2bfa.png)

In Firefox Save + Visual/Text switcher appears after opening the Developer Console and closing it.
![bug](https://user-images.githubusercontent.com/282234/27842671-b1e4d33c-6114-11e7-916a-9d4a7981d624.gif)

**Comment by Kluny** [comment] 2017-09-04 12:01
I was also wondering how to save a post as draft. Clicking the "publish" button is quite risky!

![screen shot 2017-09-04 at 13 57 06](https://user-images.githubusercontent.com/310102/30025590-7cb429de-9179-11e7-8e1f-b448d9a45486.png)

**Comment by aduth** [comment] 2017-09-27 17:13
In these cases where the Save button is not appearing, are you certain that the post is not published? The Save button is not intended to show for published posts, though I can see that we might want to be more explicit about the current post status to make this clearer (or better consolidate the save behaviors).

**Comment by aduth** [comment] 2017-10-04 17:28
Going to close this as suspected to have been resolved in recent versions, being unable to reproduce the original issue. Changes have been made to the CSS layout of these components and more are planned. If you're still encountering this, let me know and we can look to reopen.

**Comment by youknowriad** [comment] 2017-10-04 17:44
Reopening, you can reproduce this on large screens (but without full screen)

**Closed** 2017-10-05 07:25 UTC
Labels: [Status] Needs More Info, [Type] Bug

**Comment by CantonJester** [comment] 2017-10-10 00:09
Save button disappeared on me when I had already published a draft of a post. The 'publish' button apparently did not possess save functionality beyond the initial publishing, either.

**Comment by TechBae** [comment] 2018-10-15 09:53
I am facing the same issue from yesterday on my website [http://www.techbae.com](url)

Whenever I click on **Save as Draft** button , it loads for some time and then shows the message, "**_Connection Lost. Saving has been disabled until you're reconnected. We're backing up this post in your browser, just in case._**" It then loads the website for forever. While, when I refresh the page, everything works fine but the content is gone. FYA, my internet works fine. Every other sites or any other feature in WordPress is working fine. It's really frustrating.

I tried changing the browser, internet connection, even tried opening WordPress in Incognito Mode. Still, the problem remains the same. Any help on this?
