### ISSUE TITLE
Data: Stores become unresponsive when batched actions trigger an error

### ISSUE THREAD

**Issue by Mr2P** [WordPress/gutenberg#62311] opened 2024-06-05 04:27 UTC
### Description

Possible solution: change from `catch` statement to `finally` statement in this line https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/resolvers.js#L298

### Step-by-step reproduction instructions

Execute `useEntityRecords('root', 'site')` inside the edit function of a block.

### Environment info

WordPress 6.6 beta 1
Twenty-Twenty Four
Chrome
Desktop with Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2024-06-05 05:39
Thanks for reporting the issue, @Mr2P!

Can you provide more details for the reproduction steps? What should I test after placing `useEntityRecords` in the block edit component?

Update: I was able to reproduce the issue.

Note: The `site` entity doesn't support fetching a list of entities (`getEntityRecord`), so you should use the `useEntityRecord` hook for it.

**Comment by Mr2P** [comment] 2024-06-05 06:42
@Mamaduka In my block, I need to fetch all public setting fields as follows:
`const { records, isResolving } = useEntityRecords(
  "root",
  "site",
  { per_page: -1 },
);`
It worked well before this commit [getEntityRecords: batch actions](https://github.com/WordPress/gutenberg/commit/d5790098bb6d11a932fd0e0269b5a1ea5c9d41d2) in Gutenberg version 18.2.0. Someone changed from `finally` to `catch` caused this issue. I’m not sure why it was changed to `catch`, but I believe that reverting it back to `finally` will resolve the issue.”

**Comment by Mamaduka** [comment] 2024-06-05 07:01
@Mr2P, the `site` has only a single entity with settings provided as its properties and no pagination. Using `useEntityRecord( 'root', 'site' )` should give you the same results.

#60591 indeed introduced the behavior change, but it is not a cause of the bug; it only highlighted one.

There are two issues:
1. Calling `getEntityRecords( 'root', site' )` will throw an error. Because it doesn't return an entity list (Related #61348).
2. `registry.batch` lacks error handling. It will pause store emitters, but they're never resumed due to error.

cc @ellatrix, @jsnajdr, @youknowriad

**Comment by Mr2P** [comment] 2024-06-05 08:28
> @Mr2P, the `site` has only a single entity with settings provided as its properties and no pagination. Using `useEntityRecord( 'root', 'site' )` should give you the same results.

@Mamaduka Thank you for this information.

**Comment by Mamaduka** [comment] 2024-06-05 14:01
@Mr2P, the main issue should be resolved via #62322.

I'm going to re-open the issue since it's important to resolve `reducer` warnings caused by the selector `getEntityRecords( 'root', site' )` call.

**Closed as completed** 2024-06-06 14:48 UTC
Labels: [Type] Bug, [Status] In Progress, [Package] Data
