### ISSUE TITLE
Shortcode block seems not to work with full site editing

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#21397] opened 2020-04-04 07:38 UTC
**Describe the bug**
When a shortcode block is part of some content being rendered through a `wp_template`, either in the template itself or in the post content being rendered through the `wp:post-content` block, the shortcode does not work.

If the shortcode block is directly part of the `wp_template`, the shortcode input is directly output as if the filter is not being applied.

If the shortcode block is part of the post content being rendered, the shortcode input disappears but the expected output of the shortcode does not take its place.

**To reproduce**
1. Turn on full site editing
2. Make a `wp_template` and include a shortcode block
3. Invoke the template from the front end
4. See the input of the shortcode directly output on the front end instead of the expected output

**OR:**
1. Turn on full site editing
2. Make a `wp_template` and include a `wp:post-content` block
3. Include a shortcode block in any post to be rendered by the template
4. Invoke the template from the front end
5. See the shortcode disappear from the front end with no output

**Expected behavior**
The shortcode should be processed in either case to display the expected output of the shortcode.

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Browser Firefox 73.0.1

**Additional context**
- Gutenberg 7.8.1

**Comment by talldan** [comment] 2020-08-18 05:30
Closing as a duplicate of #19278

**Closed by talldan** 2020-08-18 05:30 UTC
Labels: Needs Testing, [Feature] Full Site Editing, [Feature] Shortcodes
