### ISSUE TITLE
I am having trouble with formatting

### ISSUE THREAD

**Issue by prwhitney1** [WordPress/gutenberg#10324] opened 2018-10-04 01:24 UTC
My last post I wrote with Guttenberg and never touched old editor.  Now, every page on my blog:  archives, ask a question, about us,..... is in Guttenberg format except the page that comes up when someone enters my website.  The one i published today.  It is in old format.

This latest I decided on no sidebars, but everyone one of my previous pages done under old editor comes out with no sidebar the way I want my home page

**Comment by designsimply** [comment] 2018-10-04 03:05
It's hard to tell exactly what is going wrong since I don't know what the old format you're talking about looks like compared to the current view. I would like to ask some clarifying questions.

> Now, every page on my blog: archives, ask a question, about us,..... is in Guttenberg format except the damn page that comes up when someone enters my website.

What do you mean Gutenberg format? Do you mean the sidebar is missing from the right? Do you mean galleries don't look the same? Do you mean paragraph formatting has changed? What are the specifics?

> This latest I decided on no sidebars, make very graphic and shit comes out the other end.

To clarify, you changed a setting in your theme to turn off sidebars and added graphics but the graphics don't look right?

> Every one one of my previous pages done under old editor comes out with no sidebar the way I want my home page.

I checked an older post and I see it currently does not have a sidebar and the home page does have a sidebar. Is your goal to take the sidebar off of the home page?

**Comment by tofumatt** [comment] 2018-10-04 03:39
@prwhitney1 In the future: please describe your issue in the issue title more clearly as it will help us triage and address the issue.

I would ask that you review our [contributor Code of Conduct](https://wordpress.org/about/etiquette/). Please refrain from using aggressive, offensive language when reporting issues. Please also refrain from addressing the project's team aggressively. We're here to help and it is unnecessary to swear at the project when reporting an issue.

I've edited your comments to remove the offensive wording. If you could clarify the issue you're having we'll do our best to help out. Thanks! 🙂

**Comment by designsimply** [comment] 2018-10-05 12:04
Closing as a duplicate of #10309.

**Closed by designsimply** 2018-10-05 12:04 UTC
Labels: [Status] Needs More Info, [Type] Help Request
