### ISSUE TITLE
Inserter "browse all" not usable with Inner Blocks (Columns, Social Links)

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#26208] opened 2020-10-16 15:59 UTC
**Describe the bug**

When using an InnerBlocks (Columns or Social Links are two examples) if you click "browse all" from the inserter it opens a sidebar with the full inserter and then when selecting a block it creates a new block not a part of the InnerBlocks.

Possibly related to change in #24429

**Screenshots**

![columns-inner-blocks](https://user-images.githubusercontent.com/45363/96281171-d39cb500-0f8d-11eb-8ab1-303ceed56975.gif)

**Comment by shaunandrews** [comment] 2020-10-16 16:02
Can confirm. This is particularly annoying when the set of inner blocks are restricted, like in the case of the Social Icons block. It makes it impossible to know what blocks are supported.

**Comment by gziolo** [comment] 2020-11-08 05:22
It looks like a duplicate of https://github.com/WordPress/gutenberg/issues/24403.

**Closed** 2020-11-08 05:23 UTC
Labels: [Feature] Inserter, [Feature] Nested / Inner Blocks, [Type] Bug
