### ISSUE TITLE
Site Editor: Global Style Button block Shadow presets is empty

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#48061] opened 2023-02-14 06:14 UTC
### Description

The Shadow presets popover is empty when trying to apply them to a Button block in the Global Style.

First reported on trac https://core.trac.wordpress.org/ticket/57708

It seems this is a core-specific issue, the problem does not affect the Gutenberg 15.1 plugin.

### Step-by-step reproduction instructions

1. Activate a block theme (TT3 or other)
2. Go to Global Styles
3. Select Button block to customize
4. Select Shadow property
5. Observe the Shadow presets popover is empty

### Screenshots, screen recording, code snippet

![shadow-block](https://user-images.githubusercontent.com/79677758/218653715-b3103362-921f-43c2-bf91-19358bc55ae6.gif)

### Environment info

WP 6.2 beta 1, Firefox 109.0.1, Chrome 110.0.5481.78, Windows 11, TT3 & Powder themes.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-02-14 14:13
@franzaurus thanks for reporting. I am able to replicate in Beta 1, but the issue is resolved in Gutenberg trunk and will therefore get updated in Beta 2. Therefore, I am going to close this out. Thanks!

**Comment by franzaurus** [comment] 2023-02-15 01:43
@ndiego I find the problem is still happening in Beta 2.

**Comment by ndiego** [comment] 2023-02-15 02:19
I see that too, thanks @franzaurus. Something must not have been backported. I will look into it.

**Comment by Mamaduka** [comment] 2023-02-22 07:11
This needs another core to backport. I'll handle that.

Edit: I created a core PR to fix the bug - https://github.com/WordPress/wordpress-develop/pull/4114. I will close this issue since the problem doesn't exist in the Gutenberg plugin.

**Closed as completed** 2023-02-22 07:45 UTC
Labels: [Type] Bug, Global Styles

**Comment by hellofromtonya** [comment] 2023-02-22 14:43
The fix is from PR https://github.com/WordPress/gutenberg/pull/46502 and [this commit](https://github.com/WordPress/gutenberg/commit/d9da1250c77d3dc083729b72b8143dfc7bc222ba#diff-ba57fd27dc15a6079df31427f442f760cbe4035a941cfb1a4763c7cf90766b15).
