### ISSUE TITLE
IE11: Gallery block doesn't show

### ISSUE THREAD

**Issue by tg-ephox** [WordPress/gutenberg#3586] opened 2017-11-21 07:08 UTC
## Issue Overview

Gallery block doesn't appear, works correctly though.  Can upload an image and view it in another browser.

## Steps to Reproduce (for bugs)

1. Add Gallery block
2. Upload Image

**Doesn't show**

## Expected Behavior

Displays as in other browers.

## Current Behavior

Doesn't display.

## Possible Solution

Probably CSS issue

## Screenshots / Video

![screen shot 2017-11-21 at 5 02 05 pm](https://user-images.githubusercontent.com/30682649/33059016-254c7cda-cede-11e7-8486-4c8e993ecc64.png)
The Gallery block is the last block that is cut off.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jeffpaul** [comment] 2018-03-22 19:51
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521735322000202)._

**Comment by jorgefilipecosta** [comment] 2018-03-29 14:07
The crash is not happening but the block still have problems in IE11.

**Comment by aduth** [comment] 2018-03-29 14:10
@jorgefilipecosta Can you enumerate the problems?

I had seen in some brief testing that there was significant unexpected vertical stretch of images in IE11.

**Comment by jorgefilipecosta** [comment] 2018-03-29 14:18
> I had seen in some brief testing that there was significant unexpected vertical stretch of images in IE11.

Yes, that's it the images get stretched:
<img width="736" alt="screen shot 2018-03-29 at 15 17 26" src="https://user-images.githubusercontent.com/11271197/38093975-6c4d3260-3364-11e8-8b66-afecbf9917e6.png">
In the front end the problem also happens.

**Comment by jorgefilipecosta** [comment] 2018-03-29 14:20
But no crash at all, not certain If we should close the issue in this case, as the crash was probably caused by other problem that as fixed meanwhile.

**Comment by aduth** [comment] 2018-03-29 14:34
Is the other issue tracked?

**Comment by jorgefilipecosta** [comment] 2018-03-29 15:17
Yes, it is https://github.com/WordPress/gutenberg/issues/5504.
So I'm closing this issue for now.
Thank you @tg-ephox for reporting this issue, it was probably solved as a side effect of other change.

**Closed** 2018-03-29 15:17 UTC
Labels: Browser Issues, Needs Testing, [Type] Bug
