### ISSUE TITLE
FSE: Query block. Clicking the post title (link) leads to weirdness

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30941] opened 2021-04-17 22:57 UTC
## Description
Site Editor:
Adding a Query block that also contains a Post title block. I clicked the title and it refreshed the Site Editor and showed some weird behavior. I had to exit the Site Editor and re-enter.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to the Site Editor (TT1)
2. Add a new Query block. Add Post title.
3. Click the second title. A link is activated.
4. Page is refreshed showing some weird graphical element placements.

## Expected behaviour
I was expecting that clicking the Post title would not lead to a refresh of the Site Editor.

## Actual behaviour
Site Editor became refreshed.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/5323259/115128766-70ddb200-9fe0-11eb-807a-1d98ca5f65d1.mp4

Opened the console:

https://user-images.githubusercontent.com/5323259/115128814-d9c52a00-9fe0-11eb-87ee-9a04548bcf9b.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1

## Device information
- Device: Desktop
- Operating system: OSX 10.15.7
- Browser: Chrome

**Comment by carolinan** [comment] 2021-04-18 00:15
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/30647

**Closed as completed** 2021-04-18 00:15 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Query Loop
