### ISSUE TITLE
Seperator: Wide line does not have a default color

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52206] opened 2023-07-01 14:52 UTC
### Description

If the theme does not have any custom colors yet and the default colors are turned off, the wide line is invisible.
Default and Dots styles work.

### Step-by-step reproduction instructions

1. Create a new theme without any colors
2. Insert the separator block
3. Chose the style "Wide line"

### Environment info

- WP 6.2.2
- GB 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment] 2023-07-01 15:02
Seems also to be the case when theme.js has custom colors.

Here's the block markup:

```html
<!-- wp:query {"queryId":4,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"default","columnCount":3}} -->
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:post-featured-image {"isLink":true,"align":"wide"} /-->

<!-- wp:group {"style":{"position":{"type":""}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:post-title {"level":3,"isLink":true} /-->

<!-- wp:group {"style":{"spacing":{"blockGap":""}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:post-author-name {"isLink":true,"fontSize":"Info-md"} /-->

<!-- wp:post-date {"fontSize":"Info-md"} /-->

<!-- wp:post-terms {"term":"category","fontSize":"Info-md"} /-->

<!-- wp:post-terms {"term":"post_tag","fontSize":"Info-md"} /--></div>
<!-- /wp:group -->

<!-- wp:post-excerpt /-->

<!-- wp:read-more /-->

<!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator has-alpha-channel-opacity is-style-wide"/> 
<!-- /wp:separator -->

<!-- wp:separator -->
<hr class="wp-block-separator has-alpha-channel-opacity"/>
<!-- /wp:separator -->

<!-- wp:separator {"className":"is-style-dots"} -->
<hr class="wp-block-separator has-alpha-channel-opacity is-style-dots"/>
<!-- /wp:separator --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:query-pagination {"paginationArrow":"chevron","align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination --></div>
<!-- /wp:group -->

<!-- wp:query-no-results -->
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"placeholder":"Add text or blocks that will display when a query returns no results."} -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- /wp:query-no-results --></div>
<!-- /wp:query -->

```

**Comment by carolinan** [comment] 2023-07-02 10:46
Hi!
This problem is unrelated to the color, the separator has no width when it is placed inside a row block.
I am closing this as a duplicate of: 
https://github.com/WordPress/gutenberg/issues/47993

**Closed as not planned by carolinan** 2023-07-02 10:46 UTC
