### ISSUE TITLE
Theme Twenty-Twenty Two issue in image block in styles option

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/gutenberg#38441] opened 2022-02-02 09:54 UTC
### Description

When we choose Image block we have the option in sidebar for styles
If we choose any styles(Default, Rounded) that is reflected on image but in the sidebar that option of styles(Default, Rounded) is not seen properly.

### Step-by-step reproduction instructions

Go to Image Block
In the right side Go to Styles option (Default, Rounded)
There is some issue. It is not looking perfectly
I have attached  the screenshot for better understanding   

### Screenshots, screen recording, code snippet

<img width="1440" alt="Screenshot 2022-02-02 at 11 25 13 AM" src="https://user-images.githubusercontent.com/97427256/152130886-136cd9f9-1157-4eec-adfd-1d48c62fcb29.png">

### Environment info

WordPress Version : 5.9

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment] 2022-02-02 14:16
Please see: https://github.com/WordPress/gutenberg/issues/38448#issuecomment-1027983082

**Comment by talldan** [comment] 2022-02-03 02:05
So the issue is that the previews for Default and Rounded are not showing the full image?

It looks similar to an issue that was mentioned for the block patterns (https://github.com/WordPress/gutenberg/issues/37573#issuecomment-1020685935).

**Comment by kajalmultidots** [comment] 2022-02-04 10:00
Hi @talldan 

So the issue is that the previews for Default and Rounded are not showing the full image?
**Yes Exactly**

**Comment by skorasaurus** [comment] 2022-02-04 18:28
heavily related: https://github.com/WordPress/gutenberg/issues/38473

**Comment by annezazu** [comment] 2022-02-09 08:15
With Gutenberg 12.5.4, the Styles show a nice preview on hover:

<img width="652" alt="Screen Shot 2022-02-09 at 12 08 20 AM" src="https://user-images.githubusercontent.com/26996883/153152029-3e3be1a4-440c-4abf-a1e5-a5939bd4c987.png">

With just WordPress 5.9, I'm not able to replicate what you're describing:

<img width="1145" alt="Screen Shot 2022-02-09 at 12 14 33 AM" src="https://user-images.githubusercontent.com/26996883/153153596-3cf04ead-4a64-4ce0-9693-cedde8725c6e.png">

Are others able to replicate this?

**Comment by HILAYTRIVEDI** [comment] 2022-03-22 08:02
I think we can close this ticket as the UI is proper in the latest release.

**Closed as completed** 2022-03-22 08:15 UTC
Labels: [Block] Image
