### ISSUE TITLE
Error after clicking create new post

### ISSUE THREAD

**Issue by rgllm** [WordPress/gutenberg#8456] opened 2018-08-03 17:15 UTC
**Describe the bug**
After creating a new post when clicking the categories box the editor encounters an unexpected error.

**To Reproduce**
1. Install the try version of Gutenberg via core
2. Click on new post
3. See error

**Screenshots**
![screenshot 2018-08-03 at 18 08 04](https://user-images.githubusercontent.com/9056941/43655881-4157e710-9748-11e8-8b72-221064b1635a.jpg)
Video: [https://imgur.com/a/vnxwWHx](https://imgur.com/a/vnxwWHx)

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - OS: Mojave
 - Browser: Chrome dev 69.0.3497.23

**Error Log**
TypeError: Cannot read property 'show_ui' of undefined at site/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533315246:12:302843 at i (site/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:6:91) at An.filter (site/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:99:338) at site/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533315246:12:302808 at yh (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:96:396) at lg (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88) at mg (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386) at gc (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202) at vb (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230) at
 ub (site/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)

P.S: I hid the site url

**Comment by designsimply** [comment] 2018-08-03 23:41
Thank you for including the console error and a screenshot! I am also adding the error text from your screenshot for reference:

<blockquote>The editor has encountered an unexpected error.</blockquote>

I tested WordPress 4.9.8 and Gutenberg 3.4.0 with the latest stable releases of Chrome 67.0.3396.99 and macOS 10.13.6 and am unable to reproduce the problem in that environment.

I noticed you mentioned this happens "when clicking the categories box" but I couldn't see that in your video and you didn't mention it in the steps. Did you mean the "Add New" button?

What happens if you click the "Attempt Recovery" button below the error?

What happens if you click the "Add New" post button and then reload the page?

I saw a similar error reported at https://github.com/WordPress/gutenberg/issues/8412 but I am not sure whether the resolution there is related. If you are using CloudFlare, there's a problem with the CloudFlare WAF that they're working on a fix for and there's a [workaround here](https://github.com/WordPress/gutenberg/issues/2704#issuecomment-41009093) that you can use.

**Comment by youknowriad** [comment] 2018-08-04 08:02
Hi there!

I suspect this probably happens because some plugin or code is:

 - tweaking or disabling the REST API endpoints (a security plugin can do that)
 - adding custom taxonomies that are not available in REST (`show_in_rest` => false).

**Comment by rgllm** [comment] 2018-08-04 15:30
@designsimply the error initial occurred just when I clicked the categories box. After some attempts it started to happen when creating a new post.  
If I click "Attempt Recovery" it reloads the page and gives the same error.
If I click "New Post" it give the same error (initial it successful created a new post).
Yes, I'm using CloudFlare. Any other information you need I'm pleased to help.

**Comment by youknowriad** [comment] 2018-08-04 15:39
@rgllm yes, there's a workaround you can attempt, it's detailed here https://github.com/WordPress/gutenberg/issues/8441#issuecomment-410431269 

we contacted Cloudflare to fix these issue globally.

I'm going to closing this one as it's a duplicate of other similar issues #8441

**Closed by youknowriad** 2018-08-04 15:39 UTC
Labels: [Status] Needs More Info
