### ISSUE TITLE
Title box problem in the post editor

### ISSUE THREAD

**Issue by marcorroma** [WordPress/gutenberg#39292] opened 2022-03-08 17:25 UTC
### Description

Hi, I have this problem. I try to explain myself.
It has happened to several of my colleagues that while writing a post it is no longer possible to change the title of the post editor Gutenberg.
Even if the title was changed a few seconds earlier.
This happens both if you want to edit a post, and if you want to create a new post.
Clicking on the title box does not show the cursor.
No problem if I try to edit the post text.
Is this a known problem?

I noticed that the title code in the editor has been changed. Maybe it is a problem related to this?

i have this problem since i updated to the latest version of wordpress 5.9.1. Until a few days ago, version 5.8.3 was used.

My colleagues and I are using Chrome, version 99.0.4844.51

Thank you

### Step-by-step reproduction instructions

Indications already explained in the description

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment] 2022-03-09 08:03
Hi, @ellatrix 

You fixed this or a similar issue with content editable, if I remember correctly. Is it something we should or can backport into a minor release?

**Comment by marcorroma** [comment] 2022-03-09 09:30
> Hi, @ellatrix
> 
> You fixed this or a similar issue with content editable, if I remember correctly. Is it something we should or can backport into a minor release?

Hi, the problem is recent and has not been solved.
I am waiting for a solution ...

**Comment by smeans** [comment] 2022-03-11 06:32
I've run into the same issue recently using 5.9.2 in Chrome. I just found out that if I go into developer tools and manually set `contenteditable` on the `h1 `tag I can rename the post, fwiw.

**Comment by marcorroma** [comment] 2022-03-11 08:04
> I've run into the same issue recently using 5.9.2 in Chrome. I just found out that if I go into developer tools and manually set `contenteditable` on the `h1 `tag I can rename the post, fwiw.

Thanks, but I hope this bug will be fixed by the Wordpress developers

**Comment by skorasaurus** [comment] 2022-03-13 19:03
Thanks for reporting. Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

**Comment by marcorroma** [comment] 2022-03-14 11:51
> Thanks for reporting. Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

Hi, I don't use the Gutenberg plugin. I can't reproduce the problem now.
I don't usually post, but my colleagues post from different PCs and they have this problem.
Even today they report this problem to me, after updating to Wordpress 5.9.2.
It is a problem that is encountered not always, but only sometimes.
How can I solve the problem? Or how can I reproduce the problem?
PS. I can't disable all plugins, if I did I would risk the job :)

**Comment by afercia** [comment] 2022-03-16 15:36
Note: this issue has been reported also on Trac, see https://core.trac.wordpress.org/ticket/55244 and can be reproduced on latest trunk with no plugins activated. It appear to happen after selecting all blocks with Ctrl (Cmd) + A. 
It would be great to confirm this has been fixed in latest Gutenberg.

Maybe related: https://github.com/WordPress/gutenberg/pull/38820

**Comment by marcorroma** [comment] 2022-03-16 17:36
It's the exact same problem. Thank you

> Note: this issue has been reported also on Trac, see https://core.trac.wordpress.org/ticket/55244 and can be reproduced on latest trunk with no plugins activated. It appear to happen after selecting all blocks with Ctrl (Cmd) + A. It would be great to confirm this has been fixed in latest Gutenberg.
> 
> Maybe related: #38820

**Comment by skorasaurus** [comment] 2022-03-16 18:05
Thanks @marcorroma ; could you edit your issue's title to something that more clearly describes your issue like "Unable to edit the post title in the post editor?

**Comment by skorasaurus** [comment] 2022-03-16 18:34
thanks for the detailed reproduction instructions in the trac ticket; 

Like @afercia ; I am able to reproduce this consistently when the gutenberg plugin is deactivated; but I am unable to reproduce this when Gutenberg plugin ( 12.7.2 ) is installed and activated. 

Would whatever fixed this be worthy of  5.9.x inclusion?

**Comment by Mamaduka** [comment] 2022-03-16 18:36
My best guess is that this PR fixed issue #38821. But it would be nice to get confirmation from @ellatrix.

**Comment by marcorroma** [comment] 2022-03-17 10:16
> Thanks @marcorroma ; could you edit your issue's title to something that more clearly describes your issue like "Unable to edit the post title in the post editor?

I have the same problem if I go through the procedure it says here step by step:
https://core.trac.wordpress.org/ticket/55244#comment:4

**Comment by skorasaurus** [comment] 2022-04-28 20:33
(needs to be tested if it's still present on WP 6.X)

**Comment by skorasaurus** [comment] 2022-08-10 16:25
No longer able to reproduce in WP 6, Gutenberg 13.

**Closed as completed by skorasaurus** 2022-08-10 16:25 UTC
Labels: Needs Testing, [Type] Regression
