### ISSUE TITLE
Blocks: `enqueue_block_editor_assets` not working with the editor's iframe

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [WordPress/gutenberg#41821] opened 2022-06-20 15:58 UTC
### Description

**Actual Status**
Site Editor is loading it's own iframe without loading the CSS registered via [enqueue_block_editor_assets](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/).

**Target Status**
[enqueue_block_editor_assets](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/) should work for site editor iframe, too.

**Explanation**
While function [add_editor_styles](https://developer.wordpress.org/reference/functions/add_editor_style/) seems to be optimized for loading static styles from theme, it's still required for plugins to load (dynamic generated) styles via enqueue_block_editor_assets. Additionally, it won't work for styles loaded from a htaccess-protected website and absolute paths are not supported yet.

Plugins without serving a block are not able to serve styles with "editor_style"-Attribute of "register_block_type"-function.

It would be great to either support absolute paths in [add_editor_styles](https://developer.wordpress.org/reference/functions/add_editor_style/) or add support for [enqueue_block_editor_assets](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/) in site editor.

### Step-by-step reproduction instructions

1. Register CSS via [enqueue_block_editor_assets](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/)
2. Open Page Edit Screen and check if CSS is loaded, if so then:
3. Open Site Editor Edit Screen and check if CSS is loaded in template iframe
4. In my tests, CSS is loaded in editor wrapper, but not in iframe of the loaded template (e.g. header), so styles won't be active there

### Screenshots, screen recording, code snippet

related: https://wordpress.org/support/topic/adding-styles-from-plugins-to-the-editor/

### Environment info

WordPress v6.0.0
Gutenberg v13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by pryley** [comment] 2022-08-12 19:12
i just spent an hour trying to figure out why the block css wasn't loading in the site editor.

Strangely, one of the blocks is loading the stylesheet inside the body tag of the iframe. I have no idea why this block loads the css in the iframe yet the others do not as they are all registered in the same way with the `enqueue_block_editor_assets` hook.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/134939/184427947-7c2a0081-f609-4b4d-b42b-806ed315943e.png">

For now, this is how I'm doing it until this bug is fixed:

```php
function register_block_assets () {
    // wp_register_style ...
}

function register_block_assets_in_site_editor () {
    global $pagenow;
    if ('site-editor.php' === $pagenow) {
        register_block_assets();
    }
}

add_action('init', 'register_block_assets_in_site_editor');
add_action('enqueue_block_editor_assets', 'register_block_assets');
```

See also: https://github.com/WordPress/gutenberg/issues/34763#issuecomment-1029946655

**Comment by pryley** [comment] 2022-08-12 20:08
Looks like the CSS needs to contain `.wp-block` inside the file in order for it to be enqueued inside the iframe.

See: https://github.com/WordPress/gutenberg/issues/40603#issuecomment-1112807162

**Comment by leeshadle** [comment] 2023-01-18 13:13
I'm seeing the same issue.  From what I understand, enqueue_block_editor_assets is for enqueuing UI styles for the editor's interface, not for content.  With that being said, how do we include CSS that isn't tied to a block or that is being globally applied to blocks?  What if there is no way to include a .wp-block selector inside the CSS file?

> Looks like the CSS needs to contain `.wp-block` inside the file in order for it to be enqueued inside the iframe.
> 
> See: [#40603 (comment)](https://github.com/WordPress/gutenberg/issues/40603#issuecomment-1112807162)

For example, I'm loading CSS for GDPR Compliant [Google Fonts](https://fonts.bunny.net/) in the block editor but I have no way of adding a .wp-block selector to the style sheet.

**Comment by mark-c-woodard** [comment] 2023-02-03 21:47
@leeshadle did you find out anything on this issue. I'm running into the same thing with google fonts myself.

**Comment by leeshadle** [comment] 2023-02-03 21:52
@mark-c-woodard Unfortunately I have not.  Please if you find a way I'd love to know.  I've been trying to prevent this issue from arising for 1.5 years with no luck:
[Warning when enqueueing styles for a plugin in iframed Full Site Editor](https://github.com/WordPress/gutenberg/issues/33212)

The same issue applies for [scripts](https://github.com/WordPress/gutenberg/issues/44945) as well...

**Comment by gziolo** [comment] 2023-02-13 13:12
Now that the iframed editor is being rolled out for the post editor screen, this might become a general issue with plugins and the block editor (a similar issue caused by the iframe https://github.com/WordPress/gutenberg/issues/47983). I updated the title of this issue to reflect that.

**Comment by gziolo** [comment] 2023-02-26 06:55
@fabiankaegy proposes in   https://github.com/WordPress/gutenberg/issues/48382 a new utility function that could help with enqueuing scripts for blocks. It’s probably the best way to resolve the issue discussed here as it would make it possible to explicitly expose such scripts to the iframe when we know they are needed by blocks.

**Comment by phil-sola** [comment] 2023-03-23 10:13
Is there any news on this at all? We need to consider both core & custom blocks as well as third party blocks such as ACF blocks etc. which people use. 

Not being able to load relevant JS in the site editor using the current enqueue_block_editor_assets hook is confusing and frustrating when blocks just don't work properly in the site editor. 

I would be very keen to see some kind of fix for this.

**Comment by mark-alexandre** [comment] 2023-04-05 23:25
As of now, I have tested with add_editor_style() and it seems to work properly when callled this way in a plugin :

`add_theme_support( 'editor-styles' );
add_editor_style( plugins_url( 'assets/css/_gutenberg-editor.css', __FILE__ ) );`

I have previously tested with plugin_dir_path() or plugin_dir_url() without success, but plugins_url() works perfectly for me. I really don't know if this will solve the issue for some people here. This will not solve the JS issue, but at least the gutenberg CSS injection will definetely work with it.

Cheers.

**Comment by ellatrix** [comment] 2023-04-07 12:26
Hi! #49655 should be able to address this issue. This PR will load anything enqueued through `enqueue_block_assets` to the iframe and adds a new action `enqueue_block_editor_content_assets` for anything that you want to add to the iframe but not the front-end (editor content specific styles).

The reason we can't add assets enqueued through `enqueue_block_editor_assets` is because this is meant for editor UI styles and scripts. We don't want to add those to the iframe. Ideally you should use `enqueue_block_assets` if your style or script should be added to both the front-end and editor content, and `enqueue_block_editor_content_assets` for only the editor content without front-end.

Hopefully we can merge #49655 soon so it can be tested in the plugin.

**Closed as completed** 2023-04-26 06:23 UTC
Labels: [Feature] Block API, [Feature] Blocks, Needs Technical Feedback
