### ISSUE TITLE
Image placeholder: unfortunate UI for the Upload / Media library dialogue

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#55618] opened 2023-10-25 12:04 UTC
### Description

When a image placeholder is set to a certain pixel size (e.g. width 60px as in the TT4 theme), it's not really possible/intuitive to upload a new image, due to the limited space. Theoretically one could use the scrollbars, but I think there must be a better solution. Maybe opening the "Upload and Media library"  dialogue in a modal if the image width or height is below a certain amount (e.g. 200px)?

### Step-by-step reproduction instructions

1. Try to swap the testimonial image on the TT4 theme

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/62a1d1ac-6cda-412b-9ba9-4adc4f0f6378

### Environment info

- WordPress 6.4-RC2
- GB  16.8.1
- TT4

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment] 2024-05-28 22:12
Closing this out as a duplicate of https://github.com/WordPress/gutenberg/issues/54867 Thanks for opening! Just ran into it today and went to report it.

**Closed as completed by annezazu** 2024-05-28 22:12 UTC
Labels: [Type] Enhancement, [Block] Image
