### ISSUE TITLE
Odd behavior of formatting controls when a proper selection is not made.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#519] opened 2017-04-26 22:16 UTC
I am mostly assuming this stems as an issue with TinyMCE somehow, but bringing it up none the less.  If you select at the bounds of a text selection and use the formatting controls weird things happen.  The state of the buttons also seems to get very confused.  View the screen captures below for a better picture.

Steps to reproduce:

1. Select any block, with an editable component.
2. Select at either the beginning or ending of the text.
3. Click the formatting buttons and as you toggle more you will notice that the state of the buttons gets messed up when you try to toggle all three.  Seems to work perfectly when text is selected properly.

![formatting-controls-odd](https://cloud.githubusercontent.com/assets/16389612/25459469/6401c754-2aac-11e7-9749-3848a4145a38.gif)

**Comment by aduth** [comment] 2017-05-02 19:56
I'm having trouble reproducing this. Are you still seeing this issue in the latest master?

**Comment by aduth** [comment] 2017-05-26 20:52
Still unable to reproduce. Closing, but do reopen if it's still an issue for you.

**Closed by aduth** 2017-05-26 20:52 UTC
Labels: Blocks, [Component] TinyMCE, [Type] Bug
