### ISSUE TITLE
Need add "open in new tab" feature in social share in Gutenberg

### ISSUE THREAD

**Issue by Preciousomonze** [WordPress/gutenberg#25455] opened 2020-09-18 14:23 UTC
***@rkradadiya  noticed in the social share widget there is no option for the "open in new tab" feature.***
This has already been reported on __trac__ , as ticket [51250](https://core.trac.wordpress.org/ticket/51250)
🙂

**Comment by fabiankaegy** [comment] 2020-09-18 15:06
I can take this one and work on a PR.

**Comment by mkaz** [comment] 2020-09-18 20:44
Duplicate of #20707

**Closed by mkaz** 2020-09-18 20:44 UTC
Labels: Accessibility (a11y)
