### ISSUE TITLE
Rename "drawer" site editor menu

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27185] opened 2020-11-23 04:54 UTC
Original ticket by transl8or:
https://core.trac.wordpress.org/ticket/51835

> The word "Drawer"used at https://build.trac.wordpress.org/browser/branches/5.6/wp-includes/js/dist/edit-post.js?marks=4146#L4146
> 
> Is there another english word for Drawer that could be used in that context, and is hopefully better to translate (into german) and understand?
> 
> At the moment I just don't understand what is meant with it, even after researching the net for it. The comment "accessibility text for the nav bar landmark region." is helpful (and maybe not have a dot at the end here?) and I landed here: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html but still no clue how to translate it properly.
> 
> The only thing I could think about is ... Should it describe the behaviour of the navbar, like there are vertical navbars/menus that do slide in and out from the side, like a drawer?
> 
> A clarification or change of word on that would be much appreciated

> I think we should find a better word and replace the word "Drawer" and improve the comment of the string too.

File:
https://github.com/WordPress/gutenberg/blob/master/packages/interface/src/components/interface-skeleton/index.js#L54

**Comment by sabernhardt** [comment] 2020-11-23 04:59
1. For the comment, I'd suggest "accessibility text to describe the site editing navigation menu"
2. Since full site editing is not active in WordPress 5.6, could/should this text string be removed from translations?

**Comment by transl8or** [comment] 2020-11-24 11:27
I add the link to the screenshot again that was provided by @sabernhardt on the trac ticket: 
https://github.com/WordPress/gutenberg/pull/26944#issuecomment-726687081
It is the black "Multi-Level Push Menu" there sliding in from the left.

And after some consideration I think the simplest word to exchange "Drawer" here can just be "**Navigation**".

I mean, is the fact that the menu in this screen area for navigation is a multilevel one and also does have a sliding behavior, like implicated by the word **Drawer**, really import?

[_If the sliding behaviour would be an important information, that should be communicated with that word... here are some more suggestions, where I translated backwards from german to english. 
I hope the english native-speakers here will find the one that suits best in the context of usage._ 

_Navigationsleisten-Einschub_       (in english: **slide-in navigation bar**)
_Menü-Einschub oder Einschub-Menü oder nur "Einschub"_ (in english: **slide-in menu**)
_Slide-In-Navigationsleiste_        (in english: **slide-in navigation bar**)
_Slide-In-Menü_                     (in english: slide-in menu)
_Push-Menü_                         (in english: **push menu**)
_Multilevel-Push-Menü_              (in english: **multilevel push menu**)
_Multilevel-Push-Navigationsleiste_ (in english: **multilevel push navigation bar**)
_Multilevel-Push-Navigationsmenü_ (in english: **multilevel push navigation menu**)

On a more abstract level, as the "_Drawer_" must not necessarily be a menu/navbar, it may just be a "_Sliding-Element_". ]

**Comment by Lewiscowles1986** [comment] 2020-12-01 05:15
As a native UK English person, I believe that `drawer` does sort of work as a name... A lot of the multi-word names here are quite cumbersome and might have other issues.

I did a lazy google on a few of the proposed terms above.

* ["Einschub" "Menü" "UI"](https://duckduckgo.com/?q=%22Einschub%22+%22Men%C3%BC%22+%22UI%22&atb=v229-1&ia=web)
* ["Navigationsleisten" "Einschub" "UI"](https://duckduckgo.com/?q=%22Navigationsleisten%22+%22Einschub%22+%22UI%22&atb=v229-1&ia=web)
*  ["Push" "Menu" "UI"](https://duckduckgo.com/?q=%22Push%22+%22Menu%22+%22UI%22&atb=v229-1&ia=web)
*  ["Navigationsleisten" "UI"](https://duckduckgo.com/?q=%22Navigationsleisten%22+%22UI%22&atb=v229-1&ia=web)

The last two sort of worked, but `Navigationsleisten` was as-expected, quite broad.

Drawer as a term is both vague in the used context to an unfamiliar user, but also specific in a way that has prior art though in the UI community (it may be a lost battle for a perfect name for something generic)

Quick searching for ["ui pattern drawer"](https://duckduckgo.com/?q=ui+pattern+drawer&atb=v229-1&ia=web ) (without quotes) got many interesting links which were this pattern

* https://material-ui.com/de/components/drawers/
* https://www.oracle.com/webfolder/ux/middleware/alta/patterns/Drawers.html
* https://material.io/components/navigation-drawer
* https://www.pinterest.co.uk/amegana/drawer/

This isn't very much different to "kitchen sink" which was a part of the pre-gutenberg editor, which was less global, so I think it's at least a step in the right direction.

["tinymce" "kitchen sink"](https://duckduckgo.com/?q=%22tinymce%22+%22kitchen+sink%22&atb=v229-1&ia=web)

Naming is hard. In-jokes and conventions don't travel, but in the links on drawer, I found that material-ui.com might have done some work which benefits the WordPress community. `Seitliches Menü (Drawer)` -> lateral menu.

Perhaps the name could center around the big-picture purpose, rather than the details which might change, such as:
  - position
  - current animation or interaction patterns

This could be hard as perhaps it's purpose is simply a place to put things.

Interestingly (to me at least), a search on the gutenberg codebase only showed a few occurrences of the word drawer over 6 files

https://github.com/WordPress/gutenberg/search?q=drawer

None really communicate to me the purpose, more the presentation and expected interactions. Searching for the word drawer on WordPress.org also came up with a number of examples, which suggest perhaps the community do "get-it"

https://wordpress.org/support/topic-tag/drawer/

However clicking through issues are related to plugins, themes, traditional navigational menus. I Think this one is about settings rather than navigation right?

https://wordpress.org/plugins/wordpress-sliding-drawer-content-area/

A lot of this centers around "Menu". Would there be a way to focus on that, like in the case of Lateral Menu (Seitliches Menü)?

**Comment by jordesign** [comment] 2023-08-17 10:46
I no longer see any references to 'Drawer' in the front-end code of the Site Editor (which has undergone significant changes since this issue was opened). I'm going to close this issue for now - but please feel free to open with additional details if the issue is still in place.

**Closed by jordesign** 2023-08-17 10:46 UTC
Labels: Internationalization (i18n), Needs Copy Review, [Package] Interface
