### ISSUE TITLE
Gutenberg list block says there is an HTML error when <ol start="number"> is used.

### ISSUE THREAD

**Issue by garikaib** [WordPress/gutenberg#17414] opened 2019-09-12 07:54 UTC
**Describe the bug**
Gutenberg list block says there is an HTML error when <ol start="number"> is used.
**To reproduce**
1. Go to 'Gutenberge editor and add a numbered list'
2. Click on 'Edit HTML' and add the start at number attribute to the list
3. Now click on block three dots and try to go back to editing visually
4. Gutenberg throws an error saying HTML is not valid and attempts to convert it unsuccessfully

**Expected behavior**
A list which starts form the desired number appears in visual editor. Generally numbered lists display differently than they would in the front-end anyway. Changing list type doesn't update in editor you keep seeing lists styled as 1,2,3 instead of a,b,c,d although the front end shows the correct format.

**Desktop (please complete the following information):**
 - OS:  Deepin 15.11
 - Browser Chrome
 - Version  76.0.3809.132

**Additional context**
-Gutenberg Version 6.4.0

**Comment by ellatrix** [comment] 2019-09-16 07:34
I think #17144 fixes this issue? It adds the attributes to the block.

**Comment by garikaib** [comment] 2019-09-16 12:00
I can confirm that there is no way to select ordered list type after testing multiple times with the latest version of Gutenberg (version 6.40 found in the Wordpress.org repos). While there is now an option to choose where to start the numbering from there is no option to select list type. I have tested on my sites and even cranked up a local environment in docker using the 10up image and still don't see it.
![DeepinScreenshot_select-area_20190916135824](https://user-images.githubusercontent.com/7372322/64956204-5e424a80-d88a-11e9-8a3f-30f88c53b6d5.png)
![DeepinScreenshot_select-area_20190916135444](https://user-images.githubusercontent.com/7372322/64956205-5edae100-d88a-11e9-932c-026113cb5d5a.png)

**Comment by swissspidy** [comment] 2019-09-16 13:34
@garikaib Turns out that support for the list type was reverted again so yeah, there is currently no option for it.

See https://github.com/WordPress/gutenberg/pull/15113#issuecomment-521613624 and https://github.com/WordPress/gutenberg/pull/15113#discussion_r309117007

**Comment by garikaib** [comment] 2019-09-16 15:00
Yeah, that sucks. So how do I go about adding the HTML attribute without getting the HTML is invalid error? I have an Academic Notes blog and use both ordered and unordered lists a lot.

**Comment by swissspidy** [comment] 2019-09-16 15:05
You can use the [existing block filters](https://developer.wordpress.org/block-editor/developers/filters/block-filters/) to extend the list block with such an attribute until support for that is added in Gutenberg.

**Comment by youknowriad** [comment] 2019-10-01 09:34
I'm going to close this as a duplicate of #13888 where adding the type support is tracked.

**Closed by youknowriad** 2019-10-01 09:34 UTC
Labels: [Block] List, [Component] Block Validation/Deprecation
