### ISSUE TITLE
Block cannot be previewed error

### ISSUE THREAD

**Issue by byrd** [WordPress/gutenberg#9775] opened 2018-09-11 00:33 UTC
**Describe the bug**
Receive error message: "This block has encountered an error and cannot be previewed." The error began with the most recent update of WP. I tried deactivating all plugins on the site but this didn't resolve the problem.

Gutenberg Version 3.7.0
WP Version 4.9.8

Two errors show up in the console. The first is:
`react-dom.min.82e21c65.js:110 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (react-dom.min.82e21c65.js:142)
    at m (react-dom.min.82e21c65.js:12)
    at ed (react-dom.min.82e21c65.js:65)
    at If (react-dom.min.82e21c65.js:82)
    at v (react-dom.min.82e21c65.js:84)
    at react-dom.min.82e21c65.js:88
    at rd (react-dom.min.82e21c65.js:91)
    at O (react-dom.min.82e21c65.js:90)
    at yh (react-dom.min.82e21c65.js:104)
    at lg (react-dom.min.82e21c65.js:120)`

The second error is:
`Jed localization error: 

Error: Domain `gravityforms` was not found.
s @ index.js?ver=1535740608:1
(anonymous) @ index.js?ver=1535740608:5
s @ index.js?ver=1535740608:1
d @ index.js?ver=1535740608:5
(anonymous) @ core.min.js?ver=1533153378:2307
__webpack_require__ @ core.min.js?ver=1533153378:20
(anonymous) @ core.min.js?ver=1533153378:63
(anonymous) @ core.min.js?ver=1533153378:66
`

**To Reproduce**
Access page within admin area that had a previously registered block added to it.

**Expected behavior**
Should see the content blog in the page editor instead of the error message.

**Desktop (please complete the following information):**
 - OS: IOS & Windows
 - Browser Chrome & Safari

**Comment by youknowriad** [comment] 2018-09-11 09:01
The error message suggest you still have the "gravityforms" plugin active. Which block is causing this issue?

**Comment by byrd** [comment] 2018-09-11 13:28
When I deactivate Gravity Forms, I'm left with this error: 
`react-dom.min.82e21c65.js:110 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (react-dom.min.82e21c65.js:142)
    at m (react-dom.min.82e21c65.js:12)
    at ed (react-dom.min.82e21c65.js:65)
    at If (react-dom.min.82e21c65.js:82)
    at v (react-dom.min.82e21c65.js:84)
    at react-dom.min.82e21c65.js:88
    at rd (react-dom.min.82e21c65.js:91)
    at O (react-dom.min.82e21c65.js:90)
    at yh (react-dom.min.82e21c65.js:104)
    at lg (react-dom.min.82e21c65.js:120)`

Here's a screenshot: https://screencast.com/t/HcmeDJCU

**Comment by youknowriad** [comment] 2018-09-11 13:30
Can you run your code with `SCRIPT_DEBUG = true`? and which block is causing this error? is it all the blocks?

**Comment by byrd** [comment] 2018-09-12 18:06
I get the error. Here's a screenshot for reference: https://screencast.com/t/p6vsPytL 

`Uncaught (in promise) 
Object
code
:
"invalid_json"
message
:
"The response is not a valid JSON response."
__proto__
:
constructor
:
ƒ Object()
hasOwnProperty
:
ƒ hasOwnProperty()
isPrototypeOf
:
ƒ isPrototypeOf()
propertyIsEnumerable
:
ƒ propertyIsEnumerable()
toLocaleString
:
ƒ toLocaleString()
toString
:
ƒ toString()
valueOf
:
ƒ valueOf()
__defineGetter__
:
ƒ __defineGetter__()
__defineSetter__
:
ƒ __defineSetter__()
__lookupGetter__
:
ƒ __lookupGetter__()
__lookupSetter__
:
ƒ __lookupSetter__()
get __proto__
:
ƒ __proto__()
set __proto__
:
ƒ __proto__()`

**Comment by youknowriad** [comment] 2018-09-12 18:13
It's better, I suspect you have a PHP notice/warning that's altering the JSON response of one of the XHR requests. So if you're able to look through the browser's devtools (network tab) and check the api call causing this?

Also, it might be good to check the web server's error log because sometimes the warnings/notices... show up there.

**Comment by SolespireMarcus** [comment] 2018-09-26 23:13
![180926-0001](https://user-images.githubusercontent.com/31710444/46114311-eb3a5280-c1a6-11e8-8b07-0235299d0f57.png)
I am getting the same problem on a clean install of WordPress 4.9.8 and Gutenberg 3.9.0.

**Comment by designsimply** [comment] 2018-10-25 18:11
Are you able to check for error in your browser developer tools inside the Network panel? If you spot something with an error there, can you take a screenshot or copy down the response from any failed API call you see?

**Comment by designsimply** [comment] 2018-11-29 21:11
> To Reproduce
> Access page within admin area that had a previously registered block added to it.

I was unable to reproduce the problem using the following testing steps:

1. Install Yoast SEO 9.2.1.
1. Go to Posts > Add New and add a title.
1. Add an FAQ block (comes with the Yoast plugin).
1. Publish the page.
1. Deactivate & Delete the Yoast plugin.
1. Re-open the post created earlier.

<strong>Result:</strong> I see the following warning message:

> Your site doesn’t include support for the "yoast/faq-block" block. You can leave this block intact, convert its content to a Custom HTML block, or remove it entirely.

![screen shot 2018-11-29 at 2 04 47 pm](https://user-images.githubusercontent.com/1119271/49252015-2bed5c80-f3e0-11e8-8a81-10f178a757ce.png)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=214&action=edit running WordPress 4.9.8 and Gutenberg 4.5.1 and Yoast SEO 9.2.1 using Firefox 63.0.3 on macOS 10.13.6.</sup>

Because updates have been made since this request was originally posted and because I was unable to reproduce the problem in testing, I will close the issue with a note for @byrd to please re-open once you have a chance to keep troubleshooting!

@SolespireMarcus thank you for posting a screenshot. If you aren't seeing the same console errors, then your issue may be a different case. If you are still having trouble, may I please ask you to first make sure you have updated to the latest version of Gutenberg and then open a new issue and include as much information as you can about any errors you can find in your web developer tools console and network panels?

**Closed by designsimply** 2018-11-29 21:11 UTC
Labels: [Status] Needs More Info

**Comment by CarlasHub** [comment] 2018-12-19 08:12
I'm running into the same issue and getting the same error messages. Have you encountered a solution for this @byrd ?
