### ISSUE TITLE
Extra scrollbar appears while editing patterns/template parts whenever there are notices

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#62911] opened 2024-06-27 08:24 UTC
### Description

When editing patterns any notices result in a second scrollbar appearing.

The bug happens because the notices push the editor canvas area off-screen, which triggers a scrollbar.

I'm personally unsure of the right fix. For the normal post editing experience, the editor canvas shrinks when there's a notice, so perhaps the focus mode should do the same?

### Step-by-step reproduction instructions

1. Edit a pattern (post or site editor)
2. Add enough content so that a scrollbar appears
3. Run this JavaScript snippet in your browser console:
```js
wp.data.dispatch( 'core/notices' ).createInfoNotice( 'Notice' );
```

Observe two scrollbars

### Screenshots, screen recording, code snippet

![Screenshot 2024-06-27 at 4 21 31 pm](https://github.com/WordPress/gutenberg/assets/677833/4ea2e1c1-6e29-4f45-b4f9-868145d70093)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2024-06-28 03:19
I was not able to reproduce this issue, maybe it was fixed in a recent commit? Or do I need some special content?


https://github.com/WordPress/gutenberg/assets/54422211/51ab4085-d1c5-450d-9523-e198d5c2bf99

**Comment by talldan** [comment] 2024-06-28 04:24
@t-hamano Interesting, seems like your canvas area didn't get pushed down far enough. Does it still look ok if you add multiple notices?

**Comment by stokesman** [comment] 2024-06-28 04:31
Testing at 55f3a98159, I was able to reproduce but only in the Post editor.

**Comment by talldan** [comment] 2024-06-28 05:15
I see! I'm sure that was broken before. The site editor behaves closer to how I would expect it to work in the post editor, so hopefully there's a clue there for fixing it.

**Comment by stokesman** [comment] 2024-06-28 05:49
One difference between the editors I've noted are these styles applied to the VisualEditor only in the Post Editor:
https://github.com/WordPress/gutenberg/blob/55f3a98159a754cee5162a05852881fa168134a7/packages/edit-post/src/components/layout/style.scss#L1-L4

I found them to be creating a related issue with too many scrollbars for device previews and made #62940 for that. I just tried reproducing this issue on that branch and could not. I'd appreciate any testing or reviews on that 🙇

**Comment by t-hamano** [comment] 2024-06-28 07:08
Ah, I was able to reproduce that issue in the post editor too.

https://github.com/WordPress/gutenberg/assets/54422211/37e235e6-7b73-4801-8592-734504a5ed8d

What we would expect here is for the editor canvas to be lowered by the height of the notification, without causing double scrollbars, like in the site editor, right?

![image](https://github.com/WordPress/gutenberg/assets/54422211/9723c4e4-372b-456b-9c8e-4b26e45d733b)

**Comment by talldan** [comment] 2024-06-28 07:18
@stokesman Thanks - I've approved that PR.

**Closed as completed** 2024-06-28 07:44 UTC
Labels: [Type] Bug, General Interface, Needs Design Feedback
