### ISSUE TITLE
Error when deleting a block

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#15718] opened 2019-05-18 15:14 UTC
**Describe the bug**

I've gotten the following error while removing a block through the block settings. I've not had the chance to debug further. The error happens consistently with the same post on reload, but I'm not sure if I can provide steps to reproduce from a new post.

The block being deleted is a nested block.

Gutenberg 5.7 + Mac n Chrome

```
TypeError: Cannot read property 'name' of null
    at https://ellavandurpe.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1557923878:12:33271
    at c (https://ellavandurpe.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:6:348)
    at ru (https://ellavandurpe.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:67:186)
    at https://ellavandurpe.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1557923878:12:33247
    at Td (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:82:11)
    at be (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:91:479)
    at hi (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:104:202)
    at Qg (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:144:217)
    at Rg (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:145:76)
    at Sc (https://ellavandurpe.com/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:158:109)
```

**Comment by swissspidy** [comment] 2019-05-18 15:55
Sounds like a duplicate of #15458. Can you test whether #15543 resolves the issue you are seeing? Thanks!

**Comment by aduth** [comment] 2019-05-31 17:56
Closing as assumed duplicate of #15458 (since fixed).

**Closed by aduth** 2019-05-31 17:56 UTC
Labels: Block API, [Status] Duplicate, [Type] Bug
