### ISSUE TITLE
Crashed website

### ISSUE THREAD

**Issue by dwj2018** [WordPress/gutenberg#11419] opened 2018-11-02 16:03 UTC
**Describe the bug**
I installed the Gutenberg plugin to try to test it out.  While I liked what I saw in the preview post page, my website and admin page completely crashed when I went away from that page.  I could not get anything to respond.  I had to go into my FTP and remove the plugin in order to get my website to work again.

**Desktop (please complete the following information):**
 - OS: iOS 10.14
 - Browser Chrome
 - Version: 70.0.3538.77

**Comment by designsimply** [comment] 2018-11-02 20:11
That sounds really odd! I haven't heard a report like that before. I would like to I ask a few clarifying questions.

Were you using WordPress 5.0 beta or the Gutenberg plugin at the time the problem happened? If you are using the plugin, can you note the version?

To confirm, the admin page at https://yourdomain/wp-admin/ crashed? Do you recall if there were any error messages on screen when that happened or was the screen completely blank?

On the front end, was there an error displaying on screen or was it blank? What exactly do you mean that it crashed?

Any chance you can find web server error logs corresponding to the time of the problem?

May I ask where your site is hosted and if you have made any customizations to the web server settings?

**Comment by dwj2018** [comment] 2018-11-02 20:52
I was using plug in when I log into wordpress and it says try Gutenberg I installed that.  I am using wordpress 4.9.8.

https://yourdomain/wp-admin/ was what crashed. It was blank other than a z in the top left corner.  I could not get the page to respond at all to do anything.  I couldn't do anything at all front or backend.  When I went to my page I got a blank screen completely.

**Comment by youknowriad** [comment] 2018-11-03 18:19
I suspect this is an incompatibility with another plugin or them. Try disabling the other plugins you have and enable them one by one to see if there's any relation.

**Comment by designsimply** [comment] 2018-11-29 23:46
@dwj2018 I'm closing this issue since there hasn't been a reply in a while. If you are able to try the suggestion to temporarily disable other plugins to rule out a conflict, please re-open this issue to confirm if the problem is still happening for you at that point. Thank you!

**Closed by designsimply** 2018-11-29 23:46 UTC
Labels: [Type] Help Request
