### ISSUE TITLE
Custom HTML block preview not same as the Frontend Views

### ISSUE THREAD

**Issue by RumanCodes** [WordPress/gutenberg#52438] opened 2023-07-07 19:02 UTC
### Description

Custom HTML block preview not same as the Frontend Views

### Step-by-step reproduction instructions

To reproduce the issue, you will need to follow the steps:

1. Activate the Twenty-Fourteen theme.
2. Choose the custom HTML block.
3. Add a few heading tags to it.
4. Check the preview in the HTML block and also the Frontend View

### Screenshots, screen recording, code snippet

[https://prnt.sc/72nMe8HmIr_S](url)
[https://prnt.sc/1dV9rgwAsEIS](url)

### Environment info

WordPress Version: 6.2.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment] 2023-07-08 15:46
_originally reported in [Trac 58463](https://core.trac.wordpress.org/ticket/58463)_

All direct child elements inside the block preview's `div` have no top or bottom margin.

https://github.com/WordPress/gutenberg/blob/aaf6f8f5e044624a9ff98dbd5acd6c38749e297b/packages/components/src/sandbox/index.tsx#L109-L112

**Comment by skorasaurus** [comment] 2023-07-26 19:44
Thanks for reporting; I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/35962 which has the same issue (the HTML block's preview does not have any margin)

**Closed as completed by skorasaurus** 2023-07-26 19:44 UTC
Labels: [Type] Bug, [Feature] Blocks, [Status] Duplicate
