### ISSUE TITLE
Option to drag seems to be missing and spacer block resets to 20 when trying to manually input a value

### ISSUE THREAD

**Issue by 418Design** [WordPress/gutenberg#24518] opened 2020-08-12 10:45 UTC
Tested this on 2 sites

The new UI seems to be lacking the option to drag blocks around.

And trying to enter 60 for the spacer height, when you type 6 it resets to the minimum value of 20.

**Comment by 418Design** [comment] 2020-08-12 10:46
OK so you now drag the up and down arrows. Not clear.

Spacer issue seems to be a thing.

**Comment by lukecarbis** [comment] 2020-08-13 18:09
I had to go searching the internet to discover this. Definitely worth addressing, IMO.

Duplicate of #24506.

**Comment by talldan** [comment] 2020-08-14 04:46
The spacer block issue was also reported in #24460.

As there are other previously created issues that seem to cover those two bugs, I'll close this one.

Thanks for reporting these issues though, @418Design.

**Closed by talldan** 2020-08-14 04:46 UTC
