### ISSUE TITLE
Add option to add contents on Keyboard Shortcuts

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#15880] opened 2019-05-29 09:24 UTC
**Is your feature request related to a problem? Please describe.**
Allow developers to add contents on Keyboard Shortcuts modal pop-up :

<img width="1064" alt="Screen Shot 2019-05-29 at 5 20 30 PM" src="https://user-images.githubusercontent.com/3365507/58545673-4fca1780-8236-11e9-97fd-473623680cd1.png">

**Describe the solution you'd like**
I've created markdown support for the editor : https://twitter.com/phpbits/status/1132988500196773888 and would love to include all the Markdown on this list, similar to what Dropbox Paper has:

<img width="340" alt="Screen Shot 2019-05-29 at 5 24 01 PM" src="https://user-images.githubusercontent.com/3365507/58545781-93248600-8236-11e9-8d33-a221cc5b7fb0.png">

**Describe alternatives you've considered**
As of the moment I'm adding new menu using `registerPlugin` hook but would love to just add these on Keyboard Shortcuts. Thanks!

![Screen Capture on 2019-05-29 at 18-02-27](https://user-images.githubusercontent.com/3365507/58548537-14324c00-823c-11e9-9ccf-16119d44565a.gif)

**Comment by talldan** [comment] 2019-05-30 08:52
Hey @phpbits, I think your issue is a duplicate of https://github.com/WordPress/gutenberg/issues/15205. At least they cover the same ground. Would you be able to add your thoughts to that issue? Thanks.

**Closed** 2019-05-30 08:52 UTC
Labels: [Status] Duplicate, [Type] Enhancement
