### ISSUE TITLE
LinkControl - ensure minmum loading UI display when Creating a new suggestion via `createSuggestion`

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#20138] opened 2020-02-10 12:11 UTC
> A delay of 0.2–1.0 seconds does mean that users notice the delay and thus feel the computer is "working" on the command, as opposed to having the command be a direct effect of the users' actions.

https://www.nngroup.com/articles/response-times-3-important-limits/

Currently when clicking "Create" if the `createSuggestion` promise resolves quickly then the UI state for "loading" only displays very briefly. This can be jarring (as per @karmatosed's comment below).

To avoid this we should enforce a minimum delay on the "Creation" of between 500 - 1000ms to the ensure the user can perceive the editor is doing "work".

-----

_Originally posted by @karmatosed in https://github.com/WordPress/gutenberg/pull/19775#issuecomment-582972264_
> The 'creating page' flashed a little too short. I wonder if we either shouldn't see it or should and then carry on. Seeing a flash was a little weird for an experience.
![2020-02-06 15 55 25](https://user-images.githubusercontent.com/253067/73954013-213e2980-48f9-11ea-933b-2e38e95fd157.gif)

**Comment by jasmussen** [comment] 2021-01-26 07:38
I'm not able to reproduce this issue anymore. Is it still relevant?

**Comment by jasmussen** [comment] 2021-03-15 11:30
I'm closing this one as the UI has changed so much since then. We can always revisit.

**Closed by jasmussen** 2021-03-15 11:30 UTC
Labels: [Block] Navigation, [Type] Enhancement
