### ISSUE TITLE
Editing text for a URL edits another URL's text

### ISSUE THREAD

**Issue by twstokes** [WordPress/gutenberg#40857] opened 2022-05-05 17:19 UTC
### Description

I have two URLs in the editor, URL A and URL B. When editing the text for URL B and clicking "ENTER" to commit the change, the change is applied to URL A instead.

I would expect the change to be applied to URL B.

### Step-by-step reproduction instructions

1. Start a new post and switch to the code editor
2. Paste the following into the code editor

```
<!-- wp:list {"ordered":true} -->
<ol><li>(<a href="http://www.google.com" data-type="URL" data-id="http://www.google.com">example demo</a>)</li><li>(<a href="http://www.wordpress.org" data-type="URL" data-id="http://www.wordpress.org">example</a> demo)</li></ol>
<!-- /wp:list -->
```
3. Exit the code editor

Expect to see:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/2092798/166976991-cd3f5971-f820-48bc-9f52-49c3b2e28fba.png">

4. Click the "example" link on list item 2
5. Click the pencil icon to edit it
6. Update the text from "example" to "example demo"
7. Click "Press ENTER to add this link"

Observe that list item 1's text has been edited and item 1 now reads "example demo demo".

<img width="350" alt="image" src="https://user-images.githubusercontent.com/2092798/166977292-e050d76e-728d-4bb3-9a5c-b48a68efa8a1.png">

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/2092798/166977774-776d4eb2-35c5-44fa-bdbf-bd6851e216e2.mov

### Environment info

- WordPress 5.9.3
- Gutenberg 11.9
- Theme: Twenty Twenty-One

- Browsers: Chrome 100.0.4896 ARM, Safari 15.4
- Desktop with macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amustaque97** [comment] 2022-05-05 17:47
Closing this issue. Duplicate of #40348

**Closed as completed by amustaque97** 2022-05-05 17:47 UTC
