### ISSUE TITLE
External images can't be edited or transformed into galleries

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#14056] opened 2019-02-22 14:30 UTC
**Describe the bug**

I wrote a draft in Google Docs and pasted it into Gutenberg, which worked apparently fine. I had two images that I wanted to lay out side by side, so I selected both image blocks and transformed them to a Gallery, which was presented as an option, but they got replaced with a gallery placeholder:

![image](https://user-images.githubusercontent.com/8739/53248270-9f3bfd00-36b5-11e9-9757-ea701407458f.png)

Also, on any of the individual image blocks, if I click on the Edit button, the image block turns into a placeholder:

![image](https://user-images.githubusercontent.com/8739/53248354-cdb9d800-36b5-11e9-8e68-56c60dc16ce0.png)

This one is even worse, because somehow it doesn't register as a change and the undo button is disabled. You can refresh the page without saving and the image comes back.

When I look at the HTML, this makes a bit more sense:

```html
<figure class="wp-block-image"><img src="https://lh3.googleusercontent.com/XXXXXX" alt=""/></figure>
```

You can also see the same issues if you add the images manually from URLs instead of uploading.

**Expected behavior**

Since I know galleries are based on IDs, I understand why this wouldn't work, but I'd expect a few things to be done differently:

* If an external image won't be transformed to a gallery, don't offer the option to transform.
* When you click the edit button on an external image, there should be a way to see/edit the URL it's pointing to and, more importantly, cancel the edit and leave it as it was.
* When pasting from Google Docs (or any other source), I would have expected those images to be automatically uploaded to my media library.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0.2

**Additional context**

I was creating this post in https://make.wordpress.org/mobile/ but I'm not sure what version that is running

**Comment by iseulde** [comment] 2019-02-22 15:38
We still need to auto upload pasted images. See #2515.

**Comment by youknowriad** [comment] 2019-02-27 13:34
Should we close this as a duplicate of #2515

**Comment by iseulde** [comment] 2019-02-27 15:46
Sounds good

**Closed by iseulde** 2019-02-27 15:46 UTC
