### ISSUE TITLE
tinyMCE.execCommand('mceReplaceContent', false,000(, in classic block - no conrol over insert postion

### ISSUE THREAD

**Issue by StephenAtty** [WordPress/gutenberg#8940] opened 2018-08-13 19:28 UTC
I have a plugin that uses

` tinyMCE.execCommand('mceReplaceContent', false,.......) 
`
to insert data at the current cursor point.

Under GB this plugin works when you are editing a classic block but it seems that the insert point is always character position 1 in the classic block rather than the current cursor position

I suspect this is related to:

https://github.com/WordPress/gutenberg/issues/4855

**Comment by youknowriad** [comment] 2018-11-03 21:08
Yes, seems like a duplicate of #4855 let's consolidate there.

**Closed by youknowriad** 2018-11-03 21:08 UTC
Labels: Needs Technical Feedback, [Block] Classic, [Type] Help Request
