### ISSUE TITLE
Open link in a new window?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2204] opened 2017-08-03 23:34 UTC
I am looking at creating a link.
I see no way to select having the link open in a new window.

**Comment by karmatosed** [comment] 2017-08-04 15:41
Thanks, this is already being covered in #1450

**Comment by jwold** [comment] 2017-08-04 18:29
Took a stab at what the UI could look like. Happy for feedback!

![img_930ee0334f7b-1](https://user-images.githubusercontent.com/3411173/28981791-238b0f5a-7908-11e7-885c-8b4c0c3429bc.jpeg)

**Comment by notnownikki** [comment] 2017-08-31 12:33
Picking this up now, based on @jwold's UI

**Comment by karmatosed** [comment] 2017-08-31 15:00
Removing 'needs design' as in progress :) Thanks for tackling this @notnownikki and @jwold ❤️

**Comment by afercia** [comment] 2017-08-31 15:06
If this is going to use an "expandable div" then please see #469. Te toggle should use aria-expanded, the expandable div should be immediately after the toggle in the source order.

**Comment by karmatosed** [comment] 2017-09-05 15:12
I think rather than reopening something that has been added and works, let's create a new issue to enhance and improve it.

**Comment by karmatosed** [comment] 2017-09-05 15:13
https://github.com/WordPress/gutenberg/issues/2667 is the new ticket.

**Comment by afercia** [comment] 2017-09-05 15:16
Sorry to reopen, I see a few issues introduced in #2628 

1
the "cog" button doesn't have any text or aria-label, it's completely empty so it will be reported by assistive technologies just as "button". Worth noting the other buttons that are very close in the code, they all have an aria-label...

Since it misses an aria-label, the button misses also a tooltip. I'd say it should have an aria-label with text "Link settings" or something along those lines.

<img width="407" alt="screen shot 2017-09-05 at 16 06 11" src="https://user-images.githubusercontent.com/1682452/30067696-c1bc1f7c-925b-11e7-9ecc-638024e69683.png">

2
z-index issue!
see screenshot above: when entering or pasting a link *and* there are also search results, when pressing the cog button the expanded panel stays below the search results.
To reproduce, insert a link to `https://wordpress.org` in a couple other posts. Then edit a third post and insert a link pasting in the field `https://wordpress.org`.
I'd say either increase the x-index or, maybe better, close the search suggestions when the setting panel is expanded, and display them again when the setting panel gets closed.

3
the input field misses a focus style.
This is because the input fields inherit the focus style from `forms.css` where input of `type="url"` aren't targeted. Two options here:
- set the input field to `type="text"` and miss minor advantages given by `type="url"`
- add proper selectors to the styles in core `forms.css`, targeting `type="url"`

4
IE 11 and Edge display a proprietary "X" control in the input fields of `type="url"`:

![ie11](https://user-images.githubusercontent.com/1682452/30068248-6ef172a4-925d-11e7-94c0-cc884106668f.png)

![edge](https://user-images.githubusercontent.com/1682452/30068249-6ef48dd6-925d-11e7-96ce-473bad0972c2.png)

This would be a minor issue, but unfortunately the spinner that appears when the search runs doesn't look so nice in combination with the "X":

![screenshot 62](https://user-images.githubusercontent.com/1682452/30068287-9a8b11fe-925d-11e7-8491-0022cee8cbcc.png)

If I remember correctly, a similar issue happened in the Customizer for the menu/widget search field and we just switched back the input field type "search" to "text" (which would also solve the focus style issue).

**Comment by notnownikki** [comment] 2017-09-05 15:29
@afercia thank you! I'll take care of those, perhaps I could ping you for more feedback once I've got them taken care of?

**Comment by afercia** [comment] 2017-09-05 15:33
@notnownikki sure! Agreed with @karmatosed to close this in favor of #2667 that should be updated with the right issues (sorry for the confusion).

**Closed by afercia** 2017-09-05 15:33 UTC
Labels: Blocks, [Type] Enhancement
