### ISSUE TITLE
Cannot add block for any post or any user!

### ISSUE THREAD

**Issue by ShadowGames-Dev** [WordPress/gutenberg#12927] opened 2018-12-16 15:09 UTC
I am unable to add a block on a post, new or old. This error started when I upgraded to WP 5.0.1.

![block-grey](https://user-images.githubusercontent.com/22234142/50055264-78f16280-0144-11e9-8977-9c2eb86f7b16.JPG)

![edit](https://user-images.githubusercontent.com/22234142/50055265-7c84e980-0144-11e9-9925-8229b6c0c2ad.JPG)

I have disabled all of my plugins, The checkbox "Disable the visual editor when writing" on my profile is not checked.

![profile](https://user-images.githubusercontent.com/22234142/50055266-83136100-0144-11e9-8d68-f19aa0caa506.JPG)

I have attempted may recommendations as per other issues here but none of them have resolved mine. 

I have tried other user profiles on the site but all have the very same issues.

I have also re-installed WP several times now and the issue is persisting!

**Comment by ShadowGames-Dev** [comment] 2018-12-16 19:13
Now I am even more confused...

I have my WP site hosted on AWS, running on an EC2 instance, I have an ElasticLoadBalancer and then am setting up my Route53 to connect to the site thought CloudFront. I have full SSL setup on the site.

When I am accessing the site on the domain, I have the error I described above... But, when I access it thought the IP of the EC2 instance, I do not have this error... 

Can anyone explain to me what is going on here??????????

**Comment by ShadowGames-Dev** [comment] 2018-12-16 19:19
I have invalidated the caches in-case that was causing any issues, cleared my browser cache completely... No change...

**Comment by jrsconfitto** [comment] 2018-12-17 15:03
I'm experiencing a similar issue with my .org site: I also cannot add a block. Same screenshot basically:

![](https://user-images.githubusercontent.com/238079/50013004-0b9bd100-ff8e-11e8-85de-74ab879939ff.jpg)

I cannot switch between visual and code mode in the editor, either. The link's not there and the keyboard shortcuts for it don't work.

* There's no JS errors in the console (in troubleshooting mode, default theme)
* This started in 4.9.8 for me, I was hoping I just goofed something up and a fresh install of 5 would fix it but I'm on 5.0.1 now and still have the issue.

I have [a lengthy post on the support forum about it][support-post] and would be happy to provide any other information that I can, here or there.

A snippet from [my post][support-post]:

>The keyboard shortcut to switch between visual and code (CTRL-SHIFT-ALT+M) does nothing.

> When I installed the Classic Editor plugin to see if that helped, I can’t see the visual or code tabs:
Classic editor plugin: no visual or code tabs. This was done in troubleshooting mode on 2019 theme and there were no JS errors in the console.

[support-post]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/

**Comment by designsimply** [comment] 2018-12-18 00:06
I tested with WordPress 5.0.1 (no plugins active) using Edge 42 on Windows 10 and was unable to replicate the problem. I'd like to help you find the source of the trouble though! May I ask for additional information?

- List of active plugins
- WordPress version
- Gutenberg plugin version if it is installed*
- OS and browser versions
- Are you using a VPN or behind any firewall which could be blocking something in an unpredictable way?

Note: the Gutenberg plugin is no longer required since WP5.0 and you may uninstall it unless you are a developer working on the Gutenberg project or are helping with beta testing.

**Comment by swissspidy** [comment] 2018-12-18 09:34
If you run `wp.data.select( 'core/editor' ).getEditorSettings().richEditingEnabled` in your browser's JS console, what does it return?

**Comment by swissspidy** [comment] 2018-12-18 09:44
Also added some helpful debugging steps in https://github.com/WordPress/gutenberg/issues/12881#issuecomment-448159119. Please try these as well.

**Comment by ShadowGames-Dev** [comment] 2018-12-18 10:03
@designsimply 

I have no active or installed plugins right now. 
I am on WP 5.0.1
Gutenberg is not installed as it is with WP 5.0.1
Windows 10, Chrome Version 70.0.3538.110
No VPN, standard network connection.

@swissspidy That command returns "true".

Again, this issue is happening with the sites live URL going through CloudFront on AWS. When I access the site thought the EC2 IP, it appears to be working fine, but it is not acceptable to access the site through its IP.

**Comment by jrsconfitto** [comment] 2018-12-18 17:38
Hi @designsimply,

I saw your post on the support forum, so [I've answered there](https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/#post-11003644) and I think that covers most of your questions.

My site is also live and is operated by a third-party host, so I don't know much about details but they are also hosting on AWS.

Please let me know if there's anything else I can add to this issue.

**Comment by ShadowGames-Dev** [comment] 2018-12-18 18:33
I am operating and have setup the hosting myself. All done, configured on an EC2 instance, going through a load balance and through CloudFront with Route53 set to the domain.

**Comment by ShadowGames-Dev** [comment] 2018-12-20 18:48
Is anyone else able to add to this?
I still have the same issue!

**Comment by designsimply** [comment] 2018-12-20 22:39
There's one StackExchange link that @jrsconfitto pointed to earlier which has a solution posted: https://wordpress.stackexchange.com/questions/126110/visual-editor-missing-server-side-problem-how-would-you-debug-it and it might be worth checking that as well.

**Comment by designsimply** [comment] 2018-12-21 20:44
Thanks for checking it.

I found something in the support forums which may be more relevant:

<blockquote>I’m using the CloudFront, AWS CDN, and one of the behaviors was not passing the headers to the application. When changing this configuration in CloudFront, everything has returned to work.</blockquote>

Source: https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/2/#post-11014978

Can you check for that option?

**Comment by jrsconfitto** [comment] 2018-12-28 15:33
I can confirm that CloudFront not passing headers along was the source of the issue, and once those were handled our editor is working great again. My host chose to fix it by adding code to the functions file to force rich editing on.

Thanks again @designsimply for your detective work!

**Comment by jrsconfitto** [comment] 2019-01-02 14:41
@ShadowGames-Dev Sure, I can share that. There's two methods for resolution that we've landed on:

1. Change the CloudFront behaviors to pass on headers. This is detailed in [this post by user g3luka][1].
2. Add code to functions.php that will enable the `user_can_richedit` flag [as detailed in my post][2]. Many thanks to https://webhost.io/, my host, for coming up with this one.

[1]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/2/#post-11014978
[2]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/3/#post-11032983

**Comment by designsimply** [comment] 2019-01-07 22:13
Thank you @jrsconfitto for your persistence and patience and for posting more details about the solution for others!

**Closed by designsimply** 2019-01-07 22:13 UTC
Labels: [Status] Needs More Info, [Type] Help Request

**Comment by designsimply** [comment] 2019-01-07 22:15
Adding webhost.io's notes (linked to above by @jrsconfitto) for reference: 

> Researching it I found that WP does an odd thing in looking at the UserAgent to determine if it should show the editor or not. […] A CDN strips the UserAgent out to improve caching, so the following code forces it to be shown. […]

```
function richedit_wp_cloudfront () {
   add_filter('user_can_richedit','__return_true');
}

add_action( 'init', 'richedit_wp_cloudfront', 9 );
```

**Comment by ShadowGames-Dev** [comment] 2019-01-08 09:43
@jrsconfitto Thanks for that. It worked for me!

**Comment by jrsconfitto** [comment] 2019-01-10 14:39
@andreyugolnik hi! Is AWS part of your hosting environment, and if so, have you tried looking into the mitigations given above?

**Comment by lapo-luchini** [comment] 2020-09-09 14:41
I solved this by disabling visual editor in user configuratiom, and then re-enabling it again. 🤷🏻‍♂️

**Comment by seitenmeister** [comment] 2020-09-09 15:10
@lapo-luchini Thanks! That solved my Problem :-)

**Comment by philbirnie** [comment] 2020-09-28 16:38
Thank you @jrsconfitto & @designsimply for leading me to the solution.  For all `wp-admin` paths, I had the following headers whitelisted: `Authorization`, `Origin`, `Host`; however as they suggested, this is insufficient -- adding the `User-Agent` to the `Header` whitelist in our cache-policy took care of it.  There was no need to make edits to the code. 

Also of note, if you are using CloudFront, I had issues with blocks loading/saving -- for those particular paths (i.e. `wp-json/*`) make sure that the `Refer` and `X-WP-Nonce` are also passed to the origin.
