### ISSUE TITLE
Site Editor is empty in Firefox

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#28403] opened 2021-01-21 18:30 UTC
## Description
Since 9.8.0 the Site Editor is empty when using Firefox browser.
Other browsers that I have tested (Chrome & Edge) not affected, although now much slower to load when compared to previous version of Gutenberg.

## Step-by-step reproduction instructions

1. In the dashboard, click on 'Site Editor (beta)'

## Expected behaviour

Load the Site Editor.

## Actual behaviour

The Site Editor does not load, and is an empty grey page, then redirects to standard dashboard type layout with empty page.

## Screenshots or screen recording (optional)

![site-editor-blank](https://user-images.githubusercontent.com/76742815/105395097-45803c80-5c16-11eb-9ea4-d780889336d9.png)

![site-editor-blank-redirect](https://user-images.githubusercontent.com/76742815/105395136-53ce5880-5c16-11eb-9729-61f893da0cec.png)

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No (using 'TT1 Blocks' theme)

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 84.0.2

**Comment by Sandstromer** [comment] 2021-01-21 18:56
**Console errors if it helps.**

/gutenberg/vendor/react-dom.min.de439aae.js:125:24

TypeError: n is undefined
    Vp /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81
    Bh /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:126
    Dj /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    unstable_runWithPriority /wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25
    Da /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    xb /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    Te /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146
    Pg /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61
    unstable_runWithPriority /wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25
    Da /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    Pg /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61
    ha /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    Ja /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:224
    ch /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:93
    t /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81
    b /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81


/gutenberg/build/block-editor/index.js:81:23058

Uncaught TypeError: n is undefined
    Vp /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81
    Bh /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:126
    Dj /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    unstable_runWithPriority /wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25
    Da /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    xb /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162
    Te /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146
    Pg /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61
    unstable_runWithPriority /wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25
    Da /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    Pg /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61
    ha /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60
    Ja /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:224
    ch /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:93
    t /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81
    b /wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1cd322178bcb34cc86341ccc8d0e3ed5:81

**Comment by gziolo** [comment] 2021-01-22 03:19
It was also mentioned in the comment on WP Tavern: https://wptavern.com/gutenberg-9-8-brings-rounded-borders-to-the-group-block-and-moves-the-site-editor-canvas-into-an-inline-frame#comment-361459

**Comment by carolinan** [comment] 2021-01-22 08:40
Hi
I am able to reproduce this with full site editing themes that still has the theme attribute (`"theme":"tt1-blocks"`) for the template parts.

I am not able to reproduce it with themes that have had the theme attribute removed in preparation for version 9.9 (https://github.com/WordPress/gutenberg/pull/28088)

**Comment by aristath** [comment] 2021-01-22 08:46
Just a note in case it's related: There was an error initially with iFrames and Firefox which was fixed in https://github.com/WordPress/gutenberg/pull/28212.
I don't think it was included in v9.8, if not it will be included in v9.9

**Comment by ntsekouras** [comment] 2021-01-22 09:21
>I don't think it was included in v9.8, if not it will be included in v9.9

It was not included. It works with the fix @aristath mentioned.

**Comment by aristath** [comment] 2021-01-22 10:12
Thank for verifying @ntsekouras 
In that case I'm closing this one as it has already been fixed and I can confirm everything works fine using the master branch.
Duplicate of #28212

**Closed by aristath** 2021-01-22 10:12 UTC
Labels: Browser Issues, Needs Testing, [Priority] High, [Type] Bug

**Comment by ockham** [comment] 2021-01-22 11:59
I've cherry-picked the relevant commit to the `release/9.8` branch and will include it in 9.8.1 (to be released later today).

**Comment by Sandstromer** [comment] 2021-01-22 17:40
9.8.1 mostly fixes this issue.

Occasionally the site editor hangs with the grey screen, and gives this console error:
`Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

Forcing a refresh (sometimes once, sometimes twice is needed) usually corrects it.

**Comment by TechDotHaus** [comment] 2021-08-18 17:04
I am having this same issue as shown in the original screenshots using:
WordPress 5.8 running blockbase or quadrat using Gutenberg plugin 11.2.1

This happens both on Firefox and Firefox Developer Edition, locally, and on my server.

Can this be reopened?

**Comment by ntsekouras** [comment] 2021-08-18 20:17
@TechDotHaus can you try GB 11.3? I think there was a new similar WSOD that was fixed in this PR: https://github.com/WordPress/gutenberg/pull/33896

**Comment by TechDotHaus** [comment] 2021-08-19 20:13
> @TechDotHaus can you try GB 11.3? I think there was a new similar WSOD that was fixed in this PR: #33896

Thank you. All clear :)
