### ISSUE TITLE
Navigation Block Tracking Issue i2

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#35521] opened 2021-10-11 17:37 UTC
Supersedes #27593 

With most of the work in #27593 in place, it is a good time to revisit the Navigation block priorities with a near-future release in mind. Instead of mass-editing the existing issue, let's close it and leave it as a snapshot of a first iteration and focus here on the next round of improvements. Bugs should be reported with the `[Type] Bug` label and added directly to the [Navigation Project Board](https://github.com/WordPress/gutenberg/projects/58).

## High Priority
Setup interactions & placeholders
- [x] #34041
- [x] #30170
- [x] #35818

Design customization & inner blocks
- [x] #33278
- [x] #34783
- [x] #35632
- [x] #34511
- [x] #34872
- [x] #34525
- [x] https://github.com/WordPress/gutenberg/issues/36667

IA
- [x] #30674
- [x] #35750
- [x] #34612
- [x] #35868
- [x] #35827

General UI & Copy
- [x] #33640

## Normal Priority
Setup interactions & placeholders
- [x] #30116
- [x] #23573
- [x] #30115
- [x] #23603
- [x] #35261
- [x] #34962
- [x] #32555
- [x] #32373
- [ ] #31452

Design customization & inner blocks
- [ ] #31688
- [ ] #23293
- [x] #29423

Responsiveness & hamburger menu
- [x] #33985
- [x] #30370
- [x] #27131

## Backlog
- [ ] #33018
- [x] #34514
- [x] #24604
- [ ] #23745
- [x] #31387
- [x] #34611
- [x] #31733

---
_This issue aims to collect new features or enhancements that build towards a better Navigation Block experience or allow for richer designs, excluding requirements driven by compatibility with the [Navigation Editor](https://github.com/WordPress/gutenberg/issues/29102)._

**Comment by carolinan** [comment] 2021-10-20 07:11
I think this one is important to solve
https://github.com/WordPress/gutenberg/issues/29401

**Comment by getdave** [comment] 2021-10-20 10:49
There is currently an exploration underway regarding separating _presentation_ from the underlying _data_ (items) of a navigation. This is all to do with allowing navigations to be _reused_ across a site.

We should check out Dan's PRs and provide feedback:

- https://github.com/WordPress/gutenberg/pull/35746
- https://github.com/WordPress/gutenberg/pull/35418

Also related is [this issue about Theme switching](https://github.com/WordPress/gutenberg/issues/35750).

**Comment by draganescu** [comment] 2021-10-22 09:19
Updated the issue with @talldan 's [listed follow-ups](https://github.com/WordPress/gutenberg/pull/35746#issuecomment-949283858).

**Comment by priethor** [comment] 2021-10-22 15:51
>I think this one is important to solve
#29401

Thanks for flagging that one, @carolinan! I've added it to the Navigation Block project board as a ToDo item. However, I would recommend not including bugs in tracking/overview issues, as they are more oriented to provide a feature roadmap, and including bugs makes it harder to grasp the overall progress of projects regarding their scope.

**Comment by getdave** [comment] 2021-10-27 13:42
## Update - 27th October 2021

* Following on from updates [here](https://github.com/WordPress/gutenberg/issues/35521#issuecomment-947549374) and [here](https://github.com/WordPress/gutenberg/issues/29102#issuecomment-947554777) some progress has been made on the architecture of the Nav block.
* [The PR to get the block to save its "items" (data) to a `wp_navigation` post type](https://github.com/WordPress/gutenberg/pull/35746) has been merged. This allows the same navigation (items) to be used in multiple places on a site but with the _potential_ for each one to have a different visual _presentation_.
* Work is underway on [facilitating the ability to preserve navigations on Theme switch](https://github.com/WordPress/gutenberg/issues/35750). Currently exploring utilising a custom `wp_navigation_area` taxonomy and modelling the ways that classic Menus currently work.
* Work has continued on the Lighter Navigation block experience:
    - transforms are being added to the Link UI when used in the Nav block https://github.com/WordPress/gutenberg/pull/35857
    - ability to modify link item _text_ from the Link UI has been merged https://github.com/WordPress/gutenberg/pull/33849.
* Following on from the Hallway Hangout, contributors are working hard to communicate the direction of the work as widely as possible to ensure the community are kept informed.

**Comment by jasmussen** [comment] 2021-10-28 08:17
With the merger of #35857 (@tellthemachines 👏 ), I wonder if we shouldn't — for the sake of this tracking issue — check the box for #34041?

This will not preclude further enhancements to transforms, which is one of the most powerful aspects of the block, to the point that the feature could deserve its own tracking issue!

**Comment by getdave** [comment] 2021-11-10 09:28
## Update - 10th November 2021

* Work has continued on making Navigations reusable across a Site and between Themes. 
* A [Navigation Area block was added](https://github.com/WordPress/gutenberg/pull/36178) to facilitate the reuse of Navigations between Themes. You can now switch Themes and (if the target Theme is configured correctly) your Navigation will be preserved.
* This works somewhat similarly to Menu Locations in classic Themes:
    - you add a Nav _Area_ block and configure it to be `Primary`, `Secondary` or `Tertiary`. These terms are provided by default and denote an approximate hierarchy of navigations on a site.
    - you then insert a Nav block _inside_ the Nav Area block. This can be used to configure _presentational_ properties of a given Menu and is ideal for Theme Developers. Note you do not need to add any nav _items_ at this point.
    - you then optionally add _items_ to your Navigation block. 
    - when switching Theme, assuming the new Theme also has a Navigation Area block with a matching "area" (e.g. Primary, Secondary, Tertiary), then any nav items from matching Navigation Areas on your old Theme will automatically appear in the associated location in the new Theme.
    - the navigation -> area relationship is saved via site options is a format of  `{ "primary": 794, "secondary": 112 }` where the keys are the navigation _areas_ and the values are the post IDs of [Navigation post types](https://github.com/WordPress/gutenberg/pull/35746).
- Lots of great work behind the scenes work on the REST API which has allowed all of the above to progress. 
- Tweaks to the UI and UX of the block itself have been ongoing.

**Comment by getdave** [comment] 2021-11-22 09:32
## WP 5.9 "Must Haves"

Below is a collation of the Issues I'm aware of that are "Must Haves" for WP 5.9, for which [the Gutenberg feature freeze is the **26th November**](https://href.li/?https://make.wordpress.org/core/2021/11/19/wordpress-5-9-editor-update-19-november/).  

**⚠️ Update: the list of tasks has been moved to [the 5.9 overview issue under `Navigation block`](https://github.com/WordPress/gutenberg/issues/36556).**

I've also added these to [the WP 5.9 Must Haves board](https://github.com/WordPress/gutenberg/projects/62).

**Please note**: this intentionally does not cover any bugs as these can still be fixed during [the Beta phase](https://make.wordpress.org/core/5-9/).

**Comment by mkaz** [comment] 2021-11-22 15:32
If we want to take a harder line for "must have" I think both #36593 and #36722 could be moved if not ready.

For #36722, yes, the property name could be simplified, but there is also a reason we moved the name from menu to navigation, so personally I like the more descriptive property name, but even if we want to change later we can deprecate.

For #36593, it's a better user experience without the "Save as" button but nothing is functionally broken or an issue, so it would be good to have, but like above I wouldn't hold a release for it.

**Comment by noisysocks** [comment] 2021-11-23 00:07
Thanks for summarising @getdave. I updated the "Navigation block" section in https://github.com/WordPress/gutenberg/issues/36556 to be the same as your list in https://github.com/WordPress/gutenberg/issues/35521#issuecomment-975327997. Let's try to use https://github.com/WordPress/gutenberg/issues/36556 if we can as that's the issue that the 5.9 squad is referring to.

**Comment by getdave** [comment] 2021-11-23 17:05
> If we want to take a harder line for "must have" I think both #36593 and #36722 could be moved if not ready.

That's a good point. There are PRs underway to address those issues, but as you say if those aren't going to land then they could be dropped without compromising things.

**Comment by tellthemachines** [comment] 2021-11-24 02:45
> If we want to take a harder line for "must have" I think both #36593 and #36722 could be moved if not ready.

 I was given to understand that removing the dialog that forces users to name their navigation block before saving is a must have for this release. #36593 is the only issue tracking that work, since #36575 was closed.

It is important at this stage that we're all super clear about what needs to be done for 5.9, so let's please not create further confusion by mentioning issue numbers instead of explicitly referring to the features themselves.

**Comment by getdave** [comment] 2021-11-24 12:51
## Update 24th November 2021

* [A list of "Must Haves" for the Navigation block for WP 5.9](https://github.com/WordPress/gutenberg/issues/35521#issuecomment-975327997) were published.
* We're [tracking these items on the main 5.9 overview issue](https://github.com/WordPress/gutenberg/issues/36556).
* Navigation Areas (including the block itself) are **_not_** going to be in 5.9. In fact they are now [deprecated](https://github.com/WordPress/gutenberg/pull/36727) due to concerns and lack of community consensus around the UX.
* Reusable Navigations (via the `wp_navigation` Custom Post) **_will_** be shipping in 5.9.
* The final experience we are targeting for the Nav block for 5.9 will be:
   - Navigation Menus will be saved to a Custom Post and thus be reusable between Themes.
   - on Theme switch your Navigation _Menu_ will _not_ be _automatically_ carried across to the Navigation block in the new Theme.
   - instead you will have to _manually_ visit the Navigation block and select the Menu you wish to display there. 
   - if no Menu is assigned to a given Navigation block, then the block will [render an appropriate fallback on the front of the site](https://github.com/WordPress/gutenberg/issues/36721). This mirrors the behaviour of `wp_nav_menu` for classic Themes.
   - bear in mind that when you switch Themes it is likely that a Navigation block will already exist in the new Theme. This will be preconfigured with presentation attributes. Therefore for the user, the Theme switch process will simply be a matter of assigning an existing Menu (`wp_navigation` Post) to the existing Navigation block.
* We recognise this is not perfect and we fully intend to iterate and improve upon this process in WordPress 6.0. However, our priority is to land a stable experience in 5.9.

**Comment by getdave** [comment] 2021-11-25 16:58
## Update for 5.9 merge day (26th Nov 2021)

Thanks to all the hard work we’re down to the last couple of items on the [“Must Haves” list](https://github.com/WordPress/gutenberg/issues/36556#:~:text=isn%27t%20invoked%C2%A0%2335536-,Navigation%20block,-Page%20List%20block).

We’d really appreciate any help with reviewing and/or coding on the following PRs/items:

- [Remove Navigation Area endpoints and utility functions](https://github.com/WordPress/wordpress-develop/pull/1944) - should be good to merge but I just want to check that the block will be gone from Core once this is merged.
- [Bug with Nav block editing the wrong entity](https://github.com/WordPress/gutenberg/pull/36880) - needs review.
- [Allow filtering of Nav block fallback](https://github.com/WordPress/gutenberg/pull/36850) - needs review.
- [Removing attribute from Nav block](https://github.com/WordPress/gutenberg/pull/36877) - needs review.
- [Avoid rendering unstable location if block has data](https://github.com/WordPress/gutenberg/pull/36863) - needs review.


Also, tangentially related in that no editor = no nav block:

- [Fallback template resolution mechanism in `/templates` API endpoint](https://github.com/WordPress/gutenberg/pull/36881) - needs review.

If anyone is aware of any other critical items that impact on the "Must Haves" please feel free to edit this list.

Thank you 🙇

**Comment by getdave** [comment] 2021-12-01 15:02
## Update for 1st December 2021

* All of the "Must Have" items for Nav block were merged in time for WP 5.9 Beta 1.
* We now switch focus to resolving the `[Type] Bug` issues.
* Please do pop into [`#feature-navigation-block-editor`](https://wordpress.slack.com/archives/C01KDAZJMQ9) on Core Slack if you have a question or wish to contribute. 
* Feel free to raise an Issue to report a bug. Be sure to label it with the `Block: Navigation` label.

**Comment by getdave** [comment] 2021-12-14 09:30
## Update for 14th December 2021

* [A number of bugs](https://github.com/WordPress/gutenberg/projects/62?card_filter_query=block+navigation) have been discovered during the Beta period. These must be resolved asap as [the RC is on 4 January 2022](https://make.wordpress.org/core/5-9/). 
* Many of the bugs have already been fixed 🥳 🎉 **_But_**...there's more work to do:
* Feedback and reviews required for several proposed solutions for mitigating [the problems with lower permission users interacting with the Navigation block](https://github.com/WordPress/gutenberg/issues/36286):
    - https://github.com/WordPress/gutenberg/pull/37302
    - https://github.com/WordPress/gutenberg/pull/37286
    - https://github.com/WordPress/gutenberg/pull/37289
* A [regression was discovered which effects usage of Patterns](https://github.com/WordPress/gutenberg/issues/37354) which urgently needs fixing.
* It's now possible to [filter the conversion of classic Menus to block based Navigation Menus](https://github.com/WordPress/gutenberg/pull/36950).

**Comment by uniquesolution** [comment] 2021-12-23 11:55
Sorry if this is not the right place to put this question here, but I want to know how we can modify the svg icons used for the dropdown in navigation block ? Is there some way through functions.php or otherway to use a different icon, for example plus icon instead of the arrow ?

**Comment by jasmussen** [comment] 2021-12-23 12:05
@uniquesolution There isn't a way to change those SVGs yet, we are discussing (among other things) how to best enable a UI for that [in this PR](https://github.com/WordPress/gutenberg/pull/36149#issuecomment-957944791).

But you should be able to do it with CSS in the mean time. Something like this:

```
button.wp-block-navigation__responsive-container-open {
	background: url('mysvgfile') no-repeat center center;
	width: 24px;
	height: 24px;
}

button.wp-block-navigation__responsive-container-open svg {
	display: none;
}
```

**Comment by getdave** [comment] 2022-01-17 11:44
## Update 17th Jan 2022

* Team are refocusing back onto work landing in the Gutenberg Plugin as opposed to WP 5.9.
* There's a question about [how best to handle editing of Navigation Menus in isolation](https://github.com/WordPress/gutenberg/issues/37950).
* We're asking how we can/might need to s[ave Nav blocks to the post under certain circumstances](https://github.com/WordPress/gutenberg/issues/38030). 
* Otherwise the team are working on bugs and extensibility.

**Comment by getdave** [comment] 2022-01-26 09:49
## Update 26th Jan 2022

* We're absorbing and collating feedback from WordPress 5.9 release.
* Work underway to refine the placeholder state in https://github.com/WordPress/gutenberg/pull/36775 and https://github.com/WordPress/gutenberg/pull/37099.
* We've started refactoring to [make the block more internally consistent](https://github.com/WordPress/gutenberg/issues/37190).
* Exploring an idea to allow users to ["revert" the submenu block to a link](https://github.com/WordPress/gutenberg/pull/38203) via the block toolbar.

**Comment by getdave** [comment] 2022-01-27 11:22
As discussed with @priethor and [noted in the #feature-navigation-block Slack channel](https://wordpress.slack.com/archives/C01KDAZJMQ9/p1643116972033700) I'm closing this Issue in favour of a new Tracking Issue over at https://github.com/WordPress/gutenberg/issues/38275.

**Closed as completed by getdave** 2022-01-27 11:22 UTC
Labels: [Type] Tracking Issue, [Block] Navigation
