### ISSUE TITLE
Incredibly difficult to select Column Block (container)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7919] opened 2018-07-12 05:22 UTC
**Describe the bug**
It's incredibly difficult to select the Column Block container, for when you want to make it Wide or Full Width. At first I thought it was broken. It took me at least 5 minutes before I found that you have to click in the very right-hand or left-hand edge of the block before it will select it.

![gutenberg_cantselectcolumnblock](https://user-images.githubusercontent.com/2078245/42613971-0e8b27ce-85e7-11e8-88f4-b4599361e57b.gif)

**To Reproduce**
1. Add Column Block
2. try to change Block to Full Width

**Expected behavior**
Selecting the Column Block (container) needs to be easier

_macOS Sierra 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by mtias** [comment] 2018-07-12 11:57
Related discussion at the end of https://github.com/WordPress/gutenberg/issues/7919

**Comment by chrisvanpatten** [comment] 2018-07-12 12:00
I think this is also somewhat related to the refactoring in #7365. The collapsed margins make the edges of the block a little harder to hit.

**Comment by SuperGeniusZeb** [comment] 2018-07-12 14:03
See also: #7694.

**Comment by designsimply** [comment] 2018-07-18 21:46
Closing as a duplicate of #7766 (which I had mistakenly closed too soon! sorry for the trouble!).

**Closed by designsimply** 2018-07-18 21:46 UTC
