### ISSUE TITLE
Image block needs to be resolved after first time save

### ISSUE THREAD

**Issue by ArraysNL** [WordPress/gutenberg#10515] opened 2018-10-11 14:05 UTC
**Describe the bug**
A image with Gutenberg will be transformed to html after saving, viewing the page and editing the page again.

**To Reproduce**
1. Create a page or post with Gutenberg and add a image.
2. Save the page and view the page.
3. Edit the page.
4. And the image block will give the 'This block contains unexpected or invalid content.' error. Resolving will fix the problem.

**Expected behavior**
Block should be still a image block and not be transformed to a html block.

**Screenshots**
<img width="658" alt="schermafbeelding 2018-10-11 om 16 01 50" src="https://user-images.githubusercontent.com/1218091/46809564-01cbd680-cd6f-11e8-8f2d-e036c8e31d6d.png">

<img width="722" alt="schermafbeelding 2018-10-11 om 15 56 38" src="https://user-images.githubusercontent.com/1218091/46809467-d0530b00-cd6e-11e8-9dd5-f54bd4fbdd65.png">

<img width="720" alt="schermafbeelding 2018-10-11 om 16 01 09" src="https://user-images.githubusercontent.com/1218091/46809528-eeb90680-cd6e-11e8-9ca1-11a3ed4f948b.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: 69.0.3497.100

**Additional context**
- Gutenberg version 4.0 RC 1
- Looks like the block doesn't read the html the right way. Because the html is valid.

**Comment by bph** [comment] 2018-10-12 22:47
Seems to experience the same on Firefox. 
**here is a video** 
http://recordit.co/ZN2p5omAlG

Once I click on "Convert to HTML" - 
and then use the "Convert to Blocks" 
align the image and resize it again, 
it's all ok and stays ok. beyond the save and the edit again. 
http://recordit.co/XhPFoKjBLd

Seems to be related to the first save only. 

**And here is the console error:** 
JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542
Block validation: Expected token of type `EndTag` ( 
Object { type: "EndTag", tagName: "figure" }
 ), instead saw `StartTag` ( 
Object { type: "StartTag", tagName: "figcaption", attributes: [], selfClosing: false }
 ). index.js:2:144515
Block validation: Block validation failed for `core/image` ( 
Object { name: "core/image", title: "Image", description: "They’re worth 1,000 words! Insert a single image.", icon: {…}, category: "common", keywords: (1) […], attributes: {…}, transforms: {…}, getEditWrapperProps: getEditWrapperProps()
, edit: WithSelect(WithViewportMatch((t)))()
, … }
 ).

Expected:

<div class="wp-block-image"><figure class="alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/></figure></div>

Actual:

<div class="wp-block-image"><figure class="alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/><figcaption></figcaption></figure></div> index.js:2:144515
Block validation: Expected tag name `figure`, instead saw `div`. index.js:2:144515
Block validation: Block validation failed for `core/image` ( 
Object { name: "core/image", title: "Image", description: "They’re worth 1,000 words! Insert a single image.", icon: {…}, category: "common", keywords: (1) […], transforms: {…}, getEditWrapperProps: getEditWrapperProps()
, edit: WithSelect(WithViewportMatch((t)))()
, deprecated: (3) […], … }
 ).

Expected:

<figure class="wp-block-image alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/></figure>

Actual:

<div class="wp-block-image"><figure class="alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/><figcaption></figcaption></figure></div> index.js:2:144515
Block validation: Expected tag name `figure`, instead saw `div`. index.js:2:144515
Block validation: Block validation failed for `core/image` ( 
Object { name: "core/image", title: "Image", description: "They’re worth 1,000 words! Insert a single image.", icon: {…}, category: "common", keywords: (1) […], transforms: {…}, getEditWrapperProps: getEditWrapperProps()
, edit: WithSelect(WithViewportMatch((t)))()
, deprecated: (3) […], … }
 ).

Expected:

<figure class="wp-block-image alignright"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/></figure>

Actual:

<div class="wp-block-image"><figure class="alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/><figcaption></figcaption></figure></div> index.js:2:144515
Block validation: Expected tag name `figure`, instead saw `div`. index.js:2:144515
Block validation: Block validation failed for `core/image` ( 
Object { name: "core/image", title: "Image", description: "They’re worth 1,000 words! Insert a single image.", icon: {…}, category: "common", keywords: (1) […], transforms: {…}, getEditWrapperProps: getEditWrapperProps()
, edit: WithSelect(WithViewportMatch((t)))()
, deprecated: (3) […], … }
 ).

Expected:

<figure class="wp-block-image alignright" style="width:310px"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" width="310" height="207"/></figure>

Actual:

<div class="wp-block-image"><figure class="alignright is-resized"><img src="http://testing37.local/wp-content/uploads/2018/08/rawpixel-777267-unsplash-web-1.jpg" alt="rawpixel-777267-unsplash-web" class="wp-image-33" width="310" height="207"/><figcaption></figcaption></figure></div> index.js:2:144515
e/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:144515
rt
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:147083
bt/s<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:151594
bt
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:151278
208/wt</</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:151894
208/wt</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/blocks/index.js:2:151867
SETUP_EDITOR
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/editor/index.js:50:68306
this.wp.editor</e.exports</</</</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/editor/index.js:12:29972
l/t[e].actions</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:6073
value
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:15256
t
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/editor/index.js:50:298727
yh
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:97:111
lg
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:120:88
mg
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:120:386
gc
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:127:202
vb
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:126:230
ub
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:126:65
zd
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:124:449
ra
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:123:319
enqueueSetState
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react-dom.min.82e21c65.js:189:231
q.prototype.setState
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/react.min.ab6b06d4.js:18:428
value/this.unsubscribe<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:14405
n/</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:4745
n/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:4716
v
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:21770
S/</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:4298
G/</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:12594
a/</</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/redux-routine/index.js:1:3778
dispatch
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/data/index.js:1:24328
i/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/redux-routine/index.js:1:3359
n/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/redux-routine/index.js:1:7930
n
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/redux-routine/index.js:1:7904
u/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/build/redux-routine/index.js:1:7859
j/</<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29352
j/<
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/wp-polyfill-ecmascript.min.2ae96136.js:2:29220
f
http://testing37.local/wp-content/plugins/gutenberg-v4.0-rc.1/vendor/wp-polyfill-ecmascript.min.2ae96136.js:1:20743

**Comment by cmmarslender** [comment] 2018-10-16 00:31
After a bit of further testing, it doesn't appear to happen if I add a caption before saving the first time.. Images without caption have the error until I resolve and save the post.

**Comment by designsimply** [comment] 2018-10-16 03:02
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.0.0-rc.1 with Chrome 69.0.3497.100 on macOS 10.13.6.

**Comment by youknowriad** [comment] 2018-10-16 09:44
@iseulde This was fixed by your recent PR merge right?

**Comment by iseulde** [comment] 2018-10-16 10:10
@youknowriad Unsure if it's related, but if it's no longer reproducible in master then yes. :)

**Comment by iseulde** [comment] 2018-10-16 11:28
Confirmed.

**Closed by iseulde** 2018-10-16 11:28 UTC
Labels: Blocks, [Type] Bug
