### ISSUE TITLE
Upload button Meta boxes

### ISSUE THREAD

**Issue by msykes** [WordPress/gutenberg#5389] opened 2018-03-04 17:26 UTC
## Issue Overview
When using the meta boxes in Gutenberg on some of my plugins (which works well overall!) I notice that making a change to any values in the meta box will keep the 'Update' button inactive and light blue. Only way to enable it is to make a change to something in the core editor such as adding a space to the post content.

## Steps to Reproduce (for bugs)
1. Enable a plugin with meta boxes (e.g. meta tag manager)
2. Go to add a post or page or edit an existing one
3. Add some content and save if a new post/page
4. Click the X on top right so the buttons to update post reappear (now greyed out)
4. In the meta box area, try to add a new meta box and type anything into the text box
5. Upload button does not turn solid blue and remains greyed out, which cannot be clicked on.

## Expected Behavior
Upload/Publish box should turn solid blue and become clickable when any content in meta boxes are modified

## Current Behavior
The button remains greyed out and inactive.

**Comment by youknowriad** [comment] 2018-03-04 17:28
@msykes Can I ask which version of the plugin you're using, this is supposed to be fixed in the last version but a regression is possible.

**Comment by msykes** [comment] 2018-03-04 17:41
Sorry forgot to mention versions!

Gutenberg 2.3.0
WP 4.9.4

I'm using [Meta Tag Manager](https://translate.wordpress.org/projects/wp-plugins/meta-tag-manager) for testing this, although I get the same issue with my other plugins that I was enabling Gutenberg for.

**Comment by youknowriad** [comment] 2018-03-04 17:42
Thanks, so we updated this to make the "update" button always enabled when using meta boxes because "dirty-detection" is not possible with meta boxes. I'll take a look soon to see why this regressed.

**Comment by msykes** [comment] 2018-03-04 17:58
I'd agree with that approach/logic of just keeping that button enabled. 

I was thinking about that actually whilst writing this report, because there's so many plugins that may not even have input boxes or modify values in ways that'd be hard to detect.

For example, Meta Tags Manager allows you to drag/drop elements and order the tags around, but if I remember correctly no input values are changed, just the order of the elements.

**Closed** 2018-03-06 15:58 UTC
Labels: [Component] Meta Boxes, [Type] Bug
