### ISSUE TITLE
cmd+up and cmd+down do not work

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#8542] opened 2018-08-05 00:58 UTC
**Describe the bug**
In the classic editor, cmd+up took you to the beginning of the post, and cmd+down the bottom. This functionality is not working in Gutenberg

**Expected behavior**

I would expect on cmd + up to be in the first block after the title on the first character, and on cmd + down to be on the last character of the last block

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome
 - Version 68

**Additional context**
- v3.4

**Comment by designsimply** [comment] 2018-08-07 00:05
Tested and confirmed that pressing cmd + up/down moves to the top/bottom of the current block and then to the next block using WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome 67.0.3396.99 on macOS 10.13.6. ([51s](https://cloudup.com/cnC7v-yJOLT)) @iseulde what is the intended behavior in this case?

**Comment by iseulde** [comment] 2019-02-19 15:35
Duplicate of #5805.

**Closed by iseulde** 2019-02-19 15:35 UTC
Labels: Input Interaction
