### ISSUE TITLE
Code Block: ampersands inside of <script> tags are parsed as HTML entities

### ISSUE THREAD

**Issue by chaosharmonic** [WordPress/gutenberg#10634] opened 2018-10-15 20:13 UTC
**Describe the bug**
When using the script tag in a code block, any ampersand inside the tag is still parsed as an HTML entity, causing syntax errors when they're used in control flow to denote a logical AND.

**To Reproduce**
- Use the script tag inside a code block
- Write an if statement that includes a logical AND
- Create a preview of your post. You'll see an "unexpected token" syntax error at at the line where your ampersands are located, and that the console shows entity numbers in place of the ampersands themselves.

**Expected behavior**
All code inside the script tag would evaluate as JavaScript without any special characters being parsed as HTML entities.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 69

**Additional context**
Gutenberg version: 3.9.0 (originally found while on 3.7.0, but the issue persisted after updating)

**Comment by johngodley** [comment] 2018-10-19 08:42
I've been unable to reproduce this using 4.0. Can you try with 4.0 and see if it still happens for you?

If it does can you list the contents of your code block, and include some screenshots of the block and the error?

**Comment by johngodley** [comment] 2018-10-19 14:29
Thanks. I'll close this for now, but please re-open if it comes back.

**Closed by johngodley** 2018-10-19 14:29 UTC
Labels: Blocks, Needs Testing
