### ISSUE TITLE
Typography: Impossible to select correct font size preset

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#53558] opened 2023-08-11 06:07 UTC
### Description

When I have fontSize presets, and I select one, it automatically takes another one that has a similar size (but not the same). 

### Step-by-step reproduction instructions

1. Create a new theme with fontSize presets like
```        {
          "fluid": {
            "max": "18px",
            "min": "18px"
          },
          "name": "Heading 6",
          "size": "18px",
          "slug": "heading-6"
        },
        {
          "fluid": {
            "max": "18px",
            "min": "17px"
          },
          "name": "Paragraph lg",
          "size": "18px",
          "slug": "paragraph-lg"
        },

```
2. Try to select the second font size preset in the editor

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/4e85b3cd-934f-4baf-9796-c78928e4b18c

### Environment info

- WP 6.3
- GB 16.04
- Custom theme: https://github.com/hanneslsm/ProLooksUI

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by saifullahnakiih** [comment] 2023-08-11 09:31
I face no issue using this one

**Comment by hanneslsm** [comment] 2023-08-11 10:08
> I face no issue using this one

What do you mean by "this one"? The presets?
I can replicate this also in TT3.

**Comment by t-hamano** [comment] 2023-08-11 13:35
Perhaps the problem is due to duplicate variations of the same value for the font `size` property. You can reproduce this with theme.json as follows:

<details><summary>Details</summary>

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"typography": {
			"fontSizes": [
				{
					"name": "Large 1",
					"slug": "large-1",
					"size": "20px"
				},
				{
					"name": "Large 2",
					"slug": "large-2",
					"size": "20px"
				},
				{
					"name": "Large 3",
					"slug": "large-3",
					"size": "20px"
				},
				{
					"name": "Large 4",
					"slug": "large-4",
					"size": "20px"
				},
				{
					"name": "Large 5",
					"slug": "large-5",
					"size": "20px"
				},
				{
					"name": "Large 6",
					"slug": "large-6",
					"size": "20px"
				}
			]
		}
	}
}
```

</details> 

I believe that even if the value of the `size` property is the same, it should be treated as a different variation if the `slug` is unique. Therefore, I label this issue as a bug.

https://github.com/WordPress/gutenberg/assets/54422211/dca2bec9-d4cc-4c62-95db-9878fc44aae2

**Comment by hanneslsm** [comment] 2023-08-11 14:48
> I believe that even if the value of the size property is the same, it should be treated as a different variation if the slug is unique. Therefore, I label this issue as a bug.

This was also my understanding. Thanks!

**Comment by hanneslsm** [comment] 2023-09-16 12:20
@annezazu Can you please add this issue to the Polish board (or maybe even 6.4)? It's crucial for building themes. Thanks!

**Comment by jordesign** [comment] 2024-01-11 23:12
It sounds like this might be similar (although not exactly the same) as https://github.com/WordPress/gutenberg/issues/42683 ?

**Comment by t-hamano** [comment] 2024-01-12 03:38
I believe both issues are caused by duplicate `size` property values in font size variations. Therefore, I would like to close this issue as a duplicate.

**Closed as not planned by t-hamano** 2024-01-12 03:38 UTC
Labels: [Type] Bug, [Feature] Typography
