### ISSUE TITLE
i think that add a hook to add custom tab in media library.

### ISSUE THREAD

**Issue by hiepcua** [WordPress/gutenberg#15729] opened 2019-05-20 05:03 UTC
**Is your feature request related to a problem? Please describe.**
I am build a plugin about media library that meet a problem when add custom tab to media library.  

**Describe the solution you'd like**
I need a hook to create custom tab and document release to modify basic feature.

**Describe alternatives you've considered**
My research found a way that use Backbone.js. But i still have many difficulties in interaction.
`
var l10n = wp.media.view.l10n;
wp.media.view.MediaFrame.Select.prototype.browseRouter = function( routerView ) {
    routerView.add({
        upload: {
            text:     l10n.uploadFilesTitle,
            priority: 20
        },
        browse: {
            text:     l10n.mediaLibraryTitle,
            priority: 40
        },
        designbold_tab: {
            text:     "my tab name",
            priority: 60
        }
    });
};`

**Comment by youknowriad** [comment] 2019-05-21 09:25
This seems like a duplicate of #6523

**Closed by youknowriad** 2019-05-21 09:25 UTC
