### ISSUE TITLE
Widgets Editor - Existing Widgets disappear when closing sidebar

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#25551] opened 2020-09-23 04:04 UTC
**Describe the bug**
When I first enter the Widgets Editor, my main sidebar has a number of different widgets displayed. If you close the sidebar and then reopen it, they all disappear

Vid: https://share.getcloudapp.com/L1uJLZlW

**To reproduce**
1. Go to Widgets screen
2. Close a sidebar containing widgets and then reopen it
3. See widgets disappear

**Expected behavior**
My widgets shouldn't disappear

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 9.0.0

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Firefox 80.0.1

**Comment by annezazu** [comment] 2020-09-24 01:54
@maddisondesigns I wasn't able to replicate this using WordPress 5.5.1 & Gutenberg 9.0. However, I was testing this by first adding blocks to the widget screen and then seeing if they appeared when checking the drop downs. Can you give a bit more information about whether these widgets existed before updating to Gutenberg 9.0 and if they are disappearing after? I did run into a problem with adding the classic block though so am going to leave this as needs testing for now: https://github.com/WordPress/gutenberg/issues/25595

**Comment by maddisondesigns** [comment] 2020-09-24 03:45
@annezazu These widgets existed before updating to Gutenberg 9.0. This was the first time I've been to the new Widgets screen since updating the Gutenberg plugin to 9.0.

**Comment by annezazu** [comment] 2020-09-24 17:07
Brilliant! I was able to replicate this. Changing this to a bug. Thanks for reporting :)

![disappearing widgets](https://user-images.githubusercontent.com/26996883/94177013-2800b900-fe56-11ea-903b-527a52976363.gif)

**Comment by adamziel** [comment] 2020-09-25 10:23
Thank you for reporting! I just confirmed it's indeed a problem - this is specific to text widget, it seems like TinyMCE is getting removed once the tab is collapsed.

**Comment by adamziel** [comment] 2020-09-25 11:06
And it's likely for the same reasons as new text widgets not getting properly initialized with TinyMCE.

**Comment by adamziel** [comment] 2020-09-28 11:13
https://github.com/WordPress/gutenberg/pull/25645 should have fixed the problem - I'm closing this issue. If you find the issue is still there, by all means please comment / reopen!

**Closed by adamziel** 2020-09-28 11:13 UTC
Labels: [Feature] Widgets Screen, [Type] Bug
