### ISSUE TITLE
Heading Block: Can't split the block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#701] opened 2017-05-08 08:27 UTC
If you place the caret in a text block and press enter twice, you split the block in two.

Enter doesn't work inside the heading block at all. But if you backspace from a text block into a heading block, you merge the text block with the heading block, creating a new giant heading block.

You can obviously undo, or you can use the switcher to a text block, then split, then split back to heading, but it seems suboptimal. It feels like we should either:

- Allow enter and splitting in the heading block
- Disallow backspace-to-merge with a heading block

**Comment by mtias** [comment] 2017-05-08 13:42
Duplicate of #536.

**Closed by mtias** 2017-05-08 13:42 UTC
Labels: Blocks, [Component] Editable
