### ISSUE TITLE
Media library module dates filter doesn't fully display

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2202] opened 2017-08-03 23:30 UTC
As I click to add an image I notice that the All Dates dropdown is cropped. 

![screen shot 2017-08-04 at 01 26 36](https://user-images.githubusercontent.com/5323259/28948148-2c928db6-78b4-11e7-9b71-3e93a05e95a6.png)

**Comment by karmatosed** [comment] 2017-08-04 15:44
Good catch, I can replicate.

**Comment by mrxkon** [comment] 2017-09-07 19:33
Hello there! Trying to help so I picked up an easy one to try the workflow.

This could be 'easily' patched but the thing is that the css is actually coming from the `media-views.css` that resides in `wp-includes`. This is caused because there is 1 select box missing the 'All media items' so the widths of the single select box have to be replaced.

Question: is this something manageable through Gutenberg's files, meaning can we actually override the admin .css like we would do with a theme / plugin in any other case or is it something of a no-no situation so it should be handle on core somehow ?

If we could do it through Gutenberg I'd love a little file guidance as I haven't found a proper place to put the styles needed :D

**Comment by nielslange** [comment] 2017-12-24 17:52
Related to https://github.com/WordPress/gutenberg/issues/4034. Potential fix can be found there as well.

**Comment by karmatosed** [comment] 2018-04-11 15:28
Also worth noting: https://github.com/WordPress/gutenberg/issues/6111

**Comment by designsimply** [comment] 2018-07-23 23:20
Tested and confirmed that "All dates" is still awkwardly cropped in the media modal.

![screen shot 2018-07-23 at mon jul 23 4 52 27 pm](https://user-images.githubusercontent.com/1119271/43107189-1522efe4-8e99-11e8-843f-97bf25c9d122.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13999&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by ianbelanger79** [comment] 2018-07-30 18:18
Hi All,

I have a solution for this issue, but I would like to refer back to @mrxkon previous comment.

> Hello there! Trying to help so I picked up an easy one to try the workflow.
> 
> This could be 'easily' patched but the thing is that the css is actually coming from the media-views.css that resides in wp-includes. This is caused because there is 1 select box missing the 'All media items' so the widths of the single select box have to be replaced.
> 
> Question: is this something manageable through Gutenberg's files, meaning can we actually override the admin .css like we would do with a theme / plugin in any other case or is it something of a no-no situation so it should be handle on core somehow ?
> 
> If we could do it through Gutenberg I'd love a little file guidance as I haven't found a proper place to put the styles needed

Could I get some insight on this? Where should I put the CSS that is needed to fix this issue?

Thanks

**Comment by brandonpayton** [comment] 2018-08-08 05:10
@mrxkon and @ianbelanger79, it looks like the best place add a stopgap would be in a `style.scss` file that is a sibling and dependency of our[ MediaUpload component](https://github.com/WordPress/gutenberg/blob/dd81e6b978ba627b42604dadcd36ea933c78970e/edit-post/hooks/components/media-upload/index.js). If possible, it would be good to submit a patch to core for this issue and add a link to it with our Gutenberg fix, indicating the fix should be removed once it is patched in core.

**Comment by ajitbohra** [comment] 2018-08-09 04:08
Ticket/Patch 
https://core.trac.wordpress.org/ticket/44760

**Comment by youknowriad** [comment] 2018-08-09 09:03
I'm closing as this is fixed in Gutenberg.

**Closed by youknowriad** 2018-08-09 09:03 UTC
Labels: Good First Issue, Media, [Type] Bug, [Type] WP Core Bug
