### ISSUE TITLE
Flexbox and auto margins layout

### ISSUE THREAD

**Issue by danieldudzic** [WordPress/gutenberg#46133] opened 2022-11-28 20:36 UTC
## What problem does this address?
I am trying to add a few patterns to the [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-blocks) Product Query block and realized there's currently no good layout solution for the following layout:

![Flex_·_Bootstrap](https://user-images.githubusercontent.com/905781/204349883-fb05a07f-e073-47cd-b2bb-cacc90e04fec.jpg)

I was trying to achieve the following layout using core blocks:

![🔎_Product_Query_Block_–_Figma](https://user-images.githubusercontent.com/905781/204350240-2fb6b550-951c-4c38-91ca-bceb866e7cf3.jpg)

Since the product image will have a variable height (which will determine the height of the container), achieving the desired **Price** product element position is currently not possible without custom code.

## What is your proposed solution?

It would be useful if:
- There was a straightforward way to tweak `flexbox` behavior of blocks (on per block level, if the parent is using flexbox)
- The margin block setting would support the `auto` value

Related issue: https://github.com/WordPress/gutenberg/issues/45868

**Comment by tellthemachines** [comment] 2023-01-04 04:38
With #45364 it's now possible to set width/height on children of (Row/Stack) flex containers, with a `fill` option that essentially adds `flex-grow: 1` to the block, which behaves the same as `margin: auto` in this context. 

 In theory, it should be possible to recreate the layout above by creating a Row block with an Image block and a Stack block (with the product info) inside it, then setting the height (under Dimensions) of the "Product title" block to "fill".

The problem is that the Row block has an `align-items: center` set on it by default, which makes the Stack block inside it not take up full height, so the `flex-grow` inside it doesn't work.

I'm inclined to label this as a bug; I know the flex-layout has always had a default `align-items` set on it but am unsure if there's any good reason for that. The risk of removing it is, of course, that existing layouts may depend on it, so it's not clear what the best solution may be.

**Comment by tellthemachines** [comment] 2023-01-04 05:25
Just thinking we might be able to work around this once we add alignment controls to Row as per #35849, as long as we add a `stretch` option. It's not super intuitive but might be our best option for not breaking back compat 🤔

**Comment by tellthemachines** [comment] 2023-01-30 04:53
With #47134 merged, we can now recreate this layout by:

* Adding a Row block with an Image block and a Stack block (with the product info) inside it;
* Setting the vertical alignment on the Row block to stretch ;
* Setting the setting the height (under Dimensions) of the "Product title" block to "fill".

<img width="683" alt="Screenshot 2023-01-30 at 3 50 14 pm" src="https://user-images.githubusercontent.com/8096000/215390261-2b678c50-960d-4c95-8b5b-7f2eca644564.png">

I'm going to go ahead and close this issue for now; feel free to reopen if anything doesn't work as expected!

**Closed as completed by tellthemachines** 2023-01-30 04:53 UTC
Labels: [Type] Bug, [Feature] Nested / Inner Blocks, [Feature] Layout
