### ISSUE TITLE
Blocks never used before are appearing under Frequent

### ISSUE THREAD

**Issue by chrislema** [WordPress/gutenberg#5956] opened 2018-04-03 17:31 UTC
## Issue Overview

After adding several new gutenberg block plugins to my site, I am presented with several new blocks in the Frequent section of the block selector. Since I've never used them before, I don't believe they belong there.

## Steps to Reproduce (for bugs)

1. Activate Gutenberge
2. Activate additional Gutenberg block plugins (like this one: https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/)
3. Create New Post
4. Click on the Plus sign and notice that there are new blocks in the Frequent section

I was using Chrome 64 on MacOs 10.13

## Expected Behavior

I believe that the only blocks that should show up under Frequent are those that I have actually used. Preferably, more than once (hence the term, frequent).

## Current Behavior

Right now, it looks like plugins can determine on their own how to categorize their blocks. If everyone puts theirs in Frequent, the designation will become dramatically less valuable.

## Possible Solution

Limit blocks entry into that section that have been used more than once.
Alternatively, measure how often every block is used and only present those in the top 10%.

## Screenshots / Video

<img src="https://chrislema.com/wp-content/uploads/2018/04/NeverBeenUsedBlocksUnderFrequent.png" />

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by noisysocks** [comment] 2018-04-04 00:06
Thanks for your feedback, @chrislema!

Blocks that have not been used will appear under _Frequent_ by design, but I appreciate that this is confusing. I think our simplest path forward is to rename the tab to something like _Suggested_. I went into a little detail about how we pick these blocks here: https://github.com/WordPress/gutenberg/issues/5627#issuecomment-375144795

Closing this for now as it's a duplicate of https://github.com/WordPress/gutenberg/issues/5956.

**Closed by noisysocks** 2018-04-04 00:06 UTC
