### ISSUE TITLE
Changing Permalinks on new posts

### ISSUE THREAD

**Issue by hansschuijff** [WordPress/gutenberg#7144] opened 2018-06-05 11:50 UTC
**Describe the bug**
When I add a new post using gutenberg and it is saved for the first time the permalink shows "https/domain/?p=123" (of course "domain" and "123" are template strings here, rather than the actual content of what you will see). When I than click on the button behind the permalink to change the permalink, I'm guided to the permalink settings page instead of opening the field to set the permalink for the document. That cannot be intended behavior and is not what I wanted.

**To Reproduce**
1. Go to 'New Post'
2. Add title and make a paragraph block under it
3. Just wait until the post is auto-saved for the first time
4. Go into the title and see that the permalink shows the post-id rather than a slug.
5. Click on the "Change Permalink" button (I suppose that is the English button text, I use the dutch translation myself.
6. See that it opens the Permalink settings page instead of allowing to change the permalink slug of the post itself.

**Expected behavior**
Just opening the slug to be edited (in this case edit the "?p=ID" part of the permalink and entering a slug instead)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox Developer Edition
 - Version: 61.0b9 (64-bit)

**Smartphone (please complete the following information):**
- haven't tried on a smartphone

**Additional context**
- Gutenberg version 3.0.0
- Permalinks on the test-website are set to show a slug based on postname (/%postname%/)

**Comment by GlennMartin1** [comment] 2018-06-05 11:54
Duplicate of https://github.com/WordPress/gutenberg/issues/7129

**Comment by hansschuijff** [comment] 2018-06-05 12:00
Not exactly duplicate, but solving #7129 would probably solve this too. By the way, after the above occurs, the actual permalink based on a slut is shown as intended and so the second time around the button behaves as I would expect.

**Comment by mtias** [comment] 2018-07-19 14:15
Closing to focus conversation on #7129.

**Closed by mtias** 2018-07-19 14:15 UTC
