### ISSUE TITLE
Add Caption to Gallery Images within Block is impractical.

### ISSUE THREAD

**Issue by bahia0019** [WordPress/gutenberg#6858] opened 2018-05-21 01:18 UTC
**Describe the bug**
Playing around with Gallery block, I noticed you can add Captions without launching the Media Modal.
However, it seems too impractical to be a viable method of adding caption.
Long captions completely take over the photo, making it impossible to recognize which photo it is.

**To Reproduce**
1. Insert photos into a Gallery block.
2. Hover over individual photo to see the "Add Caption."
3. Write any caption you like, and see the text overfloweth.

**Possible Solution**
In the new Image block, I love the ability for text to be styled and links to be created. 
I think a possible solution here is:
1. Create a gallery of images.
2. Select individual image (maybe an icon in lower right).
3. Image expands to and looks like Image Block.
4. Caption can be filled out similarly to Image Block.
5. Click icon to save.
6. Image zooms back to small thumbnail.

The other option is to just not have ability to add captions in Gallery block, and leave it in the Media Modal only.  

**Screenshots**
<img width="778" alt="screen shot 2018-05-20 at 5 57 52 pm" src="https://user-images.githubusercontent.com/1586037/40285991-8da306b2-5c57-11e8-8db1-f3723d333e21.png">

**Comment by BinaryMoon** [comment] 2018-07-03 11:02
Related to this -  the toolbar is not visible. It just all looks a bit broken to me.

<img width="733" alt="screen shot 2018-07-03 at 12 00 28" src="https://user-images.githubusercontent.com/1004130/42216193-eee49584-7eb8-11e8-81e9-104ebf7e4874.png">

**Comment by nerrad** [comment] 2019-05-26 00:40
> Related to this - the toolbar is not visible. It just all looks a bit broken to me.

I'm not seeing this issue.

> However, it seems too impractical to be a viable method of adding caption.

I'm not sure what the issue is here.  Is the request that images in galleries should not show captions or that any captions should not overlay the images?

One issue with making changes to this block after a year of it being in the wild is some sites might be _used_ to and _using_ the current behaviour, so any changes could make will disrupt those use-cases.

One thing I do notice is that entering a caption on the image in the gallery does not persist that so it's attached with the image when viewing through the media modal.  Also, if you update a caption in the media modal it clears any captions added via the block editor (which I see is being worked on in #15004)

This also appears to be a function of theme design  (so depends on how themes display the captions for images).

There's some related discussions in the following pulls/issues (related in terms of gallery captions):

- #14304 
- #7963
- #8030 is a _very_ similar proposal to here (if I'm reading things correctly) and it was closed.

In light of the above and the staleness of this issue I'm going to close this for now.  It does appear captions _are_ being worked on in the meantime and this issue certainly can be re-opened.

**Closed by nerrad** 2019-05-26 00:40 UTC
Labels: Media, Priority Low, [Type] Enhancement

**Comment by bahia0019** [comment] 2019-05-26 02:12
Yes, the issue is about the cludgy UI when the captions are overlaid on the image. I do like that look on the frontend, but when you have a narrow area, it just looks terrible (Yes, these are unusually long in the example). 
Personally, I think a text field below each photo would suffice for this.

<img width="709" alt="Screen Shot 2019-05-25 at 7 06 03 PM" src="https://user-images.githubusercontent.com/1586037/58376448-55ff8180-7f20-11e9-8475-c7785d836246.png">
