### ISSUE TITLE
Responsive mode editing

### ISSUE THREAD

**Issue by arshadshah440** [WordPress/gutenberg#67415] opened 2024-11-29 09:57 UTC
## What problem does this address?

Currently in order to make the section or the post which is build with gutenberg responsive , we have to write custom css and add custom class even for the small changes which is not ideal for some user who don't have knowledge about the code...

## What is your proposed solution?

It will be better if there are responsive modes in which user can set different styles for specific devices or at least for the typography..

**Comment by ellatrix** [comment] 2024-12-19 05:42
Duplicate of #57719, #13363.

**Closed as completed by ellatrix** 2024-12-19 05:42 UTC
Labels: [Type] Enhancement
