### ISSUE TITLE
.wp-block-image margin-bottom is incorrectly applied when aligned left/right

### ISSUE THREAD

**Issue by benlk** [WordPress/gutenberg#16241] opened 2019-06-21 16:23 UTC
**Describe the bug**

<img width="560" alt="Screen Shot 2019-06-21 at 12 07 28 " src="https://user-images.githubusercontent.com/1754187/59936166-5acf2c80-941d-11e9-94f2-078d3e966e21.png">

The problem is that a `.wp-block-image` block with an `alignright` image retains the margin-bottom on the parent element, and as a result the following paragraph tag does not align with the top of the image/

**To reproduce**
1. With WordPress 5.2.2.1 and no Gutenberg plugin
2. Add an image block aligned right that is less than the full column width.
3. Following the image block, add a paragraph text block.

**Expected behavior**
I expect the top of the image to be level with the top of the adjacent paragraph tag.

**Screenshots**
<img width="560" alt="Screen Shot 2019-06-21 at 12 07 28 " src="https://user-images.githubusercontent.com/1754187/59936166-5acf2c80-941d-11e9-94f2-078d3e966e21.png">
<img width="371" alt="Screen Shot 2019-06-21 at 12 07 33 " src="https://user-images.githubusercontent.com/1754187/59936723-b6e68080-941e-11e9-8d71-24ac1f633283.png">
<img width="356" alt="Screen Shot 2019-06-21 at 12 07 48 " src="https://user-images.githubusercontent.com/1754187/59936724-b6e68080-941e-11e9-8d7a-42ebcfef0f7d.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 75

## Suggested fix

- [ ] remove the margin-bottom on `.wp-block-image` in /wp-includes/css/dist/block-library/style.min.css?ver=5.2.2
- [ ] add a margin-bottom to the `<figure>` element in the optional styles that themes can opt out of. Themes generally provide their own margin styles for `.alignright`.

**Comment by GlennMartin1** [comment] 2019-06-21 16:27
Related? https://github.com/woocommerce/storefront/pull/1165

**Comment by benlk** [comment] 2019-06-21 18:48
@tiagonoronha didn't specify the source of the misaligning when the ticket was reported, so there's no way to be absolutely certain.

I'd agree with you, @GlennMartin1, because based on the diff that ticket does look like it's reporting this same issue. The fix that theme implemented is that I would implement in my themes, if there was not going to be a fix for this in Gutenberg.

**Comment by noisysocks** [comment] 2020-03-19 05:50
Definitely looks like something is awry. 

Here's what I see when I follow the steps to reproduce using latest Gutenberg + Twenty Twenty:

<img width="918" alt="Screen Shot 2020-03-19 at 16 41 23" src="https://user-images.githubusercontent.com/612155/77035749-9aa15f80-6a01-11ea-89f3-1f4de672d122.png">

And here's it using latest Gutenberg + Twenty Nineteen:

<img width="920" alt="Screen Shot 2020-03-19 at 16 43 22" src="https://user-images.githubusercontent.com/612155/77035762-a0974080-6a01-11ea-8406-3f5df72378d9.png">

I'm unsure if this is an issue in the block editor that's being patched by Twenty Twenty, or if this is an issue in Twenty Nineteen. 

Adding `Needs Design Feedback` in the hopes that someone familiar with the CSS here can chime in.

**Comment by richtabor** [comment] 2020-07-14 16:47
We chatted about this issue in today's design meeting ([Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1594744722111700)). 

It's _really_ difficult to match paragraph and image placements for right/left images. We could probably get it right for baseline/default Gutenberg styles - but not for every theme out there. It's dependent on font size, line height, paragraph margin/padding as well.

**Comment by benlk** [comment] 2020-07-14 18:56
In the theme I screenshot, the paragraph had no margin-top; the theme uses margin-bottom to space between paragraphs. The `.wp-block-image{ margin-bottom: 1em }` margin-bottom comes from `wp-includes/css/dist/block-library/style.min.css?ver=5.4.2`.

**Comment by paaljoachim** [comment] 2020-10-27 20:18
Is this issue stil valid?

**Comment by GlennMartin1** [comment] 2020-10-27 20:24
> Is this issue still valid?

I don't know. My earlier comment was using Storefront, but it's been addressed there (see https://github.com/woocommerce/storefront/pull/1165).

**Comment by paaljoachim** [comment] 2021-02-10 14:41
I tested with WordPress 5.7 beta 1.

Aligning the image right.
Adding a paragraph.


![Screen Shot 2021-02-10 at 15 40 01](https://user-images.githubusercontent.com/5323259/107524698-5b9a7080-6bb6-11eb-9c55-98b11ab830cd.png)


It looks pretty good. I will close this issue.

**Closed by paaljoachim** 2021-02-10 14:41 UTC
Labels: Needs Design Feedback, [Block] Image, [Feature] Themes
