### ISSUE TITLE
Shared/Reusable Blocks do not show when using the `allowed_block_types` filter

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#5893] opened 2018-03-29 23:33 UTC
If you limit the blocks which can be shown using the `allowed_block_types` filter then shared blocks do not appear in the 'Shared' block inserter tab.

**Comment by gziolo** [comment] 2018-04-09 08:24
Closing in favor of #6070 which is duplicate but with a much detailed description :)

**Comment by noisysocks** [comment] 2018-04-10 00:12
I don't think it's a dupe. #5893 is referring to shared blocks not appearing in the inserter when `allowed_block_types` is set to `false`, whereas #6070 is referring to _all blocks_ mistakenly appearing in the / command regardless of what `allowed_block_types` is set to.

**Comment by noisysocks** [comment] 2018-04-10 00:15
Having said that, @paulwilde: could you elaborate on this a little more? Reproduction steps would be useful for making sure that we're all on the same page here.

My first impression is that this is expected behaviour. If one adds this to their `lib/load.php`:

```php
add_filter( 'allowed_block_types', function() {
	return [ 'core/paragraph', 'core/image', 'core/quote' ];
} );
```

Then I would expect that shared blocks should **not** appear in any of the inserters, as we did not explicitly allow the `core/block` block type.

**Comment by paulwilde** [comment] 2018-04-10 02:10
Actually, this isn't a bug in that case. I didn't realise you had to add `core/block` for shared blocks to appear in the inserter. I figured that just whitelisting the block types would suffice for them to show up as shared blocks.

Maybe the ability to create shared blocks should be disable if `core/block` is disabled, in that case?

**Closed** 2018-10-16 01:09 UTC
Labels: Reusable Blocks
