### ISSUE TITLE
Intermittent: This block has encountered an error and cannot be previewed.

### ISSUE THREAD

**Issue by davidkartuzinski** [WordPress/gutenberg#9135] opened 2018-08-18 16:48 UTC
The exact bug:
When using Gutenberg on a new install, erratic and intermittent cross-browser, different computers (same website) - getting:

Error: This block has encountered an error and cannot be previewed.
For all blocks in Gutenberg.

I am unable to reliably reproduce this bug.  Sometimes clearing cache resolves it in Firefox Dev, sometimes just waiting five minutes and then refreshing solves it, sometimes refreshing 5+ times solves it.  But not on every computer and not always.

The console error messages that appear are: 
```
JQMIGRATE: Migrate is installed, version 1.4.1     load-scripts.php:9
wp-tinymce.php:1 Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
tinymce-plugin-lists.min.137fa94a.js:1 Uncaught ReferenceError: tinymce is not defined
    at tinymce-plugin-lists.min.137fa94a.js:1
    at tinymce-plugin-lists.min.137fa94a.js:1
tinymce-plugin-paste.min.f6e82d7a.js:1 Uncaught ReferenceError: tinymce is not defined
    at tinymce-plugin-paste.min.f6e82d7a.js:1
    at tinymce-plugin-paste.min.f6e82d7a.js:1
tinymce-plugin-table.min.3fa6c17e.js:1 Uncaught ReferenceError: tinymce is not defined
    at tinymce-plugin-table.min.3fa6c17e.js:1
    at tinymce-plugin-table.min.3fa6c17e.js:1
32
react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'init' of undefined
    at t.value (index.js:12)
    at t.value (index.js:12)
    at jc (react-dom.min.82e21c65.js:134)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at zd (react-dom.min.82e21c65.js:124)
    at ra (react-dom.min.82e21c65.js:123)
    at Object.enqueueSetState (react-dom.min.82e21c65.js:189)
    at e.q.setState (react.min.ab6b06d4.js:18)
```

Website is self hosted and 5 other WP websites have no issues including additional fresh install.
The latest version of Wordpress 4.9.8, and Gutenberg 3.6.2

No other plugins activated.  Tried switching to default themes. Tried reinstalling it. 

Other symptoms: Cell phone login and use create the same error, but a refresh allows for editing and the error doesn't occur.

Error occurs in all major browsers: Chrome, FF, FF Dev, safari and Opera.

In the past, chmod permission on the files were an issue, but I have run permissions again:

```
   sudo chown -R www-data:www-data public_html
   sudo chown -R www-data:www-data public_html/wp-content
   sudo chown -R www-data:www-data public_html/wp-content/plugins
   sudo find /var/www/html/ronan/public_html -type d -exec chmod g+s {} \;
   sudo chmod g+w /var/www/html/ronan/public_html/wp-content
   sudo chmod -R g+w /var/www/html/ronan/public_html/wp-content/themes
   sudo chmod -R g+w /var/www/html/ronan/public_html/wp-content/plugins

```

Fixing permissions resolved this issue in the past, but not this time.

![edit post wordpress - chromium_004](https://user-images.githubusercontent.com/29503118/44301450-46ab3200-a317-11e8-96da-7d6c74ab30f4.png)

Thank you for all your hard work.

**Comment by wpfangirl** [comment] 2018-08-19 19:52
So far I've seen this with button blocks. The block works but I get the preview error.

**Comment by davidkartuzinski** [comment] 2018-08-19 20:08
We got “all or nothing”.  After doing doing, the Gutenberg editor started working today (the next day).  Is there cacheable assets?  Above my pay grade but it’s intermittent on and off.

Thanks.

Ps.  All my other sites on the same host work no problem.  So still confused.

**Comment by designsimply** [comment] 2018-08-20 17:03
I searched Google for "Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING" and found the following:

> Finally, just as I was about to give up, I decided to disable the Real-time protection on my antivirus.
> 
> And it worked….

Source: http://thisinterestsme.com/err_incomplete_chunked_encoding/

> Whenever I disable the Real-Time protection, the issue disappears. Today, I left the Real-Time protection off for 6-7 hours and the issue never occurred.

Source: https://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error

Since I found more than one similar reply, maybe it's the same issue in your case?

For reference, may I ask what antivirus software and what operating system you are using?

**Comment by designsimply** [comment] 2018-08-21 02:07
@wpfangirl, to confirm, are you seeing the exact same error that says "Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING" but only for the button block?

**Comment by wpfangirl** [comment] 2018-08-21 03:16
I didn't check the console...and now that I'm trying to reproduce it, naturally I can't.

**Comment by davidkartuzinski** [comment] 2018-08-23 08:38
This doesn't seem related to the antivirus. Copying the install to a local environment (Windows or Linux) doesn't solve it. Nor does having browser plugins seem to make any difference as multiple people on the same site are experiencing the same issue.

**Comment by GManchester** [comment] 2018-08-24 14:30
I have the same problem with blocks, and the console error messages that appear are:

react-dom.min.82e21c65.js:110 TypeError: e.on is not a function
    at Object.e (wp-tinymce.php:2)
    at jg.c.fire (wp-tinymce.php:2)
    at Object.fire (wp-tinymce.php:2)
    at new Hx (wp-tinymce.php:2)
    at n (wp-tinymce.php:2)
    at Array.<anonymous> (wp-tinymce.php:2)
    at qt (wp-tinymce.php:2)
    at e (wp-tinymce.php:2)
    at je.b.bind (wp-tinymce.php:2)
    at Object.F [as bind] (wp-tinymce.php:2)

**Comment by youknowriad** [comment] 2018-08-27 15:13
closed by #9373

Feel free to raise again if it's still happening after the release of 3.7

**Closed by youknowriad** 2018-08-27 15:13 UTC
Labels: [Status] Needs More Info, [Type] Help Request

**Comment by GManchester** [comment] 2018-08-31 15:39
It's still happening.

**Comment by youknowriad** [comment] 2018-08-31 15:44
@GManchester you're error is actually different from the initial one. It's probably a metabox error. Did you try disabling the plugins you have that add metaboxes?

**Comment by GManchester** [comment] 2018-09-01 11:08
Hi, yes I have disabled and deleted the metabox plugin I had. I've not been
able to post on classic editor either as the visual editor tab isn't
working. Only text editor.

Thanks

**Comment by RaneMstSage** [comment] 2018-11-21 06:02
I just received this error this morning after updating Gutenberg. After I press enter it gives me the error, I then have to save the draft and reopen or press f5 to refresh the page to continue working. I disabled Yoast SEO and it seems to have fixed it.
