### ISSUE TITLE
Block actions are cut off near the top of the screen

### ISSUE THREAD

**Issue by stompweb** [WordPress/gutenberg#5368] opened 2018-03-03 14:05 UTC
## Issue Overview

If you have blocks near to the top of the screen then sometimes the actions are cut off.
## Steps to Reproduce (for bugs)

1. Add a block with a little bit of content (i.e. paragraph)
2. Add another block and do not enter any content.

Using latest Chrome, WP 4.9.4 & Gutenberg 2.3.0. I'm on a laptop so obviously the screen height isn't as big.

## Expected Behavior

The actions should not be cut off.

## Current Behavior

Some of the actions are cut off - especially the delete action.

## Possible Solution

N/A

## Screenshots / Video

<img width="868" alt="screen shot 2018-03-03 at 13 56 54" src="https://user-images.githubusercontent.com/1017511/36935151-c9fcaf4a-1eeb-11e8-8a66-a22c72d5ac43.png">

**Comment by stompweb** [comment] 2018-03-04 17:07
Actually looks like it could be a duplicate of https://github.com/WordPress/gutenberg/issues/5276

**Comment by ktmn** [comment] 2018-03-05 06:16
I added this to editor styles as a temporary fix:

```
.components-popover:not(.is-mobile).is-top .components-popover__content {
  bottom: auto;
}
```

**Comment by youknowriad** [comment] 2018-03-06 16:02
closing as duplicate of #5276

**Closed by youknowriad** 2018-03-06 16:02 UTC
