### ISSUE TITLE
Excessive <svg> elements? As of 5.9.1 Release - Not present in 5.9.

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#39008] opened 2022-02-23 08:07 UTC
### Description

This was reported on Trac. Copy-pasting from https://core.trac.wordpress.org/ticket/55231
Props mvaleno for the original report.
---
This is a before and after.

Started with WordPress 5.9 updated to 5.9.1 and I see a bunch of <svg> elements before the wp-site-blocks <div> element.

One of these <svg> elements looks like this when expanded in the inspector:
```
<svg xmlns="http://www.w3.org/2000/svg[](https://ibb.co/TmwMJtf)[](https://ibb.co/W5XhRt4)" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;"><defs><filter id="wp-duotone-dark-grayscale"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 "></feColorMatrix><feComponentTransfer color-interpolation-filters="sRGB"><feFuncR type="table" tableValues="0 0.49803921568627"></feFuncR><feFuncG type="table" tableValues="0 0.49803921568627"></feFuncG><feFuncB type="table" tableValues="0 0.49803921568627"></feFuncB><feFuncA type="table" tableValues="1 1"></feFuncA></feComponentTransfer><feComposite in2="SourceGraphic" operator="in"></feComposite></filter></defs></svg>
```
There are many!

Here are the before and after 5.9.1 update images.

Looking at the home page twenty-twenty-two theme, default content, with Google inspect, WordPress 5.9
https://ibb.co/TmwMJtf

Looking at the home page twenty-twenty-two theme, default content, with Google inspect, WordPress 5.9.1
https://ibb.co/W5XhRt4

Not that they seem to be effecting anything, but 1) I can't find where they are generated 2) They are really cluttering the page structure in the inspector; as I use it to make sure I am following ARIA rules...

### Step-by-step reproduction instructions

See the above description.

### Screenshots, screen recording, code snippet

See the above description.

### Environment info

See the above description.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-02-23 08:19
Thanks, @audrasjb.

Possibly duplicate of #38299. I think this will be resolved via #38681.

**Comment by mvaleno** [comment] 2022-02-23 17:12
Thank you @audrasjb  for putting this in the right place! Was my first ticket... hehe. @Mamaduka, this issues may be related as it appears the svgs are for the duotones, but does not occur in 5.9, only in the 5.9.1 update. 

So, idk but it is a drastic amount of clutter before the web page container (div class="wp-site-blocks".) I would not think it is a notable performance hit. However, I been waiting for 5.9 to dive into parent theme development and now as I review the HTML build of my pages, I have to weed through all those svgs to get to the actual page. So, for me personally, as a novice developer, it effects my experience, while using browser dev-tools to inspect my pages.

WordPress 5.9 is nice and clean during inspection, by comparison. Hopefully, there is a more elegant way to implement what is being done with the duotones.

**Comment by Mamaduka** [comment] 2022-02-23 17:17
Thanks for contributing, @mvaleno.

Currently, we're trying to improve conditional checks that Duotone depends on to render required SVG filters.

There's also a new PR that will conditionally disable Duotone for Block Themes when it's not used on page - #39018.

**Comment by Mamaduka** [comment] 2022-04-12 12:06
I will close this since the general discussion is happening in #38299.

**Closed as completed by Mamaduka** 2022-04-12 12:06 UTC
Labels: [Status] Duplicate
