### ISSUE TITLE
Dragging a block to the right/left of another block should wrap both in a columns block

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#28773] opened 2021-02-05 09:55 UTC
Came up in a contributors day, testing the Gutenberg behavior.
Users expected to be able to drag a block to the right of another block and have it on the right.
Technically this would require wrapping both blocks in a columns block automatically and position them according to the user's action.

**Comment by mtias** [comment] 2021-07-14 11:41
Closing as duplicate of #13202 and #32819.

**Closed by mtias** 2021-07-14 11:41 UTC
Labels: Needs Design, [Feature] Drag and Drop, [Type] Feature
