### ISSUE TITLE
"Please wait... Generating preview." not translatable

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10874] opened 2018-10-21 15:36 UTC
![image](https://user-images.githubusercontent.com/18373563/47268974-c2b03900-d557-11e8-8c09-3d7aadd6ddd9.png)

`this.previewWindow.document.write('\n\t\t\t<div class="editor-post-preview-button__interstitial-message">\n\t\t\t\t<p>Please wait…</p>\n\t\t\t\t<p>Generating preview.</p>`

**Comment by swissspidy** [comment] 2018-10-21 17:07
Related: #7922.

**Comment by ocean90** [comment] 2018-10-21 17:20
Duplicate of #7725.

**Closed by ocean90** 2018-10-21 17:20 UTC
Labels: [Type] Bug, i18n
