### ISSUE TITLE
Editor: "Copy All Content" changes Gallery Blocks into List Blocks 

### ISSUE THREAD

**Issue by xpurichan** [WordPress/gutenberg#13303] opened 2019-01-12 19:05 UTC
(Note: reposting on behalf of liviopv from this original report: https://github.com/Automattic/wp-calypso/issues/29921)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a Gallery Block
3. Click on the "Show more tools & options" on the top right
4. Click on "Copy All Content"
5. Open a new post: https://wordpress.com/block-editor/post/
6. Paste the clipboard in the context box
7. All the other paragraphs will be pasted correctly, but the Gallery Block will be turned into a List Block

#### What I expected

Since we're just copying posts in the same site (so it's the same attachment IDs), the Gallery Block should be copied

#### What happened instead

The Gallery was transformed into an empty list

#### Browser / OS version

Mac OS 10.14.2
Chrome 71.0.3578.98

#### Screenshot / Video

http://cld.wthms.co/qAsI2h

#### Context / Source

Reported in 1691525-zen

#user-report

**Comment by tellthemachines** [comment] 2019-08-08 06:27
Hi there, I can't reproduce this either on my local Gutenberg dev environment or on wordpress.com so I guess it's been fixed in the meantime. Closing this issue for now but feel free to reopen if this occurs again.

**Closed by tellthemachines** 2019-08-08 06:27 UTC
Labels: Needs Testing, [Block] Gallery, [Component] Raw Handling
