### ISSUE TITLE
WP 5.2:  Change preview link or rewrite PostPreviewButton component

### ISSUE THREAD

**Issue by demo-igor** [WordPress/gutenberg#15895] opened 2019-05-29 16:18 UTC
**WP 5.2**
I would like to ask is it possible to update preview link for preview button on post edit page? I have a custom preview link and I'm able to update link related to php with add_action and add_filter but I' didn't find any way to update preview link to **PostPreviewButton**.
Maybe there is  possible to rewrite **PostPreviewButton** component?

**Comment by talldan** [comment] 2019-05-30 09:27
@demo-igor If it helps, the link that's used by `PostPreviewButton` is:
- The `preview_link` property received from the REST API autosaves endpoint if an autosave exists.
- The `link` property received from the REST APIs posts endpoint if there isn't an autosave.

I'm not sure if there are ways to intercept those properties on the post objects, but that might be the most promising route to investigate.

**Comment by demo-igor** [comment] 2019-05-30 09:51
@talldan the main problem to me that WP used the same API on many places and I don't want to change the API globally. I just would like to change preview link  for **PostPreviewButton** only, like I did with WP php hooks for another places.
Maybe we have a good way to modify selectors functions:
`wp.data.select('core/editor').getCurrentPostAttribute()
wp.data.select('core/editor').getEditedPostPreviewLink()`

**Comment by demo-igor** [comment] 2019-06-03 15:42
@youknowriad could you help to understand is it possible to replace link  for PostPreviewButton or maybe is it possible to updated those methods:
wp.data.select('core/editor').getCurrentPostAttribute() wp.data.select('core/editor').getEditedPostPreviewLink()
Thanks!

**Comment by ocean90** [comment] 2019-07-01 21:07
Closing as a duplicate of #13998.

**Closed by ocean90** 2019-07-01 21:07 UTC
Labels: [Status] Duplicate, [Type] Question

**Comment by chrisvanpatten** [comment] 2019-07-11 12:41
I'd like to consider reopening this as I think it's slightly distinct from #13998.

In my particular case, simply rewriting the preview link isn't enough — that gets a small part of the job done, but you are still unable to overwrite a lot of the behavior around how Gutenberg handles autosaving and preview generation.

In my case, I'm working within an architecture where our front-end is completely decoupled from WordPress _and_ from the WP API (two levels of headless!) where previews need to actually trigger a POST event with data from another database to work properly.

In my case, it would be much easier to be able to filter the button entirely, or completely disable it and provide my own alternative. As of now, I'm not able to find a great way to do that, short of using CSS, which feels frustratingly hacky in this declarative Gutenberg world.

**Comment by avblink** [comment] 2020-11-03 16:07
@chrisvanpatten have you solved the problem?
Could you please share your solution.

Thank you
