### ISSUE TITLE
Classic editor block not working in site editor.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#37706] opened 2022-01-04 10:27 UTC
### Description

Inserting a classic editor block will break it in site editor.

https://github.com/WordPress/gutenberg/blob/ca85ced9298a252d4832438d8408ea4cda95696f/packages/block-library/src/freeform/edit.js#L66

The error seems to occur because wpEditorL10n is undefined.

### Step-by-step reproduction instructions

1. Go to Site editor
2. Insert classic block
3. show error.

### Environment info

- WordPress 5.9-beta4, gutenberg latest.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-01-04 10:48
Hi, @torounit

I think this is a duplicate of #23086.

**Closed as completed** 2022-01-05 05:15 UTC
Labels: [Status] Duplicate, [Block] Classic, [Feature] Site Editor
