### ISSUE TITLE
Editor: Editor styles of Gutenberg overwrite theme editor styles

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#22221] opened 2020-05-08 12:54 UTC
**Describe the bug**

Gutenberg adds the following editor style, which overwrites the default editor styles of the theme:

```
.editor-styles-wrapper a {
    color: inherit;
    transition: none;
}
```

**To reproduce**

1. Go to 'https://themes.local/wp-admin/post-new.php'
2. Create a new post
3. Add at least one link

**Expected behavior**

The link is using the theme editor styles.

**Current behavior**

The link is using the Gutenberg editor styles.

**Screenshots**

<table>
<tr>
<td>Currently:
<br><br>

<img width="1278" alt="Screenshot 2020-05-08 at 19 50 29" src="https://user-images.githubusercontent.com/3323310/81407185-2d8a8a80-9165-11ea-897a-5be390d5f3b4.png">
</td>
<td>Expected:
<br><br>

<img width="1280" alt="Screenshot 2020-05-08 at 19 50 53" src="https://user-images.githubusercontent.com/3323310/81407233-3d09d380-9165-11ea-8878-2e9eb17e1432.png">
</td>
</tr>
</table>

**Editor version (please complete the following information):**
- WordPress version → 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? → Yes and this issue only occurs when the Gutenberg plugin had been activated
- If the Gutenberg plugin is installed, which version is it? → 7.9.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: Chrome 81.0.4044.129 (Official Build) (64-bit)

**Comment by juanallo** [comment] 2020-05-10 21:31
Same happened to me, seems to be a recent update?

**Comment by kjellr** [comment] 2020-05-11 12:21
Thanks for reporting! This appears to be a duplicate of https://github.com/WordPress/gutenberg/issues/22139, and it should be fixed as of https://github.com/WordPress/gutenberg/pull/22160. I'll close for now, but we can re-open if I'm incorrect about that. 👍

**Closed by kjellr** 2020-05-11 12:21 UTC
