### ISSUE TITLE
Custom Taxonomies Don't Show in the sidebar

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#3369] opened 2017-11-07 14:24 UTC
## Issue Overview

When viewing the Gutenberg editor, categories and tags appear in the sidebar, however, custom taxonomies do not

## Steps to Reproduce (for bugs)

1. Add a custom taxonomy to posts or a custom post type
2.Open the Gutenberg editor
3.The new taxonomies do not have a UI, and if only CT's are present, the categories and tags drawer shows nothing when expanded

## Expected Behavior

I expected to see the Custom taxonomies shown the same was categories and tags are shown

## Current Behavior

No custom taxonomy UI is available

## Possible Solution

Show the custom taxonomies as categories and tags are shown, respecting the visibility and hierarchy attributes set on registration

**Comment by aduth** [comment] 2017-11-07 14:32
Can you confirm whether the taxonomy has the `show_in_rest` property assigned as true? Since the editor operates using the REST API, taxonomies and post types must be whitelisted to be accessible within the editor. This is a restriction of the API itself, and one which has caused some trouble in the past.

Related: #2340, #3066

**Comment by lukecav** [comment] 2017-11-07 16:54
You can replicate by trying WooCommerce with Gutenberg, none of the product categories using `product_cat` will display in Gutenberg, when say editing or creating a new product.

**Comment by lukecav** [comment] 2017-11-07 17:02
`unction wc_product_category_add_tax_to_api() {
    $mytax = get_taxonomy( 'product_cat' );
    $mytax->show_in_rest = true;
}
add_action( 'init', 'wc_product_category_add_tax_to_api', 30 );`

Then the product categories would show.

![gutenberg product categories](https://user-images.githubusercontent.com/5797332/32506804-bde0dd34-c3a2-11e7-9cc9-0350a8d91d0f.png)

**Comment by tomjn** [comment] 2017-11-07 20:40
hmmm yes adding that fixed the issue, though it's still a regression

I would expect that since anybody with editor access will have Gutenberg access then would it make sense to make it so that `show_in_rest` was true by default is `current_user_can` indicate the logged in user can modify that taxonomy? This would fix the issue without revealing terms to the public or subscribers that could cause issues

**Comment by aduth** [comment] 2017-11-07 20:44
>I would expect that since anybody with editor access will have Gutenberg access then would it make sense to make it so that `show_in_rest` was true by default is `current_user_can` indicate the logged in user can modify that taxonomy? This would fix the issue without revealing terms to the public or subscribers that could cause issues

This may work, and is a question more of general REST API authorization behavior than it is specific to Gutenberg. It does impact the editing experience of course, and ought to be raised for consideration. Also relevant to #3066 and previously discussed at https://github.com/WordPress/gutenberg/issues/1342#issuecomment-319920850.

**Comment by mtias** [comment] 2017-11-20 13:44
Closing as duplicate of #3066 so we can keep the conversation in a single place.

**Closed by mtias** 2017-11-20 13:44 UTC
Labels: Core REST API Task, [Status] Needs More Info

**Comment by danicotillas** [comment] 2019-03-08 12:49
> `function wc_product_category_add_tax_to_api() { $mytax = get_taxonomy( 'product_cat' ); $mytax->show_in_rest = true; } add_action( 'init', 'wc_product_category_add_tax_to_api', 30 );`
> 
> Then the **product categories** would show.
> 
> ![gutenberg product categories](https://user-images.githubusercontent.com/5797332/32506804-bde0dd34-c3a2-11e7-9cc9-0350a8d91d0f.png)

Hi! This is working for me but I don´t know how should be the code when you have more than one Custom Category. My knowledge about PHP is not very good at all. Could you help me @lukecav ?
Thanks!
