### ISSUE TITLE
Image block: Align Center option not reflected in editor

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#21552] opened 2020-04-12 08:33 UTC
The **Align Center** option works, but the image alignment isn't updated in the editor and remains in the **Align Left** position, which is confusing as user would need to go back and forth between the site and editor to make sure images are aligned as they want.

![gif](https://user-images.githubusercontent.com/15944096/79064350-bdf6bc00-7cda-11ea-85eb-bf3a05e2d195.gif)

**Comment by draganescu** [comment] 2020-04-13 13:55
Howdy @formosattic I tested this using one of the default themes and could not reproduce the problem. Might this be an issue with the theme you are using? Can you test the same using, say, TewntyTwenty?

**Comment by jasmussen** [comment] 2020-04-16 11:22
Some of the float aspects have been improved in later versions of the plugin, that might have affected centering. @formosattic can you test in the most recent version of the Gutenberg plugin and see if it fixes the issue?

Alternatively, what theme are you using? Themes can (and arguably should) customize how elements are aligned, and there may be a bug here with the theme.

**Comment by karmatosed** [comment] 2020-04-24 16:42
For now, let's close this up until we have more information. It can always be reopened once that happens.

**Closed by karmatosed** 2020-04-24 16:42 UTC
Labels: [Status] Needs More Info
