### ISSUE TITLE
WP 5.2.2 impossible to find publication option "immediately"

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/gutenberg#16766] opened 2019-07-26 08:50 UTC
**Describe the bug**
impossible to find publication option "immediately"

**To reproduce**
1. I write an article and put it in a draft
2; I come back to this article several days later, it displays "Published on (date of the first edition)
3. Can not have the function "published immediately" or to reset the publication date ".
4. I try to plan the article, except it does not work, I put it, a minute later, for example it is 10:30, I program at 10:31 or 10:32, but it does not publish not.

How to do ?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 5.2.2 de WordPress

**Comment by swissspidy** [comment] 2019-07-31 14:34
Sounds like a duplicate of #12048.

**Closed by swissspidy** 2019-07-31 14:34 UTC
Labels: [Component] Saving, [Status] Duplicate
