### ISSUE TITLE
Duplicating a block no longer works reliably

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15716] opened 2019-05-18 08:07 UTC
**Describe the bug**
After duplicating a block (a Heading Block in this instance), it looks like it works, but when I click on the block to edit it, the content disappears, the background colour changes and I cant edit the text. I can't even move the block either.

When I click on the block, it doesn't show the block toolbar either.

https://cl.ly/1f4f31eac6ba

**To reproduce**
1. Duplicate a heading block
2. Try and edit it
3. Try and move it

**Expected behavior**
Duplicating the block shouldn't break the block

**Screenshots**
<img width="1191" alt="screenshot_04" src="https://user-images.githubusercontent.com/2078245/57966588-6d29f680-7997-11e9-9d2a-8f5d2e4aa2a4.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox Quantum 66.0.5
 - Version: WP 5.2 & TwentyNineteen

**Comment by maddisondesigns** [comment] 2019-05-18 08:10
After trying multiple times, sometimes it works, sometimes it doesn't.

**Comment by youknowriad** [comment] 2019-05-21 09:37
I was not able to replicate this yet, do you think you can find more details about the testing instructions to reproduce?

**Comment by maddisondesigns** [comment] 2019-05-22 06:47
It looks like it happens when you're in Responsive Design Mode (in Firefox).
I duplicated a (Heading) Block and then went to try and drag it to another location. As soon as you try to move it, it breaks.

Another vid: https://cl.ly/4f9f6876b56d

**Comment by youknowriad** [comment] 2019-05-22 08:00
Thanks 👍 It wasn't clear initially that this was related to drag and drop.

**Comment by youknowriad** [comment] 2019-05-22 08:00
cc @nosolosw in case you have ideas here.

**Comment by nosolosw** [comment] 2019-05-23 11:54
Didn't have the time to dig deeper, but wanted to share what I've found so at least we can reliable reproduce: it looks like if you switch to Responsive Mode, then Drag&Drop, then go back to normal mode things doesn't properly. 

Created https://github.com/WordPress/gutenberg/issues/15795 to track this issue. Going to close this as to not confuse the bug report.

**Closed by nosolosw** 2019-05-23 11:54 UTC
Labels: Block API, Drag and Drop, Needs Testing
