### ISSUE TITLE
Blocks inside a InnerBlocks container with "insert" templateLock can be dragged outside of the container

### ISSUE THREAD

**Issue by garciaalvaro** [WordPress/gutenberg#11131] opened 2018-10-26 17:38 UTC
**Describe the bug**
The documentation states: 
> insert — prevents inserting or removing blocks, but allows moving existing ones.

I might be reading this wrong but I interpreted the lock permits moving the inner blocks within the container but not to/from the outside. So there will always be the blocks set in the template, but they can be reordered.
Currently it is possible to drag inner blocks to the outside (to a different container or the root). If my interpretation is correct this should not be allowed. However, it is not possible to drag a block from the outside to the inside. 

**Versions**
- Gutenberg 4.1.1
- WordPress 4.9.8

**Comment by designsimply** [comment] 2018-10-26 18:14
May we have some basic steps for testing this? I would like to try to check it out but am not very experienced with coding Gutenberg so a code example would be really awesome. If you don't have one, that's okay and we can wait to see if we can get a response about what the intended behavior is with regard to locked blocks in a template and whether or not it should be possible to drag them out without seeing a code example.

**Comment by alvaro0555** [comment] 2018-10-26 18:34
Sure, no problem. For example, insert this test block in the page:

`
registerBlockType("qqq/qqq", {
	title: "qqq",
	icon: "carrot",
	category: "common",
	attributes: {},
	edit(props) {
		return (
			<div>
				<InnerBlocks
					template={[
						["core/quote"],
						["core/image"],
						["core/quote"]
					]}
					allowedBlocks={[
						"core/quote",
						"core/image",
					]}
					templateLock="insert"
				/>
			</div>
		);
	},
	save(props) {
		return null;
	}
});
`
Add the block inside the page (a quote, an image and a quote will be included inside).
Start dragging any of the three: this is expected as "insert" allows reordering the inner blocks.
Drop the block outside of the container into the root: this is where the problem happens, the drop should only be allowed before/after the sibling blocks, always inside the container block, as far as I understood.

I hope it is clear. Thanks.

**Comment by momotofu** [comment] 2020-01-23 05:22
This seems to no longer be an issue, since we were unable to reproduce the bug. Blocks weren't able to be dragged out of the container when having templateLock set to "insert".

**Closed by momotofu** 2020-01-23 05:22 UTC
Labels: Needs Testing, [Feature] Drag and Drop, [Feature] Nested / Inner Blocks, [Feature] Templates API
