### ISSUE TITLE
Text lines overlap when color background added

### ISSUE THREAD

**Issue by adrian29630** [WordPress/gutenberg#52660] opened 2023-07-15 19:58 UTC
### Description

If you have added a text block with text written and then use settings to add a background color to that block on occasions, it seems lower down the page, the lines of text overlap once the page or post has been saved. 

You can see examples on the screenshots provided.
![screenshot-metrosaludrd com-2023 07 15-15_14_20](https://github.com/WordPress/gutenberg/assets/17201344/298d5160-1ae0-403d-b865-094b72c1aa1e)
![screenshot-metrosaludrd com-2023 07 15-15_16_39](https://github.com/WordPress/gutenberg/assets/17201344/c02561aa-c2fc-4a37-9cbc-b077632d2f29)

### Step-by-step reproduction instructions

Add a series of text blocks to a page or post.
Add background colors to the text blocks
Save the page or post
View the page either in preview or by publishing and viewing the live post
You will see at some point where two lines of text overlap and are no longer clear

### Environment info

WordPress V6.2.2 Gutenberg latest version with WP version Theme: MediCenter - Health Medical WordPress Theme
Browser All but mainly Firefox or Chrome
Laptop Windows 10 fully up to date

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2023-07-17 10:12
Hi!
What setting are you using to set a background color? The sidebar background color option, or the Highlight color option in the toolbar? Do I understand correctly from the images that you are adding a custom gradient as the background?

Can you reproduce this with a default theme like Twenty Twenty-Three?

**Comment by adrian29630** [comment] 2023-07-17 20:38
Hi

Please see the attached screenshot showing where/how the background was
added. I tried switching to a default theme and it does not seem to happen
there but the layout is completely different as well so maybe this is
related to the theme but the the says it is compatible with blocks as well
as WP Bakery which was not used to create this post.

Kind regards

Adrian

**Comment by felipevelzani** [comment] 2023-07-17 21:06
Hi Adrian,

I tried to reproduce this issue, but it works as expected from my end. Can you please try with a default theme again and ensure you don't have other plugins enabled?

https://github.com/WordPress/gutenberg/assets/40555737/0412639a-db0a-4e26-afc3-552d2d75e0e2

**Comment by carolinan** [comment] 2023-07-17 21:27
@adrian29630 while I can see the colors, the images does not show which option was used to add them. 

The paragraph block background color is usually covering a full row, it is not normally cut off like in image two, second paragraph.


Overlapping text can happen when the line height of a text is changed. Adding a background does not normally change the line height.

**Comment by adrian29630** [comment] 2023-07-17 21:45
Please see below:

Kind regards

Adrian


On Mon, Jul 17, 2023 at 5:27 PM Carolina Nymark ***@***.***>
wrote:

> @adrian29630 <https://github.com/adrian29630> while I can see the colors,
> the images does not show which option was used to add them.
>
Unfortunately, a screenshot does not offer the option to show the open box
where the colors are chosen. This was the 5th default color/gradient/Linear
type/Gradiant 135 deg.  That is all I can really tell you.

> The paragraph block background color is usually covering a full row, it is
> not normally cut off like in image two, second paragraph.
>
On the draft page that is what is seen and expected. Of course on the front
end/live the length of the line of text changes to fit the width of the
column so the break in the text happens at an earlier point.  Why it is
different on the front and back I have no idea.

> Overlapping text can happen when the line height of a text is changed.
> Adding a background does not normally change the line height.
>
Yes, that would make a difference but not in this case.  The text had been
written with no edits to the line spacing and the color background was
added later.

As I said, as this does not happen if the page is viewed in a default theme
I am assuming that the theme is the culprit but the theme says it should
work with Blocks so it should not happen.

**Comment by felipevelzani** [comment] 2023-07-18 17:22
Hi again,

> As I said, as this does not happen if the page is viewed in a default theme I am assuming that the theme is the culprit but the theme says it should work with Blocks so it should not happen.

In this case, can you please contact your theme authors and explain that you can't reproduce with the default theme? They would need to debug to identify if there is something specific on the Gutenberg plugin triggering this issue.

After that, if they identify that as something on Gutenberg (and not something specific that they had on the theme), please do let us know, so we can check this further. I'm going to close this issue for now.

**Closed as completed by felipevelzani** 2023-07-18 17:22 UTC
Labels: [Type] Bug, [Status] Needs More Info
