### ISSUE TITLE
Slash inserter: enable searching blocks with more than one string match

### ISSUE THREAD

**Issue by ShinichiNishikawa** [WordPress/gutenberg#8365] opened 2018-08-01 15:55 UTC
**Is your feature request related to a problem? Please describe.**

When searching, for example, image block in Japanese `/image` doesn't work but instead you need to change your typing language to Japanese and type `/画像`. This isn't a pleasant experience because I need to first set the typing language to English to get `/`, and then switch to Japanese to type `画像`. It would be much better if I can get the image block both with `/image` and `/画像`.

If this issue is solved, it will give more possibilities. 
We can get Twitter oEmbed block by typing `/sns`, `/tweet`, and `/ツイッター` in addition to `/twitter`. 

**Describe the solution you'd like**

It would be nice if we can register multiple search keywords for each block.

**Comment by chrisvanpatten** [comment] 2018-08-02 04:06
So it is possible to pass multiple keywords in for a block that are triggered in the inserter (for example you can type “h2” to find the heading block).

So I expect here the issue is actually allowing translators to provide _additional_, language-specific options for a block’s keywords. This would be useful as in the case in the issue report (languages with non-Roman characters that might require changing between different text input methods, and trying to improve that case) or perhaps if there are any languages that might have multiple words to refer to a concept that only has one word in English.

**Comment by mcsf** [comment] 2018-08-21 17:17
I left a comment on #6633 that uses @ShinichiNishikawa 's case as illustration. If the proposal seems like a good start, I propose closing this issue in favor of #6633.

**Comment by mcsf** [comment] 2018-08-24 15:43
Closing in favor of #6633.

**Closed by mcsf** 2018-08-24 15:43 UTC
Labels: [Component] Inserter, [Type] Enhancement, i18n
