### ISSUE TITLE
Themes should use site language on Block editor canvas

### ISSUE THREAD

**Issue by OmerQadirFM** [WordPress/gutenberg#64074] opened 2024-07-30 03:36 UTC
### Description

when user profile language is different from site language, on Block editor canvas display theme in user profile language, and on the website front display site language

### Expected Results
✅ the Website should display site language on Front and Block editor canvas

### Actual Results
❌ the Website always display in user profile language on Block editor canvas

### Step-by-step reproduction instructions

1. go to General Settings -> Site Language, change it to Kurdish or another language
2. go to User -> Profile -> Language, change it to English or another language that's different from site language

* It always happens when Site and User language are different 

### Screenshots, screen recording, code snippet

![Screenshot 2024-07-30 040914](https://github.com/user-attachments/assets/d7e8cd69-e50d-400e-9cf7-02dce1a1ea29)
![Screenshot 2024-07-30 040936](https://github.com/user-attachments/assets/4d46e01b-0d53-43e2-9bd5-b2a5a681eb89)

### Environment info

- WordPress: 6.6.1
- PHP: 8.1.29
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.29)
- Browser: Edge 127.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Four 1.2
- MU-Plugins: None activated

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment] 2024-07-30 05:49
I think this has been discussed several times, and using user locale was the correct choice.

@swissspidy, do you have any input?

**Comment by swissspidy** [comment] 2024-07-30 06:41
Duplicate of #52777 I believe

**Closed as not planned by swissspidy** 2024-07-30 06:41 UTC
Labels: [Type] Bug, Internationalization (i18n), [Status] Duplicate

**Comment by ramonjd** [comment] 2024-07-30 08:44
I asked @OmerQadirFM to create this one to track the translation side of things specifically, mainly to narrow the scope of the issue, especially if https://github.com/WordPress/gutenberg/pull/63883 ever gets in.

I believe themes like TT4 are translated in the cited language, but the _site_ locale isn't being loaded.

If folks prefer to keep the other one and close this, it's all good 👍🏻

**Comment by swissspidy** [comment] 2024-07-30 09:37
we‘ll want to use the correct text direction **and** the correct translation for that to be really useful

**Comment by ramonjd** [comment] 2024-07-30 09:50
> we‘ll want to use the correct text direction and the correct translation for that to be really useful

No dispute there.

If users are typing their own template and other post/page locale language text into the editor, then wouldn't https://github.com/WordPress/gutenberg/pull/63883 be "semi" useful in that scenario? And therefore be one of a couple of iterations?

Unless I'm missing something. 

As mentioned, I'll defer to folks' preference on the specific question of whether to close this issue as duplicated.

**Comment by swissspidy** [comment] 2024-07-30 10:26
#52777 is about locale and text direction. Are you suggesting that one should be just for the text direction, and this one for the locale?

**Comment by ramonjd** [comment] 2024-07-30 12:36
> Are you suggesting that one should be just for the text direction, and this one for the locale?

Yes. 

No worries at all to keep this closed and let the original issue stand 👍🏻

**Comment by OmerQadirFM** [comment] 2024-07-30 13:05
![Screenshot 2024-07-30 153933](https://github.com/user-attachments/assets/12dbcc48-b954-41be-b09d-904e9ff6c48c)
![Screenshot 2024-07-30 153909](https://github.com/user-attachments/assets/742ac1d7-2891-4738-99ce-b8d4151ac60e)
