### ISSUE TITLE
Templates `lookup` REST endpoint can result in inconsistent results between the editor and front end.

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#55920] opened 2023-11-07 10:02 UTC
While testing [this PR](https://github.com/WordPress/gutenberg/pull/55883), I observed that the `lookup` REST endpoint in Templates controller will loop through the available templates following the templates hierarchy, but also skips an existing template which is empty.

This can lead to inconsistent results between the editor and front end.

## Testing instructions
1. In site editor create a custom template for a page and leave it empty.
2. View this page in site editor and in the front end.
3. Observe the inconsistency. 

--cc @jorgefilipecosta

**Comment by jorgefilipecosta** [comment] 2023-11-07 11:04
Hi @ntsekouras,
The ignore empty flag is optional and when enabled to objective is to show a non-empty template that can act as a fallback.
I guess in the case you describe the site editor should load the empty template correctly as in the frontend, but a modal will appear offering a possibility to start from a non-empty state higher in hierarquy if the user wants to. Isn't that what you are experiencing?

**Comment by jorgefilipecosta** [comment] 2023-11-15 11:02
Hi @ntsekouras if you are experiencing what I referred above, I guess we can close the issue?

**Comment by ntsekouras** [comment] 2023-11-16 07:18
>I guess in the case you describe the site editor should load the empty template correctly as in the frontend, but a modal will appear offering a possibility to start from a non-empty state higher in hierarquy if the user wants to

Yes, that's exactly the problem, but that's the reason for the issue. Why close it if we don't fix it?

**Comment by youknowriad** [comment] 2024-10-24 16:54
If I'm reading this properly, things are working as intended. If you're looking for non empty templates you pass the flag and the result is different than the frontend but your intent is to look for a fallback template to the one being created.

**Closed as completed by youknowriad** 2024-10-24 16:54 UTC
Labels: [Type] Bug, [Feature] Templates API, REST API Interaction
