### ISSUE TITLE
Can't copy Separator block with keyboard shortcut

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#27729] opened 2020-12-15 04:25 UTC
**Describe the bug**

Trying to copy a Separator block by using ctrl+C or cmd+C has no effect. 

**To reproduce**
1. Open a new post
2. Add a separator block
3. With the block selected, press ctrl+C or cmd+C
4. Verify that block is not copied to clipboard

**Expected behavior**

Expected keyboard shortcuts to work the same as for other blocks.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- If the Gutenberg plugin is installed, which version is it? latest Gutenberg

**Comment by ntsekouras** [comment] 2020-12-15 13:53
Hey @tellthemachines - I can confirm that `Separator` didn't work, but I was able to copy `Spacer` with keyboard shortcuts.

Can you share specifics about `Spacer`, like browser etc..?

Thanks!

**Comment by tellthemachines** [comment] 2020-12-15 23:22
@ntsekouras I was testing on Chrome/macOS but pulling the latest from master the Spacer block does seem to be fixed now. It's not working on 5.6 without the plugin. Any idea when it was fixed? Might be good to get the fix into 5.6.1 (whenever that happens).

**Comment by ntsekouras** [comment] 2020-12-18 13:49
I don't know, no 😞

**Comment by tellthemachines** [comment] 2021-01-04 00:25
Edited to reflect that Spacer is now fixed.

**Comment by noisysocks** [comment] 2021-01-06 04:46
This works for me when I test latest Gutenberg `master` in Firefox. Is it browser related?

**Comment by mcsf** [comment] 2021-07-14 11:29
Can't repro either. Also tested on Safari, macOS.

Closing until we have new reports of this.

**Closed by mcsf** 2021-07-14 11:29 UTC
Labels: [Block] Separator, [Package] Keyboard Shortcuts, [Type] Bug
