### ISSUE TITLE
Global Styles: New colours added to palette removing existing ones.

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#26703] opened 2020-11-04 18:03 UTC
**Issue:** 

Adding a new colour to the colour palette removes existing colours theme / default colours.

![2020-11-04 11 53 41](https://user-images.githubusercontent.com/545779/98151154-5cc05100-1e95-11eb-8b20-45045ea3e499.gif)

**What I expected:**

Adding a colour would add to the existing list.

Additionally, there appear to be some alignment issues with the colour palette section relative to the rest of the panel in the inspector.

**Comment by carolinan** [comment] 2020-11-08 11:30
I second this, when testing I also found it strange that the new color replaces the current palette instead of add to it.

**Comment by nosolosw** [comment] 2020-11-23 17:23
I think this was fixed recently (tested master and can't reproduce, the user-provided color is appended), so I'm going to close this.

**Closed by nosolosw** 2020-11-23 17:23 UTC
Labels: Global Styles, [Type] Bug
