### ISSUE TITLE
Embed Spotify block is failed

### ISSUE THREAD

**Issue by sukezane** [WordPress/gutenberg#17139] opened 2019-08-22 08:52 UTC
**Describe the bug**
Embed Spotify block is failed. 
Also I got an error message on console:
Failed to load resource: the server responded with a status of 404 ()
https://example.com/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F7COXchtUOMd6uIT6HvmRaI&_locale=user

Also I got message on above the URL.
```

{"code": "rest_forbidden", "message": "Sorry, you do not have permission to make requests from oEmbed with proxy.", "data": {"status": 401}}
```
**To reproduce**
1. Insert Spotify Block
2. Enter URL(https://open.spotify.com/track/7COXchtUOMd6uIT6HvmRaI)
3. click "Embed"

**Expected behavior**
Spotify embed appear on editor.

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/56a6ea829d30528a6b4a17a285511e05/raw)](https://gyazo.com/56a6ea829d30528a6b4a17a285511e05)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4
 - Browser Chrome
 - Version 72

**Additional context**
- Gutenberg 6.3
- Wordpress 5.2.2

**Comment by senadir** [comment] 2019-08-22 09:38
Spotify doesn't support oEmbed discovery on single tracks for some reason (try contacting Spotify about this point since Gutenberg can't do anything about it).
The problem is, they provide embed option to single tracks, just not the discovery. a solution you can use for now is to use an HTML block and paste the embed code directly into it.

```html
<iframe src="https://open.spotify.com/embed/album/13yMsBNa2femeWzhcDOqFw" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```

**Comment by KokkieH** [comment] 2019-08-23 10:43
@senadir 

We've received a report via the [WordPress.com Twitter](https://twitter.com/JamesonSayer/status/1164825223599808513) account from someone claiming the embed block used to work with single track links, but recently stopped working. They also provided a link to a post created in the block editor which show the track properly embedded in [this tweet](https://twitter.com/JamesonSayer/status/1164848990141263872).

This also doesn't only happen with single tracks. I'm able to replicate the same issue with album and playlist links as well, on both WordPress 5.2.2 and on a WordPress.com site.

**Comment by senadir** [comment] 2019-08-23 10:47
hey @KokkieH I will test more & report back, if someone else can test as well, find a version that caused this problem, if someone can tell me what version does .com uses so I can see if there is a regression there.

**Comment by KokkieH** [comment] 2019-08-23 10:53
.com is on the latest versions of Core and Gutenberg, so 5.2.2 and 3.6 respectively.

Doing some more testing here, and this appears broken in the classic editor as well, where I know for certain it used to work. So it's possible something changed in the oEmbed implementation on Spotify's end.

**Comment by youknowriad** [comment] 2019-08-23 11:04
It could be a good idea to report a trac ticket (as this is more server-side and handled in Core). Also, maybe reach out to Spotify to check if something changed.

**Comment by senadir** [comment] 2019-08-23 11:06
implementation of oEmbed depends on an open framework that is shared between all oEmbed blocks using the same foundation, since all other blocks works fine for now and not spotify, it seems something changed from spotify side.
as I stated, the person can use Spotify app, copy the embed code from there, create an HTML block and paste that code directly.

**Comment by KokkieH** [comment] 2019-08-29 09:43
Circling back to this I was able to dredge up some old posts on a test site where I tested Spotify embeds at one point last year, and based on those posts something has indeed changed on Spotify's end, specifically, the playlist URL structure has changed from `https://open.spotify.com/user/spotify/playlist/*` to `https://open.spotify.com/playlist/*`, and that leads me to think they might have made other changes as well.

I've done another round of testing, and today I'm able to embed single track, album, and playlist links, in both the block and classic editors. The embeds work correctly in the editor and on the published post. And I checked both pasting the link into a Spotify block, and just pasting the link so it auto-selects the correct block. I've confirmed it works correctly on WordPress.com as well.

So if this issue was caused by changes on Spotify's end, it appears they have since fixed it as well.

(Just for additional context: Last year's issue was regarding Spotify desktop URLs with `https://open.spotify.com/user/spotify/playlist/*` correctly embedding on WordPress, but Spotify web player URLs with `https://open.spotify.com/playlist/*` not embedding. I'd reported the issue to Spotify at the time in https://github.com/spotify/web-api/issues/1060

Now it seems the desktop app URL structure has been changed to be the same as the web app.)

**Comment by senadir** [comment] 2019-08-29 10:40
I filled a report with the support team a week ago about this issue, glad it's fixed now

**Closed by senadir** 2019-08-29 10:40 UTC
Labels: Regression, [Block] Embed
