### ISSUE TITLE
Post terms are not set by the time the 'save_post' hook runs, whereas in the classic editor they are

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#8032] opened 2018-07-18 17:40 UTC
**Describe the bug**
With the classic editor, by the time the [`save_post`](https://developer.wordpress.org/reference/hooks/save_post/) hook is called, the post's terms (custom taxonomies) have been set using `wp_set_post_terms`. See [here](https://github.com/WordPress/WordPress/blob/4c2fcf36a3193a7e63a82e5ff459f2587c69a859/wp-includes/post.php#L3693) in `wp-includes/post.php`.

With Gutenberg, the post terms are not set by the time `save_post` runs, which has meant the behaviour of code hooked onto this action may be different. For plugin editors, it would be reasonable to assume that the updated terms would be set by the time the hook runs, since this is what saving with the classic editor would do.

I'm not sure what to do about this - I guess this isn't strictly a bug in Gutenberg, but rather an unfortunate difference in behaviour when using the REST API to edit posts. However, I thought I'd post it here in case the plan for Gutenberg is to try to mimic the classic editor's order of operations as closely as possible.

**To Reproduce**
1. Set a hook on `save_post` which writes the terms for a custom taxonomy associated with a post to the debug log.
2. Edit the post with the classic editor, and change the terms in the custom taxonomy.
3. Note the list of terms printed on the debug log - this will be the *new* terms.
4. Reset the post to the initial terms before step 2.
5. Edit the post with Gutenberg, changing the terms to whatever was also set in step 2.
6. Note the list of terms printed on the debug log - this will be the *previous* terms associated with the post before step 5.

**Expected behavior**
The new custom taxonomy terms should be updated prior to the execution of `save_post`, just like in the classic editor.

**Additional context**
- Gutenberg 3.2.

**Comment by chrisvanpatten** [comment] 2018-07-18 18:01
Ohhh this is a really interesting one that'll impact some of our code. Thanks for the report.

**Comment by danielbachhuber** [comment] 2018-07-20 13:00
Hi @SeanDS,

Thanks for the report. This issue is a duplicate of #3898. Preparing a patch on https://core.trac.wordpress.org/ticket/42864 would be a productive next step.

**Closed by danielbachhuber** 2018-07-20 13:00 UTC
Labels: Needs Testing, [Component] Saving

**Comment by SeanDS** [comment] 2019-01-06 11:15
@danielbachhuber The behaviour is still inconsistent between the classic editor and Gutenberg - the post terms are still saved to the parent post *after* the revision is created in Gutenberg (at least as of WordPress 5.0.2) whereas in Classic they save before. The core ticket above has been merged but this simply created new hooks and didn't move the creation of post terms to these hooks.

**Comment by Kubitomakita** [comment] 2019-01-09 10:30
Seems like `rest_insert_{$post_type}` action is still being executed before terms are saved.

You want to use the `rest_after_insert_{$post_type}` hook and I can confirm it's working.

**Comment by SeanDS** [comment] 2019-01-09 14:34
@Kubitomakita my problem is not so much the lack of available hooks, more the difference in behaviour between the two editors.

In any case, I've found a workaround that doesn't require using any post-terms-being-set hooks now.
