### ISSUE TITLE
Unable to select all blocks/text

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1006] opened 2017-06-02 15:17 UTC
I expected to be able to select all blocks using my systems shortcut command (cmd+a), but it doesn't work — it just selects all the HTML text in wp-admin. Ideally, I'd be able to cmd+a to copy and then paste somewhere else. Similarly, I'd expect to be able to cmd+a and paste to replace it all. Or, cmd-a and delete to remove everything.

**Comment by aduth** [comment] 2017-06-02 15:18
Duplicate of #3

**Closed by aduth** 2017-06-02 15:18 UTC
