### ISSUE TITLE
Allow insertion of reusable block of allowed type

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19932] opened 2020-01-28 17:57 UTC
**Describe the bug**
Currently it is not possible to insert a reusable block into a block with restricted allowed block types,
even when the reusable block contains (solely, top) a block with allowed block type.
Example: A button with image has been prepared and should now be re-used among the site.
The current implementation of buttons block allows only the insertion of a new button block,
not the insertion of a button block that had been made reusable block, at least not by using the UI.

**To reproduce**
1. Create a buttons block. Then create a button block inside.
Notice that it isn't possible to make a singular button block a reusable block (it had been possible in Gutenberg before the buttons block was introduced though).
Also notice that the inserter only allows adding new button blocks, there is no option available for reusable blocks of button block type.

**Expected behavior**
The inserter allows selection of reusable blocks of button block type.

**Comment by jorgefilipecosta** [comment] 2020-01-28 22:24
Hi @strarsis, you can create a buttons block with a single button inside and make that block reusable. Would that be equivalent to what was possible before:"make a singular button block a reusable block"?

**Comment by strarsis** [comment] 2020-01-29 11:59
@jorgefilipecosta: The `buttons` block is a container and can be styled, e.g. like a round buttons ring on a TV remote. When `button` blocks only can be reused by adding them with their own `buttons` block, they would also appear separately and not as being part of an existing `buttons` block.

**Comment by jorgefilipecosta** [comment] 2020-01-30 10:34
Hi @strarsis, thank you for the additional details. Yes, I agree this is an issue. A generic one not specific to buttons a general reusable blocks problem. Basically, when we specify a block can only exist inside another block the reusable block insert mechanism is not taking that restriction into account.

**Comment by youknowriad** [comment] 2020-01-30 10:40
I consider this an enhancement and not a bug and I also question whether we need it or if it's too complex to be worth it.

Reusable blocks don't just contain a single block, they can contain multiple ones and they can be edited independently from the parent block.

Say for instance I create a reusable block today that is a button, I assigned it as a child to a buttons block and then later I forgot about that, I'm editing my reusable block and I decide to change that block and make it a paragraph or a link instead of a button. This would break the previous usage without even noticing.

For this reason, I think we should probably just accept we currently have and close this issue.

**Comment by jorgefilipecosta** [comment] 2020-01-30 10:52
> Say for instance I create a reusable block today that is a button, I assigned it as a child to a buttons block and then later I forgot about that, I'm editing my reusable block and I decide to change that block and make it a paragraph or a link instead of a button. This would break the previous usage without even noticing.


That's a very good point, yes a reusable block type may change in the future. I guess that makes it impossible to solve this problem in a reliable way and make sure things don't break. I will close the issue for now.

**Closed by jorgefilipecosta** 2020-01-30 10:52 UTC
Labels: [Feature] Reusable Blocks, [Type] Enhancement
