### ISSUE TITLE
Toggle Control ClassName no added to Editor

### ISSUE THREAD

**Issue by jjlmoya** [WordPress/gutenberg#15481] opened 2019-05-07 09:50 UTC
**Description**
When you add a custom className to ToggleControl Component classes are not added to editor control

**To reproduce**
Use Toggle Control with ClassName field.
Go to Inspect Elements
Search 'components-base-control components-toggle-control'
And see the missing classes

**Expected behavior**
Add ClassName field to HTML

Comments:
Probably a good first issue.
Can you assign to me, I'll try to help with this :)

**Comment by Soean** [comment] 2019-05-07 13:02
I haven't tested it yet, but I can't see any error in the code at first sight:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/toggle-control/index.js#L46

**Comment by jjlmoya** [comment] 2019-05-07 17:08
I didn't see nothing in the code neither but I attach a few screens:
![image](https://user-images.githubusercontent.com/29946421/57318739-519f3000-70fb-11e9-9a62-22e84ffb2465.png)
![image](https://user-images.githubusercontent.com/29946421/57318765-6085e280-70fb-11e9-9dcf-37786e6e40af.png)

Maybe fixed yet? My version WordPress 5.1.1

**Comment by tellthemachines** [comment] 2020-02-20 06:00
Closing this issue because I'm unable to reproduce it. The `LinkControl` component uses `ToggleControl` with classname and it works correctly.

**Closed by tellthemachines** 2020-02-20 06:00 UTC
Labels: Needs Testing
