### ISSUE TITLE
Images disappear when publishing a post

### ISSUE THREAD

**Issue by LaryRauh** [WordPress/gutenberg#12974] opened 2018-12-18 12:39 UTC
**Describe the bug**
I published a post containing 8 images total, but the last 3 of them disappeared when opening the post live on my website. They had been visible in the preview and the editor before but just weren't shown anymore as soon as the post was published. A friend opened the post on her phone and laptop and wasn't able to see them either. 

**To Reproduce**
1. Go to 'New Post'
2. Insert images
3. Publish the post
4. See if there are images not being displayed towards the end of the post

**Expected behavior**
All pictures should have been shown, instead there was a blank.

**Desktop (please complete the following information):**
 - OS: macOS Mojave Version 10.14.1 
 - Browser: Safari
 - Version 12.0.1 

**Additional context**
Gutenberg Version: 4.7.1

**Comment by designsimply** [comment] 2019-01-07 20:50
I tested using WordPress 5.0.2 with no active plugins using Safari 12.0.2 on macOS 10.13.6 and was unable to reproduce the problem using the following steps:

1. Go to Posts > Add New.
1. Drag eight selected images into the editor all at once.
1. A gallery block is automatically created.
1. Publish and view the post. Check to see that images appear normally.
1. Go to Posts > Add New.
1. Drag eight images, one at a time, into the editor.
1. Each image appears as a separate block.
1. Publish and view the post. Check to see that images appear normally.

<strong>Result:</strong> all images appeared normally.

<sup>Tested on https://testingallthetime.com/ with WordPress 5.0.2 and no active plugins using Safari 12.0.2 on macOS 10.13.6. I used the Twenty Nineteen 1.1 theme in my testing.</sup>

Since we have now had two replies of testing without being able to reproduce, I am closing this issue. Please update to the latest version of WordPress and deactivate the Gutenberg plugin and test again. If the problem persists, please re-open this issue and mention which version of WordPress you tested with and whether your testing steps are any difference compared to the ones listed above.

**Closed by designsimply** 2019-01-07 20:50 UTC
Labels: [Status] Needs More Info
