### ISSUE TITLE
Tests: The column block fixture uses a "columns" closing tag instead of "column"

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#59145] opened 2024-02-18 03:32 UTC
### Description

The [column block fixture](https://github.com/WordPress/gutenberg/blob/trunk/test/integration/fixtures/blocks/core__column.html) is closed with `<!-- /wp:columns -->` not `<!-- /wp:column -->`

```
<!-- wp:column -->
<div class="wp-block-column">
	<!-- wp:paragraph -->
	<p>Column One, Paragraph One</p>
	<!-- /wp:paragraph -->
	<!-- wp:paragraph -->
	<p>Column One, Paragraph Two</p>
	<!-- /wp:paragraph -->
</div>
<!-- /wp:columns -->
```

Is this intentional?

### Step-by-step reproduction instructions

See the linked file above

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2024-02-19 01:21
I believe this is a simple typo 😅

**Comment by talldan** [comment] 2024-02-19 02:57
Wow. Should it be failing if it's wrong? 😅

**Comment by t-hamano** [comment] 2024-02-19 03:17
Maybe the block parser or something isn't accurate and we might need to look into the root cause.
For example, if I update the closing comment of a paragraph block, the block will still render. However, if you update the content, the closing comment will be corrected automatically 🤔

https://github.com/WordPress/gutenberg/assets/54422211/e6d47f39-1527-424c-a750-fe15be923ead

**Comment by talldan** [comment] 2024-02-19 03:21
> Maybe the block parser or something isn't accurate and we might need to look into the root cause.

Good point. I seem to recall there is some leniency in how closing tags are parsed. Perhaps it being the only block in the markup helps too.

**Comment by carolinan** [comment] 2024-06-29 02:13
What is the correct way of solving it?

This is still causing me a little bit of trouble because I use the fixtures as examples of the block markup in my block reference plugin, and I have visitors reporting that the code is wrong. I understand this is not what the fixture is intended for, but I would rather not have to implement a one-off solution for this single bug in one fixture.
Here is the example page where the code example is displayed https://fullsiteediting.com/blocks/column/

**Comment by talldan** [comment] 2024-07-01 08:30
This file can be updated, and then the related files re-generated. There's some instructions in the README.md within that folder explaining how those tests can be updated.

I'll throw together a quick PR that updates it.

**Closed as completed** 2024-07-01 09:54 UTC
Labels: [Type] Bug, [Status] In Progress, [Block] Columns
