### ISSUE TITLE
snackbar notice is partially hidden under sidebar

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#18787] opened 2019-11-27 16:26 UTC
**Describe the bug**
On post update the part of the snackbar that reads "post updated." is hidden beneath the sidebar.

**To reproduce**
1. Update a post.
2. look at the snackbar.

**Screenshots**
![Kapture 2019-11-27 at 11 01 28](https://user-images.githubusercontent.com/3585901/69740099-d50b8780-1106-11ea-8636-373169eed03e.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox

**Additional context**
- It appears that https://github.com/WordPress/gutenberg/pull/18683 may have surfaced some styles that were previously inactive?

The `fixed` position in the [/edit-post/layout CSS](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/layout/style.scss#L17)
```
.edit-post-layout .components-editor-notices__snackbar {
    position: fixed;
```
is overriding the `absolute` position in the [/snackbar component CSS](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/snackbar/style.scss#L62)
```
.components-snackbar-list {
    position: absolute;
```
- Is it necessary to even have snackbar styles outside of the snackbar component?

**Comment by youknowriad** [comment] 2019-11-27 20:10
I think this issue is a duplicate of another one I created but I though it was fixed :)

**Comment by bobbingwide** [comment] 2019-11-28 08:32
In my experience the snack bar is too far to the left.

**Closed** 2019-11-28 10:22 UTC
Labels: General Interface, [Status] In Progress, [Type] Bug
