### ISSUE TITLE
Multiple icons disappear from Social Icons Block when just removing one (WP Beta 3)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#20573] opened 2020-03-02 09:59 UTC
**Describe the bug**
As soon as you remove any icons from the Social Icons block, all the other icons disappear as well once the block is deselected.

As an example, I removed the WordPress icon, and all the icons disappeared. When I removed the Instagram Icon, all the icons except for the WordPress icon disappeared.

The icons only show up again after clicking on the block, which is kind of pointless. How am I supposed to know there's a block there, if the icons don't display?

Vid: https://share.getcloudapp.com/z8uXZPnr

**To reproduce**
1. Add Social Icons block
2. Remove WordPress icon from block
3. Click outside of block to deselect it
4. See all the remaining icons disappear

**Expected behavior**
The only icon that should disappear, is the one that you remove. The other icons should still be visible. If the icon isn't going to show on the front-end because it doen't have a URL, then it should dim, or be greyed out, not disappear altogether.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox 73.0.1
 - Version: WP 5.4-beta3-47379
 - Theme: TwentyNineteen

**Comment by youknowriad** [comment] 2020-03-02 10:04
The icons that don't have any assigned URL are removed when the block is unselected to reflect the frontend, select it back and they'll show up again. I believe this is how it's meant to work. cc @jasmussen

**Comment by maddisondesigns** [comment] 2020-03-02 10:10
That's a really bad UI. As I mentioned above, if I remove the WordPress icon (which for some reason seems to get an automatic url assigned to, even though none of the others do), then every single icon disappears when the block isn't selected.

If I save my page to go do something else, and then come back to it, how am I supposed to find the block if I can't see any icons?

The better option would be to simply dim them, or grey them out, if they don't have a URL, not make them disappear altogether.

**Comment by jasmussen** [comment] 2020-03-02 10:10
This is intentional insofar as it is an attempt to provide a setup state indicative of what the social links block is, that is different from a gray slab. I do agree that flow should be refined, as is discussed in #19020. We should consider closing this one in favor of that.

**Comment by maddisondesigns** [comment] 2020-03-02 10:14
I've never used the Coblocks Social Profiles block, but I can see from your gif in #19020 that it does exactly what I described above. It dims them out when they don't have a URL. It doesn't just make them disappear.

**Comment by maddisondesigns** [comment] 2020-03-02 10:17
Also, why is the WordPress icon added by default? The majority of users aren't going to want a WordPress icon. The Block is for social platforms, so the default should be Twitter, Facebook, Instagram, LinkedIn & YouTube. They're the most common ones used.

**Comment by youknowriad** [comment] 2020-03-02 10:35
I'm going to close this issue as a duplicate of #19020 let's continue discussing there.

**Closed by youknowriad** 2020-03-02 10:35 UTC
Labels: [Block] Social
