### ISSUE TITLE
Classic Text block fails to preview if ACF is installed

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#3512] opened 2017-11-16 07:04 UTC
Using a fresh install of WP 4.9 and Gutenberg 1.7.0 with the Advanced Custom Fields plugin activated (version 4.4.12), upon inserting a Classic Text block, the block cannot be used or edited:

> ![2017-11-16t14 55 54 0800](https://user-images.githubusercontent.com/227022/32877875-855e7802-cade-11e7-8ce0-97eaf2f55930.png)

The following errors (including more attempts to download non-existent TinyMCE plugins) appear in the console:

> ![2017-11-16t14 59 43 0800](https://user-images.githubusercontent.com/227022/32877943-daa09930-cade-11e7-9b26-a9315d3a00cd.png)

Deactivating the ACF plugin resolves this issue as well as the failed requests for TinyMCE plugins.

**Comment by EphoxJames** [comment] 2017-11-20 06:51
@ephox-mogran and I spent some time trying to figure out what is going wrong.

The error message is being caused by the theme failing to load. The theme and plugins are failing to load because TinyMCE is trying to get it from `wp-content/plugins/gutenberg/vendor` when it should be loading them from `wp-includes/js/tinymce`. This seems to be happening because the global `tinyMCE.baseURL` is being overwritten when gutenberg loads.

So I think the following is happening:

1. Wordpress TinyMCE is loaded with the base url `wp-includes/js/tinymce`
2. Gutenberg TinyMCE is loaded with the base url `wp-content/plugins/gutenberg/vendor` which overwrites the global `tinyMCE.baseURL`
3. Wordpress TinyMCE tries to load plugins (possibly ACF requests a TinyMCE instance?) and uses the global `tinyMCE.baseURL` which looks for them in `wp-content/plugins/gutenberg/vendor` and fails
4. The vendored plugin files load so the plugins are made available
5. Gutenberg editors load and since the vendored plugins register themselves it doesn't matter that the baseUrl is wrong because it never has to look for them.

**Comment by youknowriad** [comment] 2017-11-20 09:03
Is it time to rely on the same version for classic and gutenberg editor @iseulde ?

**Comment by nylen** [comment] 2017-11-21 08:04
> possibly ACF requests a TinyMCE instance?

Probably so, this type of issue is one reason why we initially chose to render metaboxes within `iframe`s.

Not saying that was the right solution, just providing context.

**Comment by youknowriad** [comment] 2018-05-21 15:21
Fixed by https://github.com/WordPress/gutenberg/pull/6848

**Closed by youknowriad** 2018-05-21 15:21 UTC
Labels: [Component] TinyMCE
