### ISSUE TITLE
Move the unwrap transform some container blocks have

### ISSUE THREAD

**Issue by dsas** [WordPress/gutenberg#45841] opened 2022-11-17 09:59 UTC
## What problem does this address?
Columns, quotes and groups all have an 'unwrap' transform which removes the block, replacing it with the contained content. Unwrap isn't really a transform in the sense that the other transforms are and is perhaps a bit unclear. Unwrap is closer to ungroup which lives in the ellipses menu.

See https://github.com/WordPress/gutenberg/pull/45666#issuecomment-1317675557 for initial discussion of this confusion

## What is your proposed solution?
Add "Ungroup" to every container ellipsis menu, in the same position as Ungroup (maybe call it Unwrap or otherwise for non-group blocks) — and consider giving it a shortcut such as ⌘⇧G

**Comment by talldan** [comment] 2023-04-11 07:16
It sounds like the issue is calling for changes in the UI, so I've changed the label to 'Needs Design Feedback'.

There doesn't seem to be anything challenging in the technical implementation, so removing 'Needs Technical Feedback'.

**Comment by jasmussen** [comment] 2023-05-05 06:47
I agree with this [quite a lot](https://github.com/WordPress/gutenberg/pull/50139#issuecomment-1534680784). Unwrap feels both like the wrong term, and its placement as a transform destination feels wrong. So I would echo this:

* Remove the "Unwrap" from the transform menu, rename the feature to "Ungroup". It can still unwrap a columns block or any other container with that term, since those are also just groups of content.
* Have generic shortcuts for both, ⌘G to convert it to Group, but ⌘⇧G to ungroup (e.g. also for a Columns block)

**Comment by richtabor** [comment] 2023-11-24 19:52
Upwrap has been removed; closing this.

**Closed as completed by richtabor** 2023-11-24 19:52 UTC
Labels: [Type] Enhancement, Needs Dev, [Block] Columns, [Block] Quote, [Block] Group
