### ISSUE TITLE
Query Loop block: navigating between pages of posts causes page reload

### ISSUE THREAD

**Issue by vncntdvrs** [WordPress/gutenberg#43664] opened 2022-08-27 09:04 UTC
### Description

Recently I ran into an issue using the query loop block halfway down on the front page of a website I was working on.

Whenever I clicked on the ‘next page’ button to show more blogposts results, the click would cause the page to jump to to top and I would have to scroll down to go back to the blog overview window.

I expected the click to show me more more results yet stay in the same place on the page. Is this a wrong assumption or is this an actual bug?

If it's not a bug then maybe an enhancement issue?

### Step-by-step reproduction instructions

Create a query loop on a page with some other content above.

set the numbers of posts to about 3

make sure you have 4 or more posts

Save the page and on the frontend click on "next page" to show more blogposts.

when clicked you'll see that the page jumps to the top 

in order to see the next posts in the query window you'll have to scroll down

### Environment info

Wordpress Gutenberg 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-09-09 00:54
I can replicate this with GB 14.0.2 and WP 6.0.2:

https://user-images.githubusercontent.com/26996883/189250154-0f202733-7c2f-4fa6-8850-450dfab37a16.mov

You can see it when flipping through the block museum: https://block-museum.com/museum/ Essentially, a page reload is happening! I agree that this would be great to improve. I'm not quite sure what's intended here vs what can be improved to have more of a dynamic response.

**Comment by luisherranz** [comment] 2022-09-09 15:25
It's not a bug, but the way the web works 🙂

Even sites made with JS frameworks that don't need to do a full page reload [scroll to the top by default](https://twentytwenty.frontity.org/). Not doing so feels weird, but I understand that your use case is different because there is content at the top, and users can lose their context.

I think the easiest solution for your use case would be to add an HTML anchor (id) to the Query Loop block and its pagination URLs (`/some-page/?query-12-page=2#my-query-block`) so that when the page reloads, it scrolls back to the block position. But it's something that would have to be added to the block's code.

**Comment by annezazu** [comment] 2022-09-09 15:26
Thanks @luisherranz for diving in! Going to close this out as expected.

**Closed as not planned by annezazu** 2022-09-09 15:26 UTC
Labels: [Type] Enhancement, [Block] Query Loop

**Comment by vncntdvrs** [comment] 2022-09-09 15:56
Thanks everybody for jumping in, I guess jumping to the top makes sense for blog-pages but maybe not so much for instances with content on top or instances that showcase multiple query loops. 

I have a feeling your suggested solution is a bit over my head. Would I need to do this for every results page? or could I add some code so that every "query loop next page click" stays in place for any next page query? Hope that makes sense.

I wonder.... would this be a handy feature request to add a "stay in place" button as an option?

**Comment by luisherranz** [comment] 2022-09-12 06:46
> would this be a handy feature request to add a "stay in place" button as an option?

If you mean my anchor (id) suggestion, sure 🙂

If you mean avoiding a page reload, there are already experiments to implement client-side navigation, like [this](https://github.com/WordPress/gutenberg/pull/38713) or [this](https://github.com/WordPress/gutenberg/pull/44034), but they are very preliminary, and they would require more challenges than just figuring out how to replace the HTML, like:

- Make sure all the styles of the new blocks are loaded.
- Make sure the JavaScript of the interactive blocks is loaded and figure out a way to trigger it (people usually do it with DOM-ready events, which are not present on client-side navigation).
- Figure out how to trigger analytics and other trackers that usually act on the initial page load.
