### ISSUE TITLE
Pages are missing from Parent Page dropdown

### ISSUE THREAD

**Issue by Razorrank** [WordPress/gutenberg#21563] opened 2020-04-13 18:42 UTC
**Describe the bug**
This website has 527 published pages. Only 447 pages are being listed in "Parent Page" dropdown.
Following return 100 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user`
Following return 100 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user&page=2`
Following return 100 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user&page=3`
Following return 100 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user&page=4`
Following return 100 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user&page=5`
Following return 26 pages:
`wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=111&parent_exclude%5B0%5D=111&orderby=menu_order&order=asc&context=edit&_locale=user&page=6`
100+100+100+100+100 + 26 = 526 pages are being returned using JSON API. But only 447 pages are being listed in parent page dropdown.

Currently running WordPress 5.3.2.

**Comment by Razorrank** [comment] 2020-04-15 19:52
Any updates on this?

**Comment by jasmussen** [comment] 2020-04-16 11:10
Hi @Razorrank, it's a little hard to reproduce this. 

For testing purposes, can you try installing the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin and seeing whether you're also seeing 447 pages there, or seeing indeed 526 pages?

**Comment by Razorrank** [comment] 2020-04-16 14:53
@jasmussen , I installed the Classic editor and edited the page. It shows 486 items in the parent dropdown list. When I use "Quick Edit" feature it shows 487 items in the parent dropdown.
Thank you

**Comment by jasmussen** [comment] 2020-04-17 06:31
Alright so it seems like the problem is not _block editor specific_. Which leaves two options, it's either intended, or it's an issue with the API. It's very probably the latter — but I wonder if there might be a reason for there being a reduced amount of parent page options. For example maybe you can't make a en existing parent page a child of another parent page? Not sure, but I'll flag this for some more feedback.

**Comment by Razorrank** [comment] 2020-04-17 14:30
@jasmussen ,

- Cloned the site to a staging site
- Deactivated all the plugins
- Switched to 2020 Wordpress theme
- Updated the Wordpress to the latest version
- Increased max_execution_time , max_input_time ,  max_input_vars , memory_limit , post_max_size , upload_max_filesize
- Looked at the error log in the root and /wp-admin/ for any potential relevant error messages but nothing is there!
- Problem persist. The specific page that is not appearing in the parent list is not parent of any other pages.
If you refer to my first comment, I mentioned that the API collectively returns all the pages(paginated). It is the page-editor/block-editor that is not using that data to populate the parent list. Not sure why you think the issue is from the API!?

Do I need to provide more technical feedback or someone from your team will provide feedback?

Thank you

**Comment by jasmussen** [comment] 2020-04-17 16:52
It looks as if you've been exceptionally thorough with feedback here, thank you! Hopefully someone with more in-depth knowledge of the API will be able to look based on the "needs technical feedback" tag I added soon!

**Comment by tellthemachines** [comment] 2020-11-29 22:24
Closing as this was fixed in #26397.

**Closed by tellthemachines** 2020-11-29 22:24 UTC
Labels: Needs Technical Feedback
