### ISSUE TITLE
Paste-to-Embed Not Working in 5.0-beta1

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11162] opened 2018-10-27 22:24 UTC
**Describe the bug**
I expect to paste an oembed friendly URL and have the embed automatically appear. This does not appear to be working.

**To Reproduce**
1. Create a post in Gutenberg.
2. Paste an oembed friendly URL. I tried https://twitter.com/MRWweb/status/1055941503766286336 and https://www.youtube.com/watch?v=zTD2DLTBiBs
3. URLs are not transformed into embeds

**Expected behavior**
Embedded tweet and YouTube video.

**Screenshots**
![two plain URLs in gutenberg editor that should be embeds](https://user-images.githubusercontent.com/1238696/47609875-57091880-d9fc-11e8-8c47-5ae66dbf4148.png)

**From the Console**

> Received plain text:
>  https://twitter.com/MRWweb/status/1055941503766286336
> editor.min.js:55:155302
> 
> Processed inline HTML:
>  https://twitter.com/MRWweb/status/1055941503766286336
> blocks.min.js:2:128757
> 
> Received HTML:
>  editor.min.js:55:155259
> 
> Received plain text:
>  https://www.youtube.com/watch?v=zTD2DLTBiBs
> editor.min.js:55:155302
> 
> Processed inline HTML:
>  https://www.youtube.com/watch?v=zTD2DLTBiBs
> blocks.min.js:2:128757
> 
> back tab addListener: restorebar
> content_script.js:128:4 

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 60
 - WordPress 5.0-beta1-43823, Twenty Nineteen, no plugins

**Comment by Smith-erin** [comment] 2018-10-28 19:16
I was not able to reproduce this error.

OS X 10.14
Chrome 69
WordPress 5.0-beta1-43832, Twenty Nineteen, no plugins

**Comment by earnjam** [comment] 2018-10-28 19:29
Thanks for reporting @mrwweb. 

This is actually the same way the classic editor worked. oEmbed URLs needed to be in their own paragraph in order to automatically be inserted, and did not work if you just used line breaks before them. 

Similarly, in Gutenberg, automatic embeds work when they are pasted into their own paragraph block, but when pasted into a paragraph block that contains other text, they will be inserted as a link instead of an embed.

**Closed by earnjam** 2018-10-28 19:29 UTC

**Comment by mrwweb** [comment] 2018-10-29 14:36
> oEmbed URLs needed to be in their own paragraph in order to automatically be inserted, and did not work if you just used line breaks before them.

I'm well aware of that.

That said, I couldn't reproduce this again either. I'm not sure what happened the first time (though even then, URLs were _definitely_ in a clean paragraph block).
