### ISSUE TITLE
FontSizePicker: Improve size/alignment of controls

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#23908] opened 2020-07-13 16:13 UTC
<img width="307" alt="Screen Shot 2020-07-13 at 12 09 03 PM" src="https://user-images.githubusercontent.com/2322354/87327440-1029c200-c502-11ea-8d31-6b7999b11e1e.png">

With the `FontSizePicker` that appears in blocks like **Paragraph**, the Reset button wraps below the other controls when a scrollbar appears in the sidebar.

**To reproduce**
* Add a paragraph block
* Expand Inspector controls for sidebar scrollbar to show
* Notice the Reset button under the Typography panel

**Expected behavior**
* For the controls to maintain alignment regardless of scrollbar

**Comment by ntsekouras** [comment] 2021-10-04 12:26
Is this still relevant? I couldn't reproduce it. Also noting that the control will soon be updated by: https://github.com/WordPress/gutenberg/issues/34345

**Comment by gwwar** [comment] 2021-10-04 17:24
I wasn't able to reproduce this in trunk for FF, Chrome or Safari. @ntsekouras how about we close this one for now?

<img width="278" alt="CleanShot 2021-10-04 at 10 23 34@2x" src="https://user-images.githubusercontent.com/1270189/135896203-1c385f7e-94d0-4827-9e87-1db6093a31db.png">

**Closed** 2021-10-04 17:30 UTC
Labels: [Package] Components, [Feature] Design Tools
