### ISSUE TITLE
Block Editor 's shadow DOM of edited page: <body> misses many classes upon which CSS selectors may depend: such as page-template-*, page-id-*, post-type-* , etc

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#51353] opened 2023-06-08 20:08 UTC
![WordPress Block Editor shadow DOM body misses many classes which may be used as legitimate CSS selectors](https://github.com/WordPress/gutenberg/assets/737143/db3c9468-f17f-41f8-9293-713b039db7a3)

## Problem

In the shadow DOM of the Block Editor the `<body>` element misses many classes which may be legitimately used as a CSS selector. Such as those which are specific for a content-type (post vs. page) or template or certain page-IDs.

## Proposed Fix / Improvement
Include the relevant classes like in the `<body>` of the Frontend output in the Block Editor shadow DOM too, except of course those which are Frontend runtime specific (such as Logged-In, or those coming from plugins and their dynamic runtime state).

## Reproduction

My CSS selector in my enqueued global.css file

                          .page-template-default section:nth-child(2n + 2) { background-color: var(--wp--preset--color--tertiary) !important; }

Which in the enqueued representation gets:

    .editor-styles-wrapper.page-template-default section:nth-child(2n + 2) { ... }

- ✅ In the Frontend this works:
   - On a page with the "Default" page template
   - Every second section (Group block with section as its html type) has a gray background color.

- ❌ In the Block Editor this has no effect.

After debugging I found out why:

- Output in Frontend:

  `<body class="page-template-default page page-id-1571 page-child parent-pageid-24 logged-in admin-bar no-customize-support wp-custom-logo wp-embed-responsive gspbody gspb-bodyfront mega-menu-max-mega-menu-1 mega-menu-max-mega-menu-2" style="position: relative;">`

- Shadow DOM in the Block Editor:

  `<body class="block-editor-iframe__body editor-styles-wrapper post-type-page admin-color-fresh wp-embed-responsive" tabindex="0" contenteditable="false">`

## Realization

A lot of classes are missing in the Block Editor environmnet, which should be there, because it's legit to use them as CSS selectors:

- Some classes are only mode/runtime relevant, and are ok to be left out in the body of the Block Editor Shadow DOM:

  - admin-bar
  - no-customize-support
  - wp-custom-logo
  - wp-embed-responsive
  - gspbody
  - gspb-bodyfront
  - mega-menu-max-mega-menu-1
  - mega-menu-max-mega-menu-2

- But it is very legit to have CSS styles specifically for:
  - page || post
  - page-template-*
  - page-id-*
  - page-child
  - logged-in
- These should be present in the Block Editor too!

## Environment

- WordPress 6.2
- Gutenberg 15.9.1
- Safari 16.5 on macOS 11.7.6 Big Sur

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by MaggieCabrera** [comment] 2023-07-19 09:44
I can confirm this, I was working on a theme that was relying on the .error-404 class to style that page and saw that the classes are missing in the editor. That leads to inconsistencies between editor and frontend for themes that rely on the classes.

**Comment by ellatrix** [comment] 2023-08-15 18:08
I think this is a duplicate of #17854?

**Comment by spencerfinnell** [comment] 2023-08-15 18:15
Related/duplicate of:

- https://github.com/WordPress/gutenberg/issues/13339 (closed improperly)
- https://github.com/WordPress/gutenberg/issues/26494
- https://github.com/WordPress/gutenberg/issues/10640
- https://github.com/WordPress/gutenberg/issues/17854

**Comment by annezazu** [comment] 2023-09-07 18:52
Let's close this out as it seems to be a duplicate of the above items. If that's incorrect, please comment back on here and I'll reopen!

**Closed as completed by annezazu** 2023-09-07 18:52 UTC
Labels: [Type] Enhancement, CSS Styling

**Comment by spencerfinnell** [comment] 2023-09-07 19:17
@annezazu can you please reopen https://github.com/WordPress/gutenberg/issues/13339 for visibility. The issue was closed without addressing the original report.

**Comment by annezazu** [comment] 2023-09-08 00:49
@spencerfinnell looking that over, I think the current issue reported there is covered by work around having style partials as mentioned here: https://github.com/WordPress/gutenberg/issues/39281 Does that match your understanding?

**Comment by spencerfinnell** [comment] 2023-09-08 01:28
@annezazu No, that still requires _an element/group/block_ to be inserted. #13339 refers to an additional class being applied to the editor's body based on the page template being applied -- not the content on the page.

**Comment by spencerfinnell** [comment] 2023-09-08 01:29
#13339 refers to the client-side implementation of https://developer.wordpress.org/reference/functions/body_class/ which does not exist as far as I am aware.
