### ISSUE TITLE
Widget Screen: Not able to save when using Nav vertical block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27171] opened 2020-11-21 14:56 UTC
**Describe the bug**
I added a Nav - vertical block and menu items.
Then when I clicked save it went into a never ending loop.

![Screen Shot 2020-11-21 at 15 42 34](https://user-images.githubusercontent.com/5323259/99879924-5578a180-2c10-11eb-823f-03e5258dde56.png)

**To reproduce**
1. Add nav - vertical block.
2. Add an existing menu.
3. Click Save.

**Expected behavior**
That I would be able to save.

**Screenshots**

When clicking Save this notification also showed up.
![Screen Shot 2020-11-21 at 15 38 45](https://user-images.githubusercontent.com/5323259/99879928-63c6bd80-2c10-11eb-94c7-7015a50a6166.png)

![Screen Shot 2020-11-21 at 15 51 30](https://user-images.githubusercontent.com/5323259/99880114-a6d56080-2c11-11eb-82df-55980fd08248.png)

Error code:
{"code":"widgets_cannot_access","message":"Sorry, you are not allowed to access widgets on this site.","data":{"status":401}}

![Screen Shot 2020-11-21 at 15 53 34](https://user-images.githubusercontent.com/5323259/99880125-c2406b80-2c11-11eb-8613-00c36851e5b3.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Gutenberg plugin 9.4.1
- Theme Twenty Twenty.
- All other plugins deactivated.

**Comment by lionzeye** [comment] 2021-01-11 10:19
This issue appears to be a duplicate of https://github.com/WordPress/gutenberg/issues/27173

**Comment by draganescu** [comment] 2021-01-14 10:30
Closing as duplicate of #27173

**Closed by draganescu** 2021-01-14 10:30 UTC
Labels: [Feature] Navigation Component, [Feature] Widgets Screen, [Type] Bug
