### ISSUE TITLE
Deleting the first list item in a list after a paragraph converts each list item into a paragraph

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#8803] opened 2018-08-10 02:18 UTC
## Describe the bug

Given a paragraph block followed by an unordered list block: if I delete the first list item from the list, I would expect one of three things:

1. (My favorite) The first bullet or placeholder disappears and my cursor is now in a new paragraph block.
2. The cursor goes to the end of the previous block. (Current classic editor)
3. The list is reduced by one item and the focus remains in the list.

In Gutenberg 3.5.0, when the first item is deleted, each of the remaining items turns into its own paragraph block.

## To Reproduce
1. Add a paragraph block as the first block
2. Add a list block as the second block
3. Add more than one list item
4. Focus on the first list item
5. Delete the first item using the delete key

## Expected behavior

In general, the remaining list items should continue to be list items.

### Other solutions:
I really like how smoothly Dropbox Paper handles this:

![drobox-paper-list-items](https://user-images.githubusercontent.com/286171/43935322-37c183b8-9c08-11e8-8b52-b8a364059e51.gif)

Google Docs does something similar to Paper, though drops the bullet and keeps the indent until you hit delete again.

The classic editor deletes the first item and moves the cursor to the end of the previous block.

## Screenshots

This is a screencap of the current behavior in Gutenberg:

![disappearing-list](https://user-images.githubusercontent.com/286171/43935236-d98d0fa6-9c07-11e8-854b-a2c9784ab305.gif)

## Desktop (please complete the following information):
 - OS: OSX
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by designsimply** [comment] 2018-08-21 00:36
Tested and confirmed using WordPress 4.9.8, Gutenberg 3.6.2, Firefox 61.0.2, and macOS 10.13.6. ([gif](https://user-images.githubusercontent.com/1119271/44373702-cff16e80-a4a7-11e8-9c72-e55b8039b235.gif))

**Comment by arunsathiya** [comment] 2018-10-20 12:19
Noting that I stumbled upon this issue and I am able to reproduce this as well on Gutenberg 4.0.0.

WordPress 4.9.8 and Gutenberg 4.0.0 with Firefox Quantum 62.0.3 (64-bit) on macOS 10.14 - Mac OS Mojave. [Video indicating this behaviour](https://cloudup.com/cM30iRK8mhs).

**Comment by davidjmachado** [comment] 2018-12-07 21:38
Noting that I am observing this same behavior with Gutenberg 4.6.1 on Chrome Version 70.0.3538.77 (Official Build) (64-bit) on macOS 10.14.

**Comment by lealife** [comment] 2018-12-19 04:38
me too.
Wordpress: 5.0.1
OS: OSX
Browser: Chrome (latest)

**Comment by iseulde** [comment] 2019-02-11 09:13
I agree that we should make this better. Your first option sound great. So the would mean prepending the list with a paragraph and the first item as content, and removing the item from the list. Ideally the selection goes at the start of the paragraph. Sound doable to me.

I'm marking this as an enhancement because the current behaviour is how it is supposed to work, but I agree that it should be improved.

**Closed** 2019-10-24 18:25 UTC
Labels: [Block] List, [Feature] Block Conversion, [Status] In Progress, [Type] Enhancement
