### ISSUE TITLE
Columns(beta) Does Not Align Properly On Frontend

### ISSUE THREAD

**Issue by Xarcell** [WordPress/gutenberg#7251] opened 2018-06-10 19:44 UTC
**Describe the bug**
Columns(beta) with image in one column, and two elements such as a subheading & paragraph in the other column, appears correctly in editor, but not on frontend. 

**To Reproduce**
1. Add columns(beta)
2. In one column add image.
3. In the other column add subheading.
4. In same column as subheading, add paragraph.

**Expected behavior**
Subheading and Paragraph should be aligned beside the image, not below it.

**Screenshots**
![screenshot 3](https://user-images.githubusercontent.com/6114450/41205588-3b11db94-6cc4-11e8-9a08-fe4088fec8ff.png)
![screenshot 5](https://user-images.githubusercontent.com/6114450/41205589-3f90c1bc-6cc4-11e8-9e45-8a611876f0ae.png)

**Desktop (please complete the following information):**
 - OS: Windos 10
 - Browser: Edge & Chrome

**Additional context**
Gutenberg Version: 3.0.1
Tested in latest versions of Wordpress Twenty-Seventeen Theme and Gutenberg Starter Theme.

**Comment by aduth** [comment] 2018-06-11 00:44
Thanks for the report. Closing this as a duplicate of #5351. There is in-progress effort to resolve this issue at #7234.

**Closed by aduth** 2018-06-11 00:44 UTC
