### ISSUE TITLE
UI for Inserter is confusing

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#8217] opened 2018-07-26 06:36 UTC
**Describe the bug**
Gutenberg 3.3
The (+) that appears when hovering a block will insert a block **before** the hovered block.  
The (+) that is on the left of a block will put a block **in** the block space.
The (+) that is on the top of the editor will add a block **after** the selected block.
If a block is selected, I can't insert a block before it.
I can only insert one block at a time (although hitting Enter several times will do it).

**Expected behavior**
The (+) should mean the same thing wherever it is used. Since it is being called the Inserter Tool, it should insert blocks **before** the current block. If it is not inserting (but just filling the space), it should use a different symbol.

**Comment by SuperGeniusZeb** [comment] 2018-07-27 18:02
Duplicate of #7271.

To quote myself from there:

<blockquote>
<p>Perhaps the insertion icon in placeholders should look different to indicate it is replacing the placeholder. Perhaps an arrow to the side of the plus to make it clear that the block is being inserted at that spot and to simultaneously differentiate it from the normal plus icon?</p>
<p>On a related note, right now the sibling inserter just works the same as pressing <kbd>Enter</kbd>, which I think is a mistake. You have to click twice to actually get to the menu to insert a specific block, and then of course you have to click again to actually insert the desired block so it takes a total of <strong>three clicks</strong> when it could just be two. It is also confusing to click a button that looks like it should act the same as the one in the toolbar, only for it to insert a placeholder and you have to click another identical icon to actually get to the inserter menu.</p>
<p><strong>Having the sibling inserter open the inserter menu directly just makes so much more sense, in my opinion. Can you think of a single downside to doing this?</strong> People just writing posts would not be affected since <kbd>Enter</kbd> would and should keep acting like it does now, and keyboard users would likely be using <kbd>Enter</kbd> and slash commands. Mouse and touch users would definitely benefit. It would also solve #7763 by allowing the sibling inserter to be used in nested contexts that do not allow Paragraph blocks.</p>
</blockquote>

**Comment by designsimply** [comment] 2018-07-27 23:45
Closing in favor of #7271.

I think the placement and context for the different inserters are designed to match up with writing flow as much as possible. Here is how I see each one working:

> The (+) that appears when hovering a block will insert a block before the hovered block.

If I click an inserter above a block, it's logical to me that is where the new block will appear. If I click an inserter between two blocks, it makes sense to me that is exactly where the new block will appear. Adding a final trailing inserter, as suggested in a comment on #7271, sounds like a nice addition to me.

> The (+) that is on the left of a block will put a block in the block space.

This happens for blocks that exist but do not have a block type assigned yet. If you start typing, the default block type will be used. Since the block already exists and has space, it makes sense to me that clicking the (+) icon directly to the left of that block assigns the block type within that same space.

> The (+) that is on the top of the editor will add a block after the selected block.

In a natural writing flow, it makes sense to me that if I click an inserter for the document as a whole (top toolbar) that it would appear just below where I am editing if something is selected or at the bottom of the post if nothing is selected.

> The (+) should mean the same thing wherever it is used. Since it is being called the Inserter Tool, it should insert blocks before the current block.

I think it's hard to assess this issue without being opinionated and that it's possible feedback will be split (i.e. there is no absolute solution that will please everyone). Let's continue the conversation in #7271 and please note that this issue is already cross-referenced there.

**Closed by designsimply** 2018-07-27 23:45 UTC
Labels: [Type] Question
