### ISSUE TITLE
LaTeX code makes HTML block fail

### ISSUE THREAD

**Issue by aurelienpierre** [WordPress/gutenberg#29855] opened 2021-03-13 23:39 UTC
## Description
Input `$\LaTeX$` in the HTML block returns an error. Roughly translated from French, it says "Post update has failed, the response is not a valid JSON response".

## Step-by-step reproduction instructions
1. create an HTML block,
2. input `$\LaTeX$`

## Expected behaviour
Special characters should be escaped and the block saved.

## Actual behaviour
The change is not saved. TinyMCE works flawlessly for the same code.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: Not installed & Installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Fedora 33
- Browser:  Firefox 85.0.1

**Comment by talldan** [comment] 2021-03-15 03:56
I couldn't reproduce an issue. I didn't see any error messages and the post saved without issue. This is what I see when I view the post content:
<img width="104" alt="Screenshot 2021-03-15 at 11 55 34 am" src="https://user-images.githubusercontent.com/677833/111101701-6b2a2200-8585-11eb-8e70-f543a8f9df7a.png">

Not sure whether escaping could be theme dependent, this was tested with Twenty Twenty One.

I don't know much about LaTeX, or how this is intended to work, so happy for others to test and share info.

**Comment by cngodles** [comment] 2021-03-19 20:46
Agreed with @talldan 

I am not using a default theme, and my experience is the same as his. The post saves correctly.

## HTML Box:
![image](https://user-images.githubusercontent.com/5685764/111840156-58d81d00-88d2-11eb-8ee1-0c834869e4ba.png)

## Output:
![image](https://user-images.githubusercontent.com/5685764/111840173-5e356780-88d2-11eb-8643-5b93fe2de7aa.png)

## String sent via post to WordPress backend

`<!-- wp:html -->↵$\LaTeX$↵<!-- /wp:html -->`

**Comment by dev-sabbir** [comment] 2021-03-22 17:45
I couldn't reproduce this issue either. The post saved and there was no error.

### **HTML Box:**
![image](https://user-images.githubusercontent.com/5733224/112034254-78887300-8b68-11eb-96d8-cc7c58fcb7ed.png)

### **Output:**
![image](https://user-images.githubusercontent.com/5733224/112034337-91912400-8b68-11eb-81cf-48a282939981.png)

I am using the default theme twenty twenty one.

**Comment by talldan** [comment] 2021-03-23 00:10
Thanks for testing, closing the issue.

**Closed by talldan** 2021-03-23 00:10 UTC
Labels: [Block] HTML, [Status] Not Applicable

**Comment by aurelienpierre** [comment] 2021-03-24 15:52
I don't reproduce anymore, in the same conditions. It's weird.

**Comment by aurelienpierre** [comment] 2021-03-24 18:25
Actually, it's back. The tricky thing it doesn't appear straight away, you need a couple of revisions for the post for it to popup. Then, F5 on the post admin fixes it for the next couple of minutes until it comes back again.

I can't determine a minimal reproducer for it, but LaTeX equations and raw HTML code seem to make it appear quite reliably. It happens also in plain HTML editor, not just HTML block.
