### ISSUE TITLE
Huge space under small featured image

### ISSUE THREAD

**Issue by iamchetanp** [WordPress/gutenberg#11004] opened 2018-10-24 12:24 UTC
**Describe the bug**
When I am adding small featured image, it is showing huge white space below it. I have tried 150px X 150px image. It is due to 100% padding.

**Expected behavior**
There should be no white space below it.

**Screenshots**
![Small Featured Image](https://i.snag.gy/EA9dlq.jpg)

**Comment by salcode** [comment] 2018-10-28 18:50
**Reproduced**. I am able to recreate this with core `5.0-beta1-43832`. For reference, here are comparison screenshot.

## Classic Editor

running the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/)

`100px x 100px` featured image

<img width="293" alt="screen shot 2018-10-28 at 14 43 18" src="https://user-images.githubusercontent.com/5194588/47620404-196dc380-dac0-11e8-857a-5445ff253856.png">

## Gutenberg

`100px x 100px` featured image

<img width="273" alt="screen shot 2018-10-28 at 14 44 01" src="https://user-images.githubusercontent.com/5194588/47620406-1ecb0e00-dac0-11e8-8353-c00471d1479f.png">

**Comment by danielpost** [comment] 2018-10-28 21:00
This is happening because the full width responsive wrapper around the picture always matches the aspect ratio of the picture itself. The problem gets amplified when using a small but tall image (eg 100px x 600px).

What is the reasoning behind using this wrapper as opposed to doing it the way the Classic Editor handles small thumbnails?

**Comment by jorgefilipecosta** [comment] 2019-06-06 11:09
Hi all, thank you for reporting and testing this issue. It looks like in the last version of Gutenberg the issue is not happening anymore, as we don't have a space even if a 100x100 image is added, although the image is stretched and I'm not sure if this is the correct behavior either. I'm closing the issue as the original space problem seems solved if the problem is still happening in your tests feel free to re-open the issue and we will look further.

**Closed by jorgefilipecosta** 2019-06-06 11:09 UTC
Labels: [Component] Post Settings, [Type] Bug
