### ISSUE TITLE
When a default value is an array of objects, field values change across multiple blocks.

### ISSUE THREAD

**Issue by AdamWills** [WordPress/gutenberg#41565] opened 2022-06-06 12:18 UTC
### Description

When the default value of a block is set as an array of objects, field values change across multiple blocks.

My expectations would get that value updates are isolated to the block where the changes are actually made.

### Step-by-step reproduction instructions

1. Clone https://github.com/AdamWills/wp-blocks-default-array-issue (a basic reproduce case)
2. Enable the plugin
3. Create a new page
4. Add the "To Do" block to the page
5. Add a second "To Do" block to the page
6. Change one of the items in the second block.

Expected:
The first block is unaffected

Actual:
The values in the first block are changed to match the second block.

### Environment info

- WordPress 6.0
- Gutenberg 13.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-07-25 09:36
I could produce the issue with the provided sample plugin.

**Comment by t-hamano** [comment] 2022-08-06 06:24
I took a look at your code and I think these lines are the problem:

https://github.com/AdamWills/wp-blocks-default-array-issue/blob/21471f6d95b660b19c02c5449cbf315ddb04ceb0/src/edit.js#L45-L47

Since copying by spread syntax is **shallow copy**, the objects in the array will refer to the original variables.

Therefore, `props.attributes.items[index].text` of the `Edit` component is rewritten at the same time, causing unexpected behavior in the following code:

```javascript
const newItems = [...items];
newItems[ index ].text = newValue;
```

By specifying a new object in the array as shown below, it is detached from the source of the copy and should work correctly:

```javascript
const newItems = [...items];
newItems[ index ] = {
	...items[index],
	text: newValue,
}
```

**Comment by t-hamano** [comment] 2022-08-06 06:25
@AdamWills 

I would like to close this issue, but if there are any misunderstandings or clarifications, please don't mind reopening it 👍

**Closed as completed by t-hamano** 2022-08-06 06:25 UTC
Labels: [Type] Bug, [Feature] Block API
