### ISSUE TITLE
Gallery Image Selector doesn't work

### ISSUE THREAD

**Issue by ShareTextures** [WordPress/gutenberg#19556] opened 2020-01-10 11:44 UTC
Gallery Image Selector can't be seeing at block options. 
https://github.com/wordpress/gutenberg/pull/18581

Also, how can I change all gallery images as the thumbnail for old posts?

**Comment by mmtr** [comment] 2020-01-13 12:52
Moving the discussion from https://github.com/WordPress/gutenberg/pull/18581 here:

> It's interesting I tried it another computer and it's show it now. Cookies possible :) Thanks
> 
> Edit: It setup as a thumbnail but at the single-post page, it still serving image full size instead of thumbnail. [Link](https://www.sharetextures.com/patron-only/grey-fantasy-polished-marble/)

I'm afraid I'm missing some info. It seems the post you shared has not been generated with the block editor (I don't find in the HTML source any block syntax), and in that case it's normal the gallery block image size option doesn't take effect since there is no gallery blocks at all rendered in the post.

> Also, how can I change all gallery images as the thumbnail for old posts?

Currently there is no way of doing that in bulk. You'd need to change then manually one by one.

**Comment by ShareTextures** [comment] 2020-01-13 13:52
> Moving the discussion from #18581 here:
> 
> > It's interesting I tried it another computer and it's show it now. Cookies possible :) Thanks
> > Edit: It setup as a thumbnail but at the single-post page, it still serving image full size instead of thumbnail. [Link](https://www.sharetextures.com/patron-only/grey-fantasy-polished-marble/)
> 
> I'm afraid I'm missing some info. It seems the post you shared has not been generated with the block editor (I don't find in the HTML source any block syntax), and in that case it's normal the gallery block image size option doesn't take effect since there is no gallery blocks at all rendered in the post.
> 
> > Also, how can I change all gallery images as the thumbnail for old posts?
> 
> Currently there is no way of doing that in bulk. You'd need to change then manually one by one.

Lets check this link together if: [Free Parquet Textures ](https://www.sharetextures.com/textures/wood/classic-parquet-6/)

<figure class="wp-block-gallery columns-4 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item">

I want to load thumbnail size(125x125) of images on the single post page, when I click them(using lightbox) I want to open full size (512x512).

Is it possible?

**Comment by idea--list** [comment] 2020-01-14 12:16
Here is what i find:
After instaling GB 7.2 i get the option to chose the "Image Size" in case i insert a core "gallery" block from from scratch.

However i also have other plugins featuring gallery blocks:
with Kadence Blocks activated i can convert the core gallery block to an "advanced gallery" block of Kadence blocks and keep the image size i previously set up in core gallery block. I can also convert back to the core gallery block.

However i try the same with Meow gallery's of Block Gallery's gallery/carousel blocks then if a can convert back to the core gallery block, the image size option is simply not showing up anymore. To get that option again, i have to remove the gallery block and insert it from scratch.


IMHO this is unexpected and the core gallery block should add that property (defaulting to large) if it is missing to avoid this bug.

**Comment by enriquesanchez** [comment] 2020-03-16 22:23
I'm closing this one since it seems there's no clear definition of what the problem is. In addition, it is expected for Core blocks to not have all the functionality that 3rd party blocks do.

Please feel free to reopen and provide more information if necessary.

**Closed by enriquesanchez** 2020-03-16 22:23 UTC
Labels: [Status] Needs More Info, [Type] Help Request
