### ISSUE TITLE
Insert link: unify link interfaces

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6392] opened 2018-04-24 17:42 UTC
Right now we have a little variation on styling for links, most have been update to the current one but lets fix those that haven't.

Here is the latest interface:

![link-paragraph](https://user-images.githubusercontent.com/253067/39204177-fe20b09c-47ee-11e8-9e4d-4cb866b87a9c.png)

This however on images right now isn't updated here:

![link-image](https://user-images.githubusercontent.com/253067/39204197-0c86d18e-47ef-11e8-9fc4-990aad110e95.png)

You can see it even more, when you have both link interfaces open:

![link-images-both](https://user-images.githubusercontent.com/253067/39204201-148b6980-47ef-11e8-959b-f077de89a6e9.png)

For buttons you get the following:

![link-button](https://user-images.githubusercontent.com/253067/39204245-2cf02916-47ef-11e8-9e12-973217c5e627.png)

I would suggest we should unify the links and have everything use the same like we do in these examples:

![link-coverimage](https://user-images.githubusercontent.com/253067/39204261-3adb3944-47ef-11e8-9403-12487c2dbef2.png)

![link-quote](https://user-images.githubusercontent.com/253067/39204270-42c82d10-47ef-11e8-9f17-2c457616eec0.png)

**Comment by mtias** [comment] 2018-07-19 12:00
@karmatosed what's the status of this one? Maybe we need specific issues for any that are wrong.

**Comment by designsimply** [comment] 2018-09-07 01:12
@karmatosed would you like me to split this issue out into more specific ones or would it be better to wait for a unified design to be posted here first?

Regarding design, would it be possible to note the post type (e.g. Page, CPT name, or the date for posts) on the right for suggested links or should that be filed as a separate issue? Note: asking because it was requested in #9660.

![screen shot 2017-07-29 at 17 39 06](https://user-images.githubusercontent.com/1682452/28746065-5593b8f8-7485-11e7-9cc7-ab9ce4993130.png)
<sup>Example screenshot from #2084 showing how post types are listed in link suggestions in the classic editor.</sup>

**Comment by mtias** [comment] 2018-10-12 16:55
@karmatosed what is the status of this?

**Comment by karmatosed** [comment] 2018-10-15 09:34
We need to fix for button only:


![button](https://user-images.githubusercontent.com/253067/46942776-ef4ee700-d065-11e8-868d-d03517582ca5.png)

**Comment by afercia** [comment] 2018-10-20 10:17
@designsimply when you have a chance 🙂 has the post type / date thing been split in a separate issue? Couldn't find one. Thanks! /Cc @azaozz

**Comment by mtias** [comment] 2018-11-01 19:14
> Ideally we would have the link design to be the same as the other instances:

The button shows the url input on selection of the block, should it still use a dropdown menu in that case?

**Comment by karmatosed** [comment] 2018-11-02 09:44
> The button shows the url input on selection of the block, should it still use a dropdown menu in that case?

My feelings are yes because that's our interface for linking. It isn't perfect but right now this is the only link adding that doesn't have this. For example even without text, you get the following for cover image:

![2018-11-02 at 09 42](https://user-images.githubusercontent.com/253067/47907797-d2971980-de83-11e8-8b1f-2869b48591ae.png)

**Comment by mtias** [comment] 2018-11-12 20:34
The biggest outlier seems to be the Button block. Punting this from 5.0 as improvements there can be done later.

**Comment by designsimply** [comment] 2019-02-01 19:01
I am closing this issue and deferring to #8000 as the last issue remaining for the request to unify the link interfaces for the paragraph, button, image caption, cover image, and quote blocks. See audit details below.

/hat tip @nfmohit-wpmudev and @kadencethemes for proposing solutions to #8000 in #10128 and #12738 respectively.

I audited link inserters for the following blocks:

1. Paragraph
1. Button
1. Image (done in sidebar not popover)
1. Image caption
1. Cover image
1. Quote

And found the following:

1. Image block currently does not have a Urlpopover link inserter, image links are set in the sidebar and this looks to be by design ([screenshot](https://user-images.githubusercontent.com/1119271/52139188-9f902d80-260c-11e9-917b-1e0b4a52c3a1.png)).
1. Button block link inserter does not match the rest ([screenshot](https://user-images.githubusercontent.com/1119271/52141710-d453b300-2613-11e9-8312-d7b04fb648e4.png)).

![screen shot 2019-02-01 at 11 37 27 am](https://user-images.githubusercontent.com/1119271/52142404-cdc63b00-2615-11e9-8295-b4ec5dd57f20.png)

I also moved the request to include different post types and the dates of posts to the suggested links to #13641. cc @afercia

**Closed by designsimply** 2019-02-01 19:01 UTC
Labels: Good First Issue, UI Components, [Type] Enhancement
