### ISSUE TITLE
Copying and pasting lists adds empty list items

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#6621] opened 2018-05-07 15:44 UTC
## Issue Overview
I have been copying text from Word to Gutenberg 2.8.

After copying and pasting the content in a list block it looks like this:
![image](https://user-images.githubusercontent.com/1785641/39710680-c7c07602-521d-11e8-92b1-ec3c84a333f2.png)

In the code editor the content looks like follows.
```
<!-- wp:list -->
<ul> 	<li>Bauherrschaft: privat Gebäudeart: Ersatzneubau in Holz- </li> 	<li>Elementbauweise Realisierung: 2006 - 2007</li> 	<li> 		Verantwortliche Mitarbeit: Marcel, Enis<br/> </li> 	<li>Fotografen: Heinrich + Roland, Zürich 	</li> 	<li>Leistungsumfang Kosten- und Terminplanung</li> </ul>
<!-- /wp:list -->
```

Even after removing the empty spaces in the list, they return once I saved the post.

## Expected Behavior
I would expect that I could copy and paste text without it adding the extra spaces and `<br>` tags. 

## Possible Solution
Strip the spaces within the `<li>` tags.

**Comment by tofumatt** [comment] 2018-05-31 11:57
Just to make sure we can reproduce this bug, which version of Word were you using? Operating system info would be great too 😄

**Comment by designsimply** [comment] 2018-10-16 18:01
Thank you for reporting this and for testing Gutenberg! I am closing this issue as a duplicate of #5727 and this issue will be linked there for reference.

**Closed by designsimply** 2018-10-16 18:01 UTC
Labels: [Block] List, [Component] Raw Handling, [Status] Duplicate, [Type] Bug
