### ISSUE TITLE
Verse: Unable to exit via enter

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#52773] opened 2023-07-19 18:17 UTC
Initially noted here https://github.com/WordPress/gutenberg/discussions/50129#discussioncomment-6489248. When trying to exit the Verse block, the only way is to use the option to insert after/before or to use the Inserter to insert a new block. This is replicated using 6.3 RC1:

https://github.com/WordPress/gutenberg/assets/26996883/eafef770-187d-4baf-8df5-6c8200b3a050

To address this, solutions have been offered https://github.com/WordPress/gutenberg/pull/52783#discussion_r1273380089 and https://github.com/WordPress/gutenberg/pull/52783#issuecomment-1645277213. TLDR: a single return keeps you in the selected block, and a subsequent return exits it. This matches behavior with the List block.

**Comment by Mamaduka** [comment] 2023-07-25 10:41
FYI, it was decided to revert the changes and mark this as `wontfix`. See #52783 and #52928.

**Comment by hanneslsm** [comment] 2023-07-25 11:26
Linking the comments https://github.com/WordPress/gutenberg/pull/52783#discussion_r1273380089 and https://github.com/WordPress/gutenberg/pull/52783#issuecomment-1645277213

The verse block should have the same exit behavior as the list block.

**Comment by Mamaduka** [comment] 2023-07-25 11:30
Re-opening the issue.

@annezazu, do you mind updating the description to reflect the suggested solution(s)?

**Comment by annezazu** [comment] 2023-07-25 16:52
Done.

**Comment by ellatrix** [comment] 2023-08-03 15:27
I've been looking into this issue and tried adding a new RichText prop `onSplitBr`, which would split when pressing ENTER on a line break. However, I'm not convinced that we should do this. It's super confusing when you have an empty line in a verse, press Enter, and it suddenly splits in two. And what if you want more than one line between text? Imo, this block works as intended.

Verse is pretty close to how the Preformatted and Code blocks work. Enter creates a soft line break and you can add as many as you like. I also wouldn't expect two Enter pressed to exit a Code block. If exiting is difficult, it means there's a larger problem for all blocks.

**Comment by annezazu** [comment] 2023-08-03 16:46
@WordPress/gutenberg-design keen to get designer thoughts here. In my mind, this makes it incredibly hard to get out of blocks currently (another example https://github.com/WordPress/gutenberg/issues/52774 ) and perhaps a wider solution needs to be considered.

**Comment by hanneslsm** [comment] 2023-08-03 16:47
> It's super confusing when you have an empty line in a verse, press Enter, and it suddenly splits in two

I didn't get this. Splitting into two verse blocks? I'd expect to be in paragraph block then again.

> And what if you want more than one line between text?

You also cannot do this at the moment with paragraphs because empty paragraphs get ignored. 

> Verse is pretty close to how the Preformatted and Code blocks work. Enter creates a soft line break and you can add as many as you like. I also wouldn't expect two Enter pressed to exit a Code block.

Good point. I also just looked into it and the root of the problem are the visuals.
The verse block _looks_ like a paragraph block but it _behaves_ like a Code block.
I am really not a big fan of opinionated designs for blocks, but here it might make sense. Background, a border, font-color, font-size, an icon in the background…? cc @WordPress/gutenberg-design

**Comment by hanneslsm** [comment] 2023-08-03 16:56
> @WordPress/gutenberg-design keen to get designer thoughts here. In my mind, this makes it incredibly hard to get out of blocks currently (another example https://github.com/WordPress/gutenberg/issues/52774 ) and perhaps a wider solution needs to be considered.

You got me by a minute :) 
The column block has the same issue. But since we cannot also change the background or anything else in the column block, it wouldn't make sense for verse. My ideas from the previous post are obsolete.

There must be another way to indicate that the user is "locked" into a block and cannot exit via enter.

How about letting a border bottom appear when pressing enter? 
I wish I knew javascript to do an interactive prototype to see if it works. Here is a static image, hope it conveys the idea:
<img width="1099" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/24d8b3e9-9b95-4f1b-b34c-9d5bb0e8bd76">

**Comment by jasmussen** [comment] 2023-08-04 07:39
My instinct here is to leverage a similar behavior as the List block. That is, double enter exits it, but the full behavior of backspace restoring the last list item seems important:

![List](https://github.com/WordPress/gutenberg/assets/1204802/c8f8cc55-3808-4345-a302-352e49b1c626)

That is, two enters _does_ escape this verse:

![verse](https://github.com/WordPress/gutenberg/assets/1204802/c025bda8-32e8-4b54-bb50-b9ff9ac50306)

However, the precise flow would likely be this:

* Verse line 1, type something, press enter
* Verse line 2, don't type anything, press enter
* _You escape the verse_ but are still on _line 2_, now it's just a paragraph
* Press backspace, you're back in the verse, but on _line 2_

Make sense?

**Comment by ellatrix** [comment] 2023-08-04 09:07
It sounds to me like you only want Enter to create a paragraph when at a line break at the end of a verse, and not also in the middle of a verse, which is different from list, which also splits in the middle.

In that case, I think we should slightly modify `onSplitAtEnd`, to only split on a newline. That will change the behaviour for captions too, but that's fine, It's better to be consistent.

My only worry is that you can no longer insert two line breaks to have a blank line between texts, which is common is verses, and common in the Preformatted and Code blocks too.

So maybe we should only split when there are TWO previous line breaks. In that case we'll need a separate `onSplitAtEnd`. I will make a PR like that so you can test it.

**Comment by ellatrix** [comment] 2023-08-04 09:11
In other words: it should be triple Enter that exits the block.

**Comment by jasmussen** [comment] 2023-08-04 09:20
Worth a try, especially if two or three can be tweaked in the PR somewhat easily?

**Comment by ellatrix** [comment] 2023-08-04 09:30
* https://github.com/WordPress/gutenberg/pull/53332

ready for testing

**Closed as completed** 2023-09-14 12:25 UTC
Labels: [Type] Bug, [Feature] Writing Flow, [Block] Verse
