### ISSUE TITLE
Edit image settings when in a gallery block

### ISSUE THREAD

**Issue by STHLMWebDesign** [WordPress/gutenberg#12351] opened 2018-11-27 10:10 UTC
Right now if you create a gallery block there is no way to edit the image settings even when you highlight and select one image inside the gallery block. 

This is incredibly annoying if you want to switch image size. You basically are forced to covert the gallery block into blocks of single images, make your changes to the image settings, and then recombine them in a gallery block. That or flip into the code view.

**Comment by swissspidy** [comment] 2018-11-27 13:31
So you want to change the image size for a single image inside the gallery?

I don't think that is or should be possible. Galleries are meant to show all images in the same size.

**Comment by designsimply** [comment] 2018-11-27 19:35
I think they mean they'd like the option to change the image size for all gallery images at once, similar to how the gallery works in the classic editor (I think the note about selecting one image was just to show they thought they would be able to access the image size settings that way but weren't able to).

Adding some screenshots for comparison:

When creating or editing a gallery in the classic editor, I see "Gallery Settings" options for: Link To, Columns, Random Order, Size:

<img width="1280" alt="screen shot 2018-11-27 at 12 26 53 pm" src="https://user-images.githubusercontent.com/1119271/49106488-8cde2e80-f240-11e8-9bd8-27bc3b92683e.png">
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post-new.php using WordPress 4.9.8 (no Gutenberg) using Firefox 63.0.3 on macOS 10.13.6.</sup>

In Gutenberg, I don't see any options for "Gallery Settings" such as image size: 

<img width="1280" alt="screen shot 2018-11-27 at 12 27 59 pm" src="https://user-images.githubusercontent.com/1119271/49106487-8cde2e80-f240-11e8-8a94-5ecbb87d2018.png">
<sup>Seen at http://localhost:8888/wp-admin/post.php?post=43&action=edit running WordPress 4.9.8 and Gutenberg `ef596ca85` (>4.5.1) using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment] 2018-11-27 19:41
Related: #7504 discusses similar image details settings for the image block.

**Comment by noisysocks** [comment] 2020-04-23 03:57
Closing this as a duplicate of https://github.com/WordPress/gutenberg/issues/11436 as the desired fix is to achieve some degree of parity between the Image and Gallery settings.

**Closed by noisysocks** 2020-04-23 03:57 UTC
Labels: [Block] Gallery, [Type] Enhancement
