### ISSUE TITLE
When selecting an existing "Group" block a paragraph block gets automatically inserted.

### ISSUE THREAD

**Issue by zkingdesign** [WordPress/gutenberg#21251] opened 2020-03-30 09:20 UTC
**Describe the bug**
The issue is that when I select a group block using the navigation a paragraph block gets added automatically into that group block. I don't think this is ok.

**To reproduce**
Loom screencast: https://www.loom.com/share/f3ae52ed04584fa3a437be82dfea9172

**Expected behavior**
When selecting a `Group` block a paragraph item shouldn't be automatically inserted.

**Desktop (please complete the following information):**
 - MacOs 10.15.4
 - Chrome [e.g. chrome, safari]
 - Version 80.0.3987.149

**Comment by talldan** [comment] 2020-03-31 04:17
@zkingdesign I wasn't able to reproduce this issue. Are there any plugins you have active that might be affecting the behavior of the group block?

**Comment by zkingdesign** [comment] 2020-03-31 04:34
@talldan just tried with a fresh wordpress install, and with only Gutenberg 7.8.1 activated and it does the same thing. In gutenberg 7.6 this issue didn't exist.

**Comment by talldan** [comment] 2020-03-31 07:19
Ah, I can reproduce it now! Looks like I closed this prematurely. Thanks for reporting.

**Closed** 2020-04-01 12:54 UTC
Labels: [Block] Group, [Status] In Progress, [Type] Bug
