### ISSUE TITLE
Reusable Blocks: An infinite loop when nesting same block

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#26542] opened 2020-10-28 15:10 UTC
**Describe the bug**
When editing a certain reusable block, it is possible to insert the same block inside, creating an infinite loop that will completely freeze the page.

**To reproduce**

1. Create a reusable block and save it
2. Open that reusable block for editing
3. Open inserter and add the same reusable block that you're currently editing
4. See the block content being repeatedly added in an endless loop
5. Open your browser's task manager to terminate the page

**Expected behavior**
Either it's possible to nest like that without the infinite loop or not possible at all.

**Screenshots**
![infinite loop](https://user-images.githubusercontent.com/1451471/97455157-d4432d00-1937-11eb-9011-bbe6d037ba56.gif)

**Editor version:**
- WordPress v5.5
- Gutenberg v9.2.2

**Desktop:**
 - OSX
 - Chrome

**Comment by talldan** [comment] 2020-10-29 06:08
Closing as a duplicate of #18704

**Closed by talldan** 2020-10-29 06:08 UTC
Labels: [Type] Bug
