### ISSUE TITLE
Can't open Gutenberg after edit posts with classical editor

### ISSUE THREAD

**Issue by StudyingFather** [WordPress/gutenberg#13042] opened 2018-12-20 14:28 UTC
**Describe the bug**
After edit a post by classical editor which was edited by Gutenberg before, I can't open Gutenberg to edit any posts.

But there is no error while editing a post by classical editor.

**To Reproduce**
1. Use classical editor to edit a post edited by Gutenberg before.
2. Enable Gutenberg editor.
3. Edit any posts by Gutenberg(including posts edited by Gutenberg before).
4. An 504 error occured.

**Expected behavior**
Gutenberg was opened as usual.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by StudyingFather** [comment] 2018-12-20 14:38
**Additional context**

* Gutenberg 4.7.1
* WordPress 5.0.1
* classical editor enabled

**Comment by swissspidy** [comment] 2018-12-20 14:55
Does the Gutenberg editor work again after disabling the Classic Editor plugin?

**Comment by StudyingFather** [comment] 2018-12-20 15:16
> Does the Gutenberg editor work again after disabling the Classic Editor plugin?

No. And reinstall Wordpress didn't help,either.

**Comment by StudyingFather** [comment] 2018-12-24 13:45
@swissspidy So is there any rapid way to fix the bug ?

**Comment by youknowriad** [comment] 2018-12-25 11:54
Could you provide the HTML content of the page you're trying to edit, this may help track the issue.

**Comment by StudyingFather** [comment] 2018-12-25 11:56
@youknowriad It seems that all pages can't edit with Gutenburg after the bug occured.

**Comment by youknowriad** [comment] 2018-12-25 11:58
Well, I personally can't reproduce with my pages after editing them in the classic editor. We might need more information to track and fix the bug.

**Comment by StudyingFather** [comment] 2018-12-25 12:00
@youknowriad So which pages should I provide? The pages that occured bugs?

**Comment by youknowriad** [comment] 2018-12-25 12:01
Any page that doesn't load for you with Gutenberg.

**Comment by StudyingFather** [comment] 2018-12-25 12:03
https://studyingfather.com/test-page

**Comment by youknowriad** [comment] 2018-12-25 12:04
This page is fairly simple and works properly for me. I wonder if you might have a plugin causing a conflict with Gutenberg or something?

**Comment by StudyingFather** [comment] 2018-12-25 12:05
I try to disable all plugin and edit pages with Gutenberg,but it can't work.

**Comment by youknowriad** [comment] 2018-12-25 12:08
I don't know, It could be a server configuration issue? 504 is a timeout issue. Your server might be calling an external URL and don't have access to it or something? Best way is to check the server logs to see if there's something suspicious there.

**Comment by youknowriad** [comment] 2019-10-03 11:07
Going to close the issue now as there's nothing actionable on the Gutenberg side. Let's reopen if we have ways to reproduce it.

**Closed by youknowriad** 2019-10-03 11:07 UTC
Labels: Needs Testing
