### ISSUE TITLE
unhandled exemption media.media_type/e.media_type

### ISSUE THREAD

**Issue by thesquaremedia** [WordPress/gutenberg#21741] opened 2020-04-20 22:45 UTC
We have a plugin that stops duplicate media files from being uploaded. it throws a file upload error. with in WP throws a WP_Error with a 500 status code. I am noticing though that it causing a JS error which maybe be causing the WP to not print the error UI on the block displaying the error. 

https://imgur.com/L0luzXu

hook into wp_handle_upload_prefilter and just pass an error to the upload. use the media and text block and upload an image. the error UI wont display and the media.media_type error will show. something like this

```
function custom_wp_handle_upload_prefilter( $file ) {
		$file['error'] = 'custom error message';
		return $file;
}
add_filter( 'wp_handle_upload_prefilter', 'custom_wp_handle_upload_prefilter' );
```

**Comment by talldan** [comment] 2020-04-21 04:14
@thesquaremedia I don't think this is enough information for a developer here to be able to look into this issue. Would you be able to provide some minimal steps to reproduce the issue?

**Comment by karmatosed** [comment] 2020-04-24 16:42
As there doesn't seem enough information to recreate right now, let's close this up for now. It can always reopen once more details are known.

**Comment by thesquaremedia** [comment] 2020-04-27 15:18
@talldan @karmatosed sorry been swamped. I would hook into `wp_handle_upload_prefilter` and just pass an error to the upload. use the media and text block and upload an image. the error UI wont display and the media.media_type error will show.

```function custom_wp_handle_upload_prefilter( $file ) {
		
		$file['error'] = 'custom error message';
	
		return $file;
	}
add_filter( 'wp_handle_upload_prefilter', 'custom_wp_handle_upload_prefilter' );```

**Comment by thesquaremedia** [comment] 2020-05-14 20:25
should I just create a new issue? with the steps to reproduce from the start? been about two weeks since I provided steps how to reproduce the problem.

**Comment by talldan** [comment] 2020-05-15 02:57
@thesquaremedia Thanks, yep, either a new issue or you can update the description of this one and I'll re-open it.

If you open a new issue, it'd be great if you could add comment to this issue with the issue number so that there's a trail for anyone reading.

**Comment by thesquaremedia** [comment] 2020-05-26 16:55
@talldan updated original comment/description.

**Comment by synthetiv** [comment] 2021-10-13 21:28
Just to chime in, I'm running into the same issue with errors added using the `wp_handle_upload_prefilter` hook not being handled well by Gutenberg. The exact JS errors I'm getting aren't identical, but that may be the result of browser differences or other changes in Gutenberg or WP core since this issue was opened.

**To recreate the issue:**

- Hook into `wp_handle_upload_prefilter` and add an `error` key to the `$file` array, as in @thesquaremedia's example above
- Create or edit a post
- Insert a Media & Text, Image, Cover, or Gallery block
- Click the Upload button in the block and select a file

**Expected outcome:**

An error message should appear containing the error message added by the hook, probably styled similarly to the error that's displayed when a user tries to upload a file of a forbidden MIME type: 
![Error message in Media & Text block](https://user-images.githubusercontent.com/752281/137208439-103e6140-4c55-4546-8fe7-b4496e28d344.png)

**Actual outcome:**

When the Gutenberg plugin is inactive, no error is displayed to the user, so the block looks as it would if the user had clicked Cancel in the browser's file upload dialog box; and two errors appear in the Firefox console: an HTTP 500 error for the upload (the full HTTP response contains the custom error message set by the hook, so this is appropriate) and an error that `media` is undefined in /wp-includes/js/dist/block-library.js line 17221.

Block after attempted upload:
![Media & Text block after attempted upload - Gutenberg inactive](https://user-images.githubusercontent.com/752281/137210943-58c95b32-b49e-45d4-8ac8-8c57216e5fe8.png)

HTTP 500 error:
![HTTP 500 error containing the error message](https://user-images.githubusercontent.com/752281/137211138-61fdae72-365c-4dd6-a714-900cbc30001d.png)

JS error:
![JS error - Gutenberg inactive](https://user-images.githubusercontent.com/752281/137211408-5701072b-a8db-4a7e-8076-8c8129c29031.png)

When Gutenberg 11.7.0 is active, the block is replaced with a loading spinner that never stops spinning, the same 500 error appears, and a different JS error appears (probably only different because the plugin loads minified JS).

Block after attempted upload:
![Media & Text block after attempted upload - Gutenberg active](https://user-images.githubusercontent.com/752281/137211846-a48be5ed-dd61-4ac4-a40e-ccadb8f81431.png)

JS error:
![JS error - Gutenberg active](https://user-images.githubusercontent.com/752281/137212014-e640e4d1-d44b-488e-818e-14a946b635ab.png)

**System info:**

Mac OS 11.6
Firefox 93.0
WordPress 5.8.1
PHP 7.4.24
`SCRIPT_DEBUG` on in wp-config.php

I've poked around a bit in the Gutenberg source and it certainly looks like the Media & Text block and similar blocks are designed to handle errors & notices – but for some reason, HTTP 500 errors are being ignored and in the case of the Media & Text block, `MediaContainer`'s `onSelectMedia` prop is being called even though there isn't a valid `media` object to pass to it.

Let me know if I can provide any other info.

**Comment by dhusakovic** [comment] 2022-01-31 04:28
Experiencing the same issue, with WP 5.8.3 and WP 5.9

It looks like any error triggered during the upload of an image within the image block, and returned in `WP_REST_Attachments_Controller` [here](https://github.com/WordPress/WordPress/blob/fe7d62fe138421c065dbb7044c6942d594d15cfd/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L1230), does not get reflected anywhere on the page, and the image upload is left in a loading state. 

As pointed out in previous comments and issue description, this can be seen by hooking into `wp_handle_upload_prefilter` to add an error, but it can also be reproduced by making the `uploads` dir unavailable, in which case we see the same behaviour, and the error response returned is along the lines of:
`{"code":"rest_upload_unknown_error","message":"Unable to create directory wp-content\/uploads\/2022\/01. Is its parent directory writable by the server?","data":{"status":500}}`

No JS errors observed.

**Closed** 2022-03-07 09:17 UTC
Labels: [Status] In Progress, [Feature] Extensibility, [Feature] Media, Needs Testing

**Comment by thesquaremedia** [comment] 2022-03-07 14:47
I see that the fix targets the media and text block specifically. so I just want to point out that this happened on all blocks with a media upload functionality. I guess initially I suspected this could be fix in a more universal location but if the fix needs to be targeted then it will need to be applied to all the blocks with a media upload.

**Comment by Mamaduka** [comment] 2022-03-07 14:53
Hi, @thesquaremedia

It needs to be updated block by a block basis. This one is targeting Media & Text as initially reported, but I am also working on the remaining media blocks.

**Comment by thesquaremedia** [comment] 2022-03-07 15:32
@Mamaduka alright cool awesome thanks for letting us know
