### ISSUE TITLE
Widget area does not work with Gutenberg and Storefront

### ISSUE THREAD

**Issue by davidvb67** [WordPress/gutenberg#27458] opened 2020-12-03 08:58 UTC
**Describe the bug**
When Gutenberg is activated the widget area in Storefront/Wordpress doesn't work anymore. 
I get to see a Gutenberg like lay-out for the widget area in admin, but when I add something to a widget area (footer, under header, sidebar ...) I can't update the page. 
So the widgets don't show. 

The widget section works well when Gutenberg is deactivated but then I can't add the Gutenberg blocks I made.

**Expected behavior**
I expected the Gutenberg blocks to be inserted in the widget area.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5.3.
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? 
"gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it?
9.5.0

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - Browser chrome
 - Version 86.0.4240.198

**Comment by Aljullu** [comment] 2020-12-11 15:35
Hi @davidvb67, I'm trying to diagnose this issue but I would need some more information:

* How are you accessing the widget areas? Via Appearance > Widgets or Appearance > Customize > Widgets?
* Are you getting any error in screen? Could you post a screenshot of what you see?
* Can you test with another theme (for example, [Twenty Twenty](https://wordpress.org/themes/twentytwenty/)) and try to reproduce the same issue? This will help us figure out whether the issue is in Storefront or Gutenberg.

Thank you in advance!

**Comment by davidvb67** [comment] 2020-12-11 16:14
Hi, 

This is some extra information:

I am indeed accessing the widget areas via Appearance > Widgets 
When I acces the widgets through Appearance > Customize > Widgets then I can’t insert the pre-made Gutenberg blocks.

Same thing happens when I activate Twenty Twenty.

One of the screenshots shows the error message I get when I try to save the changes. Something with ‘object’.

Best regards and enjoy the weekend!
David

**Comment by Aljullu** [comment] 2020-12-11 17:49
Thanks for details @davidvb67! I'm not able to see the screenshots, but according to your description I wonder if this is a duplicate of https://github.com/WordPress/gutenberg/issues/27173.

**Comment by Aljullu** [comment] 2021-01-13 09:10
I'm going to close this issue in favor of #27173, which is already being addressed. If you think this is a mistake, feel free to re-open or create a new issue.

**Closed by Aljullu** 2021-01-13 09:10 UTC
Labels: [Block] Legacy Widget, [Feature] Widgets Screen, [Type] Plugin Interoperability
