### ISSUE TITLE
Registering a lot of meta boxes results in a small editor screen

### ISSUE THREAD

**Issue by websupporter** [WordPress/gutenberg#11482] opened 2018-11-05 09:16 UTC
**Describe the bug**
I registered a lot of meta boxes to see what would happen. I was suprised to see a very small editor window and a very huge metabox section, basically disabling me to edit text in a good way.

**To Reproduce**

1. Add a plugin with the following code and activate it
```
add_action(
	'add_meta_boxes',
	function() {

$i = 0;
		while ( $i < 20 ) {
			add_meta_box(
				'test-'.$i,
				'TEST-'.$i,function () {
	echo '<h1>TEEEEEST</h1>';
},
				['post']
			);
			$i++;
		}
	}
);
```
2. Go the the editor

**Expected behavior**
I would expect to have the vertical scrollbar with the metaboxes, not with the editor, so I could have more space with the editor.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6458412/47988839-f65c9880-e0eb-11e8-84f1-02dadc81a491.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 14.04
 - Browser firefox

**Additional context**
- WordPress 5.0 beta 3

**Comment by La-Geek** [comment] 2018-11-05 11:54
I assume, this depends on the issue, that the meta boxes overlap the gutenberg blocks
see  #11378

**Comment by designsimply** [comment] 2018-11-05 16:04
Thank you for testing! Closing as a duplicate of #11378.

**Closed by designsimply** 2018-11-05 16:04 UTC
Labels: [Component] Meta Boxes, [Status] Duplicate, [Type] Bug
