### ISSUE TITLE
When I resize the image, it goes beyond the parent content.

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#28617] opened 2021-01-31 08:36 UTC
!!! : I'm sorry, I sent it in the middle of writing. I'm writing the continuation now.

Thank you for your development.

Please note that English may be inappropriate because you are Japanese.

## Description

When I resize the image, it goes beyond the parent content. The image may stick out when some conditions are met.

###Case 1 : In the default theme, it happens just by changing the "% size" of the image.

![img_bug_case1](https://user-images.githubusercontent.com/31400297/106378701-3190c380-63ea-11eb-8ce3-aad65da43de6.gif)

This issue can be prevented by controlling max-width in .components-resizable-box__container.

For example, I was able to solve it by adding the following CSS.

```css
.wp-block-image .components-resizable-box__container {
     max-width: 100% !important;
    height: auto !important;
}
```

### Case 2 : Further problems occur when moving blocks.

I don't know the specific conditions yet, but for example, this problem may occur when moving an image to a column-block.

It cannot be solved if it is a solution to Case1.

For example, the theme "Arkhe" includes CSS that solves Case 1, but this Case 2 has occurred further.

( "Arkhe": https://ja.wordpress.org/themes/arkhe/ )

![the_bug_case02](https://user-images.githubusercontent.com/31400297/106379193-9bf73300-63ed-11eb-996a-038dde6b8d2e.gif)

When this problem occurred, I looked into the DOM and noticed that the `.components-resizable-box__container` class did not exist.

![ss-2021-01-31 17 52 45](https://user-images.githubusercontent.com/31400297/106379171-618d9600-63ed-11eb-8956-3d7f25097957.png)

### Case 3 : As with Case 2, `.components-resizable-box__container` does not exist for mobile size.

The following image is a screenshot without the "% size" specified.

<img width="455" alt="ss-2021-01-31 18 04 33" src="https://user-images.githubusercontent.com/31400297/106379402-12e0fb80-63ef-11eb-9536-df038e563d1b.png">

And the following image is a screenshot with "% size" specified.

<img width="469" alt="ss-2021-01-31 18 04 18" src="https://user-images.githubusercontent.com/31400297/106379408-196f7300-63ef-11eb-8fa1-76d51052527b.png">

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.2
- Are all plugins except Gutenberg deactivated? "Yes".
- Are you using a default theme "Yes". Twenty Twenty-One Ver.1.1

## Device information
- Device: MacBook
- Operating system: Mac OS Catalina
- Browser: Chrome

**Comment by paaljoachim** [comment] 2021-01-31 14:47
Hi @ddryo 

Thank you for creating the issue!

Your issue is a duplicate of this issue: https://github.com/WordPress/gutenberg/issues/12168
There are also other similar issues as well.
As your issue brings with it additional context I am not sure if we should close or keep it open.
@tellthemachines @jasmussen

**Closed** 2021-02-01 02:37 UTC
Labels: [Block] Image, [Status] Duplicate, [Type] Bug
