### ISSUE TITLE
Can't select or create groups inside reusable blocks

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#19586] opened 2020-01-12 19:58 UTC
More of an inconvenience and inconsistency than anything, not impossible to work around because you can just open a reusable block it it's own window.

2020 theme, create a reusable block with manage reusable blocks. Create a paragraph inside a group. Everything works as expect.
Add the reusable block to a page, then edit the block on that page, try to select the paragraph, then try to select the group. It is impossible via the select too and via the toolbar at the bottom of the screen.

Windows 10
Edge BETA
Gutenberg 7.2

**Comment by youknowriad** [comment] 2020-01-13 12:41
Gutenberg (and the classic editor) use what we call "format boundaries". This means each format (bold, italic, link...) has two caret positions at the beginning and at the end of the format and since these two positions are not visually separated, a click there will choose one over the other.  In that case, it chose the one inside the format and not outside it but you can easily navigate in and out of the format using the arrow keys in the keyboard.  So try clicking "left arrow" when the caret is at the beginning of the link to move out of the link and start typing. 

You'll notice that if you're inside a format (link, bold...), the text is highlighted a little bit.

I hope this fixes your issue.

**Comment by noisysocks** [comment] 2020-04-21 03:47
Duplicate of https://github.com/WordPress/gutenberg/issues/19373.

**Closed by noisysocks** 2020-04-21 03:47 UTC
Labels: [Feature] Reusable Blocks
