### ISSUE TITLE
Release v3.5.0 not tagged here

### ISSUE THREAD

**Issue by goldenapples** [WordPress/gutenberg#8939] opened 2018-08-13 18:42 UTC
Version 3.5.0 is released in the .org repo, but not available as a tag here. I believe that b66cc665f30aa670a249f2386b27b5aeed659ba0 is the commit that should be tagged as `v3.5.0`

**Comment by designsimply** [comment] 2018-08-14 21:53
Releases are sorted using milestones such as https://github.com/WordPress/gutenberg/milestone/60?closed=1

I am closing this but if I've misunderstood, please let me know and I will re-open!

**Comment by chrisvanpatten** [comment] 2018-08-14 22:00
@designsimply I think @goldenapples means the Git tag, not the "labels" in GitHub. It's a bit hard to see because of all the packages releases but the last tagged release was 3.4.0: https://github.com/WordPress/gutenberg/tags?after=%40wordpress%2Fbabel-plugin-import-jsx-pragma%401.0.2

**Comment by chrisvanpatten** [comment] 2018-08-14 22:02
(There isn't an exact label for "Repo Management" — also noticed that when trying to label #8986 — but Build Tooling feels like it comes closest for this one!)

**Comment by chrisvanpatten** [comment] 2018-08-14 22:06
Just confirmed that release tagging is [in the release documentation](https://github.com/WordPress/gutenberg/blob/master/docs/reference/release.md#build-the-release), so this might have been a case of a mistakenly skipped push. Should definitely be resolved though; it makes it easier to `checkout` a specific release locally.

**Comment by pento** [comment] 2018-08-15 01:55
Thanks for the reminder, I've added the release.

https://github.com/WordPress/gutenberg/releases/tag/v3.5.0

**Closed by pento** 2018-08-15 01:55 UTC
Labels: Build Tooling

**Comment by chrisvanpatten** [comment] 2018-08-15 01:59
Thanks @pento! 🚢
