### ISSUE TITLE
Clicking new template button crashes FSE

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38562] opened 2022-02-07 09:09 UTC
### Description

Trying out the new site editor for the first time, using Twenty-Twenty Two. After clicking on the _Add New_ button to see what it does,  when browsing All Templates, the editor crashed.

![Gutenberg-fse-1](https://user-images.githubusercontent.com/2078245/152756235-c11fd71b-512c-45a0-a555-4eca7b5775b7.png)

Error: 
```
p@http://your-wordpress-site.com/wp-includes/js/dist/components.min.js?ver=6b6e502f785d29d6e254e5706ae7ec7c:37:103195
oXO//E</</e/e<@http://your-wordpress-site.com/wp-includes/js/dist/components.min.js?ver=6b6e502f785d29d6e254e5706ae7ec7c:37:105407
e@http://your-wordpress-site.com/wp-includes/js/dist/components.min.js?ver=6b6e502f785d29d6e254e5706ae7ec7c:37:106085
oXO//E</<@http://your-wordpress-site.com/wp-includes/js/dist/components.min.js?ver=6b6e502f785d29d6e254e5706ae7ec7c:37:107373
Bj@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:144:41
Qj@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:176:361
unstable_runWithPriority@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
eb@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:170:165
gf@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:162:319
$g/<@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
unstable_runWithPriority@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
$g@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:178
ja@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:111
Pa@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:157:212
Me@http://your-wordpress-site.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:110:252
e@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:22762
t@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:22829
pfJ3/Z/p/t.subscribe/o<@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:18690
pfJ3/q/instantiate/v</<@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:16310
b@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:8590
+ekt/s/</</<@http://your-wordpress-site.com/wp-includes/js/dist/redux-routine.min.js?ver=6c3ab278bc9641b6f62731e018a4449e:2:1797
pfJ3/L/</<@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:10824
pfJ3/x/</</<@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:11136
dispatch@http://your-wordpress-site.com/wp-includes/js/dist/data.min.js?ver=c5f9378263e5eea9d870764c8fc1dd1b:2:9450
+ekt/l/</</<@http://your-wordpress-site.com/wp-includes/js/dist/redux-routine.min.js?ver=6c3ab278bc9641b6f62731e018a4449e:2:1647
vsQm/e.default/t/c/u/<@http://your-wordpress-site.com/wp-includes/js/dist/redux-routine.min.js?ver=6c3ab278bc9641b6f62731e018a4449e:2:9369
```

### Step-by-step reproduction instructions

- Entered Site Editor
- Clicked top dropdown and selected _Browse all templates_
- Clicked _Add New_ button
- Clicked _Front Page_ option (as it was the only option available)
- Editor crashed

### Environment info

- WP 5.9 (no Gutenberg plugin, just core)
- Twenty-Twenty Two
- Firefox 96.0.3
- macOS Monterey 12.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-02-07 12:21
Thanks for reporting the issue, @maddisondesigns.

I followed the steps but couldn't reproduce the error. I was testing using Chrome and Firefox on macOS.

Can you enable script debugging by placing this constant in the `wp-config.php` file?

```
define( 'SCRIPT_DEBUG', true );
```

It should give us a better error stack trace.

**Comment by annezazu** [comment] 2022-02-07 20:21
I'm not able to reproduce this either as quick note.

**Comment by maddisondesigns** [comment] 2022-02-08 02:56
@Mamaduka I've turned on `SCRIPT_DEBUG` and will post back here if it happens again.

**Comment by Mamaduka** [comment] 2022-02-08 04:34
Thank you, @maddisondesigns.

**Comment by annezazu** [comment] 2022-03-09 00:55
Going to close this out for now but please let me know if this recurs and I will gladly reopen <3

**Closed as completed by annezazu** 2022-03-09 00:55 UTC
Labels: Needs Testing, [Feature] Site Editor
