### ISSUE TITLE
Bug in wordpress editor

### ISSUE THREAD

**Issue by hemrajrs** [WordPress/gutenberg#5544] opened 2018-03-10 08:17 UTC
Hi There,

I have raised one issue with existing wordpress editor, and they closed it saying it may get resolved with gutenberg,

https://core.trac.wordpress.org/ticket/42876

I tested this plugin and it seems this issue is also exist in gutenberg

Please check

Thanks,

**Comment by ajitbohra** [comment] 2018-07-08 13:54
Unable to reproduce this on the master. Hence closing this for now, feel free to reopen.

Observation:
If word document is empty and you type `a.` & hit space its automatically converted into a list. Copying that to the editor will create list block which is expected behavior.

**Closed by ajitbohra** 2018-07-08 13:54 UTC
Labels: [Component] Raw Handling, [Component] TinyMCE, [Type] Bug
