### ISSUE TITLE
Need quicker path to access  "Reusable Block Management"

### ISSUE THREAD

**Issue by gbassoc** [WordPress/gutenberg#13519] opened 2019-01-26 01:14 UTC
I am really embracing Gutengberg, each day I find something really useful to enhance my content writing.
 
I have created several reusable blocks that I can use in any area of my website using a couple of plugins I have discovered. However what's annoying is in order to get to "Reusable Block Management" I first have to go to a page then click on "More Tools and Option" and then I see the link for "Reusable Block Management".

This is crying out to have it own link on the Admin Menu panel.

**Comment by paaljoachim** [comment] 2019-01-26 19:15
Hello again @gbassoc 
Management of Reusable blocks is still lacking. It will get there.
https://github.com/WordPress/gutenberg/issues/12286

**Comment by gbassoc** [comment] 2019-01-26 21:39
Glad to hear it my friend!

**Comment by youknowriad** [comment] 2019-02-06 16:20
closing as a duplicate of #13519 as it's a different goal but same consequence. Feel free to chime-in there.

**Closed by youknowriad** 2019-02-06 16:20 UTC
Labels: [Component] Reusable Blocks
