### ISSUE TITLE
Columns (beta) renders correctly in Gutenberg Editor but wrong on website

### ISSUE THREAD

**Issue by Theremingenieur** [WordPress/gutenberg#7518] opened 2018-06-24 12:23 UTC
**Describe the bug**
See title

**To Reproduce**
1. Create a new Columns block with 2 columns. 
2. Insert a single image block into the first column and pick a picture from the media library.
3. Insert alternating header and paragraph blocks in the second column.
4. Everything looks fine in the editor
5. Switch to preview
6. See that the second column is rendered BELOW the 1st column.

**Expected behavior**
The second column should show up on the right side besides the first column

**Screenshots**
Editor:
![capture d ecran 2018-06-24 a 14 19 11](https://user-images.githubusercontent.com/25463159/41819006-c5db2b36-77b9-11e8-9293-3b4a21e87713.png)
Website preview:
![capture d ecran 2018-06-24 a 14 20 03](https://user-images.githubusercontent.com/25463159/41819007-c5f7a252-77b9-11e8-8422-af19df2fa50d.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13
 - Browser: Safari & Firefox
 - Gutenberg 3.1.0, WP 4.9.6, Twentyseventeen child theme

**Comment by chrisvanpatten** [comment] 2018-06-24 13:35
Likely a duplicate of #5351, unless it previously worked for you in 3.0.1? If it worked in 3.0.1 but stopped working on 3.1, that could be a regression.

**Comment by Theremingenieur** [comment] 2018-06-24 13:52
Had not tested this in 3.0.1. Found it already wrong this way  in earlier releases, abondoned  that for a few months and decided to give it a try with 3.1. Now surprised that the issue still exists. Am I the only one to experience that?

**Comment by chrisvanpatten** [comment] 2018-06-24 14:43
@Theremingenieur no, definitely not the only one. #5351 has a lot of discussion about it, and #7234 is trying out a potential solution.

**Comment by Theremingenieur** [comment] 2018-06-24 15:55
@chrisvanpatten  Thank you for your time to reply. It looks like that pull request did not make it into 3.1 and I‘ll have to wait for a later release.

**Comment by designsimply** [comment] 2018-06-27 17:42
Thank you for the report! I'd like to close this as a duplicate of #5351 since it has work in progress.

**Closed by designsimply** 2018-06-27 17:42 UTC
Labels: Blocks, [Type] Bug
