### ISSUE TITLE
Unsaved text in Code Editor disapears when switching to Visual Editor

### ISSUE THREAD

**Issue by boblmckee** [WordPress/gutenberg#12768] opened 2018-12-10 19:00 UTC
If there is unsaved code / text in editor, and switch to the other editor, the unsaved code/text is removed. This did not happen in old editor.

**Comment by youknowriad** [comment] 2018-12-26 15:42
This doesn't happen to me. Do you have any other plugin that can alter the behavior of the editor?

**Comment by designsimply** [comment] 2019-01-07 22:02
I tested this using WordPress 5.0.2 and Gutenberg 4.8.0 `master` @ `71be7e60f` using Firefox 63.0.3 on macOS 10.13.6 and was unable to see the problem happen with the following steps:

1. Create a new post.
1. Type some content into a paragraph block.
1. Go to More > Edit as HTML in the block toolbar.
1. Make a change to the HTML.
1. Go to More > Edit visually in the block toolbar.
1. Confirm that HTML changes took effect.
1. Add a little more content.
1. Go to More > Code Editor in the main editor toolbar.
1. Make another change to the HTML.
1. Go to More > Visual Editor in the main editor toolbar.
1. Confirm that HTML changes took effect.

<strong>Result:</strong> basic HTML changes made using valid/approved HTML all took effect and worked as expected. ([43s](https://cloudup.com/cswCnfTAtYI))

<sup>Seen at http://localhost:8888/wp-admin/post.php?post=7&action=edit running WordPress 5.0.2 and 4.8.0 `master` @ `71be7e60f` using Firefox 63.0.3 on macOS 10.13.6.</sup>

@boblmckee I am closing this issue after two testers reported being unable to reproduce the problem. However, if you spot something different in the testing steps listed above compared to what is shown above, please re-open the issues with a new set of steps for testing (for example, if you tested with a block other than the paragraph block). Please also check that you have updated to the latest version of WordPress and please include a sample of unsaved code/text that did not work for you. Note that the HTML should be valid HTML and not something normally removed during block conversion. If you are using non-standard HTML, then the Custom HTML block should be used instead of modifying HTML in a paragraph (or similar) block.

**Closed by designsimply** 2019-01-07 22:02 UTC
Labels: Code Editor, History, [Status] Needs More Info
