### ISSUE TITLE
Social Icons Block should have Phone as an option

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33609] opened 2021-07-21 19:06 UTC
## What problem does this address?

I know the mobile phone number is not a social network, but it is commonly used in the same place as social icons

## What is your proposed solution?

There should be a phone on the social icons list. Just like email is.
![image](https://user-images.githubusercontent.com/11801254/126545439-62e77557-f1c1-4555-b680-e5982f6978c4.png)

**Comment by TheRadicalDreamer** [comment] 2021-07-21 19:08
And Whatsapp also by the way

**Comment by jasmussen** [comment] 2021-08-03 06:51
This seems to be a duplicate of #32890, is that right?

**Comment by TheRadicalDreamer** [comment] 2021-08-03 14:39
Yes. But I also mentioned WhatsApp as a missing icon

**Comment by jasmussen** [comment] 2021-08-05 06:41
Cool, thanks. In that case we can close this one in favor of #32890 (phone icon), and #30378 (Whatsapp icon.)

**Closed as completed by jasmussen** 2021-08-05 06:41 UTC
Labels: [Type] Enhancement, [Block] Social

**Comment by loyukfai** [comment] 2021-08-11 15:22
Thanks for mentioning issue #30378, would we be so lucky to see these added in the next release? 😊
