### ISSUE TITLE
Image blocks can not be previewed in Internet Explorer

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8186] opened 2018-07-25 00:14 UTC
In Internet Explorer 11, previously #3585

When adding an image block, or trying to view an existing one in a page, it shows the error `This block has encountered an error and cannot be previewed.`

![image](https://user-images.githubusercontent.com/468735/43172354-3ddfbf9a-8faf-11e8-8882-4a5d92a80f15.png)

Stack trace from JS console

```
"TypeError: Object doesn't support property or method 'from'
   at Anonymous function (http://gutenberg.local/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1532269725:12:71497)
   at base.get (http://gutenberg.local/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1532269725:12:71384)
   at value (http://gutenberg.local/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1532269725:12:65844)
   at dg (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:110:434)
   at eg (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:113:462)
   at jc (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:131:280)
   at gc (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
   at vb (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
   at ub (http://gutenberg.local/wp-content/plugins/gutenberg/vendor/react-do"
```

Versions:
Gutenberg 3.3.0
Internet Explorer 11.112.17134.0
Windows 10

**Comment by jorgefilipecosta** [comment] 2018-07-25 19:33
I'm able to reproduce this, the problem is caused inside re-resizable like in https://github.com/WordPress/gutenberg/issues/3585 which was closed meanwhile.

**Comment by jorgefilipecosta** [comment] 2018-07-25 19:54
Things seem to work correctly on the last version of re-resizable. When merged PR https://github.com/WordPress/gutenberg/pull/8209 will fix this problem.

**Closed** 2018-07-31 15:56 UTC
Labels: Blocks, Browser Issues, [Type] Bug
