### ISSUE TITLE
Gallery block setting Randomize order isn't doing anything

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#65120] opened 2024-09-06 11:11 UTC
### Description

`Randomize order` button on gallery block settings isn't doing anything in the editor or live site.

### Step-by-step reproduction instructions

1. Go to editor and create a gallery with 6 images.
2. Go to block setting of created gallery block.
3. Enable the toggle "Randomize order"
4. Save changes.
5. Go to live site, and observe that the image order remains same (even after multiple reloads)

### Screenshots, screen recording, code snippet

**Editor:**

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/9fa152d4-931f-41f0-80c4-5f80a5c4efc7">

**Live site:**

<img width="836" alt="image" src="https://github.com/user-attachments/assets/7cfd2d7c-d86e-4105-b45b-f4a8cefa707d">

### Environment info

- WordPress 6.6
- Gutenberg 19.1.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment] 2024-09-08 16:29
I haven't been able to reproduce this issue.

- Are you experiencing this issue in Gutenberg trunk?
- Does this issue occur under certain conditions?

https://github.com/user-attachments/assets/20d93444-2aef-46e4-af9d-c374570c2397

**Comment by kspilarski** [comment] 2024-09-09 03:04
Hi @madhusudhand and  @t-hamano I am also not able to replicate this issue. 

Editor with a gallery on randomized order: 
<img width="624" alt="Screenshot 2024-09-09 at 11 55 00" src="https://github.com/user-attachments/assets/66bd32ba-4f36-449c-bac9-e74a9ee277a6">

The live site displays the gallery images randomly, and the image order changes everytime the site is refreshed: 
<img width="615" alt="Screenshot 2024-09-09 at 11 55 27" src="https://github.com/user-attachments/assets/b015d6ba-1c8c-4ac4-a4e0-0ee9c95ffcc6">

**Comment by ntsekouras** [comment] 2024-11-12 14:58
I can't reproduce either. Let's close this for now.

**Closed as completed by ntsekouras** 2024-11-12 14:58 UTC
Labels: [Type] Bug, [Block] Gallery

**Comment by pomito** [comment] 2025-08-28 13:01
Hello @ntsekouras @madhusudhand We may have found the cause of this issue. While working together with a colleague @les-ann, we ran into the same problem. It seems to be related to images that have the “Enlarge on click” option enabled.

In a gallery with mixed images, only the ones without this option enabled get randomized after refreshing. The images with “Enlarge on click” stay in the same place.

https://github.com/user-attachments/assets/ac80ad4c-d6f1-499b-8680-1ad28894877b

**Comment by t-hamano** [comment] 2025-08-29 09:07
Thanks for the report, @pomito!

Your report revealed that the randomization logic was insufficient. #71408 should fix the issue that occurs when the Gallery block has lightbox images
