### ISSUE TITLE
Block previews can cause flickering at specific screen sizes

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#24611] opened 2020-08-18 07:23 UTC
**Describe the bug**

When an image block is selected and the sidebar is open, the sidebar flickers. I have managed to reproduce this both in fullscreen mode and with the wp-admin sidebar showing, but so far only on Chrome/mac and with scrollbars always visible.

Could be related to #19304

**To reproduce**
1. Open sidebar
2. Add image block
3. Watch sidebar flicker

**Screenshots**

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/8096000/90482937-51ebff00-e177-11ea-8ed6-8ebbf128a502.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Gutenberg version: latest from this repo

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - Browser Chrome
 - Version 84

**Comment by joyously** [comment] 2020-08-19 02:27
I mentioned this in WP 5.5 RC2: https://wordpress.slack.com/archives/C02QB2JS7/p1596755462372600

I was using Firefox 79 on Ubuntu, and the window width was 1031px. Mine happened when clicking on the Advanced metabox.
![seizure-mode](https://user-images.githubusercontent.com/7957680/90584958-5aedc800-e199-11ea-91f3-059dd7d4676b.gif)

**Comment by ntsekouras** [comment] 2020-09-23 15:50
I can't reproduce this now. Can you verify that it has been fixed?

**Comment by talldan** [comment] 2020-11-05 03:15
I've noticed this happening more lately.

I closed #26711 as a duplicate, which had some notes on reproducing the issue.

**Comment by JasonWoof** [comment] 2020-11-05 04:26
To reproduce you need a very specific window height. There's only a 5-pixel range of window heights where I get the flicker in chrome, and it's a bit taller than fits on a 1080p monitor.

Try zooming out with ctrl-minus and then resizing your window.

Insert an image block and select/upload an image into it. Open the block settings for this block.

Make sure that the "advanced" section at the bottom of the right-hand column is collapsed, and then resize your window very slowly until there's just barely not enough room for the "advanced" section toggle to fit without scrolling.

I can reproduce with firefox and chrome on linux. Both with the zoom-out trick and at normal size.

**Comment by Morgunov-Vitaly** [comment] 2021-05-18 15:05
I have the very similar issue with patterns panel!

**Comment by miminari** [comment] 2021-06-22 06:16
I closed #31943 #29255 as duplicate by [today's triage](https://wordpress.slack.com/archives/C02QB2JS7/p1624339362341100).
I was able to reproduce #29255, which may be reproduce more easy.

**Comment by getsource** [comment] 2021-06-22 08:36
Just in case it's helpful, when testing #29255, I was able to see these two places in dev tools changing during the flickering:

https://user-images.githubusercontent.com/1034160/122892254-33025e80-d380-11eb-9bfd-aed2b1bc3833.mov

https://user-images.githubusercontent.com/1034160/122892273-34cc2200-d380-11eb-839d-0ad855a71a41.mov

**Comment by JasonWoof** [comment] 2021-06-22 08:39
Please make sure you also test/fix the scrollbar flickering issue in the sidebar. Unless you have an unusually large resolution, you may need to zoom out to be able to resize your browser window big enough. See detailed instructions on reproducing here: https://github.com/WordPress/gutenberg/issues/24611#issuecomment-722133323

Also, in the interest of getting everything in one place, here's an explanation of how this bug works:

In browsers where the scrollbars take up space (ie the scrollable content area gets narrower to make room for it), when you make the scrollable area just barely too small in height to contain the content, a scrollbar appears, because of the css property "overflow-y: auto". If the scrollable content contains something that maintains aspect ratio, then when it gets narrower (because of the addition of the scrollbar) it'll also get shorter (less height). If your scrollable area is just exactly the wrong height, then these few pixels shorter will cause the content to fit without scrolling, which causes the scrollbar to disappear and the whole cycle begins anew.

And how to fix it:

I think that the best solution to this problem is to replace "overflow-y: auto" with "overflow-y: scroll". In addition to fixing this flickering issue, it also reduces the distraction of ui in the sidebar from resizing to be come narrower/wider whenever the scrollbar is added/removed (which can happen quite a lot, eg when people click the section toggles).

**Comment by stokesman** [comment] 2021-06-22 16:30
>I think that the best solution to this problem is to replace "overflow-y: auto" with "overflow-y: scroll"

That happens to be what #31858 does. It should fix this issue but not the other ones that were closed as duplicates.

**Comment by antonis** [comment] 2021-08-19 08:52
I was able to reproduce this issue (or a similar one) when the patterns tab is selected in the block inserter.

https://user-images.githubusercontent.com/304044/130038878-2ff8f04a-8e66-4caa-81f9-460888f2f1a7.mov

When the scrollable height matches the available screen height the behaviour illustrated in the attached video occurs. I was able to reproduce both with Chrome and Safari on Mac.

**Comment by talldan** [comment] 2021-10-12 07:45
Another report of this in https://github.com/WordPress/gutenberg/issues/35494 with the patterns panel.

I've retitled the issue to make it easier to find.

**Comment by t-hamano** [comment] 2022-07-24 12:40
The block style previews are now displayed as popovers, so I believe this issue will no longer occur.
How about testing again to see if we can close this issue?

**Comment by Mamaduka** [comment] 2023-03-22 04:52
I think we can close this one.

**Closed by Mamaduka** 2023-03-22 04:52 UTC
Labels: [Type] Bug, [Block] Image
