### ISSUE TITLE
Warning after inserting a Gallery into an empty post

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#52362] opened 2023-07-06 08:56 UTC
### Description

The following React warning is logged in the console after inserting a Gallery into an empty post. The gallery should be the only block in a post.

Based on the trace, this might be related to recent changes introduced for the Footnotes feature #51201.

cc @ellatrix

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <figure>. See https://reactjs.org/link/warning-keys for more information.
    at figure
```

### Step-by-step reproduction instructions

1. Create a new post.
2. Insert Gallery block.
3. Select images from the media library and create a Gallery.
4. The warning should be logged in the console.

There are a few other ways to reproduce the warning. See the screencast for another one.

### Screenshots, screen recording, code snippet

![CleanShot 2023-07-06 at 12 42 12](https://github.com/WordPress/gutenberg/assets/240569/e46bbd1a-cd00-4daf-9775-354fabcbac85)

https://github.com/WordPress/gutenberg/assets/240569/ca171ec8-f390-458a-98d2-e50c5ecaf99d

### Environment info

- WP 6.2, Gutenberg latest trunk
- Chrome, MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-07-10 14:47
I was able to reproduce the same issue shortly after this issue was submitted. With the latest trunk, I could not reproduce this issue. I think #52241 probably solved the problem because the `getRichTextValues` that appear in the trace changed in #52241. 

Therefore, I would like to close this issue.

**Closed as completed by t-hamano** 2023-07-10 14:47 UTC
Labels: [Type] Bug, [Feature] Nested / Inner Blocks
