### ISSUE TITLE
Yoast SEO FAQ get stucks when activating Gutenberg

### ISSUE THREAD

**Issue by bilalimran1412** [WordPress/gutenberg#40574] opened 2022-04-25 05:11 UTC
### Description

The yoast SEO faq block hangs and get uneditable/freezez when gutenberg is active. 

### Step-by-step reproduction instructions

Install Yoast SEO
Install Gutenberg

1) Add new post 
2) Add new block
3) Choose FAQ Yoast block 

### Screenshots, screen recording, code snippet

https://www.awesomescreenshot.com/video/8569881?key=29452fd62c46a259afa62297f2fe0128

### Environment info

Gutenberg Version 13.0.0
Wodrpess  5.9.3
Browser Chrome 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-04-25 05:26
Hi!
Can you provide any more details that can help us reproduce this?
Do you know how to use the browser devTools to check if there are any JavaScript errors?
What steps did you perform to unfreeze it, or did it start to respond again after a few seconds?

>Please confirm that you have tested with all plugins deactivated except Gutenberg.

Did you deactivate all other plugins? I am asking so that we can try to exclude other plugin conflicts, and because there are many other plugins active in the video.

**Comment by carolinan** [comment] 2022-04-28 06:21
Just letting you know that at Yoast we have received additional bug reports about this issue, we are looking into it.
Because this is not a Gutenberg issue, I will close this issue but I will keep you updated when I learn anything new.

**Closed as completed by carolinan** 2022-04-28 06:21 UTC
