### ISSUE TITLE
Formatting Settings within a Block Are Affecting Text Outside That Block, and the WordPress Interface Itself

### ISSUE THREAD

**Issue by rcio1** [WordPress/gutenberg#31307] opened 2021-04-29 03:06 UTC
My understanding is that settings for elements inside a block, i.e. text weight, should not affect elements outside that block, however, that is what I am seeing.

I have seen this with both Getwid's "Advanced Header" block, and Stackable's "Advanced Header" block.  Those just happen to be the ones that made me notice it, but this may also occur with other blocks, from other creators.

This has been confirmed to occur on a default fresh install of WordPress 5.7.1, using the Twenty-Twenty-One theme, and no other themes or plugins installed.

This issue is viewable in the following browsers on Linux: Firefox, Brave, and Chromium.
I believe this issue always occurs, however, in my testing it is not apparent on Windows (I suspect because Windows isn't using/displaying fonts correctly).

I first noticed this when I added a Getwid "Advanced Header" block to my page content using weight 900 for the font, and discovered my footer text also started displaying as extra bold.

It concerns me greatly to think that formatting settings in one block could affect [mess up] other parts of my site.  I would think that this shouldn't be possible.

This is easy to reproduce for testing...  Just create a page with some paragraph text, add a Getwid "Advanced Header" block, set the weight in the block to 900, and see the paragraph text also change.  This issue also affects the text of the WordPress interface itself, visible on the top strip, and in the block settings area.

I have included some screen shots:
Test Page A: This just provides reference for how the title and paragraph text should look.
Test Page C: Same page, with a Getwid "Advanced Header" block, weight 100
Test Page C: Same page, with a Getwid "Advanced Header" block, weight 900

Note, the page title and paragraph text _should_ be displaying as identical in all three screenshots, the issue I am reporting is the fact that it does not.

![Test-Page-A](https://user-images.githubusercontent.com/83384262/116497638-db5edf80-a875-11eb-869f-b4f01a829d98.png)
![Test-Page-C](https://user-images.githubusercontent.com/83384262/116497640-dbf77600-a875-11eb-9a3b-f2f1c5da5dc1.png)
![Test-Page-D](https://user-images.githubusercontent.com/83384262/116497641-dbf77600-a875-11eb-9525-6b8ee72c9dac.png)

**Comment by carolinan** [comment] 2021-05-01 04:17
Hi!
To eliminate that this is an issue with the two mentioned plugins, please provide instructions where the problem can be reproduced without any other plugins installed than Gutenberg,

**Comment by rcio1** [comment] 2021-05-01 16:32
Thank you for considering my report.

Per your request, I have tried to reproduce the problem on a new WordPress installation without any other plugins installed, and so far I have been unable to do so.

Given that blocks from two different companies seem to be showing the same or similar improper behavior, I had suspected that there may be a shared root cause, such as an underlying issue with WordPress/Gutenberg.

Based on the testing I've done, I am now considering other possible explanations for the problems I am seeing, such as:
- The problem may be with the actual plugins, and not necessarily with the specific blocks being used.
- Each company's plugin may have it's own separate/unique bug(s) that just happen to look similar.

I have support tickets opened with both Getwid and Stackable.  At this point, I think it is fair to wait and see what they each find before pursuing any further the theory of a possible issue with WordPress/Gutenberg.  Hopefully Getwid and Stackable will find the root cause of the issues seen with their individual plugins, and share their findings.

I will provide an update when/if I get any helpful information from Getwid and/or Stackable.

**Comment by annezazu** [comment] 2021-05-19 00:40
@rcio1 Thanks so much for your awesome and thorough reply + sleuthing. It's greatly appreciated! I'm sure the respective block creators are appreciative too. 

For now since it's been over two weeks, I'm going to close this out as I believe the problem is with the actual plugins rather than the core editor itself. With that said, if you hear back and find the issue might be with Gutenberg, please do comment back here so the investigation can continue :D

**Closed as completed by annezazu** 2021-05-19 00:40 UTC
Labels: Needs Testing
