### ISSUE TITLE
Selected custom gradient is not displayed in color settings

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#42017] opened 2022-06-28 16:28 UTC
## Description
When setting a custom gradient in the color settings, there is no indication that a custom gradient is selected. The "Custom" indicator is missing entirely, leaving the appearance of no color/gradient selected. 

## Step-by-step reproduction instructions
1. Add a Buttons block. 
1. Open the settings for the Button block. 
1. Tap _Background_. 
1. Tap _Gradient_. 
1. Select a preset gradient. 
1. Tap _Customize Gradient_. 
1. Modify the gradient. 
1. Tap _Back_. 

## Expected behaviour
At the end of the list of gradients, a "Custom" option is listed and marked as selected with a checkmark. 

## Actual behaviour
There is no "Custom" option listed in the list of gradients. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/438664/176231648-36002fcc-348b-44fc-809c-0e29ebe668aa.MP4

## WordPress information
- WordPress version: 6.0
- Gutenberg version: 13.5.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: iPhone SE, Samsung Galaxy S20
- Operating system: iOS 15.6, Android 12
- WordPress app version: 20.1

**Comment by dcalhoun** [comment] 2022-06-28 16:34
This may be related to https://github.com/WordPress/gutenberg/pull/30994.

**Comment by fluiddot** [comment] 2022-06-29 10:52
I managed to reproduce it on version 19.6, so looks like this issue was introduced a while ago. I don't think it's a major issue but since it's a regression I'll set it as a high priority.

**Comment by geriux** [comment] 2024-01-05 16:30
I'm working on a fix for this since I've probably introduced this regression in https://github.com/WordPress/gutenberg/pull/38417

Since it's been a while since this issue was opened, I'll remove the high-priority label since a fix is on the way anyways.

**Closed as completed** 2024-01-10 14:49 UTC
Labels: [Status] In Progress, [Type] Regression, Mobile App - i.e. Android or iOS, [Feature] Colors
