### ISSUE TITLE
Browser gets frozen after pressing ENTER button

### ISSUE THREAD

**Issue by stevepdt** [WordPress/gutenberg#12150] opened 2018-11-21 03:54 UTC
**Describe the bug**
I updated the last version of Gutenberg (4.5.0) this morning (10:00 am GMT +7). After updating, I try to write a post, it **gets frozen** when I press ENTER button **to create next paragraph**. Moreover, when I open the posted article and click to a paragraph to edit, then I **can't click to another** or the title again. Please check it and let me know if it not a bug (First, I think it's my computer problem but it was normal if I use Classic Editor or the old version of Gutenberg).

**To Reproduce**
1. Click 'Add new' to create a post
2. Write something in paragraph
3. Press 'Enter'
4. The browser's tab is frozen after 2 secs.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Coc coc (Vietnamese's browser which is built on Chrome platform)
 - Version: 75.4.124 (32 bit)

**Comment by meymigrou** [comment] 2018-11-21 04:48
I'm having the same problem! I can't create or edit posts and pages because the browser gets frozen.

**Comment by stevepdt** [comment] 2018-11-21 05:37
> I'm having the same problem! I can't create or edit posts and pages because the browser gets frozen.

Seems like it's not my own problem. Hope they can find the way to fix it soon.

**Comment by miniMAC** [comment] 2018-11-21 08:10
Is a React/JS problem. Results from console:
<img width="893" alt="schermata 2018-11-21 alle 09 07 23" src="https://user-images.githubusercontent.com/1235741/48827321-3a4ad100-ed6d-11e8-8004-b56addeedfa6.png">

**Comment by youknowriad** [comment] 2018-11-21 08:18
Do you have any plugin installed with Gutenberg support like Yoast for instance? Can you try to disable them to see if there's a conflict.

**Comment by gziolo** [comment] 2018-11-21 08:19
Error message from the url for reference:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by miniMAC** [comment] 2018-11-21 08:21
@youknowriad You right! The problem is Yoast SEO plugin.

**Comment by iseulde** [comment] 2018-11-21 08:32
Duplicate of #12143.

**Closed** 2018-11-21 10:02 UTC
