### ISSUE TITLE
Templates: Focus mode: Constrain the view to the size of the template part

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42731] opened 2022-07-27 11:29 UTC
## What problem does this address?
When editing template parts in focus mode, its hard to understand how they fit into the broader context of the site because there is so much white space:
<img width="1440" alt="Screenshot 2022-07-27 at 12 26 02" src="https://user-images.githubusercontent.com/275961/181235720-80b42caa-be66-4429-9873-94c222b9047c.png">

## What is your proposed solution?
Ideally the iframe would display at the same size as the template is rendered at in the site, something like this:
<img width="1440" alt="Screenshot 2022-07-27 at 12 28 11" src="https://user-images.githubusercontent.com/275961/181236223-441fb71a-4b16-46d5-bc54-45033dd40723.png">

**Comment by Mamaduka** [comment] 2022-07-27 11:44
Duplicate of #42226.

**Closed as completed** 2022-07-27 12:15 UTC
Labels: [Feature] Site Editor, [Feature] Focus Mode
