### ISSUE TITLE
Add a way to identify variations in html (group / row)

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#39382] opened 2022-03-11 11:46 UTC
## What problem does this address?
Currently there is no way to see in the front-end code if a group has a 'row' variation or not.

This can create some issues, especially when custom css is involved. 

## What is your proposed solution?
Similar to 'block-styles', there should be some way to identify if a group is in row variation or not.

`is-variation-row` comes to mind.

**Comment by carolinan** [comment] 2022-03-11 13:56
Hi!
I am closing this issue as a duplicate of https://github.com/WordPress/gutenberg/issues/38126.

Feel free to voice your support in the pull request, there is no consensus yet if a class like this should be added.
https://github.com/WordPress/gutenberg/pull/39181

**Closed as completed** 2022-03-11 13:56 UTC
Labels: [Status] Duplicate
