### ISSUE TITLE
Button block not showing border/outline

### ISSUE THREAD

**Issue by rielyncampbell** [WordPress/gutenberg#38387] opened 2022-01-31 20:31 UTC
In our 2020 WordPress theme installation, we are not able to get the border outline for our buttons to appear.  It shows in the editor but not on our site.  If I deactivate gutenberg, it works.  It appears to work up to 11.8.3 version of the gutenberg plugin.  After that, the border disappears.
We are currently on WP core version 5.8.2 and twenty-twenty theme version 1.9.
I deactivated all other plugins and this issue persisted as described above.

Adding screenshot of inspect of the CSS that is setting border:none;
![Screen Shot 2022-01-31 at 3 45 35 PM](https://user-images.githubusercontent.com/18360227/151870414-7cc4973d-dce1-401e-9a3b-7055e231bd1d.png)

Another screenshot taken of the full screen with "Test" being a button that should have a border.
![Screen Shot 2022-01-31 at 3 47 04 PM](https://user-images.githubusercontent.com/18360227/151870594-21ae4000-eecb-4326-9259-6062c7ba0c66.png)

Here is a screenshot of when it works.  You can see the .is-style-outline>.wp-block-button__link style has the border: 2px solid;
![Screen Shot 2022-01-31 at 3 50 56 PM](https://user-images.githubusercontent.com/18360227/151871087-cf8f820a-7a46-4041-a6ba-ba9445bdc9ac.png)
s.

**Comment by carolinan** [comment] 2022-02-02 12:23
Possibly related to this change in 11.9:
https://github.com/WordPress/gutenberg/commit/c0e6bd4aa8cf9a44bdb120fa9a80b7adc7ece902

**Comment by carolinan** [comment] 2022-02-02 12:38
I can confirm the issue. And my suggestion would be to open a ticket on Trac to update the theme instead,
The theme removes the border in style.css line 840, but it does so for all button blocks, when (according to the original design) it should only remove it for the filled button (default).

**Comment by dhjw** [comment] 2022-02-06 18:11
https://core.trac.wordpress.org/ticket/54919

**Comment by annezazu** [comment] 2022-02-09 08:25
Going to close this out since a trac issue is now open :)

**Closed as completed by annezazu** 2022-02-09 08:25 UTC
Labels: [Block] Buttons
