### ISSUE TITLE
Toolbar on small screens not working for blocks in columns

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#11499] opened 2018-11-05 15:53 UTC
**Describe the bug**
On screens below 600px, the toolbar for blocks added in column blocks disappears when clicked. Also the toolbar appears to the bottom of the block, not the top. Not sure if that was intended.

**To Reproduce**
I added a columns block. In one of the columns I added the cover image block. In the cover image block, when I click a button in the toolbar (e.g. align text button) the entire toolbar disappears. 

**Screenshots**

![screen shot 2018-11-05 at 5 45 07 pm](https://user-images.githubusercontent.com/3076742/48008930-4c98fe00-e123-11e8-9939-1b0d6bb9b5c7.png)

**Desktop (please complete the following information):**
 - Chrome 70.0.3538.77

**Additional context**
- Gutenberg 4.1.1.

.

**Comment by designsimply** [comment] 2018-11-07 20:50
Tested and confirmed that clicking on any of the alignment options for a cover block inside a columns block causes the toolbar to disappear if the screen size is <600px wide. ([33s](https://cloudup.com/cv96uQ3tpTI))

<sup>Tested using "Responsive Design Mode" in Firefox 63.0.1 on macOS 10.13.6 using WordPress 4.9.8 and Gutenberg 4.2.0.</sup>

**Comment by virgiliud** [comment] 2018-11-08 10:18
@danhort note: there are issues with other blocks as well that are added in the columns block at screen size < 600px. For example the + sign for adding blocks cannot be selected.

**Comment by virgiliud** [comment] 2018-11-15 09:35
Note: this is still an issue in version 4.3.0. Column blocks are behaving strange on mobile and are difficult to click.

**Comment by marekhrabe** [comment] 2019-02-22 14:42
I've noticed this bug when working on Columns. I identified that the cause is a pseudo element `::after` of `.editor-inner-blocks`, which gets displayed when class `.has-overlay` is also active on it.

<img width="1176" alt="screenshot 2019-02-21 at 13 21 15" src="https://user-images.githubusercontent.com/156676/53249168-c398d900-36b7-11e9-8fbb-fdefedac4fd5.png">

Not only toolbars are inaccessible. Nothing inside InnerBlocks is clickable due to the element being positioned over everything. Apart from Toolbars, this blocks the access to block UIs and generally clicking anything in blocks - even making text selections. All of that is caught as a click on the parent block and selects it.

I believe we should raise the priority of this issue, as it makes anything in `InnerBlocks` completely inaccessible on smaller screens.

**Comment by marekhrabe** [comment] 2019-02-22 14:45
This overlay pseudo element was introduced as part of https://github.com/WordPress/gutenberg/pull/6773

**Comment by youknowriad** [comment] 2019-08-22 12:49
In my testing, the clicking the alignment options (left/right) can move the toolbar to the top of the block. 

I think the floated toolbars are probably not working properly on mobile unless that's intended. cc @jasmussen @kjellr

**Comment by jasmussen** [comment] 2019-08-23 07:23
> In my testing, the clicking the alignment options (left/right) can move the toolbar to the top of the block.

This is "intentional" in that it is the best interface we could provide given the complexities that floats add to the interface. However it's also pretty clear that we can definitely improve here:

<img width="524" alt="Screenshot 2019-08-23 at 09 22 17" src="https://user-images.githubusercontent.com/1204802/63574237-9bffcc00-c587-11e9-81b2-23c9d3894f3b.png">

**Comment by youknowriad** [comment] 2020-02-27 13:06
I think this is fixed now that the block toolbar is fixed on mobile

**Closed by youknowriad** 2020-02-27 13:06 UTC
Labels: Mobile Web, [Block] Columns, [Feature] UI Components, [Type] Bug
