### ISSUE TITLE
I can not use Gutenberg in any way

### ISSUE THREAD

**Issue by jotapardo** [WordPress/gutenberg#39368] opened 2022-03-11 01:39 UTC
### Description

I want to use Gutenber in my site, but all post and pages always edit with the editor clasic. I've uninstalled clasic editor, and also all related plugins I had been using in the past. However, nothing happens. I can not use gutenberg. I installed Gutenberg Version 12.7.2 but I can not find where I need to configure or what I need to do more... It is really frustrating. Is there some configuration in the wordpress files where I can find another solution to force Gutenberg use technically? maybe some .php configuration file?

### Step-by-step reproduction instructions

1. Go to Pages
2. Click on Edit any Page
3. Always open with Classic Editor.
4. I can not find any option related with edit with Gutenberg.

### Screenshots, screen recording, code snippet

![2022-03-10_20h35_15](https://user-images.githubusercontent.com/24879714/157785105-d967a102-df27-4691-a6db-f006433181be.png)
![2022-03-10_20h35_20](https://user-images.githubusercontent.com/24879714/157785108-97925fcf-7da3-4b62-9020-65edd7516d60.png)
![2022-03-10_20h35_30](https://user-images.githubusercontent.com/24879714/157785110-9d09d1f4-6a4d-43cd-980e-0bc34ad10aa6.png)
![2022-03-10_20h35_35](https://user-images.githubusercontent.com/24879714/157785112-8603503d-58bf-4d99-be63-229e0a63864d.png)
![2022-03-10_20h35_55](https://user-images.githubusercontent.com/24879714/157785114-e2ec5da2-7061-49d4-a6e6-e1d0ed9d35c4.png)
![2022-03-10_20h36_18](https://user-images.githubusercontent.com/24879714/157785116-56dcab02-387e-436c-be17-9c3bdff7a056.png)
![2022-03-10_20h36_25](https://user-images.githubusercontent.com/24879714/157785121-ace84cba-7d8e-48c0-b5ed-ee3d83467fe0.png)
![2022-03-10_20h36_46](https://user-images.githubusercontent.com/24879714/157785123-d913c801-935b-4958-9008-dcf6f5b58a16.png)

### Environment info

Wordpress version 5.9.1, Gutenberg 12.7.2, Theme GeneratePress 3.1.0
Problem in Chrome, Firefox, Edge.
Desktop windows 10, and Phone with Andriod 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-03-11 02:31
Hi @jotapardo

Perhaps the block editor (Gutenberg) is disabled on the theme side ?

Please try to activate the default theme such as "Twenty Twenty Two" or "Twenty Twenty One".

Also, Gutenberg is included in WordPress itself, so please diactivate the Gutenberg plugin if you do not need to try the latest features.

**Comment by jotapardo** [comment] 2022-03-14 20:19
Thank you for your answer @t-hamano . I've been using same theme since 3 years ago. Is there some configuration that I could change in the global configuration manually? I need this theme. 


> Hi @jotapardo
> 
> Perhaps the block editor (Gutenberg) is disabled on the theme side ?
> 
> Please try to activate the default theme such as "Twenty Twenty Two" or "Twenty Twenty One".
> 
> Also, Gutenberg is included in WordPress itself, so please diactivate the Gutenberg plugin if you do not need to try the latest features.

**Comment by jotapardo** [comment] 2022-03-15 03:07
I posted an additional answer here. https://stackoverflow.com/questions/71473889/how-to-force-to-use-gutenberg-in-worpress-after-install-uninstall-clasic-editor/71474039#71474039.

Solution 1: `add_filter('use_block_editor_for_post', '__return_true', 999);` [_current theme_/functions.php]
Solution 2: Find the function `use_block_editor_for_post` and add `return true;` [wp-admin/includes/post.php]

**Comment by jotapardo** [comment] 2022-03-15 03:17
I want to add something... I know that I am not finding the real error. I just forced the specific function to use Gutenberg (which is my urgency). So, I could add some console.log or similar to identify the real problem, but my theme definitely worked every time.

Something is happening here
![image](https://user-images.githubusercontent.com/24879714/158299122-0b1acf71-4594-40f9-b3ba-82a34e81e0cc.png)

**Comment by t-hamano** [comment] 2022-03-15 03:37
First, I recommend switching to another theme to ensure that it is indeed the theme that is preventing gutenberg from being enabled.

If the problem is resolved, as this will indicate that the problem is with the theme not gutenberg, so you may want to check with the theme developer or the theme's forum,

**Comment by t-hamano** [comment] 2022-07-18 04:59
Hi @jotapardo,

Has your problem been resolved since then?
I believe the problem is due to the theme or your own customization, so I will close it once.

If you revert to the default theme or settings and still reproduce the problem, please feel free to reopen.

**Closed as completed by t-hamano** 2022-07-18 04:59 UTC
Labels: [Type] Question

**Comment by jotapardo** [comment] 2022-07-18 19:25
> First, I recommend switching to another theme to ensure that it is indeed the theme that is preventing gutenberg from being enabled.
> 
> If the problem is resolved, as this will indicate that the problem is with the theme not gutenberg, so you may want to check with the theme developer or the theme's forum,

I tested with Twenty Twenty Two, also same problem. I fixed as I mentioned when I just forced the specific function to use Gutenberg. Thank you.
