### ISSUE TITLE
Reusable Blocks Add New creates drafts that can't be deleted

### ISSUE THREAD

**Issue by BlogAid** [WordPress/gutenberg#21708] opened 2020-04-18 17:07 UTC
**Describe the bug**
The only way to get to the Manage All Reusable Blocks list is to first open a page or post.

From that page, if you then go to Add Block > Reusable Blocks > Manage All Reusable Blocks and click the Add New button, it will bring up a new, reusable block editor page. 

That new editor page will be saved as a Draft in the Reusable Blocks list.

It cannot be deleted.

It will not show up in your Pages list.

**Expected behavior**
We need a way to get to Manage All Reusable Blocks without first opening a post or page. Some folks don't want to create a Reusable Block on the fly in a post/page they intend to publish. The only way we can safely do it now is to create a page, create the reusable block, and then save that page as a draft. We then have a page in our Pages list and then the block in the Reusable Blocks list.

We need a way to delete the Draft that appears in the Reusable Blocks list if we used the Add New button method above to create the reusable block.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? native block editor, no Gute plugin

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox and Chrome

**Comment by talldan** [comment] 2020-04-20 07:59
Hi @BlogAid. Thanks for creating the issue. There are already a couple of similar issues:
- https://github.com/WordPress/gutenberg/issues/20557
- https://github.com/WordPress/gutenberg/issues/20551

#20557 seems the most relevant. I'll close this issue as a duplicate of that one.

**Comment by BlogAid** [comment] 2020-04-20 12:20
Neither of the other two mention drafts that can't be deleted, so not quite
a duplicate issue.

**Comment by talldan** [comment] 2020-04-21 10:07
Apologies, I see what you mean now. Even after trashing and permanently deleting the draft reusable block it stays in the list of blocks.

**Comment by jordesign** [comment] 2023-10-30 11:42
If I now create a Synced Pattern and it remains as a draft - I no longer see it in the inserter at all. It can also be deleted from /wp-admin/edit.php?post_type=wp_block which is accessed viaSite Editor > Patterns.

Closing this as no longer reproducible.

**Closed by jordesign** 2023-10-30 11:42 UTC
Labels: [Type] Bug, [Feature] Synced Patterns, [Block] Block
