### ISSUE TITLE
Query loop Block problem with featured post in WordPress 5.8

### ISSUE THREAD

**Issue by NicoHood** [WordPress/gutenberg#35251] opened 2021-09-30 10:31 UTC
### Description

I have a query loop block set to 3 entries and one block post that is featured. The featured post will not be displayed in the block preview, but on the site. It results in 4(!) entries, not 3, break the complete layout

### Step-by-step reproduction instructions

1. Creat4 Blog posts of which one is featured
2. Create a query loop and enable featured posts
3. You will not see the featured post in the preview, but on the published site.

### Environment info

- wordpress 5.8
- gutenberg stable of wordpress 5.8
- firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2021-10-04 20:07
I can replicate this with WordPress 5.8.1 and Gutenberg 11.6. In this case, I made the "Pattern Skate Park" post a sticky post and set the query loop block to show 3 items + include sticky posts: 

Front end view: 
<img width="1268" alt="Screen Shot 2021-10-04 at 4 06 24 PM" src="https://user-images.githubusercontent.com/26996883/135917221-d89c3655-6608-488d-b8fe-6c0507ae4bfa.png">

Editor view: 
<img width="1273" alt="Screen Shot 2021-10-04 at 4 06 21 PM" src="https://user-images.githubusercontent.com/26996883/135917213-a8861890-b997-48f4-91fa-025cb545e96b.png">

**Comment by carolinan** [comment] 2021-10-05 07:55
This replicates the existing behavior for a [standard PHP query loop](https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters/) without using blocks.

If you go to the WordPress admin area and open Settings > Reading and select "Blog pages show at most 3 posts", then a standard loop will show 3 posts and the sticky posts.
It is working as intended but it could be described better.

**Comment by ntsekouras** [comment] 2021-10-05 08:17
>This replicates the existing behavior for a standard PHP query loop without using blocks.

That's correct and you can set `Sticky posts` to `exclude` for your use case and your `Query Loop` that is intended for simple posts will be shown as expected.

>It is working as intended but it could be described better.

I guess this is something we could improve - the `Sticky posts` setting description..

**Comment by NicoHood** [comment] 2021-10-05 08:22
I dont understand your comment. I do not want to exclude sticky posts. I want to include them, but have at maximum 3 posts -  a common usecase. There is no scenario I can think of where it would make sense to add an (unknown) number of sticky posts to the list. That would disrupt all kind of layouts.

**Comment by carolinan** [comment] 2021-10-05 09:06
If you want to show 2 standard posts and have one sticky post, set the number of posts to two. This will show 3 posts.
If you have more than one sticky posts, then you need to change the number again.

**Comment by NicoHood** [comment] 2021-10-05 19:21
That is super wonky! Why would somebody do that?

I want to show 3 Posts on my main site. Not 4, not 2. No Matter if they are featured or not. If there are multiple featured, then there are no "normal" posts and vice versa. Every other solution would break the layout, I dont see why people would want to break their layout? And even if that solution is desired, how can I limit the sticky posts? There is no such option. Makes no sense to me.

**Comment by carolinan** [comment] 2021-10-06 06:09
There has been discussions about this in the past, and I tried to find the old tickets, here is the most recent one:
https://core.trac.wordpress.org/ticket/50989

Either way, it is not a problem with the block, (even if the UI is not great), but with WordPress core.

**Comment by NicoHood** [comment] 2021-10-06 06:43
Thanks for sharing! I've added a comment there. Hope to see a solution...

**Comment by annezazu** [comment] 2024-03-29 18:58
Closing this out as it matches a Core ticket :)

**Closed as completed by annezazu** 2024-03-29 18:58 UTC
Labels: [Type] WP Core Ticket, [Block] Query Loop
