### ISSUE TITLE
Floated blocks cause visual overlay issues

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7500] opened 2018-06-22 20:01 UTC
If you float a block the adding and suggested blocks doesn't always clear:

![2018-06-22 at 20 56](https://user-images.githubusercontent.com/253067/41796590-161f8f26-765f-11e8-8e7b-db40c37606b7.png)

If you align to the right you get the suggested blocks vanishing:

![2018-06-22 at 20 59](https://user-images.githubusercontent.com/253067/41796633-3b88082e-765f-11e8-8514-7016d24cacbd.png)

This can even cause z-index issues like this:

![2018-06-22 at 21 00](https://user-images.githubusercontent.com/253067/41796649-49370218-765f-11e8-8bbc-8d04d53bd034.png)

I think if it's aligning we maybe need to not have suggested blocks, but open other ideas.

**Comment by talldan** [comment] 2018-07-09 04:14
I've had a quick look into this issue and the related issues. It's best illustrated by an image floated either left or right with paragraph text flowing around it. In this case both the image and the next paragraph blocks have overlapping controls:
![screen shot 2018-07-09 at 11 47 33 am](https://user-images.githubusercontent.com/677833/42429834-2c65f2b8-836e-11e8-9f24-a01a0ae922ef.png)

My first thought was that the UI for the blocks could appear in columns, a bit like this:
![screen shot 2018-07-09 at 12 09 45 pm](https://user-images.githubusercontent.com/677833/42430338-2fa7e744-8371-11e8-8e82-c4482fe63f83.png)

Unfortunately, the paragraph blocks have no way of knowing that they're flowing alongside a floated element, so it's hard to do anything clever with the way they're displayed. The only solutions I can come up with to determine whether a paragraph is flowing around a floated element are not particularly nice solutions.

Because of that, I think any design solution might have to focus on changing the way the UI for the floated element appears - i.e. moving it so that it doesn't overlap.

**Comment by karmatosed** [comment] 2018-07-09 21:37
> Because of that, I think any design solution might have to focus on changing the way the UI for the floated element appears - i.e. moving it so that it doesn't overlap.

Do you have an idea of what that could look like? Just as a rough concept?

**Comment by talldan** [comment] 2018-07-10 09:14
The main issue is with the controls at the sides of blocks (block settings ellipsis icon and block mover icons), since they overlap when you have two blocks side by side and they're quite important.

The easiest thing I can come up with (without being too drastic) is to make sure they don't overlap for floated elements by making them slightly inset. Here's a really crude example:
![floated-block-controls](https://user-images.githubusercontent.com/677833/42499053-64ccfe4c-8460-11e8-9945-3d19947fd1da.gif)

I don't completely like that solution - for a start the image block doesn't seem like the first block on the page because the mover icons are visually to the right of the paragraph's mover icons. But it probably is an improvement at least.

As a side note - there are a couple of technical things that could be improved around floated blocks:
- left and right floated blocks are a div with a floated div inside it. At the moment the height of the outer div collapses to zero, which causes a bunch of issues. I think the outer div should be the one with the float applied.
- There are z-index issues. Floated blocks aren't always on top of neighbouring full-width blocks in terms of z-index, making them hard to select.

**Comment by designsimply** [comment] 2018-07-10 19:35
Closed https://github.com/WordPress/gutenberg/issues/7848 as a duplicate.

**Comment by karmatosed** [comment] 2018-07-15 09:58
Noting this isn't just the image block: https://github.com/WordPress/gutenberg/issues/6288

**Comment by karmatosed** [comment] 2018-07-15 09:59
Another one to consider in this is what happens on the bottom with overlaps and lack of clearing: https://github.com/WordPress/gutenberg/issues/6490

**Comment by talldan** [comment] 2018-07-16 05:04
@SuperGeniusZeb - I quite like the redesign in #6224, but not sure it solves the issue, unless the controls were only visible when the block is selected and they were made to sit over the top of the floated element. Here's a quick sketch showing how things would overlap:
![screen shot 2018-07-16 at 12 56 22 pm](https://user-images.githubusercontent.com/677833/42743598-f99d0e5e-88f7-11e8-859a-f059c0ec0bee.png)

One other side effect of the block controls being at the bottom is that you end up with bigger gaps between paragraphs.

**Comment by SuperGeniusZeb** [comment] 2018-07-16 05:16
@talldan The block controls would not take up space on hover (just like they and the block toolbar do not take up space now), and as far as I can tell it is not even decided yet if they would take up space on a selected block. And of course, the controls would only be shown for blocks that are either selected or being hovered over. The standard distance between blocks should be unaffected by the change; only the selected block may be affected.

**Comment by designsimply** [comment] 2018-08-01 14:46
Closed #8355 to consolidate here because it's a concern about how to move floated blocks and the z-index issues mentioned here are closely related. Note that the concern in #8355 is more specifically about how to grab a floated block with the mouse and drag it to another location within the document.

**Comment by jasmussen** [comment] 2018-10-29 08:31
Closing this one as fixed:

<img width="777" alt="screenshot 2018-10-29 at 09 30 08" src="https://user-images.githubusercontent.com/1204802/47637861-4623e880-db5d-11e8-9ed0-9312cc971afb.png">

It's not yet a perfect experience, but it's better to close this one and either reopen or revisit if/when the issue surfaces again.

**Closed by jasmussen** 2018-10-29 08:31 UTC
Labels: UI Components, [Type] Enhancement

**Comment by omrllm** [comment] 2018-12-19 10:16
In some articles the plugins floats on top of the editor block itself, like with the image problem here.
The image is taken on mobile.

![image](https://user-images.githubusercontent.com/45340167/50213990-79297200-037f-11e9-97a8-363131d116dc.png)

**Comment by omrllm** [comment] 2018-12-19 11:44
Alright, it's WD YouTube by WebDorado.

**Comment by jasmussen** [comment] 2018-12-19 12:38
Thanks so much @omrllm, I can confirm that I can reproduce it with that plugin also. It's because it outputs a JavaScript tag before the doctype, causing the editor to render in quirks mode:

![screenshot 2018-12-19 at 13 37 05](https://user-images.githubusercontent.com/1204802/50220676-48533800-0393-11e9-8158-deef2db26612.png)

I'll reach out to them and suggest a fix. Thanks!

**Comment by omrllm** [comment] 2018-12-19 12:52
Happy to help :+1: 

> I'll reach out to them and suggest a fix.

Sweet :smiley:
