### ISSUE TITLE
Instagram block embeds not displaying on front end.

### ISSUE THREAD

**Issue by joshuaiz** [WordPress/gutenberg#14351] opened 2019-03-09 00:12 UTC
**Describe the bug**
Gutenberg Instagram embed block not displaying on front end in our starter theme [Plate](https://github.com/joshuaiz/plate).

**To Reproduce**
1. Install [Plate](https://github.com/joshuaiz/plate) theme.
2. Activate in `Appearance > Themes`
3. Create Post + add Instagram Block. 
4. Add Instagram embed URL. We are using this for testing: https://www.instagram.com/p/BnOcZz1l_T9/
5. Save Post.
6. View on front end: the Plate theme just shows the link without embedding. The Instagram `iframe` is never loaded.

**Expected behavior**
Instagram post should display on the front end.

**Screenshots**
Gutenberg editor (back end):
<img width="774" alt="Screen Shot 2019-03-07 at 1 32 21 PM" src="https://user-images.githubusercontent.com/1096738/54062478-d5a46c80-41cb-11e9-8791-ab076d0bfe0f.png">

Front end:
<img width="732" alt="Screen Shot 2019-03-07 at 1 32 11 PM" src="https://user-images.githubusercontent.com/1096738/54062482-e1902e80-41cb-11e9-96ae-dd8b23011567.png">

**Desktop (please complete the following information):**
 - macOS 10.14.3 (Mojave)
 - tested in Chrome Version 72.0.3626.121 + Safari Version 12.0.3 (14606.4.5)
 - Plate v 1.4.0

**Additional context**
- WordPress 5.1
- no other plugins installed
- Using Local by Flywheel but also tested on live server (same behavior)
- no JavaScript errors in the back end or on the front end
- AdBlockers off

Originally posted here (I know now it was the wrong place): https://github.com/Automattic/wp-calypso/issues/30837

Plate is our starter theme and is used on thousands of projects so we'd like to get this working as we have had some support requests to fix this.

As per the suggestion in the above thread, I fired up two installs side-by-side, one with the WP default twentynineteen thread and the other with Plate, both with identical Posts with the Instagram block using the url posted above.

From there, I went through both themes with Chrome Dev Tools to see if Plate was not enqueuing any scripts that were in twentynineteen. I could not find anything missing in Plate. 

Additionally,  all the recommended `add_theme_support()` functions are included in Plate and every other default block from Gutenberg works except Instagram. That there are no errors makes this incredibly hard to troubleshoot.

After that I tried the following:
- turned off *all* enqueues from the Plate theme: jQuery, Modernizr, additional scripts, styles
- added `wp-embed.js` manually to Plate
- went through all of Plate's css to see if there was anything preventing the embed

^^ none of the above had any effect.

Really stumped as to what is causing the Instagram block not to work on the front end. If someone could download and install the Plate theme and try to figure out what is missing or blocking the embed, I'd be eternally grateful. Not sure what to try next.

**Comment by jlapitan** [comment] 2019-03-24 05:41
Can you try installing Query monitor to have more details on front end issue?

**Comment by joshuaiz** [comment] 2019-03-24 18:21
Hi @jlapitan will do. Give me a couple days to report back. Thanks for the follow-up.

**Comment by joshuaiz** [comment] 2019-03-28 05:13
Ok @jlapitan I have Query Monitor installed but as I mentioned there are no errors with Plate in the front or back end so what should I be looking for?

**Comment by jlapitan** [comment] 2019-03-28 06:51
@joshuaiz can you check http api calls?

**Comment by joshuaiz** [comment] 2019-04-06 04:43
Hey @jlapitan - my wife and I had a baby on early Monday morning so sorry for the delay (everyone is doing great).

When I check the Instagram Block post referenced with QM I'm getting 'No HTTP API calls'. If there's supposed to be one, it's not firing.

Anything else to check? Thanks!

**Comment by thadley** [comment] 2019-04-15 19:01
We are having this issue as well. In our case it appears that wordpress is stripping out the instagram embed script `<script async src="//www.instagram.com/embed.js"></script>` which is causing it not to show on the frontend.

**Comment by djrekd** [comment] 2019-05-15 20:15
I'm running into the same issue & I think I may have discovered what's happening here, I stumbled across this in the Wordpress documentation, under: https://en.support.wordpress.com/code/ 

> Flash and Other Embeds
Flash and other types of embed that use the following are not allowed on WordPress.com sites using Premium and below plans:
 frame
 iframe
form
input
object
textarea

> For security reasons, we remove the tags needed for these to work. Your intentions may be innocent, but someone somewhere might try to use such embeds to damage the site, affecting all of our users.

> There are several safe ways to post Videos, Audio, and other items to your WordPress.com site. In addition, the Embedding content page lists the various types of embeds that are allowed.

Hope this is helpful

**Comment by gziolo** [comment] 2019-05-24 08:11
I couldn't reproduce on my local WordPress and using my account on WordPress.com.

**Comment by joshuaiz** [comment] 2019-05-24 19:06
The original issue still stands. Instagram block embeds are not working in our theme and we cannot figure out why.

**Comment by sndrgb** [comment] 2019-06-11 12:55
Having the same problem.

I try to fix it removing instagram.com/embed.js under each post and append it at the end of the dom:
```
		add_filter('wp_footer', function() {
			if (apply_filters('has_instagram_embed', false)) : ?>
					<script async defer src="//www.instagram.com/embed.js"></script>
			<?php
			endif;
			}, 999);

```

**Comment by joshuaiz** [comment] 2019-06-11 16:20
@sndrgb How are you *removing* `instagram.com/embed.js` from each post?

I tried using your function as well as adding the Instagram `embed.js` directly in the header and the Instagram Gutenberg block still won't display the image on the front end.

**Comment by sndrgb** [comment] 2019-06-15 19:52
Ok guys I understand something
I read about this article https://stallion-theme.co.uk/understanding-wordpress-oembed-and-unknown-postmeta-entries/ and I saw a lot of {{unknown}} tables inside my database

**Comment by sndrgb** [comment] 2019-06-16 16:21
I try to delete {{unknown}} tables and regenerate instagram posts from some posts. But after some time everything come back. I think there's a cache script fro oemebeds in embed.php?

**Comment by youknowriad** [comment] 2019-08-19 14:18
I'm going to close this issue right now because we can't reproduce here and based on some comments, it seems that it could be related to these {{unknown}} entries in the database or other conflicts.

**Closed by youknowriad** 2019-08-19 14:18 UTC
Labels: [Type] Help Request, [Type] Plugin Interoperability

**Comment by joshuaiz** [comment] 2019-08-19 14:42
@youknowriad as the original poster this is *not* related to extraneous db tables and the issue is still outstanding. We'd like to get this resolved so I would ask that you unclose it.

**Comment by youknowriad** [comment] 2019-08-19 15:15
In my testing it's your custom "$content_width = '100%';" in your functions.php that is breaking the instagram embeds. I don't know exactly why though. I'm not sure $content_width accepts percentage.

**Comment by joshuaiz** [comment] 2019-08-19 15:51
Ok cool...let me give that a go - I'll report back in a bit. 

Really that's only there for Theme Check so I'm ok with removing it.

**Comment by joshuaiz** [comment] 2019-08-19 18:39
Removing the `$content_width = '100%';` does solve this. So yes you can now close. Thanks for the info!
