### ISSUE TITLE
Navigation elements should be movable by drag and drop (and with buttons)

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#19357] opened 2019-12-28 10:16 UTC
## Background
@mapk had [asked me to open a new idea](https://github.com/WordPress/gutenberg/issues/15558#issuecomment-569352531). The discussion had taken place [here](https://github.com/WordPress/gutenberg/issues/15558). To better separate the two issues, I'll open a new issue or feature request. I hope this fits and I don't open a duplicate.

## Is your feature request related to a problem? Please describe.
Complex designs are very difficult to create. The breadcrumbs are very helpful. But what if you have a block at the bottom of your post and you want to put it in a column at the top? This is currently very difficult and complex.

## Describe the solution you'd like
The navigation elements can be moved by drag and drop as well as arrows up and down.
![1SNAG-0000](https://user-images.githubusercontent.com/9355398/71542188-6d459800-2963-11ea-80cd-14b7c749f420.png)

### Exampel:
Ok, let's assume we want to insert the last block of the content from https://wordpress.org/gutenberg/ into a column:
![1](https://user-images.githubusercontent.com/9355398/59273369-5bff9d00-8c58-11e9-95a3-731ceab2e1e8.png)

Then these would be the work steps:
![lolHNU6RGl](https://user-images.githubusercontent.com/9355398/59273412-79cd0200-8c58-11e9-9322-cc794a7b6563.gif)

**Conclusion:** 
I have to be very careful with the mouse. This is quite difficult to move this block to a position far away. Especially if you're talking about very complex blocks: Paragraph in a column and this one is in a group.

### How could that be simplified?

**Idea:** 
It should be possible to move the elements in the navigator.

**Example:**
Elementor does that quite well:
![YcdGVSQ32I](https://user-images.githubusercontent.com/9355398/59274157-0f1cc600-8c5a-11e9-925e-0953a80d76ba.gif)

![DuxaszJQVV](https://user-images.githubusercontent.com/9355398/59274345-75a1e400-8c5a-11e9-823c-caf5305f9b91.gif)

Isn't that cool? I need a fraction of the time to do the same thing...

And the amazing thing is: you can move whole sections/group with their contents. This is currently difficult to do with GP or I as an end user just don't understand how to do it better :-)

The reference by @jasmussen should also be considered:
> As a meta-answer: drag and drop are fine interactions to think about, so long as they are made as enhancements on top of explicit buttons or actions that are both mouse and keyboard accessible. Or to frame it differently, drag and drop can never be the only way to accomplish an action, it has to be an additional method.

**Comment by mapk** [comment] 2019-12-30 17:46
I love the idea of being able to drag around items in the Block Navigator, or even use "up" and "down" arrows to move them within the popover. These feel like strong solutions to the problem of moving blocks over a long space.

In relation to this, we've explored some ideas around combining the Block Navigator and Doc Outline as well in https://github.com/WordPress/gutenberg/pull/14956.

If we move that old PR forward, we might also be able to add this as another PR on top of that one. @youknowriad your thoughts?

**Comment by SchneiderSam** [comment] 2019-12-31 07:42
@mapk It's kind of totally cool that you liked my idea. :-P

> In relation to this, we've explored some ideas around combining the Block Navigator and Doc Outline as well in #14956.

How cool is that? The combination of the two ideas or concepts would be a BIIIIIIIIIIIIG UX improvement. By the way, many design programs like the Adobe series or Affinity have this. The layers can be arranged in any order. A big relief.
![2](https://user-images.githubusercontent.com/9355398/71613938-3d87d180-2ba9-11ea-9fd6-a3724537c1f5.gif)


And if you want to take it all to the limit, you can even be inspired by it. But that's very huuuuuuge:
![move-layers-photoshop-script](https://user-images.githubusercontent.com/9355398/71613941-44164900-2ba9-11ea-8d42-d8cb322204ee.gif)

**Comment by mtias** [comment] 2020-01-03 10:57
Flagging as duplicate of #11408 and work has already started in #18014.

**Comment by mapk** [comment] 2020-01-03 22:49
Ha! I thought I'd seen that before. Thanks! I'll close this out since #18014 is already underway.

**Comment by mapk** [comment] 2020-01-04 00:31
Reexamining that PR, it looks like the work directly effects the Navigator from within the Nav block. [This comment](https://github.com/WordPress/gutenberg/pull/18014#issuecomment-546297111) does suggest that we add this to the Top Toolbar Navigator, so maybe we leave this issue open until that is merged.

**Comment by mtias** [comment] 2020-01-04 12:23
I meant the duplicate issue is #11408, which covers the wide case for the main navigator.

**Closed by mtias** 2020-01-04 12:23 UTC
Labels: Needs Design, [Feature] Block Navigation, [Type] Enhancement
