### ISSUE TITLE
odd UX: Links require clicking "apply" before they are saved

### ISSUE THREAD

**Issue by kathrinchen** [WordPress/gutenberg#9867] opened 2018-09-13 12:06 UTC
When I use Gutenberg, which I really like, it comes to the point, that I want to link to other pages of my blog.

When I used the classic editor, I was able to open a small window, in which I could search my already published pages by entering a search word.

I would be very pleased, if it could be possible to invent such a function to Gutenberg.

Thanks a lot in advance and pleaseapologize my bad English skills.
**

**Comment by mtias** [comment] 2018-09-13 12:50
It's already part of Gutenberg. Did you try typing in the link box one of your other pages?

![image](https://user-images.githubusercontent.com/548849/45489277-2af34a00-b764-11e8-83ad-71a648c8cc92.png)

**Comment by kathrinchen** [comment] 2018-09-13 12:57
Thank you for your answer.
Yes I tried so, but it doesn‘t work.

**Comment by tofumatt** [comment] 2018-09-13 14:26
I think this might be a bit of a UX issue, because I tried to record a video of how to apply a link and thought I found a bug myself. The issue is you need to click the "apply" button to add it, but I really didn't expect that:

![2018-09-13 15 23 58](https://user-images.githubusercontent.com/90871/45494564-3e54e400-b769-11e8-8c3b-107ed6984348.gif)

I thought the link would be applied there. I think it should 🤷‍♂️

@kathrinchen: for now, can you try adding the link and then clicking the "Apply" button next to the link URL? Here's a video of the process:

![2018-09-13 15 24 22](https://user-images.githubusercontent.com/90871/45494619-5af11c00-b769-11e8-9cbb-6e929afd8174.gif)

------

Why do we make users click "apply" here? I think that's unhelpful 🤷‍♂️

**Comment by kathrinchen** [comment] 2018-09-13 14:35
That‘s absolutely strange to me - but 2 hours ago, there appareared no dropdown menu with links, when I typed something in the field.

But now it does - and it works!

Thank you so much!

**Comment by tofumatt** [comment] 2018-09-13 14:41
Not a problem! Maybe it was just a spotty connection–there isn't a lot of visual feedback that it will autocomplete, it's something we could work on.

Glad it's working now, and thanks for letting us know you're liking Gutenberg 😄. If you spot any other issues please let us know!

**Comment by iseulde** [comment] 2019-01-29 14:49
Any actionable items here?

**Comment by designsimply** [comment] 2019-02-01 00:20
Closing because I couldn't find anything actionable since https://github.com/WordPress/gutenberg/issues/9867#issuecomment-421029758 mentions the problem went away.

**Closed by designsimply** 2019-02-01 00:20 UTC
Labels: [Package] Format library, [Type] Enhancement
