### ISSUE TITLE
Navigation: Two rows with nav links. Add submenu. Hover submenu. 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21454] opened 2020-04-07 11:37 UTC
**Describe the bug**
Two rows of menu links. Add a dash of submenu. Stir (hover link with submenu) and see the results.

![Screen Shot 2020-04-07 at 13 29 11](https://user-images.githubusercontent.com/5323259/78664396-3b35c180-78d4-11ea-8f6f-0fda14925784.png)

**To reproduce**
1. In Twenty Twenty. Add a menu containing links so that two rows are created.
2. Add a submenu to one of the nav links in the first row.
3. Hover over the link with the submenu.
4. See error.

**Expected behavior**
I did not expect to see a mix of submenu and the nav link below. But to have a clear z-index to where the submenu is on top of the row 2 nav item.

Chrome
Twenty Twenty
Desktop Server.

**Comment by paaljoachim** [comment] 2020-04-07 11:40
Associated issue: https://github.com/WordPress/gutenberg/issues/21449

**Comment by tellthemachines** [comment] 2020-04-20 02:33
I can reproduce the issue, and it seems to be a regression introduced by #21471. The code removed was:

```
.wp-block-navigation-link:not(.has-background) > .wp-block-navigation__container {	
			background-color: $light-style-sub-menu-background-color;	
		}
```

However, it wasn't working 100% previously, as the default background was hardcoded white:

<img width="545" alt="Screen Shot 2020-04-20 at 11 59 25 am" src="https://user-images.githubusercontent.com/8096000/79707726-c1a0c900-8300-11ea-90a0-33246e2f76bb.png">

I guess we can add in that default again as an interim measure, but this will probably only be fully resolved with the work being done on global styles.

**Comment by talldan** [comment] 2020-04-20 02:38
Closing as a duplicate of #21449

**Closed by talldan** 2020-04-20 02:38 UTC
Labels: CSS Styling, [Block] Navigation, [Type] Bug
