### ISSUE TITLE
Align-wide enabled for Columns

### ISSUE THREAD

**Issue by nickfmc** [WordPress/gutenberg#28993] opened 2021-02-14 22:58 UTC
## What problem does this address?
I'm constantly manually adding the alignwide class to my columns to get the desired effect. Why would the Columns block not be affected by the add_theme_support( 'align-wide' );  it works perfect for me when I add the class manually.

## What is your proposed solution?
Consider adding the alignwide "alignment" to the Columns block

**Comment by talldan** [comment] 2021-02-15 04:09
@nickfmc I can't reproduce any issues, the option seems to be present:
<img width="630" alt="Screenshot 2021-02-15 at 12 02 56 pm" src="https://user-images.githubusercontent.com/677833/107904174-f794f500-6f85-11eb-82ff-cd0268786a82.png">

I've tested a few different themes. In the code, wide alignments are definitely shown as supported:
https://github.com/WordPress/gutenberg/blob/b2bd065fa0365955b850f7bb6364798b08b1dc24/packages/block-library/src/columns/block.json#L13

I'll close this issue, as it seems to be a problem localised to your WordPress environment. It might be worth reaching out to the forums for support:
https://wordpress.org/support/forums/

**Closed by talldan** 2021-02-15 04:09 UTC
