### ISSUE TITLE
[Bug]: Overtype not working anymore

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#38804] opened 2022-02-15 05:39 UTC
### Description

It appears the overtype feature isn't working anymore, but we have a confirmation from user that it did work in the past(a few months ago).

### Step-by-step reproduction instructions

1. Create a new page/post
2. Add some text on it
3. Try to use INS while on Windows to overwrite the existing content

### Screenshots, screen recording, code snippet

Previous report: https://github.com/WordPress/gutenberg/issues/15675#issuecomment-1036204936

### Environment info

- WordPress 5.9 and Gutenberg 12.5.4
- Windows 11 and Chrome 98

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-08-27 14:10
I believe the root cause of this problem is that the Chronium browser has disabled mode switching with the Insert key.

- May 11, 2021: [Disable toggling of Overwrite mode by-default](https://chromium-review.googlesource.com/c/chromium/src/+/2885319)
- Oct 17, 2020: [Disable toggling of Overwrite mode when insert key is pressed.](https://chromium-review.googlesource.com/c/chromium/src/+/2473771/)

I could not figure out how to change to overwrite mode without using the `insert` key in the browser, but I'm closing this issue because at least it isn't a Gutenberg issue.

**Closed as completed by t-hamano** 2022-08-27 14:10 UTC
Labels: Browser Issues
