### ISSUE TITLE
Cover image provides no indicator where to click for adding text

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6823] opened 2018-05-18 11:03 UTC
**Describe the bug**
After adding a Cover Image block it displays a tiny toolbar on top of the image, however there's no indicator or even a flashing cursor, to show where you're actually supposed to click to insert text, or even that you can actually insert text.

This is just one of the many blocks that are incredibly frustrating to use because of the poor UI and lack of visual indicators!

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a cover image
2. Try and work out where you have to click to add text

**Expected behaviour**
I shouldn't have top spend 5 minutes clicking around on the image to try and find the insertion point so that I can add some text

**Screenshots**
![gutenberg_coverimagenoclickindicator](https://user-images.githubusercontent.com/2078245/40231482-a8eae810-5ade-11e8-94a8-85478618c68e.gif)

_macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)
WordPress 4.9.6
Gutenberg 2.8.0_

**Comment by SuperGeniusZeb** [comment] 2018-05-18 20:01
This issue will likely be resolved by a combination of the Cover Image and Quote blocks being updated to use nested blocks (#5452 and #6520) and block hover improvements (#6773).

**Comment by danielbachhuber** [comment] 2018-05-18 21:09
> This issue will likely be resolved by a combination of the Cover Image and Quote blocks being updated to use nested blocks

Cool. Let's keep this issue open until we can confirm the problem is addressed.

**Comment by johngodley** [comment] 2018-10-31 15:36
Circling back on this, the current cover image block behaviour is that it now shows a placeholder indicating there's a clickable part:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47799430-27bb1a00-dd22-11e8-85de-82ec711db7ef.jpg)

The toolbar only appears when clicked:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/47799463-386b9000-dd22-11e8-972d-8134b6c07656.jpg)

I think this resolves the original issue?

**Comment by maddisondesigns** [comment] 2018-11-01 03:02
@johngodley That's working better now that there's placeholder text.

**Comment by johngodley** [comment] 2018-11-01 07:32
Great, thanks. Closing as resolved.

**Closed by johngodley** 2018-11-01 07:32 UTC
Labels: Blocks, Priority Low, [Type] Bug
