### ISSUE TITLE
Global Styles: Switching styles takes a while on the frontend

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#43914] opened 2022-09-06 14:00 UTC
Switching to an alternate style variation, inside the editor, is instant. Click one of the tiles and the visual is shown immediately:

<img width="367" alt="Screenshot 2022-09-06 at 15 57 52" src="https://user-images.githubusercontent.com/1204802/188654411-8155082d-7574-4bee-ab38-16f9e3201ade.png">

If you then save the changes and preview the site frontend, however, the styles take a while to settle in. The following GIF shows changing a style, opening the frontend in a new tab, and then reloading the page over and over to see what takes:
![styles](https://user-images.githubusercontent.com/1204802/188654600-3bfe85ab-aaa9-4756-8826-c912189d15de.gif)

Note that the typography and a few of the style changes are immediately shown. But things like background colors take a while, up to several minutes. Clearing the cache doesn't make any difference. 

Steps to reproduce:

* Use a block theme, such as TT3 or TT2
* Go to the site editor
* Switch to a different style variation (Click global styles > Browse styles > Pick one). Save the changes.
* Click view > View site. Note that the new styles aren't applied immediately. Wait up to several minutes to reload. Eventually the whole style is applied.

Tested in Chrome on Mac.

**Comment by jasmussen** [comment] 2022-09-06 15:56
Just to confirm, this is running latest trunk Gutenberg and TT3.

**Comment by Mamaduka** [comment] 2022-09-06 16:28
Probably a duplicate of #43395, or the cause might be the same.

**Comment by jasmussen** [comment] 2022-09-06 18:03
Excellent, thank you!

Closing in favor of #43395.

**Comment by jasmussen** [comment] 2022-10-04 10:27
Reopening as this issue does appear to be separate from #43395 after all.

**Comment by Mamaduka** [comment] 2022-11-08 12:52
The improvements proposed by @spacedmonkey in [#56910](https://core.trac.wordpress.org/ticket/56910) will also fix this issue.

The missing cache invalidation for `wp_get_global_stylesheet` is the cause of this problem.

**Comment by Mamaduka** [comment] 2022-11-09 08:59
@jasmussen, I'm thinking of bumping this issue to WP 6.2.

The problem has been around since WP 6.0, and I think we both prefer to solve it with better cache invalidation proposed in [#56910](https://core.trac.wordpress.org/ticket/56910).

**Comment by jasmussen** [comment] 2022-11-09 09:11
No objections from my part. It's a good one to fix, but definitely let's do it right.

**Comment by oandregal** [comment] 2022-11-11 15:10
@mmtr has a PR that fixes this at https://github.com/WordPress/gutenberg/pull/45679 

There's an issue with the test but we're looking at fixing that the next week (not in time for 6.1.1).

**Closed as completed** 2022-11-22 16:19 UTC
Labels: [Type] Bug, Global Styles
