### ISSUE TITLE
Cover block: Can not set repeated background image with gradient overlay

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#39108] opened 2022-02-27 13:12 UTC
### Description

It seems to be impossible to set Cover block with repeated transparent PNG image on background positioned `50% 0` and overlaid with a gradient.

### Step-by-step reproduction instructions

1. Create a Cover block in a page and set it with these:
  - **Media settings**:
    - repeated background,
    - set [this background image](https://user-images.githubusercontent.com/2456735/155883638-7cf676a6-fbb1-456a-8b2b-094031ffd8d2.png),
    - background position: Left = 50%, Right = 0.
  - **Overlay**:
    - Opacity = 100,
    - Linear gradient from `#d1e4dd` to `#d1e3dce0` (`rgba(209, 227, 220, 0.88)`), angle 0°.
2. Compare the result with [expectations seen in the screenshot](https://user-images.githubusercontent.com/2456735/155883603-26ade0de-1583-4e6c-add6-1b183299eaff.png) below:
  - The image can not be seen as the circles in PNG background image are semi transparent black and the Cover block background color is black as set by Cover block default styles.
  - The position of the image is set to `50%` in Cover block default styles and custom position from block settings is not honored.

### Screenshots, screen recording, code snippet

![cover block issue](https://user-images.githubusercontent.com/2456735/155883603-26ade0de-1583-4e6c-add6-1b183299eaff.png)

### Environment info

- WordPress 5.9.1
- Twenty Twenty-One 1.5
- Background image used: [download the image](https://user-images.githubusercontent.com/2456735/155883638-7cf676a6-fbb1-456a-8b2b-094031ffd8d2.png)
 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by matiasbenedetto** [comment] 2022-05-27 19:28
I'm not able to reproduce this using the latest trunk version of Gutenberg. Seems to be fixed with the latest Cover Block changes regarding fixed and repeated backgrounds.

**Comment by webmandesign** [comment] 2022-07-13 02:30
The issue still persist for me. Using WP 6.0.1 and Twenty Twenty-One 1.6.

**Comment by jordesign** [comment] 2023-08-29 01:40
I'm no longer able to recreate this in WP6.3

**Closed as completed by jordesign** 2023-08-29 01:40 UTC
Labels: [Type] Bug, [Block] Cover
