### ISSUE TITLE
Widget Editor: Undo should not be clickable if nothing has been done yet

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26124] opened 2020-10-14 19:32 UTC
As reported by @garretthyder, [here](https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40042), the Undo button should not be clickable if nothing has been done yet.

![undo](https://user-images.githubusercontent.com/617986/96036333-2acd4900-0e19-11eb-9a15-3a563a9b8432.gif)

**Comment by talldan** [comment] 2020-10-15 09:22
Duplicate of #26073.

**Closed by talldan** 2020-10-15 09:22 UTC
Labels: Needs Dev, [Feature] Widgets Screen, [Type] Bug
