### ISSUE TITLE
TypeError for extending block attempt

### ISSUE THREAD

**Issue by robbisy** [WordPress/gutenberg#5955] opened 2018-04-03 16:13 UTC
## Issue Overview

I try to add a select control to all blocks. This select controls allows to add class (class1, class2, class3) to each blocks. but the problem is that when I publish and reload my page I get 
```
Block validation: Block validation failed because an error occurred while generating block content:

TypeError: a is not a function
index.js:11:8783
Block validation: Expected  
Object { type: "StartTag", tagName: "p", attributes: [], selfClosing: false }
 , instead saw end of content.
index.js:11:8783
Block validation: Block validation failed for `core/paragraph` ( 
Object { name: "core/paragraph", title: "Paragraph", description: "This is a simple text only block for adding a single paragraph of content.", icon: "editor-paragraph", category: "common", keywords: […], transforms: {…}, deprecated: […], merge: merge(), getEditWrapperProps: getEditWrapperProps(), … }
 ).

Expected:

<p></p>

Actual:

index.js:11:8783
Block validation: Block validation failed because an error occurred while generating block content:

TypeError: a is not a function
index.js:11:8783
Block validation: Expected  
Object { type: "StartTag", tagName: "blockquote", attributes: […], selfClosing: false }
 , instead saw end of content.
index.js:11:8783
Block validation: Block validation failed for `core/quote` ( 
Object { name: "core/quote", title: "Quote", description: "Quote. In quoting others, we cite ourselves. (Julio Cortázar)", icon: "format-quote", category: "common", transforms: {…}, edit: State(r)(), deprecated: […], attributes: {…}, save: save() }
 ).

Expected:

<blockquote class="wp-block-quote blocks-quote-style-1"></blockquote>

Actual:

index.js:11:8783
TypeError
​
columnNumber: 7169
​
fileName: "http://localhost/test/wp-content/plugins/gutenberg-examples/02-esnext/block.build.js?ver=1522526653"
​
lineNumber: 12

​
message: "a is not a function"
```
## Steps to Reproduce (for bugs)

```
/**
 * External dependencies
 */

import  assign  from 'lodash/assign';
import * as classnames from 'classnames';

/**
 * WordPress dependencies
 */

const { __ } = wp.i18n;
const { getWrapperDisplayName,Component } = wp.element;
const { addFilter } = wp.hooks;
const { InspectorControls,hasBlockSupport  } = wp.blocks;
const { SelectControl  } = wp.components;


const linkCss = [
    { value: 'class1', label: __( 'class 1' ) },
    { value: 'class2', label: __( 'class 2' ) },
    { value: 'class3', label: __( 'class 3' ) },
];
/**
 * Filters registered block settings, extending attributes with anchor using ID
 * of the first node.
 *
 * @param {Object} settings Original block settings.
 *
 * @return {Object} Filtered block settings.
 */
function addAttribut( settings ) {
    if ( hasBlockSupport( settings, 'customClassName', true ) ) {
        // Use Lodash's assign to gracefully handle if attributes are undefined
        settings.attributes = assign( settings.attributes, {
            className: {
                type: 'string',
            },
        } );
    }

    return settings;
}

/**
 * Override the default edit UI to include a new block inspector control for
 * assigning the custom class name, if block supports custom class name.
 *
 * @param {function|Component} BlockEdit Original component.
 *
 * @return {string} Wrapped component.
 */

function withInspectorContro( BlockEdit ) {
    
    const WrappedBlockEdit = ( props ) => {
        const hasCustomClassName = hasBlockSupport( props.name, 'customClassName', true ) && props.isSelected;
        
        return [
          <BlockEdit key="block-edit-custom-class-name" { ...props } />,
            hasCustomClassName && <InspectorControls key="inspector-custom-class-name">
                <SelectControl
                    label={ __( 'Additional CSS Class' ) }
                    value={ props.attributes.className || '' }
                    onChange={ ( newclassNames ) => {
                        props.setAttributes( {
                            className: newclassNames,
                        } );
                    } }
                    options={ linkCss }
                />
            </InspectorControls>
           
        ];
    };
    WrappedBlockEdit.displayName = getWrapperDisplayName( BlockEdit, 'customClassName' );

    return WrappedBlockEdit;
}

/**
 * Override props assigned to save component to inject anchor ID, if block
 * supports anchor. This is only applied if the block's save result is an
 * element and not a markup string.
 *
 * @param {Object} extraProps Additional props applied to save element.
 * @param {Object} blockType  Block type.
 * @param {Object} attributes Current block attributes.
 *
 * @return {Object} Filtered props applied to save element.
 */
export function addSaveProp( extraProps, blockType, attributes ) {
    if ( hasBlockSupport( blockType, 'customClassName', true ) && attributes.className ) {
        extraProps.className = classnames( extraProps.className, attributes.className );
    }

    return extraProps;
}

addFilter( 'blocks.registerBlockType', 'core/custom-class-name/attribut', addAttribut );
addFilter( 'blocks.BlockEdit', 'core/custom-class-name/inspector-contro', withInspectorContro );
addFilter( 'blocks.getSaveContent.extraProps', 'core/custom-class-name/save-prop', addSaveProp );
```

**Comment by gziolo** [comment] 2018-04-20 11:04
It works for me:

![screen shot 2018-04-20 at 13 03 25](https://user-images.githubusercontent.com/699132/39047729-42709d4a-449b-11e8-8c36-5f1bf52cdda1.png)

As of today, you will have to remove `getWrapperDisplayName` or replace with `createHigherOrderComponent` as in the example you built your plugin upon: https://github.com/WordPress/gutenberg/blob/master/blocks/hooks/custom-class-name.js#L50.

**Comment by gziolo** [comment] 2018-04-20 11:09
I can't reproduce so closing it for the time being. Feel free to reopen and provide more details if you still can't solve your issue.

**Closed by gziolo** 2018-04-20 11:09 UTC
Labels: Block API, Extensibility, [Type] How Do I?

**Comment by robbisy** [comment] 2018-04-20 21:50
@gziolo Thanks Grzegorz for your help.
Is it possible to do this with data-attributes  in gutenberg ?
I mean create our own data-attribute let say data-gut and change their attributes data-gut ="attribute1"
or data-gut ="attribute2" like we do with class 1, class 2, class 3

**Comment by gziolo** [comment] 2018-04-23 10:43
> @gziolo Thanks Grzegorz for your help.
> Is it possible to do this with data-attributes in gutenberg ?
> I mean create our own data-attribute let say data-gut and change their attributes data-gut ="attribute1"
> or data-gut ="attribute2" like we do with class 1, class 2, class 3

@robbisy you should be able to use `data-*` attributes, too. I don't see why it wouldn't have to work.

**Comment by gziolo** [comment] 2018-04-24 07:31
> t works when i try to add a data-* on the front end
but when I try to have a selected data-* which are display on front end and on editor .
I'm getting this error : `The "save" property must be specified and must be a valid function`

You see the error because you return only `attributes` instead of returning all `settings` in https://gist.github.com/robbisy/6a2071275b8e043293068394c9c9f817#file-gistfile1-txt-L35.
It should be instead:
```js
settings.attributes = assign( settings.attributes, { "data-attribute":  attrNames   }  );
return settings;
```

> For the editor I don't understand why I can get the select value with `const attrNames = attributes.attrName;` and for the editor I guess I had to add my  data-* to settings which from what I understand is the div setting on the editor so I do
> `return settings.attributes = assign( settings.attributes, { "data-attribute":  attrNames   }  );`
> and since you use [settings.attributes](https://github.com/WordPress/gutenberg/blob/master/blocks/hooks/custom-class-name.js#L32) I guess I can use settings to get my selected attributes likes this `const attrNames = settings.attributes.attrName;`

In `addFilter( 'blocks.registerBlockType', 'core/custom-class-name/addattr', addAttr );` you should add `attrName` to the list of the existing attributes to be able to use it inside the Editor in other parts. You try to read its value, but it doesn't exist yet.

**Comment by robbisy** [comment] 2018-04-24 14:42
> In addFilter( 'blocks.registerBlockType', 'core/custom-class-name/addattr', addAttr ); you should add attrName to the list of the existing attributes to be able to use it inside the Editor in other parts.

In the docs I found 
`addFilter( 'hookName', 'functionName', callback, priority )`
There isn't any attributes parameter.
I've test few option like 
`addFilter( 'blocks.registerBlockType', 'core/custom-class-name/addattr', addAttr, attrName  );`
or pass the attributes in the function
```
export function addAttr( settings) {
        attributes: { attrName: { type: 'string' } }
        ....
      } 
```
but no one works 
Where new attributes should be added in the addFilter ?
