### ISSUE TITLE
Add a simple way to add hover style

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#30068] opened 2021-03-21 23:52 UTC
At the moment seems that there's no a simple way to add `hover` pseudo class on buttons.  So the only option is to let theme handle this. But how can someone add different button style with hover effect?

I have tried with `wp_add_inline_style` to my block, without success.

**Comment by carolinan** [comment] 2021-03-23 04:29
Hi, I am closing this as a duplicate of #27075.

**Closed as completed by carolinan** 2021-03-23 04:29 UTC
