### ISSUE TITLE
[Data Views] Manage All Templates: Pagination links not active/clickable after changing results-per-page

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#57839] opened 2024-01-15 01:58 UTC
### Description

When changing the view details to show less per page than the total number of templates (so paging is needed) the actual pagination dropdown and arrow buttons are not clickable until after returning focus to the main panel/frame.

### Step-by-step reproduction instructions

1. Open the Site Editor and go to Templates > Manage all templates
2. Go to the view options button (top right) and change settings to the results shown are _less_ than the total number of templates/
3. Try and use the pagination controls at the bottom of the frame.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/16bac24a-2648-4bbb-91d7-445dbce85721

### Environment info

Found in testing with https://make.wordpress.org/test/2024/01/13/early-opportunities-to-test-wordpress-6-5/

- WP 6.5-alpha-57278
- GB 17.5.0-rc.1
- Twenty Twenty-Four

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2024-02-02 11:44
👋 - Is this still happening for you? I couldn't reproduce it.

**Comment by youknowriad** [comment] 2024-07-12 08:19
I can't reproduce either, closing for now but please reopen and share more details if needed.

**Closed as completed by youknowriad** 2024-07-12 08:19 UTC
Labels: [Type] Bug, [Feature] DataViews
