### ISSUE TITLE
Editor Suggestions

### ISSUE THREAD

**Issue by GhenetPR** [WordPress/gutenberg#8585] opened 2018-08-06 10:16 UTC
I'm trying out the new editor for my blog and I'm running into a lot of problems. There are a few things that would be really helpful: 

Adding headers and justified alignment in text box block. I have tried doing this a number of times as I prefer my pages to be justified, and it turns it into an html block and gives me an error. Allow the text block to be both visual and html edited. 

It would also be helpful to save templates. Once I set up a new post with different blocks where I want them, if I could save them that would be great. I don't see how to do that at the moment which means building posts from scratch every single time. 

More control over certain appearance things. Being able to control spacing around photos for example, when they're side by side in two columns,  

I've used the WP Bakery Page Builder for a while now to do what it seems the new editor is supposed to be able to do, but it's not as smooth. 

Just a little bit of feedback from my attempts to use Gutenberg over the weekend.

**Comment by youknowriad** [comment] 2018-08-06 10:48
Hi there and thanks for the feedback.

> Adding headers and justified alignment in text box block. I have tried doing this a number of times as I prefer my pages to be justified, and it turns it into an html block and gives me an error. Allow the text block to be both visual and html edited.

Duplicate of #8433 

> It would also be helpful to save templates. Once I set up a new post with different blocks where I want them, if I could save them that would be great. I don't see how to do that at the moment which means building posts from scratch every single time.

Yes, this would be a great feature. This is meant to be worked on for V2 (custoomization) See #3588

> More control over certain appearance things. Being able to control spacing around photos for example, when they're side by side in two columns,

I think the idea is that spacing around images etc... is the responsibility of themes but nothing stops you from building blocks with these options built-in. A section block #4900 could potentially have spacing options though. And we already have a columns block to put photos side by side etc...


I'm closing as all these items have corresponding issues. If you have other suggestions, please search for issues to avoid duplicates and create separate issues for each feedback item. Thanks for your help.

**Closed by youknowriad** 2018-08-06 10:48 UTC

**Comment by GhenetPR** [comment] 2018-08-06 11:02
Hi,

I'd just like to clarify a point I was attempting to make. With the last
point I made about spacing - yes the theme does that for me, but when two
blocks are side by side (which I am aware already exists, it's a point
about that particular block that I'm raising) they are flush together. Two
images side by side are flush together with no small space between. Text is
flush against an image in the same manner. With the column block, it would
be nice to be able to adjust that.

Ghenet

ghenetactually.co.uk
Facebook | Ghenet Actually <https://www.facebook.com/ghenetactually/>
Instagram | @ghenetactually <https://www.instagram.com/ghenetactually>
Twitter | @GhenetActually
<https://twitter.com/ghenetactually>

**Comment by youknowriad** [comment] 2018-08-06 11:06
> With the column block, it would be nice to be able to adjust that.

Definitely, I'm pretty sure there's an issue for it. Also the theme should be able to define the spacing for each column.
