### ISSUE TITLE
Group Block ignores nested blocks' width settings

### ISSUE THREAD

**Issue by kavyagokul** [WordPress/gutenberg#44922] opened 2022-10-13 09:31 UTC
### Description

The Group Block seems to ignore the alignment settings for blocks added to the Group Block.

### Step-by-step reproduction instructions

1. Add a Group Block set to full-width
2. Add a Cover Block with a combination of a YouTube Block, Paragraph Blocks, Heading Block, and Spacer Blocks to the Cover Block
3. The Cover Block is set to wide-width
4. When viewed, the Cover Block expands to fill the full width of the Group Block

### Screenshots, screen recording, code snippet

![195087855-e3fd5991-7ef8-40ea-8ae3-303c7790b0dc](https://user-images.githubusercontent.com/1659416/195558906-76edd02e-cea6-4d6e-86e9-684a07ff9345.jpeg)
![195087788-8ef93ff6-b834-4d15-b907-e577e240949f](https://user-images.githubusercontent.com/1659416/195558947-b9482e0f-e11c-4cb8-bc6c-b6cb0f127e0b.jpeg)

### Environment info

- WordPress 6.0.2
- Gutenberg 14.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment] 2022-10-17 04:41
Might be one to look at under https://github.com/WordPress/gutenberg/issues/44720 ?

Do you think this will be addressed by https://github.com/WordPress/gutenberg/pull/43504 @tellthemachines ?

**Comment by tellthemachines** [comment] 2022-10-17 06:07
@kavyagokul thanks for reporting this! I can't reproduce it on trunk with Twenty Twenty Three theme. Can you reproduce it with one of the default themes? If not, it's likely a theme issue.

**Comment by ndiego** [comment] 2022-11-08 15:50
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the Blank Canvas theme and the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.

**Closed as completed by ndiego** 2022-11-08 15:50 UTC
Labels: [Type] Bug, Needs Testing, [Feature] Layout
