### ISSUE TITLE
This page is asking you to confirm that you want to leave

### ISSUE THREAD

**Issue by wpalchemist** [WordPress/gutenberg#3356] opened 2017-11-06 20:35 UTC
## Issue Overview
Every time I navigate away from a post using Gutenberg, I get a JS alert.  In Firefox, the alert says "This page is asking you to confirm that you want to leave - data you have entered may not be saved."  In Chrome, the alert says "Do you want to leave this site? Changes you made may not be saved."

## Steps to Reproduce (for bugs)
1. Create new post
2. Add content to post
3. Click "Publish" or "Update"
4. Click "View post" or any other link on the page
I am using Gutenberg 1.6.1.  This happens on multiple sites, in Firefox and Chrome.  I am using Windows 10.

## Expected Behavior
If I have just saved my content, I should be able to navigate away without being warned that my changes may not be saved.

## Current Behavior
Every time I navigate away from a post, I get a pop-up dialog warning me that my changes may not be saved.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by GlennMartin1** [comment] 2017-11-06 21:07
Duplicate issue: https://github.com/WordPress/gutenberg/issues/3307

**Comment by aduth** [comment] 2017-11-06 21:11
Duplicate of #3296. Should be resolved in the next release.

**Closed by aduth** 2017-11-06 21:11 UTC

**Comment by wpalchemist** [comment] 2017-11-06 21:38
Oh great!  I searched, but couldn't find duplicates.  Thanks!
