### ISSUE TITLE
File block retains href after uploading an unsupported file type causing block to encounter an error after page refresh

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#8155] opened 2018-07-24 02:51 UTC
**Describe the bug**
Refreshing the page after a File Block after an invalid file type has been added results in a block in an erroneous state

Related to umbrella issue #8119, since this happens when the file block edit componentDidMount and triggers particular transitions in state.

**To Reproduce**
1. Create a new post
2. Drag and drop a file with an unsupported file type (.exe, .dmg, .json etc.)
3. Observe that a file block is created and displays an error "Sorry, this file type is not permitted for security reasons."
4. Update/Save the post
5. Refresh the page
6. Observe that 'This block has encountered an error and cannot be previewed.' is displayed where the file block once was.

**Expected behavior**
The file block should still be displayed and should probably not display any kind of error.

**Screenshots**
![screen shot 2018-07-24 at 10 42 13 am](https://user-images.githubusercontent.com/677833/43113798-6dacb006-8f2e-11e8-84a5-e637d63ad78f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 67

**Additional context**
- Discovered while testing #8066, but not caused by it
- This is caused by the file block retaining the 'href' attribute for a blob that no longer exists after previously encountering an error. When mounting after the page reload the `file` variable is undefined. The call to `mediaUpload` then results in an error:
https://github.com/WordPress/gutenberg/blob/7aacd2d6fde175aeaf83b48f29565d712f2aac05/core-blocks/file/edit.js#L58-L68

**Comment by arunsathiya** [comment] 2018-08-11 12:29
Was able to reproduce a similar error `Sorry, this file type is not permitted for security reasons.` when uploading a `.mkv` file - #8873. 

Was not able to reproduce an erroneous state of the block on the output though.

**Comment by jorgefilipecosta** [comment] 2019-06-06 11:02
Hi @talldan, thank you for reporting this issue, @arunsathiya thank you for the tests you performed. I was also not able to replicate a block crash in my tests, so I'm going to close this issue as I think it got fixed meanwhile.
To not that when dragging an invalid file to the editor without previously adding a file block, the block keeps a transient URL, and that should be fixed but it is a different issue.

**Closed by jorgefilipecosta** 2019-06-06 11:02 UTC
Labels: Blocks, Drag and Drop, [Block] File, [Type] Bug
