### ISSUE TITLE
please make the image box clickable. Currently it does not work 

### ISSUE THREAD

**Issue by Darchorse64** [WordPress/gutenberg#37431] opened 2021-12-16 01:28 UTC

**Comment by Darchorse64** [comment] 2021-12-16 01:32
If I have an already created "Image Box Block" I cannot select the image after the first time. I also cannot make the "whole Image box block" clickable.

It should be as simple as selecting the image block block and selecting from a drop down menu an "add URL" or something like that.

**Comment by talldan** [comment] 2021-12-16 01:37
Closing as a duplicate of #37432

**Closed as completed by talldan** 2021-12-16 01:37 UTC
Labels: [Status] Duplicate
