### ISSUE TITLE
Updating failed. The response is not a valid JSON response.

### ISSUE THREAD

**Issue by indianmomszurich** [WordPress/gutenberg#61671] opened 2024-05-15 07:34 UTC
### Description

WordPress 6.5.3 currently running Astra theme.
Elementor v3.21.5
Elementor Pro v3.21.2

1. Create a page/post with default Editor, save the Post. no errors.
2. Edit the same page with Elementor and Save the page from Elementor. No Errors
3. Exit Elementor and save the Page from WP Editor - Classis or Block.. (with or without changes made.)
The update fails - Updating failed. The response is not a valid JSON response.

We have tried the following:
1. Recreated Permalinks (deletion of htaccess file)
2. Tested with Hello theme
3. Disabled all other plugins

The error only occurs on pages created with Elementor.

Debug log:
[14-May-2024 11:54:21 UTC] PHP Notice:  Trying to access array offset on value of type bool in /home/ch369560/web/idcn.ch/public_html/wp-content/plugins/elementor/includes/managers/image.php on line 113

blocks.min.js?ver=6612d078dfaf28b875b8:19 Block validation: Block validation failed for `core/image` (Object).
Content generated by `save` function:

### Step-by-step reproduction instructions

1. Create a page/post with default Editor, save the Post. no errors.
2. Edit the same page with Elementor and Save the page from Elementor. No Errors
3. Exit Elementor and save the Page from WP Editor - Classis or Block.. (with or without changes made.)
The update fails - Updating failed. The response is not a valid JSON response.

### Screenshots, screen recording, code snippet

![screenshot](https://github.com/WordPress/gutenberg/assets/61111723/b65bf980-36e6-4df6-9c6f-15323ba55202)

### Environment info

WordPress 6.5.3 currently running Astra theme.
Elementor v3.21.5
Elementor Pro v3.21.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by indianmomszurich** [comment] 2024-05-15 08:09
Since this issue occurs with Elementor and Gutenberg, we have deacticated all other plugins except Elementor and Elementor Pro.

**Comment by Mamaduka** [comment] 2024-05-15 08:10
@indianmomszurich, the issue seems to be a conflict with Elementor. The issue can't be reproduced on clean WP installations.

I would recommend reaching out to Elementor support.

**Comment by indianmomszurich** [comment] 2024-05-15 08:43
We reached out to them before contacting you. They suggested raising it here because the error occurs when saving from default Editor. We have recontacted them. Thank you.

**Comment by Mamaduka** [comment] 2024-05-15 09:17
I'm going to close the issue. Feel free to re-open it or share it with the Elementor team for further discussion.

**Closed as not planned by Mamaduka** 2024-05-15 09:17 UTC
Labels: [Type] Bug, [Type] Plugin Interoperability
