### ISSUE TITLE
Template part areas display as "undefined" in the template editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37443] opened 2021-12-16 09:13 UTC
### Description

When you add a template part in the template editor, (either template part, header, or footer aliases) and select "Choose existing",
the area displays as "Undefined".

### Step-by-step reproduction instructions

1. Activate a theme with support for template editing, for example Twenty Twenty-Two
2. Open a template in the template editor
3. Add a template part. Select "Choose existing"
4. See that the area is undefined.

### Screenshots, screen recording, code snippet

![A template part block is added in the template editor, but the area is "undefined" instead of the registered header area ](https://user-images.githubusercontent.com/7422055/146341930-69d54e0d-a751-4a0f-88b8-d7e7ba4582e5.png)

### Environment info

WordPress 5.9.0 beta 3 via the beta tester
With and without Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment] 2021-12-16 13:31
I think we forgot to backport this part of the editor settings into the WP core. I'm not able to reproduce this with the Gutenberg trunk.

https://github.com/WordPress/gutenberg/blob/b3837134a6ecea321b70362b1ce2ab27ef601e96/lib/editor-settings.php#L27-L29

**Comment by carolinan** [comment] 2021-12-20 11:44
Would that be in get_default_block_editor_settings()? https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-editor.php#L154

Or get_block_editor_settings() https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-editor.php#L300

**Comment by tellthemachines** [comment] 2021-12-21 06:29
I can't reproduce this locally with WP trunk plus the [package updates for Beta 4](https://github.com/WordPress/wordpress-develop/pull/2073).

**Comment by hellofromtonya** [comment] 2021-12-21 06:31
[WordPress Core's changeset 52232](https://core.trac.wordpress.org/changeset/52232/trunk/src/wp-admin/site-editor.php) added the `defaultTemplatePartAreas` setting:

```php
$block_editor_context = new WP_Block_Editor_Context();
$custom_settings      = array(
	'siteUrl'                              => site_url(),
	'postsPerPage'                         => get_option( 'posts_per_page' ),
	'styles'                               => get_block_editor_theme_styles(),
	'defaultTemplateTypes'                 => $indexed_template_types,
	'defaultTemplatePartAreas'             => get_allowed_block_template_part_areas(),
	'__experimentalBlockPatterns'          => WP_Block_Patterns_Registry::get_instance()->get_all_registered(),
	'__experimentalBlockPatternCategories' => WP_Block_Pattern_Categories_Registry::get_instance()->get_all_registered(),
);
$editor_settings      = get_block_editor_settings( $custom_settings, $block_editor_context );
```
I'm not seeing other changes to that setting in Core since that commit. 

And `get_allowed_block_template_part_areas()` was committed 6 weeks ago with [changeset 52062](https://core.trac.wordpress.org/changeset/52062/trunk/src/wp-includes/block-template-utils.php).

**Comment by hellofromtonya** [comment] 2021-12-21 06:32
Removing the backport label until the needed backport is identified.

**Comment by carolinan** [comment] 2021-12-21 07:53
Changeset 52232 changes wp-admin/site-editor.php, is that used for the template editor? Which is part of the block editor, not the site editor.

**Comment by carolinan** [comment] 2021-12-22 04:27
> I can't reproduce this locally with WP trunk plus the [package updates for Beta 4](https://github.com/WordPress/wordpress-develop/pull/2073).

How did you add the template part? I am still unable to add a template part block using 5.9-beta4-52408-src.

**Comment by Mamaduka** [comment] 2021-12-22 07:20
I was able to reproduce this with beta 4. It should be fixed via a core patch, and I will create it shortly.

**Comment by Mamaduka** [comment] 2021-12-22 07:48
Core PR: https://github.com/WordPress/wordpress-develop/pull/2076

**Comment by Mamaduka** [comment] 2021-12-22 13:20
The core patch got merged - https://core.trac.wordpress.org/changeset/52409.

I am closing the issue since there's no change required on the plugin side.

**Closed as completed** 2021-12-22 13:21 UTC
Labels: [Block] Template Part, [Feature] Template Editing Mode
