### ISSUE TITLE
Cover Block: Open Media Library actually opens Upload dialog

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#52842] opened 2023-07-21 14:34 UTC
### Description

When I want to replace an image, this is the user journey:
1. Click Replace
2. Click "Open Media Library" (I'd expect that the media library then opens)
3. However, the Upload Dialog Opens
4. Click "Media Library" again

The Media Library should open directly, instead of the Upload screen (Upload is already in the "Replace" Drop down.

### Step-by-step reproduction instructions

see above or screencast

### Screenshots, screen recording, code snippet

 

https://github.com/WordPress/gutenberg/assets/17861443/a93a851c-b9fc-43ed-84b9-f7d5d418f9d0

### Environment info

- Wp 6.2.2
- GB 16.2.1

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment] 2023-07-25 11:45
Hey @hanneslsm  - I've been unable to recreate this in testing. Do you mind telling me what theme was active when you were trying this out?

**Comment by hanneslsm** [comment] 2023-07-25 11:47
@jordesign It's a custom theme, build from scratch with the Create Block Theme Plugin.

**Comment by jordesign** [comment] 2023-07-25 11:54
Thanks @hanneslsm - do you still get the same error when you try replacing the image in a cover while using the TwentyTwentyThree theme?

**Comment by hanneslsm** [comment] 2023-07-25 11:59
> Thanks @hanneslsm - do you still get the same error when you try replacing the image in a cover while using the TwentyTwentyThree theme?

Yes, I do.
Here is the block markup, just put it in the index template.

```
<!-- wp:group {"style":{"spacing":{"padding":{"right":"clamp(16px,4vw,64px)","left":"clamp(16px,4vw,64px)","top":"var:preset|spacing|fluid-16-64","bottom":"var:preset|spacing|fluid-16-64"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--fluid-16-64);padding-right:clamp(16px,4vw,64px);padding-bottom:var(--wp--preset--spacing--fluid-16-64);padding-left:clamp(16px,4vw,64px)"><!-- wp:cover {"url":"http://prolooks.local/wp-content/themes/prolooksX/assets/images/martin-martz-UlxfzEEN3HU-unsplash-scaled.jpg","id":403,"dimRatio":0,"minHeight":80,"minHeightUnit":"vh","contentPosition":"center left","isDark":false,"style":{"spacing":{"padding":{"right":"var:preset|spacing|fluid-16-64","left":"var:preset|spacing|fluid-16-64","top":"clamp(64px, 8vw, 96px)","bottom":"clamp(64px, 8vw, 96px)"}},"border":{"radius":"40px"}},"className":"has-light-color has-text-color"} -->
<div class="wp-block-cover is-light has-custom-content-position is-position-center-left has-light-color has-text-color" style="border-radius:40px;padding-top:clamp(64px, 8vw, 96px);padding-right:var(--wp--preset--spacing--fluid-16-64);padding-bottom:clamp(64px, 8vw, 96px);padding-left:var(--wp--preset--spacing--fluid-16-64);min-height:80vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-403" alt="" src="http://prolooks.local/wp-content/themes/prolooksX/assets/images/martin-martz-UlxfzEEN3HU-unsplash-scaled.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:group {"align":"wide","layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group alignwide"><!-- wp:paragraph {"align":"left","style":{"typography":{"textTransform":"uppercase","fontStyle":"normal","fontWeight":"400","letterSpacing":"4px"}},"fontSize":"paragraph-sm","fontFamily":"inter"} -->
<p class="has-text-align-left has-inter-font-family has-paragraph-sm-font-size" style="font-style:normal;font-weight:400;letter-spacing:4px;text-transform:uppercase">● everything you need ●</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"left","style":{"typography":{"lineHeight":"1.1","letterSpacing":"-2px"}},"fontSize":"display-lg"} -->
<h2 class="wp-block-heading has-text-align-left has-display-lg-font-size" style="letter-spacing:-2px;line-height:1.1">🡒 </h2>
<!-- /wp:heading -->

<!-- wp:heading {"textAlign":"left","style":{"typography":{"lineHeight":"1.1","letterSpacing":"-2px"}},"fontSize":"display-lg"} -->
<h2 class="wp-block-heading has-text-align-left has-display-lg-font-size" style="letter-spacing:-2px;line-height:1.1">The easiest way to build websites with Gutenberg</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","fontSize":"heading-6"} -->
<p class="has-text-align-left has-heading-6-font-size">Lorem ipsum dolor sit amet. Et repellat quia aut ullam autem aut minima dolor. Nam ipsum laboriosam et excepturi dolorsum rem neque internos. Qui aperiam eveniet At officia illo in labore dolor aut explicabo quaerat et vero voluptatem in tempore aspernatur. Eos assumenda officiis sed vero soluta et sint fugiat ut galisum autem ut voluptatum illum.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"style":{"layout":{"flexSize":null,"selfStretch":"fill"}}} -->
<div aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>Available for</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"fontStyle":"normal","fontWeight":"400"}},"fontSize":"heading-4"} -->
<p class="has-heading-4-font-size" style="font-style:normal;font-weight:400"><strong>W</strong><sup><sub><kbd>orld</kbd></sub></sup>—<strong>W</strong><sub><kbd><sup>ide</sup></kbd></sub>—<strong>W</strong><kbd><sup><sub>eb</sub></sup></kbd></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontStyle":"italic","fontWeight":"800","letterSpacing":"3px"}},"fontSize":"heading-5"} -->
<p class="has-heading-5-font-size" style="font-style:italic;font-weight:800;letter-spacing:3px">WORDPRESS</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontStyle":"normal","fontWeight":"200","letterSpacing":"-4px"}},"fontSize":"heading-4"} -->
<p class="has-heading-4-font-size" style="font-style:normal;font-weight:200;letter-spacing:-4px">Gutenberg</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"600","lineHeight":"1"}},"fontSize":"display-xl"} -->
<p class="has-text-align-center has-display-xl-font-size" style="font-style:normal;font-weight:600;line-height:1">2</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">hands</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1"}},"fontSize":"display-xl"} -->
<p class="has-display-xl-font-size" style="line-height:1">|</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"600","lineHeight":"1"}},"fontSize":"display-xl"} -->
<p class="has-text-align-center has-display-xl-font-size" style="font-style:normal;font-weight:600;line-height:1">10</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">fingers</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1"}},"fontSize":"display-xl"} -->
<p class="has-display-xl-font-size" style="line-height:1">|</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"600","lineHeight":"1"}},"fontSize":"display-xl"} -->
<p class="has-text-align-center has-display-xl-font-size" style="font-style:normal;font-weight:600;line-height:1">27</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">bones per hand</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group -->
```

**Comment by Mamaduka** [comment] 2023-07-25 16:57
If I recall correctly media library remembers the last selected tab and set is as an active tab when you open it next time.

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/a1330a2d-3f2d-4d17-bbc8-b9af6efe6d3e

**Comment by hanneslsm** [comment] 2023-07-25 17:00
> If I recall correctly media library remembers the last selected tab and set is as an active tab when you open it next time.

That's it!

Not sure if this is still needed though. 
As you can see, if found it rather confusing.

**Comment by Mamaduka** [comment] 2023-07-25 17:05
The Media Library isn't maintained in this repo, you can open a [Track ticket](https://core.trac.wordpress.org/) for core, but I think this is one of those "feature, not a bug" situations.

P.S. The media library overhaul is on the roadmap - https://make.wordpress.org/core/2023/07/07/media-library/.

**Comment by Mamaduka** [comment] 2023-07-25 17:10
I'll close this issue as it's not actionable from the editor's perspective.

**Closed as completed by Mamaduka** 2023-07-25 17:10 UTC
Labels: [Type] Bug, [Status] Needs More Info, [Block] Cover

**Comment by hanneslsm** [comment] 2023-07-25 17:11
> I'll close this issue as it's not actionable from the editor's perspective. 

That would have been my next question - how to handle such issues. Thanks! :)
