### ISSUE TITLE
Mobile web post editor continually scrolls viewport to top of edit screen

### ISSUE THREAD

**Issue by cagrimmett** [WordPress/gutenberg#53880] opened 2023-08-22 19:31 UTC
### Description

This is on a fresh install with only WP Core. Zero active plugins. The editor keeps bumping the view back to the top, making it impossible to write a post on mobile in wp-admin on iOS in Safari.

### Step-by-step reproduction instructions

1. Install a fresh copy of WordPress with no plugins.
2. Navigate to the site in Safari on iOS
3. Click to write a new post in the block editor
4. Add a title 
5. Write 4 paragraphs in the block editor
6. Observe how you can't get past the second or third paragraph block without being auto-scrolled back to the top.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/8738771/ef384023-746a-4ebc-abdd-98452d8201d1

### Environment info

- WordPress 6.3
- No plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-08-22 20:46
Duplicate of https://github.com/WordPress/gutenberg/issues/33198 Going to close this out!

**Closed as completed by annezazu** 2023-08-22 20:46 UTC
Labels: Mobile Web, Browser Issues, [Feature] Writing Flow
