### ISSUE TITLE
Should ENTER keep UI hidden?

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#1561] opened 2017-06-28 14:48 UTC
Currently if you type and press ENTER, the UI for the next text block pops up. Of course it hides again once you start typing again, but a new paragraph is not only a break in text, but also in writing. When I'm thinking about what the next paragraph should be, I don't want to be disturbed with UI popping up, I just want to be left alone with my text. :)

**Comment by mtias** [comment] 2017-06-28 15:32
Let's try it, makes sense to me.

**Comment by nylen** [comment] 2017-07-01 08:40
#1616 was a duplicate of this one:

> When <kbd>return</kbd> is pressed twice to start a new paragraph, a bunch of UI pops up. It goes away with the first keystroke in the new paragraph, but the appearance of all these things is jarring. Shouldn't it just assume that if you used they keyboard to start a new paragraph, you want to continue writing, and that if you actually want to do something like choose a different block type, you'll move the cursor, at which point the UI can appear?

> ![gutenberg](https://user-images.githubusercontent.com/353790/27743183-29ca7a8a-5d89-11e7-8bf6-c667652a1085.gif)

**Comment by jwold** [comment] 2017-07-07 20:26
Absolutely agree with the premise of this ticket. I always do 2 enters to separate my paragraph, and having it split out into another block is really jarring. Would love for text to just stay in one block indefinitely until I decide to add another type of block.

**Comment by nylen** [comment] 2017-07-07 23:45
@jwold this is more like #1748.

**Comment by jwold** [comment] 2017-07-08 02:04
Good point!

**Closed** 2017-07-14 16:08 UTC
Labels: [Type] Question

**Comment by nylen** [comment] 2017-07-19 17:13
FYI, this was closed because it was fixed in #1812.
