### ISSUE TITLE
When text goes below the bottom of the text window, it doesn't scroll down.

### ISSUE THREAD

**Issue by moriartyviccar** [WordPress/gutenberg#13376] opened 2019-01-19 21:31 UTC
**Describe the bug**
When I write a long article, the words have started disappearing behind the plug ins situated at the foot of the window, such as Yoast. This has never happened before today. I can't scroll down. When this occasionally happened in Classic, I could click on the window and it would sort itself out. Now it won't. I can write out the copy in Word and paste it in later, but I won't be able to post any images in or links or anything.

**To Reproduce**
1. Go to 'New Post'
2. Click on 'the edit window and type an article of a few hundred words'
3. Scroll down to 'the end of the window'
4. See error. Words go behind the plug ins and can't be seen. Editing can still happen, but blindly.

**Expected behavior**
I expect the window to scroll down with the copy so that i can see what I'm typing.

**Screenshots**
I have tried to upload a video shot but it won't allow me to. I have flv, mp4 or mov format.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Newest]

**Comment by moriartyviccar** [comment] 2019-01-28 19:02
![github_image_1](https://user-images.githubusercontent.com/42593751/51859517-38822880-232f-11e9-9427-649071c687a3.jpg)
![2](https://user-images.githubusercontent.com/42593751/51859518-38822880-232f-11e9-9405-fc187aa33bdb.jpg)

**Comment by moriartyviccar** [comment] 2019-01-28 19:03
As you can see, the text goes down underneath the Yoast Plug in. I can't get the scroll bar to bring the text any higher.

**Comment by mikestopcontinues** [comment] 2019-02-12 08:47
This is a dup of https://github.com/WordPress/gutenberg/issues/4445.

As I just mentioned there, I suspect fixed positioning of the editor (`.edit-post-layout__content`) might be a good solution.

**Comment by jasmussen** [comment] 2019-02-12 10:29
Hi there, thanks for the ticket. This issue sounds a lot like #11378, or potentially #13503. 

In case it's a duplicate of #11378 it is likely because of a new plugin, or a theme change, that is causing the editor to load in "quirks" mode. 

Can I ask that you press `Ctrl + Shift + J` to open your console and see if there's an error message there? It should read something like this:

```
[Warning] Your browser is using Quirks Mode. This can cause rendering issues such as blocks overlaying meta boxes in the editor. Quirks Mode can be triggered by PHP errors or HTML code appearing before the opening <!DOCTYPE html>. Try checking the raw page source or your site's PHP error log and resolving errors there, removing any HTML before the doctype, or disabling plugins.
```

If you _do_ have that error message, the issue is most likely with a plugin. Try deactivating them one by one to see which one might have been causing the issue.

**Comment by moriartyviccar** [comment] 2019-02-12 11:21
Hi many thanks for your replies :-)
The issue seems to have corrected with the last GitHub update.
I'll keep this information to hand in case it arises again though.
Many thanks 
Matt

**Comment by moriartyviccar** [comment] 2019-02-12 11:21
Not GitHub, Gutenberg haha

**Closed** 2019-02-12 11:21 UTC
Labels: General Interface, Needs Testing

**Comment by jasmussen** [comment] 2019-02-12 11:24
Thank you! Glad it's fixed.
