### ISSUE TITLE
FSE Featured Image block needs size settings

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#31323] opened 2021-04-29 09:12 UTC
## What problem does this address?
When adding the Post Featured Image block to the Query Loop placeholder, it does it quite literally: it shows the image set as the Featured Image for that post. But there are no size controls for the image and it doesn't seem to respect a content column width setting or anything, it just always renders at full width it seems. This has taken over 90% of the browser window. I tried resizing the image in the media library but that didn't change the size it is displayed at on the frontend. I selected a different image which was a lot smaller but that too renders across the entire width of the browser.

## What is your proposed solution?
Add size and width options to the Post Featured Image block.

![Screenshot_2021-04-29 Site Editor (beta) ‹ Chéz Hedge — WordPress](https://user-images.githubusercontent.com/6073772/116528065-ab4a2780-a8db-11eb-9c43-58a519b902c7.png)

**Comment by carolinan** [comment] 2021-05-07 13:08
@hedgefield Is this a duplicate of https://github.com/WordPress/gutenberg/issues/27620 ?

**Comment by hedgefield** [comment] 2021-05-10 07:52
It's related in the sense that it both problems have the same cause - the lack of size controls on query loop images - but I wouldn't exactly call it duplicates. I think 27620 talks about a different kind of block, and fixing that does not automatically fix this.

**Comment by carolinan** [comment] 2021-05-10 17:18
It is the same block, you can choose to place it inside a query, or anywhere else where there is a post-type context.

**Comment by hedgefield** [comment] 2021-05-11 17:19
Ahh sorry yes I thought it was the gallery block they were talking about from that screenshot. Yes then they are duplicates in that sense.

**Comment by annezazu** [comment] 2021-05-17 20:40
Making this decision to close this out as a duplicate as I agree with @carolinan: https://github.com/WordPress/gutenberg/issues/27620 Feel free to re-open if there is some nuance that I missed but it's helpful to consolidate these related issues!

**Closed as completed by annezazu** 2021-05-17 20:40 UTC
Labels: [Block] Post Featured Image

**Comment by justintadlock** [comment] 2021-05-17 20:53
I thought this ticket was for the "Image Size" setting (e.g., Full, Large, Medium, Custom Theme Sizes, etc.), which is slightly different from dimensions and resizing controls.

We really need to be able to set the Image Size.  Should I create a new ticket or would that be more appropriate in the other too?

**Comment by annezazu** [comment] 2021-05-17 21:23
Personally, I'd chime in on the issue mentioned above as much of what I _believe_ you are referring to is touched on there. If you're thinking of something else though, happy to re-open this or to see a new issue created.
