### ISSUE TITLE
Multi-Site - Can't add new page

### ISSUE THREAD

**Issue by anthonyproctor** [WordPress/gutenberg#15163] opened 2019-04-25 03:05 UTC
**Describe the bug**
When muti site is enabled with sub-directories. You can't make a new page on the sub-directory sites.

**To reproduce**
1. Go to a sub directory site in a mult site environtment and try to create a page.

**Expected behavior**
You will get a white page.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4
 - Browser Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Most recent wordpress and gutenburg released version

**Comment by anthonyproctor** [comment] 2019-04-25 04:30
The problem was fixed once I installed classic editor and disabled gutenberg.

**Comment by ajitbohra** [comment] 2019-05-09 14:44
Hi there,

Unable to reproduce the issue on multi-site with sub-folder setup. Looks like server or plugin compatibility issues.

There is not enough information in your report for this to be actionable so I'm going to close this for now but feel free to open a new issue following the template and with more details.

**Closed by ajitbohra** 2019-05-09 14:44 UTC
Labels: [Status] Needs More Info
