### ISSUE TITLE
Image block replace button drop down - horizontal scrollbars are seen- bug 

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#27788] opened 2020-12-17 20:24 UTC
**Describe the bug**
![Horizontal-scrollbar-Replace-image](https://user-images.githubusercontent.com/5323259/102538004-00fc0100-40ac-11eb-81f7-f0edbb723e50.gif)

**To reproduce**
1. Add an Image block.
2. Add image.
3. Click Replace to replace the image.
4. See the horizontal scrollbar.

**Expected behavior**
No scrollbar.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Yes
- If the Gutenberg plugin is installed, which version is it? 9.5.2

**Desktop (please complete the following information):**
Local
Desktop Server
Chrome

NB! Testing also with Gutenberg version 9.6 RC. 
Using theme: Twenty Twenty One. 
WP 5.6. 
Chrome.
No other plugins activated.

![Replace-image-bug](https://user-images.githubusercontent.com/5323259/102538862-29d0c600-40ad-11eb-8a58-35069cd47df2.gif)

----

Also tested on a customer site running WP 5.5. Gutenberg plugin: 9.5.2. Custom theme.
Even turning off the Gutenberg plugin I could see the same error.

**Comment by paaljoachim** [comment] 2020-12-19 13:01
Btw
I am seeing the following when I create the Core Editor summary post.

![Screen Shot 2020-12-19 at 13 57 38](https://user-images.githubusercontent.com/5323259/102689982-99a49500-4202-11eb-93b1-4fc0b1c20922.png)

**Comment by carolinan** [comment] 2020-12-20 01:40
Closing, as duplicate of https://github.com/WordPress/gutenberg/issues/27186 and https://github.com/WordPress/gutenberg/issues/27753

**Closed by carolinan** 2020-12-20 01:40 UTC
Labels: [Block] Image, [Status] Duplicate, [Type] Bug
