### ISSUE TITLE
Media query pushes toolbar buttons and notifications under the admin menu

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#4559] opened 2018-01-18 01:38 UTC
## Issue Overview
I noticed this when I opened the console. It looks like there's a rouge media query pushing the toolbar buttons and notifications under the admin menu on short pages. A screenshot has been attached below.

## Steps to Reproduce (for bugs)

1. Resize the height of your window to less than 620px.
2. You should see the toolbar buttons and notifications pushed under the admin menu.

I'm using Chrome on OSX.

## Screenshots / Video
![screenshot 2018-01-17 17 34 56_preview](https://user-images.githubusercontent.com/2453483/35076417-360c3b72-fbad-11e7-84c4-616c42d44eca.png)

**Comment by gthayer** [comment] 2018-01-18 17:25
I am unable to replicate this using Chrome on OSX and tried Firefox and Safari for good measure. Also tried switching between the different default themes in case that caused it. Checked Master, v2.0.0 and v1.9.1 of this repo to see if a version updated fixed/caused it.

I see you have a number of plugins with pending updates. Possible any of those are effecting this? Can you element inspect notice and see if any plugin styles are being applied to it?

**Comment by fastlinemedia** [comment] 2018-01-18 17:31
Hey @gthayer! I've disable all plugins and switched to Twenty Sixteen and am still seeing the issue (cleared cache as well). 

I'm on OSX 10.13.2 using the latest Chrome.

**Comment by gthayer** [comment] 2018-01-18 17:57
Ahh, I think I see it now. For whatever reason, your body tag does not have the class "auto-fold". If you add that to your body directly, I think you'll see it display correctly.

I'm not sure why it's not being added for you. It appears this is handled by core.

What version of core are you running? Are you seeing any console errors?

**Comment by fastlinemedia** [comment] 2018-01-18 17:59
Yep! That fixes it. I'm running 5.0-alpha-42525 using the beta tester plugin. Maybe something there?

**Comment by gthayer** [comment] 2018-01-18 18:13
I'm afraid I don't know. I updated to 5.0-alpha-42525 and I am still not able to replicate. Only difference I see right now is that you are running a higher version of OSX than I am.

I'll see if I can find anything, but I think we'll have to wait and see if anyone else has any ideas.

**Comment by jorgefilipecosta** [comment] 2018-03-15 18:21
Thank you for your debugging @fastlinemedia and @gthayer. There were some CSS changes, and I'm not being able to replicate this issue. I will close this for now. If the problem is still happening on the last version of Gutenberg, feel free to reopen the issue with a comment!

**Closed by jorgefilipecosta** 2018-03-15 18:21 UTC
Labels: Good First Issue, [Type] Bug

**Comment by jeffpaul** [comment] 2018-03-15 18:32
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521134070000380)._
