### ISSUE TITLE
Cover block become invisible if aligned left or right without text

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#11919] opened 2018-11-15 14:59 UTC
**Describe the bug**

When a cover block has no text and it's aligned left or right, it disappears.

**To Reproduce**
1. Insert a cover block.
2. Set it to align right.
3. Insert a new paragraph block.
4. The cover image disappears.

**Expected behavior**

Perhaps there should be a minimum width for cover images that keeps them visible when aligned but there is no text.

**Screenshots**

![cover image](https://user-images.githubusercontent.com/3314354/48561011-fa0bce80-e8e6-11e8-84a7-c0dd45f3b167.gif)

**Comment by ellatrix** [comment] 2019-06-24 13:18
This seems to be resolved with recent refactorings. Correct me if I'm wrong. I'm no longer able to reproduce.

**Closed by ellatrix** 2019-06-24 13:18 UTC
Labels: Needs Testing, [Block] Cover
