### ISSUE TITLE
Adding tooltips to toolbar options

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2207] opened 2017-08-03 23:47 UTC
Hovering over the for instance options for images. Does not give us a hint without clicking what each icon does.

![screen shot 2017-08-04 at 01 45 19](https://user-images.githubusercontent.com/5323259/28948552-aca87e82-78b6-11e7-8767-9da10c050e07.png)

It would be great to have tooltips for all the toolbar options.

**Comment by afercia** [comment] 2017-08-04 11:22
Duplicate of #531 ?

**Closed** 2017-08-04 12:21 UTC
