### ISSUE TITLE
Tabbing to modal close button positions label outside of view

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15434] opened 2019-05-04 21:33 UTC
**Describe the bug**

When [a `TextControl` is inside a `Modal`](https://github.com/iandunn/gutenberg-escape-modal-bug/blob/475ae85/src/main/index.js), and the user tabs from the input field to the close button, the `Close Dialog` label appears, but it is positioned in the bottom right corner, outside the normal content area, creating vertical and horizontal scrollbars.

It might happen without `TextControl` too, but I didn't test that.

<img width="478" alt="Screen Shot 2019-05-04 at 2 30 51 PM" src="https://user-images.githubusercontent.com/484068/57185027-6f5d6280-6e79-11e9-8866-10b84082ee4c.png">
<img width="532" alt="Screen Shot 2019-05-04 at 2 30 17 PM" src="https://user-images.githubusercontent.com/484068/57185028-72585300-6e79-11e9-9e7a-e449ec713e21.png">

**To reproduce**

1. `git clone git@github.com:iandunn/gutenberg-escape-modal-bug.git`
1. `npm install`
1. `npm start`
1. activate plugin
1. browse to `wp-admin/admin.php?page=gutenberg-escape-modal-bug`
1. click on `input` field
1. press `shift + tab` key to focus on close button

**Expected behavior**

The label should be positioned next to the close button, and not create any scrollbars.

**Comment by jorgefilipecosta** [comment] 2019-06-06 17:00
I test the issue in the last version of Gutenberg, and I got a similar problem. I was not able to see the label at all and I got an "infinit" on the popover content with an empty space.

**Comment by jessepearson** [comment] 2021-05-07 13:20
Just wanting to note here that this happens when you hover over the X, as well. It was mentioned in #28311, but not noted explicitly here.

**Comment by youknowriad** [comment] 2023-06-01 08:39
I'm not able to reproduce this issue anymore. Closing.

**Closed by youknowriad** 2023-06-01 08:39 UTC
Labels: [Type] Bug, [Package] Components
