### ISSUE TITLE
V2 Theme.json spacingSizes not applied properly

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62195] opened 2024-05-31 18:58 UTC
### Description

A follow-up to https://github.com/WordPress/gutenberg/pull/61842 is needed to iron out a quirk. It seems if the `spacingSizes` has a `slug` that is not the default values, the control does not apply them properly (tested on a V2 theme.json implementation).  

### Step-by-step reproduction instructions

1. Edit the Twenty Twenty Four theme.json spacingSizes `slugs` to use `small`, `large`, etc. Also change the `name` value for each to match. 
2. Add a new page. 
3. Add a spacer block. 
4. Open the Inspector.
5. Set the spacer block to use the presets. 
6. Drag it to the right. 
7. See the spacing sizes applied out of order. 
8. See the spacing sizes `name` not rendering, only the default numbers. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1813435/a273683d-c6db-48b2-8a3d-551f6725b641

### Environment info

Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment] 2024-05-31 18:59
```"spacingSizes": [
				{
					"name": "1",
					"size": "1rem",
					"slug": "x-small"
				},
				{
					"name": "2",
					"size": "min(1.5rem, 2vw)",
					"slug": "small"
				},
				{
					"name": "3",
					"size": "min(2.5rem, 3vw)",
					"slug": "medium"
				},
				{
					"name": "4",
					"size": "min(4rem, 5vw)",
					"slug": "large"
				},
				{
					"name": "5",
					"size": "min(6.5rem, 8vw)",
					"slug": "x-large"
				},
				{
					"name": "6",
					"size": "min(10.5rem, 13vw)",
					"slug": "xx-large"
				}
```

**Comment by ajlende** [comment] 2024-05-31 20:28
Duplicate of #62194

**Closed as completed by ajlende** 2024-05-31 20:28 UTC
Labels: [Type] Bug, Global Styles
