### ISSUE TITLE
Pseudo links cause nested instances of the FSE editor

### ISSUE THREAD

**Issue by diedexx** [WordPress/gutenberg#30967] opened 2021-04-19 15:29 UTC
## Description

When you click an anchor with a fake placeholder link like this in the FSE, a new instance of the editor is loaded inside the editor.
```
<a href="#post-date-pseudo-link"><time datetime="2021-04-09T12:20:52+02:00">April 9, 2021</time></a>
```
This allows you to nest multiple editors:
![image](https://user-images.githubusercontent.com/5352634/115260680-451f1100-a133-11eb-9aea-cffbb14b55f4.png)

## Step-by-step reproduction instructions
1. Install a FSE capable theme (I use TT1 Blocks)
2. Open the Site Editor.
3. Add a Query block and and select "Large".
4. Open the sidebar
5. Select the post date block that has been added to your page.
6. Under "link settings", enable "Link to post"
7. Save your template
8. Click the post edit link.

## Expected behaviour
I expected the link to do nothing, like in the post editor.

## Actual behaviour
The link spawned a new instance of the editor inside the current editor.

## WordPress information
- WordPress version: 5.7.2-alpha-50758
- Gutenberg version: 10.4.0-rc.1 
- Are all plugins except Gutenberg deactivated? yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks 

## Device information
- Device: Desktop 
- Operating system: MacOS 11 
- Browser: Chrome 89.0

**Comment by carolinan** [comment] 2021-04-19 16:05
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/30647

**Closed as completed by carolinan** 2021-04-19 16:05 UTC
Labels: [Status] Duplicate
