### ISSUE TITLE
Can't escape list with ENTER

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11163] opened 2018-10-27 22:49 UTC
**Describe the bug**
I'm used to being able to "escape" a list by hitting `RETURN` twice. Once to make a new empty bullet and once to move to a next paragraph (removing the empty bullet created with the first `RETURN`). Gutenberg creates infinite list items and one can only get to a new paragraph by hitting `DOWN` or `TAB`.

I can't always recreate this bug, but it most frequently happens if the list is the last block on the page, though I've seen it happen when that's not the case.

**Screenshots**
![Hitting return just adds new empty bullets, not make a new paragraph](https://user-images.githubusercontent.com/1238696/47610024-e19f4700-d9ff-11e8-9fd6-ef8bf76487e7.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 63
 - WordPress 5.0-beta1-43823, Twenty Nineteen, no plugins

**Comment by mrwweb** [comment] 2018-10-29 14:45
@earnjam I'm able to recreate on 5.0-beta1-43832. It seems to only happen when creating a the first bullet via the "-" typed shortcut.

![stuck-in-bullets](https://user-images.githubusercontent.com/1238696/47657560-8a5bbc80-db4e-11e8-8c0f-1f1ea4c2ea53.gif)

**Comment by earnjam** [comment] 2018-10-29 14:57
Thanks for the extra info @mrwweb! I was able to recreate this in Firefox on OSX. 
It's not happening in Chrome. 
Only occurs when using the `-` shortcut to start a list. 
Does not happen if you use `/list` or the block inserter button and select a list block.

**Comment by youknowriad** [comment] 2018-10-30 10:21
Can't reproduce either, This may have been fixed in ##10799

If it still doesn't work in the next Gutenberg release (4.2) let us know.

**Closed by youknowriad** 2018-10-30 10:21 UTC
Labels: Browser Issues, [Block] List, [Type] Bug

**Comment by earnjam** [comment] 2018-10-30 10:47
Looks like that may have fixed it. It only happened in Firefox, but now seems to be resolved with latest from `master`. 

I did just run into #11164 when testing, though.
