### ISSUE TITLE
Caption of last gallery element is put out of the hierarchy a few tags below after using links to media file.

### ISSUE THREAD

**Issue by lucastoma** [WordPress/gutenberg#13683] opened 2019-02-05 21:13 UTC
**Describe the bug**
Gallery Block: In case we add link to media/attachment last gallery element have problem. Caption of last gallery element is put out of the hierarchy a few tags below.

https://drive.google.com/open?id=0B3bWaFnSRXZTLUcwM093Mm44MVludlN6UlNkX3VZOXVhWFBN

as you see <figcaption> is putout of hierarchy resulting in broken rendering. There is no problem when there is no link to media file or attachment.

I have Wordpress 5.03
gutenberg 4.9.0

i hope it is easy problem :)
Lucas

**Comment by nosolosw** [comment] 2019-04-02 11:07
I've tested this in WordPress 5.1 and the latest Gutenberg plugin (which is to be bundled with WordPress 5.2). Both in Firefox and Chrome. I can't reproduce this.

**Comment by tellthemachines** [comment] 2020-02-06 05:39
Hi there @lucastoma , I can't reproduce this in WordPress 5.3 or with the latest version of the Gutenberg plugin (7.4), so I'm closing this issue for now. Feel free to reopen it if you are still experiencing this problem!

**Closed by tellthemachines** 2020-02-06 05:39 UTC
Labels: Needs Testing, [Block] Gallery
