### ISSUE TITLE
Site Editor / Nav Link - Control only shows results for posts.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#27164] opened 2020-11-21 00:02 UTC
Using the link-control to edit a Nav Link in the site editor only shows search results for posts, not pages:
![Screen Shot 2020-11-20 at 6 55 10 PM](https://user-images.githubusercontent.com/28742426/99860863-636fe900-2b62-11eb-8024-b96d43a185c3.png)

![Screen Shot 2020-11-20 at 6 55 18 PM](https://user-images.githubusercontent.com/28742426/99860866-6539ac80-2b62-11eb-8ba9-8731306c7a5c.png)

We would expect this to allow setting the Nav Link to a page as in the post editor:
![Screen Shot 2020-11-20 at 6 56 53 PM](https://user-images.githubusercontent.com/28742426/99860882-75ea2280-2b62-11eb-99de-77b504da06bc.png)

**Comment by MarcGuay** [comment] 2021-08-20 15:07
Related https://github.com/WordPress/gutenberg/issues/2084

**Comment by Thelmachido** [comment] 2022-08-03 11:55
I cannot reproduce this as shown below: 

https://user-images.githubusercontent.com/41231764/182601519-af1e1014-2aec-4817-b07c-8b155a3c47b1.mov

Gutenberg 13.7.3 

WordPress 6.0.1

Closing this one because the issue was handled in #2084

**Closed** 2022-08-03 11:55 UTC
Labels: [Type] Bug, [Feature] Full Site Editing, [Feature] Link Editing
