### ISSUE TITLE
Navigation: Ghost inserter after items

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46574] opened 2022-12-15 09:12 UTC
## What problem does this address?
When a link in the Navigation block is selected there's some kind of ghost inserter after them:
<img width="630" alt="Screenshot 2022-12-15 at 09 11 23" src="https://user-images.githubusercontent.com/275961/207819464-728f2632-cede-4a6a-ac94-444986c2af52.png">

## What is your proposed solution?
Remove it.

**Comment by ndiego** [comment] 2022-12-20 14:29
This issue was reviewed in today's Editor Bug Scrub, and I can confirm this in 14.7.3. It almost looks like there is an extra `div` being added after the link that should not be there and is nearly a duplicate of the container `div`. It's less apparent in the post/page editor since the blue outline is not applied. But in the Site Editor, it becomes very obvious. 

![image](https://user-images.githubusercontent.com/4832319/208690283-605f8a22-306c-4f27-99e6-c35378d9405c.png)

**Comment by Lovor01** [comment] 2022-12-24 23:35
@scruffian can you describe what you refer to as "ghost inserter" - is it a blue horizontal line after link text or "+" button on the right?

**Comment by draganescu** [comment] 2023-01-04 16:41
The blue horizontal like after link text - that is the ghost inserter :)

**Closed as completed** 2023-01-06 08:19 UTC
Labels: [Type] Bug, [Block] Navigation
