### ISSUE TITLE
Schedule post: Calendar won't close after date picked

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#30415] opened 2021-03-31 15:28 UTC
## Description
The calendar popup won't close after the scheduled publish date is picked. It sometimes does close after a few clicks outside, but this seems to be happening at random.

## Step-by-step reproduction instructions
1. Go to the editor and add any content, just so the post is publishable
2. Open the calendar picker for scheduled publish
3. Click on the next month arrow button
4. Pick a random day there
5. Click on the `Schedule...` button in the topmost nav (or just outside the calendar for that matter)
6. See how the calendar won't disappear
7. Click the picked day again - now the calendar can be dismissed.

## Expected behaviour
The calendar popup disappears when clicked outside.

## Actual behaviour
The calendar popup won't disappear when clicked outside if the date picking click is preceded with the next month button click.

## Screenshots or screen recording
https://user-images.githubusercontent.com/1451471/113169265-b9a61480-9245-11eb-9620-781568b7995c.mp4

## WordPress information
- Gutenberg version: v10.3.0-rc.1

## Device information
- Browser: Chrome

**Comment by fullofcaffeine** [comment] 2021-04-01 23:47
This was closed by accident and is still a problem.

**Comment by Quintis1212** [comment] 2021-04-03 09:45
Hi @fullofcaffeine ) I can not implement yours bug , my date picker closes immediately when I click on date

**Comment by Mamaduka** [comment] 2021-07-14 12:14
I'm no longer able to reproduce this issue with Gutenberg 11.0.

**Comment by skorasaurus** [comment] 2022-09-04 17:25
Closing since multiple people aren't able to reproduce; please reopen if you're still experiencing this.

**Closed as completed by skorasaurus** 2022-09-04 17:25 UTC
Labels: [Type] Bug
