### ISSUE TITLE
Search Block: Button styles don't save when placed inside a Navigation block

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#53038] opened 2023-07-27 14:03 UTC
### Description

If you place a Search block inside of a menu in a Navigation block, then set the block to "Button only" (or any other option besides "Button inside"), the style is not persisted when the Navigation menu is saved. The Search block reverts to "Button inside". See the gif below. 

### Step-by-step reproduction instructions

1. Create a Navigation menu
2. Save the Navigation menu
3. Add a Search block to the menu
4. Set the Search block to "Button only" (or any other option besides "Button inside")
5. Save the Navigation menu and see that the Search block is no longer set to "Button only"

### Screenshots, screen recording, code snippet

![search-block](https://github.com/WordPress/gutenberg/assets/4832319/78ad0685-6a6a-4247-8c9e-b8e1d08bbe77)

### Environment info

- WordPress 6.3 RC2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2023-07-27 14:04
cc @getdave I think you have been working on Navigation. Any ideas here?

**Comment by getdave** [comment] 2023-07-27 14:28
@scruffian wasn't this a bug you and I were looking into at one point? It was to do with random effects in the search block firing?

Did we miss a backport?

**Comment by tellthemachines** [comment] 2023-07-28 01:38
Is this a duplicate of #51713? In any case, I can reproduce it in 6.2.2 so it's not a 6.3 regression.

**Comment by ndiego** [comment] 2023-07-28 02:20
> Is this a duplicate of https://github.com/WordPress/gutenberg/issues/51713? In any case, I can reproduce it in 6.2.2 so it's not a 6.3 regression.

And apparently, I commented on that issue!?! 😅 That said, I am still able to replicate in Gutenberg 16.3, so the linked PR did not resolve the issue even though it is closed. 

As for 6.3, since this issue is present in 6.2 and therefore not a regression, let's punt.

**Comment by wayneconnor** [comment] 2023-08-17 01:07
Is there a work around for this in the meantime?

**Comment by ramonjd** [comment] 2023-09-25 03:16
I couldn't reproduce this specific issue in Chrome, Edge, Firefox or Safari but was experiencing some other strange behaviour. When trying to add text to an empty search block rich text field I couldn't at all. It would bounce focus away from the button.

https://github.com/WordPress/gutenberg/assets/6458278/7832cc87-dade-4572-9006-39ae3bd48ebb

**Comment by tellthemachines** [comment] 2023-09-25 04:37
I can reproduce the issue only when first adding a Search block in a Nav block; saving and reloading or even just switching to code view and back restores the expected behaviour.


https://github.com/WordPress/gutenberg/assets/8096000/5fcad2d5-09ae-486e-b540-088b0d3c652b

**Comment by getdave** [comment] 2023-09-27 11:41
@ramonjd @tellthemachines I have [a PR for review](https://github.com/WordPress/gutenberg/pull/54823) 🙏

**Closed as completed** 2023-09-27 20:15 UTC
Labels: [Type] Bug, [Block] Search

**Comment by ramonjd** [comment] 2023-09-27 21:28
Thanks for tracking it down @getdave !
