### ISSUE TITLE
Link creation unreliable. Link box left on screen and scrolls with user.

### ISSUE THREAD

**Issue by fluffyfour** [WordPress/gutenberg#10692] opened 2018-10-17 16:13 UTC
When creating a link on a piece of text (on a page) one has to create the link and apply, come away from it, then click again and edit to open in a new window. If the link is created and the new window box ticked at the same time, the link will not be applied to the text.

Open in new window is never applied, although it seems to be updating, this is being stripped off whenever it is added.

After creating the link, one is taken to the top of the page (very annoying) and the link addition box stays on screen the whole time, jumping to the correct place only when the next link is required. This scrolls down the page no matter where the user is and cannot be removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select text for link.
2. Click on link button from edit bar.
3. Type or paste link.
4. Click on gear icon (Link Options).
5. Click box for open in new window.
6. Click Update button.
7. You will find yourself at the top of the page with an empty link box in the centre of the screen.
8. Scroll down to text you have just linked.
9. Link will not have been actioned.

**Expected behaviour**
1. Link box should allow input of url and click Open in New Window box at the same time.
2. Empty link box should not appear on screen after first link applied, nor scroll with user.
3. User should not be taken to the top of the editor after a link has been created, but should remain in the desired area of editing.
4. Open in new window box should not be unticked on Update.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- Please add the version of Gutenberg you are using in the description - 4.0.0

Screenshots:-

![gutedss4](https://user-images.githubusercontent.com/44237651/47100610-d7c35a00-d22f-11e8-92b6-59d4a0d07626.png)
![gutedss3](https://user-images.githubusercontent.com/44237651/47100611-d7c35a00-d22f-11e8-8cf5-354d3fc0c0b7.png)
![gutedss2](https://user-images.githubusercontent.com/44237651/47100612-d7c35a00-d22f-11e8-8fb1-c0338991b3b8.png)
![gutedss1](https://user-images.githubusercontent.com/44237651/47100613-d85bf080-d22f-11e8-8c56-93c3896e190f.png)

**Comment by designsimply** [comment] 2018-10-17 18:05
Thank you for testing Gutenberg at this stage! I am closing this issue as a duplicate of #7932 and noting that the detail in your report should be very useful. It looks like #7932 needs a developer to step up but there haven't been any takers yet! I see it's on the milestone for 5.0 so it will get reviewed and hopefully someone can pick it up.

**Closed by designsimply** 2018-10-17 18:05 UTC
Labels: Needs Testing

**Comment by fluffyfour** [comment] 2018-10-18 21:01
Thanks for letting me know. Glad the detail will be useful. I’m an ex IT Project Mgr so know the annoyance of vague bug reports.

Have stopped using Gutenberg on that site, but may try it on some others. Am now a Wordpress exclusive web designer (among other things), so plenty of sites to practice on!

Joanna
