### ISSUE TITLE
Problem with Russian language 

### ISSUE THREAD

**Issue by daskel** [WordPress/gutenberg#13007] opened 2018-12-19 09:59 UTC
I install latest Russian WordPress version. All elements in admin panel on Russian. Default theme. Without any plugins. But edit post peges (gutenberg ui) on English. How fix this? How change on Russian language?

**Comment by daskel** [comment] 2018-12-19 10:11
![alt](https://pp.userapi.com/c845523/v845523287/15b36f/rjtCKbJ4tPs.jpg)

**Comment by swissspidy** [comment] 2018-12-19 12:48
There is an issue with translations if your site is installed in a subfolder, which is the case here. It will be fixed in WordPress 5.0.2

**Comment by swissspidy** [comment] 2018-12-19 14:13
Closing as duplicate of #12979.

You can test the current Release Candidate for that version here: make.wordpress.org/core/2018/12/18/wordpress-5-0-2-rc2

**Closed by swissspidy** 2018-12-19 14:13 UTC
Labels: [Status] Duplicate, i18n
