### ISSUE TITLE
Contextual toolbar border is shown when toolbar is disabled

### ISSUE THREAD

**Issue by joshuatf** [WordPress/gutenberg#49418] opened 2023-03-28 22:16 UTC
### Description

When setting `__experimentalToolbar` as `false` in a block's metadata, the contextual toolbar is hidden.  However, the border for the toolbar is still shown as a single dot since no content exists in the toolbar.

### Step-by-step reproduction instructions

1. Create a block with the following metadata:
```json
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 2,
	"name": "custom/block-name",
	"title": "Your block name",
	"category": "widgets",
	"supports": {
		"__experimentalToolbar": false,
	},
}
```
2. Focus the block
3. See the dot appear where the toolbar should be

### Screenshots, screen recording, code snippet

<img width="229" alt="Screen Shot 2023-03-28 at 3 00 16 PM" src="https://user-images.githubusercontent.com/10561050/228378263-56dbb255-d5e9-4186-8074-d862d40529ab.png">

(See the dot directly above the input field)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-03-29 03:04
@joshuatf 
Thank you for the report. 

I have tested with the following code and could not reproduce it.

```javascript
wp.blocks.registerBlockType( 'gutenberg/no-toolbar-block', {
	apiVersion: 2,
	title: 'No Toolbar Block',
	supports: {
		'__experimentalToolbar': false,
	},
	edit: function () {
		const blockProps = wp.blockEditor.useBlockProps();
		return wp.element.createElement( 'div', blockProps, 'No Toolbar Block' );
	},
	save: function () {
		return null;
	},
} );
```

The WordPress version is 6.2 RC4 and I tested both with and without the latest Gutenberg plugin enabled. Can you tell me what version of WordPress and Gutenberg plugins you used for testing?

![toolbar-block](https://user-images.githubusercontent.com/54422211/228416027-693eca82-bb65-4f6b-99f4-6bd3a111ae23.png)

**Comment by joshuatf** [comment] 2023-04-20 18:13
Thanks for the quick reply @t-hamano!

Sorry, I was wrong on the testing instructions for this.  This actually occurs when a block does not have `__experimentalToolbar`, is still editable, and has a parent with a template lock of `contentOnly`.

To reproduce:

1. Create a parent block with:
```
// block.json
{
	...
	"templateLock": "contentOnly"
}
// edit.tsx (render)
<InnerBlocks templateLock="contentOnly" />
```
2. Create a child with a content role:
```
// block.json
{
	...
	"attributes": {
		"content": {
			"type": "string",
			"__experimentalRole": "content"
		}
	},
}
```
3. Focus the child field.
4. Note the toolbar border as a single pixel.

I believe that is due to the content lock check here that prevents the toolbar from rendering:
https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-editor/src/components/block-toolbar/index.js#L132-L145

Unfortunately, that the wrapper has already been rendered at this point, making the border visible but without any content:
https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-editor/src/components/block-tools/block-contextual-toolbar.js#L71-L79

**Comment by t-hamano** [comment] 2023-04-21 11:45
I tried testing with the following code:

```javascript
const el = wp.element.createElement;
wp.blocks.registerBlockType( 'gutenberg/test', {
	apiVersion: 2,
	title: 'Test Block',
	category: 'text',
	supports: {
		__experimentalToolbar: false,
	},
	edit: function () {
		return el(
			'div',
			wp.blockEditor.useBlockProps(),
			el(
				wp.blockEditor.InnerBlocks,
				{
					template: [ [ 'core/paragraph', { content: 'Hello World'} ] ],
					templateLock: "contentOnly",
				}
			)
		);
	},
} );
```

The parent custom block has `__experimentalToolbar: false` and InnerBlocks specifies `tempateLock:contentOnly`.
The child paragraph block has the content role. The condition should be met, but I cannot reproduce it.

Is there anything I missed?

![capture](https://user-images.githubusercontent.com/54422211/233627731-621a24dc-2c94-4951-849f-1d76b0cee4e6.png)

**Comment by t-hamano** [comment] 2024-01-15 13:02
I tested again with WordPress 6.4.2 and was unable to reproduce the issue, regardless of whether the latest Gutenberg plugin was enabled or not.

@joshuatf I would like to close this issue, but if you are still having problems, please feel free to comment.

**Closed as not planned by t-hamano** 2024-01-15 13:02 UTC
Labels: [Type] Bug, [Feature] Blocks, General Interface
