### ISSUE TITLE
Overriding "'wp-components" styles makes ".components-visually-hidden" elements visible

### ISSUE THREAD

**Issue by a-danae** [WordPress/gutenberg#35435] opened 2021-10-07 15:38 UTC
### Description

When using the [VisuallyHidden](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/visually-hidden) component, its contents are being displayed. The contents shouldn't be visible, as explained in the component's README file.

Original report [here](https://github.com/Automattic/woocommerce-payments/issues/3033).

### Step-by-step reproduction instructions

1. Install and activate [WooCommerce](https://wordpress.org/plugins/woocommerce/) and [WooCommerce Payments](https://wordpress.org/plugins/woocommerce-payments/)
2. Register a test account for WooCommerce Payments as explained [here](https://docs.woocommerce.com/document/payments/testing/dev-mode/)
3. Go to `/wp-admin/admin.php?page=wc-admin&task=woocommerce-payments--additional-payment-methods` and enable the new checkout experience (step 1)
4. When step 2 is displayed, notice things look fine
5. Install and activate Gutenberg
6. Go to `/wp-admin/admin.php?page=wc-admin&task=woocommerce-payments--additional-payment-methods`  again, and notice the UI is broken

Things look fine when commenting out [this style override](https://github.com/WordPress/gutenberg/blob/trunk/lib/client-assets.php#L319) from Gutenberg.

### Screenshots, screen recording, code snippet

On WooCommerce Payments, we're using the VisuallyHidden component to add context for screenreaders for tooltips [here](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/payment-methods-checkboxes/payment-method-checkbox.js#L28).

This is how things look like when Gutenberg is disabled, which is the expected appearance:
![image](https://user-images.githubusercontent.com/41606954/136415184-d97cd1d2-8e96-4947-8a68-877d6a7cf75a.png)

This is how things look like when Gutenberg is enabled, which is the issue being reported:
![image](https://user-images.githubusercontent.com/41606954/136415348-2720300e-553f-48c5-a659-858810e90c34.png)

### Environment info

WordPress: 5.8.1
Gutenberg 11.6.0 and 11.7.0-rc.1
Theme: Storefront
Browser: Chrome
Device: MacBook Pro with macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2021-10-11 04:01
This sounds pretty complex.

I think the issue is that a plugin might be importing an older version of VisuallyHidden from WordPress that used scss styles. When the Gutenberg plugin is active those styles are no longer present in the components stylesheet because the new version of VisuallyHidden uses css-in-js (https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/visually-hidden/styles.js).

Sounds like a problem that might occur with other components that are rewritten to use css-in-js.

I imagine woocommerce and other plugins could probably solve this by using the latest version of `@wordpress/components`, but there still might be an underlying backwards compatibility issue here for plugins.

cc @ciampo.

**Comment by ciampo** [comment] 2021-10-11 18:28
Thank you @talldan , I'll try to have a deeper look at this issue in the upcoming days and I'll come back here with any findings.

**Comment by a-danae** [comment] 2021-10-11 18:52
Hey @talldan! Yup, looks like the issue is no longer present after upgrading to the latest `@wordpress/components` version. There are still some other details to consider before upgrading on our end, though, so I've sent a PR to overwrite the styles on our end in the meantime. I guess we could close this issue, but leaving it up to you as I'm not sure what's the process here.

Thanks for checking this out and for your feedback!

**Comment by ciampo** [comment] 2021-10-12 07:54
Hey @a-danae , upgrading to the latest version is the correct thing to do here.

In general, we're in process of migrating the components internal styling system to Emotion. While this will practically be just an internal implementation detail, one consequence is that external code relying on hardcoded classnames can stop working. As a rule thumb, and to avoid further issues like this one, we shouldn't rely on the classnames of these components.

In any case, thank you for flagging and for being able to take care of the issue on your end! @talldan , I believe we can close this issue?

**Comment by a-danae** [comment] 2021-10-12 12:03
My pleasure!

Gotcha, makes sense. Thanks for the context, @ciampo!

**Comment by mirka** [comment] 2021-11-02 17:35
Closing as this looks like it was resolved.

**Closed as completed by mirka** 2021-11-02 17:35 UTC
Labels: [Package] Components
