### ISSUE TITLE
Scroll beyond end of file

### ISSUE THREAD

**Issue by Studio384** [WordPress/gutenberg#7382] opened 2018-06-19 21:45 UTC
**Is your feature request related to a problem? Please describe.**
When writing a post, it is very unpractical that Gutenberg goes all the way to the bottom of the window because on a large screen, this means that you might be writing a text file at the bottom of your screen, which is uncomfortable.

**Describe the solution you'd like**
Make it possible to scroll beyond the end of the blog post. With the "normal" writing experience in WordPress, you can just scroll the writing area in the middle of the screen and you're good to go, you can't do that with Gutenberg, and allowing to scroll beyond the bottom would fix that.

**Describe alternatives you've considered**
No other solutions I can think of, but it is probably worth noting that at least in Edge, it is possible that when you're at the bottom of the window and a new line start, the window doesn't scroll up and you end writing below the view of the window.

**Comment by karmatosed** [comment] 2018-06-25 14:37
I think it could be nice to as you type at the bottom into a block perhaps scroll page up. I am cautious because I do want to have the experience of being at the bottom. This will help when more layout aspects come into Gutenberg with phase two.

**Comment by youknowriad** [comment] 2019-04-19 16:38
I think #14852 is a duplicate of this issue. While this one is older, I'm going to leave the other one instead as a bit more detailed.

**Closed by youknowriad** 2019-04-19 16:38 UTC
Labels: Input Interaction

**Comment by Studio384** [comment] 2019-04-19 18:56
I don't see how this is less detailed. Also, note that this is also a bug report because not scrolling beyond the bottom when the cursor gets there is extremely annoying, for every line written you have to scroll again and again (as noted in the top post).

**Comment by youknowriad** [comment] 2019-04-19 20:07
@Studio384 yes true, I'd say it's very equivalent, if you have extra thoughts please add them to the other issue. The important thing is to consolidate in a single issue as it keeps a healthy and consistent backlog.
