### ISSUE TITLE
getEntityRecord resolver always queries the API even when the data is already stored

### ISSUE THREAD

**Issue by lindapaiste** [WordPress/gutenberg#19153] opened 2019-12-15 20:47 UTC
**Describe the bug**
The core resolvers, specifically "getEntityRecord" will ALWAYS fetch their data from rest when they are first called for a given type/id combo.  This presents an unnecessary re-fetching of data if the entity has already been seen and stored through a call to "getEntityRecords". 

This is not a major issue, but it is an inefficiency that can be avoided.

**To reproduce**
Suppose you want to show the edited titles of a group of posts.  First you use would call "getEntityRecords" for your query, which calls the API and saves all of the returned entities into the store.  In order to show the edited title, you would loop through the items and call "getEditedEntityRecord" for each, which internally calls "getRawEntityRecord" then "getEntityRecord."  This is the first call of "getEntityRecord" for this id, so it will call the API to request the entity, even though the entity's queried data already exists in the store.

**Expected behavior**
I would expect the getEntityRecord resolver to first look at the state (select) and return if no fetching is required.

**Comment by mcsf** [comment] 2019-12-16 11:48
By design, **resolvers** are meant to always perform the necessary requests to resolve some piece of data when called.

This is why, generally speaking, **selectors** are the preferred tool for accessing data. Indeed, for any resolver there must be a selector with the same name (the opposite isn't true).

In the case you cite, the `getEntityRecord` **selector** should be called, and this will internally call the resolver as needed. Calling a selector with a query that has already been satisfied will not trigger a new unnecessary request. This seems to be the behaviour that you are interested in.

The one thing to be aware of is that selectors are synchronous. Consequently, the first time a selector is called, if data needs to be resolved, then the selector will return some form of empty results (which could be an empty array, an undefined value, etc.). It is thus important to use selectors in contexts that can handle this. 
* For instance, using the `useSelect` hook inside components guarantees that the component will be rerendered with the resolved data once that data is ready.
* In addition, for advanced cases, there are some ["meta-selectors"](https://github.com/WordPress/gutenberg/blob/5f07b19c8f5826b3c4a3787f2cd752cc133229bc/packages/data/src/namespace-store/metadata/selectors.js) available such as `hasFinishedResolution`, `isResolving`, etc. See [example usage in the Navigation block](https://github.com/WordPress/gutenberg/blob/bfd1117846c7802d62dbba046c27968d961781e7/packages/block-library/src/navigation/edit.js#L210-L211).

Let me know if this answer is helpful. If so, we can close the issue.

**Closed** 2019-12-18 12:03 UTC
Labels: [Package] Core data, [Package] Data, [Type] Help Request, [Type] Question
