### ISSUE TITLE
Popup is getting overlapped in the editor.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#24438] opened 2020-08-07 11:37 UTC
**Describe the bug**

Popup is getting overlapped on the block listing.

WordPress version : 5.5 RC2

**To reproduce**
1. Go to 'Editor.'
2. Click on 'add icon'
3. Type "/" slash 
4. Clicking on the add icon button 

**Expected behavior**
Block listing popup should not be overlapped with the block listing

**Please find the below attached video **
https://www.loom.com/share/34ca709e882540fd9d670038f9bccb79

**Comment by ellatrix** [comment] 2020-08-17 12:40
I think I've seen this issue reported before. The problem seems to be that the active selection moves to the search field and the popover position is moved there. Rather than moving the popover, we should close it.

**Comment by talldan** [comment] 2021-07-21 08:20
I can't reproduce this any more. I don't think the steps are particularly clear, so maybe I'm not testing correctly. I'll close the issue, but if it still happens it can be reopened.

**Closed by talldan** 2021-07-21 08:20 UTC
Labels: [Feature] Inserter, [Type] Bug
