### ISSUE TITLE
Add Footnotes Support

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#1890] opened 2017-07-13 19:13 UTC
Implement a block for footnotes.

---

Prior pull requests: #2818

**Comment by swissspidy** [comment] 2017-07-13 19:17
Interesting suggestion, thanks! Have you had anything in mind how this could be resolved  UI-wise?

I mean, displaying footnotes is one thing. But you also need to add them to words/sentences/paragraphs somehow in the first place.

**Comment by androb** [comment] 2017-07-14 15:25
It is a good question. It is an "insert inline at cursor" action which I do not believe we have modeled before. 

Under the current UX regime, I believe it would belong alongside link on the inline toolbar that pops up over each block... but it doesn't feel like a commonly enough used function to occupy such prime real estate.

May be we keep it in the Insert drop-down but it behaves somewhat differently?

Perhaps @annaephox has some thoughts?

**Comment by karmatosed** [comment] 2017-07-19 20:21
I really like this idea and think a lot of users would want this.

**Comment by EphoxJames** [comment] 2017-07-24 04:24
The tricky bit with footnotes is that they need to be coordinated across block boundaries. In my mind footnotes need 3 things:

- Link to some external resource
- Short description about the external resource (could be pulled from the external resource directly using the same techniques as for embeds)
- Knowledge of their position in the overall document so they can be numbered.

If the editor has control over the whole document then they are easy. Just allow users to insert a link with a "footnote" toggle button that applies a style or a data attribute. Then before save of the entire document, you process the document to find all of the link tags that have the appropriate style or data attribute. You move the links to the footnote block of the document and then replace them in the edited block with a link to the entry in the footnote. On edit you do the reverse, you find all the footnote locations and reinsert the original link.

**Comment by iseulde** [comment] 2017-09-27 00:51
I'm pretty excited about footnotes. I think it should be supported in core, as it's something that really needs to be baked in and it's quite common for people to use.

# Adding

* We probably don't want to be adding too much UI when you're not using them. We'll need a button in the formatting toolbar for sure, but maybe we can introduce a "Footnotes" block, which is inserted at the bottom, and only with this block present the button in the formatting toolbar pops up.
* There should be a shortcut. Probably `[1]` etc. (order should be autocorrected) and using an existing number links to an existing footnote. `[#]` (or any not yet existing number) to create a new item without having to know the correct number.
* It would be nice if, once you click the button or complete the shortcut, a field slides in at the button that auto-focusses (you can continue typing from the shortcut), enter submits it and puts the caret back after the reference mark.

# Editing

* The reference mark `[1]` looks like a superscripted link, and when the caret goes in the boundaries, the footnote field slides in again at the bottom.
* You can also go to the bottom and edit the footnotes in the footnote block. The reference mark links to the footnote, and the footnote links to the reference mark.

# Deleting

* I think for sanity, it should only be possible to delete the reference marks (which deletes the footnote). Of course you should be able to bring it back with undo.

At a state/reducer level, insertion and delete (or only post save if we don't want numbers/order in edit mode) will both have to look through all editable content to determine order.

**Comment by iseulde** [comment] 2017-09-27 09:19
Actually, we don't even have to loop through all editable areas, only look at the editable area the current one is in and sort. We could add the footnotes as properties to each block, and the footnotes block could put these together based on the block order.

**Comment by iseulde** [comment] 2017-09-27 09:24
Going to assign to look at in the near future.

**Comment by aaronjorbin** [comment] 2017-09-27 16:07
I love footnotes, but I think this might be something that belongs as a property to the post, rather than as a block. Two thoughts:

1) How do we ensure if it is a block, that it can be locked to the bottom of the post (i.e. that there is never a case when footnotes are in the middle of a post)
2) If you are using multiple pages ( via `<!-- next-page -->` or whatever form that has taken in Gutenberg) in a post, that the footnotes appear on each page and are numbered correctly for that page.

**Comment by dsifford** [comment] 2017-09-27 19:41
@iseulde I'd be happy to work with you on this.

Check out https://wordpress.org/plugins/academic-bloggers-toolkit/. I've been working on a pretty good academic citations plugin over the last 3 years (although, I am biased!).

There's quite a few hidden difficulties that come with managing references and footnotes that I'd imagine most people don't consider early on (I was one of those people). I'd be happy to discuss this in detail if this is something you'd be interested in pursuing.

**Comment by karmatosed** [comment] 2017-09-27 19:46
This is just a v1 but the basic design could look like this:

1. A simple option is added to the toolbar. We will have to iterate the graphic but after doing some research this is a good starting iconography for footnotes.

![footnotes-1](https://user-images.githubusercontent.com/253067/30934155-989dc62a-a3c4-11e7-92fc-82db17fed79c.png)

2. Following on from creating a footnote, the footnote block would appear. This has no options, we can discuss if it should have options. I'm cautious this can be deleted even, if you have footnotes why would you delete? Isn't just remove a footnote the delete?

![footnotes-2](https://user-images.githubusercontent.com/253067/30934230-dab47ed2-a3c4-11e7-85d5-b3450b1d7db6.png)

Perhaps people would want a title, but for now this shows the minimum I think footnotes would make sense. I'm very cautious we do not spiral this feature, it could easily spiral.

**Comment by jasmussen** [comment] 2017-09-28 07:18
Love those mockups, Tammie, I think they provide a solid basis and can help our minds grok the side effects and everything. The "deleting" thing is one issue that immediately pops up, but that seems solvable by looking at how other editors have done it — perhaps a "are you sure" prompt is sufficient. 

The icon also is almost there, with a popout label I'm sure people will get it.

But one thing I keep coming back to is — it's very very clear that we need to be able to both add more buttons to the quick toolbar, and stay responsive. 

This is how Google Docs does it:

![more](https://user-images.githubusercontent.com/1204802/30953840-eeb760ac-a42d-11e7-802e-2a7e4c54bf4d.gif)

This is how it could look for us:

![quick toolbar alt](https://user-images.githubusercontent.com/1204802/30953838-ede99d8e-a42d-11e7-850f-e943b28f7d4d.png)

**Comment by dsifford** [comment] 2018-09-11 23:46
@RayWaldo When the gutenberg API stabilizes just a bit more (and also when I have the time) I plan on converting [my plugin](https://wordpress.org/plugins/academic-bloggers-toolkit/) to gutenberg and include first-class footnote support. Can't give a time-frame for when that will precisely happen though.

**Comment by johanneswilm** [comment] 2018-09-22 21:39
@dsifford Great work with your plugin!

I am working on [Fidus Writer](https://www.fiduswriter.org) and I'm trying to make sure that copy-and-pasting from Fidus Writer to Wordpress works well. I noticed that it's really hard to make the kinds of internal links for footnotes you are currently producing, @dsifford, as `<div>`s are not allowed and `<p>`s are not allowed to have `id`s. So the only way one can make footnotes is by making them headlines - something like `<h6>`. That will look ok or not depending on the styling of `<h6>`.

The advantage of dsifford's work is really that the footnotes continue to work even if one uninstalls his plugin because he stops maintaining it, etc. . Yet that advantage goes away with Gutenberg, as far as I can tell.

One solution could be to allow `id`-attributes on `<p>`. There could be other solutions.

**Comment by aaronjorbin** [comment] 2018-10-07 18:06
@mtias I put future back on this.  If there is a different target for this, can you please move it to the appropriate one.

**Comment by mtias** [comment] 2018-10-07 18:27
"Future" is correct, I misclicked while managing the Bonus Features so we could close it.

**Comment by jcklpe** [comment] 2018-11-26 21:33
Just wanted to throw in my two cents, that I'd love to see this implemented, or at least something in the Gutenberg API (similar to how one can create one's own custom inline styles using the new Rich Text API) that makes it possible for individual theme/block developers to implement themselves.

I've been meaning for awhile to create a footnote feature in my personal blog theme using ACF or something of that sort, but I'm fully bought in on Gutenberg and found this page when trying to look up how I could make my own gutenberg compatible inline footnotes etc. 

Also I'll echo previous sentiments that I don't think of footnotes as just for external sources. In fact, I would really like to implement my own footnotes solely as a means of adding extra information to or next to a piece of text. This could be a link externally, or a bit of extra info, or perhaps even an image or a video! When taken in it's most flexible and generalizable form, I think it can be thought of as being sort of like a hyperlink that triggers a modal container. 

Could something be built off it with the Rich Text API? Like if the hyperlink is now using the Rich Text API, then a footnote can be thought of as "a hyperlink whose scope is to content already inside the page" essentially, right? I hope that makes sense and isn't just gibberish. 

EDIT: I think you can kinda add ID elements on inline stuff using the Rich Text API @johanneswilm

**Comment by jcklpe** [comment] 2018-12-07 23:18
> 
> 
> @jcklpe Working on this as we speak for my plugin. Citations are being prioritized, but footnotes should be done shortly after. It's looking like it should be done sometime early January if all goes well (doing this in my spare time).
> 
> @johanneswilm Sorry I missed your message before. RichText allows for custom `data-` attributes, which is what I'm going with for my implementation. Feel free to shoot me an email if you want to talk more on this.

Hey I've also been thinking about diving into making my own custom Rich Text stuff for gutenberg. I just finished a mini course on building custom blocks. Seems pretty easy so far but I have no clue how to get started for Rich Text. I don't even really know where the documentation for it is? You have any ideas or suggestions @dsifford   ?

**Comment by johanneswilm** [comment] 2018-12-08 01:31
Ok, yeah so not having copy/paste access is somewhat problematic as that continues to be the #1 easiest method for 99.9% of users. Power users with extensive programming experience will be able to set up API access from some other site, etc. .

Just think about what you would do if a random friend asks you to just help them quickly transfer a document they have written in Google Docs or some other editor to make a new blog post in their Wordpress site. My guess is you'll try to copy-and-paste and then spend a few minutes cleaning the result up, rather than try hunting down plugins for Google Docs and Wordpress that enable API access and add menus to transfer the document in some other way.

**Comment by dsifford** [comment] 2018-12-08 01:45
@johanneswilm There's gotta be sanity and security checks before allowing anybody to just arbitrarily paste in HTML, so they're doing the right thing.

If you needed to add copy and paste raw HTML functionality to the editor, you can do that pretty easily by adding in a modal dialog that accepts HTML in a textarea form. When the user clicks the submit button, the plugin can just sanitizes the potential bad stuff first, and then insert it programatically using the API. 

But with all that said, I think it's probably possible just to copy and paste raw HTML into the "Code editor" of Gutenberg. If the text format was registered correctly, it _should_ just pick up on that. Similar to the old TinyMCE editor.

**Comment by johanneswilm** [comment] 2018-12-08 07:44
> There's gotta be sanity and security checks before allowing anybody to just arbitrarily paste in HTML, so they're doing the right thing.

Sure. But there is no reason this should go as far as making it impossible to copy and paste footnotes. That script tags are being removed, inline CSS, etc. goes without saying. There should be a way for plugins to have a say in what is being stripped out.

> If you needed to add copy and paste raw HTML functionality to the editor, you can do that pretty easily by adding in a modal dialog that accepts HTML in a textarea form. [...]

Sure. But that's similar to a car engineer telling a normal person "Wheelchair passengers cannot get in through the door. But if you remove one of the windows and use a crane, you can get the wheelchair in like that." For the car engineer who has a crane standing around at home and has replaced a million windows this seems easy as pie. The problem is the average user who will not be able to figure out to do anything beyond opening the door and trying to get in that way. 

There is no good explanation for average users why footnotes  are toxic and cannot be copied, whereas headlines can. And it's not impossible to program this either in a way that is both sane and user friendly.

**Comment by dsifford** [comment] 2018-12-08 17:02
@johanneswilm I just tested pasting html directly into the visual editor and it seems to work for supported/registered elements (e.g. blockquotes).. So I think this conversation is largely not even valid.

I'd refer you to one of the core contributors to this project for further clarification just so I don't misspeak and add to the confusion.

**Comment by johanneswilm** [comment] 2018-12-08 18:21
@dsifford Yes, so I opened [this](https://github.com/WordPress/gutenberg/issues/10118) to figure out what can be pasted and what cannot. I hope to get an answer there eventually.

Something related came up in a break of this year's [W3C Editing taskforce](https://github.com/w3c/editing) meeting at TPAC: Copy and pasting between Google Docs and Wordpress does not work that well, which is surprising given the number of users this will affect worldwide. One solution mentioned by the browser maker devs was that Wordpress could provide and consume its own mimetype format from the web clipboard. That way it could use a subset of HTML specifically targeting Wordpress when integrating pasted content. Another solution would be to organize a meeting/conference for difference web based editors and try to agree on some kind of standard transfer format (please invite me if such a meeting is to be held).

**Comment by dsifford** [comment] 2018-12-08 19:47
Sweet! I'll be sure to follow along in that issue thread.

Good point Re: Google Docs and WordPress not pairing well. That's affected me personally dozens of times. (Specifically, the fact that Google Docs seems to want to add `<span style="font-weight: 400">` to anything that has had bold toggled.

**Comment by nicopujol** [comment] 2019-01-02 22:08
I am writing an article in Gutenberg now, trying to add a footnote like(1) at the end of the post. Until the feature is ready, is there any workaround we can use in the text editor? I am not cut & pasting, writing from scratch. Thanks!

**Comment by dsifford** [comment] 2019-01-06 17:39
Beta is nearly ready. Would any of you like to try kicking the tires? Still might be somewhat buggy, but it seems to do the job so far.

Here's a small demo: 

https://www.useloom.com/share/fef8ab0d7ba34186aa8129d1924844cc

(I figured out why the tooltip didn't generate properly in the demo... fixing that right now).

**Comment by nicopujol** [comment] 2019-01-06 20:11
Looks great on the demo! Do you have a link to the beta plugin in ZIP or uncompressed format to load in WordPress? I'll take it for a test drive.

**Comment by jcklpe** [comment] 2019-01-06 20:35
Woo! I'm excited. Going to try the demo now. Should I just git clone the dev branch into my plugins folder?

**Comment by dsifford** [comment] 2019-01-06 23:07
Sorry for the delay. Here ya go!

[academic-bloggers-toolkit-5.0.0-beta.1.zip](https://github.com/WordPress/gutenberg/files/2730976/academic-bloggers-toolkit-5.0.0-beta.1.zip)

If you guys could also post any bugs you might be able to turn up [here](https://github.com/dsifford/academic-bloggers-toolkit/issues), I'd be eternally grateful :pray: 

Still a bit of housekeeping and various odds and ends to get to, so I won't be pushing this to wp.org for a little bit still. _Maybe_ next weekend.

**Comment by dsifford** [comment] 2019-01-07 03:36
I've still neglected to update the docs for the new update, but the old ones should be close enough to get you on the right track.

> Does it have any performance impact? Is everything generated cacheable?

This is one of, if not _the_, most important consideration I had when updating the plugin. Everything that I could possibly cache, [I did](https://github.com/dsifford/academic-bloggers-toolkit/blob/gutenberg/src/js/utils/cache.ts). Also, the expensive functionality (notably, re-parsing out editor citations and footnotes for changes) only occurs after a user is done typing. You can see this by adding in a footnote/citation and simply using the backspace key to delete it out.. After you stop typing for a few seconds, or click somewhere else, the footnotes list/bibliography will update.

There's still a few perf things that need to be added, but nothing too huge.

**Comment by nicopujol** [comment] 2019-01-07 06:35
Here is a test post containing a legacy footnote (MS WORD import, I believe) with a hyperlinked [1], and a footnote using your new plugin, showing as an asterix. https://bit.ly/2LRUZqI. Is there a way to make footnotes the same as the legacy example, i.e. its standard text size and with a hyperlink? Mobile users may find references easier to access and read that way.

**Comment by dsifford** [comment] 2019-01-07 23:00
@nicopujol Sorry for the delay. It is possible to make it work in the way you describe, absolutely. There are some potential issues though that I should point out:

The most salient issue is the strict differentiation of footnotes from in-text citations. Some (of the now well over 4000 available citation styles there are to choose from) are styled precisely in the way you have listed (e.g. `[1]`, `[2]`, `[1,4,5-9]`, etc..). So that's the reason I opted to go straight to using symbols.

The other issue with using the traditional anchor-style footnotes is with posts that are paged. Anchors just simply will not work in those instances.

After checking out your example page though, it is clear that the tap targets need to be made bigger on mobile; especially so when footnotes are positioned right next to a link. That's something I will probably work on.

Another thing (as I mentioned in my demo video): I do think there is some merit in allowing users to choose between symbols, numbers, and letters for their footnote format. That's something I'll likely look into after releasing the update. I think it should always default to the symbols though, just for safety with in-text citations.

To comment on your question Re: automatically converting legacy footnotes to this format: I don't think that's worth the effort. Too many potential variations to account for and the return frankly isn't really worth it for the amount of work it would require.

Hope that answers your questions. Good thoughts nevertheless. Again, I definitely think there is some progress to be made on tap targets. :+1:

**Comment by dsifford** [comment] 2019-01-08 20:11
Yeah, unfortunately in those situations, you'd just need to replace your old citations with new ones using the plugin in order for them to be tracked.

Looking back at your test post I now also see that adding `transition: all` to link elements within the tooltips causes them to behave weirdly when the tooltip hides due to the transition still applying. I'll have to stub those out in the plugin as well.

**Comment by dsifford** [comment] 2019-01-08 20:12
@nicopujol Did you try using the ISBN to insert your book citation? Assuming the book is indexed in google books, that is another alternative. If not, yeah, you'd have to add manually. I'll look into maybe adding a URL field to books.

**Comment by jcklpe** [comment] 2019-01-16 00:01
@dsifford 

Hey sorry for the delay in testing the plugin. 

Unfortunately when I tried to activate the plugin I got this response:

```
Parse error: syntax error, unexpected '}', expecting identifier (T_STRING) in /home/jcklpe/jackalope.tech/wp-content/plugins/academic-bloggers-toolkit/php/admin.php on line 16
```

![image](https://user-images.githubusercontent.com/9451726/51217768-0e704580-18ef-11e9-9597-db87f88dd4ee.png)

Some additional thoughts:

I know this is primarily an academic tool, but my biggest interest is in the footnotes functionality, and I'd love to see that expanded a bit more. Namely, I think it would be interesting to allow a wider diversity of content to be linked through footnotes. So right now it can only be used to display some text, but it could also be used hypothetically to show a video or image on mouseover. It seems to me that if one were to treat the individual footnotes as their own individual sub blocks you could possibly genericize the footnote content to the point where it could easily be adapted to almost any other kind of gutenberg child block type, even ones not created by you specifically. Just a thought.

**Comment by dsifford** [comment] 2019-01-16 00:21
Whoops, sorry @jcklpe... I forgot to mention that I'm being super opinionated and am requiring PHP 7.2+ for the update since I work on this in my spare time and don't feel like supporting older PHP versions.

> but it could also be used hypothetically to show a video or image on mouseover. It seems to me that if one were to treat the individual footnotes as their own individual sub blocks.

Interesting idea! Unfortunately, that's a bit outside the scope of the plugin I'm working on so I'll let others take the lead on pursuing something like that.

**Comment by jcklpe** [comment] 2019-01-16 01:31
Totally, yeah I prefer to use php also. This is on my host, so I'll have to see if I can upgrade stuff.

**Comment by paaljoachim** [comment] 2020-11-24 17:30
Hey Ella @ellatrix 

It would be great with a status update to how the issue is coming along.
Thank you!

**Comment by rodrigo-arias** [comment] 2021-07-08 14:58
Thanks for everyone's work here, it will be great to have this feature.

**Comment by FedericoPistono** [comment] 2021-09-25 13:48
Thanks for the great work! 🙏🏻

Will definitely use footnotes in Gutenberg on a daily basis as soon as they're available.

**Comment by nooblag** [comment] 2023-05-11 04:57
I'm excited for this to come out too. :)

**Comment by mtias** [comment] 2023-06-29 15:04
Marking this as done!

**Closed by mtias** 2023-06-29 15:04 UTC
Labels: [Feature] Blocks, [Status] In Progress, [Package] Format library

**Comment by bph** [comment] 2023-06-29 19:01
PR to introduce Footnotes to WordPress block editor:

- #51201
