### ISSUE TITLE
Single quotes in content following bold text get curled the wrong way

### ISSUE THREAD

**Issue by dknauss** [WordPress/gutenberg#42345] opened 2022-07-12 00:20 UTC
Apostrophes in content get curled in the wrong direction (to the right) in the screen output (not within the editor) when used after bold text. E.g., **He**'s will be rendered like this:

<img width="26" alt="Screen Shot 2022-07-11 at 6 01 18 PM" src="https://user-images.githubusercontent.com/273554/178379392-c5b06008-6cf4-4f11-9c0b-b6f104ff87dc.png">

**Probably related to ye olde `wptexturize` filter:** #37754, #2199.

**Comment by kathrynwp** [comment] 2022-07-12 14:20
Hi @dknauss - thanks for your report. So far I haven't been able to replicate this. Here's a front-end screenshot:

![Bold_Apostrophe_–_Self-hosted_Test](https://user-images.githubusercontent.com/7662449/178511876-7db83ab4-2a12-4024-9bd7-5fcea9a4af48.jpg)

My test setup:

- WordPress 6.0
- Gutenberg 13.6.0 - active or inactive
- No other plugins active
- Twenty Twenty-Two
- Paragraph block

Could you please provide detailed steps to replicate, as well as your WP and Gutenberg version, and theme name/version? Could you provide a link to a page or post where the problem is visible? Thanks!

**Comment by dknauss** [comment] 2022-07-12 17:19
Hi @kathrynwp, the output you are showing is actually (typographically) incorrect and exactly the same as my example. Yours is just much more subtle due to the font used by Twenty Twenty-two. I was fooled by this as well when I first replied. This comment has been heavily edited. :-) 

I also realized "apostrophe" is not exactly the right term to use, so I updated the issue title as well. 

The issue I've identified has to do with single quotation marks — Unicode Character “'” ([U+0027](https://www.compart.com/en/unicode/U+0027)) being potentially transformed into Unicode Character “‘” ([U+2018](https://www.compart.com/en/unicode/U+2018)) *or* Unicode Character “’” ([U+2019](https://www.compart.com/en/unicode/U+2019)). 

(U+0027) is identified as an "apostrophe" in PostScript corresponding to the Unicode HTML entity `&apos;`, `&#39; &#x27;`. That character is _not_ appearing in the test cases I've shared. 

Using the same test setup as you (a paragraph block in WP 6.0 with no other plugins, with or without Gutenberg 13.6.0 active), this is the content I started with in the editor — in the first screenshot below. The Avant-Garde theme is active there but just in the first example. The text, formatting, and `'` characters are the same in the editor (and the rendered page source) in all themes tested here.

<img width="571" alt="Screen Shot 2022-07-12 at 10 57 29 AM" src="https://user-images.githubusercontent.com/273554/178552137-b2454dc2-0a70-4307-8eff-7073639406fc.png">

Underlying markup in the editor:
<img width="373" alt="Screen Shot 2022-07-12 at 10 57 58 AM" src="https://user-images.githubusercontent.com/273554/178552865-9863e086-cc1d-4fac-a984-a250050512be.png">

Post output with the **Avant Garde** theme showing misdirected single quotation marks: 
<img width="701" alt="Screen Shot 2022-07-12 at 10 58 13 AM" src="https://user-images.githubusercontent.com/273554/178553183-49e843c5-3d70-4159-a658-91de9a9e3015.png">

Post output with the **Twenty Twenty** theme showing misdirected single quotation marks: 
<img width="709" alt="Screen Shot 2022-07-12 at 11 01 02 AM" src="https://user-images.githubusercontent.com/273554/178553617-104d8720-549c-4e10-b1a8-2aee730d343c.png">

Rendered HTML source with the **Twenty Twenty** theme activated — single quotation marks are bad, as shown above:
<img width="337" alt="Bad 2020 Screen Shot 2022-07-12 at 11 01 53 AM" src="https://user-images.githubusercontent.com/273554/178556064-80483486-d6a4-4bd5-84b9-b44d8c8c2737.png">

Rendered HTML source and post output with the **Twenty Twenty-One** theme activated — _single quotation marks are bad_ — but it's _much_ harder to detect visually. It fooled me at first:
<img width="724" alt="Screen Shot 2022-07-12 at 11 23 22 AM" src="https://user-images.githubusercontent.com/273554/178554712-4407252c-72b3-4a6e-8740-44eb4fda97aa.png">

Rendered HTML source with the **Twenty Twenty-Two** theme activated — again, the wrong output but masked by the subtle differences of the font in use:
<img width="1405" alt="Actually Not Good 2022 Screen Shot 2022-07-12 at 11 00 21 AM" src="https://user-images.githubusercontent.com/273554/178553507-2c195ca5-7396-4c45-b137-da954dfd63f2.png">

In all these themes the character encoding is UTF-8, and the `&#8216;` and `&#8217;` HTML entities are created in the same pattern, presumably by [`wptexturize()`](https://developer.wordpress.org/reference/functions/wptexturize/), under which `&#8217;` always seems to follow the `</strong>` tag. 

I think that should be/is? considered a bug in `wptexturize`. 

Discriminating accurately between '`'`' characters intended as opening or closing single quotes in all possible cases (which vary by language) isn't likely to be an option, but if they're immediately adjacent to an inline HTML tag like `<strong></strong>` with no space between them, it would make sense to have `wptexturize` ignore the `'` by default. 

Is there any chance of core making text filtering optional (there's [a 12-year-old plugin](https://en-ca.wordpress.org/plugins/wp-unformatted/) for that) and/or simpler for users to [modify with exceptions](https://developer.wordpress.org/reference/hooks/no_texturize_tags/)? :-)

There's some neat history behind all this... The infelicities of `wptexturize` are [almost as old as WordPress itself](https://lists.automattic.com/pipermail/wp-hackers/2007-July/013641.html). Its source, [Texturize](https://ma.tt/?s=texturize), was one of Matt's early projects for b2, later forked into WordPress... Here's [the whole fascinating thread](https://wp-hackers.automattic.narkive.com/l8G3CTPC/wordpress-uses-wrong-apostrophe-in-blog-title#post1).

**Comment by kathrynwp** [comment] 2022-07-12 18:43
@dknauss Thank you for the additional clarifications, super helpful – and tricky indeed! I was able to see the issue clearly in **Twenty Twenty**, with or without Gutenberg 13.6.0 active.

![Bold_Apostrophe_–_Self-hosted_Test](https://user-images.githubusercontent.com/7662449/178570366-08db7b83-314e-4eaf-b9b6-31865dc1f363.jpg)

I added a label requesting technical feedback from a developer to see what they have to say about your suggestions. Thanks again!

**Comment by dknauss** [comment] 2022-07-12 19:15
Thank you, @kathrynwp — you made me think it through more deeply and carefully. 👍

**Comment by dknauss** [comment] 2023-05-27 17:28
Just dropping this here for the #WP20 historical interest: [Matt talking about Texturize in WordPress 0.72](https://youtube.com/clip/UgkxabdUpbP3NmbIo002ivzLDKn5KQcszSDi ).

**Comment by ellatrix** [comment] 2023-08-18 07:18
This is a super old bug for wptexturize in core: https://core.trac.wordpress.org/ticket/18549

Unfortunately there's nothing we can do here in the Gutenberg repo, this must be fixed in the core repo. I'd recommend following that ticket and bringing it back up.

**Closed as completed by ellatrix** 2023-08-18 07:18 UTC
Labels: [Type] Bug, Needs Technical Feedback, [Block] Paragraph
