### ISSUE TITLE
Extending Editor UI to save Meta Data

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg#7535] opened 2018-06-25 14:54 UTC
I just can't make sense of this... 

It appears blocks are also able to save to predefined post-meta fields?
https://riad.blog/2017/10/16/one-thousand-and-one-way-to-extend-gutenberg-today/ (point 3)

But I don't see how having to add a new block to save meta is useful.
In my case I need to extend the editor UI / sidebar. Preferably add a panel right below the "revisions" panel.

So the handbook (https://wordpress.org/gutenberg/handbook/extensibility/#extending-the-editor-ui) tells me to look at these two links..
https://github.com/WordPress/gutenberg/tree/master/edit-post
https://github.com/WordPress/gutenberg/tree/master/packages/plugins 

which still leaves me with tons of issues / questions:
1. `const { PluginSidebar, PluginSidebarMoreMenuItem } = wp.editPost;` produces the following error: 
![image](https://user-images.githubusercontent.com/1983382/41857239-5415d7a6-7897-11e8-9fa8-76a12ca7e301.png) although the console shows `wp.editPost.PluginSidebar` exists 
2. Even if I get this to work, how do I make the extension represent meta data (load it..) and save it?
3. Do I also have to register the meta explicitly with PHP?
4. Is it important where I add this js code? I just put it in my custom-blocks.js, which gets registered on "init"

```js
add_action("init", function() {

	// Add Editor script for all blocks
	wp_register_script(
		"wingmag-blocks-editor-js",
		plugins_url("index.es5.js", __FILE__),
		array("wp-blocks", "wp-element")
	);

        ...
```

I want to go the gutenberg route and not use meta-boxes, but .. man, .. how?!!

**Comment by oxyc** [comment] 2018-06-25 21:32
1. You need to depend on `'wp-edit-post'` in your wp_register_script so it's available.

2. I recently wrote a plugin that adds a _Hide title_ checkbox to the _Post Status_ panel in the sidebar. Not sure if I'm using the ideal way of making it work and I don't really follow WP coding standards but it can probably help you figure out how it works https://github.com/generoi/wp-gutenberg-hidetitle/blob/master/src/component.js

3. Yes

4. It should be in the action `enqueue_block_editor_assets`. Also see point 1 about dependencies.

**Comment by katerlouis** [comment] 2018-06-27 11:59
@oxyc 
Why isn't the "usual way" of depending on components not working here?
And how do I depend on `wp-edit-post` in php? (I guess `wp_register_script` is referring to the php function?)

```js
const { registerPlugin } = wp.plugins;
const { PluginSidebar, PluginSidebarMoreMenuItem } = wp.editPost;

registerPlugin("...
```

Where'd you get the info with the subtype from? And why exactly is this necessary?

**Comment by oxyc** [comment] 2018-06-27 12:21
> Why isn't the "usual way" of depending on components not working here?

Unless you depend on `wp-edit-post` your own script could (and is) loaded before `wp.editPost` has been set. By depending on it, WP ensures it's loaded after.

> And how do I depend on wp-edit-post in php? (I guess wp_register_script is referring to the php function?)

```php
add_action("enqueue_block_editor_assets", function() {
	wp_register_script(
		"wingmag-blocks-editor-js",
		plugins_url("index.es5.js", __FILE__),
		array("wp-blocks", "wp-element", "wp-edit-post")
	);
});
```

> Where'd you get the info with the subtype from? And why exactly is this necessary?

No idea, haven't really read up on the API. It's gonna be `post`. Basically you reigster your meta with:

```php
        register_meta('post', 'custom_meta_field', [
            'object_subtype' => 'post',
            'show_in_rest' => true,
            'single' => true,
            'type' => 'string',
            ...sanitize callbacks
        ]);
``

**Comment by katerlouis** [comment] 2018-06-27 12:49
Aaah, totally forgot about the array in `wp_register_script()` – sorry; I could've figured that out myself. Gutenberg is so confusing.. So I got components from wp.editPost available in my JS now. 

And I successfully added a panel, that can be expanded by clicking the newly created icon right to the corg. Unfortunately that's not what I want.

But I want to insert content into the main panels document tab
![image](https://user-images.githubusercontent.com/1983382/41974702-f4647d2a-7a18-11e8-8a5d-9e5d9ae05280.png)

Reading here: https://github.com/WordPress/gutenberg/tree/master/edit-post
I can't find out how to extend this main panel.

**Comment by oxyc** [comment] 2018-06-27 13:06
`PluginPostStatusInfo` isn't so restricted is it? You should be able to add any control or I guess even `< PanelBody>`.

Glancing at the code I don't really see a way to plug into other parts either but haven't looked into it properly. Maybe others here can help more from now on. Good luck!

**Comment by katerlouis** [comment] 2018-06-27 13:43
Yeah, it seems to be as flexible as the rest; the docs mislead me here.

a `<PanelBody>` above the "Move To Trash" link wouldn't be so great, would it?

.. So now I am stuck with getting and saving the data with `select`/`dispatch`

The "docs" confuse me a lot, compared to your use of it
https://github.com/WordPress/gutenberg/tree/master/packages/data

**Comment by oxyc** [comment] 2018-06-27 14:23
Not sure to be honest, I just used core as an example. I'm assuming you need to structure it [like I did](https://github.com/generoi/wp-gutenberg-hidetitle/blob/master/src/component.js#L28:L39) but I bet others here provide better solutions.

**Comment by katerlouis** [comment] 2018-06-27 16:17
Okay, thank you very much! Unfortunately bundling is not an option for me, and I don't understand what this cluster of `compose` and use of `withDispatch` etc. is doing.

can you help, @danielbachhuber? I need to get this to work somehow; the deadline is pushing hard.

**Comment by danielbachhuber** [comment] 2018-06-27 16:23
> can you help, @danielbachhuber? I need to get this to work somehow; the deadline is pushing hard.

Sorry, I can't offer that level of support for every Gutenberg integration.

**Comment by oxyc** [comment] 2018-06-27 16:51
Something like:

```jsx
function CustomComponent({ testString, onUpdate }) {
  return (
    <PluginPostStatusInfo className="my-plugin-post-status-info">
      { __( 'testString' ) }
      <input 
        type="text" 
        onChange={ () => onUpdate(testString) } 
        value={ testString } 
      /> 
    </PluginPostStatusInfo>
  );
}

const component = compose([
  withSelect((select) => {
    return {
      testString: select('core/editor').getEditedPostAttribute('meta').testString,
    };
  }),
  withDispatch((dispatch) => ({
    onUpdate(value) {
      dispatch('core/editor').editPost({ meta: { testString: value } } );
    },
  })),
])(CustomComponent);

registerPlugin("my-custom-plugin", {
  icon: "hidden",
  render: component,
});
```

**Comment by katerlouis** [comment] 2018-06-27 17:11
Thanks!

Okay, apparently my approach results in atleast something similar (so far..)

When I `console.log(value)` in `onUpdate`, I get this:

![image](https://user-images.githubusercontent.com/1983382/41988904-db68d210-7a3d-11e8-937e-04fabb793b8b.png)

![image](https://user-images.githubusercontent.com/1983382/41988856-b46f0d8c-7a3d-11e8-8012-08c4f812e4bf.png)

**Comment by oxyc** [comment] 2018-06-27 19:09
Because you're just using a plain `<input>`. The value would be in `target.value`. Better to use a Gutenberg Component though. For example [`TextControl`](https://github.com/WordPress/gutenberg/blob/a72a74502daafb585bae12416e1c759166fe5912/editor/hooks/anchor.js#L68:L77).

**Comment by katerlouis** [comment] 2018-07-05 21:31
Oh boy, it's insane what lengths one has to go just to enhance a post with simple meta fields.
I really hope you guys will provide a slicker and more straight forward method of doing tasks like this, which should be really simple.

I'm having 2 major issues.

1) 98% percent of the save attempts fail. I can't figure out why it will save sometimes.
(This error does not occure, when I comment out the code for extending the sidebar)

![image](https://user-images.githubusercontent.com/1983382/42348947-68d748fc-80ab-11e8-942e-a30510eb3c37.png)

2) Everytime I interact with an UI element, the others reset? Or better said: they are just not set in this render. The values of normal input fields seem to stick, but when you want to work with the current value, it is `undefined`. And it doesn't seem to matter if a value is saved or not; the other fields are undefined in the next render.

The code should make things clearer:

```php
add_action( 'init', function() {

	register_meta( 'post', 'bananas', array(
		'object_subtype' => 'post',
		'show_in_rest' => true,
		'single' => true,
	) );

	register_meta( 'post', 'why', array(
		'object_subtype' => 'post',
		'show_in_rest' => true,
		'single' => true,
	) );
```

```js
function CustomComponent({ bananas, why, onUpdateBananas, onUpdateWhy }) {

	// everytime I interact with the UI, this function gets called and
	// logs correct value for the property I just interacted with 
	// but always logs undefined for the other, .. why?
	console.log("Bananas boolean", bananas);
	console.log("Question on why", why);

	return (
		<Fragment>
			<PluginPostStatusInfo className="my-plugin__bananas">
				<label htmlFor="bananas-checkbox">Do you like bananas?</label>
				<FormToggle
					key="toggle"
					checked={ !! bananas }
					onChange={ () => onUpdateBananas( !bananas ) }
					id="bananas-checkbox"
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo className="my-plugin__why">
				<label htmlFor="why-input" class="my-plugin__why">
					Why do you{ (!bananas) ? " not" : "" } like bananas?
				</label>
				<TextControl
					type="text"
					onChange={ (value) => onUpdateWhy(value) }
					value={ why }
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo>
				<span>
					for debugging purposes: here is the type of `why`: <i>{ typeof why }</i>
				</span>
			</PluginPostStatusInfo>
		</Fragment>
	)
}

const plugin = compose([
	withSelect((select) => {
		return {
			bananas: select("core/editor").getEditedPostAttribute("meta").bananas,
			why: select("core/editor").getEditedPostAttribute("meta").why,
		};
	}),
	withDispatch((dispatch) => ({
		onUpdateBananas(value) {
			dispatch("core/editor").editPost({ meta: { bananas: value } })
		},
		onUpdateWhy(value) {
			dispatch("core/editor").editPost({ meta: { why: value } })
		},
	})),
])(CustomComponent);


registerPlugin("my-custom-plugin", {
	icon: "hidden",
	render: plugin,
});
```


@oxyc: have you encountered something similar?
I hope @danielbachhuber can look into this, because issue 1) seems like a bug.

**Comment by jrmd** [comment] 2018-07-12 11:03
@katerlouis I have just came across the same issue you had my solution was to all of the meta to the update functions the easiest way to do this would be to change your stuff to this

```
function CustomComponent({ meta, onUpdateBananas, onUpdateWhy }) {

	// everytime I interact with the UI, this function gets called and
	// logs correct value for the property I just interacted with 
	// but always logs undefined for the other, .. why?
	console.log("Bananas boolean", meta.bananas);
	console.log("Question on why", meta.why);

	return (
		<Fragment>
			<PluginPostStatusInfo className="my-plugin__bananas">
				<label htmlFor="bananas-checkbox">Do you like bananas?</label>
				<FormToggle
					key="toggle"
					checked={ !! meta.bananas }
					onChange={ () => onUpdateBananas( !meta.bananas, meta ) }
					id="bananas-checkbox"
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo className="my-plugin__why">
				<label htmlFor="why-input" class="my-plugin__why">
					Why do you{ (!meta.bananas) ? " not" : "" } like bananas?
				</label>
				<TextControl
					type="text"
					onChange={ (value) => onUpdateWhy(value, meta) }
					value={ meta.why }
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo>
				<span>
					for debugging purposes: here is the type of `why`: <i>{ typeof meta.why }</i>
				</span>
			</PluginPostStatusInfo>
		</Fragment>
	)
}

const plugin = compose([
	withSelect((select) => {
		return {
			meta: select("core/editor").getEditedPostAttribute("meta")
		};
	}),
	withDispatch((dispatch) => ({
		onUpdateBananas(value, meta) {
			dispatch("core/editor").editPost({ meta: { ...meta, bananas: value } })
		},
		onUpdateWhy(value, meta) {
			dispatch("core/editor").editPost({ meta: { ...meta, why: value } })
		},
	})),
])(CustomComponent);


registerPlugin("my-custom-plugin", {
	icon: "hidden",
	render: plugin,
});
```

All i have done is passed all post meta down, then on each update function I pass all of the meta back so it updates correctly.

**Comment by katerlouis** [comment] 2018-07-13 09:44
Thank you very very much, @jrmd !
Your suggestion helped to work around the `undefined` issue on rendering.

But still, publishing / updating fails with the 404 error (bad request) explained above.
![image](https://user-images.githubusercontent.com/1983382/42685024-2592ac48-8692-11e8-83ff-d6182ac8a503.png)

**Comment by jrmd** [comment] 2018-07-13 10:01
@katerlouis I did find a work around for this too, it's caused by trying to update meta to the same value, its fairly hacky but this should work:

```
// loops through the old meta and checks if it has changed
// if it has changed then it it will add it to the object for updating
// else it omits it from the returned object
const reviseData = (oldData, newData) => Object
	.keys(newData)
	.reduce((prev, key) => {
		if (oldData[key] === newData[key]) {
			return prev;
		}

		return {
			...prev,
			[key]: newData[key],
		};
	}, {});

function CustomComponent({ meta, oldMeta, onUpdateBananas, onUpdateWhy }) {

	// everytime I interact with the UI, this function gets called and
	// logs correct value for the property I just interacted with 
	// but always logs undefined for the other, .. why?
	console.log("Bananas boolean", meta.bananas);
	console.log("Question on why", meta.why);

	return (
		<Fragment>
			<PluginPostStatusInfo className="my-plugin__bananas">
				<label htmlFor="bananas-checkbox">Do you like bananas?</label>
				<FormToggle
					key="toggle"
					checked={ !! meta.bananas }
					onChange={ () => onUpdateBananas( !meta.bananas, meta, oldMeta ) }
					id="bananas-checkbox"
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo className="my-plugin__why">
				<label htmlFor="why-input" class="my-plugin__why">
					Why do you{ (!meta.bananas) ? " not" : "" } like bananas?
				</label>
				<TextControl
					type="text"
					onChange={ (value) => onUpdateWhy(value, meta, oldMeta) }
					value={ meta.why }
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo>
				<span>
					for debugging purposes: here is the type of `why`: <i>{ typeof meta.why }</i>
				</span>
			</PluginPostStatusInfo>
		</Fragment>
	)
}

const plugin = compose([
	withSelect((select) => {
		const postMeta = select('core/editor').getEditedPostAttribute('meta');
		const oldPostMeta = select('core/editor').getCurrentPostAttribute('meta');

		return {
			meta: { ...oldPostMeta, ...postMeta },
			oldMeta: oldPostMeta,
		};
	}),
	withDispatch((dispatch) => ({
		onUpdateBananas(value, newMeta, oldMeta) {
			const meta = {
				...reviseData(oldMeta, newMeta),
				bananas: value,
			};

			dispatch("core/editor").editPost({ meta })
		},
		onUpdateWhy(value, newMeta, oldMeta) {
			const meta = {
				...reviseData(oldMeta, newMeta),
				why: value,
			};

			dispatch("core/editor").editPost({ meta })
		},
	})),
])(CustomComponent);


registerPlugin("my-custom-plugin", {
	icon: "hidden",
	render: plugin,
});
```

It works by merging the current saved post meta with the edited meta, when it does the update it checks if the meta value has changed, if it hasnt then it removes it from the dispatch event.

**Comment by katerlouis** [comment] 2018-07-13 17:20
Thanks very much! I'll look into this later–

(phew, it feels like I have to code my own cms here, yihaw! Hope so much the devs will get this mess under control eventually. Don't like to switch to another CMS; but the way things are now don't look too bright :( )

**Comment by katerlouis** [comment] 2018-07-14 07:18
@jrmd Your workaround solved the saving issue for the toggle switch and the text input. 
When my media uploader is used, however, I get the error 400 again. Would appreciate if you could look into this again :(

(bonus question: how could I use `withAPIdata()` in this setup, so I can display a thumbnail when a video id is set. Having to save the thumbnail url aswell feels unwise. I already save the videoURL as meta only to fill the text-input; would like to retrieve that from the actual attachment aswell.)

```js
// loops through the old meta and checks if it has changed
// if it has changed then it it will add it to the object for updating
// else it omits it from the returned object
const reviseData = (oldData, newData) => Object
	.keys(newData)
	.reduce((prev, key) => {
		if (oldData[key] === newData[key]) {
			return prev;
		}

		return {
			...prev,
			[key]: newData[key],
		};
	}, {});

function CustomComponent({ meta, oldMeta, onUpdateBananas, onUpdateWhy, onSelect }) {

	return (
		<Fragment>
			<PluginPostStatusInfo className="my-plugin__bananas">
				<label htmlFor="bananas-checkbox">Do you like bananas?</label>
				<FormToggle
					key="toggle"
					checked={ !! meta.bananas }
					onChange={ () => onUpdateBananas( !meta.bananas, meta, oldMeta ) }
					id="bananas-checkbox"
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo className="my-plugin__why">
				<label htmlFor="why-input" class="my-plugin__why">
					Why do you{ (!meta.bananas) ? " not" : "" } like bananas?
				</label>
				<TextControl
					type="text"
					onChange={ (value) => onUpdateWhy(value, meta, oldMeta) }
					value={ meta.why }
				/>
			</PluginPostStatusInfo>
			<PluginPostStatusInfo>
				<MediaUpload
					onSelect={ (value) => onSelect( value, meta, oldMeta ) }
					type="video"
					multiple={ false }
					value={ meta.myVideoId }
					render={ ({ open }) => (
						<Fragment>
							<TextControl
								label="Stage als video"
								onClick={ open }
								value={ meta.myVideoURL }
							/>
							
							<Button isLarge onClick={ open }>
								Upload
							</Button>
						</Fragment>
					) }
				/>
			</PluginPostStatusInfo>
		</Fragment>
	)
}

const plugin = compose([
	withSelect((select) => {
		const postMeta = select('core/editor').getEditedPostAttribute('meta');
		const oldPostMeta = select('core/editor').getCurrentPostAttribute('meta');

		return {
			meta: { ...oldPostMeta, ...postMeta },
			oldMeta: oldPostMeta,
		};
	}),
	withDispatch((dispatch) => ({
		onUpdateBananas(value, newMeta, oldMeta) {
			const meta = {
				...reviseData(oldMeta, newMeta),
				bananas: value,
			};

			dispatch("core/editor").editPost({ meta })
		},
		onUpdateWhy(value, newMeta, oldMeta) {
			const meta = {
				...reviseData(oldMeta, newMeta),
				why: value,
			};

			dispatch("core/editor").editPost({ meta })
		},
		onSelect(attachment, newMeta, oldMeta) {
			const meta = {
				...reviseData(newMeta, oldMeta),
				myVideoId: attachment.id,
				myVideoURL: attachment.url,
			}  
			
			dispatch("core/editor").editPost({ meta })
		}
	})),
])(CustomComponent);


registerPlugin("my-custom-plugin", {
	icon: "hidden",
	render: plugin,
});
```

**Comment by kadamwhite** [comment] 2018-08-09 16:26
@oxyc @katerlouis Won't really address this issue, but I wanted to chime in to say that there's a new function in WordPress 4.9.8 `register_post_meta` which will accept a post type (_e.g._ 'post' or a custom post type of your own making), and that using `register_post_meta( 'post_type_name', ... )` is now recommended over `register_meta( 'post', ... )`. This avoids data pollution or conflicts between different post types' response objects.

**Comment by katerlouis** [comment] 2018-08-18 09:26
@kadamwhite – Cool to see there's still movement here. Thanks! I'll look into this in a week or two, when I pick up this project again. Right now another deadline is pushing haaard– (I hope Gutenberg has improved a lot over the weeks in general)

**Comment by youknowriad** [comment] 2018-11-27 10:19
Looks like this issue served it's purpuse to explain the different Extensiblity APIs. I'm closing it now.

**Closed by youknowriad** 2018-11-27 10:19 UTC
Labels: [Type] Help Request

**Comment by squibbleFish** [comment] 2018-11-30 17:01
@katerlouis I know this issue is closed, and I don't know if you figured out the save issue. I think I may have figured out an issue you were having with the `400` error from the console. You may have been sending the full object instead of a string or an array.  If that's the case, you will need to stringily the data set. Hope that helps.
