### ISSUE TITLE
Automatically migrate existing Gallery blocks to use the new format

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#35564] opened 2021-10-12 16:49 UTC
Relates to #34881

## What problem does this address?
Gutenberg 11.6 introduced a toolbar button to convert legacy Gallery blocks to the new refactored Gallery block that leverages inner blocks thanks to #34606. Although this button is useful to test the migration mechanism on demand, it is not clear for users its purpose and what are the benefits of doing this. 

## What is your proposed solution?
When taking the refactored Gallery Block out of experimental and introducing it in WordPress 5.9 as the default Gallery Block, the Gallery migration should be done in an automatic, seamless way for users.

**Comment by glendaviesnz** [comment] 2021-10-13 00:44
This is a duplicate of https://github.com/WordPress/gutenberg/issues/32075, so we may want to close this one in favour of that as it includes details of work already done in relation to this.

**Comment by priethor** [comment] 2021-10-13 09:07
Closing in favor of #32075

**Closed as completed** 2021-10-13 09:08 UTC
Labels: [Block] Gallery
