### ISSUE TITLE
Errors during manual 16.2.1 → 16.3.0 update of Gutenberg

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#52992] opened 2023-07-26 17:10 UTC
### Description

While reporting #52991 I wanted to see, if my Gutenberg is in newest available version and noticed a message saying that an automatic update is scheduled in next 4 hours. Upon forcing manual update right now, I've noticed the following:

![Gutenberg Auto-Update](https://github.com/WordPress/gutenberg/assets/2903392/ff67be99-6989-4ba9-b6ee-6304112419f2)

And the plugin remained in 16.2.1, supposedly newest version.

Upon refreshing the page, it turned out that it got actually updated to 16.3.0.

Maybe just a glitch to be ignored.

### Step-by-step reproduction instructions

Steps given above.

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment] 2023-07-26 17:55
cc @mburridge

**Comment by mburridge** [comment] 2023-07-27 09:52
I'm not able to reproduce this.

**Comment by ndiego** [comment] 2023-07-27 11:30
Thanks for reporting @trejder. I tested upgrading on 5 different sites and could not reproduce the error. As you mentioned, this might have just been an erroneous error message caused by a glitch between the scheduled update and the manual upgrade. I am going to close this for now, but if anyone is able to reliably reproduce this issue, please post here, and I will reopen. Thanks!

**Closed as completed by ndiego** 2023-07-27 11:30 UTC
Labels: [Type] Bug, Gutenberg Plugin
