### ISSUE TITLE
Provide options for invalid block resolution

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2132] opened 2017-08-01 19:23 UTC
Related: #1929

When a block is detected as invalid, we should offer the user options to view, resolve, or ignore differences. We should be careful in distinguishing from false positives; in the latter case, if we can improve block validation to be more accommodating while remaining accurate, we should seek to do so. This assumes a good understanding of the flows which lead to invalid blocks.

__Current dialog:__

![Locked content](https://user-images.githubusercontent.com/1779930/28842928-75ab161e-76cd-11e7-8742-56d65407a97f.png)

__Possible implementations:__

From @mtias at https://github.com/WordPress/gutenberg/pull/1929#issuecomment-317406642:

>We should consider adding these buttons:
>
>`[ Convert to Freeform block ] [ Overwrite changes ] [ Do nothing ]`

From @mtias at https://github.com/WordPress/gutenberg/pull/1929#issuecomment-317692322:

>I'm thinking it'd be cool to be able to switch between "old" and "new" renders to visually diff. It could be two tabs next to the warning message.

**Comment by hedgefield** [comment] 2017-08-02 08:42
That would be very useful, because this now also happens to posts started in the current editor, making migration of content a bit more difficult. If it works on copy-paste, which I believe it does, it should also work when opening old posts in gutenberg.

**Comment by aduth** [comment] 2017-08-02 13:04
>because this now also happens to posts started in the current editor

This transition should be transparent, without any "invalid block" prompt at all. I'll do some more testing with existing post contents to see where it might be getting caught up.

Ideally it should only be the case that this prompt is shown when in fact the content _has been_ modified externally, or directly in the Text / HTML view. In all other cases, it would be very helpful to have clear and repeatable steps to reproduce.

**Comment by hedgefield** [comment] 2017-08-02 14:02
Oh interesting. In 0.6.0 I've experienced this a few times with posts written in the current editor.

I've managed to reproduce it:

- I copied the (text view) contents of the affected post (see below)
- started a new post (in the current editor)
- switched to text view
- pasted the content into its text view
- saved the draft
- went back to the posts screen
- clicked the little "gutenberg" link under this draft
- saw the 'content locked' warning for the full text (in which I could see the HTML markup)

The content (text view):
```
Game development has many facets. It takes a lot of work and mastery of a lot of different disciplines to make something playable and enjoyable. We can discern the following areas when it comes to game development:
<h1>Concept and design</h1>
To make something, you need an idea first. This gradually turns into a concept, where you have thought about theme and gameplay mechanics a little more. This goes along with concept art, meant to illustrate the look and feel of the game. Then you get into actual systems design. Not everything needs to be thought out yet, but just some key elements to move on to the next phase, which is prototyping.
<h1>Prototyping</h1>
Here you start making quick and ugly test versions of the game to try out the ideas you had, and whether those are fun or not. If not, try again, and otherwise, we can move on to developing them further.
<h1>Development</h1>
Here we start actually coding features.
<h1>Art</h1>
Of course, just having code doesn't put that much interesting stuff on screen, so we need art. Models, sprites, shaders, textures, all kinds of things are relevant here.
<h1>Sound</h1>
Sound can add a lot to the experience and should be taking into equal consideration.
<h1>Testing</h1>
Testing (with people who were not part of the development team) is essential for catching bugs and other weird things.
<h1>Polish</h1>
Now that the features are locked and the tests are in, we can start polishing the game up to a higher standard.
<h1>Marketing</h1>
If nobody knows about your game, they won't buy it, so make sure you build a little hype and get your social media right.
<h1>Support</h1>
After launch, you need to keep an eye out for problems with the game that didn't come up in testing and develop patches with fixes.
```

**Comment by jasmussen** [comment] 2017-08-18 08:29
Can we close this as addressed? Seems to be working pretty well now.

**Comment by mtias** [comment] 2017-08-18 15:58
Yes, it's in fairly good shape. If we want to preview diffs, let's make a separate issue for that.

**Closed by mtias** 2017-08-18 15:58 UTC
Labels: [Type] Task
