### ISSUE TITLE
Gutenberg on iOS Chrome: Pressing return from title doesn't do anything

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2575] opened 2017-08-28 16:37 UTC
Gutenberg 0.9

When I type a title, it doesn't move into the next block upon hitting "return"

**Comment by aduth** [comment] 2017-08-28 17:57
Related: #2421, https://github.com/WordPress/gutenberg/issues/2279#issuecomment-320861452

**Comment by afercia** [comment] 2017-08-29 14:33
See also #1650

**Comment by aduth** [comment] 2017-09-27 17:52
Closing as duplicate of #1650

**Closed by aduth** 2017-09-27 17:52 UTC
Labels: [Component] Mobile
