### ISSUE TITLE
The third and fourth welcome tips reference actions that are not always possible

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#12360] opened 2018-11-27 13:57 UTC
**Describe the bug**

The third and fourth welcome tips instruct the user to click the `Preview` and `Publish` buttons. If the user has chosen not to insert any content, and instead simply follow the tips, then these actions are unavailable and the user is pointed to two disabled buttons.

Tested with WordPress 5.0 RC.

**To Reproduce**

1. Ensure the localStorage in your browser is clear for your domain, so that tips appear (related: #8052).
2. Open the block editor.
3. Click `See next tip` on the first and second welcome tips.
4. Observe that the third tip points to a disabled `Preview` button.
5. Click `See next tip`.
6. Observe that the fourth tip points to a disabled `Publish` button.

**Expected behavior**

The welcome tip flow should be tweaked so that a user is not instructed to click a disabled button. Maybe the tips should be dynamic based on whether the user is adding content, or simply following along with the tips. Not sure on the best approach.

**Screenshots**

<img width="727" alt="" src="https://user-images.githubusercontent.com/208434/49086360-4098eb80-f24c-11e8-8df0-cd7319cb2669.png">
<img width="648" alt="" src="https://user-images.githubusercontent.com/208434/49086361-4098eb80-f24c-11e8-8c9b-04a830991bb0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 70

**Comment by skorasaurus** [comment] 2018-11-27 16:46
maybe a duplicate of https://github.com/WordPress/gutenberg/issues/8061

**Comment by designsimply** [comment] 2018-11-27 19:49
Closing in favor of consolidating to #8061.

**Closed by designsimply** 2018-11-27 19:49 UTC
Labels: General Interface, NUX, [Type] Bug
