### ISSUE TITLE
Add Block prompt regression

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31562] opened 2021-05-06 18:31 UTC
## Description

As reported by others in [core-editor slack ](https://wordpress.slack.com/archives/C02QB2JS7/p1619766350080600), there seems to be a regression in the add block prompt within the site editor. Rather than just showing a + button, there is now text saying "Add Block".

## Step-by-step reproduction instructions

1. Set up a site with FSE capabilities 
2. Use either the site editor or template editing mode and notice that the add block prompt has changed. 

## Expected behaviour

Expect to just see the + button and no "Add Block" text. 

## Actual behaviour

The add block appender now say "add block" and looks quite awkward :D  

## Screenshots or screen recording (optional)

Here are two examples in the Site Editor where adding a new template part causes it and trying to add a new navigation block item: 

https://user-images.githubusercontent.com/26996883/117352231-fdef8a80-ae6b-11eb-830f-b2869986cee5.mov

Here's an example from the Template Editing Mode:

https://user-images.githubusercontent.com/26996883/117352496-4b6bf780-ae6c-11eb-8a5c-16da86d56db1.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6RC
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by jasmussen** [comment] 2021-05-07 08:31
Definitely a bug, inspecting this I see that there's a "visuallyhidden" component, which is used when the text is meant as added context for screenreaders, but not meant to be _seen_:

<img width="1270" alt="Screenshot 2021-05-07 at 10 29 45" src="https://user-images.githubusercontent.com/1204802/117421951-59c71b80-af1f-11eb-9c8c-32432172a578.png">

Since the bug is present only in the site editor, I wonder if the regression is related to the split block styles loading system that landed recently, but only for block themes. CC: @aristath

**Comment by aristath** [comment] 2021-05-07 13:55
v10.5 works as expected, the regression is in v10.6 and the block-styles tweaks far predate these 2 versions :wink: 
Using `git bisect` I tracked down the issue to this PR: https://github.com/WordPress/gutenberg/pull/31244

**Comment by jasmussen** [comment] 2021-05-07 14:00
Thanks so much for doing that. CC @sarayourfriend in case you might have thoughts.

**Comment by sarayourfriend** [comment] 2021-05-07 14:23
This is a problem with iframe support in Emotion. It seems to work in some cases (if you try a block like the Jetpack Google Calendar block you can see that the external link is rendered with the correct CSS-in-JS styles) but for some reason it's not working for the columns block appender. I'm not familiar with the architecture of FSE so I don't know why one is inside the `StyleProvider` and the other isn't. Maybe @youknowriad will know?

**Comment by youknowriad** [comment] 2021-05-07 14:33
I think all of these are supposed to be already inside a `StyleProvider` 🤔 It's not a Slot AFAIK

**Closed as completed** 2021-05-17 13:29 UTC
Labels: [Type] Bug, [Status] In Progress, General Interface, Needs Design Feedback, [Type] Regression, [Feature] Site Editor, [Feature] Template Editing Mode
