### ISSUE TITLE
Backtick to code: no convertion to code tag when starting at the end

### ISSUE THREAD

**Issue by Digiover** [WordPress/gutenberg#8579] opened 2018-08-06 08:35 UTC
**Describe the bug**
When I start at the end -right- with a backtick, and then type the first -left- backtick, there is no convertion to code.

In my workflow, I often re-read the text, from the end to the beginning. Sometimes I need to add backticks to create HTML `code` tags. This works when you start with the first (most left) backtick, and then the end (right side), but not in reverse order.

**To Reproduce**
1. Type text in a paragraph block
2. add the far right backtick first
3. add the most left backtick second
4. See that there is no HTML `<code>...</code>`

**Expected behavior**
I would expect HTML-code markup being added to the block.

**Screenshots**
Visual view
![selection_022](https://user-images.githubusercontent.com/8005150/43705755-c77dab1e-9963-11e8-9428-cee78bda3f1b.png)
HTML code view:
![selection_023](https://user-images.githubusercontent.com/8005150/43705761-cb1c94a6-9963-11e8-98f8-891fcf2a355b.png)

**Desktop (please complete the following information):**
 - OS: Fedora release 28 (Twenty Eight)
 - Browser Chromium
 - Version 67.0.3396.79 Fedora Project

**Smartphone (please complete the following information):**

**Additional context**
WordPress version 5.0-alpha-43555, and 4.9.8
Gutenberg version 3.4.0

**Comment by youknowriad** [comment] 2018-08-06 09:40
This is a duplicate of #5454, Can you consolidate your feedback there please? Thanks

**Closed by youknowriad** 2018-08-06 09:40 UTC
