### ISSUE TITLE
allowed_block_types_all filter breaks list block

### ISSUE THREAD

**Issue by topi-rantanen** [WordPress/gutenberg#46057] opened 2022-11-25 13:35 UTC
### Description

If default blocks are limited with allowed_block_types_all filter list block does not allow create new list -elements.

### Step-by-step reproduction instructions

1. Add to functions.php

`function filter_allowed_block_types_when_post_provided( $allowed_block_types, $editor_context ) {
    if ( ! empty( $editor_context->post ) ) {
        return array( 'core/paragraph', 'core/heading', 'core/list' );
    }
    return $allowed_block_types;
}

add_filter( 'allowed_block_types_all', 'filter_allowed_block_types_when_post_provided', 10, 2 );`

2. Add new post
3. Add list block
4. Try to add multiple list elements

### Environment info

WP 6.1.1
Twenty Twenty-Two
Chrome Version 107.0.5304.107

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Soean** [comment] 2022-11-25 14:38
The list block has a child block `list-item` since WordPress 6.1.

So you also need to add `'core/list-item'` to the array.

**Comment by t-hamano** [comment] 2022-11-26 03:10
@topi-rantanen 
Thanks for the report.

This is the expected behavior and I think the solution is to add `core/list-item`  as @Soean suggested. Others have been reported at #46047 and #45583.

I would like to close this issue.

**Closed as not planned by t-hamano** 2022-11-26 03:10 UTC
Labels: [Block] List
