### ISSUE TITLE
Flickering issue in the Media and text block

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#26936] opened 2020-11-12 13:59 UTC
Description: When we add the media and text block and then scroll down the page at the time flickering issue is getting raise.

Steps to follow : 

-> Add the Media and Text.
-> Scroll down the page.
-> See the Flickering issue in the editor.

Please find the below attached video : 

https://www.loom.com/share/7ecc0d47ee974f65a5ae2daaeab7e978

Blocks : 

-> Media and Text Block

Version : 

WordPress 5.6 beta

Thanks

**Comment by tellthemachines** [comment] 2020-11-23 05:47
Hi @nayana96249, I can't reproduce this issue on WordPress 5.6 RC1. Can you check if it's still occurring, and, if so, do you have any other plugins active that might be causing this?

**Comment by stokesman** [comment] 2020-11-23 21:59
This appears to have the same underlying cause as #22026. The window scrollbar appearing and disappearing is what is creates the flickering/shifting issue. I'm accusing the browser extension Grammarly as the culprit since it can be seen in the videos from both issues and I'm able to reproduce on Chrome/OS X with the extension installed and enabled. The editing caret must also be active somewhere on the page. When the caret position overflows the editor content area the window scrollbar will appear.

So this may not be the responsibility of WP to workaround but if there's a generic way to do it why not? My first thought was to simply add `overflow: hidden` to the document but that will break scrolling of the admin menu (when not in “fullscreen mode”). So perhaps that menu could be made to have its own scrollbar (with block editor and not classic). I'll likely try that at some point and make a PR if it seems workable. Maybe someone else has another idea.

**Comment by talldan** [comment] 2020-12-16 03:42
Lets close this as a duplicate of #22026

**Closed by talldan** 2020-12-16 03:42 UTC
Labels: [Type] Bug
