### ISSUE TITLE
Blocks list is hidden only, if you click in another block

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#38356] opened 2022-01-30 22:07 UTC
### Description

If you open up a block list, by typing `/something` you can close it only, if you click in another line / block or hit <kbd>Esc</kbd>. 

Clicking:

- In the same line
- In the Wordpress sidebar (right)
- In the Gutenberg sidebar (left)

does not close the blocks list.

Block list isn't even closed when you navigate through Gutenberg menus or interact with popup windows, which can lead to as weird (from UX perspective) situation as the following:

![image](https://user-images.githubusercontent.com/2903392/151719773-9da6fcd6-7adf-480b-b965-8ffaff8f8f59.png)

### Step-by-step reproduction instructions

1. Start a new post. Create a new block
2. Type `/img` (or any other shortcut) to bring up a list of blocks
3. Click on three-dot button in the top right corner to open the Gutenberg menu
4. Click _Preferences_ item to open corresponding dialog / popup block
5. Observe that list of blocks is still visible, messing up entire UI.

### Environment info

- Wordpress 5.9, Gutenberg 12.4.1, WR-Elite theme
- Microsoft Edge 97.0.1072.76 (Official build) (64-bit)
- Windows 10.0.19042 Build 19042

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment] 2022-02-22 05:05
Thanks for reporting! I could replicate this with Gutenberg 12.6 and WordPress 5.9 when I made my screen quite small with Chrome on a Mac while in the Site Editor:

<img width="886" alt="Screen Shot 2022-02-21 at 9 04 33 PM" src="https://user-images.githubusercontent.com/26996883/155066511-2663a785-ebe1-4044-85c2-23593475c80f.png">

**Comment by t-hamano** [comment] 2023-03-24 14:06
I believe this issue was fixed in #45904. I could not reproduce it in WordPress 6.2 RC or the latest Gutenberg. I would like to close this issue, but if the problem continues to occur, please comment.

https://user-images.githubusercontent.com/54422211/227543154-88a518c9-a2fc-48a3-ad25-b84787fb9aac.mp4

**Closed as completed by t-hamano** 2023-03-24 14:06 UTC
Labels: [Type] Bug, General Interface, z-index
