### ISSUE TITLE
Cannot edit links to open in external window in Gutenberg

### ISSUE THREAD

**Issue by coxconsultancy** [WordPress/gutenberg#10088] opened 2018-09-21 10:48 UTC
There is a problem when setting up/editing a link to open in an external window. It occasionally works but more often just goes round in circles and closes the window.

- Clicking on the 3 dots and then the open in new window button closes the window without making the change. 
- Clicking on the pencil and then the open in new window button does the same.

Using Chrome 68 on Windows 10 on a PC.  
Wordpress 4.9.8 and Listing Pro Theme.

**Comment by saulirajala** [comment] 2018-10-07 15:46
I was not either able to replicate the issue with toggle value not saving, but I also tested with Mac.

#7890 seemed to fix the usability issue (link settings hides immediately after toggle-button is clicked) partially and #10372 will fix the rest. This is how it looks like with #10372 :
![link-open-in-new-window](https://user-images.githubusercontent.com/5536354/46583472-bb216800-ca60-11e8-83ec-fb8c8ce39da8.gif)

**Comment by mtias** [comment] 2018-11-12 04:16
Thanks for the report! Closing as unable to reproduce in latest versions. Please, reopen if it's still happening.

**Closed by mtias** 2018-11-12 04:16 UTC
Labels: [Type] Bug
