### ISSUE TITLE
Youtube block don't embed videos

### ISSUE THREAD

**Issue by avagp** [WordPress/gutenberg#8954] opened 2018-08-14 03:31 UTC
**Describe the bug**
The youtube block only leaves the link, and do not embed the video (neither has settings to adjust the embedding).

Gutemberg v3.5.0
Wordpress v4.9.8

**To Reproduce**
1. Insert a youtube block
2. Paste a youtube url (like https://www.youtube.com/watch?v=lwijYwA22mA)
3. Press embed button
4. Go to the page and see the result

**Expected behavior**
The youtube video should be embeded

**Screenshots**
This...
![image](https://user-images.githubusercontent.com/11801254/44070154-a35d4a82-9f58-11e8-8b26-de545f8a207e.png)
turns to...
![image](https://user-images.githubusercontent.com/11801254/44070179-c57d5c24-9f58-11e8-94b8-eb9151b97cd1.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome
 - Version 68

**Additional context**
- It may be related to https://github.com/WordPress/gutenberg/issues/8411

**Comment by avagp** [comment] 2018-08-14 03:33
Also, youtube block cannot be editable after press embed button. There is not way to edit that link.

And if you click the link on the block (after embedding), it dissapears.
![screenshot 2018-08-14 at 00 26 00](https://user-images.githubusercontent.com/11801254/44070349-b8a5d214-9f59-11e8-915a-b94e8e960159.png)

![image](https://user-images.githubusercontent.com/11801254/44070342-afd5baa0-9f59-11e8-927d-6f34c8ea639d.png)

**Comment by avagp** [comment] 2018-08-14 13:27
I have change tht ethem to twenty seventeen. And disabled ALL plugins but gutemberg.

Now i get this error:
![image](https://user-images.githubusercontent.com/11801254/44094474-a5aadc56-9fac-11e8-851a-1f6201bb8b10.png)

**Comment by avagp** [comment] 2018-08-14 13:29
If it is better for the situation i can give you the access to the wordpress site. It has nothing in it, because i was testing some things before beginning the actual building process.

**Comment by avagp** [comment] 2018-08-15 16:11
i just tested it on another site i have, on the same server, and it worked.
So i came back to this.

As soon as i select the youtube block (neither have i write nothing on the input) i get this error on the console:
![image](https://user-images.githubusercontent.com/11801254/44158590-6cbca200-a08b-11e8-9d6c-d9a55b48a1d6.png)

**Comment by avagp** [comment] 2018-08-15 16:15
Now i have tested the following:

Fresh new wordpress site with gutemberg only installed on two different places.
One place as a sub site on the site that youtube is working properly, and other on the site that have never worked.

The one that worked, still works, but i still get this error message
![image](https://user-images.githubusercontent.com/11801254/44159162-f882fe00-a08c-11e8-8eb3-cf253aa3ff7d.png)

And the other one, still doesn't work and i get this error message:
![image](https://user-images.githubusercontent.com/11801254/44159185-089add80-a08d-11e8-969c-612fa574d20e.png)

I will contact my server provider and try something else with them.

Do you have any ideas or question I might ask to them?

**Comment by ianbelanger79** [comment] 2018-09-24 19:52
Hi @avagp,

I have tested the YouTube embed, using your YouTube link and the steps provided. I cannot recreate the issue either, so I am closing this issue for now. Feel free to reopen it if you think this is a mistake, or if you get some more information and continue to see the error.

Thank you

**Closed by ianbelanger79** 2018-09-24 19:52 UTC
Labels: [Type] Help Request

**Comment by avagp** [comment] 2018-09-24 20:15
Hi @ianbelanger79 .

At the end i changed the host, and worked like a charm.

So keep it closed.

Even, the center align button did not work, and now works correctly as well.

**Comment by mradkov** [comment] 2019-04-04 16:13
I can confirm the issue is still present. It is not persistent tho.

**Comment by maximusblade** [comment] 2019-05-22 07:16
I have the same embed issue with SoundCloud.

**Comment by mradkov** [comment] 2019-05-22 10:30
> I have the same embed issue with SoundCloud.

I've created a jquery script to work this around. Basically, it is looking for all of the iframes with "youtube" as `src` and adjusts their dimensions and position.

```
var $allIframes = $("iframe");
    $allIframes.each(function(index, el) {
      $(this)
        .data('aspectRatio', this.height / this.width)
        .removeAttr('height')
        .removeAttr('width');
    });

    $(window).resize(function() {
      $allIframes.each(function(index, el) {
        var $el = $(this);
        var newWidth = $el.parent().width();
        $el.animate({
          width: newWidth,
          height: newWidth * $el.data('aspectRatio')
        }, 10)
      });
    }).resize();
```

**Comment by designsimply** [comment] 2019-06-06 19:27
> I have the same embed issue with SoundCloud.

@maximusblade I tested adding a SoundCloud embed by pasting the following link into an empty block and it worked in my test. I used WordPress 5.2.1 with no active plugins for testing.

```
https://soundcloud.com/silverdogmusic/st-thomas-sonny-rollins?in=musiclistenfree/sets/jazz
```

If you are still having trouble with SoundCloud embeds, please post your steps to reproduce and any details about your setup which may be relevant into a new issue at https://github.com/WordPress/gutenberg/issues/new?template=Bug_report.md
