### ISSUE TITLE
Inserter cursor for search field is off

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14157] opened 2019-02-27 23:28 UTC
**Describe the bug**
My cursor for the search field in the inserter should appear inside the field, but it appears below it. 

![cursor-issue](https://user-images.githubusercontent.com/617986/53530275-2c12fc00-3aa4-11e9-9d41-eefbba3c2e30.gif)

**To Reproduce**
1. In Firefox, click to open inserter.
2. The cursor should be blinking below the search field.

**Expected behavior**
I expect the cursor to appear in the search field.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser FF
 - Version 65.0.1
- Gutenberg version 5.1.1

**Comment by codebykat** [comment] 2019-03-09 19:08
I'm seeing this in Firefox too. It's only with the inserter at the top of the block; the one on the left is correct.


Inserter at the top:  
<img width="485" alt="Screen Shot 2019-03-09 at 12 04 47 PM" src="https://user-images.githubusercontent.com/52152/54076024-3d55c880-425b-11e9-9d9e-7f44e6c9c881.png">

When opened from the inserter on the left side:
<img width="455" alt="Screen Shot 2019-03-09 at 12 04 27 PM" src="https://user-images.githubusercontent.com/52152/54076028-43e44000-425b-11e9-915b-76795a10dbac.png">

I tested this in Chrome and Safari and both cursors are correctly positioned.

* OS: OSX
* Browser: Firefox
* Version: 65.0.1

**Comment by codebykat** [comment] 2019-03-09 19:15
Ah this is a dupe of https://github.com/WordPress/gutenberg/issues/13751.

I'm going to close this and update the earlier issue.

**Closed by codebykat** 2019-03-09 19:15 UTC
Labels: [Component] Inserter, [Type] Bug
