### ISSUE TITLE
Customizer Widgets: small bugs and styling tweaks

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#31958] opened 2021-05-18 21:36 UTC
Hi all, I just completed the recent Widgets [Call for Testing](https://make.wordpress.org/core/2021/05/12/help-test-the-widgets-editor-for-wordpress-5-8/) and compiled a list of bugs I noticed within the Customizer Widgets editor. I'm adding images as external links to keep this list easy to read! 

**Block-related:**

- Paragraph block: The [popover for adding a link](https://cloudup.com/id234qkxUni) is getting cut off on the right edge
- Paragraph block: Seeing some [overlapping popover menus](https://cloudup.com/iQRFyFx4Qby) for link / inline text color
- Paragraph block: Seeing some alignment issues when a color is selected (ex. [black color swatch](https://cloudup.com/iQRFyFx4Qby) is misaligned)
- Image block: Some of the color options are getting cut off within the [duotone popover menu](https://cloudup.com/iPlQtc-S7CD)
- Navigation block: modal doesn’t open from the “block navigation” icon in the toolbar
- Group block: Focused outline is [overlapping with “add block” button](https://cloudup.com/cfHx6uQEoi0) — can we hide the "add" button that's appearing within the group?

**Legacy widget-related:**

- Legacy widgets should switch back to “preview” mode when not selected

**General:**

- When adding a block, sometimes an extra[ “add” button appears](https://cloudup.com/cuI_oRMKoJw) on top of the block on the left edge of the screen
- It's confusing that the “patterns” tab is available within the Inserter but appears empty — could we just remove the tab entirely for now?

**Comment by kevin940726** [comment] 2021-05-20 17:43
Thanks for testing! They're really helpful 😍. I did a triage for some of them below:

> Paragraph block: Seeing some [overlapping popover menus](https://cloudup.com/iQRFyFx4Qby) for link / inline text color

I'm seeing this too in the post editor though, can you confirm it's customizer only? Or maybe we can open a separate issue for it.

![image](https://user-images.githubusercontent.com/7753001/119024334-8a09c200-b9d5-11eb-90f0-acfc9cd3b62c.png)

> Navigation block: modal doesn’t open from the “block navigation” icon in the toolbar

It's opening during my testing though, can you confirm it's still happening on `trunk`?

https://user-images.githubusercontent.com/7753001/119024117-52027f00-b9d5-11eb-9abb-90b57398f220.mp4

> Group block: Focused outline is [overlapping with “add block” button](https://cloudup.com/cfHx6uQEoi0) — can we hide the "add" button that's appearing within the group?

I'm not seeing this either. Could you provide reproduction steps?

![image](https://user-images.githubusercontent.com/7753001/119024422-a0178280-b9d5-11eb-9b48-81a6f127c71e.png)

> Legacy widgets should switch back to “preview” mode when not selected

I can't reproduce this either, do you have reproduction steps?

> It's confusing that the “patterns” tab is available within the Inserter but appears empty — could we just remove the tab entirely for now?

I'm not seeing this on `trunk` either, maybe it has been fixed not long ago?

![image](https://user-images.githubusercontent.com/7753001/119024614-da811f80-b9d5-11eb-9f88-6a2acdbdeda8.png)

**Comment by critterverse** [comment] 2021-05-25 19:42
Thanks so much for going through all of these notes @kevin940726, and sorry there were a few false alarms! 🙈

Double checked all, and everything not mentioned below is working as intended 😁

**Overlapping pop-up menus:**
Confirming that this does happen in the post editor as well and opened a new issue, #32221

**Group block "add" button:**
I am still seeing this overlapping issue — here's a quick video.

https://user-images.githubusercontent.com/77359364/119558322-40bbc880-bd6f-11eb-808b-bc3b333fcd01.mov

**Comment by kevin940726** [comment] 2021-05-26 09:52
@critterverse Thanks for confirming!

I also found out that the **Group block "add" button** issue can be reproduced in the post editor as well. I'm not sure whether it's the expected behavior though. Also seems like it can only be reproduced when the last block is an image block.


https://user-images.githubusercontent.com/7753001/119640217-f6a81500-be4a-11eb-827b-7af250a383ff.mp4

**Comment by critterverse** [comment] 2021-05-27 13:40
I believe it is the expected behavior for container blocks like Group, Columns, etc have an extra add button that allow you to insert a new block within the container (so my suggestion to hide the add button wasn’t a great one).

But I'm unable to recreate the focus outline overlapping issue in the post editor, even within a narrow Column area. I think that bug is unique to the Customizer but I could be wrong! 

https://user-images.githubusercontent.com/77359364/119834563-116f9d80-bece-11eb-909e-959db27dfae1.mov

**Comment by kevin940726** [comment] 2021-06-01 08:18
@critterverse This is also an issue in other editors (widgets screen) other than the post editor as well. The issue is because these editors don't load some of the styles loaded in the post editor. I don't have any idea how to fix it yet, might need to come back to it later 🤔.

**Comment by noisysocks** [comment] 2021-06-08 01:01
What's left here? Can we close the issue?

**Closed as completed** 2021-06-09 13:08 UTC
Labels: [Feature] Widgets Customizer
