### ISSUE TITLE
Update not actually updating

### ISSUE THREAD

**Issue by drbe4t** [WordPress/gutenberg#7655] opened 2018-07-01 13:47 UTC
**Describe the bug**
I've been using Gutenberg for several months know. Most of the bugs that I've dealt with have been worked out, but one that keeps coming back is when I go in to update a post or page. For example, I try to add a featured image and it goes through the motion of updating but it never actually does. 
**To Reproduce**
1. open editor
2. Make changes in editor or document (featured images, categories)
3. Press update..
4. WP Gutenburg says saving/ updating button does its fancy thing and then it says done with a view post link
5. when clicked changes are not made. 
**Expected behavior**
If I go in to update a post I'd hope it updates. 

**Screenshots**
<img width="1373" alt="screen shot 2018-07-01 at 8 41 53 am" src="https://user-images.githubusercontent.com/10386515/42135002-ab196f82-7d0a-11e8-928a-205493815b84.png">
<img width="1254" alt="screen shot 2018-07-01 at 8 42 06 am" src="https://user-images.githubusercontent.com/10386515/42135003-ab2a8330-7d0a-11e8-90ac-3553fc596781.png">
<img width="1381" alt="screen shot 2018-07-01 at 8 41 23 am" src="https://user-images.githubusercontent.com/10386515/42135004-ab39fd7e-7d0a-11e8-83dc-c10c87ff2332.png">
<img width="1383" alt="screen shot 2018-07-01 at 8 41 02 am" src="https://user-images.githubusercontent.com/10386515/42135005-ab48bb7a-7d0a-11e8-8d94-c135c600a7c1.png">
<img width="1384" alt="screen shot 2018-07-01 at 8 40 23 am" src="https://user-images.githubusercontent.com/10386515/42135006-ab57f266-7d0a-11e8-8a72-df4d2736b040.png">

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra 10.13.5
 - Browser Chrome(v-67.0.3396.99 ), Firefox(v-61.0), Safari(v-11.1.1), Vivaldi(v-1.15.1147.47)

**Additional context**
Gutenberg version is 3.1.1

**Comment by designsimply** [comment] 2018-07-02 23:02
Thank you for the report @drbe4t! I tested using WordPress 4.9.6 and Gutenberg 3.1.1 on Firefox 61.0 on macOS 10.13.5 and couldn't reproduce the problem you reported. Would you mind having a look at my testing steps and let me know if I've done something differently in my steps compared to yours? Maybe I'm missing a step?

<strong>Video:</strong> [2m9s](https://cloudup.com/cWW8qQ3QM07)

FWIW, I have seen this happen when using the P2 theme (and also related plugins), but in my test above I was using the [Storefront](https://wordpress.org/themes/storefront/) theme. P2 is complex and uses a lot of JavaScript in ways other themes may not. Would you mind documenting what plugins and themes you currently have installed? Is there any chance you are able to test this issue without other plugins enabled (maybe on a different test blog, if you have one, if that's not something you can do on your main site)? Finally, does this problem happen to you every time you edit a previously published post or does it only happen for some posts and not others?

**Comment by youknowriad** [comment] 2018-08-24 17:48
It's been a long time without activity, I'm closing for now. It seems related to P2/O2 similar bugs where themes/plugins alter the REST API behavior https://github.com/Automattic/o2/issues/161 and in that case, there's nothing we can do in Gutenberg itself as the bug is elsewhere.

**Closed by youknowriad** 2018-08-24 17:48 UTC
Labels: [Component] Saving, [Status] Needs More Info, [Type] Bug
