### ISSUE TITLE
New Pattern features need documentation

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#41021] opened 2022-05-12 09:54 UTC
Add to theme developer documentation from this Dev Notes to the Block Editor Handbook

- [ ] [Pattern registration from Pattern Directory for themes](https://make.wordpress.org/core/2022/05/02/new-features-for-working-with-patterns-and-themes-in-wordpress-6-0/)
- [ ] [Place Patterns in the subfolder /patterns of your theme](https://make.wordpress.org/core/2022/05/02/new-features-for-working-with-patterns-and-themes-in-wordpress-6-0/)
- [ ] [Page creation patterns](https://make.wordpress.org/core/2022/05/03/page-creation-patterns-in-wordpress-6-0/) 

**Location:** 
- [ ]  [Reference > Block API > Patterns](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/)
- [ ] with an overview page under [How-to-Guides > Themes](https://developer.wordpress.org/block-editor/how-to-guides/themes/)

**Comment by carolinan** [comment] 2022-05-12 12:10
I strongly feel that the features that are going to be in **core** in 6.0 should be in the theme developer handbook and not in
https://developer.wordpress.org/block-editor/how-to-guides/themes

**Comment by gziolo** [comment] 2022-05-12 12:28
> I strongly feel that the features that are going to be in core in 6.0 should be in the theme developer handbook

Good feedback. It still would be great to add all listed references from the Block Editor Handbook if we follow your recommendation.

**Comment by carolinan** [comment] 2022-05-12 13:12
I have opened this issue for the theme developer handbook: https://github.com/WordPress/Documentation-Issue-Tracker/issues/342

**Comment by bph** [comment] 2022-05-12 14:28
Thank you so much @carolinan - I close this issue here.

**Comment by carolinan** [comment] 2022-05-12 14:30
Reopened because the **reference** still needs to be updated.

**Comment by carolinan** [comment] 2022-05-12 14:36
Or, when do we consider the https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/ to be a duplicate of the core code reference?

https://developer.wordpress.org/reference/functions/register_block_pattern/ 
https://developer.wordpress.org/reference/functions/unregister_block_pattern/

**Comment by bph** [comment] 2022-05-18 19:06
Good point. Both have their place. One is to look up the function reference, the other explains the concept and the context, that could link to the function references... I need to think about it some more, though.

**Comment by bph** [comment] 2022-05-19 09:28
@carolinan 
Would you want to create a new discussion post  for the overall question, on at which point will the block-editor handbook, be integrated into the core references to avoid duplication and confusion as to where to go? 
Then we can discuss it on the next #docs meeting? And the next #core-editor meeting and get people's input. 
With the automating docs production it probably a bit more complicated than I can understand at the moment.

**Comment by carolinan** [comment] 2022-06-23 08:51
@bph I'm sorry I missed the notification!

**Comment by ndiego** [comment] 2022-07-21 16:47
@bph and @carolinan, I am going to pick this up for the [Block Editor Handbook page](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/) if that's ok. I'll aim to have a PR put together by the end of the week.

**Comment by carolinan** [comment] 2022-07-22 09:54
@ndiego @colorful-tones If it is not clear which handbook it should live in then there needs to be more discussions.

**Comment by carolinan** [comment] 2022-07-22 09:58
The decision process for where this type of documentation should be placed seems very unclear.
-We need to avoid duplicate work
-We need to avoid duplicate content

**Comment by carolinan** [comment] 2022-07-22 09:59
I do not have the bandwidth to lead that discussion.

**Comment by ndiego** [comment] 2022-07-22 10:51
@carolinan it's a great discussion to have. At the very least I just want to ensure the [Block Editor Handbook page](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/) is complete. It does not even mention that patterns can be registered in a `/patterns` folder. There are also dedicated sections on that page regarding contextual and semantic patterns, but no discussion on page creation patterns. A Patterns doc for the Theme Handbook can be much more theme specific with additional examples as @colorful-tones [put together](https://github.com/WordPress/Documentation-Issue-Tracker/issues/342).

**Comment by carolinan** [comment] 2022-07-22 11:03
Ok that sounds like a good plan!

**Comment by jordesign** [comment] 2024-01-13 10:14
Looping back to this issue - @carolinan @ndiego  does https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/ mean this issue can be closed?

**Comment by ndiego** [comment] 2024-01-13 12:13
I think we can preemptively close this issue. Coupled with the improvements in the Block Editor Handbook, @justintadlock is working on an expanded chapter in the Themes Handbook that will go into great detail on Patterns. The tracking issue for this is here: https://github.com/WordPress/Documentation-Issue-Tracker/issues/816

**Closed as not planned** 2024-01-15 00:00 UTC
Labels: [Type] Developer Documentation, [Feature] Patterns
