### ISSUE TITLE
[RNMobile]: Split pasted content correctly between title and body

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#35733] opened 2021-10-18 14:26 UTC
## What problem does this address?

In the native mobile editor, it's not possible to paste content into the editor title field and have it split correctly between the title and body.

| Web | Native Mobile |
| - | - |
| <img src="https://user-images.githubusercontent.com/1898325/137749698-224e1760-0970-4015-ae9f-d24370e8f7e1.gif" alt="Screen recording showing how pasted text in the title field of the web editor is split correctly between title and body" width="350"> | <img src="https://user-images.githubusercontent.com/1898325/137750296-77523902-b6c0-4b9c-bf0e-e2d4b86babf2.gif" alt="Screen recording showing how pasted text in the title field of the native mobile editor is not split correctly between title and body" width="350"> |

## What is your proposed solution?

Just like on the web, content pasted into the title field should split correctly between the title and body. It might be reasonable to put whatever follows the first new-line character in the body, keeping what's before it in the title. That said, there might be a web implementation we can use to avoid re-implementing this.

**Comment by mchowning** [comment] 2021-10-19 13:44
I'm a bit torn on what priority to give this. It feels like a bit of an edge case, but it's not that much of an edge case, and it is really annoying when it happens because of how jarring it feels. For that reason I'm marking it as high priority, but definitely open to other opinions.

**Comment by guarani** [comment] 2021-12-02 23:10
Assigning myself to work on it next week.

**Comment by derekblank** [comment] 2022-03-22 06:50
Hello 👋 I'm happy to take a look at this one.

**Comment by derekblank** [comment] 2023-04-13 05:52
I can confirm that @guarani 's changes in https://github.com/WordPress/gutenberg/pull/37169 resolve the issue for both platforms for all test cases. 🎉 

I'll get the CI and merge conflicts in the related PRs to pass so we can merge them and close this issue. 👍 

https://user-images.githubusercontent.com/643285/231665741-9febd8e1-4905-4caa-84ad-de4736fbdf7d.mov

**Comment by derekblank** [comment] 2023-04-14 01:35
The issue fix has been merged. 🏁 

* https://github.com/WordPress/gutenberg/pull/37169
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/5664

**Closed as completed by derekblank** 2023-04-14 01:35 UTC
Labels: [Type] Enhancement, [Priority] High, Mobile App - i.e. Android or iOS
