### ISSUE TITLE
BUG: issue with slugs/permalinks using non-english chars

### ISSUE THREAD

**Issue by ramiy** [WordPress/gutenberg#13616] opened 2019-01-31 11:22 UTC
**Describe the bug**

Gutenberg has a display bug with permalinks using non-english chars.

This bug was **fixed in WordPress over 9 years ago** by applying `editable_slug` filter on all permalinks displayed on screen. For more information see track tickets [10966](https://core.trac.wordpress.org/ticket/10966) and [16999](https://core.trac.wordpress.org/ticket/16999).

But with Gutenberg it's back again.

**To Reproduce**

1. Create new post.
2. Give it a title with non-english chars (for example **internationalizætiøn**).
4. Save the post.

**Expected behavior**

The slug preview should be displayed with the original letters, not gibberish letters.

**Screenshots**

![gut-slug-bug](https://user-images.githubusercontent.com/576623/52050615-cd686a00-2559-11e9-9fe0-34c6996752a6.png)

**Additional context**
- Using WP 5.0.3

**Comment by ocean90** [comment] 2019-01-31 11:46
Duplicate of #13229.

**Closed by ocean90** 2019-01-31 11:46 UTC
Labels: [Status] Duplicate
