### ISSUE TITLE
How to insert an image or paragraph above a column?

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#16094] opened 2019-06-11 16:16 UTC
If I want to insert an image or an paragraph above a column, it's very difficult. It only works with a cumbersome intermediate step.

If I click on the + that is between the two columns, then a block is inserted in the upper column. But I want that in the lower column. I have a feeling that on good luck you have to try where the block lands. That is not quite clear where exactly the block is now... 

Here is a screenshot:

![45FppvxB9C](https://user-images.githubusercontent.com/9355398/59288812-ea821780-8c74-11e9-931c-7ce36277080f.gif)

Am I doing something wrong?

**Comment by talldan** [comment] 2019-06-13 02:27
Hi @SchneiderSam, it's quite hard to see what's happening in the screenshot. It looks like you have columns, but they're horizontal? Is this your own custom style?

in the block's menu (the icon with three stacked dots on the block toolbar), there are options for inserting a block before or after the current block. Does that help, or do you end up with the same outcome as when you use the '+' button?

**Comment by youknowriad** [comment] 2020-07-02 09:55
This is definitely a struggle, it's a duplicate of #6842 though.

**Closed by youknowriad** 2020-07-02 09:55 UTC
Labels: [Block] Columns, [Feature] Blocks, [Feature] Inserter
