### ISSUE TITLE
Stopped Working after Update.

### ISSUE THREAD

**Issue by masterpulha** [WordPress/gutenberg#10162] opened 2018-09-25 15:01 UTC
I have been using Gutenberg for a few weeks without any issue with my theme or plugins.
Had Cloudflare and WP Fastest Cache from start. Decided to upgrade and now it only gives me a White Screen.
Tried Cloudflare Developer Mode, and stop caching the site, removed the plugin and installed again but the same result.

 - Windows 10
 - Google Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)
- Gutenberg Version 3.9.0

https://imgur.com/Kz6YbCM

![kz6ybcm](https://user-images.githubusercontent.com/1119271/46086112-6d118800-c175-11e8-85b5-f8287103e657.png)

`Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (commons-820.min.js:1)
    at Object.<anonymous> (commons-820.min.js:1)
    at e (commons-820.min.js:1)
    at Object.<anonymous> (commons-820.min.js:6)
    at e (commons-820.min.js:1)
    at commons-820.min.js:1
    at commons-820.min.js:1

Uncaught TypeError: Cannot read property 'InspectorControls' of undefined
    at Object.<anonymous> (index.js:1)
    at t (index.js:1)
    at Object.<anonymous> (index.js:1)
    at t (index.js:1)
    at Object.<anonymous> (index.js:1)
    at t (index.js:1)
    at index.js:1
    at index.js:1

Uncaught TypeError: Cannot read property 'Content' of undefined
    at Object.1439 (wp-seo-structured-data-blocks-820.min.js:1)
    at e (commons-820.min.js:1)
    at Object.1438 (wp-seo-structured-data-blocks-820.min.js:1)
    at e (commons-820.min.js:1)
    at Object.1437 (wp-seo-structured-data-blocks-820.min.js:1)
    at e (commons-820.min.js:1)
    at Object.1436 (wp-seo-structured-data-blocks-820.min.js:1)
    at e (commons-820.min.js:1)
    at window.yoastWebpackJsonp (commons-820.min.js:1)
    at wp-seo-structured-data-blocks-820.min.js:1

Uncaught TypeError: Cannot set property 'cssText' of undefined
    at content.index.js:9150
    at content.index.js:9189
    at Object.defineProperty.value (content.index.js:1029)
    at Object.defineProperty.value (content.index.js:1041)
    at __webpack_require__ (content.index.js:20)
    at Object.__webpack_exports__.a (content.index.js:12790)
    at __webpack_require__ (content.index.js:20)
    at Object.<anonymous> (content.index.js:12043)
    at __webpack_require__ (content.index.js:20)
    at Object.<anonymous> (content.index.js:12030)`

**Comment by barrymichaeldoyle** [comment] 2018-09-25 19:53
I'm also having issues since the update.

```
TypeError: wp.media is not a function
    at new t (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1537904929:12:4466)
    at yh (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:97:111)
    at lg (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at zd (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449)
    at ra (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319)
    at Object.enqueueSetState (https://www.barrymichaeldoyle.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231)
```

**Comment by masterpulha** [comment] 2018-09-25 23:03
Now I also disableable Yoast SEO and tested Gutenberg 3.8.0 - 3.7.0 and 3.6.2.
All will just show a blank page :-/
Really need this solved today, was creating content and got used to Gutenberg.
Tried Elementor just to see if it worked and maybe get some work done, and it's working great.
Also tried WPBakery and all good, so I'm pretty sure its exclusively a Gutenberg problem.

The plugin is starting to get to the level of the other two so I hope it gets fixed soon.

**Comment by kudesa** [comment] 2018-09-26 12:38
Not working. Gutenberg 3.8.0 and 3.9.0. 

macOS 10.13.6
Chrome/69.0.3497.100
Gutenberg Version 3.9.0

![image](https://user-images.githubusercontent.com/1862552/46079983-4f5a1800-c1a1-11e8-800c-c47a5d83be67.png)
```
TypeError: Cannot read property 'show_ui' of undefined
    at /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537964740:50:237190
    at i (/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:6:91)
    at An.filter (/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:99:338)
    at /wp-content/plugins/gutenberg/build/editor/index.js?ver=1537964740:50:237155
    at yh (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:95:430)
    at lg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
```

**Comment by twosg** [comment] 2018-09-26 13:16
Similar problem right now after activating on the edit page:
```
view.block.editor.js?ver=3.2.1:25201 Uncaught TypeError: Cannot read property 'InspectorControls' of undefined
    at Object.<anonymous> (view.block.editor.js?ver=3.2.1:25201)
    at __webpack_require__ (view.block.editor.js?ver=3.2.1:20)
    at Object.<anonymous> (view.block.editor.js?ver=3.2.1:24826)
    at __webpack_require__ (view.block.editor.js?ver=3.2.1:20)
    at module.exports.version (view.block.editor.js?ver=3.2.1:63)
    at view.block.editor.js?ver=3.2.1:66
(anonymous) @ view.block.editor.js?ver=3.2.1:25201
__webpack_require__ @ view.block.editor.js?ver=3.2.1:20
(anonymous) @ view.block.editor.js?ver=3.2.1:24826
__webpack_require__ @ view.block.editor.js?ver=3.2.1:20
module.exports.version @ view.block.editor.js?ver=3.2.1:63
(anonymous) @ view.block.editor.js?ver=3.2.1:66
15:12:12.553 ct.block.editor.js?ver=3.2.1:2105 Uncaught TypeError: Cannot read property 'InspectorControls' of undefined
    at Object.<anonymous> (ct.block.editor.js?ver=3.2.1:2105)
    at __webpack_require__ (ct.block.editor.js?ver=3.2.1:20)
    at Object.<anonymous> (ct.block.editor.js?ver=3.2.1:1924)
    at __webpack_require__ (ct.block.editor.js?ver=3.2.1:20)
    at module.exports.version (ct.block.editor.js?ver=3.2.1:63)
    at ct.block.editor.js?ver=3.2.1:66
(anonymous) @ ct.block.editor.js?ver=3.2.1:2105
__webpack_require__ @ ct.block.editor.js?ver=3.2.1:20
(anonymous) @ ct.block.editor.js?ver=3.2.1:1924
__webpack_require__ @ ct.block.editor.js?ver=3.2.1:20
module.exports.version @ ct.block.editor.js?ver=3.2.1:63
(anonymous) @ ct.block.editor.js?ver=3.2.1:66
15:12:12.556 custom.html.block.editor.js?ver=3.2.1:249 Uncaught TypeError: Cannot read property 'BlockControls' of undefined
    at Object.162 (custom.html.block.editor.js?ver=3.2.1:249)
    at __webpack_require__ (custom.html.block.editor.js?ver=3.2.1:20)
    at 0.module.exports.version (custom.html.block.editor.js?ver=3.2.1:63)
    at custom.html.block.editor.js?ver=3.2.1:66
162 @ custom.html.block.editor.js?ver=3.2.1:249
__webpack_require__ @ custom.html.block.editor.js?ver=3.2.1:20
0.module.exports.version @ custom.html.block.editor.js?ver=3.2.1:63
(anonymous) @ custom.html.block.editor.js?ver=3.2.1:66
15:12:13.560 wp-seo-structured-data-blocks-830.min.js?ver=8.3:1 Uncaught TypeError: Cannot read property 'Content' of undefined
    at Object.1623 (wp-seo-structured-data-blocks-830.min.js?ver=8.3:1)
    at t (commons-830.min.js?ver=8.3:1)
    at Object.1622 (wp-seo-structured-data-blocks-830.min.js?ver=8.3:1)
    at t (commons-830.min.js?ver=8.3:1)
    at Object.1621 (wp-seo-structured-data-blocks-830.min.js?ver=8.3:1)
    at t (commons-830.min.js?ver=8.3:1)
    at Object.1620 (wp-seo-structured-data-blocks-830.min.js?ver=8.3:1)
    at t (commons-830.min.js?ver=8.3:1)
    at window.yoastWebpackJsonp (commons-830.min.js?ver=8.3:1)
    at wp-seo-structured-data-blocks-830.min.js?ver=8.3:1
```

**Comment by designsimply** [comment] 2018-09-26 14:33
@masterpulha thanks for reporting this! I see that several of the notices in your console errors include `wp-seo-structured-data-blocks-820.min.js` and that may indicate a conflict with Yoast SEO. I did test the plugin with the Gutenberg 3.9.0-rc.2 release and it worked in my test, so there may be something specific to your server environment that is different compared to what I have been able to test so far. Also, Yoast SEO has just been updated to 8.3 so updating that first and then clearing cache and testing again would be a good step based on those specific errors.

To confirm, the problem still happens when you have installed Gutenberg 3.9.0 and have also temporarily disabled Cloudflare and Yoast SEO 8.2? In that state, if you clear local browser cache and then load the editor and check your browser developer tools for errors, you shouldn't see the same errors any more with the plugin disabled (the ones that start with `wp-seo`), can you confirm that? Do you see any different errors at that point?

If the problem is with Cloudflare, then a good troubleshooting step will be to check the Cloudflare WAF log to see if it indicates which rule is causing requests to be blocked. Is this something you can check?

Based on the errors showing in your screenshot, it looks like a plugin conflict, but based on what you have mentioned testing (thanks for those details btw!) it sounds like there could be something additional going on and the more information we can get about the specifics the better!

**Comment by designsimply** [comment] 2018-09-26 14:36
@barrymichaeldoyle `TypeError: wp.media is not a function` is a different error. If you are using the Wordfence plugin, may I ask that you add a comment to https://github.com/WordPress/gutenberg/issues/7643 noting the error there and whether you are using a multisite install or not? If you are not using Wordfence, may I ask that you create a new issue and note the error as well as a list of your plugins as a starting point for further help?

**Comment by designsimply** [comment] 2018-09-26 14:47
@kudesa the error and screenshots you posted look similar to https://github.com/WordPress/gutenberg/issues/9912. Would you mind adding your screenshots there and also note whether you are using nginx and also if you use a VPN?

**Comment by kudesa** [comment] 2018-09-26 14:58
@designsimply I am using mamp with nginx

**Comment by designsimply** [comment] 2018-09-26 15:08
@kudesa cool, could you note that on #9912 and also mention if it's a plain vanilla install or if you have made any server configuration changes such as for Content-Security-Policy or to rewrite rules? Or you think it should be a separate issue, could you open a new one with all of the related details you can think of?

For reference, here is another similar error reported where updating rewrite rules on the server solved the problem: https://github.com/WordPress/gutenberg/issues/8802#issuecomment-411961456

**Comment by designsimply** [comment] 2018-09-26 15:11
@twosg since I see references to `wp-seo-structured-data-blocks-830.min.js` in the error you posted, may I ask if the problem goes away if you temporarily deactivate the Yoast SEO plugin and then clear browser cache and try editing a post again?

**Comment by twosg** [comment] 2018-09-26 15:20
@designsimply Now I only get 3 errors:

```
Uncaught TypeError: Cannot read property 'BaseControl' of undefined
    at Object.defineProperty.value (view.block.editor.js?ver=3.2.1:24728)
    at __webpack_require__ (view.block.editor.js?ver=3.2.1:20)
    at Object.<anonymous> (view.block.editor.js?ver=3.2.1:25167)
    at __webpack_require__ (view.block.editor.js?ver=3.2.1:20)
    at Object.<anonymous> (view.block.editor.js?ver=3.2.1:24826)
    at __webpack_require__ (view.block.editor.js?ver=3.2.1:20)
    at module.exports.version (view.block.editor.js?ver=3.2.1:63)
    at view.block.editor.js?ver=3.2.1:66

Uncaught TypeError: Cannot read property 'InspectorControls' of undefined
    at Object.<anonymous> (ct.block.editor.js?ver=3.2.1:2105)
    at __webpack_require__ (ct.block.editor.js?ver=3.2.1:20)
    at Object.<anonymous> (ct.block.editor.js?ver=3.2.1:1924)
    at __webpack_require__ (ct.block.editor.js?ver=3.2.1:20)
    at module.exports.version (ct.block.editor.js?ver=3.2.1:63)
    at ct.block.editor.js?ver=3.2.1:66

Uncaught TypeError: Cannot read property 'BlockControls' of undefined
    at Object.162 (custom.html.block.editor.js?ver=3.2.1:249)
    at __webpack_require__ (custom.html.block.editor.js?ver=3.2.1:20)
    at 0.module.exports.version (custom.html.block.editor.js?ver=3.2.1:63)
    at 
```

Should I better open a new issue for this?

**Comment by kudesa** [comment] 2018-09-26 15:29
@masterpulha wow! 
I replaced the old rule nginx location 
`
$uri $uri/ /index.php?q=$uri$args;
`
on new rule
`$uri $uri/ /index.php?$args;`
It's worked. 
Thank you!

**Comment by Lofesa** [comment] 2018-09-27 19:10
Hi @kudesa 
Try better index.php$is_args$args ; from nginx docs:
$is_args
    “?” if a request line has arguments, or an empty string otherwise 
$args
    arguments in the request line

**Comment by Lofesa** [comment] 2018-09-27 19:11
Hi @masterpulha 
errors related to polifyll are from Yoast. Update the version and it is go

**Comment by designsimply** [comment] 2018-09-28 15:59
@twosg, ah! Good find! May I ask which plugin? Maybe we can contact them and let them know aobut the problem.

**Comment by designsimply** [comment] 2018-09-28 16:08
I am closing this issue with the following notes:

1. @masterpulha's errors are related to the Yoast SEO plugin and should try updating.
1. @barrymichaeldoyle should move to #9912.
1. @kudesa solved by updating nginx location rules.

I also wanted to note that I really appreciate everyone here who is testing Gutenberg at this early stage and taking the time to understand the details. Thank you so much!

**Closed by designsimply** 2018-09-28 16:08 UTC
Labels: [Type] Help Request

**Comment by twosg** [comment] 2018-09-28 16:45
Plugin called Clearfy: https://wordpress.org/plugins/clearfy/ - its not a fault of the plugin directly. It allowes to remove a lot of unneeded stuff from WP, depending on the project.

**Comment by designsimply** [comment] 2018-09-28 19:17
Ace. Thank you for the follow-up @twosg !
