### ISSUE TITLE
Hard to type in values in Range Control

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#25018] opened 2020-09-02 14:27 UTC
**Describe the bug**
It's very hard to type in values in range controls.

**To reproduce**
1. Add a Spacer block
2. Change height value. Highlight the value or hit backspace to try and input the number `100`

Here I am trying to input "100" in the spacer block:
![typing-range-control](https://user-images.githubusercontent.com/1033611/91995836-dc815080-ed6a-11ea-96e8-466b7dc72f32.gif)

For range controls, it's also generally hard to type in negative values.

The issue probably is that the value when typing gets validated right away by rules like the `min` prop and therefore is making things hard to type in supposedly valid numbers.

**Expected behavior**
I should be able to type in values easily in range control input fields.

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by aristath** [comment] 2020-09-02 15:42
Confirmed, marking as a bug.
The issue is that as soon as you start typing it tries to validate the value and it can't go any lower than `20`, so when you type `1`, it goes to `20`

**Comment by talldan** [comment] 2020-09-03 06:03
I think this was raised in #24460, so will mark this one as a duplicate and close. Thanks for reporting though, @bfintal.

**Closed by talldan** 2020-09-03 06:03 UTC
Labels: [Type] Bug
