### ISSUE TITLE
Column blocks (e.g. 30) are not displayed correctly in a group block

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#42031] opened 2022-06-29 06:22 UTC
### Description

If I insert many column blocks in a group block (in the mentioned example these are 30 column blocks - I copied the columns blocks and the last column block I labeled "the last one" in the movie), then the list is not shown completely. 
As a workaround I have found the following solution: Delete a column block and undo the deletion afterwards. After that the list is shown correctly.
However, if I then leave the page and then edit this page again, then I have the same problem, which I then have to solve again via the mentioned workaround.

When I activate Gutenberg 13.5.1 the error is still present and after performing the workaround the error is fixed, but when I then exit the page and edit again the list is displayed correctly

### Step-by-step reproduction instructions

1. Create group block
2. Column block with a column containing an image, heading and paragraph.
3. I have copied this column block

### Screenshots, screen recording, code snippet

![issue_columns_in_group](https://user-images.githubusercontent.com/27292550/176363657-fb8aa559-bcfd-4340-ae67-53c2b83dea8d.gif)

### Environment info

WordPress 6.0
Chrome
Gutenberg 13.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hagege** [comment] 2022-06-29 07:40
I forgot to mention two more points:

1. there is no problem in the frontend
2. if you have more column blocks in the group block, more column blocks will not be shown in the dashboard.

**Comment by hagege** [comment] 2022-06-29 08:05
Here an example with about 100 column blocks within a group block
![list_with_many_columns_blocks_in_group_block](https://user-images.githubusercontent.com/27292550/176384932-35281481-fc3d-4f75-88df-e7e03540df2e.jpg)

**Comment by t-hamano** [comment] 2022-07-23 12:44
I found that this problem is not limited to columns or group blocks.

In the list view, if there are **31 or more nested child blocks**, the 31st and subsequent blocks are not displayed, including the next parent block.

https://user-images.githubusercontent.com/54422211/180605423-a02f1fcd-8a9e-4736-9c2c-294e2ccf2683.mp4

**Comment by t-hamano** [comment] 2022-07-23 12:49
Looking at #35230, it appears that the initial rendering is limited to 30 blocks, which are rendered according to scrolling.
However, if there are more than 30 child blocks, I think the scroll rendering is not working for some reason.

**Comment by jtnico** [comment] 2022-08-29 08:25
@t-hamano  I confirm the problem is not limited to columns or group blocks. 
Test on wordpress 6.0.1 and also in gutenberg 13.9.0 (plugin)

Hope this bug will be fix soon because "List View" is very useful to build page/post containing lot of blocks.

**Comment by andrewserong** [comment] 2023-08-18 05:50
I believe I have a fix for this, over in #53716. The fix looks to update / refresh the list view's windowing calculation when the expanded state of blocks changes (expanding / collapsing anywhere in the tree).

**Closed as completed** 2023-08-20 23:43 UTC
Labels: [Type] Bug, [Package] Editor, Needs Technical Feedback, [Feature] List View
