### ISSUE TITLE
Gutenberg conflicts with Starter Content widgets

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#20827] opened 2020-03-12 12:21 UTC
**Describe the bug**
When Gutenberg is installed, and a site is set to "fresh", error messages are shown in the customizer for widgets included in a theme's starter content.

The site with the starter content can not be published until the widgets are edited.
In my tests, changing the widget title or content removed the error.

I am not familiar with the any changes made for the "Widget blocks in the customizer", but perhaps it is related. 
It does not seem to be theme dependent, I tested different themes that includes starter content.
I only tested with Gutenberg 7.7.0 so I am not sure when the problem was introduced.

Code relevant to widgets in starter content: 
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/theme.php#L2035

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/inc/starter-content.php#L23

**To reproduce**
1. Create a new WordPress site or reset an existing install
2. Activate Gutenberg
3. Activate a theme with starter content, for example Twenty Twenty or Twenty Seventeen.
4. Go to the Customizer.
5. Press Publish
6. See the error: **_**Unable to save due to 2 invalid settings.**_**

**Expected behavior**
I expect the starter content to be saved without errors.

**Screenshots**
![2020-1](https://user-images.githubusercontent.com/7422055/76520256-d9b03d80-6462-11ea-9234-078c76905451.png)

OS: Win10
Browser: Chrome Version 80.0.3987.132
Additional context

Please add the version of Gutenberg you are using in the description.
Version 7.7.0
WordPress Version 5.3.2

**Comment by annezazu** [comment] 2020-04-22 23:32
I was able to replicate this following the steps outlined above using the following setup:
- TwentySeventeen theme
- WordPress: 5.4
- Gutenberg: 7.9.1
- Chrome 81.0.4044.122
<img width="395" alt="Screen Shot 2020-04-22 at 4 31 05 PM" src="https://user-images.githubusercontent.com/26996883/80043507-c0190180-84b6-11ea-83b6-7ec592c51ea4.png">

**Comment by carolinan** [comment] 2020-05-14 06:39
Confirmed that this is still an issue with version 8.1

**Comment by katiebethbrown** [comment] 2020-07-20 23:29
Same issue on

TwentySeventeen theme
WordPress: 5.4.2
Gutenberg: 8.3.0

**Comment by zdenys** [comment] 2020-07-21 08:11
I can still reproduce with:

Twenty Twenty Theme
WordPress 5.4.2
Gutenberg 8.5.1

**Comment by alshakero** [comment] 2020-07-21 12:01
I'm investigating this.

**Comment by alshakero** [comment] 2020-07-21 22:11
It seems to be a core issue. I've created a [Trac ticket](https://core.trac.wordpress.org/ticket/50730) and sent a [pull request](https://github.com/WordPress/wordpress-develop/pull/425) with the fix 🎉 .

**Comment by geekinthegirl** [comment] 2020-08-09 08:47
I came across the same issue in a chat this morning, the user was unable to delete widgets from their footer after I reset their Atomic site, and I was able to replicate when I SUed in: #23234538-hc

Theme: Twenty Twenty
WordPress: 5.4.2
Gutenberg: 8.7.0

**Comment by jartes** [comment] 2020-10-02 10:36
Had a similar situation in 3368333-zen. Disabling Gutenberg (9.0) and saving customizer settings made the trick. Now, with Gutenberg enabled again customizer settings are saving with no error.

**Comment by mattwiebe** [comment] 2020-10-05 20:48
I was trying to dig into a fix for this, but I haven't been able to replicate this on any combination of:

WP: 5.5.1
Gutenberg: 9.1.0; 9.0.0 
Themes: Twenty Twenty; Twenty Seventeen
Themes: Twenty Twenty and Twenty Seventeen. 

Are people changing any values in the Customizer before saving? Which ones? I have tried saving the Starter Content as-is and also editing some widgets and still can't produce an error.

**Comment by carolinan** [comment] 2020-11-08 14:27
Tested on 5.6-beta3-49486 with and without Gutenberg 9.3.0. Twenty Twenty-One and some personal theme projects.
 I am no longer able to reproduce this issue.

**Comment by annezazu** [comment] 2020-11-16 15:43
@carolinan thanks for updating! @mattwiebe thanks for testing! I'm going to go ahead and close this out as a result since this no longer seems to be an active issue. Please re-open if that's not the case.

**Closed by annezazu** 2020-11-16 15:43 UTC
Labels: [Type] Bug
