### ISSUE TITLE
Classic block overlaps previous block

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#5908] opened 2018-03-30 13:59 UTC
It seems there is an issue with the classic block that overlaps the previous block in the editor.

See the screenshot below

![classic_block_issue](https://user-images.githubusercontent.com/1268089/38140248-9b8cdf44-343b-11e8-837e-df95df49134b.png)

**Comment by jasmussen** [comment] 2018-03-30 14:11
This looks like the intended behavior when you have the dock toolbar to block option enabled. For the classic block, this doesn't work, which is just one reason why we're redesigning the classic block in https://github.com/WordPress/gutenberg/pull/4948.

**Comment by paulwilde** [comment] 2018-03-30 14:12
Unless I'm mistaken, isn't this intended? I see your focus is in the classic block. So presumedly the toolbar disappears when you remove that focus?

**Comment by SuperGeniusZeb** [comment] 2018-03-30 15:49
@paulwilde Yeah, technically it is intended behavior... but since the Classic block toolbar is so big, it gets in the way a lot more than the toolbars of other blocks, hence why @jasmussen pointed out that the Classic block is being redesigned in #4948 to have the toolbar be always shown and be an inline part of the block rather than an overlay that appears on focus.

**Comment by karmatosed** [comment] 2018-04-01 09:58
I think the redesign covers this issue, so closing for now. Thanks.

**Closed by karmatosed** 2018-04-01 09:58 UTC
