### ISSUE TITLE
Having trouble appending blocks in a column on the Columns (beta) block

### ISSUE THREAD

**Issue by babblebykev** [WordPress/gutenberg#8887] opened 2018-08-12 00:22 UTC
Whenever I try to add a new block at the end of a column on the Columns block, the plus button for adding new blocks doesn't appear when I hover my mouse on the last block of the column.

**Comment by designsimply** [comment] 2018-08-14 19:39
Thank you for posting! I would like to close this issue as a duplicate of #8589 which proposes adding a trailing inserter for nested blocks.

**Closed by designsimply** 2018-08-14 19:39 UTC
Labels: [Component] Inserter, [Component] Nested / Inner Blocks, [Status] Duplicate
