### ISSUE TITLE
Units reset to px when resizing a Cover block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#41636] opened 2022-06-09 15:48 UTC
### Description

In the current experience, if I set the Cover block to use any unit, other than `px`, then resize the block with the ResizableBox control, the units will revert back to `px`. Which means that when `vh` or `vw` is used, the direct mechanism for dragging the height of the cover block is no longer useful, as you are required to navigate back to the control and pick the unit again, and type in a value. 

### Proposal 
Is it possible to maintain the units, perhaps calculating the pixel height from the resizable box into the alternative units? Say if we set the cover block's minimum height to 100vw, then grab that number of pixels v the height or width of the viewport to use for calculating the delta. Then convert back to 1-100 (for vh/vw at least). Just a thought, but there has to be a way to do this. 

### Step-by-step reproduction instructions

1. Add a cover block.
2. Set the block's minimum height in the Inspector Controls to 20.
3. Set the units to `vh`.
4. Resize the cover block via the ResizableBox dragging handle.
5. See the units converting back to pixels.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1813435/172888122-9fc3a2a6-76e4-41ac-93d3-dc0f6697c409.mp4

### Environment info

Gutenberg 13.4.0
WordPress 6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-06-15 08:15
I am closing as a duplicate of #39077.

**Closed as not planned by Mamaduka** 2022-06-15 08:15 UTC
Labels: [Block] Cover

**Comment by richtabor** [comment] 2022-06-15 15:37
> I am closing as a duplicate of https://github.com/WordPress/gutenberg/issues/39077.

Bah, I wrote that one too 🤦
