### ISSUE TITLE
Can't exit preformatted block even if I press Esc

### ISSUE THREAD

**Issue by Wingo5315** [WordPress/gutenberg#13380] opened 2019-01-20 08:11 UTC
**Describe the bug**
I cannot get out of the Preformatted block by pressing Enter or the Down key - and even pressing Esc doesn't work.

**To Reproduce**
1. Create a new post/page.
2. Create a preformatted block.
3. Type something.
4. Press Enter or down key.

**Expected behavior**
I was expecting to be able to exit the Preformatted block using the Esc key.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 64.0.2

**Smartphone (please complete the following information):**

**Additional context**
- I am using WordPress 5.0.3

**Comment by aduth** [comment] 2019-01-21 16:06
Can you clarify what "get out" means to you?

I would not expect <kbd>Enter</kbd> to leave the block, as one of the primary purposes of the Preformatted block is to preserve line breaks verbatim.

<kbd>ArrowDown</kbd> works for me in my testing (Firefox, Windows 10). Can you elaborate:

- Where is the cursor position for you after pressing the button?
- What is the contents of the block?
- What is the next block, if applicable?

**Comment by Wingo5315** [comment] 2019-01-21 16:24
This video emulates what I did in order to find that bug: [https://onedrive.live.com/embed?cid=E2138AE1D101D504&resid=E2138AE1D101D504%214257&authkey=AJFiUgh3b-IRmf8](https://onedrive.live.com/embed?cid=E2138AE1D101D504&resid=E2138AE1D101D504%214257&authkey=AJFiUgh3b-IRmf8)
(At the time, I entered the content "ballyhoo();" before pressing the down key, expecting for the focus to exit that block.)

**Comment by aduth** [comment] 2019-01-21 19:55
Are you able to reproduce on a fresh site, like one created via [jurassic.ninja](https://jurassic.ninja/) ?

I'm curious if there is a plugin/theme interoperability issue at play here.

**Comment by Wingo5315** [comment] 2019-01-22 16:41
I just tried it on [jurassic.ninja](https://jurassic.ninja) and I got the same result [http://calumchilds.com/videos/13380_2.mp4](video). I tried it again without Jetpack and it still didn't change block.
(Another question: Is there any easy way of uploading the videos to Github for free?)

**Comment by designsimply** [comment] 2019-01-25 23:45
> Another question: Is there any easy way of uploading the videos to Github for free?

Not that I know of for videos! If you can make a short enough animated GIF though, those can be uploaded directly to GitHub. For videos, I have been using https://cloudup.com/.

**Comment by iseulde** [comment] 2019-02-28 15:41
Related: #14114.

**Comment by oxyc** [comment] 2020-06-20 23:11
Tested using the master branch of Gutenberg and currently both `esc` and down arrow exits the block. I also tested on jurassic.ninja where it works. @Wingo5315 could you check if it works and it's okay to close this issue?

**Comment by annezazu** [comment] 2020-09-24 03:09
As an update with WordPress 5.5.1 and Gutenberg 9.0, hitting escape leads to this view where one is able to select the overall block: 
<img width="654" alt="Screen Shot 2020-09-23 at 9 04 49 PM" src="https://user-images.githubusercontent.com/26996883/94096078-6bb8db80-fde0-11ea-9f0c-79eeffd398ea.png">

On the flip side, using the up or down arrow completely removes you from the block:

![arrows](https://user-images.githubusercontent.com/26996883/94096158-9e62d400-fde0-11ea-9244-6868ecc5b97f.gif)

From there, I viewed both pressing enter (stays preformatted) vs down key (creates a new paragraph block): 

![enter vs down key](https://user-images.githubusercontent.com/26996883/94096313-044f5b80-fde1-11ea-8e6a-7923691e2f2e.gif)

@Wingo5315  I'm closing this out for now as a result but welcome your feedback if you believe this is closed incorrectly!

**Closed by annezazu** 2020-09-24 03:09 UTC
Labels: Needs Testing, [Block] Preformatted, [Feature] Blocks, [Feature] Writing Flow
