### ISSUE TITLE
Template Editor: Cursor Loses Focus While Typing

### ISSUE THREAD

**Issue by donalirl** [WordPress/gutenberg#33412] opened 2021-07-14 07:12 UTC
## Description
The cursor loses focus mid-typing.

## Step-by-step reproduction instructions
Using Gutenberg 9.7+ and a FSE ready theme:

1. In the Template Editor, click the Site Title block
2. Start typing the new text
3. Notice the typing is interrupted because the block is no longer selected

Also reproducible on other blocks such as the Buttons block.

## Expected behaviour
I expected to continue typing without interruption.

## Actual behaviour
My typing was interrupted, making it impossible to finish typing.

## Screenshots or screen recording (optional)
In both the Site Title block (header) and the Buttons block (footer), I have demonstrated the action of typing, but then it abruptly stops because the cursor is no longer focused within the block:

https://user-images.githubusercontent.com/30727666/125578853-947675e2-4d55-4e3f-8696-1417d5552a08.mp4

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.9
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system:  Windows 10
- Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by annezazu** [comment] 2021-07-14 18:04
Thanks for reporting this! Noting that this needs to be tested with Gutenberg 11.0+ (ideally 11.1 RC launched today).

**Comment by stacimc** [comment] 2021-08-26 21:46
Noting that I was unable to reproduce this in Gutenberg 11.3, testing with Buttons, Site Title, and Site Tagline for good measure.

**Comment by talldan** [comment] 2021-10-26 05:48
I wasn't able to reproduce this in the latest version of Gutenberg. I'll close the issue, but if you still experience it, let me know and I can reopen the issue.

**Closed as completed by talldan** 2021-10-26 05:48 UTC
Labels: Needs Testing, [Block] Site Title, [Feature] Template Editing Mode
