### ISSUE TITLE
Group alignfull within a group align full

### ISSUE THREAD

**Issue by unprintedch** [WordPress/gutenberg#31317] opened 2021-04-29 08:21 UTC
## Description
If we use group align full within a group alignfull there is an overflow on the left

## Step-by-step reproduction instructions
Add a group alignfull
Add another one in it...

## Expected behaviour
It would be nice to have it align and nice

## Actual behaviour

<img width="1629" alt="dc_screen_shot 2021-04-29 à 10 11 52" src="https://user-images.githubusercontent.com/2622001/116521577-6cfd3a00-a8d4-11eb-99ed-d60c11470f97.png">

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
## Device information
- Device: Desktop
- Operating system:  "iOS 14"
- Browser: Chrome 86.0

**Comment by carolinan** [comment] 2021-05-07 13:12
Hi
I have not been able to reproduce this using:

WordPress version: 5.7.1
Gutenberg version: Not installed
Are all plugins except Gutenberg deactivated? Yes
Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty-One
Device: Desktop
Operating system: Windows 10
Browser: Version 90.0.4430.93

**Comment by unprintedch** [comment] 2021-05-11 04:43
Yes i'll try to fine out another reason.

**Comment by annezazu** [comment] 2021-05-19 00:44
Since this can't be replicated and further information hasn't been shared just yet, I'm going to close this issue out. Feel free to re-open if you have more to share though @davouid ! Thanks for opening this and engaging around the core editor.

**Closed as completed by annezazu** 2021-05-19 00:44 UTC
Labels: Needs Testing, [Block] Group
