### ISSUE TITLE
Template change won't update in Preview

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50016] opened 2023-04-23 18:57 UTC
### Description

After selecting a different template for a page (e.g. one with a sidebar) and then previewing the page in a new tab, the updated template won't show. You have to click "Update" first.

### Step-by-step reproduction instructions

1. Select a page
2. Change the template
3. Preview the page in a new tab without the changes

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/17861443/233859358-d59c3460-2502-4fc2-a545-5427d6acf512.mp4

### Environment info

 - Wordpress 6.2
 - Brave Browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-04-24 09:49
Thanks for opening this issue! This is a duplicate of the following: https://github.com/WordPress/gutenberg/issues/28208 I'm going to close this out as a result as it helps to have feedback consolidated there (similar to why I closed out https://github.com/WordPress/gutenberg/issues/37894).

**Closed as completed by annezazu** 2023-04-24 09:49 UTC
