### ISSUE TITLE
Cannot insert Block Patterns inside Inner Blocks

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#26805] opened 2020-11-08 04:36 UTC
**Describe the bug**
The Block Editor does not allow the insertion of Block Patterns inside a block that uses the `InnerBlocks` component (like the Group and Columns block).

**To reproduce**
1. Add a new post.
2. Add a "Group" block inside the post.
3. Add a "Paragraph" block inside the "Group"
4. Add another "Paragraph" block inside the "Group".
5. Use the appender button between the two paragraphs (the one that toggles on hover), and click on "Browse All".

**Expected behavior**
After completing Step 5 above, the Patterns tab should show in the Block Directory and allow me to insert a block pattern inside my Group. However, only the list of Blocks shows up, so I'm not able to insert a pattern inside my Group.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin.
- If the Gutenberg plugin is installed, which version is it? 9.3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.111

**Smartphone (please complete the following information):**

**Comment by carolinan** [comment] 2020-11-08 11:23
This is a duplicate of https://github.com/WordPress/gutenberg/issues/22400, but because the description and steps to reproduce is clearer in this issue, I will close mine.

-A way around this for now, is to select and manually move the pattern to its position.

**Comment by talldan** [comment] 2020-11-09 06:56
This looks like a duplicate of https://github.com/WordPress/gutenberg/issues/26281, which was also considered a duplicate of https://github.com/WordPress/gutenberg/issues/24403, so I'll close this one.

Thanks for reporting though, hopefully this one will be fixed soon.

**Closed by talldan** 2020-11-09 06:56 UTC
Labels: [Feature] Patterns
