### ISSUE TITLE
Custom gallery block ignores images order when saving to meta (after the initial save)

### ISSUE THREAD

**Issue by premitheme** [WordPress/gutenberg#13648] opened 2019-02-04 05:51 UTC
**Describe the bug**
I'm developing a custom gallery block that should save to post meta. I managed to get everything working fine except being able to order the images.

When the block is empty, when I select images in the media manager screen and move to gallery edit screen to order the images, insert them and update the post, the block saves with no problems. But when I try to reorder them again in the galley edit screen, the new order applies to the images in the editor but once I hit "Update" button, the editor images' order resets and the new order never be saved to the meta.

It's important to mention that If I add or remove images the block saves the new images normally, only the reordering that is not saving.

I'm not sure if this is a bug or I'm doing something wrong, but when I tweak the block a little bit to save the common way (save function instead of saving to meta), then I can reorder the images and they save fine.

**##UPDATE##**
The reset behavior only occurs when saving the meta as an array of strings, as shown below I save every image as JSON serialized object containing image `url`, `id` and `alt`.
If I changed the saved data to only an array of image ids (integers in this case), the whole problem does not exist. 

Here is my "attributes" part:
```javascript
attributes: {
    images: {
        type: 'array',
        source: 'meta',
        meta: '_pt_folio_imgs',
        default: []
    }
},
```
Here is my `edit()` function:
```javascript
edit({ attributes, className, setAttributes, isSelected }) {
    const { images } = attributes;
    const imagesParsed = images.map( ( img ) => JSON.parse( img ) );

    function updateImages( newImages ) {
        setAttributes({
            images: newImages.map( ( img ) => JSON.stringify({ id: img.id, url: img.url, alt: img.alt }) )
        });
    }

    function removeImages() {
        setAttributes({
            images: []
        });
    }

    const controls = (
        <BlockControls>
            { !! images.length && (
                <Toolbar>
                    <MediaUpload
                        multiple
                        gallery
                        allowedTypes={ [ 'image' ] }
                        value={ imagesParsed.map( ( img ) => img.id ) }
                        onSelect={ updateImages }
                        render={ ({ open }) => (
                            <Fragment>
                                <IconButton
                                    className="components-toolbar__control"
                                    label={ __( 'Edit gallery' ) }
                                    icon="edit"
                                    onClick={ open }
                                />
                                <IconButton
                                    className="components-toolbar__control"
                                    label={ __( 'Delete All' ) }
                                    icon="trash"
                                    onClick={ removeImages }
                                />
                            </Fragment>
                        ) }
                    />
                </Toolbar>
            ) }
        </BlockControls>
    );

    if ( 0 === images.length ) {
        return (
            <Fragment>
                <MediaPlaceholder
                    icon="format-gallery"
                    className={ className }
                    labels={ {
                        title: __( 'Test Gallery' ),
                        instructions: __( 'Drag images, upload new ones or select files from your library.', 'rouben-core' )
                    } }
                    onSelect={ updateImages }
                    accept="image/*"
                    allowedTypes={ [ 'image' ] }
                    multiple
                />
            </Fragment>
        );
    }

    return (
        <Fragment>
            { controls }
            <ul>
                { imagesParsed.map( ( img ) => {
                    return (
                        <li className="blocks-gallery-item" key={ img.id || img.url }>
                            <img
                                src={ img.url }
                                alt={ img.alt }
                                data-id={ img.id }
                            />
                        </li>
                    );
                }) }
            </ul>
        </Fragment>
    );
},
```
And here is my `save()` function:
```javascript
save() {
    return null;
}
```

**To Reproduce**
1. Insert the block.
2. Add images.
3. Update the post.
4. I go to "Edit Gallery" and change the order of images -> the order updated in the editor.
5. Update the post -> the order resets in the editor and is not saved in the meta.

**Expected behavior**
When I change the images order in the gallery edit screen and then publish/update the post it should save the new order of the images.

**Screenshots**
![feb-04-2019 07-32-14-low](https://user-images.githubusercontent.com/3824596/52191915-b377a180-284f-11e9-920a-b52e67589ab1.gif)

**Desktop:**
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome 71.0.3578.98
 - WordPress 5.0.3

**Comment by noisysocks** [comment] 2019-11-14 05:47
Hey @premitheme! I'm having trouble reproducing this one.

Are you still running into this issue? If so: could you please share a minimal code example which has only the parts pertaining to `setAttributes()` and not the media gallery? That will help me narrow down what's going on here.

**Comment by shazahm1** [comment] 2019-11-14 13:58
I saw this come up in the #core-editor Slack channel yesterday...

I ran into this issue too. This seems to be have been fixed in Gutenberg 6.7/6.8 and presumably in the just released 6.9. But, still exists in WP 5.2/5.3. Basically I ran into two issues:

 - `setAttributes()`  post meta, registered as an `array` or in my case `object`, does not update the db when changed.
 - Adding a second block, of same type to the same page, it is initialized with the post meta registered default value instead the last value set with `setAttributes()`. The registered post meta type did not seem to matter as I switch from `object` to `string` (just saving the object serialized).

This thread in Alpha/Beta/RC  wp.org support forum has more detail, if needed.

https://wordpress.org/support/topic/setattributes-does-not-work-as-expected-with-two-or-more-post-meta-fields/#post-12103993

As I mentioned, for me, the issues seemed to be resolved by having the Gutenberg plugin active. So, these bugs have been fixed.

Since I did not want to wait for WP 5.4, to workaround this I ended up registering the post meta as a `string` (serialized array of objects). I then had to use `compose` with `withDispatch` returning a function to update the post meta value and  used `withSelect` to select the post meta value and return it as a property. Like this:

Register post meta using the `sanitize_callback` to unserialize and sanitize value before serializing again and saving to db:
``` javascript
register_meta(
	'post',
	'_cbd_carousel_blocks',
	array(
		'single'            => TRUE,
		'type'              => 'string',
		'auth_callback'     => function() {

			return current_user_can( 'edit_posts' );
		},
		'sanitize_callback' => array( __CLASS__, 'sanitize' ),
		'show_in_rest'      => array(
			'prepare_callback' => function( $value ) {

				// If value is empty, then return an empty JSON encoded array.
				if ( ! $value ) $value = wp_json_encode( array() );

				return $value;
				//return wp_json_encode( $value );
			},
		),
	)
);
```

The compose to update and save post meta:
``` javascript
export default compose( [
	withDispatch( ( dispatch, { value } ) => {

		return {
			setMetaFieldValue: ( value ) => {
				dispatch( 'core/editor' ).editPost( { meta: { _cbd_carousel_blocks: value } } );
			},
		};

	} ),
	withSelect( ( select, props ) => {

		return {
			metaCarousels: select( 'core/editor' ).getEditedPostAttribute( 'meta' )._cbd_carousel_blocks,
		};

	} ),
	withInstanceId
	]
)( Carousel )
```

I hope this helps!

**Comment by premitheme** [comment] 2019-11-22 15:33
I had to withdraw the entire idea since I didn't get a response since February, therefore I don't have the code active to test if the problem is resolved.

Here is the attributes part:
```javascript
attributes: {
    images: {
        type: 'array',
        source: 'meta',
        meta: '_pt_folio_imgs',
        default: []
    }
},
```

And here is the `seAttributes` part:
```javascript
function updateImages( newImages ) {
    setAttributes({
        images: newImages.map( ( img ) => JSON.stringify({ id: img.id, url: img.url, alt: img.alt }) )
    });
}
```

**Closed** 2020-01-13 14:01 UTC
Labels: [Status] Needs More Info, [Type] Bug

**Comment by bikramchettri** [comment] 2023-01-02 11:35
Were you able to solve the issue?
