### ISSUE TITLE
Allow draging to reize column width

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#38350] opened 2022-01-30 12:01 UTC
## What problem does this address?

I have two columns, one with text and one with image
I want to "make the image bigger" (relative to the text)
I drag the image and, because it's now bumped up against the inside of the column on the inside, it just gets wider "out the side" of the column to the right.

The way to actually make the image wider is to click the column and change the width in %, then the image can be dragged bigger.

https://greencloud.gn.apc.org/index.php/s/Dtmp2s443ANA7gE

## What is your proposed solution?

When you drag the image (or other column content) to make it bigger, the column width is adjusted to suit. In this case, the text on the left would get narrower as the image gets bigger. 

This is how the "image and text" block works,

**Comment by annezazu** [comment] 2022-02-09 08:20
Thanks for opening this @gingerling. I agree. It would be really neat to have this. For now, closing this out as a duplicate of this previous issue (unless I've misunderstood): https://github.com/WordPress/gutenberg/issues/15659

**Closed as completed by annezazu** 2022-02-09 08:20 UTC
Labels: [Status] Duplicate, [Block] Columns
