### ISSUE TITLE
Gutenberg navigates to edit.php upon table creation (macOS Safari 12.0)

### ISSUE THREAD

**Issue by Luehrsen** [WordPress/gutenberg#10436] opened 2018-10-09 12:02 UTC
**Describe the bug**
Upon the creation of a table block the browser navigates to /wp-admin/edit.php and discards all the edits. This only happens in our office in macOS Safari 12.0. 

![bildschirmfoto 2018-10-09 um 13 54 08](https://user-images.githubusercontent.com/1105871/46667950-64846d00-cbcb-11e8-9c54-2dfe5b838ad9.png)

**To Reproduce**
1. Go to any Gutenberg edit screen in Safari 12.0 on macOS.
2. Add a table block either through the inserter or /table command
3. Create the desired number of cols and rows.

http://www.wp-munich.com/gutenberg/gutenberg_table_bug.mov

**Expected behavior**
We expected to stay in the edit screen.

**Desktop (please complete the following information):**
 - OS: masOS High Sierra (10.13.6)
 - Browser: Safari
 - Version: 12.0

**Comment by designsimply** [comment] 2018-10-15 23:44
Thank you for reporting this! Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/10254.

**Closed by designsimply** 2018-10-15 23:44 UTC
Labels: [Status] Duplicate
