### ISSUE TITLE
Offer Gutenberg As A Separate Plugin Instead Of Integrating It Into WordPress Core

### ISSUE THREAD

**Issue by Naspat** [WordPress/gutenberg#8111] opened 2018-07-21 22:07 UTC
Hello,

To integrate **Gutenberg** into the **WordPress core** without offering the option for WordPress users worldwide to freely choose whether they want to accept it or not just shows how far short-sighted Gutenberg developers have come in terms of considering and respecting user needs as well as understanding the practical implications of it in the real world. And no, we don’t even want to get started talking about your proposed and crafted "solution" by installing (yet again) another defective plugin (bugs guaranteed) which in turn would emulate the well-proven, stable and classic WordPress environment, when in fact it should be exactly the other way around!

**Yes, WordPress users should have the absolute freedom to choose whether they want to install and use the Gutenberg feature/plugin or not** rather than having to install an additional plugin which presumably preserves the established WordPress environment just because Gutenberg has become part of the WordPress core. Simply unbelievable...

**OBSERVATION:** After using Gutenberg for merely several minutes we thought this can’t be for real and must be a joke. In simple words: **Gutenberg at its current stage is completely useless for feature-rich and highly complex Websites/E-Commerce solutions and throws you right back into the 18th century!** Gutenberg misses so many important features, we don’t even know where to start with. Looking at the current Gutenberg version inevitably **makes you wonder whether Gutenberg "developers" ever took a hard and detailed look at existing top-notch page builders**, such as i.e. the WPBakery Page Builder, as well as applying best practice in web development, left alone all possible (yet to be discovered) Gutenberg bugs and endless incompatibility issues with other plugin and theme authors!

**To force the entire WordPress community to a simplistic and semi-finished Gutenberg solution without even getting close to a level of professional page builders is simply stunning, ignorant and completely irresponsible. This is nothing short of boarding a semi-finished airplane...**

**BOTTOM LINE/SUGGESTION:** Before planning on integrating Gutenberg into the WordPress core we strongly suggest to ensure Gutenberg covers all features/functions of modern page builders. 

Once you’ve reached this level continue with making Gutenberg completely bug-free, speed optimized and compatible with all major plugin and theme/template authors out there.

Finally, once you've gotten to this proficiency level build several highly complex dev stage Websites/E-Commerce solutions which include (among many other factors) thousands of variable products in different languages (i.e. WPML), various user roles, different currencies and prices/discounts, various dynamic sliders (i.e. Smart Slider 3 Pro), tables, graphs/charts, submission forms and fully automated imports/exports spread across many different pages.

Only if you have gone through the entire **due diligence process** and cover above mentioned features can you start considering to integrate (if at all!) Gutenberg into the WordPress core, not one second before!

Should you realize that you can’t match these basic expectations and widely used features go back to the drawing board and **reconsider your entire Gutenberg "core strategy" unless you want to create a lot of upheaval, a big mess and, ultimately, to commit complete suicide** as many WordPress users across the world will simply switch to other CMS solutions.

Considering above insights it should be in your best interest to **offer Gutenberg as an entire separate plugin** which we as WordPress users can install at any time should Gutenberg once have reached the same proficiency level like modern page builders do.

**In the meantime, we highly recommend to start using WPBakery (or any other professional page builder out there; see links below) for testing and insight purposes to actually understand what's at stake and what we are talking about here.** By simply using i.e. WPBakery **you will immediately notice the stark difference between the current and underdeveloped Gutenberg "solution" versus the comprehensive and professional WPBakery page builder** which in turn makes any further discussion unnecessary.

**WPBakery:**
https://wpbakery.com

**Elementor:**
https://elementor.com

**Beaver Builder:**
https://www.wpbeaverbuilder.com

**Divi Builder:**
https://www.elegantthemes.com

**DISCLAIMER:** We do neither promote any of the above mentioned plugins nor are we affiliated with any of them. The only purpose of this entire review is for WordPress to **stop patronizing WordPress users and acknowledge and respect their needs!** Again, leave it up to us WordPress users whether we want to use Gutenberg or just any other professional page builder. - That’s all!

Regards,
Patrick

**Comment by chrisvanpatten** [comment] 2018-07-22 13:22
@Naspat A few points of clarification:

1. The Classic Editor plugin does not "emulate" the current editor. The current editor and all its code will continue to be in WordPress core for the foreseeable future. The Classic Editor plugin will simply disable Gutenberg, exposing the Classic Editor underneath.
2. Gutenberg in its current revision should not be considered a page builder, and *third-party page builders will continue to work.* Even as Gutenberg picks up more page builder features, third party page builders will continue to work. In fact I think it's safe to say that third-party page builders will _always_ work, will always _exist_, and will be an important part of the WordPress ecosystem for years to come.
3. There's been a lot of dialogue within the GitHub issues, learning from existing paradigms in Page Builder plugins. @SuperGeniusZeb has lead the charge on that but he's far from the only one.

I'm sure you can appreciate that there is a chicken-and-egg scenario: if Gutenberg lives as a plugin indefinitely, plugin and theme developers may choose avoid integrating with it — there are always other priorities. By absolutely committing to getting it in Core, and making it clear that it is the future of the content management experience in WordPress, it sends a message to third-party developers that integrating with Gutenberg _must_ be on their roadmaps, which will lead to many of the compatibility issues you referenced being solved. And until then, concerned users can continue to fall back on the Classic Editor safely and reliably.

**Comment by Naspat** [comment] 2018-07-22 15:50
A few **REAL WORLD** points of thought:

**As for 1)** Having to install yet again! another plugin (bugs are guaranteed!) to deactivate Gutenberg simply ignores best practice in professional web development. In other words: **You’re making things more complicated and prone to failure than they need to be. - Period!**

Instead of letting WordPress users, plugin and theme developers choose freely to opt-in for using Gutenberg you force them to install a plugin to deactivate Gutenberg. This is exactly the sort of thinking and behavior that brought Facebook and Google to court since they were charged with intentionally confusing and misleading customers. Definitely not a smart Gutenberg reputation strategy to begin with in progressive 2018…

**As for 2)** The only way to prove your point (..._"third-party page builder will continue to work"_...) is to **make Gutenberg absolutely voluntary to install** for WordPress users, plugin and theme developers. **Leave it up to the community to decide on Gutenberg and stop patronizing them!** WordPress is supposed to be an open and free community (not a communist model!) without any constraints whatsoever. Should that no longer be the case please let us know accordingly so we can start searching for CMS alternatives… 

**As for 3) Looking at Gutenberg at its current and completely underdeveloped stage we are talking about years of further and very intense development before Gutenberg even comes close to existing professional page builders,** left alone all the **costly and time-consuming Gutenberg bugs** associated with it and the fact that professional page builders will always be one step ahead due to their long term expertise and specialized learning curve provided in turn by precious customer feedback.

**It is simply outrageous and arrogant by the Gutenberg team to believe to easily compete against professional page builders in the next several years to come** while, at the same time, forcing WordPress users, plugin and theme developers to install a plugin to avoid using Gutenberg. **There’s only one expression for this sort of behavior: "Compulsion"...**

**INFO:** Forget about your chicken-and-egg scenario and your mentioned _"foreseeable future"_ blabla. This is nothing but politics! Instead **do your homework by start having a very hard long look at professional page builders** with all their efficient and complex features and keep developing your Gutenberg to a professional level.

**BOTTOM LINE:** If Gutenberg becomes a real viable option for WordPress users, plugin and theme developers, they will automatically switch to Gutenberg. If not, Gutenberg simply dies as **free market forces will take over due to their self-regulated mechanism of supply and demand.** The path of constraint and paternalism has and will never work in a free world.

**BONUS POINT OF THOUGHT:** Imagine yourself having built your very own online E-commerce company with 10,000 of man-hours in development, customization and tests while being responsible for your employees and customers around the globe. **The last thing you need are some developer kids (nerds) from around the block with no REAL WORLD experience** who think they can sell you a semi-finished Gutenberg wheel while completely forgeting about the **REAL WORLD** impacts (interruptions, website crashes, loss of data, revenues and market share, firing employees, etc.) on all those WordPress/WooCommere businesses out there. Well, if this is the way you want to introduce Gutenberg and do business, good luck! Do it once on the Titanic and live with the consequences...

Regards,
Patrick

**Comment by SuperGeniusZeb** [comment] 2018-07-22 18:57
Gutenberg is not intended to replace the major page builders at all. It is intended to provide a common foundation for them all to build upon, which should help reduce the ever-annoying issue of having to rebuild your content after switching page builders. If everything uses a common base API, then you can have page builder plugins be split up into alternate/better GUIs for the Gutenberg back-end, extensions that add additional APIs, or plugins that add blocks which can be used with any builder, rather than the monolithic page builders we have now where you get stuck in one because of its exclusive slider module or because moving to another one requires rebuilding all your content.

Gutenberg is really just like WordPress in general: something basic that is designed to provided necessary functionality, but can be extended to do anything.

To make Gutenberg just a clone of the other page builders would be short-sighted. It seems like the obvious thing to do, but I no longer think it would be the right thing to do. The WordPress team realized something I did not at first.

Back when I first heard about Gutenberg last year, I was viewing it under the assumption that it was supposed to be a monolithic solution like Divi, Elementor, Beaver Builder, Fusion Builder, Visual Composer or Oxygen. I thought it was supposed to replace page builders, so I was confused why it seemed so basic and underpowered. What was the point?

But then I realized it was not supposed to kill page builders at all. It will actually make them more powerful. Gutenberg may end up being the greatest thing to happen to page builders, because it will provide a common foundation they all build off of. I realized that with Gutenberg in core, everything will start becoming easier. Divi (my page builder of choice) will become better. It will be like the early days when everyone was using plugins that added a single widget or shortcode, except that they will add blocks instead that can be used anywhere and edited visually, and be accessible from any page builder interface you want.

WordPress is supposed to be modular. You install a plugin and it adds one or a couple things. But right now there are page builder plugins that act as backend APIs, module bundles, and GUIs all at once, trapping people into a single ecosystem, which is often closed-source (Visual Composer, Fusion Builder, Oxygen), rather than the open-source ecosystem of WordPress in general.

Like the color picker system in Divi but also like the custom-width columns of Beaver Builder? And what if you like the user interface of Elementor? Well what if the color picker was its own plugin that could be installed and used with any builder? And what if the custom-width columns were merely custom blocks added by another plugin? And how about if the graphical user interface was yet another plugin? Gutenberg makes this mix-and-matching of various extensions and functionality possible.

Themes will become more powerful through Gutenberg as well. Themes will become far more flexible, with Gutenberg eventually allowing for full-on website template building. Themes will become merely bundles of preset styles and pre-made template that you can easily and visually customize if desired.

I think Gutenberg will help bring the modularity of WordPress to website building. That is its purpose. The greatest strength of WordPress is its extensibility, and Gutenberg will only increase that.

Thinking Gutenberg should have all the page builder features is like thinking WordPress should have an e-commerce system and SEO tools built-in. It should not. There is no need for that. But the popularity of page builder plugins (and the subsequent lack of use of the current editor) right now have shown that what WordPress does need is a common website building foundation.

And I am not alone in my enthusiasm. the Beaver Builder team seems to be looking forward to Gutenberg as well:
https://www.wpbeaverbuilder.com/future-web-gutenberg-facebook-wordpress-myspace/

Elegant Themes (the Divi developers) also appear quite positive about it:
https://www.elegantthemes.com/blog/editorial/the-value-of-wordpress-designers-and-developers-in-the-gutenberg-era

The Elementor team seems pretty optimistic as well:
https://docs.elementor.com/article/257-gutenberg
>Our estimate is that the Gutenberg project will contribute to WordPress’s continual growth as the #1 CMS in the world.

I think the inclusion of Gutenberg in core will be a big boost to the developer community. Plugins will start popping up that add all sorts of useful blocks or add additional functionality to Gutenberg, and existing plugins will be able to start integrating more and taking advantage of the functionality Gutenberg provides.

In my opinion, Gutenberg will not constrain. It will actually do the reverse and help free users from the vendor lock-in caused by the current monolithic page builders.

In terms of backwards compatibility, I do not think there is any reason to worry. The current plan (correct me if I am wrong, @mtias) is that if an incompatibility is detected when loading the Gutenberg editor, a message will appear to inform the user that there is a conflict and that they should install the Classic Editor plugin. The callout to try Gutenberg in the upcoming 4.9.8 release (unless it gets delayed again) includes a prominent button and directions to install the Classic Editor plugin if desired to prepare for WordPress 5.0. There is also, of course, the Classic block that is used automatically for existing content, as well as support for most metaboxes to appear in the editor and work just fine. Additionally, since 5.0 is a major update, websites will not upgrade automatically, and so people can hold off on updating until they are ready, just in case the Classic Editor plugin is somehow not enough.

That said, there are still a few bugs present which result in less-than-ideal content transfer when converting Classic blocks to standard Gutenberg blocks, but they are all planned to be fixed before the release of 5.0, so I see nothing to worry about there.

With the support of many major plugins (WooCommerce, Yoast, pretty much all major page builders), the upcoming callout that points out the existence of the Classic Editor plugin, all the backwards compatibility features already in Gutenberg itself (Classic block used for all content pre-Gutenberg, metabox support, Shortcode block) and those coming soon (incompatibility detection and prompt to install Classic Editor), not to mention the fact that 5.0 is **not** an automatic update, I see no reason to worry about backwards compatibility.

If you are just using WordPress with no plugins, Gutenberg is a neat upgrade from what you currently have. If you are using page builders like Divi or Elementor or Beaver Builder, Gutenberg will have practically no effect on you at first (though the benefits will start to become apparent as the page builders and other plugins start integrating). If you are in some situation where you need the Classic Editor, you can just install the Classic Editor plugin and upgrade to 5.0. The welcome screen after updating to 5.0 will surely include a link to install the Classic Editor plugin, so even there you will be made aware of its existence.

In order to be negatively affected by Gutenberg being in core, you need to:
- Not already be aware of and preparing for Gutenberg, even after the months between the 4.9.8 release (which includes a rather large and prominent notice about Gutenberg) and the release of 5.0.
- Not know about the Classic Editor plugin despite the prominent mention in the 4.9.8 notice. (And 4.9.8 is an automatic update, meaning everyone who is using 4.9.x should see it before updating.)
- Update to 5.0 (which requires user intervention and uses a major version increase, implying big changes)
- Still not know about the Classic Editor plugin despite its inevitable mention in the 5.0 post-update screen.
- Be in a situation where you are using a plugin or theme that is incompatible with Gutenberg but somehow does not trigger the incompatibility detection (which would prompt you to install the Classic Editor).
- Still not be aware of the Classic Editor plugin after doing a quick online search regarding the new WordPress update.

And that is all assuming that you even have an incompatibility in the first place. With the Classic block (used automatically for all pre-Gutenberg/non-block content), the metabox support, and incompatibility detection, it is unlikely that most users will be affected by Gutenberg. All the major plugins (including page builders) are supporting Gutenberg, and plugins that do not affect the editor will not be affected at all.

It seems almost impossible to me for someone to update to 5.0, have an incompatibility, and yet not be aware that they can install the Classic Editor plugin to continue as they have before.

Also, if enough people disagree with the direction WordPress is heading in, then they can always fork it. That is the beauty of open-source. If there is a strong enough desire to go a different direction than Gutenberg, then there will be a fork, just like what happened with other projects like GNOME 3 and OpenOffice. In fact, **WordPress itself is a fork of b2/cafelog**. But with the Classic Editor plugin existing, and the many opportunities opened up by Gutenberg, I doubt there will be a need for a fork.

I think Gutenberg will end up being one of the best things to ever happen to WordPress, and I really am excited to see it get merged into core because of all the doors it will open and the long-term benefits that it will bring.

**Comment by pento** [comment] 2018-07-23 04:56
Thank you for the discussion, everyone.

The current plan for Gutenberg is to optimise for the majority of users to be able to use it from day 1, whilst providing fall backs to the Classic Editor for more highly customised sites.

For sites that will not work with Gutenberg in the near future, I would strongly recommend installing the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/), which will ensure that your editing experience remains the same, even after upgrading to WordPress 5.0. If you require a more customisable way to opt-out of the block editor, [Gutenberg Ramp](https://wordpress.org/plugins/gutenberg-ramp/) provides all sorts of options to only allow Gutenberg in particular circumstances.

**Closed by pento** 2018-07-23 04:56 UTC

**Comment by JimBTek** [comment] 2018-08-14 10:42
I will say that now I have to check all my websites and install this plugin. It would have been a more friendly / responsible approach to enable Gutenberg by default only in clean 5.0+ installs, and any install that was upgraded to 5.0+ would receive the same code, but have Gutenberg disabled by default, while nudging the users to adopt it.
