### ISSUE TITLE
Adding tags not working consistently

### ISSUE THREAD

**Issue by commorancy** [WordPress/gutenberg#10240] opened 2018-09-28 22:56 UTC
**Describe the bug**
When adding new tags, the tag addition is inconsistent. Sometimes it adds the tag in the grey oval. Sometimes it does nothing. Some times it adds the tag and leaves the word immediately after. When you try to type a new tag, the previous tag disappears. If you type the previous tag again after it disappears, the next time it sticks. Basically, you have to type the tag several times in a row to finally get the tag to stick.

**To Reproduce**
1. Type a new tag name and press enter
2. Wait to see what happens
3. Try typing a new tag after that one and see what happens
4. Sometimes it works, sometimes it fails, sometimes it wipes out the tag

**Expected behavior**
Consistently add a new tag upon typing and pressing return

**Screenshots**
Getting a screenshot of this problem is not easily possible.

**Desktop (please complete the following information):**
 - OS: MacOS X High Sierra
 - Browser: Firefox Quantum
 - Version: 61

**Smartphone (please complete the following information):**
 - Device: _Untested_

**Additional context**
- How do I find the version of Gutenberg?

**Comment by designsimply** [comment] 2018-10-01 22:05
Closing as a duplicate of #9971. Thank you for the report!

**Closed by designsimply** 2018-10-01 22:05 UTC
Labels: Needs Testing, [Component] Post Settings, [Type] Bug
