### ISSUE TITLE
Button with alignment and width - not work as expected.

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/gutenberg#44385] opened 2022-09-22 17:18 UTC
### Description

I can able to reproduce this issue with many wordpress themes so this is common issue.

### Step-by-step reproduction instructions

1. Choose button block.
2. Give button width 75% or 50% etc.
3. Give alignment to button.
You can able to see that button is not taking any width if we choose alignment.

### Screenshots, screen recording, code snippet

I have attached the video recording for better understanding.
Video URL :- [https://share.cleanshot.com/VJnu2ZcAM6wMhrbukNQG](url)

### Environment info

- wordpress version 6.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-10-12 23:35
Hey there @NidhiDhandhukiya74! Thanks for opening this issue and pursuing a PR to address the same. This seems to be a duplicate of https://github.com/WordPress/gutenberg/issues/39937. I'm going to close this out as a result and encourage you to share your findings on that prior issue. If I'm off-based, just let me know too and I'm happy to reopen :)

**Comment by annezazu** [comment] 2022-10-12 23:36
Just found this issue too! https://github.com/WordPress/gutenberg/issues/44614

**Closed as completed by annezazu** 2022-10-12 23:35 UTC
