### ISSUE TITLE
Unable to insert Patterns using Safari by drag and dropping them

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#36523] opened 2021-11-16 15:19 UTC
### Description

Inserting a pattern by drag and dropping it from the sidebar inserter doesn't work in Safari.

I was able to insert patterns this way using both Firefox and Chrome on a mac.

### Step-by-step reproduction instructions

Using Safari:

1. Go to the Site Editor.
2. Open the block inserter from the top bar.
3. Open the Patterns tab bar.
4. Try to drag a Pattern into the canvas.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4933/142012599-588bc4a0-70fb-46c8-85d8-b2276e342886.mp4

### Environment info

- WordPress 5.8.2, Gutenberg 11.9.0, TT1 Blocks.
- Mac with bigSur 11.6
- Safari 15.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jorgecontreras** [comment] 2021-11-19 01:51
I would like to work on a fix for this bug!

**Comment by noisysocks** [comment] 2021-12-01 22:11
@jorgecontreras: How did you go with a fix? Could you please open a PR?

**Comment by jorgecontreras** [comment] 2021-12-01 22:37
hi @noisysocks! I have just created a PR, please let me know your thoughts: https://github.com/WordPress/gutenberg/pull/37308

**Comment by Mamaduka** [comment] 2022-01-05 05:45
I'm removing this issue from WP 5.9 project board since RC1 was released last night.

Let's try and land a fix for this in a minor release.

**Comment by TimBroddin** [comment] 2022-11-10 00:18
It seems like this is fixed in Safari 16.1 (I can't reproduce it).

**Comment by youknowriad** [comment] 2023-02-24 13:05
Yeah I do remember fixing this issue.

**Closed as completed by youknowriad** 2023-02-24 13:05 UTC
Labels: [Type] Bug, [Feature] Patterns, [Feature] Site Editor
