### ISSUE TITLE
Change a Post from Publish to Draft

### ISSUE THREAD

**Issue by wpmark** [WordPress/gutenberg#3711] opened 2017-11-29 09:05 UTC
## Issue Overview

There does not appear to be a way to change a post from being "published" back to being "draft" from the new post editor screen.

## Steps to Reproduce (for bugs)

1. Write a post
2. Publish post
3. Try and find a way on the new post editor screen to turn this post to draft

## Expected Behavior

Surely there should be a method to save a post back to draft after it was published. The only way I can do this is through the post listing screen quick edit.

**Comment by mtias** [comment] 2017-11-29 12:19
Closing as duplicate of #1452.

**Closed by mtias** 2017-11-29 12:19 UTC
