### ISSUE TITLE
Moving a block with the select tool doesn't work with Chromium (Chrome?)

### ISSUE THREAD

**Issue by jaredyork** [WordPress/gutenberg#37809] opened 2022-01-09 17:46 UTC
### Description

Attempting to move a block using the select tool in the editor doesn't work when using the handle when using Chromium.  I'm unable to confirm if it affects Chrome.  It does behave as expected with Firefox.  With Firefox, the line appears showing where you're dropping a block, then when you drop it, it does in-fact move to where you dropped it as expected.  I tested this with both WordPress 5.8.3, 5.9 RC1, and 5.8.3 with the Gutenberg plugin activated -- the issue occurs with all of these.

![](https://i.imgur.com/707VgVI.png)

The List View is also affected, the same issue happens when moving blocks in the list view.  I'm happy to start a second issue if that's preferred.

### Step-by-step reproduction instructions

1. Use the select tool by going up the _Tools_ button in the bar at the top of the editor.
2. Click the block you wish to move.  The black tool ribbon will appear.
3. Click and drag the handle (six white dots) to attempt to drag the block to a new location.

### Screenshots, screen recording, code snippet

Here is what's happening with Chromium (and Chrome?):
![](https://i.imgur.com/BIjhVy2.gif)

Here is the expected behavior with Firefox:
![](https://i.imgur.com/RgZlRtR.gif)

### Environment info

I tested this with WordPress 5.8.3 and 5.9 RC1, and 5.8.3 with Gutenberg plugin activated and the issue occurs with all of these.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jaredyork** [comment] 2022-01-09 18:03
The List View is also affected, the same issue happens when moving blocks in the list view.

**Comment by annezazu** [comment] 2022-01-10 18:52
I can't replicate this with Chrome using both 5.9 RC1 without GB and with GB 12.3.1.

https://user-images.githubusercontent.com/26996883/148822250-cb804fbf-3655-4282-a0c8-886cf3617875.mov

Going to add this as a browser issue and leave as needs testing!

**Comment by JustinyAhin** [comment] 2022-01-14 14:02
I've tried reproducing this. It works as expected on Chrome.

Same thing for Chromium. @jaredyork could you maybe add more testing instructions.

Here are the details for the Chromium test.


I was able to reproduce the issue, but it looks like it happens in very specific conditions.

## Environment
- OS: macOS BigSur 12.0
- Browser: Chromium
- WordPress 5.9-RC2
- Plugins: WordPress Beta Tester
- Theme: TT2

## Recording
https://cln.sh/YcwlxV

**Comment by ndiego** [comment] 2022-09-13 14:14
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.

**Closed as completed by ndiego** 2022-09-13 14:14 UTC
Labels: Browser Issues, Needs Testing
