### ISSUE TITLE
Global Styles: Cover block with vh height units expands indefinitely when browsing styles.

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#49461] opened 2023-03-30 04:49 UTC
### Step-by-step reproduction instructions
1. I run this test on a site with TT3.
2. Open up the site editor and edit the home template.
3. Add a cover block, and set the minimum height of cover to 100vh.
4. Open global styles tab, then navigate to Browse Styles.
5. In the zoomed out site preview the Cover block starts expanding.
6. I tried changing the Cover block height to use different units, and the issue was only visible when using `vh`. I also tried using a different value, for example `50vh` and the issue persisted.

### Screenshots, screen recording, code snippet
https://www.dropbox.com/s/4vhb0aptwdc2co7/cover_block_global_styles_bug.mov?dl=0

### Environment info
* WordPress 6.2, Gutenberg plugin 15.4
* Theme: TT3 v. 1.1
* macOS 13.2.1 / Firefox 111.0

**Comment by Mamaduka** [comment] 2023-03-30 06:10
Thanks for contributing, @alaczek!

I believe this is a duplicate of #49461.

**Closed as not planned by Mamaduka** 2023-03-30 06:10 UTC
Labels: [Status] Duplicate, [Feature] Site Editor
