### ISSUE TITLE
Improve dropping blocks within nested blocks in the List view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#39070] opened 2022-02-24 18:24 UTC
## What problem does this address?
It is difficult to drag and drop blocks precisely within the List view, when nested Group blocks are incorporated into a page. In the current experience, its not possible to drop a block as the last block within a Group block, if a nested Group block exists. 

As you'll see in the recording below, the drop indicator does not follow the block hierarchy, but skips up to the top level block. 

The only way to do this today is to add it above the nested group block, then go leave the List view and use the block up/down arrows, or drag/drop it around the editor (but that get's tricky in the context of nested blocks as well). 

## What is your proposed solution?
I'd expect to be able to confidently drag/drop a block at all levels of block hierarchy. 

#### Attempting to drop a block at the bottom of a parent group block

https://user-images.githubusercontent.com/1813435/155583396-d20bd450-f9a7-4b91-ad15-7c66067ee327.mp4

**Comment by talldan** [comment] 2022-02-25 06:03
Thanks for reporting. I'll close this one as a duplicate of https://github.com/WordPress/gutenberg/issues/33678, which tries to describe the same issue (though it's hard to describe 😄 ).

I may grab your video and add to the description if that's ok!

**Closed as completed by talldan** 2022-02-25 06:03 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Feature] List View
