### ISSUE TITLE
Unrelated plugins break "Media Library" button on Image Block

### ISSUE THREAD

**Issue by ChrisBAshton** [WordPress/gutenberg#13084] opened 2018-12-23 16:00 UTC
**Describe the bug**
Activating a plugin that has nothing to do with Images, can break the Image block behaviour, i.e. the "Media Library" button stops appearing as an option.

|Image block without create-guten-block|Image block WITH create-guten-block|
|----------------------------------------|--------------------------------------|
|<img width="476" alt="screen shot 2018-12-23 at 14 56 31" src="https://user-images.githubusercontent.com/5111927/50384881-61c1f000-06c3-11e9-8472-04e2a01d72b1.png">|<img width="467" alt="screen shot 2018-12-23 at 14 56 51" src="https://user-images.githubusercontent.com/5111927/50384883-65ee0d80-06c3-11e9-92b2-08c669302cb5.png">|

I [raised this as an issue in create-guten-block itself](https://github.com/ahmadawais/create-guten-block/issues/128), but the project maintainer thinks it's more likely to be an issue with Gutenberg so I'm raising it here instead.

**To Reproduce**

1. Install [this minimal MCVE plugin](https://github.com/ChrisBAshton/create-guten-block-debug) ([definition](https://stackoverflow.com/help/mcve)) via `git clone`, `npm install`, `npm start` and deploy the `dist/` & `plugin.php` to a subdir within `plugins/`. 
2. Do not activate it yet.
3. Try adding an Image block to any Post - you'll see the Media Library button.
4. Activate the plugin, and attempt step 3. again. The button is missing.

**Expected behavior**
The button should work regardless of the external plugin (which has nothing to do with images)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version 71

I'm using Gutenberg v5.0.2.

**Additional context**
- This has [happened before as a result of Advanced Custom Fields](https://github.com/WordPress/gutenberg/issues/7523) plugin, so appears to be quite brittle functionality. To confirm, I don't have ACF (or any other plugins) installed.

**Possible cause**
I've narrowed it down to the plugin's main PHP file:

```php
// Hook: Editor assets.
add_action( 'enqueue_block_editor_assets', 'action_block_cgb_editor_assets' );

function action_block_cgb_editor_assets() {
	wp_enqueue_script(
		'action_block-cgb-block-js',
		plugin_dir_url( __FILE__ ) . '/dist/blocks.build.js',
                // THIS LINE - try passing an empty array and things work again! :
		array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-editor' ), // Dependencies
		true // enqueue script in footer
	);
}
```

If I remove the dependencies array and pass a empty `array()` instead, the Image Block works as normal.

**Comment by draganescu** [comment] 2019-08-08 06:21
Hi @ChrisBAshton and thank you for your very well done ticket (especially for providing a MCVE). 

We have tested during our [Core Edior New Contributor and Triage meeting](https://wordpress.slack.com/archives/C02QB2JS7/p1565244281298300) and fortunately it worked for the testers.

What this means is that maybe the problem was fixed in the current version of Gutenberg and WordPress or that the problem is not related to code in default distribution.

I will close this as "works for me" but feel free to comment with new details or reopen if the problem reappears.

**Closed by draganescu** 2019-08-08 06:21 UTC
Labels: Needs Testing
