### ISSUE TITLE
Global Styles: Allow to define hover color for buttons

### ISSUE THREAD

**Issue by nielslange** [WordPress/gutenberg#49608] opened 2023-04-05 12:54 UTC
## Problem

Currently, Global Styles allow defining both the default and the hover color for links. For buttons, however, only the default color can be defined. It’s not possible to define the hover color.

## Steps to reproduce

1. Open the Global Styles settings via `Appearance » Editor`.
2. Go to `Styles » Colors » Links`.
3. Verify that link colors can have both a default and a hover color.
4. Go to `Styles » Colors » Buttons`.
5. Verify that button colors can only have a default, but not a hover color.

## Screenshots

<table>
<tr>
<td valign="top">Link » Default:
<br><br>
<img width="277" alt="Screenshot 2023-03-27 at 16 31 47" src="https://user-images.githubusercontent.com/3323310/230086035-6d4d3b86-18d1-4451-9fdf-9a53ce7541c2.png">
</td>
<td valign="top">Link » Hover:
<br><br>
<img width="274" alt="Screenshot 2023-03-27 at 16 31 55" src="https://user-images.githubusercontent.com/3323310/230086033-020bf45b-0541-4302-82d7-105552b22d80.png">
</td>
<td valign="top">Button:
<br><br>
<img width="275" alt="Screenshot 2023-03-27 at 16 32 04" src="https://user-images.githubusercontent.com/3323310/230086016-3534b2df-6fe0-4557-b166-fe9955465b5f.png">
</td>
</tr>
</table>

## Benefits

1. **Improved usability**: Changing the hover color provides visual feedback to users when they interact with buttons, making it easier for them to understand which element is active and clickable.
2. **Enhanced accessibility**: A clearly defined hover color can make the interface more accessible for people with visual impairments or color blindness, as it helps to differentiate between interactive and non-interactive elements.
3. **Consistent branding**: Customizing the hover color of buttons to match your brand's color scheme contributes to a consistent and cohesive design, which can improve users' perception of your product or website.
4. **Increased engagement**: An engaging and interactive user interface, which includes hover effects, can encourage users to explore and interact with your content, potentially increasing conversion rates or user retention.
5. **Aesthetic appeal**: A well-designed hover effect can make your user interface more visually appealing and professional, creating a positive first impression for users.
6. **Reduced user errors**: By providing clear visual cues, a defined hover color can help users avoid clicking the wrong button or misunderstanding the interface, reducing the likelihood of errors.
7. **Increased user satisfaction**: A user-friendly interface that incorporates hover effects can lead to increased user satisfaction and a more enjoyable overall experience.
8. **Compliance with design standards**: Following established web design standards, including the use of hover effects, ensures that your website or application meets the expectations of most users, leading to a better overall experience.

**Comment by kathrynwp** [comment] 2023-04-05 15:16
Great idea, but I think this is a duplicate of #4543 - closing in favour of the older one.

**Closed as not planned by kathrynwp** 2023-04-05 15:16 UTC
Labels: [Type] Enhancement, [Status] Duplicate, [Block] Buttons

**Comment by nielslange** [comment] 2023-04-05 16:56
Thanks for closing this one, @kathrynwp. I was looking for an existing issue, but couldn't find #4543. 🙈
