### ISSUE TITLE
You can no longer use unregisterBlockType() with core blocks

### ISSUE THREAD

**Issue by sheepzilla** [WordPress/gutenberg#4699] opened 2018-01-26 19:47 UTC
## Issue Overview
After the update to 2.1.0 the sample code to unregister core blocks taken from the Gutenberg handbook no longer works as expected. 
https://wordpress.org/gutenberg/handbook/extensibility/#using-a-whitelist

It looks like the initial registering of the blocks has been moved in the following commit: 
https://github.com/WordPress/gutenberg/commit/e694f6a99b7ce01bb3586798e1af6c662a7a4895

Can the docs be updated to reflect this change? 

## Steps to Reproduce (for bugs)

1. Add whitelist code from https://wordpress.org/gutenberg/handbook/extensibility/#using-a-whitelist to a theme or plugin and load in the admin
2. Observe that while editing a page all blocks are still available.

## Expected Behavior

Expected behaviour would be for only the specified blocks to be available.
## Current Behavior

All blocks available

**Comment by taija** [comment] 2018-01-30 16:49
Also seeing this issue. Any workarounds?

**Comment by gziolo** [comment] 2018-01-31 16:38
I might break something with the recent refactoring. I will debug later this week and hopefully push a patch. Aplogies for temporary inconvenience :)

**Comment by gziolo** [comment] 2018-02-05 11:27
This is the same issue as described and explained by @youknowriad in #4848. We started exploring different ways of registering blocks to come up with a much reliable solution. You can see what has been proposed already in #2751. Code explorations are done in #4841. So the idea would be to have full control over which blocks are going to be registered on PHP side. 

I will close this one as a duplicate of #4848, but I would expect API change really soon.

**Closed by gziolo** 2018-02-05 11:27 UTC
Labels: Blocks, Extensibility, Priority High, [Type] Bug
