### ISSUE TITLE
Deleting empty paragraph also deletes proceeding block

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#19224] opened 2019-12-18 19:37 UTC
### Problem 

If you focus on an empty paragraph and hit `delete`, it's deleted, but so it the block that follows it.

### Steps to Reproduce

1. Paste the below markup into the Code editor, and switch to Visual
1. Focus on empty paragraph, hit `delete`

```html
<!-- wp:paragraph -->
<p>foo bar</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p><span style="font-size: inherit;">bar foo</span></p><cite>quix</cite></blockquote>
<!-- /wp:quote -->

```

### Expected

Only the empty paragraph should be deleted.

### Actual

The following block is also deleted.

### Desktop
 - Chrome  78.0.3904.108
 - WP 5.3.1

**Comment by talldan** [comment] 2019-12-19 04:08
Hey @iandunn, I was able to reproduce slightly different results—instead of being deleted the blockquote is converted into separate paragraphs, which still is a bug.

This was testing against `master` (Chrome, Mac OS) so that might be the reason for the different behaviour.

![paragraph-delete](https://user-images.githubusercontent.com/677833/71144178-16034180-2258-11ea-8a1a-2c0ba9a8237e.gif)

**Comment by ntsekouras** [comment] 2020-09-23 12:27
I'm closing this as was fixed here: https://github.com/WordPress/gutenberg/pull/8735

**Closed by ntsekouras** 2020-09-23 12:27 UTC
Labels: [Feature] Writing Flow, [Type] Bug
