### ISSUE TITLE
Add individual link to gallery item

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#14797] opened 2019-04-03 15:04 UTC
From time to time the need comes up to individually link a 
gallery item to some specific page (and add a custom text below).

It is nice that now individual caption with individual link (inline) can be added.
But when all the other gallery items link to their media image (e.g. for a lightbox),
then also the gallery items that contain the individual link still link to the media image, 
hence the user has to click/touch exactly on the individual caption, 
otherwise the gallery item link to the media image file is selected.

**Comment by amielucha** [comment] 2019-04-07 11:43
What you are looking for can be done using [Gallery Custom Links](https://wordpress.org/plugins/gallery-custom-links/) plugin.

**Comment by strarsis** [comment] 2019-04-07 14:48
@amielucha: Ideally this should be integrated into Gutenberg gallery block.

**Comment by justintadlock** [comment] 2019-04-19 19:02
This feature would also make gallery images consistent with regular images, which allow you to enter a custom URL.  The addition of this would definitely make galleries far more versatile.

I have a layout right now where I'm having to use the Columns block and manually enter individual Image blocks into the columns with custom URLs to get this behavior.

**Comment by dionysous** [comment] 2019-08-26 14:03
## Why the Custom URL setting if useful for the Gallery Block:
The _Gallery Custom Links_ plugin, @amielucha mentioned, adds two fields on the images in the Media Library (Link URL and Link Target). What if one and the same image is used in two different galleries? And you want to have two individual links in both Galleries on the same image? With this solution, it will break, therefore, in my opinion, the custom Link/URL values should be saved in the Gallery Block itself, which is cleaner and more elegant and doesn't lead to the described problem.

I find it very useful to have a **Custom URL setting** in the **GalleryImage component**. I can't let my customers use the core Gallery Block, because it lacks this feature compared to the core Image Block.

## The Core Image Block already has a good implementation:

![Screencapture of Custom URL settings in the image block's controls](https://user-images.githubusercontent.com/12687777/63695500-1e52ef00-c819-11e9-9b9f-3d5256fc787a.gif)

## The Core Gallery Block & GalleryImage don't have the needed option:

![Screencapture of kink settings in the gallery block's controls](https://user-images.githubusercontent.com/12687777/63695882-eac49480-c819-11e9-94a0-5a95b86c00b4.gif)

Why are the **Image and GalleryImage settings** so **inconsistent**?

**Comment by talldan** [comment] 2019-10-08 23:11
This looks like a duplicate of #10057. Also see https://github.com/WordPress/gutenberg/issues/11436 which seems to be proposing using the Image block as a nested block of the gallery, which would solve this issue.

**Closed by talldan** 2019-10-08 23:11 UTC
Labels: [Block] Gallery
