### ISSUE TITLE
Query loop settings miss taxonomies from custom post type

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#38347] opened 2022-01-29 20:36 UTC
### Description

When configuring a query loop, I can choose just to display posts from specific category/ies

so this

![Screenshot from 2022-01-29 20-29-55](https://user-images.githubusercontent.com/2853040/151676651-5f5671eb-c201-4054-be1f-5936f40bb3ba.png)

then this

![Screenshot from 2022-01-29 20-33-22](https://user-images.githubusercontent.com/2853040/151676678-f538e65a-9935-4f3e-ac71-1394e2c3616b.png)

However, for custom post types, only Author and keyword are visible and and the equivalent of tags and categories (taxonomies) are missing

![Screenshot from 2022-01-29 20-29-13](https://user-images.githubusercontent.com/2853040/151676647-423a6c4d-83e5-4c96-a0e1-89837ea5122f.png)
![Screenshot from 2022-01-29 20-29-31](https://user-images.githubusercontent.com/2853040/151676693-0a1cb891-a2b4-4fab-bce5-7323a81b331a.png)

### Step-by-step reproduction instructions

Set up custom post type 
Set up tag or category for it
Add a query loop to page/template and set it up from scratch so settings can be edited
Select the custom post type in post type
See that the tag or category no longer show in filters section

### Environment info

WordPress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ntsekouras** [comment] 2022-02-03 09:06
👋  Thanks for reporting this!

This wasn't supported until yesterday's release of GB `12.5` (https://github.com/WordPress/gutenberg/pull/38063). It's not in WordPress `5.9`. I'm saying this because you have in the issue's `Environment info` the WP version only. 

Have you tried with GB 12.5 and the problem is still there?

**Comment by gingerling** [comment] 2022-02-07 15:34
Hi, so I activated the Guttenberg plugin (was deactivated) and updated to Version 12.5.3 and have checked, this issue is still present for me.

**Comment by gingerling** [comment] 2022-02-07 15:37
No, wait suddenly started working!! Okay, so anyone with this bug, you need to install the Guttenberg plugin (this is as well as having guttenberg block editor enabled in general, it's more up to date). Then make sure that plugin dosen't need any updates. It should now work!

**Comment by ntsekouras** [comment] 2022-02-07 15:49
I'm going to close this one then. Thanks again for reporting this @gingerling!

**Closed as completed by ntsekouras** 2022-02-07 15:49 UTC
Labels: [Type] Bug, [Block] Query Loop
