### ISSUE TITLE
When editing tables, it is a mess

### ISSUE THREAD

**Issue by lobaluna** [WordPress/gutenberg#9327] opened 2018-08-24 17:18 UTC
I already had tables in one page. When I try to edit content, the space where I can visualize all the columns is so narrow that I have to use horizontal scrollbars to move between elements ans columns. On the classic editor, this is not an issue.

**Comment by afercia** [comment] 2018-08-26 16:50
I guess the problem is that, while the Classic Editor takes all the available width, the Gutenberg content area has a max-width?

![screen shot 2018-08-26 at 18 48 44](https://user-images.githubusercontent.com/1682452/44630618-d6c52900-a960-11e8-9b66-952d4193e43b.png)

**Comment by talldan** [comment] 2018-09-11 18:30
I've made a PR #9801 which should help matters a small amount. Users will be able to specify a width and height for tables, and I've also slightly improved the handling of overflowing content.

Unfortunately, I don't think there's much more that can be done beyond that—at the moment the table has to fit within a block's editor area. There are some other issues that discuss the width of blocks which I'd defer to:
- https://github.com/WordPress/gutenberg/issues/1483
- https://github.com/WordPress/gutenberg/issues/5650

I've set this issue to close once #9801 is merged, but let me know if you think any more can be done.

**Comment by tellthemachines** [comment] 2020-04-20 04:24
The editor content width is set to be the same as the content width on the front end, as the goal is ultimately to achieve complete identity between the editor and the front end. Any table that is wider than the content area will scroll horizontally, rather than trying to squish all the columns into a narrow window which, for a large table, would make it unusable. 

What isn't working too well is keyboard navigation with the arrow keys: it's impossible to move focus with the left and right arrow keys to a cell that's hidden from view. It's also not possible to navigate table cells vertically with the up/down keys. Issue #14675 is tracking arrow keyboard navigation on the table block, so I am going to close this one and add further information to the one above.

**Closed by tellthemachines** 2020-04-20 04:24 UTC
Labels: [Block] Table, [Feature] Blocks
