### ISSUE TITLE
IE 11: sibling inserter doesn't appear, breaking keyboard navigation

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3408] opened 2017-11-09 14:55 UTC
With IE 11, tabbing from one block to the following block doesn't make the "sibling" inserter button appear. Tabbing again, focus is lost and the tab sequence starts from scratch from the document root.

This makes impossible to tab through blocks, since focus constantly fallbacks to the document root.

Happens also when tabbing from the title to the following block. To reproduce:

![screenshot 105](https://user-images.githubusercontent.com/1682452/32610752-0408f338-c564-11e7-8935-2526960b624a.png)

- 1: click on the title
- 2: press Tab (seems focus goes somewhere and then is lost immediately)
- 3: press Tab: focus starts from scratch from the skip link

Dumping something in the console to check when the relevant functions run:

Chrome macOS: Not sure why they run multiple times after a single Tab press (maybe because it re-renders?)

![screen shot 2017-11-09 at 15 27 40](https://user-images.githubusercontent.com/1682452/32610835-3d49cfe6-c564-11e7-8bb9-86bcba63c4d7.png)

IE 11:

![screenshot 106](https://user-images.githubusercontent.com/1682452/32610874-56b0b116-c564-11e7-8919-35a95635bc6a.png)

`isVisible` is false

**Comment by ephox-mogran** [comment] 2017-11-10 01:47
This is caused by the `onBlur` handler in `SiblingInserter`. The div gets focused, and then immediately focuses the button inside. That fires a `blur` on the div, which calls `hide`. 

Note, this seems to be resolved by just ensuring that the newly focused item (`document.activeElement`) isn't contained by the div before firing `hide`. It seems to work on all browsers from some cursory testing, but if we hit problems, we might need to use the `withFocusOutside` HOC again.

**Comment by ephox-mogran** [comment] 2017-11-10 01:52
Note, that I needed the PR #3415 to even begin debugging this. I'm not sure how you were able to get so far @afercia ! :) My Gutenberg just kept crashing due to the `startsWith` issue.

**Comment by afercia** [comment] 2017-11-10 08:15
> I'm not sure how you were able to get so far

Old-school methods 😬 

I was wondering why there's the need of the wrapper div and the focus management in the first place. Wouldn't be simpler to have the sibling inserter button always rendered and visually hidden? There are simple CSS techniques to visually hide elements and still keep them focusable. On focus, just a className update can reveal the element. Something like the row action links in the WordPress list tables.

**Comment by aduth** [comment] 2017-11-13 15:39
>I was wondering why there's the need of the wrapper div and the focus management in the first place.

Originally this was intended as an optimization to avoid unnecessary DOM nodes, since a between-inserter-per-block could lead to an excessive number of nodes and therefore potential for a performance impact. However, given that as implemented, the Inserter component contains its own logic for rendering only when open and is otherwise limited to a single node, there really may not be need for this after-all and could be simplified.

**Comment by ephox-mogran** [comment] 2017-11-14 23:49
So is this the simplification we want:

- Basic empty DIV that is focusable when it is not focused or visible
- Unwrapped Inserter dropdown button when it is visible / focused

I've also noticed that it seems like moving the mouse can make the inserter button disappear, even when it is focused. I assume that's not desired behaviour?

**Closed** 2017-11-21 18:49 UTC
Labels: Accessibility, [Type] Bug
