### ISSUE TITLE
Nav block: Navigation structure - drag elements to reorder

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#19985] opened 2020-01-31 16:41 UTC
I noticed the sidebar Navigation area.

![Screen Shot 2020-01-31 at 17 38 48](https://user-images.githubusercontent.com/5323259/73556930-a1bfde80-4450-11ea-8287-73537755856e.png)

![Screen Shot 2020-01-31 at 17 40 42](https://user-images.githubusercontent.com/5323259/73557046-d469d700-4450-11ea-95f0-55a07e907083.png)

Here it would be natural to be able to drag the menu items to reorder them.

**Comment by mtias** [comment] 2020-01-31 17:20
Closing as duplicate of #11408.

**Closed by mtias** 2020-01-31 17:20 UTC
