### ISSUE TITLE
Youtube Links & Embeds Not Working: "Updating Failed" error message

### ISSUE THREAD

**Issue by themightymo** [WordPress/gutenberg#5126] opened 2018-02-18 15:49 UTC
## Issue Overview
If I embed or link to Youtube videos, I get an "Updating Failed" error message.

## Steps to Reproduce (for bugs)
1. Link to a Youtube video or use the "Youtube" block to embed a video.
2. Save the post.

## Expected Behavior
The post should save, but it does not.  Instead I get "Updating Failed" error.

WP 4.9.4
Gutenberg 2.2.0

## Current Behavior
Youtube links and embeds make it impossible to save post.

## Screenshots / Video
https://youtu.be/4jT0lKZ_er4

**Comment by youknowriad** [comment] 2018-02-18 16:17
Are you using "CloudFlare", this more likely a duplicate of #2565

**Comment by themightymo** [comment] 2018-02-19 16:49
@youknowriad 
Yes, I am using Cloudflare.  Let's close this issue in favor of the other open issue.

p.s. I was searching the wrong Github field for these issues.  Now I see my error, and I'll do a better job of searching next time.

keep up the great work!

**Closed** 2018-02-19 16:49 UTC
