### ISSUE TITLE
Edit button in Site Editor > Template Parts broken

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#46719] opened 2022-12-21 18:23 UTC
### Description

The number of characters that make up "Template parts" is breaking the "Edit" button in the panel.

### Step-by-step reproduction instructions

1. Go to Site Editor > Template parts
2. See broken Edit button

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/486261/208976626-1a3b018e-ab0e-4fa0-a82e-85fc044f36a5.png)

### Environment info

WordPress 6.1.1, Gutenberg 14.8

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2022-12-23 03:35
I think this issue will have different results than the language. For example, in Japanese, the button text will be wrapped.

Template:

![jp_template](https://user-images.githubusercontent.com/54422211/209265991-bc5024c1-b934-4c5a-8bda-75e402c9aa1a.png)

Template Parts (title not yet translated):

![jp_parts](https://user-images.githubusercontent.com/54422211/209266001-f8058be1-4aa7-4a93-ace9-7c38848cd6e2.png)

**Comment by t-hamano** [comment] 2022-12-23 14:53
Since the Edit button has been moved by #46700, this problem does not appear to reproduce in the latest Gutenberg.

@bgardner 
I would like to close this issue, but if I have missed something, please feel free to comment.

![design](https://user-images.githubusercontent.com/54422211/209355425-a0c891e6-8ebd-4816-aece-1a33b6be9417.png)

![templates](https://user-images.githubusercontent.com/54422211/209355432-53dab8fa-2c25-475f-ac4e-08c827bb7913.png)

![template-parts](https://user-images.githubusercontent.com/54422211/209355449-0b9aea8f-0670-41cd-aa43-0f95162b8207.png)

**Closed as completed by t-hamano** 2022-12-23 14:53 UTC
Labels: [Type] Bug, Needs Design, [Block] Template Part
