### ISSUE TITLE
[Full Site Editing] Block inserter missing patterns as an option

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24630] opened 2020-08-18 18:34 UTC
**Describe the bug**

Just below the navigation block when you enable the FSE experiment, the inserter does not show block patterns as an option. 

**To reproduce**
1. Install Gutenberg and activate.
2. Head to Gutenberg > Experiments > Activate all. 
3. Head to "Site Editor (beta)" 
4. Select the block area below the navigation block and try to add a pattern from the Inserter.
5. Don't see patterns listed.

**Expected behavior**

I expected to find patterns as an option. If I scroll further down and attempt to add patterns in, I'm able to see patterns as an option but, for some reason, just below the navigation block doesn't seem to show options for patterns to be used. 

**Screenshots**

Here's a video: https://cloudup.com/cJWPt0q1r0W

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg installed
If the Gutenberg plugin is installed, which version is it? 8.7.1

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Chrome
- Version: Version 84.0.4147.105

**Comment by carolinan** [comment] 2021-03-24 11:19
I am not able to reproduce this, so I am closing the issue. I suspect that this was an earlier problem with template parts, as "header" is visible in the video when the inserter below the navigation block is selected.

The block patterns are available unless a block with inner blocks -like the navigation block - is selected.

**Closed by carolinan** 2021-03-24 11:19 UTC
Labels: [Feature] Full Site Editing, [Feature] Patterns, [Type] Bug

**Comment by annezazu** [comment] 2021-03-24 16:57
Not able to replicate either anymore! Thanks for looping back.
