### ISSUE TITLE
Default page-template value changed from "default" to ""

### ISSUE THREAD

**Issue by gschoppe** [WordPress/gutenberg#12873] opened 2018-12-14 13:22 UTC
**Describe the bug**
In the classic editor, the page template selection dropdown defaults to the string "default" as a value. On initial post-creation, the value is "", then changes to "default" on save. This provides useful context, as it allows plugins to change the default page template for new posts, in specific contexts, without preventing the user from selecting the theme's default template, if they prefer.

Gutenberg presents the default value as "", both before and after save, thereby leaving plugins with no way of detecting whether the value has been set by the user or not.

**To Reproduce**
1. inspect the "page template" select box in Classic Editor.
2. note that the value of the default template option is "default"
3. inspect the "page template" select box in Gutenberg
4. note that the value of the default template option is ""

**Expected behavior**
These two values should match, such that a post edited before a template was created or a new post will have the value "", and a post which was saved with this select box on screen should have the value "default".

**Comment by youknowriad** [comment] 2019-04-22 10:09
Can I ask which theme are you using here, I just tested and can't reproduce personally.

**Comment by youknowriad** [comment] 2019-05-10 18:03
Closing. Let's reopen if we have reproducible steps.

**Closed by youknowriad** 2019-05-10 18:03 UTC
Labels: [Component] Post Settings, [Status] Needs More Info
