### ISSUE TITLE
theme.json CSS rendering styles.elements.link / + :hover

### ISSUE THREAD

**Issue by mleathem** [WordPress/gutenberg#64720] opened 2024-08-22 15:08 UTC
### Description

**theme.json** settings for element link color /hover color are rendered in CSS correctly 
It seems to be impossible to set BOTH the link color and hover color.

the color, or the hover can be set, but not **also** the link and the hover
the rules to which value is taken are definetly mixed up.

Note there are two methods (I have tried various combinations, all fail)
- Link = `styles.elements.link.color.text`
- Link:hover = `styles.elements.link[":hover"].color.text`
and 
- Link = `styles.elements.link.css`
- Link:hover = `styles.elements.link[":hover"].css`

Code sample
` "styles": {
        "elements": {
            "link": {
                "css": "color:var(--wp--custom--link-color)",
                "typography": {
                    "textDecoration": "underline"
                },
                "color": {
                    "text": "var(--wp--custom--link-color)"
                },
                ":hover": {                
                    "color": {
                        "text": "var(--wp--custom--link-color-hover)"
                    }
                }
              }
        },
  `
Aside code:  I set those CSS vars as follows:
`"settings": {
      "custom": {
         "link-color": "#ffcc00",
         "link-color-hover": "#ff0000"
      }
}`

The CSS that gets rendered is as follows*
`:root :where(a:where(:not(.wp-element-button))) {
    color: var(--wp--custom--link-color);
}`
OR for hover
`:root :where(a:where(:not(.wp-element-button)):hover) {
    color: var(--wp--custom--link-color-hover);
}`
but these importantly cannot be rendered simultaneously from the JSON 

elsewhere this CSS styles the link color:
`a:where(:not(.wp-element-button)) {
    color: var(--wp--preset--color--black);
    text-decoration: underline;
}`

---

*(**ASIDE**):  I will not comment further on what a terrible idea such a CSS rule that is : _convoluted-overkill_ ... (see many other issues on that!) - but I am sure that this complexity of the CSS rule contributed to the reason why this rendering is incomplete.

### Step-by-step reproduction instructions

1. use the provided json within the context of theme.json (eg. in an otherwise blank theme)
2. view the frontend (link in body content)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by mleathem** [comment] 2024-08-22 15:16
I attach my **theme.json** (so far) in case there is a related configuration that causes an anomaly 
[theme.json](https://github.com/user-attachments/files/16714057/theme.json)

---

for anyone else...? as a workaround (until there is a fix)
 - I kept the full `element.link` configuration as above and additionally loaded this CSS :
 
`:root :where(a:where(:not(.wp-element-button))):hover {
    color: var(--wp--custom--link-color-hover);
}`

since the rendered CSS manages the standard (non hover) like it works as expected.
(Should also then become redundant should a fix eventually happen  ... leaves me with the overkill CSS rule though ;)  ).

**Comment by t-hamano** [comment] 2024-08-22 15:45
Thanks for the report.

Could you tell me which WordPress version you tested? I was not able to reproduce this problem in WordPress6.6.1.

Here is the theme.json I used for testing:

<details><summary>theme.json</summary>

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"custom": {
			"link-color": "#ffcc00",
			"link-color-hover": "#ff0000"
		}
	},
	"styles": {
		"elements": {
			"link": {
				"typography": {
					"textDecoration": "underline"
				},
				"color": {
					"text": "var(--wp--custom--link-color)"
				},
				":hover": {
					"color": {
						"text": "var(--wp--custom--link-color-hover)"
					}
				}
			}
		}
	}
}
```

</details>

Default link style:

![image](https://github.com/user-attachments/assets/10c277da-175c-470e-ae50-40ce3b418617)

Hovered link style:

![image](https://github.com/user-attachments/assets/4ceb759f-7eea-42e9-b686-c1f161f30bb1)

**Comment by mleathem** [comment] 2024-08-23 05:33
Also 6.6.1 - I tried version2 also (same). So far I have zero plugins activated.  

**Default link style:**
![image](https://github.com/user-attachments/assets/17c42f80-e0be-43af-9572-8d99fbd73700)
**Hovered link style:**
![image](https://github.com/user-attachments/assets/a6f40f26-2d87-4f98-bf13-76b83b942824)

Note: to test I also have removed the **functions.php** , and I even stripped the theme.json dont to only the essentials  - same result!
`{
    "$schema": "https://schemas.wp.org/trunk/theme.json",
    "version": 3,
    "settings": {
        "custom": {
            "link-color": "#ffcc00",
            "link-color-hover": "#ff0000"
        }
    },
    "styles": {
        "elements": {
            "link": {
                "css": "color:var(--wp--custom--link-color)",
                "typography": {
                    "textDecoration": "underline"
                },
                "color": {
                    "text": "var(--wp--custom--link-color)"
                },
                ":hover": {
                    "css": "color:var(--wp--custom--link-color-hover)",
                    "color": {
                        "text": "var(--wp--custom--link-color-hover)"
                    }
                }
            }
        }
    }
}`

If I remove the "css" configuration only the hover style in rendered.
`:root :where(a:where(:not(.wp-element-button)):hover) {
    color: var(--wp--custom--link-color-hover);
}`
default state gets does not get styling from theme.json
`a:where(:not(.wp-element-button)) {
    color: var(--wp--preset--color--black);
    text-decoration: underline;
}`
OR if I remove the `text.color` so it relies on the "css" the hover color is falsely set.
![image](https://github.com/user-attachments/assets/985c7914-95dc-4c0c-827f-f4df527dfe49)

**Comment by mleathem** [comment] 2024-08-23 05:45
One more test (I wondered if somehow it's possible). We can see with this config - the hover state gets set correctly, but then overwriten! default: `css` only - hover: `color.text` only
`"styles": {
    "elements": {
        "link": {
            "css": "color:var(--wp--custom--link-color)",
            "typography": {
                "textDecoration": "underline"
            },
            ":hover": {
                "color": {
                    "text": "var(--wp--custom--link-color-hover)"
                }
            }
        }
    }
}`
![image](https://github.com/user-attachments/assets/84402ae1-f982-413c-8123-81af7c2ecce9)

**Comment by t-hamano** [comment] 2024-08-23 05:49
@mleathem Please try testing the theme.json posted in [this comment](https://github.com/WordPress/gutenberg/issues/64720#issuecomment-2305086884) as is, without adding any CSS properties.

If the same style is applied to both the `css` field and the `color.text` field, unintended conflicts can occur.

**Comment by mleathem** [comment] 2024-08-23 05:54
Righto! thanks (using that theme.json - so notably local schema) - but is still incorrect.
Now the default state doesn't get styling
![image](https://github.com/user-attachments/assets/23f00cdd-99b1-4dfd-9649-80d8b5ff5e6e)
but hover state is correct
![image](https://github.com/user-attachments/assets/5b56626b-0c08-4336-8854-fb54eb18309e)

**Comment by mleathem** [comment] 2024-08-23 06:02
@t-hamano I don't know if there's some kind of magic I dont understand... but I looked for the local schema theme.json file ... I cant find it (local install using Laragon, if that makes a difference )

**Comment by mleathem** [comment] 2024-08-23 06:19
I gave it another go.... using just the CSS for both states... still incorrect
[theme.json](https://github.com/user-attachments/files/16724484/theme.json)
`"link": {
	"css": "color:var(--wp--custom--link-color);text-decoration:underline;",
	":hover": {
		"css": "color:var(--wp--custom--link-color-hover)"
	}
}`
![image](https://github.com/user-attachments/assets/7db24dce-fea7-466e-9a0e-42c36d594067)

**Comment by t-hamano** [comment] 2024-08-23 07:12
```css
a:where(:not(.wp-element-button)){
  color: var(--wp--preset--color--black);
}
```

I'm concerned that this style is being output. As far as I've tried, this style isn't being output. What happens if you switch to the Twenty Twenty-Four theme and update only the theme.json with the code presented in [this comment](https://github.com/WordPress/gutenberg/issues/64720#issuecomment-2305086884)?

Again, please do not use the `css` field to pinpoint the cause.

**Comment by mleathem** [comment] 2024-08-23 14:39
As you suggested: I did **Twenty Twenty-Four** + my relevant config code (as of [this comment](https://github.com/WordPress/gutenberg/issues/64720#issuecomment-2305086884) )
the result is as we would expect (working correctly as expected)
![image](https://github.com/user-attachments/assets/77efa98e-5960-49df-a518-70b91de209f9)

**Comment by mleathem** [comment] 2024-08-23 15:38
What is strange is I can make it clear that in my theme that same CSS rule is being used, just NOT for color
If I add outline to the same link configuration. We can see that outputted in the same CSS rule..
![image](https://github.com/user-attachments/assets/853304df-16af-4c79-b7ad-c1387d51986b)
(note I did change the CSS var actual color to green, -I added :focus, as this is more correct)
eg. config: `"link": {
                "outline": {
                    "color": "var(--wp--custom--link-color)",
                    "width": "0px",
                    "style": "solid"
                },
                "typography": {
                    "textDecoration": "underline"
                },
                "color": {
                    "text": "var(--wp--custom--link-color)"
                },
                ":focus": {
                    "color": {
                        "text": "var(--wp--custom--link-color-hover)"
                    }
                },
                ":hover": {
                    "color": {
                        "text": "var(--wp--custom--link-color-hover)"
                    }
                }
            }`

**Comment by t-hamano** [comment] 2024-08-23 15:46
I can't reproduce this in my environment. Do you have Twenty Twenty-Four activated?

If the issue only occurs with a non-default block theme, it's likely an issue with that theme.

**Comment by mleathem** [comment] 2024-08-26 14:59
This isnt a child theme of  "Twenty Twenty-Four" ... my idea was that I wanted to keep it as "pure" as possible ( _I now regret that, as I can see it's just not possible_ )

Let's leave it at that, thanks for the help, but this bug is too time consuming. I have a hack in place - not very satisfactory, but I can see this going nowhere further fast

**Comment by t-hamano** [comment] 2024-08-27 04:42
So far, everything seems to be working as expected if we define theme.json properly in the default theme, so I would like to close this issue.

If you can provide us with all the code for the theme that is causing the problem, we may be able to figure out if it is a Gutenberg issue or a problem with your theme.

If you can provide the code, feel free to paste the link or code here.

**Closed as not planned by t-hamano** 2024-08-27 04:42 UTC
Labels: [Type] Bug, Global Styles

**Comment by mleathem** [comment] 2024-08-27 13:32
to be honest... it's looking more likely that: abandoning Wordpress seems a better use of my time (shame... but them's the breaks)
