### ISSUE TITLE
Cannot use Alt+Shift+J to set text alignment to justified

### ISSUE THREAD

**Issue by c-ro82** [WordPress/gutenberg#8433] opened 2018-08-03 11:28 UTC
Hi

I write all my texts with justification. Today I've installed the gutenberg-Editor and I had to realize there's no option to format with justification (or am I wrong?). I've tried ALT+SHIFT+J but did not work...

Is there any chance to get the possibility of justification?

Thanks
Chris

**Comment by swissspidy** [comment] 2018-08-03 12:01
Note that there's no justification button in the classic editor since WordPress 4.7, see https://core.trac.wordpress.org/changeset/38932

**Comment by c-ro82** [comment] 2018-08-03 12:03
I know that, but with ALT+SHIFT+J it was possible to do this. With the gutenbergeditor it's not possible to do that...

**Comment by Xarcell** [comment] 2018-08-03 13:39
I write with justification as well. Too bad this feature isn't there. It appears Gutenberg is making things worse instead of better.

**Comment by SuperGeniusZeb** [comment] 2018-08-03 13:51
@c-ro82 @Xarcell 

Notably, you can still manually use justification alignment by using the <kbd><samp>Edit as HTML</samp</kbd> to add it in manually, or by using a custom CSS class on the blocks you want to use it on.

![image](https://user-images.githubusercontent.com/19592990/43646217-e25f706e-96f9-11e8-9e22-d61374ab04c2.png)
![image](https://user-images.githubusercontent.com/19592990/43646244-fee028aa-96f9-11e8-8b2c-c4e111daaf86.png)

Also notable is that a plugin could add the option back, since Gutenberg is designed to be extended by plugins just like WordPress in general.

Apparently the justification option was removed from WordPress because it was bad for accessibility, was not used much, and was considered bad practice.

That said, perhaps the keyboard shortcut should still work. Pinging @karmatosed about this.

**Comment by c-ro82** [comment] 2018-08-03 14:24
Thanks. I know, that it is possible to use the html-editor and this way is ok, but if you go back to the block-editor, the justification will be removed every time. That‘s really annoying, unfortunately.

**Comment by SuperGeniusZeb** [comment] 2018-08-03 15:17
@c-ro82 It is? Oh, well I think that is a bug. I have just reported it here: #8450.

**Comment by c-ro82** [comment] 2018-08-03 15:59
I used this tag <p align="justify">TEXT</p>
Maybe it‘s wrong?

**Comment by SuperGeniusZeb** [comment] 2018-08-03 16:40
@c-ro82 Yeah, that attribute was deprecated in HTML a long time ago. Since the advent of HTML5, there has been a push to separate document semantic meaning/structure from style and visuals. Text alignment is style, so it belongs in CSS, and not as a dedicated HTML attribute. Therefore, the correct way to have justified text is the following:

`<p style="text-align:justify">TEXT</p>`.

However, despite being allowed by the HTML5 and CSS3 spec, the Paragraph block does not consider this valid, which is why I created #8450.

**Comment by c-ro82** [comment] 2018-08-03 18:03
Thanks Zeb!

**Comment by parnanet** [comment] 2018-08-07 21:20
Removing justification was always a BIG mistake.   Terrible decision, since version 4.7  
I hope developers reconsider that decision .  
Or at least someone come up with another plugin that works with this new editor...  otherwise, I'll go back to the old editor and be  happy.

**Comment by c-ro82** [comment] 2018-08-07 21:35
Again: justification was never removed, just the button was removed.it was possible to use Alt+Shift+J. But with the Gutenbergeditor this option is not working at the moment...

**Comment by c-ro82** [comment] 2018-08-13 11:04
They just released a new Version of Gutenberg and the "HTML/Block-Bug" (not sure that it is a bug) is still there... it's a bit annoying...

**Comment by burnuser** [comment] 2018-11-12 19:29
In Gutenberg 4.3 thankfully inline-formatting is not longer lost if converting a classic block into regular blocks. Only justify is still lost! (And can not be done in Gutenberg!)
Imagine a large site with a lot of justified text ... and the impact of justify-destroying Gutenberg ...

**Comment by fstath** [comment] 2018-11-15 10:20
Reported here as well:
https://en.forums.wordpress.com/topic/how-to-justified-in-new-editor/

**Comment by pedrohgodoys** [comment] 2018-11-23 16:32
I really don't understand why they removed justify buttom. Isn't everybody how knows anything about HTML5 and/or CSS, and that's a big mistake, really. Add this buttom take money? Space? I really can't understand that.

**Comment by iseulde** [comment] 2018-11-26 17:53
Duplicate of #8450.

**Closed by iseulde** 2018-11-26 17:53 UTC
Labels: Needs Decision, [Type] Enhancement
