### ISSUE TITLE
New Template Editor missing in WP 5.8

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#33647] opened 2021-07-23 11:52 UTC
Hey,

the new template editor is landed in the new WP 5.8 release. [https://make.wordpress.org/core/2021/06/16/introducing-the-template-editor-in-wordpress-5-8/](https://make.wordpress.org/core/2021/06/16/introducing-the-template-editor-in-wordpress-5-8/).

But the template editor is not included if I use the following to opt-in:

`add_theme_support( 'block-templates' );`

Only if the gutenberg plugin is additionally activated, I can see the new menu items at "Appearance > Templates / Temlate Parts".

I do not work with FSE and without the theme.json.

Is there something I doing wrong or is this a bug?

**Comment by getdave** [comment] 2021-07-23 12:26
Hi @CreativeDive. Thanks for your report, but I can confirm this feature is working as specified in the docs you referenced. 

https://user-images.githubusercontent.com/444434/126780975-fee18bb0-c23c-400d-bbc9-573239f9b52f.mov

Have you tried using another Theme and/or a clean install of WordPress? Unfortunately this Issue doesn't seem to have followed the default bug reporting template provided in this repository so it's missing a lot of information about your setup. This makes it quite difficult for me to verify.

That said, I'm pretty confidence the feature is working as intended.

I would always recommend that if you come across potential problems such as these, that you confirm on a fresh install of the latest WordPress. As I'm sure you know it's very easy for Themes or Plugins to cause problems and so it's always best to check.

I'm going to close this one out.

**Comment by getdave** [comment] 2021-07-23 12:26
Whoops! Forgot to close it 🤦

**Closed as completed by getdave** 2021-07-23 12:26 UTC

**Comment by CreativeDive** [comment] 2021-07-23 12:59
@getdave Thanks for the feedback. My issue is more related to the missing menu items on the left admin menu at "Appearance > Templates / Template Parts".

If Gutenberg is installed this menu items are visible all the time.

With WP 5.8. and deactivated Gutenberg plugin, this menu items are missing. Also if I use the "Twenty Twenty One" theme.

Is that an expected behavior?

**Comment by bph** [comment] 2021-07-23 13:22
@Creativedive in 5.8 the template editor was only added to the sidebar of the block editor when working on the page or a post screen. It took me a while to 'see' it, too.

**Comment by CreativeDive** [comment] 2021-07-23 14:12
@bph thanks for confirming this. Perhaps it should be clarified whether it makes sense to make the templates menu item visible for WordPress by default? For now it's a missing page to manage all the created templates.

**Comment by bph** [comment] 2021-07-23 21:28
It will all come with the next iteration to core in 5.9. The template managing a screens and menus haven't been tested thoroughly yet - that's why their are only available in the plugin.
