### ISSUE TITLE
SpacingSizesControl: Duplicate slug when Twenty Twenty-Four theme is enabled

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#55276] opened 2023-10-11 16:33 UTC
### Description

In the latest Gutenberg, slugs appear to be duplicated in padding, margins, blockGap, etc. where `SpacingSizesContrl` components are used. For TwentyTwenty-Four, the following labels will appear in the dropdown:

- Default
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 1
- 2
- 3
- 4
- 5
- 6

As a result, it is rendered as a Select box rather than a slider, probably because it has exceeded the variation threshold for displaying as a slider.

At the same time, there is no proper margin between the select boxes.

This issue did not occur on WordPress (Beta-3) with Gutenberg disabled. Furthermore, it does not occur with themes such as TT3, TT2.

### Step-by-step reproduction instructions

- Activate the latest Gutenberg plugin.
- Enable the Twenty Twenty-Four theme.
- Insert some blocks and check the Dimensions panel.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/ee5ebf05-ea92-46bd-afa2-bf7911045982

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2023-10-12 09:51
This is because the TT4 theme adds some custom spacing sizes but does not disable the default spacing scale, so both are merged into the global styles. I have added a [fix PR](https://github.com/WordPress/twentytwentyfour/pull/618) to the TT4 repo for this.

**Comment by luminuu** [comment] 2023-10-12 10:48
I can't reproduce this issue with the freshly released Gutenberg 16.8.0, you're using 16.8.0-rc2 in your video. Could it be it has been fixed before the final release?

**Comment by richtabor** [comment] 2023-10-12 16:43
> I can't reproduce this issue with the freshly released Gutenberg 16.8.0, you're using 16.8.0-rc2 in your video. Could it be it has been fixed before the final release?

I couldn't either, but the PR would be good anyhow https://github.com/WordPress/twentytwentyfour/pull/618.

**Closed as completed** 2023-10-12 16:48 UTC
Labels: [Type] Bug, Global Styles
