### ISSUE TITLE
Accessibility: add Paragraph shortcuts similar to Classic editor

### ISSUE THREAD

**Issue by jessestu** [WordPress/gutenberg#10018] opened 2018-09-18 22:26 UTC
I've been working with a blind user who tested Gutenberg and offered their feedback to me. I'm relaying that here.

The main feature they miss was the keyboard shortcuts for headers like in the Classic Editor (e.g., Alt + Shift + 1). They wrote in Italian and I used Google to translate where they describe this (emphasis mine):

> I tried using the bar presented by composing from the Bulletin a new article, I find paragraphs and so on, inserting blocks, deleting etc .. _[word not translated]_ way to enter the different titles followed or preceded by a paragraph. _I tried to write and then to insert the correct header with the button, but in the preview everything is as a paragraph and I can not find the titles._

I've searched accessibility issues here but did not see this feature specifically requested. There is a shortcut to press `/` on a new block to switch blocks. The first one that comes up is the Heading block. That is good but still not as flexible as the Classic Editor's paragraph shortcuts.

## Possible Solutions

1. Feature-parity with Classic editor where a paragraph block turns into a Heading block
2. A new shortcut that transforms a paragraph block into a header block, but not the full options of header 1, 2, 3, etc. It switches the block to a default Header starting point.
3. Perhaps there could be more control over the accessibility options that happen when using the `/` block-switching shortcut.
4. Cut the Classic editor feature and recommend the `/` block-switching as the best option.

**Describe the solution you'd like**

This user would prefer option 1 above. I like option 2, but I do not use a screen reader.

**Comment by jessestu** [comment] 2018-09-18 22:27
I can't add labels so I did not add the `accessibility` label.

**Comment by pento** [comment] 2018-09-19 05:18
Thank you for the feature request, @jessestu!

I'm going to close this issue as a duplicate of #7438, which has a discussion of various options for keyboard shortcuts there. Please follow along and join in the discussion, too! 🙂

**Closed by pento** 2018-09-19 05:18 UTC
