### ISSUE TITLE
Issue with editing links

### ISSUE THREAD

**Issue by commandrea** [WordPress/gutenberg#8463] opened 2018-08-03 18:57 UTC
After using the editor to link text, the pop up link box stays open and the cursor returns to the top of the post/page instead of remaining where the edit was made. 

**To Reproduce**
 Highlight text, click link icon, add link, hit enter. Cursor/page moves to the top of the document, link box stays open until page is refreshed. 

**Expected behavior**
Link box should close and the cursor/page location should stay in place. 
 

**Desktop (please complete the following information):**
 - OS: Mac High Sierra 10.13.14
 - Browser Chrome 
 - Version 68

Gutenberg Version 3.4.0

**Comment by oscarcarrillou** [comment] 2018-08-03 19:13
Yes, it happened to me also. 
OS Windows 10
Browser: Mozilla Firefox

**Comment by ltbennight** [comment] 2018-08-03 20:31
Yeah, I've had this happen. It also doesn't always add the link, so I've been doing most of them manually.

OS: Sierra/Windows 10
Browser: Safari, Chrome
Multiple versions, including the most recent

**Comment by designsimply** [comment] 2018-08-03 22:01
Good find! I tested and found some slightly different behavior. In my case, I couldn't get the link button to work at all if I switched to "Fix Toolbar to Top" _during the same session_ where I try to add a link. 

Are you using a fixed toolbar by chance?

**Video:** [1m55s](https://cloudup.com/cXPvsYG-ZTn)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14112&action=edit&revision=14122 running WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome 67.0.3396.99 on macOS 10.13.6.</sup>

**Comment by abwdvm** [comment] 2018-08-04 15:26
No errors.  Tried it several times (1st step second etc).  Looks to me like it works correctly.

**Comment by arunsathiya** [comment] 2018-08-04 16:00
I tested this as well, and I wasn't able to see the same behaviour that OP @commandrea had mentioned.

I noticed something different instead after linking a text. Here is what I did and what I noticed:

- Added a hyperlink to a text
- Clicked on another word and clicked on the link button
- Enabled `Fix toolbar to top` mode
- Clicked on that word again to notice that the link popup was still there. (Is this expected?)
- Clicked on the link button again, while the word was highlighted already.
- Clicked outside of the text (meaning, disabled the text selection/highlight) 
- Double-clicked on the text again, to notice that a link popup shows up with a link that was added to the last word/text.

Noting that the link was not actually inserted to the second word/text, but the link popup is confusing by having the last link.

Hoping I am making sense here. :) Adding GIF for clarity.  

![hyperlink shown on new text selection when not in reality it s not hyperlinked](https://user-images.githubusercontent.com/18581859/43678238-41fcd640-982d-11e8-862b-9eecce52d69f.gif)

The original video is available here. http://cld.wthms.co/dRTmAF

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome 67.0.3396.99 on macOS 10.13.6

**Comment by arunsathiya** [comment] 2018-08-04 16:02
Additionally, to note, I had to click twice on each text to highlight it. You can notice that on the GIF or the video. Unsure if this has happened in the past, but if this is a new bug, I am happy to log it as a fresh issue. 

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome 67.0.3396.99 on macOS 10.13.6

**Comment by designsimply** [comment] 2018-09-10 18:30
@arunsathiya, thank you for testing! 

> Clicked on that word again to notice that the link popup was still there. (Is this expected?)
I think this might be the same as the issue reported in #7992.

> Additionally, to note, I had to click twice on each text to highlight it.
I tested just now with WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 using Chrome 68.0.3440.106 on macOS 10.13.6 couldn't reproduce the issue you mentioned about needing to double click a word two times in order to highlight it. If you are still seeing that problem with the latest version of Gutenberg and it's annoying, you could report it and we could try to get more eyes on it for testing.

**Comment by mtias** [comment] 2018-11-12 03:46
Closing this as seems resolved. Please, reopen if you can reproduce again.

**Closed by mtias** 2018-11-12 03:46 UTC
Labels: Writing Flow, [Type] Bug

**Comment by alane019** [comment] 2019-02-12 19:12
This is not fixed.
