### ISSUE TITLE
Cover Block allow insert image via URL

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#16350] opened 2019-06-28 14:30 UTC
**Is your feature request related to a problem? Please describe.**
The image block allows adding images via a URL. It would be helpful to allow this also for Cover image. 
This is a screenshot from the newly released Gutenberg Playground.  
![Screen Shot 2019-06-28 at 9 57 45 AM](https://user-images.githubusercontent.com/39980/60349384-7f805280-998f-11e9-8247-b1f133145c02.png)

There is not access to upload images but to demo the Cover block here it would be necessary, to have a way to add an image via URL. 

**Describe the solution you'd like**
Similar to the image placeholder offering three buttons and if access to the media library or to upload is not available hide those buttons and only leave the "Insert from URL" button
![Screen Shot 2019-06-28 at 10 27 00 AM](https://user-images.githubusercontent.com/39980/60349405-88712400-998f-11e9-9a3d-a341710cb967.png)

Although I describe the need for the "Insert Image via URL" in the context of the Playground site, I can easily imagine that it expands the ease of use for the cover block in any implementation context.

**Comment by jorgefilipecosta** [comment] 2019-06-28 15:13
There is already work in progress to fix this issue https://github.com/WordPress/gutenberg/pull/15519 :)

**Comment by bph** [comment] 2019-06-28 19:30
Thanks for flagging this @jorgefilipecosta I'll keep an eye out for this landing in a plugin version:-)

**Comment by talldan** [comment] 2020-07-31 07:31
This seems to be a duplicate of #10853, so closing this in favor of the older issue.

**Closed by talldan** 2020-07-31 07:31 UTC
Labels: Good First Issue, Needs Dev, [Block] Cover, [Type] Enhancement
