### ISSUE TITLE
Image block created with the clipboard not updated properly

### ISSUE THREAD

**Issue by mipon** [WordPress/gutenberg#19004] opened 2019-12-08 17:15 UTC
**Describe the bug**
When pasting an image from the clipboard right after deleting a previous image (which was pasted with the clipboard) from the Upload Media window, the previous image gets inserted. 

**To reproduce**
1. Have two different images opened in graphic software UI to copy & paste.
2. In the Gutenberg screen, paste the first image and see it is uploaded.
3. Click on the Edit Image icon at the top of the image block you just created in the above step.
4. Click on the Media Library button.
5. In the Attachment Details section of the pop-up window Select or Upload Media, click on Delete Permanently and delete the image from the site.
6. Close the Select or Upload Media window.
7. Delete the image block.
8. Copy the second image to the clipboard and paste it in Gutenberg in the same position as the previous image block you just deleted.
9. You'll see the previously pasted image.

**Expected behavior**
The newly copied image should be inserted.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 78, Firefox 71

**Additional context**
- WordPress 5.3

**Comment by talldan** [comment] 2020-02-04 05:31
Thanks for the report, @mipon. 

I wasn't able to reproduce this issue on Mac OS X, but can confirm it on Windows.

**Comment by kathrynwp** [comment] 2022-08-08 14:05
Hi @mipon, are you still able to replicate this with the latest version of WordPress? I tried to have someone with a Windows machine follow the above steps, but they could not find the "Edit image" icon at this step, so it looks like the UI may have changed. Just let me know if there's a different way to replicate, thank you!

> Click on the Edit Image icon at the top of the image block you just created in the above step.

**Comment by mipon** [comment] 2022-08-09 01:21
Indeed, in recent WordPress versions (at least in 6.0.1), the UI of the image block seems to have changed and the above steps are no longer valid. 

I tried to reproduce the bug with similar approaches in the new UI but so far I haven't been able to on Windows.

**Comment by kathrynwp** [comment] 2022-08-09 15:06
@mipon Thanks so much for responding and retesting. I'll go ahead and close this out, but if anyone is still able to replicate, feel free to add a comment with additional details and I’ll be glad to reopen it.

**Closed by kathrynwp** 2022-08-09 15:06 UTC
Labels: [Type] Bug, [Feature] Raw Handling, Browser Issues
