### ISSUE TITLE
Remove override indicator when editing a pattern with overrides

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62193] opened 2024-05-31 17:22 UTC
### Description

As a follow-up to https://github.com/WordPress/gutenberg/pull/61560, the override indicator should be available only in the context of overriding, rather than editing the synced pattern itself. 

### Step-by-step reproduction instructions

1. Add a synced pattern.
2. Add an override.
3. See the extra block icon. 
4. Add that pattern to a page. 
5. See the proper placement for the icon. 

### Screenshots, screen recording, code snippet

![335621721-1d989332-7718-46a9-b9b7-32f923071e02](https://github.com/WordPress/gutenberg/assets/1813435/0d79e75e-3ab1-4099-94a9-c09a7b8124ad)

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment] 2024-06-03 20:12
@richtabor do you mind attaching the synched pattern you used for testing and reporting this please? It would likely expedite testing and solving. Thanks for reporting!

**Comment by colorful-tones** [comment] 2024-06-04 02:01
I’m unclear as to whether this is a bug or merely iteration towards a new feature through code and/or without any design consideration or user experience outreach? Perhaps some brief details as to how it is framed as a bug might help other contributors dig in and move things along, which could free up other contributors to focus on other things.🤔

**Comment by talldan** [comment] 2024-06-04 02:57
It definitely looks like a bug, as there are two block icons on the toolbar:
![Screenshot 2024-06-04 at 10 51 38 am](https://github.com/WordPress/gutenberg/assets/677833/3b15d426-19d5-4d3d-a0be-8a6c889b25a0)

It should happen with any pattern when editing the pattern source. So for example, in the site editor's patterns page, when editing an existing synced pattern or using the 'Add new pattern' option.

Select a paragraph in the pattern, go to the block inspector > advanced panel, and select 'Enable Overrides'. Type a name into the modal and confirm, then the second block icon appears on the toolbar.

**Comment by richtabor** [comment] 2024-06-04 13:42
> I’m unclear as to whether this is a bug or merely iteration towards a new feature through code and/or without any design consideration or user experience outreach?

Two of the same block icons in the toolbar is a bug. :)

**Comment by colorful-tones** [comment] 2024-06-04 14:15
> It definitely looks like a bug, as there are two block icons on the toolbar

I guess as long as its clear to you folks that a duplicate icon is a bug then that is all that matters, right. However, it is not clear from the information on this current issue the context as to why or what the expected behavior is (to me). We may want to explore being a bit more thorough on our issue descriptions in order to empower new contributors or even newer contributors to engage and possibly even chip in. Just some feedback for consideration. Thanks for all the contribution efforts. 🫶

**Comment by talldan** [comment] 2024-06-20 10:10
I believe this was fixed by @kevin940726 (and in testing I can no longer repro). Kai can probably advice the exact PR.

**Closed as completed by talldan** 2024-06-20 10:10 UTC
Labels: [Type] Bug, [Feature] Synced Patterns
