### ISSUE TITLE
Widgets Editor: Remove inserter parent block header

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#28174] opened 2021-01-13 19:30 UTC
<img width="698" alt="image" src="https://user-images.githubusercontent.com/191598/104499853-ae7b0b00-55ab-11eb-8c4a-960d64dc237a.png">

When adding a block to a widget area using the new Widgets editor, the inserter sidebar shows an indicator of the "parent block" — which I guess in this case is the widget area. However, this is mostly useless information.

Can we remove it?

**Comment by talldan** [comment] 2021-01-14 04:01
This looks like a duplicate of #26329, it's actively being fixed in #28036.

**Closed by talldan** 2021-01-14 04:01 UTC
Labels: [Feature] Widgets Screen
