### ISSUE TITLE
Social Icons - icon color overridden by parent group container link color

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#34658] opened 2021-09-08 15:13 UTC
### Description

When adding Social Icons within a Group block, the icon color is overridden by the link color set at the parent group level.

This only happens on the frontend, in the editor the icon displays correctly with the icon color.

### Step-by-step reproduction instructions

1. insert a Group block, set Link Color for this group block
2. add a Social Icons block within the group
3. change the Icon Color from the default to any color other than the parent group link color
4. in the editor the icon color is correct
5. view in frontend and notice how the icon color is incorrectly rendered with the link color of the parent group block

### Screenshots, screen recording, code snippet

Editor view:
![social-icons-color-editor](https://user-images.githubusercontent.com/76742815/132536162-f03f8d0d-8583-4bcf-a6a8-77727e352067.png)

Frontend view:
![social-icons-color-frontend](https://user-images.githubusercontent.com/76742815/132536202-79f6290f-516f-4fe9-bab7-8027b6820f7c.png)

### Environment info

WP 5.8
Gutenberg 11.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment] 2021-09-09 06:21
Confirmed. I was able to replicate this. It's due to the usage of `currentColor` on Social Icon SVGs and the icon color setting not being applied.

Needs fix.

**Comment by getdave** [comment] 2021-09-09 06:27
<img width="667" alt="Screen Shot 2021-09-09 at 07 26 26" src="https://user-images.githubusercontent.com/444434/132634120-86dd8928-8bf8-457e-afd4-8cf3de6f89e5.png">

Seems to be due to `!important` on this CSS rule which is injected into the DOM as a `<style>`.

**Comment by mkkeck** [comment] 2021-09-09 07:12
If css elements referenced correct, then the `!important` flag is not required.

I think it has to do with merged styles, see #34575, why there now always the `!important` is required.

**Comment by Sandstromer** [comment] 2021-09-09 07:59
> 
> 
> <img alt="Screen Shot 2021-09-09 at 07 26 26" width="667" src="https://user-images.githubusercontent.com/444434/132634120-86dd8928-8bf8-457e-afd4-8cf3de6f89e5.png">
> 
> Seems to be due to `!important` on this CSS rule which is injected into the DOM as a `<style>`.

Yes, using browser inspector, removing `!important` rule fixes this issue, and does not break the text link color either.

**Comment by getdave** [comment] 2021-09-09 08:28
I suspect this could be coming from global styles? I did search on the entire GB codebase and found the only references were in global styles unit tests.

I've [asked in Core Editor in Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1631176228390700).

**Comment by getdave** [comment] 2021-09-09 08:57
@oandregal Replied

> It comes from the lib/block-supports/elements.php that takes care of creating the styles for the link color. In this case !important is used for user-provided styles to have higher specificity than any theme-provided styles (see PR).

In this case @oandregal how can we avoid playing specificity wars within the Social Links block?

**Comment by oandregal** [comment] 2021-09-09 09:50
I'm going to close this in favor of https://github.com/WordPress/gutenberg/issues/33437 Will continue the conversation there.

**Closed as completed by oandregal** 2021-09-09 09:50 UTC
Labels: [Type] Bug, [Block] Social
