### ISSUE TITLE
No simple way to "View Post"

### ISSUE THREAD

**Issue by wekhter** [WordPress/gutenberg#1573] opened 2017-06-29 02:28 UTC
I was testing out the Gutenberg editing experience, and one of the first things I noticed after publishing a test post was the lack of "View Post" link in the top toolbar.

With the current editor, when you publish or update a post you get a notification, "Post published (or updated). View post." Gutenberg seems to replace this with a small "saved" which is of course missing the link to "view post."

The current editor also keeps the permalink visible underneath the post title, both to give easy access to the permalink (I know there's another issue about this already) and also to serve as a preview of the post (if it isn't published) and as a "view post" link (if it is published).

Aside from clicking on a post's title to reveal the permalink (which is not intuitive, on top of requiring an extra click) there is no easy way to view the post from the Gutenberg editor. There's an always-visible preview post, as there's always been, so why has view post been removed?

**Comment by StaggerLeee** [comment] 2017-06-29 12:17
It is on the right in top toolbar, called "Preview" with eye icon.

**Comment by mtias** [comment] 2017-06-29 12:54
Also see: https://github.com/WordPress/gutenberg/pull/1564

**Comment by wekhter** [comment] 2017-06-29 13:59
@StaggerLeee I understand there's an always-visible "Preview" link (I mentioned it in the last line of my comment) but "Preview" is very different from "View Post."

"Preview" is "see how the post **will** look."

"View post" is "see the published post."

@mtias It looks like that's adding the "View Post" back with the published notice, but is the "View Post" in the toolbar coming back?

**Comment by youknowriad** [comment] 2017-06-29 14:24
looks like a duplicate to #969 for me

**Comment by youknowriad** [comment] 2017-06-30 12:22
@StaggerLeee There's a button to remove the notices, maybe we should add a timeout for these notices, but this deserves a separate issue.

**Comment by StaggerLeee** [comment] 2017-06-30 12:23
Yes, please add timeout. Should I make new issue ?

**Comment by youknowriad** [comment] 2017-06-30 12:29
Yes, thanks. A timeout has several implications a dedicated issue will be a good place to discuss it. I'm closing this one as duplicate of #969

**Closed by youknowriad** 2017-06-30 12:29 UTC
