### ISSUE TITLE
UI: Add Page Templates

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#991] opened 2017-06-02 07:46 UTC
When you use the editor to edit a page, you need to be able to pick a template, set the order, and parent.

Those three properties are very likely to change in the future. But they are nonetheless important to be able to set in a transitional period.

What's the best way to approach this?

Here's a quick mockup of a transitional metabox that would be good to retire once something superior can replace it:

![screen shot 2017-06-02 at 09 44 37](https://cloud.githubusercontent.com/assets/1204802/26716064/5143ce58-4778-11e7-9498-2e69beff9f05.png)

![post settings](https://cloud.githubusercontent.com/assets/1204802/26716068/534631a0-4778-11e7-9a92-12aecf32d3b9.png)

**Comment by paulwilde** [comment] 2017-06-02 12:05
The order should be a `[type="number"]` input field instead of a dropdown, by the way.

**Comment by jasmussen** [comment] 2017-06-02 12:12
> The Order field should be a [type="number"] input instead of a dropdown, by the way. Drop-down doesn't really make sense for numerical values, as you could be thousands of options.

That was bad mockup copy/pasta on my part, sorry :) I meant for it to be a plain input field, but type="number" is even better.

**Comment by afercia** [comment] 2017-06-02 15:10
Hm I'm not sure about the `[type="number"]` while technically it would be appropriate, we're discussing them in the accessibility team since it seems it's not widely supported by assistive technologies 😞  More details here: https://make.wordpress.org/accessibility/2017/02/13/testing-html5-type-attributes-in-forms-with-different-browsers-and-at/

`[type="number"]` seems problematic especially with speech recognition software (Dragon), more details here: https://make.wordpress.org/accessibility/2017/01/16/testing-form-functionality-with-different-assistive-technology/

**Comment by aduth** [comment] 2017-06-12 20:33
>we're discussing them in the accessibility team since it seems it's not widely supported by assistive technologies 😞 More details here: https://make.wordpress.org/accessibility/2017/02/13/testing-html5-type-attributes-in-forms-with-different-browsers-and-at/

My takeaways from this post are: validation isn't always reliable (maybe not a blocker?), shows a small input by default (could be resolved by styling or `size` attribute?). Anything I overlooked?

>`[type="number"]` seems problematic especially with speech recognition software (Dragon), more details here: https://make.wordpress.org/accessibility/2017/01/16/testing-form-functionality-with-different-assistive-technology/

That's a shame. If this becomes a blocker, maybe it could be enough to recreate the effect with a `text` type, numeric `pattern` attribute, and manually bind to the keyboard events to simulate increment effects?

**Comment by mtias** [comment] 2017-06-22 10:23
This is something that needs to be added. For v2 we'll rethink how you select templates, maybe with an upfront selection process like when creating a new slide in keynote or pages document.

**Comment by westonruter** [comment] 2017-07-04 00:51
I'd like to see, probably in v2, page templates that specify the blocks that they allow, their order, how many of each type, and so on. When they do these blocks then get added to the editor as locked. This could be added to the page template metadata PHP docblock comment.

**Comment by jasmussen** [comment] 2017-07-04 08:01
> that specify the blocks that they allow

See also #1654

**Comment by aduth** [comment] 2017-07-12 19:27
Added "Needs API Endpoint" label. To my knowledge, there's currently no way to retrieve available page templates from the REST API.

**Comment by westonruter** [comment] 2017-07-12 23:56
Something else to note is that the list of available page templates can actually vary from page to page, due to the `page_attributes_dropdown_pages_args` filter. So the endpoint would need to hang off of the page resource itself, like: `/wp-json/wp/v2/pages/:id/available-templates`

**Comment by westonruter** [comment] 2017-07-29 19:21
@aduth I've started a PR (#2086) to add a new `available_page_templates` field to the `page` resource which we can use to obtain the available templates _and their names_ for use in a page template selector.

**Comment by mtias** [comment] 2017-08-04 15:00
Punting.

**Comment by BE-Webdesign** [comment] 2017-09-06 15:13
From my understanding #2086 has been closed. I can take this up.

**Comment by youknowriad** [comment] 2017-12-18 10:01
This is important to have, let's try to work on this soon.

**Comment by redsoxfan2499** [comment] 2017-12-25 12:23
Just wondering about the status of including page templates. I just downloaded the recent version and there is no where to choose a page template. I like idea of adding certain blocks based on a CPT but there are plenty of times where there is NO CPT created but I still need to use a custom template. So just checking on the status of how and when the ability to choose a custom template from the Gutenberg editor.

**Closed** 2018-01-26 11:34 UTC
Labels: Core REST API Task, Design, [Component] Plugin

**Comment by redsoxfan2499** [comment] 2018-08-20 13:06
aduth,  thanks for the information. Yes it is showing up now.  

Thanks!

**Comment by gmariani** [comment] 2018-09-05 15:17
Still not seeing it, running Gutenberg 3.7 on WordPress 4.9.8

**Comment by ajvillegas** [comment] 2018-09-05 17:49
@gmariani Make sure that your theme is loading at least one page template, because if your theme is not, then it won't show up.

**Comment by jcklpe** [comment] 2018-09-29 06:09
@ajvillegas I am also not able to see any page template selectors, and I'm pretty sure that my theme is loading up a template. I'm just using a modified version of twentyseventeen.

**Comment by ChazzLayne** [comment] 2018-12-21 21:07
I'm not seeing it either, and I KNOW there are page templates on the site/theme I'm editing. The site and theme in question have not changed in any way other than the update to WP5, so clearly this is a WP5/Gutenberg issue.

(And FWIW, I actually love Gutenberg, can't wait for it to be perfect.)

**Comment by aduth** [comment] 2019-01-02 16:37
@jcklpe @ChazzLayne If possible, could you provide a set of steps that someone could follow to reproduce the issue? Particularly considering whether there's a specific (publicly-available) theme / post type combination under which valid templates are not appearing.

It may be worth providing these as part of a new issue targeted at missing templates, rather than continuing the discussion here, since it will be more visible / actionable that way.

**Comment by stellalabella** [comment] 2019-01-17 17:26
WordPress 5.0.3 running Twenty Nineteen theme.  No template options in New Page. :(

**Comment by aduth** [comment] 2019-01-21 18:38
@stellalabella The Twentynineteen theme does not include any custom page templates, which is the likely explanation for them not being shown in the editor. The same can be seen in the classic editor using the Classic Editor plugin.

**Comment by jultra** [comment] 2019-02-28 06:40
I have installed Wordpress 5.1. Template option is not available in Add new page also. I tried several themes just in case, and yet, none one of them got their template option displayed in the edit page.

**Comment by themedleb** [comment] 2020-03-22 06:30
Same here, no "Page Template" option under "Page Attributes", and I'm sure that I have a template file in my theme folder like "templatename.php".
Has this content:
`
<?php
/*
Template Name: templatename
Template Post Type: page
*/
?>
`

That's weird.
