### ISSUE TITLE
Gallery Block: Full-width causes horizontal scrollbar

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#17233] opened 2019-08-28 12:40 UTC
Discovered by @jasmussen in https://github.com/WordPress/gutenberg/pull/17197#issuecomment-525628228, but does not appear to be related to that PR. 

<img width="671" alt="Screen Shot 2019-08-28 at 8 37 22 AM" src="https://user-images.githubusercontent.com/1202812/63856213-160cc800-c96f-11e9-8f49-6c958c1cb779.png">

To reproduce: 

1. Add a Gallery Block with at least one item.
2. Set it to full width.
3 Observe that horizontal scrollbars appear.

This is not present in Gutenberg Version 6.4.0, but is present in `master` as of 9/28/19.

**Comment by youknowriad** [comment] 2020-04-01 10:24
Can't reproduce on 2020. I believe this is related to the 2019 alignment issues. So I'm going to close this as I believe these are already fixed separately?

**Closed by youknowriad** 2020-04-01 10:24 UTC
Labels: [Block] Gallery, [Type] Bug, [Type] Regression
