### ISSUE TITLE
Query Block: No posts displayed in editor

### ISSUE THREAD

**Issue by filipanoscampos** [WordPress/gutenberg#56592] opened 2023-11-28 14:37 UTC
### Description

In the Site Editor, the Query Block doesn't display any posts even if they show on the frontend.front end

### Step-by-step reproduction instructions

1. On a website with a Site Editor theme installed, published posts, and Gutenberg version 17.1.2 or 17.1.3, please navigate to the Site Editor and open a template
2. Add a query loop block
3. Notice how it shows "No results found" while the live site displays the posts as expected.

### Screenshots, screen recording, code snippet

How this is shown in the Editor:
![Editor](https://github.com/WordPress/gutenberg/assets/2540430/d5990439-2b1b-45e6-b786-15620612d82e)

And on the front end:
![Live site](https://github.com/WordPress/gutenberg/assets/2540430/53912b9f-fbca-4bec-9d3a-a982f0e76a80)

### Environment info

Gutenberg versions 17.1.2 and 17.1.3
Tested on several themes. 

Reported also on WordPress.com websites that do not use plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-11-28 15:53
Thanks for the report.

This problem may be caused by the offset of the query being shifted on the editor side. Also reported in #56440 and fixed in #56439.

This fix will ship as part of version 17.2 of the Gutenberg plugin.

I'll close this issue, but if this problem still occurs with Gutenberg plugin version 17.2, I'd appreciate it if you could comment again.

**Closed as not planned by t-hamano** 2023-11-28 15:53 UTC
Labels: [Type] Bug, [Status] Duplicate, [Block] Post Template
