### ISSUE TITLE
Gallery: Add image to existing Gallery overwrites existing Images Selection

### ISSUE THREAD

**Issue by vheinrich** [WordPress/gutenberg#36620] opened 2021-11-18 15:40 UTC
### Description

When you already added a Gallery Block with some images and want to add more images, the new images arent added to the selection. instead these new images replace the whole former gallery image selection.

### Step-by-step reproduction instructions

1) Add a Gallery with images
2) Save the post / page
3) Edit the post and go to the Gallery Block to the Button "Media Library"
4) Select new images and click "Add to gallery"
5) At the media library view you just see the new selected images
6) When you click update Gallery the former images selection is gone and just the new selected images are at the Gallery Block

### Screenshots, screen recording, code snippet

https://app.tango.us/app/workflow/08eae919-c50f-4f76-902b-768d2ef8089c

### Environment info

- Wp 5.8.2.
- Plugins: WP Importer
- Theme: Twenty Twenty-One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2021-11-22 04:00
Thanks for reporting this. It looks like it is a duplicate of https://github.com/WordPress/gutenberg/issues/33769, which was fixed by https://github.com/WordPress/gutenberg/pull/35070 - I just tested on Gutenberg 11.9 and can't reproduce this, so this will be fixed in WP 5.9.

I am closing for now, but if you can reproduce it with 11.9 of Gutenberg installed @vheinrich feel free to re-open this issue.

If you are not able to install the 11.9 plugin for some reason there is a workaround to the problem [noted here](https://github.com/WordPress/gutenberg/issues/33769#issuecomment-893919935).

**Closed as completed by glendaviesnz** 2021-11-22 04:00 UTC
Labels: [Block] Gallery
