### ISSUE TITLE
Pullquote block issue in left and right align.

### ISSUE THREAD

**Issue by Smit2808** [WordPress/gutenberg#39250] opened 2022-03-07 12:15 UTC
### Description

When Pullquote is having a full-width option selected and then selecting left or right-align the full width gets removed and the whole block shifts in left or right alignment.

### Step-by-step reproduction instructions

1. Select Pullquote block and then select the full-width option.
2. Now select the left or right alignment. You can clearly see the issue. 

Attaching images for better understanding.

### Screenshots, screen recording, code snippet

<img width="1440" alt="Screenshot 2022-03-07 at 5 39 56 PM" src="https://user-images.githubusercontent.com/64188895/157031941-85c51bdc-dfae-4c01-b8c8-7d72bc47aadf.png">

The above image is of the editor view.

<img width="1440" alt="Screenshot 2022-03-07 at 5 41 37 PM" src="https://user-images.githubusercontent.com/64188895/157032180-c2b1bef0-b989-4bd7-bc86-246038b150bb.png">

The above image is the front view.

### Environment info

WordPress version 5.9.1
Theme: Twenty Twenty-Two.
Fresh setup no other plugins or themes are installed.
Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment] 2022-03-07 18:05
Hi, 

Thanks for reporting. I am able to reproduce this in wordpress 5.9.1. with  [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)  disabled but I am not able to reproduce this with the Gutenberg plugin enabled; so it appears to be fixed by a recent change in the Block editor that will eventually be included in WordPress Core; in the meantime, you can use the [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/) if you would like the latest updates and fixes with the block editor.

**Closed as completed by skorasaurus** 2022-03-07 18:05 UTC
Labels: [Block] Pullquote, CSS Styling
