### ISSUE TITLE
Gutenberg Issue -TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by latereverafter** [WordPress/gutenberg#12695] opened 2018-12-08 04:41 UTC
Hello I have an issue with the new Gutenberg.  Here is the error I an experiencing.  I can not add or edit any posts.  Can you help?  The error is below.  

```
 TypeError: Object(...) is not a function
    at ve (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83680)
    at https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83120
    at i (https://www.latereverafter.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:6:91)
    at An.filter (https://www.latereverafter.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:99:338)
    at _e (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83097)
    at we (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83557)
    at t.value (https://www.latereverafter.com/wp-includes/js/dist/editor.min.js?ver=9.0.4:55:266041)
    at Fd (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:367)
    at Mf (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:160)
    at ph (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474)
```

**Comment by designsimply** [comment] 2018-12-08 06:05
Thank you for including an error! However, in this case it's not shedding much light on what could be the source of the trouble. 

To clarify, when exactly does that error appear? On page load or when you click something like "Save Draft" or "Publish"?

In order to rule out a plugin conflict, would it be possible for you to temporarily deactivate other plugins (if you have any) and switch to the default theme. If the problem goes away, then turn on each plugin one-by-one until you find the source of the trouble.

**Comment by Drayks** [comment] 2019-01-03 15:31
i get the same, it is caused by Yoast (latest version Version 9.3 )
in the new wp editor (latest wp version 5.0.2)

**Comment by sg6** [comment] 2019-02-11 20:39
> Just noticed that its a combination of ACF ( old version pre Gutenberg ) with Yoast.
> Disabling or updating ACF also fixes it.

You saved me hours of work, man ! Thanks so much

**Comment by designsimply** [comment] 2019-02-11 21:28
> Just noticed that its a combination of ACF ( old version pre Gutenberg ) with Yoast.
> Disabling or updating ACF also fixes it.

Thank you so much for the note @Drayks!

I am closing this issue as a older plugin conflict with the recommendation to please make sure all plugins are updated to the latest versions since many updates have been made recently, especially compatibility updates with Gutenberg.

If anyone finds they are finding a similar issue, please try to get a more detailed error message from the console panel in your browser's web developer tools section, if at all possible, and report it as a new issue for the relevant plugin author mentioning your WordPress version and your active plugins and their versions for reference. If you feel the issue you are experiencing is more relevant to the Gutenberg code than the plugin code (which can happen!), please first go through troubleshooting at https://wordpress.org/support/forum/how-to-and-troubleshooting/ and ask them for help determining what information should be gathered prior to creating a bug report in the Gutenberg Github repository. Thank you so much!

**Closed by designsimply** 2019-02-11 21:28 UTC
Labels: [Type] Help Request

**Comment by gauravdeveloper** [comment] 2020-01-31 10:48
> i get the same, it is caused by Yoast (latest version Version 9.3 )
> in the new wp editor (latest wp version 5.0.2)
> 
> While trying to edit a block (clicking on block to activate the editor)
> 
> Just noticed that its a combination of ACF ( old version pre Gutenberg ) with Yoast.
> Disabling or updating ACF also fixes it.

Thanks Buddy, it's working.
