### ISSUE TITLE
Nav block: No option to choose existing menu.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#19982] opened 2020-01-31 14:51 UTC
I add the Navigation block and see this:

<img width="723" alt="Screen Shot 2020-01-31 at 12 52 37" src="https://user-images.githubusercontent.com/5323259/73537446-c56f2e80-4428-11ea-90cb-8e22a022b70b.png">

I expect to see the option to choose from an existing menu.

I find this a very interesting issue:
https://github.com/WordPress/gutenberg/issues/19170
As it explores a better Navigation Block experience.

Here is a wireframe I made based on the 19170 issue.

![Nav-wireframe-Gutenberg](https://user-images.githubusercontent.com/5323259/73548643-6e298800-4441-11ea-8fe5-f457f38727bb.jpg)

I see various work is going on regarding the navigation block. I will just share what I notice at this stage that I notice needs adjusting.

**Comment by mtias** [comment] 2020-01-31 17:22
Duplicate of #18575.

**Closed by mtias** 2020-01-31 17:22 UTC
