### ISSUE TITLE
Backspace to clear "Create Reusable Block" modal's name field deletes the selected blocks

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#37539] opened 2021-12-20 22:30 UTC
### Description

Originally reported in [WordPress Core's Trac ticket 54652](https://core.trac.wordpress.org/ticket/54652).

Since WordPress 5.9 Beta (works correctly in 5.8.1), backspacing to clear the reusable block's name in the "Create Reusable Block" modal closes the modal and deletes the selected blocks. This is different from WordPress 5.8.1 which clears the name field, but keeps the modal open and does not delete the selected blocks.

The reporter also notes that control Z does not restore the content; however, in my testing, control Z did restore the blocks for me.

### Step-by-step reproduction instructions

1. Add a new post
2. Add several blocks
3. Select more than one block
4. Select options icon in the toolbar
5. Select "Add to Reusable blocks"
6. Start to type something in the modal
7. Backspace to clear the name field

Notice the modal closes and the selected blocks are deleted.

### Screenshots, screen recording, code snippet

![test-attempt-to-reproduce-54652](https://user-images.githubusercontent.com/7284611/146841150-532206c3-e1de-4827-b433-108f572ee2e2.gif)

### Environment info

* OS: macOS Big Sur
* Browsers: Chrome, Safari, Edge, and Firefox
* WordPress: trunk, 5.9 Beta 3, and 5.8.1
* Theme: TT2 for 5.9, TT1 for 5.8.1
* Plugins: none and with Gutenberg v 12.1.0 activated
* Localhost: wp-env and Local

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by costdev** [comment] 2021-12-21 06:35
**Environment Info**
OS: Windows 10
Browser: Chrome
WordPress: trunk
Theme: TT2
Plugins: Gutenberg 12.1

1. Pressing the `Backspace` or `Delete` keys while naming a Reusable Block deletes the content.
2. Ctrl-Z restores the content after two presses.

Removing this event listener removes the `Backspace` or `Delete` behaviour:

![gb-37539](https://user-images.githubusercontent.com/79332690/146882807-5482eed1-1dab-418a-906b-7453363e0b52.jpg)

- Removing any other event listener, including (5), doesn't work.
- It's specifically (4) that seems to be causing the behaviour.

**Comment by Mamaduka** [comment] 2021-12-21 11:50
I think this is a duplicate of #36513, and it also has (unlinked) PR - #36663.

Unfortunately, I'm not sure if the solution proposed in the PR is the proper fix.

/cc @ellatrix.

**Comment by costdev** [comment] 2021-12-21 13:54
@Mamaduka You're right, it is a duplicate. I haven't tested the PR, but it seems to only target Backspace - In my testing, the Delete key produced the same behaviour. Testing of the PR should include testing with the Delete key also.

/cc @delowardev

**Comment by Mamaduka** [comment] 2021-12-21 13:57
Good point, @costdev.

I will close this issue as a duplicate and reference your comment in PR.

**Closed as completed by Mamaduka** 2021-12-21 13:57 UTC
Labels: [Type] Bug, [Feature] Synced Patterns, [Status] Duplicate, [Block] Block
