### ISSUE TITLE
Pasting equation breaks due to markdown interpretation

### ISSUE THREAD

**Issue by gibrown** [WordPress/gutenberg#10080] opened 2018-09-20 20:37 UTC
**Describe the bug**
When pasting an equation that has `*` in it, the text gets interpreted as markdown which then messes up the formatting. The particular case I see pasting

```fields: 500*6 + 1000*4 = 7000```

results in

```fields: 5006 + 10004 = 7000```

With emphasis added to the `6 + 1000` string

**To Reproduce**
1. Just paste `fields: 500*6 + 1000*4 = 7000` into a block

**Expected behavior**
I expected to just see an equation. :)

This particular case may not be a big deal, but I suspect there may be some related bugs that are not a great UX.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68

**Additional context**
- I've only tested this on a8c p2s on WP.com. Not sure if that is a different flavor of Gutenberg right now.

**Comment by gibrown** [comment] 2018-09-22 02:39
Interesting, yes, I only tested when pasting text from emacs.

**Comment by gektor-de** [comment] 2018-11-06 15:20
Is this still the case? Can't reproduce on 4.1.1.

**Comment by gibrown** [comment] 2018-11-08 17:53
@gektor-de still happening on 4.2.0. Note that it only happens if you paste from a pure text file. So copying and pasting from this browser window does not cause the problem to occur. I would guess because some formatting info is coming along with it. I'm doing it from an emacs buffer. TextEdit on mac for instance does not show the problem. If I past from a command line terminal though (iTerm2) then it also happens.

**Comment by ellatrix** [comment] 2019-12-12 13:25
We could make an exception for single lines or if we don't otherwise detect any Markdown.

**Comment by talldan** [comment] 2020-04-22 08:09
I can no longer reproduce this issue, so closing

**Closed by talldan** 2020-04-22 08:09 UTC
Labels: [Feature] Raw Handling, [Type] Bug
