### ISSUE TITLE
Toolbar controls of block persist after selecting different one

### ISSUE THREAD

**Issue by bartekcholewa** [WordPress/gutenberg#6213] opened 2018-04-16 21:44 UTC
I used example from
https://wordpress.org/gutenberg/handbook/blocks/block-controls-toolbars-and-inspector/

![zrzut ekranu 2018-04-16 o 23 41 31](https://user-images.githubusercontent.com/5921659/38836821-e21310d6-41cf-11e8-8612-53386a5a8fdf.png)

After deselecting Hello World (Step 4) block[dsadsadsa content ] its controls are showing on other blocks [alignment].

**Comment by gziolo** [comment] 2018-04-17 06:03
It's a similar issue to #5633. Is it your block or Text columns block of Columns (Experimental) block?

**Comment by bartekcholewa** [comment] 2018-04-17 06:50
Two on top with Welcome to WordPress are Columns (Experimental).

**Comment by gziolo** [comment] 2018-04-18 07:33
I will work on both issues later this week, thanks for opening this issue 🙇

**Comment by SuperGeniusZeb** [comment] 2018-04-30 14:47
I cannot reproduce in Gutenberg 2.7.0. I think this may have been fixed along with #6047 in #6082.

**Comment by gziolo** [comment] 2018-04-30 14:56
#6419 should be merged soon and might help, too.

**Closed** 2018-05-07 08:00 UTC
Labels: Blocks, [Type] Bug
