### ISSUE TITLE
NUX: Confused experience when toggling Show Tips on edit post

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#7753] opened 2018-07-06 17:18 UTC
It appears that the NUX tips are shown only when drafting a new post. Thus, it is confusing when editing an existing post there is an option shown in the More Options menu to "Show Tips", which does not have any noticeable effect when toggled one way or the other.

Should we...

- Allow tips to be shown on edit?
   - Only in response to toggling the menu option?
- Hide the menu option if we don't intend for NUX to be shown on edit?

**Steps to reproduce:**

1. Navigate to Posts > Add New
2. Ensure Menu > Show Tips is not toggled
3. Add a paragraph with some text
4. Save the post
5. Refresh the editor
6. Toggle Menu > Show Tips on

_Expected:_ Tips prompts are shown.
_Actual:_ Tips prompts are not shown, even after another refresh.

**Comment by aduth** [comment] 2018-07-06 17:19
Related: #7458

**Comment by karmatosed** [comment] 2018-07-09 14:38
I think allow tips to be shown on first 'anything' including edit. We kept the to new post to test and that seems a valid expansion.

**Comment by noisysocks** [comment] 2018-07-10 01:39
Closing this in favour of https://github.com/WordPress/gutenberg/issues/7458. I think that the best UX is to uncheck the _Show Tips_ setting when the guide has been completed.

**Comment by noisysocks** [comment] 2018-07-10 01:40
Oh, misread this. 

Tips should show in edit. The issue is likely that the inserter button is not shown and so the first tip does not render.

**Comment by tofumatt** [comment] 2018-07-10 20:16
I was having issues with tips not appearing in the "edit post" screen I think as well, but I seem to be able to see them now:

![2018-07-10 21 15 18](https://user-images.githubusercontent.com/90871/42535128-8122e2a2-8486-11e8-8932-44fe56741fc2.gif)

Please reopen if I missed something, but I can see the tips on edit in `master`.

**Comment by aduth** [comment] 2018-07-10 20:20
As noted by @noisysocks in https://github.com/WordPress/gutenberg/issues/7753#issuecomment-403671766 , I think the specific steps to reproduce aren't entirely obvious, and depend on whether the default appender is present when the editor loads.

**Steps to reproduce:**

1. Navigate to Posts > Add New
2. Ensure Menu > Show Tips is not toggled
3. Add a paragraph with some text
4. Save the post
5. Refresh the editor
6. Toggle Menu > Show Tips on

_Expected:_ Tips prompts are shown.
_Actual:_ Tips prompts are not shown, even after another refresh.

**Comment by tofumatt** [comment] 2018-07-10 20:21
Ohhhhhh okay, thanks. I'll see about another test for that in #7874.

**Comment by afercia** [comment] 2018-07-26 08:29
> I think allow tips to be shown on first 'anything' including edit.

Seems on current master the tips are now displayed also on existing posts, not sure if after an intentional change.

Note: the last block must not be a paragraph otherwise there's no "side inserter" the first tip can hook to. There's a pending proposal to move the first tip to the inserter in the top bar though. See #8050

**Comment by aduth** [comment] 2018-07-31 14:45
Also, if the existing post has a significant amount of content, it's not clear there's a tip at all, because it is shown outside of the initial viewport.

**Comment by jasmussen** [comment] 2018-10-23 12:14
I cannot reproduce this issue in master anymore. This is after exploring explicit steps in https://github.com/WordPress/gutenberg/issues/7753#issuecomment-403952816. Closing as fixed, but please reopen if this was in error.

**Closed by jasmussen** 2018-10-23 12:14 UTC
Labels: NUX, [Type] Bug

**Comment by noisysocks** [comment] 2018-10-24 00:46
I think https://github.com/WordPress/gutenberg/pull/9223 fixed this. Thanks @jasmussen!
