### ISSUE TITLE
Gallery Caption gets removed when edit the gallery again.

### ISSUE THREAD

**Issue by Tajwebdeveloper** [WordPress/gutenberg#8749] opened 2018-08-09 04:42 UTC
## Issue Overview
I have inserted the gallery using Gutenberg and added caption with link directly from WYSIWYG editor, but as soon as i edit the gallery to reorder the images all the captions got disappear.. Now i have added caption from the admin gallery screen this time all works fine.

## Steps to Reproduce (for bugs)
1. Insert Gallery from editor
2. Add few images and put some caption on the WYSIWYG editor
3. now click on edit gallery 
4. all the caption are blank whether you save the article or not.

## Expected Behavior
If you have added the description and link which is very useful.. it should not get blank when we try to edit the gallery

it should work like it is currently.. but caption should be permanently stored and there are issues sometime while adding the link to the caption it gets off/on and doesn't work properly .. it happens only sometime so i cannot tell you how to reproduce the bug.

http://neelnetworks.org/videos/gallery-issue.mp4

**Comment by KristinaKay** [comment] 2018-08-15 07:41
I just ran into this tonight while updating on my self-hosting site. 

StudioPress's Academy Pro theme and Genesis Framework
You can[ see this in action here](https://monosnap.com/file/CCAQ9afWL9sgrTsDlOjwoajDMFPnze).

**Comment by davidsword** [comment] 2018-08-16 16:13
I'm experiencing this too, custom gallery captions being overwritten by Media Library captions while using Edit Gallery to just rearrange items.

**Comment by noisysocks** [comment] 2018-08-20 06:44
Duplicate of https://github.com/WordPress/gutenberg/issues/8310.

**Closed** 2018-08-20 06:44 UTC
Labels: Blocks, Media, Needs Testing, [Type] Bug

**Comment by jchornenky** [comment] 2020-06-10 04:06
I am experiencing this issue
