### ISSUE TITLE
Problem with caption for aligned images remains in Gutenberg 4.1

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#11039] opened 2018-10-25 06:32 UTC
The problem described in #9530 still remains after an update to gutenberg 4.1.0.

An exemplary post showing the error can be found here: https://www.david-wille.de/autumn-street-scene/

**Comment by jasmussen** [comment] 2018-10-25 07:35
Thanks for the ticket. After investigating, though, it appears the margins are correct. The problem is that the Tracks theme you use applies a zero lineheight to alignments, which breaks the captions:

![captions](https://user-images.githubusercontent.com/1204802/47483307-3c3a7680-d839-11e8-899c-3109a822cbe7.gif)

This is not something we should override in Gutenberg, this should be fixed in the tracks theme. As such, I'm going to close this one for now.

**Closed by jasmussen** 2018-10-25 07:35 UTC
