### ISSUE TITLE
iOS block editor does not respect the in-app dark mode setting

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#31001] opened 2021-04-20 13:41 UTC
## Description
If the in-app Appearance settings is set to Dark, the iOS block editor _does not_ correctly apply the dark mode color scheme. The block editor _does_ correctly respect the OS-level dark mode setting. 

## Step-by-step reproduction instructions
1. Launch the WPiOS app. 
2. Open the My Site tab. 
3. Tap the avatar in the top-right corner to open the Me modal. 
4. Tap App Settings. 
5. Set Appearance to Dark. 
6. Navigate to open the block editor for a post. 

## Expected behaviour
The block editor has the dark color scheme applied. 

## Actual behaviour
The block editor has the light color scheme applied.  

## Screenshots or screen recording (optional)
| In-App Setting | Block Editor |
| --- | --- |
| ![in-app-apperance-setting](https://user-images.githubusercontent.com/438664/115405391-cfa75500-a1b3-11eb-9144-259541187075.jpeg) | ![block-editor-missing-dark-color-scheme](https://user-images.githubusercontent.com/438664/115405398-d0d88200-a1b3-11eb-8a51-fb8a934da6d8.jpeg) |

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v10.4.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone SE
- Operating system: iOS 14.4.2 
- WordPress app version: 17.1 (17.1.0.3)

**Comment by dcalhoun** [comment] 2021-05-13 16:28
This issue is duplicative of https://github.com/wordpress-mobile/WordPress-iOS/issues/14376.

**Comment by Thelmachido** [comment] 2022-08-12 10:56
I can still replicate this issue, on IOS the phone is set to light but I changed the WP in-app settings to dark: 

On a  Post the background is light even though the WP App Settings have been changed to dark: 

<img src="https://user-images.githubusercontent.com/41231764/184339534-997ccd45-6e65-4b84-a0a3-60d98804e52f.png " width="250"  />
 
However, since this is a duplicate of [#14376](https://github.com/wordpress-mobile/WordPress-iOS/issues/14376) I will close this issue. Let me know if we need to keep this open. 

WordPress 6.0.1
Gutenberg 13.8.1 active
Twenty Nineteen theme

**Closed as completed by Thelmachido** 2022-08-12 10:56 UTC
Labels: [Type] Bug, [Priority] Low, Mobile App - i.e. Android or iOS
