### ISSUE TITLE
Taxonomy shows up in the list unexpectedly

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#4114] opened 2017-12-20 18:01 UTC
## Issue Overview
When a taxonomy is registered to show up in the REST API, it will be shown at a post.
Even if `show_ui` is set to `false` or `public` is set to `false`.

Reference:
https://github.com/Yoast/wordpress-seo-premium/blob/035349d2a3f1be95e401b2201a4d5f1545fddef9/premium/classes/premium-prominent-words-registration.php#L75

## Steps to Reproduce (for bugs)

1. Create a taxonomy with `show_in_rest` set to `true`
1. Configure `show_ui` to be set to `false`
1. Configure `public` to be set to `false`

## Screenshots / Video

<img width="285" alt="tewtwet___ _local_wordpress_ _wordpress" src="https://user-images.githubusercontent.com/2005352/34221267-b747f3ae-e5b7-11e7-967d-5592bf0685ee.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment] 2017-12-20 18:10
I think this is duplicate of #2450 but we should mention the "show_ui" flag as well.

**Closed** 2017-12-20 18:11 UTC
