### ISSUE TITLE
Column block: change primary space between columns

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#31723] opened 2021-05-11 20:06 UTC
In columns block when there is more than one column, there should be a space to make it obvious that they are separated, though there is no feature to modify this space.

I mean there should be box model settings to customize each column default margin and padding.
![guten-column-margin](https://user-images.githubusercontent.com/64708228/117877245-91d0b480-b2b9-11eb-913d-b3e2f9e4db4a.png)

Sometimes column inner blocks have their own space and column space makes it double which means ruins the UI.

**Comment by paaljoachim** [comment] 2021-05-11 22:39
Hey @amir2mi Amir

Check out this issue:
**Add gutter, margin, and padding controls to the columns block**
https://github.com/WordPress/gutenberg/issues/24874

The space between the columns would be the gutter area. This is something @aaronrobertshaw is looking into working on. Thank you for creating the issue. As it is a duplicate of the one above we can go ahead and close your issue. (I will let you do so.)

**Closed as completed** 2021-05-12 08:35 UTC
Labels: [Status] Duplicate, [Block] Columns
