### ISSUE TITLE
When converting paragraph to heading, advanced settings in different order

### ISSUE THREAD

**Issue by versatilehuman** [WordPress/gutenberg#11864] opened 2018-11-14 15:39 UTC
**Describe the bug**
The order of the "Advanced" settings for the Heading Block differs depending on if the block was created as a Heading Block or if it was converted from a Paragraph Block. 

Created Heading Block:
1.  HTML Anchor
2. Additional CSS Class

Heading Block converted from Paragraph Block:
1. Additional CSS Class
2.  HTML Anchor

After clicking away from a Heading Block converted from Paragraph Block and clicking back, the order changes to:
1.  HTML Anchor
2. Additional CSS Class

**Screenshots:**

Created Heading Block:

![captureb](https://user-images.githubusercontent.com/7032169/48492208-e7ae6980-e7ee-11e8-9c48-bb12f4444f71.PNG)

Created Paragraph Block, converted to Heading Block:

![capturea](https://user-images.githubusercontent.com/7032169/48492068-956d4880-e7ee-11e8-86de-e992e4d3166e.PNG)

**To Reproduce**
1. Create a new block
2. Type something
3. Convert block to Heading

**Expected behavior**
The Advanced Block Settings are ordered the same for blocks created as Heading Blocks and blocks converted from Paragraph Blocks to Heading Blocks.

**Desktop (please complete the following information):**
- OS: Windows 10
- Chrome 69.0.3497.100

**Additional context**
- Wordpress 4.9.8
- Gutenberg 4.3.0

**Comment by tellthemachines** [comment] 2020-04-23 06:02
This is a duplicate of #7964. Closing in favour of that issue as it has more context.

**Closed by tellthemachines** 2020-04-23 06:02 UTC
Labels: [Priority] Low, [Type] Enhancement
