### ISSUE TITLE
Can't set hover colour for buttons

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8606] opened 2018-08-06 16:09 UTC
**Describe the bug**
You can set the background colour of a button, but you can't set the hover colour (which is quite often different to the background colour). A theme can obviously set a default hover colour, but when the editor allows you to change the button background colour, that default hover colour may not suit. If you can change the background colour of a button, then it makes sense to be able to also change the hover colour.

**To Reproduce**
1. Add button block into page
2. Change background colour
3. Try to change hover colour

**Desktop (please complete the following information):**
- OS: macOS Sierra 10.12.6
- Browser: Firefox Quantum 61.0.1 (64-bit)
- Version: Gutenberg 3.4.0

**Comment by youknowriad** [comment] 2018-08-06 16:32
Closing as duplicate of #4543 Thanks

**Closed by youknowriad** 2018-08-06 16:32 UTC
Labels: [Type] Enhancement
