### ISSUE TITLE
Sidebar doesn't appear when selecting a block inside a Reusable Block

### ISSUE THREAD

**Issue by OksanaRomaniv** [WordPress/gutenberg#18560] opened 2019-11-16 16:44 UTC
**Describe the bug**
Before the update, when you select a block inside the reusable block, it's settings would show in the sidebar under the "Block" tab. Now the tab is empty. This issue isn't there is a block isn't reusable, but a regular block.

**To reproduce**
1. Create 2 group blocks with paragraphs in them
2. Make one block reusable.
3. Select block inside regular group and see the settings of the block in the sidebar.
4. Click "edit" on the reusable group.
5. Select the paragraph block
6. See empty sidebar on the right or reusable group settings (don't know on what this depends, but it's either way and isn't consistent).

**Expected behavior**
The inner block of the reusable block have settings on the right sidebar when selected

**Screenshots**
[block settings in a simple group](http://i.imgur.com/h8kaVu4.png)
[block settings in a reusable group](http://i.imgur.com/W6zZtbY.png)
[block settings in a reusable group v2](http://i.imgur.com/ne6tZlT.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 78
 - Version : WP 5.3

**Comment by draganescu** [comment] 2019-11-19 16:16
I can confirm this as a bug, or at least unexpected behavior:

<img width="989" alt="Screenshot 2019-11-19 at 18 08 31" src="https://user-images.githubusercontent.com/107534/69164405-a125d600-0af8-11ea-9326-5106a2e9501f.png">

In the screenshot above there is a list block selected inside a reusable block and the inspector does not show the properties of the list as it would be expected.

**Comment by draganescu** [comment] 2020-03-27 10:13
I don't know if this has gotten worse or it was like that from the beginning when this bug was signaled. Searching how to debug, I found that you can actually see the controls for a block in a reusable block by:

1. Clicking edit on the reusable
2. Click the desired block
3. Clicking on the reusable again

However the problem is that after 3 selecting another block in the reusable crashes the editor.

![gif-reusable-crash](https://user-images.githubusercontent.com/107534/77745698-6989e600-7024-11ea-9445-3beb5536f363.gif)

**Comment by themightymo** [comment] 2020-04-09 21:27
I'm also experiencing this issue.

- WP 5.4
- Google Chrome Version 80.0.3987.163
- Pressable (nginx)

![gutenberg-block-issue](https://user-images.githubusercontent.com/179105/78942305-0ca81a00-7a7f-11ea-8f86-0fc82c409598.gif)

**Comment by chrisvanpatten** [comment] 2020-04-09 21:29
Looks potentially related to #19436.

**Comment by noisysocks** [comment] 2020-04-21 03:17
My guess is that the sidebar can't tell that the block is selected because that selection state is in the reusable block's registry, not the main post's registry.

**Comment by noisysocks** [comment] 2020-04-21 04:23
I'm adding `[Priority] High` here since there were quite a few duplicate issues which suggests that many users are running into this problem.

Note though that there is a workaround: you can view the sidebar when you edit the reusable block via _Manage all reusable blocks_.

**Comment by OksanaRomaniv** [comment] 2020-05-22 05:49
I also stumbled upon the same behavior when using `BlockEditorProvider`, `WritingFlow` and `BlockList` in a custom block. The content blocks of the custom editor don't render the settings in the sidebar.

**Comment by elliotcondon** [comment] 2020-06-18 01:22
Hi all. Confirming that the issue still exists using WordPress 5.4.2 (with and without the latest Gutenberg plugin). 

The screen-recording posted by https://github.com/WordPress/gutenberg/issues/18560#issuecomment-604920204 sums up the problem quite well. Something is going wrong when selecting a block within a Reusable block. 

Has any progress been made since April?

**Comment by youknowriad** [comment] 2020-07-20 10:23
The path forward here is to use the controlled inner blocks approach for reusable blocks (like template parts).

**Comment by elliotcondon** [comment] 2020-07-20 23:08
@youknowriad Thanks for the reply, but I'm a little confused.

Can you please take a moment to watch in full the screen recordings on this page. They both describe the issue well - which is that when editing the content within a reusable block, it is not possible to edit any properties via the sidebar.

**Comment by youknowriad** [comment] 2020-07-21 07:32
@elliotcondon The fact that the reusable blocks as written today are basically an editor inside an editor makes it "impossible" to show the properties on the sidebar because at any moment in time, we have "two selected" blocks, one in  the outer editor  (the reusable block core/block)  and the  one inside the reusable block editor. In the sidebar we should the properties of the outer selected block.

With a Controlled InnerBlocks (like the template part block), you only end up with a single selected block as all blocks are now part of the same editor.

**Comment by johnstonphilip** [comment] 2020-08-19 11:53
I think I may have found an approach that works as a workaround that does not require using innerBlocks here. If you add a "focusoutside" handler to detect any clicks outside `BlockEditorProvider`, you can run `clearSelectedBlock`, which then deselects that block. That gets around the toolbar showing in places it shouldn't. However, you would also need to add another `<BlockInspector />` for the block-editor inside reusable blocks. 

Note that in order to target the right data store (since both share the `core/block-editor` name), you need to place a handling component inside `BlockEditorProvider`. That component might look something like this:

```

function ThisEditorActions(props) {
	
	// This gives us access to the "right" core/block-editor store, because this component lives inside the BlockEditorProvider.
	const { clearSelectedBlock } = useDispatch( 'core/block-editor' );

	function handleOutsideFocus() {
		if ( props.focusedOutside ) {
			clearSelectedBlock();
		}
	}

	return (
		<>
			{ handleOutsideFocus() }
		</>
	);
	
}
```

**Comment by chrisvanpatten** [comment] 2020-08-19 18:06
I think what we have in #23601 is still our best solution to this, but we're stuck until #22639 is resolved. It looks like #24180 had some discussion from @youknowriad and @noahtallen last week that seems to be moving toward consensus on a solution, so hopefully we can be in a good position to merge #23601 in the near future!

**Comment by noahtallen** [comment] 2020-08-19 19:31
> seems to be moving toward consensus on a solution

It would be very helpful to get more feedback on that PR! The code itself is not ready for review, but hopefully there is enough commentary to understand the exact issue at hand. It's fairly complex, so there are tradeoffs to many of the possible solutions. We need to come to a technical consensus before moving forward with code, I think.

**Closed** 2020-12-30 11:24 UTC
Labels: Needs Dev, [Feature] Reusable Blocks, [Type] Bug
