### ISSUE TITLE
Setting for default image on post feature image block

### ISSUE THREAD

**Issue by Olein-jp** [WordPress/gutenberg#49629] opened 2023-04-06 05:35 UTC
## What problem does this address?
When preparing article archive pages in full site editing, post feature image blocks are often utilized depending on the design.

However, currently, when a post with no feature image is displayed, it will be empty, with nothing displayed.

This is not a good design look, and there is currently no way for developers to set a default image other than by using hooks.

I think this is a very frequently used block, and if the default image can be set, and the post does not have a feature image set, I think it should automatically display that image.

**Comment by carolinan** [comment] 2023-04-06 07:14
Hi! This is a duplicate of https://github.com/WordPress/gutenberg/issues/34865; please continue the discussion there.

**Closed as completed** 2023-04-06 07:15 UTC

**Comment by Olein-jp** [comment] 2023-04-06 11:48
@carolinan I'll see that issue. Thank you!
