### ISSUE TITLE
New block editor z-index issue. Link options are hidden at the bottom of the page

### ISSUE THREAD

**Issue by 83pixel** [WordPress/gutenberg#63795] opened 2024-07-22 08:40 UTC
### Description

When you are editing text in the new block editor if your text is on the bottom of the page and you are trying to add/edit a link, the options are hidden if you have some options for example seo options. This is due to no z-index on the class .editor-visual-edit. A simple z-index: 5 will do the trick

![before](https://github.com/user-attachments/assets/5b98def8-30af-4161-9b8c-52ed0a10c6b7)

![after](https://github.com/user-attachments/assets/a9e71f25-c09b-47e0-bbc6-14f74db4af78)

### Step-by-step reproduction instructions

Go to New Post
Add a long Text
Try to add a link at a bottom text

### Screenshots, screen recording, code snippet

.editor-visual-editor {
        align-items: center;
        background-color: #ddd;
        display: block;
        height: 100%;
        isolation: isolate;
        position: relative;
        **z-index: 5;**
}

Any positive z-index will fix the problem

### Environment info

WordPress 6.6 fresh install

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by rgerhards** [comment] 2024-07-22 11:00
I can confirm this bug. It's very annoying, as I have source citations usually at the end of the posting. I  want them to open in a new window. Since a couple of updaes, this no longer is possible during link insertion, but only afterwards via the property dialog. This is now also no longer available ;-)

Work-around: add 6 blank paragraphs, edit link, delete these 6 paragraphs. Just if someone else comes across this bug.

**Comment by talldan** [comment] 2024-07-23 07:54
Thanks for reporting, though there's already an existing issue for this - #62998.

I'll close this as a duplicate.

**Closed as not planned by talldan** 2024-07-23 07:54 UTC
Labels: [Type] Bug

**Comment by stokesman** [comment] 2024-07-23 21:32
> Work-around: add 6 blank paragraphs, edit link, delete these 6 paragraphs. Just if someone else comes across this bug.

That’s a solid workaround. I did want to mention that quicker one can work given there’s enough content in the page that scrolling up will leave too little room for the popover to fit below the text. Here’s demo:

https://github.com/user-attachments/assets/96c9073a-6c35-4c93-bdda-e686df448698

Still, the bug is annoying but it might help save a little frustration.
