### ISSUE TITLE
Preview button still misbehaving

### ISSUE THREAD

**Issue by harryherbert** [WordPress/gutenberg#11966] opened 2018-11-16 09:39 UTC
after updating custom html and the pressing preview button it goes through the motions but looking at the preview it does not show the changes. The only way to see the changes after update is to ckick on view page at the top left and the go to edit page to make further changes.
this is on a bare twentysixteen theme.

**Comment by harryherbert** [comment] 2018-11-16 09:46
after updating custom html and the pressing preview button it goes through the motions but looking at the preview it does not show the changes. The only way to see the changes after update is to ckick on view page at the top left and the go to edit page to make further changes.
this is on a bare twentysixteen theme.

**Comment by designsimply** [comment] 2018-11-16 23:20
I was unable to reproduce the problem described using the following testing steps:

1. Go to Posts > Add New.
1. Add a Custom HTML block with a paragraph in it.
1. Save and publish the post.
1. Make an edit to the post to turn the color of the text red.
1. Click the "Preview" button.
1. Note whether the preview has the updated text color made just before clicking "Preview."
1. Publish the post.
1. View the post.

<strong>Result:</strong> updates made to a Custom HTML block showed up properly. ([26s](https://cloudup.com/cUmykwFwDGr), [18s](https://cloudup.com/cr-N5xKKVbg))

![custom-html-changes-do-show-up-in-a-preview](https://user-images.githubusercontent.com/1119271/48652095-09f4e280-e9bb-11e8-9d0e-878ebf603964.png)
<sup>Tested with WordPress 4.9.8 and Gutenberg 4.4 `7e814e393` and the Twenty Seventeen 1.7 theme using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment] 2018-11-30 20:49
Closing because I was unable to reproduce the problem and asking that you please re-open the issue with the details requested or to let me know if I got any testings steps wrong compared to your steps. Thank you!

**Closed by designsimply** 2018-11-30 20:49 UTC
Labels: [Status] Needs More Info
