### ISSUE TITLE
[BUG] List with links

### ISSUE THREAD

**Issue by andreamk** [WordPress/gutenberg#11707] opened 2018-11-10 11:23 UTC
**Describe the bug**
If you create a list with links you can't add a new item in list

**To Reproduce**
1. Create a new list block
2. add some item
3. add item with link
4. Pressing enter does not create a new line

This is an example html that you can use in a post content
`
&lt;!-- wp:list --&gt;
&lt;ul&gt;&lt;li&gt;item 1&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;http://testlink&quot;&gt;item 2&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;http://testlink&quot;&gt;http://testlink&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;!-- /wp:list --&gt;

&lt;!-- wp:paragraph --&gt;
&lt;p&gt;&lt;/p&gt;
&lt;!-- /wp:paragraph --&gt;
`

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome and firefox

**Additional context**
- Gutemberg 4.2

**Comment by swissspidy** [comment] 2018-11-10 11:40
Duplicate of #11606.

**Closed by swissspidy** 2018-11-10 11:40 UTC
Labels: [Block] List, [Status] Duplicate
