### ISSUE TITLE
Video block: Add support for aspect ratio control

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#66933] opened 2024-11-12 14:16 UTC
The video block does not offer much in the way of dimension tools:

![Image](https://github.com/user-attachments/assets/f21c2f73-ce60-4350-a9ad-eca10bdb5d23)

Allowing you to pick an aspect ratio would allow you to more easily combine different poster images of a different size and shape than the video itself, and still allow both to function. This use case came up as part of working on #65776.

To test, this CSS would do the trick:

```
video {
    aspect-ratio: 1/1;
}
```

**Comment by youknowriad** [comment] 2024-11-12 18:55
This seems like a duplicate of #60911

**Comment by up1512001** [comment] 2024-11-12 19:38
@jasmussen raised PR for this, can you please review 🙇‍♂ 
https://github.com/WordPress/gutenberg/pull/66946

**Comment by Mamaduka** [comment] 2024-11-13 05:30
Closing this as a duplicate of #60911.

**Closed as not planned by Mamaduka** 2024-11-13 05:30 UTC
Labels: [Type] Enhancement, [Block] Video

**Comment by jasmussen** [comment] 2024-11-13 08:23
Thanks folks for the cleanup! 🙏
