### ISSUE TITLE
[Latest Posts] not displaying excerpt when text is inside Group block

### ISSUE THREAD

**Issue by PHuhn** [WordPress/gutenberg#26706] opened 2020-11-04 19:03 UTC
**Describe the bug**

[Latest Posts] not displaying excerpt when all content is inside Group block

**To reproduce**

1. Add a new page.
2. In page Title enter Latest Posts
3. Click in the + sign and navigate to the WIDGETS group and select the **Latest Posts** block.
4. Click on the settings icon (gear) and toggle to display the Settings.
5. On the Settings panel select the Block tab.
6. On the Block panel, on **Post content settings** toggle on the **Post content**.
7. On the Block panel, select **Excerpt** radio button for **Show** option. (I am assuming you will be seeing at least the 'Hello world!' post)
8. Click the **Publish** and **Publish** again.
9. View the page
10. The 'Hello world!' post should have an excerpt. (established excerpts works)
11. Now, click on the 'Hello world!' post, it should launch the 'Hello world!' post.
12. Click edit for 'Hello world!' post.
13. Click on the paragraph text, and on the Paragraph ... menu bar and select **Group** block.
14. Click the **Publish**.
15. Click browser back button till you get to the Latest Posts page.
16. Reload the page and the 'Hello world!' post should _NOT_ have an excerpt.

**Expected behavior**

At the very least, any paragraph text should be displayed.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- No additional Gutenberg block plugins (just standard)

**Desktop (please complete the following information):**
 - OS: Window 10 Pro
 - Browser Chrome
 - Chrome Version: Version 86.0.4240.111 (Official Build) (64-bit)

**Additional context**

I originally reported this on [WordPress.org](https://wordpress.org/support/topic/2020-theme-latest-posts-not-displaying-excerpt/)

**Comment by paaljoachim** [comment] 2021-02-12 20:49
Hi @PHuhn Phil!

I followed your instructions.
Adding a paragraph into a Group block hides the text from the excerpt.

Example:
Paragraph block inside a Group block
![Screen Shot 2021-02-12 at 21 46 56](https://user-images.githubusercontent.com/5323259/107820935-ed9fa600-6d7b-11eb-863f-e92963ee5ccb.png)

Viewing the frontend of a page using the Latest Post block.
Notice the excerpt is not showing for Hello world!
![Screen Shot 2021-02-12 at 21 47 18](https://user-images.githubusercontent.com/5323259/107821008-09a34780-6d7c-11eb-84ac-15085990fb10.png)

This is a bug.

**Comment by Thelmachido** [comment] 2022-08-03 10:39
I cannot reproduce this issue as shown in the short video below since this was handled here: https://github.com/Automattic/jetpack/pull/18904


https://user-images.githubusercontent.com/41231764/182588599-528ee000-cc1c-470a-aafe-d79f6a80914a.mov

Gutenberg 13.7.3 

WordPress 6.0.1 

Closing this issue

**Closed** 2022-08-03 10:40 UTC
Labels: [Type] Bug, [Block] Latest Posts
