### ISSUE TITLE
Inserter UI disappears when i type, and it's not obvious how to get them back

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#5055] opened 2018-02-14 16:38 UTC
## Issue Overview

If you have no empty paragraph blocks, and you click out of editing the document so that is there no currently active block (e.g. click between the blocks and the right hand column of menus), the inserter and frequently used blocks are gone.

## Expected Behavior

If nothing is selected and you have no empty paragraph blocks, the inserter / frequently used blocks UI should still be visible, at the bottom of the document.

**Comment by youknowriad** [comment] 2018-02-14 22:14
Adding a design feedback as this is an intended behavior described in #4951

**Comment by jasmussen** [comment] 2018-02-22 11:12
> e.g. click between the blocks

This aspect seems like it would be mitigated with https://github.com/WordPress/gutenberg/pull/5198, correct?

> If nothing is selected and you have no empty paragraph blocks, the inserter / frequently used blocks UI should still be visible, at the bottom of the document.

Although the thread is now closed, [Matías wrote some good ideas for how we wanted to continue to refine the in-canvas inserter](https://github.com/WordPress/gutenberg/issues/5113#issuecomment-366469479):

- Maybe always show the quick blocks on the last empty block at the bottom.
- Show the quick blocks on the last empty block at the bottom on hover.
- Don’t show the ellipsis menu on an empty paragraph block.
- Consider moving + to the left, replacing the "movers" on an empty paragraph block, to emphasize the +.
- Consider showing the + with recent blocks closer to how it was but hide it all when typing.

I think all of those can be worth trying, one by one. But the first one, and probably the one to fix in order to address this particular ticket, is to look at a way to _always_ having the in-canvas appender at the end of the document. Right now, if you have 4 paragraph blocks, none of them empty, you can't click at the end of the document to start typing or inserting — you have to make a linebreak first. 

I believe this is in order to stop a tab-trap from happening. But it seems like it might be worth thinking of ways to address that. 

The next step could then be to show the recent blocks in this trailing in-canvas inserter on _hover_, and if that isn't sufficient, make them perma visible again.

**Comment by notnownikki** [comment] 2018-02-22 11:18
I'm going to stay away from design conversations as much as possible so that my experience isn't biased by my knowledge of the decisions made, so I'd like to help test any proposed solutions or WIP code, but please don't have useful inserter buttons hidden until you hover. You can't hover on mobile, and we'd just have to revisit this again.

**Comment by jasmussen** [comment] 2018-02-22 11:23
>  You can't hover on mobile, and we'd just have to revisit this again.

Well on mobile you'd set focus first, and then get access to the quick buttons. This is no different from the current mobile editor, except in the current setup you _have_ to use the toolbar insert button, as there is no in-canvas insert button. 

We're not hiding those buttons in an attempt to make it harder to insert blocks. We're trying to find the right balance, in showing just the UI you need, when you need it. Because when every UI is loud, they all drown each other out. 

Just to be super clear, we're definitely not there yet, but it's just context for why we are moving slowly with this. It's about refining the fine interactions, and we are going to make mistakes and correct along the way.

**Comment by notnownikki** [comment] 2018-02-22 11:46
I guess this issue is highlighted for me because my content is heavy on embedded content, images, audio, video, etc. and when your post's last block isn't a text one, then the flow changes.

With paragraphs, you press enter to get a new paragraph, and you're in the "commandline" where you can carry on typing. The + is visible, the recent blocks are there, all is good.

When you've just inserted an image, for example, the "commandline" disappears and it _seems_ like there's no way to carry on. It's the same when you load an existing post, too. You have to click into the end of the last paragraph and press enter to be able to start typing. Or, at least that's how it looks to someone who doesn't know the commandline is hidden at the bottom.

**Comment by SuperGeniusZeb** [comment] 2018-06-28 22:48
Related: #6834 and #7297.

**Comment by youknowriad** [comment] 2019-01-26 14:08
Anything actionable here? It seems like we can close this issue now?

**Comment by ZebulanStanphill** [comment] 2019-01-28 16:02
@youknowriad I see a couple issues coming into play here:

- Whether a block appender is shown is inconsistent between Paragraphs and every other block... even textual blocks. It really should be consistent, since having the appender sometimes appear and sometimes is confusing to users. I think fixing this is the most actionable task.
- The block appender has been in need of a redesign to be clearer and easier to use. See #10519.
- It would also be helpful if the "Add block" button in the top bar (and all the other buttons there) had a visible label on desktop (perhaps with an option to toggle showing the labels in the Options modal), to help people more easily figure out how to add a block when they can't find the sibling inserter or appender.

**Comment by ellatrix** [comment] 2020-08-20 12:26
@ZebulanStanphill Would it make sense to open separate smaller actionable issues?

**Comment by ntsekouras** [comment] 2020-12-23 12:03
Hey @ZebulanStanphill - do you think any item of your comment: https://github.com/WordPress/gutenberg/issues/5055#issuecomment-458190487, have not been addressed by all the changes in block insertion? If no, we could close this one.

**Comment by ZebulanStanphill** [comment] 2020-12-27 14:10
@ntsekouras Neither of my first two points have been addressed yet. There are a few draft PRs trying to address the second one, though: #24372 and #24926.

**Comment by paaljoachim** [comment] 2021-01-22 12:13
Can we can get a status update here?
Thank you!

**Comment by ZebulanStanphill** [comment] 2021-01-27 18:11
@paaljoachim

The appender behavior is still inconsistent for Paragraph blocks versus every other block. I tried to make a PR to change that, but I was unable to find the part of the code that controls that behavior. If anyone else wants to tackle that issue, feel free to do so.

I have a proposal for improving the inserter behavior in #13571, which would keep an inserter visible after the current block being edited. I tried implementing it in a PR as well, but it proved to be a lot trickier than I thought due to the complexity of the current inserter code, so I gave up on that for now. If anyone else wants to tackle it, be my guest.

#24926 is the closest thing to an implementation of my idea, but it's out-of-date, unfinished, and needs a new dev if it is to continue.

There are also some other inserter explorations happening in #26404.

**Comment by ZebulanStanphill** [comment] 2021-01-27 21:02
> The appender behavior is still inconsistent for Paragraph blocks versus every other block. I tried to make a PR to change that, but I was unable to find the part of the code that controls that behavior. If anyone else wants to tackle that issue, feel free to do so.

I figured out where to make the change. See #28529.

**Closed** 2021-11-24 10:19 UTC
Labels: [Type] Question, [Status] In Progress, [Feature] Inserter
