### ISSUE TITLE
Attribute with type 'object' no longer saved in the block comment delimiter

### ISSUE THREAD

**Issue by drocks13** [WordPress/gutenberg#37967] opened 2022-01-14 02:59 UTC
### Description

This is an issue with the WordPress block editor. When setting a block attribute as an object in a block, and no source, the attribute is no longer saved in the block comment delimiter when it is changed. This use to be the behavior; I am not sure when it changed but in was working in the spring of 2021. Now the object type attribute is not saved in the comment delimiter. 

I can't find any documentation on why this might have stopped worked. A possible clue, but may not be related, is in the documentation when describing attribute types it says - 'Note that the validity of an object is determined by your source.' [https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/#type-validation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/#type-validation ) . I am wondering if it has changed so objects types only work with query sources???

### Step-by-step reproduction instructions

This will be quite general as my issue is with a custom plugin but this is the process. Set any attribute as an object without a source so it should default to being saved in the block comment delimiter e.g.

`testAttribute: {
    type: 'object',
    default: {},
},`

then alter it:
`setAttributes( {testAttribute: {foo:bar} } );`

Save the post and then refresh the page - the attribute is not saved. 

Check the block in the database - no attribute is saved in the block comment.

### Environment info

Wordpress version: 5.8.3
Gutenberg: version: 12.3.2

`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No but that is just because my custom plugin where I am attempting this is active, but no other plugins.

**Comment by drocks13** [comment] 2022-01-14 13:23
A little more testing on this. The setAttributes is updating the editor data store. In the browser console, I can see all blocks with wp.data.select( 'core/block-editor' ).getBlocks() and check the attributes - they have updated in the store. However, checking the REST api request sent when I hit update shows that the attribute has not been added to the block comment delimiter. 

I can probably track down what is causing this bug but need just a little pointer in the right direction. Anyone know where the conversion to the comment delimiter occurs in the cycle so I can have a look and see what might be causing the bug? Is it not triggered until the click with a saveEntityRecord function that then does the conversion and sends the content to the REST API?

Thank you.

**Comment by drocks13** [comment] 2022-01-14 15:29
An odd short term fix to this problem is to set an empty objects when the block was created, even though the default was an empty object. Example
`
testAttribute: { type: 'object', default: '' }...... //set the default as a string to trigger a single call to set the attribute in the beginning. 

if(attributes.testAttribute == '') {
	setAttributes({testAttribute:{}});
}` 

For some reason the empty object attribute is saved in the comment delimiter. Afterwards the behavior returns to normal and all future edits to the object are saved in the comment delimiter. 

Without this initial setting it reverts back to the unexpected behavior - no updates to the post content, just to the block attributes in the local store i.e. attributes are not saved to the comments in the post. For now this fixes my problem but it is a very shaky solution and could break in the future. It would be great to figure out what is happen and get normal behavior, if anyone has any insights would love to hear them.

**Comment by dennisheiden** [comment] 2022-04-22 10:25
If I have to guess (have the same issue right now), type object is limited to what is described in the handbook, otherwise validation would be a lot harder I think. I would like to have an object with multiple values ({width, style, unit}) but that is not working right now.

What I'm going to do is to split those sub values into 3 dedicated attributes, kinda messy if you do that for responsive steps IMO.

I think type object should allow nested stuff like:

`{
type: 'object', 
default: { 
    width: { type: 'integer', default: 0 }, ...
}`

**Comment by M4N0JKUM4R** [comment] 2022-07-11 07:07
@dennisheiden I was trying ways to know how to update object via setAttributes but there is no documentation and not covered in any tutorial. For now, should we have to use the level 1 attribute way of doing that? Takes the structuring out of picture though.

**Comment by dennisheiden** [comment] 2022-07-11 08:07
> @dennisheiden I was trying ways to know how to update object via setAttributes but there is no documentation and not covered in any tutorial. For now, should we have to use the level 1 attribute way of doing that? Takes the structuring out of picture though.

```
let myObject = props.attributes.myObject;
myObject.helloText = "Hello World; 

props.setAttributes({ myObject }); or props.setAttributes({ myObject: myObject });
```

Like any other attribute. But you could use a JSON for storing objects and preventing the issue above, therefore your default would be 'string'. You also can use a local setAttributes function to prepare your data like in the v1  [Gallery Block](https://github.com/WordPress/gutenberg/blob/47bbd793ec613da0a27d9826aff7db25c6650925/packages/block-library/src/gallery/v1/edit.js).

**Comment by M4N0JKUM4R** [comment] 2022-07-11 08:59
@dennisheiden Initially it was confusing in the documentation that we should not change it directly. Still confusing :D But anyway I will try that.

![image](https://user-images.githubusercontent.com/11471878/178225910-a55fcb3a-76fc-44f4-82c5-ae499d2d0f73.png)

**Comment by M4N0JKUM4R** [comment] 2022-07-11 12:12
**Looks like this causes low performance as mentioned by @tiennguyenvan. So use it if you know what you are doing.**

@dennisheiden Another hack is to add in a dummy attribute like 'time' and update it so the editor catches the changes. The editor saved the attributes for me.


```
time: {
   type: "number",
},
```
    let localStyles = {};
    function handleLineType(value) {
		setAreaStyles((prevValue) => {
			return { ...prevValue, lineType: value };
		});
		localStyles = attributes.areaStyles;
		localStyles.lineType = value;
		setAttributes({ areaStyles: localStyles, time: Date.now() });
	}

If this dummy attribute does not work, resort to the localAttributes method which is working for all of my files.

**Comment by drocks13** [comment] 2022-07-11 12:25
@M4N0JKUM4R @dennisheiden thanks, glad to know there are a couple of other work arounds.

**Comment by dennisheiden** [comment] 2022-07-11 12:53
> @dennisheiden Another hack is to add in a dummy attribute like 'time' and update it so the editor catches the changes. The editor saved the attributes for me.

That's what I said ;):
> What I'm going to do is to split those sub values into 3 dedicated attributes, kinda messy if you do that for responsive steps IMO.

Conclusion for others:
The main issue is that attributes type object are not saved correctly (IMHO), Therefore you could either use a JSON (works very good, but you have to handle defaults and data types by yourself) or add every object property as single attribute to props.attributes (I recommend to prefix the attribute names  like "prefixSettingName", to prevent issues with other attributes.)

**Comment by tiennguyenvan** [comment] 2023-01-06 10:05
@M4N0JKUM4R 
Wow. Thanks for the hack. You saved my day. I was nearly flipping up my PC because of this issue when thinking that I will need to define thousand of variables like styleColorText, ...

**Comment by tiennguyenvan** [comment] 2023-01-06 10:59
@M4N0JKUM4R The hack creates another problem: low performance. Some controls like BorderBoxControl fires the onChange event every time we drag its range control. This causes slow performance because we have to set two attributes at the same time.

![image](https://user-images.githubusercontent.com/12868514/210999136-a9b4931d-71c7-4ae0-ba0c-04dbff640cf4.png)

**Comment by M4N0JKUM4R** [comment] 2023-01-06 11:31
> @M4N0JKUM4R The hack creates another problem: low performance. Some controls like BorderBoxControl fires the onChange event every time we drag its range control. This causes slow performance because we have to set two attributes at the same time.
> 
> ![image](https://user-images.githubusercontent.com/12868514/210999136-a9b4931d-71c7-4ae0-ba0c-04dbff640cf4.png)

Oh! I did not use that method in my code as the local attributes method was enough for me. Thanks for the warning though!

**Comment by tiennguyenvan** [comment] 2023-01-08 11:24
@M4N0JKUM4R @drocks13 
I eventually found the answer to this issue. setAttribute will only trigger if it receives a **new** object. If we change only the object's property, it is still an old object (at an old address) so setAttribute will not fire. 

To solve this, just create a deep copy of the original object and then change the property on the new object or simply use `{...valueObj}`.

Thanks to all.

**Comment by talldan** [comment] 2023-04-17 08:32
I personally couldn't reproduce the issue as described.

> I eventually found the answer to this issue. setAttribute will only trigger if it receives a new object. If we change only the object's property, it is still an old object (at an old address) so setAttribute will not fire.

Yes, it's good practice to avoid mutations in react/block code.

I'll close the issue if that was the cause of the problem.

**Closed as not planned by talldan** 2023-04-17 08:32 UTC
Labels: [Feature] Block API

**Comment by anteatersa** [comment] 2024-10-22 09:37
For anyone else struggling with this, I resolved by adding a version key to my object and setting it to a random int on every state update. 

I think react or Gutenberg is comparing the default object to the new object and only saving if different, the problem is this is only one level deep on the object attributes so in my case adding a new top level attribute and randomising resolved the issue e.g.

```
breakpoints = {
  "version" : 123456,
  "mobile" : {
    "paddingTop" : 123
  }
}
```
