### ISSUE TITLE
Recent blocks showing blocks that I've never used

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#3737] opened 2017-11-30 07:48 UTC
## Issue Overview
When I'm editing a page, the Recent Blocks tab on the Insert Block popup shows a whole bunch of blocks that I haven't used. Why is it showing all these other blocks? The only block I've actually when writing my test page was a paragraph block, but for some reason, it's indicating that I've used Images, Galleries, Heading, Button, Tables and a bunch of other blocks which I haven't touched in this post. So, the end effect is that the only block that I've actually used in this post, is hidden right down the bottom of the list, out of view, which forces me to scroll and go look for it. The whole idea of a "recent" tab is to make it easier to access the blocks that I've recently used. Adding all these other blocks that I haven't actually touched, makes this tab useless!

![screenshot_530](https://user-images.githubusercontent.com/2078245/33417686-98f655e2-d5f6-11e7-976f-9f93f1697873.png)

## Steps to Reproduce (for bugs)
1. Edit a page and add multiple paragraph blocks
2. Open the Insert Block popup and view all the other Blocks (that I haven't used) on the Recent tab

## Expected Behavior
As the name suggests, the Recent tab should only show the blocks that I've recently used within the current page. It shouldn't fill this tab up with blocks that I haven't used, or blocks that I used 3 weeks ago on a completely seperate page.

## Current Behavior
The recent tab is showing a whole bunch of blocks that I haven't actually recently used, forcing the only block that I have used, to be out of view. This in effect, makes the Recent tab useless.

## Possible Solution
Only show the blocks that I've inserted into the current page. i.e. The blocks that I've **recently** used

## Related Issues and/or PRs
#3708

_Firefox Quantum 57.0
Gutenberg Version 1.8.1
macOS Sierra 10.12.1_

**Comment by mcsf** [comment] 2017-11-30 16:28
Thanks for the report. I've had a look at this.

1. That the Recents tab should come pre-filled with blocks is a feature. In a gist, blocks deemed [common](https://github.com/WordPress/gutenberg/blob/1c53b02039be3d318350dfa08badfe90fd487af8/blocks/library/image/index.js#L20) are selected [to "top off"](https://github.com/WordPress/gutenberg/blob/1c53b02039be3d318350dfa08badfe90fd487af8/editor/reducer.js#L513-L523) the Recent panel if there aren't enough block types that the user has actually used.

2. However, there is indeed a bug in that order isn't properly preserved. I was able to repro your issue, where indeed Paragraph sits at the very end of the tab. The root cause is [the way the blocks are collected](https://github.com/WordPress/gutenberg/blob/1c53b02039be3d318350dfa08badfe90fd487af8/editor/components/inserter/menu.js#L153) to display in the tab. I'll work on a fix.

Adding to point 1), we could discuss the merits of such a decision. The way I see it, one could argue that, if a user hasn't inserted any blocks yet, perhaps a different tab should be presented instead—presumably, "Blocks" instead of "Recent". However, as soon as a user has inserted at least one block, this becomes a little awkward, as the Recent tab would be shown sporting a single block type. Thus, this hybrid approach of showing `[ ...actuallyRecent, ...commonOnes ]` seems like a reasonable way to ease the user in, and the cost of mixed semantics is acceptable.

**Comment by maddisondesigns** [comment] 2017-12-01 02:18
I like the idea that if no blocks have been inserted, then the recent tab isn't shown, and instead, you just see the Blocks tab.

I'm still of the opinion though, that once you start adding blocks to your page, the Recent tab should only display the blocks that you've used, and not get auto-populated with a bunch of other random blocks.

As I mentioned above, the whole idea of having a Recent tab is that it's supposed to show blocks that you've recently used. I don't see an issue with this tab only showing one block, if that's all they've used. As the user adds more blocks to their page, the Recent tab will populate with these blocks that they've used. I feel that auto-populating the Recent tab with a bunch of blocks that I haven't used, is confusing. If you're just going to add a bunch of random or common blocks, why even bother having the Recent tab, just have the Blocks tab and that's it.

When I'm selecting fonts in Microsoft Word, it separates your recently used fonts at the top of the menu, for easy selection. It doesn't automatically add in a bunch of extra common or adhoc fonts, it only shows the ones that I've used. If I've used one font, it only shows one font. If I've used 5, it'll show 5.

![screenshot_542](https://user-images.githubusercontent.com/2078245/33465035-aeb81b2e-d699-11e7-8ded-e48128c1d311.png)

**Comment by NewJenk** [comment] 2017-12-01 11:06
I'm with @maddisondesigns, it makes complete sense that recent blocks should only contain blocks you've actually used, with them in order of how recently they were used.

**Comment by mcsf** [comment] 2018-03-06 16:27
I feel confident closing this for now, thanks to improvements from #3742 and especially #5342.

**Closed by mcsf** 2018-03-06 16:27 UTC
Labels: [Component] Inserter

**Comment by maddisondesigns** [comment] 2018-03-07 04:59
@mcsf Can you please reopen this until I've had a chance to test the changes. Too many times issues are closed before the person who raised the issue has actually had a chance to test it. The issue then gets forgotten about because we no longer get notifications. I've lost count of the number of closed issues that I've had to ask to get reopened because the supposed "solution" didn't actually fix anything.

As far as I can see, those changes you mentioned above haven't been released in the plugin yet which means that I can't actually test to see if anythings changed.
