### ISSUE TITLE
Odd behavior when using ctlr+i to format italics

### ISSUE THREAD

**Issue by lofreqnet** [WordPress/gutenberg#13269] opened 2019-01-09 19:08 UTC
**Describe the bug**
Formatting to italics in "real time" (ie hitting ctrl+i before typing a word or passage, hitting again to end italics) results in buggy behavior. Going into italics mode is fine, but coming back into the default format within a single block of text results in the cursor jumping back a character and "hiding" it as sometimes is the case with punctuation or deleting it altogether in the case of a space, or on one occasion, jumping to the beginning of the block/paragraph, and never releasing the italics formatting. To return to the default, I must highlight the word I don't want italicized and hit ctrl+i or hit ctrl+i twice, replace the deleted character, and then may continue typing as normal. I'm using the latest version of Wordpress and I've tested this in the Brave and Chrome browsers (both are based on Chromium).

**To Reproduce**
1. Open up the Gutenberg editor.
2. Start typing in italics.
3. Hit ctrl+i after hitting the space bar.
4. See bug.

**Desktop (please complete the following information):**
 - Win 8
 - Brave, Chrome
 - Brave version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit) / Chrome version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
- Using latest (5.0.3) version of Wordpress.

**Comment by designsimply** [comment] 2019-01-10 02:19
Tested with WordPress 5.0.3 using Chrome 71 on Windows 8 and confirmed that pressing space then `ctrl+i` results in the space getting deleted and the caret landing inside the inline boundary instead of outside of it as expected.

![13269-25s](https://user-images.githubusercontent.com/1119271/50941774-674d6300-1443-11e9-97aa-ec201e5ee1a0.gif)

**Comment by lofreqnet** [comment] 2019-01-10 20:22
A tangential issue revealed in the @designsimply gif above is why italicized text moves to a new line instead of wrapping inline with default formatted text...

**Comment by iseulde** [comment] 2019-02-08 09:39
Sounds like a duplicate of #12529.

**Closed by iseulde** 2019-02-08 09:39 UTC
Labels: [Package] Rich text, [Type] Bug
