### ISSUE TITLE
Preview: Selecting other than Desktop will make admin bars visible.

### ISSUE THREAD

**Issue by kwight** [WordPress/gutenberg#21001] opened 2020-03-18 20:43 UTC
**Describe the bug**
The editor defaults to fullscreen on desktop, but when I go to preview in another screen size, the WP Admin sidebar and admin bar pop into view. They go away once choosing "desktop" again.

![2020-03-18 13 35 41](https://user-images.githubusercontent.com/349751/77005378-f0044080-691d-11ea-8c3e-e352b4beda04.gif)

**To reproduce**
1. Start a new post.
2. Enter content to activate the preview dropdown.
3. Select anything other than Desktop under the preview dropdown.
4. Notice the admin bars pop into view.

**Expected behavior**
Admin bars should not be visible while in fullscreen mode, regardless of preview mode.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80.0.3987.132
 - clean install of Gutenberg repo on master with built-in WordPress install

**Comment by youknowriad** [comment] 2020-03-18 20:46
Duplicate of https://github.com/WordPress/gutenberg/issues/20991

**Closed by youknowriad** 2020-03-18 20:46 UTC
