### ISSUE TITLE
Gallery: uploaded image not available in Edit view

### ISSUE THREAD

**Issue by eliorivero** [WordPress/gutenberg#10877] opened 2018-10-21 16:34 UTC
### Context
While authoring a post, I added an image gallery. Shortly afterwards, I wanted to add one more image to the gallery and rearrange the items.

### Expectations

Since Edit is available after uploading an image, I hoped to be able to rearrange the items as soon as the image was uploading–or at least after it was uploaded–without having to save and reload the page.

### Reality

Right after adding a gallery block and adding the images, I realized there was another one I wanted to add. I clicked the button **Upload an image** and uploaded it.
Since it was instantly visible in the editor, I wanted to re-arrange the thumbnails, so I clicked the pencil to edit the gallery. To my surprise, the image wasn't there.
I waited briefly until it was uploaded and tried one more time. Again, the image wasn't there.
I saved and reloaded, and this time the image was shown in the gallery edit mode.
All this can be seen in the gif below.

![gallery-edit](https://user-images.githubusercontent.com/1041600/47269543-b5825280-d535-11e8-941c-c1c13bf1cf87.gif)

**Comment by youknowriad** [comment] 2018-10-21 16:40
Seems like a duplicate of #9073

**Closed by youknowriad** 2018-10-21 16:40 UTC
