### ISSUE TITLE
White space / gap above (Youtube) videos

### ISSUE THREAD

**Issue by ChampagneCoffee13** [WordPress/gutenberg#29408] opened 2021-02-27 21:56 UTC
## Description
I am using Ocean WP theme with an elementor template (used across all posts) and then I enter the post content via the wordpress editor. There is a hg gap between all Youtube videos (added via URL) and I cannot figure out hoe to remove them.

## Expected behaviour
They should display how they do in the backend, with about a 1cm gap but I am seeing a 15cm gap (approx), front end.

## Screenshots or screen recording

https://prnt.sc/108t5zg
https://prnt.sc/108t6i2
https://prnt.sc/108t7ip

## WordPress information
- WordPress version: 

Version | 5.6.2

- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Active: OceanWP.

## Device information
- Device: Desktop, Mac, Chrome and Safari

**Comment by ChampagneCoffee13** [comment] 2021-02-27 21:57
There is a similar closed thread here https://github.com/WordPress/gutenberg/issues/10109

**Comment by talldan** [comment] 2021-06-08 05:43
Hi @ChampagneCoffee13. Thanks for reporting this, and apologies it took a few months for someone to look at this.

The embed was tested during a triage session in slack (https://wordpress.slack.com/archives/C02QB2JS7/p1623130185369500). Two of us couldn't reproduce the issue using Ocean WP. It may have been fixed by some recent changes to the embed block, like https://github.com/WordPress/gutenberg/pull/29510.

I'll close the issue.

**Closed by talldan** 2021-06-08 05:43 UTC
Labels: Needs Testing, [Block] Embed
