### ISSUE TITLE
Allow filtering alignment option for `core/image` block

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34316] opened 2021-08-26 08:01 UTC
`core/image` is the only core block that doesn't allow filtering the alignment controls it exposes to users.

This block is using the `BlockAlignmentControl` control [directly](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/edit.js#L330) instead of the [the align hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/align.js#L147) that's enabled via block supports. Unlike the align hook, the `core/image` block doesn't pass the allowed controls to the `BlockAlignmentComponent`, hence, it'll show all of them.

It sounds like the alignment options of `core/image` should be filterable as any other block. Ideally, it should use the align hook as well.

**Comment by fabiankaegy** [comment] 2022-10-04 07:28
This is a duplicate of #19103

**Closed as completed by fabiankaegy** 2022-10-04 07:28 UTC
Labels: [Block] Image
