### ISSUE TITLE
Multiple NUX tips when using nested blocks

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#8382] opened 2018-08-02 07:42 UTC
After installing Gutenberg 3.4.0 and opening a post with the columns block, multiple (identical) NUX tips appear. Closing one closes all. And they don't particularly seem connected to what they're describing. I'd expect this one to be on the inserter button.

<img width="1548" alt="screen shot 2018-08-01 at 10 51 29" src="https://user-images.githubusercontent.com/6073772/43569510-f4e18ba4-9637-11e8-97f5-499cb06985b7.png">

 - MacOS High Sierra 10.13.5
 - Chrome 68.0.3440.84
 - WordPress 4.9.7
 - Gutenberg 3.4.0

**Comment by designsimply** [comment] 2018-08-02 13:56
Thank you for the report! The nested blocks detail is helpful.

Closing as a duplicate of #8285.

**Closed by designsimply** 2018-08-02 13:56 UTC
Labels: NUX, [Component] Nested / Inner Blocks, [Status] Duplicate, [Type] Bug
