### ISSUE TITLE
Blank Post Screen in Editing Mode

### ISSUE THREAD

**Issue by mamabearscookbook** [WordPress/gutenberg#9222] opened 2018-08-22 03:18 UTC
Since the most recent Gutenberg update (3.6.2) I have no access to my posts in editing mode. They still appear when you visit my site, but I have zero access to them in the editing mode. The screen in blank. I had to deactivate the Gutenberg plugin to gain access to edit my posts.

-safari version 11.1.2

**Comment by designsimply** [comment] 2018-08-22 18:04
It's hard to say what might be causing this in your case without more information. Are you able to try turning Gutenberg back on and then checking the browser console to see if you can find any errors there at the time a blank screen happens for you?

**Comment by mamabearscookbook** [comment] 2018-08-22 19:53
How do I check the browser console?

**Comment by mamabearscookbook** [comment] 2018-08-22 19:59
okay I figured out the browser console, then activated the Gutenberg plugin and went to my posts. A whole bunch of error were in the browser console

**Comment by mamabearscookbook** [comment] 2018-08-22 20:00
![screen shot 2018-08-22 at 12 58 27 pm](https://user-images.githubusercontent.com/42596437/44487521-56729100-a60b-11e8-9856-7c3ad2f0eed5.png)

**Comment by designsimply** [comment] 2018-08-22 22:18
Thank you for finding that! I'm including a copy of the errors in text for reference:

```
TypeError: Vo.rawShortcut.primaryAlt is not a function. (In 'Vo.rawShortcut.primaryAlt("backspace")', 'Vo.rawShortcut.primaryAlt' is undefined)
TypeError: undefined is not an object (evaluating 'wp.editor.RichText')
TypeError: Object($.withColors) is not a function. (In 'Object($.withColors)("backgrounndColor",{textColor:"color"})', 'Object($.withColors)' is an instance of Object)
TypeError: undefined is not an object (evaluating 'c.registerCoreBlocks')
Error: only one instance of babel-polyfill is allowed
```

I am not 100% sure but it seems to me there might be a plugin conflict between the editor and something else. Typically, the next troubleshooting step for that would be to temporarily deactivate all other plugins besides Gutenberg and then check to see if the problem still happens. If it does not, turn each plugin back on one-by-one until you find the conflict. Note that the theme can also be the source of a conflict and temporarily switching to the default theme is how to rule that out. Any chance you would be willing to give those troubleshooting steps a try? If that's not possible, listing your plugins here would be a good next step to see if someone else experiencing the same problem can verify if they have a plugin or theme conflict.

**Comment by mamabearscookbook** [comment] 2018-08-23 02:50
I am not very tech savvy, so am not comfortable deactivating my plugins or switching themes. I will the current plugins I have activated. 
Akismet Anti-Spam
Another MailChimp Widget
Cookie Consent
Google Analytics for WordPress by MonsterInsights
Insert Headers and Footers
Insert Post Ads
Jetpack by WordPress.com
MailChimp for WordPress
Meks Smart Author Widget
Really Simple SSL
Redirection
Remove Query Strings
Simple Share Buttons Adder
UpdraftPlus - Backup/Restore
WP Fastest Cache
WP Recipe Maker
WPForms Lite
Yoast SEO

**Comment by designsimply** [comment] 2018-09-15 00:30
I tested by installing each of the plugins you listed one-by-one and checking to see if both a new post and editing an existing post opened normally and all of them did in my case.

![screen shot 2018-09-14 at 6 22 24 pm](https://user-images.githubusercontent.com/1119271/45580147-281f5480-b84b-11e8-8ca3-7c4b8b58b562.png)
<sup>Tested with WordPress 4.9.8 and Gutenberg 3.9.0-rc.1 using Safari 11.1.2 on macOS 10.13.6.</sup>

The top results in a [plugin search](https://wordpress.org/plugins/search/Remove+Query+Strings/) for "Remove Query Strings" return more than one result with similar names. I tested the one by "Speed Up My Website." Here are the top two which look very similar, which one do you have installed?

1. https://wordpress.org/plugins/remove-query-strings-from-static-resources/
2. https://wordpress.org/plugins/remove-query-strings-littlebizzy/

I couldn't find an exact match for "WPForms Lite" at https://wordpress.org/plugins/search/WPForms+Lite/ so I didn't test that one.

Here are the plugins I tested:

Akismet Anti-Spam 4.0.8
Another MailChimp Widget 2.0.6
Cookie Consent 2.3.11
Google Analytics for WordPress by MonsterInsights 7.1.0
Gutenberg 3.9.0-rc.1
Insert Headers and Footers 1.4.3
Insert Post Ads 1.3.2
Jetpack by WordPress.com 6.5
MailChimp for WordPress 4.2.5
Meks Smart Author Widget 1.1.1
Plugins List 2.4.3
Really Simple SSL 3.0.5
Redirection 3.4.1
Remove Query Strings From Static Resources 1.4
Simple Share Buttons Adder 7.4.18
UpdraftPlus - Backup/Restore 1.15.0
WP Fastest Cache 0.8.8.4
WP Healthcheck 1.3.1
WP Recipe Maker 3.2.1
Yoast SEO 8.2

I noticed that some of the plugins in your list have been updated recently. If you are still having trouble, would you please check to make sure all of your plugins have been updated to the latest available versions, including Gutenberg (3.8 at the time of this writing)?

I see that you have a caching plugin. Could you try purging cache and testing again? Could you also try clearing local browser cache as a troubleshooting step to rule out something funky going on with that?

If you're still having trouble after that, could you note your theme name and version and if possible include the scripts you're using in the Insert Headers and Footers plugin? Maybe something in those is the source of a conflict?

I'm going to close this for now, and we can continue the discussion even though the issue is closed.

**Closed by designsimply** 2018-09-15 00:30 UTC
Labels: Needs Testing, [Status] Needs More Info, [Type] Help Request

**Comment by designsimply** [comment] 2018-09-18 19:04
@mamabearscookbook were you able to try clearing browser cache and cookies and did that help?

If you are uncomfortable disabling all plugins for testing, would you be able to try disabling just a few of the ones most-likely to have a conflict and then test editing posts again after you purge cache? Consider temporarily disabling Insert Headers and Footers (because I am not sure how that one is being used in your case) and WPForms Lite (since I didn't find that one downloadable for testing on my side).

Because I don't recognize the first error message reported in your browser console, it feels like a plugin conflict is the most likely cause of the trouble in this case.

**Comment by mamabearscookbook** [comment] 2018-09-19 02:37
Hey sorry I've had a family emergency and have not been able to work on these issues. I have been using Wordpress without the Gutenberg plugin activated. There have been quite a few updates since deactivating it, so I just went and activated the Gutenberg plugin and now it works! So it must have been a plugin conflict like you assumed.

**Comment by designsimply** [comment] 2018-09-19 17:44
No worries at all! My thoughts are with you for the family emergency.

Aha! Thanks tons for checking it again. There's a goal in place to turn around these `Needs Testing` issues more quickly and hopefully that will help us catch things like this faster. Glad to hear it's working now and thank you again for writing in earlier!

**Comment by shznaqvi** [comment] 2018-09-22 13:39
I am have Blank screen with latest version 3.9.0.

Here are the errors from my browser console:

JQMIGRATE: Migrate is installed, version 1.4.1
wp-polyfill-ecmascript.min.2ae96136.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js?ver=1537622800:50 Uncaught ReferenceError: regeneratorRuntime is not defined
    at index.js?ver=1537622800:50
    at Object.<anonymous> (index.js?ver=1537622800:50)
    at n (index.js?ver=1537622800:1)
    at index.js?ver=1537622800:1
    at index.js?ver=1537622800:1
index.js?ver=1537622800:12 Uncaught TypeError: Object(...) is not a function
    at Object.216 (index.js?ver=1537622800:12)
    at n (index.js?ver=1537622800:1)
    at wp.blockLibrary.0 (index.js?ver=1537622800:1)
    at index.js?ver=1537622800:1
index.js?ver=1537622800:12 Uncaught TypeError: Cannot read property 'getBlockSelectionStart' of undefined
    at index.js?ver=1537622800:12
    at Ge (index.js?ver=1537622800:12)
    at Array.INIT (index.js?ver=1537622800:12)
    at Object.dispatch (index.js?ver=1537622800:1)
    at Object.217 (index.js?ver=1537622800:12)
    at n (index.js?ver=1537622800:1)
    at wp.editPost.0 (index.js?ver=1537622800:1)
    at index.js?ver=1537622800:1
post-new.php:4729 Uncaught TypeError: Cannot read property 'initializeEditor' of undefined
    at HTMLDocument.<anonymous> (post-new.php:4729)

**Comment by shznaqvi** [comment] 2018-10-18 03:57
No. Even after updating other plugins several times. So, I deactivated gutenberg

**Comment by designsimply** [comment] 2019-02-08 21:01
> wp-polyfill-ecmascript.min.2ae96136.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Circling back to note that this file name turned out to be problematic because a version of it had been blocked by some types of server security rules in the past. It should have been fixed as part of this changeset: https://core.trac.wordpress.org/changeset/44261.

If you are still having trouble and see this error:

> wp-polyfill-ecmascript.min.2ae96136.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Please contact your web host and ask them to help you find out if the file in question is being blocked by any security rules on the server side. Please let them know the exact error message and the latest version of WordPress you have tested and verified the problem for. Thank you!
