### ISSUE TITLE
Alert the editor when trying to leave the Site Editor with unsaved changes

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#24209] opened 2020-07-26 17:10 UTC
**Is your feature request related to a problem? Please describe.**
When using the Site Editor, sometimes I might click on the wrong place and leave the editor, withour being alerted that I have unsaved changes and asked whether I want to proceed or cancel, which results in my latest edition being lost.

**Describe the solution you'd like**
It would be very helpful to display the same browser-native popup that opens when trying to leave the page/post editing page with unsaved changes, so that the editor can confirm or cancel.

**Comment by ehti** [comment] 2020-07-28 14:10
Hmm, yep, for the unsaved changes there doesn't appear to be a warning/popup if you navigate away.

I'm not sure if it's by design, but let's get feedback from the design folks on it!

**Comment by noahtallen** [comment] 2020-07-28 22:53
Definitely not intentional to not have it yet -- just hasn't been implemented!

**Comment by ehti** [comment] 2020-08-04 09:24
Thanks!

I guess the feedback label can be removed - going ahead with it.

**Comment by david-szabo97** [comment] 2020-08-19 12:11
I'll give this one a try 😄

**Comment by ockham** [comment] 2020-08-20 14:28
Closed by https://github.com/WordPress/gutenberg/pull/24659 :slightly_smiling_face:

**Closed by ockham** 2020-08-20 14:28 UTC
Labels: [Feature] Full Site Editing, [Type] Enhancement
