### ISSUE TITLE
Legacy widget: Text widget results in javascript error

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#33203] opened 2021-07-05 16:15 UTC
## Description

The legacy text widget, use the tinymce error. If you have a text widget from the old widget editor then go to the new widget screen, this generates a javascript error. 

```
TypeError: wp.editor.initialize is not a function
    at buildEditor (text-widgets.js?ver=5.7.2:265)
    at n.initializeEditor (text-widgets.js?ver=5.7.2:359)
    at renderWhenAnimationDone (text-widgets.js?ver=5.7.2:434)
    at HTMLDocument.handleWidgetAdded (text-widgets.js?ver=5.7.2:437)
    at HTMLDocument.dispatch (jquery.js?ver=3.5.1:5429)
    at HTMLDocument.elemData.handle (jquery.js?ver=3.5.1:5233)
    at Object.trigger (jquery.js?ver=3.5.1:8715)
    at HTMLDocument.<anonymous> (jquery.js?ver=3.5.1:8793)
    at Function.each (jquery.js?ver=3.5.1:381)
    at jQuery.fn.init.each (jquery.js?ver=3.5.1:203)
```

## Step-by-step reproduction instructions
1. Activate classic widgets plugins. 
2. Insert text widget 
3. Add some text to widget. 
4. Deactivate classic widgets plugins.
5. Go to widget screen. 
6. See error. 

## Expected behaviour

No error message and the tinymce editor should be displayed. 

## Screenshots or screen recording (optional)

<img width="1904" alt="Screenshot 2021-07-05 at 17 12 36" src="https://user-images.githubusercontent.com/237508/124498441-3f40df80-ddb4-11eb-99e1-581b287f96de.png">

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by draganescu** [comment] 2021-07-05 17:18
Testing this on the current 5.8 branch or WordPress `master` and I cannot repro, with or without Gutenberg active.
The problem appears on WordPress 5.7.2 and possibly earlier.

**Comment by spacedmonkey** [comment] 2021-07-05 21:13
I am seeing a similar error WP 5.9-alpha without the gutenberg plugin. 

<img width="1884" alt="Screenshot 2021-07-05 at 22 08 42" src="https://user-images.githubusercontent.com/237508/124518378-22b99d00-ddde-11eb-921d-75a6b6b1d075.png">

**Comment by tellthemachines** [comment] 2021-07-06 00:27
I can reproduce this on WP 5.7.2 with the latest from this repo, but not on 5.9-alpha-51272-src with or without the Gutenberg plugin.

**Comment by noisysocks** [comment] 2021-07-06 03:42
Moved this to the post-5.8 grab bag ("Maybe later") as it's not affecting 5.8.

**Comment by kevin940726** [comment] 2021-07-06 04:40
I believe the problem is that the Text Widget is using trying to call [`wp.editor.initialize` in `text-widgets.js`](https://github.com/WordPress/wordpress-develop/blob/7026369035d0632f670d7dd618a797bbcbb413ec/src/js/_enqueues/wp/widgets/text.js#L240), where `wp.editor` is defined in [`base.js`](https://github.com/WordPress/wordpress-develop/blob/7026369035d0632f670d7dd618a797bbcbb413ec/src/js/_enqueues/wp/editor/base.js#L8). However, Gutenberg also injects `wp.editor` global variable from the `editor` package, hence override the value.

Seems like we already have solved this before by reassigning it to [`wp.oldEditor`](https://github.com/WordPress/wordpress-develop/blob/7026369035d0632f670d7dd618a797bbcbb413ec/src/wp-includes/script-loader.php#L378-L383). All we have to do is to change every occurrence of `wp.editor` to `wp.oldEditor` in `text-widgets.js` and the error should go away. And also the editor should display as expected:

![image](https://user-images.githubusercontent.com/7753001/124543130-41a84580-de57-11eb-86a5-00813d121ff9.png)

**Comment by adamziel** [comment] 2021-07-06 15:54
> Moved this to the post-5.8 grab bag ("Maybe later") as it's not affecting 5.8.

I think it is affecting 5.8.

There may be more problems here, but one originates in Jetpack when it is enabled in the latest WP 5.8 version, with or without the gutenberg plugin. Specifically, here:
```
wp_enqueue_script(
   'jetpack-blocks-editor',
   $editor_script,
   $editor_deps,
   $version,
   false
);
```

`$editor_deps` comes from `plugins/jetpack/_inc/blocks/editor.asset.php` which lists 26 different scripts including `wp-edit-post` and `wp-editor`. As soon as I comment them both out, everything works like a charm.

On the surface, this could be seen as a Jetpack problem so let me cc @jeherve and @kraftbj.

If we look deeper, however, this could be a common situation among many plugins and we should address it somehow. A somewhat naive solution could be to update `text-widgets.js` (and anything else) in core to first look for `wp.oldEditor` and only fall back to `wp.editor` if the former is not there. I said naive, because some plugins may rely on `wp.editor` and there isn't much we can do there. CCing @draganescu, @noisysocks, @getdave, @talldan – what do y'all think?

**Comment by adamziel** [comment] 2021-07-06 16:02
I just had the worst idea ever, but it could just solve this issue once and for all :D The problem is that we have two different sets of expectations in regard to what resides under the name `wp.editor`. Part of the code expects to find a _module_:

<img width="317" alt="Zrzut ekranu 2021-07-6 o 17 59 31" src="https://user-images.githubusercontent.com/205419/124631711-efc9e480-de83-11eb-8564-ff43726f5156.png">

While the rest of the code expects to find a legacy editor object with a few specific keys available:

<img width="445" alt="Zrzut ekranu 2021-07-6 o 18 00 11" src="https://user-images.githubusercontent.com/205419/124631822-08d29580-de84-11eb-8485-0583d500ebe8.png">

What if, instead of trying to match the right object with the right code, we just _fuse the two together_? So `wp.editor` would expose all the exported members of the module **as well as** all the members of wp.oldEditor?

**Comment by spacedmonkey** [comment] 2021-07-06 16:07
Sharing for visibility. A quick search on WordPress plugin directory for [wp.editor.initialize](https://wpdirectory.net/search/01F9Y8K963004JWYGWY0XQ3MKM) brings up a lot of results. Not all of these will spin up tinymce in widget screen. But two popular ones seem too. [SiteOrigin Widgets Bundle](https://wordpress.org/plugins/so-widgets-bundle/) and [Page Builder by SiteOrigin  ](https://wordpress.org/plugins/siteorigin-panels/). SiteOrigin Widgets Bundle with 900k downloads. Not to mention Jetpack 5+ million downloads. 

Worth testing against Jetpack and these plugins....

**Comment by adamziel** [comment] 2021-07-06 16:16
Great idea checking the plugin directory @spacedmonkey! This shows that we need a solution that's compatible with both the widgets editor and all the existing code. I just proposed one in https://github.com/WordPress/gutenberg/pull/33228

**Comment by noisysocks** [comment] 2021-07-07 04:20
This is a related issue: https://core.trac.wordpress.org/ticket/53569

I wonder if we could add code to Core that warns against enqueueing `wp-edit-post` and `wp-editor` in the widgets screen?

**Comment by adamziel** [comment] 2021-07-07 10:52
Here's a PR proposing a very similar approach, but without touching the `@wordpress/editor` package: https://github.com/WordPress/wordpress-develop/pull/1481
Also, there's another related issue: https://core.trac.wordpress.org/ticket/53437

**Comment by noisysocks** [comment] 2021-07-08 01:48
Let's go with https://github.com/WordPress/wordpress-develop/pull/1481. Closing this.

**Closed as completed by noisysocks** 2021-07-08 01:48 UTC
Labels: [Feature] Widgets Screen, [Block] Legacy Widget
