### ISSUE TITLE
Auto border on Images and Gallery affecting alignment in twenty eleven

### ISSUE THREAD

**Issue by snighole** [WordPress/gutenberg#12035] opened 2018-11-18 15:37 UTC
A border is automatically added when using Guttenberg image and gallery blocks when using twenty eleven, however is not added with other themes. The border spoils the alignment on the post. Not sure if this is a bug or something I can get rid of?

eg 
![image](https://user-images.githubusercontent.com/38671596/48674754-b532a280-eb47-11e8-8f32-663ce17e0abe.png)

The example gallery is aligned different to the one I created, and always is

Thanks

**Comment by GlennMartin1** [comment] 2018-11-29 13:34
This is a bug that affects other themes as well, not only Twenty-Eleven.

Storefront theme is addressing it themselves, but it should really be fixed in Gutenberg core. 

See https://github.com/woocommerce/storefront/issues/1005

**Comment by designsimply** [comment] 2019-02-01 00:09
Closing because I tested with Twenty Eleven version 3.1 and did not see the problem. 

![screen shot 2019-01-31 at 5 05 38 pm](https://user-images.githubusercontent.com/1119271/52094060-cd2c9680-257a-11e9-8283-2cb56703a89a.png)
<sup>Twenty Eleven 3.1 on the left and Twenty Seventeen 2.0 on the right. Tested with WordPress 5.0.3 on Firefox 64.0.2 on macOS 10.13.6.</sup>

@snighole or @GlennMartin1 if this problem is still happening for you and you have confirmed you've updated to the latest version of the Twenty Eleven theme (currently 3.1), please leave a comment here and I can help make sure it gets sorted whether that means checking to see if Gutenberg still needs to make a change or if this should go to the theme author to address at that level. Thank you!

**Closed by designsimply** 2019-02-01 00:09 UTC
Labels: Needs Testing, [Type] Help Request
