### ISSUE TITLE
Incorrect Author Shown in UI when user is no longer on the site

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#46558] opened 2022-12-14 21:46 UTC
### Description

If a Post was written by a user who is no longer on the site (or never was, in the case of a MultiSite Network Admin), the Post Author dropdown shows the first user alphabetically.  "Update" doesn't actually update the author to the one in the dropdown, but if you CHANGE the author to an existing user, then it will update.

### Step-by-step reproduction instructions

1. Be a Network Admin on MultiSite, where a site has another user but you do not have a user account on that site
2. Publish a Page
3. See that the All Pages list indicates you are the author (as does the database)
4. Go to Edit the Page, and see that the 'Author' dropdown displays the first user on the site
5. If you like, click 'Update' and see that you are still the author.

Alternatively
1. Have someone Publish a page.
2. Remove that user from the site.
3. Edit the Page, and see that the first alphabetical user will be shown as the Author in the dropdown (just like above)

### Environment info

6.1.1, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment] 2022-12-20 16:19
I have been able to confirm this in 6.1 and in Gutenberg trunk. 

Post author is set to `admin` who is the Network admin and is not actually a user of this site. 
![image](https://user-images.githubusercontent.com/4832319/208714254-7dbe8bbf-4ad9-4a6b-a2ea-3503afaab12c.png)

In the Editor, the Author field defaults to the first author (alphabetically) that is available on the site, which in this case is `test`. 
![image](https://user-images.githubusercontent.com/4832319/208714531-7510abd5-3362-4255-90d8-eb04e1f6e4d9.png)

**Comment by krokodok** [comment] 2023-07-17 07:47
I experience the same on my multisite, with the difference, that the Author dropdown does not render at all instead of showing the first user.

**Comment by iandunn** [comment] 2023-10-05 19:14
I think this is a duplicate of #11000 / https://core.trac.wordpress.org/ticket/50754, but we can re-open if there's something distinct about this.

**Closed as completed by iandunn** 2023-10-05 19:14 UTC
Labels: [Type] Bug, [Feature] Document Settings
