### ISSUE TITLE
Sidebar animation: Content area scrollbar jumps over before the animation completes

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#13926] opened 2019-02-18 14:55 UTC
**Describe the bug**

As noted by @afercia in https://github.com/WordPress/gutenberg/pull/13635#issuecomment-464349294, On systems that show scrollbars at all times, the scrollbar for the main content area does not slide over nicely when the sidebar animation occurs. Instead, it jumps over immediately, resulting in an empty white box that the sidebar animates into. 

**Screenshot**
_(The frame rate has been slowed down here to show the effect)_

![](https://user-images.githubusercontent.com/1202812/52957437-aa162b00-335f-11e9-9da8-81a872c196ae.gif)

**Comment by karmatosed** [comment] 2019-02-18 22:16
I am fairly sure this is a regression. Would be great to get fixed.

**Comment by kjellr** [comment] 2019-02-19 13:33
I haven't tested, but I imagine this would've been fixed by #13831 if we'd been able to get that animation to be more consistently performant.

**Comment by mapk** [comment] 2019-06-04 16:26
I've removed the "Needs Design Feedback" because yes, let's get this fixed. Great find here, Kjell.

**Comment by cpapazoglou** [comment] 2020-09-18 16:05
I can't reproduce it anymore in : 
- Mac Safari (with scrollbars always visible)
- Mac Chrome (with scrollbars always visible)
- Windows IE 11

**Comment by paaljoachim** [comment] 2021-02-21 17:46
Hi @kjellr 

I am not seeing this any longer, and will close this issue.
Please reopen if I am mistaken.

**Closed by paaljoachim** 2021-02-21 17:46 UTC
Labels: Needs Dev, [Type] Bug
