### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by jasonpoon89** [WordPress/gutenberg#11413] opened 2018-11-02 15:09 UTC
Normal font size doesn't work properly. Whenever it is selected, it does not become size 16 (which is what it is for my website). Instead, it becomes a size 9. I typed in 16 manually and the size automatically becomes normal. So to combat this, I have to manually set all the fonts to 17, one size up from normal size.

**Comment by chrisvanpatten** [comment] 2018-11-02 15:53
Another argument for #10687…

**Comment by designsimply** [comment] 2018-11-02 22:45
I tested using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 and the Twenty Seventeen 1.7 theme with Firefox 63.0 on macOS 10.13.6 and did not have the same experience. In my test, I added a paragraph block in the editor, left the size set to "Normal" which is the default, and then used the Inspector in developer tools for the browser to check the font size and it appears to be 16px in my case:

![screen shot 2018-11-02 at 1 35 49 pm](https://user-images.githubusercontent.com/1119271/47944000-a351ce00-debe-11e8-9f6e-bcbde3bfe9a2.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15471&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

![screen shot 2018-11-02 at 1 38 56 pm](https://user-images.githubusercontent.com/1119271/47944003-a77deb80-debe-11e8-832d-c923c4336745.png)
<sup>Seen at http://alittletestblog.com/2018/11/02/title-8/ running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

May I ask what theme you are using?

May I ask what OS and browser version you are using and whether you have made any changes to your browser's font settings?

**Comment by chrisvanpatten** [comment] 2018-11-09 14:05
I've opened #11671, which discusses the problem of numeric sizes always mapping to named sizes. This is also technically a duplicate of #8689.

To consolidate and simplify, I'm going to close this ticket and strongly recommend following #11671. I definitely want to make this better!

**Closed by chrisvanpatten** 2018-11-09 14:05 UTC
Labels: Customization, [Status] Needs More Info
