### ISSUE TITLE
Cut and paste list item into another list item fails

### ISSUE THREAD

**Issue by pansamolot** [WordPress/gutenberg#32980] opened 2021-06-25 07:38 UTC
Quite very similar to #32467 but has different results.

## Description

Copying and pasting a list item into another empty list item fails. Both pressing _Ctrl+V_ and selecting _Paste_ from context menu gives no effects. Pasting the very same copied element into a paragraph or into new empty non-list block works just fine.

## Step-by-step reproduction instructions

1. Select any list item in the block editor (either from ordered or unordered list), select entire line
2. Hit _Enter_ **once** in the same line to create a new empty list item
3. Move cursor to that new line / new list item
4. Paste copied text

![one](https://user-images.githubusercontent.com/60975060/123387990-a1ba0480-d598-11eb-87c8-135445e25a0a.gif)

To compare:

1. Select any list item in the block editor (either from ordered or unordered list), select entire line
2. Hit _Enter_ **twice** in the same line to end current list and create new empty block (paragraph)
3. Move cursor to that new line
4. Paste copied text

![two](https://user-images.githubusercontent.com/60975060/123388029-aaaad600-d598-11eb-9817-82df4a39bb29.gif)

## Expected behaviour

Text is correctly copied in both scenarios.

## Actual behaviour

Text is correctly copied only in second (compare) scenario. In first (base) scenario pasting brings no effect.

## WordPress information
- WordPress version: _5.7.2_
- Gutenberg version: _Version 10.9.0 | By Gutenberg Team_
- Are all plugins except Gutenberg deactivated? _No_
- Are you using a default theme (e.g. Twenty Twenty-One)? _No_

## Device information
- Device: _PC_
- Operating system: _Windows 10 10094_
- Browser: _Chrome Version 91.0.4472.114_

**Comment by skorasaurus** [comment] 2021-06-25 16:45
Hi, 

Thanks for reporting. I think this may have been fixed just a couple days ago with https://github.com/WordPress/gutenberg/pull/32527 

I downloaded the nightly version of gutenberg, released on a daily basis that includes all published changes and I am unable to reproduce the that you described in your first scenario. It pasted as expected. 

If you download the newest Gutenberg nightly from https://gutenbergtimes.com/need-a-zip-from-master/#nightly ; do you have the same issue?

**Comment by pansamolot** [comment] 2021-06-25 16:50
Hi @skorasaurus,

Thanks for a feedback. Sorry, but I don't have any kind of dev-like environment to test nighties from Gutenberg or any other plugins. Must wait for the official release instead in order to confirm.

If you cannot reproduce this bug in nightly, which I was able to reproduce using official then most likely you're right that this bug has been fixed. Thank you.

**Comment by skorasaurus** [comment] 2021-06-25 16:53
I understand, thanks for your prompt response : ) That fix definitely will be included in Gutenberg 11.0 and may even be backported to a 10.9 release. 

Please reopen if you are still experiencing this in 11.0.

**Closed as completed by skorasaurus** 2021-06-25 16:53 UTC
Labels: [Type] Bug, [Feature] Rich Text, [Status] Needs More Info, [Block] List

**Comment by pansamolot** [comment] 2021-06-26 19:01
Just to update / clarify. Both #32467 and my description above may incorrectly suggest that there is a problem with pasting list item into list item only.

I can now confirm that this is not true. There's a general problem with pasting anything (any type of block) into list item. In my case Gutenberg failed to paste both preformatted block of text, link and generally anything except for a unformatted text.

**Comment by skorasaurus** [comment] 2021-06-30 18:43
Thanks for the clarity, I'm able to confirm this @pansamolot 

This is being tracked at https://github.com/WordPress/gutenberg/issues/33078

**Comment by pansamolot** [comment] 2021-07-01 08:15
@skorasaurus Isn't newly created #33078 and old #32467 a duplicates? Or at list one of them being a substitute of another? Or am I missing something?

**Comment by skorasaurus** [comment] 2021-07-01 16:19
As I understand; they're extremely similar and the tickets somewhat overlap but 2 expected behaviors/workflows are not : 

#33078 is text copied from a paragraph block cannot be pasted as an item in a list block; nothing is pasted when pasted action is done (right click and select paste)
#32467 is text copied from a list block, in certain conditions (as outlined in the issue), will create an invalid block when pasted.

**Comment by pansamolot** [comment] 2021-07-01 16:30
Well... my assumption (and a question here) was, because I have somewhat a mixture of both above.

In my case _nothing_ can be pasted into a list block (or actually: a list item inside list block) in certain scenarios. I tried pasting:

- content from another list item (animations above),
- content from a simple block (paragraph block)
- content from outside Wordpress (some rich or plain text)

But, OK, that was just for a clarifications. Let's keep current ticket closed and let's wait for the resolution for the two mentioned by you above (either fix + merge or closure). And, ultimately, let's wait for a public release of a Gutenberg version having fixes to these and similar fixes.
