### ISSUE TITLE
Group block: improve excerpt display with grid layout themes

### ISSUE THREAD

**Issue by formosattic** [WordPress/gutenberg#17078] opened 2019-08-18 10:09 UTC
The problem happens with themes (like [Rebalance](https://wordpress.org/themes/rebalance/)) which have:

* a grid layout
* a **Blog Display** set to **Post excerpt** (either from **Content Options** or by default from the theme)

If a post starts with a Group block, then none of the content (even Paragraph blocks inside it) will get displayed in the excerpt.

**Describe the solution you'd like**: the excerpt should pickup text at the beginning of the article, regardless of whether it's in a Group block or not.

**Temporary Solutions**

* move the text at the beginning of the Group block to its own Paragraph block
* manually add text under **Document > Excerpt**

### Editor view
<img width="853" alt="Screen Shot 2019-08-18 at 17 48 00" src="https://user-images.githubusercontent.com/15944096/63222934-d57bb480-c1e0-11e9-80b9-8e04f646b831.png">

### Blog display with a grid layout theme ([Rebalance](https://wordpress.org/themes/rebalance/))
<img width="858" alt="Screen Shot 2019-08-18 at 17 46 57" src="https://user-images.githubusercontent.com/15944096/63222933-cf85d380-c1e0-11e9-9207-26fe686b036b.png">

### Blog display with a non-grid layout theme ([Dara](https://wordpress.org/themes/dara/))
<img width="788" alt="Screen Shot 2019-08-18 at 17 55 01" src="https://user-images.githubusercontent.com/15944096/63222988-576bdd80-c1e1-11e9-8d95-d1ed5a38645b.png">

**Comment by swissspidy** [comment] 2019-08-18 13:43
To me that sounds more like the Rebalance theme does some custom filtering of the excerpt. Does this work correctly when using a theme like Twenty Nineteen? If so, I'd suggest reaching out to the Rebalance theme developers to get some more details on how the theme handles excerpts.

**Comment by kristarella** [comment] 2019-08-20 06:44
Yes this can be replicated in Twenty Nineteen.

**To replicate**
1. Create a post starting with a group block containing a paragraph, and another paragraph outside and after the group block.
2. In Twenty Nineteen theme edit file `template-parts/content/content.php` at line 32, either replace `the_content`, or in addition to it, add `the_excerpt();`
3. View post: excerpt does not show the paragraph inside the group block, only the paragraphs outside and after that block.

This was using: 
- WP 5.2.2
- Gutenberg plugin 6.3.0
- Twenty Nineteen 1.4

**Screenshot**
For my test I had both `the_excerpt()` and `the_content()` showing at the same time. You can see the start of `the_excerpt` is not the same text as `the_content`.
![Screen Shot on 2019-08-20 at 16:40:57](https://user-images.githubusercontent.com/2031017/63323563-71d0c300-c369-11e9-998d-e912dcb170f5.png)

**Comment by loxK** [comment] 2019-12-10 22:51
I can confirm too that the content in a group block is ignored by the_excerpt() or the get_the_excerpt() functions.

**Comment by talldan** [comment] 2019-12-13 09:18
I think the issue is captured by this trac ticket:
https://core.trac.wordpress.org/ticket/47637

As it's an issue that needs to be fixed in WordPress Core, I'll close this as a duplicate/reported upstream and link to this issue from that ticket. Agreed there's a definite need to improve this, though 👍

**Closed by talldan** 2019-12-13 09:18 UTC
Labels: [Block] Group, [Feature] Themes
