### ISSUE TITLE
Custom post type incorrect width if not public queryable

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#53885] opened 2023-08-23 02:25 UTC
### Description

I have noticed a strange behaviour on Wp 6.3. 

Custom post type always have class `is-layout-flow` if I set `'publicly_queryable'  => false,`.

The behaviour is happening after latest Wp update. Before I have a width exactly like posts or pages.

This can be checked using my Formello plugin, that simply use CPT to store forms.

### Step-by-step reproduction instructions

1. Create a simple custom post type
2. Set `'publicly_queryable'  => false,`
3. Check the width is full-width and differs from posts or pages.

### Environment info

- WP 6.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment] 2023-08-23 04:49
Thanks for opening this separate issue!

I can reproduce this. To replicate the issue I did the following:

1. Installed [Custom Post Type UI plugin](https://wordpress.org/plugins/custom-post-type-ui/)
2. Created a new custom post type that is publicly queryable
3. Confirmed that in the post editor, the main post content area uses a constrained layout
4. If I then switch the post type to not be publicly queryable and then reload the editor for that custom post type, then in the editor, the content is displayed as full-width

The setting in CPT UI:

<img width="1099" alt="image" src="https://github.com/WordPress/gutenberg/assets/14988353/25e3738b-aebc-47bc-9d06-7a91221c5232">

| Editor view for a custom post type with publicly_querable true | Editor view for a custom post type with publicly_querable false |
| --- | --- |
| ![image](https://github.com/WordPress/gutenberg/assets/14988353/caa2da8e-0580-4512-9d7f-456f2dd076aa) | ![image](https://github.com/WordPress/gutenberg/assets/14988353/c13166b4-8916-4198-a288-140170ab544a) |

I'm not sure if it's related to #53752 as that issue is particular to the post content block being rendered in the block editor, however it might also be related to the issue described in https://github.com/WordPress/gutenberg/issues/52163

**Comment by tellthemachines** [comment] 2023-09-08 05:18
I can no longer reproduce this issue and am reasonably sure it was fixed by #54158. 

For some reason, the edited post template for a non-publicly queryable post doesn't have a theme file attached, so it defaults to the home/front page template. You can see this if you navigate to the post on the front end: it will show the front page instead of the post content.

(I'm not sure if that's intended behaviour or not; should not being publicly queryable equate to not being publicly visible at all?)

**Comment by andrewserong** [comment] 2023-09-08 05:31
> I can no longer reproduce this issue and am reasonably sure it was fixed by https://github.com/WordPress/gutenberg/pull/54158.

Oh, thanks! Yes, just double checked that fixed the issue for me, so I'll close this out now 👍

> (I'm not sure if that's intended behaviour or not; should not being publicly queryable equate to not being publicly visible at all?)

Hrm, oh that's weird! In case it narrows it down at all, for me that only happens if I attempt to access it via the "pretty" url for the post type:

![image](https://github.com/WordPress/gutenberg/assets/14988353/c275cb42-e0f9-4ddf-968a-c143f1f559d3)

If I go to access via post id, then I get a 404, which I'd expect:

![image](https://github.com/WordPress/gutenberg/assets/14988353/3d56c8b2-9318-4e45-9af5-9be42ab24bfc)

🤔

**Closed as completed by andrewserong** 2023-09-08 05:31 UTC
Labels: [Type] Bug, [Feature] Layout
