### ISSUE TITLE
Update Failed when trying to save draft

### ISSUE THREAD

**Issue by mgarf** [WordPress/gutenberg#3252] opened 2017-10-31 03:23 UTC
## Issue Overview
When a user in wp admin tries to save a draft, it gets update failed

## Steps to Reproduce (for bugs)
1. Go to New Post
2. Enter Content
3. Hit Save

## Expected Behavior
Update should occur

## Current Behavior
No save occurs.

Console shows the following:
![image](https://user-images.githubusercontent.com/5124393/32206061-f958bca2-bdc0-11e7-8e2c-dd33f53df4d8.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment] 2017-10-31 12:01
My assumption is that the host might not have support for HTTP verbs except basic GET and POST.

The REST API has built-in support for manually specifying intended method on a POST request:

https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_method-or-x-http-method-override-header

I'm not clear on how this is meant to be used from a client, whether it is built-in for the [Backbone client](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/) or [api-request](https://core.trac.wordpress.org/ticket/40919) utilities, or must be manual opt-in.

**Comment by mgarf** [comment] 2017-11-01 00:45
Hmm any thoughts on how to get around this issue

**Comment by aduth** [comment] 2017-11-01 13:07
@mgarf On your end, this is dependent on the hosting environment supporting HTTP verbs aside from just GET and POST. I am unsure how much control you have over this, depending on your host, but in Apache and nginx I believe these restrictions must be explicitly put in place, so a resolution could be to remove them if the option is available.

From the WordPress end, arguably it seems that the underlying [Backbone client](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/) and [api-request](https://core.trac.wordpress.org/ticket/40919) should use the `POST` verb with `_method` argument as more compatible default.

I raised this today in the core-restapi Slack channel: https://wordpress.slack.com/archives/C02RQC26G/p1509540912000307

**Comment by mgarf** [comment] 2017-11-03 23:36
@aduth thank you for raising the concern with core-restapi. I'll try to figure out on my side on an easy solution to enable those wider range of verbs on azure.

**Comment by jeffpaul** [comment] 2018-03-07 03:36
@mgarf as discussed in [last week's bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1519926514000207), this could be a duplicate of #2565. Are you using CloudFlare? If not, could you provide additional details on your testing environment?

**Comment by mgarf** [comment] 2018-03-07 12:23
My apologies I never updated this thread. Once I expanded the verbs saving worked properly.

The environment was a azure web app with WordPress running on IIS. No cloudflare

**Comment by jeffpaul** [comment] 2018-03-07 15:59
@mgarf apologies but I'm not clear, is this still an issue or can this be closed?

**Comment by svnsbck** [comment] 2018-03-11 05:02
I'm having the same issue here. Failing every time and leaving a blank AUTO-SAVE.

**Comment by thebugfixnet** [comment] 2018-03-17 11:25
Do you use any Firewall Plugin?

For example at [All In One WP Security & Firewall](https://wordpress.org/plugins/all-in-one-wp-security-and-firewall/)  it is needed to deactivate the '6G Firewall Protection'. With the 'legacy 5G Firewall Protection' Gutenberg works fine. 

You can find the settings at Dashboard - WP Security - Firewall - 6G Blacklist Firewall Rules

![image](https://user-images.githubusercontent.com/37211016/37554805-2d2c401a-29de-11e8-8afd-ed5e720b5abc.png)

**Comment by mgarf** [comment] 2018-03-17 16:59
@jeffpaul yep thjis can be closed

**Comment by jeffpaul** [comment] 2018-03-19 18:20
@svnsbck is your issue occurring when trying to save a draft?

**Comment by svnsbck** [comment] 2018-03-19 21:12
@jeffpaul Yes, just tested again. It happens both when manually saving and the autosave. Looking at the "all posts" list shows merely a "AUTO DRAFT" which is empty and doesn't have a title. Also noticed that the "Categories and Tags" are not read and are empty.

**Comment by danielbachhuber** [comment] 2018-06-04 11:48
Closing, per https://github.com/WordPress/gutenberg/issues/3252#issuecomment-373935737

**Closed by danielbachhuber** 2018-06-04 11:48 UTC
Labels: Core REST API Task, [Type] Bug
