### ISSUE TITLE
Removing a reusable block does not get removed from all posts

### ISSUE THREAD

**Issue by JoeDawson** [WordPress/gutenberg#11175] opened 2018-10-28 14:45 UTC
**Describe the bug**
When removing a reusable block from a post, we're prompted that the block will be removed from all existing posts/pages it **is not**.

**To Reproduce**
1. Create a post
2. Insert a heading and make it reusable
3. Publish the post
4. Create a second post
5. Insert the reusable block created in our first post
6. Publish the second post
7. Head back to our first post and "Remove from Reusable Blocks"

*At this point, we're asked to confirm if we want to permanently delete the reusable block since it will be removed from all posts and pages that use it.*

<img width="494" alt="screenshot 2018-10-28 at 14 39 24" src="https://user-images.githubusercontent.com/1009696/47617502-a7957a00-dabf-11e8-8266-bd3ae19dc3c6.png">

8. Update our first post
9. Edit our second post, the reusable blocks still remains
10. In addition to this, if you then remove this block from the second post it is removed - however an error is displayed saying the the post has already been deleted (referencing the reusable block we deleted earlier)

**Expected behavior**
Expect the reusable block to be removed from all posts and pages as the prompt suggests.

**Screenshots**
(See above)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- Gutenberg Version: 4.1.1

**Comment by jjchrisdiehl** [comment] 2018-10-28 18:41
Reproduced as described https://cloudup.com/c_gp40w_WnN

Web Browser
Chrome 69.0.3497.100

Browser Operating System
Operating System
Microsoft Windows (10) NT 4.0

WP Version
4.9.8

**Comment by earnjam** [comment] 2018-10-28 18:57
This may be a copy related issue. I think the intention of the message is to mean that it will no longer display on the front-end, not necessarily that it will parse all posts for the existence of this block.

**Comment by slimmilkduds** [comment] 2018-10-29 10:28
This really looks like a bug to me, otherwise it's pretty weird behaviour. If you do "remove from reusable blocks" it is removed from the reusable block list, however, the block is still available for editing in the back end of other posts using it (and it displays on the front end). I always assumed it wouldn't be rendered on the front end and that it would disappear when the reference to that block wasn't resolved when you edit a post with a missing block.

**Comment by kristastevens** [comment] 2018-10-29 13:46
It seems like a bug to me. (I'm thinking that if a RB was deleted, it would behave like an image deleted from the media library -- it no longer appears on the site anywhere.) If this is not to be treated as a bug, then I  propose revising the messaging so that it matches the block behavior when deleted. 

Original: 
> Are you sure you want to delete this Reusable Block? 
> It will permanently be removed from all posts and pages that use it. 

Proposed: 
> Are you sure you want to delete this Reusable Block? 
> It will no longer appear in this post.

**Comment by slimmilkduds** [comment] 2018-10-29 14:03
> Proposed:
> 
> > Are you sure you want to delete this Reusable Block?
> > It will no longer appear in this post.

"It will still appear in other posts but will prompt an error message if you try to delete it since it's already deleted" ;)

**Comment by earnjam** [comment] 2018-10-29 14:29
Yeah, I think we need some clarity about the intended result of deleting a reusable block to confirm whether it's a bug in the implementation, or it needs clearer wording on the warning prompt.

**Comment by youknowriad** [comment] 2018-10-29 14:31
AFAIK the intent has never been to remove it from all the posts, just remove it from the list of available blocks and also from the current post which means when you open another post containing this block, you get a notice of a missing reusable block. In the frontend it won't show anything though.

**Comment by slimmilkduds** [comment] 2018-10-29 14:47
_"which means when you open another post containing this block, you get a notice of a missing reusable block. In the frontend it won't show anything though."_

If you are right than it's a bug since I can still see the deleted block in other posts (front end and back end) and I don't get a notice about the missing block (only an error when I try to delete it)

**Comment by noisysocks** [comment] 2018-11-05 06:12
The expected behaviour is that a reusable block, once deleted, will no longer appear on the frontend. Editing a post that includes a reusable block will result in a placeholder that explains that the block is deleted or missing:

<img width="594" alt="screen shot 2018-11-05 at 17 06 43" src="https://user-images.githubusercontent.com/612155/47980812-6cc5be80-e11d-11e8-87ea-18d1baf1f2ff.png">

I've confirmed that this works as expected in `master`. Closing this out for now. We can re-open if there's consensus about changing the copy to be clearer.

**Closed by noisysocks** 2018-11-05 06:12 UTC
Labels: Needs Copy Review, [Component] Reusable Blocks, [Type] Bug
