### ISSUE TITLE
Unable to return to former placeholder state in a Media & Text block

### ISSUE THREAD

**Issue by smerriman** [WordPress/gutenberg#28535] opened 2021-01-28 00:07 UTC
## Description
When you first insert a Media & Text block, you see a placeholder where an image can be uploaded.

It is possible to save and publish the content without uploading an image. I believe this is intended and think it is a good idea, especially while you're in the process of creating the page and want to get a consistent flow of content before placing images. You may want to retain the layout while keeping the image area blank for the short term.

Once an image is selected, it is impossible to return to the prior state of having a placeholder box without deleting the entire block and starting again.

## Step-by-step reproduction instructions
1. Add a Media & Text block, and add some text content.
2. Note that the block can be saved and published as is, which places the text to the side.
3. Upload and select an image.
4. Note there is no way of removing the image without replacing it with another one.

## Expected behaviour
There should be a way of removing the image.

## Actual behaviour
There isn't.

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by talldan** [comment] 2021-01-28 02:31
Thanks for creating the issue. This isn't really a bug, seems more like a feature request. Currently the block works as designed.

I'm sure this could be done, but I'm not completely sure about the widespread value this feature would have. I'll leave the issue open so that it can gather feedback.

**Comment by smerriman** [comment] 2021-01-28 02:33
I considered feature request, but the UX issues means it is a bug. If you don't want the ability for a Media & Text block without an image, then it's a bug that you can; if you do, then it's a bug that you can't.

**Comment by talldan** [comment] 2021-01-28 05:35
> If you don't want the ability for a Media & Text block without an image, then it's a bug that you can initially

The initial state is to allow users to select an image. There's no written rule that says that this operation should be reversible.

**Comment by paaljoachim** [comment] 2021-02-02 13:54
Well this is kinda tricky.
When using Gutenberg or any piece of software one will use whatever features are available. Independent of if one is using the feature the "correct" way or not.

In this case it means adding a Media & Text block and just add the text on the right side and no image. 

![Screen Shot 2021-02-02 at 14 48 04](https://user-images.githubusercontent.com/5323259/106609451-db488f80-6565-11eb-95b8-b525576b5b2b.png)

Frontend:
![Screen Shot 2021-02-02 at 14 48 28](https://user-images.githubusercontent.com/5323259/106609717-2b275680-6566-11eb-8711-1f427d03e1d2.png)

A user might be just looking for a simple way to add text to the right like the above screenshot.

The official recommendation would likely be to use the columns block and add two columns. Then add text in the right column.

I am sorry to say it, @smerriman but I believe this is a won't fix issue. As for the Media & Text block the purpose is about adding media and text.

**Comment by carolinan** [comment] 2023-06-16 10:06
Initially, there is an undo step that can be used to return to the default state.
The only image block that has a reset is the post-featured image block, so I think this is consistent with the other image blocks.

**Comment by kraftner** [comment] 2023-06-16 10:09
@carolinan Please reconsider this. The undo state only works when you haven't saved and reloaded the page.

This is a huge problem when using the block inside a locked template since there you can't just delete the block. It makes the block basically unusable in such a scenario.

**Comment by Mamaduka** [comment] 2024-12-11 12:43
I'll close the issue. You can now "Reset" media using the media replace dropdown. See #64826.

## Screenshot
![Image](https://github.com/user-attachments/assets/011672c9-aba5-4b9f-90dc-703de362dfe0)

**Closed by Mamaduka** 2024-12-11 12:43 UTC
Labels: [Type] Enhancement, Needs Design Feedback, Needs Decision, [Block] Media & Text
