### ISSUE TITLE
Add hook for block deletion so post meta can be removed

### ISSUE THREAD

**Issue by diegoliv** [WordPress/gutenberg#5626] opened 2018-03-15 05:29 UTC
## Issue Overview
When you create a block that have a attribute set as `meta`, Gutenberg saves this same attribute as post meta, which is expected. However, if you remove the block and save the post, the post meta is still stored on the database.

## Steps to Reproduce (for bugs)

1. Create a custom block, and set any random attribute as `source: 'meta'`.
2. Change the attribute value and save the post.
3. Check on the frontend, using `get_post_meta`, the value of the post meta from that specific block.
4. Now go back to the editor, remove the block and update the post.
5. Go back to the frontend, and check again the value of the post meta. It is still there.

## Expected Behavior
When the block is deleted, the post meta should be deleted as well. Unless there is another block of the same type for the post. On this case, post meta should be treated on a block basis, not on a post basis (related to #5599)

## Current Behavior
Post meta is stored when you add one block, changes when you change the attribute on any instance of the block for the respective post, but it is not removed from the database if you remove all block instances.

## Related Issues and/or PRs
#5599

**Comment by ocean90** [comment] 2018-05-02 06:56
See #4054 for previous discussion.

If the editor is not going to remove/reset them to default (see #6505) by default, there needs at least a hook on block delete that can be used to perform additional cleanups like deleting post meta.

**Comment by Luehrsen** [comment] 2018-05-16 14:37
I would like to add importance to this issue. We are using blocks to control the existence of certain metadata (e.g. control template pieces outside of 'the_content()')

AFAIK there is currently no way to force the existance of a certain block, so the the problem is that we will have metadata existing without an interface to edit them. That is less than optimal.

**Comment by Luehrsen** [comment] 2018-05-25 14:17
https://gist.github.com/Luehrsen/41d27f30eaca2d997a84898271c004c7

This is my current implementation. It works, but it has some issues. Sometimes the actions fire twice, sometimes I get a strange error from the rest API. (See screenshot)

But so far I am quite happy with the progress. 

![bildschirmfoto 2018-05-25 um 16 16 58](https://user-images.githubusercontent.com/1105871/40549215-26e530d8-6037-11e8-8953-8fbd341178a3.png)

**Comment by danielbachhuber** [comment] 2018-06-04 13:27
Re-titled issue as "Add hook for block deletion so post meta can be removed" to clarify its direction.

**Comment by aduth** [comment] 2018-06-18 13:33
To me, ideally this is not something which occurs in the editor itself, as it's very possible someone may remove the block without interfacing with Gutenberg (by database, or `wp_update_post`). With server registration of blocks (#2751), it seems reasonable that in the updating of a post's content, we could detect whether a block is being removed which sources some attribute value from post meta, then delete the associated post meta from the server (admittedly only addresses `wp_update_post`, and not database manipulation, but a step in the right direction).

**Comment by hgezim** [comment] 2018-12-13 20:44
Any updates on this?

**Comment by mitogh** [comment] 2018-12-13 21:05
As a workaround of this I used `componentWillUnMount`  and trigger an action there.

**Comment by gziolo** [comment] 2019-02-01 08:12
Indeed, it makes a lot of sense what @aduth shared. Even if we would land #7325 proposed by @Luehrsen, this issue would still be present if someone uses REST API to remove one of the blocks. Given that mobile team is working on Gutenberg integration for the mobile app this issue will become even more prominent.

I'm wondering if the root issue shouldn't be moved to WordPress core now as the logic for saving blocks is there.

**Comment by youknowriad** [comment] 2020-04-11 00:06
I'm going to close this now as a potential solution for this can't come from the block editor itself. 
Please consider opening a trac ticket about this if needed.

**Closed by youknowriad** 2020-04-11 00:06 UTC
Labels: [Feature] Block API
