### ISSUE TITLE
Reusable blocks not showing and then failing to convert to static

### ISSUE THREAD

**Issue by nicholasurban** [WordPress/gutenberg#28260] opened 2021-01-17 16:40 UTC
I’ve had lots of problems with Gutenberg reusable blocks. Most of the time they don’t show at all in the _add new block_ menu (both slash commands & via the + button).

Activating the Health Check plugin sometimes works to get them to show.

Even when they do show, I **cannot convert them to static blocks**. Every time I click the button I get console errors. In index.js. Getting:

`index.js?ver=1689cb956d512255e83b9beeb3877c72:1 Uncaught (in promise) TypeError: e.substr is not a function
    at b (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at p (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at s (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at Vr (index.js?ver=99dbf067058789c8337dd6701f5bb465:13)
    at O.CONVERT_BLOCK_TO_STATIC (index.js?ver=113e55d4803dcb7a750c08ac417bde4c:1)
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1
    at Array.some (<anonymous>)
    at e (index.js?ver=f9853317f55f74370a03b45280d6c03e:1)
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1`

Tried disabling all plugins, using other browsers without extensions, and changing to the default theme. No luck.

Not positive it’s Gutenberg but seems like it is.

## WordPress information
Latest WordPress
Latest Gutenberg
All plugins disabled
Default theme

## Device information
Safari/Brave

**Comment by Alexius08** [comment] 2021-01-18 03:10
Could [this](https://core.trac.wordpress.org/ticket/52031) be related to the error message you got? Someone else reported a similar issue involving third-party plugins.

**Comment by alaxmo13** [comment] 2021-01-19 19:04
I have also the same problem. My console output is this:

index.js?ver=1689cb956d512255e83b9beeb3877c72:1 Uncaught (in promise) TypeError: e.substr is not a function
    at b (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at p (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at s (index.js?ver=1689cb956d512255e83b9beeb3877c72:1)
    at Vr (index.js?ver=99dbf067058789c8337dd6701f5bb465:13)
    at O.CONVERT_BLOCK_TO_STATIC (index.js?ver=113e55d4803dcb7a750c08ac417bde4c:1)
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1
    at Array.some (<anonymous>)
    at e (index.js?ver=f9853317f55f74370a03b45280d6c03e:1)
    at index.js?ver=f9853317f55f74370a03b45280d6c03e:1

I think it's the same bug. 

I have the latest WordPress version and the latest Gutenberg version. 

I'm using Astra them and I have several plugins activated.

**Comment by alaxmo13** [comment] 2021-01-19 19:19
index.js:1 Uncaught (in promise) TypeError: e.substr is not a function
    at b (index.js:1)
    at p (index.js:1)
    at s (index.js:1)
    at Vr (index.js:13)
    at O.CONVERT_BLOCK_TO_STATIC (index.js:1)
    at index.js:1
    at index.js:1
    at Array.some (<anonymous>)
    at e (index.js:1)
    at index.js:1

Here you have the output if you try to "convert to regular blocks" when the post is published instead of draft.

**Comment by nicholasurban** [comment] 2021-01-20 18:24
> Could [this](https://core.trac.wordpress.org/ticket/52031) be related to the error message you got? Someone else reported a similar issue involving third-party plugins.

I had already looked through the Gutenberg forms and other sources on the Internet. Couldn’t find anything related. Same error with all plug-ins disabled and on the default theme

**Comment by talldan** [comment] 2021-01-28 03:13
Would appreciated it if you could use the provided issue template.

Anyway, this looks like a duplicate of https://github.com/WordPress/gutenberg/issues/26421 so closing.

**Closed by talldan** 2021-01-28 03:13 UTC

**Comment by yolinfl** [comment] 2021-01-28 12:11
I have the same problem with reusable blocks from Publishpress and Kioken blocks. I hope this issue will be solved soon.
