### ISSUE TITLE
Cannot Insert Pattern into Column Block (Pattern Library Missing)

### ISSUE THREAD

**Issue by pattyok** [WordPress/gutenberg#29514] opened 2021-03-03 13:25 UTC
## Description
I've added several patterns to the pattern library. One is specifically to be used inside of a column. When I click inside the column to add the block and browse all, there is no Patterns tab on the Library. If I click outside of the column block, I can add the column and drag it in, but this is not something I am going to ask my clients to do. Also will add that this is a completely confusing experience and took me quite some time to determine why the Pattern Library was missing... sometimes?

## Step-by-step reproduction instructions
1. Create a new page
2. Add a column block
3. Click inside the column to add a block 
4. Click Browse All

## Expected behavior
I would expect to see the Pattern Library available among the tabs on the Block Library.

## Actual behavior
Pattern Library tab is missing.

## Screenshots or screen recording (optional)
https://www.loom.com/share/1f85718398274020be70cee180cecbb5

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: Not Installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?Yes

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Chrome 88.0.4324.192

**Comment by Sandstromer** [comment] 2021-03-03 15:07
I can confirm that I can recreate this issue with Gutenberg deactivated.

With Gutenberg activated, this issue is not present and I can select and insert a pattern directly into a column, so I would assume that the issue is fixed in Gutenberg and the fix will filter through to WP core in the next update.

**Comment by skorasaurus** [comment] 2021-03-04 00:09
Hi, 

Thanks for reporting. I believe this is a duplicate of https://github.com/WordPress/gutenberg/issues/26805 which was ultimately fixed by https://github.com/WordPress/gutenberg/pull/26443.
This was included in Gutenberg 9.4 and will be included in [WordPress 5.7 which comes out next week, March 9t](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwifn7qsrJXvAhWkT98KHWIcBzYQFjACegQIBRAD&url=https%3A%2F%2Fwww.wpbeginner.com%2Fnews%2Fwhats-coming-in-wordpress-5-7-features-and-screenshots%2F&usg=AOvVaw3lOi3VjMcGaw7X_49oL75N)h.

**Closed by skorasaurus** 2021-03-04 00:09 UTC
