### ISSUE TITLE
Can't add TinyMCE custom formats in gutenberg classic editor block

### ISSUE THREAD

**Issue by stratboy** [WordPress/gutenberg#15715] opened 2019-05-18 07:29 UTC
The filter `tiny_mce_before_init` seems not to work anymore. Can't add custom formats to classic editor block. This code won't work anymore:

``` php
add_filter( 'tiny_mce_before_init', 'add_tinymce_formats', 10, 2);
function add_tinymce_formats($mceinit, $editor_id){

  $new_styles = array(
    array(
      'title' => 'Foradori'
      ,'items' => array(
        array(
          'inline' => 'span',
          'title' => 'Red',
          'classes' => 'red'
        )
      )// end items
    )// and main array
  );

  $mceinit['style_formats_merge'] = true;
  $mceinit['style_formats'] = json_encode($new_styles);
  return $mceinit;
}
```

**Comment by youknowriad** [comment] 2019-05-21 09:39
This is a duplicate of #14221

**Closed by youknowriad** 2019-05-21 09:39 UTC
