### ISSUE TITLE
Remove unsupported Hulu embed block

### ISSUE THREAD

**Issue by tacitonic** [WordPress/gutenberg#23920] opened 2020-07-14 07:10 UTC
**Describe the bug**

The Hulu Embed Block from the default Block Editor cannot embed any links. This error was discovered while creating the Documentation for this block. Different links were tried from Hulu as well as this article - https://wordpress.com/support/videos/hulu/ but none of them successfully embedded the content. There might be a possibility of non-subscribers/paywall or geo-locking preventing the embed.
The console shows that there might be an API fetch error.

CC: @bph 

**To reproduce**
1. Add a Hulu Embed Block
2. Paste a Hulu link in the text box.
3. Click "Embed"
4. The block will display an error similar to this: https://i1.wp.com/wordpress.org/support/files/2020/06/soundcloud5.4_8.png?w=700&ssl=1

**Expected behavior**
The Hulu link gets embedded.

**Editor version:**
- WordPress version: 5.4.2
- Default Block Editor

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by talldan** [comment] 2020-07-14 08:52
> There might be a possibility of non-subscribers/paywall or geo-locking preventing the embed.

Possibly. I tried testing using the link from that WordPress.com article (https://www.hulu.com/watch/771496), but I'm in Australia, so this would also be an issue for me. Would be great if someone US based could test this.

**Comment by bph** [comment] 2020-07-14 12:18
@talldan 
It doesn't work for me in US (Florida) either. 

Video: https://recordit.co/WEbLy3XdnR (nothing 

No error message in the console. 

OS X 10.14.6
Chrome: Version 83.0.4103.116
Gutenberg 8.5.1
WP 5.4.2

**Comment by tacitonic** [comment] 2020-07-14 14:04
![Screenshot (132)](https://user-images.githubusercontent.com/38654946/87435036-d2fc2780-c608-11ea-8d25-d8fc438a8eda.png)

**Comment by youknowriad** [comment] 2020-07-15 21:05
Unless I'm mistaken this is the direct link to hulu's oembed provider

https://www.hulu.com/api/oembed.xml?url=https://www.hulu.com/watch/771496

but as you can see it's not working. I wonder if they silently removed their oembed API?

**Comment by bph** [comment] 2020-07-15 22:04
Thanks for scouting this out, @youknowriad 
As it seems to be an abandoned service, shouldn't we remove the embed block from the block editor?

**Comment by youknowriad** [comment] 2020-07-15 22:16
yes, if it's confirmed we'd need to remove both the block and the provider from core too. I'd love for someone else (preferably in the US) to try to confirm that.

**Comment by bph** [comment] 2020-07-15 22:34
@youknowriad I can confirm "We'll be back - This page is temporarily unavailable. Please try refreshing the page or go back to the homepage." That this is not working from the US either. [Just pinged them on Twitter.](https://twitter.com/bph/status/1283529732907245568) But I doubt I'll get an answer.

**Comment by bph** [comment] 2020-07-16 01:19
This was the answer: "Apologies for any disappointment! This isn't an available option at the moment, but we'll express your interest. (...)"

Sounds quite noncomittal. It seems to be ok to remove the Hulu block from the block editor. @youknowriad

**Comment by talldan** [comment] 2020-07-16 04:57
Thanks so much for testing @bph!

Looks like the previous approach has been to remove unsupported embed blocks - https://github.com/WordPress/gutenberg/pull/12759, and then as Riad mentions, also remove the provider code from core - https://core.trac.wordpress.org/ticket/45399.

I've updated this issue and made a new trac ticket for the core task:
https://core.trac.wordpress.org/ticket/50676#ticket

**Comment by tacitonic** [comment] 2020-07-16 05:33
I'm new to core, but perhaps I could have a go at this? The task seems simple enough; just have to remove `core-embed/hulu` from `packages/block-library/src/embed/core-embeds.js` & then also make the required changes to `src/wp-includes/class-oembed.php`. 
Kindly mention if I missed anything. Could you assign me to this issue @talldan?

**Comment by ntsekouras** [comment] 2020-07-16 06:03
Hey @tacitonic! Thanks for stepping in 👍

**Comment by talldan** [comment] 2020-07-16 06:51
Sounds great, thanks @tacitonic!

**Comment by tacitonic** [comment] 2020-07-16 07:13
#23984

**Comment by talldan** [comment] 2020-07-16 07:37
Closed by #23984.

**Closed by talldan** 2020-07-16 07:37 UTC
Labels: Good First Issue, [Block] Embed, [Type] Task

**Comment by desrosj** [comment] 2020-07-20 13:07
Just wanted to add this for reference. The Hulu support team responded saying it was not a supported option at this time: https://twitter.com/hulu_support/status/1283562756726300672
