### ISSUE TITLE
Fatal error: cyclical embedded blocks

### ISSUE THREAD

**Issue by carlomanf** [WordPress/gutenberg#25472] opened 2020-09-19 04:43 UTC
**Describe the bug**
#22080 fixed the infinite loop that occurred when the post content block tries to render the same post that it's embedded in.

This, however, isn't the only scenario where an infinite loop could occur. In theory, it could occur through:

- any block that embeds block-based content (post content block, reusable block, template part and so on)
- any cyclical combination of any of the above blocks embedding each other (cycle of 1 or more)

For example, I was able to produce a fatal error with two reusable blocks that embed each other:

**Example 1**
1. Created a reusable block with id 168 and the following content:

```
<!-- wp:paragraph -->
<p>reusable 1 paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>reusable 1 paragraph 2</p>
<!-- /wp:paragraph -->

<!-- wp:block {"ref":169} /-->
```

2. Created a reusable block with id 169 and the following content:

```
<!-- wp:paragraph -->
<p>reusable 2 paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>reusable 2 paragraph 2</p>
<!-- /wp:paragraph -->

<!-- wp:block {"ref":168} /-->
```
3. See fatal error whenever either of these blocks is rendered

**Example 2**
1. To illustrate that this happens with any cyclical combination of any of these block types, I changed the post type of 169 from `wp_block` to `wp_template_part` and updated the content of 168 accordingly:

```
<!-- wp:paragraph -->
<p>reusable 1 paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>reusable 1 paragraph 2</p>
<!-- /wp:paragraph -->

<!-- wp:template-part {"postId":169,"slug":"untitled-reusable-block-2","theme":""} /-->
```
2. 169 retains the same post content as example 1

3. See fatal error whenever either reusable block or template part is rendered

**Expected behavior**
The expected behavior that I would suggest is to keep rendering a cycle of embedded blocks until one block tries to render a piece of content that is already part of the cycle, and then render a placeholder instead to break the cycle.

**Editor version (please complete the following information):**
- WordPress 5.5 and Gutenberg 9.0

**Comment by talldan** [comment] 2020-09-24 01:46
Closing as a duplicate of #18704

**Closed by talldan** 2020-09-24 01:46 UTC
Labels: [Feature] Reusable Blocks, [Status] Duplicate, [Type] Bug
