### ISSUE TITLE
Switching Quote block with HTML tags in it splits it in two

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#1765] opened 2017-07-06 15:33 UTC
## Steps to Reproduce

1. Create a new post, type some text in a Text block
2. Select part of the text and turn it into a link
3. Turn the block into a quote
4. Turn the block back into text, and it splits in two

![breaking blocks](https://user-images.githubusercontent.com/6073772/27919130-2607463e-6271-11e7-8746-fc6e96997cb3.gif)

Version 0.3.0

## Expected Behavior
For the text to stay together in one block.

## Current Behavior
The text gets split into two blocks.

**Comment by westonruter** [comment] 2017-07-06 22:09
There seems to be some issues with the block transformation: https://github.com/WordPress/gutenberg/blob/313e6c3b2d7d263d6685c5f710c94f7e23888099/blocks/library/quote/index.js#L62-L84

I'm taking a look.

**Comment by westonruter** [comment] 2017-07-06 22:22
I think the issue may have been introduced by #1078, where a Text block now only contains a single paragraph. /cc @iseulde

**Comment by westonruter** [comment] 2017-07-07 01:37
See one possible improvement in #1774.

**Comment by karmatosed** [comment] 2017-09-04 19:46
I am still seeing this in 1.0.

**Comment by EphoxJames** [comment] 2017-09-06 06:37
I just tried to replicate this and I am not seeing the link split off as in the video. It is still creating 2 blocks though which is probably not what we want when the quote attribution field is empty.
![p-link-to-quote-conv](https://user-images.githubusercontent.com/26243021/30097567-935185ca-9321-11e7-89ee-d9e7a971922e.gif)

**Comment by jasmussen** [comment] 2017-12-04 13:43
I can't reproduce the "breaking on the link" issue, but it still does create two blocks, and I think #3559 is related or the same.

**Comment by jorgefilipecosta** [comment] 2017-12-05 11:09
Thank you for your report @hedgefield this should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3802.

**Closed by jorgefilipecosta** 2017-12-05 11:09 UTC
Labels: [Type] Bug
