### ISSUE TITLE
block navigation no longer highlights currently selected block

### ISSUE THREAD

**Issue by njwgh** [WordPress/gutenberg#24520] opened 2020-08-12 12:23 UTC
The block navigation is not highlighting the block that the cursor is currently in

**To reproduce**
Click on a block
Click on the 'Block Navigation'
It has the top block highlighted not the block the cursor is currently in

**Expected behavior**
It should highlight the block that the cursor is currently in

**Editor version (please complete the following information):**
- WordPress version: 5.5
Default Gutenberg
Theme: twentytwenty
NO plugins

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version 84.0.4147.105 

**Screenshots**
![block-navigation](https://user-images.githubusercontent.com/6837919/90014305-29cd4d80-dcea-11ea-9833-ae100c0f44e1.png)

**Comment by Computerbuddha** [comment] 2020-08-14 17:38
Same issue here! And hover not active (sub-)items with the mouse does not change the background color. Also the spacing between the items is bigger than before. On smaller screens - e.g. laptop - this is not so optimal.

**Comment by annezazu** [comment] 2020-08-14 23:25
@njwgh @Computerbuddha it sounds like you might describing this currently open and heavily discussed issue: https://github.com/WordPress/gutenberg/issues/23892 Can you review and, if this matches what you're describing, close this issue out in favor of continuing the discussion there? Thank you!

**Comment by njwgh** [comment] 2020-08-15 01:04
@annezazu  This is NOT the same issue as #23892 
This issue is about the drop-down navigation block, NOT about the highlight of the currently selected block
![image](https://user-images.githubusercontent.com/6837919/90302072-0cb19e00-dee7-11ea-878f-a15e5787c353.png)

**Comment by ellatrix** [comment] 2020-08-17 13:29
Seems like this regressed. @talldan Do you know anything about this?

**Comment by Computerbuddha** [comment] 2020-08-17 17:06
See here the differences between WP 5.4 and 5.5:

![grafik](https://user-images.githubusercontent.com/31189789/90423282-76cf6c00-e0bc-11ea-98dd-6581ae2b3350.png)


![grafik](https://user-images.githubusercontent.com/31189789/90423312-7f27a700-e0bc-11ea-8d6d-e278c2001bb2.png)

**Comment by talldan** [comment] 2020-08-18 04:21
Yes, this does seem like a regression. Looks like it was accidentally removed here in changes that were only supposed to land in the navigation screen:
https://github.com/WordPress/gutenberg/pull/22996/files#diff-3d2c7e20b234263753f1a83b39a15724L59-L66

**Comment by talldan** [comment] 2020-08-18 04:56
Fix was pretty straightforward - https://github.com/WordPress/gutenberg/pull/24609

**Closed** 2020-08-18 10:25 UTC
Labels: [Feature] List View, [Status] In Progress, [Type] Regression
