### ISSUE TITLE
Scaffolded block doesn't register in editor due to @wordpress/scripts version 28.0.0

### ISSUE THREAD

**Issue by wlcdesigns** [WordPress/gutenberg#62390] opened 2024-06-06 22:36 UTC
### Description

Currently, if I use `npx @wordpress/create-block@latest` to scaffold a new block in WP 6.5.4, it does not register. Meaning it does not show up int he editor at all via the inserter or "/". Downgrading @wordpress/scripts to version 27.*.* fixes the issue. The @wordpress/scripts changelog states that 28.0.0 is a breaking change for 6.5.

### Step-by-step reproduction instructions

1. Run `npx @wordpress/create-block@latest my-block`
2. `cd my-block`
3. `npm run build`
4. Navigate to new page or new post
5. Try to find "my-block"

### Environment info
WP 6.5.4

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2024-06-07 07:14
This is duplicate of #62202.

**Closed as not planned by Mamaduka** 2024-06-07 07:14 UTC
Labels: [Type] Bug, [Tool] WP Scripts, [Status] Duplicate
