### ISSUE TITLE
don't reload editor new post 

### ISSUE THREAD

**Issue by NickObrien1** [WordPress/gutenberg#10731] opened 2018-10-18 11:27 UTC
**Describe the bug**
Doesn't load editor of new post, only blank page.

**Comment by Soean** [comment] 2018-10-18 11:36
Hey, @NickObrien1,
can you provide more Information about your WordPress installation? Which Plugin and Themes are you using?

Do you see an error in the browser console?

**Comment by NickObrien1** [comment] 2018-10-18 11:40
adney theme, wordpress 4.9.8.
no, i see blank page, and that's all
![image](https://user-images.githubusercontent.com/18753800/47151900-c9cf1100-d2e3-11e8-8d43-38cc2b6f9edf.png)

**Comment by Soean** [comment] 2018-10-18 11:43
Thanks, for your information. We will try to reproduce the problem.

**Comment by NickObrien1** [comment] 2018-10-18 11:44
thank u too

**Comment by designsimply** [comment] 2018-11-29 20:15
I am closing this issue because of the fatal error related to the theme.

@NickObrien1 if you're still having trouble, can you please try temporarily switching to the Twenty Seventeen theme and re-open the issue if the problem doesn't go away at that point?

**Closed by designsimply** 2018-11-29 20:15 UTC
Labels: [Status] Needs More Info, [Type] Help Request, [Type] Plugin / Theme Interoperability
