### ISSUE TITLE
(Mobile) :hover styles on component menus are following thumb movements

### ISSUE THREAD

**Issue by jobthomas** [WordPress/gutenberg#10320] opened 2018-10-03 21:41 UTC
**Describe the bug**

The `:hover` styles for component menu buttons aren't disabled as they should be resulting in the components menus following the thumb movements. 

**To Reproduce**

1. On mobile, go to adding a new post. 
2. Open any of the component drop down menus and scroll up and done a bit.

**Expected behavior**
On mobile, I'd expect that these styles would not show since hover isn't really an option.

**Screenshots**
Link to screencasts here: http://cld.wthms.co/rOz1SC and here: http://cld.wthms.co/VbiBYh

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 12
 - Browser: Firefox Focus 7.0, but also recreated on Chrome 69.0.3497.105, Safari native
- Gutenberg Version: master

**Comment by kjellr** [comment] 2019-06-17 11:42
Re-opening this issue, since #16168 re-introduces this behavior. 

The method used in #10333 eliminated it, but it also removed the hover state for non-touch-enabled views on small screens, which was not ideal. Ideally, we'd come up with a solution that removes these on small, touch-enabled screens only.

**Comment by jobthomas** [comment] 2019-06-20 10:59
CSS doesn't have a clear option to detect touch-enabled devices yet, but wondering if we can use some of these techniques instead: https://css-tricks.com/touch-devices-not-judged-size/

For example, if we'd be moving the check of hovering to the media query, rather than looking at the screensize, we'd be able to fix this:

`@media (hover: none) { ... }`

**Comment by jobthomas** [comment] 2019-06-20 11:00
And here's the browser adoption rate: https://caniuse.com/#feat=css-media-interaction

**Comment by tellthemachines** [comment] 2020-04-23 03:51
I can no longer reproduce this issue on Android or iOS (xcode simulator), so guessing it must have been fixed with the recent redesign. Closing but feel free to reopen if it's still an issue.

**Closed by tellthemachines** 2020-04-23 03:51 UTC
Labels: Mobile Web
