### ISSUE TITLE
Inactive widgets are invisible - Gutenberg widgets editor

### ISSUE THREAD

**Issue by mrsjaved** [WordPress/gutenberg#32194] opened 2021-05-25 12:07 UTC
## Description
I can't widgets in the inactive widgets area. Those widgets are there but invisible. 

## Step-by-step reproduction instructions

1, Go to Appearance -> Widgets (make sure the new widget editor is enabled)
2. Scroll down to the inactive widgets area.
3. The widgets are invisible. 

## Expected behavior
The widgets are there but invisible due to having the same color as the background I guess.

## Actual behavior
It should display all inactive widgets. 

## Screenshots or screen recording (optional)
https://d.pr/i/obleAH/hrtrmatOu2

Device: MacBook Pro
Operating system: Big Sur
Browser: Chrome
Tested on: Simple site

**Comment by carolinan** [comment] 2021-05-25 13:22
Related: https://github.com/WordPress/gutenberg/issues/31935

**Comment by talldan** [comment] 2021-05-26 09:34
Closing as a duplicate of #31935.

**Closed as completed by talldan** 2021-05-26 09:34 UTC
Labels: [Status] Duplicate, [Feature] Widgets Screen
