### ISSUE TITLE
Typography size setting in Paragraph and Heading block has no undo functionality. 

### ISSUE THREAD

**Issue by Smit2808** [WordPress/gutenberg#39283] opened 2022-03-08 11:24 UTC
### Description

When typography size setting is used in paragraph and heading block. Then after giving some size like 1 or 2 then not able to set to default after selecting some size.

So the solution is after selecting some size by clicking on it, when want to undo it or set to default size again then by clicking the selected size again then it should be set it to the default size.  

### Step-by-step reproduction instructions

1. Add heading/paragraph block.
2. Set the Typography size from block settings.
3. Now want to set it to the default size, but not able to set it to the default size.  

Attaching video link for better understanding.

### Screenshots, screen recording, code snippet

video link: https://www.loom.com/share/620ca5f78a604942b87ea8f921a060cc

### Environment info

-> Wp version 5.9.1
-> Fresh WordPress site, not having any external plugin or theme.
-> Gutenberg cloned from the Github repo trunk branch.
-> Browser chrome.
-> Mac os.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2022-03-09 03:30
I see what you mean. There is a 'Reset all' button here in the dropdown menu:
![Screen Shot 2022-03-09 at 11 29 14 am](https://user-images.githubusercontent.com/677833/157367261-4c15d422-8d36-4381-b14e-1a37f5c32052.png)

But that will reset all typography settings. If you just want to deselect a size, that doesn't seem possible in the UI.

edit: It is also possible to click here and empty out the custom font size field that appears:
![Screen Shot 2022-03-09 at 11 31 40 am](https://user-images.githubusercontent.com/677833/157367509-666f3a30-bb50-4aff-a126-eb66c31b3b1b.png)

**Comment by Smit2808** [comment] 2022-03-09 05:28
Hi @talldan, yes I know that we can undo the size by using "set custom size" settings. But for the user who is not familiar with the "set custom size" setting, then it will be harder for the user. And user will always try to undo the font size by clicking that selected font again. So I think this undo setting we should add this undo setting, from a UI/UX point of view it is very important.

I am working on a patch for this. I am a wp core and meta contributor but I am new to Gutenberg contribution, so any help will be appreciated.

thank you.

**Comment by talldan** [comment] 2022-03-11 07:01
I agree with your points, I was just adding some extra detail to the issue and sharing possible workarounds for anyone that may be reading.

Thanks for volunteering to contribute. Let me know if you need any help with the contribution process for Gutenberg.

I think it would be good to get input from a designer on this issue, so an option might be to reach out in the #design channel in the WordPress slack.

**Comment by cbirdsong** [comment] 2022-03-21 13:49
FYI, there is already discussion of this very confusing design here: https://github.com/WordPress/gutenberg/issues/38219

It's worth noting that if you register more than five font sizes then the control reverts to a `<select>`-style design and this problem goes away entirely: 
![CleanShot 2022-03-21 at 08 51 05](https://user-images.githubusercontent.com/1672206/159275250-dc7604a3-adfc-47b2-8486-6fcf50d957fa.png)

**Comment by talldan** [comment] 2022-03-28 00:51
Thanks for pointing that out @cbirdsong. This issue looks like a duplicate of https://github.com/WordPress/gutenberg/issues/38219, so I'll close it.

**Closed as completed by talldan** 2022-03-28 00:51 UTC
Labels: [Status] Duplicate, [Feature] Design Tools
