### ISSUE TITLE
Unable to Scroll to the Bottom of Long Posts

### ISSUE THREAD

**Issue by mchowning** [WordPress/gutenberg#41116] opened 2022-05-17 19:25 UTC
## Description
When scrolling to the bottom of a very long post, the block list gets "reset" and returns me to the beginning of the post. This essentially makes it impossible to scroll to the end of a long post. 

It feels like both Android and iOS should have this issue, but **I have only been able to reproduce this issue on Android.** 

I've found it easier to reproduce this issue on slower builds (i.e., the demo app or a debuggable WordPress app build). The faster the build, the longer the post I seem to need to recreate the issue.

## Step-by-step reproduction instructions
1. Open a long post (500 paragraphs should be more than enough)
2. Quickly scroll to the bottom of the post (if the bug doesn't occur scroll back to the middle of the post and then back to the bottom again until the bug occurs)
3. Observe that the scrolling will stop and you will suddenly be back at the top of the post.

## Expected behaviour
Scrolling through the post should be fluid and not return you to the top of the post

## Actual behaviour
On long posts, you are sometimes returned to the start of the post.

## Screenshots or screen recording

https://user-images.githubusercontent.com/4656348/168893298-60292baa-11f1-4c7b-9289-0beb334d8c0c.mp4

## Device information
- Device: Pixel 3 and Pixel 6 Pro
- Operating system: Android 12
- WordPress app version: 19.9-rc-1 (I have **not** been able to recreate this issue on 19.8)

**Comment by mchowning** [comment] 2022-05-17 19:32
I can "fix" this issue by commenting out [the `CellRendererComponent` prop within our BlockList](https://github.com/WordPress/gutenberg/blob/b440515cfe42ad895d79dad9ef65ba04521211e2/packages/block-editor/src/components/block-list/index.native.js#L308), but of course that breaks the new drag and drop functionality. It's not clear to me why commenting that out is fixing the issue, but hopefully it can help point us in the right direction for a proper fix.

https://github.com/WordPress/gutenberg/pull/39089 is the PR that added the `CellRendererComponent`, cc: @geriux and @fluiddot

**Comment by fluiddot** [comment] 2022-05-18 08:48
> I can "fix" this issue by commenting out [the `CellRendererComponent` prop within our BlockList](https://github.com/WordPress/gutenberg/blob/b440515cfe42ad895d79dad9ef65ba04521211e2/packages/block-editor/src/components/block-list/index.native.js#L308), but of course that breaks the new drag and drop functionality. It's not clear to me why commenting that out is fixing the issue, but hopefully it can help point us in the right direction for a proper fix.
> 
> #39089 is the PR that added the `CellRendererComponent`, cc: @geriux and @fluiddot

@mchowning, good catch! @geriux already addressed the issue with the `CellRendererComponent` in [this PR](https://github.com/WordPress/gutenberg/pull/41105) 🎊 . Looks like this issue and https://github.com/wordpress-mobile/gutenberg-mobile/issues/4864 are both related to the `onLayout` handler on that component, so that fix will most likely solve both at the same time.

**Comment by geriux** [comment] 2022-05-18 08:53
I can confirm that https://github.com/WordPress/gutenberg/pull/41105 fixes the issue so I'll close this since it was already merged 👍

**Closed as completed by geriux** 2022-05-18 08:53 UTC
Labels: [Priority] High, Mobile App - i.e. Android or iOS
