### ISSUE TITLE
Toolbars are not usable anymore

### ISSUE THREAD

**Issue by corentin-gautier** [WordPress/gutenberg#16505] opened 2019-07-10 13:05 UTC
**Describe the bug**
Toolbars are overlapped by a div making the buttons unreachable

**To reproduce**
1. Make a group block
2. add a block in it
3. try using the group toolbar buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/4660731/60971275-105a1500-a324-11e9-9c38-25d22dac192f.png)

**Additional context**
- since gutenberg 6.0 (working as expected un 5.9.2)

**EDIT:**
Also happen in this situation: 
![image](https://user-images.githubusercontent.com/4660731/60971891-6aa7a580-a325-11e9-8079-17d1bc66f697.png)

**AND**
also this (the parent controls overlap the child controls) : 
![image](https://user-images.githubusercontent.com/4660731/60972261-3385c400-a326-11e9-8817-197cb99e6fc8.png)

**Comment by karmatosed** [comment] 2019-07-18 13:39
I was able to interact with the toolbar. I wonder if it's the combination of blocks you are using? Would you perhaps be able to let me know what those are?

![image](https://user-images.githubusercontent.com/253067/61461998-c8fa0700-a969-11e9-9cd7-2756a3c9ea07.png)

**Comment by mapk** [comment] 2019-07-19 17:47
I've actually experienced this problem recently as well. The toolbars are falling behind the above block so that when I go to click on a particular toolbar option, the block above receives the focus instead of the block toolbar.

**Comment by karmatosed** [comment] 2019-07-19 19:05
Oh that's great @mapk - are you able to give steps to create this, as you can see I failed?

**Comment by mapk** [comment] 2019-07-24 21:39
@enriquesanchez you experienced this recently while using Gutenberg. I can't quite figure out what causes the issue, are you able to?

**Comment by enriquesanchez** [comment] 2019-07-24 22:05
Yep, this is caused by an inline style of `transform: translate3d(0px, 0px, 0px);` on the block. It seems that it's being fixed in https://github.com/WordPress/gutenberg/issues/16519

**Comment by mapk** [comment] 2019-07-24 22:13
This issue was opened 14 days ago while the issue looks to be resolved 13 days ago. Just missed each other. I'm closing although if this continues, please reopen.

**Closed by mapk** 2019-07-24 22:13 UTC
Labels: [Block] Group, [Status] Needs More Info
