### ISSUE TITLE
Navigation Block: Make individual menu item more visible when editing links

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30110] opened 2021-03-22 21:04 UTC
## What problem does this address?

Currently, when editing a link in the navigation block, the UI obscures your ability to see what you're editing which makes for a frustrating experience as shown below:

https://user-images.githubusercontent.com/26996883/112057076-713c7780-8b1e-11eb-97a6-9b39f2c84dfe.mov

This was discovered as part of the [third round of testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/)

## What is your proposed solution?

I'm not sure what's technically possible but it would be great to have a similar interaction to what's in place when editing a link in a paragraph block for example (as shown in the video above).

**Comment by jasmussen** [comment] 2021-03-24 08:09
I'm able to reproduce this in the site editor:

![site editor](https://user-images.githubusercontent.com/1204802/112276114-a06afa00-8c80-11eb-9401-0c1437476730.gif)

But not the post editor:

![nav items](https://user-images.githubusercontent.com/1204802/112276124-a365ea80-8c80-11eb-8d36-3d89e5cba482.gif)

CC: @youknowriad @ellatrix

**Comment by ellatrix** [comment] 2021-03-24 08:35
Looks like that's because for rich text, the link UI is anchored to the link in the content and for navigation its anchored to the toolbar button. Would be good for people working on the navigation block to look into this.

**Comment by jasmussen** [comment] 2021-03-24 08:39
That's the thing, it works fine for the navigation block in the post editor. It does not work for the navigation block in the site editor.

**Comment by ellatrix** [comment] 2021-03-24 08:41
Oh, in that case, let me have a look. :)

**Comment by ellatrix** [comment] 2021-03-24 08:49
Should be fixed in #30173. As I expected, the popover was missing a defined anchor ref.

**Comment by jasmussen** [comment] 2021-03-24 08:50
You are the best of them all.

**Closed as completed** 2021-03-24 10:11 UTC
Labels: [Type] Bug, [Type] Enhancement, [Status] In Progress, [Block] Navigation, [Feature] Site Editor

**Comment by annezazu** [comment] 2021-03-24 14:44
Thank you so much for your speedy work 🌟
