### ISSUE TITLE
Retain formatting when pasting from rich text editor into the WordPress editor

### ISSUE THREAD

**Issue by sundoulos2** [WordPress/gutenberg#26434] opened 2020-10-24 00:39 UTC
Is text formatting supposed to be retained when pasting from a rich text editor like LibreOffice or WPS Office into the WordPress editor? In particular, should the specific font used and paragraph indentation be retained?

You can see in the attached screenshot: bidirectional paste between RichViewActionsTest and WPS Office retains all the formatting except font color. If I copy and paste text from RichViewActionsTest to the WordPress editor (or Google Docs), all the formatting is lost and only the text is pasted in. If I copy and paste text from WPS Office to the WordPress editor, font selection and paragraph indents are lost (see the screenshot). If I copy and paste from WPS Office to Google Docs, all the formatting is retained.
Is this the expected behavior for the WordPress editor?

If I remember correctly, the current behavior is a regression from the previous editor which gave the same results as Google Docs.

A sample docx is available here: [https://drive.google.com/file/d/1OfQCo9m8v0MckqekeVrAxdQt2vMgNgb6/view?usp=sharing]

(url)
![Screenshot_20201023_071017](https://user-images.githubusercontent.com/26822854/97063777-b0669c80-156f-11eb-8579-c9e5d25b5b11.jpg)

**Comment by Mamaduka** [comment] 2021-03-16 05:50
Hi, @sundoulos2

Currently, we're preserving only some formatting (link, bold, italic, etc).

Duplicate of #18381.

**Closed by Mamaduka** 2021-03-16 05:50 UTC
Labels: Needs Testing, [Feature] Raw Handling
