### ISSUE TITLE
Site Editor: 'page-home' template is categorized as a 'General' template

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#30454] opened 2021-04-01 15:07 UTC
## Description

The TT1 Blocks theme has one additional custom page template - 'page-home.html'
In the Site Editor > page templates side navigation panel, the 'page-home' template is grouped under the 'General templates' sub-panel.

## Step-by-step reproduction instructions

1. Go to 'Site Editor'
2. Select 'Browse all templates'
3. In the side nav panel, go to 'Templates' > 'General templates'
4. Notice how the 'page-home' template is available to select in the 'General templates' section.
5. Rename the 'page-home.html' template to something else e.g. 'page-home-one.html' or 'page-bob.html' etc
6. Back in Site Editor, notice how the renamed template is now correctly grouped in the 'Page templates' section.

## Expected behaviour

Custom page templates should be grouped in 'Page templates'

## Actual behaviour

A custom page template with the file name 'page-home.html' is grouped in 'General templates'
I tested with variations of the file name and creating additional page templates, and the only time a custom page template is not grouped in 'Page templates' is when it is specifically named 'page-home.html'

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks. Also same issue with other FSE enabled themes.

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by carolinan** [comment] 2021-04-13 13:12
I named my templates template-page-sidebar-left.html and so on and they show up under general.

**Comment by Sandstromer** [comment] 2021-04-19 15:37
Sorry, I should have clarified page templates beginning with 'page-'

It seems weird how templates that start 'page-' are grouped under page templates, yet 'page-home' is grouped under general.

How is it decided which page templates are 'Page templates', and which page templates are 'General templates'?

**Comment by carolinan** [comment] 2021-05-11 07:06
It looks like it is expecting the home template to be _home_, not _page-home_.

https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/navigation-sidebar/navigation-panel/constants.js

The pr says that "page-home is an exception, it's set to shown up in General" https://github.com/WordPress/gutenberg/pull/28291

So I think it is working as intended?

**Comment by jameskoster** [comment] 2021-05-19 09:13
I think the sections should work as follows:

* The Page Templates section should contain templates that are assigned to specific pages. These are the equivalent of `page-$id` templates in classic themes.
* The Post Templates section should contain templates that are assigned to specific posts. These are the equivalent of `single-post-$slug` templates in classic themes. 
* The General Templates section should contain templates that can be assigned to any post or page. These are the equivalent of `$custom` templates in classic themes.

So I think the issue here is may be the name of the template in tt1-blocks? It needs testing, but as it stands I think any template with a `page-` prefix will function as a general (`$custom`) template until a page with the appropriate suffix is created, at which point it becomes a template for that specific page. IE the `page-home` template in tt1-blocks functions as a `$custom` template until you create a page called "Home" at which point it becomes a specific page template.

**Comment by youknowriad** [comment] 2023-02-24 12:49
The UI has changed a lot here and these sections don't exist anymore.

**Closed as completed by youknowriad** 2023-02-24 12:49 UTC
Labels: [Feature] Site Editor
