### ISSUE TITLE
Why "disableAlpha" for ChromePicker?

### ISSUE THREAD

**Issue by diegoliv** [WordPress/gutenberg#5811] opened 2018-03-27 04:28 UTC
## Issue Overview
Working with the `<ColorPalette />` component, I see that Gutenberg is using [react-color](https://casesandberg.github.io/react-color/), more specificaly the `<ChromePicker />` component. By default, all components from the `react-color` library has a Hue channel and an Alpha channel, including . With the alpha channel, you can effortlessly create a solid color or a transparent color, since the `<ChromePicker />` automatically generates an RBGa / HSLa version of the color you chose. But I see that Gutenberg is disabling the alpha channel with `disableAlpha` on purpose. Any particular reason for that? I can only see benefits of enabling the alpha channel:

* With an RGBa color, you can set a transparent background color on an element. But if you move the alpha value to a separate attribute (like what the cover block is doing), you can't do it. You have to create an extra element (or use a pseudo-element), set the rgb / hsl / hex color to the element, and then set the opacity.
* If you want to parse two attributes (like color and opacity) into an RGBa color, for example, you have to do it yourself.

I want to propose that we should make `disableAlpha` optional. Might be set to `true` by default, but we should allow custom blocks the use of the alpha channel if necessary.

## Possible Solution
`<ColorPallete />` should have an attribute called `disableAlpha` that can be set to `false`, allowing the alpha channel inside the color picker to be displayed.

**Comment by SuperGeniusZeb** [comment] 2018-04-06 04:58
I was recently playing around in the editor and I noticed that there was no way to make the background of a paragraph a transparent color. I do not see any reason to leave out the ability to have transparent colors in the color picker for backgrounds. I can see disabling it for text, but it definitely should not be disabled for things like backgrounds, in my opinion.

**Comment by mcsf** [comment] 2018-07-18 13:08
Duplicate of #4726, closing.

**Closed by mcsf** 2018-07-18 13:08 UTC
Labels: [Type] Enhancement
