### ISSUE TITLE
Cover Block: Deleted Inserted Button Block Keeps Appearing

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#30766] opened 2021-04-12 17:37 UTC
## Description

If you add a button block to the cover block and then delete it, it will reappear when you modify the block alignment settings.

## Step-by-step reproduction instructions

1. Insert a cover block into a post
2. Add a button block
3. Delete the button block
4. Modify the block alignment settings for the cover block

## Expected behaviour

The button block to stay deleted and not to reappear.

## Actual behaviour

The button block reappears.

## Screenshots or screen recording (optional)

https://youtu.be/iGukon3rJAA

## WordPress information
- WordPress version: 5.7
- Gutenberg version:  Not Installed
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes, Twenty Twenty-One

## Device information
- Device:  Desktop
- Operating system:  Windows 10
- Browser:  Microsoft Edge Version 89.0.774.68

**Comment by deborah86** [comment] 2021-04-12 18:51
@Soean I noticed the bug tag wasn't added. Is this a bug?

**Comment by Soean** [comment] 2021-04-12 18:59
@deborah86 I can reproduce the bug and added the label.

**Comment by annezazu** [comment] 2021-04-12 19:49
Hey all! Thanks so much for opening more issues @deborah86. Great snag. In this case, this is actually due to a wider problem with the block button itself rather than specifically in the Cover block. I'm going to close this out as a result in favor of the original issue that touches on this frustrating experience: https://github.com/WordPress/gutenberg/issues/28217#issuecomment-816054217 

By the way, it's super neat to see the issues you've opened 🤩 . I tried to find you in the Making WordPress Slack ([you can sign up here](https://make.wordpress.org/chat/)) to more personally say thank you. If you end up joining or want to generally chat about contributing to WordPress, please feel free to ping me. I'm @annezazu on slack too!

**Closed as completed by annezazu** 2021-04-12 19:49 UTC
Labels: [Type] Bug, [Block] Cover
