### ISSUE TITLE
Confusing editor mode switching (Visual/Code Editor)

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#12374] opened 2018-11-27 19:58 UTC
## Description

Options to switch between "Visual Editor" and "Code Editor" mode are pretty confusing. They basically work like radio buttons, however, the checkmark icon sets expectation they would work the same way as, for example, the "Top Toolbar" option, which is basically a toggle button (a checkbox). 

## Expected behavior

Not sure whether "Visual Editor" option is even needed. Could there only be a "Code Editor" option that works like a toggle button?

## Video

https://www.dropbox.com/s/aw2x03xjjwja1u3/gutenberg-editor-mode-switching.mp4

## Additional context
- Gutenberg v4.5.1
- Tested at https://wordpress.org/gutenberg/

**Comment by swissspidy** [comment] 2018-11-28 06:44
Not sure how well a toggle button would work accessibility-wise. Just so that it won‘t be forgotten.

**Comment by webmandesign** [comment] 2018-11-28 10:51
Yes, accessibility is also my concern.
But I'm coming from presumption that those already included toggle buttons ("Top Toolbar" option, for example) are accessible. So, implementing similar functionality for editor mode switcher shouldn't be a problem(?).

**Comment by mapk** [comment] 2019-04-06 00:25
An additional benefit for keeping them as they are is it helps with terminology. If we eliminate the "Visual editor" choice, people begin to call it all sorts of things.

**Comment by Nobiuss** [comment] 2019-06-20 12:45
Hi,

I understand the confusions about this because the look is the same and they don't act the same.
Maybe it is best if there would be some kind of a switch for the visual or code editor.
I will add a mockup for this, how it can look.

![image (2)](https://user-images.githubusercontent.com/28691640/59850185-ee472580-9369-11e9-85cf-56ac7359bce6.png)

Kind regards,
Kim

**Comment by afercia** [comment] 2019-06-29 07:58
Worth reminding the "More" dropdown is an [ARIA menu](https://www.w3.org/TR/wai-aria-practices-1.1/#menu), and as such can contain exclusively items of type `menuitem`, `menuitemcheckbox`, `menuitemradio`.

**Comment by mapk** [comment] 2019-08-13 02:48
I'm taking another look at how the Code Editor might work as a whole in this other issue: 
https://github.com/WordPress/gutenberg/issues/17017

Chances are, it will affect this issue too.

**Comment by youknowriad** [comment] 2020-01-16 17:38
Is this still an issue? As raised by @afercia The Menu is an aria menu that only contains menu items (with their keyboard interactions).

**Comment by webmandesign** [comment] 2020-01-22 09:38
Well, for me I can still see the issue simply from user experience perspective. But it's up to you guys what works best. I'd appreciate the toggle button or something similar, but if it's not implemented, I will deal with current state of the things :)

**Comment by youknowriad** [comment] 2020-01-22 10:09
I'm going to close this as works as intended. While I appreciate the opinion, we still need to make this good a11y wise and it seems that the dropdown being an aria menu is the way to go.

**Closed by youknowriad** 2020-01-22 10:09 UTC
Labels: General Interface, Needs Design Feedback
