### ISSUE TITLE
Video block is unselectable once upload completes

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#22589] opened 2020-05-25 00:15 UTC
**Describe the bug**
After uploading a video using the video block, the block becomes unselectable

![video](https://user-images.githubusercontent.com/22446385/82768026-7e8dc480-9e6f-11ea-879d-1fc68c67e8c5.gif)

**To reproduce**
1. Go to the editor
2 Add a video block
3. Upload a sample video
4. The video becomes unselectable! (see gif)

**Expected behavior**

**Editor version**
- On wordpress.com atomic site running 8.1.0
- Interestingly, I created a new atomic site and could not reproduce this, however I was able to see it on existing atomic sites.
 - I tested with firefox on macos

** More context **

This bug was also introduced along with an upgrade notice issue. This card tracks handling the same bug from the jetpack side. https://github.com/Automattic/jetpack/issues/15796

This bug can be fixed in the short term by reverting https://github.com/WordPress/gutenberg/pull/22028 which is the fix we've released to wordpress.com.

**Comment by talldan** [comment] 2020-05-25 04:01
I'm not able to reproduce any issue selecting the block (also testing using Firefox on Mac OS X) against latest `master`.

@roo2 Is this bug only happening on wordpress.com? I don't think the ticket should be created here if it's only an issue there.

I'm closing the issue, but can reopen it if we can establish that there's a bug in the gutenberg codebase.

**Closed by talldan** 2020-05-25 04:01 UTC
Labels: Needs Testing, [Block] Video

**Comment by ockham** [comment] 2020-05-25 17:24
I've moved this over to the Jetpack repo, where the relevant block lives: https://github.com/Automattic/jetpack/issues/15922
