### ISSUE TITLE
Pressing delete key within a paragraph containing an anchor deletes the anchor (Firefox)

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#25598] opened 2020-09-24 02:32 UTC
_Originally reported in https://core.trac.wordpress.org/ticket/45992._

When editing a paragraph containing an anchor (e.g. `<a id="test"></a>`) in Firefox (64.0.2, macOS 10.14.2), pressing the delete key to delete any text in the paragraph removes the anchor, regardless of the position of the cursor in relation to the anchor within the paragraph. This affects:

- Classic Editor
- Gutenberg (Classic Block)
- Gutenberg (Paragraph)

This behaviour occurs with WordPress 5.0.3, with and without the Classic Editor plugin installed. I cannot reproduce the issue in Chrome or Safari.

Demo videos:

- Classic Editor: https://cl.ly/cd80dd3c8cf8
- Gutenberg https://cl.ly/24307cf3c26c

**Comment by tellthemachines** [comment] 2020-09-30 04:54
I can't reproduce this on 5.5.1 or on the latest master, so guessing it was fixed in the meantime. Safe to close?

**Comment by skorasaurus** [comment] 2021-06-30 16:23
(I'm also unable to reproduce).

**Closed** 2021-06-30 16:23 UTC
Labels: Browser Issues, [Feature] Rich Text, [Type] Bug
