### ISSUE TITLE
Gutenberg / Wordpress adding <br> element when enter is pressed

### ISSUE THREAD

**Issue by Armadur** [WordPress/gutenberg#11048] opened 2018-10-25 09:57 UTC
**Describe the bug**
When pressing enter and "formatting" code Gutenberg adds new element as represents as <br>
When editing code, that element is not visible, but somehow, browser compiles it and element is there, in DOM

**To Reproduce**

1. Add some html 
2. format code with adding space between and pressing "Enter" button
3. Update

**Expected behavior**
Just format code, don't add anything

**Screenshots**
![image](https://user-images.githubusercontent.com/26959135/47492236-d526bd00-d84c-11e8-9900-dff2872299ad.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome 
 - Version 69

**Additional context**
**Versions:**
_Wordpress 4.9.8_
_Gutenberg 4.1.0_

**Comment by ideadude** [comment] 2018-10-28 19:01
Can you be more clear on the steps to reproduce?

What do you mean by "Add some html"?

* What specific HTML did you add?
* Are you using the Custom HTML block?
* Are you using the Class block in HTML mode?

What do you mean by "format code with adding space between"? Did you add the br tags to the html inside the span/etc? Or did those show up on their own somehow?

I notice the span has the class hidden-xs. Is this part of a theme or plugin? Which one? Is it custom? Perhaps the hidden-xs class is defined in a css file that is only loaded in the admin. In this case, it would hide things in the admin but show them on the frontend.

**Comment by mcsf** [comment] 2018-11-26 15:29
There doesn't seem to be an issue here. `<br>` tags are HTML's representation of a line break, inserted upon pressing <kbd>Enter</kbd>.

Closing issue. Please comment with more details if needed.

**Closed by mcsf** 2018-11-26 15:29 UTC
Labels: [Status] Needs More Info

**Comment by shuttermuse** [comment] 2019-01-04 10:07
This is a problem for anyone using the Amazon Associates program (tens or even hundreds of thousands of people?)

WP5 added br tags at the end of each line in the Amazon ad code. This breaks it and it won't display. It doesn't just do it on new posts, it did it on every post. So anyone using the Amazon Native ads in their post has lost them all. For me it is hundreds and hundreds of ads.

Here is an example of the issue. Without those br tags the ads used to display just fine. Now they are all broken. 

`<p><script type="text/javascript"><br />
amzn_assoc_tracking_id = "EXAMPLE";<br />
amzn_assoc_ad_mode = "manual";<br />
amzn_assoc_ad_type = "smart";<br />
amzn_assoc_marketplace = "amazon";<br />
amzn_assoc_region = "US";<br />
amzn_assoc_design = "enhanced_links";<br />
amzn_assoc_asins = "B079Y45KTJ";<br />
amzn_assoc_placement = "adunit";<br />
amzn_assoc_linkid = "6c4721f9ed7f9cd9738d7947175d8ef2";<br />
</script><br>
<script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US"></script></p>`

I did find mention of this some time back by someone else, but it looks like it wasn't taken into account. 

I can't even begin to imagine how much money this is going to cost some people who rely on these ads. As far as I can see, there's no way to get them to work. I tried putting them in a code block, in a classic bock etc. etc. Every time the tags get added and the ad breaks.

**Comment by Ruud-Mens** [comment] 2019-04-23 08:03
@shuttermuse did you find a solution for this? Just noticed that some older articles of mine have the same issue.

**Comment by shuttermuse** [comment] 2019-04-24 17:35
No real solution other than going back in and manually fixing it. To do
that you have to take all your code and place it into an HTML block, then
manually delete all the extra br> tags.

**Comment by ultrageek** [comment] 2020-08-01 20:29
> No real solution other than going back in and manually fixing it. To do that you have to take all your code and place it into an HTML block, then manually delete all the extra br> tags.

I had the same problem with a <script> block I wrote. I manually removed all the <br> and <p> tags, but WP stuck them all back in.

**Comment by ultrageek** [comment] 2020-08-01 20:33
> There doesn't seem to be an issue here. `<br>` tags are HTML's representation of a line break, inserted upon pressing Enter.

They're HTML's representation, not a text editor's. That would be \n, the way WordPress used to work. So yes, there is an issue. WordPress now mangles lines within a custom block of WP by adding br tags at the end (and p tags as well). So code within a script block turns into mangled HTML instead of staying as JavaScript.

**Comment by mcsf** [comment] 2020-08-10 10:59
I suggest looking at the Custom HTML block, since it seems like a similar case to the one in this comment https://github.com/WordPress/gutenberg/issues/11048#issuecomment-451403129. In particular, it doesn't inject BR tags and relies on newline characters as you'd expect:

https://github.com/WordPress/gutenberg/blob/665a2602a8ef9963504d0fdca9855219d1700cdb/packages/block-library/src/html/edit.js#L99-L106

It hinges on the PlainText component. See its [README file](https://github.com/WordPress/gutenberg/blob/665a2602a8ef9963504d0fdca9855219d1700cdb/packages/block-editor/src/components/plain-text/README.md#plaintext).
