### ISSUE TITLE
Site Editor: Incorrect text padding when adding background color to blocks

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#23937] opened 2020-07-14 19:23 UTC
## Describe the bug
For any block with a background color set as a direct child of a group block, text padding isn't appropriately applied.

## To reproduce
1. Navigate to the site editor
2. Create a group block
3. Within the group block, create any block that supports background color changes (paragraph, site tagline, etc.)
4. Modify the background color (it's easier to see the bug with a dark background)
5. Notice that the text looks improperly aligned

## Expected behavior
Block content implements appropriate padding when adding a background color is added

## Screenshots
<img width="1409" alt="Screen Shot 2020-07-14 at 12 26 16 PM" src="https://user-images.githubusercontent.com/5414230/87468155-f2c22a00-c5cd-11ea-99ed-90753081bc13.png">

## Notes
After some digging, it looks like padding styles are being overwritten by `group` block css [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/group/editor.scss#L42-L71) on L51-52 and L59-60.

### Correct Padding
<img width="1824" alt="Screen Shot 2020-07-13 at 5 08 43 PM" src="https://user-images.githubusercontent.com/5414230/87365752-e7b6bd80-c52b-11ea-9bd4-e508139b22d3.png">

### Incorrect Padding
<img width="1825" alt="Screen Shot 2020-07-13 at 4 51 09 PM" src="https://user-images.githubusercontent.com/5414230/87365755-e8e7ea80-c52b-11ea-8cd2-9d75e1e1967f.png">

**Editor version (please complete the following information):**
- WordPress v5.4
- Gutenberg Plugin v8.5

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.5
 - Chrome, Firefox, Safari

**Comment by carolinan** [comment] 2021-03-24 10:14
I am not able to reproduce this.

Empty theme:
![image](https://user-images.githubusercontent.com/7422055/112292624-8f76b480-8c91-11eb-9fb8-e626de0b5902.png)

I was not able to re-test in Seedlet Blocks today because of unrelated issues with the current Gutenberg trunk.

**Comment by annezazu** [comment] 2021-04-16 17:03
I wasn't able to reproduce this with Gutenberg 10.4 and WordPress 5.7 using TT1 Blocks. Going to close this out as a result but, as always, feel free to reopen :)

**Closed by annezazu** 2021-04-16 17:03 UTC
Labels: [Feature] Full Site Editing, [Type] Bug
