### ISSUE TITLE
Reusable Block

### ISSUE THREAD

**Issue by stan-luburic** [WordPress/gutenberg#25052] opened 2020-09-03 15:47 UTC
All my reusable blocks are disabled, on all my previous posts.
I tried re-import JSON file of blocks, but nothing. It happened next to upgrade to Gutenberg 8.9.1

In block editor I can see the reusable block OK, but when I want to preview, it doesn't appear.

I want to use reusable blocks just like before.

- WordPress version: 5.5.1
- GUtemberg activated 8.9.1

 - OS: Windows
 - Browser: Chrome

**Comment by mikeyh** [comment] 2020-09-03 23:52
Looks to be broken since 8.9.0

**Comment by mikeyh** [comment] 2020-09-19 14:51
Anyone able to confirm when this will be fixed or if fixed in 9.0.0 but missed from release notes?

**Comment by tellthemachines** [comment] 2020-09-29 03:51
@mikeyh I am not able to reproduce this on 9.0.0.

My testing steps were:
1. On WP 5.5 with Gutenberg plugin disabled, create a reusable block inside a post. 
2. Add reusable block inside another post, and verify that it renders in the front end.
3. Activate the Gutenberg plugin (9.0.0).
4. Go back to post and verify that reusable block is still rendering in both the editor and the front end.

Have I missed anything? Could you confirm if it works for you with 9.0.0?

**Comment by mikeyh** [comment] 2020-09-29 08:38
Confirmed fixed in 9.0.0 with WP 5.5.1 in live sites.

Also tested with Advanced Gutenberg 2.4.6

**Comment by talldan** [comment] 2020-10-22 01:48
Seems like this is resolved, and the fix should be in WordPress 5.6 given it was fixed in Gutenberg 9.0. 

Should we close this @tellthemachines?

**Comment by tellthemachines** [comment] 2020-10-26 00:36
Yup, closing. Thanks everyone!

**Closed by tellthemachines** 2020-10-26 00:36 UTC
Labels: [Feature] Reusable Blocks, [Type] Bug
