### ISSUE TITLE
Cursor moves unexpectedly when backspacing over a line break

### ISSUE THREAD

**Issue by wpalchemist** [WordPress/gutenberg#6789] opened 2018-05-16 18:25 UTC
**Describe the bug**
If you have text on multiple lines, and you put your cursor at the beginning of a line and hit "backspace", the cursor jumps to a different place.

**To Reproduce**
1. Create a paragraph block with a bunch of line breaks in it
2. Convert the paragraph to a bulleted list.  When you do this, there will only be one bullet, so the easiest way to replace each line break with a bullet is to go to the beginning of each line, hit backspace to remove the line break, and then hit enter to add a bullet.
3. When you put your cursor at the beginning of a line and hit backspace, the cursor will jump to a different place in the text.

**Expected behavior**
The cursor should stay in the same place.

**Screenshots**
[https://imgur.com/a/FH9vP7t](https://imgur.com/a/FH9vP7t)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 59

**Additional context**
Gutenberg version 2.8.0

**Comment by danielbachhuber** [comment] 2018-05-16 21:00
Hi @wpalchemist,

Thanks for the report. Can you make sure you're running the most recent version of Firefox?

This may be a duplicate of #5243

**Comment by wpalchemist** [comment] 2018-05-18 16:25
I just updated to Firefox 60, and I can't reproduce the error any more.

**Comment by danielbachhuber** [comment] 2018-05-18 16:31
Thanks @wpalchemist !

**Closed** 2018-05-18 16:31 UTC
Labels: [Status] Needs More Info
