### ISSUE TITLE
Quote block: Multi-paragraph quotes should be possible (like with <blockquote>)

### ISSUE THREAD

**Issue by orenwolf** [WordPress/gutenberg#24833] opened 2020-08-26 17:45 UTC
**Is your feature request related to a problem? Please describe.**
Currently, if you are attempting to replicate the functionality of <blockquote> with a multi-paragraph quote, there's no mechanism to do this within the quote block. If you attempt to paste a quote into a block that has multiple paragraphs, these will instead be split out into paragraph blocks instead. There is no way to, for example, quote an excerpt from a news article without having to manually create a new quote block for each paragraph.

**Describe the solution you'd like**
Since quote blocks are often filled with copied data from other sources, the likelihood that you are pulling from a source with blank lines between paragraphs is very high. Allowing for this formatting within a quote block, similar to what would happen in the classic editor with a <blockquote> text block, should be possible.

**Describe alternatives you've considered**
Automatically splitting a multiparagraph quote into multiple _quote_ blocks, instead of plain _paragraph_ blocks, would be better, though then the citation would likely only be linked to the final quote block in that situation.

Thanks!

**Comment by youknowriad** [comment] 2020-08-26 22:20
Thanks for the issue, this is a duplicate of #4992 which was closed in favor of #15486

**Closed by youknowriad** 2020-08-26 22:20 UTC

**Comment by GhBsx-png** [comment] 2020-08-26 23:06
Ok, thank you for your assistance
