### ISSUE TITLE
Add color selection icon to caption toolbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12282] opened 2018-11-25 08:33 UTC
**Is your feature request related to a problem? Please describe.**
One needs to add CSS to be able to adjust the color of the caption.

![screen shot 2018-11-25 at 09 25 54](https://user-images.githubusercontent.com/5323259/48977109-5c599180-f094-11e8-8ed2-489351e913e9.png)

**Describe the solution you'd like**
I would like to see a color select icon in the caption toolbar. Perhaps something like this:

![gutenberg-color-caption-option](https://user-images.githubusercontent.com/5323259/48977144-ffaaa680-f094-11e8-9680-15da02be2b92.jpg)

**Describe alternatives you've considered**
Figuring out the caption css and then modifying that with the color I want to use for the caption.

**Comment by swissspidy** [comment] 2018-11-25 14:07
Not sure how common that use case is, but color settings are usually in the block sidebar. So in this case it could be added there as well.

**Comment by paaljoachim** [comment] 2018-11-25 16:15
Yup, color for affecting the background and the text is in the sidebar.
I was thinking that for smaller cases such as a caption for single and gallery captions (I am also thinking that other cases will show up) it could be added directly into the caption toolbar. As the caption toolbar has the direct affect on the caption and is very localized just above it.

Use case is wanting another color for the caption text.

**Comment by iseulde** [comment] 2018-11-26 09:10
For now you can use https://wordpress.org/plugins/advanced-rich-text-tools/.

**Comment by paaljoachim** [comment] 2018-11-26 15:05
Thanks Ella!

**Comment by iseulde** [comment] 2019-02-08 10:02
Closing as there are no plans of adding this by default in core. This issue is also a duplicate of #10225.

**Closed by iseulde** 2019-02-08 10:02 UTC
Labels: [Block] Gallery, [Type] Enhancement

**Comment by phpbits** [comment] 2019-05-17 15:13
@paaljoachim  I've added text highlighting color options on EditorsKit plugin ( https://wordpress.org/plugins/block-options/ ). Here's how my implementation works :

![Gutenberg Highlighted Text and Background Colors](https://user-images.githubusercontent.com/3365507/57937370-60a29100-78f8-11e9-8069-06a8ec43259d.gif)

**Comment by paaljoachim** [comment] 2019-05-21 10:34
That sounds very cool Jeffrey!

**Comment by phpbits** [comment] 2019-05-21 10:43
Thanks @paaljoachim! Really glad you like it :)
