### ISSUE TITLE
Heading's Advanced metabox content order is not persistent

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#20417] opened 2020-02-24 17:38 UTC
**Describe the bug**
Based on an issue recorded here: https://wordpress.org/support/topic/ordering-of-advanced-options-in-editor/

The Advanced metabox shows two options for a Heading block: CSS class and an HTML anchor. These two options switch visual order if the user converts a Paragraph block to a Heading block.

**To reproduce**
1. Add a Heading block.
2. Open the Advanced metabox and note the order of options: HTML anchor then CSS Class.
3. Add a Paragraph block with content.
4. Convert that block to a Heading block. 
5. Open the Advanced metabox and note the order of options: CSS Class then HTML anchor.

**Expected behavior**
The content order should remain the same regardless of how the Heading block was created.

**Screenshots**

**Creating a Heading block**

![Screen Shot 2020-02-24 at 9 31 46 AM](https://user-images.githubusercontent.com/617986/75176557-38e32380-56e9-11ea-976b-aebc211348b6.png)

**Converting a Paragraph block to a Heading block**

![Screen Shot 2020-02-24 at 9 32 25 AM](https://user-images.githubusercontent.com/617986/75176579-426c8b80-56e9-11ea-8ec4-c26f4b877644.png)

**Comment by donmhico** [comment] 2020-02-28 18:07
Hello @mapk,

Unfortunately, I can't replicate the issue.

![Kapture 2020-02-29 at 1 43 39](https://user-images.githubusercontent.com/5747475/75573562-13169f80-5a98-11ea-951b-fe55c1b587bd.gif)

**Comment by mapk** [comment] 2020-03-06 21:30
I just tested again with G2 styling and am still getting this mix up.

**Added a heading to the page**

![Screen Shot 2020-03-06 at 1 29 16 PM](https://user-images.githubusercontent.com/617986/76123986-a24b1800-5fae-11ea-89ea-c279f4d9b32f.png)

**Added a paragraph and then converted to heading**

![Screen Shot 2020-03-06 at 1 29 36 PM](https://user-images.githubusercontent.com/617986/76124008-ac6d1680-5fae-11ea-83d3-5a0f5215fcbb.png)

**Comment by youknowriad** [comment] 2020-06-16 09:16
This looks like a duplicate of #7964

**Closed by youknowriad** 2020-06-16 09:16 UTC
Labels: [Block] Heading, [Block] Paragraph, [Type] Bug
