### ISSUE TITLE
InnerBlocks Template Adjustments Cause Content Loss

### ISSUE THREAD

**Issue by michealengland** [WordPress/gutenberg#8109] opened 2018-07-21 17:09 UTC
**Describe the bug**
I've been playing around with the InnerBlocks template options found here [InnerBlocks](https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks). I've noticed when removing an existing block or adding a new block that the template will remove new blocks and re-add any of the missing template blocks. The same is also true if you use templateLock={ false }. 

**To Reproduce**
Create a basic InnerBlocks with a template that can be found here [InnerBlocks](https://github.com/WordPress/gutenberg/tree/master/editor/components/inner-blocks).
Once you have a custom block template add it to the editor and insert or remove a template block. Next update the page/post and refresh the editor. 

**Expected behavior**
I expected that an unlocked template would keep it's current state upon save / editor refresh if a block has been added or removed instead of reverting back to the original template.

**Screenshots**
Before New Content
<img width="1075" alt="screen shot 2018-07-21 at 1 03 21 pm" src="https://user-images.githubusercontent.com/25035900/43038464-fd822296-8ce6-11e8-90f8-d89e15fa7766.png">
Newly Added Content
<img width="1099" alt="screen shot 2018-07-21 at 1 05 25 pm" src="https://user-images.githubusercontent.com/25035900/43038465-fd8ecd70-8ce6-11e8-9d37-37bdec3a782b.png">
After Save
<img width="1074" alt="screen shot 2018-07-21 at 1 05 44 pm" src="https://user-images.githubusercontent.com/25035900/43038466-fd9bad74-8ce6-11e8-9ffe-af01b64b9c72.png">

**Desktop (please complete the following information):**
 - OS: [10.13.6]
 - Browser [Mozilla Developer Edition]
 - Version [62.0b6 (64-bit)]

**Additional context**
- Gutenberg Version tested on 3.2 / 3.3

**Comment by brettsmason** [comment] 2018-07-30 15:07
I think I'm experiencing the same issue as the above.
If it helps, my code for the `InnerBlocks` portion looks like this:

```
<InnerBlocks
	allowedBlocks={ [
		'core/heading',
		'core/paragraph',
		'core/button',
		'core/list'
	] }
	template={ [
		[ 'core/heading' ],
		[ 'core/paragraph' ],
		[ 'core/list' ],
	] }
	templateLock={ false }
/>
```
If I add a list or button block in the editor and save, those blocks are no longer visible upon refresh.

**Comment by mikemcalister** [comment] 2018-08-21 17:29
I'm also having the same issue as described above. When I try to set a template, any additional content that is added to the block disappears on refresh. The newly added content is visible on the front end, but does not display in the editor. [Here is a video](https://cl.ly/2E1O1X3Q0t3a) showing the bug.

```
<InnerBlocks
	template={[
		// Add placeholder blocks
		['core/heading', {
			content: 'We Build Blocks',
			level: '3',
		}],
		['core/paragraph', {
			content: 'Lorem ipsum dolor sit amet elit do, consectetur adipiscing, sed eiusmod tempor incididunt ut labore et.'
		}],
		['atomic-blocks/ab-button', {
			buttonText: 'Find Out More',
			buttonAlignment: 'left',
		}],
	]}
/>
```

Another quirk with the template, I can change the text within those placeholder blocks and it will update as expected, but if I try to delete a placeholder block entirely, it will regenerate after save and refresh.

**Comment by jorgefilipecosta** [comment] 2018-08-24 17:53
I'm able to reproduce this problem in a simple test block.

**Comment by felixarntz** [comment] 2018-08-25 13:14
I ran into a similar issue and accidentally opened a duplicate of this issue with #9349. I'll paste my sample code into here for easy replication of the issue:

```js
const { Fragment } = wp.element;
const {
	InnerBlocks,
} = wp.editor;
const { __ } = wp.i18n;

const ALLOWED_BLOCKS = [ 'core/image' ];
const TEMPLATE = [
	[ 'core/image' ],
	[ 'core/image' ],
	[ 'core/image' ],
];

export const name = 'myplugin/test';

export const settings = {
	title: __( 'Test', 'textdomain' ),
	category: 'layout',
	icon: 'grid-view',
	attributes: {},
	edit: () => {
		return (
			<Fragment>
				<div className="my-blocks-container">
					<InnerBlocks
						allowedBlocks={ ALLOWED_BLOCKS }
						template={ TEMPLATE }
						templateLock={ false }
					/>
				</div>
			</Fragment>
		);
	},
	save: () => {
		return (
			<div className="my-blocks-container">
				<InnerBlocks.Content />
			</div>
		);
	},
};
```

The issue is a result of the `InnerBlocks` component calling `synchronizeBlocksWithTemplate()` from `@wordpress/blocks` unconditionally. That function will match the blocks with the template and strip everything that doesn't match. It should instead look at `templateLock` first and only call the function if its value is not set to 'all'. This would be in line with how the editor globally handles this.

**Comment by phpbits** [comment] 2018-09-05 14:04
@aduth @gziolo I hope you don't mind the tags. I'm having similar issue and I hope you can enlightened us. Thank you very much!

**Closed** 2018-09-20 15:21 UTC
Labels: [Component] Nested / Inner Blocks, [Type] Bug

**Comment by michealengland** [comment] 2018-09-21 11:05
@jorgefilipecosta Thanks for getting this one solved! So excited to see it closed.
