### ISSUE TITLE
WP 6.4 RC2 Cover block with button has no background color options

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#55666] opened 2023-10-27 16:57 UTC
### Description

When you use the cover block with a button in 6.4 RC2, most of the button color background options dissapears except for the base and contrast colors. Please see the screen recording: https://www.loom.com/share/6c1b4448b1e344cb8e65f1811cba8218?sid=4cb69431-e474-4ddc-829b-20233eb52a0f
I tried this TT3 and TT4 themes both having same issues

### Step-by-step reproduction instructions

Create cover block
than button on the cover block
click on the button and style
click on the background color the button color background options despairs except for the base and contrast colors

### Environment info

WP 6.4 RC2 
Deactivate Gutenberg 16.9.0 or activated I am seeing same issues

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment] 2023-10-28 03:29
Thanks for the report.

> WP 6.4 RC2
> Deactivate Gutenberg 16.9.0 or activated

I tested it in this environment, but I was unable to reproduce it on both TT3 and TT4. Have you made any changes to your theme's global styles or color palette?

![color](https://github.com/WordPress/gutenberg/assets/54422211/f84ae73b-dec7-453c-9380-51e2519f6d1e)

**Comment by lwangdu** [comment] 2023-10-28 20:14
No, I didn't change global styles or color palette. I just download again TT4 and tested. It still happening.
![Screenshot 2023-10-28 at 1 11 19 PM](https://github.com/WordPress/gutenberg/assets/24829573/ab0c463d-174a-4e60-8041-9f95dde4eb47)
Maybe this is something to do with caching.

**Comment by lwangdu** [comment] 2023-10-28 20:22
I did test with Firefox and Chrome. It still happening same issue.

**Comment by annezazu** [comment] 2023-10-31 11:06
Thanks for this report. I'm unable to replicate either and won't be adding to the 6.4 board until we can.

**Comment by lwangdu** [comment] 2023-10-31 15:57
@annezazu Thanks for checking on this issue. I installed a new site on my local machine and tested the Cover block with a button color again. It works fine on the new site, so there may have been something wrong with my previous installation.

Thank you!

**Comment by annezazu** [comment] 2023-10-31 19:08
Of course! Thanks for testing again. I'll close this out but please keep sharing feedback and opening issues <3

**Closed as completed by annezazu** 2023-10-31 19:08 UTC
Labels: [Type] Bug, Needs Testing, [Block] Cover, [Block] Buttons, [Feature] Colors
