### ISSUE TITLE
Feature request: Allow decimals in padding controls, or, update the padding for blocks with background colors.

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#32645] opened 2021-06-12 07:20 UTC
## What problem does this address?

**This is very much an edge case.**
The default padding for blocks with background color is:
```
// Padding for blocks with a background color (e.g. paragraph or group).
$block-bg-padding--v: 1.25em;
$block-bg-padding--h: 2.375em;
```
But if I want the padding to be consistent I can not add 2.375 em using the control.
It is reset to the closest number without decimals.
So my only other option is to override this default padding.

## What is your proposed solution?

Allow decimals in padding controls, or, update the padding for blocks with background colors.

**Comment by justintadlock** [comment] 2021-06-13 13:29
Related: https://github.com/WordPress/gutenberg/issues/31964

**Comment by talldan** [comment] 2021-06-14 04:38
Duplicate of #31964

**Closed as completed by talldan** 2021-06-14 04:38 UTC
Labels: [Status] Duplicate
