### ISSUE TITLE
"Error while uploading file ... to the media library"

### ISSUE THREAD

**Issue by torres126** [WordPress/gutenberg#9878] opened 2018-09-13 16:50 UTC
**Describe the bug**
Whilst writing a blog post using Gutenberg, a red message appears saying that there was an error whilst uploading the file

**To Reproduce**
1. Start writing a blog post via Gutenberg
2. Add an Image Block
3. Try and upload the image from your device

**Expected behavior**
The image should have uploaded to the Media Library without any issues, ready for me to embed.

I was able to upload images just fine on any other editor, including whilst uploading it directly to the Media Library when not writing a post, which leads me to believe this is an issue with Gutenberg.

**Screenshots**
See here: https://clubpenguinmountains.files.wordpress.com/2018/09/gsdfsgfdsfgdsdfg.png

(Seems I'm unable to upload them directly to GitHub for some reason, sorry)

**Desktop (please complete the following information):**
 - Mac 10.6.8
 - Chrome
 - Version 44

**Additional context**
- Using the Gutenberg version rolled out on WordPress.com

Thanks! :)

**Comment by davoraltman** [comment] 2018-10-24 19:13
I'm not able to reproduce the red message from your screenshot when using the currently latest version of Gutenberg (4.1.0).

However, I am not able to upload any images in the editor when using Gutenberg. I tried to upload the image from the computer and recorded a short video - https://cld.wthms.co/Ma8047

The same happens when I try to drag-and-drop the image into the editor.

On the other hand, uploading via the classic editor and directly into the Media file works.

Chrome 69.0.3497.100
Mac 10.13.6

**Comment by adamleone** [comment] 2018-10-30 17:37
I wasn't able to replicate this issue, I could upload an image into the editor ok. 

I recorded my findings here: http://cld.wthms.co/jgWTWT maybe this was fixed?

**Comment by youknowriad** [comment] 2018-11-03 18:38
Closing as we can't replicate, let's reopen if there's any more details about how to replicate the issue.

**Closed by youknowriad** 2018-11-03 18:38 UTC
Labels: Needs Testing, [Type] Help Request
