### ISSUE TITLE
Custom HTML block not displaying in Chrome 83 / MacOS but works in Chrome 83 / Windows 10

### ISSUE THREAD

**Issue by BajaBarry** [WordPress/gutenberg#23943] opened 2020-07-14 21:29 UTC
Using the latest versions of WordPress and Mac and Windows OSs. Deactivated Gutenberg plugin and still have the problem. The HTML code (from Amazon) shows but using Preview in the block results in blank space on MacOS whereas the expected content displays on Windows, and in FireFox on MacOS (have not tried all the browsers, but I use Chrome most). Same result if use the Preview post tool. The post is still a draft. 

The HTML looks like:

![image](https://user-images.githubusercontent.com/18059713/87477505-13de4700-c5dd-11ea-8c51-9a8323f1a92f.png)

When clicking Preview on Chrome 83/MacOS Catalina it shows:

![image](https://user-images.githubusercontent.com/18059713/87477631-47b96c80-c5dd-11ea-8381-210252ca0470.png)

What it shows on MacOS/FireFox & Chrome 83/Windows 10 - the correct display:

![image](https://user-images.githubusercontent.com/18059713/87477806-9830ca00-c5dd-11ea-90a8-d0c76ad55d97.png)

**Expected behavior**
A clear and concise description of what you expected to happen. - See above

**Screenshots**
Hopefully attached.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website have Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] - Plugin was deactivated with no change to the behavior.
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] - Installed, but not activated - 8.5.1

**Comment by annezazu** [comment] 2020-07-14 22:47
@BajaBarry Thanks for reporting this. Can you share the exact HTML you are trying to add so others can more readily try to replicate this? Thank you!

**Comment by BajaBarry** [comment] 2020-07-15 23:24
<script type="text/javascript">
amzn_assoc_tracking_id = "mytrackingid-99";
amzn_assoc_ad_mode = "manual";
amzn_assoc_ad_type = "smart";
amzn_assoc_marketplace = "amazon";
amzn_assoc_region = "US";
amzn_assoc_design = "enhanced_links";
amzn_assoc_asins = "B085VPPGZG";
amzn_assoc_placement = "adunit";
amzn_assoc_linkid = "b4c5f2b43b124d2fb48f734c96591118";
</script>
<script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US"></script>

**Comment by lukecarbis** [comment] 2020-12-08 05:26
Tested in both Chrome 87/MacOS Catalina and Chrome 83/MacOS Catalina. I can't reproduce in either version of Chrome with the code provided.

**Comment by talldan** [comment] 2020-12-08 05:33
Same here in Chrome 87. Lets close this.

**Closed by talldan** 2020-12-08 05:33 UTC
Labels: Needs Testing, [Block] HTML, [Feature] Raw Handling
