### ISSUE TITLE
Adding link to existing page does not insert page name

### ISSUE THREAD

**Issue by pawel-tomkiel** [WordPress/gutenberg#13290] opened 2019-01-11 12:16 UTC
In classic editor adding link to existing content would insert the name of such page linked to it. In Gutenberg I get only URL inserted.

1. Open Gutenberg
2. Create new paragraph
3. Click insert link button and choose some existing post or page
4. Only URL will be inserted into paragraph

I would expect a similar behaviour to classic editor - that I will get something like: `<a href="/post-url">Post Name</a>`

 - OSX
 - Chrome

**Comment by designsimply** [comment] 2019-01-11 20:56
Closing as a duplicate of #11930. Thank you for the report @pawel-tomkiel!

**Closed by designsimply** 2019-01-11 20:56 UTC
Labels: [Block] Paragraph
