### ISSUE TITLE
Gutenberg Editor flickers while going from bottom to top

### ISSUE THREAD

**Issue by kamlesh08** [WordPress/gutenberg#22026] opened 2020-05-01 11:58 UTC
**Describe the bug**
When we write 3-4 paragraphs on Gutenberg Editor and then scroll to the top, the size of right sidebar changes thus causing a noticeable flicker in the editor which distracts the user.

**To reproduce**
1. Go to any 'Page'.
2. Start writing 3-4 paragraphs in 'Gutenberg Editor'. 
3. Scroll to the top.
4. See error.

**Expected behavior**
There should be no change in size of the right sidebar and the user should have distraction-free writing experience.

**Editor version**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?: Default Block Editor

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Google Chrome
 - Version: Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by youknowriad** [comment] 2020-05-01 12:25
Can you provide a screenshot or gif so we can understand better what you're experiencing as this is not something that happens by default. Thanks.

**Comment by karmatosed** [comment] 2020-05-01 18:18
For now, I am closing this as it's waiting for more details. It can always be reopened once those happen though.

**Comment by kamlesh08** [comment] 2020-05-03 17:52
Hello, 

Please have a look at this link for the details - https://www.loom.com/share/d9022adf8678432e934c6f4b8942da8e

What happens is vertical scrollbar pops out when we scroll from bottom to top, however, it is hidden when we scroll from top to bottom!
Both behaviors are different and cause a distraction from the user's point of view.

Thanks!

**Comment by karmatosed** [comment] 2020-05-04 15:43
Ah, thanks for more details @kamlesh08 - the missing piece might be the screen size potentially, what is that set to?

**Comment by kamlesh08** [comment] 2020-05-04 16:48
Hello,
My current screen size is 1920 x 1080, however, I face this issue on almost all screen sizes.
Thanks!

**Comment by noisysocks** [comment] 2020-10-27 05:18
[This came up in #core-editor triage.](https://wordpress.slack.com/archives/C02QB2JS7/p1603775202026800) The group wasn't able to reproduce the issue.

Is anyone with an Ubuntu machine able to reproduce this?

@kamlesh08: Do you still see this buggy behaviour? What about if you disable all plugins?

**Comment by kamlesh08** [comment] 2020-10-27 12:01
@noisysocks I still see this behavior even after disabling all the plugins.

**Comment by talldan** [comment] 2020-12-16 03:44
@stokesman mentioned this might be caused by Grammarly in #26936:
https://github.com/WordPress/gutenberg/issues/26936#issuecomment-732450722

@kamlesh08 Does the issue go away if you disable Grammarly?

**Comment by annezazu** [comment] 2021-02-26 19:44
@kamlesh08 I'm going to close this issue out for now since it's been a while since we heard from you. Feel free to re-open it but please check to see if the issue goes away upon disabling Grammarly first :)

**Closed by annezazu** 2021-02-26 19:44 UTC
Labels: General Interface, Needs Testing
