### ISSUE TITLE
Any update/edit action with Gutenberg results in 500 internal server error.

### ISSUE THREAD

**Issue by leninnair** [WordPress/gutenberg#9983] opened 2018-09-18 04:32 UTC
**Describe the bug**
Hi, when I try to update an existing post or edit or publish anything, it results in internal server error 500. When I disable Gutenberg, the error disappears.

**To Reproduce**
1. Try clicking the edit link on any post
2. It shows the 500 internal server error.

**Expected behavior**
It should have opened the editor with the text on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38178422/45664481-9e60d700-bb29-11e8-8143-4f4302414c93.png)
![image](https://user-images.githubusercontent.com/38178422/45664490-a6207b80-bb29-11e8-88b3-210a762fa549.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version 68

**Additional context**
- Gutenberg v 3.8.0
- WordPress 4.9.8
- Hestia theme
- Yoast SEO 8.2
- WP Fastest Cache 0.8.8.4

**Comment by designsimply** [comment] 2018-09-18 17:14
Thank you for reporting this! 

Are you able to check the browser console to see if you can find a more detailed error message?

Do you have access to your server's error logs, and can you see if there's any more information showing in them?

Do you have any security plugins installed?

If you have a firewall setup on your server, can you check your firewall logs to see if there is a log for a related rule being triggered?

**Comment by designsimply** [comment] 2018-09-28 18:27
It's hard to say what might be going wrong in your case without more information. May I ask if you have the Advanced Custom Fields Pro plugin installed? #9699 might not be related (there's not enough information provided yet to tell) but it does mention 500 server errors and considers the possibility that it's because of a conflict between the two plugins.

**Comment by designsimply** [comment] 2018-11-26 23:34
I'm closing this issue for lack of reply and because I have been unable to see this problem in testing. 500 errors like this are most often caused by an incompatible configuration on your web server, such as turning off access to the API. See https://core.trac.wordpress.org/ticket/44711#comment:2 for an example. 

Please check to make sure your site's API is working properly and if it isn't please either re-open this issue with the answers to the questions asked above or create a new issue which includes those answers.

**Closed by designsimply** 2018-11-26 23:34 UTC
Labels: [Status] Needs More Info, [Type] Help Request

**Comment by gotron** [comment] 2018-12-12 15:50
I had the same error. This was in my logs. 
`WARNING: [pool www] child 484 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/site-nursing/wp-includes/load.php:978"`

The problem resolved after updating the plugin "JWT Authentication for WP-API".
