### ISSUE TITLE
Bug: Image block selecting medium or thumbnail does not relocate caption - caption centered in relation to boundry box.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17162] opened 2019-08-23 10:25 UTC
**Describe the bug**
Resizing image by selecting image size drop down does not relocate caption when selecting thumbnail or medium.

![Screen Shot 2019-08-23 at 12 19 31](https://user-images.githubusercontent.com/5323259/63585816-497ed980-c5a0-11e9-98bd-303eb6fb3325.png)

Btw I also tested the 25%, 50% etc and these worked nicely. Except when it resets back to medium or thumbnail default image size.

**To reproduce**
1. Select an image block.
2. Add image. 
3. Select thumbnail or medium image size in the drop down.
4. Notice that the caption does not show directly under the image.

**Expected behavior**
That the caption would show directly under the image also on thumbnail and medium size image.

Chrome.
Using Desktop Server.
Mac OS 10.13.6

**Comment by phpbits** [comment] 2019-09-25 09:25
@paaljoachim Just checked and it seems to be theme-specific. For instance, if you are using TwentyTwenty theme with the default caption aligned to the left, you won't have this issue. Perhaps the solution is to define caption alignment on `theme_support`?

I'm not really sure what's the best solution but I'm working on Caption Alignment for EditorsKit - https://wordpress.org/plugins/block-options/ and I'm sure it'll help for user-specific solution. Here's what I have for alignment toolbar so far :


![Screen Capture on 2019-09-25 at 17-24-07](https://user-images.githubusercontent.com/3365507/65588008-5fc1f000-dfb9-11e9-956d-acb12eed8e3d.gif)

**Comment by paaljoachim** [comment] 2019-09-26 05:43
That is good to hear Jeffrey! That means we can close this issue. Do you agree?

I tested using Twenty Nineteen and that has the error still there. I believe this is something @kjellr will need to adjust later on.

**Comment by tellthemachines** [comment] 2020-11-27 03:14
I can reproduce this issue on any small image, without resizing. It would be good to fix this issue in the editor rather than forcing themes to adopt specific styling as a workaround. [Some context here](https://github.com/WordPress/gutenberg/issues/13684#issuecomment-465473023) which should be taken into account.

**Comment by paaljoachim** [comment] 2020-11-27 08:14
@tellthemachines As this is also affecting the new default theme Twenty Twenty One. A fix should be backported to WP 5.6.

**Comment by tellthemachines** [comment] 2020-11-29 23:56
@paaljoachim unfortunately this is not a 5.6 regression, so it doesn't qualify for inclusion during RC stage. Agree we should fix it soon and make sure it's ready for 5.7.

**Comment by paaljoachim** [comment] 2020-12-01 16:34
Hi Isabel @tellthemachines 
What can perhaps be done it getting a fix for this into a 5.6.1 release.

**Comment by paaljoachim** [comment] 2021-01-11 11:49
@noisysocks Robert.
This is an important user interface adjustment that we should get either into 5.6.1 or 5.7 "Must haves".
Thanks.

I look forward to being able to center captions below the image. Today too many captions are off centered.

**Comment by noisysocks** [comment] 2021-01-11 23:34
Thanks for flagging.

**Comment by paaljoachim** [comment] 2021-01-28 15:11
Related issues:
**Missing text-align for image caption**
https://github.com/WordPress/gutenberg/issues/19975

**Introduce explicit caption positioning**
https://github.com/WordPress/gutenberg/issues/12997
Inline alignment caption toolbar. Which would give the user the option into where the caption should be placed.

**Image caption styles global styles support**
https://github.com/WordPress/gutenberg/issues/27480

**Comment by talldan** [comment] 2021-01-29 04:53
This issue seems like a duplicate of https://github.com/WordPress/gutenberg/issues/11719

**Comment by paaljoachim** [comment] 2021-01-29 08:51
Hey Dan @talldan 
This issue is a duplicate of https://github.com/WordPress/gutenberg/issues/11719 . I closed the other issue so that we can focus on this issue which has been added the 5.7 project board.

Bottom line is that is looks like we need to rework the Image block, as multiple issues needs to be addressed.
Here is another issue: https://github.com/WordPress/gutenberg/issues/21836

**Comment by mtias** [comment] 2021-02-09 17:14
@paaljoachim these issues don't require reworking the image block!

**Comment by paaljoachim** [comment] 2021-02-16 16:42
Could we keep the image centered within the boundary box, so that the caption is always centered below the image?

**Comment by paaljoachim** [comment] 2021-10-08 07:42
It would be nice to get this fix into WP 5.9.
I am hoping someone is able to take a closer look.
Thanks!

We are getting additional reports on this.

Additional associated/duplicate issues:
**Image alignment is left by default but it displays center as default**
https://github.com/WordPress/gutenberg/issues/33349

**Images are centered in editor and aligned left in preview**
https://github.com/WordPress/gutenberg/issues/31011


I made a quick fix through the CSS to one of my customer sites. Which shows the caption centered below the image independent of the size on the frontend. Backend still shows the caption centered to the boundry box.

wp-block-image {
    margin-bottom: 1.2em;
    display: inline-block;
    justify-content: center;
}

![Screenshot 2021-10-08 at 09 41 29](https://user-images.githubusercontent.com/5323259/136517599-baf14355-c571-4a03-a762-ecb9e1edbb04.jpg)


@Mamaduka

This seems like one solution. (PR has stalled)
Image block: try caption as inner block
https://github.com/WordPress/gutenberg/pull/31823

**Comment by paaljoachim** [comment] 2021-10-08 08:35
There seems bigger fixes needed related to the PR which was suggested by @jasmussen 
https://github.com/WordPress/gutenberg/pull/31823#issuecomment-842082668

Can we create a step between? With focus on improving the current caption alignment problem. A fix that can also later be incorporated into the PR by @ellatrix

**Comment by antpb** [comment] 2021-10-14 14:34
Is it possible the solution for this could be making the caption respect the alignment of the image? For instance, the image currently initializes left aligned. The caption initializes centered. Is there a reason they aren't the same alignment? It would greatly improve the experience if I added an image block with everything matching the default alignment.

More often than not when I add an image block, the first thing I do is click center so it matches the alignment of the caption. That seems to be the core problem. Folks want to unify that button with the content of the image block which currently has alignment settings.

**Comment by glendaviesnz** [comment] 2021-10-20 00:37
Potential fix for this at https://github.com/WordPress/gutenberg/pull/35787

**Closed** 2021-12-09 19:55 UTC
Labels: [Type] Bug, [Block] Image

**Comment by paaljoachim** [comment] 2021-12-09 20:47
A big thank you to @glendaviesnz and @andrewserong !
