### ISSUE TITLE
No option to update after a change to an image made

### ISSUE THREAD

**Issue by rossahall** [WordPress/gutenberg#9459] opened 2018-08-30 09:43 UTC
Edited an existing page. Page has image block in it.
Changed image block "Link Settings" to link to attachment page.

No option presented to update the published page after the change has been made.

Had to edit another block to force it to give me the option.

Tested on multiple pages with same results.

**Comment by designsimply** [comment] 2018-08-31 20:28
Thank you for reporting!

I was unable to reproduce the problem described using the following testing steps while running WordPress 4.9.8 and Gutenberg 3.7 using Firefox 61.0.2 on macOS 10.13.6:

1. Go to Pages > Add New.
1. Insert an image from the media library.
1. Save and publish the page.
1. Go to Pages.
1. Open the page that was just published.
1. Note that there is an "Update" button at top right but it is greyed out.
1. Click on the image.
1. Go to Settings > Block > Link Settings and change "Link To" to "Attachment Page".

<strong>Result:</strong> the "Update" button at top right changes from greyed out to active. ([1m12s](https://cloudup.com/cXDDvMLuZaE))

Have I missed anything or gotten something wrong in the testing steps? For example, in the video ([1m12s](https://cloudup.com/cXDDvMLuZaE)) can you spot anything different in the content that's different such as you are using the classic block and not an image block (or anything like that)?

Can you confirm the version of the plugin you are using and also note your OS and browser versions?

Do you see any errors in the browser console at the time you make the "Link Settings" option change? If you do, that could help provide a clue for narrowing down the cause of the problem.

**Comment by designsimply** [comment] 2018-10-01 11:54
Closing because we were unable to reproduce the issue in a test and no information has been added since then. One thing that might help in this case would be to try the testing steps again and watch the Network panel in your browser developer tools while you do the testing steps and note whether you see any errors show up as you go (such as a problem with autosaves which could be specific to your setup and would help provide context needed to move forward). 

Please re-open if you find this is still an issue and please mention whether the steps noted for testing are different at all from what you are doing. Also, if someone else finds the same problem, please post details and we can re-visit.

**Closed by designsimply** 2018-10-01 11:54 UTC
Labels: [Status] Needs More Info
