### ISSUE TITLE
Error: Failed to load plugin: [object from url https://www.domainname.com/wp-includes/js/tinymce/plugins/[object/plugin.min.js

### ISSUE THREAD

**Issue by boemedia** [WordPress/gutenberg#3469] opened 2017-11-14 09:41 UTC
When I re-open a Gutenberg post to edit, I get a TinyMCE error.

See this screenshot: 
![image](https://user-images.githubusercontent.com/29769622/32773022-18f9b2d8-c928-11e7-8660-ddab0bada24a.png)

This site runs on a Multisite installation
WordPress version 4.8.3
Beaver Builder Pagebuilder 2.0.1.1.
Gutenberg version 1.6.1
Chrome version 62.0.3202.94
Working on a MacBook Pro

**Comment by ephox-mogran** [comment] 2017-11-16 18:30
What is likely happening here is that you are appending a JavaScript object to a string when creating your plugin list for tinymce. Therefore, it would be ending up with something like:

`plugins: '[object Object] lists table'` etc.

To check if this is the case, in your Chrome developer tools (https://developer.chrome.com/devtools), goto the Console tab, and see if you are getting an error for an `Object]` plugin as well. 

I have created a replication case of what I think is the same issue here: http://fiddle.tinymce.com/Pegaab

Is this consistent with what you are seeing?

If so, we're probably going to need more information. One of your plugin names might be incorrectly configured.

**Comment by mtias** [comment] 2017-11-29 15:30
Closing this, but feel free to re-open if there's additional information. Thanks.

**Closed by mtias** 2017-11-29 15:30 UTC
Labels: [Component] TinyMCE, [Status] Needs More Info

**Comment by thesm2** [comment] 2018-03-11 02:53
Hi, was this ever resolved? I'm running PHP 7.2 with NGINX alongside my Wordpress installation. I get the following error:
`Failed to load plugin url: https://xxxx.com/blog/wp-content/plugins/wp-shortcode/tinymce/langs/en.js`
when opening Gutenberg editor
In my chrome dev console it says: 
`Deprecated TinyMCE API call: <target>.onNodeChange.add(..)`

**Comment by boemedia** [comment] 2018-03-13 14:45
Sorry, didn't have the chance to test this again, but haven't come across it again either.

**Comment by djordje47** [comment] 2018-09-24 18:11
Hey guys,
I have the exact same error I just installed wordpress, so it is clean instalation. Error is appearing in the post page for example. 

`Failed to load plugin: wordpress from url http://wptest.development/wp-includes/js/tinymce/plugins/wordpress/plugin.min.js`

![image](https://user-images.githubusercontent.com/16069373/45970014-a8a53880-c035-11e8-8479-1bc65defbbfe.png)

It looks like it's a 404, but it's strange because it is fresh installation. I have tried to reinstall wordpress but it won't solve the problem for me. Any suggestions?

Has anyone solved it yet ? 

Thanks in advance ?

**Comment by jinalshah** [comment] 2018-10-04 05:05
Hello! 

I am facing the same issue too! However, it only appears to be on a Chrome on a Mac. Tried other browsers and OS's and it appears to be OK.

**Comment by jesska-f** [comment] 2018-10-21 07:43
I have the same issue with using a Mac with Chrome. Works fine in Safari. Brand new website, it's so frustrating. Reinstallation was a waste of time.

**Comment by djordje47** [comment] 2018-10-21 08:57
@jinalshah I have the problem on Linux.. I don't know why, I had no time to debug it.

**Comment by zethodderskov** [comment] 2019-01-01 11:42
I just had the same error, occurring all of a sudden on a site, that I had been working on for hours and hours (without the error). I have a bit of a special setup, since I'm working on it locally (using Flywheel - WP-version 5.0.2). 

The error disappeared when I updated my [WooCommerce Blocks-plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) . The plugin-version was 1.1.2, and I updated it to 1.2.0. And after I did that, then the error disappeared. 

And if that doesn't help, then it may be another plugin causing the error, so I guess that the good ol': 'Disable all of your plugins and see if the error goes away'.

**Comment by tonydjukic** [comment] 2020-05-05 02:40
I'm getting this error on a series of sites as well - I've been seeing persistent issues so when launching an entirely new WP install a couple of weeks ago I tried to 'stress test' it while it was entirely fresh and it was giving the same errors.  What I'm discovering is that I get random 'failed to load' errors for any number of WP core files.  Everything from admin-ajax.php to different tinymce scripts.

I noticed random errors around 5.3.x - 5.4.x (I didn't note it at the time) and assumed it was simply due to the fact that I was still mid-development.  But it's been increasing in frequency and severity (it was initially just failing to load the favicon.io) and it's now become a major development issue.  I haven't yet ruled out whether it's hosting related (FlyWheel's Cloud servers), but am wondering if there's been any further investigation into this?

**Comment by bongklim** [comment] 2021-03-06 05:43
I got a same problem when I edit something in the website "Failed to load plugin: charmap from url https://www.theprojectdefinition.com/wp-includes/js/tinymce/plugins/charmap/plugin.min.js" horizontally and vertically.

It can be disappeared if the "Advanced Editor Tools (previously TinyMCE Advanced)" plugin deactivated. But I need to use some functions of this plugin.

Could you please let me know how to solve this problem?

**Comment by orvn** [comment] 2021-03-19 20:40
> It can be disappeared if the "Advanced Editor Tools (previously TinyMCE Advanced)" plugin deactivated. But I need to use some functions of this plugin.

@bongklim, keep `Advanced Editor Tools (previously TinyMCE Advanced)` enabled, but try disabling script concatenation. This is typically a setting that's in `wp-config.php` (but it could be in other places).

If `CONCATENATE_SCRIPTS` doesn't exist anywhere in the non-core code (your themes/plugins/config), add
`define('CONCATENATE_SCRIPTS', false);` to the end of `wp-config.php`

If this works, you might find that scripts not being concatenated causes a lower site speed on the frontend (due to a ton of js files being served in separate http calls). You can solve this by wrapping your setting in a condition based on whether you're in the admin.

```php
if (is_admin() ) {
    define('CONCATENATE_SCRIPTS', false);
} else {
    define('CONCATENATE_SCRIPTS', true);
}
```

(Or you can use `http/2` which would parallelize the resource calls)

**Comment by madriverweb** [comment] 2022-02-10 08:56
I have this problem on two sites but can't locate the second one. The error message I'm seeing is: Failed to load plugin: wordpress from url .../wp-includes/js/tinymce/plugins/wordpress/plugin.min.js. The file is in the installation. The icons are being added to the content editor. This is happening in Classic posts, not in Block. I removed the suspect items from the functions file, no change.

The plugin notes "Warning: This plugin has not been tested with your current version of WordPress." It is tested up to 5.7.5 and I'm on 5.9. Hasn't been updated in 10 months. Come on, Automattic!!!

**Comment by wdburgdorf** [comment] 2023-05-05 14:01
Same problem here with /wp-includes/js/tinymce/plugins/wordpress/plugin.min.js
I played around a bit and found that in my case the issue is with the folder name "wordpress". For everything in any folder with that name, I get a 404. So also when I change the folder name in the tinymce path, the files are readable. But of course, then TinyMCE won't find them. Only one installation has this problem, none of the other WP-Sites on that hosting. 
I even tried putting the files into a differently named folder and rewriting the path in htaccess, didn't work. 
Still a mystery.
