### ISSUE TITLE
Uploading Featured Image inserts it into post content

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/gutenberg#3393] opened 2017-11-08 19:12 UTC
## Issue Overview

When you upload a featured image, it puts it into the post CONTENT if you happen to have your cursor in a text block.

## Steps to Reproduce (for bugs)
1. Write a post
2. While your cursor is in a text block, upload featured image
3. Congratulations, you now have a featured image in your post content

Note: This DOES NOT happen if you have your cursor in the title block or (magically) in no block at all. 

This MAY be related to why #3392 happens

## Expected Behavior
The featured image uploader should not insert the image into post content.

## Current Behavior
The featured image gets inserted and ends up in the content

**Comment by youknowriad** [comment] 2017-12-28 12:29
I can't reproduce this, can you confirm?

**Comment by Ipstenu** [comment] 2017-12-29 19:14
Nope, not fixed.

I just reproduced it on my site.

**Comment by youknowriad** [comment] 2017-12-29 22:25
It's probably related to your setup, plugins, theme etc... I can't reproduce on a fresh install. Anything particular we should test with?

**Comment by Ipstenu** [comment] 2017-12-30 00:39
I've opened a support ticket with StudioPress to ask them about that (and linked here)

**Comment by Ipstenu** [comment] 2018-01-03 21:54
@youknowriad Can I DM you or otherwise send you a link to the themes? (you can email me `ipstenu AT halfelf.org` if needed :) ) - Due to the theme being premium, I don't want to post it up for free :)

**Comment by danielbachhuber** [comment] 2018-01-23 14:39
@Ipstenu Were you able to track down any additional details? If so, can you share them on this ticket?

**Comment by Ipstenu** [comment] 2018-01-24 16:08
No, but it’s still happening as of last week. This week I was writing a lot of posts with code, and since #4456 is an issue, I have to go back to the old editor for that.

**Comment by JeroenSormani** [comment] 2018-03-03 08:31
I can confirm this is still happening for me in version 2.3.0.

**Comment by JeroenSormani** [comment] 2018-03-03 09:08
So I'm really hard trying to find a consistency of when this happens. Done probably over 300+ uploads of images to try and find when this is happening exactly. Every time I think I've found a consistency it stops there and its no longer happening.

Here's what I know so far:
- It happens sometimes
- Doesn't happen with all images (Stripe logo won't)
- When it happens, the image is also double uploaded to the media library
- It is not required to have the pointer on the content, I've done many tests with specifically clicking outside the containers and even in the menu / address bar before clicking 'Set featured image'.
- The location where the image appears in the post **is not** consistent with where the cursor is/was before.
    - It does appear that the image gets uploaded **UP TO** being the 5th block, never below there, even if there's plenty more below. 
- In relation to the above, when testing with only a few block (less then 5) is appears less frequently, which could mean it may still try, but can't inset it in the, say 4th block as they don't exist..?


Here's a GIF, you can see the first time it doesn't happen, the second it does.
![screen recording 2018-03-03 at 10 05 am](https://user-images.githubusercontent.com/5774447/36932544-a2310afe-1eca-11e8-8524-267bf9ce13a1.gif)

Image I get good consistency with:

Stripe logo that doesn't get this behaviour:

**Comment by JeroenSormani** [comment] 2018-03-03 09:18
Sorry, after I just posted that I did a couple more tests with the stripe logo as I don't think I've tried that in a post where I had many blocks before, it does have the same consistency as the other image when testing it in post with the many blocks as per the GIF. 

Weirdly enough this one seems to only insert at the 5th+ block (up to the 7th). Which is very weird as the other one **definitely** doesn't go beyond the 5th for me.
It only inserting in the 5~7th block could explain why I initially thought it didn't get the behaviour earlier..

Hope I'm being helpful in a way, there seems to be some consistency, just a really weird one.
I'm on the WP slack if anyone needs additional info or maybe a screenshare?

**Comment by youknowriad** [comment] 2018-03-03 14:55
You are definitely being helpful and I think I know the real issue thanks to you. 

I believe from the gif that you're dragging the image to the modal to upload it right? I never tried that before instead I was using buttons. I think what happens is that the "drop" behavior of the modal is triggered but also the "drop" behavior of the editor behind the modal. 

Thanks for the help.

**Comment by JeroenSormani** [comment] 2018-03-03 17:34
Makes perfect sense.., I must've been very consistent in dragging those two different images to different heights then! _(which also kinda makes sense as they were at entirely different locations in my finder) 🙄_

**Comment by gziolo** [comment] 2018-03-09 10:08
It should be fixed with #5432. Can you confirm?

**Closed** 2018-03-09 10:07 UTC
Labels: Blocks, Media, [Status] Needs More Info

**Comment by JeroenSormani** [comment] 2018-03-09 19:41
Didn't seem to work initially, but after running `npm run build` it no longer double adds the image. 
Can confirm it works for me :+1:

**Comment by Ipstenu** [comment] 2018-05-01 15:55
Just to confirm, it's working for me too :)
