### ISSUE TITLE
With new WP 5.02 i get recurring error message for page "Updating failed"

### ISSUE THREAD

**Issue by trade-commander1** [WordPress/gutenberg#13072] opened 2018-12-22 00:39 UTC
**Describe the bug**
With new WP 5.02 i get recurring error message for page "Updating failed"

(Have you tested new version of WP...?)

**Comment by swissspidy** [comment] 2018-12-22 10:06
WordPress 5.0 runs on millions of websites and it works pretty smoothly for them, so yeah it has been tested :-)

The issue you're getting could be caused by some conflict in the REST API response.

Before you try to update the page, open your browser's developers tools by pressing F12. Then, click on "Network" to monitor any HTTP requests made and try to update your page. You should see some requests to `/wp-json/…` or similar, or requests where the "Status" is "4xx" or "5xx". Check out the "Response" tab of these entries and see if there's any error message or similar. Post the error messages here or take screenshots.

If you're using Chrome, the developer tools should look like this:

<img width="504" alt="screenshot 2018-12-22 at 11 04 39" src="https://user-images.githubusercontent.com/841956/50373067-85107080-05d9-11e9-8fc1-4ed3ce4f47f4.png">

Also, try to disable all plugins and switch to a default theme like Twenty Nineteen to see if the issue still persists.

**Comment by atcytech** [comment] 2018-12-25 19:14
I was able to recreate this problem using Apache 2.4.34, php7.2.13 (or php7.3.0). The fix to this problem is to use the _plain_ permalink setting. Using any other permalink setting results in the failed update.

**Comment by atcytech** [comment] 2018-12-25 20:57
I am a user like you. I am experiencing the same issue and my experimentation discovered the less than ideal fix. I shared to provide the developers some details they might be looking for in order to fix the issue.

**Comment by trade-commander1** [comment] 2018-12-25 21:00
Ok, sorry.

But for me it makes no sense to change permalink settings.

 

Von: atcytech [mailto:notifications@github.com] 
Gesendet: Dienstag, 25. Dezember 2018 21:58
An: WordPress/gutenberg
Cc: trade-commander1; Author
Betreff: Re: [WordPress/gutenberg] With new WP 5.02 i get recurring error message for page "Updating failed" (#13072)

 

I am a user like you. I am experiencing the same issue and my experimentation discovered the less than ideal fix. I shared to provide the developers some details they might be looking for in order to fix the issue.

**Comment by swissspidy** [comment] 2018-12-26 16:42
@trade-commander1 Have you seen my previous comment with some debugging steps at https://github.com/WordPress/gutenberg/issues/13072#issuecomment-449559654? Please follow these so we can narrow down the issue.

**Comment by trade-commander1** [comment] 2018-12-26 16:48
Hello,

i switched back to classic editor and preview works

again.

This is ok for me.

Thank you

Von: Pascal Birchler [mailto:notifications@github.com] 
Gesendet: Mittwoch, 26. Dezember 2018 17:43
An: WordPress/gutenberg
Cc: trade-commander1; Mention
Betreff: Re: [WordPress/gutenberg] With new WP 5.02 i get recurring error message for page "Updating failed" (#13072)

 

@trade-commander1 <https://github.com/trade-commander1>  Have you seen my previous comment with some debugging steps at #13072 (comment) <https://github.com/WordPress/gutenberg/issues/13072#issuecomment-449559654> ? Please follow these so we can narrow down the issue.

**Comment by designsimply** [comment] 2019-01-08 20:13
I see that you have switched to the Classic Editor as a workaround. I will close this issue for now since there are other similar issues and because more detail would be needed in order to proceed with this specific case. 

If you find that you would like to try Gutenberg again in the future and that you are still experiencing problems with "Updating failed" messages, please post to https://wordpress.org/support/forum/how-to-and-troubleshooting/ with details such as any errors you see in your browser tools network or console panels or ask for help learning how to do that. Thank you!

**Closed by designsimply** 2019-01-08 20:13 UTC
Labels: [Status] Needs More Info, [Type] Help Request
