### ISSUE TITLE
I use but the "patterns" subfolder is not recognized.

### ISSUE THREAD

**Issue by spstrap** [WordPress/gutenberg#57621] opened 2024-01-06 13:08 UTC
### Description

I use [!-- wp:pattern {"slug":"header"} /--] but the "patterns" subfolder is not recognized.
If this feature was not supported I would have hundreds of files listed in the "patterns" folder which would make management very difficult.

Could you please help?

### Step-by-step reproduction instructions

1. /patterns/header.php : [!-- wp:pattern {"slug":"header"} /--]  O it's work
2. /patterns/header/type-1.php -> [!-- wp:pattern {"slug":"header-type-1"} /--]   X not work

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment] 2024-01-07 01:42
I don’t think this is a bug, because it’s working as designed. The pattern sub-folder would be a feature request.

More on this: https://github.com/WordPress/gutenberg/issues/50144

**Comment by talldan** [comment] 2024-01-08 02:24
I'll close this as a duplicate given there's already a feature request

**Closed as not planned by talldan** 2024-01-08 02:24 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Patterns, [Block] Pattern
