### ISSUE TITLE
Some font names don't work in theme.json fontFamilies/fontFace 

### ISSUE THREAD

**Issue by lunule** [WordPress/gutenberg#49021] opened 2023-03-13 09:52 UTC
### Description

Some font names can't be used in the theme.json fontFace declaration, for some reason.

One of these names that don't work is `Guillon` - if this name is used in the fontFamilies then the fontFace declaration, e.g.:

``` json

(...)
"fontFamilies": [
	{
		"fontFamily": "Guillon, Helvetica, Arial, sans-serif",
		"slug": "guillon",
		"name": "Guillon",
	  	"fontFace": [
		  	{
			  	"fontFamily": "Guillon",
			  	"fontWeight": "300",
			  	"fontStyle": "normal",
			  	"fontStretch": "normal",
			  	"src": [ 
				  	"file:./assets/fonts/Guillon-Light.eot",
				  	"file:./assets/fonts/Guillon-Light.svg",
				  	"file:./assets/fonts/Guillon-Light.ttf",
			  		"file:./assets/fonts/Guillon-Light.woff2" 
			  	]
		  	},
		  	(...)

```

... font weights stop working.

But, if "Guillon" is replaced with practically **_anything else than "Guillon"_**, font weights work again.

So, for instance, the following version works as expected, with the same font files, and with the only difference of the aforementioned renaming:

``` json

(...)
"fontFamilies": [
	{
		"fontFamily": "Guillon, Helvetica, Arial, sans-serif",
		"slug": "guillon",
		"name": "AnythingElseThanGuillon",
	  	"fontFace": [
		  	{
			  	"fontFamily": "AnythingElseThanGuillon",
			  	"fontWeight": "300",
			  	"fontStyle": "normal",
			  	"fontStretch": "normal",
			  	"src": [ 
				  	"file:./assets/fonts/Guillon-Light.eot",
				  	"file:./assets/fonts/Guillon-Light.svg",
				  	"file:./assets/fonts/Guillon-Light.ttf",
			  		"file:./assets/fonts/Guillon-Light.woff2" 
			  	]
		  	},
		  	(...)

```

### Step-by-step reproduction instructions

Just use the above-mentioned font name in a fontFamily/fontFace declaration - it won't work.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment] 2023-03-14 17:41
From my experience it's happening on macOS when the font is locally installed — the browser tries to load the system version but fails to load the correct variations in the form of italics and weights.

Renaming it forces the browser to download the font from the server instead.

**Comment by lunule** [comment] 2023-03-14 17:59
@devon-waterwerks-agency - 👍 thanks for the info.

I'm with Windows :) - and there's a very strong chance the issue is related, simarly, to local system font availability.

But even if that's the case, this still seems to be a bug to me.

I mean, the font file paths should be specified for a reason. 
The availability of fonts as _installed system fonts_ is totally irrelevant regarding the way font declarations in the theme.json file should work/be parsed and interpreted.

**Comment by lunule** [comment] 2023-04-15 17:10
I tested the issue today with 
- WP 6.2,
- no Gutenberg plugin,
- local instance running with Laragon,  

and couldn't reproduce the issue.

I'm closing this one as completed - whoever worked on solving it, huge thanks. 🙏

**Comment by lunule** [comment] 2023-04-16 01:09
After some testing, it turned out that the issue still persists.
Interestingly enough, now it's happening in reverse direction: when I change back the font name to the original string (Guillon), it works locally, but as soon as I upload the site to the server, fonts are broken again.

The font-family itself is recognized, but all content types set up with Guillon are displayed with the same one Guillon font weight (Regular, 400). Font-weight values specified in theme.json or in the stylesheets don't work anymore.

**Comment by hellofromtonya** [comment] 2023-04-25 18:26
@lunule What version of Gutenberg are you using? Does the problem persist with the newest version of the plugin?

**Comment by lunule** [comment] 2023-04-25 20:52
@hellofromtonya No separate Gutenberg plugin install, I'm using only the core FSE features (notably font-facing in the theme.json file).

**Comment by anton-vlasenko** [comment] 2023-05-29 22:44
I'm assigning this issue to myself for investigation.

**Comment by lunule** [comment] 2023-05-30 19:38
👍 Thanks, @anton-vlasenko - I'm totally stuck with this, and unfortunately, I won't even have time to (re-)test it in the following two months...

**Comment by anton-vlasenko** [comment] 2023-05-30 23:40
## Reproduction Report

### Environment
- WordPress: 6.3-alpha-55505-src
- PHP: 8.0.27
- Server: Apache/2.4.55 (Unix) PHP/8.0.27
- Database: mysqli (Server: 5.7.38 / Client: mysqlnd 8.0.27)
- Browser: Safari 16.5 (macOS)
- Theme: Twenty Twenty-Two 1.4
- MU-Plugins: None activated
- Plugins: 
  None activated

### Steps to Reproduce
1. **Prerequisites:
Add the following text to the `fontFamilies` section of the `theme.json` file of the `Twenty Twenty-Two` theme:
```json
				{
					"fontFamily": "Guillon, Helvetica, Arial, sans-serif",
					"slug": "guillon",
					"name": "Guillon",
					"fontFace": [
						{
							"fontFamily": "Guillon",
							"fontWeight": "300",
							"fontStyle": "normal",
							"fontStretch": "normal",
							"src": [
								"file:./assets/fonts/Guillon-Light.eot",
								"file:./assets/fonts/Guillon-Light.svg",
								"file:./assets/fonts/Guillon-Light.ttf",
								"file:./assets/fonts/Guillon-Light.woff2"
							]
						},
						{
							"fontFamily": "Guillon",
							"fontWeight": "400",
							"fontStyle": "normal",
							"fontStretch": "normal",
							"src": [
								"file:./assets/fonts/Guillon-Regular.eot",
								"file:./assets/fonts/Guillon-Regular.svg",
								"file:./assets/fonts/Guillon-Regular.ttf",
								"file:./assets/fonts/Guillon-Regular.woff2"
							]
						},
						{
							"fontFamily": "Guillon",
							"fontWeight": "700",
							"fontStyle": "normal",
							"fontStretch": "normal",
							"src": [
								"file:./assets/fonts/Guillon-Bold.eot",
								"file:./assets/fonts/Guillon-Bold.svg",
								"file:./assets/fonts/Guillon-Bold.ttf",
								"file:./assets/fonts/Guillon-Bold.woff2"
							]
						}
					]
				}
```


2. Unzip 
[Guillon Fonts.zip](https://github.com/WordPress/gutenberg/files/11606756/Guillon.Fonts.zip)
 to `src/wp-content/themes/twentytwentytwo/assets/fonts` (no sub-folders).
3. Activate the `Twenty Twenty-Two` theme.
4. Edit any post.
5. Select a paragraph block in the List View, and change the font's appearance as shown in the screenshot below:
![Screenshot 2023-05-31 at 01 20 16](https://github.com/WordPress/gutenberg/assets/43744263/4cbc4c29-9d2e-4790-8ca9-adfc219dd524)
6. Select the `Guillon` font in the `Font` dropdown. Change the font appearance as shown in the screenshot below. Select `Regular`, `Light`, and `Bold` weights.
![Screenshot 2023-05-31 at 01 27 27](https://github.com/WordPress/gutenberg/assets/43744263/cfa274a5-e755-41c2-b519-6b11425127a3)
7. Observe that the font's weight changes.
8. Go to the `theme.json` file and change
```json
"name": "Guillon",
```
to
```json
"name": "Acme Font",
```
9. Repeat steps 4 through 7, but select the `Acme Font` in the `Font` dropdown.

### Reproduction Results
- ❌ [Reported issue](#issue-49021) was not reproducible.

**Comment by anton-vlasenko** [comment] 2023-05-30 23:46
> 👍 Thanks, @anton-vlasenko - I'm totally stuck with this, and unfortunately, I won't even have time to (re-)test it in the following two months...


You are welcome, @lunule. I would be happy to debug this issue. However, I'm unable to reproduce it (please refer to [my test report](https://github.com/WordPress/gutenberg/issues/49021#issuecomment-1569279937) above for more information).
If you could provide any additional details that might assist in reproducing the issue, I would appreciate it. Thanks!

**Comment by lunule** [comment] 2023-06-01 12:31
Thanks for the thorough testing, @anton-vlasenko .

My only idea is that the issue is indeed related to the availability of these fonts as a locally installed font - just as @devon-waterwerks-agency mentioned earlier.

As a last test, can you please check if things work fine on your end also when the fonts are locally installed on your desktop, not only available as font files in the theme subfolder?

**Comment by CookiesForDevo** [comment] 2023-06-04 22:17
Did some additional testing and I can no longer reproduce the issue in WP 6.2 as it no longer includes a `local()` in the `@font-face` declaration.

6.1:
```
@font-face{font-family:"Noto Sans";font-style:normal;font-weight:400;font-display:block;src:local("Noto Sans"), url('/wp-content/themes/twentytwentythree/assets/fonts/NotoSans/NotoSans-Regular.woff2') format('woff2');
```

6.2:
```
@font-face{font-family:"Noto Sans";font-style:normal;font-weight:400;font-display:block;src:url('/wp-content/themes/twentytwentythree/assets/fonts/NotoSans/NotoSans-Regular.woff2') format('woff2');
```

**Comment by lunule** [comment] 2023-06-04 22:46
@CookiesForDevo I'm not sure I follow - the issue discussed here is about the font-face setup in the theme.json file, something that doesn't use the local() function, this latter is purely optional btw even in the **CSS** font-face declaration.

Your examples are from CSS stylesheets. 
I didn't check where these examples are from, but the fact that they might have removed the `local()` from the default theme stylesheet is simply a theme author's decision. 

I don't think this has anyhting to do with what we're dealing with here.

**Comment by CookiesForDevo** [comment] 2023-06-04 22:58
@lunule The examples are from the default twentytwentythree theme with Noto Sans added as it was causing issues for me on another site with a custom theme.

With 6.1, the `@font-face` rules generated from the theme.json include the local() declaration but when WordPress is upgraded to 6.2, it's no longer included and the fonts work just fine. 

According to these, the local() rule being added to `@font-face` was causing issues and was patched in 6.2:
[https://core.trac.wordpress.org/ticket/57430](https://core.trac.wordpress.org/ticket/57430)
[https://github.com/WordPress/gutenberg/pull/47254](https://github.com/WordPress/gutenberg/pull/47254)

**Comment by lunule** [comment] 2023-06-04 23:47
@CookiesForDevo Thanks for the swift reply & explainer - 👍 all clear.
And, after reading through the referenced trac ticket, I agree, the issue seems to be solved.

Additionally, this whole topic might be marked as a duplicate of the bug reported here (and referenced in the trac ticket as well):
https://github.com/WordPress/gutenberg/issues/42190

Before marking this as closed and fixed, I'd like to retest it though - but I won't have time to do this before August, so, if someone's tracking these tickets and closing them if not commented for a while: I would appreciate it if this could be left open and active for the next two months. 🙏

**Comment by ironprogrammer** [comment] 2023-06-05 21:27
## Reproduction Report
I was also unable to reproduce this issue ([test steps above](https://github.com/WordPress/gutenberg/issues/49021#issuecomment-1569279937)), both with and without GB enabled.

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 13.4
- Browser: Safari 16.5
- Server: nginx/1.25.0
- PHP: 7.4.33
- WordPress: 6.3-alpha-55505-src
- Theme: twentytwentythree v1.1
- Active Plugins:
  - gutenberg v15.9.1 (tested both active and deactivated)

### Actual Results
- ❌ Unable to reproduce issue in post editor or global _Styles > Typography_.

### Additional Notes
While system fonts were not expected to interfere here (see @CookiesForDevo's [reference above](https://github.com/WordPress/gutenberg/issues/49021#issuecomment-1575763966)), I did sanity check this by also adding Guillon as a system-installed font with all three weights, some weights disabled, and some weights removed. In all cases, the theme-supplied fonts were used and included weights supported.

**Comment by ironprogrammer** [comment] 2023-06-05 21:46
Hi, @lunule, thank you for your willingness to continue testing to verify that the original issue has been resolved 🙌🏻.

I'm going to mark this closed for now, because multiple reports have reflected that it cannot be reproduced (as we currently understand it). However, if in August you're able to reproduce, then please do re-open with whatever additional context or steps you might have found.

**Closed as completed by ironprogrammer** 2023-06-05 21:46 UTC
