### ISSUE TITLE
Custom styles of core/group invisible in editor

### ISSUE THREAD

**Issue by aartjan** [WordPress/gutenberg#20140] opened 2020-02-10 14:20 UTC
**Describe the bug**
Before activating the Gutenberg plugin (working in WordPress 5.3.2) I could use JS or PHP to add a custom style to the core/group block and the backend would provide a "is-style-XXX" class to the group. This is still working in the website, but not in the editor when I activate the Gutenberg Plugin.
 
**To reproduce**
Add this JS:
`registerBlockStyle( 'core/group' , {
     name: 'golden-border',
     label: __( 'Golden Border' ),
   });`
or this PHP:
`register_block_style(
	'core/group',
	[
		'name'			=> 'golden-border',
		'label'			=> 'Golden Border',
		'style_handle'	=> 'block-styles-stylesheet',
	]
);`
to a theme, without installing Gutenberg Plugin.
Add this to the stylesheet of the theme
`.wp-block-group.is-style-golden-border {
  border: 2px solid #caa071;
  (...)
}`
Add this to the theme:
`add_theme_support( 'editor-styles' );`

**Expected behavior**
Both in the website and in the editor a 2px border should appear around the group if I select the style for a group. This happens if I disable the plugin, but with the plugin enabled, the is-style-golden-border class is gone.

**Screenshots**
Fragments of editor with Gutenberg plugin disabled
<img width="1354" alt="Schermafbeelding 2020-02-10 om 15 11 34" src="https://user-images.githubusercontent.com/19993252/74157011-ccabee80-4c17-11ea-83fc-44b68aaaaf2e.png">
<img width="501" alt="Schermafbeelding 2020-02-10 om 15 16 45" src="https://user-images.githubusercontent.com/19993252/74157367-755a4e00-4c18-11ea-926a-cfa065942f37.png">

Fragments of editor with Gutenberg plugin enabled
<img width="1203" alt="Schermafbeelding 2020-02-10 om 15 11 50" src="https://user-images.githubusercontent.com/19993252/74157064-eb11ea00-4c17-11ea-8b67-d5dcb2a472d1.png">
<img width="492" alt="Schermafbeelding 2020-02-10 om 15 17 12" src="https://user-images.githubusercontent.com/19993252/74157380-7ab79880-4c18-11ea-945e-5ede219a397f.png">

Fragment of the website (identical in both cases)
<img width="1203" alt="Schermafbeelding 2020-02-10 om 15 11 59" src="https://user-images.githubusercontent.com/19993252/74157094-fe24ba00-4c17-11ea-9466-ff9b169ba712.png">

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Browser Chrome
 - Version 79

**Additional context**
- Gutenberg plugin 7.4.0

**Comment by talldan** [comment] 2020-02-11 05:57
@aartjan Thanks for reporting the issue. I can confirm the bug. Looks like it's caused by this change:
https://github.com/WordPress/gutenberg/pull/19181/files#diff-d819635dc4c6f7b9326773f5726a37b7R36

I'll work on a fix for this.

**Closed** 2020-02-12 13:24 UTC
Labels: [Block] Group, [Status] In Progress, [Type] Regression
