### ISSUE TITLE
CSS Issue When Bar Button Are Not Invoked!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#1746] opened 2017-07-05 18:07 UTC
## Issue Overview
If an element doesn't have any use of bar button then the block on focus becomes disoriented. 

## Steps to Reproduce (for bugs)
1. Add a code block
2. Focus on the block.

## Expected Behavior
The block should not jump up.

## Current Behavior
![ixinstw8pa](https://user-images.githubusercontent.com/960133/27878095-83b9a394-61d6-11e7-8be1-a830e0d8b12d.gif)

Same thing happens if I try to add a custom block that doesn't make use of the button's bar.

**Comment by youknowriad** [comment] 2017-07-05 18:10
This seems fixed in master, which version are you using?

**Comment by jasmussen** [comment] 2017-07-05 18:11
Yep, this was a 0.3.0 bug, fixed in 0.4.0. Thanks for the report though!

**Comment by ahmadawais** [comment] 2017-07-05 18:21
@youknowriad @jasmussen Does NOT seem to be fixed here. I am at the HEAD of master at the moment. Double checked!

**Comment by youknowriad** [comment] 2017-07-05 18:22
Just double checked too, works for me, what browser are you using?

**Comment by ahmadawais** [comment] 2017-07-05 18:29
Latest Chrome! OSX

**Comment by jasmussen** [comment] 2017-07-05 18:32
Cache cleared? It was a CSS thing.

**Comment by ahmadawais** [comment] 2017-07-06 00:29
Yup no luck there either. Wonder if we might wanna keep this issue open to see there are similar complaints?

**Comment by jasmussen** [comment] 2017-07-06 06:56
Fine to reopen, good idea, but I'd wager it's fixed in master but didn't make the 0.3 cut.

**Comment by mtias** [comment] 2017-08-18 21:07
Going to close this one as it seems to work well. Feel free to comment again if you can still reproduce.

**Closed by mtias** 2017-08-18 21:07 UTC
