### ISSUE TITLE
Template Editing Mode: Preview doesn't reflect switching between templates

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31567] opened 2021-05-06 18:59 UTC
## Description

Using the new template editing mode, if you change which template a post is using and try to preview it, the preview doesn't reflect the change in template. 

## Step-by-step reproduction instructions

1. Set up a site with FSE capabilities
2. Add a new post 
3. In the sidebar settings, change which template the post is using.
4. Preview the post and go back to the editor.
5. In the sidebar settings, change which template the post is using once more (make sure it's a template with changes).
6. Preview the post and notice the template didn't update. 

## Expected behaviour

I expect the preview to show the template I selected in the editor. 

## Actual behaviour

The preview shows only the last selected template/new template if you created one. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/117350961-62114f00-ae6a-11eb-8c92-b081db7ecd2b.mov

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6 RC
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by paaljoachim** [comment] 2021-05-06 22:37
Older associated issue related to Page templates:
https://github.com/WordPress/gutenberg/issues/17727

**Comment by youknowriad** [comment] 2021-05-07 07:43
closing  this  as duplicate of #17727

Unfortunately thought, I don't expect this to be fixed soon. That's related to a very old behavior for autosaves in Core that is very unlikely to change. It might be better as a trac ticket actually

**Closed as completed by youknowriad** 2021-05-07 07:43 UTC
Labels: [Type] Bug, [Feature] Template Editing Mode

**Comment by paaljoachim** [comment] 2021-05-09 07:24
I am pinging
@iandunn @peterwilsoncc @desrosj @audrasjb 
To let you all know about this issue as well as the original one that Ian made.
It would be great if this could be transferred over to Trac.
