### ISSUE TITLE
How do I remove white space at the bottom of embed?

### ISSUE THREAD

**Issue by daleferrario** [WordPress/gutenberg#10631] opened 2018-10-15 19:28 UTC
I have used embed previously to add "See Also" at the bottom of my posts. It worked great.

Today when I added the links I get a lot of white space.

How do I remove this wite space?

Thanks!
Dale

![embed block website](https://user-images.githubusercontent.com/30103782/46973322-c0407180-d075-11e8-88e4-fb19e3d7a271.JPG)
![embed block editor](https://user-images.githubusercontent.com/30103782/46973323-c0d90800-d075-11e8-81db-1ac9c49434cd.JPG)

**Comment by ianbelanger79** [comment] 2018-10-15 19:46
Hi @daleferrario,

You can remove this space by un-checking the "Automatically scale content" option in the blocks toolbar.

![scale-content](https://user-images.githubusercontent.com/34601694/46974188-546c0200-d091-11e8-956c-6a8afc3b6004.PNG)

I am going to close this issue because it is a duplicate of #10419

**Closed by ianbelanger79** 2018-10-15 19:46 UTC
Labels: Embeds, [Status] Duplicate, [Type] Bug

**Comment by daleferrario** [comment] 2018-10-15 19:59
Thanks for the quick response. But my block is not Vimeo, it is WordPress. I do not have the ability to turn off automatic scale content. Do you have another recommendation for how to fix this?

Thanks,
Dale
![wordpress embed type](https://user-images.githubusercontent.com/30103782/46974893-16171880-d07a-11e8-8f76-a19f87532b19.JPG)
