### ISSUE TITLE
Editing post in Text Mode causes shared blocks to go away

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#5754] opened 2018-03-22 23:38 UTC
## Issue Overview
If you edit a post using Text Mode, any shared blocks will appear as though they have been deleted when you return to Visual Mode.

## Steps to Reproduce (for bugs)
1. Create a new post
2. Create or insert a Shared Block
3. Switch to Text Mode
4. Make an edit, e.g. add a line of text
5. Return to Visual Mode

## Expected Behavior
The Shared Block should render properly in the visual editor.

## Current Behavior
The Shared Block appears as though it has been deleted.

## Possible Solution
This is because `RESET_BLOCKS` is dispatched when `PostTextEditor` is blurred. This has the unintended side effect of deleting the block that the Shared Block is referencing.

One solution is to change `RESET_BLOCKS` so that it doesn't delete any blocks in `blocksByUid` that are referenced by `orderedBlocks` or `reusableBlocks`.

cc. @aduth 

## Screenshots / Video
![bug](https://user-images.githubusercontent.com/612155/37804010-45e10256-2e86-11e8-9928-9042af965cf2.gif)

## Related Issues and/or PRs
https://github.com/WordPress/gutenberg/pull/5228 introduced this bug. I discovered this while debugging https://github.com/WordPress/gutenberg/issues/2978 which is vaguely related.

**Comment by noisysocks** [comment] 2018-07-11 00:55
https://github.com/WordPress/gutenberg/pull/7453 (or any similar refactor of how we implement shared blocks) will likely fix this.

**Comment by slimmilkduds** [comment] 2018-09-05 05:16
I’ve checked related the tickets related to this. Is it right to assume that this problem probably wont be resolved until 5.0 or later? 

For me this is an incredibly annoying issue since my only plan atm for templating involves using e.g. an 3rd party section block or a hacky 1 column column block to store a bunch of blocks as a reusable block (and to convert that to a regular block after importing the ”template”)

I know there’s a way to make a specific template load for CPTs but we need to be able to have multiple templates availiable for each CPT.

Sorry, rant over.

**Comment by dkieffer** [comment] 2018-09-10 14:43
@slimmilkduds my current workaround until this is fixed is creating custom html reusable blocks.

`
<section class="page-section header-section">
	<div class="content-wrapper">
		<div class="header-title">
`

**Comment by slimmilkduds** [comment] 2018-09-13 04:44
@dkieffer The custom html reusable block, how does that work?

**Comment by dkieffer** [comment] 2018-09-13 14:13
@slimmilkduds add a custom html block, make some sections or divs or whatever, then convert it to a reusable block.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/6288440/45493681-f3b97480-b734-11e8-9bbd-d9ea29276174.png">

**Comment by slimmilkduds** [comment] 2018-10-29 04:54
Now since 
https://github.com/WordPress/gutenberg/pull/7453# got pushed to phase 2, is there any chance of some stop gap solution to this or will 5.0 actually ship with this bug?

**Comment by noisysocks** [comment] 2018-10-29 05:18
Yes we will need to fix this. Note that it's up to the release lead whether or not #7453 will be punted. Right now, it's still in the 5.0 milestone.

> For me this is an incredibly annoying issue since my only plan atm for templating involves using e.g. an 3rd party section block or a hacky 1 column column block to store a bunch of blocks as a reusable block (and to convert that to a regular block after importing the ”template”)

If I'm understanding you correctly, https://github.com/WordPress/gutenberg/pull/9732 which was shipped in Gutenberg 3.9 should let you turn multiple blocks into a single reusable block.

**Comment by slimmilkduds** [comment] 2018-10-29 05:31
> Yes we will need to fix this. Note that it's up to the release lead whether or not #7453 will be punted. Right now, it's still in the 5.0 milestone.
> 
> > For me this is an incredibly annoying issue since my only plan atm for templating involves using e.g. an 3rd party section block or a hacky 1 column column block to store a bunch of blocks as a reusable block (and to convert that to a regular block after importing the ”template”)
> 
> If I'm understanding you correctly, #9732 which was shipped in Gutenberg 3.9 should let you turn multiple blocks into a single reusable block.

Yeah, that was written before 3.9. The problem is that with the reusable templates released in 3.9 this bug only becomes more apparent. Creating a reusable block from multiple blocks is a 100 times smoother than what I was planning to do pre 3.9.  I imagine loads of users will be pretty disapointed to have such an awesome feature rendered unusable if you want the reusable template to contain a column or any other block with nested support.

**Comment by slimmilkduds** [comment] 2018-10-29 05:40
Just to be clear, it’s another issue I’m referring to that you mentioned likely had the same root cause as the one described in this ticket:
https://github.com/WordPress/gutenberg/issues/9278

**Comment by noisysocks** [comment] 2018-10-29 05:54
Thanks for the clarification @slimmilkduds! I'll look into getting a quicker albeit less ideal fix in for these two bugs 🙂

**Comment by slimmilkduds** [comment] 2018-10-29 07:05
That sounds great! ☺️

**Comment by noisysocks** [comment] 2018-10-30 05:53
> This is because `RESET_BLOCKS` is dispatched when `PostTextEditor` is blurred. This has the unintended side effect of deleting the block that the Shared Block is referencing.
> 
> One solution is to change `RESET_BLOCKS` so that it doesn't delete any blocks in `blocksByUid` that are referenced by `orderedBlocks` or `reusableBlocks`.

This still holds true and is a little tricky to address. Some ideas:

1. Change the shape of state so that `blocksByClientId` and `orderedBlocks` are removed in lieu of a `blocks` object with a `byClientId` and `order` subtrees. Then, `RESET_BLOCKS` could ignore blocks that are present in the `.order` subtree. @aduth also did this as part of https://github.com/WordPress/gutenberg/pull/10844.
2. Mark reusable blocks in `blocksByClientId` with a flag e.g. `isReusable: true`. Then, `RESET_BLOCKS` could ignore blocks that have the `isReusable` flag set. `getBlock` could strip this flag out so that there isn't any extra API which we have to maintain.

**Closed** 2018-11-19 16:46 UTC
Labels: Priority High, [Component] Reusable Blocks, [Status] In Progress, [Type] Bug
