### ISSUE TITLE
Set the cursor to the clicked position if a text block is selected via click

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#12217] opened 2018-11-22 11:22 UTC
**Is your feature request related to a problem? Please describe.**

Selecting a paragraph block (or headline block, et cetera) via clicking sets the cursor to the beginning of the block. I think it would be nice to set the cursor to the position the user clicked – at least for me it is like an additional step because I need to set the cursor to the wanted position after selecting the block.

**Describe the solution you'd like**

Directly set the cursor to the clicked position.

**Comment by designsimply** [comment] 2018-11-23 17:21
Tested and confirmed that clicking on a paragraph block places the cursor at the beginning of the paragraph (tested with WordPress 4.9.8 and Gutenberg `bd897f6cb` (>4.5.1) using Firefox 63.0.3 on macOS 10.13.6).

My take: I personally like the suggestion of adding it to the bottom because it seems more inline with a writing flow of adding new content to below the current content clicked.

**Comment by florianbrinkmann** [comment] 2018-11-23 18:54
Bottom would be better, but (in my opinion) also not ideal. For example, if you see a paragraph with a word you want to remove or modify. Then you click on that word to place the cursor there, but the cursor first jumps to the beginning (or end) if that click is the select-the-block-click. I think it would be great, if the cursor could directly be placed (in the example) on that word, so no additional click is needed before I can modify/edit the word.

**Comment by rpkoller** [comment] 2018-11-24 23:50
@florianbrinkmann in Safari and Chrome (on MacOS) Gutenberg is already behaving like you requested ( tested in RC1 on MacOS). Only Firefox is behaving that way, other browsers I haven't tested. @designsimply so I would file it as a bug instead of a feature request.

**Comment by chrisvanpatten** [comment] 2018-11-25 01:20
I’m about 90% sure there is an issue open for this. I believe @danielbachhuber might have reported it...?

**Comment by chrisvanpatten** [comment] 2018-11-25 02:41
Found it, this is a dupe of #11812! I'll close this so we can consolidate the discussion there, where it's classified as a bug already :) Thanks for the reports/confirmations, y'all!

**Closed by chrisvanpatten** 2018-11-25 02:41 UTC
Labels: Writing Flow, [Type] Enhancement

**Comment by florianbrinkmann** [comment] 2018-11-25 06:57
Thanks! :)
