### ISSUE TITLE
Cannot create reusable block if template lock is on

### ISSUE THREAD

**Issue by benplum** [WordPress/gutenberg#16008] opened 2019-06-05 17:05 UTC
**Describe the bug**
If a post uses a locked block template, the child blocks can not be converted into reusable blocks. If a reusable block is added via the code view the reusable block renders fine, as does selecting an existing reusable block from the inserter, but the option to convert an existing local block to a reusable block is not displayed. 

**To reproduce**
1. Add a locked block template to a post type.
2. Add a new post of that type and insert a block (one that can theoretically be reused)
3. Click on the block options and see that the option to convert to a reusable block is missing.

**Expected behavior**
The convert to reusable block should be an option for any block that is set to be reused.

**Comment by talldan** [comment] 2019-11-14 05:35
Hi @benplum, thanks for creating the issue, and apologies it took a while for a response.

My feeling is that this behaviour is by design. Creating a reusable block replaces the current selection of blocks with the new reusable block. Looking at the docs for template locking (https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#locking), the two options are:

> all — prevents all operations. It is not possible to insert new blocks, move existing blocks, or delete blocks.
insert — prevents inserting or removing blocks, but allows moving existing blocks.

Both don't allow inserting or removing blocks, which is what would be involved in creating a reusable block.

I do think the docs could be updated to make this clearer though.

**Comment by pwkip** [comment] 2020-05-04 14:58
While we could argue about allowing locked blocks to be reusable or not, I think the inner blocks of locked blocks should definitely be convertible to reusable blocks. This is not the case right now. Even if you define it explicitly on a block that is part of a template:

```
registerBlockType( 'my-plugin/content-part', {
  // ...
  supports: {
    reusable: true, // <--------- This has no effect on the block or any of its InnerBlocks
  },
  // ...
  edit( { className } ) {
    return (
      <div className={ className }>
        <InnerBlocks templateLock={ false } />
      </div>
    );
  },
}
```
Note that this is only the case if the block is loaded as part of a template AND template_lock is true or 'insert'. With template_lock set to false, all blocks become reusable again.

This might be related to other problems with inner blocks inside a template-locked block: https://github.com/WordPress/gutenberg/issues/11681

**Comment by talldan** [comment] 2021-01-28 03:09
@pwkip Late reply, but that sounds like a different issue to the one reported here. Maybe make a new issue if there's not one already reported.

**Comment by youknowriad** [comment] 2024-11-11 13:06
Going to close this issue in favor of #11681 as it's the same one really (just manifesting slightly differently).

**Closed by youknowriad** 2024-11-11 13:06 UTC
Labels: [Type] Developer Documentation, Good First Issue, [Feature] Templates API, [Feature] Synced Patterns
