### ISSUE TITLE
Preview doesn't work after modifying on published posts

### ISSUE THREAD

**Issue by idpokute** [WordPress/gutenberg#4099] opened 2017-12-20 04:12 UTC
## Issue Overview

Preview doesn't work after modifying on published posts. 

## Steps to Reproduce (for bugs)

1.Add new post.
2.Write a title and add new paragraph block.
3.Publish it.
4.Delete the paragraph block.
5.Click Preview

## Expected Behavior

Display the preview.

## Current Behavior

The blank popup is showed and shows the message"Please wait…Generating preview." but nothing happens.

## Screenshots / Video

The post in the gif was already published. I did Step 4 and 5 of "Steps to Reproduce"
![PreviewGIF](http://wp.senna-design.com/wp-content/uploads/2017/12/preview.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment] 2018-01-23 22:15
Hi @idpokute,

Thanks for the report. I can't reproduce this on `master`:

![previewpublished](https://user-images.githubusercontent.com/36432/35303747-e28b0e20-0047-11e8-901f-6ced089d5bec.gif)


Does the issue still reproduce for you? If so, can you look at your console to see if there are any relevant JavaScript or network errors?

**Comment by idpokute** [comment] 2018-01-26 20:48
Hi @danielbachhuber 

I updated Gutenberg V2.1, and I can still reproduce it. 
In the screenshot, it seems you miss fourth step; Delete the paragraph block.

As you delete the one block, click the preview button. Than you could reproduce it. 
Console doesn't show any related error so far.

**Comment by danielbachhuber** [comment] 2018-01-26 21:24
Thanks for following up, @idpokute. As a matter of fact, I ran into this issue independently yesterday too (working on something unrelated).

**Comment by skorasaurus** [comment] 2018-03-05 22:06
Confirming that I am able to reproduce this on gutenberg 2.3; console does not display anything.

**Comment by skorasaurus** [comment] 2018-03-23 13:39
Just confirming that I'm still experiencing this on gutenberg 2.4.

**Comment by skorasaurus** [comment] 2018-04-13 14:58
Just following up, I'm still able to reproduce this on gutenberg 2.6 and wordpress 4.9.5; I have tried this on the vanilla wordpress spun up w/ vvv w/ no plugins; have experienced this on both firefox and chrome.

**Comment by skorasaurus** [comment] 2018-04-20 19:53
Just following up, I'm still able to reproduce this on gutenberg 2.7 and wordpress 4.9.5; I have tried this on the vanilla wordpress spun up w/ vvv w/ no plugins; have experienced this on both firefox and chrome

**Comment by jhackett1** [comment] 2018-04-25 17:55
I'm also seeing this on 2.7. I can't see any PHP or JS errors or obvious reason what's gone wrong.

**Comment by skorasaurus** [comment] 2018-05-07 15:19
Still experiencing this on 2.8. 

I've narrowed down that this only occurs if you do not click update before clicking preview.

**Comment by aduth** [comment] 2018-05-31 18:46
Noting that this is a known as-of-yet unimplemented feature, since it relies on the ability to autosave published posts, which until recently was not possible.

Related: #4112 #1773

**Comment by danielbachhuber** [comment] 2018-05-31 18:49
Let's make this happen!

**Comment by ginigangadharan** [comment] 2018-06-12 02:04
@danielbachhuber thanks.
Yes, I have mentioned that in #7253 , if you save the draft/post, then preview will work.
is that a bug or missing feature ?

**Comment by danielbachhuber** [comment] 2018-06-12 11:42
@ginigangadharan This is a known bug that's being worked on. While work is being tracked in #2544 and others, we can keep this issue open for visibility until it's addressed.

**Comment by aduth** [comment] 2018-06-20 17:44
Closed by #7130.

**Closed by aduth** 2018-06-20 17:44 UTC
Labels: [Type] Bug
