### ISSUE TITLE
Group block background color adding extra padding to first paragraph with aligned image

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#15177] opened 2019-04-25 15:12 UTC
**Describe the bug**
When you create a group block with a background color, it adds padding. Perfect.

When you add a paragraph block to the group, no problem. When you add an image block that's left or right aligned next to the paragraph, the paragraph seems to get extra padding above it, which does look good next to the image: the paragraph should align with the top of the image.

**To reproduce**

For testing purposes, use the Twenty Nineteen theme.

1. Add a group block and add a background color (so it has the padding)
2. Add a paragraph block and put some text in it (no background color)
3. Add an image above the paragraph block, and align it either left or right
4. In the editor, it looks good. On live site, the paragraph block gets an extra padding above the block.

This happens only on the first paragraph/block combination in the group.

**Expected behavior**
Paragraph block should not get the extra padding above it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Versie 73.0.3683.103

**Additional context**
WP version: 5.1.1
Gutenberg version: 5.5.0

![1](https://user-images.githubusercontent.com/7248645/56747033-9206c180-677d-11e9-8547-ee397f8b780c.png)
![2](https://user-images.githubusercontent.com/7248645/56747035-929f5800-677d-11e9-9479-ae340180eca2.png)

**Comment by talldan** [comment] 2019-10-31 05:34
Hi @RobinRoelofsen. Thanks for reporting this. We discussed this issue during one of the core-editor triage meetings.

Out of interest, which theme were you using to reproduce the issue? It's likely the issue is very theme dependent.

When we tried to reproduce, we each got a myriad of issues depending on the theme.

In Twenty Nineteen we were seeing this:
*Editor*
<img width="634" alt="Screen Shot 2019-10-31 at 10 28 45 AM" src="https://user-images.githubusercontent.com/677833/67921494-e4b8ae80-fbe2-11e9-9bdc-4f0850376348.png">

*Post*
<img width="713" alt="Screen Shot 2019-10-31 at 10 28 53 AM" src="https://user-images.githubusercontent.com/677833/67921499-ee421680-fbe2-11e9-8f11-8b510a3544ed.png">

Not too bad. Twenty Twenty was completely different:
*Editor*
![Screen Shot 2019-10-31 at 1 21 41 pm](https://user-images.githubusercontent.com/677833/67921556-1a5d9780-fbe3-11e9-817f-5ef28911f2a3.png)

*Post*
![Screen Shot 2019-10-31 at 1 21 32 pm](https://user-images.githubusercontent.com/677833/67921562-1fbae200-fbe3-11e9-9572-8bd762e0b18e.png)

I think there are clearly some issues, so I'll leave this open.

**Comment by RobinRoelofsen** [comment] 2019-11-01 15:33
Hi @talldan,

Thanks for looking into this.

I was using the GeneratePress theme.

**Comment by youknowriad** [comment] 2023-04-11 15:44
This is an old issue but I noticed that left and right aligned image blocks in classic themes indeed add `0.5em` margin top and bottom. This is indeed very opinionated but it's consistent as it's applied both the editor and frontend.

We could remove these margins but it will have a visible impact on existing themes and sites. So my opinion would be to just close this issue as won't fix. 

But curious about other thoughts cc @jasmussen

**Comment by jasmussen** [comment] 2023-04-12 07:46
Tested this out a fair bit, both with block themes and classic themes. I know this issue and the opinionated style is present in classic themes only, but just for reference, in block themes in fact, the top margin is fairly noticable:

<img width="1029" alt="Screenshot 2023-04-12 at 09 40 08" src="https://user-images.githubusercontent.com/1204802/231387667-14637949-d30f-4c4d-a14b-407cde67e853.png">

This appears to be the general flow content block spacing that gets applied as a top margin on the image:

<img width="303" alt="Screenshot 2023-04-12 at 09 40 30" src="https://user-images.githubusercontent.com/1204802/231387891-38514883-7c4a-4037-ad95-f9928acd1614.png">

If zeroed out, it would look like this:

<img width="1029" alt="Screenshot 2023-04-12 at 09 40 40" src="https://user-images.githubusercontent.com/1204802/231388008-79ab3a40-a872-4447-9480-efe128e04493.png">

I'm not suggesting that as a change, just noting.

For classic themes, I can indeed reproduce and seeing this:
<img width="303" alt="Screenshot 2023-04-12 at 09 41 39" src="https://user-images.githubusercontent.com/1204802/231388116-419100ff-d43e-48c2-9b4e-315c5f589b4a.png">

<img width="701" alt="Screenshot 2023-04-12 at 09 41 44" src="https://user-images.githubusercontent.com/1204802/231388140-9acae204-579d-410e-930f-61ba998e1e5a.png">

Here's how it would look, at least in Twenty-Thirteen, if we were to remove that opinionated style:

<img width="752" alt="Screenshot 2023-04-12 at 09 41 56" src="https://user-images.githubusercontent.com/1204802/231388258-d6a548e9-c7b3-4690-af30-a874770621f7.png">

It's such a small change, that I have no strong opionion. I tend to think that classic themes are more likely to customize and override these styles anyway, so I'm tempted to agree with Riad that this is likely best kept as-is to keep existing content intact. But that's not a strong opionion.

**Comment by youknowriad** [comment] 2023-04-12 09:46
Going to close this for now. Thanks for raising it though.

**Closed by youknowriad** 2023-04-12 09:46 UTC
Labels: [Type] Bug, [Block] Group
