### ISSUE TITLE
Multi-select may break when Unified Toolbar on

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#9796] opened 2018-09-11 15:03 UTC
**Describe the bug**

While multi-selecting with the keyboard's arrow keys, if the new Unified Toolbar option is on, selection may break in the sense that whole blocks are no longer selected, but rather — seemingly — selection moves across content per the browser's default selection method. See screenshot below.

![gutenberg-multi-select-unified-toolbar](https://user-images.githubusercontent.com/150562/45368464-9067ff00-b5db-11e8-89f9-8b1e35067c9c.gif)

**Desktop (please complete the following information):**
 - OS: macOS, stable
 - Browser: Firefox Dev, latest

**Comment by youknowriad** [comment] 2018-09-13 09:11
Closing as duplicate of #9848 because it has more discussions.

**Closed by youknowriad** 2018-09-13 09:11 UTC
Labels: Chrome, [Component] Multi-Select, [Type] Bug
