### ISSUE TITLE
Navigation: Not adding a submenu the "Add link..." remains and is not automatically deleted.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21448] opened 2020-04-07 08:09 UTC
Related #21450

**Describe the bug**
"Add link..." remains even though one might have changed ones mind in adding a submenu.
To remove it one needs to click into it and add some letters (or click into it and then go to the toolbar select the 3 dots menu and select remove block). Then select the container around it which is hard to see and then click delete on the keyboard.

**Steps:**

Click menu item. Then click to Add Submenu.

![Screen Shot 2020-04-07 at 10 01 11](https://user-images.githubusercontent.com/5323259/78644908-f2234480-78b6-11ea-9a06-7870f81ac247.png)

Then change your mind. No submenu is needed anyway.

"Add link..." remains even though one have not added a submenu.

![hard-to-remove-add-to-link](https://user-images.githubusercontent.com/5323259/78646609-97d7b300-78b9-11ea-8181-10b786c80975.gif)

One then needs to either click into the "Add link..." area and then go to the toolbar, click the 3 dots menu and remove block or write some letters into the area then select it and click the delete key on the keyboard.

**Solution I would like to see:**
The "Add link..." should when not adding a submenu be automatically removed.

Gutenberg 7.8.1
Chrome
Live dev site

(Adding the following info here as well)
William as you worked on the Permalink PR. #12009
When not saving and clicking outside of the box the Permalink would automatically close. I am thinking the same method can be used on this issue and the related adding top level menu item issue I made. https://github.com/WordPress/gutenberg/issues/21450
@earnjam

**Comment by talldan** [comment] 2020-04-20 02:27
This seems like a very similar issue to #21450, it might be possible to consolidate them.

The only thing that differs is that the 'Add Submenu' button perhaps doesn't make it clear that it'll add a block in a submenu and that removing that block will remove the submenu. I think that might be where the confusion is coming from.

I'll add the `Needs design feedback` label.

**Comment by draganescu** [comment] 2020-06-04 19:49
This is a duplicate of #21848

**Closed by draganescu** 2020-06-04 19:49 UTC
Labels: Needs Design Feedback, [Block] Navigation
