### ISSUE TITLE
Resizing images in the image gallery are not reflected in the Gutenberg UI

### ISSUE THREAD

**Issue by tpolischuk** [WordPress/gutenberg#28250] opened 2021-01-15 19:38 UTC
## Description
When resizing images in a gallery block, the size of the image is never reflected in the drop down.

## Step-by-step reproduction instructions
Create an image gallery and assign a few images.
Select a new image size in the block editor. 

## Expected behaviour
I would expect that the new size would be reflected in the dropdown.

## Actual behaviour
The value in the dropdown never changes, even though the image does.

## Screenshots or screen recording (optional)
https://imgur.com/th99QM7

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? All plugins are disabled
- Are you using a default theme: Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu 18.04
- Browser: Google Chrome

**Comment by paaljoachim** [comment] 2021-01-23 15:07
@tpolischuk 

I believe this is a similar issue to what you are mentioning here:

In Image Block the image size in drop down is not proper as per image dimension
Linking to my comment here: https://github.com/WordPress/gutenberg/issues/27198#issuecomment-747611900

**Comment by Intervik** [comment] 2021-02-10 07:01
This occurs on wp-block-image too, but we are stuck on "thumbnail" size

**Comment by paaljoachim** [comment] 2021-02-11 09:10
The Image gallery is getting a total work over with inner child blocks in a parent Gallery block.
https://github.com/WordPress/gutenberg/pull/25940

**Comment by ocean90** [comment] 2021-02-26 14:04
This was already fixed in #27691 but unfortunately was never back-ported to 5.6. It will be fixed in WordPress 5.7, planned for March 9th.

Duplicate of #27492.

**Closed by ocean90** 2021-02-26 14:04 UTC
Labels: [Block] Gallery, [Status] Duplicate
