### ISSUE TITLE
"Wide" Full Width Image Available But Not Showing

### ISSUE THREAD

**Issue by chillvillain** [WordPress/gutenberg#9594] opened 2018-09-03 21:44 UTC
The demo post has a full width image inside of it (gorgeous) but when I changed it to be centered, I didn't see the "Wide" option show up anywhere.

**Comment by ianbelanger79** [comment] 2018-09-04 19:39
Hi @chillvillain,

Thanks for your report. In order to use the Wide and Full-wide, your theme must add the support for it by using `add_theme_support( 'align-wide' )`. The demo comes with the code for the full-width images, but once you change it to something else, you can't add it back in without the theme supporting it.

Check your theme's functions file for `add_theme_support( 'align-wide' )`, if you don't see it, you can add it and then you will see the option for Wide and Full-wide images.

I am closing this ticket as it is not a bug or feature request.

**Closed by ianbelanger79** 2018-09-04 19:39 UTC
Labels: [Type] Help Request

**Comment by chillvillain** [comment] 2018-09-04 20:51
Thanks Ian! I successfully added that function and see the buttons for Wide
Width and full width. In the Gutenburg editor, it correctly widens the
image to each setting and looks fantastic, but then in the preview of the
post both the wide width and the full width images are still constrained to
the width of the text...
