### ISSUE TITLE
Block toolbar icons duplicate when editing a reusable block

### ISSUE THREAD

**Issue by thomashigginbotham** [WordPress/gutenberg#21829] opened 2020-04-23 14:39 UTC
**Describe the bug**
While editing a reusable block, if you give focus to another block, the icons on its toolbar will duplicate, and only the old icon buttons work, while the duplicated icons appear to be tied to the reusable block.

**To reproduce**

1. Create a new page.
2. Add a Paragraph block with some sample text.
3. Add another Paragraph block below the first with more sample text.
4. Convert the second Paragraph block into a reusable block but do not save it (leave in edit mode).
5. Click inside the second Paragraph block again to give it focus.
6. Click inside the first Paragraph block to give it focus.
7. Notice the first Paragraph block icons have been duplicated.

**Expected behavior**
The block toolbar icons should not be duplicated.

**Screenshots**

<img width="545" alt="duplicated-icons" src="https://user-images.githubusercontent.com/1651691/80111674-2c930f80-854e-11ea-90c7-af783df9f4af.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Comment by annezazu** [comment] 2020-04-23 22:28
Thanks for this report! This oddly took me a bit to replicate. I had to click in and out of the different blocks before the duplication happened. 

**Screenshots/Screencasts**

No duplication:
<img width="773" alt="Screen Shot 2020-04-23 at 3 23 52 PM" src="https://user-images.githubusercontent.com/26996883/80155591-dd150980-8576-11ea-9d80-0a6df7f222f6.png">

Duplication:
<img width="777" alt="Screen Shot 2020-04-23 at 3 24 00 PM" src="https://user-images.githubusercontent.com/26996883/80155569-d2f30b00-8576-11ea-9d8a-8d6224d25e71.png">

Here's a video showing the duplication appearing upon toggling between the two paragraphs a second time: https://cloudup.com/cHE5JHj8TW0

**My Setup**

- MacOS 10.14.6
- Chrome 81.0.4044.122 
- WordPress 5.4 (gutenberg deactivated)
- Twenty Twenty theme with no other plugins activated

**Comment by chrisvanpatten** [comment] 2020-05-01 01:57
I suspect this is a duplicate of #19436 — could you confirm @thomashigginbotham @annezazu?

**Comment by annezazu** [comment] 2020-05-01 03:01
Ah yes. I can confirm!  Closing this out in favor of #19436.

**Closed by annezazu** 2020-05-01 03:01 UTC
Labels: [Block] Block, [Feature] Blocks, [Feature] Reusable Blocks, [Type] Bug
