### ISSUE TITLE
Editor: Additional Panels cannot be moved via drag and drop

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#49451] opened 2023-03-29 21:44 UTC
### Description

Originally reported here: https://github.com/Automattic/wp-calypso/issues/74876

### Quick summary

Moving "Additional" panels back and forth between the sidebar and below the editor via drag and drop is not working.  Tested with "Custom Fields" panel as well as free Yoast SEO plugin's panel.

1 exception: When 2 panels are enabled, such as **Custom Fields** and **Yoast SEO**, and one is in the sidebar while the other is below the editor - then it is possible to drag and drop the panel below the editor into the sidebar.  

### Step-by-step reproduction instructions

1. Open a page or post, then open Editor Preferences > Panels
2. Toggle on the "Custom Fields" panel and reload the editor
3. Try dragging the Custom Fields panel from below the editor to the sidebar
     - Trying this just causes a horizontal scroll in the editor, but you can't drop the panel into the sidebar.
4. Next, install & activate Classic Editor plugin
5. Return to post, and move 1 additional panel(s) to the sidebar
6. Deactivate Classic Editor plugin, and return to the post
     - Your relocated panel will now appear in the sidebar. From here, it's possible to relocate the panel below the editor to the sidebar, but then it's not possible to move anything back.

### Screenshots, screen recording, code snippet

Behavior after steps 1-3:

https://user-images.githubusercontent.com/27249804/228673746-1d0b5ac2-c481-4548-9a31-5eb7373546a2.mov

Behavior after steps 4-6:

https://user-images.githubusercontent.com/27249804/228674197-e665b8c4-5010-4e39-a96a-e719a4256b1d.mp4

### Environment info

WordPress 6.2
Gutenberg 15.4.0; same behavior with Gutenberg deactivated (but no classic editor plugin active)

Tested with Yoast SEO v20.4 activated to see another panel. Behavior matched the above without this plugin active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2023-03-30 06:13
Hi, @cuemarie

This is a duplicate of #7960.

**Closed as not planned by Mamaduka** 2023-03-30 06:13 UTC
Labels: [Feature] Meta Boxes, [Status] Duplicate

**Comment by albanyacademy** [comment] 2023-10-25 23:04
@cuemarie  just do this:

https://github.com/WordPress/gutenberg/pull/25187#issuecomment-1780174882
