### ISSUE TITLE
Enhancement: On mobile, columns should be stacked

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#9449] opened 2018-08-29 22:46 UTC
Due to size constraints on mobile, columns should be stacked.

This would be in keeping with general practice, such as page builders.

**Comment by youknowriad** [comment] 2018-08-29 23:06
Thanks for the issue, I'm closing as a duplicate of #9449 please follow the discussion there. Thanks.

**Closed by youknowriad** 2018-08-29 23:06 UTC

**Comment by GlennMartin1** [comment] 2018-08-29 23:20
This is issue # 9449. Your evidently meant a different issue number.

**Comment by youknowriad** [comment] 2018-08-29 23:26
Yes sorry #6048 I probably should go to bed :P
