### ISSUE TITLE
Setting the alignment property of the "Media & Text" block to "wide" does not add block attribute

### ISSUE THREAD

**Issue by greatislander** [WordPress/gutenberg#15476] opened 2019-05-06 23:37 UTC
**Describe the bug**
The Media & Text block defaults to `wide` alignment. However, this alignment value is not assigned as a block attribute, so the `parse_blocks()` function can only determine the block's alignment setting if it is set to `full`.

**To reproduce**
1. With the latest (master) version of the Gutenberg plugin, add a new Media & Text block to an empty post or page but do not change the default alignment (or change it to `full` and then back to `wide`).
2. Update the post or page.
3. Access the block's attributes via the `render_block` hook (I added this code in a must-use plugin for debugging):
```php
add_filter('render_block', function ($block_content, $block) {
    return '<pre>' . print_r( $block['attrs'], true ) . '</pre>';
}, 10, 2);
```
4. Instead of seeing the `wide` alignment listed alongside other attributes, no alignment is shown:

```php
Array
(
    [mediaId] => 6
    [mediaType] => image
)
```

**Expected behavior**
Alignment attributes should always be exposed via `parse_blocks()` / `render_block()`. If a block has a default alignment, it should still be retrieved from block attributes.

**Example Source**

_Align: Wide_
```html
<!-- wp:media-text {"mediaId":6,"mediaType":"image"} -->
<div class="wp-block-media-text alignwide"><figure class="wp-block-media-text__media"><img src="https://render-blocks.island/wp-content/uploads/2019/05/56162874_2232284040126920_3990250984235335680_o-1024x679.jpg" alt="" class="wp-image-6"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">text</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->
```

_Align: Full_
```html
<!-- wp:media-text {"align":"full","mediaId":6,"mediaType":"image"} -->
<div class="wp-block-media-text alignfull"><figure class="wp-block-media-text__media"><img src="https://render-blocks.island/wp-content/uploads/2019/05/56162874_2232284040126920_3990250984235335680_o-1024x679.jpg" alt="" class="wp-image-6"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">text</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Firefox Quantum
 - Version: 66.0.3

**Additional context**
 - I discovered this when trying to add a wrapper element to wide/full aligned blocks using the `render_block` hook. See [Slack conversation](https://wordpress.slack.com/archives/C02QB2JS7/p1556717887127700). I thought this was an issue with `render_block` because it was consistently retrieving alignment values from all blocks except the Media & Text block. As far I can tell now, this is either a bug with the block parser or with the Media & Text block; I'm not clear if the parser should be able to determine the alignment from the presence of the `alignwide` class or whether the block attribute in the block delimiter comment is the source of truth for the parser.

**Comment by talldan** [comment] 2019-05-07 02:06
Hi @greatislander. I didn't realise this until working on #12757, but this is the expected behaviour. default properties are not saved if the value of that property is unchanged from the default.

After the block data is parsed from the content, the next phase is to create the block using the matching block type with the parsed data. My understanding is that during this phase, `getBlockAttribute` is called against each of the block attributes specified in the block type:
https://github.com/WordPress/gutenberg/blob/d8f1875c229f49f9af501c3259bbd16461aa6aae/packages/blocks/src/api/parser.js#L274-L306

In that code, the default is applied when a value is undefined:
```
 	if ( value === undefined ) { 
 		return attributeSchema.default; 
 	} 
```

I imagine the issue is that the filter you're working with is using the parsed representation of the block, but is triggered before the default attribute is applied from the block type. It looks like `render_block` only renders dynamic blocks, so it'd be expected that the Media and Text's align default isn't applied:
https://github.com/WordPress/wordpress-develop/blob/a8942b4a17f1b1de9f6dfd9f649685be89c9759b/src/wp-includes/blocks.php#L261-L265

I'm not sure what the way around it is for your use case, perhaps the default can be read from the `block.json` and applied if the value isn't set in the parsed data? It seems like that would work for most cases, but granted it adds a bit more complexity.

I'll close the issue, as this isn't a bug as far as I'm aware. It can always be re-opened if it turns out something needs to be changed as a result of this discussion.

**Closed by talldan** 2019-05-07 02:06 UTC
Labels: [Block] Media & Text

**Comment by greatislander** [comment] 2019-05-07 12:11
@talldan Thanks for the detailed explanation. I still feel like this behaviour is a bit weird given that the `render_block` filter is supposed to work with all blocks as per @aduth's comment here: https://wordpress.slack.com/archives/C02QB2JS7/p1556718011130600

I guess TL:DR; — I believe that the core `render_block` filter should have access to default attributes of all blocks, static or dynamic. Otherwise there are bound to be other weird edge cases like the one I encountered and the filter is much less useful.

**Comment by aduth** [comment] 2019-05-07 13:12
> I still feel like this behaviour is a bit weird given that the `render_block` filter is supposed to work with all blocks as per @aduth's comment here: https://wordpress.slack.com/archives/C02QB2JS7/p1556718011130600

At the time it was raised, I had understood the issue in question to be whether `render_block` was being called _at all_, not to its specific behavior.

> I'm not sure what the way around it is for your use case, perhaps the default can be read from the `block.json` and applied if the value isn't set in the parsed data? It seems like that would work for most cases, but granted it adds a bit more complexity.

Just as it is in JavaScript, I do think it would be reasonable that the attributes received in the render callback would account for defaults automatically. It's currently made difficult by the fact that the server is rarely aware of these defaults. As you hint at, the development and availability of the `block.json` file should help make this possible. This is an active area of development (#13693). The code for assigning the default values in PHP already exists ([source](https://github.com/WordPress/wordpress-develop/blob/96649a5ad1a80cd8aaea15b955a48e292c406135/src/wp-includes/class-wp-block-type.php#L159-L166)), and needs only the attributes schema to be assigned from the JSON file.

That said, for the specific use case mentioned here, even if the default attribute value was made available, assigning a different value would not have the desired effect. You would need to provide an entirely substitute markup for the block, as otherwise the markup for the block had already been generated in the editor and saved to post content (it is not computed server-side).

**Comment by greatislander** [comment] 2019-05-07 16:48
Thanks for the info re: https://github.com/WordPress/gutenberg/pull/13693. I read the Make post about that initiative but I'll revisit it in more detail.

> That said, for the specific use case mentioned here, even if the default attribute value was made available, assigning a different value would not have the desired effect.

Actually, to clarify, if the default attribute was available my use case would work. The goal was to return the block content of `wide`- and `full`-aligned blocks within a wrapper element, like so:

```
add_filter( 'render_block', function ( $block_content, $block ) {
    if ( is_admin() || ! isset( $block['attrs']['align'] ) ) {
		return $block_content;
	}
	if ( $block['attrs']['align'] === 'wide' ) {
		$block_content = sprintf( '<div class="block-wrapper block-wrapper--wide">%s</div>', $block_content );
	} elseif ( $block['attrs']['align'] === 'full' ) {
		$block_content = sprintf( '<div class="block-wrapper block-wrapper--full">%s</div>', $block_content );
	}
	return $block_content;
}, 10, 2 );
```

The block markup would not be affected, but would be enclosed in a wrapper when it's displayed on the front end. I hope this clarifies.
