### ISSUE TITLE
Styles for the latest posts blocks are not loaded in the editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#26445] opened 2020-10-26 07:41 UTC
**Describe the bug**
The CSS for the latest posts blocks, including the grid style, is not loaded in the editor, only on the front.

**To reproduce**
1. Go to the editor.
2. Add a latest posts block.
3. Select the grid style. confirm that the block does not change.
4. Save and view the front.
5. See that the editor and front does not match.

**Expected behavior**
The editor and front needs to match.

**Screenshots**
![grid-56](https://user-images.githubusercontent.com/7422055/97145617-c68a7d80-1766-11eb-8e6e-04e058b6c901.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta1-49308

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome version 86.0.4240.111

**Comment by talldan** [comment] 2020-10-26 08:36
Closing as a duplicate of #26441

**Comment by ryelle** [comment] 2020-10-26 23:05
@talldan This is a different issue than #26441 — this happens in the editor, the frontend is fine. I tracked it back to https://github.com/WordPress/gutenberg/pull/26122 and opened a PR https://github.com/WordPress/gutenberg/pull/26477. Since it's not a duplicate, I'm going to re-open this issue.

**Comment by talldan** [comment] 2020-10-27 10:41
Oh, sorry for closing, but thanks for reopening.

**Closed** 2020-10-28 07:42 UTC
Labels: [Block] Latest Posts, [Type] Bug
