### ISSUE TITLE
Selecting the Reusable Block causes toolbar to appear inconsistently

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#33375] opened 2021-07-12 23:52 UTC
## Description

When trying to select the parent reusable block, I noticed the toolbar flickers/feels very unreliable to select. I fear this will be a painful user experience if not resolved for 5.8. 

## Step-by-step reproduction instructions

1. Create a reusable block. 
2. Edit the inner content and try selecting the overall parent reusable block. 
3. Notice the toolbar inconsistently appears. 

## Expected behaviour

Expect the toolbar reliably appear each time. 

## Actual behaviour

It is a bit flaky. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/125369498-978a5b00-e339-11eb-899f-c7d2dcc6880c.mov

## WordPress information
- WordPress version: 5.8-RC2
- Gutenberg version: not installed
- Are all plugins except Gutenberg deactivated? No, WP Beta Tester. 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome 89

**Comment by youknowriad** [comment] 2021-07-15 12:35
I have been able to reproduce in the Gutenberg plugin but not without it. Given this is flaky and a bit hard to reproduce, also it feels very minor to me, I'm removing this from 5.8.

**Comment by Thelmachido** [comment] 2022-08-19 21:04
I couldn't reproduce this issue with Gutenberg enabled as shown below. 

https://user-images.githubusercontent.com/41231764/185706445-977240ce-d9e3-4612-b2dd-5c70f5beacc1.mov

I will be closing this issue, please let me know if I missed something. 

Gutenberg 13.9.0
WordPress 6.0.1
Twenty Twenty-Two

**Closed as completed by Thelmachido** 2022-08-19 21:04 UTC
Labels: [Type] Bug, [Feature] Synced Patterns, [Block] Block
