### ISSUE TITLE
Buttons block: Full width vs wide width in Gutenberg 9.8.1

### ISSUE THREAD

**Issue by nagpai** [WordPress/gutenberg#28484] opened 2021-01-26 09:13 UTC
## Description

In Gutenberg 9.8.1 we see the option of Full width and wide width alignment in the buttons block (parent) settings. 

![Screen Shot on 2021-01-26 at 14:37:14](https://user-images.githubusercontent.com/4162931/105824206-0e2dd900-5fe4-11eb-8652-4ec33bde0e4c.png)

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. On a test website add a buttons block with at least two or three buttons within it
2. Navigate to the parent Buttons block and change the settings from wide width to full width.

## Expected behaviour

I would expect the buttons to get spread out. 

## Actual behaviour

Nothing changes at the front end. In the editor we do see the container of the buttons going full width, but the position of the buttons inside remains unchanged.  This can cause confusion to users, unless we have a setting to adjust spacing between buttons. 

Although this sounds feature request-ish, I have reported it as a bug since it has a tendency to confuse users. 

## Screenshots or screen recording (optional)
![Screen Shot on 2021-01-26 at 14:37:14](https://user-images.githubusercontent.com/4162931/105824613-990ed380-5fe4-11eb-93db-17c55d4ca229.png)

## WordPress information
- WordPress version: 5.6 
- Gutenberg version: 9.8.1  
- Are all plugins except Gutenberg deactivated? Yes 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes - 2020 theme 

## Device information
- Device: iMac - Desktop 
- Operating system: MacOS Big Sur 
- Browser: Vivaldi (Chromium based) 3.5.2

**Comment by t-hamano** [comment] 2022-06-11 12:52
I tested again with the latest Gutenberg and WordPress and could not reproduce it with either theme.
I could not find a specific fix PR, but it looks to me that this issue has already been resolved.

## Twenty Twenty Two

| Editor  |  Frontend  |
| ---- | ---- |
| ![tt2_editor](https://user-images.githubusercontent.com/54422211/173188674-2a347178-3680-41b4-bc51-18e1e1e72317.png) | ![tt2_front](https://user-images.githubusercontent.com/54422211/173188682-2a75ea95-945e-4849-abb3-eaeb48ad0682.png) |

## Twenty Twenty One

| Editor  |  Frontend  |
| ---- | ---- |
| ![tt1_editor](https://user-images.githubusercontent.com/54422211/173188685-0081c052-a9a5-4458-b71e-80508bd9aee5.png) | ![tt1_front](https://user-images.githubusercontent.com/54422211/173188689-82632943-f411-445b-a278-a329bb38def3.png) |

## Twenty Twenty

| Editor  |  Frontend  |
| ---- | ---- |
|![tt0_editor](https://user-images.githubusercontent.com/54422211/173188696-268e7e44-55f4-423c-be80-fd284af46147.png) | ![tt0_front](https://user-images.githubusercontent.com/54422211/173188703-90cd382e-dac5-4a08-9673-df07bb611612.png) |

- WordPress version: 6.1-alpha-53473
- Gutenberg version: 13.4.0

**Comment by t-hamano** [comment] 2022-07-19 11:39
I couldn't be able to reproduce the problem with the latest WordPress and Gutenberg, but just to be sure, I tested again in an environment similar to the one in which you reported the problem.

- WordPress version: 5.6
- Gutenberg version: 9.8.1
- Theme: Twenty Twenty
- Operating system: Windows 11
- Browser: Vivaldi 5.3.2679.68 (Stable channel) (64-bit) 

As a result, I couldn't be able to reproduce the problem.

I noticed in the screenshot attached to the issue that the content is set to center aligned.

![105824613-990ed380-5fe4-11eb-93db-17c55d4ca229](https://user-images.githubusercontent.com/54422211/179740987-27aab064-8a1d-473c-a9fa-26b83add74a4.png)

I think this is the expected result and should work correctly if you remove content justification setting or add numerous buttons.

Therefore, I would like to close this issue.

@nagpai 
If I have misunderstood or you think the issue is not resolved, please don't worry about it and re-open.

**Closed by t-hamano** 2022-07-19 11:39 UTC
Labels: [Block] Buttons
