### ISSUE TITLE
Formatting/HTML code output issue with Post Excerpt "read more" link and next-previous post link block

### ISSUE THREAD

**Issue by randhirexpresstech** [WordPress/gutenberg#38560] opened 2022-02-07 07:18 UTC
### Description

Post Excerpt "read more" link, next or previous post link formatting like bold, italic, new line or inline image are working fine in WordPress block editor but at front-end it display html code like  `<strong><em>Previous</em></strong>`
Please check [gutenberg-12.5.3 read-more link html output issue screen-cast](https://app.usebubbles.com/kvGKqKSQ5SYqGdaysuQXzz/gutenberg-12-5-3-read-more-link-html-output-issue)

### Step-by-step reproduction instructions

1.Go to pages > Add New 
2. Add Query loop block
3. Choose template which includes post excerpt 
4. Add "read more" link text 
5. Give formatting to read more text like bold or italic or add an inline image. It will show formatting and inline image perfectly in editor 
6. Publish the page and view read more link. You will see HTML code there instead of text formatting or inline image 
7. Same happens with next or previous post link  block

### Screenshots, screen recording, code snippet

Please check [gutenberg-12.5.3 read-more link html output issue screen-cast](https://app.usebubbles.com/kvGKqKSQ5SYqGdaysuQXzz/gutenberg-12-5-3-read-more-link-html-output-issue)

### Environment info

WordPress Version 5.9
Gutenberg Plugin Version 12.5.3 
Theme Twenty Twenty Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2022-02-07 09:17
If I disable Gutenberg, I can't reproduce it.
@getdave I believe it is caused by the escaping of the labels and text attributes respectively, as noted and already addressed for some of the blocks.
https://github.com/WordPress/gutenberg/pull/37876/files

**Comment by getdave** [comment] 2022-02-07 09:55
I'm very hopeful that this has been resolved in 

https://github.com/WordPress/gutenberg/pull/38519
https://github.com/WordPress/gutenberg/pull/38517

Gutenberg 12.5.3 should have those fixes. Please feel free to reopen if this does not resolve the Issue.

**Comment by carolinan** [comment] 2022-02-07 10:38
The escaping is still present in https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-excerpt/index.php#L27

**Comment by getdave** [comment] 2022-02-07 11:04
Ok [this PR updates the Post Exceprt block](https://github.com/WordPress/gutenberg/pull/38569/commits/2d273e226a1d47afbee17808fb25027d61eb5e1f) and now allows for rich text but still retains escaping of the attribute which is supplied by the user.

**Comment by randhirexpresstech** [comment] 2022-02-09 13:16
@getdave next and previous post navigation block should also be included for this fix.

**Comment by getdave** [comment] 2022-02-09 15:17
> @getdave next and previous post navigation block should also be included for this fix.

Did you mean Query Navigation Pagination? That was fixed in https://github.com/WordPress/gutenberg/pull/38519

**Comment by randhirexpresstech** [comment] 2022-02-10 05:11
> > @getdave next and previous post navigation block should also be included for this fix.
> 
> Did you mean Query Navigation Pagination? That was fixed in #38519

I didn't mean Query Navigation Pagination. I mean post-navigation-link block. please check the [screen-cast-post-navigation-link](https://app.usebubbles.com/kvGKqKSQ5SYqGdaysuQXzz/gutenberg-12-5-3-read-more-link-html-output-issue?threadId=kXLEHpfdMGv72bk3GKYzV6)

**Comment by getdave** [comment] 2022-02-10 10:49
@randhirexpresstech Great catch. Thank you. I appreciate it. Please find fix in https://github.com/WordPress/gutenberg/pull/38696. It would be much appreciated if you were able to [test and verify](https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/).

**Closed as completed** 2022-02-10 13:07 UTC
Labels: [Type] Regression, [Block] Post Excerpt, [Block] Post Navigation Link

**Comment by randhirexpresstech** [comment] 2022-02-10 13:24
Thanks @getdave 
Issues are fixed in [#38696](https://github.com/WordPress/gutenberg/pull/38696). Here is the [screen-cast of post-navigation-link block html output issue testing ](https://app.usebubbles.com/8TexecccPyUJqTSeGdsCX8/testing-post-navigation-link-block-html-output-issue)
