### ISSUE TITLE
A long link causes a 414 error

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12226] opened 2018-11-22 13:37 UTC
If you use the link editor it auto-suggests pages based on the editor content:

<img width="377" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48906117-6b093400-ee5b-11e8-869f-6a61a0e39472.png">

The check is made using an HTTP GET, with the content appearing in the request URL. If the content is sufficiently large enough it will cause a `414 Request URI too large` error.

It might make sense to limit the request size

**To Reproduce**
1. Edit a link
2. Paste a large amount of text into the link box
3. Note that a 414 error is shown in browser developer tools

**Comment by aduth** [comment] 2019-04-08 19:14
> If the content is sufficiently large enough it will cause a `414 Request URI too large` error.

Is it fair to say this is quite likely a factor dependent upon the server configuration (e.g. [Apache's `LimitRequestLine`](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline), [nginx's `large_client_header_buffers`](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers))?

>It might make sense to limit the request size

How would this be achieved? Is the issue that there's no restriction on the length of the input? In which case, would it be reasonable to impose a limit on the input length?

**Comment by skorasaurus** [comment] 2022-06-06 16:01
When trying to reproduce this, I took a 51000 word input; pasted it in to the link box (within a paragraph block) and received a block error message `This block has encountered an error and cannot be previewed.` ; I think that's a relatively appropriate feedback loop although perhaps the error could be clearer. 

The console displayed a "regexp too big" error. 

What would the next step to resolve this?

**Comment by tellthemachines** [comment] 2023-05-09 06:50
I'm going to go ahead and close this because it seems the problem only occurs with certain server configurations and due to the variability of these there's no solution on the Gutenberg side that will cover all cases.

**Closed by tellthemachines** 2023-05-09 06:50 UTC
Labels: [Type] Enhancement, Needs Technical Feedback

**Comment by ankurparihar** [comment] 2025-01-11 23:35
> > If the content is sufficiently large enough it will cause a `414 Request URI too large` error.
> 
> Is it fair to say this is quite likely a factor dependent upon the server configuration (e.g. [Apache's `LimitRequestLine`](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline), [nginx's `large_client_header_buffers`](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers))?
> 
> > It might make sense to limit the request size
> 
> How would this be achieved? Is the issue that there's no restriction on the length of the input? In which case, would it be reasonable to impose a limit on the input length? What would that limit be, especially if it depends on a user-configurable server setting?

No, this is nothing to do with the servers @aduth. This is a huge miss from WP side.

For any REST api call where we need to send content, we use POST method with the payload in the body, not in query param. WordPress folks here didn't think of the general URL limits browser and servers usually impose and that's why it's breaking.

The right solution is to use body for payload, instead of query-params.
