### ISSUE TITLE
Drag and drop target marker not shown when there is only one paragraph

### ISSUE THREAD

**Issue by msurdi** [WordPress/gutenberg#42365] opened 2022-07-12 11:37 UTC
### Description

When there's only one paragraph, the blue image drop marker is not being shown, which makes it unclear where the image is going to land when dropped.

### Step-by-step reproduction instructions

1. Write a post consisting of just a title and a single line (paragraph) of text
2. Drag and drop an image, try to drop it before or after the paragraph. It's unclear where it is going to land.

### Screenshots, screen recording, code snippet

I'm attaching two videos. In the first one you can see the blue marker is not displayed, thus not making easy to tell where (and if) the image is going to drop.

In the second one you can see it working between paragraphs, but still doesn't show before the first one, or after the last one.

https://user-images.githubusercontent.com/1574407/178481103-003d6085-4371-4c34-aadd-16cc221dd13c.mp4

https://user-images.githubusercontent.com/1574407/178481124-919ba9bc-92e9-4d92-afe9-0760f9b8b281.mp4

### Environment info

Gutenberg: v13.6.0
Theme: Twenty Twenty Two
WordPress version: 6.0-RC4-53438

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment] 2022-07-12 15:20
I was able to replicate this with:

WordPress: 6.0
Gutenberg: 13.6.0
Theme: Twenty Twenty-Two

With Gutenberg **deactivated**, the issue is not present and the blue image drop marker does appear as expected.

**Comment by talldan** [comment] 2022-09-12 01:48
This is fixed as of https://github.com/WordPress/gutenberg/pull/43135.

There's one situation where is still doesn't work, which is the default block appender that appears when first creating a post (the text that says "Type / to choose a block"). There's also https://github.com/WordPress/gutenberg/pull/42722 that may end up being a reasonable way to fix that.

I'll close this and report that problem in another issue (https://github.com/WordPress/gutenberg/issues/44064).

**Closed as completed by talldan** 2022-09-12 01:48 UTC
Labels: [Type] Bug, [Feature] Drag and Drop, [Block] Image
