### ISSUE TITLE
Relative CSS units used in front-end, absolute in block editor

### ISSUE THREAD

**Issue by andrejcremoznik** [WordPress/gutenberg#30734] opened 2021-04-12 09:55 UTC
## Description

From trac: https://core.trac.wordpress.org/ticket/52763

` .has-large-font-size` and `.has-small-font-size` are core CSS classes. On front-end, the font-size uses `em`s while in the editor, the units are in `px`.

If the cascaded `font-size` is `16px`, then it's not a problem but anything else obviously breaks everything if your goal is to visually match front-end and editor.

This is not limited to only these 2 classes.

## Step-by-step reproduction instructions

1. on any theme find the element that wraps the output of `the_content()` and make sure the style `font-size: 16px` is set on that element.
2. Create a new post with a Cover block, give it a background and type some text. The text by default will have the `has-large-font-size` class. Publish the post.
3. Visually compare the Cover block on the front-end with the Cover block in the editor. They will be more or less identical.
4. Now change the `font-size` on the element from step 1 to anything other than `16px` and repeat step 3. The text size will differ. 

## Expected behaviour

Visual consistency between the front-end and editor regardless of cascaded styles.

## Actual behaviour

WordPress core CSS sets values that are hard to override for a consistent editing experience. As a theme developer I don't want to touch anything that comes out of the box because I don't want to deal with 3rd party changes.

## WordPress information
- WordPress version: latest (5.7.0)
- Gutenberg version: WP core
- No plugins
- Any theme

## Device information
- Any device/OS/browser

**Comment by dhruvkb** [comment] 2021-04-14 10:37
Verified that Gutenberg Paragraph blocks have px-based font sizes when the font-size is set to values other than Default.

<img width="1244" alt="Screenshot 2021-04-14 at 4 06 52 PM" src="https://user-images.githubusercontent.com/16580576/114697355-71095380-9d3b-11eb-8c8d-1a0dd97575ca.png">


@andrejcremoznik I've marked this as a high priority issue because it adversely affects theming, which is an essential feature.

**Comment by andrejcremoznik** [comment] 2021-04-14 11:00
@dhruvkb what you are looking at is not an issue.

I didn't look at the code from twentytwentyone but you are able to define font sizes for the styles in the dropdown with the `add_theme_support('editor-font-sizes', [])` function. If you select any style from that dropdown, a theme developer specific `class` will be applied to the element after which it's up to the developer to provide back and front-end styles for that class.

If you type in a custom value, however, then a `style="font-size: Npx"` attribute is added which is also perfectly fine. It's not great if you want the font scalable at different media queries but that cannot be our responsibility. As developers we can only provide responsive font sizes for a limited set of defined presets; the styles registered with `add_theme_support('editor-font-sizes', [])`.

The problem are specifically classes that are in the core and provide `px` units for the editor and `em` units for the same elements on the front end. Which is why I'm specifically talking about `.has-large-font-size` and `.has-small-font-size` and the "Cover block". I did not explore further / can't remember which other cases are affected by this same problem but there is definitely more. Let's focus on just the `.has-large-font-size` for now and fix that.

**Comment by annezazu** [comment] 2023-12-19 16:50
👋🏼 Hey folks! I'm doing a [sweep of high priority labeled issues](https://wordpress.slack.com/archives/C02QB2JS7/p1702996696603749) to ensure the label remains actionable and relevant. As part of this sweep, I'm removing the high priority label from this issue as this issue is quite out of date at this point and it's not clear where this stands. @justintadlock can you check this out and give your sense of it as a themer and sponsored contributor? I want to get this right and would appreciate your sense of this/where things stand today.

**Comment by justintadlock** [comment] 2023-12-19 21:14
From what I'm getting, the CSS custom properties for the core font sizes are currently consistent on both the editor and front end (WordPress 6.4):

```css
--wp--preset--font-size--small: 13px;
--wp--preset--font-size--medium: 20px;
--wp--preset--font-size--large: 36px;
--wp--preset--font-size--x-large: 42px;
```

These CSS custom properties are tied to the `.has-{size}-font-size` classes consistently as well.

I'm going to go ahead and close this. It must have been fixed since this ticket was originally open. If anyone can reproduce the issue in the latest WP or Gutenberg, please reopen.

**Closed as completed by justintadlock** 2023-12-19 21:14 UTC
Labels: [Type] Bug, [Block] Paragraph, CSS Styling
