### ISSUE TITLE
Columns Block: container block overlaps adjacent blocks

### ISSUE THREAD

**Issue by 2one2** [WordPress/gutenberg#7766] opened 2018-07-07 08:25 UTC
As of version 3.2, columns block overlaps other blocks.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/27442964/42408483-9fa86b72-81cd-11e8-9d67-aaec8c9a343a.gif)

Windows 10
Chrome 67 ( 64-bit)

**Comment by designsimply** [comment] 2018-07-11 17:49
@2one2 thank you for the report! I am closing this issue because I believe it will be addressed by https://github.com/WordPress/gutenberg/issues/7694. @aduth can you correct me if that's wrong?

Also noting a related discussion at https://github.com/WordPress/gutenberg/pull/7234#issuecomment-401722360.

**Comment by aduth** [comment] 2018-07-12 20:57
I'm not sure #7694 will strictly address the specific design issues. Might be related to #7365 ? cc @jasmussen

**Comment by designsimply** [comment] 2018-07-16 23:02
Thank you for the feedback! Re-opening and marking as a bug.

**Comment by chrisvanpatten** [comment] 2018-07-17 00:00
I posted some additional screenshots in #7988 which I'll also share here. This was definitely caused by #7365.

![_untitled____ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/42782226-3f59d1d4-8916-11e8-886c-122bf4944615.png)

![_untitled____ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/42782284-710033a4-8916-11e8-97db-bb239f457cff.png)

![kapture 2018-07-16 at 16 38 51](https://user-images.githubusercontent.com/1231306/42782388-c1f65374-8916-11e8-965c-866d6fb5ff97.gif)

**Comment by designsimply** [comment] 2018-07-18 21:47
Noting some helpful steps from 7919 which was marked as a duplicate:

<blockquote>Steps to reproduce the behavior:

1. Add Column Block
1. try to change Block to Full Width</blockquote>

**Comment by designsimply** [comment] 2018-07-19 14:12
Noting that #7920 also mentions not being able to select the full columns block due to overlap.

**Comment by ZebulanStanphill** [comment] 2018-11-13 16:29
Noting that while the Columns block had this issue fixed (I think even before #11620), the Column blocks still have borders that are too tall:
![image](https://user-images.githubusercontent.com/19592990/48427580-af475680-e72e-11e8-8fe0-619cc767c285.png)

**Comment by ilovenataliekay** [comment] 2019-08-13 13:00
I have been searching for a fix to this for a while...... I cannot edit anything inside of columns because I can't GET to them with the overlap.

**Comment by designsimply** [comment] 2019-08-16 21:19
I see that some iterations have been made since this issue was originally opened and I just tested with WordPress 5.2.2 (no plugins) and I am not seeing the same overlap that was originally reported and noted in this issue. ([16s](https://cloudup.com/ck09ed533PJ)) Because of that, I am closing with a note that I am happy to re-open if I've missed anything.

@ilovenataliekay, if you're still having trouble, one potential workaround may be to try using the arrow keys to navigate. It has helped me in some cases.

**Closed** 2019-08-16 21:19 UTC
Labels: [Block] Columns, [Component] Nested / Inner Blocks, [Type] Bug
