### ISSUE TITLE
Embed block/floated embed block audit

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#10440] opened 2018-10-09 14:03 UTC
In #10437 we discovered an issue with embedding Instagram posts. 

The issue was that when we float an embed, we set a minimum and a maximum width on the floated embed, because the embed itself does not necessarily have a specific intrinsic width we can work with. In the case of Instagram, the max-width we set (290px) was smaller than the minimum width supported by Instagram embeds (326px). 

Following this, we should do an audit on every embed block, floated or otherwise, and verify that they are not cropped at any time.

**Comment by gziolo** [comment] 2018-10-16 10:12
@jasmussen is there any more work left? I see one PR merged. Can we move to 4.2?

**Comment by jasmussen** [comment] 2018-10-16 11:33
Yes okay to move. But would be good to do a thorough test sooner rather than later 😅

**Comment by designsimply** [comment] 2018-11-15 23:05
Call to action: audit every embed block, floated or otherwise, and verify that they are not cropped at any time.

1. [ ] Twitter
1. [ ] YouTube
1. [ ] Facebook
1. [ ] Instagram
1. [ ] WordPress
1. [ ] soundCloud
1. [ ] Spotify
1. [ ] Flickr
1. [ ] Vimeo
1. [ ] Animoto
1. [ ] Cloudup
1. [ ] CollegeHumor
1. [ ] Dailymotion
1. [ ] Funny Or Die
1. [ ] Hulu
1. [ ] Imgur
1. [ ] Issuu
1. [ ] Kickstarter
1. [ ] Meetup.com
1. [ ] Mixcloud
1. [ ] Photobucket
1. [ ] Polldaddy
1. [ ] Reddit
1. [ ] ReverbNation
1. [ ] Screencast
1. [ ] Scribd
1. [ ] Slideshare
1. [ ] SmugMug
1. [ ] Speaker Deck
1. [ ] TED
1. [ ] Tumblr
1. [ ] VideoPress
1. [ ] WordPress.tv

The list of core embeds above was pulled from https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/embed/core-embeds.js

**Comment by designsimply** [comment] 2018-11-16 00:56
I tested a WordPress.tv embed of https://wordpress.tv/2018/11/08/matt-mullenweg-qa-at-wordcamp-portland-2018/ using WordPress 4.9.8 and Gutenberg 4.4 `cdeb40986` with Firefox 63.0.1 on macOS 10.13.6. All alignments look good (including wide and full) and the embed doesn't get cropped unexpectedly.

Aside: I noticed that the sizes of right-aligned WordPress.tv embeds don't match in the editor versus the front-end for Twenty Nineteen (but work properly for Twenty Seventeen) so I reported that separately at https://github.com/WordPress/twentynineteen/issues/610

**Comment by jasmussen** [comment] 2018-11-16 08:54
Thanks for the call to action, Sheri! I've done some testing too:

- VideoPress, can confirm it works right in floats left and right, and in vanilla and TwentyNineteen editor styles.
- Tumblr, same, ✔.
- Ted ✔
- Speaker Deck ✔
- Smug Mug — not so great. Technically the _floats_ aspect works fine, which is why I've checked the box on this page, but there are issues with the embeds collapsing, and some of them use Flash, which causes weirdness. I will open a separate ticket for this.
- Slideshare: ✔
- Scribd: does not appear to embed anything at all, neither in Gutenberg or the classic editor. Could use a sanity check on this one. What are we supposed to be able to embed? Tried embedding `https://www.scribd.com/article/392711110/The-Democrats-New-Power-Tools`
- Screencast.com: ✔
- Twitter: ✔
- YouTube: ✔
- Instagram: ✔
- WordPress: ✔
- Soundcloud: ✔

**Comment by jasmussen** [comment] 2018-11-16 09:00
- Spotify: ✔
- Flickr: Appears square and pixelated in the editor but not the frontend. But checking regardless because the floats aspect works fine. 
- Vimeo: ✔
- Kickstarter: ✔

**Comment by arunsathiya** [comment] 2018-11-16 13:54
I tested the ones below, and I don't see any unexpected cropping when the embeds are set to float/aligned to center.

- Reddit ✅ 
- Cloudup ✅ 
- Facebook ✅ - When testing this though, I ran into the same issue as the one here https://github.com/WordPress/gutenberg/issues/11880
- Imgur ✅ 

I also noticed that the `Control` + `Option` + `Z` command to remove the embed blocks don't work on most. I wasn't able to get it working on Reddit, Cloudup and Imgur so far. 

Works fine on Facebook. I can search for the ones where it doesn't work and file a ticket, as required.

**Comment by designsimply** [comment] 2018-11-16 23:06
Tested Meetup.com embeds using WordPress 4.9.8 and Gutenberg 4.4 `7e814e393` with Firefox 63.0.1 on macOS 10.13.6 and found another small Twenty Nineteen nitpick ( https://github.com/WordPress/twentynineteen/issues/624 ) but otherwise it looks good.

**Comment by AtrumGeost** [comment] 2018-11-17 22:41
Did some testing :D

✅  Twitter
✅  YouTube
✅  Facebook
✅  Instagram
✅  WordPress
✅  SoundCloud
✅  Spotify
✅  Flickr
✅  Vimeo
👾  Animoto: 
There's an extra space below the video http://cld.wthms.co/VdxgIP

URL: https://animoto.com/play/FQ12uazXH10WDez7vsfh2g

✅  Cloudup
👾  CollegeHumor:
Got an empty space.
http://cld.wthms.co/RqmGwc

URL: http://www.collegehumor.com/video/40004082/the-girl-with-a-birthday-month
✅  Dailymotion
👾  Funny Or Die:
Got this message: "Sorry, we could not embed that content."
http://cld.wthms.co/mAOqGR

URL: https://www.funnyordie.com/2018/11/16/18097374/depression-olympics-sketch-parody-al-madrigal
👾  Hulu:
Got an error since I'm outside US: http://cld.wthms.co/qsszHP
And an error when I tried with VPN: http://cld.wthms.co/JGZlQi

URL: https://www.hulu.com/watch/771496
✅  Imgur
✅  Issuu
👾  Kickstarter
Empty space on editor: http://cld.wthms.co/05Me72
Looks odd: http://cld.wthms.co/rr2jCJ

URL: https://www.kickstarter.com/projects/antsylabs/pixl-a-magnetic-building-system
✅  Meetup.com
✅  Mixcloud
👾  Photobucket
Didn't work. Tried two URLS. They gave me this error: "Sorry, we could not embed that content."


URL 1: http://i1044.photobucket.com/albums/b444/zzztttzzz/20181117_084341_zpswlblzpk2.jpg
URL 2: http://photobucket.com/gallery/user/zzztttzzz/media/bWVkaWFJZDoxOTY3ODY4MjE=/?ref=


✅  Polldaddy (Crowdsignal)
✅  Reddit
👾  ReverbNation
Big space below embed block: http://cld.wthms.co/y7bdkf
 
URL: https://www.reverbnation.com/sammybrue

👾  Screencast
Appears a black space when aligning the image:
Centered: http://cld.wthms.co/bV381m
Aligned: http://cld.wthms.co/ldsG38

URL: http://www.screencast.com/t/9QpXpRrzf

✅  Scribd
✅ Slideshare
👾  SmugMug
Works but doesn't show a preview: http://cld.wthms.co/PXm1NZ
I'm guessing it is because it uses Flash.

URL: https://foaloce.smugmug.com/Travels/Italy/Toscana-april-2012/

👾  Speaker Deck
It looks cropped: http://cld.wthms.co/HBfKQg

URL: https://speakerdeck.com/maltzj/code-reviewing-like-a-champion

✅  TED
✅  Tumblr
✅  VideoPress
✅  WordPress.tv

WordPress 4.9.8 running Twenty Seventeen theme

**Comment by notnownikki** [comment] 2018-11-22 10:53
funnyordie no longer supports oembed, we should remove the block and remove the provider from core WP.

**Comment by notnownikki** [comment] 2018-11-22 10:57
> SmugMug Works but doesn't show a preview: http://cld.wthms.co/PXm1NZ I'm guessing it is because it uses Flash.

Confirmed, `Failed to load 'https://cdn.smugmug.com/ria/ShizamSlides-2015060701.swf' as a plugin, because the frame into which the plugin is loading is sandboxed.` in the console, so this might have to go on the list of domains we can't show previews for.

**Comment by notnownikki** [comment] 2018-11-22 10:59
> Photobucket Didn't work. Tried two URLS. They gave me this error: "Sorry, we could not embed that content."

Photobucket no longer supports oembed. Another one we should remove from the blocks and from core code.

**Comment by jasmussen** [comment] 2018-11-29 13:20
Thank you all so much for testing here.

This audit has revealed a number of issues, some that were present even in 4.9. 

The initial issue was related to how the embeds work with regards to floats, though, and it seems this aspect has worked well. For that reason I'm tempted to close this ticket in favor of the individual issues that have been surfaced as a result of this audit. 

But for now atleast, I'm moving it out of the 5.0 milestone as the audit has technically been completed.

**Comment by youknowriad** [comment] 2019-01-26 14:57
This served its purpose I think. Let's close and open individual issues.

**Closed by youknowriad** 2019-01-26 14:57 UTC
Labels: Good First Issue, Needs Testing, [Block] Embed
