### ISSUE TITLE
Child inserter button is missing for Buttons and Social Icons blocks on Chrome

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#22780] opened 2020-05-31 13:57 UTC
When you add a Buttons or Social Icons blocks, the child (+) inserter button is missing when using Chrome. Therefore, it's impossible to add a second button or another social icon.

The bug only occurs on Chrome. Working fine on Safari, Firefox, Edge...

- Tested with WordPress 5.2.1 and Gutenberg 8.2.1
- Tested with the following themes: Twenty Twenty, Twenty Nineteen, Twenty Seventeen
- Browser: Chrome latest version on Windows and Mac

**Comment by edmundcwm** [comment] 2020-06-03 00:30
Hmm seems to work fine for me on Chrome (v83)
![Screenshot 2020-06-03 at 8 27 33 AM](https://user-images.githubusercontent.com/13222067/83582470-2728dc00-a574-11ea-8189-65339963907d.png)

Did u try deactivating any plugins u have that might be causing some conflict? Could you post a screenshot of it as well?

**Comment by dianeco** [comment] 2020-06-03 07:03
Hi @edmundcwm,

I've tested with zero plugins installed on a fresh WP install. I've just found that it's working fine on Chrome if I browse on Incognito mode. But on normal mode, even if I remove all my Chrome extensions, clear the cache and hard reload,  the (+) button isn't visible.  Two weeks ago, it was working fine on both my computers (PC and Mac) on Chrome normal mode.

**Comment by talldan** [comment] 2020-06-03 09:20
I also can't reproduce the issue in Chrome: 
<img width="250" alt="Screenshot 2020-06-03 at 5 19 48 pm" src="https://user-images.githubusercontent.com/677833/83619456-7c89db00-a5be-11ea-926a-cad3cc36ee8b.png">

The block does need to be selected for the button to appear.

**Comment by talldan** [comment] 2020-08-14 10:20
I still haven't been able to reproduce an issue, and there have been no other reports, so closing this issue.

**Closed by talldan** 2020-08-14 10:20 UTC
Labels: [Block] Buttons, [Block] Social, [Status] Needs More Info
