### ISSUE TITLE
Headings: Width discrepancy between editor and preview when nested in cover block

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#25936] opened 2020-10-08 00:56 UTC
**To reproduce**
1. Create a new post or a page. Add a cover block with an image background, set the cover block to Full width.
2. Inside the cover block add a headings block.
3. For comparison, add a paragraph block below the heading.
4. Notice the different width and alignment between the two.
5. Save draft and go preview the post/page. Notice the paragraph and heading are both the same width.

A similar thing happens when headings block is nested in the group block set to wide or full width.

**Expected behavior**
For the editor to match the preview.

**Screenshots**
Editor view:
![image](https://user-images.githubusercontent.com/4550351/95402948-a97b3f80-095c-11eb-98db-2f86a573a541.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/95402974-b7c95b80-095c-11eb-98ac-ad9ce5130a5f.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1, Gutenberg default
- Theme: TwentyTwenty

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Chrome 85.0

**Comment by glendaviesnz** [comment] 2020-10-08 03:27
Duplicate of https://github.com/WordPress/gutenberg/issues/25937

**Closed by glendaviesnz** 2020-10-08 03:27 UTC
