### ISSUE TITLE
ACF, Meta Not Showing. Classic Editor failing to load on localhost as well.

### ISSUE THREAD

**Issue by brograhamer** [WordPress/gutenberg#2631] opened 2017-08-31 18:05 UTC
## Issue Overview

I'm unable to see any ACF / Meta Boxes in the latest Gutenberg 1.0 release (or any prior).

## Steps to Reproduce (for bugs)

1. Install Yoast and ACF (Advanced Custom Fields)
2. Create a basic text input called and assign it to show for all Posts.
3. Use Gutenberg to edit a Post.
4. Unable to see / find the Yoast or ACT text input meta anywhere.

## Expected Behavior

I've ready every thread / issue on Gutenberg and it's very unclear for some of us. It seems like there is currently support for meta boxes / ACF but I'm not seeing it. Am I crazy or is it not implemented yet?

## Current Behavior

Default Gutenberg editor, no meta boxes aside from the block editors. Unsure how to see my Yoast or ACF fields.

## Possible Solution

Unsure. See [#952](https://github.com/WordPress/gutenberg/issues/952)

## Related Issues and/or PRs

See [#952](https://github.com/WordPress/gutenberg/issues/952)

## Comments

We thrive on Custom Post Types and extending Posts / Pages through ACF. For some of our Custom Post Types we hide the Content completely and create our own "editor" using ACF and it's tab feature. I love what Gutenberg is but I see NO clear answer as to how this will be implemented so far. Yet, I'm seeing some people say that Meta fields exist ... ?

I am running the latest Vagrant, VirtualBox, VVV setup on localhost ... could that be my problem? If so, that's silly, and should definitely be a separate ticket. 

Lastly, because I am on localhost the "classic editor" fails to load. Something to look into.

**Comment by aduth** [comment] 2017-08-31 18:24
>It seems like there is currently support for meta boxes / ACF but I'm not seeing it.

Metaboxes are not yet supported, and are tracked at #952, with pending (but incomplete) explorations at #2251 and #2583. To that effect, this issue duplicates #952.

I'm not familiar with issues of loading the current editor in `localhost`, and there is very little that could impact the existing editor. Could you check to see if the issue is still present if the Gutenberg plugin is disabled?

**Comment by karmatosed** [comment] 2017-09-24 12:35
As metaboxes are being worked on, lets close this right now. We can always come back to this.

**Closed by karmatosed** 2017-09-24 12:35 UTC
Labels: [Status] Needs More Info
