### ISSUE TITLE
Paste handler strips white space characters

### ISSUE THREAD

**Issue by davidyeiser** [WordPress/gutenberg#15649] opened 2019-05-15 11:39 UTC
It seems that special characters are stripped from the paragraph block. For example, if you try to paste a thin space (`&#8201;`) nothing appears. 

**To reproduce**
1. Go here and copy a thin space character: http://www.elizabethcastro.com/html/extras/entities.html#punct
2. Try to paste the thin space in a paragraph block in Gutenberg editor.

**Expected behavior**
The thin space would appear in the editor as well as render on the website page.

**Local env.**
- MacOS Sierra 10.12.6
- Chrome 74.0.3729.131 (Official Build) (64-bit)
- WordPress 5.2

**Comment by ellatrix** [comment] 2019-06-27 11:17
Sounds like a paste issue. Relabelling.

**Comment by ellatrix** [comment] 2019-06-27 11:18
@davidyeiser is this limited to white space characters?

**Comment by davidyeiser** [comment] 2019-07-09 21:43
It seems to be. I tested with these: ¶ ™ § ® — ÷ ∩ ∴ ℜ And they all worked fine. However testing with a thin space, no break space, em space and en space and none of those would paste.

**Comment by ellatrix** [comment] 2019-12-10 14:55
@davidyeiser Sorry for the late reply. It seems to work fine for me. Does it paste correctly in Google Docs and [TinyMCE](https://www.tiny.cloud)?

**Comment by noisysocks** [comment] 2020-05-28 05:28
To reproduce this reliably:

1. Copy a thin space from http://www.elizabethcastro.com/html/extras/entities.html#punct.
2. Paste into a plain text Notepad / TextEdit file.
3. Copy the thin space from Notepad / TextEdit.
4. Paste into Gutenberg. Note that nothing happens.

**Comment by pento** [comment] 2020-08-24 01:29
This is likely caused by one of the several points in `raw-handling` that runs `.trim()` on text node content. For a simple test case, paste `"\u2009".trim()` (thin space is Unicode character number 2009) in your browser console, showing that the space is trimmed.

While there's obvious value in trimming out unnecessary whitespace characters, the current behaviour feels a little overly aggressive. There are a couple of cases I've noticed recently that fall into this same category:

- Pasting text from any source that includes a space at the end, the space is is trimmed.
- In the block editor, set up an Annotation that highlights a space character in a paragraph block. Select the text (including the Annotation), copy, and paste it to a new block.

I suspect there are additional quirks of this nature which would be addressed by making the paste handler a little less aggressive with it's space trimming.

**Comment by gwwar** [comment] 2021-03-04 20:20
I see a whitespace inserted, but when I look at code view, there's an editor crash. 

https://user-images.githubusercontent.com/1270189/110024497-14019300-7ce3-11eb-91bc-898d6f8ff6c8.mp4

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (http://wordpress.local/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=c813087cbcf153f23e582a00fae7a578:383:9)
    at _slicedToArray (http://wordpress.local/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=c813087cbcf153f23e582a00fae7a578:528:418)
    at ActionItemSlot (http://wordpress.local/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=c813087cbcf153f23e582a00fae7a578:17351:101)
    at renderWithHooks (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:14938:20)
    at mountIndeterminateComponent (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:17617:15)
    at beginWork (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:18731:18)
    at HTMLUnknownElement.callCallback (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:182:16)
    at Object.invokeGuardedCallbackDev (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:231:18)
    at invokeGuardedCallback (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:286:33)
    at beginWork$1 (http://wordpress.local/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:23338:9)
```

**Comment by maddisondesigns** [comment] 2021-03-09 08:17
This is still happening with Gutenberg 10.1.1. If I copy some text with a space on the end, the space gets stripped out when I paste it. When I copy some text, I expect the exact same text to be pasted. Nothing should be stripped.


https://user-images.githubusercontent.com/2078245/110439485-a357dd80-810b-11eb-8d81-5cfabf2e3723.mp4

**Comment by ellatrix** [comment] 2021-03-09 11:16
I rebased #28077.

**Closed** 2021-03-17 10:03 UTC
Labels: [Feature] Raw Handling, [Status] In Progress, [Type] Bug
