### ISSUE TITLE
Cover block: focal point not working when 'Repeated background' is toggled on

### ISSUE THREAD

**Issue by albarin** [WordPress/gutenberg#40809] opened 2022-05-04 09:08 UTC
### Description

The focal point settings are not applied to the image when the `Repeated background` option is enabled.

### Step-by-step reproduction instructions

1. Create a new page and add a `Cover` block with an image.
2. Toggle on the `Repeated background` option.
3. Change the focal point settings and publish the page.
4. Go to the frontend and see that the focal point settings are not applied to the image.
5. Go back to edit the page, refresh, and see that the focal point settings are saved but not applied to the image.

### Screenshots, screen recording, code snippet

https://d.pr/v/NNeZLM

### Environment info

WordPress 5.9.3
Gutenberg 13.1.0
Twenty Twenty-Two 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by matiasbenedetto** [comment] 2022-05-27 19:46
:wave: I'm not able to reproduce this issue using the latest Gutenberg trunk version, I think it was already fixed with the latest fixes to the Cover Block.

**Comment by amustaque97** [comment] 2022-05-28 19:24
> 👋 I'm not able to reproduce this issue using the latest Gutenberg trunk version, I think it was already fixed with the latest fixes to the Cover Block.

I'm still able to reproduce the issue using latest Gutenberg trunk version.
Sharing my screencast.


https://user-images.githubusercontent.com/21127788/170840038-bbe95435-83f1-4961-90ac-18cca9fccc8b.mov

**Comment by draganescu** [comment] 2022-06-01 09:55
I am unable to reproduce this on `trunk`:



https://user-images.githubusercontent.com/107534/171378128-9eae2481-91c2-4adb-819a-0b5abbe1fbf1.mp4

**Comment by amustaque97** [comment] 2022-06-01 18:46
Volla 😃 , after a bit of cleanup (`git clean -xfd`) and installing everything fresh. I'm not seeing this issue on `trunk` branch. Probably we can close this issue.

**Comment by draganescu** [comment] 2022-06-02 10:05
👏🏻

**Closed as completed by draganescu** 2022-06-02 10:05 UTC
Labels: Needs Testing, [Block] Cover
