### ISSUE TITLE
E2E: Settings sidebar test sometimes fails

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#30580] opened 2021-04-07 17:36 UTC
Noticed this one failing today on an unrelated change. @david-szabo97 or @ntsekouras would it be possible to investigate?

```
npm run test-e2e -- --puppeteer-interactive specs/experiments/settings-sidebar.test.js
```

<img width="841" alt="Screen Shot 2021-04-07 at 8 35 49 AM" src="https://user-images.githubusercontent.com/1270189/113909548-a5ee3700-978c-11eb-950c-a9d9d9ba0a9a.png">

**Comment by ntsekouras** [comment] 2021-04-09 11:40
Hey @gwwar 👋 - It seems like a local setup problem with the `500` error, indicating that site editor didn't load? 🤔 

For me it works as expected in trunk with both interactive and non mode.

**Comment by gwwar** [comment] 2021-04-09 15:05
I took a screenshot of a failing CI build in trunk, re-running the job cleared it up, but wanted to document the flakeyness

**Comment by david-szabo97** [comment] 2021-04-12 10:03
Any other instances that we can investigate? I ran the test file locally like 6 times and never failed. The 500 error is indeed related. Maybe there was a change that broke the site editor, or there was a change on WordPress develop branch that broke it a short time. I don't think this is related to the test file you mention here, it just happened to fail there for some reason because the site editor failed to load.

**Comment by ntsekouras** [comment] 2021-04-12 10:26
I'm closing this for now as it can't be reproduced and seems related to some `site editor` failure to load. Please feel free to reopen if needed.

**Closed as completed by ntsekouras** 2021-04-12 10:26 UTC
Labels: [Package] E2E Tests
