### ISSUE TITLE
Preload menu REST API requests on new navigation editor. 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34298] opened 2021-08-25 13:21 UTC
## What problem does this address?
When the new navigation page, it loads a number of API are requested to load this page. See screenshot. 

![Screenshot 2021-08-25 at 14 15 17](https://user-images.githubusercontent.com/237508/130797213-557ca748-d5f8-47db-9cd7-05410c178b81.png)

This means that page waits until the page and the request to these API return, before a meaning UX can shown to a user. 

## What is your proposed solution?

Preload REST API requests, that are needed to render the page. WordPress allows for preloading of rest api see these examples.

[Gutenberg post editor](https://github.com/WordPress/wordpress-develop/blob/c550a592b9f2ffb6262ad6de07bc645095a77e98/src/wp-admin/edit-form-blocks.php#L52-L74)
[Gutenberg widget editor](https://github.com/WordPress/wordpress-develop/blob/7368e869942a68cd731662d5f1d03672e5317778/src/wp-admin/widgets-form-blocks.php#L20-L25)

There is even a function found in core to help this [block_editor_rest_api_preload](https://developer.wordpress.org/reference/functions/block_editor_rest_api_preload/)

**Comment by spacedmonkey** [comment] 2021-08-25 13:30
As a start, I would preload 
- wp/v2/types
- __experimental/menus?context=edit&per_page=100
- __experimental/menu-locations

**Comment by spacedmonkey** [comment] 2021-08-25 15:54
I would also like to preload the currently selected menu when the page loads, but there is no easy way to know what menu is selected as is used in local storage.

**Comment by draganescu** [comment] 2021-08-26 12:06
Is this a duplicate of  #24642 ?

**Closed as completed** 2021-08-30 11:59 UTC
Labels: [Status] In Progress
