### ISSUE TITLE
Cannot edit blocks below group block

### ISSUE THREAD

**Issue by amandablum** [WordPress/gutenberg#17469] opened 2019-09-17 23:53 UTC
**Describe the bug**
When you add a group block to your content, the block directly below that block will not allow you to select any of the tools from the editing tools (alignment, deletion, etc). This only applies to the blocks directly below the group. 

**To reproduce**
1. Insert a group block. Add any components to it. Add another block below, doesn't matter what kind. 
2. Click on the 2nd block to activate the editing tools menu above the block. 
3. Try to click on any of the tools for the second block. 
4. It will result in selecting the 1st block instead, activating the first block's editing menu. 

**Expected behavior**
Expected to be able to use the editing tools on the second block 

**Screenshots**
![1](https://user-images.githubusercontent.com/2366499/65087648-6625eb80-d96b-11e9-8621-0c3c9c1acf1a.png)
(if you try to click on the menu shown here, it will just activate the group block above. 

**Desktop (please complete the following information):**
 - Win 10 
 - Chrome 76.0.3809.132

**Additional context**
- WP 5.2.3, Gutenberg 6.4.0

**Comment by talldan** [comment] 2019-09-24 02:14
@amandablum Thanks for reporting this. At first I wasn't able to reproduce this, but then when using the Media & Text as the second block it always happens. I noticed it's also always an issue when the second block has an alignment.

I'll raise the priority of this, as it seems like an important one to fix.

**Comment by talldan** [comment] 2019-09-24 07:38
Actually, on further testing I can't reproduce this using v6.5.0 of the plugin. It seems like it's already been fixed.

@amandablum are you able to test using 6.5 and report back on if you still have the issue? Thanks.

**Comment by carolinan** [comment] 2020-04-02 06:00
Hi
We have tested this during our triage today and we are unable to reproduce it, so we are closing this issue.

**Closed by carolinan** 2020-04-02 06:00 UTC
Labels: Needs Testing, [Block] Group, [Type] Bug
