### ISSUE TITLE
Navigation block: text color not appearing in the editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#41146] opened 2022-05-19 03:30 UTC
### Description

When assigning a text color to the main navigation block using TT2, the color isn't shown properly in the editor but does appear correctly when viewed on the front end of the site. This occurs with 6.0 RC3. cc @ndiego as a heads up, @getdave to perhaps help address, and @scruffian for possibility of this being a TT2 issue. 

### Step-by-step reproduction instructions

1. Add a navigation block.
2. Select a text color.
3. Notice no changes in editor.
4. Publish changes.
5. View frontend of the site and see changes there.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/169198201-0897ec69-5b83-4584-92cf-dddb746a9dff.mov

### Environment info

- WordPress 6.0 RC 3
- TT2
- No GB installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-05-19 03:30
Adding to 6.0.1 conservatively. Would love to see this addressed for RC4 planned for this Friday but I recognize that that's a tight timeline :)

**Comment by carolinan** [comment] 2022-05-19 04:01
[This problem](https://github.com/WordPress/gutenberg/issues/40908) seems to be escalating

**Comment by getdave** [comment] 2022-05-20 10:57
https://user-images.githubusercontent.com/444434/169513995-48ae259a-0f3e-4663-b1bd-616d52de7898.mov

Tested and confirmed. Seems to be another inline style overriding this text color style 🤔 

Doesn't happen on Archeo Theme though. 

<img width="1277" alt="Screen Shot 2022-05-20 at 11 59 03" src="https://user-images.githubusercontent.com/444434/169514431-711e0be6-684d-4ce9-867e-a0fd22ce421b.png">

I wonder if there's a specific Theme JSON setting that's causing the cascade to be overriden. Certainly the style that's overriding the text color seems to come from Global Styles.

Doesn't happen in the Post Editor either. Only the Site Editor which makes me think Global Styles:

https://user-images.githubusercontent.com/444434/169515115-86e20deb-74a1-4a3d-b9d5-3cfc4bcab5ce.mov

**Comment by getdave** [comment] 2022-05-20 11:09
Some more debugging reveals the culprit to be the text color set on a wrapper Group block whose styles are cascading on to every `a` in it's container. 

https://user-images.githubusercontent.com/444434/169515750-683e0df9-f085-4ab5-9c43-1a64ba4c3c3f.mov

You can see this at

https://github.com/WordPress/twentytwentytwo/blob/27054dbcb95f5d72cd943a0f3318c3ad97599f85/parts/header-small-dark.html#L1

```
<!-- wp:group {"align":"full","style":{"elements":{"link":{"color":{"text":"var:preset|color|background"}}},
```

The cascade is how CSS works so this would seem to be legit. However, I'd expect the Nav block CSS to be more specific.

The temporary "fix" would be to have a specific style on the Navigation block a or to remove the styles on the wrapping Group.

We should look into why the Nav block CSS isn't more specific and/or overiding this. My instinct is that the `a` on the Nav are set to inherit their color from the parent Nav block. Therefore the Global Styles selector will override this.

**Comment by getdave** [comment] 2022-05-23 15:49
@annezazu @carolinan A few contributors have discussed this and it looks like the problem is due to CSS specificity introduced by the fact that the Nav block has (for historical and legitimate reasons) a custom implementation of the color picking system.

We could [extend this system to affect a patch](https://github.com/WordPress/gutenberg/pull/41199) but as [a few folks have noted](https://github.com/WordPress/gutenberg/pull/41199#pullrequestreview-981904954) would be compounding existing technical debt which will have to be "undone" later.

Ideally we would take time to do a wider refactor which would:

- extend Global Styles to allow the ability to define custom color properties to be handed by Globsl Styles (i.e. not just text, link and background).
- refactor the Nav block to use the updated system
- fix any remaining specificity issues

I believe this issue "only" affects the Editor and not the front end. How impactful do you feel this bug is? If it's causing real pain and cannot be "managed" then we might need to go for the fix and try to undo the tech debt later. If not then we could take our time and get a solid fix in place which should also protect the block for further regressions as it would then be coupled to the wider system.

No decisions have been made at this point and so I'd really appreciate your feedback should you be able to offer it 🙇‍♂️

**Comment by annezazu** [comment] 2022-05-25 21:16
@getdave thanks for summarizing the discussion and laying out the option. This feels like a very common UX bug to resolve that would impact the basics of using the navigation block (updating the colors of the links). My vote is to have an interim fix for 6.0.x and then figure out a longer term solution for 6.1 that is in line with what you described, which should work well since the Global Styles Engine work will continue to mature. cc @priethor for thoughts too :)

**Comment by getdave** [comment] 2022-05-26 09:00
Thanks @annezazu 👍 

Also @draganescu and @scruffian do you have any thoughts about short term vs longer term fix?

**Comment by scruffian** [comment] 2022-05-26 10:13
My concern with a short term fix is that it will make the long term fix harder, as we'll have to undo the mess that it will create.

**Comment by priethor** [comment] 2022-05-27 17:57
I'm also concerned about adding a lot of technical debt to fix this. I would evaluate a short-term fix for 6.0.1 but would only proceed if the effort required is not too big and there is confidence the patch doesn't compromise the long-term solution.

**Comment by getdave** [comment] 2022-07-01 11:10
**Update**: myself and @scruffian took some time to pair on the problem here. This is what we found:

---

- On trunk the Nav block uses non-standards text color and background controls. 
- There is now a standards based Block Supports for Text, Background and Link colors which it should be using.

## The Bug:

- The styles for the Nav block [tell the links inside it to inherit their color from the parent element](https://github.com/WordPress/gutenberg/blob/85eb2b68cb442b8853d09bc28f5a7bf39b899e42/packages/block-library/src/navigation/block.json#L118-L126) (color: inherit ). 
- In the case that a parent block specifies a link color (e.g. a containing Group block), Navigation links will use that block's Link color setting rather than the Text color set on the Navigation block itself. 
- The Nav block is relying on implicit CSS inheritance to set the a  (link) color based on the value of Text Color .
- Moreover, because it uses non-standard controls the Block Supports output has no knowledge of the CSS that is being output.
- The link color CSS rules from parent blocks are also output later in the DOM and thus override the custom rules in the Nav block (even though the specificity is identical).
- The Nav block should have a specific color setting for Link color in order that the CSS ordering will output in the correct order thereby allowing the Nav block specific styles for Links to win out.
- This happens only in the Editor. 
- The block is relying on hardcoded, implicit CSS rules to set the color of anchor links.



## Solution

- We need to make the Nav block have a Link specific color control to set the a color of the block explicitly (as opposed to relying on hardcoded inheritance).
- Enabling color block supports for Text, Background and Link allows us to do this. 
- Setting the Link color successfully overwrites any link color setting that is being "inherited" from parent blocks - this works!
- The problem:
	- Nav block currently uses custom color controls not standard Block Supports.
	- A user's current expectation is that setting Text color on the block will modify the color of the Links in the Navigation block - indeed this does happen on the front end. (Q: why does that work on the front end?)
	- We need to migrate any existing Text color selections to the new Link color setting. We could do this in a deprecation on the block.
	- We should consider hiding the Text color control because it adds confusion. This could be progressively disclosed.


## Summary

We believe we've come up with a solution which should solve. It will have some compromises in the short term but these would mostly be manifested in the block controls' presentation.

PR to follow.

**Comment by getdave** [comment] 2022-10-05 11:28
I'm going to suggest we close this one out as I believe it was fixed in https://github.com/WordPress/gutenberg/pull/44578 (cc @jasmussen).

However the Navigation block still does not use the standardised color controls from Block Supports. It's a custom implementation. 

If it's desirable and necessary to do that then we should consider opening a new issue to track that requirement.

For a summary of the original bug here and the status of the problem you can [watch my video](https://d.pr/v/9meXIc/6ttPL3NB8L).

**Closed as completed by getdave** 2022-10-05 11:28 UTC
Labels: [Type] Bug, [Block] Navigation, [Feature] Design Tools
