### ISSUE TITLE
Search Block: Button Inside setting not working in classic themes

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#44675] opened 2022-10-04 17:34 UTC
### Description

When using a classic theme such as **Twenty Seventeen**, setting the Search block's button position to `button inside` doesn't result in the button inside the search field - it just adds a border to the block.

### Step-by-step reproduction instructions

1. Choose a classic theme such as Twenty Seventeen
2. In a new page or post, add a Search Block
3. Change button position and choose "button inside"

### Screenshots, screen recording, code snippet

**Editor**
![Screen Capture on 2022-10-04 at 10-30-51](https://user-images.githubusercontent.com/27249804/193887137-d68a8c8b-4bd5-44d7-be6c-bff079d779f2.gif)

**Live Site**
![Markup on 2022-10-04 at 10:32:30](https://user-images.githubusercontent.com/27249804/193887249-2b3797fe-e6a8-4710-a61f-f831fb2cf2fa.png)

### Environment info

- WP 6.0.2
- Gutenberg 14.2.0
- Theme: Twenty Seventeen
- Also reported here: https://github.com/Automattic/wp-calypso/issues/68502 on the following themes: 
     - *Sequential, Edin, Twenty Seventeen, Dara, Argent, Hemingway Rewritten, Karuna*

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment] 2022-10-05 07:55
@cuemarie Is it only a Twenty Seventeen issue?

If so I think it'd be good to check core trac (WordPress core's bug tracker) for any previous reports of the issue:
https://core.trac.wordpress.org/search?q=twenty+seventeen&noquickjump=1&ticket=on

If you can't find any a new issue can be made in trac. The code for Twenty Seventeen resides in WordPress core, so it would only be possible to fix this as part of a trac ticket rather than a gutenberg issue.

**Comment by jerrysarcastic** [comment] 2022-10-05 18:00
In my tests I was able to replicate this issue when using Sequential, Edin, Twenty Seventeen, Dara, Argent, Hemingway Rewritten. Other classic themes may be affected as well.

**Comment by cuemarie** [comment] 2022-10-06 00:58
Hey @talldan ! Thanks for the ping. I saw the same issue present on **Karuna** in triaging, and as @jerrysarcastic noted, the issue also presented on many other classic themes. 

Apologies for any confusion - I just only included **Twenty Seventeen** as the example in my notes. Hope that helps!

**Comment by cuemarie** [comment] 2022-10-26 02:14
@talldan Let me know if you need any other details. The issue was replicated on the following:

- Twenty Seventeen
- Karuna
- Sequential
- Edin
- Dara
- Argent
- Hemingway Rewritten

**Comment by talldan** [comment] 2022-10-26 07:28
@cuemarie I'm still unsure what the issue is with 'button inside', but I can see that the search block's button styles look wrong in many classic themes regardless of whether 'button inside' is set. Button block styles also seem incorrect.

Some of these might be bugs in the themes as the problems seem to differ wildly (Twenty Twenty is completely wrong, while Twenty Twenty One has only a few issues).

I can see there was a recent attempt to fix classic theme styles in #42012, but I personally don't know much about this area of work. (cc @scruffian @draganescu)

**Comment by ddryo** [comment] 2022-10-29 03:09
I am also having this problem.

![CleanShot 2022-10-29 at 12 07 54](https://user-images.githubusercontent.com/31400297/198796256-7f9e872b-382b-4764-ade3-f18ead2590a4.gif)

**Comment by annezazu** [comment] 2024-09-10 20:44
I can still replicate this with 6.6.1 and GB 19.1 using the Twenty Seventeen theme.

**Comment by t-hamano** [comment] 2024-09-11 01:24
I believe this is an issue that should be addressed on the theme side.

The Search block provides [minimal styling for the Button Inside](https://github.com/WordPress/gutenberg/blob/98c65eaf268b86175d51cbb91c35e4111a7950ef/packages/block-library/src/search/style.scss#L112-L131). For example, if you use this block in a classic theme that has no styling, it will appear as follows:

![image](https://github.com/user-attachments/assets/dc2a72e9-4265-46b4-b8a8-bcdfd367b46f)

If you feel that the Button Inside setting is not working correctly in a particular theme, it may be that the theme does not provide styling for the Button Inside setting, or that the default styling is unintentionally affecting the Button Inside styles.

**Comment by annezazu** [comment] 2024-09-11 16:02
Let's close this out then as it does seem to be theme specific :)

**Closed as completed by annezazu** 2024-09-11 16:02 UTC
Labels: [Type] Bug, Backwards Compatibility, [Block] Buttons, [Block] Search
