### ISSUE TITLE
Active border around movers on blocks not equal

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25774] opened 2020-10-01 13:52 UTC
I noticed in the widget screen this, however, it seems to be also in the editor, the clicked state of the movers is a little unequal as you can see here:

![image](https://user-images.githubusercontent.com/253067/94817292-c6f85880-03f4-11eb-801d-cdf308047744.png)

My suggestion would be to reduce the width to the right to bring it inline. This could look like this:

![image](https://user-images.githubusercontent.com/253067/94817936-75040280-03f5-11eb-989e-ee2443048287.png)

However, that was by removing the 'padding-right' that was set on this element and I am not sure that's a scalable fix, so it will need exploring more. I do understand the need to keep the hit space large so that needs to be done in any solution.

I would love feedback and insights on this.

**Comment by paaljoachim** [comment] 2021-02-11 22:27
@jasmussen Joen this looks like a quick fix.

**Comment by jasmussen** [comment] 2021-02-12 08:32
Great ticket, however I think it's actually working as intended, because we intentionally make the clickable area as large as possible to make it easier to hit. We could make it smaller horizontally, but the only benefit would be the visual when the button is focused.

I tend to think that the meta chip on the left — block type indicator, drag handle, mover — is in an acceptable place, but can still be improved a great deal. Specifically it is inconsistent with how it works when the top toolbar mode is enabled, and it's also rather wide and big. Both of these suggest that we can take a separate holistic effort to look at how to keep what's good about the current, but realign the metrics to address the discrepancies. When we have time to do that, I promise I will remember Tammie's good advice here. In the mean time, I'm actually going to close this one!

**Closed by jasmussen** 2021-02-12 08:32 UTC
Labels: General Interface, Needs Design Feedback
