### ISSUE TITLE
Paragraph block: overlapping popover menus for link / inline text color

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32221] opened 2021-05-25 19:29 UTC
Hi all, this bug was spotted in #31958 while testing the Widgets Customizer editor but looks like this is happening in the post editor as well. 

If you have highlighted text that includes a link and try to change the inline color settings from the Paragraph block toolbar, it's possible to open both popovers at once that overlap each other:

https://user-images.githubusercontent.com/77359364/119548225-fa14a100-bd63-11eb-8b52-ca9968e6b271.mov

Would it be possible to detect when one popover is already open and close the existing one before opening the new one?

**Comment by Thelmachido** [comment] 2022-08-17 09:26
I am not able to reproduce this, as shown in the screenshot below.  I will be closing this issue for now. 

<img width="645" alt="Untitled 2" src="https://user-images.githubusercontent.com/41231764/185084827-d5d8b4c1-3c07-4be7-8b41-bd0bef4ceff0.png">

WordPress - 6.0.1

Gutenberg  - 13.8.1

Theme - Twenty Twenty Two

**Closed as completed by Thelmachido** 2022-08-17 09:26 UTC
Labels: [Type] Bug, [Block] Paragraph
