### ISSUE TITLE
Add class to <ul> in List block.

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#12420] opened 2018-11-29 14:08 UTC
**Is your feature request related to a problem? Please describe.**

The subject of adding classes to default blocks was discussed at [#6639](https://github.com/WordPress/gutenberg/issues/6639), and I know [you can filter the List block to add a new class](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/), but the `wp-block-list` class should be present by default.

Without a specific class, any style applied to the generic `<ul>` will inadvertently affect elements from third-party plugins or custom HTML added elsewhere, and we can't know beforehand if they will be affected.

One practical example happens when you try, for instance, to style the List block in a theme to add new bullets and you are also using the Elementor plugin.

Without a class, the generic `.ul` style will affect `<li>` elements used by Elementor in their control handles – unless you explicitly filter the class or resort to a convoluted solution as `ul:not(.elementor-editor-element-settings):not(.wp-block-gallery):not(.wp-block-categories):not(.wp-block-latest-posts)`... and so on.

This will surely happen with lots of other plugins that use the `<ul>` tag for tasks like this.

**Image 1:** Custom style added to `<ul>` tag.

![image](https://user-images.githubusercontent.com/1451087/49225833-37cf2380-f3cc-11e8-9a02-44841590160a.png)

**Image 2:** Custom style affecting a third-party plugin.

![image](https://user-images.githubusercontent.com/1451087/49225770-0d7d6600-f3cc-11e8-9ea6-dee3f430f179.png)

**Describe the solution you'd like**
Just add the `wp-block-list` class to the `<ul>` tag by default, in the List block.

**Describe alternatives you've considered**
* [Filter the List block to add a new class](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/)
* Add multiple `:not()` to the generic `.ul` style to target only the List block. 

Tested with 5.0-RC1-43946

**Comment by swissspidy** [comment] 2018-11-29 14:46
Note that using non-specific selectors like `ul` is a bad idea in general. I'm sure you could use something like `.content-area ul` in your theme.

**Comment by pagelab** [comment] 2018-11-29 15:23
That was just an example. 

The problem would persist if you utilize `.content-area ul.` – or other more specific selector.

The only way to solve the issue is to add a class to the `<ul>` tag itself.

**Comment by designsimply** [comment] 2018-11-29 16:01
I _think_ that the reason for avoiding adding classnames for everything by default is that not every theme would need them by default and so filtering in the cases where it makes sense is the preferred method when possible. Adding the `Needs Design Feedback` label to get a check on that assumption and to pull in feedback from the core design team.

**Comment by MichaelCampanella** [comment] 2018-12-03 16:34
I'm in favor of unordered lists having a class attached, especially with other blocks like the gallery block using the ul tag.

**Comment by saltnpixels** [comment] 2018-12-03 17:21
I am in favor of the ul block have some sort of class. Without it I cannot target those blocks easily.
I already made an issue once before and showed how the blocks could use a class or even a wrapper to stop from major issues in themes, especially ones where there is a sidebar or where pre and code are used without a wrapper...
:/ sadly it seems classes and div wrappers are not being added to the basic blocks.

**Comment by swissspidy** [comment] 2018-12-03 17:38
> sadly it seems classes and div wrappers are not being added to the basic blocks.

Adding div wrappers around every block by default would be quite a backward compatibility break.

**Comment by saltnpixels** [comment] 2018-12-03 18:43
> > sadly it seems classes and div wrappers are not being added to the basic blocks.
> 
> Adding div wrappers around every block by default would be quite a backward compatibility break.

How so? Backwards to what? Gutenberg hasn't been officially released yet has it?
And I doubt it would break anything except floats, which have their own issues.

**Comment by cecoates** [comment] 2019-04-17 21:24
A user emailed in:

1961093-zen

reporting that the gallery block on their site seems to be inheriting the margins for the theme itself.

![2HrDDw9](https://user-images.githubusercontent.com/10121835/56321841-26917400-612d-11e9-92cf-97ee4d1d7489.png)

That sounds very similar to what you're describing here. Would giving the block its own class allow things like "resetting" ul/li margins?

**Comment by Fcog** [comment] 2019-06-17 20:28
Please add a class to the ul and li tags. I need them to style the default gutenberg list style. I can't use the parent class because the custom blocks ul and li will be styled.

**Comment by onetrev** [comment] 2019-07-08 04:27
I very much agree `wp-block-list` should be included by default for `<ul>` and `<ol>` items. But the good news is for any developer you can at least easily add the class using the [code found here](https://wordpress.stackexchange.com/questions/308021/add-custom-class-to-core-blocks-in-gutenberg).

**UPDATE!!** The original answer in the link above technically works, but there are issues doing it this way, in particular you can then no longer add new classes later. But below in this issue is very much a [good workaround](https://github.com/WordPress/gutenberg/issues/12420#issuecomment-1557986683).

**Comment by aduth** [comment] 2019-07-10 13:43
> Without a specific class, any style applied to the generic `<ul>` will inadvertently affect elements from third-party plugins or custom HTML added elsewhere, and we can't know beforehand if they will be affected.
> 
> [...]
> 
> Without a class, the generic `.ul` style will affect `<li>` elements used by Elementor in their control handles – unless you explicitly filter the class or resort to a convoluted solution as `ul:not(.elementor-editor-element-settings):not(.wp-block-gallery):not(.wp-block-categories):not(.wp-block-latest-posts)`... and so on.

If I understand correctly: This is not inadvertent, the default list block intentionally absorbs generic `ul` styling (either explicit or browser-default). A list block should expect to be styled the same as any other standard list on the page, and vice-versa. The block implementation shouldn't be optimized on the assumption of a CSS reset (lists stripped of their default styling), but instead that the onus is on a custom variation of a list to unset its own default styling, or choose a more appropriate HTML tag which does not carry the same styling implications.

**Comment by pagelab** [comment] 2019-07-11 14:05
> I very much agree `wp-block-list` should be included by default for `<ul>` and `<ol>` items. But the good news is for any developer you can at least easily add the class using the [code found here](https://wordpress.stackexchange.com/questions/308021/add-custom-class-to-core-blocks-in-gutenberg).

Unfortunately, this is not a solution because it brings a bigger problem. If you add a class to the List block like this on the frontend (via `enqueue_block_assets`), you will also add many JS files from the editor.

![editor-js-files-frontend](https://user-images.githubusercontent.com/1451087/61057136-0e975c80-a3cb-11e9-9d7d-7adfb8b6c592.gif)

**Comment by pagelab** [comment] 2019-07-11 14:27
> (...) that the onus is on a custom variation of a list to unset its own default styling, 

This would only work if we could control the whole codebase, which is obviously not the case. 

A custom style created by any theme (or plugin), can't know beforehand if a certain property is applied to the default tag. So the onus can't be on it.

> (...) or choose a more appropriate HTML tag which does not carry the same styling implications.

If you have a list of things you should use the semantic tag for it. We should not resort to this kind of change just to avoid problems with styles.

The `<ul>` is a particular case, because is commonly used for lots of things besides displaying a simple list of text items, so this block should be treated differently.

**Comment by strarsis** [comment] 2019-12-23 02:52
@MichaelCampanella: Also, using `:not([class])` can cause new issues, as when a **typographically** used list gets additional classes assigned, e.g. for color or font-size, or a block style class that should just extend a small aspect of it on top of the base styles. Then the selector will stop working.

**Comment by mtias** [comment] 2020-08-30 10:40
Seems we should add standard block classes to a few of the elements we have left without.

**Comment by syllie** [comment] 2021-09-10 23:03
With every project I seem to add more :not exclusions to my css. Almost all blocks can be targeted directly. We have no options to 'slip in' extra classes on core blocks via PHP and this issue is pending like forever.  I do understand the purist approach but with the freedom for users to include blocks in more locations, we do need means to target and style them accordingly. Some priority on this issue would be nice.

**Comment by keithdevon** [comment] 2021-11-19 10:44
I'd like to add my vote to this issue.

Ideally, I'd be able to style 'List' block lists without using either reset styles on all other lists, or :not() selectors for all of the other lists.

I'd like a method to style List blocks that doesn't interfere with all of the other lists on a site. For example, menus, meta lists, footer lists, lists introduced by plugins (e.g. WP Job Manager), etc.

There is an argument above that List blocks should inherit the base `ul/ol` styles and additional styles should be applied with custom block styles.

I agree that solid default list styles are important, but I don't see how that is mutually exclusive with adding a `.wp-block-list` class. This would give theme developers more control and allow us to write _less_ CSS.

**Comment by markhowellsmead** [comment] 2021-11-19 11:04
I agree with @keithdevon. Adding a class to all of the core blocks (where they don't already have them) is a simple addition, and will allow developers to use much less (and much less hierarchically complex and less-specific) CSS.

**Comment by mtias** [comment] 2021-11-22 23:32
Let's look into rendering classes but only server side, without serializing them.

**Comment by markhowellsmead** [comment] 2021-11-23 08:24
@mtias I was going to add a pull request to add classes to the headings, paragraphs etc. Should this also be server-side instead of in the editor? (cc @luminuu.)

**Comment by mtias** [comment] 2021-11-24 13:26
Yes, that'd be preferable as a first approach. It can also ensure it works for existing content.

**Comment by markhowellsmead** [comment] 2021-11-30 16:26
I've been unable to find the place where a core class name would be applied server-side to e.g. the list block. The `render_block_core_` functions are only called on server-side-rendered blocks (e.g. `core/post-date`). Not for editor-rendered blocks. Applying class names in the editor is covered in the PR #36676 which Jessica submitted.

I see that the json files (e.g. wp-includes/blocks/list/block.json) already contains entries for style and editorStyle, which appear to be currently used only if core is to load individual styles per block. It doesn't look as if these definitions (e.g. `wp-block-list`) are currently intended for use as class names, which is puzzling.

Would your suggestion be to add a server-side aspect to parse every block, @mtias?

**Comment by Humanify-nl** [comment] 2021-12-15 10:35
NB. For those still struggling with this, until this is added / solved.

Adding a style to the list block generates the 'is-style-default' class to the unstyled list. For now, i've found this is the easiest way to solve the problem of splitting CSS code for generic ul applications like menu, gallery etc, in my custom theme. Since lists are quite often styled with a block-style in practice, this is the least painful to implement.

**Comment by mtias** [comment] 2021-12-15 12:21
@markhowellsmead all blocks can have a render callback attached. They are used in core to hook many behaviours, like responsive images, etc.

**Comment by skorasaurus** [comment] 2022-06-09 17:10
> NB. For those still struggling with this, until this is added / solved.
> 
> Adding a style to the list block generates the 'is-style-default' class to the unstyled list. For now, i've found this is the easiest way to solve the problem of splitting CSS code for generic ul applications like menu, gallery etc, in my custom theme. Since lists are quite often styled with a block-style in practice, this is the least painful to implement.

Interestingly, for me, this is not the case.. When I registered a new block style for the core list block (via registerBlockStyle; I omitted the isDefault value), the class name `wp-block-list` is applied to all newly created list blocks; even those that do not use my newly registered block style .

**Comment by alexandrebuffet** [comment] 2022-12-05 11:41
Block style do not seem to be the best solution. Adding a style to the list block (even with is_default/isDefault) does not generate the "is-style-default" parameter until the user has selected the style in the interface... See #38890.

Now that the decision has been made to add support for class name on "Heading" blocks. Can we consider the same support for "List" blocks until we develop a better solution to not saving className in the markup? @adamziel has correctly stated the problem and @andrewserong seems to validate the idea here: [#42122](https://github.com/WordPress/gutenberg/pull/42122#issuecomment-1331690557).

**Comment by pagelab** [comment] 2022-12-06 17:20
> Can we consider the same support for "List" blocks

@alexandrebuffet This is being discussed at #42269.

**Comment by carolinan** [comment] 2023-04-06 07:35
Can we resurrect this?
When the new per block custom CSS  is used with the list block, it affects all lists.

**Comment by RavanH** [comment] 2023-05-04 17:54
Please resurrect.

It also affects Navigation block submenus with a custom background color. See https://github.com/WordPress/gutenberg/issues/50342

**Comment by mrwweb** [comment] 2023-05-22 20:59
Here's a PHP polyfill for doing this if it's useful to anyone:

```php
add_filter( 'render_block', __NAMESPACE__ . '\add_class_to_list_block', 10, 2 );
/**
 * Polyfill wp-block-list class on list blocks
 *
 * Should not be necessary in future version of WP
 *
 * @see https://github.com/WordPress/gutenberg/issues/12420
 * @see https://github.com/WordPress/gutenberg/pull/42269
 */
function add_class_to_list_block( $block_content, $block ) {

	if ( 'core/list' === $block['blockName'] ) {
		$block_content = new WP_HTML_Tag_Processor( $block_content );
		$block_content->next_tag(); /* first tag should always be ul or ol */
		$block_content->add_class( 'wp-block-list' );
		$block_content->get_updated_html();
	}

	return $block_content;
}
```

This requires WordPress 6.2 which included the new `WP_HTML_Tag_Processor` class.

**Comment by strarsis** [comment] 2023-05-22 21:55
@mrwweb: The inclusion of `WP_HTML_Tag_Processor` is great, finally an external HTML5 parser library can be skipped.

**Comment by talldan** [comment] 2023-11-27 09:18
I noticed there's also https://github.com/WordPress/gutenberg/issues/50486, which might be a duplicate of this. It has quite a lot of detail on it.

**Comment by shaunjc** [comment] 2023-12-21 07:02
This still seems to be a major issue when developing block themes, as setting any of the default styling or setting custom CSS via **Styles > Blocks > List** will create CSS rules for `ul, ol`, affecting all manner of other blocks, such as latest posts, query loop and navigation blocks.

The polyfill above currently only works at putting a class name into the markup. If we want to use the same class name in our CSS, we either need to use the **Styles > Additional CSS** or find another way to populate the styles.

With that in mind, I registered a second filter that replaces the selector with my own custom classes, and it seems to work well for me so far.

```php
add_filter( 'register_block_type_args', function( $args, $block_name ) {
	switch ( $block_name ) {
		case 'core/list':
			$args['supports']['__experimentalSelector'] = 'ol.wp-block-list,ul.wp-block-list';
			break;
	}
	return $args;
}, 10, 2 );
```

Of course, given that it has "experimental" in the name, I assume that this may change in future. Setting a default class name for this block in core would be the best way to move forward.

**Comment by tellthemachines** [comment] 2024-02-29 05:49
Given the way that global styles can now be defined on blocks, attaching classes only on the server side doesn't seem like a viable approach any longer. We need to be able to attach List block-specific styles to a classname that works in _both_ the editor and the front end.

**Comment by onetrev** [comment] 2024-03-05 01:31
What about adding className support as demonstrated in the [Block Filters docs](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-registerblocktype)? It seems to work well on a new site, but it will result in "_This block contains unexpected or invalid content_" if added to a site with existing lists. So still not perfect.

**Comment by carolinan** [comment] 2024-03-05 03:28
@priethor @mtias Hi
There are two suggestions for changing the approach on how to add the wp-block class name to the list block.

One is to use the class in both the editors and front:
> Given the way that global styles can now be defined on blocks, attaching classes only on the server side doesn't seem like a viable approach any longer. We need to be able to attach List block-specific styles to a classname that works in _both_ the editor and the front end.

The other is to also add a class on the inner list item block:
> Question? Seeing the amount of work it takes to add a class name to a block, wouldn't it make sense to use this oportunity when we are already chaging the selector that is used for the list item block so also just add the class `wp-block-list-item` to the list item block?

Given the previous discussion and change requests from @mtias, how do you propose that we move forward with the issue?

**Comment by carolinan** [comment] 2024-04-05 12:46
How can we move this forward?

**Comment by youknowriad** [comment] 2024-04-05 12:55
> Given the way that global styles can now be defined on blocks, attaching classes only on the server side doesn't seem like a viable approach any longer. We need to be able to attach List block-specific styles to a classname that works in both the editor and the front end.

I think @mtias's idea was to add it to both the frontend and the editor but to not serialize it in the saved markup. I think it's a given that the markup of the editor should match the frontend.

**Comment by carolinan** [comment] 2024-04-12 13:13
I am going to need more context because when I apply the PR the class is in all editors and the front...

**Closed** 2024-05-09 04:12 UTC
Labels: [Type] Task, Good First Issue, Needs Decision, [Block] List, [Feature] Themes
