### ISSUE TITLE
Visual tools: make it possible to customize separators and strokes weight and shape

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#41228] opened 2022-05-23 10:03 UTC
In the context of style variations (_Related: #40988 and #35619_), considering elements that can vary between them, it would be great to be able to customize separators and strokes weight and shape (line/double line/dashed/dotted) in the editor, as this can be a differentiator element between variations.

<img width="1543" alt="Captura de ecrã 2022-05-23, às 11 01 35" src="https://user-images.githubusercontent.com/65220155/169795446-ffdb683e-f113-4595-bea2-16cd01fd0dfa.png">

Perhaps even consider a more advanced stroke customization:

<img width="272" alt="Captura de ecrã 2022-05-23, às 11 03 05" src="https://user-images.githubusercontent.com/65220155/169795693-1831de86-f4d6-4b23-8538-2393ac914b99.png">

**Comment by javierarce** [comment] 2022-05-24 10:05
This would be great and I think we have all the pieces necessary to improve this block. I would also include a way to customize the width of the separator.

**Comment by beafialho** [comment] 2022-05-24 10:13
Seems like separator width is being handled here @javierarce #23403

**Comment by annezazu** [comment] 2024-07-02 21:58
Closing this out as a duplicate of the following original issue: https://github.com/WordPress/gutenberg/issues/16483

**Closed as completed by annezazu** 2024-07-02 21:58 UTC
Labels: [Type] Enhancement, [Feature] Theme Style Variations, [Block] Separator, Global Styles
