### ISSUE TITLE
Rendering empty paragraph blocks

### ISSUE THREAD

**Issue by edirpedro** [WordPress/gutenberg#15918] opened 2019-05-30 14:19 UTC
The editor is rendering empty paragraph blocks and this always cause some issues in the front-end, placing empty spaces on screen that breaks the design and the client can't understand what is happening and how to fix it.

It's hard to fix too because the paragraphs can appear on the editor with just a click or using the arrow keys to navigate through the blocks. It's easy to create those empty tags when editing some content. I can understand the way the editor add this block automatically, but if empty, the editor shouldn't save them without some content, at least a space to indicate that it was really intentional.

Moving between blocks using arrow keys creates empty paragraph blocks

![ezgif-1-88041265fa1a](https://user-images.githubusercontent.com/831507/58639001-70dd4780-82cc-11e9-8761-1eed821eb096.gif)

They are saved and rendered on the front-end

![Captura de Tela 2019-05-30 às 11 07 02](https://user-images.githubusercontent.com/831507/58638918-44293000-82cc-11e9-9640-b99837c63b75.png)

Testing on WordPress 5.2.1

**Comment by talldan** [comment] 2019-05-31 05:52
Hi @edirpedro - thanks for creating the issue. Are you specifically talking about an empty paragraph at the end of a post? It's a bit hard to tell, because in your screen capture it's an empty paragraph between blocks.

I wasn't able to reproduce it in my editor. I tried:
1. Add a block
2. Add another block
3. Use arrow keys to navigate between them.

If you can provide some specific steps that others can follow to reproduce the issue that would be really helpful. Thanks.

**Comment by edirpedro** [comment] 2019-05-31 12:59
1. Add a columns block
2. Add an image block inside each one
3. Use arrows keys to navigate  between them

Another way is just starting a document and hit enter to add new paragraphs. The empty tag `<p>` will be saved and rendered in the front.

![Captura de Tela 2019-05-31 às 09 48 13](https://user-images.githubusercontent.com/831507/58706847-806e9600-8389-11e9-8e88-a09f3d1cd8c6.png)

Results in:

```
<h1>Gutenberg</h1>
<p></p>
<p></p>
<p></p>
<p></p>
```

In my opinion, only a paragraph with some space `<p> </p>` should be saved as intentional, when empty, the editor should remote it when saving.

**Comment by senadir** [comment] 2019-06-03 10:03
some people use empty paragraphs for spacing between blocks of text, removing them all together might cause problems & compatibility issues

a fix you can implement on your side is to hide empty paragraphs all together
```css
p:empty {
    display: none;
}
```

or hide the last one if you wish

```css
p:empty:last-of-type {
    display: none;
}
```

**Comment by swissspidy** [comment] 2019-06-03 10:48
Previously reported in #10051, #13599. Also related: #11238.

**Comment by edirpedro** [comment] 2019-06-03 13:37
I was thinking about and first, using empty paragraphs is how text editors works and how people usually write when they need some space in the document, second, for web development this can be intended as a bug because empty tags is not a good practice.

As a developer I would like to see this "feature" removed, but i'm not sure how this would affect other people who will write content. But Gutenberg doesn't work exactly like a text editor because of the block elements used to create content, the interface is not clean like a text editor is, so empty paragraphs does not seems to fit good on it. In my recorded video you can see that they break good rendering even on the Gutenberg side.

There is a Spacer block so I think that this element should be the right one to create spaces inside Gutenberg and not empty blocks.

**Comment by senadir** [comment] 2019-06-03 13:42
maybe we can find a way to keep compatibility & encourage the use of the Spacer Block

**Comment by jkd77** [comment] 2019-06-26 14:57
Has there been any movement on this issue? If there's an empty block awaiting text (for admin convenience) it should either be deletable in back-end or should not render an empty element on the front-end. Visual element spacing should be the purview of style / css and not empty paragraphs.

**Comment by youknowriad** [comment] 2019-08-19 17:12
Let's close this as a duplicate to #10051 to keep discussions focused.

**Closed by youknowriad** 2019-08-19 17:12 UTC
Labels: [Block] Paragraph, [Status] Needs More Info, [Type] Bug

**Comment by WraithKenny** [comment] 2020-02-07 17:25
I'm not sure this should be closed in favor of the other, since this is about empty Ps being inserted unintentionally, and the inability to remove them at all.

**Comment by Markus872** [comment] 2020-02-24 23:53
one reason not to use Guteberg. They're not even able to fix this so you will always have an empty p tag below a reusable element. Hilarious

**Comment by Markus872** [comment] 2020-02-26 06:38
This is really unbelievable. I tried to remove the empty p tags but it is not possible for me. Who is responsible for this Gutenberg crap. You need to immediately stop doing this editor as it is extremly bad and a time waste. This editor is absolutely the worst editor ever. Everyone says it. The UI is horrible and not quickly understandable by any normal person and stupid to use. Now you can't even remove p elements and the bots will see them. This was the first and last time that I used Gutenberg. I used it in combination with ACF to give the client a pagebuilder.
