### ISSUE TITLE
`render_callback` not called when "Hide the teaser" is selected in "more" block

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#14874] opened 2019-04-08 20:25 UTC
**Describe the bug**
When enabling _"Hide the teaser before the More tag"_ option in More block, blocks relying on `render_callback` stop working.

**To reproduce**
1. Create a new page, add:
    - Paragraph block with some content
    - More block
    - Latests posts block
    <img width="730" alt="Screenshot 2019-04-08 at 23 15 34" src="https://user-images.githubusercontent.com/87168/55754380-31754600-5a55-11e9-8db6-940b913fcfee.png">

2. Click on more block and toggle _"Hide the teaser"_ option:
    <img width="282" alt="Screenshot 2019-04-08 at 23 14 38" src="https://user-images.githubusercontent.com/87168/55754166-aac06900-5a54-11e9-9895-6914d26dfdbd.png">

3. Save and open the page
4. No latests posts :-(
5. Go back to editor and disable toggle
6. Latests posts work :-)

Unlike normally, in the source code, HTML comments for blocks are visible:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/87168/55746376-341a7000-5a42-11e9-9cc3-b003234c3290.png">

**Expected behavior**
Blocks depending on `render_callback` to work.

**Additional context**
- Tests with Gutenberg plugin enabled 5.4.0
- Tests with Gutenberg plugin disabled on WordPress 5.1.1
- Didn't test latest `master` branch

Came up via https://github.com/Automattic/jetpack/issues/11959

**Comment by paaljoachim** [comment] 2021-01-12 22:43
Hey @simison Mikael

Is this issue still relevant? Can we close it?

**Comment by carolinan** [comment] 2022-07-14 08:44
I am unable to reproduce this following the provided instructions, the latest posts blocks displays correctly.
(The setting is now labeled "Hide the excerpt on the full content page")

**Closed** 2022-07-14 08:44 UTC
Labels: [Type] Bug, [Block] More
