### ISSUE TITLE
I recommend adding the Table of Contents Block to WordPress version 6.6

### ISSUE THREAD

**Issue by phanduynam** [WordPress/gutenberg#61887] opened 2024-05-23 04:33 UTC
WordPress version 6.5.3 does not have a table of contents block, I recommend adding a Table of Contents block to WordPress 6.6 to quickly create a table of contents based on all the headings on a page. From then on I won't need to install the Table of Contents Plugin anymore.

**Comment by fabiankaegy** [comment] 2024-05-23 05:41
Closing this as a duplicate of #42229

@phanduynam please leave your thoughts about this inclusion of this block in #42229 :)

**Closed as completed by fabiankaegy** 2024-05-23 05:41 UTC
Labels: [Type] Enhancement
