### ISSUE TITLE
The editor has encountered an unexpected error

### ISSUE THREAD

**Issue by mitchellkrogza** [WordPress/gutenberg#14613] opened 2019-03-25 09:22 UTC
**Describe the bug**
Unable to edit old post

**To Reproduce**
The moment I click inside old style block it crashes the editor. This makes my post totally uneditable nor am I able to convert it to blocks and resume editing. Works in Chrome but I use Firefox for all my wp-admin work.

**Expected behavior**

**Screenshots**
![gute3](https://user-images.githubusercontent.com/9961541/54908053-abeb8500-4eef-11e9-8c0c-6029dbc56a7e.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Arch
 - Browser Firefox
 - Version 66.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
Latest wordpress 5.1.1

**Error Message**
```
zn@https://mydomain.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45248
this.wp.editor</Gn</o<@https://mydomain.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:46071
this.wp.editor</Gn<@https://mydomain.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45906
u@https://mydomain.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:12:3425
g/n</</<@https://mydomain.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:6377
this.wp.editor</zl<@https://mydomain.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:270190
n@https://mydomain.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13036
r@https://mydomain.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13298
zf@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258
Mf@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:87:4
ph@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474
eg@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307
fg@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168
wc@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237
fa@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115
ng@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:149:69
Se@https://mydomain.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:40:45
```

**Comment by youknowriad** [comment] 2019-03-25 10:09
The error message is incomplete, can you share the full message (or make a screenshot of your browser's console)

**Comment by mitchellkrogza** [comment] 2019-03-25 10:37
@youknowriad clicking the "Copy Error" button and posting into my text editor ... that is all there is, I'm afraid.

**Comment by youknowriad** [comment] 2019-03-25 10:39
I guess the "Copy Error" is doing something wrong :) or not fully rendering the error. Can you try to open the browser's console. See here for Chrome for instance https://developers.google.com/web/tools/chrome-devtools/shortcuts

**Comment by mitchellkrogza** [comment] 2019-03-25 10:42
@youknowriad here's from console
![error](https://user-images.githubusercontent.com/9961541/54913439-646af600-4efb-11e9-90a3-c0ff6b2199d3.png)

**Comment by youknowriad** [comment] 2019-03-25 10:44
It looks like this is a duplicate of #14580

Try clearing the local storage of your browser, I think it should fix the issue for you for now.

**Closed by youknowriad** 2019-03-25 10:44 UTC
Labels: [Status] Needs More Info

**Comment by mitchellkrogza** [comment] 2019-03-25 10:48
Clearing caches, cookies ie. everything has not helped. Just tried now.

**Comment by youknowriad** [comment] 2019-03-25 10:49
not caches or cookings, local storage for the website you're currently editing.

**Comment by mitchellkrogza** [comment] 2019-03-25 10:59
Ok thanks that has fixed it now.
