### ISSUE TITLE
Navigation block doesn't show Categories

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18859] opened 2019-12-02 07:30 UTC
**Describe the bug**
When You type a Category name into the input field it doesn't list any Categories.

Having different Categories as menu items is extremely common, especially for blogs, where someone might want a direct link to different blog topics.

Even the current Appearance > Menus screen has the Categories option available by default because it's so popular.

<img width="1143" alt="screenshot_269" src="https://user-images.githubusercontent.com/2078245/69938221-d38bf600-1530-11ea-870a-d20a3faf813a.png">

Current Menus edit screen with Categories panel
<img width="1105" alt="screenshot_270" src="https://user-images.githubusercontent.com/2078245/69938346-25348080-1531-11ea-996f-e243ab647a1e.png">

**To reproduce**
1. Add Navigation Block
2. Add menu option and type in a Category name
4. Notice there's no categories listed

**Expected behavior**
Users shouldn't have to manually type in the URL of their Categories page to add it to the menu.

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6
- Browser: Firefox 70.0.1
- Version: WP 5.3

**Comment by ramonjd** [comment] 2020-02-10 05:45
We've come across this issue during internal testing as well (`7.4.0`).

Are there any plans to add Categories and Tags to available navigation items?

See: p7DVsv-87m-p2#comment-26737

**Comment by noisysocks** [comment] 2020-05-20 01:01
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/20165 as, although newer, that issue has some proposed ways to go about implementing this.

**Closed by noisysocks** 2020-05-20 01:01 UTC
Labels: [Block] Navigation
