### ISSUE TITLE
"Welcome" tip dismissal uses local storage, requiring a new dismissal for every new device and browser

### ISSUE THREAD

**Issue by JJJ** [WordPress/gutenberg#10742] opened 2018-10-18 14:34 UTC
When adding or editing a post for the first time, Gutenberg shows a big weird blocking tip thing. Aside from the relatively confusing look and disconnected styling of the thing, it's also per-device and per-browser, so every new visit to Gutenberg requires acknowledgement and dismissal of the same obtrusive thing before I can do anything.

**To Reproduce**
1. Open your favorite browser and navigate to a newish install
2. Login, and head to WP Admin
3. Click "Add New" Post via your favourite route
4. See the tip with the blue throbber (screenshot below)
5. Click "X" to dismiss the tip
6. Open a different browser, or go into Incognito/Private mode
7. Repeat steps 2 through 4
8. See the tip again, even though you dismissed it

**Expected behavior**
Tips like these should not use local storage. They should be persistent across sessions, and belong in the database, so users are not required to re-dismiss something repeatedly across all devices.

**Screenshots**
<img width="691" alt="screen shot 2018-10-18 at 9 32 22 am" src="https://user-images.githubusercontent.com/88951/47161985-be1a2500-d2b8-11e8-8354-c9714faee8e1.png">

<img width="706" alt="screen shot 2018-10-18 at 9 33 07 am" src="https://user-images.githubusercontent.com/88951/47162024-d7bb6c80-d2b8-11e8-916f-548a7a57e16f.png">

<img width="914" alt="screen shot 2018-10-18 at 9 33 52 am" src="https://user-images.githubusercontent.com/88951/47162093-f588d180-d2b8-11e8-8dbb-6ad9de04669f.png">

**Desktop (please complete the following information):**
 - OS: macOS (10.14)
 - Browser Any (any)

**Additional context**
- Gutenberg 4.0.0

**Comment by Soean** [comment] 2018-10-18 14:59
Related to #8052

**Comment by Soean** [comment] 2018-10-18 15:16
Thanks for reporting @JJJ, I close this one as duplicate of #8052. It covers this issue and related problems of storing user settings for the editor.

**Closed by Soean** 2018-10-18 15:16 UTC
Labels: NUX, [Type] Enhancement
