### ISSUE TITLE
Frontend parser is too slow

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#1758] opened 2017-07-06 09:09 UTC
## Issue Overview
When we publish a changelog for Yoast SEO Premium on [yoast.com](https://yoast.com/) with Gutenberg 0.3 active, it times out in the Gutenberg parser. See screenshot:

![yoast_seo_premium_changelog_wordpress_plugin_ _yoast](https://user-images.githubusercontent.com/487629/27903882-2e39648a-623b-11e7-9b37-213e2b495560.jpg)

I've also tested this on a lighter site, [where it does load](https://joost.blog/changelog-test/) but is extremely slow too.

This is the raw HTML we have in the post:
[changelog-yoast-seo-premium.txt](https://github.com/WordPress/gutenberg/files/1127297/changelog-yoast-seo-premium.txt)

## Steps to Reproduce
1. Put the content of the above linked txt file in a post or page.
2. Load that page on the frontend, experience slowness and/or see the error seen in the screenshot above.

**Comment by swissspidy** [comment] 2017-07-06 09:19
Duplicate of #1646.

**Closed by swissspidy** 2017-07-06 09:19 UTC
