### ISSUE TITLE
⌘A should select all of the content

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2292] opened 2017-08-08 16:34 UTC
Right now,  ⌘A only selects the current block of content.  This means that it's impossible in the Visual editor to select all of the content only using the keyboard.

**Comment by youknowriad** [comment] 2017-08-08 16:36
If a block is selected yet (an input, a textarea, an editable),  ⌘A will select only this area but if you focus something else it will select the whole content. That's the tradeoff we're making right now.

**Comment by jasmussen** [comment] 2017-08-08 18:27
We discussed this in Slack briefly, and I misunderstood the question being asked. And so this ticket is actually expected behavior per discussion in #3. 

We also discussed copy and paste behavior, which as it turns out is _semi functional_ but needing a lot of polish. Here's a video also showing the ⌘ A behavior on the blocks. But I'm closing this one for now, and will reopen a separate ticket for copy/paste improvements.

**Closed by jasmussen** 2017-08-08 18:27 UTC

**Comment by bluefuton** [comment] 2019-05-30 01:53
Are there any more recent updates on this one folks? It trips me up frequently, because my natural expectation is that  ⌘ A selects the entire document (as it would in most other editors).
