### ISSUE TITLE
Query Loop Pagination: When there are multiple queries with pagination - paging seems to affect both loops

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53006] opened 2023-07-27 01:54 UTC
### Description

On a page with 2 (or more ) Query Loop blocks that allow paging - clicking to the next page of results loads the next set of posts for BOTH loops/queries.

When navigating to the next 'page' of either loop I found the URL was the same - appending `?query-13-page=2`. My understanding is that the `query-13` part of that is designed to target the specific query, but as both loops use the same ID it doesn't seem to work.

### Step-by-step reproduction instructions

1. Set up a page with 2 separate query loops. They'll need to not use the inherited query, and be separate queries (filtered for separate taxonomies).
2. Make sure both of the Query Loops includes pagination.
3. Publish and view the page - and then click to the next page of results for one of the Query Loops.

### Screenshots, screen recording, code snippet

<img width="1009" alt="Screenshot 2023-07-27 at 11 49 23 am" src="https://github.com/WordPress/gutenberg/assets/1842363/f857d07d-33d5-4530-b04a-1ea78e485b44">

On Initial Load

<img width="1024" alt="Screenshot 2023-07-27 at 11 49 14 am" src="https://github.com/WordPress/gutenberg/assets/1842363/577512c3-32b3-4c47-8512-a1d9a697dfe9">

Result when navigating to the next 'page' of either query

### Environment info

* WP 6.2.2 and 6.3RC2
* No plugins
* TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2023-07-31 10:03
👋 Thanks for the issue! Query Loop blocks need to have a different queryId in order for the pagination to work well. Currently this block(with `queryId`) and some other blocks too, are affected by an issue we have when we duplicate/clone blocks that need some attributes to have a special handling(for example being unique). See [here](https://github.com/WordPress/gutenberg/pull/38643) for a currently stale attempt to do that.

 Is that the case how you ended up with two Query Loop blocks with the same queryId? If yes, for now you should just update manually one `queryId` in code editor..

**Comment by jordesign** [comment] 2023-07-31 10:34
Thanks @ntsekouras  - that is indeed how I generated the second query loop. That's good to know - thank you :)

**Comment by ntsekouras** [comment] 2023-07-31 12:22
@jordesign I'll close this issue then, as the root cause of your problem was caused by a different thing, being tracked elsewhere.

**Closed as completed by ntsekouras** 2023-07-31 12:22 UTC
Labels: [Type] Bug, [Block] Query Loop
