### ISSUE TITLE
Navigation Block doesn't show in published page

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#27259] opened 2020-11-25 07:40 UTC
**Describe the bug**
The navigation block that I added into a page doesn't display when I view that published page in the browser.

**To reproduce**
Steps to reproduce the behaviour:
1. Add navigation Block
2. Publish Page and view in browser
3. Navigation block doesn't appear

**Expected behaviour**
If I add a block to a page I expect it to appear in the page when I view it the browser

**Screenshots**
Block Editor
<img width="1920" alt="screenshot_512" src="https://user-images.githubusercontent.com/2078245/100196313-ce4b6680-2f4c-11eb-80b2-4558e3f92612.png">

Published Page
<img width="1920" alt="screenshot_514" src="https://user-images.githubusercontent.com/2078245/100196339-d4d9de00-2f4c-11eb-90d3-82673dcc1a3c.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6-RC1-49690
- Does the website have the Gutenberg plugin installed, or is it using the block editor that comes by default? Yes v9.4.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Firefox 83.0

**Comment by ntsekouras** [comment] 2020-11-25 13:27
Hey @maddisondesigns - thanks for reporting this.

I tried to reproduce and couldn't. Tried with Chrome and Firefox.

**Comment by talldan** [comment] 2020-11-26 06:18
I also couldn't reproduce against latest 5.6 code and Gutenberg plugin code. I wondered if it might be working now due to this reverted change in core, but I'm not sure:
https://github.com/WordPress/wordpress-develop/commit/a86bedfc920141d2bebbc608e419c04ee221b229

We don't have many tests to catch issues with dynamic block rendering, so hard to say if there was an issue.

**Comment by maddisondesigns** [comment] 2020-11-26 06:45
I've just had another look at the original page I mentioned above, and the menu is now appearing in the browser as expected. The only thing that has changed on that site since I raised this issue, is that WordPress has updated itself to 5.6-RC1-49694 (was previously 5.6-RC1-49690)


<img width="1920" alt="screenshot_515" src="https://user-images.githubusercontent.com/2078245/100316533-d370ea00-300e-11eb-93fd-9a679b0cb7a4.png">

**Comment by ntsekouras** [comment] 2020-11-26 09:07
Thanks for testing again @maddisondesigns . I'll close this then.

**Closed by ntsekouras** 2020-11-26 09:07 UTC
Labels: Needs Testing, [Block] Navigation
