### ISSUE TITLE
harmonize media & text block and image block - insert from url

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#42264] opened 2022-07-08 11:34 UTC
## What problem does this address?
When media & text block is inserted, there is no option to insert image from url, like it exists for image block

![image](https://user-images.githubusercontent.com/33687174/177984449-95700616-9b9f-4156-89c0-8a025db33f2f.png)

![image](https://user-images.githubusercontent.com/33687174/177984393-0daa4f21-7bbb-43a3-b8de-00a327ebdc2b.png)

## What is your proposed solution?
Add button to media & text block to insert image from url. This option should also exist when replace button on toolbar in media & text is pushed.

**Comment by carolinan** [comment] 2022-07-08 12:07
Hi!

This feature used to exist but needed to be removed because there was no way to detect if the remote media was a video or image (I have no technical details of why). See https://github.com/WordPress/gutenberg/pull/19606.

I am closing this as a duplicate of [#14397. ](https://github.com/WordPress/gutenberg/issues/14397), please continue the discussion there.

**Closed as not planned by carolinan** 2022-07-08 12:07 UTC
Labels: [Status] Duplicate
