### ISSUE TITLE
Typing ```js doesn't select the right language in SyntaxHighlighter Code block and causes block to crash

### ISSUE THREAD

**Issue by alexflorisca** [WordPress/gutenberg#41623] opened 2022-06-09 10:17 UTC
### Description

When typing ```js to bring up a SyntaxHighlighter Code block, it creates the block, but the language is set to empty. Clicking on the language setting makes the block crash. I would expect it to create the SyntaxHighlighter Code block with the JavaScript language selected.

### Step-by-step reproduction instructions

1. Open up the editor
2. Type: ```js and hit enter
3. See that the SyntaxHighlighter Code block has been added, but where the language setting should be, there is nothing.
4. Click on where the language setting should be and the block will crash with a `This block has encountered an error and cannot be previewed.` error.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/3966773/172822772-1ad04096-1f87-4d1c-b510-a5268738e42c.mov

### Environment info

Wordpress 6.0, Gutenberg not installed, P2 theme
Mac OS
Chrome v101

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment] 2022-06-10 05:22
I don't think that the `SyntaxHighlighter Code block` is part of the core Gutenberg project. Are you sure there isn't another plugin installed that is providing this block? 

I tried a base GB install with P2 theme and I don't see the syntax highlighting block:

<img width="327" alt="Screen Shot 2022-06-10 at 5 21 32 PM" src="https://user-images.githubusercontent.com/3629020/172995835-191bca8c-8d48-4779-b4e4-b1310468bce6.png">

**Comment by t-hamano** [comment] 2022-06-10 09:01
[SyntaxHighlighter Code Block](https://wordpress.com/support/wordpress-editor/blocks/syntax-highlighter-code-block/) seems to be a block provided by WordPress.com.
I was able to reproduce the exact same problem in my environment.
Does anyone know where we should report this issue?

**Comment by tyrann0us** [comment] 2022-06-10 09:20
@t-hamano

> Does anyone know where we should report this issue?

Probably here: https://github.com/Automattic/syntaxhighlighter.

**Comment by t-hamano** [comment] 2022-06-10 11:08
@tyrann0us
Thanks for letting me know!
I built and tested this repository and confirmed the same problem.

@alexflorisca
I have submitted a [PR](https://github.com/Automattic/syntaxhighlighter/pull/242).
I close this issue, and please check this PR for future status.

**Closed as completed by t-hamano** 2022-06-10 11:08 UTC

**Comment by alexflorisca** [comment] 2022-06-10 12:32
Thanks for the PR @t-hamano. apologies for raising this in the wrong repo!
