### ISSUE TITLE
Cover Block with solid background has always black background

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#21709] opened 2020-04-18 19:37 UTC
Hey since the gutenberg 7.9 release, cover blocks with a solid background color get always a black background. Because the block container has an unexpected class name "has-background-dim". There is something wrong. Because the background opacity is only correct, if we use a background image, but not a solid background color.

It looks correct in the backend editor and wrong on the frontend view.

<img width="187" alt="Bildschirmfoto 2020-04-18 um 21 34 14" src="https://user-images.githubusercontent.com/31563167/79669522-62d23700-81bc-11ea-8485-d1ef6eab5936.png">

**Comment by annezazu** [comment] 2020-04-23 22:18
Hey there! Thanks for reporting this. I tried to replicate the problem you described but wasn't able to. @CreativeDive can you share more [screenshots](https://www.take-a-screenshot.org/) of the problem? Can you try replicating this with a different theme and without any other plugins activated? I want to be sure to rule out a possible plugin/theme conflict :) 

**Screenshots**

<img width="1365" alt="Screen Shot 2020-04-23 at 3 14 15 PM" src="https://user-images.githubusercontent.com/26996883/80154813-2fedc180-8575-11ea-90a0-93c15e4457b5.png">
<img width="1364" alt="Screen Shot 2020-04-23 at 3 14 25 PM" src="https://user-images.githubusercontent.com/26996883/80154818-30865800-8575-11ea-8c2d-cd08c65fb843.png">

**My Setup**

- WordPress 5.4
- Gutenberg 7.9.1
- Theme: Twenty Twenty
- No other plugins installed except Gutenberg

**Comment by carolinan** [comment] 2020-04-24 02:13
If you save and preview the post or page before selecting a color image, it is black.
The background dim is always applied even if there is no selected background.

**Comment by annezazu** [comment] 2020-04-24 04:35
Thanks for clarifying. It sounds like this only happens if you don't actually begin to edit the actual cover block before publishing. Here are screenshots so we're all on the same page:

<img width="870" alt="Screen Shot 2020-04-23 at 9 31 45 PM" src="https://user-images.githubusercontent.com/26996883/80175261-f2575b80-85a9-11ea-968f-ea8c037628a4.png">
<img width="791" alt="Screen Shot 2020-04-23 at 9 31 48 PM" src="https://user-images.githubusercontent.com/26996883/80175257-f1262e80-85a9-11ea-9a98-d61ae0d4560e.png">

This is actually a duplicate of this https://github.com/WordPress/gutenberg/issues/10854 so I'm going to close this out in favor of this original issue. Thanks for the reports!

**Closed by annezazu** 2020-04-24 04:35 UTC
Labels: [Block] Cover, [Status] Needs More Info

**Comment by salytwo** [comment] 2020-07-16 21:22
same problem with drupal 8, the interested thing is when give the user who will edit the page administrator role, Gutenberg works fine.
In other words this problem occurs with non administrator role users
