### ISSUE TITLE
Add a universal way to remove top/bottom margins

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#20973] opened 2020-03-17 23:34 UTC
**Is your feature request related to a problem? Please describe.**
Here's an example of a page layout I've been working on. The idea is to have no spaces between sections:
![smallbusiness_alves](https://user-images.githubusercontent.com/4550351/76910585-8c204e80-6902-11ea-95e1-946bb2c67852.png)

**Describe the solution you'd like**
It would be useful to be able to remove top/bottom margins on any block.

**Comment by talldan** [comment] 2020-03-19 04:02
@alaczek There's some movement on being able to adjust margin/padding in the group block as a starting point.

The issue is here: https://github.com/WordPress/gutenberg/issues/14747
There's ongoing work in a pull request here: https://github.com/WordPress/gutenberg/pull/16730#issuecomment-590409843

I'd recommend catching up with the discussion and commenting on those issues. I'll close this issue as a duplicate if that's ok.

**Closed by talldan** 2020-03-19 04:02 UTC
