### ISSUE TITLE
.wp-block-cover style is getting overridden by themes .alignleft utility styles. v4.3.0

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#11883] opened 2018-11-14 21:28 UTC
**Describe the bug**
When a cover block is set to one of the align states, it's styles go up against the themes age-old `.align*` styles.

Most of them include a `display:` style and it usually isn't `flex`.

This breaks the wp-block-cover-image-text

**To Reproduce**
Add an align state to a cover block with text.

**Screenshots**
Here's how it looks before `.aligncenter` is added
![no-align](https://user-images.githubusercontent.com/3585901/48513256-5ad4d180-e829-11e8-9d9a-4ee313a5c8db.png)

Here's with the `.aligncenter` class
![align-center](https://user-images.githubusercontent.com/3585901/48513281-6de7a180-e829-11e8-86b5-5de8e79c26e6.png)

In this case Twenty Seventeen is overriding the `display: flex;` with it's aligncenter's `display: block;`

**Comment by designsimply** [comment] 2018-11-14 23:22
Thanks for the report! Closing this one as a duplicate of https://github.com/WordPress/gutenberg/issues/11382 and this issue will automatically get linked there.

**Closed by designsimply** 2018-11-14 23:22 UTC
Labels: [Block] Cover, [Status] Duplicate, [Type] Bug
