### ISSUE TITLE
Improve upon bulk save modal

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#49880] opened 2023-04-17 23:41 UTC
The existing bulk save modal that's triggered when in site editor admin has an unusual structure with actions on top vs bottom. We should align with other modals on the platform.

![Image](https://user-images.githubusercontent.com/1072756/232380778-02feaafd-be47-4d9d-8dc6-a8f84940dd0e.png)

**Comment by Mamaduka** [comment] 2023-04-18 05:29
Thank you, @SaxonF!

Is this a duplicate of #49832? Should we combine the issues?

**Comment by SaxonF** [comment] 2023-04-18 05:59
@Mamaduka It is indeed! I'll close this one out.

**Closed as completed** 2023-04-18 05:59 UTC
