### ISSUE TITLE
Columns Block: adjacent siblings not updating flex-basis when setting width

### ISSUE THREAD

**Issue by bfiessinger** [WordPress/gutenberg#25905] opened 2020-10-07 13:49 UTC
By setting the width of a single column in **Columns Block** the adjacent columns are not updating their width depending on the currently edited column.

**To reproduce**
1. Add a new columns block
2. set the width of a single column to let's say 60%

if no variant was chosen the other column will still have no flex-basis instead of 40%, if a variant was chosen other columns flex-basis won't change and will for example still have flex basis of 50% or 25% and 25%.

**Expected behavior**
By chosing a variant for example `25 / 50 / 25` and changing the width of the second column to 60% the other columns should get a flex basis of 20%.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg version: 9.1.0

**Comment by ntsekouras** [comment] 2020-10-08 10:51
Hey @bfiessinger thanks for reporting this! 

@aristath I know you worked on `Columns` recently and also had some discussions with @ItsJonQ about widths and the handling of total `widths > 100`. Can you take a look in this and share your thoughts?

**Comment by aristath** [comment] 2020-10-08 10:59
Thank you for the ping @ntsekouras :+1: 

This is not new btw, it was always like that, and to be expected.
flex-basis doesn't need to total 100%, and recently we also added support for other units besides percentages.
A variant 25-50-25 will insert columns and set the to the widths defined, but these stay in the columns themselves. There is no mechanism for total-width calculation in the parent columns block, the browser just does its best to guess what to render based on the values defined.
If one wants the other columns to auto-scale the simplest solution is to delete their width values - in which case they'll use their initial value of `auto`.

**Comment by ntsekouras** [comment] 2020-10-08 11:13
Based on @aristath 's explanation, seems to me that the current approach is a good one, in the sense that the editor doesn't make `smart` choices for the user, as recalculating to `100` is a single use case. If we were to implement this and a user wanted to adjust only the adjacent column, with the new approach would have to change all the other widths as well.

This also affects the current support of `units besides percentages`, as there can be columns with different units and a calculation with `100` would be probably not `correct` (which unit to choose etc..). 

Do you think there is an alternative solution without involving so many `smart` changes from the editor? If not maybe we should close this issue, no?

**Comment by aristath** [comment] 2020-10-08 11:21
I don't think it should try to be smart... Maybe I really want to use sizes like 100% for the 1st column and 50% for the other 2. It will work just fine, % doesn't necessarily mean percentage of the total width :laughing:

**Comment by youknowriad** [comment] 2021-03-26 12:58
Closing as this works as intended. In fact the proposed behavior was how it worked originally and it was too confusing for users.

**Closed by youknowriad** 2021-03-26 12:58 UTC
Labels: [Block] Columns
