### ISSUE TITLE
Inserter: Reorder blocks in the Theme & Design sections

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#36547] opened 2021-11-16 20:14 UTC
Reorder so that the most common use cases are on top. 

Reference images: 
<img width="353" alt="Screen Shot 2021-11-16 at 3 04 20 PM" src="https://user-images.githubusercontent.com/5835847/142058442-e816ba7a-f18d-4b4c-90d0-8891d58048f8.png">

<img width="352" alt="Screen Shot 2021-11-16 at 3 04 33 PM" src="https://user-images.githubusercontent.com/5835847/142058633-72f21b33-34c6-47f7-bbee-2b4f813aa80c.png">

**Comment by mtias** [comment] 2021-11-16 20:56
For "theme" blocks, header, footer, navigation, post lists should all be coming ahead.

**Comment by ntsekouras** [comment] 2021-11-22 08:22
What blocks do you think should be prioritized for the `design` category?

**Comment by mtias** [comment] 2021-11-22 22:31
We probably need to move some of those in "design" to "theme" (site title, logo, etc).

**Comment by jameskoster** [comment] 2021-11-22 23:59
+1 to grouping all theme blocks together. Then we can consider hiding that entire category in the post editor.

**Comment by jameskoster** [comment] 2021-11-23 15:14
FWIW I find both "Theme" and "Design" to be a little blurry. I'm not sure the nuance will be interpreted so well by the average user. "Design" also feels a little loose as a definition... the arguments to classify the blocks therein can probably be made for the majority of blocks...

Here's the Design section with the Theme blocks removed:

<img width="349" alt="Screenshot 2021-11-23 at 13 45 33" src="https://user-images.githubusercontent.com/846565/143035474-c5929ed6-17ce-4999-9d85-e26ec9d68007.png">

Columns, Group, Row, Spacer, and Separator feel like Layout blocks and will see frequent use in both post and site editors.

Page Break and More Link feel like content formatting and will not feature in the Template Editor at all.

Buttons... I'm not sure, seems to be a bit of an outlier :)

All that said, would it make sense to rename "Design" to "Layout" and include the blocks above?

Then create a new section for Page Break / More Link that is only visible in the post editor.

<img width="349" alt="Screenshot 2021-11-23 at 13 59 16" src="https://user-images.githubusercontent.com/846565/143050801-54070cc6-3ccf-4584-969c-8b58adc7c336.png">

Then find a home for Buttons :)

**Comment by ntsekouras** [comment] 2021-11-25 08:10
I removed myself from assignee because my first approach [wasn't the one](https://github.com/WordPress/gutenberg/pull/36719#discussion_r754088181) wanted and I understand the issue is time sensitive.

I'll still try to find a better approach but If anyone has something better in mind, please try this out.

**Closed as completed** 2021-11-26 11:13 UTC
Labels: [Type] Task, [Status] In Progress, [Feature] Inserter, Needs Dev
