### ISSUE TITLE
Query Block: Add alignment controls

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28532] opened 2021-01-27 21:43 UTC
It could be useful to have alignment controls in the Query Block (or the nested Query Loop Block) for wide and full-width.

![image](https://user-images.githubusercontent.com/545779/106058080-60d7c580-60b6-11eb-8a2c-cbe71d46d170.png)

**Comment by ntsekouras** [comment] 2021-02-24 07:56
Duplicate of: https://github.com/WordPress/gutenberg/issues/27589

**Closed by ntsekouras** 2021-02-24 07:56 UTC
Labels: Good First Issue, [Block] Query, [Type] Enhancement
