### ISSUE TITLE
Toolbar doesn't move to selected widget reliably (on new Widgets Screen)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#28995] opened 2021-02-15 02:44 UTC
## Description
When you click on the Editor section of a Text Widget on the new Widgets Screen, the Block Toolbar doesn't move to the selected Widget.

Vid: https://share.getcloudapp.com/X6u991Dd

## Step-by-step reproduction instructions
1. Go to Appearance > Widgets
2. Click on a widget and edit it
3. Now click in the Editor of a different widget and notice the toolbar doesn't move to the selected widget

## Expected behaviour
When I click on a Widget, the Toolbar should move to the selected widget

## Actual behaviour
Toolbar doesn't move to selected widget

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 9.9.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac Mini
- Operating system: macOS Big Sur 11.2
- Browser: Firefox 85.0.2

**Comment by talldan** [comment] 2021-04-20 07:01
I can confirm this one. It specifically happens when clicking into the visual editor area of the text widget. I guess that it swallowing the focus event.

**Comment by noisysocks** [comment] 2021-04-27 05:16
This is incidentally fixed by https://github.com/WordPress/gutenberg/pull/30889 because the form will no longer appear unless selected.

**Closed** 2021-04-27 05:26 UTC
Labels: [Block] Legacy Widget, [Feature] Widgets Screen, [Type] Bug
