### ISSUE TITLE
Three issues when trying to edit links

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#14461] opened 2019-03-15 16:36 UTC
**Describe the bug**
I was trying to edit a link's text and ran across 3 different issues.

1. I can't select just a single word and edit it within the link.
2. Clicking outside the link and then arrowing over to select the word I want to change causes a series of link popover spasms. The popover keeps disappearing and reappearing with every key stroke.
3. When I do edit a single word in the link, the link doesn't stay associated to the new word and actually breaks the link into two different groups of linked words.

![links](https://user-images.githubusercontent.com/617986/54446843-2c96ce00-4705-11e9-9448-30274f8ce9c5.gif)

**To Reproduce**
1. Write a sentence.
2. Make several words into a link.
3. Try to edit one of the middle words within the link.

**Expected behavior**
1. I expected to be able to select a single word within the group of linked words. I'm able to do this with groups of bold or italicized words.
2. The popover should just remain open despite my keystroke movements if I'm within the group of linked words.
3. Editing a word should retain the link associated to the group.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox 65.0.1
- Gutenberg 5.2

**Comment by youknowriad** [comment] 2019-03-21 08:18
cc @ellatrix

**Comment by ellatrix** [comment] 2019-03-22 09:30
@mapk I cannot reproduce (1) and (2):

![link](https://user-images.githubusercontent.com/4710635/54813207-544ddf00-4c8d-11e9-9733-f227b6737990.gif)

**Comment by ellatrix** [comment] 2019-03-22 09:32
Oh, I _can_ reproduce (1) now in Firefox. But still not (3).

**Comment by ellatrix** [comment] 2019-03-22 09:39
For (1), in Firefox, it seems that this is an issue across different `contenteditable`-based editors. I have the same issue in TinyMCE. Unfortunately, there's no easy fix. The browser sets the selection after a double click, not us. Trying to recreate selecting a word after a double click is hard because word boundaries are different depending on your script. I would suggest not trying to fix this browser bug.

(2) I'll fix.

(3) I'm still trying to reproduce.

**Comment by ellatrix** [comment] 2019-03-22 09:41
Try to select a word in the link here: https://codepen.io/anon/pen/moaeQL. This proves it's a `contenteditable` bug in Firefox. :)

**Comment by ellatrix** [comment] 2019-03-22 09:50
I checked out `5.2.0` and I can now reproduce (3). It's fixed in `master` though, I'm not sure which commit exactly fixed it.

**Comment by mapk** [comment] 2019-03-23 03:56
Thanks for looking into this, @ellatrix!

1. It's a problem with FF, and not the editor.
2. You're working on it.
3. Fixed after 5.2 in master, excellent.

So looks like if 2 can be worked out in a PR, we can close this then. I appreciate your help.

**Comment by ellatrix** [comment] 2019-04-19 08:54
@mapk (2) has been fixed by @aduth in #14938. Would you be able to create an issue just for the Firefox problem? Then we can close this issue as it has mostly been fixed. Unsure if there's a good fix for it.

**Closed by ellatrix** 2019-04-19 08:54 UTC
Labels: [Type] Bug
