### ISSUE TITLE
wp.element.RawHTML is gone

### ISSUE THREAD

**Issue by Luke1982** [WordPress/gutenberg#14305] opened 2019-03-07 10:07 UTC
After testing an upgrade to 5.1 I noticed one of my custom blocks was broken. In that block, I used the RichText component and to be able to save the HTML tags that produces (for instance when you open a new line to save the <br> or to be able to save links without them being escaped) I saved the data as a child of the containing element wrapped into a new element of the RawHTML type.

The block validation now fails since the expected data has an empty containing DIV where the actual data has content, including HTML. Opening the console and looking in the global wp.element object I noticed the RawHTML element is simply gone!

**Comment by youknowriad** [comment] 2019-03-07 12:29
RawHTML is not gone, it's there, can you share a small block to reproduce the issue?

**Comment by Luke1982** [comment] 2019-03-07 14:29
I get the same error now without the 5.1 update. The entire page is uneditable all of a sudden without any changes being made, suddenly it decides to expect something else than it gets.

This is partly due to the documentation being so focussed on people that have a react development environment. I don't. I'm just a developer who writes old-fashioned JS for now, who finds the documentation on creating Gutenberg blocks horrible. Just some simple debugging on a block that is really, really simple takes me forever. Finding practical 'did you check this and that' lists is impossible.

Will get back on this after trying some more things but my above rant should be addressed in my opinion. Making the threshold for developers low seems crucial for the adoption of this technique

**Comment by rebmullin** [comment] 2019-03-13 16:28
I had to add `wp-element` to the dependency array in the enqueue script that I am using: 

`wp_enqueue_script( 'nav-script', get_template_directory_uri() . '/src/js/nav.js', ['wp-element'], 1 );`

It's been a little while since I've used wp so I'm not sure if there is a better way but for me this made `wp-element` available to this particular script.

**Comment by youknowriad** [comment] 2019-03-13 16:57
Yes, that's the way to go, anytime you use `wp.something` you should add `wp-something` as a dependency of your script.

**Comment by youknowriad** [comment] 2019-03-13 16:57
I guess we can close this issue now, thanks for the follow-up.

**Closed by youknowriad** 2019-03-13 16:57 UTC
Labels: [Status] Needs More Info

**Comment by Luke1982** [comment] 2019-03-13 18:15
This issue is no longer relevant since I opened it with a wrong description. I still have pages that stop working for no reason, even those that don't include any custom blocks. By the way, the custom block-pages were working before, no need to include separate JS.

Will get back here when I have a more detailed description of the problem but something's off.

**Comment by Luke1982** [comment] 2019-03-13 18:39
OK, hold the presses. Come and kick me in the head, spit on me and call me stupid, because it most definitely **was** a faulty plugin. The Caldera form plugin was the culprit here it seems.

**Comment by youknowriad** [comment] 2019-03-14 08:27
I'm glad you got it fixed :) 👍
