### ISSUE TITLE
block.json not loaded on block plugin dynamic load

### ISSUE THREAD

**Issue by KevinBatdorf** [WordPress/gutenberg#38494] opened 2022-02-03 16:25 UTC
### Description

This is hard to reproduce as it requires finding a block plugin that breaks. As it requires the block to be approved and on the repository. I imagine it could be faked in a dev example but I'm just reporting it at this point.

If a block plugin has its default attributes set in block.json _only_, (including title), will get errors on quick install and ask the user to refresh the page. Additionally, all the default attributes will be `undefined`

### Step-by-step reproduction instructions

1. Register a block in JS with `registerBlockType()` but leave off the title.
2. Set the title in block.json
3. Publish the plugin to .org
4. Search for your block
5. Press to install
 

### Screenshots, screen recording, code snippet

Unfortunately I don't have screenshots of it erroring out (I fixed it right away by importing the json config and merging it via Object.assign), but I mentioned the error to a colleague and they confirmed their block title was missing and the same error occurred. 

![Screen Shot 2022-02-03 at 11 05 34 AM](https://user-images.githubusercontent.com/1478421/152381134-d21d3e77-75f9-484a-9eed-2c37f2962935.png)

### Environment info

I was on WP 5.9 without the Gutenberg plugin installed. 

I can _not_ confirm whether the issue exists in the Gutenberg plugin as I fixed my block plugin already so can't reproduce the issue to test (without working on the fix)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment] 2022-02-07 16:05
Ooh! This is interesting! Thanks for flagging this @KevinBatdorf! In the case of the [Super List Block](https://wordpress.org/plugins/superlist-block/), which also has this error when installing, I can confirm I have the title in the index.js file as well, but I don't have the default attributes. I'll test the attributes part a bit later today, because that's pretty much what I'm seeing – default attributes end up `undefined`.

**Comment by aurooba** [comment] 2022-02-07 16:17
Update! I _just_ tested importing the attributes into the function from block.json, and that 100% fixed the problem.

My approach:

```js
import metadata from "./block.json";

const { name, attributes } = metadata;
```

and then 

```js
registerBlockType("createwithrani/superlist-block", {
	/**
	 * add name and attributes here
	 */
	title: __(name, "superlist-block"),
	attributes,
	icon,
	edit,
	save,
	example,
});
```

But, ideally, you shouldn't have to do that. :)

**Comment by ryelle** [comment] 2022-02-07 21:05
This is a duplicate of #38245 - as mentioned, the workaround is to set a title in `registerBlockType`, or load in the metadata from `block.json`.

Personally, I use a method like this:

```js
import settings from '../block.json';

registerBlockType("ryelle/fake-block", {
	...settings,
	edit: () => …,
	save: () => …
} );
```

https://github.com/ryelle/grainy-gradients/blob/028cb7d49d8b4050746385f3c8a5c17b156322cc/src/index.js#L15-L20

**Closed as completed** 2022-02-07 21:08 UTC
Labels: [Status] Duplicate, [Feature] Block Directory

**Comment by aurooba** [comment] 2022-02-07 21:10
It's not just title related though. Blocks fail to load if they have default attributes that are not then added into block.json (more info in #38588). The `...settings` approach definitely fixes that though. :)

**Comment by ryelle** [comment] 2022-02-07 21:12
So, is this issue different than both #38588 & #38245, or do both of those cover it?

**Comment by aurooba** [comment] 2022-02-07 21:14
#38588 covers it! :) Thanks @ryelle (I saw your comment over there after, my bad!)
