### ISSUE TITLE
Editing link "Open link in new tab" not working

### ISSUE THREAD

**Issue by redpay** [WordPress/gutenberg#12548] opened 2018-12-03 14:02 UTC
**Describe the bug**
When I edit a link and I tick the box "Open link in new tab" AND then click "Update", the page scrolls up and it nevers updates.

**To Reproduce**
1. Go to 'Any link on a post you are editing'
2. Click on 'Edit link and tick box "open link in new tab'
3. Click on 'Update'

**Expected behavior**
Page scrolls up, link does not open in new tab when you check the page, checkbox remains unticked

**Screenshots**
![ashampoo-wordpress2](https://user-images.githubusercontent.com/38899074/49377888-99b0c580-f70b-11e8-8ddb-b3ff4e68ec9b.jpg)
![ashampoo-wordpress](https://user-images.githubusercontent.com/38899074/49377906-a2a19700-f70b-11e8-8fa8-940750600647.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave browser/Chrome based
 - Version: Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

**Additional context**
- Gutenberg 4.6.1

**Comment by designsimply** [comment] 2018-12-03 14:42
Thanks for the report. This looks like a duplicate of https://github.com/WordPress/gutenberg/issues/7932 to me. Please let me know if you're seeing this as a separate case though!

Aside: temporary workaround is to edit twice (an update like that seems to work for me in testing if I do it twice in a row).

**Closed by designsimply** 2018-12-03 14:42 UTC
Labels: [Block] Classic, [Status] Duplicate, [Type] Bug
