### ISSUE TITLE
When previewing themes the style of the widgets don't match

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#32629] opened 2021-06-11 16:17 UTC
When previewing themes using the Customizer the style of the widgets in the widgets editor sidebar is the one of the currently active theme.

### To reproduce:

1. Have WordPress 5.8 and latest Gutenberg
2. Have TwentyTwenty and TwentyTwentyOne installed
3. Set TwentyTwentyOne  as active
4. Go to Appearance > Customize
5. From the top bar of the Customizer header choose Previewing theme > Change
6. Pick Installed themes
7. For TwentyTwenty click Live Preview
8. After the preview is complete go to Widgets

### Expected behavior:

The styles should match 

### Screenshot

<img width="764" alt="style-mismatch" src="https://user-images.githubusercontent.com/107534/121717097-7d1a5300-cae9-11eb-83ef-0d292b7f27ba.png">

**Comment by noisysocks** [comment] 2021-06-15 02:40
What precisely do you mean by "they should match". Is this a dupe of https://github.com/WordPress/gutenberg/issues/26163?

**Comment by draganescu** [comment] 2021-06-17 06:56
It's not a dupe I believe. The problem here is that the editor in the Customizer styles the widgets and blocks to match the active theme not the one being previewed. If we eventually drop editor styles from the Widgets editor, hence the Customizer as well, then this issue won't exist anymore.

**Comment by noisysocks** [comment] 2021-06-23 03:55
Ah, I see! The problem is that the Legacy Widget block preview renders using the **site's active theme** and not the theme being previewed in the current changeset. Thanks for clarifying.

**Comment by noisysocks** [comment] 2021-08-30 05:57
I wonder if we should disable the Legacy Widgets "preview mode" in the Customizer. It's not very useful because there is already a preview on the right hand side, and it's confusing that the two previews look different. What do you think, @critterverse?

**Comment by critterverse** [comment] 2021-08-30 22:07
>I wonder if we should disable the Legacy Widgets "preview mode" in the Customizer.

Could we disable preview mode only when live previewing a different theme? I'm not opposed to making that change universally, just curious what the other possibilities are.

**Comment by noisysocks** [comment] 2021-08-31 05:21
We most certainly could!

**Comment by draganescu** [comment] 2021-08-31 13:20
I have heard (but unfortunately did not bookmark) others suggesting the same as an UX improvement for the customizer.

**Comment by draganescu** [comment] 2022-02-08 11:38
@noisysocks even if we disable legacy preview mode this is not solved since my testing appears to be using a search block, not some legacy widget. The block editor needs to reload its CSS when we preview another theme. I have no idea if this can be done on the fly.

**Comment by noisysocks** [comment] 2022-02-14 00:59
Right. So in the original comment's screenshot, that's a Search block and not a Legacy Widget block? And you would expect the search button to appear red, not black?

**Comment by noisysocks** [comment] 2022-02-16 06:50
Related: https://github.com/WordPress/gutenberg/issues/33264

**Comment by draganescu** [comment] 2022-02-16 10:29
> So in the original comment's screenshot, that's a Search block and not a Legacy Widget block? And you would expect the search button to appear red, not black?

Yes.

**Comment by noisysocks** [comment] 2022-02-17 03:53
Got it 😀 thanks for clarifying. I mistakenly thought this was about the Legacy Widget block.

So, this happens by design. We don't load editor styles in the Customizer widgets block editor (that is: it's equivalent to turning _Use theme styles_ off in the post block editor preferences) because there is already a preview of what the content will look like on the right hand side of the screen. Maybe it's something we'll revisit in the future but for now this is working as expected.

**Closed as completed by noisysocks** 2022-02-17 03:53 UTC
Labels: [Type] Bug, [Feature] Widgets Customizer

**Comment by draganescu** [comment] 2022-02-24 10:54
Yes, excellent, I believe the problem was found when we did load the styles.
