### ISSUE TITLE
Gutenberg doesn't work anymore after installing the update

### ISSUE THREAD

**Issue by Visdief** [WordPress/gutenberg#9515] opened 2018-08-31 16:12 UTC
Hello,

A couple of minutes ago 3.7.0 installed. 
And afther that, Gutenberg does not work anymore.

I get the following report (in Dutch, look at the attached file). Something like 'The editor has encountered an unexpected problem.'

[Issue Gutenberg.docx](https://github.com/WordPress/gutenberg/files/2340773/Issue.Gutenberg.docx).

<img width="909" alt="screen shot 2018-08-31 at 10 45 58 am" src="https://user-images.githubusercontent.com/1119271/44925251-20b86100-ad0b-11e8-8131-73099adc413c.png">

Please, can this problem been solved quickly?

Thanks a lot.

Sincerey,

Jako

**Comment by Visdief** [comment] 2018-08-31 16:37
I now see that only the Gutenberg editor for messages has this problem. The Gutenberg editor for pages works well. Very strange. I haven't any other details about the problem. Sincerely, Jako

**Comment by srw985** [comment] 2018-08-31 16:40
Same problem here. Cannot edit posts or make new posts in Gutenberg since today's update.

Pages somehow work fine.

Urgent fix needed, will try rolling back versions

**Comment by ecuencac** [comment] 2018-08-31 16:48
I have the same problem. I can write in pages but I can't create new post.
Is a fail with the version?

**Comment by designsimply** [comment] 2018-08-31 16:55
Thank you for reporting this! I am not seeing the same problem when I test so I am hoping you will help provide some additional info. First, can you make sure all of your other plugins are up-to-date?

Can you check to see if you find any errors in your browser console when you see the error happen? If you are using Chrome, you can see the console by going to View > Developer > JavaScript Console. If you are using another browser it should be something similar and if you can't find the console, let me know which browser you are using and I will look up instructions.

Another very helpful troubleshooting step will be to check for plugin conflicts. If this is possible for you, you can do it by temporarily turning off all plugins and trying a new post again. If it works without error at that point, you can turn on each plugin one at a time and check to see which one is the source of the conflict for this case.

**Comment by designsimply** [comment] 2018-08-31 17:06
I have been trying more tests to see if I can trigger the same problem and I haven't been able to so far. My first tests have been with WordPress 4.9.8 and Gutenberg 3.7. I tried testing Yoast SEO 7.8 and 8.1 and didn't see problems with either of those. I will keep testing and please do let me know if you find any additional information about console errors that might provide some clues!

**Comment by youknowriad** [comment] 2018-08-31 17:32
I guess this is the Yoast issue raised in other issues. See here for a workaround https://github.com/WordPress/gutenberg/issues/9506#issuecomment-417688790

I'm closing, let me know if it's a different issue and we'll reopen.

**Closed by youknowriad** 2018-08-31 17:32 UTC
Labels: [Status] Needs More Info

**Comment by GlennMartin1** [comment] 2018-09-03 10:42
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and (if applicable) deactivate and uninstall the workaround, and confirm the issue is addressed.

**Comment by Visdief** [comment] 2018-09-03 15:52
Thank you very much! Gutenberg works again!


Op ma 3 sep. 2018 12:42 schreef GlennMartin1 <notifications@github.com>:
