### ISSUE TITLE
Contributor role: No save button

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#11946] opened 2018-11-15 22:35 UTC
**Describe the bug**
If the user has the role contributor, there is no save button in the toolbar.
<img width="466" alt="bildschirmfoto 2018-11-15 um 23 26 03" src="https://user-images.githubusercontent.com/695201/48586027-eb490a00-e92e-11e8-9dad-d9f0e07ce475.png">

Classic Editor:
<img width="301" alt="bildschirmfoto 2018-11-15 um 23 34 41" src="https://user-images.githubusercontent.com/695201/48586051-0c115f80-e92f-11e8-948e-a65cfd49b85f.png">

**Comment by youknowriad** [comment] 2018-11-15 22:38
I don't think that's a bug. I do recall this being the desired behavior at least for posts already submitted for a review. I don't recall the details though, maybe @imath does?

**Comment by imath** [comment] 2018-11-16 04:15
@youknowriad @Soean Yes to me it's not a bug. Once a post is submitted for review by a contributor, here's how look the publishing metabox of the classic editor.

![publishing-metabox](https://user-images.githubusercontent.com/1834524/48597415-f5cec800-e95d-11e8-8167-950d87fb5a46.png)

In Gutenberg the behavior is the same. If the post has not yet been submitted for review by the contributor, the "Save Draft" button is available:

![top-bar](https://user-images.githubusercontent.com/1834524/48597463-33335580-e95e-11e8-9c51-1a2e4af73a86.png)

As soon as it has been submitted for review, only the Submit for review button is displayed.

![top-bar-2](https://user-images.githubusercontent.com/1834524/48597514-81485900-e95e-11e8-9f11-64228cda8ef7.png)

**Comment by youknowriad** [comment] 2018-11-16 07:51
Thanks for the input, I'm closing now.

**Closed by youknowriad** 2018-11-16 07:51 UTC
Labels: UI Components, [Type] Bug
