### ISSUE TITLE
Resizable Off Boundary Dragging Loses Focus

### ISSUE THREAD

**Issue by onuro** [WordPress/gutenberg#16449] opened 2019-07-07 22:13 UTC
**Describe the bug**
Ok so this is happening with blocks using Resizable component, mostly with spacer to be specific. When you start dragging the block's resizable handle beyond the block's boundaries up or fast down, you go from resizing the block to multi-selecting blocks.

**To reproduce**
1. Insert a spacer block in between other blocks
2. Start dragging the resize handle up or speedy down
3. Experience uh oh.

**Expected behavior**
Handle and the block should stay on focus at all times of dragging state.

**Issue in Action**
 
![Screen Recording 2019-07-08 at 01 07 AM](https://user-images.githubusercontent.com/645713/60774498-4b3e2c00-a11d-11e9-9fd1-8833e73f5656.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra
 - Browser Chrome 
 - Version 75.0.3770.100

**Additional context**
- Using Gutenberg 6.0.0
- Note: Issue only happening with the GB plugin active.

**Comment by ehti** [comment] 2020-04-20 22:20
Hi @onuro,

As of Gutenberg 7.9.1 I'm not able to reproduce it - looks like it shouldn't be an issue anymore. Closing, but if you're still running into it please ping. :)

Thanks!

**Closed by ehti** 2020-04-20 22:20 UTC
Labels: [Block] Spacer, [Feature] Blocks, [Type] Bug
