### ISSUE TITLE
'corrupted' reusable block

### ISSUE THREAD

**Issue by norlink** [WordPress/gutenberg#29852] opened 2021-03-13 19:13 UTC
## Description
I had a reusable block 'corrupt' on me. The block itself lost everything in it and then caused issues on the front end

## Step-by-step reproduction instructions
I was bringing reusable blocks into page on a site I'm developing. When I saved, I noticed it had check boxes next to a number of reusable blocks, including some that weren't even on that page. After that, my css styles from GenerateBlocks were no longer working on the page I was working on, and the home page (the two pages that particular reusable block was added to). Other pages were fine.

Deleting the block from reusable blocks didn't solve the issue. Removing the block on the page going through Outline and removing did. No HTML rendered in the source code where that block was and the block itself appears empty except for the title. I'm not sure where in the database the info is saved to see what's in the table row, if anything

## Expected behaviour
Only blocks that were edited AND on the page were triggered for saving. 

## Actual behaviour
A number of blocks thought they needed to be updated without actually being on the page. When recording the the video, I created a test page and both times I went to save, it showed a different reusable block needed to be saved that were not on the page. Both videos linked below. I didn't save either time as I was afraid of messing up more reusable blocks

## Screenshots or screen recording (optional)
[https://share.getcloudapp.com/6quQg41m](https://share.getcloudapp.com/6quQg41m)
Shows the issue of what was happening on the front end with the 'corrupted' block

[https://share.getcloudapp.com/BluY86qo](https://share.getcloudapp.com/BluY86qo)
Shows an unused reusable requesting to be saved, a different block though from the previous video

## WordPress information
- WordPress version:  5.7
- Gutenberg version: Not installed/what's in 5.7
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop 
- Operating system: Windows 10
- Browser: Chrome 89.0.4389.82

**Comment by talldan** [comment] 2021-03-19 04:32
This is definitely unusual. Did the 'About Barb' reusable block get inserted at any point during the session?

The only other thing I can think of is that the 'About Barb' reusable block is inside the 'CTA' one. Though it looks empty and shouldn't need saving.

Styling issues are also unusual.

**Comment by norlink** [comment] 2021-03-19 18:06
No. I created the page to record the video. Added a container and the headline and then went to save. I never did anything with reusable blocks. The first time it showed I believe the Newsletter reusable block needing to be saved and then the second time it wanted to save a different reusable block. I didn't save either as the last time it happened is when all the problems started happening.

I ended up reverting back to WP5.6.2 as I need to get this site launched for a client.

I did grab a backup of the site prior to reverting back in case I needed to test out anything on it. I can spin it up on a subdomain.

**Comment by talldan** [comment] 2021-06-22 05:26
Hi @norlink, sorry for the amount of time taken to reply to you.

I've had another go at testing this one on with the Gutenberg plugin and GenerateBlocks, and couldn't. It might be something specific about your Reusable Block.

We also discussed the issue in a triage session on slack (https://wordpress.slack.com/archives/C02QB2JS7/p1624338381331400), and other folks couldn't reproduce.

I know you mentioned downgrading the site, but is this something you've experienced again since then?

I'll close the issue, which is the usual step if we can't reproduce, but if we can narrow this down it can always be reopened or a new issue reported.

**Closed by talldan** 2021-06-22 05:26 UTC
Labels: Needs Testing, [Block] Block, [Feature] Reusable Blocks
