### ISSUE TITLE
Table cell widths don't resize properly after inserting column

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#4026] opened 2017-12-15 01:27 UTC
## Issue Overview
When you first add a table block, it gives you a 2x2 table. After entering data in each of the cells they automatically adjust their width to accommodate the data.

So, as an example, if you have similar data in each column, you'll end up with a table that automatically adjusts so that each column is 50% width.

![screenshot_552](https://user-images.githubusercontent.com/2078245/34022188-e691cb32-e191-11e7-82de-e6458750401a.png)

After inserting a column, the table stops automatically adjusting the cell widths, thereby breaking the formatting. Since its impossible to specify the column widths unless you edit the table in HTML mode, it makes it impossible to get a nice, evenly formatted table

![screenshot_551](https://user-images.githubusercontent.com/2078245/34022374-fdd929f6-e192-11e7-8aae-c681aaab0cea.png)

## Steps to Reproduce (for bugs)
1. Insert Table block
2. Add similar data to each cell
3. Insert new column between the existing columns
4. Insert more data in new cell

## Expected Behavior
I expect the table cells to automatically adjust to fit the content properly, thereby giving you evenly formatted columns.

## Current Behavior
Tables cells don't adjust evenly after inserting a column

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)_

**Comment by danielbachhuber** [comment] 2018-01-23 22:04
Related #4027

**Comment by jeffpaul** [comment] 2018-03-15 18:38
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521135466000462)._

**Comment by jeffpaul** [comment] 2018-03-15 18:38
Seems related or potentially a duplicate of #4027

**Comment by maddisondesigns** [comment] 2018-03-16 01:52
@jeffpaul I originally raised #4027 because of the use of pixels in the markup on the front-end. i.e. when the theme displays the page. With that said though, it does also affect the edit screen because the table displayed in the block also uses pixels, which it shouldn't.

The issue raised here is because the table columns don't resize properly when inserting a new column, which is a different problem altogether.

Please keep them both open. Thanks.

**Comment by karmatosed** [comment] 2018-07-11 10:40
Closing as including to fix this in one master table issue here: https://github.com/WordPress/gutenberg/issues/6923

**Closed by karmatosed** 2018-07-11 10:40 UTC
Labels: Blocks, Good First Issue, [Type] Bug
