### ISSUE TITLE
Cursor jumps to start of block when clicking it

### ISSUE THREAD

**Issue by hochitom** [WordPress/gutenberg#12380] opened 2018-11-28 11:13 UTC
**Describe the bug**
if i want to edit content of an text block, and click on a word in the middle of the block, the cursor jumps to the first word instead of being there where i clicked. this happens since version 4.5, before it was right where i clicked. this is quite annoying bc i now must click on a word twice to edit content.

**To Reproduce**
1. create or open a post with a few text blocks
2. Click on one word in the middle of the text block
3. cursor is now at the beginning instead of the selected word

**Expected behavior**
instead of being at the beginning of the block, the cursor should be at the selected position

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - Browser: firefox
 - Version 63.0.1

**Additional context**
- wordpress 4.9 and gutenberg 4.5.1

**Comment by markjaquith** [comment] 2018-11-28 16:57
Cannot duplicate with Firefox 63.0.3, macOS 10.14.1, and Gutenberg 4.5.1 @ `e4fd51cb535e8300b41`

**Comment by designsimply** [comment] 2018-11-28 17:30
I was able to replicate, see https://github.com/WordPress/gutenberg/issues/11573#issuecomment-442533839.

Closing as a duplicate of #11573.

**Closed by designsimply** 2018-11-28 17:30 UTC
Labels: Writing Flow, [Status] Duplicate, [Type] Bug
