### ISSUE TITLE
Table block: validateDOMNesting warnings

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1937] opened 2017-07-18 17:56 UTC
Create a new post in Gutenberg:
- add a title (optional)
- insert a table
- enter something in the default 4 cells
- save the post
- refresh the page, or navigate away and then re-open the post in Gutenberg

I get this warnings from `validateDOMNesting` that seems completely wrong to me:
```
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tbody> ...
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tr> ...
```

Switching to text mode, the actual markup is something like this:
```
<!-- wp:core/table -->
<table class="wp-block-table">
    <tbody>
        <tr>
            <td>hello</td>
            <td>hello</td>
        </tr>
        <tr>
            <td>hello</td>
            <td>hello</td>
        </tr>
    </tbody>
</table>
<!-- /wp:core/table -->
```

Yes, there are spaces for indentation but I wonder why these are considered  something to warn about.

**Comment by EphoxJames** [comment] 2017-08-01 06:54
I could probably make the table block remove the spaces (as I did with the serialization test) but it seems to me that the warning is incorrect.

Any idea what library is doing the validation and producing the spurious warnings?

**Comment by karmatosed** [comment] 2017-09-04 19:48
@afercia could we have some feedback on the library please?

**Comment by afercia** [comment] 2017-09-05 06:52
@karmatosed @EphoxJames `validateDOMNesting` is part of React and it's meant to (partially) catch invalid nesting. See https://github.com/facebook/react/blob/3f6e8d28031c85dd3d101e6f259db572d82fe1a1/src/renderers/dom/shared/validateDOMNesting.js#L23

I'd suggest to check if there are spaces between the table elements, for example spaces between `<tr>` and `<td>` or similar.

**Comment by mtias** [comment] 2017-11-20 11:49
What's the status of this one?

**Comment by aduth** [comment] 2018-03-06 15:10
I can still reproduce this given the steps from the original comment.

**Comment by designsimply** [comment] 2018-07-09 22:54
I tested with Firefox 61.0.1 on macOS 10.13.5 just now and I was not able to see any `validateDOMNesting` warnings in the browser console after following the testing steps provided. Here's how my screen looked after my test:

![screen shot 2018-07-09 at mon jul 9 4 51 16 pm](https://user-images.githubusercontent.com/1119271/42479957-7d6f3d52-8398-11e8-95e9-54402adf5a4f.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13895&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5. Note: I also tested with Chrome 67.0.3396.99 on macOS 10.13.5 with the same result.</sup>

**Comment by designsimply** [comment] 2018-07-09 22:57
I am closing this issue because it has been about a year since it was first raised and because I haven't been able to reproduce the problem in testing. I also know that the table block has had some recent updates and this issue may have been fixed as part of that work. If I've missed something in my testing steps, please let me know and I will re-test and re-open!

**Closed by designsimply** 2018-07-09 22:57 UTC
Labels: Blocks, [Type] Bug
