### ISSUE TITLE
Reusable block can't be converted to a regular block

### ISSUE THREAD

**Issue by Sven74Muc** [WordPress/gutenberg#26421] opened 2020-10-23 13:33 UTC
I have 2 different reusable blocks which worked fine in the past.
When I add them now, I can't convert them to a regular block. 

I have Gutenberg 9.2.1 installed.
Rolled back to 9.2, the same issue.
Rolled back to 9.1.1, everything is working again.

So starting with 9.2. there is something breaking the "convert to a regular block" function to make the block editable.

**Comment by tellthemachines** [comment] 2020-10-26 03:14
I can't reproduce this with Gutenberg 9.2.1 on WP 5.5.1. Tried with existing buttons and image reusable blocks. Also tried creating a reusable block and converting back to a regular one. All working as expected.

@Sven74Muc it would be great to have some more details, such as which WP version you're on and which types of block you're having issues with. Would also be good to know if you have any plugins installed that may be causing this.

**Comment by Sven74Muc** [comment] 2020-10-26 13:17
Ok, my fault, didn't checked it on a blank installation first... SORRY

However, I found it. It is working with the core Gutenberg blocks. I have the issue just with the following blocks:

https://de.wordpress.org/plugins/ultimate-addons-for-gutenberg/

So tacking one of the block, make it reusable and then try to convert it back isn't working here.

The point is what has changed in Gutenberg that "external" blocks do not work any longer as they should? Do the plugins need to change or is it better to solve it on the Gutenberg end?

**Comment by bfintal** [comment] 2020-12-16 03:45
Our blocks are having this issue as well. We did some investigation and here's our findings:

These steps show the error:
1. add a Stackable blockquote block (or any one of our blocks)
2. convert to reusable block (**don't press save**)
3. add the the newly added reusable block
4. press the convert to regular block = **error**

But, if you click on the save button, the error goes away:
1. add a blockquote block
2. convert to reusable block (**press save**)
3. add the the newly added reusable block
4. press the convert to regular block = **no error**

Here's the error:
```
Uncaught (in promise) TypeError: document.substr is not a function
```
![image](https://user-images.githubusercontent.com/1033611/102302424-fcdcc000-3f93-11eb-8390-cbe639868050.png)

Seems like core blocks don't encounter this.

**Comment by talldan** [comment] 2020-12-16 04:59
Thanks @bfintal, I can reproduce this using your steps.

From what I can tell, the issue seems to be here:
https://github.com/WordPress/gutenberg/blob/694fe1114100747d154d78e5df263c4f9ef1873c/packages/reusable-blocks/src/store/controls.js#L71

`reusableBlock.content` is a function instead of a string, so `parse` chokes on it. Not sure why it only happens with particular blocks (especially those from stackable).

**Comment by bfintal** [comment] 2021-01-10 08:42
A few more findings. I tried the same steps I previously gave against other custom blocks provided by other block plugins and I'm encountering the same error. So this isn't something only with our blocks. I mostly tried icon blocks from these:
* Kadence
* UAG
* Qubely
* Otter
* Stackable

Not sure why, but I found that Getwid blocks don't suffer from this.

@talldan, I'm not sure what this means but another difference in that line is that the `reusableBlock.blocks` property is present when `reusableBlock.content` is a function, when the error appears. But when there's no error, `reusableBlock.blocks` isn't present.

**Comment by bfintal** [comment] 2021-01-10 09:09
@talldan Okay I think I found what's triggering the issue. Across all my blocks, I generate a unique class attribute for the block based on the client Id that's only generated once for the block. I generate this unique class using this HOC:

```js
const withUniqueClass = createHigherOrderComponent(
	WrappedComponent => class extends Component {
		static defaultProps = {
			attributes: {},
			clientId: '',
			setAttributes: () => {},
		}

		componentDidMount() {
			const {
				attributes, setAttributes, clientId,
			} = this.props
			const newUniqueClass = createUniqueClass( clientId )

			if ( typeof attributes.uniqueClass === 'undefined' || attributes.uniqueClass !== newUniqueClass ) {
				setAttributes( { uniqueClass: newUniqueClass } )
			}
		}

		render() {
			return (
				<WrappedComponent { ...this.props } />
			)
		}
	},
	'withUniqueClass'
)
```

I use the above HOC with my `edit` function:

```js
export default compose(
	withUniqueClass,
)( edit )
```

The issue seems to be coming from this line `setAttributes` in the HOC:

```js
setAttributes( { uniqueClass: newUniqueClass } )
```

When I change it to this, the issue seems to go away:

```js
this.props.attributes.uniqueClass = newUniqueClass
```

So it seems that calling `setAttributes` is somehow causing the issue.

**Comment by covertnine** [comment] 2021-01-13 16:57
Having this same issue on some of our blocks as well. We have quite a few references to SetAttributes in our code, so I'm hoping there's a fix for this vs. re-factoring a ton of code.

**Comment by Alexius08** [comment] 2021-01-23 05:06
Our blocks also suffer from this issue. As @bfintal noted, newly-created reusable blocks don't have this issue as long as the second set of steps are followed. However, it happens to old reusable blocks no matter which approach is used.

We save the block's clientID into an attribute of each block, and setAttributes worked perfectly fine for that purpose in Wordpress 5.5. In Wordpress 5.6, it stopped working when reusable blocks are converted into regular blocks. We tried modifying the attribute directly instead of using setAttributes for that purpose. Most of the time, it works, but there are some cases where it doesn't. Do we have an event listener or anything else that could detect when a conversion happens?

**Comment by yolinfl** [comment] 2021-01-28 12:01
I have this problem with the blocks of PublishPress and Kioken. Any idea when this issue will be solved?

**Comment by yolinfl** [comment] 2021-02-01 10:13
I have downgraded to 5.5.3 and now it works as it should.
Or, as work around you can edit the reusable block and save it again, then you are able to convert it to a normal block.

**Closed** 2021-02-26 01:21 UTC
Labels: [Feature] Reusable Blocks, [Status] In Progress, [Type] Regression

**Comment by ckpinguin** [comment] 2021-04-25 18:43
Maybe I'm mistaken, but I don't have any option "convert to regular" block an ANY reusable block (be it standard or 3rd party)?
