### ISSUE TITLE
Lazy load authors in the post editor

### ISSUE THREAD

**Issue by rolf-yoast** [WordPress/gutenberg#48069] opened 2023-02-14 12:57 UTC
## What problem does this address?
At the moment the amount of authors are set to max 50 authors in the author selector. If you've got a website with more authors you can't select them without filtering the query and editing it.

Another problem is that if you've got a big site with a lot of users loading 50 users every time you edit a post this can be a pretty heavy query.

## What is your proposed solution?
Only load 20 users and lazy load more users if you scroll down in the select field.

**Comment by ghost** [comment] 2023-02-14 16:43
@rolf-yoast Thanks for sharing this issue. Are you referring to the Post Author block, or the select input in the Post Summary?

**Comment by skorasaurus** [comment] 2023-02-14 16:56
might be a duplicate of https://github.com/WordPress/gutenberg/issues/27103 and/or https://github.com/WordPress/gutenberg/issues/15994

**Comment by rolf-yoast** [comment] 2023-02-15 08:34
It was the select input box and @skorasaurus is right. They are duplicates of those 2.

**Comment by skorasaurus** [comment] 2023-02-15 15:44
thank you for the response @rolf-yoast . You can follow either issue for its progress.

**Closed as completed by skorasaurus** 2023-02-15 15:44 UTC
Labels: [Status] Duplicate
