### ISSUE TITLE
Impossible to copy/paste text into a list

### ISSUE THREAD

**Issue by MVColombie** [WordPress/gutenberg#36120] opened 2021-11-01 15:38 UTC
### Description

It's impossible to copy/paste a text into a list. You should be able to copy one or more words from a paragraph and paste it into a list.

### Step-by-step reproduction instructions

1/ Create a paragraph
2/ Create a list
3/ Copy one or more words of your paragraph 
4/ Try to paste it into the list

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/33600764/139719341-8a6c1b31-f42a-40fb-96a5-b100a488d193.mov

### Environment info

WordPress v5.8.1
Twenty Twenty One  v1.4
Firefox v93.0
Mac OS BigSur 11.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2021-11-01 17:37
👋 Thanks for the issue. I couldn't reproduce this though. Can you share a video or some more details about this?

**Comment by MVColombie** [comment] 2021-11-01 18:10
Hi @ntsekouras sorry video didn't load first time. You'll find the video up there.

Difficult to say more, it's quite basic issue and don't know what to add ? It's impossible to copy a word in a paragraph and then paste it in a list.

**Comment by ntsekouras** [comment] 2021-11-02 09:59
TBH I had tried with the shortcuts and now tried with `right click` as well and with different themes. Still can't reproduce though.. I'll leave the `needs testing` label for other to try to reproduce as well..

**Comment by annezazu** [comment] 2021-11-12 20:06
I just tried to test this with Gutenberg 11.9, WordPress 5.8.2 and couldn't replicate. I'm going to close this out as a result for now!

https://user-images.githubusercontent.com/26996883/141528140-11e303f9-e46e-45d9-938c-727b3e371b31.mov

**Closed as completed by annezazu** 2021-11-12 20:06 UTC
Labels: Needs Testing
