### ISSUE TITLE
Spaces between paragraphs lost for a long post in Hebrew

### ISSUE THREAD

**Issue by nirstern** [WordPress/gutenberg#10389] opened 2018-10-07 18:24 UTC
**Describe the bug**
I wrote long post in Hebrew, right to left. After publishing, all the spaces between paragraphs lost. All the text of the post became one very long paragraph. Windows 10, 8gb memory.

**Comment by carladoria** [comment] 2018-10-26 20:20
I wasn't able to reproduce this on Chrome, Mac OS High Sierra, 10.13.6 
I can see the spaces on the post and on the published post:
![test](https://user-images.githubusercontent.com/23703267/47590648-f960c780-d93a-11e8-8da7-ff4306289386.jpeg)
Published:
![test 2](https://user-images.githubusercontent.com/23703267/47590659-febe1200-d93a-11e8-8459-8b66c75d4e6f.jpeg)

**Comment by nirstern** [comment] 2018-10-26 21:06
I was using Edge

**Comment by nirstern** [comment] 2018-10-26 21:09
That was the post

https://nirsternaristotle.wordpress.com/2018/10/04/58/


I used Edge explorer

**Comment by SiobhyB** [comment] 2018-11-30 16:46
We had another report from a WordPress.com user who was editing their posts on Chrome version 70.0.3538.110 (Official Build) and Windows 8.1. Their site is vereduntold.wordpress.com and the spaces were lost when they edited their latest post on two separate occasions. They've now switched back to the classic editor, and the issue isn't continuing there.

**Comment by waviaei** [comment] 2018-12-09 20:34
I tested and found same result as @carladoria -- spaces between the paragraphs are visible on editor, preview, and published post. Test was done in:

- Mac OS Mojave 10.14.2
- Chrome 70.0.3538.110
- WordPress 5.0
- theme: Twentynineteen

The step I took to test was:

1. use paragraph block
2. paste Hebrew text
3. hit [enter] to move to next block
4. repeat steps 1 to 3 twice

@nirsten Could you let us know following.
- which block did you use -- paragraph? classic?
- what is the exact step did you use -- same as above? or different?
- which theme did you use?

**Comment by nirstern** [comment] 2018-12-09 20:57
hi

my theme is
Franklin by Michael Burrows <http://www.wpmultiverse.com/>

i don't have more answers. i used the new editor only once and i am not
familiar what is paragraph etc. . it was a long post, about 30 A4 pages in
word. lot of work. i wrote it in the editor (not copy-paste from another
app)
I was so panic so i did not try again. my posts are only simple text so i
have no benefits with the new editor. i just tried once because some
annoying bugs in the old editor.

best regards

**Comment by ellatrix** [comment] 2019-12-10 21:07
Is this issue still present in Gutenberg 7.0?

**Comment by mapk** [comment] 2020-07-16 21:22
I just tested this with Hebrew using the Gutenberg Starter Theme and all the spacing between paragraphs remained as expected. Seeing as others have shared a similar experience, I'm going to close this.

**Closed by mapk** 2020-07-16 21:22 UTC
Labels: Needs Testing, [Feature] Rich Text
