### ISSUE TITLE
Loading animation for Site Editor

### ISSUE THREAD

**Issue by namithj** [WordPress/gutenberg#41286] opened 2022-05-24 19:37 UTC
## What problem does this address?
The site editor takes several seconds to load.  The user is presented with a blank white screen during this time with no feedback as to whether its loading or stuck

## What is your proposed solution?
Add a loading animation to the site editor.

**Comment by mtias** [comment] 2022-05-24 21:06
This is planned! Marking as duplicate of #35503.

**Closed as completed by mtias** 2022-05-24 21:06 UTC
