### ISSUE TITLE
List: Can't italicize across multiple list items

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#53197] opened 2023-07-31 20:36 UTC
In Google Docs, I can italicize across multiple list items:

![CleanShot 2023-07-31 at 13 35 02](https://github.com/WordPress/gutenberg/assets/36432/6d748cf9-0721-4cbf-af0a-4aa1158f0b76)

It would be nice if I could do this in the Block Editor too.

**Comment by mtias** [comment] 2023-08-04 09:18
There a few challenging implications here. For example, on the web italics carry semantic meaning with `em`. It's not clear if the user intention is to add such meaning or if it's a stylistic choice (like changing font-style across all these items).

We can probably support some multi-line formats, but not as wildcards. For example, adding a link across multiple lines would create multiple links, and it's not evident that you haven't created a single link around the whole set—which means it's not clear if editing one link would edit all links, etc.

So if we support multi-line inline formatting we probably need to make it opt in when registering a format.

**Comment by ellatrix** [comment] 2023-08-15 18:21
~~This is a duplicate of #20568. Let's close in favour of that.~~ Edit: misread alt for ctrl.

It has been an issue since the start. With partial selection, we could attempt it, but only for blocks that are simple and mergeable. For full selection, I don't think we should be going through all rich text areas and format all of them?

**Comment by ellatrix** [comment] 2023-08-15 19:08
I guess it is a duplicate of #27221 though :)

**Comment by ellatrix** [comment] 2023-08-17 13:29
Also found #40907. Let's close these in favour of the oldest ticket.

**Comment by colorful-tones** [comment] 2023-09-28 20:19
@annezazu @ellatrix I'm not clear as to whether this was addressed. It has been marked Done though on the project board. Am I missing something? 🤔

**Comment by colorful-tones** [comment] 2023-09-28 20:23
Ok, I see that #27221 is the favorable task to address this in. Closing this back out. Thanks!

**Closed as completed by colorful-tones** 2023-09-28 20:23 UTC
Labels: [Type] Enhancement, [Feature] Writing Flow, [Block] List
