### ISSUE TITLE
Moving a reusable block made of multiple blocks deletes blocks one by one

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#17370] opened 2019-09-08 10:21 UTC
Create a reusable block composed of more than one block. When attempting to move the whole group, instead of moving the last block is removed until the group is empty.

(Saving the post and reloading makes the issue go away.)

**Comment by senadir** [comment] 2019-09-08 13:12
This was only introduced recently since I couldn't reproduce before refreshing my master

It only happens to newly created reusable blocks, if you save the block, and then insert it from the inserter it doesn't happen, if save & reload, it doesn't happen as well

I added some gifs
if you insert or reload:
![didnthappen](https://user-images.githubusercontent.com/6165348/64488695-98846a00-d242-11e9-8a8d-99363f48356a.gif)

if you create it and try to move it:
![didhappen](https://user-images.githubusercontent.com/6165348/64488697-9de1b480-d242-11e9-9451-17c5dbf4ad89.gif)

**Comment by paaljoachim** [comment] 2019-09-09 05:42
Btw: "Try refactoring the reusable blocks to use a separate block editor."
This PR consolidates multiple issues.
https://github.com/WordPress/gutenberg/pull/14367
I have no idea when Riad returns from his vacation, but it is important to get the above PR merged. I do believe it will help with multiple issues.

Here is another Reusable block error issue:
https://github.com/WordPress/gutenberg/issues/17217

**Closed** 2019-09-10 11:11 UTC
Labels: Priority High, [Type] Bug
