### ISSUE TITLE
Return inside Titel creates new block despite template_lock set on CPT

### ISSUE THREAD

**Issue by Drivingralle** [WordPress/gutenberg#14307] opened 2019-03-07 10:34 UTC
**Describe the bug**
I register a custom post type with the tempalte lock argement set for the whole post type. I also add some blocks into the psot type as block tempalte.
```
$args = array (
    [...]
    'template_lock'       => 'all',
    [...]
);
```

As I create a new post of my post type the block tempalte is loaded. There are no block inserter button in the tool bar. And no block inserter showing up on the blocks directly.

BUT as I enter a title and hit enter a new block right below the title and above the first block of my tempalte is inserted.

**To Reproduce**
1. Have custom post type registed that uses Gutenberg
2. Add a few blocks as a block template for the CPT
3. Add the tempalte lock to the CPT
4. Create a new post of the CPT
5. Check thst no block inserter is visible 
6. Enter any title and hit ENTER

**Expected behavior**
No new block beeing added.

**Screenshots**
https://cloudup.com/cV3dsaLfdJg

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser Firefox 65.0.1
 - Version WP 5.1

**Comment by youknowriad** [comment] 2019-03-07 12:31
Seems related to the work you were doing recently right @jorgefilipecosta to avoid inserting not allowed blocks?

**Comment by jorgefilipecosta** [comment] 2019-03-07 12:33
Exactly I think as soon as we merge the restrictions PR https://github.com/WordPress/gutenberg/pull/14003 this issue will be fixed.

**Comment by jorgefilipecosta** [comment] 2019-06-06 18:43
https://github.com/WordPress/gutenberg/pull/14003 was merged and I confirmed the problem is fixed in the last version of Gutenberg. Thank for reporting this issue @Drivingralle.

**Closed by jorgefilipecosta** 2019-06-06 18:43 UTC
Labels: [Type] Bug
