### ISSUE TITLE
Grid Experiments: Testing feedback

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#62928] opened 2024-06-27 14:10 UTC
Here's some feedback from my testing of the new Grid experiments introduced in https://github.com/WordPress/gutenberg/pull/61025. The video has the full walkthrough, but here are the highlights:

1. Overall, looks pretty good. I was skeptical about overlapping in Manual mode, but it's more intuitive than I expected.
2. There is an issue where all the row heights increase when the item in one row becomes taller. Seems like all rows are locked into being the same height, which is not what you would expect.
 
<img width="1154" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/945eaab2-318b-4880-ac86-aad2b0d1c2a2">
3. Overlapping Image blocks does not work as expected in the Editor. The Image appears above the text content when it should be below. The front end is fine. 

| Editor | Frontend |
|-|-|
|<img width="899" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/7fab04e9-63b8-4640-90f5-89de501f30dd">|<img width="889" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/9d8dccd7-6596-433e-ba14-9006490ef198">|

5. The row/column indicators overlap in tablet/mobile mode
<img width="612" alt="image" src="https://github.com/WordPress/gutenberg/assets/4832319/e64d971c-cb07-44ad-8c26-cf5b9df79071">

6. While I know this will be tricky, we really need some sort of mobile control for Manual mode. 

**Video Walkthrough**

https://github.com/WordPress/gutenberg/assets/4832319/d8821f8a-cbea-47a2-a41c-c7599dcaa09d

cc @tellthemachines @noisysocks @jasmussen

**Comment by tellthemachines** [comment] 2024-06-28 04:06
Thanks for giving this a test run @ndiego!

>  There is an issue where all the row heights increase when the item in one row becomes taller. Seems like all rows are locked into being the same height, which is not what you would expect.

Hmm, were you expecting more of a masonry layout? There seems to be [some appetite](https://github.com/WordPress/gutenberg/issues/39280) for that, so it would be good to consider adding it as an option. The main technical obstacle is that it's not yet possible to implement with CSS only, and having to add JS in the front end it might make more sense to add it to specific blocks as interactivity, rather than a layout type.

I wouldn't expect a grid to behave like masonry, but more like a table, in which the tallest cell will determine the height of the rest of the row. That said, it might be good to look into a way of setting max/min row height! I think in this case both max and min settings could be useful.

> Overlapping Image blocks does not work as expected in the Editor. The Image appears above the text content when it should be below. The front end is fine.

This sounds like a bug; front end and editor should match. I'll look into it!

> The row/column indicators overlap in tablet/mobile mode

Oh well spotted! I suspect that's due to the visualizer being a popover outside the editor canvas. Adding it to the bug list 😅 

> While I know this will be tricky, we really need some sort of mobile control for Manual mode.

I'm looking into combining the Columns and Minimum column width settings to make responsive grids with a max column number in #62777, which hopefully will solve that problem!

**Comment by tellthemachines** [comment] 2024-06-28 04:20
> There is an issue where all the row heights increase when the item in one row becomes taller

Oh wait I think I see what you mean! Every row is the same height, correct? 

Update: I pushed a fix to #62777. In that PR, rows are now the height of their tallest block:

<img width="721" alt="Screenshot 2024-06-28 at 2 35 05 PM" src="https://github.com/WordPress/gutenberg/assets/8096000/8f147dc9-a345-4357-8320-5b596e3924a9">

**Comment by tellthemachines** [comment] 2024-06-28 05:04
> > Overlapping Image blocks does not work as expected in the Editor. The Image appears above the text content when it should be below. The front end is fine.
> 
> This sounds like a bug; front end and editor should match. I'll look into it!

I'm struggling to reproduce this; resizing the right hand text block to the left always results in it overlapping the image:

<img width="871" alt="Screenshot 2024-06-28 at 3 01 33 PM" src="https://github.com/WordPress/gutenberg/assets/8096000/1265fff8-20d5-4bb5-939c-efbc03f57d0e">

Might you at any point have moved the blocks around in list view? That would have reordered the markup without changing their visual position, so it could result in a bug like that. (The list view behaviour is on the list of things to be worked on btw!)

**Comment by ndiego** [comment] 2024-06-28 13:40
> Oh wait I think I see what you mean! Every row is the same height, correct?
> Update: I pushed a fix to https://github.com/WordPress/gutenberg/pull/62777. In that PR, rows are now the height of their tallest block:

Yeah exactly, not masonry. Thanks!

> Might you at any point have moved the blocks around in list view? That would have reordered the markup without changing their visual position, so it could result in a bug like that.

Yeah, that must have been what happened.

**Comment by jasmussen** [comment] 2024-07-01 08:26
Casting a broader net here, @WordPress/gutenberg-design. Note that we do want mobile controls, but we want to build that in a generic-for-all-blocks way, not unique to this block. It's been time for a while, and I'm happy to work on it, just important we don't build more per-block code.

Separately, that text-labels-only mode for the block toolbar, do we have a tracking issue for legibility of those strings yet? I doubt half of that is legible on mobile.

**Comment by tellthemachines** [comment] 2024-07-02 00:47
> Note that we do want mobile controls, but we want to build that in a generic-for-all-blocks way, not unique to this block.

If we allow users to set both minimum column width and a max column count in either mode, they can control the point at which the grid columns reflow. This won't replace mobile controls altogether, but until we have those controls (and I agree they should be generic, not block-specific), we can add a little baseline responsive behaviour to grid by taking advantage of its unique properties. 

> Separately, that text-labels-only mode for the block toolbar, do we have a tracking issue for legibility of those strings yet? I doubt half of that is legible on mobile.

It's actually not terrible 😅 because the toolbar scrolls, so all buttons are reachable:

<img width="401" alt="Screenshot 2024-07-02 at 10 28 07 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/59f59c44-76dd-4cf5-b1e7-687fbe25fa63">

<img width="408" alt="Screenshot 2024-07-02 at 10 46 02 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/b8d69acf-7dae-487c-bb91-e77e91885870">


The main things you _can't_ do in mobile mode are selecting the parent block and dragging and dropping. #25237 could potentially help with the drag and drop but that's unrelated to labels.

The text label toolbar is actually worse on smaller desktop screens, because it can be partially hidden so its right hand side becomes inaccessible unless you're using the keyboard, in which case you can reach the Options button but it looks really broken:

<img width="1131" alt="Screenshot 2024-07-02 at 10 41 10 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/0e38228b-4121-4bc3-9e92-71b4299c6e9a">

<img width="1129" alt="Screenshot 2024-07-02 at 10 44 27 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/fc9a1732-59a2-483d-8231-832d26a64dea">

**Comment by tellthemachines** [comment] 2024-07-12 04:56
Thanks for the feedback folks! I'm going to go ahead and close this issue now, as the reported bugs have been addressed, except for the visualizer being visible outside of the editor canvas. There's now a dedicated issue for that one, as it also overlaps the sidebars in mobile: https://github.com/WordPress/gutenberg/issues/63275. 

The toolbar situation has been somewhat improved in https://github.com/WordPress/gutenberg/pull/63394, though it can still benefit from further improvement, but that's not so much a grid specific issue so I think it can be addressed separately.

**Closed as completed by tellthemachines** 2024-07-12 04:56 UTC
Labels: [Type] Feedback, [Block] Group, [Feature] Layout
