### ISSUE TITLE
Paragraphs locked when a post is opened with standard WP editor

### ISSUE THREAD

**Issue by nicolinuxfr** [WordPress/gutenberg#2469] opened 2017-08-19 09:11 UTC
## Issue Overview

If I open a post written with Gutenberg in the standard WordPress editor using text mode, all paragraph blocks are immediately locked and I can’t edit them. Image and HTML blocks are fine, I have not tested every other blocks.

![gutenberg-locked mov](https://user-images.githubusercontent.com/2078386/29485257-1618579c-84cf-11e7-99db-eba3a3ebaafd.gif)

## Steps to Reproduce (for bugs)

1. Create a new post using Gutenberg
2. Add some paragraphs of text
3. Edit the post with the standard WordPress editor, for instance through a preview
4. Change a metadata, like a taxonomy and don’t touch the post itself
5. Go back to Gutenberg, reload the page
6. All paragraphs are locked

Here’s what it looks like :

![bug-gutenberg-0 9 mov](https://user-images.githubusercontent.com/2078386/29485170-caec378a-84cd-11e7-88a8-d7b618004059.gif)

I’m using latest stable versions of Gutenberg (0.9) installed on WordPress (4.8.1) and used in Safari (10.1.2) on macOS Sierra (10.12.6).

## Expected Behavior

Since I don’t edit the « Gutenberg syntax », I should be able to keep editing the post in Gutenberg. 

And even if I edit the content of a post without Gutenberg, I should be able to preserve the simple syntax to keep the option to go back to Gutenberg at any time.

## Current Behavior

I have to use only Gutenberg to edit my post. If I go inside the WordPress standard editor, even by mistake, I can’t use Gutenberg editor to edit my post. 

Furthermore, I can’t ever use Gutenberg to edit a post at a later date.

**Comment by aduth** [comment] 2017-08-19 15:13
**Cause:** The current editor applies "wpremovep" to strip paragraph tags from the content, including those in the paragraph block. So next time a post is loaded in Gutenberg it detects that the block has been manipulated (since the `<p>` it expects does not exist).

**Possible solutions:**

- Re-apply ["wpautop"](https://codex.wordpress.org/Function_Reference/wpautop) when loading Gutenberg content
- Allow blocks to define recovery behavior, and paragraph block can check for removep'd content
- Accept that for all intents and purposes, the current editor is an unsupported external editor mangling content, and validation is working as expected

**Comment by nicolinuxfr** [comment] 2017-08-19 16:11
Why do I have paragraph tags visible inside the standard editor, then ? I never use visual editor, only the « Text » (HTML) editor.

![bug-gutenberg-0 9 00 00 05 133 0001](https://user-images.githubusercontent.com/2078386/29488376-9e59b77e-8509-11e7-9b42-e93688ada2e0.jpg)

**Comment by aduth** [comment] 2017-08-21 16:17
>Why do I have paragraph tags visible inside the standard editor, then ?

In that case, I would not expect the blocks to be locked (and in my testing, they don't), since this is what the Gutenberg editor is expecting. I wonder if there's something else at play here: perhaps locale? Hidden text in `post_content` ? Do you have other plugins enabled that might be modifying content on save?

Here's a screencast of me through your steps: https://cloudup.com/ciqgX_8F01o

**Comment by nicolinuxfr** [comment] 2017-08-21 17:09
Indeed, it must be a problem on my side.

First thought : I’m using Jetpack and Markdown mode. Maybe it’s the reason why ?

Otherwise, here are my ```functions.php``` file : https://github.com/nicolinuxfr/voiretmanger/blob/master/functions.php

And here’s the list of plugins on my blog :

``` 
+--------------------------------------------+----------+--------+---------+
| name                                       | status   | update | version |
+--------------------------------------------+----------+--------+---------+
| azindex                                    | active   | none   | 0.8.1   |
| color-posts                                | active   | none   | 1.5.2   |
| confirm-publishing-actions                 | active   | none   | 1.3     |
| disable-comments                           | active   | none   | 1.7     |
| gutenberg                                  | active   | none   | 0.9.0   |
| jetpack                                    | active   | none   | 5.2.1   |
| jsonfeed                                   | active   | none   | 1.1.2   |
| pronamic-google-maps                       | active   | none   | 2.3.2   |
| raccourcis-html                            | inactive | none   | 0.1     |
| safe-redirect-manager                      | active   | none   | 1.7.8   |
| search-by-algolia-instant-relevant-results | active   | none   | 2.6.1   |
| shortpixel-image-optimiser                 | inactive | none   | 4.6.0   |
| simple-cache                               | active   | none   | 1.6.3   |
| taxonomy-images                            | active   | none   | 0.9.6   |
| wp-footnotes                               | active   | none   | 4.2.2   |
| wp-optimize                                | active   | none   | 2.1.1   |
| wp-serverinfo                              | active   | none   | 1.64    |
| json-rest-api                              | inactive | none   | 1.2.5   |
| wp-word-count                              | active   | none   | 2.1.0   |
| wordpress-seo                              | active   | none   | 5.2     |
+--------------------------------------------+----------+--------+---------+
```

**Comment by hedgefield** [comment] 2017-08-25 12:28
Can confirm that this happens to me too.
v0.9.0, vagrant environment, no other plugins installed.

- started a post in gutenberg, wrote a title and a few paragraph blocks of gibberish.
- saved draft
- opened in current editor
- changed publish date from `now` to a date in the future and hit `schedule`
- post was saved and turned from draft to scheduled
- opened post in gutenberg, everything fine, new publish date can be seen
- back to posts screen, opened post again in current editor
- post opened on the text view, I switched back to the visual view and hit `update` (no changes made to the content)
- open again in gutenberg and now everything is locked.

**Comment by aduth** [comment] 2017-08-25 12:32
@hedgefield Your workflow would be caused by the circumstances by https://github.com/WordPress/gutenberg/issues/2469#issuecomment-323528951, assuming you're using Visual mode by default in the current editor.

**Comment by nicolinuxfr** [comment] 2017-08-25 12:40
By the way, I disabled completely the visual editor (pref on my profile) and it changed nothing in my case.

**Comment by hedgefield** [comment] 2017-08-25 12:55
@aduth Agreed. In the current editor's Text view I could see the `<p>` tags inside the gutenberg paragraph block tag, which wpautop strips out again when switching over, causing the modification flag. Functionally though, nothing changed about the actual copy. Is there a way for the modification check to handle this more intelligently?

**Comment by karmatosed** [comment] 2017-09-05 19:46
I am unable to replicate this in 1.1 with a normal setup and considering #2469. With that in mind, going to close this. We can always reopen if need.

**Closed by karmatosed** 2017-09-05 19:46 UTC

**Comment by nicolinuxfr** [comment] 2017-09-08 07:36
I still have this behaviour with latest Gutenberg (1.1.0)… 

Could you help me determine what is anormal with my setup ?

**Comment by aduth** [comment] 2017-09-08 16:55
@nicolinuxfr If you're able, can you deactivate all plugins on your site and report back on whether that fixes the issue?

If deactivating plugins resolves the issue, can you try individually reactivating each plugin and testing to see whether the issue is reintroduced? This will help narrow down the specific plugin causing a conflict.

It's otherwise difficult to recreate your site environment on my end.

For what it's worth, I tested briefly with Jetpack's Markdown mode and did not notice any conflicts following the steps from the original issue.
