### ISSUE TITLE
core/image - Block Attribute missing width and height in <InnerBlocks />

### ISSUE THREAD

**Issue by khoipro** [WordPress/gutenberg#35982] opened 2021-10-27 08:16 UTC
## What problem does this address?
I create a new custom block that use `<InnerBlocks />` to create a repeater item.

When I try to read metadata from attributes in `function Save() {}`, the core/image block seem missing width and height attribute **if I don't edit any width/height parameter**. It only visible in metadata if I change those params.

**No edit any width/height param**

<img width="877" alt="Screenshot_9" src="https://user-images.githubusercontent.com/10395311/139026780-6f762edf-394a-4fdc-91c8-51acdc00e042.png">

**Editing height**

<img width="322" alt="Screenshot_1" src="https://user-images.githubusercontent.com/10395311/139048116-1c05a7f1-84f7-47ca-b33c-d3f54b02f912.png">

> The width and height from image source could help to reduce web vitals score.

My example code:

```js
import { __ } from '@wordpress/i18n';
import { useBlockProps } from '@wordpress/block-editor';

export default function save(attributes) {
	const itemBlocks = attributes.innerBlocks ?? [];

       console.log(itemBlocks);

	return (
		<div { ...useBlockProps.save() }>
			{itemBlocks.length ? itemBlocks.map(itemBlock => {
				const imageBlockUrl = itemBlock.innerBlocks[0].attributes.url
				const imageBlockAlt = itemBlock.innerBlocks[0].attributes.alt ?? ''

				if (imageBlockUrl) {
					return <img src={imageBlockUrl} alt={imageBlockAlt} width="640" height="480" />
				}
			}) : ''}
		</div>
	);
}
```

## What is your proposed solution?

Add missing width and height from given image when using with `<InnerBlocks />` even if we don't edit width and/or height in block setting.

**Comment by khoipro** [comment] 2021-10-27 08:18
Hi,

To ensure it works without CORS, I attached the screenshot when using the local image file.

<img width="329" alt="Screenshot_10" src="https://user-images.githubusercontent.com/10395311/139027540-ee07925e-e4c8-4745-a18e-192f880247d5.png">

**Comment by guarani** [comment] 2022-01-06 15:12
I also ran into this problem when trying to get the width/height of an inner image block. Like you say, only when the user edits the image's dimensions do they appear in the image block's attributes.

I think the cause is unrelated to inner blocks, plain image blocks don't set their width/height attributes until their width/height values are edited by the user (either through the input boxes or by the user resizing the image using drag handles):


|  | Editor | Block HTML |
| - | - | - |
| Default size | <img width="1111" alt="Screen Shot 2022-01-06 at 11 54 55" src="https://user-images.githubusercontent.com/1898325/148404026-bfe064b5-6211-4161-8c74-01ac344e3bfb.png"> | <img width="1113" alt="Screen Shot 2022-01-06 at 11 55 02" src="https://user-images.githubusercontent.com/1898325/148404063-d0f3b6e6-e94b-4bed-84ea-3cee89845cfa.png"> |
| Custom size | <img width="1114" alt="Screen Shot 2022-01-06 at 11 55 32" src="https://user-images.githubusercontent.com/1898325/148404070-088492e8-3309-48db-8e95-ec219f148a50.png"> | <img width="1112" alt="Screen Shot 2022-01-06 at 11 55 38" src="https://user-images.githubusercontent.com/1898325/148404154-eb9984d5-5313-4062-b05f-9fd460935ed1.png"> | 


Also, I noticed
- Even if their original values are restored by the user, the width and height still remain available.
- Clicking the "100%" button also similarly causes width/height to be added to the inner image block's attributes.

Regarding the last point, I wonder why the "100%" button is not set by default. Also, I don't know if this is a bug or if the image block behaves this way intentionally.

**Comment by guarani** [comment] 2022-01-06 17:51
I also want to link to https://github.com/WordPress/gutenberg/issues/23244 which this issue may be a duplicate of.

**Comment by t-hamano** [comment] 2022-08-27 11:27
Hi @khoipro,
As @guarani mentions, I think this problem is not limited to `InnerBlocks`, but is the same as #23244.
I would like to close this issue to focus the discussion on #23244.

**Closed as completed by t-hamano** 2022-08-27 11:27 UTC
Labels: [Feature] Nested / Inner Blocks, [Status] Duplicate
