### ISSUE TITLE
Add Block: Chat

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#954] opened 2017-05-31 09:29 UTC
This block exists to be the counterpart to the Chat post format. See also #857.

## Attributes

Good question. Do we want any? Decorative/float alignments, perhaps?

## States

Placeholder:

![chat placeholder](https://cloud.githubusercontent.com/assets/1204802/26625440/60a408e8-45f4-11e7-95ad-86ebadd94655.png)

Neutral:

![chat neutral](https://cloud.githubusercontent.com/assets/1204802/26625445/630f6f0a-45f4-11e7-8b78-e68101dde288.png)

Selected:

![chat selected](https://cloud.githubusercontent.com/assets/1204802/26625450/674d163a-45f4-11e7-96ea-b94c9f7a89f2.png)

**Comment by mtias** [comment] 2017-06-22 10:19
It'd be nice to have a much more condensed view of this. From a few posts I've been looking at, when people do full conversations like this it will waste a lot of space.

**Comment by jasmussen** [comment] 2017-06-23 07:40
Here's a more compact design:

![chat](https://user-images.githubusercontent.com/1204802/27471397-f9f3a674-57f7-11e7-8ed5-045ed30a6d65.png)

We can also go full-on iMessage:

![chat alt](https://user-images.githubusercontent.com/1204802/27471401-fe956faa-57f7-11e7-94ad-841f34551e92.png)

**Comment by swissspidy** [comment] 2017-06-28 14:27
Here are some solutions I found for parsing chat transcripts:

* https://www.narga.net/styling-wordpress-chat-transcript/
* https://github.com/dougalcampbell/Formattd/blob/c05b6a3b290a31c8779fa1f58f9a500bcab54e96/functions.php#L647-L655
* http://justintadlock.com/archives/2012/08/21/post-formats-chat

Regarding the layout: perhaps there could be a toggle to switch compact mode on/off?

Also, the iMessage layout would need to work with multiple people. Who would be on the right side, who on the left?

**Comment by jasmussen** [comment] 2017-06-29 08:35
> Regarding the layout: perhaps there could be a toggle to switch compact mode on/off?

Good idea

> Also, the iMessage layout would need to work with multiple people. Who would be on the right side, who on the left?

Solid point. Scratch that idea :)

**Comment by swissspidy** [comment] 2017-07-01 12:31
As mentioned on Slack yesterday:

* There used to be a chat transcript parsing function in core during 3.6 development, see https://core.trac.wordpress.org/ticket/23625. We can perhaps borrow some stuff from there, mostly regarding to handling edge cases.
* Ideally we shouldn't do any of the rendering server-side (what themes usually do). It can all happen in React and we then store the serialized markup in the database.

**Comment by swissspidy** [comment] 2017-07-01 13:05
One note regarding markup.

The [HTML 5 spec says](https://www.w3.org/TR/html5/common-idioms.html#conversations):

> This specification does not define a specific element for marking up conversations, meeting minutes, chat transcripts, dialogues in screenplays, instant message logs, and other situations where different players take turns in discourse.
> 
> Authors are encouraged to mark up conversations using `p` elements and punctuation. Authors who need to mark the speaker for styling purposes are encouraged to use `span` or `b`. Paragraphs with their text wrapped in the `i` element can be used for marking up stage directions.

**Comment by justintadlock** [comment] 2017-09-14 14:56
The chat transcript parser in my tutorial linked to above has been worked on since then.  You can find the latest here: https://github.com/justintadlock/hybrid-core/blob/master/inc/class-chat.php

It's nowhere near perfect, but feel free to utilize any parts of it needed.

**Comment by karmatosed** [comment] 2017-11-07 16:51
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg.

**Closed by karmatosed** 2017-11-07 16:51 UTC
Labels: Blocks, Good First Issue, Hacktoberfest, New Block

**Comment by remouk** [comment] 2023-01-24 17:35
Hello, I am sorry if I bother anyone about this, but I can't find any information anywhere else. Is this block available? The issue seems closed/resolved, but I can't find the block in Gutenberg.

I am searching for a way to display chat logs in an elegant way.

**Comment by mtias** [comment] 2023-01-25 09:01
Hi there. No, this block doesn't exist in core.

**Comment by remouk** [comment] 2023-01-25 12:56
Thank you for your answer! 🙏 I don't really know how this github works... Since the issue is closed I guess it won't ever be done?
Is there a way to push forward (should I create a new issue with some ideas/specs?)?
