### ISSUE TITLE
Can't apply bold or italics across multiple selected blocks.

### ISSUE THREAD

**Issue by LyteNetworkIO** [WordPress/gutenberg#26519] opened 2020-10-27 20:28 UTC
**Describe the bug**
Can't apply bold or italics across multiple selected blocks. The option disappears.
**To reproduce**
1. Paste in a few paragraphs into Gutenberg
2. Select all the text you pasted, spanning multiple blocks
3. Try to make all that text bold or italic.

**Expected behavior**
If I paste in multiple paragraphs and they become multiple blocks, I should be able to select and format them as I please.

**Comment by bluefuton** [comment] 2021-06-30 21:56
You're also unable to use the keyboard shortcuts to do this. I often find myself doing Cmd-A to select all blocks, then Cmd-B to remove bold styling from all the blocks. Instead this opens the Bookmarks Toolbar on Firefox, which is pretty jarring.

**Comment by KokkieH** [comment] 2021-07-01 05:41
Duplicate of the issue in #27221

**Comment by skorasaurus** [comment] 2022-06-03 21:13
Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/27221 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

**Closed by skorasaurus** 2022-06-03 21:13 UTC
Labels: [Type] Enhancement, [Feature] Block Multi Selection
