### ISSUE TITLE
Move caret behind text after paste

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#6029] opened 2018-04-06 08:51 UTC
## Current Behavior
Pasting copied text into an empty paragraph block leaves the caret at the start of the pasted content.

Gutenberg 2.6.0, WP 4.9.5.

## Expected Behavior
The caret to move to the end of the block contents, so you can paste/type more immediately, as that is what almost all text editors do.

I seem to remember there being an issue about this before but I couldn't find it.

**Comment by karmatosed** [comment] 2018-04-06 14:47
I could have sworn this was an issue already, although I can't find it either! Let's get this resolved :)

**Comment by designsimply** [comment] 2018-08-15 14:30
Found it! Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/5317.

**Closed by designsimply** 2018-08-15 14:30 UTC
Labels: Writing Flow, [Component] Rich Text, [Type] Bug
