### ISSUE TITLE
`media_view_strings` filter execution order not consistent with classic editor

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#9884] opened 2018-09-13 20:51 UTC
When adding images to a Gallery block, the button on the final step has an empty string inside it, instead of `Insert into Post`.

**To Reproduce**

1. Add a `Gallery` block
2. Click on `Media Library` button
3. Click on the `Media Library` tab (if not already selected)
4. Select multiple images
5. Click on `Create a new gallery` button

**Screenshots**

<img width="2047" alt="screen shot 2018-09-13 at 1 44 00 pm" src="https://user-images.githubusercontent.com/484068/45514843-676e7800-b75b-11e8-8bac-f66e0747c68b.png">

**Desktop (please complete the following information):**
 - OS X 10.13.6
 - Firefox 63
 - Gutenberg 3.8.0

**Comment by Soean** [comment] 2018-09-14 09:35
I can't reproduce this issue on 3.8
![bildschirmfoto 2018-09-14 um 11 35 26](https://user-images.githubusercontent.com/695201/45542492-52a0eb80-b812-11e8-85fd-32c9e80f9a72.png)

**Comment by iandunn** [comment] 2018-09-14 17:09
Ah, you're right, it's a plugin conflict. I should have checked that first.

https://github.com/Codeinwp/themeisle-companion/blob/3ef1a45/obfx_modules/mystock-import/init.php#L239

What they're doing works in Classic, though, so it may still be a back-compat issue. The problem seems to be that, in the Classic editor, the `media_view_strings` filter is called _before_ `admin_enqueue_scripts` is fired by `admin-header.php`; but in Gutenberg it's the opposite. 

cc @abaicus, @selul as an FYI

**Comment by danielbachhuber** [comment] 2018-09-29 13:38
> What they're doing works in Classic, though, so it may still be a back-compat issue. The problem seems to be that, in the Classic editor, the `media_view_strings` filter is called _before_ `admin_enqueue_scripts` is fired by `admin-header.php`; but in Gutenberg it's the opposite.

Related #4929

**Comment by antpb** [comment] 2018-10-29 17:18
@johnbillion is this still valid after https://github.com/WordPress/gutenberg/pull/10660 ? 

I noticed you added the 5.0 milestone and then a few days after, the above PR was merged. I think changing `admin_enqueue_scripts` to fire after `admin_head` will solve this. Want to verify.

**Comment by johnbillion** [comment] 2018-10-29 20:38
I added it as it's closely related to #4929 which was in the 5.0 milestone. It does indeed look like this was fixed in #10660. Closing off.

**Closed by johnbillion** 2018-10-29 20:38 UTC
Labels: Backwards Compatibility, Media, [Type] Plugin / Theme Interoperability
