### ISSUE TITLE
Moving the mouse even a pixel when clicking the "apply" icon when making a link will lose the link and multi-select blocks

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#5663] opened 2018-03-16 15:44 UTC
## Issue Overview

(found by @mapk)

If you move your cursor even a pixel when you're clicking on the "apply" icon when making a link, you'll lose the link and end up selecting the blocks below the link dialog.

## Steps to Reproduce (for bugs)
1. Create a post with multiple blocks
2. Select some text in one of the middle blocks and open the link dialog
3. Enter a URL
4. With the pointer over the apply icon, press the mouse button and move the mouse slightly

## Expected Behavior

Nothing should happen until you mouseup.

## Current Behavior

Link dialog disappears and multiple blocks get selected.

## Screenshots / Video

![37004486-69252ae4-2085-11e8-867d-d0a59e0e6b56](https://user-images.githubusercontent.com/3314354/37530075-b27340f6-2930-11e8-8ba0-5ec418bec3d1.gif)

**Comment by designsimply** [comment] 2018-07-17 23:41
Re-tested with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5 and I was unable to reproduce. Closing, but please re-open if you find I've missed something! ([14s](https://cloudup.com/c64f3HKxF2h))

**Closed by designsimply** 2018-07-17 23:41 UTC
Labels: Needs Testing, [Type] Bug
