### ISSUE TITLE
Overlapping of Gutenberg content while scrolling in the editor

### ISSUE THREAD

**Issue by thebud15** [WordPress/gutenberg#4724] opened 2018-01-29 03:24 UTC
## Issue Overview

When using Gutenberg in WP Admin, I noticed that the scroll of the Gutenberg blocks (such as Add Title and opening blocks of text) start overlapping with the Woo info on my page, such as adding Storefront, Theme Integration Guide and Stripe. This happened also when viewing the Gutenberg 

## Steps to Reproduce (for bugs)

1. Opened up a new post in WP Admin
2. This took me to a new Gutenberg post
3. Scrolled down along the post
4. Noticed that the WooCommerce info stayed stationary, while the Gutenberg editing area overlapped it while I scrolled. 

This was on my MacBook Pro, using Safari and Chrome

## Expected Behavior
There shouldn't be an overlapping of the Gutenberg content with the above-post editor area that includes WooCommerce notifications. 

## Current Behavior
The content overlaps when scrolling down the page.

## Screenshots / Video
Happened here with the Gutenberg Demo post: https://cloudup.com/c0bvuaCl-ZT and here with my own test post: https://cloudup.com/caXdCh_GYa5

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by nnoom** [comment] 2018-01-31 22:05
Seems to be an issue with admin notices in general being overlapped by the editor. The first one is near completely overlapped, and the following ones partially. Can be recreated easily on a local environment by throwing in the [sample from the action reference](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices).

**Comment by nnoom** [comment] 2018-01-31 22:17
This appears to be a duplicate of [#3395](https://github.com/WordPress/gutenberg/issues/3395).

**Comment by Soean** [comment] 2018-01-31 23:07
Hey @thebud15, thanks for your report. As @nnoom has mentioned, the error is already known. Therefore, I close this issue.

**Closed by Soean** 2018-01-31 23:07 UTC
