### ISSUE TITLE
Site Editor ( FSE ): Not able to add custom templates in FSE

### ISSUE THREAD

**Issue by sadikmultani** [WordPress/gutenberg#38726] opened 2022-02-11 05:34 UTC
### Description

Hi 

There is no option available like custom so we can add custom templates like a custom archive or single template for specific custom post types. For ex., I've one custom post type called a book. So, I want to add custom templates for my custom post types for a different archive or single templates which we were using in standard themes like archive-book.php or single-book.php.

Also, once we add all possible options available for adding a new template then the add new button is removed from the site editor templates tab.

Is there any other way to add custom templates with the FSE site editor?

Thanks

### Step-by-step reproduction instructions

1. open the site editor and add new templates
2. once we add all the templates which options are available then the add new button will be removed

### Screenshots, screen recording, code snippet

Add new button is removed once I've added all templates from the option - https://prnt.sc/26thvsb

### Environment info

- WordPress 5.9 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2022-02-23 16:56
Thanks for issue @sadikmultani! I'll close this as duplicate of https://github.com/WordPress/gutenberg/issues/37407

**Closed as completed by ntsekouras** 2022-02-23 16:56 UTC
Labels: Needs Testing
