### ISSUE TITLE
Error in color palette depreciation message

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#6616] opened 2018-05-07 08:15 UTC
It's a very little issue about the 2.8 color palette depreciation message :
![capture 2018-05-07 a 10 12 49](https://user-images.githubusercontent.com/1785489/39691873-4ed9cf60-51df-11e8-9f7d-2e9b54b352ec.jpg)

2 things:  
- the first argument should be `editor-color-palette`
- `:` after color should be a fat arrow `=>`

**Comment by jorgefilipecosta** [comment] 2018-05-23 20:16
Hi @maximebj, thank you for reporting this issue! I'm sorry for the trouble caused :( When 2.9 was released the deprecation messages were removed so this issue does not apply now and I'm closing it. I verified the documentation is correct so that should mitigate the problem if there is another action that could be taken to mitigate the troubles caused by the wrong deprecation message on Gutenberg 2.8 just let me know.

**Closed by jorgefilipecosta** 2018-05-23 20:16 UTC
Labels: Blocks, [Type] Bug
