### ISSUE TITLE
A Scheduled Post with Public Visibility Is Displayed Immediately (as if it were not scheduled) 

### ISSUE THREAD

**Issue by drussogit** [WordPress/gutenberg#9136] opened 2018-08-18 20:54 UTC
Gutenberg plugin 3.6.2. WordPress 4.9.8 running Executive Pro Theme theme and Genesis 2.4.2. 
Desktop OS: win10 
Browser Chrome or Firefox 61.0.2 (latest) 
 
With Gutenberg, a post scheduled to display on a future date is displayed immediately after I click the Publish button. In the past, such a post would not be displayed until the scheduled date. That is what we want, of course. 

FYI: If I open the same post in the Classic WP editor, I see these attributes: 

Status: Scheduled 
Visibility: Public 
Scheduled for: Nov 14, 2018 @ 09:00 

Suggestions?

**Comment by nickcernis** [comment] 2018-10-12 19:13
Do you still see this issue, @drussogit?

I am not able to reproduce it so far with Executive Pro, Genesis 2.6.1 and Gutenberg 4.0-RC1.

Posts or pages I schedule with Gutenberg active are not accessible for logged-out users, and they continue to appear as Scheduled in the page/post view:

![screen shot on 2018-10-12 at 21 12 41](https://user-images.githubusercontent.com/647669/46889323-9283de80-ce63-11e8-873e-da27c63a1b76.png)

**Comment by ellatrix** [comment] 2019-06-24 12:36
I'm also not able to reproduce. Closing. Please reopen if this is still a problem in the latest version.

**Closed by ellatrix** 2019-06-24 12:36 UTC
Labels: Needs Testing, [Component] Saving
