### ISSUE TITLE
Text appearing slowly when writing new posts on iPad

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#17939] opened 2019-10-14 16:48 UTC
**Describe the bug**
URL: balloonmachine.net

The user is using an iPad with Chrome or Safari to access the editor.
They can edit "existing posts" without problems but, when they go to create a new post it opens, they can type in the headline fine but when they go to enter text in the main block of the text, the text appears very slowly.
It takes a few seconds from when they press the key to when the text appears.
If they switch away from the browser and come back, the words have disappeared.
Site is premium no plugins. Using block editor.
Occurs on Chrome and Safari on their iPad.

It sounds very similar to this one https://github.com/WordPress/gutenberg/issues/17729

**To reproduce**
1. Create a new post
2. Enter text in the paragraph block.

**Expected behavior**
Not to see a delay

**iPad:**
These are the details which were on HC:-
Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

2420316-zen
15940903-hc

**Comment by rickmgithub** [comment] 2019-10-14 16:57
Also, spotted this issue which looks very similar whereby the editor is freezing when the user tries to edit posts.

They are using - iPad Air2 iOS 12.4.1 model MGTX2LL/A. 

2416649-zen

**Comment by ellatrix** [comment] 2019-10-14 17:31
Thanks for the report! I really think that this is a duplicate of #17729, so I'll close this issue. The fix will be in the next Gutenberg release.

**Closed** 2019-10-14 17:33 UTC
