### ISSUE TITLE
A-tag is not removed when URL is left empty

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#1763] opened 2017-07-06 15:26 UTC
## Issue Overview
Empty link tags are not removed after closing the link modal.

## Steps to Reproduce (for bugs)

1. Select a piece of text
2. Click the Link button (the text is surrounded by an `a` tag, there is not `href` attribute because I have not entered any link.)
3. Clicking next to the modal, the `a` tag remains in the text.

## Expected Behavior

I expect the `a`-tags to be removed when the `href`-attribute is not present or empty.

## Todos
- [ ] Tests
- [ ] Documentation

Plugin version: 0.3.0

**Comment by iseulde** [comment] 2017-07-07 08:47
Duplicate of #1446.

**Closed by iseulde** 2017-07-07 08:47 UTC
