### ISSUE TITLE
Mobile: Columns Block: Missing move arrows on iPhone 11 when you have more then 2 columns.

### ISSUE THREAD

**Issue by enejb** [WordPress/gutenberg#29570] opened 2021-03-04 18:15 UTC
## Step-by-step reproduction instructions
1. Add a new columns block. 
2. Select the 30/30/30 grid. 
3. Rotate the phone so that it is horizontal. 
4. Note that you don't see the arrows to order the columns.

## Expected behavior
I should be able to see the move arrows so that I can reorder the columns.

## Actual behavior
I don't see the move arrows.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/115071/110009802-6090a280-7cd2-11eb-998e-d6771bf5b6c3.png)

## WordPress information
Latest iOS build of the Mobile App.

## Device information
- Device:iPhone 11 
- Operating system:  iOS 14.0
- WordPress app version: Latest

**Comment by mchowning** [comment] 2021-03-05 12:20
Sounds like this [may just be a matter of screen size](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3205#issuecomment-791270373). Is this issue still valid?

**Comment by hypest** [comment] 2021-03-08 11:55
Aha, I guess it's not quite intuitive that the arrow buttons are hosted in the 3-dot menu when the space is limited.

I'd also say that since the arrow buttons are direct manipulation of the block, I'd argue that they should stick around and instead, the settings cog and the 3-dot should collapse into one control since those both are "extra settings/options" for the block.

I'd still consider this ticket as lower-prio since the options are still available (albeit moved) and I'll put it in the backlog but, WDYT @iamthomasbishop?

**Comment by iamthomasbishop** [comment] 2021-05-14 14:51
> Sounds like this may just be a matter of screen size. Is this issue still valid?

@mchowning That's correct, we're moving the movers into the overflow menu when the toolbar is too narrow to accommodate them.

> I'd also say that since the arrow buttons are direct manipulation of the block, I'd argue that they should stick around and instead, the settings cog and the 3-dot should collapse into one control since those both are "extra settings/options" for the block.

@hypest The short version is that we had to make a decision which icons should be moved into the overflow menu when there isn't enough space to display all of the actions. Our decision re: movers vs. block settings was based on priority and discoverability of each of the actions (movers, settings, overflow). With that in mind, we believed that settings was a more primary action and thus deserved more visibility, whereas movers are secondary and obviously the overflow menu was necessary to be the "container" for those items to reside in.

I think we can probably close this for now, mainly because it's expected behavior, but also because I think we may revisit the Inline Toolbar more holistically when we embark on projects related to drag & drop and multi-block selections.

**Closed** 2021-05-17 13:41 UTC
Labels: Mobile App - i.e. Android or iOS, [Priority] Low
