### ISSUE TITLE
YouTube Video Embed Doesn't Load Video

### ISSUE THREAD

**Issue by sabahbah** [WordPress/gutenberg#8423] opened 2018-08-03 08:05 UTC
**Describe the bug**
Gutengberg Version 3.4.0: adding a Video Block in the editor doesn't render youtube video, it just gives an image that says "No video with supported format and MIME type found". I tried both the shortened and long url of the video, it doesn't work in either the editor or the resulting preview.

**To Reproduce**
1. Go to the plus icon next to a new paragraph in Gutenberg editor
2. Click on Video Block in the Common Blocks section
3. Paste the URL in the URL box and click "Use URL"

**Expected behavior**
I would have expected a preview of the video like you would get in the classic editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/15178758/43631550-c80f1318-9703-11e8-813a-cf9d63c4ccd2.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Firefox
 - Version: 61.0.1

**Additional context**
Site is live, hosted on HostGator shared.

From the console in the editor
![image](https://user-images.githubusercontent.com/15178758/43631750-666482f0-9704-11e8-8fbc-f8bbab83e497.png)

From the console on the front-end
![image](https://user-images.githubusercontent.com/15178758/43631677-2af7e5ea-9704-11e8-955e-fe5d8ce82d37.png)

**Comment by youknowriad** [comment] 2018-08-03 10:55
For now, the Video block doesn't accept youtube URLs, it's meant for video URLs (mp4, mpg...), you can use the "Youtube" embed block for that. Granted that this is a bit confusing and needs to be improved. 

I'm closing this one as a duplicate of #6824

**Closed by youknowriad** 2018-08-03 10:55 UTC
