### ISSUE TITLE
Cover Block added to Columns Block cut some of the toolbar options

### ISSUE THREAD

**Issue by StefZarb** [WordPress/gutenberg#15620] opened 2019-05-14 08:32 UTC
**Describe the bug**
The paragraph's toolbar of a cover block inside a column block on a three column set not display all the toolbar options. 

**To reproduce**
1. Add a column block with three columns
2. Add a cover block inside the column block
3. Enter a title to the cover

**Expected behavior**
Being able to add a link to the text or use italic.

**Screenshots**
<img width="1264" alt="Edit Page 9 Productive Bobolink  WordPress 2019-05-14 09-18-00" src="https://user-images.githubusercontent.com/40502934/57682303-70d11c80-7629-11e9-8b83-f4f4297a0600.png">

**Desktop:**
 - Chrome 74.0.3729.131
 - WP 5.2
 - Gutenberg 5.6.1

**Comment by arunsathiya** [comment] 2019-05-15 05:01
A quick note that I am able to reproduce this as well on Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) with macOS 10.14.4 - Mac OS Mojave. 

The closest I came to finding a similar issue is this one - WordPress/gutenberg#11499, but it's not the same.

**Comment by youknowriad** [comment] 2019-08-22 12:59
Duplicate of #15443

**Closed by youknowriad** 2019-08-22 12:59 UTC
Labels: Needs Testing, [Block] Columns, [Block] Cover
