### ISSUE TITLE
Audio Playlist Block - Currently Only Found in WP-Admin Classic.

### ISSUE THREAD

**Issue by scosgro** [WordPress/gutenberg#14199] opened 2019-03-01 18:49 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the only way to add an Audio Playlist is through the Classic Editor in WP-Admin. The playlist shortcode requires file IDs only found in WP-Admin as well. Creating an Audio Playlist in Calypso or Gutenberg is extraordinarily unintuitive (shortcode, with having to use WP-Admin to find IDs from the file URL). 

**Describe the solution you'd like**
Add an Audio Playlist block so audio playlists can be created in the editor once again (currently only available in Classic WP-Admin). 

**Describe alternatives you've considered**
Features could include:
- Ability to easily reorder playlist items once they've been added
- Ability to convert an Audio Block into a Playlist Block

**Comment by noisysocks** [comment] 2019-03-13 02:14
Closing this as a duplicate of #805.

**Closed by noisysocks** 2019-03-13 02:14 UTC
Labels: [Status] Duplicate
