### ISSUE TITLE
Adding paragraphs by keyboard sends you to the bottom of the new paragraph

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8548] opened 2018-08-05 08:33 UTC
**Describe the bug**
If you have a block of text and you wish to split it into two or more paragraphs, you'll position your self where you want the new paragraph, and hit return.

This moves the following content to a new paragraph block, but prepends a line break AND moves the view focus to the end of the newly created paragraph.

This is especially noticeable if you've pasted content, as it can often be considered one large paragraph of text you need to manually transform, depending on the source of the copied text, which means you'll be taken back and forth a whole lot to make the content right.

**To Reproduce**
1. Insert a large single paragraph of text
2. Move to an early point and try to create a new paragraph by hitting the return key
3. Scroll up to get back to where you were in the document
4. Manually remove extra line break that was added

**Expected behavior**
The new paragraph should be created, but not a new line break, and I do not wish for my view to be thrown away, it should remain on top of the new block.

**Screenshots**
![screen-janking](https://user-images.githubusercontent.com/468735/43684131-aa684094-989a-11e8-8b91-2b7a5fccbffb.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68
 - Gutenberg 3.4.0

**Comment by youknowriad** [comment] 2018-08-06 15:43
I can't reproduce personally, Hitting Enter creates a new block for me and not a line break. Unless I'm not reading the issue properly?

**Comment by designsimply** [comment] 2018-08-07 16:08
@youknowriad the problem lies in where the carat is placed before hitting enter. If you place the caret before a line break then that line break is moved to the new paragraph (this is surprising to people: #7616 & #7973) and if you place the caret after the line break it works as they expect. ([22s](https://cloudup.com/cKOM80WUUsb)) 

Possible solution: strip leading line breaks for new blocks.

I am closing this issue in order to consolidate at #7616. Please ask to re-open if you think this issue should remain separate!

**Closed by designsimply** 2018-08-07 16:08 UTC

**Comment by youknowriad** [comment] 2018-08-07 17:40
> If you place the caret before a line break then that line break is moved to the new paragraph 

For me that's the expected behavior, I'd be surprised by any other behavior :).

**Comment by Clorith** [comment] 2018-08-07 17:45
I would argue that you don't expect that, you're at the end of a line and hit return to make a new paragraph, you don't expect an empty line to be carried over with it.

**Comment by youknowriad** [comment] 2018-08-07 17:47
She said before a line break `<br>` not a line break `<p>`. So for me `<br>` is not really an empty paragraph so you have to keep at the position it was before hitting enter.

**Comment by youknowriad** [comment] 2018-08-07 17:50
If you click `Enter` before any character (say `a`) You end up with an empty paragraph followed by a paragraph starting with `a` and the caret is still before `a`. That's exactly what happening here (switch `a` by `<br>`)
