### ISSUE TITLE
No class added to body tag in editor for active page/post template

### ISSUE THREAD

**Issue by jlvngs96** [WordPress/gutenberg#8948] opened 2018-08-13 21:07 UTC
In the classic editor, a body class is added to the editor, indicating the active post/page template. This is very useful when creating the editor specific stylesheet during theme development so the editor matches styles on the front end. For example, my default single post has a sidebar, but I also have a full width post/page template that removes the sidebar. So in the classic editor a body class is added for "page-template-full-width" for example, that lets me target that in the editor stylesheet. Would like this same functionality for Gutenberg. This is important so if the default is active, the editor body is one width, and if a page template is selected, the editor body is another width.

**Comment by jlvngs96** [comment] 2018-08-13 22:48
It's in the editor "#tinymce" body tag that's in the iframe (not the body tag for the whole admin page). I have no special plugins that would be doing this. Def core:

![body-class-for-template](https://user-images.githubusercontent.com/24628268/44062171-81e1c3dc-9f18-11e8-8ea7-f0bb7da6d5d6.JPG)

**Comment by chrisvanpatten** [comment] 2018-08-13 23:16
Oooh, interesting. I was looking at the actual body class. I can confirm it's there for me too.

In that case this might qualify as a backcompat issue. I'll tag it and let's see what the other folks say!

**Comment by webmandesign** [comment] 2018-08-28 16:59
Hi guys,

I'm all for this to be included. I actually have the exact same issue as @jlvngs96 experiences. Was using the classes to target specific page/post template editor appearance and I think [this should be kept in Gutenberg](https://github.com/WordPress/WordPress/blob/4.9.8/wp-admin/js/post.js#L1179) too.

Also, in my opinion it would be better if such classes are applied onto actual Gutenberg editor content area, not on admin body. So, on `div.edit-post-visual-editor`. This is open for discussion, surely.

If you can, could you also please allow filtering such classes. Currently, for example, it is possible to filter TinyMCE classes via `tiny_mce_before_init` hook.

Thanks!

**Comment by foreverpinetree** [comment] 2018-09-12 03:52
Hi,
A class "page-template-**" is very useful when editing a page, becaue usually we need to change the backend layout according to the Page Template.
Although I can listen the select which in the Page Attributes to add a class to the body or somewhere, I don't know if it would change later, that's not a save method.

Looking forward to this feature!

**Comment by webmandesign** [comment] 2018-10-08 10:11
Hi guys (@chrisvanpatten),

Any update on this issue? Will the functionality be integrated with Gutenberg?

As my themes actually rely on page template body class change in TinyMCE editor, I'm still hesitating to update them for Gutenberg compatibility because the feature is not integrated in Gutenberg. As you can understand that would basically mean downgrading the user experience which I don't really want to do&hellip;

Thanks for any update provided!

**Comment by eddhurst** [comment] 2018-10-16 14:51
Keen for this as well - we have some different block styling depending on the template you're on to better reflect the front-end. This works fine on CPT, as the CPT is in the body class, but there's no template class here as yet.

For now I'm going to need to add in some custom JS to achieve this, but it would be super useful going forwards.

**Comment by danielbachhuber** [comment] 2018-10-16 14:57
@eddhurst Can you share the JavaScript you end up using so I can add to my [Gutenberg Migration Guide](https://github.com/danielbachhuber/gutenberg-migration-guide)?

**Comment by webmandesign** [comment] 2018-10-16 18:43
@danielbachhuber 

I'm actually also using JS to dynamically apply template class on Gutenberg's `#editor` container when a page template is selected/changed. Here is what I've come with:
```
<?php
add_action( 'enqueue_block_editor_assets', function() {
	wp_add_inline_script(
		'wp-edit-post',
		"
		// When changing page template, change the Gutenberg editor container class.
		( function( $ ) {
			wp.domReady( function() {
				var editorContainer     = $( '#editor' ),
				    templateSelectClass = '.editor-page-attributes__template select';

				editorContainer
					.on( 'change.set-editor-class', templateSelectClass, function() {
						var pageTemplate = $( this ).val() || 'default';

						pageTemplate = pageTemplate
							.substr( pageTemplate.lastIndexOf( '/' ) + 1, pageTemplate.length )
							.replace( /\.php$/, '' )
							.replace( /\./g, '-' );

						editorContainer
							.removeClass( function( index, className ) {
								return ( className.match( /\bpage-template-[^ ]+/ ) || [] ).join( ' ' );
							} )
							.addClass( 'page-template-' + pageTemplate );

						$( document ).trigger( 'editor-classchange' );
					} )
					.find( templateSelectClass ).trigger( 'change.set-editor-class' );
			} );
		} )( jQuery );
		"
	);
} );
```

This is basically an adapted version of [original WordPress code](https://github.com/WordPress/WordPress/blob/4.9.8/wp-admin/js/post.js#L1179) and obviously, this is an example of a PHP function outputting the JS ;)

**Comment by designsimply** [comment] 2018-10-18 18:03
I'm closing this issue in order to consolidate with #10640 and would like to note the discussion here has been useful and helpful and it will be linked from the other issue. Sometimes it's hard to choose which to keep when there are duplicates—in this case, the #10640 issue seemed better to me because it's very clear and concise and I am interested in keeping the easiest-to-grok issues open where possible.

Thank you for testing Gutenberg at this stage and for your open discussion on this topic!

**Closed by designsimply** 2018-10-18 18:03 UTC
Labels: Backwards Compatibility, [Status] Duplicate, [Type] Plugin / Theme Interoperability

**Comment by foreverpinetree** [comment] 2018-10-31 06:13
@webmandesign 
Thanks for your code. But if the Page Attributes is closed, then refresh the page, you will see that the editor container won't be applied a page-template class.

**Comment by strarsis** [comment] 2019-04-15 16:45
Based on the code here, I made a little tutorial (sage9 based theme): https://discourse.roots.io/t/gutenberg-body-class-elements-by-template/15310
