### ISSUE TITLE
Supports Inserter: False is not working

### ISSUE THREAD

**Issue by squibbleFish** [WordPress/gutenberg#8789] opened 2018-08-09 17:49 UTC
**Describe the bug**
Creating a custom block in Gutenberg using the `supports`. According to the docs, if I don't want the custom block to appear in the `inserter` I just need to add `inserter: false` to the `supports` object. This is currently not working. The block is still appearing in the Gutenberg Inserter

**To Reproduce**
1. Register a new custom block
2. Pass `inserter: false` to the `supports` object
3. Look at the inserter

**Expected behavior**
The block should not be visible from the inserter.

**Screenshots**
It's the Milestone block that currently shows in the inserter.
<img width="363" alt="screen shot 2018-08-09 at 11 48 29 am" src="https://user-images.githubusercontent.com/5972722/43916218-2d8a1966-9bca-11e8-8efd-1e86efcbeb9f.png">

**code sample**
```javascript
export const settings = {
  title: 'Milestone',
  description: 'A single Milestone for the Milestones block',
  category: 'common',
  icon: 'list-view',
  supports: {
    customClassName: false,
    html: false,
    inserter: false,
  },
  attributes: {},
  edit,
  save: (() => null),
};
```

**Comment by youknowriad** [comment] 2018-08-10 08:58
I can't reproduce this. I just tried with the exact same code above. In the screenshot above I see the name of the block is "Milestones" and in the code "Milestone", could this be another block?

**Comment by squibbleFish** [comment] 2018-08-16 19:14
This might be an issue with running an outdated version. Once I update, I'll test out and let you know. Thanks for the help 😄

**Comment by designsimply** [comment] 2018-09-17 22:12
Closing because it couldn't be reproduced in testing. Happy to re-open or continue the discussion if the problem is still happening with the latest version.

**Closed by designsimply** 2018-09-17 22:12 UTC
Labels: Extensibility, Needs Testing, [Status] Needs More Info, [Type] Bug

**Comment by squibbleFish** [comment] 2018-09-18 19:13
@designsimply & @youknowriad So after further testing, it looks like `inserter: false` only works on core blocks and not custom blocks. We are currently extending `core/list`, and when adding `inserter: false` we do notice that the list is missing from the inserter. However; this does not work for any custom blocks. Is there a filter we might be missing?
