### ISSUE TITLE
Selecting column elements is very difficult/confusing

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15975] opened 2019-06-03 23:02 UTC
From #9156

> Selecting elements (especially the RIGHT element) is very confusing.
>
> Base styles should probably include a gutter between columns.
>
> Being able to select the individual columns maybe isn't strictly necessary. The only thing you can do with them is add a CSS class. Why not just add a CSS class to begin with?

When the block is first inserted, there are no borders around the columns, so it's not obvious what the block even does until you insert content into both columns. Even after you insert content, it's difficult to click on the `Column` (singular) and `Columns` (plural) containers, because they have no borders to help you distinguish between them and their children; they probably also don't have much (if any) padding. The only way I could reliably access them was through the `Block Navigator` component.

I'm not sure if removing the UI of the `Column` (singular) block is possible at this point b/c of back-compat, but maybe it could be done for blocks that don't have a custom CSS class assigned yet?

Related #11159

**Comment by talldan** [comment] 2019-06-04 03:02
Hi @iandunn - there's a very similar issue open at the moment:
- (https://github.com/WordPress/gutenberg/issues/9628) Enhance the tools for selecting child/parent blocks

And there are some PRs attempting to tackle this:
- (https://github.com/WordPress/gutenberg/pull/14961) Try additional borders and padding for nested blocks
- (https://github.com/WordPress/gutenberg/pull/15537) Selecting Parent Blocks: Try clickthrough

I think this one could be considered a duplicate of #9268, so will close it. Let me know if you disagree.

> I'm not sure if removing the UI of the Column (singular) block is possible at this point b/c of back-compat, but maybe it could be done for blocks that don't have a custom CSS class assigned yet?

I remember seeing some past discussion on #14961, I think recently there have been some additional features added to the column (vertical alignment, column width), which might make that less of a possibility.

**Closed** 2019-06-04 03:03 UTC
Labels: Needs Design, [Block] Columns, [Status] Duplicate, [Type] Bug

**Comment by iandunn** [comment] 2019-06-05 16:58
👍 I missed those in my search, thanks!
