### ISSUE TITLE
block preview throws error / fails 

### ISSUE THREAD

**Issue by lgersman** [WordPress/gutenberg#21018] opened 2020-03-19 13:54 UTC
**Describe the bug**

Block preview fails in Gutenberg for all block types containing just text like 

* core/paragraph
* core/heading  

For the same reason block styles for core/paragraph and core/heading will not get rendered in the Sidebar inspector panel.

The main reason is that in function `ScaledBlockPreview` (`packages/block-editor/src/components/block-preview/scaled.js`) previewElement is expected to be a Element (having method `getBoundingClientRect`) but the called method `getBlockPreviewContainerDOMNode(block.clientId)` will return a Text Node instead of an Element for 'core/paragraph' and 'core/heading'.  And Text Node does'nt provide method 'getBoundingClientRect'.

**To reproduce**
1. Open Gutenberg editor
2. Click on 'Add block'
3. Scroll down to pararaph or heading
4. See empty preview and check the javascript developer console for js stacktrace. 

**Expected behavior**

Block preview and preview of block styles will render a preview.

**Screenshots**

![bug](https://user-images.githubusercontent.com/81591/77074592-56a65e80-69f1-11ea-83f0-2accbc5cfb2b.jpg)

**Desktop:**
 - OS: Linux Mint
 - Browser Chrome
 - Version 80

**Additional context**
- Gutenberg 7.7.1

**Comment by lgersman** [comment] 2020-03-20 13:02
Everything needed to fix this Gutenberg bug : 

Edit file [packages/block-editor/src/utils/dom.js (line 22)](https://github.com/WordPress/gutenberg/blob/8af5f08d37901f442ed7c46cf66cd21bf9864909/packages/block-editor/src/utils/dom.js#L22) and replace the whole line

`return domNode.firstChild || domNode;`

with 

`return [domNode.firstChild, domNode].find(_ => !!_ && _.getBoundingClientRect);`

The change ensures that the returned node is a DOM node having method getBoundingClientRect.

Since the changed function `getBlockPreviewContainerDOMNode` is only used once within a single sourece file (`ScaledBlockPreview.js`) its a side effect free change 

Have a good one,

Lars

**Comment by talldan** [comment] 2020-03-26 01:05
Fixed by #21014

**Closed by talldan** 2020-03-26 01:05 UTC

**Comment by larsgersmann** [comment] 2020-03-26 07:54
Hello @talldan : I'd just checked out Gutenberg 7.8.0. to see if this issue is fixed. 

Unfortunately #21014 fixes just the preview of the Inserter Panel, but not the preview of the style variations in the Inspector Panel.

I created this issue because the preview failed at the Inserter panel AND within the styles variations preview of the Inspector Panel ("For the same reason block styles for core/paragraph and core/heading will not get rendered in the Sidebar inspector panel." -> take a look at the issue description).

So again, my Pull Request #21048 will also fix this issue. 

Please reopen this issue because the issue is not fixed yet.
