### ISSUE TITLE
Navigation block: editable list view shows double "menu" heading

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#48657] opened 2023-03-01 20:54 UTC
### Description

When using the navigation block's editable list view, "menu" is shown twice in the sidebar. This was previously fixed and I'm not sure why it's back or if this is intentional. 

### Step-by-step reproduction instructions

1. Open Appearance > Editor.
2. Select the navigation block.
3. Open block settings and look at the editable list view. 

### Screenshots, screen recording, code snippet

<img width="294" alt="Screen Shot 2023-03-01 at 12 52 41 PM" src="https://user-images.githubusercontent.com/26996883/222262483-d0635e9f-8fa8-4714-9416-53f0fc7843a4.png">

### Environment info

- WP 6.2 beta 4
- no GB
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment] 2023-03-02 14:11
Duplicate of: https://github.com/WordPress/gutenberg/issues/48671

**Comment by ndiego** [comment] 2023-03-02 15:34
It looks like both duplicates were closed. We need one on them, so reopening since this was the first.

I can also replicate in Beta 4, it was fixed previously.

**Comment by ntsekouras** [comment] 2023-03-02 15:47
@ndiego it was fixed though by:https://github.com/WordPress/gutenberg/pull/48679. So both can be closed.

**Comment by ndiego** [comment] 2023-03-02 15:49
@ntsekouras oh perfect. Thanks for the clarification!

**Closed as completed by ndiego** 2023-03-02 15:49 UTC
Labels: [Type] Bug, Needs Design Feedback, [Block] Navigation
