### ISSUE TITLE
Docs: Add tutorial explaining how to use block variations API

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#20581] opened 2020-03-02 13:34 UTC
## Description

Originally raised in #16283.

Based on the examples shared in #20068 and e2e tests created in #20286 we could create tutorials presenting how to make the most using the block variations API.

## Examples

_Recorded screencasts contain unstable API but included code examples are up to date._

1. Registers the variation with the inner blocks to apply from the block variation picker using `scope` limited to the block: 

```js
wp.blocks.registerBlockVariation( 'core/columns', { name: 'custom', title: 'Smiley', isDefault: true, innerBlocks: [ [ 'core/column' ], [ 'core/column' ], [ 'core/column' ], [ 'core/column' ] ], icon: 'smiley', scope: [ 'block' ] } );
```
![patterns-api-inserter-1](https://user-images.githubusercontent.com/699132/72546493-245e7080-388b-11ea-9962-c870b6e69046.gif)

2. Registers the variation with the inner blocks to apply from the inserter using `scope` limited to the inserter: 
```js
wp.blocks.registerBlockVariation( 'core/columns', { name: 'custom', title: 'Smiley', isDefault: true, innerBlocks: [ [ 'core/column' ], [ 'core/column' ], [ 'core/column' ], [ 'core/column' ] ], icon: 'smiley', scope: [ 'inserter' ] } );
```

![patterns-api-inserter-2](https://user-images.githubusercontent.com/699132/72546494-245e7080-388b-11ea-8ee1-d2a309991fcd.gif)

2. Registers two variations with initial attributes to apply from the inserter directly:
```js
wp.blocks.registerBlockVariation( 'core/heading', { name: 'green-text', title: 'Green Text', description: 'This block has green text. It overrides the default description.',  attributes: { content: 'Green Text', textColor: 'vivid-green-cyan' }, icon: 'palmtree', scope: [ 'inserter' ] } );
wp.blocks.registerBlockVariation( 'core/heading', { name: 'red-text', title: 'Red Text', attributes: { content: 'Red Text', level: 3, textColor: 'vivid-red' }, icon: 'smiley', scope: [ 'inserter' ] } );
```

![patterns-api-inserter-3](https://user-images.githubusercontent.com/699132/72546975-080f0380-388c-11ea-8955-5eef87d997be.gif)

3. Registers a variation which allows changing the default style variation:
```js
wp.blocks.registerBlockVariation( 'core/quote', { name: 'large', title: 'Large Quote', isDefault: true, attributes: { className: 'is-style-large' }, icon: 'palmtree', scope: [ 'inserter' ] } );
```

**Comment by gziolo** [comment] 2020-07-02 12:32
It's currently documented in the following places:
- https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#variations-optional
- https://make.wordpress.org/core/2020/02/27/introduce-block-variations-api/

There is also a very helpful post from @richtabor on his blog: https://richtabor.com/block-variations/

**Comment by jorgefilipecosta** [comment] 2020-09-16 11:48
I'm closing the issue for now as it seems variations are already documented.

**Closed by jorgefilipecosta** 2020-09-16 11:48 UTC
Labels: Needs Dev, [Feature] Block API, [Type] Documentation

**Comment by aacassandra** [comment] 2021-01-03 16:18
Hi everyone, im trying to implement the code as above 
1. scope block, not working
2. scope. inserter is work

For variation like social-link, how do we get into sidebar blocks? any examples for this or documentation?
@gziolo

**Comment by coreyworrell** [comment] 2021-04-22 00:04
@aacassandra it looks like there is no a scope option for `transform` which adds the sidebar option there. Not sure what `block` scope is supposed to do.

> `block` – Used by blocks to filter specific block variations. Mostly used in Placeholder patterns like Columns block.

Not very clear what that means.

I also noticed though that if you specify `{ attributes: { className: 'is-style-whatever' } }` that you can no longer add additional classes via the Advanced sidebar panel, or else it "deactivates" the variation.

**Comment by Humanify-nl** [comment] 2021-08-28 08:45
Sorry to add this to a closed issue. But I found it is very elusive in the documentation how to use the variations picker if block scope is chosen. I had to find it digging into the core src, comparing groups & columns.

For example, when creating variations on the core group block, the variations picker is not found. Yet, it allows me to choose block scope, while this doesnt do anything (because there is no `<__experimentalBlockVariationPicker />` in core/group).

Would it be helpful if this is mentioned somewhere in the docs? (if you choose block scope, make sure there is a variation picker)

**Comment by gziolo** [comment] 2021-08-31 19:31
> Would it be helpful if this is mentioned somewhere in the docs? (if you choose block scope, make sure there is a variation picker)

Yes, that sounds like a good clarification to include. It looks like there are only 2 core blocks that have it integrated:
- Columns
- Query Loop

@ntsekouras, can you confirm?

**Comment by ntsekouras** [comment] 2021-09-01 12:31
>Yes, that sounds like a good clarification to include. It looks like there are only 2 core blocks that have it integrated:
Columns
Query Loop
@ntsekouras, can you confirm?

I can confirm that. I'll open a PR to update the docs a bit.
