### ISSUE TITLE
Adding background colour to heading block squashes text by adding too much padding

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#38926] opened 2022-02-19 08:43 UTC
### Description

Adding a background colour to the Heading block squashes all the text, making it look like a mess, as it adds a HUGE amount of padding around all the sides.

<img width="1440" alt="screenshot_167" src="https://user-images.githubusercontent.com/2078245/154793517-78a25bae-8163-4330-afa7-1ca37dc48ec0.png">

https://user-images.githubusercontent.com/2078245/154793494-07aaaa21-5648-4f59-8881-d746a0e25745.mp4

### Step-by-step reproduction instructions

- Add heading block
- Change background colour
- See text get really squashed due to huge amounts of padding

### Screenshots, screen recording, code snippet

See above

### Environment info

WP 5.9
Twenty Twenty One
Firefox 97.0.1
macOS 12.1
No Gutenberg plugin, core only

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment] 2022-03-23 19:48
Thanks for the detailed report and screenshots; 

I am able reproduce this as shown in the first screenshot; with 5.9.2; no gutenberg plugin activated 
![Selection_164](https://user-images.githubusercontent.com/955351/159783463-e158698c-910a-46ca-8533-dfc74b744faa.jpg)


in the second screenshot, the gutenberg plugin is activated and the issue appears to be solved and doesn't have the padding issue:
![Selection_163](https://user-images.githubusercontent.com/955351/159783551-1bbadbe4-282d-45ea-a003-3e33b3112796.jpg)

I'm closing the issue since this has been fixed in the newest version of gutenberg; I appreciate your detailed, clear report, saving time for me to troubleshoot.

**Closed as completed** 2022-03-23 19:54 UTC
Labels: [Type] Bug, [Block] Heading, CSS Styling
