### ISSUE TITLE
"Latest posts" block is stripped from the_content if $strip_teaser=true and "more" block exists

### ISSUE THREAD

**Issue by whywaitwebs** [WordPress/gutenberg#15008] opened 2019-04-17 07:19 UTC
**Describe the bug**
"Latest posts" block is stripped from the_content if $strip_teaser=true and "more" block exists.

**To reproduce**
1. Use a theme that calls the_content with $strip_teaser "true" [ie, the_content(null, true)]
2. Create a post with a "latest posts" block and a "more" block or a "page break" block.
3. View the post and see that the "latest posts" block has been stripped and outputs no HTML.

**Expected behavior**
The latest posts block should not be stripped if it occurs after the "more" block as it is not a part of the teaser.

**Additional context**
- Wordpress 5.1.1
- With or without Gutenberg plugin installed
- Advanced Gutenberg "Recent Posts" block gets stripped as well

**Comment by youknowriad** [comment] 2019-04-17 12:48
Thanks for the issue, this is a duplicate of #14874

**Closed by youknowriad** 2019-04-17 12:48 UTC
Labels: [Block] Latest Posts
