### ISSUE TITLE
Gutenberg demo shows a full-width Cover Image, but this option is not present in the UI

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#3516] opened 2017-11-16 07:58 UTC
![2017-11-16t15 57 06 0800](https://user-images.githubusercontent.com/227022/32879944-e2f478ba-cae6-11e7-8f95-8b3b45b44ce3.png)

It appears that it is no longer possible to create a full-width cover image via the editing interface.  Maybe I am just missing the way to do it, but if it is really no longer possible, then this feature should be removed from the demo content and its CSS rules should be removed.

**Comment by samikeijonen** [comment] 2017-11-16 08:13
In my opinion it should definitely be possible. This is pretty common design pattern. 

See also #2650.

**Comment by samikeijonen** [comment] 2017-11-16 08:19
@nylen You can set `'wide-images' => true,` and after that you can set full width cover image. But `alignwide` or `alignfull` are still missing in the markup. Those should be added.

**Comment by nylen** [comment] 2017-11-17 03:40
I'm not aware of the context behind making this available on a per-theme basis, but it sounds sensible.

So I think the only thing to do here is to remove the full-width cover image from the demo content, since this can't be recreated on a standard install.

**Comment by samikeijonen** [comment] 2017-11-17 10:23
> I'm not aware of the context behind making this available on a per-theme basis, but it sounds sensible.

It's because Gutenberg can't know is there room for full width or wide, and what that even means on theme by theme. There can be sidebars in the left or right etc.

**Comment by mtias** [comment] 2017-11-20 14:01
Closing as duplicate of #2595.

**Closed by mtias** 2017-11-20 14:01 UTC

**Comment by pipskidoodle** [comment] 2018-11-27 03:07
/**
 * Register support for Gutenberg wide images in your theme
 */
function mytheme_setup() {
  add_theme_support( 'align-wide' );
}
add_action( 'after_setup_theme', 'mytheme_setup' );

https://weblines.com.au/gutenberg-blocks-wide-alignment-full-width/
