### ISSUE TITLE
The Library page in Hybrid Themes that support Template Parts has a broken homepage preview

### ISSUE THREAD

**Issue by aurooba** [WordPress/gutenberg#51295] opened 2023-06-07 13:07 UTC
### Description

This is a similar issue to what we saw in the 6.2 beta, #48391, and it's reproducible again in 6.2.2 – I'm not sure if it came back in 6.2.1, but it _was_ fixed and confirmed fixed when the initial 6.2 release happened. I just noticed it again.

### Step-by-step reproduction instructions

1. Activate a classic theme with theme.json and support for block template parts that includes at least one block template part. (happy to provide an example theme if needed)
2. Go to Appearance > Template Parts
3. Click on the back button for `All Template Parts`
4. See the loading screen where the homepage should be – this page shouldn't exist for hybrid themes, from my understanding, it should go straight back to the dashboard.

#### Without Gutenberg
https://github.com/WordPress/gutenberg/assets/6925260/ca29a187-f8ad-4e31-a0a9-1b8de5d965b8

#### With Gutenberg 15.9.1 
https://github.com/WordPress/gutenberg/assets/6925260/7aa89d19-a058-4023-a1e0-9985c7c54cf3

### Environment info

- WordPress  6.2.2
- Tested with AND without Gutenberg 15.9.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2023-06-07 16:46
@Mamaduka  in case you might be able to dig in!

**Comment by t-hamano** [comment] 2023-07-02 13:24
WordPress 6.3 and the latest Gutenberg behave differently: when you press the back button on the All Template Parts page, it takes you to the Library page, but the loading status is not displayed in the canvas area, but the registered pattern is displayed.

I would like to close this issue as I believe this problem is no longer reproduced.

However, I have submitted issue #52150 because I don't believe it is strictly intended that non-block themes that support block template parts be able to access the Library page.

**Closed as completed by t-hamano** 2023-07-02 13:24 UTC
Labels: [Type] Bug, [Feature] Templates API, [Feature] Site Editor
