### ISSUE TITLE
theme.json: Global link color always overloads any block styles on the frontend

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#31990] opened 2021-05-19 12:11 UTC
## Description

When declaring a link color under `style:elements` and a link color under `style:blocks`, the global color always overrides the block specific selection.

## Step-by-step reproduction instructions

1. Open TT1 and add the following to the `theme.json`:
```
{
	"version": 1,
	"styles": {
		"elements": {
			"link": {
				"color": {
					"text": "pink"
				}
			}
		},
		"blocks": {
			"core/site-title": {
				"elements": {
					"link": {
						"color": {
							"text": "red"
						}
					}
				}
			}
		}
	}
}
```
2. See on the frontend that the site title is pink.

## Expected behaviour

Blocks should be able to override the global link color.

## Actual behaviour

In the admin, the site title is red, and other links pink, as expected:

![link-admin](https://user-images.githubusercontent.com/1221942/118809987-9d207300-b8ab-11eb-81c5-73f37f6d93b8.png)

On the frontend however, the site title is always pink.

![link-frontend](https://user-images.githubusercontent.com/1221942/118810038-ae697f80-b8ab-11eb-9482-5d6a99d70c47.png)

## Screenshots or screen recording

CSS on the backend:

![link-css-backend](https://user-images.githubusercontent.com/1221942/118810234-ea9ce000-b8ab-11eb-94a1-a1f0a5f35ae9.png)

The grey background is from #30874.

CSS on the frontend:

![link-css](https://user-images.githubusercontent.com/1221942/118810053-b3c6ca00-b8ab-11eb-9d05-d86694649387.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1

## Device information
- Device: Mac
- Operating system: MacOS
- Browser: Chrome

**Comment by carolinan** [comment] 2021-05-20 14:10
🤔 `wp-block-site-title` is placed on the heading/p element, so the red link color is not applied to the actual link.

**Comment by oandregal** [comment] 2021-07-13 12:11
:wave: I can't repro this. I'm using: WordPress 5.7.2, Gutenberg 11.0.0, and tried with TT1 and TT1-blocks. Both work as expected.

By adding the `theme.json` in the issue description to TT1 I get the following CSS in the front-end (plus all the CSS for preset classes and CSS custom properties):

```css
a {
  color: pink;
}
.wp-block-site-title a {
  color: red;
}
```

This is correct. However, it does nothing because the TT1 is not prepared to work with that: it doesn't use the site title block (so no `wp-block-site-title` class to target) and the specificity it has for links in its own stylesheet is higher than `a`.

@fklein-lu I wonder if the bug is no longer reproducible due to latest changes or if you had a different setup?

**Comment by getsource** [comment] 2021-08-31 06:06
Hi @fklein-lu !

This issue was tested in [a triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1630388517113100).

A few of us tested with varying themes, and as @oandregal mentioned previously, were unable to reproduce it.

I suspect that this might have been fixed since the original posting.
As such, I'm going to close the issue for now, but if you're still having the issue, please feel free to re-open!

**Closed as completed** 2021-08-31 06:06 UTC
Labels: [Type] Bug, Needs Testing, Global Styles, CSS Styling
