### ISSUE TITLE
Not Publishing Corretly

### ISSUE THREAD

**Issue by prwhitney1** [WordPress/gutenberg#12250] opened 2018-11-23 15:26 UTC
I am using "post name" permalinks.  When document done editing, a  permalink with post name is generated and visible when clicking on post title.  After publishing, the correct post comes up but not everything is there, e.g. picture zooming, author info and  others.  If i copy and paste permalink, it come up correctly  my site:   www.bibleanswersforyou.com/    permalink:  https://bibleanswersforyou.com/thanksgiving-day-giving-thanks-god/  

This has been the case for the last 4 weeks.  I am new at this so I may have  set something up wrong.  I tried a redirect and that did not work.  [login details removed—these should not be posted in a public forum]

Thanks much.  I have been tempted to jump ship because of all the problems with Gutenberg, but I'm going to hang tight with you guys.   I love the editor but as with Forrest Gump, it's like a box of chocolates.  You never know how it will behave tomorrow.  Worked with IBM 20 years and understand software development and what you guys are going through.  My opinion it was released a little early.  

It has cut my productivity 50% with the time required fixing problems

Thanks much.

**Comment by tellthemachines** [comment] 2019-07-25 06:24
Hi there, 

Are you still having trouble with this?

I am unable to reproduce the issue by:
*  Changing the permalinks setting to "postname";
*  Creating a new post, clicking "Publish" and then clicking "View Post".

I'm closing this issue for now; feel free to re-open it if the problem is still occurring.

**Closed by tellthemachines** 2019-07-25 06:24 UTC
Labels: Needs Testing
