### ISSUE TITLE
Classic: Infinite content duplication loop when wrapping with anchor tag

### ISSUE THREAD

**Issue by WunderBart** [WordPress/gutenberg#29338] opened 2021-02-25 12:57 UTC
## Description
Using the Classic block, when manually wrapping a captioned image with an anchor tag via the Code Editor, the anchor starts duplicating indefinitely after exiting the Code Editor and toggling back in. This can potentially lead to running out of RAM and making the post completely uneditable.

## Step-by-step reproduction instructions
1. Add a Classic block
2. Inside that block, add an image with a caption
3. Go to Code Editor
4. Wrap the whole content with an anchor tag manually
5. Exit the Code Editor
6. Enter the Code Editor back in
7. See how the content duplicates.

## Expected behaviour
Content never duplicates itself.

## Screenshots or screen recording
https://user-images.githubusercontent.com/1451471/109156516-3a6a8000-7771-11eb-8a69-f878b1191763.mov

## WordPress information
- Gutenberg version: latest

## Device information
- Browser: Chrome

**Comment by ramonjd** [comment] 2021-02-26 02:56
I can reproduce this in Gutenberg 10.1.0-rc.1 in Chrome

Wrapping the shortcode in a tag that has an attribute seems to affect the code editor. 

So, for example. wrapping with an `<a href=""></a>`

![Feb-26-2021 13-47-43](https://user-images.githubusercontent.com/6458278/109248278-9dbfe500-7839-11eb-9d88-8fcb8b496396.gif)

Or wrapping with a `<p align="left"></p>` seems to do a quick replace when you blur out of the code editor.

So this:

```
<p align="left">


[caption id="attachment_11" align="alignnone" width="289"]<img class="wp-image-11 size-medium" src="http://localhost:4759/wp-content/uploads/2021/02/Screenshot-2021-01-29-at-4.50.07-PM-289x300.png" alt="t-shirt" width="289" height="300"> t-shirt[/caption]
</p>
```

Becomes this:

```
<p align="left"></p>


[caption id="attachment_11" align="alignnone" width="289"]<img class="wp-image-11 size-medium" src="http://localhost:4759/wp-content/uploads/2021/02/Screenshot-2021-01-29-at-4.50.07-PM-289x300.png" alt="t-shirt" width="289" height="300"> t-shirt[/caption]
```

**Comment by avivalk** [comment] 2021-03-22 22:26
I have this same issue! Any ideas how to get around it? My entire page is unusable because its just stuck in the infinite loop. How can I stop the loop and restructure the html so it doesn't start again?

OR is an update going to come out soon that will fix it?

**Comment by mcsf** [comment] 2021-04-05 18:16
Closing as duplicate of #29988.

**Closed by mcsf** 2021-04-05 18:16 UTC
Labels: [Block] Classic, [Type] Bug
