### ISSUE TITLE
No way to delete an empty block with a mouse

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#10385] opened 2018-10-07 13:40 UTC
Previously #6579

In #6589 we added a trash icon to empty blocks, for a unified UX. Since then, the block options have been moved to the block actions menu, which does not exist for an empty block until you start typing and thus converting it to a paragraph block.

**Versions** 
WordPress 4.9.8
Gutenberg 3.9.0

**Comment by kkoppenhaver** [comment] 2018-10-14 21:38
Added a suggestion for something similar on https://github.com/WordPress/gutenberg/issues/10334 and would love any suggestions. Happy to tackle this once we decide on an approach.

**Comment by antonioguedes** [comment] 2019-02-27 05:37
Found out that when you have 2 or more empty columns in one block, if you go to the menu and click on the three lines (hamburger menu) next to the icon "i", select > column > then on the right where you see the number of columns you can create, just delete whatever number is there, and boom! Block is deleted!

**Comment by talldan** [comment] 2019-03-13 03:05
Just noting #14325 was created, which is a duplicate of this. @garrett-eclipse had this suggestion:

> Describe the bug
> Currently when you have an empty paragraph block to remove it you hit backspace (delete key) or you switch to Code View to remove it. New users are unaware of the backspace and often don't feel comfortable in Code View. It would be nice to provide the triple-dot menu which provides the Delete Block option on empty paragraph blocks.
> Alternatively, could update the placeholder text 'Start writing or type / to choose a block.' to add 'To remove simply hit the backspace/delete button'. Or something along those lines.
> 
> To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to the block editor
> 2. Add an empty paragraph block.
> 3. Click on it and find only the 'Add Block', 'Add Image', 'Add Heading' and 'Add Gallery' options.
> *It's not clear how to remove this block.
>
> Expected behavior
> A clear method for removing the empty paragraph block would be nice. Something that didn't require the user to guess or read docs to understand how to remove.

**Comment by aduth** [comment] 2019-04-22 14:02
I'm going to close this as considered duplicate of #9063, at least to consolidate discussion on how to handle block controls for this "empty" state.

**Closed by aduth** 2019-04-22 14:02 UTC
Labels: Accessibility, Priority Low, User Experience (UX)
