### ISSUE TITLE
Please add clarifying comments for translators on unclear strings

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#5388] opened 2018-03-04 14:28 UTC
## Issue Overview
Some strings are unclear to translators. It would be good to add comments to translators

For example, there are two strings that in many languages normally would translate to the same string. Is it important that they stay different? Do they mean different things? I'm referring to:
`Write quote…` and `Write citation…`
In the translation interface for WordPress (at translate.wordpress.org) you get direct links to the place(s) in the repository where a string is used. But, since Gutenberg almost solely operate with Javascript, these links go to a "dummy file" and you need to dig even deeper in order to try to understand how a string actually is used.

Therefore it would be golden to add comments to translators by putting a comment with the right format on the immediately preceding line in /languages/gutenberg-translations.php
I understand this is not totally trivial, since this file most probably is automatically generated. But I'd like to make the point that there are quite a few strings that are hard to understand, when they are out of context.

## Related Issues and/or PRs
I didn't find related issues when I did a quick search, but would welcome additional notes from people who are more involved in this project.

## Todos
- [ ] Fill out a todo list, once we know that to do

**Comment by aduth** [comment] 2018-03-04 15:06
Relevant Slack conversation: https://wordpress.slack.com/archives/C02QB2JS7/p1520166612000107

**Comment by ocean90** [comment] 2018-03-04 15:30
Looks like a duplicate of #5361.

**Closed by ocean90** 2018-03-04 15:30 UTC
Labels: duplicate, i18n
