### ISSUE TITLE
Post Featured Image Block Consolidate double dimensions panel 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36536] opened 2021-11-16 18:13 UTC
## What problem does this address?

This came up as part of the eleventh call for testing for the FSE outreach program from @paaljoachim:

>But instead I noticed a Dimensions panel with Height and Width. + Another Dimensions panel further below with a + in it. (Confusing having two Dimenions kinds of panels. I did not know what Height/Width I should add so I randomly added 300px Height and 600px Width. Doing so the Scale option showed up. To where I could select Cover – Contain or Fill.

<img width="272" alt="Screen Shot 2021-11-15 at 7 30 47 PM" src="https://user-images.githubusercontent.com/26996883/142041994-c04d8d8f-b3c1-49ac-b132-6cd502a1b17b.png">

## What is your proposed solution?

Consolidate these sections :D cc @stacimc as we chatted about this.

**Comment by paaljoachim** [comment] 2021-11-24 22:24
Thank you Anne and @stacimc Staci!

**Comment by annezazu** [comment] 2022-01-12 00:06
This has somehow returned in 5.9 RC2 :D 

<img width="286" alt="Screen Shot 2022-01-11 at 4 04 58 PM" src="https://user-images.githubusercontent.com/26996883/149040670-4b61c4ba-ca17-4a64-92c5-ce9de5c06746.png">

Found this while writing documentation for 5.9: https://github.com/WordPress/Documentation-Issue-Tracker/issues/69 cc @stacimc

**Comment by Mamaduka** [comment] 2022-01-12 06:21
@annezazu, it looks like we forgot to backport the changes. Marked PR to be backported in minor release - https://github.com/WordPress/gutenberg/pull/36540#issuecomment-1008916827

**Comment by noisysocks** [comment] 2022-01-18 23:17
We can keep the issue closed as the issue is fixed in the plugin. Since https://github.com/WordPress/gutenberg/pull/36540 has the "Backport to minor" label, it will end up in 5.9.1.

**Closed as completed by noisysocks** 2022-01-18 23:17 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Block] Post Featured Image
