### ISSUE TITLE
Widget Editor: Need more left/right spacing for List block

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26127] opened 2020-10-14 20:00 UTC
### Problem
As reported by @monika-12, [here](https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40066), when using the List block, the numbers, depending on the theme, can get pushed right against the edge of the widget area. 

**Example**
<img width="818" alt="list" src="https://user-images.githubusercontent.com/617986/96039055-f2c80500-0e1c-11eb-8eee-98cdc24504cc.png">

### Solution
Provide more left/right spacing between the blocks and the edges of the areas.

**Comment by mapk** [comment] 2020-10-20 21:49
I've tested this with Gutenberg Starter Theme, and Twenty Twenty and could NOT recreate the problem.

**Comment by talldan** [comment] 2021-01-06 07:30
I also couldn't reproduce:
<img width="692" alt="Screenshot 2021-01-06 at 3 30 12 pm" src="https://user-images.githubusercontent.com/677833/103741478-1a9dc200-5034-11eb-8403-2f8535cb4c73.png">

I'll close this, but if we can find some reproduction steps happy to reopen again.

**Closed by talldan** 2021-01-06 07:30 UTC
Labels: Needs Testing, [Feature] Widgets Screen, [Type] Bug
