### ISSUE TITLE
Add WordPress User Setting for Welcome Tips, Pre-publish Checks & Other "Settings" Stored in Browser Cookies or Local Storage

### ISSUE THREAD

**Issue by kopepasah** [WordPress/gutenberg#18999] opened 2019-12-08 03:17 UTC
**Is your feature request related to a problem? Please describe.**

When users open the editor for the first time they are graciously greeted with very helpful tips to assist in quick learning about the new editor. The current conditional to determine if these tips should show rely on client side storage within the browser, and not a permanent user setting.

**Describe the solution you'd like**

Browser storage is still okay, but a permanent user setting needs to be added, then a conditional check could **first** occur based on the user setting.

**Describe alternatives you've considered**

Not clearing my cookies (sorry, that's not going to happen 🤷‍♂).

Clearing cookies is simply something people often do and knowing I have to reset these "settings" each time I clear my cookies is a bit of a pain.

**Comment by aduth** [comment] 2019-12-08 22:36
Thanks for the report. There's already an existing issue at #15105 which encompasses this pretty well, so I'm going to close this in favor of the other issue.

**Comment by aduth** [comment] 2019-12-08 22:36
Duplicate of #15105

**Closed by aduth** 2019-12-08 22:36 UTC

**Comment by kopepasah** [comment] 2019-12-09 16:43
@aduth that makes complete sense and thanks for following up. I did perform a few issue searches, which did not expose any relevant issues, but obviously I was not searching for the correct keywords.

I'll follow along on #15105.
