### ISSUE TITLE
Using the inserter to insert a paragraph in the second column of the columns block, moves the cursor to the first column

### ISSUE THREAD

**Issue by haemeulrich** [WordPress/gutenberg#7160] opened 2018-06-05 21:24 UTC
I'm unable to insert a Paragraph Block inside a Columns (Beta) Block. I'm only able to insert other blocks like images. Is this a limitation of the current version?

**Comment by haemeulrich** [comment] 2018-06-05 21:35
Now it is even worse. I get content only to the first column. Please see my screencast here:
https://www.screencast.com/t/5S5M3mPibeW9

**Comment by youknowriad** [comment] 2018-06-05 21:47
I'm seeing a small issue in your screencast where the paragrapn is inserter to the first column.

A simple workaround is to put the cursor directly in the second column and start typing.

**Comment by haemeulrich** [comment] 2018-06-05 21:51
ok, thanks for this worlaround. Do I habe to do any bug report or so?

**Comment by youknowriad** [comment] 2018-06-05 22:03
No, this issue is fine, I'm just renaming the title to clarify the bug.

**Comment by haemeulrich** [comment] 2018-06-05 22:05
great thamk you for your great work!

**Comment by ZebulanStanphill** [comment] 2018-08-20 17:33
I think this is a duplicate, or at least very closely related to #5772.

**Comment by mtias** [comment] 2018-11-15 18:06
Is this issue still happening?

**Comment by ZebulanStanphill** [comment] 2018-11-15 19:36
@mtias Yes, it is still happening in `master`.

**Comment by youknowriad** [comment] 2019-08-22 12:38
Ii think this is fixed now.

**Closed by youknowriad** 2019-08-22 12:38 UTC
Labels: Writing Flow, [Block] Columns, [Component] Nested / Inner Blocks, [Type] Bug

**Comment by ZebulanStanphill** [comment] 2019-08-22 15:31
@youknowriad It's currently not possible to reproduce this bug due to the mobile-style clickthrough selection behavior introduced a little while ago. It might resurface if that change is reverted (see #16888), though I'm not sure. It's probably fine to close this for now, though.
