### ISSUE TITLE
Background image not showing in the editor for Cover blocks with the "fixed background" setting enabled 

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#28678] opened 2021-02-02 22:55 UTC
## Description

Background image not showing for Cover blocks with the "fixed background" setting enabled. This seems to happen only upon the block's initialization (i.e when the editor loads and the block is constructed). More details below.

## Step-by-step reproduction instructions

1. Create a new post or page;
1. Add a Cover block, select a background image for it;
1. Select the Cover block, and in the settings, pane look for a "Media settings" section and enable the "Fixed background" setting;
1. Reload the page.
1. Notice how the Cover block's background image is not shown **in the editor**. If you publish the page, the rendered block correctly shows it as expected, though.

Interestingly enough, if you disable the setting and enable it again, the image will keep rendering without problems. However, if you enable it *and reload the page*, you'll see experience the issue again. **It seems the issue only happens upon the block's initialization and if this setting is on.**

## Expected behavior

I expect the Cover block to correctly render the image in the editor when the background is set to "fixed".

## Actual behavior

The cover background image is not shown at all.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/81248/106673317-0f787c00-6577-11eb-89ae-a34a85c46470.mp4

## WordPress information
- WordPress version: `5.7-alpha-49963`
- Gutenberg version: `v9.8.3`
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes.

## Device information
- Device: Desktop.
- Operating system: Ubuntu Linux 18.04.
- Browser: `86.0b4 (64-bit)`.

**Comment by annezazu** [comment] 2021-02-02 23:52
@noisysocks as a heads up since this seems to impact the 5.7-alpha-49963.

**Comment by stokesman** [comment] 2021-02-03 03:37
This looks to be a duplicate of #28425, which the changes from #28565 have fixed.

**Comment by fullofcaffeine** [comment] 2021-02-03 03:47
> This looks to be a duplicate of #28425, which has been fixed by the changes from #28565.

I double-checked and could *not* reproduce the issue on the latest `master`. Great to know 9.9 will have the fix!

**Comment by annezazu** [comment] 2021-02-03 03:50
Since this is a duplicate and will be fixed in 9.9, going to go ahead and close this out :)

**Closed by annezazu** 2021-02-03 03:50 UTC
Labels: [Block] Cover, [Type] Bug
