### ISSUE TITLE
Structural CSS bugs on Windows 10

### ISSUE THREAD

**Issue by azaozz** [WordPress/gutenberg#11638] opened 2018-11-08 17:14 UTC
Testing 4.2 (prebuild) in Chrome on Windows 10. The results are the same in Firefox and Edge.

1. The bottom of the admin menu is not accessible (can't scroll):
![1](https://user-images.githubusercontent.com/743931/48214515-caaa0e80-e388-11e8-8001-5caabf34370b.png)

2. After resizing the window a bit, another scrollbar appears that scrolls the admin menu and the main column. The double scrollbars on the right look pretty bad though:
![2](https://user-images.githubusercontent.com/743931/48214638-0ba22300-e389-11e8-9525-09b29e19bcf7.png)

3. With the inspector closed, no scrollbars and the bottom of the admin menu is not accessible:
![3](https://user-images.githubusercontent.com/743931/48214712-3c825800-e389-11e8-9463-e2a7254cf733.png)

4. With longer content, there are two scrollbars. One scrolls the main column, the other scrolls the inspector. Admin menu still not accessible:
![4](https://user-images.githubusercontent.com/743931/48214798-6b98c980-e389-11e8-8f3a-3755f1d4f038.png)

5. After resizing the window a bit another scrollbar appears. It scrolls the admin menu and the main column just some of the way. Additionally the scrollbar on the main column scrolls the rest of it. Note how the top of main column scrollbar is somewhere under the header:
![5](https://user-images.githubusercontent.com/743931/48214947-d0ecba80-e389-11e8-8aee-1752c7be1ef9.png)

6. Longer content, no inspector. One scrollbar that scrolls only the main column. Admin menu not accessible:
![6](https://user-images.githubusercontent.com/743931/48214998-f37ed380-e389-11e8-88e4-842727735b55.png)

7. After resizing the window a bit same as before: another scrollbar on the right that scrolls both the admin menu and partially the main column. To reach the rest of the main column need to use the inner scrollbar:
![7](https://user-images.githubusercontent.com/743931/48215095-2d4fda00-e38a-11e8-9367-e8aac3684407.png)

Expected behavior: "proper" layout where the longest of the three "blocks" (admin menu, main column, inspector) would push the bottom of the window so there is only one scrollbar on the right.

**Comment by jasmussen** [comment] 2018-11-14 09:15
Aspects of this are intentional insofar as you are meant to be able to scroll the contents of the inspector separately. You are meant to be able to scroll the contents of the editing canvas itself separtely. These all scroll separately so as to let you keep focus on the content, and to avoid scroll bleed. For example you should be able to scroll to the bottom of the editing canvas without also the sidebar content scrolling out of view (being way at the top). Additionally, you should be able to scroll to the end of the block library, without additional scrolling starting to scroll the content below.

The sub-optimal behavior here is the navigation sidebar on the left. When there is a lot of content here, ideally this would be scrollable on its own, without affecting the contents on the right. However if we add overflow properties to this container, the flyout menus stop working. 

The fix that is implemented at the moment is the additional scrollbar on the right. When there is the need for scrolling the content outside the editor, this is scrollable using the rightmost scrollbar. I agree this would be nice to optimize, but that requires a refactor of the navigation menu in wp-admin. 

However I can't reproduce the issues you show here — when there is need to scroll the navigation sidebar contents, the scrollbar is always present for me. Can you provide additional steps to reproduce?

![resize](https://user-images.githubusercontent.com/1204802/48472266-2d226500-e7f6-11e8-8609-aaa3895bd271.gif)

**Comment by youknowriad** [comment] 2020-01-16 17:25
The layout changed a lot. Are these issues still happening?

**Comment by enriquesanchez** [comment] 2020-03-16 23:43
Closing as stale. Feel free to reopen if necessary.

**Comment by tellthemachines** [comment] 2020-03-16 23:55
I can still reproduce this issue in IE (the sidebar is not scrollable at all):

![ie-no-scrollbar](https://user-images.githubusercontent.com/8096000/76808978-6bda8c00-683d-11ea-812d-ba3d34c9628c.png)

It's working fine on Chrome though (the outer scrollbar allows us to scroll the admin sidebar):

![chrome](https://user-images.githubusercontent.com/8096000/76809010-92002c00-683d-11ea-978d-e9d0caf21127.png)

**Comment by skorasaurus** [comment] 2021-10-05 15:38
Closing this [since IE is no longer supported](https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/); please reopen and comment if you're able to reproduce this.

**Closed by skorasaurus** 2021-10-05 15:38 UTC
Labels: General Interface, Browser Issues, CSS Styling
