### ISSUE TITLE
Early slug edit

### ISSUE THREAD

**Issue by pgrab86** [WordPress/gutenberg#8645] opened 2018-08-07 07:08 UTC
I am not sure, if this is not a bug actually. 

When you try to add a post/page you can't edit the slug of a page before publishing it and refreshing the site.

Without Gutenberg you can click on create new post/page, type title and edit the slug immediately. With gutenberg you have to save it first and refresh the page, because without that last one step there is no "tooltip" with slug edit

**Comment by youknowriad** [comment] 2018-08-07 08:00
This is a duplicate of #7129 Let's consolidate there.

**Closed by youknowriad** 2018-08-07 08:00 UTC
