### ISSUE TITLE
Classic Block toolbar doesn't sit on the edge of frame

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7918] opened 2018-07-12 05:12 UTC
**Describe the bug**
The toolbar on the Classic Block no longer sits right on the top edge of the block, like it used to. There's now a weird gap appearing above the toolbar.

![screenshot_731](https://user-images.githubusercontent.com/2078245/42613700-b0eb333a-85e5-11e8-8f76-b7a039d09de3.png)

**To Reproduce**
1. Add Classic Block
2. Take note of toolbar location in reference to block container

**Expected behavior**
Toolbar should align with the top edge of the Block. 

_macOS Sierra 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by designsimply** [comment] 2018-07-16 19:11
Tested and confirmed using WordPress 4.9.7 and Gutenberg 3.2.0 on Firefox 61.0.1 on macOS 10.13.5.

![screen shot 2018-07-16 at mon jul 16 1 07 54 pm](https://user-images.githubusercontent.com/1119271/42778209-96e896be-88f9-11e8-9ec6-1fb8afa40f65.png)

**Comment by aduth** [comment] 2018-07-17 15:09
Duplicate of #7728. Since this has more context, I'll close the other.

**Closed** 2018-07-31 07:51 UTC
Labels: Blocks, Good First Issue, UI Components, [Type] Bug
