### ISSUE TITLE
Read more link doesn't work with reusable block

### ISSUE THREAD

**Issue by FalconTheme** [WordPress/gutenberg#8633] opened 2018-08-07 01:05 UTC
Hey I try to make custom read more link on a post and on all my posts.

So here what I did:
1. I edit the post and I create the 'More' block to cut my post in half.
2. I edit its text into 'Read detail'
3. And I want it reusable to all my posts. So I click the option button on right corner of block, and click 'Add to reusable block'.
4. And I save the post.
5. Then I check on my home page. No any 'read more' button show up. And my post doesn't cut.

I want that button show up with my custom text. That what I expect.

I use:
 - OS: Windows 10, 64
 - Browser : chrome,
 - Version (I don't know. It always updated by itself)
- I use Gutenberg ver 3.4.0

**Comment by 10given** [comment] 2018-08-11 02:27
Gutenberg ver 3.5.0 still not fix this. 
Please disable the 'Add to reusable block' for this block or just make it work.

**Comment by FalconTheme** [comment] 2018-08-20 08:13
Gutenberg ver 3.6.2 still not fix this.
Please disable the 'Add to reusable block' for this block or just make it work.

**Comment by Soean** [comment] 2018-08-20 10:47
Hey, @FalconTheme thanks for reporting and testing this issue. 
I don't think we can fix it in the next versions, see https://github.com/WordPress/gutenberg/issues/7957#issuecomment-412783208 for more details.

**Comment by aduth** [comment] 2019-05-31 19:58
In testing this today, it works for me to assign a "More" block as a Reusable Block, and the content is split as expected in the blog listing.

![image](https://user-images.githubusercontent.com/1779930/58731524-ed4f5380-83bc-11e9-88e8-1d22a3722127.png)

Are you still having issues with this?

**Comment by GlennMartin1** [comment] 2019-06-23 15:23
I have the identical issue.

When the "more" block is included within a reusable block, the "more" has no effect.

**Comment by davoraltman** [comment] 2020-01-01 07:05
I can confirm I can reproduce this issue.

I add the More block - it works.
I make that same More block a reusable block - it no longer works.

**Comment by tanjoymor** [comment] 2020-02-03 23:25
If this assists... I've found that features like the More block don't work within the Reusable blocks UNLESS you convert the Reusable block back to regular blocks after placing them.

Reusable block with More block: https://d.pr/i/LUZv4a
Preview: https://d.pr/i/C74jsZ
Convert to regular blocks: https://d.pr/i/Ny4QEW
Preview: https://d.pr/i/ZlDUTi

**Comment by karmatosed** [comment] 2020-03-16 20:28
I was able to do this using the latest version:

![image](https://user-images.githubusercontent.com/253067/76797111-bb30a600-67c4-11ea-8d26-fe094b40cf0e.png)

If people are still unable to do this, we can reopen, for now closing.

**Closed by karmatosed** 2020-03-16 20:28 UTC
Labels: [Block] More, [Feature] Blocks, [Status] Needs More Info

**Comment by youknowriad** [comment] 2020-03-16 20:33
I believe the block doesn't work on the frontend but I'm not sure it's possible to make it work. I have vague memories that we had to switch the `the_content` hooks priorities at some point, it caused this issue but solved others.
