### ISSUE TITLE
Line break remains in RichText after deleting second line

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#7630] opened 2018-06-29 10:29 UTC
**Describe the bug**
After adding multiline text to a `<RichText>` component the content will always receive a trailing `<br/>` even after the text has been updated to no longer be multiline.

**To Reproduce**
1. Add a `core/button` block.
2. Add content `"Hello{enter}{enter}World"` to produce a button with multiple lines of text. (note: Already the content is `Hello<br/>world<br/>`, one `<br/>` too many)
3. (optional) Save, refresh...
4. Delete the text `"World"` to return the button to a single line of text
5. (optional) Save, refresh...
6. Both front and back end, the button's content is `Hello<br/>` when it should just be `Hello`

This behavior also exists when the block attribute is saved in comments, not pulled from dom, leaving this in the block comments: `{"content":["Hello",{"type":"br","key":"_domReact1","ref":null,"props":{},"_owner":null,"_store":{}}]}` when it could simply be `{"content":["Hello"]}` 

**Expected behavior**

Don't leave a trailing `<br/>` when going multiline.

Also a `<RichText>` prop that prevents multiple lines altogether would be useful.

**Comment by designsimply** [comment] 2018-07-03 01:19
Tested and confirmed that adding multiple lines of text to a button and then removing the extra lines leaves an extra `<br />`.

![screen shot 2018-07-02 at mon jul 2 7 16 27 pm](https://user-images.githubusercontent.com/1119271/42193613-c2e85466-7e2c-11e8-856f-e319a1c2e04b.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13861&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>

**Comment by iseulde** [comment] 2018-11-26 15:59
Does this only happen in Firefox? Then this is a duplicate of #5872. Feel free to reopen if this in not the case.

**Comment by ktmn** [comment] 2018-11-26 17:33
Nope, Chrome too.

**Closed** 2019-03-05 11:25 UTC
Labels: [Component] Rich Text, [Type] Bug
