### ISSUE TITLE
Feature: Move post-title outside editor canvas to the top bar.

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/gutenberg#44244] opened 2022-09-18 15:56 UTC
## What problem does this address?

This is a long-standing annoyance:

Since the start of Gutenberg, the post-title is on top of the block editor as a h1. But it is never representing the actual design well and goes against the WYSIWIG principles. 

Let me explain: 

You will see a lot of sites where the post-title is placed in a cover block, or an advanced layout. The post title can be placed anywhere, right?

By placing it in the editor canvas, it ultimately confuses the end-user to the purpose of this UI element, illustrated by these thoughts and feedback I've received:

"If it is in the editor, why can't I edit its style or move it? "
"Do I have to use the post-title for this page, or not?"
"Why do I see the post-title twice?" (if a post-title is placed manually, and within other blocks - which is almost always the case).

## What is your proposed solution?

Present the post-title outside the editor canvas, and add it to the toolbar on top, in a similar font.

![Screenshot 2022-09-18 175102](https://user-images.githubusercontent.com/82579622/190916042-8df63df2-3fa5-44c3-a161-80dc40850c2f.jpg)

This will signal to end-user: _"this is an important part of the editing proces, **but** it is _not_ inside the editor canvas, **so** (it is intuitively clear) there is no way to control its block style/settings"_ which are usually available when a post-title is placed manually.

Added cherry on top is that it will be uniform with site-editor, and the top of the page is actually the top of the page, as a visual 1:1 representation (except for template-parts above it).

**Comment by mtias** [comment] 2022-09-19 13:40
See #20877 and #27093.

**Comment by talldan** [comment] 2022-09-20 02:51
I think this can be closed as a duplicate of #27093

**Closed as not planned by talldan** 2022-09-20 02:51 UTC
Labels: [Status] Duplicate, [Package] Edit Post
