### ISSUE TITLE
Block's "More options" opens above

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#5387] opened 2018-03-04 11:07 UTC
## Issue Overview
The block's "More options" (rotated dashicons ellipsis icon) opens above the button when there is not enough space below (while dev tools open for example). You are unable to scroll up to select "Remove (block)" option when the block in question is located at the top area of the editor. 

![](https://i.imgur.com/pJIoMlG.png)

## Steps to Reproduce (for bugs)

1. Open new editor. Make screen resolution in chrome dev tools responsive preview 1440x600, for example.
2. Add a paragraph.
3. Add another paragraph under it.
4. Open the second paragraph's More options popup - it opens above.
5. You can't scroll up to reach the Remove option.

![](https://i.imgur.com/IcKXL3N.png)

## Expected Behavior

The menu shouldn't open above the button when there's not enough room in the editor (ie. the block is 2nd-3rd position from the top).

## Possible Solution
1. The "Turn into" options could be in a submenu to reduce the height overall of the menu.
2. There could be a simpler button to remove a block, for example a "minus/trashcan" icon next to the "plus" icon for adding a block. It should delete the block instantly if it's brand new/not modified (aka. accidentally added, as happens a lot with this editor), but use a confirmation method when it's got manually added content. (I'm aware backspace can delete a block, but a simple, always available button, would be more desirable in my opinion). 

## Related Issues and/or PRs

I understand the UI is in constant flux and this is far from final implementation, but I'm still making this issue because I'm finding it really cumbersome to test/develop custom blocks at the moment due to no easy way to get rid of them. I have to open this long menu with many options irrelevant to me and pray that the option I want is actually visible when I do.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by stompweb** [comment] 2018-03-04 11:13
Duplicate of https://github.com/WordPress/gutenberg/issues/5368

**Closed** 2018-03-04 11:33 UTC
