### ISSUE TITLE
Gutenberg 14.8.0+ compat issue with WordPress < 6.1

### ISSUE THREAD

**Issue by Otto42** [WordPress/gutenberg#46811] opened 2022-12-28 16:54 UTC
Gutenberg 14.8.0+ compat issue with WordPress < 6.1

14.8.0 introduced the use of has_same_registered_blocks function call:
https://plugins.trac.wordpress.org/changeset/2837553/gutenberg/trunk/lib/experimental/class-wp-theme-json-resolver-gutenberg.php

This function was only added to WordPress in 6.1.:
https://core.trac.wordpress.org/changeset/54493

However, Gutenberg itself was marked as compatible with 6.0:
https://plugins.trac.wordpress.org/changeset/2837553/gutenberg/trunk/gutenberg.php

Result attempting to install Gutenberg 14.8.0 and up with WordPress 6.0 will cause a fatal error. Example:
https://wordpress.org/support/topic/call-to-undefined-method-wp_theme_json_resolver_gutenberghas_same_registered_b/

Thus, the compatibility needs to be marked at 6.1 in the plugin headers, which will prevent older installs from accidentally breaking the site.

**Comment by kathrynwp** [comment] 2022-12-28 17:43
@spacedmonkey @oandregal @felixarntz – hey there, just a ping to see if any of you might be able to have a look at this. Thanks!

**Comment by noahtallen** [comment] 2022-12-28 18:48
I'll take a look and try to get a fix into a patch release.

**Comment by noahtallen** [comment] 2022-12-28 19:00
> Thus, the compatibility needs to be marked at 6.1 in the plugin headers, which will prevent older installs from accidentally breaking the site.

We do need to add back compatibility in Gutenberg for this feature -- Gutenberg does need to be compatible with 6.0, since its goal is to support the last two major WordPress releases (which would be 6.1 and 6.0 currently). At least, that's what I've heard from others in the project!

**Comment by noahtallen** [comment] 2022-12-28 19:02
possibly fixed by #46806, will test

**Comment by noahtallen** [comment] 2022-12-28 19:21
Ok, so I've confirmed that the trunk branch is compatible with WordPress 6.0. This means that everything has been fixed! The challenge is getting those fixes into the 14.8.x release. Most of the fixes include changes targeted for the next Gutenberg release, so I need to make sure I'm not introducing new issues when porting over just the fixes.

The good news is that 14.9 will be compatible with 6.0, assuming nothing else breaks in the next week!

**Comment by noahtallen** [comment] 2022-12-28 19:48
I can fix compatibility in 14.8 by cherry-picking the following PRs into the release branch:

- https://github.com/WordPress/gutenberg/pull/46579
- https://github.com/WordPress/gutenberg/pull/46750
- https://github.com/WordPress/gutenberg/pull/46806
- https://github.com/WordPress/gutenberg/pull/46809

Explanations:
- "fix compat with 6.0.x" relies on the bundling of  the `WP_Theme_JSON` class. so we need both of those.
- #46809 is standalone compatibility fix
-  however those two aren't enough; we also need #46750 to fix the `has_same_registered_blocks` issue

So... the problem is now that #46579 and #46750 are _really_ big PRs. By cherry-picking just them, we potentially introduce new features or unfixed bugs that are intended for 14.9.... So I'm not entirely sure what to do. I'll reach out for some feedback

**Comment by noahtallen** [comment] 2022-12-28 21:46
I've mostly verified that those PRs don't introduce new changes (and are just refactors of code that already exists in 14.8), I think we can put them in a patch release. I'll definitely be testing them thoroughly before pushing anything.

**Comment by Otto42** [comment] 2022-12-28 23:05
Fair enough on adding 6.0 support back, but for the existing tags that are not compatible, somebody needs to retroactively edit them to have the compatibility tag correct. Just for sanity. And safety. We use that to prevent breaking sites, and right now, sites are being broken.

If you need any help with this email me.

**Comment by noahtallen** [comment] 2022-12-28 23:19
14.8.3 has been released, which should be compatible with WP 6.0. I unfortunately don't know how to retroactively change those headers for 14.8.0, 14.8.1, and 14.8.2. I doubt I even have direct access to the plugin repo to do so -- I'm only using the existing point release processes which goes through GitHub Actions.

You could also technically say that 14.8.0 wasn't compatible with any WordPress version, due to a severe issue with publishing posts that was fixed in 14.8.1

**Comment by oandregal** [comment] 2022-12-29 09:24
> So... the problem is now that https://github.com/WordPress/gutenberg/pull/46579 and https://github.com/WordPress/gutenberg/pull/46750 are really big PRs. By cherry-picking just them, we potentially introduce new features or unfixed bugs that are intended for 14.9.... So I'm not entirely sure what to do. I'll reach out for some feedback

I can confirm these are refactors: they bundle the code in a single class when it was before in multiple folders and classes inheriting from each other. If anything, it fixes bugs like the one raised here.

It seems the issue was introduced at https://github.com/WordPress/gutenberg/pull/46250 Apparently, it was reported and a [fix prepared](https://github.com/WordPress/gutenberg/pull/46363), though the fix missed the 14.8 window. To catch these things earlier, Gutenberg would benefit from running the CI tests in all the WordPress versions it supports. I presume most people test the PRs with only one WordPress runtime. cc @hellofromtonya @anton-vlasenko in case this is something in your radar.

I've tested that 14.8.2 breaks and 14.8.3 works fine again. Thanks for taking care of preparing the patch release, Noah!

**Comment by noahtallen** [comment] 2022-12-29 18:47
Very happy to hear! I'll close this issue now. But I definitely agree we _need_ to test compatibility before publishing the plugin. [There was a fatal error](https://github.com/WordPress/gutenberg/pull/46488) in the original 14.x releases as well, which only happened with WP 6.0 and PHP 8. So this is two releases in a row that haven't been compatible with WP 6 at first!

**Closed as completed by noahtallen** 2022-12-29 18:47 UTC
Labels: [Type] Bug, [Priority] High, Backwards Compatibility

**Comment by ockham** [comment] 2023-01-02 10:37
> But I definitely agree we need to test compatibility before publishing the plugin.

I wonder if we should run our existing test suite against `currentWordPress - 1` in CI 🤔 I guess that should cover a lot of these errors? Probably too much stuff to run on every single PR, but it might make sense to do upon release. Not quite sure how to best flag errors in such a scenario; we could drop them into the release draft maybe?

Or maybe we should run those tests upon merge to `trunk`? This would give some ongoing visibility via :x: marks next to those commits...

**Comment by noahtallen** [comment] 2023-01-03 19:31
Yes definitely. I think at the very least, the phpunit suite would have caught all of these issues. My impression is that the vast majority of issues are related to PHP compatibility, rather than client-side code. That kinda makes sense, since Gutenberg is _mostly_ self-contained on the client-side. It bundles almost everything it needs itself. Whereas in PHP, it relies on both PHP working as expected and WordPress working as expected.

So I think PHPunit with currentWordPress - 1 along with PHP 8 would do a pretty good job as a baseline. (PHP 8 seems to be stricter about types than PHP 7, meaning more fatals can happen)

**Comment by ockham** [comment] 2023-01-09 13:06
FWIW, PHP 8 coverage is also one of the goals of @hellofromtonya's #43333. I think that @anton-vlasenko actually has a PR to implement that ready for review: https://github.com/WordPress/gutenberg/pull/46510.

Edit: Since that PR also moves PHP unit tests from `unit-tests.yml` (which they share with JS unit tests) into their own workflow file, let's wait for it to land so that we can then consider adding `currentWordPress - 1` to the PHP unit test matrix.

**Comment by ockham** [comment] 2023-01-09 13:23
I've filed https://github.com/WordPress/gutenberg/issues/46979 to keep track of this.
