### ISSUE TITLE
Small spacing issue

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9749] opened 2018-09-10 14:33 UTC
The negative margin for second last panel of the settings 

Here is screenshot - https://goo.gl/WXJg4i

Advance CSS class should have this -ve padding instead of second last setting panel.

**Comment by youknowriad** [comment] 2018-09-10 14:37
Which version are you testing because this should be fixed now.

**Comment by prajaktagadhave** [comment] 2018-09-11 06:12
3.8.0

**Comment by prajaktagadhave** [comment] 2018-09-27 05:32
I still facing this issue in 3.9.0 too. Any update regarding this?

**Comment by youknowriad** [comment] 2018-11-26 18:03
Are you still seeing this issue? I can't reproduce in my testing. I'm closing for now, let's reopen if we find reproducible steps. (Maybe a browser issue)?

**Closed by youknowriad** 2018-11-26 18:03 UTC
Labels: [Status] Needs More Info
