### ISSUE TITLE
Merging two blocks then separating them does not work properly

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#35765] opened 2021-10-19 14:36 UTC
### Description

I run a newspaper site where people can send in press releases. When cleaning those releases, sometimes I need to merge two paragraphs and then separate them. I stand at the end of the first paragraph, press the Delete button to merge the first with the second paragraph and then press Enter to separate them.

When I press Enter, the text from the second paragraph is gone. When I press Ctrl-Z to get the text back and then again hit Enter, it works as it should. Used to work without a hitch before - I think - 5.8.

### Step-by-step reproduction instructions

1. open a post
2. place the cursor at the end of the first text block (heading or paragraph)
3. press Delete to merge the first and the second block
4. press Enter to separate them again
5. the text of the second block is gone
6. now press Ctrl-Z and the text of the second block reappears
7. press Enter again and the two blocks are as they schould be

### Screenshots, screen recording, code snippet

https://www.loom.com/share/ceee59535a614f9fa8e1eba68873abe1

### Environment info

WordPress version 5.8.1
Browsers: Chrome and Edge
Issue does not show on beta 5.8.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment] 2021-10-22 02:46
I can confirm this issue, it is a common problem for me when I edit texts, I would love to see this fixed.

**Comment by Mamaduka** [comment] 2021-10-27 08:24
@carolinan I are still able to reproduce the issue on the current Gutenberg `trunk`?

Merging and separation are working for me as expected. I'm wondering if I'm missing a step here.

**Comment by ellatrix** [comment] 2023-08-16 12:54
I also cannot reproduce. Would be good to have exact steps to reproduce from an empty post.

**Comment by karmatosed** [comment] 2024-11-28 15:55
I am in a similar situation and unable to replicate this. As a result, I think closing this is going to be my recommendation and action for now. This doesn't at all mean we can't reopen if further information surfaces on how to reproduce today. @carolinan, if you are still able to reproduce, please add that to this issue and either reopen yourself or I am happy to undo my closing.

Thank you, everyone, for collaborating on this.

**Closed as completed by karmatosed** 2024-11-28 15:55 UTC
Labels: [Type] Bug, [Status] Needs More Info, [Feature] Writing Flow, [Block] Paragraph, Needs Author's Reply
