### ISSUE TITLE
Block Style names truncate too aggressively

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#42707] opened 2022-07-26 15:55 UTC
### Description

When a Block style name is too long for the button, it is truncated and given a "..." at the end. However, it truncates too aggressively, replacing a single character with "..."

### Step-by-step reproduction instructions

1. Register a block style with the name "Subtle Border"
2. Insert the block and view the Style selection panel
3. See that "Subtle Border" has been truncated to "Subtle Borde...", which is less readable and actually longer.

### Screenshots, screen recording, code snippet

![2022-07-26 10_51_02-Edit Page “Block Showcase” ‹ Front End Wayfinder — WordPress](https://user-images.githubusercontent.com/945157/181052879-e33a1bc7-2ab1-4224-896d-c0a39de72e7a.png)

### Environment info

WordPress 6.0.1, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrwweb** [comment] 2022-07-26 16:39
Duplicate of #40331

**Closed as not planned** 2022-07-27 02:56 UTC
Labels: [Status] Duplicate
