### ISSUE TITLE
Syntax coloration in « HTML Block »

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#18597] opened 2019-11-18 23:39 UTC
**Is your feature request related to a problem? Please describe.**
Yes, the HTML code in black & white is difficult to read.

**Describe the solution you'd like**
That in HTML block to be able to activate or not syntax colouration, and why not with many theme’s.

**Describe alternatives you've considered**
In my study, to show code in my page next to JavaScript function,
I use [PrismJS](https://prismjs.com/), Okaidia (clear color & brown background) theme,
it would be interesting to use that script in W.P. HTML Block to edit easily,
or made on by our own.

**Comment by youknowriad** [comment] 2019-11-19 07:47
Duplicate of #10423

**Closed by youknowriad** 2019-11-19 07:47 UTC
