### ISSUE TITLE
Mobile/Tablet preview not applying correct styles

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/gutenberg#24002] opened 2020-07-16 17:58 UTC
**Describe the bug**
The tablet and mobile styles don't appear to be applied to the editor when using the 'Preview' options. 

This may be a duplicate of #21193, but it's also happening non-externally loaded CSS, so I opted to create a separate issue in case the cause is different. If not, please feel free to close! 

**To reproduce**
1. Running Gutenberg, and using a theme like Twenty Twenty, edit a post.
2. Click on Preview and pick Tablet. Compare font-size to front-end at that screen size.
2. Click on Preview and pick Mobile. Compare font-size to front-end at that screen size.

**Expected behavior**
That the font sizes would match between the preview and front end.

**Screenshots**
Tablet in editor:

![image](https://user-images.githubusercontent.com/177561/87705166-59705080-c752-11ea-9791-1fba41c1eda3.png)

Tablet on front-end (780px wide, like the editor preview and same browser size as above):

![image](https://user-images.githubusercontent.com/177561/87705866-6b062800-c753-11ea-96fc-be4151b28e22.png)

Mobile in editor:

![image](https://user-images.githubusercontent.com/177561/87705418-b835ca00-c752-11ea-8b37-a2150797662b.png)

Mobile on front-end (360px wide, like the editor preview and same browser size as above):

![image](https://user-images.githubusercontent.com/177561/87705914-81ac7f00-c753-11ea-9d7a-79bf7d54a41a.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it?  8.5.1

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser: Firefox
 - Version: 78.0.2

**Comment by carolinan** [comment] 2022-07-19 07:49
I am not able to reproduce using Twenty Twenty on WP 6.0.1, with and without Gutenberg Version 13.7.0-rc.1.
The text size is reduced correctly both in the editor and front.

**Comment by kathrynwp** [comment] 2022-08-04 21:23
@carolinan I took another look at this and I think I'm able still to replicate on heading tags within the body of the page/post content:

For example, here's what the page title, h2 and h3 look like in tablet preview in the editor:

![Cursor_and_Add_New_Page_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/182954023-bd297468-eede-47c3-b4ba-3293f7466368.jpg)

While the page title remains the same size, the h2 and h3 are displayed **larger** when the page is viewed at the a 780 tablet device size on the front end (using Firefox inspector):

![Page_Title_–_Self-hosted_Test](https://user-images.githubusercontent.com/7662449/182954743-0c438a55-8f64-4147-a94e-3d348087eb92.jpg)

I was not able to replicate with Twenty Twenty-Two, however.

What do you think?

Tested with:

WordPress 6.0.1
Gutenberg 13.8.0 active or inactive
No other plugins active
Theme: Twenty Twenty 2.0

Firefox 103.0.1 
macOS 12.2.1

**Comment by ellatrix** [comment] 2023-08-15 18:45
This should be fixed by #33342.

**Closed by ellatrix** 2023-08-15 18:45 UTC
Labels: [Type] Bug, Mobile Web, CSS Styling
