### ISSUE TITLE
Spacing controls: Can't edit units on unlinked controls

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#41845] opened 2022-06-21 17:06 UTC
### Description

When editing the values in an unlinked spacing control (padding, margin, etc), the unit can't be changed. If you switch back to the linked control, it's possible to update it, but then it sets the same unit for all sides.

Could be related to #37856

### Step-by-step reproduction instructions

1. Add a Cover or Group (or any other block with spacing controls)
2. Go to the Dimensions settings, enable padding if it's not, and click the "unlink" button
3. Try to change the dimension for the top padding
4. You can't 😞 

If you link the controls again, you can change the dimension for all.

### Screenshots, screen recording, code snippet

For example, here I want to add a top margin of 2rem to a columns block:

https://user-images.githubusercontent.com/541093/174855576-f5d8abaa-2859-431e-8ea3-e6187959105b.mp4

### Environment info

- WordPress 6.1-alpha-53448
- Gutenberg Version 13.4.0
- Mac OS + Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment] 2022-06-24 14:39
Strangely, this problem seems to be reproduced only in Firefox.
It isn't reproduced in Google Chrome.

Maybe it is related to the issue in [this comment](https://github.com/WordPress/gutenberg/issues/38113#issuecomment-1030857770).

**Comment by t-hamano** [comment] 2022-06-24 14:56
This problem was also reproduced in `BoxControl` component on StoryBook.
[https://wordpress.github.io/gutenberg/?path=/story/components-experimental-boxcontrol--default](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-boxcontrol--default)

So this might be a component issue.

Furthermore, this problem was not reproduced by keyboard operation (arrow move + `enter`).
It seems to be reproduced only when mouse clicking on a value in the dropdown.

https://user-images.githubusercontent.com/54422211/175563875-da443364-c2f3-4baf-bbaf-2b7a96c51914.mp4

**Comment by t-hamano** [comment] 2022-06-24 15:24
I found an interesting [comment](https://github.com/facebook/react/issues/12584#issuecomment-383233455) in react repository about this problem.
I would like to do some research to see if this issue is relevant.

**Comment by ciampo** [comment] 2022-07-19 13:28
cc @andrewserong and @aaronrobertshaw

**Comment by t-hamano** [comment] 2022-07-23 09:46
@ryelle 

We were able to solve this problem with #42483.
After testing again, we no longer reproduce this issue and would like to close it.

If the issue has not been resolved, please feel free to reopen it.

**Closed as completed by t-hamano** 2022-07-23 09:46 UTC
Labels: [Type] Bug, Browser Issues, [Package] Components, [Feature] Design Tools
