### ISSUE TITLE
[Feature Request] Add a placeholder image to the image block

### ISSUE THREAD

**Issue by samxmunoz** [WordPress/gutenberg#42006] opened 2022-06-28 12:12 UTC
### Issue

If you don't have an image in mind while building with blocks, it can throw off the layout of a project to see a spaced "placeholder" on the editing view but nothing in the live version of the page. 

![Screen Shot 2022-06-28 at 8 03 19 AM](https://user-images.githubusercontent.com/43501707/176174141-1846ae6f-563e-4ea8-a98a-ef86ab83b6ed.png)

![Screen Shot 2022-06-28 at 8 03 27 AM](https://user-images.githubusercontent.com/43501707/176174162-f636de23-1acc-4bbe-ab81-9eb007f67217.png)

### Proposed Solution

Add a placeholder image to the image block (perhaps a landscape default placeholder with the WordPress logo, or allow a random placeholder pulled in from an API from a royalty free photo suite like Unsplash _or_ even better, utilize Openverse).

If a WordPress logo default placeholder image, maybe something like these (created with ❤ by me using the **[Graphics & Logos](https://wordpress.org/about/logos/)** open source imagery + Canva) 

![Blue WP Logo - Image Placeholder](https://user-images.githubusercontent.com/43501707/176175314-e5f39409-01ea-4bd5-9941-a01c35f1dcdf.png)
![Dark WP Logo - Image Placeholder](https://user-images.githubusercontent.com/43501707/176175318-c3466474-64b9-4973-8d7d-89352276dfa4.png)
![Light WP Logo - Image Placeholder](https://user-images.githubusercontent.com/43501707/176175320-05b400bd-242e-4446-8743-f419296bfb5c.png)

**See it in action...**

![Screen Shot 2022-06-28 at 8 12 08 AM](https://user-images.githubusercontent.com/43501707/176175468-384b779b-53cc-4a6e-95a3-6267888e60cd.png)

**Comment by colorful-tones** [comment] 2022-06-28 14:45
This may be a duplicate of https://github.com/WordPress/gutenberg/issues/41142

**Comment by annezazu** [comment] 2022-06-30 06:26
I'm going to close this out as a confirmed duplicated. If there's something that feels distinctive about this issue though, just let me know and I'll reopen!

**Closed as completed by annezazu** 2022-06-30 06:26 UTC
Labels: [Type] Enhancement, [Block] Image
