### ISSUE TITLE
Site editor: Random Template order 

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#56079] opened 2023-11-13 10:17 UTC
### Description

In the site editor the templates are not displayed in an alphabetical order (I'd expect it to be alphabetically) 

### Step-by-step reproduction instructions

1. Go in the site editor
2. Change the template / see that the order is messed up

### Screenshots, screen recording, code snippet

Theme | Site Editor | Expected (Quick Edit) |
|--------|--------|--------|
|custom| <img width="299" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/5e4ad128-1b32-4106-903a-8e59a6a35dc0"> | <img width="375" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/446dc123-dd25-4043-b100-931d19c29204"> |
|TT4|<img width="284" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/34b0d6ec-8e98-4fb1-b945-da52f3f85e2f">|<img width="274" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/5639a9a8-9e7d-488f-a70a-a8f8a0604b5b">|

### Environment info

- WP 6.4.1
- GB 17.0.1 and without

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment] 2023-11-14 12:43
In the editor we have yet another order:
<img width="345" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/005d2f1b-7c61-4bde-b306-587b92080f3e">

**Comment by annezazu** [comment] 2023-11-14 16:44
Adding to Polish as this has come up a fair amount, especially when the 404 template was rendering first in the list. cc @WordPress/gutenberg-design.

**Comment by annezazu** [comment] 2023-11-14 17:26
Ah! This was the issue I couldn't pull up that relates: https://github.com/WordPress/gutenberg/issues/48651

**Comment by richtabor** [comment] 2023-11-23 01:25
I would consider this a duplicate of #48651, closing this in favor of that issue — which explores possible solutions a bit more. Thoughts?

**Comment by annezazu** [comment] 2023-11-23 02:18
Sure, let's do that.

**Closed as completed by annezazu** 2023-11-23 02:18 UTC
Labels: [Type] Bug, [Feature] Templates API

**Comment by hanneslsm** [comment] 2023-11-23 06:53
> I would consider this a duplicate of https://github.com/WordPress/gutenberg/issues/48651, closing this in favor of that issue — which explores possible solutions a bit more. Thoughts?

well, yes - when it comes to the black site editor. 
This issue here was mainly to adjust the order of the template dropdown to fit the quick edit dropdown. I hoped that'd be a quick fix. 
The drop downs must be revisited anyways after an order in the site editor is decided on and how things like headings are handled, for example.
