### ISSUE TITLE
Site Editor: left panel items are black on dark background

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#31697] opened 2021-05-11 11:17 UTC
## Description

In 10.6.0-rc1 some of the items in the Site Editor left panel are black on a dark background, making them unreadable.

## Step-by-step reproduction instructions

Go into Site Editor.
Click the WP icon at top left to open the side panel.
Notice some of the items are black on the dark background.

## Expected behaviour

All the items should be readable against the dark background.

## Actual behaviour

Some of the items are black on the dark background.

## Screenshots or screen recording (optional)

![gutenberg-left-panel-dark-text](https://user-images.githubusercontent.com/76742815/117806680-8ac28b80-b252-11eb-9309-f777247d298b.png)

![gutenberg-left-panel-dark-text-02](https://user-images.githubusercontent.com/76742815/117806702-901fd600-b252-11eb-8a96-3d102735cdf5.png)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6.0-rc1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks and others all same result

## Device information
- Device: Desktop
- Operating system: W10
- Browser: Chrome and Firefox

**Comment by paaljoachim** [comment] 2021-05-11 22:43
Hi @Sandstromer 

Thank you for the report! I am seeing the same thing.
WordPress 5.7.1. Gutenberg plugin 10.6.0 - rc1. TT1 blocks theme.

![Screen Shot 2021-05-12 at 00 42 31](https://user-images.githubusercontent.com/5323259/117893626-0fe18b00-b2bb-11eb-865b-3b9b6a92c3b5.png)

**Comment by jasmussen** [comment] 2021-05-12 06:48
I think this is a duplicate of #31574, so closing as such. Please reopen if this was in error!

**Closed as completed by jasmussen** 2021-05-12 06:48 UTC
Labels: [Type] Bug, [Type] Regression
