### ISSUE TITLE
Autosave notification covers Permalink

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8064] opened 2018-07-20 03:24 UTC
**Describe the bug**
The Autosave notification covers the Post/Page permalink.

![screenshot_744](https://user-images.githubusercontent.com/2078245/42981412-5562d9f6-8c1f-11e8-9a50-ba843c6fbf8c.png)

**To Reproduce**
1. Open an existing page to edit
2. Wait until the page has auto-saved
3. Exit page and then re-edit the page. The Autosave notification should now appear
4. Click on the Page/Post title and try to view or change the permalilnk

**Expected behavior**
Notifications should never cover any content

**macOS Sierra 10.12.6 (16G1510)
Firefox 61.0.1 (64-bit)
Gutenberg 3.2.0**

**Comment by designsimply** [comment] 2018-07-20 19:17
Duplicate of #4172 which was closed with a comment saying that the notification is not permanent and it's okay to have the overlap since the notice is not permanent and can be dismissed.

Consider closing. Would ❤️ a 2nd opinion for good measure. 🙂

**Comment by maddisondesigns** [comment] 2018-07-21 08:39
What about getting rid of all the postion styles (i.e. `left`, `top`, `position` etc.) and just placing the notifcation above the content so it doesn't cover it, regardless of whether you dismiss it or not

![screenshot_246](https://user-images.githubusercontent.com/2078245/43033860-2838fbee-8d15-11e8-92d5-c0ac8fe7d6c3.png)
.

**Comment by designsimply** [comment] 2018-08-01 14:25
Because notices are meant to be read and closed and because it's possible for there to be multiple notices and pushing content down for multiple notices could cause more problems rather than helping, notices should be dismissed before continuing to edit.

Closing because this was asked and answered in #4172. Thank you for the feedback!

**Closed by designsimply** 2018-08-01 14:25 UTC
Labels: UI Components, [Status] Duplicate
