### ISSUE TITLE
Tools menu styling adjustment suggestions

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19447] opened 2020-01-06 21:26 UTC
The tools menu could do with a few iterations in current version:

![image](https://user-images.githubusercontent.com/253067/71849920-13fc0800-30cb-11ea-8445-11cf885aed68.png)

Suggestions:

- Stronger focus state or none on first open as there is a really weird almost layered visual to the menu.
- Spacing between Select and icon

**Comment by mapk** [comment] 2020-01-07 17:51
The alignment looks good on my live site. 

![Screen Shot 2020-01-07 at 9 47 25 AM](https://user-images.githubusercontent.com/617986/71916608-290c8180-3133-11ea-9434-b097560970f1.png)

The icon angles cause a visual weirdness, but everything is aligned correctly. Maybe this is a local build issue, @karmatosed ? I have this problem on my local `wp-env` build too.

**Comment by karmatosed** [comment] 2020-01-08 14:15
@mapk it now is fine for me having reset my entire wp-env. I still find the hover weird though.

**Comment by mapk** [comment] 2020-01-08 17:40
Ah ha! I just tested this again in another live site and found the alignment issue. Here's a screenshot:

![Screen Shot 2020-01-08 at 9 37 15 AM](https://user-images.githubusercontent.com/617986/72001684-ced6f380-31fa-11ea-9146-508971932d00.png)

The Title is also wacky below the popover and not aligning with the content similarly to how our local environments were. 

This is a real issue that goes beyond our local environments.

**Comment by 0aveRyan** [comment] 2020-04-02 23:38
@mapk @karmatosed I'd love to see keyboard shortcuts inline on the modes for clarity like they are in the Main Menu, then use the description to describe more _why_ instead of _how_

<img width="261" alt="Screen Shot 2020-04-02 at 4 35 52 PM" src="https://user-images.githubusercontent.com/9565066/78309610-55e8ee80-7500-11ea-8cef-7d5797d05480.png">

**Comment by jasmussen** [comment] 2020-04-03 08:48
Hey @0aveRyan — you probably found a regression there, I could swear those keyboard shortcuts used to be visible, or maybe I'm misremembering? I do agree, by the way, they should be present! 

The question is how, though — as I recall it, we showed the keyboard shortcut conditionally based on whether it worked or not. For example if you have the edit tool selected, pressing Enter will make a line-break rather than ... well, select the too you already have. Similarly, if you're using the select tool, Enter returns to edit mode, but pressing Escape again doesn't do anything.

**Comment by 0aveRyan** [comment] 2020-04-03 16:10
@jasmussen yep I went back and edited that comment because I realized `Enter` would create a new empty Paragraph in Edit.

As you indicated, showing keyboard shortcuts only for inactive navigation tools seems a good solution.

**Comment by jasmussen** [comment] 2020-04-08 07:33
Very possibly just a design mock that I'm remembering! 

If you'd like to open that PR, I'll help shepard it through. Go forth and conquer!

**Comment by 0aveRyan** [comment] 2020-04-09 00:54
@jasmussen I've started some of this in #21497, however something I wanted to bring up.

When a Block is selected, using `Escape` as a keyboard shortcut correctly toggles the Mode. However, if the focused element is the Navigation Tools menu (i.e. a user clicks the Navigation Tools menu and then try the Escape shortcut), the Popup simply closes and the mode doesn't toggle.

Neither of the shortcuts are very "global" shortcuts... if a user is in an input or textarea in the sidebar and types enter, the tool doesn't toggle either. 

I like the simplicity and predictability of the shortcuts... I'm not crazy about subsituting in a combo shortcut. But also now wondering whether they should be shown on the menu items. Thoughts?

**Comment by jasmussen** [comment] 2020-04-09 06:12
That is a doozy, and this is possibly why we ended up never adding those keyboard shortcuts in the first place. I'm skeptical now also. After all, when you see this:

<img width="729" alt="Screenshot 2020-04-09 at 08 10 03" src="https://user-images.githubusercontent.com/1204802/78863304-8ae1cd80-7a39-11ea-9799-c09939fd5fe0.png">

in that particular moment, ⌘B does indeed make the text bold. Whereas neither enter nor escape work as suggested when you read that text.

Perhaps we should course correct and instead add to this sheet instead?

<img width="495" alt="Screenshot 2020-04-09 at 08 09 24" src="https://user-images.githubusercontent.com/1204802/78863349-a3ea7e80-7a39-11ea-8a46-211ab409238f.png">

We could add some items under "Block shortcuts". Or add a new section. What do you think?

**Comment by 0aveRyan** [comment] 2020-04-09 18:22
@jasmussen Doozy indeed 😎 

A few thoughts based on your comments:
* ✅I like adding `Enter` and `Escape` to the **Block shortcuts** in the modal.
* ⚠️I worry about duplicating `Escape` functionality to both close the Popover and toggle mode... Escape has a long-established UX pattern. It makes sense when in a Block, I don't think it makes sense in the Popover to take both actions.
* ℹ️ Notably, near every icon button in the top left has some form of global or widely-available keyboard trigger. There's the `/` inserter, Undo, Redo and Block Navigation all can be triggered via keyboard shortcuts. Only the Content Info/Outline lacks a keyboard shortcut (separate issue, but perhaps worth addressing).
* 💡What if we maintain the current Block shortcuts, but add a global keyboard shortcut for cycling through Tools (i.e. [`Alt + Shift + Tab`](https://defkey.com/what-means/alt-shift-tab))? Similar to an OS-level pattern for cycling through open applications, we could have something like `alt + tab` (Win), `cmd + tab` (macOS), `super + tab` (ubuntu). This could trigger a similar modal with Edit, Select and future Tools.
![Screen Shot 2020-04-09 at 11 11 45 AM](https://user-images.githubusercontent.com/9565066/78927157-3ea38700-7a53-11ea-9123-91cdf8a35ad1.png)

Which brings me to...
* _**🤔How important is having this toggle in the top toolbar?** Does this feature require its' prime real estate -- can it be relocated? Does seeing the current mode persist 100% of the time aid users -- how frequently do we expect them to switch Tools?_ I totally see the value of these tools. Navigation Tools definitely _don't_ belong in the Block Toolbar or Menu, nor the Document Toolbar. But would a global keyboard toggle, perhaps combined with a snackbar or "tool switcher modal" when mode is toggled suffice? Forgive me for playing devil's advocate, I see arguments for both keeping/relocating, but I perhaps lean towards the latter.

**Comment by jasmussen** [comment] 2020-04-10 06:05
> I worry about duplicating Escape functionality to both close the Popover and toggle mode... Escape has a long-established UX pattern. It makes sense when in a Block, I don't think it makes sense in the Popover to take both actions.

Yep. Let's not do that then. We can always revisit if we come around to it again.

> What if we maintain the current Block shortcuts, but add a global keyboard shortcut for cycling through Tools (i.e. Alt + Shift + Tab)? Similar to an OS-level pattern for cycling through open applications, we could have something like alt + tab (Win), cmd + tab (macOS), super + tab (ubuntu). This could trigger a similar modal with Edit, Select and future Tools.

I think this is an idea that could potentially work, but with "only two tools" it feels like a little much at this point, which seques into my answer to your next one ...

> How important is having this toggle in the top toolbar? 

Key question to ask, and I do feel it is very important. Because it's more than just a tools selector, it is also a _editing mode indicator_, and this aspect is much much more important, and in fact one of the key factors in adding the item there in the first place.

Selection mode, or the select tool, or navigation mode, it's had many names — this is the interface where you can press tab 20 times to select the 20th block in a long post. This is a key affordance for screen readers so as to avoid having to tab through endless tabstops on your journey. It has a number of additional benefits:

- Dig through layer by layer in complex nesting situations, click selects the columns block first, then the column, then contents of the column. 
- When editing, press Escape to _select the block_, press Delete to remove it, press Enter to return to editing. A power user flow where you float in and out of these two tools/modes.

![select and edit](https://user-images.githubusercontent.com/1204802/78966883-3bff6b00-7b01-11ea-9e43-5d20e12648a9.gif)

Key to this experience, though, is visualizing what's going on, surfacing what happens. To some users they might be confused why suddenly they click to start editing a block and it has a blue border when they expected a caret. They can click again to edit so it will probably not stump them for long. But if they are to ever discover what is actually going on, it's important we surface visually the mode indicator, same as how in Photoshop you might click the canvas to select and instead you paint — "oh, I had the paintbrush selected". 

I think your idea of a snackbar notification is an interesting one! And I do applaud you for asking questions that serve to _reduce_ — more often than not I see the inverse. But I feel it does serve an important purpose.

**Comment by mapk** [comment] 2020-04-14 00:05
Our conversation here has taken quite the turn. Can we move the requests to separate issues? I'm closing this one out as being fixed. 😄 

1. Adding keyboard shortcuts for the Select/Edit tools. (or is this just not possible?)
2. Whether or not to include that tool in the top toolbar.

cc @jasmussen  and @0aveRyan.

In response to topic of the issue, I tested it recently and found no more problems.

![Screen Shot 2020-04-13 at 5 00 44 PM](https://user-images.githubusercontent.com/617986/79172194-dcc38400-7da8-11ea-90ea-babeef120ddd.png)

**Closed by mapk** 2020-04-14 00:05 UTC
Labels: Needs Design Feedback

**Comment by jasmussen** [comment] 2020-04-14 06:20
> Adding keyboard shortcuts for the Select/Edit tools. (or is this just not possible?)

Given the keyboard shortcuts aren't global, they really only work in context of the cursor, any additional keyboard shortcuts we create aren't going to solve any problems here. But it was good to learn this!
