### ISSUE TITLE
Columns don't work with dynamic blocks on front-end

### ISSUE THREAD

**Issue by miljushm** [WordPress/gutenberg#7567] opened 2018-06-27 10:45 UTC
**Describe the bug**
When I add a columns (beta) block and add a dynamic block in each column, everything shows OK on the admin side however blocks are displayed in a wrong way on the front-end. They are not shown from left to right but from top to bottom.

**To Reproduce**
1) Add columns (beta) block to the editor with two columns
2) Add one dynamic block to the left side (column 1) and another dynamic block to the right side (column 2)
3) You probably see what you wanted to achieve in the admin
4) Go to the front-end and you'll see content of the second column displayed bellow the content of the first column. 

**Expected behavior**
Should be shown same as it's shown in the admin.

**Additional context**
- I've noticed that block in the admin has following classes wp-block-columns has-2-columns then blocks have classes like layout-column-1 and layout-column-2 
- however, on the front, block has class has-2-columns but each inner block doesn't have classes layout-column-1 and layout-column-2 which is actually the core of the issue.

**Comment by designsimply** [comment] 2018-06-27 17:43
Thank you for the report! Closing as a duplicate of #7518 and #5351.

**Closed** 2018-06-27 17:43 UTC
Labels: Blocks, [Type] Bug
