### ISSUE TITLE
Env: access denied for user 'root@x.x.x.x'

### ISSUE THREAD

**Issue by ckanitz** [WordPress/gutenberg#29829] opened 2021-03-12 15:28 UTC
## Step-by-step reproduction instructions
Related issue: https://github.com/WordPress/gutenberg/issues/29752
Related PR: https://github.com/WordPress/gutenberg/pull/29800

- install wp-env
- implement changes from related PR (since a version containing those changing is still pending atm)
- run `wp-env start`

--
So basically: I ran into the issue described in #29752 and since the changes of #29800 haven't been pushed to a new npm package version I implemented the changes myself to get the environment running.

After I added the changes to my local installation of wp-env I ran into the same error but with `root` instead of `username_here`.

I had a look at the rest of the code, checked the created docker-compose.yml and finally ran into this SO: https://stackoverflow.com/questions/49182448/mariadb-error-1045-28000-access-denied-for-user-rootlocalhost-using-pas

So with this I changed `password` in `lib/config/db-env.js` to `longpassword`, hit `wp-env start` and it was working again.

## Expected behaviour
Everything to work

## Actual behaviour
error 1045 access denied for user 'root@x.x.x.x' ...

## Device information
- Device: Macbook Pro
- Operating system: OS X 10.14.6

**Comment by ribaricplusplus** [comment] 2021-03-13 20:52
It's unlikely that changing the password is what caused things to work again. This issue is described in the same PR you referenced, in this comment and the one below it: https://github.com/WordPress/gutenberg/pull/29800#pullrequestreview-610266104

Everyone will need to run `wp-env destroy` and then `wp-env start` to get things working again.

**Comment by talldan** [comment] 2021-03-15 04:11
Closing as a duplicate of #29752.

**Closed by talldan** 2021-03-15 04:11 UTC
Labels: [Package] Env, [Status] Duplicate

**Comment by talldan** [comment] 2021-03-15 04:15
Ah, I see now this isn't so much a duplicate.

I agree `wp-env destroy` is the best remedy. Not sure what can be done beyond that. A note in the README could be an option.
