### ISSUE TITLE
extraProps.className not working with core/latest-posts and others

### ISSUE THREAD

**Issue by marcosrego-web** [WordPress/gutenberg#36127] opened 2021-11-01 22:07 UTC
### Description

I'm using the filter editor.BlockEdit to add options to core blocks and those options add classes using the filter blocks.getSaveContent.extraProps and the function extraProps.className .

It's working on most blocks, but for some reason no classes area added to blocks such as core/latest-posts, core/latest-comments and the latest core blocks from WP5.8 such as core/query-title and core/post-terms

### Step-by-step reproduction instructions

1- Paste the gist code on the url given below into a index.js file created with npx @wordpress/create-block
_(It should be okay to use, might have mistakes because I quickly shorten it a lot for this report)_

2- Add a "Latest Posts" block and select it.

3- Change "animation" option to something like "Fade".

4-  The classes "mr-fade active" are applied on the backend but are not applied in the frontend as it should
(in other blocks such as paragraph, image, heading and more it is working properly). 

### Screenshots, screen recording, code snippet

[https://gist.github.com/marcosrego-web/8b6d873ea7bd086ae5fce8f883a9b800](https://gist.github.com/marcosrego-web/8b6d873ea7bd086ae5fce8f883a9b800)

### Environment info

- localhost
- 5.9-alpha-51961
- Gutenberg 11.8.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marcosrego-web** [comment] 2021-12-13 22:57
I see this is still with the label Needs testing, here's an easier way to whoever test this:

On this page of [Wordpress Block Editor Handbook](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-getsavecontent-extraprops), the following code is mentioned:

```
function addBackgroundColorStyle( props ) {
    return lodash.assign( props, { style: { backgroundColor: 'red' } } );
}
 
wp.hooks.addFilter(
    'blocks.getSaveContent.extraProps',
    'my-plugin/add-background-color-style',
    addBackgroundColorStyle
);
```

Its said: **"Adding a background by default to all blocks."**

But in fact, also this code does not work for blocks such as the ones I mentioned above.

Couldn't figure out the problem yet, it would be awesome if someone could help solving this.

**Comment by surajkrsingh** [comment] 2022-01-07 10:50
I have the same issue and hook `blocks.getSaveContent.extraProps` not working for all new theme blocks.

```
"core/navigation",
"core/site-logo",
"core/site-title",
"core/site-tagline",
"core/post-author",
"core/post-date",
"core/post-template",
"core/post-excerpt",
"core/post-featured-image",
"core/post-title",
"core/post-content",
"core/post-terms",
"core/term-description",
"core/post-comments",
"core/loginout",
"core/query-title",
"core/query-pagination-numbers",
"core/query-pagination-next",
"core/query-pagination-previous",
"core/query-pagination",
"core/post-navigation-link"

```
Tested with WP 5.9 RC1
I want to extend the block properties but it is not working for these above blocks.

**Comment by easilyamused** [comment] 2022-02-22 08:23
Any status update on this bug?

**Comment by surajkrsingh** [comment] 2022-03-24 11:30
All new theme blocks support apiVersion:2 and the filter `blocks.getSaveContent.extraProps` support has removed for them.

Here commit - https://github.com/WordPress/gutenberg/commit/c0c8ca055b0e8d018b2de5cab55320dc99d608a0#

Can somebody explain, why support for this filter removed for apiVersion:2 supported blocks ?
And is there any other way to extend the theme block properties?

![image](https://user-images.githubusercontent.com/19591301/159906148-78f69bbd-ebc5-41b5-bf3d-80299a39407e.png)

@gziolo

**Comment by gziolo** [comment] 2022-03-24 11:50
@ellatrix, can you explain why `blocks.getSaveContent.extraProps` doesn't work with `apiVersion` v2 anymore?

**Comment by easilyamused** [comment] 2022-04-01 03:25
@ellatrix could you help us out on this topic, please. 

We have been blocked for a couple of months.

**Comment by easilyamused** [comment] 2022-04-22 04:49
I know I might be coming across as rude but this has been blocking several people for 6 months now. 

@ellatrix, can you please explain why blocks.getSaveContent.extraProps doesn't work with apiVersion v2 anymore?

**Comment by mcsf** [comment] 2022-04-22 11:38
@easilyamused: I'm sorry about the silence. Ella is on extended leave, so @gziolo and I are looking at this. We'll get back to you.

**Comment by mcsf** [comment] 2022-04-22 15:51
Alright, I spent some time looking at this to refresh my memory.

The matter of `apiVersion` and `lightBlockWrapper` is a red herring. Those APIs are not affecting the `blocks.getSaveContent.extraProps` and other filters. Moreover, those filters are working as expected. Let me explain.

## Save-time filters

`blocks.getSaveContent.extraProps` is a **client-side filter**. Specifically, it fires upon block serialisation and is meant to filter the properties that are ultimately attached to the outermost element of a block's **static markup**. However, all the block types mentioned in this issue — Latest Posts, Navigation, FSE blocks — are **dynamic** blocks.

Let's take `core/latest-posts` as an example. Notice that it [registers an `edit` method but no `save` method](https://github.com/WordPress/gutenberg/blob/a0e1728bc29fdbcc60ab571cf15ff657fd887c89/packages/block-library/src/latest-posts/index.js#L16-L21). You can confirm in the Code Editor or in the database that the block is serialised without any inner markup:

```html
<!-- wp:latest-posts /-->
```

It should become apparent why `blocks.getSaveContent.extraProps` is never applied to this block: there is nothing to save.

Note that there are other save-time hooks, including [`blocks.getSaveElement`](https://github.com/WordPress/gutenberg/blob/f7dbd0dcf10a48b8723a6eab2e4d6285ffa352f9/docs/reference-guides/filters/block-filters.md#blocksgetsaveelement). Their constraints are similar.

## The changes around `apiVersion`

> Can somebody explain, why support for this filter removed for apiVersion:2 supported blocks ?

The filter was never removed. What that commit did was ensure that we didn't run the same filter twice. That's because blocks that satisfy `hasLightBlockWrapper` are expected to interpolate `{ useBlockProps.save() }` in their `save` method, which already invokes the filter in question (_cf._ `getBlockProps`).

## The case of custom class names

You may be wondering: if `blocks.getSaveContent.extraProps` only works with static blocks, how come dynamic blocks seem to support the `customClassName` feature? That is because the feature comes with a [server-side implementation](https://github.com/WordPress/wordpress-develop/blob/9a8d52395c299a289187843fea27ac1bf4250a56/src/wp-includes/block-supports/custom-classname.php) too.

* Read more: [Block Supports](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/block-supports-in-static-blocks/)
* Read more: [Block Supports in dynamic blocks](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/block-supports-in-dynamic-blocks/)

## Workarounds

If you'd like to intercept dynamic blocks, you'll have to filter on the server. Depending on your needs, you could implement something more formal using block-supports just like `customClassName`, or you could implement something more _ad hoc_. For the former, take a look at how [typography support is implemented](https://github.com/WordPress/gutenberg/blob/ace064391f2ce2d96c30a0c8761a5d2a985b9c5b/lib/block-supports/typography.php#L209-L215). For the latter, the `'render_block'` hook is probably what you want. I played with @marcosrego-web's snippet, and below is a working example based on it.

```php
// Server-side filter 
function g36127_render_foo( $block_content, $block ) {
	if ( ! $block_content || ! isset( $block['attrs']['foo'] ) ) {
		return $block_content;
	}

	$injected_class = 'foo-' . $block['attrs']['foo'];
	return preg_replace(
		'/' . preg_quote( 'class="', '/' ) . '/',
		'class="' . esc_attr( $injected_class ) . ' ',
		$block_content,
		1
	);
}

add_filter( 'render_block', 'g36127_render_foo', 10, 2 );
```

@marcosrego-web and @easilyamused: I hope that the context, resources, and examples I've provided are helpful. I'm going to close this issue, as everything is behaving as intended, but feel free to reach out if you need more guidance.

**Closed as completed** 2022-04-22 15:55 UTC
Labels: [Type] Help Request, [Status] Not Applicable

**Comment by easilyamused** [comment] 2022-04-22 17:32
Thanks for the feedback @mcsf. I will review with my dev team and report back.

**Comment by mateuswetah** [comment] 2022-05-30 23:09
@mcsf, can't express how enlightening your comment was... I've been trying to do this for a while. I feel like there should be some mention to these dynamic blocks incompatibility with the client-side filters here:
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters.
It makes all sense once you now the internals, but really, for new developers that are just building theme it is not obvious.

**Comment by mcsf** [comment] 2022-05-31 17:22
> @mcsf, can't express how enlightening your comment was... I've been trying to do this for a while.

Thanks, I'm glad it helped. :)

> I feel like there should be some mention to these dynamic blocks incompatibility with the client-side filters here:
> https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters.
> It makes all sense once you now the internals, but really, for new developers that are just building theme it is not obvious.

Yes, those docs could use some improvement for sure. They work in the small but not so much in the large; they could be complemented with a high-level explanation (in the vein of Matías's old [How Little Blocks Work](https://make.wordpress.org/core/2017/05/05/editor-how-little-blocks-work/) and our [The Language of Gutenberg](https://lamda.blog/2018/04/22/the-language-of-gutenberg/)), and maybe with an explicit caveat about dynamic blocks. /cc @juanmaguitar as this is maybe something to be on your team's radar. :)

**Comment by gilsonviana** [comment] 2022-11-11 22:01
Unfortunately I stumbled upon this issue today only to find out there's no way around using JS with filter hook.
But a solution I found was to apply the modifications to the `core/group` and then wrap my elements with it.
