### ISSUE TITLE
How to have both static and dynamic content in the same block

### ISSUE THREAD

**Issue by miljushm** [WordPress/gutenberg#7568] opened 2018-06-27 10:52 UTC
Is it possible to have a block which will render on the server and also have a static text before the dynamic content?

For instance, I've converted a shortcode to a Gutenberg block and upon edit I do this:

el(ServerSideRender, {
                block: "example/shortcode-name",
                attributes: props.attributes
            }),

which retrieved the content rendered on the server (in this case, it gives the number of sold products - pure number). That one works like a charm.

However, I'd like to have results like this "Sold: 56" or "56 Sold Already" instead of just getting "56". That "Sold" or "Sold Already" would be a static input by a user.

Thanks in advance!

**Comment by katerlouis** [comment] 2018-06-27 11:19
Similiar issues

#7331
#5760 #5968 #6239

**Comment by miljushm** [comment] 2018-06-27 11:29
So, that's not possible yet?

**Comment by katerlouis** [comment] 2018-06-27 11:33
Mixing dynamic rendering together with static content generated by gutenberg directly is currently not possible as far as I know.

**Comment by miljushm** [comment] 2018-06-29 09:50
I know for that one since that's probably the only way. However, in that case I would need to have two extra fields like BEFORE number and AFTER number content fields which is really now user friendly if you know what I mean.

**Comment by mcsf** [comment] 2018-07-17 13:40
Closing as duplicate of #5760.

**Closed by mcsf** 2018-07-17 13:40 UTC
Labels: [Type] Help Request
