### ISSUE TITLE
CSS and add Link Issue

### ISSUE THREAD

**Issue by hadezuka** [WordPress/gutenberg#8419] opened 2018-08-03 07:22 UTC
Usually I am using old editor with specific css class (using copy and paste post template), but when I use this plugin (at least trying) my css removed. I have many css in there and I wont edit my post line by line as it is wasting my time. And when editing link, it's always wont change till I clik enter/click twice (not happen in current editor), and also when I want to add other post link I cant find any of my post list on different post_type. 

Sorry for my bad english.
Thanks.

**Comment by youknowriad** [comment] 2018-08-03 11:02
If you have a specific markup you want to keep as is in Gutenberg, you can use the "HTML" block directly or even the "Classic" editor block. Does that work for you?

I can't reproduce the link issue personally, can you record a screenshot or something? it's not very clear?

> I want to add other post link I cant find any of my post list on different post_type.

This is true in the last released Gutenberg version but in the next update (which is coming very soon I think), you'll be able to do so. Related #7894

**Comment by designsimply** [comment] 2018-09-13 22:05
Usually I am using old editor with specific css class (using copy and paste post template), but when I use this plugin (at least trying) my css removed.

I am closing this issue for now. If you are still having trouble and are able to reply with a CSS example, then we can continue the discussion even if the issue is closed.

> And when editing link, it's always wont change till I click enter/click twice.

I tested this and was unable to see the problem happen. Perhaps it has been solved already? If you still see the problem, please reply back and let me know your OS and browser version so I can test with the same.

**Closed by designsimply** 2018-09-13 22:05 UTC
Labels: [Status] Needs More Info, [Type] Help Request
