### ISSUE TITLE
Categories not shown when publishing a post

### ISSUE THREAD

**Issue by alexdezi** [WordPress/gutenberg#17734] opened 2019-10-03 01:18 UTC
I am having the issue that the categories are not shown when writing a new post to users, when they don't have the capability to manage categories. The issue only arises when ithemes security plugin is installed. The plugin author says the issue lies within Wordpress.

I am using the Advanced Access Manager to create user roles and to their capabilities. When the user role has the capability of "manage categories", they can also select a category when creating a post.

1. Install and activate ithemes security
2. create a user with the user role "contributor"
3. create a new post and try to select a category
4. None of the categories are shown

Wordpress and plugins are all up to date and the error was reproduced when only ithemes security was installed - again, according to ithemes the bug is within wordpress.

**Comment by tellthemachines** [comment] 2020-04-16 05:50
Hi there, thanks for your report! 

This sounds like a duplicate of #6942 which [was found to be due to the ithemes plugin](https://github.com/WordPress/gutenberg/issues/6942#issuecomment-391802619). 

With no plugins enabled, it is possible for Contributor level users to access the Categories section, so I am closing this issue.

**Closed by tellthemachines** 2020-04-16 05:50 UTC
Labels: Needs Testing, [Feature] Document Settings, [Feature] REST API Interaction, [Type] Plugin Interoperability
