### ISSUE TITLE
You are trying to edit an item that doesn't exist. Maybe it was deleted error while seeing page, cpt and articles

### ISSUE THREAD

**Issue by maurodf0** [WordPress/gutenberg#67695] opened 2024-12-06 14:54 UTC
### Description

After the Update to Gutenberg 19.8 inside my site is impossible to open (in back-end) every pages, cpt or articles.
I tried deactived all the plugins (except Gutenberg) and to change the theme to the default one (TT25), but nothing worked.

The error says 'You are trying to edit an item that doesn't exist. Maybe it was deleted?' and then only white page.

The problem disappear when disabling Enable real-time collaboration and offline persistence among peers in the experiment section of Gutenberg

### Step-by-step reproduction instructions

1) Upgrade to Gutenberg 19.8
2) Open some type of post type
3) White screen

[Image](https://github.com/user-attachments/assets/4794b43e-7f65-4341-9b0f-228f36f35e35)

### Environment info

WordPress 6.7.1
Gutenberg 19.8

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment] 2024-12-06 21:25
I think this is a duplicate of #67229.

**Closed as not planned** 2024-12-06 21:26 UTC
Labels: [Type] Bug, [Status] Duplicate, [Feature] Real-time Collaboration
