### ISSUE TITLE
Improve performance of term search (tags/categories)

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#28708] opened 2021-02-03 22:30 UTC
For some installations, it appears that searching for tags or categories is slow when there are many tags. Let's verify and see if there's a performance issue in the term search endpoint when there are thousands of tags, since the max suggestions are already capped to 20 in the query.

https://github.com/WordPress/gutenberg/blob/0105c9a2312272d768f1ecb77c0b9e6dca77d0a0/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L30-L36

The search is already throttled at 500 ms. But I feel like this interaction is probably better using debounce vs throttle:
https://github.com/WordPress/gutenberg/blob/0105c9a2312272d768f1ecb77c0b9e6dca77d0a0/packages/editor/src/components/post-taxonomies/flat-term-selector.js#L77

We're most interested in the latest search value, vs trying to eliminate jank.

There was originally reported in: https://wordpress.org/support/topic/disable-suggestions-in-editors-tag-field/

**Comment by Mamaduka** [comment] 2021-05-11 05:22
Hi, @gwwar

[Discussed](https://wordpress.slack.com/archives/C02QB2JS7/p1620709944016300) this issue during editor triage today and agreed that `debounce` is better suited for this kind of things.

I'm going to assign this issue to myself and will create PR later today.

Thanks for bringing this up.

**Closed** 2021-05-12 03:06 UTC
Labels: [Package] Editor, [Status] In Progress, [Type] Enhancement, [Type] Performance

**Comment by atakanuludag** [comment] 2022-02-07 08:32
@gwwar  @Mamaduka  is there any progress?
because there are so many tags on my site. my browser crashes

**Comment by Mamaduka** [comment] 2022-02-07 09:02
Hi, @atakanuludag

We did ship a few improvements in WP 5.9. I did my tests using few thousand, but it's not the same as the actual production site.

Are you running the latest WordPress or Gutenberg versions?

**Comment by atakanuludag** [comment] 2022-02-07 09:16
Hi @Mamaduka ,
Yes. I am using wp 5.9. This issue happens with WooCommerce tags. I can send a video about the issue ?

Example autocomplete service used in tags;
`/wp-admin/admin-ajax.php?action=ajax-tag-search&tax=product_tag&q=lg`

**Comment by atakanuludag** [comment] 2022-02-07 09:18
the problem is caused by (Response);
![image](https://user-images.githubusercontent.com/6053742/152759613-5d37411e-788b-4da5-9ffb-5f85fc92cb22.png)

**Comment by Mamaduka** [comment] 2022-02-07 09:26
Thanks for the details, @atakanuludag.

This isn't an endpoint that Editor uses for searching tags. Instead, we use REST API for fetching and searching tags.

```
/wp-admin/admin-ajax.php?action=ajax-tag-search&tax=product_tag&q=lg
```

I would recommend reporting the issue on the [WooCommerce repo](https://github.com/woocommerce/woocommerce/).

**Comment by atakanuludag** [comment] 2022-02-07 09:29
@Mamaduka thanks. best regards 👍
