### ISSUE TITLE
Navigation block making block editor super slow

### ISSUE THREAD

**Issue by uniquesolution** [WordPress/gutenberg#40619] opened 2022-04-26 12:52 UTC
### Description

Whenever we create a navigation using block editor and it become a bit bigger with some dropdowns added, the block editor start lagging and become super slow to response. To even able to click and select anything in the editor.

### Step-by-step reproduction instructions

1. Go to any page
2. add some section group or any blocks
3. Now add a navigation block
4. Add some pages in it or create new pages using the navigation block, create some drop down also.
5. Now save the page and refresh the page and now try editing the page you will see the loading time has increased a lot.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment] 2022-04-27 17:33
Hey there! Can you share what version of WordPress and Gutenberg you're using in order for folks to replicate this? I'd also love to know what you're doing to measure the change in performance. Thanks in advance.

**Comment by uniquesolution** [comment] 2022-04-27 23:46
I am using Wordpress 5.9.3 and gutenberg plugin version 13.0.0, I am just measuring it as visible lagging in time. For example let two separate pages one with a navigation block (with a big menu in it) and another without any navigation block, Put same content in both pages and compare block editor how much more effort you have to take to make any changes on the page.

**Comment by annezazu** [comment] 2022-04-28 22:45
Ah ha thank you @uniquesolution -- seems this is a duplicate of this issue which I just learned more about today thanks to you opening this one! https://github.com/WordPress/gutenberg/issues/40357#issuecomment-1112351314 

I'm going to close this out as a result since this is a duplicate. Please follow along in the other issue to stay informed of the progress. Thanks so much for reporting this on.

**Closed as completed by annezazu** 2022-04-28 22:45 UTC
Labels: [Status] Needs More Info, [Block] Navigation
