### ISSUE TITLE
404, missing build/core-blocks/style.css

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#8886] opened 2018-08-12 00:16 UTC
**Describe the bug**

My site has this directive:

```
<link rel='stylesheet' id='wp-core-blocks-css'  href='https://tomjn.com/wp-content/plugins/gutenberg/build/core-blocks/style.css?ver=1533850912' type='text/css' media='all' />

```

But `https://tomjn.com/wp-content/plugins/gutenberg/build/core-blocks/style.css` is showing a 404, and that folder contains only an `index.js` file on the server.

**To Reproduce**
1. Install and activate gutenberg
2. view the frontend

**Expected behavior**

I expected the `style.css` to be present and to load correctly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 68

Gutenberg 3.5

**Comment by designsimply** [comment] 2018-09-17 22:11
Closing because it couldn't be reproduced in testing. Happy to re-open if the problem is still present! Please try testing again using the latest version of Gutenberg.

**Closed by designsimply** 2018-09-17 22:11 UTC
Labels: [Status] Needs More Info, [Type] Help Request
