### ISSUE TITLE
Text Block: Sometimes the cursor gets moved behind the first character

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#1607] opened 2017-06-30 13:54 UTC
![weird text bug](https://user-images.githubusercontent.com/191598/27738666-fc75f87a-5d79-11e7-836a-45bb6a5cef02.gif)

In the gif above, you'll notice that as soon as I start typing, my cursor gets positioned behind the first letter. Very strange.

Just a guess, but maybe something related to the drop cap feature?

**Comment by westonruter** [comment] 2017-07-08 01:21
I cannot reproduce this.

**Comment by jasmussen** [comment] 2017-08-18 09:35
I also can't reproduce this, with or without dropcap enabled, in Safari.

**Comment by mtias** [comment] 2017-08-18 20:44
Going to close for now. @shaunandrews feel free to reopen if you still see this.

**Comment by nicolinuxfr** [comment] 2017-08-18 21:32
I have definitely seen this bug, also on Safari. I don’t know how to replicate it exactly, but I think it happens when you click outside of a paragraph, then inside and continue to write. 

Then, the cursor is sometimes before the last letter instead of being at the end. 

I’ll try to find a more reproducible explanation.

**Comment by nicolinuxfr** [comment] 2017-08-19 17:26
Sorry, I can’t reproduce it when I want to. But I still this behavior with Gutenberg 0.9.

Sometimes, the cursor moves to the last styled text in the current block (may it be bold or italic). I don’t know exactly how it happens, but I have to deal with this bug at least once or twice per post, on average.

**Comment by nicolinuxfr** [comment] 2017-08-20 14:57
OK, I found one reliable and reproducible way to have the bug : 

1. Click the preview button to load the preview in another tab or window
2. Click in the paragraph of the Gutenberg window to continue editing
3. The cursor is placed at the wrong place.

Here’s a short video demonstrating it : 

![bug-cursor](https://user-images.githubusercontent.com/2078386/29495925-b02d906e-85c8-11e7-9293-2ff0f96f483c.gif)

**Comment by jasmussen** [comment] 2017-08-21 06:34
Reopening because of the excellent bug report, thank you!

**Comment by tg-ephox** [comment] 2017-08-24 01:24
This can also be replicated by clicking on 'Settings' to toggle the panel on the right side.

**Comment by youknowriad** [comment] 2017-10-12 21:52
closed by #2787

**Closed by youknowriad** 2017-10-12 21:52 UTC
Labels: [Component] TinyMCE, [Type] Bug

**Comment by jasmussen** [comment] 2017-10-13 06:51
Ooh nice! Does this fix the 2nd issue that I noted here? https://github.com/WordPress/gutenberg/pull/2779#issuecomment-336053813

CC: @tg-ephox @annaephox
