### ISSUE TITLE
Inline CSS for query block is too specific

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#34047] opened 2021-08-12 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

The new query block adds inline CSS; the use of !important on the margins is too specific, and has to be overridden in theme code by using !important again. This needs to be improved.

For example:

```
.wp-container-61154d850afa1 > * {
    max-width: 736px;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

### Step-by-step reproduction instructions

1. Add a query block to the page.
2. Add regular `margin-left` and `margin-right` rules to the theme CSS.
3. These rules don't take effect because of the use of `!important` coming from Core CSS.

### Expected Behavior

The use of `!important` leads to complications for theme developers and (in some instances) can't be overridden without unnecessarily complicated theme CSS.

### Current Behavior

The theme styles are overridden by the core css.

### WordPress Information

Sprache der Website | de_DE_formal
Benutzersprache | de_DE_formal
Zeitzone | Europe/Zurich
Homepage-URL | https://ffde.local
Website-URL | https://ffde.local
Permalink-Struktur | /%postname%/
Verwendet diese Website HTTPS? | Ja
Ist dies eine Multisite? | Nein
Kann sich jeder auf dieser Website registrieren? | Nein
Ist diese Website für Suchmaschinen ausgeschlossen? | Ja
Standard-Kommentarstatus | Offen
Umgebungstyp | local
Anzahl der Benutzer | 4
Verbindung mit WordPress.org | WordPress.org ist erreichbar

### Gutenberg Information

Gutenberg plugin is not installed

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Device Information

All

### Operating System Information

All

**Comment by markhowellsmead** [comment] 2022-05-23 10:38
See also https://github.com/WordPress/gutenberg/issues/41230.

**Comment by carolinan** [comment] 2022-07-25 10:27
I am closing this as a duplicate of #33956 since these margin styles are not specific to the query block.

**Closed as not planned by carolinan** 2022-07-25 10:27 UTC
Labels: [Type] Bug, [Status] Duplicate, CSS Styling
