### ISSUE TITLE
Plugin List Not Displaying

### ISSUE THREAD

**Issue by cobisan** [WordPress/gutenberg#8439] opened 2018-08-03 13:33 UTC
I'm working on a site locally using MAMP (version 5.0, mac, chrome Version 67.0.3396.99, WP version 4.9.8, Divi theme 3.11.1). This is a second iteration of this site and I can no longer see the plugins beyond the first three listed in the plugin list. As you can see on the top, there are 17 active plugins.

**To Reproduce**
1. Click on Plugins > Installed plugins
2. See error

<img width="1382" alt="screen shot 2018-08-03 at 7 33 57 am" src="https://user-images.githubusercontent.com/42068196/43645588-9df2fc52-96ef-11e8-93b4-677ac66e9708.png">

**Comment by youknowriad** [comment] 2018-08-03 14:15
How is this related to Gutenberg?

**Comment by cobisan** [comment] 2018-08-03 14:29
Wasn't a problem until I installed Gutenberg

**Comment by youknowriad** [comment] 2018-08-03 15:55
Can you provide the list of plugins you have, it could be a conflict between plugins as we can't reproduce this.

**Comment by cobisan** [comment] 2018-08-03 16:43
Sure. They are:

Askimet Anti-Spam
Contact Form 7
Duplicate Page
Easy Updates Manager
Google Analytics Dashboard for WP
Insert Headers and Footers
Jetpack
MetaSlider
Page Builder by SiteOrigin
Photo Gallery by Supsystic
Schema
Simple Staff List
SiteOrigin Widgets Bundle
Sucuri
WP Fastest Cache
WP Instagram Widget
WP Simple PayPal Shopping Cart
WP-DBManager
Yoast SEO

**Comment by designsimply** [comment] 2018-10-16 18:22
Looping back to check on this. What an odd bug! @cobisan thank you for listing your plugins. Nothing jumps out at me as obvious but it certainly does <em>seem</em> like a plugin conflict of some kind at first glance. May I ask if the problem still happening for you with the latest stable release of Gutenberg installed and, if it is, would you be able to open the plugins page and check the console panel in your browser's web developer tools and see if any errors show up there—or errors may just show up in the sever error logs for a case like this, do you have access to check your server error logs by chance?

Thanks so much for testing Gutenberg!

**Comment by youknowriad** [comment] 2018-11-03 18:53
Closing, let's reopen if we have more info to reproduce it.

**Closed by youknowriad** 2018-11-03 18:53 UTC
Labels: Needs Testing, [Status] Needs More Info, [Type] Help Request, [Type] Plugin / Theme Interoperability
