### ISSUE TITLE
Performance issues when using lots of blocks

### ISSUE THREAD

**Issue by gmariani** [WordPress/gutenberg#51210] opened 2023-06-02 20:10 UTC
### Description

I have an almost text only post/article on my site, but it has maybe 150 blocks (since each heading and paragraph are separate). The performance is terrible, i can start typing and there is about a second lag for the letters to appear after typing.

I realize this is client-side, but I'm running with 32GB of memory (only 50% used), and an i7-4790K CPU which should be more than sufficient to edit an article. Performance issues like this is what keeps people using Classic Editor. What is going on behind the scenes where just have text runs the performance into the ground?

### Step-by-step reproduction instructions

Create a new page using the Block Editor. Add about a hundred blocks consisting of headers, a sprinkling of bulleted lists, and lots of paragraph blocks. Performance starts to take a major hit.

### Screenshots, screen recording, code snippet

No screenshots per se, just a lot of text.

### Environment info

WordPress 6.2.2
Firefox 113.0.2 x64
- AutoTube extension
- Don't track me Google extension
- Firefox Multi-Account Containers
- IndicateTLS
- Kee - Password Manager
- React Developer Tools
- Save webP as PNG or JPEG
- uBlock Origin
Windows 10 x64 desktop, 32GB DDR4, Intel i7-4790K

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment] 2023-06-03 04:15
Thanks for the report, @gmariani!

Can you share a screen recording of an issue?

Here are a few more questions that could help us narrow things down:

* Do you have a List View sidebar open while typing?
* Are you using the fixed Top toolbar?

## Screenshot
![CleanShot 2023-06-03 at 08 13 58](https://github.com/WordPress/gutenberg/assets/240569/929ca103-08eb-4978-9b48-dcd550647861)

**Comment by gmariani** [comment] 2023-06-03 06:03
Do you have a List View sidebar open while typing? - No, i usually have it closed
Are you using the fixed Top toolbar? - No, i didn't realize you could even do that

Uploaded a video from my home computer with the same issue. This is less pronounced than on the previous computer I was using. This computer has 64 GB of DD4 RAM and an AMD Ryzen 9 5900X, and it still wasn't enough to make the problem go away, just make it harder to demonstrate.

https://github.com/WordPress/gutenberg/assets/5058619/9d8590c0-03bf-49a4-a8f9-f3f0f563731b

**Comment by gmariani** [comment] 2023-06-03 06:07
Almost forgot, in the video that was on:

Environment info

WordPress 6.2.2
Firefox 113.0.2 x64

    AutoTube extension (disabled)
    Don't track me Google extension
    Firefox Multi-Account Containers
    IndicateTLS
    Kee - Password Manager
    React Developer Tools (disabled)
    Save webP as PNG or JPEG
    uBlock Origin
    Windows 11 x64 desktop, 64GB DDR4, AMD Ryzen 9 5900X

**Comment by Mamaduka** [comment] 2023-06-03 06:09
Thank you, @gmariani!

**Comment by Mamaduka** [comment] 2023-06-12 15:24
@gmariani, I'm going to close this as a duplicate of #22822. The original issue has more details, and I've cross-linked your report.

**Closed as not planned by Mamaduka** 2023-06-12 15:24 UTC
Labels: [Type] Performance
