### ISSUE TITLE
Add pages to suggestions for UrlInput

### ISSUE THREAD

**Issue by skript-cc** [WordPress/gutenberg#7951] opened 2018-07-13 12:48 UTC
## Issue Overview
I'm using Gutenberg in a project for which I only need to use pages, not posts. The UrlInput only shows suggestions for posts, which makes linking to pages impossible without typing or pasting the url. It would be very nice if pages would show up as suggestions as well or at least have the possibility to customize the suggestions of the UrlInput. When I look at the [current implementation](https://github.com/WordPress/gutenberg/blob/843ba97ae2b21be211cecd51416006115fd11ae7/editor/components/url-input/index.js#L71-L77) this seems to be impossible too.

## Steps to Reproduce (for bugs)

1. Ensure there are some pages
2. On another page insert a paragraph
3. Select some text and try to insert a link
4. Start typing in the url input

## Expected Behavior

Pages should come up in the suggestions.

## Current Behavior

Only posts are showing up.

## Possible Solution

Include pages in the suggestions by default or make it possible to customize the suggestions.

**Comment by paulwilde** [comment] 2018-07-13 17:21
I feel this should also include public custom post types as well.

**Comment by DerTanzschuh** [comment] 2018-07-14 11:36
Oh. The problem is the usage of the posts endpoint from the rest api. You can cheat a bit and customize the query params with a small filter:

```
add_filter( 'rest_post_query', 'postRestQueryArgs' );
function postRestQueryArgs( $args ) {
    if ( $args[ 'orderby' ] === 'relevance' ) {
        $args[ 'post_type' ] = array( 'post', 'page' );
    }
   return $args;
}
```
Or if you are lazy and want to include all post types just use 
```$args[ 'post_type' ] = array( 'post', 'page' );```

I know it kills the sense of the posts endpoint. It would be a better solution to have a GET parameter for example to set the required post types,. This is only a quick and dirty solution.

**Comment by chrisvanpatten** [comment] 2018-07-14 13:10
I _think_ this is covered by the changes in #7894. I know @danielbachhuber has been guiding that with @felixarntz — maybe one of you can confirm and potentially tag or close this issue?

**Comment by danielbachhuber** [comment] 2018-07-14 13:52
Yes, this issue is a duplicate of #2084

**Closed by danielbachhuber** 2018-07-14 13:52 UTC

**Comment by skript-cc** [comment] 2018-07-19 15:31
Thanks for the info and sorry for the duplicate. A search didn't brought similar issues up.
