### ISSUE TITLE
Group block layout settings are enabled in the widget area even though there is no theme.json

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#33491] opened 2021-07-16 08:16 UTC
## Description
I am testing 5.8.

When `theme.json` is not installed in the theme, the "Group" block "Layout setting" does not appear in the post editor.

However, in the widget area, the group block layout setting is enabled.

## Step-by-step reproduction instructions

1. Please use a theme that does not have theme.json.
2. Go to the widget page.
3. Place the "Group" block and check the sidebar.

<img width="1174" alt="スクリーンショット 2021-07-16 17 17 49" src="https://user-images.githubusercontent.com/31400297/125916110-b6c82a89-dcfa-484e-96f8-70aed69146db.png">

**Comment by draganescu** [comment] 2021-07-28 15:34
👋🏻 Hi! Is this problem that the Widgets editor does not respect `theme.json`?

**Comment by talldan** [comment] 2021-08-02 07:52
This no longer happens with the Gutenberg plugin active:
<img width="279" alt="Screenshot 2021-08-02 at 3 50 15 pm" src="https://user-images.githubusercontent.com/677833/127823947-4616f43b-9fc8-455a-a84c-02815055d490.png">

So it may have been fixed at some point in the plugin.

**Comment by draganescu** [comment] 2021-08-02 07:57
Given this cannot be reproduced, let's close it because having it caused by `theme.json` does not look like it needs a backported fix.

**Closed as completed by draganescu** 2021-08-02 07:57 UTC
Labels: [Feature] Widgets Screen, [Block] Group
