### ISSUE TITLE
Widgets Shortcode block does not work.

### ISSUE THREAD

**Issue by styledev** [WordPress/gutenberg#29129] opened 2021-02-18 22:14 UTC
## Description
When using the shortcode block in the widgets area it does not execute the shortcode and just prints it to the page.

## Step-by-step reproduction instructions
1. Go to Appearance > Widgets
2. Open up a Widget Area and add the Shortcode block and paste in your shortcode
3. Update the widgets area
4. View page with widget area

## Expected behaviour
Shortcode should display what ever the shortcode is meant for.

## Actual behaviour
Shortcode is printed to screen.

## Screenshots or screen recording (optional)
<img width="736" alt="Screen Shot 2021-02-18 at 2 10 34 PM" src="https://user-images.githubusercontent.com/12783/108428371-4e533680-71f3-11eb-8943-8ace9a091ed2.png">
<img width="974" alt="Screen Shot 2021-02-18 at 2 10 42 PM" src="https://user-images.githubusercontent.com/12783/108428390-54e1ae00-71f3-11eb-87dd-b79fa1d52ef2.png">

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 10.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS 11.2.1
- Browser: Chrome 88.0.4324.182

**Comment by draganescu** [comment] 2021-02-24 08:12
Howdy @styledev this is a duplicate of #27793. Will close this and track the older one instead.

**Closed by draganescu** 2021-02-24 08:12 UTC
Labels: [Feature] Widgets Screen
