### ISSUE TITLE
Bug: Spotify link does not expand in Block or Embed

### ISSUE THREAD

**Issue by vajrasar** [WordPress/gutenberg#17166] opened 2019-08-23 11:01 UTC
**Describe the bug**
The Spotify link does not expand in either the Spotify Block, or the Embed Shortcode block. However, the same Spotify link expands as expected in Widgets while using Embed and iFrame.

**To reproduce**
1. Create a Post
2. Insert Spotify Block or Embed Block
3. Use a Playlist link
4. Block says "Sorry, this content could not be embedded"

**Expected behavior**
The block should embed the link and expand to the Spotify Player

**Screenshots**
![Dashboard](https://cloudup.com/cFSZei8rYZc)

![Blocks with Widget Embed at .com](https://cloudup.com/ceczhpWMfmF)

![Blocks with Widget iFrame](https://cloudup.com/cjPUUcozYyR)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome and FF
 - Version 76.0.3 and 68.0.2

**Additional context**
- Gutenberg 6.3.0
- Test Site: https://razzmtazz.blog/2019/08/23/spotify-test/
- Test Site: https://alive-sole.jurassic.ninja/2019/08/23/spotify-test/

**Comment by youknowriad** [comment] 2019-08-23 11:03
This looks like a duplicate of #17139

**Closed by youknowriad** 2019-08-23 11:03 UTC

**Comment by vajrasar** [comment] 2019-08-23 11:06
@youknowriad It did not fail for me. It always showed "Sorry, this content could not be embedded."

**Comment by youknowriad** [comment] 2019-08-23 11:07
It's the same error in the screenshot.

**Comment by vajrasar** [comment] 2019-08-23 11:08
👍
