### ISSUE TITLE
Block toolbar misaligned in RTL contexts

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#23265] opened 2020-06-18 08:41 UTC
It appears that the block toolbar is misaligned in RTL environments. 

1. Set the site language to an RTL language, for example arabic.
2. Go to the block editor and add content. 
3. Make sure the viewport is not too wide, less than 1280px or thereabouts.

Observe that the block toolbar is mis-aligned. It should be flush with the right margin of blocks, but it is indented a little bit. 

GIF of small viewport:

![rtl](https://user-images.githubusercontent.com/1204802/84998377-081f7200-b150-11ea-941b-a95fd96f7c05.gif)

Note that on a very wide viewport the issue only appears once one or two sidebars appear:

![rtl widescreen](https://user-images.githubusercontent.com/1204802/84998407-153c6100-b150-11ea-9a65-cedcadd8066c.gif)

Mac/Chrome/Nightly.

**Comment by jasmussen** [comment] 2020-06-18 08:42
@youknowriad notes that it might be related to "the viewport boundaries shifting we have in Popovers" and CC's @ellatrix

**Comment by ellatrix** [comment] 2020-07-16 11:36
@jasmussen I tried to reproduce but it seems fine?

<img width="755" alt="Screenshot 2020-07-16 at 14 35 41" src="https://user-images.githubusercontent.com/4710635/87666655-aca5cb80-c771-11ea-87a6-c977967437c0.png">

**Comment by diegohaz** [comment] 2020-07-16 13:26
Also couldn't reproduce, but I did notice that arrow key navigation doesn't follow.

![GIF showing the use of the block toolbar in an RTL context. Focus on the toolbar is moved using arrow keys. Using arrow right moves to the right](https://user-images.githubusercontent.com/3068563/87675959-65f2aa00-c74e-11ea-8b9f-a717cf630a1e.gif)

Not the same issue but this should be fixed anyway. Do we have a way to identify if WordPress/Gutenberg is set to RTL in JavaScript?

**Comment by youknowriad** [comment] 2020-07-16 15:06
> Do we have a way to identify if WordPress/Gutenberg is set to RTL in JavaScript?

I think there's a few different ways but it seems like the last consensus is to rely on `isRTL` from the i18n package.

**Closed** 2020-07-20 09:49 UTC
Labels: [Status] In Progress, [Type] Bug

**Comment by jasmussen** [comment] 2020-08-03 08:51
Thank you all!
