### ISSUE TITLE
render_block -> core/heading ["attrs"]["level"] only with <h1> headings

### ISSUE THREAD

**Issue by nicmare** [WordPress/gutenberg#16877] opened 2019-08-02 09:44 UTC
When i debug the render_block filter on core/heading block, i've noticed there is an attrs array with "level" entry for only h1 headline. Then "level" has value of "1". When i change h1 to h2 or h3 the "level" entry is missing. Is this on purpose?! WordPress 5.2.2

**Comment by shawncook** [comment] 2019-10-07 04:11
Noticing this as well. I'm able to target `core/heading` blocks with a level of `1`, but I can't target 2 through 6.

**Comment by danbowles** [comment] 2019-10-10 15:42
Ended up implementing a regex:
```
if (
	'core/heading' === $block['blockName']
) {
	preg_match( '/\n*<(?P<level>h[1-6])/si', $block['innerHTML'], $matches );
	$heading_level = ! empty( $matches['level'] ) ? 'block--heading-' . $matches['level'] : '';
	$wrapped_block_content = sprintf(
		'<div class="block--heading-container '. $heading_level .'">%s</div>',
		$block_content
	);
}
return ! empty( $wrapped_block_content ) ? $wrapped_block_content : $block_content;
```

**Comment by certainlyakey** [comment] 2019-10-13 20:03
Clearly a bug. Makes creating a table of contents or page headings menu more difficult.

**Comment by talldan** [comment] 2020-04-30 04:19
I'm not able to reproduce fully what's described using the following code:
```php
function my_test_render_callback( $content, $block ) {
	if ( 'core/heading' !== $block['blockName'] ) {
		return $content;
	}

	return json_encode( $block[ 'attrs' ] );
}

add_filter( 'render_block', 'my_test_render_callback', 10, 2 );
```

I do indeed see that there's no `level` attribute when the level is set to `2`, but at other levels it works ok.

This is happening because the default level is 2, and default attributes aren't applied for static blocks when trying to access them in PHP. It looks like this is tracked in https://github.com/WordPress/gutenberg/issues/2751, I think there's a long term effort to improve this, part of which is moving all the attribute definitions to `.json` files so that they can be read by PHP.

I'll close this if that's ok, as I think this is adequately tracked in #2751.

**Closed by talldan** 2020-04-30 04:19 UTC
Labels: Needs Testing, [Block] Heading

**Comment by swinggraphics** [comment] 2021-05-05 22:16
> Default attributes aren't applied for static blocks when trying to access them in PHP

Aaaargh. Gutenberg: making life harder in PHP, and requiring a lot more skill and hoop-jumping to access in JS. The linked issue #2751 is Closed, as well. 😢
