### ISSUE TITLE
Initially close the Block Styles sidebar panel

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#24072] opened 2020-07-20 18:55 UTC
Applying a Block Style is not be a high-priority action within a block's Settings Sidebar. Thinking through the flow of editing, its not likely a style will be changed often. I suggest initially closing the Styles `PanelBody` to limit the amount of actionable UI when a block's settings sidebar is opened. 

While not a _major_ deal using core blocks, if any third-party blocks add a Block Style to a particular block, it can quickly clutter the sidebar - pushing all other controls away and directly affecting cognitive overload.

### Before:
<img width="1295" alt="Screen Shot 2020-07-20 at 2 43 58 PM" src="https://user-images.githubusercontent.com/1813435/87974168-a11b1300-ca97-11ea-95d0-d920fe87c2a2.png">

### After: 
<img width="1293" alt="Screen Shot 2020-07-20 at 2 43 45 PM" src="https://user-images.githubusercontent.com/1813435/87974177-a6785d80-ca97-11ea-901c-a1659e7e6e2a.png">

### With CoBlocks (adding block styles): 
<img width="1298" alt="Screen Shot 2020-07-20 at 2 52 16 PM" src="https://user-images.githubusercontent.com/1813435/87974807-9f9e1a80-ca98-11ea-87f0-51070e4d78a0.png">
<img width="1227" alt="Screen Shot 2020-07-20 at 2 50 28 PM" src="https://user-images.githubusercontent.com/1813435/87974670-6cf42200-ca98-11ea-8dd8-cdc5219846fa.png">

**Describe the solution you'd like**
Set the `initialOpen` prop to `false` for the Styles PanelBody which will clean up the Settings Sidebar UI and lowering cognitive overload.

**Describe alternatives you've considered**
Closing the Styles panel every time I open a block that has a number of Block Styles, before moving to edit additional sidebar controls.

**Comment by shaunandrews** [comment] 2020-07-21 20:19
I wonder if there's a way to reduce the size of the Styles UI. Maybe if we introduce a preview on hover, we can show smaller thumbnails. We could also remove the accordion UI and closely tie the block description with the styles:

![block styles floating preview on hover](https://user-images.githubusercontent.com/191598/88102624-ddb93e00-cb6d-11ea-8997-dde8f56cccae.gif)

We might not even need the floating preview; Maybe we can just show the preview directly on the canvas:

![block styles preview on hover](https://user-images.githubusercontent.com/191598/88102652-ec9ff080-cb6d-11ea-86bc-5c6f7a639406.gif)

**Comment by mtias** [comment] 2020-07-22 11:11
How would those little things be created from a block author perspective?

**Comment by shaunandrews** [comment] 2020-07-22 13:43
I'd expect it to work the way it does now, just with smaller thumbnails. They're rendered blocks, not some static image or other representation.

**Comment by richtabor** [comment] 2020-07-22 21:37
So just smaller previews? Would be great if like in your example, they were based on the block - not the example.

**Comment by MichaelArestad** [comment] 2020-08-11 21:48
The root of the problem is hierarchy within the sidebar. For now, I think defaulting the panel to being closed works well.

I think a more complete solution involves something like what @ItsJonQ proposed [here](https://github.com/WordPress/gutenberg/issues/23486) using a context popover. Perhaps something like this:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/1123119/89952063-c9ef7d80-dbe9-11ea-9e9a-43c8878440ab.png">

**Comment by mtias** [comment] 2020-08-25 11:51
That could work

**Comment by richtabor** [comment] 2020-08-25 20:14
I like that idea as well.

**Comment by getsource** [comment] 2021-03-22 09:44
I see that in the attached PR, #24073, there was a mix of opinions, but the final feedback was against closing initially, which is different than was [noted above](https://github.com/WordPress/gutenberg/issues/24072#issuecomment-672296421), afterwards.

Would it be better to close this issue, given the feedback on the PR, in lieu of the other tickets making the experience better, or is initially closing still something under discussion?

**Comment by getsource** [comment] 2021-04-13 07:29
Thought of this later, so thought I'd add:
If user testing would be appreciated to A/B, I can ask to see if this is a possibility, or if there are any existing studies that might help with data.

**Comment by paaljoachim** [comment] 2021-04-20 16:18
I do wonder if the Styles thumbnails should be made smaller, and that we have a preview on the left. Somewhat similar to what @shaunandrews is mentioning here: https://github.com/WordPress/gutenberg/issues/24072#issuecomment-662085339

Today we have the hover over blocks in the Inserter panel. Adding the same method to Style smaller thumbnails could be helpful. I do wonder about accessibility.

Today the Styles take a lot of visual space in the Styles panel. Having the thumbnails half the size could make the visual distraction feel less disturbing. Adding hover could then show a bigger preview than todays thumbnails. A user can choose to just click the small thumbnail without really looking much at the preview seen on hover to just add the style and see how it looks. 

Another option (which might not work) is actually showing a live preview directly affecting the block in the Gutenberg layout. As in hover over a style and see the preview directly, and click the thumbnail to apply the style.

**Comment by getsource** [comment] 2021-12-14 06:12
#34522 is merged, which changes the behavior / UX here.

Does that seem like enough to solve this issue, or should be leave this open?

**Comment by paaljoachim** [comment] 2021-12-14 12:48
Well let's do a before and after.

Before:
![Screenshot 2021-12-14 at 13 45 25](https://user-images.githubusercontent.com/5323259/146001166-4915eb3b-bdd8-4d5e-bdab-8ff97be7853c.jpg)

After:
![Screenshot 2021-12-14 at 13 46 03](https://user-images.githubusercontent.com/5323259/146001176-ab74b1ab-729d-4dd0-aa9f-b1f41f3baef9.jpg)

The new Styles Panel takes a lot less space than the earlier one. It is still open by default though.
Let's see what @richtabor says.

**Comment by mtias** [comment] 2021-12-14 15:11
@getsource yes, this addresses the main inconveniences we had before more reliably than initially collapsing.

**Closed by mtias** 2021-12-14 15:11 UTC
Labels: [Status] In Progress, Needs Design Feedback
