### ISSUE TITLE
Import/upload images from clipboard pasting instead of hotlinking

### ISSUE THREAD

**Issue by sparanoid** [WordPress/gutenberg#18263] opened 2019-11-04 11:00 UTC
**Is your feature request related to a problem? Please describe.**
When pasting images from clipboard, there seems to have two behaviors: 

- Hotlink directly when you copy images from other websites to Gutenberg editor.
- Upload it to the media library and insert it to your editor when you copy images from the image viewer/editor.

In most cases when I copy and paste an image from other websites, I mean to copy it and let me host it on my own server then insert it to my post. But the problem is, the default behavior of how Gutenberg inserts images from pasting from other websites is hotlinking. Hotlinked images are easily got renamed, removed, or blocked from hotlinking due to any unpredictable reason.

To make this issue clearly, I recorded a video demo: https://www.youtube.com/watch?v=NmmvQoLLJEo

**Describe the solution you'd like**
Import/upload external images by default when pasting from other websites. This is also how GitHub and Notion handle images from the clipboard.

**Describe alternatives you've considered**
Add an option to toggle the behavior of inserting images from the clipboard.

**Comment by ellatrix** [comment] 2019-12-10 17:55
Duplicate of #2515.

**Closed by ellatrix** 2019-12-10 17:55 UTC
Labels: [Block] Image, [Feature] Raw Handling, [Type] Enhancement
