### ISSUE TITLE
Can't Easily Select FullWidth Blocks

### ISSUE THREAD

**Issue by kwoodall** [WordPress/gutenberg#17290] opened 2019-08-31 21:44 UTC
When using Gutenberg in regular or distraction-free mode it can become quite difficult to select a block when it's full-width.  The 'handle' is either off screen or doesn't want to pop up so I can grab it.

This has happened in multiple themes including 2019. So far as I can tell it's theme and plugin agnostic. It's just the behavior of Gutenberg.

**Comment by talldan** [comment] 2019-09-02 03:38
@kwoodall Thanks for reporting.

Can I ask which version you're testing with, and whether you're using the Gutenberg plugin or testing with the version bundled with WordPress?

>  The 'handle' is either off screen or doesn't want to pop up so I can grab it.

In the latest version of the block editor my understanding is that the handle appears like this above the block in the top left (when the block is full-width):
![Screen Shot 2019-09-02 at 11 31 31 am](https://user-images.githubusercontent.com/677833/64088765-98352c00-cd75-11e9-9ab7-884573cbf64f.png)

If it doesn't appear like that for you I'm wondering if it might be due to an older version.

There's also the block navigation menu, which should make selecting blocks much easier:
![Screen Shot 2019-09-02 at 11 33 41 am](https://user-images.githubusercontent.com/677833/64088830-e34f3f00-cd75-11e9-88cb-0cbeb6807f90.png)

**Comment by kwoodall** [comment] 2019-09-02 03:46
I'm using the built in version. Thanks for pointing out the block navigator
though!

K

**Comment by talldan** [comment] 2019-09-02 04:43
@kwoodall Thanks for clarifying. I can confirm that it does seem like an issue when using the built-in version of the editor, but seems resolved in the plugin. The improvements in the plugin should be released in WordPress 5.3, so you'll be able to see the handle like in my screenshot above at that point.

If it's ok with you, I'll close the issue as it's something that already seems to be fixed in the codebase.

**Closed by talldan** 2019-09-02 04:43 UTC
Labels: Blocks, [Status] Needs More Info
