### ISSUE TITLE
Clicking the link edit button triggers multi-block select

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3454] opened 2017-11-13 11:06 UTC
![linkoops](https://user-images.githubusercontent.com/6073772/32722672-eb375750-c86a-11e7-99d6-09f696b27cb5.gif)

Gutenberg 1.6.1 + WP 4.8.3 vagrant + chrome.

**Comment by karmatosed** [comment] 2017-11-13 20:22
I am seeing this also, thanks for reporting.

**Comment by ephox-mogran** [comment] 2017-11-14 05:11
Note, this is strong related to #3348 and #3362.

The problem in #3362 is probably that in `visual-editor/block-list.js`, a `mousemove` is being added to the window on mouse click, and that mousemove keeps going until a mouseup is detected. This especially causes problems because the y positions of the blocks are cached so it doesn't recognise that as the image grows, the block will change in size. Therefore, multi-block selection appears to start before the mouse moves over another block.

**Comment by aduth** [comment] 2017-12-13 18:51
Closing as duplicate of #3348 (will cross-link context).

**Closed by aduth** 2017-12-13 18:51 UTC
Labels: [Type] Bug
