### ISSUE TITLE
Popover from @wordpress/components has sizing issues at small screen sizes

### ISSUE THREAD

**Issue by samueljseay** [WordPress/gutenberg#24592] opened 2020-08-17 02:40 UTC
**Describe the bug**
It seems that if a `Popover` has some content that is a bit wide and you narrow the screen size down (even to a screen size that is much wider than the content), it has trouble deciding what size to adjust to and it starts to flicker badly on the screen and become unusable.

**To reproduce**
We've seen this in woocommerce-admin [here](https://github.com/woocommerce/woocommerce-admin/pull/4907) but I wanted to try create a minimal reproduction. Here is a sandbox with `@wordpress/components` and it's stylesheet loaded. I set some inner content to have a width of 500px and if you shrink the preview screen it starts to flicker from any width below about `850px`.

Also note that its not just when resizing the screen. If the screen size is too small on load the flicker will still occur so this is quite problematic.

I also wonder but have not confirmed, if it's possible that #24532 could be related.

**Screenshots**
![repro](https://user-images.githubusercontent.com/1281828/90352373-50e3a080-e097-11ea-986d-4649ee7934db.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 84

**Comment by ItsJonQ** [comment] 2020-08-17 20:09
Ooh boy. This isn't good 😅 . I worked with the Popover here and there. I believe this flickering is caused by the Popover attempting to **MATH** it's way into a proper size, causing it to go into an infinite **MATH** loop.

We may be hitting some edges/limitations for the Popover component. There's a Github issue (https://github.com/WordPress/gutenberg/issues/21275) that explores improving the underlying mechanics and adding features (like additional alignment positions). In theory, if those are addressed, it should resolve this flickering issue.

In the meantime, we could totally take a look at resolving this flickering issue independently 👍 .

**Comment by talldan** [comment] 2020-08-28 08:46
@samueljseay You mention a codesandbox, did you mean to provide a link to that?

**Comment by samueljseay** [comment] 2020-08-30 20:56
@talldan Whoops! Sorry, here is the link: https://codesandbox.io/s/funny-wing-icoe0

**Comment by talldan** [comment] 2020-09-01 04:02
Thanks!

**Comment by rebeccahum** [comment] 2020-09-29 17:40
Potentially related to #24532?

**Comment by supernovia** [comment] 2020-12-08 07:53
Here's a video of the math if it's of any help.
https://cloudup.com/izqp-zVDGQ7

**Comment by david-szabo97** [comment] 2020-12-16 10:45
Fixed by #27648

**Closed** 2020-12-16 10:45 UTC
Labels: [Package] Components, [Type] Bug
