### ISSUE TITLE
Button Block: button padding is different for left and center aligned buttons

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7812] opened 2018-07-09 12:42 UTC
**Describe the bug**
When a button is used with center-justify, the padding is inconsistent with no justify

**To Reproduce**
1. add a paragraph block, add button block with no justify
2. add a paragraph block, add button block with center-justify
3. compare the two

**Expected behavior**
There shouldn't be a difference in the padding  between the two justification settings.

**Screenshots**
![button padding bug](https://user-images.githubusercontent.com/30901407/42450945-cad0d5c8-8353-11e8-8eb0-cc973962a6cd.jpg)

**Comment by designsimply** [comment] 2018-07-11 17:31
Tested and found that the bottom margin for center-aligned buttons set on `.wp-block-button` is overridden by the `margin: 0 auto;` rule set on `.aligncenter`.

![screen shot 2018-07-11 at wed jul 11 11 27 15 am](https://user-images.githubusercontent.com/1119271/42589256-a06f7072-84fd-11e8-8d99-36c4af238bba.png)
<sup>Seen at http://alittletestblog.com/2018/07/11/button-block-padding-alignment-test/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

**Comment by jasmussen** [comment] 2018-10-10 09:57
@GlennMartin1 

I can't reproduce this issue in TwentySeventeen running 3.9. Editor:

![screenshot 2018-10-10 at 11 42 50](https://user-images.githubusercontent.com/1204802/46728001-1a11f780-cc82-11e8-869b-cdb8973b49d5.png)

Frontend:

![screenshot 2018-10-10 at 11 42 57](https://user-images.githubusercontent.com/1204802/46728006-1d0ce800-cc82-11e8-98b0-221cfc73eeb9.png)

As you can see in this GIF, there's a bottom margin applied to the button that is the same regardless of alignment:

![buttons](https://user-images.githubusercontent.com/1204802/46728080-4a599600-cc82-11e8-9f60-079a0a9b1f76.gif)

However as Sheri notes above, many many WordPress themes come with a CSS style for `.aligncenter` that is a little heavy handed:

![screenshot 2018-10-10 at 11 45 44](https://user-images.githubusercontent.com/1204802/46728294-c81da180-cc82-11e8-983f-b5e69725c042.png)

Specifically, if `margin-left: auto; margin-right: auto;` was used instead of `margin: 0 auto;` this would not be an issue. 

In #10470 I created a "fix" for this issue. I write that in quotes because I'm not sure we should merge it or decide that this is something themes should fix. I personally have no strong opinion, but I think it's worth more people than _me_ decide this ;)

**Comment by tofumatt** [comment] 2018-10-10 10:59
As mentioned in #10470, I think we shouldn't fix this "issue". Themes can update to fix it, but more importantly I don't see any data on the number of themes (or popularity of said themes) that implement a `margin: 0 auto;` rule for `.aligncenter`.

Without data on how many users this issue affects it's tough to weigh the annoyance of dealing with the "fix" compared to the annoyance of dealing with the issue.

**Comment by GlennMartin1** [comment] 2018-10-10 11:08
For what it's worth, the issue is in Storefront theme. 

If it's a theme issue, I can raise the issue with them.

**Comment by tofumatt** [comment] 2018-10-10 11:09
It is, but I think we were concerned that it might be affecting a lot of users.

I think it's worth bringing up with Storefront as well. Thanks! 👍

**Comment by tofumatt** [comment] 2018-10-12 09:49
Thanks for filing 
https://github.com/woocommerce/storefront/issues/972, @GlennMartin1 🙂

I'll close this as a won't fix as we'd like to see this issue fixed in themes, based on the discussion id #10470.

**Closed by tofumatt** 2018-10-12 09:49 UTC
Labels: Blocks, [Type] Bug
