### ISSUE TITLE
Wrong Toolbar in Cover

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#14879] opened 2019-04-09 09:06 UTC
The toolbar in block Cover is overdimensioned. In my opinion, this cannot be intended. Watch [Video](https://decwap8ztgrry.cloudfront.net/items/3l2o0J371j2y2G373o43/Screen%20Recording%202019-04-07%20at%2007.38.08.07%20PM.mp4)  and you'll see, what I mean. 

WordPress 5.2 beta 2

**Comment by youknowriad** [comment] 2019-04-09 09:13
I think this is intended, the Cover Block right now support nesting different block types inside the cover block container. I think what you're seeing is the paragraph toolbar.

We have another kind of formatting toolbar we call inline formatting toolbar but this only applies to inputs/richtexts, not entire blocks.

I think what we have right now is a good tradoff between the UI and the features (the possibility to use multiple blocks inside the cover)

**Comment by youknowriad** [comment] 2019-04-11 08:49
I'm going to close this right now as It works as intended.

**Closed by youknowriad** 2019-04-11 08:49 UTC
Labels: [Block] Cover
