### ISSUE TITLE
Justify button

### ISSUE THREAD

**Issue by Athanor66** [WordPress/gutenberg#9359] opened 2018-08-26 09:29 UTC
Please, add a paragraph justify button to the button bar!
Justifyed paragraphs are important.

Thank you

**Comment by youknowriad** [comment] 2018-08-26 09:31
Thanks for the suggestion, I'm closing as a duplicate of #8450

The classic editor also removed the justify button a while ago. That said it should possible for a plugin to add it back like the classic editor.

**Closed by youknowriad** 2018-08-26 09:31 UTC

**Comment by phpbits** [comment] 2019-05-17 12:47
@Athanor66 I've added Justify button on EditorsKit plugin ( https://wordpress.org/plugins/block-options/ ) together with underline text format.

Here's how these formats works:

![EditorsKit-Formats](https://user-images.githubusercontent.com/3365507/57929042-d866c080-78e4-11e9-8470-512953d265fb.gif)

I hope this will solve your problem. Thanks!

**Comment by Athanor66** [comment] 2019-05-18 17:54
You are great!
Thank you!
