### ISSUE TITLE
Backspace doesn't (always) delete images

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#7422] opened 2018-06-21 08:54 UTC
**Describe the bug**

I can't delete images using the keyboard only when coming from below.

**To Reproduce**
1. Create a post with an image and add a bit of text after it
2. Place the cursor at the end of the text and backspace until the paragraph is empty
3. Backspace once to remove the paragraph
4. Backspace again from the image block

**Expected behavior**

I'd expect the last backspace (with the image selected) would remove the image.
Instead, the cursor is stuck on the caption and backspace does nothing.

**Screenshots**

![screen shot 2018-06-21 at 10 53 46](https://user-images.githubusercontent.com/8739/41708626-69fa0226-7541-11e8-9946-0324fd5b2dbc.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 11.1.1

**Additional context**
- Tested in Gutenberg 3.0.1

**Comment by AtrumGeost** [comment] 2018-10-19 13:53
Hi there,

I tested this with Gutenberg 4.0 and was able to reproduce the issue:

![guten gh 7422_](https://user-images.githubusercontent.com/3696121/47222443-61803e00-d37c-11e8-8f69-d257d076e3c5.gif)

Tried the same with the classic editor and using backspace deleted both the text and the image.

_WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 70.0.3538.67 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave_

**Comment by spencerfinnell** [comment] 2018-11-13 15:22
Still an issue on 4.3.

**Comment by La-Geek** [comment] 2018-11-18 17:02
Windows 10 64bit, Chrome browser, (all recent), WP (5.0-beta5-43907), Theme Twenty Nineteen, no Gutenberg installed:
**_Confirmed_**

![backspace_issue](https://user-images.githubusercontent.com/1585416/48675676-27ad7d80-eb5c-11e8-8d2e-987b4a70fb2b.gif)

**Comment by ellatrix** [comment] 2019-06-24 13:20
Still an issue.

**Comment by adamziel** [comment] 2020-04-22 12:57
Still an issue. It seems like a problem with the Image block - the caret is getting stuck in the Caption rich text and pressing backspace is only considered in context of removing letters from caption text (instead of removing the block).

**Comment by adamziel** [comment] 2020-04-22 13:11
To ensure that the image will be deleted when backspace is pressed in an empty caption field, we'd need to handle `onRemove` or `onMerge` in the caption RichText here:

https://github.com/WordPress/gutenberg/blob/f8e4c9c5b244e3e0254f07db0517f43765ce360b/packages/block-library/src/image/edit.js#L693

A bigger question here is: should we do that? I imagine editing your caption only to remove the entire block with one extra backspace would be at least unexpected.

An alternative would be deleting the block when a backspace is pressed in the succeeding paragraph (instead of moving the cursor to the caption field). This feels a bit off too - maybe selecting the image block would be the right thing to do here? I'm not sure - let's discuss.

**Comment by mapk** [comment] 2020-05-12 00:43
Hmmm... `Backspace` dropping the user into the Caption field is awkward. This appears to be inconsistent as well with other blocks. For example, when I `Backspace` from a Paragraph into a Quote block, it jumps into the Quote itself and not into the Cite portion of the quote. Sure, it's still   odd, but my point is that the backspace doesn't drop me into the meta portion of the block.

![backspace-quote](https://user-images.githubusercontent.com/617986/81625479-e9d69180-93ad-11ea-8d21-f9a12ab743c8.gif)

It should work similarly to the Select mode when `Backspace` encounters a block that is not text. 
1. Highlight the block on the first `Backspace`.
2. Delete the block when hitting `Backspace` again.

![selectmode-backspace](https://user-images.githubusercontent.com/617986/81625692-78e3a980-93ae-11ea-93ba-d842c02f9e6c.gif)

**Comment by paaljoachim** [comment] 2020-06-16 16:17
Hitting backspace when a block contains letters should delete the letters.
When there is no letters left then the block should be deleted.

**Comment by paaljoachim** [comment] 2021-02-10 13:24
I see that this issue is still valid.

Any thoughts on this one Isabel?
@tellthemachines

**Comment by youknowriad** [comment] 2021-03-08 10:43
For me there's logic in "backspace moving to the caption" because it's just the "text" that is before the removed paragraph which means it behaves like any text editor.

that said, when the whole caption is emptied and you hit backspace, maybe we should remove the block?

**Comment by mtias** [comment] 2021-06-30 13:44
@ellatrix agreed on backspace at most selecting the image block in that case.

**Comment by Trapsta** [comment] 2022-03-01 15:42
I took a look at the RN android app and I can see backspace selects the image block, not sure where the UX diverged but from the discussion , it looks like that is the consensus @youknowriad I would love to work on this , should I work on a PR in that direction or do we need to discuss it further?

**Comment by paaljoachim** [comment] 2022-03-01 16:16
Hey @Trapsta Jasper. If you'd like you can bring this up during tomorrows Core Editor chat (Open Floor) if you have not received any feedback by tomorrow evening and ask about it. https://make.wordpress.org/core/2022/02/28/editor-chat-agenda-march-2-2022/ (Add a comment to the agenda as it creates some additional attention.)

**Comment by youknowriad** [comment] 2022-03-02 12:24
@Trapsta Indeed that seems like the consensus, please free to open a PR about it ❤️

**Comment by t-hamano** [comment] 2023-12-17 05:11
The current Image block does not display the empty placeholder itself if there is no caption text. Then, when you press backspace in the next block of the Image block, it will work as follows:

- When the image has a caption: the cursor moves to the end of the caption text.
- When the image does not have a caption: Select the Image block

I feel like this is expected behavior, what do you think?

https://github.com/WordPress/gutenberg/assets/54422211/c42f440e-096c-427c-9a15-e269a00321f1

**Comment by jasmussen** [comment] 2023-12-19 08:48
> I feel like this is expected behavior, what do you think?

Agreed.

**Comment by t-hamano** [comment] 2023-12-19 12:06
I would like to close this issue, but please reopen if you believe that the current backspace key behavior inthe Iimage Block is not what you intended.

**Closed by t-hamano** 2023-12-19 12:06 UTC
Labels: [Type] Bug, [Feature] Media, Needs Dev, [Feature] Writing Flow, [Block] Image
