### ISSUE TITLE
Won't display page for new posts in WP

### ISSUE THREAD

**Issue by stekmedia** [WordPress/gutenberg#10175] opened 2018-09-25 18:38 UTC
When trying out Gutenberg I get a blank white screen when trying to add a post in Wordpress.

**To Reproduce**
1. Go to Wordpress (4.9.8) Dashboard
2. Click on Install Gutenberg (There is a Section titled, A new, modern publishing experience is coming soon., which talks about Gutenberg.)
After it installs the button changes to Activate. Once clicked and activated the button changes to Try Gutenberg. Click that button and it takes you to http://<yoursite.com>/wp-admin/post-new.php?gutenberg-demo
3. Then all you see is a blank white screen. Same white screen happens if you simply try to add a new post (http://<yoursite.com>/wp-admin/post-new.php)
4. Deactivting plugin takes you back to being able to add posts normally with the default editor.

**Expected behavior**
Expected to be able to test drive gutenberg before they implement it in the next version of WordPress

**Screenshots**
N/A BlankWhite web page..

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 (OS Build 17134.285)
 - Browser Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Gutenberg - This is the development plugin for the new block editor in core.
Version 3.9.0 | By Gutenberg Team

**Comment by designsimply** [comment] 2018-09-26 17:52
Thank you for reporting this! I don't see the same problem happening so the likely cause is either a plugin conflict or a server side security configuration that blocks the API or certain files. To help figure out where the conflict may be in your case, would you be able to check the console in your browser's web developer tools and then load the blank screen and check to see if any errors appear?

**Comment by DragonhelmDL** [comment] 2018-12-18 05:57
I had the same version after the WordPress 5.0 release.

I discovered that it was caused by having the Toolset Types plugin activated. When I deactivated it, problem solved. 

Hope that helps.

**Comment by designsimply** [comment] 2019-02-11 22:33
Thanks for the reply @DragonhelmDL! Ruling out a plugin conflict is a really good troubleshooting step. For @stekmedia's case, we can't know if it's the same cause without more information though, so the request to find out more details from the console panel in the browser's web developer tools still stands.

@stekmedia I am going to close this issue since you haven't replied in several months. If you are still having trouble after updating your WordPress and plugins to the latest versions available, please open a help request at https://wordpress.org/support/forum/how-to-and-troubleshooting/ and let them know the situation and what you have tried already. They should be able to guide you in helping to find the relevant details needed to open a bug report if that's the correct route for your case or they may be able to solve the issue with you directly if another update hasn't already fixed the problem.

**Closed by designsimply** 2019-02-11 22:33 UTC
Labels: [Type] Help Request
