### ISSUE TITLE
Latest post Block 

### ISSUE THREAD

**Issue by mohitdadhich10** [WordPress/gutenberg#21808] opened 2020-04-23 06:17 UTC
**Describe the bug**
If No published are available to display and if we select Latest Posts Block then it display "Block Error" .
Expected :- ".

**To reproduce**
1. Do not add any posts
1. Go to 'Add page'.
2. Select 'Latest Posts Block'
3. See error

**Expected behavior**
Instead of showing error message the block must display Proper validation message that "No posts are published to show

**Screenshots**
https://www.screencast.com/t/HUs4RDofzNT

**Editor version (please complete the following information):**
- WordPress version: [5.4]
-  gutenberg plugin

**Comment by Soean** [comment] 2020-04-23 11:06
<img width="642" alt="Bildschirmfoto 2020-04-23 um 13 05 27" src="https://user-images.githubusercontent.com/695201/80092491-2eb39900-8563-11ea-840f-7aae430f6bc5.png">

I can't reproduce the error. Tested with the current master.

**Comment by annezazu** [comment] 2020-04-23 22:21
I also couldn't replicate using the Twenty Twenty theme, WordPress 5.4, and Gutenberg 7.9.1.

**Comment by karmatosed** [comment] 2020-04-24 16:41
I couldn't recreate either, which doesn't mean this isn't an issue, it does mean more information would be great to discover why we are unable to recreate. For now, I am going to close this issue but it can always reopen with more details.

**Closed by karmatosed** 2020-04-24 16:41 UTC
Labels: [Block] Latest Posts, [Status] Needs More Info
