### ISSUE TITLE
Serious performance issues in Safari with 100+ blocks

### ISSUE THREAD

**Issue by paulwilde** [WordPress/gutenberg#9048] opened 2018-08-16 13:15 UTC
So I've built a production website (that has since gone live) which has 118 blocks and nesting which goes 4-5 levels deep (Section > Columns > Column > Contents) however there is major performance issues under Safari 11.1.1.  

By performance issues I mean scrolling sometimes feels sluggish and typing has a 3-4 second delay before anything shows up. It's unusable. Chrome on the other hand doesn't seem to have these issues, so it seems its Safari specific.

Creating a new page and inserting a few new blocks and everything feels fast again.

If there is anything I can do to help diagnosis the cause, do let me know.

**Comment by tofumatt** [comment] 2018-08-16 13:18
Cheers, thanks for filing! This is likely a duplicate of #8822, so I encourage you to subscribe to that issue and follow our progress there.

I'll close this as a duplicate of #8822, but this is definitely a valid issue.

**Closed by tofumatt** 2018-08-16 13:18 UTC
Labels: [Status] Duplicate
