### ISSUE TITLE
Gallery Image sizes in the admin

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#21650] opened 2020-04-16 14:44 UTC
**Describe the bug**
The gallery image sizes, seem to reset in the admin on page refresh The image size on the front end is not effected, which shows the size that was last "updated".

Also, may I ask if there will ever be a "default" option for the image sizes?

**To reproduce**
1. Add a gallery and set the image sizes as "Full size"
2. Save the post
3. Refresh the page, select the gallery and the image sizes has reverted to "thumbnail"

**Please note** the images on the FE stay at "Full size" but the admin doesn't reflect this.

Gif demo (can just see the ending when I refresh the page, then it loops again)
https://gyazo.com/7002bb4ce7ddcb9635b2632e505ed6fd

**Expected behavior**
I would expect the backend to match the size that was last saved.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: Version 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: [e.g. mac]
 - Browser [e.g. chrome]
 - Version [e.g. 80]

**Comment by talldan** [comment] 2020-04-20 04:17
@shane-sigma I haven't been able to reproduce this, so I wonder if it could be related to a plugin causing the behaviour. It may be worth disabling plugins and testing.

One other thing. Would you be able to (after reloading) switch to Code Editor view and take a screenshot of the block HTML. You should see something like this:
<img width="441" alt="Screenshot 2020-04-20 at 12 14 02 pm" src="https://user-images.githubusercontent.com/677833/79713484-7be40080-8300-11ea-90d9-bba20493e989.png">

`"sizeSlug":"full"` is the attribute that drives the selected value in the dropdown, so you should see that for your block.

PS I've updated the reproduction steps to make sure it mentions saving the post before reloading.

**Comment by shane-sigma** [comment] 2020-04-20 07:54
Hi @talldan,

Thank you for your response.

I disabled all plugins, both prior to, and during the test you asked me to do. This has no effect.

I don't see sizeSlug in the object at any point, neither after saving and reload, or when I change the dropdown within the CMS.

<img width="936" alt="Screen Shot 2020-04-20 at 08 47 15" src="https://user-images.githubusercontent.com/44576021/79727504-69f46480-82e4-11ea-8eac-d23cd6c3a37f.png">

**Comment by shane-sigma** [comment] 2020-04-20 08:51
Hi @talldan,

Have a look at the following video, it seems to happen when you change the image dropdown values **after the first save**. This appears to be stripping the sizeSlug out If I never change it then no issues arise.

https://www.dropbox.com/s/adkrl46oti0ah6l/WP-2.mov?dl=0

**Comment by talldan** [comment] 2020-04-22 05:08
@shane-sigma What's happening there is that 'large' is the default value for sizeSlug in the gallery block. When a default value for a block is used it isn't stored in the serialized value for the block, it's assumed instead.

There does seem to be an issue where if you use small images for a gallery, large might not be a size option. In this case the dropdown shows 'Thumbnail' even though internally the block has the large value. Steps to repro:
1. Create a gallery by uploading small images to the media library (e.g. 150x150)
2. Note that the size selector shows 'Thumbnail'
3. Switch to code view, notice that `sizeSlug` is not set to 'thumbnail', it still has the default size of 'large', even though these images can't be shown at that size.

This also led me to wonder whether this issue is related specifically to the images and possibly the sizes that were generated when they were uploaded, and that's why I haven't been able to reproduce it.

cc @mmtr I notice you worked on the feature, wondering if you had any insights?

**Comment by mmtr** [comment] 2020-04-22 09:19
I think you're correct @talldan. The gallery block image size selector doesn't resize images, it only _tries_ to retrieve a resized version of the image that should have been [created during upload](https://rudrastyh.com/wordpress/image-sizes.html).

https://github.com/WordPress/gutenberg/blob/8acbb4f9646f6b3ad8687f60e7816bf88c13ae14/packages/block-library/src/gallery/shared.js#L12-L15

That's indeed an issue when the [default `large` value](https://github.com/WordPress/gutenberg/blob/8acbb4f9646f6b3ad8687f60e7816bf88c13ae14/packages/block-library/src/gallery/block.json#L74-L77) is not a valid size, since the selector won't contain it (thus it will fallback to the first option available which is "Thumbnail") but the block attribute will remain as `large`.

@shane-sigma, in your case, once you've reloaded the editor and the option has switched to "Thumbnail", can you see the "Large" option in the image size selector if you open it?

**Comment by crawls-turner** [comment] 2020-06-21 04:00
Looks like attributes.sizeSlug is not getting saved.

If you drop a console.log here:

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/edit.js#L383

```
console.log('sizeSlug', sizeSlug)
```

... you'll get 'undefined'. Since it's undefined at that point, when you get to this line:

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/edit.js#L415

... the select control defaults to the first option which is "Thumbnail".

I'm guessing it was missed because the sizeSlug attribute isn't used anywhere in the save function since you already have the images attribute that has the appropriate sized image urls available. (which was handled during the save process ... ie. there it looks at the sizeSlug and does the magic to save the correct image urls based on it.)

**Comment by crbadboy** [comment] 2020-06-21 04:40
No sure why yet but adding:

```
    sizeSlug: {
        type: 'string',
        default: 'large'
    }
```

to: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/gallery/deprecated.js#L78

Fixed the issue for me. Now sizeSlug saves like it's supposed to and when I refresh the edit post page, the select control now receives the value and pre-selects it in the 'image size' dropdown.

Haven't look at why it's pulling from deprecated yet.

**Comment by glendaviesnz** [comment] 2021-09-10 03:08
I wasn't able to replicate this in the refactored gallery so closing. Feel free to reopen if you can replicate in the new gallery format - enable the Gallery block experiment to test:
<img width="592" alt="Screen Shot 2021-09-10 at 3 08 14 PM" src="https://user-images.githubusercontent.com/3629020/132793243-932b8867-f437-47ee-93fa-cfabff98e405.png">

**Closed by glendaviesnz** 2021-09-10 03:08 UTC
Labels: [Type] Bug, [Block] Gallery
