### ISSUE TITLE
Disabling plugin crashes block editor / Enabling it means "All posts" page won't load..

### ISSUE THREAD

**Issue by MrCrin** [WordPress/gutenberg#14602] opened 2019-03-24 17:22 UTC
I have uninstalled the plugin and now I can't create new posts, or edit existing ones, even in troubleshooting mode with all other plugins disabled.

The edit page loads ok, but as soon as you hover over the space where a new block would be (in new posts) or click on an existing block (when editing an existing post) the editor crashes out with the following error...

TypeError: Cannot read property 'core/paragraph' of undefined
    at zn (https://crin.co.uk/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45280)
    at https://crin.co.uk/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:46071
    at Array.map (<anonymous>)
    at https://crin.co.uk/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45906
    at u (https://crin.co.uk/wp-includes/js/dist/editor.min.js?ver=9.0.11:12:3427)
    at https://crin.co.uk/wp-includes/js/dist/data.min.js?ver=4.2.1:1:6379
    at https://crin.co.uk/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:109194
    at n (https://crin.co.uk/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13036)
    at new r (https://crin.co.uk/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13298)
    at zf (https://crin.co.uk/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258)

If I reinstall the plugin the block editor will work normally but then the "all posts" page won't load.

EDIT: It's https://crin.co.uk/wp-admin/edit.php that won't load once the plugin is reinstalled and activated. If I disable the plugin then the problem reverts to crashing the block editor.

**Comment by youknowriad** [comment] 2019-03-25 10:30
Can you try clearing the local storage?

**Comment by youknowriad** [comment] 2019-03-25 10:30
I suspect this happens because downgrading Gutenberg is broken now because of the block editor refactoring. We should find a way to not load the previous preferences if they break the editor.

**Comment by aristath** [comment] 2019-03-25 10:36
+1 on this one, I've encountered this issue as well on multiple occasions and multiple sites

**Comment by youknowriad** [comment] 2019-03-25 10:37
Actually, I think this is a duplicate of #14580

**Closed by youknowriad** 2019-03-25 10:37 UTC
Labels: [Type] Bug
