### ISSUE TITLE
Widgets editor: React state warning after 2nd interaction between widget areas

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#31907] opened 2021-05-17 19:15 UTC
## Description
A React state update warning occurs on the second interaction between ~active and "Inactive widgets"~ areas.

## Step-by-step reproduction instructions

Attempting to move more than one block from "Inactive widgets" to an active widget area:

1. Go to Appearance → Widgets
2. Adds blocks to "Inactive widgets"
3. Update
4. Refresh browser
5. Move one block from "Inactive widgets" to an active widget area
6. Click on another block in the "Inactive widgets" area => notice the warning in the browser's console

Attempting to move a widget or block from "Inactive widgets" to an active widget area _after_ moving an active widget or block to the "Inactive widgets" area:

1. Go to Appearance → Widgets
2. Drag a widget or block to the "Inactive widgets" area
3. Update
4. Refresh browser
5. Move one block from "Inactive widgets" to an active widget area
6. Click on another block in the "Inactive widgets" area => notice the warning in the browser's console

Attempting to move an active widget or block to the "Inactive widgets" area:

1. Go to Appearance → Widgets
2. Drag a widget or block to the "Inactive widgets" area
3. Click on another widget or block in an active widget area => notice the warning in the browser's console

Using Twenty Twenty theme, attempting to move widgets or blocks between active widget areas:

1. Go to Appearance → Widgets
2. Drag a widget or block from Footer #1 to Footer #2
3. Click on another block in Footer #1, Footer #2, or "Inactive widgets" area => notice the warning in the browser's console

## Expected behaviour
No errors, notices, or warnings in the console.

## Actual behaviour

The warning flagged in this file: http://[my local site]/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ot (created by WPComponentsTooltip)
    in WPComponentsTooltip (created by ForwardRef)
    in ForwardRef (created by Js)
    in Js (created by fa)
    in fa
    in div
    in Unknown
    in Unknown (created by WithSelect(Component))
    in WithSelect(Component) (created by Is)
    in div (created by Wf)
    in Wf (created by $f)
    in $f (created by Is)
    in div (created by Is)
    in div (created by Is)
    in Is (created by xs)
    in div (created by ForwardRef(g))
    in ForwardRef(g) (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ls)
    in ls (created by xs)
    in div (created by xs)
    in xs (created by Ns)
    in div (created by k)
    in div (created by k)
    in div (created by k)
    in p (created by O)
    in O (created by k)
    in k (created by Ns)
```

The warning did not prevent the ability to move blocks or widgets. However, it does prevent updating and gives an update status of:
>There was an error. a is undefined

<img width="287" alt="Screen Shot 2021-05-17 at 2 17 59 PM" src="https://user-images.githubusercontent.com/7284611/118544116-cf4e9b00-b71a-11eb-929c-d9fbe80d4434.png">

## Screenshots or screen recording (optional)

![react-warning-inactive-widgets](https://user-images.githubusercontent.com/7284611/118542252-623a0600-b718-11eb-8cb8-ffb9c5c991e1.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur
- Browser: Chrome 90.0, Firefox 88.0.1

**Comment by hellofromtonya** [comment] 2021-05-17 19:26
Updated title and description after finding the problem also happens when moving blocks or widgets between active widget areas such as between Footer 1 and Footer 2 in the Twenty Twenty theme.

**Comment by tellthemachines** [comment] 2021-06-22 05:13
I can no longer reproduce this on latest trunk. @kevin940726, you mentioned #32729 partially addressed this. Is there anything still to do before we can close this issue?

**Comment by kevin940726** [comment] 2021-06-22 06:59
> I can no longer reproduce this on latest trunk. @kevin940726, you mentioned #32729 partially addressed this. Is there anything still to do before we can close this issue?

I didn't test all the cases mentioned here in #32729. It's possible that #32729 solved multiple issues here. If we can't reproduce it anymore then sure let's close this.

**Comment by tellthemachines** [comment] 2021-06-23 01:08
I can no longer reproduce any of these scenarios, so closing as fixed.

**Closed as completed by tellthemachines** 2021-06-23 01:08 UTC
Labels: [Type] Bug, [Feature] Widgets Screen
