### ISSUE TITLE
Copy and pasting URLs is messing with Anchor links

### ISSUE THREAD

**Issue by camilopbam** [WordPress/gutenberg#21112] opened 2020-03-24 16:33 UTC
**Describe the bug**
Gutenberg copy/paste handler is auto-completing relative path hash fragments with the current edit page URL.

**To reproduce**
1. in a paragraph block(or any RichText input) create an anchor link using a relative path hash fragment. e.g. #test-section
2. Copy the Anchor link and paste it in the same or other block.
3. Check the url of the anchor you just pasted. 
![ezgif com-optimize (2)](https://user-images.githubusercontent.com/54121990/77451501-bf5f5380-6dc2-11ea-813d-02d0615bedd5.gif)

**Expected behavior**
If I copy an anchor with the url #test-section it should be maintain said URL,  not auto-complete it.

**Additional context**
- Tested in Chrome, Safari, Mozilla and Brave
- WordPress 5.3.2

**Comment by jorgefilipecosta** [comment] 2020-03-25 10:42
Hi @camilopbam thank you for reporting this issue.

I was able to reproduce the issue in Gutenberg master and WordPress 5.3.2. I think the issue happens because when copy-pasting the browsers pass the href with an URL and not only the anchor.

**Comment by talldan** [comment] 2021-07-21 05:44
Closing as this no longer happens. There was a different bug that I spotted when testing - #33585.

**Closed by talldan** 2021-07-21 05:44 UTC
Labels: [Feature] Link Editing, [Feature] Raw Handling, [Package] Format library, [Type] Bug
