### ISSUE TITLE
Settings:Document:Page Attributes:Parent Page no pages shown

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#5782] opened 2018-03-25 14:14 UTC
## Issue Overview

Unable to pick Parent Page from Page Attributes

## Steps to Reproduce (for bugs)

1. Ediit a new page (site has other pages defined)
2. Open the Settings : Document view
3. In the Page Attributes, try to pick a Parent Page
4. only choice is (no parent)

## Expected Behavior

Full list of existing pages

## Current Behavior

(no parent)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by pento** [comment] 2018-04-21 11:56
Thank you for the bug report, @weavertheme!

I'm unable to reproduce this behaviour: my test install shows a complete list of pages that I can choose as the Parent Page. Could you please re-test and confirm that you're still seeing this issue?

**Comment by weavertheme** [comment] 2018-04-21 16:00
This is still a big issue on my own test sites.

On my test sites, I find it far easier to use the old page method with order and parent page, and will thus test without selecting any menu.

After some more testing of this issue,  I think I understand what is going on at this point, and I guess it might be an intentional decision on the team's part.

The Parent Page list does not work the same as the Parent Page on the classic editor. The classic editor shows **all** pages, even those not assigned to any custom menu. The Parent Page list in the block editor seems to show only pages from a custom menu - probably the one containing the page - I haven't figured that out. But whatever, it does seem to show only a small list of other pages, or possibly no other pages if the page is not on a menu. (What happens to new pages - shouldn't they be able to be assigned to a parent?)

Even when it shows some pages, it takes 10 or 15 seconds to even show up. Perhaps the title can popup to indicate the list is being built?

So, my request:

It should work just like the classic editor - show all pages, or have the option to. At the least, if the current page is NOT assigned to a menu, then all pages could be shown? (And what is the behavior if the menu is multiple places on the custom menu.)

 I sincerely believe that for sites with many many pages (like a development site with many test pages...), the custom menu approach is extremely difficult to use. It is just so much slmpler to add a new test page to the appropriate place on the testing hierarchy. It is nearly impossible to search through 4 or 5 pages of listed pages on the Custom Menu interface. It seems that many themes no longer support the legacy menu structure, but some do.

Now I may have figured this out incorrectly, but only showing a limited set of parents is the only thing that makes sense with the observed behavior I see.

If you need to see this working on my test site, I can provide credentials.

**Comment by weavertheme** [comment] 2018-04-24 14:12
I'm not so sure it is really related to the default menu or not. Here are some images for the Page Attributes of the same page:

1 GB Page Attributes:
![gb-page-attributes](https://user-images.githubusercontent.com/2816397/39192719-11b09652-4797-11e8-8688-f1ed82cc1895.jpg)

2. Classic Editor Page Attributes:
![classic-page-attributes](https://user-images.githubusercontent.com/2816397/39192743-21bbf168-4797-11e8-8080-34169b6ece3c.jpg)

And the pop down list of pages from the classic editor include ALL of my pages (dozens of them). I think this should be the behavior from the Gutenberg editor.

**Comment by danielbachhuber** [comment] 2018-05-14 13:04
@weavertheme I _think_ this is a duplicate of #6487, which will be fixed with the next Gutenberg release.

**Closed by danielbachhuber** 2018-05-14 13:04 UTC
Labels: [Status] Needs More Info, [Type] Enhancement
