### ISSUE TITLE
Gallery Block image selector works, but selector doesn't change

### ISSUE THREAD

**Issue by nosilver4u** [WordPress/gutenberg#27492] opened 2020-12-03 23:59 UTC
**Describe the bug**
When inserting a gallery block, changing the Image Size from the default (Large) to anything else does not change the option in the selector itself. I can see that the sizes DO change, because the images shift to accomodate the new sizing. For example, going from Large to Thumbnail causes everything to become square (using cropped thumbs) and vice versa. But the selector still says Large.

**To reproduce**
1. Create a post/page
2. Insert a gallery block (with uploaded or existing images)
3. Change the Image Size selector in the Block settings sidebar
4. The effective image size appears to change (also can be verified by previewing or saving/viewing the post). But the selector is stuck on Large.

**Expected behavior**
I expect the value I selected to actually display in the drop-down box.

**Editor version (please complete the following information):**
- WordPress version: 5.6-rc2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?
Also tested the latest Gutenberg plugin - 9.5
Note, the error does NOT occur with WP 5.5, tested on the same server, and a different server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome & Firefox
 - Version: 87 & 83 respectively

**Additional context**
This happened with a handful of plugin enabled, but was replicated when all plugins were disabled (except when testing the latest Gutenberg of course). The theme in use is the Twenty Twenty theme, also tested with the Twenty Twenty-One theme.

**Comment by tellthemachines** [comment] 2020-12-04 03:12
I can reproduce this with 5.6 RC3 and with Gutenberg 9.5.

**Comment by gziolo** [comment] 2021-01-12 13:55
From #27630 

<img src="https://user-images.githubusercontent.com/1898325/101701885-8d7c4300-3a5e-11eb-9b13-fbdc8d3a3719.gif" alt="Screenshot showing image sizing in Gallery block not working">

**Comment by brentswisher** [comment] 2021-01-13 22:07
I started looking into this but am unable to recreate the problem with the latest version of Gutenberg master branch - I tried in both Chrome and Firefox. It looks like the examples here are from Gutenberg 9.4.1 and 9.5. Wondering if this has been inadvertently fixed in the mean time. Could anyone else try to recreate on the latest version?

**Comment by brentswisher** [comment] 2021-01-13 22:13
Ah, I did a little more digging into the code history, and it appears this was likely fixed in #27691 which was after both examples above. @nosilver4u or @tellthemachines could you verify that it is working for you now and then we can probably close this issue.

**Comment by tellthemachines** [comment] 2021-01-15 03:49
Can confirm this is fixed in 9.7.2. Closing, thanks everyone!

**Closed by tellthemachines** 2021-01-15 03:49 UTC
Labels: [Block] Gallery, [Type] Bug

**Comment by nosilver4u** [comment] 2021-01-15 04:51
Verified for me also, but @tellthemachines beat me to it :)

**Comment by daermail** [comment] 2021-02-23 23:23
The issue is still around for me unfortunately. :(
