### ISSUE TITLE
Anchor: true breaks block validation

### ISSUE THREAD

**Issue by espenjanson** [WordPress/gutenberg#12912] opened 2018-12-15 18:53 UTC
**Describe the bug**
Setting 

```
supports: {
anchor: true
}
```

causes block validation to fail, the ID attribute is missing from the expected block content:

```

Block validation: Block validation failed for `rfw-blocks/intro-section`

Expected:

<div class="wp-block-rfw-blocks-intro-section">

Actual:

<div class="wp-block-rfw-blocks-intro-section" id="my-anchor">

```

**To Reproduce**
1. Set supports anchor true
2. Set anchor tag
3. Save block
4. View page
5. Go back into editor

**Expected behavior**
Should not fail

**Additional context**
- Wordpress 5.0.1

**Comment by goldenapples** [comment] 2019-05-30 17:37
I ran into the same issue recently and it turned out that I was filtering the block to add anchor support _after_ the hooks which added the "id" attribute is added by core. Since the addAttribute decorator checks for "anchor" support, if that support isn't registered before that function runs, you'll get validation errors on opening the editor.

Code I had which caused validation errors:

```
/**
 * Add "anchor" support to all registered block types.
 */
const addAnchorSupport = settings => ( {
	...settings,

	supports: {
		...settings.supports,
		anchor: true,
	},
} );

addFilter( 
    'blocks.registerBlockType', 
    'my-project/add-anchor-support', 
    addAnchorSupport
);
```

By changing the priority of my hook to 9, I was able to avoid the validation errors.

```
addFilter( 
    'blocks.registerBlockType', 
    'my-project/add-anchor-support', 
    addAnchorSupport,
    9
);
```

**Comment by talldan** [comment] 2020-03-05 05:43
Hi @espenjanson Sorry for the amount of time taken to respond. Is this something you're still experiencing? If so, it'd be great if you could share the code for your block so that others can try to reproduce the issue. Thanks.

**Comment by espenjanson** [comment] 2020-03-17 20:08
@talldan Sorry, I am not currently doing any WordPress development and the code I was working on is buried in an old client project. Can't remembered if this was ever solved, but I think the error was pretty straight forward at the time - I tried to follow the docs but received an error. If this is no longer this case, I'm sure it has been solved by now :)

**Comment by talldan** [comment] 2020-03-19 06:45
@espenjanson It's used in a couple of core blocks (heading and group) and I wasn't able to reproduce any issue with those. I'll close the issue for now, but it can always be reopened if this reoccurs.

**Closed by talldan** 2020-03-19 06:45 UTC
Labels: Needs Testing, [Feature] Block API
