### ISSUE TITLE
[Widgets Editor] The toggle arrow is not rotated when the widget area is expanded

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#25723] opened 2020-09-30 04:07 UTC
**Describe the bug**
The toggle arrow icon is not rotated when widget area is not expanded in the widget editor. The toggle arrow icon on the right is not down arrow. See the screenshot below for more info.

**To reproduce**
1. Go to 'Widgets editor'
2. Click the first widget area to collapse it
3. Observe that the toggle arrow is not rotated

**Expected behavior**
The toggle arrow icon should rotate 180 deg.

**Screenshots**

![image](https://user-images.githubusercontent.com/7753001/94657049-7a007d80-0333-11eb-8e3f-79354dd3b836.png)

**Comment by adamziel** [comment] 2020-09-30 08:27
This is a duplicate of https://github.com/WordPress/gutenberg/issues/25675

**Closed by adamziel** 2020-09-30 08:27 UTC
Labels: Good First Issue, [Feature] Widgets Screen, [Type] Bug
