### ISSUE TITLE
Resized center-aligned images do not appear centered in the editor. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#21152] opened 2020-03-25 16:13 UTC
#### Steps to reproduce

1. Add an image.
2. Resize it to be a custom size using the handles or the sidebar. 
3. Set the image to be center-aligned.
4. Observe that the image appears to be left-aligned, instead of centered. 

#### Screenshot / Video

![resize-align-center](https://user-images.githubusercontent.com/1202812/77558748-b38e9280-6e91-11ea-9cb7-3a6ed2949cd2.gif)

^ Gutenberg Starter Theme

#### Details

Tested in Safari 13.0.5, using Gutenberg 7.71 and 7.8.0-rc.1. 
Tried with Twenty Twenty and also the Gutenberg Starter Theme

**Comment by roo2** [comment] 2020-03-26 01:30
This one is also caused by https://github.com/WordPress/gutenberg/pull/20658/files

**Comment by roo2** [comment] 2020-03-26 01:41
I've made a PR to revert #20658 which fixes this for me locally. It now needs testing
https://github.com/WordPress/gutenberg/pull/21160

**Comment by mikeicode** [comment] 2020-03-27 16:21
This came up 19688573-hc

**Comment by roo2** [comment] 2020-03-30 06:43
May be fixed by #21167

**Comment by scosgro** [comment] 2020-03-31 20:24
Also appeared in 19880008-hc

**Comment by noahtallen** [comment] 2020-04-06 19:49
I just tested this locally and could not replicate, so I'll assume it was resolved by #21167 unless folks have other concerns. The fix should be in the next Gutenberg Plugin release 👍

**Closed by noahtallen** 2020-04-06 19:49 UTC
Labels: [Block] Image, [Type] Bug
