### ISSUE TITLE
Blocks that contain `Editable` have different styling from blocks that do not

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1744] opened 2017-07-05 16:20 UTC
From https://github.com/nylen/gutenberg-boilerplate-es5:

![2017-07-05t18 08 23 0200](https://user-images.githubusercontent.com/227022/27873717-65b0538a-61ad-11e7-8b07-8d017c67f30a.png)

Note that the [step 1](https://github.com/nylen/gutenberg-boilerplate-es5/blob/3d67408017a8a88fc04c0f134b2b3a709e959fe7/step-01/block.js) and [step 2](https://github.com/nylen/gutenberg-boilerplate-es5/blob/3d67408017a8a88fc04c0f134b2b3a709e959fe7/step-02/block.js) blocks (which do not contain an `Editable` instance) have extra margins around their root-level `p` elements.  This is because of [this CSS rule in core](https://core.trac.wordpress.org/browser/tags/4.8/src/wp-admin/css/common.css?marks=307#L304).

However, the [step 3](https://github.com/nylen/gutenberg-boilerplate-es5/blob/3d67408017a8a88fc04c0f134b2b3a709e959fe7/step-03/block.js) and [step 4](https://github.com/nylen/gutenberg-boilerplate-es5/blob/3d67408017a8a88fc04c0f134b2b3a709e959fe7/step-04/block.js) blocks look as they should.  This is because these blocks contain `Editable` instances for their root-level `p` elements, and we override this rule for TinyMCE elements [here](https://github.com/WordPress/gutenberg/blob/2f3a79df4fe4ee76c9391d87ddb631137aae397d/blocks/editable/style.scss#L6):

![2017-07-05t18 17 35 0200](https://user-images.githubusercontent.com/227022/27874002-46938a52-61ae-11e7-87a1-1e513d131a82.png)

To fix this, we should probably remove margins for more `p` elements inside the editor.

**Comment by nishitlangaliya** [comment] 2017-07-06 07:35
fixes- 1744 ,

I have done the pr https://github.com/WordPress/gutenberg/pull/1756 please check for the same and let me know if if any changes required.

Thanks

**Comment by youknowriad** [comment] 2018-02-15 13:47
Is this still an issue, we do have `RichText` and `PlainText` right now with similar styles and other blocks look consistent as well?

**Comment by youknowriad** [comment] 2018-02-15 13:48
I can't reproduce this anymore. Closing

**Closed by youknowriad** 2018-02-15 13:48 UTC
Labels: Blocks, [Type] Bug
