### ISSUE TITLE
Gutenberg deactivation breaks core block editor

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#14680] opened 2019-03-28 11:49 UTC
**Describe the bug**
Installing Gutenberg 5.3 with WordPress 5.1.1, activating and deactivating makes the block-editor error and unusable.

**To Reproduce**
1. Start with a brand new, clean WordPress 5.1.1 site
1. Install Gutenberg 5.3
1. Activate Gutenberg plugin
1. Interact with the block editor (create a new post)
1. Dectivate Gutenberg plugin
1. Interact with the block editor (create a new post)
1. Repeat steps 3-6 and eventually you'll see the error.

The error appears to persist until Gutenberg is re-activated.

**Expected behavior**
Gutenberg can be deactivated without breaking the block editor.

**Screenshots**

Copied the error from the editor.

```
TypeError: Cannot read property 'core/paragraph' of undefined
    at zn (https://huge-urial.jurassic.ninja/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45280)
    at https://huge-urial.jurassic.ninja/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:46071
    at Array.map (<anonymous>)
    at https://huge-urial.jurassic.ninja/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45906
    at u (https://huge-urial.jurassic.ninja/wp-includes/js/dist/editor.min.js?ver=9.0.11:12:3427)
    at https://huge-urial.jurassic.ninja/wp-includes/js/dist/data.min.js?ver=4.2.1:1:6379
    at https://huge-urial.jurassic.ninja/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:109194
    at n (https://huge-urial.jurassic.ninja/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13036)
    at new r (https://huge-urial.jurassic.ninja/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13298)
    at zf (https://huge-urial.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258)
```

With `SCRIPT_DEBUG`, the stack trace is as follows:

```
dmp.js:19 Uncaught TypeError: Cannot read property 'core/paragraph' of undefined
    at getInsertUsage (dmp.js:19)
    at buildBlockTypeInserterItem (dmp.js:19)
    at Array.map (<anonymous>)
    at dmp.js:19
    at callSelector (dmp.js:19)
    at runSelector (data.js?ver=4.2.1:709)
    at dmp.js:19
    at getNextMergeProps (data.js?ver=4.2.1:1738)
    at new ComponentWithSelect (data.js?ver=4.2.1:1756)
    at constructClassInstance (react-dom.js?ver=16.6.3:12604)
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Chrome 72

**Comment by youknowriad** [comment] 2019-03-28 11:51
Duplicate of #14580

**Closed by youknowriad** 2019-03-28 11:51 UTC
