### ISSUE TITLE
Gallery block is not loading image size

### ISSUE THREAD

**Issue by celiance** [WordPress/gutenberg#49022] opened 2023-03-13 10:51 UTC
I uploaded various galleries with lots of photos (100+). Unfortunately the image size is not loading when this amount of images are involved. 
[printscreen.pdf](https://github.com/WordPress/gutenberg/files/10956412/printscreen.pdf)

**Comment by carolinan** [comment] 2023-03-13 11:20
Hi!
Does it work again if you disable all plugins except Gutenberg?

**Comment by glendaviesnz** [comment] 2023-03-13 22:32
If you are able to try this in Chrome and open up the dev tools console (More tools -> Developer tools) and under the Network tab add `/wp/v2/media` in the filter box and reload the page with the Gallery on and see if the call to the media API endpoint returns an error, of so if  you are able to add the error message in the `Response` tab that will help try and track down the cause of this issue, thanks.

<img width="885" alt="Screenshot 2023-03-14 at 11 28 21 AM" src="https://user-images.githubusercontent.com/3629020/224847182-e2e91367-6c16-4481-931f-eedb4e1f4fcd.png">

**Comment by Mamaduka** [comment] 2023-03-14 07:56
I believe we resolved a similar issue via #46143.

@celiance, what version of WP and Gutenberg plugin are you using?

**Comment by ndiego** [comment] 2023-04-25 15:47
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. 

@celiance Would you be able to share the version of WordPress and Gutenberg you are using? This would help us diagnose further. Thanks!

**Comment by ndiego** [comment] 2023-05-02 16:50
This issue was reviewed again in today's Editor Bug Scrub. We have been unable to replicate it using the latest versions of Gutenberg and WordPress, but it appears to be similar to #47526, which was reported earlier. Therefore, I am going to close this issue as a duplicate.

**Closed as completed by ndiego** 2023-05-02 16:50 UTC
Labels: [Type] Bug, [Status] Needs More Info, Needs Testing, [Block] Gallery
