### ISSUE TITLE
Cover Block: fixed background issue

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/gutenberg#28425] opened 2021-01-22 16:06 UTC
## Description
In Gutenberg 9.8+ the cover block image is not visible when selecting the Media settings > Fixed background option.

## Step-by-step reproduction instructions
Add a cover block with a background image.
In Media settings, select the Fixed background option.

## Expected behaviour
The cover image should be visible when refreshing the editor or navigating away and then going back to edit the post.

## Actual behaviour
Initially the image is visible, but when refreshing the editor or navigating away and then going back to edit the post, the image is not visible.
Instead only the overlay color is visible.
Deselect the fixed background option and the cover image appears.
The above describes the behavior with a non-fse theme active.
With a FSE theme active, the image also disappears when adjusting the block align options.

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Dekstop
- Operating system: Windows 10
- Browser: various, all same result

**Comment by stokesman** [comment] 2021-02-02 16:09
I believe this was fixed by the changes in #28565. I've tested with the plugin built off master. It looks like those changes are going to be in 9.9 so could be verified then.

**Comment by brentswisher** [comment] 2021-02-03 21:25
I've also confirmed that this is no longer happening for me in master and was likely fixed in #28565,  so I'm closing this issue. Thanks for the report @Sandstromer and the follow-up @stokesman!

**Closed by brentswisher** 2021-02-03 21:25 UTC
Labels: [Block] Cover, [Type] Bug
