### ISSUE TITLE
Console errors in Gutenberg 4.4.

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#11977] opened 2018-11-16 13:03 UTC
**Describe the bug**
When I load gutenberg (4.4) in browser, I get a high number console errors. See screenshot. 

**To Reproduce**
1. Open post edit screen in browser. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/237508/48622589-24b95e00-e99f-11e8-867e-261162475a0f.png)
![image](https://user-images.githubusercontent.com/237508/48622592-27b44e80-e99f-11e8-8927-344660930313.png)
![image](https://user-images.githubusercontent.com/237508/48622597-2aaf3f00-e99f-11e8-99d9-cdeed0e1daa8.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome
 - Version: 70.0.3538.102

**Additional context**
- Gutenberg 4.4 
- Yoast SEO 9.1

**Comment by tofumatt** [comment] 2018-11-16 13:16
Any chance this is related to the recent React upgrade in #11840? cc @gziolo @youknowriad

**Comment by tofumatt** [comment] 2018-11-16 13:18
Seems like this'd be fixed by #11360. These warnings don't imply anything is broken, for what it's worth. We just have to update our code to move to new APIs 😄

**Comment by youknowriad** [comment] 2018-11-16 13:18
yes, it is related most of these are not coming from Gutenberg thought but more from plugins using deprecated APIs, Gutenberg itself is still using one or two deprecated APIs (the first warning I think). I'm closing this as a duplicate of #11360 but at the same time you should try to reach out the plugin authors using these too.

When it comes to the React update, it didn't add any new warnings to Gutenberg itself.

**Comment by spacedmonkey** [comment] 2018-11-16 13:19
Looking into this, I am only seeing this when `define( 'SCRIPT_DEBUG', true );` Even so, I get over 200 errors in console, seems like a lot. It seems to be linked to react-dom

**Comment by tofumatt** [comment] 2018-11-16 13:19
Ah, noted, my bad.

**Closed by youknowriad** 2018-11-16 13:18 UTC
Labels: Code Quality

**Comment by spacedmonkey** [comment] 2018-11-16 13:45
Below is screenshots from a fresh install of WordPress 4.9.8 with no other plugins than gutenberg. 

![image](https://user-images.githubusercontent.com/237508/48624921-a1e7d180-e9a5-11e8-94ee-fcd9f2ee68b2.png)
![image](https://user-images.githubusercontent.com/237508/48624898-92688880-e9a5-11e8-9c42-5ead396fe99d.png)

@youknowriad ^

**Comment by youknowriad** [comment] 2018-11-16 14:01
Yes, nothing really concerning, but it should be fixed when #11360 is closed.
