### ISSUE TITLE
YouTube blocks do not render inside of reusable blocks

### ISSUE THREAD

**Issue by cagrimmett** [WordPress/gutenberg#37467] opened 2021-12-16 20:05 UTC
### Description

When a YouTube block is inside of a resuable block, it only renders as a link on the front-end rather than the embedded video. The same video renders just fine outside of the reusable block.

### Step-by-step reproduction instructions

1. Create a new post.
2. Add any public YouTube video as a YouTube block.
3. Make that block a reusable block.
4. Publish and view the post.
5. The video only renders as a link, rather than the embedded video.

### Screenshots, screen recording, code snippet

<img width="798" alt="CleanShot 2021-12-16 at 14 52 37@2x" src="https://user-images.githubusercontent.com/8738771/146439988-8317e9af-a2df-45b7-a20b-3644692702f8.png">

### Environment info

- WordPress 5.8.2
- Issue happens with and without the Gutenberg plugin running
- All themes

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by NewYorkerLaura** [comment] 2021-12-17 13:54
Upon further testing the identical issue also arises in the following blocks:

- Vimeo Block
- Embed Block

**Comment by Mamaduka** [comment] 2021-12-21 13:14
I am closing this as a duplicate of #14608.

**Closed as completed by Mamaduka** 2021-12-21 13:14 UTC
Labels: [Type] Bug, [Feature] Synced Patterns, [Status] Duplicate, [Block] Embed
