### ISSUE TITLE
Making it easier to transition to Gutenberg

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7060] opened 2018-05-31 16:43 UTC
I noticed when activating Gutenberg then going to the frontend and clicking edit post/page that Gutenberg becomes the default editor. I thought the frontend would add a link to where one could choose to edit the post/page with the Classic editor or Gutenberg. (Similar to the Add New drop down button next to post/pages.)

While in the Gutenberg edit screen I see now way to switch over to the Classic Editor. I expected to click the top right 3 dots, and in the drop down and have the option to switch over to using the Classic Editor.

**Comment by GlennMartin1** [comment] 2018-05-31 19:10
1. Click on Posts or Page. All posts or pages will be displayed.
2. When hovering the mouse over any post or page, there's an option displayed for "Edit" and "Classic Editor".

"Edit" opens in Gutenberg; "Classic Editor" opens in the Classic Editor.

You can convert a page/post from Classic to Gutenberg.
You can**not** convert a page/post from Gutenberg to Classic.

Not a bug - that's by design.

**Comment by paaljoachim** [comment] 2018-05-31 20:48
Three different areas:
**Frontend:**

Right now:
![screen shot 2018-05-31 at 22 27 29](https://user-images.githubusercontent.com/5323259/40806515-162e4618-6522-11e8-829b-7c3d6820e979.png)

Can be:
![frontend-edit-page-gutenberg-wireframe](https://user-images.githubusercontent.com/5323259/40807047-8753957c-6523-11e8-92a1-6ae3ab8a2d76.jpg)

Notice the classic editor edit option.


All Posts/All Pages:
![screen shot 2018-05-31 at 22 28 10](https://user-images.githubusercontent.com/5323259/40807104-af0a5150-6523-11e8-8a8f-475c2ed18e02.png)

Inside a post or page:

Right now:
![edit-page-gutenberg-3dot-dropdown](https://user-images.githubusercontent.com/5323259/40807423-8beed046-6524-11e8-886f-9fbb25574d99.jpg)

Can be:
![edit-page-gutenberg-3dot-dropdown-wireframe](https://user-images.githubusercontent.com/5323259/40807446-98e61232-6524-11e8-915e-4cc7da76b32e.jpg)

Notice the Classic Editor option inside the drop down.

This creates a better integration of the Classic Editor with Gutenberg.

**Comment by danielbachhuber** [comment] 2018-06-04 14:42
Flagging as `Needs Design Feedback` to see if this is something we want to incorporate.

**Comment by karmatosed** [comment] 2018-06-09 16:39
For now let's not do this, we won't be shipping with 2 editors when 5.0 happens. In that light lets close this.

**Closed by karmatosed** 2018-06-09 16:39 UTC
Labels: Needs Design Feedback
