### ISSUE TITLE
wp-env: Add support for wp-cli shell

### ISSUE THREAD

**Issue by pablinos** [WordPress/gutenberg#22347] opened 2020-05-14 11:05 UTC
**Is your feature request related to a problem? Please describe.**
While using `wp-env` I tried to run the shell using the `run` command. It hung, as it was waiting for input, while the run command waits for the process to complete.

**Describe the solution you'd like**
I'd like some kind of 'interactive' flag to the run command or a dedicated `shell` command, so that I can run wp-cli shell in the docker environment.

**Describe alternatives you've considered**
I'm currently getting round this with the following (very poorly constructed) shell command in the `scripts` section of my `package.json`

```
docker-compose -f $HOME/.wp-env/`md5 -qs $PWD/.wp-env.json`/docker-compose.yml run --rm cli wp shell
```

Another option might be to have a command that outputs the path of the current environment's `docker-compose.yml`, so you can run `docker-compose` commands without having to determine that or the appropriate container ID.

**Comment by noahtallen** [comment] 2020-05-21 01:57
Sounds like a great idea!

**Comment by noahtallen** [comment] 2020-05-21 02:04
Closing as duplicate of #21301, which has been around for a bit longer. feel free to continue discussion there :)

**Closed by noahtallen** 2020-05-21 02:04 UTC
Labels: [Package] Env

**Comment by pablinos** [comment] 2020-05-21 04:23
Ah, thanks @noahtallen, my GitHub searching skills failed me!

**Comment by noahtallen** [comment] 2020-05-21 04:24
no problem!
