### ISSUE TITLE
Wide-aligned blocks: Non latin text characters are rendered as gibberish inside the block if set to Wide or Full Width

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#24445] opened 2020-08-07 14:53 UTC
**Describe the bug**

First reported by @zdenys at https://github.com/Automattic/wp-calypso/issues/44759. The following is a copy of that issue, since it applies to Gutenberg.

**To reproduce**
1. Add a Cover block with paragraph of text with some or all non-Latin characters (I tried Norwegian, Japanese and Chinese)
2. Set Cover Block to Wide or Full Width
3. View Preview or Published site

**Expected behavior**
See all characters rendered normally on the front end just like on the backend. 

**Screenshots**
![](https://d.pr/i/5gdq1V+)
_Link: https://d.pr/i/5gdq1V_

![](https://d.pr/i/gFwXfS+)
_Link: https://d.pr/i/gFwXfS_

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.7

**Additional context**
Encoding issue. PR coming right up.

cc/ @sirreal @akirk @simison @yansern

**Comment by mcsf** [comment] 2020-08-07 14:54
Thanks for the report! To be clear, this only affects server-side-rendered blocks, is that correct?

**Comment by ockham** [comment] 2020-08-07 15:13
> Thanks for the report! To be clear, this only affects server-side-rendered blocks, is that correct?

I think so, but haven't run any broader testing for other blocks yet.

**Comment by sirreal** [comment] 2020-08-07 17:44
Apparently I closed this unintentionally. Reopening. This should be fixed by https://github.com/WordPress/gutenberg/pull/24447

**Closed** 2020-08-11 08:47 UTC
Labels: [Priority] High, [Status] In Progress, [Type] Bug

**Comment by pedro-rivera** [comment] 2020-08-14 14:57
Facing the same problem on a local environment, WP 5.5, Gutenberg 8.7.1:

![Block Issue](https://i.imgur.com/dPODLIf.png)

Where it's read **direÃ§Ã£o** should be **direção** (pt-BR)

**Comment by mcsf** [comment] 2020-08-17 09:30
> Facing the same problem on a local environment, WP 5.5, Gutenberg 8.7.1:

The issue is fixed in `master` and should land in Gutenberg 8.8 later this week.
