### ISSUE TITLE
After pasting a text, the cursor moves to the starting of the text

### ISSUE THREAD

**Issue by GutenDev** [WordPress/gutenberg#11569] opened 2018-11-07 09:58 UTC
**Describe the bug**
When I copy and paste a line of text, the blinking cursor goes back to the beginning of the text. 

**To Reproduce**
1. Pase a text on a paragraph block
2. Look at your cursor 

**Expected behavior**
The cursor should go to the end of the pasted text. 

**Screenshots**
![copied text](https://user-images.githubusercontent.com/44389517/48124159-d7096b00-e2a5-11e8-80fd-e8065ad4bd70.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Google Chrome
 - Version 70

**Comment by designsimply** [comment] 2018-11-07 14:32
Thank you for the report! Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/5317.

**Closed by designsimply** 2018-11-07 14:32 UTC
Labels: Writing Flow, [Component] Raw Handling, [Status] Duplicate, [Type] Bug
