### ISSUE TITLE
Block Inserter between blocks doesn't show reliably

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24745] opened 2020-08-23 09:09 UTC
**Describe the bug**
When trying to insert a block between existing blocks, the Add Block icon rarely shows and when it does, it's quite often in the wrong place.

vid: https://share.getcloudapp.com/7KuLEKAd

**To reproduce**
1. Edit existing page
2. Try to add a new block between your existing blocks by hovering the cursor between blocks

**Expected behavior**
It shouldn't be this difficult to add a new block to your content

**Editor version (please complete the following information):**
-WordPress version: [5.5]
-Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
-If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):
-OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

See also #24743

**Comment by talldan** [comment] 2020-08-25 01:36
Closing as a duplicate of #22801

**Closed by talldan** 2020-08-25 01:36 UTC
