### ISSUE TITLE
I want feature 'disable auto block changing' option.

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#10778] opened 2018-10-19 06:35 UTC
I can't speak English well. Please understand me.
I think you guys never read feedback. So I write here. I want gutenberg becomes better and better.

I want 'disable auto block changing' feature option.

I usually write list in post like that.

1. 명사적 용법
    동명사는 명사적 기능을 해서 주어, 목적어, 보어가 될 수 있을 뿐만 아니라, 관사, 형용사, 소유격 등의 수식을 받기도 하며, 복수형이 될 수도 있습니다.
      ex) Teaching requires tact.
            She avoided making any promise.
            Doing nothing is being idle.

2. 동사적 용법
1) ......
a. ......
ㄱ. .....
.
.
.

But when i write only 1) or 1. , it changed to list block automatically. So It become like that

1. 명사적 용법
    동명사는 명사적 기능을 해서 주어, 목적어, 보어가 될 수 있을 뿐만 아니라, 관사, 형용사, 소유격 등의 수식을 받기도 하며, 복수형이 될 수도 있습니다.
2.    ex) Teaching requires tact.
            She avoided making any promise.
            Doing nothing is being idle.

I can't delete 2. because it is in list block.

![cap 2018-10-19 15-30-46-256](https://user-images.githubusercontent.com/44285360/47201238-226ddf00-d3b4-11e8-9949-35b5e1a64ec3.png)

I want that 'ex)' part is on next line.

![cap 2018-10-19 15-30-48-591](https://user-images.githubusercontent.com/44285360/47201240-226ddf00-d3b4-11e8-9bd1-3ba4f6851dde.png)

but It become '4. ex)' automatically. I press enter and shift+enter. Same results.

![cap 2018-10-19 15-31-09-875](https://user-images.githubusercontent.com/44285360/47201241-23067580-d3b4-11e8-8ac0-aca4cc617c16.png)

So I have to make new block and copy and paste it.

![cap 2018-10-19 15-31-18-209](https://user-images.githubusercontent.com/44285360/47201242-23067580-d3b4-11e8-81f1-f6b92288fdf6.png)

Then It become good.

Do I have to make like that when I make list again and again???? I feel so angry about it. Please add that feature.

![cap 2018-10-19 15-42-33-884](https://user-images.githubusercontent.com/44285360/47201699-c441fb80-d3b5-11e8-8fcf-9dc7fbde55cb.png)
![cap 2018-10-19 15-44-43-769](https://user-images.githubusercontent.com/44285360/47201767-f2274000-d3b5-11e8-9786-aa1bba8f774e.png)

so amazing wow~~~

**Comment by youknowriad** [comment] 2019-02-11 12:36
So If I understand properly, this is a duplicate of #11215 ?

Let me know if I'm wrong.

**Closed by youknowriad** 2019-02-11 12:36 UTC
Labels: Blocks, [Block] List

**Comment by MYIG** [comment] 2019-02-11 12:43
hello youknowriad. i can't read english well. but i think it is almost same.

wow you guys read it now... i wrote it 4 month ago... you guys seriously rarely read feedback...

hmm okay. reading anyway and becoming gutenberg better and better is important. please make that feature. i still want 'disable auto block changing'

**Comment by iseulde** [comment] 2019-02-18 10:22
@MYIG Please be aware that we only have a limited amount of contributors and a huge amount of issues that get reported every day. This is an open source project.

Gutenberg 5.1 will add the ability to press shift+enter in lists so you can create new lines.

I believe the other issue is a duplicate of #13134. When you type `1. ` or `1) ` or `* `, the paragraph is converted to a list. You can undo this automatic behaviour by clicking the undo button or ctrl+Z or cmd+Z if you're on a Mac. However the space will be removed so it's broken. See #13134 where I'll attempt to fix the issue.

**Comment by iseulde** [comment] 2019-02-18 11:08
@MYIG I'm fixing the undoing of an automatic change to list block in #13917. Likely to be in Gutenberg 5.2. After this, you'll be able to undo the automatic change when you type `1. `.

**Comment by MYIG** [comment] 2019-02-18 17:36
@iseuldeI can't read English well but I think it is similar to #13134.

I understand you have many issues. but I want that you understand me too. I write it 4 months ago but it didn't fix yet. whenever gutenberg is updated, I read patch note and search my feedback but no result... so i give up. I really want Gutenberg become better and better.
