### ISSUE TITLE
Innerblock not being restricted within groups

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#48311] opened 2023-02-22 12:43 UTC
### Description

I am trying restrict the blocks that are available inside a group block, when I create a template for my innerBlocks.
I have tried the below, but this does not seem to work. Also the ALLOWED_BLOCKS does not work inside the group block either. All blocks are available to me for selection inside the group block.

```
	const ALLOWED_BLOCKS = ['core/group', 'core/image', 'core/paragraph', 'core/heading'];
	const MY_TEMPLATE = [
		['core/group', { lock: { 'move': true, 'remove': false }, allowedBlocks: ['core/heading'] }],
	];

	return (
		<div {...useBlockProps()}>
			<InnerBlocks
				allowedBlocks={ALLOWED_BLOCKS}
				template={MY_TEMPLATE}
			/>
		</div>
	);
```
	
Is this a bug? 

I already created a ticket on the WordPress forum here: https://wordpress.org/support/topic/gutenberg-set-allowedblocks-for-the-core-group-block/, but did not get a reply, so hoping this will go quicker.

### Step-by-step reproduction instructions

1. Create a simple block with npx create-block
2. Edit the block to use a template as above
3. Add a block inside the group. You will see all blocks are available for selection.

### Environment info

Latest WordPress and Gutenberg at time of writing.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment] 2023-03-27 06:48
This is still a valid issue. Would be great if anyone would find the time to look at it.

**Comment by landwire** [comment] 2023-04-03 09:02
Hi there, will anybody look at this in the near future?

**Comment by glendaviesnz** [comment] 2023-04-12 22:34
I was able to replicate this issue. Currently, a group block specified in a template ignores the `allowedBlocks` setting.

**Comment by landwire** [comment] 2023-05-09 16:39
Hi @glendaviesnz
thank you for replicating the problem.
Do you know if anybody will look at this issue?

**Comment by glendaviesnz** [comment] 2023-05-10 04:54
I am not sure where this sits in the priorities at the moment, or whether there is some intentional reason why the core Group block behaves like this, but I will try and take a closer look sometime next week to try and at least work out what might be required to fix it.

**Comment by landwire** [comment] 2023-05-10 06:51
That's great. For me it is absolute essential that in certain scenarios the user does not have full access to all the blocks. It just makes it so much easier and manageable from a point of UI for the user to create content for certain blocks/areas, where the full selection of blocks is not needed.

**Comment by landwire** [comment] 2023-05-31 09:31
As far as I know this has been resolved with a recent update of the Gutenberg plugin.

**Comment by t-hamano** [comment] 2023-09-10 02:13
I, too, have not been able to reproduce this issue with the latest Gutenberg, and it works as expected both with the `useInnerBlocksProps` hook and with the `InnerBlocks` component.

Perhaps this is due to the fact that the Group block did not originally have `allowedBlocks` attribute. The attribute was added in #49128 after this issue was submitted.

**Closed as completed by t-hamano** 2023-09-10 02:13 UTC
Labels: [Type] Enhancement, [Feature] Nested / Inner Blocks, [Block] Group
