### ISSUE TITLE
[Widgets editor] TypeError: Cannot read property 'body' of null at onLoad

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#34164] opened 2021-08-19 10:00 UTC
### Description

In some scenarios – and I am not sure which ones – the legacy widget preview results in an error `TypeError: Cannot read property 'body' of null at onLoad`. Stack trace points to the following line:

https://github.com/WordPress/gutenberg/blob/253d9b6e2123a2806b8843562f3f37de186c933a/packages/widgets/src/blocks/legacy-widget/edit/preview.js#L110

The problem occurs both in customizer and on widgets.php

### Step-by-step reproduction instructions

1. Be a lucky owner of an affected site – I am not sure how to reproduce the pre-conditions, but there are no custom plugins or themes involved
2. Go to customizer or the widgets editor
3. Observe the error

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by adamziel** [comment] 2021-08-20 13:37
There are two possibilities here:

1. `event.target` is somehow not an iframe 
2. `event.target` is an iframe, but `contentDocument` is null

According to the [HTML Living Standard](https://html.spec.whatwg.org/multipage/browsers.html#concept-bcc-content-document):

```
The content document of a browsing context container container is the result of the following algorithm:

* If container's nested browsing context is null, then return null.
* Let context be container's nested browsing context.
* Let document be context's active document.
* If document's origin and container's node document's origin are not same origin-domain, then return null.
* Return document.
```

My guess is that the `nested browsing context` is not null because it was just populated, which leaves us with just one possibility: `<iframe src="" />` points to a different origin than the document's origin. If so, this problem should be fixed by switching to `<iframe srcdoc="" />` populated via `apiFetch()`: https://github.com/WordPress/gutenberg/pull/34184

**Comment by noisysocks** [comment] 2022-02-21 07:01
> If so, this problem should be fixed by switching to `<iframe srcdoc="" />` populated via `apiFetch()`: #34184

@adamziel @anton-vlasenko: Did we ever do this?

**Comment by noisysocks** [comment] 2022-02-21 07:05
> > If so, this problem should be fixed by switching to `<iframe srcdoc="" />` populated via `apiFetch()`: #34184
> 
> @adamziel @anton-vlasenko: Did we ever do this?

Looks like it's tracked in https://github.com/WordPress/gutenberg/issues/33540..

**Comment by ndiego** [comment] 2022-08-02 14:56
@noisysocks and @adamziel this issue came up in our weekly Editor Bug Scrub and I just wanted to check in. Seems like work on the Legacy Widget block has stalled? Just curious if this is an issue we are actively planning to fix, or if it can be closed as a "[Status] Not Implemented".

**Comment by noisysocks** [comment] 2022-08-03 01:25
I don't believe anyone is working on this, no. If we're struggling to reproduce this and not hearing many reports from users then I'd be happy to close.

**Comment by ndiego** [comment] 2022-08-09 14:18
Thanks for the follow-up @noisysocks. We reviewed it again during this week's Editor Bug Scrub, and the consensus was to close this ticket.

**Closed as completed by ndiego** 2022-08-09 14:18 UTC
Labels: [Type] Bug, Needs Testing, [Block] Legacy Widget
