### ISSUE TITLE
Sign $ in attributes values

### ISSUE THREAD

**Issue by Alexus450** [WordPress/gutenberg#40154] opened 2022-04-07 14:20 UTC
### Description

Once I am adding the sign $ in the attiributes values it makes to disappear content after the point I inserted that sign. I am assume it needs to be serialize, but it doesn't.

### Step-by-step reproduction instructions

I used the recipe card block plugin, and it has the ingredients, based on gutenberg attributes. Everywhere I inserted the sign $ or $30 it makes the content disapear. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment] 2022-04-07 14:25
Hi, @Alexus450

Can you share the code that defines attributes or the plugin?

**Comment by Alexus450** [comment] 2022-04-07 14:39
Sure I am using this plugin https://wordpress.org/plugins/recipe-card-blocks-by-wpzoom/ and if you add anywhere the the sign $ and digits after like so $300, it disapears

**Comment by talldan** [comment] 2022-04-08 08:17
@Alexus450 Have you tried reaching out to the plugin developers about the problem?

I can't reproduce any issues using $ in any other blocks, so I'm not sure that this is related to the block editor, but perhaps instead that specific plugin.

**Comment by Alexus450** [comment] 2022-04-12 11:34
@talldan the issue appears only if the sign $ and a digit are inputted in the attributes values. Not in the content of the block itself

**Comment by talldan** [comment] 2022-04-13 00:48
@Alexus450 That is what I tested and it wasn't a problem. I'd recommend reaching out to the plugin developers. I'll close this issue.

**Closed as not planned by talldan** 2022-04-13 00:48 UTC
Labels: Needs Technical Feedback
