### ISSUE TITLE
Editor screen is blank after making a page a child page of a parent page

### ISSUE THREAD

**Issue by davedenis** [WordPress/gutenberg#9591] opened 2018-09-03 18:59 UTC
**Describe the bug**
Editor screen is blank after making a page a child page of a parent page.
Possible dupe or related to #8534 and #8455.
Gutenberg Version: 3.7.0

**To Reproduce**
1. Go to page.
2. Click on Page Attributes -> Parent and select a page.
3. Page loads with just the top and left nav and blank body.
4. It is possible to load the page under Classic Editor, change the page back so it is no longer a child page and it will work again.

**Expected behavior**
Gutenberg editor expected to load.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Browser: Chrome 68.0.3440.106
 - Gutenberg Version: 3.7.0

**Comment by ianbelanger79** [comment] 2018-09-04 18:52
Hi @davedenis,

Thanks for your report. However, I am unable to recreate the issue. I am using GB 3.7, Chrome 68.0.3440.106 and Windows 10 OS. I'm not sure why this would work on Windows and not on a Mac. I will see if someone else with a Mac can test this. @0aveRyan or @earnjam could you test this on your Mac's?

**Comment by davedenis** [comment] 2018-09-04 19:40
I can confirm Classic Editor loads fine. It's only when I switch to Gutenberg on a page that has been moved to a child page. I thought it was maybe a permalink issue.

**Comment by designsimply** [comment] 2018-09-18 19:26
I tested loading a child page using Chrome on macOS and I was unable to see the problem described.

![screen shot 2018-09-18 at 1 19 04 pm](https://user-images.githubusercontent.com/1119271/45711164-eaba1000-bb45-11e8-8cb1-ff190e9267ec.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14775&action=edit using Chrome 69.0.3497.92 on macOS 10.13.6.</sup>

> Click on Page Attributes -> Parent and select a page.

To confirm, does the problem only happen when you make a change such as selecting a parent page or does the problem also happen if you re-open a page that already has a parent page set?

> Page loads with just the top and left nav and blank body.

Are you able to check the web console in your browser developer tools to see if any error messages appear there at the time you see the blank screen happen?

**Comment by designsimply** [comment] 2018-09-18 19:28
> I thought it was maybe a permalink issue.

Is the problem only happening for certain parent/child combinations or does it happen for any child page?

**Comment by Keized** [comment] 2018-09-27 08:44
Hi 

I have the same problem  for any child page, 
I have this javascript error : 

> TypeError: Cannot read property 'models' of undefined : react-dom.min.82e21c65.js:110 TypeError

> Uncaught (in promise) TypeError: Cannot read property 'models' of undefined : index.js?ver=1538037426:1

**Comment by youknowriad** [comment] 2018-11-26 18:09
I can't reproduce this. I'm going to close this as state. Let's reopen if we find reproducible steps to investigate more. Thanks.

**Closed by youknowriad** 2018-11-26 18:09 UTC
Labels: [Status] Needs More Info, [Type] Help Request
