### ISSUE TITLE
Fatal Error on post listing in Admin Panel

### ISSUE THREAD

**Issue by 1naveengiri** [WordPress/gutenberg#4908] opened 2018-02-07 05:26 UTC
## Issue Overview
I have clone GitHub repo https://github.com/WordPress/gutenberg and activated the plugin. 
I can see a fatal on post listing page in admin panel. 
![screen shot 2018-02-07 at 10 50 04 am](https://user-images.githubusercontent.com/24760592/35899835-ba9cde76-0bf4-11e8-843f-c8b1695846fd.png)

## Steps to Reproduce (for bugs)
1. clone GitHub repo https://github.com/WordPress/gutenberg 
2. change to master branch
3. activate plugin Gutenberg using WP-CLI
4. You will see a message in admin header 
![screen shot 2018-02-07 at 10 46 48 am](https://user-images.githubusercontent.com/24760592/35899762-3fb02434-0bf4-11e8-86a9-152f3405aab1.png)

5. don't follow the instruction and check post listing page in backend click on `Post ` tab in Admin menu bar.
6. you will see 
![screen shot 2018-02-07 at 10 50 04 am](https://user-images.githubusercontent.com/24760592/35899835-ba9cde76-0bf4-11e8-843f-c8b1695846fd.png)

I am running latest version of WordPress 4.9.4 and Gutenberg version 2.1.0 
from GitHub repository. 
I didn't get this error when running using gutenberg plugin from wordpress.org.

## video link 
https://drive.google.com/file/d/1tWDPqfHSa44K2ERFb1dvkMql8t-R0g6J/view

## Expected Behavior
it should not show Fatal error in the master branch, even if it development version of Gutenberg.

**Comment by Soean** [comment] 2018-02-07 12:54
@1naveengiri I can't reproduce the error. Looks like gutenberg can't find the `gutenberg_can_edit_post_type()` function from `/lib/register.php`. Can you make a `git pull` an check if the error is gone?

**Comment by 1naveengiri** [comment] 2018-02-07 13:02
I have just checked it with fresh WordPress setup and with the latest code of master branch. 

FYK I haven't gone through the setup required for running Gutenberg like node and other things.
this is the simple step I have taken, I have cloned master branch and got this Fatel on the page mention in video.

**Comment by Soean** [comment] 2018-02-07 13:26
Ah okay, if you use the GitHub development version, you need to run `npm install` and `npm run build`, otherwise you can't use it.
This version is for development. As you mentioned, there is a message and a link to the instructions. If you just want to test Gutenberg and don't want to compile anything, you can use the version from the WordPress Plugin Directory.

This is not a bug,. If you run the dev version, you have to build the JS files. So I close your issue.

**Comment by 1naveengiri** [comment] 2018-02-07 13:28
but instead of returning Fatel, can't we show some message or warning? 
It would be much better even though it is development version.

**Comment by Soean** [comment] 2018-02-07 13:47
I don't think it's necessary, because a message is already displayed when you activate the dev version.

This is how it can be solved:
To avoid this fatal error, all `add_action()`-calls in gutenberg.php have to be in the `gutenberg_pre_init()` function.

**Comment by designsimply** [comment] 2018-10-16 16:54
First, I am noting the error from the screenshot in plain text for reference:

> Fatal error: Uncaught Error: Call to undefined function gutenberg_can_edit_post_type() in /srv/www/verkada/wp-content/plugins/gutenberg/gutenberg.php:399

@1naveengiri some time has passed and many changes have been made since this issue was originally filed and because the development environment has an admin notice with links stating what to do and the build tooling is working if the instructions are followed, I think we should close this issue. I also want to note that making the development environment easier to setup is something on developers minds and your feedback is appreciated—I am closing this issue for now because the current focus is on bug fixing prior to merge but also would like to note that we can re-visit this at a later time. Thank you!

@mintplugins I noticed you solved your issue using `rm -rf node_modules && npm install` as noted at https://github.com/WordPress/gutenberg/issues/9474#issuecomment-420107785 👍

**Closed by designsimply** 2018-10-16 16:54 UTC
Labels: Build Tooling, [Type] Enhancement

**Comment by mrmoret** [comment] 2019-03-22 04:09
Same problem and i can't resolve. Any ideas?
Elementor 2.5.9
Elementor Pro 2.4.8
Gutenberg 5.3.0

**Comment by designsimply** [comment] 2019-04-03 08:02
@mrmoret since this issue is specifically about getting set up with the build tooling you should first test without any additional plugins such as Elementor installed. If you're having trouble with cloning the local GitHub repo for a local setup as described above, I suggest trying again carefully following the instructions starting at https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#getting-started and if you run into problems, check first with support to ask for help with troubleshooting steps to make sure you are on the right track. If you were still having trouble after that, I suggest opening a new issue including your specific testing steps and documenting the exact error you are seeing.
