### ISSUE TITLE
Reusable Blocks: Convert to Regular Block does not preserve nested blocks

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9278] opened 2018-08-23 16:14 UTC
## The issue
If you save a block containing nested blocks as a Reusable Block, then it works just fine as a Reusable Block. But if you try to convert an instance of that Reusable Block to a regular block, then the resulting regular block will not contain any of the nested blocks that the Reusable Block had.

## Steps to reproduce
1. Insert a Columns block.
2. Insert some other block into the Columns block.
3. Open the ellipsis (<kbd><samp>More Options</samp></kbd>) menu and choose <kbd><samp>Add to Reusable Blocks</samp></kbd>.
4. Finish naming and saving the Reusable Block.
5. Notice that the nested blocks are saved in the Reusable Block as expected.
6. Open the ellipsis menu again and choose <kbd><samp>Convert to Regular Block</samp></kbd>.
7. Notice that the nested blocks are gone.

## Expected behavior
Reusable blocks should preserve nested blocks when an instance is converted to a regular block.

## Related issues and PRs
- #5754
- #7453
- #8375

**Comment by designsimply** [comment] 2018-08-23 17:54
Tested and confirmed using WordPress 4.9.8 and Gutenberg 3.6.2 and noting that in my case the blocks were preserved but the content inside them was not. ([39s](https://cloudup.com/cRdOJMMjKKO))

**Comment by asadrahbar** [comment] 2018-09-18 19:28
Is anyone working on a fix for this? The issue also occurs when using the Atomic Blocks plugin's AB Container block. I would like to create reusable sections (ex: image with heading, paragraph, and button) that clients could drop onto a page and then edit the content, similar to how the Divi library works. The only workaround for now is to copy the HTML for the nested blocks, paste into an HTML block and then Convert to Blocks - obviously not ideal for users who are afraid of code.

**Comment by slimmilkduds** [comment] 2018-09-19 12:45
@asadrahbar with 3.9 you will be able to create reusable blocks containing multiple blocks without a section block, hopefully someone will pick this issue up soon since that feature goes from being amazing to pretty useless with this bug present

**Comment by riemerta6** [comment] 2018-10-19 01:16
I'm also experiencing the same issue :/ Learned the hard way.

**Comment by noisysocks** [comment] 2018-10-29 05:52
> Likely the same root cause as #5754.

After looking into this some more, I think that this is a seperate bug caused by not passing `referencedBlock.innerBlocks` here:

https://github.com/WordPress/gutenberg/blob/308f6aa950705531ef9d360dc88bb9f4194542f5/packages/editor/src/store/effects/reusable-blocks.js#L240

**Closed** 2018-10-30 07:54 UTC
Labels: Reusable Blocks, [Component] Nested / Inner Blocks, [Type] Bug
