### ISSUE TITLE
Pasting into the title field from a spreadsheet cell causes new table block to be created

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27219] opened 2020-11-24 07:22 UTC
**Original report by bhkh:**
https://core.trac.wordpress.org/ticket/51314

**To reproduce**
1. Add new page from spreadsheet (external program like libre office) copy the contents of a cell that is to become the page title
2. Paste (using ctrl-v or ctrl-shift-v) into the page title field on the new page

**Expected Result**
Text of the copied cell would become the title of the page.

**Actual Result**
Instead of pasting the text of the cell (as it had done prior to 5.5) it skips away from the title title field and instead creates a one cell "table" block on the body of the page. Title field remains empty.

[Related support topic](https://wordpress.org/support/topic/copy-from-spreadsheet-cell-into-page-title-does-not-work/#post-13408178)

**Editor version:**
- WordPress version: first checked in 5.5.1, and still in 5.6 RC1
- Gutenberg plugin: 9.4.1

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 83

**Comment by sabernhardt** [comment] 2020-11-24 07:23
It seems to be related to PR #21758

Also, I can use Ctrl-Shift-V to paste as plain text within a paragraph block, but it does not paste at all for me in the title block.

**Comment by talldan** [comment] 2020-11-24 08:41
Thanks for moving this one to the right place.

I couldn't reproduce the issue using google sheets, which I think means that Libre Office is copying the content as a table when a single cell is copied, while google sheets only does this when more than one cell is selected and copied.

Given there's a lot of nuance in how external applications treat the content, I wonder how much value there is in solving this. The feature introduce in #21758 is really useful for the majority of use cases. Keeping that and fixing this would require special detection of a single-celled table being pasted into the title, which seems very intricate for what seems like something that would happen quite rarely. There's also the option of copying from the text from the function input field in the spreadsheet, which is a decent workaround.

> Also, I can use Ctrl-Shift-V to paste as plain text within a paragraph block, but it does not paste at all for me in the title block.

I see this too, and it seems more like a valid issue.

**Comment by annezazu** [comment] 2023-07-19 19:07
I can't replicate this with 6.3 RC1 with Google Sheets: 
https://github.com/WordPress/gutenberg/assets/26996883/7e4caf1c-7492-4d0b-b8ca-7b3e03eb3f4a

However, I could replicate using Libre Office with the recent download of 7.5 if you select the entire cell rather than just the content. 

I'm going to close this out at this point though because it does seem like there's a solid workaround (selecting just the content rather than the entire cell) and the lack of widespread problems with other external softwares (seems specific to Libre). 

Happy to reopen though if folks can provide more context and more examples! Right now, this just seems like a won't fix for an edge situation.

**Closed by annezazu** 2023-07-19 19:07 UTC
Labels: [Feature] Raw Handling
