### ISSUE TITLE
Extra click to add an image

### ISSUE THREAD

**Issue by jancavan** [WordPress/gutenberg#7296] opened 2018-06-12 21:41 UTC
**Is your feature request related to a problem? Please describe.**
We provide a quick access button to be able to add an image:

![screenshot 2018-06-12 14 36 31](https://user-images.githubusercontent.com/4924246/41318694-07f60696-6e4e-11e8-934d-89d11010b0f8.png)

An image icon, in general, when in a wysiwyg editor, represents "insert image". Therefore, at first glance, I thought that clicking on it would allow me to insert an image directly into my empty block. However, what it did instead was convert my text block into an image block.

I think this is confusing because when a user clicks on this, what they're telling us is, "I want to add an image". Yes, eventually, a user will learn it, but it's one of those little things where it shouldn't require an extra click (click on "add image" --> then click on upload) just to be able to insert an image. It also kind of defeats the purpose of making it a "quick access" button.

**Describe the solution you'd like**
Allow users to insert an image into their empty block when clicking on the "add image" icon. This should just immediately pull up their file manager. 

So essentially, we're converting it into an image block for them after they upload their image .

**Comment by SuperGeniusZeb** [comment] 2018-06-13 14:06
Related: #4108.

**Comment by danielbachhuber** [comment] 2018-06-14 13:12
> Allow users to insert an image into their empty block when clicking on the "add image" icon. This should just immediately pull up their file manager.

What if the intended behavior is that they want to choose an image from the media library?

**Comment by jancavan** [comment] 2018-06-15 03:48
> What if the intended behavior is that they want to choose an image from the media library?

That's a good point. I think the PR #4108 helps address this issue. This way, if you intend to pick images from the Media Library, you're presented with your thumbnails immediately instead of having to click the "Media Library" button.

But maybe instead of having two tabs (Media Library and Upload Files), the first box can be a way for you to drag and drop your files in. Clicking on it (and the entire box) will bring up the file manager. Something like (note that this is a very quick mockup):

![media-library](https://user-images.githubusercontent.com/4924246/41449029-6c67e8da-7013-11e8-86b6-c6d8499afc10.jpg)

The area you could drop images into is, of course, not limited to just that box, but you can drag files onto the entire block as well.

On another note, I think you should be able to drop images into the entire editor as well without having to create an empty block for it first.

cc @jasmussen

**Comment by danielbachhuber** [comment] 2018-06-15 11:45
Flagged as `Needs Design Feedback` to see if this is a change we want to make or addressed by something already in the works.

**Comment by jasmussen** [comment] 2018-06-19 06:52
I will defer to the project leads, @mtias and @karmatosed for final call on whether this is a Gutenberg V1 features. My personal opinion is that #4108 is the right solution to this issue, keeping the block-based nature of the editor in mind. But I also don't know that we have time to implment this before feature freeze.

**Comment by mtias** [comment] 2018-06-19 12:29
> the first box can be a way for you to drag and drop your files in

This is possible already on the image placeholder element. The addition to that would be to expose recent images, but other than that, it works as described above.

> On another note, I think you should be able to drop images into the entire editor as well without having to create an empty block for it first.

You can drag an image into the writing area now, it should already work. You don't need an image block to drag a media file. If you drag multiple items you should be able to build a gallery, etc.

All in all, the image button above is just like any other block. There was a point where we also opened the media library when you clicked on that button, but it wasn't a great experience, and it wasn't clear why we would break consistency just for the image block.

Since there are multiple ways in which a user might choose to add an image (from their library, from their local files, from a URL on the web, etc) we can't make an assumption. The block placeholder would be the perfect place to expedite those interactions, and the only piece it misses is showing some recent media.

**Closed by mtias** 2018-06-19 12:29 UTC
Labels: Needs Design Feedback, [Status] Needs More Info
