### ISSUE TITLE
Gutenberg editor is crashing

### ISSUE THREAD

**Issue by nicopujol** [WordPress/gutenberg#14885] opened 2019-04-09 17:27 UTC
**Describe the bug**
Today the editor is crashing within 20 seconds of being open. Attaching a screen shot and error message. Nothing appears to have changed in the configuration, except that I had the gutenberg plugin active and deactivated it, since it is now part of WordPress core. Not sure this is related as the error message states "jetpack/business-hours"

TypeError: Cannot read property 'jetpack/business-hours' of undefined
    at zn (https://www.nicolaspujol.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45280)
    at https://www.nicolaspujol.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:46071
    at Array.map (<anonymous>)
    at https://www.nicolaspujol.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:45906
    at u (https://www.nicolaspujol.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:12:3427)
    at https://www.nicolaspujol.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:6379
    at https://www.nicolaspujol.com/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:109194
    at n (https://www.nicolaspujol.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13036)
    at new r (https://www.nicolaspujol.com/wp-includes/js/dist/data.min.js?ver=4.2.1:1:13298)
    at zf (https://www.nicolaspujol.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258)

**Screenshots**
![Gutenberg crashing](https://user-images.githubusercontent.com/1319146/55821301-ff460180-5ab1-11e9-81ea-1697fbf031b7.jpg)

**Desktop (please complete the following information):**
 - Device: X1
 - OS: Win 10
 - Browser Chrome
 - Version 73

**Additional context**
- WordPress 5.1.1

**Comment by aduth** [comment] 2019-04-09 18:49
It appears this is the same as #14580. Specifically, the error can occur when downgrading from Gutenberg v5.2.0 or v5.3.0 to WordPress 5.1.x . You should be able to resolve the issue by one of: Updating Gutenberg to v5.4.0, or by clearing your browser's local storage (for example, using `localStorage.clear()` in your browser's Developer Tools Console, or in many cases by clearing your browser's cache).

**Comment by aduth** [comment] 2019-04-09 18:49
Duplicate of #14580

**Closed by aduth** 2019-04-09 18:49 UTC

**Comment by nicopujol** [comment] 2019-04-09 18:51
Thanks!
