### ISSUE TITLE
Preview before Save Draft not show Featured image, Categories and Tag.

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7767] opened 2018-07-07 10:02 UTC
When create new post and assigned Featured image, Categories and tags, preview not show them until Save Draft first.

**Comment by designsimply** [comment] 2018-07-18 21:41
Tested and confirmed using the following testing steps:

1. Start a new post and give it a title and some content.
1. Select a category, add a tag, and add a featured image.
1. Click the "Preview" button.
1. Note that the category, tag, and featured image are not shown in the preview.
1. Close the preview.
1. Click the "Save Draft" button.
1. Click the "Preview" button.
1. Note that you can now see the category, tag, and featured image in the preview.

<strong>Result:</strong> category, tag, and featured images are not shown for draft previews unless the "Save Draft" button is explicitly. ([45s](https://cloudup.com/cQ3XanwJ5VW))

![preview-before-save-draft](https://user-images.githubusercontent.com/1119271/42909249-b6dc8554-8aa0-11e8-8c63-41ba1c5686d9.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14016&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

What is the intended behavior? (@youknowriad may I ask you? 😊)

**Comment by adamsilverstein** [comment] 2018-07-19 20:03
> Can I ask if it's a similar behavior in the classic editor?

Currently in the classic editor previews **do include all of the meta stored data**, _however a longstanding core bug_ means that **any changed meta is actually saved to the live post** when you perform the preview action (https://core.trac.wordpress.org/ticket/20299) although i think we fixed this for featured images recently.

**Comment by designsimply** [comment] 2018-07-19 20:14
@youknowriad, fwiw, it makes sense to me that previewing featured images should always work because that potentially changes the view on the front end dramatically. I don't feel strongly about categories or tags but they sound like nice-to-haves. 😊

**Comment by youknowriad** [comment] 2018-08-15 13:58
So I think we should close this as `invalid` because the fact that classic editor saves those meta is considered a bug per @adamsilverstein's comment and not sure revisions/autosave allows saving more values than the `content`/`title`/`excerpt`.

Please correct me if I'm wrong.

**Comment by youknowriad** [comment] 2018-08-16 13:48
I'm closing as invalid, if it's not please reopen ;)

**Closed by youknowriad** 2018-08-16 13:48 UTC
Labels: [Component] Saving, [Type] Bug
