### ISSUE TITLE
Gallery block Full/None alignment bug

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#7099] opened 2018-06-02 02:44 UTC
**Describe the bug**
Please see #7098 .
The Gallery block has the identical issue - alignundefined vs alignnone.

**Comment by designsimply** [comment] 2018-07-17 19:07
Closing as a duplicate of #7098 (which has also been updated to reflect that the same problem happens in more than one kind of block).

**Closed by designsimply** 2018-07-17 19:07 UTC
Labels: Block API, [Status] Duplicate, [Type] Bug
