### ISSUE TITLE
Chrome and Safari - leave this side?

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#3307] opened 2017-11-02 08:47 UTC
with 4.9-RC1-42105 and Gutenberg 1.6 Chrome and Safari shows this window "Leave this side?" after new post or update post and click to "View Post".

<img width="735" alt="bildschirmfoto 2017-11-02 um 09 35 21" src="https://user-images.githubusercontent.com/6922544/32317000-a0c61596-bfb2-11e7-8240-56a21fe9805b.png">

<img width="782" alt="bildschirmfoto 2017-11-02 um 09 39 58" src="https://user-images.githubusercontent.com/6922544/32317001-a0e4856c-bfb2-11e7-840e-ed0962a096a3.png">

**Comment by Soean** [comment] 2017-11-02 09:28
Maybe related to #3296

**Comment by GlennMartin1** [comment] 2017-11-02 13:01
Identical issue here. I'm using Chrome.

I'm running Gutenberg 1.6.1.
This issue started for me in 1.6.0.

**Comment by aduth** [comment] 2017-11-06 21:11
Duplicate of #3296. Should be resolved in the next release.

**Closed by aduth** 2017-11-06 21:11 UTC

**Comment by bradhogan** [comment] 2021-04-28 21:18
Still seeing this issue.  Any news on why this keeps happening?  Using Chrome (Version 90.0.4430.93) on a Macbook (Big Sur 11.2.3).   Thanks!
