### ISSUE TITLE
columns block inline problem

### ISSUE THREAD

**Issue by robbisy** [WordPress/gutenberg#6599] opened 2018-05-04 19:56 UTC
When I add an image block next to the first one it appears under it
![p1](https://user-images.githubusercontent.com/18592516/39649260-82a1c0ba-4fe5-11e8-8e21-b00420ec35b0.png)
![p2](https://user-images.githubusercontent.com/18592516/39649262-84258b74-4fe5-11e8-8c8e-56a05529bb68.png)

**Comment by theleemon** [comment] 2018-05-04 20:35
I can confirm this, too. Every block type, not only images.

**Comment by SuperGeniusZeb** [comment] 2018-05-04 23:07
Duplicate of #5772.

**Closed** 2018-05-05 08:54 UTC

**Comment by Soean** [comment] 2018-05-05 10:25
I can confirm this issue, the #5772 describes the same, so we close this issue.
