### ISSUE TITLE
Widgets editor - can't add or save

### ISSUE THREAD

**Issue by Simonsbs** [WordPress/gutenberg#27964] opened 2021-01-04 08:53 UTC
I'm trying to add a block to a widget area - but no matter what I do I get an error "There was an error. [object Object]"

**To reproduce**
1. Go to Design -> Widgets
2. Add a block to any area
3. Click Save
4. See an error in the bottom corner

**Expected behavior**
Save the changes made

**Screenshots**
![2021-01-04 10_09_12-וידג'טים › TechLab — וורדפרס](https://user-images.githubusercontent.com/1129815/103517407-b97ebe80-4e7a-11eb-8518-107c488d7720.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6
- using the block editor that comes by default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by bph** [comment] 2021-01-04 16:27
Is there an error message in the browser console? 
3-dot menu > More Tools > Developer Tools 
![Screen Shot 2021-01-04 at 11 26 12 AM](https://user-images.githubusercontent.com/39980/103556384-b508d480-4e7f-11eb-84ef-02480eb5c322.png)

The first tap is the "Console". It'll help to clear all previous error messages and refresh the page.

**Comment by Soean** [comment] 2021-01-04 21:42
I can reproduce the error, if I add a block to an empty widget area:

Request payload:
```JSON
{
   "id":"sidebar-1",
   "widgets":[
      null
   ]
}
```

Response:
```JSON
{
   "code":"rest_invalid_param",
   "message":"Invalid parameter(s): widgets",
   "data":{
      "status":400,
      "params":{
         "widgets":"widgets[0] is not of type object,string."
      }
   }
}
```

**Comment by annezazu** [comment] 2021-01-05 20:45
Ran into this today with Twenty Twenty theme and 9.6.2: https://cloudup.com/cdA49pgrb0N Marking this as a regression and adding to the project board for widgets to get more attention!

**Comment by annezazu** [comment] 2021-01-05 21:54
@tellthemachines kindly pointed out to me that this is a duplicate of https://github.com/WordPress/gutenberg/issues/27173 Going to close this out for now and defer to the original issue which has a bit more information.

**Closed by annezazu** 2021-01-05 21:54 UTC
Labels: [Feature] Widgets Screen, [Type] Bug, [Type] Regression
