### ISSUE TITLE
Editor styles are broken when a Google Font @import is included

### ISSUE THREAD

**Issue by andreiglingeanu** [WordPress/gutenberg#53509] opened 2023-08-10 07:59 UTC
### Description

When the editor style contains this line, it breaks the page entirely:

```
@import url('https://fonts.googleapis.com/css2?family=Lobster:wght@400;500;600;700&display=swap');
```

### Step-by-step reproduction instructions

1. Start with any classic theme
2. Put the code from down below in the `functions.php`
3. Observe the problem

```php
add_editor_style('some-style.css');
```

```css
@import url('https://fonts.googleapis.com/css2?family=Lobster:wght@400;500;600;700&display=swap');

:root {
	--test: red;
}
```

Result:

![CleanShot 2023-08-10 at 10 57 06@2x](https://github.com/WordPress/gutenberg/assets/2979628/a9c3edd2-af58-4387-9c2a-b67d8c581294)

Expected result:

```css
@import url('https://fonts.googleapis.com/css2?family=Lobster:wght@400;500;600;700&display=swap');

.editor-styles-wrapper {
	--test: red;
}
```

### Screenshots, screen recording, code snippet

This seems like a problem within the `block-editor/src/utils/transform-styles/transforms/wrap.js` file.

### Environment info

WordPress 6.3, a classic theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbirdsong** [comment] 2023-08-10 15:12
This also occurs when using an `@import` for Adobe Fonts/Typekit.

**Comment by jorgefilipecosta** [comment] 2023-08-14 15:33
Howdy @andreiglingeanu and @cbirdsong, much appreciation for flagging the problem. I delved into it and successfully replicated it. This glitch might impact the editor styles on many sites.

**Comment by jorgefilipecosta** [comment] 2023-08-14 16:04
The issue stems from a bug in the CSS parsing library we used:
https://github.com/reworkcss/css

It's feasible to reproduce this using:
```
const css = require('css');
const obj = css.parse(`@import url('https://fonts.googleapis.com/css2?family=Lobster:wght@400;500;600;700&display=swap');

:root {
	--test: red;
}`);
console.log(obj);
```
For instance, on npm runkit: https://npm.runkit.com/css.

Our task involves rectifying our local fork packages/block-editor/src/utils/transform-styles/ast/parse.js and submitting an upstream patch to ensure universal benefit from the fix.

**Comment by annezazu** [comment] 2023-12-19 15:16
@jorgefilipecosta what can be done to move forward on this? This issue is labeled high priority but has sat for a number of months. The high priority label should be used for important items that need quick attention. To help ensure these issues are actionable,[ I'm doing a sweep ](https://wordpress.slack.com/archives/C02QB2JS7/p1702996696603749)and wanted to check in here to ensure we close this promptly whether that's with your PR or bringing in others to help resolve.

**Comment by skorasaurus** [comment] 2023-12-19 17:34
@annezazu @jorgefilipecosta 
I don't think this is applicable as the reworkcss library has been replaced with PostCSS in https://github.com/WordPress/gutenberg/issues/40444 ; 

I'm unable to reproduce the error that @andreiglingeanu posted; i'm able to load the font in the editor as expected. 

(if I add the following to the css file enqueued by add_editor_style)
```
h2 {
    font-family: 'Lobster';
}
```
the heading block with h2 will use that font in the editor

note, the new result is: 

```

@import url('https://fonts.googleapis.com/css2?family=Lobster:wght@400;500;600;700&display=swap');

:root {
	--test: red;
}

```

(I believe the that root selector appearing instead of editor-styles-wrapper is now intentional;  cc @strarsis

**Comment by annezazu** [comment] 2023-12-19 17:44
!! Amazing triaging and diving in @skorasaurus. I'm going to proactively remove the high priority label from now but keep in mind we can always add in back in as this updated convo unfolds.

**Comment by andreiglingeanu** [comment] 2023-12-22 09:56
@skorasaurus I can re-validate the initial issue against the latest `trunk`, if it helps. But it all seems correct, judging from your comment.

**Comment by strarsis** [comment] 2023-12-26 18:23
> (I believe the that root selector appearing instead of editor-styles-wrapper is now intentional; cc @strarsis

The CSS variables should also be isolated by adding `.editor-styles-wrapper` to the selector (also when defined in root scope).

> I don't think this is applicable as the reworkcss library has been replaced with PostCSS in #40444 ;

🤔 Interesting, IMHO that CSS parser code was basically developed internally, and therefore replaced by a proper library.

**Comment by jorgefilipecosta** [comment] 2024-01-16 15:01
I verified this issue was fixed with the merge of https://github.com/WordPress/gutenberg/pull/49521.

**Closed as completed by jorgefilipecosta** 2024-01-16 15:01 UTC
Labels: [Type] Bug, [Status] In Progress, [Package] Style Engine, [Feature] Typography
