### ISSUE TITLE
[Android] Retrying a failed media upload after rotate never progresses. 

### ISSUE THREAD

**Issue by chipsnyder** [WordPress/gutenberg#24654] opened 2020-08-19 12:12 UTC
**Describe the bug**
This was discovered as part of the regression testing for 1.35.0 https://github.com/wordpress-mobile/WordPress-Android/pull/12709#issuecomment-675636800. 

On Android, if you rotate the device after a failed upload to any media block, then retrying the upload will never progress.

**To reproduce**
1. In Landscape mode, add a media block such as Image or Media Text
1. Tap on the block to bring up the upload options
1. Tap option ‘Choose from device’ and choose an image or video
1. Turn off internet connection and wait
1. You should see the retry message on the image thumbnail 
1. Rotate the device to portrait
1. Tap on the retry
1. You should be asked to retry
1. Tap retry
**Actual:** The image/video fails to upload

**Expected behavior**
The image/video should attempt to upload again and progress successfully.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10 API 29
 - https://github.com/wordpress-mobile/WordPress-Android/pull/12709#issuecomment-675636800

**Comment by geriux** [comment] 2020-09-18 09:57
After some investigation and tests, I thought it might be related to the media upload listeners on the JS side but I believe its more related to some cleaning that is done when the device goes to landscape / portrait.

Some rotation bugs were fixed by introducing [this](https://github.com/wordpress-mobile/WordPress-Android/pull/10383/files#diff-f0ac1208c376c229367ac274e0e32b2a) and [this](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2011/files#diff-f2e1dfe800569dfb4ee4830f88779890), so now I wonder if those changes are some how interfering with the media upload listeners that maybe get destroyed when rotating the device.

Also, once you rotate the device back to portrait, turn on the internet connection, tap on retry (it wont change the failed state) then if you close the post and go to media library you can see the failed file successfully uploaded, if you open the post, the media in the block will show correctly. So the issue is letting the editor know while it's opened that the media was uploaded correctly.

**Closed** 2021-03-16 06:52 UTC
Labels: Mobile App - i.e. Android or iOS, [Type] Bug
