### ISSUE TITLE
Backslash breaks block json attributes

### ISSUE THREAD

**Issue by emanuellopes** [WordPress/gutenberg#28795] opened 2021-02-05 17:54 UTC
## Description
I added an attribute on my guteneberg block, when I try to add this char \ in a richtext, the block breaks and I can recover them.

I need this attribute on json because I will use them in my block parser. 

## Step-by-step reproduction instructions
1. Create a block a add a new attribute
2. `content: {
    type: 'string' // this should be available on block parser!
}
`
3. add a backslash char to the Richtext block and save the article.
4. The block will break because \ char is not escaped and this produces a wrong JSON format.

## Expected behaviour
The backslash char should be escaped on variables.

```JS
export function serializeAttributes( attributes ) {
	return (
		JSON.stringify( attributes )
			// Don't break HTML comments.
			.replace( /--/g, '\\u002d\\u002d' )

			// Don't break non-standard-compliant tools.
			.replace( /</g, '\\u003c' )
			.replace( />/g, '\\u003e' )
			.replace( /&/g, '\\u0026' )

			// Bypass server stripslashes behavior which would unescape stringify's
			// escaping of quotation mark.
			//
			// See: https://developer.wordpress.org/reference/functions/wp_kses_stripslashes/
			.replace( /\\"/g, '\\u0022' )

			//escape attributes with backslash char
			.replace(/\\/g, '\\\\') //add this please
	);
}
```

## Actual behaviour
Backslash char on attributes breaks the block.

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: Not Installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: All devices
- Operating system: All
- Browser: All

**Comment by skorasaurus** [comment] 2021-02-05 18:42
Thanks for reporting. This may be a duplicate of https://github.com/WordPress/gutenberg/issues/16508 but before taking any action, I'll defer to others who are more experienced with the richtext component.

**Comment by emanuellopes** [comment] 2021-02-05 21:24
Thank You @skorasaurus, I added an example of my code. This is very similar to Gutenberg table block.

`//index
import {Component} from "@wordpress/element";
import {RichText} from "@wordpress/block-editor";

export const settings = {
	title: 'Sample',
	description: '',
	category: 'sample-category',
	attributes: { //This properties should be available on BlockParserBlock PHP
		body: {
			type: 'array',
			default: [],
			query: {
				cells: {
					type: 'array',
					default: [],
					query: {
						content: { //This content var is used in a RichText
							type: 'string',
							source: 'tag',
							selector: 'td,th',
						},
					},
				},
			},
		},
	},
	SampleEdit,
};

export class SampleEdit extends Component {
	render() {
		const { attributes } = this.props;
		const { body } = attributes;

		return (
			<td>
				{body.map(({ cells }, rowIndex) => (
					<tr key={rowIndex}>
						{cells.map(({ content }, columnIndex) => {
							<RichText
								tagName="td"
								key={columnIndex}
								value={content}
								onChange={this.onChange}
							/>
						})}
					</tr>
				))}
			</td>
		);
	}

	onChange(content) {
		//update content value
		// try escape the backslash but no success
		const escaped = this.stringEscape(content); // but doing this here don't work
	}

	stringEscape(s) {
		return s
			? s
				.replace(/\\/g, '\\\\')
				.replace(/\n/g, '\\n')
				.replace(/\t/g, '\\t')
				.replace(/\v/g, '\\v')
				.replace(/'/g, "\\'")
				.replace(/"/g, '\\"')
			: s;
	};
}
`

**Comment by Mamaduka** [comment] 2023-06-12 14:46
Hi, @dmsnell

This is the bug I mentioned during WCEU. You can use reproduction steps from https://github.com/WordPress/gutenberg/issues/16508#issuecomment-564856689 to test with the core block.

**Comment by Mamaduka** [comment] 2024-12-10 19:10
Closing as duplicate of #16508.

**Closed by Mamaduka** 2024-12-10 19:10 UTC
Labels: [Type] Bug, [Feature] Parsing, [Feature] Rich Text, [Package] Rich text
