### ISSUE TITLE
All those new paragraphs...

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#2466] opened 2017-08-18 22:52 UTC
So many New Paragraphs....

![screen shot 2017-08-19 at 00 43 10](https://user-images.githubusercontent.com/5323259/29480287-80d88a78-8477-11e7-907c-683820486fdd.png)

Don't hit that enter button multiple times.... or you might get this:

![attack-of-the-new-paragraphs](https://user-images.githubusercontent.com/5323259/29480447-aaf1d188-8478-11e7-9dd5-0550b2868022.gif)

We need to do something about all those blocks that show up like this....

**Comment by iseulde** [comment] 2017-08-20 15:11
Isn't this expected? You hit enter so many times, so you created so many new paragraphs.

**Comment by annaephox** [comment] 2017-08-21 02:39
This is a good example of the micro-overhead that is caused by the yet-to-be-massaged fine grained interactions (see #2279)

In this particular example, if 
- the new paragraph did not have placeholder text and/or 
- the paragraph decorations (toolbar, arrows/cog & trash) did not pop up on up-down arrow or mouseover

the interface would impose less cognitive load on the user

**Comment by nbertino** [comment] 2017-08-21 15:41
@annaephox I agree - on consecutive paragraphs, I think too much interface is introduced for such a simple content creation flow. Also, selecting text in multiple paragraph blocks selects the blocks themselves, not the text inside, which I think can be confusing. 

If these paragraphs need to be registered as blocks for proper rendering, then I'd suggest showing less of that to the user and making consecutive paragraphs more cohesive (e.g., Medium).

**Comment by nic-bertino** [comment] 2017-08-21 15:42
@annaephox I agree - on consecutive paragraphs, I think too much interface is introduced for such a simple content creation flow. Also, selecting text in multiple paragraph blocks selects the blocks themselves, not the text inside, which I think can be confusing.

If these paragraphs need to be registered as blocks for proper rendering, then I'd suggest showing less of that to the user and making consecutive paragraphs more cohesive (e.g., Medium).

**Comment by hedgefield** [comment] 2017-08-25 12:48
Aye, this is mechanically no different than what happens in the current editor, or Word for that matter. Every time you press enter, it creates a new `<p>`. The difference is that Gutenberg makes this structure visible, each with their own placeholder. That makes it seem very crowded. I agree with @annaephox that this can be fixed by tuning the little interactions.

**Comment by getsource** [comment] 2017-08-31 18:37
Also agreed. A user expects to be able to insert whitespace in a post, and in this case it appears to inserts content the user is not expecting. 

This caught me by surprise when writing a post as well.

**Comment by maddisondesigns** [comment] 2017-09-02 08:12
I'd like to know the decision behind making every single paragraph a new block. This is really annoying and the average page is going to end up with literally dozens and dozens of blocks.

Why can't we insert multiple paragraphs in to the one (Paragraph) block? It should be the users decision whether or not they want to insert a new block, not the editor.

With all these blocks, it's going to make moving content around the page really frustrating, and not mention, time consuming. Instead of being able to simply move a couple of paragraphs with a simple copy/paste, now we're forced to move multiple blocks, individually.

The Paragraph block should be changed so that we can enter as much (or as little) text as we want and it should be the users decision when to insert a new block. This single block for every paragraph is an absolute mess.

**Comment by hedgefield** [comment] 2017-09-02 09:05
You _can_ already move multiple paragraphs, and cut/copy-paste them.

![paragraphs](https://user-images.githubusercontent.com/6073772/29994328-adeddc78-8fcd-11e7-83d3-a6294ea019ab.gif)

Again, these separate paragraphs, it's functionally no different from how the current editor works, _behind-the-scenes_. The only difference is that we can _see_ the structure here, visually, as blocks, and that alters our perception of how to work with the text. Something for the UX team to take into consideration. But the move arrows are not the only way to edit text. Ctrl+A, Ctrl+X, Ctrl+C, Ctrl+V, drag to select, it's all there.

**Comment by maddisondesigns** [comment] 2017-09-02 14:42
@hedgefield That's good to know. Thanks. I wasn't aware that Ctrl+X/C/V actually worked on multplie blocks like that. The Arrows keys don't currently work like in your gif though. After selecting multiple blocks, clicking the Down Arrow simply inserts the cursor in the first block.

It's still annoying that your page is going to end up with so many separate paragraph blocks though. And I still believe that it should be the end users choice whether or not to insert a new block, rather than Gutenberg forcing it on you.

**Comment by karmatosed** [comment] 2017-09-07 08:20
I'm going to add this feedback from a user who left a review. I think it adds a view point to this conversation worth considering:

> Sometimes I’m not sure when I’m drafting whether I’m going to flush out a thought into a full paragraph or just leave it as bullets. I write in the bullets and maybe come back and write more or maybe just highlight all of them and choose “list”. But currently a carriage return makes a new block and you can’t multi-select blocks… Ugg.

https://wordpress.org/support/topic/the-key-issue-is-blocks-not-everyone-thinks-that-way/

**Comment by jasmussen** [comment] 2017-11-21 11:51
Although I can see that this can be frustrating if you intend to use an empty paragraph block for space, for now this is the intended behavior, and the spacing issue should probably be fixed separately. Given the improvements we've since made in cross-block list-making and multi selection using both keyboard and mouse, I'm going to close this. 

We should never be afraid to close tickets, because it's easy to reopen them, and/or create new ones, should the issue, or a variant of it, be relevant again.

**Closed by jasmussen** 2017-11-21 11:51 UTC
Labels: [Type] Question

**Comment by maddisondesigns** [comment] 2017-11-22 01:56
I've bought this up in multiple tickets. Creating a new block EVERY TIME you hit enter, is going to make your page an absolute mess with blocks. You should be able to put multiple paragraphs of text into a single block. It should be up to the user to decide when they want to create a new text block, instead of Gutenberg forcing all these tiny single-paragraph blocks on us. Having hundreds of tiny single-paragraph blocks for a page that's primarily text, is not making the editor a better user experience.

**Comment by paaljoachim** [comment] 2017-11-22 09:33
There is too much focus on creating blocks. There should be a lot more focus on the writing process. Simplifying how the UI/UX is put together. Looking at issues such as:
1. How can we simplify?
2. Is the focus on writing or on adding a block?
3. Is it a multiple step process? If so what are some ideas on making it simpler?
4. If we just focused on writing what changes would we make?

Bottom line is this: When I write I focus on the flow the meaning I want to get across and not on the individual letters themselves.

**Comment by karmatosed** [comment] 2017-11-22 10:57
It is important to take time to think beyond what we do. I see a lot of you saying how you do the process @paaljoachim, as we enter into a time of usability testing, I would encourage you to join in with that and observe some users. Right now we need to as a project do this. We need to put our headspace to one side, observe, digest the insights and then if needed act and iterate.

**Comment by robmcclel** [comment] 2018-01-11 21:54
The problem here is basic:  Each piece of text is a block.  It should not be this way.

Blocks are things that get inserted into text, they should not be the actual elements of the text.  Making individual paragraphs, lists, headings, block quotes, etc all unique and different types of blocks is madness.  Seriously, it is madness.  You will never get this UI/UX under control until the block concept is reigned in and dealt with.

Stop thinking about Medium and Wix and think about actual document creation.  Composing in WordPress should be as simple and intuitive as writing in MS Word or Google Docs.  That is the direction an editor should be heading.  That is the interface to be emulated, not Medium.
