### ISSUE TITLE
Dragging a .flac file into the editor creates a File block instead of an Audio block

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8863] opened 2018-08-11 04:16 UTC
## The issue
Dragging an image (`.png`, `.jpg`, `.gif`) into the editor creates an Image block. Dragging multiple images into the editor creates a Gallery block. Dragging a video (.webm, .ogv, .ogg) into the editor creates a Video block.

However, dragging a `.flac` file into the editor does _not_ create an Audio block. Instead, it creates a File block.

## Steps to reproduce
1. Drag a `.flac` file into the editor.
2. Notice that a File block is created, rather than an Audio block.

## Expected behavior
Dragging a `.flac` file into the editor should create an Audio block.

## Related issues and PRs
- #8861
- #8862
- #8864

**Comment by designsimply** [comment] 2018-08-14 05:08
Closing as a duplicate of #8020.

**Closed by designsimply** 2018-08-14 05:08 UTC
Labels: Blocks, [Status] Duplicate, [Type] Enhancement
